### ISSUE TITLE
Activities messages are too wide

### ISSUE THREAD

**Issue by JakeRadMSFT** [Microsoft/AzureStorageExplorer#1]
**Storage Explorer Version:** 0.9.6

**OS Version:** Windows 10

**Steps to Reproduce:**
1. Download File with long path.

**Expected Experience:**
Message spans multiple lines.

**Actual Experience:**
Need to scroll to the right to view the full message.

**Comment by MRayermannMSFT** [comment]
Will be fixed in v1.0.0

**Comment by michaeldaw** [comment]
Huge improvement. Thanks guys.
