### ISSUE TITLE
Update 'Rename' to 'Rename...' on file context menu

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#1000]
Storage Explorer Version: 1.6.1
Platform/OS Version: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
Architecture: ia32
Build Number: 20181211.1
Commit: 2455da61
Regression From: Not a regression

#### Steps to Reproduce: ####
1. Expand an account -> Open a blob container which at least contains one blob.
2. Right click the blob -> Check the context menu.

#### Expected Experience: ####
Show '**Rename**...' in the context menu.

#### Actual Experience: ####
Show '**Rename**' in context menu.
![image](https://user-images.githubusercontent.com/41351993/49861181-44289700-fe36-11e8-833b-4049f9603b6c.png)

**More Info:**
 This issue also reproduces on files/directories context menu.

**Comment by v-xianya** [comment]
Verified with build 20181219.2. This issue also reproduces for files under file share. So reopen it.

**Comment by craxal** [comment]
This has already been addressed for file shares. Closing again.

**Comment by v-xuanzh** [comment]
Hi @craxal ,this issue still happens on **files context menu**. So reopened it again. :(
![image](https://user-images.githubusercontent.com/34729022/50818008-abb40280-1360-11e9-8752-8c1ee9a128da.png)

**Comment by MRayermannMSFT** [comment]
Updated title...
