### ISSUE TITLE
Folder statistics in virtual folder does not append '/'

### ISSUE THREAD

**Issue by CoenraadS** [microsoft/AzureStorageExplorer#1001]
**Storage Explorer Version**: 1.6?
**Platform/OS**: Windows?
**Architecture**:
**Regression From**: Broken in all versions

**Bug description**
container/1/foo.txt
container/11/bar.txt

Go to the virtual folder `1` and use folder statistics. Result = 2 blobs, because it lists `container/1` instead of `container/1/`

**Comment by CoenraadS** [comment]
Note, you have to be in the parent folder, click the child folder (but don't go in it), then use folder statistics.

If you go into the folder and use it then it works correctly. Just encountered this again today..

**Comment by JasonYeMSFT** [comment]
We have made sure that when performing FolderStatistics, the folder name used as prefix will end with a trailing slash while supporting <no_name> blobs/folders. That ends up fixing this issue.
