### ISSUE TITLE
Show an incomplete log message when downloading a file 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1003]
**Storage Explorer Version**: 1.6.1
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181213.1
**Commit**: 4ca2a5cb
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Expand an account -> Open one file share -> Upload a file to this file share.
2. Download the uploaded file in step1.
3. Check the download log messages in 'Activities'.

#### Expected Experience: ####
Log message shows as 'Downloaded **file/directory** from......'

#### Actual Experience: ####
Log message shows as 'Downloaded **file** from......'
![image](https://user-images.githubusercontent.com/41351993/49926191-ff643500-fef5-11e8-87e2-16adbc80c602.png)

**More Info:**
This issue also reproduces when downloading a directory which contains only one file.

**Comment by johnliu2016** [comment]
This isn't looking like a localization issue, but a suggestion to English.

Here's the string info:
ID: MessageFileDownloadedSingle
ENU: Downloaded file from '%s' to '%s'
Expected: Downloaded file/directory from '%s' to '%s'
