### ISSUE TITLE
Should show 'folder' rather than 'directory' for the log message when creating an existing ADLS Gen2 blob folder

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1004]
**Storage Explorer Version**: 1.6.1
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181213.1
**Commit**: 4ca2a5cb
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Expand one ADLS Gen2 account -> Blob Containers node.
2. Open one blob container -> Create a new folder with the default name 'New Folder'.
3. Create the same folder again with the name 'New Folder' -> Check the failed log message on Activities.

#### Expected Experience: ####
The log message shows 'Failed to create **folder** '/New Folder''

#### Actual Experience: ####
The log message shows 'Failed to create **directory** '/New Folder''
![image](https://user-images.githubusercontent.com/34729022/49930835-638bf680-ff00-11e8-98ca-0791d03dc83d.png)

**Comment by MRayermannMSFT** [comment]
Merged into hotfix branch.
