### ISSUE TITLE
[Unstable]The text box of the 'Add user or group' becomes narrow and can't be edited when switching the 'Users and groups' frequently on 'Manage Access' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1006]
**Storage Explorer Version**: 1.6.1
**Platform/OS Version**: Windows 10
**Architecture**: ia32
**Build Number**: 20181213.1
**Commit**: 4ca2a5cb
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Expand one ADLS Gen2 account -> Right click one blob container then select 'Manage Access...'.
2. Change the users and groups frequently(Notes: don't save it).

#### Expected Experience: ####
The text box of the 'Add user or group' shows well.
#### Actual Experience: ####
The text box of the 'Add user or group' becomes narrow and can't be edited.
![image](https://user-images.githubusercontent.com/34729022/49930058-d09e8c80-fefe-11e8-90cc-1a4c5ef642c0.png)
#### More info: ####
This issue is unstable.

**Comment by MRayermannMSFT** [comment]
I'm not able to reliably repro this bug. Could only do it once after 5min of trying. Additionally, if I resized the dialog, then the text box re-sized itself to the correct width. Closing as won't fix/no repro.
