### ISSUE TITLE
Storage explorer does not show documents of cosmos db

### ISSUE THREAD

**Issue by JayeshSonawane-GEP** [Microsoft/AzureStorageExplorer#1007]
**Storage Explorer Version**: 1.6.0
**Platform/OS Version**: windows10 pro 64 bit
**Architecture**: cosmos db
**Regression From**: working in 1.5.0 

#### Steps to Reproduce: ####
Open Storage Explorer and Go to subscription.
Open Cosmos Db and click on Documents.

#### Expected Experience: ####
show documents and able to query

#### Actual Experience: ####
it does not show documents. Also query window does not show any info.

**Comment by fscahill** [comment]
Same problem - documents not displaying??

**Comment by JayeshSonawane-GEP** [comment]
its not showing documents.

**Comment by mcqueene** [comment]
Same problem for me. Using Azure portal I can confirm documents exist but this version doesn't show anything.

**Comment by clementdelebecque** [comment]
Same as #971

**Comment by jinglouMSFT** [comment]
This will be fixed in the next hotfix release, expecting next week.

**Comment by jinglouMSFT** [comment]
If you need to go back to 1.5.0, you can get a copy of it from our Github repo here: https://github.com/Microsoft/AzureStorageExplorer/releases.  Please scroll down to version 1.5.0 then download the bits.

Someone must have changed the fwlink in our release notes (https://docs.microsoft.com/en-us/azure/vs-azure-tools-storage-explorer-relnotes) that we are not aware of.  We'll trace it down and fix the link.  Sorry about the inconvenience.

**Comment by goldenspb** [comment]
Thanks for links!

**Comment by jinglouMSFT** [comment]
Also, the fix will be included in the 1.6.1 release which will go live in a day or two.  I am going to close this issue for now. Please feel free to reopen if you still see the issue in 1.6.1.  Thanks.
