### ISSUE TITLE
After deleting a blob next node should be highlighted

### ISSUE THREAD

**Issue by juliusl** [microsoft/AzureStorageExplorer#1008]
[Window Title]
Microsoft Azure Storage Explorer

[Main Instruction]
Microsoft Azure Storage Explorer

[Content]
Version: 1.5.0

Platform: Windows
Architecture: ia32
Build Number: 20181026.3
Commit: a9422b7d
Support Id: 2f5b2624-a8e5-94df-f0a1-ad5fe1308f84

Copyright © 2018 Microsoft. All rights reserved.

[OK]

#### Steps to Reproduce: ####
1. Delete a blob container

#### Expected Experience: ####
Next sibling node down the list should be highlighted

#### Actual Experience: ####
The parent node is highlighted

**Comment by MRayermannMSFT** [comment]
Going to close this issue as duplicate. We just posted a description of the current node focusing behavior after a delete at this issue: https://github.com/microsoft/AzureStorageExplorer/issues/5615#issuecomment-1101631581 

If you have feedback regarding the current behavior please leave it there.
