### ISSUE TITLE
The dropdown list panel of Azure environment is odd in Connect dialog under non-dark theme

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#101]
**Storage Explorer Version:** rel/1.0.0_20180426.6

**OS Version:** Win10/Linux/Mac

**Regression**: Also repro on release 1.0.0

**Steps to Reproduce:**

1. Launch Storage Explorer.
2. Make sure the current theme is non-dark.
3. Open the 'Connect to Azure Storage' dialog -> Check the dropdown list panel of Azure environment.

**Expected Experience:**
The background color of unchecked items are friendly.

**Actual Experience:**
The dropdown list panel of Azure environment is odd.
![ddd](https://user-images.githubusercontent.com/34729022/39355053-ac6ba932-49fb-11e8-869c-90a67f4e2b62.png)

**More info:**
This issue also reproduces for dropdown list panel of Access Policy, dropdown list panel of Property Type in 'Add Entity' dialog.

**Comment by craxal** [comment]
This is a Chromium external bug we have no control over. It is odd, but accessibility is not hindered by the coloring.
