### ISSUE TITLE
Storage Explorer not prompting for conflict resolution

### ISSUE THREAD

**Issue by Bender911** [Microsoft/AzureStorageExplorer#1014]
**Storage Explorer Version**: 1.6.0
**Platform/OS**: Windows 10
**Architecture**: i86
**Regression From**: It was working in prior releases.

**Bug description**
While coping blobs from one folder to the other, if the same blobs existed at the destination location, SE  used to prompt for actions overwrite or skip.  Now it just reports that the blob exists.

**Steps to Reproduce**
1.  Upload a few blobs to a container using some folder structure.
2.  Perform a copy/paste from with storage explorer to a different folder.
3. Repeat step 2.

**Expected Experience**
In the activities window, a prompt would have come for action for the blobs, which exist at the destination location.

**Actual Experience**
The existing blobs were shown as error, and only retry or cancel option was presented.

**Comment by Bender911** [comment]
@Craig. 

The blobs have forward slashes in their names. 

The reported behavior occurs both within same container and across containers. 

I use AZ copy all the time for copying large volume of data, unattended.  

I do have workarounds.  I am simply repointing a broken functionality in v1.6.

**Comment by MRayermannMSFT** [comment]
Fix merged into hotfix branch.
<img width="501" alt="image" src="https://user-images.githubusercontent.com/21112697/50784688-40d0d180-1263-11e9-8624-6366f94f5897.png">
