### ISSUE TITLE
Ctrl+Tab and Ctrl+Shift+Tab keyboard shortcuts should allow navigating between tabs

### ISSUE THREAD

**Issue by johndowns** [microsoft/AzureStorageExplorer#1018]
**Storage Explorer Version**: 1.6.0
**Platform/OS Version**: Windows (also on macOS)
**Architecture**: ia32 (also on macOS)

#### Steps to Reproduce: ####
1. Open multiple tabs - e.g. blob container, queue, table.
2. Press Ctrl+Tab or Ctrl+Shift+Tab in an attempt to move between tabs quickly.

#### Expected Experience: ####
Ctrl+Tab should move to the next tab in the tab view. Ctrl+Shift+Tab should move to the previous tab in the tab view.

#### Actual Experience: ####
Ctrl+Tab and Ctrl+Shift+Tab does nothing.

**Comment by jinglouMSFT** [comment]
Please try Tab and Shift Tab for now.  We can look into adding ctrl+tab and ctrl+shft+tab in the future.

**Comment by johndowns** [comment]
Thanks. Tab and Shift+Tab just move between all of the controls on the window though, so this isn't really a substitute.

I'll look forward to this hopefully in a future update.

**Comment by MRayermannMSFT** [comment]
Hi @johndowns , we actually already have shortcuts for doing this! See the view menu for details (look for the next/prev editor menu items).

**Comment by johndowns** [comment]
Hi @MRayermannMSFT, thanks for your reply! Yes I'm aware the shortcuts exist - but my point was that the standard way of switching tabs, on both Windows and macOS, is to use the Ctrl+Tab and Ctrl+Shift+Tab keyboard shortcuts. All the major browsers (Chrome, Safari, Edge, IE) use these shortcuts, as does the macOS Finder. It helps a lot when applications adopt these conventions as many of us have built up muscle memory!

**Comment by mms-** [comment]
I suppose standard ctrl-tab can't be used because this app is written using Electron? I mean lets face it the UI does feel crappy, menu bar dosn't fit in, it dosn't feel like a real app. Use your own UI frameworks Microsoft.

**Comment by MRayermannMSFT** [comment]
Ok, merged into master for 1.10.0! Thank you for bringing this up @johndowns , I'm a big believer in trying to follow [existing standards](https://xkcd.com/927/) where possible, so more than happy to fix this.

Also, @mms- , we've heard complaints in the past about our UI. Unfortunately most of the complaints are vague/don't get specific suggestions. So if you have the time, it'd be great if you could open a new issue regarding what you don't like (and maybe even what you do like! 😄 ) about our UI. Personally, I'm not a fan of how we still use a gradient in the toolbar, but I also really like our move to colored SVG icons in the tree. So if you have any examples like that, we'd love to hear them. Thanks!
