### ISSUE TITLE
"Add an account..." causing confusions

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#1019]
Feedback from customers:

In the account panel and the tooltip for the ![image](https://user-images.githubusercontent.com/10081483/50193787-f526aa00-02ec-11e9-9a66-89ed1eeca352.png) button, 
 , we use "Add an account..." for both the sign-in experience and the attach experience. It potentially could cause confusion as where to look for the newly added node.  We have customers tried to look for nodes under the storage account node after using the connection strings.  

Let's see what we can label the experience to minimize the potential of confusion.

**Comment by MRayermannMSFT** [comment]
Change button tooltip to be "Connect to Azure"

**Comment by MRayermannMSFT** [comment]
Tooltip is already correct.
