### ISSUE TITLE
Add the file name in renaming log for file share

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1020]
**Storage Explorer Version**: 1.6.1
**Platform/OS Version:** Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181219.2
**Commit**: 670bface
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Expand a storage account -> File Shares -> Open one file share and upload a file to it.
2. Try to rename the file -> Check the log.

#### Expected Experience: ####
 Show the file name in the renaming log.

#### Actual Experience: ####
The file name doesn't show in the renaming log.
![image](https://user-images.githubusercontent.com/41351993/50269914-d8b07c00-046a-11e9-8ebc-9ca6acbe0e3d.png)
#### More info: ####
1. This issue doesn't reproduce when renaming a directory under file share.
2. This issue doesn't reproduce when renaming a blob.

**Comment by MRayermannMSFT** [comment]
Won't fix.
