### ISSUE TITLE
Add the specific path to the log of uploading blobs

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1021]
**Storage Explorer Version:** 1.6.1
**Platform/OS Version:** Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture:** ia32
**Build Number:** 20181219.2
**Commit:** 670bface
**Regression From:** Not a regression

#### Steps to Reproduce: ####
1. Expand a storage account -> Blob Containers -> Create a new blob container.
2. Upload a file to it ->Check the **Activities**.

#### Expected Experience: ####
 There shows the source and destination paths of the uploaded file.

#### Actual Experience: ####
The specific path doesn't display in log.
![image](https://user-images.githubusercontent.com/41351993/50268136-89674d00-0464-11e9-99cf-309ef10789b3.png)

**More Info:**
 There only displays the destination path when downloading blobs.
![image](https://user-images.githubusercontent.com/41351993/50268276-232efa00-0465-11e9-80d9-0db8bdf056bc.png)

**Comment by MRayermannMSFT** [comment]
Won't fixing. Having the path information is a nice to have/we're moving to AzCopy for blob transfers.
