### ISSUE TITLE
Update 'Load more' to 'Load More' on the tree view

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#1022]
**Storage Explorer Version:** 1.6.1
**Platform/OS Version:** Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture:** ia32
**Build Number:** 20181219.2
**Commit:** 670bface
**Regression From:** Not a regression

#### Steps to Reproduce: ####
1. Expand a storage account -> Expand Blob Containers which contains many blob containers and make sure **Load more** displays.

#### Expected Experience: ####
Display 'Load More'  under blob containers.

#### Actual Experience: ####
Display 'Load more'  under blob containers.

**Comment by MRayermannMSFT** [comment]
Won't fix.
