### ISSUE TITLE
Support to add file systems to Quick Access from ADLS Gen2 accounts

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1023]
**Storage Explorer Version:** 1.6.1
**Platform/OS Version:** Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture:** ia32
**Build Number:** 20181219.2
**Commit:** 670bface
**Regression From:** Not a regression

#### Steps to Reproduce: ####
1. Expand one ADLS Gen2 account -> Blob Containers node.
2. Right click one blob container -> Check whether there is an action to add resources to Quick Access or not.

#### Expected Experience: ####
There is an action to add resources to Quick Access.

#### Actual Experience: ####
There is no action to add resources to Quick Access.

**Comment by jinglouMSFT** [comment]
This is by-design in current release without the interop support.
