### ISSUE TITLE
Cannot work with Blob containers

### ISSUE THREAD

**Issue by CAHInspari** [Microsoft/AzureStorageExplorer#1024]
**Storage Explorer Version**: 1.6.1
**Platform/OS Version**: Windows
**Architecture**: ia32
**Regression From**: Have not used previous versions

#### Steps to Reproduce: ####
1. Add ned account
2. Add an Azure account
3. Pick "Azure Environment" = "Azure"
4. Sign in with my credentials (work account)
5. Connection succeeds and I can see the subscriptions
6. Navigate to the subscription -> Storage Accounts -> "cdmlake" Blob Containers
7. Error message occurs

"cdmlake" is the name of the data lake I am trying to connect to.

I am not able to create blob containers either, getting a similar error message.

The data lake is a gen2.

#### Expected Experience: ####
I would expect to see a list of Blob containers.
The function works when connecting to Azure with my personal account, where I have another data lake running (in different Azure AAD).

#### Actual Experience: ####
I get two error windows:
1: The requested action could not be completed
2. Unable to retrieve child resources

Both also contain the following description:
Details: getaddrinfo ENOTFOUND cdmlake.dfs.core.windows.net
cdmlake.dfs.core.windows.net:443

**Comment by jinglouMSFT** [comment]
Couple of questions: Is this an ADLS Gen2 account with HNS turned on or off?  Also, do you know what permissions do you have when you signed in using your work account?  The error message said that we couldn't find the end points. It seemed that you don't have the right permission to list or read the containers. Also, depending on whether HNS is enabled or not, different APIs are called.

**Comment by CAHInspari** [comment]
Yes, it is an ADLS Gen2 and HNS is turned on.
From the access control (IAM) my user is set to owner of the resource.

**Comment by CAHInspari** [comment]
The error seems to have been resolved elsewhere. It works as expected now.
