### ISSUE TITLE
Explorer window to see contents(schema + body) of Avro files

### ISSUE THREAD

**Issue by tarinidash** [Microsoft/AzureStorageExplorer#1025]
Version : 1.6.1 

I could not find an option in the storage explorer to see the contents(schema + body) of an Avro file.

Is this currently supported or is planned to be supported in future? 

It would be nice to have it.

**Comment by jinglouMSFT** [comment]
Storage Explorer doesn't ship with any editors.  Also we only associate with few common file types, so i am pretty sure we will not automatically open Avro files.  If it were supported, you can double click on the file and we will download it and automatically open it if we can find the editor.
