### ISSUE TITLE
Show an unmatched value of ContentType for blob folders of ADLS Gen2 accounts

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1026]
**Storage Explorer Version:** 1.6.1
**Platform/OS Version:** Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture:** ia32
**Build Number:** 20181220.1
**Commit:** 670bface
**Regression From:** Not a regression

#### Steps to Reproduce: ####
1. Choose one ADLS Gen2 account -> Open one blob container.
2. **Create a new folder** then check the value of the Content Type column on the editor view.
3. Right click the created folder then select 'Properties...' -> Check the value of the ContentType under System Properties.

#### Expected Experience: ####
The value of the ContentType is '**Folder**' on the Properties dialog.

#### Actual Experience: ####
There shows an unmatched value '**application/json;charset=utf-8**' of the ContentType on Properties dialog for the new created folder.
![image](https://user-images.githubusercontent.com/34729022/50328576-9fd9db00-052e-11e9-8328-cdbe1956e677.png)
#### More info: ####
1. There is no value of the ContentType **on Properties dialog** for **uploaded folders** from ADLS Gen2 accounts.
![image](https://user-images.githubusercontent.com/34729022/50328632-cd268900-052e-11e9-8329-8b85f5f10762.png)
2. There is no value of the **Content Type column** for uploaded blob files from ADLS Gen2 accounts.
![image](https://user-images.githubusercontent.com/34729022/50328674-fb0bcd80-052e-11e9-8516-e9ed53e0f348.png)

**Comment by MRayermannMSFT** [comment]
Going to won't fix this for now as the "fix" is unclear. If customers have feedback we can get guidance for them on what they want the experience to be.
