### ISSUE TITLE
The value of DFS Endpoint is empty for the attached GPV2 accounts on Properties Panel

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1027]
**Storage Explorer Version:** 1.6.1
**Platform/OS Version:** Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture:** ia32
**Build Number:** 20181220.1
**Commit:** 670bface
**Regression From:** Not a regression

#### Steps to Reproduce: ####
1. Choose one GPV2 account -> Verify the value of the DFS Endpoint on Properties Panel.
2. Attach the account with SAS like below.
**Display name:** alphatreadaccess
**SAS**: SharedAccessSignature=sv=2018-03-28&ss=bfqt&srt=sco&sp=rwdlacup&st=2018-12-21T06%3A54%3A32Z&se=2019-12-22T06%3A54%3A00Z&sig=iWZhgfO4VYeb7oIuwH8VZC9BpNxBNZlTzfnWstY1qe4%3D;BlobEndpoint=https://alphatreadaccess.blob.core.windows.net/;FileEndpoint=https://alphatreadaccess.file.core.windows.net/;QueueEndpoint=https://alphatreadaccess.queue.core.windows.net/;TableEndpoint=https://alphatreadaccess.table.core.windows.net/;
3. Expand **'Local & Attached'** -> '**Storage Accounts**' -> '**alphatreadaccess**' -> Check the value of DFS Endpoint on Properties Panel.

#### Expected Experience: ####
The value of DFS Endpoint is not empty.

#### Actual Experience: ####
The value of DFS Endpoint is empty.
![image](https://user-images.githubusercontent.com/34729022/50329401-20e6a180-0532-11e9-9a6b-818863202635.png)
#### More info: ####
This issue doesn't reproduce for attached ADLS Gen2 accounts with Key/Name.
![image](https://user-images.githubusercontent.com/34729022/50329749-87b88a80-0533-11e9-8b2b-7f201ac89c7b.png)

**Comment by MRayermannMSFT** [comment]
We don't support SAS for ADLS Gen2. By design.
