### ISSUE TITLE
There shows an extra error message when renaming a blob with the same name

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1028]
**Storage Explorer Version:** 1.6.1
**Platform/OS Version:** Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture:** ia32
**Build Number:** 20181220.1
**Commit:** 670bface
**Regression From:** Not a regression

#### Steps to Reproduce: ####
1. Expand one **non-ADLS Gen2** account -> Open one blob container which contains one blob at least.
2. Try to rename the blob with the same name -> Check the log message on Activities.

#### Expected Experience: ####
1. Shows '_Skipped ... New name provided is identical_'.
2. There is no error message shows.

#### Actual Experience: ####
1. Shows '_Skipped ... New name provided is identical_'.
2. There shows an extra error message with confused description.
![image](https://user-images.githubusercontent.com/34729022/50330917-eaac2080-0537-11e9-871f-2c06239f052e.png)
#### More info: ####
This issue doesn't reproduce when renaming a ADLS Gen2 blob with the same name.
![image](https://user-images.githubusercontent.com/34729022/50331258-0a901400-0539-11e9-85bc-4c0aaae1dc44.png)

**Comment by MRayermannMSFT** [comment]
This is fixed on master. Closing.
