### ISSUE TITLE
unclear issue in Microsof Azure Storage Explorer

### ISSUE THREAD

**Issue by jamweb2019** [Microsoft/AzureStorageExplorer#1029]
{
  "name": "StorageError",
  "message": "The specified blob or block content is invalid.\nRequestId:217d7d66-b01e-0017-433b-9c5577000000\nTime:2018-12-25T10:19:25.6296106Z",
  "stack": "StorageError: The specified blob or block content is invalid.\nRequestId:217d7d66-b01e-0017-433b-9c5577000000\nTime:2018-12-25T10:19:25.6296106Z\n    at Function.StorageServiceClient._normalizeError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:1198:23)\n    at Object.StorageServiceClient._processResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:744:50)\n    at Request.processResponseCallback [as _callback] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:317:37)\n    at Request.self.callback (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1157:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1079:12)",
  "code": "InvalidBlobOrBlock",
  "statusCode": 400,
  "requestId": "217d7d66-b01e-0017-433b-9c5577000000"
}

**Comment by jinglouMSFT** [comment]
Could you please provide more detailed info so we can try to help you with?  For example, which version Storage Explorer, on what platform?  What did you do when you got this error?  Did you sign into Azure or did you attach to a storage account?  What type of blob was it? Block blob? Page blob? Append blob?  Also, if using version after 1.5.0, did you enable the Experimental AzCopy feature when you did blob operations?  By just looking at the error message itself, it basically meant that you had an invalid blob. It could be of corrupted content, or didn't meet the blob type specifications.  Here is a link to the blob specifications:  https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-block-blobs--append-blobs--and-page-blobs

Please feel free to reopen the issue if you still have the issue active, but please provide detailed info so we can help diagnose. 

Thanks.
