### ISSUE TITLE
Make our usage of DataTables accessible without workarounds, or replace DataTables with a better library

### ISSUE THREAD

**Issue by blindfrustratio** [Microsoft/AzureStorageExplorer#103]
**Storage Explorer Version:**

**OS Version:**

**Steps to Reproduce:**

1.
2.

**Expected Experience:**

**Actual Experience:**
I opened a blob container and seem to be able to navigate the table displaying the list of blobs in this container, but don't seem to be able to actually select the one I believe I've selected.

In my particular case, I only have 2 blobs in the container, one is an image, the other is a plain text file. I want to open the text file but every time I try to open the context menu when I hear the row representing the plain text file spoken and then select open to view the contents, I am always presented with a standard windows dialog asking whether I want to open image files using whatever.

When I select the properties menu, the image blob properties are displayed, so I'm assuming that the first blob is selected. However, I can't find any way to select the second blob.

I'm using the latest version of NVDA (2018.1.1)  on Windows 10

**Comment by MRayermannMSFT** [comment]
Fixing this will close:
- https://msdata.visualstudio.com/Cosmos/_workitems/edit/120385
- https://msdata.visualstudio.com/Cosmos/_workitems/edit/120429
- https://msdata.visualstudio.com/Cosmos/_workitems/edit/125316
- https://msdata.visualstudio.com/Cosmos/_workitems/edit/120413
- https://msdata.visualstudio.com/Cosmos/_workitems/edit/123415
- https://msdata.visualstudio.com/Cosmos/_workitems/edit/123416
- https://msdata.visualstudio.com/Cosmos/_workitems/edit/120975
- https://msdata.visualstudio.com/Cosmos/_workitems/edit/120385
- https://msdata.visualstudio.com/Cosmos/_workitems/edit/125331
- https://msdata.visualstudio.com/Cosmos/_workitems/edit/125333

**Comment by MRayermannMSFT** [comment]
Hey @blindfrustratio , please let us know of any feedback you have regarding the improved experience with the table of blobs. Thanks!
