### ISSUE TITLE
[Feature Request] Copy URI

### ISSUE THREAD

**Issue by wsmelton** [Microsoft/AzureStorageExplorer#1030]
**Storage Explorer Version**: any
**Platform/OS**: Windows
**Architecture**: x64
**Regression From**: N/A

**Current Experience**
1. Select a blob file
1. Right-click file
1. Go to properties
1. Find URI field
1. Select field, press CTRL + A
1. Copy text

**Desired Experience**
It would be nice to have the ability to right-click a blob file and have quick option to "copy as URI" or something of that nature. A similar feature is available in Windows Explorer where we can hold SHIFT and we see an extra right-click menu option to "copy as path". In Azure Explorer it would be just a menu option to "copy as URI" and would only be there if we selected a file that supported that option.

**Comment by wsmelton** [comment]
I use the URI for scripting with SQL Server and in most scenarios need just that value.

I don't utilize SAS.

**Comment by jinglouMSFT** [comment]
OK. Thanks for the info.

**Comment by MRayermannMSFT** [comment]
Hi @wsmelton , this feature actually already exists!
![image](https://user-images.githubusercontent.com/21112697/56154663-eb951200-5f6d-11e9-9644-ab4976093c7b.png)
Closing. 😄

**Comment by wsmelton** [comment]
That is not a right click menu option though.
