### ISSUE TITLE
Save CosmosDB query tabs

### ISSUE THREAD

**Issue by drhkocher** [microsoft/AzureStorageExplorer#1031]
Storage explorer is a great product.

I use it with several standard queries while developing a CosmosDB application. Unfortunately, there is no possibility to save queries so they can be reused in future sessions. I would like to be able to store arbitrary queries (and the default filter that I change every time to display the latest documents first).

- Support saving queries to a storage container
- Support collection of queries to group queries and load them all  or individually

This should work like SQL Management Studio in this regard.

**Comment by ImrePyhvel** [comment]
Even simpler and still of great help would be to just auto-save the query tabs and restore them when app is restarted.

**Comment by jinglouMSFT** [comment]
Storage Explorer support have been removed from Storage Explorer.
