### ISSUE TITLE
Return extended query metrics for CosmosDB

### ISSUE THREAD

**Issue by drhkocher** [microsoft/AzureStorageExplorer#1032]
Add checkbox to CosmosDB queries to optionally return extended query metrics.

Often I would like to know if a query can be answered from the index, document size etc. I know how to get this information in code but it would be easier if it would be an option in the query tab.

**Comment by ImrePyhvel** [comment]
This seems a rather trivial thing to fetch from http header and show in GUI. Any plans?

**Comment by jinglouMSFT** [comment]
CosmosDB support has been removed from Storage Explorer.
