### ISSUE TITLE
Issue downloading .pst file from Azure storage explorer.

### ISSUE THREAD

**Issue by dtram** [Microsoft/AzureStorageExplorer#1033]
{
  "name": "StorageError",
  "message": "Forbidden",
  "stack": "StorageError: Forbidden\n    at Function.StorageServiceClient._normalizeError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:1198:23)\n    at Object.StorageServiceClient._processResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:744:50)\n    at Request.processResponseCallback [as _callback] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:317:37)\n    at Request.self.callback (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1157:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1079:12)",
  "code": "Forbidden",
  "statusCode": 403,
  "requestId": "b210b541-501e-0062-5044-a113e9000000"
}

**Comment by dtram** [comment]
Hello, 

I really need you help in downloading the .pst file stored in Azure storage.  MS support is of no help....  the cannot re-initiate importing the .pst files to an Office 365 mailbox.  The import completed with errors and only a third of the emails were successfully imported to the mailbox.

**Comment by jinglouMSFT** [comment]
This is similar to #966.  Same question to you.  Can you find out what SAS URL permissions you have? 
Also, please provide the following information.
- which version of Storage Explorer you are using?
- Did you enable the Experimental feature to utilize AzcCopy?

**Comment by dtram** [comment]
Hello,

Go ahead and close this ticket.  I’ve download the .pst from backup.


Dave Tram
Systems engineer | Neutrino Networks, Inc.

i.t. consulting > managed services > cloud computing
-----------------------------------------------------------------
Tel: 310-556-4435 | Fax: 310-556-0205 | www.goneutrino.com<http://www.goneutrino.com/>


*Having a technical issue that needs immediate assistance? Contact our HelpDesk at support@goneutrino.com<mailto:support@goneutrino.com> or (310) 556-4435 and receive instant service. We look forward to hearing from you and solving all of your technical needs.
