### ISSUE TITLE
Clicking a sub-item of "Quick Access" doesn't keep the highlight on the clicked item

### ISSUE THREAD

**Issue by zivcaspi** [Microsoft/AzureStorageExplorer#1035]
**Storage Explorer Version**: 1.6.1
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**: No idea

**Bug description**
See title

**Steps to Reproduce**
1. Add a new item to "Quick Access"
2. Click on the item in the left pane

**Expected Experience**
The clicked item will be highlighted in the UX

**Actual Experience**
The highlight immediately "jumps" to the "Quick Access" tree node itself (and the right pane + properties pane show the information relevant to Quick Access, not the actual item being clicked)

**Additional Context**

**Comment by jinglouMSFT** [comment]
Based on the information provided, i am not observing the behavior you described.  Could you please elaborate your step 2 above?  What item you clicked in the left pane?

**Comment by zivcaspi** [comment]
I seem to have lost the repro, sorry. I'm fine with closing this issue until I'll observe it again (hopefully never :))

**Comment by jinglouMSFT** [comment]
Were you referring to the broken link or the original focus issue?  The broken link is a known issue. We currently preserve the links at the storage account level. The blob/queue/table/file quick links are preserved however.
