### ISSUE TITLE
Sign in using global AAD account but cannot load subscription both in the admin and tenant 

### ISSUE THREAD

**Issue by supervicky42** [microsoft/AzureStorageExplorer#1037]
Storage Explorer Version: 1.6.1
Platform/OS Version: win10
Steps to Reproduce:
Install the 1.6.1version Storage Explorer ,Import the certificate, Target the AZURE STACK.
Sign in use global AAD account.
Expected Experience:
The account will display its' all subscription.
Actual Experience:
None. Even It can load normally but the all subscriptions will disappear after short time.

**Comment by jinglouMSFT** [comment]
Nevermind. This was through testing.

**Comment by MRayermannMSFT** [comment]
@supervicky42 please reopen / open a new issue if this still a problem. It sounds like from your last comment that it was resolved...
