### ISSUE TITLE
Show a wrong version number on the Release Notes

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1041]
**Storage Explorer Version:** 1.6.2
**Platform/OS Version:** Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture:** ia32/x64
**Build Number:** 20190104.2
**Commit:** 6ad194d8
**Regression From:** Previous release

#### Steps to Reproduce: ####
1. Open Release Notes -> Check the version number on the Release Notes.

#### Expected Experience: ####
Show as 1.6.2 on the Release Notes.

#### Actual Experience: ####
Show as 1.6.1 on the Release Notes.
![image](https://user-images.githubusercontent.com/34729022/50680338-4e5b4100-1042-11e9-8fb0-0ad88332b497.png)

**Comment by jinglouMSFT** [comment]
closing.
