### ISSUE TITLE
Show a duplicate description for the #3 hotfixes on the Release Notes

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1042]
**Storage Explorer Version:** 1.6.2
**Platform/OS Version:** Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture:** ia32/x64
**Build Number:** 20190104.2
**Commit:** 6ad194d8
**Regression From:** Previous release

#### Steps to Reproduce: ####
1. Open Release Notes -> Check the descriptions under the Hotfixes.

#### Expected Experience: ####
There is no duplicate descriptions.

#### Actual Experience: ####
There shows a duplicate description for the 3rd hotfixes.
![image](https://user-images.githubusercontent.com/34729022/50680495-e48f6700-1042-11e9-982f-eae85d9dbbc5.png)

**Comment by jinglouMSFT** [comment]
closing,
