### ISSUE TITLE
Adding a user with long user name shows an odd layout on the Manage Access dialog for ADLS Gen2 accounts

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1043]
**Storage Explorer Version:** 1.6.2
**Platform/OS Version:** Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture:** ia32/x64
**Build Number:** 20190104.2
**Commit:** 6ad194d8
**Regression From:** Not a regression

#### Steps to Reproduce: ####
1. Expand one ADLS Gen2 account -> Open one blob container -> Create a new folder.
2. Right click the folder then select 'Manage Access' -> Input one Object ID for user with long user name -> 'Add'.
3. Check the layout for the dialog.

#### Expected Experience: ####
The layout of the 'Manage Access' dialog shows well.

#### Actual Experience: ####
Show an odd layout on the 'Manage Access' dialog.
![image](https://user-images.githubusercontent.com/34729022/50680973-b3b03180-1044-11e9-952a-90b0c028f78d.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into hotfix branch.
