### ISSUE TITLE
Add account using "Name" and "Key" stuck on "Adding new connection."

### ISSUE THREAD

**Issue by lambiuk** [microsoft/AzureStorageExplorer#1044]
**Storage Explorer Version**: 1.6.1
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**: 

**Bug description**
Unable to add account using name / key approach

**Steps to Reproduce**
1. Add Azure Account
2. Select "Use a storage account name and key"
3. Enter valid info copied straight from Azure page / details
4. Click connect

**Expected Experience**
New account listed and accessible

**Actual Experience**
Activities window showing "Adding new connection." with loader icon but nothing happens, it's stuck in this state

**Comment by jinglouMSFT** [comment]
Can you provide a bit more detailed info?  For example, the steps to get the key in Azure.  Was it a primary key or a secondary key being used for your connection?  Which Azure did you try to connect to? Global Azure? or others?  Was HTTP checked?  Thanks.

**Comment by IrisClasson** [comment]
I get the same error when I try to attach to a local  emulator

**Comment by sherryhw** [comment]
Same issue here. Which version can work?

**Comment by lesterw1** [comment]
I am also seeing the same issue with the v1.7.0 February 2019 version. HTTP is not checked.  Just stuck on Adding New Connection.  Also happens with Sas key, regardless of storage account. I also do not have a proxy.

**Comment by rubrik-vikas** [comment]
Hitting the same issue. 

It worked on one account but doesn't work on another account.

If the credentials are wrong, it should timely error out.

**Comment by XristophD** [comment]
Hitting the same issue adding via Connection string or Name/Key pair. 
Http not checked, First Key used. 

It seems it creates the connection in the background since I am not able to add another one with the same name afterwards. Current version 1.8.1 of Storage Explorer used.

**Comment by MRayermannMSFT** [comment]
Hey @XristophD @rubrik-vikas @lesterw1  @sherryhw  @lambiuk  are any of y'all still having problems related to this issue?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open new issues if you're still having problems.
