### ISSUE TITLE
Graph Traversal (Query) clear icon hides text, can't see what I'm typing.

### ISSUE THREAD

**Issue by davidatorres** [microsoft/AzureStorageExplorer#1045]
**Storage Explorer Version**:  1.6.1
**Platform/OS Version**: macOS, Build Number: 20181218.1
**Architecture**: x64
**Regression From**: It's been annoying me forever ;o)

#### Steps to Reproduce: ####
1. Type a Traversal (Query) in the Graph tab's text field that is longer than the text input box
2. The "Clear X" icon inside the text input box covers that last few characters of the string making it impossible to see what you're typing.  

#### Expected Experience: ####
What I Need: Is the "Clear X" icon moved outside of the text box and for the text box to resize with the window size.

What I Want: Is a multiline text input box that retains the last 50 traversals (queries)

What I Dream Of: Gremlin syntax checking, with quotation mark and parenthesis completion checking

#### Actual Experience: ####
This has caused me hundreds of failed queries because I can't see what I'm typing.

**Comment by jinglouMSFT** [comment]
CosmosDB support has been removed from Storage Explorer.
