### ISSUE TITLE
Can add the same user multiple times on 'Manage Access' dialog for ADLS Gen2 accounts

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1047]
**Storage Explorer Version:** 1.6.2
**Platform/OS Version:** Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture:** ia32/x64
**Build Number:** 20190104.4
**Commit:** 959a9434
**Regression From:** Not a regression

#### Steps to Reproduce: ####
1. Expand one ADLS Gen2 account -> 'Blob Containers' node.
2. Right click one blob container then select 'Manage Access...'.
3. Enter the Object ID of one user -> Click 'Add'_(Do not save it)_.
4. Enter the same Object ID again -> Click 'Add'.

#### Expected Experience: ####
An error prompts due to the added user already exists.

#### Actual Experience: ####
The the Object ID can be added successfully without any error.
![image](https://user-images.githubusercontent.com/34729022/50757648-fe2aeb80-129a-11e9-9349-77667ff5e6d6.png)

#### More info: ####
Fail to save the permissions with the below error.
![image](https://user-images.githubusercontent.com/34729022/50757645-fb2ffb00-129a-11e9-877c-19590ce1033c.png)

**Comment by MRayermannMSFT** [comment]
Won't fix for now.
