### ISSUE TITLE
Remove 'Apply to All' on 'Upload Conflict' dialog when uploading an existing blob

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1051]
**Storage Explorer Version:** 1.6.2
**Platform/OS Version:** Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture:** ia32/x64
**Build Number:** 20190108.1
**Commit:** 1d51960b
**Regression From:** Not a regression 

#### Steps to Reproduce: ####
1. Expand one non-ADLS Gen2 account -> Blob Containers
2. Open one blob container then upload one blob to it.
3. Upload the same blob again then check the popped 'Upload Conflict' dialog.

#### Expected Experience: ####
1. No 'Apply to All' shows when uploading **one existing blob** like below: 
![image](https://user-images.githubusercontent.com/34729022/50820946-ede14200-1368-11e9-83c3-e1847b2fa214.png)
2. Both show the 'Apply to All' and 'Apply' when uploading **multiple existing blobs**.
#### Actual Experience: #### 
Both show 'Apply to All' and 'Apply' when uploading **one existing blob**.
![image](https://user-images.githubusercontent.com/34729022/50821168-7bbd2d00-1369-11e9-9767-27ed2f2fff96.png)

**Comment by jinglouMSFT** [comment]
A harmless bug.  Let's use the resource to fix other higher priority bugs.
