### ISSUE TITLE
Display bug is back in 1.6.2

### ISSUE THREAD

**Issue by pjirsa** [Microsoft/AzureStorageExplorer#1054]
The display bug that was fixed in 1.6.1 appears to be back in 1.6.2. Please include this fix in future versions.

**Comment by pjirsa** [comment]
https://github.com/Microsoft/AzureStorageExplorer/issues/971

**Comment by MRayermannMSFT** [comment]
@pjirsa , can you confirm for me that you are on 1.6.2/try to view your CosmosDB documents again? I'm not seeing this.
![image](https://user-images.githubusercontent.com/21112697/50854640-6bda2480-133a-11e9-9bb3-e90a540c9a1d.png)

**Comment by jinglouMSFT** [comment]
I can't repro this either with build 20190108.1.

**Comment by pjirsa** [comment]
I performed a clean install and also opted out of preview builds. No longer seeing the issue.
Thanks.
