### ISSUE TITLE
Create BLOB container for ADLS Gen2 Preview Storage Account Fails

### ISSUE THREAD

**Issue by jgleason00** [microsoft/AzureStorageExplorer#1057]
Storage Explorer Version: 1.6.2
Platform/OS: Windows 10
Architecture: ia32
Build Number: 20190108.2

Bug description
Cannot create a BLOB container under  an ADLS Gen2 storage account. Returns a EPROTO error in storage explorer (see attached image).

Steps to Reproduce
1.install 1.6.2
2.create a Gen 2 ADLS with Hierarchical Namespace
3.sign in to storage explorer
4. navigate to storage account (it does show ADLS Gen2 Preview)
5. right click on Blob Container and select Create Container
6. give it a name

Expected Experience
A new container is created

Actual Experience
EPROTO error.

![capture](https://user-images.githubusercontent.com/22594349/50931846-76271c00-1429-11e9-8f6c-aafae5b7fa28.PNG)

**Comment by colinrippeyfinarne** [comment]
I am experiencing this exact same issue today, @MRayermannMSFT  do you have any update?

[Window Title]
Microsoft Azure Storage Explorer

[Content]
Unable to retrieve child resources. Details: write EPROTO 0:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:d:\buildagent\workspace\318698\vendor\node\deps\openssl\openssl\ssl\s23_clnt.c:827:


[OK]

My desktop goes out via a WPAD.DAT proxy, and so I typically use fiddler as the proxy to "get through" the WPAD.DAT.

I can see fiddler trying to connect to the file shares on the https://<accountname>.file.core.windows.net but I don't see any attempt to connect to the https://<accountname>.blob.core.windows.net.

(I can see traffic to the queue and table endpoints, just not the blob endpoint)

**Comment by colinrippeyfinarne** [comment]
@MRayermannMSFT  from what I can tell any storage account that has the ADLS Gen2 Preview won't connect to the blob endpoint. 

I can connect to all other endpoints on these storage accounts, and I can connect to the blob endpoint on other storage accounts that do not have the ADLS Gen2 Preview features enabled.

**Comment by oedenfield** [comment]
I know it's been a while but I can't replicate this issue using Azure Storage Explorer 1.8.1. ADLS Gen2 is now GA as well. I'm not sure what was fixed but please try newer releases of Storage Explorer.

**Comment by MRayermannMSFT** [comment]
Sounds like this was fixed/mitigated. Going to go ahead and close.
