### ISSUE TITLE
Windows 64-bit Storage Explorer

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#106]
Since macOS and Linux platforms only use 64-bit versions of Storage Explorer, we're planning to make a 64-bit version available for Windows users in the very near future. In tandem, we intend to phase out and drop support for 32-bit versions.

Please let us know any concerns you may have.

**Comment by HenryGelderbloem** [comment]
Any update on the progress of this? This has been on the backlog for almost 5 years.

**Comment by craxal** [comment]
@HenryGelderbloem We actually just had a discussion about this. Since very few of users are these days on 32-bit machines, we're planning on making this available in the near future.
