### ISSUE TITLE
The properties of file snapshots can be edited

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1060]
**Storage Explorer Version:** 1.6.2
**Platform/OS Version:** Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture:** ia32/x64
**Build Number:** 20190110.1
**Commit:** b4ffb306
**Regression From:** Not a regression

#### Steps to Reproduce: ####
1. Expand one storage account -> 'Files Shares'.
2. Open one file share which contains one file at least -> Create a snapshot for the file share.
3. Go to the file share snapshot view -> Right click one file snapshot to open 'Properties' dialog.
4. Check whether the properties can be edited or not.

#### Expected Experience: ####
The properties of the file snapshot can't be edited.

#### Actual Experience: ####
1. The properties of the file snapshot can be edited.
![image](https://user-images.githubusercontent.com/34729022/51020305-211a1000-15b9-11e9-8e99-d9661d50079a.png)
2. Reopening the 'Properties' dialog of  file snapshots doesn't save the inputted properties. 

#### More Info: ####
This issue doesn't reproduce for properties of blob snapshots.

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
