### ISSUE TITLE
stgquery Files not Opening

### ISSUE THREAD

**Issue by btmi** [microsoft/AzureStorageExplorer#1061]
**Storage Explorer Version**: 1.6.2
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**: 1.6.1

**Bug description**
Previously saved Cosmos queries (stgquery) are not working. Instead of the saved clauses, an empty line for each clause is created and all queries have to be recreated from scratch.

**Steps to Reproduce**

1. Open Cosmos Table
2. Select Query

**Expected Experience**
Query is opened, but not displayed
**Actual Experience**
**Additional Context**

**Comment by btmi** [comment]
Previously saved Cosmos queries (stgquery) are not working.  Instead of the saved clauses, an empty line for each clause is created and all queries have to be recreated from scratch.

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
