### ISSUE TITLE
Storage Explorer can't copy or download folders with more than 10000 files 

### ISSUE THREAD

**Issue by felix185** [microsoft/AzureStorageExplorer#1062]
**Storage Explorer Version**: 1.6.2
**Platform/OS**: Windows 10
**Architecture**: ia32

**Bug description**
I tried to download a folder with two subfolders. The first subfolder contains about 24000 files, the second about 200. When the download finished I could see the 200 files from the second folder but only the first 10000 of the other one. 
I recognized the same behavior when I tried to copy the folder to another destination. Only the first 10000 elements of the folder with the 24000 files were copied.

**Steps to Reproduce**
1. create a folder with more than 10000 files
2. try to download the folder
3. only the first 10000 files are downloaded

**Expected Experience**
All of the files in a folder are downloaded/copied without any limit in number of files in a folder.

**Actual Experience**
Only the first 10000 files in a folder are downloaded/copied

**Comment by MRayermannMSFT** [comment]
@felix185 , are you downloading from a blob container, file share, or adlsgen2 blob container?

**Comment by felix185** [comment]
I am downloading from a file share

**Comment by MRayermannMSFT** [comment]
@felix185 is the copy from Azure to Azure? Or do you mean copying locally on your machine?

**Comment by felix185** [comment]
e.g. copy from a folder /test to another folder /another_test in the same ADLS. 
And downloading is from ADLS to my local machine. 
The activity log shows 10k and not the actual number. 
The files are small, only a few KB (2-3 KB per file)

**Comment by MRayermannMSFT** [comment]
@felix185 , bit confused here...earlier you said you were downloading from a File Share, but now you're saying ADLS? Can you confirm which of the following you are working with:

- ADLS Gen1: 
![image](https://user-images.githubusercontent.com/21112697/56917095-734f4600-6a6f-11e9-9eb4-3849a012bf85.png)
- ADLS Gen2 Storage Account: 
![image](https://user-images.githubusercontent.com/21112697/56917110-7fd39e80-6a6f-11e9-8c1d-de4e1fb2f996.png)
- Normal Storage account: 
![image](https://user-images.githubusercontent.com/21112697/56917139-94179b80-6a6f-11e9-9b7e-e18a18e99a13.png)

And then if it is an ADLS Gen2 storage account or a normal storage account, are you downloading from a Blob container or a File Share?

**Comment by felix185** [comment]
Sorry for the confusion... We're using ADLS Gen 1

**Comment by rbarrett3** [comment]
I have the same issue with Storage Explorer v1.27.0.  I was running it on an Azure VM pulling 695k files from an Azure File Share (100TB hot) to the VM's local data disk and after the first 10,000 items it just hung/spun.  I could still use the app to calculate disk stats, etc, but the transfer wasn't going to recover.

**Comment by mcf-rocha** [comment]
I have been experiencing the same behavior when using AZ Storage Explorer:
Version: 1.30.0
AzCopy Version: 10.19.0
Platform: macOS
Architecture: x64 

It doesn't matter if it is between 2 Blog Storage or from Blob Storage to ADLS Gen 2, frequently when I have for instance...

Total: 20 993 items, 2,49 GiB (2 672 431 496 bytes)

Only these get copied....

Total: 10 000 items, 1,26 GiB (1 356 130 434 bytes).

...and the Storage Explorer does not show any error message :-(
