### ISSUE TITLE
Can't download *.psd or *.tif files - the download never completes

### ISSUE THREAD

**Issue by alvipeo** [Microsoft/AzureStorageExplorer#1065]
Try to download *.psd or *.tif files from blob storage (cool ties in my case), the download never completes! And the files are ~10 Mb each.

**Comment by MRayermannMSFT** [comment]
@alvipeo , can you reconfirm that this repro's on our latest version, 1.7.0, and that it is only these file types that are affected?

**Comment by alvipeo** [comment]
yes, it works now! Thank you!

**Comment by alvipeo** [comment]
Too fast... .PSD do not work still :(

**Comment by alvipeo** [comment]
ok, no, it doesn't work still. it worked once (I had AzCopy enabled, disabled it and it downloaded TIFF that time). but after the restart (AzCopy is disabled) it doesn't work.

**Comment by MRayermannMSFT** [comment]
@alvipeo:

1. Are you still having issues? 
2. Are you signed in or using SAS?

**Comment by alvipeo** [comment]
I just checked - everything works with AzCopy enabled.
