### ISSUE TITLE
Still cant connect to azure account

### ISSUE THREAD

**Issue by RobertK73** [Microsoft/AzureStorageExplorer#1067]
**Storage Explorer Version**: 1.5.0
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**: 

**Bug description**

Errormsg: 
Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: a6e5f0c0-7367-4f15-800d-de3e8da90325, Error: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"51.144.236.151","port":443}

**Steps to Reproduce**

1. Connecting to Azure via VS2015 and webbrowser works fine. Why does it not do the same here???
2.

**Expected Experience**

**Actual Experience**

**Additional Context**

**Comment by jinglouMSFT** [comment]
Please tell us which version of Storage Explorer?  Which version of Windows?  Are you going through a proxy?

**Comment by RobertK73** [comment]
I use v 1.5.0. of Storage Explorer on Windows 10 x64. I am not going through a proxy since I allready have access to azure via webbrowser and vs 2015 without using proxy

**Comment by RobertK73** [comment]
What kind of bs is this!!!? What more info do you need?? You havent specified jesus christ!!!!!!!!!!!!!!!!!!

**Comment by RobertK73** [comment]
WHAT THE FUCK ARE YOU TALKING ABOUT "reluctant to provide additional info to help us help you,".
WHAT INFORMATION!!!??? SPECIFY FOR FUCKS SAKE

**Comment by jinglouMSFT** [comment]
We did provide a bug template for you to open the issue.  We certainly need to know the basic version/OS info, as well as what actions you performed to trigger the error message at the least. Did you sign into Azure Storage or did you attach to it using Name/Key or SAS?  If you believe this is a bug in the product, we would need the repro steps so we can reproduce the problem in house and hopefully find a workaround for you while we work on the fix. Those are the reasons why we asked for more info.

We are thankful to all our customers for using Storage Explorer and are very appreciative that our customers spending their precious time to send us constructive feedback. If you are willing to continue working with us to resolve the issue you ran into, we'd love to work with you.  As a gentle reminder, please do keep the conversation at a professional level. Thank you!
