### ISSUE TITLE
Memory leak of storage explorer

### ISSUE THREAD

**Issue by EvanCui-zz** [microsoft/AzureStorageExplorer#1068]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10 10.0.17763.134
**Architecture**: x64
**Regression From**: None

#### Steps to Reproduce: ####
1. Open the app, and leave it there for 1 weekend
2. I uploaded some files to a blob container

#### Expected Experience: ####
No memory leak

#### Actual Experience: ####
The memory consumption is more than 1.5G.

I have a memory dump, but I don't think I can attach it here.
If you need, please give out a place where I can upload them. 
Since I am inside Microsoft, so a file share might be good.

**Comment by MRayermannMSFT** [comment]
Hey @EvanCui , if you're internal, just look me up and shoot me an email. Thanks. :)

**Comment by MRayermannMSFT** [comment]
Hey @EvanCui still waiting on that email.
