### ISSUE TITLE
Problem copying Volve dataset, error: EPERM

### ISSUE THREAD

**Issue by Jessenri** [Microsoft/AzureStorageExplorer#1069]
```json
{
  "name": "Error",
  "message": "EPERM: operation not permitted, open 'E:\\Volve Database\\GeoScience_OW_Archive\\VOLVE_PUBLIC_Seismic.dszip.partial'",
  "stack": "Error: EPERM: operation not permitted, open 'E:\\Volve Database\\GeoScience_OW_Archive\\VOLVE_PUBLIC_Seismic.dszip.partial'",
  "errno": -4048,
  "code": "EPERM",
  "syscall": "open",
  "path": "E:\\Volve Database\\GeoScience_OW_Archive\\VOLVE_PUBLIC_Seismic.dszip.partial"
}
```

**Storage Explorer Version**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**: 

**Bug description**

**Steps to Reproduce**

1.
2.

**Expected Experience**

**Actual Experience**

**Additional Context**

**Comment by craxal** [comment]
@Jessenri, please provide the information as indicated in the bug template, including the Storage Explorer version, bug description and repro steps, and expected/actual experience.

**Comment by MRayermannMSFT** [comment]
1. Closing due to lack of information
2. The error makes it sound like Storage Explorer can't read the files you want to upload. Check the permissions on the files you want to upload to make sure you have access to them. You could also try running Storage Explorer as admin.
