### ISSUE TITLE
Unable to break lease

### ISSUE THREAD

**Issue by gacurtin** [Microsoft/AzureStorageExplorer#1070]
**Storage Explorer Version**:  1.6.2
**Platform/OS**:  Windows 10 Enterprise
**Architecture**:  64
**Regression From**:  Not Sure

**Bug description**
  When breaking a VHD lease the message "Input does not match" results.  The names do match in this scenario (See screenshot).  Most likely related to VHD naming convention that is using special characters

**Steps to Reproduce**

1. Right click VHD and select break lease
2. Type in vhd name (only happens when special characters are in the name of the VHD.

![1](https://user-images.githubusercontent.com/41650197/51144987-317bf600-1818-11e9-997d-271782c22103.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
