### ISSUE TITLE
Allow to rename an empty folder with an existing name

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1071]
**Storage Explorer Version:** 1.6.2
**Platform/OS Version:** Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture:** ia32/x64
**Build Number:** 20190115.1
**Commit:** ae10c367
**Regression From:** Not a regression

#### Steps to Reproduce: ####
1. Expand one ADLS Gen2 account -> 'Blob Containers'.
2. Open one blob container then upload a non-empty folder named 'Folder1'.
3. Create a new folder with empty content named 'Folder2'.
4. Try to rename the empty folder 'Folder2' to 'Folder1' -> Check the result.

#### Expected Experience: ####
Fail to rename the empty folder with the existing name.

#### Actual Experience: ####
Succeed to rename the empty folder with the existing name.
#### More info: ####
Actually, we cannot create two empty folders with the same name.
![image](https://user-images.githubusercontent.com/34729022/51173529-93a82a00-18f0-11e9-892d-7422a72b0ed5.png)

**Comment by craxal** [comment]
I observe that after the "rename", if I open "Folder1", there's a "Folder2" folder inside.

**Comment by MRayermannMSFT** [comment]
@craxal please continue to follow up with platform team

**Comment by craxal** [comment]
Platform team has confirmed they will be chiecking in changes today. There should be no work required on our end.

**Comment by craxal** [comment]
Just tested again. Still isn't working. Getting back in contact with storage folks.

**Comment by MRayermannMSFT** [comment]
CTI only bug. Can revisit if a customer opens an issue.
