### ISSUE TITLE
Fail to upload VHD files to one sub-folder of ADLS Gen2 blob containers

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1072]
**Storage Explorer Version:** 1.6.2
**Platform/OS Version:** Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture:** ia32/x64
**Build Number:** 20190115.1
**Commit:** ae10c367
**Regression From:** Not a regression

#### Steps to Reproduce: ####
1. Expand one ADLS Gen2 account -> 'Blob Containers'.
2. Open one blob container then create a folder.
3. Go to the created folder and upload a VHD file to it -> Check the result.

#### Expected Experience: ####
The VHD file can be uploaded to the sub-folder successfully.

#### Actual Experience: ####
Fail to upload the VHD file to the sub-folder with the below error.
![image](https://user-images.githubusercontent.com/34729022/51169861-ef21ea00-18e7-11e9-95ba-0d02c666b8ed.png)
#### More info: ####
This issue doesn't reproduce for normal blobs using AzCopy.

**Comment by craxal** [comment]
Can you click "Retry Transfers..." and show us the errors that come up there?

**Comment by v-xuanzh** [comment]
Hi @craxal ,click 'Retry Transfer...' with the error code:0
![image](https://user-images.githubusercontent.com/34729022/51649696-86f69680-1fc0-11e9-90bb-17172393d302.png)
Click 'Retry Selected' with Enable Overwrite still occurs the reported error.

**Comment by craxal** [comment]
I noticed you're uploading from a file share. @jinglouMSFT, we've seen this issue in the past. Is this supposed to be fixed now?

@v-xuanzh, can you try uploading the file from a location on your local machine? Does that succeed?

**Comment by MRayermannMSFT** [comment]
I was able to upload this file without issue. I would guess that there was just an issue with the quality/speed of @v-xuanzh 's connection to trinlab. @v-xuanzh , can you try copying the command and running it via powershell? I'm hoping we'll get a more descriptive error message from AzCopy that way.

**Comment by v-xuanzh** [comment]
Hi @craxal , I can upload the file from desktop without error.Seems like trinlab server's issue. 

But i am confusing, this issue doesn't reproduce when uploading a file from the server location to one normal blob container with AzCopy enabled.

**Comment by craxal** [comment]
AzCopy does things differently than the default method. Frankly, they do it better. I suspect Node sometimes has problems with file shares, especially if the file is large. AzCopy uses Go, which probably doesn't have the same problem.
