### ISSUE TITLE
Valid Cosmos DB query has incorrect syntax highlighting

### ISSUE THREAD

**Issue by scholtes** [microsoft/AzureStorageExplorer#1073]
**Storage Explorer Version**: `1.6.2` (`build no. 20190108.2` `commit b3158558`)
**Platform/OS**:  `Microsoft Windows [Version 10.0.16299.726]`
**Architecture**: `x64`
**Regression From**: Undetermined

**Bug description**
Valid Cosmos DB query has incorrect syntax highlighting when escaping single quotes within strings.

**Steps to Reproduce**
1. Create or obtain access to a Cosmos DB account with an existing collection
2. In Storage Explorer, go to the left blade with the tree viewer and expand the Cosmos DB account and expand a collection.  
3. Right click on "Documents", and click "Open Query Tab" in the right click menu.  
4. Paste the following text exactly into the query editor: 
```
SELECT * FROM c
WHERE CONTAINS(c.name, '\'')
ORDER BY c._ts DESC
```
5. Observe the syntax highlighting in the Query editor

**Expected Experience**
Escaping a single quote within a single quote delimited string is valid Cosmos DB syntax ([per reference](https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-query-reference)).  The syntax highlighter should recognize the end of a string correctly when there are escaped single quotes.  

**Actual Experience**
The syntax highlighter does not recognize backslash preceded single quotes as being escaped and instead interprets them as the beginning or end of a string literal (depending on their position).  This can cause text within a string to be seen as not part of a string literal, or text after the string literal to be seen as part of the literal.  See screenshot: 

![image](https://user-images.githubusercontent.com/3686667/51193485-97b35800-18ae-11e9-8a0a-e287a99ab93e.png)

**Additional Context**
This problem also exists in the Azure Portal.  If I had to guess they use the same highlighting engine, which likely uses a different parser than the actual back end query interpreter.

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
