### ISSUE TITLE
Azure Storage Explorer (client tool & portal) | "Folder Statistics" relates to irrelevant paths 

### ISSUE THREAD

**Issue by dumarkov** [microsoft/AzureStorageExplorer#1074]
Hi Team
There is a bug with the “Folder Statistics” functionality (client tool & portal).

Given the following directories and files (please note that the directory name myfolder is a prefix of the other directories):

```
rootfolder/
├── myfolder
│   └── myfile.txt
├── myfolder_a
│   └── myfile.txt
├── myfolder_b
│   └── myfile.txt
├── myfolder_c
│   └── myfile.txt
└── myfolder_d
    └── myfile.txt
```

When standing inside the folder myfolder and using “Folder Statistics” the given result is 5 blobs (instead of 1 blob).
Apparently, the lookup

 is done for /path/myfolder* instead of /path/myfolder/*

**Comment by MRayermannMSFT** [comment]
Duplicate of #1001
