### ISSUE TITLE
ERR_SSL_CLIENT_AUTH_SIGNATURE_FAILED

### ISSUE THREAD

**Issue by Jordi-f** [Microsoft/AzureStorageExplorer#1075]
**Bug description**
When trying to login to Azure AD for a MFA enabled account Azure storage explorer will fail to login with below error: ERR_SSL_CLIENT_AUTH_SIGNATURE_FAILED

This happens after entering the e-mail account, when the password is expected to be entered this errors comes up.

**Steps to Reproduce**
1. Open MASE
2. Login to MFA enabled account

**Expected Experience**
Expected would be that the password can be entered so the account is logged on to

**Actual Experience**
Not able to login

**Additional Context**
Following this guide did not resolve the issue https://docs.microsoft.com/nl-nl/azure/storage/common/storage-explorer-troubleshooting

**Comment by MRayermannMSFT** [comment]
@Jordi-f , so this happened during sign in, yes? Not while loading subscriptions.

**Comment by Jordi-f** [comment]
@MRayermannMSFT , correct after choosing Azure as a login method and providing the username this error occurs. Did not even make it to the password screen

**Comment by MRayermannMSFT** [comment]
What OS are you on?

**Comment by Jordi-f** [comment]
Any update @MRayermannMSFT  ?

**Comment by MRayermannMSFT** [comment]
Yes @Jordi-f . In 1.7.0 we're introducing the ability to optionally sign-in via device code flow, or as you may be more familiar with, copying a code from an app into a page in your browser, and then signing in via your browser.

I'm hoping that this different method of sign in will get you past this error. Unfortunately, it may also expose a similar error once we attempt loading your subscriptions. If that's the case, then troubleshooting this issue will become more difficult. I'm hoping that doesn't happen though.

If you're willing to try it out, you can go to Help -> Opt-in To Insider Builds.
![image](https://user-images.githubusercontent.com/21112697/52584072-04563f80-2de6-11e9-90c1-094e4bbcd0b4.png)
Then, go to Help -> Check for updates, wait for 1.7.0 to appear, and install it. Then once you install it, you can enable device code flow by going to Experimental -> Use Device Code Flow Sign In. 
![image](https://user-images.githubusercontent.com/21112697/52584173-3e274600-2de6-11e9-85af-6ed3cf5ed006.png)
Now try signing in.

And then let us know if you become fully unblocked.

**Comment by Jordi-f** [comment]
@MRayermannMSFT , works great! thanks a lot

**Comment by MRayermannMSFT** [comment]
No errors after that? Subscriptions loaded and everything?

**Comment by Jordi-f** [comment]
Everything works fine, no issues!

**Comment by MRayermannMSFT** [comment]
Ok. I'll go ahead and close this then. :)
