### ISSUE TITLE
Storage Explorer does not work with Data Lake Gen2

### ISSUE THREAD

**Issue by taylormoran** [Microsoft/AzureStorageExplorer#1076]
**Storage Explorer Version**: 1.6.2
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**: Never worked for me. 

**Bug description**

Storage Account v2 with HNS enabled and includes a DFS endpoint, will not appear as a Gen 2 in Storage Explorer. It also says HNS is not enabled. I've been working with the account using the Gen2 REST API and have created a container/filesystem successfully. 

**Steps to Reproduce**

1. Browse to storage account using ASE.

**Expected Experience**

The storage account being recognized including the indication on the account name that it's a HNS enable storage account.

**Actual Experience**

Receive error when trying to expand or create container under Blob Containers that the Blob API is not yet supported for HNS accounts.

**Comment by jinglouMSFT** [comment]
Did you sign into Azure or did you use name&key to connect to Azure?  Also, are you behind a proxy?  Thanks.

**Comment by taylormoran** [comment]
Signed into Azure. I have tried name and key previously though. Talked to network admin and we aren't behind a proxy.

**Comment by jinglouMSFT** [comment]
Could you share what you see in the Properties grid under the treeview on the left hand side?  what are the values for "HNS Enabled" and "DFS Endpoint"?  I just create two new accounts, one with LRS and one with RA-GRS replication. Both worked just fine. 
I don't know if the type of the subscriptions has caused the different behavior.

**Comment by taylormoran** [comment]
Sorry been away.

HNS Enabled is false and there is no DFS Endpoint either in the properties grid. My storage account has both HNS enabled and dfs endpoint though. I've tried updating Storage Explorer and use insider builds and none of them identify the storage account as ADLSGen2.

**Comment by jinglouMSFT** [comment]
This is weird.  Can you help try to create a new storage account with HNS enabled to see if Storage Explorer can identify it?  Thanks.

**Comment by taylormoran** [comment]
I used az cli to create a new storage account. 

> bash-4.4# az storage account create \
> --name fakename \
> --resource-group fakerg \
> --location eastus2 \
> --sku Standard_LRS \
> --kind StorageV2 \
> --hierarchical-namespace true

Snippets from the output:

> "isHnsEnabled": true,
> "kind": "StorageV2",
> "primaryEndpoints": {
>     "blob": "https://fakename.blob.core.windows.net/",
>     "dfs": "https://fakename.dfs.core.windows.net/",

ASE build 20190108.2 / 1.6.2 shows HNS Enabled as false and no dfs endpoint.

**Comment by taylormoran** [comment]
Version 1.7.0 Preview has fixed my issue. I was and still am connected through my Azure account and not through shared key and we're not behind a proxy (according to network admin), so I'm still unsure what the problem was.

**Comment by MRayermannMSFT** [comment]
Closing since you're unblocked. But I will ask, did you have Azure Stack mode enabled by chance?
