### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by ajitgoel** [Microsoft/AzureStorageExplorer#1078]
**Storage Explorer Version**: 1.6.2
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**: Was working before i reinstalled windows 10. 

**Bug description**
"Unable to retrieve child resources' error when i try to load the tables of the local azure storage(localdb database) in Azure storage explorer. I have tried to reinstall the localdb database, azure storage sdk including emulator, azure storage explorer. i have also tried to delete %AppData%\StorageExplorer folder to see if that helps but of no avail. 

**Steps to Reproduce**
try to load the tables of the local azure storage(localdb database) in Azure storage explorer.

**Expected Experience**
Azure storage explorer should be able to connect to the localdb database as a local azure storage.

**Actual Experience**
i get a "Unable to retrieve child resources' error when i try to load the tables of the local azure storage(localdb database) in Azure storage explorer.

**Additional Context**
i have raised several issues on but am still struggling:
1. https://stackoverflow.com/questions/54210507/azure-storage-explorer-server-encountered-internal-error 
2. https://social.msdn.microsoft.com/Forums/en-US/96c45ac5-a64a-49a7-9fc8-3f5874af338b/azure-storage-explorer-server-encountered-an-internal-error?forum=windowsazuredata
3. https://stackoverflow.com/questions/54176192/unable-to-connect-to-local-azure-storage-account/54179289#54179289

when i open the azure storage explorer  and try to load the tables from my localdb database, i see the following error messages. 

![image](https://user-images.githubusercontent.com/6394444/51364254-28518a00-1aa1-11e9-8ee3-c177b5ef364c.png)

![image](https://user-images.githubusercontent.com/6394444/51364056-584c5d80-1aa0-11e9-9c33-c8f985391c94.png)

![image](https://user-images.githubusercontent.com/6394444/51364074-6b5f2d80-1aa0-11e9-85ab-4b3d61238037.png)

in the azure storage explorer console window, i see the following warnings and errors:

C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\ExtensionLoader.js:79 Unable to load user extensions: Error: ENOENT: no such file or directory, scandir 'C:\Users\AjitGoel\AppData\Roaming\StorageExplorer\extensions'
(anonymous) @ C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\ExtensionLoader.js:79

/C:/Program%20Files%20(x86)/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Common/Debug.js:39 HTTP ERROR 409: Conflict
error @ /C:/Program%20Files%20(x86)/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Common/Debug.js:39

The emulator has been initialized and is started (I however see an "windows azure emulator is not installed" error message at the top).

![image](https://user-images.githubusercontent.com/6394444/51364596-44a1f680-1aa2-11e9-9131-4c1fb51b36e1.png)

**help in Azure storage explorer:**
Version: 1.6.2
Platform: Windows
Architecture: ia32
Build Number: 20190108.2
Commit: b3158558
Support Id: 60daa3f8-f7c0-9be9-6454-51454deb4c49

**Data in Application tab:**
Standalone_NetPromoterScoreDialog_v1 | {"launchCount":2} |  
-- | -- | --
Standalone_RolloutPercentile_v1 | {"default":{"name":"default","percentage":65},"null":{"name":null,"percentage":100},"60daa3f8-f7c0-9be9-6454-51454deb4c49":{"name":"60daa3f8-f7c0-9be9-6454-51454deb4c49","percentage":100}} |  
Standalone_Telemetry_OptInSetting | true |  
Standalone_Telemetry_UserId | "60daa3f8-f7c0-9be9-6454-51454deb4c49" |  
Standalone_VersionOnLastRun_v1 | "1.6.2" |  
StorageExplorer.AzureSubscriptionsManager.subscriptionCache | {"zWyNVGMIqNgteYIb-rQk90adUMrvyFayxIhotbyeKjw:107D38C8EA4DED548A0F4EE097AA83E8D0A4A0FAFDDCC2CACD854AAC42881A46":[{"id":"775910ce-a191-456f-a217-481d8b4895a8","accountId":"zWyNVGMIqNgteYIb-rQk90adUMrvyFayxIhotbyeKjw:107D38C8EA4DED548A0F4EE097AA83E8D0A4A0FAFDDCC2CACD854AAC42881A46","tenantId":"efc2baa6-3f45-454e-803b-8b7ceb84c8a8","name":"Free Trial","managementEndpoint":"https://management.azure.com/","coreEndpoint":"https://management.core.windows.net/","portalEndpoint":"https://portal.azure.com/","graphEndpoint":"https://graph.windows.net/","cloudName":"https://management.azure.com/","selected":true,"adalEndpoint":"https://management.core.windows.net/","isAzureStackSubscription":false,"isIsolatedCloud":false}]} |  
StorageExplorer.ExperimentalFeatures.Settings.v1 | {"AzCopy.Blob.Enable":false} |  
StorageExplorer_InPlaceQuickAccessItems_v1 | "WZGvjhlZROoop1Uyii1R

**Comment by jinglouMSFT** [comment]
Also, just to make sure everyone is aware of, the issues reported here are meant to be product bug reports. This is not a support form as some have mistakenly mentioned in stackoverflow or the MS forum. Storage Explorer actually has a dedicated support engineering team. You can follow the below link to request for support. https://docs.microsoft.com/en-us/azure/azure-supportability/how-to-create-azure-support-request. The support team probably can response to your request much quicker than we can. So please give them a try. Thank you!

**Comment by ajitgoel** [comment]
Thank you @jinglouMSFT , i have the azure storage emulator in my windows tray. 
one thing i have noticed is that when i start the azure storage emulator it does not provide any information about connecting to a localdb. I however see that the a database has been created in the localdb database server, so perhaps it is a connection issue or a permissions issue. 
wrt to the errors, i get the same error when i expanded the Blob node or the Queue node. 
adding the attachment to the storage explorer, i get the same error as the default attachment. 
i have not turned on the  Experimental->AzCopy in my azure storage explorer. 

i will do some more research by turning on fiddler and turning on logging in the azure storage explorer.

**Comment by ajitgoel** [comment]
I was able to get the application working by

a. removing LocalDB database, 
b. deleting the localdb created mdf, ldf files, 
c. installing "SQL server Express" and manually creating the database that the Azure Storage explorer needed, and then configuring Azure Storage explorer to work with "SQL server Express"
Please consider the issue as closed.
