### ISSUE TITLE
Going down virtual folder quickly when blob list is still loading causes storage explorer to go to a non-existing virtual folder

### ISSUE THREAD

**Issue by srikcgaa2** [microsoft/AzureStorageExplorer#1080]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: WIndows 10
**Architecture**: ia32
**Regression From**: No
#### Steps to Reproduce: ####
1. Open Storage Explorer
2. Go to any storage account
3. Select any container that has virtual folders.  Our container structure has a virtual folder which has a second virtual folder and all blobs are present under the second folder (say Folder1/Folder2/(all blobs here).  Folder2 contains a large number of blobs in the order of 1000s
4. Double click Folder1 to display Folder2 and quickly double click on it two times.

#### Expected Experience: ####
5. When I double click on folder2 for the first time, the storage explorer tries to enumerate all the blobs under this virtual folder.  While the spinner is still displayed, the second double click should NOT be allowed
#### Actual Experience: ####
5. Bug:- Observe that the storage explorer tries to go to Folder1/Folder2/Folder2 which never exists.  This happens because the second double click was allowed and it took the folder2 twice.  Check the red highlighted folder name depth in the attachment

In the attachment folder1 is Default and folder2 is 1.0.0 (Sirius is parent virtual folder to folder1 but for this discussion, I generalized it as folder1 and folder2)

![nonexistingfolder](https://user-images.githubusercontent.com/24926263/51444188-80df8c00-1d1a-11e9-8267-740e1cfb20e7.png)

**Comment by JasonYeMSFT** [comment]
We have reimplemented our data explorers and this should have been fixed. We now disable mouse events when the data explorer is in loading state which would prevent the 2nd navigation in this issue from happening.
