### ISSUE TITLE
Fail to expand Blob Containers node when attached using name/key on ADLS Gen 2 account

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1081]
**Storage Explorer Version**: 1.6.2_20190117.1
**Platform/OS Version**: Windows x64
**Architecture**: ia32
**Regression From**: Work well on release 1.6.0, Regression from release 1.6.1

**Repro Steps:**
1. Choose one ADLS Gen2 account -> Copy Primary Key ->Try to attach it using Key/Name like below.
**Display Name**: adlsxuantest
**Primary Key:** REDACTED
2. Once attached, go to '**Local & Attached**' ->'**Storage Accounts'** ->'**adlsxuantest**' -> '**Blob Containers**'.

**Expect**:
1. The Blob Containers node can be expanded successfully.
2. Show '**Key, ADLS Gen2 Preview'** next to the attached account.

**Actual**:
1. Fail to expand Blob Containers node with the below error.
2. Show '**Key**' net to the attached account.
![image](https://user-images.githubusercontent.com/34729022/51526109-9a90e880-1e6c-11e9-827d-b1c953e8e524.png)

**Comment by MRayermannMSFT** [comment]
Updated library merged into master. See my comment on #1112 for more info about this bug and some other side effects you may run into with $web
