### ISSUE TITLE
No default Start time and Expiry time display on 'Access Policies' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1085]
**Storage Explorer Version**: 1.6.2_20190123.3
**Platform/OS Version**: Windows x64/Linux Ubuntu 16.04/MacOS High Sierra
**Architecture**: ia32
**Commit**:e412c857
**Regression From**: Previous release 1.6.2

#### Steps to Reproduce: ####
1. Choose one non adls gen2 account ->Right click one blob container then select 'Manage Access Policies...'.
2. Click 'Add' -> Check the Start time and Expiry time for the added accees policy -> Save.
3. Right click the same blob container then select 'Get Shared Access Signature...' -> Select the added ploicy on the dropdown list -> Check the Start time and Expiry time on the SAS dialog.

#### Expected Experience: ####
Step2: Show the default Start time and Expiry time on the  'Access Policies' dialog.
Step3: SAS dialog shows the same Start time and Expiry time with default.

#### Actual Experience: ####
Step2: There is no default Start time and Expiry time.
![image](https://user-images.githubusercontent.com/34729022/51595161-0a68a700-1f31-11e9-87da-8d56af0b9ee2.png)

Step4: Only shows the Expiry time on SAS dialog.
![image](https://user-images.githubusercontent.com/34729022/51595167-0e94c480-1f31-11e9-92bb-cafaa3490e4a.png)

**Comment by craxal** [comment]
By design. Access policies do not need expiry or start times. This was done to fix #764.

**Comment by v-xuanzh** [comment]
@craxal ,
Also, the default expiry time with the current time shows on SAS dialog when selecting the set access policy(_no start time and expiry time_). Is it by design?
![image](https://user-images.githubusercontent.com/34729022/51648178-89ee8880-1fba-11e9-830c-27252c30e245.png)

**Comment by craxal** [comment]
No, but we're going to revert changes made here due to too many regressions. See #1092, #1093.
