### ISSUE TITLE
Remove the descriptions on Upload dialog for ADLS Gen2 accounts

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1086]
**Storage Explorer Version**: 1.6.2_20190123.3
**Platform/OS Version**: Windows x64/Linux Ubuntu 16.04/MacOS High Sierra
**Architecture**: ia32
**Commit**:e412c857
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Choose one ADLS Gen2 account -> Open one blob container.
2. Click 'Upload Files...' -> Check the dialog.

#### Suggestion: ####
Remove the descriptions because there is no distinction for ADLS Gen2 blobs(Block/Append/Page Blob).
![image](https://user-images.githubusercontent.com/34729022/51594201-d9877280-1f2e-11e9-8c68-7cc3c21ce9f6.png)

**Comment by craxal** [comment]
Won't fix. This will be relevant when blob interop is released.
