### ISSUE TITLE
Unable to upload 10 GB bak file with Storage Explorer

### ISSUE THREAD

**Issue by eftim** [Microsoft/AzureStorageExplorer#1088]
When uploading a bak file with a very stable optical connection I got this issue with Azure Storage Explorer 1.6.1 for Mac OS, even after several retries (at around 50%).

```json
{
  "name": "Error",
  "message": "write EPIPE",
  "stack": "Error: write EPIPE\n    at _errnoException (util.js:1024:11)\n    at WriteWrap.afterWrite [as oncomplete] (net.js:867:14)",
  "code": "EPIPE",
  "errno": "EPIPE",
  "syscall": "write"
}
```

**Comment by jinglouMSFT** [comment]
Did you sign into Azure or did you attach using SAS or Name/Key?  Did you also upload as a blob or as a file? If you upload as a blob, what blob type did you chose to use?  Have you tried to enable using AzCopy for your upload (through the Experimental top menu)?  Files in this size, I'd recommend using AzCopy for upload/download. You'll see dramatic performance improvement.

**Comment by eftim** [comment]
Thanks a lot for the suggestion. This indeed improved the speed dramatically and I managed to upload the file with it.

**Comment by jinglouMSFT** [comment]
Great to hear that you are able to upload the file. If you don't mind, i am closing the issue. Thanks for using Storage Explorer.
