### ISSUE TITLE
'Open' is enabled when selecting multiple files at the same time

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1091]
**Storage Explorer Version**: 1.6.2_20190123.7
**Platform/OS Version**: Windows x64/Linux Ubuntu 16.04/MacOS High Sierra
**Architecture**: ia32
**Commit**:2fbb86a9
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Open one file share ->Upload multiple files to it.
2. Select multiple file then check the 'Open' on the toolbar.

#### Expected Experience: ####
'Open' is disabled on the toolbar and context menu.

#### Actual Experience: ####
'Open' is enabled on the toolbar and context menu.
![image](https://user-images.githubusercontent.com/34729022/51667868-e9b95380-1ffb-11e9-87dc-e0fd13613447.png)
#### More info: ####
This issue doesn't reproduce when selecting multiple blob files at the same time.

**Comment by MRayermannMSFT** [comment]
Let's make sure open is disabled on multi-select.

**Comment by JasonYeMSFT** [comment]
Close as fixed.
