### ISSUE TITLE
Attaching blob container which set access policies with SAS URI causes an error

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1092]
**Storage Explorer Version**: 1.6.2_20190123.7
**Platform/OS Version**: Windows x64/Linux Ubuntu 16.04/MacOS High Sierra
**Architecture**: ia32
**Commit**:2fbb86a9
**Regression From**: Previous release 1.6.2

#### Steps to Reproduce: ####
1. Choose one non adls gen2 account -> 'Blob Containers' node.
2. Right click one blob container -> 'Manage Access Policies...'.
3. In the opened dialog, add one access policy using the default time and permission -> Save.
4. Right click the same blob container -> 'Get Shared Access Signature...' -> Select the added policy from the dropdown list on the SAS dialog -> 'Create'.
5. Check the result.

#### Expected Experience: ####
The selected blob container can be attached successfully.

#### Actual Experience: ####
Pop up the error for the attached blob container/file share.
Blob container:
![image](https://user-images.githubusercontent.com/34729022/51668262-cb078c80-1ffc-11e9-973b-93f6bcf8f01f.png)
File share:
![image](https://user-images.githubusercontent.com/34729022/51668280-d1960400-1ffc-11e9-8b5d-683ae3454a85.png)

**Comment by craxal** [comment]
By "default time", do you mean unspecified start and expiry times? Please be more specific.
