### ISSUE TITLE
Changing the applied subscriptions don't auto refresh the tree view of the Toggle Explorer

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1095]
**Storage Explorer Version**: 1.6.2_20190126.3
**Platform/OS Version**: Windows x64/Linux Ubuntu 16.04/MacOS High Sierra
**Architecture**: ia32
**Commit**:ac860e79
**Regression From**: Previous release 1.6.2

#### Steps to Reproduce: ####
1. Make sure you have logged into Storage Explorer and applied subscriptions.
2. Change the applied subscriptions ->Verify the tree view of the Toggle Explorer.

#### Expected Experience: ####
The tree view of the Toggle Explorer refreshes automatically.

#### Actual Experience: ####
The tree view of the Toggle Explorer needs to refresh manually.

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
