### ISSUE TITLE
Cmd+R/Ctrl+R should refresh the file listing, not reload the whole app viewport

### ISSUE THREAD

**Issue by stewartadam** [Microsoft/AzureStorageExplorer#1097]
**Storage Explorer Version**: 1.6.2
**Platform/OS**: macOS
**Architecture**: x64
**Regression From**: No

**Bug description**
Conventionally, Cmd+R/Ctrl+R is used to refresh the page. In Storage Explorer, it reloads the whole Electron application and destroys whatever workflow the user had in progress.

**Steps to Reproduce**
1. Start doing something in the app (i.e. navigate somewhere)
2. Press Cmd+R/Ctrl+R

**Expected Experience**
File listing should refresh itself.

**Actual Experience**
Whole app reloads, navigating back to root.

**Comment by craxal** [comment]
What you're essentially asking for is a keyboard shortcut for Refresh, correct? We have several places that have a Refresh command, and they all refresh different things. Can you explain in more detail what you mean by "start doing something" so that we have a better idea of what you'd like?

**Comment by stewartadam** [comment]
> What you're essentially asking for is a keyboard shortcut for Refresh, correct?
Yes, and specifically to have it be Cmd/Ctrl+R which is the conventional shortcut for refresh list

> We have several places that have a Refresh command, and they all refresh different things
In this case I mean the container's file list (since it doesn't auto-refresh and this is most likely what I want to refresh vs my list of subscriptions, for example)

> Can you explain in more detail what you mean by "start doing something" so that we have a better idea of what you'd like?
e.g. open any storage account, browse to a container and start uploading/downloading a file and then hit Ctrl+R/Cmd+R. The whole app viewport reloads (I presume it reinits the Electron app or something) and so progress through any user workflow is lost.

**Comment by craxal** [comment]
Thanks! OK, we can add this to our backlog for an upcoming release.

**Comment by MRayermannMSFT** [comment]
When we fix this, don't forget to change reload command to have a new shortcut as well!

**Comment by kieronlanning** [comment]
I'm going out of my mind with this! I keep CTRL+R'ing and losing my place.

**Comment by craxal** [comment]
@kieronlanning We'll consider this a 👍+1 to getting it fixed. 😉 We've put this in our 1.8.0 milestone.

**Comment by kieronlanning** [comment]
@craxal Amazing work, thank-you! 

I can't seem to fight my muscle memory for this one.
