### ISSUE TITLE
Can't upload from really deep/long paths.

### ISSUE THREAD

**Issue by JakeRadMSFT** [microsoft/AzureStorageExplorer#11]
**Storage Explorer Version**: 0.9.6

**OS Version**: Windows (all)

#### Steps to Reproduce:

1. Try to upload from extremely deep path

#### Expected Experience:
Successfully uploads

#### Actual Experience:
Fails to upload. Perhaps because "path" starts to contain "~1" for some folders.

**Comment by MRayermannMSFT** [comment]
Closing after doing some testing this morning and not being able to repro. If we hear any user complaints about this we can investigate.
