### ISSUE TITLE
No way to see current access tier of a storage account

### ISSUE THREAD

**Issue by MRayermannMSFT** [Microsoft/AzureStorageExplorer#110]
**Storage Explorer Version**: 1.1.0 RC ()
**Platform**: Linux
**Architecture**: x64
**Build Number**: 2018501.1
**Commit**: 754b96f7
**Regression From**: N/A

#### Steps to Reproduce: ####

1. Reveal a Storage Account in the tree view (one that can have an access tier)

#### Expected Experience: ####
1. The current access tier is in the properties pane
2. When I go to change the access tier, the change access tier dialog should let me know which of the two options is the current one

#### Actual Experience: ####
Access tier is not in the properties pane, and I don't know which access tier is the current one when looking at the dialog

**Comment by JakeRadMSFT** [comment]
Out for PR for 1.1.0
