### ISSUE TITLE
The name of the metadata/properties always shows the default name even though changed it

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1103]
**Storage Explorer Version:** 1.6.2/20190129.6
**Platform/OS Version:** Windows x64/Linux Ubuntu 16.04/MacOS High Sierra
**Architecture:** ia32
**Commit:** 07adac3b
**Regression From:** Previous release 1.6.2

#### Steps to Reproduce: ####
1. Expand any one account -> Open one blob container which contains one blob at least.
2. Right click the blob then select 'Properties...' -> Add one metadata/property for it(There indicates the default name and value).
3. Try to change the default name of the metadata -> 'Save'.
4. Reopen the same Properties dialog -> Check the updated properties.

#### Expected Experience: ####
The name of the metadata is updated successfully.

#### Actual Experience: ####
The name of the metadata still shows the default name 'Metadata1'.
![image](https://user-images.githubusercontent.com/34729022/51963552-0099f300-249f-11e9-8b26-c50276841590.png)

#### More info: ####
1. This issue reproduces for all the Properties dialog(File Properties, Directory Properties, ADLS Gen2 blob/blob containers Properties)
2. This issue doesn't reproduce for the value of metadata/properties.

**Comment by MRayermannMSFT** [comment]
Fix merged into master. @v-xuanzh , thank you for the excellent testing of the properties dialog recently. 😄 Please continue to test it as much as you can. Thanks!

**Comment by v-xuanzh** [comment]
Got it. 😄
