### ISSUE TITLE
Error to remove files with Azure Storage Explorer

### ISSUE THREAD

**Issue by ngallard** [Microsoft/AzureStorageExplorer#1104]
```json
{
  "name": "StorageError",
  "message": "This request is not authorized to perform this operation using this permission.\nRequestId:cb884691-101e-008f-5d77-b8c964000000\nTime:2019-01-30T08:38:10.2327255Z",
  "stack": "StorageError: This request is not authorized to perform this operation using this permission.\nRequestId:cb884691-101e-008f-5d77-b8c964000000\nTime:2019-01-30T08:38:10.2327255Z\n    at Function.StorageServiceClient._normalizeError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:1198:23)\n    at Object.StorageServiceClient._processResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:744:50)\n    at Request.processResponseCallback [as _callback] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:317:37)\n    at Request.self.callback (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1157:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1079:12)",
  "code": "AuthorizationPermissionMismatch",
  "statusCode": 403,
  "requestId": "cb884691-101e-008f-5d77-b8c964000000"
}
```

**Comment by ngallard** [comment]
Goor morning,

Thanks for your answer.
Actually, i do not have any knowledge in Azure Storage Explorer.
I needed to import pst files into Azure, to be able to import them in Office 365.

When the import process is finished, I have now to remove those pst files from azure.

So, a consultant told us to do it with Azure explore, but is seems I am not able to remove those files.

So, how can I process?

Thanks for your feedback,

Nicolas

De : v-xuanzh <notifications@github.com>
Envoyé : mercredi 30 janvier 2019 10:26
À : Microsoft/AzureStorageExplorer <AzureStorageExplorer@noreply.github.com>
Cc : Nicolas GALLARD <ngallard@batistyl.fr>; Mention <mention@noreply.github.com>
Objet : Re: [Microsoft/AzureStorageExplorer] Error to remove files with Azure Storage Explorer (#1104)


Hi @ngallard<https://github.com/ngallard> Is it an attached account using SAS connection string? Looks like you do not have write permission for this destination file.

[image]<https://user-images.githubusercontent.com/34729022/51971392-fc2c0500-24b3-11e9-928c-c39c4e1880d7.png>

**Comment by v-xuanzh** [comment]
@jinglouMSFT ,Could you help to take a look?

**Comment by craxal** [comment]
@ngallard, I assume you received a SAS token or URL from Office 365? Can you share that with us here, please? Be sure to remove the `sig` part of the SAS token.

To speed up the process, please follow our bug template to provide us important information, including the Storage Explorer version you're using, OS, architecture, and steps followed to reproduce the error.

**Comment by craxal** [comment]
Closing bug due to inactivity. If you still see this bug, please let us know along with providing relevant info, and we can reactivate.

**Comment by craxal** [comment]
@andymdpage The error suggests you don't have permission to delete the blob from the container. Unfortunately, it's not apparent from the SAS alone what permissions you actually have, since it is purely based on an access policy (the "si" property in the URI). You may need to contact someone from Office 365 to find out what permissions "IngestionSasForAzCopy" has.

**Comment by andymdpage** [comment]
Hi craxal Thanks for the advice I have logged a call with the Azure Office 365 support portal. 
Andy
