### ISSUE TITLE
Rename/Copy when using rbac

### ISSUE THREAD

**Issue by kdutt** [Microsoft/AzureStorageExplorer#1107]
**Storage Explorer Version**: 1.6.2
**Platform/OS**: Windows 10
**Architecture**: x64

**Bug description**
Blob item Rename, Copy unavailable when using rbac.

**Steps to Reproduce**
1. Apply RBAC role (ex: Storage Blob Data Contributor (Preview)) to a blob container
2. Open Storage explorer, select blob item.
3. Copy/Rename options are greyed out.

**Comment by MRayermannMSFT** [comment]
Hi @kdutt , this is because copy and paste requires a SAS token, which we cannot generate if you are accessing the container via RBAC. I believe the Storage backend team is working on a solution for this issue, so when one is available we will onboard it when we can.
