### ISSUE TITLE
Install option for non privileged (no admin) users in Windows systems

### ISSUE THREAD

**Issue by RogerCD** [microsoft/AzureStorageExplorer#1108]
This is just a request to release an Azure Storage explorer edition with the capability to install for local users with no administrator rights like work, school, shared computers.

This is a feature already available for Visual Studio Code and Azure Data Studio, and I use both. It would make a great value-add for end users working in restricted environments.

Thanks.

**Comment by craxal** [comment]
Great suggestion. @MRayermannMSFT, do we know why administrator permissions are required during installation?

**Comment by Nirmal4G** [comment]
So by default it installs for all users in the `Program Files` dir?

**Comment by kasuteru** [comment]
I can second that this should really be an option. Ideal would be to test for admin rights, and continue with a by-user installation if none are given. But as a first step, a question in the beginning would be welcome as well... right now almost nobody in our company can use it, and tbh, the web-based explorer is awful.

**Comment by kasuteru** [comment]
Thank you for the update on this, I really hope this makes it into 1.11.0. Having to use the web interface to manage data in the ADLS is one of the major complaints we keep getting from our users, and company policy prevents us from giving users admin rights...

**Comment by craxal** [comment]
From what I can tell, the only piece of our installation that requires admin privileges is the registry write to HKEY_CLASSES_ROOT we make to support direct links. I'm looking into whether there's a similar registry write we can do that doesn't require admin privileges.

My current leads:

- https://stackoverflow.com/questions/53135/what-registry-access-can-you-get-without-administrator-privileges
- https://docs.microsoft.com/en-us/windows/win32/winprog64/shared-registry-keys

**Comment by kasuteru** [comment]
> From what I can tell, the only piece of our installation that requires admin privileges is the registry write to HKEY_CLASSES_ROOT we make to support direct links. I'm looking into whether there's a similar registry write we can do that doesn't require admin privileges.

I think the default install location will also cause problems: Admin rights are always needed to install to the Program Files folder. Currently, the Admin prompt pops up before selecting the folder, so users that do not have privileges will not even get to that part.

What a lot of programs do is ask at the very beginning whether the program should be installed only for the user (to appdata) or for every user (to Program Files) and only request admin privileges if the user selects all users.

See also: https://en.wikipedia.org/wiki/User_Account_Control#Tasks_that_trigger_a_UAC_prompt

**Comment by RogerCD** [comment]
> I think the default install location will also cause problems: Admin rights are always needed to install to the Program Files folder. Currently, the Admin prompt pops up before selecting the folder, so users that do not have privileges will not even get to that part.
>...
> In our case, users would gladly have a limited user-only install without direct links, so a selection in the beginning ("Full" or "Light" install) would be perfectly fine and shouldn't be too hard to implement. Feel free to contact me if you need beta testers for this feature.

As a solution for that, we can better adopt the current model that Microsoft has for [Visual Studio Code](https://code.visualstudio.com/#alt-downloads) and [Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/download?view=sql-server-2017). For both products, they have two different installers. One installer is for a privileged user with admin rights and the other installer is for normal users with no privileges at all.

**Comment by kasuteru** [comment]
> As a solution for that, we can better adopt the current model that Microsoft has for [Visual Studio Code](https://code.visualstudio.com/#alt-downloads) and [Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/download?view=sql-server-2017). For both products, they have two different installers. One installer is for a privileged user with admin rights and the other installer is for normal users with no privileges at all.

I think this would be a good solution. I like that they explain the difference for Azure Data Studio, so that people know which version to use:

> The user installer is recommended because it does not require administrator privileges, which simplifies both installs and upgrades. The user installer does not require Administrator privileges as the location is under your user Local AppData (LOCALAPPDATA) folder. The user installer also provides a smoother background update experience. For more information, see User setup for Windows.

**Comment by craxal** [comment]
After some experimentation with a sample application, I've figured out how to install without needing admin privileges and confirmed that everything works by modifying the following:

1. Install to %LOCALAPPDATA% instead of %PROGRAMFILES%
2. Register custom app URL by writing to HK_CURRENT_USER instead of HK_CLASSES_ROOT.

Still need to figure out how to do these:
1. Parameters defined in URL are received by the application correctly (via command line arguments).
2. The uninstaller does not need admin privileges. Currently, the uninstaller requests admin privileges when run on my machine, but I'm not sure if it's just because my user _is_ an admin, and therefore ask for privileges by default.

**Comment by StingyJack** [comment]
@craxal - i cant tell if this is done and available or not from these last few status updates.

**Comment by craxal** [comment]
@StingyJack This has been available since 1.13.0. You will likely have to uninstall Storage Explorer first before the option becomes available, because updates use the same privileges as the existing installation.

**Comment by StingyJack** [comment]
That existing install from before 1.13.0 is exactly what the user is running into. He will just have to wait for IT to update his installation.
