### ISSUE TITLE
In activities for changing the access tier, a space is missing ("AccessTier")

### ISSUE THREAD

**Issue by MRayermannMSFT** [Microsoft/AzureStorageExplorer#111]
**Storage Explorer Version**: 1.1.0 RC ()
**Platform**: Linux
**Architecture**: x64
**Build Number**: 2018501.1
**Commit**: 754b96f7
**Regression From**: N/A

#### Steps to Reproduce: ####

1. Start changing the access tier of a Storage Account
2. Cancel out of the dialog

In the activity saying I cancelled the change, a space is missing between the words "Access" and "Tier".

![image](https://user-images.githubusercontent.com/21112697/39487368-d5abd2d2-4d33-11e8-8136-c28af2c9b195.png)

Also, the wording of that is really weird. "User cancelled"? Who is the activity log talking to? Just say "Cancelled changing the default access tier of <storage account name>"

**Comment by JakeRadMSFT** [comment]
Out for PR for 1.1.0
