### ISSUE TITLE
stalled loading initial load - 

### ISSUE THREAD

**Issue by trghpy** [Microsoft/AzureStorageExplorer#1113]
**Storage Explorer Version**: 1.6.2
**Platform/OS Version**: MacOS 10.13.6
**Architecture**: x64
**Regression From**: N/A

#### Steps to Reproduce: ####

1. Installed the app.
2. Tried to run the app. Stuck at "Loading".

#### Expected Experience: ####

Present a sign in prompt or some sign of working.

#### Actual Experience: ####

App spins forever saying "Loading"

Deleted App Support folder and restarted.  No help.

App Support folder doubled in size, 300k to 600k after 10 minutes. No change after 30 minutes.

Exits gracefully.

**Comment by craxal** [comment]
Can you open Activity Monitor and see how may Storage Explorer processes open up?

**Comment by trghpy** [comment]
My apologies for not checking back in. 

After reboot the software worked as expected. 

Mike!
