### ISSUE TITLE
Read-only access to Cosmos DB

### ISSUE THREAD

**Issue by webbermt** [microsoft/AzureStorageExplorer#1114]
**Storage Explorer Version**: 1.6.2
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:

**Bug description**
Read-only access to Cosmos DB is not working.  Cosmos DB requires user to have DocumentDB Account Contributor RBAC role or the read-write connection string.

**Steps to Reproduce**
1. Create Cosmos DB account
2. Assign user Cosmos DB Account Reader Role at resource group or Cosmos DB resource scope
3. Login to Azure Storage Explorer using user account from step 2
4. Try to open the Cosmos DB database created in step 1
5. Receive error: Cannot connect to this CosmosDB account

**Expected Experience**
The user should be able to view the Cosmos DB account information in read-only mode through the Cosmos DB Account Reader Role RBAC assignment or the read-only Cosmos DB account connection string.

**Actual Experience**
The user is unable to connect to the Cosmos DB account

**Additional Context**
User needs to have DocumentDB Account Contributor RBAC role to connect to the Cosmos DB account which allows read-write access.

**Comment by sebcruz** [comment]
I have the same issue.  I was granted ‘Cosmos DB Account Reader Role’ and can view collections and data in the Portal's Data Explorer, but will receive "The requested action could not be completed. Details: Cannot connect to this CosmosDB account. The account may in create or delete process. Please refresh the account list later and try again."

**Comment by vineet761** [comment]
Any update on this issue ?? It is still not able to have read only access - any workarounds apart from accessing from Azure portal exlorer ???

**Comment by JFolberth** [comment]
FYI ran into this as well.

Believe the issue is the default storage explorer is looking for `Microsoft.DocumentDB/databaseAccounts/listkeys/action`

This action is not part of the Account Reader Role. `Microsoft.DocumentDB/databaseAccounts/readonlykeys/action` is.  Thus, it is failing.

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
