### ISSUE TITLE
Unable to sign in using the general way after you have logged into accounts using device code flow

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1115]
**Storage Explorer Version:** 1.6.2/20190201.1
**Platform/OS Version:** Windows x64/Linux Ubuntu 16.04/MacOS High Sierra
**Architecture:** ia32
**Commit:** f30fe10c
**Regression From:** Not a regression

#### Steps to Reproduce: ####
1. Enable 'Use Device Code Flow Sin-in' from Experimental menu.
2. Open Connect dialog and sign in with your account(Open a web browser then paste the code).
3. After sign-in successfully, Disable 'Use Device Code Flow Sin-in' from Experimental menu.
4. Try to open Connect dialog -> Choose **the same account type** with the added account in step2 -> Sign in...(Use the general way).

#### Expected Experience: ####
There is no error.

#### Actual Experience: ####
An error occurs as below.
![image](https://user-images.githubusercontent.com/34729022/52112956-fc0e3f80-2642-11e9-837a-224f0803c5b1.png)

#### More info: ####
This issue doesn't reproduce if you choose one differenrt account type in step4.

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
