### ISSUE TITLE
An extra error message shows after renaming one blob with the same name

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1116]
**Storage Explorer Version:** 1.6.2/20190201.1
**Platform/OS Version:** Windows x64/Linux Ubuntu 16.04/MacOS High Sierra
**Architecture:** ia32
**Commit:** f30fe10c
**Regression From:** Not a regression

#### Steps to Reproduce: ####
1. Expand one non-adls gen2 account -> Open one blob container which contains one blob at least.
2. Select one blob and rename it with the same name ->Check the log message.

#### Expected Experience: ####
There only shows '**_Skipped renaming ...,New name provided is identical_**' and no error shows.

#### Actual Experience: ####
Show an extra error message except for the skipped activities.
![image](https://user-images.githubusercontent.com/34729022/52113266-d6ce0100-2643-11e9-832a-5860bb5776d2.png)
#### More info: ####
This issue doesn't reproduce for adls gen2 blobs.

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
