### ISSUE TITLE
The 'Save' button is disabled after removing the access policy with errors on 'Manage Access' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1117]
**Storage Explorer Version:** 1.6.2/20190201.1
**Platform/OS Version:** Windows x64/Linux Ubuntu 16.04/MacOS High Sierra
**Architecture:** ia32
**Commit:** f30fe10c
**Regression From:** Not a regression

#### Steps to Reproduce: ####
1. Right click one normal blob container -> Select 'Manage Access Policies...'.
2. Add a policy then delete the expiry time(There shows an error with the red border).
3. Remove the policy with error -> Check the 'Save' button

#### Expected Experience: ####
The 'Save' button is enabled.

#### Actual Experience: ####
The 'Save' button is disabled.
![image](https://user-images.githubusercontent.com/34729022/52113791-455f8e80-2645-11e9-94e0-dafc0951bf70.png)
![image](https://user-images.githubusercontent.com/34729022/52113795-485a7f00-2645-11e9-88e6-ce2bb89558a2.png)

**Comment by MRayermannMSFT** [comment]
Craig merged a fix into master.
