### ISSUE TITLE
"Add to Quick Access" can be performed more than once for one same item

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#1118]
**Storage Explorer Version:** 20190201.1
**Platform/OS Version:** Windows x64/Linux Ubuntu 16.04/MacOS High Sierra
**Architecture:** ia32
**Commit:** f30fe10c
**Regression From:** Not a regression

#### Steps to Reproduce: ####
1. Select a storage account under one subscription.
2. Right click the account -> Add the account to Quick Access twice.
3. Navigate to Quick Access -> Remove the added storage account.
4. Check whether the account shows under Quick Access or not.

#### Expected Experience: ####
The storage account doesn't show under Quick Access.
#### Actual Experience: ####
The storage account still shows under Quick Access.

**More Info:**
1. This issue doesn't  reproduce for attached items. 
2. The storage account disappears after performing "Remove from Quick Access" at the second time.

**Comment by MRayermannMSFT** [comment]
Craig merged a fix into master.
