### ISSUE TITLE
Standard Upload Cannot Upload .app on macOS

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1119]
**Storage Explorer Version:** 1.6.2/20190201.1
**Platform/OS Version:** MacOS High Sierra
**Architecture:** ia32
**Commit:** f30fe10c
**Regression From:** Not a regression

#### Background: ####
1. On MacOS, unzip the set up package of Storage Explorer - StorageExplorer-darwin-64.zip.
2. Open the unzipped folder, it shows the layout as below
![image](https://user-images.githubusercontent.com/34729022/52115834-8e661180-264a-11e9-82a7-1780d1fbfc81.png)

3. Try to upload **Microsoft Azure Storage Explorer.app**(Actually, it is a directory) to one blob container/file share.
#### Actual Experience: ####
1. We have no way to upload **Microsoft Azure Storage Explorer.app** as a directory, because it is disabled.
![image](https://user-images.githubusercontent.com/34729022/52115586-e9e3cf80-2649-11e9-953c-8178b474de54.png)
2. Fail to upload it as a file with the below error.
![image](https://user-images.githubusercontent.com/34729022/52115651-1992d780-264a-11e9-806b-08cd608f71ae.png)

**Comment by MRayermannMSFT** [comment]
Yep, definitely not a regression. I'm going to rename this bug to something a little more general, and we'll fix it later.

**Comment by MRayermannMSFT** [comment]
More info:
- .app files are actually folders
- when we open the finder on mac though, and ask for folders, .apps are greyed out, so you have to upload them as files
- this causes the .app file to be treated as a file in our local file query, which means we try to upload it instead of traversing it
- this causes the node sdk to get upset, and the upload fails

**Comment by MRayermannMSFT** [comment]
Fix merged into master.

**Comment by v-xuanzh** [comment]
Hi @MRayermannMSFT , We are confused about this fixes.

For now, We can upload the .app using '**Upload File**' on Upload dialog, 
After uploading successfully, The .app shows as a **folder**. 

I think these two behaviors are conflict.
