### ISSUE TITLE
The opened Storage Explorer doesn't close automatically after uninstalling it from Control Panel

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1120]
**Storage Explorer Version:** 1.6.2/20190201.7
**Platform/OS Version:** Windows x64
**Architecture:** ia32
**Commit:** 4c7d5de3
**Regression From:** Not a regression

#### Steps to Reproduce: ####
1. Install Storage Explorer then open it.
2. Uninstall the opened Storage Explorer -> Check whether the opened application is closed or not.

#### Expected Experience: ####
The opened Storage Explorer is closed automatically.

#### Actual Experience: ####
The opened Storage Explorer still opens and we have to close it from Task Manager.

**Comment by craxal** [comment]
Won't fix. Very unlikely scenario.
