### ISSUE TITLE
Authentication issues

### ISSUE THREAD

**Issue by simonlid** [microsoft/AzureStorageExplorer#1123]
**Storage Explorer Version**: January 2019 (Version 1.6.2)
**Platform/OS**: Windows 10, Version 1809 Build 17763.253
**Architecture**: x64

**Bug description**
Error authenticating using MFA when you belong to several organistations and the orgs have different emails for the account. 

**Steps to Reproduce**
I have an account which is alias@microsoft.com my default email address is firstname.lastname@microsoft.com. My account has been added to customers AD through B2B. I then add my alias@microsoft.com as the account since that is what my Azure subscription is tied to.

**Expected Experience**
I expect that I should get a single MFA request and be able to sign in to my Azure subscription

**Actual Experience**
When I sign in as alias@microsoft.com I first get a ton of MFA requests and then at the end it fails with the following error message:

{
  "message": "\"User 'firstname.lastname@microsoft.com' returned by service does not match user 'alias@microsoft.com' in the request\""
}

**Comment by jonmach** [comment]
I have the same problem. Running on 1.8.1 (Mac).

**Comment by MRayermannMSFT** [comment]
Hi, sorry that you're having sign in issues. There's some fairly involved steps I'd like you to take to help us diagnose what's going wrong. I know it's a lot, but this is what will help us figure out how to help you. If you have any problems with the below steps let us know and we'll do our best to help you. If you don't have time to do all of these steps, then you can probably ignore the proxy and Fiddler stuff for now, but it's usually easiest to get all of this collected in one go.

Note: these steps are for Windows, let me know if you need them for another OS.

Part 1: Reset Auth/Sign Out of Everything
1. Open Storage Explorer
2. Go to "Help" -> "Reset", make sure "Authentication" is selected (you can deselect "Quick Access" if you'd like), click "Reset"
3. After the reset dialog closes, go to "Edit" -> "Configure Proxy". Enable proxy, set the URL to 'http://localhost' and the port to '8888' (if you already have a proxy, skip this step and ignore all steps related to Fiddler), click "OK"
4. Close Storage Explorer

Part 2: Setup Fiddler
1. Install Fiddler from https://www.telerik.com/fiddler (Note: you can put in a fake email when they ask you for one 😋)
2. Start Fiddler
3. Go to Tools -> Options
4. Click on the HTTPS tab
5. Make sure Capture HTTPS CONNECTs and Decrypt HTTPS traffic are checked
6. Click on the Actions button
7. Choose "Trust Root Certificate" and then "Yes" in the next dialog
8. Click on the Actions button again
9. Choose “Export Root Certificate to Desktop”
10. Go to your desktop
11. Find the FiddlerRootCer file
12. Double click to open
13. Go to the "Details" tab
14. Click "Copy to File…"
15. In the export wizard choose the following options
    - Base-64 encoded X.509
    - For file name, Browse… to `C:\Users\<your username\AppData\Roaming\StorageExplorer\certs`, and then you can save it as any file name
16. Close the certificate window

Part 3: Clear Auth Logs
1. Go to C:\Users\<your username>\AppData\Local\Temp\servicehub\logs
2. Delete Everything

Part 4: Try Signing In!
1. Open PowerShell
2. Goto where Storage Explorer is installed, if you installed at the default location you can just do `cd 'C:\Program Files (x86)\Microsoft Azure Storage Explorer\'`
3. Execute `$env:SERVICEHUBTRACELEVEL="all"`
4. Close as many other running programs as possible (excluding Fiddler and PowerShell)
5. Start Storage Explorer from PowerShell: `.\StorageExplorer.exe`
6. Try signing in, after your issue happens, close Storage Explorer
7. In Fiddle, in the bottom left where it says "Capturing", click that, and then "File" -> "Save All Sessions", and save the file wherever you'd like

Part 5: Share results with us
1. Go back to `Go to C:\Users\<your username>\AppData\Local\Temp\servicehub\logs`
2. Zip up all of the log files and attach them to a comment on this issue
3. Do not attach us the file you saved in Part 4!!! If we need that, we'll give you an email to send it to. That type of file can contain some super sensitive information so we do not want you putting it in a public place.

PS: @jonmach, let me know if you're up to also try these steps. I can give you similar instructions that will work on Mac.

**Comment by jonmach** [comment]
Thanks for this, but I’m using a Mac

**Comment by MRayermannMSFT** [comment]
And you were also the only one of like 5 people I asked for logs to reply. 😆 I'll come up with some steps later today. Thanks!

**Comment by jonmach** [comment]
No probs - thank you.

**Comment by MRayermannMSFT** [comment]
Hey, sorry I never got back to you. We started working on onboarding a new auth library, and instead of having you waste time investigating something we plan on getting rid of, I decided to focus on the new library. We have a private build available that we're distributing to see if it can help anyone who has recent issues. So it'd be great if you could try it out and let us know if it resolves your problems.

You can download the private build here:
- Windows: https://aka.ms/storageexplorer/msal/windows 
- Mac: https://aka.ms/storageexplorer/msal/macos 
- Linux: https://aka.ms/storageexplorer/msal/linux 

To enable the new auth library, go to Settings (gear icon) -> Application -> Sign-in -> Microsoft Authentication Library (Preview), and then click the checkbox and restart. 

Since this is a private build, we do not recommend using it long term, or on production data.

Let us know if the build resolves your issue. Thanks!

**Comment by MRayermannMSFT** [comment]
Going to go ahead and close this as we're shipping 1.11.1. If you run into any problems please let us know via a new issue.

**Comment by jonmach** [comment]
Hi Matthew,

Sorry, I didn't see your earlier mail. Thanks.  I'll download the latest version and let you know if I have any issues.

Cheers 

Jon
