### ISSUE TITLE
The attached item isn't focused when 'Storage Accounts' node doesn't expand

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#1124]
**Storage Explorer Version:** 1.7.0/[20190208.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2399505&view=results)
**Platform/OS Version:** Windows x64\Linux\MacOS
**Architecture:** ia32
**Commit:** d247f51b
**Regression From:** Not a regression

#### Steps to Reproduce: ####
1. Reload Storage Explorer.
2. Use SAS to attach a storage account.
**_Account Name:_** testyan1
**_SAS URL:_** [REDACTED]

#### Expected Experience: ####
The attached account is focused and expanded.

#### Actual Experience: ####
The attached account isn't focused and expanded.

**More Info:**

This issue doesn't reproduce when 'Storage Accounts' node is expanded.

**Comment by craxal** [comment]
@v-xianya Can you do this again and confirm this reproduces?

**Comment by v-xianya** [comment]
Hi @craxal, Follow the reproduce steps using build 20190311.1. This issue still reproduces.

**Comment by MRayermannMSFT** [comment]
Going to label this won't fix. Will fix if customers give similar feedback.
