### ISSUE TITLE
Show an extra value of CacheControl on Properties dialog for the new created ADLS Gen2 folders

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1125]
**Storage Explorer Version**: 1.7.0/20190208.3
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Commit**: d247f51b
**Regression From**: Regression from release 1.7.0/20190208.2

#### Steps to Reproduce: ####
1. Expand one ADLS Gen2 account -> 'Blob Containers' node.
2. Open one blob container and create a new folder -> Right click the created new folder then select 'Properties...'.
3. Check the value of CacheControl on Properties dialog.

#### Expected Experience: ####
The value of CacheControl is empty.

#### Actual Experience: ####
The value of CacheControl is 'max-age=0'.
![image](https://user-images.githubusercontent.com/34729022/52551265-aaba3900-2e16-11e9-9501-b5430043bc97.png)
#### More info: ####
1. This issue doesn't reproduce for uploaded folders.
2. This issue doesn't reproduce for blob files.

**Comment by MRayermannMSFT** [comment]
Talked to someone on the server side. They side this is their change. Closing as won't fix.
