### ISSUE TITLE
Keep the values of default ports consistent between 'Attach to Local Emulator' dialog and AzureStorageEmulator.exe.config file

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#1126]
**Storage Explorer Version:** [20190208.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2399505&view=results)
**Platform/OS Version:** Windows x64\Linux\MacOS
**Architecture:** ia32
**Commit:** d247f51b
**Regression From:** Not a regression

#### Steps to Reproduce: ####
1. Open the local file AzureStorageEmulator.exe.config("C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe.config") -> Update services ports like below.
![image](https://user-images.githubusercontent.com/41351993/52553311-09cf7c00-2e1e-11e9-8ca4-6aba05a17b07.png)

2. Restart Azure Storage Emulator and open Storage Explorer.
3. Open Connect dialog  -> Attach to a local emulator -> Click 'Next'.
4. Check the values of default ports on 'Attach to Local Emulator' dialog.

#### Expected Experience: ####
The values of default ports on 'Attach to Local Emulator' dialog are consistent with the updated values on AzureStorageEmulator.exe.config file.
#### Actual Experience: ####
The values of default ports still show 10000,10001,10002 on 'Attach to Local Emulator' dialog.
![image](https://user-images.githubusercontent.com/41351993/52552468-52d20100-2e1b-11e9-8475-8810c612ae60.png)

**Comment by craxal** [comment]
@v-xianya Azure Storage Explorer isn't the only emulator. What about Azurite?

**Comment by v-xianya** [comment]
Hi @craxal ,We installed Azurite from CMD directly. But I have no idea how to change these values of  default ports. Could you help to share us a guidance?
![image](https://user-images.githubusercontent.com/41351993/52605816-472e1b00-2eab-11e9-8e20-69ef0c47e4f6.png)

**Comment by craxal** [comment]
The [Azurite page](https://github.com/Azure/Azurite#current-list-of-command-line-options) explains. You just use the `--blobPort`, `queuePort`, and/or `--tablePort` flags.

**Comment by v-xianya** [comment]
Hi @craxal Thanks for your sharing. 

For Azurite, It is same with Azure Storage Emulator after changing the default ports. 
![image](https://user-images.githubusercontent.com/41351993/52681062-917bce80-2f75-11e9-8010-71983e01ddd4.png)

The values of default ports still show 10000,10001,10002 on 'Attach to Local Emulator' dialog.
![image](https://user-images.githubusercontent.com/41351993/52681251-21ba1380-2f76-11e9-910f-0d837371a82b.png)

**Comment by craxal** [comment]
Detecting the configured ports requires some foreknowledge about the emulator(s) being used. For Azure Storage Emulator, what if the user installed the emulator somewhere other than the default? We have no way of knowing. Also, what if they're not using Azure Storage Emulator? Again, we have no way of knowing. Azurite doesn't even use a config file, from what I can see; the ports are declared at startup on the command line.

The current ports we enter by default are the known defaults for both of these emulators. I don't see much value in trying to find differently configured ports automatically.
