### ISSUE TITLE
Change 'Experimental Features' to 'Experimental' on 1.7.0 Release Notes

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1128]
**Storage Explorer Version**: 1.7.0/20190208.3
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Commit**: d247f51b
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Open 1.7.0 Release Notes.
2. Check the descriptions under New tab.

#### Expected Experience: ####
There shows '**Experimental**' or **'Experimental' features**.

#### Actual Experience: ####
Show 'Experimental Features' on Release Notes.
![image](https://user-images.githubusercontent.com/34729022/52554175-ef4ad200-2e20-11e9-85f0-2e75acc5410c.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
