### ISSUE TITLE
localhost:8081 loading error ennregust

### ISSUE THREAD

**Issue by bahr2** [Microsoft/AzureStorageExplorer#1129]
**Storage Explorer Version**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**: 

**Bug description**

**Steps to Reproduce**

1.
2.

**Expected Experience**

**Actual Experience**

**Additional Context**

**Comment by craxal** [comment]
@bahr2 Please give us some context by filling in the details as outlined by the bug template.

**Comment by craxal** [comment]
Closing due to staleness and lack of info. If issue persists, please respond, and we can reopen.
