### ISSUE TITLE
Grammar error in error message connecting to database

### ISSUE THREAD

**Issue by chrdavis** [microsoft/AzureStorageExplorer#1130]
![image](https://user-images.githubusercontent.com/6734176/52616171-75304280-2e4c-11e9-83d2-2a7d92d28ec2.png)

"The account may in create or delete process."

Should be 

"The account may be in a create or delete process."

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
