### ISSUE TITLE
The two icons are inconsistent between the tree view and the opened tab of adls gen1 accounts

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1131]
**Storage Explorer Version**: 1.7.0/20190211.2
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Commit**: 0d18c6d0
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Expand 'Data Lake Storage Gen1(Preview)' node -> Open one file system.
2. Check the two icons between the node and the opened tab 

#### Expected Experience: ####
There shows a consistent icons.

#### Actual Experience: ####
There shows an inconsistent icons.
![image](https://user-images.githubusercontent.com/34729022/52619716-72316280-2edd-11e9-8695-b89a965a91f6.png)

**Comment by JasonYeMSFT** [comment]
We are now using consistent icon at both places.

**Comment by v-xianya** [comment]
Verified this issue on the rel build main 20220728.1 Fixed.
![image](https://user-images.githubusercontent.com/41351993/181437003-3ba9b631-b6ca-428d-99c0-b0cf11cb7d68.png)
