### ISSUE TITLE
The renamed file misses a dot when renaming it end with .

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1133]
**Storage Explorer Version**: 1.7.0/20190211.2
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Commit**: 0d18c6d0
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Expand any one account -> Open one blob container which contains one blob at least
2. Rename one blob end with .(Like **text.txt** -> **text1.txt.**)
3. Check the result after renaming successfully

#### Expected Experience: ####
The renamed file shows as **text1.txt.**

#### Actual Experience: ####
The renamed file shows as **text1.txt**(There misses a dot/.)
![image](https://user-images.githubusercontent.com/34729022/52620450-92622100-2edf-11e9-9c36-42e9fdafe518.png)

**Comment by craxal** [comment]
Doesn't look like Storage Explorer is doing anything wrong. Possibly a bug in the client library or platform?

**Comment by craxal** [comment]
Looks to me like this might be platform behavior. I did the following from a Mac:

1. Upload a file named "01.txt" and "02.txt." Notice that "02.txt." gets uploaded as "02.txt" without the trailing ".".
2. Rename "01.txt" to "02.txt."

The operation fails, saying that "02.txt." already exists. If you check the error message, it even shows the request URL has the expected "." in the path. The error message is good news in that no inadvertent dataloss is occurring (meaning the renamed file isn't overwriting an existing one).
