### ISSUE TITLE
Show an error in web page when selecting 'Open in Portal' for Germany accounts

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#1134]
**Storage Explorer Version:** 1.7.0/[20190211.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2404095&view=results)
**Platform/OS Version:** Windows x64\Linux\MacOS
**Architecture:** ia32
**Commit:** 0d18c6d0
**Regression From:** Not a regression

**Steps to Reproduce:**
1. Sign in with one Germany account -> Right click one storage account then select 'Open in Portal'.
2. Check the web page.

**Expected Experience:**

Succeed to open the account in portal.

**Actual Experience:**

Show an error in web page.
![image](https://user-images.githubusercontent.com/41351993/52620196-d274d400-2ede-11e9-995c-ee5c2bcc1cf8.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
