### ISSUE TITLE
AzCopy - Uploud VHD files 

### ISSUE THREAD

**Issue by Aseronly1** [Microsoft/AzureStorageExplorer#1137]
**Storage Explorer Version**: _In which Storage Explorer version was the bug encountered?_
**Platform/OS**: _Linux Ubuntu? macOS High Sierra? Windows 10?_
**Architecture**: _i86? x64?_
**Regression From**: _Was this working in a previous version? If so, which one?_

**Bug description**
After uploading VHD file large one, it's saved on Storageaccount v2 as Block Blob not Page blob?

**Steps to Reproduce**
1. _List the minimal steps required to reproduce the bug._
2. _Be as clear and concise as you can._

**Expected Experience**
_A clear and concise description of what you expected to happen. If applicable, add screenshots to help explain what you expected._

**Actual Experience**
_A clear and concise description of what actually happens. If applicable, add screenshots to help explain what actually happened._

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by craxal** [comment]
When using AzCopy, you need to manually specify that you want to upload the VHD as a page blob. The reason for this is AzCopy handles most of the work for upload, and we have no way of telling it to upload certain files as page blobs.

![image](https://user-images.githubusercontent.com/3473026/52879810-01748b00-3115-11e9-9620-991e3aea7a0d.png)

**Comment by Aseronly1** [comment]
Hi Craig,

No when I enable Azcopy feature I don’t have this option !?

[cid:image001.png@01D4C621.2E408DF0]


Regards
Aser Aladdin

**Comment by MRayermannMSFT** [comment]
Hey @Aseronly1, this has been fixed for our next release. If you download 1.7.0 Preview (Help -> Opt in to Insider Builds, and then Help -> Check for Updates). Or, you can wait till we release 1.7.0 (soon).

**Comment by craxal** [comment]
Fixed in final v1.7.0. Closing for now. Will reopen if we get more user issues. Note that this may still be an issue for drag and drop.
