### ISSUE TITLE
The location of the Cancel button in the 'Edit Entity' and 'Add Entity' dialogs isn't in the Windows standard location

### ISSUE THREAD

**Issue by MikeHus** [Microsoft/AzureStorageExplorer#1138]
**Storage Explorer Version**: 1.6.2
**Platform/OS**: Windows 10
**Architecture**: ia32
**Regression From**: 

**Bug description**
The Cancel button is in the Mac OS standard location, but when using it on a Windows machine, it is easy to accidentally commit data when the intent was to cancel.

**Steps to Reproduce**
1. Open a **Table Storage** query tab.
2. Click **Add** from the menu bar or select a row and click **Edit**

**Expected Experience**
The Cancel button appears as the right-most icon. Using the Proxy dialog as an example.

![azure storage explorer expected cancel button location](https://user-images.githubusercontent.com/43753255/52882654-03971380-312e-11e9-8699-6d2ee4c5346d.png)

**Actual Experience**
The Cancel button is the left-most icon.

![azure storage explorer cancel button](https://user-images.githubusercontent.com/43753255/52882590-ce8ac100-312d-11e9-95da-0b07e9a6c3f2.png)

**Comment by craxal** [comment]
@MikeHus Good catch! Thanks! 😄
