### ISSUE TITLE
No access tier column when opening a blob in a new tab

### ISSUE THREAD

**Issue by MRayermannMSFT** [Microsoft/AzureStorageExplorer#114]
**Storage Explorer Version**: 1.1.0 RC
**Platform**: Linux
**Architecture**: x64
**Build Number**: 2018501.1
**Commit**: 754b96f7
**Regression From**: N/A

#### Steps to Reproduce: ####

1. Open a blob container which has files with access tiers
2. Open the blob container again via "Open in new tab"

#### Expected Experience: ####
The new editor has an access tier column

#### Actual Experience: ####
There is no access tier column

![accesstier](https://user-images.githubusercontent.com/21112697/39492856-c8e8c836-4d45-11e8-9c08-416a4f1b5529.gif)

**Comment by JakeRadMSFT** [comment]
Out for PR for 1.1.0
