### ISSUE TITLE
The part of 'Edit' icon is covered by the scroll bar on 'Manage Access' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1140]
**Storage Explorer Version**: 1.7.0/20190215.9
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Commit**: bfb69abc
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Expand one ADLS Gen2 account -> 'Blob Containers' node.
2. Right click one blob container then select 'Manage Access...'.
3. Add one user or group to make the scroll bar shows on the right side -> Save.
4. Reopen the same dialog -> Check the 'Edit' icon next to the default user and group.

#### Expected Experience: ####
The 'Edit' icon shows well when there is the scroll bar.
#### Actual Experience: ####
The part of 'Edit' icon is covered by the scroll bar.
![image](https://user-images.githubusercontent.com/34729022/52930401-21ff3980-32fd-11e9-85d2-a4fd1dc6b95c.png)

**Comment by MRayermannMSFT** [comment]
Change overflow-y to be scroll instead of auto. Always visible gutter is something we have to live with to prevent this.

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
