### ISSUE TITLE
Show a confused code next to the 'Permission for...' on 'Manage Access' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1141]
**Storage Explorer Version**: 1.7.0/20190215.9
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Commit**: bfb69abc
**Regression From**: Previous release 1.7.0
#### Steps to Reproduce: ####
1. Expand one ADLS Gen2 account -> 'Blob Containers' node.
2. Right click one blob container then select 'Manage Access...'.
3. The default user $superuser(Owner) is focused -> Check the description next to the 'Permission for...'.

#### Expected Experience: ####
It shows 'Permission for: $superuser(Owner)'.
#### Actual Experience: ####
It shows a confused code.
![image](https://user-images.githubusercontent.com/34729022/52931081-dc903b80-32ff-11e9-920d-1eb050264ec5.png)
#### More info: ####
This issue doesn't reproduce after changing the focused user.

**Comment by MRayermannMSFT** [comment]
Fix merged
