### ISSUE TITLE
Unable to sign in on Linux

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#1142]
**Storage Explorer Version**: 1.7.0/20190218.1
**Platform/OS Version**: Linux Ubuntu 16.04
**Architecture**: x64
**Commit**: bfb69adc
**Regression From**: Not a regression

**Repro Steps:**
1. Enable "Use Device Code Flow Sign-in" under Experimental(**Use a new machine**).
2. Open "Connect to Azure Storage" dialog -> Sign in... -> Paste the copied code to the opened browser.
3. Click "Continue" then enter your account and password.
4. Check the result in Storage Explorer after signing in successfully.

**Expect:**
1. The "Connect" dialog disappears automatically.
2. All the subscriptions display well with checked.

**Actual:**
1. The 'Connect' dialog still shows.
2. No subscription displays.

**More Info:**
This issue also reproduces for using non device code flow to sign in.

**Comment by maetthu** [comment]
Can confirm for 1.7.0/20190208.2 (20190218.1 isn't available for me, newest insider build shown is 20190208.2) on Arch Linux as well. Neither standard nor device code flow close the connect window and no account is added.

**Comment by craxal** [comment]
@maetthu We recently released the full v1.7.0. Can you update and try again?

**Comment by maetthu** [comment]
@craxal Still the same with 1.7.0/20190305.10 unfortunately. Neither of the two login methods work.

**Comment by MRayermannMSFT** [comment]
Hi @maetthu , we recently discovered that .NET Core 2.1 shipped a breaking change that broke our auth library. So if you're on .NET Core 2.1 or 2.2, this is why sign in isn't working for you. To workaround the issue you can either downgarde to .NET Core 2.0 or perform the following steps:

1. Download version 1.5.43 of StreamJsonRpc [from nuget](https://www.nuget.org/packages/StreamJsonRpc/1.5.43). Look for the "Download package" link on the right hand side of the page.
2. After downloading the package, change its file extension from `.nupkg` to `.zip`
3. Unzip the package
4. Go to `streamjsonrpc.1.5.43/lib/netstandard1.1/`
5. Copy `StreamJsonRpc.dll` to the following locations inside the Storage Explorer folder:
    1. `StorageExplorer/resources/app/ServiceHub/Services/Microsoft.Developer.IdentityService/`
    2. `StorageExplorer/resources/app/ServiceHub/Hosts/ServiceHub.Host.Core.CLR.x64/`

If you do that, you shouldn't need to downgrade your .NET Core version. We'll be updating out Linux docs later today with updated Linux install instructions, so if none of the above works for you, you can check those out in about 8 hours or so (I'll try to come back and drop a link once the docs are updated).

**Comment by maetthu** [comment]
@MRayermannMSFT This (copying the dll) does indeed mitigate the issue and I can login again, thx.

**Comment by AArnott** [comment]
FYI this was due to https://github.com/Microsoft/vs-streamjsonrpc/issues/116.

**Comment by rnsc** [comment]
@MRayermannMSFT Thank you for the quick fix, however, it's very impractical if we have to do that every time there's an upgrade. Can you tell use when this will actually be fixed once and for all? (people have been unable to use StorageExplorer app on Linux for months now)

**Comment by jinglouMSFT** [comment]
This will be fixed in our next release.

**Comment by MRayermannMSFT** [comment]
We've received new bits from our auth library that make the patch no longer needed. The bits will be included in 1.8.0.

**Comment by kj299** [comment]
this was not fixed in the next release. i cannot find streamjsonrpc.1.5.43/lib/netstandard1.1/ online either

**Comment by craxal** [comment]
@kj299 If you're having problems, could you open a new issue and fill in the bug template? It's been quite a while since this issue was opened, and there have been significant changes to Storage Explorer since then. Having a fresh bug opened with up-to-date info will be most helpful.

**Comment by kj299** [comment]
@craxal  thank you for your response sir. i failed to provide an update or cancel my message.

since then, i opened up an issue at

https://github.com/Azure/azure-storage-fuse/issues/378
