### ISSUE TITLE
Succeed to download a file which name only containing blank space with AzCopy enabled

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/AzureStorageExplorer#1144]
**Storage Explorer Version**: 1.7.0/20190215.9
**Platform/OS Version**: Windows 10
**Architecture**: x64
**Commit**: bfb69abc
**Regression From**: Not a regression

**Steps to Reproduce**
1. Enable 'Use AzCopy for Improved Blob Upload and Download'.
2. Upload a file in blob container --> Rename it with blank space.
3. Download the file.

**Expect Experience**
Prompt to type the file name when downloading and fail to download the file which name only containing blank space.
![image](https://user-images.githubusercontent.com/34729092/52985766-16b61780-33aa-11e9-8392-e6b43c9783de.png)

**Actual Experience**
Succeed to download this file.
![image](https://user-images.githubusercontent.com/34729092/52985720-f2f2d180-33a9-11e9-84cd-d97492545627.png)

**Additional Context**
Display with '++' as the default file name.
![image](https://user-images.githubusercontent.com/34729092/52985773-1ae23500-33aa-11e9-975c-ee021d36bff5.png)

**Comment by MRayermannMSFT** [comment]
Won't fix for now. If customers report issues with how AzCopy makes names Windows safe we'll look into this more.

**Comment by v-dantch** [comment]
Got it. Thanks for your reply.
