### ISSUE TITLE
More Verbose Error Messages

### ISSUE THREAD

**Issue by Brinsby** [microsoft/AzureStorageExplorer#1146]
**Storage Explorer Version**: 1.6.2
**Platform/OS**: Win 7
**Architecture**: x64
**Regression From**: Unsure but it was working before so it is an issue with my machine rather than the program itself

**Bug description**
Connection to azure subscription fails and gives no useful info as to why.

**Steps to Reproduce**
1. Log into Azure Account
2. Try to load azure resources and have it fail due to a firewall or proxy.

**Expected Experience**
Clear concise error message telling me everything that went wrong.

**Actual Experience**
I expected a better error message aside from ECONNRESET.

**Additional Context**
In my enterprise environment we have a number of custom network configurations (firewalls, proxies, etc) that potentially block an application like this. With no information as to why other than ECONNRESET, I have to go through a large list of possibilities to figure out the issue. Any additional context that could be added would be appreciated.

**Comment by MRayermannMSFT** [comment]
Looked into this. Those types of error messages come directly from node. There's not much else we can do to make them more verbose.
