### ISSUE TITLE
Ability to modify AzCopy parameters

### ISSUE THREAD

**Issue by OwainEsau** [microsoft/AzureStorageExplorer#1147]
**Is your feature request related to a problem? Please describe.**
We had a botched upload and had to redo it, i wanted to be able to upload and overwrite using AzCopy inside Azure Storage explorer but couldn't.

**Describe the solution you'd like**
Ability to specify the parameters on an AzCopy upload.

**Comment by JasonYeMSFT** [comment]
We are currently working on these AzCopy parameters:
- [ ] Caps transfer rate
- [ ] Concurrent connections
- [ ] Concurrent files
- [ ] Default conflict resolution
- [ ] Maximum buffer size
- [ ] Auto detect vhd files as page blobs

**Comment by MRayermannMSFT** [comment]
All of these options have been merged. They will be available in the next release (1.11.0).
