### ISSUE TITLE
Cosmos DB mongo Connection Strings include extra "https" URL scheme

### ISSUE THREAD

**Issue by ilkka** [Microsoft/AzureStorageExplorer#1148]
**Storage Explorer Version**: 1.6.2 build number 20190108.2
**Platform/OS**: Windows 10
**Architecture**: About dialog reports ia32, machine is x64

**Bug description**
When viewing the Properties for a Cosmos DB Account that uses the MongoDB API, the connection strings start with "mongodb://" but include an extra "https://" after the "@" that separates the username and password from the hostname. That is, whereas the connection string should be

`mongodb://cosmosdb-username:cosmosdb-password@cosmosdb-host:12345/?query=string`

it is in fact

`mongodb://cosmosdb-username:cosmosdb-password@https://cosmosdb-host:12345/?query=string`

**Steps to Reproduce**
1. Connect to a subscription that has a CosmosDB account set up with the MongoDB API
2. Look at the Primary Connection String

**Expected Experience**
An URL that can be used to connect to the MongoDB API

**Actual Experience**
An URL that does not parse.

**Comment by MRayermannMSFT** [comment]
@ziyel , was this fixed in the PR you just merged?

**Comment by ziyel** [comment]
Yes. It is fixed.

**Comment by MRayermannMSFT** [comment]
Ok, closing then for tracking purposes.
