### ISSUE TITLE
Nothing happens when trying to open 'Connect' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1149]
**Storage Explorer Version**: 1.7.0/20190221.1
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Commit**: a1fecf3f
**Regression From**: Previous release 1.7.0

#### Steps to Reproduce: ####
1. Click 'Add Account' to open 'Connect' dialog.

#### Expected Experience: ####
The 'Connect' dialog opens successfully.

#### Actual Experience: ####
Nothing happens after clicking the 'Add Account' button.

#### More info: ####
Based on the step1, nothing happens after executing the below actions.
_**Storage Account:**_
1. Rename…
2. Get Shared Access Signature… 
3. Set Default Access Tier…

_**Blob Container:**_ 
1. Get Shared Access Signature… 
2. Manage Access Policies…
3. Set Public Access Level…
4. Configure CORS Settings…
5. Configure Soft Delete Policies…
6. Upload…
7. New Folder
8. Rename…
9. Delete
10. Get Shared Access Signature… 
11. Properties…

_**File Shares:**_

1. Configure CORS Settings…
2. Rename…
3. Get Shared Access Signature… 
4. Manage Access Policies…
5. Upload…
6. New Folder
7. Rename…
8. Connect VM
9. Properties…

_**Queues:**_

1. Configure CORS Settings…
2. Get Shared Access Signature… 
3. Manage Access Policies…
4. Add Message

_**Tables**:_

1. Configure CORS Settings…
2. Get Shared Access Signature… 
3. Rename…
4. Manage Access Policies…
5.  Add Entity
6. Edit Entity
7. Column Options

**Comment by craxal** [comment]
Resource files weren't copied to the package. That's likely the root cause of all this, though I'm not sure why it would interfere with dialogs we haven't fixed up yet...
