### ISSUE TITLE
Rename is enabled for archived blobs

### ISSUE THREAD

**Issue by MRayermannMSFT** [Microsoft/AzureStorageExplorer#115]
**Storage Explorer Version**: 1.1.0 RC
**Platform**: Linux
**Architecture**: x64
**Build Number**: 2018501.1
**Commit**: 754b96f7
**Regression From**: N/A

#### Steps to Reproduce: ####
1. Have a blob with access tier "Archive"

#### Expected Experience: ####
Renaming an archived blob is not possible, so I would expect rename to not be enabled

#### Actual Experience: ####
Rename is enabled, and it immediately fails with an error

**Comment by JakeRadMSFT** [comment]
Out for PR for 1.1.0
