### ISSUE TITLE
The 'Delete' icon is invisible and shows an odd layout after adding one user with long user name on 'Manage Access' dialog with non-Dark theme

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1150]
**Storage Explorer Version**: 1.7.0/20190221.1
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Commit**: a1fecf3f
**Regression From**: Not a regression
#### Steps to Reproduce: ####
1. Make sure the current theme is not Dark -> Expand one ADLS Gen2 account -> 'Blob Containers'.
2. Right click one blob container then select 'Manage Access...'.
3. Add a user with long user name -> Check the added user on the shown list.
#### Expected Experience: ####
1. The shown name of the added user is focused well.
2. 'Delete' icon is visible.
#### Actual Experience: ####
1. The shown name of the added user shows an odd layout.
2. 'Delete' icon is invisible.
![image](https://user-images.githubusercontent.com/34729022/53153646-a657f380-356d-11e9-8ae5-29936b0c2295.png)

**Comment by MRayermannMSFT** [comment]
We should now be handling long names much better:
![image](https://user-images.githubusercontent.com/21112697/53357362-967c3e80-38e2-11e9-8cae-68852c1e1b5e.png)

This has been checked into master.
