### ISSUE TITLE
Show a confused message when trying to change the default group on 'Manage Access' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1151]
**Storage Explorer Version**: 1.7.0/20190221.1
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Commit**: a1fecf3f
**Regression From**: Not a regression
#### Steps to Reproduce: ####
1. Expand one ADLS Gen2 account -> 'Blob Containers'.
2. Right click one blob container then select 'Manage Access...'.
3. Click 'Edit' icon next to the default group $superuser(Owning Group) -> Clear the group name then check the messages.

#### Expected Experience: ####
1. The placeholder shows '**Enter an Object ID**'.
2. The error message shows '**No Object ID specified.**'

#### Actual Experience: ####
1. The placeholder shows '**Enter a **UPN** or Object ID**'.
2. The error message shows '**No UPN  or Object ID specified.**'
![image](https://user-images.githubusercontent.com/34729022/53154759-50d11600-3570-11e9-938c-9c3f73f07d46.png)

**Notes**: The UPN is just for users not groups.

**Comment by MRayermannMSFT** [comment]
Hey @v-xuanzh , I also thought this would be the case! But I double checked with the platform team, and the owner/owning group can be either a user or a group, which means we need to allow the user to enter either a UPN or an OID. Definitely confusing, but that's the intended design apparently.
