### ISSUE TITLE
Use custom dns when copying url links for blobs

### ISSUE THREAD

**Issue by laurencee** [microsoft/AzureStorageExplorer#1153]
**Describe the solution you'd like**
After setting up a custom dns on a storage account all url copy's should make use of that DNS

Example:
1. Open storage explorer
2. Navigate to blob container
3. Select a blob and click copy url

**Expected**
The copied URL link would make use of the custom dns I bound to the storage account

**Actual**
The copied url is just using the default azure provided url.

**Comment by craxal** [comment]
Strange. Storage Explorer should be using the custom endpoint. If you click on the storage account node and look under properties, what endpoints do you see listed? Do they reflect your custom endpoint?

**Comment by laurencee** [comment]
@craxal The properties window shows only the azure endpoints. 

The custom hostname is working/bound and visible on the azure portal. We are using the custom domain to link to all our files and it works as expected.

**Comment by laurencee** [comment]
If the properties are meant to use the custom domain instead of the azure domain then it sounds like the bug is on the azure resource side itself. Do you know if all the endpoints are meant to be shown with the custom domain if one is provided?

**Comment by craxal** [comment]
Just to be clear, you are seeing something like this:

Properties | -
---|---
Blob Endpoint | https://account.blob.core.windows.net/
File Endpoint | https://account.file.core.windows.net/

But you expect to see something like...this?

Properties | -
---|---
Blob Endpoint | https://customblobdns.net/
File Endpoint | https://customfiledns.net/

One way we might be able to verify if Storage Explorer is doing it right:
1. Launch Storage Explorer and navigate to your subscription.
2. Hit F12, click the Sources tab, and open "AzureStorageAccountAttributeLoader.js"
3. Drop a breakpoint around line 108:
   ```js
   attributes = AzureStorageUtilities.getStorageAccountV2Attributes(resource, args.subscription, args.id, [args.primaryKey, args.secondaryKey]);
   return [2 /*return*/, { results: attributes }];
   ```
4. Expand the subscription node (you may have to refresh first). The breakpoint should be hit. Depending on how many storage accounts you're listing, you may have to continue execution a few times until the account you're looking for comes up.
5. When paused, exampine the `resource`, `args.subscription`, and `attributes` variables. Look for something like "endpoints". Do you see your custom DNS anywhere?

**Comment by laurencee** [comment]
In regards to your first question about what i expect to see, I don't know what I should expect to see as I've never looked at the properties before. I was just going off what you said here:

> Storage Explorer should be using the custom endpoint. If you click on the storage account node and look under properties, what endpoints do you see listed? Do they reflect your custom endpoint?

I'll hopefully be able to get around testing out the js debugging later this weekend.

**Comment by laurencee** [comment]
@craxal I put a breakpoint in the area you suggested, the `resources` object contains the custom domain entry: `resources.properties.customDomain`.

**Comment by craxal** [comment]
@laurencee Sorry about the delay. I did some investigations, and I believe I was mistaken about Storage Explorer using custom domains. Storage Explorer really just goes off what Azure gives it. While a `customDomain` property is clearly visible when debugging the code, it's obvious Azure doesn't "replace" the primary endpoints with it, and Storage Explorer doesn't do anything with it.

The problem here is I don't think using the custom endpoint for blob URLs is obvious behavior. We can probably include some option in our planned settings/configurations feature.

**Comment by laurencee** [comment]
@craxal Thank you for the reply,
I sort of agree, on the one hand it's not the same behavior as the portal but on the other hand a user isn't going to set a custom domain and not want to use it in the default instance.

You could have a setting to toggle how this functions or you could have a drop down button that has the other option if a custom domain is detected so that way both options are always available without having to go into any settings menu.

**Comment by craxal** [comment]
@laurencee I agree. These are good suggestions. We'll keep this on our backlog and see what we could do.

**Comment by trendyequine** [comment]
I've been waiting for this feature for ages too. For me though, my requirements are a little different since I front my blob storage with a non-Microsoft CDN. I'd like to be able to set a custom domain parameter (for example, cdnstorage.com) so that every URL I copy to the clipboard uses this domain instead of the mystorage.blob.core.windows.net domain.

**Comment by jasongaylord** [comment]
Searching for Copy URL, this didn't come up. Thanks for merging.

**Comment by craxal** [comment]
@jasongaylord No problem. I reworded the original bug to make it easier to find.
