### ISSUE TITLE
Break lease error message displays wrong number of spaces for blob name starting with multiple spaces

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1155]
**Storage Explorer Version**: 1.7.0/20190221.2
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Commit**: 81c1ae6b
**Regression From**: Not a regression
#### Steps to Reproduce: ####

1. Expand one non adls gen2 account -> 'Blob Containers'. 
2. Open one blob container which contains one blob at least.
3. Rename one blob starting with multiple spaces -> Acquire lease for the renamed blob.
4. Right click the leased blob then select 'Break Lease' -> Enter an invalid name -> Check the error message.

#### Expected Experience: ####
The error message shows a matched numbers of spaces for the blob.
#### Actual Experience: ####
The error message shows one space if you inputted an invalid name for the blob. So we have no way to break the lease according to the error message.

The renamed blob:
![image](https://user-images.githubusercontent.com/34729022/53223634-dc0ce300-3626-11e9-977f-a285e4ccbb89.png)

![image](https://user-images.githubusercontent.com/34729022/53223249-9e5b8a80-3625-11e9-8de2-0e7931a04a12.png)

**Comment by cg6** [comment]
I have an issue with Break Lease which seems close enough to be worth combining.
The Break Lease dialog appears to be using a regex match on the filenames.
Version 1.6.2 on Windows.

Blob Name: PRODSGSQC11_[CATSTEST]_FULL_20170427-11.42.20.bak
Break Lease Dialogue does not accept: PRODSGSQC11_[CATSTEST]_FULL_20170427-11.42.20.bak
However it does accept either of these:
PRODSGSQC11_C_FULL_20170427-11.42.20.bak
PRODSGSQC11_E_FULL_20170427-11A42B20Cbak

**Comment by MRayermannMSFT** [comment]
@cg6 , this issue is for the one you're facing: https://github.com/Microsoft/AzureStorageExplorer/issues/1070

**Comment by MRayermannMSFT** [comment]
Fix for this bug merged into master for this. @cg6 , yes, that bug does/did exist. It'll be fixed in 1.7.0 (which ships soon-ish). If you need it now, the fix was also shipped in 1.7.0 preview which you can install by going to Help -> Opt in to Insider builds. Sorry for the inconvenience.
