### ISSUE TITLE
'undefined' instead of 'SAS' and 'Permissions' on 'Connection Summary' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1156]
**Storage Explorer Version**: 1.7.0/20190221.2
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Commit**: 81c1ae6b
**Regression From**: Previous release 1.7.0
#### Steps to Reproduce: ####
1. Get SAS connection string for one storage account.
**Display name:** accxuangpv2test
**SAS**: SharedAccessSignature=sv=2018-03-28&ss=bfqt&srt=sco&sp=rl&st=2019-02-22T06%3A16%3A05Z&se=2019-02-23T06%3A16%3A05Z&sig=yC81rug%2F6KKL1pZtNUu8ELPN8lv4IGiUNL8tcvqMPFk%3D;BlobEndpoint=https://accxuangpv2test.blob.core.windows.net/;FileEndpoint=https://accxuangpv2test.file.core.windows.net/;QueueEndpoint=https://accxuangpv2test.queue.core.windows.net/;TableEndpoint=https://accxuangpv2test.table.core.windows.net/;
2. Open Connect dialog ->Paste the copied connection string -> Next.
3. Check the strings on 'Connection Summary' dialog.
#### Expected Experience: ####
The strings show well on 'Connection Summary' dialog.
#### Actual Experience: ####
'undefined' instead of 'SAS' and 'Permissions' on 'Connection Summary' dialog.
![image](https://user-images.githubusercontent.com/34729022/53224434-8b4ab980-3629-11e9-8f04-a1ffd66aea33.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
