### ISSUE TITLE
The item 'Use Custom Environment' shows an extra single quotes under the drop-down list of Azure environment on Connect dialog

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1157]
**Storage Explorer Version**: 1.7.0/20190221.2
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Commit**: 81c1ae6b
**Regression From**: Previous release 1.7.0
#### Steps to Reproduce: ####
1. Open Connect dialog -> Select 'Add New Environment' under the drop-down list of Azure environment. 
2.  Enter an invalid Environment name and ARM endpoint -> Sign in.
3. Reopen the Connect dialog -> Check the the drop-down list of Azure environment. 

#### Expected Experience: ####
There shows **Use Custom Environment**
#### Actual Experience: ####
There shows **Use 'Custom Environment'**.
![image](https://user-images.githubusercontent.com/34729022/53225116-cfd75480-362b-11e9-854b-f10e9af864b2.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
