### ISSUE TITLE
Tabbing to the first 'Remove' button then Pressing 'Enter' focuses on 'Add' button on 'Manage Access' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1158]
**Storage Explorer Version**: 1.7.0/20190221.2
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Commit**: 81c1ae6b
**Regression From**: Not a regression
#### Steps to Reproduce: ####

1. Expand one non adls gen2 account -> 'Blob Containers'.
2. Right click one blob container then select 'Manage Access Policies...'.
3. Add two access policies for the blob container.
4. Tab to the first 'Remove' button then press 'Enter'.
5. Check the next focus.

#### Expected Experience: ####
It will focus the second 'Remove' button.
#### Actual Experience: ####
It focuses on the 'Add' button.
![image](https://user-images.githubusercontent.com/34729022/53226833-3b6ff080-3631-11e9-9277-64e9575d828b.png)

**Comment by craxal** [comment]
Good observation! As long as focus isn't lost, we don't need to worry about where focus goes, so we won't worry about fixing this.
