### ISSUE TITLE
VS Cloud Explorer prevents loading subscriptions in Storage Explorer

### ISSUE THREAD

**Issue by beneuto** [microsoft/AzureStorageExplorer#1159]
**Storage Explorer Version**: _1.6.2_
**Platform/OS**: _Windows 10_
**Architecture**: _x64_
**Regression From**: _Before installation of Visual Studio_

**Bug description**
After installation of Visual Studio Community 2017 with Cloud Explorer extension, Storage Explorer can no longer load subscriptions.   Reentering credentials has no effect.   Removing and re-adding account has no effect.
Cloud Explorer in VS works fine.  

We are using Azure Active Directory with accounts replicated from onsite AD.

May be related to issue #629 however accounts are not removed, just broken.

**Comment by MRayermannMSFT** [comment]
Hey @beneuto , what exactly do you mean by can no longer load subscriptions? Is there are error message? Does it say no subscriptions found? Are you stuck in a reauthentication loop?

**Comment by beneuto** [comment]
In Storage Explorer, Account Management under my account name it says "Subscriptions could not be loaded....." and the option to "Reenter credentials".   After the authentication process there is no change.   Under "More information", I see the following error:

Error: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect"....

**Comment by beneuto** [comment]
I've just realised that the same behaviour occurs inside Visual Studio if I try to manage accounts via the Cloud Explorer window. It is only when I sign into Visual Studio itself (via Windows Authentication) that it works.

**Comment by MRayermannMSFT** [comment]
@beneuto, are you behind a proxy?

**Comment by beneuto** [comment]
Ah, yes I am.   That seems to be the issue so I will close this.
