### ISSUE TITLE
Update the message 'Experimental feature …' to 'Preview feature…' on Activities Window

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1161]
**Storage Explorer Version**: 1.7.0/20190226.5
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Commit**: b9da01ca
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Launch Storage Explorer then Navigate to 'Preview' menu.
2. Check anyone item like 'Use Device Code Flow Sign in' then verify the log message.

#### Expected Experience: ####
There shows '**Preview** feature 'Use Device Code Flow Sign in' is enabled.
#### Actual Experience: ####
There shows '**Experimental** feature 'Use Device Code Flow Sign in' is enabled.
![image](https://user-images.githubusercontent.com/34729022/53398472-86a24000-395e-11e9-9845-e297660974c1.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
