### ISSUE TITLE
The item 'Use AzCopy for Improved Blob Upload and Download' isn't checked after enabling the preview AzCopy feature on notification bar

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1162]
**Storage Explorer Version**: 1.7.0/20190226.5
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Commit**: b9da01ca
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Launch Storage Explorer -> Make sure the AzCopy feature is disabled.
2. Go to dev tools(F12) -> Application -> Local Storage (left hand side) -> file:// -> look for Standalone_VersionOnLastRun_v1, and double click the value and change it to “1.6.2” .
3. Restart Storage Explorer -> Open a blob container(There pops a notification bar) -> Click 'Enable'. 

#### Expected Experience: ####
1. There shows a message indicates the AzCopy is enabled.
2. The item 'Use AzCopy for Improved Blob Upload and Download' under 'Preview' menu is checked.
#### Actual Experience: ####
1. There shows a message indicates the AzCopy is enabled.
2. The item 'Use AzCopy for Improved Blob Upload and Download' under 'Preview' menu isn't checked.
![image](https://user-images.githubusercontent.com/34729022/53399060-04b31680-3960-11e9-9490-26668df21520.png)
![image](https://user-images.githubusercontent.com/34729022/53399064-0977ca80-3960-11e9-9fc5-1a7aff521c97.png)

#### More info: ####
The log message shows the AzCopy is disabled after checking the item 'Use AzCopy for Improved Blob Upload and Download' manually.
![image](https://user-images.githubusercontent.com/34729022/53399152-3b892c80-3960-11e9-9a38-5b598fba4468.png)
![image](https://user-images.githubusercontent.com/34729022/53399158-3e841d00-3960-11e9-90d0-e5de001c5f79.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into master.

**Comment by v-xuanzh** [comment]
This issue reproduces on the latest master build 20190827.12. So we reopen it.
