### ISSUE TITLE
The speed is always 0.0 Mbps when uploading a large folder using AzCopy

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1163]
**Storage Explorer Version**: 1.7.0/20190226.5
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Commit**: b9da01ca
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Enable AzCopy from 'Preview' feature.
2. Open one blob container then try to upload a folder which contains multiple files.
3. Check the message during uploading.

#### Expected Experience: ####
The speed is not 0.0Mbps.
#### Actual Experience: ####
The speed always is 0.0Mbps until the uploading is complete.
![image](https://user-images.githubusercontent.com/34729022/53400251-4e046580-3962-11e9-880e-fbf959f7075e.png)
#### More info: ####
This issue also reproduces when uploading a large folder not using AzCopy.
![image](https://user-images.githubusercontent.com/34729022/53400370-90c63d80-3962-11e9-8323-aca6ac01c0f4.png)

**Comment by MRayermannMSFT** [comment]
Hi @v-xuanzh , can you try this again with the latest master builds? Try both:

- Uploading the folder while it is trinlab
- Uploading the folder while it is on your machine (so copy and paste the folder from trinlab to your machine)

Thanks!

**Comment by v-xuanzh** [comment]
Hi @MRayermannMSFT ,We tried to verify this issue with the latest master build. 

1. This issue reproduces when uploading it from trinlab.
2. This issue reproduces when uploading it from local file system.
![image](https://user-images.githubusercontent.com/34729022/55053526-b3a74880-5019-11e9-91a6-a20d0c718647.png)

**Comment by v-xianya** [comment]
Verified on build 20190515.1. This issue doesn't reproduce. Could you help to resolve it?
