### ISSUE TITLE
Error when copying one attached blob container with name containing "_"

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1166]
**Storage Explorer Version**: 1.7.0/20190227.3
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Commit**: 1f111467
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Get SAS URI for one normal blob container like below.
   Blob Container: newblob
   SAS URI: [REDACTED]
2. Open 'Connect' dialog -> Paste the copied URI then update the display name containing underlines on 'Attached with SAS URI' dialog (Like '**_newblob_'** => '**_newblob_test1'_**)-> 'Connect'.
3. Expand '**Local & Attached**' -> '**Storage Accounts**' -> (**SAS-Attached Service**) -> '**Blob Container'**.
4. Right click the attached blob container then click 'Copy Blob Container'.

#### Expected Experience: ####
No error occurs.
#### Actual Experience: ####
An error occurs.
![image](https://user-images.githubusercontent.com/34729022/53476518-6c806480-3a27-11e9-82f7-cdb0baf850fc.png)
#### More info: ####
1. Execute other actions like 'Open'/'Detach'/'Add to Quick Access' for the attached blob container without errors. 
2. This issue doesn't reproduce for attached file shares/tables.

**Comment by craxal** [comment]
The problem is copy is trying to use the display name instead of proper container name. Easy fix.
