### ISSUE TITLE
Update the setting key of  'StorageExplorer.ExperimentalFeatures.Settings.v1' to 'StorageExplorer.PreviewFeatures.Settings.v1' on dev tools

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1167]
**Storage Explorer Version**: 1.7.0/20190227.3
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Commit**: 1f111467
**Regression From**: Not a regression
#### Steps to Reproduce: ####
1. Launch Storage Explorer -> Go to dev tools(F12) -> Application -> Local Storage -> file://.
2. Check the settings' key.

#### Suggestion ####
Update the setting key of  'StorageExplorer.**ExperimentalFeatures**.Settings.v1' to 'StorageExplorer.**PreviewFeatures**.Settings.v1'
![image](https://user-images.githubusercontent.com/34729022/53477051-ba499c80-3a28-11e9-827c-bae185e38da3.png)

**Comment by MRayermannMSFT** [comment]
Need to keep the key value the same so we persist the settings. The key is not user visible so I'm not worried about. Won't fix.
