### ISSUE TITLE
The value of DFS Endpoint misses a slash for the attached ADLS Gen2 blob containers

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1168]
**Storage Explorer Version**: 1.7.0/20190227.3
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Commit**: 1f111467
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Attach one adls gen2 account with key and name.
Display name: adlsxuantest
Key:hFRNh+hK0IOlofQi2nvj8eIYbhsqRl7rhuJWDarlzY9egyGoQfYrhvFnYfEpzqd0o8OnFHkmL2Y/zE33GGb3fg==
2.  Expand '**Local & Attached**' -> '**Storage Accounts**' -> '**adlsxuantest(Key, ADLS Gen2)**' -> '**Blob Container'**.
3. Focus on one blob container then check its properties.

#### Expected Experience: ####
The value of DFS Endpoint ends with a slash.

#### Actual Experience: ####
The value of DFS Endpoint misses the slash.
![image](https://user-images.githubusercontent.com/34729022/53478116-f4b43900-3a2a-11e9-8a53-d251df998471.png)

**Comment by MRayermannMSFT** [comment]
Closing as won't fix.
