### ISSUE TITLE
The shortcut of 'Edit' is confused on 'Manage Access' dialog for ADLS Gen2 accounts

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1169]
**Storage Explorer Version**: 1.7.0/20190227.3
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Commit**: 1f111467
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Expand one ADLS Gen2 account -> 'Blob Containers'.
2. Right click one blob container then select 'Manage Access...'.
3. Focus on the default user or group -> Try to edit the owner with short key.

#### Expected Experience: ####
The shortcut of 'Edit' isn't 'Enter'.
#### Actual Experience: ####
We can use the 'Enter' key to edit and confirm inputting when focusing on one owner(The same key has two operations).

In this case, can we use 'Enter' to delete the added users/groups when focusing on it?
Actually, we can only use 'Delete' key to delete the added users/groups.

**Comment by MRayermannMSFT** [comment]
Won't fix for now/I'm not sure what key you would expect to be used for each command. Let me know if you have a concrete suggestion.
