### ISSUE TITLE
Remove Option to Upload Block/Append Blobs to Premium SV2 Accounts

### ISSUE THREAD

**Issue by jcrobins** [microsoft/AzureStorageExplorer#1171]
**Storage Explorer Version**: 1.6.2
**Platform/OS Version**: Windows
**Architecture**: ia32
**Regression From**: N/A

#### Steps to Reproduce:
1. Create a Premium StorageV2 storage account.
2. Select the created storage account in Storage Explorer.
3. Select a container in this account in Storage Explorer and select **Upload** > **Upload Files...** to view the **Microsoft Azure Storage Explorer - Upload Files to Blob Container** dialog.

#### Expected Experience:
**Block Blob** and **Append Blob** should not be a selectable option in the **Blob type** drop-down.

#### Actual Experience:
**Page Blob** should be the only available option in the **Blob type** drop-down.

**Comment by jcrobins** [comment]
Related to https://github.com/Microsoft/AzureStorageExplorer/issues/1170

**Comment by craxal** [comment]
Ran quick verification. Appears to be fixed after resolving #1050.
