### ISSUE TITLE
Breaking the lease with multiple blobs selected shows incorrect blob name on 'Break Lease' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1173]
**Storage Explorer Version**: 1.7.0/20190227.3
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Commit**: 1f111467
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Expand one non adls gen2 account -> 'Blob Containers'.
2. Open one blob container then upload more than 2 blobs.
3. Lease one blob.
4. Select multiple blobs at the same time then select 'Break Lease' -> Check the result.

#### Expected Experience: ####
The message shows '**Type the leased [blob_name] to proceed'** on 'Break Lease' dialog.
#### Actual Experience: ####
The message shows '**Type 'continue' to proceed'** on 'Break Lease' dialog.
![image](https://user-images.githubusercontent.com/34729022/53543380-61850d00-3ad7-11e9-9ef4-ba55286deda5.png)

**Comment by MRayermannMSFT** [comment]
By design. We go with continue during multi select.

**Comment by v-xuanzh** [comment]
Hi @MRayermannMSFT,
I am confused about the keyword '**continue**' during multi select.

1. We can not break the lease after inputting 'contine'
![image](https://user-images.githubusercontent.com/34729022/53612657-2ee71d00-3b88-11e9-9fc2-f03f01df0bf3.png)
2. The lease can be broken after inputting the blob name
![image](https://user-images.githubusercontent.com/34729022/53612692-54742680-3b88-11e9-898c-da8693803fd3.png)

I think the message and behavior is inconsistent. ![image](https://user-images.githubusercontent.com/34729022/53612805-cba9ba80-3b88-11e9-973c-f455710a7b49.png)
