### ISSUE TITLE
The 'Add New Param' button is truncated on 'Execute Storage Procedure' dialog for graph account

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1174]
**Storage Explorer Version**: 1.7.0/20190227.3
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Commit**: 1f111467
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Expand one Graph account -> Database -> Graph.
2. Create a stored procedure then make sure it opens.
3. Click 'Execute' button on the toolbar -> Check the 'Add New Param' button on the opened dialog.

#### Expected Experience: ####
The 'Add New Param' button shows well on 'Execute Storage Procedure' dialog.
#### Actual Experience: ####
The 'Add New Param' button is truncated on 'Execute Storage Procedure' dialog.
![image](https://user-images.githubusercontent.com/34729022/53544537-3a303f00-3adb-11e9-9a90-0d89f3364900.png)

**Comment by MRayermannMSFT** [comment]
@ziyel / @djlan , please triage this.

**Comment by ziyel** [comment]
@v-xuanzh Hi Xuan, have you `Zoom In` the view before open the dialog?

**Comment by v-xuanzh** [comment]
No, This button is truncated with the default size.

**Comment by v-xianya** [comment]
Verified on build 201905015.1. This issue doesn't reproduce. Could you help to resolve it?

**Comment by ziyel** [comment]
The issue has not reproduced. Close the issue.

**Comment by v-xianya** [comment]
Hi, @jinglouMSFT We verified this issue on the build 201905015.1. 

This issue reproduces when using the known CosmosDB account "Azure Tools Manual Testing 1 -> stephwe3", but it doesn't reproduce when using the new created CosmosDB account "Azure Tools Manual Testing 1 -> test0517".
![image](https://user-images.githubusercontent.com/41351993/57992746-6eb70400-7ae8-11e9-8468-aba2fe2e41b2.png)



And we noticed there are some differences between these two CosmosDB accounts. Could you help to take a look at it? Thanks a lot.
![image](https://user-images.githubusercontent.com/41351993/57992435-b8065400-7ae6-11e9-99d8-1e583bb52d4d.png)

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
