### ISSUE TITLE
Add 'Size' field to 'Properties' dialog of ADLS Gen2 blobs

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1175]
**Storage Explorer Version**: 1.7.0/20190227.3
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Commit**: 1f111467
**Regression From**: Not a regression
#### Steps to Reproduce: ####
1. Choose one ADLS Gen2 account -> Open one blob container.
2. Upload a blob file to it -> Select the uploaded blob then check the system properties on 'Properties' dialog.

#### Expected Experience: ####
The 'Size' field shows on the 'Properties' dialog.
#### Actual Experience: ####
No 'Size' field shows on the 'Properties' dialog.
![image](https://user-images.githubusercontent.com/34729022/53556175-2e9f4100-3af8-11e9-82bd-21493f130be7.png)

**Comment by MRayermannMSFT** [comment]
Closing as won't fix. Size is available in the editor.
