### ISSUE TITLE
Cannot login due to username / alias does not match

### ISSUE THREAD

**Issue by noselander** [Microsoft/AzureStorageExplorer#1177]
**Storage Explorer Version**: 1.4.1
**Platform/OS**: Win10
**Architecture**:  x64? 
**Bug description**
Cannot login using AAD since username returned does not match alias / email or some other attribute.

**Steps to Reproduce**

Try to login using an account in AAD that has both alias and firstname.lastname registered.

{
  "message": "\"User 'Joachim.Nasslander@microsoft.com' returned by service does not match user 'jonas@microsoft.com' in the request\""
}

**Expected Experience**
A successful login

**Actual Experience**
Login denied due to mismatch between username / alias / smtp

**Comment by craxal** [comment]
@noselander We recently released v1.7.0. Can you update and try again?

**Comment by noselander** [comment]
Done, works :)

Might start using it a little more often...

/j

On Mar 11, 2019 19:10, Craig <notifications@github.com> wrote:

@noselander<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnoselander&data=02%7C01%7CJoachim.Nasslander%40microsoft.com%7C23d02a06d9544ec3c40908d6a64cc6cf%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636879246017851225&sdata=kudw4d3jrHU8y3CmPEfcIjxmK0fBqKqLNjZ3j2aV%2F8o%3D&reserved=0> We recently released v1.7.0. Can you update and try again?

**Comment by jinglouMSFT** [comment]
Great!  Glad it works out for you.  Thanks for using Storage Explorer.
