### ISSUE TITLE
Duplicate property shows on 'Actions/Properties' window for one storage account

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#1184]
**Storage Explorer Version**: 1.7.0/20190228.2
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Commit**: c01e74cc
**Regression From**: Not a regression

**Steps to Reproduce:**
Select a storage account node -> Check the 'Actions/Properties' window.

**Expected Experience:**
There is no duplicate property shows.

**Actual Experience:**
There is a duplicate property shows.
![image](https://user-images.githubusercontent.com/41351993/53625015-f2c1c400-3c3c-11e9-8697-291596ac1688.png)

**Comment by v-xianya** [comment]
Hi @craxal Verified on build 20190410.5. This issue still reproduces. So we re-open it.

**Comment by craxal** [comment]
Build 20190410.5 does not have the change in it. Please verify in a newer build.

**Comment by v-xianya** [comment]
Hi @craxal , Verified on build 20190415.1. 
This issue reproduces for one **classic** storage account. So we re-open it.
