### ISSUE TITLE
Unable to retrieve Cosmos DB accounts

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1185]
**Storage Explorer Version**: 1.7.0/20190228.2
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Commit**: 
**Regression From**: Previous release 1.7.0(Preview)

#### Steps to Reproduce: ####
1. Try to expand one Cosmos DB account.

#### Expected Experience: ####
The cosmos db account can be opened successfully.
#### Actual Experience: ####
An error occurs.
![image](https://user-images.githubusercontent.com/34729022/53626183-ec3e3880-3bb9-11e9-95f1-4c90be41d75e.png)

**Comment by jinglouMSFT** [comment]
This should have been fixed in Storage Explorer v1.7.0 release.
