### ISSUE TITLE
There is no audio feedback for deleting a file

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#1187]
**Storage Explorer Version**: 1.7.0
**Platform/OS**: All
**Architecture**: All
**Regression From**: No

**Bug description**
Usability study indicated that we need some audio feedback for deleting a file. This is impacting:
- LV + 200%
- 200% + HC
- NVDA
- JAWS

We should consider including an ARIA alert message letting the user know if a file was deleted successfully or not.

**Comment by MRayermannMSFT** [comment]
This doesn't repro any more. We have activity messages, and therefore audio feedback, for deleting blobs.
