### ISSUE TITLE
The edit control in the treeview needs a prompt for entering a container name (NVDA)

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#1189]
**Storage Explorer Version**: 1.7.0
**Platform/OS**: All
**Architecture**: All 
**Regression From**: No

**Bug description**
There is no feedback when creating a new blob container or folder.  It says 'tree view'. It doesn't say that the user is naming it. (NDVA)

The edit control in the treeview needs a prompt for entering a container name.

**Comment by MRayermannMSFT** [comment]
The aria label of the input now says what it is for.
