### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by MRK1993** [Microsoft/AzureStorageExplorer#119]
**Storage Explorer Version**: 1.0.0

**Platform**: Windows 7

Hi, 

I seem to have an issue with the latest version of the app hanging on bootup. 

The app enters a constant 'loading' state and fails to launch. 

I've attempted to re-install the application in addition to clearing the appdata, with no luck. 

Any help would be appreciated. 

Thanks!

**Comment by craxal** [comment]
@MRK1993 Sorry you're having trouble. What platform are you installing Storage Explorer on? If you're on Linux, you'll need to install .NET Core (see the [release notes](https://docs.microsoft.com/en-us/azure/vs-azure-tools-storage-explorer-relnotes)).

**Comment by dragan088** [comment]
I have the same issue on Windows 7. Decided to upgrade to 1.0.0 this morning. After installation the app hangs on "Loading" splash screen. I'm now regretting upgrading, all my links, 20 odd links are lost. Is there any way to recover the settings?

**Comment by MRK1993** [comment]
@craxal Thanks for the response. My issue is with the Windows 7 application, as the above user reported the application hangs at the loading screen.

**Comment by dragan088** [comment]
I don't get any output from command line. Btw, I've found the links saved in %APPDATA%\AzureStorageExplorer Thanks for that. I will try updating .net environment.

**Comment by dragan088** [comment]
Updating .NET to 4.7.2 fixed the issue.

Thanks

**Comment by MRayermannMSFT** [comment]
Thanks for sharing the fix @dragan088 . I'll add needing .NET 4.7.2 to our prerequisites documentation.
