### ISSUE TITLE
The search function on LHS doesn't work as expected 

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#1190]
**Storage Explorer Version**: 1.7.0
**Platform/OS**: All
**Architecture**: All 
**Regression From**: No

**Bug description**
Experience 1: Trying to change theme. "we typed the word 'theme' into the search bar here. Searching. And nothing's happening, it just says 'searching'". (JAWS)
Experience 2: The user conducted a search 3 times because they were unaware the search completed. (JAWS)
Experience 3: The user thought their files disappeared because they were unaware their search filtered out their files. (JAWS)

We should consider adding some explanatory text or a help icon near the search bar to generally describe how it works or what the user can search for

**Comment by mscirri** [comment]
I am having a similar issue where the progress wheel just keeps spinning forever.  Never sure if it is done searching or is just really slow but 3 hours later I just cancelled it.

**Comment by JasonYeMSFT** [comment]
Let's come up with the a detailed design on how to improve the search experience in 1.21.0.

**Comment by JasonYeMSFT** [comment]
Closing as we have released 1.22.0.
