### ISSUE TITLE
Can't use Alt to go across the app menu to explore it, so there is no real way of knowing what different options are in the menu (NVDA)

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#1191]
**Storage Explorer Version**: 1.7.0
**Platform/OS**: All
**Architecture**: All
**Regression From**: No

**Bug description**
"I can't just hit Alt to go across the menu to explore it, so there is no real way of knowing what different options are in the menu"
The Alt key doesn't stick so there is no way to navigate through the top menu. 

Reference to the Office experience.

**Comment by JasonYeMSFT** [comment]
This doesn't reproduce with our current build. For all platforms, the alt key/ctrl+F2 stick with the app menu for navigation.

**Comment by MRayermannMSFT** [comment]
This was fixed by updating Electron.
