### ISSUE TITLE
The Alt key doesn't do anything on the toolbar buttons

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#1192]
**Storage Explorer Version**: 1.7.0
**Platform/OS**: All
**Architecture**: All
**Regression From**: No

**Bug description**
The Alt key doesn't do anything on the toolbar buttons (NVDA)

the Alt key doesn't stick so there is no way to easily go to the Toolbar buttons for rename or other activities.  We need a better experience here. Reference to the Office UI maybe.

**Comment by JasonYeMSFT** [comment]
Office on Windows supports adding some toolbar buttons to a "quick access toolbar" which can be accessed by pressing Alt, and then pressing a number key. However, this is not a standard design for other applications. An alternative solution is a "Go to toolbar" shortcut to help people quickly navigate to the toolbar items.
