### ISSUE TITLE
Improperly labeled links cause confusion when navigating the app (NVDA)

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#1193]
**Storage Explorer Version**: 1.7.0
**Platform/OS**: All
**Architecture**: All
**Regression From**: No

**Bug description**
The user encountered multiple links labeled 'clickable' but didn't provide any additional context for what they referred to. (NVDA)
This corresponds to user study scenario 7 under the general findings. 

- [x] #5245
- [x] Actions panel (bottom left)
- [x] Buttons at top of tree view
- [x] #5246
- [x] Some sort of refresh link in most of our explorers (search for "Refresh!")
- [x] All href buttons in the query builder
- [x] ReleaseNotes.html links  (check to make sure not just spoken as "link")
- [x] Configure delete retention learn more (check to make sure not just spoken as "link")
- [x] EULA privacy statement link (check to make sure not just spoken as "link")
- [x] Generate SAS learn more (check to make sure not just spoken as "link")
- [x] MultiOptions learn more (check to make sure not just spoken as "link")
- [x] Options learn more (check to make sure not just spoken as "link")
- [x] Telemetry learn more (check to make sure not just spoken as "link")
- [x] Tab buttons
- [x] Vertical toolbar buttons
- [x] Tree view "Refresh all" button announces its label. But it redundantly announce it twice, "Refresh all, link, Refresh all".
- [x] All the "Refresh!" link in explorer have style "display:none" and aren't used.

**Comment by JasonYeMSFT** [comment]
Get a list of those button locations in 1.19.0 and make sure they are labeled properly in 1.20.0

**Comment by MRayermannMSFT** [comment]
- Tree view load more
- Actions panel (bottom left)
- Buttons at top of tree view
- Tree view toolbar items (I don't think we use these, they were a Cloud Explorer only thing, but the code does exist)
- Some sort of refresh link in most of our explorers (search for "Refresh!")
- All blue links in the query builder
- Recursive ACL learn more
- Set access tier learn more
- ReleaseNotes.html
- Configure delete retention learn more
- EULA privacy statement link
- Generate SAS learn more
- MultiOptions learn more
- Options learn more
- Telemetry learn more

**Comment by MRayermannMSFT** [comment]
Good mention from Craig, anchors are only suitable if the "link"/"blue text" is in the middle of like a sentence or paragraph.

**Comment by JasonYeMSFT** [comment]
A few findings after checking the items that already have clear labels.
- Tree view "load more" node only announce its label "load more", which makes it hard to guess whether it is interact-able or not.
- Tree view "Refresh all" button announces its label. But it redundantly announce it twice, "Refresh all, link, Refresh all".
- All the "Refresh!" link in explorer have style "display:none" and aren't used.
- Only the access policy prompt dialog uses MultiOption dialog and it doesn't have a link.

**Comment by JasonYeMSFT** [comment]
Closing since we have addressed all the listed sub-work items.
