### ISSUE TITLE
It is unclear which theme is currently selected

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#1194]
**Storage Explorer Version**: 1.7.0
**Platform/OS**: All
**Architecture**: All
**Regression From**: No

**Bug description**
There is no visual or audio indication on which theme is currently selected in the theme sub-menu. Comments from the user study "What I would expected is the selected theme to be marked as 'checked' and it is not"  (NVDA) 

Expected:
The menu for the currently selected theme should be checked and read when the submenu is opened.

**Comment by JasonYeMSFT** [comment]
I happened to know how to do this when adding the accelerator.
