### ISSUE TITLE
During Azure sign-in, the authentication dialog should read out "Enter password" instead of "Alert" (NVDA)

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#1196]
**Storage Explorer Version**: 1.7.0
**Platform/OS**: All
**Architecture**: All
**Regression From**: No

**Bug description**
The sign-in authentication dialog should read "Enter password" instead of "Alert".  The user was able to guess that it's asking for password because it's after an email address. But the user experience wasn't optimal.

**Comment by MRayermannMSFT** [comment]
I can no longer repro this issue, both when MSAL is enabled/disabled. NVDA reads a good description for the password text box.
