### ISSUE TITLE
It is unclear that the dropdown for Azure Environment is associated with the Add an Azure Account radio button in the connection dialog (NVDA)

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#1198]
**Storage Explorer Version**: 1.7.0
**Platform/OS**: All
**Architecture**: All
**Regression From**: No

**Bug description**
As the title says. Visually we also need an indentation for the combo box. Screen reader should associate the combobox to the "Add an Azure Account" radio button.

**Comment by MRayermannMSFT** [comment]
Fix merged into main.
