### ISSUE TITLE
It is unclear why the Apply button is disabled when adding a new account in the account panel (NVDA)

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#1199]
**Storage Explorer Version**: 1.7.0
**Platform/OS**: All
**Architecture**: All
**Regression From**: No

**Bug description**
"This is a very weird way to design the interface. You add the account, then you basically can't even apply it and you have to click cancel to close that window".   From the usability study, it looked to me that the Apply button was only grayed out when there was no account to add. This was specific to screen reader. When in the previous session there were accounts added, the Apply button was only disabled when we tried to load the accounts. Maybe we need to look into when the screen reader reads what when. In the video, the Apply button was actually visually enabled.  Maybe the screen reader can't catch the state change fast enough and read the old state of the button?  Needs some investigations.

**Comment by JasonYeMSFT** [comment]
The button now has a description announcing why it is disabled.
