### ISSUE TITLE
No error displays when there are multiple '/' in the path from 'Upload to folder (optional)'

### ISSUE THREAD

**Issue by v-dantch** [microsoft/AzureStorageExplorer#120]
**Storage Explorer Version**: 1.1.0

**Platform**: Windows

**Architecture**: ia32

**Build Number**: 20180510.4

**Commit**: 754b96f7

**Regression From**: Not a regression 

#### Steps to Reproduce: #### 

1. Open one blob container,  click 'Upload' and select 'Upload Files'. .
2. Select one file at least and type a path to 'Upload to folder (optional)' with multiple '/'.
3. Check whether there is an error or not.

#### Expected Experience: ####
 There is an error to prompt you the path is wrong and fail to upload.

#### Actual Experience: ####
No error displays and succeed to upload.
![actual](https://user-images.githubusercontent.com/34729092/39516632-065be25a-4ded-11e8-9c1c-1a31e1bd5213.PNG)

**Comment by craxal** [comment]
I don't consider this a bug, but it sounds related to #92.

**Comment by MRayermannMSFT** [comment]
We should indicate that we are collapsing the extra slashes into one.

**Comment by v-xianya** [comment]
Close this issue according to the related bug: [3389](https://github.com/microsoft/AzureStorageExplorer/issues/3389)
