### ISSUE TITLE
The treeview does not wrap back up to the top on LHS

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#1200]
**Storage Explorer Version**: 1.7.0
**Platform/OS**: All
**Architecture**: All
**Regression From**: No

**Bug description**
If you down arrow on the last item it wraps you back to the top. But if you arrow up at the top, it doesn't wrap back down to the bottom, which is expected. (NVDA)

**Comment by JasonYeMSFT** [comment]
We should stop wrapping on both top and bottom.

**Comment by MRayermannMSFT** [comment]
We are no longer wrapping in either direction.
