### ISSUE TITLE
Toolbar button labeled as menu item caused confusion when using the app

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#1201]
All the toolbar controls of the app are read as Buttons except for Upload, which is read as a menu. Technically the Upload control is a menu as it has two different choices under it, while the rest of the controls are indeed just buttons. Let's think about what we can do to make the user experience a bit better for the upload scenario/button.

**Comment by craxal** [comment]
Accessibility team says that setting the button's role as menu is the correct thing to do. So I'm going to close this as Won't Fix.
