### ISSUE TITLE
In Manage Snapshot editor, the full file name is not read by the screen readers (NVDA)

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#1202]
**Storage Explorer Version**: 1.7.0
**Platform/OS**: All
**Architecture**: All
**Regression From**: No

**Bug description**
The full file name is not read by the screen readers, making it sound like you have multiple files with the same name.  After creating a few snapshots, the screen reader didn't read the timestamps associated with the snapshots.  (NVDA)

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
