### ISSUE TITLE
Files cannot be copied and pasted into the Storage Explorer

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#1203]
Screen reader users have extreme difficulties to drag and drop their files into Storage Explorer.  As an alternative, they attempted to copy and paste their files.  We currently can't do copy files from the file explorer to storage explorer.  We can only do copy and paste from and to storage explorer.

**Comment by MRayermannMSFT** [comment]
Currently not possible.
