### ISSUE TITLE
can not log in

### ISSUE THREAD

**Issue by lorenzobrito** [Microsoft/AzureStorageExplorer#1205]
**Storage Explorer Version**: 1.6.2 , also installed from https://azure.microsoft.com/es-mx/features/storage-explorer/
**Platform/OS**: 
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic
lorenzo@lorenzo-FX503VD:~/
**Architecture**: 64
**Regression From**: 

**Bug description**
Cant sig in. 
**Steps to Reproduce**
unzip the tar. 
./Storeexplorer

**Expected Experience**
Sig in  and able to see tables

**Actual Experience**
When I sig in, nothing happens .

**Additional Context**
Received message 'register-dialog'
Received message 'register-dialog'
Received message 'register-dialog'
Received message 'register-dialog'
A dialog has already been registered with namespace 'AzCopy.Dialog.RetryTransfers'
Received message 'register-dialog'
A dialog has already been registered with namespace 'AzCopy.Dialog.UploadBlobs'
Received message 'register-dialog'
A dialog has already been registered with namespace 'Azure.Storage.AdlsGen2.managePermissions'
Received message 'get-dialog-result'
Received message 'dialog-ready'
Received message 'dialog-execute-operation'
Received message 'did-execute-operation'
Received message 'dialog-execute-operation'
Received message 'did-execute-operation'
Received message 'dialog-execute-operation'
Received message 'did-execute-operation'
Received message 'dialog-execute-operation'

**Comment by lorenzobrito** [comment]
I have also tried to add a connection by conecction string but nothing happen

**Comment by nipunsahni** [comment]
I am unable to login after a restart. It throws the below error
{
  "message": "\"OK\""
}

**Comment by jinglouMSFT** [comment]
@lorenzobrito You have the following dependencies installed?
- libsecret
- libgconf-2-4
- up-to-date GCC
- .NET Core 2.x (I'd assume you have this installed as you can actually start the app)

**Comment by camckay** [comment]
Same issue on Ubuntu 18.04.  All dependencies are installed, and program was working previously.

**Comment by MRayermannMSFT** [comment]
Hi everyone, we recently spent some time updating our Linux dependencies instructions. Please try them (and do note the issue with newer versions of .NET core) and let us know if you're still blocked: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=1804#linux-dependencies

**Comment by MRayermannMSFT** [comment]
Going to close this for now. It sounds like the troubleshooting steps we've distributed have worked for everyone. Please open a new issue if you continue to encounter issues after either patching Storage Explorer, downgrading .NET Core, or confirming you have the right dependencies installed.
