### ISSUE TITLE
Pressing 'Enter' doesn't open the web page when tabbing to the link 'Learn more about default ACLs' on 'Manage Access' dialog 

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1207]
**Storage Explorer Version**: 1.7.0/20190304.2
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Commit**: 10e32996
**Regression From**: Not a regression

**Steps to Reproduce**
1. Expand one ADLS Gen2 account -> 'Blob Containers'.
2. Right click one blob container then select 'Manage Access...'.
3. Tab to the link '_Learn more about default ACLs_' on 'Manage Access' dialog -> Press 'Enter'.

**Expected Experience**
The web page opens well.

**Actual Experience**
Nothing happens after pressing 'Enter'.

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
