### ISSUE TITLE
Keep deleting more than 10 mins after deleting files/directories from a non-existent file share

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#121]
**Storage Explorer Version**: 1.1.0 RC
**Platform**: Windows/Linux/Mac
**Architecture**: x64

**Build Number**: 20180501.4
**Commit**: 754b96f7

**Regression From**: 1.0.0

#### Steps to Reproduce: ####

1. Launch Storage Explorer and expand storage accounts.
2. Create a file share and upload a file to it.
3. Open a new instance and delete the created file share in step2. 
4. Back to the main instance and delete the uploaded file.
5. Check the log message in Activities Panel.

#### Expected Experience: ####
Fail to delete the file from the non-existent file share.

#### Actual Experience: ####
Keep deleting more than 10 mins.
![deleting](https://user-images.githubusercontent.com/34729022/39516834-a472b6d0-4ded-11e8-9f44-514c2457ca7a.png)

**Comment by MRayermannMSFT** [comment]
Closing as won't fix.
