### ISSUE TITLE
Invalid url when using custom port with custom endpoint suffix for File Services

### ISSUE THREAD

**Issue by vadmyst** [microsoft/AzureStorageExplorer#1211]
**Storage Explorer Version**: 1.6.2
**Platform/OS**: Windows 10?
**Architecture**: x64?
**Regression From**: 0.9.2

**Bug description**
When creating File Storage connection using custom endpoint with explicit port number. Storage explorer displays error dialog that url is invalid. The url is encapsulated into square brackets.

**Steps to Reproduce**
1. Connect to Azure storage 
2. Select use storage account name and key.
3. Specify account name and key
4. Select Storage domain as Other (enter below)
5. Enter custom domain with explicit port number
6. Press Connect

**Expected Experience**
Successful connection

**Actual Experience**
Error dialog as in attachmen

![error](https://user-images.githubusercontent.com/331752/53770298-7379fd80-3e93-11e9-839f-7640236378a2.png)

**Additional Context**
Traced the reason to be in url.format method that wraps the url in square brackets when explicit port is specified

![url_format](https://user-images.githubusercontent.com/331752/53770300-7379fd80-3e93-11e9-8b11-d7a0768d906c.png)

**Comment by craxal** [comment]
It looks like custom domain is essentially translated to `EndpointSuffix` in the generated connection string. I don't know if custom endpoints with ports is supported. Do you need a custom port for your custom endpoint?

**Comment by vadmyst** [comment]
Custom port used to be supported on previous versions of Storage Explorer. Additionally, AFAIR there was an Azure storage emulator that could use custom port.

The reason we need custom ports is because we do not do direct connection but through a special proxy software.

**Comment by craxal** [comment]
What end is the proxy on? It sounds like you just need to turn on proxy settings. Also, if you're connecting to an emulator, you should use the "Connect to local emulator" option in the Connect dialog. It has fileds for port numbers and handles it correctly.

**Comment by vadmyst** [comment]
Proxy is local to the Storage Explorer.

**Comment by craxal** [comment]
OK, so it sounds like you just need to enable proxy settings. You can do that from the menu **Edit** > **Configure Proxy**. If all you need is a hostname and port number, it should work just fine.

**Comment by vadmyst** [comment]
The proxy software I was talking about is not classic HTTP proxy. It works on the TCP level. So essentially Storage Explorer connects to that software thinking that it is one of the Azure Storage servers.

**Comment by craxal** [comment]
I believe you said the software runs on your local machine, yes? You should still be able to route Storage Explorer web requests correctly by configuring the proxy to go through localhost:4433.

**Comment by vadmyst** [comment]
Not always. It can also run on the same network or on premises in customer environment.

**Comment by craxal** [comment]
Is your system also configured to go through this proxy? Can you tell me anything else about the proxy, such as whether it is an NTLM proxy?

**Comment by vadmyst** [comment]
My system does not run through this proxy and as far as I know it is not an NTLM proxy. 
I do not understand why does it matter? Even if can tweak or setup proxy differently on my local environment I do not have such control on other environments. 
The issue here is that Storage Explorer does not handle custom ports correctly, while in the past there was no such problem.

**Comment by craxal** [comment]
I've suggested proxy settings, because that's where port numbers are usually use the way you're describing. As far as I know, your scenario is not one we usually cover, so we don't have tests that make sure your scenario continues to work.

Since that's apparently not the issue here, I did some deeper investigation and found where the bad URL is coming from. It's deep down in the Azure Storage client library for Node that we use. The bad news is I don't know a way around this, so we'll have to push for a fix.

One of the reasons this may have changed is because we switched to passing around connection strings to make our architecture simpler a while ago.

@XiaoningLiu Is this something we can get fixed in v2.*? I'm not aware of an explicit way to pass ports via connection string, so we may have to be smart about how we parse the DNS/suffix/endpoints.

**Comment by vadmyst** [comment]
@XiaoningLiu, I guess v2.* should be fine. Do you have any timelines for when that version would come around?

**Comment by XiaoningLiu** [comment]
Hi, I think definition of `DNS/suffix/endpoints` refers to an endpoint suffix, which doesn't include port. So it's more like a feature request instead of bug fix. Out our curious, did it work previously?

**Comment by craxal** [comment]
Yes, according to @vadmyst, but I think that's because we were using URIs directly. As I explained above, we switched to using connection strings throughout to simplify the architecture some time ago.

**Comment by XiaoningLiu** [comment]
Got it. Which connection section are you using? "EndpointSuffix" or "BlobEndPoint"? "EndpointSuffix" doesn't support a port, while "BlobEndPoint" can support a customized port like "http://account.blob.core.windows.net:8080"

**Comment by vadmyst** [comment]
I did not use connection string explicitly. Look the the first post in this thread for details how to reproduce. BTW, we are using File Services.

**Comment by craxal** [comment]
@vadmyst Just about every attachment you make we convert to a connection string.

Here's something you can try. Instead of using the account name and key option in the Connect dialog, do the following:

1. Construct a connection string manually using the account name, key, and custom endpoints (see [here](https://docs.microsoft.com/en-us/azure/storage/common/storage-configure-connection-string#connect-to-the-emulator-account-using-the-well-known-account-name-and-key)). For example:
   ```text
   DefaultEndpointsProtocol=http;
   AccountName=myaccount;
   AccountKey=ABC...==;
   BlobEndpoint=http://my.custom.blob.endpoint:1234;
   FileEndpoint=http://myaccount.file.core.windows.net:1234
   ```
2. Open the Connect dialog and choose the connection string option.
3. Enter the connection string you constructed, give the connection a name, etc.

**Comment by MRayermannMSFT** [comment]
Closing. No responses since June. This is a known limitation of connection strings.

**Comment by ayeltsov** [comment]
Commenting on a closed issue in case this helps someone.
The below suggestion worked well for me.

I have local proxy on 8433 forwarding to emulator so I can observe the traffic, and hosts entry for myaccount.blob.core.windows.net.

DefaultEndpointsProtocol=http;AccountName=myaccount;AccountKey=TXlLZXk=;BlobEndpoint=http://myaccount.blob.core.windows.net:8433;

> @vadmyst Just about every attachment you make we convert to a connection string.
> 
> Here's something you can try. Instead of using the account name and key option in the Connect dialog, do the following:
> 
> 1. Construct a connection string manually using the account name, key, and custom endpoints (see [here](https://docs.microsoft.com/en-us/azure/storage/common/storage-configure-connection-string#connect-to-the-emulator-account-using-the-well-known-account-name-and-key)). For example:
>    ```
>    DefaultEndpointsProtocol=http;
>    AccountName=myaccount;
>    AccountKey=ABC...==;
>    BlobEndpoint=http://my.custom.blob.endpoint:1234;
>    FileEndpoint=http://myaccount.file.core.windows.net:1234
>    ```
> 2. Open the Connect dialog and choose the connection string option.
> 3. Enter the connection string you constructed, give the connection a name, etc.
