### ISSUE TITLE
Trying to connect ADLS and it keeps on showing the processing, but to no avail.

### ISSUE THREAD

**Issue by lanaindia** [microsoft/AzureStorageExplorer#1215]
**Storage Explorer Version**: Azure storage 1.6.2
**Platform/OS**:  Windows 7?
**Architecture**: x64 
**Regression From**: This was working when it was downloaded in Dec end  28th or so... and from recent 1 month past, it does not connect

**Bug description**
NOT able to connect to Azure data lake store .
Even though we are connected to azure subscription

**Steps to Reproduce**
1. Launch storage explorer,
2. Set proxy
3. connect to azure subscription
4. browse to azure data lake store 

Then it does not connect and does not show any folder

**Expected Experience**
It should show contents of azure data lake store

**Actual Experience**
Not connecting to ADLS

**Additional Context**

**Comment by craxal** [comment]
@landaindia We recently released v1.7.0. Can you please upgrade and try again?

@djlan Can your team take a look into this?

**Comment by lanaindia** [comment]
Even installed the latest released v1.7.0 and having the same issue.
I have the right proxy set up and it is detecting the ADLS from all my subscriptions. But I am not able to view any folder of ADLS.
It shows processing status for a long time  just to show me the below message ..which is very frustrating 
tunneling socket could not be established, statusCode=407

This tool has been nightmare to me since a year, here or there or other, it will have prob :(

**Comment by lanaindia** [comment]
If somebody from MS wants to have a live demo, I am happy to demonstrate it...

**Comment by lanaindia** [comment]
I have raised the same issue under x-plat-cli ... can somebody merge that issue with this issue

**Comment by djlan** [comment]
Investigating.

**Comment by anoopasokan** [comment]
I am also facing the same issue with ADLS gen 2. Is there any update for this issue?

**Comment by craxal** [comment]
@anoopasokan ADLS Gen2 is an entirely different feature set. If you are experiencing an issue with connecting to ADLS Gen2, please open a separate issue.

**Comment by jinglouMSFT** [comment]
The retirement of ADLS Gen1 is now less than three months away. As [previously announced](https://azure.microsoft.com/en-us/updates/action-required-switch-to-azure-data-lake-storage-gen2-by-29-february-2024/) the service will be retired on 29 February 2024. With this date now close approaching we are going to close this issue as "won't fix". Documentation on how to migrate your data to ADLS Gen2/blob storage can be found here: https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-migrate-gen1-to-gen2-azure-portal

If you have any non ADLS Gen1 feedback for Storage Explorer, please feel free to open a new issue: https://github.com/microsoft/AzureStorageExplorer/issues/new/choose

This issue will now no longer be monitored.
