### ISSUE TITLE
Upload VHDs as Page Blobs

### ISSUE THREAD

**Issue by JackStromberg** [Microsoft/AzureStorageExplorer#1216]
**Storage Explorer Version**: 1.7.0
**Platform/OS**:  Windows 10
**Architecture**: _x64

**Bug description**
When uploading a VHD, Storage Explorer doesn't prompt for what type to upload, so it goes up as a block blob.  VHDs should either default page blob or prompt upon every upload as odds are, it's going to be page blob.

**Expected Experience**
Blob type should be page blob

**Actual Experience**
VHDs are uploaded as block blobs

**Additional Context**
The setting to use page as the blob type for VHDs should hold true for those using the new AzCopy feature to help speed uploads/downloads of large blobs.

**Comment by craxal** [comment]
@JackStromberg Are your dragging and dropping or using the toolbar button? Are you using AzCopy?

Related to #1204.

**Comment by JackStromberg** [comment]
Drop/Drop.  Don't get prompted when using the AzCopy preview feature.

Reading through the other related items, that seems to be the exact same experience I have.

Jack

**Comment by craxal** [comment]
@JackStromberg Thanks! We'll go ahead and close this as a duplicate then. We will be addressing the drag and drop issue.
