### ISSUE TITLE
Azure Storage Explorer access problem

### ISSUE THREAD

**Issue by mcissecontractor** [microsoft/AzureStorageExplorer#1217]
Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: cb1c5458-f4a9-49f7-9f0e-373d74f884e8, Error: {"code":"ENOTCONN","errno":"ENOTCONN","syscall":"connect","address":"52.143.136.20","port":443}

**Comment by craxal** [comment]
@mcissecontractor Please provide us some more information:
1. Storage Explorer version installed
2. Platform (OS and version)
3. Repro steps describing clearly how you arrived at your problem.
4. Information about your network, such as whether you're behind a proxy or if you have problems when using another network, such as a home network.

**Comment by AliviaB** [comment]
I am getting same error.It always asks me to reenter credentials

**Comment by MRayermannMSFT** [comment]
@AliviaB , can you give us some more information about your network: Are you behind a proxy? Do you have any network inspection software running? Are you able to use storage explorer on a different network?

**Comment by AliviaB** [comment]
Hi,
Yes I am behind proxy, and there are many network inspection soft wares. I am able to use it properly on other networks.

**Comment by vikaschaurasia** [comment]
I have same issue , may i know how to resolve 

Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: f25493ae-1c98-41d7-8a33-0be75f5fe603, Error: {"code":"ECONNRESET"}

**Comment by MRayermannMSFT** [comment]
Hi @vikaschaurasia , are you behind a proxy?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
