### ISSUE TITLE
After upgrading to version 1.7.0 the app always crashes when attempting to open table

### ISSUE THREAD

**Issue by KewalkKelly** [microsoft/AzureStorageExplorer#1219]
After the latest upgrade the app is unusable due to crashing on every attempt to use.  It opens, lets me expand my Storage Accounts and drill into a table.  Soon after this it crashes every time when opening a table or expanding more accounts it seems.

This is the popup message right before ending.
"A problem caused Storage Explorer to stop working correctly (a renderer process crashed). Storage Explorer can try to restart the program."
[Restart] [Close Application]

Microsoft Azure Storage Explorer
Version: 1.7.0
Platform: Windows
Architecture: ia32
Build Number: 20190305.10
Commit: 49598b7f
Support Id: 036f0072-2d3a-1f74-e933-ac519b02cd47

**Comment by KewalkKelly** [comment]
This is the popup message right before ending.
A problem caused Storage Explorer to stop working correctly (a renderer process crashed). Storage Explorer can try to restart the program.

[Restart] [Close Application]

**Comment by MRayermannMSFT** [comment]
Hi @KewalkKelly , can you reinstall 1.6.2 and confirm that this is a regression? You can find that version here: https://github.com/Microsoft/AzureStorageExplorer/releases/tag/V1.6.2
Also, can you provide any other details about your table? Are you connected via Name and Key, SAS, or Sign In? Is the table in an emulator?

**Comment by KewalkKelly** [comment]
v1.6.2 works for me again after uninstalling 1.7 and reinstalling.  I'm connected via Sign In and have multiple accounts used for different storage accounts in different azure subscriptions.  I also have some connected via key that I'd forgotten about until you asked but didn't try to open those on v1.7.  I have no connections to an emulator.

**Comment by MRayermannMSFT** [comment]
@KewalkKelly , two questions:

1. Does this happen for blobs, file shares, and queues?
2. Are you able to view the release notes? Help -> Release Notes

**Comment by KewalkKelly** [comment]
I am able to view the Release Notes.
The issue happens for Blobs, File Shares and Tables.
It does Not happen for Queues or CosmosDB Accounts.

**Comment by MRayermannMSFT** [comment]
@KewalkKelly , is this still reproing in 1.9.0?

**Comment by KewalkKelly** [comment]
Based on one of the earlier questions I had removed all Local and Attached connections and the issue has not recurred even in earlier versions.  In v1.9.0 now re-adding some connections by Account Name and Key I don't experience any problems although I'm not sure I'm recreating the precise scenario I had.
