### ISSUE TITLE
AzCopy doesn't copy all files

### ISSUE THREAD

**Issue by gdignard** [Microsoft/AzureStorageExplorer#1220]
I have a blob container with 9632 items. I tried a download all but the copy didn't start after waiting 5+ minutes so I specified a prefix of "0" (names all begin with a guid) which yielded 586 items.

After the AzCopy was complete, only 585 items had been downloaded (first and last in the list were both there; the missing one is somewhere in between).

I followed up with a regular non-AzCopy attempt which took quite a bit longer, but had the pleasant attribute of downloading all 586 items.

v1.7

**Comment by craxal** [comment]
Looks like two different issues being described here:
1. The list of blobs to download is large.
2. AzCopy doesn't download all blobs from a filtered list.

**Comment by gdignard** [comment]
Correct.

The first item I noted more as a context (probably a QOL issue I could have waited out) to the second item (a bug serious enough to have me avoid using this until positively identified and fixed).

- Gilles

**Comment by MRayermannMSFT** [comment]
@gdignard , would you be willing to give a SAS to the data you're trying to download? With read and list permissions? We've upgraded the integrated AzCopy version and we'd like to try the download with that. Alternatively we can send you a private build.

**Comment by gdignard** [comment]
Matthew -

Unfortunately while I'd be fine with it, providing access to the data
wouldn't exclusively be my decision to make.

I'd be more than happy, however, to install and try out a private build;
far easier at my end to travel that path.

- Gilles

**Comment by craxal** [comment]
@gdignard Can you list the steps you followed? Specifically, how did you select all blobs to download? I can easily see why no all 9,000+ items would get downloaded, but the all but one of 586 items is a little more mysterious. Is there anything special about the omitted item, such as is it at the beginning or end of the list, or does it have a significantly different name?

**Comment by MRayermannMSFT** [comment]
Hey @gdignard , we're updating the AzCopy version for our upcoming release. If you are willing, we'd like you to give it a try in a private build of Storage Explorer to see if the new version fixes the issues you were seeing. Here are links to the build:

- macOS: https://storageexplorerpublish.blob.core.windows.net/privatebuilds/AzCopy-v10-0-9/StorageExplorer-darwin-x64.zip
- Windows https://storageexplorerpublish.blob.core.windows.net/privatebuilds/AzCopy-v10-0-9/StorageExplorer-ia32.exe
- Linux: https://storageexplorerpublish.blob.core.windows.net/privatebuilds/AzCopy-v10-0-9/StorageExplorer-linux-x64.tar.gz

Let us know if this new version works for you. If if doesn't we can take a look at your AzCopy logs to find out more now that you'll be running against the latest version.

**Comment by gdignard** [comment]
Matthew / AzureStorageExplorer team -

I just had a chance to install and try out the new build.

Since it was a transient thing, I can't say for sure the bug is gone, but I
can say that I tried the same thing as before and it worked.

Specifically, the Blob Container I tested against has 10,036 items, no
directory structure, and all blob names are in the form
"{guid}.{extension}".

With AzCopy turned on, I tried filtering and downloading each of the
sixteen initial characters ('0' - 'f'), noted how many items there were
with that filter applied and then did a "Select All Cached" and Download to
a specific folder.

Previously, one of the items ('0') yielded a different number of items
downloaded from found. This time all sixteen were correct.

I also did a download of all 10,036 and that worked as well. (Suggestion:
It would be nice not to have to select "Load more" over and over but have
some option to "Download all blobs in container" like it's possible to do
when Exporting from Tables)

Azure Storage is a go-to product for me; great to see it getting better and
better all the time!

Thanks,

- Gilles

**Comment by MRayermannMSFT** [comment]
Wohooooooo!!!! I'm really glad it worked. And yes, making it easy to download an entire container is definitely on our backlog. Look for it in a future release. 😄

**Comment by gdignard** [comment]
Matthew -

A final quick question. We make use of the Blob REST API and as AzCopy is
currently only available as a command-line (and from within the Storage
tool), I'm wondering if AzCopy is something that would be amenable to
access from a REST context (we're also Xamarin users so our target runtime
environment would be iOS), or whether (as I suspect) AzCopy is, in fact,
code which makes very highly optimized use of the existing REST calls.

Appreciatively,

- Gilles

**Comment by craxal** [comment]
AzCopy is a command-line application for performant data transfer to and from Azure Storage resources. It uses the REST API to accomplish it's work. AzCopy provides a simplification over the API that manages the all the bookkeeping, batching, chunking, etc. of large sizes or numbers of blobs/files.

The REST API would give you fine-grained control, but you'd have to all of that bookkeeping yourself. As you may be aware of, this isn't trivial. True story: for a while, Storage Explorer has used it's own implementation of data transfer, which is a significant piece of our codebase. We've been transitioning to using AzCopy, because that tool is developed by a dedicated team, therefore they've had more experience and resources to getting data transfer with Azure right. Leveraging their work will greatly simply ours.

That being said, I don't think they have an iOS version of AzCopy available. However, the [AzCopy source code](https://github.com/Azure/azure-storage-azcopy) is right here on GitHub, so you can either contribute an iOS version or leverage their design patterns in your work.
