### ISSUE TITLE
Opt-Out of detecting local changes!

### ISSUE THREAD

**Issue by kjackson1998** [microsoft/AzureStorageExplorer#1221]
**Storage Explorer Version**: Any
**Platform/OS**: Windows 10
**Architecture**: x64

**Bug description**
Modal dialogs that detect local changes are unwelcome and annoying in my usage pattern. It seems I cannot turn them off and it's unclear how/if to answer 'No, do nothing, with everything' and the dialog just keeps repeatedly popping up when I click X.

**Steps to Reproduce**
I leave Storage Explorer open for long periods of time (days) and frequently open text files to read them. It seems the temp files get deleted or modified or something with triggers very annoying popups in Storage Explorer.

**Expected Experience**
I want a way to completely turn these dialogs off, or a clear answer that is 'Do nothing with this file, and do nothing with all other detections.' Just leave me alone!

**Comment by yaohualibin** [comment]
Do you have plan for this feature?

**Comment by MRayermannMSFT** [comment]
@yaohualibin yes we have plans for this feature. We will be:
- adding a checkbox to the prompt dialog to always use your answer going forward for the file being asked about
- adding a global setting to disable the feature entirely
- not prompting you if the file is deleted

**Comment by MRayermannMSFT** [comment]
I've just merged those 3 things, so they'll definitely be in our 1.26 release which is currently targeting end of September. I'll leave this issue open a few more days incase y'all have any extra feedback for us to consider.
