### ISSUE TITLE
MD5 is missing from uploaded files

### ISSUE THREAD

**Issue by doronAtuar** [Microsoft/AzureStorageExplorer#1223]
**Storage Explorer Version**: 1.7.0
**Platform/OS**: macOS Mojave
**Architecture**: x64
**Regression From**: yes, 1.6.*

**Bug description**
MD5 is missing from uploaded files

**Steps to Reproduce**
1. upload a file
2. check the file's properties for md5

**Expected Experience**
md5 should be present

**Actual Experience**
md5 is missing

**Comment by MRayermannMSFT** [comment]
Hi @doronAtuar , quick clarification question. Are you uploading to a File share, an ADLS Gen2 Blob container, or a normal Blob container? For a normal Blob container, I cannot repro your issue. For a File Share and an ADLS Gen2 Blob container I can.

For File share, I don't think this is a regression, but I'm pretty sure we can add it.

For ADLS Gen2 Blob container, [it doesn't look that property currently exists for those blobs](https://docs.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/path/getproperties#response), so I don't think it is something we can support at the moment...

**Comment by doronAtuar** [comment]
> Hi @doronAtuar , quick clarification question. Are you uploading to a File share, an ADLS Gen2 Blob container, or a normal Blob container? For a normal Blob container, I cannot repro your issue. For a File Share and an ADLS Gen2 Blob container I can.
> 
> For File share, I don't think this is a regression, but I'm pretty sure we can add it.
> 
> For ADLS Gen2 Blob container, [it doesn't look that property currently exists for those blobs](https://docs.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/path/getproperties#response), so I don't think it is something we can support at the moment...

Hi @MRayermannMSFT 
I'm using a regular Blob container

Let me know how I can provide with more helpful data.
It reproduces everytime, let me know how I can provide more helpful data.
Maybe debug prints?

**Comment by doronAtuar** [comment]
I managed to narrow it down:
It reproduces only for large files
In my case > 500mb

**Comment by MRayermannMSFT** [comment]
Thanks for narrowing it down! Will look into seeing if I see that as well.

**Comment by MRayermannMSFT** [comment]
Hey @doronAtuar , I'm only repro'ing it with standard blob containers if I have AzCopy turned on. Do you also have it enabled?

**Comment by MRayermannMSFT** [comment]
AzCopy 10.0.9 has been inserted and the calculate MD5 flag is definitely being set now.

**Comment by plivius** [comment]
Hi @MRayermannMSFT , when can we expect a new SE release containing mentioned version of AzCopy >= 10.0.9?
Some of our clients (dependent on using SE with AzCopy) have reported the same issue under the same conditions, however for all file sizes (20Mb - 4Gb).

**Comment by MRayermannMSFT** [comment]
Hey @plivius , 1.8.0 was released last week. Included in it is AzCopy 10.1.0!
![image](https://user-images.githubusercontent.com/21112697/57392303-47ba1300-7175-11e9-98a3-2ecf351b73ac.png)
Taken from: https://docs.microsoft.com/en-us/azure/vs-azure-tools-storage-explorer-relnotes#version-180
