### ISSUE TITLE
Poor performance on Windows 10

### ISSUE THREAD

**Issue by alexmarshall132** [Microsoft/AzureStorageExplorer#1229]
With 10 storage accounts and 3 Cosmos DB instances in the Local & Attached section, it takes 25 seconds to load the application, 17 seconds just to load the storage types list, then a further 10 seconds to load the accounts underneath each storage type. This is extremely poor performance for a desktop app.

**Comment by MRayermannMSFT** [comment]
Hi @alexmarshall132 , the time it takes you to initially get to your resources is something we're working on for 1.8.0. We already have an issue open for it as well. Feel free to participate on that issue: #1016
