### ISSUE TITLE
The 'Canceled' activities shows when canceling the setting of Access Tier

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1230]
**Storage Explorer Version**:1.7.0_20190312.3
**Platform/OS**: _Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture**: _i86
**Regression From**: Not a regression

**Steps to Reproduce**
1. Right click one non-adls gen2 account -> Select 'Set Default Access Tier'.
2. Click 'Cancel/Close' on the dialog -> Check whether the canceled activities shows or not.

**Expected Experience**
No canceled activities shows.

**Actual Experience**
The canceled activities shows.
![image](https://user-images.githubusercontent.com/34729022/54263149-6319f080-452d-11e9-8d59-32b14778137a.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
