### ISSUE TITLE
Nothing happens when creating folder with a blank name

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1233]
**Storage Explorer Version**:1.7.0_20190313.2
**Platform/OS**: _Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture**: _i86
**Regression From**: Not a regression

**Steps to Reproduce**
1. Expand one normal account -> 'Blob Containers' node.
2. Open one blob container -> Click 'New Folder' -> Delete the default name then type  a blank name(Pressing space directly) -> 'OK'.
3. Check the result.

**Expected Experience**
The folder with a blank name can be created successfully.

**Actual Experience**
Nothing happens.

**More info**
1. This issue also reproduces when creating a directory with a blanks name.
2. Actually, we can rename on folder/directory with a blank name.
![image](https://user-images.githubusercontent.com/34729022/54338618-9a50d600-45ef-11e9-8f11-43f4966855dd.png)

**Comment by MRayermannMSFT** [comment]
Fix: don't let people create folder name with empty name.
