### ISSUE TITLE
Show an unmatched destination path when uploading files to one subfolder for ADLS Gen2 accounts

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1234]
**Storage Explorer Version**:1.7.0_20190313.2
**Platform/OS**: _Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture**: _i86
**Regression From**: Previous release 1.7.0

**Steps to Reproduce**
1. Expand one ADLS Gen2 account -> 'Blob Containers' node.
2. Open one blob container -> Create a new folder then go to it.
3. Click 'Upload Files...' -> Check the path of the 'Destination directory' on 'Upload Files' dialog.

**Expect Experience:**
There shows the path of subfolder.

**Actual Experience:**
There only shows the root path. 
![image](https://user-images.githubusercontent.com/34729022/54339434-0c2a1f00-45f2-11e9-9c2c-f8fb19139bf5.png)

**More info:**
This issue doesn't reproduce for normal blob containers and file shares.

**Comment by MRayermannMSFT** [comment]
Fix merged into master
