### ISSUE TITLE
The value of  'Dequeue Count' is different between the queue editor and View Message dialog

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#1235]
**Storage Explorer Version:** 1.7.0_20190313.3
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32
**commit:** 1eb29a98
**Regression From:** Not a regression

**Steps to Reproduce:**
1. Expand one storage account -> Queues -> Create a new queue then add one message.
2. Select 'View Message' and make sure prompt a dialog.
3. Check the value of 'Dequeue count' between the dialog and editor.

**Expected Experience:**
 The value of 'Dequeue Count' is same between the editor and View Message dialog.

**Actual Experience:**
The value of  'Dequeue Count' is different between the editor and View Message dialog.
![image](https://user-images.githubusercontent.com/41351993/54339814-ded08600-4670-11e9-9e9c-727bf504a14a.png)

**Comment by MRayermannMSFT** [comment]
Change table to be 0 only if the reason the table displays "" is b/c dequeue count is undefined and if the API says that undefined is the same as 0. Otherwise, revisit in future milestone.

**Comment by MRayermannMSFT** [comment]
Fix checked into master.

**Comment by MRayermannMSFT** [comment]
<img width="369" alt="image" src="https://user-images.githubusercontent.com/21112697/54785943-c6b6b480-4be4-11e9-905b-357b62d33101.png">
