### ISSUE TITLE
Show an extra tooltip for the inputted String value on 'Add Entity' dialog 

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1236]
**Storage Explorer Version**:1.7.0_20190313.2
**Platform/OS**: _Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture**: _i86
**Regression From**: Previous release 1.7.0

**Steps to Reproduce**
1. Expand any one account -> 'Tables' node.
2. Open one table then click 'Add' button on the toolbar.
3. On the 'Add Entity' dialog, Click 'Add Property' button -> Select **String** type then type a valid value.
4. Hover the mouse on the inputted value -> Check the result.

**Expect Experiment:**
No tooltip shows due to the added value is valid.

**Actual Experiment:**
There shows a tooltip even though the added value is valid.
![image](https://user-images.githubusercontent.com/34729022/54339805-18fb4280-45f3-11e9-9d58-9468f156b961.png)

**More info:**
This issue **only** reproduces for **String** type.

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
