### ISSUE TITLE
The dropdown list next to the 'name' property is empty on 'New Vertex' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1237]
**Storage Explorer Version**:1.7.0_20190313.2
**Platform/OS**: _Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture**: _i86
**Regression From**: Not a regression

**Steps to Reproduce**
1. Expand one Graph account -> 'Database' -> 'Graph'.
2. Open one graph then click 'New Vertex' button on the toolbar.
3. On the opened dialog, check the dropdown list next to 'name' property.

**Expect Experiment:**
The dropdown list is not empty.

**Actual Experiment:**
The dropdown list is empty.
![image](https://user-images.githubusercontent.com/34729022/54341029-05051000-45f6-11e9-8002-77a575b7984f.png)

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
