### ISSUE TITLE
ADLS Gen2 storage container error message

### ISSUE THREAD

**Issue by bc3tech** [Microsoft/AzureStorageExplorer#1240]
**Storage Explorer Version**: 1.7.0
**Platform/OS**: Windows 10
**Architecture**: x64

**Bug description**
When trying to browse to a container in an ADLS Gen2 Storage account, I get the following error:
~~~
The specified filesystem does not exist. RequestId:daac17ff-a01f-000a-7231-ddd6a2000000 Time:2019-03-18T02:23:22.8348017Z
~~~

I have 4 containers in the same account and this error occurs on them all.

**Steps to Reproduce**
1. Create a new Storage Account, enable ADLS Gen 2 storage
1. Create a container in the account
1. Try to browse to it in Storage Explorer

**Expected Experience**
The Azure Portal tells me I can _only_ browse ADLS Gen2 storage w/ Storage Explorer, so I'd expect it to work as it does w/ any other type of blog storage account.

**Actual Experience**
I can't view the blobs in the container and I get the above error message

**Comment by MRayermannMSFT** [comment]
Hi @bc3tech , I reached out to the backend team and they were able to explain why you're running into this. Basicially you made this Storage Account back when it was still possible to create a blob container in a HNS enabled account. Today though, using Blob APIs has been fully blocked for HNS enabled accounts, which means you can't access these containers. So you need to make a new HNS enabled Storage Account and use the ADLS Gen2 APIs to make containers (which Storage Explorer will do for you). If you still need to access the data in this Storage Account though, then let us know. The backend team can apparently help you migrate the data out.

**Comment by bc3tech** [comment]
geez this is the 2nd time i'll have had to re-create my storage while in this preview.... will it be the last?

**Comment by MRayermannMSFT** [comment]
Hopefully it is. Unfortunately I'm not on the back-end team so I can't confirm that for sure. I'll assume you're all good for now though, so I'm going to close this issue.
