### ISSUE TITLE
"Unable to retrieve child resources" when attach Cosmos DB in Japan East

### ISSUE THREAD

**Issue by bowen5** [microsoft/AzureStorageExplorer#1241]
**Storage Explorer Version**: 1.7.0
**Platform/OS**: Window 10
**Architecture**: x64
**Regression From**: Not sure, never created a Cosmos DB in Japan East before.

**Bug description**
When use Azure Storage Explorer to attach a Cosmos DB account with Table API created in Japan East, it failed with error "Unable to retrieve child resources" and "The requested action could not be completed.". I'm using the same Explorer application to connect to Cosmos DB account w/ Table API in East US, North Europe, West Europe, West US 2 and Southeast Asia, all works fine as expected.
Note that it only fails when attach it in "Local & Attached" section, but when load it from those Azure Subscriptions I owned, there is no issue.

**Steps to Reproduce**
Create a Cosmos DB account with Table API in Japan East and attach it.

**Expected Experience**
Should be able to connect and list tables inside.

**Actual Experience**
Failed with "Unable to retrieve child resources" and "The requested action could not be completed."

**Additional Context**
N/A

![image](https://user-images.githubusercontent.com/1721643/54511958-9f19df00-498d-11e9-8b06-530e956bc2c4.png)

![image](https://user-images.githubusercontent.com/1721643/54511936-86a9c480-498d-11e9-9bb3-7f1b748f711b.png)

**Comment by iRainbow5** [comment]
Is there any ETA about the bug fixing?

**Comment by ziyel** [comment]
@iRainbow5 Sorry for the late response.
I have reproduced the issue. Will let you know the ETA once I found the root cause.

**Comment by iRainbow5** [comment]
Any ETA?

**Comment by ziyel** [comment]
@iRainbow5 We will fix this in next release.

**Comment by iRainbow5** [comment]
Okay... Seems 1.9 is released, how about the fix?

**Comment by iRainbow5** [comment]
Ping...

**Comment by djlan** [comment]
Hi, Ziye is working on it, unfortunately he is OOF for family emergency. He will continue to look at it when back. Thank you!

**Comment by ziyel** [comment]
@iRainbow5 , sorry for the late response. We will try to fix this in 1.10.0.

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
