### ISSUE TITLE
An error occurs when trying to update the access tier for GPV2/Blob accounts

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1242]
**Storage Explorer Version:** 1.7.0_20190318.3
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Previous release 1.7.0

**Steps to Reproduce:**
1. Right click one GPV2/Blob account -> Select '**Set default Access Tier**' on the context menu.
2. Check the result.

**Expected Experience:**
The 'Update Access Tier' dialog shows well.

**Actual Experience:**
An error occurs.
![image](https://user-images.githubusercontent.com/34729022/54590045-707b2300-49e4-11e9-9d78-9521ce572289.png)

**More info:**
This issue also reproduces when updating the access tier for block blobs.

**Comment by MRayermannMSFT** [comment]
Fixed.
