### ISSUE TITLE
Nothing happens when dragging local files to ADLS Gen2 blob containers

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1243]
**Storage Explorer Version:** 1.7.0_20190318.3
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Previous release 1.7.0

**Steps to Reproduce:**
1. Expand one ADLS Gen2 account -> 'Blob Containers'.
2. Open one blob container -> Drag some local files to the opened blob containers.
3. Check the result.

**Expected Experience:**
These files can be uploaded successfully.

**Actual Experience:**
Nothing happens.

**More info:**
1. An error occurs when dragging files to one normal blob container with AzCopy **enabled**.
![image](https://user-images.githubusercontent.com/34729022/54590350-27779e80-49e5-11e9-9854-372fe3d9e032.png)
2. This issue doesn't reproduce when dragging files with AzCopy **disabled**.

**Comment by MRayermannMSFT** [comment]
Fix checked into master.
