### ISSUE TITLE
No 'X' button shows on system dialog 

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1246]
**Storage Explorer Version:** 1.7.0_20190319.1
**Platform/OS:** Linux Ubuntu 18.04
**Architecture:** x64
**Regression From:** Not a regression

**Steps to reproduce**:
1. Expand any one storage account -> Blob Containers.
2. Try to delete one blob container -> Check the Delete confirmation dialog.

**Expect Experience:**
There shows the 'X' button on this dialog.
![image](https://user-images.githubusercontent.com/34729022/54670934-0466f080-4ab2-11e9-9304-63d4df43ac21.png)

**Actual Experience:**
No 'X' button shows.
![image](https://user-images.githubusercontent.com/34729022/54670927-016c0000-4ab2-11e9-9513-6cb1b91b0f00.png)

**More info:**
1. This issue doesn't reproduce on Ubuntu 16.04/Windows/Mac
2. Also reproduces on other systems dialog like Detach/Acquire lease/Break lease/Restore Snapshot so on.

**Comment by MRayermannMSFT** [comment]
Can't force the OS to add X's to these dialogs. Won't fix.
