### ISSUE TITLE
Horizontal Scroll is missing in document editor

### ISSUE THREAD

**Issue by ntrpnr** [microsoft/AzureStorageExplorer#1248]
**Is your feature request related to a problem? Please describe.**
When editing documents with long strings, there is no horizontal scroll.

**Describe the solution you'd like**
I'd like a horizontal scrollbar that displays when the line is longer than the input container.

**Describe alternatives you've considered**
I can use my keyboard to navigate, but it's not that efficient.

**Additional context**
<img width="1123" alt="2019-03-20 13_13_26-ActingAdmin - Microsoft Visual Studio  (Administrator)" src="https://user-images.githubusercontent.com/7208470/54683578-41fb6600-4b12-11e9-8f07-4278c38bc75e.png">

**Comment by obiwanjacobi** [comment]
The horizontal scrollbar is also missing in (storage) Table View after you've entered a Query. When the result of the query is shown, the horizontal scrollbar and the count-summary is missing. Resize the (main) window and it reappears. Bloody annoying. [2c]

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
