### ISSUE TITLE
Copy&Paste seems not utilize the azcopy.

### ISSUE THREAD

**Issue by xiangwu-ms** [microsoft/AzureStorageExplorer#1249]
Leverage azcopy in copy&paste when the azcopy option is selected. Without azcopy, copy from storage account to another storage account is very slow.

**Comment by MRayermannMSFT** [comment]
Definitely in the plans to make this happen @xiangwu-ms !

**Comment by JasonYeMSFT** [comment]
We have done this for Blobs for our 1.11 release.
