### ISSUE TITLE
Copy failing in ASE but successful in AzCopy?

### ISSUE THREAD

**Issue by MCKLMT** [microsoft/AzureStorageExplorer#1250]
**Storage Explorer Version**: _1.7.0_
**Platform/OS**: _Windows 10_
**Architecture**: _x64_

**Bug description**
A file is not copied using Azure Storage Explorer using AzCopy. If I use the same command in the command prompt with AzCopy, the copy is successful.

The file path is "//10.147.28.15/projects/Libraries/TCS Business Unit Community/Sync Demo/Transit and O&C/4_Caltrain CBOSS_PE-2054-0003/01.05 Correspondence/01.05.01 Incoming - From Customer/EXT JPB - enterprise Interim Kickoff Meeting Minutes from Tuesday May 16 2017 .msg"

As you can see, there is a space just before the file extension. 
Could it be a cause?

Thanks

**Comment by MRayermannMSFT** [comment]
@MCKLMT , is the space supposed to be there?

**Comment by MCKLMT** [comment]
Yes it is. The space is present in the customer file path.

◾ Mickaël
________________________________
De : Matthew Rayermann <notifications@github.com>
Envoyé : Monday, March 25, 2019 6:46:44 PM
À : Microsoft/AzureStorageExplorer
Cc : Mickaël Mottet; Mention
Objet : Re: [Microsoft/AzureStorageExplorer] Copy failing in ASE but successful in AzCopy? (#1250)


@MCKLMT<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMCKLMT&data=02%7C01%7Cmimott%40microsoft.com%7C4b2d263c398c4b434f8c08d6b149d930%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636891328065800427&sdata=PGGw%2BmswFrBjN3rg0Fs73fepmt7%2FUne1lto74hR0BNU%3D&reserved=0> , is the space supposed to be there?

**Comment by MRayermannMSFT** [comment]
@MCKLMT , which AzCopy version did you verify against manually? Did you use the current GA'd one or the new, still in preview AzCopy v10?

**Comment by MRayermannMSFT** [comment]
@MCKLMT , we'll be releasing Storage Explorer 1.8.0 soon. This version will include the GA'd AzCopy v10. Please try your transfer again using 1.8.0 once it's released.
