### ISSUE TITLE
Create CosmosDB collection sharing database throughput

### ISSUE THREAD

**Issue by phatcher** [microsoft/AzureStorageExplorer#1251]
**Storage Explorer Version**:  1.7.0
**Platform/OS**:   Windows 10?
**Architecture**:  x64?
**Regression From**:  Unknown
**Bug description**
Can't create a collection without specifying a throughput, i.e. I want the collection to share the database throughput

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
