### ISSUE TITLE
An error occurs when executing the action 'Manage Access Policies...'

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1255]
**Storage Explorer Version**: 1.7.0/20190326.6
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04,18.04/ MacOS High Sierra
**Architecture**: ia32/x64
**Commit**: 1b38838b
**Regression From**: Previous release 1.7.0

#### Steps to Reproduce: ####
1. Expand one non adls gen2 account -> Blob Containers.
2. Right click one blob container then select 'Manage Access Policies...'.

#### Expected Experience: ####
The 'Manage Access Policies' dialog pops up.

#### Actual Experience: ####
An error occurs.
![image](https://user-images.githubusercontent.com/34729022/55063160-99c72f00-5034-11e9-84e9-4442191885dd.png)
#### More info: ####
This issue also reproduces for file shares/queues/tables.

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
