### ISSUE TITLE
The space between Permissions and Entity Restrictions is too narrow on SAS dialog for tables

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1256]
**Storage Explorer Version**: 1.7.0/20190326.6
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04,18.04/ MacOS High Sierra
**Architecture**: ia32/x64
**Commit**: 1b38838b
**Regression From**: Previous release 1.7.0

#### Steps to Reproduce: ####
1. Expand any one account -> Tables.
2. Right click one **table** then select 'Share Access Signature...'.
3. Check the opened SAS dialog.
#### Expected Experience: ####
The space between Permissions and Entity Restrictions shows well.
#### Actual Experience: ####
The space between Permissions and Entity Restrictions is too narrow on SAS dialog.
![image](https://user-images.githubusercontent.com/34729022/55064385-24a92900-5037-11e9-8985-7b74f59569f4.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into master. @v-xuanzh , please verify. Thanks.

**Comment by v-xuanzh** [comment]
This issue has been fixed on the latest master build. 😀
