### ISSUE TITLE
Expanding subscription nodes takes 1 full minute to populate

### ISSUE THREAD

**Issue by icnatejackson** [Microsoft/AzureStorageExplorer#1258]
**Storage Explorer Version**: 1.7.0
**Platform/OS**: Windows 10
**Architecture**: i86
**Regression From**: used to work on versions older than about 3-4 months ago

**Bug description**
When expanding the subscription node, Storage Explorer takes nearly a minute to expand the various nodes.  Doesn't matter which subscription. 

**Steps to Reproduce**
1. Open Storage Explorer
2. Sign into Azure, select any subscription
3. Click the subscription to see the storage accounts/cosmos db nodes
4. wait 1 minute before they expand

**Expected Experience**
I expect the nodes to expand and show the storage account list and cosmos db account lists within a few seconds.

**Actual Experience**
The app takes 1 minute to expand these.  

**Additional Context**
During this time, using the F12 debugger tools, you can see Storage Explorer making 3 sets of calls out to https://{name of one of my storage accounts}.dfs.core.windows.net/?resource=account&timeout=60, and each of those times out.

Oddly, the name of the storage account that it is timing out against(3 times) before showing the cosmos and storage accounts isn't even in the Azure subscription I've chosen.  It is one of my storage accounts, but it doesn't have to be in the subscription I'm drilling into.

I have already completely reset Storage Account and re-linked my azure login.  same results.

**Comment by MRayermannMSFT** [comment]
Hi @icnatejackson , this is something we're addressing in 1.8.0. Both polling the dfs URLs at a later point, and not trying to do things for Storage Accounts in the subscription you're looking at. You can track that work here: https://github.com/Microsoft/AzureStorageExplorer/issues/1016

Closing this as a duplicate.
