### ISSUE TITLE
Data Lake Storage Gen1 does not work

### ISSUE THREAD

**Issue by RiccardoTisseur** [microsoft/AzureStorageExplorer#1259]
Dear,
I'm starting to use Microsoft Azure Storage Explore 1.6.2 to connect to my company subscription. I can see and use all blob starage but for Data Lake storage it does't work. I can see Data Lake storage in the Explorer view, but I can't see the content.

Best,
Riccardo

**Comment by jinglouMSFT** [comment]
Could you please try this using the latest version, 1.7.0?  Let us know if it fixes the problem.  Thanks.

**Comment by jinglouMSFT** [comment]
The retirement of ADLS Gen1 is now less than three months away. As [previously announced](https://azure.microsoft.com/en-us/updates/action-required-switch-to-azure-data-lake-storage-gen2-by-29-february-2024/) the service will be retired on 29 February 2024. With this date now close approaching we are going to close this issue as "won't fix". Documentation on how to migrate your data to ADLS Gen2/blob storage can be found here: https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-migrate-gen1-to-gen2-azure-portal

If you have any non ADLS Gen1 feedback for Storage Explorer, please feel free to open a new issue: https://github.com/microsoft/AzureStorageExplorer/issues/new/choose

This issue will now no longer be monitored.
