### ISSUE TITLE
Application Identities showing as GUID

### ISSUE THREAD

**Issue by amattas** [Microsoft/AzureStorageExplorer#1260]
**Storage Explorer Version**: 1.7.0
**Platform/OS**: Mac and Windows
**Architecture**: x64
**Regression From**: no

**Bug description**
When using an App ID to control ACL's in storage explorer the name of the AppID doesn't show up, only the GUID does.

**Steps to Reproduce**
1. Open Storage Explorer
2. Add Application Identity and grant permissions

**Expected Experience**
It should show the name of the Application ID having permissions (This is how it works in the IAM blades of the portal)

**Actual Experience**
It shows a GUID

**Additional Context**
This makes it really difficult for administrators to quickly find and revoke access..

**Comment by MRayermannMSFT** [comment]
Hey @amattas, this is currently by design. We/the service team are looking to address this in the future/are aware of this feedback.
