### ISSUE TITLE
Storage Explorer version 1.6.2 and 1.7.0 on both Ubuntu 18.04 and 16.04  spins on "Adding new connection"

### ISSUE THREAD

**Issue by jpsebasti** [microsoft/AzureStorageExplorer#1261]
Deployed Ubuntu 18.04 and 16.04 VM images in Azure Compute
Have tried both Storage Explorer 1.7.0 and 1.6.2 on both VM deployments.
When I try to connect to Azure Storage using Connection String, it just spins with message "Adding new connection." 

I'm also getting this error if I try to click the Storage Accounts tree item on the left hand side of the screen in the tree view.

"Unable to retrieve child resources."   
Details:  Cannot read property 'connectionString' of undefined.  

I have seen multiple suggestions for both Windows and Linux to get rid of the above message by cleaning up the $HOME/.config/StorageExplorer directory on Linux and the AppData directory on Windows.  I've tried this cleanup multiple times on Linux but the results are still the same.

**Comment by aaronpowell** [comment]
I can confirm the same problem on Kubuntu 18.04.

**Comment by jinglouMSFT** [comment]
could you please take a look at the troubleshooting guide here:  https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&tabs=1804.  Make sure you have the correct dependencies installed and the workaround applied.

**Comment by jpsebasti** [comment]
I did look at the troubleshooting guide and did patch the Storage Explorer 1.7.0 since my installed dotnet is version 2.2.105.    
After patching SE 1.7, I'm seeing the same behavior.   Attempts to connect (I've tried via Connect string and SAS key.  In both instances, SE just hangs attempting to connect.

**Comment by MRayermannMSFT** [comment]
@jpsebasti , how are you remoted into your VM?

**Comment by jpsebasti** [comment]
I use ssh

________________________________

**Comment by craxal** [comment]
@jpsebasti I think what Matthew is asking is are you using a remote desktop application to connect to your VM? Storage Explore is a desktop application, not a command-line application...

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
