### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by thedavegray** [microsoft/AzureStorageExplorer#1262]
**Storage Explorer Version**: 1.7.0
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**: 1.6.* 

**Bug description**
 Cannot expand any storage accounts without getting the error shown in the subject line

**Steps to Reproduce**
1. Log into an account with fill read/list/delete access to a storage account.
1.  Click "Load more" on any storage accounts

**Expected Experience**
 I expect to view the blobs and files in the storage account

**Actual Experience**
As above 

**Additional Context**
![Image 050](https://user-images.githubusercontent.com/4395873/55173125-0ba59280-5173-11e9-808f-f74b560d1d64.png)
![Image 051](https://user-images.githubusercontent.com/4395873/55173132-0ea08300-5173-11e9-8636-ab8eb28332d1.png)
![Image 052](https://user-images.githubusercontent.com/4395873/55173139-12340a00-5173-11e9-8ab2-9b1e5d420ca5.png)

**Comment by craxal** [comment]
Do you have any custom connections (local and attached, or resources you've attached to via connection string or SAS URI)? If so, there's a posibility one got corrupted somewhere, which would block retrieving sources. We're working on a fix that prevents corrupted attachements from preventing subscription resources from working properly.

An easy way to check is to open the developer tools (hit F12), select the Application tab, expand Local Storage > file:// and look for StorageExplorer_CustomConnections_* keys. If anything in there is nonempty, you have a custom connection saved.

If you want to go further, you can debug the custom connection loading process:
1. Open the Sources tab in the developer tools.
2. Open CustomConnectionStore.js.
3. Drop a breakpoint on line 54:
   ```js
   return [2 /*return*/, { id: connectionNames_1[index], data: data }];
   ```
4. Reload Storage Explorer.

The breakpoint should pause the app soon after reloading. Step through each iteration and check the value for `data` each time. If you have a corrupted connection, the breakpoint will be hit fewer times than you have connections.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
