### ISSUE TITLE
Cannot create database and unable to receive child resources

### ISSUE THREAD

**Issue by danabdn** [Microsoft/AzureStorageExplorer#1265]
**Storage Explorer Version**: 1.7.0
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**: This problem relates to creation the of the Storage Emulator database (I have an new PC) which results in unable to retrieve child resources.  I have had it working in the past on another PC.

**Bug description**
The main bug is that I cannot use the storage emulator to create a new database i.e. AzureStorageEmulator.exe init

It fails to create a new database.

Even if I give a helping hand to the system and manually create the database, I then get the common "Unable to retrieve child resources message" from Azure Storage Explorer.

**Steps to Reproduce**
1. Launch storage emulator in cmd window
2. Type AzureStorageEmulator.exe init

**Expected Experience**
Database has been created successfully (or something similar)

**Actual Experience**
"Found SQL Instance (localdb)\MSSQLLocalDB.

> Creating database AzureStorageEmulatorDb57 on SQL instance '(localdb)\MSSQLLocalDB'.
> Cannot create database 'AzureStorageEmulatorDb57' : The database 'AzureStorageEmulatorDb57' does not exist. Supply a valid database name. To see available databases, use sys.databases..
> One or more initialization actions have failed. Resolve these errors before attempting to run the storage emulator again.
> Error: Cannot create database 'AzureStorageEmulatorDb57' : The database 'AzureStorageEmulatorDb57' does not exist. Supply a valid database name. To see available databases, use sys.databases.."

**Additional Context**
When examining the error logs, I found one line which may be of interest:

> 2019-04-01 10:21:22.09 spid51      CREATE FILE encountered operating system error 5(Access is denied.) while attempting to open or create the physical file 'C:\Users\danieAzureStorageEmulatorDb57.mdf'.

_**Notice how the username danie - shouldn't there be an additional slash here?
I.e. it's trying to create a file in a folder that doesn't exist / have permission to.**
Perhaps there is some logic which is resulting in a missing slash?_

If this persists for not only database creation but also for subsequent connections, then this could also explain the "Unable to receive child resources message".

I have also tried:
1. Deleting the local instance i.e. sqllocaldb stop/delete/start MSSQLLocalDB
2. Deleting the C:\Users\danie\AppData\Roaming\StorageExplorer folder

I launch the emulator before Azure Storage Emulator.  I have had it working before in the past.
But given the logs this would appear to be a bug.

Thanks,
Dan.

**Comment by seguler** [comment]
@danabdn - could you create this issue in the Storage .NET SDK repository ? https://github.com/azure/azure-storage-net 

Alternatively use https://github.com/azure/azurite - which is the next generation Storage emulator due to release soon replacing the Azure Storage Emulator.

**Comment by danabdn** [comment]
Hi @seguler, 

Subsequent to submitting the above, I did indeed (with Spidersense it seems) register the issue with the Azure Storage Net repository.  [Issue 871](https://github.com/Azure/azure-storage-net/issues/871)

I initially submitted to this repository because even when the database was manually created, the issue remains which is an issue which may be considered to be related as a relationship between user-application of the Azure Storage Explorer.  I.e. the emulator initialised (with help) and was seemingly running - therefore no longer an issue with the emulator.  I.e. Unable to retrieve child resources.

Thank you for your suggestion to Azurite.  How "soon" is soon?  Are we talking soon like tomorrow for the VS2019/.Net core 3 release?

Though the above issue would appear to be a simple fix.  It's just a missing forward slash.
Can you offer insight into where the settings for this lookup may exist? Can I edit the settings to accurately reflect the correct path to the database as a workaround in the short term?

Many thanks,
Dan.

**Comment by seguler** [comment]
Azurite is already publicly available and is being used by many. We will declare official support for it sometime around May (tentative). Based on your issue description however, I have a feeling Azurite could simply solve your issue.

**Comment by MRayermannMSFT** [comment]
Closing due to the bug being in the .NET Emulator. Unfortunately there isn't anything we can do to fix this bug on our end.
