### ISSUE TITLE
Allow to set an empty Expiry time on SAS/ACL dialog

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1269]
**Storage Explorer Version:** 1.7.0_20190401.1
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Previous release 1.7.0

**Steps to reproduce:**
1. Right click one account -> Select 'Get Shared Access Signature...'
2. Set an empty Expiry time on SAS dialog.

**Expect Experience:**
 A red border shows and the 'Create' button is disabled.

**Actual Experience:**
1. No error occurs and the 'Create' button is enabled.
2. Actually, the generated connection string cannot be attached.
![image](https://user-images.githubusercontent.com/34729022/55464949-04d2b180-55b1-11e9-8d4d-374ae63e503a.png)

**More info:**
This issue also reproduces on ACL dialog.
![image](https://user-images.githubusercontent.com/34729022/55465188-727edd80-55b1-11e9-850e-4a4d11d383d7.png)

**Comment by craxal** [comment]
This is a regression? I thought we always required at least an expiry time?

**Comment by craxal** [comment]
Probably related to fix for #764?

@MRayermannMSFT can you check this out?
