### ISSUE TITLE
Uploading with AzCopy never completes - shows 100% indefinitely

### ISSUE THREAD

**Issue by alvipeo** [microsoft/AzureStorageExplorer#1271]
1.7.0
Windows 10 x64

I just tried to upload 2Gb file (AzCopy) over LTE and the process stuck at 100%. The file is MP4.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.

**Comment by alvipeo** [comment]
Sorry, on vacation... still have LTE here but only Mac. Would it work with mac?

**Comment by MRayermannMSFT** [comment]
If you're on vacation then enjoy your vacation. 😋 When you get back, try again, and if you have issues, just open a new issue. Thanks!

**Comment by alvipeo** [comment]
It works on 1.9.0!
