### ISSUE TITLE
using SA 1.7.0 to try and download 165GB file

### ISSUE THREAD

**Issue by jpsebasti** [Microsoft/AzureStorageExplorer#1272]
Download is failing with these details:
{
  "message": "\"Download failed unexpectedly after 5 attempt\""
}

**Comment by jpsebasti** [comment]
Figured out the issue although the detailed error message was quite unhelpful. The drive I'm trying to download to was just added to the server and I needed to grant read/write permissions to the file.  I found this out by trying to download a small file using SE and immediately received an error message that I was not privileged.  When attempting to download the large 165GB file, it did not throw this error and instead seemed to work on it for a while before just reporting the failure message above.

**Comment by jpsebasti** [comment]
I was wrong, even opening up permissions failed to download the large 165GB file.  same error
{
  "message": "\"Download failed unexpectedly after 5 attempt\""
}

**Comment by jinglouMSFT** [comment]
Can you try to enable AzCopy and give it a try?  Files in this size, AzCopy usually does a better job.

**Comment by jpsebasti** [comment]
azcopy worked and I was successful at downloading the file.  Thanks
