### ISSUE TITLE
fail to upload large file(s)

### ISSUE THREAD

**Issue by mingl2000** [microsoft/AzureStorageExplorer#1275]
**Storage Explorer Version**: 1.7.0
**Platform/OS**: _Linux Ubuntu? macOS High Sierra? Windows 10?_
**Architecture**: x64
**Regression From**: NO

**Bug description**
It fails to upload large files such as 1GB or bigger consistently.

Once reach 100%, I would believe the upload is done, but it continues to increase the percentage uploaded, to even 150%. Strange.

**Steps to Reproduce**
1. Upload a large file such as 2GB to Azure blob container. It will fail. No file is uploaded.
   
**Expected Experience**
The large file should be uploaded.

Once the file size uploaded reach 100%, it should be uploaded.

In case of multiple files uploaded, it should display the percentage of upload of current file, once a file is uploaded, the explorer should update accordingly. so that user can upload again those failed ones...

**Actual Experience**
_A clear and concise description of what actually happens. If applicable, add screenshots to help explain what actually happened._

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by craxal** [comment]
- Are you using the integrated AzCopy to upload files?
- If you are using AzCopy, have you tried copying the command to the clipboard and runnin it from the command line manually?
- If you are not using AzCopy, have you tried turning it on to see if the transfer succeeds?
- Do you have unusal network configurations, such as a proxy?
- Does the transfer immediately fail, or does it take some time to fail?
- What error messages appear? Does anything show up in the dev window (F12) console?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
