### ISSUE TITLE
Pressing Shift+F6 doesn't focus on the previous panel if the current panel is Actions/Properties

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1277]
**Storage Explorer Version:** 1.7.0_20190408.2
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Press F6 twice to focus on the Actions/Properties panel.
2. Press Shift+F6 -> Check whether the previous panel - 'Explorer' is focused or not.

**Expect Experience:**
The previous panel is focused(The cursor in the Search box).
![image](https://user-images.githubusercontent.com/34729022/55783925-5ae99e00-5a64-11e9-80ba-6ca1f452d80c.png)

**Actual Experience:**
The cursor is still in Actions/Properties panel.
![image](https://user-images.githubusercontent.com/34729022/55783892-47d6ce00-5a64-11e9-81eb-4e2e21853b1d.png)

**Comment by MRayermannMSFT** [comment]
@v-xuanzh can you still repro this? I'm unable to in 1.9.0.

**Comment by v-xuanzh** [comment]
This issue doesn't reproduce on the latest master build 20190723.4. So closed it
