### ISSUE TITLE
 Misspell the word 'permanently' in delete blobs dialog 

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#1278]
**Storage Explorer Version:** 1.7.0_20190408.2
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** d69b9735
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand a non-ADLS Gen2 account -> Blob Containers(make sure the soft delete policy is disabled).
2. Create a blob container -> Upload a file then try to delete it.
3. Check the delete dialog.

**Expect Experience:**
The word 'permanently' spells correctly.

**Actual Experience:**
 Misspell the word 'permanently'.
![image](https://user-images.githubusercontent.com/41351993/55785357-de4ad400-5ae4-11e9-8fb7-c349570b85c8.png)

**Comment by jinglouMSFT** [comment]
PR submitted

**Comment by jinglouMSFT** [comment]
Merged.

**Comment by v-xianya** [comment]
Hi @jinglouMSFT, Verified this issue on the latest build [20190418.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2599525). This issue still reproduces.

**Comment by jinglouMSFT** [comment]
Please try with today's build. Craig just approved the new PR and should be in today's build.
