### ISSUE TITLE
Value of 'Timestamp' doesn't display when typing a large number into 'last number of Days'

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/AzureStorageExplorer#128]
**Storage Explorer Version**: 1.1.0 RC

**Platform**: Windows/Mac/Linux

**Architecture**: ia32

**Build Number**: 20180502.5

**Commit**: 48f8a5a0

**Regression From**: Not a regression

#### Steps to Reproduce: ####

1. Create a new table and add one entity at least.
2. Click 'Query' >add new clause > select 'Timestamp' for 'Field 'and 'Custom...' for 'Value'.
3. Type a large number into 'last number of Days' like 999999, then click 'OK' in 'Custom Timestamp Query' dialog.
4. Check whether the value can display or not.

#### Expected Experience: ####
The value of 'last number of Days' auto displays.

#### Actual Experience: ####
The value of 'last number of Days' doesn't display.
![actual](https://user-images.githubusercontent.com/34729092/39569507-ecf05bf2-4eb4-11e8-88ee-9705ae6c1a77.png)

More Info:
There is no tooltip if the value is very large.

**Comment by craxal** [comment]
Can you clarify what you mean by "doesn't display"? Do you mean that the length of the number extends beyond the bounds of the input box?

**Comment by v-dantch** [comment]
No, the 'doesn't display' in Step4 means the 'Value' doesn't display after clicking 'OK' in 'Custom Timestamp Query' dialog. Please get the details from below screenshot.
![not-display](https://user-images.githubusercontent.com/34729092/39614693-41443244-4f61-11e8-9974-394cd0b06cc1.PNG)

**Comment by craxal** [comment]
999999 is roughly 2700 years. I think that's long past the value a JavaScript Date object can represent, and I highly doubt users are going to enter ranges that large.

**Comment by v-dantch** [comment]
Ok, thanks for your update.
