### ISSUE TITLE
The 'Binary' type is enabled for user defined properties on query builder

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1282]
**Storage Explorer Version:** 1.7.0_20190409.1
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Open one table which contains some entities.
2. Open query builder -> Add a new clause, then select one user defined property under field column.
3. Check the dropdown list of Type for the added clause.

**Expect Experience:**
The 'Binary' type is disabled.

**Actual Experience:**
The 'Binary' type is enabled.
![image](https://user-images.githubusercontent.com/34729022/55848458-d6e5f380-5b01-11e9-9bc6-1d75d4ca2530.png)

**Comment by v-xianya** [comment]
@craxal 
Verified on build 20200324.12.
We can add one property with Binary type to an enitity for tables. So we close this issue.
Related bug: [554](https://github.com/microsoft/AzureStorageExplorer/issues/554)
