### ISSUE TITLE
Show an odd layout after updating the default user with an invalid and long UPN

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1283]
**Storage Explorer Version:** 1.7.0_20190409.1
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one ADLS Gen2 account -> Blob Containers.
2. Right click one blob container then select 'Mange Access...'.
3. Try to edit the default user with an invalid and long UPN like _**'unifiedsupportstatus_mhivestasoffshore.com#EXT#@microsoft.onmicrosoft.com**_

**Expect Experience:**
The layout shows well.

**Actual Experience:**
Show an odd layout.
![image](https://user-images.githubusercontent.com/34729022/55854377-53d09780-5b19-11e9-927c-613b415c2c03.png)

**Comment by MRayermannMSFT** [comment]
This was fixed in 1.8.0
