### ISSUE TITLE
Keep consistent between queue editor and View Message dialog

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#1285]
**Storage Explorer Version:** 1.7.0_201904010.5
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** 60ec9247
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand Queues -> Create a queue -> Add a message.
2. View the message.
3. Check the View Message dialog and queue editor.

**Expect Experience:**
The columns name of queue editor are consistent with view message dialog. 

**Actual Experience:**
It is not consistent between queue editor and view message dialog.
![image](https://user-images.githubusercontent.com/41351993/55948037-4125a200-5c82-11e9-8122-818aff6af75c.png)

**Comment by MRayermannMSFT** [comment]
Won't fix. In the dialog, we don't use title casing for input labels. For the table, we use title casing for column headers.
