### ISSUE TITLE
Delete a blob with all associated snapshots in one operation

### ISSUE THREAD

**Issue by tommye** [microsoft/AzureStorageExplorer#1286]
**Is your feature request related to a problem? Please describe.**
I often need to delete several blobs in one operation. If these blobs have associated snapshots, then I get an error message. I must manually delete these snapshots before I can delete the base blob.

**Describe the solution you'd like**
A solution like in the azure portal, where you can chose to delete associated snapshots or not.

**Comment by andre-ss6** [comment]
This is really fundamental. Deleting all snapshots for each file before being able to delete the files in a folder is not practical.

**Comment by MRayermannMSFT** [comment]
This is checked in for 1.13. If you try to delete a blob with snapshots, AzCopy will fail. In the retry dialog, there is now an option to "Delete blobs with snapshots" during the retry.
