### ISSUE TITLE
Disable the'Create Snapshot' when seelcting multiple blob files and folders at the same time

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1287]
**Storage Explorer Version:** 1.7.0_20190411.3
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Open one normal blob container which contains multiple blob files and folders.
2. Select one blob file and folder at the same time -> Check whether the 'Create Snapshot' is enabled or not on the toolbar/Context menu.

**Expect Experience:**
The 'Create Snapshot' is disabled.

**Actual Experience:**
The 'Create Snapshot' is enabled. 
![Untitled picture](https://user-images.githubusercontent.com/34729022/56016671-e5730d00-5cb1-11e9-9718-1c044d56ddc6.png)

**More info:**
Actually, The blob snapshot can be created successfully.

**Comment by JasonYeMSFT** [comment]
Have you verified this issue in 1.8.1? It seems like it has already been fixed.

**Comment by v-xianya** [comment]
Hi @JasonYeMSFT 
Verified this issue on the latest build 20190624.4. It still reproduces.

**Comment by v-xuanzh** [comment]
This issue has been fixed on the latest rel/1.9.0 build 20190626.4. So closed it.
