### ISSUE TITLE
Version 1.7.0 macOs Mojave - Cannot view or create new queues

### ISSUE THREAD

**Issue by sahgilbert** [microsoft/AzureStorageExplorer#1288]
**Storage Explorer Version**: 1.7.0
**Platform/OS**: macOs Mojave
**Architecture**: x64
**Regression From**: n/a

**Bug description**
Attempting to view or create a local queue shows the spinning icon, and nothing is created.

**Steps to Reproduce**
1. Open a fresh version of Azure Storage Explorer.
2. Connect to a fresh emulator.
3. Open the queue list to view available queues.
4. Note that the spinning icon appears and continues to spin.
5. Right-click, choose "create new queue".
6. Enter valid queue name, click create.
7. Nothing happens.

**Expected Experience**
A new queue is created locally for testing.

**Actual Experience**
A new queue is not created.

**Comment by jinglouMSFT** [comment]
What emulator do you use?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
