### ISSUE TITLE
'Sign in...' is enabled when using an empty environment name and valid ARM endpoint on 'Custom Environment' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1290]
**Storage Explorer Version:** 1.7.0_20190415.1
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Open 'Connect' dialog -> Select 'Use Custom Environment' on the dropdown list of azure environment -> 'Next'.
2. Ignore the Environment name field, then input a valid ARM endpoint like 'https://management.azure.com'.
3. Check the 'Sign in...' button is enabled or not.

**Expect Experience:**
'Sign in...' button is disabled due to the Environment name is required.

**Actual Experience:**
1. 'Sign in...' button is enabled.
![image](https://user-images.githubusercontent.com/34729022/56119540-35a3d680-5f21-11e9-800c-49da8c338f60.png)
2. Keep 'Starting sign in...' more than 10 minutes after clicking 'Sign in...' button.
![image](https://user-images.githubusercontent.com/34729022/56119545-389ec700-5f21-11e9-85e8-8f87c07aabdc.png)

**More info:**
Nothing happens after clicking 'Sign in...' button without any input on 'Custom Environment' dialog. 
![image](https://user-images.githubusercontent.com/34729022/56119832-ba8ef000-5f21-11e9-807f-a0ecfcd2b12f.png)

**Comment by v-xianya** [comment]
Verified this issue on the build 20190624.4. It has been fixed. So we close it.
