### ISSUE TITLE
errow while downloading with az copy

### ISSUE THREAD

**Issue by bkbartk** [Microsoft/AzureStorageExplorer#1291]
**Storage Explorer Version**: _In which Storage Explorer version was the bug encountered?_
1.7.0
**Platform/OS**: _Linux Ubuntu? macOS High Sierra? Windows 10?_
Windows 1o
**Architecture**: _i86? x64?_
x64
**Regression From**: _Was this working in a previous version? If so, which one?_
don't know

**Bug description**
I get this message while downloading a file
{
  "message": "\"AzCopy quit unexpectedly\""
}

**Steps to Reproduce**
Activate AZ copy
access a blob.
find an .exe file
right mouse click,
download
select path, ok

**Expected Experience**
file should be download

**Actual Experience**
and error occurs

**Additional Context**

**Comment by jinglouMSFT** [comment]
Is there anything specific about the .exe file you were trying to download?  I couldn't repro this from my end.

**Comment by bkbartk** [comment]
not that I know of,
I was logged in with my office365 AAD account which I also use to connect to azure,
and it was classic a classic storage account.
the file is called setup.exe
when I disable AZcopy everything works as aspected.
![image](https://user-images.githubusercontent.com/17070805/56188117-e9da5580-6024-11e9-91cb-ca615d93635b.png)
details give the error message shown above.

**Comment by jinglouMSFT** [comment]
We've recently integrated a new version of AzCopy. If you are willing to give it a try, we can arrange to give you a private build. Please let us know if you are interested.  Thanks.

**Comment by bkbartk** [comment]
I'm certainly willing to try,
and communicate the results back to you

**Comment by MRayermannMSFT** [comment]
Hey @bkbartk , here is the private build:
- macOS: https://storageexplorerpublish.blob.core.windows.net/privatebuilds/AzCopy-v10-0-9/StorageExplorer-darwin-x64.zip
- Windows https://storageexplorerpublish.blob.core.windows.net/privatebuilds/AzCopy-v10-0-9/StorageExplorer-ia32.exe
- Linux: https://storageexplorerpublish.blob.core.windows.net/privatebuilds/AzCopy-v10-0-9/StorageExplorer-linux-x64.tar.gz

Let us know if AzCopy works for you now. If not, we can take a look at your AzCopy logs to find out more.

**Comment by bkbartk** [comment]
Hello,
Thank you for this build,
I would like to let you know that now it  works as expected (for windows)
![image](https://user-images.githubusercontent.com/17070805/56342039-28077e80-61b7-11e9-9ef9-56dc2de09992.png)

**Comment by MRayermannMSFT** [comment]
Yay! Glad to hear it worked. If you have a future issue, feel free to open another issue. The bits I gave you will be released in an official build soon. Thanks for taking the time to try it!
