### ISSUE TITLE
Error: AzCopy quit unexpectedly when uploading to Emulator via Storage Explorer

### ISSUE THREAD

**Issue by kickinmhl** [microsoft/AzureStorageExplorer#1292]
Error message:
{
  "message": "\"AzCopy quit unexpectedly\""
}

**Storage Explorer Version**:  1.7
**Platform/OS**: Windows 10
**Architecture**:  x64
**Regression From**: First time this has happened.  Upgraded to this version just today.  HOWEVER, this version was working fine most of the day... then all of a sudden.... this.

**Bug description**
Attempt to upload files either by dropping or using the upload UI. It fails with above error

**Steps to Reproduce**
1. Upload file to blob storage 

**Expected Experience**
the usual... it uploads

**Actual Experience**
above error

**Additional Context**
1.) This has been working all morning... just now started getting this error.
2.) Yes I closed everything and re-stared my machine.  Same issue once I bring emulator back up.
3.)

**Comment by fernamp** [comment]
Same here.
Closing it and restart fixes it but it is just worth a single upload after that.

**Comment by tonytontian** [comment]
same here, restart does not fix the issue.

**Comment by MRayermannMSFT** [comment]
Which emulator are y'all using?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
