### ISSUE TITLE
No colons show next to properties in 'Connect to Cosmos DB' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1295]
**Storage Explorer Version:** 1.7.0_20190416.1
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** c684556c
**Regression From:** Not a regression

**Steps to reproduce:**
1. Create a cosmos db account with SQL API -> Right click it and select 'Copy Primary Connection String'.
2. Right click 'Cosmos DB Accounts(Preview)' ->Select 'Connect to Cosmos DB...' -> Paste the connection string -> Click 'Next'.
3. Check the properties in Summary description.

**Expect Experience:**
Display colons next to properties.

**Actual Experience:**
No colons show next to properties.
![image](https://user-images.githubusercontent.com/41351993/56196034-a73a6c80-6068-11e9-9ec0-66673fd6b877.png)

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
