### ISSUE TITLE
Able to attach one Graph account with SQL API on 'Connect to Commas DB' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1296]
**Storage Explorer Version:** 1.7.0_20190416.1
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** c684556c
**Regression From:** Not a regression

**Steps to reproduce:**
1. Create one graph account -> Copy the connection string of the created account.
2. Open 'Connect to Cosmos DB' dialog -> Paste the connection string with SQL API.
3. Check whether the account can be attached successfully or not.

**Expect Experience:**

There shows an error that indicates the select API is unmatched.

**Actual Experience:**

The graph account can be attached successfully.

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
