### ISSUE TITLE
StorageError-Blob type not supported

### ISSUE THREAD

**Issue by arunkumarms31** [microsoft/AzureStorageExplorer#1297]
**Storage Explorer Version**: 1.6.2
**Platform/OS**: Windows 10
**Architecture**: ia32
**Regression From**: Didn't try in other versions

**Bug description**
While trying to upload the generated certificate for that vhd i'm getting error like StorageError:Block blobs are not supported

**Steps to Reproduce**
1. Add the generated certificate using "Upload Files" option
2. After selecting the file chose Blob Type as "Block Blob"

**Expected Experience**
Expecting the certificate to get uploaded successfully 

**Actual Experience**
{
  "name": "StorageError",
  "message": "Block blobs are not supported.\nRequestId:b9ae2aaa-c01c-0094-4c95-f3fa54000000\nTime:2019-04-15T14:12:21.3579572Z",
  "stack": "StorageError: Block blobs are not supported.\nRequestId:b9ae2aaa-c01c-0094-4c95-f3fa54000000\nTime:2019-04-15T14:12:21.3579572Z\n    at Function.StorageServiceClient._normalizeError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:1198:23)\n    at Object.StorageServiceClient._processResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:744:50)\n    at Request.processResponseCallback [as _callback] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:317:37)\n    at Request.self.callback (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1157:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1079:12)",
  "code": "BlobTypeNotSupported",
  "statusCode": 400,
  "requestId": "b9ae2aaa-c01c-0094-4c95-f3fa54000000"
}

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by jinglouMSFT** [comment]
What kind of storage account were you trying to upload this to?

**Comment by arunkumarms31** [comment]
> What kind of storage account were you trying to upload this to?

My storage account is of "Classic" type

**Comment by MRayermannMSFT** [comment]
@arunkumarms31 can you click on the node for the Storage Account and double check the "Type"? Classic should support block blobs. So let us know what you have for "Type".

![image](https://user-images.githubusercontent.com/21112697/56916122-09ce3800-6a6d-11e9-86a3-2195ee774b31.png)

**Comment by arunkumarms31** [comment]
@MRayermannMSFT "Type - Microsoft.ClassicStorage/storageAccounts" this is my storage account type

**Comment by MRayermannMSFT** [comment]
Can you upload any other types of blobs? Such as page or append?

**Comment by arunkumarms31** [comment]
@MRayermannMSFT I tried with all other types of blobs but the result is same

**Comment by MRayermannMSFT** [comment]
Hmmm ok this is weird. Can you try some of the following:

- Try using a different account (preferably another classic account)
- Try uploading using the Azure Portal
- Try using AzCopy from the command line: https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#download-azcopy

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
