### ISSUE TITLE
Fail to attach accounts/services with SAS	

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1299]
**Storage Explorer Version:** 1.7.0_20190417.3
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Previous release 1.7.0

**Steps to reproduce:**
1. Right click one normal account -> Select 'Get Shared Access Signature...'
2. Set a specific expiry time and permissions on SAS dialog -> 'Create'.
3. Copy the generated SAS connection string -> Paste it to 'Attach with Connection String' dialog.
4. Check the result.

**Expect Experience:**
1. There is no error.
2. 'Next' button is enabled.

**Actual Experience:**
1. Cause an error 'missing required parameter 'se' or 'si' in SAS token.
![image](https://user-images.githubusercontent.com/34729022/56262970-ee8b2200-6095-11e9-8cec-9aedb62caee8.png)
2. 'Next' button is disabled.

**More info:**
1. This issue also reproduces when attaching services with SAS.
2. This issue doesn't reproduce when attaching resources with the set access policy.

**Comment by v-xuanzh** [comment]
Hi @craxal ,This issue has been fixed on latest master build 20190417.7. Could you help to resolve it?

**Comment by Pl4nky** [comment]
Has this issue resurfaced?  Using exact same steps by  @v-xuanzh in build 20190510.6 is resulting in the same error "missing required parameter 'se' or 'si' in SAS token"
