### ISSUE TITLE
Configurable Speed

### ISSUE THREAD

**Issue by JakeRadMSFT** [microsoft/AzureStorageExplorer#13]
Storage Explorer Version: 0.9.6

OS Version: Windows 10 (all)

Steps to Reproduce:

1. Upload several large files

Expected Experience:
The ability to throttle

Actual Experience:
Storage Explorer uses all of the systems available network resources (60+ MB/s).

**Comment by natelaff** [comment]
This also causes issues uploading a couple large files at once. They all slow each other down, as if competing for resources.

**Comment by jinglouMSFT** [comment]
This is already in Storage Explorer v1.11.0+.
