### ISSUE TITLE
Tabbing the group expander icon doesn't keep focus in Activities Panel when renaming a folder which contains multiple blobs

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#130]
**Storage Explorer Version**: 1.1.0 RC

**Platform**: Windows/Mac

**Architecture**: x64

**Build Number**: 20180502.5

**Commit**: 48f8a5a0

**Regression From**: Not a regression

#### Steps to Reproduce: ####

1. Launch Storage Explorer and expand storage accounts. 
2. Open one blob container and rename a folder which contains multiple blobs.
3. Focus on the group expander icon in Activities Panel using Tab.

#### Expected Experience: ####

The group expander icon keeps focus.

#### Actual Experience: ####

The group expander icon doesn't keep focus.

#### More info: ####
This issue also reproduces when uploading/downloading a directory which contains multiple files.

**Comment by v-xianya** [comment]
Verified this issue on the latest build 20190614.7. It doesn't reproduce. So we close it.
