### ISSUE TITLE
Unable to list resources in account.... Contact your subscription administrator

### ISSUE THREAD

**Issue by crissandraauree** [microsoft/AzureStorageExplorer#1301]
I have been working solo on a free trial account for a few months perfectly fine. I am running the desktop software on Macbook 10.13.16 High Sierra. 

Now I am receiving this error: 
Unable to list resources in account due to inadequate permissions. Permission to list containers or to list account keys is required. Contact your system administrator to resolve this issue. 

I've logged out at logged back in and updated the app. What else can I do to fix this?Screenshot attached for reference.

![Screen Shot 2019-04-16 at 6 13 07 PM](https://user-images.githubusercontent.com/49701865/56254024-e8844980-6073-11e9-89fa-185deb19a48a.png)

**Comment by MRayermannMSFT** [comment]
Hey @crissandraauree , how long ago did you make your trial account? According to what I can find they are only good for 12 months: https://azure.microsoft.com/en-us/free/

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
