### ISSUE TITLE
Update the dialog's title 'Connect to Cosmos DB' to 'Connect to Cosmos DB Emulator' 	

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1303]
**Storage Explorer Version:** 1.8.0_20190417.7
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Previous release 1.7.0

**Steps to reproduce:**
1. Right click 'Cosmos DB Account(Preview)' -> Select 'Connect to Cosmos DB Emulator...'.
2. Check the dialog's title.

**Expect Experience:**

The dialog's title shows '**Connect to Cosmos DB Emulator**'

**Actual Experience:**

The dialog shows '**Connect to Cosmos DB**'

**Comment by ziyel** [comment]
This is by design.
