### ISSUE TITLE
Uploading Millions of files hangs or says complete but 1,000's of files missing

### ISSUE THREAD

**Issue by chhamso** [microsoft/AzureStorageExplorer#1307]
**Storage Explorer Version**: 1.7.0
**Platform/OS**: Windows 7
**Architecture**: _i86? x64?_
**Regression From**: _Was this working in a previous version? If so, which one?_

**Bug description**
Uploading millions of files. ASE says complete and ~100,000 files are not uploaded. 3x tried.

**Steps to Reproduce**
1. _List the minimal steps required to reproduce the bug._
2. _Be as clear and concise as you can._

**Expected Experience**
_A clear and concise description of what you expected to happen. If applicable, add screenshots to help explain what you expected._

**Actual Experience**
As bug description. See screen shot
![MillionsOfFiles](https://user-images.githubusercontent.com/23435661/56376533-1d101680-61d6-11e9-80b2-219375c9577d.png)

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by craxal** [comment]
The Statisics feature can be innaccurate; we have plans to address that. Do you know for a fact some files are missing? If there are indeed files missing, have you tried turning on AzCopy?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
