### ISSUE TITLE
Deletions from ADLS shown as queued even after the operation is complete

### ISSUE THREAD

**Issue by fabio-muramatsu** [microsoft/AzureStorageExplorer#1308]
**Storage Explorer Version**: 1.7.0
**Platform/OS**: Windows 10
**Architecture**: i86

**Bug description**
Deletions from Azure Data Lake Store accounts remain in queued state in the Activities window even after they are finished. This causes these entries to be stuck in this window, since the "Clear Completed" and "Clear Successful" buttons don't remove them.

**Steps to Reproduce**
1. Delete a file from an Azure Data Lake Store account

**Expected Experience**
The delete activity shows up in the Activities window and is updated to a completed status after the deletion finishes.

**Actual Experience**
The delete activity remains in queued state even after the deletion finishes.

**Additional Context**
Here's a screenshot of my activities window after performing a few deletions. Note how the deletion is marked as successful in the group, but not for each individual stream.
![image](https://user-images.githubusercontent.com/14302074/56378539-327b4580-61c2-11e9-835f-890cb6796bfb.png)

**Comment by jinglouMSFT** [comment]
The retirement of ADLS Gen1 is now less than three months away. As [previously announced](https://azure.microsoft.com/en-us/updates/action-required-switch-to-azure-data-lake-storage-gen2-by-29-february-2024/) the service will be retired on 29 February 2024. With this date now close approaching we are going to close this issue as "won't fix". Documentation on how to migrate your data to ADLS Gen2/blob storage can be found here: https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-migrate-gen1-to-gen2-azure-portal

If you have any non ADLS Gen1 feedback for Storage Explorer, please feel free to open a new issue: https://github.com/microsoft/AzureStorageExplorer/issues/new/choose

This issue will now no longer be monitored.
