### ISSUE TITLE
Azure File Storage corrupts .bak in transit

### ISSUE THREAD

**Issue by elamje** [microsoft/AzureStorageExplorer#1309]
**Storage Explorer Version**: 
**Platform/OS**:  Windows 10?
**Architecture**: x64?
**Regression From**: N/A

**Bug description**
After a lot of debugging, I believe that Azure Storage - File Storage corrupts my .bak file in transit to my VM. Using the web app upload GUI and the Storage Desktop Application it seems .bak file is being corrupted in transit as it works locally. The closest lead that I found was that if ftp is set to transfer in ASCII mode rather than binary mode, the .bak file will get corrupted. I'm not sure what transfer protocol is used to get the file from Azure file storage to the Azure VM. 

**Steps to Reproduce**
1. Upload ~5GB .bak to Azure file storage (not blob)
2. Download onto VM instance with SQL installed
3. Restore using SSMS Restore Database
4. Select source file, and notice that SSMS doesn't find a backup db in the .bak file

**Expected Experience**
Once .bak is selected, it should load backup sets available to restore into the "Restore Plan" window.

**Actual Experience**
Source file selected does not yield any options in the Restore Plan window.

**Comment by MRayermannMSFT** [comment]
@elamje, couple of questions:

1. Are you uploading to a blob container or file share?
2. If a blob container, is it for a normal Storage Account or an ADLS Gen2 storage account?
3. Can you calculate the MD5 hash of the file prior to uploading? If so, then you can do that, and then compare it to the MD5 hash of the file once in Storage. That way we can see if it's getting corrupted on download or on upload.

**Comment by elamje** [comment]
1. File Share
3. I calculated the hash before and after upload and they are different. I don't know how to calculate the hash while it's sitting in storage, so I don't know if its getting corrupted in upload or download. The only way I can check the hash is to hash pre-upload, then download it, then recalc the hash. Any tips?

**Comment by MRayermannMSFT** [comment]
Hey @elamje, can you try using AzCopy? For File Shares, we currently don't support an integrated experience (calling AzCopy from Storage Explorer), but you could at least try it directly on the command line: https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#download-azcopy

If what it uploads has the same "wrong" hash, then I think we can conclude this is either a server error or an issue in the local MD5 calculation...

Thanks!

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
