### ISSUE TITLE
Add 'Restore Snapshot' for file snapshot context menu

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#131]
**Storage Explorer Version**: 1.1.0 RC

**Platform**: Windows/Linux/Mac

**Architecture**: x64

**Build Number**: 20180502.5

**Commit**: 48f8a5a0

**Regression From**:  Not a regression

#### Steps to Reproduce: ####

1. Launch Storage Explorer and expand storage accounts.
2. Open one file share and upload files to it.
3. Create a snapshot for the file share.
4. Delete one uploaded file in Current file share.
5. Go to its snapshot view and right click one file snapshot then check the context menu.

#### Expected Experience: ####

'Restore Snapshot' displays on the file snapshot context menu.

#### Actual Experience: ####

'Restore Snapshot' doesn't display on the file snapshot context menu.
![context menu](https://user-images.githubusercontent.com/34729022/39569541-08344310-4eb5-11e8-9ac3-b7c5ba7dd3e6.png)

**Comment by MRayermannMSFT** [comment]
Merged into master for 1.2.0
