### ISSUE TITLE
Blob Storage: When uploading a file without extension to a folder the name is not respected. 

### ISSUE THREAD

**Issue by rmbrunet** [microsoft/AzureStorageExplorer#1310]
**Storage Explorer Version**: 1.7.0
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**: ?

**Bug description**

When uploading a file without extension to a blob container virtual folder/directory the name of the file is not respected and the name of the folder is used instead. The result is the same if uploading by drag-and-drop or using the Upload File dialog. 

**Steps to Reproduce**
1. Create a file without extension
2. Create a folder in blob container
3. Drag or upload the file to the created folder

**Expected Experience**

The resulting blob should have the original name of the file.  

**Actual Experience**

The resulting blob has the name of the folder. The URL to the blob is missing the name of the file.

![image](https://user-images.githubusercontent.com/2124799/56462058-74ef7e80-638a-11e9-8405-7b095124d622.png)

**Comment by MRayermannMSFT** [comment]
@rmbrunet , do you have AzCopy enabled?

**Comment by rmbrunet** [comment]
Yes

**Comment by MRayermannMSFT** [comment]
@rmbrunet, can you try this in 1.8.1? There's a newer version of AzCopy in that version, where this issue may be fixed. Thanks!

**Comment by MRayermannMSFT** [comment]
I'm not seeing this repro in either 1.7.0 or 1.9.0, so closing with no repro. Please open a new issue against 1.9.0 if you see problems with that version. Thanks!
