### ISSUE TITLE
Show an odd layout on 'Manage Access' dialog when editing User with an invalid UPN/OID

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1311]
**Storage Explorer Version:** 1.8.0_20190419.9
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Previous release 1.7.0

**Steps to reproduce:**
1. Expand one ADLS Gen 2 account -> Blob Containers.
2. Right click one blob container then select 'Manage Access...'.
3. On the opened ACL dialog, try to edit the default user $superuser with an invalid UPN.
4. Check the layout of the error message.

**Expect Experience:**
The error message shows on the below of the inputting text box.

**Actual Experience:**
The shown layout is odd.
![image](https://user-images.githubusercontent.com/34729022/56495464-b37c5a80-64aa-11e9-8f80-1e7098aeb544.png)

**Comment by MRayermannMSFT** [comment]
Fix checked into rel branch. Will be available in next RC build.
