### ISSUE TITLE
There shows a large blank on SAS dialog of blobs

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1312]
**Storage Explorer Version:** 1.8.0_20190419.9
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Previous release 1.7.0

**Steps to reproduce:**
1. Expand one normal account -> Blob Containers.
2. Open one blob container which contains one blob at least.
3. Right click one blob file then select 'Get Shared Access Signature...'.
4. Check the 

**Expect Experience:**
There is no extra blank under the checkbox 'Generate container-level shared access signature URI'.

**Actual Experience:**
There shows a large blank under the checkbox 'Generate container-level shared access signature URI'.
![Untitled picture](https://user-images.githubusercontent.com/34729022/56495764-97c58400-64ab-11e9-9767-76248e5ce64f.png)

**Comment by craxal** [comment]
Won't fix. Superficial change to UI that doesn't affect accessibility or usability.
