### ISSUE TITLE
Storage Error : The specified blob or block content is invalid

### ISSUE THREAD

**Issue by RSquare101** [microsoft/AzureStorageExplorer#1313]
This is the error I get when I try to upload a folder with 8 files. Of the 8 files, largest 2 files do not get uploaded. I tried enabling and disabling AzCopy. Still does not work.

{
  "name": "StorageError",
  "message": "The specified blob or block content is invalid.\nRequestId:9e309e88-401e-0009-77f3-f81627000000\nTime:2019-04-22T10:07:35.4859039Z",
  "stack": "StorageError: The specified blob or block content is invalid.\nRequestId:9e309e88-401e-0009-77f3-f81627000000\nTime:2019-04-22T10:07:35.4859039Z\n    at Function.StorageServiceClient._normalizeError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:1198:23)\n    at Object.StorageServiceClient._processResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:744:50)\n    at Request.processResponseCallback [as _callback] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:317:37)\n    at Request.self.callback (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1157:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1079:12)",
  "code": "InvalidBlobOrBlock",
  "statusCode": 400,
  "requestId": "9e309e88-401e-0009-77f3-f81627000000"
}

**Comment by MRayermannMSFT** [comment]
@RSquare101 what type of Storage account are you using? Standard, Classic, Premium, Blob, etc?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
