### ISSUE TITLE
Disable the 'Create' button on SAS dialog when only the optional permissions are selected

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1315]
**Storage Explorer Version:** 1.8.0_20190422.2
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Bug Description:**
Actually, The 'Created' button is disabled when there is no permission selected on SAS dialog. And when we checked one or more optional permission options(No required permission is selected), The 'Create' button is enabled. But the generated the SAS URI is invalid.

**Steps to reproduce:**
1. Right click one blob container then select 'Get Shared Access Signature...'.
2. Unchecked the required permission 'List', then checked any other permissions.
3. Check whether the 'Create' button is enabled or not.

**Expect Experience:**
The 'Create' button is disabled due to the generated SAS URI is disabled.(Missed the required permission 'List').

**Actual Experience:**
1. The 'Create' button is enabled.
2. The generated SAS URI is disabled.
![image](https://user-images.githubusercontent.com/34729022/56557950-dc0b5f80-6551-11e9-96a4-5fd935141dd9.png)

**Comment by craxal** [comment]
@v-xuanzh The screenshot above is of the Connect dialog, not the SAS dialog.

**Comment by MRayermannMSFT** [comment]
I believe @v-xuanzh is mentioning that the "Connect" button is enabled. This is a bug, but it doesn't need to be fixed in 1.8.0. I'll be addressing in 1.9.0 as part of attach with RBAC.

**Comment by v-xuanzh** [comment]
Hi @craxal @MRayermannMSFT , In my view, I hope the 'Create' is disabled when the required permisson has not been checked on SAS dialog. 
![image](https://user-images.githubusercontent.com/34729022/56626385-4f66ad00-65f6-11e9-8ee0-83bbc8d1fcd3.png)
Actually, the 'Create' is enabled and the generated SAS URI is disabled(There exists a red border on the above screenshot). Do you think it's needed to block the users operation via disabling the 'Create' button on SAS dialog when the required permission is not selected?

**Comment by craxal** [comment]
@MRayermannMSFT The bug he's referring to is not about the Connect dialog. He's just showing that we don't let customers connect if a SAS is missing certain permissions.

@v-xuanzh I still don't know what you mean you say the "SAS URI is disabled". There is no URI in this panel yet.

No, we should not block customers when the "required" permissions aren't selected. Once again, there are no specific permissions required when creating a SAS for general use. You only need to specify at least one permission. While it's true Storage Explorer needs Read and List, we should not block customers from creating a perfectly valid SAS. For example, we create SAS with only the Read permission when copying blobs.

**Comment by jinglouMSFT** [comment]
@craxal Let me try to interpret the bug.  Basically what this is about is that we seemed to have a logic in place to check if the "list" permission is included in the SAS URI when one tries to use the SAS URI generated by ourselves (in the attach dialog, the first dialog shown above).  If we know we need the "list" permission, why don't we block the user in the "Get Shared Access Signature..." dialog from generating a SAS URI when/if the "list" permission is de-selected. I believe what Xuan was suggesting was that when/if the "list" permission is de-selected, we should disable the "Create" button.

**Comment by craxal** [comment]
@jinglouMSFT Yes, that is my understanding here, and I disagree that we should disable the Create button. People do not generate SAS just for Storage Explorer, so we shouldn't limit customers to generating SAS that meet Storage Explorer requirements. We already automatically select List and Read for new SAS in the dialog. If we do anything here, we could add a warning message or something.
