### ISSUE TITLE
ADFS Azure Stack storage account doesn't load resources/properties

### ISSUE THREAD

**Issue by xin42** [Microsoft/AzureStorageExplorer#1316]
Storage Explorer Version: 1.8.0
Platform/OS Version:win10 x64
Steps to Reproduce:
1.Install the 1.8.0 version Storage Explorer ,Import the certificate, Target the AZURE STACK.
2.Open it and log on the ADFS AAD account.
3.Randomly click one Storage account.
Expected Experience:
The corresponding blob container, table, queue, property display normally.
Actual Experience:
Nothing displays.
![Capture](https://user-images.githubusercontent.com/8746959/56558082-0c91de80-65d0-11e9-8cbb-2a78b4f96dc3.PNG)

**Comment by MRayermannMSFT** [comment]
Fix merged to rel branch
