### ISSUE TITLE
Show an incomplete contents on Rename dialog after zooming in

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1318]
**Storage Explorer Version:** 1.8.0_20190422.2
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Zoom in Storage Explorer once at least.
2. Expand one normal account -> Blob Containers.
3. Right click one blob container then select 'Rename...'.
4. Check all the contents on the Rename dialog.

**Expect Experience:**
Show all the contents with a scrollbar.

**Actual Experience:**
1. Show an incomplete contents.
2. No scrollbar shows.
![image](https://user-images.githubusercontent.com/34729022/56562200-c6039c00-655d-11e9-90bd-25e3e74e35ab.png)

**More info:**
1. This issue also reproduces on 'Rename File Share', 'Rename Table', 'Rename Directory', 'Rename File', 'Create New Virtual Directory', 'Connect VM' dialog.
2. This issue doesn't reproduce on 'Rename Blob Folder', 'Rename Blob' dialog.

**Comment by MRayermannMSFT** [comment]
Won't fix. Zooming sometimes requires resizing dialog.
