### ISSUE TITLE
Upload folder will display twice after refresh in the uploading process

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/AzureStorageExplorer#1319]
**Storage Explorer Version**: _In which Storage Explorer version was the bug encountered?_1.8.0
**Platform/OS**: _Linux Ubuntu? macOS High Sierra? Windows 10?_Windows
**Architecture**: _i86? x64?_x64
**Regression From**: _Was this working in a previous version? If so, which one?_haven't try

**Bug description**
Upload folder will display twice after refresh in the uploading process

**Steps to Reproduce**
1. Open one Data Lake Storage Gen1
2. Upload a folder, in the uploading process, click Refresh

**Expected Experience**
Only one folder or no folder is acceptable

**Actual Experience**
Two folder display, both acceptable
 
![image](https://user-images.githubusercontent.com/36756024/56563043-60ef8b00-65dd-11e9-9c26-d0f25e48494a.png)

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by MRayermannMSFT** [comment]
Won't fix.
