### ISSUE TITLE
An extra scrollbar displays in 'Add Entity' dialog when there are multiple properties

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#132]
**Storage Explorer Version**: 1.1.0 RC

**Platform**: Windows/Linux/Mac

**Architecture**:  x64

**Build Number**: 20180502.5

**Commit**: 48f8a5a0

**Regression From**:  1.0.0
#### Steps to Reproduce: ####

1. Launch Storage Explorer and expand storage accounts.
2. Open one table and add a entity with multiple properties.
3. Click 'Add' button on the toolbar and check the 'Add Entity' dialog.

#### Expected Experience: ####

No extra scrollbar displays.

#### Actual Experience: ####

An extra scrollbar displays.
![scrollbar](https://user-images.githubusercontent.com/34729022/39569221-155f6ee4-4eb4-11e8-9bf4-a17249eb630f.png)

**Comment by craxal** [comment]
Does the scrollbar obscure the last item if you scroll down all the way?

**Comment by v-xuanzh** [comment]
Hi Craig,
The last item isn't obscured after dragging down the scroll bar of the right side.

More info:
The bottom scroll bar will disappear after hovering the mouse to any of proerties type.

**Comment by craxal** [comment]
If it's not blocking accessibility, I don't see this as a big issue. We probably won't have time to look into this.
