### ISSUE TITLE
For gen2 storage account, open deleted folder will close the active window

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/AzureStorageExplorer#1320]
**Storage Explorer Version**: _In which Storage Explorer version was the bug encountered?_1.8.1
**Platform/OS**: _Linux Ubuntu? macOS High Sierra? Windows 10?_Windows
**Architecture**: _i86? x64?_x64
**Regression From**: _Was this working in a previous version? If so, which one?_

**Bug description**
For gen2 storage account, open deleted folder will close the active window

**Steps to Reproduce**
1. Open one container under ADLS Gen2 storage account
2. Upload one folder
3. Refresh as prompt
4. Delete the folder
5. Click No when prompt for refresh
6. Open the deleted folder

**Expected Experience**
The container should keep opening

**Actual Experience**
The container closed
![image](https://user-images.githubusercontent.com/36756024/56563675-df98f800-65de-11e9-9345-e19ac791e722.png)

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by v-xianya** [comment]
Verified this issue on build 20200924.2. Not reproduce.

**Comment by JasonYeMSFT** [comment]
This has been fixed in the latest build.
