### ISSUE TITLE
An odd layout shows when selecting an access policy with long id on SAS dialog

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1322]
**Storage Explorer Version:** 1.8.0_20190422.2
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one normal account -> Blob Containers.
2. Right click one blob container then select 'Manage Access...'.
3. Add an access policy with long id like 'ンライン ストレージなどのサービスが含まれるので、さらに快適にデバイスや アプリ'.
4. Right click the same blob container then select 'Get Shared Access Signature...'.
5. On the opened SAS dialog, select the added policy then check the layout.

**Expect Experience:**
The layout shows well.

**Actual Experience:**
Show an odd layout.
![image](https://user-images.githubusercontent.com/34729022/56571640-3a483a80-6572-11e9-8d0e-c5e181a46560.png)

**Comment by MRayermannMSFT** [comment]
Won't fix.
