### ISSUE TITLE
Warning massage may confuse users,should be more detailed and accurate,and it is best not to include codes.

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/AzureStorageExplorer#1323]
**Storage Explorer Version**: _In which Storage Explorer version was the bug encountered?_StorageExplorer-ia32
**Platform/OS**: _Linux Ubuntu? macOS High Sierra? Windows 10?_Windows 10
**Architecture**: _i86? x64?_
**Regression From**: _Was this working in a previous version? If so, which one?_

**Bug description**
Warning massage may confuse users,should be more detailed and accurate,and it is best not to include codes.

**Steps to Reproduce**
1. Click "New Document"
2.Fill in an existing ID and click save.

**Expected Experience**
Pop up a warning that the ID number already exists

**Actual Experience**
![image](https://user-images.githubusercontent.com/43333874/56571890-c4909e80-6572-11e9-9e7e-ef0f6f7dafcd.png)

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
