### ISSUE TITLE
Reopening ACL dialog doesn't save the added access policies using Azurite

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1325]
**Storage Explorer Version:** 1.8.0_20190422.2
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Install and run Azurite.
2. Attach one local emulator -> Create one blob container under the attached emulator 'local-1'.
3. Add access policies for the created blob container -> Save.
4. Re-open the 'Manage Access' dialog -> Check the access policies.

**Expected Experience:**
The added access policies show well after reopening the ACL dialog.

**Actual Experience:**
The added access policies disappear after reopening the ACL  dialog.

**More info:**
1. This issue doesn't reproduce for Azure Storage Emulator.
2. After step 3, Try to change the 'Public Access Level' for the same blob container, the activities cannot complete.
![image](https://user-images.githubusercontent.com/34729022/56576176-86987800-657c-11e9-8e1f-bfa3a686cc34.png)

**Comment by craxal** [comment]
Closing this issue as external. See Azure/Azurite#199 and Azure/Azurite#200.
