### ISSUE TITLE
Group subscriptions by directory (tenant)

### ISSUE THREAD

**Issue by thomaslevesque** [microsoft/AzureStorageExplorer#1326]
I have access to many Azure subscriptions in several Azure directories. It's sometimes difficult to find the one I'm looking for in a very long list.

**Describe the solution you'd like**
It would be much easier to navigate subscriptions in Storage Explorer if they were grouped by directory.

**Describe alternatives you've considered**
Alternatively, some kind of manual organization of subscriptions in folders would be nice.

**Comment by snapfisher** [comment]
Additionally, it would be great if we could hide subscriptions, similar to the way it works in the Azure portal

**Comment by craxal** [comment]
@snapfisher You can already hide subscriptions today. If you click the Manage Accounts button at the left, you can uncheck any subscriptions you don't want to see.
![image](https://user-images.githubusercontent.com/3473026/68037006-0ddd4b80-fc84-11e9-931a-53d67bf989fb.png)

**Comment by craxal** [comment]
@thomaslevesque What do you mean by "Azure directory"? Do you mean you'd like to group by tenant?

**Comment by thomaslevesque** [comment]
> @thomaslevesque What do you mean by "Azure directory"? Do you mean you'd like to group by tenant?

Yes ("directory" is the the Azure portal terminology)

**Comment by snapfisher** [comment]
I never realized that!  Thanks.  Please close this, then.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by LarsKemmann** [comment]
Well, please don't actually close this issue. We still need the directory name to show in the UI. :)

**Comment by craxal** [comment]
@LarsKemmann Don't worry, we aren't close this! 😄@snapfisher's issue was a separate one, and it's been mitigate. This feature request is still quite valid.

**Comment by MRayermannMSFT** [comment]
This is going to be addressed as part of #460!
