### ISSUE TITLE
Spelling 'Enocde' instead of Encode 

### ISSUE THREAD

**Issue by ToledoEM** [Microsoft/AzureStorageExplorer#1328]
**Storage Explorer Version**: 1.7.0/1.6.2 
**Platform/OS**: _Linux Ubuntu? macOS High Sierra

**Bug description**
Spelling mistake when a file name need to be encoded when is downloaded into a windows machine

![Capture_speeling](https://user-images.githubusercontent.com/8144940/56638673-b3c15500-6666-11e9-85d4-c1f326745564.PNG)

**Comment by MRayermannMSFT** [comment]
Thanks for reporting this. Splleing is hard. 😄
