### ISSUE TITLE
Miss colon next to 'Blob Type' on Upload dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1329]
**Storage Explorer Version:** 1.8.0_20190423.4
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** 2b9f35e1
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand a storage account -> Blob Containers -> Create a new blob container and upload a file.
2. Check the upload Files dialog.

**Expect Experience:**
Show colon next to 'Blob Type'.

**Actual Experience:**
No colon shows next to 'Blob Type'.
![image](https://user-images.githubusercontent.com/41351993/56645250-ea6f8d80-66af-11e9-9e9e-d7a61ada4f93.png)

**More Info:**
This issue also reproduces for file Share.
![image](https://user-images.githubusercontent.com/41351993/56645083-919ff500-66af-11e9-9c17-5d294229acf1.png)

**Comment by jinglouMSFT** [comment]
Fix in PR.

**Comment by jinglouMSFT** [comment]
The missing colon in the blob upload dialog only occurs when AzCopy is enabled.

**Comment by MRayermannMSFT** [comment]
Need to publish the package.

**Comment by MRayermannMSFT** [comment]
Ok, AzCopy package has been published, so fix will be available in the next build.
