### ISSUE TITLE
No tooltip shows for the 'Copy URL' button on file shares view

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1331]
**Storage Explorer Version:** 1.8.0_20190423.4
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** 2b9f35e1
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one account -> File Shares.
2. Open one file share -> Focus on the 'Copy URL' on the toolbar.
3. Check whether there is tooltip or not.

**Expect Experience:**
The 'Copy URL' shows the tooltip.

**Actual Experience:**
No tooltip shows for the 'Copy URL' button.

**More info:**
This issue doesn't reproduce on blob container view.

**Comment by JasonYeMSFT** [comment]
A fix has been merged.
