### ISSUE TITLE
[ADLSinASE][Linux]ASE block.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/AzureStorageExplorer#1334]
Build:
StorageExplorer-ia32.exe

1. Install ASE on Linux.
2. Start ASE 

Result:
     ASE has no response.
![image](https://user-images.githubusercontent.com/35950097/56648568-29084680-66b6-11e9-9c1f-d8ad7597a888.png)

**Comment by JasonYeMSFT** [comment]
What version of Storage Explorer are you using? What type of services are you trying to load? Is it just Quick Access or everything fail to load? Or do you mean the application freeze when you start up?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. @v-jiche , please open a new issue if you're still having linux issues.
