### ISSUE TITLE
Update the tooltip 'Execute Query(F5)' to 'Execute query(F5)'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1336]
**Storage Explorer Version:** 1.8.0_20190425.8
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture**: ia32/x64
**Commit:** f43a9ee4
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand a storage account -> Tables -> Create a new table.
2. Click 'Query' on the toolbar -> Hover the mouse on the Execute query button.
3. Check the tooltip.

**Expect Experience:**
Show 'Execute query(F5)'.

**Actual Experience:**
Show 'Execute Query(F5)'.
![image](https://user-images.githubusercontent.com/41351993/56789755-47488080-6835-11e9-8b0a-d22111b3c829.png)

**Comment by MRayermannMSFT** [comment]
Fix checked into master. Please verify that all tooltips on those buttons still works. The query builder has not yet been made localizable, so I started working on that by doing the button tooltips.
