### ISSUE TITLE
Unable to open table with Azurite

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1337]
**Storage Explorer Version:** 1.8.0_20190425.8
**Platform/OS:** Windows 10/macOS High Sierra/Ubuntu 18.04
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Make sure the Azurite is installed and started.
2. Attach to a local emulator -> Expand 'local-1(Key)' -> 'Tables' node.
3. Create a new table -> Try to open the created table.
4. Check the result.

**Expect Experience:**
The tabled can be opened successfully.

**Actual Experience:**
Fail to open the table with the below error.
![image](https://user-images.githubusercontent.com/34729022/56795853-2bf25c80-67c6-11e9-8c5b-e968571e3df8.png)

**More info:**
This issue doesn't reproduce with emulator.

**Comment by craxal** [comment]
@v-xuanzh Are you sure this is a Storage Explorer version? Sounds like it's just a problem with Azurite.

**Comment by v-xuanzh** [comment]
You are right. It is an Azurite issue because this issue doesn't reproduce using Emulator

**Comment by craxal** [comment]
Closing this bug as external then. Please open a bug with Azurite.
