### ISSUE TITLE
The message text shows as messy code after inputting a specific message with 'Encode message body in Base64' unchecked

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1338]
**Storage Explorer Version:** 1.8.0_20190425.8
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** f43a9ee4
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand a storage account -> Queues -> Create a new queue.
2. Select 'Add Message' -> Input a specific message like '123q' and uncheck 'Encode message body in Base64' -> Click 'OK'.
3. Select 'View Message' -> check the 'View Message' dialog. 

**Expect Experience:**
No messy code shows and indicate 'This message is stored with no encoding'.

**Actual Experience:**
Show messy code and still indicate 'This message is encoded in Base64'.
![image](https://user-images.githubusercontent.com/41351993/56795818-d3fa3b00-6843-11e9-8f85-4d4d150a3450.png)

**Comment by MRayermannMSFT** [comment]
Seems to only repro if the message starts with a number.

**Comment by MRayermannMSFT** [comment]
Putting feature request tag back on. Basicially, we use a regex to see if a string is a valid base 64 string. It's not impossible that a user would store a string in a queue message that is not supposed to be a base 64 string but looks like one to our regex. So, to "fix" this issue, we could add a option in the 'View Message' dialog to alternate between raw and base 64 decoded views. 

So, moving this to a later milestone.
