### ISSUE TITLE
Show an inconsistent error message when using an incomplete expiry time on SAS dialog

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1339]
**Storage Explorer Version:** 1.8.0_20190426.3
**Platform/OS:** Windows 10/macOS High Sierra/Ubuntu 18.04
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one normal account -> Blob Containers.
2. Right click one blob container then select 'Get Shared Access Signature...'.
3. Remove anyone filed of Expiry time on SAS dialog. 
4. Put the mouse on the invalid time -> Check the error message.

**Expect Experience:**
There shows 'An expiry time is required. The field is incomplete or has an invalid date'

**Actual Experience:**
Only show 'An expiry time is required'
![image](https://user-images.githubusercontent.com/34729022/56862305-70b0fb80-695e-11e9-8315-a1f2091fb06f.png)

**Comment by craxal** [comment]
Won't fix. The field requires a full date and time. If it's not typed in entirely, the value doesn't "submit" to our code. It's how Chromium date-time controls work. I wouldn't consider this an inconsistent error message.
