### ISSUE TITLE
There is no action to add the attached Cosmos DB account to Quick Access

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1340]
**Storage Explorer Version:** 1.8.0_20190426.3
**Platform/OS:** Windows 10/macOS High Sierra/Ubuntu 18.04
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Right click one Document account -> Select 'Copy Primary Connection String'.
2. Open the 'Connect to Cosmos DB' dialog -> Paste the connection string -> 'Connect'.
3. Go to '**Local & Attached'** -> '**Cosmos DB Account(Preview)**'.
4. Right click the attached account -> Check the context menu.

**Expect Experience:**

There has an action to add the attached Cosmos DB account to Quick Access.

**Actual Experience:**

There is no action to add the account to Quick Access.
![image](https://user-images.githubusercontent.com/34729022/56862481-47916a80-6960-11e9-9437-aaa01185e5e5.png)

**More info:**
Actually, We can add the original account to Quick Access.

**Comment by craxal** [comment]
I don't think we ever supported Quick Access for CosmosDB, did we?

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
