### ISSUE TITLE
Show an unmatched title for the 'Create Graph' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1341]
**Storage Explorer Version:** 1.8.0_20190426.3
**Platform/OS:** Windows 10/macOS High Sierra/Ubuntu 18.04
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Select a Graph account ->Right click it and create a new database.
2. Right click the new database and select 'Create Graph...'.
3. Check the prompt dialog.

**Expected Experience:**
Show a correct title for the dialog.

**Actual Experience:**
Show an unmatched title for the dialog.
![image](https://user-images.githubusercontent.com/41351993/56862795-55d39b00-69e1-11e9-9aa4-e786f3a17b0e.png)

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
