### ISSUE TITLE
The message 'Showing xx to xx of xx cached item' is truncated on Blob View

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1344]
**Storage Explorer Version:** 1.8.0_20190429.3
**Platform/OS:** Windows 10/macOS High Sierra/Ubuntu 18.04
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one ADLS Gen2 account(Or select one normal account with AzCopy enabled) -> Blob Containers.
2. Try to upload one blob to it.(Click 'Upload' button or drag some local files to it)
4. DO NOT refresh the view -> Check the message 'Showing xx to xx of xx cached item' on Blob View.

**Expect Experience:**
The message 'Showing xx to xx of xx cached item' shows well on Blob View.

**Actual Experience:**
The message 'Showing xx to xx of xx cached item' is truncated on Blob View.
![image](https://user-images.githubusercontent.com/34729022/56939405-f9de4480-6abc-11e9-9005-0b0679c450a9.png)

**Comment by v-limu** [comment]
This issue has been fixed on build [20190927.10](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3091851). So close it.
