### ISSUE TITLE
The specified blob or block content is invalid.

### ISSUE THREAD

**Issue by mntorque** [microsoft/AzureStorageExplorer#1345]
**Storage Explorer Version**: 1.70
**Platform/OS**:  Windows Server 2012
**Architecture**: x64
**Regression From**: First attempt via SE.  Attempted via web console, same result.

**Bug description**
Error when attempting to upload file via Storage Explorer. File is on a local storage system, accessed from UNC authenticated as local account.

**Steps to Reproduce**
1. Open storage explorer.  Sign into Azure.  
2.  Browse to target dir.  Upload file from local network path.

**Expected Experience**
Successful upload

**Actual Experience**
Prompted to overwrite file (file out there is partial, hence trying to upload via Storage Explorer vs QNAP application), selected overwrite.

Got error:

{
  "name": "StorageError",
  "message": "The specified blob or block content is invalid.\nRequestId:c6964f7e-401e-0106-1e70-ff41b0000000\nTime:2019-04-30T16:21:30.8111281Z",
  "stack": "StorageError: The specified blob or block content is invalid.\nRequestId:c6964f7e-401e-0106-1e70-ff41b0000000\nTime:2019-04-30T16:21:30.8111281Z\n    at Function.StorageServiceClient._normalizeError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:1198:23)\n    at Object.StorageServiceClient._processResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:744:50)\n    at Request.processResponseCallback [as _callback] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:317:37)\n    at Request.self.callback (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1157:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1079:12)",
  "code": "InvalidBlobOrBlock",
  "statusCode": 400,
  "requestId": "c6964f7e-401e-0106-1e70-ff41b0000000"
}

**Additional Context**
Storage v2
Standard
Hot

File is 667.5GB, .vbk 

I also deleted the file (enabling soft delete, 3 days).  Attempted again, same error.

**Comment by MRayermannMSFT** [comment]
Can you try using the preview AzCopy upload/download to upload your file?

**Comment by mntorque** [comment]
I have the command used (where it provides a link to copy the command), but I haven't figured out how to run it in powershell manually.
I did enable the AzCopy function in Storage Explorer, I would have thought it would have used that functionality.
(I also did not get a notification of your reply, sorry for the delay)

**Comment by mntorque** [comment]
this is the code I got: (sterilized) 
```
$env:AZCOPY_CRED_TYPE = "Anonymous";
./azcopy.exe copy "\\[resource]\Veeam\[folder]\[filename].vbk" "https://[storage].blob.core.windows.net/[top level folder]/veeam/Veeam/[longstring]" --overwrite=false --follow-symlinks --recursive --from-to=LocalBlob --blob-type=BlockBlob --put-md5;
$env:AZCOPY_CRED_TYPE = "";
```

Althought I'd like it to overwrite - as I've had an issue with a failed copy from another source creating a 0kb file that I have to delete first.

**Comment by MRayermannMSFT** [comment]
Hey @mntorque , you can download an exe from here: https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#download-azcopy

**Comment by MRayermannMSFT** [comment]
@mntorque are you still having issues? Please let us know.

**Comment by mntorque** [comment]
Eventually we got it to go successfully – but it was not reliable enough to keep using.

Thank you
