### ISSUE TITLE
Can't copy contents of a container to another container when using Emulator

### ISSUE THREAD

**Issue by alvipeo** [microsoft/AzureStorageExplorer#1346]
v 1.7.0, Windows 10 x64

I have a container on my Emulator locally that has files and folders. I select all of them and click Copy. Then I go to my Azure Storage Account, choose another container and click Paste. All I get is errors. This is with AzCopy and without it.

Haven't tried that when both containers are in Azure.

**Comment by MRayermannMSFT** [comment]
Hey @alvipeo, which emulator are you using? And you coping from Azure to the emulator, emulator to Azure, or emulator to emulator?

**Comment by alvipeo** [comment]
@MRayermannMSFT I tried to copy from emulator to Azure.

**Comment by MRayermannMSFT** [comment]
@alvipeo , which emulator are you using? Azurite or the Windows only emulator.

**Comment by alvipeo** [comment]
Azure Storage Emulator on Windows 10 x64

**Comment by JasonYeMSFT** [comment]
Hi @alvipeo ,

Neither AzCopy nor we support copying from local emulator to Azure since the platform cannot access the resource url at your localhost. A work around for this is to download your contents from the emulator and upload them to your target Azure container.

**Comment by alvipeo** [comment]
ok
