### ISSUE TITLE
MSDN subscription not attached. 

### ISSUE THREAD

**Issue by Jackjjyyli** [microsoft/AzureStorageExplorer#1347]
**Storage Explorer Version**: _In which Storage Explorer version was the bug encountered?_ 1.8.0
**Platform/OS**: _Linux Ubuntu? macOS High Sierra? Windows 10?_ Windows 10
**Architecture**: _i86? x64?_ x64
**Regression From**: _Was this working in a previous version? If so, which one?_

**Bug description**
_A clear and concise description of what the bug is._
Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: 53f3dc0a-512f-4399-817d-c4a55242d086, Error: {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"13.71.185.242","port":443}

**Steps to Reproduce**
1. _List the minimal steps required to reproduce the bug._ Get Subscriptions Failure Details
2. _Be as clear and concise as you can._ looking into my account, and click "More information"

**Expected Experience**
_A clear and concise description of what you expected to happen. If applicable, add screenshots to help explain what you expected._  Has MSDN subscription from guggenheimpartners.com

**Actual Experience**
_A clear and concise description of what actually happens. If applicable, add screenshots to help explain what actually happened._ looking into my account, and click "More information"

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._ behind company proxy.

**Comment by MRayermannMSFT** [comment]
@Jackjjyyli are you behind a proxy?

**Comment by Jackjjyyli** [comment]
Yes, how do I config that?

**Comment by MRayermannMSFT** [comment]
Edit -> Configure Proxy Settings. 

If after configuring your settings you are still running into issues, you can find more troubleshooting steps for proxy issues here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=1804#proxy-issues

If after that you still can't connect, please reach back out via this issue. Thanks!

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
