### ISSUE TITLE
Middle click closes the tab

### ISSUE THREAD

**Issue by juliusl** [microsoft/AzureStorageExplorer#1348]
**Is your feature request related to a problem? Please describe.**
When you middle click a tab in most things it will close the tab. It would be nice if storage explorer behaved the same.

**Describe the solution you'd like**
Mouse over tab. Middle Click. Tab is closed.

**Describe alternatives you've considered**
None

**Additional context**
Today middle click will "highlight" the tab. It's not clear what the highlight does.

**Comment by v-xuanzh** [comment]
This feature request has been implemented on the latest master build 20190715.7. So closed it.
