### ISSUE TITLE
ADLS Gen2 "Folder Statistics" in Azure Storage Explorer

### ISSUE THREAD

**Issue by JackyChiou** [microsoft/AzureStorageExplorer#1349]
**Is your feature request related to a problem? Please describe.**
**_Can't show "Folder Statistics" in Azure Storage Explorer_**

**Describe the solution you'd like**
**_ADLS Gen2 "Folder Statistics" in Azure Storage Explorer_**
![image](https://user-images.githubusercontent.com/5474418/57203453-c599e500-6fe2-11e9-902a-38675a2e4670.png)

**Describe alternatives you've considered**
**_Get "Folder Statistics" in ACL, PowerShell or API._**

**Additional context**

**Comment by MRayermannMSFT** [comment]
Duplicate of #964
