### ISSUE TITLE
Queue can't be cleared if all messages are dequeued

### ISSUE THREAD

**Issue by amithegde** [Microsoft/AzureStorageExplorer#135]
**Storage Explorer Version**: 1.0.0
**Platform**: Windows
**Architecture**: ia32
**Build Number**: 20180415.2
**Commit**: 5d603052

#### Steps to Reproduce: ####

1. Add some messages to a queue and dequeue them using another process.
2. Try to clear the queue

#### Expected Experience: ####
I should be able to clear the queue even if the messages are dequeued.

#### Actual Experience: ####
Clear button is disabled.

**Comment by craxal** [comment]
If the queue is already empty, why do you need to clear it?

**Comment by amithegde** [comment]
Queue is not empty, the messages are just dequeued. If the message did not get processed (say because of an exception) it will come back to the queue after the visibility timeout. Having a way to force clear the queue would help in such cases so that the queue listeners do not try to dequeue it again. This will be helpful when you are testing out some feature.

**Comment by MRayermannMSFT** [comment]
PR out for review

**Comment by xt0rted** [comment]
Is this the same thing as #82?

**Comment by MRayermannMSFT** [comment]
Merged into master. Will be shipped with 1.2.0.
