### ISSUE TITLE
Can't download files from ADL Gen2 Blob folder since updating to 1.8.0

### ISSUE THREAD

**Issue by davidc555** [microsoft/AzureStorageExplorer#1350]
**Storage Explorer Version**: 1.8.0
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**: Whatever was before 1.8.0

**Bug description**
I can no longer download files via the desktop version of Storage Explorer.  It still works via the Azure Portal / Data Lake storage explorer.   

**Steps to Reproduce**
I have some files stored in Data Lake Gen 2 blob storage.  
Navigate to the folder
Right click on file
Choose to download
Select folder on my computer to save the file.
It then reports that it has failed (see error details below).

**Expected Experience**
Download the file to my computer like it used to.

**Actual Experience**
Nothing downloads.

**Additional Context**
Logs:
2019/05/06 04:09:20 ERR: [P#0-T#0] DOWNLOADFAILED: https://ourhostname.dfs.core.windows.net/test/2019-05-06T01:19:47.6210193Z.json : 000 : File Creation Error The filename, directory name, or volume label syntax is incorrect.
   Dst: c:///Users/my.name/Desktop/Reading/2019-05-06T01:19:47.6210193Z.json
2019/05/06 04:09:20 ERR: [P#0-T#0] c:///Users/my.name/Desktop/Reading/2019-05-06T01:19:47.6210193Z.json: 0: Delete File Error -remove C:/Users/my.name/Desktop/Reading/2019-05-06T01:19:47.6210193Z.json: The filename, directory name, or volume label syntax is incorrect.. X-Ms-Request-Id:

2019/05/06 04:09:20 JobID=0007a369-8e3e-8e45-5717-c57f4a6c69e7, Part#=0, TransfersDone=1 of 1
2019/05/06 04:09:20 all parts of Job 0007a369-8e3e-8e45-5717-c57f4a6c69e7 successfully completed, cancelled or paused
2019/05/06 04:09:22 PERF: primary performance constraint is Unknown. States: R:  0, W:  0, F:  0, H:  0, B:  0, S:  0, P:  0, Q:  0, D:  0, T:  0

**Comment by MRayermannMSFT** [comment]
Hey @davidc555 , looks like there's an issue in AzCopy that needs to be addressed. I'll open a bug with them later today. For now, you should be able to download your file if you select both it and something else, and then download both.

**Comment by davidc555** [comment]
OK - thank you.  Glad to know it was not just PEBKAC. :)

**Comment by MRayermannMSFT** [comment]
Nope, not this time. :)

**Comment by MRayermannMSFT** [comment]
Hey @davidc555, we shipped 1.8.1 today and it contains a fix for this. I'm going to go ahead and close the issue. 😄

**Comment by Lharri11** [comment]
Hey there @MRayermannMSFT, this same issue is now occurring for me in version 1.11.1. All issues are identical to what was described by OP. I believe 1.11.1 was released on 12/5/2019 - is there any way you could open another bug for this? Thanks in advance!

**Comment by Kapster17** [comment]
Hey there ....I see the same issue with 1.11.2 (AzCopy ver 10.3.2)
DOWNLOADFAILED: 
 File Creation Error The filename, directory name, or volume label syntax is incorrect.
