### ISSUE TITLE
Cannot log in with Azure Credentials

### ISSUE THREAD

**Issue by rodneyjoyce** [Microsoft/AzureStorageExplorer#1351]
**Storage Explorer Version**: 1.7.0 (and also in 1.8.0)
**Platform/OS**:  Windows 10
**Architecture**:  x64
**Regression From**: Was working in 1.7.0 a few weeks ago.

**Bug description**
When I try to sign in I am redirected to my org login screen and then SE shows the error message:

{
  "message": "\"OK\""
}

I can use Name and Key to connect however I cannot seem to upload a file (may or may not be related).

**Comment by jinglouMSFT** [comment]
Could you try to follow the steps in the troubleshooting guide to see if the problem can be fixed?  The Troubleshooting guide is here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&tabs=1804.  Thanks.

**Comment by rodneyjoyce** [comment]
Ok, it would appear to be a proxy issue - I tried a different wifi and it works, however adding my corporate proxy does not fix it. So it can be closed for now.
