### ISSUE TITLE
Load More and Search From Here not working in 1.8.0

### ISSUE THREAD

**Issue by redewell** [microsoft/AzureStorageExplorer#1353]
**Storage Explorer Version**: 1.8.0
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**: 1.7.0

**Bug description**
Clicking "Load more" at the bottom of an incomplete list of resources (i.e., Cosmos DB or Storage accounts) will not expand the displayed list.
Using "Search From Here" to find a known resource that isn't displayed in an incomplete list results in an infinite spinner.

**Steps to Reproduce**
1. Locate a list of Cosmos DB or Storage accounts in a subscription where all entities are not displayed.
2. Click "Load more" to see more items.
3. In some cases, additional items will be displayed; but in most cases, no additional items will be displayed.
4. Use "Search From Here" on an incomplete list to find an account that isn't displayed.  A spinner will display until the search is cancelled.

**Expected Experience**
1. Clicking "Load more" should expand an incomplete list of resources.  Multiple clicks should continue to add items to the list until all items of that type are displayed.
2. Adding a partial resource name to the path presented in the search box when using "Search From Here" should list all resources that match the partial name, even if the resources aren't displayed in an incomplete list (i.e., a list with "Load more" at the bottom).

**Actual Experience**
Clicking "Load more" on an incomplete list of accounts, in most cases, does not expand the list with more items.  Using "Search From Here" to find an account not displayed in an incomplete list results in a spinner that only goes away when the search is cancelled.

**Additional Context**
Nothing special about the installation or system.  The above functionality has worked in all previous versions of Storage Explorer.

**Comment by markarnolditpro** [comment]
I have the same issue.  As this was reported by users, I verified my own access to storage accounts in 1.7, then performed the 1.8 update and have the problem.  It appears it's a case of `load more` not actually loading more, or not being able to display the additions.  

I deleted the `appdata\roaming\storageexplorer` and restarted 1.8 for grins but problem persists.

**Comment by markarnolditpro** [comment]
I ended up uninstalling 1.8 and reinstalling 1.7 from [here](https://github.com/microsoft/AzureStorageExplorer/releases/tag/V1.7.0) and the problem goes away.

**Comment by redewell** [comment]
@markarnolditpro  I attempted to roll back to 1.7 from another link, but it didn't do the job.  Your link worked; thanks for passing that along.

**Comment by Jerid421** [comment]
Agreed.  1.8 does not show all of my Data Lake Storage Gen 1 data lakes.  When you hit "Load more", it doesn't load anything in addition to what is currently visible.  I had to revert back to 1.7. 

The Search From Here functionality also fails to search for the value that you aren't able to find by using Load More.  Basically, my data lake is completely unavailable.
