### ISSUE TITLE
Support to refresh the opened Editor using Ctrl+R

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1356]
**Storage Explorer Version:** 1.8.0_20190507.2
**Platform/OS:** Windows 10/macOS High Sierra/Ubuntu 18.04
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand Cosmos DB account -> Database -> Collection -> Document.
2. On the opened document view, Try to use Ctrl+R to refresh the editor.

**Expect Experience:**

Pressing Ctrl+R refreshes the opened editor.

**Actual Experience:**

Nothing happens.

**Comment by MRayermannMSFT** [comment]
@djlan, you can work with @craxal to get the ctrl+r accelerator added to y'all's editors.

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
