### ISSUE TITLE
Fail to rename local (Emulator) blob container which contains multiple blobs

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1357]
**Storage Explorer Version:** 1.8.0_20190507.2
**Platform/OS:** Windows 10/macOS High Sierra/Ubuntu 18.04
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Make sure Storage Emulator is started.
2. Open 'Connect' dialog -> Attach to a local emulator.
3. Expand '**Local & Attached'** -> '**Storage Accounts**' -> '**local-1(Key)'** -> '**Blob Containers**'.
4. Create a new blob container then upload multiple files to it(Or upload a blob folder which contains multiple files)
5. After uploading successfully, Try to rename the blob container.

**Expect Experience:**

Succeed to rename the blob container without any error.

**Actual Experience:**

Fail to rename the blob container with the below error.
![image](https://user-images.githubusercontent.com/34729022/57364540-41f20c80-7138-11e9-8e97-091a9c7762e8.png)

**More info:**

This issue still reproduces when renaming a local table which contains multiple entities.
![image](https://user-images.githubusercontent.com/34729022/57364778-af9e3880-7138-11e9-93f5-166c9f9b5fc8.png)

**Comment by MRayermannMSFT** [comment]
@v-xuanzh , which emulator did you test against? Azurite or the legacy emulator.

**Comment by v-xuanzh** [comment]
Hi @MRayermannMSFT ,We used Storage Emulator version is 5.9.0.0

**Comment by MRayermannMSFT** [comment]
Ok, we're pretty sure this is an emulator issue. Closing.
