### ISSUE TITLE
Clicking 'Sign in' on the prompt doesn't do anything when using the direct link of resource without signing in 

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1358]
**Storage Explorer Version:** 1.8.0_20190507.2
**Platform/OS:** Windows 10/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Sign in with your account -> Right click one storage account -> Select 'Copy the Direct Link to Account'.
2. Remove the added account.
3. Paste the copied direct link to browser -> Try to use 'Open Microsoft Azure Storage Explorer' option to navigate the target account.
4. It shows a prompt on Storage Explorer -> Click 'Sign in' button.
![image](https://user-images.githubusercontent.com/34729022/57365741-81b9f380-713a-11e9-9cb1-86ba856ad70e.png)

**Expect Experience:**

The 'Connect' dialog opens after clicking the 'Sign in'.

**Actual Experience:**

Nothing happens.

**Comment by MRayermannMSFT** [comment]
Fix merged into master
