### ISSUE TITLE
Link "Load more" doesn´t work with the last release to the 1.8.0

### ISSUE THREAD

**Issue by pasStiga** [microsoft/AzureStorageExplorer#1359]
Storage Explorer Version: 1.8.0
Platform/OS Version: Windows 10
Architecture: ia32
Build: 20190501.8
Regression From: N/A

Steps to Reproduce:
Expand a classic storage account with 3 containers
Click load more.
Expected Experience:
More containers are loaded.

Actual Experience:
Message loading... is shown and any container appear

**Comment by MRayermannMSFT** [comment]
Hi @pasStiga , I'm a little confused. You say the account has 3 containers. Shouldn't there not be a load more? We initially retreive 25 containers when you expand "Blob Containers", so if there's only 3 we should get all at once.

**Comment by jccantre** [comment]
I'm having the same issue. "Load more" isn't working. CosmosDB spins forever without loading anything. And loading Blob from the Azure Portal also causes anything not listed in the first 4-5 items to never show up. I'm seeing this issue cause lag with Azure itself as well. The Blob interface in the portal starts acting strangely while Storage Explorer is doing this infinite load.

**Comment by MRayermannMSFT** [comment]
@jccantre are you saying that you're seeing issues in tools other than Storage Explorer?

**Comment by jccantre** [comment]
Yes. It seems to be affecting the Azure Portal itself. When Storage Explorer is doing the infinite load the Blob portal stops working.

**Comment by MRayermannMSFT** [comment]
Interesting. Are you also trying to load more blob containers from a classic storage account, or is it a standard storage account? If you're unsure then you can look in the properties panel after selecting your account:
![image](https://user-images.githubusercontent.com/21112697/57402631-9030fb00-718c-11e9-9401-3eb6148ccd3c.png)

**Comment by jccantre** [comment]
Microsoft.Storage/storageAccounts

**Comment by MRayermannMSFT** [comment]
This is very odd. Does your company have some sort of screen sharing software we could use with each other? I'd like to debug your machine, because so far we haven't been able to repro this at all. If you don't, then we could use TeamViewer....

I can also give you debugging instructions for you to try on your own:

0. Close and then reopen Storage Explorer
1. Open Dev Tools (F12, or help -> toggle developer tools)
2. Use ctrl+p to open CommonStorageManager.js
3. Go expand your blob containers node the first time
4. Go to line 165 and click on the line number, should see it turn blue:
![image](https://user-images.githubusercontent.com/21112697/57403375-6d9fe180-718e-11e9-836f-1697e5793a01.png)
5. Click load more
6. When the breakpoint is hit, hover over current token and let me know what it says
![image](https://user-images.githubusercontent.com/21112697/57403510-b6f03100-718e-11e9-855e-8a7b80334377.png)

**Comment by jccantre** [comment]
Unfortunately I'm working for a client and can't screen share. I've opened the dev tools and hit ctrl+p and do not see CommonStorageManager.js.

I have the following:
LocalStorageManager.js
BrowserStorageManager.js
SessionStorageManager.js

**Comment by MRayermannMSFT** [comment]
Ah ok, that's possible. Can you expand the Blob Containers node for the first time and then look for it? I have some containers in Quick Access, so for me the file is loaded on startup. And nbd about not being able to screenshare. I'll do my best to talk back and forth with you here. Very interested to figure out what's giving y'all issues.

**Comment by MRayermannMSFT** [comment]
If we need to go deeper, you can also set breakpoints in BlobService.js, at lines 68 and 71:
![image](https://user-images.githubusercontent.com/21112697/57405029-46e3aa00-7192-11e9-985b-82e4dd12e0a8.png)
You can set them after the initial expansion of Blob Containers, click Load More, and then we can see if either get hit? If neither ever get hit, then we're looking at a server issue maybe. For that we'll need to break out fiddler...

**Comment by jccantre** [comment]
I have containers in Quick Access as well and it doesn't pop up. When I open the resource group, Cosmos DB Accounts, ADLS Gen1, and Storage Accounts are already expanded and there's no CommonStorageManager.js that I can see.

**Comment by jccantre** [comment]
And the Cosmos DB load never stops spinning. 
![image](https://user-images.githubusercontent.com/45396261/57405374-46580d00-71ac-11e9-9208-89fc97a31c2f.png)

**Comment by MRayermannMSFT** [comment]
So you see blob containers in the tree but you don't see the file? Because it should definitely be there:
![image](https://user-images.githubusercontent.com/21112697/57405569-9ecee080-7193-11e9-8d9b-999c9b57ef10.png)
That's really strange, but ok, guess we'll go with Fiddler then. Here are the instructions for getting Fiddler setup (unfortunately they're really long, also it assumes you've installed [Fiddler](https://www.telerik.com/fiddler), so make sure you have that installed):
![image](https://user-images.githubusercontent.com/21112697/57405658-d9d11400-7193-11e9-857c-c7e05b67ad9d.png)

**Comment by jccantre** [comment]
Ok. Now I know why I'm not seeing that js file. I'm not having an issue with Blob Containers. I'm having an issue with Storage Accounts. That js file pops up when I click Blob Containers. My issue is loading Storage Accounts, i.e. the Blob resource not the containers in the resource.

**Comment by MRayermannMSFT** [comment]
Ok, I guess I'm back to being confused about which load more is failing. 
Is it for "Blob Containers":
![image](https://user-images.githubusercontent.com/21112697/57408042-7944d580-7199-11e9-86bd-139ca6a23e52.png)
Or is it for "Storage Accounts:"
![image](https://user-images.githubusercontent.com/21112697/57408098-9b3e5800-7199-11e9-9ab8-33280b99f046.png)

**Comment by jccantre** [comment]
Storage Accounts

**Comment by MRayermannMSFT** [comment]
Ok so if you could do the following:
1. Launch storage explorer
2. Get the debug tools to NodeQueryHandler.js (this one should definitely be there right at the beginning)
3. Expand your tree all the way up to before you expand "Storage Accounts"
4. Set a breakpoint on line 105
5. Expand "Storage Accounts"
6. When the break point is hit, hover over queryResult and let me know how many results there are, and if there's a continuationToken
![image](https://user-images.githubusercontent.com/21112697/57410692-5964e000-71a0-11e9-9ca2-305d8d82bb29.png)
7. Click "Load more", if the breakpoint is eventually hit, let me know what is inside of queryResult, if it never is, then we'll have to look somewhere else next

Also, do you know how many Storage Accounts are in this subscription?

**Comment by jccantre** [comment]
I can't get to the Storage Accounts expansion. It keeps hitting the break point after expanding the Resource.
continuationToken
:
"https://management.azure.com/subscriptions/1824bc1e-b99a-4dab-9a84-b0d5f05f83c7/resources?api-version=2014-04-01&%24filter=substringof(%27%27%2cname)+and+(resourceType+eq+%27Microsoft.DocumentDb%2fdatabaseAccounts%27)&%24skiptoken=eyJuZXh0UGFydGl0aW9uS2V5IjoiMSE4IU0wUTNOamstIiwibmV4dFJvd0tleSI6IjEhMjI0IU1UZ3lORUpETVVWQ09UbEJORVJCUWpsQk9EUkNNRVExUmpBMVJqZ3pRemRmUjFKTUxVRmFWVG95UkVWVlV6STZNa1JFUlZZNk1rUlNSem95UkVsT1IwVlRWRkpGVkVGSlRFeEpUa3RFVnpveVJFVlZReTFOU1VOU1QxTlBSbFE2TWtWWFJVSTZNa1pUUlZKV1JWSkdRVkpOVXpveVJrRmFWVG95UkVWVlV6STZNa1JFUlZZNk1rUkJVMUE2TWtSSlVreEZWVU5EVDA1V1JWSlRTVTlPTFVWQlUxUlZVekktIn0%3d"

**Comment by MRayermannMSFT** [comment]
Ok. I have a path I think I can investigate. Will work on this diligently. This seems like an urgent issue. Thank your for your patience today.

**Comment by jcantrell1** [comment]
Thank you!

**Comment by MRayermannMSFT** [comment]
Ok, I have something I'd like you to try.

1. Close Storage Explorer
2. Open a text editor as admin (if you use VS Code, you can open it normally)
3. Open "C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\CloudHub\js\Providers\Azure\Producers\AzureResourceTypeProducer.js" (path may differ depending on your install location)
4. On line 52, make it look like this (at the end, `continuationToken`):
5. <img width="1240" alt="image" src="https://user-images.githubusercontent.com/21112697/57462063-038a4980-722d-11e9-9498-30cd263ab77b.png">
6. Save
7. Reopen Storage Explorer and try to repro the issue

**Comment by MRayermannMSFT** [comment]
Also, @pasStiga, please reply to my questions when you can. I don't think you have the same issue as jcantrell, but we didn't make any changes at that level of "loading", only at the level where jcantrell is seeing issues.

**Comment by jcantrell1** [comment]
Here's the code after the change above:
queryBindingManager.addProducerBinding(AzureResourceTypeProducer.getResourcesByTypeNamespace, function (args) { return _this.getResourcesByType(args,continuationToken); });

And it caused Storage Explorer to not load anything:
![image](https://user-images.githubusercontent.com/43820095/57464320-7d7cfb80-724a-11e9-9a2e-943f733b85e8.png)

**Comment by MRayermannMSFT** [comment]
The line should be: 
`queryBindingManager.addProducerBinding(AzureResourceTypeProducer.getResourcesByTypeNamespace, function (args, continuationToken) { return _this.getResourcesByType(args,continuationToken); });`

**Comment by jcantrell1** [comment]
That fixed it!

**Comment by pasStiga** [comment]
Hi @MRayermannMSFT , sorry for the delay. I can try the same that @jcantrell1 but I dont know if it is the same issue

**Comment by garygsscott** [comment]
I have the same issue.   It was working fine in 1.7.0.   Will try the steps above and let see if it resolves.

**Comment by MRayermannMSFT** [comment]
Yes, please let us know ASAP. The plan is to ship 1.8.1 today, with the fix for this included. So if y'all are having a different problem, it'd be great to know before shipping! Thanks. 😊

**Comment by garygsscott** [comment]
I have tried the same as @jcantrell1 and can confirm it fixes the issue for me also so we should be good to go when v1.8.1 is made available.   Thanks for your help,

**Comment by garygsscott** [comment]
I have just downloaded v1.8.1 from chocolatey and can confirm that issue is definitely fixed for me now in that version.   Many thanks for your help on this.

**Comment by MRayermannMSFT** [comment]
Wohoo good stuff! I'll assume paastiga was under the same umbrella issue wise. Closing this issue.

**Comment by pasStiga** [comment]
Hi,
It was fixed with the new release.
Thanks!
