### ISSUE TITLE
can not update or refresh  other storages

### ISSUE THREAD

**Issue by crisar19** [microsoft/AzureStorageExplorer#1360]
**Storage Explorer Version**: _In which Storage Explorer version was the bug encountered?_ 1.8.0
**Platform/OS**: _Linux Ubuntu? macOS High Sierra? Windows 10?_ Windows 10
**Architecture**: _i86? x64?_
**Regression From**: _Was this working in a previous version? If so, which one?_Yes

**Bug description**
_A clear and concise description of what the bug is._ in the previous version i was able to refresh others storages, but now it's not working. Please solve it

**Steps to Reproduce**
1. _List the minimal steps required to reproduce the bug._
2. _Be as clear and concise as you can._

**Expected Experience**
_A clear and concise description of what you expected to happen. If applicable, add screenshots to help explain what you expected._

**Actual Experience**
_A clear and concise description of what actually happens. If applicable, add screenshots to help explain what actually happened._

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by MRayermannMSFT** [comment]
Hi @crisar19, can you give us some more information as to the issue you're facing? I'm not sure what you mean by "in the previous version i was able to refresh others storages, but now it's not working"

**Comment by crisar19** [comment]
Hi, sorry for answer late. Now the problem is fixed.
My problem was that, on the previous version (1.7.0), below data lake accounts and blob storage accounts you have the option "load more" if you need to see more containers that you see by default. When you click on that option , storage explorer add other data lake or blob storage accounts that you already have. 
When I updated it (version 1.8.0) I couldn't refresh other data lake or blob storage accounts, but now, with the new update (version 1.8.1) I can do it.

**Comment by MRayermannMSFT** [comment]
So you're all good then? No more problems? 😄

**Comment by MRayermannMSFT** [comment]
Pretty sure @crisar19 is unblocked, so closing...
