### ISSUE TITLE
AZCopy Preview Functionality - OverWrite Prompt Before Failure

### ISSUE THREAD

**Issue by aarondglover** [microsoft/AzureStorageExplorer#1361]
The current behaviour when using AZCopy to copy blobs is for the transfer to FAIL if there is an existing file.

Would it be possible to throw the "overwrite dialog box" prior or during the file copy as it currently does when NOT using the AZCopy option.

At the moment it fails and I have to look at the Activities tray and select "Retry" at which point I have the option to overwrite.

Alternatively or perhaps in addition, it would be good to be able to define a global overwrite behaviour in the application. Allow me to set to "Prompt", "Overwrite", "Do Not Copy" or something similar.

**Comment by jinglouMSFT** [comment]
Thank you for the feedback. We are currently working with the AzCopy team to provide the overwrite option. Once we have it, we will integrate it into Storage Explorer.  Hopefully sometime in the summer we will provide that functionality.  Thanks again for the input.

**Comment by BulldogCTISolutions** [comment]
+10
If I can "undo" the AzCopy Preview, would I get the option to overwrite back?

**Comment by MRayermannMSFT** [comment]
Yes, you can undo enabling it by going to the preview menu and clicking on the azcopy option.
