### ISSUE TITLE
Need to update the version to 1.8.1 on Release Notes

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1363]
**Storage Explorer Version:** 1.8.1_20190510.3
**Platform/OS:** Windows 10/macOS High Sierra/Ubuntu 18.04
**Architecture**: ia32/x64
**Regression From**: Previous release

**Steps to reproduce:**
1. Open Release Notes.
2. Check the shown version.

**Expect Experience:**

It shows 1.8.1

**Actual Experience:**

It still shows 1.8.0
![image](https://user-images.githubusercontent.com/34729022/57519001-39800a00-72cf-11e9-99f9-9acbe1c278cb.png)

**Comment by MRayermannMSFT** [comment]
Fixed.
