### ISSUE TITLE
Unable to get the latest release(1.8.0) from an old version

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1364]
**Storage Explorer Version:** 1.7.0_20190305.10
**Platform/OS:** Windows 10/macOS High Sierra/Ubuntu 18.04
**Architecture**: ia32/x64
**Regression From**: Previous release

**Steps to reproduce:**
1. Install the Storage Explorer with 1.7.0 release build(2.1903.5.10).
2. Go to 'Help' -> 'Check for updates'.

**Expect Experience:**

There shows a notification that 'The 1.8.0 is available'.

**Actual Experience:**

There is no update available.
![image](https://user-images.githubusercontent.com/34729022/57522567-ae574200-72d7-11e9-98a4-2b4819c4addf.png)

**Comment by MRayermannMSFT** [comment]
By design. The update notification was turned off
