### ISSUE TITLE
Change Blob store mid action, force quit, upgrade fail

### ISSUE THREAD

**Issue by OzBob** [microsoft/AzureStorageExplorer#1366]
**Storage Explorer Version**: StorageExplore.exe fileverstion 60863.2.0.0
**Platform/OS**: Windows 10 (1903)
**Architecture**: x64
**Regression From**: unknown

**Bug description**
Open ASE and now it gives node error
![image](https://user-images.githubusercontent.com/1796771/57671562-e8617480-7646-11e9-8018-caa885e5be42.png)

**Steps to Reproduce**
I'm sorry but this is a multi step saga:

1. AzureStorageExplorer is usually awesome!!!
2. but not this once:
3. Deleting 100s of blobs
4. Then click out on to another blobstore
5. ASE hung, and not responsive for 20min
6. So Force close using task manager
7. Re-open
8. Click the 'install' button to install the latest version
9. but there are leftover services still open that prevent upgrade
10. The installation step 'close/force close' open services, did not work.
11. The Retry/Abort screen pops up
12. Click Abort
13. Rollback installation completed
14. Open ASE and now it gives node error.

**Expected Experience**
1 multi delete blob should not hang 
2 abort on fail to close services should not ruin the previous installation

**Actual Experience**
can't open ASE

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by MRayermannMSFT** [comment]
@OzBob, are you still blocked? Could you try:

1. Restart your computer
2. Download the latest installer from storageexplorer.com
3. Run that installer
4. After installation is complete, try launching Storage Explorer

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
