### ISSUE TITLE
Update 'Edit' to 'Edit…' on entities context menu

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1367]
**Storage Explorer Version:** 1.8.1_20190513.2
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** 41005d14
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand a storage account -> Tables -> Create a new table -> Add some entities to it.
2. Select one entity and check its context menu.

**Expect Experience:**
Show 'Edit...' on the context menu.

**Actual Experience:**
Show 'Edit' on the context menu.
![image](https://user-images.githubusercontent.com/41351993/57677261-01732100-7659-11e9-9ff6-23de0db7f81e.png)

**Comment by jinglouMSFT** [comment]
Fix in PR

**Comment by jinglouMSFT** [comment]
Fix merged into master.

**Comment by v-xianya** [comment]
Verified on master\20190610.4. This issue has been fixed, so we close it.
