### ISSUE TITLE
Update the tooltip 'Dequeue' to 'Dequeue Message'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1368]
**Storage Explorer Version:** 1.8.1_20190513.2
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** 41005d14
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand a storage account -> Queues -> Create a new queue.
2. Hover the mouse on 'Dequeue Message' button in toolbar and check the tooltip.

**Expect Experience:**
Show 'Dequeue Message' as the tootip.

**Actual Experience:**
Show 'Dequeue' as the tootip.
![image](https://user-images.githubusercontent.com/41351993/57677499-8b22ee80-7659-11e9-869c-ae97275540f9.png)

**Comment by jinglouMSFT** [comment]
Fix in PR.

**Comment by jinglouMSFT** [comment]
Fix merged into master.

**Comment by JasonYeMSFT** [comment]
The fix has been merged to the npm package's source file. It needs to be published.

**Comment by v-xianya** [comment]
Hi @JasonYeMSFT Thanks for your update!

Verified this issue on the latest build 20190619.4. It has been fixed. So we close it!
