### ISSUE TITLE
Update the tooltip 'Import entities from file' to 'Import entities from a file'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1369]
**Storage Explorer Version:** 1.8.1_20190513.2
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** 41005d14
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand a storage account -> Tables -> Create a new table.
2. Hover the mouse on 'Import' button in toolbar and check the tooltip.

**Expect Experience:**
Show 'Import entities from a file' as the tooltip.

**Actual Experience:**
Show 'Import entities from file' as the tooltip.
![image](https://user-images.githubusercontent.com/41351993/57677750-287e2280-765a-11e9-9e64-decdd1141c91.png)

**Comment by jinglouMSFT** [comment]
Fix in PR.

**Comment by jinglouMSFT** [comment]
Fix merged into Master.

**Comment by v-xianya** [comment]
Verified on master\20190610.4. This issue has been fixed, so we close it.
