### ISSUE TITLE
Enable ability to copy text from table cells/rows

### ISSUE THREAD

**Issue by amithegde** [microsoft/AzureStorageExplorer#137]
**Version**: 1.0.0
**Platform**: Windows
**Architecture**: ia32
**Build Number**: 20180415.2
**Commit**: 5d603052

#### Steps to Reproduce: ####

1. Open a storage table which has some data
2. Try to select some text in a cell

#### Expected Experience: ####
- Be able to select some text on a cell and copy it with `Ctrl+C`
- Be able to select rows and copy by using `Ctrl+C`

#### Actual Experience: ####
Cant' select text in cells, cant copy, can't select multiple rows at a time and copy them as CSV/TSV

**Comment by amithegde** [comment]
Also, be able to select rows by click drag

**Comment by craxal** [comment]
We suggest using the Export feature in the toolbar to download data from tables, which exports table data to a CSV file.

**Comment by craxal** [comment]
Can you use the query builder to select the data you need? The Export function should support exporting just the queried entities.

Unfortunately, I can't pin down when we'll get a chance to look into this.

**Comment by amithegde** [comment]
You can push this request to backlog.

It would be great to have Ctrl+C feature in 2018 :)

**Comment by amithegde** [comment]
> @amithegede @awolman While we're looking at this, we've since added the ability to export only rows you have selected.

While I appreciate the effort to make users use Export feature, I would still prefer the select a cell, `Ctrl+C` to copy the value and move on.

**Comment by amithegde** [comment]
> @amithegde Understood. My comment was merely meant to inform of a workaround feature you can use while we continue to investigate this feature request.
> 
> Selecting a cell or text to copy will require some thought, because some users may want to copy one or more rows and not a cell. We also have to be thoughtful about whether we support copying multiple cells, if that will even be possible. Also, selecting rows by click drag could conflict with selecting text in a cell.

It is a customary to introduce a `tab` between text from two cells when copied so that it can be pasted on notepad for example in a tabular format. Even Microsoft Excel recognizes this format and pastes text into different cells.

Can look at Copy and Paste example here as a reference: https://github.com/6pac/SlickGrid/wiki/Examples
