### ISSUE TITLE
Use 'storage account' rather than 'Storage Account' of the description in the Connect dialog 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1370]
**Storage Explorer Version:** 1.8.1_20190513.2
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** 41005d14
**Regression From:** Not a regression

**Steps to reproduce:**
1. Click "Add Account" button.
4. Check the description "How do you ... Storage Account or service?" in the connect dialog.

**Expect Experience:**

Show "How do you ... **storage account** or service" in the dialog.

**Actual Experience:**

Show "How do you ... **Storage Account** or service" in the dialog.
![image](https://user-images.githubusercontent.com/41351993/57679695-8f053f80-765e-11e9-8aca-2a6a7dc7f12a.png)

**Comment by jinglouMSFT** [comment]
Fix in PR

**Comment by jinglouMSFT** [comment]
Fix merged into master.

**Comment by v-xianya** [comment]
Verified on master\20190610.4. This issue has been fixed, so we close it.
