### ISSUE TITLE
Can not access Cosmos DB account

### ISSUE THREAD

**Issue by binalyze-admin** [microsoft/AzureStorageExplorer#1371]
Hi, 

I have tried two latest versions of Azure Storage Explorer but still facing this issue. Tried deleting AppData folder, clearing the Local Storage > file:/// as well but it won't work. Please see below screenshot:

![image](https://user-images.githubusercontent.com/1567932/57687695-2efda180-763c-11e9-9f75-44257d99db57.png)

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
