### ISSUE TITLE
Return results in order

### ISSUE THREAD

**Issue by mikeblakeuk** [microsoft/AzureStorageExplorer#1373]
**Storage Explorer Version**: 1.8.1
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**: No

**Bug description**
When you load more, the items are not sorted.
a,c,d comes back. 
Load More. b,e,f comes back

**Steps to Reproduce**
Have lots of storage account with mixed names and ages
Load more (first 100 are loaded)
Load more (some accounts are "injected")

**Expected Experience**
Get storage accounts / subscriptions in A-Z order

**Actual Experience**
It appears storage accounts might be return chronologically.

**Additional Context**
(can we also increase the load size from 100?)

**Comment by MRayermannMSFT** [comment]
Hey @mikeblakeuk, unfortunately when we list Storage Accounts, they are not returned in alphabetical order. So to do this we'd have to get all accounts from ARM and then sort them. For some users though they have hundreds upon hundreds of Storage Accounts so this might lead to some perf issues. We can maybe try to find some time to investigate if that will be true though.

As for the load size, that is something we plan to expose via settings very soon. See #153

**Comment by MRayermannMSFT** [comment]
We already have an issue for exposing load more size via settings. As for the results not being returned in alpha order, we've checked with the platform team and there's nothing that can be done about that right now.
