### ISSUE TITLE
The new created blob container doesn't auto display when $logs or $web already exists in "Blob Containers"

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1376]
**Storage Explorer Version:** 1.8.1_20190514.1
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** 41005d14
**Regression From:** 1.8.1 release

**Steps to reproduce:**
1. Create a storage account( GPV2 ) -> Enable static website hosting.
2. Launch Storage Explorer then expand the created storage account -> Blob Containers -> Make sure there shows two blob container $web and $logs.
3. Create a new blob container.
4. Check whether the new blob container auto displays under 'Blob Containers' node or not.

**Expect Experience:**

The new blob container auto displays under 'Blob Containers' node.

**Actual Experience:**

The new created blob container doesn't auto display under 'Blob Containers' node.

**More Info:**
1. The new created blob container displays after manually refreshed.
2. This issue also reproduces when one storage account only has $logs.

**Comment by MRayermannMSFT** [comment]
Needed to update the CE ref. @v-xianya , this should be fixed in tomorrow's build. Can you verify then? Thanks!

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT ,

Thanks for your updates!

We will verify this issue using the latest build in tomorrow.

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT. 

Verified this issue on build 20190522.1. It doesn't reproduce.
