### ISSUE TITLE
Unable to login to Azure

### ISSUE THREAD

**Issue by Risord** [microsoft/AzureStorageExplorer#1377]
**Storage Explorer Version**: 1.8.1 (and 1.7.0)
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**: -

**Bug description**
I am trying to connect to Azure with my.name@company.onmicrosoft.com account which works just fine directly to Azure portal. However after login sign in dialog redirect to login again so you are in loop:
1. Insert username
2. Insert password
3. You get redirected to again sign in
4. Choose username from list (which you inserted on step 1)
5. Insert password again
6. Goto step 3

How to debug? Netword debugger doesn't show netword request done by sign in dialog.

**Steps to Reproduce**
1. Add Azure account with my.name@company.**onmicrosoft.com** account

**Expected Experience**
Login would be successful or at least meaningful error message should be given.

**Actual Experience**
Redirect loop

**Additional Context**
We tend to use my.name@company.com login but these accounts got deleted or something in who-know-what migration.

**Comment by MRayermannMSFT** [comment]
Hi @risord, can you try using Device Code Flow Sign-in? You can find it under the preview menu.

**Comment by Risord** [comment]
It doesn't work either. I got "You have signed in to the Microsoft Azure Cross-platform Command Line Interface application on your device. You may now close this window." message from the browser but Storage Explorer won't proceed anywhere.

On the other hand I gave access to my new Office365 account to our Azure and I am able to log in to Storage Explorer with it (both normal and Device Code Flow). Therefore this is no longer show stopper for me.

**Comment by MRayermannMSFT** [comment]
Ok, sounds good.
