### ISSUE TITLE
No "Add to Quick Access" displays on one blob container's context menu

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1378]
**Storage Explorer Version:** 1.8.1_20190515.1
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** fe253f0c
**Regression From:** 1.8.1 release

**Steps to reproduce:**

1. Expand a Non-ADLS Gen2 storage account -> Blob Containers.
2. Right click one blob container.
3. Check whether "Add to Quick Access" displays on its context menu or not. 

**Expect Experience:**
"Add to Quick Access" displays on the blob container's context menu
![image](https://user-images.githubusercontent.com/41351993/57829975-3e6b1f00-77e3-11e9-82e4-a3d61ecbd145.png)

**Actual Experience:**
No "Add to Quick Access" displays on the blob container's context menu
![image](https://user-images.githubusercontent.com/41351993/57830053-7d997000-77e3-11e9-9966-3a0e8b58fee2.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
