### ISSUE TITLE
AzureStorageExplorer connection issue

### ISSUE THREAD

**Issue by Thirapathireddy** [microsoft/AzureStorageExplorer#1379]
Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: a6b169f1-592b-4329-8f33-8db8903003c7, Error: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"13.71.185.242","port":443}

**Comment by MRayermannMSFT** [comment]
Hey @thirapathireddy, are you behind a proxy?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
