### ISSUE TITLE
[Feature Request] Azure Data Lake Gen 2 | Cascade security settings

### ISSUE THREAD

**Issue by danielstocker** [microsoft/AzureStorageExplorer#1380]
To my knowledge, there is currently no UI feature to reset and cascade security setting to child files and folders on the Azure Storage Explorer when using Azure Data Lake Gen2. 

This is supported via the command line tools, but it would be nice to be able to reset and cascade permissions in Azure Storage Explorer directly.

**Comment by MRayermannMSFT** [comment]
Hey @danielstocker, what CLI tools support this scenario?

**Comment by danielstocker** [comment]
Sorry @MRayermannMSFT I wasn't clear at all in that statement. 
What I was thinking off was using PowerShell (or another command line tool) as a REST client to both iterate through an existing DL Gen2 file system and apply permissions. 

https://docs.microsoft.com/en-gb/rest/api/storageservices/datalakestoragegen2/path/list
https://docs.microsoft.com/en-gb/rest/api/storageservices/datalakestoragegen2/path/update

I realise that I made it sound like I'm thinking of a single CLI command to apply recursive permissions.

**Comment by MRayermannMSFT** [comment]
For us, this is the type of feature we will wait for the APIs to support.

**Comment by MRayermannMSFT** [comment]
Hi y'all, the storage service added an API that will allow us to do this. Thought I'm not sure if it'll be in a way that'll make y'all happy. 

https://docs.microsoft.com/en-us/azure/storage/blobs/recursive-access-control-lists?tabs=azure-powershell

We'll be adding a feature which uses this API in version 1.17. You can track that work here: #3695

I'm going to leave this issue open for a while in-case y'all have anything to say. Eventually I will close it in favor of issue #3695 though. Thanks.

**Comment by MRayermannMSFT** [comment]
Hi all, 1.17 recently shipped with a feature that allows you to propagate the ACLs of a directory to all of it's existing descendants. Please give the feature a try and let us know if you have any feedback. Thanks!

**Comment by MRayermannMSFT** [comment]
Closing. If anyone has feedback feel free to open an issue. :)
