### ISSUE TITLE
Make sure a long running stg acct -> stg acct blob copy actually finishes

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#1381]
Internal customer claims a long running, overnight copy crashed, we should investigate.

Steps to try and reproduce:

1. Create a storage account in a region
2. Create a storage account in another region
3. Upload a very large file into the first storage account, something greater than 100GB in size. Ideally the file can be uploaded as a page blob
4. Copy and paste the page blob to the other storage account
5. See if Storage Explorer stays running until the copy finishes (it may take a very long time, a matter of days)

**Comment by MRayermannMSFT** [comment]
@v-xuanzh , can one of y'all try following the above steps to see if this repros?

**Comment by v-xuanzh** [comment]
Hi @MRayermannMSFT ,I will verify this issue with tomorrow's new build.

**Comment by v-xuanzh** [comment]
Hi @MRayermannMSFT ,We verified this issue with the latest master build 20190522.1 and got a different result following your steps 

**Prerequisite**:

(1) The first account with East US region
(2) The second account with West US region
(3) Uploaded file = 120G

**Actual Experience:**

The 'Copy Conflict' dialog pops up during the paste activities.
![image](https://user-images.githubusercontent.com/34729022/58164242-074fae80-7cb8-11e9-92fb-45881a2700ad.png)
![image](https://user-images.githubusercontent.com/34729022/58167417-80520480-7cbe-11e9-81cb-7fe553325bf7.png)

**More info:**

The operation is skipped after clicking 'Overwrite'.
(We used new created blob container to paste the uploaded file every time.)

**Comment by MRayermannMSFT** [comment]
Xuan has left, probably not worth the time to verify that a long running JS copy works since it should be using AzCopy soon.
