### ISSUE TITLE
Unable to sign into Azure Storage Explorer

### ISSUE THREAD

**Issue by n1ckl0ve** [microsoft/AzureStorageExplorer#1383]
**Storage Explorer Version**: 1.8.1
**Platform/OS**: Windows 10 1803
**Architecture**:  x64?_
**Regression From**: No

**Bug description**
Azure Storage explorer was working yesterday. I had a password change today, and for some reason needed to go through setting up of MFA again.

I can sign into the Azure Portal successfully now using my login details and MFA.

**Steps to Reproduce**
1. Open the Storage explorer, 
2. Add an Azure Account
3. Type email address
4. Application states that its handing over to my company's sign in page.
5. Then Error "{
  "message": "\"ERR_SSL_CLIENT_AUTH_SIGNATURE_FAILED\""
}"

**Expected Experience**
I expect it to prompt for my password on companys sign in page.

**Actual Experience**
Not

**Additional Context**
I have removed the ".identityService" Folder.
I have performed a reset of the application using the "Reset" option under - Help.
I have enabled the check box for "Use Device Code flow", however very similar. When I try to sign in, I get the url and code. When I sign into the browser, the browser states I signed in successfully but he Storage explorer does nothing further.

**Comment by MRayermannMSFT** [comment]
@n1ckl0ve , please see this section of our troubleshooting guide for help with SSL issues: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=1804#error-self-signed-certificate-in-certificate-chain-and-similar-errors

**Comment by MRayermannMSFT** [comment]
Closing due to lack of customer response.
