### ISSUE TITLE
Unable to retrieve child resource when attaching a blob container

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1386]
**Storage Explorer Version:** 1.8.1_20190522.1
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** 1.8.1 release

**Steps to reproduce:**
1. Expand one normal account -> 'Blob Containers'
2. Right click one blob container then select 'Get Shared Access Signature...'.
3. Generate the SAS URI of the blob container.
4. Try to attach the blob container using the SAS URI.
5. Check the result.

**Expect Experience:**

The blob container can be attached successfully.

**Actual Experience:**

1. There always shows 'Adding new connection' on Activities.
2. Pop up the below error when trying to expand the 'Blob Containers' node under 'Local & Attached'
![image](https://user-images.githubusercontent.com/34729022/58161574-141dd380-7cb3-11e9-81a5-f08236c3c560.png)

**Comment by MRayermannMSFT** [comment]
Fixed on master. @v-xuanzh, please verify!
