### ISSUE TITLE
Adding URI with trailing space should remove space or fail

### ISSUE THREAD

**Issue by FaronFaulk** [microsoft/AzureStorageExplorer#1387]
**Storage Explorer Version**:  1.8
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**: _Was this working in a previous version? not that i know of.

**Bug description**
Creating a new connection that contains a connection string with a trailing space allows the connection to be created (no error), but then fails when you try to use it.

**Steps to Reproduce**
1. Click 'Connect to Azure Storage'
2. select 'Use a connection string'
3. Click Next
4. Paste the connection string that contains a trailing space.
5. Click Next.
6. Click Connect. Connection is created successfully.
7. Click the Blob Storage under the new connectoid
8. observe the error:
"[Window Title]
Microsoft Azure Storage Explorer

[Content]
The provided URI "core.windows.net " is invalid.

[OK]"

**Expected Experience**
If the connection string contains a trailing space, ASE should either remove it automagically (since it's never valid) or prompt the user to remove it. 
ASE should NEVER continue without error if the connection string is invalid.

**Actual Experience**
![image](https://user-images.githubusercontent.com/44375156/58205663-fea5ab00-7cac-11e9-8a8a-8a94e846abe5.png)

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by JasonYeMSFT** [comment]
Close as fixed.
