### ISSUE TITLE
Folders with too many files take too long to delete

### ISSUE THREAD

**Issue by andre-ss6** [microsoft/AzureStorageExplorer#1388]
**Storage Explorer Version**: 1.8.1
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**: Not sure

**Bug description**
I have a folder with a ASP.NET Core website published, so inside it there are some .NET Core DLLs and some folders like wwwroot, which in turn has bootstrap, jquery, etc.

If I try to delete that folder, ASE gets stuck on "Discovering blobs for deletion from [...]". I've waited more than 3min and it was still stuck on that.

**Steps to Reproduce**
1. Publish a SCD ASP.NET Core website with some 10 popular JS libraries installed (or anything like this) and upload it to a folder on a blob storage container.
2. Try to delete the folder.

**Expected Experience**
My files are deleted in a reasonable time.

**Actual Experience**
My files are _not_ deleted in a reasonable time.

**Comment by craxal** [comment]
@andre-ss6 About how many blobs are in this directory?

**Comment by andre-ss6** [comment]
Maybe something like three thousand files.

**Comment by andre-ss6** [comment]
Well, a friend tried to delete on his machine using this same version and it worked normally. 🤷‍♀️ 
Although it still took some time to actually delete, the "Discovering blobs for deletion" message didn't even appear. If this happens again I'll be sure to report.

**Comment by craxal** [comment]
@andre-ss6 That'll work. Out of curiosity, did you try this with AzCopy turned on?

**Comment by andre-ss6** [comment]
@craxal Yea, I forgot to mention that. Yes, I did. And if I'm not mistaken, I tried having it both on and off. For reference, my friend also used AzCopy on.
