### ISSUE TITLE
The QA blob container doesn't  show as broken after renaming/deleting the original item

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1389]
**Storage Explorer Version:** 1.8.1_20190523.2
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** 1.8.1 release

**Steps to reproduce:**
1. Expand one normal account -> 'Blob Containers' node.
2. Right click one blob container then select 'Add to Quick Access'.
3. Try to rename or delete the original blob container.
4. Check whether the Quick Access blob container shows broken or not.

**Expect Experience:**

The Quick Access blob container shows as broken.

**Actual Experience:**

The Quick Access blob container doesn't show as broken.

**More info:**
This issue doesn't reproduce for file shares/queues/tables.

**Comment by MRayermannMSFT** [comment]
Hey @v-xuanzh , I think I might have fixed this on master. Can you verify? Thanks.

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT 
We verified this issue on the build master/20190624.4. It still reproduces.

**Comment by MRayermannMSFT** [comment]
Hey @v-xianya, I'm going to go ahead and close this. The way we are loading QA items now, we don't make a call to Azure. Instead we make the node from the information we have stored. It isn't till the user tries to do something with the container that we can find out it doesn't exist. So at that point should we break? Eh. Probably. But I don't think it's worth it w/o customer feedback that they'd like. So closing for now. Thanks for reporting though. 😄

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT , Thanks for your sharing.
For this issue, We noticed it doesn't reproduce for QA file shares/queues/tables😲. Does the way loading QA file shares/queues/tables is different from QA blob containers？Could your help to take a look? Thank a lot！

**Comment by MRayermannMSFT** [comment]
@v-xianya Yes. It is different.
