### ISSUE TITLE
Adding a new created blob container to Quick Access shows as broken

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1390]
**Storage Explorer Version:** 1.8.1_20190523.2
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** 1.8.1 release

**Steps to reproduce:**
1. Expand one normal account -> Create a new blob container.
2. Try to add the new created blob container to Quick Access.
3. Check the status of added blob container in Quick Access.

**Expect Experience:**

The blob container shows well after adding it to Quick Access.

**Actual Experience:**

The blob container shows as broken after adding it to Quick Access.

**More info:**
1. This issue doesn't reproduce for file shares/queues/tables.
2. This issue also reproduces when adding one renamed blob container to Quick Access.

**Comment by MRayermannMSFT** [comment]
Fix checked into master
