### ISSUE TITLE
The 'Range' contents can be edited when the radio button isn't selected on 'Custom TimeStamp Query' dialog 

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1392]
**Storage Explorer Version:** 1.8.1_20190523.2
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Open a table in an editor.
2. Click 'Query' -> Add a new clause for any DateTime type field.
3. Select the pull-down menu under the Value item -> Select 'Custom...'.
4. Check the 'Last' item -> Try to edit the start/end time from 'Range' item.

**Expect Experience:**

1. These time cannot be edited due to the 'Range' item isn't checked.
2. 'OK' button is enabled.

**Actual Experience:**
1. There time can be edited.
2. 'OK' button is disabled.
![image](https://user-images.githubusercontent.com/34729022/58238155-54478980-7d79-11e9-9fdd-a675de1d2aae.png)

**Comment by craxal** [comment]
You can still edit the range to be valid as a workaround, so won't fix. If customers bring this up, we'll revisit.
