### ISSUE TITLE
The new created blob container shows an extra 'Detach' action on the context menu

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1393]
**Storage Explorer Version:** 1.8.1_20190523.2
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** 1.8.1 release

**Steps to reproduce:**
1. Expand anyone account -> 'Blob Containers' node.
2. Create a new blob container -> Check its context menu.

**Expect Experience:**

There doesn't show the 'Detach' action.

**Actual Experience:**
There shows an extra 'Detach' action.
![image](https://user-images.githubusercontent.com/34729022/58238458-e6e82880-7d79-11e9-9737-5ca220519f47.png)

**More info:**
This issue also reproduces for ADLS Gen2 blob containers.

**Comment by MRayermannMSFT** [comment]
Fix checked into master
