### ISSUE TITLE
The downloading activities cannot complete when the selected folder is empty for one ADLS Gen2 account

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1394]
**Storage Explorer Version:** 1.8.1_20190523.2
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one ADLS Gen2 account -> 'Blob Containers' node.
2. Open one blob container then create an empty folder.
3. Try to download the empty folder. 
4. Check the result.

**Expect Experience:**

The empty folder can be downloaded successfully.

**Actual Experience:**

The downloading activities cannot complete and takes a long time.
![image](https://user-images.githubusercontent.com/34729022/58239160-26fbdb00-7d7b-11e9-91b8-238136a4e8f5.png)

**Comment by MRayermannMSFT** [comment]
AzCopy bug. See here: https://github.com/Azure/azure-storage-azcopy/issues/412

**Comment by v-limu** [comment]
The downloading activities has been changed on build [20191106.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3218228&view=logs). So we close it.
![image](https://user-images.githubusercontent.com/54055206/68375176-506dbf00-0181-11ea-9a0b-306346039798.png)
