### ISSUE TITLE
Update the 'Query string' to 'Query String' on Generate SAS dialog

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1395]
**Storage Explorer Version:** 1.8.1_20190523.2
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Right click one normal account -> Select 'Get Shared Access Signature...'.
2. Set the permissions -> Click 'Create'.
3. Check the contents on the 'Generate SAS' dialog.

**Expect Experience:**

There shows 'Query String' rather than 'Query string'.

**Actual Experience:**

'Query string' instead of 'Query String'.
![image](https://user-images.githubusercontent.com/34729022/58239625-f8323480-7d7b-11e9-8456-a5c722a88870.png)

**Comment by MRayermannMSFT** [comment]
We're actually doing the "red" way. So the "green" labels are wrong. Will fix those.

**Comment by MRayermannMSFT** [comment]
Fix merged to master.
