### ISSUE TITLE
Sign-In Error

### ISSUE THREAD

**Issue by klem-ent** [microsoft/AzureStorageExplorer#1396]
Explorer v.: 1.8.1
Microsoft Windows: version 10.0.16299.1029

Unable to sign in, it gave me this error. I don't have proxy at home, and checked that the Explorer's proxy settings are cleaned (=OK).
Only my Internet Explorer got a proxy setting, but even if I remove it, I still have the error.

{
  "message": "\"ERR_PROXY_CONNECTION_FAILED\""
}

**Comment by craxal** [comment]
@klem-ent Check out our [troubleshooting guide](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=1804#proxy-issues) for more info on proxies. If you still have problems, let us know.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of customer response.
