### ISSUE TITLE
Unable to sign in to Storage Explorer

### ISSUE THREAD

**Issue by dootdootbeep** [microsoft/AzureStorageExplorer#1397]
**Storage Explorer Version**: 1.8.1
**Platform/OS**: Windows 10
**Architecture**:  x64
**Regression From**: Never tried

**Bug description**
Unable to sign in to Azure Government tenant

**Steps to Reproduce**
1. Add account and select Azure US Government  
2. Enter credentials in Azure AD login screen
3. Redirected to internal ADFS  
4. Window appears stating "Waiting for authentication" window spins for awhile.
5. Error message stating: "Subscriptions for the following tenants could not be loaded {tenantID}. Error: {"code":"UNABLE_TO_VERIFY_LEAF_SIGNATURE"}

**Expected Experience**
Successful login

**Actual Experience**
Error message stating: "Subscriptions for the following tenants could not be loaded {tenantID}. Error: {"code":"UNABLE_TO_VERIFY_LEAF_SIGNATURE"}

Device Login doesn't work either.

**Additional Context**
Customer does SSL inspection

**Comment by craxal** [comment]
@dootdootbeep Check our [troubleshooting guide](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=1804#error-self-signed-certificate-in-certificate-chain-and-similar-errors) for more info on certificates. Get back to us if you're still having troubles.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response
