### ISSUE TITLE
AzCopy fails to complete large upload

### ISSUE THREAD

**Issue by whanksta** [microsoft/AzureStorageExplorer#1398]
**Storage Explorer Version**: 1.8
**Platform/OS**: Server 2016/2019
**Architecture**: x64
**Regression From**: N/A

**Bug description**
I Tried to upload ~150k small files (100gb) to blob storage utilizing preview feature "AzCopy". The upload completes around ~30k actual files uploaded with no error. Repeated attempts could not get all files uploaded. 

I was able to upload everything utilizing AzCopy outside of Storage Explorer. 

**Steps to Reproduce**
1. Upload folder

**Expected Experience**
All files uploaded

**Actual Experience**
Only partial upload without any reported error

**Comment by MRayermannMSFT** [comment]
Hey @whanksta , are you selecting a bunch of folders that hold the files, or are you selecting a bunch of files? Or more specifically, how big is your initial selection of files and folders?

**Comment by whanksta** [comment]
I am selecting a single folder that holds thousands of folders and subfolders.

**Comment by craxal** [comment]
@whanksta Are you trying to overwrite files in your upload? AzCopy on the command line overwrites by default. But Storage Explorer turns the AzCopy overwrite option off, so you will run into an error if you're trying to upload a re-upload to an existing blob.

**Comment by whanksta** [comment]
> @whanksta Are you trying to overwrite files in your upload? AzCopy on the command line overwrites by default. But Storage Explorer turns the AzCopy overwrite option off, so you will run into an error if you're trying to upload a re-upload to an existing blob.

I am overwriting existing uploads but never ran into any "Errors" presented by the Explorer.

**Comment by MRayermannMSFT** [comment]
@whanksta , can you try invoking AzCopy directly via the command line? You can download an exe here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=1804
And then you can use the same command we use by clicking on the "Copy AzCopy command to clipboard" action in the activity log.

This should help us figure out if this is a Storage Explorer issue or an AzCopy issue.

**Comment by MRayermannMSFT** [comment]
@whanksta are you still having issues? Please let us know!

**Comment by whanksta** [comment]
I just uploaded another batch of ~172k files via the same method and it uploaded everything without an issue.

**Comment by whanksta** [comment]
This happened again. tried to upload 182k files, 120gb, only 15k are uploaded, repeated attempts with the same result. 

![image](https://user-images.githubusercontent.com/50347256/63470960-fa1f9880-c43b-11e9-827b-de8a8a8cb9d4.png)

**Comment by craxal** [comment]
@whanksta The statistics feature you're showing can be pretty inaccurate sometimes (we plan to fix it at some point). Is that how you're trying to verify if everything uploaded? Can you verify for sure that you have any missing files another way?

**Comment by whanksta** [comment]
It was 100% accurate for emails/marketing - 51577 blobs, I had no reason to doubt other results. 

I knew files were missing because the upload completed too quickly, even subsequent attempts. There are no other ways for me to verify unless I download everything and run stats on it.
