### ISSUE TITLE
Cannot search for Azure Storage explorer on Windows

### ISSUE THREAD

**Issue by nishankgu** [microsoft/AzureStorageExplorer#1399]
**Storage Explorer Version**: 1.8.1 (have seen this forever
**Platform/OS**: Win10
**Architecture**:x64
**Regression From**: _Was this working in a previous version? If so, which one?_

**Bug description**
When you search for "Storage explorer" or "Azure Storage explorer" or "Microsoft Azure Storage explorer" - none of those work. Why?

**Steps to Reproduce**
1. Do Windows+Q and search for the product, it never shows up

**Expected Experience**
_A clear and concise description of what you expected to happen. If applicable, add screenshots to help explain what you expected._

**Actual Experience**
_A clear and concise description of what actually happens. If applicable, add screenshots to help explain what actually happened._

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by MRayermannMSFT** [comment]
Hey @nishankgu, unfortunately this isn't something we directly control. I'd advise doing some web searches regarding programs not showing up in Windows search. Sorry to not be of more help. :(
