### ISSUE TITLE
An error occurs when trying to expand a CosmosDB account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1402]
**Storage Explorer Version:** 1.8.1_20190524.1
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** 7c0154a6
**Regression From:** Previous release 1.8.1

**Steps to reproduce:**
1. Launch Storage Explorer -> Expand one CosmosDB account.
2. Check the result.

**Expect Experience:**
No error occurs and it can be expanded successfully.

**Actual Experience:**
An error occurs.
![image](https://user-images.githubusercontent.com/41351993/58312728-7ce58700-7e3e-11e9-89ab-ca277126e04b.png)

**Comment by v-xuanzh** [comment]
This issue still reproduces on the latest feature branch build.

**Comment by v-xianya** [comment]
Verified this issue on build main-host\20190605.4. It still reproduces, so we re-open it.

**Comment by craxal** [comment]
This is still fixed on my end. The build probably didn't have the right CloudExplorer reference. Verify on a new build, please.

**Comment by v-xianya** [comment]
Verified on the latest feature branch. This issue has been fixed.
