### ISSUE TITLE
Refresh button is out of view in Blob Containers view

### ISSUE THREAD

**Issue by artemious7** [microsoft/AzureStorageExplorer#1404]
**Storage Explorer Version**:  1.8.0 and 1.8.1
**Platform/OS**: Windows 10
**Architecture**: _x64_
**Regression From**:  It was. Don't remember, but definitely it was working in February 2019.

**Bug description**
Refresh button is not there in the commands panel of Blob Containers view. The last button I see (though only partly) is Manage Snaphots. I also can not scroll to this button, which, as I suppose, should be there, but not visible.

**Steps to Reproduce**
1. I open one of my Blob Containers. The commands here are labeled in Russian, because it's my OS language (but commands in other views are in English, for example in Tables View). 

2. Hide the "Explorer" using the "Toggle Explorer" button. But I still don't see the "Refresh" button (which is supposed to be in the end of the command panel). The last button I see (though only partly) is Manage Snaphots.

**Expected Experience**
_A clear and concise description of what you expected to happen. If applicable, add screenshots to help explain what you expected._
![image](https://user-images.githubusercontent.com/16724889/58315037-65e06e00-7e19-11e9-979b-4cc3171bfa95.png)

**Actual Experience**
_A clear and concise description of what actually happens. If applicable, add screenshots to help explain what actually happened._
![image](https://user-images.githubusercontent.com/16724889/58315084-7ee91f00-7e19-11e9-88b9-a86fa3f8b384.png)

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._
**Screen resolution**: 1920x1080
**Scale**: 150%

**Comment by MRayermannMSFT** [comment]
@aretmous7 if you resize the window does that cause either the refresh button or the more button to appear?

**Comment by v-xuanzh** [comment]
Hi @MRayermannMSFT I can reproduce this issue.

The 'Refresh' button shows after zooming out the window. 
![image](https://user-images.githubusercontent.com/34729022/58855279-3d3a5d00-86d2-11e9-9af0-664e3ea01fb0.png)

**Comment by artemious7** [comment]
I can resize the window only to make it smaller width. The system doesn't allow me to make it wider because it's the maximum width - my screen width.

**Comment by artemious7** [comment]
I can use the Refresh button in English version. But Russian has now made it unusable, though I often need only this button

**Comment by craxal** [comment]
@artemious7 Localization is being turned off in the next version. This feature is still a work in progress. Sorry for the confusion!
