### ISSUE TITLE
Show an extra action 'Add to Quick Access' for an Quick Access blob container 	

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1407]
**Storage Explorer Version:** 1.8.1_20190524.1
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Previous release 1.8.1

**Steps to reproduce:**
1. Expand one normal account -> Blob Containers.
2. Right click one blob container -> Select 'Add to Quick Access'.
3. Check the context menu of the Quick Access blob container.

**Expect Experience:**

There is no extra action on the context menu.

**Actual Experience:**

There shows an extra action 'Add to Quick Access' on the context menu.
![image](https://user-images.githubusercontent.com/34729022/58315741-b02b1480-7e44-11e9-91d7-061a68529c8c.png)

**More info:**

This issue doesn't reproduce for file shares/queues/tables.

**Comment by craxal** [comment]
I don't think this bug is related to the feature work this build is based on, so assigning to Matt to fix in master.

**Comment by MRayermannMSFT** [comment]
Fix merged into master.

**Comment by v-xianya** [comment]
Verified on build master\20190605.8, This issue also reproduces. So we re-open it.

**Comment by MRayermannMSFT** [comment]
Ok, real fix actually now merged to master. 😋

**Comment by v-xuanzh** [comment]
This issue still reproduces on latest  master build. 
Keep closed status. And we will verify it in next build.
