### ISSUE TITLE
Unable to 'Add an Azure Account'

### ISSUE THREAD

**Issue by Mithrilhall** [microsoft/AzureStorageExplorer#1410]
**Storage Explorer Version**: 1.8.1
**Platform/OS**: Linux (KDE Neon 5.15)
**KDE**:
- KDE Plasma Version: 5.15.5
- KDE Frameworks Version: 5.58.0
- Qt Version: 5.12.0
- Kernel Version: 4.15.0-50-generic

**Architecture**: x64

**Bug description**
When trying to 'Add an Azure Account' via the 'Sign in...' button I get prompted via a dialog window to sign into my account. After entering my username/password I get the 'Waiting for authentication' loading screen. In the dev tools console I see the following:

![error](https://user-images.githubusercontent.com/5432148/58334009-a7b6e780-7e0c-11e9-9fb2-85d105d98785.png)

**Steps to Reproduce**
1. Launch StorageExplorer.
2. Click the 'Add Account' button.
3. Choose 'Add an Azure Account' and click the 'Sign in...' button.

**Expected Experience**
I expect it to actually connect to azure (see image).

**Actual Experience**
Never connects but the 'Waiting for authentication' screen disappears after a few minutes.

**Comment by MRayermannMSFT** [comment]
@Mithrillhall did you install dependencies that are the equivalent of the ones we specify for ubuntu?

**Comment by Mithrilhall** [comment]
@MRayermannMSFT It appears to be working now. Thanks.
