### ISSUE TITLE
Can't connect to Azure DataLake Gen 2

### ISSUE THREAD

**Issue by bellowman** [microsoft/AzureStorageExplorer#1411]
**Storage Explorer Version**: 18.1
**Platform/OS**: Windows 10?
**Architecture**: x64?
**Regression From**: It was working in 18.0

**Bug description**
I can't access my Azure DataLake gen 2.  I can see when I search for it my typing in its name, but I can't access. This work in the previous version. Please fix immediately

![image](https://user-images.githubusercontent.com/16313859/58372967-ef646e80-7ef3-11e9-94d8-90375354e78b.png)

**Comment by MRayermannMSFT** [comment]
Does it work when you're not in the search results view? If not, can you elaborate how not?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of reply.
