### ISSUE TITLE
The value of the theme always is 'dark' on Dev Tools even though the current theme isn't Dark

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1412]
**Storage Explorer Version:** 1.8.1_20190524.5
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Previous release 1.8.1

**Steps to reproduce:**
1. Launch Storage Explorer -> Make sure the current theme **isn't Dark**(Like HC-Black).
2. Go to Developer Tools(Press F12) -> Application -> Local Storage -> file://
3. Check the value of the theme.

**Expect Experience:**

The value of the theme is 'hc-black'

**Actual Experience:**

The value of the theme is 'dark'.
![image](https://user-images.githubusercontent.com/34729022/58408337-31caae80-80a0-11e9-9fcf-5cea49658f8f.png)

**Comment by craxal** [comment]
Won't fix. This value is no longer the correct theme. That's not found in a settings.json file in the app data folder.
