### ISSUE TITLE
Miss 'Detach' action for one Quick Access blob container which is added from 'Attached Containers'

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1413]
**Storage Explorer Version:** 1.8.1_20190524.5
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Previous release 1.8.1

**Steps to reproduce:**
1. Expand one normal account -> 'Blob Containers'.
2. Select one blob container to attach using SAS URI.
3. Go to 'Local & Attached' -> 'Storage Accounts' -> '(Attached Containers)'.
4. Select the attached blob container -> Add it to Quick Access.
5. Right click the Quick Access blob container -> Check the context menu.

**Expect Experience:**

'Detach' action shows on the context menu.

**Actual Experience:**

Miss 'Detach' action on the context menu.
![image](https://user-images.githubusercontent.com/34729022/58408978-a9e5a400-80a1-11e9-812c-e567d2bd200a.png)

**More info:**
This issue doesn't reproduce for file shares/queues/tables/storage account.

**Comment by craxal** [comment]
Reproducible on master branch.

**Comment by MRayermannMSFT** [comment]
Won't fixing for now. We're going to try not allowing people to detach from the QA version of the node.

**Comment by v-xuanzh** [comment]
Hi @MRayermannMSFT 
For Quick Access file share/queue/table/storage account, There still shows the Detach action, Do we need to log an another bug to track?
![image](https://user-images.githubusercontent.com/34729022/58846930-91821480-86b3-11e9-8f9f-d2cc9f730f6c.png)
