### ISSUE TITLE
The percentage is changed from 7% to 100% directly when uploading a page blob using AzCopy

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1415]
**Storage Explorer Version:** 1.8.1_20190524.5
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Make sure AzCopy is enabled.
2. Expand one normal account -> 'Blob Containers'.
3. Open one blob container then upload a large blob file(Like 30G) as page blob.
4. Check the percentage from uploading activities.

**Expect Experience:**

The percentage is getting bigger and bigger.

**Actual Experience:**

The percentage keep 7% a long time, then upload activities finishes directly.
![image](https://user-images.githubusercontent.com/34729022/58411428-db14a300-80a6-11e9-8a98-c39c8ddc992d.png)

**More info:**
1. This issue doesn't reproduce when uploading a block blob using AzCopy.
2. This issue doesn't reproduce when uploading a page/block blob without AzCopy.

**Comment by MRayermannMSFT** [comment]
Won't fix. If AzCopy is reporting immediate 7% -> 100% then that's the percentage they are reporting. If we get similar feedback from customers though and the feedback is "we don't like this" then I'll raise an issue with the AzCopy team.
