### ISSUE TITLE
No "Refresh" shows on one attached table's context menu

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1417]
**Storage Explorer Version:** 1.8.1_20190524.5
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** b5247b04 
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand a storage account -> Tables.
2. Create a new table -> Use SAS URl to attach it.
3. Check the attached table's context menu.

**Expect Experience:**
Show "Refresh" on its context menu.

**Actual Experience:**
No "Refresh" shows on its context menu.

**More Info:**
1.This issue also reproduces for one attached queue.
2.This issue doesn't reproduce for one attached blob / file share.

**Comment by MRayermannMSFT** [comment]
Won't fixing. Small issue.
