### ISSUE TITLE
Unable to view all properties on table query editor which contains multiple properties

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1418]
**Storage Explorer Version:** 1.8.1_20190524.5
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** b5247b04 
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one account -> 'Tables' node.
2. Create a new table -> Add one entity which contains multiple properties.
3. Click 'Query' -> Check whether there is a scrollbar to view all properties or not.

**Expect Experience:**

There shows a scrollbar to view all properties of the entity.
![image](https://user-images.githubusercontent.com/34729022/58464398-3064b900-8168-11e9-8be7-b69d0cb19178.png)

**Actual Experience:**

There is no scrollbar to view all properties of the entity.
![image](https://user-images.githubusercontent.com/34729022/58464364-22af3380-8168-11e9-909b-7f88c25fbf87.png)

**More info:**

This issue doesn't reproduce after collapsing the Activities.

**Comment by MRayermannMSFT** [comment]
Won't fix. If you resize the scrollbar comes back.
