### ISSUE TITLE
Adding CORS rules to Premium account causes an error

### ISSUE THREAD

**Issue by v-flyuan** [Microsoft/AzureStorageExplorer#142]
**Storage Explorer Version**: 1.1.0 RC

**Platform**: Windows/Linux/Mac

**Architecture**: x64

**Build Number**: 20180503.1

**Commit**: 253b437b

**Regression From**: Not a regression

#### Steps to Reproduce: ####

1.  Launch Storage Explorer and expand Storage Accounts. 
2.  Right click 'Blob Containers' node under a premium storage account and select "Configure CORS Settings...".
3.  On the 'CORS' Settings dialog, click 'Save' directly. Verify whether save successfully or not. 

#### Expected Experience: ####
Save successfully. 

#### Actual Experience: ####
Pop up an error dialog. You can see the screenshot.
![cors](https://user-images.githubusercontent.com/12556995/39618664-45e3b8f2-4f74-11e8-90c1-87ae56fa2931.png)

**Comment by craxal** [comment]
Same root as #133. Already fixed.

**Comment by v-xuanzh** [comment]
The issue #133 has been fixed. But we have no way to add rules for premium account with the posted error. 
Could you help to take look at it?

**Comment by v-xuanzh** [comment]
This issue still reproduces on 20180704.1. But it displays as the below different error
![error](https://user-images.githubusercontent.com/34729022/42314560-d6a12320-8034-11e8-9ef4-db8840adb47e.png)

**Comment by craxal** [comment]
CORS is not supported for Premium Storage accounts (see [documentation](https://docs.microsoft.com/en-us/rest/api/storageservices/cross-origin-resource-sharing--cors--support-for-the-azure-storage-services)).

We just need to remove this action.

**Comment by v-xuanzh** [comment]
Hi @craxal , The action **'Configure CORS Settings...**' still shows on the premium context menu with build 20180724.5. So we re-open this issue.
![need_to_remove](https://user-images.githubusercontent.com/34729022/43181636-b0c177e2-8fcd-11e8-9fd9-66792eab6362.png)

**Comment by v-xuanzh** [comment]
For the original premium account, the action 'Configure CORS Setting...' is removed. But for one attached premium account, the action still displays. So we re-opened this issue.
![action](https://user-images.githubusercontent.com/34729022/43384008-3dd186de-93cc-11e8-864e-5b9c995b27e8.png)

**Comment by craxal** [comment]
The visibility of this option depends on information that can only be retrieved from the management endpoint, which we don't have for attached resources. This is not a high-priority issue, so I'm closing as Won't Fix.
