### ISSUE TITLE
Error when adding connection and when trying to access connection

### ISSUE THREAD

**Issue by debchat** [microsoft/AzureStorageExplorer#1421]
**Storage Explorer Version**: 1.8.1
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:

**Bug description**
Trying to use Storage Explorer to connect to Azure storage.

**Steps to Reproduce**
1. Add account
2. Use SAS URI
3. Next page - fill URI
4. Fills other fields as expected.
5. Tweak - change name slightly. Then I can click "connect"
6. "Adding new connection"
7. Stays in that phase for very long time

![Azure1](https://user-images.githubusercontent.com/51143917/58525029-d1b33580-818f-11e9-82b2-33dd070cb5a7.PNG)

Even if I press "Refresh all", then open "Storage accounts" 
![Azure2](https://user-images.githubusercontent.com/51143917/58525095-0626f180-8190-11e9-9d1f-97063937faf4.PNG)

**Expected Experience**
I expect a new storage account will be visible and I can see content of that storage account.

**Actual Experience**
Cannot go past "Adding new connection" stage

**Comment by MRayermannMSFT** [comment]
Related to #985

**Comment by debchat** [comment]
Please see new ticket 1771. I encountered the same problem today. Wish we find out the root cause.
Searching in the web, I find the users are calling it the "infamous" issue. See here.

https://www.urtech.ca/2019/02/solved-azure-storage-explorer-cannot-read-property-connectionstring-of-undefined-other-troubleshooting/

**Comment by MRayermannMSFT** [comment]
Closing. In 1.10, if something gets corrupted we show a broken node now. Please open a new issue if you continue to encounter problems.
