### ISSUE TITLE
I am not able to read data from file system using databricks. Below is the error details.

### ISSUE THREAD

**Issue by Aishwaryadinde18** [microsoft/AzureStorageExplorer#1423]
{
  "message": "\"{\\n  \\\"name\\\": \\\"TypeError\\\",\\n  \\\"message\\\": \\\"Cannot read property 'graphEndpoint' of undefined\\\",\\n  \\\"stack\\\": \\\"TypeError: Cannot read property 'graphEndpoint' of undefined\\\\n    at Object.<anonymous> (C:\\\\\\\\Program Files (x86)\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\se-adls2-extension\\\\\\\\dist\\\\\\\\src\\\\\\\\Actions\\\\\\\\PathActions.js:200:60)\\\\n    at step (C:\\\\\\\\Program Files (x86)\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\tslib\\\\\\\\tslib.js:133:27)\\\\n    at Object.next (C:\\\\\\\\Program Files (x86)\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\tslib\\\\\\\\tslib.js:114:57)\\\\n    at fulfilled (C:\\\\\\\\Program Files (x86)\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\tslib\\\\\\\\tslib.js:104:62)\\\\n    at ZoneDelegate.invoke (C:\\\\\\\\Program Files (x86)\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\zone.js\\\\\\\\dist\\\\\\\\zone-node.js:242:26)\\\\n    at Zone.run (C:\\\\\\\\Program Files (x86)\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\zone.js\\\\\\\\dist\\\\\\\\zone-node.js:113:43)\\\\n    at C:\\\\\\\\Program Files (x86)\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\zone.js\\\\\\\\dist\\\\\\\\zone-node.js:535:57\\\\n    at ZoneDelegate.invokeTask (C:\\\\\\\\Program Files (x86)\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\zone.js\\\\\\\\dist\\\\\\\\zone-node.js:275:35)\\\\n    at Zone.runTask (C:\\\\\\\\Program Files (x86)\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\zone.js\\\\\\\\dist\\\\\\\\zone-node.js:151:47)\\\\n    at drainMicroTaskQueue (C:\\\\\\\\Program Files (x86)\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\zone.js\\\\\\\\dist\\\\\\\\zone-node.js:433:35)\\\\n    at <anonymous>\\\"\\n}\""
}

**Comment by MRayermannMSFT** [comment]
Hi @Aishwaryadinde18 , are you accessing the file system/container after signing in or after attaching with name and key? Thanks!

**Comment by Aishwaryadinde18** [comment]
Thanks for your reply. I figured out.


Thanks,

Aishwarya


________________________________
