### ISSUE TITLE
Miss "Copy Direct Link to Blob Container" for one new created blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1425]
**Storage Explorer Version:** 1.8.1_20190530.1
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** 4359b6f0
**Regression From:** Previous release 1.8.1

**Steps to reproduce:**
1. Expand a non-ADLS Gen2 storage account -> Blob Containers.
2. Create a new blob container -> Check its context menu.

**Expect Experience:**
"Copy Direct Link to Blob Container" & "Set Public Access Level…" display on the context menu.
![image](https://user-images.githubusercontent.com/41351993/58684468-e9b2d100-83aa-11e9-878c-0a52c3e1406f.png)

**Actual Experience:**
No "Copy Direct Link to Blob Container" & "Set Public Access Level…" display on the context menu.
![image](https://user-images.githubusercontent.com/41351993/58684482-f9321a00-83aa-11e9-9251-fb4ede32362f.png)

**More Info**
These two actions display well after refreshing Blob Containers node

**Comment by MRayermannMSFT** [comment]
@v-xianya, can you confirm whether or not the Direct Link that which was copied as in the previous version worked or not? I found some cases where although the action was offered, the link that was put on the clipboard didn't work. So for those cases, I made the action no longer visible. I believe this is one of those cases. Thanks!

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT, Thanks for your update.

We select "Copy Direct Link to Blob Container" for **one new created blob container** and paste the direct link to browser using the 1.8.1 release. It works well.

Could you share more info about those cases that the action no longer visible you've mentioned?

**Comment by MRayermannMSFT** [comment]
Ok so the cases I have are:

1. Direct link for a QA blob container that was originally from a Storage Account that was the child of a subscription. Example direct link: `storageexplorer://v=1&resourcetype=Azure.BlobContainer&resourcename=1testdest100000`
2. Direct link for a QA blob container that was originally from a Storage Account that was attached with name & key. Example direct link: `storageexplorer://v=1&resourcetype=Azure.BlobContainer&resourcename=1millionblobs`
3. Direct link for a QA blob container that was originally from a Storage Account that was attached via Connection String. Example direct link: storageexplorer://v=1&resourcetype=Azure.BlobContainer&resourcename=emptycontainer

Although all of those links open Storage Explorer, none of them result in Storage Explorer doing anything in the tree view.

**Comment by v-xianya** [comment]
Verified this issue on the build rel/1.9.0_20190626.4. 
Miss "Copy Direct Link to Blob Container" for one new created **blob container**. So we re-open it.

**More Info:**
"Copy Direct Link to Blob Container" displays well for one new created **file share/ queue/ table.**

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
