### ISSUE TITLE
Miss "Copy Direct Link to Blob container" for one Quick Access blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1426]
**Storage Explorer Version:** 1.8.1_20190530.1
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** 4359b6f0
**Regression From:** Previous release 1.8.1

**Steps to reproduce:**
1. Expand a storage account.
2. Expand Blob Containers which contains at least one blob container.
3. Select one blob container and add it to Quick Access.
3. Check the Quick Access blob container's context menu.

**Expect Experience:**

Show “Copy Direct Link to Blob Conatiner" on context menu for one Quick Access blob container.
![image](https://user-images.githubusercontent.com/41351993/58685330-f258d680-83ad-11e9-8119-3eb4e6439f58.png)

**Actual Experience:**

No “Copy Direct Link to Blob Container" shows on context menu for one Quick Access blob container.
![image](https://user-images.githubusercontent.com/41351993/58685384-203e1b00-83ae-11e9-9489-a0908a759b5c.png)

**More Info:**
This issue also reproduces for one file share & table & queue.

**Comment by MRayermannMSFT** [comment]
@v-xianya, can you confirm whether or not the Direct Link that which was copied as in the previous version worked or not? I found some cases where although the action was offered, the link that was put on the clipboard didn't work. So for those cases, I made the action no longer visible. I believe this is one of those cases. Thanks!

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT, Thanks for your update.

We select "Copy Direct Link to Blob Container" for a **Quick Access blob container** and paste the direct link to browser using the 1.8.1 release. It works well.

Could you share more info about those cases that the action no longer visible you've mentioned?

**Comment by MRayermannMSFT** [comment]
Ok so the cases I have are:

1. Direct link for a QA blob container that was originally from a Storage Account that was the child of a subscription. Example direct link: `storageexplorer://v=1&resourcetype=Azure.BlobContainer&resourcename=1testdest100000`
2. Direct link for a QA blob container that was originally from a Storage Account that was attached with name & key. Example direct link: `storageexplorer://v=1&resourcetype=Azure.BlobContainer&resourcename=1millionblobs`
3. Direct link for a QA blob container that was originally from a Storage Account that was attached via Connection String. Example direct link: `storageexplorer://v=1&resourcetype=Azure.BlobContainer&resourcename=emptycontainer`

Although all of those links open Storage Explorer, none of them result in Storage Explorer doing anything in the tree view.

Additionally, in 1.8.1, for the original blob container's in scenarios 2 and 3, a copy direct link is offered which gives links which do not work. I've also removed those for 1.9.0.

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT, 
Got it. Thanks very much for your sharing.
