### ISSUE TITLE
Promoting a snapshot shows the refresh notification when the base blob is leased

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1428]
**Storage Explorer Version:** 1.8.1_20190530.1
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** 4359b6f0
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one normal account -> Blob Containers.
2. Open one blob container -> Upload a blob to it.
3. Right click the uploaded blob -> Select 'Acquire Lease' on the context menu.
4. Create a snapshot for the same blob -> Go to Manage Snapshot editor.
5. Try to prompt the created snapshot.

**Expect Experience:**

There is no refresh notification when executing the action 'Promote Snapshot'.

**Actual Experience:**

The refresh notification shows up.
![image](https://user-images.githubusercontent.com/34729022/58687930-a1e57700-83b5-11e9-8508-39e89b8aea10.png)

**More info:**
Actually, executing the action is failed.
![image](https://user-images.githubusercontent.com/34729022/58687976-ba559180-83b5-11e9-9486-2aa39bfe72f2.png)

**Comment by v-limu** [comment]
This issue has been fixed on build [20191106.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3218228&view=logs). So we close it.
