### ISSUE TITLE
interaction_required on signin

### ISSUE THREAD

**Issue by dagr9782** [microsoft/AzureStorageExplorer#1429]
When trying to signin using corporate MFA:
{
  "message": "\"interaction_required: interaction_required\""
}

**Comment by MRayermannMSFT** [comment]
Hi @dagr9782, I assume you're getting this during the sign-in process, yes? Are you getting to this method by clicking on the "Details" for the "Unable to sign in:" activity?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
