### ISSUE TITLE
CosmosDb Stored Procedure Editor - Autosave or notify to Save before Execute

### ISSUE THREAD

**Issue by AndriyGorda** [microsoft/AzureStorageExplorer#1430]
**Storage Explorer Version**: 1.8.1
**Platform/OS**: Windows 10
**Architecture**: x64

**Bug description**
Execute experience is misleading and not up to expectations.

**Steps to Reproduce**
1. Create stored procedure, click Save.
2. Change stored procedure body, click Execute

**Expected Experience**
Modified procedure body is executed
**Actual Experience**
Previous (saved) procedure body's version is executed.
**Additional Context**
VS2017 autosaves modified file before run in this case

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
