### ISSUE TITLE
CosmosDb stored procedure editor - Need F5 working

### ISSUE THREAD

**Issue by AndriyGorda** [microsoft/AzureStorageExplorer#1432]
**Is your feature request related to a problem? Please describe.**
In terms of shortcuts I'm expecting Storage Explorer to work inline with the other MS development products.
As long as SSMS, VS and other tools use F5 to run I have the same expectation here, pressing F5 just to get to know it is still not working is annoying.

**Describe the solution you'd like**
As long as Storage Explorer is a desktop product it shall be oriented towards keyboard experience. The planned keyboard shortcuts shall be inline with well-known existing ones in the other MS products.

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
