### ISSUE TITLE
Pop up a dialog when trying to paste one SAS-attached file share 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1434]
**Storage Explorer Version:** 1.8.1_20190603.4
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** f4f98c7f
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand a storage account -> File Shares.
2. Attach one file share using SAS.
3. Right click the SAS-attached file share and select "Copy File Share" -> Paste the SAS-attached file share to a subscription-based account.
4. Check the result.

**Expect Experience:**

Paste successfully.

**Actual Experience:**

Pop up a dialog.
![image](https://user-images.githubusercontent.com/41351993/58863799-18e87b80-86e6-11e9-9f96-03b3f9ba7404.png)

**More Info**
This issue also reproduces for an attached blob container.

**Comment by MRayermannMSFT** [comment]
@v-xianya , so you're expecting to not be warned about losing properties and metadata? Can you explain what that is? As far as we know this behavior is expected.

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT We are confused about the warning message. Could you help to take a look?
1. There no metadata for one container, but the warning shows “The properties and metadata for this container…”. So it is confusing.
2. After pasting one attached container, properties and metadata of files inside the pasted container are copied successfully.

**Comment by craxal** [comment]
The dialog message is referring to the properties and metadata of the _file share_ itself, not the files. It appears that a SAS does not allow us to view the metadata of a _file share_, but we can see the metadata of _files_ in that share. That's why we have this error message. If need be, we can write a more clear message.

**Comment by MRayermannMSFT** [comment]
Closing as the message is not wrong. We can look into providing more information if customers report being confused.
