### ISSUE TITLE
The renamed item disappears on the tree view for one new created blob container

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1435]
**Storage Explorer Version:** 1.8.1_20190603.4
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** f4f98c7f
**Regression From:** Previous release 1.8.1

**Steps to reproduce:**
1. Expand one normal account -> 'Blob Containers' node.
2. Create a new blob container -> Try to rename the created blob container.
3. Check the tree view after renaming successfully.

**Expect Experience:**

The renamed blob container shows on the tree view.

**Actual Experience:**

The renamed blob container disappears on the tree view.

**More info:**

The renamed blob container shows well after refreshing the Blob Containers node.

**Comment by MRayermannMSFT** [comment]
Related: #1414

**Comment by MRayermannMSFT** [comment]
Fix merged to master.

**Comment by v-xuanzh** [comment]
This issue still reproduces on latest  master build. 
Keep closed status. And we will verify it in next build.
