### ISSUE TITLE
The confirmation dialog appears twice when deleting one leased blob container

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1439]
**Storage Explorer Version:** 1.8.1_20190605.4
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** a7b2b07e
**Regression From:** Previous release 1.8.1

**Steps to reproduce:**
1. Expand one normal account -> 'Blob Containers' node.
2. Right click one blob container -> Select 'Acquire Lease'.
3. Try to delete the leased blob container -> The confirmation dialog will pop up.
4. Click 'Yes' on the dialog.

**Expect Experience:**

It will show an error dialog indicates that the blob container cannot be deleted.
![image](https://user-images.githubusercontent.com/34729022/58944964-7a2b5000-87b5-11e9-8c9a-eb1442b7da9a.png)

**Actual Experience:**

The confirmation dialog pops up again.
![image](https://user-images.githubusercontent.com/34729022/58944990-87483f00-87b5-11e9-989d-b34bbed96544.png)

**More info:**
1. The error dialog shows well after clicking 'Yes' on the second confirmation dialog.
2. This issue doesn't reproduce on latest master build.

**Comment by MRayermannMSFT** [comment]
I don't see this repro'ing on master, and the build is from the settings branch. 

@craxal I'll move it to your milestone, and you can close it once you can confirm it is fixed there
@v-xuanzh can you confirm that it doesn't repro on master

**Comment by craxal** [comment]
Definitely a feature branch bug only. Problem here was _any_ error caught in `executeAction` was being passed to the main host when only `ProviderNotFound` errors should lead to that.
