### ISSUE TITLE
The generated SAS URI missed 'si' when attaching a blob container with access policies

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#144]
**Storage Explorer Version**: 1.1.0 RC

**Platform**:  Windows/Linux/Mac

**Architecture**:  x64

**Build Number**: 20180503.1

**Commit**: 253b437b

**Regression From**:  Works well on release 1.0.0

#### Steps to Reproduce: ####

1. Launch Storage Explorer and expand storage accounts.
2. Right click one blob container and select 'Manage Access Policies...'.
3. Add one access policy at least for the blob container.
4. Attach the blob container with SAS using the set access policy in step3.

#### Expected Experience: ####
 The blob container can be attached successfully.

#### Actual Experience: ####
The generated SAS URI missed 'si' in 'Attach with Connection String or SAS URI' dialog.
![si](https://user-images.githubusercontent.com/34729022/39619432-5639ba82-4f77-11e8-953d-a66b0486cb5b.png)

More info:
This issue doesn't reproduce for file share/queue/table.

**Comment by MRayermannMSFT** [comment]
Merged into rel branch.
