### ISSUE TITLE
The default selected item isn't 'Yes' on delete file dialog

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1440]
**Storage Explorer Version:** 1.8.1_20190606.2
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Previous release 1.8.1

**Steps to reproduce:**
1. Expand one normal account -> 'File Shares' node.
2. Open one file share which contains some files.
3. Right click one file -> Select 'Delete'.
4. Check the default selected item on the confirmation dialog.

**Expect Experience:**

The item 'Yes' is selected.

**Actual Experience:**

The item 'No' is selected.
![image](https://user-images.githubusercontent.com/34729022/59012001-e1eea300-8868-11e9-87e9-4670491fbfbf.png)

**Comment by MRayermannMSFT** [comment]
Fix merged to master.
