### ISSUE TITLE
The title of delete dialog shows 'Delete Files' when deleting directories 

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1441]
**Storage Explorer Version:** 1.8.1_20190606.2
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one normal account -> 'File Shares' node.
2. Open one file share -> Upload one directory to it.
3. Right click the uploaded directory then select 'Delete'.
4. Check the title on the confirmation dialog.

**Expect Experience:**

The title shows 'Delete Directories' on the confirmation dialog.

**Actual Experience:**

The title shows 'Delete Files' on the confirmation dialog.
![image](https://user-images.githubusercontent.com/34729022/59012122-4c9fde80-8869-11e9-84df-238a1ecc0d02.png)

**Comment by MRayermannMSFT** [comment]
Minor issue. Won't fix.
