### ISSUE TITLE
Unbale to download file from Blobstorage

### ISSUE THREAD

**Issue by sranesushant1988** [microsoft/AzureStorageExplorer#1443]
Hello Pals

Im new to Github and posting following issue which im faceing while downloading file from bolb storage.
{
  "name": "Error",
  "message": "EPERM: operation not permitted, rename 'C:\\Users\\Sushant\\Documents\\Veeam\\Archive\\Folder01.partial' -> 'C:\\Users\\Sushant\\Documents\\Veeam\\Archive\\Folder01'",
  "stack": "Error: EPERM: operation not permitted, rename 'C:\\Users\\Sushant\\Documents\\Veeam\\Archive\\Folder01.partial' -> 'C:\\Users\\Sushant\\Documents\\Veeam\\Archive\\Folder01'",
  "errno": -4048,
  "code": "EPERM",
  "syscall": "rename",
  "path": "C:\\Users\\Sushant\\Documents\\Veeam\\Archive\\Folder01.partial",
  "dest": "C:\\Users\\Sushant\\Documents\\Veeam\\Archive\\Folder01"
}

I try even on different storage it given me following error
{
  "name": "Error",
  "message": "EEXIST: file already exists, mkdir 'F:\\Veeam'",
  "stack": "Error: EEXIST: file already exists, mkdir 'F:\\Veeam'",
  "errno": -4075,
  "code": "EEXIST",
  "syscall": "mkdir",
  "path": "F:\\Veeam"
}

Need help in getting this resolved.

**Comment by jinglouMSFT** [comment]
Can you please tell us what you were trying to do that let you to the errors? 
Also, which version of Storage Explorer on what OS?  
Thanks.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
