### ISSUE TITLE
The default size of "Delete Files" dialog is too small

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1444]
**Storage Explorer Version:** 1.8.1_master_20190610.4
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Previous release(1.8.1)

**Steps to reproduce:**
1. Expand a storage account -> File Shares.
2. Create a new file share and upload a file to it.
3. Select the uploaded file and try to delete it.
4. Check the prompt dialog.

**Expect Experience:**
Pop up the "Delete Files" dialog that show messages completely.

**Actual Experience:**
The default size of "Delete Files" dialog is too small to show complete messages.
![image](https://user-images.githubusercontent.com/41351993/59180138-b6d0c000-8b96-11e9-8add-ba024c020d58.png)

**More Info:**
This issue also reproduces for one blob.

**Comment by MRayermannMSFT** [comment]
Fix merged into master.

**Comment by v-xianya** [comment]
This issue reproduces on **feature\main-host** branch 20190614.4. So we re-open it.

**Comment by craxal** [comment]
We just need to merge master into the feature branch.

**Comment by v-xianya** [comment]
Verified this issue on build feature/main-host 20190624.2. It has been fixed. So we close it.
