### ISSUE TITLE
An error occurs when selecting 'Add Message' for a queue

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1445]
**Storage Explorer Version:** 1.8.1_master_20190610.4
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Previous release(1.8.1)

**Steps to reproduce:**
1. Expand a storage account -> Queues.
2. Create a new queue and select "Add Message".

**Expect Experience:**
Pop up the "Add Message" dialog.
![image](https://user-images.githubusercontent.com/41351993/59180406-76be0d00-8b97-11e9-8d8e-2246c2865e4a.png)

**Actual Experience:**
Pop up an error dialog.
![image](https://user-images.githubusercontent.com/41351993/59180426-85a4bf80-8b97-11e9-8246-61590b7b78b8.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into master.

**Comment by v-xianya** [comment]
This issue reproduces on **feature\main-host** branch 20190614.4. So we re-open it.

**Comment by craxal** [comment]
We just need to merge master into the feature branch.

**Comment by v-xianya** [comment]
Verified this issue on build feature/main-host 20190624.2. It has been fixed. So we close it.
