### ISSUE TITLE
Azure Account "Remove" Button Hidden Under Long Domain Name

### ISSUE THREAD

**Issue by rrmistry** [microsoft/AzureStorageExplorer#1447]
**Storage Explorer Version**: 1.8.1
**Build Number**: 20190510.6
**Platform/OS**: Windows
**Architecture**: ia32
**Regression From**:  
**Commit**: 947fc741

## Bug Description ##
The "Remove" button on the Azure Subscription Account Management is hidden under a long domain name:
![Remove Account Button](https://user-images.githubusercontent.com/25514145/59220736-aff47e00-8b93-11e9-90bb-a01da273d7f7.gif)

## Expected Experience ##
The domain name for Azure Subscription should not overlap the "Remove" account button. And should be easily accessible.

Thank you,

**Comment by MRayermannMSFT** [comment]
Hi @rrmistry thanks for the bug report. We'll work on getting this fixed, but in the meantime you should be able to use your tab key to access the Remove link.

**Comment by MRayermannMSFT** [comment]
Fix checked into master. Thanks again for the bug report @rrmistry!
![1447](https://user-images.githubusercontent.com/21112697/69077837-64b88400-09eb-11ea-835f-aec077f27a0b.gif)
