### ISSUE TITLE
The pasted URL is removed after changing the Resource type to Blob Container(ADLS Gen2) on 'Connect' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1448]
**Storage Explorer Version:** 1.8.1_master_20190610.4
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Give RBAC access to a container to a user like 'Blob Data Owner Role'.
2. Open Connect dialog -> Select 'Add a resource via RBAC'.
3. On the second page, choose the account with access to the resource and the subscription that the resource is in.
4. On the third page, paste a URL to the container -> Change the resource type from  'Blob Container' to 'Blob Container(ADLS Gen2)'
5. Check the result.

**Expect Experience:**

The pasted URL still shows well.

**Actual Experience:**

The pasted URL is removed.
![image](https://user-images.githubusercontent.com/34729022/59256260-2b266480-8c66-11e9-962c-66b69596dbf0.png)

**More info:**
This issue doesn't reproduce when changing the resource type from 'Blob Containers(ADLS Gen2)' to 'Blob Container'.

**Comment by MRayermannMSFT** [comment]
This is by design. They are different inputs.

**Comment by v-xuanzh** [comment]
Hi @MRayermannMSFT ，Just want to confirm 1 question with you.

The container URL isn't removed when changing the resource type from '**Blob Container(ADLS Gen2)**' to '**Blob Container'**, Is it expected?
