### ISSUE TITLE
'AccessTierChangeTime' is truncated in blob 'Properties' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#145]
**Storage Explorer Version**: 1.1.0 RC

**Platform**: Windows/Linux/Mac

**Architecture**: x64

**Build Number**: 20180503.1

**Commit**: 253b437b

**Regression From**: Not a regression

#### Steps to Reproduce: ####

1. Launch Storage Explorer and expand storage accounts.
2. Open one blob container and upload a blob to it.
3. Right click the uploaded blob then select 'Properties...'.

#### Expected Experience: ####
'AccessTierChangeTime' displays well in the default dialog size.

#### Actual Experience: ####

'AccessTierChangeTime' is truncated in the default dialog size.
![truncated](https://user-images.githubusercontent.com/34729022/39619651-2b2fefd6-4f78-11e8-904e-000cc2ba5976.png)

**Comment by MRayermannMSFT** [comment]
Fix was merged into master for 1.3.0
