### ISSUE TITLE
Creating folder with a starting dot results in dot being removed

### ISSUE THREAD

**Issue by jpda** [microsoft/AzureStorageExplorer#1451]
**Storage Explorer Version**: 1.8.1
**Build Number**: 20190510.6
**Platform/OS**: Windows 10 x64
**Architecture**: ia32
**Regression From**: unknown

## Bug Description ##
When creating a folder in a container, then uploading a file into that folder, if the folder name starts with a dot, the dot is removed after refresh.

## Steps to Reproduce ##
1. Create/acquire a storage account, if necessary
2. Go to blob containers
3. Create a container, if necessary
4. Add folder named `.well-known` (or anything starting with a dot)
5. Note that folder name appears with dot in the address bar
6. Drag file to upload
7. 'Your view may be out of date. Do you want to refresh?' - YES
8. 'No data in this blob container'
9. Navigate back to root container
10. Note that folder exists (along with file), but without dot - e.g., `.well-known` becomes `well-known`

## Expected Experience ##
Expected folder name to include dot `.`

## Actual Experience ##
Folder created but without dot `.`

## Additional Context ##
From the Azure Portal, uploading a file and including a folder/path works fine, so the service definitely supports it.

If you use the 'Upload' button/dialog to upload the file, the folder is pre-populated, but missing the dot. If you add the dot manually in the dialog, the upload succeeds to the correct folder (including the dot) - see below.

![image](https://user-images.githubusercontent.com/5932293/59281545-7411f500-8c35-11e9-9929-7f6ec17b837f.png)

![image](https://user-images.githubusercontent.com/5932293/59281486-5d6b9e00-8c35-11e9-9ad2-b96e7d0bbf63.png)

![image](https://user-images.githubusercontent.com/5932293/59281466-53499f80-8c35-11e9-8cc6-f6050c542a77.png)

**Comment by JasonYeMSFT** [comment]
Hi, it seems that this bug only occurs when you have azcopy enabled. If you disable azcopy, the upload will work as expected. We will make a fix for the this bug soon.

**Comment by v-xianya** [comment]
Verified this issue on build master/20190702.3. It has been fixed. So we close it.
