### ISSUE TITLE
Allow to copy Azure Blob to ADL

### ISSUE THREAD

**Issue by fsetdeveloper** [microsoft/AzureStorageExplorer#1452]
Please allow copy from Blob to ADL from UI.
May be you can implement ADLCopy behind the scene, but working with ADL has been painful.
I need to download to local folder, then reupload, as ADLCopy sometime not working (always busy)

**Comment by MRayermannMSFT** [comment]
For now yes, you need to download and then reupload. We do recommend trying to move to ADLS Gen2 though.
