### ISSUE TITLE
Missing st and se field in SAS token generated by Browser Storage Explorer (Preview)

### ISSUE THREAD

**Issue by gwh-cpnet** [microsoft/AzureStorageExplorer#1453]
**Storage Explorer Version**: browser version in azure portal
**Build Number**: 
**Platform/OS**: Browser
**Architecture**: 
**Regression From**:  

## Bug Description ##
The SAS url generated by browser storage explorer is invalid for at least 24 hours.

## Steps to Reproduce ##
Go to Storage Explorer (preview) on browser, generate a SAS url on a blob resource
it would look like 
```
https://xxx.blob.core.windows.net/yyy/zzz.tar.gz?sv=2018-03-28&sig=QqSHQfCTiP%2BlIcaEdRVh4BIeSYAyODspROSCny7NIkE%3D&sr=b
```

## Expected Experience ##
The url generated should look like the one generated by the app, 
```
https://xxx.blob.core.windows.net/yyy/zzz.gz?st=2019-06-12T04%3A25%3A36Z&se=2019-06-13T04%3A25%3A36Z&sp=rl&sv=2018-03-28&sr=b&sig=QbN3Qo%2BZk3RKe%2Frx1WPaHbtKdW96Es3qDsJxqF7o9uU%3D
```

This one works fine. You see, `st` and `se` fields are missed in the browser version.

I just noticed this problem about 12 hours ago. Before the browser version works fine. My main work station runs Linux, so I use the browser version all the time.

**Comment by craxal** [comment]
We don't manage anything in the Azure Portal. This is just for the standalone Storage Explorer desktop application. We'll reach out to them.

**Comment by gwh-cpnet** [comment]
@craxal At least, can you confirm this issue? Until today, the bug is still there.

**Comment by gwh-cpnet** [comment]
it looks like this bug is fixed for now.
