### ISSUE TITLE
Sign-in continuously reprompts when account is associated with multiple tenants (via B2B)

### ISSUE THREAD

**Issue by lesterw1** [microsoft/AzureStorageExplorer#1454]
**Storage Explorer Version**: 1.8.1
**Build Number**: 20190510.6
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  somewhere prior to v1.7.0

## Bug Description ##
I am unable to sign-in with Storage Explorer v1.8.1. The issue is that the Sign In... continuously repeats itself. This issue has been around since v1.7.0 (and possibly earlier) and appears to be related to the fact that my account is also a B2B guest account in another tenant. The other tenant's logo briefly pops up after signing into the primary tenant. It seems that Storage Explorer gets confused in this case.

Previously, you could sign in and then break out by clicking cancel after the second or third time repeating the sign-in and Storage Explorer would then populate the list of resources available. But this work-around has stopped working. Now I cannot sign in at all.

This sign-in issue ONLY happens when using Storage Explorer. If there is some advanced debug logging that can be turned on, I am happy to do so.

## Steps to Reproduce ##
I suspect that the problem relates to having an Azure account which is also a B2B guest account in another tenant (or in multiple tenants).  I have not tried this with a new account to confirm but watching the login sequence, I briefly see the icon for the secondary tenant during the Storage Explorer Sign-In sequence.

To reproduce, I suggest adding an account from one tenant as a Guest to another tenant. 

## Expected Experience ##
Sign-in should not continuously re-prompt.

## Actual Experience ##
Sign-in continuously re-prompts.  In previous versions, you could break out of the infinite sign-in loop and then all of the subscriptions would appear. This work-around stopped in v1.8.1.

## Additional Context ##
The account needs to be associated with multiple tenants.

**Comment by lesterw1** [comment]
**RESOLVED**. In looking at the error log within the "more information..." of Storage Explorer, I noticed that it was attempting to use a proxy server, despite having the Storage Explorer proxy setting to "None" AND have the Internet Options proxy setting also disabled.

It turns out that our IT department sets the HTTP_PROXY and HTTPS_PROXY environment variables as defaults. When Storage Explorer runs, it picks up this proxy setting and uses is, despite its own setting being "None".

RECOMMENDATION: Add a 3rd Radio button to the Proxy Setting which is "Use default proxy settings" which will then - and only then - pick up either the Internet Options proxy setting or (if that isn't set), the HTTP_PROXY and HTTPS_PROXY environment settings.

**Comment by lesterw1** [comment]
Closing as duplicate of [https://github.com/microsoft/AzureStorageExplorer/issues/1139](https://github.com/microsoft/AzureStorageExplorer/issues/1139)

**Comment by craxal** [comment]
See #1534 for tracking default/system proxy settings.
