### ISSUE TITLE
Trying to upload file with the same name as one existing gives an error when using AzCopy

### ISSUE THREAD

**Issue by andre-ss6** [microsoft/AzureStorageExplorer#1455]
**Storage Explorer Version**: 1.8.1
**Build Number**: 20190510.6
**Platform/OS**: Windows 10 1903
**Architecture**: x64
**Regression From**:  Not sure

## Bug Description ##
As title says. Error shown: 

> Transfer of '[redacted]\web.7z' to 'release/[redacted]' skipped (used SAS)

## Steps to Reproduce ##
- Enable AzCopy
- Upload a file to a blob container
- Try to upload the same file again

## Expected Experience ##
Conflict window is shown

## Actual Experience ##
Error message is shown.

**Comment by MRayermannMSFT** [comment]
Hey @andre-ss6 , bringing up a conflict dialog mid upload is on our backlog for upload. Currently you need to click on "View failed transfers". From there you can choose to retry with overwrite enabled or disabled. Let us know if this unblocks you. Thanks!

**Comment by schellem** [comment]
Very, very annoying feature

**Comment by jinglouMSFT** [comment]
@schellem Not sure which "feature" you referred to?  Using AzCopy or the current behavior for conflict resolution when AzCopy is enabled? If for conflict resolution, we are working with AzCopy for a better solution as mRayermannMSFT mentioned above.  If you referred to AzCopy in general, could you be a bit more specific so we can try to act on it/them?  Thanks.

**Comment by schellem** [comment]
@jinglouMSFT , I'm not sure what you are asking.
I use Azure Storage Explorer to copy a file that already exists into a storage account. You just see an error in the bottom pane that is meaningless, only if you open the error do you see that it was not really an error. It's a failure in the app to tell or simply allow me me to overwrite an existing file. 

File utility applications with overwrite warnings and settings to ignore overwrite prompts have been around for many, many years. 

It's very annoying that ASE just quits and calls this an error that doesn't tell me the real reason without further action.

**Comment by jinglouMSFT** [comment]
OK. I understood the issue from your description.  When you have AzCopy enabled (from the Preview menu), the current conflict resolution is the error you saw. This is due to a limitation in AzCopy which we are working with the AzCopy team to solve as MRayermannMSFT mentioned above.  If you are copying a small amount of files or smaller files and would like to have the usual overwrite experience, you can turn off AzCopy (from the Preview menu), and you will have the familiar experience you expected.
