### ISSUE TITLE
The provided connection string does not have complete configuration settings.

### ISSUE THREAD

**Issue by davidrpk** [microsoft/AzureStorageExplorer#1457]
**Storage Explorer Version**: 1.8.1
**Build Number**: 20190510.6
**Platform/OS**: Windows
**Architecture**: ia32
**Regression From**:  Unknown

## Bug Description ##
Unable to delete folders with container-level permissions applied. The following error occurs: NoMatchError: The provided connection string does not have complete configuration settings.

## Steps to Reproduce ##
The user account is connected to Azure Storage using Azure Account credentials.

A user account has the following roles:
"Storage Blob Data Owner" applied at the container level
"Reader" applied at the storage account level

This should allow read/write/delete access to blobs within the specified container.

In Azure Storage Explorer, blobs can be read, written and deleted. But when a folder is selected to be deleted the following error occurs: NoMatchError: The provided connection string does not have complete configuration settings.

## Expected Experience ##
The folder should be deleted with no error.

## Actual Experience ##
The following error is captured in Azure Storage Explorer.

```
{
  "name": "NoMatchError",
  "message": "The provided connection string \"DefaultEndpointsProtocol=https;AccountName=storageaccountname;BlobEndpoint=https://storageaccountname.blob.core.windows.net/;QueueEndpoint=https://storageaccountname.queue.core.windows.net/;TableEndpoint=https://storageaccountname.table.core.windows.net/;FileEndpoint=https://storageaccountname.file.core.windows.net/;\" does not have complete configuration settings.",
  "stack": "NoMatchError: The provided connection string \"DefaultEndpointsProtocol=https;AccountName=storageaccountname;BlobEndpoint=https://storageaccountname.blob.core.windows.net/;QueueEndpoint=https://storageaccountname.queue.core.windows.net/;TableEndpoint=https://storageaccountname.table.core.windows.net/;FileEndpoint=https://storageaccountname.file.core.windows.net/;\" does not have complete configuration settings.\n    at Object.captureStackTrace (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\errors\\errors.js:23:11)\n    at new NoMatchError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\servicesettings.js:32:10)\n    at Object.exports.noMatchConnectionString (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\servicesettings.js:49:9)\n    at Function.StorageServiceSettings.createFromConnectionString (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageservicesettings.js:129:23)\n    at Function.StorageServiceClient.getStorageSettings (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:919:53)\n    at new BlobService (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\services\\blob\\blobservice.core.js:103:53)\n    at Object.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\Azure\\AzureStorage\\Blobs\\BlobUtilities.js:181:35)\n    at step (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:133:27)\n    at Object.next (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:114:57)\n    at fulfilled (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:104:62)"
}
```

## Additional Context ##
Using network proxy with corporate SSL certificates installed. No other issues have be observed with the setup.

**Comment by craxal** [comment]
First of all, thank you for providing a thorough bug report. That helps us immensely! 😃

It's likely Storage Explorer is trying to use the connection string to connect instead of your Azure credentials. And since the connection string is lacking a key or SAS token, the request to Azure would expectedly fail.

If you click on your account node and look through the Properties section below, do you see your account keys? Also, what kind of blob storage are you trying to delete folders from (Standard, Premium, Cold, ADLS Gen 2, etc.)?

**Comment by davidrpk** [comment]
Thanks for the quick reply.
On the account node the keys are showing as "Error loading property" and the connection strings do not contain a key or SAS token.

The account is: StorageV2, Standard Tier with Hot access. ADLS Gen 2 is disabled. Let me know if there is anything else that might be relevant.

**Comment by craxal** [comment]
OK, that's expected for RBAC connections. Did some digging and found we missed RBAC support for deleting folders. That's likely because folder deletion follows a different code path than single item deleting. Does deleting a single item in the folder work as expected?

**Comment by davidrpk** [comment]
Deleting a single item in the folder does work as expected, along with standard read/write access. I can also create folders.

**Comment by craxal** [comment]
Good. Deleting folders should be fixed for the next release already. We'll verify to be sure.
