### ISSUE TITLE
Keep a consistent icon between prompts of "Dequeue Message" and "Clear Queue"

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1458]
**Storage Explorer Version:** 1.8.1_master_20190613.5
**Platform/OS:** Windows 10/ Linux Ubuntu
**Architecture:** ia32/x64
**Commit:** bc3a9ae7
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand a storage account -> Queues.
2. Create a new queue and add one message to it.
3. Select button "Dequeue Message" and "Clear Queue" separately.
4. Check the prompts.

**Expect Experience:**
The icon of the two prompts is consistent.

**Actual Experience**
The icon of the two prompts is inconsistent.
![image](https://user-images.githubusercontent.com/41351993/59414857-f268c580-8df4-11e9-9b78-7e23ff3e0a3a.png)

**Comment by v-xuanzh** [comment]
This issue has been fixed on the latest build 20190806.12. So we closed it.
