### ISSUE TITLE
Support "Cut and Paste" for Blobs and File Shares

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#146]
**Storage Explorer Version**: 1.1.0 RC

**Platform**: Windows/Linux/Mac

**Architecture**: x64

**Build Number**: 20180503.1

**Commit**: 253b437b

**Regression From**: Not a regression

#### Steps to Reproduce: ####

1. Launch Storage Explorer and expand storage accounts. 
2. Open one blob container and upload a blob to it. 
3. Select the blob and press 'Ctrl+X'.
4. Check whether the 'Paste' button is enabled or not.

#### Expected Experience: ####
'Paste' is enabled.

#### Actual Experience: ####
 
'Paste' is disabled.

**Comment by MRayermannMSFT** [comment]
Closing as won't fix. You can accomplish the same task by copy, pasting, then deleting.

**Comment by Ginginho** [comment]
@MRayermannMSFT Hi Matthew. That's an unsympathetic take on things. Imagine a need to move 101 out of 200 files from one folder to another. Sure I can select those 101 files twice, once for the copy and once for the delete. Seems a bit poor though, wouldn't you agree? Could MSFT not take the view that it would improve the Storage Explorer UI with relative ease?
