### ISSUE TITLE
Give an error when try to lease one blob which is assigned read permission

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1461]
**Storage Explorer Version:** 1.8.1_master_20190613.5
**Platform/OS:** Windows 10/ Linux Ubuntu/macOS High Sierra
**Architecture:** ia32/x64
**Commit:** bc3a9ae7
**Regression From:** Not a regression

**Steps to reproduce:**
1. Attach one blob container with SAS given Read & List permission.
2. Open the attached blob container then try to lease a blob.
3. Check the result.

**Expect Experience:**

There shows an error that indicates this request is not authorized to perform using this permission.

**Actual Experience:**

Nothing happens.

**Comment by MRayermannMSFT** [comment]
If this gets moved to another milestone again, just won't fix unless customers request a fix.

**Comment by JasonYeMSFT** [comment]
This is by design.
