### ISSUE TITLE
keep consistent between the link "Choose Columns…" and the prompt dialog's title

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1462]
**Storage Explorer Version:** 1.8.1_master_20190614.7
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** bc3a9ae7
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand a storage account -> Tables.
2. Select one table -> Select "Query" button -> Click "Advanced Options" -> Click "Choose Columns...".
3. Check the prompt dialog's title.

**Expect Experience:**
It is consistent between the link "Choose Columns…" and the prompt dialog's title.

**Actual Experience:**
It is inconsistent between the link "Choose Columns…" and the prompt dialog's title.
![image](https://user-images.githubusercontent.com/41351993/59489907-ff99b900-8eb5-11e9-99d5-eebb31404eb1.png)

**Comment by MRayermannMSFT** [comment]
Go with select columns everywhere!

**Comment by MRayermannMSFT** [comment]
Package just needs updating.

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
