### ISSUE TITLE
Clicking "Cancel" doesn't do anything when trying to open a large blob

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1464]
**Storage Explorer Version:** 1.8.1_**master**_20190614.7
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** bc3a9ae7
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand a storage account -> Blob Containers.
2. Create a new blob container -> Upload a large blob like 7 GB.
3. Try to open it.
4. Click "Cancel" when it starts to download the blob.

**Expect Experience:**

The downloading activity can be cancelled successfully.

**Actual Experience:**

Nothing happens after clicking "Cancel".
![image](https://user-images.githubusercontent.com/41351993/59490400-25738d80-8eb7-11e9-9bee-2595b905bac1.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
