### ISSUE TITLE
Hide the actions don't work for RBAC attached containers

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1465]
**Storage Explorer Version:** 1.8.1_**feature/main-host**_20190614.4
**Platform/OS:** macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Give RBAC access to a container to a user like '**Blob Data Owner Role**'.
2. Attach the blob container via RBAC.
3. Expand 'Local & Attached' -> Storage Accounts -> (Attached Containers).
4. Right click the attached blob container -> Check the context menu.

**Expect Experience:**

These actions don't work for RBAC attached containers are hidden.

**Actual Experience:**

These actions don't work for RBAC attached containers are disabled(Rename/Copy Blob Container/Get Shared Access Signature...).
![image](https://user-images.githubusercontent.com/34729022/59494203-417b2d00-8ebf-11e9-8a58-61116fb0175a.png)

**More info:**
This issue doesn't reproduce for **master** branch.

**Comment by craxal** [comment]
Fixed after merging master.
