### ISSUE TITLE
An error occurs when trying to lease one blob container

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1466]
**Storage Explorer Version:** 1.8.1_**feature/main-host**_20190614.4
**Platform/OS:** macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Previous release(1.8.1)

**Steps to reproduce:**
1. Expand one normal storage account -> 'Blob Containers' node.
2. Right click one blob container -> Select 'Acquire Lease' -> Click 'Yes' on the popped confirmation dialog.
3. Check the result.

**Expect Experience:**

The selected blob container is leased successfully.

**Actual Experience:**

An error occurs.
![image](https://user-images.githubusercontent.com/34729022/59494458-c2d2bf80-8ebf-11e9-814b-93cd6fed0d89.png)

**More info:**

1. This issue doesn't reproduce for **master** branch.
2. This issue doesn't reproduce when trying to lease blobs.

**Comment by v-xianya** [comment]
Verified this issue on the build feature/main-host 20190624.2. It has been fixed. So we close it.
