### ISSUE TITLE
Miss three settings on Connection Summary page of Connect dialog when attaching one container with RBAC

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1467]
**Storage Explorer Version:** 1.8.1
**Branch**: feature/main-host
**Build**: 20190614.4
**Platform/OS:** macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Give RBAC access to a container to a user like '**Blob Data Owner Role**'.
2. Copy a URL of one blob container -> Open Connect dialog -> Select 'Add a resource via RBAC'.
3. On the second page, choose the account with access to the resource and the subscription that the resource is in.
4. On the third page, paste a URL to the container -> 'Next'.
5. Check the summary on the last page.

**Expect Experience:**

There shows five settings on the last page of Connect dialog.

**Actual Experience:**

There misses three settings on the last page of Connect dialog.
![image](https://user-images.githubusercontent.com/34729022/59494912-c74ba800-8ec0-11e9-8748-3c8a4442f2ce.png)

**More info:**

This issue doesn't reproduce on **master** branch.

**Comment by craxal** [comment]
Fixed after merging master.
