### ISSUE TITLE
Unable to see the toolbar buttons after closing one dialog from query builder of a large table

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1468]
**Storage Explorer Version:** 1.8.1_**master**_20190614.7
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** bc3a9ae7
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> 'Tables' node.
2. Open one large table -> Click 'Query' button.
3. On the opened query builder editor, click anyone buttons to open one dialog(Add/Edit/Column Options).
4. Close the opened dialog directly -> Check the toolbar buttons.

**Expect Experience:**

Able to see the toolbar buttons.

**Actual Experience:**

Unable to see the toolbar buttons.
![image](https://user-images.githubusercontent.com/34729022/59493795-51464180-8ebe-11e9-989e-d17a4873ce7c.png)

**Comment by MRayermannMSFT** [comment]
Closing as won't fix. Can address it if customers run into it. You can also just resize window to fix the issue.
