### ISSUE TITLE
self signed certificate in certificate chain

### ISSUE THREAD

**Issue by GY000** [microsoft/AzureStorageExplorer#1469]
{
  "name": "Error",
  "message": "self signed certificate in certificate chain",
  "stack": "Error: self signed certificate in certificate chain\n    at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)\n    at emitNone (events.js:106:13)\n    at TLSSocket.emit (events.js:208:7)\n    at TLSSocket._finishInit (_tls_wrap.js:637:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38)",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}

**Comment by MRayermannMSFT** [comment]
Hi @GY000 , have you looked at our troubleshooting guide for this issue?

https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=1804#error-self-signed-certificate-in-certificate-chain-and-similar-errors

**Comment by GY000** [comment]
> Hi @GY000 , have you looked at our troubleshooting guide for this issue?
> 
> https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=1804#error-self-signed-certificate-in-certificate-chain-and-similar-errors

hi, I did look through that but it doest work too.
However, I managed to solve it by keep trying to upload that failed file.
