### ISSUE TITLE
Unable to browse Azure File Share

### ISSUE THREAD

**Issue by gabe-c** [microsoft/AzureStorageExplorer#1471]
Storage Explorer Version: 1.8.1
Build Number: 20190510.6
Platform/OS: Windows 7 Enterprise
Architecture: x64

## Bug Description ##
Experiencing issues with being unable to open an Azure File Share and with Loading status that doesn't complete. I was able to open it twice, though. But it doesn't work consistently. I suspect issues with our corporate proxy servers. Proxy config is not set and set as default as WebSense allows to set the initial storage account authentication. 

## Steps to Reproduce ##
1. Expand storage account using a connection established with storage account name and key. 
2. Select File Shares to browse a share but most of the time it stalls in loading and times out with error, "Unable to retrieve child resources. Details: This request is not authorized to perform this operation..."

**Comment by MRayermannMSFT** [comment]
Hi @gabe-c, what is WebSense? I'm asking because Storage Explorer does not use your system proxy settings. You need to set those manually via the Edit -> Proxy Settings menu item. Loading the system settings by default is on our backlog though.

**Comment by MRayermannMSFT** [comment]
Also, the error you're getting is what we display when Azure gives us a permission error. Do you know if you have access to your storage account keys? Since File Shares has not yet implemented RBAC, you still need to be able to list those to use File Shares. To check, you can click on your storage account and then look in the properties panel for them:
![image](https://user-images.githubusercontent.com/21112697/59788099-dc895380-927f-11e9-9fae-57ddfcca6ee9.png)

**Comment by gabe-c** [comment]
Hi, WebSense is a proxy agent. I did try to manually set the proxy address and port and it doesn't seem to like my settings. We use that address and port in other apps and works fine. 

I do see full access under permissions:  
![image](https://user-images.githubusercontent.com/51932817/59788770-b072d000-9289-11e9-8b73-c289b2121b0e.png)

I can attempt to connect with an Azure account instead of storage account and primary key and see what happens?

**Comment by gabe-c** [comment]
Can any of these console errors help in troubleshooting?

![image](https://user-images.githubusercontent.com/51932817/59797456-f1c0ab00-929c-11e9-8347-1243b686d2bc.png)

**Comment by gabe-c** [comment]
Switched to using Storage Explorer Preview from the Azure Portal. Issues were more than likely our security systems introspection SSL traffic etc.
