### ISSUE TITLE
An extra action 'Copy Direct Link to Blob Container' shows on the context menu of blob containers

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1472]
**Storage Explorer Version:** 1..1_**master**_20190618.3
**Platform/OS:** Ubuntu 18.04
**Architecture:** x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one normal storage account -> 'Blob Containers' node.
2. Right click one blob container -> Check the context menu.

**Expect Experience:**

No 'Copy Direct Link to Blob Container' action shows on the context menu.

**Actual Experience:**

An extra action 'Copy Direct Link to Blob Container' shows on the context menu.
![image](https://user-images.githubusercontent.com/34729022/59665526-a5fefa80-91e5-11e9-961c-9caa8e0b7767.png)

**Comment by MRayermannMSFT** [comment]
@v-xuanzh, why do you not expect a direct link action?

**Comment by craxal** [comment]
Agreed with @MRayermannMSFT. This appears to be as designed.

**Comment by v-xuanzh** [comment]
Hi @MRayermannMSFT @craxal ,

This action only appears for **blob containers** like the screenshot. But it doesn't appear for **file shares/queues/tables and a storage account** on Linux. So we think it is not expected?

**Comment by MRayermannMSFT** [comment]
Craig merged a fix into master.
