### ISSUE TITLE
Update "Blob Type" to "Blob type" on the upload dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1477]
**Storage Explorer Version:** 1.8.1_master_20190619.4
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** 952cf5dc
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch storage explorer -> Go to Preview -> Check 'Use AzCopy for Improved Blob Upload and Download'.
2. Expand a non-ADLS Gen2 storage account -> Blob Containers.
3. Create a new blob container -> Click 'Upload' then select 'Upload Folder...'.
4. Check the prompt dialog.

**Expect Experience:**
Display 'Blob type' on the prompt dialog.

**Actual Experience:**
Display 'Blob Type' on the prompt dialog.
![image](https://user-images.githubusercontent.com/41351993/59749519-be3b4c00-92af-11e9-80af-3e44171a329d.png)

**Comment by jinglouMSFT** [comment]
Fix in PR.

**Comment by v-xuanzh** [comment]
This issue still reproduces on the Upload dialog with the AzCopy enabled.
![image](https://user-images.githubusercontent.com/34729022/61694438-02fd4b80-ad64-11e9-9c08-3826ba8ed166.png)

**Comment by v-xianya** [comment]
This issue has been fixed on build master/20190724.6. So we close it.
