### ISSUE TITLE
The blob container named '$logs' appears after enabling the soft delete policy

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1478]
**Storage Explorer Version:** 1.8.1_master_20190619.4
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** 952cf5dc
**Regression From:** Not a regression

**Steps to reproduce:**
1. Create a storage account with ADLS Gen2 disabled.
2. Expand the created account -> Right click 'Blob Containers' node then select 'Configure Soft Delete Policy...'.
3. Enable soft delete -> Refresh 'Blob Containers' node of the same account.

**Expect Experience:**

No extra blob container shows under the 'Blob Containers' node after enabling soft delete.

**Actual Experience:**

There shows an blob container named '$logs' under the 'Blob Containers' node.
![image](https://user-images.githubusercontent.com/34729022/59754999-c8624800-92b9-11e9-9e7d-7d6419594909.png)

**More info:**

1. Actually, we cannot create a blob container starting with $.
2. The generated blob container '$logs' is empty.

**Comment by MRayermannMSFT** [comment]
This is a known side effect of turning on soft delete. Closing as by-design.
