### ISSUE TITLE
Show 'Edit Property Value' rather than 'Edit Entity Value'

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1479]
**Storage Explorer Version:** 1.8.1_master_20190619.4
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** 952cf5dc
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one account -> 'Tables' node.
2. Open one table -> Click 'Add' button to add an entity.
3. Click 'Add Property' on the opened 'Add Entity' dialog.
4. Click 'Edit Property' next to the added property.
5. Check title of the second page of the 'Add Entity' dialog.

**Expect Experience:**

There shows '**Edit Property Value**' on the second page of the 'Add Entity' dialog.

**Actual Experience:**

There shows '**Edit Entity Value**' on the second page of the 'Add Entity' dialog.
![image](https://user-images.githubusercontent.com/34729022/59756081-a36ed480-92bb-11e9-8021-270018c2ab53.png)

**Comment by jinglouMSFT** [comment]
Fix should be in the daily build now.

**Comment by v-xuanzh** [comment]
This issue has been fixed on latest master build 20190709.5. So closed it.

**Comment by v-xuanzh** [comment]
This issue reproduces on main/host build 20190709.6. So reopened it.

**Comment by v-xuanzh** [comment]
This issue has been fixed on feature/main-host build 20190711.2. So closed it.
