### ISSUE TITLE
An error icon is displayed to the user when there is no error

### ISSUE THREAD

**Issue by Liversage** [Microsoft/AzureStorageExplorer#148]
**Storage Explorer Version**:  1.0.0

**Platform**: Windows

When I delete a row in an Azure table or the table itself etc. then Azure Storage Explorer will display a message box asking me if I'm sure I want to perform the operation. In this dialog box an icon is displayed:

![Dialog box with error icon displayed to prompt the user](https://user-images.githubusercontent.com/3593901/39630744-8e18257c-4fb0-11e8-91b5-0f329d19565e.png)

With reference to [Standard Icons](https://msdn.microsoft.com/en-us/library/windows/desktop/dn742488(v=vs.85).aspx) in *Design basics for Desktop applications* in the *Windows Dev Center* the icon displayed is an **Error icon**.

(I know that Azure Storage Explorer doesn't have to follow these design guidelines for Windows applications but in my opinion following these guidelines generally lead to a better user experience. And if for some reason the Azure Storage Explorer team decides to not follow these guidelines you can record that fact in this issue.)

According to the guidelines the error icon should be used for the following message type:

> An error or problem that has occurred.

The discussion in the **Avoid overwarning** section is also relevant even though is about overuse of the warning icon and not the error icon:

> The typical Windows program has warning icons seemingly everywhere, warning about things that have little significance. In some programs, nearly every question is presented as a warning. Overwarning makes using a program feel like a hazardous activity, and it detracts from truly significant issues.

Asking me if it is OK to delete something is not an error. The application should either warn or inform me that the operation cannot be undone and not make me feel that I'm doing some kind of hazardous activity.

**Comment by craxal** [comment]
Yeah, we've noticed this before. We just used the wrong icon. We're on it!

**Comment by MRayermannMSFT** [comment]
PR is ready.
![image](https://user-images.githubusercontent.com/21112697/39640422-c8f24e6a-4f7f-11e8-93fe-85eece29cab9.png)

**Comment by MRayermannMSFT** [comment]
Merged into rel branch!

**Comment by Liversage** [comment]
After installing 1.1.0 I saw to my delight that this issue was resolved. However, while my report used deleting rows in Azure tables as an example I really intended the issue to be about the overuse of the error icon in general. Apparently, this issue was resolved by only changing the icon used when deleting a row in an Azure table but there are many other places in the app when - at least according to my opinion - you use the error icon when you should either use no icon or only use a warning icon because there is no error.

I'm certainly no master of UX so I tend to follow guidelines set forth by people smarter than me and based on the document I quoted in the original issue I would get rid of the icon all together for "minor" destructive operations, use the warning icon for "major" destructive operations and reserve the error icon for error conditions.

I noticed that the error and warning icons have distinct sounds and I'm sure "no icon" has no sound so you might also take that into consideration when designing the UX.

**Comment by MRayermannMSFT** [comment]
Hey @Liversage , thankfully I think we were on the same page about the point of your issue. While I didn't go looking for every system error/warning dialog we pop up to see if the icon was correct/the right level, I have been keeping my eye out when making changes and reviewing other people's changes. In fact, just last week I changed the icon for the clear queue icon to be warning instead of error. 😃
