### ISSUE TITLE
Add ... next to the 'Break Lease' on the blob context menu of blob

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1480]
**Storage Explorer Version:** 1.8.1_master_20190619.4
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** 952cf5dc
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one normal account ->'Blob Containers' node.
2. Open one blob container which container one blob at least.
3. Right click one blob then check the context menu.

**Expect Experience:**

There shows 'Break Lease...' on the blob context menu.

**Actual Experience:**

There shows 'Break Lease' on the blob context menu.
![image](https://user-images.githubusercontent.com/34729022/59756422-4293cc00-92bc-11e9-9e31-8bb06d9e526d.png)

**Comment by jinglouMSFT** [comment]
Fix in PR

**Comment by v-xuanzh** [comment]
This issue has been fixed on the latest master build 20190724.6. So closed it.
