### ISSUE TITLE
Failed to delete or update blob file into a container

### ISSUE THREAD

**Issue by bortolotti** [microsoft/AzureStorageExplorer#1483]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:

**Comment by craxal** [comment]
@bortolotti Can you please provide:
- Storage Explorer version
- Platform and architecture
- Steps you took that will help us reproduce the problem
- Include details of how you are connected to your blob container (sign-in with RBAC, attached with account key, attached with SAS, etc.)
- Include any details about any error messages you see.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response
