### ISSUE TITLE
Incorrect SAS URL for fileshare directories

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#1485]
**Storage Explorer Version**: 1.8.1
**Build Number**: 20190510.6
**Platform/OS**: Windows 10/Mac OS
**Architecture**: ia32
**Regression From**:  Unknown

## Bug Description ##
SAS URL generated for fileshare directories are incorrect.

## Steps to Reproduce ##
1. Create a folder in some fileshare
2. Get a SAS URL with delete permission
3. Use the rest API to delete that directory

## Expected Experience ##
Success without modifying the URL

## Actual Experience ##
Azure platform uses a parameter restype=directory to distinguish directories and files. We didn't take it into consideration. In our case, trying to access the resource always get response as "ResourceNotFound"

**Comment by craxal** [comment]
Duplicate of #1375. Just add your comments to that bug.
