### ISSUE TITLE
Azure Storage Eplorer - Unable to get local issuer certificate

### ISSUE THREAD

**Issue by giusbi** [microsoft/AzureStorageExplorer#1487]
Error "unable to get local issuer certificate" blocks copies and downloads in Azure Storage Explorer.

**Comment by craxal** [comment]
@giusbi We have a section in our [troubleshooting guide](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=1804#error-self-signed-certificate-in-certificate-chain-and-similar-errors) that should help. If you're still running into this, please let us know.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
