### ISSUE TITLE
Azure Storage Explorer - Subscription Failure

### ISSUE THREAD

**Issue by yiwenfeng** [microsoft/AzureStorageExplorer#1488]
**Storage Explorer Version**: 1.8.1
**Platform**: Windows 10

Subscription could not be loaded.  More information is shown below:
Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: f8cdef31-a31e-4b4a-93e4-5f571e91255a, Error: {"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}
Tenant Id: 685232ed-a87e-4cb7-8ae9-815b3de706d8, Error: {"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}

**Comment by craxal** [comment]
@yiweneng Can you go to the Azure portal and verify for us how many subscriptions you have? Also, can you tell us what version of Storage Explorer you're running, what platform you're running on, etc.?

**Comment by yiwenfeng** [comment]
Hello Craig,

I have two Azure subscriptions, one is my company account yvonne.wang@airliquide.com and the other is the personal yiwenfeng@outlook.com which I am using to take training.

Storage Explorer version is 1.8.1 on Windows 10.

Thanks for your help.
Yvonne
________________________________

**Comment by MRayermannMSFT** [comment]
@yiwenfeng are you behind a proxy?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
