### ISSUE TITLE
Cannot view Blob Storage Containers

### ISSUE THREAD

**Issue by gituser227** [microsoft/AzureStorageExplorer#1489]
**Storage Explorer Version**: Version: 1.8.1
**Build Number**:  20190510.6
**Commit**: 947fc741e
**Platform/OS**: macOS Mojave
**Architecture**: x64
**Support Id**: d9e67a19-e636-23aa-de45-4a87ad51edd8
**Regression From**:  Was working fine in previous versions.

## Bug Description ##
Cannot view Blob Storage Containers

## Steps to Reproduce ##
Open Storage Explorer
Click on "Blob Containers" under a storage account. 

## Expected Experience ##
Expected the list of containers to appear as usual.

## Actual Experience ##
This error message:
Unable to retrieve child resources.

Details: Cannot find module '/private/var/folders/s2/ysq9f90n56976_xcw_6mycl40000gp/T/MicrosoftAzureStorageExplorer/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/renderer/providers/StorageProvider'

appears in a pop-up.  After clicking "Ok", the pop-up appears a second time.

**Comment by craxal** [comment]
@gituser227 Try downloading the application again. If you're still encountering this issue, browse the internal application files and see if you can find the file in question. Let us know what you find.

**Comment by gituser227** [comment]
Downloaded from https://azure.microsoft.com/en-us/features/storage-explorer/

Browsed to /private/var/folders/s2/ysq9f90n56976_xcw_6mycl40000gp/T/MicrosoftAzureStorageExplorer/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/renderer/providers/ 
There is no "StorageProvider" there.

**Comment by gituser227** [comment]
I now suspect an installation issue.  There was a previous version still present.  I deleted both old and new version completely, and re-installed.  After that, Blob Containers are again visible.
This can be closed if you feel appropriate.  Maybe some clarification would help so people know they need to manually delete all files for a prior version when updating to a new version.

**Comment by craxal** [comment]
@gituser227 Very interesting. You shouldn't have to delete old apps or files since macOS apps are all sandboxes. But glad you found a solution. If this continues to be a problem for you or others, we can revisit.
