### ISSUE TITLE
Connect button enabled, but do not have response when click

### ISSUE THREAD

**Issue by dexinghua** [microsoft/AzureStorageExplorer#1492]
**Storage Explorer Version**: 1.8.1
**Build Number**: 20190510.6
**Platform/OS**: Windows 10 Server 2016
**Architecture**: ia32
**Regression From**:  N/A

## Bug Description ##
Click ‘Connect’ button on ‘Connect with Name and Key’ dialog does not got any response. Also repo other connect dialog.

## Steps to Reproduce ##
1. Try to connect to a storage account via account name and key.
2. Input correct account name, key and other required info.
3. Click button 'Connect'
![connect](https://user-images.githubusercontent.com/52196491/60083996-49fa2000-9769-11e9-8e78-52c94eaea3b4.jpg)

## Expected Experience ##
It connect to the storage account successfully  or  disable 'Connect' button

## Actual Experience ##
'Connect' button was enabled but no response when click

## Additional Context ##
Also repro for other connect methods

**Comment by jinglouMSFT** [comment]
Not a blocking issue for 1.9.0

**Comment by MRayermannMSFT** [comment]
Also, already fixed in 1.9.0
