### ISSUE TITLE
Rename a blob/container with snapshot will failed make a copy of the blob/container added

### ISSUE THREAD

**Issue by dexinghua** [microsoft/AzureStorageExplorer#1493]
**Storage Explorer Version**: 1.8.1
**Build Number**: 20190510.6
**Platform/OS**: Windows 10 Server 2016
**Architecture**: ia32
**Regression From**:  N/A

## Bug Description ##
Rename a blob/container with snapshot will failed with error message say not allowed, but it will create a copy of the blob/container with the expected name.

## Steps to Reproduce ##
1. Create a snapshot on a blob/container
2. Try to rename the blob/container

## Expected Experience ##
Rename blob/container failed with error message, and no copy blob/container added

## Actual Experience ##
Rename a blob/container failed with error message say not allowed, but it will create a copy of the blob/container with the expected name.
![rename](https://user-images.githubusercontent.com/52196491/60084685-91cd7700-976a-11e9-98a4-6b861dabe6dc.png)

**Comment by jinglouMSFT** [comment]
Renaming blob isn't a native operation by the blob service. It's a copy+delete operation on the client side. Delete is not permitted if a blob has a snapshot. But copy is allowed.  This is why you have a new copy. If we would fix this issue, we probably need to update our error message, but it might be tricky to do.  We'll investigate more.

**Comment by MRayermannMSFT** [comment]
This won't repro anymore. Rename is no longer available in Storage Explorer for blob containers. We now offer "Clone with New Name". That operation preserves the original container, so there will be no delete that fails.
