### ISSUE TITLE
Rename blob failed when connect by SAS on container with ‘read+write +list’ permission make a copy of blob added

### ISSUE THREAD

**Issue by dexinghua** [microsoft/AzureStorageExplorer#1494]
**Storage Explorer Version**: 1.8.1
**Build Number**: 20190510.6
**Platform/OS**: Windows 10 Server 2016
**Architecture**: ia32
**Regression From**:  N/A

## Bug Description ##
Rename a blob/container with snapshot will failed with error message say not allowed, but it will create a copy of the blob/container with the expected name.

## Steps to Reproduce ##
1. Get shared access signature on a container with ‘read+write +list’ permission.
2. Connect the container by the SAS.
3. Try to rename a blob in the container

## Expected Experience ##
Rename blob failed, and no copy of the blob added.

## Actual Experience ##
Rename blob failed, but a copy of the blob with the expected updated name added.
![renameblob](https://user-images.githubusercontent.com/52196491/60085679-53d15280-976c-11e9-92de-3c5d5c4dd2e3.png)

**Comment by JasonYeMSFT** [comment]
Hi, how renaming blob works is that we create a new blob with the new name and delete the old blob. Since you don't have the delete permission, the delete operation will fail and thus it seems that a copy is created.

**Comment by jinglouMSFT** [comment]
This is a permission issue as Jason mentioned above. So in this particular scenario, our behavior was correct.
