### ISSUE TITLE
It cannot refresh automatically after change public access level of container

### ISSUE THREAD

**Issue by dexinghua** [microsoft/AzureStorageExplorer#1495]
**Storage Explorer Version**: 1.8.1
**Build Number**: 20190510.6
**Platform/OS**: Windows 10 Server 2016
**Architecture**: ia32
**Regression From**:  N/A

## Bug Description ##
It cannot refresh automatically after change public access level of container

## Steps to Reproduce ##
1. Change public access level of a container and apply
2. Click 'Set Public Access Level.." to check whether access level was updated as expected

## Expected Experience ##
The access level was updated as expected

## Actual Experience ##
It still selected original access level, after refresh container manually, and check the access level. it will updated to the new level.
![updateaccesslevel](https://user-images.githubusercontent.com/52196491/60086305-6b5d0b00-976d-11e9-8592-a3ffe92aaefe.jpg)

**Comment by MRayermannMSFT** [comment]
This has been fixed at some point in the past.
