### ISSUE TITLE
The unmatched file share doesn't auto disappear when filtering 

### ISSUE THREAD

**Issue by v-dantch** [microsoft/AzureStorageExplorer#1497]
**Storage Explorer Version**: 1.9.0
**Build Number**: 20190625.3
**Platform/OS**: All
**Architecture**: ia32
**Commit**: 73eecc3c
**Regression From**:  Not a Regression

## Steps to Reproduce ##
1. Select "Search From Here" from the File Shares tree view and filter one specific file share with name.
2. Rename the listed file share and make sure it does not meet the filter.
3. Check the listed item.

## Expected Experience ##
There is no matched file share.

## Actual Experience ##
The renamed file share still list and does not auto disappear.
![image](https://user-images.githubusercontent.com/34729092/60089145-76ff0080-9772-11e9-83c7-f9dd8cf6045c.png)

## More Info ##
The renamed file share disappears after refreshing File Shares node.

**Comment by JasonYeMSFT** [comment]
This is very corner case. Won't fix.

**Comment by v-dantch** [comment]
Got it. Thanks for your update.
