### ISSUE TITLE
Update 'Undelete by Date' to 'Undelete by Date…' for one soft deleted blob 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1498]
**Storage Explorer Version:** rel/1.9.0_20190625.3
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** 73eecc3c
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand a Non-ADLS Gen2 storage account -> Blob Container -> Enable soft delete.
2. Create a new blob container then upload a blob -> Delete the uploaded blob.
3. Go to 'Active and deleted blobs' -> Right click the deleted blob then click 'Undelete' on the context menu.
4. Check the sub-action of the 'Undelete'.

**Expected Experience:**
Show 'Undelete by Date…'.

**Actual Experience:**
Show 'Undelete by Date'.
![image](https://user-images.githubusercontent.com/41351993/60088560-73b74500-9771-11e9-984a-4fbf34dc8aac.png)

**Comment by v-juwe** [comment]
Verified this issue on build rel/1.9.0_[20190627.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2807645). It has been fixed. So we close it.
