### ISSUE TITLE
Show '(Leased,)' next to one leased blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1499]
**Storage Explorer Version:** rel/1.9.0_20190625.3
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** 73eecc3c
**Regression From:** Previous release(1.8.1)

**Steps to reproduce:**
1. Expand a Non-ADLS Gen2 storage account -> Blob Container.
2. Create a new blob container and acquire lease.
3. Check the blob container.

**Expected Experience:**
Show '(Leased)' next to the blob container.
![image](https://user-images.githubusercontent.com/41351993/60087228-2e921380-976f-11e9-9981-ee6cc4f0a429.png)

**Actual Experience:**
Show '(Leased,)' next to the blob container.
![image](https://user-images.githubusercontent.com/41351993/60087171-0acecd80-976f-11e9-99ce-5ec2e25c397a.png)

**Comment by v-xianya** [comment]
Verified this issue on build 20190626.4. It has been fixed. So we close it.

**Comment by v-xianya** [comment]
This issue reproduces on build **master**/20190702.3. So we re-open it.

**Comment by MRayermannMSFT** [comment]
Rel branch just needs merging back into master, which will happen today. 😄

**Comment by v-xianya** [comment]
This issue reproduces on the build feature/main-host 20190709.6. So we re-open it.

**Comment by v-xianya** [comment]
Verified this issue on the build feature/main-host 20190711.2. It has been fixed. So we close it.
