### ISSUE TITLE
Cannot connect to ADFS Backed Azure Stack

### ISSUE THREAD

**Issue by thomasmaurer** [Microsoft/AzureStorageExplorer#150]
**Storage Explorer Version**: 

**Platform**: Windows
**Architecture**: ia32

**Build Number**: 20180415.2

**Commit**: 5d603052

**Regression From**: Yes

#### Steps to Reproduce: ####

1. Add new account
2. add an azure Account
3. Custom Environment
4. Enter the Azure Stack URL https://management.region.fqdn
5. login with Azure AD Account
6. Switch Target Azure Stack
7. Restart
8. I cannot see any storage accounts on Azure Stack

#### Expected Experience: ####
Do all the steps and see the Azure Stack storage accounts

#### Actual Experience: ####
I cannot see the Azure Stack Azure Storage Accounts which are in my Azure Stack subscriptions.

**Comment by MRayermannMSFT** [comment]
Hi @thomasmaurer , for AAD backed azure stack, we recently added functionality that will let sign in to Azure/Azure China a custom environment. Please see this documentation: https://docs.microsoft.com/en-us/azure/azure-stack/user/azure-stack-storage-connect-se 

If after following it you are still stuck, please let me know. Thanks!

**Comment by thomasmaurer** [comment]
Hi @MRayermannMSFT 
I used that, there are now two options, Option one I don't see it or option two, there is something wrong with that documentation. I cannot see how they will know to which Azure Stack I want to connect.

If I login with my Azure AD Account which I use to sign in to Azure Stack an select Azure as an environment, I obviously only see my Azure Storage Accounts and Subscriptions. How would the tool know, how to connect to the right Azure Stack?

**Comment by MRayermannMSFT** [comment]
When Azure Stack is backed by AAD, Azure Stack "applications" are added to one of your Azure subscriptions. So when you sign into Azure, if you're targeting Azure Stack, we look for those applications and then use them to get your Azure Stack subscriptions (all of them, for every Azure Stack you are part of).

**Comment by thomasmaurer** [comment]
Oh wow I am impressed :) This is awesome. I didn't expect it to be that easy :) 👍

One question, how does it work if I am in a disconnect scenario?

**Comment by thomasmaurer** [comment]
Azure Stack can be installed in a disconnected mode. This means that Azure Stack does not really get registered to Azure and does also not use Azure AD, instead it will use ADFS. You can find more here:
https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-disconnected-deployment

**Comment by MRayermannMSFT** [comment]
Ah ok, ADFS backed Azure Stack I am very familiar with. :) Unfortunately recent changes to Azure Stack broke sign in from Storage Explorer and Visual Studio, which is why there's no longer anything in the documentation referencing it. Azure Stack has been working on a fix, though as far as I'm aware they have yet to deploy it. Once they do, we'll add back in the section about connecting to ADFS Azure Stack.

**Comment by thomasmaurer** [comment]
Okay this is good to know :) We prefer Azure AD connected Azure Stacks anyway, but the question could come up :)

**Comment by MRayermannMSFT** [comment]
Azure Stack v1804 and greater will work with Storage Explorer v1.2.0 (shipping soon). I'm going to close this issue now.
