### ISSUE TITLE
Unable to retrieve the resource after attaching one local service using SAS URI

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1501]
**Storage Explorer Version:** 1.9.0_**rel/1.9.0**_20190625.3
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Not a regression

## Bug Description ##
Unable to retrieve resource after attaching one local service using SAS URI.

## Steps to Reproduce ##
1. Make sure Storage Emulator has been started.
2. Expand 'Local & Attached' -> 'Storage Accounts' ->'Emulator - Default Ports(Key)' -> 'Tables' node.
3. Create a new table -> Get the SAS URI for the created table.
4. Attached the table using SAS URI.
5. Check the result.

## Expected Experience ##
The attached table appears under the 'Tables' in the (Attached Containers) section.

## Actual Experience ##
Unable to retrieve the resource.
![image](https://user-images.githubusercontent.com/34729022/60091424-20e08c00-9777-11e9-89f9-77653a1131bd.png)

## Additional Context ##
Maybe the local service cannot be attached using SAS URI. 

I cannot attached other tables for now due to the error. Could you help me to handle the error?

**Comment by JasonYeMSFT** [comment]
Hi, this is a very rare use case and we decided not to fix it soon. If any customer comes to us for this, we will revisit and make a fix.
