### ISSUE TITLE
Add Ubuntu 19.04 dependencies to troubleshooting

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1502]
**Storage Explorer Version:** 1.9.0
**Branch**: rel/1.9.0
**Build**: 20190625.3
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Not a regression

## Bug Description ##
We cannot get the latest real signed build on Linux using snap. So we installed Storage Explorer using the .tar.gz. But for Ubuntu 19.04, we found the [troubleshooting](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=1804#linux-dependencies) have no dependencies guidance.
![image](https://user-images.githubusercontent.com/34729022/60091753-e75c5080-9777-11e9-8f4e-810049184e78.png)

**Comment by craxal** [comment]
@v-xuanzh What exactly do you mean you were unable to get the latest signed build using snap? What problems occurred? Also, please specify the build and branch you are testing as separate fields (see edited comment above).

@jinglouMSFT I'm not aware of us mentioning any official support for Ubuntu 19.04 yet. Do we need to look into this? I also notice that Ubuntu 14 and 16 are no longer directly downloadable from Ubuntu's website. Should we consider dropping official support for those versions?

**Comment by jinglouMSFT** [comment]
@craxal Ubuntu 19.04 is already available and people are using it.  Storage Explorer should work on it as well. It might take us some time to find and fix all the issues in SE on 19.04 but our basic functionality should work.  In terms of 14 and 16, let's give it a bit time for customers to move to 18 or 19 before our new releases stop working on them.

**Comment by v-xuanzh** [comment]
Hi @craxal ,Today we try to install the latest real signed build **20190626.4** using the snap on Linux, but we got build is **20190626.3** actually.

**Steps to reproduce:**

1. Make sure Ubuntu 19.04 have supported snap.
2. Download the 'StorageExplorer_latest_amd64.snap' from Linux Artifactes(20190626.4)
3. Run the following commands:

`sudo snap install StorageExplorer_latest_amd64.snap --dangerous`
`snap connect storage-explorer:password-manager-service :password-manager-service`

4. Launch Storage Explorer by the command: `storage-explorer`
5. Check the build version after launching Storage Explorer successfully.

**Expect:**

The shown build is **20190626.4**

**Actual:**

The shown build is **20190626.3**
![image](https://user-images.githubusercontent.com/34729022/60145616-30081e00-97f9-11e9-8188-326b53d7b967.png)

**Comment by craxal** [comment]
@v-xuanzh Ah, weird. Possibly a random fluke in the build? Since this appears to be off topic, let's do this: If the problem persists in future builds, open a new bug, and we'll continue the discussion there.

**Comment by v-xuanzh** [comment]
@craxal . We will open a bug if it persists in future.

**Comment by craxal** [comment]
FYI, I was unable to reproduce the wrong build error described. I installed the 20190626.4 snap, and the About dialog displayed the correct build. It's possible the wrong snap was installed by accident.

**Comment by v-xuanzh** [comment]
Hi @craxal ,I tried to install the latest rel/1.9.0 build **20190627.4** on Ubuntu 18.04 and 19.04, but both of these About dialog display the wrong build **20190627.3**. I'm not sure if it related to the snap version. 

**Notes**: we used the integrated snap Ubuntu 18.04 and 19.04.
![image](https://user-images.githubusercontent.com/34729022/60310258-953c4a80-9984-11e9-8070-561afbfb33fb.png)
![image](https://user-images.githubusercontent.com/34729022/60310300-cb79ca00-9984-11e9-8861-62440a14bd5a.png)

**Comment by craxal** [comment]
@v-xuanzh Let's move the build number discrepancy to another bug, please.
