### ISSUE TITLE
Make tab support more robust

### ISSUE THREAD

**Issue by ChrisRobbers** [microsoft/AzureStorageExplorer#1504]
**Is your feature request related to a problem? Please describe.**
My organization relies heavily on Azure storage. I'm frequently comparing different tenants/accounts in Storage Explorer and I get frustrated when I can't have related tabs next to each other. Additionally, if my computer needs to be rebooted it would be nice if I could come back to my last session and have all my tabs still there.

**Describe the solution you'd like**
I would prefer something more akin to modern editors like VS Code, where the tabs can be drag & drop reordered, and session state maintained when the program is closed and reopened. Bonus points: Queries in table storage are remembered and retained.

**Describe alternatives you've considered**
Quick Access helps somewhat with at least being able to pin current resources, and tabs can be carefully opened in order, but these are all inferior to what I envision.

**Comment by MRayermannMSFT** [comment]
Related: https://github.com/microsoft/AzureStorageExplorer/issues/501

**Comment by MRayermannMSFT** [comment]
@ChrisRobbers what is more important to you, reordering or sessions state restoration?

**Comment by ChrisRobbers** [comment]
Probably sessions state restoration.

**Comment by munael** [comment]
Related to session restore: Allow a more detailed mode for tab names that shows the current path (not just container). Possibly with the ability to rename?

**Comment by JasonYeMSFT** [comment]
We will start by adding the support for preserving the navigation path of blob containers, ADLS Gen2 containers, file share and ADLS Gen1 in 1.21.0
https://github.com/microsoft/AzureStorageExplorer/issues/4765

**Comment by JasonYeMSFT** [comment]
Work needs to be done for an actual tab session restoration.
- [ ] Lazy load tab contents
- [ ] Encrypted tab session storage
- [ ] Allow opening tab with a non-default state

**Comment by JasonYeMSFT** [comment]
The support to preserve tab sessions have been added to our 1.25.0 release. It's an opt-in feature. If you would like to start using it, please enable the setting at "Settings" -> "Data Explorers" -> "Preserve Explorer Session".
