### ISSUE TITLE
Update 'URI' to 'URL' on the first page of the Connect dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1506]
**Storage Explorer Version:** rel/1.9.0_20190626.4
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** 0afd7438
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch storage explorer -> Open Connect dialog.
2. Check the descriptions on the dialog.

**Expected Experience:**
Show 'Use a shared access signature (SAS) **URL**'

**Actual Experience:**
Show 'Use a shared access signature (SAS) **URI**'
![image](https://user-images.githubusercontent.com/41351993/60165406-cfe19e00-9831-11e9-893e-ce30e1cf7b5f.png)

**More Info:**
Show URL when generating share access signature.
![image](https://user-images.githubusercontent.com/41351993/60165549-13d4a300-9832-11e9-84f7-bbde2a163d2c.png)

**Comment by MRayermannMSFT** [comment]
Fix the bottom string to say URI.

**Comment by v-xianya** [comment]
Verified this issue on the latest build master/20190708.4. It has been fixed. So we close it.

**Comment by v-xianya** [comment]
This issue reproduces on the build **feature/main-host** 20190709.6. So we re-open it.

**Comment by v-xianya** [comment]
Verified this issue on the build feature/main-host 20190711.2. It has been fixed. So we close it.
