### ISSUE TITLE
Disable the 'Next' button when the Environment name/ARM endpoint is invalid on 'Custom Environment' dialog 

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1509]
**Storage Explorer Version:** rel/1.9.0_20190626.4
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** 0afd7438
**Regression From:** Not a regression

**Steps to reproduce:**
1. Open Connect dialog -> Select 'Add New Environment' from the drop-down of Azure environment -> Next.
2. Leave the Environment name/ARM endpoint are blank -> Check the 'Next' button on the 'Custom Environment' dialog.

**Expect Experience:**

The 'Next' button is disabled.

**Actual Experience:**

The 'Next' button is enabled.
![image](https://user-images.githubusercontent.com/34729022/60169488-5e0d5280-9839-11e9-9a2a-11714a03994e.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into master
