### ISSUE TITLE
 Clicking "Cancel" shows 'Skipped copying xxx' when copying a large blob

### ISSUE THREAD

**Issue by v-juwe** [microsoft/AzureStorageExplorer#1510]
**Storage Explorer Version**: rel/1.9.0_20190626.4
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture**: ia32/x64
**Commit**: 0afd7438
**Regression From**: Not a regression

**Steps to Reproduce:** 

1. Open a blob container -> Chose a large blob -> Click 'Copy'.
2. Paste the copied blob to an another account.
3. Click 'Cancel' next to the shown log message on Activities.

**Expected Experience:**

There shows **'Cancelled** copying xxx' after clicking the 'Cancel'.

**Actual Experience:** 

There shows **'Skipped** copying xxx' after clicking the 'Cancel'.
![image](https://user-images.githubusercontent.com/52151370/60170915-06241b00-983c-11e9-9f32-ab42bfe1aa2d.png)

**Comment by v-limu** [comment]
Verified this issue on build [20191220.9](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3338616). The activity log message has been changed. So we close it.
![image](https://user-images.githubusercontent.com/54055206/71608387-ea6b4a00-2bbb-11ea-8d10-a856c0c863f8.png)
