### ISSUE TITLE
Show a duplicate account email on the Account list of 'Attach with Azure AD' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1513]
**Storage Explorer Version:** 1.9.0_**rel/1.9.0**_20190626.4
**Platform/OS:** Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Make sure you have signed into accounts.
2. Open 'Connect' dialog -> Select 'Add a resource via Azure Active Directory(Azure AD)'.
3. Check the shown account list.

**Expect Experience:**

There shows as below format:
**Account name** -- `Xuan zhang(Beyondsoft Corporation)`
**Email** - `v-xuanzh@microsoft.com`

**Actual Experience:**

There shows a duplicate email.

**Email** - `v-xuanzh@microsoft.com`
**Email** - `v-xuanzh@microsoft.com`

![image](https://user-images.githubusercontent.com/34729022/60228200-82fad780-98c4-11e9-83be-3daac1811a1f.png)

**Comment by MRayermannMSFT** [comment]
Double check what account member we are using for the top field. If we are using the right one, then ask Chris if this is expected. If it is, then see if they can fix, otherwise, close.

**Comment by MRayermannMSFT** [comment]
Talked to Chris. By design. Limitation of libraries identity uses on their end.
