### ISSUE TITLE
SAS Attach Does Not Auto-Detect Endpoints

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#1514]
**Storage Explorer Version**: 1.9.0 rel branch

When I attach using a SAS URI, the endpoint for the service type I'm attaching isn't filled out:
![image](https://user-images.githubusercontent.com/21112697/60283706-af135a00-98be-11e9-82b1-296b7e61bad2.png)

As a customer, this might make me wonder if my URI is wrong.

**Comment by v-xianya** [comment]
Verified this on build 20201209.5. Fixed.
![image](https://user-images.githubusercontent.com/41351993/101594387-863c4180-3a2c-11eb-972f-a79ed05a6e1a.png)
