### ISSUE TITLE
Miss "Copy Direct Link to Blob Container" for one renamed blob container

### ISSUE THREAD

**Issue by v-juwe** [microsoft/AzureStorageExplorer#1515]
**Storage Explorer Version:** rel/1.9.0_[20190627.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2807645)
**Platform/OS**: Windows 10
**Architecture:** ia32/x64
**Commit:** d1c142cc
**Regression From:** Not a regression

**Steps to Reproduce:**
1. Expand a non-ADLS Gen2 storage account -> Blob Containers.
2. Right click one blob container -> Click 'Rename' on the context menu.
3. After the renamed action is successful -> Check the context menu for renamed blob container.

**Expected Experience:**
"Copy Direct Link to Blob Container" displays on the context menu.
![image](https://user-images.githubusercontent.com/52151370/60317328-1efa1100-99a1-11e9-8b97-5ce6313e7571.png)

**Actual Experience:**
No "Copy Direct Link to Blob Container" displays on the context menu.
![image](https://user-images.githubusercontent.com/52151370/60317343-31744a80-99a1-11e9-8570-1f9a69272ee7.png)

**More Info**
1. The issue reproduces for renamed file shares.
2. This issue also reproduces for copied blob container/file share.

**Comment by MRayermannMSFT** [comment]
Won't fix for now due to low usage.
