### ISSUE TITLE
azcopy command line show percentage of progress

### ISSUE THREAD

**Issue by powdermonkey007** [microsoft/AzureStorageExplorer#1516]
**Is your feature request related to a problem? Please describe.**
when i have to use the azcopy command i don't know how much data has been copied. i have to calculate the transfer estimate time and then just hope it finishes successfully

**Describe the solution you'd like**
like the azure file explorer show the percentage of progress

**Describe alternatives you've considered**

**Additional context**

**Comment by JasonYeMSFT** [comment]
Hi, 
The AzCopy command line tool is developed by the AzCopy team. If you are working with blobs, you can enable AzCopy in Storage Explorer to upload or download blobs, which will show a percentage progress for how much data has been transferred.

**Comment by powdermonkey007** [comment]
hi Jason, the command line as mentioned in the subject line. Since you cannot copy managed disks with storage explorer the command line is the only option. if the command line would show a percentage too it would be super helpful.

**Comment by JasonYeMSFT** [comment]
Hi,
Could you please open an issue under the AzCopy repo https://github.com/Azure/azure-storage-azcopy. They are in charge of the command line tool and they can help adding the progress bar feature in it. Since we are depending on the command line tool, there is nothing we can do for now.
