### ISSUE TITLE
error 'missing required parameter 'se' or 'si' in SAS token

### ISSUE THREAD

**Issue by Pl4nky** [microsoft/AzureStorageExplorer#1517]
**Storage Explorer Version**: 1.8.1
**Build Number**: 20190510.6
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  Unknown

## Bug Description ##
When attempting to add a storage account using SAS URI, an error is displayed and does not let you progress

error 'missing required parameter 'se' or 'si' in SAS token

## Steps to Reproduce ##

1. Create a storage account
2. Create blob container via console storage explorer
3. Right click blob container and select 'Get Shared Access Signature'
4. Choose Access policy and Start/Expiry times and click Create
5. Container, URL and Query string values are displayed. 
6. Copy URL into Storage Explorer URI field

## Expected Experience ##
No errors and be able to click next on the wizard

## Actual Experience ##
"error 'missing required parameter 'se' or 'si' in SAS token" is displayed, next button is disabled

## Additional Context ##
May relate to #1299 

Not sure if this way of creating SAS keys is supported.

**Comment by Pl4nky** [comment]
Appears that if you generate the URL via the Azure Console (Storage Explorer preview), the url is invalid/missing parameters.  I have a ticket open with Microsoft support for it. 

Generating via the Storage Explorer client software itself gives a valid URL that it can be used for connecting.

**Comment by FreddyEcu-Ch** [comment]
I have been faced the same problem. It seems that the version 1.18.1 is not working well by adding a new SAS

**Comment by chadleong** [comment]
> I have been faced the same problem. It seems that the version 1.18.1 is not working well by adding a new SAS

When you connect - make sure you select Blob Container instead of Storage account.
