### ISSUE TITLE
about "folder" in Blob

### ISSUE THREAD

**Issue by zhengyiqun** [microsoft/AzureStorageExplorer#1518]
I have a question about "folders". If I upload a blob, I chose "Upload to Folder". When using the Get Blob API, the Blob name format is "test/test/test/1353363361.jpg". The "Content-Type" attribute of "test" in the storage explorer is "folder". The question is: the "folder" obtained from Blob name?

**Comment by JasonYeMSFT** [comment]
Hi, 
Your guess is correct. The blob name infers a virtual hierarchy. You can get more details here: [Blob name doc](https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#blob-names).
