### ISSUE TITLE
Issues not able to open free trail subscription - Azure storage Explorer

### ISSUE THREAD

**Issue by ShwetaBhatkal** [microsoft/AzureStorageExplorer#1519]
Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: cb356782-ad9a-47fb-878b-7ebceb85b86c, Error: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"13.75.216.21","port":443}

**Comment by MRayermannMSFT** [comment]
@ShwetaBhatkal,

- What version of storage explorer are you running?
- Are you behind a proxy?

Have you looked at a t[roubleshooting guide](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=1804)?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
