### ISSUE TITLE
Copy to clipboard in About dialog

### ISSUE THREAD

**Issue by juliusl** [Microsoft/AzureStorageExplorer#152]
**1.0.0**: 

**Windows**: 

**64 bit**: 

**20180415.2**: 

**5d603052**: 

**Regression From**: 

#### Steps to Reproduce: ####
I open the about dialog.

#### Expected Experience: ####
I expect a Copy to clipboard or the ability to copy the text in the dialog myself.

#### Actual Experience: ####
I can't highlight anything.

This makes it hard to fill out github issues.

**Comment by JakeRadMSFT** [comment]
Great idea!

**Comment by whiskeyjay** [comment]
In the Windows version you can actually use "Ctrl+C" to copy the dialog content just like any other system message box dialogs.

```
[Window Title]
Microsoft Azure Storage Explorer

[Main Instruction]
Microsoft Azure Storage Explorer

[Content]
Version: 1.1.0

Platform: Windows
Architecture: ia32
Build Number: 20180507.1
Commit: bcc8990d
Support Id: a4162cc5-e568-af8c-f86a-da46f067e1bb

Copyright © 2018 Microsoft. All rights reserved.

[OK]
```

**Comment by juliusl** [comment]
@whiskeyjay nice, didn't know that.

**Comment by MRayermannMSFT** [comment]
Closing as we're going to do this instead: #401 .
