### ISSUE TITLE
Install an unmatched Storage Explorer version using snap

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1520]
**Storage Explorer Version:** 1.9.0
**Branch**: rel/1.9.0
**Build**: 20190701.8
**Platform/OS:** Linux Ubuntu
**Architecture:** x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Make sure Ubuntu 19.04/18.04 have supported snap(**_The integrated snap version: 2.39.2_** ).
2. Download the 'StorageExplorer_latest_amd64.snap' from Linux Artifactes(20190701.8).
3. Run the following commands:
`sudo snap install StorageExplorer_latest_amd64.snap --dangerous`
`snap connect storage-explorer:password-manager-service :password-manager-service`
4. Launch Storage Explorer using the command `storage-explorer`
5. Check the installed version on About page.

**Expect Experience:**

The installed version is **20190701.8**

**Actual Experience:**

The installed version is **20190701.4**

**More info:**

There shows storage-explorer 1.8.1 installed(Actually, the currently version is 1.9.0)
![image](https://user-images.githubusercontent.com/34729022/60488916-b5963d00-9cd5-11e9-9f46-79c30f2180ed.png)
![image](https://user-images.githubusercontent.com/34729022/60489009-e8403580-9cd5-11e9-8747-3e62512e0d70.png)

**Comment by craxal** [comment]
Fixed in master. If snaps are ready before we're ready to release 1.10.0, we may consider doing a hotfix.

**Comment by v-xianya** [comment]
Hi @craxal . Verified this issue on the latest build master/20190709.4. It has been fixed.
