### ISSUE TITLE
Update 'Blob containers' to 'blob containers' on Release Notes New section

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1521]
**Storage Explorer Version:** 1.9.0_**rel/1.9.0**_20190701.8
**Platform/OS:** Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer -> Open Release Notes.
2. Check the description (1) under the New section.

**Expect Experience:**

There shows '... **blob containers**...'.

**Actual Experience:**

There shows '... **Blob containers**....'
![image](https://user-images.githubusercontent.com/34729022/60489873-fa22d800-9cd7-11e9-9558-07f3e956394d.png)

**Comment by MRayermannMSFT** [comment]
These release notes are going to be discarded for the next version. Will keep this casing in mind though for next release. Thanks!
