### ISSUE TITLE
Display a different Cosmos DB API between Portal and Storage Explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1522]
**Storage Explorer Version:** 1.9.0_20190702.3
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Create a Cosmos DB account with Core(SQL) API in Portal.
2. Open the new created account in Storage Explorer
3. Check the Cosmos DB API on actions & Properties panel.

**Expect Experience:**
Display the same Cosmos DB API between Portal and Storage Explorer.

**Actual Experience:**
Display a different Cosmos DB API between Portal and Storage Explorer.
![image](https://user-images.githubusercontent.com/41351993/60500040-3b24e780-9cec-11e9-8881-a31f807ac849.png)

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
