### ISSUE TITLE
The action 'Create Database' shows a confused icon for one Cosmos DB account 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1523]
**Storage Explorer Version:** 1.9.0_20190702.3
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Select a Cosmos DB account with Graph API.
2. Check the icon of the action 'Create Database' on Actions & Properties panel.

**Expect Experience:**

Show a database icon for the 'Create Database'.

**Actual Experience:**

Show a confused icon to the 'Create Database'.
![image](https://user-images.githubusercontent.com/41351993/60501585-d9b24800-9cee-11e9-8b1c-28988b577ec7.png)

**More Info:**
1. This issue also reproduces for the action 'Create Graph...'.
2. This issue also reproduces for the action 'Create Collection...' under one Cosmos DB account with SQL API.
3. This issue also reproduces for the action 'Create Table...' under one Cosmos DB account with table API.

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
