### ISSUE TITLE
'Save' is enabled when deleting the value of Max Age on 'Add CORS Rule' dialog

### ISSUE THREAD

**Issue by v-juwe** [microsoft/AzureStorageExplorer#1525]
**Storage Explorer Version:** 1.9.0_20190702.3
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to Reproduce:**
1.  Expend  one storage account -> Right click 'Blob Containers' -> Click 'Configure CORS Settings...'.
2.  Click Add -> Input the valid Allowed Origins/Allowed Headers/Exposed Headers and Max Age value.
3. Delete this value of Max Age manually -> Check the 'Save' button.

**Expected Experience:**

'Save' button is disabled.

 **Actual Experience:**
The 'Save' button is enabled.
![image](https://user-images.githubusercontent.com/52151370/60504670-9955c880-9cf4-11e9-9f89-eee0de586b63.png)

**Comment by MRayermannMSFT** [comment]
Won't Fix. Will reopen pending customer feedback.
