### ISSUE TITLE
Cannot complete the undelete operation for one folder which contains multiple blobs

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1529]
**Storage Explorer Version:** 1.9.0_**master**_20190703.4
**Platform/OS:** Windows 10/Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Copy a large folder('StorageExplorer' -> 'stgexp' -> 'bigblobs' -> '**1000smallblobs**') to an another account.
2. Make sure the soft delete is enabled for the target account.
3. Try to delete the copied blob folder.
4. Switch to 'Active and deleted blobs' after deleting successfully -> Right click the deleted folder then select 'Undelete Selected' .
5. Check the result.

**Expect Experience:**

The deleted folder can be undeleted successfully.

**Actual Experience:**

The undelete operation cannot be completed.
![image](https://user-images.githubusercontent.com/34729022/60576859-ca93ce80-9db0-11e9-887a-058b784cb624.png)

**Comment by JasonYeMSFT** [comment]
I cannot reproduce this bug. By the way, the activity log shouldn't say canceling the job, even if it encounters an error. Are you sure that you haven't clicked the cancel button?

**Comment by v-xuanzh** [comment]
Hi @JasonYeMSFT , I can reproduce this issue. And I am sure I haven't click the 'Cancel All' link.

**Comment by MRayermannMSFT** [comment]
@JasonYeMSFT is going to try in the same blob container/directory. If he can repro he will move it to 1.10

**Comment by JasonYeMSFT** [comment]
Hi @v-xuanzh , I tried the following steps on that build and still cannot reproduce this bug:

1. Enable soft delete on one of my storage account
2. Copy the folder 'StorageExplorer' -> 'stgexp' -> 'bigblobs' -> '1000smallblobs'
3. Navigate to one blob container in my storage account
4. Click "Paste" in the toolbar
5. Wait for the transfer to finish
6. Delete the copied folder
7. Enter active and deleted view and undelete the folder
8. Wait for undelete to finish

If you can still reproduce this bug, could you please show us more details?

**Comment by v-xuanzh** [comment]
​I cannot reproduce this issue on the latest master build 20190716.7​​​​​​😔

I am not sure if it is a network issue. We will continue to track it if it reproduce in future.😀 

So close it due to does not reproduce for now.
​​​​​​​
