### ISSUE TITLE
Update the dialog’s title to 'Delete Snapshots' when deleting blob snapshots

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1530]
**Storage Explorer Version:** 1.9.0_20190703.4
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand a storage account -> Blob Container.
2. Create a new blob container and upload a file.
3. Create a snapshot for the new blob -> Right click the snapshot and select 'Delete'.
4. Check the prompt dialog.

**Expect Experience:**

Display 'Delete Snapshots' on the dialog.

**Actual Experience:**

Display 'Delete' on the dialog.
![image](https://user-images.githubusercontent.com/41351993/60577163-6ae9f300-9db1-11e9-8933-641ed0a11031.png)

**Comment by jinglouMSFT** [comment]
It turned out that this dialog is shared by multiple objects such as Blobs, snapshots, folders, etc.  So the title of the dialog is generic, but it does indicate the action the user has decided to do.  Not worth the code churn for a cosmetic change.
