### ISSUE TITLE
Cannot directly open blobs with no file extension on Windows 10 1903

### ISSUE THREAD

**Issue by neilrees** [microsoft/AzureStorageExplorer#1531]
**Storage Explorer Version**: 1.9.0
**Build Number**: 20190701.8
**Platform/OS**: Windows 10 1903
**Architecture**: x64
**Regression From**:  Regression from behavior on Windows 10 1809

## Bug Description ##
When double clicking a blob to open it and the blob does not have a file extension (e.g. `configuration`), rather than showing the "Open file with" windows dialog, you instead receive an error dialog: e.g.:
![image](https://user-images.githubusercontent.com/282424/60584671-ba1a2e80-9d85-11e9-9e7d-9407772ea107.png)

## Steps to Reproduce ##
1. Navigate to a Storage Account -> Container that contains a blob without a file extension
2. Double click the blob

## Expected Experience ##
Expect to receive the standard Windows "How do you want to open this file" picker:
![image](https://user-images.githubusercontent.com/282424/60584773-01082400-9d86-11e9-9171-1a647a1c746a.png)
After picking an application from the list the file would be opened in the selected app.

## Actual Experience ##
An error is received:
![image](https://user-images.githubusercontent.com/282424/60584671-ba1a2e80-9d85-11e9-9e7d-9407772ea107.png)

The file cannot be opened in an editor without downloading it explicitly.

## Additional Context ##
The behavior is as expected on Windows 10 1803 and 1809, but shows the error on 1903.

**Comment by OzBob** [comment]
I have the same issue on 1903

Work around: 
Right click on the blob | Download
Save.
Open Windows Explorer
Double click file
Choose a program to open file, e.g. notepad
or Optionally rename file to have .txt(?) extension

**Comment by MRayermannMSFT** [comment]
@JasonYeMSFT , let's look into this while doing AzCopy open.

**Comment by MRayermannMSFT** [comment]
Ok, I'm on 1809 and things are working as expected....I'm going to update to 1903 and see what happens...

**Comment by MRayermannMSFT** [comment]
Yep, it regresses on upgrade. Unfortunately there doesn't seem to be anything we can do on our side for this. I'll need to file an electron bug tomorrow. Sorry y'all. 😰

**Comment by MRayermannMSFT** [comment]
Filed Electron issue: https://github.com/electron/electron/issues/20543

**Comment by neilrees** [comment]
Electron have closed the bug - where does this go next?

**Comment by MRayermannMSFT** [comment]
They believe it is an issue in Windows. So we need to do some more investigation.

**Comment by neilrees** [comment]
I've now seen this issue in a number of electron based applications.  Is there an upstream bug we can be tracking?

**Comment by OzBob** [comment]
@neilrees  Electron issue: https://github.com/electron/electron/issues/20543

**Comment by OzBob** [comment]
@MRayermannMSFT : do you have a windows issue for us to monitor?

**Comment by jinglouMSFT** [comment]
Using Storage Explorer 1.13.1 and Windows 10 1909, double click to open a blob without an extension will generate the following warning dialog:

![image](https://user-images.githubusercontent.com/10081483/83064741-22fe3b00-a017-11ea-9f51-e6ae8d78bc53.png)

If you click on Yes to open the file, it will be downloaded first then Windows File Explorer is opened. If you double click to open the file, you will be asked how you want to open the file.

**Comment by OzBob** [comment]
@jinglouMSFT I've tried double clicking on a file and the same error is reported. 
Storage Explorer Version: 1.13.1
Build Number: 18362.836
Platform/OS: Windows 10 1903
Architecture: x64

**Comment by jinglouMSFT** [comment]
This is still repro with Storage Explorer 1.13.1 and Windows 10.1090.  Will enter a bug on Windows.

**Comment by jinglouMSFT** [comment]
Reported the issue to Windows.

![image](https://user-images.githubusercontent.com/10081483/83183713-23f9a000-a0dd-11ea-8502-f054e6c50105.png)

**Comment by jinglouMSFT** [comment]
Reporting back on the Windows bug - There was a regression in the ShellExecute API in Windows 10 builds 190x.  This issue has been fixed in Windows 10 build 2004. Build 2004 is currently being rolled out gradually.  In terms of a workaround if you are on Windows 10 build 190x and if you are comfortable modifying your Windows registries, you can associate the file extension (no-extension) there.  We don't recommend this if you don't normally modify the registries as the impact is system wide.  Another workaround is to down load the file/blob to a local temp folder, and open it from Windows File Explorer.  This is the default download experience in Storage Explorer. The association in the File Explorer works just fine.

**Comment by neilrees** [comment]
Thanks @jinglouMSFT can confirm that upgrading to Windows 2004 has solved this 👍

**Comment by jinglouMSFT** [comment]
That's great.  Thanks much for letting us know.
