### ISSUE TITLE
Use system proxy settings

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#1534]
This feature requires the use of a different networking module (Electron's `net` module instead of `request`).

**Comment by MRayermannMSFT** [comment]
Let's try using electron net for listing subscriptions. If it unblocks people, then we can prioritize switching everything to electron net.

**Comment by MRayermannMSFT** [comment]
Ok, we've added some stuff that will help us see if the Electron net framework will be a good networking solution. We'll check back in a few months and see how it's doing.

**Comment by craxal** [comment]
See #3573 for another, short-term implementation.

**Comment by MRayermannMSFT** [comment]
Starting in 1.20 Storage Explorer will have the option to "Use System Proxy". This option will, in short, have Storage Explorer make HTTP requests via the Chromium networking stack. That said, this feature will being in a preview state. Not all of Storage Explorer's features are in a state where they can take advantage of this new feature. We will be continuing to work on that. You can roughly track the progress of that work, with these issues:

#4475
#4474
#4483
