### ISSUE TITLE
Add '…' next to 'Set Default Access Tier' for one StorageV2 account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1537]
**Storage Explorer Version:** 1.9.0_**master**_20190709.5
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:**  6e6ca7a0
**Regression From:** Not a regression

**Steps to reproduce:**
1. Right click one StorageV2 account -> Check its context menu.

**Expected Experience:**
Show 'Set Default Access Tier...' in the context menu.

**Actual Experience:**
Show 'Set Default Access Tier' in the context menu.
![image](https://user-images.githubusercontent.com/41351993/60955841-38ea0b00-a334-11e9-9f4b-62f7acec5ef9.png)

**Comment by jinglouMSFT** [comment]
Fix merged to Master.
