### ISSUE TITLE
Display 'Loading...' when trying to expand 'Stored Procedures' for one MongoDB account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1538]
**Storage Explorer Version:** 1.9.0_**master**_20190709.5
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** 6e6ca7a0
**Regression From:** Not a regression

**Steps to reproduce:**
 1. Expand a one MongoDB account -> Create a new database.
 2. Create a new collection then expand it.
 3. Try to expand 'Stored Procedures' and observe the result.

**Expected Experience:**
   Expand successfully.

**Actual Experience:**
  Display 'Loading...'.
![image](https://user-images.githubusercontent.com/41351993/60956183-da715c80-a334-11e9-8ecf-c9356181dacf.png)

**More Info:**
This issue also reproduces for 'Triggers' and 'User Defined Functions' node.

**Comment by v-xianya** [comment]
Hi  @MRayermannMSFT @southpolesteve

Verified on the Storage Explorer 1.14.0 version. Pop up the below error dialog when trying to expand 'Stored Procedures','Triggers' and 'User Defined Functions' node.

![image](https://user-images.githubusercontent.com/41351993/87013729-abb6ec00-c1fd-11ea-826b-9d9c3ea10c36.png)

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
