### ISSUE TITLE
An extra action 'Set Public Access Level…' displays on context menu for one created premium blob container

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#154]
**Storage Explorer Version**: 1.1.0 RC

**Platform**: Windows/Linux/Mac

**Architecture**: ia32/x64

**Build Number**: 20180507.1

**Commit**: bcc8990d

**Regression From**: Not a regression

#### Steps to Reproduce: ####

1. Launch Storage Explorer and expand a premium storage account.
2. Create a new blob container and check the context menu.

#### Expected Experience: ####

No 'Set Public Access Level…' displays on the context menu.

#### Actual Experience: ####

An extra action 'Set Public Access Level…' displays on context menu.
![extra](https://user-images.githubusercontent.com/34729022/39750803-b86225ec-52a5-11e8-9605-fa8de017ca1c.png)

**More info:**
This issue doesn't reproduce after refreshing.

**Comment by MRayermannMSFT** [comment]
Note: bug only repros for a brand new container. If you refresh the parent node then the bug goes away.

**Comment by MRayermannMSFT** [comment]
@v-xuanzh , can you check if this still repros in 1.4.0? Thanks!

**Comment by v-xuanzh** [comment]
This issue is fixed in 1.4.0. Could you help to resolve this issue?

**Comment by MRayermannMSFT** [comment]
Yep!

**Comment by v-limu** [comment]
This issue reproduces on build [20191116.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3250060). So reopen it.

**More Info:**

1. This issue also reproduces for **paste one non-premium blob.**
2. This issue doesn't reproduce after refreshing.
