### ISSUE TITLE
Miss a colon next to the settings on 'Connection Summary' dialog when attaching RBAC containers

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1540]
**Storage Explorer Version:** 1.9.0_**master**_20190709.5
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** 8a04af7f
**Regression From:** Not a regression

**Steps to reproduce:**
1. Give RBAC access to a container to a user like '**Blob Data Owner Role**'.
2. Copy a URL of one blob container -> Open Connect dialog -> Select 'Add a resource via Azure Directory(Azure AD)' -> 'Next'.
3. On the second page, choose the account with access to the resource and the subscription that the resource is in.
4. On the third page, paste a URL to the container -> 'Next'.
5. Check the connection summary on the last page.

**Expect Experience:**

There shows colons next to the settings.

**Actual Experience:**

Miss a colon next to the settings.
![image](https://user-images.githubusercontent.com/34729022/60958775-8452e800-a339-11e9-84c0-c55dd47c28e2.png)

**Comment by v-limu** [comment]
This issue has been fixed on build [20190927.10](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3091851). So close it.
