### ISSUE TITLE
Unable to sign in on ADFS Azure Stack

### ISSUE THREAD

**Issue by MilanNXT** [microsoft/AzureStorageExplorer#1543]
**Storage Explorer Version**: all version including 1.9.0
**Build Number**: 20190701.8
**Platform/OS**: Windows 10 (1803)
**Architecture**:  x64
**Regression From**:  tried in all versions from 1.5 but no luck

## Bug Description ##
Unable to sign in to Azure stack ADFS

## Steps to Reproduce ##
1. Storage Explorer switched to Stack API
2. Adding account 
3. Select Custom environment
4. Populating ARM endpoint
5. click sign-in
6. new blank window is open with caption StorageExplorer. should display and ask for login information but remain blank.

## Expected Experience ##
Sign in using username and credentials
## Actual Experience ##
No able to sign in 

## Additional Context ##
Tried also to import root CA certificates but no help

**Comment by MRayermannMSFT** [comment]
Hey @MilanNXT can you try using device code flow? You can enable it from the  "Preview" menu at the top. After enabling it try signing in again. Device code flow redirects the sign in experience to your browser, which should get you past the blank sign in dialog.

**Comment by pmanvoj** [comment]
Hi, I have followed the sollution suggested above and got one step further. The behaviour has chnaged however I got stuck during the next screen where sign in process starts. The behaviour on my side is that the spinning circle appears and nothing more happens. See also the attached picture. 
![CaptureSESignIn](https://user-images.githubusercontent.com/28111950/63094985-4cf3de80-bf6a-11e9-840a-d15251a0a9bc.PNG)
Any advice? Thanks.

**Comment by MRayermannMSFT** [comment]
Are y'all still having issues when using the latest version of Storage Explorer?

**Comment by pmanvoj** [comment]
HI, we tested the latest version.
1) Wesuccessfully connected to the storage using name and key approach
2) Using Device code + MSAL we are able to connect to the Azure stack environment and the tool also loads all available subscriptions, see picture attached.  Once we tried to expand one of them, we are getting error
![image](https://user-images.githubusercontent.com/28111950/71962734-67b93f00-31fa-11ea-84fb-a68417e75e2e.png)
This is a log from dev console, it seems that the tool sends something "outside", is it so???
![image](https://user-images.githubusercontent.com/28111950/71962923-d8605b80-31fa-11ea-9173-9bbfb4c4e689.png)

**Comment by MRayermannMSFT** [comment]
What version did you test with? Can you make sure to test against version 1.12.0?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you're still having problems. Thanks.
