### ISSUE TITLE
Display a wrong tooltip when hovering over the 'Undelete' icon for one blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1546]
**Storage Explorer Version:** 1.9.0_master_20190711.5
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** a1cd90ad
**Regression From:** Previous release(1.9.0)

**Steps to reproduce:**
1. Expand a Non-ADLS Gen2 account -> Blob Container.
2. Create a new blob container -> Hover over the 'Undelete' icon on the toolbar.
3. Check the tooltip.

**Expected Experience:**
The tooltip shows 'Undelete'.
![image](https://user-images.githubusercontent.com/41351993/61033364-ecff9a80-a3f5-11e9-88a0-712f00e7143b.png)

**Actual Experience:**
The tooltip shows 'ASX_UndoDropdown_blue23x19'.
![image](https://user-images.githubusercontent.com/41351993/61033373-f2f57b80-a3f5-11e9-8e00-cf0a61e9ec3a.png)

**More Info：**
1. This issue also reproduces on feature/main-host 20190711.2.
2. This issue doesn't reproduce when hovering over the 'Undelete' item.
3. This issue also reproduces when hovering over the 'Move' icon for one ADLS Gen1 account.
![image](https://user-images.githubusercontent.com/41351993/61033515-3e0f8e80-a3f6-11e9-83d3-955185f788f4.png)

**Comment by v-xianya** [comment]
This issue also reproduces for toolbar 'Pin to Quick access' on the build master/20190711.8 for one ADLS Gen1 account.
![image](https://user-images.githubusercontent.com/41351993/61111700-b80a4b00-a4bc-11e9-9dd9-74bdf7fffba6.png)

**Comment by v-xuanzh** [comment]
This issue has been fixed on the latest master build 20190717.6. So closed it,
