### ISSUE TITLE
Keep a consistent tooltip for the '+' button on Query Builder

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1547]
**Storage Explorer Version:** 1.9.0_**master**_20190711.5
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** a1cd90ad
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand a storage account -> Tables.
2. Create a new table.
3. Click 'Query' button -> Click 'Add new clause' to add new filter line.
4. Hover over these two '+' buttons and observe the corresponding tooltips.

**Expected Experience:**
Keep a consistent tooltip for these two '+' buttons.

**Actual Experience:**
Display an inconsistent tooltip for these two '+' buttons.
![image](https://user-images.githubusercontent.com/41351993/61034467-e40fc880-a3f7-11e9-85e3-2b1d4b35912b.png)

**Comment by MRayermannMSFT** [comment]
Change all to "Add new clause"

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT  
Since the tooltip "Insert new filter line" will be changed to "Add new clause". We think it would be better using the tooltip "Remove this clause" other than "Remove this filter line".
![image](https://user-images.githubusercontent.com/41351993/61260112-91475f80-a7af-11e9-84ee-0bbe4af0eaa8.png)

**Comment by jinglouMSFT** [comment]
The fix has been merged into Master.
