### ISSUE TITLE
Changing the current instance theme affects other opened instances when opening multiple instances

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1548]
**Storage Explorer Version:** 1.9.0_**feature/main-host**_20190711.2
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Commit:** a1cd90ad
**Regression From:** Previous release 1.9.0

**Steps to reproduce:**
1. Launch Storage Explorer and make sure the current theme is **default**.
2. Press Ctrl+Shift+N to open a new window.
3. Change the theme of second instance to **dark**.
4. Check the first instance theme.

**Expect Experience:**

The first instance theme is **default**.

**Actual Experience:**

The first instance theme is changed to **dark**.

**More info:**
1. This issue doesn't reproduce on latest master build 20190711.5.
2. This issue also reproduces on previous release 1.9.0.

**Comment by craxal** [comment]
By design. Settings are now centralized into a settings.json file, from which all instances read.
