### ISSUE TITLE
Unable to retrieve resources for one attached Table account

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1549]
**Storage Explorer Version:** 1.9.0
**Branch:** master
**Build:** 20190711.8
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Create a cosmos db account with Table API.
2. Navigate to the created account from Storage Explorer.
3. Copy the Primary Connection String then open 'Connect to Cosmos DB' dialog.
4. Select Table API then paste the connection string -> 'Next'.
5. Try to expand the attached table account from 'Local & Attached' -> 'Cosmos DB Accounts(Preview)'.

**Expect Experience:**

The attached table account can be expanded successfully.

**Actual Experience:**

Fail to expand the attached table account with the below error.
![image](https://user-images.githubusercontent.com/34729022/61113649-4aace900-a4c1-11e9-81dc-67fe8718eb29.png)

**More info:**

This issue doesn't reproduce for one attached SQL account.

**Comment by craxal** [comment]
Confirmed bug reproduces on 1.9.0, so definitely not due settings infrastructure merge. It's unclear how long this has been broken.

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
