### ISSUE TITLE
All the panels are not fully been themed after changing the current theme

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1551]
**Storage Explorer Version:** 1.9.0
**Branch:** master
**Build:** 20190711.8
**Platform/OS:** Linux Ubuntu
**Architecture:** x64
**Regression From:** Previous release 1.9.0

**Steps to reproduce:**
1. Launch Storage Explorer and make sure the current theme is default.
2. Change the current theme to dark.
3. Check whether these panels are themed or not.

**Expect Experience:**

All the panels are themed.

**Actual Experience:**

All the panels are not fully been themed.
![image](https://user-images.githubusercontent.com/34729022/61113279-7380ae80-a4c0-11e9-83a8-63aadff48f45.png)

**Comment by craxal** [comment]
See #1550.
