### ISSUE TITLE
Default selected item should be the current Access tier in 'Update Access Tier' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#156]
**Storage Explorer Version**: 1.1.0 RC

**Platform**: Windows/Linux/Mac

**Architecture**: ia32/x64

**Build Number**: 20180507.1

**Commit**: bcc8990d

**Regression From**: Not a regression

#### Steps to Reproduce: ####

1. Launch Storage Explorer and expand a blob account.
2. Right click the account and set the default Access Tier to 'Cool'.
3. Reopen the 'Update Access Tier' dialog and check the default selected item.

#### Expected Experience: ####

The default selected item is the current Access Tier 'Cool'.

#### Actual Experience: ####

'Hot' still is selected in the 'Update Access Tier' dialog.
![default](https://user-images.githubusercontent.com/34729022/39750291-67cbf60e-52a4-11e8-84d9-b77d1c91ec2a.png)

**Comment by v-xianya** [comment]
Verified this issue on the latest build 20190614.7. It still reproduces. Could you help to take a look?

**Comment by v-xianya** [comment]
Verified this issue on build 20201116.2. Fixed.
