### ISSUE TITLE
There shows an inconsistent icon between the tree view and opened tab for one UDF

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1563]
**Storage Explorer Version:** 1.9.0
**Branch**: master
**Build**: 20190716.7
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one SQL account -> Database -> Collection.
2. Create a UDF -> Check the icon between the tree view and the opened tab.

**Expect Experience:**

There shows a consistent icon.

**Actual Experience:**

There shows an inconsistent icon.
![image](https://user-images.githubusercontent.com/34729022/61282656-531d6080-a7ee-11e9-9926-7041574b4c8c.png)

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
