### ISSUE TITLE
Use 'OK' instead of 'Ok' on 'Node Error' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1568]
**Storage Explorer Version:** 1.9.0
**Branch**: master
**Build**: 20190719.7
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Not a regression

## Bug Description ##
I have attached one blob container then deleted its account from Azure Portal. After about 24h, the attached blob container shows as broken. Clicking 'View Error' shows 'Ok' rather than 'OK' on 'Node Error' dialog.
![image](https://user-images.githubusercontent.com/34729022/61522994-1350b600-aa46-11e9-8d08-91705a1b1842.png)

![image](https://user-images.githubusercontent.com/34729022/61522327-be607000-aa44-11e9-8816-e023a5b1ce9b.png)

## Steps to Reproduce ##
1. Attach one blob container with SAS URI.
2. Try to delete its account.
3. Wait for about 24h.
4. Observe the attached blob container from (Attached Containers) node.
5. This blob container shows as broken, then click 'View Error' on the context menu.

**Comment by MRayermannMSFT** [comment]
This bug no longer repro's. We've switched to using the error details dialog in this scenario.
