### ISSUE TITLE
The property's value of default Access Tier doesn't auto change

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#157]
**Storage Explorer Version**: 1.1.0 RC

**Platform**: Windows/Linux/Mac

**Architecture**: ia32/x64

**Build Number**: 20180507.1

**Commit**: bcc8990d

**Regression From**: Not a regression

#### Steps to Reproduce: ####

1. Launch Storage Explorer and expand a blob account. 
2. Right click the account and set the default Access Tier to 'Cool'. 
3. Check the value of default Access Tier in Properties Panel.

#### Expected Experience: ####

The value of default Access Tier auto change to 'Cool'.

#### Actual Experience: ####

The value of default Access Tier still displays as 'Hot'.
![autorefresh](https://user-images.githubusercontent.com/34729022/39750539-02bf6272-52a5-11e8-9bbc-7fcf887c8a27.png)

**Comment by MRayermannMSFT** [comment]
Let's:
- Update wording/icon in the activity to make what's going on more clear
- Think about polling for `Default Access Tier`, but probably not

**Comment by v-xianya** [comment]
Verified this issue on the latest build 20190614.7. It still reproduces. Could you help to take a look?

**Comment by MRayermannMSFT** [comment]
@v-xianya does this still reproduce on latest builds from main? :P

**Comment by v-xianya** [comment]
@MRayermannMSFT  This issue still reproduces on build main/20201020.3.  （The Default access tier updated after manually refreshing the account node）
![image](https://user-images.githubusercontent.com/41351993/96533215-13320c80-12c0-11eb-934f-489692c47989.png)

**Comment by v-xianya** [comment]
Verified this issue on build 20201116.2. Fixed.
