### ISSUE TITLE
Azure Storage Explorer fails when trying to upload files into an Storage Account from a Sharepoint or OneDrive folder

### ISSUE THREAD

**Issue by AubinHdez** [microsoft/AzureStorageExplorer#1571]
**Storage Explorer Version**: 1.9.0
**Build Number**: 20190701.8
**Platform/OS**: Windows 10
**Architecture**:  x64
**Regression From**:  No

## Bug Description ##
Azure Storage Explorer fails when trying to upload files into an Storage Account from a Sharepoint or OneDrive folder. The same file from a local folder in the same computer is uploaded successfully to the same target Storage Account. Also using azcopy from command line works uploading the same file from the Sharepoint or OneDrive folder, so it is only failing in Azure Storage Explorer. 

The error shared in Azure Storage Explorer is the following:
{
  "message": "\"failed to perform copy command due to error: cannot start job due to error: nothing can be uploaded, please use --recursive to upload directories.\\n\""
}

## Steps to Reproduce ##
1. Drag and drop any file from a mapped sharepoint or onedrive folder to an storage account available (already mapped) in the Azure Storage Explorer
Exactly same issue if using upload functionality

## Expected Experience ##
File uploaded successfully with a similar experience that uploading the file form a local folder in the laptop..

## Actual Experience ##
File upload fails with error:
Transfer of 'C:\Users\xxxxx\yyyyy\zzzzz - dd_b\08 Team shared\Templates\test file.docx' to 'raw/' failed: error: failed to perform copy command due to error: cannot start job due to error: nothing can be uploaded, please use --recursive to upload directories. (used name and key, discovery not completed)

Azcopy command:
$env:AZCOPY_CRED_TYPE = "SharedKey";
$env:ACCOUNT_NAME = "??????";
$env:ACCOUNT_KEY = "??????";
./azcopy.exe copy "C:\Users\xxxxx\yyyyy\zzzzz - dd_b\08 Team shared\Templates\test file.docx" "https://xxxxxx.dfs.core.windows.net/raw/test file.docx" --overwrite=false --follow-symlinks --recursive --from-to=LocalBlobFS --put-md5;
$env:AZCOPY_CRED_TYPE = "";
$env:ACCOUNT_NAME = "";
$env:ACCOUNT_KEY = "";

## Additional Context ##
N/A

**Comment by zezha-msft** [comment]
Hi @AubinHdez, thanks for reaching out!

To confirm, when you ran AzCopy directly from the command line, did you include `--follow-symlinks`?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
