### ISSUE TITLE
Cannot add an account using Code Flow

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1572]
**Storage Explorer Version:** 1.9.0
**Branch**: master
**Build**: 20190722.3
**Platform/OS:** Linux Ubuntu/macOS High Sierra
**Architecture:** x64
**Regression From:** Previous release 1.9.0

**Steps to reproduce:**
1. Launch Storage Explorer and make sure the 'Use Device Code Flow Sign-in' is enabled.
2. Open 'Connect' dialog -> Try to add an account -> 'Next'.
3. Verify the second page of Connect dialog.

**Expect Experience:**

It prompts users copy code and open browser to sign in.
![image](https://user-images.githubusercontent.com/34729022/61618148-cae00500-ac9e-11e9-85e7-f6e5acbeccaf.png)

**Actual Experience:**

The sign in dialog pops up.
![image](https://user-images.githubusercontent.com/34729022/61618160-d16e7c80-ac9e-11e9-9042-15a0f6ec33eb.png)

**More info:**

This issue doesn't reproduce on Windows installed the same build.

**Comment by v-xianya** [comment]
This issue also reproduces on Windows with the build master/20190806.12.

**Comment by v-xianya** [comment]
This issue has been fixed on build master/20190815.2. So we close it.
