### ISSUE TITLE
RBAC permissions - rename/copy/paste disabled for Storage Blob Data Contributor

### ISSUE THREAD

**Issue by johnayoub** [microsoft/AzureStorageExplorer#1573]
**Storage Explorer Version**: 1.9.0
**Build Number**: 20190701.8
**Platform/OS**:  windows 7
**Architecture**: 32
**Regression From**:  don't think so

## Bug Description ##
A user with the following RBAC (Storage Blob Data Contributor) can't perform a copy/rename 

## Steps to Reproduce ##
1. Grant Reader permission on storage account
2. Grant Storage Blob Data Contributor on a container

## Expected Experience ##
Should be able to rename/ copy. 

## Actual Experience ##
Rename/ copy/ paste buttons are disabled. Upload/deleting works fine

**Comment by MRayermannMSFT** [comment]
Hi @johnayoub , when you are accessing storage via RBAC, copy, paste, and rename are unavailable. This is because those features rely on generating a SAS token which currently isn't supported when you don't have access to the account key. In the future it will be possible but as of today it is not.

**Comment by sid5233** [comment]
Hi, In my Storage Explorer, I connected using the Access key and VPN to access the private endpoint of my storage. I could upload but was unable to delete and rename the blob.
