### ISSUE TITLE
Update the Rename dialog's title to 'Rename File' for one file under file shares

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1575]
**Storage Explorer Version:** 1.9.0
**Branch:** master
**Build:** 20190724.6
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> File Shares.
2. Create a new file share -> Upload a file to it.
3. Try to rename the file and check the prompt dialog.

**Expect Experience**:

Display the prompt dialog't title as 'Rename File'.

**Actual Experience:**

Display the prompt dialog't title as 'Rename'.
![image](https://user-images.githubusercontent.com/41351993/61776359-70c17a00-ae2d-11e9-9c09-eb3138ef6293.png)

**More Info:**
1. This issue also reproduces when trying to rename a directory.
2. This issue doesn't reproduce for one blob.
![image](https://user-images.githubusercontent.com/41351993/61776552-dc0b4c00-ae2d-11e9-87c2-b8cf78582028.png)

**Comment by v-limu** [comment]
Verified this issue on build [20191220.9](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3338616). The feature has been changed. So we close it.
