### ISSUE TITLE
Keep a consistent layout in the Rename/Clone dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1577]
**Storage Explorer Version:** 1.9.0
**Branch:** master
**Build:** 20190724.6
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one Non-ADLS Gen2 account -> Blob containers.
2. Create a new blob container -> Upload one blob.
3. Try to rename the blob -> Check the layout in the Rename dialog.

**Expect Experience**:
Keep a consistent layout with other rename dialogs. Like: rename one file under file share / rename one blob container/ rename one file share/ rename one table.
![image](https://user-images.githubusercontent.com/41351993/61777010-bd598500-ae2e-11e9-8f69-0fabacd165d8.png)

**Actual Experience:**
Show a different layout with other rename dialogs.
![image](https://user-images.githubusercontent.com/41351993/61777028-cd716480-ae2e-11e9-9be6-9ddc0e0ff51c.png)

**More Info:**
1. This issue also reproduces for one folder under blob containers.

**Comment by MRayermannMSFT** [comment]
To do at same time: #1575

**Comment by MRayermannMSFT** [comment]
Work finally done!
