### ISSUE TITLE
Update upload dialog's title for blob containers

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1578]
**Storage Explorer Version:** 1.9.0
**Branch:** master
**Build:** 20190724.6
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Create a new blob container ->Click the 'Upload' button then select 'Upload Files...'
3. Check the prompt dialog.

**Expect Experience**:
The prompt dialog's title shows 'Upload Files to blob container'.

**Actual Experience:**
The prompt dialog's title shows 'Upload to blob container'.
![image](https://user-images.githubusercontent.com/41351993/61777546-ad8e7080-ae2f-11e9-83c1-5e7283426535.png)

**More Info:**
1. This issue doesn't reproduce for one file share.
2. This issue also reproduces for uploading a folder to blob containers.

**Comment by MRayermannMSFT** [comment]
Nice suggestion, but won't fix. 😄
