### ISSUE TITLE
The scrollbar still displays on Account Panel after maximizing Storage Explorer

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#158]
**Storage Explorer Version**: 1.1.0 RC

**Platform**: Windows/Linux/Mac

**Architecture**: ia32/x64

**Build Number**: 20180507.1

**Commit**: bcc8990d

**Regression From**:  Not a regression

#### Steps to Reproduce: ####

1. Launch Storage Explorer and sign in with your account.
2. Maximize Storage Explorer and check whether scrollbar displays on Account Panel or not.

#### Expected Experience: ####

No scrollbar displays on Account Panel after maximizing Storage Explorer.

#### Actual Experience: ####

The scrollbar still displays on Account Panel after maximizing Storage Explorer.
![scrollbar](https://user-images.githubusercontent.com/34729022/39752029-b840c40c-52a9-11e8-9330-813d5c6f29d0.png)

**Comment by craxal** [comment]
The scrollbar is there because the subscription text overflows horizontally. You can resize the panel.
