### ISSUE TITLE
I've made an error and I need to delete some files to start again

### ISSUE THREAD

**Issue by adrianedgar** [microsoft/AzureStorageExplorer#1581]
**Storage Explorer Version**: 1.9.0
**Build Number**: 20190701.8
**Platform/OS**: 
**Regression From**:

**Comment by adrianedgar** [comment]
{
  "name": "StorageError",
  "message": "This request is not authorized to perform this operation using this permission.\nRequestId:5c3ce8da-e01e-0062-5c58-422f80000000\nTime:2019-07-24T19:45:21.6800886Z",
  "stack": "StorageError: This request is not authorized to perform this operation using this permission.\nRequestId:5c3ce8da-e01e-0062-5c58-422f80000000\nTime:2019-07-24T19:45:21.6800886Z\n    at Function.StorageServiceClient._normalizeError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:1205:23)\n    at Object.StorageServiceClient._processResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:751:50)\n    at Request.processResponseCallback [as _callback] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:319:37)\n    at Request.self.callback (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1157:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1079:12)",
  "code": "AuthorizationPermissionMismatch",
  "statusCode": 403,
  "requestId": "5c3ce8da-e01e-0062-5c58-422f80000000"
}

**Comment by MRayermannMSFT** [comment]
This is a permissions error. How are you accessing your storage? Did you sign in? Did you attach with SAS? Did you attach with Azure AD?

**Comment by TOMY0616** [comment]
Hello,

I'am uploading files via AzCopy to Azure storage example

AzCopy.exe /Source:<Location of PST files> /Dest:<SAS URL> /V:<Log file location> /Y

It's ok , i have files (pst) in Blob Containers > Ingestiondata (SAS)

When i want to delete files i can't delete it

{
  "name": "StorageError",
  "message": "This request is not authorized to perform this operation using this permission.\nRequestId:903e8fe9-b01e-0124-263d-48c2c9000000\nTime:2019-08-01T07:48:17.5021559Z",
  "stack": "StorageError: This request is not authorized to perform this operation using this permission.\nRequestId:903e8fe9-b01e-0124-263d-48c2c9000000\nTime:2019-08-01T07:48:17.5021559Z\n    at Function.StorageServiceClient._normalizeError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:1205:23)\n    at Object.StorageServiceClient._processResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:751:50)\n    at Request.processResponseCallback [as _callback] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:319:37)\n    at Request.self.callback (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1157:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1079:12)",
  "code": "AuthorizationPermissionMismatch",
  "statusCode": 403,
  "requestId": "903e8fe9-b01e-0124-263d-48c2c9000000"
}

Azure Storage Sign in (SAS) or Azzure Account

**Comment by adrianedgar** [comment]
Its a SAS ket from a PST import.  Indeed no delete permission.  
I got round it in the end by creating a sub folder and using that.
We don't see this storage account in our Azure subscription so I assume its a space provided by MS for the migration.
