### ISSUE TITLE
Blob storage upload issue

### ISSUE THREAD

**Issue by mikhadmimars** [microsoft/AzureStorageExplorer#1582]
Hi,

I can’t upload file to Blob (I had similar issue with other files). Could you help me please?
I tried both through application and browser.
Thanks!

{
  "message": "\"failed to perform copy command due to error: cannot start job due to error: nothing can be uploaded, please use --recursive to upload directories.\\n\""
}

$env:AZCOPY_CRED_TYPE = "Anonymous";
./azcopy.exe copy "C:\Users\mikhadmi\Mars Inc\MGS Culture of Performance - Dashboard Data Inputs\MGS Finance\ICB NA Aging Reports\2019_P07_Aging Report_CC412.xlsx" "https://mgsperformancedevsa.blob.core.windows.net/vendordata/MGS%20Finance/ICB%20NA%20Aging%20Reports/2019_P07_Aging%20Report_CC412.xlsx?se=2019-07-28T11%3A29%3A26Z&sp=rwl&sv=2018-03-28&sr=c&sig=JOU0ldV4ouvaRaRBuztf91HwseddkvfCJ3acKRDBnhY%3D" --overwrite=false --follow-symlinks --recursive --from-to=LocalBlob --blob-type=BlockBlob --put-md5;
$env:AZCOPY_CRED_TYPE = "";

**Comment by MRayermannMSFT** [comment]
@mikhadmimars can you attach your azcopy logs to the issue? when you get the failure, you should see an "Open AzCopy logs" action or something like that which will you take you to the log file for that specific upload/download.

**Comment by mikhadmimars** [comment]
Yes, please:

$env:AZCOPY_CRED_TYPE = "Anonymous";
./azcopy.exe copy "C:\Users\mikhadmi\Mars Inc\MGS Culture of Performance - Dashboard Data Inputs\MGS Finance\2019_P07_FI61.EU_IC AR Ageing.xlsx" "https://mgsperformancedevsa.blob.core.windows.net/vendordata/MGS%20Finance/2019_P07_FI61.EU_IC%20AR%20Ageing.xlsx?se=2019-07-29T08%3A12%3A12Z&sp=rwl&sv=2018-03-28&sr=c&sig=Bk5Ro3aRfjRsTCMVRmf9P0X6wk0N8kGkiMBBohGksDo%3D" --overwrite=false --follow-symlinks --recursive --from-to=LocalBlob --blob-type=BlockBlob --put-md5;
$env:AZCOPY_CRED_TYPE = "";

  Dima Mikhaylov
  Global Performance Insights Manager | Mars Global Services Performance Center

**Comment by MRayermannMSFT** [comment]
@mikhadmimars that is the command used to perform the upload. There should also be an action to  "Go to AzCopy Log File". That should take you to a .txt file AzCopy produces. Can you attach that to a reply to this issue? Thanks.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
