### ISSUE TITLE
Keep consistent between the action name and its corresponding dialog's title 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1585]
**Storage Explorer Version:** 1.9.0
**Branch:** master
**Build:** 20190725.2
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Right click a storageV2 account -> Select "Set Default Access Tier".
2. Check the prompt dialog's title.

**Expect Experience:**
It keeps consistent between the action name and its corresponding dialog's title 

**Actual Experience:**
It is inconsistent between the action name and its corresponding dialog's title 

![image](https://user-images.githubusercontent.com/41351993/61938649-33dbbb80-afc4-11e9-9141-c44320ec5f85.png)

**More Info:**
This issue also reproduces for one blob's action 'Change Access Tier...' and its corresponding dialog't title.
![image](https://user-images.githubusercontent.com/41351993/61938643-31796180-afc4-11e9-9a82-05dd431913df.png)

**Comment by MRayermannMSFT** [comment]
Won't fix. We're getting rid of those dialog titles soon.
