### ISSUE TITLE
Add the container name to the log message when uploading files to one blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1587]
**Storage Explorer Version:** 1.9.0
**Branch:** master
**Build:** 20190725.2
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Make sure 'Use AzCopy for Improved Blob Upload and Download' is unchecked.
2. Expand a Non-ADLS Gen2 account -> Blob Containers.
3. Create a new blob container -> Upload a file to it.
4. Check the Activities.

**Expect Experience:**
Show "Uploaded '_file_name_' to '_conatiner_name/file_name_'"

**Actual Experience:**
Show "Uploaded '_file_name_' to '_file_name_'
![image](https://user-images.githubusercontent.com/41351993/61937302-240ea800-afc1-11e9-8e24-f7d5b006f813.png)

**Comment by MRayermannMSFT** [comment]
Won't fix. AzCopy will become default upload/download path in the near feature.
