### ISSUE TITLE
There shows an inconsistent account name between the last page of 'Connect to Cosmos DB' dialog and the tree view

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1590]
*Storage Explorer Version:** 1.9.0
**Branch:** master
**Build:** 20190725.2
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Add a China Account(Mooncake) to Storage Explorer -> Create a SQL account.
2. Navigate to the created account then copy the primary connection string.
3. Open the 'Connect to Cosmos DB' dialog -> Paste the copied connection string with the SQL API.
4. Click 'Next' -> Check the shown Account name.

**Expect Experience:**

There only shows the account name.

**Actual Experience:**

There shows the 'account_name'.azure.cn.443.
![image](https://user-images.githubusercontent.com/34729022/61943462-0ac02880-afce-11e9-95be-02067a8bdf84.png)

**More info:**
This issue doesn't reproduce for Table account of the same Mooncake account.

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
