### ISSUE TITLE
Storage Explorer crashes when there appears multiple searched results

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1591]
**Storage Explorer Version**: 1.9.0
**Branch:** master
**Build:** 20190725.2
**Platform/OS:** Linux Ubuntu 19.04
**Architecture:** x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer from the terminal.
2. Add your account to SE then apply all the subscription.
3. Search the 'Table' wards from the search box.
4. Click any of the searched result -> Check the results.

**Expect Experience:**

Storage Explorer works well even though there are multiple search results.

**Actual Experience:**

There are two cases for the experience:
Storage Explorer crashes with the below error.
![image](https://user-images.githubusercontent.com/34729022/61943887-06483f80-afcf-11e9-859f-e80afe8504d8.png)

**More info:**
This issue doesn't reproduce on Mac/Windows.

**Comment by MRayermannMSFT** [comment]
@v-xuanzh are you doing search in the tree view or search in the table editor?

**Comment by v-xuanzh** [comment]
Hi @MRayermannMSFT , I did this search action on the tree view.

I have sent a mail to you and recorded a video for it.

**Comment by JasonYeMSFT** [comment]
This is due to extremely high memory usage when you have a lot of search results. Windows and MacOS are more tolerant on application's memory usage.

**Comment by MRayermannMSFT** [comment]
Closing.
