### ISSUE TITLE
unable to sign in on macOs

### ISSUE THREAD

**Issue by azdatascience** [microsoft/AzureStorageExplorer#1594]
**Storage Explorer Version**: 1.9.0 and 1.6.2
**Build Number**: 20190701.8
**Platform/OS**: macOs
**Architecture**: 
**Regression From**:  n/a

## Bug Description ##

I am unable to sign-in and get the following error message
```
{
  "message": "\"An error occurred while sending the request.\""
}
```

## Steps to Reproduce ##

1. download and install azure storage explorer for mac
2. "add an account"
3. login and go through SSO for my company
4. error

## Additional Context ##

I tried both inside my company network, configuring a proxy and outside, using guest wifi + no proxy.

**Comment by alex2345235235342** [comment]
I get the same error.  The poster has included the full content of the logs:

> Unable to sign in: An error occurred while sending the request.
> {
>   "message": "\"An error occurred while sending the request.\""
> }

**Comment by MRayermannMSFT** [comment]
Hi, sorry that you're having trouble loading subscriptions. There's some fairly involved steps I'd like you to take to help us diagnose what's going wrong. I know it's a lot, but this is what will help us figure out how to help you. If you have any problems with the below steps let us know and we'll do our best to help you. If you don't have time to do all of these steps, then you can probably ignore the proxy and Fiddler stuff for now, but it's usually easiest to get all of this collected in one go.

Note: these steps are for Windows, let me know if you need them for another OS.

Part 1: Reset Auth/Sign Out of Everything
1. Open Storage Explorer
2. Go to "Help" -> "Reset", make sure "Authentication" is selected (you can deselect "Quick Access" if you'd like), click "Reset"
3. After the reset dialog closes, go to "Edit" -> "Configure Proxy". Enable proxy, set the URL to 'http://localhost' and the port to '8888' (if you already have a proxy, skip this step and ignore all steps related to Fiddler), click "OK"
4. Close Storage Explorer

Part 2: Setup Fiddler
1. Install Fiddler from https://www.telerik.com/fiddler (Note: you can put in a fake email when they ask you for one 😋)
2. Start Fiddler
3. Go to Tools -> Options
4. Click on the HTTPS tab
5. Make sure Capture HTTPS CONNECTs and Decrypt HTTPS traffic are checked
6. Click on the Actions button
7. Choose "Trust Root Certificate" and then "Yes" in the next dialog
8. Click on the Actions button again
9. Choose “Export Root Certificate to Desktop”
10. Go to your desktop
11. Find the FiddlerRootCer file
12. Double click to open
13. Go to the "Details" tab
14. Click "Copy to File…"
15. In the export wizard choose the following options
    - Base-64 encoded X.509
    - For file name, Browse… to `C:\Users\<your username\AppData\Roaming\StorageExplorer\certs`, and then you can save it as any file name
16. Close the certificate window

Part 3: Clear Auth Logs
1. Go to C:\Users\<your username>\AppData\Local\Temp\servicehub\logs
2. Delete Everything

Part 4: Try Loading Subscriptions!
1. Open PowerShell
2. Goto where Storage Explorer is installed, if you installed at the default location you can just do `cd 'C:\Program Files (x86)\Microsoft Azure Storage Explorer\'`
3. Execute `$env:SERVICEHUBTRACELEVEL="all"`
4. Close as many other running programs as possible (excluding Fiddler and PowerShell)
5. Start Storage Explorer from PowerShell: `.\StorageExplorer.exe`
6. Try signing in, after your issue happens, close Storage Explorer
7. In Fiddle, in the bottom left where it says "Capturing", click that, and then "File" -> "Save All Sessions", and save the file wherever you'd like

Part 5: Share results with us
1. Go back to `Go to C:\Users\<your username>\AppData\Local\Temp\servicehub\logs`
2. Zip up all of the log files and attach them to a comment on this issue
3. **Do not attach us the file you saved in Part 4!!!** If we need that, we'll give you an email to send it to. That type of file can contain some super sensitive information so we do not want you putting it in a public place.

**Comment by alex2345235235342** [comment]
The subject line is for the bug on macOS.  The debugging for Windows isn't appropriate.  I have also configured my proxy and tried all troubleshooting methods available.
I was able to find a hack to get connected - use Connection String.  This works, but signing into Azure doesn't.  I have very many storage accounts, so using Connection Strings is a poor workaround.

**Comment by craxal** [comment]
@alex2345235235342 What kind of proxy are you working behind? Does it have NTLM authentication or any other complex configurations or features?

**Comment by alex2345235235342** [comment]
Likely the firewall is complex - I don't have direct details, but am working at a telecom company that puts in many layers of network security.

**Comment by MRayermannMSFT** [comment]
@alex2345235235342 have you tried recently with 1.10? We shipped a bug fix in there for a macOS sign-in proxy issue.

**Comment by JasonYeMSFT** [comment]
Close due to no reply.

**Comment by susierao** [comment]
I am using 1.12 and 1.13, both do not allow to me to log in with my azure account...
