### ISSUE TITLE
CosmosDB Accounts: Unable to delete multiple documents at once

### ISSUE THREAD

**Issue by tmeadlin** [microsoft/AzureStorageExplorer#1595]
It would be helpful to be able to be able to ctrl + click or shit + click and be able to delete those documents at once rather than selecting one, clicking delete, and on to the next one. If this is currently implemented, it is not that visible to the user.

**Comment by southpolesteve** [comment]
Thanks for the feedback! Will add it to our backlog

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
