### ISSUE TITLE
Pop up an error when setting 'Proxy' using custom proxy settings

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1597]
**Storage Explorer Version:** 1.9.0
**Branch:** master
**Build:** 20190729.3
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Previous release(1.9.0)

**Steps to reproduce:**
1. Make sure Fiddler has been installed and set well.
2. Launch storage explorer -> Click 'Edit' -> 'Configure Proxy'.
3. Select 'Use custom proxy settings' then enter URL(**localhost**) and port(**8888**) -> Click 'OK'.

**Expect Experience:**
No error occurs.

**Actual Experience:**
Pop up an error dialog as below.
![image](https://user-images.githubusercontent.com/41351993/62116105-2e47e380-b2ec-11e9-94da-c0095af7368b.png)

**More info:**
1. Show odd values of URL and Port on the 'Proxy Settings' dialog.
![image](https://user-images.githubusercontent.com/41351993/62116973-b1b60480-b2ed-11e9-9557-ec72afc66ce8.png)
2. The option 'Do not use proxy' is always selected after reopening the 'Proxy Settings' dialog.

**Comment by craxal** [comment]
Ah, well obviously we’re expecting a number value and not a string.

@JasonYeMSFT Can you fix this? I believe you’ve been tinkering with configurations.

**Comment by JasonYeMSFT** [comment]
The new configuration settings have been merged. This should work now. Please reopen it if there is still any issue.
