### ISSUE TITLE
Save dialog's initial location isn't consistent/persisted

### ISSUE THREAD

**Issue by JakeRadMSFT** [Microsoft/AzureStorageExplorer#16]
**Storage Explorer Version**: 0.9.6
**OS Version**: Windows 10/MacOs

**Steps to Reproduce**:

1. Download one folder to FolderA\FolderB\FolderC\FolderD\FolderE.
2. Download another folder. It'll default to FolderA\FolderB\FolderC\FolderD
3. Download another folder. It'll default to FolderA\FolderB\FolderC
4. Download another folder. It'll default to FolderA\FolderB\
5. Download another folder. It'll default to FolderA

**Expected Experience**:
Save dialog opens to last location

**Actual Experience**:
Save dialog opens to parent of last location

**Comment by craxal** [comment]
Unable to repro in 1.6.2. Not sure if it's something we did or if an Electron upgrade changed something. @v-xuanzh, can your team verify this, please?

**Comment by v-xuanzh** [comment]
Hi @craxal , we verified this issue on latest build 20190115.1. You can get the details from below. 
1. Unable to reproduce when downloading **files** to the folder with multiple layers.
2. This issue still reproduces when downloading **folders** to the local folder with multiple layers.

**Steps to reproduce:**
1. Download one **folder** to FolderA\FolderB\FolderC\FolderD\FolderE
2. Download another **folder** it'll default to FolderA\FolderB\FolderC\FolderD
3. Download another **folder** it'll default to FolderA\FolderB\FolderC
4. Download another **folder** it'll default to FolderA\FolderB\
5. Download another **folder** it'll default to FolderA

**Expected Experience**:
Save dialog opens to last location

**Actual Experience**:
Save dialog opens to parent of last location
