### ISSUE TITLE
No ‘Access Tier’ column displays for one attached blob container with SAS

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#160]
**Storage Explorer Version**: 1.1.0 RC

**Platform**: Windows/Linux/Mac

**Architecture**: ia32/x64

**Build Number**: 20180507.1

**Commit**: bcc8990d

**Regression From**: Not a regression

#### Steps to Reproduce: ####

1. Launch Storage Explorer and expand a blob account. 
2. Set the default Access Tier for the account.
3. Create one blob container and upload a blob to it.
4. Attach this blob container with SAS and make sure it is opened.
5. Check whether ‘Access Tier’ column displays or not on the attached blob container.

#### Expected Experience: ####
 ‘Access Tier’ column displays on the attached blob container.

#### Actual Experience: ####
 No ‘Access Tier’ column displays for attached blob container with SAS.
![tier](https://user-images.githubusercontent.com/34729022/39791512-9d4b2336-532b-11e8-8f09-606f7f3c7ccd.png)

More info:
1. ‘Access Tier’ displays well on the blob 'Properties' dialog.
2. This issue also reproduces for one blob container which is added to Quick Access.

**Comment by MRayermannMSFT** [comment]
Merged into master for 1.2.0.
