### ISSUE TITLE
Upload file log

### ISSUE THREAD

**Issue by nielswart84** [microsoft/AzureStorageExplorer#1602]
**Is your feature request related to a problem? Please describe.**
No, I would like to see a completed file transfer log of all files transferred to the blob  after an upload is complete.

**Describe the solution you'd like**
A link to download the file transfer log after a transfer will be of great help.

**Describe alternatives you've considered**

**Additional context**

**Comment by MRayermannMSFT** [comment]
Duplicate of #1214
