### ISSUE TITLE
Show the property of 'Connection display name' in the top-line on 'Connection Summary' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1605]
**Storage Explorer Version:** 1.9.0
**Build:** [20190731.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2898642)
**Platform/OS:** Linux Ubuntu 19.04/Windows 10/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Try to attach one blob container using 'Add a resource via Azure Active Directory(Azure AD)'.
2. Check descriptions in the last page of Connect dialog.

**Actual Experience:**

The property 'Connection display name' displays in the bottom line.
![image](https://user-images.githubusercontent.com/41351993/62196328-657fc880-b3b0-11e9-944e-c689c09e4574.png)

**Suggestion Experience:**
The property 'Connection display name' displays in the top-line.

**Comment by jinglouMSFT** [comment]
Fix merged into master for 1.10.0.
