### ISSUE TITLE
Keep a consistent value of 'Lease State' between the blob editor and properties dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1606]
**Storage Explorer Version:** 1.9.0
**Build:** [20190731.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2898642)
**Platform/OS:** Linux Ubuntu 19.04/Windows 10/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand a Non-ADLS Gen2 account -> Blob Container.
2. Create a blob container -> Upload a file to it.
3. Observe the value of 'Lease state' in blob editor and properties dialog. 

**Expected Experience:**
The value of the 'Lease State' are same between teh blob editor and properties dialog.

**Actual Experience:**
Show an inconsistent value of 'Lease State' between blob editor and properties dialog.
![image](https://user-images.githubusercontent.com/41351993/62195418-8ba46900-b3ae-11e9-8827-e588b3b4b1ad.png)

**Comment by MRayermannMSFT** [comment]
Lack of space in the dialog is by design. In the properties dialog we use the property names as given by the server.
