### ISSUE TITLE
Clicking 'Restart Now' cannot restart Storage Explorer after importing one SSL certificate

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1607]
**Storage Explorer Version:** 1.9.0
**Branch:** master
**Build:** 20190731.1
**Platform/OS:** Linux Ubuntu
**Architecture:** x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer from command line.
2. Go to Edit -> 'SSL Certificates'.
3. Select one file to import -> Click 'Restart Now' after importing successfully.

**Expect Experience:**

The Storage Explorer can be restarted.

**Actual Experience:**

The Storage Explorer isn't restarted.

**More info:**

1. The Storage Explorer can be restarted after pressing  'Ctrl+C' on the opened terminal.
2. This issue doesn't reproduce on Windows/Mac.

**Comment by craxal** [comment]
@v-xuanzh I'm currently investigating. Out of curiosity, how long did you wait before entering Ctrl+C in the command line? Also, keep an eye on your process list. How many StorageExplorer processes are open? Are any of them in the Zombie status when you close Storage Explorer? Do they go away if you wait 1-2 minutes?

**Comment by v-xuanzh** [comment]
Hi @craxal I verified this issue on the latest master build 20190814.2. It doesn't reproduce for now. So closed it.
