### ISSUE TITLE
The 'Delete' icons are not aligned to the right after adding one user with a long UPN on ACL dialog

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1608]
**Storage Explorer Version:** 1.9.0
**Branch:** master
**Build:** 20190731.1
**Platform/OS:** Windows 10
**Architecture:** ia32
**Regression From:** Previous release(1.9.0)

**Steps to reproduce:**
1. Expand one ADLS Gen2 account -> 'Blob Containers' node.
2. Right click one blob container then select 'Manage Access...'.
3. Add one user with a long UPN -> Check the 'Delete' icon next to the added UPN.

**Expect Experience:**

The 'Delete' icons are aligned to the right on the user/group list.

**Actual Experience:**

The 'Delete' icons are not aligned to the right.
![image](https://user-images.githubusercontent.com/34729022/62199755-a8dd3580-b3b6-11e9-8282-6b7b65e19756.png)

**More info:**

This issue doesn't reproduce on Linux/Mac.

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
