### ISSUE TITLE
Unable to signin and getting error

### ISSUE THREAD

**Issue by 777shubham** [microsoft/AzureStorageExplorer#1612]
{
  "message": "\"ERR_NAME_NOT_RESOLVED\""
}

**Comment by MRayermannMSFT** [comment]
@777shubham are you behind a proxy? If so you need to enable proxy settings. Consult our troubleshooting guide for more information. 

https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=1804#error-self-signed-certificate-in-certificate-chain-and-similar-errors

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
