### ISSUE TITLE
Error when downloading

### ISSUE THREAD

**Issue by albgen** [microsoft/AzureStorageExplorer#1614]
hi,

suddenly got the following error after 200gb of data downloaded...
had to restart again...

{
  "name": "AuthenticationFailedError",
  "message": "Authentication Error. Signature not valid in the specified time frame: Start [Tue, 06 Aug 2019 07:52:04 GMT] - Expiry [Tue, 06 Aug 2019 15:52:04 GMT] - Current [Tue, 06 Aug 2019 15:52:05 GMT]"
}

**Comment by JasonYeMSFT** [comment]
Hi @albgen,

Are you using AzCopy? Does this constantly fail even if you retry it?

**Comment by albgen** [comment]
> Hi @albgen,
> 
> Are you using AzCopy? Does this constantly fail even if you retry it?

hi, thanks for the reply. Just got the confirmation from the one who sent me the token that basically it has expired.
