### ISSUE TITLE
There shows an empty log message on Activities after coping/pasting blobs

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1616]
**Storage Explorer Version:** 1.9.0
**Branch:** master
**Build:** 20190806.12
**Platform/OS:** Linux Ubuntu 19.04/Windows 10/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release(1.9.0)

**Steps to reproduce:**
1. Expand one normal account -> Blob Containers.
2. Open one blob containers which contains one blob at least -> Select one blob then click 'Copy'.
3. Open another blob container then paste the copied blob container.
4. Check the log message on Activities.

**Expect Experience:**

The copying blob message shows well on Activities.

**Actual Experience:** 

There shows an empty log message on Activities.
![image](https://user-images.githubusercontent.com/34729022/62608149-e7806c00-b931-11e9-8b3d-19d5065e3ce7.png)

**Comment by v-xianya** [comment]
This issue has been fixed on build 20190809.2. So we close it.
