### ISSUE TITLE
An error occurs when uploading a file/folder to one new created blob container using AzCopy

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1618]
**Storage Explorer Version:** 1.9.0
**Build:** 20190806.12
**Platform/OS:** Linux Ubuntu 19.04/Windows 10/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release(1.9.0)

**Steps to reproduce:**
1. Make sure AzCopy is checked.
2. Expand a Non-ADLS Gen2 account -> Blob Containers.
3. Create a new blob container and upload a file to it.
4. Check the Activities.

**Expect Experience:**
Upload successfully.

**Actual Experience:**
An error message occurs.
![image](https://user-images.githubusercontent.com/41351993/62608779-1a772f80-b933-11e9-9746-eb9ae06ae197.png)

**More Info:**
1. This issue doesn't reproduce for HNS blob container.
2. This issue doesn't reproduce when AzCopy is unchecked.

**Comment by JasonYeMSFT** [comment]
Hi, this seems to have been fixed in the master. Could you please verify it this still reproduce?

Thanks.

**Comment by v-xianya** [comment]
Hi @JasonYeMSFT . Thanks for your update!
On the latest build master/20190814.2. This issue is blocked by the bug [1631](https://github.com/microsoft/AzureStorageExplorer/issues/1631) and we will verify it once the bug [1631](https://github.com/microsoft/AzureStorageExplorer/issues/1631) fixed.

**Comment by v-xianya** [comment]
This issue has been fixed on build master/20190815.2. So we close it.
