### ISSUE TITLE
Add 'Dequeue Message'/'Clear Queue' to the title of corresponding dialog 

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1619]
**Storage Explorer Version:** 1.9.0
**Branch:** master
**Build:** 20190806.12
**Platform/OS:** Linux Ubuntu 19.04/Windows 10/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Queues.
2. Open one queue then add some messages to it.
3. Click 'Dequeue Message' or 'Clear Message'.
4. Check the popped dialog title.

**Expect Experience:**

'Dequeue Message'/'Clear Message' shows on the popped title.

**Actual Experience:**

'Dequeue Message'/'Clear Message' doesn't show on the popped dialog.
![image](https://user-images.githubusercontent.com/34729022/62611152-9ffcde80-b937-11e9-928c-be5347e5f641.png)

**Comment by craxal** [comment]
By design. These dialogs originally used system dialogs, which had the exact same title as they do now. This is the same behavior as dialogs for native applications.
