### ISSUE TITLE
The 'Promote Snapshot' dialog isn't themed

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1620]
**Storage Explorer Version:** 1.9.0
**Branch:** master
**Build:** 20190806.12
**Platform/OS:** Linux Ubuntu 19.04/Windows 10/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release(1.9.0)

**Steps to reproduce:**
1. Change the current theme to Dark.
2. Open one normal blob container then upload one file to it.
3. Create a snapshot for the uploaded blob -> Go to the Snapshot View of the blob.
4. Right click the created snapshot then click 'Promote Snapshot'.
5. Check the popped dialog.

**Expect Experience:**

The 'Promote Snapshot' dialog is themed.

**Actual Experience:**

The 'Promote Snapshot' dialog isn't themed.
![image](https://user-images.githubusercontent.com/34729022/62611604-83ad7180-b938-11e9-86a6-19efd33af0d2.png)

**Comment by craxal** [comment]
It's not themed because this is a system dialog. We will fix this to use our custom message dialog.
