### ISSUE TITLE
Can't select all column name when the name is too long

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/AzureStorageExplorer#1623]
**Storage Explorer Version:** 1.9.0
**Branch:** master
**Build:** 20190806.12
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch storage explorer -> Navigate to one table.
2. Add an entity which has one property name with 255 characters.
3. Open 'Column Options' dialog.
4. Select the column which with the longer name.
5. Check if all column name is selected.

**Expect Experience:**
All column name is selected.

**Actual Experience:**
A part of column name is selected.
![image](https://user-images.githubusercontent.com/45614674/62613788-c1ac9480-b93c-11e9-977e-1f8e785a9669.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240526.2. Fixed. So, we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/7ec87e9e-4efb-4747-84e9-a7d035449b17)
