### ISSUE TITLE
The 'Save query as...' button is disabled after cancelling this action

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/AzureStorageExplorer#1625]
**Storage Explorer Version:** 1.9.0
**Branch:** master
**Build:** 20190806.12
**Platform/OS:** Linux Ubuntu/macOS High Sierra/Windows 10
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch storage explorer -> Navigate to one table.
2. Open query builder for this table and click 'Save query' button.
3. Click 'cancel' button or close the 'save query' dialog to cancel this action.
4. Check the state for 'Save query' button.

**Expect Experience:**
The 'Save query' button is enabled.

**Actual Experience:**
The 'Save query' button is disabled.
![image](https://user-images.githubusercontent.com/45614674/62612813-cff9b100-b93a-11e9-8db1-c834ff67b7ce.png)

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220630.8. Fixed. So closed it.
