### ISSUE TITLE
The added access policies disappear for one renamed container

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1627]
**Storage Explorer Version:** 1.9.0
**Branch:** master
**Build:** 20190808.2
**Platform/OS:** Linux Ubuntu 19.04/Windows 10/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one normal account -> Blob Containers.
2. Select one blob container then add policies for it.
3. Rename the same blob container.
4. Reopen the ACL dialog then check the access policies.

**Expect Experience:**

The added access policies show well for the renamed blob container.

**Actual Experience:**

The added access policies disappear for the renamed blob container.
![image](https://user-images.githubusercontent.com/34729022/62688171-ea935f00-b9fa-11e9-9597-1df04f1c0c33.png)

**More info:**

This issue also reproduces for one copied blob container.

**Comment by craxal** [comment]
Pretty sure this is by design, because we're only copying blobs over. Doesn't the rename dialog explain that these things aren't carried over?
