### ISSUE TITLE
Unable to open one new ADLS Gen2 blob container at the first time

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1628]
**Storage Explorer Version:** 1.9.0
**Branch:** master
**Build:** 20190808.2
**Platform/OS:** Linux Ubuntu 19.04/Windows 10/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release 1.9.0

**Steps to reproduce:**
1. Expand one ADLS Gen2 account -> Blob Containers.
2. Create one new blob container.
3. Check whether it can be opened automatically or not.

**Expect Experience:**

The created blob container can be opened successfully.

**Actual Experience:**

Unable to open the created blob container.
![image](https://user-images.githubusercontent.com/34729022/62688378-52e24080-b9fb-11e9-9dff-9a215d213fbe.png)

**More info:**

This issue doesn't reproduce after reopening the same blob container.

**Comment by MRayermannMSFT** [comment]
Fix merged into master.

**Comment by v-xuanzh** [comment]
This issue has been fixed on the latest master build 20190809.2. So closed it.
