### ISSUE TITLE
Attaching one blob container occurs an error with Azure AD

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1629]
**Storage Explorer Version:** 1.9.0
**Branch:** master
**Build:** 20190808.2
**Platform/OS:** Linux Ubuntu 19.04/Windows 10/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release 1.9.0

**Steps to reproduce:**
1. Give RBAC access to a container to a user like '**Blob Data Owner Role**'.
2. Copy a URL of one blob container -> Open Connect dialog -> Select 'Add a resource via Azure Directory(Azure AD)' -> 'Next'.
3. On the second page, choose the account with access to the resource and the subscription that the resource is in.
4. On the third page, paste a URL to the container -> 'Next'.
5. Check the result.

**Expect Experience:**

1. There is no error during attach the blob container.
2. The attached blob container can be opened automatically.

**Actual Experience:**
1. There occurs an error.
![image](https://user-images.githubusercontent.com/34729022/62689879-35fb3c80-b9fe-11e9-87c5-f5bf706f2b7d.png)
2. The attached RBAC container doesn't opened **automatically**.
3. The attached RBAC container can be opened **manually** without error.

**More info:**

This issue doesn't reproduce when attaching one ADLS Gen2 blob container with Azure AD.

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
