### ISSUE TITLE
Miss 'Preview' menu

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1631]
**Storage Explorer Version:** 1.9.0
**Branch:** master
**Build:** 20190809.2
**Platform/OS:** Linux Ubuntu 19.04/Windows 10/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release 1.9.0

**Steps to reproduce:**
1. Launch Storage Explorer then check the menu bar.

**Expect Experience:**

The 'Preview' menu shows well.

**Actual Experience:**

Miss 'Preview' menu.
![image](https://user-images.githubusercontent.com/34729022/62760597-f3496b00-bab6-11e9-8d2d-90533f8bf5f3.png)

**Comment by v-xianya** [comment]
This issue has been fixed on build master/20190815.2. So we close it.
