### ISSUE TITLE
No context menu appears after right clicking blobs

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1632]
**Storage Explorer Version:** 1.9.0
**Branch:** master
**Build:** 20190809.2
**Platform/OS:** Linux Ubuntu 19.04/Windows 10/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release 1.9.0

**Steps to reproduce:**
1. Open anyone blob container -> Upload one blob to it.
2. Right click the uploaded blob then check the context menu.

**Expect Experience:**

The context menu appears.

**Actual Experience:**

No context menu appears.

**More info:**
1. This issue doesn't reproduce for files.
2. This issue also reproduces for adls gen2 blobs.

**Comment by v-xianya** [comment]
This issue doesn't reproduce on build master/20190810.5. So we close it.
