### ISSUE TITLE
Nothing happens after clicking 'Upload/Download' for one blob container

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1633]
**Storage Explorer Version:** 1.9.0
**Branch:** master
**Build:** 20190809.2
**Platform/OS:** Linux Ubuntu 19.04/Windows 10/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release 1.9.0

**Steps to reproduce:**
1. Expand one non-adls gen2 account -> 'Blob Containers'
2. Open one blob container -> Click 'Upload Files...'.
3. Check the results.

**Expect Experience:**

The Upload dialog pops up.

**Actual Experience:**

Nothing happens.

**More info:**
1. This issue DOES NOT reproduce for file shares.
2. This issue DOES NOT reproduce for ADLS Gen2 blob container.
3. This issue also reproduces when Dragging files to one blob container.

**Comment by v-xianya** [comment]
This issue doesn't reproduce on build master/20190810.5. So we close it.
