### ISSUE TITLE
Add a validation on ACL dialog after editing an UPN with trailing whitespace

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1636]
**Storage Explorer Version:** 1.9.0
**Branch:** master
**Build:** 20190809.2
**Platform/OS:** Linux Ubuntu 19.04/Windows 10/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one ADLS Gen2 account -> 'Blob Containers'.
2. Right click one blob container then select 'Manage Access...'.
3. Edit the default user/group with a valid UPN with trailing whitespace.
4. Press 'Enter' -> Click 'Save'.

**Expect Experience:**

There shows a red border due to the edited UPN with trailing whitespace.

**Actual Experience:**

1. There is no error after editing an UPN with trailing whitespace.
![image](https://user-images.githubusercontent.com/34729022/62764005-75d62880-babf-11e9-8be7-978e71733663.png)

2. An error message shows on Activities after saving the edited UPN.
![image](https://user-images.githubusercontent.com/34729022/62764013-78d11900-babf-11e9-8cb0-d2e30c18d8d1.png)

**Comment by v-limu** [comment]
This issue has been fixed on build [20190927.10](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3091851). So close it.

**Comment by MRayermannMSFT** [comment]
This issue will no longer repro with the new search feature.
