### ISSUE TITLE
Acquire/Break lease dialog is empty for one blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1638]
**Storage Explorer Version:** 1.9.0
**Build:** 20190809.2
**Platform/OS:** Linux Ubuntu 19.04/Windows 10/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release(1.9.0)

**Steps to reproduce:**
1. Expand a Non-ADLS Gen2 account -> Blob Containers.
2. Create a new blob cotainer and try to acquire lease. 
3. Check the prompt dialog.

**Expect Experience:**
The prompt dialog is not empty.
![image](https://user-images.githubusercontent.com/41351993/62764689-1416be00-bac1-11e9-8102-22c1dc14f6a4.png)

**Actual Experience:**
The prompt dialog is empty.
![image](https://user-images.githubusercontent.com/41351993/62764803-517b4b80-bac1-11e9-83aa-80d7d11234d9.png)

**Comment by v-xuanzh** [comment]
This issue also reproduces on the latest master build 20190821.3. So reopened it.

**Comment by craxal** [comment]
Fix is still merged and working, but Cloud Explorer reference wasn't updated in Storage Explorer.
