### ISSUE TITLE
There shows a duplicate file when overwriting the conflict file for File Shares

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1647]
**Storage Explorer Version:** 1.9.0
**Branch:** master
**Build:** 20190810.5
**Platform/OS:** Linux Ubuntu 19.04/Windows 10/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release 1.9.0

**Steps to reproduce:**
1. Create one file share then upload a file to it.
2. Copy the uploaded file then select 'Paste'.
3. There shows a conflict error on the Activities -> Expand the error message.
4. Click the link 'Overwrite' -> Check the result.
![image](https://user-images.githubusercontent.com/34729022/62853363-b1baf900-bd1e-11e9-95cc-f97d305701bf.png)

**Expect Experience:**

The existing file can be overwritten and there only shows one file.

**Actual Experience:**

There shows a duplicate file after overwriting the conflict file.
![image](https://user-images.githubusercontent.com/34729022/62853445-fa72b200-bd1e-11e9-9f85-d526611910ef.png)

**Comment by v-xuanzh** [comment]
This issue doesn't reproduce on the latest master build 20190813.3. So closed it.

**Comment by v-xuanzh** [comment]
This issue still reproduces on the latest master build 20190813.12. So reopened it.

**Comment by v-limu** [comment]
This issue doesn't reproduce on the latest master build [20190920.6](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3071039). So closed it.
