### ISSUE TITLE
The 'Cancel' button shows as blank on 'Create New Directory' dialog for blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1649]
**Storage Explorer Version:** 1.9.0
**Build:** 20190813.12
**Platform/OS:** Linux Ubuntu 19.04/Windows 10/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release(1.9.0)

**Steps to reproduce:**
1. Expand a Non-ADLS Gen2 account -> Blob Containers.
2. Create a new blob container then click 'New Folder' on toolbar.
3. Check the popped dialog.

**Expect Experience:**
The 'Create New Directory' dialog shows well.
![image](https://user-images.githubusercontent.com/41351993/62853253-512bbc00-bd1e-11e9-9fc6-a7d937328ba3.png)

**Actual Experience:**
The 'Cancel' button shows as blank on the dialog.
![image](https://user-images.githubusercontent.com/34729022/62990912-3a9d7600-be80-11e9-84bf-852c2c28d31d.png)

**More Info:**
1. This issue also reproduces for one file share.
2. This issue doesn't reproduce on 'New Folder' for one ADLS Gen2 blob container.
3. This issue also reproduces on 'Rename Directory'/'Upload' dialog.
4. This issue also reproduces on 'Add Entity' dialog for one table.
5. This issue also reproduces on 'Generate Shared Access Signature' / 'Manage Access Policies' dailog.

**Comment by v-xuanzh** [comment]
Updated the title and repro steps.

**Comment by v-xuanzh** [comment]
Closed it and reported another bug to track.
