### ISSUE TITLE
An error dialog pops up when breaking the lease for one blob

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1650]
**Storage Explorer Version:** 1.9.0
**Build:** 20190810.5
**Platform/OS:** Linux Ubuntu 19.04/Windows 10/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release(1.9.0)

**Steps to reproduce:**
1. Expand a storage account -> Blob Containers.
2. Create a new blob container -> Upload a blob.
3. Acquire lease for the new blob.
4. Try to break the lease for the blob and check the result.

**Expect Experience:**
The 'Brake Lease' dialog pops up.

**Actual Experience**
An error dialog occurs.
![image](https://user-images.githubusercontent.com/41351993/62852918-66ecb180-bd1d-11e9-9575-4568afb2209a.png)

**Comment by v-xuanzh** [comment]
This issue has been fixed on the latest master build 20190813.12. So closed it.
