### ISSUE TITLE
An error dialog pops up when deleting files for one blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1651]
**Storage Explorer Version:** 1.9.0
**Build:** 20190810.5
**Platform/OS:** Linux Ubuntu 19.04/Windows 10/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release(1.9.0)

**Steps to reproduce:**
1. Expand a storage account -> Blob Containers.
2. Open one blob container and try to delete a blob.
3. Observe the result.

**Expect Experience:**
The blob can be deleted sucessfully.

**Actual Experience**
An error dialog pops up.
![image](https://user-images.githubusercontent.com/41351993/62853528-386fd600-bd1f-11e9-8d3b-504bc883bd00.png)

**More Info:**
1.This issue also reproduces when deleting blobs/file share snapshots.
2.This issue also reproduces when deleting files of file share.
3.This issue also reproduces when clicking 'Dequeue Message' & 'Clear Queue'.

**Comment by v-xuanzh** [comment]
This issue has been fixed on the latest master build 20190813.12. So closed it.
