### ISSUE TITLE
An error dialog pops up when selecting 'Set Public Access Level…' for one blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1652]
**Storage Explorer Version:** 1.9.0
**Build:** 20190810.5
**Platform/OS:** Linux Ubuntu 19.04/Windows 10/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release(1.9.0)

**Steps to reproduce:**
1. Expand a storage account.
2. Right click the 'Blob Containers' then select 'Set Public Access Level...'.
3. Check the result.

**Expect Experience:**
No error occurs.

**Actual Experience**
An error dialog occurs.
![image](https://user-images.githubusercontent.com/41351993/62853585-66edb100-bd1f-11e9-9c59-45d26b55def0.png)

**Comment by v-xuanzh** [comment]
This issue has been fixed on the latest master build 20190812.13. So closed it.
