### ISSUE TITLE
An error message displays on Activities when selecting 'Set Default Access Tier...' for one GPV2 account 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1653]
**Storage Explorer Version:** 1.9.0
**Build:** 20190810.5
**Platform/OS:** Linux Ubuntu 19.04/Windows 10/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release(1.9.0)

**Steps to reproduce:**
1. Right click one GPV2 account -> Select 'Set Default Access Tier...'.
2. Check the result.

**Expect Experience:**
The 'Update Access Tier' dialog pops up.
![image](https://user-images.githubusercontent.com/41351993/62854181-1f682480-bd21-11e9-8c85-29de5d17efc7.png)

**Actual Experience**
Show an error message on Activities.
![image](https://user-images.githubusercontent.com/41351993/62854278-7241dc00-bd21-11e9-8765-a69e82ffb6b4.png)

**Comment by v-xuanzh** [comment]
This issue has been fixed on the latest master build 20190813.12. So closed it.
