### ISSUE TITLE
Could not load subscriptions

### ISSUE THREAD

**Issue by RDariol** [microsoft/AzureStorageExplorer#1657]
**Storage Explorer Version**: 1.9.0
[Error.txt](https://github.com/microsoft/AzureStorageExplorer/files/3496269/Error.txt)
[Error.txt](https://github.com/microsoft/AzureStorageExplorer/files/3496270/Error.txt)
**Build Number**: 20190701.8
**Platform/OS**: Windows 10
**Architecture**: ia32
**Regression From**:  First use of Storage Explorer

## Bug Description ##
Log in ok, receive message "Subscriptions could not be loaded. Please try reentering credentials"

## Steps to Reproduce ##
1. Start Storage Explorer
2. Log into Azure
3. Organisation login requires MFA
4. Receive verification code via SMS, enter and continue
5. Storage Explorer loads and receive a dialog box to copy and report the error, attached

[Error.txt](https://github.com/microsoft/AzureStorageExplorer/files/3496272/Error.txt)

**Comment by jinglouMSFT** [comment]
Retrieving your subscription timed out based on the error message.  Are you behind a proxy?  If you are, you need to configure your proxy settings first in Storage Explorer.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
