### ISSUE TITLE
Please allow key selection when getting shared access signature in blob container

### ISSUE THREAD

**Issue by John-Garrett** [microsoft/AzureStorageExplorer#1659]
**Is your feature request related to a problem? Please describe.**
When using Azure Portal to get a shared access signature for a blob container, there's no way to select which access key is used to generate the secret. Key 1 is always used. Please allow key selection at this time.

**Describe the solution you'd like**
When you select your storage account, select storage explorer, expand blob containers, right click your blob container, select Get Shared Access Signature. In the next window where you select access policy, start and expiry time, and permissions, please add a dropdown for which key will be used to generate the secret used in the query string.

**Describe alternatives you've considered**
The only alternative, as far as I know, to specify the access key is with powershell, as shown here: https://docs.microsoft.com/en-us/sql/relational-databases/tutorial-use-azure-blob-storage-service-with-sql-server-2016?view=sql-server-2017

**Additional context**
This process would make it easier for quick one-offs where scripting the solution may be impractical, but you still want the flexibility of specifying key 2 instead of the default key 1.

**Comment by MRayermannMSFT** [comment]
Related to #421
