### ISSUE TITLE
StorageExplorer takes forever to load on Windows 7

### ISSUE THREAD

**Issue by andikrueger** [Microsoft/AzureStorageExplorer#166]
**Storage Explorer Version**:  1.0.0, 1.1.0, 1.3.1
**Platform**: Windows 7
**Architecture**: 32 Bit
**Build Number**: 
**Commit**: 
**Regression From**: 

#### Steps to Reproduce: ####

1. Start Storage Explorer
2. Wait for about 15-30 minutes

#### Expected Experience: ####
Storage Explorer opens in no time.

#### Actual Experience: ####
Storage Explorer opens very very slowly or non at all. During this loading phase there are way to many processes allocating RAM and CPU.

![2018-05-11 09_33_30-windows task-manager](https://user-images.githubusercontent.com/15608729/39918818-f0d7ac3a-5511-11e8-8ea3-c8994922cee4.png)

**Comment by MRayermannMSFT** [comment]
Wow, that is indeed a lot of processes and quite a long startup time. 😲 Could you share a bit more about your machine/vm specs? I want to try and recreate your situation as close as possible when we investigate this. Thanks!

**Comment by andikrueger** [comment]
It's a German Windows 7 x64 (Domain joined) with all updates (automatic updates) installed.
Is there anything more specific I can look for? Are there any log files or system specs that can lead to this issue?

**Comment by MRayermannMSFT** [comment]
CPU and hard drive speed would probably be the biggest factors when it comes to startup time. I don't have any ideas at the moment though for what could be causing the massive number of processes though.

**Comment by andikrueger** [comment]
Element | Value
----|----
Prozessor | Intel(R) Core(TM) i5-3427U CPU
Drive | SSD SATA 6gb/s; Read 500MB/s; write: 175 MB/s

**Comment by jinglouMSFT** [comment]
Just curious, do you have .NET 4.7.x installed on your machine?

**Comment by andikrueger** [comment]
Element | Value
---|---
.net | .NET Framework 4.7.1 (Release: 461310)

**Comment by craxal** [comment]
Considering several other issues have been created with this same problem, it's safe to say this isn't a Windows 10 issue. We've seen other cases where many processes are launched, running the CPU up unnecessarily high.

We use separate processes to, among other things, run several resource-heavy operations, such as blob downloads and uploads. This keeps Storage Explorer from locking up, especially if a problem occurs during those operations. The number of these child processes should be limited to 5 or so. If for some reason a child process doesn't respond within a certain period, I think we try again by spawning a new process. This may explain where the flood of processes comes from.

Another factor that may hurt performance is if your system has hooks that make inter-process operations take longer. For example, antivirus software may monitor process creation and communication, slowing things down.

See #281 for more info.

❓ **If you watch Task Manager at startup, how fast does the list of processes grow?**

We haven's seen this issue pop up in any of our dev/test environments, making this difficult to pin down. We have some ideas for the future that may help, though, including better logging and auto-termination of processes that aren't able to communicate with Storage Explorer.

**Comment by ChrisJWoodcock** [comment]
As soon as I start Storage Explorer (Windows 10 Latest Updates) I get 55% increase in CPU and it runs continuously loading three SQL Server processes at 15 - 20% each; this is without actually using the Storage Explorer or reading from the Emulator - it's just background loading.

**Comment by craxal** [comment]
@ChrisJWoodcock You sure it's Storage Explorer launching SQL Server processes? Storage Explorer doesn't automatically launch any storage emulators when you connect to them. What version of Storage Explorer are you running?

**Comment by ChrisJWoodcock** [comment]
> @ChrisJWoodcock You sure it's Storage Explorer launching SQL Server processes? Storage Explorer doesn't automatically launch any storage emulators when you connect to them. What version of Storage Explorer are you running?

You are correct I've updated my original comment to highlight the mistake.

**Comment by craxal** [comment]
Closing due to inactivty (in regards to original error). Please let us know if problems persist.
