### ISSUE TITLE
The original table is still listed in SAS attached storage account after renaming

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/AzureStorageExplorer#1662]
**Storage Explorer Version:** 1.9.0
**Build:** 20190813.12
**Platform/OS:** Linux Ubuntu 19.04/Windows 10/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a Regression

Steps to reproduce:

1. Attach one storage account with SAS.
2. Create a new table 'test' in this attached SAS storage account.
3. Rename the created table to 'test1'.
4. Check the table list.

Expect Experience:
The original table 'test' is disappear from the list.

Actual Experience
The original table 'test' is still listed.
![image](https://user-images.githubusercontent.com/45614674/63015102-b3bdbd00-bec2-11e9-8e59-8aedd527dbbc.png)

More info:

1. This bug does not reproduce in the storage account without SAS.
2. Refresh can fix this issue.

**Comment by v-limu** [comment]
This issue also reproduces for renaming the last table under 'Load more'.
