### ISSUE TITLE
There is no response after clicking 'Save query' and 'Save query as...' buttons

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/AzureStorageExplorer#1664]
**Storage Explorer Version:** 1.9.0
**Build:** 20190813.12
**Platform/OS:** Linux Ubuntu 19.04/Windows 10/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release(1.9.0)

**Steps to reproduce:**

1. Open one table which has several entities.
2. Click 'Query' button to open it.
3. Click 'Save query' and 'Save query as...' buttons in query builder.
4. Check the result.

Expect Experience:
The 'Save query' dialog pops up.
![image](https://user-images.githubusercontent.com/45614674/63014399-07c7a200-bec1-11e9-9e0c-75ac57df2f76.png)

**Actual Experience**
There is no response.

**Comment by v-xuanzh** [comment]
This issue has been fixed on the latest master build 20190828.6. So we close it.
