### ISSUE TITLE
can't expand column 

### ISSUE THREAD

**Issue by ohadbitt** [microsoft/AzureStorageExplorer#1666]
**Storage Explorer Version**: 1.9
**Build Number**: 20190701.8
**Platform/OS**: windows 10
**Architecture**:  x64
**Regression From**:  no

## Bug Description ##
can't drag column name in order to expend the view - to being able to read long blob name

## Steps to Reproduce ##
1. create a blob with a long name (e.g :  ohtst__tmpTableDatabricksShell_maps3_1d433a56_a7f5_445b_8e2f_0255ee53bc3a_08765237-40fe-485f-9f14-5ec504556cba_SparkStreamUpload.gz
2. get into the container that holds it
3. try to drag any column (main problem here is that i cant view the full name .. )

**Comment by MRayermannMSFT** [comment]
Are you trying to move the column (or in other words, change the order in which the columns appear) or resize it (change the width of the column to make it wider or thinner)?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
