### ISSUE TITLE
Allow the query pane to be resized vertically in Cosmos DB query tabs

### ISSUE THREAD

**Issue by RichardMisiak** [Microsoft/AzureStorageExplorer#167]
**Storage Explorer Version**: 1.1.0

**Platform**: Windows
**Architecture**: ia32

**Build Number**: 20180507.1

**Commit**: bcc8990d

**Regression From**:  n/a

#### Steps to Reproduce: ####

1. Open a query tab for a Cosmos DB collection

#### Expected Experience: ####
A user should be able to resize the query pane to make it larger/taller, making it easier to edit queries.

#### Actual Experience: ####
The user cannot resize the query pane.
The results pane takes up a majority of the screen and the query pane is locked at ~5 lines tall making queries hard to edit.

**Comment by djlan** [comment]
It can actually be resized. However the separation line is not quite obvious.

**Comment by djlan** [comment]
Got it. Looking. Thanks for the feedback!

**Comment by ziyel** [comment]
We will fix this in next release.

**Comment by RichardMisiak** [comment]
Fantastic, thanks

**Comment by MRayermannMSFT** [comment]
@ziyel , did this make 1.3.0?

**Comment by ziyel** [comment]
@MRayermannMSFT , yes!

**Comment by MRayermannMSFT** [comment]
Ok, then closing the issue. Thank you. 😄
