### ISSUE TITLE
Blob storage folder not accessible via explorer

### ISSUE THREAD

**Issue by RudyEvers** [microsoft/AzureStorageExplorer#1673]
**Storage Explorer Version**: 1.9.0
**Build Number**: 20190701.8
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  Don't think so

## Bug Description ##
json files created by azure stream analytics in the following path pattern (/{DeviceId}/{date}/)  in a blob container are visisble via the azure portal but not via the storage explorer.

## Steps to Reproduce ##
Store json message using Streaming Analytics in a blob storage using the following 
path pattern:  /{DeviceId}/{date}/
date format: YYYY/MM/DD
other configuration is default.

## Expected Experience ##
Files stored in de blob container named messages is accessible via storage explorer if the created path by Streaming Analytics is: messages///device1/2019/08/16/

Not certain why Stream analytics is creating blank folders in the middle?

## Actual Experience ##
Can drill to the device folder after that other folders are not shown in Storage Explorer

## Additional Context ##
As mentioned all folders in de container are created by the Azure Streaming Analytics so it should work by default.
![example_azure_portal_storage](https://user-images.githubusercontent.com/38738862/63176374-1f7c6300-c046-11e9-8f26-0700fa3dc60e.PNG)
![example_storage_explorer](https://user-images.githubusercontent.com/38738862/63176405-23a88080-c046-11e9-9038-50eb4f3e36c9.PNG)

**Comment by JasonYeMSFT** [comment]
Hi @RudyEvers ,

We do not support navigation of blobs whose name contain consecutive slashes, meaning having directories with "" names. This is an abnormal behavior and we don't have a good solution so far. We have put this into our 1.11 goals. If you really need to make the navigation work immediately, please let us know and we can provide some work around for you.

**Comment by RudyEvers** [comment]
I solved this issue by removing the first slash in my path pattern in Azure Streaming Analytics. I am able to get into all folders.
