### ISSUE TITLE
Provide timestamp for Folder Statistics

### ISSUE THREAD

**Issue by rababued** [microsoft/AzureStorageExplorer#1674]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rababued** [comment]
Would be really nice to have the timestamp each time I run an activity like Folder Statistics... it would give me an idea on time slice between Folder Statistics snapshots...

**Comment by MRayermannMSFT** [comment]
Duplicate of #222
