### ISSUE TITLE
Storage Explorer has a "phantom" connection

### ISSUE THREAD

**Issue by EtharAlali** [microsoft/AzureStorageExplorer#1676]
**Storage Explorer Version**: 1.9.0 
**Build Number**: 20190701.8
**Platform/OS**: Windows 10 
**Architecture**: ia86 (x86) 
**Regression From**:  Never used before

## Bug Description ##
Cannot add devstoreaccount1 with that Display name

## Steps to Reproduce ##

When trying to add an explicit connection string with the name devstoreaccount1, it fails to add, even though there is no existing connection with that name.  
 
"A connection with the name 'devstoreaccount1' already exists. Detatch(sic) the existing connection or provide a different name."

1. Open Storage explorer and click "Add an account..."
2. In the Connect dialog, select "Use a connection string", enter devstoreaccont1 as the Display name  and click Next 
3. Complete the details for an explicit storage connection using a connection string for a local storage emulator
4. Click Next 

## Expected Experience ##
A connection is available in the left-hand resource tree, given it didn't previously exist

## Actual Experience ##
![image](https://user-images.githubusercontent.com/2097628/63221976-151eae00-c199-11e9-9db4-00ebca98e105.png)

When trying to add an explicit connection string, 
"A connection with the name 'devstoreaccount1' already exists. Detatch(sic) the existing connection or provide a different name."

Note that in the image, there is no devstoreaccount1 in the left resource tree navigator. 

## Additional Context ##
This took place _after_ the error in #1675. Note, even completing the connection string doesn't connect to the resource. However, that's a separate issue.

**Comment by MRayermannMSFT** [comment]
@EtharAlali , can you go back to the tree view/explorer view (top icon on the vertical toolbar), and look under "(Local & Attached)" and see if the devstoreaccount1 is there?

**Comment by EtharAlali** [comment]
@MRayermannMSFT saw your message, but didn't respond. I was unable to access it. I've just tried again and Local & Attached is accessible and the devstore1 account is definitely there now. Happy to close.
