### ISSUE TITLE
Azure account not getting added to Storage explorer

### ISSUE THREAD

**Issue by mandritac** [microsoft/AzureStorageExplorer#1678]
**Storage Explorer Version**: 1.9.0
**Build No**: 20190701.8
**Platform/OS** - Windows 7 32 bit
**Architecture** - ia32
**Regression From** - NA

**Bug Description**
Not able to add Azure account to the storage explorer

**Steps to reproduce**
Try adding a new Azure account from behind corporate proxy

**Expected**
Account should get added

**Actual Experience**
```
Error - Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: f8cdef31-a31e-4b4a-93e4-5f571e91255a, Error: {
"name": "Error",
"message": "getaddrinfo ENOTFOUND management.azure.com management.azure.com:443",
"__zone_symbol__error": {
"originalStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (D:\Microsoft-Azure-Storage-Explorer\resources\app\node_modules\zone.js\dist\zone-node.js:811:33)\n at new AppInsightsAsyncCorrelatedErrorWrapper (D:\Microsoft-Azure-Storage-Explorer\resources\app\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:172:18)\n at errnoException (dns.js:50:10)\n at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
"zoneAwareStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (D:\Microsoft-Azure-Storage-Explorer\resources\app\node_modules\zone.js\dist\zone-node.js:811:33)\n at new AppInsightsAsyncCorrelatedErrorWrapper (D:\Microsoft-Azure-Storage-Explorer\resources\app\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:172:18)\n at errnoException (dns.js:50:10)\n at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)"
},
"stack": "Error: getaddrinfo ENOTFOUND management.azure.com\n at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (D:\Microsoft-Azure-Storage-Explorer\resources\app\node_modules\zone.js\dist\zone-node.js:811:33)\n at new AppInsightsAsyncCorrelatedErrorWrapper (D:\Microsoft-Azure-Storage-Explorer\resources\app\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:172:18)\n at errnoException (dns.js:50:10)\n at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
"originalStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (D:\Microsoft-Azure-Storage-Explorer\resources\app\node_modules\zone.js\dist\zone-node.js:811:33)\n at new AppInsightsAsyncCorrelatedErrorWrapper (D:\Microsoft-Azure-Storage-Explorer\resources\app\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:172:18)\n at errnoException (dns.js:50:10)\n at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
"zoneAwareStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (D:\Microsoft-Azure-Storage-Explorer\resources\app\node_modules\zone.js\dist\zone-node.js:811:33)\n at new AppInsightsAsyncCorrelatedErrorWrapper (D:\Microsoft-Azure-Storage-Explorer\resources\app\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:172:18)\n at errnoException (dns.js:50:10)\n at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
"__zone_symbol__stack": "Error: getaddrinfo ENOTFOUND management.azure.com\n at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (D:\Microsoft-Azure-Storage-Explorer\resources\app\node_modules\zone.js\dist\zone-node.js:811:33)\n at new AppInsightsAsyncCorrelatedErrorWrapper (D:\Microsoft-Azure-Storage-Explorer\resources\app\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:172:18)\n at errnoException (dns.js:50:10)\n at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
"__zone_symbol__name": "Error",
"__zone_symbol__message": "getaddrinfo ENOTFOUND management.azure.com management.azure.com:443",
"__zone_symbol__originalStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (D:\Microsoft-Azure-Storage-Explorer\resources\app\node_modules\zone.js\dist\zone-node.js:811:33)\n at new AppInsightsAsyncCorrelatedErrorWrapper (D:\Microsoft-Azure-Storage-Explorer\resources\app\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:172:18)\n at errnoException (dns.js:50:10)\n at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
"__zone_symbol__zoneAwareStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (D:\Microsoft-Azure-Storage-Explorer\resources\app\node_modules\zone.js\dist\zone-node.js:811:33)\n at new AppInsightsAsyncCorrelatedErrorWrapper (D:\Microsoft-Azure-Storage-Explorer\resources\app\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:172:18)\n at errnoException (dns.js:50:10)\n at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
"code": "ENOTFOUND",
"errno": "ENOTFOUND",
"syscall": "getaddrinfo",
"hostname": "management.azure.com",
"host": "management.azure.com",
"port": 443
}
```

**Additional Context**
All internet connections happen through corporate proxy
Thanks.

**Comment by MRayermannMSFT** [comment]
@mandritac , since you have a corporate proxy, have you setup those proxy settings in Storage Explorer? Edit -> Proxy Settings

**Comment by mandritac** [comment]
Yes I tried that but it started giving error. Please check attached screenshot.
[StorageExplorerIssue.zip](https://github.com/microsoft/AzureStorageExplorer/files/3519042/StorageExplorerIssue.zip)

**Comment by mandritac** [comment]
Also I tried options using connection string or a storage account key option but with or without enabling proxy I am getting following error - 
{
  "name": "TypeError",
  "message": "Cannot read property 'uids' of undefined",
  "__zone_symbol__error": {
    "originalStack": "Error: Cannot read property 'uids' of undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at Function.ExceptionSerializer.deserialize (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler.finalizeOperation (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:76:91)\n    at Object.finalizeOperation (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:99:76)\n    at Function.<anonymous> (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:28:63)\n    at step (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:136:27)\n    at Object.next (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:117:57)\n    at D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:110:75\n    at new ZoneAwarePromise (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:106:16)\n    at JsonPortMarshaler.standardMarshaler.(anonymous function) [as finalizeOperation] (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:22:32)\n    at JsonPortMarshaler.onMessage (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\common\\event.js:69:30)\n    at Port.processMessage (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\communication.js:163:18)",
    "zoneAwareStack": "Error: Cannot read property 'uids' of undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at Function.ExceptionSerializer.deserialize (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler.finalizeOperation (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:76:91)\n    at Object.finalizeOperation (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:99:76)\n    at Function.<anonymous> (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:28:63)\n    at step (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:136:27)\n    at Object.next (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:117:57)\n    at D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:110:75\n    at new ZoneAwarePromise (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:106:16)\n    at JsonPortMarshaler.standardMarshaler.(anonymous function) [as finalizeOperation] (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:22:32)\n    at JsonPortMarshaler.onMessage (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\common\\event.js:69:30)\n    at Port.processMessage (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\communication.js:163:18)"
  },
  "stack": "TypeError: Cannot read property 'uids' of undefined\n    at StorageExplorerProvider.<anonymous> (file:///D:/Microsoft-Azure-Storage-Explorer/resources/app/out/CloudHub/js/Providers/StorageExplorer/StorageExplorerProvider.js:282:51)\n    at step (file:///D:/Microsoft-Azure-Storage-Explorer/resources/app/out/CloudHub/js/Providers/StorageExplorer/StorageExplorerProvider.js:47:23)\n    at Object.next (file:///D:/Microsoft-Azure-Storage-Explorer/resources/app/out/CloudHub/js/Providers/StorageExplorer/StorageExplorerProvider.js:28:53)\n    at fulfilled (file:///D:/Microsoft-Azure-Storage-Explorer/resources/app/out/CloudHub/js/Providers/StorageExplorer/StorageExplorerProvider.js:19:58)\n    at <anonymous>",
  "originalStack": "Error: Cannot read property 'uids' of undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at Function.ExceptionSerializer.deserialize (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler.finalizeOperation (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:76:91)\n    at Object.finalizeOperation (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:99:76)\n    at Function.<anonymous> (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:28:63)\n    at step (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:136:27)\n    at Object.next (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:117:57)\n    at D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:110:75\n    at new ZoneAwarePromise (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:106:16)\n    at JsonPortMarshaler.standardMarshaler.(anonymous function) [as finalizeOperation] (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:22:32)\n    at JsonPortMarshaler.onMessage (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\common\\event.js:69:30)\n    at Port.processMessage (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\communication.js:163:18)",
  "zoneAwareStack": "Error: Cannot read property 'uids' of undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at Function.ExceptionSerializer.deserialize (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler.finalizeOperation (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:76:91)\n    at Object.finalizeOperation (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:99:76)\n    at Function.<anonymous> (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:28:63)\n    at step (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:136:27)\n    at Object.next (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:117:57)\n    at D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:110:75\n    at new ZoneAwarePromise (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:106:16)\n    at JsonPortMarshaler.standardMarshaler.(anonymous function) [as finalizeOperation] (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:22:32)\n    at JsonPortMarshaler.onMessage (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\common\\event.js:69:30)\n    at Port.processMessage (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\communication.js:163:18)",
  "__zone_symbol__stack": "TypeError: Cannot read property 'uids' of undefined\n    at StorageExplorerProvider.<anonymous> (file:///D:/Microsoft-Azure-Storage-Explorer/resources/app/out/CloudHub/js/Providers/StorageExplorer/StorageExplorerProvider.js:282:51)\n    at step (file:///D:/Microsoft-Azure-Storage-Explorer/resources/app/out/CloudHub/js/Providers/StorageExplorer/StorageExplorerProvider.js:47:23)\n    at Object.next (file:///D:/Microsoft-Azure-Storage-Explorer/resources/app/out/CloudHub/js/Providers/StorageExplorer/StorageExplorerProvider.js:28:53)\n    at fulfilled (file:///D:/Microsoft-Azure-Storage-Explorer/resources/app/out/CloudHub/js/Providers/StorageExplorer/StorageExplorerProvider.js:19:58)\n    at <anonymous>",
  "__zone_symbol__name": "TypeError",
  "__zone_symbol__message": "Cannot read property 'uids' of undefined",
  "__zone_symbol__originalStack": "Error: Cannot read property 'uids' of undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at Function.ExceptionSerializer.deserialize (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler.finalizeOperation (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:76:91)\n    at Object.finalizeOperation (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:99:76)\n    at Function.<anonymous> (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:28:63)\n    at step (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:136:27)\n    at Object.next (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:117:57)\n    at D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:110:75\n    at new ZoneAwarePromise (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:106:16)\n    at JsonPortMarshaler.standardMarshaler.(anonymous function) [as finalizeOperation] (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:22:32)\n    at JsonPortMarshaler.onMessage (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\common\\event.js:69:30)\n    at Port.processMessage (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\communication.js:163:18)",
  "__zone_symbol__zoneAwareStack": "Error: Cannot read property 'uids' of undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at Function.ExceptionSerializer.deserialize (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler.finalizeOperation (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:76:91)\n    at Object.finalizeOperation (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\CloudExplorerProxyMarshaler.js:99:76)\n    at Function.<anonymous> (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:28:63)\n    at step (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:136:27)\n    at Object.next (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:117:57)\n    at D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:110:75\n    at new ZoneAwarePromise (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:106:16)\n    at JsonPortMarshaler.standardMarshaler.(anonymous function) [as finalizeOperation] (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\out\\app\\renderer\\marshalers\\StandardMarshaler.js:22:32)\n    at JsonPortMarshaler.onMessage (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\common\\event.js:69:30)\n    at Port.processMessage (D:\\Microsoft-Azure-Storage-Explorer\\resources\\app\\node_modules\\daytona\\pluginHost\\messaging\\communication.js:163:18)"
}

**Comment by MRayermannMSFT** [comment]
@mandritac, are you still encountering issues?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of reply. Please open a new issue if you still have problems.

**Comment by DanBer39** [comment]
Just try to check one of the boxes listed on account tab of the Azure storage explorer to show your ayure subscription listed on Azure storage explorer
