### ISSUE TITLE
Update '上载' to '上传' for one blob container on Chinese

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1685]
**Storage Explorer Version:** 1.9.0
**Build:** master_20190821.3
**Platform/OS:** Windows 10/Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Language:** Chinese (zh-CN)
**Regression From:** Not a regression

**Steps to reproduce:**
1. Run the command '_**StorageExplorer.exe --lang=zh-CN**_' to launch storage explorer.
2. Expand one storage account -> Blob Containers.
3. Create a new blob container -> Click '上载' on the toolbar and observe the drop down.

**Expect Experience:**
Keep a constitent translation for upload.

**Actual Experience:**
1. Dislpay '上载' on the toolbar.
2. Dispaly '上传' in the drop down.
![image](https://user-images.githubusercontent.com/41351993/63416215-9e501200-c431-11e9-9be3-7120b62449b4.png)

**More Info:**
This issue also reproduces for one file share.

**Comment by v-xianya** [comment]
This issue has been fixed on the private build. So close it.

**Comment by v-xianya** [comment]
This issue reproduces on ADLS Gen2 blob containers. So we re-open it.

**Comment by johnliu2016** [comment]
Should change 上载 to 上传 for term consistency. All instances implemented.

**Comment by craxal** [comment]
Verified change is checked into master, so looks like we need to generate a new package version.

**Comment by v-xianya** [comment]
This issue has been fixed on the latest build master/20190917.7. So we close it.
