### ISSUE TITLE
Extra quotes are added for '下载' / '打开' button on toolbar

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1687]
**Storage Explorer Version:** 1.9.0
**Build:** master_20190821.3
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Language**: Chinese (zh-CN)
**Regression From:** Not a regression

**Steps to reproduce:**
1. Run the command 'StorageExplorer.exe --lang=zh-CN' to launch storage explorer.
2. Expand one Non-ADLS Gen2 account -> Blob Containers.
3. Create a new blob container -> Observe its toolbar.

**Expect Experience:**
No quote is added for '下载' / '打开' button.

**Actual Experience:**
Extra quotes are added for'下载' / '打开' button.
![image](https://user-images.githubusercontent.com/41351993/63417983-e1f84b00-c434-11e9-85b7-decb484dc411.png)

**More Info:**
This issue also reproduces for one file share.

**Comment by craxal** [comment]
The translated files contain [下载] and [打开] for those strings. Not sure why they're there. But the localization team is aware of several issues in the Chinese translation pipeline, so we'll let them sort that out.

**Comment by v-xianya** [comment]
This issue has been fixed on the private build. So close it.
