### ISSUE TITLE
The opened Blob Container shows an incomplete buttons on the toolbar with Russian and German

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1688]
**Storage Explorer Version:** 1.9.0
**Build:** 20190821.3
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04
**Branch**: master
**Architecture:** ia32/x64
**Language**: Russian and German
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer using the  command _**StorageExplorer.exe --lang=de**_(or _**StorageExplorer.exe --lang=ru**_)
2. Open one normal blob container -> Check the buttons on the toolbar.

**Expect Experience:**

All the buttons show well on the toolbar.

**Actual Experience:**

Show an incomplete buttons on the toolbar.
![image](https://user-images.githubusercontent.com/34729022/63418592-f12bc880-c435-11e9-835b-7916ca8a600a.png)
![image](https://user-images.githubusercontent.com/34729022/63418596-f426b900-c435-11e9-97c1-01f348704532.png)

**Comment by craxal** [comment]
Reproduced. Resizing the window has no effect.
