### ISSUE TITLE
'Download' is not localized on the editor toolbar with German language

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1689]
**Storage Explorer Version:** 1.9.0
**Build:** 20190821.3
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Branch**: master
**Architecture:** ia32/x64
**Language**: German
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer using the  command _**StorageExplorer.exe --lang=de**_.
2. Open one blob container/file share -> Check the toolbar buttons.

**Expect Experience:**

The 'Download' is translated to 'Herunterladen'.

**Actual Experience:**

The 'Download' is not localized.
![image](https://user-images.githubusercontent.com/34729022/63419236-fc332880-c436-11e9-8b0d-0ab3fb847518.png)

**Comment by johnliu2016** [comment]
Lingusitic review result:
The current translation is basically fine but it is inconsistent with the adjacent Upload item. Therefore, use the Approved Change field for updating. ​
​
Approved Change:​
Herunterladen

**Comment by johnliu2016** [comment]
Implemented as suggested.
