### ISSUE TITLE
Get an error when executing the 'Mange Access...' action for ADLS Gen2 container

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1690]
**Storage Explorer Version:** 1.9.0
**Build:** 20190821.3
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04
**Branch**: master
**Architecture:** ia32/x64
**Regression From:** Previous release

**Steps to reproduce:**
1. Expand one ADLS Gen2 account -> 'Blob Containers' node.
2. Right click one blob container then select 'Manage Access...'.
3. Check the result.

**Expect Experience:**

The 'Manage Access' dialog shows well.

**Actual Experience:**

Get an error on the Activities.
![image](https://user-images.githubusercontent.com/34729022/63419530-94c9a880-c437-11e9-94f4-d67bd88665cf.png)

**Comment by craxal** [comment]
@MRayermannMSFT The reason is because `ManagePosixAclViewModel` doesn't have a default export.

**Comment by v-xuanzh** [comment]
This issue has been fixed on the latest master build 20190813.5. So closed it.
