### ISSUE TITLE
An extra . shows for the localized 'Refresh' button the editor toolbar with Russian language

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1691]
**Storage Explorer Version:** 1.9.0
**Build:** 20190821.3
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04
**Branch**: master
**Architecture:** ia32/x64
**Language**: Russian
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer using the command **_StorageExplorer.exe --lang=ru_**.
2. Open one table then check the toolbar buttons.

**Expect Experience:**

No extra . shows for the localized 'Refresh' button.

**Actual Experience:**

An extra . shows for the localized 'Refresh' button.
![image](https://user-images.githubusercontent.com/34729022/63419907-39e48100-c438-11e9-9b46-ab1ec8522314.png)

**Comment by johnliu2016** [comment]
"The full stop is extra, plus the word form should be changed to Infinitive so that it is suitable for this command."

New string - "Обновить" implemented
