### ISSUE TITLE
Show a wrong tooltip for the '删除' button on the editor toolbar with Chinese language

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1692]
**Storage Explorer Version:** 1.9.0
**Build:** 20190821.3
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Branch**: master
**Architecture:** ia32/x64
**Language**: Chinese(zh-CN)
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer using the command '**_StorageExplorer.exe --lang=zh-CN_**'.
2. Open one blob container -> Focus on the '删除' button on the toolbar.
3. Check the tooltip.

**Expect Experience:**

The tooltip of the '删除' button shows '删除选中的项目'.

**Actual Experience:**

The tooltip of the '删除' button shows '创建选中的项目'.
![image](https://user-images.githubusercontent.com/34729022/63420214-d3139780-c438-11e9-897f-10a40afbce19.png)

**Comment by v-xianya** [comment]
This issue has been fixed on the private build. So close it.

**Comment by Smille02a** [comment]
How many emails must I delete from you, almost on a daily basis?

Where is your email etiquette?


Thank you.
--
Regards,
Stephen W.  Miller
smille02@msn.com<mailto:smille02@msn.com>  @Smille02  Skype:live:smille02
Cell: +1 917.704.5934<tel:+1%20917.704.5934> Fax:  +1 212.225.8247<tel:+1%20212.225.8247>
www.linkedin.com/in/swmps<http://www.linkedin.com/in/swmps>

On Sep 2, 2019, at 10:29 PM, v-xianya <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #1692<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FAzureStorageExplorer%2Fissues%2F1692&data=02%7C01%7C%7C93b59bb02ede4790881708d730168794%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637030745621911287&sdata=h6Mb2VOnuzMgSTueKKj1UiVUrrM9ONf0TZypYJbzp6w%3D&reserved=0>.

**Comment by craxal** [comment]
@Smille02a We are not sending emails to you directly. We are leaving comments on issues reported on our GitHub page. GitHub is probably sending emails to you automatically. My guess is you are subscribed to these issues, so you'll need to adjust your GitHub user settings to disable email communications (https://github.com/settings/notifications).

**Comment by v-xianya** [comment]
This issue reproduces on ADLS Gen2 blob containers. So we re-open it.

**Comment by johnliu2016** [comment]
Implemented to '删除选中的项目'

**Comment by v-limu** [comment]
This issue has been fixed on build [20190925.6](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3080492). So we close it.
