### ISSUE TITLE
The uploading activity cannot complete when uploading files/folder to one blob container using AzCopy

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1693]
**Storage Explorer Version:** 1.9.0
**Build:** 20190821.3
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04
**Branch**: master
**Architecture:** ia32/x64
**Regression From:** Previous release

**Steps to reproduce:**
1. Make sure AzCopy is enabled.
2. Open one normal blob container -> Try to upload one file to it.
3. Check the uploading result.

**Expect Experience:**

The file can be uploaded successfully.

**Actual Experience:**

The uploading activities cannot complete.
![image](https://user-images.githubusercontent.com/34729022/63420535-719ff880-c439-11e9-85ad-66b5ac00af88.png)

**More info:**

This issue also reproduces when uploading files/folder to one ADLS Gen2 container.

**Comment by v-xianya** [comment]
This issue has been fixed on the latest build master/20190827.12. So we close it.
