### ISSUE TITLE
The contents of 'Promote Snapshot' dialog shows as zh-TW rather than zh-CN with Chinese language

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1694]
**Storage Explorer Version:** 1.9.0
**Build:** 20190821.3
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04
**Branch**: master
**Architecture:** ia32/x64
**Language**: Chinese(zh-CN)
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer using the command **_StorageExplorer.exe --lang=zh-CN_**.
2. Open one blob container which contains one blob at least.
3. Create snapshot for one blob -> Go to the snapshot view of the blob.
4. Right click the snapshot then select '提升快照'。
5. Check the contents of the popped dialog.

**Expect Experience:**

The contents of the 'Promote Snapshot' dialog shows as zh-CN.

**Actual Experience:**

The contents of the 'Promote Snapshot' dialog shows as zh-TW.
![image](https://user-images.githubusercontent.com/34729022/63420940-4f5aaa80-c43a-11e9-9b24-37ecb78542d5.png)

**More info:**

The 'Promote Snapshot' dialog is not localized on German language.
![image](https://user-images.githubusercontent.com/34729022/63421018-6e593c80-c43a-11e9-87c0-c36a18763a35.png)

**Comment by v-xianya** [comment]
This issue has been fixed on the latest build master/20190827.12. So we close it.
