### ISSUE TITLE
'Rename' is not localized for one file share's toolbar

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1695]
**Storage Explorer Version:** 1.9.0
**Build:** master_20190821.3
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Language**: Chinese (zh-CN) / Russian (ru) / German (de)
**Regression From:** Not a regression

**Steps to reproduce:**
1. Run the command '**_StorageExplorer.exe --lang=zh-CN_**' to launch storage explorer.
2. Expand one storage account -> File Shares.
3. Create a new file share -> Observe its toolbar.

**Expect Experience:**
All buttons are localized.

**Actual Experience:**
'Rename' button is not localized.
![image](https://user-images.githubusercontent.com/41351993/63418776-3bad4500-c436-11e9-970a-5789af4b1a0a.png)

**More Info:**
This issue doesn't reproduce for one blob container.

**Comment by craxal** [comment]
Ah, we missed localizing this string. Good catch!
