### ISSUE TITLE
Miss '...' next to localized actions 'Break Lease' & 'Undelete by Date' for one blob

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1696]
**Storage Explorer Version:** 1.10.1
**Build:** master_20190925.6
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Language**: Chinese (zh-CN)(zh-TW) / Russian (ru) / German (de)
**Regression From:** Not a regression

**Steps to reproduce:**
1. Run the command '**_StorageExplorer.exe --lang=zh-CN_**' to launch storage explorer.
2. Expand one storage account -> Blob Containers.
3. Select one blob container which contains one blob at least .
4. Right click one blob and check its context menu.

**Expect Experience:**
Display '...' next to the localized actions 'Break Lease' &‘Change Access Tier’ &'Undelete by Date'

**Actual Experience:**
Miss '...' next to localized actions 'Break Lease' &‘Change Access Tier’& 'Undelete by Date' for one blob.
![image](https://user-images.githubusercontent.com/41351993/65589422-97ca3280-dfbb-11e9-81c2-5d1defc9dc49.png)

**More Info:**
This issue also reproduces on the localized 'Edit' action for table's entity.
![image](https://user-images.githubusercontent.com/41351993/63420107-99db2780-c438-11e9-96e3-011fe95666bd.png)

**Comment by johnliu2016** [comment]
Punctuation mismatch

Resource ID: 0;"String Table"\0;"Strings"\0;"ContextMenu.BreakLeaseCommandName"
Relative File Path: drop\loc\en\src\components\se-blob-extension\resources\BlobEditor.json.lcg​
Project: StorageExplorer​
Subtenant: StorageExplorer
ENU: Break Lease...
CHS: 中断租约

Resource ID: 0;"String Table"\0;"Strings"\0;"Toolbar.UndeleteByDateCommandName"
Relative File Path: drop\loc\en\src\components\se-blob-extension\resources\BlobEditor.json.lcg​
Project: StorageExplorer​
Subtenant: StorageExplorer
ENU: Undelete by Date...
CHS: 按日期取消删除

Resource ID: 0;"String Table"\0;"Strings"\0;"ContextMenu.EditEntityCommandName"
Relative File Path: drop\loc\en\src\components\se-table-extension\resources\TableEditor.json.lcg​
Project: StorageExplorer​
Subtenant: StorageExplorer
ENU: Edit...
CHS: 编辑

**Comment by johnliu2016** [comment]
LM review result:

Approved Change:
ENU: Break Lease...
CHS: 中断租约...

ENU: Undelete by Date...
CHS: 按日期取消删除...

ENU: Edit...
CHS: 编辑...

**Comment by johnliu2016** [comment]
Implemented as LM review suggestion.

**Comment by lukaschal** [comment]
@v-xianya Still repro on latest build ?

**Comment by v-xianya** [comment]
Hi @lukaschal Verified this issue on build 20191018.3.
1. This issue still reproduces in Chinese(zh-TW)/ Russian (ru) / German(de).
2. This issue doesn't reproduce in Chinese (zh-CN).
![image](https://user-images.githubusercontent.com/41351993/67061402-ca1e1880-f192-11e9-9a67-de4e7cda568b.png)
![image](https://user-images.githubusercontent.com/41351993/67061508-19fcdf80-f193-11e9-875a-3370d10097d1.png)
![image](https://user-images.githubusercontent.com/41351993/67061682-9394cd80-f193-11e9-9c34-32c6a30f1103.png)

**Comment by lukaschal** [comment]
Fixed on all languages.

**Comment by MRayermannMSFT** [comment]
Need to update packages and verify
