### ISSUE TITLE
An extra '...' displays to localized 'Selection Statistics' for one blob

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1698]
**Storage Explorer Version:** 1.9.0
**Build:** master_20190821.3
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Language**: Chinese (zh-CN) / Chinese (zh-TW) / Russian (ru) / German (de)
**Regression From:** Not a regression

**Steps to reproduce:**
1. Run the command 'StorageExplorer.exe --lang=zh-CN' to launch storage explorer.
2. Expand one Non-ADLS Gen2 storage account -> Blob Containers.
3. Select one blob container which contains at least one blob.
4. Select one blob and check its context menu.

**Expect Experience:**
No  '...' displays to localized 'Selection Statistics' for one blob.

**Actual Experience:**
An extra '...' displays to localized 'Selection Statistics' for one blob.
![image](https://user-images.githubusercontent.com/41351993/63421166-ba0be600-c43a-11e9-8a15-9d1bd9a5d9d5.png)

**More Info:**
This issue also reproduce for files under one file share.

**Comment by lukaschal** [comment]
Fixed.

File: loc\en\src\components\se-blob-extension\resources\BlobEditor.json
ID: 0; "Toolbar.SelectStatsCommandName"
SRC: Selection Statistics
TGT: 选择内容统计信息

File: loc\en\src\components\se-file-extension\resources\FileEditor.json
ID: 0; "Toolbar.SelectStatsCommandName"
SRC: Selection Statistics
TGT: 选择内容统计信息

**Comment by v-xianya** [comment]
1. This issue has been fixed in Chinese (zh-CN).
2. This issue still reproduces in Chinese (zh-TW) /Russian (ru) / German (de). **So we re-open it.**
3. We only verified this issue in these four lanuages. (Chinese (zh-CN) / Chinese (zh-TW) / Russian (ru) / German (de)).

**Comment by lukaschal** [comment]
Fixed on all languages.
