### ISSUE TITLE
Can't accept agreement in 1.1.0 installer

### ISSUE THREAD

**Issue by jeffschoner** [Microsoft/AzureStorageExplorer#170]
**Storage Explorer Version**: 1.1.0

**Platform**: Windows

**Architecture**: ia32

**Build Number**: ?

**Commit**: ?

#### Steps to Reproduce: ####

1. Download Storage Explore 1.1.0 either from the prompt in 1.0.0 or by downloading the installer off the website
2. Open the installer
3. Get prompted to accept the legal agreement

#### Expected Experience: ####
Can click "I agree" and continue with installation.

#### Actual Experience: ####
Cannot select "I agree". I've tried scrolling to the bottom of the text. Also, the cancel button does not work. I had to go into Task Manager and kill the process to get it to exit.

**Comment by MRayermannMSFT** [comment]
Have you tried just the one time or multiple times? Unfortunately I am unable to repro this. If it consistently repros, then you could try running it silently from the command line:
`.\StorageExplorer.exe /verysilent/supressmsgboxes  `

**Comment by jeffschoner** [comment]
I tried several times to no avail. I'm not sure what's different about my
computer or set up that might be causing this, unfortunately. I'll try the
command line option when I get home tonight.

**Comment by craxal** [comment]
Closing this bug as stale. If this continues to be an issue, please let us know, and we can reopen.

**Comment by fcaballe** [comment]
This is happening. to me. I have tried everything suggested here. Also, when i used the Tab key to navigate UI elements the accept radio button is not enabled even though in the UI appears enable. Who knows what the logic is there. And no information, this is very frustrating.

**Comment by jinglouMSFT** [comment]
@fcaballe which version of Storage Explorer did you try to install and on what OS?

**Comment by fcaballe** [comment]
Edition: Windows 10 Home
 Version: 20H2  
 Build: 19042.928

Azure StorageExplorer: 1.19.0

**Comment by jinglouMSFT** [comment]
This is not reproduceable for me, but could you try a few things?

-  Run the setup silently from the command line: .\StorageExplorer.exe /verysilent/supressmsgboxes.  You need to do this in the folder where StorageExplorer.exe is  
- Use the tab key to move the focus to "I do not accept the agreement", then use the up arrow key to move the focus to "I accept the agreement" radio button.  Then click the "Install" button
- if you still don't have any luck, try to change the screen resolution to something like 1024x768, then try the setup again
- If you think it's your Windows account permission limitation, try to launch StorageExplorer.exe, the installer for Windows, in the admin mode.  You can navigate to the folder where you downloaded StorageExplorer.exe, right click on it and select "Run as administrator".  Try to see if you can accept the EULA during the install. 

I hope one of these would help you get a successful install.  Let us know if none of these works.  Thanks.

**Comment by aeromac** [comment]
I get this with 1.24.0 on Windows 11. Closing and opening doesn't help. The Cancel button also becomes unclickable. 
Also, if I choose to install 'All users' I get this: ShellExecuteEx failed; code 3221226505

StorageExplorer.exe /VERYSILENT /SUPRESSMSGBOXES works (although, above you have no space between the two switches)

**Comment by JustDre** [comment]
Am getting this also on 1.28.0.  Someone clever probably dictated that the "I accept the agreement" cannot be selected unless you're scrolled to the bottom.  I scrolled, even put the cursor in the textbox and scrolled down using the cursor.

I can confirm that @aeromac 's workaround works.
