### ISSUE TITLE
Extra '...' is added in the descriptions on blob upload dialog with AzCopy checked

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1700]
**Storage Explorer Version:** 1.9.0
**Build:** master_20190821.3
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Language**: Chinese (zh-CN)
**Regression From:** Not a regression

**Steps to reproduce:**
1. Run the command 'StorageExplorer.exe --lang=zh-CN' to launch storage explorer.
2. Make sure the AzCopy is checked.
3. Expand one Non-ADLS Gen2 account -> Blob Containers.
4. Create a new blob container -> Click '上载' to open upload dialog.
5. Check the upload dialog.

**Expect Experience:**
No '...' shows in the descriptions on the upload dialog.

**Actual Experience:**
Extra '...' is added in the descriptions on the upload dialog.
![image](https://user-images.githubusercontent.com/41351993/63422032-30f5ae80-c43c-11e9-8274-677d6ab7ac65.png)

**Comment by craxal** [comment]
@v-xianya The screenshot doesn't appear to have any ellipses. Perhaps not the right screenshot?

**Comment by v-xianya** [comment]
Hi @craxal The ellopses shows in the sentence.
![image](https://user-images.githubusercontent.com/41351993/63490301-f137d100-c4e6-11e9-83e9-aa4d8542faf6.png)

**Comment by craxal** [comment]
@v-xianya Ah, sorry, didn't see it. Thanks.

**Comment by lukaschal** [comment]
Fixed.

File: loc\en\src\components\se-az-copy-extension\resources\UploadBlobsDlg.json
ID: 0; "TypeOfBlobToUpload"
SRC: , the type of blob you want to upload as
TGT: ，要作为哪种 blob 类型上传

**Comment by craxal** [comment]
Need to update extension package version.

**Comment by JasonYeMSFT** [comment]
This has been fixed in the latest build.
