### ISSUE TITLE
Proeprty 'ID' is not localized on one queue editor

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1701]
**Storage Explorer Version:** 1.9.0
**Build:** master_20190821.3
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Language**: Chinese (zh-CN) / German (de)
**Regression From:** Not a regression

**Steps to reproduce:**
1. Run the command 'StorageExplorer.exe --lang=zh-CN' to launch storage explorer.
2. Expand one storage account -> Queues.
3. Create a new queue -> Check its editor.

**Expect Experience:**
ID is locaized.

**Actual Experience:**
 ID is not localized.
![image](https://user-images.githubusercontent.com/41351993/63422406-e0328580-c43c-11e9-9d53-b2893dabdc13.png)

**Comment by johnliu2016** [comment]
'ID' usually translates as is in English for zh-CN, checking with linguistic

**Comment by johnliu2016** [comment]
Linguist confirms it's fine to keep as 'ID' in Chinese string.
