### ISSUE TITLE
No tooltip shows for the Settings button

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1708]
**Storage Explorer Version:** 1.9.0
**Build:** 20190822.2
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04
**Branch:** master
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch storage explorer.
2. Hover over the Settings button.
3. Check whether the tooltip shows well or not.

**Expect Experience:**
The tooltip shows well.

**Actual Experience:**
No tooltip shows.
![image](https://user-images.githubusercontent.com/41351993/63502696-afb41f80-c500-11e9-8f3d-a259b5ac989a.png)

**Comment by v-xuanzh** [comment]
This issue has been fixed on the latest master build 20190827.3. So close it.
