### ISSUE TITLE
No red borer shows when inputting an expression as a SAS duration on AzCopy tab of Setting Panel

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1709]
**Storage Explorer Version:** 1.9.0
**Build:** 20190822.2
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04
**Branch**: master
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open the Setting Panel using 'Settings' icon or 'Edit' -> 'Settings'.
3. Go to 'AzCopy' tab -> Input an expression as a SAS duration.
4. Check the prompt message.

**Expect Experience:**

1. It shows 'Please enter a number'.
2. A red border shows due to the inputting is invalid.

**Actual Experience:**

1. It shows 'Please enter a number'.
2. No red border shows.
![image](https://user-images.githubusercontent.com/34729022/63503580-4fbe7880-c502-11e9-8e65-f769b76da082.png)

**Comment by MRayermannMSFT** [comment]
Won't fix.
