### ISSUE TITLE
'Change Access Tier' is disabled for block blobs of blob accounts and V2 accounts

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#171]
**Storage Explorer Version**: 1.1.0

**Platform**: Windows

**Architecture**: x64

**Build Number**: 20180510.2

**Commit**: d271505a

**Regression From**: Previous release 1.1.0

#### Steps to Reproduce: ####

1. Launch Storage Explorer and select a V2 account.
2. Set the default access tier for the account and open one blob container.
3. Upload one block blob.
4. Right click the uploaded blob and check whether 'Change Access Tier' is enabled or not.

#### Expected Experience: ####
'Change Access Tier' is enabled.

#### Actual Experience: ####
'Change Access Tier' is disabled.
![disabled](https://user-images.githubusercontent.com/34729022/39985006-8640eeb2-574c-11e8-83ea-fbcc9779863c.png)

**Comment by MRayermannMSFT** [comment]
Merged into master for 1.2.0.

**Comment by fields987** [comment]
The "Change Access Tier" option is still grayed out for me in 1.4.1.

**Comment by 020tecmakerhub** [comment]
Please check if you're applying a change on a right block type. Not all types of block support access tiers. For example, append blob doesn't support access tiers.
