### ISSUE TITLE
Keep a consistent format for the preview features between English and Localization

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1710]
**Storage Explorer Version:** 1.9.0
**Build:** 20190822.2
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04
**Branch:** master
**Architecture:** ia32/x64
**Language:** Chinese(zh-CN) / German(de) / Russian(ru)
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Navigate to Preview menu -> Check the preview features. 
3. Close the Storage Explorer ->Run the command 'StorageExplorer.exe --lang=zh-CN' to launch Storage Explorer.
4. Navigate to Preview menu -> Check the preview features. 

**Expect Experience:**
The preview features format is consisent between English and Localization languages.

**Actual Experience:**
The preview features format is inconsisent between English and Localization languages.
![image](https://user-images.githubusercontent.com/41351993/63503818-cf4c4780-c502-11e9-82f3-57814b1d8013.png)

**Comment by craxal** [comment]
@v-xianya What do you mean by "format"? Are you referring to capitalization? That doesn't really matter here, because these strings aren't event localized yet.

**Comment by v-xianya** [comment]
Hi @craxal 
Do not consider the localization. We noticed:
1. On **1.9.0 release** build, the preview feature shows like below.
![image](https://user-images.githubusercontent.com/41351993/63568673-a41c3380-c5a8-11e9-8c55-03bc7dc1fe86.png)
2. On **build master/20190815.2**, the preview feature shows like below.
![image](https://user-images.githubusercontent.com/41351993/63569119-98317100-c5aa-11e9-9bdb-a836ea0227cb.png)

3. On the latest **build 20190823.5**, the preview feature shows like below.
![image](https://user-images.githubusercontent.com/41351993/63568876-97e4a600-c5a9-11e9-9d18-2550f29ab19d.png)

**Comment by JasonYeMSFT** [comment]
We are getting rid of this menu. Closed.
