### ISSUE TITLE
Always keep loading when trying to launch storage explorer on Mac

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1711]
**Storage Explorer Version:** 1.9.0
**Build:** 20190822.2
**Platform/OS:** macOS High Sierra
**Branch:** master
**Architecture:** x64
**Regression From:** Previous release(1.9.0)

**Steps to reproduce:**
1. Launch Storage Explorer on Mac.

**Expect Experience:**
Launched successfully.

**Actual Experience:**
Always keep loading.
![image](https://user-images.githubusercontent.com/41351993/63503676-82687100-c502-11e9-96ce-55edfcdee691.png)

**Comment by craxal** [comment]
Tested against several different commits and found it starts freezing at commit af3175, which is where the Settings UI was integrated. @JasonYang-MSFT Can you investigate?

**Comment by v-xianya** [comment]
This issue has been fixed on build master/20190827.3. So we close it.
