### ISSUE TITLE
The localized tooltip of 'Save Query as…' shows zh-TW rather than zh-CN

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1714]
**Storage Explorer Version:** 1.9.0
**Build:** 20190823.5
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04
**Branch:** master
**Architecture:** ia32/x64
**Language:** Chinese(zh-CN)
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer using the command '**_StorageExplorer.exe --lang=zh-CN_**'.
2. Open one table -> Click '查询' button on the toolbar.
3. Focus on the localized 'Save Query as...' -> Check the tooltip.

**Expect Experience:**

The tooltip shows as zh-CN.

**Actual Experience:**

The tooltip shows as zh-TW.
![image](https://user-images.githubusercontent.com/34729022/63577977-1ea57d00-c5c2-11e9-9d1b-a4a5ff042145.png)

**More info:**

This issue also reproduces on localized 'Save Query'/'Stop Query'.

**Comment by johnliu2016** [comment]
Observed in current loc pool, icon tooltips are correctly localized to zh-CN.

**Comment by craxal** [comment]
We probably need to generate a new version of the `se-tables-extension` package

**Comment by v-xianya** [comment]
This issue fixed on build 20190924.3. So we close it.
