### ISSUE TITLE
No 'Access Tier'/'AccessTierChangeTime' columns display on container's editor for blob account and V2 account

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#172]
**Storage Explorer Version**: 1.1.0

**Platform**: Windows

**Architecture**: x64

**Build Number**: 20180510.2

**Commit**: d271505a

**Regression From**: Previous release 1.1.0

#### Steps to Reproduce: ####

1. Launch Storage Explorer and select a V2 account. 
2. Open one blob container and check whether 'Access Tier'/'AccessTierChangeTime' columns display well or not.

#### Expected Experience: ####
'Access Tier'/'AccessTierChangeTime' columns display well.

#### Actual Experience: ####
No 'Access Tier'/'AccessTierChangeTime' columns display on the container's editor.
![columns](https://user-images.githubusercontent.com/34729022/39985314-c7c9e9fa-574d-11e8-8e97-958af3044afa.png)

**Comment by JakeRadMSFT** [comment]
By design. Do you mean V2 or GPv2?

**Comment by JakeRadMSFT** [comment]
Leaving open, I'll investigate to make sure GPv2 is still working in Master.

**Comment by v-xuanzh** [comment]
Hi Jake,
For GPv2 account which is set as 'Cool' Access Tier(account level),  No 'Access Tier'/'AccessTierChangeTime' columns display on container's editor.

More info:
This issue doesn't reproduce for Blob accounts which is set as 'Cool'.

**Comment by MRayermannMSFT** [comment]
Merged into master for 1.2.0.
