### ISSUE TITLE
Azcopy login failure

### ISSUE THREAD

**Issue by sterkhedkar** [microsoft/AzureStorageExplorer#1721]
**Storage Explorer Version**: v10
**Build Number**: not sure
**Platform/OS**: debian 9
**Architecture**: x64
**Regression From**:  none

## Bug Description ##
The azcopy login fails with following error thrown on retrying the login after 4-5 hours of a successful login.

```
azcopy login --tenant-id "some-tenant-id"
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code EV2D9L34H to authenticate.
Failed to perform login command: 
failed to get keyring during saving token, key has been revoked
NOTE: If your credential was created in the last 5 minutes, please wait a few minutes and try again.

```
## Steps to Reproduce ##
- We are using oAuth method to login to azcopy v10 on GCP compute instance
- azcopy login --tenant-id "some-tenant-id"
- It works fine for the first login. 
- Then I run a sync job
- Sync job fails with errors
- retry sync - then authorization error
- re-login - fail to login.

**Comment by MRayermannMSFT** [comment]
This looks like it'd be better suited for the AzCopy repo. Thanks! https://github.com/Azure/azure-storage-azcopy/issues
