### ISSUE TITLE
Keep a consistent tooltip for the localized 'Dequeue Message' button

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1723]
**Storage Explorer Version:** 1.10.0
**Build:** 20190827.12
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Language:** Chinese (zh-CN)/ Russian(ru)/ German(de)
**Regression From:** Not a regression

**Steps to reproduce:**
1. Run the command 'StorageExplorer.exe --lang=zh-CN' to launch Storage Explorer.
2. Expand one storage account -> Queues.
3. Create a new queue -> Check the tooltip for '取消排队消息' button.

**Expect Experience:**
Display a consistent tooltip for the  '取消排队消息' button.

**Actual Experience:**
Display an inconsistent tooltip for the  '取消排队消息' button.
![image](https://user-images.githubusercontent.com/41351993/63756306-b79e0600-c8ea-11e9-8934-dca98a202452.png)

**More Info:**
Display a consistent tooltip for the 'Dequeue Message' button on English.
![image](https://user-images.githubusercontent.com/41351993/63755907-08612f00-c8ea-11e9-84bb-c4ebd76e47d8.png)

**Comment by lukaschal** [comment]
On review.

File: loc\en\src\components\se-queue-extension\resources\QueueEditor.json
ID: 0; "Toolbar.DequeueCommandDescription"
SRC: Dequeue Message
TGT: 取消排队

File: loc\en\src\components\se-queue-extension\resources\QueueEditor.json
ID: 0; "Toolbar.DequeueMessageCommandName"
SRC: Dequeue Message
TGT: 取消排队消息

**Comment by lukaschal** [comment]
Fixed.

File: loc\en\src\components\se-queue-extension\resources\QueueEditor.json
ID: 0; "Toolbar.DequeueCommandDescription"
SRC: Dequeue Message
TGT: 取消排队消息

**Comment by craxal** [comment]
Verified on master.

**Comment by v-xianya** [comment]
This issue reproduces on the latest build master/20190917.7. So we re-open it.

**Comment by craxal** [comment]
Need to build a new version of the queue extension.
