### ISSUE TITLE
It's better to translate 'Transfers' to '传输' rather than '转让' on Settings panel

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1724]
**Storage Explorer Version:** 1.10.0
**Build:** 20190827.12
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS High Sierra
**Architecture:** ia32/x64
**Language:** Chinese (zh-CN)
**Regression From:** Not a regression

**Steps to reproduce:**
1. Run the command 'StorageExplorer.exe --lang=zh-CN' to launch Storage Explorer.
2. Open Settings panel and check the translation of 'Transfers'.

**Actual Experience:**
Translate 'Transfers' to '转让'.
![image](https://user-images.githubusercontent.com/41351993/63755550-7d803480-c8e9-11e9-918d-b3e151067a39.png)

**Suggestion:**
It's better to translate 'Transfers' to '传输' rather than '转让'.

**Comment by lukaschal** [comment]
On review.

File: loc\en\src\components\se-az-copy-extension\resources\AzCopySettings.json
ID: 0; "TitleTransfer"
SRC: Transfers
TGT: 转让

**Comment by lukaschal** [comment]
Fixed.

Linguistic answer:

this current target 转让 is usually used in financial context, not suitable here. It should be changed to 传输.

**Comment by craxal** [comment]
@lukaschal Verified of master. String has not changed, so I'm assuming this is by design.
