### ISSUE TITLE
Miss a description on 'Data Explorers' tab of Settings Panel

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1726]
**Storage Explorer Version:** 1.10.0
**Build:** 20190827.12
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open Settings Panel -> Go to 'Data Explorers' tab.
3. Check whether the description shows on the border line or not.

**Expect Experience:**

There shows a description on the border line.

**Actual Experience:**

No description shows on the border line.
![image](https://user-images.githubusercontent.com/34729022/63758466-66901100-c8ee-11e9-8a7a-a9ad707a68ed.png)

**Comment by MRayermannMSFT** [comment]
By design
