### ISSUE TITLE
An extra log message after closing the 'Update Access Tier' dialog or clicking Cancel'

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#173]
**Storage Explorer Version**: 1.1.0

**Platform**: Windows

**Architecture**: x64

**Build Number**: 20180510.2

**Commit**: d271505a

**Regression From**:  Not a regression

#### Steps to Reproduce: ####

1. Launch Storage Explorer and select a V2 account. 
2. Right click the V2 account and select 'Set Default Access Tier'.
3. Close the 'Update Access Tier' dialog directly.

#### Expected Experience: ####
No log message display on Activities Panel.

#### Actual Experience: ####
'Canceled Access Tier of 'account_name' displays on Activities Panel.
![canceled](https://user-images.githubusercontent.com/34729022/39986956-d0aa97d6-5752-11e8-832c-653e6fc6b19e.png)

More info:
This issue doesn't reproduce for 'Set Public Access Level'.

**Comment by JakeRadMSFT** [comment]
By Design
