### ISSUE TITLE
Azure storage explorer 1.9.0 Connection Issue 

### ISSUE THREAD

**Issue by ayon1911** [microsoft/AzureStorageExplorer#1730]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 

## Steps to Reproduce ##
- Click on add an account
- Click on add account with the account name and key
- Enter the account name and the key along with the display name
- Add then click finish

**Comment by phuketk0k** [comment]
I'm following these steps and getting the error below if I try and connect via string, access key or SAS:
Error occurred while adding new connection: TypeError:Cannot read property 'uids' of undefined

**Comment by MRayermannMSFT** [comment]
Can y'all please update to 1.10.1 and try again? We have fixed the Cannot read property 'uids' of undefined issue.
