### ISSUE TITLE
Tab key must be pressed twice to focus on 'Cancel' link in Activity Log

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1734]
**Storage Explorer Version:** 1.10.0
**Build:** 20190828.6
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Open one storage account -> Open one large table(StorageExplorer/Storage Accounts/stgexp/Tables/table200x5000).
2. Execute the action 'Table Statistics'.
4. Focus on the statistics message on Activities -> Try to press 'Tab' to focus the 'Cancel' link.

**Expect Experience:**

Pressing Tab once can focus on the 'Cancel' link.

**Actual Experience:**

Pressing Tab twice can focus on the 'Cancel' link.
![image](https://user-images.githubusercontent.com/34729022/63840822-4460c680-c9b4-11e9-8f82-9b20dad4e952.png)

**Comment by craxal** [comment]
The first Tab moves focus to a "phantom" element, which is actually the element normally used to display the progress of the activity. The reason for this is because the element has `tabindex`. We probably just need to not render the element if it's empty.

**Comment by v-xianya** [comment]
This issue still reproduces on build **hotfix/1.11.1** 20191120.3 and **master**/20191119.12.
so we re-open it.

**Comment by craxal** [comment]
Cloud Explorer reference needs to be updated. Please try another build.
