### ISSUE TITLE
There is no red border for the access policies id box if its name is too long

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/AzureStorageExplorer#1735]
**Storage Explorer Version:** 1.10.0
**Build:** 20190828.6
**Platform/OS:** Linux Ubuntu 19.04/Windows 10/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a Regression

**Steps to reproduce:**

1. Right click one blob container/file share/queue/table and click 'Manage Access Policies...'.
2. Add a new policies with a long id, such as more than 63 characters.
3. Check whether there is red border for this id box or not.

**Expect Experience:**
There is a red border for this id box and the Save button is disabled.

**Actual Experience:**
There is no red border for the access policies id box and the Save button is enabled.
![image](https://user-images.githubusercontent.com/45614674/63845935-6579e500-c9bd-11e9-9f22-d6f362828b8d.png)

**More info:**
1. An error dialog pops up if save this invalid access policies for File Shares/Queue/Table.
![image](https://user-images.githubusercontent.com/45614674/63846065-9b1ece00-c9bd-11e9-80b4-c9c3e2333b14.png)
2. There is an error if save this invalid access policies for blob container.
![image](https://user-images.githubusercontent.com/45614674/63846161-cef9f380-c9bd-11e9-955b-c28f312b822b.png)

**Comment by MRayermannMSFT** [comment]
Won't fix pending customer feedback.
