### ISSUE TITLE
Extra three properties related to 'Access Tier' display in 'Properties' dialog for premium blobs

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#174]
**Storage Explorer Version**: 1.1.0

**Platform**: Windows

**Architecture**: x64

**Build Number**: 20180510.2

**Commit**: 271505a

**Regression From**: Not a regression

#### Steps to Reproduce: ####

1. Launch Storage Explorer and select a premium account. 
2. Open one blob container and upload one page blob for it.
3. Open the blob 'Properties' dialog and check the blob's properties. 

#### Expected Experience: ####
None of properties related to 'Access Tier' display.

#### Actual Experience: ####
Extra three properties related to 'Access Tier' display.
![properties](https://user-images.githubusercontent.com/34729022/39988370-b285c4d4-5756-11e8-8f27-e7eca3a90be0.png)

**Comment by JakeRadMSFT** [comment]
They're all valid. It's just byproduct of Storage Team using Access Tier for multiple meaning (Premium and Hot/Cool/Archive).
