### ISSUE TITLE
Show a confusing message in Activities after copying one file share

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#1744]
**Storage Explorer Version**: 1.9.0
**Build**: 20190828.15
**Branch:** master
**Platform/OS**: Windows 10/Linux Ubuntu 18.04/macOS High Sierra
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**

1. Expand one storage account -> File Shares.
2. Select one file share which contains files and directories.
3. Copy this file share -> Check the message in Activities after pasting successfully.

**Expect Experience:**
Show a clear message in Activities after copying one file share.

**Actual Experience:**
Show a confusing message in Activities after copying one file share.
![image](https://user-images.githubusercontent.com/54055206/63927837-18f7dd80-ca81-11e9-8a5b-7b337f05bbc1.png)

**More Info:**
1. Show the below message in Activities after executing the action 'Directory Statistics' for this file share.
![image](https://user-images.githubusercontent.com/54055206/63931869-b30f5400-ca88-11e9-8a73-95c9be61a3d1.png)

**Comment by v-limu** [comment]
This issue doesn't reproduce on the latest master build [20190920.6.](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3071039) So closed it.

**Comment by v-limu** [comment]
This issue reproduces on the latest master build [20190927.2.](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3088411) So we reopen it.
![image](https://user-images.githubusercontent.com/54055206/65745749-4e9aef80-e12f-11e9-9ae7-9d01a6aa4514.png)

**Comment by MRayermannMSFT** [comment]
Closing b/c we're going to move files to azcopy and so this code path/method of displaying numbers will go away. Agreed it's bad right now though. :(
