### ISSUE TITLE
Storage Explorer not working for uploads

### ISSUE THREAD

**Issue by DavidASmithOTPP** [microsoft/AzureStorageExplorer#1745]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:

**Comment by JasonYeMSFT** [comment]
Hi @DavidASmithOTPP ,

Could please provide more information about your issue? What type of upload are you performing (e.g. blob upload, fileshare upload, etc.) ? Does Storage Explorer show any message in the Activity tab for the upload? Are you uploading from a local directory or some special directory (e.g. OneDrive)?

Thanks.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
