### ISSUE TITLE
Nothing happens after selecting 'Acquire Lease' for a blob inside one attached blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1746]
**Storage Explorer Version:** 1.10.0
**Build:** 20190830.2
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Attach one blob container which contains one blob at least with **Read & List** perimissons.
2. Expand Local & Attached -> Storage Accounts -> Attached Containers -> Blob Containers.
3. Open the attached blob container -> Right click one blob then select 'Acquire Lease'.
4. Check the result.

**Expect Experience:**
An error message displays in Activities indicates that this request is not authorized to perform this permisson.

**Actual Experience:**
Nothing happens after selcting 'Acquire Lease'.

**More Info:**
This issue also reproduces for blobs which inside Azure AD attached blob containers with 'Storage Blob Data Reader'

**Comment by craxal** [comment]
I'm able to reproduce when the SAS only has Read and List permissions. From the command line, I get an uncaught error saying I'm not authorized to acquire a lease. So I'll fix that. Please double-check your permissions and see if this still reproduces if you have write permissions.

**Comment by v-xianya** [comment]
Hi @craxal Thanks for your updates!
This issue doesn't reproduce when the SAS URI with '**Read &List & Write**' permissions.
