### ISSUE TITLE
The shown name of sub file doesn't contain its parent directory name on Properties dialog

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1748]
**Storage Explorer Version:** 1.10.0
**Build:** 20190830.2
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one account -> File Shares node.
2. Create a new file share -> Create a new directory.
3. Go to the created directory -> Upload one file and one directory.
4. Check the name of file and directory on Properties dialog.

**Expect Experience:**

The file name contains its parent directory.

**Actual Experience:**

The file name doesn't contain its parent directory.
![image](https://user-images.githubusercontent.com/34729022/64001581-bc58f900-cb3a-11e9-8ede-a2815118ac40.png)

**More info:**

This issue doesn't reproduce for one ADLS Gen2 blob file.

**Comment by craxal** [comment]
By design. Since files are actually organized into directories, the actual name of the file is as shown.
