### ISSUE TITLE
Allow to delete resource groups in Storage Explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1749]
**Storage Explorer Version:** 1.10.0
**Platform/OS:** Windows 10
**Architecture:** x64
**Commit:** f06deb7a6
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand 'Disks' -> Right click one resource group.

**Suggestion:**
It's better to have 'Delete' action for resource groups. 

**Actual Experience:**
No 'Delete' action for resource groups.

**Comment by MRayermannMSFT** [comment]
Because the actual resource group contains more than just disks, we don't want to allow doing this from Storage Explorer
