### ISSUE TITLE
Unable to view Blob Containers in the Development Storage Account, gets stuck while loading

### ISSUE THREAD

**Issue by ttrichar** [Microsoft/AzureStorageExplorer#175]
Storage Explorer Version: 1.1.0
Platform: Windows
Architecture: ia32
Build Number: 20180507.1
Commit: bcc8990d
Regression From: Unsure
Steps to Reproduce:
1) Open Azure Storage Explorer
2) Navigate to Local and Attached/Storage Accounts/ (Development)/ Blob Containers
3) Expand "Blob Containers"

Expected Experience:
Storage explorer will list available blob containers

Actual Experience:
A "Loading" icon appears, but never finishes. The option to create a blob container is available, but as soon as the name is entered, it disappears, and the loading icon remains.

**Comment by MRayermannMSFT** [comment]
Did you start your storage emulator before opening Storage Explorer?

**Comment by ttrichar** [comment]
Ah yes, that would help. That fixed my issue, thank you!

**Comment by MRayermannMSFT** [comment]
:)

**Comment by pankajag** [comment]
I am even not able to open Azure Storage Explorer

**Comment by craxal** [comment]
@pankajag It's likely not related to development storage specifically. Double-check our release notes and existing issues here on GitHub. If you're not finding anything that solves your issue, please open a new issue.

**Comment by ede0m** [comment]
This is happening for me as well. Trying to connect to blob storage in Azure Storage Emulator. Was working last week before I did a windows update and storage explorer update.

I am running azure storage emulator from a docker container.

Just stalls and loads forever when searching through development -> blob storage
---------------------
Seems to work when running the application outside of docker.

**Comment by PMoransais** [comment]
Same Issue - worked before storage explorer 1.10 install on windows 10. Re-installed - same issue. Updated to latest windows 10 same issue

When checking with task manager the process is running, seemingly in a loop see screen shot
![capture](https://user-images.githubusercontent.com/19433579/40269355-9646fd80-5b4b-11e8-9548-98337a06373a.PNG)

thanks

**Comment by craxal** [comment]
Hm, normally, we should be throwing errors if communication errors are detected...

The developer node is hardcoded to look for services on the local machine at the default ports (blobs at 10000, queues at 10001, and tables at 10002). Currently, this is not configurable (but we're working on this).

One possibility is communication across Docker container boundaries frustrates this. Something inside the container probably has a different external endpoint. You may need to do something with your Docker container to properly expose the emulator's service endpoints.

Since we're already working on a better experience for emulators, I'm going to suggest you not run emulators in Docker containers as a workaround for the time being.

**Comment by predssj4** [comment]
I have the same issue. Does someone have any idea where is the problem ? I've configured emulator.
Installed on the second PC, the same problem.

**Comment by craxal** [comment]
What are your emulator's endpoints? Did you actually start the emulator?

**Comment by predssj4** [comment]
Sorry to misdirect you. There is something wrong with my  Azure account. I've logged in a office using my work account - everything ok, but with my "test" account, that I've mentioned above, the problem still occurs.

I can't access the configuration of my work account - someone else did it before, but I will try to ask him.

Nonetheless, any ideas ?

**Comment by craxal** [comment]
@predssj4 Your question is somewhat off topic, as the original issue is related to local emulator connections. I suggest you search for other issues (we have a lot of open sign-in related issues) more likely similar to yours. If you can't find any, feel free to open a new issue.

**Comment by predssj4** [comment]
@craxal this is what I get :  https://github.com/Microsoft/AzureStorageExplorer/issues/223 , thx for the interest.
