### ISSUE TITLE
Miss two icons on Actions panel for resource groups 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1750]
**Storage Explorer Version:** 1.10.0
**Platform/OS:** Windows 10
**Architecture:** x64
**Commit:** f06deb7a6
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand 'Disks' -> Select one resource group.
2. Observe its actions on 'Actions' Panel.

**Expect Experience:**
Icons display well for 'Open' and Add to Quick Access' actions.

**Actual Experience:**
No icon displays for 'Open' and Add to Quick Access' actions.
![image](https://user-images.githubusercontent.com/41351993/64102152-e829e800-cda1-11e9-8e5a-8db33acf2bf7.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into master
