### ISSUE TITLE
Fail to open resource groups from Disks for China/Germany account

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1751]
**Storage Explorer Version:** 1.10.0
**Platform/OS:** Windows 10
**Architecture:** x64
**Commit:** f06deb7a6
**Regression From:** Not a regression

**Steps to reproduce:**
1. Sign in to Storage Explorer with China(test@azuretools.partner.onmschina.cn) or Germany(cawa@bfdevopsnonrestricted.onmicrosoft.de) account.
2. Expand 'Disks' node -> Try to open one resource group.

**Expect Experience:**

The selected resource group can be opened successfully.

**Actual Experience:**

Fail to open the selected resource group with the below error.
![image](https://user-images.githubusercontent.com/34729022/64103306-7d2de080-cda4-11e9-8cf6-482760ec90f3.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into master
