### ISSUE TITLE
Add the icon of resource group before the opened resource group tab

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1752]
**Storage Explorer Version:** 1.10.0
**Platform/OS:** Windows 10
**Architecture:** x64
**Commit:** f06deb7a6
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand 'Disk' node -> Open one resource group.
2. Check the opened tab.

**Expect Experience:**

There shows the icon of resource group for the opened tab.

**Actual Experience:**

No icon shows for the opened tab.
![image](https://user-images.githubusercontent.com/34729022/64103728-705dbc80-cda5-11e9-8049-1f6d11df0f7d.png)

**Comment by MRayermannMSFT** [comment]
Decided to go with the disks node for the icon. Merged into master.
