### ISSUE TITLE
Add the 'Open in Portal' action for one resource group

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1754]
**Storage Explorer Version:** 1.10.0
**Platform/OS:** Windows 10
**Architecture:** x64
**Commit:** f06deb7a6
**Regression From:** Not a regression

**Steps to reproduce:**
1.  Expand 'Disks' -> Select one resource group.
2. Check its context menu.

**Expect Experience:**
The action 'Open in Portal' displays on the context menu.

**Actual Experience:**
No 'Open in Portal' displays on the context menu.
![image](https://user-images.githubusercontent.com/41351993/64103504-fe857300-cda4-11e9-81d9-0669463239a8.png)

**Comment by MRayermannMSFT** [comment]
For this issue, please understand that when you open the resource group in the portal, it'll show resources other than disks as well. This is by design. There is no way to open up the portal and only show disks in the resource group.
