### ISSUE TITLE
Cannot open new tabs using the 'Open New Tab' for one resource group

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1756]
**Storage Explorer Version:** 1.10.0
**Platform/OS:** Windows 10
**Architecture:** x64
**Commit:** f06deb7a6
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand 'Disks' -> Open one resource group.
2. Right click the same resource group -> Click 'Open New Tab'.
3. Check the result.

**Expect Experience:**
1. A new tab opens.
2. The new tab is focused.

**Actual Experience:**
1. No new tab opens.
2. The first opened tab is focused.

**Comment by MRayermannMSFT** [comment]
Fix merged into master
