### ISSUE TITLE
Add (Ctrl+R) next to the tooltip for Refresh button on one opened resource group

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1759]
**Storage Explorer Version:** 1.10.0
**Platform/OS:** Windows 10
**Architecture:** x64
**Commit:** f06deb7a6
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand 'Disks' node -> Open one resource group.
2. Hover the mouse to the Refresh button on the toolbar -> Check the tooltip.

**Expect Experience:**

1. Ctrl+R works well.
2. (Ctrl+R) shows next to the tooltip.

**Actual Experience:**

1. Ctrl+R works well.
2. (Ctrl+R) doesn't show next to the tooltip.
![image](https://user-images.githubusercontent.com/34729022/64106429-c123e400-cdaa-11e9-87cc-416b3fce0c69.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into master
