### ISSUE TITLE
"Access Tier" should show rehydration status

### ISSUE THREAD

**Issue by whiskeyjay** [microsoft/AzureStorageExplorer#176]
Version: 1.1.0
Platform: Windows
Architecture: ia32
Build Number: 20180507.1
Commit: bcc8990d

This is a feature request.

Since it can take hours to rehydrate an Archive Tier blob, it would be nice to have the "Access Tier" column to show rehydration status.

For example:

For normal Archive Tier blobs: "Archive"
For blobs being rehydrated to cool: "Archive (Pending to Cool)"
For blobs being rehydrated to hot: "Archive (Pending to Hot)"

The .NET storage API provides [this information](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.blob.rehydrationstatus?view=azure-dotnet), haven't checked the Node API but hopefully it does something similar.

**Comment by whiskeyjay** [comment]
This is related to the root cause of #155 which is not a duplicate of #157.

**Comment by MRayermannMSFT** [comment]
Rehydration status is now available in the properties dialog.
