### ISSUE TITLE
Add the action 'Refresh' for Disks node

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#1761]
**Storage Explorer Version:** 1.10.0
**Platform/OS:** Windows 10
**Architecture:** x64
**Commit:** f06deb7a6
**Regression From:** Not a regression

**Steps to reproduce:**

1. Select 'Disks' -> Check its context menu.

**Expect Experience:**
The action 'Refresh' displays well.

**Actual Experience:**
No 'Refresh' action displays.
![image](https://user-images.githubusercontent.com/54055206/64106386-ac475080-cdaa-11e9-8a6e-9ca5de4e9d70.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into master
