### ISSUE TITLE
Miss 'Open Folder' in Activities for downloading one disk

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#1762]
**Storage Explorer Version:** 1.10.0
**Platform/OS:** Windows 10
**Architecture:** x64
**Commit:** f06deb7a6
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand 'Disks' -> Right click one resource group.
2. Select one disk -> Download this disk -> Check the message in Activities.

**Expect Experience:**
 'Open Folder' shows in Activities after downloading this disk successfully.

**Actual Experience:**
No 'Open Folder' shows in Activities after downloading this disk.
![image](https://user-images.githubusercontent.com/54055206/64103826-9a16e380-cda5-11e9-80b8-131641656701.png)

**Comment by JasonYeMSFT** [comment]
I am adding the speed summary to the activity log for managed disk commands as well.
