### ISSUE TITLE
Unable to sort all the disks in sequence on each columns

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1763]
**Storage Explorer Version:** 1.10.0
**Platform/OS:** Windows 10
**Architecture:** x64
**Commit:** f06deb7a6
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand 'Disks' node -> Open one resource group.
2. Create multiple disks to it -> Click anyone column name like 'Disk Name'.
3. Check whether all disks can be sorted in sequence or not.

**Expect Experience:**

All disks can be sorted by the 
![image](https://user-images.githubusercontent.com/34729022/64106994-fd0b7900-cdab-11e9-84b1-0a9ea6ac869b.png)

**Actual Experience:**

Unable to sort all the disks in sequence.
![image](https://user-images.githubusercontent.com/34729022/64107053-2a582700-cdac-11e9-88b7-bf10d5514387.png)

**Comment by v-xianya** [comment]
This issue has been fixed on the build master/20190917.7. So we close it.
