### ISSUE TITLE
Show a permanent tab after single clicking one resource group

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1764]
**Storage Explorer Version:** 1.10.0
**Platform/OS:** Windows 10
**Architecture:** x64
**Commit:** f06deb7a6
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand 'Disks' -> Single click one resource group.
2. Observe the opened tab.

**Expect Experience:**
A temporary tab is opened.

**Actual Experience:**
A permanent tab is opened.
![image](https://user-images.githubusercontent.com/41351993/64107363-ef0a2800-cdac-11e9-9a4a-c25782215b65.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into master
