### ISSUE TITLE
Cannot open one resource group which name is same as the opened resource group

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1765]
**Storage Explorer Version:** 1.10.0
**Platform/OS:** Windows 10
**Architecture:** x64
**Commit:** f06deb7a6
**Regression From:** Not a regression

**Steps to reproduce:**
1. Create two resource group with the same name and different contents from separate subscriptions. Like below: 

No | Subscriptions | Resource   Group
-- | -- | --
1 | Azure Tools Manual   Testing 1 | xuantest1
2 | Azure Tools Manual   Testing 2 | xuantest1

2. Open the first resource group -> Make sure it has opened successfully.
3. Open the second resource group -> Check the result.

**Expect Experience:**

1. The second resource group can be opened.
2. The second resource group is focused.

**Actual Experience:**

1. The second resource group can not be opened.
2. The first resource group is focused.

**Comment by MRayermannMSFT** [comment]
Fix merged into master
