### ISSUE TITLE
Pop up an empty warning dialog when trying to copy & paste an attached blob container 

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1768]
**Storage Explorer Version:** 1.10.0
**Platform/OS:** Windows 10
**Architecture:** x64
**Commit:** f06deb7a6
**Regression From:** Previous release 1.9.0

**Steps to reproduce:**
1. Attach one blob container with SAS URI.
2. Expand 'Local & Attached' -> 'Storage Accounts' -> 'Blob Containers'.
3. Right click the attached blob container then select 'Copy Blob Container'.
4. Select an another account -> Right click 'Blob Containers' node then select 'Paste Blob Container'.

**Expect Experience:**

Pop up a warning dialog.
![image](https://user-images.githubusercontent.com/34729022/64160733-0a3d6c00-ce6f-11e9-9a99-0470aa5260d6.png)

**Actual Experience:**

Pop up an empty warning dialog like below.
![image](https://user-images.githubusercontent.com/34729022/64160769-1d503c00-ce6f-11e9-82a8-f702605a7003.png)

**More info:**

This issue also reproduce for attached file shares.

**Comment by MRayermannMSFT** [comment]
@craxal , if a string in non-english language X is not available, we should return the english string. Please make that happen!

**Comment by craxal** [comment]
Error here is also because the wrong namespace is referenced.
