### ISSUE TITLE
An attached table which source does not already exist can be pasted successfully

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1769]
**Storage Explorer Version:** 1.10.0
**Platform/OS:** Windows 10
**Architecture:** x64
**Commit:** f06deb7a6
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one account -> Select one table to attach with SAS URI.
2. Delete the original table from the selected account.
3. Expand 'Local & Attached' -> 'Storage Accounts' -> 'Tables'.
4. Make sure the current attached table cannot be opened.
5. Right click the attached table and select 'Copy Table'.
6. Select an another account -> Try to paste the attached table.

**Expect Experience:**

The attached table cannot be pasted successfully due to it does not exist.

**Actual Experience:**

1. The attached table can be pasted successfully.
2. The pasted table is empty.
![image](https://user-images.githubusercontent.com/34729022/64161565-710f5500-ce70-11e9-8678-637a070c6653.png)

**Comment by craxal** [comment]
I'm gonna say won't fix on this. This is similar to receiving a SAS URL to a table that doesn't exist. You can still attach regardless of whether the table is there or not. @MRayermannMSFT or @jinglouMSFT, do you agree?
