### ISSUE TITLE
Warning message for rehydration time in "Update Access Tier" dialog

### ISSUE THREAD

**Issue by whiskeyjay** [microsoft/AzureStorageExplorer#177]
Version: 1.1.0
Platform: Windows
Architecture: ia32
Build Number: 20180507.1
Commit: bcc8990d

This is a feature request.

In the said dialog, if the user selected Archive, the dialog should show some key info regarding this tier:

![image](https://user-images.githubusercontent.com/15821566/40024419-11386e88-5783-11e8-9c3f-7fbb13de61c4.png)

**Comment by MRayermannMSFT** [comment]
Probably better to do it as an info rather than a warning...maybe check with Catherine to get her opinion. Not sure if this falls under warning: https://docs.microsoft.com/en-us/windows/desktop/uxguide/mess-warn

**Comment by v-xuanzh** [comment]
This issue has been fixed on the real singed build 20190625.3. So close it.
