### ISSUE TITLE
Show an incorrect notification message for one empty blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1773]
**Storage Explorer Version:** 1.10.0
**Platform/OS:** Windows 10
**Architecture:** x64
**Commit:** f06deb7a6
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand a storage account -> Blob Containers.
2. Create a new blob container -> Observe the notification message on the left bottom corner of the editor.

**Expect Experience:**
Show 'Showing 0 to 0 of 0 **items**'.

**Actual Experience:**
Show 'Showing 0 to 0 of 0 **enetries**'.

**More Info:**
This issue also reproduces for one empty file share.

**Comment by craxal** [comment]
Duplicate of #1697.
