### ISSUE TITLE
Remove the option 'Disable soft Delete' on the prompt dialog after selecting 'Enable Soft Delete'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1775]
**Storage Explorer Version:** 1.10.0
**Platform/OS:** Windows 10
**Architecture:** x64
**Commit:** f06deb7a6
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand a storage account -> Blob Containers. (Make sure the soft delete is disabled).
2. Select one blob container and upload one new file.
3. Right click the uploaded blob then select delete.
4. Click 'Enable Soft Delete' button then check the prompt dailog.

**Expect Experience:**
No the option 'Disable soft Delete' shows.
![image](https://user-images.githubusercontent.com/41351993/64238692-7a142b00-cf31-11e9-811f-bf9464136649.png)

**Actual Experience:**
The option 'Disable soft Delete' shows after selecting 'Enable Soft Delete'.
![image](https://user-images.githubusercontent.com/41351993/64236403-e9d3e700-cf2c-11e9-9056-ebe9c254a3b9.png)

**Comment by JasonYeMSFT** [comment]
The sever may need some time to propagate the new delete policy across its machines. During this time, it may give us incorrect delete policy values upon our request. This behavior is expected and we decided to always show what the server returns by design.
