### ISSUE TITLE
[loc][Query][AzureStorageExplorer] Localizability of 0; "ButtonClearCompleted"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/AzureStorageExplorer#1778]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help, please?
Thanks!

**Source:**
Clear completed

**File Name:**
loc\en\src\Standalone\resources\Activities.json

**Resource ID:**
0; "ImportModuleCompletionsLabel"

**Query:**
Please confirm this means 'To clear the completed items' and NOT 'The clear operation is completed'.

Also applies to ResourceID 0; "ButtonClearSuccessful"

**Comment by JasonYeMSFT** [comment]
Yes and yes, it will clear the completed/successful items once the button is clicked.
