### ISSUE TITLE
 [loc][Query][AzureStorageExplorer] Localizability of 0; "ErrorNoMoreCacheData"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/AzureStorageExplorer#1779]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help, please?
Thanks!

**Source:**
The cache should have more data, but does not. Remaining: %s, file: %s

**FileName**:**
loc\en\src\Standalone\resources\Activities.json

**Resource ID:**
0; "ErrorNoMoreCacheData"

Query:
Does the last part "file: %s" refer to a single (1) file? And %s = file name?

**Comment by craxal** [comment]
@PDostalek Yes, the first placeholder is a number, and the second placeholder is a file path. For example, "The cache should have more data, but it does not. Remaining: 6, file: /path/to/file".

Do you have everything you need for translation now?

**Comment by PDostalek** [comment]
THanks for clarification

**Comment by PDostalek** [comment]
What is meant by the part, "but does not".
Does this mean that "the cache does not have enough data"?
Could you clarify this as well ? @craxal

**Comment by craxal** [comment]
@PDostalek No, it means the cache has less data than expected. Don't worry too much about this string. It's part of an old code path that that we're phasing out, and I've never seen it pop up.

**Comment by PDostalek** [comment]
THanks quick reply .
