### ISSUE TITLE
 [loc][Query][AzureStorageExplorer] Localizability of 0; "AttachWithRbacAccountPrompt"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/AzureStorageExplorer#1780]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help, please?
Thanks!

Source:
Select the Azure Account which has access to the Storage resource you want to attach and the tenant that the resource is in.

File Name:
loc\en\src\Standalone\resources\ConnectDialog.json

Resource ID:
0; "AttachWithRbacAccountPrompt"

Query:
Please clarify what 'the tenant that the resource is in' is related to:

1. Select the Azure Account ... and (select) the tenant...
2. Select the Azure Account which has access to the Storage resource ... and (which has access to) the tenant...

**Comment by craxal** [comment]
@PDostalek A tenant is a broad group of things in Azure. The tenant contains a resource that the user wants to connect to. The tenant also contains permissions that grant various security entities access to the resources it contains.

The "account" refers to a list of items representing Azure accounts that the user has signed in to through Storage Explorer. The "tenant" refers to a list of dropdown items representing Azure tenants wherein the selected account has permissions.

**Comment by PDostalek** [comment]
excellent, thanks

**Comment by PDostalek** [comment]
In THIS sentence, does the user have to select ONLY the Azure Account, OR to select the Azure Account + the Tenant ?

**Comment by craxal** [comment]
@PDostalek The sentence instructs the user that they should select _both_ an account and a tenant.
