### ISSUE TITLE
[loc][Query][AzureStorageExplorer] Localizability of 0; "MessageEntitiesCompleted"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/AzureStorageExplorer#1781]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help, please?
Thanks!

Source:
%s entities completed.

File Name:
loc\en\src\Standalone\resources\Activities.json

Resource ID:
0; "MessageEntitiesCompleted"

Query:
Please, define what will be placeholder replaced by.

**Comment by JasonYeMSFT** [comment]
The placeholder is supposed to be a number (e.g. 125). The string is used to convey the operation has completed on how may entities (e.g. copy).
