### ISSUE TITLE
[loc][Query][AzureStorageExplorer] Localizability of 0; "LabelAriaDeleteEntityButton"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/AzureStorageExplorer#1782]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Can you help, please?
Thanks!

Source:
%s property delete entity

File Name:
loc\en\src\Standalone\resources\EntityEditorDialog.json

Resource ID:
0; "LabelAriaDeleteEntityButton"

Query:
1. Would you please confirm if "delete" acts as a noun or a verb here? In other words, is it "deletion of entity" or "an entity named delete"?

2) Please, confirm whether placeholder will be replaced by the property and sentence means: delete entity from property %s.
Clarify placeholder also for these entries:
%s property edit entity 0; "LabelAriaEditEntityButton"
%s property name 0; "LabelAriaPropertyName"
%s property type 0; "LabelAriaPropertyType"
%s property value 0; "LabelAriaPropertyValue"
Also applies to ResourceID 0; "ButtonClearSuccessful"

**Comment by craxal** [comment]
For `LabelAriaDeleteEntityButton`, "Delete" is a verb here.

The placeholders for the ARIA labels here are for an ID of sorts. If a user is editing a table entity (row), These labels help the user know which property in that entity/row is being edited. For example, if I'm editing the "Timestamp" property, the labels should read thus:
- `LabelAriaEditEntityButton`: "Timestamp property, edit entity" (for a button)
- `LabelAriaPropertyName`: "Timestamp property, name" (for an input field)
- `LabelAriaPropertyType`: "Timestamp property, type" (for an dropdown)
- `LabelAriaPropertyValue`: "Timestamp property, value" (for an input field)

For `ButtonClearSuccessful`, this label a button in the Activity Log that is supposed to remove all activity items that have completed successfully. So "clear successful" could be read as "remove successful activities".

**Comment by PDostalek** [comment]
Superb, thanks
