### ISSUE TITLE
[loc][Query][AzureStorageExplorer] Localizability of 0; "MessageNumCanceled"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/AzureStorageExplorer#1783]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help, please?
Thanks!

Source:
%d canceled

File Name:
loc\en\src\Standalone\resources\Activities.json

Resource ID:
0; "MessageNumCanceled"

Query:
Please, define placeholder and whether it will appear with similar strings (%d conflict, %d errors...) for consistent translation.
Also for string
%d completed 0; "MessageNumCompleted"

**Comment by craxal** [comment]
@PDostalek Yes, "%d canceled" is just like the other strings. It will be a number, such as "2 canceled, 3 succeeded".

**Comment by PDostalek** [comment]
Thanks
