### ISSUE TITLE
[loc][Query][AzureStorageExplorer] Localizability of 0; "MessageRetryWillOccur"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/AzureStorageExplorer#1784]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help, please?
Thanks!

Source:
Retry #%s will occur at %s

File Name:
loc\en\src\Standalone\resources\Activities.json

Resource ID:
0; "MessageRetryWillOccur"

Query:
Please, define what will be placeholders replaced by.

**Comment by craxal** [comment]
@PDostalek The first placeholder is a number. The second is a time. For example, "Retry # 2 will occur at 11:15 AM".

**Comment by craxal** [comment]
@PDostalek Do you have everything you need for translation now?

**Comment by PDostalek** [comment]
ok, thanks
