### ISSUE TITLE
[loc][Query][AzureStorageExplorer] Localizability of 0; "MessageRetryWillOccur"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/AzureStorageExplorer#1787]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help, please?
Thanks!

Source:
Retry #%s will occur at %s

File Name:
loc\en\src\Standalone\resources\Activities.json

Resource ID:
0; "MessageRetryWillOccur"

Query:
Would you please clarify the placeholder? Is it a time or location?

**Comment by craxal** [comment]
The first string is a retry attempt number. The second is time.
