### ISSUE TITLE
[loc][Query][AzureStorageExplorer] Localizability of 0; "TypeOfBlobToUpload"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/AzureStorageExplorer#1788]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help, please?
Thanks!

Source:
, the type of blob you want to upload as

File Name:
loc\en\src\components\se-az-copy-extension\resources\UploadBlobsDlg.json

Resource ID:
0; "TypeOfBlobToUpload"

Query:
Would you please give me the full visibility into this truncated string? Its preceding and following strings are needed for appropriate translation.

**Comment by craxal** [comment]
We are reworking this string. Please wait for an update.

**Comment by craxal** [comment]
@PDostalek Please look over UploadBlobsDlg.json for translation again. The strings have been altered for easier translation.

**Comment by janbaltus** [comment]
similar to **https://github.com/microsoft/AzureStorageExplorer/issues/1714**

**Comment by craxal** [comment]
@PDostalek Do you have everything you need for translation now?
