### ISSUE TITLE
Keep uploading when uploading an non-existing directory to file share

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#179]
**Storage Explorer Version**: 1.1.0

**Platform**: Windows/Linux

**Architecture**: x64

**Build Number**: 20180510.2

**Commit**: d271505a

**Regression From**: Not a regression

#### Steps to Reproduce: ####

1. Launch Storage Explorer and expand Storage Accounts.
2. Open one file share and upload an non-existing directory to it.

#### Expected Experience: ####
 An error displays in Activities Panel like 'The directory doesn't exist'.

#### Actual Experience: ####
Keep uploading more than 20mins.
![deleting](https://user-images.githubusercontent.com/34729022/40041522-cb249c4c-580d-11e8-93d4-3e50afb821a8.png)

**Comment by MRayermannMSFT** [comment]
@v-xuanzh what do you mean by non-existing directory?

**Comment by v-xuanzh** [comment]
Yes. You can use the following steps:
a. Click on Upload
b. Select a directory
c. Before clicking Upload, go to Finder/Windows Explorer and delete the directory you selected
d. Click upload

**Comment by MRayermannMSFT** [comment]
Ok, that's what we thought you meant. Just needed to make sure. We're going to close this as won't fix for now.
