### ISSUE TITLE
Azure Storage Explorer takes minutes to find specific Blob Storage Container

### ISSUE THREAD

**Issue by AlexUrbanAc** [microsoft/AzureStorageExplorer#1790]
So, I am trying to navigate a slightly bigger blob storage using Azure Storage explorer. The storage has about 100k Blob Storage Containers (guesstimate) with godknows how many objects (no one ever counted).

I now I want to navigate to the blob storage container named "XYZ" to check a specific blob.
The only way of navigation I see in the UI is to right click "Blob Containers" -> "Search From Here", enter "XYZ" and press Enter.

The full search box content then is "/Local & Attached/Storage Accounts/MyStorageConnectionString/Blob Containers/XYZ" and the progress wheel is spinning. The search has been running without result for ten minutes before I had to abort it because I have to get other work done.

Am I right that there is no way to select a specific blob storage without search, and that the search is really taking the prohibitively long time of 10 minutes or more for 100k blob storage containers?

Once I am in a specific container the search by blob name is comparatively fast, but for this you have to go to a specific Blob Container first. For me, writing code to modify a specific blob feels faster than using Azure Storage Explorer.

The version is 1.9.0 ia32 20190701.8 commit 38471464; account access is solely through a connection string, if that matters.

**Comment by JasonYeMSFT** [comment]
@AlexUrbanAc ,

Sorry about our search performance. Currently, search is the only way to filter out specific blob containers without manually expanding storage accounts. If there are many blob containers under your current active subscriptions, the search will take a long time to finish. However, if the result under the Local & Attached node is the blob container you want, you can just open it from there and abort the search. Or you can find the most frequently used blob containers once and add them to Quick Access, the next time you can just go to Quick Access to open the blob container and search will find it in Quick Access quicker.

**Comment by AlexUrbanAc** [comment]
Hello Jason,

the problem is that there is no "most frequently used blob container". Every other week I will be debugging different problems in different containers. I am not sure I understand what "result under the Local & Attached" you mean. If I expand the "Blob containers" the individual containers are sorted lexicographically, so the entries shown are "000", "001", "002", "003" ..., and to get to "XYZ" I would have to click "Show more" about 500 times.

Is it planned to improve the search performance and/or enable direct access to a Table or Blob Container by name in future versions?

Kind regards,

Alex

**Comment by scabana** [comment]
I would have expected the "Search for resources" to search by prefix only. It would use the search by prefix apis and be super quick. It would work with containers and tables for sure.

**Comment by c-s-n** [comment]
As indicated above, also the Table search suffers from this significant performance issue. For certain storage structures with thousands of resources, this makes the Azure Storage Explorer pretty much unusable.
The search APIs used by the Azure Portal for this storage account return almost instantly; so I'd say this should be the expected behavior.

**Comment by MRayermannMSFT** [comment]
We'll handle this while addressing #75
