### ISSUE TITLE
 [loc][Query][AzureStorageExplorer] Localizability of 0; "TelemetryCollection"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/AzureStorageExplorer#1791]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help, please?
Thanks!

Source:
Telemetry collected includes

File Name:
loc\en\src\Standalone\resources\TelemetryDialog.json

Resource ID:
0; "TelemetryCollection"

Query:
Would you please advise what will precede and follow this truncated string? Also, we understood the structure of this string as [Collected telemetry includes] where "collected" modifies "Telemetry."

**Comment by craxal** [comment]
Yes, I think that's right. The context of this string is:

> Telemetry collected includes
> - Information about your software and hardware configurations.
> - Information on how you use Microsoft software and services to identify trends and usage patterns.

**Comment by PDostalek** [comment]
Thank you
