### ISSUE TITLE
[loc][Query][AzureStorageExplorer] Localizability of 0; "LabelTreeViewButton"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/AzureStorageExplorer#1792]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help, please?
Thanks!

Source:
Toggle Explorer

File Name:
loc\en\src\Standalone\resources\Shell.json

Resource ID:
0; "LabelTreeViewButton"

Query:
Would you please advise if "Explorer" stands for "Storage Explorer" and therefore not translatable? Or is it used as a generic term?

**Comment by craxal** [comment]
The "Explorer" in "Toggle Explorer" is equivalent to the one defined by Host.json > `CloudExplorer.Appearance.Explorer.Name`. It is not the same as "Storage Explorer".

**Comment by PDostalek** [comment]
Therefore is explorer translatable @craxal ?

**Comment by craxal** [comment]
Yes, it's translatable.

**Comment by PDostalek** [comment]
thanks!
