### ISSUE TITLE
The value of MD5 is missed for one uploaded file

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1795]
**Storage Explorer Version:** 1.10.0
**Build:** 20190905.11
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one account -> File Shares.
2. Open one file share -> Upload one local file to it.
3. Check the MD5 of the uploaded file on Properties dialog.

**Expect Experience:**

The value of MD5 shows well.

**Actual Experience:**

The value of MD5 is missed.
![image](https://user-images.githubusercontent.com/34729022/64331835-1ad41a80-d006-11e9-9d03-3b4a1bd63735.png)

**More info:**

No MD5 property shows for one ADLS Gen2 blob on Properties dialog.

**Comment by v-limu** [comment]
Verified on build [20200216.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3477731&view=logs). This issue has been fixed. So we close it.
![image](https://user-images.githubusercontent.com/54055206/74635790-b070fa00-51a1-11ea-928e-d5d660e9a65d.png)

**Comment by RobbBrock** [comment]
I think whatever code was changed to fix this issue has caused a regression bug by loosing the ETag property in the System Properties view.

**Comment by JasonYeMSFT** [comment]
@RobbBrock are you using ETags a lot? As a work around for now, you can view the ETags on [Portal](https://portal.azure.com/). If you still prefer using Storage Explorer to view the properties, let us know if you want a hot fix for you.

If no immediate action is required, we will track this regression in #2947 and make a fix in our next release.

**Comment by JasonYeMSFT** [comment]
Since #2940 is already opened. Let's track it there.
