### ISSUE TITLE
Add an icon to 'Open New Tab' on Actions panel for one blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1796]
**Storage Explorer Version:** 1.10.0
**Build:** [20190905.11](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3020665)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand a storage account -> Blob Containers.
2. Select one blob container and observe it actions on 'Actions' panel.

**Expect Experience:**
An icon shows for action 'Open New Tab'.

**Actual Experience:**
No icon shows for action 'Open New Tab'.
![image](https://user-images.githubusercontent.com/41351993/64330809-376f5300-d004-11e9-9d3a-9eab2c63e765.png)

**More Info:**
This issue also reprodueces for one file share/ queue/ table.

**Comment by MRayermannMSFT** [comment]
Won't fix.
