### ISSUE TITLE
It allows to input 'e/E' to Max Age box on the Add CORS Rule dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1797]
**Storage Explorer Version:** 1.10.0
**Build:** [20190905.11](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3020665)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one Non-ADLS Gen2 storage account.
2. Right click Blob Containers node then select 'Configure CORS Settings...'.
3. Click 'Add' to add an cors rule and input Mac Age like:123e.

**Expect Experience:**
 The inputed 'e' is invalid. 

**Actual Experience:**
It allows to input e and the 'Save' button is enabled.

**More Info:**
1. An error occurs after clicking Save on the CORS Settings dialog.
![image](https://user-images.githubusercontent.com/41351993/64332155-a3eb5180-d006-11e9-9357-4b220eb08755.png)
2. The value of Max Age which ended with e/E still keeps when trying to continue to add a new cors rule.
![image](https://user-images.githubusercontent.com/41351993/64332192-b1084080-d006-11e9-9835-ea925ace4ce8.png)

**Comment by craxal** [comment]
Won't fix. Server catches the error properly, and it's highly unlikely someone is going to want to use a scientific notation for number here.
