### ISSUE TITLE
Nothing happens after clicking 'Create Disk' button

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#1798]
**Storage Explorer Version**: 1.10.0
**Build:** 20190905.11
**Branch:** master
**Platform/OS:** Windows 10/Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand 'Disks' -> Open one resource group.
2. Click 'Create Disk' button on the toolbar.

**Expect Experience:**
The 'Create Disk' dialog displays.

**Actual Experience:**
Nothing happens.

**More Info:**
This issue also reproduces for 'Paste' button.

**Comment by MRayermannMSFT** [comment]
Fix merged into master
