### ISSUE TITLE
 [loc][Query][AzureStorageExplorer] Localizability of 0; "MessageTransferProgress"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/AzureStorageExplorer#1799]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help, please?
Thanks!

Source:
%s of %s (speed: %s, average: %s)

File Name:
loc\en\src\Standalone\resources\Activities.json

Resource ID:
0; "MessageTransferProgress"

Query:
What is average here? Is it average speed value?

**Comment by craxal** [comment]
@PDostalek Yes, average is a transfer speed.

**Comment by PDostalek** [comment]
Ok, thanks
