### ISSUE TITLE
Azurite fail to delete a table

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#180]
**Storage Explorer Version**: 1.1.0

**Platform**: Windows/Linux/Mac

**Architecture**: x64

**Build Number**: 20180510.2

**Commit**: d271505a

**Regression From**: Not a regression

#### Steps to Reproduce: ####

1. Install Azurite and launch Storage Explorer.
2. Expand 'Development' node.
3. Create a new table and delete it.

#### Expected Experience: ####
The created table can be deleted successfully.

#### Actual Experience: ####
Pop up an error dialog.
![delete_table](https://user-images.githubusercontent.com/34729022/40041714-7f067a3c-580e-11e8-839f-9d1a4f713451.png)

**Comment by craxal** [comment]
This is an Azurite bug, not ours. See Azure/Azurite#20.
