### ISSUE TITLE
[loc][Query][AzureStorageExplorer] Localizability of 0; "ErrorPropertyInvalidInt64"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/AzureStorageExplorer#1800]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Can you help, please?
Thanks!

Source:
Enter a signed 64-bit integer, in the range (-2^53 - 1, 2^53 - 1).

File Name:
loc\en\src\Standalone\resources\Azure.json

Resource ID:
0; "ErrorPropertyInvalidInt64"

Query:
We think the left border of the range should be either -2^53 + 1 (plus, not minus), or just -2^53. Please double-check.

**Comment by craxal** [comment]
I'm not finding any documentation that gives these specific numbers. There may me a legacy in-app reason for these numbers (possibly due to JavaScript being unable to express all 64-bit integers). Either way, I'm hesitant to change this string for now.
