### ISSUE TITLE
[loc][Query][AzureStorageExplorer] Localizability of 0; "MessageBlobDeleteQueued"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/AzureStorageExplorer#1801]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Can you help, please?
Thanks!

Source:
Queued delete blobs from '%s'.

File Name:
loc\en\src\components\se-adls2-extension\resources\FileSystemEditor.json

Resource ID:
0; "MessageBlobDeleteQueued"

Query:
Unclear string. Could you please paraphrase it? Thanks!

**Comment by craxal** [comment]
The message indicates that A number of requests have been queued to delete from a blob container. For example, "Queue delete blobs from 'my-blob-container'" means that the application is preparing to delete blobs from the blob container named "my-blob-container".
