### ISSUE TITLE
 [loc][Query][AzureStorageExplorer] Localizability of  0; "MessageBlobDeleteCanceled"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/AzureStorageExplorer#1802]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Can you help, please?
Thanks!

Source:
Canceled deleting %1$s '%2$s': %3$s completed

File Name:
loc\en\src\components\se-adls2-extension\resources\FileSystemActivities.json

Resource ID:
0; "MessageBlobDeleteCanceled"

Query:
What will "%1$s" "%2$s" "%3$s" be?
Thanks.

**Comment by craxal** [comment]
@PDostalek The first placeholder is a number. The second placeholder is a path. The third placeholder is another number. Possibly a typo, but should read as "Canceled deleting 3 items from 'path/to/cloud': 2 completed".

**Comment by PDostalek** [comment]
ok

**Comment by PDostalek** [comment]
However, from your example sentence, the first placeholder should be replaced by the phrase "3 items from." Will this string be updated later? @craxal

**Comment by craxal** [comment]
Yes, but we're out of time, so moving to 1.13.0.

**Comment by PDostalek** [comment]
@craxal as I can see , string is still same : Canceled deleting %1$s '%2$s': %3$s completed

**Comment by craxal** [comment]
@PDostalek As mentioned above, we're moving this to 1.13.0.

**Comment by PDostalek** [comment]
still active, please check @craxal

**Comment by craxal** [comment]
@PDostalek We merged a fix as of 21 Feb. Moved this issue to "Translating".
