### ISSUE TITLE
[loc][Query][AzureStorageExplorer] Localizability of 0; "MessageBlobDeleting"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/AzureStorageExplorer#1803]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Can you help, please?
Thanks!

Source:
Deleting %1$s blobs from '%2$s': %3$s completed

File Name:
loc\en\src\components\se-adls2-extension\resources\FileSystemActivities.json

Resource ID:
0; "MessageBlobDeleting"

Query:
Would you please give more info about placeholders?
Thanks.

**Comment by craxal** [comment]
@PDostalek The first placeholder is a number. The second placeholder is the name of the blob container. The third placeholder is another number. For example "Deleting 3 blobs from 'my-blob-container': 2 completed".

**Comment by PDostalek** [comment]
Ok, thanks
