### ISSUE TITLE
 [loc][Query][AzureStorageExplorer] Localizability of 0; "AriaPrincipleEditingDescription"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/AzureStorageExplorer#1804]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Can you help, please?
Thanks!

Source:
type the UPN or OID of the desired %1$s then press enter to save

File Name:
loc\en\src\components\se-adls2-extension\resources\ManagePosixAcl.json

Resource ID:
0; "AriaPrincipleEditingDescription"

Query:
What are the options for the placeholder? Now translated as "type the UPN or OID of the desired element of type %1$s", please confirm.

**Comment by craxal** [comment]
The placeholder is either "Owner" (`LabelOwner`) or "Owning Group" (`LabelOwningGroup`). For example "type the UPN of OID of the desired owner then press enter to save".

**Comment by PDostalek** [comment]
Many thanks
