### ISSUE TITLE
 [loc][Query][AzureStorageExplorer] Localizability of 0; "AriaPrincipleItem"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/AzureStorageExplorer#1805]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Can you help, please?
Thanks!

Source:
%1$s entity, %2$s

File Name:
loc\en\src\components\se-adls2-extension\resources\ManagePosixAcl.json

Resource ID:
0; "AriaPrincipleItem"

Query:
Please clarify the placeholders.

**Comment by craxal** [comment]
See #1806 for similar explanation.

**Comment by PDostalek** [comment]
Thx
