### ISSUE TITLE
 [loc][Query][AzureStorageExplorer] Localizability of 0; "AriaPrincipleItemWithStatus"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/AzureStorageExplorer#1806]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Can you help, please?
Thanks!

Source:
%1$s entity, %2$s is %3$s

File Name:
loc\en\src\components\se-adls2-extension\resources\ManagePosixAcl.json

Resource ID:
0; "AriaPrincipleItemWithStatus"

Query:
Please clarify the placeholders.

**Comment by craxal** [comment]
The first placeholder is the entity type: "group", "user", "mask", or "other". The second placeholder is an ID, and the third is either "owner" (`LabelOwner`) or "Owning Group" (`LabelOwnerGroup`)

**Comment by PDostalek** [comment]
excellent, thanks
