### ISSUE TITLE
 [loc][Query][AzureStorageExplorer] Localizability of 0; "PromptSelectionDisabledDiscoveryNotFinished"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/AzureStorageExplorer#1807]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Can you help, please?
Thanks!

Source:
The following is a list of failed and skipped transfers. Because discovery did not complete though, this is only a partial list and you can only retry the operation.

File Name:
loc\en\src\components\se-az-copy-extension\resources\RetryTransfersDlg.json

Resource ID:
0; "PromptSelectionDisabledDiscoveryNotFinished"

Query:
Is there a possibility that this means "failed transfers and skipped transfers"?
Currently translated as "trasfers that failed and then was skipped"

**Comment by craxal** [comment]
@PDostalek "Failed transfers and skipped transfers" is the proper interpretation.

**Comment by PDostalek** [comment]
Clarified, thanks
