### ISSUE TITLE
[loc][Query][AzureStorageExplorer] Localizability of 0; "MessageBlobActionFailed"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/AzureStorageExplorer#1808]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Can you help, please?
Thanks!

Source:
%1$s failed (expand for more)

File Name:
loc\en\src\components\se-adls2-extension\resources\FileSystemActivities.json

Resource ID:
0; "MessageBlobActionFailed"

Query:
Please explain the placeholder. Thanks.

**Comment by craxal** [comment]
@PDostalek The string is similar to other result reporting strings. The placeholder is for a number. For example "3 failed", and in 3 activities failed.

**Comment by PDostalek** [comment]
Thanks for the info
