### ISSUE TITLE
 [loc][Query][AzureStorageExplorer] Localizability of  0; "AriaPrincipleEditing"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/AzureStorageExplorer#1809]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Can you help, please?
Thanks!

Source:
editing, current value %1$s

File Name:
loc\en\src\components\se-adls2-extension\resources\ManagePosixAcl.json

Resource ID:
0; "AriaPrincipleEditing"

Query:
Will this string be concatenated? If so, please explain what it will be preceded by.
In general, is there a reason for strings with ID "AriaPrincipleXXX" to start with lower case? Thanks

**Comment by craxal** [comment]
@PDostalek This string will be preceded by something similar to "input", as in an input text box. For example, "value input editing, current value myvalue".

**Comment by PDostalek** [comment]
Thanks
