### ISSUE TITLE
Charset display under 'Content type' column after uploading development blobs(.txt)

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#181]
**Storage Explorer Version**: 1.1.0

**Platform**: Windows/Linux/Mac

**Architecture**: x64

**Build Number**: 20180510.2

**Commit**: d271505a

**Regression From**: Not a regression

#### Steps to Reproduce: ####

1. Install Azurite and launch Storage Explorer.
2. Create a blob container and upload one blob file(.txt) at least.
3. Check the content type after uploading successfully.

#### Expected Experience: ####
The charset of the blob doesn't display under 'Content type'.

#### Actual Experience: ####
The charset od the blob displays under 'Content type'.
![charset](https://user-images.githubusercontent.com/34729022/40042187-049014dc-5810-11e8-9537-74fa00316bb4.png)

**More info:**
The charset doesn't display after refreshing the container's editor, but it still displays on 'Properties' dialog.

**Comment by MRayermannMSFT** [comment]
Duplicate of #183
