### ISSUE TITLE
 [loc][Query][AzureStorageExplorer] Localizability of  0; "AriaPrincipleEditingBlank"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/AzureStorageExplorer#1810]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Can you help, please?
Thanks!

Source:
editing, current value blank

File Name:
loc\en\src\components\se-adls2-extension\resources\ManagePosixAcl.json

Resource ID:
0; "AriaPrincipleEditingBlank"

Query:
Please explain what this string will be preceded by. Thanks.

**Comment by craxal** [comment]
@PDostalek This string will be preceded by something similar to "input", as in an input text box. For example, "value input editing, current value myvalue".

**Comment by PDostalek** [comment]
Ok, thanks
