### ISSUE TITLE
 [loc][Query][AzureStorageExplorer] Localizability of  0; "MessagePasswordManagerSnap"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/AzureStorageExplorer#1811]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Can you help, please?
Thanks!

Source:
Microsoft Azure Storage Explorer must be connected to the system's password manager service to keep your data safe, but the service plug has not been connected yet. Please run the following command before launching the application again:\n\nsnap connect storage-explorer:password-manager-service :password-manager-service

File Name:
loc\en\src\Standalone\resources\Shell.json

Resource ID:
0; "MessagePasswordManagerSnap"

Query:
Please explain "plug" here. Is it meant to be "plug-in"? Thanks.

**Comment by craxal** [comment]
@PDostalek The "plug" in question here is a plug as described in the [interface documentation for snaps](https://snapcraft.io/docs/interface-management). The Storage Explorer snap defines a password manager "plug" that connects to the system's password manager "socket". Do not interpret as "plug-in".

**Comment by PDostalek** [comment]
THanks for clarification
