### ISSUE TITLE
 [loc][Query][AzureStorageExplorer] Localizability of 0; "AriaPrincipleChange"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/AzureStorageExplorer#1812]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Can you help, please?
Thanks!

Source:
press enter to change the %1$s

File Name:
loc\en\src\components\se-adls2-extension\resources\ManagePosixAcl.json

Resource ID:
0; "AriaPrincipleChange"

Query:
In order to determine gender, please explain the placeholder. Thanks.

**Comment by craxal** [comment]
@PDostalek The placeholder can be either "Owner" (`LabelOwner`) or "Owning Group" (`LabelOwnerGroup`). For example, the string will read as "press enter to change the Owner".

@MRayermannMSFT This looks suspiciously like string synthesis, which we shouldn't be doing for localized strings. If @PDostalek comes back with more questions, we may need to consider refactoring.

**Comment by PDostalek** [comment]
@craxal now it is sufficient, otherwise I let you know. Thanks !
