### ISSUE TITLE
 [loc][Query][AzureStorageExplorer] Localizability of  0; "ErrorInactiveFileDownload"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/AzureStorageExplorer#1813]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Can you help, please?
Thanks!

Source:
Internal error: The specified file download is not currently active.

File Name:
loc\en\src\Standalone\resources\Activities.json

Resource ID:
0; "ErrorInactiveFileDownload"

Query:
Please clarify if "file" is singular or plural here. Thanks.

**Comment by craxal** [comment]
@PDostalek "File" is an adjective here. The subject of the sentence is "file download", that is, a singular file download.

**Comment by PDostalek** [comment]
Perfect, thanks
