### ISSUE TITLE
Update 'No file chosen' to 'No file selected' on Create Disk dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1815]
**Storage Explorer Version:** 1.10.0
**Build:** [20190906.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3023890)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand Disks -> Select a resource group.
2. Click 'Create Disk' -> Observe the description under 'Source VHD' on Create Disk dialog.

**Expect Experience:**
Show 'No file selected'.

**Actual Experience:**
Show 'No file chosen'.
![image](https://user-images.githubusercontent.com/41351993/64411905-d194d100-d0c0-11e9-9637-4f4004d20795.png)

**Comment by MRayermannMSFT** [comment]
Fix checked into master
