### ISSUE TITLE
No warning occurs after using an empty name for the new created folder

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#1817]
**Storage Explorer Version:** 1.10.0
**Build:** 20190906.4
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one ADLS Gen2 account -> Blob Containers.
2. Create a new blob container -> Click 'New Folder' button on the toolbar.
3. Input an empty string in 'New Folder' dialog -> Check the result.

**Expect Experience:**
A warning displays and the 'OK' button is disabled.
![image](https://user-images.githubusercontent.com/54055206/64413509-343b9c00-d0c4-11e9-9383-07d6d6320751.png)

**Actual Experience:**
No warning displays and the 'OK' button is enabled.
![image](https://user-images.githubusercontent.com/54055206/64413222-aeb7ec00-d0c3-11e9-9ff0-96874f42c61f.png)

**Comment by jinglouMSFT** [comment]
Won't fix at this time. API actually allows to create empty name folders. We may at some point to make this work in UI.

**Comment by v-limu** [comment]
But we cannot create empty name folders(Input white spaces directly) with the error 'Failed to create folder '/' ' in Activities. So I reopen this issue.
![image](https://user-images.githubusercontent.com/54055206/64498668-1fd7e900-d2e8-11e9-8e76-5efb771d3dc1.png)

**Comment by jinglouMSFT** [comment]
I know we currently don't work when trying to create folders with empty name from the UI. If users want to create empty name folders, s/he will have to use API to do so.  This is an edge case.  We may consider supporting that in the future.  There is no point to do throw-away work in the UI knowing we at some point will make the UI to work with empty name folders.
