### ISSUE TITLE
The Recent items can be selected as Source VHD on 'Create Disk' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1818]
**Storage Explorer Version:** 1.10.0
**Build:** [20190906.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3023890)
**Branch:** master
**Platform/OS:** Linux Ubuntu 19.04
**Architecture:** x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Make sure used Desktop/Download/Documents ... from your home directory.(Like download one blob to Desktop from Storage Explorer).
2. Expand 'Disk' node -> Open one resource group -> Click 'Create Disk'.
3. On the Create Disk dialog, Try to select one source VHD.
4. On the 'Browse files' dialog, go to 'Recent' tab -> Select 'Desktop'.
![image](https://user-images.githubusercontent.com/34729022/64414711-6ea63880-d0c6-11e9-96b0-880ee87e59c1.png)

**Expect Experience:**

It will go to the Desktop to select one VHD file.

**Actual Experience:**

The Desktop is selected as source VHD on 'Create Disk' dialog.
![image](https://user-images.githubusercontent.com/34729022/64414832-aa410280-d0c6-11e9-8cd4-7d2544b30f37.png)

**Comment by MRayermannMSFT** [comment]
We pass in arguments to the Electron API to open a file picker, and a filter that says only allow user's to select VHDs. If the Ubuntu file picker is letting you pick the Desktop, then that's going to be a bug in Ubuntu.
