### ISSUE TITLE
Miss a slash on the shown path for the opened resource group tab

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1819]
**Storage Explorer Version:** 1.10.0
**Build:** [20190906.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3023890)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand 'Disks' node -> Open one resource group.
2. Hover the mouse to the opened resource group tab.
3. Observe the shown path.

**Expect Experience:**

There shows a slash before the subscription name.

**Actual Experience:** 

Miss a slash before the subscription name.
![image](https://user-images.githubusercontent.com/34729022/64415421-d3ae5e00-d0c7-11e9-8bd5-d8a811ddb69e.png)

**Comment by JasonYeMSFT** [comment]
We won't fix this for 1.10. We actually prefer not having slash at the beginning, so we will remove the slash of other tabs later.
