### ISSUE TITLE
Cannot paste local blobs to regular accounts 

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#182]
**Storage Explorer Version**: 1.1.0

**Platform**: Windows/Linux/Mac

**Architecture**: x64

**Build Number**: 20180510.2

**Commit**: d271505a

**Regression From**: Not a regression

#### Steps to Reproduce: ####

1. Make sure the Storage Emulator is installed and started.
2. Attach to a local emulator -> Expand 'local-1(Key)' -> 'Blob Containers'.
3. Create a new blob container then try to upload a blob file to it.
4. Copy the uploaded blob then paste it to another regular account.
5. Check the result.

#### Expected Experience: ####
The blob can be pasted successfully.

#### Actual Experience: ####
Failed to paste the blob with the below error.
![image](https://user-images.githubusercontent.com/34729022/56799247-67445980-67cd-11e9-9013-cf057f33509e.png)

**More info:**
This issue doesn't reproduce for local tables.

**Comment by MRayermannMSFT** [comment]
@v-xuanzh , can you see if this still repros with 1.4.0? Thanks.

**Comment by v-xuanzh** [comment]
This issue still reproduces in 1.4.0 with the below error.
![error](https://user-images.githubusercontent.com/34729022/43937076-2a5eab72-9c4b-11e8-8d18-6ed8357ed80f.png)

**Comment by v-xianya** [comment]
The Copy/Paste action has been removed for local emulator. So we close it.
