### ISSUE TITLE
Remove … next to the 'Download' action on the context menu for disks

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1820]
**Storage Explorer Version:** 1.10.0
**Build:** [20190906.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3023890)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand 'Disks' node -> Open one resource group.
2. Create a new disk from a local VHD file.
3. Right click the disk then check the context menu.

**Expect Experience:**

No ... shows next to the 'Download' action.

**Actual Experience:**

Show ... next to the 'Download' action.
![image](https://user-images.githubusercontent.com/34729022/64415789-8b437000-d0c8-11e9-84b2-48b1152b9e1f.png)

**Comment by JasonYeMSFT** [comment]
@v-xuanzh ,

We won't fix this for 1.10. Could you please log a bug to remind us to add the ... to the Download button in the context menu for other services? It is more accurate since it brings up a dialog. Thanks.
