### ISSUE TITLE
Show a confused error message when creating a disk from an empty VHD file

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1821]
**Storage Explorer Version:** 1.10.0
**Build:** [20190906.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3023890)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand 'Disks' node -> Open one resource group.
2. Create a new disk from an **empty** VHD file.
3. Check the result.

**Expect Experience:**

Show a clear message on Activities.

**Actual Experience:**

Show a confused error message like below.
![image](https://user-images.githubusercontent.com/34729022/64416078-19b7f180-d0c9-11e9-8bbd-8c0478843ba8.png)

**Comment by MRayermannMSFT** [comment]
This is the current behavior of the service if we try to make a disk of size 0. They're going to support in a future update to the platform.
