### ISSUE TITLE
Allow to view the properties of disks

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1823]
**Storage Explorer Version:** 1.10.0
**Build:** [20190906.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3023890)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Description:**

For one created disk, how to view its properties on the editor？

**Expect Experience:**

There is an action 'Properties...' on the context menu.

**Comment by MRayermannMSFT** [comment]
@v-xuanzh I just looked in the portal at available disk properties, and there doesn't seem to be much more to expose than what we already show in the table view. I'm going to go ahead and close this. If customers request it though then we can reconsider. Thanks for the suggestion tho!
