### ISSUE TITLE
The 'Support ID' is null on About page

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1824]
**Storage Explorer Version:** 1.10.0
**Build:** [20190906.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3023890)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release 1.9.0

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open About page -> Check the 'Support ID'.

**Expect Experience:**

The Support ID is not null.

**Actual Experience:**

The Support ID is null.
![image](https://user-images.githubusercontent.com/34729022/64417234-4bca5300-d0cb-11e9-846f-423654762414.png)

**Comment by v-xianya** [comment]
This issue has been fixed on build 20190909.2.  So we close it.
