### ISSUE TITLE
The ‘Yes’ button isn’t selected on acquire/break lease dialog for one blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1826]
**Storage Explorer Version:** 1.10.0
**Build:** 20190909.2
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release

**Steps to reproduce:**
1. Expand a storage account -> Blob Containers.
2. Seletct one blob container and try to acquire lease.
3. Observe the acquire lease dialog.

**Expect Experience:**
The 'Yes' button is selected.
![image](https://user-images.githubusercontent.com/41351993/64514722-c5f21600-d31d-11e9-880c-95402d68e941.png)

**Actual Experience:**
The 'Yes' button isn't selected.
![image](https://user-images.githubusercontent.com/41351993/64514685-b246af80-d31d-11e9-8d92-dac02259b5db.png)

**Comment by MRayermannMSFT** [comment]
Fix checked into master
