### ISSUE TITLE
The frame of the description is incomplete on Upload VHD dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1827]
**Storage Explorer Version:** 1.10.0
**Build:** 20190909.2
**Branch:** master
**Platform/OS:** macOS High Sierra
**Architecture:** x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand 'Disks' node -> Select one resource group.
2. Click 'Upload' button on the toolbar -> Focus on the description 'Select a VHD...'.
3. Check the result.

**Expect Experience:**
The frame of the description is complete.

**Actual Experience:**
The frame of the description is incomplete.
![image](https://user-images.githubusercontent.com/41351993/64515660-90e6c300-d31f-11e9-85ff-6894b3a95b24.png)

**More Info:**
1. This issue also reproduces on **Upload to Blob Container dialog** with AzCopy checked.
2. This issue also reproduces on **Manage Access dialog** for one ADLS Gen2 blob container.

**Comment by v-xianya** [comment]
Verified this issue on build master/[20200512.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3719948&view=results). 
1. This issue doesn't reproduce in 'Upload VHD' dialog.
2. This issue reproduces in 'Manage Access' dialog.
![image](https://user-images.githubusercontent.com/41351993/81646708-4a250c00-945e-11ea-8a21-652e75bfc673.png)

**Comment by MRayermannMSFT** [comment]
No longer repros.
