### ISSUE TITLE
Fail to paste a disk to other resource groups

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1829]
**Storage Explorer Version:** 1.10.0
**Build:** 20190909.2
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand 'Disks' node -> Open one resource group.
2. Upload a VHD file to create a new disk.
3. Copy the created disk -> Paste it to another resource group.
4. Check the result.

**Expect Experience:**

The copied disk can be pasted successfully.

**Actual Experience:**

Fail to paste the copied disk with the below error.
![image](https://user-images.githubusercontent.com/34729022/64518718-47997200-d325-11e9-878d-428e628a63a7.png)

**Comment by MRayermannMSFT** [comment]
Fix checked into master. We need to use azcopy for cross region copying.
