### ISSUE TITLE
Storage Explorer crashes when searching one resource directly

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1830]
**Storage Explorer Version:** 1.10.0
**Build:** 20190909.2
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release

**Steps to reproduce:**
1. Launch Storage Explorer -> Input a resource name like 'adlsblob' on the Search box.
![image](https://user-images.githubusercontent.com/34729022/64518996-e02ff200-d325-11e9-8c6e-7ccc689fa71f.png)
2. Wait a moment and check the result.

**Expect Experience:**

The searched resources show well on the result.

**Actual Experience:**

Storage Explorer crashes.
![image](https://user-images.githubusercontent.com/34729022/64518962-cdb5b880-d325-11e9-8e76-21d8ee3bc659.png)

**Comment by southpolesteve** [comment]
Can you provide the full stack trace? The line numbers are cut off

**Comment by MRayermannMSFT** [comment]
Fix checked into master
