### ISSUE TITLE
Update 'Theme' to 'Themes' on Settings panel

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1832]
**Storage Explorer Version:** 1.10.0
**Build:** 20190909.2
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Click 'Settings' button.
2.  Open 'Settings' panel -> Click 'Application'.
3. Check the **Theme** under Appearance.

**Expect Experience:**
Display 'Themes'.

**Actual Experience:**
Display 'Theme'.
![image](https://user-images.githubusercontent.com/41351993/64520369-a4e2f280-d328-11e9-8320-1a7e0b2c7ce3.png)

**Comment by JasonYeMSFT** [comment]
I feel that "Theme" is the proper word here since this it is setting one Theme at a time.

**Comment by jinglouMSFT** [comment]
To be consistent with VS Code, Theme here should be singular.

**Comment by MRayermannMSFT** [comment]
Jason changed the Edit menu to be "Theme". Now we are consistent.
