### ISSUE TITLE
Upload of Files to Local Storage Emulator Fails

### ISSUE THREAD

**Issue by brianmrush** [microsoft/AzureStorageExplorer#1833]
**Storage Explorer Version**: version 1.9.0
**Build Number**: 20190701,8
**Platform/OS**: 
**Architecture**: x64
**Regression From**:  

## Bug Description ##
When trying to upload a file using Azure Storage explorer to the local attached emulator I am receiving the following error Group upload failed

{
  "name": "StorageError",
  "message": "Server encountered an internal error. Please try again after some time.\nRequestId:61080b4b-7469-47f2-91e9-3c862ea3fa83\nTime:2019-09-09T12:33:45.4125249Z",
  "stack": "StorageError: Server encountered an internal error. Please try again after some time.\nRequestId:61080b4b-7469-47f2-91e9-3c862ea3fa83\nTime:2019-09-09T12:33:45.4125249Z\n    at Function.StorageServiceClient._normalizeError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:1205:23)\n    at Object.StorageServiceClient._processResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:751:50)\n    at Request.processResponseCallback [as _callback] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:319:37)\n    at Request.self.callback (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1157:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1079:12)",
  "code": "InternalError",
  "statusCode": 500,
  "requestId": "61080b4b-7469-47f2-91e9-3c862ea3fa83"
}

## Steps to Reproduce ##
1 Open storage explored
2,  Attache storage account to by selecting attached to a local emulator.
3.  create a container in the local emulator
4, upload a small csv file

## Expected Experience ##
File uploads correctly 

## Actual Experience ##
Fails to upload file

## Additional Context ##
![Screenshot](https://user-images.githubusercontent.com/193558/64531442-8b688900-d2dd-11e9-96a1-0661b941fce0.png)

**Comment by jinglouMSFT** [comment]
Looks like the emulator had some issues.  Which emulator did you use?  Windows Storage Emulator or Azurite?  If Windows Storage Emulator, which version?  I just tried your scenario on my 1.9.0 with Windows Storage Emulator 5.9, worked fine with Azcopy turned on (you can turn it on from the 'Preview' menu or not turned on.

**Comment by brianmrush** [comment]
I used Windows Storage Emulator and the latest version from the site.  Version is 5.10.0.0

**Comment by jinglouMSFT** [comment]
I just verified on 5.10 and still works for me.  Just out of curiosity,  were you uploading the file as page blob, block blob and append blob?  If page blobs, please make sure the content length is a multiple of 512.  The error itself actually comes from the storage emulator.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
