### ISSUE TITLE
Fehlermeldung beim öffnen einer gefüllten Tabelle, dieser Fehler tritt nicht auf wenn ein neues Fenster geöffnet wird.

### ISSUE THREAD

**Issue by Bernd60** [microsoft/AzureStorageExplorer#1834]
**Storage Explorer Version**: < 1.9.0>
**Build Number**: <20190701.8>
**Platform/OS**: <Windows 10 64Bit>
**Architecture**: < ia32 >
**Regression From**:  <>

## Bug Description ##
<Fehlermeldung beim öffnen einer Tabelle>
<"rowB[col]._.toLowerCase is not a function">

## Steps to Reproduce ##
<Fehler tritt nur in einer Tabelle auf alle andere funktionieren>
<Wenn diese Tabelle in einem neuen Fenster geöffnet wird, kommt dieser Fehler nicht>

**Comment by MRayermannMSFT** [comment]
Hey @Bernd60, unfortunately none of us speak or read German. Google translate says you see the error when opening a "filled" table. Can you tell us what filled is, or give us more details in English? Thanks!

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
