### ISSUE TITLE
Collapsible sections CosmosDB for viewing documents

### ISSUE THREAD

**Issue by ChrisAllisonMalta** [microsoft/AzureStorageExplorer#1835]
**Is your feature request related to a problem? Please describe.**
When you have a long document, like x thousand lines its difficult to scroll the whole document to get to the bottom or to a property (field) below a list

**Describe the solution you'd like**
Properties, Lists or Dicts are collapsible, like they are if you query the object via rest in Postman

**Comment by ImrePyhvel** [comment]
Real world documents are not 3 field simpletons. Currently it is really cumbersome to constantly copy paste data to  a proper JSON-aware editor (like Visual Studio) for actually grasping what is being returned.

I'm pretty sure some existing editor components could be integrated, no need to reinvent the wheel.

**Comment by jinglouMSFT** [comment]
CosmosDB support has been removed from Storage Explorer.
