### ISSUE TITLE
The ‘Yes’ button isn’t selected on delete dialog for files under ADLS Gen1 accounts

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#1836]
**Storage Explorer Version:** 1.10.0
**Build:** 20190910.8
**Branch:** master
**Platform/OS:** Windows 10/Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** regression from 1.9.0

**Steps to reproduce:**

1. Select a ADLS Gen1 account.
2. Upload one file to it -> Right click the file -> Select 'Delete' on the content menu.
3. Observe the prompt dialog.

**Expect Experience:**
The 'Yes' button is selected.
![image](https://user-images.githubusercontent.com/54055206/64604634-112b2800-d3f5-11e9-92bf-bd81fa5b7132.png)

**Actual Experience:**
The 'Yes' button isn't selected.
![image](https://user-images.githubusercontent.com/54055206/64603877-a1686d80-d3f3-11e9-8e44-ac54a5add9cc.png)

**Comment by JasonYeMSFT** [comment]
Fix has been merged.
