### ISSUE TITLE
MacOS storage explorer - {   "name": "TypeError",   "message": "Cannot read property 'version' of undefined",   "__zone_symbol__error": {     "originalStack": "Error: Cannot read property 'version' of undefined\n

### ISSUE THREAD

**Issue by JimGrantAmytna** [microsoft/AzureStorageExplorer#1839]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:  

## Bug Description ##
Cannot connect to azure storage

## Additional Context ##
{
  "name": "TypeError",
  "message": "Cannot read property 'version' of undefined",
  "__zone_symbol__error": {
    "originalStack": "Error: Cannot read property 'version' of undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:172:18)\n    at Function.ExceptionSerializer.deserialize (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/se-exception-serializer/dist/ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler.finalizeOperation (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/renderer/marshalers/CloudExplorerProxyMarshaler.js:76:91)\n    at Object.finalizeOperation (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/renderer/marshalers/CloudExplorerProxyMarshaler.js:99:76)\n    at Function.<anonymous> (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/renderer/marshalers/StandardMarshaler.js:28:63)\n    at step (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:136:27)\n    at Object.next (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:117:57)\n    at /Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:110:75\n    at new ZoneAwarePromise (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:551:29)\n    at Object.__awaiter (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:106:16)\n    at JsonPortMarshaler.standardMarshaler.(anonymous function) [as finalizeOperation] (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/renderer/marshalers/StandardMarshaler.js:22:32)\n    at JsonPortMarshaler.onMessage (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/daytona/pluginHost/messaging/marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/daytona/pluginHost/common/event.js:69:30)\n    at Port.processMessage (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/daytona/pluginHost/messaging/communication.js:163:18)",
    "zoneAwareStack": "Error: Cannot read property 'version' of undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:172:18)\n    at Function.ExceptionSerializer.deserialize (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/se-exception-serializer/dist/ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler.finalizeOperation (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/renderer/marshalers/CloudExplorerProxyMarshaler.js:76:91)\n    at Object.finalizeOperation (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/renderer/marshalers/CloudExplorerProxyMarshaler.js:99:76)\n    at Function.<anonymous> (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/renderer/marshalers/StandardMarshaler.js:28:63)\n    at step (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:136:27)\n    at Object.next (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:117:57)\n    at /Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:110:75\n    at new ZoneAwarePromise (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:551:29)\n    at Object.__awaiter (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:106:16)\n    at JsonPortMarshaler.standardMarshaler.(anonymous function) [as finalizeOperation] (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/renderer/marshalers/StandardMarshaler.js:22:32)\n    at JsonPortMarshaler.onMessage (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/daytona/pluginHost/messaging/marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/daytona/pluginHost/common/event.js:69:30)\n    at Port.processMessage (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/daytona/pluginHost/messaging/communication.js:163:18)"
  },
  "stack": "TypeError: Cannot read property 'version' of undefined\n    at Function.CustomConnections.connectionIsV1 (file:///Applications/Microsoft%20Azure%20Storage%20Explorer.app/Contents/Resources/app/out/CloudHub/js/Providers/StorageExplorer/CustomConnections/CustomConnections.js:11:32)\n    at getCustomConnectionAttributes (file:///Applications/Microsoft%20Azure%20Storage%20Explorer.app/Contents/Resources/app/out/CloudHub/js/Common/AzureStorageUtilities.js:204:51)\n    at Object.getRawDataFromAccountCustomConnection (file:///Applications/Microsoft%20Azure%20Storage%20Explorer.app/Contents/Resources/app/out/CloudHub/js/Common/AzureStorageUtilities.js:128:25)\n    at AzureStorageProducer.<anonymous> (file:///Applications/Microsoft%20Azure%20Storage%20Explorer.app/Contents/Resources/app/out/CloudHub/js/Providers/Azure/Producers/AzureStorageProducer.js:549:81)\n    at step (file:///Applications/Microsoft%20Azure%20Storage%20Explorer.app/Contents/Resources/app/out/CloudHub/js/Providers/Azure/Producers/AzureStorageProducer.js:34:23)\n    at Object.next (file:///Applications/Microsoft%20Azure%20Storage%20Explorer.app/Contents/Resources/app/out/CloudHub/js/Providers/Azure/Producers/AzureStorageProducer.js:15:53)\n    at file:///Applications/Microsoft%20Azure%20Storage%20Explorer.app/Contents/Resources/app/out/CloudHub/js/Providers/Azure/Producers/AzureStorageProducer.js:9:71\n    at new Promise (<anonymous>)\n    at __awaiter (file:///Applications/Microsoft%20Azure%20Storage%20Explorer.app/Contents/Resources/app/out/CloudHub/js/Providers/Azure/Producers/AzureStorageProducer.js:5:12)\n    at file:///Applications/Microsoft%20Azure%20Storage%20Explorer.app/Contents/Resources/app/out/CloudHub/js/Providers/Azure/Producers/AzureStorageProducer.js:547:69",
  "originalStack": "Error: Cannot read property 'version' of undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:172:18)\n    at Function.ExceptionSerializer.deserialize (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/se-exception-serializer/dist/ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler.finalizeOperation (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/renderer/marshalers/CloudExplorerProxyMarshaler.js:76:91)\n    at Object.finalizeOperation (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/renderer/marshalers/CloudExplorerProxyMarshaler.js:99:76)\n    at Function.<anonymous> (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/renderer/marshalers/StandardMarshaler.js:28:63)\n    at step (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:136:27)\n    at Object.next (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:117:57)\n    at /Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:110:75\n    at new ZoneAwarePromise (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:551:29)\n    at Object.__awaiter (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:106:16)\n    at JsonPortMarshaler.standardMarshaler.(anonymous function) [as finalizeOperation] (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/renderer/marshalers/StandardMarshaler.js:22:32)\n    at JsonPortMarshaler.onMessage (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/daytona/pluginHost/messaging/marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/daytona/pluginHost/common/event.js:69:30)\n    at Port.processMessage (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/daytona/pluginHost/messaging/communication.js:163:18)",
  "zoneAwareStack": "Error: Cannot read property 'version' of undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:172:18)\n    at Function.ExceptionSerializer.deserialize (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/se-exception-serializer/dist/ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler.finalizeOperation (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/renderer/marshalers/CloudExplorerProxyMarshaler.js:76:91)\n    at Object.finalizeOperation (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/renderer/marshalers/CloudExplorerProxyMarshaler.js:99:76)\n    at Function.<anonymous> (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/renderer/marshalers/StandardMarshaler.js:28:63)\n    at step (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:136:27)\n    at Object.next (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:117:57)\n    at /Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:110:75\n    at new ZoneAwarePromise (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:551:29)\n    at Object.__awaiter (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:106:16)\n    at JsonPortMarshaler.standardMarshaler.(anonymous function) [as finalizeOperation] (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/renderer/marshalers/StandardMarshaler.js:22:32)\n    at JsonPortMarshaler.onMessage (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/daytona/pluginHost/messaging/marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/daytona/pluginHost/common/event.js:69:30)\n    at Port.processMessage (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/daytona/pluginHost/messaging/communication.js:163:18)",
  "__zone_symbol__stack": "TypeError: Cannot read property 'version' of undefined\n    at Function.CustomConnections.connectionIsV1 (file:///Applications/Microsoft%20Azure%20Storage%20Explorer.app/Contents/Resources/app/out/CloudHub/js/Providers/StorageExplorer/CustomConnections/CustomConnections.js:11:32)\n    at getCustomConnectionAttributes (file:///Applications/Microsoft%20Azure%20Storage%20Explorer.app/Contents/Resources/app/out/CloudHub/js/Common/AzureStorageUtilities.js:204:51)\n    at Object.getRawDataFromAccountCustomConnection (file:///Applications/Microsoft%20Azure%20Storage%20Explorer.app/Contents/Resources/app/out/CloudHub/js/Common/AzureStorageUtilities.js:128:25)\n    at AzureStorageProducer.<anonymous> (file:///Applications/Microsoft%20Azure%20Storage%20Explorer.app/Contents/Resources/app/out/CloudHub/js/Providers/Azure/Producers/AzureStorageProducer.js:549:81)\n    at step (file:///Applications/Microsoft%20Azure%20Storage%20Explorer.app/Contents/Resources/app/out/CloudHub/js/Providers/Azure/Producers/AzureStorageProducer.js:34:23)\n    at Object.next (file:///Applications/Microsoft%20Azure%20Storage%20Explorer.app/Contents/Resources/app/out/CloudHub/js/Providers/Azure/Producers/AzureStorageProducer.js:15:53)\n    at file:///Applications/Microsoft%20Azure%20Storage%20Explorer.app/Contents/Resources/app/out/CloudHub/js/Providers/Azure/Producers/AzureStorageProducer.js:9:71\n    at new Promise (<anonymous>)\n    at __awaiter (file:///Applications/Microsoft%20Azure%20Storage%20Explorer.app/Contents/Resources/app/out/CloudHub/js/Providers/Azure/Producers/AzureStorageProducer.js:5:12)\n    at file:///Applications/Microsoft%20Azure%20Storage%20Explorer.app/Contents/Resources/app/out/CloudHub/js/Providers/Azure/Producers/AzureStorageProducer.js:547:69",
  "__zone_symbol__name": "TypeError",
  "__zone_symbol__message": "Cannot read property 'version' of undefined",
  "__zone_symbol__originalStack": "Error: Cannot read property 'version' of undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:172:18)\n    at Function.ExceptionSerializer.deserialize (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/se-exception-serializer/dist/ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler.finalizeOperation (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/renderer/marshalers/CloudExplorerProxyMarshaler.js:76:91)\n    at Object.finalizeOperation (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/renderer/marshalers/CloudExplorerProxyMarshaler.js:99:76)\n    at Function.<anonymous> (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/renderer/marshalers/StandardMarshaler.js:28:63)\n    at step (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:136:27)\n    at Object.next (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:117:57)\n    at /Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:110:75\n    at new ZoneAwarePromise (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:551:29)\n    at Object.__awaiter (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:106:16)\n    at JsonPortMarshaler.standardMarshaler.(anonymous function) [as finalizeOperation] (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/renderer/marshalers/StandardMarshaler.js:22:32)\n    at JsonPortMarshaler.onMessage (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/daytona/pluginHost/messaging/marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/daytona/pluginHost/common/event.js:69:30)\n    at Port.processMessage (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/daytona/pluginHost/messaging/communication.js:163:18)",
  "__zone_symbol__zoneAwareStack": "Error: Cannot read property 'version' of undefined\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:172:18)\n    at Function.ExceptionSerializer.deserialize (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/se-exception-serializer/dist/ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler.finalizeOperation (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/renderer/marshalers/CloudExplorerProxyMarshaler.js:76:91)\n    at Object.finalizeOperation (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/renderer/marshalers/CloudExplorerProxyMarshaler.js:99:76)\n    at Function.<anonymous> (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/renderer/marshalers/StandardMarshaler.js:28:63)\n    at step (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:136:27)\n    at Object.next (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:117:57)\n    at /Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:110:75\n    at new ZoneAwarePromise (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:551:29)\n    at Object.__awaiter (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/tslib/tslib.js:106:16)\n    at JsonPortMarshaler.standardMarshaler.(anonymous function) [as finalizeOperation] (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/renderer/marshalers/StandardMarshaler.js:22:32)\n    at JsonPortMarshaler.onMessage (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/daytona/pluginHost/messaging/marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/daytona/pluginHost/common/event.js:69:30)\n    at Port.processMessage (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/daytona/pluginHost/messaging/communication.js:163:18)"
}

**Comment by JasonYeMSFT** [comment]
Hi @JimGrantAmytna,

It seems you have encountered a similar issue to #1626. We have posted a work around there to get new connections work. It would be great if you can provide us more information to help us diagnose what is causing this problem. Are you using connection string, SAS uri or name&key? Have you ever succeeded in adding any connections before you see this error? Have you used emulator before you see this error?

Thanks.
