### ISSUE TITLE
No value of 'Shared Access Signature' display in 'Properties' window for attached table

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/AzureStorageExplorer#184]
**Storage Explorer Version**: 1.1.0

**Platform**: Windows

**Architecture**: ia32

**Build Number**: 20180510.2

**Commit**: d271505a

**Regression From**: Not a regression

#### Steps to Reproduce: ####

1. Attach one table with SAS.
2. Navigate to '(SAS-Attached Services) > Tables' and check the 'Properties' window of this table.

#### Expected Experience: ####
The value of 'Shared Access Signature' displays well. 

#### Actual Experience: ####
No value of 'Shared Access Signature' displays.
![sas](https://user-images.githubusercontent.com/34729092/40048320-776bdb9c-5821-11e8-9879-08a4be327500.png)
More Info:
This issue doesn't reproduce for tables under attached storage account with SAS.
![sas-account](https://user-images.githubusercontent.com/34729092/40048396-a5282acc-5821-11e8-96d4-19a1d8154a07.png)

**Comment by MRayermannMSFT** [comment]
Will be fixed with custom connections.
