### ISSUE TITLE
Navigate to an unmatched webpage after clicking link 'online release notes' in Release Notes

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1840]
**Storage Explorer Version:** 1.10.0
**Build:** 20190911.4
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Click 'Help' menu -> Select 'View Release Notes'.
3. Click the link '_online release notes_' at the end of the release notes page.
![image](https://user-images.githubusercontent.com/41351993/64690865-01c6e000-d4c4-11e9-8482-7147e51c2ec7.png)
4. Check the result.

**Expect Experience:**
Navigate to a right webpage.

**Actual Experience:**
Navigate to an unmatched webpage.
![image](https://user-images.githubusercontent.com/41351993/64690385-d8598480-d4c2-11e9-9329-131428b3607b.png)

**Comment by JasonYeMSFT** [comment]
This is expected since we haven't published the Release Notes yet. Since we are using forwarding link, it doesn't go with the application and will show the correct page then.
