### ISSUE TITLE
Navigate to an unmatched webpage after clicking link 'getting started guide' 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1841]
**Storage Explorer Version:** 1.10.0
**Build:** 20190911.4
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Click 'Help' menu -> Select 'View Release Notes'.
3. Click the link 'getting started guide' at the end of the third part in release notes page.
4. Check the result.

**Expect Experience:**
Navigate to a right webpage.

**Actual Experience:**
Navigate to an unmatched webpage.
![image](https://user-images.githubusercontent.com/41351993/64690850-f7a4e180-d4c3-11e9-9286-541133540c1c.png)

**More Info:**
In which the link 'getting started guide' located.
![image](https://user-images.githubusercontent.com/41351993/64690887-11debf80-d4c4-11e9-9048-d553228cd321.png)

**Comment by JasonYeMSFT** [comment]
This is expected since we haven't published the Release Notes yet. Since we are using forwarding link, it doesn't go with the application and will show the correct page then.
