### ISSUE TITLE
Show an unmatched icon during creating a database for one Cosmos DB account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1842]
**Storage Explorer Version:** 1.10.0
**Build:** 20190911.4
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1.  Right one CosmosDB account with Graph API.
2.  Select 'Create Database' -> Observe the database icon before it has been created.

**Expect Experience:**
Display one database's icon.

**Actual Experience:**
Disply the same icon with Cosmos DB account.
![image](https://user-images.githubusercontent.com/41351993/64692021-ae09c600-d4c6-11e9-9639-0c28d1d87636.png)

**More Info:**
This issue also reproduces for one Cosmos DB account with MongoDB/DocumentDB API.

**Comment by jinglouMSFT** [comment]
It's pretty minor. I would suggest won't fix.

**Comment by southpolesteve** [comment]
Agreed. Let's close as won't fix. I don't appear to have permissions to do that on this repo
