### ISSUE TITLE
A warning occurs when adding an user using object ID on Manage Access dialog 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1843]
**Storage Explorer Version:** 1.10.0
**Build:** 20190911.4
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release

**Steps to reproduce:**
1. Launch Storage Explore using one mooncake account.
2. Expand a ADLS Gen2 account -> Blob Containers.
3. Create a blob container -> Open its context menu then select 'Mange Access...'.
4. Input an object id then click 'Add' button.
5. Check the result.

**Expect Experience:**
One user can be added successfully.
![image](https://user-images.githubusercontent.com/41351993/64691570-8ebe6900-d4c5-11e9-826e-2af0f6d5b9e1.png)

**Actual Experience:**
A warning occurs after clicking Add button. 
![image](https://user-images.githubusercontent.com/41351993/64691565-8bc37880-d4c5-11e9-880b-6911bae7afa0.png)

**More Info:**
1. This issue also reproduces for Azure Germany accounts.
2. This issue doesn't reproduce for Azure accounts.

**Comment by MRayermannMSFT** [comment]
Fix checked into master. Also, @v-xianya , if you're going to be testing ACLs for sovereign clouds, make sure you're adding things which are actually in the directory for your sovereign cloud account.

To look for example things to add, you can:
- go to the portal for the cloud
- go to azure active directory
- click on either users, groups, or enterprise applications
- use the UPNs or object IDs of any thing that appears after click on those

For example, here's a user in the tenant for our Azure China test account:

![image](https://user-images.githubusercontent.com/21112697/64735062-a2090e80-d49c-11e9-9195-76b6ccf2f4c1.png)
