### ISSUE TITLE
I would expect after clicking on Load More on LHS will keep the focus area around the Load More area

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#1846]
Tested on v1.10.0 RC build 20190911.8
Windows 10

The Load More experience on LHS is a little unexpected.  I happened to have my focus set on one of the resource group nodes on LHS because i was doing something with the disks. Then i moved on to my storage nodes as i wanted to upload a blob, but container i wanted to upload to happened to be in one of the those "Load more" section, so i clicked on "Load more".  This resulted to bring the focus (or the section of the tree being display) back to the resource groups under the Disks.  I thought something went wrong at the first as it was totally unexpected.  Then i realized that my last focus was on the resource group node.  It would be nice if i clicked on Load More, we reset the focus to the first node being added from the Load More action.

**Comment by MRayermannMSFT** [comment]
Fix merged into main for 1.18

**Comment by MRayermannMSFT** [comment]
(due to CE ref update not being done, this is not include in any builds from 2/3, we'll update the CE ref tomorrow)
