### ISSUE TITLE
Line Appears Under Tabs At Certain Zoom Levels

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#1848]
v1.10.0
Windows

At certain zoom levels, an extra line appears underneath the tab list.

![image](https://user-images.githubusercontent.com/10081483/64744832-4a799b80-d4ba-11e9-80c1-112d60f0a016.png)

![image](https://user-images.githubusercontent.com/10081483/64745045-1e124f00-d4bb-11e9-9261-49ecf738b6ff.png)

**Comment by craxal** [comment]
Unable to reproduce. If you can reproduce, please show me!
