### ISSUE TITLE
Fail to see the entire value of 'Shared Access Signature' in 'Properties' window after maximizing the Toggle Explorer

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/AzureStorageExplorer#185]
**Storage Explorer Version**: 1.1.0

**Platform**: Windows

**Architecture**: ia32

**Build Number**: 20180510.2

**Commit**: d271505a

**Regression From**: Not a regression

#### Steps to Reproduce: ####

1. Attach a storage account with SAS.
2. Select one table, then maximize the Toggle Explorer.
3. Check the value of 'Shared Access Signature' message in 'Properties' window.

#### Expected Experience: ####
The value of 'Shared Access Signature' displays well.

#### Actual Experience: ####
Fail to see the value of 'Shared Access Signature' in 'Properties' window.
![actual](https://user-images.githubusercontent.com/34729092/40047954-739ccf72-5820-11e8-981f-a1c5a8a084fb.png)

**Comment by craxal** [comment]
You can use the arrow keys to horizontally scroll the text. You can also copy the text to the clipboard and paste elsewhere.

**Comment by v-dantch** [comment]
Thanks a lot for your update.
