### ISSUE TITLE
Add setting to hide metric tables such as $MetricsCapacityBlob

### ISSUE THREAD

**Issue by zeroskyx** [microsoft/AzureStorageExplorer#1852]
Thanks again for adding the new settings page to Storage Explorer.
It would be great if you could add a setting to hide metric/ system tables that begin with a $ (just like the Azure Portal Storage Explorer does) since for many Tables, there can be dozens of $ tables without real use to the user.

Thanks in advance
-Simon

**Comment by MRayermannMSFT** [comment]
Duplicate of #3 !
