### ISSUE TITLE
Cannot read property 'Azure.Resources' of undefined

### ISSUE THREAD

**Issue by alaendle** [microsoft/AzureStorageExplorer#1853]
**Storage Explorer Version**: 1.10.0
**Build Number**: 20190912.8
**Platform/OS**: Windows 7
**Architecture**: x64
**Regression From**:  1.9.0

## Bug Description ##
While trying to enter a specific folder in our Data Lake Storage Gen1 this error appears; the folder is not opened and the tab representing the data lake storage closes.

## Steps to Reproduce ##
Double click on the folder - works any time; but might be data sensitive - the folder name is
"data/datalake/processed/raw/DataType=Trace/"
My guess is that the '=' might be problematic?

## Expected Experience ##
The folder opens and I'm able to view the content.

## Actual Experience ##
The tab representing the folder structure closes and the mentioned error pops up.

## Additional Context ##
Please let me know if you need further information to track down the problem.

**Comment by caksoylar** [comment]
Also hitting this issue since updating to 1.10.0. It seems to fail on any folder written by Spark DataframeWriter, which includes a few empty/small files with names like `_SUCCESS`, `_started_1987144563411163524`, `_committed_1987144563411163524q`, along with many part files in the form of `part-*.csv.gz` or `part-*.parquet`.

**Comment by philadamson93** [comment]
I am also experiencing this issue with my Data Lake Storage Gen1 after updating to version 1.10.0

**Comment by jinglouMSFT** [comment]
Thank you all for quickly reporting the issue. We are in the process of testing the fix tonight. We will release a hotfix in a day or two the max.  If you are blocked, you can revert back to 1.9.0 which is available under the Releases tab here in the repo while waiting for the 1.10.1 release.  On behalf of the team, we are very sorry for the inconvenience this may have caused you. Our sincere apology for the regression.

**Comment by jinglouMSFT** [comment]
v1.10.1 is now available on the release tab (of this repo) for download now.  It will be also available on http://storageexplorer.com in 6-8 hours from now.  For Linux users who want to install from the snap store, it is also available now.  Thank you for your patience.

**Comment by alaendle** [comment]
Thanks, I can confirm that v1.10.1 fixes this issue.
