### ISSUE TITLE
Entity with more than 252 properties

### ISSUE THREAD

**Issue by evrpires** [microsoft/AzureStorageExplorer#1856]
Hi,

As we know, an individual entity from a table can have **no more than 252 properties** (excluding the mandatory system properties). This is a problem when creating/importing a table with more than 252 columns.

Do you know if Microsoft intends to fix this problem?

Best regards,
Evandro

**Comment by MRayermannMSFT** [comment]
As far as we know, there are no plans to fix this limitation at this time. If getting this fixed is important to you then we suggest opening feedback via the Portal, on the docs, or via a support request.
