### ISSUE TITLE
Storage account name in Update Access Tier dialog is not surrounded by quotes

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1862]
**Storage Explorer Version:** 1.10.0
**Build:** [20190916.5](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3055553)
**Branch:** master
**Platform/OS:** Windows 10/ Centos Linux release_7.6.1810(core)/ macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Right click one StorageV2 account -> Select 'Set Default Access Tier'.
2. Check the description on the 'Update Access Tier' dialog.

**Expect Experience:**

Indicate the storage account in the description on 'Update Access Tier' dialog.
Like 'Which access tier would you like **the account 'myadlsxuanacc'** to have?'

**Actual Experience:**

It doesn't indicate the storage account in the description on 'Update Access Tier' dialog.
Display 'Which access tier would you like **myadlsxuanacc** to have?'
![image](https://user-images.githubusercontent.com/41351993/65034050-dc7d1a80-d978-11e9-9dc7-d420270bbad1.png)

**More Info:**
1. This issue also reproduces for one BlobStorage account.
2. This issue also reproduces for one blob.
![image](https://user-images.githubusercontent.com/41351993/65034230-341b8600-d979-11e9-9b70-80def45adf96.png)

**Comment by janbaltus** [comment]
@craxal Please remove localization label. If source string get updated with quotes localization will update target strings as well

**Comment by MRayermannMSFT** [comment]
Verified as fixed.
