### ISSUE TITLE
Nothing happens when deleting a folder via keyboard under one ADLS Gen1 account

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#1863]
**Storage Explorer Version:** 1.10.0
**Build:**[ 20190916.5](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3055553)
**Platform/OS:** Windows 10/ Centos Linux release_7.6.1810(core)/ macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Open one ADLS Gen1 account -> Create a new folder.
2. Try delete the created folder via keyboard.
3. Check the result.

**Expect Experience:**
The delete dialog pops up.

**Actual Experience:**
Nothing happens.

**More Info:**
This issue also reproduces when using 'Ctrl + V' & 'Ctrl + C'.

**Comment by craxal** [comment]
Let me investigate to make sure it's not a localization bug. If not, I'll transfer to @southpolesteve.

**Comment by jinglouMSFT** [comment]
ADLS Gen1 used a lot of the blob's code, but I don't think it has all the latest fixes we made in blob's accessibility.  Steve doesn't own ADLS Gen1 so please don't assign the bug to him.  The ADLS team strongly recommends users upgrade to ADLS Gen2 as Gen1 is in the process of being deprecated.  ADLS Gen1 eventually will be removed from Storage Explorer at some point.

**Comment by craxal** [comment]
@v-limu Can you verify that delete still works using the mouse?

**Comment by v-limu** [comment]
Hi @craxal It works well when using the mouse to delete.

**Comment by craxal** [comment]
@Jing I don't believe ADLS Gen 1 affects our accessibility grade, does it? If not, and since users can still use the mouse, I propose we don't fix.

**Comment by jinglouMSFT** [comment]
hmm...i actually vote to fix this one. Not necessarily for accessibility, more for productivity.

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
