### ISSUE TITLE
Storage Explorer doesn't open folders in ADLS

### ISSUE THREAD

**Issue by kunalwadhwa** [microsoft/AzureStorageExplorer#1865]
Azure Storage Explorer v1.10.0
Mac OS

I upgraded my storage explorer to v1.10.0 but I cannot access some folders in ADLS. Following is the error:

![image](https://user-images.githubusercontent.com/34522964/65057835-382bb180-d941-11e9-94f7-584d4d23ccb0.png)

All was working fine with the old version i.e. v1.9.0

**Comment by craxal** [comment]
@kunalwadhwa Looks to be a string resource retrieval problem. Can you please provide the exact steps you followed to run into this error? I'm exploring an ADLS account of my own, but I'm not running into it.

**Comment by caksoylar** [comment]
Related: #1853

**Comment by ration** [comment]
This happens with me as well. 

Opening some Storage Gen 1 or ADLS path that has a deep directory structure. Over 9 "directories" seem to trigger it, but this is probably coincidental.

**Comment by jancschaefer** [comment]
Repro:
----------------------

# Python -- this works
```python
for i in range(0,100): 
     AzureDLFileSystem.touch(f"folder/_file{i}")   
```

# Python -- this breaks it
```python
for i in range(0,105): 
     AzureDLFileSystem.touch(f"folder/_file{i}")   
```

# Assumption:
Storage explorer gets 100 files for the first page. If there are more than 100 files (maybe if these files are empty) in a folder, this breaks.

# Error
```js
Uncaught (in promise) TypeError: Cannot read property 'Azure.Resources' of undefined
    at FileListViewModel.DataTableViewModel.updatePaginationControls (DataTableViewModel.js:189)
    at FileListViewModel.DataTableViewModel.renderPage (DataTableViewModel.js:132)
    at FileListViewModel.<anonymous> (FileListViewModel.js:146)
    at step (AddressBarViewModel.js:34)
    at Object.next (AddressBarViewModel.js:15)
    at fulfilled (AddressBarViewModel.js:6)
```

Full trace [trace.txt](https://github.com/microsoft/AzureStorageExplorer/files/3627242/1568820296032.txt)

**Comment by craxal** [comment]
The problem is Storage Explorer is looking for a display string in the wrong place. The paging likely causes the app to query for a particular string that it doesn't normally grab right away.

**Comment by jinglouMSFT** [comment]
Please reference to #1853.  Fix is available now.
