### ISSUE TITLE
An extra double quotation shows on the context menu of resource groups with Chinese 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1866]
**Storage Explorer Version:** 1.10.0
**Build:** [20190917.7](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3060091)
**Branch:** master
**Platform/OS:** Windows 10/ Centos Linux release_7.6.1810(core)/ macOS High Sierra
**Language:** Chinese(zh-CN)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer using the command 'StorageExplorer.exe --lang=zh-CN'.
2. Expand 'Disks' -> Right click one resource group.
3. Observe the context menu.

**Expect Experience:**
No double quotation shows on the context menu.

**Actual Experience:**
An extra double quotation shows on the context menu.
![image](https://user-images.githubusercontent.com/41351993/65132577-c1231580-da33-11e9-9825-f12cbd344e1b.png)

**More Info:**
This issue doesn't reproduce on German/ Russian.

**Comment by lukaschal** [comment]
On review.

File: loc\en\src\components\se-managed-disks-extension\resources\ManagedDisks.json
ID: 0; "ResourceGroupOpenNewTabActionDisplayName"
SRC: Open New Tab
TGT: 打开“新建”选项卡

**Comment by lukaschal** [comment]
Fixed.

new tgt:  打开新建选项卡

**Comment by craxal** [comment]
New package version needed.

**Comment by v-xianya** [comment]
This issue has been fixed on build 20190925.6. So we close it.
