### ISSUE TITLE
Display unmatched tooltips for 'Save query' and 'Save query as' buttons in the toolbar

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1867]
**Storage Explorer Version:** 1.10.0
**Build:** [20190917.7](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3060091)
**Branch:** master
**Platform/OS:** Windows 10/ Centos Linux release_7.6.1810(core)/ macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release(1.10.0)

**Steps to reproduce:**
1. Expand a storage account -> Tables.
2. Create a new table -> Click 'Query' in the toolbar.
3. Observe tooltips for 'Save query' and 'Save query as' buttons.

**Expect Experience:**
Display the right tooltips for 'Save query' and 'Save query as' buttons.
![image](https://user-images.githubusercontent.com/41351993/65133922-13653600-da36-11e9-9a86-d2197c8bd44e.png)

**Actual Experience:**
Display unmatched tooltips for 'Save query' and 'Save query as' buttons.
![image](https://user-images.githubusercontent.com/41351993/65133936-16f8bd00-da36-11e9-87bb-c00edc0b15ab.png)

**Comment by craxal** [comment]
@v-xianya Do you have the right screenshots? The buttons appear to have the correct tooltips. That is "disk with pencil" is properly labeled "Save query as..." and "disk" is labeled "Save query (Ctrl+S)".

**Comment by v-xianya** [comment]
Hi  @craxal Thanks for your clarification.
This issue doesn't reproduce on the latest build 20190919.2. So we close it.
