### ISSUE TITLE
The keyword 'Leased' doesn't show after acquiring lease for one Azure AD attached blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1868]
**Storage Explorer Version:** 1.10.0
**Build:** 20190917.7
**Branch:** master
**Platform/OS:** Windows 10/ Centos Linux release_7.6.1810(core)/ macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Give an RBAC role to a user like '**Blob Data Owner Role**' or '**Blob Data Contributor Role**' on one blob container tier.
2. Attach the blob container with Azure AD.
3. Attach the same blob container with Azure AD and select the same account.
4. Acquire lease for one of the new attached blob container -> Then try to acquire lease for the other Azure AD attached blob container.
5. Observe the result.

**Expect Experience:**
1. Aquire lease successfully.
2. Show the keyword 'Leased' for the attached blob container.
![image](https://user-images.githubusercontent.com/41351993/65136498-414c7980-da3a-11e9-9683-12790a79792b.png)

**Actual Experience:**
1. Aquire lease successfully.
2. No keyword 'Leased' shows for the attached blob container.
![image](https://user-images.githubusercontent.com/41351993/65136253-d4d17a80-da39-11e9-8f93-1b21823fe0da.png)

**More Info:**
The Keyword shows well after refreshing manually.

**Comment by MRayermannMSFT** [comment]
Not a likely scenario, but for something like Quick Access this should work.

**Comment by MRayermannMSFT** [comment]
@v-xianya I just tried this and it appears to be fixed. Can you verify?

**Comment by v-xianya** [comment]
@MRayermannMSFT Verified this issue on build 20210330.10. 
The behaviors are different between the acquire lease/ break lease actions for another Azure AD attached blob container.

Could you please have a look?

 The current behaviors as below:
After acquiring lease for one Azure AD Attached blob container
1. Need to manually refreshing for the key word 'Leased' to display to another same Azure AD Attached blob container.
2.  If acquire lease for another blob container, there is a failed activity log '**There is already a lease present.**'

After breaking lease for one Azure AD Attached blob container
1. Need to manually refreshing to make the word 'Leased' disappear for another same Azure AD Attached blob container.
2. If break lease for another blob container, there is a successful activity log.
![image](https://user-images.githubusercontent.com/41351993/113082409-fefa2000-920c-11eb-93bd-b2d86091eb60.png)
![image1](https://user-images.githubusercontent.com/41351993/113083001-0241db80-920e-11eb-9128-e3389731708e.gif)

**Comment by JasonYeMSFT** [comment]
I don't think we need to that smart on associating all nodes that point to the same container.

**Comment by MRayermannMSFT** [comment]
@v-xianya ya, as long as the node you are acquiring lease on originally updates, that's fine for now. I'm going to close this as won't fix. :) Thanks!

**Comment by v-xianya** [comment]
@MRayermannMSFT got it and thank you for the response!
