### ISSUE TITLE
Keep its original sign word for one attached storage account 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1869]
**Storage Explorer Version:** 1.10.0
**Build:** [20190917.7](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3060091)
**Branch:** master
**Platform/OS:** Windows 10/ Centos Linux release_7.6.1810(core)/ macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Attach one premium storage account using **name and key**.
2. Observe the attached storage account.

**Expect Experience:**
Keep the original sign word '**Premium**' next to the attached storage account.
Like one attached ADLS Gen2 account：
![image](https://user-images.githubusercontent.com/41351993/65137477-ff243780-da3b-11e9-80bf-f78e3bdd9712.png)

**Actual Experience:**
No not show the original sign word.
![image](https://user-images.githubusercontent.com/41351993/65137582-31359980-da3c-11e9-9821-f24777bf9e12.png)

**More Info:**
1. This issue also reproduces for Blob storage account/ Classic storage account/ File storage account.
2. This issue also reproduces when using SAS attach.

**Comment by MRayermannMSFT** [comment]
By design. If you attach with name and key, there's no way for us to do the ARM call which tells us if the account is premium or not.
