### ISSUE TITLE
Uploading an existing blob doesn't display the default account tier after overwriting it

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#187]
**Storage Explorer Version**: 1.1.0

**Platform**: Windows/Linux/Mac

**Architecture**: x64

**Build Number**: 20180515.2

**Commit**: ca623f81

**Regression From**: Not a regression

#### Steps to Reproduce: ####

1. Launch Storage Explorer and Select one GPv2/Blob account.
2. Set the default Access Tier for the account as 'Cool'.
3. Open one blob container -> Upload one block blob named 'test.txt' -> Make sure the Access Tier of the blob is 'Cool(inferred)'.
4. Change the blob access tier to 'Hot'.
5. Upload the same blob 'test.txt' again to the blob container and overwrite it.
6. Check access tier for the second uploaded blob.

#### Expected Experience: ####
It displays as the set default account tier 'Cool(inferred)'.

#### Actual Experience: ####
It still displays 'Hot'
![tier](https://user-images.githubusercontent.com/34729022/40114278-cd0efa86-58fb-11e8-9465-cda230ebebca.png)

More info:
The value of  'Access Tier Last Modified' same as the value of the 'Last Modified'.

**Comment by craxal** [comment]
I just spoke with the platform team. They're aware of a problem where they don't always send the inferred access tier property when listing blobs.
