### ISSUE TITLE
Add (Ctrl+ R) next to tooltip for the Refresh button in one ADLS Gen1 account's toolbar

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1870]
**Storage Explorer Version:** 1.10.1
**Build:** [20190919.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3064513&view=results)
**Branch:** hotfix/1.10.1
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/ macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Open one ADLS Gen1 account.
2. Hover the mouse to the Refresh button in the toolbar -> Check the tooltip.

**Expect Experience:**
 1. Ctrl+R works well.
 2. (Ctrl+R) shows next to the tooltip.
![image](https://user-images.githubusercontent.com/41351993/65233399-56420f00-db05-11e9-9841-f2619412396b.png)

**Actual Experience:**

1. Ctrl+R works well.
2. (Ctrl+R) doesn't show next to the tooltip.
![image](https://user-images.githubusercontent.com/41351993/65233385-52ae8800-db05-11e9-9151-f19356ed410b.png)

**Comment by MRayermannMSFT** [comment]
Won't fix b/c gen1
