### ISSUE TITLE
No value of size shows for one ADLS Gen2 blob with 0B 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#1872]
**Storage Explorer Version:** 1.10.1
**Build:**[ 20190919.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3064513)
**Branch:** hotfix/1.10.1
**Platform/OS:** Windows 10/ Ubuntu Linux/ macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one ADLS Gen2 account -> Blob Containers.
2. Create a new blob container -> Upload a file with 0B size.
3. Check the value of size for the new uploaded file.

**Expect Experience:**
The size value shows as '0B'.

**Actual Experience:**
No value of size shows.
![image](https://user-images.githubusercontent.com/54055206/65238726-e6855180-db0f-11e9-8e5c-01c6e239d8a3.png)

**More Info:**
1. This issue doesn't reproduce for one non-ADLS Gen2 blob.
2. This issue doesn't reproduce for files under one file share.

**Comment by craxal** [comment]
Looks like there's a type difference between blobs and ADLS Gen 2. ADLS Gen 2 provides and actual number when we're expecting a string in the normal blob case.
