### ISSUE TITLE
Show 'Nothing to display' after searching a non-exist item in blob containers editor

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1874]
**Storage Explorer Version:** 1.10.1
**Build:** [20190919.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3064513&view=results)
**Branch:** hotfix/1.10.1
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/ macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one Non-ADLS Gen2 account -> Blob Containers.
2. Create a new blob container -> Upload a file name 'text.txt' ->Type 'A' in 'Search by prefix(case-sensitive)' box.
3. Check the notification message.

**Actual Experience:**
Show 'No data available in this blob container' in the editor.
![image](https://user-images.githubusercontent.com/41351993/65241396-028bf180-db16-11e9-9b48-919dfda55b2d.png)

**Suggestion:**
Show 'Nothing to display' in the editor.

**More Info:**
This issue also reproduces for file shares.

**Comment by MRayermannMSFT** [comment]
Won't fixing.
