### ISSUE TITLE
Copy, Paste Rename Not Available for non-ADLS Gen2 Blobs

### ISSUE THREAD

**Issue by faulus** [microsoft/AzureStorageExplorer#1875]
**Storage Explorer Version**: 1.9.0
**Build Number**: 20190701.8
**Platform/OS**:  Windows 10
**Architecture**: ia32

## Bug Description ##
On the Storage Account Level i have a READER access & STORAGE BLOB DATA OWNER, but i'm unable to copy paste and rename.

![image](https://user-images.githubusercontent.com/12154672/65261359-64ddf580-db08-11e9-84e5-1164b8fb5efb.png)

## Steps to Reproduce ##
1 - Grant access to user as a Reader on a Storage Account 
2- Give access to the user as a STORAGE BLOB DATA OWNER
3- try to use Azure Storage Explorer with sign in, try to use copy, paste and rename button 

## Expected Experience ##
As a storage blob data owner you will be able to copy paste and rename blobs ... but in my case the data actions are not sufficient. Need owner or contributor on the Storage Account. 

## Additional Context ##
I can't give such rights to a user on the storage account, just to rename a folder ...

**Comment by JasonYeMSFT** [comment]
Hi faulus, 

This was due to limitation of copy/paste api available. The platform team and us are currently working to make it available.

**Comment by MRayermannMSFT** [comment]
Related: https://github.com/microsoft/AzureStorageExplorer/issues/3428
