### ISSUE TITLE
Add blob Creation Time to list / properties views

### ISSUE THREAD

**Issue by davidmatson** [microsoft/AzureStorageExplorer#1876]
**Is your feature request related to a problem? Please describe.**
I can't see the creation time of a blob in storage explorer, even though the underlying REST API has provided this data since 2017.

**Describe the solution you'd like**
In addition to Last Modified, show Created times in both the blob list view (table) and the properties viewer.

**Describe alternatives you've considered**
Use a different tool to get this data.

**Additional context**
The blob service added this data quite a while back via a x-ms-creation-time header. See:
https://docs.microsoft.com/en-us/rest/api/storageservices/version-2017-11-09

**Comment by MRayermannMSFT** [comment]
Hey @davidmatson , for now, we're just going to add this to the properties viewer. In the future, we're looking to add column selection to the blob explorer (the "blob list view"). Once that happens we'll look at adding this to the blob explorer as well.

**Comment by davidmatson** [comment]
Thanks for the update, @MRayermannMFST!

**Comment by MRayermannMSFT** [comment]
Merged into master for 1.14. I've referenced the addition of the creation time field to the issue regarding column selecting for the blob explorer.
