### ISSUE TITLE
A11y_AzureToolsStorageExplorer_ConfigureSoftDeletePolicy_keyboard: Loss of keyboard focus is found after "Cancel" button.

### ISSUE THREAD

**Issue by Radha2019** [microsoft/AzureStorageExplorer#1884]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.” 

GitHubTags: #A11y_AzureToolsStorageExplorer; #A11yMAS; #A11YTCS; #DesktopApp; #MAS2.4.3; #Keyboard; #Win10;

**Environment Details:**
Application Name: Azure Tools Storage Explorer
Application Version: 1.10.0
Windows10

**Repro Steps:**
1. Launch Storage Explorer.
2. Navigate to "Open Connect dialog" pane and Sign in to Azure.
3. Go to "Manage Accounts" pane and Select the subscriptions you will use. Once selected, click on "Apply" button.
4. Navigate to "Blob Containers" of the selected subscription, right click and Select "Configure Soft Delete Policy" and hit enter.
5. Start Navigating on the screen using TAB key.
6. Verify Keyboard focus is lost after "Cancel" button.

**​Actual:​**
Loss of keyboard focus is found after "Cancel" button.

**Same issue is observed throughout the application for all the dialog screens after "Cancel" button.**

**Expected:**
Keyboard focus should not be lost after "Cancel" button. Instead focus when it is Tab Keyboard focus should shift to "What is Soft Delete?" link.

**UserImpact:**
If keyboard focus is lost after cancel button they keyboard only users face difficulty to know where the keyboard focus is on the screen.

**Recommendation:**
https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx

**MAS Reference:**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={0de7fbe1-ad7e-48e5-bcbb-8d986691e2b9} 

**Attachment for Reference:**
[A11y_AzureToolsStorageExplorer_ConfigureSoftDeletePolicy_Keyboard.pptx](https://github.com/microsoft/AzureStorageExplorer/files/3642011/A11y_AzureToolsStorageExplorer_ConfigureSoftDeletePolicy_Keyboard.pptx)

**Comment by MRayermannMSFT** [comment]
Figure out how to resolve as in VPAT

**Comment by Alexandria-R** [comment]
Approved for exclusion as low impact.

**Comment by vinodbk197** [comment]
@MRayermannMSFT 

Verified this issue on: Application Name: Azure Tools Storage Explorer
Application Version: 1.12.0
As part of core scenario test execution, This issue (Keyboard focus is lost after the "cancel" button) is still reproduces for the below scenario.
1. Connect to Azure Storage
2. Delete Popup
3. Upload Files
4. Upload Folder
5. Update Access Tier
6. Clone with New Name Blob
7. Break Lease Popup
8. Rename Blob Container

**Comment by mstechie** [comment]
GitHubTags:#BM-TCS-StorageExplorer-Win32-Sep2019;

**Comment by Yash14j** [comment]
GitHubTags:#A11ysev3
