### ISSUE TITLE
Table Statistics in Table Storage View Fails on Partition Key Queries

### ISSUE THREAD

**Issue by Programmerman1** [microsoft/AzureStorageExplorer#1886]
**Storage Explorer Version**: 1.10.1
**Build Number**: 20190919.2 
**Platform/OS**: macOS
**Architecture**: x64
**Regression From**: Unknown

## Bug Description ##
Running Table Statistics when query searches Partition Key fails with the message
`Inspecting entities...: [_.sprintf] huh?`

## Steps to Reproduce ##
1. Query a Table Storage account by Partition Key equality and nothing else
2. Press the "Table Statistics" button

## Expected Experience ##
A success message appears in Activities with the total number of rows, possibly after several updates while the data is paged through

## Actual Experience ##
A failure message appears in Activities
`Inspecting entities...: [_.sprintf] huh?`

## Additional Context ##
I also see this problem on the Azure portal's Storage Explorer. I couldn't reproduce when making other queries, only PartitionKey

**Comment by craxal** [comment]
Looks like the code is trying to format a string that isn't actually localized. We'll get this fixed.

**Comment by craxal** [comment]
Bug itself has been fixed. Waiting for string translation.

**Comment by lukaschal** [comment]
@craxal Which resources/strings needs to be localized in this case ?

**Comment by craxal** [comment]
Strings in Activities.json appear to be translated now, so closing.
