### ISSUE TITLE
The action 'Remove from Quick Access' for one QA resource group is not localized

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1894]
**Storage Explorer Version:** 1.10.1
**Build:** [20190924.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3076815&view=logs&j=c9f4993e-ba9a-5f87-11e6-962dc1008ac4)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS High Sierra
**Architecture:** ia32/x64
**Language:** Chinese (zh-CN)/ Russian(ru)/ German(de)
**Regression From:** Not a regression

**Steps to reproduce:**
1. Run the command 'StorageExplorer.exe --lang=zh-CN' to launch Storage Explorer.
2. Expand '磁盘' -> Select one resource group then add it to Quick Access.
2. Check the QA resource group's context menu.

**Expect Experience:**
'Remove from Quick Access' is localized

**Actual Experience:**
'Remove from Quick Access' is not localized
![image](https://user-images.githubusercontent.com/41351993/65504672-1494d800-defa-11e9-8da3-1d9179afe4aa.png)

**Comment by lukaschal** [comment]
Localized at 8/6/2019.

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer/commit/12a1ea18300736b3b870c8eeb2e8a467325e41e5?_a=compare&path=%2Floc%2Floc%2Fzh-Hans%2Fsrc%2FStandalone%2Fresources%2FHost.json.lcl

File: loc\en\src\Standalone\resources\Host.json
ID: 0; "TreeView.QuickAccess.Remove"
SRC: Remove from Quick Access
TGT: 从快速访问中删除

**Comment by MRayermannMSFT** [comment]
Fixed.

**Comment by MRayermannMSFT** [comment]
![image](https://user-images.githubusercontent.com/21112697/65626563-7b5dd400-df82-11e9-96dd-c3b843271dc2.png)
