### ISSUE TITLE
'Cancel' is not translated in upload dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1895]
**Storage Explorer Version:** 1.10.1
**Build:** [20190924.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3076815&view=logs&j=c9f4993e-ba9a-5f87-11e6-962dc1008ac4)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04 /macOS High Sierra
**Architecture:** ia32/x64
**Language:** Chinese (zh-CN)/ Russian(ru)/ German(de)
**Regression From:** Not a regression

**Steps to reproduce:**
1. Run the command 'StorageExplorer.exe --lang=zh-CN' to launch Storage Explorer.
2. Make sure Azcopy is enabled.
3. Expand a storage account -> Blob Containers.
4. Create a new blob container -> Click 'Upload' button then select 'Upload Files...'.
5. Check the upload dialog.

**Expect Experience:**
 'Cancel' is translated.

**Actual Experience:**
 'Cancel' is not translated.
![image](https://user-images.githubusercontent.com/41351993/65505986-1d3add80-defd-11e9-85b3-ed06e7e023f3.png)

**More Info:**
This issue also reproduces for file shares.

**Comment by craxal** [comment]
Odd. The app appears to have pulled the English strings for one namespace. I'll have to look into that further.

**Comment by craxal** [comment]
Aha, we're not copying all of the translated files to the build. 😅 Most of the strings in the dialog come from `se-az-copy-extension` which does include the translated files, but the Cancel button label comes from the "core" resource files, which we weren't copying. Easy fix.
