### ISSUE TITLE
Storage Explorer wont start on Windows 7

### ISSUE THREAD

**Issue by unnity** [Microsoft/AzureStorageExplorer#190]
**Storage Explorer Version**:  

1.0.0

**Platform**: 

Windows 7

**Architecture**: 

32 bit

**Build Number**: 

Not sure

**Commit**: 

Not sure

**Regression From**: 

Trying for first time

#### Steps to Reproduce: ####

1. 

Install Storage Explorer, run storage explorer

2. 

Just shows Loading on the startup screen but never starts. Unsure where to check the logs

#### Expected Experience: ####

Expect it to allow me to login and work on Azure storage

#### Actual Experience: ####

Only seeing the startup screen with loading

![image](https://user-images.githubusercontent.com/19242791/40156830-64bf69c0-59b9-11e8-86b1-a15549825d61.png)

**Comment by craxal** [comment]
Please look at #119 and #166 and see if those resolve your issue. If not, please let us know and we can reopen this.
