### ISSUE TITLE
Miss '…' next to the localized action 'Change Access Tier' for one blob

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#1900]
**Storage Explorer Version:** 1.10.1
**Build:** [20190924.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3076815)
**Branch:** master
**Platform/OS:** Windows 10/ Ubuntu Linux 18.04
**Language:** Chinese(zh-CN)
**Architecture:** ia32/x64

**Steps to reproduce:**

1. Launch Storage Explorer using the command '_StorageExplorer.exe --lang=zh-CN_'.
2. Expand one storage account -> Blob Containers -> Create a new blob container and upload a file.
3. Right click the file and check its context menu.

**Expect Experience:**
Displays '...' next to the localized action 'Change Access Tier'.

**Actual Experience:**
Miss '…' next to the localized action 'Change Access Tier'.
![image](https://user-images.githubusercontent.com/54055206/65505014-dba93300-defa-11e9-9efd-4571ec1f1f05.png)

**Comment by lukaschal** [comment]
Fixed on all languages.

**Comment by v-limu** [comment]
This issue has been fixed on build [20191012.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3136519). So we close it.
