### ISSUE TITLE
v1.10.1 is no longer connecting to Hierarchical Namespace

### ISSUE THREAD

**Issue by rajrao** [microsoft/AzureStorageExplorer#1902]
v1.10.1, when I connect to a ADLS gen 2 hierarchical namespace, i get the following error:

Unable to retrieve child resources.

Details:
Blob API is not yet supported for hierarchical namespace accounts.
RequestId:8cfe2868-201e-0029-6127-73ebe9000000
Time:2019-09-24T22:30:05.4948780Z

This worked in v 1.9.x and after upgrading today this no longer works

**Comment by rajrao** [comment]
Issue appears first in v1.10.0.

**V1.9.0** 
![image](https://user-images.githubusercontent.com/1643325/65557104-4fddd980-deef-11e9-9be3-4aed8722e3f7.png)
**v.1.10.0** Broken!
![image](https://user-images.githubusercontent.com/1643325/65557809-cd0a4e00-def1-11e9-96f3-4b6c5045f822.png)

**Comment by jinglouMSFT** [comment]
Looks like we don't recognize this is an ADLS Gen2 HNS enabled account.  Was there anything changed from the account perspective?

**Comment by rajrao** [comment]
No, nothing changed. Also, if I rollback to v1.9, it works. So, it shouldnt be related to the Storage Account.
One thing to note is that we did request to enroll in public preview for multi-protocol access, today.

**Comment by jinglouMSFT** [comment]
The error message indicated to me that you are on the preview for the multi-protocol access.  Did you try to rollback to 1.9 after the enrollment?  Either way, we will need to look at the fiddler trace results to diagnose this issue.  We need the fiddler trace from the point where Storage Explorer is newly launched, to the point where you click on the "Load more" node that generated the errors.  

Fiddler ([www.telerik.com/fiddler](https://www.telerik.com/fiddler) is a free product from Telerik. Fiddler records, inspects and debugs internet traffic your computer sends and receives. The data collected will allow us to analyze communication between your computer and our services to help diagnose your specific issue. We will only use this data in compliance with our privacy statement ([msdn.microsoft.com/en-us/vstudio/dn751493.aspx](https://privacy.microsoft.com/en-US/privacystatement)) to resolve your problem and improve our service. We will promptly delete it following our investigation of the issue. You may want to disable ‘Decrypt HTTPS traffic’ in Fiddler or uninstall Fiddler when you are finished with this process.
Fiddler is a third party tool subject to its own terms and conditions that you are using at your own risk. Microsoft disclaims any liability or damages related to your usage of Fiddler, even as a result of following the instructions provided.
 
STEPS TO FOLLOW 
	1. Start Fiddler
	2. Go to Tools -> Options
	3. Click on the HTTPS tab
	4. Make sure Capture HTTPS CONNECTs and Decrypt HTTPS traffic are checked
	5. Click on the Actions button
	6. Choose "Trust Root Certificate" and then "Yes" in the next dialog
	7. Click on the Actions button again
	8. Choose “Export Root Certificate to Desktop”
	9. Go to your desktop
	10. Find the FiddlerRootCer file
	11. Double click to open
	12. Go to the "Details" tab
	13. Click "Copy to File…"
	14. In the export wizard choose the following options
		○ Base-64 encoded X.509
		○ For file name, Browse… to C:\Users\<your user dir> \AppData\Roaming\StorageExplorer\certs, and then you can save it as any file name
	15. Close the certificate window
	16. Start Storage Explorer
	17. Go to Edit -> Configure Proxy
	18. In the dialog, enable proxy settings, and set the URL to http://localhost and the port to 8888
	19. Click Ok
	20. Reproduce the scenario.
	21. Close the application
	22. Go back to fiddler
	23. Click File > Save > All Sessions… and save the file in a location you can find later. 
	24. Send us the saved file

**Comment by rajrao** [comment]
Is it safe to upload the session files here, or is there an email I can send it to you?

**Comment by jinglouMSFT** [comment]
please send it to sehelp@microsoft.com.  Thanks.

**Comment by rajrao** [comment]
Not sure what has changed, but this is magically working today (v1.10.0)
![image](https://user-images.githubusercontent.com/1643325/65718888-bd117c00-e061-11e9-90af-773a3a192bcb.png)

**Comment by jinglouMSFT** [comment]
Thanks for letting us know.  Please feel free to reopen the issue if you see it coming back.

**Comment by rajrao** [comment]
Also tested in v1.10.1 and its working in it too. So maybe it was a server side issue. Feel free to close this issue if you think it is resolved.
