### ISSUE TITLE
Miss '...' next to localized 'Properties' for one ADLS Gen2 blob

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1907]
**Storage Explorer Version:** 1.10.1
**Build:** [20190925.6](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3080492&view=results)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Language:** Chinese (zh-TW) 
**Regression From:** Not a regression

**Steps to reproduce:**
1. Run the command 'StorageExplorer.exe --lang=zh-TW' to launch storage explorer.
2. Expand one ADLS Gen2 storage account -> Blob Containers.
3. Select one blob container which contains at least one blob.
4. Select one blob and check its context menu.

**Expect Experience:**
Display '...' next to localized 'Properties'.

**Actual Experience:**
No '...' displays to localized 'Properties'.
![image](https://user-images.githubusercontent.com/41351993/65590847-090ae500-dfbe-11e9-82f9-506e634c0098.png)

**Comment by lukaschal** [comment]
All instances fixed on all languages.

File: loc\en\src\components\se-adls2-extension\resources\FileSystemEditor.json
ID: 0; "ContextMenu.PropertiesCommandName"
SRC: Properties...
TGT: 屬性...

**Comment by v-limu** [comment]
This issue has been fixed on build [20191017.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3150956). So we close it.
