### ISSUE TITLE
An extra '[ ]' displays to localized buttons 'Open' & 'Download' for one blob 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#1909]
**Storage Explorer Version:** 1.10.1
**Build:** [20190925.6](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3080492)
**Branch:** master
**Platform/OS:** Windows 10/ Ubuntu Linux 18.04/Mac OS High Sierra
**Language:** Chinese(zh-TW)
**Architecture:** ia32/x64

**Steps to reproduce:**

1. Launch Storage Explorer using the command 'StorageExplorer.exe --lang=zh-TW'.
2. Expand one storage account -> Blob Containers.
3. Open one blob container -> Check the Open button and Download button on editor.

**Expect Experience:**
No '[ ]' displays to localized buttons 'Open' & 'Download'.

**Actual Experience:**
An extra '[ ]' displays to localized buttons 'Open' & 'Download'.
![image](https://user-images.githubusercontent.com/54055206/65593697-a3215c00-dfc3-11e9-8308-b7196c4f8b18.png)

**More Info:**

1. This issue also reproduces for one file under one file share.
2. This issue also reproduces on localized actions 'Open' & 'Download' in the context menu for one blob/file.
![image](https://user-images.githubusercontent.com/54055206/65594083-9ea97300-dfc4-11e9-8d86-283217eedc24.png)

3. This issue also reproduces for the one disk.
![image](https://user-images.githubusercontent.com/54055206/65594159-c7ca0380-dfc4-11e9-83d3-11e629b06fd1.png)

**Comment by lukaschal** [comment]
Fixed.

File: loc\en\src\components\se-adls2-extension\resources\FileSystemEditor.json
ID: 0; "Toolbar.DownloadCommandName"
SRC: Download
TGT: 下載

File: loc\en\src\components\se-adls2-extension\resources\FileSystemEditor.json
ID: 0; "Toolbar.OpenCommandName"
SRC: Open
TGT: 開啟

**Comment by v-limu** [comment]
This issue has been fixed on build [20191012.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3136519). So close it.
