### ISSUE TITLE
An extra broken icon displays in 'About' Panel

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#191]
**Storage Explorer Version**: 1.1.0
**Platform**: Linux Ubuntu 16.04
**Architecture**: x64
**Build Number**: 20180516.1
**Commit**: e0a60be3
**Regression From**: Previous release

#### Steps to Reproduce: ####

1. Launch Storage Explorer.
2. Navigate to 'Help' -> 'About'.

#### Expected Experience: ####
No extra icon displays in 'About' Panel.

#### Actual Experience: ####
An extra broken icon displays in 'About' Panel.

![broken](https://user-images.githubusercontent.com/34729022/40171179-02a42626-59ba-11e8-9433-4aee08a7cb28.png)

**Comment by MRayermannMSFT** [comment]
@v-xuanzh , can you see if this still repros? I'm not seeing it on master builds or the released version of 1.1.0. Thanks!

**Comment by MRayermannMSFT** [comment]
Please reopen if it still does.

**Comment by v-xuanzh** [comment]
Hi Matthew,

I verified this issue on latest master build 20180606.1, Still reproduces. So reopen it.
![broken](https://user-images.githubusercontent.com/34729022/41073939-257c10c8-69f5-11e8-8d9e-df4f0e6ad827.png)

**Comment by MRayermannMSFT** [comment]
What version of Ubuntu are you using?

**Comment by craxal** [comment]
I was able to repro. I played around with this, and I expect it's an Electron 2.* bug. I opened electron/electron#13250 for reference.
