### ISSUE TITLE
A11y_AzureToolsStorageExplorer_SASGenerate_Screenreader:Unnecessary table is read when the focus is on the "Access policy" combo box.

### ISSUE THREAD

**Issue by Charanrajkb** [microsoft/AzureStorageExplorer#1915]
" [Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing aster and easier.”

GitHubTags: #A11y_AzureToolsStorageExplorer; #A11yMAS; #A11YTCS; #DesktopApp; #MAS1.3.1; #NVDA; Win32; 

**Environment Details:**
Application Name: Azure Tools Storage Explorer
Application Version: 1.10.0
Windows10

**Repro Steps:**
1. Launch Storage Explorer
2. Navigate to "Open Connect dialog" pane and Sign in to Azure.
3. Go to "Manage Accounts" pane and Select the subscriptions you will use. Once selected, click on "Apply" button.
4. Navigate to "Blob Containers" of the selected subscription, right click and hit enter on "Create Blob container" to Create a new Blob container.
5. Once completed, Navigate to "Upload" button and Upload a blob/file by using  "Upload Files" control.
6. Blob gets uploaded, right click on blob and select "Get Shared Access Signature" control and hit enter
7. Start NVDA and navigate using the tab key till the "Access policy" combo box.
8. Observe the NVDA readings.

​**Actual:​**
Unnecessary table is read when the focus is on the "Access policy" combo box.

**Expected:**
Screen reader must only read the "Access policy" combo box and it should not read the table unnecessary.

**User Impact:**
Screen readers user gets confused if the if the table is read when the focus is on the combo box.

**Recommendation:**
[https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx](url)

**MAS Reference:**
MAS1.3.1:
[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}](url)

**Attachment for Reference:**
[1915_A11y_AzureToolsStorageExplorer_SharedAccessSignature_Screenreader.pptx](https://github.com/microsoft/AzureStorageExplorer/files/3652457/1915_A11y_AzureToolsStorageExplorer_SharedAccessSignature_Screenreader.pptx)

**Comment by craxal** [comment]
Verified, but the focus is _not_ on the Access Policy combo box when "row 1, column " is read out. I think it's reading this because we're using CSS tables (`display: table`). We should switch to CSS grids.

**Comment by Alexandria-R** [comment]
Approved for exclusion as low impact.

**Comment by fsteffi** [comment]
GithubTags:#Closed;

**Comment by mstechie** [comment]
GitHubTags:#BM-TCS-StorageExplorer-Win32-Sep2019;
