### ISSUE TITLE
Folder hidden both in desktop and web version

### ISSUE THREAD

**Issue by dsosas** [microsoft/AzureStorageExplorer#1916]
Storage Explorer Version: 1.10.1
Platform/OS: Windows 10
Architecture: x64

**Bug Description**
Created a folder under a a Blob container named "DataExportJobs" but is always hidden in the explorer. It only appears after navigating to the last page and then going back to the first page (where the folder should render)

**Steps to reproduce**
* Create blob container named "exports" add a folder named "2019" and over 2,389 blob files whose names are GUIDs.

* Create folder named "DataExportJobs" under the exports blob, after all files were added.

* Then close the exports container tab and reopen it. The folder, which should show at the beginning next to the folder 2019, does not show in any of the pages.

![explorer_nofolder](https://user-images.githubusercontent.com/12314648/65609565-fcff3300-df7d-11e9-81c4-70f32c8ba84e.PNG)

* Navigate to the last page of the container then back to the first one and the folder is there.

![explorer_foldershow](https://user-images.githubusercontent.com/12314648/65609655-2324d300-df7e-11e9-8e91-6faebcbb430e.PNG)

**Expected exprience**
The folder should show next to the 2019 folder as it does after navigating to the last page then back to the first.

** Additional context**
Please let me know if you need further information to track down the problem.

**Comment by jinglouMSFT** [comment]
Is this regular blobs or ADLS Gen2?   If regular blobs, the folder DataExportJobs you created doesn't actually exist in Azure until you paste, drag or upload blobs into it.  Did you paste or drag or upload any blobs after you created DataExportJobs?  What's strange is that after you went the last page and come back to the first page, you saw the DataexportJobs, which i couldn't reproduce based on the steps you described above .  Is there anything missing in the steps above?

Also, it's a little unclear when you said "add a folder named 2019 and over one thousand blob files whose names are GUIDs. Were the thousand blob files added under 2019 or parallel to 2019?  the screenshots have the GUIDs parallel to 2019, but from how the virtual folder works, you probably also have the GUIDs inside the 2019 folder, correct?

**Comment by dsosas** [comment]
These are regular blobs. The DataExportJobs folder has other folders which each contain blobs. The behavior is indeed strange. _The thousand blob files are parallel to 2019_. I just went over it again and noticed I have more blobs than initially thought. There are exactly 2,389 items in the export container. You don't need the 2019 folder but you should with at least that many blob files. I deleted them to about half of them in a duplicate container and the behavior disappeared.

![exports](https://user-images.githubusercontent.com/12314648/65697271-a6aaf680-e048-11e9-8dd8-fee0e97bbbd0.PNG)

It looks as it only shows when all items are loaded to cache, which it seems to do after I navigate to the last page.
![exports2](https://user-images.githubusercontent.com/12314648/65697305-b32f4f00-e048-11e9-9adc-553061bd78ff.PNG)

**Comment by MRayermannMSFT** [comment]
Ya, this makes sense. Looking at the names of the blobs you have, the folder "DataExportJobs" comes later in the alphabet than everything else. When we list blobs, they are listed alphabetically, so your folder (or really, all of the blobs inside of it) are listed last. Unfortunately the order in which the blobs are listed is not something we can change when making the API call.

**Comment by dsosas** [comment]
So it is a normal behavior for the folder not to show at all? Because the issue I've been having is that the folder isn't in any of the pages when I first open up the container in the explorer. I can only see it after I navigate all the way to the end and then back to the first page and it's magically there. One could easily create a folder, add blobs to it, and navigate through all the pages to not find it. Then close the blob container thinking it was never added while it was actually there.

I know it's a very specific case as it only happens after a certain number of blobs are in the container, but wanted you to be aware it's an annoying little bug we've been experiencing at our company :)
