### ISSUE TITLE
What does this issue mean?

### ISSUE THREAD

**Issue by AlexFiala** [microsoft/AzureStorageExplorer#1917]
**Storage Explorer Version**: 1.10.1
**Build Number**: 20190919.2
**Platform/OS**:  Windows 10
**Architecture**:  x64
**Regression From**:  1.10

## Bug Description ##
Using the upload button, on storage explorer, to upload a csv file

## Steps to Reproduce ##
Upload, select file, wait, error shown.

## Expected Experience ##
File uploads without issue.

## Actual Experience ##
This error:
Transfer of 'D:\tmp\DimClaimants_new.csv' to 'trg/raw/Asbestos/Miosoft-InputFiles' failed: error: Authentication failed, it is either not correct, or expired, or does not have the correct permission -> github.com/Azure/azure-storage-azcopy/azbfs.newStorageError, /home/vsts/work/1/s/azbfs/zc_storage_error.go:41 ===== RESPONSE ERROR (ServiceCode=) ===== Description=failed to unmarshal response body, Details: (none) PUT https://e2nprdadls01.dfs.core.windows.net/trg/raw/Asbestos/Miosoft-InputFiles/DimClaimants_new.csv?action=append&position=394264576&timeout=901 Authorization: REDACTED Content-Length: [352777] User-Agent: [AzCopy/10.2.1 Azure-Storage/0.1 (go1.12; Windows_NT)] X-Http-Method-Override: [PATCH] X-Ms-Client-Request-Id: [df19e901-2b66-4d30-7035-21795b632538] X-Ms-Date: [Wed, 25 Sep 2019 17:27:16 GMT] X-Ms-Version: [2018-11-09] -------------------------------------------------------------------------------- RESPONSE Status: 403 Forbidden Cache-Control: [no-cache] Content-Length: [14413] Content-Type: [text/html] Server: [Zscaler/5.7] invalid character '<' looking for beginning of value (used name and key, discovery completed)

## Additional Context ##
Other files of the same type work fine, and this file is literally just a copy/past of another file that was previously successfully uploaded to storage explorer, using the same exact process.  I have no idea what this error message means.

**Comment by jinglouMSFT** [comment]
Can you send us the AzCopy log file? There should be a link in the activity log after the transfer fails.  Thanks.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
