### ISSUE TITLE
ADLS Gen 2 Not listing Filesystems aka containers

### ISSUE THREAD

**Issue by Saugat168** [microsoft/AzureStorageExplorer#1921]
**Storage Explorer Version**: 1.10.1
**Build Number**: 20190919.2
**Platform/OS**: Windows 10
**Architecture**: ia32
**Regression From**:  0.7 and also 0.9

## Bug Description ##

I have multiple Azure Data Lake Gen 2 accounts and this new version of Storage explorer would not list the Filesystems (aka containers). Throws an error - "
## Steps to Reproduce ##
Go to your Storage Account and expand "Blob Containers". By the way, we have a corporate proxy.

## Actual Experience ##

![errorStorageExplorer](https://user-images.githubusercontent.com/30119939/65668615-54ff6d80-e042-11e9-9d9e-007ef1a5516e.PNG)

**Comment by MRayermannMSFT** [comment]
Have you added your corporate proxy to Storage Explorer yet? You can do this via the Settings UI.

**Comment by Saugat168** [comment]
Yes, like I mentioned it used to work in the earlier version 0.7 and even later. The proxy settings were always there.

**Comment by Saugat168** [comment]
Hey, any update on this one? We still have the issue. As mentioned,the corporate proxy setting was always set and is still set, which worked previously.

**Comment by MRayermannMSFT** [comment]
@saugat168 , can you please try this private build?

- Windows: https://aka.ms/storageexplorer/msal/windows 
- Mac: https://aka.ms/storageexplorer/msal/macos 
- Linux: https://aka.ms/storageexplorer/msal/linux 

It is an early version of our next release (1.11.1).

**Comment by Saugat168** [comment]
@MRayermannMSFT - Thanks for getting back. I installed this private build and faced the same issue. I installed the version 1.9.0 (I had the installer on my hard drive), and that works.

So, surely something has gone wrong with the versions 1.10.1 and also with this new upcoming release of 1.11.1. 

Will you check what it is, that has gone wrong? As I said- version 1.9.0 works.

**Comment by MRayermannMSFT** [comment]
@Saugat168 , can you elaborate on what type of proxy you are behind? What we're currently thinking is there is some sort of proxy technology that the new Storage SDKs don't support, and we're trying to figure out what that technology is, and then setup that same type of proxy here on our machines.

**Comment by Saugat168** [comment]
@MRayermannMSFT : This is the info that we got from our Network team.

We are using Cisco WSA – S390 appliance as proxy.

The Proxy is running on AsyncOS version: 11.7.0-407.

**Comment by MRayermannMSFT** [comment]
Hi @Saugat168 , would you be open to doing a customer call with us? Our SDK team would like to do some debugging locally on your machine. If yes, do you have a screen sharing software you are comfortable with? Thanks!

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. A proxy fix for gen2 was shipped in 1.12.0. This should be fixed. Please open a new issue if you continue to have problems.
