### ISSUE TITLE
'EXPLORER' is not localized in Chinese (zh-TW)

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1923]
**Storage Explorer Version:** 1.10.1
**Build:** [20190926.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3084119)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Language:** Chinese (zh-TW)
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer -> Open Settings panel-> Preference Locale.
2. Select language as 'Chinese (tranditional)' -> Restart Storage Explorer.
3. Check whether 'EXPLORER' is localized or not.

**Expect Experience:**
'EXPLORER' is localized.

**Actual Experience:**
'EXPLORER' is not localized.
![image](https://user-images.githubusercontent.com/41351993/65678214-7e8db880-e085-11e9-824a-8a07e61dc9d3.png)

**More Info:**
This issue doesn't reproduces in Chinese (zh-CN).
![image](https://user-images.githubusercontent.com/41351993/65678198-77ff4100-e085-11e9-94bd-03b603576f05.png)

**Comment by lukaschal** [comment]
On review.

File: loc\en\src\Standalone\resources\Host.json
ID: 0; "CloudExplorer.Appearance.Explorer.Name"
SRC: Explorer
TGT: Explorer

**Comment by lukaschal** [comment]
Localized.

**Comment by v-xianya** [comment]
This issue has been fixed on build 20191017.3. So we close it.
