### ISSUE TITLE
'Configure Soft Delete Policy…'  is not localized on Blob Containers context menu

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1925]
**Storage Explorer Version:** 1.10.1
**Build:** [20190926.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3084119)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Language:**  Chinese (zh-CN) / Chinese (zh-TW)
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer -> Open Settings panel-> Preference Locale.
2. Select language as 'Chinese (simplified)' -> Restart Storage Explorer.
3. Expand one non-ADLS Gen2 storage account.
4. Right click 'Blob Containers' -> Check its context menu. 

**Expect Experience:**
'Configure Soft Delete Policy…' is localized.

**Actual Experience:**
'Configure Soft Delete Policy…' is not localized.
![image](https://user-images.githubusercontent.com/41351993/65679446-b0078380-e087-11e9-9ce1-aa9d4462c195.png)

**Comment by craxal** [comment]
Good catch. Missed localizing a string. Will also need to be translated.

**Comment by lukaschal** [comment]
On translation now.

File: loc\en\src\Standalone\resources\Azure.json
ID: 0; "ActionConfigureSoftDeletePolicy"
SRC: Configure Soft Delete Policy...
TGT: 配置软删除策略

**Comment by craxal** [comment]
Verified fixed on master.
