### ISSUE TITLE
There are strings on Settings panel are not localized in Chinese(zh-TW)

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1927]
**Storage Explorer Version:** 1.10.1
**Build:** [20190926.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3084119)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Language:** Chinese (zh-TW)
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer -> Open Settings panel-> Preference Locale.
2. Select language as 'Chinese (tranditional)' -> Restart Storage Explorer.
3. Open Settings panel.
4.  Check the 'Preference Locale' and 'Data Explorers' parts.

**Expect Experience:**
All of the strings in the two parts are localized. 

**Actual Experience:**
There are strings in the two parts are not localized. 
![image](https://user-images.githubusercontent.com/41351993/65679923-9f0b4200-e088-11e9-9117-08f9b41fde9e.png)

![image](https://user-images.githubusercontent.com/41351993/65679969-b1857b80-e088-11e9-8e21-b91c1bf9dc9c.png)

**Comment by lukaschal** [comment]
Localized  at 9/27/2019.

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer?_a=contents&path=%2Floc%2Floc%2Fzh-Hant%2Fsrc%2FStandalone%2Fresources%2FShell.json.lcl&version=GBmaster

**Comment by v-xianya** [comment]
Hi @lukaschal  This issue has been fixed on build 20191018.3. So we close it.
