### ISSUE TITLE
An extra letter shows next to one localized menu

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1928]
**Storage Explorer Version:** 1.10.1
**Build:** [20190926.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3084119)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04
**Architecture:** ia32/x64
**Language:** Chinese (zh-TW) / Chinese (zh-CN)
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer -> Open Settings panel-> Preference Locale.
2. Select language as 'Chinese (simplified)' -> Restart Storage Explorer.
3. Check the localized menus in the top left corner of Storage Explorer.

**Expect Experience:**
No extra letter shows.

**Actual Experience:**
An extra letter shows.
![image](https://user-images.githubusercontent.com/41351993/65680892-7be19200-e08a-11e9-8960-c2800bded3bb.png)

**More Info:**
This issue doesn't reproduce on Mac.

**Comment by craxal** [comment]
That's by design. The letter corresponds to keyboard input when pressing Alt.
