### ISSUE TITLE
Storage Explorer assumes port 1000[0,1,2] for Storage Emulator

### ISSUE THREAD

**Issue by oxxa** [Microsoft/AzureStorageExplorer#193]
**Storage Explorer Version**: 1.1.0

**Platform**: Windows

**Architecture**: ia32

**Build Number**: 20180507.1

**Commit**: bcc8990d

**Regression From**: Not a regression afaik

#### Steps to Reproduce: ####

This bug/missing feature relates to how Storage Explorer interacts with the Storage Emulator.  

By default Azure Storage Emulator is setup to listen on ports http://127.0.0.1:10000 10001 and 10002 . On my system I have found another process grabs port 100000, so I have to start the Storage Emulator with it listening on another port range instead - via a change to its config file. That works fine and I can configure my VS project to talk to it, the issue is there seems to be no way to tell Storage Explorer that the emulator is now using different ports, instead it always tries to look for 10000, 10001 and 10002. Can an option be added so I can let it know about the ports the emulator is actually using?  Or could Storage Explorer try to query the AzureStorageEmulator.exe.config file in C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator directory to see what ports it uses if it has trouble connecting?

![image](https://user-images.githubusercontent.com/20371749/40190530-13572f44-59f7-11e8-87d0-9915fdf89dba.png)

#### Expected Experience: ####
I would like an option so that I can tell Storage Explorer what my Storage Emulator ports are.

#### Actual Experience: ####
I can't seem to find such an option to change the connection details for my local storage account.

**Comment by craxal** [comment]
Currently, you can't customize the endpoints for the emulator connection. That will be fixed in an upcoming release.
