### ISSUE TITLE
The 'Create Snapshot' is not localized for a file share context menu

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#1930]
**Storage Explorer Version:** 1.10.1
**Build:** [20190926.6](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3084878&view=logs)
**Branch:** master
**Platform/OS:** Windows 10/ Ubuntu Linux 18.04/Mac OS High Sierra
**Language:** Chinese(zh-CN)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer using the command 'StorageExplorer.exe --lang=zh-CN'.
2. Expand a storage account -> File Shares.
3. Create a new file share -> Right click it and check the 'Create Snapshot' on the context menu.

**Expect Experience:**
The 'Create Snapshot' shows '创建快照'.

**Actual Experience:**
The 'Create Snapshot' is not localized.
![image](https://user-images.githubusercontent.com/54055206/65680532-b72f9100-e089-11e9-8987-6ae52ffef111.png)

**Comment by craxal** [comment]
Hard-coded string.
