### ISSUE TITLE
Keep a consistent sorts for the top left menus between ENU and non-ENU

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#1931]
**Storage Explorer Version:** 1.10.1
**Build:** [20190926.6](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3084878&view=logs)
**Branch:** master
**Platform/OS:** Windows 10/ Ubuntu Linux 18.04/Mac OS High Sierra
**Language:** Chinese(zh-CN)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer using the command 'StorageExplorer.exe --lang=zh-CN'.
2. Check the top left menus sort.

**Expect Experience:**
The localized menu 'Help' is sorted as the last one like ENU.
![image](https://user-images.githubusercontent.com/54055206/65681255-1641d580-e08b-11e9-8ea1-523ac9999225.png)

**Actual Experience:**
The localized menu 'Preview' is sorted as the last one.
![image](https://user-images.githubusercontent.com/54055206/65681299-2bb6ff80-e08b-11e9-848a-d65c0f6038c7.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
