### ISSUE TITLE
'Permissions' is not translated on Properties panel for one attached resource

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1932]
**Storage Explorer Version:** 1.10.1
**Build:** [20190926.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3084119)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Language:** Chinese (zh-TW) / Chinese (zh-CN)
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer using the command 'StorageExplorer.exe --lang=zh-CN'.
2. Attach one storage account using Name & Key.
4. Check the attched storage account's Properties panel.

**Expect Experience:**
'Permissions' is translated on Properties panel.

**Actual Experience:**
'Permissions' is not translated on Properties panel.
![image](https://user-images.githubusercontent.com/41351993/65682991-bbaa7880-e08e-11e9-8204-dddf137d6622.png)

**More Info:**
This issue also reproduces for one SAS attached services.

**Comment by craxal** [comment]
Hard-coded string.
