### ISSUE TITLE
An error dialog pops up when detaching one attached item

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1933]
**Storage Explorer Version:** 1.10.1
**Build:** [20190926.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3084119)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Language:** Chinese (zh-TW) / Chinese (zh-CN)
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer using the command 'StorageExplorer.exe --lang=zh-CN'.
2. Attach one blob container using SAS.
3. Try to detach the attached blob container.

**Expect Experience:**
  No error occurs and detach successfully.

**Actual Experience:**
  An error dialog pops up.
![image](https://user-images.githubusercontent.com/41351993/65683564-1bedea00-e090-11e9-9158-06d6c0c27bb9.png)

**More Info:**
1. This issue reproduces for one **SAS attached item**.
2. This issue reproduces for one **Name & Key attached storage account**.
3. This issue reproduces for one **Azure AD attached blob container**.
4. This issue reproduces for the **account attached via local emulator**.(Emulator version:5.10.0.0).

**Comment by craxal** [comment]
The error appears to be in the translated string:

```
"MessageConfirmDetachResource": "确定要断开资源 \"%S\" 吗?",
```

The "S" here should be lowercase, not capitalized.

**Comment by lukaschal** [comment]
Fixed.

**Comment by v-xianya** [comment]
This issue has been fixed on build 20191009.1. So we close it.
