### ISSUE TITLE
'Third Party Notices' under Help menu is not localized

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1934]
**Storage Explorer Version:** 1.10.1
**Build:** [20190926.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3084119)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Language:**  Chinese (zh-CN)/ Chinese (zh-TW) 
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer using the command 'StorageExplorer.exe --lang=zh-CN'.
2. Click the localized menu 'Help' -> Check its dropdown list.

**Expect Experience:**
'Third Party Notices' is localized.

**Actual Experience:**
'Third Party Notices' is not localized.
![image](https://user-images.githubusercontent.com/41351993/65683885-00371380-e091-11e9-9c40-97dfb5ca48e0.png)

**Comment by craxal** [comment]
Existing string translated, but forgot to swap out hard-coded string.
