### ISSUE TITLE
The contents of 'Release Notes' are not localized

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1935]
**Storage Explorer Version:** 1.10.1
**Build:** [20190926.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3084119)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Language:** Chinese (zh-TW) / Chinese (zh-CN)
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer using the command 'StorageExplorer.exe --lang=zh-CN'.
2. Go to localized 'Help' menu -> Select the localized 'View Release Notes'.
3. Check whether the contents of 'Release Notes' are localized or not.

**Expect Experience:**
The contents of 'Release Notes' are localized.

**Actual Experience:**
The contents of 'Release Notes' are not localized.

**Comment by MRayermannMSFT** [comment]
We're choosing to not translate the release notes.
