### ISSUE TITLE
'Yes' and 'No' are not localized on delete blob container dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1936]
**Storage Explorer Version:** 1.10.1
**Build:** [20190926.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3084119)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Language:** Chinese (zh-TW) / Chinese (zh-CN)
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer using the command 'StorageExplorer.exe --lang=zh-CN'.
2. Expand a storage account -> Blob Containers.
3. Select one blob container then try to delete it.
4. Check the prompt dialog.

**Expect Experience:**
'Yes' and 'No' are localized.

**Actual Experience:**
'Yes' and 'No' are not localized.
![image](https://user-images.githubusercontent.com/41351993/65684881-45f4db80-e093-11e9-8325-8184ad12b350.png)

**More Info:**
1. This issue also reproduces for one file share/ queue/ table.
2. This  issue also reproduces for one file under one file share.

**Comment by craxal** [comment]
The "in storage account" piece is also not localized. We need to add a new string for translation.

**Comment by v-xianya** [comment]
This issue has been fixed on build 20191009.1. So we close it.
