### ISSUE TITLE
'Search by prefix (case-sensitive)' is not localized in blob container's editor

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1937]
**Storage Explorer Version:** 1.10.1
**Build:** [20190926.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3084119)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Language:** Chinese (zh-TW) / Chinese (zh-CN)
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer using the command 'StorageExplorer.exe --lang=zh-CN'.
2. Expand a non-ADLS Gen2 storage account -> Blob Containers.
3. Create one blob container and check its editor.

**Expect Experience:**
'Search by prefix(case-sensitive)' is localized.

**Actual Experience:**
'Search by prefix(case-sensitive)' is not localized.
![image](https://user-images.githubusercontent.com/41351993/65685278-34600380-e094-11e9-9241-7e89619c0597.png)

**More Info:**
This issue also reproduces for one file share.

**Comment by craxal** [comment]
Blob extension package version needs to be updated.
