### ISSUE TITLE
Path does not exist error on renaming after renaming a sub folder

### ISSUE THREAD

**Issue by gauravkhuraana** [microsoft/AzureStorageExplorer#1938]
https://test.core.windows.net/test/main/sub/test123

Rename the folder test123 and press enter

System gives the below error in latest version 

![image](https://user-images.githubusercontent.com/15048211/65675015-19c56480-e06b-11e9-80b0-824985379630.png)

**Comment by jinglouMSFT** [comment]
What was the error?  I tried this on 1.10.1 with and without AzCopy being enabed.  Both worked fine. Can you elaborate a bit more on what exactly you did? Thanks.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
