### ISSUE TITLE
An error dialog occurs when trying to add metadata for one blob 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1939]
**Storage Explorer Version:** 1.10.1
**Build:** [20190926.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3084119)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Language:** Chinese (zh-CN)/ Chinese (zh-TW) 
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer using the command 'StorageExplorer.exe --lang=zh-CN'.
2. Expand one non-ADLS Gen2 account -> Blob Containers.
3. Create a blob container -> Upload a blob -> Open its context menu
4. Right click the uploaded blob and select 'Properties...'.
5. Add metadata -> Click 'Save'.
6. Check the result.

**Expect Experience:**
Add metadata successfully.

**Actual Experience:**
An error dialog occurs. 
![image](https://user-images.githubusercontent.com/41351993/65685787-658d0380-e095-11e9-818f-4ab8f2a7d2f2.png)

**More Info:**
This issue also reproduces for one file under one file share.

**Comment by MRayermannMSFT** [comment]
Fixes merged into master.
