### ISSUE TITLE
Thinks subscription is not selected if try to navigate to a storage account which has not been loaded yet

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/AzureStorageExplorer#194]
From https://github.com/Microsoft/vscode-azurestorage/issues/142
Related to #25 (but different outcome)

**Storage Explorer Version**: 1.1

#### Steps to Reproduce: ####

Platform: Mac/Windows/Linux

Repro Steps:
Right click one storage account and check the context menu.

Expect:
Display 'Refresh'.

Actual:
No 'Refresh' item displays.
![no-refresh](https://user-images.githubusercontent.com/34729092/39860755-074bfbea-542e-11e8-9889-366ec1db6dd3.PNG)

More Info:
The 'Refresh' refreshes the applied subscriptions actually.
![refresh](https://user-images.githubusercontent.com/34729092/39860763-0caa288c-542e-11e8-806d-0165d1cd1a86.PNG)

**Comment by MRayermannMSFT** [comment]
Looks like this was fixed some time ago. Closing. 😄
