### ISSUE TITLE
Extra square brackets show for localized tooltip 'Open Connect Dialog'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1940]
**Storage Explorer Version:** 1.10.1
**Build:** [20190926.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3084119)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Language:** Chinese (zh-TW)
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer using the command 'StorageExplorer.exe --lang=zh-TW'.
2. Check the tootip of the 'Plug' icon in the left column of Storage Explorer.

**Expect Experience:**
Extra square brackets show for the tooltip.

**Actual Experience:**
No square brackets show for the tooltip.
![image](https://user-images.githubusercontent.com/41351993/65686517-5eff8b80-e097-11e9-9802-fa78856e82b5.png)

**More Info:**
This issue doesn't reproduce in Chinese(zh-CN).

**Comment by lukaschal** [comment]
On review.

File: loc\en\src\Standalone\resources\Shell.json
ID: 0; "LabelConnectButton"
SRC: Open Connect Dialog
開啟 [連線] 對話方塊

**Comment by lukaschal** [comment]
@v-xianya Please close, this is "by design".

**Comment by v-xianya** [comment]
Hi @lukaschal Thanks for your updates!
