### ISSUE TITLE
An odd 'Blob' shows on Generate Shared Access Signature dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1941]
**Storage Explorer Version:** 1.10.1
**Build:** [20190926.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3084119)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Language:**  Chinese (zh-CN) /Chinese (zh-TW) 
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer using the command 'StorageExplorer.exe --lang=zh-CN'.
2. Select one storage account -> Open 'Generate Shared Access Signature' dialog.
3. Check the Services part.

**Expect Experience:**
Show localized 'Blobs'.

**Actual Experience:**
An odd 'Blob' shows on 'Generate Shared Access Signature' dialog
![image](https://user-images.githubusercontent.com/41351993/65686611-cddce480-e097-11e9-9426-c851c01a8bf3.png)

**More Info:**
![image](https://user-images.githubusercontent.com/41351993/65686763-8a36aa80-e098-11e9-91e6-72f0c2908d06.png)

**Comment by lukaschal** [comment]
On implementation.

**Comment by lukaschal** [comment]
These translations are correct as they are. No change is needed. In some languages they translating "Blobs" as "Blob".

**Comment by jinglouMSFT** [comment]
Can you please verify 'Blob' is used through the entire product of zh-CN?  
In traditional Chinese, I noticed that some places 'blob' is used and some places 'Blob' is used.

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
Fixed on CHS few days ago.
