### ISSUE TITLE
'Rename' & 'Delete' & 'Undelete' & 'Break Lease' dialogs are not localized

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1942]
**Storage Explorer Version:** 1.10.1
**Build:** [20190926.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3084119)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Language:** Chinese (zh-TW) / Chinese (zh-CN)
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer using the command 'StorageExplorer.exe --lang=zh-CN'.
2. Expand storage account -> Blob Containers.
3. Create a new blob container -> Upload one blob.
4. Check the 'Rename' & 'Delete' & 'Undelete' & 'Break Lease' dialogs.

**Expect Experience:**
'Rename' & 'Delete' & 'Undelete' & 'Break Lease' dialogs are localized.

**Actual Experience:**
'Rename' & 'Delete' & 'Undelete' & 'Break Lease' dialogs are not localized.

**More Info:**
1. This issue also reproduces on 'Set Container Public Access Level' dialog for one blob container.
2. This issue also reproduces on 'Copy Conflict' & 'File Changes Detected' dialog for blobs/files.
![image](https://user-images.githubusercontent.com/41351993/65686921-87888500-e099-11e9-9e62-b24e75fd592b.png)
![image](https://user-images.githubusercontent.com/41351993/65686926-92dbb080-e099-11e9-98fa-1cf55d263675.png)
3. The prompt dialog is not localized when creating a new file share with an invalid name.
4. This issue also reproduces for one blob container/file share/table/queue.
5. This issue also reproduces when using an invalid name to rename one file share/blob container/ table.
6. This issue also reproduces when no permission to operate one attached items.

**Comment by lukaschal** [comment]
Are these strings exposed to localization ?

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer?path=%2Fsrc%2FStandalone%2Fapp%2Frenderer%2FJobHandlers%2FBlob%2FGroupCopy%2FState%2FBlobGroupCopyContext.ts&version=GBmaster

**Comment by JasonYeMSFT** [comment]
@lukaschal, we plan to deprecate this copy/paste conflict resolution dialog as we migrate to use AzCopy as our default blob transfer method. There will be a new localized conflict resolution dialog for that part.
