### ISSUE TITLE
Dialog titles are not localized

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1943]
**Storage Explorer Version:** 1.10.1
**Build:** [20190926.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3084119)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Language:** Chinese (zh-TW) / Chinese (zh-CN)/ Japanese/ Korean/ German/ French/ Spanish
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer using the command 'StorageExplorer.exe --lang=zh-CN'.
2. Expand one storage account -> Blob Containers.
3. Create a new blob container -> Click 'Upload' -> 'Upload Files...'.
4. Check the upload dialog.

**Expect Experience:**
The Upload dialog's title is localized.

**Actual Experience:**
The Upload dialog's title is not localized.
![image](https://user-images.githubusercontent.com/41351993/65687590-3037e400-e09c-11e9-9411-6b689f1ffcc3.png)

**More Info:**
1. This issue also reproduces for **View Message** & **Add Message** dialog.
2. This issue also reproduces for **Connect** dialog.
3. This issue also reproduces for **Manage Access Policies** dialog.
4. This issue also reproduces for **Properties** dialog.
5. This issue also reproduces for **Rename** dialog for one blob container/ file share.
6. This issue also reproduces for **Generate Shared Access Signature** dialog.
7. This issue also reproduces for **CORS Settings** dialog.
8. This issue also reproduces for **Manage Access** dialog.
9. This issue also reproduces for one **Connect to Data Lake Store** dialog.
10. This issue also reproduces for one **Configure Soft Delete Policy** dialog.
11. This issue also reproduces for **Connect to Cosmos DB** dialog.
12. This issue also reproduces for **Add Entity** & **Edit Entity** & **Select Columns** dialog.
13. This issue also reproduces for **Feedback Survey** dialog.

**Comment by lukaschal** [comment]
Non-localizable for now.

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer?path=%2Fsrc%2Fcomponents%2Fse-az-copy-extension%2Fsrc%2FDialogs%2FUploadBlobs%2FUploadBlobsView.html&version=GBmaster

**Comment by craxal** [comment]
Dialog framework has been updated so that the dialog title bar uses the same text as the header in the dialog content window.

**Comment by v-limu** [comment]
**More Info:**
This issue also reproduces for 'Restore Files' dialog.
![image](https://user-images.githubusercontent.com/54055206/74518584-1285f100-4f4f-11ea-9c79-fe07de1c7d6b.png)

**Comment by craxal** [comment]
@v-limu This issue was used to track dialog title in general. If this is a specific case, please log it as a new issue so that we can better track it.

**Comment by v-limu** [comment]
Hi @craxal Thanks! logged this as a new issue:[2673](https://github.com/microsoft/AzureStorageExplorer/issues/2637)
