### ISSUE TITLE
'Connect to Data Lake Storage Gen1… ' is not localized

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1944]
**Storage Explorer Version:** 1.10.1
**Build:** [20190926.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3084119)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Language:** Chinese (zh-TW) / Chinese (zh-CN)
**Regression From:** Not a regression
**Steps to reproduce:**
1. Launch Storage Explorer using the command 'StorageExplorer.exe --lang=zh-CN'.
2. Right click 'Data Lake Storage Gen1 (Preview)' node.
3. Check its context menu.

**Expect Experience:**
'Connect to Data Lake Storage Gen1… ' is localized.

**Actual Experience:**
'Connect to Data Lake Storage Gen1… ' is not localized.
![image](https://user-images.githubusercontent.com/41351993/65688388-a0933500-e09d-11e9-86cd-f7cdc52add11.png)

**More Info:**
1. This issue also reproduces for one Cosmos DB account.
![image](https://user-images.githubusercontent.com/41351993/65688413-aab53380-e09d-11e9-9621-d507bb6731f1.png)
2. There two actions are not localized on context menu of one Cosmos DB account.
![image](https://user-images.githubusercontent.com/41351993/66560672-6b511180-eb8a-11e9-82bf-d0c1ccb95130.png)
3. The property 'Configuration Override' is not localized on Cosmos DB account Properties panel.
![image](https://user-images.githubusercontent.com/41351993/66561436-0d252e00-eb8c-11e9-806a-b197907ddf7f.png)

**Comment by lukaschal** [comment]
Not occurs in localizable  resources for now.

https://devdiv.visualstudio.com/DevDiv/_git/CloudExplorer?path=%2Fsrc%2FCloudHub%2Fts%2FProviders%2FAzure%2FConfig%2FAzureDocumentDBAccountResourceTypeConfig.ts&version=GBmaster

                    displayName: {
                        value: "Connect to Cosmos DB..." // Localize
                    },
                    icon: AzureConstants.imagePaths.DocumentDBAccountsIcon,
                    themeSrc: AzureConstants.imageThemeSrc.DocumentDBAccountsIcon,
                    isDefault: false,
                    visible: {
                        value: Utilities.isRunningOnElectron()
                    },
                    namespace: "Azure.Actions.DocumentDB.connectAccount"
                },
                {
                    displayName: {
                        value: "Connect to Cosmos DB Emulator..." // Localize
                    },
                    icon: AzureConstants.imagePaths.DocumentDBAccountsIcon,
                    themeSrc: AzureConstants.imageThemeSrc.DocumentDBAccountsIcon,
                    isDefault: false,
                    visible: {
                        value: Utilities.isRunningOnElectron()
                    },
