### ISSUE TITLE
'Next' & 'Cancel' are not localized on Connect to Cosmos DB dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1945]
**Storage Explorer Version:** 1.10.1
**Build:** [20190926.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3084119)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Language:** Chinese (zh-TW) / Chinese (zh-CN)
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer using the command 'StorageExplorer.exe --lang=zh-CN'.
2. Right click 'Cosmos DB Accounts (Preview)' -> Select 'Connect to Cosmos DB'.
3. Check the prompt dialog.

**Expect Experience:**
'Next' & 'Cancel' are localized.

**Actual Experience:**
'Next' & 'Cancel' are not localized.
![image](https://user-images.githubusercontent.com/41351993/65688717-2d3df300-e09e-11e9-8393-3a81b69dd395.png)

**Comment by lukaschal** [comment]
Please confirm, are these buttons exposed to localization ?

**Comment by craxal** [comment]
They are, but the dialog panels here aren't setting the button text. They're just using the default, hard-coded text.

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
