### ISSUE TITLE
'Add' is not translated on Manage Access dialog for one ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1946]
**Storage Explorer Version:** 1.10.1
**Build:** [20190926.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3084119)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Language:** Chinese (zh-TW) / Chinese (zh-CN)
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer using the command 'StorageExplorer.exe --lang=zh-CN'.
2. Expand one ADLS Gen2 storage account -> Blob Containers.
3. Right click one blob container -> Select 'Manage Access...'.
4. Check the 'Mange Access' dialog.

**Expect Experience:**
 'Add' is translated.

**Actual Experience:**
Add' is not translated.
![image](https://user-images.githubusercontent.com/41351993/65689220-2368bf80-e09f-11e9-85e1-14bbee40ea87.png)

**More Info:**
1. The strings Other & Mask on the dialog are not translated.
2. This issue also reproduces on 'Update Access Tier' dialog for one Storagev2 account.

![image](https://user-images.githubusercontent.com/41351993/65689388-9114eb80-e09f-11e9-9db8-fe26178bc733.png)

**Comment by MRayermannMSFT** [comment]
Do translate: the buttons
Don't translate: Mask and Other, Hot and Cool

**Comment by lukaschal** [comment]
These two buttons translated at 10/3/2019.

File: loc\en\src\components\se-adls2-extension\resources\ManagePosixAcl.json
ID: 0; "LabelAdd"
SRC: Add
TGT: 添加

File: loc\en\src\components\se-az-copy-extension\resources\Copy.json
ID: 0; "ApplyToOneConflictButton"
SRC: Apply
TGT: 应用

**Comment by MRayermannMSFT** [comment]
Both dialogs are now using localizeable strings. Any further bugs for them should be new "translation" bugs.
