### ISSUE TITLE
Total Record Count For Tables

### ISSUE THREAD

**Issue by chrismid75** [microsoft/AzureStorageExplorer#1947]
In Storage Explorer When viewing blobs or tables I'd like to be able to see the total number of Blobs or Rows contained within either the account or subfolder. Currently to get a total count I have to load all records in to cache with for millions of records is just not possible

**Describe the solution you'd like**
I'd like to be able to right click on either the table / blob container and click properties. This will then show me a windows explorer style dialog box with total records and possible total size

**Describe alternatives you've considered**
Only option i can see is powershell (if you have coding knowledge)

**Comment by MRayermannMSFT** [comment]
@chrismid75 have you tried using the "selection statistics" action when viewing a blob container?

**Comment by MRayermannMSFT** [comment]
This feature is already available for blobs via the "selection statistics" button. Please try using that. As for doing it for tables, we wouldn't add this feature to that at this time.
