### ISSUE TITLE
View Ticks as Date & Time

### ISSUE THREAD

**Issue by SndrSchnklshk** [microsoft/AzureStorageExplorer#1948]
First of all; I really like the storage explorer, great work! 

Currently I work a lot with the table-explorer and the data I'm using contains lots of (different) date fields. Mostly stored as ticks (Int64, .NET Ticks, e.g: 637052256000000000).

I would like to request a very simple feature that shows the ticks in a human readable date (+time) for example; when I move my mouse over a Int64 cell in the grid and it looks like .NET datetime ticks (>=599266080000000000, 1/1/1900) it shows the hint: "9/28/2019 12:00:00 AM". See screenshot below:

![hint_example](https://user-images.githubusercontent.com/35453771/65738818-c0663f80-e115-11e9-8ce9-48e9ce19907c.png)

Currently I have to copy paste and convert it to get the date & time and that is somehow time consuming.

It would be nice as UNIX timestamps are also supported.

...oh, yes, making a new tool myself, only for this feature is possible but sounds a bit like overkill to me :)

Thanks.

**Comment by craxal** [comment]
I'm afraid such feature just isn't tractable. There are a few problems that would need to be solved:
* Different users have different data practices. There's no general way to tell for sure if an `Int64` value is meant to represent a date/time of some kind.
* Not everyone uses the same format. There's no general way to tell what kind of date/time format a value represents (.NET tick, UNIX timestamp, Julian day, etc.). Some formats have more complex encoding/decoding processes.

Generally speaking, if you're storing data in an Azure Table that's meant to represent a specific point in time, you should use a DateTime property.

We are starting some initial investigations into the possibility of bringing some user-customizable functionality into Storage Explorer by allowing users to kick off an Azure Function (see earlier comments). With this feature, you could theoretically execute an Azure Function from Storage Explorer that converts or copies integer values you know represents some kind of date/time into a proper DateTime field.

**Comment by SndrSchnklshk** [comment]
Thanks for looking in to it. No problem at all, since this was a feature request back in 2019 :)
