### ISSUE TITLE
Renaming a blob displays the default account tier after changing the blob tier 

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#195]
**Storage Explorer Version**: 1.1.0

**Platform**: Windows/Linux/Mac

**Architecture**: ia32/x64

**Build Number**: 20180516.1

**Commit**: e0a60be3

**Regression From**: Not a regression

#### Steps to Reproduce: ####

1. Launch Storage Explorer and Select one GPv2/Blob account. 
2. Set the default Access Tier for the account as 'Cool'. 
3. Open one blob container -> Upload one block blob named 'test.txt' -> Make sure the Access Tier of the blob is 'Cool(inferred)'.
4. Change the blob access tier to 'Hot'.
5. Rename the blob.

#### Expected Experience: ####
 The blob tier still displays as 'Hot' after renaming successfully.

#### Actual Experience: ####
The blob tier displays as the default account tier 'Cool(inferred)'.
![rename_tier](https://user-images.githubusercontent.com/34729022/40223401-7f44ed1a-5a72-11e8-9057-4d506ea0f1e6.png)

**Comment by JakeRadMSFT** [comment]
Since a rename is actually creating a new file, the value doesn't carry over.

**Comment by JakeRadMSFT** [comment]
I think this is more of a service ask, since we're doing a server side copy.
