### ISSUE TITLE
Get a wrong URL for the renamed directory in file share

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1952]
**Storage Explorer Version:** 1.10.1
**Build:** [20190927.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3088411&view=logs)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> File Shares.
2. Create a file share then create a new directory with default name 'New Directory'.
3. Rename the directory's name from 'New Directory' to 'test'.
4. Right click the renamed directory -> Select 'Copy URL'.

**Expect Experience:**
Get a correct URL. 
https://2uh2fx7n5d4eu100.file.core.windows.net/testfile/test/

**Actual Experience:**
Get a wrong URL.
https://2uh2fx7n5d4eu100.file.core.windows.net/testfile/t

**More Info:**
This issue doesn't reproduce when refreshing the directory after renamed.

**Comment by MRayermannMSFT** [comment]
Uncommon user scenario.
