### ISSUE TITLE
The behavior is different between Storage Explorer and Portal when inputting message with unicode characters

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1953]
**Storage Explorer Version:** 1.10.1
**Build:** [20190927.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3088411&view=logs)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand a storage account -> Queues.
2. Open a queue and click 'Add Message'.
3. Input Unicode characters like '你好'.
4. Add the same message ''你好' to queue in Portal.
5. Check the behavior between Storage Explorer and Portal.

**Expect Experience:**
The behavior is same between Storage Explorer and Portal.

**Actual Experience:**
The behavior is different between Storage Explorer and Portal.
![image](https://user-images.githubusercontent.com/41351993/65753323-5c597080-e141-11e9-8b66-86c1cea75f1b.png)

**Comment by MRayermannMSFT** [comment]
@v-xianya are you referring to whether or not the checkbox is checked by default?

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT 
In portal
1. 'Encode the message body in Base64' is **unchecked by default**.
2. 'Encode the message body in Base64' **becomes disabled** when inputting '你好'.

In Storage Explorer
1. 'Encode the message body in Base64' is **checked by default**.
2. 'Encode the message body in Base64' still **shows enabled** when inputting '你好'.
