### ISSUE TITLE
The opened tab is auto closed after pasting a blob container to another account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1954]
**Storage Explorer Version:** 1.10.1
**Build:** [20190927.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3088411&view=logs)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Create a new blob container and make sure one tab is opened.
3. Copy the blob container to another account.
4. Check the tab is opened or not.

**Expect Experience:**
The tab is opened.

**Actual Experience:**
The tab is closed.

**More Info:**
This issue also reproduces for one file share/ table.

**Comment by MRayermannMSFT** [comment]
Won't fix pending any customer reports for this bug.
