### ISSUE TITLE
The 'Partition Key' tab can't be dragged to change the column order in table editor

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1955]
**Storage Explorer Version:** 1.10.1
**Build:** [20190927.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3088411&view=logs)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Tables.
2. Open a table.
3. Drag the 'Partition Key' tab to change the column order.

**Expect Experience:**
The 'Partition Key' can be dragged to change the column order in the table editor.

**Actual Experience:**
The 'Partition Key' tab can't be dragged to change the column order in the table editor.

**More Info:**
1. Other columns can be dragged to change the column order in table editor.
2. The order can be changed in 'Column Options' dialog by moving down the 'Partition Key' column.

**Comment by MRayermannMSFT** [comment]
Partition key is not movable by design.
