### ISSUE TITLE
Can't focus on the renamed item after renaming it successfully

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1956]
**Storage Explorer Version:** 1.10.1
**Build:** [20190927.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3088411&view=logs)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> File Shares.
2. Open a file share including more than three files.
3. Select a file/folder and rename it.
4. Check the view in right side after renaming successfully.

**Expect Experience:**
The renamed item has been focused. 

**Actual Experience:**
The 'File Shares' node has been focused.

**More Info:**
This issue also reproduces for one blob container/ table.

**Comment by JasonYeMSFT** [comment]
In our testing, we see the focus go to the first item in the right hand side instead of going to the Tree node. Can you verify this in 1.11.0?

**Comment by v-xianya** [comment]
Hi @JasonYeMSFT 
Verified this issue in 1.11.0. 
It did focus on the first item in the right hand side😊
