### ISSUE TITLE
The items disappear after deleting one sub-item under 'Search from Quick Access' node 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#1957]
**Storage Explorer Version:** 1.10.1
**Build:** [20190927.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3088411)
**Branch:** master
**Platform/OS:** Windows 10/ Ubuntu Linux 18.04/Mac OS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Select a storage account -> Right click it and add to Quick Access.
2. Right click the Quick Access -> Click 'Search from Here'. 
3. Expand this storage account -> Blob Containers -> Create a new blob container and delete it.
4. Check whether the QA items display or not.

**Expect Experience:**
The QA items display well.
![image](https://user-images.githubusercontent.com/54055206/65759124-d80cea80-e14c-11e9-877c-c4f2e8b4fad8.png)

**Actual Experience:**
The QA items disappear.
![image](https://user-images.githubusercontent.com/54055206/65759086-c297c080-e14c-11e9-8301-23792f1d2b2f.png)

**More Info:**
This issue reproduces for actions 'Rename/ Delete/ Add to Quick Access'.

**Comment by MRayermannMSFT** [comment]
Won't fix. Uncommon user scenario.

**Comment by MRayermannMSFT** [comment]
Probably fixed now in 1.29 given the work done for issue #6393
