### ISSUE TITLE
Disable the no permitted actions for 'Archive' blob

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#196]
**Storage Explorer Version**: 1.1.0

**Platform**: Windows/Linux/Mac

**Architecture**: ia32/x64

**Build Number**: 20180516.1

**Commit**: e0a60be3

**Regression From**: Not a regression

#### Steps to Reproduce: ####

1. Launch Storage Explorer and Select one GPv2/Blob account. 
2. Open one blob container and upload a block blob.
3. Change the blob tier to 'Archive'.
4. Check the context menu for the 'Archive' blob.

#### Expected Experience: ####
No permitted actions like 'Open/Download/Create Snapshot' are disabled.

#### Actual Experience: ####
No permitted actions like 'Open/Download/Create Snapshot' are enabled.
![disable](https://user-images.githubusercontent.com/34729022/40223985-546a5dc6-5a74-11e8-92e5-8107d3819443.png)

**Comment by MRayermannMSFT** [comment]
Closing as won't fix.
