### ISSUE TITLE
Azurite Connection Error

### ISSUE THREAD

**Issue by justinyoo** [microsoft/AzureStorageExplorer#1973]
**Storage Explorer Version**: `1.10.1`
**Build Number**: `20190919.2`
**Platform/OS**: `Windows 10 18362`
**Architecture**: `x64`
**Regression From**:  Updated from 1.9.1. 1.9.1 wasn't working either.

## Bug Description ##

I wanted to connect the [`Azurite`](https://github.com/Azure/Azurite) emulator through Azure Storage Explorer. I followed the [instruction](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite#storage-explorer), but it showed the error message like below:

![image](https://user-images.githubusercontent.com/1538528/65825123-6650b000-e2b6-11e9-8ebe-0752e7731821.png)

My Azurite version was [`3.2.0-preview`](https://www.npmjs.com/package/azurite).

I ignored the error message and was able to create a blob container, upload files to the container, and download the file from the container. However, as soon as I reloaded the list of blob containers by clicking the `Load more` button, it threw the same error.

## Steps to Reproduce ##

1. Install Azurite
    ```
    npm install -g azurite
    ```
1. Run Azurite
    ```
    azurite --silent --location c:\azurite --debug c:\azurite\debug.log
    ```
1. Open Storage Explorer
1. Click the plug button at the left-hand side to connect Azurite
1. Select `Attach to a local emulator`
1. Click `Next`
1. Leave everything as default
1. Click `Next`
1. Click `Connect`

## Expected Experience ##

The error pop-up shouldn't be appearing.

## Actual Experience ##

This error modal popped up
![image](https://user-images.githubusercontent.com/1538528/65825123-6650b000-e2b6-11e9-8ebe-0752e7731821.png)

## Additional Context ##

N/A

**Comment by MRayermannMSFT** [comment]
@justinyoo , do you know the names of the containers you've created in Azurite? Or have you not made any yet?

**Comment by justinyoo** [comment]
@MRayermannMSFT Now, I found out what the problem was.

When I manually created a blob container with a name of `mycontainer`, it was OK.

When I locally ran an Azure Functions project with the command, `func host start`, it automatically created another container of `azure-webjobs-hosts`. As soon as I got this container, the Storage Explorer threw the error. This time I got this error:

![image](https://user-images.githubusercontent.com/1538528/65924592-d3885080-e430-11e9-9f96-1cd44cc0b1e8.png)

So... at least we found the root cause. As far as I know, the container name should be alphanumeric. If this is the case, Azure Functions team may have to change their logic.

**Comment by justinyoo** [comment]
@MRayermannMSFT I just downgraded the npm package to `2.7.1` and it works perfectly fine. Soooo apparently the preview version needs to fix this issue.

**Comment by jinglouMSFT** [comment]
BTW, azure-webjobs-hosts is a valid container name.  hyphen is allowed to be in a container name as long as it's not two consecutive hyphens, or begin or end with hyphens.

**Comment by jinglouMSFT** [comment]
Please feel free to open a new issue if you run into additional problems, but for now I am going to close this issue.
