### ISSUE TITLE
Collections created via Entity Framework Core CosmosDB provider seem empty

### ISSUE THREAD

**Issue by xtellurian** [microsoft/AzureStorageExplorer#1974]
**Storage Explorer Version**: 1.10.1
**Build Number**: 20190919.2 
**Platform/OS**: MacOS
**Architecture**: x64
**Regression From**:  Unsure

## Bug Description ##
Documents in Cosmos DB are not shown when collection is created and populated by Entity Framework Core.

## Steps to Reproduce ##
1. Create a collection + populate collection using Entity Framework Core, C# and the CosmosDB provider.

## Expected Experience ##
* Documents created in this process are visible in the Storage Explorer

## Actual Experience ##
* List of documents appears empty. The documents are visible in the Azure Portal, cosmos Data Explorer.

Screenshot of Azure Portal Data Explorer:
<img width="551" alt="image" src="https://user-images.githubusercontent.com/8497130/65842048-f3097580-e36b-11e9-8a16-a2c71bef23ef.png">

Screenshot of Storage Explorer (same collection etc.):
<img width="392" alt="image" src="https://user-images.githubusercontent.com/8497130/65842060-01579180-e36c-11e9-87f6-29430d04dc50.png">

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
