### ISSUE TITLE
Acess Control Management to multiple files

### ISSUE THREAD

**Issue by denilsongrupp** [microsoft/AzureStorageExplorer#1988]
I needed to access multiple files from one folder. I didn't have read access, so I had to give 48 permissions instead of one, unbelievable !!!!!!!!!!! Please create something to grant permission for multiple files.

**Comment by craxal** [comment]
@denilsongroup Can you clarify a bit what you're asking about? Are you referring to managing permissions for ADLS Gen2 blobs and folders?

**Comment by MRayermannMSFT** [comment]
With Gen2 ACLs, if you set a default on the parent, then children created after setting the default will have matching permissions. But if you made the children prior, then unfortunately you'll need to set them 1 by 1. The platform team is aware of the feature request to recursively set permissions. We'll pass your feedback along to them.

**Comment by MRayermannMSFT** [comment]
Duplicate of #1380
