### ISSUE TITLE
Bring Back old Column Order 

### ISSUE THREAD

**Issue by ramkmp** [microsoft/AzureStorageExplorer#1989]
The column order of the Azure Tables were changed and the timestamp is now appearing based on sorted column names. This was so annoying as I usually sort by timestamp and fetch most recent records. 

Same goes to Export as all the column order are changed by column name sort.

Please bring back the original order PartitionKey, RowKey, TimeStamp, followed other columns, or provide an option to change the order and store that settings.

**Comment by craxal** [comment]
Duplicate of #1918.
