### ISSUE TITLE
The second added account doesn't auto display in Account Panel

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#199]
**Storage Explorer Version**: 1.1.0

**Platform**: Windows/Linux/Mac

**Architecture**: ia32/x64

**Build Number**: 20180520.2

**Commit**: 713c27c5

**Regression From**: Not a regression

#### Steps to Reproduce: ####

1.  Launch Storage Explorer and add one account.
2. Open Manage Account Panel and add the second account.
3. Check whether the Account Panel is auto refreshed or not.

#### Expected Experience: ####
The second account auto displays in Account Panel.

#### Actual Experience: ####
The Account Panel isn't auto refreshed.

#### More info: ####
This issue doesn't reproduce when doesn't open the Account Panel.

**Comment by MRayermannMSFT** [comment]
Hey @v-xuanzh , I can no longer get this to repro. I think this may have been already fixed. Can you try again with a more recent build, and then reopen if you can repro. Thanks!

**Comment by v-xuanzh** [comment]
Ok, we will reopen this issue if it still reproduce on recent builds.
