### ISSUE TITLE
unable to verify the first certificate

### ISSUE THREAD

**Issue by alexgman** [microsoft/AzureStorageExplorer#1991]
**Version: 1.10.1
AzCopy Version: 10.2.1
Platform: Windows
Architecture: ia32 
Build Number: 20190919.2 
Commit: 868c6dff1 
Support ID: 53e4cd95-f15a-82cb-9cb5-2e099058571f** 

## Bug Description ##
When attempting to browse in my `gen1` account, I am getting this error:
![image](https://user-images.githubusercontent.com/4227695/66143187-5bef2880-e5cc-11e9-8ce3-9276415c91c1.png)

## Steps to Reproduce ##
go to browse one of your `gen1` accounts in storage explorer
![image](https://user-images.githubusercontent.com/4227695/66143259-775a3380-e5cc-11e9-8b24-9d80bd29f04f.png)

![2019-10-03_10-58-24](https://user-images.githubusercontent.com/4227695/66143495-da4bca80-e5cc-11e9-8b7b-a5edd7d6e04e.gif)

**Comment by craxal** [comment]
@alexgman Have you gone our [troubleshooting guide](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C1904#error-self-signed-certificate-in-certificate-chain-and-similar-errors)?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of reply.
