### ISSUE TITLE
Infobar buttons are not localized

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#1993]
**Storage Explorer Version**: 1.11.0 (prerelease)
**Build Number**: 20191002.6
**Platform/OS**: All

![image](https://user-images.githubusercontent.com/3473026/66155420-70372380-e5d4-11e9-9763-ae5f5effb2d8.png)

![image](https://user-images.githubusercontent.com/3473026/66156353-5c8cbc80-e5d6-11e9-8658-7635ffd94b62.png)

**Comment by lukaschal** [comment]
Hard-coded string.

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer?path=%2Fsrc%2FStandalone%2Fapp%2Frenderer%2FUserAccountManagement%2FIdentityUserAccountsManager.ts&version=GBmaster

**Comment by MRayermannMSFT** [comment]
Hardcoded strings have been replaced. Just waiting on messages to be loc'd now. Closing.

**Comment by craxal** [comment]
Keeping the issue open until we've verified the strings are translated and display well in the app.

**Comment by lukaschal** [comment]
Localizable now. On translation.

File: loc\en\src\Standalone\resources\Shell.json
ID: 0; "MessageAccountsNeedReauth"
SRC: One or more accounts requires reauthentication.

**Comment by lukaschal** [comment]
Localized at 10/17.

**Comment by MRayermannMSFT** [comment]
Verified.
![image](https://user-images.githubusercontent.com/21112697/67461135-7e83c880-f5f1-11e9-8cef-29922a6836fa.png)
