### ISSUE TITLE
Emulator node is not localized

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#1994]
**Storage Explorer Version**: 1.11.0 (prerelease)
**Build Number**: 20191002.6
**Platform/OS**: All

![image](https://user-images.githubusercontent.com/3473026/66155559-c86e2580-e5d4-11e9-88c3-846e89671a6c.png)

**Comment by lukaschal** [comment]
Hard-coded string.

https://devdiv.visualstudio.com/DevDiv/_git/CloudExplorer?path=%2Fsrc%2FCloudHub%2Fts%2FProviders%2FAzure%2FProducers%2FAzureStorageProducer.ts&version=GBmaster

**Comment by JasonYeMSFT** [comment]
We have merged the english string for this. @lukaschal

**Comment by lukaschal** [comment]
New string added at 10/11/2019.

File: loc\en\src\Standalone\resources\Azure.json
ID: 0; "DisplayNameEmulator"
SRC: (Emulator - Default Ports)

**Comment by lukaschal** [comment]
Localized at 10/17.

**Comment by MRayermannMSFT** [comment]
Verified.
