### ISSUE TITLE
Node statuses are not localized

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#1995]
**Storage Explorer Version**: 1.11.0 (prerelease)
**Build Number**: 20191002.6
**Platform/OS**: All

![image](https://user-images.githubusercontent.com/3473026/66155623-ed629880-e5d4-11e9-842b-880fd8a145aa.png)

**Comment by lukaschal** [comment]
Hard-coded strings.

https://devdiv.visualstudio.com/DevDiv/_git/CloudExplorer?path=%2Fsrc%2FCloudHub%2Fts%2FCommon%2FAzureStorageUtilities.ts&version=GBmaster

**Comment by craxal** [comment]
@jinglouMSFT As far as I can tell, I don't think these values aren't translated in Azure. I'm moving this to 1.13.0 unless you think we should not fix or fix for 1.11.0.

**Comment by jinglouMSFT** [comment]
I would vote to not fix them.
