### ISSUE TITLE
"Inferred" in blob access tier column is not localized

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#1996]
**Storage Explorer Version**: 1.11.0 (prerelease)
**Build Number**: 20191002.6
**Platform/OS**: All

![image](https://user-images.githubusercontent.com/3473026/66155742-27339f00-e5d5-11e9-8dd8-7da99a54cd67.png)

**Comment by lukaschal** [comment]
Hard-coded string.

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer?path=%2Fsrc%2FStandalone%2Fapp%2Frenderer%2FAzure%2FAzureStorage%2FBlobs%2FBlobQueryOperations.ts&version=GBmaster
