### ISSUE TITLE
"Case sensitive" is cut off in editor search box

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#1998]
**Storage Explorer Version**: 1.11.0 (prerelease)
**Build Number**: 20191002.6
**Platform/OS**: All

![image](https://user-images.githubusercontent.com/3473026/66155955-93ae9e00-e5d5-11e9-8d84-fc63334a108d.png)

**Comment by lukaschal** [comment]
@craxal  Non-resizable from localiization side. Would you like to resize this on develop side or should we just shorten this translation ? It seems this issue will appear almost on all languages. See below.


cs-CZ | Search by prefix (case-sensitive) | Vyhledat podle předpony (rozlišují se malá   a velká písmena)
-- | -- | --
de-DE | Search by prefix (case-sensitive) | Nach Präfix suchen (Groß-/Kleinschreibung relevant)
es-ES | Search by prefix (case-sensitive) | Buscar por prefijo (distingue mayúsculas de minúsculas)
fr-FR | Search by prefix (case-sensitive) | Rechercher par préfixe (sensible à la casse)
it-IT | Search by prefix (case-sensitive) | Cerca per prefisso (distinzione tra maiuscole e minuscole)
ja-JP | Search by prefix (case-sensitive) | プレフィックスで検索 (大文字と小文字を区別)
ko-KR | Search by prefix (case-sensitive) | 접두사로 검색(대/소문자 구분)
pl-PL | Search by prefix (case-sensitive) | Wyszukaj według prefiksu (z uwzględnieniem wielkości liter)
pt-BR | Search by prefix (case-sensitive) | Pesquisar por prefixo (diferencia maiúsculas de minúsculas)
ru-RU | Search by prefix (case-sensitive) | Поиск по префиксу (с учетом регистра)
tr-TR | Search by prefix (case-sensitive) | Ön eke göre ara (büyük/küçük harfe duyarlı)
zh-CN | Search by prefix (case-sensitive) | 按前缀搜索(区分大小写)
zh-TW | Search by prefix (case-sensitive) | 依前置詞搜尋 (區分大小寫)
