### ISSUE TITLE
New Folder Dialog launches on wrong monitor

### ISSUE THREAD

**Issue by JakeRadMSFT** [Microsoft/AzureStorageExplorer#2]
Storage Explorer Version: 0.9.6

OS Version: Windows 10

Steps to Reproduce:

1. Open Blob Container
2. Click New Folder

Notes:
If it doesn't reproduce try changing the monitor that Storage Explorer is running on.

Expected Experience:
New Folder Dialog launches on same monitor as Storage Explorer.

Actual Experience:
New Folder launches on different monitor.

**Comment by JakeRadMSFT** [comment]
Rename Dialog Also

**Comment by coip** [comment]
erroneous link just prior, apologies.
