### ISSUE TITLE
Sections of table query builder are not localized

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#2000]
**Storage Explorer Version**: 1.11.0 (prerelease)
**Build Number**: 20191002.6
**Platform/OS**: All

![image](https://user-images.githubusercontent.com/3473026/66156627-e177d600-e5d6-11e9-91ed-1c627571db4b.png)

**Comment by lukaschal** [comment]
Hard-coded. Cloud explorer.

https://devdiv.visualstudio.com/DevDiv/_git/CloudExplorer?path=%2Fsrc%2FCloudHub%2Fwwwroot%2Fhtml%2FStorageExplorer%2FTables%2Findex.html&version=GBmaster

**Comment by craxal** [comment]
Strings have been localized. @weeteckt When strings are translated, please reassign to me.

**Comment by lukaschal** [comment]
Localizable now.

File: loc\en\src\components\se-table-extension\resources\TableEditor.json
ID: 0; "LabelSelectFieldsForQuery"
SRC: Select fields for query

**Comment by lukaschal** [comment]
Localized at 10/17.

**Comment by MRayermannMSFT** [comment]
Verified 
![image](https://user-images.githubusercontent.com/21112697/67461471-48931400-f5f2-11e9-8d8d-dbbdf5c0f77e.png)
