### ISSUE TITLE
Various menu items are not localized

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#2003]
**Storage Explorer Version**: 1.11.0 (prerelease)
**Build Number**: 20191002.6
**Platform/OS**: All

- [x] App Menu &rarr; Opt out of Insider Builds
- [x] App Menu &rarr; Roll Back to Public Build
- [x] [Blob container] &rarr; Copy Blob Container
- [x] [Blob container] &rarr; Paste Blob Container
- [x] [Blob container] &rarr; Copy Direct Link to Blob Container
- [x] [Blob container] &rarr; Get Shared Access Signature
- [x] [Blob container] &rarr; Break Lease
- [x] [Blob container] &rarr; Configure Soft Delete Policy
- [x] [Storage account] &rarr; Get Shared Access Signature
- [x] Storage Accounts &rarr; Connect to Azure Storage

Feel free to break this up into individual issues as necessary.

**Comment by lukaschal** [comment]
Localized on all languages 2 months ago.

File: loc\en\src\Standalone\resources\ConfigureDeleteRetentionPolicyDialog.json
ID: 0; "TitleConfigureSoftDeletePolicy"
SRC: Configure Soft Delete Policy

File: loc\en\src\Standalone\resources\Azure.json
ID: 0; "ActionCopyContainerDirectLink"
SRC: Copy Direct Link to Blob Container

File: loc\en\src\components\se-table-extension\resources\TableEditor.json
ID: 0; "ContextMenu.GetSasCommandDescription"
SRC: Get Shared Access Signature

**Comment by JasonYeMSFT** [comment]
@lukaschal ,Some of the strings are obviously not translated. 
e.g. in loc/loc/zh-Hant/src/Standalone/resources/Azure.json.lcl line 60
For some languages, we don't know enough to tell if they are untranslated or they just appears to be the same. Could you please double check the translations?

**Comment by lukaschal** [comment]
@JasonYeMSFT This one localized at 10/7/2019 on all languages.

File: loc\en\src\Standalone\resources\Azure.json
ID: 0; "ActionConfigureSoftDeletePolicy"
SRC: Configure Soft Delete Policy...
