### ISSUE TITLE
"Add Metadata" button in Properties dialog is not localized

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#2004]
**Storage Explorer Version**: 1.11.0 (prerelease)
**Build Number**: 20191002.6
**Platform/OS**: All

![image](https://user-images.githubusercontent.com/3473026/66157875-8d222580-e5d9-11e9-9735-954ceafc3a79.png)

**Comment by lukaschal** [comment]
Localized at 8/15/2019.

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer?_a=contents&path=%2Floc%2Floc%2Fzh-Hans%2Fsrc%2FStandalone%2Fresources%2FAzure.json.lcl&version=GBmaster
