### ISSUE TITLE
Various translation errors

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#2005]
**Storage Explorer Version**: 1.11.0 (prerelease)
**Build Number**: 20191002.6
**Platform/OS**: All

Feel free to break this into individual issues as necessary.

# Multiple Languages
- Product names should not be translated, such as:
  - Microsoft Azure Storage Explorer
  - Storage Explorer

  ![image](https://user-images.githubusercontent.com/3473026/66163555-74b80800-e5e5-11e9-898d-9ca380a94218.png)

  ![image](https://user-images.githubusercontent.com/3473026/66164204-fceadd00-e5e6-11e9-91b2-36f89021ca73.png)

# Chinese (Simplified)
- File share displayed as blob container
  ![image](https://user-images.githubusercontent.com/3473026/66164422-80a4c980-e5e7-11e9-8b33-c59cb696158d.png)

- "Schema" has a strange translation
  ![image](https://user-images.githubusercontent.com/3473026/66164467-9adea780-e5e7-11e9-9181-721724c2d5c9.png)

- "Blob" should always be lowercase ("blob"); 
  ![image](https://user-images.githubusercontent.com/3473026/66164547-c6fa2880-e5e7-11e9-8a58-e2d57f38992f.png)

- App/Help &rarr; Insider Build has a strange translation

# Chinese (Traditional)

- "Explorer" banner on the left-hand side should be translated
  ![image](https://user-images.githubusercontent.com/3473026/66163395-1559f800-e5e5-11e9-93a6-089891d98df1.png)

- "Proxy" is not translated
  ![image](https://user-images.githubusercontent.com/3473026/66164232-0ecc8000-e5e7-11e9-972f-bfb2ee61986a.png)

- "Blob" should always be lowercase ("blob"); 
![image](https://user-images.githubusercontent.com/3473026/66164320-43403c00-e5e7-11e9-9a35-e26615103aad.png)

- "Clear completed" translated inaccurately
  ![image](https://user-images.githubusercontent.com/3473026/66164348-54894880-e5e7-11e9-9a5d-99b528e5ea93.png)

- "Operator" not translated
  ![image](https://user-images.githubusercontent.com/3473026/66164456-92866c80-e5e7-11e9-9155-4149cd3e0a94.png)

# German
- "Transfers" in Settings panel should be "Übertragungen"
  ![image](https://user-images.githubusercontent.com/3473026/66163796-fc057b80-e5e5-11e9-8ffc-636fb2d52b12.png)

# Korean
- "File Share" is translated literally
  ![image](https://user-images.githubusercontent.com/3473026/66164157-e3499580-e5e6-11e9-9bfe-6e656dd31617.png)

- "Share" is often translated to Korean word for "sharing"

# Spanish
- "Clear completed" and "Clear successful: use different verbiage for "clear"
  ![image](https://user-images.githubusercontent.com/3473026/66163545-6d90fa00-e5e5-11e9-9bc7-a6e23f2cd7e6.png)

- "ID" is translated as "Id."
  ![image](https://user-images.githubusercontent.com/3473026/66163634-a4671000-e5e5-11e9-90fa-866923ce81f1.png)

**Comment by lukaschal** [comment]
@craxal According to termstudio. Translations below are actual approved translations for "Storage Explorer" and "Microsoft Azure Storage Explorer"

https://termstudio.azurewebsites.net/viewdata.aspx?tid=2556351&langCode=English

Approved translation - Language
		
存储资源管理器 - Chinese (Simplified) CHN 
儲存體總管 - Chinese (Traditional) TWN 
Průzkumník služby Storage - Czech CZE 
Storage Explorer - Dutch NLD 
Storage Explorer - English USA 
Explorateur Stockage - French FRA 
Storage-Explorer - German DEU 
Storage Explorer - Hungarian HUN 
Storage Explorer - Italian ITA 
Storage Explorer - Japanese JPN 
Storage Explorer - Korean KOR 
Storage 탐색기 - Korean KOR Term Change 	
Eksplorator usługi Storage - Polish POL 
Gerenciador de Armazenamento - Portuguese (Brazil) BRA 
Explorador de Armazenamento - Portuguese (Portugal) PRT 
Обозреватель службы хранилища - Russian RUS 
Explorador de Storage - Spanish ESP 
Storage Explorer - Swedish SWE 
Depolama Gezgini - Turkish TUR


https://termstudio.azurewebsites.net/viewdata.aspx?tid=2556349&langCode=English

Microsoft Azure 存储资源管理器 - Chinese (Simplified) CHN
Microsoft Azure 儲存體總管 - Chinese (Traditional) TWN
Průzkumník služby Microsoft Azure Storage - Czech CZE
Microsoft Azure Storage Explorer - Dutch NLD
Microsoft Azure Storage Explorer - English USA
Explorateur Stockage Microsoft Azure - French FRA
Microsoft Azure Storage-Explorer - German DEU
Microsoft Azure Storage Explorer - Hungarian HUN
Microsoft Azure Storage Explorer - Italian ITA
Microsoft Azure Storage Explorer - Japanese JPN
Microsoft Azure Storage Explorer - Korean KOR
Eksplorator usługi Microsoft Azure Storage - Polish POL
Gerenciador de Armazenamento do Microsoft Azure - Portuguese (Brazil) BRA
Explorador de Armazenamento do Microsoft Azure - Portuguese (Portugal) PRT
Обозреватель службы хранилища Microsoft Azure - Russian RUS
Explorador de Microsoft Azure Storage - Spanish ESP
Microsoft Azure Storage Explorer - Swedish SWE
Microsoft Azure Depolama Gezgini - Turkish TUR



So should we use actual approved terminology or initial termchange to get all targets same as ENU for these terms?

**Comment by craxal** [comment]
@lukaschal That's the first I've heard of this resource. I'm curious to know how this term was approved for translation, because we've been told that product names, like "Azure" or "Outlook" should not be translated.

@jinglouMSFT What's the right way to proceed here?

**Comment by danyeh** [comment]
@craxal , it is company wide solid process that term translation governed by what's defined in termstudio. Only trademark (like Azure, Outllook) need to stay in English with exception that 'Microsoft' need a localized form in Russian language.

**Comment by jinglouMSFT** [comment]
Can we please not translate "Microsoft Azure Storage Explorer" for all languages?  I like the consistency across all languages.

**Comment by craxal** [comment]
@jinglouMSFT What about short application names, like "Storage Explorer"?

**Comment by danyeh** [comment]
@craxal @jinglouMSFT , keep "Microsoft Azure Storage Explorer" and "Storage Explorer" in English in loc product contradict with language requirement and purpose. I would like to suggest stick to term (studio) process. Term studio process is the right way to keep consistency across Microsoft Products, and between content (docs) and software.

**Comment by johnliu2016** [comment]
German suggestion - Implemented
Spanish suggestion - Implemented for "Clear completed", others are good as they are.
Korean suggestion is declined since current translation is compliant to term studio. 
Chinese simplified - Implemented lowercase of 'blob' in translation

**Comment by lukaschal** [comment]
Chinese traditional - According to the Term Studio, "proxy" is always kept in English. Rest suggestions implemented.

**Comment by lukaschal** [comment]
Terms "Storage Explorer" and "Microsoft Azure Storage Explorer" are consistent with termstudio for now.

**Comment by craxal** [comment]
@lukaschal @johnliu2016 @danyeh OK, let's go with whatever termstudio says. Please make sure we are consistent throughout the application.
