### ISSUE TITLE
Subscription not listed when using guest account with MFA

### ISSUE THREAD

**Issue by halkor** [microsoft/AzureStorageExplorer#2006]
**Storage Explorer Version**: 1.10.1
**Build Number**: 20190919.2
**Platform/OS**: Windows
**Architecture**: ia32
**Regression From**:  

## Bug Description ##
I have a subscription that I access using a guest account with multifactor authentication enabled. This account is not displayed in Storage Explorer.

## Steps to Reproduce ##
1. Add account

## Expected Experience ##
All subscriptions that my user account have access to should be listed.

## Actual Experience ##
Subscriptions accessed through a guest account with MFA enabled is not listed.

## Additional Context ##
I think this is where the problem happens:

![FiddlerTrace](https://user-images.githubusercontent.com/15158870/66290825-8bf63e80-e8e0-11e9-80f6-dc60f3bcac1c.png)

**Comment by Wh00T** [comment]
+1

I can see subscriptions on my default tenant (with MFA) and subscriptions from guest tenants without MFA. But I can't see any subscription for tenants where I'm invited as a guest that have MFA enabled. Though I have to confirm MFA for all those tenants when I add my account to storage explorer. I've also tried v1.9, same issue.

Let me know if you need more logfiles and I'll try to collect them 👍

**Comment by MRayermannMSFT** [comment]
Can y'all try using MSAL? It's a new auth library we're in the process of onboarding. You can enable it in Edit -> Settings -> Application -> Sign-in.

**Comment by JasonYeMSFT** [comment]
@halkor @Wh00T Does MSAL work for you all?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of reply. Please open a new issue if you still have problems.
