### ISSUE TITLE
Version 1.10.1 cannot list/view documents under a collection (MongoDB API account)

### ISSUE THREAD

**Issue by youxu71** [microsoft/AzureStorageExplorer#2008]
**Storage Explorer Version**: 
Version 1.10.1

**Build Number**: 
20190919.2

**Platform/OS**: 
Windows 10

**Architecture**: 
X64

**Regression From**:  
No.

## Bug Description ##

Cannot view/list any documents under a collection for a MongoDB API account.
## Steps to Reproduce ##
1. Open storage explorer
2. Click a MongoDB API account from Cosmos DB account list
3. Click database and collection (already created several documents from Azure portal)

## Expected Experience ##

List all documents under the collection.

## Actual Experience ##

Nothing show up.

**Comment by southpolesteve** [comment]
@youxu71 Thanks for the report. I will investigate, but in the meantime, can you continue to use the portal or the vscode extension? https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-cosmosdb

**Comment by youxu71** [comment]
Any progress on this?
I can use portal, but I prefer using storage explorer which can give me better productivity.

**Comment by akshaybabloo** [comment]
Same problem in version 1.11

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
