### ISSUE TITLE
Casing of Type's value 'DocumentDb' for one Document account is wrong

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#201]
**Storage Explorer Version**: 1.1.0

**Platform**: Windows/Linux/Mac

**Architecture**: ia32/x64

**Build Number**: 20180520.2

**Commit**: 713c27c5

**Regression From**: Not a regression

#### Steps to Reproduce: ####

1. Launch Storage Explorer and expand Cosmos DB Accounts.
2. Select one Document account and check the value of 'Type' in 'Properties' Panel.

#### Expected Experience: ####
 It displays as Microsoft.DocumentDB.

#### Actual Experience: ####
It displays as Microsoft.DocumentDb.
![compare](https://user-images.githubusercontent.com/34729022/40340369-29f93db2-5d6e-11e8-875b-a806bccf3b36.png)

**More info:**
This issue doesn't reproduce for other accounts type.

**Comment by MRayermannMSFT** [comment]
Hi @djlan , please triage this. Thanks!

**Comment by v-xianya** [comment]
Verified on build 20181108.3. This issue doesn't reproduce. Can you help to resolve it?

**Comment by jinglouMSFT** [comment]
This will be included in our next release. Closing.
