### ISSUE TITLE
"Set Default Access Tier..." is not translated yet

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#2010]
Related to #1537
 
Although we added a "..." to set default access tier, for all languages the string is english:

![image](https://user-images.githubusercontent.com/21112697/66353743-a4358000-e917-11e9-8122-928ea30baa3c.png)

**Comment by lukaschal** [comment]
New string. On translation now.

File: loc\en\src\Standalone\resources\Azure.json
ID: 0; "ActionSetDefaultAccessTier"
SRC: Set Default Access Tier...

**Comment by v-xianya** [comment]
This issue has been fixed on build 20191010.13. So we close it.
