### ISSUE TITLE
The Storage Accounts node still shows after disabling Storage Accounts on Settings panel

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2011]
**storage Explorer Version:** 1.10.1
**Build:** [20191005.6](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3115974)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer -> Open Settings panel.
2. Services -> Storage Accounts -> Uncheck the option for Storage Accounts.
3. Restart the Storage Explorer -> Observe whether the Storage Accounts node is hidden or not.

**Expect Experience:**
Storage Accounts node is hidden.

**Actual Experience:**
 The Storage Accounts node shows well.

**More Info:**
1. This issue also reproduces for **Cosmos DB**/ **Data Lake Storage Gen1**.
2. This issue doesn’t reproduce for **Disks**.

**Comment by MRayermannMSFT** [comment]
This is due to a bad Cloud Explorer commit reference. We'll update it today.
