### ISSUE TITLE
Keep consistent descriptions for enable options on Settings Panel

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2012]
**storage Explorer Version:** 1.10.1
**Build:** [20191005.6](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3115974)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer -> Open Settings panel.
2. Check the descriptions of enable options in Application & Data Explorers & Services & Transfers pages.

**Expect Experience:**
Keep consistent descriptions for enable options on Settings Panel.

**Actual Experience:**
The descriptions of enable options are inconsistent in **Services** page and **Transfers & Application & Data Explorers** pages.
![image](https://user-images.githubusercontent.com/41351993/66382464-d1ecf880-e9ed-11e9-9f14-38e4f426ae1a.png)

**Comment by craxal** [comment]
These options are enabled by default, whereas the other options are disabled by default. This is by design.
