### ISSUE TITLE
Recurring 'Cannot read property 'version' of undefined' error on Mac installation

### ISSUE THREAD

**Issue by lloyd-dotmodus** [microsoft/AzureStorageExplorer#2013]
**_Unable to load attached Storage Account. Error: Cannot read property 'version' of undefined_**

I haven't been able to get the storage explorer working properly since installation.

I have attempted to uninstall and re-install. I've tried accessing the same storage account with the connection string method, by using the account name and key, by using an SAS token, and every single time it says connection was successful but when trying to access the account on the left it shows this error. I've tried with numerous differing storage accounts where I know the credentials are correct, but this keeps happening.

After uninstalling I've deleted the following folder: /Users/<your_name>/Library/Application Support/StorageExplorer as per the instructions on this page https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C1904 so as to remove any 'cached' data/accounts after uninstalling so I can start afresh. I've removed the saved keychain credentials as well.

And after a fresh install, this still happens. Any advice or troubleshooting tips would be greatly appreciated, I really need this working so I can test a data pipeline for a client.

Kind Regards

**Comment by lloyd-dotmodus** [comment]
FYI, Version of Storage Explorer is the latest. 1.10.1

**Comment by JasonYeMSFT** [comment]
Are you seeing a broken node after adding the connection? If you are, please try detaching it and reataching it. If that doesn't work, can you try adding the same connection back and check if the credentials actually show up in the keychain? It is possible that the credentials are not corrupted but we are not given the correct permission to access them. At the mean time, can you also open the developer tool of Storage Explorer and check if there is any warning or error occurring after you added the connection?

**Comment by lloyd-dotmodus** [comment]
Hi @JasonYeMSFT, I've tried de and re-attaching. I've re-added and the credentials don 't seem to be coming up in the Keychain credentials now. I did also look at the developer tools but there weren't any errors there after adding a connection. 

I see @craxal has marked this ticket as duplicate. I'll comment on the #1961 ticket then.

Regards
