### ISSUE TITLE
Provide a cue for giving permissions after adding a new entity for ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2014]
**storage Explorer Version:** 1.10.1
**Build:** [20191005.6](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3115974)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand an ADLS Gen2 account -> Blob Containers.
2. Create a new blob container -> Open its context menu then select 'Manage Access...'.
3. Click 'Add' -> Type 'test' to search -> Select one entity -> Click 'Add'.
4. Click 'OK' -> Check the result.

**Expect Experience:**
Provide a cue to remind the user that we need to give permissions after adding a new entity.

**Actual Experience:**
1. The Manage Access dialog closed and no cue occurs.
2. Re-open the Manage Access dialog, the new added entity is not saved.

**Comment by craxal** [comment]
Very unlikely a user is going to "forget" to set permissions, because that's what they're hear for. If customers bring this up, we will revisit.
