### ISSUE TITLE
update a storage-explorer a manually bores'n'causes problems a for an example a latest thou storage-explorer ~ been required a to install .NET framework. Please, create packages'n'repositories a with an all dependencies ~ been  required thou for an atleast Ubuntu LTS versions

### ISSUE THREAD

**Issue by t3000** [microsoft/AzureStorageExplorer#2016]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jinglouMSFT** [comment]
In the release notes of v1.10.0 and v1.10.1, there is a link to the Snap store where you can install v1.10.1 from a snap store which has all the dependencies included.
