### ISSUE TITLE
Error trying to connect to Azure Gen1 Storage with SAS URI

### ISSUE THREAD

**Issue by nikhilvellala** [microsoft/AzureStorageExplorer#2019]
**Storage Explorer Version**:  1.10.1
**Build Number**:  20190919.2
**Platform/OS**:  Ubuntu Linux 18.04
**Architecture**:  x64
**Regression From**:  

## Bug Description ##

When connecting using SAS URI I get a ShareName format is incorrect error

## Steps to Reproduce ##

1. Open the SAS URI window and input a sas uri & attempt to connect

## Expected Experience ##

-- LOG BELOW
{
  "name": "SyntaxError",
  "message": "Share name format is incorrect.",
  "__zone_symbol__error": {
    "originalStack": "Error: Share name format is incorrect.\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/snap/storage-explorer/5/resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/snap/storage-explorer/5/resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:172:18)\n    at Function.ExceptionSerializer.deserialize (/snap/storage-explorer/5/resources/app/node_modules/se-exception-serializer/dist/ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler._finalizeOperation (/snap/storage-explorer/5/resources/app/out/app/renderer/marshalers/CloudExplorerProxyMarshaler.js:83:91)\n    at Object.finalizeOperation (/snap/storage-explorer/5/resources/app/out/app/renderer/marshalers/CloudExplorerProxyMarshaler.js:107:80)\n    at Function.<anonymous> (/snap/storage-explorer/5/resources/app/out/app/renderer/marshalers/StandardMarshaler.js:28:63)\n    at step (/snap/storage-explorer/5/resources/app/node_modules/tslib/tslib.js:136:27)\n    at Object.next (/snap/storage-explorer/5/resources/app/node_modules/tslib/tslib.js:117:57)\n    at /snap/storage-explorer/5/resources/app/node_modules/tslib/tslib.js:110:75\n    at new ZoneAwarePromise (/snap/storage-explorer/5/resources/app/node_modules/zone.js/dist/zone-node.js:551:29)\n    at Object.__awaiter (/snap/storage-explorer/5/resources/app/node_modules/tslib/tslib.js:106:16)\n    at JsonPortMarshaler.standardMarshaler.(anonymous function) [as finalizeOperation] (/snap/storage-explorer/5/resources/app/out/app/renderer/marshalers/StandardMarshaler.js:22:32)\n    at JsonPortMarshaler.onMessage (/snap/storage-explorer/5/resources/app/node_modules/daytona/pluginHost/messaging/marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (/snap/storage-explorer/5/resources/app/node_modules/daytona/pluginHost/common/event.js:69:30)\n    at Port.processMessage (/snap/storage-explorer/5/resources/app/node_modules/daytona/pluginHost/messaging/communication.js:163:18)",
    "zoneAwareStack": "Error: Share name format is incorrect.\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/snap/storage-explorer/5/resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/snap/storage-explorer/5/resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:172:18)\n    at Function.ExceptionSerializer.deserialize (/snap/storage-explorer/5/resources/app/node_modules/se-exception-serializer/dist/ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler._finalizeOperation (/snap/storage-explorer/5/resources/app/out/app/renderer/marshalers/CloudExplorerProxyMarshaler.js:83:91)\n    at Object.finalizeOperation (/snap/storage-explorer/5/resources/app/out/app/renderer/marshalers/CloudExplorerProxyMarshaler.js:107:80)\n    at Function.<anonymous> (/snap/storage-explorer/5/resources/app/out/app/renderer/marshalers/StandardMarshaler.js:28:63)\n    at step (/snap/storage-explorer/5/resources/app/node_modules/tslib/tslib.js:136:27)\n    at Object.next (/snap/storage-explorer/5/resources/app/node_modules/tslib/tslib.js:117:57)\n    at /snap/storage-explorer/5/resources/app/node_modules/tslib/tslib.js:110:75\n    at new ZoneAwarePromise (/snap/storage-explorer/5/resources/app/node_modules/zone.js/dist/zone-node.js:551:29)\n    at Object.__awaiter (/snap/storage-explorer/5/resources/app/node_modules/tslib/tslib.js:106:16)\n    at JsonPortMarshaler.standardMarshaler.(anonymous function) [as finalizeOperation] (/snap/storage-explorer/5/resources/app/out/app/renderer/marshalers/StandardMarshaler.js:22:32)\n    at JsonPortMarshaler.onMessage (/snap/storage-explorer/5/resources/app/node_modules/daytona/pluginHost/messaging/marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (/snap/storage-explorer/5/resources/app/node_modules/daytona/pluginHost/common/event.js:69:30)\n    at Port.processMessage (/snap/storage-explorer/5/resources/app/node_modules/daytona/pluginHost/messaging/communication.js:163:18)"
  },
  "stack": "SyntaxError: Share name format is incorrect.\n    at getNameError (/snap/storage-explorer/5/resources/app/node_modules/azure-storage/lib/common/util/validate.js:186:12)\n    at ArgumentValidator.exports.shareNameIsValid (/snap/storage-explorer/5/resources/app/node_modules/azure-storage/lib/common/util/validate.js:283:19)\n    at /snap/storage-explorer/5/resources/app/node_modules/azure-storage/lib/services/file/fileservice.core.js:1755:7\n    at Object.validateArgs (/snap/storage-explorer/5/resources/app/node_modules/azure-storage/lib/common/util/validate.js:556:3)\n    at Object.FileService.getUrl (/snap/storage-explorer/5/resources/app/node_modules/azure-storage/lib/services/file/fileservice.core.js:1752:12)\n    at /snap/storage-explorer/5/resources/app/out/app/renderer/Azure/AzureStorage/FileManager.js:140:67\n    at step (/snap/storage-explorer/5/resources/app/node_modules/tslib/tslib.js:136:27)\n    at Object.next (/snap/storage-explorer/5/resources/app/node_modules/tslib/tslib.js:117:57)\n    at fulfilled (/snap/storage-explorer/5/resources/app/node_modules/tslib/tslib.js:107:62)\n    at ZoneDelegate.invoke (/snap/storage-explorer/5/resources/app/node_modules/zone.js/dist/zone-node.js:242:26)\n    at Zone.run (/snap/storage-explorer/5/resources/app/node_modules/zone.js/dist/zone-node.js:113:43)\n    at /snap/storage-explorer/5/resources/app/node_modules/zone.js/dist/zone-node.js:535:57\n    at ZoneDelegate.invokeTask (/snap/storage-explorer/5/resources/app/node_modules/zone.js/dist/zone-node.js:275:35)\n    at Zone.runTask (/snap/storage-explorer/5/resources/app/node_modules/zone.js/dist/zone-node.js:151:47)\n    at drainMicroTaskQueue (/snap/storage-explorer/5/resources/app/node_modules/zone.js/dist/zone-node.js:433:35)",
  "originalStack": "Error: Share name format is incorrect.\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/snap/storage-explorer/5/resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/snap/storage-explorer/5/resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:172:18)\n    at Function.ExceptionSerializer.deserialize (/snap/storage-explorer/5/resources/app/node_modules/se-exception-serializer/dist/ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler._finalizeOperation (/snap/storage-explorer/5/resources/app/out/app/renderer/marshalers/CloudExplorerProxyMarshaler.js:83:91)\n    at Object.finalizeOperation (/snap/storage-explorer/5/resources/app/out/app/renderer/marshalers/CloudExplorerProxyMarshaler.js:107:80)\n    at Function.<anonymous> (/snap/storage-explorer/5/resources/app/out/app/renderer/marshalers/StandardMarshaler.js:28:63)\n    at step (/snap/storage-explorer/5/resources/app/node_modules/tslib/tslib.js:136:27)\n    at Object.next (/snap/storage-explorer/5/resources/app/node_modules/tslib/tslib.js:117:57)\n    at /snap/storage-explorer/5/resources/app/node_modules/tslib/tslib.js:110:75\n    at new ZoneAwarePromise (/snap/storage-explorer/5/resources/app/node_modules/zone.js/dist/zone-node.js:551:29)\n    at Object.__awaiter (/snap/storage-explorer/5/resources/app/node_modules/tslib/tslib.js:106:16)\n    at JsonPortMarshaler.standardMarshaler.(anonymous function) [as finalizeOperation] (/snap/storage-explorer/5/resources/app/out/app/renderer/marshalers/StandardMarshaler.js:22:32)\n    at JsonPortMarshaler.onMessage (/snap/storage-explorer/5/resources/app/node_modules/daytona/pluginHost/messaging/marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (/snap/storage-explorer/5/resources/app/node_modules/daytona/pluginHost/common/event.js:69:30)\n    at Port.processMessage (/snap/storage-explorer/5/resources/app/node_modules/daytona/pluginHost/messaging/communication.js:163:18)",
  "zoneAwareStack": "Error: Share name format is incorrect.\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/snap/storage-explorer/5/resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/snap/storage-explorer/5/resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:172:18)\n    at Function.ExceptionSerializer.deserialize (/snap/storage-explorer/5/resources/app/node_modules/se-exception-serializer/dist/ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler._finalizeOperation (/snap/storage-explorer/5/resources/app/out/app/renderer/marshalers/CloudExplorerProxyMarshaler.js:83:91)\n    at Object.finalizeOperation (/snap/storage-explorer/5/resources/app/out/app/renderer/marshalers/CloudExplorerProxyMarshaler.js:107:80)\n    at Function.<anonymous> (/snap/storage-explorer/5/resources/app/out/app/renderer/marshalers/StandardMarshaler.js:28:63)\n    at step (/snap/storage-explorer/5/resources/app/node_modules/tslib/tslib.js:136:27)\n    at Object.next (/snap/storage-explorer/5/resources/app/node_modules/tslib/tslib.js:117:57)\n    at /snap/storage-explorer/5/resources/app/node_modules/tslib/tslib.js:110:75\n    at new ZoneAwarePromise (/snap/storage-explorer/5/resources/app/node_modules/zone.js/dist/zone-node.js:551:29)\n    at Object.__awaiter (/snap/storage-explorer/5/resources/app/node_modules/tslib/tslib.js:106:16)\n    at JsonPortMarshaler.standardMarshaler.(anonymous function) [as finalizeOperation] (/snap/storage-explorer/5/resources/app/out/app/renderer/marshalers/StandardMarshaler.js:22:32)\n    at JsonPortMarshaler.onMessage (/snap/storage-explorer/5/resources/app/node_modules/daytona/pluginHost/messaging/marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (/snap/storage-explorer/5/resources/app/node_modules/daytona/pluginHost/common/event.js:69:30)\n    at Port.processMessage (/snap/storage-explorer/5/resources/app/node_modules/daytona/pluginHost/messaging/communication.js:163:18)",
  "__zone_symbol__stack": "SyntaxError: Share name format is incorrect.\n    at getNameError (/snap/storage-explorer/5/resources/app/node_modules/azure-storage/lib/common/util/validate.js:186:12)\n    at ArgumentValidator.exports.shareNameIsValid (/snap/storage-explorer/5/resources/app/node_modules/azure-storage/lib/common/util/validate.js:283:19)\n    at /snap/storage-explorer/5/resources/app/node_modules/azure-storage/lib/services/file/fileservice.core.js:1755:7\n    at Object.validateArgs (/snap/storage-explorer/5/resources/app/node_modules/azure-storage/lib/common/util/validate.js:556:3)\n    at Object.FileService.getUrl (/snap/storage-explorer/5/resources/app/node_modules/azure-storage/lib/services/file/fileservice.core.js:1752:12)\n    at /snap/storage-explorer/5/resources/app/out/app/renderer/Azure/AzureStorage/FileManager.js:140:67\n    at step (/snap/storage-explorer/5/resources/app/node_modules/tslib/tslib.js:136:27)\n    at Object.next (/snap/storage-explorer/5/resources/app/node_modules/tslib/tslib.js:117:57)\n    at fulfilled (/snap/storage-explorer/5/resources/app/node_modules/tslib/tslib.js:107:62)\n    at ZoneDelegate.invoke (/snap/storage-explorer/5/resources/app/node_modules/zone.js/dist/zone-node.js:242:26)\n    at Zone.run (/snap/storage-explorer/5/resources/app/node_modules/zone.js/dist/zone-node.js:113:43)\n    at /snap/storage-explorer/5/resources/app/node_modules/zone.js/dist/zone-node.js:535:57\n    at ZoneDelegate.invokeTask (/snap/storage-explorer/5/resources/app/node_modules/zone.js/dist/zone-node.js:275:35)\n    at Zone.runTask (/snap/storage-explorer/5/resources/app/node_modules/zone.js/dist/zone-node.js:151:47)\n    at drainMicroTaskQueue (/snap/storage-explorer/5/resources/app/node_modules/zone.js/dist/zone-node.js:433:35)",
  "__zone_symbol__name": "SyntaxError",
  "__zone_symbol__message": "Share name format is incorrect.",
  "__zone_symbol__originalStack": "Error: Share name format is incorrect.\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/snap/storage-explorer/5/resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/snap/storage-explorer/5/resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:172:18)\n    at Function.ExceptionSerializer.deserialize (/snap/storage-explorer/5/resources/app/node_modules/se-exception-serializer/dist/ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler._finalizeOperation (/snap/storage-explorer/5/resources/app/out/app/renderer/marshalers/CloudExplorerProxyMarshaler.js:83:91)\n    at Object.finalizeOperation (/snap/storage-explorer/5/resources/app/out/app/renderer/marshalers/CloudExplorerProxyMarshaler.js:107:80)\n    at Function.<anonymous> (/snap/storage-explorer/5/resources/app/out/app/renderer/marshalers/StandardMarshaler.js:28:63)\n    at step (/snap/storage-explorer/5/resources/app/node_modules/tslib/tslib.js:136:27)\n    at Object.next (/snap/storage-explorer/5/resources/app/node_modules/tslib/tslib.js:117:57)\n    at /snap/storage-explorer/5/resources/app/node_modules/tslib/tslib.js:110:75\n    at new ZoneAwarePromise (/snap/storage-explorer/5/resources/app/node_modules/zone.js/dist/zone-node.js:551:29)\n    at Object.__awaiter (/snap/storage-explorer/5/resources/app/node_modules/tslib/tslib.js:106:16)\n    at JsonPortMarshaler.standardMarshaler.(anonymous function) [as finalizeOperation] (/snap/storage-explorer/5/resources/app/out/app/renderer/marshalers/StandardMarshaler.js:22:32)\n    at JsonPortMarshaler.onMessage (/snap/storage-explorer/5/resources/app/node_modules/daytona/pluginHost/messaging/marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (/snap/storage-explorer/5/resources/app/node_modules/daytona/pluginHost/common/event.js:69:30)\n    at Port.processMessage (/snap/storage-explorer/5/resources/app/node_modules/daytona/pluginHost/messaging/communication.js:163:18)",
  "__zone_symbol__zoneAwareStack": "Error: Share name format is incorrect.\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/snap/storage-explorer/5/resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/snap/storage-explorer/5/resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:172:18)\n    at Function.ExceptionSerializer.deserialize (/snap/storage-explorer/5/resources/app/node_modules/se-exception-serializer/dist/ExceptionSerializer.js:49:28)\n    at CloudExplorerProxyMarshaler._finalizeOperation (/snap/storage-explorer/5/resources/app/out/app/renderer/marshalers/CloudExplorerProxyMarshaler.js:83:91)\n    at Object.finalizeOperation (/snap/storage-explorer/5/resources/app/out/app/renderer/marshalers/CloudExplorerProxyMarshaler.js:107:80)\n    at Function.<anonymous> (/snap/storage-explorer/5/resources/app/out/app/renderer/marshalers/StandardMarshaler.js:28:63)\n    at step (/snap/storage-explorer/5/resources/app/node_modules/tslib/tslib.js:136:27)\n    at Object.next (/snap/storage-explorer/5/resources/app/node_modules/tslib/tslib.js:117:57)\n    at /snap/storage-explorer/5/resources/app/node_modules/tslib/tslib.js:110:75\n    at new ZoneAwarePromise (/snap/storage-explorer/5/resources/app/node_modules/zone.js/dist/zone-node.js:551:29)\n    at Object.__awaiter (/snap/storage-explorer/5/resources/app/node_modules/tslib/tslib.js:106:16)\n    at JsonPortMarshaler.standardMarshaler.(anonymous function) [as finalizeOperation] (/snap/storage-explorer/5/resources/app/out/app/renderer/marshalers/StandardMarshaler.js:22:32)\n    at JsonPortMarshaler.onMessage (/snap/storage-explorer/5/resources/app/node_modules/daytona/pluginHost/messaging/marshaler.js:101:41)\n    at Port.EventTarget.dispatchEvent (/snap/storage-explorer/5/resources/app/node_modules/daytona/pluginHost/common/event.js:69:30)\n    at Port.processMessage (/snap/storage-explorer/5/resources/app/node_modules/daytona/pluginHost/messaging/communication.js:163:18)"
}

**Comment by MRayermannMSFT** [comment]
Are you still seeing this issue?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
