### ISSUE TITLE
Query predicate text box no show content in Dark theme (CosmosDB collection)

### ISSUE THREAD

**Issue by fforcen** [microsoft/AzureStorageExplorer#202]
**Storage Explorer Version**: 1.1.0

**Platform**: Windows

**Architecture**: ia32

**Build Number**: 20180507.1

**Commit**: bcc8990d

**Regression From**: 

#### Steps to Reproduce: ####

1. Change theme to Dark in: View -> Themes -> Dark
2. Go to a CosmosDB collection
3. Click Documents
4. Click Filter
5. Type in Query Predicate text box

#### Expected Experience: ####
I expect that I could see what I'm typing.

#### Actual Experience: ####
If you type in query predicate text box using dark theme, you can't see what are you typing because font color is set to white and background of the box is set to white too if you have mouse cursor over text box.

**Comment by MRayermannMSFT** [comment]
Hey @djlan  and @ziyel , please triage this bug!

**Comment by jinglouMSFT** [comment]
@southpolesteve this bug has been there for a long time and the text pretty much can not be read. Pretty annoying. While on this, can you please also plan on having the CosmosDB feature in Storage Explorer go through an Accessibility pass?  Thanks.

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
