### ISSUE TITLE
Punctuation in labels, such as colons, should be localized

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#2020]
Examples:
```json
"LabelExample": "This is a control label:",
"Message": "Plain message",
"MessageWithExtra": "Plain message (with extra)",
"StatusTemplate": "%1$s (%2$s)"
```

**Comment by lukaschal** [comment]
@craxal Any action needed from localization team ?

**Comment by craxal** [comment]
Not yet. This is a work item for us to move punctuation into strings resources.

**Comment by craxal** [comment]
@lukaschal Moving punctuation into string resources has affected a lot of strings. Have translators been picking up these changes?

**Comment by lukaschal** [comment]
@craxal I've checked examples above and no one visible in a localizable resources.

**Comment by craxal** [comment]
@lukaschal The above examples are only meant to explain what this issue is about. They aren't in reference to actual strings in Storage Explorer. If you want a practical example, please look at ConnectDialog.json.

**Comment by lukaschal** [comment]
@craxal I see. Many strings in a ConnectDialog.json with ":" at the end were localized between 3/11 and 3/19. One occurence fixed, rest is correct.
