### ISSUE TITLE
An error dialog pops up when trying to delete one ADLS Gen2 blob

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2022]
**Storage Explorer Version:** 1.10.1
**Build:** [20191009.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3124757)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release (1.10.1)

**Steps to reproduce:**
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create one blob container -> Upload one blob.
3. Try to delete the blob -> Check the result.

**Expect Experience:**
The Delete dialog pops up.
![image](https://user-images.githubusercontent.com/41351993/66462255-49359180-eaad-11e9-8137-db3b8ad0f23e.png)

**Actual Experience:**
An error dialog pops up.
![image](https://user-images.githubusercontent.com/41351993/66462206-2e631d00-eaad-11e9-8c0d-05d0649ee715.png)

**Comment by janbaltus** [comment]
@craxal  This might be caused by overloclaization of some resource.
From our side all occurrences of string Cancel are localized. If Cancel need to stay in English please lock corresponding resource string

**Comment by v-xianya** [comment]
This issue has been fixed on build 20191015.4. So we close it.
