### ISSUE TITLE
No warning shows when pasting one Cosmos DB account primary connection string to 'Attach with Connection String' dialog 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2025]
**Storage Explorer Version:** 1.10.1
**Build:** [20191009.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3124757)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a Regression

**Steps to reproduce:**

1. Expand Storage Accounts -> Cosmos DB Accounts (Preview).
2. Select one cosmos account with table api -> Right click this account and click 'Copy Primary Connection String'.
3. Click 'Open Connect Dialog' icon -> Select 'Using a connection string' and paste the copied 'Primary Connection String'.
4. Check the result.

**Expect Experience:**
A warning shows like pasting one Document DB account connection string.
![image](https://user-images.githubusercontent.com/54055206/66468721-3a54dc00-eab9-11e9-9e17-ab0af6b9409f.png)

**Actual Experience:**
No warning shows.
![image](https://user-images.githubusercontent.com/54055206/66468594-011c6c00-eab9-11e9-99dc-c80be8db8208.png)

**More Info:**
This issue doesn't reproduces for one cosmos account with Document DB / Mongo DB/ Graph api account.

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
