### ISSUE TITLE
Show a blank dialog when trying to delete one blob

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2026]
**Storage Explorer Version:** 1.10.1
**Build:** [20191009.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3124757)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release (1.10.1)

**Steps to reproduce:**

1. Expand one storage account -> Blob Containers.
2. Create a new blob container -> Upload one blob to it.
3. Delete this blob -> Check the dialog.

**Expect Experience:**
The delete dialog shows well.
![image](https://user-images.githubusercontent.com/54055206/66469649-cadfec00-eaba-11e9-8127-0cae80c526cc.png)

**Actual Experience:**
Show a blank dialog.
![image](https://user-images.githubusercontent.com/54055206/66469670-d6cbae00-eaba-11e9-8ecd-8a45f604f061.png)

**More Info:**

1. This issue also reproduces when trying to rename one blob.
![image](https://user-images.githubusercontent.com/54055206/66469706-e9de7e00-eaba-11e9-9e11-09d6add65883.png)
2. This issue also reproduces when trying to break lease for one blob.
![image](https://user-images.githubusercontent.com/54055206/66469736-fb278a80-eaba-11e9-9f98-a764c87a266f.png)
3. This issue also reproduces for **Undelete Selected** dialog.

**Comment by JasonYeMSFT** [comment]
These strings are recently localized and will show up once we publish the resource file. We will notify you when the resource files are published.

**Comment by v-xianya** [comment]
This issue has been fixed on build 20191012.1. So we close it.
