### ISSUE TITLE
Transferring file to ADLS Gen2 via Storage Explorer Tool hangs at 100%

### ISSUE THREAD

**Issue by jeeva86** [microsoft/AzureStorageExplorer#2029]
**Storage Explorer Version**: 1.10.1
**AzCopy Version**: 10.2.1
**Build Number**: 20190919.2
**Platform/OS**: macOS Mojave
**Architecture**: x64

## Bug Description ##
Uploading a 1.4GB file to ADLS Gen2 hangs when it reaches 100%

<img width="1270" alt="image" src="https://user-images.githubusercontent.com/22123580/66498942-e6340280-ea8c-11e9-859f-339f60ee5e0a.png">

hohoho: Azure Blob
datalake: ADLS Gen2

The 🚫 is from a previous transfer that I canceled that was hung at 100%.

## Steps to Reproduce ##
1. Drag and drop a 1.4GB file into the container
2. Wait until it reaches 100% and hangs there

## Expected Experience ##
Expect the transfer to complete.

## Actual Experience ##
Transfer never completes.

## Additional Context ##
I've transferred a few 4xxMB files without issues. I'm also able to transfer the identical 1.4GB file to Azure Blob storage without issues.

**Comment by jinglouMSFT** [comment]
This is weird.  Your upload to Blob also has AzCopy enabled.  Uploading to ADLS Gen2 also uses AzCopy to actually do the upload. Shouldn't fail or hung.  If you don't mind, could you try to do an actual upload from the toolbar or copy the AzCopy command from the clipboard and run the AzCopy command line from the command line?  Observe to see if either of them succeeds? Thanks.

**Comment by jeeva86** [comment]
Attached the log file that was generated when I let it timeout: [c0054505-2c1a-6143-742f-2b5704fe84b2.log](https://github.com/microsoft/AzureStorageExplorer/files/3708843/c0054505-2c1a-6143-742f-2b5704fe84b2.log)

toolbar = Upload button in the application?

I can't do the azcopy cli method because v8 doesn't support adls gen2 and v10 azcopy doesn't work for me, keeps giving me the failed to refresh access token, even though I did an azcopy login right before it. I should maybe open a separate git issue for that.

**Comment by MRayermannMSFT** [comment]
Hey @jeeva86 , so we recently learned from the AzCopy team that they way we are calculating percentages is "wrong". Basically AzCopy tell us:

1. how many bytes need to be sent
2. how many bytes have been sent

And from that we do the math to calculate % done. But what we weren't aware of was that bytes sent includes bytes failed network calls! So looking at your log, you have a lot of 500 errors (server timeouts).

Towards the end though, I did start to see some 200s, so I think your transfer might eventually finish? But I can understand how it's frustrating to not see if any progress is actually being made. Thankfully in our next version of Storage Explorer, we'll be using an AzCopy that directly tells us % successfully sent. 😄 

As for your token refresh issue, yep, you'll need to file an issue at the AzCopy repo: https://github.com/Azure/azure-storage-azcopy 

Thank you for previewing the AzCopy feature, but also apologies about this issue.

**Comment by jeeva86** [comment]
Thanks @MRayermannMSFT. My transfers never finished, but I'll try again. Is there non-preview version of azcopy for pushing to adlsg2?

**Comment by jeeva86** [comment]
I retried this in my work network(bigger pipe), and the upload was successful!

**Comment by JasonYeMSFT** [comment]
@jeeva86, other than AzCopy requiring a large network bandwidth, do you still have any problem using Storage Explorer?
