### ISSUE TITLE
Button descriptions are not localized on Manage Access dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2033]
**Storage Explorer Version:** 1.10.1
**Build:** [20191010.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3128931)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** Chinese (zh-CN)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer using the command 'StorageExplorer.exe --lang=zh-CN'.
2. Expand one ADLS Gen2 storage account -> Blob Containers.
3. Select one blob container then open its context menu -> Select localized 'Manage Access...'.
4. Check the Manage Access dialog.

**Expect Experience:**
All the strings that need to be translated have been localized.

**Actual Experience:**
Button descriptions are not localized.
![image](https://user-images.githubusercontent.com/41351993/66551008-283a7280-eb79-11e9-9788-7c5f529e43ac.png)

**More Info:**
1. Click Add -> 'Add Entity' dialog is not localized.
![image](https://user-images.githubusercontent.com/41351993/66551096-5f108880-eb79-11e9-91d8-c9fbf1cb0eae.png)
2. Only verified this issue in Chinese (zh-CN).

**Comment by v-xianya** [comment]
**More Info:**
This issue also reproduces on Telemetry Settings Panel.
![image](https://user-images.githubusercontent.com/41351993/66628398-4ebbe480-ec31-11e9-878e-6fea0af1630b.png)

**Comment by MRayermannMSFT** [comment]
First dialog fixed in 11. Later dialog will be fixed in 13.

**Comment by v-xianya** [comment]
1. The descriptions on Manage Access dialog are all localized.

2. Waiting the buttons on 'Telemetry Settings Panel' to be localized.

**Comment by v-xianya** [comment]
This issue has been fixed on build 20200212.1. So we close it.
