### ISSUE TITLE
The editor of one adls gen2 blob container is blank

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2034]
**Storage Explorer Version:** 1.10.1
**Build:** [20191010.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3128931)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release (1.10.1)

**Steps to reproduce:**
1. Expand one ADLS Gen2 account -> Blob Containers.
2. Select one blob container and check its editor.

**Expect Experience:**
The editor shows well.
![image](https://user-images.githubusercontent.com/41351993/66552031-35f0f780-eb7b-11e9-8c7b-8999ac5995b2.png)

**Actual Experience:**
The editor is blank.
![image](https://user-images.githubusercontent.com/41351993/66552040-3a1d1500-eb7b-11e9-9e45-f6771be1f40e.png)

**Comment by craxal** [comment]
Ah, this is because we're looking for a new string resource that's not in the current version of the ADLS Gen2 package. We need to update it.

**Comment by v-xianya** [comment]
This issue has been fixed on build 20191012.1. So we close it.
