### ISSUE TITLE
Show an odd layout on one ADLS Gen1 account editor

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2036]
**Storage Explorer Version:** 1.10.1
**Build:** [20191010.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3128931)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release (1.10.1)

**Steps to reproduce:**
1. Open one ADLS Gen1 account.
2. Check the layout on its editor.

**Expect Experience:**
Show a normal layout on the editor.
![image](https://user-images.githubusercontent.com/41351993/66553400-9c771500-eb7d-11e9-9683-d8873910f0f2.png)

**Actual Experience:**
Show an odd layout on the editor.
![image](https://user-images.githubusercontent.com/41351993/66553397-997c2480-eb7d-11e9-9de4-d3a3e37d3120.png)

**Comment by craxal** [comment]
Related to work done for #1997, #1998.
