### ISSUE TITLE
The descriptions of enable options are not localized for Services page on Settings panel  

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2037]
**Storage Explorer Version:** 1.10.1
**Build:** [20191010.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3128931)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** Chinese (zh-CN)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer using the command 'StorageExplorer.exe --lang=zh-CN'.
2. Open Settings panel -> Click localized Services.
3. Check the descriptions of enable options are localized or not.

**Expect Experience:**
The descriptions of enable options are localized.

**Actual Experience:**
The descriptions of enable options are not localized.
![image](https://user-images.githubusercontent.com/41351993/66555901-f37ee900-eb81-11e9-9b13-ea8e21e17583.png)

**More Info:**
Only verified this issue in Chinese (zh-CN).

**Comment by craxal** [comment]
@MRayermannMSFT Are we just waiting for translations now?

**Comment by MRayermannMSFT** [comment]
Yes. Those are resource strings.

**Comment by v-xianya** [comment]
This issue has been fixed on build 20191010.13. So we close it.
