### ISSUE TITLE
Yes & No buttons are not localized when detaching one resource

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2039]
**Storage Explorer Version:** 1.10.1
**Build:** [20191010.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3128931)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** Chinese (zh-CN)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer using the command 'StorageExplorer.exe --lang=zh-CN'.
2. Expand one Non-ADLS Gen2 storage account -> Blob Containers.
3. Select one blob container and using SAS to attach.
4. Try to detach the SAS attached blob container.
5. Check the prompt dialog.

**Expect Experience:**
Yes & No buttons are localized.

**Actual Experience:**
Yes & No buttons are not localized.

![image](https://user-images.githubusercontent.com/41351993/66557259-288c3b00-eb84-11e9-9adf-b9c078168c95.png)

**More Info:**
1. Only verified this issue in Chinese (zh-CN).
2. This issue reproduces for one attached file share/ table/ queue.
3. This issue doesn't reproduce when detaching one **attached storage account**.
![image](https://user-images.githubusercontent.com/41351993/66557283-317d0c80-eb84-11e9-8ee2-9f355388b446.png)
4. This issue doesn't reproduce when detaching one **local emulator account**.
![image](https://user-images.githubusercontent.com/41351993/66558165-b157a680-eb85-11e9-8e54-03f2b1e62da0.png)

**Comment by craxal** [comment]
The dialog is a system dialog, and so the buttons cannot be localized. Just need to switch to our own message box dialog.

**Comment by v-xianya** [comment]
This issue also reproduces on build 20191010.13. So we re-open it.

**Comment by craxal** [comment]
Related to #2042.

**Comment by v-xianya** [comment]
This issue has been fixed on build 20191012.1. So we close it.
