### ISSUE TITLE
Deep link to Blob Container doesn't work

### ISSUE THREAD

**Issue by andyseres** [microsoft/AzureStorageExplorer#204]
**Storage Explorer Version**: 1.1.0 

**Platform**: Windows 

**Architecture**: ia32

**Build Number**: 20180507.1

**Commit**: bcc8990d

**Regression From**: don't know, first time I tried it.

#### Steps to Reproduce: ####

1. navigate in the explorer to storage account to blob containers where you have some containers.
1. rt-click on the blob container to "Copy Direct Link to Blob Container"
1. close the app
1. start->run, paste the link

storageexplorer://v=1&accountid=%2Fsubscriptions%2F[subscription]%2FresourceGroups%2F[group]%2Fproviders%2FMicrosoft.Storage%2FstorageAccounts%2F[storageacct]&subscriptionid=[sid]&resourcetype=Azure.BlobContainer&resourcename=[containername]

#### Expected Experience: ####
launch azure storage explorer and take me directly to the blob container in question

#### Actual Experience: ####
launch azure storage explorer and take me to the top level virtual folder for Blob Containers, but doesn't show me the blob container in question

**Comment by robwafle** [comment]
This also fails to work when the "Open In Explorer" link is used from the Azure portal.  I believe if it isn't in the first set of storage accounts downloaded, further pages of data are not downloaded to look for more storage accounts.  If I press "Load More" until it appears on the list, then go back to the portal and click again the storage account is selected.

**Comment by MRayermannMSFT** [comment]
Possibly related to #194

**Comment by MRayermannMSFT** [comment]
I can't repro this anymore. Both for storage accounts and blob containers, both ones on the first page from Azure and ones on the non-1st pages. If y'all are still having issues in v1.9.0 please open a new issue with more details.
