### ISSUE TITLE
The delete dialog is not localized for one ADLS Gen1 file

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2040]
**Storage Explorer Version:** 1.10.1
**Build:** [20191010.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3128931)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** Chinese (zh-CN)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer using the command 'StorageExplorer.exe --lang=zh-CN'.
2. Select one ADLS Gen1 account -> Upload one file.
3. Try to delete the ADLS Gen1 file -> Check the delete dialog.

**Expect Experience:**
The delete dialog is localized.

**Actual Experience:**
The delete dialog is not localized.
![image](https://user-images.githubusercontent.com/41351993/66560389-e5cd6180-eb89-11e9-8d5c-a70602f05f91.png)

**More Info:**
Only verified this issue in Chinese (zh-CN).

**Comment by lukaschal** [comment]
Looks like hard-coded issue. Cloud explorer.

https://devdiv.visualstudio.com/DevDiv/_git/CloudExplorer?path=%2Fsrc%2FCloudHub%2Fts%2FStorageExplorer%2FAzureDataLakeStore%2FCommands%2FDeleteCommand.ts&version=GBmaster
