### ISSUE TITLE
The toolbar and editor of ADLS Gen1 accounts are not localized

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2041]
**Storage Explorer Version:** 1.10.1
**Build:** [20191010.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3128931)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** Chinese (zh-CN)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer using the command 'StorageExplorer.exe --lang=zh-CN'.
2. Open one ADLS Gen1 account -> Check the toolbar and editor.

**Expect Experience:**
The toolbar and editor are localized.

**Actual Experience:**
The toolbar and editor are not localized.
![image](https://user-images.githubusercontent.com/41351993/66561254-b4ee2c00-eb8b-11e9-8195-387aeb91e395.png)

**More Info:**
1. Only verified this issue in Chinese (zh-CN).
2. This issue also reproduces for **Collections**/ **Store Procedures**/ **Triggers**/ **User Defined Functions** under **Cosmos DB accounts.**
![image](https://user-images.githubusercontent.com/41351993/66562094-6f326300-eb8d-11e9-9423-56c6fd383937.png)

**Comment by lukaschal** [comment]
Localized 2 months ago.

File: loc\en\src\Standalone\resources\Azure.json
ID: 0; "Actions.Resources.LoadMore"
SRC: Load more

File: loc\en\src\components\se-managed-disks-extension\resources\ManagedDisksExplorer.json
ID: 0; "ButtonLoadMore"
SRC: Load more

Localized at 10/10.

File: loc\en\src\components\se-blob-extension\resources\BlobEditor.json
ID: 0; "TableView.PageLocationMessage"
SRC: Showing %1$s to %2$s of %3$s cached items
TGT: 캐시된 항목 %3$s개 중 %1$s~%2$s개를 표시하는 중

**Comment by lukaschal** [comment]
@v-xianya Still repro ?

**Comment by v-xianya** [comment]
@lukaschal 
This issue also reproduces on the new build 20200206.2.
