### ISSUE TITLE
Keep consistent dialogs when detaching one attached service and attached storage account 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2042]
**Storage Explorer Version:** 1.10.1
**Build:** [20191010.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3128931)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04
**Architecture:** ia32/x64
**Regression From:** Previous release (1.10.1)

**Steps to reproduce:**
1. Using SAS to attach one blob container and one storage account.
2. Try to detach the attached blob container and attached storage account.
3. Check the two detached dialogs.

**Expect Experience:**
Keep consistent dialogs.

**Actual Experience:**
Show inconsistent dialogs.
![image](https://user-images.githubusercontent.com/41351993/66564325-51b3c800-eb92-11e9-88cc-66096b520b16.png)

**More Info:**
Show the below dialogs in previous release (1.10.1).
![image](https://user-images.githubusercontent.com/41351993/66564491-b2430500-eb92-11e9-99ab-f33381c6968f.png)

**Comment by v-xianya** [comment]
This issue also reproduces on build 20191010.13. So we re-open it.

**Comment by craxal** [comment]
CloudExplorer reference was not updated in source.

**Comment by v-xianya** [comment]
This issue has been fixed on build 20191012.1. So we close it.
