### ISSUE TITLE
View All Snapshots Within A Storage Account

### ISSUE THREAD

**Issue by SimonWEastwood** [microsoft/AzureStorageExplorer#2043]
I would like to be able to view all snapshots in a storage account in a simple tree format or from within the explorer view window
so when I have may disks and may snapshots within a storage account I can see the hirachy of snapshots for each disk contained within the storage account and easily be able to drill down without having to highlight each disk individually to see its hirachy of snapshots

**Comment by MRayermannMSFT** [comment]
@SimonWEastwood is this request for unmanaged disks (aka page blobs) or are you talking about managed disks (aka the Azure resource type)?

**Comment by MRayermannMSFT** [comment]
@SimonWEastwood , I'm going to assume you mean unmanaged disks (page blobs). In that case, there isn't a feasible way for us to do this. Therefore we're going to close this request.

If you did not mean this, please open a new issue with more details about your request.
