### ISSUE TITLE
Nothing happens when trying to paste one blob 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2044]
**Storage Explorer Version:** 1.10.1
**Build:** [20191010.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3128931)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release (1.10.1)

**Steps to reproduce:**

1. Expand one storage account -> Blob Containers.
2. Create a new blob container -> Upload one blob to it.
3. Copy this blob and try to paste it to another blob container -> Check the result.

**Expect Experience:**
The blob can be pasted successfully.

**Actual Experience:**
Nothing happens.

**Comment by JasonYeMSFT** [comment]
AzCopy is going to replace the existing copy/paste feature for blobs. It is currently turned on if the "use azcopy" setting is enabled. However, the azcopy implementation hasn't been published, we will notify you when it is ready for testing.

**Comment by v-limu** [comment]
This issue has been fixed on build [20191012.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3136519). So we close it.
