### ISSUE TITLE
Show an odd editor when opening 'Query Builder'

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2045]
**Storage Explorer Version:** 1.10.1
**Build:** [20191010.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3128931)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release (1.10.1)

**Steps to reproduce:**

1. Expand one storage account -> Tables.
2. Create a new table -> Open this table and click 'Query' button on toolbar.
3. Check the editor.

**Expect Experience:**
The editor shows well.
![image](https://user-images.githubusercontent.com/54055206/66556542-0514c080-eb83-11e9-9cae-3627ff955fdf.png)

**Actual Experience:**
Show an odd editor.
![image](https://user-images.githubusercontent.com/54055206/66557326-448fdc80-eb84-11e9-9742-66029cd69cab.png)

**More Info:**
This issue also reproduces when opened 'Text editor'.
![image](https://user-images.githubusercontent.com/54055206/66565279-ac4e2380-eb94-11e9-922c-857812179f5d.png)

**Comment by craxal** [comment]
Table package needs to be updated. We will do that by Friday, Oct 11.

**Comment by v-xianya** [comment]
This issue has been fixed on build 20191012.1. So we close it.
