### ISSUE TITLE
Add account: Self signed certificate in certificate chain

### ISSUE THREAD

**Issue by danSpotter** [microsoft/AzureStorageExplorer#2046]
**Storage Explorer Version**: <1.10.1>
**Build Number**: <20190919.2>
**Platform/OS**: <Windows 10>
**Architecture**: < x64>

## Bug Description ##

Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: xxxxxx, Error: {
  "name": "Error",
  "message": "self signed certificate in certificate chain",
  "stack": "Error: self signed certificate in certificate chain\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at TLSSocket.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at TLSSocket.emit (events.js:182:13)\n    at TLSSocket._finishInit (_tls_wrap.js:631:8)",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}

**Comment by JasonYeMSFT** [comment]
Have you imported the certificates in Storage Explorer? We have a section of instructions on how to do this in our trouble shooting guide.
[Troubleshooting Guide: self-signed certificates errors](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C1804#error-self-signed-certificate-in-certificate-chain-and-similar-errors)

**Comment by danSpotter** [comment]
I couldn't find any self signed certs with the instructions provided.

**Comment by MRayermannMSFT** [comment]
@danSpotter , have you tried talking to your network admins? Did you try using the --ignore-certificate-errors flag?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
