### ISSUE TITLE
Transfers are queued randomly

### ISSUE THREAD

**Issue by jeeva86** [microsoft/AzureStorageExplorer#2047]
**Storage Explorer Version**: 1.10.1
**AzCopy Version**: 10.2.1
**Build Number**: 20190919.2
**Platform/OS**: macOS Mojave
**Architecture**: x64

## Bug Description ##
Jobs are queued for no reason.

## Steps to Reproduce ##
This is hard to reproduce, but I've noticed this to occur when I experience #2029. Once that transfer fails gets manually canceled, I'm unable to submit any more jobs. I suppose a lock is being held somewhere. I'd have to restart the app to get jobs going again.

## Expected Experience ##
Queued jobs to begin or provide a reason as to what are they queued behind.

## Actual Experience ##
Jobs are queued with no explanation.

**Comment by JasonYeMSFT** [comment]
AzCopy only allows one job being queued at a time. If an old job hangs, it may blocks future jobs being queued. What were you seeing when you manually cancel from the activity log? Does it show a canceled message or something else?

**Comment by JasonYeMSFT** [comment]
Are you still experiencing this issue? We cannot reproduce this issue so far.
