### ISSUE TITLE
The localized 'Upload' on one disk toolbar is not accurate

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2049]
**Storage Explorer Version:** 1.10.1
**Build:** [20191011.12](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3133776)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** Chinese (zh-CN) 
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open Settings panel -> Preference (Locale) -> Select **Chinese (simplified)** as application language -> Restart Storage Explorer.
3. Expand Disks -> Open one disk.
4. Check the localized 'Upload' on the toolbar.

**Expect Experience:**
The localized 'Upload' shows '上传'.

**Actual Experience:**
The localized 'Upload' shows '上载'.
![image](https://user-images.githubusercontent.com/41351993/66635050-fa206580-ec40-11e9-958e-4d8af7160e82.png)

**More Info:**
1. This issue doesn't reproduce in Chinese(zh-TW).
2. Only verified this issue in Chinese(zh-CN) and Chinese(zh-Tw).

**Comment by lukaschal** [comment]
On review.

File: loc\en\src\components\se-blob-extension\resources\BlobEditor.json
ID: 0; "OptionFileWatcherUpload"
SRC: Upload
TGT: 上载

File: loc\en\src\components\se-managed-disks-extension\resources\ManagedDisksExplorer.json
ID: 0; "ToolbarCreateDisk"
SRC: Upload
TGT: 上载

**Comment by lukaschal** [comment]
Fixed at 10/15.

**Comment by MRayermannMSFT** [comment]
Need to update package.

**Comment by MRayermannMSFT** [comment]
Both buttons now have 上传
