### ISSUE TITLE
The localized 'OK' button is too large on About page

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2050]
**Storage Explorer Version:** 1.10.1
**Build:** [20191011.12](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3133776)
**Branch:** master
**Platform/OS:** Windows 10
**Language:** Chinese (zh-CN)/ Chinese (zh-TW)
**Architecture:** ia32
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open Settings panel -> Preference (Locale) -> Select **Chinese (simplified)** as application language -> Restart Storage Explorer.
3. Click Help menu -> Open About page.
4. Check the localized 'OK' button on About page.

**Expect Experience:**
The localized 'OK' button is normal.

**Actual Experience:**
The localized 'OK' button is too large.
![image](https://user-images.githubusercontent.com/41351993/66636193-42408780-ec43-11e9-9b10-db58e5c34dad.png)

**More Info:**
1. This issue doesn't reproduce on Linux and Mac.
2. Only verified this issue in Chinese(zh-CN) and Chinese(zh-TW).

**Comment by janbaltus** [comment]
@craxal  loc team has only json files available and cannot control UI of dialogs

**Comment by JasonYeMSFT** [comment]
@v-xianya Could you please find a system dialog that shows the first type of buttons? Also could you please check if this type of buttons occur for other languages?

**Comment by v-xianya** [comment]
Hi @JasonYeMSFT Thanks for your attention about this issue.
1. For now, I haven't seen a system dialog that shows the first type of buttons.
2. This type of buttons also occur for **Russian/ Korean/ Spanish/ Turkish**.

**Comment by MRayermannMSFT** [comment]
By design.

**Comment by MRayermannMSFT** [comment]
(Windows is choosing this behavior)
