### ISSUE TITLE
Add '…' to 'Edit property' on Add Entity dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2051]
**Storage Explorer Version:** 1.10.1
**Build:** [20191011.12](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3133776)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/ macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Tables.
2. Create a table -> Click 'Add'  -> Click 'Add Property'.
3. Check the pencil icon's tooltip. 

**Expect Experience:**
Show 'Edit property...'.

**Actual Experience:**
Show 'Edit property'.
![image](https://user-images.githubusercontent.com/41351993/66637001-cfd0a700-ec44-11e9-9ba7-a9f0d88f5f05.png)

**Comment by craxal** [comment]
I don't think it's customary to put ellipses on tooltips. Just menu items.
