### ISSUE TITLE
The localized 'Dequeue Count' is different in the queue editor and View Message dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2053]
**Storage Explorer Version:** 1.10.1
**Build:** [20191011.12](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3133776)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** Chinese (zh-CN)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open Settings panel -> Preference (Locale) -> Select **Chinese (simplified)** as application language -> Restart Storage Explorer.
3. Expand one storage account -> Queues.
4. Create a queue -> Add a message to it.
5. Select 'View Message' and make sure prompt a dialog.
6. Check the localized 'Dequeue count' in the dialog and editor.

**Expect Experience:**
The localized 'Dequeue Count' keeps consistent.

**Actual Experience:**
The localized 'Dequeue Count' is different.
![image](https://user-images.githubusercontent.com/41351993/66638520-aebd8580-ec47-11e9-9627-a328defe1ed5.png)

**More Info:**
1. This issue doesn't reproduce in Chinese(zh-TW).
2. Only verified this issue in Chinese(zh-CN) and Chinese(zh-TW).

**Comment by lukaschal** [comment]
On review.

**Comment by v-xianya** [comment]
This issue has been fixed on build 20191018.3.  So we close it.
