### ISSUE TITLE
Update 'brackets' to 'quotes' for the localized ‘Opt Out of Sending Telemetry’ on Telemetry Settings page

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2054]
**Storage Explorer Version:** 1.10.1
**Build:** [20191011.12](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3133776)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** Chinese (zh-TW)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open Settings panel -> Preference (Locale) -> Select **Chinese (traditional)** as application language -> Restart Storage Explorer.
3. Click Help menu -> Open Telemetry Settings page.
4. Check the localized **Opt Out of Sending Telemetry** at the last part of the page.

**Expect Experience:**
The localized **Opt Out of Sending Telemetry** is surrounded by quotes.

**Actual Experience:**
The localized **Opt Out of Sending Telemetry** is surrounded by brackets.
![image](https://user-images.githubusercontent.com/41351993/66639898-681d5a80-ec4a-11e9-94ab-c4ef4eb7548f.png)

**More Info:**
1. Only verified this issue in Chinese(zh-CN) and Chinese(zh-TW).
2. This issue doesn't reproduce in Chinese(zh-CN).
![image](https://user-images.githubusercontent.com/41351993/66640817-37d6bb80-ec4c-11e9-95ae-19e17c15244d.png)

**Comment by craxal** [comment]
@weeteckt CTI has been opening a lot of these bracket/quote bugs against Chinese (Traditional). What's the correct thing to do here? Can we communicate this to the translation team?

**Comment by v-xianya** [comment]
This issue still reproduces on latest build 20191012.1. So we re-open it.

**Comment by johnliu2016** [comment]
Checking with Linguistic

**Comment by lukaschal** [comment]
Linguistic answer:

Please note that using [ ] for UIs has always been the way in Traditional Chinese instructed by the Microsoft Style Guide. And this approach is not just for CnE products, but for many other MS products and services. The related rules are described under the section "Punctuation" of the Chinese (Traditional) Style Guide.

**Comment by craxal** [comment]
@jinglouMSFT As long as we're consistent, I'm fine either way.

@lukaschal Please make sure we are using the same punctuation in all strings. Are square brackets used in place of single and double quotes?

**Comment by lukaschal** [comment]
@craxal It is used only for double quotes, but zh-tw uses this type of writing only for UI strings. So in some cases it is not consistent, but correct according to MS style guide.

**Comment by MRayermannMSFT** [comment]
Closing.
