### ISSUE TITLE
The localized 'If disabled' is different on Services page

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2055]
**Storage Explorer Version:** 1.10.1
**Build:** [20191011.12](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3133776)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** Chinese (zh-TW)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open Settings panel -> Preference (Locale) -> Select **Chinese (traditional)** as application language -> Restart Storage Explorer.
3. Open Settings panel -> Open Services page.
4. Check the localized 'If disabled'.

**Expect Experience:**
The localized 'If disabled' is consistent.

**Actual Experience:**
The localized 'If disabled' is different.
![image](https://user-images.githubusercontent.com/41351993/66643596-a36f5780-ec51-11e9-9d60-ee3cf151a0a8.png)

**More Info:**
1. This issue doesn't reproduce in Chinese(zh-CN).
2. Only verified this issue in Chinese(zh-CN) and Chinese(zh-TW).

**Comment by johnliu2016** [comment]
It's on linguistic review

**Comment by JasonYeMSFT** [comment]
We don't consider this to be causing confusion. Won't fix it.
