### ISSUE TITLE
The 'Property Name' is not localized on Add Entity dialog

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2057]
**Storage Explorer Version:** 1.10.1
**Build:**[ 20191011.12](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3133776)
**Branch:** master
**Platform/OS:** Windows 10// Linux Ubuntu 19.04/macOS High Sierra
**Language:** Chinese (zh-TW)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open Settings panel -> Preference (Locale) -> Select **Chinese (traditional)** as application language -> Restart Storage Explorer. 
3. Expand one storage account -> Tables.
4. Create a new table -> Open it and click 'Add' button.
5. Check the 'Property Name' on the Add Entity dialog.

**Expect Experience:**
The 'Property Name' is localized.

**Actual Experience:**
The 'Property Name' is not localized.
![image](https://user-images.githubusercontent.com/54055206/66642128-a6b51400-ec4e-11e9-9fa9-fff05185688e.png)

**More Info:**

1. This issue doesn't reproduce in Chinese(zh-CN).
2. Only verified this issue in Chinese(zh-CN) and Chinese(zh-TW).

**Comment by craxal** [comment]
String needs translation work.

**Comment by lukaschal** [comment]
On review.

File: loc\en\src\Standalone\resources\ImportEntitiesDialog.json
ID: 0; "AttributeNameLabel"
SRC: Property Name
TGT: Property Name

File: loc\en\src\Standalone\resources\EntityEditorDialog.json
ID: 0; "LabelPropertyName"
SRC: Property Name
TGT: Property Name

**Comment by lukaschal** [comment]
Localized on all languages now.

**Comment by v-xianya** [comment]
This issue has been fixed on build 20191018.3. So we close it.
