### ISSUE TITLE
Show ellipsis next to localized 'Table Statistics' button in Chinese(zh-TW)

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2058]
**Storage Explorer Version:** 1.10.1
**Build:**[ 20191011.12](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3133776)
**Branch:** master
**Platform/OS:** Windows 10// Linux Ubuntu 19.04/macOS High Sierra
**Language:** Chinese (zh-TW)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open Settings panel -> Preference (Locale) -> Select **Chinese (traditional)** as application language -> Restart Storage Explorer. 
3. Expand one storage account -> Tables -> Create a new table.
4. Open it and check the localized 'Table Statistics' button on the toolbar.

**Expect Experience:**
There no ellipsis shows next to localized 'Table Statistics' button.

**Actual Experience:**
Show ellipsis next to localized 'Table Statistics' button.
![image](https://user-images.githubusercontent.com/54055206/66642410-470b3880-ec4f-11e9-910f-e4013b00d445.png)

**More Info:**

1. This issue doesn't reproduce in Chinese(zh-CN).
2. Only verified this issue in Chinese(zh-CN) and Chinese(zh-TW).

**Comment by craxal** [comment]
@v-limu The Chinese string is likely longer than the English string, and button sizes are based on English string lengths. Please check the English string. If the ellipsis is still there, please reopen. Otherwise, this is by design.
