### ISSUE TITLE
The translation of theme 'Light' is not correct under View menu

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2059]
**Storage Explorer Version:** 1.10.1
**Build:** [20191012.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3136519&view=results)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** Chinese(zh-TW)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open Settings panel -> Regional Settings -> Select **Chinese (traditional)** as application language -> Restart Storage Explorer.
3. Click the localized **View** menu -> Click the localized **Theme**.
4. Check the translation of theme 'Light'.

**Expect Experience:**
The theme 'Light' is translated to ‘淺色'.

**Actual Experience:**
The theme 'Light' is translated to '光'.
![image](https://user-images.githubusercontent.com/41351993/66697738-fd802380-ed0a-11e9-8a56-3f9e9121915e.png)

**More Info:**
1. This issue doesn't reproduce in Chinese(zh-CN).
2. This issue doesn't reproduce on Setting panel.
![image](https://user-images.githubusercontent.com/41351993/66697759-391aed80-ed0b-11e9-84d2-c99967917d85.png)

**Comment by lukaschal** [comment]
On review.

File: loc\en\src\Standalone\resources\Shell.json
ID: 0; "MenuThemeLight"
SRC: Light
TGT: 光

**Comment by v-xianya** [comment]
This issue has been fixed on build 20191017.3. So we close it.
