### ISSUE TITLE
Keep a consistent order of themes between Chinese and English on Settings panel

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2060]
**Storage Explorer Version:** 1.10.1
**Build:** [20191012.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3136519&view=results)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:**  Chinese(zh-CN)/ Chinese(zh-TW)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open Settings panel -> Regional Settings -> Select **Chinese (simplified)** as application language -> Restart Storage Explorer.
3. Open Settings panel -> Application -> Appearance (Theme).
4. Check the Theme dropdown list.

**Expect Experience:**
Keep a consistent order of themes between Chinese and English on Settings panel.

**Actual Experience:**
Show an inconsistent order of themes between Chinese and English on Settings panel.
![image](https://user-images.githubusercontent.com/41351993/66698048-4933cc80-ed0d-11e9-85f6-2212baefe6b2.png)

**More Info:**
1. The order of themes is the same between Chinese and English under View menu.
![image](https://user-images.githubusercontent.com/41351993/66698075-7c765b80-ed0d-11e9-92f6-27e90a666bd6.png)

**Comment by janbaltus** [comment]
@craxal Localization cannot change order of elements under UI.

**Comment by v-xianya** [comment]
This issue has been fixed on build 20191017.3. So we close it.
