### ISSUE TITLE
Update the localized 'System Properties' to '系统屬性' for one ADLS Gen2 blob

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2061]
**Storage Explorer Version:** 1.10.1
**Build:** [20191012.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3136519&view=results)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** Chinese(zh-TW)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open Settings panel -> Regional Settings -> Select **Chinese (traditional)** as application language -> Restart Storage Explorer.
3. Expand an ADLS Gen2 storage account -> Blob Containers.
4. Select one blob container which has one blob at least.
5. Right one blob and open its Properties dialog.
6. Check the localized string on the dialog.

**Expect Experience:**
 The Localized 'System Properties' shows '系统屬性'.

**Actual Experience:**
The localized 'System Properties' shows '系統內容'.
![image](https://user-images.githubusercontent.com/41351993/66698358-03c4ce80-ed10-11e9-9e8a-7a7ddb88c714.png)

**More Info:**
1. This issue reproduces for the localized 'User Properties'.
2. This issue doesn't reproduce in Chinese (zh-CN).
![image](https://user-images.githubusercontent.com/41351993/66698467-fb20c800-ed10-11e9-955d-9df58f78675f.png)

**Comment by lukaschal** [comment]
On review.

File: loc\en\src\components\se-adls2-extension\resources\FileSystemEditor.json
ID: 0; "LabelSystemProperties"
SRC: System Properties
TGT: 系統內容

**Comment by v-xianya** [comment]
**More Info:**
1. '系統內容' has been updated to '系統屬性'.
2. Need to update ‘使用者內容’ to ‘使用者屬性’.
![image](https://user-images.githubusercontent.com/41351993/66972625-ba85cd80-f0c7-11e9-93f9-15634eb79965.png)

**Comment by lukaschal** [comment]
On review.

File: loc\en\src\components\se-adls2-extension\resources\FileSystemEditor.json
ID: 0; "LabelUserProperties"
SRC: User Properties
TGT: 使用者內容

**Comment by lukaschal** [comment]
Fixed as suggested.

**Comment by MRayermannMSFT** [comment]
Need to update package.

**Comment by JasonYeMSFT** [comment]
Verified as fixed.
