### ISSUE TITLE
A strange symbol '%1$s' shows in localized descriptions on break lease dialog 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2062]
**Storage Explorer Version:** 1.10.1
**Build:** [20191012.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3136519&view=results)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** Chinese(zh-CN)/ Chinese(zh-TW)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open Settings panel -> Regional Settings -> Select **Chinese (traditional)** as application language -> Restart Storage Explorer.
3. Expand one Non-ALDS Gen2 storage account -> Blob Containers.
4. Select one blob container which contains at least two blobs.
5. Select two blobs and acquire lease for them.
6. Select the two leased blobs then try to break lease for them at the same time.
7. Check the localized descriptions on the break lease dialog.

**Expect Experience:**
No strange symbol shows in localized descriptions.

**Actual Experience:**
A strange symbol shows in localized descriptions.
![image](https://user-images.githubusercontent.com/41351993/66698613-01637400-ed12-11e9-993e-1de6be535408.png)

**Comment by lukaschal** [comment]
@craxal Localized same way as source.

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer?path=%2Floc%2Floc%2Fzh-Hans%2Fsrc%2Fcomponents%2Fse-blob-extension%2Fresources%2FBlobEditor.json.lcl&version=GBmaster

ID: 0; "Dialog.BreakLeaseMultipleWithoutVHDMainText"
SRC: Breaking leases on blobs will allow them to be deleted or modified. To proceed with breaking the leases, please enter '%1$s'.
TGT: 中斷 Blob 上的租用會讓其得以刪除或修改。若要繼續中斷租用，請輸入 '%1$s'。

**Comment by craxal** [comment]
Make sure we're using `sprintf`, and not `vsprintf`.
