### ISSUE TITLE
Always keep queued when trying to upload files using AzCopy

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2063]
**Storage Explorer Version:** 1.10.1
**Build:** [20191012.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3136519&view=results)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** Chinese(zh-CN)/ Chinese(zh-TW)
**Architecture:** ia32/x64
**Regression From:** Previous release (1.10.1)

**Steps to reproduce:**
1. Make sure AzCopy is checked.
2. Expand one storage account -> Blob Containers.
3. Create a new blob container -> Try to upload one file to it.
4. Check the result.

**Expect Experience:**
Upload successfully.
![image](https://user-images.githubusercontent.com/41351993/66699029-dbd86980-ed15-11e9-9291-1a3ee100a231.png)

**Actual Experience:**
Always keep queued.
![image](https://user-images.githubusercontent.com/41351993/66699028-d5e28880-ed15-11e9-9173-3cc8f209c5b9.png)

**More Info:**
This issue also reproduces when downloading one blob with AzCopy checked.
![image](https://user-images.githubusercontent.com/41351993/66699075-2a860380-ed16-11e9-8344-f0ca9fabab0c.png)

**Comment by JasonYeMSFT** [comment]
This will be resolved by tonight's (10/14) build.

**Comment by v-xianya** [comment]
This issue has been fixed on build 20191015.4. So we close it.
