### ISSUE TITLE
Keep an uniform font for localized characters

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2064]
**Storage Explorer Version:** 1.10.1
**Build:** [20191012.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3136519&view=results)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** Chinese(zh-CN)/ Chinese(zh-TW)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Bug Description:**
Show different fonts for some localized characters.

**In Chinese (zh-CN)**
![image](https://user-images.githubusercontent.com/41351993/66699257-bc424080-ed17-11e9-8b7d-bd9b05a77bd0.png)
![image](https://user-images.githubusercontent.com/41351993/66699262-c9f7c600-ed17-11e9-92dc-b26e3798ac80.png)
![image](https://user-images.githubusercontent.com/41351993/66699268-d11ed400-ed17-11e9-8f0b-09a9bc26e426.png)
**In Chinese (zh-TW)**
![image](https://user-images.githubusercontent.com/41351993/66699272-d5e38800-ed17-11e9-94f5-0e8a0c008214.png)
![image](https://user-images.githubusercontent.com/41351993/66699273-d9770f00-ed17-11e9-9e12-f257c5ef2dc9.png)

**Expect Experience:**
Keep an uniform font for localized characters.

**Actual Experience:**
Show different fonts for localized characters.

**Comment by craxal** [comment]
Won't fix. Many of the UI elements are system objects, which we can't control from the application. 

@v-xianya We've found that if you install and load the matching OS language pack, fonts render consistently. If this doesn't fix the problem, please reopen, and we'll revisit.
