### ISSUE TITLE
Can't change the Storage Explorer language with command 'storage-explorer --lang=zh-TW' 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2065]
**Storage Explorer Version:** 1.10.1
**Build:** [20191012.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3136519)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** Chinese(zh-TW)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open Settings panel -> Regional Settings -> Select **English** as application language -> Close Storage Explorer.
3. Use **'storage-explorer --lang=zh-TW'** command to open Storage Explorer.
4. Check the result.

**Expect Experience:**
 Show Chinese(traditional) as the application language.

**Actual Experience:**
The application language doesn't shows Chinese(traditional).

**More Info:**

1. Still shows English as the application language when using 'storage-explorer --lang=pt-BR' command to launch Storage Explorer.
2. Still shows English as the application language when using 'storage-explorer --lang=pt-PT' command to launch Storage Explorer.

**Comment by janbaltus** [comment]
@craxal this command used to work in older builds.
This is not localization related

**Comment by craxal** [comment]
@janbaltus The localization label is used for general language issues. The translation label is for string translations. So this _is_ a localization issue as defined here.

**Comment by MRayermannMSFT** [comment]
@v-limu , craig just checked this bug and could not reproduce. Can you please try again with today's latest build? Thanks.

**Comment by v-limu** [comment]
Hi @MRayermannMSFT I verified this issue on a VM which system language is **Chinese traditional** with build [20191021.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3162964). This issue still reproduces and the details as below.

**Steps to Reproduce:**

1. Select English as application language -> Close Storage Explorer.
2. Use 'storage-explorer --lang=zh-TW' command to open Storage Explorer.
3. Observe the Storage Explorer language.

**Actual Experience:**
![image](https://user-images.githubusercontent.com/54055206/67269962-46de2900-f4ea-11e9-9d0f-2198f24d778f.png)

**Expect Experience:**
![image](https://user-images.githubusercontent.com/54055206/67269703-c61f2d00-f4e9-11e9-959d-f4668eb5318e.png)

**More Info:**
Still shows English as the application language when using 'storage-explorer --lang=pt-BR'/ 'storage-explorer --lang=pt-PT' command to launch Storage Explorer.

**Comment by jinglouMSFT** [comment]
@v-limu What I am seeing from above is that on a traditional Chinese OS, you actually saw Storage Explorer in simplified Chinese. Is that correct?  If that is the case, could you do an experiment for me?  Close Storage Explorer, then switch your IME to Chinese (from English), in an editor, say Notepad or Word, enter some Chinese characters.  Do you see traditional Chinese or simplified Chinese?

**Comment by v-limu** [comment]
Hi @jinglouMSFT  
1. For the first question, I mean that when i run command _**'storage-explorer --lang=zh-TW'**_ to launch Storage Explorer, found Storage Explorer language is not traditional Chinese.
[ To avoid the systems effect, I verified this issue on the matched OS language (**traditional Chinese OS**) , But Storage Explorer language is also not Chinese traditional. ]

2. Show **Chinese traditional** when typing some Chinese characters in Notepad with Chinese IME on a traditional Chinese OS.

**Comment by craxal** [comment]
@v-limu I will continue to investigate. What if you use "zh-Hant"? Does that work as expected?

**Comment by craxal** [comment]
Never mind. I found the problem. In ResourceProvider.ts:

```ts
 let langArgMatch = process.argv.join(" ").match(/^.*--lang=(\w+).*$/);
```

The problem is the regular expression is only looking for _word_ characters after the =. Hyphens aren't word characters, so it's only getting the "zh" or "pt" part of the language string, which we have default regions for.
