### ISSUE TITLE
Pop up an error dialog when deleting one blob with AzCopy checked

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2066]
**Storage Explorer Version:** 1.10.1
**Build:** [20191012.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3136519)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release (1.10.1)

**Steps to reproduce:**

1. Expand a non-ADLS Gen2 account -> Blob Containers.
2. Make sure the AzCopy is checked.
3. Create a new blob container -> Upload a blob to it.
4. Delete this blob and check the result.

**Expect Experience:**
The blob can be deleted successfully.

**Actual Experience:**
Pop up an error dialog.
![image](https://user-images.githubusercontent.com/54055206/66699406-33c49f80-ed19-11e9-98bf-a1ea45485abc.png)

**More Info:**
This issue also reproduces for delete the snapshots of the blob.

**Comment by JasonYeMSFT** [comment]
This will be resolved by tonight's (10/14) build.

**Comment by v-limu** [comment]
This issue has been fixed on build [20191015.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3142624). So we close it.
