### ISSUE TITLE
There are strings haven't been translated in Application page on Settings panel

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2067]
**Storage Explorer Version:** 1.10.1
**Build:** [20191012.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3136519)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** Chinese(zh-TW)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open Settings panel -> Regional Settings -> Select **Chinese(Traditional)** as application language -> Restart Storage Explorer.
3. Open Settings panel -> Application.
4. Check the strings on this page.

**Expect Experience:**
The strings that need to be translated have been localized.

**Actual Experience:**
1. The 'Proxy' and its description are not localized.
![image](https://user-images.githubusercontent.com/54055206/66698964-594faa00-ed15-11e9-9e2a-eabba5a50853.png)
2. The 'Regional Settings' and its description are not localized.
![image](https://user-images.githubusercontent.com/54055206/66698976-800de080-ed15-11e9-9b6d-e262e1b6405d.png)
3. The string 'Use device code flow sign-in' is not localized.
![image](https://user-images.githubusercontent.com/54055206/66698985-8d2acf80-ed15-11e9-89d8-dacdf27a2808.png)

**More Info:**

1. This issue also reproduces in Chinese(zh-CN).
2. Only verified this issue in Chinese(zh-CN) and Chinese(zh-TW).

**Comment by lukaschal** [comment]
New string from 10/11/2019. On translation.

File: loc\en\src\Standalone\resources\Shell.json
ID: 0; "TitleSignInDeviceCodeFlow"
SRC: Use device code flow sign-in

**Comment by lukaschal** [comment]
Localized by this commit.

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer/commit/36491ccfebba8b26249bafdeaff80d21b341a45b?_a=compare&path=%2Floc%2Floc%2Fzh-Hans%2Fsrc%2FStandalone%2Fresources%2FShell.json.lcl

**Comment by MRayermannMSFT** [comment]
Verified as fixed.
