### ISSUE TITLE
Make New Folder default name already highlighted for rapid over typing

### ISSUE THREAD

**Issue by golfalot** [microsoft/AzureStorageExplorer#2071]
Using Storage Account V2 with Data Lake Storage enabled.
When Click the New Folder button, in subsequent dialog windows please make the default "New Folder" text already highlighted. Thank you!

**Comment by golfalot** [comment]
**Storage Explorer Version**: 1.10.1
**Build Number**: 20190919.2
**Platform/OS**: Windows 10
**Architecture**: ia32
**Regression From**:  First time user

**Comment by MRayermannMSFT** [comment]
![2071](https://user-images.githubusercontent.com/21112697/83549587-65fa5b80-a4ba-11ea-8288-70a14e42127b.gif)

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
