### ISSUE TITLE
"Error: write ECONNABORTED" while uploading VHD to storage account using Storage explorer

### ISSUE THREAD

**Issue by RamBorude** [microsoft/AzureStorageExplorer#2074]
{
  "name": "Error",
  "message": "write ECONNABORTED",
  "stack": "Error: write ECONNABORTED\n    at WriteWrap.afterWrite [as oncomplete] (net.js:788:14)",
  "errno": "ECONNABORTED",
  "code": "ECONNABORTED",
  "syscall": "write"
}

**Comment by JasonYeMSFT** [comment]
Can you verify that if there is any network limitation on your host machine? It's possible that your host machine aborts the operation because of the bandwidth usage.

**Comment by RamBorude** [comment]
Hi Jason,

Thanks for your respond. Sorry didn’t mention back that It’s resolved and was network issue.

Thanks
Ram
