### ISSUE TITLE
Unable to rename or download blobs with V 1.10.1

### ISSUE THREAD

**Issue by mrevow** [microsoft/AzureStorageExplorer#2075]
**Storage Explorer Version**:  V 1.10.1 AzCopy V 10.2.1
**Build Number**: 20190919.2
**Platform/OS**:  Windows 10
**Architecture**:  x64
**Regression From**:  Not sure what I had before but works in 1.8.1

## Bug Description ##
Unable to rename blobs using the UI

## Steps to Reproduce ##
Navigate to a blob in our store
Click Rename (or right click rename)
Type in a change name in 'New name' box
Click 'Rename'

## Expected Experience ##
The blob should be renamed

## Actual Experience ##
Error dialogue pops up (See file for screen shot)
File is not renamed
## Additional Context ##
Just clicked on the notice to install new version previously was working fine
![ErrorWhenRenamingBlob](https://user-images.githubusercontent.com/8324438/66783655-3942f680-ee8d-11e9-8115-0b7496e550f7.png)

**Comment by mrevow** [comment]
Update -  I get a similar error when attempting to download a blob.
Tried rebooting my machine in case this is a temporary issue but still have the problem

![ErrorWhenDownloadingBlob](https://user-images.githubusercontent.com/8324438/66784759-34cc0d00-ee90-11e9-8508-0412346cdd66.png)

**Comment by jinglouMSFT** [comment]
Rename is basically a copy and delete.  So the fact that you got the same error for download and rename sounds weird.  Were you able to download to a different folder?  Also, do you have AzCopy enabled?

**Comment by mrevow** [comment]
@jinglouMSFT  No  it fails for all operations. even just trying to delete a blob fails. This started immediately after  I upgraded to  1.10.1. Would the upgrade have disable azcopy? help says I an using azcopy 10.21.

Everything still works if I use the browser explorer through the portal

**Comment by jinglouMSFT** [comment]
If you don't mind trying something, can you try to close Storage Explorer, then delete %AppData%/StorageExplorer.  Then restart Storage Explorer.  Please note, if you have ever imported any SSL certificates, back up the contents of the certs directory. Later, you can use the backup to reimport your SSL certificates.  Deleting the folder will also remove your attached account or storage resources.

**Comment by mrevow** [comment]
Thanks @jinglouMSFT. Yes deleting that and restarting seems to have fixed the issue

**Comment by jinglouMSFT** [comment]
Glad it worked. Closing the issue.
