### ISSUE TITLE
Show a confusing log message when copying one blob

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2077]
**Storage Explorer Version:** 1.10.1
**Build:** [20191015.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3142624)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release (1.10.1)

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Expand one Non-ADLS Gen2 storage account -> Blob Containers.
3. Select one blob container which contains one blob at least -> Copy this blob then paste it to another blob container.
4.  Check the log message in Activities panel.

**Expect Experience:**
Show a clear log message in Activities panel.

**Actual Experience:**
Show a confusing log message in Activities panel.
![image](https://user-images.githubusercontent.com/41351993/66822906-bc407b80-ef77-11e9-98ea-3e0a0b242000.png)

**Comment by craxal** [comment]
@v-xianya Seems fine to me. Can you clarify? What is confusing about the log message?

**Comment by JasonYeMSFT** [comment]
We actually had a discussion about the log message and decided to make it that way. We thought the old string was too verbose.

**Comment by v-xianya** [comment]
Hi @craxal @JasonYeMSFT 
1. When we using AzCopy to Copy&Paste, show the below log message.
 we **can't intuitively see** the copy operation from the log message.
![image](https://user-images.githubusercontent.com/41351993/66883554-eee28680-f000-11e9-8156-9d022b165f8f.png)

2.  Before we using AzCopy to Copy&Paste, the log message shows like below.
![image](https://user-images.githubusercontent.com/41351993/66883323-1f75f080-f000-11e9-9a7d-e854b805834b.png)

**Comment by JasonYeMSFT** [comment]
This is by design. Upload, download and copy/paste are now all considered transfers.
