### ISSUE TITLE
Use a verb singular form at the beginning of one sentence

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2078]
**Storage Explorer Version:** 1.10.1
**Build:** [20191015.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3142624)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open Settings panel -> Transfers.
3. Check the descriptions under **Maximum transfer rate** & **Network Concurrency** & **File Concurrency** parts.

**Expect Experience:**
Use a verb prototype at the beginning of one sentence.

**Actual Experience:**
Use a verb singular form at the beginning of one sentence.
![image](https://user-images.githubusercontent.com/41351993/66824017-ff035300-ef79-11e9-8996-f1f83299dfa4.png)

**Comment by MRayermannMSFT** [comment]
Won't fix. We're taking these strings directly from AzCopy, so we're going to defer to their grammar.
