### ISSUE TITLE
 The blob folder's name is truncated on the editor after opening it

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2079]
**Storage Explorer Version:** 1.10.1
**Build:** [20191015.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3142624)
**Branch:** master
**Platform/OS:** Linux Ubuntu 19.04
**Architecture:** ia32/x64
**Regression From:** Previous release

**Steps to reproduce:**

1. Expand a non-ADLS Gen2 account -> Blob Containers.
2. Create a new blob container -> Upload a folder to it.
3. Open this folder and check whether the folder's name shows completely or not on the editor.

**Expect Experience:**
The folder's name shows completely.
![image](https://user-images.githubusercontent.com/54055206/66819237-39b4bd80-ef71-11e9-8ddb-7062b0d3d696.png)

**Actual Experience:**
 The folder's name is truncated.
![image](https://user-images.githubusercontent.com/54055206/66819248-3cafae00-ef71-11e9-8ce8-a3efa492ac7b.png)

**More Info:**
This issue doesn't reproduce on Windows & Mac.

**Comment by craxal** [comment]
I don't think this is a regression. The breadcrumbs have always done this if the window gets small enough. Is the problem because the search bar is too long?

**Comment by v-limu** [comment]
This issue has been fixed on build [20191018.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3156019). So we close it.
