### ISSUE TITLE
No 'Copy Conflict' dialog pops up when pasting an exist folder

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2080]
**Storage Explorer Version:** 1.10.1
**Build:** [20191015.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3142624)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release

**Steps to reproduce:**

1. Expand a non-ADLS Gen2 account -> Blob Containers.
2. Create a new blob container -> Upload a folder with files to it.
3. Copy the folder and paste it to this blob container.
4. Check the result.

**Expect Experience:**
 Pop up a 'Copy Conflict' dialog.
![image](https://user-images.githubusercontent.com/54055206/66820121-ab413b80-ef72-11e9-982b-0c81b72b54db.png)

**Actual Experience:**
No 'Copy Conflict' dialog pops up.
![image](https://user-images.githubusercontent.com/54055206/66821230-abdad180-ef74-11e9-98fd-865aee6398b7.png)

**More Info:**

1. This issue doesn't reproduce for files.
2. The pasted folder appears in the original folder.
![image](https://user-images.githubusercontent.com/54055206/66820860-04f63580-ef74-11e9-8b55-a1ecc93bac8a.png)

**Comment by craxal** [comment]
@v-limu Not sure I understand this bug. Can you be more precise in your repro steps, please? Tell me exactly what folders you create and where, what buttons you click, etc.

**Comment by JasonYeMSFT** [comment]
The blobs are pasted to the wrong location, right? The conflict resolution should work fine.

**Comment by JasonYeMSFT** [comment]
Needs to publish a new package for the fix.

**Comment by v-xianya** [comment]
This issue has been fixed on build 20191021.2. So we close it.
