### ISSUE TITLE
 [loc][Query][AzureStorageExplorer] Localizability of 0; "AriaColumn"/"AriaRow"/ 0; "AriaSelectedCount"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/AzureStorageExplorer#2082]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Can you help, please?
Thanks!

Source:
column %1$s

File Name:
loc\en\src\components\se-managed-disks-extension\resources\ManagedDisksExplorer.json

Resource ID:
0; "AriaColumn"

Query:
Please, define placeholder in order to translate properly. Same for string:
row %1$s 0; "AriaRow"
%1$s selected 0; "AriaSelectedCount"

**Comment by craxal** [comment]
The placeholder in `AriaColumn` is the name of a column when examining a data table. For example, if I was examining a storage table's partition key column, this string would read "column PartitionKey".

The placeholder for `AriaRow` is a row index. For example "row 5".

The placeholder for `AriaSelectedCount` is a number. For example, "12 selected".

**Comment by PDostalek** [comment]
Many thanks
