### ISSUE TITLE
 [loc][Query][AzureStorageExplorer] Localizability of 0; "MessageInspectingEntitiesIn"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/AzureStorageExplorer#2084]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Can you help, please?
Thanks!

Source:
Inspecting %1$s entities in '%2$s'

File Name:
loc\en\src\Standalone\resources\Activities.json

Query:
We need more info about the placeholders.
Does "%1$s" stand for quantity of entities?
Thanks.

**Comment by craxal** [comment]
Yes, the first placeholder is a number. For example, "Inspecting 2 entities in 'sometable'".

**Comment by PDostalek** [comment]
Perfect, thanks
