### ISSUE TITLE
The detach dialog layout shows unfriendly with a long display name

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2087]
**Storage Explorer Version:** 1.10.1
**Build:** [20191016.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3146982)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one Non-ADLS Gen2 account -> Blob Containers.
2. Select one blob container -> Using SAS to attach with a long display name.
4. Try to detach the SAS attached blob container.
5. Check the detach dialog layout.

**Expect Experience:**
The detach dialog layout shows well.

**Actual Experience:**
The detach dialog layout shows unfriendly.
![image](https://user-images.githubusercontent.com/54055206/66908374-882f8e00-f03d-11e9-877f-890f90767780.png)

**More Info:**
This issue also reproduces for one SAS attached storage account/ file share/ queue/ table.

**Comment by v-xianya** [comment]
This issue has been fixed on build master/20191128.3. So we close it.
