### ISSUE TITLE
Always keep deleting status in Activities when deleting one ADLS Gen2 blob

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2088]
**Storage Explorer Version:** 1.10.1
**Build:** [20191016.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3146982)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release(1.10.1)

**Steps to reproduce:**

1. Expand one ADLS Gen2 account -> Blob Containers.
2. Create a new blob container -> Upload a blob to it.
3. Delete the blob and check the result.

**Expect Experience:**
The blob is deleted successfully and the log message shows well.

**Actual Experience:**
Always keep deleting status in Activities.
![image](https://user-images.githubusercontent.com/54055206/66906769-cb3c3200-f03a-11e9-9c57-059e7243ed87.png)

**More Info:**
The deleted blob disappears after manually refresh.

**Comment by v-xianya** [comment]
This issue has been fixed on build 20191029.3. So we close it.
