### ISSUE TITLE
 [loc][Query][AzureStorageExplorer] Localizability of 0; "ActiveTransfterAuthMethodSAS"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/AzureStorageExplorer#2089]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Can you help, please?
Thanks!

Source:
using SAS

File Name:
loc\en\src\components\se-az-copy-extension\resources\Copy.json

Query:
Please, explain where will this string appear, the same as the following:
Is lowercase intentional ?

using Azure AD 0; "ActiveTransfterAuthMethodAzureAD"
using name and key 0; "ActiveTransfterAuthMethodNameAndKey"

used Azure AD 0; "FinishedTransferAuthMethodAzureAD"
used name and key 0; "FinishedTransferAuthMethodNameAndKey"
used SAS 0; "FinishedTransferAuthMethodSAS"

**Comment by craxal** [comment]
@PDostalek These strings appears at the end of various activity messages, describing the credentials being used to authenticate requests. Lowercase is intentional. For example:

> Copying 6 blobs from 'container1' to 'container2' (**using SAS**)

**Comment by craxal** [comment]
Closing this now. If you still have questions, you may reopen and comment.
