### ISSUE TITLE
[loc][Query][AzureStorageExplorer] Localizability of 0; "MessageStatisticsEntityCount"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/AzureStorageExplorer#2090]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Can you help, please?
Thanks!

Source:
%1$s entities

File Name:
loc\en\src\Standalone\resources\Activities.json

Query:
Please, define placeholder. Will it be a number?

**Comment by craxal** [comment]
@PDostalek Yes, the placeholder is for a number, as in "6 entities".
