### ISSUE TITLE
A11y_AzureToolsStorageExplorer_CreateNewVirtualDirectory_Keyboard: Keyboard focus goes on non-actionable controls(Texts).

### ISSUE THREAD

**Issue by Suraj1200499** [microsoft/AzureStorageExplorer#2092]
GitHubTags: #A11y_AzureToolsStorageExplorer; #A11yMAS; #A11YTCS; #DesktopApp; #MAS2.1.1; #Keyboard; #Win32; 

**Environment Details:**
Application Name: Azure Tools Storage Explorer
Application Version: 1.10.0
Windows10

**Repro Steps:**
1. Launch Storage Explorer
2. Navigate to "Open Connect dialog" pane and Sign in to Azure.
3. Go to "Manage Accounts" pane and Select the subscriptions you will use. Once selected, click on "Apply" button.
4. Navigate to "Blob Containers" of the selected subscription, right click and hit enter on "Create Blob container" to Create a new Blob container.
5. Navigate to "New Folder" present on toolbar and hit enter.
6. "Create New Virtual Directory" popup gets opened.
7. Start navigating on the screen using Tab key.
8. Verify Keyboard focus goes on non-actionable control.

**Actual:**
Keyboard focus goes on non-actionable controls(Texts) Using Tab key.

**Same issue is observed throughout the application. Keyboard focus goes on non-interactive controls.**

**Expected:**
Keyboard focus should not go on non-actionable controls(Texts) Using Tab key.

**UserImpact:**
Keyboard only users face difficulty to know whether the control is actionable or not if keyboard focus goes on non-actionable controls using Tab key.

**Comment by JasonYeMSFT** [comment]
merged.

**Comment by MRayermannMSFT** [comment]
@Radha2019 @Charanrajkb @nirmalsahoo @Suraj1200499 @vinodbk197

Please verify whether or not this bug was fixed to your satisfaction in the latest release of Storage Explorer. You can obtain that release from https://www.storageexplorer.com

If the bug has not been fixed to your satisfaction, please:
- Explain how did the fix not meet your expectations.
- Tell us exactly how we can meet your expectations. If there is more than one way to do so, feel free to list the different ways.

**Comment by Suraj1200499** [comment]
@MRayermannMSFT Verified this issue in Microsoft Azure Tools Storage Explorer Application Version: 1.12.0, this issue is still reproduced for below Scenarios.
1. Connect to Azure Storage(Attached Video for reference)
2. Add a Resource Via Azure Active Directory
3. Use a Connection string
4. Use a shared access signature
5. Use a storage account name and key
6. Attach a local Accumula
[2092_A11y_AzureToolsStorageExplorer_CreateNewVirtualDirectory_Keyboard_StillReproduced.pptx](https://github.com/microsoft/AzureStorageExplorer/files/4148293/2092_A11y_AzureToolsStorageExplorer_CreateNewVirtualDirectory_Keyboard_StillReproduced.pptx)
tor

**Comment by JasonYeMSFT** [comment]
@Suraj1200499 we have created a branch named accessibility-verification which will contain our accessibility fixes. Please use the builds from that branch to verify the bugs that we mark as needs verification in the Accessibility Compliance project. Let me know if you don't have access to the build artifacts.

**Comment by Suraj1200499** [comment]
@MRayermannMSFT Verified this issue in Private build of Windows.
Application version: 1.12.0.
This issue is no longer reproduced. Hence Closing the bug.

Added Closed Video in [One Drive](https://microsoft-my.sharepoint.com/personal/v-nisaho_microsoft_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fv%2Dnisaho%5Fmicrosoft%5Fcom%2FDocuments%2FStorageExplorer%5FReprovideos&originalPath=aHR0cHM6Ly9taWNyb3NvZnQtbXkuc2hhcmVwb2ludC5jb20vOmY6L3Avdi1uaXNhaG8vRXNTVUtnZm9PSzlIbUVMOFBxcVhkOTRCVXRBVkJ6S0pldHB5SDZwS0FzVXh5dz9ydGltZT1GRkRuQ25QRzEwZw) for reference.

**Comment by fsteffi** [comment]
GithubTags:#Closed;

**Comment by mstechie** [comment]
GitHubTags:#BM-TCS-StorageExplorer-Win32-Sep2019;
