### ISSUE TITLE
A11y_AzureToolsStorageExplorer_ConnecttoAzureStorage_Keyboard: Radio button gets selected automatically when navigate from one radio button to other radio button using Arrow keys.

### ISSUE THREAD

**Issue by Suraj1200499** [microsoft/AzureStorageExplorer#2096]
GitHubTags: #A11y_AzureToolsStorageExplorer; #A11yMAS; #A11YTCS; #DesktopApp; #MAS2.1.1; #Keyboard; #Win32; 

**Environment Details:**
Application Name: Azure Tools Storage Explorer
Application Version: 1.10.0
Windows10

**Repro Steps:**
1. Launch Storage Explorer
2. Navigate to "Open Connect Dialog" pane present on left side of screen and hit enter.
3. "Connect to Azure Storage" popup opens.
4.  Start Navigating on the Screen using Arrow keys.
5. Verify Radio button gets selected automatically when navigate from one radio button to other radio button using Arrow keys.

**Actual:**
While navigating on the radio button using arrow keys, radio buttons gets selected automatically  without performing any action on those radio buttons.

**Same issue is observed throughout the application where ever two or more radio buttons present under a particular section.**

**Expected:**
While navigating on the radio button using arrow keys, Only keyboard focus should move from one radio button to other radio button and radio button should gets selected by hitting Space bar key.

**UserImpact:**
Keyboard only users face difficulty to navigate on the radio buttons if radio buttons are selected automatically without performing any action on those controls.

**Comment by MRayermannMSFT** [comment]
@Suraj1200499 Pretty sure this is by design/this is just how HTML works....

W3.org radio button aria docs has same behavior: https://www.w3.org/TR/2016/WD-wai-aria-practices-1.1-20161214/examples/radio/radio-1/radio-1.html
WebAIM radio button docs has same behavior: https://webaim.org/techniques/forms/controls#radio

To accomplish what you want, we'd have to override the default behavior of radio buttons, which is also another indicator that this is the wrong thing to do.

**Comment by MRayermannMSFT** [comment]
If I don't hear a reply within 3 days, I'll go ahead and close the bug.

**Comment by Suraj1200499** [comment]
@MRayermannMSFT 
The bug is By design, As per our process By design bug will be validated by our SME's. So I had put this bug in their note. Once I get a reply from them, I will update the comment.

**Comment by Suraj1200499** [comment]
Behavior of radio buttons is fine. As this is expected behaviour Closing the bug.

**Comment by fsteffi** [comment]
GithubTags:#Closed;

**Comment by mstechie** [comment]
GitHubTags:#BM-TCS-StorageExplorer-Win32-Sep2019;
