### ISSUE TITLE
'View Release Notes' doesn't work in the popped update notification

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#210]
**Storage Explorer Version**: 1.1.0

**Platform**: Linux/Mac

**Architecture**: x64

**Build Number**: 20180822.4

**Commit**: 6232e7cf

**Regression From**: Previous release

#### Steps to Reproduce: ####

1. Open terminal and navigate to where the Storage Explorer executable is located.
2. Type the command "./StorageExplorer --add-update-group=CTI"
3. Storage Explorer will open then click 'View Release Notes' in the popped update notification.

#### Expected Experience: ####
The release notes for 1.1.0 displays well.

#### Actual Experience: ####
'View Release Notes' doesn't work.

**Comment by MRayermannMSFT** [comment]
Merged into master.
