### ISSUE TITLE
ADLS Gen2 copy, move

### ISSUE THREAD

**Issue by ralphke** [microsoft/AzureStorageExplorer#2103]
AZ Storage Explore Version 1.10.1, AzCopy 10.2.1
There is currently now way to reorganize a once created structure in ADLS Gen2, without writing code.
It would be great to have a copy and a move operation in Azure Storage Explorer to reorganize hierarchical structures inside the ADLS account as well as copy these structures inside the ADLS account, which can keep the security settings in-place.
Using Data Factory for this operation seems to be an overkill and introduces a steep learning curve for getting the job done.

**Comment by JasonYeMSFT** [comment]
We have done some integration work to enable copying data in ADLS Gen2 blob containers via AzCopy. Unfortunately, we don't support preserving ACLs between copies.

**Comment by JasonYeMSFT** [comment]
A move feature has been added for ADLS Gen2 containers and will be included in 1.15.0.
