### ISSUE TITLE
The 'OK' button is not localized when trying to add an exist entity for one table

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2105]
**Storage Explorer Version:** 1.10.1
**Build:** [20191017.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3150956&view=results)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Language:** Chinese (zh-TW) /Chinese (zh-CN)
**Regression From:** Not a regression

**Steps to reproduce:**
1. Open Settings panel -> Regional Settings -> Select Chinese (traditional) as application language -> Restart Storage Explorer.
2. Expand one storage account -> Tables.
3. Create one new table -> Add an entity.
4. Try to add the same entity to the table.

**Expect Experience:**
The 'Ok' button is localized.

**Actual Experience:**
The 'OK' button is not localized.
![image](https://user-images.githubusercontent.com/41351993/66997056-5af9e300-f104-11e9-83d8-ae8384a831d2.png)

**More Info:**
Whether the error code 'EntityAlreadyExists' need to be localized or not.

**Comment by lukaschal** [comment]
@craxal  All "Ok" localizable buttons are translated on our side. These two mentioned below are last ones, translated at 10/11/2019.

File: loc\en\src\components\se-adls2-extension\resources\FileSystemEditor.json
ID: 0; "ButtonOK"
SRC: OK
TGT: 確定

File: loc\en\src\components\se-adls2-extension\resources\ManagePosixAcl.json
ID: 0; "LabelOk"
SRC: Ok
TGT: 確定

**Comment by craxal** [comment]
This is a system dialog, so there's nothing to translate. We have to find where this dialog is opened and swap for our custom message box.

**Comment by jinglouMSFT** [comment]
I think the whole world understands what OK means, so it's fine to leave it as is.  I am closing the bug as won't fix.
