### ISSUE TITLE
Upload failed unexpectedly after 5 attempt

### ISSUE THREAD

**Issue by EssenceIT** [microsoft/AzureStorageExplorer#2106]
Storage Explorer Version: 1.10.1
Build Number: 20190919.2
Platform/OS: Windows 10
Architecture: x64
Regression From: NA

## Bug Description ##
Trying to upload a VHD file through the Storage Explorer but its not working, we are getting the following error log. We are connected to Azure using the connection string method.
{
  "message": "\"Upload failed unexpectedly after 5 attempt\""
}

## Steps to Reproduce ##
Copying a VHD file (100GB) to a blob conteiner.

## Expected Experience ##
We want to be able to copy the VHD file to a blob container so we can build our server.

## Additional Context ##
We also tried to connect through our domain account and upload the file but that feiled as well, we got the following error.

{
  "name": "StorageError",
  "message": "This request is not authorized to perform this operation using this permission.\nRequestId:b4fbf996-b01e-0025-78bd-84119d000000\nTime:2019-10-17T07:33:40.8825690Z",
  "stack": "StorageError: This request is not authorized to perform this operation using this permission.\nRequestId:b4fbf996-b01e-0025-78bd-84119d000000\nTime:2019-10-17T07:33:40.8825690Z\n    at Function.StorageServiceClient._normalizeError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:1205:23)\n    at Object.StorageServiceClient._processResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:751:50)\n    at Request.processResponseCallback [as _callback] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:319:37)\n    at Request.self.callback (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:185:22)\n    at Request.emit (events.js:182:13)\n    at Request.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1157:10)\n    at Request.emit (events.js:182:13)\n    at IncomingMessage.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1079:12)\n    at Object.onceWrapper (events.js:273:13)\n    at IncomingMessage.emit (events.js:187:15)",
  "code": "AuthorizationPermissionMismatch",
  "statusCode": 403,
  "requestId": "b4fbf996-b01e-0025-78bd-84119d000000"
}

Thank you.
Regards,
Igor

**Comment by jinglouMSFT** [comment]
Do you have the write permission?  The error message seemed to suggest you don't have permission to write.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of reply.
