### ISSUE TITLE
There are extra spaces in descriptions on delete blob dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2109]
**Storage Explorer Version:** 1.10.1
**Build:** [20191018.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3156019&view=results)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** Chinese (zh-CN) / Chinese (zh-TW)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open Settings panel -> Application (Regional Settings) -> Select **Chinese (simplified)** as application language -> Restart Storage Explorer.
3. Expand one Non-ADLG Gen2 storage account -> Blob Containers.
4. Create a new blob container -> Upload one blob -> Delete the uploaded blob.
5. Check the prompt delete dialog.

**Expect Experience:**
There are no extra spaces in descriptions on delete blob dialog.

**Actual Experience:**
There are extra spaces in descriptions on delete blob dialog.
![image](https://user-images.githubusercontent.com/41351993/67077522-01f08480-f1c2-11e9-93f0-6b6de535381b.png)

**More Info:**
1. This issue also reproduces in Chinese(zh-TW).
![image](https://user-images.githubusercontent.com/41351993/67077555-146abe00-f1c2-11e9-8e14-4562ca4ab2b5.png)
2. This issue doesn't reproduce for one ADLS Gen2 blob.
![image](https://user-images.githubusercontent.com/41351993/67077660-44b25c80-f1c2-11e9-87b1-c8a4a61dd454.png)

**Comment by lukaschal** [comment]
On review.

File: loc\en\src\components\se-blob-extension\resources\BlobEditor.json
ID: 0; "Dialog.SoftDeleteSingularRetentionWarning"
SRC: Deleted blobs will be retained for %1$s day. Are you sure you want to delete the selected %2$s?
TGT: 已刪除的 Blob 會保留 %1$s 天。確定要刪除選取的 %2$s 嗎?

File: loc\en\src\components\se-blob-extension\resources\BlobEditor.json
ID: 0; "Dialog.SoftDeletePluralRetentionWarning"
SRC: Deleted blobs will be retained for %1$s days. Are you sure you want to delete the selected %2$s?
TGT: 已刪除的 Blob 會保留 %1$s 天。確定要刪除選取的 %2$s 嗎?

**Comment by JasonYeMSFT** [comment]
This seems a translation issue to me. At least for simplified Chinese, unlike English where words are separated by spaces, Chinese characters in a sentence have no space in between. In this situation, I would write the translated string as
"已删除的 blob 将保留%1$s天。确定要删除所选%2$s吗?"
Not sure what is the standard for traditional Chinese but I would guess they also have no spaces between characters.

**Comment by JasonYeMSFT** [comment]
We are going to use separate full strings to distinguish singular and plural form. We are not going to fix this due to our release schedule.

**Comment by lukaschal** [comment]
Fixed on CHS.

**Comment by lukaschal** [comment]
CHT linguistic answer:

It's correct to put half-width space between full-width characters and half-width characters according to the Style Guide and localization convention.

**Comment by lukaschal** [comment]
@v-xianya Is CHS fixed on latest build ?

**Comment by v-xianya** [comment]
@lukaschal Verified on the latest build.
1. This issue has been fixed in **Chinese (simplified).**
2. This issue still reproduces in **Chinese (traditional**).

**Comment by lukaschal** [comment]
Second CHS string fixed.

**Comment by lukaschal** [comment]
@v-xianya Still repro on latest build ?

**Comment by v-xianya** [comment]
@lukaschal  Verified this issue on the latest build 20191128.5.
1. This issue has been fixed in zh-CN.
2. In zh-TW. This issue still **reproduces** in the below situations.
    Regular blob (Soft delete is disabled)
![image](https://user-images.githubusercontent.com/41351993/69849078-9c67cd00-1230-11ea-90f0-f2cf59fcbeec.png)
Regular blob (Soft delete is enabled)
![image](https://user-images.githubusercontent.com/41351993/69849084-a1c51780-1230-11ea-995f-4d4b42e5bb9c.png)

**Comment by lukaschal** [comment]
@v-xianya  CHT linguistic answer:

It's correct to put half-width space between full-width characters and half-width characters according to the Style Guide and localization convention.

**Comment by v-xianya** [comment]
@lukaschal 
In zh-TW.  
For one HNS blob, there no any spaces show in descriptions on delete blob dialog.
So please help to confirm this issue. Thanks.
![image](https://user-images.githubusercontent.com/41351993/69934314-6885e500-1486-11ea-810d-452678d42e80.png)

**Comment by lukaschal** [comment]
On review.

File: loc\en\src\components\se-adls2-extension\resources\FileSystemEditor.json
ID: 0; "WarningDeleteConfirm"
SRC: This action is irreversible. Are you sure you want to delete the selected items?
TGT: 這個動作無法復原。確定要刪除選取的項目嗎?

**Comment by johnliu2016** [comment]
Implemented, removed the surrounding spaces in all occurrences.

**Comment by v-xianya** [comment]
This issue has been fixed in build 20191219.2. So we close it.
