### ISSUE TITLE
An error occurs when restoring file snapshot for one attached account with SAS

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#211]
**Storage Explorer Version**: 1.1.0
**Platform**: Windows/Mac/Linux
**Architecture**: ia32/x64
**Build Number**: 20180522.4
**Commit**: 6232e7cf
**Regression From**: Not a regression

#### Steps to Reproduce: ####

1. Launch Storage Explorer and attach one account with SAS. 
2. Open one file share which contains one file at least under the attached account.
3. Create a snapshot for the file share.
4. Delete one file in current file share.
5. Restore for the deleted file snapshot.

#### Expected Experience: ####
The file snapshot can be restored successfully.

#### Actual Experience: ####
An error occurs.
![error](https://user-images.githubusercontent.com/34729022/40416150-166f7eb0-5e6c-11e8-98af-1385bd83fa48.png)

#### More info: ####
1. This issue doesn't reproduce for one regular account.
2. This issue doesn't reproduce for one attached with External.

**Comment by craxal** [comment]
Yep, found the problem. Restore is implemented by copy, and copy needs a URL to the source file. In this case, the URL needs a SAS token, but the restore operation wasn't including the SAS token when generating the source URL.
