### ISSUE TITLE
The select characters 'And' & 'Or' between clauses are not localized on query editor

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2110]
**Storage Explorer Version:** 1.10.1
**Build:** [20191018.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3156019&view=results)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** Chinese (zh-CN) / Chinese (zh-TW)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open Settings panel -> Application (Regional Settings) -> Select **Chinese (simplified)** as application language -> Restart Storage Explorer.
3. Expand one  storage account -> Tables.
4. Create a new table -> Open Query builder -> Click '+' icon to add two new clauses.
5. Check whether the select characters 'Add' & 'Or' are localized or not.

**Expect Experience:**
The select characters 'And' & 'Or' between clauses are localized.

**Actual Experience:**
The select characters 'And' & 'Or' between clauses are not localized.
![image](https://user-images.githubusercontent.com/41351993/67079079-1bdf9680-f1c5-11e9-8988-a3292b9e98c6.png)

**Comment by lukaschal** [comment]
@craxal Are these strings exposed to localization ?

**Comment by craxal** [comment]
@lukaschal These strings are not exposed. But they are considered logical operators. I don't know what the standard is. Should these be localized?

**Comment by lukaschal** [comment]
@craxal It is difficult to say, it depends on language specifics or developers requirements for different components/products.

**Comment by craxal** [comment]
We'll go ahead and exposed these to localization with some comments.

**Comment by v-xianya** [comment]
Reproduce on build [20200319.10](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3566615).

**Comment by lukaschal** [comment]
@v-xianya Is it possible to provide screenshots ?

**Comment by JasonYeMSFT** [comment]
We haven't published the strings to our build yet.

**Comment by v-xianya** [comment]
@lukaschal 
Verified on build 20200322.2. 
Screenshot in Chinese(zh-CN).
![image](https://user-images.githubusercontent.com/41351993/77289668-5bcb1c80-6d15-11ea-98a5-062f0894edda.png)

Screenshot in English.
![image](https://user-images.githubusercontent.com/41351993/77289944-03484f00-6d16-11ea-8228-50df1031bfc4.png)

**Comment by lukaschal** [comment]
On review.

**Comment by v-xianya** [comment]
@lukaschal 
Verified this issue on build 20200327.2. Details please see the below.

1. **The translation of ‘And’ is inconsistent in Chinese(zh-TW)/ Polish**
In Chinese(zh-TW)
![image](https://user-images.githubusercontent.com/41351993/77717647-009e7000-701c-11ea-9400-b426fa759cea.png)
In Polish
![image](https://user-images.githubusercontent.com/41351993/77717704-19a72100-701c-11ea-9225-a7750e0f595d.png)
2. ‘**Or‘ is not translated in Chinese(zh-CN)/ Portuguese (Portugal)/ Italian**
In Chinese(zh-CN)
![image](https://user-images.githubusercontent.com/41351993/77717800-4c511980-701c-11ea-93e2-95728a5169b4.png)
In Portuguese (Portugal) 
![image](https://user-images.githubusercontent.com/41351993/77717847-67bc2480-701c-11ea-95ef-f70f3b0bc549.png)
In Italian
![image](https://user-images.githubusercontent.com/41351993/77717878-7276b980-701c-11ea-8371-84eef586f3e6.png)
3. **'And/Or' is not translated in Korean**
![image](https://user-images.githubusercontent.com/41351993/77717923-8f12f180-701c-11ea-8719-822f210cd90c.png)

**Comment by lukaschal** [comment]
Localized consistently now.

**Comment by MRayermannMSFT** [comment]
Moving to 1.14 to complete full verification then.

**Comment by v-xianya** [comment]
Verified this issue on build master/20200602.3. 
'And' & 'Or' are not localized in **Italian**. So we re-open it.
![image](https://user-images.githubusercontent.com/41351993/83473793-fb96ea80-a4bc-11ea-82cd-c9359b004c9d.png)

**Comment by lukaschal** [comment]
@v-xianya These translations are correct for ITA.

**Comment by JasonYeMSFT** [comment]
@lukaschal, do you mean that the strings are supposed to be "And" and "Or" in Italian?

**Comment by lukaschal** [comment]
@JasonYeMSFT Yes, these terms should not be localized in Italian in this context.
