### ISSUE TITLE
The renamed blob doesn't auto display when renaming one leased blob

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2111]
**Storage Explorer Version:** 1.10.1
**Build:** [20191018.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3156019)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one non-ADLS Gen2 account -> Blob Containers.
2. Create a new blob container -> Upload one blob to it and acquire lease for the blob.
3. Try to rename the blob.
4. Check whether the renamed blob displays or not.

**Expect Experience:**
The renamed blob auto display.

**Actual Experience:**
The renamed blob doesn't auto display.

**More Info:**

1. The renamed blob displays well after manually refresh. 
2. The renamed blob doesn't auto display whether 'auto-refresh on change' is on.

**Comment by v-xianya** [comment]
This issue has been fixed on build 20191023.8. So we close it.
