### ISSUE TITLE
An extra period shows next to the tooltip of the localized Copy button for one disk

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2112]
**Storage Explorer Version:** 1.10.1
**Build:** [20191018.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3156019)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** Chinese (zh-TW)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open Settings panel -> Application (Regional Settings) -> Select **Chinese (traditional)** as application language -> Restart Storage Explorer.
3. Expand Disks -> Open one resource group.
4. Check the tooltip of the localized 'Copy' on the toolbar.

**Expect Experience:**
No extra period shows next to the tooltip of the locaized Copy button.

**Actual Experience:**
An extra period shows next to the tooltip of the locaized Copy button.
![image](https://user-images.githubusercontent.com/54055206/67081247-5e0ad700-f1c9-11e9-9c57-c6b32a56f99e.png)

**Comment by lukaschal** [comment]
On review.

File: loc\en\src\components\se-managed-disks-extension\resources\ManagedDisksExplorer.json
ID: 0; "MenuCopyDescription"
SRC: Copy the selected disks to the clipboard
TGT: 將選取的磁碟複製到剪貼簿。

**Comment by lukaschal** [comment]
Fixed.

**Comment by lukaschal** [comment]
@v-limu Is this repro on latest build ?

**Comment by v-limu** [comment]
Hi @lukaschal This issue has been fixed on latest build [20191105.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3213388). So we close it.
