### ISSUE TITLE
Azure Storage Explorer Error

### ISSUE THREAD

**Issue by vensyd** [microsoft/AzureStorageExplorer#2113]
After updating Storage Explorer to Sept 2019 (Version 1.10.1) getting below error while trying to access storage containers.

![image](https://user-images.githubusercontent.com/3982803/67175236-977d5580-f408-11e9-9f50-e333ff335319.png)

What am doing wrong?

**Comment by JasonYeMSFT** [comment]
Are you behind a proxy? You might need to re-configure the proxy settings after the upgrade.

**Comment by vensyd** [comment]
> Are you behind a proxy? You might need to re-configure the proxy settings after the upgrade.

Thanks Jason, Yes it was and also have to set to Edit > Target Default Azure APIs.  All working now.
