### ISSUE TITLE
An error occurs when expanding ADLS Gen2 Blob Containers node

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2115]
**Storage Explorer Version:** 1.10.1
**Build:** [20191021.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3162964)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Create an ADLS Gen2 storage account in Portal -> Open this account in Storage Explorer.
2. Expand the new created ADLS Gen2 storage account -> Blob Container.
3. Check the result.

**Expect Experience:**
1. No error occurs.
2. The Blob Containers node can be successfully expanded.

**Actual Experience:**
An error occurs when expanding ADLS Gen2 Blob Containers node.
![image](https://user-images.githubusercontent.com/41351993/67193692-4aa97700-f428-11e9-947f-e22ae1f899fb.png)

**More Info:**
An error notification occurs after trying to create a new ADLS Gen2 blob container
![image](https://user-images.githubusercontent.com/41351993/67194315-71b47880-f429-11e9-90f9-1ce16f2f8091.png)

**Comment by craxal** [comment]
@v-xianya This only reproduces when the storage account does not have any containers. Looks like a bug in the SDK. The `containerItems` property is supposed to be an array, but the SDK returns an empty string when there aren't any containers.

@XiaoningLiu Are you aware of this?

**Comment by XiaoningLiu** [comment]
@harahma Help with a quick fix?

**Comment by craxal** [comment]
@XiaoningLiu No, I have a workaround. I just want to make sure you're aware and can get it fixed.
