### ISSUE TITLE
Cannot browse ADLS Gen 2 with ASE v 1.10.1 with proxy setting

### ISSUE THREAD

**Issue by sarmoho2** [microsoft/AzureStorageExplorer#2117]
**Storage Explorer Version**: 1.10.1
**Build Number**: 20190919.2
**Platform/OS**: Window 10
**Architecture**: ia32
**Regression From**:  1.7.1

## Bug Description ##
Cannot browse ADLS Gen 2 with ASE v 1.10.1 with proxy setting.  I found in releases note that connect to ADLS Gen2 behind proxy may fail.  Do you have workaround on this?

Error show:

Unable to retrieve child resources.

Details:
request to https://xxxx.dfs.core.windows.net/?resource=account&timeout=60 failed, reason: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND

**Comment by JasonYeMSFT** [comment]
Due to some technical limitation, ADLS Gen 2 service can only grasp the proxy setting when Storage Explorer launches. If you haven't tried this, please try configuring your proxy setting and then restart Storage Explorer.

**Comment by sarmoho** [comment]
I have restarted several times. But ADLS Gen2 still does not use proxy setting and try to connect to Microsoft server directly based on information we got from our IT security team. The problem show when we expand list of file system under ADLS Gen2 Storage Account under log in user via AAD.

**Comment by sarmoho** [comment]
I found workaround by select "Target Azure Stack APIs" under "Edit" menu. It will fix the list file system problem but you will not use some feature like "Manage Access". Is this can prove that some ADLS Gen 2 service not used the proxy setting?

**Comment by MRayermannMSFT** [comment]
@sarmoho , do you know what type of proxy you are behind? We are having trouble repro'ing this.

**Comment by sarmoho** [comment]
I am not sure about type of proxy server. But currently, I have to use a username and password to do authenticate to proxy server.

Another thing I found that, if I did not put setting for proxy server in IE -> Internet Option -> Lan Setting but set proxy server/ username / password in Azure Storage Exploerer, Azure Storage Explorer will not be able to explore ADLS gen 2 and also cannot log in to AAD.

Forgot to tell you that I connect to Storage using company AAD log in account

**Comment by sarmoho** [comment]
I can help you to debug the problem if you provide me the step to debug.

**Comment by MRayermannMSFT** [comment]
Can you ask your network admin what type of proxy you are behind? Depending on the type of the proxy, we may not support it at this time. We only support basic proxy authentication. We don't support anything more complex than that, such as NTLM.

**Comment by sarmoho** [comment]
This is the message I got from my company network team.

Our proxy infrastructure for the user’s workstation is setup to be explicit proxy (Web proxy servers)

At the Client side we force the PAC file configuration to allow client decide which proxy they have to use. Depend on Network Placement / destination domain.

The proxy primary authentication mode is Kerberos.  Can be fall back to NTLM if the Kerberos authentication are fail.

**Comment by MRayermannMSFT** [comment]
@sarmoho , can you confirm for me if you able to browse and interact with other types of Storage, such as file shares, queues, or tables?

**Comment by MRayermannMSFT** [comment]
Hi @sarmoho , would you be open to doing a customer call with us? Our SDK team would like to do some debugging locally on your machine. If yes, do you have a screen sharing software you are comfortable with? Thanks!

**Comment by sarmoho** [comment]
Hi Microsoft Team,

Sorry for the late reply. I waited for my company to approve to install v 1.11.1 and hoped it would fix this issue. Unfortunately, after we updated to 1.11.1 we still have the same issue. About file shares, queue, table, normally we don't use it but look like it works fine. I confirm that we have only a problem with file system.

Our company uses Microsoft Team for communication and our Timezone is GMT+7(Bangkok). Are you still comfortable with this timezone? We also opened the support ticket SR#119102123000817  since October in case you need more information about this issue.

Thank you.

**Comment by MRayermannMSFT** [comment]
@sarmoho no worries about the delay! Are you able to do Jan 9, 5:00 PM, PST? For you that would be Jan 10, 8:00 AM, GMT+7.

**Comment by sarmoho** [comment]
I am ok with that time. Could you please send me your email so I can add your contact to Microsoft Team?

Thank you.

**Comment by MRayermannMSFT** [comment]
Please email sehelp@microsoft.com. I'd rather not have either of us have to give out a direct email address.

**Comment by sarmoho** [comment]
Just send an email to the mail you gave.

**Comment by sarmoho** [comment]
Tested and fixed in version 1.12.0. The root cause is Username and Password in Proxy Setting dialog had not been used.

**Comment by MRayermannMSFT** [comment]
Thanks again @sarmoho! Closing.
