### ISSUE TITLE
The URL format is incorrect for one ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2118]
**Storage Explorer Version:** 1.10.1
**Build:** [20191021.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3162964)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release (1.10.1)

**Steps to reproduce:**
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a new blob container -> Refresh the Blob Containers node.
3. Check the new blob contianer URL on Properties panel.

**Expect Experience:**

The URL format is correct.
![image](https://user-images.githubusercontent.com/41351993/67272397-0a60fc00-f4ef-11e9-8beb-82368b47e9b5.png)

**Actual Experience:**
1. The URL format is incorrect.
2. An extra '/' shows in URL.
![image](https://user-images.githubusercontent.com/41351993/67272388-046b1b00-f4ef-11e9-8e0d-76f048e8ba35.png)

**Comment by v-xianya** [comment]
Hi @craxal This error doesn't reproduce on the build [20191023.8](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3171474&view=results).

There is another error for ADLS Gen2 blob container URL. Please see bug [2123](https://github.com/microsoft/AzureStorageExplorer/issues/2123).

**Comment by craxal** [comment]
If this doesn't reproduce, then we'll close this bug.
