### ISSUE TITLE
An error occurs when opening one ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2119]
**Storage Explorer Version:** 1.10.1
**Build:** [20191021.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3162964)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release (1.10.1)

**Steps to reproduce:**
1. Create an ADLS Gen2 storage account in Portal -> Add one blob container in Portal.
2. Launch Storage Explorer -> Expand the new created ADLS Gen2 storage account -> Blob Containers.
3. Select one blob container and open it.

**Expect Experience:**
1. No error occurs.
2. The blob container can be opened.

**Actual Experience:**
An error '_The specified resource does not exist_' occurs.
![image](https://user-images.githubusercontent.com/41351993/67269888-1f875c00-f4ea-11e9-9b22-958a60fe7df2.png)

**Additional Context:**
Opening a blob container under one Name & Key attached ADLS Gen2 account. Show the below error.

AuthenticationFailedServer failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:23e87597-001e-0073-0871-89ebd2000000 Time:2019-10-23T07:13:13.3019796ZThe MAC signature found in the HTTP request 'UGHkCS8LebTBEEXK1UJ3kiZWI+Gz0KI37ql1jWRMZMw=' is not the same as any computed signature. Server used following string to sign: 'GET x-ms-client-request-id:7ddf50e7-0568-470d-b858-6e1870a41f32 x-ms-date:Wed, 23 Oct 2019 07:13:13 GMT x-ms-version:2019-02-02 /abctester/test3 comp:list delimiter:/ include:metadata maxresults:1000 prefix: restype:container'.

**Comment by craxal** [comment]
@v-xianya Azure resources may take some time to be established. Please try opening the container again. Does the error still reproduce? Can you copy the entire error message into the issue here?

**Comment by v-xianya** [comment]
Hi @craxal Verified this issue on the latest build 20191023.8. Still show the same error.

**Error Message:**
<?xml version="1.0" encoding="utf-8"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist. RequestId:8b4f95f3-201e-00a3-5a64-895770000000 Time:2019-10-23T05:40:15.0871838Z</Message></Error>

**Comment by v-xianya** [comment]
**More Info:**
Opening a blob container under one Name & Key attached ADLS Gen2 account. Show the below error.

<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:23e87597-001e-0073-0871-89ebd2000000 Time:2019-10-23T07:13:13.3019796Z</Message><AuthenticationErrorDetail>The MAC signature found in the HTTP request 'UGHkCS8LebTBEEXK1UJ3kiZWI+Gz0KI37ql1jWRMZMw=' is not the same as any computed signature. Server used following string to sign: 'GET x-ms-client-request-id:7ddf50e7-0568-470d-b858-6e1870a41f32 x-ms-date:Wed, 23 Oct 2019 07:13:13 GMT x-ms-version:2019-02-02 /abctester/test3 comp:list delimiter:/ include:metadata maxresults:1000 prefix: restype:container'.</AuthenticationErrorDetail></Error>

**Comment by craxal** [comment]
@v-xianya So does this only occur for an attached account?
