### ISSUE TITLE
'Open in Explorer' doesn't auto navigate to the account in Storage Explorer with Chrome/Firefox when Storage Explorer is opened

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#212]
**Storage Explorer Version**: 1.1.0

**Platform**: Mac

**Architecture**: x64

**Build Number**: 20180523.1

**Commit**: 6232e7cf

**Regression From**: Not a regression
#### Steps to Reproduce: ####

1. Launch Storage Explorer and sign in with one subscription(Keep Storage Explorer is opened).
2. Open Azure Portal using Chrome/Firefox and go to the subscription you selected in step1.
3. Choose one storage account then click 'Open in Explorer'.
4. Check whether the selected account is auto navigated or not in Storage Explorer.

#### Expected Experience: ####
The selected account is navigated in Storage Explorer.

#### Actual Experience: ####
The selected account is navigated in Storage Explorer.

#### More info: ####
This issue doesn't reproduce when Storage Explorer isn't opened.

**Comment by craxal** [comment]
Possibly related to #204.

**Comment by MRayermannMSFT** [comment]
Look at this again. Check all browser compatibility. If there is a non-browser related bug (aka bug in deep link logic) open a new issue for that. Also, let's document deeplink support in our troubleshooting guide so we can quickly know what is supported. Also, please test on latest browser versions.

**Comment by MRayermannMSFT** [comment]
All browser seem to support deep link. Will update troubleshooting guide.
