### ISSUE TITLE
The property value of one ADLS Gen2 blob container URL is empty

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2123]
**Storage Explorer Version:** 1.10.1
**Build:** [20191023.8](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3171474&view=results)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release (1.10.1)

**Steps to reproduce:**
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a new blob container -> Refresh the Blob Containers node.
3. Check the new blob contianer URL on Properties panel.

**Expect Experience:**
Display a correct URL.
![image](https://user-images.githubusercontent.com/41351993/67376345-8ffbaf00-f5b6-11e9-9cf0-5c6b5ead771b.png)

**Actual Experience:**
The property value of URL is empty.
![image](https://user-images.githubusercontent.com/41351993/67376435-b4578b80-f5b6-11e9-9ece-8edaaab27329.png)

**Comment by craxal** [comment]
The code is checked in, but looks like the most recent package version was based on an out-of-date branch (didn't rebase). Working on a new package version.
