### ISSUE TITLE
Trying to add azure account to the explorer and the window closes when doing SSO login to organization

### ISSUE THREAD

**Issue by rampanw** [microsoft/AzureStorageExplorer#2126]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**:

**Comment by jinglouMSFT** [comment]
Which version of Storage Explorer are you using?  Are you on Windows, Mac or Linux?  Are you behind a proxy?

**Comment by rampanw** [comment]
Version 1.7.0 and windows. I’m accessing behind a IT firewall.

On Wed, Oct 23, 2019 at 5:25 PM jinglouMSFT <notifications@github.com>
wrote:

> Which version of Storage Explorer are you using? Are you on Windows, Mac
> or Linux? Are you behind a proxy?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_microsoft_AzureStorageExplorer_issues_2126-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DANSOAHWT6KD4MHNJVLKMPRLQQDTRDA5CNFSM4JEM53CKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECDJDQQ-23issuecomment-2D545690050&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=xcDajyZ6Q9E0V7sZZBo1DBRettaDn_0RmjkA_sAP5wo&m=umG1B4oManj-qIdNPBiJYTvoTijVXdm6mmlj1B78qJk&s=oBbGIEqffzfZM8uNKyv_SWlbMJREqV_fe0GlH9Nr7cg&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ANSOAHQCVQSP7Z62UPLTCHLQQDTRDANCNFSM4JEM53CA&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=xcDajyZ6Q9E0V7sZZBo1DBRettaDn_0RmjkA_sAP5wo&m=umG1B4oManj-qIdNPBiJYTvoTijVXdm6mmlj1B78qJk&s=9pVh09GBtfYwU6fCWOFkjL-wGDPELhE0MReEo_sv_TM&e=>
> .
>
-- 

Ram Ramachandran |  ETAC Replication

Palo Alto Networks |  3000 Tannery Way |  Santa Clara, CA 95054 |  USA

Mobile: 209-637-6979 |  www.paloaltonetworks.com

<https://www.paloaltonetworks.com/>
<https://www.facebook.com/PaloAltoNetworks>
<https://www.linkedin.com/company/palo-alto-networks>
<https://twitter.com/paloaltontwks>



The content of this message is the proprietary and confidential property of
Palo Alto Networks, and should be treated as such. If you are not the
intended recipient and have received this message in error, please delete
this message from your computer system and notify me immediately by reply
e-mail. Any unauthorized use or distribution of the content of this message
is prohibited

**Comment by jinglouMSFT** [comment]
The latest release is version 1.10.1 which was released in mid Sept.  I would recommend you upgrade to 1.10.1 first then go from there.  If you are running behind a proxy, you need to first configure the proxy for Storage Explorer.  You can do so after launching Storage Explorer by going to the Setting page, the gear icon on the left pane. Proxy setting is under Application.  Depending on whether you use credentials or not, you may need to also launch the Configure Proxy dialog.

**Comment by rampanw** [comment]
Do you have any documentation of how add proxy?

On Wed, Oct 23, 2019 at 5:34 PM jinglouMSFT <notifications@github.com>
wrote:

> The latest release is version 1.10.1 which was released in mid Sept. I
> would recommend you upgrade to 1.10.1 first then go from there. If you are
> running behind a proxy, you need to first configure the proxy for Storage
> Explorer. You can do so after launching Storage Explorer by going to the
> Setting page, the gear icon on the left pane. Proxy setting is under
> Application. Depending on whether you use credentials or not, you may need
> to also launch the Configure Proxy dialog.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_microsoft_AzureStorageExplorer_issues_2126-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DANSOAHTBG4DA2SZ23ZJ5PHTQQDUR3A5CNFSM4JEM53CKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECDJQCY-23issuecomment-2D545691659&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=xcDajyZ6Q9E0V7sZZBo1DBRettaDn_0RmjkA_sAP5wo&m=NjVuxHo9a_Rdslm8kKS1bzCEP9YArzqt6pfolBHHZI4&s=ooIGLTKzVUyJKUi50m1TB3W_zzzs28sLu-Qfcz-WQuA&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ANSOAHSHKLHSDSBVXJSOY6TQQDUR3ANCNFSM4JEM53CA&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=xcDajyZ6Q9E0V7sZZBo1DBRettaDn_0RmjkA_sAP5wo&m=NjVuxHo9a_Rdslm8kKS1bzCEP9YArzqt6pfolBHHZI4&s=VmuCSdA2si0O2CrQuw0WpZz8ymHo1gb27NW9n97UYbk&e=>
> .
>
-- 

Ram Ramachandran |  ETAC Replication

Palo Alto Networks |  3000 Tannery Way |  Santa Clara, CA 95054 |  USA

Mobile: 209-637-6979 |  www.paloaltonetworks.com

<https://www.paloaltonetworks.com/>
<https://www.facebook.com/PaloAltoNetworks>
<https://www.linkedin.com/company/palo-alto-networks>
<https://twitter.com/paloaltontwks>



The content of this message is the proprietary and confidential property of
Palo Alto Networks, and should be treated as such. If you are not the
intended recipient and have received this message in error, please delete
this message from your computer system and notify me immediately by reply
e-mail. Any unauthorized use or distribution of the content of this message
is prohibited

**Comment by jinglouMSFT** [comment]
Here is a section in the Storage Explorer Troubleshooting Guide - https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C1904#proxy-issues
If you don't know all the info needed to config the proxy, you will need to ask your network admin to get the info.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
