### ISSUE TITLE
Show tenant name along with/in place of subscription ID

### ISSUE THREAD

**Issue by LarsKemmann** [microsoft/AzureStorageExplorer#2127]
As a consultant, I work with a _lot_ of Azure subscriptions. It becomes very difficult to separate the different subscription names and find the ones I'm actively working with. It would be very helpful if the Manage Accounts view would show the Azure AD tenant names (e.g. "Contoso Ltd.") along with the subscription names and subscription IDs.

**Comment by craxal** [comment]
Duplicate of #1326.
