### ISSUE TITLE
Storage Explorer was unable to revoke access to a disk when copying data disk over 256GB

### ISSUE THREAD

**Issue by theweazel** [microsoft/AzureStorageExplorer#2128]
**Storage Explorer Version**: 1.10.1
**Build Number**: 20190919.2
**Platform/OS**: Windows 10
**Architecture**: x64

## Bug Description ##
Storage Explorer was unable to revoke access to a disk.
The disks involved in this operation may still be in an 'Active SAS' state. You may need to return the disks to an 'Unattached' state before retrying this operation, or before performing new operations on the disks.
Service response: {
  "name": "Error",
  "message": "The access token expiry UTC time '10/23/2019 4:10:06 PM' is earlier than current UTC time '10/23/2019 5:39:36 PM'.",
  "stack": "Error: The access token expiry UTC time '10/23/2019 4:10:06 PM' is earlier than current UTC time '10/23/2019 5:39:36 PM'.\n    at new RestError (C:\\Program Files (x86)\\Microsoft Azure Storage 

## Steps to Reproduce ##
1.) Connect 2 Azure accounts
2.) Open "Disks" from the expanded tree of one Subscription
3.) highlight a disk and copy
4.) Navigate to the subscription you wish to copy the disk to and expand tree to "Disk"
5.) Click Paste and wait for the operation to complete

## Expected Experience ##
If I copy and OS disk or data disk below 256GB they copy 100% fine and I can build a VM from them or attached the data disk.

Anything above 256GB I get the error, I have tried to increase the SAS token but still no luck

I am wondering if this is a limitation of Storage explorer or If anyone has any other experiences?

**Comment by theweazel** [comment]
this fix worked for me :)

https://github.com/microsoft/AzureStorageExplorer/issues/2048

**Comment by MRayermannMSFT** [comment]
![so glad it worked for you!](https://media.giphy.com/media/BlVnrxJgTGsUw/source.gif)
Super happy it worked for you! We'll be shipping it in our next release, which is soon-ish. 😄
