### ISSUE TITLE
Properties dialog title is missing for ADLS Gen2 blob containers

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2129]
**Storage Explorer Version:** 1.10.1
**Build:** [20191024.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3176191)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release (1.10.1)

**Steps to reproduce:**
1. Expand an ADLS Gen2 storage account -> Blob Containers.
2. Right click one blob container  -> Click 'Properties...' on the context menu.
3. Check the Properties dialog.

**Expect Experience:**
The Properties dialog is normal.
![image](https://user-images.githubusercontent.com/41351993/67468599-5f327d00-f67d-11e9-94fe-3e42c2818738.png)

**Actual Experience:**
The Properties dialog is odd.
![image](https://user-images.githubusercontent.com/41351993/67468594-5cd02300-f67d-11e9-9ee1-609f64d81429.png)

**Comment by JasonYeMSFT** [comment]
need package update.

**Comment by v-xianya** [comment]
Hi @JasonYeMSFT 
In today's build, we noticed the Properties dialog title shows like:
![image](https://user-images.githubusercontent.com/41351993/67655661-62cf4800-f98c-11e9-9f24-ed1b1a2bbb2d.png)
In previous release, the Properties dailog title shows like:
![image](https://user-images.githubusercontent.com/41351993/67655765-af1a8800-f98c-11e9-9d3f-ec66813da62d.png)


**Is this by design?**

**Comment by JasonYeMSFT** [comment]
Yes. We don't wanna add a duplicate sub-title in this dialog.

**Comment by v-xianya** [comment]
@JasonYeMSFT Got it, Thanks for your quick response !
Since this issue has been fixed. We close it.
