### ISSUE TITLE
An error occurs when creating a blob container under one attached ADLS Gen2 account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2130]
**Storage Explorer Version:** 1.10.1
**Build:** [20191024.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3176191)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release (1.10.1)

**Steps to reproduce:**
1. Attach one ADLS Gen2 storage account via Name & Key.
2. Expand the attached ADLS Gen2 storage account -> Create a new blob container.
3. Check the result.

**Expect Experience:**
1. No error occurs 
2. The blob container can be created and opened successfully.

**Actual Experience:**
1. An error **Cannot read property 'slice' of undefined** occurs.
![image](https://user-images.githubusercontent.com/41351993/67469334-9bb2a880-f67e-11e9-825f-e9c2b1a24a00.png)
2. The new created blob container displays on the tree view.

**Comment by craxal** [comment]
Reproduced. Not blocking. Still investigating where the bug occurs.

**Comment by craxal** [comment]
Looks like the error is due to the `_addChildAndOpen` not receiving a blob connection object, which the explorer context is expecting. So when the extension goes to form the URI for a list blobs request, it's calling `slice` on an undefined property.
