### ISSUE TITLE
Pop up an error dialog when managing access policies for one Azure AD attached ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2131]
**Storage Explorer Version:** 1.10.1
**Build:** [20191024.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3176191)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Give RBAC access to an ADLS Gen2 blob container to a user like 'Blob Data Owner Role'.
2. Attach this ADLS Gen2 blob container via Azure Active Directory (Azure AD).
3. Manage access policies for the Azure AD attached blob container.
4. Check the result.

**Expect Experience:**
No error occurs.

**Actual Experience:**
Pop up an error dialog.
![image](https://user-images.githubusercontent.com/41351993/67471547-2943c780-f682-11e9-8a61-f06b405983b4.png)

**Comment by craxal** [comment]
Won't fix. Managing shared access policies (SAP) is only possible if you have an account key. Since we're attached via RBAC, that's not possible. The menu item has been removed for attached containers.
