### ISSUE TITLE
An error occurs when opening one Azure AD attached container which contains one blob at least

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2133]
**Storage Explorer Version:** 1.10.1
**Build:** [20191024.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3176191)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release

**Steps to reproduce:**
 1. Select one ADLS Gen2 blob container which contains one blob at least.
 2. Give RBAC access to the ADLS Gen2 blob container to a user like 'Blob Data Owner Role'.
 3. Attach this ADLS Gen2 blob container via Azure Active Directory (Azure AD).
 4. Check the result.

**Expect Experience:**
The ADLS Gen2 blob container can be attached and auto opened successfully.

**Actual Experience:**
1. An error **Cannot read property 'credentials' of undefined** occurs.
![image](https://user-images.githubusercontent.com/41351993/67474673-6f4f5a00-f687-11e9-8da2-cc2447b32ee2.png)
2. The editor shows like below.
![image](https://user-images.githubusercontent.com/41351993/67474485-213a5680-f687-11e9-9744-b7b9184ec0c7.png)

**More Info:**
1. Everything works well after **reopen** this attached blob container.
2. This issue doesn't reproduce when attaching one ADLS Gen2 blob container **which doesn't contain blobs**.

**Comment by craxal** [comment]
@v-xianya What is the URL you used? We've recently added code that requires you enter a default DFS endpoint for ADLS Gen2 reources.

**Comment by craxal** [comment]
Error is due to confusion of connection objects when opening the editor. DFS connection is passed as a blob connection.

**Comment by v-xianya** [comment]
Hi @craxal 
We used ADLS Gen2 blob URL when we met this issue.

On today's build 20191029.3. We met the below issues when attaching ADLS Gen2 blob container via Azure AD. Could your help to take a look?

1. When using the Container URL. Show error '**Invalid URL. A default DFS endpoint is required.**'
![image](https://user-images.githubusercontent.com/41351993/67734233-71286d00-fa3b-11e9-8140-d229930be1f0.png)

2. When using DFS Endpoint. Show error '**Unable to determine the container name from the given URL**'
![image](https://user-images.githubusercontent.com/41351993/67733706-15111900-fa3a-11e9-9f6a-00a757c4b425.png)

3. When pasting DFS Endpoint then typing the corresponding container name append to the DFS Endpoint. There **is no error occurs and we can successfully attached**. (The default connection display name is 'b')
![image](https://user-images.githubusercontent.com/41351993/67734676-a1244000-fa3c-11e9-8c82-316bfa91322b.png)
