### ISSUE TITLE
Show ellipsis next to 'New Folder' & 'Folder Statistics' for one ADLS Gen1 account

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2135]
**Storage Explorer Version:** 1.10.1
**Build:** [20191024.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3176191)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release(1.10.1)

**Steps to reproduce:**

1. Expand Data Lake Storage Gen1(Preview).
2. Open one ADLS Gen1 account -> Check the 'New Folder' & 'Folder Statistics' button on editor.

**Expect Experience:**
No ellipsis shows next to 'New Folder' & 'Folder Statistics'.
![image](https://user-images.githubusercontent.com/54055206/67473599-8db45600-f685-11e9-8dd9-09b2b3be3f74.png)

**Actual Experience:**
Show ellipsis next to 'New Folder' & 'Folder Statistics'.
![image](https://user-images.githubusercontent.com/54055206/67473588-87be7500-f685-11e9-9180-dae24c405952.png)

**Comment by v-limu** [comment]
This issue still reproduces on build [20191026.10 ](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3185098). So we reopen it.

**Comment by craxal** [comment]
Cloud Explorer submodule reference needs to be updated.

**Comment by v-xianya** [comment]
This issue has been fixed on build 20191029.3. So we close it.
