### ISSUE TITLE
The public access level of original blob container doesn't update after changing it from Quick Access

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#214]
**Storage Explorer Version**: 1.1.0

**Platform**: Windows/Mac/Linux

**Architecture**: ia32/x64

**Build Number**: 20180522.4

**Commit**: 6232e7cf

**Regression From**: Not a regression

#### Steps to Reproduce: ####

1. Launch Storage Explorer and Expand Storage Accounts.
2. Add one blob container to Quick Access.
3. Change the public access level to others for the container which is added to Quick Access.
4. Check the public access level for the original blob container.

#### Expected Experience: ####
The public access level  of the original container is updated.

#### Actual Experience: ####
The public access level of the original container isn't updated.

#### More info: ####
This issue doesn't reproduce for action 'Manage Access Policies' with the similar repro steps.

**Comment by MRayermannMSFT** [comment]
Todo: make sure the info updates after refreshing. If so, then close, if not, move to 1.3.0

**Comment by MRayermannMSFT** [comment]
The public access level properly updates when you refresh the node. Closing as won't fix.
