### ISSUE TITLE
No error occurs when setting the Buffer size to a negative

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2140]
**Storage Explorer Version:** 1.10.1
**Build:** [20191024.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3176191)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' ->  Transfers -> Buffer size.
3. Type a negative to the Buffer size box ->  Check the result.

**Expect Experience:**
An error occurs and not allow to type a negative.

**Actual Experience:**
No error occurs.
![image](https://user-images.githubusercontent.com/41351993/67558651-f6650680-f749-11e9-9a6c-6f8b80ea606e.png)

**More Info:**
This issue also reproduces for SAS Duration.
![image](https://user-images.githubusercontent.com/41351993/67558694-0a106d00-f74a-11e9-9777-d0c87d334932.png)

**Comment by jinglouMSFT** [comment]
There is no validation built in for these controls yet.  We'll add validation later if needed.  We wanted to enable these for users who really need to configure the settings for AzCopy to unblocked them from doing so.  For most of the users, there will be no need to customize these parameters.
