### ISSUE TITLE
Parts of UI are localized before restarting Storage Explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2141]
**Storage Explorer Version:** 1.10.1
**Build:** [20191024.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3176191)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** All
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Use system language' -> Restart Storage Explorer.
3. Navigate to Settings panel and select one language. Like 'Chinese (simplified)'.
4. Open one blob container and check its editor.

**Expect Experience:**
Show the system language.

**Actual Experience:**
Show Chinese (simplified).
![image](https://user-images.githubusercontent.com/41351993/67559808-3d53fb80-f74c-11e9-923e-8a584f415804.png)

**More Info:**
1. This issue also reproduces for '**Delete & Get Shared Access Signature & Manage Access Policies & Acquire Lease & Break Lease**' dialogs.
2. This issue also reproduces for all languages.

**Comment by MRayermannMSFT** [comment]
Won't fix. This is how our resource loading system works. A full restart is required to localize all of the UI.
