### ISSUE TITLE
App loads, but Explorer stuck "loading"  (macOS)

### ISSUE THREAD

**Issue by andrewconnell** [microsoft/AzureStorageExplorer#2143]
**Storage Explorer Version**: 1.10.1
**Build Number**: 20190919.2 
**Platform/OS**: macOS Catalina (10.15)
**Architecture**: x64
**Regression From**:  n/a

## Bug Description ##
The same version (1.10.1) was working just a few days ago, but suddenly it's no longer loading. It just sits stuck on "loading". I have logged in before and could see resources in multiple subscriptions. The account is global admin on all of the subscriptions and I can see all the resources and their contents within the Azure web portal.

![image](https://user-images.githubusercontent.com/2068657/67566999-128b8800-f6f7-11e9-925a-4e9f33d189c4.png)

I also tried resetting and reauthenticating using the CONNECT menu item guessing an access token was corrupted somehow, but after the auth process (which succeeded), I still am stuck with the same experience above.

## Steps to Reproduce ##
1. Launch the app
1. Observe "loading" never ends...

## Expected Experience ##
1. Explorer window loads assets

## Additional Context ##
- I'm NOT behind proxy
- I've tried deleting & downloading a fresh copy (no change)
- I've reset the app including authentication

**Comment by andrewconnell** [comment]
After a few hours, it started working... no clue what's up.

**Comment by jinglouMSFT** [comment]
After the loading screen, Storage Explorer tries to get the authentication by going through your network authentication.  It's likely your network had some issues.
