### ISSUE TITLE
The property value of ContentMD5 displays messy code for one ADLS Gen2 blob

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2153]
**Storage Explorer Version:** 1.10.1
**Build:** [20191026.10](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3185098)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release (1.10.1)

**Steps to reproduce:**
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Select one blob container -> Upload one blob.
3. Right click the blob and Select 'Properties...'.
4. Check the ContentMD5 value on Properties dialog.

**Expect Experience:**
The property value of ContentMD5 displays well.

**Actual Experience:**
The property value of ContentMD5 displays messy code.
![image](https://user-images.githubusercontent.com/41351993/67665945-b0a47a00-f9a5-11e9-9754-4f0aba0bb03f.png)

**More Info:**
1. This issue doesn't reproduce for one Non-ADLS Gen2 blob.
2. In previous release, there no property ContentMD5 shows for one ADLS Gen2 blob.

**Comment by craxal** [comment]
@v-xianya Do you know what the MD5 should look like? The MD5 is provided by the v12 SDK as a `Uint8Array`, which needs to be fed into a `Buffer` before it can be interpreted. Currently we're decoding using UTF 8, but we may need to do some investigation as to the proper interpretation.

**Comment by v-xianya** [comment]
Hi @craxal 

We noticed that for one non-ADLS Gen2 blob. The ContentMD5 shows like the below:
![image](https://user-images.githubusercontent.com/41351993/67742828-ff125100-fa57-11e9-8c3e-aa3988f3000f.png)

**Comment by craxal** [comment]
@v-xianya Do we have an ADLS Gen2 blob with MD5 in any shared accounts? I don't seem to have any blobs I can test a fix on.
