### ISSUE TITLE
An error occurs after pasting one ADLS Gen2 blob container URL to 'Attach with Azure AD' dialog

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2154]
**Storage Explorer Version:** 1.10.1
**Build:** [20191026.10](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3185098)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release (1.10.1)

**Steps to reproduce:**

1. Select one ADLS Gen2 blob container then copy its URL.
2. Open connect dialog -> Select 'Add a resource via Azure Active Directory (Azure AD)'.
3. Select **Resource type** as 'Blob Container(ADLS Gen2)' -> Paste the URL to **Container or path URL** box on 'Attach with Azure AD' dialog.
4. Check the result.

**Expect Experience:**
No error occurs.
![image](https://user-images.githubusercontent.com/54055206/67668065-2dd1ee00-f9aa-11e9-8d54-c02fa18af5d4.png)

**Actual Experience:**
An error occurs.
![image](https://user-images.githubusercontent.com/54055206/67668366-c7010480-f9aa-11e9-88a5-14cb4cfc2951.png)

**Comment by craxal** [comment]
By design. You must enter a DFS endpoint, such as abctestergen.dfs.core.windows.net. A blob endpoint is not valid.

**Comment by v-xianya** [comment]
Hi @craxal 
There is an error 'Unable to determine the container name from the given URL' occurs when we paste a DFS endpoint. Could you help to take a look?
![image](https://user-images.githubusercontent.com/41351993/67735504-4b04cc00-fa3f-11e9-8dca-258770cb90be.png)

**Comment by craxal** [comment]
@v-xianya The error message says it doesn't see the container name in the URL. You're connecting to a container, right? So you need to provide the container name in the URL path.
