### ISSUE TITLE
No error occurs after setting Properties for one leased ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2157]
**Storage Explorer Version:** 1.10.1
**Build:** [20191029.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3190347)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one ADLS Gen2 storage account.
2. Create a new blob container -> Acquire Leased for the blob container.
3. Right click it -> Select 'Properties' -> Click **Add Properties** and save it.
4. Check the result.

**Expect Experience:**
An error occurs.

**Actual Experience:**
No error occurs.

**More Info:**
1. Fail to add Properties for one leased blob.
2. Show error 'There is currently a lease on the blob and no lease ID was specified in the request' in Details.
![image](https://user-images.githubusercontent.com/54055206/67758439-a3a48b00-fa78-11e9-8077-d48fce877902.png)

**Comment by craxal** [comment]
Sorry, I was confused by the More Info section. You're referring to _containers_.

This is by design. A lease on a container is only applicable to the delete operation. According to the documentation:

> A lease on a container provides exclusive delete access to the container. A container lease only controls the ability to delete the container using the Delete Container operation.
>
> https://docs.microsoft.com/en-us/rest/api/storageservices/lease-container#remarks
