### ISSUE TITLE
failed to upload folder

### ISSUE THREAD

**Issue by briglx** [Microsoft/AzureStorageExplorer#216]
**Storage Explorer Version**: 1.1.0

**Platform**: Windows

**Architecture**: ia32

**Build Number**: 20180507.1

**Commit**: bcc8990d

**Regression From**: Yes before 1.1.0

#### Steps to Reproduce: ####

1. Select folder to upload
2. Fill in folder for destination (Optional). I filled it in

#### Expected Experience: ####
Expected folder to be uploaded

#### Actual Experience: ####
Received the message Unable to access the file

{
  "errno": -4071,
  "code": "EINVAL",
  "syscall": "stat",
  "path": "C:\\Users\\brlamore\\OneDrive - Microsoft\\src\\LearnNeuralNetworks\\vottexport\\20180326_071833_NF_output"
}

**Comment by craxal** [comment]
Are you trying to upload from a OneDrive directory? Unfortunately, we don't support that. OneDrive does something funky that blocks ordinary NodeJS calls.

You said this was working before 1.1.0?

As a workaround, you can move the files you want to upload out of OneDrive then upload from that directory.

See #96, Release Notes (Help > View Release Notes)

**Comment by briglx** [comment]
The files are stored on a local file system that is synced with onedrive.

**Comment by craxal** [comment]
Yes, and that is the problem. NodeJS, for some reason, can't upload files from a OneDrive-synced location on a local machine. If you move the files to a non-synced folder, does your upload work?

**Comment by briglx** [comment]
Yes it works for in unsynced....this seems like an open issue still.

Thanks,
Brig Lamoreaux

**Comment by craxal** [comment]
Yes, it is an open issue. See #96 for more details. We're using that to track this issue. I've marked this one as a duplicate.
