### ISSUE TITLE
An error occurs when acquiring lease for the multiple ADLS Gen2 blobs including one leased blob

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2160]
**Storage Explorer Version:** 1.10.1
**Build:** [20191029.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3190347)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one ADLS Gen2 storage account.
2. Create a new blob container -> Upload a folder with blobs to it.
3. Acquire lease for one blob.
4. Select multiple blobs including the leased blob -> Acquire leased for the selected blobs.
5. Check the result.

**Expect Experience:**
1. No error occurs.
2. All selected blobs leased.

**Actual Experience:**
An error occurs.
![image](https://user-images.githubusercontent.com/54055206/67755322-e9f6eb80-fa72-11e9-94b4-67d3ecff63cb.png)

**More Info:**
This issue doesn't reproduce for non-ADLS Gen2 blobs.

**Comment by jinglouMSFT** [comment]
@craxal  this is not a regression.

**Comment by craxal** [comment]
Right, sorry. I meant, what happens with regular blobs? We handle that gracefully, so we should fix this for ADLS Gen2.

**Comment by v-limu** [comment]
This issue has been fixed on build 20191029.11. So we close it.
