### ISSUE TITLE
Enter key does not equate to clicking "OK" button in text input dialogs

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#2165]
**Storage Explorer Version**: 1.11.0 (dev)
**Build Number**: 
**Platform/OS**: All
**Architecture**: All
**Regression From**:  N/A

## Bug Description ##
When typing in an input box for a confirmation dialog, hitting the Enter key is not interpreted as clicking the "OK" button.

## Steps to Reproduce ##
1. Open an ADLS Gen2 container. Ensure two or more blobs are uploaded.
2. Acquire leases for two blobs.
3. Select both blobs for which leases were acquired, right click, and select "Break Lease".
4. Enter "Yes" into the input box (as prompted).
5. Press Enter on the keyboard (do not click the OK button).

## Expected Experience ##
The leases are broken for both blobs.

## Actual Experience ##
No leases are broken.

## Additional Context ##
The result object returned by the dialog has a `button` property. When pressing Enter, this property has an empty string as a value. It should be "ok", assuming the OK button is meant to be the default.

**Comment by jinglouMSFT** [comment]
Fix it for 1.11.0
