### ISSUE TITLE
Getting Error - Unable to Retrieve Child Resources 

### ISSUE THREAD

**Issue by SQLfy** [microsoft/AzureStorageExplorer#2166]
**Storage Explorer Version**:  1.10.1 1.10.1 
**Build Number**:  Build 20190919
**Platform/OS**:  Windows 10
**Architecture**:  x64
**Regression From**:   Intermittennt issue with previous version also.  Could be user error but cant get anywhere.

## Bug Description ##

Can't get the blob resource to show in the explorer.
Can't see any of the resources below the blob, file, queue, Table containers.

## Steps to Reproduce ##

I have tried clearing my credentials and logging in in everyway possible 

## Expected Experience ##

Allow me to browse and add folders and upload files.
## Actual Experience ##

No frame appears for those activities to be performed

## Additional Context ##

Help please

**Comment by jinglouMSFT** [comment]
Have you tried to go through the Storage Explorer Troubleshooting Guide?  https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C1904

Also, are you behind a proxy server?  If you do, you need to configure the proxy settings.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
