### ISSUE TITLE
'Rename' is disabled for one blob in one Azure AD attached blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2168]
**Storage Explorer Version:** 1.10.1
**Build:** [20191029.11](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3193677)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Select one blob container which contains one blob at least.
2. Give RBAC access to the blob container to a user like 'Blob Data Owner Role'.
3. Attach this blob container via Azure Active Directory (Azure AD).
4. Right click one blob in the Azure AD attached blob container.
5. Check the blob context menu.

**Expect Experience:**
'Rename' is enabled.

**Actual Experience:**
'Rename' is disabled.
![image](https://user-images.githubusercontent.com/41351993/67845417-6a345400-fb3a-11e9-9eb4-c41bcceb8be2.png)

**More Info:**
1. This issue doesn't reproduce for one ADLS Gen2 blob under one Azure AD attached blob container.

**Comment by v-xianya** [comment]
Hi @craxal 
One question needs your help. Could you help to take a look?

For blobs under Azure AD attached ADLS Gen2 blob containers. We noticed that the 'Rename' is enabled and can successfully rename one blob. 
Is there any difference for **rename mechanism** between ADLS Gen2 blobs and regular blobs under Azure AD attached blob containers?
![image](https://user-images.githubusercontent.com/41351993/67913934-9945d680-fbc9-11e9-8cc7-933f9fce6c1f.png)

**Comment by craxal** [comment]
Yes, that's expected. ADLS Gen2 rename is a service-side operation, so we don't need a key for copy like we do for blobs.

As time goes on, we expect feature parity between blob and ADLS Gen2 functionality to increase.

**Comment by v-xianya** [comment]
@craxal  Got it. Thanks for your updates!😊
