### ISSUE TITLE
Fail to paste multi blobs which copied from one folder

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2169]
**Storage Explorer Version:** 1.10.1
**Build:** [20191029.11](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3193677)
**Branch:** rel/1.11.0
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release (1.10.1)

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Create one blob container -> Upload one folder which contains multi files.
3. Copy files from the uploaded folder and paste it to another normal container.
4. Check the result.

**Expect Experience:**
Paste successfully.

**Actual Experience:**
1. Fail to paste.
![image](https://user-images.githubusercontent.com/41351993/67846024-7a98fe80-fb3b-11e9-8e9b-8225fb8d8e52.png)

2. Details.
{
  "message": "\"failed to parse user input due to error: cannot use wildcards in the path section of the URL except in trailing \\\"/*\\\". If you wish to use * in your URL, manually encode it to %2A\""
}

**More Info:**
This issue doesn't reproduce when pasting one file from a folder.

**Comment by JasonYeMSFT** [comment]
A fix has been merged.

**Comment by v-xianya** [comment]
This issue has been fixed on build 20191101.5. So we close it.
