### ISSUE TITLE
Support 'back' and 'forward' buttons on Windows

### ISSUE THREAD

**Issue by ishepherd** [microsoft/AzureStorageExplorer#217]
**Storage Explorer Version**: 1.1.0

**Platform**: Windows

**Architecture**: ia32

**Build Number**: 20180507.1

**Commit**: bcc8990d

**Regression From**: n/a

Requested feature:

My mouse has hardware buttons on the side for 'back' and 'forwards' actions. (Have not confirmed what they map to - I guess `VK_BROWSER_BACK` or etc)

I'd like for Storage Explorer to support these - I am often using them in Windows Explorer, Google Chrome, etc

**Comment by craxal** [comment]
Can you tell us more of what you'd expect the back and forward keyboard/mouse buttons do? Do you mean that you'd want your mouse buttons to do the same thing as the existing back and forward navigation buttons for the blob and file explorers?

**Comment by ishepherd** [comment]
@craxal Yes. Same as the ⬅️➡️ ribbon buttons or the Alt+Left/Alt+Right keystrokes

These back/forward mouse buttons work in Chrome, Windows Explorer, &etc. Actually I guess they are the `VK_BROWSER_BACK` / `VK_BROWSER_FORWARD` virtual keys.

**Comment by JonathanMaccollum** [comment]
Any update on this? This sure would be handy when navigating folder structures of storage accounts.

**Comment by MRayermannMSFT** [comment]
This is merged for 1.32. In data explorers, forward and back buttons will navigate through navigation history.
