### ISSUE TITLE
Show the edited blob snapshot after selecting 'Snapshot original blob then upload' 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2171]
**Storage Explorer Version:** 1.10.1
**Build:** [20191029.11](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3193677)
**Branch:** rel/1.11.0
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release (1.10.1)

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Select one blob container -> Upload one file.
3. Open this uploaded file and make some changes -> Save it.
4. Select 'Snapshot original blob then upload' on the prompt dialog.
5. Check the content of snapshot.

**Expect Experience:**
The snapshot content is the same as the original blob.

**Actual Experience:**
The snapshot content is the same as the edited blob.

**Comment by JasonYeMSFT** [comment]
A fix has been merged.

**Comment by v-xianya** [comment]
This issue has been fixed on build 20191101.5. So we close it.
