### ISSUE TITLE
The renamed blob doesn't display after renaming one leased ADLS Gen2 blob

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2173]
**Storage Explorer Version:** 1.10.1
**Build:** [20191029.11](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3193677)
**Branch:** rel/1.11.0
**Platform/OS**: Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a new blob container -> Upload a blob to it -> Acquire lease for the blob.
3. Try to rename this blob and check the result.

**Expect Experience:**

1. The renamed blob shows well.
2. Fail to delete the original leased blob.

**Actual Experience:**
The renamed blob doesn't display.

**More Info:**

1. The renamed blob doesn't display after manually refresh.
2. This issue doesn't reproduce for one non-ADLS Gen2 blob.

**Comment by MRayermannMSFT** [comment]
@ v-limu as far as we can see, rename fails if you try to rename a leased blob. Can you check the activity log to see whether or not the rename worked?

**Comment by v-limu** [comment]
Hi @MRayermannMSFT .

1. The log shows 'Failed to rename....'' in Activities.
2. The process of renaming is that create a new blob then delete the original blob. So try to rename one leased ADLS Gen2 blob. the result is that create one new blob (the renamed blob shows well in editor) and fail to delete the original blob.

**Comment by v-limu** [comment]
Hi @MRayermannMSFT Please help to take a look. Thanks in advance!

1. The activity log details shows:

`"message": "There is currently a lease on the resource and no lease ID was specified in the request.\nRequestId:2edbc025-801f-0059-4fb3-a5cbf8000000\nTime:2019-11-28T06:20:54.2933742Z",
`

2. For the second point above. The mechanism of renaming is for one regular leased blob. So is it the same for one leased **ALDS Gen2 blob**?

**Comment by v-xianya** [comment]
1. The error detail is clear:
  **"message": "There is currently a lease on the resource and no lease ID was specified in the request**
2. For the rename action, it use different APIs between HNS-blobs and regulare blobs.
