### ISSUE TITLE
Show an odd string on Conflict dialog when downloading one blob conflict

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2174]
**Storage Explorer Version:** 1.10.1
**Build:** [20191029.11](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3193677)
**Branch:** master
**Platform/OS**: Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release(1.10.1)

**Steps to reproduce:**

1. Expand one storage account -> Blob Containers.
2. Create a new blob container -> Upload a blob to it.
3. Download this blob -> Download this blob to the same destination again.
4. Check the strings on Conflict dialog.

**Expect Experience:**
All strings shows well.

**Actual Experience:**
Show an odd string.
![image](https://user-images.githubusercontent.com/54055206/67846429-30644d00-fb3c-11e9-8b3d-22fb30bcde30.png)

**Comment by JasonYeMSFT** [comment]
The string comes from AzCopy. We may need to locally trim the string.

**Comment by v-limu** [comment]
This issue has been fixed on build 20191031.6. So we close it.
