### ISSUE TITLE
Add 'Rename…' action for one ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2179]
**Storage Explorer Version:** 1.10.1
**Build:** [20191031.6](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3199751)
**Branch:** rel/1.11.0
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Right click one blob container -> Check its context menu.

**Expect Experience:**
'Rename...' displays on the context menu.

**Actual Experience:**
No 'Rename...' displays on the context menu.
![image](https://user-images.githubusercontent.com/41351993/67937843-45f37880-fc09-11e9-9e77-616c6136d606.png)

**Comment by craxal** [comment]
@jinglouMSFT We are not implementing rename for ADLS Gen2 containers for 1.11.0. Are we going to implement this in the future?

**Comment by jinglouMSFT** [comment]
When SDK or REST APIs supports rename, we can add it.  Otherwise renaming a big container subjects to a huge performance hit, and we also have issues with renaming regular blob containers in certain cases.

**Comment by craxal** [comment]
@swums Platform is currently working on a container rename API. Moving to an upcoming milestone so we can make use of it.

**Comment by JasonYeMSFT** [comment]
The "Clone..." (what replaces Rename) action has been supported by ADLS Gen2 now.
