### ISSUE TITLE
Remember table sort order after refresh

### ISSUE THREAD

**Issue by Vivelin** [microsoft/AzureStorageExplorer#218]
**Storage Explorer Version**: 1.1.0

**Platform**: Windows

**Architecture**: ia32

**Build Number**: 20180507.1

**Commit**: bcc8990d

**Regression From**: N/A

#### Steps to Reproduce: ####

1. Open a table from a storage account
2. Click on the RowKey column to change sort order to RowKey ascending
3. Refresh

#### Expected Experience: ####
After refresh, the sort order is still RowKey ascending.

#### Actual Experience: ####
The sort order is reset to PartitionKey ascending.

**Comment by JasonYeMSFT** [comment]
This issue will be fixed in the 1.25.0 release.
