### ISSUE TITLE
Unable to expand File Shares for one Germany Classic storage account

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2180]
**Storage Explorer Version:** 1.10.1
**Build:** [20191031.6](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3199751)
**Branch:** rel/1.11.0
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Sign in Storage Explorer with Azure Germany account.
2. Create a new **classic** storage account in portal under the Germany account subscription -> Open in Storage Explorer.
3. Expand this account -> File Shares.
4. Check the result.

**Expect Experience:**
File Shares expands well.

**Actual Experience:**
Unable to expand the File Shares and pop up an error.
![image](https://user-images.githubusercontent.com/54055206/67935715-6b7e8300-fc05-11e9-8d85-2bdf4b87052f.png)

**More Info:**

1. The File Shares endpoint is empty on Properties panel.
![image](https://user-images.githubusercontent.com/54055206/67935972-e182ea00-fc05-11e9-97f4-63f60fd2516a.png)

2. This issue doesn't reproduce for one Azure/ Azure China Classic storage account.

**Comment by craxal** [comment]
@v-limu It could be that Germany doesn't support file shares for classic accounts, which is why we would not receive a file endpoint. Does it work for v1 and v2 accounts?

**Comment by JasonYeMSFT** [comment]
Can you verify that if Fileshare for classic storage accounts is actually supported by Germany Portal?

**Comment by v-limu** [comment]
Hi @craxal @JasonYeMSFT 

1. File Shares works well for one storage v1 and v2 account.
2. File Shares for one Germany Classic storage account shows well in the Germany Portal.
![image](https://user-images.githubusercontent.com/54055206/67997633-de344080-fc8f-11e9-854a-df89375bc6e7.png)
3. Succeed to open File Shares in the Germany Portal.
![image](https://user-images.githubusercontent.com/54055206/67998250-bc888880-fc92-11e9-8160-6780386c1972.png)

**Comment by craxal** [comment]
Just confirmed that we don't expose file shares, because the service does not return a file endpoint. This also reproduces on 1.10.1.

If the service doesn't return the file endpoint, there's not really much we can do. I'm hesitant to infer endpoints at this stage of the game, because I'm afraid of getting it wrong or a file service not existing.
