### ISSUE TITLE
'Rename...' is enabled for one archived ADLS Gen2 blob

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2182]
**Storage Explorer Version:** 1.10.1
**Build:** [20191031.6](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3199751)
**Branch:** rel/1.11.0
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Select one blob container which contains one blob at least.
3. Right click one blob and change access tier to 'Archive'.
4. Check 'Rename...' on the context menu for the archived blob.

**Expect Experience:**
'Rename...' is disabled.

**Actual Experience:**
1. 'Rename...' is enabled.
2. The archived blob can be renamed successfully.
![image](https://user-images.githubusercontent.com/41351993/67950693-13f00f80-fc25-11e9-8c1f-35bd427deb1a.png)

**Comment by craxal** [comment]
@JingLouMSFT I'm going to say Won't Fix. We don't make this restriction for regular blobs, and if the operation is allowed, I don't see the need to disable it. Do you agree?

**Comment by JasonYeMSFT** [comment]
Since the service allows us to do it, we won't fix it for now.
