### ISSUE TITLE
There is an unrelated bug on Release Notes in New section

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2187]
**Storage Explorer Version:** 1.11.0
**Build:** [20191101.5](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3203746)
**Branch:** rel/1.11.0
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer -> Help -> View Release Notes.
2. Check the bug #[1249](https://github.com/Microsoft/AzureStorageExplorer/issues/1249) appended to settings description 'Display and hide service nodes' on the New section.

**Expect Experience:**
Show the appended bug related to the description.

**Actual Experience:**
The bug is not related to the description.
![image](https://user-images.githubusercontent.com/41351993/68013821-e6f53880-fcc8-11e9-8914-d990709a77f4.png)

**More Info:**
Related bugs to the description 'Display and hide service nodes'.
Bugs: #[1877](https://github.com/microsoft/AzureStorageExplorer/issues/1877), #[2146](https://github.com/microsoft/AzureStorageExplorer/issues/2146)

**Comment by craxal** [comment]
Can't seem to find the correct bug, so we'll just remove it, unless someone knows what the correct bug number is?

**Comment by craxal** [comment]
Found it. Bug in question is #1877.
