### ISSUE TITLE
The access tier doesn't auto refresh for one regular blob

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2188]
**Storage Explorer Version:** 1.11.0
**Build:** [20191101.5](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3203746)
**Branch:** rel/1.11.0
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one GPV2 storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Change the blob access tier -> Observe whether the access tier auto refresh or not.

**Expect Experience:**
The access tier auto refresh.

**Actual Experience:**
The access tier doesn't auto refresh.

**More Info:**
The access tier auto refresh for one ADLS Gen2 blob.

**Comment by craxal** [comment]
Missing the three lines of update code. Easy to put in.
