### ISSUE TITLE
Add "Search by prefix (case-sensitive)" in one ADLS Gen2 blob container editor

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2189]
**Storage Explorer Version:** 1.11.0
**Build:** [20191101.5](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3203746)
**Branch:** rel/1.11.0
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create one blob container -> Check its editor.

**Expect Experience:**
Show "Search by prefix (case-sensitive)" in the editor.
![image](https://user-images.githubusercontent.com/41351993/68015166-8e279f00-fccc-11e9-8cc5-5fe8d8eaad9e.png)

**Actual Experience:**
No "Search by prefix (case-sensitive)" shows in the editor.

**Comment by craxal** [comment]
We left this out by design. We didn't have much time, and we didn't want a shoddy search experience.

**Comment by canjoh** [comment]
This feature is still missing for Gen2 blobs. I have lots of Gen2 blob containers with many blobs in them and it is very difficult to find anything without a search. Is this being added soon?

**Comment by jasonhendrix** [comment]
I see this issue became a P1 "fix for next release" in February but there have been 6 releases since then.

Any updates on when this might be available?

**Comment by richardMSFT** [comment]
Search by prefix for ADLS Gen2 has been added and will ship with 1.28.0

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20230127.10, Search by prefix for ADLS Gen2 has been added.
![image](https://user-images.githubusercontent.com/87792676/215238744-d1c50423-546e-4644-8efe-7bebdb2b0b2d.png)
