### ISSUE TITLE
Add support for Right-click -> Paste

### ISSUE THREAD

**Issue by alexmarshall132** [microsoft/AzureStorageExplorer#219]
**Storage Explorer Version**: 1.1.0

**Platform**: Windows 10

**Architecture**: ia32

**Build Number**: 20180507.1

**Commit**: bcc8990d

#### Steps to Reproduce: ####

1. After opening the application, go to (Local and Attached) in the Explorer pane
2. Right-click on 'Cosmos DB Accounts (preview)' -> 'Connect to Cosmos DB'
3. In the 'Connection String' text box, right-clicking produces no context menu.

#### Expected Experience: ####
Like any other Windows text box, I expect a context menu to allow me to cut, copy and paste text.

#### Actual Experience: ####
No context menu appears

**Comment by MRayermannMSFT** [comment]
Hi @djlan , please triage this bug!

**Comment by jinglouMSFT** [comment]
CosmosDB has been removed from Storage Explorer.

**Comment by alexmarshall132** [comment]
Thank you!
