### ISSUE TITLE
Fail to save access polices for one blob container which name contains 63 characters

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2191]
**Storage Explorer Version:** 1.11.0
**Build:** [20191101.5](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3203746)
**Branch:** rel/1.11.0
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Create one blob container with name contains 63 characters.
3. Right click the new created blob container -> Open its 'Manage Access Policies' dialog.
4. Add one access policy then clicking Save ->  Check the result.

**Expect Experience:**
1. No error occurs.
2. The new added access policy can be saved successfully.

**Actual Experience:**
An error occurs.
![image](https://user-images.githubusercontent.com/41351993/68017283-553df900-fcd1-11e9-8c82-396cbae21831.png)

**More Info:**
1. This issue also reproduce for one file share /queue/ table which name contains 63 characters.
f**ile share:**
![image](https://user-images.githubusercontent.com/41351993/68017386-8fa79600-fcd1-11e9-87ff-c8e4d9ef6601.png)

**queue:**
![image](https://user-images.githubusercontent.com/41351993/68017408-9f26df00-fcd1-11e9-8221-9a6613ef6934.png)

 **table:**
![image](https://user-images.githubusercontent.com/41351993/68017422-a77f1a00-fcd1-11e9-8dda-f81d690f6de3.png)

**Comment by craxal** [comment]
@v-xianya What is the name of the container? The error says the signed identifier is too long. What are the IDs of the policies you're trying to save?

**Comment by craxal** [comment]
I don't think this is a common scenario users will find themselves in, so I'm fine with fixing this in a later release, especially if this is a common issue across all other services.

**Comment by MRayermannMSFT** [comment]
I don't see this repro'ing. With an ID of length 63, everything works well. At a length of 64, we say the id is too long. Feel free to reopen if you see otherwise.

**Comment by v-limu** [comment]
Hi @MRayermannMSFT 
Verified on build [20200228.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3510155). This issue still reproduces. So we reopen it.
![image](https://user-images.githubusercontent.com/54055206/75527643-eb9ae500-5a4d-11ea-9b6c-8f567e1ff7dd.png)

**Comment by MRayermannMSFT** [comment]
AHHHHHH I UNDERSTAND NOW. I SEE I SEE I SEE!

**Comment by MRayermannMSFT** [comment]
The default name we generate for the IDs are too long!

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
