### ISSUE TITLE
'Refresh' button still under 'More' on the toolbar after toggling Explorer 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2194]
**Storage Explorer Version:** 1.11.0
**Build:** [20191101.5](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3203746)
**Branch:** rel/1.11.0
**Platform/OS:** Linux Ubuntu 19.04
**Architecture:** x64
**Regression From:** Previous release(1.10.1)

**Steps to reproduce:**

1. Expand Data Lake Storage Gen1(Preview).
2. Open one ADLS Gen1 account -> Toggle Explorer.
3. Check all buttons on toolbar.

**Expect Experience:**
All buttons show well on toolbar.
![image](https://user-images.githubusercontent.com/54055206/68018189-83bcd380-fcd3-11e9-9e3e-253970d47d96.png)

**Actual Experience:**
'Refresh' button still under 'More'.
![image](https://user-images.githubusercontent.com/54055206/68018210-90412c00-fcd3-11e9-92e7-0541b45d48bd.png)

**Comment by craxal** [comment]
More or less expected behavior for now, because we use "t-shirt" sizes, not exact pixels. At some point we need to revisit the toolbar layout logic to take better advantage of the available space.

**Comment by v-xianya** [comment]
1. The same issue occurs for regular blob containers editor. (**In Korean/ Japanese**)
2. This issue doesn't reproduce on MacOS.
Korean screenshot:
![image](https://user-images.githubusercontent.com/41351993/71436395-3c2d5380-2728-11ea-9021-034598a95020.png)

     Japanese screenshot:
![image](https://user-images.githubusercontent.com/41351993/71436445-6ed74c00-2728-11ea-80fc-06735f158b4d.png)
