### ISSUE TITLE
Create common `BlobFlobContainer` property in context for commands

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#2196]
Many commands in explorers use a `BlobFlobContainer` or similar object for certain things, like refreshing single items rather than the entire data table. We should consider factoring this out to the context, since there's nothing unique the commands initialize it with.

**Comment by JasonYeMSFT** [comment]
Blob explorer has been moved and I removed all Blob commands' dependency on BlobFlobConaitner.

**Comment by craxal** [comment]
@JasonYeMSFT This is less about `BlobFlobContainer` specifically, and more about refactoring similar behavior in commands to the base command class. If most commands initialize and use some kind of object that represents the container, that behavior would be better suited for the command base class so that all commands can make use of it.
