### ISSUE TITLE
Cannot authenticate with Azure repo in Storage Explorer

### ISSUE THREAD

**Issue by khairulneezam** [microsoft/AzureStorageExplorer#2200]
**Storage Explorer Version**: 1.10.1
**Build Number**:  20190919.2
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  NIL.

## Bug Description ##
![image](https://user-images.githubusercontent.com/57341293/68102083-04feab00-ff0c-11e9-93f4-56879998c614.png)

Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: 812b1e72-2671-4a1e-bc3f-0519db4e3723, Error: {
  "name": "Error",
  "message": "self signed certificate in certificate chain",
  "stack": "Error: self signed certificate in certificate chain\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at TLSSocket.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at TLSSocket.emit (events.js:182:13)\n    at TLSSocket._finishInit (_tls_wrap.js:631:8)",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}

## Steps to Reproduce ##
1. Head on over to: ![image](https://user-images.githubusercontent.com/57341293/68102083-04feab00-ff0c-11e9-93f4-56879998c614.png)
2. Click on More information.

## Expected Experience ##
It should've have authenticated without issues.

## Actual Experience ##
I cannot view my Azure repo/blob.

## Additional Context ##
NIL

**Comment by JasonYeMSFT** [comment]
Could you please try the steps in our trouble shooting guide? 
[self signed cert section in trouble shooting guide](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting#error-self-signed-certificate-in-certificate-chain-and-similar-errors)

**Comment by MRayermannMSFT** [comment]
Closing due to lack of reply
