### ISSUE TITLE
Update 'Blob container' to 'blob container' on Release Notes in last part of New section

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2201]
**Storage Explorer Version:** 1.11.0
**Build:** [20191102.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3207164)
**Branch:** rel/1.11.0
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer -> Help -> View Release Notes.
2. Check the last part in New section.

**Expect Experience:**
Display 'if you attach an ADLS Gen2 **blob container**'.

**Actual Experience:**
Display 'if you attach an ADLS Gen2 **Blob container**'.
![image](https://user-images.githubusercontent.com/41351993/68111306-c841ac80-ff29-11e9-980b-de17925a9839.png)

**Comment by MRayermannMSFT** [comment]
We think the casing is correct. Blob is the product name, container is a technical term.
