### ISSUE TITLE
Break Lease dialog is unfriendly when the blob name is too long

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2203]
**Storage Explorer Version:** 1.11.0
**Build:** [20191102.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3207164)
**Branch:** rel/1.11.0
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Select one blob container which contains one blob at least.
3. Select one blob and rename it with a long name (like: accoutaccoutaccoutaccoutaccoutaccoutaccouttaccoutaccoutaccoutaccoutaccoutaccoutaccout.txt.)
4. Acquire lease for the blob then try to break lease.
5. Check the break lease dialog.

**Expect Experience:**
Break Lease dialog shows well.

**Actual Experience:**
Break Lease dialog is unfriendly.
![image](https://user-images.githubusercontent.com/41351993/68113406-badaf100-ff2e-11e9-9d78-db8895a5e7d4.png)

**Comment by MRayermannMSFT** [comment]
Fix checked into master.

**Comment by v-limu** [comment]
This issue reproduces on build [20191119.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3255785). So we reopen it.

**More Info:**

1. This issue reproduces when the blob name include **no space**.
![image](https://user-images.githubusercontent.com/54055206/69145876-945dae00-0b09-11ea-895e-3ee829492ba1.png)

2. This issue doesn't reproduce when the blob name include space.
![image](https://user-images.githubusercontent.com/54055206/69145932-b1927c80-0b09-11ea-9680-d0db3e6e05c9.png)

**Comment by MRayermannMSFT** [comment]
The hotfix will not contain this fix. Please only verify it on master builds. Thanks.
