### ISSUE TITLE
There are no properties for one attached Cosmos DB account in Properties panel 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2204]
**Storage Explorer Version:** 1.11.0
**Build:** [20191102.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3207164)
**Branch:** rel/1.11.0
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Create a cosmos DB account with SQL API.
2. Navigate to the created account from Storage Explorer.
3. Copy the 'Primary Connection String' then open 'Connect to Cosmos DB' dialog.
4. Select SQL API then paste the connection string -> 'Next'.
6. Check the properties for the attached Cosmos DB account in the Properties panel.

**Expect Experience**
There are properties in Properties panel.

**Actual Experience:**
There are no properties in Properties panel.
![image](https://user-images.githubusercontent.com/41351993/68114224-781a1880-ff30-11e9-9738-4a7bfa94c430.png)

**More Info:**
This issue also reproduces for one Cosmos DB account with **Table API**.

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
