### ISSUE TITLE
Update '运算符' to '文件共享' on the prompt dialog when renaming a file share with an exist name

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2206]
**Storage Explorer Version:** 1.11.0
**Build:** [20191105.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3213388)
**Branch:** rel/1.11.0
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** Chinese(zh-CN)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Chinese (simplified)' -> Restart Storage Explorer.
3. Expand one storage account -> File Shares.
4. Create two file shares -> Rename one file share using another file share's name.
5. Check the prompt dialog.

**Expect Experience:**

Show '具有该名称的**文件共享**已存在' on the dialog.

**Actual Experience:**

Show '具有该名称的**运算符**已存在' on the dialog.
![image](https://user-images.githubusercontent.com/41351993/68189248-ed93f080-ffe5-11e9-914b-47bc6ffd9e12.png)

**More Info:**
1. This issue also reproduces for one blob container. (Update '运算符' to 'blob 容器')
2. The prompt dialog shows like below in Chinese (traditional). 
![image](https://user-images.githubusercontent.com/41351993/68189980-7b241000-ffe7-11e9-82d2-ea868bab30ab.png)

**Comment by lukaschal** [comment]
On review.

File: loc\en\src\Standalone\resources\Activities.json
ID: 0; "ErrorItemExists"
SRC: An item with that name already exists.
TGT: 具有该名称的运算符已存在。

**Comment by lukaschal** [comment]
Fixed.

new tgt: 具有该名称的文件共享已存在

**Comment by v-xianya** [comment]
Hi @lukaschal Verified this issue on master/20191123.1.
1. For one fileshare, this issue has been fixed.

2. For one blob container, Need to **update '文件共享' to 'blob 容器'**.
![image](https://user-images.githubusercontent.com/41351993/69522791-26552480-0f17-11ea-8e5c-7ee3182d340e.png)

**Comment by lukaschal** [comment]
@v-xianya Could you please provide ENU screenshot of dialog, where "文件共享" needs to be updated to 'blob 容器'. ?

**Comment by v-xianya** [comment]
Hi @lukaschal when renaming one blob container using an exist name.

ENU screenshot
![image](https://user-images.githubusercontent.com/41351993/69593791-2274e100-0faf-11ea-98ac-80d7f498582a.png)

zh-CN screenshot
![image](https://user-images.githubusercontent.com/41351993/69593966-bd6dbb00-0faf-11ea-8f6f-4313e111d994.png)

zh-TW screenshot
![image](https://user-images.githubusercontent.com/41351993/69594114-28b78d00-0fb0-11ea-8087-ded868007391.png)

**Comment by lukaschal** [comment]
@v-xianya So, you are suggesting change "具有该名称的文件共享已存在" to "具有该名称的blob 容器已存在", but source says "An item with that name already exists.", no "blob container" occurs in a source sentence.

**Comment by v-xianya** [comment]
Hi @lukaschal 
It is good to change "具有该名称的文件共享已存在" to "具有该名称的项目已存在",

**Comment by johnliu2016** [comment]
Implemented as suggested.

**Comment by v-xianya** [comment]
This issue has been fixed on build 20191205.1. So we close it.
