### ISSUE TITLE
The strings append to log message are not localized in Activities panel

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2208]
**Storage Explorer Version:** 1.11.0
**Build:** [20191105.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3213388)
**Branch:** rel/1.11.0
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** Chinese(zh-CN)/ Chinese(zh-TW)/ Japanese/ Korean/ German/ Spanish/ Czech
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Chinese (simplified)' -> Restart Storage Explorer.
3. Upload one large files to one blob container.
4. Observe the log message in Activities panel.

**Expect Experience:**
The strings append to log message are localized.

**Actual Experience:**
The strings append to log message are not localized completely.
![image](https://user-images.githubusercontent.com/41351993/68191739-2a161b00-ffeb-11e9-81c4-6575b03c93d4.png)

**More Info:**
![image](https://user-images.githubusercontent.com/41351993/68191787-4023db80-ffeb-11e9-9083-4530f55458af.png)
![image](https://user-images.githubusercontent.com/41351993/68191797-431ecc00-ffeb-11e9-8dae-fd744232b139.png)

**Comment by lukaschal** [comment]
@craxal Localized at 10/7/2019.

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer/commit/135b519bdbae147710eede7846ef2e0d76d0b7c5?_a=compare&path=%2Floc%2Floc%2Fzh-Hans%2Fsrc%2Fcomponents%2Fse-managed-disks-extension%2Fresources%2FDiskCopy.json.lcl

**Comment by JasonYeMSFT** [comment]
Package updated in master. @v-xianya, please verify the translated strings.

**Comment by v-xianya** [comment]
@JasonYeMSFT 
Verified this issue on build [20200118.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3397152&view=results).
 The string '**Cancel**' is not translated for **Copy& Paste/ Upload& Download/ Delete** activities logs.
![image](https://user-images.githubusercontent.com/41351993/72677287-9fb36280-3ad5-11ea-93ba-cebc8089a277.png)

**Comment by JasonYeMSFT** [comment]
@v-xianya, "Details" happens to be the same in English and Dutch. You can verify it using online translator. The "Cancel" translation is recently added, we will update the package for it.

**Comment by v-xianya** [comment]
@JasonYeMSFT 
Verified this issue on the lastes build 20200201.2. 
'Cancel' is not localized.
![image](https://user-images.githubusercontent.com/41351993/73635662-f5c00280-469e-11ea-98fa-27e463aec94d.png)

**Comment by JasonYeMSFT** [comment]
We recently published a new azcopy package which should have contained the translated strings.

**Comment by v-xianya** [comment]
This issue has been fixed on build 2[0200216.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3477731). So we close it.
