### ISSUE TITLE
Various error dialogs are not or not completely localized

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2209]
**Storage Explorer Version:** 1.11.0
**Build:** [20191105.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3213388)
**Branch:** rel/1.11.0
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** Chinese(zh-CN)/ Chinese(zh-TW)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Bug descriptions:**

Dialogs for the below situation are not or not completely localized.

1. Deleting one leased blob.
 2.  Create a new blob container/ file share/ queue/ table with an exist name.
 3. Delete one Metrics table.
 4. Create one blob container/ file share/ table/ queue with an invalid name.
 5. Try to remove one user account.
6. Delete one file share with snapshots.
 7. Cancel during sign-in.

![image](https://user-images.githubusercontent.com/41351993/68192439-49617800-ffec-11e9-9208-a49b18ee473e.png)
![image](https://user-images.githubusercontent.com/41351993/68192431-45355a80-ffec-11e9-84be-0b150932ad6f.png)
![image](https://user-images.githubusercontent.com/41351993/68192443-4cf4ff00-ffec-11e9-8b47-1d3d82452672.png)

![image](https://user-images.githubusercontent.com/41351993/68192461-52eae000-ffec-11e9-9277-d4be6e5bc475.png)
![image](https://user-images.githubusercontent.com/41351993/68192477-55e5d080-ffec-11e9-818a-11d796201507.png)
![image](https://user-images.githubusercontent.com/41351993/68192489-59795780-ffec-11e9-9920-fa1c9d540599.png)
![image](https://user-images.githubusercontent.com/41351993/68192495-5c744800-ffec-11e9-9c49-fce8c980b9ae.png)

**Expect Experience:**
All dialogs are localized.

**Actual Experience:**
Various dialogs are not or not completely localized.

**Comment by lukaschal** [comment]
@craxal Already localized or hard-coded.

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer?path=%2Fsrc%2FStandalone%2Fapp%2Frenderer%2Fproviders%2FConnectProvider%2FConnectProvider.ts&version=GBmaster

https://devdiv.visualstudio.com/DevDiv/_git/CloudExplorer?path=%2Fsrc%2FCloudHub%2Fts%2FProviders%2FAzure%2FActions%2FAzureStorageActions.ts&version=GBmaster

https://devdiv.visualstudio.com/DevDiv/_git/SwaggerValidation?path=%2FAzure%2FSwaggerServiceTest%2Fpackages%2FWindowsAzure.Storage.7.1.2%2Flib%2Fnet40%2FMicrosoft.WindowsAzure.Storage.xml&version=GBmaster

**Comment by craxal** [comment]
Won't fix. These are errors we get from Azure; they're not our strings.
