### ISSUE TITLE
Can't cancel uploads

### ISSUE THREAD

**Issue by Peter-Juhasz** [Microsoft/AzureStorageExplorer#221]
**Storage Explorer Version**: latest 1.10

**Platform**: 

**Architecture**: 

**Build Number**: 

**Commit**: 

**Regression From**: 

#### Steps to reproduce: ####
Cancel All on upload group.

#### Actual Experience: ####
Some uploads get cancelled, some are still initializing upload and are not even visible. I was trying to upload 1000+ files.
![image](https://user-images.githubusercontent.com/9047283/40583731-7c335b6a-6194-11e8-9698-d8309ec315f1.png)

It is really unreliable.

**Comment by craxal** [comment]
Please provide us some more information:
- Platform
- Architecture
- Regression (what version was this working for you, if any?)
- Repro steps
  - Are you uploading to a blob container or file share?
  - How large are the files you're attempting to upload?

**Comment by codificador-nocturno** [comment]
Hi, same problem here.

Version: 1.1.0
Platform: macOS High Sierra
Architecture: 64bits
Regression: not known
Repro steps:
Uploading to blob container (70.000+ small files, < 1MB each)
Files that hang and cannot be cancelled are hidden files (starting with a dot inside a __MACOSX subfolders)
Other type of files upload upload without issues

Thanks!

**Comment by MRayermannMSFT** [comment]
Closing as stale. Please open a new issue for any cancelling issues on version 1.4.0 or later. Thanks!
