### ISSUE TITLE
The warning message is not localized when typing one invalid blob container name

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2210]
**Storage Explorer Version:** 1.11.0
**Build:** [20191105.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3213388)
**Branch:** rel/1.11.0
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** Czech/ German/ Spanish/ French/ Hungarian/ Italian/ Japanese/ Korean/ Dutch/ Polish/ Portuguese (Brazil)/ Portuguese (Portugal)/ Russian/ Swedish/ Turkish/ Chinese (Simplified) / Chinese (Traditional)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Chinese (simplified)' -> Restart Storage Explorer.
3. Expand one storage account -> Blob Containers.
4. Create one blob container and type an invalid name.
5. Check the warning message.

**Expect Experience:**
The warning message is localized.

**Actual Experience:**
The warning message is not localized.
![image](https://user-images.githubusercontent.com/41351993/68198481-18d30b80-fff7-11e9-9fbc-c68c63b474d0.png)

**More Info:**
This issue also reproduces for one file share/ table/ queue.
![image](https://user-images.githubusercontent.com/41351993/68198541-3607da00-fff7-11e9-8636-5a51c6d73ead.png)

**Comment by lukaschal** [comment]
Hard-coded.

https://devdiv.visualstudio.com/DevDiv/_git/CloudExplorer?path=%2Fsrc%2FCloudHub%2Fts%2FProviders%2FAzure%2FActions%2FAzureStorageActions.ts&version=GBmaster

**Comment by MRayermannMSFT** [comment]
Fix merged and strings appear to be translated.
