### ISSUE TITLE
The notification of an expiry time is not localized on SAS dialog for one file share

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2212]
**Storage Explorer Version:** 1.11.0
**Build:** [20191105.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3213388)
**Branch:** rel/1.11.0
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** Czech/ German/ Spanish/ French/ Hungarian/ Italian/ Japanese/ Korean/ Dutch/ Polish/ Portuguese (Brazil)/ Portuguese (Portugal)/ Russian/ Swedish/ Turkish/ Chinese (Simplified) / Chinese (Traditional)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Chinese (traditional)' -> Restart Storage Explorer.
3. Select a storage account -> File Shares.
4. Create a new file share -> Right click it -> Click 'Get Shared Access Signature...'.
5. Delete the default Expiry time on SAS dialog.
6. Hover over the Expiry time box -> Check the notification message.

**Expect Experience:**
The notification message is localized.

**Actual Experience:**
The notification message is not localized.
![image](https://user-images.githubusercontent.com/54055206/68197548-68183c80-fff5-11e9-8f79-296c629c1ecb.png)

**More Info:**
This issue also reproduces for one table/queue/ regular blob container.

**Comment by lukaschal** [comment]
Hard-coded string.

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer?path=%2Fsrc%2FStandalone%2Fapp%2Fdialogs%2FGenerateSas%2FGenerateSasPanelViewModel.ts&version=GBmaster

**Comment by MRayermannMSFT** [comment]
Fix merged and strings appear to be translated.
