### ISSUE TITLE
There are strings haven't been translated in Query Builder for one table

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2213]
**Storage Explorer Version:** 1.11.0
**Build:** [20191105.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3213388)
**Branch:** rel/1.11.0
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** Czech/ German/ Spanish/ French/ Hungarian/ Italian/ Japanese/ Korean/ Dutch/ Polish/ Portuguese (Brazil)/ Portuguese (Portugal)/ Russian/ Swedish/ Turkish/ Chinese (Simplified) / Chinese (Traditional)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Chinese (traditional)' -> Restart Storage Explorer.
3. Select a storage account -> Tables -> Open one table.
4. Open 'Query' -> 'Advanced Options' -> 'Choose Columns..' -> Select all and save it.
5. Check the strings in editor.

**Expect Experience:**
All strings are translated.

**Actual Experience:**
There are strings haven't been translated.
![image](https://user-images.githubusercontent.com/54055206/68198375-dad5e780-fff6-11e9-9805-27935c5c1fef.png)

**More Info:**
This issue also reproduces on 'Text editor'.
![image](https://user-images.githubusercontent.com/54055206/68198507-27b9be00-fff7-11e9-8cf9-589222db6a0a.png)

**Comment by lukaschal** [comment]
Hard-coded.

https://devdiv.visualstudio.com/DevDiv/_git/CloudExplorer?path=%2Fsrc%2FCloudHub%2Fts%2FStorageExplorer%2FTables%2FTableQuery%2FQueryViewModel.ts&version=GBmaster

**Comment by v-limu** [comment]
This issue also reproduces in **Japanese**.
![image](https://user-images.githubusercontent.com/54055206/71237346-3e646c00-233c-11ea-971a-9f50c9e51b32.png)

**Comment by MRayermannMSFT** [comment]
I'll fix the info message, the but `and`, `or`, and other strings in the text box are not supposed to be localized. Think of that string as code. The `and` and `or` are specific syntax for the query language.

**Comment by MRayermannMSFT** [comment]
Looks like the strings are loc'd now. Closing.

**Comment by v-limu** [comment]
Verified on build [20200226.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3502854). This issue has been fixed. So we close it.
