### ISSUE TITLE
The 'New Directory' is not localized on Create New Directory dialog for one file share

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2214]
**Storage Explorer Version:** 1.11.0
**Build:** [20191105.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3213388)
**Branch:** rel/1.11.0
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** Chinese(zh-CN)/ Chinese(zh-TW)/ Japanese/ Korean/ German / Russian/ Portuguese (Brazil)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Chinese (simplified)' -> Restart Storage Explorer.
3. Select a storage account -> File Shares
4. Create a new file share -> Click 'New Folder' on toolbar.
5. Check the dialog.

**Expect Experience:**
The 'New Directory' is localized on dialog.

**Actual Experience:**
The 'New Directory' is not localized on dialog.
![image](https://user-images.githubusercontent.com/54055206/68198735-9860da80-fff7-11e9-8a8c-17502bd375c6.png)

**More Info:**

1. This issue also produces for one **regular blob container**.
2. This issue **doesn't** produce for one **ADLS Gen2 blob container**.
![image](https://user-images.githubusercontent.com/54055206/68198811-b75f6c80-fff7-11e9-9457-8d7cab8868c4.png)

**Comment by lukaschal** [comment]
Hard-coded.

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer?path=%2Fsrc%2FStandalone%2Fapp%2Fdialogs%2FAddDirectory%2FAddDirectoryViewModel.ts&version=GBmaster

**Comment by v-limu** [comment]
Verified on build [20200201.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3434212&view=results
). This issue still reproduces for one **regular blob container**. So we reopen it.
![image](https://user-images.githubusercontent.com/54055206/73636548-f1520600-461a-11ea-9e04-3d3dc4c4e2ad.png)

**Comment by MRayermannMSFT** [comment]
Looks like the strings are loc'd now. Closing.
