### ISSUE TITLE
Still showing 'Loading' in Quick Access on Mac.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/AzureStorageExplorer#2216]
**Storage Explorer Version**: 1.11.0
**Build Number**: 20191102.1
**Platform/OS**:  macOS High Sierra
**Language**: Chinese(zh-CN)/ Chinese(zh-TW)
**Regression From**: Not a regression

**Steps to reproduce:**

1. Open ASE
2. Expand the 'Quick Access'

**Expect Experience:** 
Show quick access.

**Actual Experience:** 
Still showing 'Loading' in Quick Access on Mac.
![image](https://user-images.githubusercontent.com/40199316/68200790-85e8a000-fffb-11e9-9c52-b363dae9adf3.png)

**Comment by jinglouMSFT** [comment]
@v-lanjli Did "Loading..." ever go away for you?

**Comment by v-lanjli** [comment]
@jinglouMSFT , no, when I expand 'Quick Access' node, it always shows loading...

**Comment by v-xianya** [comment]
This issue doesn't reproduce on my side in 1.11.0 release.

**Comment by jinglouMSFT** [comment]
@v-lanjli likely the cached files on your machine are corrupted.  Can you try to delete the following?  Close Storage Explorer first, then delete 
/Users/<your_name>/Library/Application Support/StorageExplorer
then restart Storage Explorer.

Note that if you have ever imported any SSL certificates, back up the contents of the certs directory. Later, you can use the backup to reimport your SSL certificates.

**Comment by v-lanjli** [comment]
@jinglouMSFT I followed the steps you provided and the issue was solved. Closed this issue. Thanks for your help~ 
![image](https://user-images.githubusercontent.com/40199316/68375660-3385bb80-0182-11ea-85d9-8c676420f849.png)
