### ISSUE TITLE
Localization issue with 'Detach'.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/AzureStorageExplorer#2218]
**Storage Explorer Version:** 1.11.0
**Build Number:** 20191102.1
**Platform/OS:**  Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** Chinese(zh-CN)/ Chinese(zh-TW)
**Regression From:** Not a regression

**Steps to reproduce**:

1. Open ASE
2. Sign in to Azure
3. Right click on Data Lake Storage Gen 1 (Preview) node under the Local & Attached
4. Connect to Data Lake Storage Gen 1
5. Right click on the connected Data Lake Storage Gen 1
6. Check the 'Detach'

**Expect Experience:**
'Detach' is localized.

**Actual Experience:**
The 'Detach' is not localized.
![image](https://user-images.githubusercontent.com/40199316/68202780-5045b600-ffff-11e9-9090-238a7403471d.png)

**Comment by jinglouMSFT** [comment]
We are not localizing ADLS Gen1.
