### ISSUE TITLE
[Data Lake Storage Gen 1 (Preview)]Localization with tool bar.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/AzureStorageExplorer#2219]
**Storage Explorer Version:** 1.11.0
**Build Number:** 20191102.1
**Platform/OS:** macOS High Sierra
**Language:** Chinese(zh-CN)/ Chinese(zh-TW)
**Regression From:** Not a regression

**Steps to reproduce:**

1. Open ASE
2. Sign in to Azure
3. Expand the Data Lake Storage Gen1 (Preview) node
4. Select and open a Data Lake Storage Gen1 in list
5. Check the Data Lake Storage Gen1 window

**Actual Experience:**
Tool bar are not localized.
![image](https://user-images.githubusercontent.com/40199316/68204185-6a34c800-0002-11ea-92c1-f1225c5c5339.png)

**Comment by jinglouMSFT** [comment]
This is by-design. ADLS Gen1 was implemented by a different team, and the users are now strongly recommended to move to ADLS Gen2.  Gen1 is in the process of being deprecated.
