### ISSUE TITLE
CosmosDB filter field unreadable when using dark theme

### ISSUE THREAD

**Issue by DotNetNerd** [microsoft/AzureStorageExplorer#2220]
**Storage Explorer Version**: 1.10.1
**Build Number**: 20190919.2
**Platform/OS**: Windows 10

## Bug Description ##
When I open a tab with a CosmosDB collection and try to apply a filter the text and background for the box is the same color, so I can't read what I am writing.

## Steps to Reproduce ##
When I open a tab with a CosmosDB collection and try to apply a filter the text and background for the box is the same color, so I can't read what I am writing.

## Expected Experience ##
I expect to be able to see what I write

## Actual Experience ##
I can't see what I am writing

**Comment by jinglouMSFT** [comment]
This likely is a duplicate.

**Comment by v-xianya** [comment]
Related bug: [202](https://github.com/microsoft/AzureStorageExplorer/issues/202)

**Comment by blugri** [comment]
Bug is not limited to Windows OS, I see the bug also on MacOS

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
