### ISSUE TITLE
Create Disk Error - Upload VHD to Disk Failing in Azure Government Subscription

### ISSUE THREAD

**Issue by HAMB0NE** [microsoft/AzureStorageExplorer#2221]
**Storage Explorer Version**: 1.10.1
**AzCopy Version**: 10.2.1
**Build Number**: 20190919.2
**Platform/OS**: Windows 10
**Architecture**: ia32
**Regression From**:  Wasn't tried in previous versions

## Bug Description ##
Storage Explorer was unable to revoke access to a disk.
The disks involved in this operation may still be in an 'Active SAS' state. You may need to return the disks to an 'Unattached' state before retrying this operation, or before performing new operations on the disks.

## Steps to Reproduce ##
1. Select Disks in the Subscription looking to upload the VHD into a Disk
2. Select the Resource Group to upload the VHD into
3. Select Upload and fill out the information on the pop-up including the location of where the VHD file is located
4. After several hours of the upload being accomplished - it completes with a Disk State of "ActiveUpload" and a "Failed to upload..." error message in Activities.

## Expected Experience ##
To upload the VHD as a Disk successfully for use in Azure per guidance at https://docs.microsoft.com/en-us/azure/virtual-machines/windows/disks-use-storage-explorer-managed-disks

## Actual Experience ##
Trying to upload a VHD (~30GB in size) into a Disk via the Azure Storage Explorer - received the below error message of "Create Disk Error":

Storage Explorer was unable to revoke access to a disk.
The disks involved in this operation may still be in an 'Active SAS' state. You may need to return the disks to an 'Unattached' state before retrying this operation, or before performing new operations on the disks.

Service response: {
  "name": "Error",
  "message": "The access token expiry UTC time '11/4/2019 10:34:06 PM' is earlier than current UTC time '11/5/2019 3:58:05 AM'.",
  "stack": "Error: The access token expiry UTC time '11/4/2019 10:34:06 PM' is earlier than current UTC time '11/5/2019 3:58:05 AM'.\n    at new RestError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\ms-rest-js\\dist\\msRest.node.js:2400:28)\n    at C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\ms-rest-js\\dist\\msRest.node.js:3544:37\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
  "code": "ExpiredAuthenticationToken",
  "statusCode": 401,
  "request": {
    "streamResponseBody": false,
   
## Additional Context ##
Reviewed "Error copying managed disk, large disk, (access token expiry)" #2048 and adjusted the StartAzCopyState.js per the recommended solution to disable the MD5 check - but, ended up with the same result. Also reviewed "Storage Explorer was unable to revoke access to a disk when copying data disk over 256GB #2128" Have attempted to upload the VHD 4 times total now - with the 4th attempt using the fix action in #2048. 

Attached the last .azcopy log from the 4th attempt for review.
[a5759a72-f7aa-a443-740a-4b8d47df11c8.log](https://github.com/microsoft/AzureStorageExplorer/files/3809161/a5759a72-f7aa-a443-740a-4b8d47df11c8.log)

Attached Full Error Details from 4th attempt:
[CreateDiskError_4NOV19_FullErrorDetails.txt](https://github.com/microsoft/AzureStorageExplorer/files/3809176/CreateDiskError_4NOV19_FullErrorDetails.txt)

**Comment by jinglouMSFT** [comment]
@HAMB0NE  We just released v1.11.0 that potentially has a fix to the issue you ran into.  Would you download it and give it a try?  You can download the bits either from http://storageexplorer.com or go to the Release tab here in github to download v1.11.0.  Thanks.

**Comment by HAMB0NE** [comment]
> @HAMB0NE We just released v1.11.0 that potentially has a fix to the issue you ran into. Would you download it and give it a try? You can download the bits either from http://storageexplorer.com or go to the Release tab here in github to download v1.11.0. Thanks.

@jinglouMSFT - I downloaded and installed the latest version per your recommendation and kicked off the upload...took some time, but it shows that it completed successfully in Azure Storage Explorer. :-) Thanks for the assistance! Looks like we can close this issue at this time.

**Comment by jinglouMSFT** [comment]
Glad it worked for you.
