### ISSUE TITLE
The translation of 'Remove from Quick Access' is not exact

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2223]
**Storage Explorer Version:** 1.11.0
**Build:** [20191106.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3218228)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** Chinese(zh-CN)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Chinese (simplified)' -> Restart Storage Explorer.
3. Add one item to Quick Access.
4. Check the localized 'Remove from Quick Access' for the QA item.

**Expect Experience:**
Display '从快速访问中**移除**'.

**Actual Experience:**
Display '从快速访问中**删除**'.
![image](https://user-images.githubusercontent.com/41351993/68286979-f0ade000-00bc-11ea-9d50-d7fb5905795e.png)

**More Info:**
This issue doesn't reproduce in zh-TW.

**Comment by lukaschal** [comment]
On review.

Rid: 0;"String Table"\0;"Strings"\0;"TreeView.QuickAccess.Remove"

**Comment by lukaschal** [comment]
Linguistic answer:

Current target "从快速访问中删除" is correct.

**Comment by MRayermannMSFT** [comment]
We think either are fine. We're ok with leaving this as is for now.
