### ISSUE TITLE
There are strings haven't been translated in Services page on Settings panel

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2224]
**Storage Explorer Version:** 1.11.0
**Build:** [20191106.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3218228)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** Chinese(zh-CN)/ Chinese(zh-TW)
**Architecture:** ia32/x64
**Regression From:** Previous release(1.11.0)

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open Settings panel -> Regional Settings -> Select Chinese(traditional) as application language -> Restart Storage Explorer.
3. Open Settings panel -> Services.
4. Check the strings on this page.

**Expect Experience:**
All strings are localized.

**Actual Experience:**
There are strings are not localized.
![image](https://user-images.githubusercontent.com/54055206/68285870-06baa100-00bb-11ea-9c4d-652d6981b949.png)

**Comment by lukaschal** [comment]
Localized at 11/5/2019.

File: loc\en\src\Standalone\resources\Shell.json
ID: 0; "DescriptionEnableADLSGen1"
SRC: If unchecked, then all ADLS Gen1 related features will be hidden. The tree view must be refreshed for this setting to be applied.
TGT: 如果禁用，则将隐藏所有 ADLS Gen1 相关功能。若要应用此设置，必须刷新树视图。

**Comment by v-xianya** [comment]
This issue has been fixed on build master/20191123.2. So we close it.
