### ISSUE TITLE
The notification message is not localized on 'Manage Access Policies' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2225]
**Storage Explorer Version:** 1.11.0
**Build:** [20191106.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3218228)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** Chinese(zh-CN)/ Chinese(zh-TW)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Chinese (simplified)' -> Restart Storage Explorer.
3. Expand one storage account -> Blob Containers.
4. Select one blob container and open its context menu -> Click 'Manage Access Policies...'.
5. Click 'Add' -> Delete one date value in Start time box then hover over on it.
6. Observe the notification message.

**Expect Experience:**
The notification message is localized.

**Actual Experience:**
The notification message is not localized.
![image](https://user-images.githubusercontent.com/41351993/68287523-d1638280-00bd-11ea-9c89-bcf5a112e2b2.png)

**Comment by lukaschal** [comment]
Not exposed to localization.

https://devdiv.visualstudio.com/Private/_git/typescriptchromium?_a=contents&path=%2Fcontent%2Fapp%2Fstrings%2Fcontent_strings.grd&version=GBmaster

**Comment by lukaschal** [comment]
@JasonYeMSFT

**Comment by MRayermannMSFT** [comment]
Correct, this is not exposed to us unfortunately. We need to investigate letting Electron know we're in a different locale...

**Comment by v-xianya** [comment]
[More Info:](url)
This isssue also reproduces for Shared Access Signature dialog & Undelete blobs by date dialog.
![image](https://user-images.githubusercontent.com/41351993/75519227-b8505a00-5a3d-11ea-9254-b03698da3f10.png)
![image](https://user-images.githubusercontent.com/41351993/75519234-bc7c7780-5a3d-11ea-9185-660bb52608ee.png)

**Comment by v-xianya** [comment]
1. Closed this bug due to the bug: [3014](https://github.com/microsoft/AzureStorageExplorer/issues/3014)
2. Verified on build 20200924.2. The notification message is localized in 'Shared Access Signature' dialog.
![image](https://user-images.githubusercontent.com/41351993/94094347-d5bd9900-fe51-11ea-96ef-4de060a1d55a.png)

3. Open a new bug: [3617](https://github.com/microsoft/AzureStorageExplorer/issues/3617) for the untranslated notification message in 'Undelete Blobs by Date' dialog.
