### ISSUE TITLE
It does not meet the usage habits when there is no any response with clicking the enter button.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/AzureStorageExplorer#2226]
Storage Explorer Version: 1.11.0
Build Number: 20191102.1
Platform/OS: Linux
Language: Chinese(zh-CN)/ Chinese(zh-TW)

Steps to reproduce:
      1. Open ASE and sign in
      2. Right click "Data Lake Storage Gen1(Preview)" then select "Connect to Data Lake Storage Gen1.."  
![image](https://user-images.githubusercontent.com/35950097/68290156-6c5e5b80-00c2-11ea-8ffc-d7cd25df4aa8.png)
      3. Input "adl://xxx" in the input box.  
![image](https://user-images.githubusercontent.com/35950097/68290343-c19a6d00-00c2-11ea-9fb9-4124b948235d.png)
      4 Click the keyboard "Enter". 

Result:
     There is no response.
![image](https://user-images.githubusercontent.com/35950097/68290496-00302780-00c3-11ea-9d31-b443ba7e961b.png)

Expect Experience:
      The dialog should be closed or there are some response.

**Comment by jinglouMSFT** [comment]
Corner case.  Won't fix.
