### ISSUE TITLE
It displays error message only during the first operation.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/AzureStorageExplorer#2227]
Storage Explorer Version: 1.11.0
Build Number: 20191102.1
Platform/OS: Linux
Language: Chinese(zh-CN)/ Chinese(zh-TW)

Repro Steps:
1. Open ASE and sign in
2. Right click "Data Lake Storage Gen1(Preview)" then select "Connect to Data Lake Storage Gen1.."
![image](https://user-images.githubusercontent.com/35950097/68290903-b8f66680-00c3-11ea-8967-1fbdaf01b517.png)
3. Input "adl://xxx" in the input box then click OK button(Please input the wrong info).
![image](https://user-images.githubusercontent.com/35950097/68291002-e3e0ba80-00c3-11ea-819b-6daad4feae1f.png)
Result:
Get error message.
![image](https://user-images.githubusercontent.com/35950097/68291119-20141b00-00c4-11ea-9523-dab912870b6e.png)
4. Click OK button to close the window.
5. Repeat step 2 and step 3.
Result:
The access Denied window did not appear. There is no any response.

Expectation:
The Access Denied window should appear when input wrong ADL URI every time rather than in the first time.

**Comment by jinglouMSFT** [comment]
Since no active work is done on ADLS Gen1 anymore, and this is a corner case that wouldn't impact normal usage, I am going to won't fix the issue.
