### ISSUE TITLE
"Use system language" is not translated

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#2228]
**Storage Explorer Version**: 1.11.0
**Build Number**: 20191105.2
**Platform/OS**: All
**Architecture**: All
**Regression**: 1.11.0 (dev)

## Bug Description ##

"Use system language" in **Settings** > **Application** > **Regional Settings** is not translated. While the specific languages should remain untranslated (the same strings regardless of current language setting), the system language option should be.

## Additional Context ##

File: Shell.json
ID: LabelLocaleUseSystemLanguage

Note that there is no "_LabelLocalUseSystemLanguage.comment", so I'm not sure why the translators "untranslated" this string.

![image](https://user-images.githubusercontent.com/3473026/68318314-70ae5880-0071-11ea-92be-6eb0438a2a3a.png)

**Comment by craxal** [comment]
@weeteckt Do you have an update on this? Has this been fixed?

**Comment by weeteckt** [comment]
@janbaltus - I believe this is fixed but could you confirm once again?

**Comment by janbaltus** [comment]
Untranslated string  Use system language fixed in Storage Explorer repo.

**Comment by v-xianya** [comment]
Verified this issue on build master/20191123.2. It has been fixed.
