### ISSUE TITLE
Certificate error

### ISSUE THREAD

**Issue by haslak** [microsoft/AzureStorageExplorer#2230]
**Storage Explorer Version**: 1.11.0
**Build Number**: 20191105.2
**Platform/OS**: Windows 10
**Architecture**:  x64
**Regression From**:  No

## Bug Description ##
Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: 5e016b8a-23ed-43f5-a521-168c5e91bb13, Error: {
  "name": "Error",
  "message": "unable to verify the first certificate",
  "stack": "Error: unable to verify the first certificate\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at TLSSocket.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at TLSSocket.emit (events.js:182:13)\n    at TLSSocket._finishInit (_tls_wrap.js:631:8)",
  "code": "UNABLE_TO_VERIFY_LEAF_SIGNATURE"
}

## Steps to Reproduce ##
Any time I add my account, I get a message that subscriptions could not be loaded and when I click on More Information it provides me with the above error.

Also if I add a storage account by other means (storage account name and key, etc.), it connects to the storage account but when I drill down into the say Blob Containers it gives me the similar error - Unable to retrieve child resources.  Details: Unable to verify the first certificate.

**Comment by MRayermannMSFT** [comment]
Hi @haslak , thanks for opening an issue. We have a section in our troubleshooting guide for dealing with these types of issues. Long story short, we recommend reaching out to your network admin to help figure out what software is injecting a self signed cert into your network requests. Once you find the cert, you can let Storage Explorer know about it so it knows to trust it. And if all else fails, there is a flag you can use to suppress this error. See more here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C1804#error-self-signed-certificate-in-certificate-chain-and-similar-errors

**Comment by haslak** [comment]
Matt, Thanks for the documentation.  I will work on figuring out the certificates needed.  In the meantime I was able to open Storage Explorer with the --ignore-certificate-errors setting.  This allowed me to see and work with everything in Azure.
