### ISSUE TITLE
ChinaRegionAccount Copy issue

### ISSUE THREAD

**Issue by msdz** [microsoft/AzureStorageExplorer#2231]
**Storage Explorer Version**: V 1.11.0，Azcopy 10.3.1
**Build Number**: 20191105.2
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  Old with Azcopy disable

## Bug Description ##
using china region account copy and paste to other folder will using the global endpoint

## Steps to Reproduce ##
copy the file
paste to another folder

## Expected Experience ##
should using the same endpoint

## Additional Context ##
Sample command:
./azcopy.exe copy "https://dotnetconf.blob.core.chinacloudapi.cn/design/Media/%E5%88%98%E8%85%BE%E9%A3%9E-ASP.NET%20Core%E5%9F%BA%E4%BA%8EK8S%E7%9A%84%E5%BE%AE%E6%9C%8D%E5%8A%A1%E7%94%B5%E5%95%86%E6%A1%88%E4%BE%8B%E5%AE%9E%E8%B7%B5.pptx?sv=2018-03-28&ss=b&srt=co&sp=rl&se=2019-11-14T03%3A24%3A45Z&sig=0DpwleMvEkxxxxxxxxxxxZxmzdpArSBw%3D" "https://dotnetconf.blob.core.windows.net/design/DotnetSpeaker/%E5%88%98%E8%85%BE%E9%A3%9E-ASP.NET%20Core%E5%9F%BA%E4%BA%8EK8S%E7%9A%84%E5%BE%AE%E6%9C%8D%E5%8A%A1%E7%94%B5%E5%95%86%E6%A1%88%E4%BE%8B%E5%AE%9E%E8%B7%B5.pptx?se=2019-12-07T03%3A24%3A54Z&sp=rwl&sv=2018-03-28&sr=c&sig=ljWZQ8hrnxxxxxxxxxivRQmcGk5E%3D" --overwrite=prompt --recursive --s2s-preserve-access-tier=false;

**Comment by JasonYeMSFT** [comment]
Are you working with storage blob or ADLS Gen2?

Which type of authentication are you using for the destination blob container (sign in, key attachment, SAS attachment, Azure AD attachment?

Does this scenario work with AzCopy in 1.10.1? I have signed into a China Region account and cannot reproduce this bug.

**Comment by JasonYeMSFT** [comment]
Possibly related to this issue https://github.com/microsoft/AzureStorageExplorer/issues/2237. @msdz, are you using Key attached accounts?

**Comment by MRayermannMSFT** [comment]
We strongly believe that this was the same issue as #2237. @msdz , feel free to either reach out to us internally or via a new github issue if you encounter any new issues. Version 1.11.1 will contain a fix for the bug we believe you are encountering.
