### ISSUE TITLE
Capitalize the first letter for each string appended to the activity logs

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2233]
**Storage Explorer Version:** 1.11.0
**Build:** [20191106.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3218228)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account.
2. Select one blob container which contains multi blobs.
3. Copy and paste the blob container to another storage account.
4. Check the strings appended to the activity logs.

**Expect Experience:**
The first letter is capitalized for each string.(Like: **Cancel All    Auto-Resolve Behavior...** )

**Actual Experience:**
Not all initials for strings are capitalized.
![image](https://user-images.githubusercontent.com/41351993/68366534-8f464980-016e-11ea-9a60-9d52d4b966b0.png)

**More Info:**
1. Update 'Retry all' to 'Retry All'.
![image](https://user-images.githubusercontent.com/41351993/68366900-63779380-016f-11ea-9066-bebd8a9245fe.png)

**Comment by MRayermannMSFT** [comment]
By design. These are cased with sentence casing

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT 
We noticed that shows 'Cancel All' next to some activity logs. Like below:

Could you help to take a look on this issue?😊
![image](https://user-images.githubusercontent.com/41351993/69229904-30ec7400-0b3b-11ea-9dde-410804c3d9cd.png)
