### ISSUE TITLE
Display two same file shares after pasting one file share 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2234]
**Storage Explorer Version:** 1.11.0
**Build:** [20191106.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3218228)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> File Shares.
2. Select one file share and copy it.
3. Select another storage account -> Expand the storage account node -> **Refresh the selected storage account**.
4. Right click the File Shares node  -> Click 'Paste File Share'.
5. Check the result.

**Expect Experience:**
1. Paste successfully.
2. The File Share node is expanded.
3. Display the copied file share in the tree view.

**Actual Experience:**
1. Paste successfully.
2. The File Share node is expanded.
3. Display **two** same copied file share in the tree view.
![image](https://user-images.githubusercontent.com/41351993/68370390-59f22980-0177-11ea-94ba-5a70f7e4158a.png)

**More Info:**
1. The copied file share shows well after manually refresh.
2. This issue doesn't reproduce for one blob container/ table.

**Comment by MRayermannMSFT** [comment]
Won't fix. Refreshing fixes the issue.
