### ISSUE TITLE
'Tables' node is not expanded after pasting one table to it

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2236]
**Storage Explorer Version:** 1.11.0
**Build:** [20191106.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3218228)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Tables -> Select one table and copy it.
2. Paste the copied table to another storage account. (Make sure the destination 'Tables' node is collapsed).
3. Check the result.

**Expect Experience:**
1. Paste successfully.
2. The destination'Tables' node is expanded.
3. The copied table is selected.

**Actual Experience:**
1. Paste successfully.
2. The destination 'Tables' node is not expanded.

**More Info:**
This issue doesn't reproduce for one blob container/ file share.

**Comment by MRayermannMSFT** [comment]
Won't fix. Refreshing/expanding manually works fine.
