### ISSUE TITLE
Feature request: Limit upload bandwidth

### ISSUE THREAD

**Issue by dichternebel** [microsoft/AzureStorageExplorer#2247]
Dear PO of AzureStorageExplorer,

I'd like to limit the upload bandwidth within the AzureStorageExplorer settings in order to be able to keep on working from my local network while uploading large files to azure.

Thanks in advance
Sascha

**Comment by JasonYeMSFT** [comment]
The bandwidth limitation configuration is available in 1.11.0 with AzCopy. You can find it in the Settings panel under the `Transfers` tab.

**Comment by MRayermannMSFT** [comment]
As @JasonYeMSFT says, you can configure this now via settings:
![image](https://user-images.githubusercontent.com/21112697/68612639-d9cb0d00-0471-11ea-9ae1-f95929753df2.png)

Please open a new issue if you continue to run into problems after doing this. 😄

**Comment by dichternebel** [comment]
Awesome! Thanks a lot. I was still on 1.10.1 and now after upgrading to 1.11.0 I can confirm that this feature works as expected. You rock!
