### ISSUE TITLE
The service items under Quick Access are not broken when MSAL is enabled

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2248]
**Storage Explorer Version:** 1.11.0
**Build:** [20191110.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3231473)
**Branch**: hotfix/1.11.1
**Platform/OS:** Windows 10
**Architecture:** ia32
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer -> Add storage accounts and services to Quick Access.
2. Open Settings panel -> Application -> Sign-in -> Enable MSAL.
3. Restart Storage Explorer -> Observe the Quick Access items. 

**Expect Experience:**
Quick Access all items are broken.

**Actual Experience:**
The services item under Quick Access are not broken.
![image](https://user-images.githubusercontent.com/54055206/68579201-888d3e80-04ae-11ea-8a45-cbd9610ce2c1.png)

**Comment by MRayermannMSFT** [comment]
@v-limu , depending on how we are authenticating to get access to the resource, it may or may not be broken. The resource will only be broken if it was being authenticated with only subscription/RBAC. If you added to quick access from something that say had key access, then it won't be broken. Can you examine the properties for the non broken items and check if they have key properties, or if their connection string properties have keys?

**Comment by v-limu** [comment]
Hi @MRayermannMSFT Thanks for your help. 

1. The items that they have key access under Quick Access shows well when removing the account **(MSAL is disabled)**. In expect that the items shows broken. 
2. So the Quick Access item doesn't show broken is it only related to the key access?

**Comment by MRayermannMSFT** [comment]
Correct.

**Comment by MRayermannMSFT** [comment]
Sounds like limu understands now. Closing.
