### ISSUE TITLE
List all subscriptions after restarting Storage Explorer with MSAL option changed

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2249]
**Storage Explorer Version:** 1.11.0
**Build:** [20191110.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3231473)
**Branch**: hotfix/1.11.1
**Platform/OS:** Windows 10
**Architecture:** ia32
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer -> Make sure there is one account signed in at least.
2. Select one or more subscriptions.
3. Open Settings -> Application -> Sign-in -> Enable MSAL.
4. Restart Storage Explorer.
5. Check the results.

**Expect Experience:**
List the subscriptions selected before.

**Actual Experience:**
List all subscriptions.

**More Info:**
This issue also reproduces after changing MSAL from enabled to disabled to restart Storage Explorer.

**Comment by MRayermannMSFT** [comment]
By design. The selected subscription setting is specific to not only the account, but the auth mode (MSAL vs non-MSAL).

**Comment by binaryPUNCH** [comment]
@MRayermannMSFT is there a way to install Azure Storage Explorer with MSAL enabled from the start?
