### ISSUE TITLE
Not remind to sign-in after enabling MSAL

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2250]
**Storage Explorer Version:** 1.11.0
**Build:** [20191110.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3231473)
**Branch**: hotfix/1.11.1
**Platform/OS:** Windows 10
**Architecture:** ia32
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer -> Settings -> Application -> Sign-in -> Enable MSAL.
2. Restart Storage Explorer.
3. Check the results.

**Expect Experience:**
1. Remind to sign-in.
2. The 'Connect' dialog pops up.

**Actual Experience:**
Not remind to sign-in.

**Comment by MRayermannMSFT** [comment]
@v-xianya , did you have any attached resources?

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT There no attached resource exists.

**Comment by MRayermannMSFT** [comment]
Because that's our policy on when to pop up the connect dialog. 😋

**Comment by MRayermannMSFT** [comment]
Talked to xianya on Teams regarding this issue. Sounds like everything is working as expected, but the description for the MSAL setting has lead to confusion. Will propose a new description during standup.
