### ISSUE TITLE
Unable to create account-level SAS for HNS-enabled accounts

### ISSUE THREAD

**Issue by zezha-msft** [microsoft/AzureStorageExplorer#2252]
Version: 1.11.0
AzCopy Version: 10.3.1

Platform: macOS
Architecture: x64 
Build Number: 20191105.2 
Commit: cd5448739 
Support ID: b1969f27-6377-645f-2a35-b110adb2e2e7 

**Regression From**:  1.10

## Bug Description ##

![image](https://user-images.githubusercontent.com/26559128/68633869-5678de00-04a8-11ea-8d0d-48249226dd1b.png)
The `Get Shared Access Signature` button is grayed out.

## Steps to Reproduce ##

1. Right-click on an HNS-enabled account

## Expected Experience ##

1. The button should work as before.

## Actual Experience ##

1. The button is grayed out.

**Comment by v-xianya** [comment]
Hi @zezha-msft  
SAS feature doesn't support ADLS Gen2 accounts for now.

**Comment by zezha-msft** [comment]
Hi @v-xianya, I've confirmed with @MRayermannMSFT that it should be fixed.

**Comment by jinglouMSFT** [comment]
The missing of the SAS generation context menu at the container level for ADLS gen2 was by-design in 1.11.0.  This is because we can't support attaching using SAS URI for ADLS Gen2 yet in SE.  We will support this sometime down the road however.

**Comment by zezha-msft** [comment]
Hi @jinglouMSFT, how about the account-level SAS? Was it also intentionally disabled?

**Comment by jinglouMSFT** [comment]
@zezha-msft Yes. it is intentionally disabled, not a very good design tho.  A better design would be to actually remove it from the context menu. 
We can't support attach as we have no way to tell the attached is HNS enabled or not.  Until ADLS gen2 supports it, we probably will not enable that menu.

**Comment by JasonYeMSFT** [comment]
Move to 1.17.0 since we haven't figured out how to support attaching Gen2 accounts via SAS.

**Comment by JasonYeMSFT** [comment]
https://github.com/Azure/azure-sdk-for-js/issues/12530 Tracking the SDK on the necessary account info property.

**Comment by JasonYeMSFT** [comment]
Due to incompleteness of service level sas support, we will defer shipping this until 1.18.0.
