### ISSUE TITLE
Polish the UI/UX experience for picking AzCopy network concurrency of AUTO and other values

### ISSUE THREAD

**Issue by zezha-msft** [microsoft/AzureStorageExplorer#2253]
Version: 1.11.0
AzCopy Version: 10.3.1

Platform: macOS
Architecture: x64
Build Number: 20191105.2
Commit: cd5448739
Support ID: b1969f27-6377-645f-2a35-b110adb2e2e7

Regression From: 1.10

## Bug Description ##

![image](https://user-images.githubusercontent.com/26559128/68634266-b4f28c00-04a9-11ea-9b5f-7cc582c8c9df.png)
The settings is shown as an integer field, so it's not possible to type in "AUTO".

## Steps to Reproduce ##

1. Open the Settings, and go to Transfers tab.

## Expected Experience ##

1. Maybe there should be a radio button? So that the user can choose to perform auto-seeking, instead of calculation based on CPU or explicit override.

## Actual Experience ##

1. Only override can be provided.

**Comment by jinglouMSFT** [comment]
"If left blank, this number is determined based on the number of logical cores on the machine" which is meant to be the "Auto" experience.  If this is confusing, we can look into other options.

**Comment by JohnRusk** [comment]
There's a difference between "AUTO" and leaving it blank. AUTO means dynamically tune it. Whereas blank means "use the number of logical cores". There are known cases where blank is totally the wrong choice (typically big machines on small networks) , so customers need away to choose AUTO. 

Maybe one day we (the AzCopy team) will make something like AUTO the default, but that's at least one or two releases away, if not more.

**Comment by jinglouMSFT** [comment]
Good to know.  Thanks for the info.

**Comment by MRayermannMSFT** [comment]
I merged an initial implementation of this into the 1.11.1 hotfix. You can simply enter AUTO into the textbox. Later we will do a more polished UI/UX experience for this settings.

**Comment by JohnRusk** [comment]
Thanks. That's enough to unblock the  "big machine; small network" customers who need this feature.

**Comment by MRayermannMSFT** [comment]
This has been done for 1.14.0:
<img width="458" alt="image" src="https://user-images.githubusercontent.com/21112697/81587754-55980a80-936c-11ea-8f73-548f735beccd.png">
Note: I'm going to add a unit to that label.
