### ISSUE TITLE
Add a setting to specify file editor

### ISSUE THREAD

**Issue by okazakov** [microsoft/AzureStorageExplorer#2254]
Hi,

Currently, Notepad.exe is used to open a file for editing.

It would be great to be able to specify an alternative text editor instead.

Is it possible to add a setting into Edit -> Settings dialog to specify (as a path to executable) an alternative editor?

Thank you.
Oleg

**Comment by jinglouMSFT** [comment]
At your system level, did you associate .txt with Notepad?  Storage Explorer honors the system setting.

**Comment by MRayermannMSFT** [comment]
Yes, this is based on your OS settings.
