### ISSUE TITLE
The Rename/Clone button is enabled when starting to input characters on Rename/Clone dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2258]
**Storage Explorer Version:** 1.11.0
**Build:** [20191112.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3234284)
**Branch:** hotfix/1.11.1
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one Non-ADLS Gen2 storage account -> Blob Containers.
2. Create a new blob container -> Open its Rename dialog -> Start to input characters.
3. Check the 'Rename' button on the dialog.

**Expect Experience:**
The Rename button is enabled when the entered characters length is valid.

**Actual Experience:**
The Rename button is enabled when starting to input characters.
![image](https://user-images.githubusercontent.com/41351993/68746023-a5eb1580-0632-11ea-8129-300c2ae57e1b.png)

**More Info:**
This issue also reproduces for one file share/ table.

**Comment by MRayermannMSFT** [comment]
Fix merged into master.

**Comment by v-xianya** [comment]
This issue reproduces on build/20200609.1. So we re-open it.

**Comment by MRayermannMSFT** [comment]
@v-xianya that build had a bad cloud explorer commit, can you verify tonight? I'll comment with a well known build number before I log off today.

**Comment by MRayermannMSFT** [comment]
I just revalidated on build 20200610.2

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT Thank you for the sharing. This issue is fixed on build 20200610.2.
