### ISSUE TITLE
An extra property displays in Properties Panel for a premium account which is added to Quick Access 

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#226]
**Storage Explorer Version**: 1.1.0

**Platform**: All

**Architecture**: ia32/x64

**Build Number**: 20180529.3

**Commit**: 1b431f90

**Regression From**: Not a regression

#### Steps to Reproduce: ####

1. Launch Storage Explorer and expand Storage Account.
2. Choose one premium account then add it to Quick Access.
3. Check the properties for the added account to Quick Access.

#### Expected Experience: ####
The property of 'Default Access Tier' doesn't display in Properties Panel..

#### Actual Experience: ####
The property of 'Default Access Tier' displays in Properties Panel.
![properties](https://user-images.githubusercontent.com/34729022/40714706-eae5b110-63f2-11e8-9b15-c18996c18b7a.png)

**Comment by craxal** [comment]
This is by design. We are now tracking access tiers for storage accounts.
