### ISSUE TITLE
Manually removing values from settings file does not work

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#2261]
1. Change theme to dark
2. Go to settings file, delete the entry for theme
3. Observe that Storage Explorer goes back to light theme
4. Open settings

Expected:
1. Settings is light themed
2. The drop down for theme is light

Actual:
1. Settings is dark themed
2. The drop down for theme is dark

![image](https://user-images.githubusercontent.com/21112697/68879789-dd070880-06be-11ea-9a4f-ec379a3afa05.png)

Note: things are fixed once the app is restarted. But for less visual settings, this can lead to much worse unexpected behavior.

Cause of the bug: ConfigurationSet.setAll iterates through the values in what you're setting the set to, and uses those values to update the values in the set. What should be done instead (imo) is there should be a loop over the values in the set, if if they are in the new values, then update, if not, then set to default.

**Comment by craxal** [comment]
What if, we only want to set two or three values in code? Then that would wipe out all the existing settings! What we really need is a new function that basically swaps in a new configuration set, separate from the function that sets values in bulk.

**Comment by MRayermannMSFT** [comment]
I'm changing my mind. We don't currently say that manually editing the file is a well supported scenario.
