### ISSUE TITLE
Can't add one new Azure account when enabling MSAL on Linux

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2265]
**Storage Explorer Version:** 1.11.0
**Build:** [20191115.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3247612)
**Branch:** hotfix/1.11.1
**Platform/OS:** Linux Ubuntu 18.04
**Architecture:** x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer -> Sign in.
2. Open Settings panel -> Application -> Sign-in -> Enable MSAL -> Restart Storage Explorer.
3. Make sure an Azure account already exists in **sign-in browser** -> Then add another Azure account to sign in.
4. Check the result.

**Expect Experience:**
Pop up a password box.

**Actual Experience:**
   1. No password box pops up.
   2.  Directly complete authenticate.
![image](https://user-images.githubusercontent.com/54055206/68938073-90175500-07d8-11ea-8b28-5862d7ae09ce.png)
   3. The Azure account that already exists in sign-in browser is added to Storage Explorer.

**More Info:**
This issue also reproduces on 'use device code flow sign-in'.

**Comment by MRayermannMSFT** [comment]
@v-limu , can you explain to me more about what you saw that was unexpected?

If you have already signed into your browser, then you won't need to enter your password again. Additionally, if you'd like to sign into an account not already signed into your browser, then you can choose "User another account":
![image](https://user-images.githubusercontent.com/21112697/68963407-b531a680-078b-11ea-91ec-d7d5f7e12f40.png)

**Comment by v-limu** [comment]
Hi @MRayermannMSFT 

The unexpected result occurs when **using another account to sign into browser.** 

**Steps to reproduce:**
1. Make sure an Azure account already exists in sign-in browser .
2. Use another account -> Type a new Azure account name.
3. Check the result.

**Expect Experience:**
Authenticate for the new account.

**Actual Experience:**
No authentication for the new account.

**Comment by MRayermannMSFT** [comment]
@v-limu , are both accounts MSAs? Or in other words, are both accounts personal accounts or are they work accounts?

**Comment by v-limu** [comment]
This issue doesn't reproduce on Linux using build [20191119.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3255785). So we close it.
