### ISSUE TITLE
Directories can be dragged to one file share snapshot editor

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#227]
**Storage Explorer Version**: 1.1.0
**Platform**: All
**Architecture**: ia32/x64
**Build Number**: 20180529.3
**Commit**: 1b431f90
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Launch Storage Explorer and expand Storage Account. 
2. Open one file share and create a snapshot for it.
3. Switch the view to the created snapshot.
3. Drag directories to it.

#### Expected Experience: ####
The directory can't be dragged to the snapshot editor.

#### Actual Experience: ####
The directory can be dragged to the snapshot editor.

#### More info: ####
1. This issue doesn't reproduce when dragging files to the snapshot editor.
2. The uploaded directory doesn't display on the snapshot editor after refreshing.

**Comment by craxal** [comment]
@v-xuanzh Please provide more info. This sounds like expected behavior. Creating a snapshot doesn't change the state of the share or the view. It just creates a checkpoint of sorts you can return to later. The share is still just as editable as before.

**Comment by v-xuanzh** [comment]
Hi Craig,
For this issue, The below notification pops up when dragging files to one snapshot editor.
![notification](https://user-images.githubusercontent.com/34729022/40763452-7d18a5be-6494-11e8-8cef-eacf113f6e22.png)
But the dragged directory will display well in the snapshot editor and no notification pops up like the post screenshot.
![directory](https://user-images.githubusercontent.com/34729022/40763615-ef558fa2-6494-11e8-8232-69a12bfd8f31.png)
In addition, the dragged directory displays in the Current file share after backing to Current from the comb box.

**Comment by craxal** [comment]
OK, so you were just missing a repro step. You didn't say that you switched to a snapshot view.

What happens when you refresh?

**Comment by v-xuanzh** [comment]
The uploaded directory doesn't display in the snapshot view but displays in Current file share editor after refreshing.

**Comment by MRayermannMSFT** [comment]
Similar to #411

**Comment by v-xianya** [comment]
Verified this issue on the latest build 20190614.7. It still reproduces.

**Comment by v-xianya** [comment]
This issue is fixed on build master [20200509.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3715211&view=results). 
The info bar prompts when trying to drag directories to file share snapshots view.
![image](https://user-images.githubusercontent.com/41351993/81537431-bf7dd780-939f-11ea-85de-b90064950a86.png)

So we close it.
