### ISSUE TITLE
No related bug is appended to the first fix on Release Notes in Fixes section

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2270]
**Storage Explorer Version:** 1.11.1
**Build:** [20191116.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3250060)
**Branch:** hotfix/1.11.1
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer -> Help -> View Release Notes.
2. Check the first fix in Fixes section.

**Expect Experience:**
A related bug shows.

**Actual Experience:**
No related bug shows.
![image](https://user-images.githubusercontent.com/41351993/69040513-e1b61e80-0a28-11ea-9794-0fe078e5247e.png)

**Comment by MRayermannMSFT** [comment]
Didn't have a good related bug to use for that bug. Won't fix.
