### ISSUE TITLE
Navigate to an incorrect web page after clicking the link 'here' in Known Issues section

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2271]
**Storage Explorer Version:** 1.11.1
**Build:** [20191116.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3250060)
**Branch:** hotfix/1.11.1
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer -> Help -> View Release Notes.
2. Go to **Known Issues** section -> Click the link '[here](https://www.microsoft.com/en-us/?ref=aka)'.
3. Check the result.

**Expect Experience:**
Navigate to a correct web page.

**Actual Experience:**
Navigate to an incorrect web page.
![image](https://user-images.githubusercontent.com/41351993/69040740-440f1f00-0a29-11ea-8616-d665809e51ba.png)

**Comment by MRayermannMSFT** [comment]
Need to update my fwd link once I get a final answer from Stephen.

**Comment by MRayermannMSFT** [comment]
Checked into hotfix branch. The page it links to isn't quite right yet, but their team is working on it. Anyway, closing. :)
