### ISSUE TITLE
A problem caused Storage Explorer to restart with GPU acceleration disabled [Windows]

### ISSUE THREAD

**Issue by ilaizi** [microsoft/AzureStorageExplorer#2272]
**Storage Explorer Version**: 1.4.0
**Build Number**: 20180803.3
**Platform/OS**: Windows
**Architecture**: ia32

## Bug Description ##
Every time I leave the storage explorer open for too long (over night), it restarts with the following error: "A problem caused Storage Explorer to restart with GPU acceleration disabled"

![image](https://user-images.githubusercontent.com/34011385/69041587-6d638700-09f8-11ea-96b6-fd1046357b72.png)

**Comment by MRayermannMSFT** [comment]
Can you please upgrade to our latest update and see if the problem persists?

**Comment by ilaizi** [comment]
> Can you please upgrade to our latest update and see if the problem persists?

Sure, I'll give it a try

**Comment by JasonYeMSFT** [comment]
@ilaizi, we have produced a private build on a potential fix for the GPU crash bug. It also allows you to save the option of disabling gpu so that it won't crash at some point and restart.
Please see #2277 for the bits. If you have any questions, please comment under that issue.

**Comment by JasonYeMSFT** [comment]
Unfortunately we haven't figured out why the GPU process may crash after running Storage Explorer. Disabling GPU is only a work around for you. If you are fine with the work around, we are going to close the issue.

**Comment by MRayermannMSFT** [comment]
Closing this. Please refer to #2277 for all discussion regarding GPU issues.
