### ISSUE TITLE
A strange symbol shows on Retry Transfers dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2273]
**Storage Explorer Version:** 1.11.1
**Build:** [20191116.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3250060)
**Branch:** hotfix/1.11.1
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Create a new blob container -> Upload one file.
3. Upload the same file -> Select 'Do not upload' -> Apply.
4. Click 'Retry Transfers...' in Activities panel -> Check the source path on Retry Transfers dialog.

**Expect Experience:**
No strange symbol shows.

**Actual Experience:**
A strange symbol shows.

![image](https://user-images.githubusercontent.com/41351993/69043144-73c02600-0a2d-11ea-96a6-903face3f0b1.png)

**Comment by MRayermannMSFT** [comment]
Jason merged a fix for this into master.
