### ISSUE TITLE
Update 'Prompt for overwrite' to 'Prompt for Overwrite' on Retry Transfers dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2274]
**Storage Explorer Version:** 1.11.1
**Build:** [20191116.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3250060)
**Branch:** hotfix/1.11.1
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Create a new blob container -> Upload one file.
3. Upload the same file -> Select 'Do not upload' -> Apply.
4. Click 'Retry Transfers...' in Activities panel.
5. Check the 'Overwrite' dropdown list.

**Expect Experience:**
Show 'Prompt for Overwrite' on the dropdown list.

**Actual Experience:**
Show 'Prompt for overwrite' on the dropdown list.
![image](https://user-images.githubusercontent.com/41351993/69044767-7a03d180-0a30-11ea-96b6-962cc8d0efd9.png)

**Comment by MRayermannMSFT** [comment]
All of these dropdown strings should **not** be using title casing now
