### ISSUE TITLE
'Set Public Access Level…' displays when pasting one non-premium blob container to a premium account 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2275]
**Storage Explorer Version:** 1.11.1
**Build:** [20191116.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3250060)
**Branch:** hotfix/1.11.1
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Expand one non-Premium storage account -> copy one blob container.
3. Paste it to a **Premium** storage account.
4. Check its context menu.

**Expect Experience:**
No 'Set Public Access Level...' displays on the context menu.

**Actual Experience:**
'Set Public Access Level...' displays on the context menu.
![image](https://user-images.githubusercontent.com/54055206/69043322-d0bbdc00-0a2d-11ea-9098-f757b675ca10.png)

**More Info:**

1. This issue also reproduces for create a new premium blob container. Related to: [154](https://github.com/microsoft/AzureStorageExplorer/issues/154).
2. This issue doesn't reproduce after refreshing.

**Comment by v-xianya** [comment]
This issue is fixed on build 20200529.3. Close it.
