### ISSUE TITLE
Add 'Blob Containers' to the first sentence on Release Notes New section

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2280]
**Storage Explorer Version:** 1.11.1
**Build:** [20191119.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3255785&view=results)
**Branch:** hotfix/1.11.1
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer -> Help -> View Release Notes.
2. Check the first sentence on New section.

**Expect Experience:**
'Blob Containers' in added to the first sentence.

**Actual Experience:**
Not mentioned 'Blob Containers' in first sentence.
![image](https://user-images.githubusercontent.com/41351993/69134795-08d92280-0af3-11ea-9123-ba928b599c48.png)

**Comment by MRayermannMSFT** [comment]
We're happy with the release notes as is for now. But thanks for being vigilant. Won't fix.
