### ISSUE TITLE
Add 'Rename' to AzCopy Blob Containers part on New section

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2281]
**Storage Explorer Version:** 1.11.1
**Build:** [20191119.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3255785&view=results)
**Branch:** hotfix/1.11.1
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer -> Help -> View Release Notes.
2. Check the Blob Containers part in the first part of New section.

**Expect Experience:**
'Rename' is mentioned.

**Actual Experience:**
'Rename' is not mentioned.
![image](https://user-images.githubusercontent.com/41351993/69136539-f90f0d80-0af5-11ea-859f-a0be6ae279c7.png)

**Comment by JasonYeMSFT** [comment]
We have decided to not explicitly mention "rename" because rename is a convenience function of copy/paste + delete.
