### ISSUE TITLE
Add 'Details...' in Activities when deleting multiple leased ADLS Gen2 blobs 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2284]
**Storage Explorer Version:** 1.11.1
**Build:** [20191119.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3255785)
**Branch:** hotfix/1.11.1
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Expand one ADLS Gen2 storage account ->Blob Containers.
3. Create a new blob container -> Upload multiple blobs to it -> Acquire lease for those blobs.
4. Select all leased blobs -> Try to delete.
5. Check the Activities.

**Expect Experience:**
'Details...' shows in Activities.
![image](https://user-images.githubusercontent.com/54055206/69138618-f2829500-0af9-11ea-91ca-bcc9fc6d68b1.png)

**Actual Experience:**
No 'Details...' shows in Activities.
![image](https://user-images.githubusercontent.com/54055206/69138606-eeef0e00-0af9-11ea-893e-0a841060cc4b.png)

**More Info:**
This issue doesn't reproduce for delete **one leased blob.**

**Comment by v-xianya** [comment]
@MRayermannMSFT 
Verified this issue on build [20200305.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3526923).
We found an action 'Retry...' is added to the multi leased blobs deletion log.
![image](https://user-images.githubusercontent.com/41351993/75963096-e16e6000-5eff-11ea-8793-e99051bd7a31.png)

However ,no intuitive error information we can see in Retry Azcopy dialog. 
I thought using 'Detail...' or 'Go to Azcopy Log File' append to activity log would be better.
![image](https://user-images.githubusercontent.com/41351993/75963156-fa771100-5eff-11ea-8b99-e29435d2eecd.png)

**Comment by JasonYeMSFT** [comment]
@v-xianya, the current AzCopy delete for ADLS Gen2 blobs don't have the detailed error message and doesn't generate log files. We need to work with AzCopy to make ADLS Gen2 delete experience the same as the blob delete experience.

**Comment by v-xianya** [comment]
@JasonYeMSFT 
Thanks for the updates.  
We noticed that there shows error detail when deleting **one** leased ADLS Gen2 blob.
![image](https://user-images.githubusercontent.com/41351993/76044482-7c654980-5f95-11ea-88e6-760e7713a8f4.png)

**Comment by MRayermannMSFT** [comment]
Bad error message in the retry dialog is related to this: https://github.com/microsoft/AzureStorageExplorer/issues/2693 

We'll use that to track that part of your feedback @v-xianya. As for there being a detailed error message when it is only 1 blob, yes that is true and that is by design. When it is only 1 blob AzCopy is successfully surfacing the error message to us.
