### ISSUE TITLE
No progress shows in Activities panel when clicking 'Table Statistics' for a large table

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2285]
**Storage Explorer Version:** 1.11.1
**Build:** [20191119.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3255785&view=results)
**Branch:** hotfix/1.11.1
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous regression(1.10.1)

**Steps to reproduce:**
1. Launch Storage Explorer -> Select the subscription 'StorageExplorer'.
2. Select and expand the storage account (stgexp) -> Tables.
3.  Select 'table200x50000' -> Click 'Table Statistics'.
4. Observe the Activities panel.

**Expect Experience:**
Show progress in Activities panel.
![image](https://user-images.githubusercontent.com/41351993/69143667-793c6f80-0b04-11ea-8322-5e5875b7a960.png)

**Actual Experience:**
No progress shows in Activities panel.
![image](https://user-images.githubusercontent.com/41351993/69143663-75a8e880-0b04-11ea-9176-92faac61f087.png)

**More Info:**
This issue doesn't reproduce in previous 1.10.1.

**Comment by JasonYeMSFT** [comment]
Merged.
