### ISSUE TITLE
Pop up ‘version 1.10.1 of Storage Explorer is available’ after installing the release version before 1.10.1 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2286]
**Storage Explorer Version:** 1.11.1
**Build:** [20191119.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3255785&view=results)
**Branch:** hotfix/1.11.1
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Install Storage Explorer with version(1.10.0).
2. A notification appears -> Check the notification.

**Expect Experience:**
Show 'version 1.11.0 of Storage Explorer is available'.

**Actual Experience:**
1. Show 'version 1.10.1 of Storage Explorer is available'.
![image](https://user-images.githubusercontent.com/41351993/69143853-f36cf400-0b04-11ea-9020-21ba844dac87.png)
2. The release build 1.11.0 is installed after clicking 'Install Now'.

**More Info:**
There is no notification appears when installing release 1.10.1.

**Comment by MRayermannMSFT** [comment]
By design. We turned off the update notification due to a platform issue.

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT 
It pops up that 1.10.1 is available, but 1.11.0 is installed after clicking Install Now. 
Could you help to clarify it? Thank you😊

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT 
1. Pop up 'Version 1.11.1 of Storage Explorer is available' after installing 1.10.1/1.11.0.
2. Pop up 'Version 1.10.1 of Storage Explorer is available' after installing 1.9.0/1.10.0.
