### ISSUE TITLE
disable-gpu runtime config

### ISSUE THREAD

**Issue by mchenx** [microsoft/AzureStorageExplorer#2287]
I'm running this app on macOS and sometimes it crashes due to gpu error. Launch this app with --disable-gpu does help but it's not convenient.

Can we have disable-gpu setting so that I can set it to true and no need to launch it in commandline?  there are many users request this feature in vs code and it was finally added as a runtime config in a recent release, so can we also have this in Azure Storage Explorer?

**Comment by MRayermannMSFT** [comment]
I'm going to consolidate this with issue  #2277
