### ISSUE TITLE
Azure Storage explorer does not open with the update

### ISSUE THREAD

**Issue by shrikan** [microsoft/AzureStorageExplorer#2288]
**Storage Explorer Version**: 1.11.0
**Build Number**:  20191105.2 
**Platform/OS**: macOS Catalina 10.15.1
**Architecture**: x64
**Regression From**:  previous one.

## Bug Description ##
When i tried opening the storage explorer on my macbook pro, the application apparently opens, but I dont see any window or anything. Except for 'About' window, I see none of the tabs or the windows getting opened even the 'settings'.

## Steps to Reproduce ##
Just try to open this Application in macOs Catalina.

## Expected Experience ##
See the Application.

## Actual Experience ##
Can't see the application being opened.

## Additional Context ##
NA

**Comment by JasonYeMSFT** [comment]
What do you mean by the "About" window? Do you mean the splash screen?
![image](https://user-images.githubusercontent.com/39359541/69187302-3318e900-0acf-11ea-83e7-c5624f4a6122.png)

If it is the case, could you please try starting Storage Explorer from the command line and see if there is any error in the console output?

**Comment by shrikan** [comment]
I dont see anything when I open the application. I get something like this,
![image](https://user-images.githubusercontent.com/31561078/69333618-4ce63780-0c59-11ea-9b73-9c4369136a24.png)

When i try to open About from the top menu, I get this
![image](https://user-images.githubusercontent.com/31561078/69333675-6f785080-0c59-11ea-97f2-bb1fa0f5ba06.png)

Other than this window, I cant see any window being shown. It will be like the first image.

**Comment by MRayermannMSFT** [comment]
Did you see this regression after updating Storage Explore or did it regress after updating macOS?

**Comment by shrikan** [comment]
Co-incidentally, both of them got updated recently. I am not sure which one of them has caused this issue.

**Comment by MRayermannMSFT** [comment]
Since this is Catalina, pretty sure this is related to app notarization. You can track our progress regarding that effort here: https://github.com/microsoft/AzureStorageExplorer/issues/2395

In the meantime, you should be able to still open Storage Explorer by right clicking and selecting open.
