### ISSUE TITLE
AzCopy Causes Insufficient credentials Error

### ISSUE THREAD

**Issue by ek1977** [microsoft/AzureStorageExplorer#2291]
**Storage Explorer Version**: 1.10.1 & 1.11.0
**Build Number**: 20190919.2
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  Yes

## Bug Description ##
When AzCopy is enabled uploads to a blob container do not work when connecting via a SAS Token with restrictions. 

## Steps to Reproduce ##

Using 1.10.1 use the following steps.  Using 1.11.0 the first step is not required.
1. Select "Use AzCopy for Improved Blob Upload and Download" from the Preview
2. Create a Blob storage container.
3. Create a SAS Token with Add, Write, and List permissions
4. Create a new connection with the URI
5. Try to upload a file.

Result: "Failed to start transfer: Insufficient credentials"

## Expected Experience ##
If using 1.10.1, turn off the "Use AzCopy for Improved Blob Upload and Download" option repeat steps 2 through 5 and the upload works.  Since there is not an option to turn off the use of AzCopy in 1.11.0 there is no way to make this work in that version.

**Comment by JasonYeMSFT** [comment]
@ek1977 , AzCopy currently requires the read permission to detect conflicts. Unfortunately it still has some other problem when the read permission is not provided, even if the overwrite option is turned on. We will work with the AzCopy team to fix this issue.

**Comment by JasonYeMSFT** [comment]
@ek1977, we have a similar issue open and I have posted some answers about AzCopy permission and proposed a potential way to allow you use finer level SAS connections with AzCopy there. I am going to track the issue there and close this one.

Please see #2325.
