### ISSUE TITLE
Error during downloading a file into the directory under "/“, which is used to mount a disk

### ISSUE THREAD

**Issue by tswc** [microsoft/AzureStorageExplorer#2292]
**Storage Explorer Version**: 1.11.0
**Build Number**: 20191105.2
**Platform/OS**: Linux Ubuntu
**Architecture**: x64
**Regression From**:  no

## Bug Description ##
Azure storage explorer can not read the directory under "/", which I use to mount a ext4 type disk.
When I use download in explorer, I can't find my target directory.
But in chrome, I can save anything in the directory

## Steps to Reproduce ##
1. create a directory "data" under "/"
2. mount the disk
e.g. sudo mount -t ext4 /data /dev/sda
3. open azure storage explorer, download a file. 
In the sub-window, you can not find "/data".

**Comment by MRayermannMSFT** [comment]
So are you saying that the Ubuntu file picker won't let you navigate to /data?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
