### ISSUE TITLE
The related bug id is incorrect on Releases Notes Fixes section

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2294]
**Storage Explorer Version:** 1.11.1
**Build:** [20191120.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3259026&view=logs)
**Branch:** hotfix/1.11.1
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer -> Help -> View Release Notes.
2. Check the third and four fix bugs id in Fixes section.

**Expect Experience:**
The related bug id is correct.

**Actual Experience:**
The related bug id is incorrect.
![image](https://user-images.githubusercontent.com/54055206/69227191-6ab18f00-0bbc-11ea-9cc7-d49e829f6b01.png)

**Comment by MRayermannMSFT** [comment]
Fixed.
