### ISSUE TITLE
The blob container auto open after pasting one blob container

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2295]
**Storage Explorer Version:** 1.11.1
**Build:** [20191120.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3259026&view=logs)
**Branch:** hotfix/1.11.1
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release(1.11.0)

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Expand one storage account -> Blob Containers.
3. Create a new blob container -> Copy it then paste it to another storage account.
4. Check the result.

**Expect Experience:**
The pasted blob container doesn't automatically open.

**Actual Experience:**

1. The pasted blob container automatically open.
2. The automatically opened blob container location information is incorrect.

![image](https://user-images.githubusercontent.com/54055206/69228280-40f96780-0bbe-11ea-8941-cd0e4e9f8b27.png)

**More Info:**
This issue doesn't reproduce for one file share/table.

**Comment by v-limu** [comment]
This issue also reproduces when cloning/renaming one blob container.

**Comment by v-xianya** [comment]
Verified on build 20200210.4. This issue also reproduces for one file share.
![image](https://user-images.githubusercontent.com/41351993/74208441-88275e00-4cbe-11ea-9929-6a18b373ea76.png)

**Comment by v-xianya** [comment]
File share part has been fixed on build 20200409.3.
![image](https://user-images.githubusercontent.com/41351993/78862501-1e32f700-7a6a-11ea-8224-361695b68ebb.png)

**Comment by v-limu** [comment]
Verified on build [20200410.5](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3629864&view=logs). This issue has been fixed.
![image](https://user-images.githubusercontent.com/54055206/78956697-a9b59200-7b15-11ea-82fb-9064f781574e.png)
