### ISSUE TITLE
A blob name is too long to fully display on 'Manage Access' dialog 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2296]
**Storage Explorer Version:** 1.11.1
**Build:** [20191120.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3259026&view=logs)
**Branch:** hotfix/1.11.1
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand an ADLS Gen2 account -> Blob Containers.
2. Open one blob container which contains one blob at least.
3. Select one blob and rename it with a long name. (Make sure there no space in the new name)
4. Right click the renamed blob then select 'Manage Access...'.
5. Check the blob name on the 'Manage Access' dialog.

**Expect Experience:**
Display the blob's full name.

**Actual Experience:**
Can't display the full name even resize the dialog.
![image](https://user-images.githubusercontent.com/41351993/69232962-dce48e00-0b40-11ea-964a-ea0ad29e2a71.png)

**Comment by MRayermannMSFT** [comment]
Won't fix for now. We're happy with how long blob names are handled here for now. If customers give feedback on it we can change.
