### ISSUE TITLE
Encoding invalid characters in filenames doesn't work in v1.11.0

### ISSUE THREAD

**Issue by dan-sovrea** [microsoft/AzureStorageExplorer#2297]
**Storage Explorer Version**: v1.11.0
**Build Number**: 
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  No

## Bug Description ##

A blob having ":" character in filename cannot be downloaded. In previous versions, those characters were encoded, and the download worked
## Steps to Reproduce ##

1. Upload a blob having ":" character in the filename (e.g. by using C# code and namespace Microsoft.WindowsAzure.Storage.Blob)
2. Try to download the blob

**Comment by JasonYeMSFT** [comment]
AzCopy isn't properly encoding the file names in this case. We will communicate and make a fix as soon as possible. 

In the mean time, as a work around, could you just rename the blobs or enable Target Azure Stack APIs for these operations? You can find the Azure Stack option under the Edit → Target Azure Stack APIs. It is designed for people who are using custom environments. However, for the download operations, it will fall back to use our old code which will handle the encoding. AzCopy has significantly better performance so you might want to turn it off once you finished working around the issue.

**Comment by dtmaidenmueller** [comment]
Encountered same problem in version 1.11.2 (blobs with ':' in name wouldn't download).  Was able to successfully use the 'Target Azure Stack APIs' workaround.

**Comment by adreed-msft** [comment]
What version of AzCopy is storage explorer on? This may already be fixed in 10.3.

**Comment by JasonYeMSFT** [comment]
@adreed-msft, we are already on 10.3.3 within our 1.11.2 release. It hasn't been fixed yet.

**Comment by dtmaidenmueller** [comment]
AzCopy version 10.3.2

**Comment by adreed-msft** [comment]
We've got a diagnosis.

In our code, we do attempt to encode this character. However, because : is apparently valid in URL paths, there is no effect.

**Comment by lostindark** [comment]
Any progress on this one? It has been broken for several month now. I really appreciate if we can get the fix in.

**Comment by adreed-msft** [comment]
Yes, it is in PR and should be released alongside the next release of SE.

**Comment by MRayermannMSFT** [comment]
We've verified that the next AzCopy version has indeed fixed this. That version of AzCopy will be included in Storage Explorer 1.13.0

**Comment by JasonYeMSFT** [comment]
This has been fixed in AzCopy 10.4.2 and integrated to the Storage Explorer 1.13.0 release.
