### ISSUE TITLE
Page for password is not opening

### ISSUE THREAD

**Issue by AbhishekKumar26** [microsoft/AzureStorageExplorer#2298]
**Storage Explorer Version**: 1.11.0
**Build Number**: 
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  The one downloaded in month of August(Sorry don't have the exact build number)

## Bug Description ##
I had my account added to the Storage Explorer on my machine.
It seems the credentials got expired. So, I was to re-enter the credentials. For entering the password, a message is displayed, taking you to the organization page and then nothing opens. 

I updated to the version 1.11.0 but the issue is still there.

Working fine for .onmicrosoft.com domains
## Steps to Reproduce ##
1. Click to Reenter credentials.
2. Select the account.
3. Wait for the password pane to open.

## Expected Experience ##
The page from the organisation with a field for password should have opened.

## Actual Experience ##
The overlay remains just white. Image attached,
## Additional Context ##

<img width="425" alt="Not going to Oganization Page" src="https://user-images.githubusercontent.com/19407265/69241466-de579a00-0bc4-11ea-829c-e917ce0f7b10.PNG">

**Comment by jinglouMSFT** [comment]
Can you please follow the troubleshooting guide to see if it resolves your issue?  https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C1904#sign-in-issues

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
