### ISSUE TITLE
Disable the 'Promote Snapshot' when selecting the original blob and one snapshot at the same time

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#230]
**Storage Explorer Version**: 1.2.0
**Platform**: All
**Architecture**: ia32/x64
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Launch Storage Explorer and expand Storage Accounts. 
2. Open one blob container and upload one blob file.
3. Create a snapshot for the uploaded blob.
4. Open the manage snapshots editor -> Select the original blob and one blob snapshot at the same time.
5. Check the 'Promote Snapshot' button on the toolbar. 

#### Expected Experience: ####
'Promote Snapshot' is disabled.

#### Actual Experience: ####
'Promote Snapshot' is enabled. 
![disable](https://user-images.githubusercontent.com/34729022/40773081-586303e6-64b1-11e8-8925-cbe34554faed.png)

**Comment by MRayermannMSFT** [comment]
Find out what happens when you click it, depending on what happens, we'll decide what to do with this bug.

**Comment by MRayermannMSFT** [comment]
Merged into rel/stg-ex/1.2.0 for 1.2.0
