### ISSUE TITLE
For Mac: screen will turn black and have to close the app.

### ISSUE THREAD

**Issue by amtsha09** [microsoft/AzureStorageExplorer#2302]
Creating new folder or deleting file gives out full screen confirmation dialog and then turns black.

**Comment by jinglouMSFT** [comment]
Can you be a little more specific?  
Which version of Storage Explorer?  Which version of Mac OS?
Is this for Blob? File Shares?  ADLS Gen2 account?  or something else?
Does this happen to other dialog or just these two?

**Comment by v-xianya** [comment]
Hi @jinglouMSFT We also met this issue.

**Platforms:** MacOs 10.13.6

**Repro Steps:**
1. Launch Storage Explorer -> Make it full screen.
2. Execute an action to open one dialog.
3. Select and click one button on the prompt dialog.
4. Check the result.

**Actual:**
The screen turns black.

![image](https://user-images.githubusercontent.com/41351993/69313865-98f89400-0be7-11ea-9f86-14a06f92b1fd.png)

**Comment by amtsha09** [comment]
> Can you be a little more specific?
> Which version of Storage Explorer?  
Version: 1.10.1
AzCopy Version: 10.2.1

Platform: macOS
Architecture: x64 
Build Number: 20190919.2 
Commit: 868c6dff1 
Support ID: e6a2b7fc-8e8c-88ba-2db7-d8fce1f406cb 

> Which version of Mac OS?  
Mac OS Catalina 10.15.1 ,

> Is this for Blob? File Shares? ADLS Gen2 account? or something else?
Blob, gen2

> Does this happen to other dialog or just these two?
So far these two, not always but most of the times.

**Comment by MRayermannMSFT** [comment]
@amtsha09 great bug find. None of us have ever noticed this. For now, you'll need to not run in full screen, but we'll look into getting this fixed.

**Comment by amtsha09** [comment]
@MRayermannMSFT happy to help :-)
Thanks.

**Comment by MRayermannMSFT** [comment]
Fix merged into master. Will ship with 1.13.0. Thank you again @amtsha09
