### ISSUE TITLE
A render process crash caused Storage Explorer to stop working correctly.

### ISSUE THREAD

**Issue by jamesosb-msft** [microsoft/AzureStorageExplorer#2303]
**Storage Explorer Version**: 1.11.0
**Build Number**: 20191105.2
**Platform/OS**: <Windows 10
**Architecture**: x64?
**Regression From**:  Not sure; it was crashing, so I updated to the latest I could find and still having this issue.

## Bug Description ##
When I search for a specific table name, it very slowly starts finding matches, but after about a minute or so, it just crashes with this error:
[Window Title]
Microsoft Azure Storage Explorer

[Content]
A renderer process crash caused Storage Explorer to stop working correctly. Storage Explorer can try to restart the program.

[Restart] [Close Application]

## Steps to Reproduce ##
Not sure why everyone isn't seeing this.  I have about a dozen storage accounts attached, some with expired keys, that I haven't bothered removing and re-adding (because I haven't found any way to edit an existing connection with StorageExplorer)

## Expected Experience ##
Search works, and the app doesn't crash? 

## Actual Experience ##
I can't search for table names.

**Comment by MRayermannMSFT** [comment]
Hi @jamesosb-msft , search currently has some...performance issues. Are you seeing the error when not searching>

**Comment by jamesosb-msft** [comment]
I know it crashed a few different times while I was away, but I’m not sure if it was hanging on a search or not.  Crashing isn’t what I’d normally call a performance issue, though. 😊

It worked fine for me for over a year, just suddenly started doing this.  I kept trying to update to newer versions hoping it was something fixed, but looks more like a regression.

-James

**Comment by MRayermannMSFT** [comment]
Can you let us know what version of Storage Explorer you start seeing the regression? You can find older versions of Storage Explorer here: https://github.com/microsoft/AzureStorageExplorer/releases

 And also, if you can lock down about whether or not this ever happens when doing something other than search?

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response.
