### ISSUE TITLE
Update 'ADLS Gen 2' to 'ADLS Gen2' on Release Notes Fixes section

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2304]
**Storage Explorer Version:** 1.11.1
**Build:** [20191121.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3262013&view=results)
**Branch:** hotfix/1.11.1
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer -> Help -> View Release Notes.
2. Check 'ADLS Gen2' on Fixes section.

**Expect Experience:**
Show 'ADLS Gen2'.

**Actual Experience:**
Show 'ADLS Gen 2'.
![image](https://user-images.githubusercontent.com/41351993/69318895-f9410300-0bf2-11ea-9e63-a734cdff632b.png)

**Comment by MRayermannMSFT** [comment]
Won't fix.
