### ISSUE TITLE
There is an extra 'to' in description of the second issue on Known Issues section

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2305]
**Storage Explorer Version:** 1.11.1
**Build:** [20191121.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3262013&view=results)
**Branch:** hotfix/1.11.1
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer -> Help -> View Release Notes.
2. Check description of the second issue on Known Issues section.

**Expect Experience:**
No extra 'to' shows.

**Actual Experience:**
There is an extra 'to' in the description.
![image](https://user-images.githubusercontent.com/41351993/69319339-d7944b80-0bf3-11ea-8c9c-a2f4fc4ef241.png)

**Comment by MRayermannMSFT** [comment]
Fixed in the remote release notes.
