### ISSUE TITLE
Misspell the word 'access' on Release Notes Fixes

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2307]
**Storage Explorer Version:** 1.11.1
**Build:** [20191121.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3262013)
**Branch:** hotfix/1.11.1
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer -> Help -> View Release Notes.
2. Check the word 'access' in Fixes section.

**Expect Experience:**
The word 'access' spells correctly.

**Actual Experience:**
Misspell the word 'access'.
![image](https://user-images.githubusercontent.com/54055206/69326552-f394fd00-0c86-11ea-80cb-18f1326325db.png)

**Comment by MRayermannMSFT** [comment]
Fixed in the remote release notes.
