### ISSUE TITLE
No error pops up when renaming one ADLS Gen2 folder with an existing folder name 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2308]
**Storage Explorer Version:** 1.11.1
**Build:** [20191121.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3262013)
**Branch:** hotfix/1.11.1
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Expand one ADLS Gen2 account -> Blob Containers.
3. Create a new blob container -> Upload two folders with blobs.
4. Try to rename one folder using another folder name.
5. Check the result.

**Expect Experience:**
An error pops up.
![image](https://user-images.githubusercontent.com/54055206/69325050-7f595a00-0c84-11ea-9ed5-3b21a03ff082.png)

**Actual Experience:**

1. No error pops up.
2. The renamed folder displays under the exists folder.
![image](https://user-images.githubusercontent.com/54055206/69325828-c005a300-0c85-11ea-8a6f-a496d0dfde15.png)

**More Info:**
This issue doesn't reproduce for one folder under a regular blob container.

**Comment by MRayermannMSFT** [comment]
Related to #2103. Fix at same time. Rename should not let you move. Move should only be available via move.

**Comment by v-xianya** [comment]
Verified this issue on build main/20200904.2. Fixed.

When trying to rename one folder using an existing folder name, show a failed activity log.
![image](https://user-images.githubusercontent.com/41351993/92342899-dede0480-f0f4-11ea-9e97-762b5e5280c2.png)
