### ISSUE TITLE
No placeholder of property's value displays in 'Add Entity' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#231]
**Storage Explorer Version**: 1.2.0
**Platform**: All
**Architecture**: ia32/x64
**Regression From**: Previous release

#### Steps to Reproduce: ####
1. Launch Storage Explorer and expand Storage Accounts. 
2. Open one table then click 'Add' button on the toolbar.
3. Add properties for the entity and check whether the placeholder of property's value displays or not

#### Expected Experience: ####
The placeholder of added property's value displays well.

#### Actual Experience: ####
No placeholder of added property's value displays.
![placeholder](https://user-images.githubusercontent.com/34729022/40773542-bc8ca4fc-64b2-11e8-8c02-b895ac701438.png)

**Comment by MRayermannMSFT** [comment]
Won't fix.
