### ISSUE TITLE
Azcopy options in azure storage explorer

### ISSUE THREAD

**Issue by vick-git** [microsoft/AzureStorageExplorer#2315]
**Problem**
In Ubuntu Azure Storage explorer, users are facing bulk upload issue where the uploads are failing. Similarly, rename/move/copy operations on files are getting grayed out for certain users.

**Solution I'd like**
For the bulk upload issue, setting the value of AZCOPY_CONCURRENCY_VALUE to 4 sometimes fixes it. For the rename/moving issue, clearing out cache is helping but Azcopy is handling it better in cases where those rename/move options are grayed out in Azure Storage Explorer. While these are only workarounds, on behalf of convenience everyone facing this issue, this is being an overhead doing throughout a lot of issue facing machines.

Having **_Azcopy options in Azure Storage Explorer_** would be ideal in such scenarios where users can quickly try the failing operations the UI way, without having to go the console way.

**Describe alternatives you've considered**
For the bulk upload issue, setting the value of AZCOPY_CONCURRENCY_VALUE to 4 sometimes fixes it. For the rename/moving issue, clearing out cache is helping but Azcopy is handling it better in cases where those rename/move options are grayed out in Azure Storage Explorer. **_These are only workarounds though._**

**Comment by JasonYeMSFT** [comment]
We have added several AzCopy options to Storage Explorer in 1.10.0, which includes the AZCOPY_CONCURRENCY_VALUE. It can be configured in the settings panel. I am not sure what exactly are the grayed out situations. Is it on Blob storage or Fileshare? Does Storage Explorer grayed out all the time or only on large batch of transfers? Also what cache are you clearing?

By the way, we have just fixed a snap related bug that might block some Linux users in 1.10 in 1.11.1. If you encountered any issue, please try upgrading to 1.11.1.

**Comment by vick-git** [comment]
@JasonYeMSFT , thanks for responding quickly. The graying out is basically move/rename/copy buttons in Azure Storage explorer are getting disabled for certain users in a Storage Account in spite of giving Blob Data Contibutor at account and container level. It is Blob storage container. 
Like I mentioned there are 2 different issues.
Graying out happens with buttons irrespective of any occurrence. It was specific to a few accounts. Cache clearing recommended below is related to this graying out. 

1.    Remove all accounts and then close Storage Explorer.
2.    Delete the .IdentityService folder from your machine. For Linux, you can find the folder at the root of your user directory.
3.    If you're running Linux, you'll also need to delete the Microsoft.Developer.IdentityService entry from your operating system's keystore. In Linux, the application is typically called Keyring, but the name might differ depending on your distribution.
 
On Linux, find identity caches at ~/.IdentityService
 
https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&tabs=macOS%2C1904#reauthentication-loop-or-upn-change

Bulk uploads were failing when trying to upload 4 or 5 files of over 10+ GB each.

**Comment by JasonYeMSFT** [comment]
The buttons will be grayed out if the blob container's connection has no Account Key nor SAS token for the account/container. The reason is that we cannot perform the related request without those credential information. I can't understand why clearing the cache may help unless the next time you add the connection, you happened to gave it a key or a SAS. 

Could you please share what kind of connection are you using for the blob container (e.g. sign-in, key attached account, SAS attached account, Azure AD attached container)?

For the upload failures, could you please share the AzCopy log file with us. It would be helpful if we can see what errors AzCopy is emitting.

**Comment by JohnRusk** [comment]
Note to anyone reading this, I recommend setting the concurrency value to AUTO instead of to 4.  AUTO will never perform slower than 4, and may in some cases perform much, much better.
