### ISSUE TITLE
Mandatory use of AzCopy makes copies within a storage account MUCH slower

### ISSUE THREAD

**Issue by m455954** [microsoft/AzureStorageExplorer#2317]
Before copy and paste used AzCopy, copying files between containers within the same storage account was almost instantaneous - this was invaluable for updating source VHDs used in ARM templates. 

Obviously AzCopy is great for speeding up copies between storage accounts (especially where they are in different regions), but copies between containers within the same storage account should NOT use AzCopy as it makes the copy take a LOT longer (copying at less that 1Gbps for large VHD images)

Please change the behaviour so that if the copy is happening withing the same storage account, Storage Explorer does NOT use AzCopy (or at least make it an option?)

Thanks.

**Comment by MRayermannMSFT** [comment]
@m455954 , thanks for bringing up this point. We're talking to AzCopy team about getting them to let the server perform the copy for a in storage account copy. Until then, if your copies are taking too long, you can downgrade to an earlier version of Storage Explorer which isn't using AzCopy by default: https://github.com/microsoft/AzureStorageExplorer/releases

**Comment by MRayermannMSFT** [comment]
@m455954 , we talked to both the AzCopy team and the platform team. At this time AzCopy is not going to add the ability to perform the faster (aka lazy) copies. The server itself is also moving away from shallow copies, and in the future everything will be a proper copy. If you'd like AzCopy to add an option to let us do a server side copy please go file an issue against them here: https://github.com/Azure/azure-storage-azcopy/issues
