### ISSUE TITLE
Hotfix released yesterday caused error deleting folders on linux

### ISSUE THREAD

**Issue by jmwoloso** [microsoft/AzureStorageExplorer#2320]
**Storage Explorer Version**: 1.11.1
**Build Number**: 20191121.1
**Platform/OS**: linux
**Architecture**: x64
**Regression From**:  1.11.0 (I guess, who knows?)
**Commit ID**: a989e2136
**Support ID**: 99d59395-0321-d43f-17ac-4d08be1b624b

## Bug Description ##
Deleting folder is not possible and results in an error.

## Steps to Reproduce ##
1. Select folder
2. Hit delete
## Expected Experience ##
That the folder can be deleted

## Actual Experience ##
Error is:

ENOENT: no such file or directory, mkdir "<path_to_fs_redacted>"

## Additional Context ##
I opened storage explorer and a screen popped up that said a hotfix had been applied, so I'm assuming this caused the issue.

**Comment by MRayermannMSFT** [comment]
@jmwoloso , can you share the path in the error message? it's ok if you need to redact parts of it, but we're curious to know in general what the path is pointing to. Also, are you using snap or the .tar.gz?

**Comment by jmwoloso** [comment]
@MRayermannMSFT the path in the error message is `/home/jason/snap/storage-explorer/5/.config/StorageExplorer/sessions/5ba4a98d-c62d-550c-a7f7-a183251f417d` I thought I was using the tar.gz (I found where i downloaded and unzipped it) but this looks like i'm using snap...so i'm not sure, lol. maybe I tried snap because I was having issues with the gzipped tarball.

**Comment by JasonYeMSFT** [comment]
@jmwoloso , sorry about it. We have identified the bug. The reason is that we are assuming an existing folder structure from snap so that we are not creating the folders recursively. For now, to work around this issue, you may need to manually create the parent directories. In your case, you will need to create directories such that "/home/jason/snap/storage-explorer/5/.config/StorageExplorer/sessions/" is an empty directory, From then on, it will be able to create directories inside it and do the work.

**Comment by jmwoloso** [comment]
thanks for the quick response. i'll try that out and report back. uploading also seems to be broken. it just queues the transfer but it never starts (and of course never completes).

**Comment by jmwoloso** [comment]
I tried your proposed solution @JasonYeMSFT and I get`EACCES: permission denied...`

**Comment by JasonYeMSFT** [comment]
How did you create the directory? Have you tried just run command `mkdir /home/jason/snap/storage-explorer/5`, and so on?

**Comment by jmwoloso** [comment]
reported by storage explorer when i try and delete a folder from adls

**Comment by JasonYeMSFT** [comment]
We have made a fix for this bug in 1.12.0, which will be released soon.

**Comment by jmwoloso** [comment]
everything seems to be fine now, though every so often I have to delete the .ServiceHub folder because I get the .NET 2.1 error, but that's a separate issue. Thanks for the fix!
