### ISSUE TITLE
Linux: v1.11.1 says that .NET 2.1 isn't installed, even though it is

### ISSUE THREAD

**Issue by Genius1237** [microsoft/AzureStorageExplorer#2322]
**Storage Explorer Version**: 1.11.1
**Build Number**: 
**Platform/OS**: Ubuntu 18.04
**Architecture**: x64
**Regression From**:  Working in 1.11.0

## Bug Description ##
On startup, an error saying that .NET v2.1 isn't installed, when in fact it actually is. 1.11.0 doesn't show this error

## Steps to Reproduce ##
1. Install .NET v2.1
2. Install storage explorer v1.11.1
3. Open storage explorer

## Additional Context ##
Possibly related to #2321

**Comment by MRayermannMSFT** [comment]
Are you installed via Snap or are you using the .tar.gz?

**Comment by Genius1237** [comment]
I'm using the tar.gz method.

**Comment by MRayermannMSFT** [comment]
Cool. If you could do the following steps, it'd be very helpful in diagnosing this issue:

# Verify .NET Version
1. Open a terminal
2. run `dotnet --info` and verify that the version under `Host` is at least 2.1 (it's not that I don't trust you, it's just that you never know if maybe the version you installed didn't get itself installed correctly or something like that)

# Get ServiceHub logs
1. Open a terminal
2. Navigate to where you have the Storage Explorer executable
3. `rm -rf ~/.ServiceHub/logs/`
4. `SERVICEHUBTRACELEVEL=ALL
5. Run Storage Explorer
6. After the issue repros, there should now be a new `~/.ServiceHub/logs/` folder. Zip that folder up and attach it to this issue.

**Comment by MRayermannMSFT** [comment]
Also, how did you install the update? Did you delete the old version and then extract the new one? Or did you just extract the new one into where the old one was and overwrote the conflicts. Basically, I'm trying to figure out whether any of the files from the old version are still there. If they are, then I recommend deleting all the installed files and reinstalling from storageexplorer.com

**Comment by Genius1237** [comment]
dotnet version is 2.1.14

I'm installing the new version now, so give me few min.

I had the old version installed in one system and it worked on it. I was installing the new one on another system and ran into an issue there. Installed the old one there and it worked.

**Comment by MRayermannMSFT** [comment]
For anyone else on Linux who is using the .tar.gz running into this problem, please try installing .Net Core 2.2 or higher! The message in the error box is unfortunately wrong.

If you are on snap, then please open a new issue. 

If you are on Windows, then please use issue #2323 

If you are on macOS, then please open a new issue.

**Comment by MRayermannMSFT** [comment]
I've merged an updated string for 1.12. The troubleshooting guide is also now up to date. Will leave this open for a while tho.

**Comment by gnloch** [comment]
On Linux, with version 1.11.1 and dotnet core 2.2, I still got the same error. 
Version 1.11.0 works fine with the same version of dotnet.
```
$ dotnet --info

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.2.6 [/opt/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by MRayermannMSFT** [comment]
@gnloch , can you try deleting your ~/.ServiceHub directory?

**Comment by gnloch** [comment]
#

> @gnloch , can you try deleting your ~/.ServiceHub directory?

I deleted `~/.ServiceHub` and got the same error.

**Comment by MRayermannMSFT** [comment]
@gnloch , can you get me the some other logs?

1. Open a terminal
2. Navigate to where you have the Storage Explorer executable
3. rm -rf ~/.ServiceHub/logs/
4. export SERVICEHUBTRACELEVEL=ALL
5. Run Storage Explorer
6. After the issue repros, there should now be a new ~/.ServiceHub/logs/ folder. Zip that folder up and attach it to this issue.

**Comment by gnloch** [comment]
[StorageExplorer.logs.zip](https://github.com/microsoft/AzureStorageExplorer/files/3947468/StorageExplorer.logs.zip)
```
$ pwd
/opt/StorageExplorer
$ ls -la
total 139M
drwxr-xr-x 5 root root  4.0K Dec 10 19:28 .
drwxr-xr-x 8 root root  4.0K Dec  9 11:58 ..
-rw-r--r-- 1 root root  164K Dec  9 11:22 chrome_100_percent.pak
-rw-r--r-- 1 root root  245K Dec  9 11:22 chrome_200_percent.pak
-rw-r--r-- 1 root root  9.8M Dec  9 11:22 icudtl.dat
-rw-r--r-- 1 root root  250K Dec  9 11:22 libEGL.so
-rw-r--r-- 1 root root  2.9M Dec  9 11:22 libffmpeg.so
-rw-r--r-- 1 root root  5.8M Dec  9 11:22 libGLESv2.so
drwxr-xr-x 2 root root  4.0K Dec 10 19:28 locales
-rw-r--r-- 1 root root  123K Dec  9 11:22 natives_blob.bin
drwxr-xr-x 3 root root  4.0K Dec 10 19:28 resources
-rw-r--r-- 1 root root  8.3M Dec  9 11:22 resources.pak
-rw-r--r-- 1 root root  627K Dec  9 11:22 snapshot_blob.bin
-rwxr-xr-x 1 root root  110M Dec  9 11:22 StorageExplorer
drwxr-xr-x 2 root root  4.0K Dec 10 19:28 swiftshader
-rw-r--r-- 1 root root 1017K Dec  9 11:22 v8_context_snapshot.bin
```

**Comment by MRayermannMSFT** [comment]
@gnloch can you verify where your install of .Net Core ended up being?

The default location is `/usr/share/dotnet`. If it is not there, then you need to set the environment variable `DOTNET_ROOT` to be the location where it is installed. If it is there, you can still try setting the environment variable anyways.

Also, I see you're also a MSFT employee. Feel free to message me internally for real-time help.

**Comment by gnloch** [comment]
Using  `DOTNET_ROOT` environment variable fixed the problem. Thanks @MRayermannMSFT .

**Comment by MRayermannMSFT** [comment]
Cool thanks @gnloch.
