### ISSUE TITLE
First time connecting using ASE, error "Read: ECONNRESET"

### ISSUE THREAD

**Issue by steffeg** [microsoft/AzureStorageExplorer#2324]
This is the message I get: request to https://apmdlw001.blob.core.windows.net/cona?delimiter=%2F&maxresults=1000&include=metadata&restype=container&comp=list failed, reason: read ECONNRESET

**Comment by MRayermannMSFT** [comment]
Did you sign in or attach? Is the Storage Account the container is in ADLS Gen2?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
