### ISSUE TITLE
Explorer pan  search takes forever to search resources.

### ISSUE THREAD

**Issue by thrajput** [microsoft/AzureStorageExplorer#2326]
**Storage Explorer Version**: 1.10.1
**Build Number**: 20190919.2 
**Platform/OS**: Windows 10
**Architecture**: ia32
**Regression From**: No

## Bug Description ##
When I click on the search button on Explorer bar on left side, it takes forever.

## Steps to Reproduce ##
Search anything in left bar in explorer. Most of the time it takes forever and shows "Searching....."

## Expected Experience ##
Should show the search results or some error or not found

## Actual Experience ##
Does not return any result and takes forever

![image](https://user-images.githubusercontent.com/8745763/69585374-5b538c80-0f94-11ea-895d-e60091c2a467.png)

**Comment by MRayermannMSFT** [comment]
Hi @thrajput , we are definitely aware of the performance issues with search. We have plans to address it in the future.

**Comment by ahyerman** [comment]
@craxal @MRayermannMSFT any updates on this? Search performance still seems pretty poor

**Comment by craxal** [comment]
@ahyerman We do not have any significant updates at this time.

Search is a very complex and ongoing problem. Storage Explorer needs to call into several different APIs to get lists of resources, and there is no unified way to query for resources. Some APIs support search criteria, such as listing subscription-level resources like storage accounts, but others do not.

For APIs lacking efficient query support, we have to do filtering on the client side. Results are sent in batches, and if you have a lot of resources, many calls are needed to iterate through all of them. With searching and filtering, many of the items in these batches don't match the search criteria, and so these API calls become wasteful.

Despite these problems, we are looking at improvements and alternatives. For example, we intent to provide an easier way to connect to resources you already know the name of without having to wade through long lists just to find the right tree node (see #75). We are also working with the Azure platform to get better search support, which should be much more efficient than client-side search.

**Comment by JasonYeMSFT** [comment]
I am making some improvements in this feature area in 1.22.0 and here are what I have done:
- The status message now displays how many nodes have been scanned.
- Under the search box, there will be a dropdown list allowing you to select what type of resource you want to search for (e.g. blob container, file share, etc.) or a combination of them. Irrelevant nodes won't be expanded to save resources.

**Comment by JasonYeMSFT** [comment]
We have released 1.22.0 which includes the mentioned improvements.
