### ISSUE TITLE
Linux, snap: 1.11.1 says .NET 2.1 isn't installed

### ISSUE THREAD

**Issue by EpicWink** [microsoft/AzureStorageExplorer#2327]
**Storage Explorer Version**: 1.11.1 via Snap
**Build Number**: 
**Platform/OS**: Ubuntu 19.10
**Architecture**: x64
**Regression From**: 1.11.0 or 1.10.x

## Bug Description ##
Error dialogue appears upon opening Storage Explorer, saying .NET Core 2.1 needs to be installed.

## Steps to Reproduce ##
1. Install Storage Explorer via snap
2. Start Storage Explorer, wait about 10 seconds

## Expected Experience ##
Normal use of Storage Explorer

## Actual Experience ##
Error dialogue, with text:
To run Microsoft Azure Storage Explorer on Linux, you must have .NET Core 2.1 installed. Please make sure .NET Core 2.1 is properly installed before launching the application again.

## Additional Context ##
Related to #2322

**Comment by MRayermannMSFT** [comment]
@EpicWink , can you grab me some logs?

1. Open a terminal
2. `rm -rf ~/snap/storage-explorer/current/.ServiceHub/logs/`
3. `export SERVICEHUBTRACELEVEL=ALL`
4. `storage-explorer`
5. After the issue repros, there should now be a new `~/snap/storage-explorer/current/.ServiceHub/logs/` folder. Zip that folder up and attach it to this issue.

**Comment by EpicWink** [comment]
@MRayermannMSFT here are the request logs: [logs.zip](https://github.com/microsoft/AzureStorageExplorer/files/3894471/logs.zip)
Also, have some command-line logs: [command-line-logs.txt](https://github.com/microsoft/AzureStorageExplorer/files/3894482/command-line-logs.txt)

**Comment by MRayermannMSFT** [comment]
Thanks @EpicWink , can you try deleting the folder `~/snap/storage-explorer/current/.ServiceHub/`?

**Comment by EpicWink** [comment]
@MRayermannMSFT that worked perfectly, thanks

**Comment by EpicWink** [comment]
@MRayermannMSFT bad news, after PC restart, the issue re-appears. Removing the directory fixes it again

**Comment by MRayermannMSFT** [comment]
I've talked with the team who owns this component and they understand the issue. I'll work on getting you a private build so you can have their fix for the bug, but until then you'll need to just delete the directory whenever you run into the issue. :(

**Comment by EpicWink** [comment]
@MRayermannMSFT no worries, thanks for the update. Let me know how I can help. Deleting a directory once a day isn't the worst thing in the world

**Comment by jmwoloso** [comment]
This also happened to me out of the blue today. Deleting the folder solved it, I've yet to restart to see if the issue persists but will update when I do.

**Comment by MRayermannMSFT** [comment]
Hey y'all. I have a private build which _should_ 🤞 fix needing to delete the folder. This build is 1.11.1 plus a fix for this issue, and a fix for a bug that can happen after upgrading a snap. If you have a chance, please give it a chance and let us know if you still see this issue.

Snap can be found here: https://storageexplorerpublish.blob.core.windows.net/privatebuilds/1.11.1-Linux-Fixes/StorageExplorer_latest_amd64.snap

To install it execute `sudo snap install StorageExplorer_latest_amd64.snap --dangerous`

**Comment by EpicWink** [comment]
That provided build seems to work fine. Will let you know if it fails after a PC restart

**Comment by EpicWink** [comment]
This problem didn't arise in v1.12. I'll close this tomorrow
