### ISSUE TITLE
Remove the prepending slash from one opened blob container's path

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2329]
**Storage Explorer Version:** 1.11.0
**Build:** [20191126.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3273921&view=results)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Expand one storage account -> Blob Containers.
3. Select one blob container and open it.
4. Hover the mouse to the opened blob container tab -> Check the shown path.

**Expect Experience:**
No slash shows at the beginning of the path.

**Actual Experience:**
There shows a slash at the beginning of the path.
![image](https://user-images.githubusercontent.com/41351993/69839428-5c8eee80-120c-11ea-815e-999a674a4544.png)

**More Info:**
This issue also reproduces for one opened file share/ queue/ table.

**Comment by MRayermannMSFT** [comment]
Won't fix pending customer feedback

**Comment by v-xianya** [comment]
Related bug: [1819](https://github.com/microsoft/AzureStorageExplorer/issues/1819)
