### ISSUE TITLE
No error appears when inputting a value less than 0 in 'Add CORS Rules' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#233]
**Storage Explorer Version**: 1.2.0
**Platform**: All
**Architecture**: ia32/x64
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Launch Storage Explorer and expand Storage Account.
2. Right click one Blob Containers node then select 'Configure CORS Settings...'.
3. Click 'Add' button -> Input '0' for the 'Max Age' value -> Click the down arrow to decrease the value.(The value of 'Max Age' can't be less than 0 by clicking down arrow)
4. Input '-1' for the 'Max Age' value and check whether an error displays or not.

#### Expected Experience: ####
An error appears.

#### Actual Experience: ####
No error appears.
![-1](https://user-images.githubusercontent.com/34729022/40774443-231acf62-64b5-11e8-845a-d6671dd4ac09.png)

**Comment by MRayermannMSFT** [comment]
Find out what happens when negative value is saved.

**Comment by craxal** [comment]
I would've expected the platform to return an error. But looks like Storage Explorer saves it just fine. Even the Azure portal reports back the set value. The documentation doesn't appear to specify anything about valid values. I'll do some investigation to find out if this is intentional or a bug in the platform.

**Comment by craxal** [comment]
According to [CORS documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Max-Age), negative values are acceptable. Browsers may also want to interpret different negative values certain ways.

I had a word with the platform people, and they agree the portal should not invalidate these negative values. So Storage Explorer is behaving correctly here.
