### ISSUE TITLE
Update 'ADLS Gen 2' to 'ADLS Gen2' in Settings AzCopy part

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2330]
**Storage Explorer Version:** 1.11.0
**Build:** [20191126.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3273921&view=results)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open Settings -> Transfers -> Check the first sentence.

**Expect Experience:**
Show 'ADLS Gen2' in the sentence.

**Actual Experience:**
Show 'ADLS Gen 2' in the sentence.
![image](https://user-images.githubusercontent.com/41351993/69618537-e6617080-0fee-11ea-9ce9-323d1cab7cfd.png)

**Comment by jinglouMSFT** [comment]
Needs a packaging update which Matt will do together with his change. The fix itself is already in the component.

**Comment by v-xianya** [comment]
This issue has been fixed on build master/20191206.2. So close it.
![image](https://user-images.githubusercontent.com/41351993/70304215-6d5ae800-183c-11ea-8ab5-d20ef1c3fb9e.png)
