### ISSUE TITLE
Can't expand services node under (Emulator – Default Ports ) (Key)

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2331]
**Storage Explorer Version:** 1.11.0
**Build:** [20191126.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3273921&view=results)
**Branch:** master
**Emulator:** V5.10.0
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Open the local file AzureStorageEmulator.exe.config("C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe.config") -> Update services ports like below.
![image](https://user-images.githubusercontent.com/41351993/52553311-09cf7c00-2e1e-11e9-8ca4-6aba05a17b07.png)

2. Restart Azure Storage Emulator and open Storage Explorer.
3. Expand Local & Attached -> Storage Accounts -> (Emulator - Default Ports) (Key).
4. Try to expand the Blob Containers & Queues & Tables.
5. Check the result.

**Expect Experience:**
Services node can be expanded successfully.

**Actual Experience:**
1. Display loading... under Blob Containers & Queues. 
![image](https://user-images.githubusercontent.com/41351993/69619997-72749780-0ff1-11ea-8880-a61f4df6b24f.png)

2. The below error occurs when trying to expand Tables.
![image](https://user-images.githubusercontent.com/41351993/69620030-85876780-0ff1-11ea-8880-55f0a6380f72.png)

**More Info:**
1. Attach the account using local emulator (Change the endpoint **Blobs port:10003; Queues port: 10004; Tables port:10005**), the services node can be expanded under the attached account.
![image](https://user-images.githubusercontent.com/41351993/69619849-245f9400-0ff1-11ea-88ef-b6e06c007ff8.png)

**Comment by JasonYeMSFT** [comment]
The "(Emulator - Default Ports" node will use the default ports (10002 for blobs, 10003 for queue, 10004 for table). If you have changed the ports being used, it may not work. This is by design.

**Comment by v-xianya** [comment]
Hi @JasonYeMSFT Thanks for your updates
The default Ports (10000 for blobs, 10001 for queue, 10002 for table)

Could you help to see the below questions?
1. What you mean **The "(Emulator - Default Ports" node will use the default ports (10002 for blobs, 10003 for queue, 10004 for table)** ?


2. I changed the default ports  ( for blobs: 10000->10003,  for queue: 10001 ->10004 , for table:10002->10005 ) in Emulator configure file. NOW, What are the default Ports ?

**Comment by abhishek-kumar-kantar** [comment]
> The "(Emulator - Default Ports" node will use the default ports (10002 for blobs, 10003 for queue, 10004 for table). If you have changed the ports being used, it may not work. This is by design.

Hi @JasonYeMSFT 
I am also facing issue the same issue.

<img width="848" alt="Image" src="https://github.com/user-attachments/assets/6a472079-0f18-407d-9b23-e6ad6464659d" />

on port 10001 already a network service called "agent-id-service" is running. In this case what do you suggest because chnaging the port number looks risky?
