### ISSUE TITLE
Succeed to delete one blob container which contains leased blobs

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2332]
**Storage Explorer Version:** 1.11.0
**Build:** [20191126.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3273921&view=results)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Expand one storage account -> Blob Containers.
3. Create one blob container -> Upload one blob then acquire lease for the blob.
4. Try to delete the blob container.
5. Check the result.

**Expect Experience:**
Fail to delete.

**Actual Experience:**
Succeed to delete.

**More Info:**
1. This issue also reproduces for one blob container which contains blobs with snapshots.

2. Fail to rename one blob container which contains leased blobs. Show the below error.

    **Renaming 'New Text Documrtrtyent.txt' to 'New Text Documrtrtyent.txt': Could not delete the 
     original item after copying.
     Details:
     There is currently a lease on the blob and no lease ID was specified in the request. 
    RequestId:b124c32e-201e-0051-6243-a48b41000000 Time:2019-11-26T10:21:55.6314999Z**

 
3. Fail to rename one blob container which contains blobs with snapshots. Show the below error.

     **Renaming 'New Text Documrtrtyent.txt' to 'New Text Documrtrtyent.txt': Could not delete the original item after copying.
 Details:
 This operation is not permitted because the blob has snapshots. RequestId:cd1d1508-301e-0067-0943-a42613000000 Time:2019-11-26T10:23:38.3593638Z**

**Comment by MRayermannMSFT** [comment]
We need to open a bug against AzCopy for preserving leases on copy.

**Comment by MRayermannMSFT** [comment]
By design

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT 
Could you help to elaborate the reason why this issue is by design? Thank you😊
