### ISSUE TITLE
Some strings haven't been translated in 'Reset' dialog

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2333]
**Storage Explorer Version:** 1.11.0
**Build:** [20191126.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3273921)
**Branch:** master
**Language:** Chinese(zh-CN) / Chinese(zh-TW)
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Chinese (simplified)' -> Restart Storage Explorer.
3. Help -> Click 'Reset'.
4. Check the dialog.

**Expect Experience:**
All strings are translated. 

**Actual Experience:**
There are strings haven't been translated.
![image](https://user-images.githubusercontent.com/54055206/69619305-5c5cea80-1076-11ea-9940-94c154b20f8e.png)

**Comment by lukaschal** [comment]
@craxal Are these strings exposed to localization ?

**Comment by v-limu** [comment]
This issue also reproduces in **Japanese**.
![image](https://user-images.githubusercontent.com/54055206/71237480-956a4100-233c-11ea-906c-f06b1fb2a953.png)

**Comment by v-xianya** [comment]
@lukaschal 
Verified this issue on build [20200319.10](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3566615).

 String 'Areas to reset' is not localized in Chinese(zh-CN)/Turkish/ Italian/ German.
![image](https://user-images.githubusercontent.com/41351993/77131987-bdcb1e00-6a98-11ea-8739-5da1797e862e.png)

**Comment by lukaschal** [comment]
Localized at 3/19/2020.

0; "LabelAreasToReset"

**Comment by v-xianya** [comment]
Verified this issue on build master/ 20200327.2. Fixd.
