### ISSUE TITLE
The 'Reset Column Order' action takes no effect when there no data available in table

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2334]
**Storage Explorer Version:** 1.11.0
**Build:** [20191126.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3273921)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Expand one storage account -> Tables.
3. Create a new table -> Click 'Column Options' -> Change the columns order.
4. Right click 'No data available in table' -> Click 'Reset Column Order'.
4. Check the results.

**Expect Experience:**
The 'Reset Column Order' action takes effect.

**Actual Experience:**
The 'Reset Column Order' action takes no effect.
![image](https://user-images.githubusercontent.com/54055206/69623196-61716800-107d-11ea-9625-bca2e0a4c928.png)
![image](https://user-images.githubusercontent.com/54055206/69623345-aac1b780-107d-11ea-9218-193e382769ef.png)

**Comment by MRayermannMSFT** [comment]
Edge case. Won't fix.
