### ISSUE TITLE
Azure Storage Explorer fails to create collection

### ISSUE THREAD

**Issue by daverozee** [microsoft/AzureStorageExplorer#2335]
**Storage Explorer Version**: 1.11.1
**Build Number**: 2019.1121.1
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  no

## Bug Description ##
The collection creation does not allow you to specify a partition key rendering the feature useless

## Steps to Reproduce ##
Create a collection in the UI

**Comment by southpolesteve** [comment]
The Cosmos team recently deprecated our integration with Azure Storage Explorer. [Here is the full deprecation notice from the 1.15.1 Storage Explorer release notes:](https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.15.1)

> The Azure Cosmos DB integration with Storage Explorer has been deprecated. Any existing functionality will not be removed for a minimum of one year from this release. Users should use the Azure Portal, the Azure Portal desktop app, or the standalone Cosmos Explorer instead – all of which contain many new features that aren’t currently supported in Storage Explorer. Additionally, the Azure Cosmos DB team has also open sourced the data explorer project and will be investing in their own desktop tooling at a later date. Please keep an eye on their repository for more information. 

Currently, we are not prioritizing new features or bug fixes for Cosmos in Azure Storage Explorer. If you the issue you are reporting also applies to the Azure Portal or https://cosmos.azure.com, please file an issue in [our open source Cosmos Explorer repo](https://github.com/Azure/cosmos-explorer)
