### ISSUE TITLE
Make AzCopy leverage existing SAS connections

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#2336]
Related to customer request #2325, #2291 

Current AzCopy requires read, write and list permission to perform data transactions. However, there are use cases where the user has write only permissions, or create only permissions. Customers want to be able to let AzCopy continue to work for them even if it would result in missing capabilities, such as overwrite protection and integrity checking.

**Comment by JasonYeMSFT** [comment]
Done by prompting a confirmation dialog for partially available permissions in the existing SAS token.

**Comment by MRayermannMSFT** [comment]
We need to do a better job of the access policy scenario.

**Comment by MRayermannMSFT** [comment]
We now provider a better experience when permissions are coming from an access policy.
