### ISSUE TITLE
Search doesn't return expected results when large number of partial matches exist

### ISSUE THREAD

**Issue by mtvessel** [microsoft/AzureStorageExplorer#2338]
**Storage Explorer Version**: 1.11.0
**Build Number**: 20191105.2
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  unknown

## Bug Description ##
Searching by prefix in a Data Lake Gen 1 account does not find files that exist and match supplied prefix.  It seems as if ASE only searches the first 1000 files, then gives up.  I have a large number of files that match a portion of the search prefix, but if my file isn't in the first 1000, it isn't found.  Ex: with 1000 files named xxx_000 through xxx_999, search by prefix cannot find a file named xxx_999a.

NOTE: This is my interpretation of the behavior, which may be incorrect.  What I can say with certainty is that not all existing files that match the supplied prefix are returned under all conditions.

## Steps to Reproduce ##
Have an ADLA Gen 1 storage account with > 1000 similarly named files.
Search for one that would be towards the end of the list, lexicographically sorted.

## Expected Experience ##
Any file that exists in the account, and matches the prefix should be returned.

## Actual Experience ##
Existing files that match the prefix are not returned under some conditions.

## Additional Context ##
Large number of potential prefix matches.

**Comment by jinglouMSFT** [comment]
The retirement of ADLS Gen1 is now less than three months away. As [previously announced](https://azure.microsoft.com/en-us/updates/action-required-switch-to-azure-data-lake-storage-gen2-by-29-february-2024/) the service will be retired on 29 February 2024. With this date now close approaching we are going to close this issue as "won't fix". Documentation on how to migrate your data to ADLS Gen2/blob storage can be found here: https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-migrate-gen1-to-gen2-azure-portal

If you have any non ADLS Gen1 feedback for Storage Explorer, please feel free to open a new issue: https://github.com/microsoft/AzureStorageExplorer/issues/new/choose

This issue will now no longer be monitored.
