### ISSUE TITLE
A11y_AzureToolsStorageExplorer_DesiredStorageExplorerTheme_ColorContrast: Several of the blue colored links and interactive elements fall below the minimum contrast ratios in dark theme.

### ISSUE THREAD

**Issue by Suraj1200499** [microsoft/AzureStorageExplorer#2339]
GitHubTags: #A11y_AzureToolsStorageExplorer; #A11yMAS; #A11YTCS; #DesktopApp; #MAS1.4.3; #ColorContrast; #Win32;  

**Environment Details:**
Application Name: Azure Tools Storage Explorer
Application Version: 1.11.0
Windows 10

**Repro Steps:**
1.Launch Storage Explorer
2. Navigate to  "View" menu and click on it.
3. Navigate to "Themes"and click on it 
4. Select dark theme. 
5. Navigate to "X" button in the "Search for resources" search field.
6. And also navigate to "Collapse All" and"Refresh All" buttons below the search field.
7. Verify that Color Contrast ratio is less than 4.5:1  for "X" button and "Collapse All","Refresh All" buttons and also for Several of the blue colored links and interactive elements.

**​Actual:​**
The "X" button has a contrast ratio of 2.454:1.
The "Collapse" and "Refresh" buttons have contrast ratios of 4.084:1

**Expected:**
Minimum contrast ratio of a non-text interactive element is 3:1.
Minimum contrast ratio of text is 4.5:1.

**UserImpact:**
Low vision users face difficulty to view the content if color contrast ratio is less than 4.5:1.

**Comment by MRayermannMSFT** [comment]
@Suraj1200499 : 
- for "Collapse All" and "Refresh All" I'm seeing a contrast ratio of 4.973:1, so as far as I can tell those do not need a change. The font color is #0097FB and background color is #252526.
- for the "X" in the search box, I agree that the color ratio is wrong too low for a UI component. I'll be updating the color of the "X" to #0097FB, which when on the background color of #333337, gives a ratio of 4.048:1, which matches the standard for UI components.
![image](https://user-images.githubusercontent.com/21112697/70100777-b23a1100-15e7-11ea-83b7-103f3cefe8ba.png)

**Comment by MRayermannMSFT** [comment]
The change to the icon has been merged into master.

**Comment by MRayermannMSFT** [comment]
@Radha2019 @Charanrajkb @nirmalsahoo @Suraj1200499 @vinodbk197

Please verify whether or not this bug was fixed to your satisfaction in the latest release of Storage Explorer. You can obtain that release from https://www.storageexplorer.com

If the bug has not been fixed to your satisfaction, please:
- Explain how did the fix not meet your expectations.
- Tell us exactly how we can meet your expectations. If there is more than one way to do so, feel free to list the different ways.

**Comment by Suraj1200499** [comment]
Verified this issue in Microsoft Azure Tools Storage Explorer Application Version: 1.12.0, this issue is no longer reproduced. Hence Closing the bug.
![2339_ColorContrast_Fixed](https://user-images.githubusercontent.com/55694920/73657137-ad610e80-46b7-11ea-9c02-2d3f102c5048.jpg)
![2339_ColorContrast1_Fixed](https://user-images.githubusercontent.com/55694920/73657139-ad610e80-46b7-11ea-920e-66bfca82131e.jpg)

**Comment by fsteffi** [comment]
GithubTags:#Closed;

**Comment by mstechie** [comment]
GitHubTags:#BM-TCS-StorageExplorer-Win32-Sep2019;
