### ISSUE TITLE
Delete confirmation

### ISSUE THREAD

**Issue by kiased** [microsoft/AzureStorageExplorer#234]
**Storage Explorer Version**: Version: 1.1.0
**Platform**: Windows 10
**Architecture**: 
**Regression From**: 

#### Steps to Reproduce: ####
1. When deleting Cosmos DB collection from Azure portal, we will be prompted for collection name. However in Azure explorer it's not happening. 
2. Add new feature to ask Cosmos DB collection Name, or Data base name when deleting. Just like Azure portal. This will reduce the risk of unintentional removal of components.

#### Expected Experience: ####
Add new feature to ask Cosmos DB collection Name, or Data base name when deleting. Just like Azure portal. This will reduce the risk of unintentional removal of components.

**Comment by jinglouMSFT** [comment]
CosmosDB has been removed from Storage Explorer.
