### ISSUE TITLE
The warning message is not localized on Connect dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2341]
**Storage Explorer Version:** 1.11.0
**Build:** [20191127.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3277410&view=results)
**Branch:** master
**Language:** Chinese(zh-CN) / Chinese(zh-TW)
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Chinese (simplified)' -> Restart Storage Explorer.
3. Open Connect dialog -> Select 'Use a connection string' -> Input an arbitrary string to  'Connections string' text box.
4. Check the warning message.

**Expect Experience:**
The warning message is localized.

**Actual Experience:**
The warning message is not localized.
![image](https://user-images.githubusercontent.com/41351993/69710053-7963de80-10b3-11ea-9b00-03c261eb877c.png)

**More Info:**
This issue also reproduces when selecting 'Use a shared access signature (SAS) URI.' 
![image](https://user-images.githubusercontent.com/41351993/69710079-854fa080-10b3-11ea-89a7-972afcc8c21b.png)

**Comment by lukaschal** [comment]
@craxal Looks like hard-coded strings.

https://github.com/ramramu3433/study_aws_azure_jenkins_docker/blob/e61373d7ce1dd1ad4729c28f4417931311bfcf3b/Files_tutor_azure_jmter/azurest/resources/app/out/app/renderer/Components/AzureStorage/ConnectionString/Validators/ConnectionStringValidator.js

https://github.com/ramramu3433/study_aws_azure_jenkins_docker/blob/e61373d7ce1dd1ad4729c28f4417931311bfcf3b/Files_tutor_azure_jmter/azurest/resources/app/out/app/renderer/Components/AzureStorage/Sas/Validators/SasTokenValidator.js

**Comment by v-limu** [comment]
**More Info:**
The expired warning message also isn't localized.
![image](https://user-images.githubusercontent.com/54055206/69857483-092fa580-12cb-11ea-99b5-83924568d85f.png)
![image](https://user-images.githubusercontent.com/54055206/69855734-1cd90d00-12c7-11ea-916a-18fe768fa6ab.png)

**Comment by v-limu** [comment]
**More Info:**
The invalid resource warning message also isn't localized.
![image](https://user-images.githubusercontent.com/54055206/70612934-c95dac00-1c42-11ea-9caf-17f84f56d4ac.png)
![image](https://user-images.githubusercontent.com/54055206/70612941-cbc00600-1c42-11ea-963e-140261e4409a.png)

**Comment by craxal** [comment]
@v-limu I think this was addressed alongside #2185. Wait for localization team to translate the error strings, then verify.

**Comment by v-limu** [comment]
Verified on build [20200327.2.](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3588105) This issue has been fixed. So we close it.
