### ISSUE TITLE
'Query string' is no localized on Generate Shared Access Signature dialog in zh-TW

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2342]
**Storage Explorer Version:** 1.11.0
**Build:** [20191127.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3277410&view=results)
**Branch:** master
**Language:** Chinese(zh-TW) 
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Chinese (simplified)' -> Restart Storage Explorer.
3. Select one storage account -> Select 'Get Share Access Signature...' -> Click 'Create'.
4. Check the dialog.

**Expect Experience:**
All strings are localized.

**Actual Experience:**
'Query string' is no localized.
![image](https://user-images.githubusercontent.com/41351993/69710601-8cc37980-10b4-11ea-8cda-786217b390ba.png)

**More Info:**
1. This issue also reproduces for one blob container/ file share/ queue/ table.
2. This issue doesn't reproduce in zh-CN.

**Comment by lukaschal** [comment]
Localized today.

File: loc\en\src\Standalone\resources\GenerateSasDialog.json
ID: 0; "SasQueryStringLabel"
SRC: Query string:
TGT: 查詢字串:

**Comment by v-xianya** [comment]
This issue has been fixed on build master/20191128.5.  Close it.
![image](https://user-images.githubusercontent.com/41351993/69839010-b7bfe180-120a-11ea-9c6f-b0d9d49e7c48.png)
