### ISSUE TITLE
The values of permission are not localized on Connection Summary dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2343]
**Storage Explorer Version:** 1.11.0
**Build:** [20191127.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3277410&view=results)
**Branch:** master
**Language:** Chinese(zh-CN) /Chinese(zh-TW)
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Chinese (simplified)' -> Restart Storage Explorer.
3. Get  'Share Access Signature' of one storage account and Copy it.
4. Open Connect dialog -> Select 'Using a connection string' -> Next -> Paste the Copied URI to Connection string text box -> Next.
4. Check the Connection Summary dialog.

**Expect Experience:**
The values of permission are localized.

**Actual Experience:**
The values of permission are not localized.
![image](https://user-images.githubusercontent.com/41351993/69711705-5d157100-10b6-11ea-808d-747f04d7a481.png)

**Comment by lukaschal** [comment]
@craxal Is this string exposed to localization ?

**Comment by JasonYeMSFT** [comment]
Portal has translated these permissions' strings. We should expose them for localization.

**Comment by MRayermannMSFT** [comment]
Moving to 1.14 for full verification then.
