### ISSUE TITLE
Focus color not covered all focused background on CORS Settings after selecting rules

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2344]
**Storage Explorer Version:** 1.11.0
**Build:** [20191127.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3277410&view=results)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Expand one storage account -> Right click the File Shares node.
3. Select 'Configure CORS Settings...' -> Add one CORS rule and save it.
4. Focus the new added rule and check the focus color.

**Expect Experience:**
Focus color covered all focused background.

**Actual Experience:**
Focus color not covered all focused background.
![image](https://user-images.githubusercontent.com/41351993/69712578-eed1ae00-10b7-11ea-8ed3-7c02302fba95.png)

**More Info:**
1. This issue also reproduces for one Blob Containers/ Queues/ Tables.

**Comment by MRayermannMSFT** [comment]
By design. That area is reserved for the scroll bar.
