### ISSUE TITLE
The word 'folder' is not localized when trying to selecting folder to upload

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2345]
**Storage Explorer Version:** 1.11.0
**Build:** [20191127.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3277410&view=results)
**Branch:** master
**Language:** Czech/ German/ Spanish/ French/ Hungarian/ Italian/ Japanese/ Korean/ Dutch/ Polish/ Portuguese(pt-BR)/ Portuguese(pt-PT)/ Russian/ Swedish/ Turkish/ Chinese(zh-CN) / Chinese (zh-TW)
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Chinese (simplified)' -> Restart Storage Explorer.
3. Expand one storage account -> Blob Containers -> Create one blob container.
4. Click Upload -> Upload Folder... -> Click '...' button on upload dialog.
5. Check the title of the prompt dialog.

**Expect Experience:**
The word 'folder' is localized.

**Actual Experience:**
The word 'folder' is not localized.

![image](https://user-images.githubusercontent.com/41351993/69713825-132e8a00-10ba-11ea-83f3-52506f42accb.png)

**More Info:**
1. This issue is also reproduces when upload files.
![image](https://user-images.githubusercontent.com/41351993/69713819-0f9b0300-10ba-11ea-8856-eb875f6af9e8.png)

2. This issue doesn't reproduce for one file share.
![image](https://user-images.githubusercontent.com/41351993/69713758-ef6b4400-10b9-11ea-979a-514e22f6c551.png)

**Comment by lukaschal** [comment]
@craxal Probably coresponds to this resource. Text "files" and "folders" is represented by "%s". Are these exposed to localization?

File: loc\en\src\components\se-az-copy-extension\resources\UploadBlobsDlg.json
ID: 0; "ChooseUploadTypeToUpload"
SRC: Choose %s to upload
TGT: 选择要上传的 %s

**Comment by v-xianya** [comment]
Verified this issue on the latest build 20200206.2.
This issue aslo reproduces for one file share.
![image](https://user-images.githubusercontent.com/41351993/73916184-e8ea1b80-48f7-11ea-9d52-8a40fed978d5.png)

**Comment by v-limu** [comment]
Verified on build 20200327.2. This issue has been fixed. So we close it.
