### ISSUE TITLE
The 'Create Snapshot' isn't localized after creating one new file share of one SAS storage account

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2346]
**Storage Explorer Version:** 1.11.0
**Build:** [20191127.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3277410)
**Branch:** master
**Language:** Chinese(zh-CN) /Chinese(zh-TW)
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Chinese (simplified)' -> Restart Storage Explorer.
3. Select one storage account -> Use SAS to attach the storage account.
4. Expand **Local & Attached** -> Create a new file share under the sas storage account .
5. Check the context menu.

**Expect Experience:**
All actions are localized.

**Actual Experience:**
The 'Create Snapshot' isn't localized.
![image](https://user-images.githubusercontent.com/54055206/69714765-03f31f00-1142-11ea-9370-f06d236e3bf1.png)

**More Info:**
This issue doesn't reproduce after refreshing File Shares.

**Comment by lukaschal** [comment]
All instances of "Create Snapshot" are localized.

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer?_a=annotate&path=%2Floc%2Floc%2Fzh-Hans%2Fsrc%2Fcomponents%2Fse-managed-disks-extension%2Fresources%2FManagedDisksExplorer.json.lcl&version=GBmaster

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer?path=%2Floc%2Floc%2Fzh-Hans%2Fsrc%2Fcomponents%2Fse-adls2-extension%2Fresources%2FFileSystemEditor.json.lcl&version=GBmaster

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer?path=%2Floc%2Floc%2Fzh-Hans%2Fsrc%2Fcomponents%2Fse-managed-disks-extension%2Fresources%2FCreateSnapshotDialog.json.lcl&version=GBmaster

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer?path=%2Floc%2Floc%2Fzh-Hans%2Fsrc%2Fcomponents%2Fse-blob-extension%2Fresources%2FBlobEditor.json.lcl&version=GBmaster

0; "ToolbarCreateSnapshot"
0; "Title"
0; "Toolbar.CreateSnapshotCommandName"
0; "Toolbar.CreateSnapshotCommandDescription"
0; "Toolbar.CreateSnapshotCommandName"
0; "Toolbar.CreateSnapshotCommandDescription"
0; "ActionCreateFileShareSnapshot"

**Comment by v-xianya** [comment]
This issue has been fixed on build [20200229.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3514328). So we close it.
