### ISSUE TITLE
The activity log is too long in Activities after pasting one deleted blob

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2347]
**Storage Explorer Version:** 1.11.0
**Build:** [20191127.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3277410)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Expand one storage account -> Blob Containers.
3. Create a new blob container -> Upload a blob to it -> Copy this blob -> Delete the **blob container**.
4. Paste the blob to another blob container.
5. Check the Activities.

**Expect Experience:**
The activity log is concise.
![image](https://user-images.githubusercontent.com/54055206/69715049-8a0f6580-1142-11ea-90a5-ffe705b90f57.png)

**Actual Experience:**
The activity log is too long.
![image](https://user-images.githubusercontent.com/54055206/69715041-867bde80-1142-11ea-921b-d6c17c1d8152.png)

**Comment by MRayermannMSFT** [comment]
Won't fix. Error is coming from azcopy and describes the error correctly.
