### ISSUE TITLE
The path information of the snapshot under one blob  isn't localized

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2348]
**Storage Explorer Version:** 1.11.0
**Build:** [20191127.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3277410)
**Branch:** master
**Language:** Chinese(zh-CN) /Chinese(zh-TW)
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Chinese (simplified)' -> Restart Storage Explorer.
3. Expand one storage account -> Blob Containers.
4. Create a new blob container -> Upload a blob to it -> Create snapshot for the blob.
5. Manage Snapshots for the blob -> Check the path information on editor.

**Expect Experience:**
The path information is localized.

**Actual Experience:**
The path information isn't localized.
![image](https://user-images.githubusercontent.com/54055206/69714576-9810b680-1141-11ea-9096-0c5d02d9bb15.png)

**More Info:**
This issue also reproduces for one file under one file share.

**Comment by lukaschal** [comment]
@craxal Is this exposed to localization?

**Comment by v-limu** [comment]
This issue also reproduces in **Japanese**.
![image](https://user-images.githubusercontent.com/54055206/71237602-f134ca00-233c-11ea-9a32-b433258a8cf0.png)

**Comment by v-limu** [comment]
Verified on build [20200319.10](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3566615). The path information of the snapshot for one blob has been fixed. **This issue still reproduces for the files under one file share.**
![image](https://user-images.githubusercontent.com/54055206/77139301-6afd6080-6ab0-11ea-9277-25b4fe2a866a.png)

**Comment by craxal** [comment]
@lukaschal This was moved to Translating a week ago. Have translators checked in an translations yet?

**Comment by lukaschal** [comment]
@craxal  Localized at 3/20/2020.

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer/commit/dcf01f94fd9d179b4ca0525ec5b0ef420318672e?_a=compare&path=%2Floc%2Floc%2Fit%2Fsrc%2FStandalone%2Fresources%2FAzure.json.lcl

File: loc\en\src\Standalone\resources\Azure.json
ID: 0; "PrefixSnapshotsFor"
SRC: Snapshots for '%1$s'
TGT: Snapshot per '%1$s'

**Comment by v-xianya** [comment]
Verified this issue on build master/ [20200324.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3577314). 
1. The word **Snapshots** is not localized in the path information of the snapshot for one **file share**.
![image](https://user-images.githubusercontent.com/41351993/77384930-a2765080-6dc1-11ea-9633-15234c2a027d.png)

**Comment by craxal** [comment]
@v-xainya We likely haven't updated the Cloud Explorer reference in Storage Explorer for the above build. Verify on a newer build.

**Comment by v-xianya** [comment]
@craxal The above issue still reproduces on build 20200324.12. 
And we will verify on a newer build. Thanks for your updates.

**Comment by MRayermannMSFT** [comment]
Moving to 1.14 for full verification then.

**Comment by v-xianya** [comment]
Verified this issue on build 20200627.2. 
The word **Snapshots** is not localized in the path information of the snapshot for one file share. So we re-open it.
![image](https://user-images.githubusercontent.com/41351993/85981520-e4dda800-ba16-11ea-87e0-1c519067bdce.png)

**Comment by craxal** [comment]
With the implementation of editable address bars, the current state of the code doesn't easily allow us to display "Snapshots for ...". Investigating potential solutions.

**Comment by v-xianya** [comment]
Verified this issue on build master/20200807.6. Fixed.
