### ISSUE TITLE
The notification of the 'Target Azure Stack APIs' isn't localized

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2349]
**Storage Explorer Version:** 1.11.0
**Build:** [20191127.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3277410)
**Branch:** master
**Language:** Chinese(zh-CN) /Chinese(zh-TW)
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Chinese (simplified)' -> Restart Storage Explorer.
3. Edit -> Click 'Target Azure Stack APIs'.
4. Check the result.

**Expect Experience:**
The notification is localized.

**Actual Experience:**
The notification isn't localized.
![image](https://user-images.githubusercontent.com/54055206/69715115-ac08e800-1142-11ea-95a2-f6fe8250c020.png)

**Comment by lukaschal** [comment]
Hard-coded strings.

    private showRestartPrompt(newVersion: string) {
        var message = "Storage Explorer must restart for the changes to take effect.";
        var link = "Restart Now";
        var closeText = "Cancel Changes";

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer?path=%2Fsrc%2FStandalone%2Fapp%2Frenderer%2FStorageApiSettingManager.ts&version=GBmaster

**Comment by v-limu** [comment]
This issue also reproduces in **Japanese**.
![image](https://user-images.githubusercontent.com/54055206/71237201-dca40200-233b-11ea-9063-c00a40063fd0.png)

**Comment by lukaschal** [comment]
On translation now.

File: loc\en\src\Standalone\resources\Shell.json
ID: 0; "MessageRestartPrompt"
SRC: Storage Explorer must restart for the changes to take effect.

**Comment by JasonYeMSFT** [comment]
@v-limu The strings have been translated, please verify.

**Comment by v-limu** [comment]
Verified on build 20200317.2. This issue has been fixed. So we close it.
