### ISSUE TITLE
Unexpected unsupported file name dialog

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#235]
**Storage Explorer Version**: 1.2.0
**Platform**: Windows
**Architecture**: win32
**Regression From**: Unknown

#### Steps to Reproduce: ####
1. Go to StorageExplorer/coolstorageencrypted/encrypted
2. Navigate into .vscode
3. Double click on tasks.json

#### Expected Experience: ####
tasks.json just opens up

#### Actual Experience: ####
I get an encoded file name dialog, with the filename having a giant GUID in it:
![image](https://user-images.githubusercontent.com/21112697/40808590-85186bda-64dc-11e8-944a-06302fda8a8d.png)

**Comment by v-xuanzh** [comment]
Verified this issue on latest rel/1.9.0 build 20190628.4, still reproduces.
