### ISSUE TITLE
Support Azure Data Lake Gen 2

### ISSUE THREAD

**Issue by dahatake** [microsoft/AzureStorageExplorer#2351]
**Describe the solution you'd like**
During Data processing with Storage Explore is the best tool to secure share data in Data Lake Storage. It dramatically reduce to Deep Learning process especially early phase of project.

**Describe alternatives you've considered**
None. Some senario, don't use Azure Data Lake Gen 2 because GUI tools is missing.

**Comment by MRayermannMSFT** [comment]
@dahatake can you elaborate on what scenarios you would like to see supported?

**Comment by dahatake** [comment]
Thank you.
I misunderstood of current Storage Explorer. I found it already supported.
Let's cancel this request.
