### ISSUE TITLE
Show an incorrect punctuation on Add Message dialog in zh-TW

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2353]
**Storage Explorer Version:** 1.11.0
**Build:** [20191128.5](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3281845)
**Branch:** master
**Language:** Chinese(zh-TW)
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '繁體中文' -> Restart Storage Explorer.
3. Expand a storage account -> Queues.
4. Create a new queue -> Click 'Add Message'.
5. Check the punctuation next to local 'Expires in' on the prompt dialog.

**Expect Experience:**
Show an correct punctuation ':'.

**Actual Experience:**
Show an incorrect punctuation '::'.
![image](https://user-images.githubusercontent.com/41351993/69851876-a3460e00-1237-11ea-90d4-98c13ff50f01.png)

**More Info:**
1. ENU screenshot
![image](https://user-images.githubusercontent.com/41351993/69851920-c07adc80-1237-11ea-8051-305d49736a63.png)

2. zh-CN screenshot
![image](https://user-images.githubusercontent.com/41351993/69851928-c53f9080-1237-11ea-8d26-d2dfed9ec417.png)

**Comment by lukaschal** [comment]
Fixed.

File: loc\en\src\Standalone\resources\AddMessageDialog.json
ID: 0; "LabelExpiresIn"
SRC: Expires in
TGT: 有效期限

**Comment by v-xianya** [comment]
Verified this issue on build 20191130.1. Fixed. So we close it.
![image](https://user-images.githubusercontent.com/41351993/69933666-5e62e700-1484-11ea-8194-696ef84c7d49.png)

**Comment by v-xianya** [comment]
This issue has been fixed on 3 platforms. So close it.
