### ISSUE TITLE
It is better to add a quantifier in the localized table Statistics log message

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2354]
**Storage Explorer Version:** 1.11.0
**Build:** [20191128.5](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3281845)
**Branch:** master
**Language:** Chinese(zh-CN)
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文(简体)' -> Restart Storage Explorer.
3. Expand a storage account -> Tables.
4. Create a new table -> Add an entity -> Click 'Table Statistics'.
5. Check the activity log.

**Expect Experience:**
Show a quantifier in the activity log. (**1个实体**)

**Actual Experience:**
No quantifier in the activity log. 
![image](https://user-images.githubusercontent.com/41351993/69853202-09806000-123b-11ea-9c4a-a31a4338cbff.png)

**More Info:**
1. ENU screenshot
![image](https://user-images.githubusercontent.com/41351993/69853291-53694600-123b-11ea-96b9-5cfc41c8b85c.png)

2. zh-TW screenshot
![image](https://user-images.githubusercontent.com/41351993/69853283-4e0bfb80-123b-11ea-9023-53d8c367b162.png)

**Comment by lukaschal** [comment]
On review.

**Comment by johnliu2016** [comment]
Fixed as suggested

**Comment by v-xianya** [comment]
This issue has been fixed. So we close it.
![image](https://user-images.githubusercontent.com/41351993/70209971-82684600-176c-11ea-946f-4399f90714af.png)
