### ISSUE TITLE
The notification is not localized on CORS Settings dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2355]
**Storage Explorer Version:** 1.11.0
**Build:** [20191128.5](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3281845)
**Branch:** master
**Language:** Chinese(zh-CN)/Chinese(zh-TW)
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文(简体)' -> Restart Storage Explorer.
3. Expand a storage account -> Right click File Shares node -> Click '配置CORS 设置...'.
4. Click '添加' on the CORS Settings dialog.
5. Input 'e' / '-1' to ‘最长使用时间’ textbox -> Hover over the textbox then check the notification.

**Expect Experience:**
The notification is localized.

**Actual Experience:**
The notification is not localized.
![image](https://user-images.githubusercontent.com/41351993/69856362-53207900-1242-11ea-80b6-f372fb354eed.png)
![image](https://user-images.githubusercontent.com/41351993/69856370-561b6980-1242-11ea-83b3-8ba0543ff020.png)

**Comment by lukaschal** [comment]
@craxal Is this exposed to loc ?

**Comment by jinglouMSFT** [comment]
We actually have no control of these strings as they are from the external component.  These are very very edge case.  The ROI for fixing isn't worthy the attempt.  Won't fix for now.
