### ISSUE TITLE
'(Emulator - Default Ports)(Key)' shows broken when adding it to Quick Access in zh-CN/zh-TW

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2356]
**Storage Explorer Version:** 1.11.0
**Build:** [20191128.5](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3281845&view=results)
**Branch:** master
**Language:** Chinese(zh-TW)/ Chinese(zh-CN)
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select Chinese(traditional) -> Restart Storage Explorer.
3. Expand **Local & Attached** -> Storage Accounts -> Add '(Emulator - Default Ports)(Key)' to Quick Access .
4. Check the result.

**Expect Experience:**
The localized '(Emulator - Default Ports)(Key)' shows well.

**Actual Experience:**
1. The localized '(Emulator - Default Ports)(Key)' shows broken.
2. '(Emulator - Default Ports)(Key)' **isn't localized**.
![image](https://user-images.githubusercontent.com/54055206/69854876-2b262980-12c5-11ea-8b1d-9ec6a0865053.png)

**More Info:**
The '(Emulator - Default Ports)(Key)' shows well in English.
![image](https://user-images.githubusercontent.com/54055206/69857305-ab9b5900-12ca-11ea-9aca-21e0bdc65763.png)

**Comment by lukaschal** [comment]
"(key)" not occurs in localizable StorageExplorer resources for now.

**Comment by JasonYeMSFT** [comment]
The `(Key)` is not supposed to be localized. The broken node is a bug that we need to fix.
