### ISSUE TITLE
When switching between Cosmos DB tabs, the editor is not repainted and appears blank

### ISSUE THREAD

**Issue by thomaslevesque** [microsoft/AzureStorageExplorer#2357]
**Storage Explorer Version**: 1.11.1
**Build Number**: 20191121.1
**Platform/OS**: Windows 10
**Architecture**: ia32
**Regression From**:  Not sure. It started happening a while ago (a few weeks, maybe months), and seems to have gotten worse

## Bug Description ##
When switching between tabs, the editor contents is not repainted and appears blank. Resizing the editor makes it reappear, but I have to do it almost every time I switch tabs.

## Steps to Reproduce ##
1. Connect to a Cosmos DB database
2. Open a documents tab and select a document
3. Open a query tab
4. Switch between the tabs

## Expected Experience ##
The document and query editors should appear normally when switching tabs

## Actual Experience ##
The editor appears blank after switching tabs:

![image](https://user-images.githubusercontent.com/1864281/69866037-46803d00-12a3-11ea-8d63-2dc7d46857f9.png)

Along with [this other bug](https://github.com/Microsoft/AzureStorageExplorer/issues/695), it makes the app almost unusable...

**Comment by mjgabriel** [comment]
As a workaround I drag the bar to resize the query and result windows and the windows redraw themselves. It's a very frustrating thing to deal with when using this app.

Same platform as OP

Platform/OS: Windows 10
Architecture: ia32

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
