### ISSUE TITLE
Unable to browse ADLS2 in versions 1.10.1 an newer

### ISSUE THREAD

**Issue by Sokon77** [microsoft/AzureStorageExplorer#2358]
1. Open ASE, Authenticate, select a subscription and a storage account
2. Open nodes for Files, Queues, Tables, even regular Blobs: Everything works fine, contents are listed.
3. Open a "blob" node that containes a ADLS2: Depending on the version and the proxy settings, different errors appear:

- v1.10.1, empty proxy settings: "The requested action could not be completed. request to <URL failed, reason: read ECONNRESET>
- v1.10.1, working proxy settings: "Unable to retrieve child resources [...] reason: tunneling socket could not be established, cause getaddrinfo ENOTFOUND"
- v1.11.1 empty proxy settings: Browsing the contents does work, Download/upload commands stay at 0.0Mbps and never finish
- v1.11.1, working proxy settings: "Unable to retrieve child resources [...] reason: tunneling socket could not be established, cause getaddrinfo ENOTFOUND"

More information:
- A proxy is involved which is the most likely cause for the problem: However: The very same proxy settings do work in v1.9.0, and besides ADLS2 all other sources are reachable.
- Conditional Access is used in our company, however, as said, v1.9.0 does work and we are running ASE on a Win2k16-Server inside the company network
- we couldn't find the issue by reading the troubleshooting page.

We can'T switch to newer versions of ASE because it would mean to be locked out of the Data Lake. Please fix! :-)

**Comment by MRayermannMSFT** [comment]
@Sokon77 can you tell us more about the proxy your company is using? Specifically any information that would help us set up an equivalent proxy.

**Comment by MRayermannMSFT** [comment]
Also, @Sokon77 , when you're testing "empty proxy settings" vs "working proxy settings", are you restarting Storage Explorer in between changing settings?

**Comment by Sokon77** [comment]
> Also, @Sokon77 , when you're testing "empty proxy settings" vs "working proxy settings", are you restarting Storage Explorer in between changing settings?

Yes i keep closing and reopening ASE every time i change settings. And I tried it more then 10 times so I'm pretty sure that at least once i would have done it correctly.

Concerning the proxy information: I'll post it as soon as I get the information myself.

**Comment by MRayermannMSFT** [comment]
Hi @Sokon77 , would you be open to doing a customer call with us? Our SDK team would like to do some debugging locally on your machine. If yes, do you have a screen sharing software you are comfortable with? Thanks!

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. A proxy fix for gen2 was shipped in 1.12.0. This should be fixed. Please open a new issue if you continue to have problems.
