### ISSUE TITLE
Unspported file name dialog has no default option, and it treats closing as "Yes encode"

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#236]
**Storage Explorer Version**: 1.2.0
**Platform**: Windows
**Architecture**: win32
**Regression From**: Unknown

#### Steps to Reproduce: ####
1. Go to StorageExplorer/coolstorageencrypted/encrypted
2. Navigate into .vscode
3. Double click on tasks.json
4. Observe the unsupported filename dialog appearing
![image](https://user-images.githubusercontent.com/21112697/40808590-85186bda-64dc-11e8-944a-06302fda8a8d.png)
5. Close the dialog

#### Expected Experience: ####
Closing the dialog should not continue with the download.

#### Actual Experience: ####
After step 4, I noticed that there was no default radio button selected. Also, after step 5, it opened the file anyways.

**Comment by v-xuanzh** [comment]
This issue still reproduces on the latest rel/1.9.0 build 20190628.4.
