### ISSUE TITLE
Gen2 Quick Access

### ISSUE THREAD

**Issue by v-canjoh** [microsoft/AzureStorageExplorer#2361]
**Is your feature request related to a problem? Please describe.**
It is difficult to get to attached Blob Containers, since you have to navigate:
Local & Attached => Storage Accounts => (Attached Containers) => Blob Containers => my_attached_container. It's easy to get lost in the clicking and would be better if it was easier to get to.

**Describe the solution you'd like**
It would be immensely useful to be able to put the attached blob container into the quick access menu or have a pinned items/favorites section to place these in.

**Comment by jinglouMSFT** [comment]
You should be able to do that by right-clicking on the individual blob container and select Add to Quick Access. 
![image](https://user-images.githubusercontent.com/10081483/70012361-18139380-1529-11ea-95de-0d90b2020eb1.png)

Did you run into any problems doing so?

**Comment by canjoh** [comment]
There appears to be no option in the right click menu:
![image](https://user-images.githubusercontent.com/53024178/70074318-52277880-15af-11ea-893a-0fb3ff512067.png)

I'm on ASE 1.11.1.

**Comment by jinglouMSFT** [comment]
Ah, it's ADLS Gen2 at the container level.  This is currently not implemented.  Adding to Quick Access for ADLS gen2 is only supported at the account level right now, not at the individual container level yet.

**Comment by canjoh** [comment]
Do you have an idea as to when it might be implemented?

**Comment by jinglouMSFT** [comment]
No, not at the moment.  We will need to prioritize this together with other customer requests.

**Comment by JasonYeMSFT** [comment]
The work for this feature has been merged.
