### ISSUE TITLE
No '…' shows next to 'Break Lease & Change Access Tier' for ADLS Gen2 blobs in Chinese

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2364]
**Storage Explorer Version:** 1.11.1
**Build:** [20191203.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3288089)
**Branch:** master
**Language:** Chinese(zh-CN) / Chinese(zh-TW)
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文 (简体)' -> Restart Storage Explorer.
3. Expand an ADLS Gen2 account -> Blob Containers.
4. Create a new blob container -> Upload a blob.
5. Check the localized actions 'Break Lease & Change Access Tier' on context menu.

**Expect Experience:**
Shows '...' next to 'Break Lease & Change Access Tier'.

**Actual Experience:**
No '…' shows next to 'Break Lease & Change Access Tier'.
![image](https://user-images.githubusercontent.com/41351993/70034285-e1528180-15eb-11ea-9a80-383efb685822.png)

**More Info:**
ENU screenshot:
![image](https://user-images.githubusercontent.com/41351993/70034902-e6fc9700-15ec-11ea-8114-6ccb304b8c6c.png)

**Comment by lukaschal** [comment]
<Val><![CDATA[Change Access Tier...]]></Val>
          <Tgt Cat="Text" Stat="Loc" Orig="New">
            <Val><![CDATA[更改访问权限层...]]></Val>

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer?path=%2Floc%2Floc%2Fzh-Hans%2Fsrc%2Fcomponents%2Fse-adls2-extension%2Fresources%2FFileSystemEditor.json.lcl&version=GBmaster


https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer?path=%2Floc%2Floc%2Fzh-Hans%2Fsrc%2Fcomponents%2Fse-blob-extension%2Fresources%2FBlobEditor.json.lcl&version=GBmaster


          <Val><![CDATA[Break Lease...]]></Val>
          <Tgt Cat="Text" Stat="Loc" Orig="New">
            <Val><![CDATA[中断租约...]]></Val>



https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer?path=%2Floc%2Floc%2Fzh-Hans%2Fsrc%2Fcomponents%2Fse-blob-extension%2Fresources%2FBlobEditor.json.lcl&version=GBmaster

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer?path=%2Floc%2Floc%2Fzh-Hans%2Fsrc%2Fcomponents%2Fse-adls2-extension%2Fresources%2FFileSystemEditor.json.lcl&version=GBmaster

**Comment by v-xianya** [comment]
This issue has been fixed on build 20191205.1. So we close it.
