### ISSUE TITLE
It is better to translate 'Break Container Lease' to '中斷容器租用' in zh-TW

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2365]
**Storage Explorer Version:** 1.11.1
**Build:** [20191203.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3288089)
**Branch:** master
**Language:** Chinese(zh-TW)
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '繁體中文' -> Restart Storage Explorer.
3. Expand one storage account -> Blob Containers.
4. Create a blob container -> Acquire lease for it.
5. Right click the leased blob container -> Select '中斷租用'.
6. Check the title of the prompt dialog.

**Expect Experience:**
Show '中斷容器租用'.

**Actual Experience:**
Show '中止容器租用'.
![image](https://user-images.githubusercontent.com/41351993/70036259-5ecbc100-15ef-11ea-8626-c6095fe3ec6a.png)

**Comment by lukaschal** [comment]
On review.

File: loc\en\src\Standalone\resources\Azure.json
ID: 0; "TitleContainerLeaseBreak"
SRC: Break Container Lease
TGT: 中止容器租用

**Comment by johnliu2016** [comment]
Implemented suggestion.

**Comment by craxal** [comment]
@johnliu2016 Is this change checked in yet? I don't see any changes to zh-Hant/Azure.json yet. To be clear, we're changing `TitleContainerLeaseBreak` tp "中斷容器租用", yes?

**Comment by johnliu2016** [comment]
@craxal, the translation is changed to '中斷容器租用', please expect it in newer build, it's through loc pipeline.

**Comment by v-limu** [comment]
This issue has been fixed on build [20191212.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3315517). So we close it.
