### ISSUE TITLE
Show an odd page when selecting 'Add New Environment' in Custom Environments dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2366]
**Storage Explorer Version:** 1.11.1
**Build:** [20191203.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3288089)
**Branch:** master
**Language:** Chinese(zh-CN)/ Chinese(zh-TW)
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文(简体)' -> Restart Storage Explorer.
3. Open connect dialog -> Select 'Add New Environment' -> Click 'Next'.
4. Type the environment name and ARM endpoint -> Click 'Next' .
5. Enter the credentials for an azure account.
6. Open connect dialog -> Select 'Use Custom Environment' option -> Click 'Next'.
7. Select 'Add New Environment' in Environment dropdown list.
8.  Check the result.

**Expect Experience:**
Show a right page.

ENU screenshot:
![image](https://user-images.githubusercontent.com/41351993/70036814-75bee300-15f0-11ea-9d94-8e3b4ab52caa.png)

**Actual Experience:**
Show an odd page.
![image](https://user-images.githubusercontent.com/41351993/70038727-b4a26800-15f3-11ea-830f-eecf459971e2.png)

**More Info:**
This issue also reproduces when deleting one environment.(Make sure there only one environment exists)

**Comment by MRayermannMSFT** [comment]
Fix checked into master
