### ISSUE TITLE
Update 'Choose' to 'Select' in the prompt window title when selecting folder to upload

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2367]
**Storage Explorer Version:** 1.11.1
**Build:** [20191203.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3288089)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Created one blob container -> Click 'Upload' (Upload Folder...).
3. Click '...' -> Check the prompt window title.

**Expect Experience:**
Show 'Select folder to upload'.

**Actual Experience:**
Show 'Choose folder to upload'.
![image](https://user-images.githubusercontent.com/41351993/70040342-5aef6d00-15f6-11ea-822d-8169d597ecd0.png)

**More Info:**
1. This issue also reproduces when uploading files to one blob container.
2. This issue doesn't reproduce for one file share.
![image](https://user-images.githubusercontent.com/41351993/70040530-abff6100-15f6-11ea-892c-a932322a0a5b.png)

**Comment by MRayermannMSFT** [comment]
Won't fix
