### ISSUE TITLE
Update 'Upload Files' to 'Upload Folder' in the Upload dialog title

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2368]
**Storage Explorer Version:** 1.11.1
**Build:** [20191203.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3288089)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> File Shares.
2. Open one file share -> Click 'Upload' (Upload Folder...).
3. Check the prompt dialog's title.

**Expect Experience:**
Show 'Upload Folder to File Share'.

**Actual Experience:**
Show 'Upload Files to File Share'.
![image](https://user-images.githubusercontent.com/41351993/70041584-680d5b80-15f8-11ea-8f83-b5851d21beaf.png)

**Comment by v-limu** [comment]
This issue has been fixed on build [20191220.9](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3338616&view=results). So we close it.
![image](https://user-images.githubusercontent.com/54055206/71573086-0a97fc00-2b1d-11ea-8b15-eb7adb74b5d1.png)
