### ISSUE TITLE
Issues signing into Storage Explorer when using MFA

### ISSUE THREAD

**Issue by terminic** [microsoft/AzureStorageExplorer#2370]
When I try to authenticate to pull up Storage Resources I get the following error when signing in while using MFA.  
{
  "message": "\"User 'Chris.Termini@microsoft.com' returned by service does not match user 'chterm@microsoft.com' in the request\""
}

**Comment by schneidenbach** [comment]
I had the exact same issue - the fix for me was enabling the MS Auth preview feature (quoted directly from [here](https://github.com/microsoft/AzureStorageExplorer/issues/1123#issuecomment-553010572), via @MRayermannMSFT):

> To enable the new auth library, go to Settings (gear icon) -> Application -> Sign-in -> Microsoft Authentication Library (Preview), and then click the checkbox and restart.

**Comment by terminic** [comment]
That works!  I had to authenticate twice, but it is now showing correctly.
