### ISSUE TITLE
Attach multiple subdirectory connections for ADLS Gen 1

### ISSUE THREAD

**Issue by andreasmarkmann** [microsoft/AzureStorageExplorer#2371]
**Storage Explorer Version**: 1.11.1
**Build Number**: 20191121.1
**Platform/OS**: macOS High Sierra
**Architecture**: x64
**Regression From**:  n/a

## Bug Description ##
For users having execute access at ADLS root and rwx access at subdirectory level, the UI does not allow for multiple connections to various subdirectory locations where the user has access.

## Steps to Reproduce ##
1. User has execute access at 
adl://mylake.azuredatalakestore.net
and rwx access at
adl://mylake.azuredatalakestore.net/data/raw/erp
as well as
adl://mylake.azuredatalakestore.net/data/foundation/erp
via AAD.
1. This means that selecting "mylake" directly in the subscription gives an ACL error.
1. Under subscription, right click "Data Lake Storage Gen1 (Preview)" and select "Connect to data Lake Storage Gen1" or select and perform the same action from the "Actions" tab at the bottom left of the screen.
1. Paste "adl://mylake.azuredatalakestore.net/data/raw/erp" and confirm "Ok"
1. Under "Local & Attached" the name of "mylake" appears, selecting it successfully opens a tab in the "/data/raw/erp" subdirectory.
1. Go back to subscription to attach another subdirectory: right click "Data Lake Storage Gen1 (Preview)" and select "Connect to data Lake Storage Gen1" or select and perform the same action from the "Actions" tab at the bottom left of the screen.
1. This time, paste the URI to the other subdirectory,
"adl://mylake.azuredatalakestore.net/data/foundation/erp"

## Expected Experience ##
Expected is a second data lake link under "Local & Attached", both ideally indicating the subdirectory location through the UI (currently only displays name of "mylake" without reference to the subdirectory).

## Actual Experience ##
In fact, nothing happens, and the existing attached storage in "Local & Attached" continues to point to the "/data/raw/erp" subdirectory.

As a workaround, the existing storage is detached (via right-click "detach"), and the last two steps have to be repeated every time when switching between the "/data/raw/erp" and the "/data/foundation/erp" subdirectories. This is cumbersome when switching between locations frequently.

I appreciate any advice for how to workaround more effectively and hope for a fix that enables the UI to deliver the Expected Experience. Thank you.

## Additional Context ##
On the Azure Portal, the data explorer module shows the ACL error at the root of "mylake" but also exposes an input line that allows entering the path to a subdirectory directly, permitting navigation to any place where the user has rwx access reasonably quickly but without the additional functionality of the standalone Storage Explorer app.

**Comment by jinglouMSFT** [comment]
The retirement of ADLS Gen1 is now less than three months away. As [previously announced](https://azure.microsoft.com/en-us/updates/action-required-switch-to-azure-data-lake-storage-gen2-by-29-february-2024/) the service will be retired on 29 February 2024. With this date now close approaching we are going to close this issue as "won't fix". Documentation on how to migrate your data to ADLS Gen2/blob storage can be found here: https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-migrate-gen1-to-gen2-azure-portal

If you have any non ADLS Gen1 feedback for Storage Explorer, please feel free to open a new issue: https://github.com/microsoft/AzureStorageExplorer/issues/new/choose

This issue will now no longer be monitored.
