### ISSUE TITLE
Storage Explorer hangs on loading accounts and/or auth (MacOS)

### ISSUE THREAD

**Issue by richardjortega** [microsoft/AzureStorageExplorer#2372]
**Storage Explorer Version**: 1.11.1
**Build Number**: 20191121.1
**Platform/OS**: macOS Catalina
**Architecture**: x64
**Regression From**:  Issue did not occur in 1.10.1, this happened during an upgrade (may be related)

## Bug Description ##
Storage Explorer will hang while loading accounts (Screenshot below). 
<img width="1210" alt="Screenshot 2019-12-03 13 31 55" src="https://user-images.githubusercontent.com/1143885/70083582-4bf6c380-15d2-11ea-8609-cc27371d06f9.png">

## Steps to Reproduce ##
Happened during an upgrade then a restart of the computer. Couldn't exactly replicate it, but I moved the 1.10.1 version to trash, re-downloaded Azure Storage Explorer and added the application from temp back to Applications folder. 

## Steps to Fix ##
The only way I could get it to work was by checking `Developer Tools` identifying that Storage Explorer was getting an `ECONNREFUSED` from a value within `~/.ServiceHub/` (a folder that Storage Explorer writes to outside of its Application installed path). 

**Note**: Use at your own risk, this is how I fixed my problem and may provide direction for bug fix.

1) Close Storage Explorer
2) Remove and delete all files with `~/.ServiceHub/`
3) Open Storage Explorer, Storage Explorer recreates `~/.ServiceHub` appropriately and the files load.

![image](https://user-images.githubusercontent.com/1143885/70084196-814fe100-15d3-11ea-9c87-68eaa53fb895.png)

## Expected Experience ##
Storage Explorer would not hang on load.

## Actual Experience ##
Storage Explorer hung while loading accounts. Deleting application, re-downloading, and fresh install did not fix the issue.

**Comment by dei79** [comment]
I have the same problem that it hangs in the same position but this solution did not help. How can I figure out what Storage Explorer is trying to do to come closer to a solution?

**Comment by jamescross91** [comment]
Same issue here - deleting `~/.ServiceHub` resolved it for me.  Can we get this resolution added to https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&tabs=Windows%2C1904#sign-in-issues while we wait for a proper fix? This would have saved me a pile of time.

**Comment by MRayermannMSFT** [comment]
I merged a fix from our auth library that fixes this problem. We're shipping 1.12 soon-ish so I'm going to hold off on updating the docs.
