### ISSUE TITLE
After the update to v1.11.1 Can't import anymore pst files to Azure Storage Explorer

### ISSUE THREAD

**Issue by Inhereadncantdoan** [microsoft/AzureStorageExplorer#2375]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:

**Comment by MRayermannMSFT** [comment]
@Inhereadncantdoan , can you elaborate on what issues you are running into? Screenshots, error messages, etc?

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response.
