### ISSUE TITLE
Add an option to generate 'share-level shared access signature URI' for one file

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2378]
**Storage Explorer Version:** 1.11.1
**Build:** [20191204.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3292206)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> File Shares.
2. Select one file share which contains one file at least.
3. Select one file and right click it -> Select 'Get Shared Access Signature...'.
4. Check whether there an option 'Generate share-level shared access signature URI' shows on the  dialog or not.

**Expect Experience:**
Show an option 'Generate share-level shared access signature URI'
![image](https://user-images.githubusercontent.com/41351993/70129150-314b4a00-16b9-11ea-80eb-698204c87d5f.png)

**Actual Experience:**
No option 'Generate share-level shared access signature URI' shows.
![image](https://user-images.githubusercontent.com/41351993/70129282-68216000-16b9-11ea-804b-af0084b685b7.png)

**More Info:**
For blobs:
![image](https://user-images.githubusercontent.com/41351993/70129445-b5053680-16b9-11ea-8e78-4a868c1d22e2.png)

**Comment by JasonYeMSFT** [comment]
Won't fix to match the current blob SAS behavior. We decided to remove the check box to avoid mixing share/container level SAS and file/blob level SAS.
