### ISSUE TITLE
No error occurs when attaching one ADLS Gen2 container using one DFS Endpoint with Blob Container type 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2379]
**Storage Explorer Version:** 1.11.1
**Build:** [20191204.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3292206)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Give an RBAC role to a user like 'Blob Data Owner Role' on one **ADLS Gen2 blob container** tier.
2. Copy the DFS Endpoint -> Open connect dialog -> Select **resource type** with Blob Container.
3. Type the blob container name -> Connect.
4. Check the result.

**Expect Experience:**
An error occurs.

**Actual Experience:**

1. No error occurs.
![image](https://user-images.githubusercontent.com/54055206/70132053-5d1cfe80-16be-11ea-9c41-3360d51bfa63.png)

2. The Azure AD attached blob container works well.

**Comment by MRayermannMSFT** [comment]
Fix merged into master. We now won't let users do this.
