### ISSUE TITLE
Blob properties dialog: adding metadata handles keyboard focus poorly

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#238]
**Storage Explorer Version**: 1.2.0
**Platform**: Windows
**Architecture**: win32
**Regression From**: Unknown

#### Steps to Reproduce: ####
1. Open the properties dialog for a blob
2. Tab to the add metadata button
3. Hit enter

#### Expected Experience: ####
Keyboard focus should go into the textbox for the new metadata

#### Actual Experience: ####
Keyboard focus stays on the button

**Comment by v-xuanzh** [comment]
This issue has been fixed. So close it.
