### ISSUE TITLE
Fail to create snapshot when selecting 'Snapshot original blob then upload' for one Azure AD attached blob

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2380]
**Storage Explorer Version:** 1.11.1
**Build:** [20191204.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3292206)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Give an RBAC role to a user like 'Blob Data Owner Role' on one blob container tier.
2. Attach the blob container with Azure AD.
3. Open one blob -> Edit this blob and close it -> Select 'Snapshot original blob then upload' on File Changes Detected dialog.
4. Check the result.

**Expect Experience:**
Succeed to create snapshot.

**Actual Experience:**
Fail to create snapshot.
![image](https://user-images.githubusercontent.com/54055206/70131461-52159e80-16bd-11ea-9f1b-bd47693ef601.png)

**Comment by JasonYeMSFT** [comment]
The issue is caused by an Electron bug electron/electron#21515.

A workaround for this bug will be implemented.

**Comment by v-limu** [comment]
This issue has been fixed on build [20191220.9](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3338616). So we close it.
