### ISSUE TITLE
The activity log always keep renaming when renaming one file under one attached file share

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2381]
**Storage Explorer Version:** 1.11.1
**Build:** [20191204.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3292206)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Expand a storage account -> File Shares.
3. Create a new file share -> Upload one file to it -> Use SAS to attach the file share.
4. Open the attached file share -> Try to rename the file.
5. Check the result.

**Expect Experience:**
Succeed to rename the file.

**Actual Experience:**

1. The original file still shows.
2. The activity log always keep renaming.

![image](https://user-images.githubusercontent.com/54055206/70129336-82f3d480-16b9-11ea-8c83-c4ad1f61c18a.png)

**Comment by MRayermannMSFT** [comment]
To be fixed as a part of file shares moving to azcopy
