### ISSUE TITLE
Please support conditional access

### ISSUE THREAD

**Issue by Sokon77** [microsoft/AzureStorageExplorer#2382]
**Is your feature request related to a problem? Please describe.**
In our tenant, conditional access is switched on. As the documentation states, this scenario is currently not supported. We provide a centrally managed ASE in the company network that circumvents that issue and is our primary access tool for the central data lake. However, now there is a problem with this ASE connecting to our data lake. Most our users are cut off their data due to that. This is bad. If conditional access was supported, there would be a workaround for them using a local installation.

**Describe the solution you'd like**
Please support conditional access!

**Describe alternatives you've considered**
The abovementioned centrally installed ASE in the corporate network that circumvents the conditional access - which is currently out of order (see Issue #2358). We also provide a older, centrally managed version of ASE which allows uploads but doesn't allow downloads or deletes. Uploading using the online version of Storage Explorer in the portal is not supported. Because current availlable ADLS-RBAC roles needed for downloading and deleteing will expose all data of the data lake, we can't give users that persmission. Using AzCopy ist no option for our data citizens, and - because of this we didn't even test it.

**Additional context**

**Comment by jinglouMSFT** [comment]
Have you tried this with v1.11.1? 
![image](https://user-images.githubusercontent.com/10081483/70173151-195ad280-1687-11ea-8d6a-e16fc75aa141.png)

**Comment by Sokon77** [comment]
@jinglouMSFT: You guys are awesome - just im time! :-) Yes, I can confirm that with that setting applied, I authentication and everything else works. We have a workaround and my user can work. Great support, thanks!
