### ISSUE TITLE
Detach and Delete when performing data plane actions on "attached" ADL Gen2 Storage Path

### ISSUE THREAD

**Issue by johndellMSFT** [microsoft/AzureStorageExplorer#2384]
**Is your feature request related to a problem? Please describe.**
On Attached storage paths (user uses the attach resource via Azure Active Directory option) when right clicking and wanting to "detach", the "delete" option is right above.  this creates potential for mistakes and is also confusion.  We've had a few incidents where DELETE was selected and worked.  End result was loss of data, but also loss of ACL investments.  My request is to have DELETE removed from the data plane activities.  Anyone who has the DELETE capability should be doing it from the Management plane via RBAC.  

If you can't remove or have a different opinion, can you at least put it somewhere else in the list away from detach.

**Describe the solution you'd like**
Remove Delete from data plane activities.  If a container path is attached, we'd prefer DELETE is not in the list of options.

**Describe alternatives you've considered**
Put Delete "far away" from Detach, in the list of options

**Additional context**
We are a team in Microsoft that provides Azure Storage as a Service to other Microsoft eng teams.  These teams and their dependent external partners get auth/auth to storage via ADLS ACL's and their only way of getting storage actions is by using "Add resource via Azure Active Directory"  .  They are performing "storage actions" NOT "storage administration".  In our opinion storage admin is a ARM only function.  Giving the option through the data plan is a risk and opens up the door for sever mistakes.

**Comment by JasonYeMSFT** [comment]
Now there are two actions, "Acquire Lease" and "Break Lease" between "Detach" and "Delete" action.
