### ISSUE TITLE
There are a part of strings not localized in Settings panel

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2385]
**Storage Explorer Version:** 1.11.1
**Build:** [20191205.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3295843)
**Branch:** master
**Language:** Chinese(zh-TW)/ Chinese(zh-CN)
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous build ([20191204.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3292206&view=results))

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文(简体)' -> Restart Storage Explorer.
3. Open '设置' -> '传输' -> Check the descriptions for '网络并发'.

**Expect Experience:**
The strings are localized.

**Actual Experience:**
The strings are not localized.
![image](https://user-images.githubusercontent.com/41351993/70216378-5c49a280-177a-11ea-8798-aecff761085e.png)

**Comment by lukaschal** [comment]
New string added at 12/3/2019.

File: loc\en\src\components\se-az-copy-extension\resources\AzCopySettings.json
ID: 0; "DescriptionConcurrencyValue"
SRC: Overrides the number of HTTP connections working on transfers. Valid values are positive whole numbers and AUTO. If set to AUTO, then AzCopy will dynamically adjust the value during the transfer. If left blank then AzCopy will set the value based on the number of logical cores on the machine.

**Comment by v-xianya** [comment]
Hi @lukaschal In today's build 20191206.2. The below strings are not localized.(Both zh-TW & zh-CN)
![image](https://user-images.githubusercontent.com/41351993/70303955-c5451f00-183b-11ea-8c46-6b9e4a1e19f3.png)

**Comment by lukaschal** [comment]
On translation now.

**Comment by lukaschal** [comment]
Localized now.

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer?path=%2Floc%2Floc%2Fzh-Hans%2Fsrc%2Fcomponents%2Fse-az-copy-extension%2Fresources%2FAzCopySettings.json.lcl&version=GBmaster&_a=blame

**Comment by v-xianya** [comment]
This issue also reproduces in Japanese.
![image](https://user-images.githubusercontent.com/41351993/71227323-c127ff80-2319-11ea-996d-42e28fca0c89.png)
![image](https://user-images.githubusercontent.com/41351993/71227331-c9803a80-2319-11ea-92eb-bac2d7e096e3.png)

**Comment by lukaschal** [comment]
JPN localized at 12/12/2019.

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer?path=%2Floc%2Floc%2Fja%2Fsrc%2Fcomponents%2Fse-az-copy-extension%2Fresources%2FAzCopySettings.json.lcl&version=GBmaster&_a=blame

**Comment by v-limu** [comment]
This issue has been fixed on build [20191220.9](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3338616). So we close it.

Screenshot:
![image](https://user-images.githubusercontent.com/54055206/71572316-63fe2c00-2b19-11ea-9c6a-5878dd628135.png)

![image](https://user-images.githubusercontent.com/54055206/71572379-bd665b00-2b19-11ea-8479-0c23543bae74.png)


![image](https://user-images.githubusercontent.com/54055206/71572357-a162b980-2b19-11ea-9565-cdfc6983df78.png)
