### ISSUE TITLE
 Disks is localized on Settings panel in zh-TW

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2386]
**Storage Explorer Version:** 1.11.1
**Build:** [20191205.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3295843)
**Branch:** master
**Language:** Chinese(zh-TW)
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '繁體中文' -> Restart Storage Explorer.
3. Open '設定' -> '服務' -> Check whether 'Disks' is localized or not.

**Expect Experience:**
Disks is not localized.

**Actual Experience:**
Disks is localized.
![image](https://user-images.githubusercontent.com/41351993/70218337-c9126c00-177d-11ea-8392-fe6411dc6700.png)

**More Info:**
1. Storage Accounts is localized in zh-CN & zh-TW.
2. In zh-CN. Disks is not localized.
![image](https://user-images.githubusercontent.com/41351993/70218402-e9422b00-177d-11ea-8215-2f02fec22161.png)
3. ENU screenshot:
![image](https://user-images.githubusercontent.com/41351993/70218477-04ad3600-177e-11ea-914b-4fbcc20c4281.png)

**Comment by lukaschal** [comment]
On review.

File: loc\en\src\Standalone\resources\Shell.json
ID: 0; "DescriptionEnableDisks"
SRC: If unchecked, then all Disk related features will be hidden. The tree view must be refreshed for this setting to be applied.
TGT: 若取消選取，則會隱藏所有磁碟相關功能。必須重新整理樹狀檢視，才可套用此設定。

**Comment by johnliu2016** [comment]
"Disks" is localized to CHT/CHS locales.

**Comment by v-limu** [comment]
This issue has been fixed on build [20191220.9](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3338616). So we close it.
![image](https://user-images.githubusercontent.com/54055206/71572036-441a3880-2b18-11ea-9af5-739daed7a3c3.png)
