### ISSUE TITLE
The localized 'blob' shows different between zh-TW and zh-CN

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2387]
**Storage Explorer Version:** 1.11.1
**Build:** [20191205.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3295843)
**Branch:** master
**Language:** Chinese(zh-TW)
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '繁體中文' -> Restart Storage Explorer.
3. Open localized 'Settings' -> 'Data Explorers' -> Check the localized 'blob'.
4. Navigate to Application (Regional Settings) -> Select '中文(简体) -> Restart Storage Explorer.
5.  Open localized 'Settings' -> 'Data Explorers' -> Check the localized 'blob'.

**Expect Experience:**
The localized blob in zh-TW and zh-CN shows same.

**Actual Experience:**
The localized 'blob' is different between zh-TW and zh-CN
zh-TW
![image](https://user-images.githubusercontent.com/41351993/70219151-47bbd900-177f-11ea-9e0d-b6d5b0b90e52.png)
zh-CN
 ![image](https://user-images.githubusercontent.com/41351993/70219179-52766e00-177f-11ea-84b0-5bcc7567fea1.png)

**More Info:**
1. ENU screenshot:
![image](https://user-images.githubusercontent.com/41351993/70219216-602bf380-177f-11ea-9f9d-b1bdacfaf678.png)

2. This issue also reproduces when Acquiring/Breaking lease for one blob container.
![image](https://user-images.githubusercontent.com/41351993/70219607-142d7e80-1780-11ea-8c50-c2082cfa5efa.png)

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
File: loc\en\src\Standalone\resources\Shell.json
ID: 0; "DescriptionAutoRefresh"
File: loc\en\src\Standalone\resources\Azure.json
ID: 0; "MessageContainerAcquireLeaseConfirmation"

**Comment by johnliu2016** [comment]
Capitalized to 'Blob'

**Comment by MRayermannMSFT** [comment]
Won't fixing. We'll review english strings, but for non-english we won't nit-pick over these.
