### ISSUE TITLE
Show a different font in the popped activity log when hovering over the original one

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2388]
**Storage Explorer Version:** 1.11.1
**Build:** [20191205.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3295843)
**Branch:** master
**Language:** Chinese(zh-CN)
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文(简体)' -> Restart Storage Explorer.
3. Expand one storage account -> File Shares.
4. Select one file share and copy it.
5.  Paste it to another account -> Hover over the finished activity log then observe the popped activity log.

**Expect Experience:**
Show the same font for every character between the original and popped activity logs.

**Actual Experience:**
Show a different font in the popped activity log.
![image](https://user-images.githubusercontent.com/41351993/70221504-7176ff00-1783-11ea-83d5-7bed59bd50e5.png)

**More Info:**
This issue doesn't reproduce in zh-TW.

**Comment by lukaschal** [comment]
@craxal

**Comment by MRayermannMSFT** [comment]
Won't fix. We can't modify the font of tooltips
