### ISSUE TITLE
The regions are not localized on upload disk dialog 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2389]
**Storage Explorer Version:** 1.11.1
**Build:** [20191205.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3295843)
**Branch:** master
**Language:**  Czech/ German/ Spanish/ French/ Hungarian/ Italian/ Japanese/ Korean/ Dutch/ Polish/ Portuguese (Brazil)/ Portuguese (Portugal)/ Russian/ Swedish/ Turkish/ Chinese (Simplified) / Chinese (Traditional)
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '繁體中文' -> Restart Storage Explorer.
3. Expand Disks -> Open one resource group -> Click 'Upload' button.
4. Check the regions in the dropdown list of **Region** on the upload dialog.

**Expect Experience:**
The all regions are localized.

**Actual Experience:**
The all regions are not localized.
![image](https://user-images.githubusercontent.com/54055206/70223341-899c4d80-1786-11ea-89bd-1f32e8bdb0b4.png)

**Comment by lukaschal** [comment]
@craxal Not occurs in localizable resources for now.

**Comment by v-limu** [comment]
This issue also reproduces in **Japanese**.
![image](https://user-images.githubusercontent.com/54055206/71238013-fe9e8400-233d-11ea-96d4-5e75d832b554.png)

**Comment by janbaltus** [comment]
@MRayermannMSFT  we can match translation, but we need to have access to portal translation?
What you mean by portal? can you point us to xlf or  code location?

**Comment by jinglouMSFT** [comment]
@janbaltus Portal is the Azure Portal website.  Here is the link:  https://portal.azure.com/#home

**Comment by janbaltus** [comment]
@jinglouMSFT please point me to location we can find localized strings for this portal.

**Comment by jinglouMSFT** [comment]
1. You first need to log into Azure portal.  https://ms.portal.azure.com 
2. In all resources, find "Disks".  
3. Try to create a new disk.  
4. In the create managed disk page, there is a dropdown called "Region"
5. Basically, this is the list we need to translation. 
6. To the localized versions of these strings, click on the setting icon on the upper right corner of the blue bar.  In "Portal settings", go to the "Langauge & region" tab, pick a language other than English. Click on "Apply".  Your portal now should display in the language you have selected.  Look at the localized strings in "Region"

Here are couple of screenshot examples - 

from portal - simplified Chinese:
![image](https://user-images.githubusercontent.com/10081483/75206476-618c0d00-572b-11ea-82dd-a6fa7203e954.png)

From portal - English:
![image](https://user-images.githubusercontent.com/10081483/75206660-d19a9300-572b-11ea-9bda-74522efa8118.png)

**Comment by janbaltus** [comment]
We can leverage translation from existing region translation.
please let us know once strings are added

**Comment by MRayermannMSFT** [comment]
@janbaltus  The new resource file is merged and it has been added to the loc project file.

**Comment by MRayermannMSFT** [comment]
@janbaltus I saw that the strings have been translated. Thanks to you and your team for the fast turnaround. 😁

**Comment by MRayermannMSFT** [comment]
Updated and published package. Closing.

**Comment by janbaltus** [comment]
@MRayermannMSFT  please note that translation was adjusted after inintial recycling to match exactly portal translation.
You can see some changes in translation now.
