### ISSUE TITLE
The activity log is strange when creating one disk snapshot with empty strings

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2390]
**Storage Explorer Version:** 1.11.1
**Build:** [20191205.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3295843)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Expand Disks -> Open one resource group -> Upload one disk to it.
3. Create snapshot **with empty strings** name for the disk.
4. Check the activity log in Activities.

**Expect Experience:**
The activity log is clear. 

**Actual Experience:**
The activity log is strange.
![image](https://user-images.githubusercontent.com/54055206/70222845-8f456380-1785-11ea-9842-68d658bb44f1.png)

**Comment by MRayermannMSFT** [comment]
I've removed the ability to create a snapshot with an empty name. Merged into master.
