### ISSUE TITLE
The tooltip of the localized 'Activities' isn't localized

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2391]
**Storage Explorer Version:** 1.11.1
**Build:** [20191205.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3295843)
**Branch:** master
**Language:** Chinese(zh-TW)/Chinese(zh-CN)
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '繁體中文' -> Restart Storage Explorer.
3. Hover the localized 'Activities'.
4. Check the tooltip.

**Expect Experience:**
The tooltip of the localized 'Activities' is localized.

**Actual Experience:**
The tooltip of the localized 'Activities' isn't localized.
![image](https://user-images.githubusercontent.com/54055206/70222010-480aa300-1784-11ea-8a07-0e3745435ea3.png)

**Comment by lukaschal** [comment]
Localized 4 months ago.

File: loc\en\src\Standalone\resources\Shell.json
ID: 0; "TabActivities"
SRC: Activities
TGT: 活动
