### ISSUE TITLE
Large File not uploading properly

### ISSUE THREAD

**Issue by NickLee-Arrow** [microsoft/AzureStorageExplorer#2392]
**Storage Explorer Version**: 1.11.1
**Build Number**: 20190919.2 
**Platform/OS**: macOS 
**Architecture**: 
**Regression From**:  don't know

## Bug Description ##
A file won't up load and throws the following error message!--.
{
  "name": "Error",
  "message": "write EPIPE",
  "stack": "Error: write EPIPE\n    at WriteWrap.afterWrite [as oncomplete] (net.js:788:14)",
  "errno": "EPIPE",
  "code": "EPIPE",
  "syscall": "write"
}

## Expected Experience ##
the file uploads

## Actual Experience ##
file doesn't upload :/

## Additional Context ##
multiple attempts and restarts/reboots and still won't upload. file is a video clip shot on an FS7 as an MXF the clip is approximately 2 hours long 110.88GB file. the clipmplays back correctly in VLC so I can vouch for the integrity of the file

**Comment by MRayermannMSFT** [comment]
Are you uploading to a blob container or a file share? And if it is to a blob container, is it an ADLS Gen2 container?

**Comment by NickLee-Arrow** [comment]
Hi, Thanks for the reply, sorry its been so long to respond. End of year mania has begun early this year :(

our Account Kind is just showing as BlobStorage. I cant find anything more detailed than that in the portal.

Im uploading to a blob container that contains approximately 28TB of camera data at present. full backup of this container will be will be around the 34TB mark. with the largest single item being camera cards upto the size of 125GB

**Comment by jinglouMSFT** [comment]
I noticed from the version number and the build number you list in the first thread. They don't match.  The build number indicates to me that you are on build 1.10.0 but you also indicated that you are on 1.11.1.  It actually makes difference depending on with version you are using.  The default upload for Blobs in 1.10.x actually uses our old JS upload algorithm while 1.11.1 uses AzCopy.  If you are no on 1.11.1, I strongly recommend you upgrade to 1.11.1.  Upload using AzCopy is much more performant. For blob sizes in 100GB+, you will see noticeable improvements.  So upgrading to 1.11.1 is first suggestion.  If you are already on 1.11.1, I would recommend trying to upload using AzCopy command line.  You can copy the AzCopy command line from Storage Explorer activity log after you have run the upload once. This way you will not need to create the command line from scratch. This will also help isolate whether the issue is in Storage Explorer or in AzCopy or in the SDK.  Thanks.

**Comment by NickLee-Arrow** [comment]
Hi,

Thanks for the reply. I had started with 1.10.0 and after being unable to get the file to upload i upgraded one of the machines to 1.11.1 (which also cant upload the file). I tried copying the command to the clipboard then pasting it into a mac shell but the command failed to even run. it threw an error _./azcopy: no such file or directory_ 

Below is the log for the storage explorer upload.....

2019/12/13 08:33:47 AzcopyVersion  10.3.2
2019/12/13 08:33:47 OS-Environment  darwin
2019/12/13 08:33:47 OS-Architecture  amd64
2019/12/13 08:33:47 Log times are in UTC. Local time is 13 Dec 2019 08:33:47
2019/12/13 08:33:47 Job-Command copy /Volumes/APM063/the_real/0 RUSHES EP3/REAL_EP3_IV_RED_C025_20190313/A024_0313OJ.RDM/A024_C004_0313OW.RDC/A024_C004_0313OW_001.mov https://arrowmediaarchive1.blob.core.windows.net/thereal/0%20RUSHES%20EP3/REAL_EP3_IV_RED_C025_20190313/A024_0313OJ.RDM/A024_C004_0313OW.RDC/A024_C004_0313OW_001.mov?se=2020-01-12t08%3A33%3A46z&sig=-REDACTED-&sp=rwl&sr=c&sv=2018-03-28 --output-type=json --overwrite=prompt --cancel-from-stdin --follow-symlinks --recursive --from-to=LocalBlob --blob-type=Detect --put-md5 
2019/12/13 08:33:47 Number of CPUs: 4
2019/12/13 08:33:47 Max file buffer RAM 2.000 GB
2019/12/13 08:33:47 Max concurrent network operations: 32 (Based on number of CPUs. Set AZCOPY_CONCURRENCY_VALUE environment variable to override)
2019/12/13 08:33:47 Check CPU usage when dynamically tuning concurrency: true (Based on hard-coded default. Set AZCOPY_TUNE_TO_CPU environment variable to true or false override)
2019/12/13 08:33:47 Max concurrent transfer initiation routines: 64 (Based on hard-coded default. Set AZCOPY_CONCURRENT_FILES environment variable to override)
2019/12/13 08:33:47 Max open files when downloading: 7856 (auto-computed)
2019/12/13 08:33:47 PERF: primary performance constraint is Unknown. States: R:  0, D:  0, W:  0, F:  0, B:  0, E:  0, T:  0, GRs:  0
2019/12/13 08:33:47 JobID=6ad039fd-8f90-044f-472c-6bda846980e8, credential type: Anonymous
2019/12/13 08:33:47 scheduling JobID=6ad039fd-8f90-044f-472c-6bda846980e8, Part#=0, Transfer#=0, priority=0
2019/12/13 08:33:47 INFO: [P#0-T#0] has worker 5 which is processing TRANSFER
2019/12/13 08:33:47 INFO: [P#0-T#0] Starting transfer: Source "/Volumes/APM063/the_real/0%20RUSHES%20EP3/REAL_EP3_IV_RED_C025_20190313/A024_0313OJ.RDM/A024_C004_0313OW.RDC/A024_C004_0313OW_001.mov" Destination "https://arrowmediaarchive1.blob.core.windows.net/thereal/0%20RUSHES%20EP3/REAL_EP3_IV_RED_C025_20190313/A024_0313OJ.RDM/A024_C004_0313OW.RDC/A024_C004_0313OW_001.mov?se=2020-01-12t08%3A33%3A46z&sig=-REDACTED-&sp=rwl&sr=c&sv=2018-03-28". Specified chunk size 8388608
2019/12/13 08:33:47 ==> REQUEST/RESPONSE (Try=1/8.741237ms, OpTime=177.793347ms) -- RESPONSE SUCCESSFULLY RECEIVED
   HEAD https://arrowmediaarchive1.blob.core.windows.net/thereal/0%20RUSHES%20EP3/REAL_EP3_IV_RED_C025_20190313/A024_0313OJ.RDM/A024_C004_0313OW.RDC/A024_C004_0313OW_001.mov?se=2020-01-12t08%3A33%3A46z&sig=-REDACTED-&sp=rwl&sr=c&sv=2018-03-28&timeout=901
   X-Ms-Request-Id: [3fcbf7b1-601e-0049-5390-b19b25000000]

2019/12/13 08:33:49 PERF: primary performance constraint is Unknown. States: R:  0, D:  1, W: 19, F:  0, B: 32, E:  0, T: 52, GRs: 32
2019/12/13 08:33:50 ==> REQUEST/RESPONSE (Try=1/118.410799ms, OpTime=3.127026052s) -- RESPONSE SUCCESSFULLY RECEIVED
   PUT https://arrowmediaarchive1.blob.core.windows.net/thereal/0%20RUSHES%20EP3/REAL_EP3_IV_RED_C025_20190313/A024_0313OJ.RDM/A024_C004_0313OW.RDC/A024_C004_0313OW_001.mov?blockid=ztgymmqyndetmjqwys0xzdrllty2n2mtzguwndhhm2viymrk&comp=block&se=2020-01-12t08%3A33%3A46z&sig=-REDACTED-&sp=rwl&sr=c&sv=2018-03-28&timeout=901
   X-Ms-Request-Id: [120832fb-301e-0051-3090-b1b6b0000000]

2019/12/13 08:33:50 ==> REQUEST/RESPONSE (Try=1/121.927255ms, OpTime=3.229513272s) -- RESPONSE SUCCESSFULLY RECEIVED
   PUT https://arrowmediaarchive1.blob.core.windows.net/thereal/0%20RUSHES%20EP3/REAL_EP3_IV_RED_C025_20190313/A024_0313OJ.RDM/A024_C004_0313OW.RDC/A024_C004_0313OW_001.mov?blockid=zta3mwm1m2qtody2zi1hnjrmltvkzjitzda3ywi2nmrhmdc0&comp=block&se=2020-01-12t08%3A33%3A46z&sig=-REDACTED-&sp=rwl&sr=c&sv=2018-03-28&timeout=901
   X-Ms-Request-Id: [3fcbf7e3-601e-0049-7d90-b19b25000000]

2019/12/13 08:33:50 ERR: [P#0-T#0] UPLOADFAILED: /Volumes/APM063/the_real/0%20RUSHES%20EP3/REAL_EP3_IV_RED_C025_20190313/A024_0313OJ.RDM/A024_C004_0313OW.RDC/A024_C004_0313OW_001.mov : 409 : 409 The uncommitted block count cannot exceed the maximum limit of 100,000 blocks.. When Staging block. X-Ms-Request-Id: 120832fb-301e-0051-3090-b1b6b0000000

   Dst: https://arrowmediaarchive1.blob.core.windows.net/thereal/0%20RUSHES%20EP3/REAL_EP3_IV_RED_C025_20190313/A024_0313OJ.RDM/A024_C004_0313OW.RDC/A024_C004_0313OW_001.mov?se=2020-01-12t08%3A33%3A46z&sig=-REDACTED-&sp=rwl&sr=c&sv=2018-03-28
2019/12/13 08:33:51 PERF: primary performance constraint is Unknown. States: R:  0, D:  0, W:  0, F:  0, B:  0, E:  1, T:  1, GRs: 32
2019/12/13 08:33:52 ==> REQUEST/RESPONSE (Try=1/1.458108827s, OpTime=1.458171582s) -- RESPONSE SUCCESSFULLY RECEIVED
   GET https://arrowmediaarchive1.blob.core.windows.net/thereal/0%20RUSHES%20EP3/REAL_EP3_IV_RED_C025_20190313/A024_0313OJ.RDM/A024_C004_0313OW.RDC/A024_C004_0313OW_001.mov?blocklisttype=all&comp=blocklist&se=2020-01-12t08%3A33%3A46z&sig=-REDACTED-&sp=rwl&sr=c&sv=2018-03-28&timeout=30
   X-Ms-Request-Id: [3fcbfe50-601e-0049-1690-b19b25000000]

2019/12/13 08:33:53 PERF: primary performance constraint is Unknown. States: R:  0, D:  0, W:  0, F:  0, B:  0, E:  1, T:  1, GRs: 32
2019/12/13 08:33:54 ==> REQUEST/RESPONSE (Try=1/4.45801ms, OpTime=4.519596ms) -- RESPONSE STATUS CODE ERROR
   DELETE https://arrowmediaarchive1.blob.core.windows.net/thereal/0%20RUSHES%20EP3/REAL_EP3_IV_RED_C025_20190313/A024_0313OJ.RDM/A024_C004_0313OW.RDC/A024_C004_0313OW_001.mov?se=2020-01-12t08%3A33%3A46z&sig=-REDACTED-&sp=rwl&sr=c&sv=2018-03-28&timeout=27
   User-Agent: [AzCopy/10.3.2 Azure-Storage/0.7 (go1.13; darwin)]
   X-Ms-Client-Request-Id: [b581e594-e0e7-467d-5665-f7ce62fe0745]
   X-Ms-Version: [2018-11-09]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation using this permission.
   Content-Length: [279]
   Content-Type: [application/xml]
   Date: [Fri, 13 Dec 2019 08:33:53 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthorizationPermissionMismatch]
   X-Ms-Request-Id: [3fcc04b0-601e-0049-4a90-b19b25000000]
   X-Ms-Version: [2018-11-09]
Response Details: ﻿<Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission. </Message>

2019/12/13 08:33:54 JobID=6ad039fd-8f90-044f-472c-6bda846980e8, Part#=0, TransfersDone=1 of 1
2019/12/13 08:33:54 all parts of entire Job 6ad039fd-8f90-044f-472c-6bda846980e8 successfully completed, cancelled or paused
2019/12/13 08:33:55 PERF: primary performance constraint is Unknown. States: R:  0, D:  0, W:  0, F:  0, B:  0, E:  0, T:  0, GRs: 32

**Comment by jinglouMSFT** [comment]
Thank you for the log.  The error message was from AzCopy.  We are contacting the AzCopy team to have a look.

**Comment by jinglouMSFT** [comment]
@NickLee-Arrow Talked to the AzCopy team. The error was caused by the blob having too many uncommitted blocks.  From the log, it looks like the job has failed multiple times and the cleanup (a DELETE call) was failing due to not having enough permission; if the cleanup had succeeded, all the uncommitted blocks would have been removed. 

If the file is 110.88GB, it only has 13,218 blocks which is way below the 100,000 block max limit, which was indicated in the error message.  So we suspected that when there were multiple failed attempts and without the delete permission, the blocks just can't be deleted. 

The suggest is trying to upload to a different blob, meaning, rename the file first then upload. This will upload to a different blob.  Another option is to give the SAS delete permission to remove the uncommitted blocks. 

Would you give this a try?  Thanks.

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response.
