### ISSUE TITLE
An extra period shows on rename blob container dialog

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2394]
**Storage Explorer Version:** 1.11.1
**Build:** [20191206.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3299462)
**Branch:** master
**Language:** Chinese(zh-TW)
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '繁體中文' -> Restart Storage Explorer.
3. Expand one storage account -> Blob Containers.
4. Create a new blob container -> Try to rename this blob container.
5. Check the dialog.

**Expect Experience:**
No extra period shows.

**Actual Experience:**
An extra period shows.
![image](https://user-images.githubusercontent.com/54055206/70310837-8919ba80-184b-11ea-8678-c48a7fb3dcf6.png)

**More Info:**

1. This issue also reproduces for one file share/table.
2. This issue doesn't reproduce in **Chinese(zh-CN).**
![image](https://user-images.githubusercontent.com/54055206/70310998-c3835780-184b-11ea-9865-eb0406c80827.png)
3. ENU screenshot.
![image](https://user-images.githubusercontent.com/54055206/70311152-09402000-184c-11ea-91e9-0c1e79e4049e.png)

**Comment by lukaschal** [comment]
File: loc\en\src\Standalone\resources\RenameDialog.json
ID: 0; "NewNameLabel"
SRC: Please specify the new name
TGT: 請指定新名稱。

**Comment by MRayermannMSFT** [comment]
We probably want a : in english as well
