### ISSUE TITLE
Deep links to folders

### ISSUE THREAD

**Issue by justinormont** [microsoft/AzureStorageExplorer#2397]
**Is your feature request related to a problem? Please describe.**
Currently I can not share a deep link to a co-worker (who has access to the blob store). 

**Describe the solution you'd like**
I should be able to share a link: storageexplorer://nameofblobstore.blob.core.windows.net/my-datasets/dataset/ and have someone open the URL.

**Describe alternatives you've considered**
Can share a link to the blob store in Azure Portal.

**Comment by jinglouMSFT** [comment]
Is this for regular Blobs or ADLS or CosmosDB?   For regular Blobs you should be able to create deep link at the container level.  Please tell us a bit more of your repro steps.  Thanks.

**Comment by JasonYeMSFT** [comment]
Related to https://github.com/microsoft/AzureStorageExplorer/issues/3279

**Comment by JasonYeMSFT** [comment]
This has been implemented supported now.
