### ISSUE TITLE
Results are not shown when manipulating more than one tab

### ISSUE THREAD

**Issue by JCKodel** [microsoft/AzureStorageExplorer#2398]
**Storage Explorer Version**: 
1.11.1

**Build Number**: 
20191121.1

**Platform/OS**: 
Windows 10

**Architecture**: 
x64

**Regression From**:  
(n/a)

## Bug Description ##

When opening more than one tab at the time (i.e. double click on Tables) or setting focus on another tab when one is loading, the results doesn't show:

Resizing the window fixes the problem.

## Steps to Reproduce ##

1. Open Azure Tables node with at least 2 tables
2. Double click on one table
3. Double click on another table (before the first one appears)

or

1. Open any table on a tab
2. Double click on one table to open it on another tab
3. Click on the first opened tab
4. Click on the new opened tab

## Expected Experience ##

To work correctly in background

## Actual Experience ##

![image](https://user-images.githubusercontent.com/379339/70398769-8c54a800-19fd-11ea-9a66-32fced3116c3.png)

## Additional Context ##

(n/a)

**Comment by MRayermannMSFT** [comment]
@JCKodel if you resize the window does the UI fix itself?

**Comment by JCKodel** [comment]
> @JCKodel if you resize the window does the UI fix itself?

Yes

**Comment by MRayermannMSFT** [comment]
Fix merged into master for 1.15 development
