### ISSUE TITLE
All of the dropdown lists on Settings show blank 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2399]
**Storage Explorer Version:** 1.11.1
**Build:** [20191206.5](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3301659)
**Branch:** dev/marayerm/electron7/packaging
**Platform/OS:** Linux Ubuntu/Windows 10
**Architecture:** x64/ia32
**Regression From:** Previous build (20191206.2)

**Steps to reproduce:**
1. Open Settings -> Application -> Check **Theme & Protocol & Language(Preview)** dropdown list.
2. Navigate to Transfers -> Check the **Check MD5** dropdown list.

**Expect Experience:**
All of the dropdown lists show well.
![image](https://user-images.githubusercontent.com/41351993/70423032-b9f62b80-1aa7-11ea-8eb6-22c5758f1b84.png)

**Actual Experience:**
All of the dropdown lists show blank.
![image](https://user-images.githubusercontent.com/41351993/70423236-0fcad380-1aa8-11ea-9678-dce9ac2e2364.png)

**More Info:**
1. This issue doesn't reproduce on MacOS.
2. This issue doesn't reproduce on build master/[20191206.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3299462)

**Comment by craxal** [comment]
May be related to electron/electron#21152
