### ISSUE TITLE
New window are always light themed

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#240]
**Storage Explorer Version**: 1.2.0
**Platform**: Windows
**Architecture**: win32
**Regression From**: Unknown

#### Steps to Reproduce: ####
1. Open Storage Explorer
2. Switch to dark theme
3. File -> New Window

#### Expected Experience: ####
New window is dark themed

#### Actual Experience: ####
It is 💡 themed

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT 
This issue is fixed on the latest build 20200107.3. So we close it.
