### ISSUE TITLE
The 'Manage Access' dialog for one adls gen2 blob shows unfriendly

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2400]
**Storage Explorer Version:** 1.11.1
**Build:** [20191206.5](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3301659)
**Branch:** dev/marayerm/electron7/packaging
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous build (20191206.2)

**Steps to reproduce:**
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Select one blob container which contains one blob at least.
3. Right click one blob and select 'Manage Access...'.
4. Check the Manage Access dialog.

**Expect Experience:**
The Manage Access dialog shows friendly.
![image](https://user-images.githubusercontent.com/41351993/70425871-f9734680-1aac-11ea-87cb-e36dbdd3b342.png)

**Actual Experience:**
The Manage Access dialog shows unfriendly.
![image](https://user-images.githubusercontent.com/41351993/70426409-f6c52100-1aad-11ea-82d8-a57a382f2103.png)

**More Info:**
1. For ADLS Gen2 blob container & ADLS Gen2 folder, the Manage Access dialog shows like below.
![image](https://user-images.githubusercontent.com/41351993/70426265-ad74d180-1aad-11ea-84a4-d7899e1d7633.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into feature/electron-7
