### ISSUE TITLE
Various 'Properties' dialog show unfriendly 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2401]
**Storage Explorer Version:** 1.11.1
**Build:** [20191206.5](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3301659)
**Branch:** dev/marayerm/electron7/packaging
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous build (20191206.2)

**Steps to reproduce:**
1. Launch Storage Explorer. 
2. Select one item and check its dialog (Like one ADLS Gen2 blob container).

**Expect Experience:**
The dialog shows friendly.
![image](https://user-images.githubusercontent.com/41351993/70427080-0ee97000-1aaf-11ea-87d0-4a2e19c1b150.png)

**Actual Experience:**
The dialog shows unfriendly.
![image](https://user-images.githubusercontent.com/41351993/70427071-098c2580-1aaf-11ea-8315-0925adbad861.png)

**More Info:**
This issue reproduces on all items that have properties dialog.

**Comment by MRayermannMSFT** [comment]
Fix merged into feature/electron-7
