### ISSUE TITLE
Error while copying data disk from classic storage account to ARM storage account

### ISSUE THREAD

**Issue by RamBorude** [microsoft/AzureStorageExplorer#2404]
Error Details
If you cannot resolve this issue on your own, you may open an issue on the Storage Explorer GitHub site. Please include the details below to help us diagnose your issue. Make sure to redact any personal information you do not wish to make public before posting.

{
  "message": "\"Copy failed.\""
}

**Comment by jinglouMSFT** [comment]
I assume by "data disk" you meant a VHD ?  which version are you using?  Are you able to do anything else with Storage Explorer?

**Comment by RamBorude** [comment]
Thanks for the respond. I guess, I got the answer, I think it was failing because I was copying dynamic vhd.
Fixed by copying same vhd to same SA and from there I started copying to another storage account.

**Comment by jinglouMSFT** [comment]
If you are unblocked, I am closing the issue.  Please feel free to reopen the issue if this is not the case. Thank.
