### ISSUE TITLE
An error dialog pops up after cancelling 'Import' action for one table

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2405]
**Storage Explorer Version:** 1.11.1
**Build:** [20191206.5](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3301659)
**Branch:** dev/marayerm/electron7/packaging
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous build (20191206.2)

**Steps to reproduce:**
1. Expand one storage account -> Tables.
2. Select one table and open it -> Click 'Import' -> Click 'Cancel'.
3. Check the result.

**Expect Experience:**
No error occurs.

**Actual Experience:**
An error dialog pops up.
![image](https://user-images.githubusercontent.com/41351993/70517869-4a9a3d80-1b74-11ea-9514-e67db8b36496.png)

**Comment by MRayermannMSFT** [comment]
Fixed on electron 8 branch.
