### ISSUE TITLE
Add 'Add to Quick Access' for one ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2406]
**Storage Explorer Version:** 1.11.1
**Build:** [20191206.5](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3301659)
**Branch:** dev/marayerm/electron7/packaging
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Select one blob container and check its context menu.

**Expect Experience:**
'Add to Quick Access' shows on the context menu.

**Actual Experience:**
No 'Add to Quick Access' shows on the context menu.

**Comment by JasonYeMSFT** [comment]
Duplicate of #2361
