### ISSUE TITLE
Nothing happens when selecting 'Snapshot original blob then upload' for one blob under emulator

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2408]
**Storage Explorer Version:** 1.11.1
**Build:** [20191206.5](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3301659)
**Branch:** dev/marayerm/electron7/packaging
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ MacOS High Sierra
**Emulator**: 5.10.0.0
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Make sure Storage Emulator(5.10.0.0) is started.
2. Expand 'Local & Attached' -> 'Storage Accounts' -> '(Emulator - Default Ports)(Key)' -> 'Blob Containers'.
3. Create a new blob container -> Upload a blob to it -> Edit the blob and close it.
4. Select 'Snapshot original blob then upload' on File Changes Detected dialog.
5. Check the result.

**Expect Experience:**
Succeed to create original blob snapshot and upload.

**Actual Experience:**
Nothing happens.

**Comment by JasonYeMSFT** [comment]
A fix has been merged in master.

**Comment by v-limu** [comment]
Hi @JasonYeMSFT 
This issue opened on **dev/marayerm/electron7/packaging** branch. It doesn't reproduce on master branch. 😃
