### ISSUE TITLE
Show a failed activity log when deleting one blob under emulator

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2409]
**Storage Explorer Version:** 1.11.1
**Build:** [20191206.5](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3301659)
**Branch:** dev/marayerm/electron7/packaging
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ MacOS High Sierra
**Emulator**: 5.10.0.0
**Architecture:** ia32/x64
**Regression From:** Previous build ([20191206.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3299462))

**Steps to reproduce:**

1. Make sure Storage Emulator(5.10.0.0) is started.
2. Expand 'Local & Attached' -> 'Storage Accounts' -> '(Emulator - Default Ports)(Key)' -> 'Blob Containers'.
3. Create a new blob container -> Upload a blob to it -> Try to delete the blob.
4. Check the result.

**Expect Experience:**
Show a successful activity log.

**Actual Experience:**

1. Succeed to delete the blob.
2. The activity log shows 'Failed to delete...'.
![image](https://user-images.githubusercontent.com/54055206/70519570-1ecc8700-1b77-11ea-8d9b-c3ce7303cab7.png)

**Comment by JasonYeMSFT** [comment]
The issue is caused by an Electron bug electron/electron#21515.

A workaround for this bug will be implemented.

**Comment by v-limu** [comment]
This issue is fixed on build electron/8-20200507.4. So we close it.
