### ISSUE TITLE
New windows always have the release notes open by default

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#241]
**Storage Explorer Version**: 1.2.0
**Platform**: Windows
**Architecture**: win32
**Regression From**: Unknown

#### Steps to Reproduce: ####
1. Open Storage Explorer
2. File -> New Window

#### Expected Experience: ####
New window with no tabs is opened

#### Actual Experience: ####
The new window has the release 🎶 open?

**Comment by v-xianya** [comment]
This issue is not reproduce on Storage Explorer_20180905.3.

**Comment by MRayermannMSFT** [comment]
I was able to reproduce this today
