### ISSUE TITLE
There are untranslated strings in Rename dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2412]
**Storage Explorer Version:** 1.11.1
**Build:** [20191210.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3309673)
**Branch:** master
**Language:** Chinese(zh-CN)/ (zh-TW)
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous build(20191206.2)

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文(简体)' -> Restart Storage Explorer.
3. Expand one storage account -> Blob Containers.
4. Select one blob container and right click it -> Click localized 'Rename...'.
5. Check the Rename dialog.

**Expect Experience:**
All strings in Rename dialog are translated.

**Actual Experience:**
There are untranslated strings.
![image](https://user-images.githubusercontent.com/41351993/70607634-c5795c00-1c39-11ea-8f32-d7917d6ce917.png)

**More Info:**
This issue also reproduces for one file share/ table.

**Comment by lukaschal** [comment]
Updated string from yesterday. On translation.

File: loc\en\src\Standalone\resources\RenameDialog.json
ID: 0; "NewNameLabel"
SRC: Please specify the new name:
TGT: 請指定新名稱。

**Comment by v-xianya** [comment]
This issue has been fixed in build 20191219.2. So we close it.
![image](https://user-images.githubusercontent.com/41351993/71149232-e6106a00-2268-11ea-8cb0-bf3e0a74c3c9.png)
