### ISSUE TITLE
It allows to input Files port in 'Attach to Local Emulator' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2413]
**Storage Explorer Version:** 1.11.1
**Build:** [20191210.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3309673)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Open connect dialog -> Select 'Attach to a local emulator' -> Click 'Next'.
2. Check the Files port text box and try to input numbers like: 1003.

**Expect Experience:**
The Files port text box is disabled.

**Actual Experience:**
The Files port text box is enabled and allows to input numbers.
![image](https://user-images.githubusercontent.com/41351993/70608729-8fd57280-1c3b-11ea-80f8-8732970eb1a4.png)

**Comment by MRayermannMSFT** [comment]
By design. We left the textbox blank but empty, just in case someone has an emulator which supports file shares.
