### ISSUE TITLE
Window buttons (Minimize& Maximize& Close) are not localized

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2415]
**Storage Explorer Version:** 1.11.1
**Build:** [20191210.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3309673)
**Branch:** master
**Language:** Chinese(zh-CN)/ (zh-TW)
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文(简体)' -> Restart Storage Explorer.
3. Hover over the window buttons (At the top right corner of Storage Explorer).

**Expect Experience:**
The window buttons are localized.

**Actual Experience:**
The window buttons are not localized.
![image](https://user-images.githubusercontent.com/41351993/70609917-99f87080-1c3d-11ea-83ce-0d4676f5fda3.png)

**Comment by lukaschal** [comment]
@craxal Not occurs in localizable resources.

**Comment by craxal** [comment]
Won't fix. These are system tooltips, and therefore are dependent on the system language setting.
