### ISSUE TITLE
Fail to upload an empty folder to one file share

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2416]
**Storage Explorer Version:** 1.11.1
**Build:** [20191210.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3309673)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> File Shares.
2. Create one file share -> Upload one empty folder.
3. Check the result.

**Expect Experience:**
The uploaded empty folder shows.

**Actual Experience:**
1. The uploaded empty folder doesn't show.
2. The activity log shows 0 completed.
![image](https://user-images.githubusercontent.com/41351993/70612883-b054fb00-1c42-11ea-9c30-a7979021c91f.png)

**More Info:**
Succeed to download one empty folder.
![image](https://user-images.githubusercontent.com/41351993/70610549-bb0d9100-1c3e-11ea-94d4-cb87d8d0db9c.png)

**Comment by MRayermannMSFT** [comment]
Fix when moving file shares to azcopy or at least make sure that behavior is consistent with similar scenarios.

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT 
Now File Share is using AzCopy to upload & Download. The activity log for downloading & uploading an empty folder is consistent.
So we close this issue.
