### ISSUE TITLE
No quantifier in the localized deleted table entity activity log 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2417]
**Storage Explorer Version:** 1.11.1
**Build:** [20191210.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3309673)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Language:** Chinese(zh-TW)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Chinese (traditional)' -> Restart Storage Explorer.
3. Expand a storage account -> Tables.
4. Create a new table -> Add one entity to it -> Try to delete the entity.
5. Check the activity log.

**Expect Experience:**
Show a quantifier in the activity log.

**Actual Experience:**
No quantifier in the activity log.
![image](https://user-images.githubusercontent.com/54055206/70609622-13439380-1c3d-11ea-9afa-69b4e09bcaf6.png)

**Comment by lukaschal** [comment]
On review.

File: loc\en\src\Standalone\resources\Activities.json
ID: 0; "MessageTableDeletedMultiple"
SRC: %s entities deleted
TGT: %s 實體已刪除

File: loc\en\src\Standalone\resources\Activities.json
ID: 0; "MessageTableDeletedSingle"
SRC: %s entity deleted
TGT: %s 實體已刪除

**Comment by lukaschal** [comment]
Fixed.

new tgt: %s 個實體已刪除

**Comment by v-limu** [comment]
This issue has been fixed on build [20191219.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3333353). So we close it.
