### ISSUE TITLE
The content type for one ADLS Gen2 folder is not localized

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2421]
**Storage Explorer Version:** 1.11.1
**Build:** [20191212.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3315517&view=results)
**Branch:** master
**Language:** Chinese(zh-CN)/ (zh-TW)/ German/ Korean/ Japanese/ French/ Russian/ Czech/ Spanish/ Dutch/ Hungarian/ Italian/ Portuguese(pt-BR)/ Swedish 
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文(简体)' -> Restart Storage Explorer.
3. Expand one ADLS Gen2 storage account -> Blob Containers.
4. Create one blob container -> Create a new folder -> Check the content type of the new folder.

**Expect Experience:**
The content type is localized.

**Actual Experience:**
The content type is not localized.
![image](https://user-images.githubusercontent.com/41351993/70700437-b3fd8600-1d05-11ea-8f35-884974f437e9.png)

**More Info:**
1. This issue doesn't reproduce for one regular blob folder.
![image](https://user-images.githubusercontent.com/41351993/70700420-acd67800-1d05-11ea-91bd-b3aee9110f0d.png)

**Comment by lukaschal** [comment]
Both instances localized 2 months ago.

File: loc\en\src\Standalone\resources\UploadBlobsAndFilesDialog.json
ID: 0; "FolderCaption"
SRC: Folder
TGT: 文件夹

File: loc\en\src\components\se-blob-extension\resources\BlobEditor.json
ID: 0; "CellContentTypeFolder"
SRC: Folder
TGT: 文件夹

**Comment by v-xianya** [comment]
This issue also reproduces in Japanese.
![image](https://user-images.githubusercontent.com/41351993/71235756-12df8280-2338-11ea-99aa-75d0ede37de9.png)

**Comment by lukaschal** [comment]
@craxal Please confirm, is this string exposed to localization ?

**Comment by MRayermannMSFT** [comment]
Looks like the strings are loc'd now. Closing.
