### ISSUE TITLE
The table data disappear when clicking one random column under Query Builder 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2423]
**Storage Explorer Version:** 1.11.1
**Build:** [20191212.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3315517)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand a storage account -> Tables.
2. Create a new table -> Add several entities to it.
3. Open **Query** -> Try to click one random column on the table row.
4. Check whether the table data disappear or not.

**Expect Experience:**
The table data show well.

**Actual Experience:**
The table data disappear.
![image](https://user-images.githubusercontent.com/54055206/70700134-2f126c80-1d05-11ea-8059-b8ae8ae0177a.png)

**More Info:**
This issue also reproduces on 'Text Editor'.
![image](https://user-images.githubusercontent.com/54055206/70700226-5e28de00-1d05-11ea-95da-4ad97cfd29d8.png)

**Comment by MRayermannMSFT** [comment]
@v-limu can you verify this bug please?

**Comment by v-limu** [comment]
Hi @MRayermannMSFT Verified on build 20210126.2. This issue still reproduces. please see the record.
![table](https://user-images.githubusercontent.com/54055206/105789080-bdef5080-5fbc-11eb-9fde-9b614a4ed0e6.gif)
