### ISSUE TITLE
The popped dialog title isn't localized  when downloading one disk 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2424]
**Storage Explorer Version:** 1.11.1
**Build:** [20191212.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3315517)
**Branch:** master
**Language**: Chinese(zh-CN) / Chinese(zh-TW) / Japanese /Korean / German / Russian / Spanish / Dutch / Hungarian/ Swedish / Turkish
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文(简体)' -> Restart Storage Explorer.
3. Expand one resource group -> Try to download one disk.
4. Check the popped dialog.

**Expect Experience:**
The popped dialog title is localized.

**Actual Experience:**
The popped dialog title isn't localized.
![image](https://user-images.githubusercontent.com/54055206/70700730-23737580-1d06-11ea-83a3-dcbcb9b096bd.png)

**More Info:**
This issue also reproduces for blobs & files.
![image](https://user-images.githubusercontent.com/41351993/74309475-cba8c780-4da5-11ea-8fc4-936bf17e7bcf.png)

**Comment by lukaschal** [comment]
Hard-coded string.

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer?path=%2Fsrc%2Fcomponents%2Fse-managed-disks-extension%2Fsrc%2FDiskOperations.ts&version=GBmaster

**Comment by v-limu** [comment]
This issue also reproduces in **Japanese**.

**Comment by lukaschal** [comment]
@craxal

**Comment by MRayermannMSFT** [comment]
Looks like the strings are loc'd now. Closing.
