### ISSUE TITLE
The information isn't localized completely on manage access dialog for one ADLS Gen2 blob

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2425]
**Storage Explorer Version:** 1.11.1
**Build:** [20191212.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3315517)
**Branch:** master
**Language**: Chinese(zh-CN) / Chinese(zh-TW)
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文(简体)' -> Restart Storage Explorer.
3. Expand one ADLS Gen2 account -> Blob Containers.
4. Create a new blob container -> Click 'Manage Access...' -> Select 'Mask' and tick 'Default*'-> Save the permission.
5. Upload **a blob** to the blob container -> Click 'Manage Access...' -> Hover over the triangle icon on the dialog.
6. Check the information.

**Expect Experience:**
The information all are localized.

**Actual Experience:**
The information isn't localized completely.
![image](https://user-images.githubusercontent.com/54055206/70701803-f3c56d00-1d07-11ea-8d6e-325fee0ff7a2.png)

**Comment by lukaschal** [comment]
@craxal  Not occurs in localizable resources for now.

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
