### ISSUE TITLE
The tooltip of the Copy button isn't localized on SAS connect dialog

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2426]
**Storage Explorer Version:** 1.11.1
**Build:** [20191212.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3315517)
**Branch:** master
**Language**: Chinese(zh-CN) / Chinese(zh-TW)
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文(简体)' -> Restart Storage Explorer.
3. Select a storage account -> Click 'Get Shared Access Signature... ' -> Create -> Hover over the Copy button of the 'Connection String'.
4. Check the tooltip of the Copy button.

**Expect Experience:**
The tooltip of the Copy button is localized.

**Actual Experience:**
The tooltip of the Copy button isn't localized.
![image](https://user-images.githubusercontent.com/54055206/70702741-b82ba280-1d09-11ea-9057-b64c4177d5f2.png)

**Comment by lukaschal** [comment]
New string from 12/11.

File: loc\en\src\Standalone\resources\GenerateSasDialog.json
ID: 0; "DescriptionCopyConnectionStringToClipboard"
SRC: Copy connection string to clipboard

**Comment by lukaschal** [comment]
Localized now.

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer/commit/68c8c74fb6d2352c8139cb7aa443be23b0330722?_a=compare&path=%2Floc%2Floc%2Fit%2Fsrc%2FStandalone%2Fresources%2FGenerateSasDialog.json.lcl

**Comment by v-limu** [comment]
This issue has been fixed on build [20191220.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3336432). So we close it.
