### ISSUE TITLE
File preview esp. for pictures

### ISSUE THREAD

**Issue by timoklimmer** [microsoft/AzureStorageExplorer#2427]
We are collecting loads of images from IoT cameras and store them in Azure Blob containers. Sometimes we need to look at the images when working with the files. A feature which lets us preview images (or even other filetypes) would significantly improve productivity. Similar to what Windows Explorer has.

**Comment by MRayermannMSFT** [comment]
Assigning to Jing so he can find other issues for this request.

**Comment by MRayermannMSFT** [comment]
Jing, please find similar issues, link them together, and then put them in future. Thanks!

**Comment by jinglouMSFT** [comment]
#2116 
Also in the backlog. Bug numbers added for tracking purpose.

**Comment by jasonhorner** [comment]
this is definitely a blocking issue for us the relevant file types that would be useful to preview are:

- txt (CSV | TSV)
- parquet
- avro
- json
- orc 

it would be great if the preview pane could render the first 100 row in a grid viewer

**Comment by danielwagn3r** [comment]
I know the Hadoop FS Explorer preview feature, it allows to view the head or tail of a file, would be helpful here as well.

**Comment by jinglouMSFT** [comment]
Thanks for the input.

**Comment by jinglouMSFT** [comment]
Closing this one.  We use #5852 to track the feature request.
