### ISSUE TITLE
No warning occurs when typing an existing display name on Attach with Azure AD dialog

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2435]
**Storage Explorer Version:** 1.11.2
**Build:** [20191213.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3318376)
**Branch:** hotfix/1.11.2
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Select one ADLS Gen2 blob container then copy its DFS Endpoint.
2. Open connect dialog -> Select 'Add a resource via Azure Active Directory (Azure AD)'.
3. Select Resource type as 'Blob Container(ADLS Gen2)' -> Paste the DFS Endpoint -> Type a display name that is already exists under Attached Containers with Azure AD.
4. Observe  the result.

**Expect Experience:**
A warning occurs.

**Actual Experience:**
No warning occurs.
![image](https://user-images.githubusercontent.com/54055206/70791511-3489b880-1dd2-11ea-8d76-a1ac18522ed0.png)

**More Info:**

1. This issue also reproduces for 'Blob Container' type.
2. An warning occurs when typing an existing display name on SAS connect dialog.
![image](https://user-images.githubusercontent.com/54055206/70792610-977c4f00-1dd4-11ea-8543-b1d0ce9c2327.png)

**Comment by MRayermannMSFT** [comment]
Moving to 1.13 for sake of time.
