### ISSUE TITLE
The blob name isn't selected on rename/clone dialog

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2436]
**Storage Explorer Version:** 1.11.2
**Build:** [20191213.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3318376)
**Branch:** hotfix/1.11.2
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand a storage account -> Blob Containers.
2. Create a new blob container -> Upload a blob to it -> Try to rename this blob.
3. Check the dialog.

**Expect Experience:**
The blob name is selected.

**Actual Experience:**
The blob name isn't selected.
![image](https://user-images.githubusercontent.com/54055206/70792774-e9bd7000-1dd4-11ea-8260-2c810f5bbba0.png)

**More Info:**
This issue doesn't reproduce for one file/directory under one file share.
![image](https://user-images.githubusercontent.com/54055206/70792830-05287b00-1dd5-11ea-89d4-3b86a2454f7d.png)

**Comment by MRayermannMSFT** [comment]
Related to #2071

**Comment by v-limu** [comment]
Verified on build 20200603.4. 

1. The 'Clone' button is enabled when the blob name is selected.
![image](https://user-images.githubusercontent.com/54055206/83589207-bc809c00-a585-11ea-94d3-8faa4680e8df.png)

**Comment by MRayermannMSFT** [comment]
@v-limu , since this issue is about the selection of the name and that is fixed I am going to close this. Please let me know if you don't see the name selected. Thanks!
