### ISSUE TITLE
Storage Explorer 64 bit can't sign in successfully on Windows without VS

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#244]
**Storage Explorer Version**: 1.2.0
**Platform**: Windows
**Architecture**: x64
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Launch Storage Explorer 64 bit.
2. Sign in with your account.

#### Expected Experience: ####
The account can be added successfully.

#### Actual Experience: ####
Display a blank sign in page after inputting your account then click 'Next'.
![sign in](https://user-images.githubusercontent.com/34729022/40828068-1e8fa4bc-656f-11e8-881f-f72ddcf9b1f2.png)

#### More info: ####
1. The account which is added in VS displays well in Storage Explorer.
2. This issue doesn't reproduce on Windows(32bit) and Mac/Linux.

**Comment by MRayermannMSFT** [comment]
Hey @v-xuanzh , I'm unable to report the issue this morning. Can you please try to repro again on Monday, and if it still repro's, email me with details on getting access to the repro machine. Thanks!

**Comment by MRayermannMSFT** [comment]
Closing as no repro.

**Comment by v-xuanzh** [comment]
Hi @MRayermannMSFT,
This issue still reproduces on latest master build 20180607.1. You can get the detail repro info from the [can’t sign in.mp4](\\trinlab2\BAQAFiles\CloudToolsTest\v-xuanzh\SE\Sign_in_issue_on_SE_64bit). So reopen this issue.

**Comment by MRayermannMSFT** [comment]
@v-xuanzh is this still reproduceable?

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT Verified this issue on build 20200622.5. Not reproduce. So we closed it.
