### ISSUE TITLE
Update 'Clone with New Name' to 'Clone With New Name' in one blob container context menu

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2440]
**Storage Explorer Version:** 1.11.2
**Build:** [20191215.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3323607)
**Branch:** hotfix/1.11.2
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one Non-ADLS Gen2 storage account -> Blob Containers.
2. Select one blob container and right click it -> Check the context menu.

**Expect Experience:**
Display 'Clone With New Name...'.

**Actual Experience:**
Display 'Clone with New Name...'.
![image](https://user-images.githubusercontent.com/41351993/70896139-1ec30000-202b-11ea-94bf-4e5e20334e87.png)

**More Info:**
1. This issue also reproduces for one file share.
![image](https://user-images.githubusercontent.com/41351993/70896167-2da9b280-202b-11ea-83ff-43b8b32784f6.png)

2. In Release Notes, 'Clone With New Name' is used.

**Comment by MRayermannMSFT** [comment]
Changing all title case instance to "Clone with New Name". In title casing the "w" in "with" is not capitalized.
