### ISSUE TITLE
Add more description in Clone dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2443]
**Storage Explorer Version:** 1.11.2
**Build:** [20191215.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3323607)
**Branch:** hotfix/1.11.2
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> File Shares.
2. Create one file share and right click it -> Click 'Clone with New Name...'.
3. Check the descriptions in the Clone dialog.
 
**Expect Experience:**
Provide more specific description in Clone dialog.

**Actual Experience:**
The description is not specific.

**Comment by MRayermannMSFT** [comment]
Per discussion with Jing, we're happy with the description as is. Won't fix.
