### ISSUE TITLE
Make the title more specific when cloning one blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2445]
**Storage Explorer Version:** 1.11.2
**Build:** [20191215.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3323607)
**Branch:** hotfix/1.11.2
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one Non-ADLS Gen2 storage account -> Blob Containers.
2. Select one blob container and right click it -> Click 'Clone with New Name...'.
3. Check the dialog title.
 
**Expect Experience:**
Show 'Clone Blob Container with New Name'.

**Actual Experience:**
Show 'Clone'.
![image](https://user-images.githubusercontent.com/41351993/70899456-96942900-2031-11ea-87cc-b1cc43b58806.png)

**More Info:**
1. This issue also reproduces for one file share.
2. This issue also reproduces for one file/ folder under one file share.

**Comment by MRayermannMSFT** [comment]
Per discussion with Jing, won't fix. We don't want that title to be too long.
