### ISSUE TITLE
Change the activity log for the action 'Clone With New Name'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2446]
**Storage Explorer Version:** 1.11.2
**Build:** [20191215.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3323607)
**Branch:** hotfix/1.11.2
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one Non-ADLS Gen2 storage account -> Blob Containers.
2. Select one blob container and right click it -> Clone the blob container with a new name.
3. Check the activity log.
 
**Expect Experience:**
Display 'Successfully cloned blob container 'xxx' to 'xxx''. 

**Actual Experience:**
Display 'Successfully copied blob container 'xxx' to 'xxx''.
![image](https://user-images.githubusercontent.com/41351993/70899762-44073c80-2032-11ea-8fb4-4b28326fd12f.png)

**More Info:**
1. This issue also reproduces for one file share.
2. This issue also reproduces for files under file share & blobs.

**Comment by MRayermannMSFT** [comment]
Per discussion with Jing, won't fix. We've reusing the copy code path so the strings are going to say copy, and cloning is done by copying anyways. So no big deal.
