### ISSUE TITLE
Miss file name in activity log when cloning one file under one file share

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2448]
**Storage Explorer Version:** 1.11.2
**Build:** [20191215.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3323607)
**Branch:** hotfix/1.11.2
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one storage account -> File Shares.
2. Create a new file share -> Upload one file to it.
3. Try to clone this file.
4. Check the activity log.

**Expect Experience:**
The file name shows in activity log.

**Actual Experience:**
Miss file name in activity log.
![image](https://user-images.githubusercontent.com/54055206/70901652-2936c700-2036-11ea-9638-fca334a95c0a.png)

**More Info:**

1. This issue doesn't reproduce for one folder under one file share.
![image](https://user-images.githubusercontent.com/54055206/70901678-3784e300-2036-11ea-900e-5efd796d6fba.png)
2. This issue doesn't reproduce for one blob.

**Comment by MRayermannMSFT** [comment]
To be fixed when clone/rename is moved to AzCopy for File Shares

**Comment by v-xianya** [comment]
Verified this issue on build [20200217.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3478085). 
The original file name displays but the new file name doesn't display. Details see the screenshot please!
![image](https://user-images.githubusercontent.com/41351993/74636423-e8c50800-51a2-11ea-831d-ca4f8afbbb6c.png)

**Comment by MRayermannMSFT** [comment]
@jasonyemsft please verify that the strings are consistent across blobs and files for azcopy operations. If it is consistent then let's just close.

**Comment by JasonYeMSFT** [comment]
The behavior is consistent across blobs and the azcopy integration for file share. The 2nd string is supposed to be the parent directory of the copied blob/file.
