### ISSUE TITLE
The buttons name in delete blob dialog are different with other delete dialog

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2449]
**Storage Explorer Version:** 1.11.2
**Build:** [20191215.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3323607)
**Branch:** hotfix/1.11.2
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one storage account -> Blob Containers.
2. Create a new blob container -> Upload one blob to it.
3. Try to delete one blob.
4. Check the dialog.

**Expect Experience:**
The buttons name show 'Yes' & 'No'.

**Actual Experience:**
The buttons name show 'Delete' & 'Cancel'.
![image](https://user-images.githubusercontent.com/54055206/70902149-27213800-2037-11ea-89d6-cb8eb53c6809.png)

**More Info:**
The buttons name show 'Yes' & 'No' on other delete dialog.
![image](https://user-images.githubusercontent.com/54055206/70902097-08bb3c80-2037-11ea-84ec-d830bd009ab2.png)

**Comment by jinglouMSFT** [comment]
@v-limu, fixes for this bug have been merged.  Please verify for both Blobs and ADLS Gen2 blobs. Thanks.

**Comment by v-limu** [comment]
Verified on build [20200201.2.](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3434212&view=results
) This issue has been fixed.😉
