### ISSUE TITLE
Can't browse Azure Stack Storage Accounts - The value for one of the HTTP headers is not in the correct format.

### ISSUE THREAD

**Issue by CharbelNemnom** [microsoft/AzureStorageExplorer#2450]
Hello Team,

Please note that I am not able to browse the storage accounts (blob, containers, files) on Azure Stack with Azure Storage Explorer.
I am using Azure Storage Explorer version 1.11.1 with AzCopy Version: 10.3.2
Azure Stack is running version 1908.

Please see attached error: 
![image](https://user-images.githubusercontent.com/13448198/70911497-4f4a7000-2012-11ea-8bfb-9bf2ece20f05.png)

Could you please advise?

Thank You!
-Charbel

**Comment by MRayermannMSFT** [comment]
Did you enable "Target Azure Stack APIs"?

**Comment by CharbelNemnom** [comment]
Thank You!

No, I did not. I enable it now and it works.
So we need to keep switching when targeting Azure / Azure Stack.

**Comment by MRayermannMSFT** [comment]
Yes, you will need to switch.
