### ISSUE TITLE
Metadata on ADLS folders

### ISSUE THREAD

**Issue by febinrejoe** [microsoft/AzureStorageExplorer#2452]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to add metadata on ADLS folder's. This forces teams to create a separate system map ADLS folders with certain metadata. I would be really nice if ADLS offers capturing metadata about a folder on the data lake itself.

**Describe the solution you'd like**
Currently the folders on ADLS has a Folder Properties tab which captures the following info,

- Name
- Type
- Last Modified Time
- Path

One solution is to expand Folder Properties to capture metadata info (similar to capturing tags) using a key/ value data structure

**Describe alternatives you've considered**
Today we are crawling the folders, storing it in a DB and then allowing users to add metadata using a separate system.

**Comment by MRayermannMSFT** [comment]
For clarification, are you asking about ADLS Gen1 or Gen2?

**Comment by febinrejoe** [comment]
> For clarification, are you asking about ADLS Gen1 or Gen2?

We are currently on Gen1 (_for other technical reasons_), so I would like this to be on both Gen1 and Gen2 :)

**Comment by MRayermannMSFT** [comment]
For gen2, folder properties already exist:
![image](https://user-images.githubusercontent.com/21112697/71203207-6ecfdb80-2252-11ea-8f8f-118ec90e1997.png)

**Comment by febinrejoe** [comment]
Can this feature be added to gen1?

**Comment by MRayermannMSFT** [comment]
@febinrejoe , doing that would be out of our scope. Please file feedback with ADLS Gen1 for that.

**Comment by febinrejoe** [comment]
> @febinrejoe , doing that would be out of our scope. Please file feedback with ADLS Gen1 for that.

Thanks!! Where can I provide the feedback.
