### ISSUE TITLE
Add 'a' in the tooltip of the 'Clone with New Name' button for one file share

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2454]
**Storage Explorer Version:** 1.11.2
**Build:** [20191216.5](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3326258)
**Branch:** hotfix/1.11.2
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one storage account -> File Shares.
2. Create a new file share -> Open it -> Hover over the  'Clone with New Name...' button on toolbar.
3. Observe the tooltip.

**Expect Experience:**
The tooltip shows 'Clone selected file or directory with **a** new name'.

**Actual Experience:**
The tooltip shows 'Clone selected file or directory with new name'.
![image](https://user-images.githubusercontent.com/54055206/70986369-b80c1800-20f8-11ea-8108-2b4eda32b241.png)

**More Info:**
This issue doesn't reproduce for one blob container.
![image](https://user-images.githubusercontent.com/54055206/70986349-b04c7380-20f8-11ea-99df-0ed0e3588ce9.png)

**Comment by MRayermannMSFT** [comment]
By design.
