### ISSUE TITLE
Copying URI using "Copy" button does not work

### ISSUE THREAD

**Issue by Rhin94** [microsoft/AzureStorageExplorer#2456]
**Storage Explorer Version**:  1.11.1
**Build Number**: 20191121.1
**Platform/OS**:  Windows 10 Pro
**Architecture**: x64
**Regression From**:  Not sure

## Bug Description ##
When generating a Shared Access Signature for a fileshare, if you copy the URI using the button you receive the below error 

![URI bug](https://user-images.githubusercontent.com/58856839/70994504-50d57000-20c6-11ea-9815-8bafbdc768c7.png)

but if you manually copy the URI from the box there is no issue 

## Steps to Reproduce ##
1. Generated Shared Access Signature
2. Copy URI to clipboard using "Copy" button
3. attempt to connect fileshare using URI code

## Expected Experience ##
Fileshare should connect and be added

## Actual Experience ##
Error shown above is displayed

**Comment by JasonYeMSFT** [comment]
I have tried your steps and cannot reproduce it. Can you share the name of the fileshare you are trying to attach to? 

FYI, the "path" is the path to the fileshare (e.g. https://<account>.blob.core.windows.net/<path_to_fileshare>) Can you double check if there is a mismatch at that place?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
