### ISSUE TITLE
Unable to download/upload data lake files

### ISSUE THREAD

**Issue by srikrishna-540** [microsoft/AzureStorageExplorer#2459]
**Storage Explorer Version**: 1.11.0
**Build Number**: 201912174
**Platform/OS**: 
**Architecture**: ia32
**Regression From**:  yes

## Bug Description ##
When i try to download/upload files from storage explorer, though able to explore the container and its files

1) error i get "UnexpectedQuit (used name and key, discovery not completed)"
2) tried re login, restart tool and os

## Expected Experience ##
Able to download file and upload

## Actual Experience ##
Not able to download files and upload files

**Comment by JasonYeMSFT** [comment]
Do you mean the feature regress from version 1.11.0? The build number doesn't match version 1.11.0. Also what operating system are you on? Is there a "Go to AzCopy log" action on the activity log for your failed download/upload? If there is one, can you share the log file with us so we can see what goes wrong?

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response.
