### ISSUE TITLE
The value of 'Expiration date' is Local in 'Connection Summary' dialog when creating the connection string using UTC Expiry time

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#246]
**Storage Explorer Version**: 1.2.0
**Platform**: All
**Architecture**: ia32/x64
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Launch Storage Explorer and expand Storage Accounts.
2. Right click one account and select 'Get Shared Access Signature...' -> Select 'UTC' under Time Zone in SAS dialog -> Creat.
3. Paste the generated connection string to 'Attach with Connection String or SAS URI' dialog -> 'Next'.
4. Check the 'Expiration date' in 'Connection Summary' dialog.

#### Expected Experience: ####
The value of 'Expiration date' is 'UTC'.

#### Actual Experience: ####
The value of 'Expiration date' is 'Local'.
![time](https://user-images.githubusercontent.com/34729022/40829761-f8ee78c8-6573-11e8-9b69-e5c11d99abcc.png)

**Comment by craxal** [comment]
Why do you expect this time to be UTC? What if the user had Local set when generating the SAS?

We haven't gotten any customer compaints about this. Unless we do, we probably don't need to wrry about this.

**Comment by v-xuanzh** [comment]
Thanks for your sharing about this issue.
