### ISSUE TITLE
There is one typo in Release Notes Known Issues section

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2460]
**Storage Explorer Version:** 1.11.2
**Build:** [20191217.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3329873&view=results)
**Branch:** hotfix/1.11.2
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer -> Help -> View Release Notes.
2. Check the first known issue description in Known Issues section.

**Expect Experience:**
No typo shows.

![image](https://user-images.githubusercontent.com/41351993/71069706-337ecf80-21b4-11ea-8832-5a3cddb56d66.png)

**Actual Experience:**
There is one typo shows.

![image](https://user-images.githubusercontent.com/41351993/71069683-2c57c180-21b4-11ea-9834-5a8717748ff2.png)

**More Info:**
It is better to add quotation marks for **~/snap/storage-explorer/current/.config/storage-explorer/sessions**.

**Comment by MRayermannMSFT** [comment]
Fixed in remote release notes.
