### ISSUE TITLE
The area covered by focus color exceeds the border in delete blob dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2461]
**Storage Explorer Version:** 1.11.2
**Build:** [20191217.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3329873&view=results)
**Branch:** hotfix/1.11.2
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one Non-ADLS Gen2 storage account -> Blob Containers.
2. Select one blob container which contains one blob at least.
3. Select one blob and right click it -> Click 'Delete'.
4. Select all descriptions in delete dialog -> Observe the area covered by focus color.

**Expect Experience:**
The area covered by focus color doesn't exceed the border.

**Actual Experience:**
The area covered by focus color exceeds the border.
![image](https://user-images.githubusercontent.com/41351993/71070983-c02a8d00-21b6-11ea-93ef-fc6f67f4f8ad.png)

**More Info:**
1. This issue doesn't reproduce for one ADLS Gen2 blob.
![image](https://user-images.githubusercontent.com/41351993/71071021-cf113f80-21b6-11ea-9969-febecddf8edd.png)
2. This issue doesn't reproduce on MacOS.

**Comment by MRayermannMSFT** [comment]
Won't fix.
