### ISSUE TITLE
The App just hangs with a loading symbol on start up

### ISSUE THREAD

**Issue by ChrisAllisonMalta** [microsoft/AzureStorageExplorer#2463]
**Storage Explorer Version**: 1.11.1
**Build Number**: 20191121.1
**Platform/OS**: macOSx 10.15.2 (19C57)
**Architecture**: 64
**Regression From**:  Yes
## Bug Description ##
When I load the app, it previously prompted me for my password for keychain access, it doesn't do that right now, it just waits and waits and I see none of my connected services or if I try and create a new connection, it just hangs on the "Waiting for Authentication" screen

## Expected Experience ##
my connected azure services to be available

## Actual Experience ##
![Screenshot 2019-12-18 at 16 57 31](https://user-images.githubusercontent.com/11945453/71101754-8a39d880-21b7-11ea-9012-d5fd030218e9.png)

**Comment by ChrisAllisonMalta** [comment]
I can confirm, if download the app from new and launch it (right click, open) from my Downloads folder it works fine, but if I move that file to my Applications it doesn't launch and I get the above error.

**Comment by ultrafastneal** [comment]
I can also confirm the same behavior as reported by ChrisAllisonMalta  . Thanks for the workaround @ChrisAllisonMalta

**Comment by dpnl87** [comment]
Can confirm same behavior on OSX 10.14.6 with 1.11.1

**Comment by MRayermannMSFT** [comment]
Can y'all try closing Storage Explorer and then deleting `~/Library/Application\ Support/StorageExplorer/sessions/`?

**Comment by dpnl87** [comment]
Thank you for the quick reply @MRayermannMSFT. Have just deleted the folder but no joy for me.

Still the loading symbol and I'm not able to add new Azure Accounts as well.

<img width="1748" alt="Screenshot 2019-12-18 at 23 46 25" src="https://user-images.githubusercontent.com/85584/71129876-ca697d00-21f0-11ea-9450-2f96aff7442a.png">

**Comment by ChrisAllisonMalta** [comment]
> Can y'all try closing Storage Explorer and then deleting `~/Library/Application\ Support/StorageExplorer/sessions/`?

Hi @MRayermannMSFT I don't have that folder. The closest I get is `~/Library/Application Support/Microsoft/` and then its a Microsoft Auto Update file

**Comment by tomridl** [comment]
Also had this issue with both 1.11.1 and 1.11.2. However after opening and closing the application a few times, and deleting the entire StorageExplorer folder from Application Support it eventually opened correctly. Also running macOS 10.15.2.

**Comment by mhammons** [comment]
I see the same issue....v1.11.2 on Windows 10 Pro. Deleting session folders has not helped. Mine hangs on the startup/splash screen. Attached....
![mase-hangs](https://user-images.githubusercontent.com/36681041/71285778-0a854880-2334-11ea-8dff-22de8de7cfe2.png)

**Comment by jmshal** [comment]
I'm currently experiencing the same issue. Have been for the past week or two. Wasn't sure if it was a Catalina thing or something else I'd done. But I'm fairly sure I remember it working on Catalina - however I recently upgraded, so things in my head are a little garbled.

If it helps at all, this is the error I'm getting in the DevTools:

```
Error: connect ECONNREFUSED /Users/jacob/.ServiceHub/5861e5a531/5861e5a531
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
From previous event:
    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)
    at Function.defer (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/node_modules/q/q.js:582:19)
    at netConnect (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/connect.js:31:22)
    at netConnectWithTimeout (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/connect.js:42:12)
    at /Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/connect.js:51:44
    at _fulfilled (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/node_modules/q/q.js:834:54)
    at /Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/node_modules/q/q.js:796:13)
    at /Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/node_modules/q/q.js:604:44
    at runSingle (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/node_modules/q/q.js:137:13)
    at flush (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/node_modules/q/q.js:125:13)
    at ZoneDelegate.invokeTask (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:275:35)
    at Zone.runTask (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:151:47)
    at ZoneTask.invoke (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:345:33)
```

There is a folder located at `/Users/jacob/.ServiceHub/5861e5a531`, but nothing inside it.

I'm happy to assist debugging this issue by way of providing any more information, and running any commands to provide that information.

Would be great to get this issue resolved before I get back to work, because not having access to it on the last week of work before we broke up for Christmas break was a little annoying.

**Comment by jmshal** [comment]
I wasn't able to fix the issue locally by deleting the `~/Library/Application Support/StorageExplorer` folder, but downgrading to 1.10.x worked for me.

It also didn't help me running the .app outside the `/Application` folder. (In regards to https://github.com/microsoft/AzureStorageExplorer/issues/2463#issuecomment-567098785).

**Comment by w-l0f** [comment]
I have this same issue. Running macOS Catalina 10.15.2 and Storage Explorer 1.12.0.
I have no `StorageExplorer` folder in `~/Library/Application\ Support/`, so nothing for me to delete there.

![image](https://user-images.githubusercontent.com/7420587/72606518-07737d00-391f-11ea-8aed-38682228c9f2.png)

**Comment by JasonYeMSFT** [comment]
Hi all, we just notarized our v1.12.0 release. Could you please try installing the 1.12.0 from storageexplorer.com

**Comment by mhammons** [comment]
I installed v1.12.0 and I thought it was hanging again, but, after about 20 minutes it finally connected. Closing and re-opening is faster, but still takes about 1-2 minutes to actually open and load.

**Comment by jaltin** [comment]
I also had this problem and none of the fixes  to delete folders etc. suggested in this issue worked for me.

Upgrading to 1.12.0 worked though.

**Comment by MRayermannMSFT** [comment]
Sounds like upgrading to 1.12.0 is fixing this issue. If anyone is still having problems please open a new issue and include specific information for what you are seeing. Thanks.

**Comment by mhammons** [comment]
I personally feel there are still issues....no application should take 20 minutes or more to open. After any reboot it takes that long to connect. Friday it was closer to 30 minutes to open.

**Comment by jmshal** [comment]
Please could this be re-opened. For some strange reason, 1.12.0 was working fine, and now it's not. It's been about a week since I noticed it stopped working on me, and still isn't working. I haven't update the app, nor my OS version. I'm experiencing the same issue as before (just a spinner with "Loading..." in the sidebar, where the storage accounts would usually show). And I'm seeing the same error message I was seeing, in the Chrome DevTools, as I was in my earlier comment - https://github.com/microsoft/AzureStorageExplorer/issues/2463#issuecomment-569197665.

**Comment by jinglouMSFT** [comment]
@jmshal  can you try to delete the files in the following folder:

**Comment by jinglouMSFT** [comment]
@jmshal  can you make sure you use 1.12.0 build 20200116.10?  This is the current 1.12.0 build on http://storageexplorer.com you can download and it's notarized.  We have seen a similar issue in early builds without the notarization.  Let us know if this helps.  Thanks.

**Comment by jmshal** [comment]
Thanks @jinglouMSFT, that worked.

However I'm curious now as to why manually checking for updates shows no updates? I understand the version number didn't change between the build I was on, and the latest build, but surely that would have been a good opportunity to bump the patch version, so people with the one build were able to update to a version which actually works for them. There's never a time I would think of going to storageexplorer.com to find out if I'm running an older build.

**Comment by jinglouMSFT** [comment]
@jmshal installing directly from http://storageexplorer.com vs installing through updates runs different setup path.  Installing from http://storageexplorer.com removes your old copy of Storage Explorer and its dependencies while updating only does delta install.  I just wanted to make sure you had a cleaner install to rule out the possibility of some leftover components that didn't get updated correctly.  Glad a clean install helped.
