### ISSUE TITLE
It is better to translate 'Id' to '識別碼' instead of 'ID' in Manage Access Policies dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2467]
**Storage Explorer Version:** 1.11.1
**Build:** [20191219.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3333353)
**Branch:** master
**Language:** Chinese(zh-TW)
**Platform/OS:** Windows 10/ CentOS 7.6.1810 /macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '繁體中文' -> Restart Storage Explorer.
3. Expand a storage account -> Blob Containers.
4. Select one blob container and right click it ->Click '管理存取原則...' -> Click '新增'.
5. Check the localized Id in Manage Access Policies dialog.

**Expect Experience:**
 Id is translated to 識別碼.

**Actual Experience:**
 Id is translated to ID.

![image](https://user-images.githubusercontent.com/41351993/71162164-aa37cd80-2285-11ea-9925-0597de2653ea.png)

**More Info:**
1. For one message ID in queue.
In zh-TW ID is localized as '識別碼'.
![image](https://user-images.githubusercontent.com/41351993/71162337-ff73df00-2285-11ea-879f-320d18f6d8d4.png)

   ENU screenshot:
   ![image](https://user-images.githubusercontent.com/41351993/71162354-0864b080-2286-11ea-9fa8-3fb993b06aa8.png)

2. This issue also reproduces for one file share/ queue/ table. 
3. ENU screenshot for Manage Access Policies dialog.
![image](https://user-images.githubusercontent.com/41351993/71163721-9fcb0300-2288-11ea-9f90-3a6e38028549.png)

**Comment by lukaschal** [comment]
On review.

0; "Properties.DocumentDB.Id"
0; "TableView.IDHeader"

**Comment by johnliu2016** [comment]
It's better to translate 'ID'/'Id' to '識別碼'

**Comment by v-xianya** [comment]
This issue still reproduces on the latest build 20200108.3.

**Comment by johnliu2016** [comment]
Fixed above location
