### ISSUE TITLE
There are strings not localized in delete file share dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2469]
**Storage Explorer Version:** 1.11.1
**Build:** [20191220.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3336432)
**Branch:** master
**Language:** Chinese(zh-TW)/ Chinese(zh-CN)/ Japanese/ Korean
**Platform/OS:** Windows 10/ CentOS 7.6.1810 /macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '日本語' -> Restart Storage Explorer.
3. Expand a storage account -> File Shares.
4. Select one file share and right click it -> Click '削除'.
5. Check the delete dialog.

**Expect Experience:**
All strings are localized in delete dialog.

**Actual Experience:**
There are strings not localized in delete dialog.
![image](https://user-images.githubusercontent.com/41351993/71238506-335f0b00-233f-11ea-9cdc-9540906390d7.png)

**More Info:**
1. This issue doesn't reproduce for one blob container.
2. This issue reproduces for one queue/ table.
3. This issue also reproduces in Chinese(zh-TW)/ zh-(CN).
![image](https://user-images.githubusercontent.com/41351993/71239637-03fdcd80-2342-11ea-8c47-5c8a474f5108.png)

**Comment by johnliu2016** [comment]
Sending to localization for review

**Comment by johnliu2016** [comment]
Resource ID: 0;"String Table"\0;"Strings"\0;"Actions.BlobContainers.Delete.ConfirmInAccount"
Relative File Path: drop\loc\en\src\Standalone\resources\Azure.json.lcg​
Project: StorageExplorer​
Subtenant: StorageExplorer

ENU: This will permanently delete the blob container '%1$s' in storage account '%2$s'. \r\n\r\nAre you sure you want to delete this blob container and its contents?

**Comment by johnliu2016** [comment]
@craxal, the build behavior looks strange on UI, source string doesn't contain 'in storage account' substring to localize, but appear in individual locale strings. Could you please confirm the build info that is used for verification? I assume each loc string in issue is not from official localization

**Comment by MRayermannMSFT** [comment]
We suspect it is a hardcoded string issue. We'll look into it.

**Comment by JasonYeMSFT** [comment]
We have the same problem for queue/table as well. We need to replace the template strings to fix the problem.

**Comment by JasonYeMSFT** [comment]
This should have been fixed for file share/queue/table, please verify.

**Comment by v-limu** [comment]
Verified on build  20200317.2. This issue has been fixed. So we close it.
