### ISSUE TITLE
Rename blob virtual folder has no feedback

### ISSUE THREAD

**Issue by codificador-nocturno** [Microsoft/AzureStorageExplorer#247]
**Storage Explorer Version**: 1.1.0
**Platform**: macOS
**Architecture**: x64
**Regression From**: Not known

#### Steps to Reproduce: ####
1. Select a virtual folder
2. Hit Rename Button on bar
3. Input a new name on dialog
4. Hit Rename button on dialog

#### Expected Experience: ####
I know It can take some time to rename a virtual folder with a lot of items. I would expect to see a confirmation:  "This is being done server side, you can close the app and check back later"  or "This is done client side, please wait and keep the app open". I would expect some progress info in the activities panel.

#### Actual Experience: ####
See nothing, no messages, no progress, no errors.

**Comment by craxal** [comment]
That's odd. I would've expected an activity to pop up for that. I assume, since this is a virtual folder, we're talking about blobs. Does the rename actually succeed?

**Comment by codificador-nocturno** [comment]
Hi, yeah, we're talking about blobs. It seems the rename didn't succeed. Thanks.

**Comment by craxal** [comment]
I'm not having any success reproducing. Rename still seems to work and add an activity to the log.

What kind of account does this container belong to? Are you using a key or SAS to connect to your blob container? What's the structure for this folder like? Lots of files? Large files? Deep paths?

**Comment by codificador-nocturno** [comment]
Hi, not sure what kind of account, because it's not managed by me; Not using SAS, just username and pwd from azure panel.

Folder structure has not deep paths, nor large files. It has many files 74000, approx. They only thing we have seen it's that it contained a lot of hidden files (started with dot in macOS).

Thanks.

**Comment by craxal** [comment]
If you signed in, sounds like it's an ordinary sign-in account we retrieve from the subscription, right?

The type of account should be visible if you select the account node in the tree view and scan it's properties in the Properties tab. You should see information about the account, such as whether it's a blob account, premium account, or standard account.

We recently released 1.2.0. Would you mind updating and seeing if the problem still occurs? What if you try doing it in smaller batches?

**Comment by codificador-nocturno** [comment]
Hi, what we tried was deleting the old dir and reuploading with the new name but removing the meta dirs "__MACOSX" before re-uploading. This way everything went fine. 

We will update to 1.2.0 and let you know if this happens again. Thanks.
