### ISSUE TITLE
The descriptions display incompletely in 'Connect File Share to VM' dialog 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2471]
**Storage Explorer Version:** 1.11.1
**Build:** [20191220.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3336432)
**Branch:** master
**Language:** Japanese/ German / Russian/ French
**Platform/OS:** Windows 10
**Architecture:** ia32
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '日本語' -> Restart Storage Explorer.
3. Expand one storage account -> File Shares.
4. Open one file share -> Click localized 'Connect VM'.
5. Check 'Connect File Share to VM' dialog.

**Expect Experience:**
The descriptions display completely.

**Actual Experience:**
The descriptions display incompletely.
![image](https://user-images.githubusercontent.com/41351993/71241008-7cb25900-2345-11ea-88bc-052798352a01.png)

**More Info:**
1. This issue doesn't reproduce on Linux / MacOS.
2. ENU screenshot:
![image](https://user-images.githubusercontent.com/41351993/71241377-6b1d8100-2346-11ea-9a71-720df7d506e8.png)

**Comment by lukaschal** [comment]
Localized 4months ago.

File: loc\en\src\Standalone\resources\ConnectFileShareDialog.json
ID: 0; "MessageConnectInstructions"
SRC: To connect to this file share, run the following command from any Azure Windows virtual machine:
TGT: このファイル共有に接続するには、任意の Azure Windows 仮想マシンから次のコマンドを実行してください:

**Comment by v-xianya** [comment]
@lukaschal This issue also reproduces in German.🙁
![image](https://user-images.githubusercontent.com/41351993/71463682-28e6ba80-27f2-11ea-9e15-22f64e2ac436.png)

**Comment by johnliu2016** [comment]
We're taking a further review

**Comment by johnliu2016** [comment]
The title string resides in StorageExplorer\src\Standalone\app\dialogs\ConnectFileShare\ConnectFileShareView.html

<title>Microsoft Azure Storage Explorer - Connect File Share to VM</title>

@craxal, the html seems not exposed to localization

**Comment by v-limu** [comment]
This issue also reproduces in Russian.
![image](https://user-images.githubusercontent.com/54055206/71615406-274f3500-2bec-11ea-8354-2c59f3241e26.png)

**Comment by v-xianya** [comment]
This issue also reproduces in French on Windows.
![image](https://user-images.githubusercontent.com/41351993/71654949-7376b280-2d6f-11ea-8eaf-02a46fd4ac3f.png)

**Comment by lukaschal** [comment]
@craxal Problem is that lowest string is truncated or not visible when first sentence is larger than one line. Non-resizable on localization side.

File: loc\en\src\Standalone\resources\ConnectFileShareDialog.json
ID: 0; "MessagePrimaryKeyWarning"
SRC: Primary key could be used to do more than just read/write from the mounted drive.

**Comment by craxal** [comment]
We just need to increase dialog height.
