### ISSUE TITLE
'Insert' is not localized in Add Entity dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2472]
**Storage Explorer Version:** 1.11.1
**Build:** [20191220.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3336432)
**Branch:** master
**Language:** Japanese/ Korean
**Platform/OS:** Windows 10/ CentOS 7.6.1810/ MacOS High Sierra
**Architecture:** ia32/ x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '日本語' -> Restart Storage Explorer.
3. Expand one storage explorer -> Tables.
4. Create one table -> Click ‘追加’ on the toolbar.
5. Check 'Insert' button in 'Add Entity' dialog.

**Expect Experience:**
'Insert' is localized.

**Actual Experience:**
'Insert' is not localized.
![image](https://user-images.githubusercontent.com/41351993/71241629-10d0f000-2347-11ea-8e93-a0e3185a7106.png)

**Comment by v-xianya** [comment]
This issue also reproduces for Import Entities dialog.
![image](https://user-images.githubusercontent.com/41351993/71436906-451f2480-272a-11ea-8ac6-beef68e02ecf.png)

**Comment by johnliu2016** [comment]
Sending to localization for review

**Comment by johnliu2016** [comment]
Localized "Insert" to Korean and Japanese in below cases, please check again for new build later than 1/10

Resource ID: 0;"String Table"\0;"Strings"\0;"ButtonInsert"
Relative File Path: drop\loc\en\src\Standalone\resources\EntityEditorDialog.json.lcg​
Project: StorageExplorer​
Subtenant: StorageExplorer

Resource ID: 0;"String Table"\0;"Strings"\0;"InsertButtonLabel"
Relative File Path: drop\loc\en\src\Standalone\resources\ImportEntitiesDialog.json.lcg​
Project: StorageExplorer​
Subtenant: StorageExplorer

**Comment by lukaschal** [comment]
@v-xianya Could you please verify this on latest build ?

**Comment by v-limu** [comment]
Hi @lukaschal 
Verified on build [20200201.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3434212&view=results). This issue has been fixed. So we close it.
