### ISSUE TITLE
There are strings not localized in Connect dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2473]
**Storage Explorer Version:** 1.11.1
**Build:** [20191220.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3336432)
**Branch:** master
**Language:** Japanese
**Platform/OS:** Windows 10/ CentOS 7.6.1810/ MacOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '日本語' -> Restart Storage Explorer.
3. Open Connect dialog -> Check the strings in the dialog.

**Expect Experience:**
All strings that need to be localized are localized.

**Actual Experience:**
There are strings not localized.
![image](https://user-images.githubusercontent.com/41351993/71242270-92754d80-2348-11ea-96ca-d0dd242cc9e3.png)

**Comment by v-limu** [comment]
**More Info:**
This issue also reproduces in '**Storage Accounts**' context menu.
![image](https://user-images.githubusercontent.com/54055206/71245172-1df1dd00-234f-11ea-860b-ba210c228344.png)

**Comment by johnliu2016** [comment]
Sending to localization review

**Comment by lukaschal** [comment]
All terms left in English in the spreadsheet are approved terms in Term Studio. Therefore, they should be left in English as they are.

**Comment by lukaschal** [comment]
@v-xianya Could you please close this issue ? Confirmed that strings are translated correctly in this case.
