### ISSUE TITLE
'Shared Access Signature' is not localized in Storage Explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2474]
**Storage Explorer Version:** 1.11.1
**Build:** [20191220.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3336432)
**Branch:** master
**Language:** Japanese
**Platform/OS:** Windows 10/ CentOS 7.6.1810/ MacOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '日本語' -> Restart Storage Explorer.
3. Select one storage account  -> Check the context menu.

**Expect Experience:**
All strings are localized.

**Actual Experience:**
The string 'Shared Access Signature' is not localized.
![image](https://user-images.githubusercontent.com/41351993/71243382-34963500-234b-11ea-96f9-0dde10d8798f.png)

**More Info:**
1. For one attached item. The string 'Shared Access Signature' is not localized in Properties panel.
![image](https://user-images.githubusercontent.com/41351993/71243132-94d8a700-234a-11ea-82f3-807af8710f30.png)
2. The string 'Shared Access Signature' is not localized on one **blob container/ file share/ queue/ table/ blob/ file** context menu.
3. The string 'Shared Access Signature' is not localized in **Generate Shared Access Signature** dialog.
![image](https://user-images.githubusercontent.com/41351993/71244585-d028a500-234d-11ea-9855-d3b46e4d8cd4.png)

**Comment by lukaschal** [comment]
Correct according to termstudio. On review.

https://termstudio.azurewebsites.net/ViewData.aspx?tid=1859267&langCode=Japanese

**Comment by johnliu2016** [comment]
Per linguistic opinion, by design not to localize
