### ISSUE TITLE
'Opt in to Insider Builds' is not localized completely under Help menu in Japanese

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2475]
**Storage Explorer Version:** 1.11.1
**Build:** [20191220.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3336432)
**Branch:** master
**Language:** Japanese
**Platform/OS:** Windows 10/ CentOS 7.6.1810/ MacOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '日本語' -> Restart Storage Explorer.
3. Click localized Help -> Check the localized 'Opt in to Insider Builds' in dropdown list.

**Expect Experience:**
'Opt in to Insider Builds' is localized completely.

**Actual Experience:**
'Opt in to Insider Builds' is not localized completely.
![image](https://user-images.githubusercontent.com/41351993/71245493-ca33c380-234f-11ea-8ebd-b9833e85ee0d.png)

**Comment by lukaschal** [comment]
On review.

**Comment by johnliu2016** [comment]
Per linguistic, it's by design not to localize the 'Insider'.
