### ISSUE TITLE
The string 'Authentication Library' is not localized in Settings 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2476]
**Storage Explorer Version:** 1.11.1
**Build:** [20191220.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3336432)
**Branch:** master
**Language:** Japanese
**Platform/OS:** Windows 10/ CentOS 7.6.1810/ MacOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '日本語' -> Restart Storage Explorer.
3. Open 'Settings' -> Select localized Application.
4. Check the MSAL descriptions in Sign-in part.

**Expect Experience:**
All strings that need to be localized have been localized.

**Actual Experience:**
The string 'Authentication Library' is not localized.
![image](https://user-images.githubusercontent.com/41351993/71245993-d704e700-2350-11ea-8b3d-30c37a4d9d8a.png)

**More Info:**
1. The string 'Authentication Library' is localized in Chinese(zh-CN)& Chinese(zh-TW).
zh-CN sceenshot:
![image](https://user-images.githubusercontent.com/41351993/71246323-627e7800-2351-11ea-9700-228db29a5599.png)

**Comment by lukaschal** [comment]
On review.

**Comment by johnliu2016** [comment]
Translated "Authentication Library" instances to Japanese.

**Comment by lukaschal** [comment]
@v-xianya Could you please verify this on some latest build ?

**Comment by v-xianya** [comment]
@lukaschal 
This issue has been fixed on build [20200122.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3404394). So close it.
