### ISSUE TITLE
Account type dropdown list are not localized in 'Upload VHD' dialog

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2477]
**Storage Explorer Version:** 1.11.1
**Build:** [20191220.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3336432)
**Branch:** master
**Language:** Japanese / German
**Platform/OS:** Windows 10/ CentOS 7.6.1810/ MacOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '日本語' -> Restart Storage Explorer.
3. Expand Disks -> Select a resource group -> Open it -> Click localized 'Upload' on toolbar.
4. Check the localized **Account type** dropdown list in the dialog.

**Expect Experience:**
The options of the Account type dropdown list are localized.

**Actual Experience:**
The options of the Account type dropdown list are not localized.
![image](https://user-images.githubusercontent.com/54055206/71245542-ed5e7300-234f-11ea-9229-89232de42773.png)

**More Info:**
This issue also reproduces in 'Paste Disk' dialog.
![image](https://user-images.githubusercontent.com/54055206/71245578-01a27000-2350-11ea-98c0-9b0d00d9fb51.png)

**Comment by johnliu2016** [comment]
sending to localization for review

**Comment by lukaschal** [comment]
"Premium" and "Standard" are the names of the plan, which should always be left in English to differentiate from the generic words.

**Comment by lukaschal** [comment]
@v-limu Looks like these names should stay untranslated, according to answer above.
