### ISSUE TITLE
Show an inconsistent order for the two nodes under 'Local & Attached' between English and Chinese

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2478]
**Storage Explorer Version:** 1.11.1
**Build:** [20191220.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3336432)
**Branch:** master
**Language:** Chinese (zh-CN)/ Chinses zh-TW/ Korean / Czech / Dutch
**Platform/OS:** Windows 10/ CentOS 7.6.1810/ MacOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '繁體中文' -> Restart Storage Explorer.
3. Expand Localized 'Local & Attached'.
4. Check the order between the localized '(Attached Containers)' and '(Emulator - Default Ports)(Key)'.

**Expect Experience:**
Show a consistent order for the two nodes.

**Actual Experience:**
Show an inconsistent order for the two nodes.
![image](https://user-images.githubusercontent.com/54055206/71246334-6611ff00-2351-11ea-89e0-d9c55d48047f.png)
ENU Screenshot：
![image](https://user-images.githubusercontent.com/54055206/71246376-7d50ec80-2351-11ea-9beb-d403d040e1c8.png)

**Comment by johnliu2016** [comment]
Sending to localization review

**Comment by johnliu2016** [comment]
Ordering seems not controllable by loc, @craxal could you please take a look?

**Comment by craxal** [comment]
I'm not 100% sure this is a localization issue.

@MRayermannMSFT @JasonYang-MSFT One of you recently did some work related to node ordering, didn't you? Can either of you check into this?

**Comment by MRayermannMSFT** [comment]
Let's keep Attached node first, and then the Emulator.

**Comment by JasonYang-MSFT** [comment]
No, I didn't. You may at wrong person.

**Comment by v-limu** [comment]
Verified on build [20200128.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3397152). This issue also reproduce in **Czech**.
![image](https://user-images.githubusercontent.com/54055206/72675878-cbc6e780-3ac5-11ea-95cf-d79c10eab17b.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
