### ISSUE TITLE
Error downloading Disk

### ISSUE THREAD

**Issue by kblack-asg** [microsoft/AzureStorageExplorer#2479]
I'm having a problem with Azure storage Explorer.. I'm not able to download a disk that boots fine.

I keep receiving this error. 

the MD5 hash of the data, as we received it, did not match the expected value, as found in the Blob/File Service. This means that either there is a data integrity error OR another tool has failed to keep the stored hash up to date. When Checking MD5 hash. X-Ms-Request-Id: 

Any thoughts on how to get around this error?

**Comment by MRayermannMSFT** [comment]
Hi @kblack-asg , if you go to Settings -> Transfters -> AzCopy, there is a setting for MD5 checking. Simply change that to be "No check", and then your download should work.

**Comment by kblack-asg** [comment]
Thanks Matthew.. I will test it!



Thanks

Kevin Black

Senior Systems Engineer
kblack@asg-us.com<mailto:kblack@asg-us.com>
[Description: signature block ASG only]

6660 South Sheridan Road
Ste 160
Tulsa, OK 74133
918-523-2700
918-523-2707 (Fax)

**Comment by MRayermannMSFT** [comment]
@kblack-asg did that work for you?

**Comment by kblack-asg** [comment]
Yes, Sir.. Thanks for the followup.
