### ISSUE TITLE
GPU Error when starting

### ISSUE THREAD

**Issue by jasonrmartin** [microsoft/AzureStorageExplorer#248]
**Storage Explorer Version**: 1.1.0
**Platform**: Windows
**Architecture**: ia32
**Regression From**: <0.7

#### Steps to Reproduce: ####
1. Just starting the application

#### Expected Experience: ####
Start fine

#### Actual Experience: ####
Receive an error saying "A problem caused Storage Explorer to restart with GPU acceleration disabled"

![storage-explorer-error](https://user-images.githubusercontent.com/6273432/40875465-92f06878-6646-11e8-8620-a8d0afcc83ae.png)

**Comment by craxal** [comment]
What version is your OS? Does the error go away if you start Storage Explorer with the indicated flag?

**Comment by jasonrmartin** [comment]
Windows 10 Pro v1803 Build 17134.81,

Yes it does go away if I use that flag.



Thanks,

Jason Martin
Digital Pioneers
m: (678) 800-4253

**Comment by JasonYeMSFT** [comment]
We have done some work to allow you to disable GPU acceleration if you have GPU issues. Please try our latest 1.12.0 and open a new issue if you still have any problems. Thanks.
