### ISSUE TITLE
Keep a consistent button name between undelete dialog 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2483]
**Storage Explorer Version:** 1.11.2
**Build:** [20191220.9](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3338616)
**Branch:** hotfix/1.11.2-to-master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core)/ MacOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1.  Expand one GPV2 storage account -> Enable soft delete policy for Blob Containers.
2.  Create a blob container -> Upload one blob.
3.  Delete the uploaded blob -> Switch to 'Active and deleted blobs' -> Right click the deleted blob. 
4.   Select 'Undelete Selected' and 'Undelete by Date... ' respectively -> Check button name on the two Undelete dialog.

**Expect Experience:**
Keep a consistent button name.

**Actual Experience:**
Display an inconsistent button name.
![image](https://user-images.githubusercontent.com/41351993/71349187-57258980-25a9-11ea-9d36-e55c0ff735a2.png)

**More Info:**
1. It is better to update title of Undelete dialog to 'Undelete Selected Blobs'.
![image](https://user-images.githubusercontent.com/41351993/71349302-a8357d80-25a9-11ea-8318-afd215040a21.png)

**Comment by MRayermannMSFT** [comment]
Change by date dialog to say "OK"
