### ISSUE TITLE
Impossible to connect to Azure

### ISSUE THREAD

**Issue by acuity-data** [microsoft/AzureStorageExplorer#2484]
**Storage Explorer Version**: 1.11.2
**Build Number**: 20191217.4 
**Platform/OS**: Mac OS Catalina 10.15.2
**Architecture**: x64
**Regression From**:  all
## Bug Description ##

Impossible to connect, whatever means used. there is a waiting circle turning in the explorer panel
It used to work perfectly, then updated to 1.11.2 then cannot connect anymore.
To note, no error, just endless waiting circle.

## Steps to Reproduce ##
launch, set a connection method (connection string or name+key)

## Expected Experience ##

it should be connecting properly...

## Actual Experience ##

The app does not connect to Azure as it used to

## Additional Context ##

It would help GREATLY to list ALL the steps needed to FULLY uninstall the app.
I feel like I'm not deleting everything (storage Explorer in library + ???)

**Comment by projuljustin** [comment]
I'm having the same issue, Storage Explorer Version 1.11.2, Mac OS Catalina 10.15.2

**Comment by levixie** [comment]
i have the same issues for  Storage Explorer Version 1.11.2, Mac OS Catalina 10.15.2

**Comment by JasonYeMSFT** [comment]
Hi all, are you having similar issue to #2463? The installation step used to be as simple as moving the content into your Application folder. However, we recently run into some Catalina specific issues and unfortunately we don't have a good solution so far.

Some other customer found launching Storage Explorer from his Downloads folder works around for him. If an older version does work for you, you can also use that version as a work around. We are actively tracking these issues and will make a fix as soon as we figure out the cause.

**Comment by MRayermannMSFT** [comment]
Might also be due to notarization: https://github.com/microsoft/AzureStorageExplorer/issues/2395

**Comment by andreacassioli** [comment]
Still cannot connect here! Any clue??

**Comment by JasonYeMSFT** [comment]
@andreacassioli , can you tell us the platform you are on? Also have you upgraded to the latest v1.12.0 (with build number 20200116.10)? Let us know if you are still seeing this issue on that exact build number.

**Comment by andreacassioli** [comment]
@JasonYang-MSFT yes updating did the trick.

**Comment by jinglouMSFT** [comment]
@andreacassioli Glad this works.  FYI, v1.12.00 (build 20160116.10) is Mac notarized.
