### ISSUE TITLE
‘Managed Disks’ is not localized in Settings AzCopy part

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2487]
**Storage Explorer Version:** 1.11.2
**Build:** [20191220.9](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3338616)
**Branch:** hotfix/1.11.2-to-master
**Language:** Korean
**Platform/OS:** Windows 10/ CentOS 7.6.1810/ MacOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '한국어' -> Restart Storage Explorer.
3. Open localized 'Settings' -> Select localized 'Transfers' -> AzCopy.
4. Check whether the 'Managed Disks' is localized or not.

**Expect Experience:**
'Managed Disks' is localized.

**Actual Experience:**
'Managed Disks' is not localized.
![image](https://user-images.githubusercontent.com/41351993/71440275-9d105800-2737-11ea-94ba-8a4fb86f4535.png)

**Comment by johnliu2016** [comment]
Sending to localization review

**Comment by johnliu2016** [comment]
'Managed Disks' is an approved proper noun not to be localized.

**Comment by v-xianya** [comment]
@johnliu2016 Thanks for the updates!
Since 'Managed Disks' is a proper noun and not to be localized, so we close it.
