### ISSUE TITLE
There are a part of strings not localized in MSAL description

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2488]
**Storage Explorer Version:** 1.11.2
**Build:** [20191220.9](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3338616)
**Branch:** hotfix/1.11.2-to-master
**Language:** Korean
**Platform/OS:** Windows 10/ CentOS 7.6.1810/ MacOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '한국어' -> Restart Storage Explorer.
3. Open localized 'Settings' -> Select localized 'Application' -> Sign-in.
4. Check the MSAL descriptions.

**Expect Experience:**
All the strings that need to be localized are localized.

**Actual Experience:**
There are a part of strings not localized in MSAL description.
![image](https://user-images.githubusercontent.com/41351993/71440964-4eb08880-273a-11ea-857f-67568f789ba7.png)

**More Info:**
1. This issue doesn't reproduce in Chinese(zh-CN)/ Chinese(zh-TW)/ Japanese.
2. Verified this issue in Chinese(zh-CN)/ Chinese(zh-TW)/ Japanese/ Korean.

**Comment by johnliu2016** [comment]
Sending to localization review

**Comment by johnliu2016** [comment]
"Single Sign-On" is an approved DNT term: https://termstudio.azurewebsites.net/viewdata.aspx?tid=216598. It should not be localized.

**Comment by lukaschal** [comment]
@v-xianya  This is by design according to answer above.
