### ISSUE TITLE
The action 'Clone with New Name...' isn't localized

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2489]
**Storage Explorer Version:** 1.11.2
**Build**: [20191220.9](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3338616)
**Branch**: hotfix/1.11.2-to-master
**Language**: Chinese(zh-CN)/ Chinese(zh-TW) / Japanese / Korean / German / Russian
**Platform/OS**: Windows 10/ CentOS 7.6.1810/ MacOS High Sierra
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '한국어' -> Restart Storage Explorer.
3. Expand one non-ADLS Gen2 storage account -> Blob Containers -> Create a new blob Container -> Right click it.
4. Observe its context menu.

**Expect Experience:**
All actions are localized.

**Actual Experience:**
The 'Clone with New Name...' action isn't localized.
![image](https://user-images.githubusercontent.com/54055206/71441119-1b222e00-273b-11ea-8ad2-49d8ea32b834.png)

**More Info:**
1. This issue also reproduces for one file share.
2. This issue also reproduces for one blob/file.
3. The 'Clone' dialog isn't localized.
![image](https://user-images.githubusercontent.com/54055206/71441140-2f662b00-273b-11ea-8775-d26fd0fb71f0.png)

**Comment by johnliu2016** [comment]
Sending to localization for review

**Comment by johnliu2016** [comment]
Source string changed, waiting for new source string to enter loc pipeline.

**Comment by lukaschal** [comment]
Localized now.

**Comment by lukaschal** [comment]
@v-limu Could you please verify this on latest build ?

**Comment by v-limu** [comment]
Verified on build [20200201.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3434212&view=results
)
This issue still reproduces for one file under one file share in **Korean/ Japanese / French / Spanish/ Chinese(zh-TW)/ Hungarian / Italian /  Polish / Portuguese / Russian / Swedish / Turkish**.
![image](https://user-images.githubusercontent.com/54055206/73626922-821ae880-45ff-11ea-82ea-40fb9e10f214.png)

**Comment by lukaschal** [comment]
Localized at 1/4/2020.

      <Item ItemId=";Toolbar.RenameCommandName" ItemType="0" PsrId="306" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Clone with New Name]]></Val>
          <Tgt Cat="Text" Stat="Loc" Orig="New">
            <Val><![CDATA[使用新名稱複製]]></Val>

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer?path=%2Floc%2Floc%2Fzh-Hant%2Fsrc%2Fcomponents%2Fse-blob-extension%2Fresources%2FBlobEditor.json.lcl&version=GBmaster&_a=blame

**Comment by craxal** [comment]
Strings have been fixed, but the Clone button was bugged from a prior merge. Putting a fix out for that. See #2590.

**Comment by v-xianya** [comment]
Verified this issue on Linux & Windows. (20200212.1) Fixed.
Wait to verify on Mac.

**Comment by v-xianya** [comment]
Verified this issue on Mac. Fixed.
