### ISSUE TITLE
Could not load subscriptions for tenant

### ISSUE THREAD

**Issue by PeterParker1234** [microsoft/AzureStorageExplorer#249]
**Storage Explorer Version**: 1.1.0
**Platform**: Windows
**Architecture**: ia32
**Regression From**: all previous versions have given me the same issue.

#### Steps to Reproduce: ####
1. Open Storage Explorer. See Nothing. Open F12. See error
2. Note that this program just worked well a few minutes before. I am always scared to close the program because of this error. It does not give me the ability to log in again. After I've logged in - when I get the opportunity since there is no menu for this, then it works. After I close it, then I see nothing again.
I have deleted / cleared items in %AppData%/StorageExplorer.
This happens whether I am behind a proxy or not.
This happens when I am connected to an Azure VPN or not.

#### Expected Experience: ####
Sometimes when I am lucky, Azure explorer logs into my accounts and I can see my accounts

#### Actual Experience: ####
 Open Storage Explorer. See Nothing. Open F12. See error : "Could not load subscriptions for tenant"
![imgur1](https://user-images.githubusercontent.com/20321256/40886483-f9d1c922-6738-11e8-8b28-71ad487ab1ae.PNG)
![imgur2](https://user-images.githubusercontent.com/20321256/40886485-fcfa8472-6738-11e8-9b76-df86fb643189.PNG)

**Comment by MRayermannMSFT** [comment]
@PeterParker1234 due to the age of this issue we're going to close it. If you're still having problems, please try using the latest version of storage explorer and then if you're still having problems open a new issue. Thanks.
