### ISSUE TITLE
The popped window title isn't localized when importing certificates

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2490]
**Storage Explorer Version:** 1.11.2
**Build**: [20191220.9](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3338616)
**Branch**: hotfix/1.11.2-to-master
**Language**: Chinese(zh-CN)/ Chinese(zh-TW) / Japanese / Korean
**Platform/OS**: Windows 10/ CentOS 7.6.1810/ MacOS High Sierra
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '한국어' -> Restart Storage Explorer.
3. Click localized 'Edit' -> SSL Certificates -> Import Certificates.
4. Observe the popped window title.

**Expect Experience:**
The popped window title is localized.

**Actual Experience:**
The popped window title isn't localized.
![image](https://user-images.githubusercontent.com/54055206/71441612-26765900-273d-11ea-923b-e68141ee10ed.png)

**More Info:**
This issue also reproduces on 'View Import Certificates' window.
![image](https://user-images.githubusercontent.com/54055206/71441709-91c02b00-273d-11ea-9509-9900267c42f4.png)

**Comment by johnliu2016** [comment]
Sending to localization review

**Comment by johnliu2016** [comment]
"Select SSL Certificates" looks not exposed to localization yet, can only be located in 
StorageExplorer\src\Standalone\app\renderer\SslCertificateManager.ts
`let certsToAdd: string[] = await DialogsManager.showOpenDialog("Select SSL Certificates", false, true);`

**Comment by v-limu** [comment]
Verified on build [20200214.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3472526). This issue has been fixed. So we closed it.
