### ISSUE TITLE
The layout of Remove button in Manage Access Policies shows unfriendly

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2492]
**Storage Explorer Version:** 1.11.2
**Build:** [20191220.9](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3338616)
**Branch:** hotfix/1.11.2-to-master
**Language:** German
**Platform/OS:** Windows 10
**Architecture:** ia32
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Deutsch' -> Restart Storage Explorer.
3. Expand one storage account -> Blob Containers.
4. Select one blob container -> Right click it -> Click localized 'Manage Access Policies...'.
5. Click localized 'Add' to add one access policy -> Slide the scroll bar in the dialog box.
6. Check the localized Remove button.
 
**Expect Experience:**
The layout of Remove button shows friendly.

**Actual Experience:**
1. The layout of Remove button shows unfriendly.
2. There occurs one vertical line and the 'Remove' button exceeds this line.
![image](https://user-images.githubusercontent.com/41351993/71468839-4de32980-2802-11ea-830e-6a8765ab8df7.png)

**More Info:**
1. This issue doesn't reproduce for one file share/ table/ queue.
2. This issue doesn't reproduce after resizing the dialog or zoom out Storage Explorer.
3. This issue doesn't reproduce in Chinese(zh-TW)/ Chinese(zh-CN)/ Korean/ Japanese.

**Comment by johnliu2016** [comment]
Sending to localization for check

**Comment by johnliu2016** [comment]
Button size/position is not controllable by loc. @craxal could you please take a look?

**Comment by v-xianya** [comment]
Screenshot in French:
![image](https://user-images.githubusercontent.com/41351993/71653679-bf722900-2d68-11ea-9b7d-818b9ddb7d0a.png)

**Comment by craxal** [comment]
Let's test this in German and/or Russian, since those strings are usually longer.

**Comment by v-xianya** [comment]
This issue has been fixed on build [20200229.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3514328). So close it.
