### ISSUE TITLE
Can't upload/download under Linux after upgrading to 1.11.2

### ISSUE THREAD

**Issue by yxlijinzhu** [microsoft/AzureStorageExplorer#2493]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**:Linux Ubuntu 16.04 
**Architecture**: x64
**Regression From**:  

## Bug Description ##

Can't upload/download under Linux after upgrading to 1.11.2
But can list folders and files

## Steps to Reproduce ##

Just open any folder, double click one file, it will keep queuing forever

**Comment by JasonYeMSFT** [comment]
Are you using snap? There is a similar issue #2222 that applies to snap installs. A fix will be released in 1.12.0. As a work around for now, you can delete the problematic files given in that issue.

**Comment by yxlijinzhu** [comment]
Thanks! The workaround works for me!
