### ISSUE TITLE
The notification message is not localized in create snapshot dialog for one disk

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2496]
**Storage Explorer Version:** 1.11.2
**Build**: [20191220.9](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3338616)
**Branch**: hotfix/1.11.2-to-master
**Language**: German
**Platform/OS**: Windows 10/ CentOS 7.6.1810/ MacOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Deutsche' -> Restart Storage Explorer.
3. Expand Disks -> Open one resource group -> Try to create snapshot for one disk -> Type an empty string in dialog.
4. Check the notification message.

**Expect Experience:**
The notification message is localized.

**Actual Experience:**
The notification message is not localized.
![image](https://user-images.githubusercontent.com/54055206/71469691-f1353e00-2804-11ea-8d7f-88bae1de4951.png)

**Comment by johnliu2016** [comment]
Sending to localization

**Comment by johnliu2016** [comment]
@craxal, is this requirement a Storage Explorer string?

**Comment by lukaschal** [comment]
Localized at 12/19/2019.

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer?path=%2Floc%2Floc%2Fde%2Fsrc%2Fcomponents%2Fse-managed-disks-extension%2Fresources%2FCreateSnapshotDialog.json.lcl&version=GBmaster

File: loc\en\src\components\se-managed-disks-extension\resources\CreateSnapshotDialog.json
ID: 0; "ErrorNameRequired"
SRC: Snapshot name is required.
TGT: Der Name für die Momentaufnahme ist erforderlich.

**Comment by JasonYeMSFT** [comment]
Verified as fixed.
