### ISSUE TITLE
Mac Install Not Loading main screen (Application Support corruption)

### ISSUE THREAD

**Issue by uofifox** [microsoft/AzureStorageExplorer#2498]
**Storage Explorer Version**: v1.9.0, v1.10.0, v1.11.2, etc.
**Build Number**: 
**Platform/OS**: macOs Majave
**Architecture**: i86
**Regression From**:  don't believe any versions would work

## Bug Description ##
Openning the Azure Storage explorer would not display any windows or settings files.  As I try to open new windows it would give me the Eula screen, but never display the main storage explorer window.  After troubleshooting using the keychains fix,etc. Never got that to change anything.

**Fixed** the issue by deleting the /<user>/Library/Application Support/StorageExplorer folder

(note that I found this location by viewing the imported certificates)

## Steps to Reproduce ##
1.  Try to open Azure Storage Explorer

## Expected Experience ##
Opens the main storage explorer window then asks for Eula and/or to signin to an azure account

## Actual Experience ##
You get the loading window and nothing actually displays

## Additional Context ##
I tried 5 different versions of the application

**Comment by hypertrends** [comment]
Hello, I am facing the same issue as of yesterday. I tried to add an Azure account and the login browser popup also keeps displaying "Loading..." and nothing happens.

**Comment by saumyasuhagiya** [comment]
<img width="1330" alt="Screenshot 2020-01-03 at 12 01 35 PM" src="https://user-images.githubusercontent.com/2899428/71710256-57cbe480-2e21-11ea-9402-27eb6163cf04.png">
Keeps showing Loading.. but nothing comes up.

**Comment by btafel** [comment]
Same here on Mac

**Comment by maleeb** [comment]
That worked for me

<img width="940" alt="Screenshot 2020-01-06 at 10 16 44" src="https://user-images.githubusercontent.com/2753459/71808458-1e3be900-306e-11ea-8454-72ecd819236b.png">

**Comment by MRayermannMSFT** [comment]
This is due to a bug in our auth library. We've merged a fix to be released in 1.12.0
