### ISSUE TITLE
Support multiple languages (localize)

### ISSUE THREAD

**Issue by tsubasaxZZZ** [microsoft/AzureStorageExplorer#250]
**Storage Explorer Version**: 1.10
**Platform**: Windows
**Architecture**: IA32
**Regression From**: 

I would like to correspond to languages other than English.
I can help translate to Japanese.

**Comment by MRayermannMSFT** [comment]
Hey! We did this! 🙃 I'm going to close this since this was done. Feel free to open an issue if you have problems with any translations.
