### ISSUE TITLE
'URI' is translated on Shared Access Signature dialog in Russian

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2500]
**Storage Explorer Version:** 1.11.2
**Build**: [20191220.9](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3338616)
**Branch**: hotfix/1.11.2-to-master
**Language**: Russian
**Platform/OS**: Windows 10/ CentOS 7.6.1810/ MacOS High Sierra
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'русский' -> Restart Storage Explorer.
3. Expand one storage account -> Blob Containers.
4. Select one blob container -> Right click it -> Click localized 'Get Shared Access Signature...'.
5. Click localized 'Create' on dialog -> Check the 'URI' on Shared Access Signature dialog.

**Expect Experience:**
'URI' displays as 'URI'.

**Actual Experience:**
'URI' displays as 'Универсальный код ресурса (URI)'.
![image](https://user-images.githubusercontent.com/41351993/71617902-481d8780-2bf8-11ea-9fdb-7df4ba83a41b.png)

ENU screenshot:
![image](https://user-images.githubusercontent.com/41351993/71617913-510e5900-2bf8-11ea-8e14-d3d6240add3a.png)

**More Info:**
1. This issue doesn't reproduce in Chinese(zh-CN)/ Chinese(zh-TW)/ Korean/ Japanese/ German.
2. This issue also reproduces for one file share/ queue/ table.

**Comment by lukaschal** [comment]
On review.

File: loc\en\src\Standalone\resources\GenerateSasDialog.json
ID: 0; "ConnectionLabel"
SRC: URI:
TGT: Универсальный код ресурса (URI):

**Comment by lukaschal** [comment]
The current translation actually corresponds to Term Studio.
