### ISSUE TITLE
The description of 'Clear All' button shows unfriendly in the Customize Columns dialog

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2501]
**Storage Explorer Version:** 1.11.2
**Build:** [20191220.9](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3338616)
**Branch**: hotfix/1.11.2-to-master
**Language**: Russian/ Turkish/ Portuguese (Portugal)/ Portuguese (Brazil)/ Polish/ Hungarian/Polish/ Dutch/ Spanish/ German
**Platform/OS:** Windows 10
**Architecture**: ia32
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'русский' -> Restart Storage Explorer.
3. Expand one storage account -> Tables.
4. Create a new table -> Open the table -> Click 'Column Options' in the toolbar.
5. Check the 'Clear All' button in the Customize Columns dialog.

**Expect Experience:**
The description of 'Clear All' button shows well.

**Actual Experience:**
The description of 'Clear All' button shows unfriendly.
![image](https://user-images.githubusercontent.com/54055206/71618020-cc700a80-2bf8-11ea-957c-67485c21cbbf.png)
ENU Screenshot:
![image](https://user-images.githubusercontent.com/54055206/71618109-2c66b100-2bf9-11ea-81c5-f2694e12d7bd.png)

**Comment by lukaschal** [comment]
Non-resizable on localization side.

File: loc\en\src\Standalone\resources\CustomizeColumnsDialog.json
ID: 0; "LabelClearAll"
SRC: Clear All
TGT: Очистить все

**Comment by v-limu** [comment]
This issue also reproduces for the localized 'Select All' button in **Spanish**.
![image](https://user-images.githubusercontent.com/54055206/72588304-d0a76200-3932-11ea-84b0-554e970c99e4.png)

**Comment by v-limu** [comment]
This issue also reproduces in **Italian**.
![image](https://user-images.githubusercontent.com/54055206/72873996-08941800-3d2c-11ea-8b87-f7f8a0b0e654.png)

**Comment by v-xianya** [comment]
Verified on build 20200112.3.  Fixed.
