### ISSUE TITLE
Attached Storage Account Error

### ISSUE THREAD

**Issue by RabiaKanwal** [microsoft/AzureStorageExplorer#2502]
**Storage Explorer Version**: 1.11.2
**Build Number**: 
**Platform/OS**: MacOS
**Architecture**: 
**Regression From**: No

## Bug Description ##
I am trying to connect to a storage account and I am getting the following error "Unable to load attached Storage Account. Error: Cannot read property 'version' of undefined" 

## Steps to Reproduce ##
I tried connecting using both Connection string and SAS URL in both cases the connection succeeded but when I started clicking on different sources I witnessed the above error in a dialog box

## Expected Experience ##
I was expecting to access  a client's blob storage for a project by using the provided connection string

## Actual Experience ##
<img width="992" alt="Screenshot 2020-01-01 at 15 57 50" src="https://user-images.githubusercontent.com/52289271/71642751-7494da80-2cb0-11ea-9ef8-b039b6c73332.png">

**Comment by JasonYeMSFT** [comment]
Are you seeing this error the first time you try to attach to some resource or does it just shows up starting from some point? Also, could you please give detailed information of your macOS version? It might help us understand the cause of this problem.

We have a work around for this issue on our troubleshooting guide: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C1804#error-occurred-while-adding-new-connection-typeerror-cannot-read-property-version-of-undefined

**Comment by RabiaKanwal** [comment]
The document helped me troubleshoot the problem now I can connect to the resource I am trying to connect to Thankyou
