### ISSUE TITLE
The content in clear queue dialog is not localized

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2503]
**Storage Explorer Version:** 1.11.2
**Build**: [20191220.9](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3338616)
**Branch**: hotfix/1.11.2-to-master
**Language**: French/ Czech/ Portuguese (Brazil)
**Platform/OS**: Windows 10/ CentOS 7.6.1810/ MacOS High Sierra
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Français' -> Restart Storage Explorer.
3. Expand a storage account -> Queues.
4. Create a new queue and open it -> Click 'Clear Queue' on the toolbar.
5. Check whether the content is localized or not in the popped dialog.

**Expect Experience:**
The content in clear queue dialog is localized.

**Actual Experience:**
The content in clear queue dialog is not localized.
![image](https://user-images.githubusercontent.com/41351993/71660941-8e552100-2d87-11ea-8161-a96eb6625516.png)

**More Info:**
1. Verified this issue in Chinese(zh-CN)/ Chinese(zh-TW)/ Korean/ Japanese/ Russian/ German, this issue doesn't reproduce.

**Comment by lukaschal** [comment]
Localized 3 months ago.

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer/commit/f4912a9ef13198158ca3ef8ef100ebb39f17007f?path=%2Floc%2Floc%2Ffr%2Fsrc%2Fcomponents%2Fse-queue-extension%2Fresources%2FQueueEditor.json.lcl&_a=contents

File: loc\en\src\components\se-queue-extension\resources\QueueEditor.json
ID: 0; "MessageConfirmClear"
SRC: Are you sure you want to clear this queue? Doing so will clear both visible and hidden messages.
TGT: Voulez-vous vraiment effacer cette file d'attente ? Les messages visibles et les messages masqués vont être effacés.

**Comment by JasonYeMSFT** [comment]
Verified as localized.

**Comment by v-xianya** [comment]
1. This issue still reproduces on the latest build master/20200118.1. 
2. This issue also reproduces in Czech.

   So we Reopen it.

**Comment by lukaschal** [comment]
On CSY localized 5 months ago.

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer?path=%2Floc%2Floc%2Fcs%2Fsrc%2Fcomponents%2Fse-queue-extension%2Fresources%2FQueueEditor.json.lcl&version=GBmaster&_a=blame

**Comment by v-xianya** [comment]
Verified this issue on build 20200206.2. 
This issue also reproduces in Czech/ Portuguese (Brazil)/ Turkish/ Polish.

**Comment by JasonYeMSFT** [comment]
@v-xianya, we have published a new package with queue. Please verify the issue.

**Comment by v-xianya** [comment]
@JasonYeMSFT 
Verified this issue on build [20200219.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3482323). Fixed. So we close it.
