### ISSUE TITLE
Storage Explorer fails to load when NODE_OPTIONS contains an invalid value

### ISSUE THREAD

**Issue by ehmPlankje** [microsoft/AzureStorageExplorer#2505]
**Storage Explorer Version**: 1.11.2
**Build Number**: 20191217.4
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  not determined

## Bug Description ##
Storage Explorer fails to load entirely, without any trace, when the environment variable NODE_OPTIONS is set to an alleged invalid value. 

## Steps to Reproduce ##
1. Open the Windows command prompt
2. Set the environment variable `NODE_OPTIONS` with the command: `set NODE_OPTIONS=--max-http-header-size=100000`. (I am aware that this setting is invalid)
3. Run storage explorer with the command: `start C:\"Program Files (x86)\Microsoft Azure Storage Explorer\StorageExplorer.exe"`
4. A process starts and only shows an error message, but Storage Explorer does not start.

## Expected Experience ##
Storage Explorer loads normally or fails with a sensible error message when run from Windows Explorer.

## Actual Experience ##
Storage Explorer doesn't load or show any error message when run from Windows Explorer. When run from the command terminal, the following error message shows: `electron: --max-http-header-size= is not allowed in NODE_OPTIONS`

## Additional Context ##
I needed the increased `max-http-header-size` property for my project, because MSAL.js/Azure AD injects session headers that exceed the default 8kb limit of NodeJS. This causes Webpack Dev server to crash. While I accidentally set it incorrectly in NODE_OPTIONS, this should not be a reason for Storage Explorer to fail without notice.

**Comment by MRayermannMSFT** [comment]
@ehmPlankje this option was introduced in Node 11. We're currently using Node 10, so for now supporting this is not possible. 

Can you explain more about your additional context? Are you saying that you have these environment variables set for something you're working on, but that's conflicting with your use of Storage Explorer?

**Comment by ehmPlankje** [comment]
@MRayermannMSFT, these environment variables are set for the development stack of our app that we are working on, because otherwise Webpack dev server won't work properly in our setup. I don't need this header in Storage Explorer, but I do need it for our app and stack.

We are building a plugin for Outlook. For the frontend, we created a React SPA that uses Office.js. that consumes a Java web app API that we have deployed on Azure. In order to authenticate the user that their instance can access the web app, we use an Azure AD authentication provider that requires the v2.0 Microsoft identity platform.
![image](https://user-images.githubusercontent.com/3234834/71872833-da082180-311d-11ea-9bb6-033be3254073.png) 
Because we didn't want to implement the authentication flow ourself, we chose to use MSAL.js instead. Unfortunately, MSAL.js is rather unstable and buggy. We use MSAL.js with only the redirect flow that we execute in a popup that is triggered with the Office Dialog API, because using the MSAL.js popup flow directly did not work as intended. This gets the job done and the user gets authenticated. However, MSAL.js always throws an error, even when the authentication was succesful. This appears to be an unresolved issue with MSAL.js.
![image](https://user-images.githubusercontent.com/3234834/71873151-ca3d0d00-311e-11ea-9e22-3e0778c56fec.png)

This exception (and other session details) is also stored in a cookie on the domain where the React SPA runs. 
![image](https://user-images.githubusercontent.com/3234834/71874192-8dbee080-3121-11ea-92c0-14a038122416.png)

This cookie however, exceeds the default header limit of Node.js. When the 8kb header limit of Node.js is exceeded, Webpack Dev server ends any request with a HTTP status 400.

To give you an impression of the cookie size and what it looks like:
![image](https://user-images.githubusercontent.com/3234834/71874234-aaf3af00-3121-11ea-92bf-53d02561c77a.png)
It contains this type of information:
```
MicrosoftApplicationsTelemetryDeviceId=<redacted>
MicrosoftApplicationsTelemetryFirstLaunchTime=2019-12-25T09:12:12.724Z
msal.<redacted>.client.info=<redacted>
msal.client.info=<redacted>
msal.<redacted>.error=invalid_state_error
msal.error=invalid_state_error
msal.<redacted>.authority|6995f2d2-4daa-48c9-95c6-041211cb7427=https://login.microsoftonline.com/<redacted>/
msal.authority|6995f2d2-4daa-48c9-95c6-041211cb7427=https://login.microsoftonline.com/<redacted>/
msal.<redacted>.nonce.idtoken|<redacted>=<redacted>
msal.nonce.idtoken|<redacted>=<redacted>
msal.<redacted>.client.info=<redacted>
msal.<redacted>.error=invalid_state_error
msal.<redacted>.idtoken=<redacted>
msal.<redacted>.error.description=Invalid state. 30d8aaa2-13ed-42c8-afc0-07f9fb2e4ae3, state expected : null.
msal.<redacted>.error.description=Invalid state. 0c3260ae-6944-49a0-96ab-fee3e590fe26, state expected : null.
msal.error.description=Invalid state. 0c3260ae-6944-49a0-96ab-fee3e590fe26, state expected : null.
msal.<redacted>.idtoken=<redacted>
msal.idtoken=<redacted>
```

I haven't been able to formulate these issues in a bug report to MSAL.js, because there's so many concurrent issues with the library, that I don't really know how to report them properly to them.

**Comment by MRayermannMSFT** [comment]
@ehmPlankje in our next release, we'll be using a newer version of electron. I can confirm that this version of electron starts, even if NODE_OPTIONS is set to max-http-header-size=100000.
