### ISSUE TITLE
Unable to sign in: ERR_TUNNEL_CONNECTION_FAILED

### ISSUE THREAD

**Issue by Rocky-Liang** [microsoft/AzureStorageExplorer#2506]
{
  "message": "\"ERR_TUNNEL_CONNECTION_FAILED\""
}

**Comment by MRayermannMSFT** [comment]
What OS are you on?

**Comment by Rocky-Liang** [comment]
win10
storage explorer version 1.1.1.2
Not a proxy

**Comment by jinglouMSFT** [comment]
Have you tried to use Device code flow or MSAL to sign-in?  If yes, were you able to sign-in?  Also, have you tried to use Name/Key to connect to any of your storage accounts?  
Is this only happening to this particular machine or all machines you've tried?  Can your co-workers sign in?  Thanks.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.

**Comment by Rocky-Liang** [comment]
Click the login page to flash back.
![2020-03-02 15_52_56-Microsoft Azure Storage Explorer](https://user-images.githubusercontent.com/56328415/75656143-49be0700-5c9e-11ea-9b47-965a440b8146.png)
the page will close.
