### ISSUE TITLE
Open File Dialog Box Feature request

### ISSUE THREAD

**Issue by ibuda** [microsoft/AzureStorageExplorer#2508]
First of all, let me thank you for a great product that we use on a daily basis!

I think that there might be an improvement if we had an option to "remember" the option chosen previously when selecting whether to allow or not opening the file.
![71778610-d60ebf00-2fb8-11ea-8743-40bef92cdbbb](https://user-images.githubusercontent.com/42291858/71831136-fd48b780-30b0-11ea-8e62-90ac34963b55.png)
I understand that it's a security reason the dialog box is there in the first place. But in the case when the user knows that the blob storage is private and secure, and works very often with files, it would be much easier if we could have a checkbox to "Remember the choice" and Open the files automatically from now on.

Once again thank you for your efforts to bring us such a great product.

**Comment by MRayermannMSFT** [comment]
What file are you being asked about? This is not a dialog/message that we generate. It looks like this is something coming from your OS.

**Comment by ibuda** [comment]
@MRayermannMSFT I guess you are right, this is platform-specific. I am running Ubuntu 19.04 and I installed Azure Storage Explorer via snap.
Apparently, it is related to snap asking permission to open the file from `/run/user/100/snap.storage-explorer/` folder, and after googling this issue I understood that there is no way to give snap access to a specific [folder](https://askubuntu.com/questions/1033344/how-to-give-snaps-access-to-somedir).
I am closing this issue.
