### ISSUE TITLE
SQL query disappears when hover

### ISSUE THREAD

**Issue by KristianJakubik** [microsoft/AzureStorageExplorer#2510]
**Storage Explorer Version**: 1.11.2
**Build Number**: 20191217.4
**Platform/OS**: Windows 10
**Architecture**:  x64

## Bug Description ##
In a dark themed application user is not able to read input from predicate field of SQL cosmos db, when he is hovering over with cursor.

## Steps to Reproduce ##
1. Set Azure Storage Explorer to dark mode
1. Go to query of SQL cosmos database
1. Fill any query predicate
1. Hover on input field

## Expected Experience ##
I can see text when I'm hovering on the field.

## Actual Experience ##
I'm not able to see current input.

![AzureStorage](https://user-images.githubusercontent.com/28342527/71852924-3ea18d00-30da-11ea-97c9-1968fe5e7023.gif)

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
