### ISSUE TITLE
Add the action 'Open in Portal' for one blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2511]
**Storage Explorer Version:** 1.12.0
**Build**: [20200107.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3362632)
**Branch**: master
**Platform/OS**: Windows 10/ CentOS 7.6.1810/ MacOS High Sierra
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer -> Select one storage account.
2. Expand the storage account -> Blob Containers.
3. Select one blob container and right click it -> Check its context menu.

**Expect Experience:**
The action 'Open in Portal' displays on the context menu.

**Actual Experience:**
No action 'Open in Portal' displays on the context menu.

**More Info:**
This issue also reproduces for one file share/ queue/ table.

**Comment by MRayermannMSFT** [comment]
Will wait on customer feedback.
