### ISSUE TITLE
The snapshot is leased which created under Snapshots view for one leased blob 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2513]
**Storage Explorer Version:** 1.12.0
**Build**: [20200107.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3362632)
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810/ MacOS High Sierra
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Expand one storage account -> Blob Containers.
3. Create a new blob container -> Upload a blob to it -> Acquire Leased for the blob -> Manage Snapshots.
4. Create snapshot for the leased blob.
5. Check the result.

**Expect Experience:**
The snapshot isn't leased.

**Actual Experience:**
The snapshot is leased.
![image](https://user-images.githubusercontent.com/54055206/71886593-74e11a00-3177-11ea-9086-3812fdc21378.png)

**More Info:**
This issue doesn't reproduce after manually refresh.

**Comment by MRayermannMSFT** [comment]
Won't fix. Snapshots is no longer primary backup scenario.
