### ISSUE TITLE
When trying to log in with an account that is blocked for azure access by one tenant, no access to other tenant

### ISSUE THREAD

**Issue by santo2** [microsoft/AzureStorageExplorer#2514]
**Storage Explorer Version**: 1.11.2
**Build Number**: 20191217.4
**Platform/OS**: windows 10
**Architecture**: x64
**Regression From**:  no

## Bug Description ##
Given I have a user account that has contributor permissions to resources in one tenant
And that user is added to another tenant by another company as a guest user
and in that other tenant, a policy is being added to block access to azure resources
then I can not log in anymore in azure storage explorer. 

- In Storage explorer, press Add account
- Add Azure Account, popup opens to log in
- entering email address
- waiting for authentication keeps (nothing happens, keeps loading)

I have sent this to azure support, and have a ticket, but it seems that the support team doesn't really think this is a big issue. I have tried to contact the company to remove me as a guest user in their active directory, but I don't get any response, meaning that I can not use this tool for as long as no one responds in another company unrelated to my daily work

## Expected Experience ##
I expect to see the resources to which I am permitted to read and write data

**Comment by MRayermannMSFT** [comment]
Hi @santo2 , to dig deeper into why you're not getting all of your tenants we need to collect some logs. Can you please:

# Sign out of Storage Explorer

1. Open Storage Explorer
2. Sign out
3. Close Storage Explorer

# Clean the ServiceHub logs

1. Open File Explorer and go to `C:\Users\your username\AppData\Local\Temp\servicehub` and delete the logs folder

# Set Trace Level

1. In the start menu search for path
2. Choose "Edit the system environment variables" ![image](https://user-images.githubusercontent.com/21112697/72846172-eb404a80-3c54-11ea-8c39-54325a480629.png)
3. In the dialog that pops up, click "Environment Variables...", and then in the next dialog click the first "New...", and finally name the variable SERVICEHUBTRACELEVEL and set the value to be ALL. 
![image](https://user-images.githubusercontent.com/21112697/72846325-38bcb780-3c55-11ea-8d46-055828136a68.png)

4. Hit Ok's until all the dialog's are closed.

# Repro and get us logs

1. Sign in
2. Let all subscriptions load
3. Close Storage Explorer
4. Go back to `C:\Users\your username\AppData\Local\Temp\servicehub`, zip up the logs folder, and attach it here

**Comment by santo2** [comment]
Hi, in attachment the zip and again the recording of what I followed.

[logs.zip](https://github.com/microsoft/AzureStorageExplorer/files/4107141/logs.zip)

[recording.zip](https://github.com/microsoft/AzureStorageExplorer/files/4107142/recording.zip)

I had this error while zipping the folder, I renamed that folder
![Aantekening 2020-01-24 080155](https://user-images.githubusercontent.com/939141/73050385-0773ff80-3e80-11ea-8182-2e57f38a5986.png)

**Comment by MRayermannMSFT** [comment]
You replied! Thank you! Ok I'm looking right now. 😀

**Comment by santo2** [comment]
Hi,

I've had a ticket with the azure support, they mentioned that this has to do with a deny policy on some azure management API, which can be denied by a policy, but has nothing to do with a tenant. 

so just to make sure I'm clear: one company can block access to an Azure API which is tenant inspecific, and thus block login procedures for other tenants :)

**Comment by MRayermannMSFT** [comment]
@santo2 , can you try enabling MSAL and try again?

<img width="339" alt="image" src="https://user-images.githubusercontent.com/21112697/73289581-d3ffe080-41b1-11ea-8ea0-e86bdbc3d0e7.png">

**Comment by santo2** [comment]
Hi @MRayermannMSFT, I just tried, this does not make a change.
Do I need to take any other actions before this option gets used? (clear caches, restart...)

**Comment by MRayermannMSFT** [comment]
Glad it worked. Feel free to leave the setting enabled. The new library is fairly stable. We'll probably move it out of preview fairly soon. It seems to be helping a lot of people (such as yourself!).
