### ISSUE TITLE
Transfers hanging at 99% completion

### ISSUE THREAD

**Issue by agentmorris** [microsoft/AzureStorageExplorer#2515]
**Storage Explorer Version**: 1.11.2
**Build Number**: 20191217.4
**Platform/OS**: Win10
**Architecture**: x64
**Regression From**: Only started experiencing this recently

## Bug Description ##

Transfers are hanging at 99% completion

## Steps to Reproduce ##

Initiate a large transfer in ASE by copy/paste within ASE.  More below on what "large" is.

## Expected Experience ##

Transfer operation in ASE completes when underlying data is transferred.

## Actual Experience ##

Over the last ~1 week (approximately aligned to the most recent ASE update), every "large" (more below re: "large") blob<-->blob transfer I initiate (all within-region, all in SCUS) has hung permanently at 99% completion, though examination of the data shows that the transfer is actual 100% complete.

The "Cancel" button is non-responsive in this state.  This is particularly problematic because the transfer appears to have actually completed, so if the "Cancel" button were responsive, I could allow subsequent queued

This has happened consistently on two different machines, both Win10, one a VM in SCUS, the other a local machine.  Smaller transfers are succeeding on both machines.  

If I had to say what "large" and "small" are, I would put the line at around 1000 blobs and around 100GB (so "large" but not "massive"), but it's difficult to test this rigorously.

I don't have data to conclude that this is specific to blob <--> blob transfers, I just haven't done, for example, local <--> blob transfer at this scale recently.

Screenshot:

![tmp](https://user-images.githubusercontent.com/10235485/71911221-2f493080-3128-11ea-827a-01eda1a6ef5c.png)

## Additional Context ##

AzCopy command (retrieved by clicking "Copy AzCopy Command to Clipboard"), without credentials:

./azcopy.exe copy "https://something.blob.core.windows.net/something/something/?sv=something" "https://something.blob.core.windows.net/something/?se=something" --overwrite=prompt --recursive --s2s-preserve-access-tier=false;

**Comment by JasonYeMSFT** [comment]
We have seen people reporting AzCopy "hangs" at the end of the transfer. We will communicate this issue to the AzCopy team. According to #2029, customers found that increasing the network bandwidth may be able to work around this issue.

**Comment by JasonYeMSFT** [comment]
Also could you please send us an AzCopy log for the hanging transfer?

**Comment by zezha-msft** [comment]
@agentmorris I can help to investigate this issue from the AzCopy side if you could kindly provide the log file.

To confirm, were you doing block blob -> block blob copies?

**Comment by agentmorris** [comment]
Log file sent by email.  Yes, this was a block<->block copy.

**Comment by Plasma** [comment]
I am seeing this problem also.

**Comment by zezha-msft** [comment]
Thanks @agentmorris! We'll study the logs and try to figure out the root cause.

@Plasma could you please send me the logs as well? My email can be viewed from my profile. Thanks!

**Comment by JohnRusk** [comment]
@agentmorris  I'm continuing the investigation started by @zezha-msft.  There's some information which would be very useful, but is only in the _plan_ files, not the log files.  By default plan files are saved in the ".plans" subdirectory under where the logs are.  Could you please take a look, and see if you have files under there that contain the same GUID as the job id (log file name) that you sent to Ze?  if you do, could you zip them all up (there may be 19 or 20 or so of them) and email them to me?  Basically they will contain the same info as the logs... but in a machine readable form and with one extra flag that is important to this bug but not reflected in the logs.
My email address is in my profile.
Thanks heaps, since the plan files may make all the difference to diagnosing this issue.
@Plasma Not sure if you've already sent logs to Ze, but could you also please send me plan files if possible, and include logs too if you have haven't already sent them to Ze.

**Comment by Plasma** [comment]
@JohnRusk Sure, where are the logs located? I can't find them anywhere nor via any of the app menus. Cheers.

**Comment by JasonYeMSFT** [comment]
@Plasma, the location for the log files are at `C:\Users\<your_username>\.azcopy`. Each log file is named by its AzCopy job ID.

**Comment by Plasma** [comment]
Thanks - it didn't happen today, so I will wait until it happens again. I note my problem was a bit different, it just never started (was stuck at the phase where its just trying to figure out how many files it needs to copy).

**Comment by JohnRusk** [comment]
Oh, yes, that is different.  I wonder if the AzCopy engine couldn't reach the source account for some reason.

**Comment by JohnRusk** [comment]
Never mind about plan files. We found enough in the log to diagnose the issue.

**Comment by JohnRusk** [comment]
@Plasma, if you can reproduce your issue, please log it in a new issue.

**Comment by MRayermannMSFT** [comment]
@agentmorris @Plasma can y'all please try repro'ing with Storage Explorer 1.12.0? Included in that verison of ASE is AzCopy 10.3.3 which includes what we believe is a fix for y'all's issue.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.

**Comment by agentmorris** [comment]
Apologies for delayed response.  We have not observed this issue since upgrading to 1.12.0, and have done maybe 5-10 large transfers since then.  That doesn't make it 100% guaranteed that the issue was resolved, since it wasn't 100% deterministic, but I'm... 97% sure the issue has been resolved.
