### ISSUE TITLE
Show an odd string in warning message on ADLS Gen2 blob container's Properties dialog 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2517]
**Storage Explorer Version:** 1.12.0
**Build**: [20200108.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3365959&view=logs)
**Branch**: master
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Expand one ADLS Gen2 account -> Blob Containers.
3. Create a new blob container -> Right click it -> Click 'Properties...' -> Add Property -> Type space in key box.
4. Check the warning message in the dialog.

**Expect Experience:**
Show a correct string in warning message.

**Actual Experience:**
Show an odd string in warning message.
![image](https://user-images.githubusercontent.com/54055206/71968533-15027600-3240-11ea-8e53-bbb9043c8911.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into master
