### ISSUE TITLE
The proper noun 'Managed Disks' is localized in Settings panel

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2518]
**Storage Explorer Version:** 1.12.0
**Build:** [20200108.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3365959)
**Branch:** master
**Language:** Chinese(zh-CN)/ Chinese(zh-TW)
**Platform/OS:** Windows 10/ CentOS 7.6.1810/ MacOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文（简体）' -> Restart Storage Explorer.
3. Open localized 'Settings' -> Select localized 'Transfers' -> AzCopy.
4. Check whether the proper noun 'Managed Disks' is localized or not.

**Expect Experience:**
'Managed Disks' is not localized.

**Actual Experience:**
'Managed Disks' is localized.
![image](https://user-images.githubusercontent.com/41351993/71968982-cdc8b500-3240-11ea-9d51-65b16d660fc9.png)

**More Info:**
ENU screenshot:
![image](https://user-images.githubusercontent.com/41351993/71968995-d325ff80-3240-11ea-94a1-5f7a1aad3ea9.png)

**Comment by lukaschal** [comment]
On review.

**Comment by johnliu2016** [comment]
Similar to #2487, checking with Linguistic

**Comment by lukaschal** [comment]
CHS result: 'Managed Disks' is localized in TermStudio as a approved term.

**Comment by JasonYeMSFT** [comment]
@lukaschal, do you mean we should keep the translated string for "Managed Disks" in this case?

**Comment by lukaschal** [comment]
@JasonYeMSFT Yes it confirmed, that for Chinese(zh-CN) and Chinese(zh-TW) this term should be  localized.

**Comment by lukaschal** [comment]
@v-xianya Confirmed that actual translations are correct.

**Comment by v-xianya** [comment]
Hi @lukaschal  Check with the TermStudio.
'Managed Disks' is a proper noun in **Hungarian /Japanese**. 

Since Managed Disks is localized in the above two languages. So we re-open this issue.

Hungarian screenshot:
![image](https://user-images.githubusercontent.com/41351993/74409542-e3e61880-4e71-11ea-841f-7d9f16986ed7.png)

Japanese screenshot:
![image](https://user-images.githubusercontent.com/41351993/74409556-eea0ad80-4e71-11ea-95a1-51940f8b2660.png)

Enu screenshot:
![image](https://user-images.githubusercontent.com/41351993/74409834-87cfc400-4e72-11ea-8ffb-3551d5bcdf3c.png)

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
New JPN tgt: これらの設定を使用して、AzCopy のパフォーマンスを調整します。AzCopy は、BLOB、ADLS Gen2、Managed Disks に使用されます。

**Comment by lukaschal** [comment]
Confirmed with hungarian linguist that actual translation is correct as is.

**Comment by v-xianya** [comment]
Fxed on build [20200228.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3510155)(In Japanese).So close this issue.
![image](https://user-images.githubusercontent.com/41351993/75516545-b5526b00-5a37-11ea-8585-61050cce9ff2.png)
