### ISSUE TITLE
The ‘Value’ dropdown list for the 'DataTime' type is not localized in Query Builder 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2519]
**Storage Explorer Version:** 1.12.0
**Build**: [20200108.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3365959&view=logs)
**Branch**: master
**Language**: Chinese(zh-TW)/ Chinese(zh-CN)/ Japanese/ Korean / German /French 
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文(简体)' -> Restart Storage Explorer.
3. Expand one storage account -> Tables.
4. Create a new table -> Add an entity -> Open Query builder  -> Select 'Timestamp' Field.
5. Check the dropdown list for the localized 'Value'.

**Expect Experience:**
The ‘Value’ dropdown list is localized.

**Actual Experience:**
The ‘Value’ dropdown list is not localized.
![image](https://user-images.githubusercontent.com/54055206/71968154-4f1f4800-323f-11ea-9f56-cc218ffca67c.png)

**Comment by lukaschal** [comment]
Not exposed to localization for now.

https://devdiv.visualstudio.com/DevDiv/_git/CloudExplorer?path=%2Fsrc%2FCloudHub%2Fts%2FStorageExplorer%2FStorageExplorerConstants.ts&version=GBmaster&_a=contents

**Comment by v-limu** [comment]
Verified on build [20200220.8](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3489167). This issue has been fixed. So we closed it.
