### ISSUE TITLE
Header columns not aligned with content in editors

### ISSUE THREAD

**Issue by v-flyuan** [microsoft/AzureStorageExplorer#252]
**Storage Explorer Version**: 1.2.0
**Platform**: Windows/Linux/Mac
**Architecture**: ia32
**Build Number**: 20180601.6
**Commit**: 16083561
**Regression From**:  Not a regression

#### Steps to Reproduce: ####
1. Launch Storage Explorer and expand Storage Accounts. 
2. Open a blob container editor, verify the items display well.

#### Expected Experience: ####
The content are alignment.

#### Actual Experience: ####
The content aren't alignment.
![alignment](https://user-images.githubusercontent.com/12556995/40909650-a85b1802-681c-11e8-8b1f-ff2495b4b30f.png)

**Comment by craxal** [comment]
This is a long-known issue. I don't think there's anything we can do, since it's a 3rd-party component.

**Comment by MRayermannMSFT** [comment]
It's probably coming from the column resize plugin. We can try updating it, but ya, nothing that can be done on our end.

**Comment by craxal** [comment]
We've already got the latest version (available through Bower).

I have half-a-mind to just dump the component. It does some funky things that interfere with accessibility.

**Comment by v-xianya** [comment]
The column is aligned after refreshing the editor. (Verified this issue on build [20191120.9](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3338616))
![image](https://user-images.githubusercontent.com/41351993/71570467-1a5d1380-2b10-11ea-9cb8-922973390aa3.png)

**Comment by craxal** [comment]
We use jQuery tables for managed disks, too. We don't have the column resize plugins, but I've observed the same problem.

**Comment by rsaa** [comment]
This issue is back. This is a screenshot from version 1.27.

![image](https://user-images.githubusercontent.com/1728603/210456515-8825840a-85e9-47fa-b7ea-fe7cdad992cb.png)

**Comment by craxal** [comment]
See also #5112.

**Comment by JasonYeMSFT** [comment]
This issue has been addressed in all the new React explorers.
