### ISSUE TITLE
There are translation errors in Custom Timestamp Query dialog

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2520]
**Storage Explorer Version:** 1.12.0
**Build**: [20200108.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3365959&view=logs)
**Branch**: master
**Language**: Chinese(zh-CN)
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文(简体)' -> Restart Storage Explorer.
3. Expand one storage account -> Tables.
4. Create a new table -> Add an entity -> Open Query builder  -> Select 'Timestamp' Field -> Select 'Custom...' in 'Value' drop down list.
5. Check the localized strings in Custom Timestamp Query dialog.

**Expect Experience:**
No translation errors.

**Actual Experience:**
There are translation errors.
![image](https://user-images.githubusercontent.com/54055206/71966752-2302c780-323d-11ea-8274-d264c9925abf.png)
ENU Screenshot:
![image](https://user-images.githubusercontent.com/54055206/71966868-534a6600-323d-11ea-8a56-390a6f9852d0.png)

**Comment by lukaschal** [comment]
On review.

**Comment by johnliu2016** [comment]
Checking with linguistic, could potentially impact multiple languages

**Comment by johnliu2016** [comment]
Implemented the fixes where necessary according to linguistic feedback. Specially in CHS, translation of `From` is corrected to `从`, `To` is corrected to `到`
