### ISSUE TITLE
The proper noun ‘Disks’ on Settings panel is localized in zh-CN

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2521]
**Storage Explorer Version:** 1.12.0
**Build:** [20200108.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3365959)
**Branch:** master
**Language:** Chinese(zh-CN)
**Platform/OS:** Windows 10/ CentOS 7.6.1810/ MacOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous build (20191220.9)

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文（简体）' -> Restart Storage Explorer.
3. Open localized 'Settings' -> Select localized 'Services'.
4. Check whether the 'Disks' is localized or not.

**Expect Experience:**
'Disks' is not localized.

**Actual Experience:**
'Disks' is localized.
![image](https://user-images.githubusercontent.com/41351993/71968531-12a01c00-3240-11ea-873c-86ed7013155c.png)

**More Info:**
1. This issue doesn't reproduce in Chinese(zh-TW).
2. ENE screenshot:
![image](https://user-images.githubusercontent.com/41351993/71968584-31061780-3240-11ea-913d-84842508aaf2.png)

**Comment by lukaschal** [comment]
On review.

**Comment by johnliu2016** [comment]
Child issue of #2328, reverted translation.

**Comment by JasonYeMSFT** [comment]
The string reported by the tester is in `Shell.json` with key `TitleDisks`. The translation there also needs to be reverted.

**Comment by johnliu2016** [comment]
Reverted `TitleDisks` in `Shell.json`

**Comment by v-xianya** [comment]
This issue has been fixed on the latest build master/20200115.5.
![image](https://user-images.githubusercontent.com/41351993/72401752-e7f61c00-3787-11ea-8315-75cab1e629bd.png)
