### ISSUE TITLE
No error details in error dialog when using an exist file name to clone one file

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2522]
**Storage Explorer Version:** 1.12.0
**Build:** [20200109.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3369695&view=results)
**Branch:** rel/1.12.0
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ MacOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> File Shares.
2. Create a new file share -> Upload two files to it.
3. After upload successfully -> Select one file and right click it -> Click 'Clone with New Name...'.
4. Specify the new name using another file name.
5. Check the error dialog.

**Expect Experience:**
Show error details in the error dialog .

**Actual Experience:**
No error details in the error dialog 
![image](https://user-images.githubusercontent.com/41351993/72059556-38dfbd80-330d-11ea-908a-1ec23954e0ed.png)

**More Info:**
1. This issue doesn't reproduce for blobs.
![image](https://user-images.githubusercontent.com/41351993/72059650-63317b00-330d-11ea-8be1-159d2f08b469.png)

**Comment by MRayermannMSFT** [comment]
Address along with azcopy for file shares.

**Comment by v-limu** [comment]
Verified on build [20200210.4. ](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3458474)

1. No error details in error dialog when using an exist **folder name to clone one folder**.
2. No error dialog pops up when using an exist **file name to clone one file**.

**Comment by MRayermannMSFT** [comment]
Jason verify that experience is good now that AzCopy is checked in.

**Comment by JasonYeMSFT** [comment]
A fix has been merged. Please verify.

**Comment by v-xianya** [comment]
Verified on build [20200304.6](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3525592). Reproduce.

**Comment by JasonYeMSFT** [comment]
I forgot to sync the CloudExplorer with the Standalone. I'll notify in this thread when it's done.

**Comment by v-xianya** [comment]
Verified this issue on build [20200312.1.](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3544533) Fixed.
![image](https://user-images.githubusercontent.com/41351993/76496845-d58d1b80-6474-11ea-8590-4e7c1072d167.png)
