### ISSUE TITLE
The prompt dialog still pops up after selecting 'Ignore all changes from this file' for one blob file

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2525]
**Storage Explorer Version:** 1.12.0
**Build:** [20200109.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3369695&view=results)
**Branch:** rel/1.12.0
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ MacOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one Non-ADLS Gen2 storage account -> Blob Containers. 
2. Create one blob container -> Upload one text file.
3. Open the text file -> Make changes in the file and save it.
4. Select 'Ignore all changes from this file' in the popped dialog and click 'Apply'.
5. Repeat step3 -> Check the result.

**Expect Experience:**
No prompt dialog pops up.

**Actual Experience:**
The prompt dialog pops up.
![image](https://user-images.githubusercontent.com/41351993/72062426-c40f8200-3312-11ea-8172-3c242055e03c.png)

**More Info:**
There is a similar bug on TFS: [510195](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/510195)

**Comment by MRayermannMSFT** [comment]
@v-xianya, can you confirm that you created 2 blob containers? If so, then this is by design. If you compare the first dialog and the second dialog, you should see that the file paths are different. Yes?

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT 
The previous repro step was a bit problematic. I have updated the repro steps.😥
Could you help to take a look?

**Comment by jinglouMSFT** [comment]
@v-xianya I am a little puzzled. Based on the exact repro steps, I actually would expect the dialog to pop up on the second or third or forth save.  This is because the option you selected was "Ignore all changes from this file" on your first "Apply".  The repeat of step 3 really made us to download a new version of the file, so storage explorer considers it a new file.  I would say this is by-design.

**Comment by v-xianya** [comment]
Hi @jinglouMSFT 
Thanks for your clarification.
Could you help to point out the difference between the options '**Ignore for now and save later**' and '**Ignore all changes from this file**'?

**Comment by v-xianya** [comment]
@jinglouMSFT 
Many thanks for the clarification. Now I understand what you say.
 So we close this issue.
