### ISSUE TITLE
The resources for Storage Explorer always keep loading after updating to 1.11.2 using 'Install Now' on info bar

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2526]
**Storage Explorer Version:** 1.11.1
**Platform/OS:** Windows 10
**Architecture:** ia32
**Regression From:** Not a regression

**Steps to reproduce:**
1. Install and open Storage Explorer with **version release 1.11.1**.
2. Click **Install Now** on info bar -> Install and launch 1.11.2 Storage Explorer.
3. Check the result.

**Expect Experience:**
The resources on the left show well.

**Actual Experience:**
The resources on the left always keep loading.
![image](https://user-images.githubusercontent.com/41351993/72065915-48193800-331a-11ea-9f51-06dd448a7d92.png)

**More Info:**
1. This issue also reproduces when selecting 'Install On Close'.

**Comment by jpatmednax** [comment]
I have the same issue

**Comment by akosibananaman** [comment]
I have the same issue. Still not loading whether on Windows Server 2012 R2 (v1.11.1) or macOS (v1.11.2).

**Comment by MRayermannMSFT** [comment]
This is fixed in 1.12. Our auth library wasn't shutting down its processes in a timely manner.
