### ISSUE TITLE
Downloading of blobs stuck forever when Select All -> Select All Cached (1000 items)

### ISSUE THREAD

**Issue by Plasma** [microsoft/AzureStorageExplorer#2528]
**Storage Explorer Version**: 1.11.2
**Build Number**: 20191217.4
**Platform/OS**: Win10
**Architecture**: x64
**Regression From**:  Yes, I forget which.

## Bug Description ##
When I filter the blob listing, and choose "Select All -> Select All Cached", eg, with 1000 cached items, and then click Download, the status remains on "Transfer from xxx to yyy (using SAS)" for a long time (I give up waiting).

It doesn't even seem to be making progress to download even one file.

I have also had it stuck with < 1000 cached items, so I don't think it needs to be that many cached.

If I select just a handful of items on the screen though, they download fine.

## Steps to Reproduce ##
As above

## Expected Experience ##
It to show progress and download the files.

## Actual Experience ##
It doesn't make any progress, stuck on "Transfer from xxx to yyy (using SAS)"

**Comment by JasonYeMSFT** [comment]
Could you please try running AzCopy from the command line? It seems like AzCopy is being slow at starting the transfer.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you're still having problems.

**Comment by Plasma** [comment]
Hi @MRayermannMSFT this is re-occurring in the latest build, 1.14.2 azcopy 10.5.0:

![image](https://user-images.githubusercontent.com/229209/87740657-1384bc80-c826-11ea-83ed-2830b5ea03ba.png)

The Activities pane just says: `Transfer from 'my-container/my-folder/' to 'c:\download' starting (using SAS)`

Ahead of time I cleared the logs and deleted the plans folder from `C:\Users\username\.azcopy\`  and then opened storage explorer, and started this process.

Its been sitting here for 10 minutes but its only created the `plans` folder (blank), and no logs appear.

I can keep reproducing this, I am:
1. Loading a container, going to a folder
2. Filtering using the topright search to a prefix
3. "Load More" bottom right clicked
4. Select All - >Select All Cached
5. Download -> pick folder

Then I'm in this state.

**Comment by Plasma** [comment]
@MRayermannMSFT it kind of also happens when downloading a single page. I wonder if its because the directory in /my-folder has many items, and the 'download this page' logic is trying to scan the entire (unfiltered) directory, to find each file listed in the page, instead of just getting the files directly as were selected?

Feels like its an issue something like that.

**Comment by JasonYeMSFT** [comment]
@Plasma, there is no special 'download this page' logic. We send all your selected items to AzCopy. Only when there are directories among your selection, AzCopy may attempt to list blobs under those directories before it starts performing the transfer.

Could you check your settings for Transfers -> AzCopy -> Network Concurrency and Transfers -> AzCopy -> Maximum transfer rate? We have seen transfers taking longer than usual if these values are too low. If you are not using the default values, please try unlimited the transfer rate and set Network Concurrency to be the default option to see if it helps.
