### ISSUE TITLE
Pop up an error dialog after clicking 'Clear Queue' for one attached queue with SAS

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#253]
**Storage Explorer Version**: 1.2.0
**Platform**: All
**Architecture**: ia32/x64
**Build Number**: 20180601.6
**Commit**: 16083561
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Launch Storage Explorer and expand Storage Accounts.
2. Select one queue then attach is with SAS.
3. Open the attached queue -> Click 'Clear Queue' button on the toolbar.

#### Expected Experience: ####
No error dialog pops up.

#### Actual Experience: ####
An error dialog pops up.
![error](https://user-images.githubusercontent.com/34729022/40909903-485b57b0-67da-11e8-8c58-3471d8330f3c.png)

**Comment by craxal** [comment]
What does your SAS look like? Do you have delete permissions?

**Comment by v-xuanzh** [comment]
Yes, attach the below queue named 'testqueue1' with full permission .

Generated SAS URI like this:
https://e7ikmorgkjtyq101.queue.core.windows.net/testqueue1?st=2018-06-04T05%3A28%3A00Z&se=2018-06-07T05%3A28%3A00Z&sp=raup&sv=2017-07-29&sig=aS0%2BLTwU9enXop3G7SEx5%2Bi1mFn%2BI7Im6dkqp8xgP18%3D

**Comment by v-xuanzh** [comment]
This issue still reproduces on the latest master build 20190703.4

**Comment by craxal** [comment]
@v-xuanzh The SAS you provided expired a year ago. You'll need a new one. If you can, please provide a valid, current SAS through an email.

**Comment by v-xuanzh** [comment]
Sent a mail to you.

**Comment by craxal** [comment]
OK, I'm able to reproduce as well. I checked the documentation, and I don't think clearing a queue is possible with a SAS. The "p" permission says you can get and delete messages. However a clear operation is different than a delete permission. Furthermore the Clear Messages REST documentation says only the account owner may call this operation.

Therefore, this is by design.
