### ISSUE TITLE
Keep consistent error dialog between services when using an exist name to clone one service

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2533]
**Storage Explorer Version:** 1.12.0
**Build:** [20200109.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3369695&view=results)
**Branch:** rel/1.12.0
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ MacOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> File Shares.
2. Create two file shares -> Select one file share and right click it -> Click 'Clone with New Name...'.
3. Specify the new name using an exist file share name -> Check the error dialog.
4. Expand one storage account -> Blob Containers.
5. Create two blob containers -> Select one blob container and right click it -> Click 'Clone with New Name...'.
6. Specify the new name using an exist blob container name -> Check the error dialog.

**Expect Experience:**
The content format between the two dialog is consistent.

**Actual Experience:**
The content format between the two dialog is inconsistent.
![image](https://user-images.githubusercontent.com/41351993/72147475-8c1f4200-33d9-11ea-9164-aec88e39cd9a.png)

**Comment by v-limu** [comment]
Verified on build [20200210.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3458474
). This issue has been fixed. So we close it.
![image](https://user-images.githubusercontent.com/54055206/74207280-e69e0d80-4cb9-11ea-934c-f8f62e277540.png)
