### ISSUE TITLE
Unnecessary horizontal scroll bar appears in bob container delete dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2535]
**Storage Explorer Version:** 1.12.0
**Build:** [20200109.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3369695&view=results)
**Branch:** rel/1.12.0
**Platform/OS:** MacOS High Sierra (10.13.6 & 10.15.2)
**Architecture:** x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Open Storage Explorer -> Select subscription '**Azure Tools Manual Testing 1**'.
2. Expand Storage Accounts -> Select account '**abcdisistestv2**'.
3. Expand the storage account -> Blob Containers.
4. Select blob container '**test**' -> Right click it and click 'Delete'.
5. Check the delete dialog.

**Expect Experience:**
The delete dialog shows well.

**Actual Experience:**
The delete dialog shows odd.
![image](https://user-images.githubusercontent.com/41351993/72149315-d30f3680-33dd-11ea-9128-ac730cf9ed32.png)

**Comment by craxal** [comment]
@v-xianya We merged a change, but can you help us verify this is fixed?

**Comment by v-xianya** [comment]
Hi @craxal 
Verified this issue on build 20200113.2. It has been fixed.
