### ISSUE TITLE
Tab key must be pressed twice in delete services dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2536]
**Storage Explorer Version:** 1.12.0
**Build:** [20200109.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3369695&view=results)
**Branch:** rel/1.12.0
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Select one blob container and right click it -> Click 'Delete'.
3. Press Tab to focus 'No' -> Try to focus 'Yes' button using Tab key.

**Expect Experience:**
Press the Tab key once, the 'Yes' button is focused.

**Actual Experience:**
Press the Tab key twice, the 'Yes' button is focused.
![image](https://user-images.githubusercontent.com/41351993/72151159-7bbf9500-33e2-11ea-810a-191acd72d6e4.png)

**More Info:**

1. This issue doesn't reproduce for delete entities dialog.
2. This issue also reproduces for Clear Queue/ Dequeue Message dialog.
3. This issue also reproduces for Acquire & Break blob container lease/ delete blobs dialog.
4. This issue also reproduces for promote blob dialog.
5. This issue also reproduces for delete files / restore file dialog under file share.
6. On mac, Nothing happens to press Tab key when ‘No’ button is focused.

**Comment by MRayermannMSFT** [comment]
This is a known issue for dialogs. There is an extra tab stop in every dialog at the very end. We already have other issues tracking it.
