### ISSUE TITLE
On Cosmos DB - Execute Query: Add ability to execute selected text only like SSMS has.

### ISSUE THREAD

**Issue by JPhillipBrooks** [microsoft/AzureStorageExplorer#2537]
Please add the ability to execute just the selected statement rather than always executing the entire contents of the query window.

Suppose I have two statements in the query window:

1. SELECT * FROM c WHERE c.Type = 'Fruit'
2. SELECT * FROM c WHERE c.Type = 'Vegetable'

In the current version of Azure Storage Explorer v1.11.2 on Windows, both statements will run when clicking "Execute Query" resulting in a 400 Bad Request message indicating "Syntax error, incorrect syntax near 'SELECT'. In applications like SQL Server Management Studio (SSMS) you can select/highlight a line or lines of query code and only that code will execute.

The current work around to having multiple queries in one query window is to comment out all other queries except for the one you want to run. Then, to run another query, you must uncomment the desired query and comment out the previous query.

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
