### ISSUE TITLE
Copying Connection String Directly from Cosmos Storage Emulator Fails

### ISSUE THREAD

**Issue by merthsoft** [microsoft/AzureStorageExplorer#2538]
**Storage Explorer Version**: 1.11.2
**Build Number**: 20191217.4
**Platform/OS**: win10
**Architecture**: x64

## Bug Description ##
When pasting the "localhost" connection string from the Azure Cosmos DB Emulator into the "Connect to Cosmos DB" dialog, you get an error saying "Invalid format connection string for SQL API". If you then manually append a semi-colon to the end of it it is valid. The connection string parser should be able to handle a connection string without a trailing semi-colon

## Steps to Reproduce ##
1. Start Azure Cosmos DB Emulator
2. Start Azure Storage Explorer
3. Navigate to "https://localhost:8081/_explorer/index.html" and copy the "Primary Connection String"
4. In Azure Storage Explorer, right-click Cosmos DB Accounts (Preview)
5. Click "Connect to Cosmos DB Emulator"
6. In the "Connection String" box, paste the connection string copied from step 3

## Expected Experience ##
I would expect the example connection string given from the official product to work in the connection dialog of the official product. Specifically, the parser should be able to handle not having a trailing semi-colon.

## Actual Experience ##
You get an error saying "Invalid format connection string for SQL API"

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
