### ISSUE TITLE
The update notification isn't themed under default theme

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#254]
**Storage Explorer Version**: 1.2.0
**Platform**: All
**Architecture**: ia32/x64
**Build Number**: 20180601.6
**Commit**: 16083561
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Launch Storage Explorer using the command: "./Microsoft\ Azure \Storage\ Explorer --add-update-group=CTI"
2. Make sure the current theme is default.
3. Check whether the update notification is themed or not.

#### Expected Experience: ####
The update notification is themed under default theme.

#### Actual Experience: ####
The update notification isn't themed under default theme.
![theme](https://user-images.githubusercontent.com/34729022/40912218-770c56ee-67e0-11e8-94d9-fd340cd70b79.png)

**Comment by craxal** [comment]
What you see for the default theme is by design. It just happens to be the same for dark.
