### ISSUE TITLE
v1.11.1  - Failed to acquire token silently as no token was found in the cache. call method Acquire Token.

### ISSUE THREAD

**Issue by Muqeeet** [microsoft/AzureStorageExplorer#2540]
**Storage Explorer Version**: 
**Build Number**: 20191121.1
**Platform/OS**: Windows Server 2012 R2
**Architecture**: 
**Regression From**:  it was working with same credentials with same version

## Bug Description ##
when add azure account is selected and credentials are provided it throws error.
Failed to acquire token silently as no token was found in the cache. call method Acquire Token.

## Steps to Reproduce ##
start Azure storage explorer application
when add azure account is selected and credentials are provided it throws error.
Failed to acquire token silently as no token was found in the cache. call method Acquire Token.

**Comment by JasonYeMSFT** [comment]
Can you try Help -> Reset and choose Auth? If it doesn't work, please try turning on using MSAL in the Settings -> Application -> Sign-in.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you're still having problems.
