### ISSUE TITLE
The number of bugs for the first fix item is incorrect in Release Notes Fixes part

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2541]
**Storage Explorer Version:** 1.12.0
**Build:** [20200113.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3379477)
**Branch:** rel/1.12.0
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ MacOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer -> Open Release Notes.
2. Check the description of the first fix in Fixes part.

**Expect Experience:**
The number of bugs is described correctly.

**Actual Experience:**
The number of bugs is described incorrectly.
![image](https://user-images.githubusercontent.com/41351993/72234078-2663cd80-3606-11ea-8833-c906bab09c4b.png)

**Comment by MRayermannMSFT** [comment]
Won't fix. There is 1 bug with 2 relevant GitHub issues.
