### ISSUE TITLE
Cannot browse to 2nd level folder on Data Lake gen2

### ISSUE THREAD

**Issue by yuttakon-cvx** [microsoft/AzureStorageExplorer#2545]
Storage Explorer Version: 1.11.2
Platform/OS: Windows 10
Architecture: x64
Regression From: 1.9

## Bug Description ##
Cannot access to particular folder second level folder

## Steps to Reproduce ##
1. Go to container
2. Browse a '1st level' folder
3. Browse a '2nd level' folder

## Expected Experience ##
No error and can work with the file

## Actual Experience ##
Got `ResourceNotFound` The specified resource does not exist. 
Then error, bounced back to root level

## Additional Context ##
This is a re-post from closed issue, would you please help 
https://github.com/microsoft/AzureStorageExplorer/issues/2245#issuecomment-568982223

The "The specified resource does not exist" seems to apply for exception when it try to access attribute resultOrError.error.
image

The "The specified resource does not exist" seems to apply for exception when it try to access attribute `resultOrError.error.`
![71460738-ba98fc80-27df-11ea-82a9-8f1e98ae0229](https://user-images.githubusercontent.com/59244520/72304342-de46b880-36a2-11ea-928f-4b3f584bd346.png)
- I have the access to the folder confirmed by accessibility on version 1.9.0
- I am in the owner group at folder level, not container
- The folder is in ADLSv2
- Seems like an attempt to use marshaler or Promise lib cause the error here
- However, it should not get into `resultOrError.type === "error"` in the first place, since I have the full access here
- Can browse to read the folder list, then crash if try to 'browse/execute' to the folder ( though have an owner right)
- Can access to any level on other storage account v2 if having root access

Have tried
1.  Toggle enable/disable MASL
2.  Toggle on/off  target stack Azure API
3.  Remove all added endpoint and re-add directly to the folder url

**Comment by MRayermannMSFT** [comment]
@yuttakon-cvx , in the full error message there should be a request id. Can you please share that with me? Thanks!

**Comment by yuttakon-cvx** [comment]
@MRayermannMSFT  
I didn't save the requestId, but then after install version 1.12.0 I found different error but it seems to reach the same mul-function behavior.

Check the development tools get this:
```
Uncaught (in promise) Error: ﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.
RequestId:0a8ec8eb-701e-0062-1f86-d5bab5000000
Time:2020-01-28T02:55:20.7821870Z</Message></Error>
    at new RestError (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\@azure\core-http\dist\coreHttp.node.js:1718:28)
    at C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\@azure\core-http\dist\coreHttp.node.js:3419:37
    at process._tickCallback (internal/process/next_tick.js:68)
```
Would you please have a look.

Also, I'm working from Chevron network and some network policy maybe applied and manipulated the request between client and AzureRM ?

**Comment by MRayermannMSFT** [comment]
Thanks @yuttakon-cvx I've passed those on to the backend teams. Hopefully they can shed some light on this.

**Comment by MRayermannMSFT** [comment]
Hi  @yuttakon-cvx, here's the reply from the server team:

"the customer does not have X on the “PRATO” folder.  The caller must have X on /, ASBU and PRATO and R on PRATO in order to list the contents of the PRATO folder"

**Comment by yuttakon-cvx** [comment]
@MRayermannMSFT ,
That should be incorrect:
1. I have browsed that folder and it's child folder, download some file, then when to _browse back to PRATO folder_ it crashed
2. I have confirmed that I'm in _Owning Group_'s Members (group's ID: 446cbf7c-f463-44dc-b998-1e640ea5e8d5)
3. Version 1.9.0 shows that `Permissions for: (my_chevron_email) Access / Default have both rwx`

Suggestion:
I found that I'm also in another group (groups' ID: 92ffaaee-838e-421a-8c45-fb1fdd0bba3b) that have no permission (0000 ACL) to access the folder.
Can the team check on this?

**Comment by MRayermannMSFT** [comment]
@yuttakon-cvx , so your folder structure is
```
/ (root)
   ASBU/
      PRATO/
```
And you're saying you:
1. list the contents of PRATO
2. go into some child file of PRATO
3. download a file in that child folder
4. return to PRATO
5. you get an error
Yes?
Can you confirm for me the permissions you have at each of the folders? For example:
```
/ (root) --x
   ASBU/ r-x
      PRATO/ rwx
         some_child/ rwx
```

**Comment by yuttakon-cvx** [comment]
@MRayermannMSFT 
Checked on version 1.9.0
I have the following

/ (root) --x                   via "Other" [r-x]
   ASBU/ r-x                  via "Other" [r-x]
      PRATO/ rwx            via 92ffaaee-838e-421a-8c45-fb1fdd0bba3b
         some_child/ rwx  via 92ffaaee-838e-421a-8c45-fb1fdd0bba3b

**Comment by MRayermannMSFT** [comment]
@yuttakon-cvx are you still having problems?
