### ISSUE TITLE
ADLSg2 file system access via Access ACL (r-x) throws error

### ISSUE THREAD

**Issue by jorgklein** [microsoft/AzureStorageExplorer#2548]
**Storage Explorer Version**: v1.12.0
**Build Number**: 20200114.3
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  Unknown

## Bug Description ##
Granted a AAD Group access to an ALDSg2 File System: Access Read & Execute (no Write). When this user that is member of this AAD Group tries to browse this File System an error is thrown: The specified resource does not exists.

## Steps to Reproduce ##
1. Create ADLSg2 File System.
2. Grant a user or group the permissions below. No RBAC permissions, no Default ACL permissions.
![image](https://user-images.githubusercontent.com/30068507/72446021-06254180-37b3-11ea-8efc-29f28d6f2bbf.png)
3. Let the user install ASE v1.12 and click on the File System to browse it (list folders).
4. The following error will be thrown:
![image](https://user-images.githubusercontent.com/30068507/72446167-500e2780-37b3-11ea-98cf-e1b7e99447c5.png)

## Expected Experience ##
Browsing the file systems should work.

## Actual Experience ##
See steps to reproduce.

## Additional Context ##
We use a proxy (configured in ASE). If I grant RBAC Storage Blob Data Reader access on the Storage Account everything works.

**Comment by MRayermannMSFT** [comment]
Hello, there is currently a known platform issue regarding ACLs that you might be running into. Let me check with the server team to see if that's what you are getting. Thanks!

**Comment by MRayermannMSFT** [comment]
@jorgklein can you please reproduce the issue and send us a fresh copy of the error message? The request for the request ID you gave us has unfortunately been scrubbed from the logs by now. Apologies for not getting to this earlier.

**Comment by jorgklein** [comment]
@MRayermannMSFT 
Here you go: 
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission. RequestId:23e786a4-b01e-00f9-213b-d8a175000000 Time:2020-01-31T13:38:26.4948393Z</Message></Error>

**Comment by jorgklein** [comment]
I now see it's a different error message than before. Just double checked and the scenario is the same.

**Comment by MRayermannMSFT** [comment]
I talked to the backend team. Apparently you are missing the execute permission on one or more of the folders in the path. To list the contents of a dir you need:

- execute permissions on every ancestor folder (including the root/container, which you can edit by right clicking on the container in the tree view and choosing -> manage access...)
- execute and read permissions on the folder you want to list

**Comment by jorgklein** [comment]
Hi @MRayermannMSFT, both of these are true. The exact situation is:

- User is member of AAD Group “SG_APP_CAAP_DLS_G”
- Group has Access r-x permissions on File System level. No Default permissions.
- Group has Access r-x permissions on 3 folders in the root of the File System. No Default permissions.
- Group has no permissions at all on 5 folders in the root of the File System.
- User is not able to list folders in the root of the File System. Error occurs when double clicking the File System to open in ASE.

If you want to I can show this to you in a Teams meeting.

Latest error:
﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission. RequestId:2abfa271-601e-0138-545a-db6c99000000 Time:2020-02-04T12:58:54.9945074Z</Message></Error>

**Comment by MRayermannMSFT** [comment]
@jorgklein are you still having issues? I'd be down to teams call about this.

**Comment by jorgklein** [comment]
Hi Matthew,

Didn’t try anymore since I was tracking this issues and the releases and I noticed it wasn’t fixed yet. If a fix was implemented, I would be more than happy to test! Do I understand that is the case?

Regards,
Jorg Klein

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Matthew Rayermann <notifications@github.com>
Verzonden: Friday, July 24, 2020 7:06:44 PM
Aan: microsoft/AzureStorageExplorer <AzureStorageExplorer@noreply.github.com>
CC: Jorg Klein <jorgklein@outlook.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [microsoft/AzureStorageExplorer] ADLSg2 file system access via Access ACL (r-x) throws error (#2548)


@jorgklein<https://github.com/jorgklein> are you still having issues? I'd be down to teams call about this.

**Comment by jorgklein** [comment]
Hi @MRayermannMSFT just tested and the issue is still there:

﻿_<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission. RequestId:5c8af546-a01e-0107-3f69-66db45000000 Time:2020-07-30T12:02:40.2268534Z</Message></Error>_

Can we schedule a teams call to resolve this?

**Comment by MRayermannMSFT** [comment]
Sure, I'm pretty easy to find on teams. :)

**Comment by jorgklein** [comment]
Hi @MRayermannMSFT I am not able to find you on teams/email. How can I contact you?

**Comment by MRayermannMSFT** [comment]
Since your email is in your profile I'll reach out. Thought you were internal MSFT. :P

**Comment by MRayermannMSFT** [comment]
Resolved this offline with @jorgklein. Issue was that automated scripts were adding groups as "users" in the ACL instead of as "groups". Service team is going to look into validating that groups are added as groups when ACLs are set.
