### ISSUE TITLE
Unable to browse storage account (1.12.0 Mac)

### ISSUE THREAD

**Issue by jystickman** [microsoft/AzureStorageExplorer#2549]
**Storage Explorer Version**: 1.12.0
**Build Number**: 20200114.3 
**Platform/OS**: MacOS 10.15.2
**Architecture**: x64
**Regression From**:  Unknown

## Bug Description ##
Unable to browse storage account (or anything)

## Steps to Reproduce ##
Launch the application.  I expect this is something environmental.

## Expected Experience ##
Should be able to browse my company storage account.  I can from a different system.

## Actual Experience ##
<img width="1303" alt="Screen Shot 2020-01-15 at 3 54 08 PM" src="https://user-images.githubusercontent.com/33039427/72471124-05d77700-37b0-11ea-8b5a-7eb4edfd9345.png">

## Additional Context ##
I have two systems - this one system behaves this way.  I am able to access the storage account from the other system.  Have tried removing keychain entries and preferences files but still appear to be stuck.

**Comment by jinglouMSFT** [comment]
Can you try to close Storage Explorer and restart it?  Your servicehub might not be shutdown appropriately during the upgrade from 1.11.x to 1.12.0.  Thanks.

**Comment by jystickman** [comment]
It happened prior to upgrading from 1.11.1 to 1.12.0.  I actually rebooted the entire system. 

No log files. I’ve also walked through the troubleshooting flow.

**Comment by JasonYeMSFT** [comment]
@jystickman , does this consistently reproduce? We just discovered a rare race condition that may lead this the infinite loading problem. If that is the case, you should be able to work around it to by restart the app.

**Comment by jystickman** [comment]
It was consistently reproducing at every launch, but there was a previous comment (which seems to have disappeared) that referenced ServiceHub.  I did a `rm -rf .ServiceHub` in my home directory and I was able to get things working again.  Thanks for your help @JasonYeMSFT  and @jinglouMSFT
