### ISSUE TITLE
Snapshots from file shares with similar names appear in the same view

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#255]
**Storage Explorer Version**: 1.2.0
**Platform**: All
**Architecture**: ia32/x64
**Build Number**: 20180601.6
**Commit**: 16083561
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Launch Storage Explorer and expand Storage Accounts.
2. Open one file share named 'empty'.
3. Create a snapshot for another file share named 'emptyfileshare' (don't open it).
4. Check the current opened snapshots view.

#### Expected Experience: ####
The created snapshot in Step 2 doesn't display in the current opened snapshots view.

#### Actual Experience: ####
The created snapshot in Step 2 displays in the current opened snapshots view.
![snapshots](https://user-images.githubusercontent.com/34729022/40911897-9c3edb7c-67df-11e8-940a-88cb83c784ee.png)

#### More info: ####
An extra dot displays next to the failed log message in Activities.

**Comment by craxal** [comment]
Looks like a bug in the client library. For some reason, it's the one returning the snapshots from both shares.

We can work around this by filtering out the odd-named snapshots.
