### ISSUE TITLE
Not work Surface Pro X(ARM64-based PC)

### ISSUE THREAD

**Issue by kazy101644** [microsoft/AzureStorageExplorer#2553]
**Storage Explorer Version**: <January 2020 (Version 1.12.0)>
**Build Number**: 
**Platform/OS**: <ARM64-based PC Windows 10 build 19541.>
**Architecture**: <i86 >
**Regression From**:  

## Bug Description ##
Not Upload File
Not Delete File

**Comment by MRayermannMSFT** [comment]
@kazy101644 , @christophwille just as an FYI, our Windows bits are 32 bit. So you can run them on Surface Pro X. It'll be a bit slower than non-ARM Windows, but it will work. I just confirmed that today.

In the future, we might consider native ARM builds, but for today they aren't available.

Let us know if you're having any issues with using the existing Windows build on ARM.

**Comment by milehighjustin** [comment]
I can install and browse through storage, but uploading and downloading just queues up and does nothing.

**Comment by pcmann** [comment]
@MRayermannMSFT, i have the same issue as @milehighjustin - The latest Azure Storage Explorer installs on Surface Por X but uploading and downloading does not work, activities just get stuck in the queue
Is there a workaround or fix in the works?

**Comment by MRayermannMSFT** [comment]
@milehighjusting @pcmann if you download the 32bit AzCopy v10 from here: https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10

And then use the "Copy AzCopy Command to Clipboard" action in Storage Explorer, are you able to run the transfer via the command line?

**Comment by xfzhang1974** [comment]
This same issue happens to me since middle December. Is there any AzureStorageExplorer release around that time. Is it possbile for me to rollback to a previous version?

**Comment by JasonYeMSFT** [comment]
We released 1.17.0 around middle December 2020. You can get all our previous release at here https://github.com/microsoft/AzureStorageExplorer/releases

**Comment by xfzhang1974** [comment]
Thank you Jason. I am trying the older versions.

**Comment by xfzhang1974** [comment]
Jason, I tried different versions of Azure Storage Explorer, and different versions of azcopy executable, and still observe the same issue, which makes me wonder if there is any recent change to ADLS  Gen2 Storage Account that conflicts with windows version azcopy. I will wait for the fix of the issue. Thank you for the help.

**Comment by MRayermannMSFT** [comment]
Hey all, I have a potential workaround for you to try:

0. Install the latest Storage Explorer
1. Go to the Storage Explorer install location, if you installed for all users it should be “C:\Program Files (x86)\Microsoft Azure Storage Explorer\”, if you installed for single user then I believe it is somewhere in %localappdata% or %appdata% (I think…).
2. Once there go to “resources\app\node_modules\@azure-tools”
3. You should see 3 folders, two of which are azcopy-win32 and azcopy-win64
4. Go into azcopy-win32/dist/bin and copy the .exe file in there to azcopy-win64/dist/bin
5. Rename the .exe that was already in azcopy-win64/dist/bin to something else (add like -backup to the end of the file name or something like that) and then rename the one you copied from azcopy-win32 to the be the original name of the x64 .exe
6. Launch Storage Explorer and do a transfer

**Comment by milehighjustin** [comment]
@MRayermannMSFT Works for me! Thank you.

**Comment by xfzhang1974** [comment]
@MRayermannMSFT I didn't do anything, it just works again.

**Comment by MRayermannMSFT** [comment]
We'll be including a fix that restores Windows ARM support in our next release. :)
