### ISSUE TITLE
The ellipsis in description is not gray for one disabled button on one blob container toolbar

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2555]
**Storage Explorer Version:** 1.12.0
**Build:** [20200117.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3393793)
**Branch:** master
**Language:** Spanish/ French/ Japanese/ German/ Czech/ Dutch/ Hungarian
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ MacOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Español' -> Restart Storage Explorer.
3. Expand one storage account -> Blob Containers.
5. Create a new blob container and open it -> Check the disabled button description.

**Expect Experience:**
The ellipsis in description is gray for one disabled button.

**Actual Experience:**
The ellipsis in description is not gray for one disabled button.
![image](https://user-images.githubusercontent.com/41351993/72592539-bfb01e00-393d-11ea-8539-c2c14ea8f822.png)

**More Info:**
This issue also reproduces for one file share/ queue.

**Comment by JasonYeMSFT** [comment]
The bug is a generic tool bar bug and isn't localization specific. It will happen whenever the button text overflows.

**Comment by v-xianya** [comment]
@MRayermannMSFT 
This issue reproduces on build 20210206.3. So we re-open it.
![image](https://user-images.githubusercontent.com/41351993/107198445-151b0980-6a30-11eb-8ae2-b520db7db8a0.png)

**Comment by JasonYeMSFT** [comment]
I merged another fix for queue.
