### ISSUE TITLE
Any way to suppress "$MetricsXxxxxxXxxxxx" tables in explorer?

### ISSUE THREAD

**Issue by ppsa-stephan** [microsoft/AzureStorageExplorer#2557]
In the desktop version on windows, when looking at tables in the explorer panel, it shows all these tables being used internally for metrics, tables whose names start with "$Metrics".  It would be very nice to have an option to suppress the display of these internal tables.

**Comment by JasonYeMSFT** [comment]
Thanks for the request. It is already prioritized in our backlog and will be added in some future release. See #3.
