### ISSUE TITLE
Blob Container add "Search by Containing" to "Search by Prefix"

### ISSUE THREAD

**Issue by ppsa-stephan** [microsoft/AzureStorageExplorer#2558]
Currently when looking at a blob container you can "Search by Prefix" of the blob name.

It would be great to have either an additional field allowing you to "Search by Containing" or alternatively a way to allow wildcards in the "Search by Prefix" field.

So if the container had the following blobs:

    Joe-2020-01-01-Error
    Joe-2019-12-15-Error
    Joe-2019-12-01-Warning
    Mary-2020-01-02-Warning
    Mary-2019-12-15-Error

One would be able to use the search to get only those with the string "Error" or only those with the string "Warning", or only those with the string "2020" or only those with the string "2019-12".

This would be a great help, especially in blob containers with thousands of entries.

**Comment by JasonYeMSFT** [comment]
We already has an issue for this #1667. We are working with the service team to make this happen and please track the request in that issue.
