### ISSUE TITLE
The string 'Tenant' is not localized in Attach with Azure AD dialog

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2559]
**Storage Explorer Version:** 1.12.0
**Build**: [20200118.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3397152)
**Branch**: master
**Language**: Czech / Dutch
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '**čeština**' -> Restart Storage Explorer.
3. Open localized 'Connect' Dialog -> Click localized 'Add a resource via Azure Active Directory(Azure AD)'.
4. Check the string 'Tenant' in the popped dialog.

**Expect Experience:**
The string 'Tenant' is localized.

**Actual Experience:**
The string 'Tenant' is not localized.
![image](https://user-images.githubusercontent.com/54055206/72678770-e1e3a080-3ae3-11ea-8f73-9bf4ae0f7503.png)

**Comment by MRayermannMSFT** [comment]
@lukaschal can you confirm that this translation is correct? It looks like for some languages, the word "tenant" may be spelled the same way? Here's the current translations on master:
![image](https://user-images.githubusercontent.com/21112697/72854414-277da600-3c69-11ea-865e-535d7b105f73.png)

**Comment by lukaschal** [comment]
@MRayermannMSFT Veryfing with linguist,.

**Comment by lukaschal** [comment]
For CSY and ITA is "Tenant" correct translation.

**Comment by MRayermannMSFT** [comment]
Ok. I'll go ahead and close this then.
