### ISSUE TITLE
Tabbing to 'Add new clause' button miss borders in Query editor

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#256]
**Storage Explorer Version**: 1.2.0
**Platform**: Mac
**Architecture**: x64
**Build Number**: 20180601.6
**Commit**: 16083561
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Launch Storage Explorer and expand Storage Accounts.
2. Open one table -> Click 'Query' -> Focus on the 'Add new clause' button using Tab.
3. Check the focused border of the button.

#### Expected Experience: ####
The focused border displays well.

#### Actual Experience: ####
Miss the left and bottom borders.
![border](https://user-images.githubusercontent.com/34729022/40910364-75a7b44c-67db-11e8-8510-d226d70f0637.png)

**Comment by craxal** [comment]
@jinglouMSFT, Is this a serious issue? The border is still visible. Did we have to fix this for other controls?

**Comment by v-xuanzh** [comment]
Verified this issue on latest master build 20180611.2. Fixed. So close this issue.
