### ISSUE TITLE
Miss '…' for the localized action 'Change Access Tier' for one blob in Dutch

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2560]
**Storage Explorer Version:** 1.12.0
**Build**: [20200118.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3397152)
**Branch**: master
**Language**: Dutch / Swedish
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '**Nederlands**' -> Restart Storage Explorer.
3. Expand one storage account -> Blob Containers.
4. Create a new blob container -> Upload a blob to it -> Right click it.
5. Check the localization action 'Change Access Tier' in its context menu.

**Expect Experience:**
Show '…' for the localized action 'Change Access Tier' .

**Actual Experience:**
Miss '…' for the localized action 'Change Access Tier'.
![image](https://user-images.githubusercontent.com/54055206/72712837-d4dbb580-3ba6-11ea-8241-a581689941a5.png)

**More Info:**

1. This issue also reproduces on the localized action **'Break Leased'** for one blob.
2. This issue also reproduces on the localized action **'Undelete By Date'** for one deleted blob.
![image](https://user-images.githubusercontent.com/54055206/72713063-4d427680-3ba7-11ea-9813-e86553c9801c.png)
3. This issue also reproduces on the localized action **'Edit'** for one table entity.
![image](https://user-images.githubusercontent.com/54055206/72713071-516e9400-3ba7-11ea-9505-257d4ac1fae8.png)
4. **An extra '...' shows next to the localized action 'Selection Statistics'** for one blob/ one file under one file share.
![image](https://user-images.githubusercontent.com/54055206/72713179-8aa70400-3ba7-11ea-8878-d06f00c6cf0c.png)

**Comment by lukaschal** [comment]
All instances fixed.

**Comment by v-limu** [comment]
Hi @lukaschal 😉
Verified on build [20200120.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3401036). This issue still reproduces and also reproduces in '**Hungarian**' / '**Portuguese(pt-PT)**' / '**Swedish**'.

**Comment by v-limu** [comment]
Miss '...' for the localized 'Select Columns' in the table query builder with **Swedish**.
![image](https://user-images.githubusercontent.com/54055206/72882979-7c3f2080-3d3e-11ea-9fa2-0e1f621cc811.png)

**Comment by lukaschal** [comment]
All instances on PT, SV and HU fixed.

**Comment by JasonYeMSFT** [comment]
@lukaschal, I have verified the fixes. I found that there is an abnormal file `FileSystemEditor.ko.json` checked in to the repository. Is it checked in by accident?

**Comment by JasonYeMSFT** [comment]
blob, adls gen2, table packages needs to be published.

**Comment by lukaschal** [comment]
@JasonYeMSFT Could you please be more specific what is wrong with file FileSystemEditor.ko.json ? Do you have link to affected pull request ?

**Comment by jinglouMSFT** [comment]
@lukaschal   This one is not fixed for all languages mentioned in this bug: (verified with build 20200221.12 (build from 2/21/2020)

An extra '...' shows next to the localized action 'Selection Statistics' for one blob/ one file under one file share.
![image](https://user-images.githubusercontent.com/10081483/75081949-276e0180-54c6-11ea-9972-ed6180fb5b0f.png)

**Comment by JasonYeMSFT** [comment]
@lukaschal , I looked at the PRs related to that file. It just seems that we forgot the delete it when deleting other <FileName>.<locale>.json formatted files. We can just go and delete it.

**Comment by lukaschal** [comment]
Fixed now.

**Comment by v-xianya** [comment]
@lukaschal 
Verified this issue on build [20200225.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3498630). 
An **extra '...' shows for action 'Selection Statistics'** for blobs/ files under one file share' in Swedish/ Portuguese(pt-PT)/Hungarian.
![image](https://user-images.githubusercontent.com/41351993/75214565-fa249a80-57c8-11ea-8b2a-35afad5e33ca.png)

**Comment by JasonYeMSFT** [comment]
Strings needs to be verified in this issue:
-[ ] Blob container Change Access Tier
-[ ] Blob Container Break Lease
-[ ] Blob Break Lease
-[ ] Blob Undelete by date
-[ ] Table Edit Entity

**Comment by v-xianya** [comment]
Verified this issue on build [20200229.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3514328). Fixed. So close it.
