### ISSUE TITLE
Error occurred while adding new connection: TypeError:Cannot read property 'uids' of undefined.

### ISSUE THREAD

**Issue by DMT16** [microsoft/AzureStorageExplorer#2561]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:

**Comment by DMT16** [comment]
When trying to connect Storage Explorer to data via an SAS URI

**Comment by JasonYeMSFT** [comment]
Have you tried refreshing the tree? We should have fixed this problem in our latest release. Can you tell us what version you are using?

**Comment by DMT16** [comment]
Hi,

I have, and that error has gone now, connection added ok, but always times out:
ETIMEDOUT 52.239.138.132:443

so I can't access the data held.

Version 1.10.1

David

On 21 Jan 2020, at 18:47, JasonYeMSFT <notifications@github.com<mailto:notifications@github.com>> wrote:


Have you tried refreshing the tree? We should have fixed this problem in our latest release. Can you tell us what version you are using?

**Comment by jinglouMSFT** [comment]
@DMT16  The latest version is now v1.12.0.  You can download it from http://storageexplorer.  You probably by now also have received a notification for upgrading to the latest version.  If not, please go to the URL I mentioned to download the latest version.  v1.12.0 is also available here on Github under the release tab.  Let us know if 1.12.0 fixes the issue.  Thanks.

**Comment by MRayermannMSFT** [comment]
Are you behind a proxy?

**Comment by DMT16** [comment]
Hi,

Yes I am, have installed the latest version and will try again tomorrow.

Proxy causing issues?

David

On 27 Jan 2020, at 18:47, Matthew Rayermann <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you behind a proxy?

**Comment by MRayermannMSFT** [comment]
Maybe? Are you behind a proxy?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
