### ISSUE TITLE
Not booting up all of a sudden 

### ISSUE THREAD

**Issue by chizzau** [microsoft/AzureStorageExplorer#2562]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:  

## Current Experience ##
Tried booting up and it would work. Then using activity monitor to shut down app and tried again and nothing. A few minutes later, I get the Microsoft Azure Storage Explorer quit unexpectedly. (image below)

I tried to restart the computer and booting up the app again, same issue. I installed the latest version and still same issue.

Not sure what happened, I know I've updated the Mac OS here and there but is that case? Thanks,

![image](https://user-images.githubusercontent.com/7821983/72752039-355ef880-3b8f-11ea-9d15-42eaeac86375.png)

**Comment by chizzau** [comment]
![image](https://user-images.githubusercontent.com/7821983/72752311-e06fb200-3b8f-11ea-92e6-666839861880.png)

**Comment by JasonYeMSFT** [comment]
The error details says that you are on macOS 10.15.1. Can you try upgrading to 10.15.2? Let us know if this still reproduces.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you're still having problems.

**Comment by garethrampton** [comment]
I have this same issue with 1.12.0. 

Both on previous and current MacOS versions.
