### ISSUE TITLE
The proper noun 'Disks' is translated in Settings & one opened resource group's path

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2563]
**Storage Explorer Version:** 1.12.0
**Build**: [20200120.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3401036&view=results)
**Branch**: master
**Language**: Hungarian/ Dutch/ Portuguese (Portugal)/ Russian/ Swedish
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '**Magyar**' -> Restart Storage Explorer.
3. Open localized 'Settings' -> Localized 'Services'.
4. Check whether the proper noun 'Disks' is translated or not.

**Expect Experience:**
The proper noun 'Disks' is not translated.

**Actual Experience:**
The proper noun 'Disks' is translated.
![image](https://user-images.githubusercontent.com/41351993/72788248-80027280-3c6c-11ea-9eac-c2ed7afe96a1.png)

**More Info:**
1. The proper noun '**Disks**' is translated in one opened resource group's path.
![image](https://user-images.githubusercontent.com/41351993/72788297-9b6d7d80-3c6c-11ea-8d4c-5f5af6761533.png)

**Comment by lukaschal** [comment]
ENU:

![image](https://user-images.githubusercontent.com/18324331/72805239-ad422700-3c52-11ea-9308-6ecaa591f44f.png)

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
@v-xianya Please, is it possible to add ENU screenshot of first screen with check-boxes?

**Comment by lukaschal** [comment]
@craxal @JasonYeMSFT Please, here is question from linguists, if context of term "Disk" for both resources mentioned below, is related to "Managed Disk" feature or not?

**Comment by lukaschal** [comment]
Unlocalized on all languages except RUS and HUN for now.

**Comment by v-xianya** [comment]
@lukaschal 
ENU screenshot:
![image](https://user-images.githubusercontent.com/41351993/73605301-a4007500-45d7-11ea-89dd-fdfb3e197659.png)

**Comment by JasonYeMSFT** [comment]
@v-xianya @lukaschal Sorry I am a little bit confused right now. Is there any specific reason why Disks is only localized in RUS and HUN but not in any other language? Is the current translation state the eventual result or is there still any pending changes?

**Comment by lukaschal** [comment]
@JasonYeMSFT This is due to different languages standards.

**Comment by jinglouMSFT** [comment]
@v-xianya  This has been fixed.  All languages except Russian (Pyccknn) and Hungary (Magyar) use "Disks".  Russian and Hungary have been translated.  I've verified on all languages using 20200210.4.

**Comment by v-xianya** [comment]
@jinglouMSFT Hi, Jing Thank you for verifing this issue.
This issue has been fixed on build 20200220.2. So close it.
