### ISSUE TITLE
"No data available in table" message is displayed after execute query

### ISSUE THREAD

**Issue by PavlenAchinsk** [microsoft/AzureStorageExplorer#2564]
**App name**: Microsoft Azure Storage Explorer
**Storage Explorer Version**: Version 1.12.0 / AzCopy Version 10.3.3
**Build Number**: 20200116.10
**Platform/OS**: Windows 10x64
**Architecture**: ia32(x86)
**Regression From**:  Not sure that the issue is regression

![image](https://user-images.githubusercontent.com/60141573/72809744-4da54500-3c6d-11ea-8b09-ab66ed6da421.png)

## Bug Description ##
No data available in table is displayed after execute query. 
![image](https://user-images.githubusercontent.com/60141573/72809830-7b8a8980-3c6d-11ea-9dda-392b2716aa15.png)

I have data if I use the same query in code
TableQuery<T> myQuery = new TableQuery<T>().Where("PartitionKey eq '252100152'");
TableQuerySegment<T> segment = await CloudTable.ExecuteQuerySegmentedAsync(myQuery , token);

## Steps to Reproduce ##
1. Launch Microsoft Azure Storage Explorer
2. Connect to storage account by Use a shared access signature (SAS) URI
3. Expand Storage Account
4. Select and expand created account in step 2
5. Expand Tables
6. Select table
7. Click Query button from top panel
8. Add new clause with PartitionKey-string-=-252100152
9. Perform Execute query by F5 or Run Icon

## Expected Experience ##
Rows found and displayed

## Actual Experience ##
No data available in table

## Additional Context ##
The issue is reproducedfor me in only one table if I try to use PartitionKey-string-=-252100152 in query but rows are displayed if I use PartitionKey-string-=-124252101.
I think the table has a lot of records that cannot be loaded initially so newer lines cannot be displayed

**Comment by JasonYeMSFT** [comment]
We are not able to reproduce the exact issue by running queries in our table. Is it possible for you to share  a table via SAS with us that can reproduce the bug?

**Comment by PavlenAchinsk** [comment]
> We are not able to reproduce the exact issue by running queries in our table. Is it possible for you to share a table via SAS with us that can reproduce the bug?

No, I can't since the table has confidential info that I am not entitled to dispose of.

I think RCA of the issue is a lot of rows in the table. I exported info from the table to file csv. File size is 450MB, Table has 291270 rows that has 36 columns.
And need to get 291261st row in Azure Storage Explorer. "No data available in table" message should be displayed.

Could you please check the scenario?

Thanks,
Vitaly

**Comment by PavlenAchinsk** [comment]
I checked the uploaded file, it does not contain the row with "PartitionKey eq '252100152'".
Can the table be full?

TableQuery myQuery = new TableQuery().Where("PartitionKey eq '252100152'");
TableQuerySegment segment = await CloudTable.ExecuteQuerySegmentedAsync(myQuery , token);
Why does a query in code work well?

**Comment by PavlenAchinsk** [comment]
I used another container, but table has the same name so I have No data available message.
