### ISSUE TITLE
CosmosDB - No documents displayed when using Partition Key Definition v2

### ISSUE THREAD

**Issue by jkonecki** [microsoft/AzureStorageExplorer#2565]
**Storage Explorer Version**: 1.11.1
**Build Number**: 20191121.1
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  not known

## Bug Description ##
No documents are shown at all from collections using Partition Key Definition v2 (2kB).

## Steps to Reproduce ##
1. Create a collection that uses partitioning schema v2 (partition key hash calculated from 2kB instead of 100 bytes of partition key)
2. Create a new document in said collection
3. Navigate ot the collection in the Explorer and click on Documents node

## Expected Experience ##
Document created in step 2 is displayed in Explorer

## Actual Experience ##
Explorer doesn't show any documents. Clicking on Refresh button or Load more link does nothing.

## Additional Context ##
Explorer experiences the same issue with CosmosDB instance hosted in Azure and also with CosmosDB emulator.
I have 2 collections with different Partition Key Definition versions with identical documents. Explorer correctly shows all document in collection with Partition Key Definition version 1, but not with version 2.

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
