### ISSUE TITLE
File rename: Need special character validation in file name

### ISSUE THREAD

**Issue by yuyez** [microsoft/AzureStorageExplorer#2566]
**Storage Explorer Version**: 1.12.0
**Build Number**: 20200116.10
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  N/A

## Bug Description ##
Cloning a file with an invalid target file name gives generic "BadRequest" message

## Steps to Reproduce ##
Upload a file to a file share
Clone with New Name
Enter an invalid file name, e.g. file**.txt

## Expected Experience ##
API returns 400 "The specifed resource name contains invalid characters." The same message should be shown.

## Actual Experience ##
Error message "BadRequest" pops up

## Additional Context ##
N/A

**Comment by MRayermannMSFT** [comment]
Merged for 1.18. Thanks for opening this issue @yuyez.
