### ISSUE TITLE
Blob metadata: Need special character validation in metadata key

### ISSUE THREAD

**Issue by yuyez** [microsoft/AzureStorageExplorer#2567]
**Storage Explorer Version**: 1.12.0
**Build Number**: 20200116.10
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  N/A

## Bug Description ##
Adding metadata with invalid key doesn't trigger UI validation error

## Steps to Reproduce ##
Upload a blob
Open blob properties
Add a metadata with key @#@#

## Expected Experience ##
Validation error pops up similar to when Unicode character is used, i.e. "Metadata keys must conform to naming conventions for C# identifiers."

## Actual Experience ##
No validation error and the user is allowed the click OK

## Additional Context ##
N/A

**Comment by MRayermannMSFT** [comment]
@yuyez I updated our validation to be more accurate, you'll see those changes in 1.14. Thanks for bringing this up. 😄 
![image](https://user-images.githubusercontent.com/21112697/83205114-8b761680-a102-11ea-8e2c-a3ca5aa85051.png)
