### ISSUE TITLE
 'Download' button is not translated for one blob container

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2569]
**Storage Explorer Version:** 1.12.0
**Build**: [20200122.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3404394)
**Branch**: master
**Language:** Italian
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '**Italiano**' -> Restart Storage Explorer.
3. Expand one storage account -> Blob Containers.
4. Create a new blob container -> Open it.
5. Check whether the 'Download' button is translated or not in the toolbar.

**Expect Experience:**
'Download' is translated.

**Actual Experience:**
'Download' is not translated.
![image](https://user-images.githubusercontent.com/54055206/72879831-a8f03980-3d38-11ea-913a-416c831353bd.png)

**More Info:**

1. This issue doesn't reproduce for **the tooltip of the 'Download' button.**
![image](https://user-images.githubusercontent.com/54055206/72879839-abeb2a00-3d38-11ea-9737-a66b63b4e4b7.png)

2. This issue also reproduces for one blob / file share / resource group.

**Comment by lukaschal** [comment]
Localized as "Scarica" now.

**Comment by v-xianya** [comment]
@lukaschal 
Verified on the latest build master/20200201.2. 
1. This issue has been fixed for one resource group.
2. This issue still reproduces for one blob container/ file share.
![image](https://user-images.githubusercontent.com/41351993/73626508-1fb7fb80-4684-11ea-80a0-ff8f1ece4687.png)

**Comment by JasonYeMSFT** [comment]
The string is added to blob, file and adls gen2 extensions. Need package update.

**Comment by MRayermannMSFT** [comment]
Looks good now
<img width="124" alt="image" src="https://user-images.githubusercontent.com/21112697/74478516-636beb80-4e62-11ea-884f-c6a9c6b3b9e2.png">
