### ISSUE TITLE
NaN Values not supported

### ISSUE THREAD

**Issue by sanore** [microsoft/AzureStorageExplorer#257]
**Storage Explorer Version**: 1.1.0
**Platform**: Windows
**Architecture**: ia32
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Launch Storage Explorer and open Table with NaN Value
2. Edit a row
    2.1. Type -> double
    2.2. Value -> NaN or _nothing_

#### Expected Experience: ####
NaN should be a valid number value and update button should be available.

If row is added by a custom user code (See [Azure Storage.NET Issue 644](https://github.com/Azure/azure-storage-net/issues/644)), the ui is shown _nothing_. 
![2018-06-04 12_43_47-microsoft azure storage explorer - edit entity](https://user-images.githubusercontent.com/4846634/40913472-fa9c6a3a-67f4-11e8-83f7-0aade55007a2.png)

#### Actual Experience: ####
But i can't edited NaN values inside MS Azure Storage Explorer.
![2018-06-04 12_43_33-microsoft azure storage explorer - edit entity](https://user-images.githubusercontent.com/4846634/40913502-0fd800a8-67f5-11e8-9fe2-413f265e2f29.png)

**Comment by craxal** [comment]
Yeah, we should look into that. Thanks for bringing this up!

**Comment by mguntli** [comment]
I assume this is related:
Copying a table does not properly copy the entire table. If a row contains properties with Double.NaN (and type is Double), those properties are not copied.

**Original:**
14 Double properties with value "Double.NaN" + 10 String properties.

**Copy:**
10 String properties

**Comment by JasonYeMSFT** [comment]
We need to adopt the new SDK to make this supported.
