### ISSUE TITLE
Error "unable to retrieve child resources" at subscription explorer node

### ISSUE THREAD

**Issue by 10843** [microsoft/AzureStorageExplorer#2570]
**Storage Explorer Version**: 1.12.0 
**Build Number**: 20200116.10: 
**Platform/OS**: MacOS: 
**Architecture**: x64: 
**Regression From**: 1.7.0:  

## Bug Description ##
Expanding a subscription in the explorer results in a popup with 
"Unable to retrieve child resources.

Details:
[{"signal":"SIGABRT"}]"

## Steps to Reproduce ##
Start Storage Explorer (assuming subscription details previously entered)
Expand desired subscription node in explorer tree

## Expected Experience ##
Show the storage accounts in that subscription

## Actual Experience ##
Got error

**Comment by JasonYeMSFT** [comment]
Does this happen to all your subscriptions after upgrading or only to some specific subscription?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you're still having problems. Thanks.
