### ISSUE TITLE
The content in Manage Access dialog shows incompletely

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2571]
**Storage Explorer Version:** 1.12.0
**Build:** [20200122.8](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3407621)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ MacOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release(1.12.0)

**Steps to reproduce:**
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Select one blob container and right click it -> Select 'Manage Access...'.
3. Check the content in Manage Access dialog. 

**Expect Experience:**
The content in Manage Access dialog shows completely.
![image](https://user-images.githubusercontent.com/41351993/72959872-da274300-3de6-11ea-9104-c5fdf349e224.png)

**Actual Experience:**
The content in Manage Access dialog shows incompletely.
![image](https://user-images.githubusercontent.com/41351993/72959807-9f250f80-3de6-11ea-96b7-0f1925e35372.png)

**More Info:**
1. This issue also reproduces for ADLS Gen2 blob's Manage Access dialog.

**Comment by craxal** [comment]
Resizing makes the missing elements come back, so the problem is when the dialog is initializing.
