### ISSUE TITLE
Setting to load Disks in treeview as collapsed

### ISSUE THREAD

**Issue by mikewo** [microsoft/AzureStorageExplorer#2575]
When I open up a Blob Storage account it will load the first few set of containers and the first set of Disks by Resource Group, both of which are loaded as open on the treeview. I rarely, if ever, go digging through the disks. I'd much prefer for the containers node to load as it does now, but the disks node to not expand automatically. Perhaps a settings flag that lets you turn off the automatic expanding of the Disks node?

I feel like this is a feature I would rarely use and it's just taking up time to fetch the resource groups and loading them. Albeit, not a lot of time, but it's also more noise in the UI than I need to focus on.

**Comment by MRayermannMSFT** [comment]
Hi @mikewo , we already have a setting similar to this. Please go to Settings -> Services -> Disks. Unchecking that checkmark will hide Disks. You can also come back and recheck it if you need to see that node in the future.

**Comment by mikewo** [comment]
Gah! Thank you. I should have Read The Manual.

**Comment by MRayermannMSFT** [comment]
To be fair, it isn't documented anywhere. You'd have to just go and find it. (between you and me, I'd love to go and write some intro docs with helpful info like this...but....not a lot of time for that right now, sorry 😓)
