### ISSUE TITLE
Can' delete or upload overwrite files on Azure Storage Explorer

### ISSUE THREAD

**Issue by coelhofh** [microsoft/AzureStorageExplorer#2576]
**Storage Explorer Version**: <1.9.0>
**Build Number**: <21090701.8>
**Platform/OS**: <Windows 10 >
**Architecture**: < x64 >

## Bug Description ##
Can' delete a file or overwrite it.

## Steps to Reproduce ##
I simply can't delete or overwrite my files - any of then.

## Expected Experience ##
AZCopy always put "overwrite=false" on the command when I try to upload a file. If it exists I got an error. Command generated by Storage Explorer is bellow.

## Additional Context ##
Here is the command:

$env:AZCOPY_CRED_TYPE = "SharedKey";
$env:ACCOUNT_NAME = "MYACCOUNTNAME";
$env:ACCOUNT_KEY = "MYACCOUNTKEY";
./azcopy.exe copy "C:\Desktop\file_full.csv" "https://******.dfs.core.windows.net/*****/file_full.csv" --overwrite=false --follow-symlinks --recursive --from-to=LocalBlobFS --put-md5;
$env:AZCOPY_CRED_TYPE = "";
$env:ACCOUNT_NAME = "";
$env:ACCOUNT_KEY = "";

**Comment by MRayermannMSFT** [comment]
Hi @coelhofh , in newer versions of Storage Explorer, you'll see commands use `overwrite=prompt`. That will tell AzCopy to ask you if you'd like to overwrite. You're also free to modify the copied command however you see fit. So, please upgrade to the latest version of Storage Explorer and let us know if you are still having issues. Thanks!

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you're still having problems. Thanks.
