### ISSUE TITLE
Number greater than 16 digits is shown incorrectly

### ISSUE THREAD

**Issue by apgapg** [microsoft/AzureStorageExplorer#2577]
**Storage Explorer Version**: v1.12.0
**Build Number**: 20200116.10
**Platform/OS**: macOS
**Architecture**: x64

## Bug Description ##
If a json contains a key where number is greater than 16 digits, the number is shown incorrectly
Data saved is correct in cosmos DB but shown incorrectly in azure explorer

## Steps to Reproduce ##
Js has 16 digits number support at max. And because Electron is based on JS hence this is a JS limitation and hence has to be handled differently here

## Additional Context ##
See this link: https://github.com/sidorares/json-bigint
https://github.com/axios/axios/issues/983
https://github.com/peterolson/BigInteger.js

**Comment by southpolesteve** [comment]
The Cosmos service supports the JSON spec which is only capable of storing the maximum integer supported by JavaScript. This is part of the service design. Larger integers need to be modeled as strings.
