### ISSUE TITLE
Change sprintf() to sprintf-js package

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#258]
**Storage Explorer Version**: 1.1.0
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Open Storage Explorer
2. Open the developer tool

#### Expected Experience: ####
No error message.

#### Actual Experience: ####
An deprecation warning message shows up. We are using sprint() in error handling. We should change it to sprintf-js package.

![sprintfwarningmessage](https://user-images.githubusercontent.com/39359541/40931988-d6493748-67e1-11e8-88ec-daf8464acdf4.JPG)

**Comment by MRayermannMSFT** [comment]
In 1.17, make a list of all places we need to fix, and then we can evaluate the size of work.

**Comment by JasonYeMSFT** [comment]
Did a search through our current code. "sprintf" is no longer used anywhere. Closed.
