### ISSUE TITLE
Failed auto update

### ISSUE THREAD

**Issue by twallace27603** [microsoft/AzureStorageExplorer#2581]
I am currently on version 1.13. When I tried to auto update things went significantly off the rails.  I got an error that it could not shut down a process - Microsoft.ServiceHub.Controller.  Even after I manually stopped the task, retry would not work.  I aborted and it actually deleted Storage Explorer, but did not uninstall.  I downloaded the latest install and it worked.

**Comment by jinglouMSFT** [comment]
Where did you get 1.13?  The latest released version is 1.12.0 build 20200116.10.

**Comment by twallace27603** [comment]
Sorry, mis-typed.  It is indeed 1.12.  Everything else is legit though.  Thanks for pointing this out.

**Comment by jinglouMSFT** [comment]
Ah, it's possible that you were on a 1.12 build that shortly lived on the download side. If you are good with build 20200116.10, you will not have issues to auto upgrade when 1.13.0 comes out. Please let us know if you have issues using 1.12.0 build 20200116.10.  Thanks.

**Comment by centur** [comment]
Just got the same experience as @twallace27603 - old installation (something from 2019) can't stop processes but update itself messed up completely and damaged the installation when I tried to abort. Have to reinstall everything from scratch and re-connect accounts.

**Comment by MRayermannMSFT** [comment]
If the installer ever reports processes that need to close, we recommend closing them manually via task manager. We're working on making sure the processes you're seeing are consistently shut down.
