### ISSUE TITLE
Microsoft Azure Storage Explorerfailed to perform remove command due to error: nothing found to remove

### ISSUE THREAD

**Issue by Golliveira** [microsoft/AzureStorageExplorer#2582]
Hi,

I am using Microsoft Azure Storage Explorer to store ".pst" files to import emails into Exchange. Once finished, I am trying to delete the pst file that will no longer be used and the following message appears:

{
  "message": "\"failed to perform remove command due to error: nothing found to remove\""
}

Att,
Gabriel Oliveira

**Comment by jinglouMSFT** [comment]
Can you clarify which Storage Explorer you used?  The desktop application or the Storage Explorer in Azure portal?  If Storage Explorer desktop, which version and on which platform?
Also, tell us a bit more on how you "store", "import" and "delete" the .pst file? 
Thanks.

**Comment by MRayermannMSFT** [comment]
There should be a link in the activity log that'll take you to the AzCopy log file. Can you follow that link and attach the log to this issue. Thanks!

**Comment by MRayermannMSFT** [comment]
Related to: https://github.com/microsoft/AzureStorageExplorer/issues/2603

**Comment by MRayermannMSFT** [comment]
Going to go ahead and close this. Please continue this discussion in #2603 if you're still having problems.
