### ISSUE TITLE
Add explanation/link explaining permissions in Access Policies dialog

### ISSUE THREAD

**Issue by snerting** [microsoft/AzureStorageExplorer#2583]
When I am in Azure Storage Explorer and go to Manage Access Policies for a Blob I always wonder what those policies means. It would have been very helpful to have something explain what those policies mean, at least a link to a page who explain this.
 
![image](https://user-images.githubusercontent.com/1882879/73459118-91d3cc00-4376-11ea-8fa7-cf09c7a957f6.png)

**Comment by MRayermannMSFT** [comment]
Try to do for 1.13. Move to 1.14 and definitely do it there if we run out of time tho.

**Comment by MRayermannMSFT** [comment]
FYI we'll be pointing to these:

- https://docs.microsoft.com/en-us/rest/api/storageservices/create-service-sas#permissions-for-a-directory-container-or-blob
- https://docs.microsoft.com/en-us/rest/api/storageservices/create-service-sas#permissions-for-a-file
- https://docs.microsoft.com/en-us/rest/api/storageservices/create-service-sas#permissions-for-a-queue
- https://docs.microsoft.com/en-us/rest/api/storageservices/create-service-sas#permissions-for-a-table

**Comment by MRayermannMSFT** [comment]
Merged for 1.21!
