### ISSUE TITLE
Unable to view CosmosDB documents with MongoDB API

### ISSUE THREAD

**Issue by akshaybabloo** [microsoft/AzureStorageExplorer#2584]
**Storage Explorer Version**: 1.12.0
**Build Number**: 20200116.10
**Platform/OS**: Windows and Mac
**Architecture**: x64

## Bug Description ##

I am unable to view CosmosDB documents with MongoDB API

## Steps to Reproduce ##

1. Create a CosmosDB service with MongoDB API with partition key
2. Create a DB and add a document to it
3. Try viewing it Azure storage explorer

## Expected Experience ##

Should be able to view it

## Actual Experience ##

Empty, with a link `Load More`.

![storage-explorer](https://user-images.githubusercontent.com/7360286/73493332-6bb23880-4417-11ea-8e5f-ee8da68d3b0d.jpg)

## Additional Context ##

In the developer tools, I get `No attribute loader for: partitionKeyValue`

**Comment by akshaybabloo** [comment]
Any update on this?

**Comment by Duchex** [comment]
I can confirm I have the same issue:
`Debug.js:41 No attribute loader for: partitionKeyValue
error @ Debug.js:41
(anonymous) @ BindingHandler.js:27
tryCatch @ -internal.js:195
invokeCallback @ -internal.js:210
publish @ -internal.js:178
publishRejection @ -internal.js:120
flush @ asap.js:98
characterData (async)
(anonymous) @ asap.js:70
asap @ asap.js:20
(anonymous) @ then.js:23
then @ then.js:26
NodeAttributeResolver.resolveAttributes @ NodeAttributeResolver.js:44
BindingHandler._evaluateAttribute @ BindingHandler.js:65
BindingHandler.updateValue @ BindingHandler.js:21
BindingHandlerSet.updateBoundArgument @ BindingHandlerSet.js:34
BindingHandlerSet.resolveArguments @ BindingHandlerSet.js:23
ActionViewModel.resolveArguments @ ActionViewModel.js:54
(anonymous) @ NodeViewModel.js:390
step @ app.js:34
(anonymous) @ app.js:15
(anonymous) @ app.js:9
__awaiter @ app.js:5
NodeViewModel.executeAction @ NodeViewModel.js:383
defaultAction @ NodeViewModel.js:590
NodeViewModel.executeDefaultAction @ NodeViewModel.js:598
(anonymous) @ NodeViewModel.js:618
setTimeout (async)
NodeViewModel.handleClick @ NodeViewModel.js:614
(anonymous) @ knockout.js:79
dispatch @ jquery.js:5183
elemData.handle @ jquery.js:4991
`

**Comment by jsutes** [comment]
I also have this issue

**Comment by tarique7070** [comment]
Same problem here.

**Comment by davejhahn** [comment]
I am also having an issue where I cannot see the Documents...

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
