### ISSUE TITLE
Navigating "Back (Alt-LeftArrow)" should restore the previous Search by Prefix value

### ISSUE THREAD

**Issue by gdignard** [microsoft/AzureStorageExplorer#2585]
In the Blob Navigation, within a given Blob Container the application offers navigation both by the pseudo-directory structure as well as the ability to specify a Prefix value which filters the current display to only those items whose name (or current pseudo-directory name) begins with the given value.

So in a case where the Blob Container has the following blobs:

`foo01/bar001.txt`
`foo01/bar002.txt`
`foo02/bar003.txt`
`foo02/bar004.txt`
`foo11/bar005.txt`

You would initially see foo01, foo02, and foo11 as the top level in the container.

If you entered "foo0" as the Prefix value, the list would be reduced to foo01 and foo02.

If you then entered foo01, you would see the two files it contained (bar001 and bar002).

At this point, however, if you navigate "Back" using the left arrow in the UI or Alt-LeftArrow on the keyboard, you go back to the top level as expected, however the Prefix value will now have been lost; the entire list of all three directory names is once again displayed.

That behaviour corresponds to what I would expected when tapping "Up".

For "Back" I would propose that the application's behaviour would be to restore both the previous directory level as well as the previous prefix value. This should also be multi-level; if prefixes are applied the container is explored deeper and deeper, each Back would ideally also restore the prefix which had been specified for that directory level.

**Comment by gdignard** [comment]
Seeing that this issue was marked with a milestone of 1.17.0 which was released today, I was hopeful this new feature would be included.

It's not there, however, and the issue is still flagged as Open. Is there an update of when it might appear?

**Comment by MRayermannMSFT** [comment]
@gdignard I recently did some other work which also resulted in this issue being addressed. Here's a screenshot where you can see my various prefix filters in the recent navigation history:
![image](https://user-images.githubusercontent.com/21112697/129798525-4c212d59-64a6-4c37-83c0-f2951aa3ceb0.png)

You'll see this ship in 1.21 which is currently timed for mid September.

Also, in the future, if there is an issue/feature you are waiting on feel free to comment with a "+1" or add a positive emoji reaction to the original issue:
![image](https://user-images.githubusercontent.com/21112697/129798649-9c0685d3-0793-4e39-a11d-dec427184797.png)
That way we can know you want the issue, which helps us prioritize it (we give priority to issues with more user/customer interest). Thanks!

**Comment by gdignard** [comment]
Wonderful news! I'm definitely looking forward to having this new tool available!
