### ISSUE TITLE
File share file watcher

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#2586]
We have the feature for blobs to open a blob as a downloaded local file, watch changes on that file, and re-upload the updated data. We can implement its counter part for File share.

**Comment by stephenplant** [comment]
Storage explorer used to behave like this, with a dialog asking if you wanted to upload a file where it had detected a change. However this feature stopped working some time ago. When might a re-fix be released?

**Comment by JasonYeMSFT** [comment]
@stephenplant Could you please open a separate issue and provide the steps to reproduce the bug? Thanks.

**Comment by jinglouMSFT** [comment]
Let's discuss if this can be done in v1.26.0

**Comment by MRayermannMSFT** [comment]
- [ ] Create new queries after changing event names
- [ ] Try to de-dupe the skip & save code
- [ ] Clean up strings
- [ ] Clean up blob transfer code
