### ISSUE TITLE
Cosmos DB not showing documents

### ISSUE THREAD

**Issue by aluong** [microsoft/AzureStorageExplorer#2587]
**Storage Explorer Version**: 1.12.0
**Build Number**: 20200116.10 
**Platform/OS**: macOS Catalina
**Architecture**: x64
**Regression From**:  

## Bug Description ##
Zero documents are not showing up in Storage Explorer. However, I see them in the Azure Portal Cosmos DB  Data Explorer web UI.

## Steps to Reproduce ##
In the Azure Portal:
1. Create a new Cosmos DB (SQL)
2. Create a new container
3. Create a new document
4. Open Storage Explorer and navigate to the container and open the documents.
5. In Storage Explorer, click refresh the container 
6. In Storage Explorer, click load more.

## Expected Experience ##
I expect there to be the document I created from the Portal.

Here is the document I see from the Azure Portal Cosmos DB Data Explorer:
![image](https://user-images.githubusercontent.com/1683309/73580552-cf019200-443a-11ea-8064-65c775269ebb.png)

## Actual Experience ##
The documents pane is completely empty.
![image](https://user-images.githubusercontent.com/1683309/73580535-bee9b280-443a-11ea-87b8-60614d386584.png)

## Additional Context ##
I do notice when I try to create a document in Azure Storage Explorer it fails with:
![image](https://user-images.githubusercontent.com/1683309/73580524-b5f8e100-443a-11ea-8f9a-d0822e5eb176.png)

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
