### ISSUE TITLE
Can not login on Mac

### ISSUE THREAD

**Issue by mmclane** [Microsoft/AzureStorageExplorer#259]
**Storage Explorer Version**: 1.1.0
**Platform**: macOS
**Architecture**: x64
**Regression From**: From what we can tell, this problem occurs on Linux and MacOS but not on windows.

#### Steps to Reproduce: ####
1. Start Microsoft Azure Storage Explorer
2. Click Account Management button on the left
3. Click Add and account
4. Once the Connect to Azure Storage Window opens click sign in...
5. Enter email address m.mclane@criteo.com
6. Click Next
 

#### Expected Experience: ####
I expect it to login and connect me to my account

#### Actual Experience: ####
I get a blank windows with Sign in to your account in the title.

I have waited well over a minute.  After a while the waiting for authentication window goes away but I am never logged in.  

I have tried to reset my keychain

I have tried re-installing the application.

**Comment by mmclane** [comment]
I can connect via connection string or storage account name and key, but not SSO.

**Comment by mmclane** [comment]
I can connect via connection string or storage account name and key, but not SSO.

if I have the developer tools open in the window where I enter my email address, I get the following error:
id.criteois.com/adfs/ls/wia?client-request-id=30ba9dc2-ac11-419d-8115-dedaf…M1MFEwtLQysrQyMYgCAA2&cbcxt=&username=m.mclane%40criteo.com&mkt=&lc=1033:1 GET https://id.criteois.com/adfs/ls/wia?client-request-id=30ba9dc2-ac11-419d-81…MNM1MFEwtLQysrQyMYgCAA2&cbcxt=&username=m.mclane%40criteo.com&mkt=&lc=1033 401 (Unauthorized)

**Comment by mmclane** [comment]
I get the same experience with version 0.9.6

**Comment by mmclane** [comment]
I do not have a ~/.IdentityService/aadconfiguration file or directory

**Comment by MRayermannMSFT** [comment]
Are you behind a proxy? From what you're saying, it sounds like we're trying to redirect to your company's SSO page, but are unable to redirect (specifically, we're getting a 401 as you've seen).

**Comment by mmclane** [comment]
Not that I know of and as I said it works on a windows box on the same network.

Interestingly if I click on the **Can’t access your account?** link and then click Work or school account I can get our company logo once I enter my email address.

**Comment by mmclane** [comment]
So do have SSO on our accounts.  I am not sure if that is related or not.

**Comment by MRayermannMSFT** [comment]
Is your Windows box domain joined with your work account? And when you say "I can get our company logo once I enter my email address". Does that mean the logo shows up but nothing else, or are you getting to your company's custom sign in page, you do some stuff, and then when you try to continue you get another blank screen?

**Comment by mmclane** [comment]
The windows box isn't mine, so I will have to check on that later in the day.  I would be highly surprised if it wasn't however. 

About the logo... 

The window starts like this:
![image](https://user-images.githubusercontent.com/19716207/40977459-0af0c55c-689f-11e8-9fda-3af474f09d3d.png)
 
Then changes to this: 
![image](https://user-images.githubusercontent.com/19716207/40977548-3eb5cebe-689f-11e8-9d04-418efe449704.png)

If I enter the captia it tries to change my password but isn't able to.  It does not give me a 401 error.  I don't know if this indicates anything, but I think it means that I can talk to the backend server.  

If this is a problem with permissions getting to our id server I am hoping you can help me point our IIT guys in the right direction.  But since it works on one platform and not others, I think it might be a bug.

**Comment by jorisd** [comment]
Same issue on Linux boxes (Ubuntu 16.04)

**Comment by jorisd** [comment]
Could this one be assigned the sin-in label ?

**Comment by jorisd** [comment]
Hi @MRayermannMSFT 
I work with @mmclane and I confirm the issue wasn't with Storage Explorer itself. Rather with a ADFS mis-configuration.
This issue can be closed, sorry for the noise :+1:

**Comment by MRayermannMSFT** [comment]
Oh awesome! I'm really glad y'all were able to help each other out. 😄 Opportunities for all of us to help each other are a big reason we decided to move our issue tracking into the open. Anyway, let us know if you have any further feedback/bugs by opening new issues. I'll be closing this one for now since you two were the only participants and you're both unblocked.
