### ISSUE TITLE
Sign in loop problem

### ISSUE THREAD

**Issue by stephenhallfr** [microsoft/AzureStorageExplorer#2592]
**Storage Explorer Version**: <1.12.0>
**Build Number**: <20200114.3>
**Platform/OS**: < Windows 10>
**Architecture**: <x64>
**Regression From**:  <yes>

## Steps to Reproduce ##

I try to follow instrruction to get out of URL loop but it changed nothing
https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C1904#reauthentication-loop-or-upn-change

**Comment by MRayermannMSFT** [comment]
Hi @stephenhallfr , sorry for this not being in the trouble shooting guide, but can you please try using MSAL?

You can enable it in Settings, under Application -> Sign In. Make sure to restart before trying to sign in again.

If sign in fails, please let us know exactly how it failed/any error messages you receive.

I'll get the troubleshooting docs updated ASAP to include this. Thanks!

**Comment by stephenhallfr** [comment]
Hi Matthew,

thanks, it worked. I had to erase all accounts on Storage explorer and delete the .IdentityService folder.

but after it worked without problem.

**Comment by MRayermannMSFT** [comment]
Awesome! Glad to hear.
