### ISSUE TITLE
The Conflict dialog pops up after selecting ‘Upload’ option for one blob file

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2593]
**Storage Explorer Version:** 1.12.0
**Build:** [20200204.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3439677)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04
**Architecture:** ia32/x64
**Regression From:** Previous release(1.12.0)

**Steps to reproduce:**
1. Expand one Non-ADLS Gen2 storage account -> Blob Containers.
2. Create a new blob container -> Upload one text file to it.
3. Open this text file and make some changes -> Save it.
4. Select 'Upload' on the popped dialog then click 'Apply'.
5. Check the result.

**Expect Experience:**
No Conflict dialog pops up.

**Actual Experience:**
Pop up a Conflict dialog.
![image](https://user-images.githubusercontent.com/41351993/73729518-291e9200-4770-11ea-9a8f-092a977ca10a.png)

**More Info:**
This issue also reproduces when selecting 'Snapshot orginal blob then upload'.

**Comment by v-limu** [comment]
Verified on build [20200210.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3458474
). This issue has been fixed. So we close it.
