### ISSUE TITLE
The content shows incompletely in Add Entity dialog

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2594]
**Storage Explorer Version:** 1.12.0
**Build:** 20200204.4
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04
**Architecture**: ia32/x64
**Regression From**: Previous release(1.12.0)

**Steps to reproduce:**

1. Expand a storage account -> Tables.
2. Create a new table -> Add entity -> Add Property on the popped dialog.
3.  **Edit this property** and check the Edit Entity dialog.

**Expect Experience:**
The content shows completely.
![image](https://user-images.githubusercontent.com/54055206/73732155-ad731400-4774-11ea-8857-bdcbd0ec2ae0.png)

**Actual Experience:**
The content shows incompletely.
![image](https://user-images.githubusercontent.com/54055206/73732613-6f2a2480-4775-11ea-8717-6af5cbd55a90.png)

**More Info:**
This issue also reproduces on Edit Entity dialog.
![image](https://user-images.githubusercontent.com/54055206/73732563-591c6400-4775-11ea-811a-912f41f9d335.png)

**Comment by MRayermannMSFT** [comment]
Craig please make sure this doesn't repro anymore.
