### ISSUE TITLE
'Manage Access Policies' dialog title is incorrect

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2595]
**Storage Explorer Version:** 1.12.0
**Build:** [20200204.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3439677)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04
**Architecture:** ia32/x64
**Regression From:** Previous release(1.12.0)

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Select one blob container and right click it -> Select 'Manage Access Policies...'.
3. Check the title of the popped dialog.

**Expect Experience:**
Show 'Manage Access Policies'.
![image](https://user-images.githubusercontent.com/41351993/73734645-ec0acd80-4778-11ea-9ea5-05b5cbb6afb2.png)

**Actual Experience:**
Show 'Access Policies'.
![image](https://user-images.githubusercontent.com/41351993/73734743-13619a80-4779-11ea-9657-53b079bd298e.png)

**More Info:**
1. This issue also reproduces for one file share/ queue/ table.
2. This issue also reproduces for Generate Shared Access Signature dialog.
![image](https://user-images.githubusercontent.com/41351993/73734507-b5cd4e00-4778-11ea-9ae4-83b9538acda3.png)

**Comment by craxal** [comment]
By design. The title is now supposed to match the header in the dialog.
