### ISSUE TITLE
The splash screen is sometimes opened as a second program 

### ISSUE THREAD

**Issue by StingyJack** [microsoft/AzureStorageExplorer#2596]
**Storage Explorer Version**: 1.12.0
**Build Number**: See Storage Explorer Version. Please dont set a bad example by separating the two, when MSFT version numbers have _already had a build position in them for 40 years_.
**Platform/OS**: Win 10 10.0.17134 (note the build number included in the version )
**Architecture**: x64
**Regression From**:  this problem has been present before and was fixed, but now its back

## Bug Description ##
See picture
![image](https://user-images.githubusercontent.com/15381181/73751920-04092f80-472e-11ea-846a-f92af8b39fd2.png)

Sometimes this happens. I've only opened the program once but this second "instance" with a splash screen only  will show up.

**Comment by craxal** [comment]
@ StingyJack Comment is noted.

Just an FYI, the Storage Explorer build number is _not_ the same as the app version number. We often share private builds with testers and users to verify features or bug fixes, so it's important we know the build number when issues are reported.

For reference, Storage Explorer v1.12.0 has a build number of 20200116.10. You can easily see this in the About dialog.

**Comment by StingyJack** [comment]
@craxal - then the version number should be 1.12.20200116.10 or 1.12.10.20200116. There's been a place for build and rev in MSFT version numbering for 40 years.

**Comment by MRayermannMSFT** [comment]
@StingyJack , are you saying that the splash screen isn't going away, or are you more concerned about the fact that there's multiple processes in task manager?

**Comment by StingyJack** [comment]
I don't notice a performance drain or problem, but the extra window does get in the way of things, so I'd say the splash screen is more important.

**Comment by MRayermannMSFT** [comment]
So @StingyJack , to be clear, the splash screen is not going away at all? Or in other words, is the splash screen staying open well after the main window has shown?

**Comment by StingyJack** [comment]
Yes. I can make it go away by hovering the taskbar button for it long enough to make the two mini windows display, then clicking the x in the mini window for the splash screen. It does not close the usable program instance, just the splash screen. Closing the usable program instance closes both windows.

**Comment by craxal** [comment]
That's _very_ strange, because our startup process explicitly hides the splash screen when the app is initialized. We've never seen this happen before.

Not easy to debug on your end, either, since this is in the main process. Here's an idea you can try:

1. Open Microsoft Azure Storage Explorer\resources\app\out\app\index.js in a text editor.

2. Locate lines 422-436 and modify the code block to something like this (notice the added `console.log` lines):

   ```js
   splashWindow.on("close", function (event) { return tslib_1.__awaiter(_this, void 0, void 0, function () {
       console.log("DEBUG >>>>> Splash window closing");
       return tslib_1.__generator(this, function (_a) {
           splashWindow.removeAllListeners("close");
           if (!!mainWindow) {
               // let the main window handle closing
               console.log("DEBUG >>>>> Hiding splash window");
               splashWindow.hide();
               event.preventDefault();
               mainWindow.close();
           }
           else {
               // let the splash window try to handle closing
           }
           return [2 /*return*/];
       });
   }); });
   ```

3. Run Storage Explorer from the command line by opening a PowerShell window and entering:

   ```powershell
   C:\Program Files (x86)\Microsoft Azure Storage Explorer\StorageExplorer.exe
   ```

4. Observe the output on the command line. Do you see those debug statements appear?

**Comment by StingyJack** [comment]
@craxal - will these changes take effect if I run the program from the start menu or do I have to run it from CLI to get the debug output?   Asking because the issue is intermittent and I may not always remember to use the CLI.  

I did make the changes outlined (with a bit more debug log info) but im not seeing the problem at the moment.  I'll run it a few more times over the next couple of days, but be aware this did go away for a few months before resurfacing again recently.

**Comment by craxal** [comment]
@StingyJack Just so you know, the changes I mentioned above aren't meant to fix anything—just to help debug your situation. They should take effect regardless of where you run it from, but you won't actually see any of the debug output unless it's run from the command line.

**Comment by StingyJack** [comment]
@craxal - is there a switch I can add to the start menu shortcut to create the debug logs somewhere?

**Comment by StingyJack** [comment]
This is triggered by windows 10's rescaling of the desktop when I move between docked (3 external monitors) and undocked (1 laptop screen), or if I am RDP into my work laptop from my home PC and switch the RDP session from one screen attached to my home pc to another. Its not consistently happening. I just happened to have used the Storage Explorer and moved my RDP window to another screen, and now that splash screen is present. 

MS Teams does a similar thing pretty reliably in that it shows the toaster for the last notification I received (could have been several hours ago or more) in a weird position (over the clock and systray), and I cant interact with it at all. Only closing teams and reopening it fixes it.  Maybe its an electron app thing?

![image](https://user-images.githubusercontent.com/15381181/75626941-c9ae7900-5b99-11ea-8a72-908ab0ef99d9.png)

Windows 10 does other things to some programs when it rescales, like opening empty an empty email message from outlook, or showing an unclickable program (GlobalProtect in the above screenshot - im not sure if its Electron based or not). I dont think that Outlook is an electron app, but it does do different things. I also have slack (another electron app) that has not shown this kind of problem.

**Comment by craxal** [comment]
@StingyJack I've also observed that multi-resolution, multi-monitor setups are...still a work in progress for Windows. I have a 3-monitor setup myself, one being twice the resolution as the others and set to 200%, and occasionally things go wonky.

There's a possibility changing screen configurations messes up the info we save when Storage Explorer launches. We save the window state (size, maximized, etc.) so that on next launch, the window is opened in the state it was in last launch. A different monitor setup could conflict with that.

**Comment by StingyJack** [comment]
I was finally able to update to Windows in 1903 couple days ago, and haven't had this problem since. The general rescaling of Windows is much better now too.
