### ISSUE TITLE
Support HTTPS Emulator Endpoints

### ISSUE THREAD

**Issue by jongio** [microsoft/AzureStorageExplorer#2598]
**Is your feature request related to a problem? Please describe.**

Yes, I'm running Azurite under HTTPS and cannot connect to it via Storage Explorer without HTTP to HTTPS redirects.  Azurite doesn't officially support HTTPS, but we have devs that are asking for it.

**Describe the solution you'd like**

Allow us to specify HTTP or HTTPS in the attach to local emulator screen.

**Describe alternatives you've considered**

Reverse proxy to redirect HTTP to HTTPS, but that's more work than should be required.

**Additional context**

Add option to select HTTPS here: 
![image](https://user-images.githubusercontent.com/2163001/73819333-289fee80-47a4-11ea-81ab-117f3b80e79b.png)

**Comment by JasonYeMSFT** [comment]
Thanks for requesting the feature. Out of curiosity, can you share with us the steps to enable Azurite to work with HTTPS? It would be very helpful if we can learn how to do that for testing when we work on this feature request.

**Comment by jongio** [comment]
As a stopgap to help customers use Azurite with HTTPS today. I posted a blog on how to use an HTTPS-HTTP reverse proxy in this blog post: https://blog.jongallant.com/2020/02/azurite-https-defaultazurecredential/

**Comment by jongio** [comment]
Related customer request for Azurite HTTPS https://github.com/Azure/Azurite/issues/38

**Comment by jongio** [comment]
User voice HTTPS request: https://feedback.azure.com/forums/217298-storage/suggestions/10221816-add-support-for-https-endpoints-to-azure-storage-e

**Comment by MRayermannMSFT** [comment]
Putting this in 1.14.0, pending built-in support for this being added to Azurite.

**Comment by jongio** [comment]
@MRayermannMSFT - By what date does Azurite need to support HTTPS in order for this to make it into 1.14?

**Comment by jinglouMSFT** [comment]
Early Q2 CY2020

**Comment by MRayermannMSFT** [comment]
Issue is still open on Azurite. Will get to this once they support it natively.

**Comment by jongio** [comment]
HTTPS/Azurite work is currently being implemented. Current POR is to release this month.  I'll let you know when that happens.

**Comment by jongio** [comment]
HTTPS now supported in Azurite 3.7.0. https://www.npmjs.com/package/azurite/v/3.7.0

**Comment by jongio** [comment]
While testing this out with HTTPS Azurite connection string, I discovered that Storage Explorer doesn't support certs that have a self signed cert in the chain.  See details here: https://github.com/Azure/Azurite/issues/430

I would like to discuss options - as the Azurite certs will most likely be generated with local CA, such as mkcert or dotnet dev-certs.

The only way around this, that I could find, it to set the following env var, which obviously isn't secure

`set NODE_TLS_REJECT_UNAUTHORIZED=0`

https://github.com/Azure/Azurite/pull/431

**Comment by MRayermannMSFT** [comment]
@jongio we actually do support self signed certs! Go to Edit -> SSL Certificates -> Import Certificates

<img width="870" alt="image" src="https://user-images.githubusercontent.com/21112697/79788323-56092c80-82fd-11ea-8bf0-baf83aa903eb.png">

**Comment by jongio** [comment]
I was able to get it to work by importing the rootCA.pem file found in `mkcert -CAROOT`. Thank you.

I will update the Azurite docs to indicate this feature.

I created a new issue to suggest adding the import cert feature info to the dialog: #2852


Let's use this issue to track adding HTTPS support to the emulator add dialog:

![image](https://user-images.githubusercontent.com/2163001/79792289-818f1580-8303-11ea-8fd8-31c8e7800004.png)

![image](https://user-images.githubusercontent.com/2163001/79792303-8784f680-8303-11ea-914a-564cdef23f8f.png)



That way I don't have to use connection string.

Also, if the user selects "HTTPS" - it would be great if you could prompt them to let them know they should import their SSL cert.

Thanks,
Jon

**Comment by fardarter** [comment]
How can this be done programmatically? Trying to automate for devops.

```
      azurite --oauth basic --cert /certs/cert.pem --key /certs/key.pem
```

Is working fine for blob but not for queue and table
