### ISSUE TITLE
Cannot have Blob Container and Queue with same name in Quick Access and open both

### ISSUE THREAD

**Issue by JakeRadMSFT** [microsoft/AzureStorageExplorer#26]
**Storage Explorer Version: 0.9.6**

**OS Version: All**

**Steps to Reproduce:**

1. Add Blob Container with name "samename" to Quick Access
2.  Add Queue with name "samename" to Quick Access
3. Open Blob Container from Quick Access
4. Open Queue from Quick Access

**Expected Experience:**
Can open Queue and Blob Container.
**Actual Experience:**
Trying to open the 2nd one fails.

**Comment by mrdnote** [comment]
Same problem when adding 2 blob containers from different accounts but with the same name.

**Comment by JasonYeMSFT** [comment]
This has been fixed in latest version of Storage Explorer.
