### ISSUE TITLE
The created blob snapshot displays the Access Tier of base blob in manage snapshots editor

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#260]
**Storage Explorer Version**: 1.2.0
**Platform**: All
**Architecture**: ia32/x64
**Build Number**: 20180605.1
**Commit**:f8373d5a
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Launch Storage Explorer and select one Blob/GPV2 storage account.
2. Open a blob container and upload one blob to it.
3. Right click the uploaded blob then select 'Manage Snapshots'.
4. Create one snapshot for the base blob.
5. Check the created snapshot in manage snapshots editor.

#### Expected Experience: ####
No Access Tier displays for the created snapshot.

#### Actual Experience: ####
An Access Tier of the base blob displays for the created snapshot.
![accesstier](https://user-images.githubusercontent.com/34729022/40969105-963855b0-68a6-11e8-8dc2-6bf07045c06c.png)

#### More info: ####
The Access Tier doesn't display after refreshing.

**Comment by craxal** [comment]
Not sure whether snapshots have access tiers or not. @JakeRadMSFT will know more.

**Comment by craxal** [comment]
I just spoke with the platform team. They're aware of a problem where they don't always send the inferred access tier property.
