### ISSUE TITLE
The popped window is incorrect when downloading files under one file share

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2600]
**Storage Explorer Version:** 1.12.0
**Build**: [20200205.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3443569&view=results)
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04
**Architecture**: ia32/x64
**Regression From**: Previous release(1.12.0)

**Steps to reproduce:**

1. Expand one storage account -> File Shares.
2. Create a new file share -> Upload one file to it -> Try to download the file.
3. Check the popped window.

**Expect Experience:**
The popped window is correct. 
![image](https://user-images.githubusercontent.com/54055206/73823970-4e74d400-4834-11ea-955f-7f6fa4fe27dd.png)

**Actual Experience:**
The popped window is incorrect.
![image](https://user-images.githubusercontent.com/54055206/73824054-73694700-4834-11ea-8fe6-a938b7a31138.png)

**More Info:**
The download **blobs** window.
![image](https://user-images.githubusercontent.com/54055206/73823518-6566f680-4833-11ea-8e74-8c35a528bb55.png)

**Comment by jinglouMSFT** [comment]
@v-limu I personally prefer the new implementation.  It provides the same download experience as Blobs.  So I am ok to leave it as is.  Am I miss reading anything about this bug?

**Comment by JasonYeMSFT** [comment]
The file share experience should call the resources "blobs".

**Comment by jinglouMSFT** [comment]
got it.

**Comment by v-limu** [comment]
Verified on build [20200210.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3458474). The popped window's title has been fixed. So we close it.
![image](https://user-images.githubusercontent.com/54055206/74206380-1ba86100-4cb6-11ea-96fa-c1ce0407bfa9.png)
