### ISSUE TITLE
Remove ‘Retry Transfers...’ after uploading non-vhd files to one premium blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2601]
**Storage Explorer Version:** 1.12.0
**Build:** [20200205.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3443569)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one premium storage account -> Blob Containers.
2. Select one blob container -> Upload one non-vhd file to it.
3. Check the activity log.

**Expect Experience:**
No 'Retry Transfers...' action dispalys append to the log.

**Actual Experience:**
The action 'Retry Transfers...' displays append to the log.
![image](https://user-images.githubusercontent.com/41351993/73828266-e629f080-483b-11ea-9c01-653f02ee6ef6.png)

**More Info:**
This issue also reproduces when copying non-vhd files to one premium blob container.

**Comment by MRayermannMSFT** [comment]
Won't fix.
