### ISSUE TITLE
Storage Explorer doesn't maximize display when first launch

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2602]
**Storage Explorer Version:** 1.12.0
**Build:** [20200205.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3443569)
**Branch:** master
**Platform/OS:** Windows 10
**Architecture:** ia32
**Regression From:** Not a regression

**Steps to reproduce:**
1. Create a new virtual machine (Windows 10).
2. Install and launch Storage Explorer.
3. Check the result.

**Expect Experience:**
Storage Explorer maximize displays.

**Actual Experience:**
Storage Explorer doesn't maximize display.

**Comment by MRayermannMSFT** [comment]
That is not the expected behavior. Won't fix.
