### ISSUE TITLE
ADL Connection String does not use token 

### ISSUE THREAD

**Issue by mattbp** [microsoft/AzureStorageExplorer#2604]
Attempting to use a Service Principal Bearer Token to connect to ADLS Gen 1 via these steps:
1) From Azure Storage Explorer, go to "Connect to Data Lake Store"
2) Use Connection string of "adl://[URI]**;token=[Bearer Token]**" appended per [these docs].(https://docs.microsoft.com/bs-cyrl-ba/azure/kusto/api/connection-strings/storage)
3) Azure Storage Explorer says "Access Denied:Your Azure account don't have access permission for the provided Uri."

I presume Azure Storage Explorer is trying to verify my attached accounts have access (they do not).

**Comment by jinglouMSFT** [comment]
The retirement of ADLS Gen1 is now less than three months away. As [previously announced](https://azure.microsoft.com/en-us/updates/action-required-switch-to-azure-data-lake-storage-gen2-by-29-february-2024/) the service will be retired on 29 February 2024. With this date now close approaching we are going to close this issue as "won't fix". Documentation on how to migrate your data to ADLS Gen2/blob storage can be found here: https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-migrate-gen1-to-gen2-azure-portal

If you have any non ADLS Gen1 feedback for Storage Explorer, please feel free to open a new issue: https://github.com/microsoft/AzureStorageExplorer/issues/new/choose

This issue will now no longer be monitored.
