### ISSUE TITLE
Make CosmosDB query execute the selected part of query

### ISSUE THREAD

**Issue by ImrePyhvel** [microsoft/AzureStorageExplorer#2607]
**Problem**
It is often required to work/switch between related or different variations of the same query. Currently I have to either:

1. spread related queries to different tabs. But this gets cluttered quickly and is difficulty to see which tabs are "of the same group".
2. constantly comment queries in and out in the same tab. But this is cumbersome, especially  for multi-line queries.

Also currently, it is not intuitive that should user select a part of query (i.e. to exclude some trailing where conditions) and press "execute" then it is not the selection being executed (like in almost all other similar client tools) but the entire query. 

**Proposed solution**
Change the behavior of "Execute query" to:
1) if some text is selected in query editor window then execute just the selection
2) otherwise, execute entire query.

This seems like a rather trivial thing to implement and make the user experience more intuitive.

**Alternatives**
Alternative could be to implement some hierarchy to tabs, but it is significantly costlier to implement and would clutter the UI.

**Comment by southpolesteve** [comment]
The Cosmos team recently deprecated our integration with Azure Storage Explorer. [Here is the full deprecation notice from the 1.15.1 Storage Explorer release notes:](https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.15.1)

> The Azure Cosmos DB integration with Storage Explorer has been deprecated. Any existing functionality will not be removed for a minimum of one year from this release. Users should use the Azure Portal, the Azure Portal desktop app, or the standalone Cosmos Explorer instead – all of which contain many new features that aren’t currently supported in Storage Explorer. Additionally, the Azure Cosmos DB team has also open sourced the data explorer project and will be investing in their own desktop tooling at a later date. Please keep an eye on their repository for more information. 

Currently, we are not prioritizing new features or bug fixes for Cosmos in Azure Storage Explorer. If you the issue you are reporting also applies to the Azure Portal or https://cosmos.azure.com, please file an issue in [our open source Cosmos Explorer repo](https://github.com/Azure/cosmos-explorer)
