### ISSUE TITLE
Keyboard focus starts all over again after backing to 'Add Entity' dialog from 'Edit Entity' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#261]
**Storage Explorer Version**: 1.2.0
**Platform**: All
**Architecture**: ia32/x64
**Build Number**: 20180605.1
**Commit**:f8373d5a
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Launch Storage Explorer and expand Storage Accounts.
2. Open one table and Click 'Add Entity' button.
3. Add properties -> Focus on 'Edit Entity' button in 'Add Entity' dialog using Tab -> Close the 'Edit Entity' dialog.
4. Press Tab again and check the keyboard focus.

#### Expected Experience: ####
Tabbing to 'X' button next to the previous focus after pressing 'Tab' again.

#### Actual Experience: ####
Keyboard focus starts all over again.
![backing](https://user-images.githubusercontent.com/34729022/40970040-f5004560-68a8-11e8-9d1b-d9ea3933f1be.png)

**Comment by craxal** [comment]
Yeah, that's a pretty undesirable behavior. Not debilitating, so we'll fix for a future release.

**Comment by MRayermannMSFT** [comment]
Closing as won't fix unless we get complaints about this.
