### ISSUE TITLE
A11y_AzureToolsStorageExplorer_AddAccount_ConnectToAzureStorage_Keyboard: Keyboard focus goes on non-actionable controls(Texts)

### ISSUE THREAD

**Issue by Shivamd1** [microsoft/AzureStorageExplorer#2614]
“[Check out Accessibility Insights](https://accessibilityinsights.io/)! - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

GitHubTags: #A11y_AzureToolsStorageExplorer; #A11YTCS; #DesktopApp; #MAS2.1.1; #Keyboard; #Mac; #Benchmark; #A11ySev2; #Azure Tools Storage Explorer;

**Environment Details:**
Application Name: Azure Tools Storage Explorer
Application Version: 1.12.0
MacOS: Catalina 10.15.3

**Repro Steps:**
1. Launch Storage Explorer
2. Navigate to "Open Connect Dialog" pane present on left side of screen and hit enter.
3. "Connect to Azure Storage" popup opens.
4. Navigate to "how do you want to connect to your storage account or services" text by keyboard.

**Actual:**
Keyboard focus goes on non-actionable controls(Texts "how do you want to connect to your storage account or services") Using Tab key .

**Expected:**
Keyboard focus should not go on non-actionable controls(Texts"how do you want to connect to your storage account or services") Using Tab key.

**User Impact:**
Keyboard only users face difficulty to know whether the control is actionable or not if keyboard focus goes on non-actionable controls using Tab key.

**Recommendation:**
https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx

**MAS Reference:
MAS2.1.1:**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={8492c4eb-c179-40ae-8777-cd044ed725a2}

**Comment by Shivamd1** [comment]
We have uploaded repro video of this bug in [OneDrive](https://microsoft-my.sharepoint.com/:f:/p/v-subha/EvxHdg1zkN9PknF1uOxnOiQBejpxKYg9n21DydgQ_om0ew?e=WK2Zih) link with name "2614_A11y_AzureToolsStorageExplorer_AddAccount_ConnectToAzureStorage_Keyboard" please refer the video for reference.
Please let us know if there is any problem in accessing the link

**Comment by craxal** [comment]
@Shivamd1 This bug is not reproducible on my end. It looks like this was fixed by @JasonYeMSFT over 8 months ago in PR 226643. Please verify.

**Comment by Shivamd1** [comment]
@MayuriNaik Can you please look into it?

**Comment by MayuriNaik** [comment]
Closing this bug as it is fixed in application Version: 1.16.0-dev.

**Comment by Shivamd1** [comment]
Verified the bug in Version: 1.16.0-dev the issue does not reproduces so closing the bug
