### ISSUE TITLE
The actions item shows strangely in the 'Actions' panel

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2616]
**Storage Explorer Version:** 1.12.0
**Build**: [20200210.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3458474)
**Branch**: master
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture**: ia32/x64
**Regression From**: Previous release(1.12.0)

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Check the actions in the 'Actions' panel.

**Expect Experience:**
The actions item shows well.

**Actual Experience:**
The actions item shows strangely.

**Comment by craxal** [comment]
@v-limu Can you share some screenshot, please? We're not sure what you mean by the action items showing "strangely".

**Comment by jinglouMSFT** [comment]
This is what I have on this particular build.
![image](https://user-images.githubusercontent.com/10081483/74268708-29adb000-4cbd-11ea-85f9-73c81e7a8357.png)

**Comment by jinglouMSFT** [comment]
Hit the wrong button. Reopen.

**Comment by v-limu** [comment]
Hi @craxal @jinglouMSFT 😉

1. Click 'Storage Accounts'. The actions show strangely in 'Actions' panel.
 ![image](https://user-images.githubusercontent.com/54055206/74296172-11519a00-4d7e-11ea-8a95-bfe4f7878c9c.png)
2. This issue also reproduces in clicking all items.

**Comment by jinglouMSFT** [comment]
oh yeah. I see this too on my install using the same build.

**Comment by JasonYeMSFT** [comment]
A fix has been merged. Please verify.

**Comment by v-xianya** [comment]
@JasonYeMSFT 

Verified on build [20200311.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3541290). Reproduce.

**Comment by v-xianya** [comment]
Fixed on build [20200312.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3544533). So close it.
