### ISSUE TITLE
Windows Portable version

### ISSUE THREAD

**Issue by baltuonis** [microsoft/AzureStorageExplorer#2619]
**Is your feature request related to a problem? Please describe.**
Current windows build (setup) requires administrator rights. This is a problem when working on limited access machines.

**Describe the solution you'd like**
Provide a portable standalone build for windows (like we have in Linux)

**Describe alternatives you've considered**
Tried to manually extract the setup, but that did not work.

**Additional context**

**Comment by MRayermannMSFT** [comment]
Duplicate of #1108
