### ISSUE TITLE
'Properties' Panel isn't refreshed after focusing next panel using F6

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#262]
**Storage Explorer Version**: 1.2.0
**Platform**: All
**Architecture**: ia32/x64
**Build Number**: 20180605.1
**Commit**:f8373d5a
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Launch Storage Explorer and select one account.
2. Focus on 'Properties' Panel using F6.
3. Press F6 again.
4. Check whether the 'Properties' Panel is refreshed or not.

#### Expected Experience: ####
The 'Properties' Panel is refreshed.(The focus of first property in 'Properties' Panel is lost)

#### Actual Experience: ####
The 'Properties' Panel isn't refreshed.

#### More info: ####
The issue doesn't reproduce after focusing previous panel using Shift+F6(Explorer Panel).

**Comment by craxal** [comment]
I'm a little confused. What is the basis of your expectation that the panel is supposed to refresh? Properties are generated only once when they are needed, which is when the node is selected for the first time. The only way to refresh the properties is to refresh the node itself.

**Comment by v-xuanzh** [comment]
Hi Craig,
For this issue, when we focus to 'Properties' Panel from 'Explorer' Panel using F6, the first property is focused by default like below.
![focusedfirst](https://user-images.githubusercontent.com/34729022/41023999-7f7da804-695d-11e8-9351-85182d2b878c.png)
Then press F6 again to focus the container editor Panel.

Expect:
The focuse of the first property in previous panel is lost.
![lost](https://user-images.githubusercontent.com/34729022/41024201-1b75b8aa-695e-11e8-9841-ea32e48596a5.png)

Actual:
The focus of the first property in previous panel still exists.

**Comment by craxal** [comment]
OK, so this isn't about "refreshing", right? Just focus in the panel.

I tested it out myself, and it's behaving as expected. What you're seeing is not focus. It's selected inactive text. If you look at the tabs (or Activity Log if there aren't any tabs), you should see that the next panel does have focus. In fact, look closely, and you should see the text box in question no longer has a border around it.

**Comment by v-xuanzh** [comment]
Yes, This issue just invoke focus in the panel.

Inaddition, thanks for your sharing and updates.
