### ISSUE TITLE
Forever Searches for Containers

### ISSUE THREAD

**Issue by t0642k8** [microsoft/AzureStorageExplorer#2620]
**Storage Explorer Version**: 1.12.0

**Platform/OS**:   windows 10  x64

**Regression From**:  No 

## Bug Description ##
Not sure if it is a bug, but on all Blob Storage , it searches and never seems to find the containers. 
Made a container in File shares and didn't find it was well. 

## Steps to Reproduce ##
1> open Storage explorer and authenticated my Credentials
2) I see all my storage account names, when it expand Blob containers it searches and does not stop

## Expected Experience ##
 I work at a US Government Facility, could possible be a ports issue.

**Comment by jinglouMSFT** [comment]
Were you signing into government Azure, or just the public Azure?  Are you behind a proxy?  If so, have you configured the proxy settings in Storage Explorer?  Also, have you tried these troubleshooting steps?  https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C1904#missing-subscriptions-and-broken-tenants

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.

**Comment by MRayermannMSFT** [comment]
Related to #1790
