### ISSUE TITLE
Add tenant name node in tree view.

### ISSUE THREAD

**Issue by blugri** [microsoft/AzureStorageExplorer#2621]
**Is your feature request related to a problem? Please describe.**
When working on multiple tenants, subscriptions are in one big list in the tree view. It is difficult to see which subscription belongs to which tenant.

**Describe the solution you'd like**
Add tenant nodes in the tree view for better visibility on which subscriptions belong to which tenants.

**Describe alternatives you've considered**
--

**Additional context**
--

**Comment by MRayermannMSFT** [comment]
@blugri Would it help if we grouped subscriptions by tenant in the account panel?

**Comment by blugri** [comment]
@MRayermannMSFT it seems that they are already grouped by tenant.

**Comment by MRayermannMSFT** [comment]
We'll think about this and consider it fully closer to 1.16

**Comment by alpinedelight** [comment]
Per this screenshot from version 1.12.0 there is no tenant grouping - I'm part of 6 tenants, many with similar subscription names, there is no way to distinguish. Note, subscription is part of a tenant (subscription != tenant)
![image](https://user-images.githubusercontent.com/23420164/76956767-90ea0000-690c-11ea-9ec3-031be081e34f.png)

**Comment by MRayermannMSFT** [comment]
@blugri @alpinedelight is there a reason y'all don't filter out subscriptions in the account panel?

**Comment by MRayermannMSFT** [comment]
Revisit this after #460 ships

**Comment by ziesemer** [comment]
To add some context from #460 ([specific comment](https://github.com/microsoft/AzureStorageExplorer/issues/460#issuecomment-805438482), paraphrased)  :

We should please have an option to include the tenant display name, tenant GUID, or even subscription GUID next to each loaded subscription in the Explorer. The majority of the tenants that I work in are all "Azure Subscription 1", so I have what appear to be duplicate accounts in the Explorer:

    Azure subscription 1 (ziesemer@example.com)
    Azure subscription 1 (ziesemer@example.com)
    ...

... with no way to differentiate between them without recognizing the different storage account names, etc., contained within.

In the "Properties" panel, after clicking on each, it at least shows the "Subscription ID", along with "Account Email" and "Environment" (but here, the "Account Email" and "Environment" are also all identical). Ideally, the tenant display name and tenant GUID would also be included as properties here - with at least one additional bit available for display inline in the tree.

**Comment by MRayermannMSFT** [comment]
For 1.32 we will add tenant name and/or subscription ID into the ()s portion of the node name depending on if the existance of subscriptions with duplicate names in the same/different tenant also exist. Example:

![image](https://github.com/microsoft/AzureStorageExplorer/assets/21112697/5e12548a-0916-4f26-a82f-23a539b35ef5)
