### ISSUE TITLE
Order resources manually

### ISSUE THREAD

**Issue by ohadbitt** [microsoft/AzureStorageExplorer#2622]
**Describe the solution you'd like**
It will be very helpfull if i could click and drag the storage accounts for example - so i can order them the way i want - this way i can cluster related storage accounts together

**Comment by MRayermannMSFT** [comment]
Would being able to view storage accounts by resource group help?

**Comment by MRayermannMSFT** [comment]
@ohadbitt we're prioritizing letting folks organize resources by resource group (see #265 ). If this doesn't work for you, we're also open to organizing by ARM tags. You can let us know if you that would interest you by opening a new issue. Overall, our curren philosophy is to minimize creating additional organizational structures/concepts outside of what Azure provides.
