### ISSUE TITLE
There are strings not localized in Settings Sign-in part

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2623]
**Storage Explorer Version:** 1.12.0
**Build**: [20200212.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3464483&view=results)
**Branch**: master
**Language**: Czech/ German/ Spanish/ French/ Hungarian/ Italian/ Japanese/ Korean/ Dutch/ Polish/ Portuguese (Brazil)/ Portuguese (Portugal)/ Russian/ Swedish/ Turkish/ Chinese (Simplified) / Chinese (Traditional)
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '**Svenska**' -> Restart Storage Explorer.
3. Open 'Settings' -> Localized 'Application' -> Localized  'Sign-in'.
4. Check the strings in this part.

**Expect Experience:**
The strings that need localized are all localized.

**Actual Experience:**
There are strings not localized in Settings Sign-in part.
![image](https://user-images.githubusercontent.com/41351993/74320805-38c75780-4dbc-11ea-9c39-11eff1dcaebb.png)

**Comment by lukaschal** [comment]
New string from 2/10/2020.

File: loc\en\src\Standalone\resources\Shell.json
ID: 0; "DescriptionSignInVerboseLogging"
SRC: Enables verbose logging for authentication. For more information about how and when to use this setting, refer to the Storage Explorer troubleshooting guide (Help → Troubleshooting Guide). Storage Explorer must be restarted for this setting to be applied.

**Comment by MRayermannMSFT** [comment]
Fairly new strings. Give it a little bit of time to get translated. I'll check back in on this later.

**Comment by v-xianya** [comment]
This issue has been fixed on build [20200220.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3486308). So we closed it.
