### ISSUE TITLE
Miss quotes for localized "Opt Out of Sending Telemetry" in Telemetry Settings page

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2624]
**Storage Explorer Version:** 1.12.0
**Build**: [20200212.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3464483&view=results)
**Branch**: master
**Language**:  Swedish/ Czech/ Hungarian/ Polish
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '**Svenska**' -> Restart Storage Explorer.
3. Click localized 'Help' -> Select localized 'Telemetry Setting'.
4. Check whether the localized 'Opt Out of Sending Telemetry' is surrounded by quotes or not.

**Expect Experience:**
The localized 'Opt Out of Sending Telemetry' is surrounded by quotes.

**Actual Experience:**
Miss quotes for localized "Opt Out of Sending Telemetry" in Telemetry Settings page.
![image](https://user-images.githubusercontent.com/41351993/74322251-9ceb1b00-4dbe-11ea-901c-88f3dc7b9885.png)

**More Info:**
ENU Screenshot:
![image](https://user-images.githubusercontent.com/41351993/74322495-fa7f6780-4dbe-11ea-9158-4178a8cf8853.png)

**Comment by v-xianya** [comment]
Comments:
In polish
![image](https://user-images.githubusercontent.com/41351993/74401548-93b08b80-4e5c-11ea-85b8-65f40d3f80bd.png)

**Comment by jinglouMSFT** [comment]
@lukaschal Is this by-design from a linguistic point of view? Thanks,

**Comment by lukaschal** [comment]
@jinglouMSFT Confirmed with linguists that this is by design for Swedish/ Czech/ Hungarian/ Polish .

**Comment by lukaschal** [comment]
Fixed on swedish.

new tgt: Du kan när som helst avanmäla dig från att skicka telemetri. Gör det genom att välja ”Avanmäl dig från att skicka telemetri” nedan.

**Comment by v-xianya** [comment]
Verified this issue on build 20200224.3. This issue has been fixed in Swedish.
Hence we close it.
