### ISSUE TITLE
When uploading .js files wrong content type is set

### ISSUE THREAD

**Issue by mvanhalen** [microsoft/AzureStorageExplorer#2627]
**Storage Explorer Version**: 1.12.0
**Build Number**: 20200116.10
**Platform/OS**: Windows 10 
**Architecture**: x64
**Regression From**:  Unknown

## Bug Description ##
When adding or replacing .js files they get content type is "text/plain; charset=utf-8" assigned. This is an issue for multiple reasons.

1. It should be application/javascript
2. Adding the charset value disables compression in Azure Edge CDN from Akamai. Pls don't do that.
3. It content type is being reset after replace.

## Steps to Reproduce ##
Just add a . js file to a store blob by dragging and dropping 

## Expected Experience ##
Content type should be  application/javascript also after replacement

## Actual Experience ##
Content type is text/plain; charset=utf-8 

## Additional Context ##
When serving content from storage blobs via a Azure CDN the compression is disabled.

**Comment by JasonYeMSFT** [comment]
Potentially related to #2267. To summarize, the content type we (azcopy) set the uploaded file to is based on the Content Type property associated with that file extension in your Windows registry.

**Comment by MRayermannMSFT** [comment]
Closing since it is possible to update the registry for .js file types.

**Comment by mvanhalen** [comment]
Ok good to know. Having an easy way to edit that from storage explorer would be nice.
