### ISSUE TITLE
Display an incorrect punctuation in Telemetry Settings page

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2628]
**Storage Explorer Version:** 1.12.0
**Build**: [20200213.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3467660)
**Branch**: master
**Language**: Turkish/ Korean
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '**Türkçe**' -> Restart Storage Explorer.
3. Click localized ‘Help’ -> Click localized ' Telemetry Setting'.
4. Check the punctuations in the 'Telemetry Setting' page.

**Expect Experience:**
Display a correct punctuation.
ENU screenshot:
![image](https://user-images.githubusercontent.com/41351993/74418297-249a5d80-4e83-11ea-92dd-e04a206a2962.png)

**Actual Experience:**
Display an incorrect punctuation.
![image](https://user-images.githubusercontent.com/41351993/74418393-41cf2c00-4e83-11ea-9bee-4bbc4824013a.png)

**More Info:**
1. This issue also reproduces in Add Message dialog for one queue in Turkish.
![image](https://user-images.githubusercontent.com/41351993/74418625-9bcff180-4e83-11ea-953c-497119e138cf.png)
ENU screenshot:
![image](https://user-images.githubusercontent.com/41351993/74420480-798ba300-4e86-11ea-9e21-a281b0c4ff59.png)

2. This issue also reproduces in Korean.
![image](https://user-images.githubusercontent.com/41351993/74418671-b1451b80-4e83-11ea-87bb-613bd3fe0979.png)

**Comment by lukaschal** [comment]
Fixed.

SRC: Telemetry collected includes

new kor tgt: 수집된 원격 분석에 다음이 포함됩니다
new trk tgt: Toplanan telemetri şunları içerir

**Comment by v-xianya** [comment]
@lukaschal Verified this issue on build 20200214.2
This issue also reproduces for Add Message dialog.
Turkish screenshot:
![image](https://user-images.githubusercontent.com/41351993/74506849-b2cf1c00-4f35-11ea-92f1-508f5c1594a4.png)
ENU screenshot:
![image](https://user-images.githubusercontent.com/41351993/74507106-74862c80-4f36-11ea-9691-07eae62a67ce.png)

**Comment by lukaschal** [comment]
Fixed as well.

**Comment by v-xianya** [comment]
Verified this issue on build 20200216.2. Fixed.
So we close it.
