### ISSUE TITLE
The character 'Gen1' is localized on Settings panel

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2629]
**Storage Explorer Version:** 1.12.0
**Build**: [20200213.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3467660)
**Branch**: master
**Language**: Turkish
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '**Türkçe**' -> Restart Storage Explorer.
3. Open 'Settings' -> Localized 'Services'.
4. Check the character 'Gen1' on the panel.

**Expect Experience:**
The character 'Gen1' is not localized.

**Actual Experience:**
The character 'Gen1' is localized.
![image](https://user-images.githubusercontent.com/41351993/74419512-fb7acc80-4e84-11ea-84d5-47111b32f71d.png)

**More Info:**
1. ENU screenshot:
![image](https://user-images.githubusercontent.com/41351993/74419550-0cc3d900-4e85-11ea-94e2-1574e78f6537.png)
2. This issue also reprodues for 'Gen2' on Settings panel.
 ENU screenshot:
![image](https://user-images.githubusercontent.com/41351993/74419899-907dc580-4e85-11ea-9566-ef4588a19fd1.png)
Turkish screenshot:
![image](https://user-images.githubusercontent.com/41351993/74419892-8cea3e80-4e85-11ea-8851-7a599fa36b58.png)
3. This issue also reproduces for 'Gen2' on Attach with Azure AD dialog.
ENU screenshot:
![image](https://user-images.githubusercontent.com/41351993/74421546-2e728f80-4e88-11ea-9c64-193ee335cab1.png)
Turkish screenshot:
![image](https://user-images.githubusercontent.com/41351993/74421424-f703e300-4e87-11ea-8b2e-6f7ad2c6d616.png)

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
Verified with linguist that actual translation are correct for TRK.

**Comment by jinglouMSFT** [comment]
@v-xianya This is by design for Turkish.  I've verified in 20200210.4.

**Comment by v-xianya** [comment]
Hi @jinglouMSFT  Got it. Thank you for the updates.
