### ISSUE TITLE
Feature request for ADLS...

### ISSUE THREAD

**Issue by atefyaziz** [microsoft/AzureStorageExplorer#263]
Extend functionality to data lake store and allow to connect to Data Lake Store with DLS Name like adding Storage account with Key

**Comment by craxal** [comment]
@atefyaziz Can you clarify what you're asking?

- *Extend functionality to data lake store...*
   What functionality are you referring to that you want extended?
- *...allow to connect to Data Lake Store with DLS Name like adding Storage account with Key*
   Are you asking for one or two different ways to connect to ADLS here?

**Comment by atefyaziz** [comment]
Point 2: Yes, I mean a sort of login screen like the one used to connect to Storage account, where user input {user name & Password & DLS_name } or {APP_Id & key & DLS name }

sometimes users get lost when they are connecting to environment with tons of data lake store account (like we already have) and a need to get focused to one Data lake store is important thing for them
thanks

**Comment by ziyel** [comment]
@atefyaziz 
For get lost in tons of data lake store accounts, could you try `Add to quick access`?
You can right click a data lake store account and choose the `Add to Quick Access` action.
![image](https://user-images.githubusercontent.com/1286176/41145293-3383301e-6b32-11e8-83a2-42f0429dd83a.png)

And you can also link the data lake store via URL.
1. Right click the `Data Lake Store(Preview)` node under `(Local and Attached)`.
![image](https://user-images.githubusercontent.com/1286176/41145394-888bdade-6b32-11e8-8516-5039d2bcce45.png)
2. Click `Connect to Data Lake Store`.
![image](https://user-images.githubusercontent.com/1286176/41145408-928acb76-6b32-11e8-905a-7c690fe173ea.png)
3. Input the URL of ADL, format is `adl://accountname.azuredatalakestore.net/your/folder`. Make sure you have login and have the access to the URL.
![image](https://user-images.githubusercontent.com/1286176/41145507-da5a0228-6b32-11e8-8323-bf3daeefd671.png)

**Comment by jinglouMSFT** [comment]
The retirement of ADLS Gen1 is now less than three months away. As [previously announced](https://azure.microsoft.com/en-us/updates/action-required-switch-to-azure-data-lake-storage-gen2-by-29-february-2024/) the service will be retired on 29 February 2024. With this date now close approaching we are going to close this issue as "won't fix". Documentation on how to migrate your data to ADLS Gen2/blob storage can be found here: https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-migrate-gen1-to-gen2-azure-portal

If you have any non ADLS Gen1 feedback for Storage Explorer, please feel free to open a new issue: https://github.com/microsoft/AzureStorageExplorer/issues/new/choose

This issue will now no longer be monitored.
