### ISSUE TITLE
Documentation about DeepLink or commandline arguments

### ISSUE THREAD

**Issue by averhaegen** [microsoft/AzureStorageExplorer#2630]
**Is your feature request related to a problem? Please describe.**
I'm trying to open the Storage Explorer from a PowerShell window and directly connect to a specific SAS URI connection. Actually I use this script to retrieve a SAS token from a Key Vault and generate a SAS URI for me. It would be nice if my script could automatically open this connection. 
I see the Storage Explorer supports some commandline parameters like '--disable-gpu" or Deeplink from the Azure portal like: "storageexplorer://". But I cannot find documentation about this topic.

**Describe the solution you'd like**
I'd like to see documentation about supported Commandline parameters and Deeplink parameters. 

**Describe alternatives you've considered**
I tried searching the Microsoft docs and also checked the Release page to see if any info could be found in the Release notes. But I did not find anything about it.
Maybe I can alter the local storage coockie and Windows Credential Manager to inject my SAS uri. Perhaps Storage Explorer would load it in when I run the program. But I did not test this yet as it seems very complicated to implement 

**Additional context**
I'd like to open Storage Explorer something like this in command prompt or PowerShell:
`.\StorageExplorer.exe --sas-uri: 'https:\\xxx.file.core.windows.net/?sv=2019-02-02&ss=f&......'`
or from a browser deeplink like
`storageexplorer://v=1&sasuri=https:\\xxx.file.core.windows.net/?sv=2019-02-02&ss=f&......`

**Comment by MRayermannMSFT** [comment]
Hi @averhaegen 

The deeplink feature is currently very limited and does not support what you would like to use it for. I believe we already have people asking for similar abilities though, so it is on our backlog. As for documenting its format, that's not something we would look to do at this time.

As for the command line parameters, we're definitely willing to document those. Feel we'll use this issue to track that work.

**Comment by tedvanderveen** [comment]
For our custmers (who do not have Azure / AAD login accounts) it would be great if we can simple supply a deep link that includes a SAS token, like the example provided by @averhaegen.

**Comment by JasonYeMSFT** [comment]
We are going to start writing these documentations but it will needs to be in 1.19.0.

**Comment by JasonYeMSFT** [comment]
- [ ] Deeplink documentation
- [x] Command line options documentation
