### ISSUE TITLE
Deleting text in query filter prompts for table entity delete

### ISSUE THREAD

**Issue by HugoLingiardi** [microsoft/AzureStorageExplorer#2631]
**Storage Explorer Version**: 1.12.0 
**Build Number**:  2020116.10
**Platform/OS**:  Windows 10 
**Architecture**: x64 
**Regression From**: Yes, it worked on previous versions but I can't remember which one.

## Bug Description ##
In the table records visualization when I try to clean a Query filter expression with the key 'DELETE' (the keyboard key) pops a dialog asking me to confirm the deletion of the selected record. Accidentally I deleted a record of my production table because of this bug. If the default focus of deletion dialog started on the button 'NO' that could be avoided.

## Steps to Reproduce ##
1. Open a table in your Storage Azure Explorer
2. Click on Query button
3. Choose the content of any fields that will appear
4. Select all the text and press the key 'DELETE' on your keyboard
5. The content will be deleted and a dialog will pops up

## Expected Experience ##
I expect the key 'DELETE' when pressed on the filter of the query delete only the content of this field and keep my table records intact.

## Actual Experience ##
Trying to clean a filter in the query window of the Azure Storage Explorer I accidentally deleted a record of my production table.

![image](https://user-images.githubusercontent.com/13078487/74539667-36304380-4f1d-11ea-96a2-8128faea84ae.png)

**Comment by jinglouMSFT** [comment]
@craxal - can you try to fix this for 1.13.0?  Thanks.

**Comment by craxal** [comment]
For some reason, our keyup event listener was registered to the _entire document_ instead of just the table. Easy fix; we just need to bind to the table element instead.

**Comment by dspeidel** [comment]
I assume the fix affects the Text Editor window as well as the Query Builder?

**Comment by craxal** [comment]
@dspeidel You are correct. With this fix, if you use the builder and check the text editor, the L will be there.

**Comment by AlexUrbanAc** [comment]
When can we expect "the next release"? I just lost data again.

**Comment by craxal** [comment]
We've been waiting for some essential updates to several components. We're hoping to get something out this month.
