### ISSUE TITLE
Don't automatically download updates on metered connections

### ISSUE THREAD

**Issue by robinmira** [microsoft/AzureStorageExplorer#2632]
**Is your feature request related to a problem? Please describe.**
Storage Explorer downloads updates on metered connections and there doesn't appear to be a setting to prevent it from automatically downloading updates.

**Describe the solution you'd like**
Respect the system's metered connection settings or provide an option in the Storage Explorer settings to disable automatic downloading of updates.

**Comment by jinglouMSFT** [comment]
Storage Explorer doesn't automatically download updates unless the user instructs to update when/if prompted. Could you tell us where and how you observed the auto download behavior?

**Comment by MRayermannMSFT** [comment]
For now we're going to add this setting:
![image](https://user-images.githubusercontent.com/21112697/84965058-b2e94f00-b0c2-11ea-9109-525019954ba0.png)

You can choose to disable it whenever you are on a metered connection.

After I've checked this in, I'll open a new issue for doing something smarter, like asking the OS if you're currently on a metered connection, and if so, suggesting you toggle this setting. That'll be put into future for now though, as talking to the OS is quite a bit of work unfortunately.

**Comment by MRayermannMSFT** [comment]
Setting checked into master for 1.15 release.

**Comment by MRayermannMSFT** [comment]
Here's an issue to track auto detecting metered connections: https://github.com/microsoft/AzureStorageExplorer/issues/3131

**Comment by schenardie** [comment]
Can this be chosen during silent install?? A switch like /noupdates or something like it?? For companies who keep track of versioning not having the app prompt the user every time it opens would be great.

**Comment by MRayermannMSFT** [comment]
@schenardie we don't typically look back at closed issues in this repo unless there's a reason to do so. Thankfully today I was looking for this issue and saw your comment. Please open a new feature request for what you are asking for and we'll triage it. Thanks!
