### ISSUE TITLE
Container cloning changes the case for blob metadata keys 

### ISSUE THREAD

**Issue by salomongorin** [microsoft/AzureStorageExplorer#2633]
**Storage Explorer Version**: 1.12.0
**Build Number**: 2020016.10
**Platform/OS**: Windows
**Architecture**: ia32
**Regression From**:  not sure

## Bug Description ##
When cloning an existing blob container to a new container, the metadata on the blobs that are copied from the source container to the destination container is changed. Specifically the case on the metadata key values is changed to have the first letter capitalized followed by all lowercase. 

## Steps to Reproduce ##
1. Create a container in blob storage "source"
2. Upload a new blob "myBlob" to "source"
3. Add metadata to the blob from step 2, key = "mixedCase", value = "someValue"
4. In storage explorer right click on "source", select "Clone with New Name"
5. Enter "destination" as new container name and click Clone
6. Wait for data transfer to complete
7. Inspect the metadata on "myBlob" in the "destination" container. Notice that the case of the entry for "mixedCase" is now "Mixedcase"

## Expected Experience ##
metadata keys should keep the same case in the destination blob as is in the source blob

## Actual Experience ##
metadata keys do not have the same case

## Additional Context ##
This presents an issue since C# clients for Azure Storage libraries make metadata available in Dictionary objects and trying to access a key/value pair with a case-sensitive key will throw an exception.

**Comment by JasonYeMSFT** [comment]
We already have an issue tracking this. See #2573 for discussion there. We are currently working on a fix for this right now.

**Comment by salomongorin** [comment]
Thanks. Didn’t see that when I ran a search for any open tickets.
