### ISSUE TITLE
Failure getting subscriptions from Azure

### ISSUE THREAD

**Issue by Buchmasx** [microsoft/AzureStorageExplorer#2634]
When I add my account and authenticate then I receive a message saying I could pull in subscription details - the error is this:

Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: 4248050d-f195-46d5-ac9c-0c7c52b04cae, Error: {
  "name": "Error",
  "message": "self signed certificate in certificate chain",
  "stack": "Error: self signed certificate in certificate chain\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at TLSSocket.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at TLSSocket.emit (events.js:182:13)\n    at TLSSocket._finishInit (_tls_wrap.js:631:8)",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}

**Comment by MRayermannMSFT** [comment]
Hi, for this error please consult [this](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C1904#error-self-signed-certificate-in-certificate-chain-and-similar-errors) section in our trouble shooting guide, and then let us know if you still have questions. Thanks.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
