### ISSUE TITLE
Gnome-keyring should be an optional dependency

### ISSUE THREAD

**Issue by marty-friedman** [microsoft/AzureStorageExplorer#2635]
**Describe the solution you'd like**
It would be very nice if gnome-keyring was an optional dependency.
- Firstly, libgnome-keyring is marked as deprecated
- Secondly, the functionality of storing credentials is helpful, but not crucial
- Thirdly, it's odd for all users having kwallet / any other keyring instead

It would already be very helpful (if it is possible) to have at least all keyring calls only at nodejs layer (keytar module, like it's done in skypeforlinux) where they can be adjusted by users pretty simply. For now, even if nodejs code is adjusted to work with kwallet, the application fails to start without libgnome-keyring shared library.

**Comment by MRayermannMSFT** [comment]
Let's update our docs to be clear that gnome-keyring is recommended (though if it is deprecated maybe it shouldn't be?), and we can also make it clear that if you want to use a different credential storing package/library/add-on you can, and list what APIs it needs to work with.

**Comment by craxal** [comment]
Related to #1887 and #2246. I don't think we should change anything until we're sure what is needed for Storage Explorer to work. I think we need to update `keytar` to a version that uses `libsecret`, which I assume is a common interface across multiple Linux systems?

**Comment by MRayermannMSFT** [comment]
We've updated to electron 8, and consequently there have been changes to our linux dependencies. We'll be updating our docs on those before we ship 1.14
