### ISSUE TITLE
Pop up a conflict dialog when clicking 'Cancel' button in clone file dialog

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2636]
**Storage Explorer Version:** 1.12.0
**Build**:[ 20200217.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3478085
)
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04
**Architecture:** ia32/x64
**Regression From:** Previous release(1.12.0)

**Steps to reproduce:**

1. Expand a storage account -> File Shares.
2. Create a new file share -> Upload a file to it.
3. Right click the file -> Click 'Clone with New Name...' -> Click 'Cancel'.
4. Check the result.

**Expect Experience:**
Succeed to cancel.

**Actual Experience:**
Pop up a conflict dialog.
![image](https://user-images.githubusercontent.com/54055206/74640442-853ed880-51aa-11ea-80f3-dd2dea4f4c59.png)
![image](https://user-images.githubusercontent.com/54055206/74640489-95ef4e80-51aa-11ea-8e20-af225034b6f2.png)

**More Info:**
This issue also reproduces in clone directory dialog.

**Comment by JasonYeMSFT** [comment]
Can you share a recording of the repro steps? I cannot reproduce the bug with on build 20200217.1.

**Comment by v-limu** [comment]
Hi @JasonYeMSFT 

This issue still reproduces on build [20200219.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3482323). Please see the recording.

https://web.microsoftstream.com/video/2ab9d8b0-6dbc-4b67-ab59-a9c8fe8f339c

**Comment by v-limu** [comment]
Verified on build [20200226.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3502854). This issue has been fixed. So we close it.
