### ISSUE TITLE
The Restore Files dialog's title is not localized

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2637]
Storage Explorer Version: 1.12.0
**Build**: [20200217.1]((https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3478085
)
**Branch**: master
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04
**Architecture**: ia32/x64
**Language**: Czech/ German/ Spanish/ French/ Hungarian/ Italian/ Japanese/ Korean/ Dutch/ Polish/ Portuguese (Brazil)/ Portuguese (Portugal)/ Russian/ Swedish/ Turkish/ Chinese (Simplified) / Chinese (Traditional)
**Regression From**: Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select **'Svenska'** -> Restart Storage Explorer.
3. Expand a storage account -> File Shares.
4. Create a new file share -> Upload one file to it.
5. Create snapshot for the file share -> View Share Snapshots and open it.
6. Right click the file -> Click 'Restore Snapshot'.
7. Check the title of the popped dialog.

**Expect Experience:**
The Restore Files dialog's title is localized.

**Actual Experience:**
The Restore Files dialog's title is not localized.
![image](https://user-images.githubusercontent.com/54055206/74637499-0dba7a80-51a5-11ea-9e8e-2bc472e720f6.png)

**Comment by v-limu** [comment]
**More Info:**
The Properties dialog is not localized for one **ADLS Gen2 blob and one file/folder** under one file share.
![image](https://user-images.githubusercontent.com/54055206/74920638-73a63c80-5407-11ea-999e-27ff58c33579.png)

**Comment by jinglouMSFT** [comment]
@v-limu Could you open a separate bug on the last issue?  It seems to be a different issue and we should have a different bug for it.  Once you have opened a new bug, please close this issue as the Restore Files dialog title has been translated.  Thanks,

**Comment by v-limu** [comment]
Hi @jinglouMSFT Thanks for your reply!
I opened a new issue for the 'more info'. Bug: [2661](https://github.com/microsoft/AzureStorageExplorer/issues/2661).
Verified on build [20200220.8](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3489167). The Restore Files dialog title is not localized. We will continue to pay attention to this issue.

**Comment by JasonYeMSFT** [comment]
file extension needs to be published for the strings.

**Comment by v-limu** [comment]
Hi @jinglouMSFT Verified on build 20200317.2. The 'Restore Files' title is missed on the dialog.

![image](https://user-images.githubusercontent.com/54055206/76827188-422f5e00-6859-11ea-8cfc-99bc31aa4fe4.png)

**Comment by v-limu** [comment]
Verified on build 2020327.2. This issue has been fixed. So close it.
