### ISSUE TITLE
I am not able to open Azure storage explorer. Loader is loading only.

### ISSUE THREAD

**Issue by edcastsaket** [microsoft/AzureStorageExplorer#2638]
**Storage Explorer Version**:  1.11.1
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:

**Comment by jinglouMSFT** [comment]
What OS are you on?  Are you behind a proxy?  Please take a look at the troubleshooting to see if anything there would help you:  https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C1904

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
