### ISSUE TITLE
Feature suggestion: Offer an automatic Retry All for upload to Azure Blob Store Containers

### ISSUE THREAD

**Issue by shaneh2** [microsoft/AzureStorageExplorer#264]
**Storage Explorer Version**:  1.1.0
**Platform**:  macOS
**Architecture**:  x64
**Regression From**: 

#### Steps to Reproduce: ####
1. Upload a large amount of data to Azure Blob Storage using Azure Storage Explorer, on a not 100% reliable wifi connection. My wifi connection is fast (approx 140 Mbps) and is relatively stable. 

#### Expected Experience: ####

When the connection drops momentarily over the course of (say) a 15 hour upload, Azure Storage Explorer will resume the uploading or Retry All automatically when the connection is resumed.

#### Actual Experience: ####

All of the files which I have not uploaded yet have failed due to network connection error. When I use Azure Storage Explorer to upload 500 files of approximately 1GB each, then after some time I notice that many of the files have failed to upload due to a network connection error. I think it would be good if Azure Storage Explorer would handle this Retry All/Resumption of Uploading automatically, rather than having the user do it, because the upload may be unattended overnight, for example.

Thank-you.

**Comment by MRayermannMSFT** [comment]
@shaneh2 are you still looking for this? Since you've opened your issue, we've made lots of improvements to data transferring, specifically by switching to using AzCopy in the background. AzCopy usually is willing to retry transfers many times before giving up.

**Comment by shaneh2** [comment]
> @shaneh2 are you still looking for this? Since you've opened your issue, we've made lots of improvements to data transferring, specifically by switching to using AzCopy in the background. AzCopy usually is willing to retry transfers many times before giving up.

Thank you for letting me know about this. I haven’t used Azure in the past while (but plan to in the future), though it’s good to know this is fixed.

At first glance, I wonder should it take advantage of the fix in the azcopy bug over unreliable (WiFi) connections I had on my Windows computer https://github.com/Azure/azure-storage-azcopy/issues/191#event-2258196018 .

**Comment by MRayermannMSFT** [comment]
Ok sounds good. I'm going to go ahead and close this. Always feel free to open new issues if you start using Storage Explorer again and run into problems.
