### ISSUE TITLE
Does not display documents in container with large partition key

### ISSUE THREAD

**Issue by pschaeflein** [microsoft/AzureStorageExplorer#2642]
**Storage Explorer Version**: 1.12
**Build Number**: 20200116.10
**Platform/OS**: Windows 10
**Architecture**: ia32

## Bug Description ##
Does not display documents in container with large partition key.

## Steps to Reproduce ##
1. Create a container with a large partition key: https://docs.microsoft.com/en-us/azure/cosmos-db/large-partition-keys
2. Add documents to container using large partition keys.

## Expected Experience ##
Selecting the container in Storage Explorer should display documents.

## Actual Experience ##
No documents are displayed in the container with large partition keys.

## Additional Context ##
The Bot Framework SDK for .Net creates partitions with large partition keys.

**Comment by JustinDao** [comment]
Is there any update on this one? It would be very helpful!

**Comment by southpolesteve** [comment]
Unfortunately, this isn't a scenario we can currently prioritize. https://cosmos.azure.com/ is the best option for interacting with these containers.

**Comment by southpolesteve** [comment]
The Cosmos team recently deprecated our integration with Azure Storage Explorer. [Here is the full deprecation notice from the 1.15.1 Storage Explorer release notes:](https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.15.1)

> The Azure Cosmos DB integration with Storage Explorer has been deprecated. Any existing functionality will not be removed for a minimum of one year from this release. Users should use the Azure Portal, the Azure Portal desktop app, or the standalone Cosmos Explorer instead – all of which contain many new features that aren’t currently supported in Storage Explorer. Additionally, the Azure Cosmos DB team has also open sourced the data explorer project and will be investing in their own desktop tooling at a later date. Please keep an eye on their repository for more information. 

Currently, we are not prioritizing new features or bug fixes for Cosmos in Azure Storage Explorer. If you the issue you are reporting also applies to the Azure Portal or https://cosmos.azure.com, please file an issue in [our open source Cosmos Explorer repo](https://github.com/Azure/cosmos-explorer)
