### ISSUE TITLE
Implement a Move Option

### ISSUE THREAD

**Issue by tjohnson1010** [microsoft/AzureStorageExplorer#2645]
Please add a move or cut and paste option to allow moving a file from one container/folder to another.

Currently to do this a user needs to:
1) Right click file and choose Copy
2) Traverse to new container
3) Right click "something" and choose Paste
4) Traverse back original container
5) Right click file and choose Delete

If the user makes an error in copy and doesn't realize it, they could then delete the file too.  So this would prevent that too.

Cut-n-Paste flow would be:
1) Right click file and choose Cut
2) Traverse to new container
3) Right click "something" and choose Paste

I understand that from a code aspect, you would would need to do Copy and Delete but from a user aspect you can do that all in step #3.

**Comment by MRayermannMSFT** [comment]
@tjohnson1010 thanks for the suggestion. Unfortunately, when we've had features like this in the past we've seen users become confused during the operation, or even after it finished (with and without failures), about what has been moved/deleted. Therefore we've chosen to not provide this type of feature, and instead leave it up to the user to perform the steps manually. That way you can verify everything is where you want it before deleting anything.
