### ISSUE TITLE
Errors on clicking attached blob container

### ISSUE THREAD

**Issue by fhryo-msft** [microsoft/AzureStorageExplorer#2648]
Error: Cannot read property 'version' of undefined

**Comment by jinglouMSFT** [comment]
Can you try to follow the steps outlined in our troubleshooting guide to see if they resolve your issue?  Thanks.  https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C1904#error-occurred-while-adding-new-connection-typeerror-cannot-read-property-version-of-undefined

**Comment by jinglouMSFT** [comment]
Here are few potential causes but I can’t pin point which one that’s causing problems for you:
-	Check the expiration date on the sas token
-	Make the clock of your computer is set correct
-	Make sure the token generated is for the service you are trying to access
-	If you are behind a proxy, make sure you configure the proxy settings

**Comment by jinglouMSFT** [comment]
Attached with wrong Tenant ID.
