### ISSUE TITLE
Search for a resource and then add to quick access, the application bombs out.  

### ISSUE THREAD

**Issue by thedavegray** [microsoft/AzureStorageExplorer#2649]
**Storage Explorer Version**: 1.12.0
**Build Number**: 20200116.10 
**Platform/OS**: Windows 10 
**Architecture**: x64
**Regression From**:  no, this app has been buggy since I started using it

## Bug Description ##
Search for a resource and then add to quick access, the application bombs out.  

## Steps to Reproduce ##
As above 

## Expected Experience ##
I don't expect an MS application to bomb when accessing Azure resources/ 

## Additional Context ##
This app is simply terrible. It works about 10% of the time even though I update it as soon as a new 
release becomes available. I use CloudBerry Explorer mostly as it works, but I have to use your application when working with MS support to look at corrupted blobs.

**Comment by MRayermannMSFT** [comment]
@thedavegray can you give us some more detail as to what you mean by "bombs out"? We're having a hard time reproducing this.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
