### ISSUE TITLE
Feature request: Organize storage accounts by resource group.

### ISSUE THREAD

**Issue by michaeldaw** [microsoft/AzureStorageExplorer#265]
If a subscription has a large number of storage accounts it can be hard to peruse them. I think if they could be organized by Resource Group (within the tree structure), it would be helpful.

**Comment by MRayermannMSFT** [comment]
@craxal in 1.35 please add a setting for organizing resources by Resource Group, and then have the storage accounts producer and the app config producer respect that setting (disks already respects it).
