### ISSUE TITLE
After deleting "folder", the "folder" still persist on Explorer.

### ISSUE THREAD

**Issue by kediwu0331** [microsoft/AzureStorageExplorer#2652]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:

**Comment by jinglouMSFT** [comment]
Can you do a refresh to see if it goes away?

**Comment by kediwu0331** [comment]
Yes I did refresh. But I can still see the virtual folder. And when I tried to delete again. It shows me this error:

{
  "message": "\"failed to perform remove command due to error: nothing found to remove\""
}

Somehow the virtual folder is not removed in the UI....

**Comment by MRayermannMSFT** [comment]
Is this for a ADLS Gen2 Blob container or a normal Blob container?

**Comment by kediwu0331** [comment]
It is a normal blob container. bug template filled: https://github.com/microsoft/AzureStorageExplorer/issues/2665

**Comment by JasonYeMSFT** [comment]
Let's close the issue and track it in #2665.
