### ISSUE TITLE
Access to file after removing the Microsoft Account

### ISSUE THREAD

**Issue by Badrikrish** [microsoft/AzureStorageExplorer#2656]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:

**Comment by MRayermannMSFT** [comment]
@Badrikrish can you give us some more information please?

**Comment by Badrikrish** [comment]
1. Used the Microsoft account to login to the storage explorer.
2. Able to get the files uploaded to the cloud from the storage accounts.
3. Removed the account from the settings.
4. Still able to open the files that are available in the storage account associated with this account.

Let me know if you need more inputs and or screen shots.

**Comment by MRayermannMSFT** [comment]
Can you clarify what type of account you are talking about?
Are you signing in and adding a **user account**?
Are you attaching a **storage account**?

**Comment by Badrikrish** [comment]
Hi Matt,

Find the details inline. Let me know if you have any more questions.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by MRayermannMSFT** [comment]
Ok. Are you continuing to access the data via the explorer on the right hand side? What we see is that if you:

1. Sign in
2. Open a container (or in other words, double click on a container)
3. Sign out

Then the view that was opened in step 2 remain opens. Is that what you are trying to report?

**Comment by Badrikrish** [comment]
Find the below steps to reproduce

1.Open Microsoft Azure Storage Explorer
2.Connect to Azure using the Azure User name and Password
3.Click apply from the account management blade
4.Expand the Storage Explorer tree from the subscription, Expand Blob Containers, Click on the container. Now I can see the uploaded files on the right pane
5.Double click and open the file, it opens up and I can see the content. Close the file.
6.Click on the Account Management icon to the top left vertical pane and click remove (Microsoft Account)
7.The files are still available on the right pane and I am still able to open. Can we disable or remove access when we remove the associated microsoft account when removed?

**Comment by Badrikrish** [comment]
Find the below steps to reproduce

1.Open Microsoft Azure Storage Explorer
2.Connect to Azure using the Azure User name and Password
3.Click apply from the account management blade 
4.Expand the Storage Explorer tree from the subscription, Expand Blob Containers, Click on the container. Now I can see the uploaded files on the right pane
5.Double click and open the file, it opens up and I can see the content. Close the file.
6.Click on the Account Management icon to the top left vertical pane and click remove (Microsoft Account)
7.The files are still available on the right pane and I am still able to open. Can we disable or remove access when we remove the associated microsoft account when removed?

**Comment by MRayermannMSFT** [comment]
Ok, got it. Yes we see this too. We'll look into closing the tabs automatically when you sign out. Also, incase you are also concerned about the downloaded file, we will not look into deleting that for you.

**Comment by MRayermannMSFT** [comment]
Let's also address https://github.com/microsoft/AzureStorageExplorer/issues/426 at the same time. Or at least try to.
