### ISSUE TITLE
Storage Explorer is throwing error for Azure Stack

### ISSUE THREAD

**Issue by HassanAlmanasrah** [microsoft/AzureStorageExplorer#2657]
**Storage Explorer Version**: January 2020 (Version 1.12.0)
**Build Number**: 20200116.10
**Platform/OS**: Windows Server 2016 & Windows 10
**Architecture**: x64
**Regression From**:  No idea

## Bug Description ##
Following this documentation to configure Azure Storage explorer for Azure Stack
https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-storage-connect-se?view=azs-1910#export-and-then-import-the-azure-stack-hub-certificate
and getting this error
![image](https://user-images.githubusercontent.com/54538594/74966159-3d74b700-541f-11ea-945d-848d9bfe7516.png)

## Steps to Reproduce ##
Tried all the steps using SAS URI or connectionstring

## Expected Experience ##
Unable to access any contains, table and queue under it

**Comment by HassanAlmanasrah** [comment]
Issue got resolved as I was missing Azure Stack APIs. thanks

**Comment by jinglouMSFT** [comment]
Glad you had it figured it out.

The screenshot in step 8 of the article referenced above is incorrect.  It should be:

![image](https://user-images.githubusercontent.com/10081483/74967499-f27e8380-53cd-11ea-877b-451f8c4054ef.png)

I'll contact the Azure Stack PM to have that corrected.
