### ISSUE TITLE
Default AAD tenant is not respected in "Attach with Azure AD" dialog box

### ISSUE THREAD

**Issue by fhryo-msft** [microsoft/AzureStorageExplorer#2658]
**Storage Explorer Version**: 1.12.0
**Build Number**: 1.12.0
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  N/A

## Bug Description ##
The default AAD tenant is not taken as default when I use "Attach with Azure AD" to attach storage container.

## Steps to Reproduce ##
1. Use "Attach with Azure AD" to attach storage container.
2. The default AAD tenant for my account is different than the actual default AAD tenant to my account.
3. The wrong AAD tenant is used and i fail to operate on attached container afterwards

## Expected Experience ##
Use the default AAD tenant to my account in the AAD tenant list and make it default to avoid unexpected impact.

## Actual Experience ##
Other AAD tenant is taken as default in AAD list.

## Additional Context ##
You can use Connect-AzureAD to get default AAD tenant ID when the user account. So technically it's feasible to get default AAD tenant ID for a user account and make it default in the "Attach with Azure AD" dialog box.

**Comment by MRayermannMSFT** [comment]
We're going to be getting rid of this dropdown. In a future version we'll simply ping the container endpoint to figure out the correct tenant. We'll ship this feature once that API is supported for blob containers (currently it is only supported by Gen2 containers).
