### ISSUE TITLE
Table

### ISSUE THREAD

**Issue by Dmarch28** [microsoft/AzureStorageExplorer#2659]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
{
  "name": "StorageError",
  "message": "XML specified is not syntactically valid.\nRequestId:128b52b4-675d-43b1-8042-f0a9c9bb47cc\nTime:2020-02-21T02:59:53.7033258Z",
  "stack": "StorageError: XML specified is not syntactically valid.\nRequestId:128b52b4-675d-43b1-8042-f0a9c9bb47cc\nTime:2020-02-21T02:59:53.7033258Z\n    at Function.StorageServiceClient._normalizeError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:1205:23)\n    at Object.StorageServiceClient._processResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:751:50)\n    at Request.processResponseCallback [as _callback] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:319:37)\n    at Request.self.callback (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:185:22)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at Request.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at Request.emit (events.js:182:13)\n    at Request.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1157:10)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at Request.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at Request.emit (events.js:182:13)\n    at IncomingMessage.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1079:12)\n    at Object.onceWrapper (events.js:273:13)",
  "code": "InvalidXmlDocument",
  "linenumber": "1",
  "lineposition": "66",
  "reason": "Element 'DeleteRetentionPolicy' is not recognized.",
  "statusCode": 400,
  "requestId": "128b52b4-675d-43b1-8042-f0a9c9bb47cc"
}

**Comment by MRayermannMSFT** [comment]
@Dmarch28  please tell us more about what are you trying to do. It looks like you're maybe trying to set a delete retention policy? Did something go wrong while doing that? How are you accessing your storage account? Did you attach it? Are you signed in?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
