### ISSUE TITLE
The left borderline of the focused tab is out of bounds from the second tab

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#266]
**Storage Explorer Version**: 1.2.0
**Platform**: Mac
**Architecture**: x64
**Build Number**: 20180604.2
**Commit**: f8373d5a
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Launch Storage Explorer and expand Storage Accounts.
2. Open multiple tabs.
3. Tab to the second tab then check the focused borderline.

#### Expected Experience: ####
The borderline of the focused tab displays well.

#### Actual Experience: ####
The left borderline of the focused tab is out of bounds.
![compare](https://user-images.githubusercontent.com/34729022/41032476-02132446-6973-11e8-9acc-662d7ea9da7d.png)

**Comment by craxal** [comment]
This is not an issue. The blue color clearly shows focus, so we're not violating anything. Default outlines in macOS also look different than they do in Windows (no orange borders).
