### ISSUE TITLE
storageerror

### ISSUE THREAD

**Issue by Dmarch28** [microsoft/AzureStorageExplorer#2660]
{
  "name": "StorageError",
  "message": "XML specified is not syntactically valid.\nRequestId:c8214677-85b4-4581-a8f7-1e26af830f30\nTime:2020-02-21T03:04:34.7300007Z",
  "stack": "StorageError: XML specified is not syntactically valid.\nRequestId:c8214677-85b4-4581-a8f7-1e26af830f30\nTime:2020-02-21T03:04:34.7300007Z\n    at Function.StorageServiceClient._normalizeError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:1205:23)\n    at Object.StorageServiceClient._processResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:751:50)\n    at Request.processResponseCallback [as _callback] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:319:37)\n    at Request.self.callback (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:185:22)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at Request.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at Request.emit (events.js:182:13)\n    at Request.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1157:10)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at Request.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at Request.emit (events.js:182:13)\n    at IncomingMessage.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1079:12)\n    at Object.onceWrapper (events.js:273:13)",
  "code": "InvalidXmlDocument",
  "linenumber": "1",
  "lineposition": "66",
  "reason": "Element 'DeleteRetentionPolicy' is not recognized.",
  "statusCode": 400,
  "requestId": "c8214677-85b4-4581-a8f7-1e26af830f30"
}

**Comment by jinglouMSFT** [comment]
Can you tell us how you ran into this?  Were you doing something with the soft delete? Thanks.

**Comment by jinglouMSFT** [comment]
Dup of #2659

**Comment by Dmarch28** [comment]
Setting up Team video, OBS provides hookup for and Office Business 365 have with Azure benefits for improvement to mixer and twitch. But I use Twitch to run through mixer!

**Comment by Dmarch28** [comment]
I'm still figuring out Streamer through Office!

**Comment by Dmarch28** [comment]
The other is setting up my storage on Azure!
But waiting on Azure for what I have on files, and my account Monetize on Mixer?

**Comment by Dmarch28** [comment]
My name tag for these are through AtomicMass3B9, and my group or team goes through Gothalion and stevenyagel!
I use Dmarch28 because of Discord and my community in it, which is the gaming app Steam!

**Comment by Dmarch28** [comment]
my repository is Dmarch28/khmer

**Comment by jinglouMSFT** [comment]
Can you help me to understand where Storage Explorer fits in this?
