### ISSUE TITLE
There are strings not localized in one ADLS Gen2 blob's Properties dialog 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2661]
**Storage Explorer Version:** 1.12.0
**Build**: [20200220.8](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3489167)
**Branch**: master
**Language**: Czech/ German/ Spanish/ French/ Hungarian/ Italian/ Japanese/ Korean/ Dutch/ Polish/ Portuguese (Brazil)/ Portuguese (Portugal)/ Russian/ Swedish/ Turkish/ Chinese (Simplified) / Chinese (Traditional)
**Platform/OS:** Windows 10/ CentOS Linux release 7.6.1810(Core)
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文(简体)'-> Restart Storage Explorer.
3. Expand one ADLS Gen2 storage account -> Blob Containers.
4. Create a new blob container -> Upload a blob to it -> Right click the blob -> Click 'Properties...'.
5. Check the strings in dialog.

**Expect Experience:**
The strings that need localized are all localized.

**Actual Experience:**
There are strings not localized.
![image](https://user-images.githubusercontent.com/54055206/75019241-82562780-54cb-11ea-85b1-4824cb59897a.png)

**More info:**
This issue also reproduces for **one file/folder's properties dialog** under one file share.
![image](https://user-images.githubusercontent.com/54055206/75019520-fd1f4280-54cb-11ea-9766-c74442adc942.png)

**Comment by MRayermannMSFT** [comment]
Title text: needs to be loc'd
"name": needs to be loc'd
Anything that is a technical team/HTTP header, do not loc.

**Comment by JasonYeMSFT** [comment]
blob extension needs to be published for the strings.

**Comment by v-limu** [comment]
Verified on build [20200317.2](https://devdiv.visualstudio.com/devdiv/_build/results?buildid=3556898). The ADLS Gen2 blob's properties dialog has been fixed. **The one file's properties dialog under one file share still reproduces.**

**Comment by v-limu** [comment]
Verified on build 20200924.2. 
1. The ADLS Gen2 blob's Properties dialog and the file share have been fixed. 
2. For **one ADLS Gen2 folder's Properties dialog** is still reproduces.

**Comment by MRayermannMSFT** [comment]
ADLS Gen2 folder's Properties dialog appears to be loc'd now to the same level as files and containers.
