### ISSUE TITLE
Cannot Load Subscriptions for either of my Azure Accounts

### ISSUE THREAD

**Issue by munkii** [microsoft/AzureStorageExplorer#2663]
**Storage Explorer Version**: 1.9 and then after upgrade to 1.12.0
**Build Number**: 20200116.10
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  I haven't used the application in a long time but I am sure it did work. Tried 1.9 last week, had this issue, tried upgrading to 1.12 but still fails.

## Bug Description ##
I have two Azure accounts to two wholly separate subscriptions. Both work at portal.azure.com. Trying to add them to ASE I get "Subscriptions could not be loaded. Please try reentering credentials..."

 If I choose "more information" link I get the error

> Subscriptions for the follwowing tenants could not be retrieved:
> Tenant Id: f8cdef31-a31e-4b4a-93e4-5f571e91255a, Error: {
>   "name": "Error",
>   "message": "tunneling socket could not be established,

## Steps to Reproduce ##
1. Choose "Add an account"
2. In "MASE - Connect Dialog" choose "Add an Azure Account"
3. Azure environment - Select "Azure"
4. Sign in with the Azure account
5. "Loading subscriptions" spinner....

## Expected Experience ##
Successfully access resource in Azure

## Actual Experience ##
Cannot get the account to register

## Additional Context ##
I have tried this on the same PC, at from my home office where there is no proxy and it fails
I have tried the same accounts on a colleagues Windows 10 box in the Work Office network and it works

**Comment by MRayermannMSFT** [comment]
Can you check your system environment variables for either HTTP_PROXY or HTTPS_PROXY? If there are, please delete them and try again. If there aren't any, let us know. Thanks!

**Comment by munkii** [comment]
Thanks!

I'd assumed no proxy because "I don't have a proxy server" but I do use Fiddler and the proxy was set to ip.ad.dr.ess:**8888** which sounds a lot like Fiddler.
