### ISSUE TITLE
Access to metadata of queue

### ISSUE THREAD

**Issue by ppsa-stephan** [microsoft/AzureStorageExplorer#2664]
**Is your feature request related to a problem? Please describe.**
When debugging issues with my Azure queues, I need to see the metadata.  (Also true for Azure storage tables).

**Describe the solution you'd like**
Should be a way to at least view and ideally edit metadata for Azure Storage.

**Describe alternatives you've considered**
Using the management portal directly, which is only kind of OK and pretty clunky.

**Additional context**
This should be pretty straightforward, and I suspect the only reason it is missing from the storage explorer in the first place is a design oversight.

**Comment by MRayermannMSFT** [comment]
@ppsa-stephen , are you talking about the metadata of the queue?

**Comment by ppsa-stephan** [comment]
@MRayermannMSFT - pardon me for being unclear.  Yes, I am talking about the metadata of the queue (and by extension any other kind of storage element that is handled in the storage explorer).

> @ppsa-stephen , are you talking about the metadata of the queue?

**Comment by MRayermannMSFT** [comment]
This will be included in 1.20:
![image](https://user-images.githubusercontent.com/21112697/116761413-71a51980-a9cc-11eb-903e-3102f1ec882b.png)

PS: yes I know that the top half is taking of way too much room given it only has 3 entries. We have an item on our backlog for that...

**Comment by MRayermannMSFT** [comment]
Merged into main!
