### ISSUE TITLE
Dir prefix got thrown away

### ISSUE THREAD

**Issue by xkszltl** [microsoft/AzureStorageExplorer#2667]
**Storage Explorer Version**: 1.12.0
**Build Number**: 20200116.10
**Platform/OS**: Windows
**Architecture**: ia32
**Regression From**:  N/A

## Bug Description ##

When navigating in Blob container with `Search by prefix (case-sensitive)` box, if the given prefix contains `/`, when double click the target dir, everything before / will disappear.

## Steps to Reproduce ##

1. Go to a blob container A, dir B
2. Search for `C/D/E`
3. E will show up in explorer
4. Double click E

## Expected Experience ##

Go to A/B/C/D/E

## Actual Experience ##

Jump to non-exist dir A/B/E

**Comment by JasonYeMSFT** [comment]
Duplicate of #541
