### ISSUE TITLE
Support the use of a Service Principal to access the storage account

### ISSUE THREAD

**Issue by chriswue** [microsoft/AzureStorageExplorer#2668]
**Is your feature request related to a problem? Please describe.**
I'm essentially after what is mentioned in this comment: https://github.com/microsoft/AzureStorageExplorer/issues/2142#issuecomment-550041538

Use case: We collect data from our machines which are owned by our customers. Occasionally a customer requests access to their raw data. For that purpose we create a separate isolated storage account and copy all the customers data into it. 

For access we create a service principal dedicated to that client that has access to the account, usually with the "Storage Account Data Contributor" role. Works well for programmatic access but having trouble finding a client which a user can use to manually explore the storage account (useful for the developer to get an idea what is there and what it looks like).

Obviously our customers usually don't have Azure accounts themselves.

**Describe the solution you'd like**
An easy way to log in with service principal credentials (tenant id, client id, client secret).

**Describe alternatives you've considered**
* Providing the access key - they get rotated and managing that with external customers is not feasible, it's also not recommended by Microsoft anyway for various reasons (which I agree with)
* SAS - expires, again service burden to manage that with external customers is not feasible
* Finding another GUI client - pretty much all clients I found only do access keys and some also SAS

I spent a lot of time trying to find if this is somehow possible but haven't managed to. So I'm either missing something or it's just not possible at this stage.

**Comment by MRayermannMSFT** [comment]
Is there a reason you don't just give the user direct RBAC access to the Storage Account? Like, as in, let's say your customer is mike@fakecompany.com, give mike@fakecompany.com "Storage Account Data Contributor" role on the Storage Account.

**Comment by MRayermannMSFT** [comment]
Ah, I just re read and saw "Obviously our customers usually don't have Azure accounts themselves."

If they don't have accounts, then is there a reason they can't make one?

**Comment by chriswue** [comment]
Well, technically a lot of things are possible however managing access for external user accounts will make our lives unnecessarily difficult since keeping in touch with the relevant customers and making sure those accounts ar updated and changed when people leave will be difficult. There are generally no processes for this on our customers side so account will become stale and things will break and it just ads friction - in particular for customers who may not see the point of why they should create a Microsoft account to just get at their data.

The current approach with the Service Principal works really well, except for the manual exploration part.

As far as I can see ASE seems to assume the user account to log in with has not only rights on the the data plane but also the management plane. So I'm not sure how big of a deal it is to add provisions for an account that only has data access rights.
Unfortunately ASE has essentially killed off most alternatives by simply being so good (and free).

**Comment by MRayermannMSFT** [comment]
"As far as I can see ASE seems to assume the user account to log in with has not only rights on the the data plane but also the management plane. "

For blob containers/ADLS Gen2 containers we added the ability to attach them without needing management plane permissions. This option is found under the connect dialog (plug icon) -> Attach with Azure AD.

**Comment by chriswue** [comment]
Well, they do have the service principal credentials that work, but the Attach with Azure AD flow doesn't support that as far as I can see.
I'd be happy to take a look but then found #138

**Comment by MRayermannMSFT** [comment]
@chriswue I don't think we're going to add the ability to use Service Principal credentials to Storage Explorer. We've consulted with the platform team, and they agree that Service Principal credentials are for use by things like apps, scripts, services, etc. Not people. We recommend giving your clients/users RBAC permissions via their Microsoft or Azure accounts. You can either give them permissions at the management and data plane, or just at the data plane. If you use the latter then the users can use Attach with Azure AD to reach the containers.

**Comment by jikuja** [comment]
> We recommend giving your clients/users RBAC permissions via their Microsoft or Azure accounts. You can either give them permissions at the management and data plane, or just at the data plane. If you use the latter then the users can use Attach with Azure AD to reach the containers.

This recommendation assumes that stakeholders who need access to storage accounts have user account with the same tenant. That makes working with cross-organizations really hard. Please, re-consider.

-----

@chriswue Late suggestion:

* login other tooling with service principal
* [generate](https://learn.microsoft.com/en-us/azure/storage/common/storage-sas-overview?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&bc=%2Fazure%2Fstorage%2Fblobs%2Fbreadcrumb%2Ftoc.json#user-delegation-sas-1) user-delegation SAS token or URL
* use that SAS token with storage explorer
  * if lucky storage explorer will support command line arguments but I doubt that

Disclaimer: I did not test if service principals can be used to generate user-delegation SAS

**Comment by chriswue** [comment]
> @chriswue I don't think we're going to add the ability to use Service Principal credentials to Storage Explorer. We've consulted with the platform team, and they agree that Service Principal credentials are for use by things like apps, scripts, services, etc. Not people. We recommend giving your clients/users RBAC permissions via their Microsoft or Azure accounts. You can either give them permissions at the management and data plane, or just at the data plane. If you use the latter then the users can use Attach with Azure AD to reach the containers.

Our customers neither have Microsoft nor Azure accounts.

**Comment by chriswue** [comment]
> > We recommend giving your clients/users RBAC permissions via their Microsoft or Azure accounts. You can either give them permissions at the management and data plane, or just at the data plane. If you use the latter then the users can use Attach with Azure AD to reach the containers.
> 
> This recommendation assumes that stakeholders who need access to storage accounts have user account with the same tenant. That makes working with cross-organizations really hard. Please, re-consider.
> 
> @chriswue Late suggestion:
> 
>     * login other tooling with service principal
> 
>     * [generate](https://learn.microsoft.com/en-us/azure/storage/common/storage-sas-overview?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&bc=%2Fazure%2Fstorage%2Fblobs%2Fbreadcrumb%2Ftoc.json#user-delegation-sas-1) user-delegation SAS token or URL
> 
>     * use that SAS token with storage explorer
>       
>       * if lucky storage explorer will support command line arguments but I doubt that
> 
> 
> Disclaimer: I did not test if service principals can be used to generate user-delegation SAS

Service Principals can be used to generate SAS tokens provided they have the relevant RBAC perms assigned. It's possible but a complexity step for some of our users - I'm talking about people who can download CSV files and perform their data analytics  in Excel and Powerpoint (nothing wrong with that if it serves their needs). Having to write some command line possibly installing AzureCLI or some Powershell modules is not really user friendly for this type of user persona.
