### ISSUE TITLE
The keyboard focus doesn't stay on 'Rename' button after canceling the rename operation

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#267]
**Storage Explorer Version**: 1.2.0
**Platform**: All
**Architecture**: x64
**Build Number**: 20180605.1
**Commit**: f8373d5a
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Launch Storage Explorer and expand Storage Accounts.
2. Open one file share.
3. Focus on 'Rename' button on the toolbar using Tab -> Press 'Enter'.
4. Cancel the rename operation then check the current focus. 

#### Expected Experience: ####
The focus stays on 'Rename' button.

#### Actual Experience: ####
The first file/directory is focused.
![focus](https://user-images.githubusercontent.com/34729022/41032240-4b20a484-6972-11e8-8d9d-c5632eb1c715.png)

**Comment by JasonYeMSFT** [comment]
Verified in 1.16.0, the issue no longer reproduce.

**Comment by v-xianya** [comment]
Verified this issue on build rel/1.17.0-20201210.6. Not produce. So close it.
