### ISSUE TITLE
Allow to select all permissions at once on Shared Access Signature dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2673]
**Storage Explorer Version:** 1.12.0
**Build**: [20200227.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3506444)
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Select one non-ADLS Gen2 account then right click it.
2. Click 'Get Shared Access Signature...' -> Check the permissions part on the dialog.

**Expect Experience:** 
Allow to select all permissions at once.

**Actual Experience:**
Can't select all permissions at once.
![image](https://user-images.githubusercontent.com/41351993/75431452-d65b8300-5987-11ea-88ca-0ed47e8e89a1.png)

**More Info:**
1. This issue also reproduces for blob containers.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240526.2. Fixed. So, we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/fbeb40f5-9860-40de-840b-1f20d607219a)
