### ISSUE TITLE
Cannot view or create documents for CosmosDB

### ISSUE THREAD

**Issue by tigerhive** [microsoft/AzureStorageExplorer#2674]
**Storage Explorer Version**: 1.12.0
**Build Number**: 20200116.10
**Platform/OS**: macOS Catalina 10.15.3
**Architecture**: don't know
**Regression From**:  1.11

## Bug Description ##
Existing documents aren't shown.
When creating a new document, this pop-up appears
```
The collection cannot be accessed with this SDK version as it was created with newer SDK version..
Please use a different id for the document.
```

## Expected Experience ##
With the previous version of Explorer I was able to browse CosmosDB documents

## Actual Experience ##
Cannot use Explorer to browse CosmosDB documents

## Additional Context ##
I can see the do documents in the Portal, so I don't think I'm going mad.

**Comment by jinglouMSFT** [comment]
I don't believe anything has changed in CosmosDB support in Storage Explorer between 1.11 and 1.12.  @southpolesteve , can you take a look at this?  Thanks.

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
