### ISSUE TITLE
HP user Get Permission fails with error: ETIMEDOUT 52.239.229.98:443

### ISSUE THREAD

**Issue by johndellMSFT** [microsoft/AzureStorageExplorer#2675]
please contact johndell@microsoft.com via email

**Storage Explorer Version**: 1.12.0
**Build Number**: 
**Platform/OS**: Windows
**Architecture**: x64
**Regression From**:  

User adds resource https://dtsazstackhub.dfs.core.windows.net/azurestack/HPE

User is unable to authenticate

Error from Azure Storage Explorer

Get Permission fails with error:
{
  "message": "\"{\\n  \\\"name\\\": \\\"FetchError\\\",\\n  \\\"message\\\": \\\"request to https://dtsazstackhub.dfs.core.windows.net/azurestack/%2F?action=getAccessControl&upn=true&timeout=60 failed, reason: connect ETIMEDOUT 52.239.229.98:443\\\",\\n  \\\"type\\\": \\\"system\\\",\\n  \\\"errno\\\": \\\"ETIMEDOUT\\\",\\n  \\\"code\\\": \\\"ETIMEDOUT\\\",\\n  \\\"stack\\\": \\\"FetchError: request to https://dtsazstackhub.dfs.core.windows.net/azurestack/%2F?action=getAccessControl&upn=true&timeout=60 failed, reason: connect ETIMEDOUT 52.239.229.98:443\\\\n    at ClientRequest.<anonymous> (C:\\\\\\\\Program Files (x86)\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\node-fetch\\\\\\\\lib\\\\\\\\index.js:1455:11)\\\\n    at ClientRequest.emit (events.js:182:13)\\\\n    at TLSSocket.socketErrorListener (_http_client.js:391:9)\\\\n    at TLSSocket.emit (events.js:182:13)\\\\n    at emitErrorNT (internal/streams/destroy.js:82:8)\\\\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\\\\n    at process._tickCallback (internal/process/next_tick.js:63:19)\\\"\\n}\""
}

Get Properties fails with error:
{
  "name": "FetchError",
  "message": "request to https://dtsazstackhub.blob.core.windows.net/azurestack?restype=container failed, reason: connect ETIMEDOUT 52.239.229.100:443",
  "type": "system",
  "errno": "ETIMEDOUT",
  "code": "ETIMEDOUT",
  "stack": "FetchError: request to https://dtsazstackhub.blob.core.windows.net/azurestack?restype=container failed, reason: connect ETIMEDOUT 52.239.229.100:443\n    at ClientRequest.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1455:11)\n    at ClientRequest.emit (events.js:182:13)\n    at TLSSocket.socketErrorListener (_http_client.js:391:9)\n    at TLSSocket.emit (events.js:182:13)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"
}

**Comment by MRayermannMSFT** [comment]
Issue mitigated over email.
