### ISSUE TITLE
unable to get local issuer certificate

### ISSUE THREAD

**Issue by Himanshu55007** [microsoft/AzureStorageExplorer#2677]
Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: cd320bb9-95e6-46f4-ae5a-8b40306aed31, Error: {
  "name": "Error",
  "message": "unable to get local issuer certificate",
  "stack": "Error: unable to get local issuer certificate\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at TLSSocket.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at TLSSocket.emit (events.js:182:13)\n    at TLSSocket._finishInit (_tls_wrap.js:631:8)",
  "code": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"
}

**Comment by jinglouMSFT** [comment]
@Himanshu55007 Can you try to follow the troubleshooting guide here to see if it helps resolve the issue?  https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C1904#error-self-signed-certificate-in-certificate-chain-and-similar-errors

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
