### ISSUE TITLE
New string 'Learn more about permissions' is not localized on Shared Access Signature dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2678]
**Storage Explorer Version:** 1.12.0
**Build**: [20200228.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3510155)
**Branch**: master
**Language**: Czech/ German/ Spanish/ French/ Hungarian/ Italian/ Japanese/ Korean/ Dutch/ Polish/ Portuguese (Brazil)/ Portuguese (Portugal)/ Russian/ Swedish/ Turkish/ Chinese (Simplified) / Chinese (Traditional)
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '**中文（简体）**' -> Restart Storage Explorer.
3. Select one non-ADLS Gen2 account then right click it -> Select 'Get Shared Access Signature...'.
4. Check whether the link 'Learn more about permissions' on the dialog is localized or not.

**Expect Experience:**
The link 'Learn more about permissions' is localized.

**Actual Experience:**
The link 'Learn more about permissions' is not localized.
![image](https://user-images.githubusercontent.com/41351993/75524471-ef783880-5a48-11ea-9c66-f298e9d98e83.png)

**More Info:**
1. This issue also reproduces for services.

**Comment by lukaschal** [comment]
New string from 2/27/2020.

File: loc\en\src\Standalone\resources\GenerateSasDialog.json
ID: 0; "LabelLearnMoreSASPermissions"
SRC: Learn more about permissions

**Comment by v-xianya** [comment]
Verified on build [20200305.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3526923).
Fixed.
