### ISSUE TITLE
page anomalous close

### ISSUE THREAD

**Issue by Rocky-Liang** [microsoft/AzureStorageExplorer#2681]
Click the login page to flash back.
2020-03-02 15_52_56-Microsoft Azure Storage Explorer
![image](https://user-images.githubusercontent.com/56328415/75657244-b20de800-5ca0-11ea-88e7-154a10bc18a3.png)

the page will close.

**Comment by Rocky-Liang** [comment]
next show:
![image](https://user-images.githubusercontent.com/56328415/75658154-b2a77e00-5ca2-11ea-862f-a379c2fce566.png)

**Comment by MRayermannMSFT** [comment]
@Rocky-Liang are you behind a proxy? If so, please meake sure you have proxy settings enabled: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C1804#proxy-issues

**Comment by Rocky-Liang** [comment]
@MRayermannMSFT Thanks,I will try to check this issues.
