### ISSUE TITLE
Add NO_PROXY setting

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#2685]
Request from Azure ProDirect Japan:

The customer would like to be able to configure the proxy settings in Storage Explorer to have exceptions for certain FQDNs (traffic to those FQDNs would not go through the proxy). They noted that they can do this in AzCopy with HTTPS_PROXY and NO_PROXY settings, but it doesn’t appear to be possible in Azure Storage Explorer.

- [X] Factor out common proxy retrieval and set functionality.
- [X] Update v12 clients so that they apply proxy changes (but only if the hostname doesn't match `NO_PROXY`).
- [x] Refactor extensions to listen for proxy changes and use common proxy utility functions.
- [x] Refactor providers defined in Standalone to listen for proxy changes and use common  proxy utility functions.
- [x] Update proxy configuration manager to support `NO_PROXY` functionality.
- [x] Make sure v2 clients unset the proxy if hostname matches `NO_PROXY` patterns (`request` does not detect changes in `NO_PROXY`).

**Comment by marcindabrowski** [comment]
Please consider also the possibility of setting different proxies for at least account levels or subscription level.
I'm working with different clients and they have different proxies. I do not want to restart Explorer every time I want to look to another Storage that I'm looking at now.

**Comment by craigjar** [comment]
With private link service end points on Storage now, you may have a mix of storage accounts that go through proxy for public, or do not go through proxy for private.  When using the AZ CLI "az storage blob" commands, they obey the no_proxy environment variable where you can put your private link enabled storage URLs, however Storage Explorer does not.  This forces you to turn proxy on or off and restart the app depending on which storage you want to connect to.

**Comment by craxal** [comment]
Delaying to 1.21.0. Adding support for NO_PROXY touches many different code locations, and we need more time for thorough testing.
