### ISSUE TITLE
No content shows in delete one file share dialog

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2686]
**Storage Explorer Version:** 1.12.0
**Build**: [20200303.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3519365)
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Regression From:** Previous release(1.12.0)

**Steps to reproduce:**

1. Expand one storage account -> File Shares.
2. Create a new file share -> Delete it.
3. Check the popped dialog.

**Expect Experience:**
The content shows well.
![image](https://user-images.githubusercontent.com/54055206/75762491-bf48d680-5d75-11ea-936a-190cb9552932.png)

**Actual Experience**:
No content shows.
![image](https://user-images.githubusercontent.com/54055206/75760235-ea312b80-5d71-11ea-861b-f1d1e8cb3dc6.png)

**More Info:**
This issue also reproduces for **one queue/table**.

**Comment by JasonYeMSFT** [comment]
These strings are recently added. Their packages are published and this should not reproduce now.

**Comment by MRayermannMSFT** [comment]
Fixed.
