### ISSUE TITLE
The icon for undelete action log is not exact when the action is skipped

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2687]
**Storage Explorer Version:** 1.12.0
**Build**: [20200303.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3519365)
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Select one non-ADLS Gen2 storage account -> Blob Containers (Make sure soft delete is enabled).
2. Expand Blob Containers -> Select one blob container -> Upload one blob.
3. Detete the uploaded blob -> Switch to 'Active and deleted blobs' view.
4. Select the deleted blob and right click it -> Slelect Undelete -> (Undelete by Date...).
5. Click 'Undelete' button -> Check the icon for the activity log.

**Expect Experience:**
The icon is exact. As below:
 ![image](https://user-images.githubusercontent.com/41351993/75765415-721b3380-5d7a-11ea-9a06-6832b72c719a.png)

**Actual Experience**:
The icon is not exact. 
![image](https://user-images.githubusercontent.com/41351993/75765444-7e9f8c00-5d7a-11ea-8a76-94f879f0f05f.png)

**Comment by v-xianya** [comment]
Hi @JasonYeMSFT   
Sorry for not making the expect much clear.
I thought the icon of the summary log also need to update. So we choose to re-open this issue.
![image](https://user-images.githubusercontent.com/41351993/75874566-d6fc7b00-5dc6-11ea-9185-31ed51780abc.png)

**Comment by JasonYeMSFT** [comment]
Please verify the icons.

**Comment by v-limu** [comment]
Verified on build 20200311.2. This issue has been fixed. So we close it.
![image](https://user-images.githubusercontent.com/54055206/76374430-2706af00-637e-11ea-8d6b-7408cec44e4c.png)
