### ISSUE TITLE
No update notification pops up after opening Storage Explorer via ‘.\StorageExplorer.exe --add-update-group=CTI’ 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2688]
**Storage Explorer Version:** 1.12.0
**Build**: [20200303.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3519365)
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Regression From:** Previous release(1.11.2)

**Steps to reproduce:**
1. Close Storage Explorer if already open.
2. Open PowerShell -> Use cd to navigate to where the Storage Explorer executable is located.
3. Run ".\StorageExplorer.exe --add-update-group=CTI" to open Storage Explorer.
4. Check whether there pops up update notification or not.

**Expect Experience:**
Pops up the update notification. like:
![image](https://user-images.githubusercontent.com/41351993/75772168-62a1e780-5d86-11ea-866a-7a3744621ee3.png)

**Actual Experience**:
No update notification pops up.

**Comment by MRayermannMSFT** [comment]
Fixed.
