### ISSUE TITLE
It's better to append 'Force Undelete' to each skipped undelete activity log

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2689]
**Storage Explorer Version:** 1.12.0
**Build**: [20200228.6](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3513083)
**Branch**: dev/chuye/beta-blob-extension
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Select one non-ADLS Gen2 storage account -> Blob Containers (Make sure soft delete is enabled).
2. Expand Blob Containers -> Select one blob container that contains more than one blob.
3. Delete the blob container -> Switch to 'Active and deleted blobs' view.
4. Select the deleted blob container and right click it -> Select Undelete -> (Undelete by Date...).
5. Click 'Undelete' button -> Expand the activity log.
6. Check whether there shows 'Force Undelete' to each skipped undelete activity log.

**Expect Experience:**
Show 'Force Undelete' to each skipped undelete activity log.
![image](https://user-images.githubusercontent.com/41351993/75775172-5c166e80-5d8c-11ea-9291-50779091d1b7.png)

**Actual Experience:**
It doesn't show 'Force Undelete' to each skipped undelete activity log.
![image](https://user-images.githubusercontent.com/41351993/75768635-ab09d700-5d7f-11ea-8543-e80f7ea4d7c8.png)

**Comment by JasonYeMSFT** [comment]
I intentionally put it on the group activity since the children activity are supposed to be used as information only elements.
