### ISSUE TITLE
Display a duplicate account when sign-in with 'MSAL' enabled

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2690]
**Storage Explorer Version:** 1.12.0
**Build**: [20200304.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3522896)
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/macOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Previous release (1.12.0)

**Steps to reproduce:**
1. Open Storage Explorer (Make sure the MSAL setting is enabled)
2. Remove the exist account.
3. Sign in with an account -> Check the result in ACCOUNT MANAGMENT panel.

**Expect Experience:**
The account displays well.

**Actual Experience**:
Display a duplicate account.
![image](https://user-images.githubusercontent.com/41351993/75873096-360cc080-5dc4-11ea-9e76-504b9cfa4b37.png)

**Comment by MRayermannMSFT** [comment]
@v-xianya the next time this repro's please email me the following file: "C:\Users\<your username>\AppData\Local\.IdentityService\StorageExplorerV2AccountStore.json"

Do not post that file here. Email it to me!

**Comment by v-xianya** [comment]
OK. got it!

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
