### ISSUE TITLE
There are strings not localized in Retry AzCopy dialog

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2691]
**Storage Explorer Version:** 1.12.0
**Build**: [20200304.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3522896
)
**Branch**: master
**Language**:  Czech/ German/ Spanish/ French/ Hungarian/ Italian/ Japanese/ Korean/ Dutch/ Polish/ Portuguese (Brazil)/ Portuguese (Portugal)/ Russian/ Swedish/ Turkish/ Chinese (Simplified) / Chinese (Traditional)
**Platform/OS**: Windows 10/  Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer -> Open 'Settings' -> Application (Regional Settings) -> Select '**中文(简体)**' -> Restart Storage Explorer.
2. Expand a storage account -> Blob Containers.
3. Create a new blob container -> Upload one file.
4. Upload the same file -> Select 'Do not upload' -> Apply.
5. Click 'Retry...' in Activities panel.
6. Check the strings in the popped dialog.

**Expect Experience:**
All strings are localized.

**Actual Experience:**
There are strings not localized.
![image](https://user-images.githubusercontent.com/54055206/75876632-035cd980-5e51-11ea-94a4-4e462b9fb276.png)

**More Info:**

1. This issue also reproduces for one file share.
2. This issue also reproduces when **trying to delete blobs with snapshots.**

![image](https://user-images.githubusercontent.com/54055206/75877085-da891400-5e51-11ea-9475-44d49479c0a5.png)

**Comment by MRayermannMSFT** [comment]
Fairly new strings. They are not hardcoded. Just awaiting localization.

**Comment by lukaschal** [comment]
On translation now.

**Comment by v-xianya** [comment]
Verified this issue on build [20200319.10](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3566615).
The word  'Overwrite' is not localized in all languages.
![image](https://user-images.githubusercontent.com/41351993/77140140-9fbee700-6ab3-11ea-9da0-203d31b15426.png)
The word 'Snapshot' is not localized in Italian.
![image](https://user-images.githubusercontent.com/41351993/77141737-dd723e80-6ab8-11ea-9c53-afef3093ec23.png)

**Comment by lukaschal** [comment]
Localized at 3/19/2020.

0; "OverwriteLabel"

**Comment by v-xianya** [comment]
Verified this issue on build 20200327.2. Fixed.
