### ISSUE TITLE
Error uploading a 9.6Gb file to blob storage via AZ Storage Explorer

### ISSUE THREAD

**Issue by xbbnq7k** [microsoft/AzureStorageExplorer#2692]
{
  "name": "Error",
  "message": "write EPIPE",
  "stack": "Error: write EPIPE\n    at _errnoException (util.js:1024:11)\n    at WriteWrap.afterWrite [as oncomplete] (net.js:867:14)",
  "code": "EPIPE",
  "errno": "EPIPE",
  "syscall": "write"
}

**Comment by jinglouMSFT** [comment]
@xbbnq7k Can you tell us a bit more info?
- Which version of Storage Explorer? On which platform?
- Are you behind a proxy? 
- Do you have problems uploading any other files?I 
- I assume this was to upload to a regular Blob container instead of ADLS Gen2?
Thanks.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
