### ISSUE TITLE
Fail to manage snapshots for one blob

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2696]
**Storage Explorer Version:** 1.12.0
**Build**: [20200305.6](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3529152)
**Branch**: dev/chuye/beta-blob-extension
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Regression From:** Previous release(1.12.0) 

**Steps to reproduce:**
1. Expand one Non-ADLS Gen2 storage account -> Blob Containers .
2. Create one blob container -> Upload one blob to it.
3. Select the uploaded blob then right click it -> Select 'Manage Snapshots'.
4. Check the result.

**Expect Experience:**
No error occurs and switch to snapshots view.

**Actual Experience:**
An error notification pops up.
![image](https://user-images.githubusercontent.com/41351993/76069773-5740fd00-5fce-11ea-83cb-b80d5c05480f.png)

![image](https://user-images.githubusercontent.com/41351993/76069794-5e680b00-5fce-11ea-8cc5-d4176bdbb806.png)

**More Info:**
1. This issue doesn't reproduce for one blob under one SAS attached account.
2. This issue doesn't reproduce for one blob under one SAS attached blob container.
3. This issue reproduces for one blob under one Name & Key attached account.
4. This issue reproduces for blobs under Emulator node.

**Comment by JasonYeMSFT** [comment]
There is some SDK request construction issue when listing blob snapshots. I will communicate with them for a work around for this.

**Comment by v-xianya** [comment]
@JasonYeMSFT 
This issue has been fixed on build feature/ [20200313.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3548286). So we close it.
