### ISSUE TITLE
Pressing `Del` key in a query text field prompts to "delete selected entities"

### ISSUE THREAD

**Issue by cparker4486** [microsoft/AzureStorageExplorer#2698]
**Storage Explorer Version**: 1.12.0
**Build Number**: 20200116.10
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  I'm am pretty sure this used to work properly but I couldn't state when it started to behave the way it does now.

## Bug Description ##
When I try to delete a character from a text field in the Query pane, I am prompted with a warning that says "Are you sure you want to deleted the selected entities? Yes/No".

## Steps to Reproduce ##
1. Make sure you're working with a table with some records in it
2. Open the Query pane
3. Type something into a text box (as if intending to filter the list)
4. Try to delete a character with the `Del` key
5. See prompt about deleting the selected entities

## Expected Experience ##
I expect the `Del` key to work normally and not erroneously trigger a delete operation on selected entities.

## Actual Experience ##
![image](https://user-images.githubusercontent.com/1189638/76113224-97858880-5f98-11ea-9d3d-3fb0dca3fc38.png)

## Additional Context ##
I don't believe there is anything unique or non-standard about what I'm doing but I can also point out that pressing `Backspace` works normally.

**Comment by JasonYeMSFT** [comment]
We are already aware of this bug #2631. We are working on a fix for 1.13.0.
