### ISSUE TITLE
It takes some time to pop up the error dialog when deleting one leased ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2700]
**Storage Explorer Version:** 1.12.0
**Build**: [20200309.6](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3537547)
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Select one blob container -> Acquire lease for it.
3. Try to delete the leased blob container.
4. Observe the result.

**Expect Experience:**
Pop up an error dialog quickly.

**Actual Experience:**
It takes some time to pop up an error dialog.

**More Info:**
This issue doesn't reproduce for one regular blob container.

**Comment by craxal** [comment]
@v-xianya Some API calls for ADLS Gen2 are expected to take a little longer, because they have to go through blob APIs. Can you be more specific and tell us how long this is taking and how long blobs take?

**Comment by v-xianya** [comment]
@craxal 
It takes about **20 seconds** for one ADLS Gen2 blob container.
For one regular blob container, the dialog pops up immediately. (No more than 1 second.)

**Comment by craxal** [comment]
@x-xianya We can investigate this further to check whether the API call is the cause for the long wait. If so, would adding an activity log item be helpful?

**Comment by v-xianya** [comment]
@craxal 
If there no way to reduce the time. Add an activty log to remind is helpful.
