### ISSUE TITLE
The release notes content is incorrect when clicking 'View Release Notes' on update notification

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2701]
**Storage Explorer Version:** 1.12.0
**Build**: [20200309.6](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3537547)
**Branch**: master
**Platform/OS:** Windows 10/Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Regression From:** Previous release (1.11.2)

**Steps to reproduce:**
1. Close Storage Explorer if already open.
2. Open PowerShell -> Use cd to navigate to where the Storage Explorer executable is located.
3. Run ".\StorageExplorer.exe --add-update-group=CTI" to open Storage Explorer.
4. Click 'View Release Notes' on update notification -> Check the release notes.

**Expect Experience:**
The release notes content is correct.

**Actual Experience:**
The release notes content is  incorrect. 
![image](https://user-images.githubusercontent.com/41351993/76292847-edd12f00-62ea-11ea-9e7c-28691a5c9b20.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into master

**Comment by v-xianya** [comment]
@MRayermannMSFT 
Hi Matthew,
Verified this issue on build master/[20200319.10](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3566615). The Release Notes shows like below. Could you help to recheck this, please!
![image](https://user-images.githubusercontent.com/41351993/77139454-0db5df00-6ab1-11ea-899d-7b197e50902c.png)

**Comment by MRayermannMSFT** [comment]
The test release notes now just show 1.13. I'll update all the string to make it clear everything is just test strings.
