### ISSUE TITLE
Operations on Azure Data Lake Storage Gen2 don't work (Auth failure)

### ISSUE THREAD

**Issue by Saul-R** [microsoft/AzureStorageExplorer#2704]
**Storage Explorer Version**: 
Microsoft Azure Storage Explorer
Version: 1.12.0
AzCopy Version: 10.3.3

**Build Number**: 
Build Number: 20200116.10
**Platform/OS**: 
Linux Ubuntu 18.04.3 LTS
**Architecture**: 
 x64

## Bug Description ##

Azcopy commands issued from the storage explorer do not work on Azure Data Lake Storage Gen2 storage acocunts. Instead I'm getting an authentication error:
```
{
  "message": "\"failed to perform remove command due to error: cannot start job due to error: cannot verify resource due to error: -> github.com/Azure/azure-storage-azcopy/azbfs.newStorageError, /home/vsts/work/1/s/azbfs/zc_storage_error.go:41\\n===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====\\nDescription=403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature., Details: (none)\\n   HEAD https://ngmldevhdiacct.dfs.core.windows.net/hdinsight/data/week_purchases.pq/transaction_week=2018-04-30failed?timeout=901\\n   Authorization: REDACTED\\n   User-Agent: [Microsoft Azure Storage Explorer, 1.12.0, linux,  AzCopy/10.3.3 Azure-Storage/0.1 (go1.13; linux)]\\n   X-Ms-Client-Request-Id: [b2c6d096-69b0-4617-7e0c-97a2565345eb]\\n   X-Ms-Date: [Tue, 10 Mar 2020 14:30:56 GMT]\\n   X-Ms-Version: [2018-11-09]\\n   --------------------------------------------------------------------------------\\n   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\\n   Date: [Tue, 10 Mar 2020 14:30:56 GMT]\\n   Server: [Windows-Azure-HDFS/1.0 Microsoft-HTTPAPI/2.0]\\n   X-Ms-Error-Code: [AuthenticationFailed]\\n   X-Ms-Request-Id: [d1721189-f01f-0072-6be8-f69a79000000]\\n   X-Ms-Version: [2018-11-09]\\n\\n\\n.\\n\""
}
```

## Steps to Reproduce ##

- Copy from a ADLS gen2 to another from the explorer (ctrl+C / Ctrl+V)
- Try deleting a file on an ADLS gen2

## Expected Experience ##

The operation works, files copied or deleted.

## Actual Experience ##

Error saying "Deletion from xxxxx failed 0 completed"

## Additional Context ##

I worked around the problem using manually generated SAS token and the `azcopy` command from the Azure storage

Similar to #1076, not sure why that one is closed.

**Comment by JasonYeMSFT** [comment]
Are you signed in or attaching with Azure AD? Does this consistently happen on every blob that you try to delete?

**Comment by Saul-R** [comment]
I'm signed in 
![image](https://user-images.githubusercontent.com/10700583/76393890-c1fa8b80-6374-11ea-98c2-9c994a47f7af.png)

It's only happening for Azure data lake storage gen2 
It's quite inconsistent, I'm not getting that error now.

**Comment by JohnRusk** [comment]
Hi @Saul-R.  John from the AzCopy team here.  It could be very helpful to see the AzCopy log files from the failed operations.  Be default they are found here $HOME$\.azcopy

If you're not sure which ones are from the failed operations, you could probably find them with a grep search for AuthenticationFailed.

Log files contain filenames but no credentials.  You can email the log files directly to me. My email address is on my profile page.

**Comment by Saul-R** [comment]
Seems like the SAS token wasn't correctly generated for this request.

```
2020/03/10 13:58:55 failed to initialize destination container hdinsight; the transfer will continue (but be wary it may fail): -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg
/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====
Description=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:fc2df15c-e01e-0041-6de4-f6c5d2000000
Time:2020-03-10T13:58:53.5423064Z, Details: 
   AuthenticationErrorDetail: Signature did not match. String to sign used was rwl

2020-04-09T13:56:51Z
/blob/ngmldevhdiacct/hdinsight



2018-03-28





   Code: AuthenticationFailed
   PUT https://ngmldevhdiacct.blob.core.windows.net/hdinsight?restype=container&se=2020-04-09t13%3A56%3A51z&sig=-REDACTED-&sp=rwl&sr=c&sv=2018-03-28&timeout=901
   User-Agent: [AzCopy/10.3.4 Azure-Storage/0.7 (go1.13; linux)]
   X-Ms-Client-Request-Id: [fed57de7-aa9c-4b62-58ac-602ce923e65d]
   X-Ms-Version: [2018-03-28]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
   Content-Length: [499]
   Content-Type: [application/xml]
   Date: [Tue, 10 Mar 2020 13:58:53 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthenticationFailed]
   X-Ms-Request-Id: [fc2df15c-e01e-0041-6de4-f6c5d2000000]

```

Can't reproduce this anymore.

**Comment by MRayermannMSFT** [comment]
Welp, I guess we'll close this then...

Please open a new issue if you still encounter problems.
