### ISSUE TITLE
Does Storage Explorer have fixed timeout (901 seconds) to upload a blob?

### ISSUE THREAD

**Issue by Networkdog** [microsoft/AzureStorageExplorer#2705]
Recently noticed some upload failures caused by SASClientTimeoutError and found all requests for upload have timeout=901 argument at the end of REST API URL like belows:

https://xxx.blob.core.windows.net/xxxx?se=2020-04-01T08:42:15Z&sig=XXXXX&sp=rwl&sr=c&sv=2018-03-28&timeout=901

Is there any switch to increase the timeout in Storage Explorer? Or any way to chunked upload a large file might take longer time than 901 seconds in Storage Explorer?

[Version Info]
Storage Explorer: 1.12.0
AzCopy: 10.3.3

**Comment by jinglouMSFT** [comment]
Is this for regular blobs or ADLS Gen2 blobs?
Our default SAS tokens generated for AzCopy transfer is 30 days which is fairly long. You can also change it here:

![image](https://user-images.githubusercontent.com/10081483/76372293-288e9380-62fa-11ea-8e04-dd589d708090.png)

**Comment by Networkdog** [comment]
Thank you for your reply. It was regular blobs. We are unable to complete any upload which would take longer than 901 seconds. 

![image](https://user-images.githubusercontent.com/35480494/76373982-3806ee80-6385-11ea-9608-705902f26176.png)

**Comment by Networkdog** [comment]
I think that there is a magic number 901 somewhere in Storage Explorer or AzCopy. I would like to know if Storage Explorer has an option to adjust the timeout.

**Comment by JasonYeMSFT** [comment]
@Networkdog, are you using SAS attached storage account/blob containers? We don't add timeout parameter in our generated SAS and neither does AzCopy. It is possible that when you attach with SAS, there are additional parameters in the SAS url such that it is picked up by AzCopy while doing the transfer.

**Comment by JasonYeMSFT** [comment]
Wait, I do see AzCopy append the parameter before sending the actual request. I will follow up with them to see if it is configurable.

**Comment by JasonYeMSFT** [comment]
@Networkdog I just get some answers from the AzCopy team. It is currently a hardcoded value that is not configurable. Given that 900 sec (15min) is a considerably long time, it might be caused by uploading too many chunks in parallel with a small bandwidth, making each one slow. A suggested work around is to set the concurrency value to "AUTO" (or some value small enough) so that each chunk can finish within 15 minutes.

You can find the concurrency value setting under "Settings -> Transfers -> AzCopy -> Network Concurrency" in Storage Explorer.

**Comment by Networkdog** [comment]
@JasonYeMSFT Thank you so much for your answer! Understood. I tried to investigate some cases where OperationTimeout was, these don't seem chunked uploads as belows:

https://flib.blob.core.windows.net/flib/xxxx/xxxx.mp3?se=2020-04-01T08:42:15Z&sig=XXXXX&sp=rwl&sr=c&sv=2018-03-28&timeout=901

https://flib.blob.core.windows.net/flib/xxxx/xxxx.MP3?se=2020-04-01T08:42:15Z&sig=XXXXX&sp=rwl&sr=c&sv=2018-03-28&timeout=901

My understanding was that chunked upload has a blockid parameter, wasn't it?

https://xxxxx.blob.core.windows.net/large/A.DAT?**blockid=yjy2nzdmy2qtzdqzms0yndqyltywmgetodixnmzhmda1zdey&comp=block**&se=2020-03-12t08%3A38%3A44z&sig=-REDACTED-&sp=rwdlacup&spr=https&srt=sco&ss=bfqt&st=2020-03-12t00%3A38%3A44z&sv=2019-02-02&timeout=901

**Comment by JasonYeMSFT** [comment]
AzCopy internally processes each upload block-wise. If you look at its log, each blob is transferred by multiple put requests with block id. 

Example log file: 
[1740b7ca-c9a9-3841-5656-f09da3a94d2e.log](https://github.com/microsoft/AzureStorageExplorer/files/4328101/1740b7ca-c9a9-3841-5656-f09da3a94d2e.log)

**Comment by JasonYeMSFT** [comment]
@Networkdog Does the concurrency value setting work around the issue for you?

**Comment by Networkdog** [comment]
Yes, exactly. The main cause of the problem appears to be number of CPU core on problematic PC. Found Network Concurrency was automatically set as 300 based on number of CPUs, so even uploading 8MB chunks took minutes sometimes due to heavy concurrency. 

......
2020/03/07 07:27:40 **Number of CPUs: 64**
2020/03/07 07:27:40 Max file buffer RAM 16.000 GB
2020/03/07 07:27:40 **Max concurrent network operations: 300 (Based on number of CPUs. Set AZCOPY_CONCURRENCY_VALUE environment variable to override)**
2020/03/07 07:27:40 Check CPU usage when dynamically tuning concurrency: true (Based on hard-coded default. Set AZCOPY_TUNE_TO_CPU environment variable to true or false override)
......

OpTime had been fluctuated a lot as belows even uploading 8MB chunk:

......
2020/03/07 07:30:09 ==> REQUEST/RESPONSE (Try=1/99.0057ms, **OpTime=34.407968s**) -- RESPONSE SUCCESSFULLY RECEIVED
   Content-Length: [8388608]
......
2020/03/07 07:57:11 ==> REQUEST/RESPONSE (Try=1/1.0001ms, **OpTime=2m49.5156958s**) -- REQUEST ERROR
   Content-Length: [8388608]
......

As you mentioned, overriding Network Concurrency into a lower value really worked. Thank you Jason so much for your help. Some PCs have a lot of CPU core like Ryzen Threadripper might have same issue with me, I think some adjustments in calculation default network concurrency are needed.
