### ISSUE TITLE
The AzureStorageExplorer call too many MessageBox to remind me to update the .NET FrameWork when I start it.

### ISSUE THREAD

**Issue by Peter-Zheng-Sp** [microsoft/AzureStorageExplorer#2708]
**Storage Explorer Version**: 1.12.0
**Build Number**: 20200116.10
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**: None

## Bug Description ##
When I first start the Azure-Storage-Explorer, the app will seems to check my .NET vesion. Unfortunately, my .NET version is lower than v4.7.2, and then!! The app calls lots of!!!!!!! MessageBox to remind me and let me to update to the new version of .NET Framework, my computer almost got stuck!!!!!!!!!!

## Steps to Reproduce ##
1. Install this version of software [Azure Storage Explorer];
2. Install .NET FrameWork lower than v4.7.2 version;
3. Start the Azure Storage Explorer.

## Expected Experience ##
1. You will start the software successfully and call a MessageBox to remind you to update .NET FrameWork.

## Actual Experience ##
1. When you start the software, it will call too many MessageBox to remind you to update the .NET FrameWork.
![image](https://user-images.githubusercontent.com/52812551/76397954-fee77200-63b6-11ea-9865-f477d3a3c841.png)

## Additional Context ##
None

**Comment by MRayermannMSFT** [comment]
Oh my. That is quite the screenshot. I feel like I'm back in [the Windows XP days](https://i.stack.imgur.com/4Jh7t.jpg).

We'll look into this.

**Comment by jinglouMSFT** [comment]
This mostly looks like either an OS issue or the library we use for authentication.

**Comment by MRayermannMSFT** [comment]
@Peter-Zheng-Sp unfortunately it looks like one of the libraries we use updated to require .NET Framework 4.7.2. We'll need to update our docs accordingly. As for the crazy amount of windows that pop up, those are definitely coming from the OS.

So summary, you'll either need to get Framework 4.7.2 on your machine or you can't use Storage Explorer.
