### ISSUE TITLE
Clicking to sort boolean column hangs if some rows have nulls

### ISSUE THREAD

**Issue by ghabre** [microsoft/AzureStorageExplorer#271]
**Storage Explorer Version**: 1.1.0
**Platform**: Windows
**Architecture**: ia32

#### Steps to Reproduce: ####
1. Fill an Azure Table with data having a boolean column
2. Leave the boolean null for some rows
3. Click column header

#### Expected Experience: ####
Rows get sorted by the boolean values

#### Actual Experience: ####
Loader hangs. Clicking refresh can get the table back and take the loader away

**Comment by tareksharbak** [comment]
I have the same problem even if there are no null values in the Boolean field. I simply can't sort on any Boolean field; it will just hang and load forever

**Comment by MRayermannMSFT** [comment]
@v-xianya , can you see if this still reproduces?

**Comment by v-xianya** [comment]
Hi, @MRayermannMSFT 
Verified on build 20200418.1. Reproduce.
![image](https://user-images.githubusercontent.com/41351993/79819221-1b19fe00-83bc-11ea-8055-087bf4c744ea.png)

**Comment by MRayermannMSFT** [comment]
Investigate root cause in 1.16
