### ISSUE TITLE
Feature request: pin a subdirectory of a blob container to quick access

### ISSUE THREAD

**Issue by OneMoreSecond** [microsoft/AzureStorageExplorer#2710]
**Is your feature request related to a problem? Please describe.**
My team members share a blob container with a subdirectory for each one.
I hope I can pin my working folder to quick access.
Also I will focus on different folders in different projects. The feature will be useful in this scenario.

**Describe the solution you'd like**
store the relative path in quick access entry

**Comment by MRayermannMSFT** [comment]
@OneMoreSecond , for today, as a workround you can attach the container via Azure AD, specify a path, and then add that attachment to quick access.

I'll post some screenshots showing you how in a bit...

**Comment by MRayermannMSFT** [comment]
@richardmsft look at how attaching containers at a specific directory work for guidance

**Comment by richardMSFT** [comment]
Done, and will be included in the 1.35.0 release.
