### ISSUE TITLE
Nothing happens when cloning one blob with an exist blob name

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2711]
**Storage Explorer Version:** 1.12.0
**Build:** [20200312.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3544533)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04
**Architecture:** ia32/x64
**Regression From:** Previous release(1.12.0)

**Steps to reproduce:**
1. Expand one Non-ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container-> Upload two blobs to it.
3. Select one blob and right click it -> Click 'Clone with New Name...'.
4. Specify the new name with another blob name.
5. Check the result.

**Expect Experience:**
An error dailog pops up.
![image](https://user-images.githubusercontent.com/41351993/76497344-cc507e80-6475-11ea-9e37-ebbed585d85e.png)

**Actual Experience:**
Nothing happens.

**Comment by v-limu** [comment]
Verified on build [20200313.5](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3548335&view=results
). This issue has been fixed. So we close it.
