### ISSUE TITLE
Show ellipsis next to the 'Clone with New Name' button for one file share

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2715]
**Storage Explorer Version:** 1.12.0
**Build**: [20200313.5](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3548335&view=results
)
**Branch**: master
**Platform/OS**: Windows 10/ Linux Ubuntu 19.04
**Architecture**: ia32/x64
**Regression From:** Previous release(1.12.0）

**Steps to reproduce:**

1. Expand one storage account -> File Shares.
2. Create a new file share -> Open it.
3. Observe the 'Clone with New Name' button on toolbar.

**Expect Experience:**
No ellipsis shows next to the 'Clone with New Name'.
![image](https://user-images.githubusercontent.com/54055206/76598114-1486a400-653d-11ea-94a2-6573dae69deb.png)

**Actual Experience:**
Show ellipsis next to the 'Clone with New Name'.
![image](https://user-images.githubusercontent.com/54055206/76598066-f751d580-653c-11ea-85ee-3d459914f57d.png)

**Comment by v-xianya** [comment]
Verified on build [20200314.6.](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3551973) Fixed. So we close it.
