### ISSUE TITLE
The editor shows blank for one new created blob container under name & key attached account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2716]
**Storage Explorer Version:** 1.12.0
**Build**: [20200313.5](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3548335&view=results
)
**Branch**: master
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Attach one Non-ADLS Gen2 storage account via name & key.
2. Expand the attached storage account -> Blob Containers.
3. Create a new blob container -> Observe the result.

**Expect Experience:**
1. The new created blob container is auto opened.
2. The editor shows well under the opened tab. 
![image](https://user-images.githubusercontent.com/41351993/76610346-bd3ffe00-6553-11ea-9fb5-c296eec5415b.png)

**Actual Experience:**
1. The new created blob container is auto opened.
2. The editor shows blank under the opened tab. 
![image](https://user-images.githubusercontent.com/41351993/76608491-a8ae3680-6550-11ea-9124-3679bc326bf9.png)

**More Info:**
1. This issue doesn't reproduce for ADLS Gen2 accounts.
2. This issue doesn't reproduce for File Shares/ Queues/ Tables.

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
