### ISSUE TITLE
Failed to create blob container.

### ISSUE THREAD

**Issue by Jen-Pearson** [microsoft/AzureStorageExplorer#2718]
I have the latest version of the Storage Emulator installed (5.10).  When I connect to it using the Azure Storage Explorer I'm just getting a bunch of internal errors.

![image](https://user-images.githubusercontent.com/8033039/76713877-d2957200-6777-11ea-890a-5179bb4f2936.png)

My emulator was initialised and started successfully.

Selecting the blob containers entity:
![image](https://user-images.githubusercontent.com/8033039/76713864-c27d9280-6777-11ea-9088-1158c8ba876d.png)

Expanding containers, right clicking to create new container:
![image](https://user-images.githubusercontent.com/8033039/76713850-ab3ea500-6777-11ea-8411-4cc6f4a91b6f.png)

I have also installed the latest version of the Azure Storage Explorer but am still getting internal errors telling me to try again later.

**Comment by MRayermannMSFT** [comment]
@Jen-Pearson are you still running into this issue?

**Comment by MRayermannMSFT** [comment]
Just tried this. No issues. Moving to be un-tiraged until Jen Pearson replies.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you're still having problems.
