### ISSUE TITLE
The value of 'sr' is incorrect in blob's SAS URI which created by selecting access policy

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2719]
**Storage Explorer Version:** 1.12.0
**Build**: [20200313.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3548286)
**Branch**: feature/blob-migrate-v12-sdk
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Regression From:** Previous release (1.12.0)

**Steps to reproduce:**
1. Expand one normal storage account -> Blob Containers.
2. Create one blob container then right click it -> Select 'Mange Access policies...' to add one access policy.
3. Upload one blob to the new created blob container.
4.  Right click the uploaded blob -> Select 'Get Shared Access Signature...'.
5.  Select the access policy to create SAS URI.
6. Check the value of property 'sr' in the SAS URI.

**Expect Experience:**
Display 'sr=b' in SAS URI.

**Actual Experience:**
Display 'sr=c' in SAS URI.

**More Info:**
1. Generate container-level shared access signature URI is not selected.

**Comment by JasonYeMSFT** [comment]
This is caused by the underlying behavior of the SDK. An access policy applies to container level access control so that the SDK decides to set the resource type to "c" for a generated SAS with access policy.

**Comment by v-xianya** [comment]
@JasonYeMSFT 
If the resource type can be set to 'c' by selecting an access policy.
So if we use an access policy, In my opinion, disable  the option 'Generate container-level shared access signature URI' is better.

**Comment by JasonYeMSFT** [comment]
After discussion, we decided to remove the Generate as Container SAS option and remove the inapplicable List permission when generating blob level SAS. We can update the info message to inform user about this behavior.

**Comment by v-xianya** [comment]
@JasonYeMSFT 
Verified this issue on build [20200327.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3588105). Everything is perfect. so we close it.
1. The option Generate as Container SAS is removed.
2. The resource type is set to 'c' by selecting an access policy.
3. The info message is added.

![image](https://user-images.githubusercontent.com/41351993/77719566-8b816980-7020-11ea-8f76-309d8968dd06.png)

**Comment by Nethemas** [comment]
Going from this:
![image](https://user-images.githubusercontent.com/22692536/82104648-566acc80-96dd-11ea-87f8-8bf501ca3080.png)

To this:
![image](https://user-images.githubusercontent.com/22692536/82104687-6aaec980-96dd-11ea-8e68-c48d66410df2.png)

Feels more like feature regression than a bug fix.  The SAS being generated also aren't valid, now getting "signature did not match" authentication errors when I try to access blobs with the SAS.  I'm now stuck on 1.12 until I can get replacement for the removed functionality.

**Comment by JasonYeMSFT** [comment]
@Nethemas The removal of the checkbox is by design because we want to make it clear between blob SAS and container SAS. You are not supposed to generate a SAS that can access things that you didn't select. The invalid SAS regression was caused by us setting the incorrect resource type. We are making a patched release 1.13.1 which will contain a fix for the invalid SAS issue but we are not planning to add the checkbox back.
