### ISSUE TITLE
Right-click menu is missing the "Copy URL" option

### ISSUE THREAD

**Issue by pieterclaerhout** [microsoft/AzureStorageExplorer#272]
**Storage Explorer Version**: 1.1.0
**Platform**: macOS
**Architecture**: x64

#### Steps to Reproduce: ####
1. Connect to a storage account and go to a storage container
2. Right-click on a blob
3. The toolbar at the top has the button "Copy URL", however, when you right-click on the blob, you don't have this option. It would be very handy to have the "Copy URL" option in the right-click menu as well (similar to the download option). All the other options are there except for "Copy URL".

<img width="3008" alt="screen shot 2018-06-07 at 09 39 18" src="https://user-images.githubusercontent.com/74731/41085355-1b120dda-6a37-11e8-864c-8078a2f53f9a.png">

#### Expected Experience: ####

I would expect the "Copy URL" option to be there in the right-click menu.

#### Actual Experience: ####

The "Copy URL" option is not there in the right-click menu

**Comment by MRayermannMSFT** [comment]
This was done at some point.

**Comment by pieterclaerhout** [comment]
Are you sure? I'm using version 1.12.0 and when right-clicking on an item, there is no "Copy URL" function…

**Comment by jinglouMSFT** [comment]
@pieterclaerhout can you take a screenshot for us?  Thanks.

**Comment by pieterclaerhout** [comment]
As you can see, no copy URL in the menu…

<img width="2373" alt="Screenshot 2020-04-26 at 11 46 18" src="https://user-images.githubusercontent.com/74731/80303946-919b6f00-87b3-11ea-8792-c47983086815.png">

**Comment by v-xianya** [comment]
Hi @pieterclaerhout 
This issue will be fixed in Storage Explorer 1.13.0.
