### ISSUE TITLE
The permission 'List' can't be passed to SAS URI for blobs

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2720]
**Storage Explorer Version:** 1.12.0
**Build**: [20200313.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3548286)
**Branch**: feature/blob-migrate-v12-sdk
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Regression From:** Previous release (1.12.0)

**Steps to reproduce:**
1. Expand one normal storage account -> Blob Containers.
2. Create one blob container -> Upload one blob to it.
3.  Right click the uploaded blob -> Select 'Get Shared Access Signature...'.
4.  Using the default permissions (Read & List) -> Click 'Create'.
5. Copy the URI -> Check the value of 'sp' in SAS URI.

**Expect Experience:**
The value of 'sp' is rl. (sp=rl)

**Actual Experience:**
The value of 'sp' is r. (sp=r)

**Comment by JasonYeMSFT** [comment]
List permission doesn't apply to blobs and new version SDK is checking if invalid permission exists in the SAS. What we current do is if it is a "sr=c" SAS, we pass the L permission to the SAS, otherwise ("sr=b"), we take it out.

**Comment by v-xianya** [comment]
@JasonYeMSFT Got it. Thanks for the sharing.
'l' is successfully passed when creating a container level sas.
In addition, It would be better if provide a clue to tell users that List permission doesn't apply to blobs.

**Comment by JasonYeMSFT** [comment]
After discussion, we decided to remove the Generate as Container SAS option and remove the inapplicable List permission when generating blob level SAS.

**Comment by v-xianya** [comment]
Hi @JasonYeMSFT 
We noticed that 'List' is removed from permissions. (on build master/20200327.2)
But we still got the below error after pasting the blob SAS URI into Attach with SAS URI dialog. 

![image](https://user-images.githubusercontent.com/41351993/77734525-d365b800-7043-11ea-9a74-cf69c1b67fde.png)

Maybe we can directly give the below info😊
1. Permission 'list' is not supported on blobs level SAS URI. 
2. Not support to attach blobs.

**Comment by JasonYeMSFT** [comment]
Since we are removing the option to generate blob SAS as container level SAS. We now require user to use SAS generated from the container nodes to attach.
