### ISSUE TITLE
No error notification shows when attaching one blob using a container-level SAS URI directly

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2721]
**Storage Explorer Version:** 1.12.0
**Build**: [20200313.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3548286)
**Branch**: feature/blob-migrate-v12-sdk
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one normal storage account -> Blob Containers.
2. Create one blob container -> Upload one blob to it.
3.  Right click the uploaded blob -> Select 'Get Shared Access Signature...'
4. Check ‘Generate container-lever shared access signature URI ’ -> Create -> Copy the URI.
5. Open connect dialog -> Select use a SAS URI -> Next.
6. Paste the copied URI -> Check the result.

**Expect Experience:**
An error notification shows.
![image](https://user-images.githubusercontent.com/41351993/76737897-9298b400-67a4-11ea-9ecb-765e537fa9d6.png)

**Actual Experience:**
No error notification shows.
![image](https://user-images.githubusercontent.com/41351993/76737790-63824280-67a4-11ea-974e-25c1955b8c17.png)

**More Info:**
1. Related bug: [2185](https://github.com/microsoft/AzureStorageExplorer/issues/2185)

2.  This issue doesn't reproduce on master [20200314.6](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3551973)

**Comment by JasonYeMSFT** [comment]
This is due to a fix in the master not merged into the feature branch. I would say there is no need to worry about this because it would go away after we we merge the feature branch to master.

**Comment by JasonYeMSFT** [comment]
@v-xianya The feature branch has been merged into master. Could you please verify the master on this issue? Thanks.

**Comment by v-xianya** [comment]
Verified this issue on build master/[20200329.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3593627). Fixed.
