### ISSUE TITLE
Add the action 'Manage Access Policies...' for one storage account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2723]
**Storage Explorer Version:** 1.12.0
**Build**: [20200317.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3556898)
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Select one normal storage account -> Right click it.
2. Check its context menu.

**Expect Experience:**
The action 'Manage Access Policies...' displays on the context menu.

**Actual Experience:**
No action 'Manage Access Policies...' displays on the context menu.

**Comment by MRayermannMSFT** [comment]
@v-xianya we checked the portal and didn't see access policies on the storage account level. Can you tell us where you are seeing account level access policies?

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT  I see that the access policies on Container level. So I want to know if it also can be applied to Storage Account level😶

**Comment by MRayermannMSFT** [comment]
Oh @v-xianya, well we can't find any mention of it being supported at the storage account level, so we don't think it is possible.
