### ISSUE TITLE
Keep a consistent tooltip format between 'Dequeue Message' and 'Requeue Message'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2725]
**Storage Explorer Version:** 1.12.0
**Build**: [20200317.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3556898)
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Queues.
2. Create one new queue and keep it open.
3. Check the tooltip of actions 'Dequeue Message' and 'Requeue Message' on the toolbar.

**Expect Experience:**
Display a consistent tooltip format between the two actions.

**Actual Experience:**
Display inconsistent tooltip formats between the two actions.
![image](https://user-images.githubusercontent.com/41351993/76836917-9132be80-686c-11ea-8c08-a92671922022.png)

**More Info:**
The tooltip of action 'View Message' needs to keep the same format with the two actions.
![image](https://user-images.githubusercontent.com/41351993/76836972-ac053300-686c-11ea-8f75-c5c2e1753473.png)

**Comment by v-limu** [comment]
Verified on build 20200522.4. This issue has been fixed. So close it.
![image](https://user-images.githubusercontent.com/54055206/82791481-6f733a80-9ea0-11ea-8b1f-473075133a2c.png)
