### ISSUE TITLE
An error occurs when creating sas for one blob container under name & key attached account

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2726]
**Storage Explorer Version:** 1.12.0
**Build**: [20200318.5](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3561251
)
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/ macOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Previous release(1.12.0)

**Steps to reproduce:**

1. Attach one Non-ADLS Gen2 storage account via name & key.
2. Expand the attached storage account -> Blob Containers.
3. Create a new blob container -> Right click it -> Click 'Get Shared Access Signature...'
4. Click 'Create' in the sas dialog and check the result.

**Expect Experience:**

1. No error occurs.
2. URI and Query string show well.

**Actual Experience:**
An error pops up.
![image](https://user-images.githubusercontent.com/54055206/76940705-b3dcda00-6935-11ea-9b45-e86a5a3ad3ec.png)

**More Info:**
This issue also reproduce for one blob under name & key attached account.

**Comment by v-xianya** [comment]
@JasonYeMSFT 
This issue is fixed on build master [20200327.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3588105). So we close it.
