### ISSUE TITLE
Show consistent symbol next to the strings in Access Policies dialog

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2727]
**Storage Explorer Version:** 1.12.0
**Build**: [20200318.5](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3561251
)
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/ macOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Previous release(1.12.0)

**Steps to reproduce:**

1. Expand one Non-ADLS Gen2 storage account -> Blob Containers.
2. Create a new blob container -> Right click it -> Click 'Manage Access Policies...'.
3. Add access policies -> Check the strings in Access Policies dialog.

**Expect Experience:**
Show consistent symbol next to the strings.

**Actual Experience:**

1. No colon shows next to 'Id'.
2. A colon shows next to 'Start time' & 'Expiry time'.

![image](https://user-images.githubusercontent.com/54055206/76941372-dd4a3580-6936-11ea-8943-b37c584f923d.png)

**More Info:**
This issue also reproduces for one file share/ queue / table.

**Comment by MRayermannMSFT** [comment]
This appears to be fixed on main.
