### ISSUE TITLE
Improve traceability by allowing to use RBAC only

### ISSUE THREAD

**Issue by hilari0n** [microsoft/AzureStorageExplorer#2728]
In cases when traceability is important when using an Azure Storage Account, it's beneficial when all the actions against an Account are performed solely using RBAC. Only in this scenario each action against the Azure Storage Account content can be traced back to a user/application in the logs.
Unfortunately Azure Storage Explorer application uses a full mix of authentication/authorization options, performing operations using Storage Account Key, using SAS tokens and (rarely) using RBAC, when the user has full Account access.
Additionally Azure Storage Explorer extracts Storage Account Keys on first opportunity, polluting the Azure Storage Account Activity Log with "List Storage Account Keys" entries, which makes any activity analysis complicated, when keys are retrieved all the time, so you can't attribute use of those keys to anyone specific.

It'd be beneficial if there was an option in the Azure Storage Explorer, to (all at once or separately):

- enforce use of RBAC for all actions (this would need to include AzCopy operations),
- stop obtaining SAS tokens, except for explicit user demand (and even then still use RBAC),
- stop retrieving Storage Account Keys (and connection strings containing those), except for explicit user demand (and even then still use RBAC),
- only fall back to Storage Account Keys (and SAS tokens) use, when:
  - no RBAC access is available for an Account and the user explicitly allows the fall back (for this specific Account only and only for application session duration),
  - a specific operation is not supported via RBAC and the user explicitly allows the fall back for this operation (each time the operation is performed).

As there seems to be no way on the Azure Storage Account service side to disable use of Storage Account Keys, there does not seem to be any alternative to this solution, other than doing this on the client side (the Azure Storage Explorer in this case).

**Comment by hilari0n** [comment]
> Hey @hilari0n , good news! For 1.13 we're adding a feature which I believe should fulfill some of your bullets. Let me go over what we're shipping and how it relates to each of your bullets, and then you let me know if you'd still like more.

Hi!

Sorry for such a late response. Working from home, with kids on our backs is not helping. :)
Thanks for sharing the news! The direction is very promising! I will definitely like the improvement.

Some feedback:

> **stop retrieving Storage Account Keys (and connection strings containing those), except for explicit user demand (and even then still use RBAC)**
> We're going to still need to retrieve keys for Table and File Shares since those services don't support RBAC. This will probably be true for a very long time.

I don't mind allowing people to still use features, which will still rely on Storage Keys. Will this however be something explicitly clear (at least by an option), so I'm warned **before** the key is actually retrieved, so I could cancel my action?
For most of the time the Blob Storage is the only service I use from Azure Storage, so retrieving the keys just because the same Account also hosts Table Storage or even because I clicked the "Tables" node in the explorer, is not something I would like to trigger key retrieval. Even expanding the "Tables" node may be a misclick. For most of the time I could even work with access to all non-blob sub-services disabled in the Azure Storage Explorer, but still, on some cases I will need it back on and would prefer to be explicitly warned/asked if I'm sure I want to do something, that requires key retrieval.

> **only fall back to Storage Account Keys (and SAS tokens) use when no RBAC access is available for an Account and the user explicitly allows the fall back (for this specific Account only and only for application session duration)**
> The new setting is currently an application wide setting. So if you enable it, and you try doing blob service, blob container, and blob actions under an account which you don't have the needed RBAC roles for that action, then things won't work.

It may be a problematic approach for when you have to work with a mix of Storage Accounts: some with RBAC configured properly and some not. I'm in such spot unfortunately.
But having said that, I still appreciate what you are doing here: You have to start somewhere and this looks like a great beginning.

And a question:
Currently the Azure Storage Explorer retrieves Storage Keys already when you navigate the resource tree, i.e. when you click on a Storage Account node in the explorer tree, e.g. to see its SKU or location, they keys are being retrieved, as among the properties you have the keys and connection strings. How will the "disable keys" setting affect that?
I would still prefer to be able to see other properties and also be able to retrieve a connection string (without a storage key), without triggering the key retrieval.


Again, thanks for sharing the plans and I'm eager to see those changes in the product!
I'm also hoping, that the Azure Storage service itself will follow your example and see some changes in this direction (e.g. allow disabling Storage Keys completely for a Storage Account).

**Comment by MRayermannMSFT** [comment]
No worries on the slow reply. We're in the same boat so we understand.

> I don't mind allowing people to still use features, which will still rely on Storage Keys. Will this however be something explicitly clear (at least by an option), so I'm warned **before** the key is actually retrieved, so I could cancel my action?

To be fully transparent, the keys are loaded shortly after the storage account is shown in the tree view. Are you worried about list key API calls showing up in your account logs or something like that?

> It may be a problematic approach for **when you have to work with a mix of Storage Accounts: some with RBAC configured properly and some not**. I'm in such spot unfortunately.
But having said that, I still appreciate what you are doing here: You have to start somewhere and this looks like a great beginning.

Yes, we are aware of **this**. Unfortunately detecting when a storage account is properly setup and when it isn't is not easy to do. What it means to be setup could have different meanings for different people. I think the end goal for Storage Explorer and keys involves potential ideas like:
- letting the user opt-in/opt-out specific storage accounts from using keys
- once all storage services support RBAC, not listing keys except as a last resort, but there are perf implications for this
- dynamically checking a user's RBAC access per resource, though I've been unable to find an API (at least when looking this morning) that would let us easily do this

But as you say, we wanted/needed to start somewhere.

> Currently the Azure Storage Explorer retrieves Storage Keys already when you navigate the resource tree, i.e. when you click on a Storage Account node in the explorer tree, e.g. to see its SKU or location, they keys are being retrieved, as among the properties you have the keys and connection strings. How will the "disable keys" setting affect that?
I would still prefer to be able to see other properties and also be able to retrieve a connection string (without a storage key), without triggering the key retrieval.

All of those are unaffected by the setting. It'll only affect blob specific features. Or in other words, the SKU, location, and key connection strings will all still be available. Are you worried about list key API calls showing up in your account logs or something like that?

**Comment by hilari0n** [comment]
Thanks for the explanation.

> To be fully transparent, the keys are loaded shortly after the storage account is shown in the tree view. Are you worried about list key API calls showing up in your account logs or something like that?

Yes, as I wrote previously:

> [...] Azure Storage Explorer extracts Storage Account Keys on first opportunity, polluting the Azure Storage Account Activity Log with "List Storage Account Keys" entries, which makes any activity analysis complicated, when keys are retrieved all the time, so you can't attribute use of those keys to anyone specific.

A real life scenario:
1. An Azure Storage Account is properly set up using RBAC:
  a. only select identities are granted appropriate access,
  b. anonymous access is disabled,
  c. Account administrators (ARM) are also granted RBAC access, so they can use it instead of Storage Keys,
  d. there's no way of blocking Storage Keys, so all Account ARM contributors still have access to Storage Keys.
2. As we need operation traceability, we set up Storage Analytics Logs
3. We need to trace, who has performed a specific "offending" Blob Storage operation, so we review the logs and find, that the offending operation was done using a Storage Key.
4. We review Storage Account Activity Log, to see who has retrieved the keys prior to the operation (since the Account setup).

In this scenario, using Azure Portal or Azure Storage Explorer to browse Storage Accounts (in case of Azure Portal, it'll be browsing the Account content, in case of Azure Storage Explorer it would just be listing the Storage Accounts) makes you a potential suspect, as those actions cause the Storage Key to be retrieved, and such key can be retained indefinitely and used later for any operation. There's no way for you to prove, that you have not stored the Storage Key obtained this way (even if in reality you were oblivious, that those applications retrieved it).

To prevent this, we'd need one of:
1. Ability to block Storage Account Key existence or use (which is not available).
2. Only use client applications, which do not retrieve the Account Keys (which excludes using Azure Portal for Storage Account content view or using Azure Storage Explorer for anything), which leaves us with basically no client application.
3. Rotate the Storage Account keys very often (optimally just after they were retrieved), which is impractical (as it would require complex analysis of the Activity Logs and could still end up inconclusive).

As for this:
> Unfortunately detecting when a storage account is properly setup and when it isn't is not easy to do. What it means to be setup could have different meanings for different people. I think the end goal for Storage Explorer and keys involves potential ideas like:
> [...]

Yes, it does mean complexity, both on the Explorer code side and the User Experience side. I'm not sure it does necessarily require complex setup from the user, but that obviously depends on expectations.
My take on this is based on an assumption, that you can attempt an RBAC-enabled action and if you do not have enough RBAC privilege,s you will get an error message which can be easily recognized as such (easily distinguishable for other error causes).
If this is true, for all RBAC-enabled action, I would always first attempt it using RBAC (even if the application already retrieved the Storage Account Key).
When a Storage Key would be needed (i.e. for non RBAC-enabled operation or when RBAC-enabled one fails due to insufficient privileges), the user would be presented with a choice to `Abort` or `Obtain the Storage Account Key and use it` and (for `Obtain...`) options:
   a. Ask each time,
   b. Remember my choice for this account and session,
   c. Remember my choice for this account permanently.
Option "a" is quite obvious. Option "b" and "c" would mean that subsequently similar actions would still always attempt RBAC-based execution first, but if fail due to insufficient RBAC privileges, the Storage Key would be used automatically, without additional prompts. For option "c" some kind of flag would need to be stored in application settings for that particular Storage Account (probably with a context menu option available on the Account, to clear it and/or some list in application settings, where one could see the list of storage accounts with this flag set).
The user experience could be designed in multiple ways, but the core behavior would be to always try RBAC first (if possible) and only if it fails, use the Storage Key.
Yes, it does mean some performance degradation, but not necessarily significant. All this approach could be an option (as the "disable keys" you described) or also offer more aggressive (per account) opt-outs.

**Comment by MRayermannMSFT** [comment]
> Yes, it does mean some performance degradation, but not necessarily significant.

For someone who has no interest in onboarding RBAC, it makes every API call take 2 attempts. Some might consider that significant. 🙃

> All this approach could be an option (as the "disable keys" you described) or also offer more aggressive (per account) opt-outs.

Very true. And that would help the people who have no interest in RBAC get rid of the perf hit if they so choose. 👍

I'm going to go ahead and move this issue to our 1.16 milestone to be revisited then. I'm hoping that by then we'll at least have queues supporting RBAC, and then at that point maybe we can have the new setting also take affect there, and also have an impact on things like showing a primary key connection string in the properties panel. Just get it to the point where we only retrieve keys if the user tries working with a non RBAC storage service, like tables or file shares. And maybe even when the setting is on, we can do as you suggest and confirm with the user they want us to retrieve keys and why we need to.

> I'm also hoping, that the Azure Storage service itself will follow your example and see some changes in this direction (e.g. allow disabling Storage Keys completely for a Storage Account).

If such a feature was going to be coming online, would you like to preview it?

**Comment by hilari0n** [comment]
> > Yes, it does mean some performance degradation, but not necessarily significant.
> 
> For someone who has no interest in onboarding RBAC, it makes every API call take 2 attempts. 
Some might consider that significant. 🙃

In worst case scenario, yes. I was referring to "actions" rather than "requests". For actions which use continuation requests, I'm assuming only the first one will have to be repeated and the subsequent ones will use the successful method. Similarly, if you want to download/upload a batch of files, if it fails on the first one, you'll retry the whole batch with the alternate method. Etc.

> I'm going to go ahead and move this issue to our 1.16 milestone to be revisited then.

I'm for seeing any improvement as soon, as possible, even if not fulfilling all expectations. Especially that they may address needs of other users, not voiced here and may result in valuable feedback also for scenarios I'm concerned with.

> > I'm also hoping, that the Azure Storage service itself will follow your example and see some changes in this direction (e.g. allow disabling Storage Keys completely for a Storage Account).
> 
> If such a feature was going to be coming online, would you like to preview it?

I most definitely would like to, although I can't promise I will find a lot of time. :(

**Comment by MRayermannMSFT** [comment]
Unfortunately not much has changed since back in March. We have some high pri things that need working on (proxy issues, new storage features, etc.), so moving this to future for now.

**Comment by cveld** [comment]
This has been a long thread so far. I believe RBAC has been implemented for file share data plane in the meantime. Is there any ETA when this gets implemented in the client?

And can you update the original description of this issue as today it is possible to turn off key auth on the storage account itself.

**Comment by MRayermannMSFT** [comment]
> I believe RBAC has been implemented for file share data plane in the meantime.

Full OAuth support has only just been added for file shares. There were several data plane APIs that were missing support, up until this a few weeks ago. Therefore, In Storage Explorer 1.36.0, we'll finally be enabling OAuth support for file shares! This means when you turn on the "Disable Usage of Keys" settings, that so long as you have permissions setup correctly and are doing through sign in or OAuth attached resources, that no keys should ever be used.

Also regarding per storage account disabling of keys, our recommendation at this time is to make use of the "Allow storage account key access" setting in ARM. You can currently toggle this setting in the Portal:


![Image](https://github.com/user-attachments/assets/949bfee7-bf57-4d07-8ddd-e99d29aa477f)

When set to "Disabled", Storage Explorer will pick up on this when listing the storage account, and automatically not use keys for it.
