### ISSUE TITLE
The deleted entity doesn't automatically disappear 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2732]
**Storage Explorer Version:** 1.12.0
**Build**: [20200319.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3564230)
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ Linux Ubuntu 19.04/ macOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Previous release(1.12.0)

**Steps to reproduce:**

1. Expand one storage account -> Tables.
2. Create one table -> Add one entity.
3. Delete the entity -> Check the result.

**Expect Experience:**
The deleted entity disappears.

**Actual Experience:**
The deleted entity still displays.

**More Info:**
1. **Only the first added entity can display automatically.** The second entity added and the ones added later will not be displayed automatically.
2. The entity disappears after manually refresh.

**Comment by craxal** [comment]
I noticed that the headers become misaligned with the columns. If I adjust the column widths enough, the table "magically" redraws correctly.

The issue appears to be related to the likelihood that multiple instances of the Datatables API are being created and passed around in the view models. We can work around that by going back to using the "immediately accessible" API instance, then continue the post-rendering work, such as updating the ARIA label, through the table operation manager.

**Comment by v-xianya** [comment]
@craxal 
This issue reproduces on build 20200324.2. So we re-open it.

**Comment by craxal** [comment]
@v-xianya Unable to reproduce on my end. My suspicion is the build you got didn't get the changes, so I'm just going to close again and let you verify on a newer build.

**Comment by v-xianya** [comment]
@craxal Thank you for the update. This issue is fixed on build 20200324.12.
