### ISSUE TITLE
Display a white border box on the selected blobs Name column

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2737]
**Storage Explorer Version:** 1.12.0
**Build**: [20200319.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3564230)
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Previous release (1.12.0)

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Select one blob container which contains blobs.
3. Open the blob container -> Select one blob and check the first column (Name column).

**Expect Experience:**
No border box display on the Name column.
![image](https://user-images.githubusercontent.com/41351993/77129709-f1557a80-6a8f-11ea-87ba-e67fed01523e.png)

**Actual Experience:**
Display a white border box on the Name column.
![image](https://user-images.githubusercontent.com/41351993/77129723-0205f080-6a90-11ea-8e2b-be90b18b4af5.png)

**More info:**
This issue also reproduces for one file share/ table/ queue.

**Comment by craxal** [comment]
This is by design. It is related to accessibility issue #1959, where we need to visual indicated selected rows.
