### ISSUE TITLE
Miss '->' in the description of setting 'User credentials'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2739]
**Storage Explorer Version:** 1.12.0
**Build**: [20200319.10](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3566615)
**Branch**: master
**Language**: Portuguese (Brazil)
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '**Português (Brasil**)' -> Restart Storage Explorer.
3. Open 'Settings' -> Localized 'Application'.
4. Check the description of Use credentials.

**Expect Experience:**
The symbol '->' displays in the description.
ENU screenshot:
![image](https://user-images.githubusercontent.com/41351993/77148246-1ff04700-6aca-11ea-9370-896626246193.png)

**Actual Experience:**
Miss '->' in the description.
![image](https://user-images.githubusercontent.com/41351993/77148293-35fe0780-6aca-11ea-9adc-11d7be66299c.png)

**More Info:**
This issue doesn't reproduce on other 17 languages.

**Comment by lukaschal** [comment]
Fixed.

new tgt: Se habilitado, o Gerenciador de Armazenamento usará as credenciais especificadas na caixa de diálogo Configurações de Proxy (Editar → Configurar Proxy).

**Comment by v-xianya** [comment]
Verified this issue on build [20200322.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3573346). Fixed. So we close it.
