### ISSUE TITLE
Broken icon in all places where they should exist

### ISSUE THREAD

**Issue by leungi** [microsoft/AzureStorageExplorer#274]
**Storage Explorer Version**:  1.1.0
**Platform**: Windows
**Architecture**:  ia32
**Regression From**:  N/A

#### Steps to Reproduce: ####
1. Open Azure Storage Explorer
2. Observe icons

#### Expected Experience: ####
Icons showing 

#### Actual Experience: ####
Broken icon showing 

![image](https://user-images.githubusercontent.com/30273868/41100695-a398ff20-6a27-11e8-99e1-ef5fdceda45f.png)

![image](https://user-images.githubusercontent.com/30273868/41100717-b490ec7a-6a27-11e8-847a-b783ec32c64b.png)

**Comment by JasonYeMSFT** [comment]
Hi @leungi , 

We cannot reproduce this bug in our machine. Could you please provide us with your Windows version? 

If possible, could you please use the developer tool to select the broken icons and check whether the icon image files actually exist in the given path?

Thank you very much.

**Comment by leungi** [comment]
@JasonYeMSFT, thanks for prompt review.

I'm on Windows 7 Enterprise, SP1.

Tried dev tools to inspect, and found the following issue - Debug.js:39.

**Comment by JasonYeMSFT** [comment]
Does this issues affects the other functionality? If this doesn't affect the other functionality, we are not going to prioritize this issue. However, if this does affect the other functionality, please tell us and let us figure out some work around.

By the way, please upgrade your OS if possible. We have seen some issues that only occurs on Windows 7. Upgrading the OS can sometimes solve the problem. Thank you very much.

**Comment by leungi** [comment]
Noted. Full functionality, just affecting aesthetics for now.

Will heed your advice, and update here if other issues surface.

Thanks again.

**Comment by MRayermannMSFT** [comment]
Haven't seen this at all recently. @leungi , if you're still seeing this in version 1.12, please open a new issue. Thanks.

**Comment by leungi** [comment]
Thanks for issue reminder; 1.8.1 fixed the bug! 🙌

![image](https://user-images.githubusercontent.com/30273868/80178416-c5b03d80-85c3-11ea-9e1c-bcd53a6285b8.png)
