### ISSUE TITLE
The tooltip of the 'Query string' copy button is not localized on SAS dialog

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2740]
**Storage Explorer Version:** 1.12.0
**Build**: [20200319.10](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3566615)
**Branch**: master
**Language**: Czech/ German/ Spanish/ French/ Hungarian/ Italian/ Japanese/ Korean/ Dutch/ Polish/ Portuguese (Brazil)/ Portuguese (Portugal)/ Russian/ Swedish/ Turkish/ Chinese (Simplified) / Chinese (Traditional)
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04 / MacOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Previous release(1.12.0)

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文(繁体)' -> Restart Storage Explorer.
3. Select a storage account -> Click 'Get Shared Access Signature... ' -> Create -> Hover over the Copy button of the 'Query string'.
4. Check the tooltip of the Copy button.

**Expect Experience:**
The tooltip of the Copy button is localized.

**Actual Experience:**
The tooltip of the Copy button isn't localized.
![image](https://user-images.githubusercontent.com/54055206/77149838-7a3ed700-6acd-11ea-9c38-93b25d77536e.png)

**Comment by lukaschal** [comment]
New string. On translation now.

0; "DescriptionCopyTokenToClipboard"

**Comment by v-limu** [comment]
Verified on build 2020327.2. This issue has been fixed. So we close it.
