### ISSUE TITLE
After editing a query filter and pressing Return key the edit message field dialogue pops up.

### ISSUE THREAD

**Issue by MikeWilliams-UK** [microsoft/AzureStorageExplorer#2741]
**Storage Explorer Version**: 1.12.0
**Build Number**: 20200114.3
**Platform/OS**: Windows 10
**Architecture**: ia32
**Regression From**:  Was this working in a previous version? Yes, sorry did not expect to need to know the previous version number as it was working fine!

## Bug Description ##
After **editing** a query filter and pressing Return key, the edit message fields dialogue pops up after the query has been executed.

## Expected Experience ##
**Given**
The user has chosen to query an azure table.
**When**
The user types a new value in the filter and presses Enter Key.
**Then**
The query is executed with the new filter and the new results displayed.

## Actual Experience ##
**Given**
The user has chosen to query an azure table.
**When**
The user types a new value in the filter and presses Enter Key.
**Then**
The edit message field dialogue pops up after the query has been executed.

## Additional Context ##
This has only started happening recently!

It is very frustrating and time-consuming to have to constantly switch between keyboard entry and mouse clicking to execute the query or to get rid of the unwanted dialogue after "forgetting" to click on the "Run Query" button instead of pressing Return

![image](https://user-images.githubusercontent.com/13162784/77172899-a26f0b80-6ab6-11ea-81af-c926542272da.png)

Unwanted dialog
![image](https://user-images.githubusercontent.com/13162784/77172680-486e4600-6ab6-11ea-8d1c-0ae4f5b597ed.png)

**Comment by craxal** [comment]
Related to #2631. Verifying to make sure the fix for that also fixes this.

**Comment by MikeWilliams-UK** [comment]
As a developer myself I concur that the symptoms are very similar and might well be due the key up listener.

**Comment by jinglouMSFT** [comment]
This does repro on 1.12.0 even with build 20200116.10.  It's actually fixed as a part of #2631 fix.  It will be in our 1.13.0 release.

**Comment by MikeWilliams-UK** [comment]
When is 1.13.0 due out?

**Comment by jinglouMSFT** [comment]
In few weeks.

**Comment by craxal** [comment]
@MikeWilliams-UK You can get a general idea by looking at our Milestones page. Keep in mind, these date fluctuate as needs or complications arise. As a developer, I'm sure you understand. 😄
