### ISSUE TITLE
The Properties of one blob snapshot are editable

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2743]
**Storage Explorer Version:** 1.12.0
**Build**: [20200322.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3573346)
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Previous release(1.12.0)

**Steps to reproduce:**

1. Expand one Non-ADLS Gen2 storage account -> Blob Containers.
2. Create a new blob container -> Upload one blob to it -> Create snapshot for the blob -> Manage Snapshots.
3. Select a snapshot -> Right click it -> Click 'Properties..'.
4. Check the Properties dialog.

**Expect Experience:**
The properties are not editable.

**Actual Experience:**
The properties are editable.
![image](https://user-images.githubusercontent.com/54055206/77293373-27f3f500-6d1d-11ea-8169-b7ad9a7a84f3.png)

**Comment by JasonYeMSFT** [comment]
Need to update se-blob-extension

**Comment by v-xianya** [comment]
This issue has been fixed on build 20200329.1. Close it.
