### ISSUE TITLE
No conflict dialog pops up when copying a file under 'View Share Snapshots' to file share

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2744]
**Storage Explorer Version:** 1.12.0
**Build**: [20200322.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3573346)
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one storage account -> File Shares.
2. Create a new file share -> Upload one file to it -> Create snapshot for the file share -> View Share Snapshots -> Open it.
3. Copy the file -> Close Snapshots -> Paste it to the file share.
4. Check the result.

**Expect Experience:**
Pop up a conflict dialog.
![image](https://user-images.githubusercontent.com/54055206/77292578-8cae5000-6d1b-11ea-92b7-66789ae26862.png)

**Actual Experience:**

1. No conflict dialog pops up.
2. The activity log shows below.

![image](https://user-images.githubusercontent.com/54055206/77292541-77d1bc80-6d1b-11ea-847f-0bb20a6fecc5.png)

**Comment by JasonYeMSFT** [comment]
We have removed the feature flag for AzCopy on file shares and this should be the new AzCopy behavior now.
