### ISSUE TITLE
The resources on the left always keep loading when restarting Storage Explorer to make MSAL enabled

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2745]
**Storage Explorer Version:** 1.12.0
**Build**: [20200322.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3573346)
**Branch**: master
**Platform/OS:** Linux Ubuntu 18.04/ macOS High Sierra
**Architecture**: x64
**Regression From:** Previous release (1.12.0)

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Settings -> Application -> Sign-in.
3. Enable the setting 'Microsoft Authentication Library (Preview)'.
4. Restart Storage Explorer -> Check the result.

**Expect Experience:**
Everything works well.

**Actual Experience:**
The resources on the left always keep loading.
![image](https://user-images.githubusercontent.com/41351993/77300361-e36e5680-6d28-11ea-9568-9af903178564.png)

**Comment by craxal** [comment]
@v-xianya Not sure if @MRayermannMSFT already told you, but there's a known bug in the current version of the auth library, and we're waiting for a fix.

**Comment by v-xianya** [comment]
@craxal
Hi Craig, Now I know it and thank you for the update.😀

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
