### ISSUE TITLE
Sign-in flow stuck upon receiving WWW-Authenticate challenge

### ISSUE THREAD

**Issue by meetamitbhatia** [Microsoft/AzureStorageExplorer#275]
Question: Does Azure Storage Explorer sign-in screen supports opening windows credential dialog (www-authenticate challenge)?

Issue:
=====
Customer is having issues Sign-in to Azure Storage Explorer and list subscription. They get the screen to enter their credentials but after entering credentials, screen is stuck.
Customer is already on latest version 1.1.0

![image](https://user-images.githubusercontent.com/13898372/41121265-80420ad6-6a5d-11e8-912e-fe180be46037.png)

Investigation
==========
- Captured fiddler traces and see that user has MFA enabled. Users are authenticated using their window credentials for second authentication. Generally, when they login-in to azure portal throughbrowser, they get a credential dialog on second authentication and enter their windows credentials to complete authentication
- While signing into Azure Storage explorer, authentication flow stucks at second authentication.
- It seems Azure Storage Explorer is stuck as it fails to open credentials dialog. We captured fiddler and see no communication post receiving www-authenticate challenge,

```
GET https://sts.xxx.xxx.com/adfs/ls/wia?client-request-id=xxxx  HTTP/1.1
Host: xxxx
Connection: keep-alive
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) StorageExplorer/1.1.0 Chrome/59.0.3071.115 Electron/1.8.3 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Referer: https://login.microsoftonline.com/Common/oauth2/authorize?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&client_id=xxxx
Accept-Encoding: gzip, deflate
Accept-Language: en-US

HTTP/1.1 401 Unauthorized
Content-Length: 0
Server: Microsoft-HTTPAPI/2.0
WWW-Authenticate: Negotiate
WWW-Authenticate: NTLM
Date: Mon, 04 Jun 2018 16:40:27 GMT
Proxy-Support: Session-Based-Authentication
```

- There's no communication further by client upon receiving WWW-Authenticate challenge

- I see a documentation which confirms that Azure Storage doesn't support NTLM proxies, not sure if it's due to same reason,
https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting
_Verify the authentication protocol used by your proxy server. Storage Explorer does not currently support NTLM proxies._

**Comment by craxal** [comment]
For completeness, what's the user's OS version? By the look, I'm assuming Windows 7?

NTLM...is the user working through an NTLM proxy? Because we don't support that right now. If it's not the proxy, @MRayermannMSFT has been looking into various sign-in issues, and this sounds very similar.

**Comment by temalo** [comment]
I think I am experiencing this issue as well, as after updating to the June version, I can no longer connect to my Azure account. When I removed and attempted to re-add my account, I never get past the MFA (either PIN or username/password with MFA) and SE will display my subscriptions, but will not allow me to select any subscription.. This is on Windows 10 latest (non-insiders 17134.48).

**Comment by craxal** [comment]
@temalo Are you also running under proxy settings? The original issue here appears to be an issue with trying to use Storage Explorer behind an NTLM proxy, which we don't support.

**Comment by MRayermannMSFT** [comment]
Closing due to the fact that Storage Explorer does not currently support NTLM proxy: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting#contact-proxy-server-admin

As a workaround, you can sign in with Visual Studio, or Visual Studio for Mac, and then your account will show up in Storage Explorer.
