### ISSUE TITLE
'Promote Snapshot' doesn't work for one blob under one Azure AD attached blob container

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2750]
**Storage Explorer Version:** 1.12.0
**Build**: [20200324.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3577314)
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Give an RBAC role to a user like 'Blob Data Owner Role' on one regular blob container tier.
2. Attach the blob container with Azure AD.
3. Create snapshot for one blob -> Manage Snapshots -> Right click the snapshot -> Click 'Promote Snapshot' -> Yes.
4. Check the result.

**Expect Experience:**
Succeed to promote snapshot.
![image](https://user-images.githubusercontent.com/54055206/77397159-4f20e580-6d62-11ea-805c-f78a0c995f1e.png)

**Actual Experience:**
The promote snapshot does not work.

**Comment by MRayermannMSFT** [comment]
Fix merged into master. Promote snapshot is now disabled if key or SAS are not available.
