### ISSUE TITLE
dotnet runtime 2.2 is EOL

### ISSUE THREAD

**Issue by faultylee** [microsoft/AzureStorageExplorer#2752]
**Storage Explorer Version**: 1.12.0
**Build Number**: 20200116.10
**Platform/OS**: Arch Linux
**Architecture**: x64
**Regression From**:  N/A

## Bug Description ##
Since `dotnet-runtime 2.2` is already EOL, is there plan to upgrade the dependency to `3.1`?

## Steps to Reproduce ##
Currently it still require `dotnet runtime 2.2`. I've tried removing `2.2` installing only `3.1`, it doesn't work for me.
![image](https://user-images.githubusercontent.com/1635211/77542909-de083c00-6ee1-11ea-92bc-11a8803d9de7.png)

## Additional Context ##
I'm the maintainer for Storage Explorer in AUR (Arch User Repo) (https://aur.archlinux.org/packages/storageexplorer/). `dotnet-runtime-2.2` has been removed from AUR so I'm raising it here since I can't find anyone else mentioning the same problem.

**Comment by kj299** [comment]
I have this issue also. same message as @faultylee

**Comment by faultylee** [comment]
It works now with `3.1.3`

**Comment by MRayermannMSFT** [comment]
Hey @faultylee we're actually going to be switching to .net core 2.1 in our next release. I hope this doesn't muck up your workaround.

**Comment by faultylee** [comment]
No worries, thanks for the heads up

**Comment by MRayermannMSFT** [comment]
@faultylee would you be up for installing a private build and letting me know if it works for you?

**Comment by faultylee** [comment]
@MRayermannMSFT sure. I usually do a quick test locally before I push the update to AUR.

**Comment by MRayermannMSFT** [comment]
@faultylee awesome! Again though, **this is not meant to be pushed to the AUR**.  I'm just giving it to you to see if it solves the .net core 2.2 issue (by working with .net core 2.1) and to see if our change to what's inside the .tar.gz works out ok. I do not recommend using this against prod data or anything like that. Simply validate the changes. 😋 Ok with that out of the way, here's a link to the build: https://storageexplorerpublish.blob.core.windows.net/privatebuilds/1.14-linux/StorageExplorer-linux-x64.tar.gz

**Comment by faultylee** [comment]
@MRayermannMSFT totally understand :smiley:  .I just tested, it works with [dotnet-runtime-2.1](https://aur.archlinux.org/packages/dotnet-runtime-2.1/) without any issue. I also tested with only `dotnet-runtime-3.1` installed and it complained about missing `2.1`. I looked around some tables and blobs all loads fine. Is there anything specific that you want me to test?

![image](https://user-images.githubusercontent.com/1635211/84376330-91481d80-ac13-11ea-9349-da41d074d71d.png)

I noticed some console error from electron when I browse around, probably harmless
```
- An error has occurred.  Please try the operation again.
- You can search for the error online: JSPlugin.4002
- No attribute loader for: $cloudName
- No attribute loader for: accessTier
- No attribute loader for: accountKind
- No attribute loader for: connectionType
```

Btw, I did some test with `1.13.1` before installing `1.14.0`, I just realized it stuck at the `Loading` spinner forever, the tree didn't load. I believe I didn't test it properly before this. I saw this error in electron's console
```
Hub Controller process exited prematurely with exit code 150
```
No one complain in AUR, so not sure how many has updated to `1.13.1` though

**Comment by MRayermannMSFT** [comment]
Ya, I have a feeling .net core 3.1 doesn't actually work with 2.x. From what I have read online, it is not backwards compat. Anyways, ok cool. I'm glad we were able to finally get onto an EOL version! You'll see this change roll out in our 1.14 release. Thanks for helping to verify. :)
