### ISSUE TITLE
Miss 'Detach' action for one Azure AD attached container after its associated account is removed

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2755]
**Storage Explorer Version:** 1.12.0
**Build**: [20200326.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3584532)
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Previous release(1.12.0)

**Steps to reproduce:**
1. Select one blob container.
2. Give RBAC access to the blob container 'Blob Data Owner Role'.
3. Attach this blob container via Azure Active Directory (Azure AD).
4. Remove the account associated with the Azure AD attached blob container.
5. Check the context menu of the blob container under Attached Containers node.

**Expect Experience:**
The action 'Detach' displays.
![image](https://user-images.githubusercontent.com/41351993/77618208-d2b02180-6f70-11ea-86fb-36413d8090bf.png)

**Actual Experience:**
No 'Detach' action displays.
![image](https://user-images.githubusercontent.com/41351993/77618212-d5ab1200-6f70-11ea-86b6-911a366eddf3.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
