### ISSUE TITLE
Support 'Cmd+A & Cmd+Z' actions for editable boxes

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2756]
**Storage Explorer Version:** 1.12.0
**Build**: [20200326.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3584532)
**Branch**: master
**Platform/OS:** macOS High Sierra
**Architecture**: x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Right click one blob container -> Select 'Clone with New Name...'. 
3. Try actions Cmd+A and Cmd+Z in the editable boxes on Clone dialog.
4. Check the result.

**Expect Experience:**
Actions 'Cmd+A & Cmd+Z' work well.

**Actual Experience:**
Actions 'Cmd+A & Cmd+Z' are not supported.

**More Info:**
The actions 'Ctrl+A & Ctrl+Z' work well for editable boxes on Windows and Linux.

**Comment by andreacassioli** [comment]
Yes, same issue here! Please fix!

**Comment by turowicz** [comment]
It's so painful having to select everything with the mouse

**Comment by turowicz** [comment]
👍

**Comment by MRayermannMSFT** [comment]
> **Is your feature request related to a problem? Please describe.**
> Keyboard navigation does not work as expected on MacOS. It'd be a really big QoL improvement to be able to use `Cmd+Up/Down` to traverse a directory structure as I can in Finder. Additionally, the standard keyboard shortcut to select all text, `Cmd+A`, does not work on text inputs in the app.
> 
> **Describe the solution you'd like**
> Better adherence throughout the app to standard MacOS keyboard conventions. A few specific examples:
>    - `Cmd+,` should open the settings tab
>    - `Cmd+Left/Right` should go back and forward instead of `Alt+Left/Right`. If focused on a text input, `Alt+Left/Right` should instead be bound to moving between words as normal in a MacOS text input
>    - `Cmd+Up/Down` should open a child directory and open the parent directory respectively as in Finder or Cyberduck
>    - (Nice to have) `Enter` should open the rename dialog instead of opening the directory
> 
> **Additional context**
> See https://support.apple.com/en-gb/HT201236

Copied from #3571

**Comment by v-xianya** [comment]
Verified this issue on build main/20201209.5. Fixed.
