### ISSUE TITLE
RA-GRS secondary endpoint

### ISSUE THREAD

**Issue by swieder** [microsoft/AzureStorageExplorer#2759]
Error when using the secondary endpoint of a RA-GRS account:   Unable to retrieve child resources Details: One of the request inputs is out of range

I connected to the secondary endpoint using a Connection String (copied from Storage Account in Portal and added -secondary to the accountname.

How can we use Storage explorer to access secondary side of RA-GRS storage account.

**Comment by MRayermannMSFT** [comment]
Duplicate of #421
