### ISSUE TITLE
Confusing setting category translation of "File Open"

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#2760]
**Storage Explorer Version**: 1.12.0
**Build Number**: N/A
**Platform/OS**: Windows/macOS/Linux
**Architecture**: N/A
**Regression From**:  N/A

## Bug Description ##
The translation is confusing for the settings category title "File Open".
It is translated to "文件已打开" in simplified Chinese.
I feel there is some misunderstanding in the translation. What we really mean here is not settings related to "opened files" but settings related to the "feature for opening files".

**Comment by JasonYeMSFT** [comment]
The relevant file is Shell.json "TitleFileOpen".

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
Fixed.

new tgt: 打开文件

**Comment by v-xianya** [comment]
@JasonYeMSFT 
This issue is fixed. So we close it.
![image](https://user-images.githubusercontent.com/41351993/82517097-efbb3800-9b4e-11ea-9d74-100e346c78ca.png)
