### ISSUE TITLE
The buttons in the 'Connect Summary' dialog are not localized

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#2770]
**Storage Explorer Version**: 1.12.0
**Build Number**: 
**Platform/OS**: All
**Architecture**: All
**Regression From**:  N/A

## Steps to Reproduce ##
1. Launch Storage Explorer using the command `StorageExplorer.exe --lang=zh-CN`.
2. Right-click a storage account and select "Copy Primary Key".
3. Open the Connect dialog and select "Using a storage account name and key". Click Next.
4. Paste the copied primary key and fill in display name and account name. Click Next.
5. Check the Connect Summary dialog.

## Expected Experience ##
The buttons are translated.

## Actual Experience ##
The buttons are still in English.

## Additional Context ##
![image](https://user-images.githubusercontent.com/54055206/77732961-f773ca00-7040-11ea-90ac-ed2503df4c00.png)

**Comment by v-limu** [comment]
Verified this issue on build master/20200509.2. Fixed.
