### ISSUE TITLE
Display a duplicate queue under one new attached local emulator account when creating one queue under Emulator node

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2773]
**Storage Explorer Version:** 1.13.0
**Build**: [20200331.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3597063)
**Branch**: rel/1.13.0
**Platform/OS:** Windows 10
**Azurite Version:** 3.6.0
**Architecture**: ia32
**Regression From:**  Not a regression

**Steps to reproduce:**
1. Install and run Azurite -> Launch Storage Explorer.
2. Open connect dialog -> Select 'Attach to a local emulator' to add one local emulator account.
3. Expand (Emulator -Default Ports) (Key) node (and make sure local-1(key) node is expanded).
4. Create one queue under (Emulator -Default Ports) (Key) node.
5. Check the created queue under local-1(Key) node.

**Expect Experience:**
The created queue displays well under local-1(Key) node.

**Actual Experience:**
Display a duplicate queue under local-1(Key) node.
![image](https://user-images.githubusercontent.com/41351993/78006655-dcba9180-736f-11ea-94d0-9208dd2c33dd.png)

**More Info:**
The created queue displays well after manually refresh.

**Comment by craxal** [comment]
This has been fixed after moving queues to an extension.
