### ISSUE TITLE
No property 'Shared Access Signature' for queues under one SAS attached account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2774]
**Storage Explorer Version:** 1.13.0
**Build**: [20200331.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3597063)
**Branch**: rel/1.13.0
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS High Sierra
**Architecture**: ia32/x64
**Regression From:**  Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Queues -> Create one queue.
2. Attach the storage account via SAS.
3. Select the queue under the SAS attached storage account.
4. Check its properties on Properties panel.

**Expect Experience:**
Show property 'Shared Access Signature'.
![image](https://user-images.githubusercontent.com/41351993/78016226-19d95080-737d-11ea-8750-c6ba6d0e59ea.png)

**Actual Experience:**
No property 'Shared Access Signature' shows.
![image](https://user-images.githubusercontent.com/41351993/78016678-b3a0fd80-737d-11ea-9946-57fc5dea8c69.png)

**More Info:**
1. This issue also reproduces for tables.
2. For one queue/table that new created under SAS attached account, there displays 'Shared Access Signature' on Actions/Properties panel, but the Shared Access Signature disappears after manually refresh.
3. This issue doesn't reproduce for blob containers/ file shares.

**Comment by craxal** [comment]
This is fixed for queues. I suggest opening a separate bug for tables.

**Comment by v-xianya** [comment]
@craxal 
This issue is fixed on master/[20200428.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3681243&view=results). 
And we opened a separate bug for table: [2904](https://github.com/microsoft/AzureStorageExplorer/issues/2904)
