### ISSUE TITLE
The activity log is too long when pasting one deleted file

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2776]
**Storage Explorer Version:** 1.13.0
**Build**: [20200331.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3597063)
**Branch**: rel/1.13.0
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ macOS High Sierra
**Architecture**: ia32/x64
**Regression From**: Previous release(1.12.0)

**Steps to reproduce:**

1. Select a storage account -> File Shares.
2. Create a new file share -> Upload one file to it -> Copy this file then delete it -> Paste this file.
3. Check the activity log.

**Expect Experience:**
The activity log is concise.

**Actual Experience:**
The activity log is too long.
![image](https://user-images.githubusercontent.com/54055206/78009925-55235180-7374-11ea-84d9-b10de6fd65d5.png)

**More Info:**
1. The activity log shows below in release 1.12.0.
![image](https://user-images.githubusercontent.com/54055206/78009701-01186d00-7374-11ea-94c3-1699bfb014d9.png)

2. The activity log shows below when pasting one **deleted blob**.
![image](https://user-images.githubusercontent.com/54055206/78009782-18575a80-7374-11ea-9993-710b57f704a4.png)

**Comment by JasonYeMSFT** [comment]
The error message directly comes from AzCopy. There isn't much we can do for now.
