### ISSUE TITLE
An error pops up when creating one folder for one file share

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2779]
**Storage Explorer Version:** 1.13.0
**Build**: [20200401.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3600038)
**Branch**: rel/1.13.0
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ macOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Previous release(1.12.0)

**Steps to reproduce:**

1. Expand one storage account -> File Shares.
2. Create a new file share -> Create one new folder.
3. Check the result.

**Expect Experience:**
Succeed to create one folder.

**Actual Experience:**
An error pops up.
![image](https://user-images.githubusercontent.com/54055206/78118765-0b04a380-743a-11ea-8219-a23ca142ce9b.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into rel branch
