### ISSUE TITLE
Unable to sign in

### ISSUE THREAD

**Issue by cwdata** [microsoft/AzureStorageExplorer#278]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Windows 10 build 1803
**Architecture**: x64
**Regression From**: It worked in an older version, don't know which one because it has been replaced

Storage Explorer worked without issues until today. I did 2 things:
1) Upgrade to the latest version
2) Remove my account using the Manage Accounts menu
If I now click on Manage Accounts -> Add Account it opens the web based login form. I go through the process entering my mail address and password and then I get an error in a black bar at the top:
Unable to sign-in: ERR_NOT_IMPLEMENTED

I have a backup (image) of my computer created at a time when everything was still working. 
Obviously I don't want to restore the whole disk.
Can anyone tell me which file(s) I need to restore to add the accounts back to storage explorer?

Thanks,
  Christian

**Comment by MRayermannMSFT** [comment]
Hey @cwdata , are you still facing this issue?

**Comment by cwdata** [comment]
No. I analyzed what was going on using the tools from Sysinternals, located the file which stores the accounts and restored that from a backup. After that I could use Storage Explorer again.

**Comment by dmarlow** [comment]
What's the file? Some people are running into this on version 1.9.0.

**Comment by cwdata** [comment]
I don't remember the exact file but it must be in the directory 
C:\Users\{username}\AppData\Local\.IdentityService
If you have a backup of that directory from a time when it still worked then I'd recommend renaming the current version of this directory and restoring the one from the backup.

**Comment by MRayermannMSFT** [comment]
We've done a lot of work on sign-in since July 2019. If anyone is still having issues, please test against our latest version (as of today, 1.12). If you are still encountering problems with that version, please open a new issue. Thanks.
