### ISSUE TITLE
Move Clone dialog to be using TextInputMessageBox

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#2780]
**Describe the solution you'd like**
Move Clone dialog to be using TextInputMessageBox

**Additional context**
The existing Clone dialog is using its own view/view model and having its own way of validating inputs. We can reduce the maintenance work by moving to use the shared TextInputMessageBox for it.

**Comment by MRayermannMSFT** [comment]
All clones are using the textinput dialog now.
