### ISSUE TITLE
Set 'Open in Portal' as the first action on the context menu for resource groups

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2781]
**Storage Explorer Version:** 1.13.0
**Build**: [20200401.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3600038)
**Branch**: rel/1.13.0
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ macOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand Disks -> Select one resource group.
2. Right click the resource group -> Check its context menu.

**Expect Experience:**
 'Open in Portal' is the first action on the context menu.

**Actual Experience:**
'Open in Portal' is not the first action on the context menu.
![image](https://user-images.githubusercontent.com/41351993/78229006-fb509200-7501-11ea-94ea-e2346b91b79e.png)

**More Info:**
1. 'Open in Portal' is the first action on the context menu for storage account/ Cosmos DB account/ Data Lake Storage Gen1.
![image](https://user-images.githubusercontent.com/41351993/78228993-f7247480-7501-11ea-9dd8-cc3b3bdb7950.png)

**Comment by JasonYeMSFT** [comment]
We don't plan to promote "Open in Portal". We want to let people try using it in Storage Explorer first.
