### ISSUE TITLE
Remove 'Detach' action for attached items under Quick Access node

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2782]
**Storage Explorer Version:** 1.13.0
**Build**: [20200401.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3600038)
**Branch**: rel/1.13.0
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ macOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Attach one storage account via SAS.
2. Add the attached storage account to Quick Access.
3. Check the context menu of the attached storage account under Quick Access node.

**Expect Experience:**
No 'Detach' action displays.

**Actual Experience:**
The action 'Detach' displays well.

**More Info:**
1. This issue doesn't reproduce for SAS attached **blob container and file shares.**
2. This issue also reproduces for SAS attached **queues and tables**.
3. This issue also reproduces for Name & Key **attached storage accounts**.
4. Related bug: [1413](https://github.com/microsoft/AzureStorageExplorer/issues/1413)

**Comment by JasonYeMSFT** [comment]
Queue will be fixed in 1.14.0. We will adjust when the Table and Storage Account nodes will be fixed.

**Comment by craxal** [comment]
Work is done for queues.

**Comment by v-xianya** [comment]
Verified this issue on build master/[20200522.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3750769&view=results).
1. Queue is fixed.
2. This issue still reproduces for **Storage account and Table**.  So we keep this bug open.

**Comment by MRayermannMSFT** [comment]
@v-xianya can you open an issue each for storage account and table? Thanks.

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT 
Sure. We opened issues for storage accounts and tables. Issues number: [3063](https://github.com/microsoft/AzureStorageExplorer/issues/3063),[3064](https://github.com/microsoft/AzureStorageExplorer/issues/3064).
