### ISSUE TITLE
'PartitionKey' & 'RowKey' & 'Timestamp' properties are editable in Edit Entity dialog

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2783]
**Storage Explorer Version:** 1.13.0
**Build**: [20200401.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3600038)
**Branch**: rel/1.13.0
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Previous release(1.12.0)

**Steps to reproduce:**

1. Expand one storage account -> Tables.
2. Create a new table -> Add one entity -> Edit this entity.
3. Check the Edit Entity dialog.

**Expect Experience:**
'PartitionKey' & 'RowKey' & 'Timestamp' properties are not editable.
![image](https://user-images.githubusercontent.com/54055206/78229818-1243b400-7503-11ea-9ef7-361cd371debc.png)

**Actual Experience:**
'PartitionKey' & 'RowKey' & 'Timestamp' properties are editable.
![image](https://user-images.githubusercontent.com/54055206/78232036-466ca400-7506-11ea-8f38-8c43be3c00c7.png)

**Comment by craxal** [comment]
Merged to rel/1.13.0.
