### ISSUE TITLE
Take about 50 seconds to throw an error when using an empty name to rename an ADLS Gen1 folder 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2784]
**Storage Explorer Version:** 1.13.0
**Build**: [20200401.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3600038)
**Branch**: rel/1.13.0
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ macOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand 'Data Lake Storage Gen1(Preview)' node -> Open one file system.
2. Upload one folder to it.
3. Rename the folder with an empty name -> Observe the result.

**Expect Experience:**
Fail to rename the folder with an empty name and throw an error immediately.
**Screenshot in Portal:**
![image](https://user-images.githubusercontent.com/41351993/78230519-04426300-7504-11ea-86af-2439bbb7c40b.png)

**Actual Experience:**
1. No error notification pops up when pressing space key directly and 'Rename' button is enabled.
2. Take about 50 seconds to throw the below error.
![image](https://user-images.githubusercontent.com/41351993/78230730-55525700-7504-11ea-9b96-62c888bbe0f4.png)

**More Info:**
1. Can't create one folder with an empty name.
![image](https://user-images.githubusercontent.com/41351993/78230794-6ef39e80-7504-11ea-81e6-b87de41cb114.png)
2. Succeed to rename a subfolder using an empty name.
![image](https://user-images.githubusercontent.com/41351993/78230838-803cab00-7504-11ea-98e9-6ba938afb65b.png)

**Comment by JasonYeMSFT** [comment]
ADLS Gen1 is on life support. We won't do non-critical work on it.
