### ISSUE TITLE
The editor displays strange after clicking ‘previous editor’ when one service temporarily open

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2785]
**Storage Explorer Version:** 1.13.0
**Build**: [20200401.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3600038)
**Branch**: rel/1.13.0
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one storage account -> Blob Containers.
2. Temporarily open one blob container like this: ![image](https://user-images.githubusercontent.com/54055206/78230756-626f4600-7504-11ea-979e-c33f7c7f30c0.png)
3. Click 'View' -> Click 'Previous Editor'.
4. Check the editor.

**Expect Experience:**
The editor is closed.

**Actual Experience:**
The editor displays strange.
![image](https://user-images.githubusercontent.com/54055206/78229509-acefc300-7502-11ea-924b-429c56361a0d.png)

**Comment by JasonYeMSFT** [comment]
We would expect the button to be disabled or simply do nothing.

**Comment by v-limu** [comment]
Verified on build 20200702.2, The actual result shows as below:
![image](https://user-images.githubusercontent.com/54055206/86324000-71cf6e00-bc70-11ea-944b-9ae89cf13088.png)

**Comment by v-limu** [comment]
Verified on build 20200722.6. This issue has been fixed. So close it.
