### ISSUE TITLE
Display 'This property must have a value' for PartitionKey when typing one value and deleting it

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2787]
**Storage Explorer Version:** 1.13.0
**Build**: [20200403.15](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3608332)
**Branch**: rel/1.13.0
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ macOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Tables.
2. Create a new table -> Click 'Add' -> Type a value ParitionKey's Value box then delete it.
3. Check the result on the Value box.

**Expect Experience:**
No red border shows.

**Actual Experience:**
1. Show a red border for the box.
2. Display 'This property must have a value' in the value box.
![image](https://user-images.githubusercontent.com/41351993/78339160-9dd24900-75c6-11ea-84f8-b549f0c4e810.png)

**More Info:**
This issue also reproduces for the RowKey.

**Comment by JasonYeMSFT** [comment]
This is by design. PartitionKey and RowKey cannot be empty. The reason we don't initially show red border is that we don't want to give an erroneous view at the beginning.
