### ISSUE TITLE
Succeed to delete one adls gen2 folder which contains leased blobs

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2790]
**Storage Explorer Version:** 1.13.0
**Build**: [20200403.15](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3608332)
**Branch**: rel/1.13.0
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a new blob container -> Upload one folder which contains blobs.
3. Acquire lease for blobs -> Try to delete the folder.
4. Check the result.

**Expect Experience:**
Fail to delete the folder.

**Actual Experience:**
Succeed to delete the folder.

**Comment by craxal** [comment]
Spoke with the platform team, and this is by design. Folders are like containers, and containers can be deleted even if some of its contents are leased.

**Comment by v-xianya** [comment]
Hi @craxal Thanks for your reply. Could you help to see the below two points?😀
1. For one regular blob container, Fail to delete folders which contain leased blobs. 
![image](https://user-images.githubusercontent.com/41351993/78621940-5d204b80-78b6-11ea-95ee-9d3a237ab566.png)

      **Error Info in AzCopy Log:**
      There is currently a lease on the blob and no lease ID was specified in the request.

2. The comment for the related bug: [2332](https://github.com/microsoft/AzureStorageExplorer/issues/2332)

**Comment by craxal** [comment]
@v-xianya Regular blob containers do not contain real folders. When you are deleting a "folder", you are actually iterating over a list of _individual_ blobs to delete. You cannot delete an individual blob if it has an active lease, so that's why you get the expected failure in the above case. For containers themselves or real folders in ADLS Gen 2 containers, this does not apply.
