### ISSUE TITLE
Display a duplicate directory after pasting a folder to one adls gen2 blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2791]
**Storage Explorer Version:** 1.13.0
**Build**: [20200403.15](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3608332)
**Branch**: rel/1.13.0
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Previous releases (1.12.0)

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Create a new blob container -> Create a new folder and upload one file to the folder.
3. Copy the folder and paste it to one ADLS Gen2 blob container.
4. Check the directory hierarchy of the pasted folder.

**Expect Experience:**
The directory hierarchy of the pasted folder shows normal.
![image](https://user-images.githubusercontent.com/41351993/78350202-5f915580-75d7-11ea-8e8e-741738554c21.png)

**Actual Experience:**
Display a duplicate folder in directory hierarchy.
![image](https://user-images.githubusercontent.com/41351993/78349984-032e3600-75d7-11ea-993c-d002c70a5de1.png)

**Comment by v-limu** [comment]
Verified on build 20200408.6. This issue has been fixed.
