### ISSUE TITLE
Write-only SAS permissions for Azure Storage Explorer (Feature Request) 

### ISSUE THREAD

**Issue by skanalytic** [microsoft/AzureStorageExplorer#2793]
**Is your feature request related to a problem? Please describe.**
I am still experiencing an issue with 'WRITE ONLY' SAS tokens on Azure Storage Explorer. If I create an SAS token with 'read', 'list', 'write' (rlw) then I can connect to my Azure File Storage account and upload/download files no problem, but if I follow this exact same process without 'read' permissions - so just list and write (lw) - then I can still connect to the account but not longer upload (even though I should be able to with 'write').

I verified this issue does not exist using the same SAS token on Azcopy (e.g. with just 'wl' permissions i can upload but not download files) so I think it is a specific bug with Azure Storage Explorer.

**Describe the solution you'd like**
When you create a SAS token with only 'write' and 'list' permissions, then you can connect this to Azure Storage Explorer and this will allow you to see files and upload new files, but not to download files from your storage account to local. The use case here is that we can provide SAS tokens to our clients to allow them to transfer us data using the Storage Explorer GUI, but have the added security feature that even if their SAS token is intercepted, then malicious parties cannot actually download client's data. 

**Describe alternatives you've considered**
Currently I get around this by asking clients to use AZCOPY instead which does allow this write-only feature (though is not suitable for non-techy clients), or give them a SAS token for Storage Explorer but limit the SAS expiry date to limit the security risk. Niether of these are of course ideal. 

**Additional context**
This issue has been brought up by other users here: https://github.com/microsoft/AzureStorageExplorer/issues/305

**Comment by craxal** [comment]
@skanalytic In #305 you mentioned that Azure suggested you use write-only SAS in Storage Explorer. That seems incorrect to me, so we may need to inform the Azure portal. Can you give me any more context, such a steps to follow, so that I can verify this?

**Comment by skanalytic** [comment]
@craxal, sure thanks for getting back to me so quickly. It is not that it 'suggests' it per-se, but that it does allow you to create a SAS token with write but without read permissions, but then does not behave that way when used with Storage Explorer. Steps on Azure portal to verify this:

1. log in to the Azure portal
2. select ‘storage account’ and select a storage account you want to create a SAS token for
3. select ‘Shared Access Signature’ from the panel on the left
4. define your SAS parameters (one of which is 'permissions' and allow you to tick/untick any combination of: Read, Write, Delete, List, Add, Create, Update, Process

![image](https://user-images.githubusercontent.com/37375099/78641543-4f17fe00-78a9-11ea-8d71-c78a9cff74f9.png)

And just to be clear, this is also the permissions it suggests you have once you add this SAS token on Storage Explorer:

![image](https://user-images.githubusercontent.com/37375099/78641780-a28a4c00-78a9-11ea-9756-8a51d181a283.png)

Hope that helps,

**Comment by skanalytic** [comment]
Also @JasonYeMSFT to your point, I think it is worth saying that the use-case that I am hoping for is really just to stop data being "downloaded" (i.e. the contents of the files being downloaded from cloud storage to local) for security reasons (e.g. if their SAS token is compromised they can still upload data to us, but malicious actors cannot use that token to steal that data), rather than have explicitly 'write-only' or 'not read' permissions. I am not sure if that makes anything easier but worth bearing in mind.

**Comment by MRayermannMSFT** [comment]
At this point, I think our support for write only SAS is good enough that I'm going to close this issue. We are still having discussions with the AzCopy team about getting overwrite detection working in that use case, but for now we do warn you that we won't check for overwrites if your SAS is write only. @skanalytic I encourage you to try the experience in our current version (1.14.x or later) and let us know in a new issue if there's any improvements you would like made. Thanks!
