### ISSUE TITLE
Save dialog on Mac hangs when selecting file format for table export

### ISSUE THREAD

**Issue by go-shinyashiki** [microsoft/AzureStorageExplorer#2794]
**Storage Explorer Version**: latest
**Build Number**: No checked
**Platform/OS**: MacOS 10.15.4 Catalina
**Architecture**: x64
**Regression From**:  No checked

## Bug Description ##
The issue occurs when selecting the format as "CSV with type annotations (comma delimited)".

## Steps to Reproduce ##
1. Start Storage Explorer and open a table.
2. Click Export in the toolbar.
3. Select format as "CSV with type annotations (comma delimited)".

## Expected Experience ##
"CSV with type annotations (comma delimited)" format can be exported.

## Actual Experience ##
The save file dialog temporarily freezes.
Cannot change the file name and cannot click Save.
Click Cancel and the dialog disappears after about 20 seconds.

## Additional Context ##
None

**Comment by MRayermannMSFT** [comment]
We can't repro this on 1.12. Can you tell us what exact version you are on? Where are you exporting the file too?

**Comment by go-shinyashiki** [comment]
Dear All

Thank you for your reply.
The version of Storage Explorer that you are using is 1.12.0 Japanese.
There is a problem with both the desktop and download.

Regards,
Go

**Comment by craxal** [comment]
@go-shinyashiki Thank you for reporting this issue. I was able to reproduce the issue.

Unfortunately, I'm not sure what can be done, as this dialog is a system dialog. It's possible this is a bug in either Electron or even Catalina. We are several major versions behind the the current version of Electron, so I wouldn't be surprised if changes to Catalina don't jive well with older versions of Electron.

I think the first step is to upgrade Electron. Our upgrade is blocked by electron/electron#22973, but fortunately, a solution has been found. So I expect we can revisit this once the upgrade has been made.

**Comment by craxal** [comment]
Electron has been updated, and I'm not seeing the hang anymore.

I should note, though, that we also removed the "CSV with type annotations" format. Instead, you will be able to control type annotations with the **Transfers** > **Table Import/Export** > **Export Type Annotations** setting. See #2104 for why this was done.
