### ISSUE TITLE
No corresponding tab shows for release notes after opening it again once it was closed with other tabs

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2795]
**Storage Explorer Version:** 1.13.0
**Build**: [20200403.17](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3609789&view=results)
**Branch**: rel/1.13.0
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Previous releases (1.12.0)

**Steps to reproduce:**
1. Select one service -> Click 'Open New Tab'.
2. Click 'Help' -> Select 'View Release Notes'.
3. Right click the Release Notes tab -> Click 'Close All'.
4. Repeat step2 -> Check the result.

**Expect Experience:**
The tab of release notes shows well.
![image](https://user-images.githubusercontent.com/41351993/78651290-b6a66b80-78f2-11ea-9c13-88f8e4c0436d.png)

**Actual Experience:**
No release notes tab shows.
![image](https://user-images.githubusercontent.com/41351993/78651302-bad28900-78f2-11ea-9ede-e5640e5056a0.png)

**More Info:**
Attachment:
https://web.microsoftstream.com/video/9fe5a3ff-0400-86e9-a912-f1ea7880746a

**Comment by MRayermannMSFT** [comment]
@v-xianya I've merged a fix into rel. It will be in tonight's build. Please do lots of testing around close tab, close all tabs, close other tabs. Thanks!

**Comment by v-xianya** [comment]
@MRayermannMSFT Got it, we will do some testing around closing tab. 😉
