### ISSUE TITLE
Fail to download an existing blob

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2796]
**Storage Explorer Version:** 1.13.0
**Build:** [20200403.17](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3609789)
**Branch**: rel/1.13.0
**Platform/OS:** Windows 10
**Architecture**: ia32
**Regression From:** Previous release(1.12.0)

**Steps to reproduce:**

1. Expand one storage account -> Blob Containers.
2. Create one new blob container -> Upload one blob to it -> Download this blob to specify folder.
3. Download this blob to same folder again -> Select 'Overwrite' in the conflict dialog -> Apply.
4. Check the result.

**Expect Experience:**
Successfully overwrite the blob.

**Actual Experience:**
Fail to download the blob
![image](https://user-images.githubusercontent.com/54055206/78650618-c70a1680-78f1-11ea-80bd-16894fb7cd4b.png)

**More Info:**

1. This issue doesn't reproduce on Linux and Mac.
2. AzCopy Log File:
`2020/04/07 09:07:35 ERR: [P#0-T#0] DOWNLOADFAILED: https://arm0402.blob.core.windows.net/test/New%20Text%20Document.txt?se=2020-04-08t07%3A04%3A13z&sig=-REDACTED-&sp=rwdlacup&srt=sco&ss=btqf&st=2020-04-07t07%3A04%3A13z&sv=2019-02-02 : 000 : File Creation Error destination file has no known flags that could cause issue (current set: 20) and azcopy was unable to clear the flag(s), so access will be denied: The process cannot access the file because it is being used by another process.
   Dst: %5C%5C?\C:\Users\vlimu\Downloads\donwload\DownloadBlob\New Text Document.txt`

**Comment by v-xianya** [comment]
Verified this issue on build [20200408.10](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3622149). Fixed.
