### ISSUE TITLE
It's hard to see which tab is selected in Dark theme

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2799]
**Storage Explorer Version:** 1.13.0
**Build**: [20200403.17](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3609789&view=results)
**Branch**: rel/1.13.0
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Not a regresssion

**Steps to reproduce:**
1. Launch Storage Explorer -> Change the theme to Dark.
2. Open serval tabs -> Select one tab.
3. Check whether it is easy to see which tab is selected or not.

**Expect Experience:**
It's easy to see which tab is selected.

**Actual Experience:**
It's hard to see the current selected tab.
![image](https://user-images.githubusercontent.com/41351993/78654088-a55f5e00-78f6-11ea-99fb-88fa0ab2a1c4.png)

**Comment by MRayermannMSFT** [comment]
As far as we know these pass color guidelines. Won't fix.
