### ISSUE TITLE
I installed the 64-bit installer but got a 32-bit version installed

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/AzureStorageExplorer#28]
**Storage Explorer Version:**
1.0

**OS Version:**
win64

**Steps to Reproduce:**

1.
https://XXX.visualstudio.com/XXX/_build/index?buildId=1510324&_a=summary&tab=artifacts
![image](https://user-images.githubusercontent.com/6913354/37857973-e33382b4-2ebc-11e8-9b64-3cd1193a3a45.png)

2.
![image](https://user-images.githubusercontent.com/6913354/37857978-eb877218-2ebc-11e8-87e5-f1b82c8909b8.png)

**Comment by MRayermannMSFT** [comment]
The platform string is "technically" correct, as NodeJS reports Windows as win32, regardless of architecture. We should add a new line to this dialog for architecture.

**Comment by StephenWeatherford** [comment]
win32 != windows. Who cares what Node.js reports.

**Comment by MRayermannMSFT** [comment]
We'll also be replacing NodeJS platform names with more meaningful names (Windows, macOS, Linux)

**Comment by MRayermannMSFT** [comment]
Changes have been merged.
