### ISSUE TITLE
Feature Request: Table Entity Copy

### ISSUE THREAD

**Issue by TheEyeOfBrows** [microsoft/AzureStorageExplorer#280]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Windows
**Architecture**: ia32
**Regression From**: N/A

#### Steps to Reproduce: ####
1. Open storage table which has populated data entities.
2. Select an entity/row.
3. Observe there is no way to duplicate/clone/copy an entity.

#### Expected Experience: ####
I expect a way to create a new entity based on a current entity.
I imagine a duplicate/copy command would open the "Edit Entity" window, already populated with the properties, property types, and values from the selected entity.
A user MUST update the PartitionKey and/or RowKey before submitting the new entity.

#### Actual Experience: ####
The user must either:
* Create the new entity from scratch.
* Export the single entity, edit the CSV in a separate editor, and import the new entity.

**Comment by ianpowell2017** [comment]
Hi

I'd love to see the option to download an entire table to csv format.
Oh and on the mac as well.

Thanks

**Comment by TheEyeOfBrows** [comment]
@ianpowell2017 
> I'd love to see the option to download an entire table to csv format.

The export button already exports all entities in a table by default (not just what's cached).
You have a choice of exporting as typed CSV, or untyped CSV.
At least, that's how it is in version 1.4.0 for windows.

**Comment by jinglouMSFT** [comment]
Due of https://github.com/microsoft/AzureStorageExplorer/issues/2547
