### ISSUE TITLE
Using snap package storage explorer have installed on linux system.

### ISSUE THREAD

**Issue by prasannakalan** [microsoft/AzureStorageExplorer#2801]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:

**Comment by prasannakalan** [comment]
But still no clue to connect from linux box? anyways?

**Comment by prasannakalan** [comment]
@

> **Storage Explorer Version**:
> **Build Number**:
> **Platform/OS**:
> **Architecture**:
> **Regression From**:
> 
> ## Bug Description
> ## Steps to Reproduce
> ## Expected Experience
> ## Actual Experience
> ## Additional Context

**Comment by MRayermannMSFT** [comment]
@prasannakalan can you elaborate on what you're asking? We're a bit confused right now.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you're still having problems.
