### ISSUE TITLE
The editor shows blank when copying one blob container to one name & key attached account 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2804]
**Storage Explorer Version:** 1.13.0
**Build**: [20200408.10](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3622149)
**Branch**: rel/1.13.0
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release(1.12.0)

**Steps to reproduce:**

1. Attach one Non-ADLS Gen2 storage account via name & key.
2. Expand the attached storage account -> Blob Containers.
3. Paste one blob container to it.
4. Check the editor.

**Expect Experience:**
The editor shows well.

**Actual Experience:**
The editor shows blank.
![image](https://user-images.githubusercontent.com/54055206/78765189-3b0ff180-79ba-11ea-9dbf-fdcda3fc1c35.png)

**Comment by v-xianya** [comment]
This issue is fixed on build [20200409.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3625874). So we close it.
