### ISSUE TITLE
An error pops up when clicking one new created blob container under Quick Access account

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2806]
**Storage Explorer Version:** 1.13.0
**Build**: [20200408.10](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3622149)
**Branch**: rel/1.13.0
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release(1.12.0)

**Steps to reproduce:**

1. Select one storage account -> Add it to Quick Access
2. Expand the account under QA-> Blob Containers.
3. Create a new blob container (the blob container auto open) -> Click the blob container.
4. Check the result.

**Expect Experience:**
No error shows.

**Actual Experience:**
An error pops up.
![image](https://user-images.githubusercontent.com/54055206/78764365-051e3d80-79b9-11ea-99cc-0010fb584d02.png)

**More Info:**

1. This issue also reproduces when clicking one new created file share/ queue/ table under QA account.
2. This issue also reproduces after copying/ cloning one file share to one QA account.
3. This issue doesn't reproduce after closing the auto opened service.

**Comment by v-xianya** [comment]
This issue is fixed on build [20200409.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3625874). So we close it.
