### ISSUE TITLE
No time shows in the name of file share snapshots 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2807]
**Storage Explorer Version:** 1.13.0
**Build**: [20200408.10](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3622149)
**Branch**: rel/1.13.0
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release(1.12.0)

**Steps to reproduce:**

1. Expand one storage account -> File Shares.
2. Create a new file share -> Create Snapshot -> View Share Snapshots.
3. Check the snapshot name.

**Expect Experience:**
The snapshot name shows well.
![image](https://user-images.githubusercontent.com/54055206/78763947-6d205400-79b8-11ea-8b7e-fc6c772f47f1.png)

**Actual Experience:**
No time shows in the snapshot name.
![image](https://user-images.githubusercontent.com/54055206/78763993-7dd0ca00-79b8-11ea-864a-6b34ba1be93b.png)

**Comment by v-xianya** [comment]
This issue is fixed on build[ 20200409.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3625874). So we close it.
