### ISSUE TITLE
Only display ‘More’ on the toolbar for tabs opened in quick succession

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2809]
**Storage Explorer Version:** 1.13.0
**Build:** [20200408.10](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3622149)
**Branch**: rel/1.13.0
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Open at least two containers tab via double clicking in quick succession.
3. Check the toolbar of the opened tabs except the last opened tab.

**Expect Experience:**
The actions display well on the toolbar. 

**Actual Experience:**
Only display ‘More’ on the toolbar. 
![image](https://user-images.githubusercontent.com/41351993/78764067-9b059880-79b8-11ea-9813-27be9a381815.png)

**More Info:**
This issue also reproduces for File shares/Tables/Queues.

**Comment by craxal** [comment]
This repros for iframe-based editors, but not for webview-based editors. We should consider migrating older editors to the webview environment.

**Comment by craxal** [comment]
Fixed in tandem with #2398.
