### ISSUE TITLE
Device Authentification required

### ISSUE THREAD

**Issue by franzbull** [microsoft/AzureStorageExplorer#2811]
**Storage Explorer Version**:  1.12.0
**Build Number**:  20200116.10
**Platform/OS**:  Linux Ubuntu 18.04 LTS
**Architecture**:  x64
**Regression From**:  

## Bug Description ##

Following Message appears when try to login on AD Tenant
{
  "message": "\"AADSTS50097: Device authentication is required.\\r\\nTrace ID: eeea4a25-7d9f-4e94-bd1a-e536e88b1a00\\r\\nCorrelation ID: 3e5c3c89-9a96-41c3-8691-78bbb9313904\\r\\nTimestamp: 2020-04-08 16:02:58Z\""
}

Remark the same works from Azure File Explorer 1.12.0 OS Win10 from the same hw client

## Additional Context ##
 owner access for AD Tenant not available

**Comment by MRayermannMSFT** [comment]
Can you try enabling the MSAL setting? Go to settings (gear icon on the left) -> application -> sign-in -> Enable Microsoft Authentication Library Preview. After that, try signing in again.

**Comment by franzbull** [comment]
Hi @MRayermannMSFT ,
thanks for the hint, it works ;O)
