### ISSUE TITLE
Bug in datetime picker

### ISSUE THREAD

**Issue by kalatchev** [microsoft/AzureStorageExplorer#2812]
**Storage Explorer Version**: 1.12.0
**Build Number**: 20200116.10
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  Dont' know

## Bug Description ##
Datetime picker in Manage Access Policies window is not functioning properly. When you increment or decrement value of hour for example (via keyboard), the value of day is also changed. Sometimes, changing the value of hours, AM/PM and/or day are also changed. And finally, if I adjust 11:59 PM, I'm actually getting 10:59, at least that what is seen when I'm getting shared access signature

## Steps to Reproduce ##
1. On Blob container, right mouse click, Manage Access Policies.
2. Add new policy
3. Try to adjust date and time with keyboard (up and down arrows)

![AzSEbug](https://user-images.githubusercontent.com/10154711/78853398-7694d500-7a27-11ea-8ca0-2fe44be9b796.gif)

**Comment by JasonYeMSFT** [comment]
Interesting, our datetime picker is the built-in datetime picker of chromium. Let me see if the bug is fixed with a higher chromium version.

**Comment by MRayermannMSFT** [comment]
Investigate in 1.14 go from there.

**Comment by MRayermannMSFT** [comment]
Fix merged into master for 1.14
