### ISSUE TITLE
The path for one opened emulator item is incorrect 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2813]
**Storage Explorer Version:** 1.13.0
**Build:** [20200409.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3625874)
**Branch**: rel/1.13.0
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Install and start Azurite -> Launch Storage Explorer.
2. Expand Local & Attached -> Storage Accounts -> (Emulator - Default Ports) (Key) -> Blob Containers.
2. Create one blob container -> Hover over the opened tab and check the path.

**Expect Experience:**
The path is correct.
 `(Emulator - Default Ports) (Key)`

**Actual Experience:**
The path is incorrect.
![image](https://user-images.githubusercontent.com/41351993/78874724-64df1c00-7a7f-11ea-931c-dc26ec2982a9.png)

**Comment by MRayermannMSFT** [comment]
This is by design. The key isn't part of the name. It's just extra info we slap on the end.

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT Thank you for the sharing.
