### ISSUE TITLE
The corresponding tab doesn't auto open when pasting one blob container to Emulator account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2816]
**Storage Explorer Version:** 1.13.0
**Build:** [20200409.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3625874)
**Branch**: rel/1.13.0
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS High Sierra
**Architecture**: ia32/x64
**Emulator version:** 5.10.0
**Regression From:** Not a regression

**Steps to reproduce:**
1. Start emulator -> Launch Storage Explorer.
2. Expand one non-ADLS Gen2 storage account -> Blob Containers.
3. Create one blob container -> Copy and paste it to emulator account.
4. Check whether the pasted blob container opens or not.

**Expect Experience:**
The pasted blob container auto opens.

**Actual Experience:**
The pasted blob container doesn't auto open.

**More Info:**
1. This issue also reproduces when cloning one blob container under Emulator node.
2. The renamed/ pasted table doesn't auto open on the right side.

**Comment by MRayermannMSFT** [comment]
Closing for now. Emulator code is still on JS code, but will eventually be moved to AzCopy.
