### ISSUE TITLE
File Upload Immediately Fails If I set Throttle speed

### ISSUE THREAD

**Issue by schellem** [microsoft/AzureStorageExplorer#2818]
**Storage Explorer Version**: 1.12.0
**Build**: 20200116.10
**Platform/OS**: Windows 10
**Architecture**: x64

AzCopy trashes my network when uploading large files,so I am trying to use the newer throttle feature to slow it down. When I set a max transfer rate speed I get the following error

UnexpectedQuit (used SAS, discovery not completed)

If I remove the throttle speed setting I get no error but my network is trashed when uploading a large file.

## Steps to Reproduce ##
Set a Maximum Transfer Rate under Settings>Transfers

## Expected Experience ##
Be able to upload a larger file

## Actual Experience ##
Get this error. UnexpectedQuit (used SAS, discovery not completed)

**Comment by MRayermannMSFT** [comment]
@schellem can you do two things for us?

1. Copy and paste the AzCopy command here so we can make sure the setting is being passed to AzCopy correctly. Please redact the SAS from the command before posting.
2. Share the AzCopy log file (if there is one). You can find the log files at C:/users/your username/.azcopy

**Comment by schellem** [comment]
I'm not using AzCopy, I'm using Storage Explorer. I just run ASE again to get a current uncluttered log, I see the error but no new log file is generated. I have pasted the log file from 4/9 that appears to have error info in it.

[3df7526a-164c-164b-4b1d-f94a101a6ccd.log](https://github.com/microsoft/AzureStorageExplorer/files/4470999/3df7526a-164c-164b-4b1d-f94a101a6ccd.log)

**Comment by MRayermannMSFT** [comment]
@schellem yes, but Storage Explorer uses AzCopy behind the scenes! So when you're running the upload, there should be the action/link/text "Copy AzCopy Command to Clipboard". Click on that to get the AzCopy command. Don't forget to redact the SAS from the command before posting.

**Comment by schellem** [comment]
Please clarify what ‘redact the SAS from the command before posting’ means, I see nothing in the copied data labeled with SAS.

**Comment by harshithjv** [comment]
@MRayermannMSFT I get same "UnexpectedQuit" error while deleting.

![image](https://user-images.githubusercontent.com/809278/84037697-93646f00-a9bc-11ea-945c-a29bf4aa4225.png)


AzCopy command output:
`$env:AZCOPY_CRED_TYPE = "Anonymous";
./azcopy.exe remove "http://10.0.0.19:18888/devstoreaccount1/test/Sada-1.jpg?se=2020-07-08T13%3A30%3A39Z&sp=rdl&sv=2018-03-28&sr=c&sig=qVs5pqaH%2FVDnKh%2FnR53bxH8RDJJJbWPg3xyQKuHmvuQ%3D" --recursive
$env:AZCOPY_CRED_TYPE = "";`

I have installed Azurite inside VM on Ubuntu 18.04.4 OS on VirtualBox. Running it with following command:

`$  azurite --silent --location ~/.azurite/ --debug ~/.azurite/debug.log --blobHost 0.0.0.0 --blobPort 18888 --queueHost 0.0.0.0 --queuePort 18889 -L`

My host system in Windows 10 and running 'Microsoft Azure Storage Explorer' tool. The above screenshot is from same tool. The connection was successful and modified connection string is:
`DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://10.0.0.19:18888/devstoreaccount1;QueueEndpoint=http://10.0.0.19:18889/devstoreaccount1;`


On click of details link in the link gives only this much:
![image](https://user-images.githubusercontent.com/809278/84038343-71b7b780-a9bd-11ea-9ad8-16e7c05ff815.png)


Please help ....

**Comment by MRayermannMSFT** [comment]
@harshithjv we've opened a new issue for what you're seeing. I have some questions for you there.

**Comment by MRayermannMSFT** [comment]
@schellem I took another look at your log. Can you try changing network concurrency to "Adjust dynamically"?

<img width="615" alt="image" src="https://user-images.githubusercontent.com/21112697/86625635-40111c80-bf7a-11ea-91bb-ad182f41b14c.png">

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having issues, please open up a new issue, thanks.
