### ISSUE TITLE
Rename attached containers

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#2819]
**Is your feature request related to a problem? Please describe.**
It is annoying to have to perform the whole attach process if I am unsatisfied with the display name of one of my attached nodes.

**Describe the solution you'd like**
A context menu action to allow me rename the display name of the attached node.

**Describe alternatives you've considered**
Nope.

Services supporting attachment:
- [x] Blobs
- [x] Files
- [x] Queues
- [x] Tables
- [x] Storage accounts

**Comment by JasonYeMSFT** [comment]
The Quick Access part is a duplicate of #1372

**Comment by MRayermannMSFT** [comment]
(Edited issue to remove duplicate part)
