### ISSUE TITLE
Keep consistent error descriptions when creating service with an existing name between services

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2823]
**Storage Explorer Version:** 1.13.0
**Build**: [20200410.5](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3629864&view=logs)
**Branch**: rel/1.13.0
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one storage account -> Tables.
2. Create a new table with an existing name.
3. Check the information in the popped dialog.

**Expect Experience:**
Keep consistent error descriptions between services.

**Actual Experience:**
The table's error  is inconsistent with other services.
![image](https://user-images.githubusercontent.com/54055206/78979029-958d8700-7b4d-11ea-8226-c80954e28b3c.png)

**Comment by MRayermannMSFT** [comment]
We have no control over this message.
