### ISSUE TITLE
The error detail is incorrect when changing one blob access tier to 'Archive' under Germany/China account

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2828]
**Storage Explorer Version:** 1.13.0
**Build**: [20200410.14](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3633000)
**Branch**: rel/1.13.0
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Sign in with one Germany account.
2. Expand one GPV2 account -> Blob Containers.
3. Create a new blob container -> Upload one block blob to it.
4. Change the blob access tier to 'Archive'.
5. Check the activity log.

**Expect Experience:**

The error detail is correct like below.
![image](https://user-images.githubusercontent.com/54055206/79112034-3e3b2100-7db0-11ea-8864-72c9fa6d9746.png)

**Actual Experience:**
The error detail is incorrect.
 `The value for one of the HTTP headers is not in the correct format`

**More Info:**
This issue also reproduces for one regular blob under China account.

**Comment by MRayermannMSFT** [comment]
Investigate in 1.14, go from there.

**Comment by JasonYeMSFT** [comment]
Verified on Azure China. Archive tier isn't supported and is grayed out on the portal.
