### ISSUE TITLE
The cloned empty folder displays under file share editor after manually refresh

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2829]
**Storage Explorer Version:** 1.13.0
**Build**: [20200410.14](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3633000)
**Branch**: rel/1.13.0
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Previous release(1.12.0)

**Steps to reproduce:**
1. Expand one storage account -> File Shares.
2. Create one file share -> Create a new empty folder.
3. Try to clone the folder with a valid name -> Check the result.

**Expect Experience:**
The cloned empty folder doesn't display after manually refresh.

**Actual Experience:**
1. Fail to perform the clone action due to Activity log.
2. The cloned folder displays after manually refresh.
![image](https://user-images.githubusercontent.com/41351993/79112333-e5b85380-7db0-11ea-8b8f-225aa42cb386.png)

**Comment by v-xianya** [comment]
Verified this issue on the build  20200720.3. The behaviors as below:
1. Display a successful  Activity log.
![image](https://user-images.githubusercontent.com/41351993/88040975-4c04fd00-cb7c-11ea-8300-f0cfa12b2c24.png)

2. The cloned folder displays after manually refresh.

**Comment by JasonYeMSFT** [comment]
This should have been fixed now.

**Comment by v-xianya** [comment]
Verified this issue on build master 20200715.1.

**Current behavior:**
Show a successful activity log and the cloned empty folder displays on the editor.

**Comment by JasonYeMSFT** [comment]
@v-xianya the current behavior is the expected behavior.

**Comment by v-xianya** [comment]
Hi @JasonYeMSFT Thank you for the confirmation!
