### ISSUE TITLE
Cosmos DB - Add "Execute" to Stored Procedures

### ISSUE THREAD

**Issue by AndriyGorda** [Microsoft/AzureStorageExplorer#283]
Hi team,

You already did brilliant job, but we need more :)

Could you please make it possible to execute Cosmos DB Stored Procedures?

Two reasons:
1. Now the experience is incomplete. 
What's the point in using two tools - one to create stored procedure and the other one to execute it?

2. Document DB Studio which is able to execute procedures is not the best tool from usability prospective.
Having this feature done in Azure Storage Explorer we can get rid of Studio finally.

Another thanks for the great software, team!

Andriy

**Comment by ziyel** [comment]
@AndriyGorda , Thanks a lot for the feedback.
We plan to support the `Execute` for stored procedure in next release.

**Comment by AndriyGorda** [comment]
Good news, many thanks!

**Comment by ziyel** [comment]
We will support execute stored procedure in version `1.3.0`. Please try it and open new issues for feedback.

**Comment by MRayermannMSFT** [comment]
@ziyel , did this make 1.3.0?

**Comment by ziyel** [comment]
@MRayermannMSFT , we added the feature in 1.3.0.

**Comment by MRayermannMSFT** [comment]
Ok, then closing the issue. Thank you. 😄
