### ISSUE TITLE
When download in progress confirm program exit

### ISSUE THREAD

**Issue by alvipeo** [microsoft/AzureStorageExplorer#2830]
I'm downloading a big blob container to my machine which is going to take hours to finish. But then I close the app and ... I lost all my download progress because the app has just been closed. Please ask for a confirmation when there's download/upload in progress!

Thanks.

**Comment by MRayermannMSFT** [comment]
This has been merged into main for 1.21. Now, if you have any not-completed activities, you will be asked if you really want to exit.
