### ISSUE TITLE
Keep consistent behaviors between ADLS Gen2 and file shares for one new created folder which name ended with dots

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2831]
**Storage Explorer Version:** 1.13.0
**Build:**  [20200414.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3639109)
**Branch:** rel/1.13.0
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one ADLS Gen2 storage account.
2. Expand blob containers and File Shares separately.
3. Create a new blob container and file share.
4. Create a new folder with name end with dots separately under blob container and file share.
5. Check the folders name separately between blob container and file shares.

**Expect Experience:**
Keep consistent behaviors for the folder name.

**Actual Experience:**
Show inconsistent behaviors for the folder name.
![image](https://user-images.githubusercontent.com/41351993/79209660-507f9280-7e76-11ea-9395-e9d0d35dc1b7.png)

**More Info:**
The dots in the file share folder name disappears after manually refresh.

**Comment by MRayermannMSFT** [comment]
The final behavior actually seems pretty consistent. Something is trimming off the dots for *ALL* services. The inconsistency comes from the fact File Shares are doing a "insert this folder" into the table after creating a new folder, while gen2 is refreshing the view.

I think we'll need to investigate this "trimming dots" issue another time.

Related; https://github.com/microsoft/AzureStorageExplorer/issues/2833

**Comment by MRayermannMSFT** [comment]
Tell the platform about this.

**Comment by MRayermannMSFT** [comment]
Closing this (the inconsistent behavior between file shares and blobs) bug as won't fix. Leaving #2833 open.
