### ISSUE TITLE
No info bar prompts when opening Storage Explorer with one deleted item direct link

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2832]
**Storage Explorer Version:** 1.13.0
**Build**: [20200414.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3639109)
**Branch**: rel/1.13.0
**Platform/OS:** macOS High Sierra
**Architecture**: x64
**Regression From:** Previous release(1.12.0)

**Steps to reproduce:**
1. Launch Storage Explorer -> Blob Containers.
2. Select one blob container -> Copy its direct link then delete the blob container.
3. Paste the copied direct link to browser -> Open Storage Explorer via the link. 
4. Check the result on Storage Explorer.

**Expect Experience:**
An info bar prompts.
![image](https://user-images.githubusercontent.com/41351993/79206668-4196e100-7e72-11ea-8886-d82fea1f2764.png)

**Actual Experience:**
No info bar prompts.

**More Info:**
1. Can't navigate to the linked item when using its direct link to open Storage Explorer.
2. This issue also reproduces for Storage Accounts/ File Shares/ Tables/ Queues.
3. This issue doesn't reproduce on Windows.

**Comment by craxal** [comment]
@v-xianya I was not able to repro on a Mac using the same build. I got the info bar as expected. If you can still repro, please provide any additional details you can.

**Comment by v-xianya** [comment]
Hi @craxal  
We verified this issue. it does not reproduce on Mac (Version: 10.15.2). Also thank you for the update.
