### ISSUE TITLE
The uploaded blob doesn't display when uploading to a new folder which name ended with dots

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2833]
**Storage Explorer Version:** 1.13.0
**Build:** [20200414.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3639109)
**Branch:** rel/1.13.0
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one non-ADLS Gen2 storage account -> Blob Containers.
2. Create a new blob container ->  Click 'New Folder'.
3. Add dots append to the default folder name -> Click 'OK'.
4. Upload one file to the folder -> Check the result.

**Expect Experience:**
The uploaded blob displays.

**Actual Experience:**
The uploaded blob doesn't display.
![image](https://user-images.githubusercontent.com/41351993/79208228-60967280-7e74-11ea-85cc-95f272c93483.png)

**More Info:**
This issue doesn't reproduce for file shares.
![image](https://user-images.githubusercontent.com/41351993/79208084-304ed400-7e74-11ea-9740-782650697bc3.png)

**Comment by MRayermannMSFT** [comment]
Something appears to be trimming the dots off of things. As far as I can tell, everyone involved is sending the right requests.

**Comment by MRayermannMSFT** [comment]
Tell the platform about this.

**Comment by MRayermannMSFT** [comment]
Platform has told me that this is by design. They will be updating docs soon to address it.
