### ISSUE TITLE
Display a duplicate account when sign-in with 'MSAL' enabled selecting Custom Environment

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2836]
**Storage Explorer Version:** 1.13.0
**Build:** [20200415.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3643137)
**Branch:** rel/1.13.0
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Open Storage Explorer (Make sure the MSAL setting is enabled).
2. Open Connect dialog -> Select 'Add New Environment' -> Click 'Next'.
3. Input the Environment name and ARM endpoint -> Click 'Next'.
4. Enter the credentials for an azure account.
5. Check the signed account on ACCOUNT MANAGEMENT panel.

**Expect Experience:**
The account displays well.

**Actual Experience:**
Display a duplicate account.

**More Info:**
1. Related bug: https://github.com/microsoft/AzureStorageExplorer/issues/2690.
2. This issue doesn't reproduce for Azure environment.

**Comment by MRayermannMSFT** [comment]
This was happening due to our changing of the redirect url.

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT 
This issue reproduces on build master/[20200520.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3742543&view=results). So re-open it.

**Comment by MRayermannMSFT** [comment]
@v-xianya what if you remove the account and sign back in? Was this after upgrading to 1.13?

**Comment by v-xianya** [comment]
Verified on build master/[20200521.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3746638&view=results). This issue doesn't reproduce. So we close it.
