### ISSUE TITLE
No conflict dialog pops up when downloading one existing empty folder

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2837]
**Storage Explorer Version:** 1.13.0
**Build**: [20200415.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3643137)
**Branch**: rel/1.13.0
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one storage account -> File Shares.
2. Create a new file share -> Create new folder.
3. Download **the empty folder** to the specify path -> Download it to same path again.
4. Check the result.

**Expect Experience:**
A conflict dialog pops up.

**Actual Experience:**

1. No conflict dialog pops up.
2. The activity log shows below.
![image](https://user-images.githubusercontent.com/54055206/79320574-99018380-7f3c-11ea-87f6-081063673aa4.png)

**More Info:**
This issue also reproduces when paste one existing empty folder.

**Comment by v-xianya** [comment]
1. This issue is fixed **on Mac & Linux**.
2. The description in conflict dialog is odd **on Windows.**
![image](https://user-images.githubusercontent.com/41351993/80299592-388a0600-87c8-11ea-9097-0d66a7a5a8a8.png)

**Comment by v-xianya** [comment]
This issue is fixed on build rel/1.13.0-[20200428.13](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3684616&view=results). So we close it.
