### ISSUE TITLE
Fail to download one existing folder with files under one file share

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2838]
**Storage Explorer Version:** 1.13.0
**Build**: [20200415.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3643137)
**Branch**: rel/1.13.0
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one storage account -> File Shares.
2. Create a new file share -> Upload one folder with files to it.
3. Download **the folder** to the specify path -> Download it to same path again.
4. Select 'Overwrite' in the conflict dialog -> Apply to All Conflicts.
5. Check the result.

**Expect Experience:**
Succeed to overwrite the folder.

**Actual Experience:**
Show below in activity log.
![image](https://user-images.githubusercontent.com/54055206/79323615-06afae80-7f41-11ea-8791-740be7944560.png)

**More Info:**

1. Click 'Retry..' in activity log-> Select 'Enabled Overwrite' -> Retry Selected -> The result shows below.
 ![image](https://user-images.githubusercontent.com/54055206/79323669-16c78e00-7f41-11ea-9b6e-05b55fc028d1.png)
3. This issue also reproduces when paste **one existing folder with files.**

**Comment by v-limu** [comment]
Verified on build [20200422.4.](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3663543&view=results)

1. Select 'Overwrite' in download conflict dialog. the result shows below.
![image](https://user-images.githubusercontent.com/54055206/79936731-bbd6ef00-848a-11ea-8081-2651048fb94b.png)
2. Succeed to download the folder after selecting 'Enabled Overwrite' in Retry AzCopy dilaog.

**Comment by JasonYeMSFT** [comment]
@v-limu, we have a pending AzCopy bug fix for the initial transfer. Once it is fixed, the user would see a prompt for the skipped item and be able to select overwrite there.

**Comment by v-xianya** [comment]
@JasonYeMSFT 
Verified Result: (on build rel/1.13.0-[20200426.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3676579&view=results))

The conflict dialog pops up twice. (Both for options **Overwrite** & **Do not download**)
1. On Windows:

![image](https://user-images.githubusercontent.com/41351993/80299805-e1853080-87c9-11ea-8b61-55208822b3bf.png)
2. On MacOS:
![image](https://user-images.githubusercontent.com/41351993/80299927-f7472580-87ca-11ea-952f-407ebcef12b4.png)
3. On Linuxt:
![image](https://user-images.githubusercontent.com/41351993/80300392-da145600-87ce-11ea-9e09-0077e412dfe5.png)

**Comment by JasonYeMSFT** [comment]
For file share service, there will be two conflict dialogs, one for files and one for folders. They are considered as different types of conflicts so that the user needs to select conflict resolution for each type. Please verify if the two conflict dialogs are for files and folders.

**Comment by v-xianya** [comment]
@JasonYeMSFT 
Yes, You are right. The two conflict dialogs are for files and folders. 😉

But, On Windows. 
1. Display **'%5C%5C'** at the beginning of the description in Folders conflict dialog.
2. Same behavior with bug [2837](https://github.com/microsoft/AzureStorageExplorer/issues/2837).

**Comment by v-xianya** [comment]
This issue is fixed on build rel/1.13.0-[20200428.13](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3684616&view=results). So we close it.
