### ISSUE TITLE
It is not appropriate to show 'Properties...' on ADLS Gen2 blob containers context menu

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2842]
**Storage Explorer Version:** 1.13.0
**Build:** [20200415.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3643137)
**Branch:** rel/1.13.0
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Right click it and check its context menu.

**Expect Experience:**
It would be much better to show 'Metadata…' instead of the 'Properties…'.
Because we can see the blob container's properties displays on the Properties panel.
![image](https://user-images.githubusercontent.com/41351993/79431698-5eabeb00-7ffd-11ea-9ee2-08b17b8cae67.png)

**Actual Experience:**
Show 'Properties...' on the ADLS Gen2 blob container.

**More Info:**
In Portal, one blob container has Properties and Metadata settings.
![image](https://user-images.githubusercontent.com/41351993/79431786-77b49c00-7ffd-11ea-9b57-5ec8a1424630.png)

**Comment by craxal** [comment]
By design. It was meant to be consistent with other uses in other places. We may in the future remove the Properties tab entirely.
