### ISSUE TITLE
File Share - cross Storage Account copy fails when firewall is enabled

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#2845]
**Storage Explorer Version**: 1.13.0
**AzCopy Version**: 10.4.0

If the user has Storage Firewall enabled on storage accounts, file share to file share copy may fail because some necessary feature hasn't been rolled out to the user's tenant. We will update in this issue when the service has been rolled out to all tenants.

Please comment below if you have any questions.

**Comment by MRayermannMSFT** [comment]
The service has rolled out a fix for this. No action is required by users.
