### ISSUE TITLE
Support private endpoints

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#2848]
https://docs.microsoft.com/en-us/azure/storage/common/storage-private-endpoints

**Comment by JamesDLD** [comment]
Adding [here](https://techcommunity.microsoft.com/t5/azure-data-explorer/microsoft-azure-storage-explorer-private-endpoints-on-adls-gen2/m-p/1317931#M209) a link with more context, thank you.

**Comment by JamesDLD** [comment]
Azure Storage Explorer supports private endpoint, this issue can be closed.
