### ISSUE TITLE
The deleted original blob still displays in manage snapshots view

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#285]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: All
**Architecture**: ia32/x64
**Build Number**: 20180611.3
**Commit**: e00d7640
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Launch Storage Explorer and expand the Storage Accounts.
2. Open one blob container and upload a blob file to it.
3. Right click this blob and select 'Manage Snapshots...'.
4. Delete the original blob in the snapshots view.

#### Expected Experience: ####
The deleted original blob doesn't displays in snapshots view.

#### Actual Experience: ####
The deleted original blob still displays in snapshots view.
![delete](https://user-images.githubusercontent.com/34729022/41278734-1783c0a0-6e1a-11e8-8122-1258a8a06cf2.png)

**Comment by v-xianya** [comment]
Verified on build 20181127.2. This issue doesn't reproduce. Could you help to resolve it?
