### ISSUE TITLE
Display an extra folder after cloning one blob under snapshots view

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2850]
**Storage Explorer Version:** 1.13.0
**Build:** [20200418.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3654085&view=results)
**Branch:** rel/1.13.0
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one non-ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Switch to snapshots view -> Clone the blob with a new name.
4. Check the result.

**Expect Experience:**
 1. The cloned blob shows well under blob view.
 2. No extra folder displays.

**Actual Experience:**
1. Display a folder with the same name with the original blob under blob view.
2. The cloned blob is located under the folder.
![image](https://user-images.githubusercontent.com/41351993/79735535-04779680-832b-11ea-83e7-58e5a43800b8.png)

**Comment by MRayermannMSFT** [comment]
Hide clone with new name (and other other similar actions) for the base blob when viewing snapshots.

**Comment by v-limu** [comment]
Verified on build 20200512.2. This issue has been fixed. So close it.
![image](https://user-images.githubusercontent.com/54055206/81648417-41820500-9461-11ea-805c-33cb90f200b1.png)
