### ISSUE TITLE
Display "directory name/blob name" in name box on blob properties dialog 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2851]
**Storage Explorer Version:** 1.13.0
**Build:** [20200418.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3654085&view=results)
**Branch:** rel/1.13.0
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload a folder contains one blob at least.
3. Select one blob -> Open blob properties dialog.
4. Check the value for the name properties.

**Expect Experience:**
Display blob name.

**Actual Experience:**
Display "directory name/ blob name".
![image](https://user-images.githubusercontent.com/41351993/79737728-52da6480-832e-11ea-9d7a-172266172bfa.png)

**Comment by MRayermannMSFT** [comment]
Technically this is correct. Since blob folders are "virtual" the actual name of a blob includes the "path" to it.
