### ISSUE TITLE
No folder shows when typing destination directory in upload files dialog

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2856]
**Storage Explorer Version:** 1.13.0
**Build**: [20200418.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3654085&view=results)
**Branch**: rel/1.13.0
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/macOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Previous release (1.12.0)

**Steps to reproduce:**

1. Expand one storage account -> File Shares.
2. Create one new file share -> Click 'Upload Files…'.
3. Select one file and type a name in Destination directory box -> Click 'Upload'.
4. Check the result.

**Expect Experience:**
The file shows below in the folder.

**Actual Experience:**
No folder shows.
![image](https://user-images.githubusercontent.com/54055206/79848023-1de41580-83f3-11ea-9261-d68852aca858.png)

**Comment by v-xianya** [comment]
Verified this issue on build rel/1.13.0-[20200422.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3663543&view=results). Fixed.
