### ISSUE TITLE
Pop up a confirmation dialog when opening a trusted file with name starting with whitespace

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2857]
**Storage Explorer Version:** 1.13.0
**Build:** [20200418.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3654085&view=results)
**Branch:** rel/1.13.0
**Platform/OS:** Windows 10
**Architecture:** ia32
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer -> Settings.
2. Go to Settings -> Transfers -> File Open -> Trusted File Extensions.
3. Make sure the **.txt** extension is included in Trusted File Extensions.
4. Expand one regular blob container -> Upload one **.txt** file with name starting with whitespace.
5. Open the file -> Check the result.

**Expect Experience:**
No dialog pops up.

**Actual Experience:**
A confirmation dialog pops up.
![image](https://user-images.githubusercontent.com/41351993/79852319-17589c80-83f9-11ea-8720-4ba271f7ca1e.png)

**More Info:**
This issue doesn't reproduce for file shares.

**Comment by MRayermannMSFT** [comment]
@craxal ,can you figure out if this is not a regression of the setting based behavior vs not a regression of the non-setting based behavior of 1.12? If the behavior is exactly the same in 1.12, then we can fix this later.

**Comment by v-xianya** [comment]
@MRayermannMSFT This issue also reproduces in 1.12.0 release. 
Pop up the below dialog.
![image](https://user-images.githubusercontent.com/41351993/79931359-6c3df680-847d-11ea-93a7-d603d28d99fa.png)

**Comment by craxal** [comment]
Moved to 1.14.0 since this is not a regression.

**Comment by craxal** [comment]
I am unable to reproduce this in the 20200426.1 build.

**Comment by v-xianya** [comment]
Hi @craxal This issue still reproduces on build rel/1.13.0- [20200428.5](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3681391&view=results).

Detail steps please see the record:
https://web.microsoftstream.com/video/ce4da1ff-0400-96d0-8d5f-f1ea892d95ea

**Comment by craxal** [comment]
@v-xianya The link you provided takes me to a blank white page. I don't see any video.

**Comment by craxal** [comment]
It appears that this bug is really a symptom of the way we treat blob/file transfers on Windows. For whatever reason, the path to the _folder containing the downloaded file_ is passed to the function that checks for trusted file extensions, meaning Storage Explorer is trying to open the folder instead of the targeted file.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240526.2. Fixed. So, we are going to close it.
![screen](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/109954dd-a217-454d-b1bc-df3d531c374b)
