### ISSUE TITLE
Attachments from Storage Explorer generated SAS don't work

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#2858]
**Storage Explorer Version**: 1.14.0
**Build Number**: dev
**Branch**: master
**Platform/OS**: Windows 10
**Architecture**: i86
**Regression From**:  1.13.0 (branch rel/1.13.0)

## Bug Description ##
Any SAS connection strings or URLs generated in Storage Explorer 1.14.0 fail authentication checks when used to attach to Azure resources.

## Steps to Reproduce ##
1. Launch Storage Explorer, sign in, and navigate to a storage account node.
2. Right-click the node and select "Generate Shared Access Signature...".
3. Create a SAS connection string with at least Read and List permissions. Copy the connection string to the clipboard.
4. Click the "Open Connect Dialog", select "Connect using a connection string", and enter the copied connection string. Complete the dialog to create the attachment.
5. Expand the attached storage account node. Attempt to expand the Blob Containers node.

## Expected Experience ##
Blob containers in the account should list.

## Actual Experience ##
A dialog containing a failed authentication message appears.

![image](https://user-images.githubusercontent.com/3473026/79900076-8a92ec00-83c2-11ea-9a39-a83b052691d5.png)

## Additional Context ##
SAS generated in version prior have `sv=2019-02-02`, but SAS generated in the current version have `sv=2019-12-12`. The Azure portal also uses `sv=2019-02-02`.

**Comment by v-xianya** [comment]
Verified this issue on build master/20200509.2. Fixed.
