### ISSUE TITLE
The focused color is inconsistent between Properties window and Editor Panel under default theme

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#286]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Mac
**Architecture**: x64
**Build Number**: 20180611.2
**Commit**: e00d7640
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Launch Storage Explorer and expand the Storage Accounts.
2. Make sure the current theme is default.
3. Check the focused color between Properties window and Editor Panel.

#### Expected Experience: ####
The focused color is inconsistent between Properties window and Editor Panel

#### Actual Experience: ####
The focused color is consistent between Properties window and Editor Panel.
![color](https://user-images.githubusercontent.com/34729022/41279193-52cd4a2c-6e1b-11e8-9921-adff24e2bcd1.png)

**Comment by v-xianya** [comment]
Verified this issue on build main/20201209.2.Fixed.
![image](https://user-images.githubusercontent.com/41351993/101564402-17e48880-3a06-11eb-8ee3-35816cb475aa.png)
