### ISSUE TITLE
Allow user to set display time zone for time stamps

### ISSUE THREAD

**Issue by z4ns4tsu** [microsoft/AzureStorageExplorer#2860]
**Is your feature request related to a problem? Please describe.**
When I'm browsing blob containers trying to match up files to events from other sources, all of the event timestamps are in UTC, but the file timestamps are in my local time zone (PDT). That makes it more difficult than it needs to be to get everything aligned.

**Describe the solution you'd like**
I'd like to be able to set the time zone dates are displayed in (or at least toggle between UTC and local) easily. Either as a setting or a context menu option, ideally.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by MRayermannMSFT** [comment]
Duplicate/related to https://github.com/microsoft/AzureStorageExplorer/issues/59
