### ISSUE TITLE
The focus misses borderlines after clicking the '<<' icon in front of the directory path

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#287]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: All
**Architecture**: ia32/x64
**Build Number**: 20180611.2
**Commit**: e00d7640
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Launch Storage Explorer and expand the Storage Accounts.
2. Open one file share and go to a deep directory.
3. Make sure '<<' icon displays in front of the path.
4. Click this icon and check the focus.

#### Expected Experience: ####
The focus displays well.

#### Actual Experience: ####
The focus misses borderlines.
![icon](https://user-images.githubusercontent.com/34729022/41280633-eb7e9ff2-6e1e-11e8-8eeb-369b9cf47fca.png)

**Comment by v-xianya** [comment]
Verified on build 20181129.6. This issue doesn't reproduce. Could you help to resolve it?

**Comment by v-xianya** [comment]
This issue doesn't reproduce. So we close it.
