### ISSUE TITLE
Support High priority rehydrate from Archive

### ISSUE THREAD

**Issue by xyh1** [microsoft/AzureStorageExplorer#2870]
https://azure.microsoft.com/en-us/blog/enhanced-features-in-azure-archive-storage-now-generally-available/

SetBlobTier from Archive to Hot/Cool now has 2 options: Standard and High.

High priority rehydrate allows for faster restore from archive to online tier.

**Comment by xyh1** [comment]
Also remember the x-ms-rehydrate-priority property please

**Comment by JasonYeMSFT** [comment]
The work for this feature has been merged.
