### ISSUE TITLE
can't display anything

### ISSUE THREAD

**Issue by CrazyCry** [microsoft/AzureStorageExplorer#2871]
**Storage Explorer Version**:  1.11.2
**Build Number**: 20191217.4
**Platform/OS**:  macOS Catalina 10.15.3
**Architecture**:  Darwin speed 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
**Regression From**:  i alway use this version

## Bug Description ##
can't display anything, when i open it, it will be download something, I can see I'm getting a lot of download traffic
![11587622944_ pic_hd](https://user-images.githubusercontent.com/15623287/80066117-e9489900-856d-11ea-8c32-b12da650d288.jpg)

## Steps to Reproduce ##
command+space
enter az
enter enter
can't display anything

**Comment by jinglouMSFT** [comment]
Can you try to upgrade to version 1.12.0?  1.12.0 supports MacOS notarization for Catalina.   Not sure if that's the cause of the issue, but can you give it a try?  Thanks.

**Comment by CrazyCry** [comment]
Since different versions of explorer use different versions of az-cli, it has a big impact on me. If I have to, I will try to upgrade，thanks
