### ISSUE TITLE
Display 'F1' as the shortcut key for Toggle Developer Tools

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2873]
**Storage Explorer Version:** 1.13.0
**Build:** [20200423.5](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3666946&view=results)
**Branch:** rel/1.13.0
**Platform/OS:** macOS Catalina (10.15.2)
**Architecture:** x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer -> Go to Help.
2. Check the shortcut key for Toggle Developer Tools.

**Expect Experience:**
Display ’F12‘ as the shortcut key for Toggle Developer Tools.
![image](https://user-images.githubusercontent.com/41351993/80078564-ad1f3380-8581-11ea-90ca-1b88e4ef06fe.png)

**Actual Experience:**
Display 'F1' as the shortcut key for Toggle Developer Tools.
![image](https://user-images.githubusercontent.com/41351993/80077607-4fd6b280-8580-11ea-8dc4-e7ac9f7fef27.png)

**More Info:**
1. This issue only reproduces in **English** and **Dutch(Netherlands)**.
2. This issue doesn't reproduce on **Mac OS Mojave** (10.14.6).

**Comment by MRayermannMSFT** [comment]
Possibly an electron bug. I'll see if this repro's in electron 8.

**Comment by v-xianya** [comment]
@MRayermannMSFT 
Verified this issue on build master/ [20200512.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3719948&view=results). Not reproduce. So we close it.
![image](https://user-images.githubusercontent.com/41351993/81644552-88b8c780-945a-11ea-863d-0e360d3af607.png)
