### ISSUE TITLE
No check box shows in upload folders's Retry AzCopy dialog 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2879]
**Storage Explorer Version:** 1.13.0
**Build**:[ 20200426.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3676579&view=results)
**Branch**: rel/1.13.0
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/macOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one storage account -> File Shares.
2. Create a new file share -> Upload one folder with multiple files to it.
3. Upload this folder again -> Select 'Do not upload' in conflict dialog.
4. Click 'Retry...' in activity log -> Check the Retry AzCopy dialog.

**Expect Experience:**
Show check box for the source.

**Actual Experience:**
No check box shows for the source.
![image](https://user-images.githubusercontent.com/54055206/80303048-6c712580-87e0-11ea-8569-bfa5f957636e.png)

**More Info:**

1. This issue doesn't reproduce for files.
2. This issue also reproduces when downloading / pasting the existing multiple folders with files.

**Comment by JasonYeMSFT** [comment]
This is by design because retrying folders and files would unnecessarily overwrite files multiple times. Thus we decided to turn off selection if folder exists. See the prompt message of the dialog.

**Comment by v-limu** [comment]
Hi @JasonYeMSFT  two issues need to confirm with you.😃

1. The blob container's 'Retry AzCopy' dialog is different from the file share. Is this by design?
![image](https://user-images.githubusercontent.com/54055206/80475001-cd346580-897a-11ea-862a-f0f64707540a.png)

2. An extra folder occurs in editor when selecting **one file** in an existing blob folder to upload. Is this by design?


     **Repro Steps:**
       1. Expand one ADLS Gen2 account -> Blob Containers -> Create a new blob container.
       2. Upload **one folder with two files** to it ->  Upload this folder again.
      3. Select 'Do not upload' in conflict dialog -> Apply to ALL Conflicts.
      4. Click 'Retry…' in activity log.
      5. Check **one file** in Retry AzCopy dialog -> Select 'Enable overwrite'  -> Click Retry Selected.
      6. Check the editor.
      
      **Actual Experience:**
![image](https://user-images.githubusercontent.com/54055206/80476086-79c31700-897c-11ea-8370-a1d283ec48d2.png)

**Comment by JasonYeMSFT** [comment]
Issue 1 is by design. Issue 2 is a bug. We need to fix it.

**Comment by v-limu** [comment]
Verified on build [20200428.13](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3684616). Issue 2 has been fixed. 
![image](https://user-images.githubusercontent.com/54055206/80554919-41b1e780-8a01-11ea-9906-e0809303a74c.png)
