### ISSUE TITLE
All tabs associated with the same service do not close when service is deleted

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2883]
**Storage Explorer Version:** 1.13.0
**Build**: [20200426.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3676579&view=results)
**Branch**: rel/1.13.0
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Mojave
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one storage account -> Blob Containers.
2. Create a new blob container -> Open multiple new tabs.
3. Delete this blob container -> Check the opened tabs.

**Expect Experience:**
All tabs are disappeared.

**Actual Experience:**

1. The focus tab is disappeared.
2. Other tabs display well.
![image](https://user-images.githubusercontent.com/54055206/80356271-cdb1fb00-88ab-11ea-8e54-e3a9deb06675.png)

**More Info:**
This issue also reproduces for one file share / table / queue.

**Comment by MRayermannMSFT** [comment]
Won't fix.

**Comment by v-limu** [comment]
More Info:
This issue also reproduces when detaching one tab of the attached service.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220908.1. 
1. This issue is fixed for File Shares/Queues/Tables.
2. This issue is reproduced for blob containers/ADLS Gen2 blob containers.
3. There is still one queue tab keeps open when deleting one queue which has serval tabs and locate in split views.

**Comment by v-xianya** [comment]
Verified this issue on the rel build 20240523.2. 
This issue has been fixed for all services. For the comments 3. We opened a new bug [7955](https://github.com/microsoft/AzureStorageExplorer/issues/7955).
