### ISSUE TITLE
Microsoft Account Login Fails

### ISSUE THREAD

**Issue by nitro911** [microsoft/AzureStorageExplorer#2886]
**Storage Explorer Version**: 1.12.0
**Build Number**: 20200116.10
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  Previous

## Bug Description ##
When logging in with Microsoft Account, app goes in circles. Continuously asks for credentials when adding. This used to work just fine, and then I was unable to see my subscriptions. I removed the account from Storage Explorer and tried to add it back. That no longer works.

## Steps to Reproduce ##
1. Click Connect
2. Select Azure from Add an Azure Account
3. Login with Microsoft Account
4. App will keep on asking to login (even after all 2FA security was removed)

## Expected Experience ##
Add an Azure Account by logging in via a Microsoft Account, select subscriptions, see resources.

## Actual Experience ##
App keeps on asking for login. No other apps I use that require Microsoft Account do this.

## Additional Context ##
None.

**Comment by simonlegeek** [comment]
Exactly same issue here
Windows 10 x64
Version: 1.12.0

It seems to default to edge for login, which is annoying.

**Comment by MRayermannMSFT** [comment]
@nitro911 @simonlegeek 

Can y'all please both try using our MSAL preview? To do so, go to Settings -> Application -> Sign In -> Enable Microsoft Authentication Library (MSAL) Preview and then restart the app.

Doing this will opt-you into previewing a new auth library we will be switching to in the future. This library has much better support for multi factor authentication than our current library.

**Comment by nitro911** [comment]
Matthew, when enabled I restarted the app and all my connections were gone. I added them back, but the Microsoft Account one still shows “Subscriptions could not be loaded. Please try reentering credentials…” – the process is much smoother then before and didn’t have a redirect loop, but still won’t let me see my Microsoft Account subscriptions ☹

-Sam

**Comment by johnstaveley** [comment]
Please vote for this issue to be fixed: https://feedback.azure.com/forums/34192--general-feedback/suggestions/40449493-fix-annoying-multi-factor-authentication-issue

**Comment by Noxxys** [comment]
> @nitro911 @simonlegeek
> 
> Can y'all please both try using our MSAL preview? To do so, go to Settings -> Application -> Sign In -> Enable Microsoft Authentication Library (MSAL) Preview and then restart the app.
> 
> Doing this will opt-you into previewing a new auth library we will be switching to in the future. This library has much better support for multi factor authentication than our current library.

This fixed the problem for me, I'm now able to log in and see all my storage accounts. Thank you

**Comment by johnstaveley** [comment]
This fixed it. I never seem to be logged out between accesses anymore! Thanks!
