### ISSUE TITLE
Would be nice if clicking on an entry that is complete in the Activity log opens the treeview node where the job was done 

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#2887]
In a scenario where a task takes a long time to complete and i am multitasking on other tasks, it would be nice when the long-running task is done, i can click on the entry in the Activity log to switch to the treeview node and the corresponding editor to go back to that work.

**Comment by MRayermannMSFT** [comment]
Jing opened this after doing an upload. A general solution will be difficult, and may not make sense for any given activity. For upload, it could at least be a good idea to add a "View Files", "Open Container", etc. action, to help people regain context after a long running upload finishes.
