### ISSUE TITLE
No visual cue in activity log when a file share snapshot is being created. It only shows up when the snapshot is created

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#2888]
The lack of the visual cue led me to wonder if the file share snapshot is being created or not after i initiated the job.  
The experience for upload/download where the activity log is immediately updated upon the start of the job gives the better visual cue and experience.

**Comment by JasonYeMSFT** [comment]
We have added the in-progress activity for creating share snapshot.
