### ISSUE TITLE
Provide hint for proper DateTime format in entity editor dialog

### ISSUE THREAD

**Issue by sholman** [microsoft/AzureStorageExplorer#289]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Win 10
**Architecture**: ia32
**Build Number**: 20180605.1
**Commit**: f8373d5a

#### Steps to Reproduce: ####
Add table to any storage account (Tested on Storage Emulator 5.5 & Live storage account)
Add entity to table
Add Property and change Type to DateTime and try to enter date

#### Expected Experience: ####
Date entered in ISO 8601 format to be allowed (as per https://docs.microsoft.com/en-us/rest/api/storageservices/formatting-datetime-property-values)

#### Actual Experience: ####
Red validation border stays in field no matter the format of the input, and the Insert button is disabled.

![2018-06-12 19_19_16-microsoft azure storage explorer](https://user-images.githubusercontent.com/885331/41283410-ae37457a-6e75-11e8-9365-31ff02c83956.png)

**Comment by craxal** [comment]
Add a milliseconds piece: `2009-03-18T04:25:03.000Z`. We can make that more clear in the future.

**Comment by amullins83** [comment]
I would guess this is a fairly low-priority product for Microsoft, but could this someday be updated to open a date-picker when editing a DateTime field?

**Comment by craxal** [comment]
Date pickers are...problematic, we've found. We struggled for a while with data accuracy and integrity problems in the past, which is why we went with an ordinary text input. The built in ones also don't let you select milliseconds or time zones.

**Comment by Bartmax** [comment]
a hint on how to properly format the datetime would help.

**Comment by craxal** [comment]
@Bartmax That is a good suggestion.
