### ISSUE TITLE
Fail to expand Queues node under one name & key attached storage account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2892]
**Storage Explorer Version:** 1.13.0
**Build**: [20200428.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3681243&view=results)
**Branch**: master
**Platform/OS:**  Windows 10/ Linux Ubuntu 18.04
**Architecture**: ia32/ x64
**Regression From:** Previous release(1.13.0 & 1.12.0)

**Steps to reproduce:**

1. Select one storage account -> Attach it via name & key.
2. Expand the attached storage account -> Queues.
3. Check the result.

**Expect Experience:**
Succeed to expand Queues node.

**Actual Experience:**
Fail to expand Queues node.
![image](https://user-images.githubusercontent.com/41351993/80443046-e15b7100-8940-11ea-9897-a0272e5bff0d.png)

**Comment by craxal** [comment]
Looks like we need to infer the queue endpoint from the connection string.
