### ISSUE TITLE
No 'Copy Direct link' action shows for one new created queue

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2896]
**Storage Explorer Version:** 1.13.0
**Build**: [20200428.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3681243&view=results)
**Branch**: master
**Platform/OS:**  Windows 10/ Linux Ubuntu 18.04
**Architecture**: ia32/ x64
**Regression From:** Previous release(1.13.0 & 1.12.0)

**Steps to reproduce:**
1. Expand one storage account -> Queues.
2. Create a new queue -> Check the context menu.
3. No 'Copy Direct Link' action shows.

**Expect Experience:**
Show the 'Copy Direct Link' action.
![image](https://user-images.githubusercontent.com/41351993/80450990-5afd5a00-8955-11ea-948d-a7d33257bbf5.png)

**Actual Experience:**
No 'Copy Direct Link' action shows. 
![image](https://user-images.githubusercontent.com/41351993/80450950-45883000-8955-11ea-94f7-bf4f9777fd2c.png)

**More Info:**
The action 'Copy Direct Link' shows after refreshing manually.

**Comment by craxal** [comment]
Direct links specifically need subscription information to work, but subscription info isn't passed to the function that adds the node. So we just need to modify the function to accept that info.
