### ISSUE TITLE
Pop up an error when trying to open Shared Access Signature dialog for one queue

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2897]
**Storage Explorer Version:** 1.13.0
**Build**: [20200428.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3681243&view=results)
**Branch**: master
**Platform/OS:**  Windows 10/ Linux Ubuntu 18.04
**Architecture**: ia32/ x64
**Regression From:** Previous release(1.13.0 & 1.12.0)

**Steps to reproduce:**
1. Expand one storage account -> Queues.
2. Select one queue -> Right click it.
3. Select 'Generate Shared Access Signature...' -> Check the result.

**Expect Experience:**
No error pops up.

**Actual Experience:**
An error dialog pops up.
![image](https://user-images.githubusercontent.com/41351993/80451404-5e451580-8956-11ea-886a-abbe9c4ec49e.png)

**More Info:**
The same error dialog pops up when selecting 'Managed Shared Access Policies...'.
![image](https://user-images.githubusercontent.com/41351993/80451678-04911b00-8957-11ea-9515-da4adc9adfd9.png)

**Comment by v-xianya** [comment]
@craxal 
Verified this issue on build master/[20200504.7](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3700661&view=results). 

This issue still reproduces when clicking 'Manage Shared Access Polices... '. So we re-open it.
![image](https://user-images.githubusercontent.com/41351993/81135345-57d42080-8f8a-11ea-9532-382815b208e2.png)

**Comment by craxal** [comment]
@v-xianya Yes, the queue extension package has not been updated. We are waiting for several bug fixes to be merged before updating the package version.
