### ISSUE TITLE
Move Storage Containers between Azure Accounts

### ISSUE THREAD

**Issue by ODA-AG** [microsoft/AzureStorageExplorer#2899]
**Is your feature request related to a problem? Please describe.**
A product was build and deployed as part of an Organization's Azure Account (let's say B), where several Storage Containers were used and have data in them. A few years later and the product has been move to another Organization and they have their own Azure Account (let's say A). Now they have some Storage Containers in their Azure Account (A) but would like the old ones (B) moved over to their Azure Account (A). I have both A and B Azure Accounts setup in Azure Storage Explorer but can't find a way to migrate the B Storage Accounts over to A, without rebuilding them, which will take forever and the web application referencing these Storage Accounts won't be to function. 

**Describe the solution you'd like**
So I am asking for the ability to move the B Storage Accounts (and the contents, keys, etc...) to the A Azure Account and remove the B Storage Account upon successful transfer. All of the Storage Accounts on both A and B are GenV2.

**Describe alternatives you've considered**
I checked to see if these requested functionality was available in the Azure Portal, but it is not.

**Additional context**
I hope there would be a validation process:
1. Check to see if it can create the Storage Account in A prior to copying the Storage Account.
2. If successful, prompt if you want the Blobs, Files, etc... in the Storage Account copied as well.
3. If successful, prompt to remove the existing B Storage Account.
4. If successful, clean up (change the primary key and secondary key to match the B Storage Account on A Storage Account, if necessary).

**Comment by xyh1** [comment]
@ODA-AG This is not an issue or feature that can be solved with storage explorer.

If you have admin access to both subscription and storage accounts, you may file a support ticket to move the storage account along with its data from subscription A to subscription B.

**Comment by MRayermannMSFT** [comment]
@ramire-cc this is not a feature which we would implement in Storage Explorer. We would rely on server capabilities for something like this. And at this time, no such capability (one click migration of everything in a storage account to a storage account in another subscription).

If you need to do this, then you can do it yourself by using Storage Explorer or AzCopy to copy contents of containers to the new Storage Account. As for keys, I do not believe there is a way to manually specify the value of a Storage Account's keys.
