### ISSUE TITLE
CosmosDB tree icon is transparent

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#290]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: All
**Architecture**: All
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Launch Storage Explorer.
2. Expand Cosmos DB Accounts node

#### Expected Experience: ####
The "pages" icon is opaque.

#### Actual Experience: ####
The "pages" icon is transparent. It doesn't look good in darker themes.

![image](https://user-images.githubusercontent.com/3473026/41305491-f1fb47b4-6e27-11e8-9861-494fe0c42fed.png)

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
