### ISSUE TITLE
No property 'Shared Access Signature' for tables under one SAS attached account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2904]
**Storage Explorer Version:** 1.13.0
**Build**: [20200428.5](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3681391&view=results) & [20200428.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3681243&view=results)
**Branch**: rel/1.13.0 & master
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS Mojave
**Architecture**: ia32/x64
**Regression From:**  Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Tables -> Create one table.
2. Attach the storage account via SAS.
3. Select the table under the SAS attached storage account.
4. Check its properties on Properties panel.

**Expect Experience:**
Show property 'Shared Access Signature'.
![image](https://user-images.githubusercontent.com/41351993/80468807-45e2f400-8972-11ea-8117-7f32be2d5871.png)

**Actual Experience:**
No property 'Shared Access Signature' shows.
![image](https://user-images.githubusercontent.com/41351993/80469143-bee24b80-8972-11ea-9a43-afdf25187731.png)

**Comment by JasonYeMSFT** [comment]
This has been added during the table rework.

**Comment by v-xianya** [comment]
Verified this issue on the rel build 20220728.1.
![image](https://user-images.githubusercontent.com/41351993/181436130-6339f92c-769e-4d6a-8018-f317265f13c4.png)
