### ISSUE TITLE
While Trying to delete contents of a blob's filessystem we are encountering following exception "This operation is not permitted on a non-empty directory."

### ISSUE THREAD

**Issue by VinayKumarAvilala** [microsoft/AzureStorageExplorer#2905]
{
  "name": "StorageError",
  "message": "This operation is not permitted on a non-empty directory.\nRequestId:7dca827f-601e-0097-1038-1dc653000000\nTime:2020-04-28T08:37:53.2147243Z",
  "stack": "StorageError: This operation is not permitted on a non-empty directory.\nRequestId:7dca827f-601e-0097-1038-1dc653000000\nTime:2020-04-28T08:37:53.2147243Z\n    at Function.StorageServiceClient._normalizeError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:1205:23)\n    at Object.StorageServiceClient._processResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:751:50)\n    at Request.processResponseCallback [as _callback] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:319:37)\n    at Request.self.callback (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1157:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1079:12)",
  "code": "DirectoryIsNotEmpty",
  "statusCode": 409,
  "requestId": "7dca827f-601e-0097-1038-1dc653000000"
}

**Comment by MRayermannMSFT** [comment]
@VinayKumarAvilala what version of storage explorer are you on?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.

**Comment by raeesgillani** [comment]
Hi, I have the same issue as above, using ADLS Gen2 Blob Container and attempting to delete a folder inside it using dbutils.fs.rm("/mnt/axisDataLake/Delta Lake/Temp/CE/Cases/",recurse=True) inside Databricks Python defaulted Notebook and it comes up with the error:

`shaded.databricks.org.apache.hadoop.fs.azure.AzureException: hadoop_azure_shaded.com.microsoft.azure.storage.StorageException: This operation is not permitted on a non-empty directory.`
