### ISSUE TITLE
 When using RA-GRS Storage (with or without HNS), enable accessing the read only secondary 

### ISSUE THREAD

**Issue by isamllr** [microsoft/AzureStorageExplorer#2906]
**Is your feature request related to a problem? Please describe.**
 When using RA-GRS Storage (with or without HNS), enable accessing the read only secondary 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by isamllr** [comment]
I agree that this feature should not be available for GRS and other type of accounts, but definitely RA-GRS and RA-GZRS, as this is as we market it, see here: https://docs.microsoft.com/en-us/azure/storage/common/storage-redundancy#summary-of-redundancy-options. 

I've seen this was an ask in the past but the item was closed @MRayermannMSFT

**Comment by MRayermannMSFT** [comment]
The one I closed was closed as a duplicate (I believe). Here's the issue we're using to track this feature request: https://github.com/microsoft/AzureStorageExplorer/issues/421
