### ISSUE TITLE
Get ServiceHub and Electron .dll's signed

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#2908]
Some the .dlls we ship seem to not be signed. Let's get those signed!
![image](https://user-images.githubusercontent.com/21112697/80545244-b9cbcf00-8967-11ea-9ef4-7b280b803e65.png)

**Comment by MRayermannMSFT** [comment]
For the service hub .dll's, the service hub team is intending to get those signed themselves.

For the electron .dll's, we should find out if the internal Electron team is supposed to be signing those, or if we need to with the 3rd party cert.

**Comment by JasonYeMSFT** [comment]
Get a response from the internal Electron team. They aren't going to sign those dll's so we need to sign them ourselves.
