### ISSUE TITLE
Update 'Replace' to 'Overwrite' in Upload Conflict dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2909]
**Storage Explorer Version:** 1.13.0
**Build**: [20200428.13](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3684616&view=results)
**Branch**: rel/1.13.0
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Mojave
**Architecture**: ia32/x64
**Regression From:**  Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Create one blob container -> Upload one file.
3. Upload the same file again -> Check the options in conflict dialog.

**Expect Experience:**
Display 'Overwrite' as the first option.

Reason: In Retry dialog, the word 'overwrite' is used.
![image](https://user-images.githubusercontent.com/41351993/80573879-67f07b00-8a33-11ea-88e9-3aa094428383.png)
**Actual Experience:**
Display 'Replace' as the first option.
![image](https://user-images.githubusercontent.com/41351993/80573430-85711500-8a32-11ea-8700-4bfd054eb94c.png)

**More Info:**
1. This issue also reproduces for file shares.
2. This issue also reproduces for Copy Conflict dialog.

**Comment by MRayermannMSFT** [comment]
Won't fix for now. Words are similar enough that users should be able to understand.
