### ISSUE TITLE
Keep the key words 'Classic' & 'Premium' & 'Blob' for attached storage accounts

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2910]
**Storage Explorer Version:** 1.13.0
**Build**: [20200430.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3689994&view=results)
**Branch**: rel/1.13.0
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Mojave
**Architecture**: ia32/x64
**Regression From:**  Not a regression

**Steps to reproduce:**
1. Expand one storage account that appended with **'Classic' or 'Premium' or 'Blob'.**
2. Attach the storage account.
3. Check the attached storage account.

**Expect Experience:**
Keep the key words 'Classic' & 'Premium' & 'Blob' for attached storage accounts

**Actual Experience:**
The key words 'Classic' & 'Premium' & 'Blob' are removed for attached storage accounts.

**Comment by MRayermannMSFT** [comment]
@v-xianya unfortunately this isn't possible. The information that tells us if an account is classic or premium comes from ARM. When you attach a storage account, we only ask about the storage service endpoints. Therefore, we cannot make a call to ARM to get the information.
