### ISSUE TITLE
Azure storage blob transfer failure

### ISSUE THREAD

**Issue by jazbrain** [microsoft/AzureStorageExplorer#2911]
Hi, I'm having issues downloading from the storage blob that was exported by Advanced eDiscovery. Error details below... 

cheers, 
jasmin 

Error Details
{
  "message": "\"failed to perform copy command due to error: cannot start job due to error: cannot list blobs. Failed with error -> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/error.go:154\\nHTTP request failed\\n\\nGet https://spapc01salinkexport001.blob.core.windows.net/5abff49d-d093-4d28-8f39-b38f6d1bd46a-1588223039-exportstore?comp=list&include=metadata&prefix=47079dc0-12e7-4cb9-83dd-1813a855c1a9%2F&restype=container&si=ExportStore63%7C0&sig=-REDACTED-&sr=c&sv=2017-07-29&timeout=901: Service Unavailable\\n.\\n\""
}

**Comment by MRayermannMSFT** [comment]
@jazbrain have you tried again since posting? It looks like this might have been a temporary issue.

If it continues to happen, can you please share the AzCopy log file with us? There should be a clickable link/action that will take you to the file. You can attach it to a reply to this issue.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
