### ISSUE TITLE
Failed to save permissions for 'demo/product.txt' on Azure Storage explorer

### ISSUE THREAD

**Issue by Thanikonda** [microsoft/AzureStorageExplorer#2912]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:

**Comment by Thanikonda** [comment]
please help on this issue

**Comment by jinglouMSFT** [comment]
To better help you, can you please elaborate what the issues you were having?  What did you do, on which version of Storage Explorer, on what platform?  What permissions do you have in terms of accessing Azure storage?

**Comment by MRayermannMSFT** [comment]
Closing due too lack of response.
