### ISSUE TITLE
AuthorizationPermissionMismatch when adding a blob container link via ADLSgen2 container

### ISSUE THREAD

**Issue by JuanAngosto12** [microsoft/AzureStorageExplorer#2914]
**Storage Explorer Version**: 1.12.0
**Build Number**: 20200116.10
**Platform/OS**: Windows 10
**Architecture**:  x64

## Bug Description ##
We are attaching ADLS gen2 containers by using adding the resource via Azure Active Directory. In the ADLS gen2 we are using only ACL to shape the security.
The link is added successfully, but the files contained in the link are not visible or accessible.
Error: ﻿AuthorizationPermissionMismatchThis request is not authorized to perform this operation using this permission.
﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission. RequestId:6e17e8b0-c01e-001e-0107-2237ef000000 Time:2020-05-04T11:33:52.9493451Z</Message></Error>

## Steps to Reproduce ##
1. Add and ADLS GEN 2 container by connecting the resource via Az Active Directory:
![image](https://user-images.githubusercontent.com/64776973/80962108-a8be0a80-8e0c-11ea-8ff7-af9c38153c70.png)

2. Observe the error message on the top of the screen.
![image](https://user-images.githubusercontent.com/64776973/80961970-5f6dbb00-8e0c-11ea-8529-f30cb6f536b5.png)

## Expected Experience ##
No error message. The tab should open and show all files contained.

## Actual Experience ##
An error message appear. The files contained on the folder don't appear.

**Comment by MRayermannMSFT** [comment]
@JuanAngosto12 please confirm:

1. That you chose the right tenant when adding the container
2. That you have the needed permissions. If you need help understanding the needed permissions, please let me know if you are relying on ACLs or RBAC.

**Comment by JuanAngosto12** [comment]
Hi @MRayermannMSFT , thank you for your answer.
1- I can confirm I used the right tenant.
2- I believe I'm relying on RBAC, as I am part of a company. I have exact same permissions as my colleagues (and it works for all of them).

**Comment by MRayermannMSFT** [comment]
@JuanAngosto12 can please then use the portal to check the RBAC permissions you have for this container?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of reply. Please open a new issue if you are still having problems.
