### ISSUE TITLE
Cannot start program after update to 1.13

### ISSUE THREAD

**Issue by mikoma** [microsoft/AzureStorageExplorer#2915]
**Storage Explorer Version**: 1.13
**Build Number**: Dont know. Software does not start.. 
**Platform/OS**: Ubuntu 18.04.4 LTS
**Architecture**: x64
**Regression From**:  It worked before the update (1.11.1)

## Bug Description ##
After automatic update to 1.13 the software did not start anymore. No error message. Nothing happens at all. I uninstalled and re-installed. Still nothing. I uninstalled and installed previous version 1.11.1 .. it works fine. I use the snap store.

## Steps to Reproduce ##
--

## Expected Experience ##
The programm should start or give an error message

## Actual Experience ##
The software does not start. nothing happens. no errors.

## Additional Context ##
Computer configuration:
Ubuntu 18.04.4 LTS
Intel® Core™ i7-10510U CPU @ 1.80GHz × 8
Intel® UHD Graphics (Comet Lake 3x8 GT2)
64-bit

**Comment by craxal** [comment]
@mikoma 1.12.0 (10) is actually the previous version. Does that version work? Can you launch `storage -explorer` from the command line and share the console output?

**Comment by mikoma** [comment]
~$ storage-explorer
/snap/storage-explorer/11/StorageExplorer: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory

**Comment by mikoma** [comment]
i can't download version 1.12.0 from the store, it only has 1.11.1 as latest/edge. Latest/beta and latest/stable are both 1.13

**Comment by craxal** [comment]
@mikoma Strange. And shoot, I thought you could install specific versions, but I'm not seeing documentation on how to do that.

Have you tried installing `libnss3-dev`? Sounds similar to Microsoft/vscode#1694.

**Comment by mikoma** [comment]
I tried both
~$ sudo apt install libnss3
~$ sudo apt install libnss3-dev

they are both installed now, Version (2:3.35-2ubuntu2.7). I still get the same error message.

**Comment by craxal** [comment]
@mikoma Right, I realized installing the library might not do much, because snaps are sandboxed. Can you try using the .tar.gz distribution instead of the snap? You might have to install .NET Core and several other libraries.

**Comment by mikoma** [comment]
@craxal I downloaded the .tar.gz version from [here](https://azure.microsoft.com/en-us/features/storage-explorer/) . First it started but ended immediatly with an error message saying that it needs a password manager and a link to [here](https://docs.microsoft.com/de-de/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C1804#linux-dependencies). After executing `sudo apt-get install libgconf-2-4 libgnome-keyring-common libgnome-keyring0` the software eventually started.
BUT it seems to be loading something which it cannot. I'm not able to open the dialog to add a new connection and the terminal where i started the software has printed a whole bunch of error messages. Not sure if i should provide those errors here or if this is a different bug?!

**Comment by craxal** [comment]
@mikoma Could be a different bug, but yes, please share those error messages so we can figure that out.

**Comment by mikoma** [comment]
> @mikoma Could be a different bug, but yes, please share those error messages so we can figure that out.

`app-startup
DEBUG >>> Running renderer startup...
3281 (Provider) >>> Loading '/home/username/Downloads/StorageExplorer-linux-x64/resources/app/out/app/main/Theming/ThemeProvider'
3343 (Provider) >>> Loading '/home/username/Downloads/StorageExplorer-linux-x64/resources/app/out/app/renderer/AzureSubscriptions/AzureSubscriptionsProvider'
3343 (Provider) >>> Loading '/home/username/Downloads/StorageExplorer-linux-x64/resources/app/out/app/renderer/providers/PersistentStorageProvider'
3343 (Provider) >>> Loading '/home/username/Downloads/StorageExplorer-linux-x64/resources/app/out/app/renderer/UserAccountManagement/UserAccountsProvider'
3343 (Provider) >>> Loading '/home/username/Downloads/StorageExplorer-linux-x64/resources/app/out/app/renderer/providers/AppResetProvider/AppResetProvider'
3343 (Provider) >>> Loading '/home/username/Downloads/StorageExplorer-linux-x64/resources/app/out/app/renderer/AzureEnvironmentsManagement/AzureEnvironmentsProvider'
Broadcast theme migration 1588863538907
Unhandled Promise rejection: Hub Controller process exited prematurely with exit code 131. ; Zone: <root> ; Task: Promise.then ; Value: { exitCode: 131 } Error: Hub Controller process exited prematurely with exit code 131.
    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/home/username/Downloads/StorageExplorer-linux-x64/resources/app/node_modules/zone.js/dist/zone-node.js:811:33)
    at ControllerConnection.onControllerProcessExited (/home/username/Downloads/StorageExplorer-linux-x64/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:140:21)
    at ChildProcess.<anonymous> (/home/username/Downloads/StorageExplorer-linux-x64/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:96:93)
    at Object.onceWrapper (events.js:273:13)
    at ZoneDelegate.invokeTask (/home/username/Downloads/StorageExplorer-linux-x64/resources/app/node_modules/zone.js/dist/zone-node.js:275:35)
    at Zone.runTask (/home/username/Downloads/StorageExplorer-linux-x64/resources/app/node_modules/zone.js/dist/zone-node.js:151:47)
    at ChildProcess.ZoneTask.invoke (/home/username/Downloads/StorageExplorer-linux-x64/resources/app/node_modules/zone.js/dist/zone-node.js:345:33)
    at ChildProcess.emit (events.js:187:15)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
From previous event:
    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/home/username/Downloads/StorageExplorer-linux-x64/resources/app/node_modules/zone.js/dist/zone-node.js:811:33)
    at defer (/home/username/Downloads/StorageExplorer-linux-x64/resources/app/node_modules/microsoft-servicehub/node_modules/q/q.js:582:19)
    at Promise.then (/home/username/Downloads/StorageExplorer-linux-x64/resources/app/node_modules/microsoft-servicehub/node_modules/q/q.js:828:20)
    at ControllerConnection.connectImpl (/home/username/Downloads/StorageExplorer-linux-x64/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:48:14)
    at Function.ControllerConnection.connect (/home/username/Downloads/StorageExplorer-linux-x64/resources/app/node_modules/microsoft-servicehub/controllerConnection.js:31:27)
    at HubLookup.getLocationService (/home/username/Downloads/StorageExplorer-linux-x64/resources/app/node_modules/microsoft-servicehub/hubLookup.js:20:80)
    at HubClient.requestServiceWithRetries (/home/username/Downloads/StorageExplorer-linux-x64/resources/app/node_modules/microsoft-servicehub/hubClient.js:74:21)
    at HubClient.requestService (/home/username/Downloads/StorageExplorer-linux-x64/resources/app/node_modules/microsoft-servicehub/hubClient.js:62:21)
    at ElectronAadAccountProviderClient.<anonymous> (/home/username/Downloads/StorageExplorer-linux-x64/resources/app/node_modules/identity-client/dist/AadAccountProviderClient.js:57:74)
    at Generator.next (<anonymous>)
    at /home/username/Downloads/StorageExplorer-linux-x64/resources/app/node_modules/identity-client/dist/AadAccountProviderClient.js:10:71
    at new ZoneAwarePromise (/home/username/Downloads/StorageExplorer-linux-x64/resources/app/node_modules/zone.js/dist/zone-node.js:551:29)
    at __awaiter (/home/username/Downloads/StorageExplorer-linux-x64/resources/app/node_modules/identity-client/dist/AadAccountProviderClient.js:6:12)
    at AadAccountProviderClient.rpc (/home/username/Downloads/StorageExplorer-linux-x64/resources/app/node_modules/identity-client/dist/AadAccountProviderClient.js:56:27)
{ promise:
   { __zone_symbol__state: 0,
     __zone_symbol__value: { exitCode: 131 } },
  rejection: { exitCode: 131 },
  task:
   { cancelFn: null,
     runCount: 1,
     source: 'Promise.then',
     type: 'microTask',
     zone:
      { _name: '<root>',
        _parent: null,
        _properties: {},
        _zoneDelegate: [Object] } },
  zone:
   { _name: '<root>',
     _parent: null,
     _properties: {},
     _zoneDelegate:
      { _cancelTaskCurrZone: null,
        _cancelTaskDlgt: null,
        _cancelTaskZS: null,
        _forkCurrZone: null,
        _forkDlgt: null,
        _forkZS: null,
        _handleErrorCurrZone: null,
        _handleErrorDlgt: null,
        _handleErrorZS: null,
        _hasTaskCurrZone: null,
        _hasTaskDlgt: null,
        _hasTaskZS: null,
        _interceptCurrZone: null,
        _interceptDlgt: null,
        _interceptZS: null,
        _invokeCurrZone: null,
        _invokeDlgt: null,
        _invokeTaskCurrZone: null,
        _invokeTaskDlgt: null,
        _invokeTaskZS: null,
        _invokeZS: null,
        _parentDelegate: null,
        _scheduleTaskCurrZone: null,
        _scheduleTaskDlgt: null,
        _scheduleTaskZS: null,
        _taskCounts: [Object],
        zone: null } } }
`
this error repeats 8 times and is followed by

`3343 (Provider) >>> Loading '/home/username/Downloads/StorageExplorer-linux-x64/resources/app/out/app/renderer/providers/HttpRequestProvider'
3343 (Provider) >>> Loading '/home/username/Downloads/StorageExplorer-linux-x64/resources/app/out/app/renderer/providers/StorageApiSettingManagerProvider'
app-poststartup-complete
Unable to load user extensions: Error: ENOENT: no such file or directory, scandir '/home/username/.config/StorageExplorer/extensions/'
PROVIDER (Main 3281) >>> Constructed NodeProcessProviderProxy for provider 'se-markdown-panel'
3343 (Provider) >>> Loading '/home/username/Downloads/StorageExplorer-linux-x64/resources/app/out/app/renderer/providers/EditorManagerProvider'
PROVIDER (Main 3281) >>> Constructed NodeProcessProviderProxy for provider 'se-managed-disks-extension'
Specifying view model modules in dialog configurations is deprecated. See 'HelloWorldView.ts' in the 'se-extension-example' package for an example of how to setup MVVM dialogs.
Specifying view model modules in dialog configurations is deprecated. See 'HelloWorldView.ts' in the 'se-extension-example' package for an example of how to setup MVVM dialogs.
Specifying view model modules in dialog configurations is deprecated. See 'HelloWorldView.ts' in the 'se-extension-example' package for an example of how to setup MVVM dialogs.
3343 (Provider) >>> Loading '/home/username/Downloads/StorageExplorer-linux-x64/resources/app/out/app/renderer/providers/WorkerManagerProvider'
3343 (Provider) >>> Loading '/home/username/Downloads/StorageExplorer-linux-x64/resources/app/out/app/renderer/providers/SslCertificateManagerProvider'
3343 (Provider) >>> Loading '/home/username/Downloads/StorageExplorer-linux-x64/resources/app/out/app/renderer/providers/NodeProducerProvider/NodeProducerProvider'
3343 (Provider) >>> Loading '/home/username/Downloads/StorageExplorer-linux-x64/resources/app/out/app/renderer/providers/SessionManagerProvider'
PROVIDER (Main 3281) >>> Constructed NodeProcessProviderProxy for provider 'se-configuration-panel'
PROVIDER (Main 3281) >>> Constructed NodeProcessProviderProxy for provider 'se-adls2-extension'
Specifying view model modules in dialog configurations is deprecated. See 'HelloWorldView.ts' in the 'se-extension-example' package for an example of how to setup MVVM dialogs.
PROVIDER (Main 3281) >>> Constructed NodeProcessProviderProxy for provider 'se-az-copy-extension'
Specifying view model modules in dialog configurations is deprecated. See 'HelloWorldView.ts' in the 'se-extension-example' package for an example of how to setup MVVM dialogs.
Specifying view model modules in dialog configurations is deprecated. See 'HelloWorldView.ts' in the 'se-extension-example' package for an example of how to setup MVVM dialogs.
PROVIDER (Main 3281) >>> Constructed NodeProcessProviderProxy for provider 'se-file-extension'
PROVIDER (Main 3281) >>> Constructed NodeProcessProviderProxy for provider 'se-blob-extension'
NODE PROCESS PROXY (Main 3281) >>> Launched Node process 3417 for module 'NodeProcessHostProxy'
NODE PROCESS PROXY (Main 3281) >>> Node process 3417 ack received for module 'NodeProcessHostProxy'
PROVIDER (Main 3281) >>> Launched Node process 3417 for provider 'se-blob-extension'
3417 (ParentProcessProxy) >>> Loading SSL Settings

3417 (ParentProcessProxy) >>> Injecting certs found in /home/username/.config/StorageExplorer/certs/

3417 (ParentProcessProxy) >>> Sending init acks back to parent process

3417 (NodeProcessHostProxy) >>> Loading '/home/username/Downloads/StorageExplorer-linux-x64/resources/app/node_modules/se-blob-extension/dist/index.js'

3417 (Provider) >>> Loading '/home/username/Downloads/StorageExplorer-linux-x64/resources/app/node_modules/se-blob-extension/dist/index.js'

3343 (Provider) >>> Loading '/home/username/Downloads/StorageExplorer-linux-x64/resources/app/out/app/renderer/providers/ShellProvider'
3417 (NodeProcessHostProxy) >>> Node host in process 3417 has started successfully

3343 (Provider) >>> Loading '/home/username/Downloads/StorageExplorer-linux-x64/resources/app/out/app/renderer/providers/UpdatesManagerProvider'
`

**Comment by craxal** [comment]
The "hub controller" is a .NET component we use for handling sign in, and it looks like it had problems starting up. Do you have .NET Core installed?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems. Thanks.
