### ISSUE TITLE
Storage Explorer should validate the GUID in AAD and throw an error indicating that it is not a valid OID for a SPN or user

### ISSUE THREAD

**Issue by isamllr** [microsoft/AzureStorageExplorer#2916]
**Is your feature request related to a problem? Please describe.**
Azure Storage Explorer has supported setting ACLs on file / folder level for ADLS Gen 2, since the 1.6 release. However, the UI does not perform any validation of the entered ID against AAD directly. For example, it allows completely random GUIDs, and also application IDs to be entered, whereas actually the only valid entry here should be the OID of the user or service principal in the current tenant.

**Describe the solution you'd like**
Storage Explorer should validate the GUID in AAD and throw an error indicating that it is not a valid OID for a SPN or user.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by MRayermannMSFT** [comment]
@isamllr what version of Storage Explorer are you using? Newer versions have much stricter/advanced validation when modifying ACLs.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems. Thanks.
