### ISSUE TITLE
Support standard Ctrl+W keyboard shortcut for 'close tab' action

### ISSUE THREAD

**Issue by johndowns** [microsoft/AzureStorageExplorer#2921]
**Is your feature request related to a problem? Please describe.**
This is a usability issue. I frequently have a number of tabs open in Storage Explorer, e.g. for multiple blob containers, tables, queues, etc. The standard convention is to allow for the Ctrl+W keyboard shortcut to close the active tab, but this does not appear to be bound to the 'close tab' action in Storage Explorer. Instead, I have to use the mouse to close the tab. If I am heavily keyboard-focused (which is often the case when I am writing code and switching windows to work with Storage Explorer) this is quite frustrating.

**Describe the solution you'd like**
Please create a new keyboard shortcut to bind the Ctrl+W key combination to the 'close tab' action.

**Describe alternatives you've considered**
N/A

**Additional context**
This applies to the Windows build of Storage Explorer, and the feedback is current as of v1.15.1.

**Comment by MRayermannMSFT** [comment]
@johndowns, I just tried this and it looks like that is already the shortcut on macOS, and it's been that way since summer of 2018. You can see it in the File menu:

**Comment by johndowns** [comment]
That shows it’s Command-W, not Control-W.

________________________________

**Comment by johndowns** [comment]
@MRayermannMSFT You're correct - on macOS it works correctly (note this is Command-W rather than Ctrl+W though). This feedback is specifically about the Windows version. I have just verified this on v1.15.1 of the Windows build - on there, the 'Close Editor' menu item is linked to Ctrl+F4, which is not standard.

**Comment by MRayermannMSFT** [comment]
Ah, yes. My apologies. I'm using a mac while WFH. 🙃 I'll get onto a Windows machine and fix this right up!

**Comment by MRayermannMSFT** [comment]
New file menu on Windows:
<img width="202" alt="image" src="https://user-images.githubusercontent.com/21112697/95501305-f0693500-095c-11eb-8be7-9bfcba953c8a.png">

Menus on mac still the same:
<img width="220" alt="image" src="https://user-images.githubusercontent.com/21112697/95501698-8ef59600-095d-11eb-8466-d2b59408a24d.png">
<img width="194" alt="image" src="https://user-images.githubusercontent.com/21112697/95501721-974dd100-095d-11eb-839e-067ee87e8a8d.png">

**Comment by johndowns** [comment]
Awesome! Thank you @MRayermannMSFT, that is perfect.

**Comment by MRayermannMSFT** [comment]
Merged into main for 1.16
