### ISSUE TITLE
Show a failed activity log when attaching one queue via SAS

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2923]
**Storage Explorer Version:** 1.13.0
**Build**:  [20200504.7](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3700661&view=results)
**Branch**: master
**Platform/OS:** Windows 10/  Linux Ubuntu 16.04/ macOS Catalina
**Architecture**: ia32/x64
**Regression From:**  Previous release(1.13.0)

**Steps to reproduce:**
1. Expand one storage account -> Queues.
2. Select one queue -> Attach it via SAS.
4. Check the result.

**Expect Experience:**
1. Succeed to attach the queue.
2. Show a successful log message.

**Actual Experience:**
1. Show a failed activity log.
2. The attached queue displays after refreshing manually.
![image](https://user-images.githubusercontent.com/41351993/81157576-b06ee200-8fb9-11ea-8a64-6b62d29aa600.png)

**Comment by craxal** [comment]
There's already a fix that's been merged for this.

**Comment by v-xianya** [comment]
@craxal 
Verified this issue on build 20200509.1.
1. Show a successful activity log when attaching queues.
2. **The attached queue doesn't auto display.**

**Comment by craxal** [comment]
@v-xianya Yes, as I mentioned earlier, there's already a fix that's been merged. The current state of this bug is "Verifying", meaning we still need to check for things on our end. Packages have not yet been updated, so you're not going to see the fix yet.
