### ISSUE TITLE
The selected permission 'Delete version' doesn't display on Connect Summary dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2926]
**Storage Explorer Version:** 1.13.0
**Build**:  [20200504.7](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3700661&view=results)
**Branch**: master
**Platform/OS:** Windows 10/  Linux Ubuntu 16.04/ macOS Catalina
**Architecture**: ia32/x64
**Regression From:**  Not a regression

**Steps to reproduce:**
1. Select one non-ADLS Gen2 storage account.
2. Right-click the storage account -> Select 'Get Shared Access Signature...'.
3. Create a SAS connection string with permissions 'Read & List & Delete version' -> Copy the connection string.
4. Click 'Open Connect Dialog' -> Select 'using a connection string' -> Click 'Next'.
5. Paste the copied connection string -> Click 'Next'.
6. Check the permissions value on Connection Summary dialog.

**Expect Experience:**
The permission 'Delete version' displays.

**Actual Experience:**
1. No permission 'Delete version' displays.
2. In Connection string: sp=rxl.
![image](https://user-images.githubusercontent.com/41351993/81161795-ba471400-8fbe-11ea-954a-9d9bd0d6be1a.png)

**Comment by JasonYeMSFT** [comment]
Blob versioning is moved out of 1.14.0. Move to 1.15.0 instead.

**Comment by v-xianya** [comment]
@JasonYeMSFT Verified this issue on build 20200813.10.
The current behaviors:
1. The permission 'Delete version' displays on Connect Summary dialog. 
![image](https://user-images.githubusercontent.com/41351993/90208811-4d90b080-de1c-11ea-9aef-5b7baf9027ef.png)
2. The permission 'Delete version' doesn't display on the Properties panel for the attached storage account.
![image](https://user-images.githubusercontent.com/41351993/90209013-dad40500-de1c-11ea-8b7d-d0e1325ab7f8.png)

**Comment by v-xianya** [comment]
Verified this issue on build master/20200818.4. Fixed.
