### ISSUE TITLE
'Manage History' is still enabled on the toolbar under one empty blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2928]
**Storage Explorer Version:** 1.13.0
**Build**:  [20200504.7](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3700661&view=results)
**Branch**: master
**Platform/OS:** Windows 10/  Linux Ubuntu 16.04/ macOS Catalina
**Architecture**: ia32/x64
**Regression From:**  Not a regression

**Steps to reproduce:**
1. Expand one non-ADLS Gen2 storage account -> Blob Containers.
2. Create a new blob container -> Check its toolbar.

**Expect Experience:**
The action 'Manage History' is disabled.

**Actual Experience:**
The action 'Manage History' is enabled.
![image](https://user-images.githubusercontent.com/41351993/81162375-ab149600-8fbf-11ea-8b97-d35cfdd824b6.png)

**More Info:**
This issue also reproduces for one blob folder.
![image](https://user-images.githubusercontent.com/41351993/81162308-8cae9a80-8fbf-11ea-8cb7-b9c5793a1ad8.png)

**Comment by JasonYeMSFT** [comment]
The dropdown type of context menu/tool bar button are always enabled by design.

**Comment by v-xianya** [comment]
This issue has been fixed on build master/20200816.2.
![image](https://user-images.githubusercontent.com/41351993/90351525-10722b80-e073-11ea-8cc1-a124427686f0.png)
