### ISSUE TITLE
The queue naming notification message is incompleted

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2930]
**Storage Explorer Version:** 1.13.0
**Build**: [20200504.7](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3700661&view=results)
**Branch**: master
**Platform/OS**: Windows 10/ macOS Catalina / Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Regression From:** Previous release(1.13.0)

**Steps to reproduce:**

1. Expand one storage account -> Queues.
2. Click 'Create' -> Type 2 characters in name box.
3. Check the result.

**Expect Experience:**
The notification message is completed.
![image](https://user-images.githubusercontent.com/54055206/81159949-19eff000-8fbc-11ea-97d3-b4665169ccb6.png)

**Actual Experience:**
The notification message is incompleted.
![image](https://user-images.githubusercontent.com/54055206/81160163-53c0f680-8fbc-11ea-99e1-0911b0e6c4a5.png)

**Comment by craxal** [comment]
This is by design. It's easier on users when the error message explains exactly what's wrong instead of giving them a big list of requirements. Please observe what happens when you type three or more characters but with the wrong arrangement of alphanumerics and hyphens.
