### ISSUE TITLE
Miss two icons on Actions panel for Queues

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2933]
**Storage Explorer Version:** 1.13.0
**Build**: [20200504.7](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3700661&view=results)
**Branch**: master
**Platform/OS**: Windows 10/ macOS Catalina / Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Regression From:** Previous release(1.13.0)

**Steps to reproduce:**

1. Expand one storage account -> Queues.
2. Observe its actions on 'Actions' Panel.

**Expect Experience:**
Icons display well for 'Create' and 'Refresh' actions.
![image](https://user-images.githubusercontent.com/54055206/81161066-8e775e80-8fbd-11ea-8771-11304daa3ee9.png)

**Actual Experience:**
No Icons display for 'Create' and 'Refresh' actions.
![image](https://user-images.githubusercontent.com/54055206/81161072-90412200-8fbd-11ea-8113-1dd6838a9773.png)

**More Info:**
This issue also reproduces for one queue.

1. The icon of 'Delete' isn't correct.
2. No icon displays for 'Add to Quick Access'.
3. An extra icon displays for 'Open in New Tab'.
![image](https://user-images.githubusercontent.com/54055206/81164696-596e0a80-8fc3-11ea-93ae-4b8924ea6ff3.png)

**Comment by craxal** [comment]
@jinglouMSFT @MRayermannMSFT @JasonYeMSFT This is kind of a bigger issue than with just queues. What're your thoughts on these icons for node actions? They're kind of a mess right now, with a mix of PNG and SVG images. The SVG images also aren't themed. Should we spend time trying to fix this up now? I don't want to copy over PNG files to the queue extension if I can avoid it.

**Comment by jinglouMSFT** [comment]
Just fix the Queue for now.  Talk to the icon team to get the SVG images for Queue. Please log a separate bug for the other issues.
