### ISSUE TITLE
Get Subscriptions Failure Details

### ISSUE THREAD

**Issue by harshaba** [microsoft/AzureStorageExplorer#294]
*Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: f8cdef31-a31e-4b4a-93e4-5f571e91255a, Error: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"52.136.136.32","port":443}
Tenant Id: 08dbd056-d6e4-4fb5-b493-0262d673f484, Error: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"52.136.136.32","port":443}

**Comment by JasonYeMSFT** [comment]
Are you still have any issue with our latest 1.12.0?
