### ISSUE TITLE
Make StorageExplorer.exe file version match product version

### ISSUE THREAD

**Issue by schenardie** [microsoft/AzureStorageExplorer#2941]
Not sure if thats the right place or if its too much to ask but would be very nice to have the storage explorer executable (StorageExplorer.exe) file version to match the product version.  Or at least make that information available at https://api.github.com/repos/microsoft/AzureStorageExplorer/releases/latest/ 

It would make life a lot easier when packaging the software for enterprise deployment (for detection pursposes).

Thanks

**Comment by MRayermannMSFT** [comment]
@schenardie what do you mean by the "file version"? Do you mean having the version in the file name, or do you mean like the file properties? Also, are you asking for this to be on the installer or the executable that ends up in your program files directory?

**Comment by schenardie** [comment]
hey @MRayermannMSFT, i'm talking about the file properties of the executable (StorageExplorer.exe).
The file currently has Product Version (1.13.1) and File version (15427.1.0.0).
Management systems like SCCM and Intune are based on file version for detection. Currently i cant tell what the next version will be, so it makes hard to automate this packaging.

Most of MS tools like VSCode have the same value for both.  If that is not doable, maybe putting a property on the intune api per release informing the version would suffice (so we can probe that information).  Thanks

**Comment by craxal** [comment]
Doesn't look like `electron-packager` lets us define that property explicitly. It's always filled in by the build version. The weird thing is the build version appears to be wrong; I don't know where it's getting that number from. As far as solutions go, we may need to use `rcedit` ourselves.

**Comment by MRayermannMSFT** [comment]
Moving this due to changes in dev resources for 1.19
