### ISSUE TITLE
The column layout in one tab is affected by the actions in another tab with the same service

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2942]
**Storage Explorer Version:** 1.13.0
**Build**: [20200507.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3708219&view=results)
**Branch**: dev/marayerm/electron/8
**Platform/OS:** Windows 10/ macOS Mojave/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one storage account -> File Shares.
2. Create one file share -> Open two tabs for it.
3. Select one tab and upload one file to it.
4. Open another tab and observe the column layout. 

**Expect Experience:**
The column layout shows well.
![image](https://user-images.githubusercontent.com/41351993/81272393-0443fe80-9080-11ea-8bcd-5b62dd81ce29.png)

**Actual Experience:**
1. The columns (except the first column) shift to the right.
2. The column layout shows well after clicking refresh.
![image](https://user-images.githubusercontent.com/41351993/81272398-06a65880-9080-11ea-9545-92593650888f.png)

**More Info:**
1. This issue also reproduces for one blob container.
2. This issue reproduces for actions Upload/ Clone/ Delete/ Copy & Paste.

**Comment by MRayermannMSFT** [comment]
This also reproduces in 1.13

**Comment by MRayermannMSFT** [comment]
Investigate for now. If this is simply "because the tab isn't visible, datatables is unable to calculate size columns properly", then don't worry about. If the root cause is not so benign, then go ahead and figure out a fix.

**Comment by MRayermannMSFT** [comment]
Just figure out what the root cause is please @craxal.

**Comment by craxal** [comment]
This just looks like a iframe/datatables issue. I can't really get it to repro consistently. If other users start complaining about this, we can look into it further.
