### ISSUE TITLE
Fail to launch Storage Explorer on Linux when using snap to install SE

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2944]
**Storage Explorer Version:** 1.13.0
**Build**: [20200507.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3708219&view=results)
**Branch**: dev/marayerm/electron/8
**Platform/OS:** Linux Ubuntu 16.04/18.04
**Architecture**: x64
**Regression From:** Previous release(1.13.0)

**Steps to reproduce:**

1. Download the 'StorageExplorer_latest_amd64.snap' from Linux Artifactes(20200507.4).
2. Run the following commands in terminal:
```
sudo snap install StorageExplorer_latest_amd64.snap --dangerous
snap connect storage-explorer:password-manager-service :password-manager-service
```
3. Launch Storage Explorer using the command `storage-explorer`.
4. Check the result.

**Expect Experience:**
Successfully launch Storage Explorer.

**Actual Experience:**
An error occurs.
![image](https://user-images.githubusercontent.com/54055206/81281150-090eaf80-908c-11ea-87eb-2fe2cf546807.png)

**More Info:**
This issue also reproduces on electron/7 branch.

**Comment by MRayermannMSFT** [comment]
Fixed on electron 8 branch.
