### ISSUE TITLE
Account SAS connections don't work due to "authorization header" error

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#2945]
**Storage Explorer Version**: 1.14.0
**Build Number**: dev
**Platform/OS**: All
**Architecture**: All
**Regression From**:  1.13.0

## Steps to Reproduce ##
1. Generate a SAS for a storage account, including permissions for all four services.
2. Attach using the SAS connection string created in step 1.
3. Attempt to expand the blob containers node of the newly attached storage account.

## Expected Experience ##
Blobs are listed.

## Actual Experience ##
An error message saying Azure could not authenticate the request.

## Additional Context ##
Related to SAS version correction already done for blob container SAS.

**Comment by JasonYeMSFT** [comment]
Version overriding logic has been merged.
