### ISSUE TITLE
Open queue editors need to be closed on delete or detach

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#2946]
**Storage Explorer Version**: 1.14.0
**Build Number**: dev
**Platform/OS**: All
**Architecture**: All
**Regression From**:  1.13.0

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Expand Queues node under a storage account.
3. Right-click a queue and select "Attach it with SAS". Make sure an editor is open.
4. Detach the attached queue.
5. Check whether the corresponding editor is closed or not.

**Comment by craxal** [comment]
Currently blocked.

I've introduced a queue editor manager of sorts to the extension. The manager can take two approaches here.
1. Use the older Editor API. The pros here are that the panel works as intended. The cons are that the Editor SDK doesn't raise events that would allow the manager to clean up when a panel is closed.
2. Use the newer Panel API. The pros is we can clean up closed panels by listening to events. The cons are we need to enable node integration and inject the SDK, which requires more work.

I think option 1 is really our only option, as option 2 involves a lot of unknowns and complicated setup. I think the editor could work around the lack of events, or we may be able to add events for the Editor API.

@MRayermannMSFT Do you have any suggestions?

**Comment by craxal** [comment]
@v-xianya Not able to reproduce based on rel/1.14.0 branch (I did not reload or open a new window). If you encounter this error again, please provide more precise repro steps.

**Comment by v-xianya** [comment]
Hi @craxal the repro steps as below. 
1. Launch Storage Explorer -> **Open a new window.**
2. Expand one storage account -> Queues.
3. Select one queue -> Attach it with SAS.
4. Detach the attached queue -> Check whether the corresponding editor is closed or not.

**Comment by craxal** [comment]
@v-xianya I have tested with build 20200622.2 and am not able to reproduce. The editor closes as expected when the attached queue is detached.

**Comment by v-xianya** [comment]
Hi @craxal Please see the below record.🙃 (On build 20200622.5) 


https://web.microsoftstream.com/video/0323a1ff-0400-a521-8278-f1eab4f88a43
