### ISSUE TITLE
Bug when undeleting a block blob

### ISSUE THREAD

**Issue by Silverlight42** [microsoft/AzureStorageExplorer#2949]
**Storage Explorer Version**: 1.13.0
**Build Number**: 20200430.5
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  It was working previously, not sure which version.

## Bug Description ##
When undeleting a Block Blob I get "Cannot read property 'deletedTime' of undefined" and the tab is closed.
![az-undeleteblobbug](https://user-images.githubusercontent.com/6467558/81361823-04a2c080-90a5-11ea-9cd9-d82f002f82d7.png)

## Steps to Reproduce ##
1. Show deleted blobs.
2. Undelete a blob.

## Expected Experience ##
The blob is undeleted successfully and the focus should be returned to the current tab.

## Actual Experience ##
The blob is undeleted successfully and the current tab is closed and the message "Cannot read property 'deletedTime' of undefined" is shown.

## Additional Context ##
None.

**Comment by Silverlight42** [comment]
Apparently after opening the tab again and trying to delete the blob that was undeleted it stays queued.

![az-undeleteblobbug-2](https://user-images.githubusercontent.com/6467558/81362122-b641f180-90a5-11ea-81a3-b10ffb2fd4ef.png)

After restarting ASE I can delete it successfully.

**Comment by JasonYeMSFT** [comment]
@Silverlight42, could you please provide the repro steps for this bug?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems. Thanks!
