### ISSUE TITLE
No feedback when Cosmos DB filter contains an error

### ISSUE THREAD

**Issue by thomaslevesque** [microsoft/AzureStorageExplorer#295]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Windows 10
**Architecture**: x64
**Regression From**: N/A

#### Steps to Reproduce: ####
1. Open the documents tab of a Cosmos DB collection
2. Specify a WHERE filter containing a syntax error
3. Apply the filter

#### Expected Experience: ####
Azure Storage Explorer should show an error message indicating what the problem is.

#### Actual Experience: ####
No error is shown. The result list just appears empty.

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
