### ISSUE TITLE
无法加载附加的存储帐户。错误: Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by albertcpp** [microsoft/AzureStorageExplorer#2950]
无法加载附加的存储帐户。错误: Cannot read property 'version' of undefined
![image](https://user-images.githubusercontent.com/8657034/81370570-12e5f080-9128-11ea-8410-c24453acb941.png)

**Comment by JasonYeMSFT** [comment]
Could you please fill the bug template so that we can know your **platform**, **Storage Explorer version** and **steps to reproduce the bug**?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
