### ISSUE TITLE
Adding large user property does not show properties of any other files

### ISSUE THREAD

**Issue by vamuzumd** [microsoft/AzureStorageExplorer#2953]
**Storage Explorer Version**:  1.13.0
**Build Number**: 20200430.5
**Platform/OS**: Windows
**Architecture**: ia32
**Regression From**:  N/A

## Bug Description ##
I am trying to change the metadata of an existing file in my storage account to make it larger. The metadata is a large text string around ~3 mb. I do this by right-clicking on the File -> Properties -> Add User Key-value field and type the large string [~3 MB]. 
On Clicking "Save" I get a REST error saying the "Size of the headers is too long". Sample error is attached in the payload.

Thereafter, I am unable to view the properties of any file by right-clicking on it. I keep getting the same error "Request too long" for all files.

## Steps to Reproduce ##
1. Right click on a file.
2. Select properties.
3. Add property by clicking on "+" and type anything in the name.
4. In the values, type a long string, sample can be found in the attached error payload.
5. Click "Save".
6. There is a loading symbol followed by this error. 
7. After you close the error dialog, right click on any other file and select "Properties". You get the same popup dialog for any file.

## Expected Experience ##
Right clicking on other files for Properties after the encountered error should show file properties.

## Actual Experience ##
Instead of showing file properties, the error dialog pops up for all files which is 
unrecoverable.

## Additional Context ##
[AzCopyError.txt](https://github.com/microsoft/AzureStorageExplorer/files/4602398/AzCopyError.txt)

**Comment by MRayermannMSFT** [comment]
@vamuzumd I'm having a hard time reproducing this issue? The only questionable thing I'm seeing is that the error dialog is taking a bit to show up after clicking on the "Details..." link. Do you have some screen recording software you can use to show me what you're talking about? If you don't, you could download [screen to gif](https://www.screentogif.com/) and take a gif recording of your screen and post it here. Thanks!

**Comment by vamuzumd** [comment]
Hi @MrayerMa

> @vamuzumd I'm having a hard time reproducing this issue? The only questionable thing I'm seeing is that the error dialog is taking a bit to show up after clicking on the "Details..." link. Do you have some screen recording software you can use to show me what you're talking about? If you don't, you could download [screen to gif](https://www.screentogif.com/) and take a gif recording of your screen and post it here. Thanks!

Hi @MRayermannMSFT , the repro is pretty straightforward, we just need to add a very long string worth ~5MB as the metadata value and Click "Save". I will try to send a screenshot, but I am afraid 
all you can see is the error message that I already added as AzCopyError.txt

**Comment by MRayermannMSFT** [comment]
Yes, your instructions were very clear. Thank you for providing those. Here's a gif of me trying to repro it. Let me know if I'm doing something wrong. (ignore the odd mouse movements, I'm remoting into the machine and the mouse goes crazy when I record the screen)

![2953](https://user-images.githubusercontent.com/21112697/83208471-9f257b00-a10a-11ea-9624-78b3d38ee015.gif)

**Comment by vamuzumd** [comment]
> @vamuzumd Yes, your instructions were very clear. Thank you for providing those. Here's a gif of me trying to repro it. Let me know if I'm doing something wrong. (ignore the odd mouse movements, I'm remoting into the machine and the mouse goes crazy when I record the screen)
> 
> ![2953](https://user-images.githubusercontent.com/21112697/83208471-9f257b00-a10a-11ea-9624-78b3d38ee015.gif)

I tried reproing this issue, but encountered another unusual behavior instead. When I try to paste the large string as user properties value by copying the long string and pasting it twice/thrice in the user value column, the properties dialog box suddenly vanishes.[the copy pasting might not be visible in the capture] Is there any way to support a large string for user properties? Attached gif with this unusual behaviour.
![StorageExplorerGif](https://user-images.githubusercontent.com/48073424/83211142-342b7280-a111-11ea-8d38-5c8f3d027b55.gif)

**Comment by MRayermannMSFT** [comment]
@vamuzumd

Let's first talk about large metadata (user properties). When you get a blob, the metadata is returned in the HTTP headers of the get request. Most services/web servers restrict header sizes to be in the range of **KBs**. I don't anticipate the design of blob metadata changing (to not be returned as headers) anytime soon but I'll still go ahead and pass along your feedback.

As for the dialog crashing, I'm not overly worried about it since you had to paste something so beyond the actual length limit for metadata. I will say though that I tested against our current development branch, and I was able to paste 14 times. After that I decided to just say "good enough". In our development branch we're using a newer version of electron, and I would suspect that it fixed the crashing problem.

Finally, let's get back to your original bug. **Are you able to reproduce it or no?**

**Comment by vamuzumd** [comment]
> @vamuzumd
> 
> Let's first talk about large metadata (user properties). When you get a blob, the metadata is returned in the HTTP headers of the get request. Most services/web servers restrict header sizes to be in the range of **KBs**. I don't anticipate the design of blob metadata changing (to not be returned as headers) anytime soon but I'll still go ahead and pass along your feedback.
> 
> As for the dialog crashing, I'm not overly worried about it since you had to paste something so beyond the actual length limit for metadata. I will say though that I tested against our current development branch, and I was able to paste 14 times. After that I decided to just say "good enough". In our development branch we're using a newer version of electron, and I would suspect that it fixed the crashing problem.
> 
> Finally, let's get back to your original bug. **Are you able to reproduce it or no?**

Thanks for passing along the feedback. I tried multiple times but was unable to repro the issue anymore, so will go ahead and close the issue.

**Comment by MRayermannMSFT** [comment]
Cool. Thanks for being understanding and hopeful! Have a good weekend. :)
