### ISSUE TITLE
Uploading files result in status OK, even if ACL verification fails

### ISSUE THREAD

**Issue by benimurza** [microsoft/AzureStorageExplorer#2955]
**Storage Explorer Version**: 1.13.0
**Build Number**: 20200430.5
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  Not sure

## Bug Description ##
Uploading a file to a folder where the user does not have write permissions results in status OK ("Uploaded Group: Uploaded: 1" and the green tick). However, the file is not shown in explorer, and isn't actually uploaded. Performing the same operation using the Azure portal results in the ACLVerificationFailed exception (which is correct).

## Steps to Reproduce ##
Upload a file via Storage Explorer to a folder where the user does not have permissions.

## Expected Experience ##
An Error/Exception in the Activities panel, pointing to missing ACLs.

## Actual Experience ##
Status OK, as if the upload succeeded.

**Comment by MRayermannMSFT** [comment]
@benimurza is this for ADLS Gen1 or Gen2?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
