### ISSUE TITLE
Ctrl + z (undo) doesn't work

### ISSUE THREAD

**Issue by apgapg** [microsoft/AzureStorageExplorer#2957]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:  

## Bug Description ##
Please incorporate ctrl+z option atleast when editing a document. Currently one needs to discard and redit if one misses something.

**Comment by craxal** [comment]
@apgapg Storage Explorer has not implemented any "Undo" support. Is this a feature request?

**Comment by apgapg** [comment]
Sorry i didn't knew ctrl+z isn't included. Should i create a feature request for that?

**Comment by craxal** [comment]
@apgapg You don't need to create a whole noew issue. You can edit your original comment using the feature request template we have. When filling out the template, please be specific about what you would expect from this kind of feature.

That said, what kind of undo operations are you looking for? If you'd like to undo blob deleted, then Storage Explorer already has support for Soft Delete. Anything beyond that, I can't make any promises. Data integrity is a core priority of Storage Explorer, and undo would be a _very_ expensive feature to add to Storage Explorer without any Azure platform support.

**Comment by apgapg** [comment]
i just look for undo while editing json of document.
for eg lets say i want to change value in json key 'abcd' but by mistake i change the value of other one. then i need to discard the change as i cant undo the wrong typo at that instant

**Comment by craxal** [comment]
@apgapg Storage Explorer does not have any in-app text editing. Are you using something else to edit your JSON document? If you could provide the app version and screenshots, that would be very helpful.

**Comment by ImrePyhvel** [comment]
Storage explorer DOES have in-app editing for CosmosDB JSON documents. Which does not have undo.

**Comment by craxal** [comment]
@ImrePyhvel Thank you for clarifying the context.

**Comment by ImrePyhvel** [comment]
Oh. There's also **CosmosDB query editor** which unfortunately also currently does not support undo. This has caused a F-moment more times than I'd like.

Is there anyone working on CosmosDB toolset at all? I'm not sure it has had any improvements in years.

**Comment by andrea-cassioli-maersk** [comment]
Any update on this issue? I have just seen document editor still does not support undo (I am using version 1.16.0). Seems a pretty basic functionality for a text-based editor.

**Comment by southpolesteve** [comment]
The Cosmos team recently deprecated our integration with Azure Storage Explorer. [Here is the full deprecation notice from the 1.15.1 Storage Explorer release notes:](https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.15.1)

> The Azure Cosmos DB integration with Storage Explorer has been deprecated. Any existing functionality will not be removed for a minimum of one year from this release. Users should use the Azure Portal, the Azure Portal desktop app, or the standalone Cosmos Explorer instead – all of which contain many new features that aren’t currently supported in Storage Explorer. Additionally, the Azure Cosmos DB team has also open sourced the data explorer project and will be investing in their own desktop tooling at a later date. Please keep an eye on their repository for more information. 

Currently, we are not prioritizing new features or bug fixes for Cosmos in Azure Storage Explorer. If you the issue you are reporting also applies to the Azure Portal or https://cosmos.azure.com, please file an issue in [our open source Cosmos Explorer repo](https://github.com/Azure/cosmos-explorer)
