### ISSUE TITLE
Make it possible to execute just the selected text in Cosmos DB query tab

### ISSUE THREAD

**Issue by thomaslevesque** [microsoft/AzureStorageExplorer#296]
**Storage Explorer Version**: 1.2
**Platform/OS Version**: Windows 10
**Architecture**: x64
**Regression From**: N/A

#### Steps to Reproduce: ####
1. Open a query tab on a CosmosDB collection
2. Enter two different queries in this tab
3. Select the text of one of the queries
4. Click "Execute Query"

#### Expected Experience: ####
Only the selected query should be executed.

#### Actual Experience: ####
Azure Storage Explorer attempts to execute the whole text as if it was a single query, which returns an error.

(I described it as if it were a bug report, following the template, but it's actually a feature request)

**Comment by thomaslevesque** [comment]
If you do implement this, please make the query text area resizable. It's too small to contain multiple queries.

**Comment by thomaslevesque** [comment]
Oh, and add a keyboard shortcut for "Execute Query". Having to leave the keyboard to take the mouse is annoying. Also, the most obvious shortcut (Ctrl-R) currently reloads the whole app, losing all open tabs...

**Comment by ziyel** [comment]
@thomaslevesque Thanks for the feedback. Actually for executing the selected text in query tab has already in our backlog. We will prioritize it.

And we have a issue related to the resizable of query text area https://github.com/Microsoft/AzureStorageExplorer/issues/167.

**Comment by thomaslevesque** [comment]
Thanks @ziyel!

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
