### ISSUE TITLE
Address bar feature

### ISSUE THREAD

**Issue by iatodoro** [microsoft/AzureStorageExplorer#2960]
**Is your feature request related to a problem? Please describe.**
We have some storage accounts with many hundreds or thousands of blob containers. Currently it's basically impossible to use storage explorer for these accounts because it loads the first couple of dozen blob containers and shows a "Load more" link, which loads another couple dozen, and so on. So finding a blob container that may be buried under 500 others takes a very long time.

**Describe the solution you'd like**
An address bar where I can type in the exact blob container location that will take me there directly without having to navigate through a very large list.

**Describe alternatives you've considered**
The "Search from here" feature either is broken or cannot handle the large number of blob containers as it takes an extremely long time to show any search results.

I could also use the Azure portal to navigate but then what's the point of Storage Explorer?

**Additional context**
None

**Comment by MRayermannMSFT** [comment]
Let's investigate possible solutions to this in 1.16

**Comment by craxal** [comment]
@iatodoro What kind of path are you expecting to enter into this address bar? Do you want to be able to enter in the Storage Explorer node path, the resource ID, or both?

**Comment by MRayermannMSFT** [comment]
We added an editable address bar in 1.15.0. If it doesn't meet your expectations, please open a new feature request detailing what it is missing. Thanks!

**Comment by craxal** [comment]
@MRayermannMSFT This issue is about an address bar on the _left_ side, not the right side. The user wants to be able to enter a path to a blob container.

**Comment by jinglouMSFT** [comment]
We have done some optimization work for the left hand side search in the latest releases. Search should be more performant. @iatodoro does the new search work ok for your scenario?

**Comment by craxal** [comment]
@iatodor To add to @jinglouMSFT, we've added search features that let you filter on the resource types of your search to only blob containers. Also, if you don't need to search across multiple storage accounts, you can right-click the "Blobs" node under a storage account node and use the "Open by Name" feature. Here you can search for a container by name and select a container to open from a list of results.

**Comment by MRayermannMSFT** [comment]
I'm going to close this issue now. When 1.32.0 ships there will be a variety of features available to make it easier to find a container in a storage account that has many hundreds:

1. Search from here (introduced pre-1.0.0): right click on the "Blob Containers" node for your account, choose "Search From Here", enter the name of the container you want to find, press enter
2. Open by Name (introduced at least a year ago or so): right click on the "Blob Containers" node for your account, choose "Open by Name...", enter the name of or a prefix of the name ofthe container you want to find, press enter
3. View All (available starting with 1.32.0): go to **Settings** → **Services**  → **Storage Accounts** → **Storage Nodes Trailing Action** and choose **View all** from the dropdown menu, then, go epand the "Blob Containers" node for your account, and click on "View All" at the end of the list of containers, you should now have a data explorer open on the right-hand side that lists all containers, with a prefix-filter box at the top of the list (see below screenshot for example).

![image](https://github.com/microsoft/AzureStorageExplorer/assets/21112697/bbc488bd-0a9e-4de7-be82-15dc4d6aedcf)
