### ISSUE TITLE
Show consistent actions in activities for emulator and regular blobs when deleting blobs with snapshots

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2962]
**Storage Explorer Version:** 1.14.0-dev
**Branch**: master
**Build**: [20200512.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3719948&view=results)
**Platform/OS:** Windows 10/ macOS Catalina / Linux Ubuntu 16.04
**Emulator**: 5.10.0.0
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Make sure the Storage Emulator has been started.
2. Expand the 'Emulator - Default Ports(Key)' -> 'Blob Containers' node.
3. Create a new blob container -> Upload one blob to it -> Create snapshots for this blob.
4. Try to delete the blob -> Check the activity log.

**Expect Experience:**
The activity log shows below for one regular blob.
![image](https://user-images.githubusercontent.com/54055206/81665161-f670ed80-9472-11ea-8a97-5bcd6cfbf9bc.png)

**Actual Experience:**

1. The activity log shows below for one emulator blob.
2. No 'Retry AzCopy' dialog pops up when clicking Retry.
![image](https://user-images.githubusercontent.com/54055206/81665157-f4a72a00-9472-11ea-8ce8-ba280a8b4cde.png)

**Comment by MRayermannMSFT** [comment]
This will be fixed once AzCopy supports doing delete against emulator. We're not going to track this for now.
