### ISSUE TITLE
Improve the Connect experience

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#2965]
**Is your feature request related to a problem? Please describe.**
The variety of ways Storage Explorer can connect to Azure Storage resources has grown in recent years, and thus the complexity of the Connect dialog has become more complex. Users may have difficulty understanding how to use the dialog to connect to their resources.

**Describe the solution you'd like**
An improved Connect dialog experience that asks users clear and concise questions in order to get exactly the information needed to connect to their resources. Some things to consider when designing the new experience:
- Connections have two essential parts: information needed to find the resource and credentials to authenticate requests.
- Icons to visually highlight the different top-level questions/options. For example, use the icon for blob containers to inform the user that an option is for connecting to a blob container. Or use a key icon to indicate an option is for authenticating using an account key or a SAS.

**Describe alternatives you've considered**
N/A

**Additional context**
Since this work is intended to make the experience better for users, please leave your comments to give us a better idea of how to make this experience better.

**Comment by slothworld** [comment]
I am using Storage Explorer in a Windows Virtual Desktop environment. Multiple users logged in to a single host and opening Storage Explorer. If one of those users tries to upgrade the app, an error is thrown....files in use. Is there a way to disable the update notification?? This would take away the ability for individual users to upgrade the app on their own. I would have admins during maintenance windows to update the app.
Thank you

**Comment by craxal** [comment]
@slothworld I would suggest creating a new feature request for that, and give some more detail about the error you receive, including repro steps and screenshots. This issue is primarily focused on the current Connect dialog experience and not installation or upgrade.

**Comment by craxal** [comment]
Related to #603

**Comment by Niharikadutta** [comment]
@craxal What Storage explorer version has this change? I have v1.20.1  and am still not able to connect to a public storage account without any authentication:

![image](https://user-images.githubusercontent.com/8151864/134077710-00a162df-47c2-4709-9b69-4eeb712495e6.png)
