### ISSUE TITLE
Navigate to an unexpected page when pasting one direct link to Microsoft Edge again

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2966]
**Storage Explorer Version:** 1.13.0
**Branch**: hotfix/1.13.1
**Build**: [20200513.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3723540&view=results)
**Platform/OS:** Windows 10
**Architecture**: ia32
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Select one storage account -> Select 'Copy Direct Link to Account'.
3. Paste the link to browser **Microsoft Edge** (Make sure the Edge keeps open).
4. Click 'Open' on the prompt dialog -> Repeat step 2 & 3. 
5. Check the result.

**Expect Experience:**
Prompt the below dialog.
![image](https://user-images.githubusercontent.com/41351993/81790560-246c3580-9538-11ea-8c6f-ae591231420e.png)

**Actual Experience:**
Navigate to the below page.
![image](https://user-images.githubusercontent.com/41351993/81790664-4bc30280-9538-11ea-8f4a-dcfc8265600f.png)

**More Info:**
1. This issue doesn't reproduce when using **Internet Explorer / Google Chrome.**
2. The Microsoft Edge version:
![image](https://user-images.githubusercontent.com/41351993/81790025-621c8e80-9537-11ea-8cbe-8619b5204783.png)

**Comment by MRayermannMSFT** [comment]
Looks like an edge issue.
