### ISSUE TITLE
File download fails if path contains a folder with an empty name

### ISSUE THREAD

**Issue by john-adkins** [microsoft/AzureStorageExplorer#2967]
**Storage Explorer Version**: 1.13.0
**Build Number**: 20200430.5
**Platform/OS**: Windows 10? 
**Architecture**: x64?

## Bug Description ##
It's possible to have a blob live inside a folder that has an empty string for its name. In this scenario a blob download fails because the empty folder is removed from the path given the AzCopy command.

## Steps to Reproduce ##
I'm not sure it's possible to create a folder without a name anymore but previously this was allowed.

## Expected Experience ##
File should download.

## Actual Experience ##
Download fails because the path is altered incorrectly. Instead of downloading a file from "/myfolder//myfile.txt" storage explorer attempts to download "/myfolder/myfile.txt".

**Comment by jinglouMSFT** [comment]
This is a dup of #1512.
