### ISSUE TITLE
Unable to add Azure account to Storage explorer   

### ISSUE THREAD

**Issue by sharavan86** [microsoft/AzureStorageExplorer#2968]
I am trying to add Azure account to storage explorer, but it throws the below error
`{
  "message": "\"Failed to acquire token silently as no token was found in the cache. Call method AcquireToken\""
}`

**Comment by jinglouMSFT** [comment]
Can you tell us a bit more info?  Which version of Storage Explorer you are using?  On which platform? Were you ever able to add Azure account before or this just happened to you?  Have you tried to delete following?  Note, you need to close Storage Explorer before you do the delete. Also, if you have imported any SSL before, back them up before you delete the following files.  Once you restart SE, you can reimport the SSLs. 

Windows: %AppData%/StorageExplorer
macOS: /Users/<your_name>/Library/Application Support/StorageExplorer
Linux: ~/.config/StorageExplorer

**Comment by acrigney** [comment]
I have the latest version running on Win 10 and I have not been able to login with the storage explorer for a week. Looks like I had better download an old version if I can.
I get no errors just it keeps asking for credentials again.

**Comment by MRayermannMSFT** [comment]
@sharavan86 @acrigney 

For this type of issue it is important that we know your:

- OS
- Storage Explorer version

Please provide that information, and then we'll be able to help.

**Comment by acrigney** [comment]
Win 10, I tired with versions 1.12.0 and the latest version.

**Comment by MRayermannMSFT** [comment]
@acrigney and @sharavan86, can you try the following when y'all have time?
1. Update to version 1.14.0
2. Enable MSAL and verbose authentication logging. Each can be found under Settings (gear icon on the left) -> Application -> Sign-in
3. Close Storage Explorer
4. In file explorer, go to C:\Users\<your username>\AppData\Local\Temp\servicehub and delete the folder `logs`. Leave file explorer open.
5. Re-open Storage Explorer
6. Sign in. You may have to enter credentials a few times depending on what tenants you belong to and their various multi factor requirements. I'd recommend not closing your browser window until Storage Explorer has stopped asking for credentials.
7. If you're still unable to get fully signed in in step 6, then go back to file explorer, zip up the logs folder, and attach it here. We'll take a look at it.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems. Thanks.
