### ISSUE TITLE
Preserve timestamp with azCopy --persist-smb-info when copy from/to file shares

### ISSUE THREAD

**Issue by PrismaComputer** [microsoft/AzureStorageExplorer#2969]
Please urgently add support of preserving the files timestamp with azCopy --persist-smb-info when copying from one azure file share to another azure file share.
This is supported since azCopy 10.4. The feature should be enabled and used by default.

**Comment by MRayermannMSFT** [comment]
Checked in for 1.14 release. Work completed jointly by me and @JasonYeMSFT (github won't let me change the issue owner)

**Comment by jcpayne** [comment]
@MRayermannMSFT can you please explain how to make Storage Explorer preserve times and dates when it copies blobs?  You've indicated that it is done but I can't figure out how to do it.  Thanks.
