### ISSUE TITLE
Allow update or deletion of documents returned by queries

### ISSUE THREAD

**Issue by thomaslevesque** [microsoft/AzureStorageExplorer#297]
**Storage Explorer Version**: 1.2
**Platform/OS Version**: Windows 10
**Architecture**: x64
**Regression From**: N/A

#### Steps to Reproduce: ####
1. Execute a query in a Cosmos DB query tab

#### Expected Experience: ####
The documents in the result should be individually editable and deletable.

#### Actual Experience: ####
The result is shown as a read-only view of the JSON.

(I described it as if it were a bug report, following the template, but it's actually a feature request)

**Comment by jinglouMSFT** [comment]
CosmosDB has been removed from Storage Explorer.
