### ISSUE TITLE
Miss the account name in URL for one new created emulator blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2973]
**Storage Explorer Version:** 1.13.1
**Build**: [20200514.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3726966&view=results)
**Branch**: hotfix/1.13.1
**Platform/OS:** Windows 10
**Architecture**: ia32
**Azurite Version:** 3.5.0
**Regression From:** Not a regression

**Steps to reproduce:**
1. Install and run Azurite -> Launch Storage Explorer.
2. Expand Local & Attached -> Storage Accounts-> (Emulator - Default Ports) (Key) -> Blob Containers.
3. Create a new blob container -> Check the URL on Properties panel.

**Expect Experience:**
Show a correct URL.

![image](https://user-images.githubusercontent.com/41351993/81917142-64e6b480-9607-11ea-982c-d0f5fb4dc096.png)

**Actual Experience:**
Miss the account name in URL.
![image](https://user-images.githubusercontent.com/41351993/81917131-60ba9700-9607-11ea-9e63-f144dea7e1d5.png)

**More Info:**
1. This issue also reproduces for emulator blob containers under Quick Access.
2. This issue doesn't reproduce for queues and tables.

**Comment by craxal** [comment]
@JasonYeMSFT Is this related to to any hotfix changes?

**Comment by JasonYeMSFT** [comment]
No, it actually regresses at the point we implement the BlobContainerProducer.
