### ISSUE TITLE
No related bug shows for the last hotfix in Release Notes Hotfixes part

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2974]
**Storage Explorer Version:** 1.13.1
**Build**: [20200514.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3726966&view=results)
**Branch**: hotfix/1.13.1
**Platform/OS:** Windows 10/ macOS Mojave/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Go to 'Help' -> View Release Notes.
2. View the last hotfix in Hotfixes part.

**Expect Experience:**
Show a related bug.

**Actual Experience:**
No related bug shows.
![image](https://user-images.githubusercontent.com/41351993/81918017-8a27f280-9608-11ea-9765-7fe773b83d56.png)

**Comment by craxal** [comment]
@v-xianya By design. There is no associated bug. It's just something we found and felt needed to be fixed. Not every bullet point has to have an issue associated with it.

**Comment by jinglouMSFT** [comment]
This was from Ze:

I encountered an issue while generating SAS in 1.13, and wanted to report it to you.

1.	Create a policy with all permissions
 

2.	Create a SAS for a specific blob using the above policy
a.	The result is https://zemaintest.blob.core.windows.net/bar2/bla.txt?sv=2019-02-02&si=bar2-1720577EA61&sr=c&sig=8qoG94DAZSEPje4POp4%2F6WG02g0s21bENyc0rxvo8LE%3D
b.	Note the “sr=c”, which doesn’t seem correct
3.	Try to download the blob by pasting the URL into a browser
<Error>
<Code>AuthenticationFailed</Code>
<Message>
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:8e2cb818-e01e-000d-31d4-272027000000 Time:2020-05-11T20:41:31.2257543Z
</Message>
<AuthenticationErrorDetail>
Signature did not match. String to sign used was /blob/zemaintest/bar2 bar2-1720577EA61 2019-02-02 c
</AuthenticationErrorDetail>
</Error>

I tried with StgExp 1.11, the generated SAS works fine: https://zemaintest.blob.core.windows.net/bar2/bla.txt?sv=2018-03-28&si=bar2-1720577EA61&sr=b&sig=NfX0Ep%2BMrQyr5qxNLUABupGBIEWMnxbGYTTJ4sFN6uo%3D. Note the “sr=b”.
