### ISSUE TITLE
An error occurs after pasting an emulator service's SAS URI to 'Attach with SAS URI' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2975]
**Storage Explorer Version:** 1.13.1
**Build**: [20200514.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3726966&view=results)
**Branch**: hotfix/1.13.1
**Platform/OS:** Windows 10
**Architecture**: ia32
**Azurite Version:** 3.5.0
**Regression From:** Previous release (1.13.0)

**Steps to reproduce:**
1. Install and run Azurite -> Launch Storage Explorer.
2. Expand Local & Attached -> Storage Accounts-> (Emulator - Default Ports) (Key) -> Blob Containers.
3. Create a blob container -> Right click it -> Select 'Get Shared Access Signature...'.
4. Copy the URI -> Open Connect Dialog -> Select 'Use a shared access signature (SAS) URI'.
5. Click 'Next' ->  Paste the URI.
6. Check the result.

**Expect Experience:**
No error occurs.

**Actual Experience:**
An error occurs.
![image](https://user-images.githubusercontent.com/41351993/81919025-dc1d4800-9609-11ea-91b3-65f1b15104e6.png)

**More Info:**
This issue also reproduces for one emulator queue and table. **Show the same error as blob containers.**

**Comment by craxal** [comment]
@jinglouMSFT @MRayermannMSFT @JasonYeMSFT I wasn't aware we could even generate a SAS for an emulator account, nor do I recall ever "officially" supporting connecting to an emulator through SAS. What changed to cause this bug to surface?

**Comment by JasonYeMSFT** [comment]
We don't support generating SAS for emulator account but we support generating SAS for blob containers in it. In 1.13.0, the SAS url is incorrect by missing the "devstoreaccount1" in the url. Since we have added it back, the SAS validation logic considers it to a blob instead of a blob container thus showing the error.

**Comment by MRayermannMSFT** [comment]
Let's start with changing the error to say we don't support the "attach emulator" scenario.

**Comment by JasonYeMSFT** [comment]
A fix to change the error to say "Attaching to development account is not supported" is merged.
