### ISSUE TITLE
Fail to clone one emulator blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2976]
**Storage Explorer Version:** 1.13.1
**Build**: [20200514.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3726966&view=results)
**Branch**: hotfix/1.13.1
**Platform/OS:** Windows 10
**Architecture**: ia32
**Azurite Version:** 3.5.0
**Regression From:** Previous release (1.12.0)

**Steps to reproduce:**
1. Install and run Azurite -> Launch Storage Explorer.
2. Expand Local & Attached -> Storage Accounts-> (Emulator - Default Ports) (Key) -> Blob Containers.
3. Create a new blob container -> Upload files to it.
4. Clone the blob container with a new name.

**Expect Experience:**
Succeed to clone.
![image](https://user-images.githubusercontent.com/41351993/81919515-885f2e80-960a-11ea-97a8-759f8682f60d.png)

**Actual Experience:**
Fail to clone.
![image](https://user-images.githubusercontent.com/41351993/81919504-85fcd480-960a-11ea-8cac-f1e0f00355a1.png)

**More Info:**
This issue also reproduces for cloning emulator blobs.
![image](https://user-images.githubusercontent.com/41351993/81919926-08859400-960b-11ea-88c1-e91e74719e52.png)

**Comment by craxal** [comment]
@v-xianya The error is coming from the emulator. Have you tried starting Azurite as the error message suggests?

**Comment by JasonYeMSFT** [comment]
I was able to reproduce the issue and in my repro case, adding the --loose parameter will be able to unblock the scenario.

**Comment by v-xianya** [comment]
This issue can be resolved by switching to loose model.
