### ISSUE TITLE
An error occurs when uploading one folder under sort by blob type

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2977]
**Storage Explorer Version:** 1.13.1
**Build**: [20200514.2]()
**Branch**: hotfix/1.13.1
**Platform/OS:** Windows 10/ macOS Mojave/ Linux Ubuntu 16.04
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one storage account -> Blob Containers.
2. Create a new blob container -> Upload folders and blobs to it.
3. Click 'Blob Type' column in Editor. 
4. Try to upload new folder to it -> Check the result.

**Expect Experience:**
The folder shows well in the blob container and no error occurs.

**Actual Experience:**

1. The blob container auto closed.
2. An error occurs.
![image](https://user-images.githubusercontent.com/54055206/81920846-5b138000-960c-11ea-8e05-f63eb925d13e.png)

**More Info:**
This issue also reproduces when sorting by other properties that the folder do not have.
![image](https://user-images.githubusercontent.com/54055206/81920874-6666ab80-960c-11ea-8411-5a1bb364605e.png)

**Comment by MRayermannMSFT** [comment]
Related to https://github.com/microsoft/AzureStorageExplorer/issues/2978

**Comment by JasonYeMSFT** [comment]
A fix has been merged so that the sorting can be done properly. Given that the sort can be done in very short time, it is unlikely that the user can upload a blob while sorting.
