### ISSUE TITLE
Always keep loading when sorting by lease state for blobs

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2978]
**Storage Explorer Version:** 1.13.1
**Build**: [20200514.2]()
**Branch**: hotfix/1.13.1
**Platform/OS:** Windows 10/ macOS Mojave/ Linux Ubuntu 16.04
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one storage account -> Blob Containers.
2. Upload two blobs to it -> Click 'Lease State' column in Editor.
3. Check the result.

**Expect Experience:**
Everything works well.

**Actual Experience:**
1. Always keep loading in Editor.
![image](https://user-images.githubusercontent.com/54055206/81921478-497ea800-960d-11ea-8e86-5a1aa57d1ee5.png)
2. An error occurs after manually refresh and the blob container auto closed.
![image](https://user-images.githubusercontent.com/54055206/81921509-54d1d380-960d-11ea-8a50-2897a8270440.png)

**Comment by MRayermannMSFT** [comment]
Seems that sorting by other columns will get rid of the infinite loading.

**Comment by JasonYeMSFT** [comment]
A fix has been merged.
