### ISSUE TITLE
Graph Filter Box Extension

### ISSUE THREAD

**Issue by chrisparkeronline** [microsoft/AzureStorageExplorer#2979]
**Is your feature request related to a problem? Please describe.**
Writing long or complex queries in the entry field for graph databases are very difficult because of the short entry field size. This forces users to use the Data Explorer in azure portal as it has a much wider field of entry.

**Describe the solution you'd like**
Could you extend the entry field to the width of the window or allow the entry to expand vertically to fit the size of the query text.

**Describe alternatives you've considered**
Currently using the Data Explorer within the Azure portal, but as it is new, it has a bug that renders the whole tab blank or freezes during heavy use in Chrome.

**Additional context**
![Untitled](https://user-images.githubusercontent.com/16803487/81978535-4675be80-95f1-11ea-9ac8-dc4915223287.png)

**Comment by chrisparkeronline** [comment]
**Story:**
As a Azure Data Explorer user, I would like the graph database query/filter entry field extended to the length of the panel or vertically extended to fit the length of the query, so that I can see my long transversals without having to scroll.

**Story Points**
1

**Effort**
Unknown (my assumption is minimal but I could totally be wrong!)

**Business Value**
100

**Business Area**
Architectural

**Comment by southpolesteve** [comment]
The Cosmos team recently deprecated our integration with Azure Storage Explorer. [Here is the full deprecation notice from the 1.15.1 Storage Explorer release notes:](https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.15.1)

> The Azure Cosmos DB integration with Storage Explorer has been deprecated. Any existing functionality will not be removed for a minimum of one year from this release. Users should use the Azure Portal, the Azure Portal desktop app, or the standalone Cosmos Explorer instead – all of which contain many new features that aren’t currently supported in Storage Explorer. Additionally, the Azure Cosmos DB team has also open sourced the data explorer project and will be investing in their own desktop tooling at a later date. Please keep an eye on their repository for more information. 

Currently, we are not prioritizing new features or bug fixes for Cosmos in Azure Storage Explorer. If you the issue you are reporting also applies to the Azure Portal or https://cosmos.azure.com, please file an issue in [our open source Cosmos Explorer repo](https://github.com/Azure/cosmos-explorer)
