### ISSUE TITLE
Issues signing into Storage Explorer when using MFA

### ISSUE THREAD

**Issue by ymaxwell** [microsoft/AzureStorageExplorer#2980]
**Storage Explorer Version**: 1.13.0
**Build Number**: 20200430.5
**Platform/OS**: Windows 
**Architecture**: ia32
**Regression From**:  

## Bug Description ##

When I try to authenticate to pull up Storage Resources I get the following error when signing in while using MFA.
{
"message": ""email address' returned by service does not match user 'userprincipalname' in the request""
}
## Steps to Reproduce ##

User resets Azure Storage Explorer OR uninstall and re-installs it
Click Add an Azure Account
Enter UserPrincipalName
Gets directed to company SSO platform (taking you to your organization's sign-in page)
Successfully authenticates with SSO platform. (administrators can see a successful authentication for Office-365 in SSO platform logs)
User sees warning that UserPrinicipal Name could not be loaded. Please try reentering credentials or removing and re-adding the account. 
User authenticates again with SSO platform, this time the Id shows as email instead of userprincipalname
User authenticates again successfully
User is finally presented with error 
Unable to sign in: _User 'email' returned by service does not match user 'userprincipalname' in the request""_

## Additional Context ##

![image](https://user-images.githubusercontent.com/8505005/81982824-fa7a4800-95f7-11ea-89c8-d9fd66933642.png)
![image](https://user-images.githubusercontent.com/8505005/81984890-17fce100-95fb-11ea-80a8-9727260ca404.png)
![image](https://user-images.githubusercontent.com/8505005/81984942-29de8400-95fb-11ea-8e2f-318da206ddd9.png)

![image](https://user-images.githubusercontent.com/8505005/81985125-73c76a00-95fb-11ea-8dbc-6bde0e6131e8.png)
![image](https://user-images.githubusercontent.com/8505005/81985214-93f72900-95fb-11ea-9ccd-600f05e2d65e.png)

**Comment by MRayermannMSFT** [comment]
@ymaxwell could you please do the following?

1. Update to version 1.14.0
2. Enable MSAL and verbose authentication logging. Each can be found under Settings (gear icon on the left) -> Application -> Sign-in
3. Close Storage Explorer
4. In file explorer, go to C:\Users\<your username>\AppData\Local\Temp\servicehub and delete the folder `logs`. Leave file explorer open.
5. Re-open Storage Explorer
6. Sign in
7. Once you get to the error message, go back to file explorer, zip up the logs folder, and attach it here.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems. Thanks.
