### ISSUE TITLE
failed to log in with account and password 

### ISSUE THREAD

**Issue by Shanon666** [microsoft/AzureStorageExplorer#2983]
**Storage Explorer Version**:1.13.0
**Build Number**: 20200430.5
**Platform/OS**: Windows
**Architecture**: X64
**Regression From**:  It was working in 1.12.0, while failed in 1.13.0 

## Bug Description ##
when we install Azure Storage Explorer 1.13.0 directly, when we tried to log in with Mooncake (China) Azure accounts ,will get error “AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: '04b07795-8ddb-461a-bbee-02f9e1bf7b46'.”

## Steps to Reproduce ##
download and install Azure Storage Explorer 1.13.0，then connect Azure China with account .

## Expected Experience ##
show storage accounts and managed disks 

## Actual Experience ##

![image](https://user-images.githubusercontent.com/58842626/82028127-cd956600-96c7-11ea-8b49-29971ca0582f.png)

Request Id: d16ce413-cbe6-4d24-bcac-4eed3d453800
Correlation Id: 2da1d7b3-198d-4b4a-a949-785210ddc996
Timestamp: 2020-05-15T02:23:55Z
Message: AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: '04b07795-8ddb-461a-bbee-02f9e1bf7b46'.

## Additional Context ##

If you are using an old version (e.g. 1.12.0) and conenct to Azure, then update to 1.13.0 ,please do not sign out, or you may cannot login agiain. 

BTW, you still can use SAS token or storage account Key for login temporarily.

**Comment by jinglouMSFT** [comment]
We are investigating the issue.  Please give us a day or two.  Meanwhile, please use the workaround mentioned above.  Thanks.

**Comment by MRayermannMSFT** [comment]
@Shanon666 the issue causing your sign in to fail has now been fixed. Please try using version 1.13.0 again and let us know how it goes. Thanks.

**Comment by Shanon666** [comment]
Thanks a lot for your quick fix， I have tested the issue is fixed in the newest version 1.13.1 .

**Comment by mohag** [comment]
> Thanks a lot for your quick fix， I have tested the issue is fixed in the newest version 1.13.1 .

Somehow check for updates says "no updates available" on 1.10.1, which shows a copyright date of 2023, which seems strange if 1.13.1 was available in 2020....
