### ISSUE TITLE
The Quick Access node takes more than one minute to expand when contains emulator queues with Azurite stopped

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2985]
**Storage Explorer Version:** 1.13.1
**Build**: [20200515.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3730601&view=results)
**Branch**: hotfix/1.13.1
**Platform/OS:** Windows 10
**Architecture**: ia32
**Azurite Version:** 3.7.0
**Regression From:** Not a regression

**Steps to reproduce:**
1. Run and install Azurite -> Launch Storage Explorer.
2. Expand Local & Attached -> Storage Accounts -> (Emulator - Default Ports) (Key).
3. Add one emulator queue to Quick Access.
4. Stop Azurite and restart Storage Explorer.
5. Observe the Quick Access node.

**Expect Experience:**
It's better to reduce the expanding time.

**Actual Experience:**
The Quick Access node takes more than one minute to expand.
![image](https://user-images.githubusercontent.com/41351993/82030188-aa1fea80-96ca-11ea-992b-fd18242a214d.png)

**Comment by craxal** [comment]
@JasonYeMSFT Frankly, I think Quick Access takes too long to load in general. Do we know why?

**Comment by JasonYeMSFT** [comment]
It was because we were awaiting all node promises to resolve before showing them. If an emulator container node is there but the emulator is not on, the loading won't end until those requests timeout.
