### ISSUE TITLE
Storage Explorer 1.13.0 | No silent install possible /VERYSILENT /NORESTART

### ISSUE THREAD

**Issue by maxleonalbrecht** [microsoft/AzureStorageExplorer#2987]
**Storage Explorer Version**: 1.13.0
**Build Number**: / 
**Platform/OS**: Windows Server 2012 R2
**Architecture**: x64
**Regression From**:  1.12.0

## Bug Description ##
StorageExplorer.exe /VERYSILENT /NORESTART prompts a windows where a user can decide, if the Storage Explorer will be installed for all users or for the user logged in.

![image](https://user-images.githubusercontent.com/8051297/82061991-ba839580-96c9-11ea-88e2-345ef11a45cc.png)

So on a automated install of the user in the background is not possible anymore

## Steps to Reproduce ##
1. Download StorageExplorer.exe
2. Execute "./StorageExplorer.exe /VERYSILENT /NORESTART"

## Expected Experience ##
Silent install of the Storage Explorer without any prompts.

**Comment by asjimene** [comment]
Adding the /ALLUSERS install flag seems to help here.

**Comment by maxleonalbrecht** [comment]
/ALLUSERS or /CURRENTUSERS helps to answer this prompt for unattended installation of the Azure Storage Explorer.

After typing /? you can see more installation parameters. 

![image](https://user-images.githubusercontent.com/8051297/82253474-583cc600-9951-11ea-866e-6b6a9da1b0ed.png)

**Comment by craxal** [comment]
@maxleonalbrecht I'll double-check the setup scripts. We may have inadvertently disabled silent installs for single users. Thanks for bringing this to our attention!

**Comment by craxal** [comment]
@maxleonalbrecht Are you trying to install Storage Explorer for all users or just for yourself? Do either of these commands work?

```cmd
StorageExplorer1.13.1.exe /VERYSILENT /NORESTART /CURRENTUSER
StorageExplorer1.13.1.exe /VERYSILENT /NORESTART /ALLUSERS
```

If they do not work, then we can investigate further. If they do, then would you consider this issue resolved?

**Comment by maxleonalbrecht** [comment]
These commands work, as I stated before.

I consider the issue as solved.
The thing is, that `/VERYSILENT ` as command alone does not work anymore standalone and needs starting from the 1.13.0 `/CURRENTUSER` or `/ALLUSERS`
