### ISSUE TITLE
Getting various errors when I try to delete a nameless blob folder and a folder named the same as a file

### ISSUE THREAD

**Issue by untilted-document** [microsoft/AzureStorageExplorer#2989]
Been struggling using SAS in a bat file, I ended up trying various commands, the following included:

```
azcopy copy myfile.zip https://my.blob.core.windows.net/mycont/myfile.zip\?sv^=2019-02-02^&st^=2020-05-16T14%%3A45%%3A03Z^&se^=2030-05-17T14%%3A45%%3A00Z^&sr=c^&sp^=racwdl^&sig^=redactedREDACTEDredactedREDACTEDredacted%%3D

azcopy copy myfile.zip https://my.blob.core.windows.net/mycont/\?sv^=2019-02-02^&st^=2020-05-16T14%%3A45%%3A03Z^&se^=2030-05-17T14%%3A45%%3A00Z^&sr=c^&sp^=racwdl^&sig^=redactedREDACTEDredactedREDACTEDredacted%%3D

azcopy copy myfile.zip https://my.blob.core.windows.net/mycont\?sv^=2019-02-02^&st^=2020-05-16T14%%3A45%%3A03Z^&se^=2030-05-17T14%%3A45%%3A00Z^&sr=c^&sp^=racwdl^&sig^=redactedREDACTEDredactedREDACTEDredacted%%3D

azcopy copy myfile.zip https://my.blob.core.windows.net/mycont?sv^=2019-02-02^&st^=2020-05-16T14%%3A45%%3A03Z^&se^=2030-05-17T14%%3A45%%3A00Z^&sr=c^&sp^=racwdl^&sig^=redactedREDACTEDredactedREDACTEDredacted%%3D
```

Couldn't get it working with all the crazy escaping, but I've ended up with some blob folders I dont want. One has no name, and one folder has the same name as the file I was trying to upload. I uploaded the MYFILE.ZIP file properly using ASE. It is the topmost file in this picture. I will discuss it more later:

![image](https://user-images.githubusercontent.com/18049243/82126203-07876a80-97a3-11ea-842d-e3837254fecc.png)

If I look inside the nameless folder, i see a nameless file, its size is the right size for what I'm trying to upload:

![image](https://user-images.githubusercontent.com/18049243/82126218-284fc000-97a3-11ea-9abc-4f0cb12a7065.png)

And now when trying to delete these in ASE, I see a javascripty "couldn't read x of undefined" error:

![image](https://user-images.githubusercontent.com/18049243/82126235-50d7ba00-97a3-11ea-8dbd-e019a262f1a0.png)

And the whole files pane disappears:

![image](https://user-images.githubusercontent.com/18049243/82126266-94322880-97a3-11ea-8854-4b6e671197cd.png)

And when I click back into the container, I see that my legit file called MYFILE.ZIP uploaded with ASE, has been deleted, but the folder called MYFILE.ZIP and the folder with the blank name are still there:

![image](https://user-images.githubusercontent.com/18049243/82126315-d8bdc400-97a3-11ea-92ef-0a9de89b3e48.png)

(Look a few screenshots up, you can see there were once 4 things in this container, now there are 3, and my legit file, where the blue star is, is gone but the folders I want to delete, remain

If i try click on the nameless folder and delete it (on its own) I get a logged error:

```
2020/05/16 17:39:28 ==> REQUEST/RESPONSE (Try=1/35.1261ms, OpTime=99.952ms) -- RESPONSE STATUS CODE ERROR
   DELETE https://my.blob.core.windows.net/my/?se=2020-06-15t17%3A39%3A28z&sig=-REDACTED-&sp=rdl&sr=c&sv=2018-03-28&timeout=901
   User-Agent: [Microsoft Azure Storage Explorer, 1.13.0, win32,  AzCopy/10.4.2 Azure-Storage/0.7 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [9b5d91f9-ce04-4b7c-4a82-6a8aafa93068]
   X-Ms-Version: [2019-02-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 400 The requested URI does not represent any resource on the server.
   Content-Length: [453]
   Content-Type: [application/xml]
   Date: [Sat, 16 May 2020 17:39:29 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [InvalidUri]
   X-Ms-Request-Id: [5bf92407-b01e-008d-24a8-2b3816000000]
Response Details: ﻿<Code>InvalidUri</Code><Message>The requested URI does not represent any resource on the server. </Message><UriPath>https://my.blob.core.windows.net/my/?se=2020-06-15T17:39:28Z&amp;sig=-REDACTED-&amp;sp=rdl&amp;sr=c&amp;sv=2018-03-28&amp;timeout=901</UriPath>

2020/05/16 17:39:28 ERR: [P#0-T#0] https://my.blob.core.windows.net/my/?se=2020-06-15t17%3A39%3A28z&sig=-REDACTED-&sp=rdl&sr=c&sv=2018-03-28: 400: DELETE ERROR -400 The requested URI does not represent any resource on the server.. X-Ms-Request-Id:5bf92407-b01e-008d-24a8-2b3816000000

2020/05/16 17:39:28 JobID=d617de09-03f7-8545-7474-9c893c6afe04, Part#=0, TransfersDone=1 of 1
2020/05/16 17:39:28 all parts of entire Job d617de09-03f7-8545-7474-9c893c6afe04 successfully completed, cancelled or paused
2020/05/16 17:39:30 PERF: primary performance constraint is Unknown. States: T:  0, GRs: 128
```

If i try to delete both folders simultaneously, the log doesn't mention this failure, it says succeeded but doesn't change the contents of the blob container (just give the 'undefined' error)

**Comment by JasonYeMSFT** [comment]
@untilted-document This is a duplicate issue of #1512.

We currently don't support viewing or managing blobs whose name contains consecutive / characters or ends with / character. These two kinds of blob names lead to "" folder or "" blob at the leaf, which will result in undefined behavior if you try to navigate through such blobs folders or perform operations on them. Please try to avoid creating such blobs.

**Comment by JasonYeMSFT** [comment]
@untilted-document Some additional information since your issue is a little different from the others. Even though we working on a work around for this type of issue in 1.14.0, by 1.14.0, it would be impossible to make AzCopy and Storage Explorer work on blobs whose names end with "/" character. The work around would be mainly focusing on unblocking scenarios where you have consecutive "/" characters in the middle of the blob name. Again, please try your best to avoid making blob names that end with "/" character. If such blobs are already created, the only way to get rid of them is to write scripts utilizing low level apis (e.g. raw shell script with rest api) since AzCopy doesn't support it or delete the whole container and start over.
