### ISSUE TITLE
Add 'Microsoft Azure Storage Explorer' label in 'Create Directory' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#299]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: All
**Architecture**: ia32/x64
**Build Number**: 20180611.3
**Commit**: e00d7640
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Launch Storage Explorer and expand Storage Accounts.
2. Open one file share and click 'New Folder' button.
3. Check the label of the 'Create New Directory' dialog.

#### Expected Experience: ####
'Microsoft Azure Storage Explorer' label displays in the dialog.

#### Actual Experience: ####
No 'Microsoft Azure Storage Explorer' label displays in the dialog.
![actual](https://user-images.githubusercontent.com/34729022/41343296-b57f929c-6eed-11e8-9fe2-b9d0f1508efe.png)

#### More info: ####
The title label should be consistent in 'Create Virtual Directory' dialog
![consistent](https://user-images.githubusercontent.com/34729022/41343177-6e47504a-6eed-11e8-9266-22b75fe378ed.png)

**Comment by JasonYeMSFT** [comment]
Fixed. It has been merged into master.
