### ISSUE TITLE
The icon and the description in Queue detach dialog are not correct

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2992]
**Storage Explorer Version:** 1.14.0-dev
**Build:** [20200518.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3736141&view=artifacts&type=publishedArtifacts)
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS Mojave
**Architecture:** ia32/x64
**Regression From:** Previous release (1.13.0)

**Steps to reproduce:**
1. Expand one storage account -> Queues.
2. Create a queue -> Attach the queue via SAS.
3. Try to detach the attached queue -> Check the prompt dialog.

**Expect Experience:**
The prompt dialog shows as below.
![image](https://user-images.githubusercontent.com/41351993/82193542-1c413b00-9928-11ea-839d-8ceb831296f2.png)

**Actual Experience:**
The prompt dialog shows as below.
![image](https://user-images.githubusercontent.com/41351993/82193589-29f6c080-9928-11ea-8ee8-e162a5694717.png)

**Comment by craxal** [comment]
By design. Icon and message were changed deliberately.

**Comment by craxal** [comment]
For consistency, we will revert this change.

**Comment by v-xianya** [comment]
This issue still reproduces on build master/[20200520.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3742543&view=results). So we re-open it.
