### ISSUE TITLE
The opened tab doesn’t close after deleting the queue

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2994]
**Storage Explorer Version:** 1.14.0-dev
**Build:** [20200518.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3736141&view=artifacts&type=publishedArtifacts)
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS Mojave
**Architecture:** ia32/x64
**Regression From:** Previous release (1.13.0)

**Steps to reproduce:**
1. Expand one storage account -> Queues.
2. Select one queue and open it.
3. Delete the queue -> Check whether the opened tab is closed or not.

**Expect Experience:**
The opened tab is closed.

**Actual Experience:**
The opened tab doesn’t close.

**Comment by craxal** [comment]
Duplicate of #2946.
