### ISSUE TITLE
An error occurs when clicking 'Manage Stored Access Policies...' for one queue

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2995]
**Storage Explorer Version:** 1.14.0-dev
**Build:** [20200518.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3736141&view=artifacts&type=publishedArtifacts)
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS Mojave
**Architecture:** ia32/x64
**Regression From:** Previous release (1.13.0)

**Steps to reproduce:**
1. Expand one storage account -> Queues.
2. Select one queue and right click it -> Select 'Manage Stored Access Policies...'.
3. Check the result.

**Expect Experience:**
No error occurs.

**Actual Experience:**
The below error occurs.
![image](https://user-images.githubusercontent.com/41351993/82196026-c078b100-992b-11ea-856e-78ecb632a291.png)

**Comment by v-xianya** [comment]
Hi @craxal 
We verified this issue on build master/[20200520.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3742543&view=results). 
The error changes. As below:
![image](https://user-images.githubusercontent.com/41351993/82400553-2aa76800-9a8a-11ea-9a2e-b5c7e598694c.png)

**Comment by craxal** [comment]
@v-xianya The code here is split between the dialog and the queue extension. Changes to the dialog in master will be picked up right away, but changes to the extension require a separate package update. Package updates are built separately. That's why you're noticing the change.

**Comment by v-xianya** [comment]
@craxal  got it. Thank you for the sharing.
