### ISSUE TITLE
Keep a consistent properties format for SAS attached services 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2997]
**Storage Explorer Version:** 1.14.0-dev
**Build:** [20200518.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3736141&view=artifacts&type=publishedArtifacts)
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS Mojave
**Architecture:** ia32/x64
**Regression From:** Previous release (1.13.0)

**Steps to reproduce:**
1. Expand one storage account.
2. Attach one queue via SAS -> Check the Properties of the attached queue.

**Expect Experience:**
Keep a consistent properties format for one sas attached file share/ table/ blob container.

**Actual Experience:**
Display an inconsistent properties format for one sas attached file share/ table/ blob container.
![image](https://user-images.githubusercontent.com/41351993/82197056-1568f700-992d-11ea-901d-bdffe77988d9.png)

**Comment by v-xianya** [comment]
@craxal 
This issue still reproduces on build master/[20200522.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3750769&view=results). Thus we reopen it.

**Comment by craxal** [comment]
It should be SAS Token. That is the string I have in the source code, so we just need to update the package version.

**Comment by v-xianya** [comment]
@craxal Got it. Thank you for the updates😊.

**Comment by v-xianya** [comment]
This issue reproduces on build master/20200609.1. We will keep an eye on this issue and verify it on the later build.

**Comment by v-xianya** [comment]
Verified this issue on build 20200611.9. Fixed.
