### ISSUE TITLE
Option to hide diagnostics tables ($Logs, $Metrics, Etc ...)

### ISSUE THREAD

**Issue by JakeRadMSFT** [microsoft/AzureStorageExplorer#3]
Storage Explorer Version: 0.9.6

OS Version: Windows 10

Steps to Reproduce:

1. Open Tables for a Storage Account
2. Observe several $ prefixed tables.

Expected Experience:
Being able to hide them if I don't use them.

Actual Experience:
Always there clogging up the TreeView UI.

**Comment by josheinstein** [comment]
Please, for the love of God, can we get this feature?

**Comment by LaughingJohn** [comment]
Please leave feedback so we can ignore it?

**Comment by gfkeogh** [comment]
Since we're up to version 1.8.1 now and this seemingly convenient and simple request has been ignored for 14 months, then either no human life is monitoring this thread or for some secret reason it's been skipped or blacklisted. Is there some other forum?

**Comment by jinglouMSFT** [comment]
We are working on building up the back-end infrastructure to support configurable settings. Once that's done, this will become one of the configurable settings.
