### ISSUE TITLE
Mounting of invalid Storage Accounts via account name and key

### ISSUE THREAD

**Issue by xyh1** [Microsoft/AzureStorageExplorer#30]
**Storage Explorer Version:** 0.9.6

**OS Version:** Windows 10

**Steps to Reproduce:**

1. Right Click "Storage Accounts"
2. Select "Connect to Azure Storage"
3. Select "Use a storage account name and key"
4. Enter Account Key
5. Enter Account Name with uppercase letter or invalid special characters or invalid account name length

**Expected Experience:**
Catch the account name with uppercase letters or special characters and throw a highlighted red error message

Also Catch the account name if less than 3 characters or more than 24 characters

**Actual Experience:**
Able to mount storage account and when clicking on containers, it throws an unhelpful message not indicating issues with Storage account name

![image](https://user-images.githubusercontent.com/2829937/38157476-1aa03d1c-343c-11e8-9a16-b07f890c1e15.png)
![image](https://user-images.githubusercontent.com/2829937/38157485-1ff64ffe-343c-11e8-8e99-739967f6f09d.png)

**Comment by MRayermannMSFT** [comment]
Same general issue as #129. Closing as duplicate.
