### ISSUE TITLE
 A confused error message for the second added property with an empty name for a table

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#300]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: All
**Architecture**: ia32/x64
**Build Number**: 20180611.3
**Commit**: e00d7640
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Launch Storage Explorer and expand Storage Accounts.
2. Open one table and click 'Add' button on the toolbar.
3. Add one property with an empty name and check the displayed error message.
4. Add the second property with the same empty name then check the error message.

#### Expected Experience: ####
The second error message is consistent with the first error.

#### Actual Experience: ####
The second error message is confused.(The empty property name is forbidden)
![error](https://user-images.githubusercontent.com/34729022/41342602-2e377440-6eec-11e8-8730-278ef80bd51a.png)

**Comment by JasonYeMSFT** [comment]
Won't fix because it is not a common scenario because it doesn't actually affect user experience.
