### ISSUE TITLE
Pop up an error dialog when closing tabs that contains a temporary opened queue tab by clicking 'Close All'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3000]
**Storage Explorer Version:** 1.14.0-dev
**Build:** [20200518.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3736141&view=artifacts&type=publishedArtifacts)
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS Mojave
**Architecture:** ia32/x64
**Regression From:** Previous release (1.13.0)

**Steps to reproduce:**
1. Expand one storage account -> Queues.
2. Select one queue and click it to open a temporary tab.
3. Select one item to open a permanent tab  -> Right-click the permanent tab -> Click 'Close All'.
4. Check the result.

**Expect Experience:**
No error dialog pops up.
 
**Actual Experience:**
Pop up an error dialog.
![image](https://user-images.githubusercontent.com/41351993/82202376-64fef100-9934-11ea-82aa-a4912147f2fa.png)

**More Info:**
Record: https://web.microsoftstream.com/video/fa09a4ff-0400-96d0-4e8e-f1ea999e8874

**Comment by MRayermannMSFT** [comment]
@v-xianya can you give me some more specifics? What actions were you doing? What tabs did you open? How long did you wait?

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT 
We have updated the steps and attached a record.🙃

**Comment by MRayermannMSFT** [comment]
@v-xianya  perfect! This bug is now very easy to fix.

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
