### ISSUE TITLE
The tab auto open temporarily after attaching one queue via SAS

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3004]
**Storage Explorer Version:** 1.14.0-dev
**Build**:[ 20200519.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3738672)
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS Mojave
**Architecture:** ia32/x64
**Regression From:** Previous release (1.13.0)

**Steps to reproduce:**

1. Expand one storage account -> Queues.
2. Select one queue -> Attach it via SAS.
3. Check the tab status.

**Expect Experience:**
The tab status is permanent.
![image](https://user-images.githubusercontent.com/54055206/82310010-67c21a80-99f6-11ea-9c4d-6af583719656.png)

**Actual Experience:**
The tab status is temporary.
![image](https://user-images.githubusercontent.com/54055206/82310114-8fb17e00-99f6-11ea-9065-0e18a8e30a5d.png)

**More Info:**
This issue doesn't reproduce for one file share / table / blob container.

**Comment by v-xianya** [comment]
This issue is fixed on build master/20200522.4. So we close it.
