### ISSUE TITLE
Mac_StorageExplorer.zip release v1.13.1 download corrupt

### ISSUE THREAD

**Issue by r-moore** [microsoft/AzureStorageExplorer#3005]
**Storage Explorer Version**: v1.13.1
**Build Number**: 
**Platform/OS**: macOS
**Architecture**: x64
**Regression From**:  yes, v1.13.0 still works

## Bug Description ##
The ZIP file will not extract.

I have tried the download multiple times from different browsers to ensure that it was not a transmission error.

If I download the previous version (v1.13.0) it extracts fine.

## Steps to Reproduce ##
Download the file from either GitHub (https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.13.1) or microsoft.com (https://azure.microsoft.com/en-us/features/storage-explorer/)

Unzip using macOS built in archive utility, ditto, or 7zip.

## Expected Experience ##
The zip file should extract, `Microsoft Azure Storage Explorer.app`.

## Actual Experience ##

The 
<img width="388" alt="image" src="https://user-images.githubusercontent.com/366280/82323560-26b70f80-99d0-11ea-985e-03f3cedaedb1.png">

Log from command line extraction:

```
ditto: Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/CloudHub/lib/jQuery-contextMenu/documentation/website/fonts/2D5240_1_0.ttf: No such file or directory
ditto: Couldn't read pkzip signature.
ditto: Couldn't read pkzip signature.
ditto: Couldn't read pkzip signature.
ditto: Couldn't read pkzip signature.
ditto: Couldn't read pkzip signature.
ditto: Couldn't read pkzip signature.
ditto: Couldn't read pkzip signature.
ditto: Couldn't read pkzip signature.
ditto: Couldn't read pkzip signature.
ditto: Couldn't read pkzip signature.
ditto: Couldn't read pkzip signature.
ditto: Couldn't read pkzip signature.
```

**Comment by r-moore** [comment]
This version appears to be corrupt too: 
<img width="552" alt="image" src="https://user-images.githubusercontent.com/366280/82323780-739ae600-99d0-11ea-8963-a1766fc1c6de.png">

**Comment by jonathan-vouch** [comment]
Also experienced this :( Breaks the auto-update feature too :(

**Comment by jsalch** [comment]
Same here.  Lots of time wasted on this issue.

**Comment by craxal** [comment]
Hey everyone. Thanks for reporting this issue. We're working on getting new packages uploaded right now. Thanks for your patience.

**Comment by jinglouMSFT** [comment]
There were some network instability issues when the bits were uploaded yesterday.  We just reuploaded the Mac file.  It will take few hours to be propagated to all data centers.  At the meantime, please feel free to download 1.13.1 from this github repo: https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.13.1.  Sorry for the inconvenience.

**Comment by guisantos** [comment]
I've just updated my azure storage explorer and is working well on macOS Catalina

**Comment by craxal** [comment]
Since this issue appears to have been resolved, I'm going to close it. If anyone is still experiencing problems, please open a new bug. Thanks!
