### ISSUE TITLE
error while opening the application

### ISSUE THREAD

**Issue by Ashribad** [microsoft/AzureStorageExplorer#3006]
**Storage Explorer Version**: 1.13.1
**Build Number**: 
**Platform/OS**: Windows 10
**Architecture**: 64
**Regression From**:  first time user of 1.13.1

## Bug Description ##
To run Microsoft Azure Storage Explorer on Windows, you must have .NET Framework 4.7.2 or greater installed. Please make sure .NET Framework 4.7.2 or greater is properly installed before launching the application again.

## Actual Experience ##
![image](https://user-images.githubusercontent.com/33851860/82341407-04dc7d80-9a0e-11ea-9bee-24e9aaad6c25.png)

**Comment by MRayermannMSFT** [comment]
@ashribad can you please do the following

# Clean the ServiceHub logs
1. Open File Explorer and go to `C:\Users\your username\AppData\Local\Temp\servicehub` and delete the logs folder 

# Set Trace Level
1. Open a terminal
2. Run `setx SERVICEHUBTRACELEVEL ALL`
3. Close Storage Explorer

# Repro and get us logs
1. Repro the issue
2. Go back to `C:\Users\your username\AppData\Local\Temp\servicehub`, zip up the logs folder, and attach it here

**Comment by Ashribad** [comment]
@MRayermannMSFT, Above steps followed ,and the issue is reproduced , here is the attached log file.
[logs.zip](https://github.com/microsoft/AzureStorageExplorer/files/4654652/logs.zip)

**Comment by MRayermannMSFT** [comment]
@Ashribad two things.

1. Our best guess is that some antivirus program is flagging one of our exe's as a virus: `C:\Users\<UserName>\AppData\Local\Programs\Microsoft Azure Storage Explorer\resources\app\ServiceHub\Controllers\microsoft-servicehub-controller\Microsoft.ServiceHub.Controller.exe`. Can you look into if this is going on?
2. Can you open up event viewer, and see if there are any failed events related to that path? You might need to try opening Storage Explorer to get a recent event to appear.

**Comment by Ashribad** [comment]
Thank you so much @MRayermannMSFT, Its worked, I struggled to fix it for last 2 days :)

**Comment by MRayermannMSFT** [comment]
@Ashribad mind sharing with me what the fix was?

**Comment by Ashribad** [comment]
@MRayermannMSFT this was due to some antivirus program..
