### ISSUE TITLE
Support to copy items in About page for Windows

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#301]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Windows
**Architecture**: ia32
**Build Number**: 20180611.3
**Commit**: e00d7640
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Launch Storage Explorer.
2. Navigate to 'Help' -> 'About'.
3. Check whether these items can be copied or not.

#### Expected Experience: ####
These items support to copy.

#### Actual Experience: ####
These items don't support to copy.
![copy](https://user-images.githubusercontent.com/34729022/41342313-720a2c86-6eeb-11e8-8aff-d2188482bdef.png)

#### More info: ####
This issue doesn't reproduce on Mac/Linux.

**Comment by MRayermannMSFT** [comment]
Hey @v-xuanzh , you can actually hit Ctrl+C in windows when the about dialog is open, and it will copy the contents to your clipboard. That being said, it isn't very discoverable, so we are looking to eventually move to a different dialog that makes it more clear on how to copy/paste the data. We already have a bug for this (#152 ), so I'm going to close this as a duplicate.
