### ISSUE TITLE
Miss 'Set Public Access Level..' action for one blob container after manually refresh

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3010]
**Storage Explorer Version:** 1.14.0-dev
**Build**: [20200520.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3742543&view=results)
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS Mojave
**Architecture:** ia32/x64
**Regression From:** Previous release (1.13.0)

**Steps to reproduce:**

1. Expand one storage account -> Blob Containers.
2. Create a new blob container -> **Refresh Blob Containers.**
3. Check actions and Properties panel for the blob container.

**Expect Experience:**

1. All actions show well.
2. All properties show well in Properties panel.
![image](https://user-images.githubusercontent.com/54055206/82430592-1d0cd500-9ac0-11ea-8c53-d91a189ae0a4.png)

**Actual Experience:**
1. Miss 'Public Read Access Level...' and 'Copy Direct Link to Blob Container' actions.
2. Miss 'Public Read Access' in Properties panel.
![image](https://user-images.githubusercontent.com/54055206/82430570-11b9a980-9ac0-11ea-92ee-df4448058323.png)

**Comment by v-limu** [comment]
**More Info:**


1. The blob container's delete icon is incorrect after manually refresh Blob Containers on build [20200521.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3746638&view=results).
![image](https://user-images.githubusercontent.com/54055206/82539719-7b998800-9b80-11ea-8420-85e39b2d90a8.png)
 Expect:
![image](https://user-images.githubusercontent.com/54055206/82540106-21e58d80-9b81-11ea-8ad5-f3bf64aba106.png)

**Comment by JasonYeMSFT** [comment]
@v-limu we have recently updated several icons in the Actions panel. We did it for blobs and queues.

**Comment by MRayermannMSFT** [comment]
Fix merged to master.

**Comment by v-xianya** [comment]
Verified this issue on build master/20200602.3. 
The action 'Copy Direct Link to Blob Container' is still missed. So we re-open it.
![image](https://user-images.githubusercontent.com/41351993/83472850-c38ea800-a4ba-11ea-81e3-845fea68c145.png)

**Comment by v-xianya** [comment]
This issue is fixed on build master/20200604.2. So close it.
