### ISSUE TITLE
Support hot keys

### ISSUE THREAD

**Issue by svetikshark** [microsoft/AzureStorageExplorer#3011]
Currently to save/discard/open filter in data tab it is needed to click on button - while it would be more convenient to use standard ctrl+s and so on

**Comment by jinglouMSFT** [comment]
I assume your suggestion is for CosmosDB?

**Comment by svetikshark** [comment]
yes sorry

ср, 20 трав. 2020, 20:55 користувач jinglouMSFT <notifications@github.com>
пише:

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
