### ISSUE TITLE
An extra folder displays after selecting 'Enabled overwrite' to retry one conflict blob

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3012]
**Storage Explorer Version:** 1.14.0-dev
**Build**: [20200520.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3742543&view=results)
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS Mojave
**Architecture:** ia32/x64
**Regression From:** Previous release (1.13.0)

**Steps to reproduce:**

1. Expand one Non-ADLS Gen2 storage account -> Blob Containers.
2. Copy one blob to another blob container -> Copy the blob to same destination again.
3. Select 'Do not paste' in the Conflict dialog -> Apply.
4. Click 'Retry...' in activity log -> Select 'Enable overwrite' in Retry AzCopy dialog -> Click 'Retry Selected'.
5. Check the result.

**Expect Experience:**

1. Succeed overwrite the blob.
2. No folder displays.

**Actual Experience:**
An extra folder displays.
![image](https://user-images.githubusercontent.com/54055206/82429579-bc30cd00-9abe-11ea-901f-733e5ea82bb6.png)

**More Info:**
This issue doesn't reproduce for one ADLS Gen2 blob container.

**Comment by v-xianya** [comment]
This issue is fixed on build master/[20200522.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3750769&view=results). So we close it.
