### ISSUE TITLE
Add the sign 'Azure AD - Azure Account' for an Azure AD attached queue

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3013]
**Storage Explorer Version:** 1.14.0-dev
**Build:** [20200520.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3742543&view=results)
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS Mojave
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Attach one queue via Azure AD.
2. Check the attached queue.

**Expect Experience:**
Display 'Azure AD - Azure Account' for the attached queue.
![image](https://user-images.githubusercontent.com/41351993/82433790-868ee280-9ac4-11ea-998f-aa44ea2c170e.png)

**Actual Experience:**
No 'Azure AD - Azure Account' displays for the attached queue.

**Comment by craxal** [comment]
Part of the work tracked by #975.

**Comment by v-xianya** [comment]
This issue is fixed on build master/[20200522.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3750769&view=results). So we close it.
![image](https://user-images.githubusercontent.com/41351993/82627728-9c63eb00-9c1d-11ea-9ec2-56a8f3c24734.png)
