### ISSUE TITLE
The string 'Create Queue' is not localized on Queues node context menu

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3015]
**Storage Explorer Version:** 1.14.0-dev
**Build:** [20200521.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3746638&view=results)
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS Mojave
**Language:** All
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文(简体)' -> Restart Storage Explorer.
3. Expand one storage account.
4. Right click Queues node -> Check the strings on the context menu.

**Expect Experience:**
All strings are localized.

**Actual Experience:**
The string 'Create Queue' is not localized.
![image](https://user-images.githubusercontent.com/41351993/82540189-3b86d500-9b81-11ea-99b9-116787b1180f.png)

**Comment by lukaschal** [comment]
Commited at 5/13/2020.

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer/commit/500f769dc998f4b1fd3dfb7b2c6332c958648e09?refName=refs%2Fheads%2Fmaster&path=%2Floc%2Floc%2Fzh-Hans%2Fsrc%2Fcomponents%2Fse-queue-extension%2Fresources%2FQueues.json.lcl&_a=contents

File: loc\en\src\components\se-queue-extension\resources\Queues.json
ID: 0; "LabelActionCreate"
SRC: Create Queue
TGT: 创建队列

**Comment by craxal** [comment]
@v-xianya Unable to repro. The build used for testing was a little behind. This should already be fixed in [20200521.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3746767&view=results).
