### ISSUE TITLE
Status strings for a non-empty queue are not localized

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3016]
**Storage Explorer Version:** 1.14.0-dev
**Build:** [20200521.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3746638&view=results)
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS Mojave
**Language:** All
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文(简体)' -> Restart Storage Explorer.
3. Expand one storage account -> Queues.
4. Create a queue -> Add messages.
5. Check the status strings.

**Expect Experience:**
The strings are localized.

**Actual Experience:**
The strings are not localized.
![image](https://user-images.githubusercontent.com/41351993/82541607-51959500-9b83-11ea-83de-c3ef99b58247.png)

**Comment by lukaschal** [comment]
Translations commited at 5/13/2020.

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer/commit/500f769dc998f4b1fd3dfb7b2c6332c958648e09?refName=refs%2Fheads%2Fmaster&path=%2Floc%2Floc%2Fzh-Hans%2Fsrc%2Fcomponents%2Fse-queue-extension%2Fresources%2FQueueEditor.json.lcl&_a=contents

**Comment by craxal** [comment]
@v-xianya Unable to repro. The build used for testing was a little behind. This should already be fixed in [20200521.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3746767&view=results).
