### ISSUE TITLE
Most of the strings in View Message dialog are not localized

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3017]
**Storage Explorer Version:** 1.14.0-dev
**Build:** [20200521.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3746638&view=results)
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS Mojave
**Language:** All
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文(简体)' -> Restart Storage Explorer.
3. Expand one storage account -> Queues.
4. Create a queue -> Add one message -> View the message.
5. Check the View Message dialog.

**Expect Experience:**
All of the strings in 'View Message' dialog are localized.

**Actual Experience:**
Most of the strings in 'View Message' dialog are not localized.
![image](https://user-images.githubusercontent.com/41351993/82542825-31ff6c00-9b85-11ea-83bc-d0d2fb4244a4.png)

**Comment by lukaschal** [comment]
Localized 2 months ago or earlier.

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer?path=%2Floc%2Floc%2Fzh-Hans%2Fsrc%2FStandalone%2Fresources%2FViewMessageDialog.json.lcl&version=GBmaster&_a=blame

**Comment by craxal** [comment]
@lukaschal The original string resource file has moved locations, so those language files are no longer valid. They need to be moved as well.

**Comment by v-limu** [comment]
Verified on build 20200924.2. This issue has been fixed in all languages. So close it.
