### ISSUE TITLE
The created new folder doesn't auto display for one file share

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3018]
**Storage Explorer Version:** 1.14.0-dev
**Build**: [20200521.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3746638&view=results)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS Mojave
**Architecture**: ia32/x64
**Regression From:** Previous release (1.13.0)

**Steps to reproduce:**

1. Expand one storage account -> File Shares.
2. Create a new file share -> Upload files to it.
3. Create a new folder -> Check whether the folder auto displays or not.

**Expect Experience:**
The folder auto displays.

**Actual Experience:**
The folder doesn't auto display.

**More Info:**
1. The folder displays when manually refresh.
2. This issue doesn't reproduce when creating one new folder under **one empty file share.**

**Comment by v-xianya** [comment]
This issue is fixed on build master/[20200522.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3750769&view=results). So we close it.
