### ISSUE TITLE
The lock icon doesn't auto display after acquiring lease for one ADLS Gen2 blob

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3019]
**Storage Explorer Version:** 1.14.0-dev
**Build**: [20200521.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3746638&view=results)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS Mojave
**Architecture**: ia32/x64
**Regression From:** Previous release (1.13.0)

**Steps to reproduce:**

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a new blob container -> Upload one blob to it.
3. Acquire lease for this blob -> Check whether the lock icon auto displays or not.

**Expect Experience:**
The lock icon auto displays.

**Actual Experience:**
The lock icon doesn't auto display.

**More Info:**
1. The lock icon displays after manually refresh.
2. This issue also reproduces when breaking lease for one ADLS Gen2 blob.
3. This issue doesn't reproduce for one regular blob.

**Comment by v-xianya** [comment]
This issue is fixed on build master/[20200522.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3750769). So we close it.
