### ISSUE TITLE
Cannot explore table storage accounts in 1.2.0

### ISSUE THREAD

**Issue by denious** [Microsoft/AzureStorageExplorer#302]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Windows
**Architecture**: ia32
**Regression From**: Was working in 1.1.0

#### Steps to Reproduce: ####
Find some old and very large table storage account and expand it

#### Expected Experience: ####
Expecting to see the usual list consisting of blob containers, file shares, queues, and tables, allowing to dig deeper

#### Actual Experience: ####
After about two minutes of loading animation, the arrow to expand/collapse the account disappears, nothing else shows up

![2018-06-13 13_33_54-microsoft azure storage explorer](https://user-images.githubusercontent.com/7120854/41368015-a86e87b8-6f0e-11e8-8311-c5c78e07e5eb.png)

**Comment by denious** [comment]
![2018-06-13 13_33_54-microsoft azure storage explorer](https://user-images.githubusercontent.com/7120854/41367987-97166eb8-6f0e-11e8-8a51-e53912a1cdb9.png)

**Comment by craxal** [comment]
You're getting gateway timeout errors. Azure Storage was down briefly yesterday (14 Jun). Have you tried again since then?

**Comment by denious** [comment]
Just tried and all good, must've been the downtime. I was confused because it only affected my classic accounts. Thanks for the update!
