### ISSUE TITLE
Cannot Paste into same directory?

### ISSUE THREAD

**Issue by LukeMcCarthy-Versor** [microsoft/AzureStorageExplorer#3022]
As a Data Platform developer I use Azure Storage Explorer to trigger new blob events which in turn execute event triggers in ADF.
Recently you took away the ability to copy and paste into the same directory.
Why?
Now I have to copy and paste into a completely different directory, then copy and paste back.
This is sometimes for 000s of files and is a very time intensive exercise.
Not to mention that in the process, the ACLs settings on the copied files often become corrupted in the process.
Can you please remove this restriction as I can see no purpose for this

**Comment by JasonYeMSFT** [comment]
I assume you mean copying blobs and pasting them into the directory they are in, right? The reason we removed it is because this will lead to data corruption on append or page blobs. If you attempt to overwrite an append/page blob by itself, it will accidentally erase the data of the blob.

**Comment by MRayermannMSFT** [comment]
@LukeMcCarthy-Versor this is by design. As @JasonYeMSFT explains, there were issues with allowing this behavior.
