### ISSUE TITLE
There is translation error in Custom Timestamp Query dialog

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3027]
**Storage Explorer Version:** 1.14.0-dev
**Build**: 20200522.4
**Branch**: master
**Language**: Chinese(zh-CN)
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS Mojave
**Architecture:** ia32/x64
**Regression From:** Previous build

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文(简体)' -> Restart Storage Explorer.
3. Expand one storage account -> Tables.
4. Create a new table -> Add an entity -> Open Query builder -> Select 'Timestamp' Field -> Select 'Custom...' in 'Value' drop down list.
5. Check the localized strings in Custom Timestamp Query dialog.

**Expect Experience:**
There is no translation error.

**Actual Experience:**
There is translation error.
![image](https://user-images.githubusercontent.com/54055206/82648017-a6034800-9c49-11ea-9893-fea5dc016777.png)
ENU Screenshot:
![image](https://user-images.githubusercontent.com/54055206/82648343-1e6a0900-9c4a-11ea-9b19-c9d80bbd52c0.png)

**More Info:**
Related bug: #[2520](https://github.com/microsoft/AzureStorageExplorer/issues/2520)

**Comment by lukaschal** [comment]
On review.

File: loc\en\src\Standalone\resources\CustomizeTimestampDialog.json
ID: 0; "LabelFrom"
SRC: From:
TGT: 发件人:

File: loc\en\src\Standalone\resources\CustomizeTimestampDialog.json
ID: 0; "LabelTo"
SRC: To:
TGT: 到:

**Comment by lukaschal** [comment]
Fixed.

src: To:
new tgt: 收件人:

**Comment by v-limu** [comment]
Hi @lukaschal The correct translation should be as below 😃:
![image](https://user-images.githubusercontent.com/54055206/82970936-191f0c80-a004-11ea-998b-2c066c9700de.png)

**Comment by lukaschal** [comment]
Fixed.

SRC: From:
TGT: 从:

SRC: To:
TGT: 到:

**Comment by v-limu** [comment]
Verified on build 2020062702. This issue has been fixed. So close it.
![image](https://user-images.githubusercontent.com/54055206/85939444-3e2ad600-b948-11ea-9a63-7f5373f53822.png)
