### ISSUE TITLE
Keep a consistent translation for the string 'Lease State'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3028]
**Storage Explorer Version:** 1.14.0-dev
**Build:** 20200522.4
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS Mojave
**Language:** Chinese(zh-CN)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文(简体)' -> Restart Storage Explorer.
3. Expand one storage account -> Blob Containers.
4. Create a blob container.
5. Check the translation for the string 'Lease State' in Properties panel and Editor.

**Expect Experience:**
Keep a consistent translation.

**Actual Experience:**
Display an inconsistent translation.
In properties panel. Translate as '租用状态'
![image](https://user-images.githubusercontent.com/41351993/82650840-dc42c680-9c4d-11ea-845f-04178ea5ad2f.png)
In Editor. Translate as '租约状态'
![image](https://user-images.githubusercontent.com/41351993/82650811-d0570480-9c4d-11ea-9f87-f9a40551ba00.png)

**More Info:**
ENU Screenshot:
![image](https://user-images.githubusercontent.com/41351993/82651474-c97cc180-9c4e-11ea-9bf0-395e6c45f1fd.png)

![image](https://user-images.githubusercontent.com/41351993/82651380-ab16c600-9c4e-11ea-8e77-d66f87eac464.png)

**Comment by lukaschal** [comment]
On review.

0; "TableView.LeaseStateHeader"
0; "Properties.BlobContainers.LeaseState"

**Comment by lukaschal** [comment]
Fixed.

new tgt: 租用状态

**Comment by v-xianya** [comment]
This issue also reproduces for '**Acquire Lease & Break Lease**'
![image](https://user-images.githubusercontent.com/41351993/83114133-2965e300-a0fb-11ea-8fc7-4b6d1b0441f9.png)
ENU Screenshot:
![image](https://user-images.githubusercontent.com/41351993/83114203-45698480-a0fb-11ea-8ac6-2adb40786e9e.png)

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/18324331/83741162-25384900-a658-11ea-8270-e67246f3cf79.png)

**Comment by v-xianya** [comment]
Verified on build master 20200611.9. Fixed.
