### ISSUE TITLE
Error uploading vhd image size in bytes 44716382720

### ISSUE THREAD

**Issue by jroales** [microsoft/AzureStorageExplorer#3029]
*El Explorador de Storage no pudo crear el disco.

Respuesta del servicio: {
  "name": "Error",
  "message": "The upload size in bytes 44716382720 - 512 bytes for the VHD footer (44716382208 in this case) must be a multiple of MiB.",
  "stack": "Error: The upload size in bytes 44716382720 - 512 bytes for the VHD footer (44716382208 in this case) must be a multiple of MiB.\n    at new RestError (C:\\Users\\jroales\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\ms-rest-js\\dist\\msRest.node.js:2400:28)\n    at C:\\Users\\jroales\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\ms-rest-js\\dist\\msRest.node.js:3544:37\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
  "code": "BadRequest",
  "statusCode": 400,
  "request": {
    "streamResponseBody": false,
  
    "message": "The upload size in bytes 44716382720 - 512 bytes for the VHD footer (44716382208 in this case) must be a multiple of MiB."
  }
}

**Comment by MRayermannMSFT** [comment]
Hey @jroales.

When uploading a disk, it's size must be between 20972032 bytes (20 MiB + 512 bytes for the VHD footer) and 35183298347520 bytes (32 TiB + 512 bytes for the VHD footer). Additionally, the size minus 512 bytes must be a multiple of MiB. You'll need to resize your VHD before uploading. I think probably this article would be of help to you: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/prepare-for-upload-vhd-image

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having issues, please open up a new issue, thanks.

**Comment by cquresphere** [comment]
As I can see after 2 years still does not work. Even if you correct file length with adding 512 for footer error still appears. 
It looks like mechanims for validation bigger vhd files is corrupted. 
It is more disturbing because GCP does not have such problems with migration to cloud.

**Comment by MaupieGit** [comment]
it does work, he needs to add 512 bytes to the total size in bytes for the VHD footer.
So 44716382720 + 512 = 44716383232. If he does that then Azure will accept the command and create the disk in Azure.
