### ISSUE TITLE
Issue with logging into Azure Storage Explorer 1.2.0

### ISSUE THREAD

**Issue by vivekappala** [microsoft/AzureStorageExplorer#303]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Windows 7 Professional

#### Steps to Reproduce: ####
1. Open Azure Storage Explorer and hit Add an Account
2. Enter your credentials

#### Expected Experience: ####
All the Subscriptions should be loaded.

#### Actual Experience: ####
Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: f8cdef31-a31e-4b4a-93e4-5f571e91255a, Error: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"13.91.242.34","port":443}
Tenant Id: ef36efe5-89a5-4781-b96a-d57e6cf7f662, Error: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"13.91.242.34","port":443}

**Comment by craxal** [comment]
Azure Storage was down briefly yesterday (14 Jun). Have you tried again since then?

**Comment by vivekappala** [comment]
Thanks for your reply! 
I did try now, no luck.

**Comment by JasonYeMSFT** [comment]
Do you still have any problem with 1.12.0?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
