### ISSUE TITLE
{   "message": "\"Failed to acquire token silently as no token was found in the cache. Call method AcquireToken\"" }

### ISSUE THREAD

**Issue by 310kdf** [microsoft/AzureStorageExplorer#3031]
**Storage Explorer Version**: 1.13.0
**Build Number**: 20200430.5
**Platform/OS**: Server 2012 R2
**Architecture**: x64

## Bug Description ##
I changed my password to my AD account and am trying to resign in, and it fails with the error.

## Steps to Reproduce ##
Try to reenter credentials, fails with this error.

## Expected Experience ##
Should log me in?

## Actual Experience ##
Failed log in.

**Comment by jinglouMSFT** [comment]
Can you try to delete the following folder after closing Storage Explorer, then start it and try to sign in?

Windows: %AppData%/StorageExplorer
macOS: /Users/<your_name>/Library/Application Support/StorageExplorer
Linux: ~/.config/StorageExplorer

**Comment by 310kdf** [comment]
I actually updated to the latest version and it fixed the problem.
