### ISSUE TITLE
"Unable to retrieve child resources - Details [{}]" when expanding a subscription which needs re-authentication

### ISSUE THREAD

**Issue by GillesZunino** [microsoft/AzureStorageExplorer#3032]
**Storage Explorer Version**: 1.13.1
**Build Number**: 202005.15.1
**Platform/OS**: Windows 10 2004
**Architecture**: x64
**Regression From**:  1.13.0

"Microsoft Authentication Library (Preview)" checkbox is NOT checked in settings.

## Bug Description ##
Storage Explorer show an error dialog box with "Unable to retrieve child resources - Details [{}]" when I try to expand a subscription which needs the user to re-authenticate.

## Steps to Reproduce ##
1 - Install storage explorer 1.13.1
2 - Launch it
3 - Choose a subscription which needs re-authentication
4 - Expand it in the subscription tree view

## Expected Experience ##
* - Error message with text similar in spirit to "this subscription need re-authentication"
* - Error message contains a link or similar affordance to take users to the place where they can re-authenticate

## Actual Experience ##
* - Dialog box with "Unable to retrieve child resources - Details [{}]"
* - There is no mention that this is in fact an authentication problem

Logs attached
[1590181967253.log](https://github.com/microsoft/AzureStorageExplorer/files/4670401/1590181967253.log)

﻿

​

**Comment by JonathanMaccollum** [comment]
Experiencing the same issue here... after dismissing and starting the procedure to re-enter credentials, I just gets stuck in an authentication loop where it continually asks for credentials and MFA code over and over again.

**Comment by MRayermannMSFT** [comment]
@JonathanMaccollum and @GillesZunino can you try enabling MSAL in the settings? Settings -> Authentication -> Microsoft Authentication Library (Preview)?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems. Thanks.
