### ISSUE TITLE
The action 'Set Public Access Level...' shows for one Azure AD attached blob container

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3036]
**Storage Explorer Version:** 1.14.0-dev
**Build**: 20200523.2
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS Mojave
**Architecture**: ia32/x64
**Regression From:** Previous release(1.13.1)

**Steps to reproduce:**
1. Select one regular blob container.
2. Give RBAC access to the blob container 'Blob Data Owner Role'.
3. Attach this blob container via Azure Active Directory (Azure AD).
4. Check the context menu of the attached Azure AD blob container.

**Expect Experience:**
No 'Set Public Access Level...' action shows.

**Actual Experience:**
The action 'Set Public Access Level...' shows.
![image](https://user-images.githubusercontent.com/54055206/82882994-71a6c900-9f74-11ea-9327-c6cb3e323cbf.png)

**More Info:**
Show a failed activity log after executing the 'Set Public Access Level...' action.
![image](https://user-images.githubusercontent.com/54055206/82883061-86835c80-9f74-11ea-9e59-338d7a756968.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
