### ISSUE TITLE
There are strings not localized in 'Delete' and 'Detach' dialog for one queue

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3037]
**Storage Explorer Version:** 1.14.0-dev
**Build**: 20200523.2
**Branch**: master
**Language**: All
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS Mojave
**Architecture**: ia32/x64
**Regression From:** Previous Release(1.13.1)

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文(简体)' -> Restart Storage Explorer.
3. Expand one storage account -> Queues.
4. Create a new queue -> Click 'Delete'.
5. Check the strings in the dialog.

**Expect Experience:**
All strings are localized in 'Delete' dialog.
![image](https://user-images.githubusercontent.com/54055206/82886091-9d2bb280-9f78-11ea-9579-08081f84db37.png)

**Actual Experience:**
There are strings not localized in 'Delete' dialog.
![image](https://user-images.githubusercontent.com/54055206/82886119-a6b51a80-9f78-11ea-9354-eecc50a86163.png)

**More Info:**
This issue also reproduces in 'Detach' dialog.
![image](https://user-images.githubusercontent.com/54055206/82886147-b16faf80-9f78-11ea-8583-e2b3d336890d.png)

**Comment by lukaschal** [comment]
Localized on all locales.

File: loc\en\src\Standalone\resources\ConnectDialog.json
ID: 0; "LabelArmEndpoint"
SRC: ARM endpoint:

**Comment by lukaschal** [comment]
Localized at 5/21/2020.

File: loc\en\src\components\se-queue-extension\resources\Queues.json
ID: 0; "MessageConfirmDetach"
SRC: Are you sure you want to detach the resource '%1$s'?
TGT: 確定要中斷資源 '%1$s' 的連結嗎?

**Comment by v-limu** [comment]
Verified on build 2020062702. This issue has been fixed. So close it.
