### ISSUE TITLE
Fail to expand the local Queues node that contains Azure AD attached queues with associated account removed

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3038]
**Storage Explorer Version:** 1.14.0-dev
**Build**: 20200523.2
**Branch**: master
Platform/OS: Windows 10/ Linux Ubuntu 16.04/ macOS Mojave
Architecture: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Queues.
2. Create one queue -> Attach this queue via Azure Active Directory (Azure AD).
3. Remove the account associated with the Azure AD attached queue.
4. Expand Local & Attached -> Storage Accounts -> Attached Containers -> Queues.
5. Check the result.

**Expect Experience:**
Succeed to expand the Queues node.

**Actual Experience:**
Fail to expand the Queues node and pop up the below error dialog.
![image](https://user-images.githubusercontent.com/41351993/82885649-02cb6f00-9f78-11ea-9deb-6e4d0ce23681.png)

**Comment by craxal** [comment]
@v-xianya This sounds like expected behavior, although the message isn't helpful. Two things:
- Can you be more specific about "remove the account"? Do you mean that you signed out of the _Azure_ account associated with the attached queue?
- Does this repro for blob containers as well?

**Comment by v-xianya** [comment]
@craxal
1. Yes, 'Remove the account' means to sign out the Azure account associated with the attached queue. (Go to ACCOUNT MANAGEMENT Page -> Remove the associated account)
2. This issue doesn't reproduce for blob containers. 
3. Screentshot:
![image](https://user-images.githubusercontent.com/41351993/82965897-0b658900-9ffc-11ea-96cd-1b66f31e7f16.png)
