### ISSUE TITLE
The translation for the notification 'There is no update available' is incorrect

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3039]
**Storage Explorer Version:** 1.14.0-dev
**Build**: 20200523.2
**Branch**: master
**Language**: Chinese(zh-TW)
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS Mojave
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '繁體中文' -> Restart Storage Explorer.
3. Go to 'Help' -> Click localized 'Check for Updates'.
4. Check the notification.

**Expect Experience:**
The translation for notification is correct.

**Actual Experience:**
The translation for the notification is incorrect.
![image](https://user-images.githubusercontent.com/41351993/82886736-846fcc80-9f79-11ea-8e0e-e24758b5e729.png)

**More Info:**
ENU screenshot:
![image](https://user-images.githubusercontent.com/41351993/82886719-80dc4580-9f79-11ea-97ee-67afd12fe85e.png)

**Comment by lukaschal** [comment]
On review.

Rid: MessageNoUpdate
Src: There is no update available.
Tgt: 已有可用的更新。

**Comment by lukaschal** [comment]
Fixed week ago.

NEW TGT: 沒有可用的更新。

**Comment by v-xianya** [comment]
Verify this issue on build 20200611.9. Fixed. 
![image](https://user-images.githubusercontent.com/41351993/84473556-dcb60680-acbb-11ea-8e6a-f26f62080bd2.png)
