### ISSUE TITLE
The string 'endpoint' is not localized in 'Custom Environments' dialog

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3040]
**Storage Explorer Version:** 1.14.0-dev
**Build**: 20200523.2
**Branch**: master
**Language**: All
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS Mojave
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文(简体)' -> Restart Storage Explorer.
3. Open connect dialog -> Select 'Add New Environment' -> Click 'Next'.
4. Type the environment name and ARM endpoint -> Click 'Next'.
5. Enter the credentials for an azure account.
6. Reopen connect dialog -> Select 'Use Custom Environment' option -> Click 'Next'.
7. Check the string 'endpoint' in the dialog.

**Expect Experience:**
The string 'endpoint' is localized.

**Actual Experience:**
The string 'endpoint' is not localized.
![image](https://user-images.githubusercontent.com/54055206/82882406-99496180-9f73-11ea-9d30-9b0a1a6e2a08.png)

**Comment by lukaschal** [comment]
Localized on all locales.

File: loc\en\src\Standalone\resources\ConnectDialog.json
ID: 0; "LabelArmEndpoint"
SRC: ARM endpoint:

**Comment by v-xianya** [comment]
Verified this issue on build 20200924.2. Reproduce.

**Comment by MRayermannMSFT** [comment]
This resource no longer exists.
