### ISSUE TITLE
Cosmos documents cause "render process crash"

### ISSUE THREAD

**Issue by BrianVallelunga** [microsoft/AzureStorageExplorer#3041]
**Storage Explorer Version**: 1.13.1
**Build Number**: 20200515.1
**Platform/OS**: Windows 10 2004
**Architecture**: x64
**Regression From**:  None

## Bug Description ##
When viewing a Cosmos document or trying to create a new cosmos document, the program crashes with the error "

## Steps to Reproduce ##
Click a document in Cosmos to view

## Expected Experience ##
Document is shwon

## Actual Experience ##
Storage Explorer crashes

## Additional Context ##
This is happening on a clean install of Windows. I did not have this issue a few days ago on my old install.

**Comment by BrianVallelunga** [comment]
Let me know if you need me to do anything else to help out. I tried again today after some restarts and had the same issue.

**Comment by southpolesteve** [comment]
@BrianVallelunga Can you email me your account name and subscription id? stfaul@microsoft.com. I can look into this further

**Comment by BrianVallelunga** [comment]
I never heard back from anyone on this, but I am happy to say that the new 1.14 build has resolved the issue. Perhaps it was the update to Electron that did it.

**Comment by southpolesteve** [comment]
@BrianVallelunga Very sorry I never got back to you. I am seeing just now your email got filtered into spam. Glad the latest version resolves it.
