### ISSUE TITLE
Support "Open" file command for ADLS Gen2 - full loop including file watch/save for changes

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#3044]
Requested by Miguel Lasuncion -

We are using Microsoft Azure Storage Explorer 1.12 application to manage Azure Data Lake files, 
I cannot directly Open the files on the Azure Data Lake Gen2 , If I want to visualize the content of a file I have to Download them (Image 1). 
I would expect to be able to Open a file like in a regular Blob Container (not in a Data Lake)  (Image 2).
Is there any reason for this? Will be able to Open a file using Azure Storage Explorer?

Image 1
![image](https://user-images.githubusercontent.com/10081483/82966204-2a720580-9f7f-11ea-8719-8db43806f983.png)

 

Image 2 
![image](https://user-images.githubusercontent.com/10081483/82966215-31007d00-9f7f-11ea-858f-5ef8da6cbd04.png)

**Comment by MRayermannMSFT** [comment]
Good news, this is actually done for 1.14 already!

**Comment by miguellasuncion** [comment]
Thank you!
