### ISSUE TITLE
No refresh notification prompts when creating a new folder under a file share without checking 'Auto-refresh on change'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3045]
**Storage Explorer Version:** 1.14.0-dev
**Build**: 20200526.3
**Branch**: master
**Platform/OS:** Windows 10/ macOS Mojave
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Open 'Settings' -> Data Explorers -> Disable the option 'Auto-refresh on change'.  
2. Expand one storage account -> File Shares.
3. Create a file share -> Create a new folder.
4. Check whether there prompts a refresh notification or not.

**Expect Experience:**
A refresh notification prompts.
![image](https://user-images.githubusercontent.com/41351993/82999655-eb55ba00-a03b-11ea-84d1-2e375302f964.png)

**Actual Experience:**
No refresh notification prompts.

**More Info:**
The refresh notification prompts when creating a new folder under ADLS Gen2 blob containers.

**Comment by JasonYeMSFT** [comment]
Matthew has checked in the work to make file share follow the refresh behavior when creating directories.
