### ISSUE TITLE
The refresh notification is not localized for ADLS Gen2 blob containers

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3046]
**Storage Explorer Version:** 1.14.0-dev
**Build**: 20200526.3
**Branch**: master
**Platform/OS:** Windows 10/ macOS Mojave
**Language**: All
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '繁體中文' -> Restart Storage Explorer.
3. Go to 'Settings' -> 'Data Explorers' -> Make sure the option 'Auto-refresh on change' is disabled.
4. Expand one ADLS Gen2 storage account -> Create a blob container.
5. Upload one file -> Check the prompt refresh notification.

**Expect Experience:**
The refresh notification is localized.
![image](https://user-images.githubusercontent.com/41351993/83000968-aaf73b80-a03d-11ea-81de-7521d862bb9c.png)

**Actual Experience:**
The refresh notification is not localized.
![image](https://user-images.githubusercontent.com/41351993/83000962-a92d7800-a03d-11ea-9d17-83ae79697e9a.png)

**More Info:**
This issue doesn't reproduce for **file shares & regular blob containers & disks.**

**Comment by lukaschal** [comment]
All localizable instances translated in loc repository.

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer?path=%2Floc%2Floc%2Fzh-Hans%2Fsrc%2Fcomponents%2Fse-file-extension%2Fresources%2FFileEditor.json.lcl&version=GBmaster&_a=blame

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer?path=%2Floc%2Floc%2Fzh-Hans%2Fsrc%2Fcomponents%2Fse-managed-disks-extension%2Fresources%2FManagedDisksExplorer.json.lcl&_a=blame&version=GBmaster

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer?path=%2Floc%2Floc%2Fzh-Hans%2Fsrc%2Fcomponents%2Fse-blob-extension%2Fresources%2FBlobEditor.json.lcl&version=GBmaster&_a=blame

**Comment by v-xianya** [comment]
Verified this issue on build 20200924.2. Fixed.
