### ISSUE TITLE
There are strings not localized in Settings 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3047]
**Storage Explorer Version:** 1.14.0-dev
**Build**: 20200526.3
**Branch**: master
**Platform/OS:** Windows 10/ macOS Mojave
**Language**: All
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '繁體中文' -> Restart Storage Explorer.
3. Go to 'Settings' -> 'Transfers' -> Check the AzCopy part.

**Expect Experience:**
All the strings are localized.

**Actual Experience:**
There are strings not localized.
![image](https://user-images.githubusercontent.com/41351993/83002164-4dfc8500-a03f-11ea-98cc-24c87d87f6ae.png)

**Comment by MRayermannMSFT** [comment]
These have not been localized yet.

**Comment by lukaschal** [comment]
Commited at 5/20/2020.

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer/commit/5fe9ed02045d6294d9012946cba508d91abb9080?refName=refs%2Fheads%2Fmaster&path=%2Floc%2Floc%2Fzh-Hans%2Fsrc%2Fcomponents%2Fse-az-copy-extension%2Fresources%2FAzCopySettings.json.lcl&_a=contents

**Comment by v-limu** [comment]
Verified on build 2020062702. This issue has been fixed. So close it.
