### ISSUE TITLE
A notification pops up after canceling the certificate import

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3049]
**Storage Explorer Version:** 1.14.0-dev
**Build**: 20200526.3
**Branch**: master
**Platform/OS:** Windows 10/ macOS Mojave
**Architecture**: ia32/x64
**Regression From:** Previous release(1.13.1)

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Click 'Edit' -> 'SSL Certificates' -> Click 'Import Certificates'.
3. Click 'Cancel' button in the popped file explorer dialog.
4. Check the result.

**Expect Experience:**
No notification pops up.

**Actual Experience:**
Pop up a notification.
![image](https://user-images.githubusercontent.com/54055206/83002357-8d2ad600-a03f-11ea-808e-81f9a72c70db.png)

**Comment by MRayermannMSFT** [comment]
Fix checked into master
