### ISSUE TITLE
No file explorer dialog pops up after clicking 'View Imported Certificates'

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3050]
**Storage Explorer Version:** 1.14.0-dev
**Build**: 20200526.3
**Branch**: master
**Platform/OS:** Windows 10
**Architecture**: ia32/x64
**Regression From:** Previous release(1.13.1)

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Click 'Edit' -> 'SSL Certificates' -> Click 'View Imported Certificates'.
3. Check whether the file explorer dialog pops up or not.

**Expect Experience:**
The file explorer dialog pops up.
![image](https://user-images.githubusercontent.com/54055206/83002879-26f28300-a040-11ea-9a3b-46500ace4ce3.png)

**Actual Experience:**
No file explorer dialog pops up.

**More Info:**
This issue doesn't reproduce on Mac.

**Comment by MRayermannMSFT** [comment]
Fix checked into master
