### ISSUE TITLE
Extra 'File Shares/Queues' nodes display for one 'Name & Key' attached blob storage account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3054]
**Storage Explorer Version:** 1.14.0-dev
**Build**: 20200527.5
**Branch**: master
**Platform/OS:** Windows 10/ macOS Mojave
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Select one Blob storage account -> Attach it via name & key.
2. Expand the attached storage account -> View the result.

**Expect Experience:**
Only display 'Blob Containers & Tables' nodes.

**Actual Experience:**
'File Shares & Queues' nodes also display.
![image](https://user-images.githubusercontent.com/41351993/83123335-5a4c1500-a107-11ea-952b-9ee2bdfa8505.png)

**More Info:**
This issue also reproduces for one premium account.

**Comment by MRayermannMSFT** [comment]
Won't fix. We cannot call ARM if all we have is a key, therefor we don't know the attached account is a blob account.
