### ISSUE TITLE
New versions missing "Genrate containier-level shared access signature URI" in get SAS token dialog

### ISSUE THREAD

**Issue by jparvu** [microsoft/AzureStorageExplorer#3055]
**Storage Explorer Version**: 1.13.1
**Build Number**: 20200515.1
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  1.11.2

## Bug Description ##
New versions missing "Genrate containier-level shared access signature URI" in get SAS token dialog

## Steps to Reproduce ##
1. Right click on a file in storage explorer select "generate shared access signature".
2. Notice "Generate containier-level shared access signature URI" it not shown on the dialog .
## Expected Experience ##
Should show "Generate containier-level shared access signature URI" as in previous versions.

## Actual Experience ##
"Generate containier-level shared access signature URI" has been removed

## Additional Context ##
Not sure why it was removed. There are things such as the "Microsoft Partner Center" that need this item checked when generating a SAS URI.

**Comment by jinglouMSFT** [comment]
This was removed by design from the "generate shared access signature" dialog on a file/blob.  You can generate container level SAS by right clicking on the container node in the tree view on the left side. This was redesigned based on user feedback.
