### ISSUE TITLE
Please add ability to copy ABFSS path for ADLS Gen2 account

### ISSUE THREAD

**Issue by ghost** [microsoft/AzureStorageExplorer#3056]
**Is your feature request related to a problem? Please describe.**
When working with synapse workspace, there is an often need to use "abfss" / "dfs" path for files.It would be good if "azure storage explorer" allows us to easily copy the abfss/dfs
![storage explorer](https://user-images.githubusercontent.com/15574543/83179799-1f86b480-a0e8-11ea-82f6-43a60693d4a3.jpg)
 path for files

**Describe the solution you'd like**
Right click on file in ADLS, click properties, it currently shows URL that is based on blob endpoint, please add additional options to copy the abfss url and dfs url.

Example
abfss : abfss://cont1@synapseadlsgen2.dfs.core.windows.net/json1/file.txt
dfs:     https://synapseadlsgen2.dfs.core.windows.net/cont1/json1/file1.txt

**Comment by MRayermannMSFT** [comment]
Let's treat this like we did custom domains, and for gen2 containers, have copy url be a pop out menu which contains options for copying the various URLs.

**Comment by craxal** [comment]
We can provide a command for copying the DFS endpoint, but any ABFSS endpoints is beyond the normal Azure Storage scope that Storage Explorer provides.
