### ISSUE TITLE
An extra action 'Set Public Access Level…' displays for blob containers under SAS attached storage accounts

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3058]
**Storage Explorer Version:** 1.14.0-dev
**Build**: 20200529.3
**Branch**: master
**Platform/OS:** Windows 10/ macOS Mojave
**Architecture:** ia32/x64
**Regression From:** Previous release(1.13.1)

**Steps to reproduce:**
1. Select one non-ADLS Gen2 storage account -> Attach the storage account via SAS.
2. Expand the attached storage account -> Blob Containers.
3. Create a blob container -> Check its context menu.
4. Refresh Blob Containers node -> Re-check the blob container's context menu.

**Expect Experience:**
No extra action displays.

**Actual Experience:**
An extra action 'Set Public Access Level...' displays.
![image](https://user-images.githubusercontent.com/41351993/83236661-72cf3480-a1c6-11ea-8baf-fa99bda7532c.png)

**More Info:**
1. Display the below activity log when executing 'Set Public Access Level...'.
![image](https://user-images.githubusercontent.com/41351993/83236755-9abe9800-a1c6-11ea-908d-d54bbb2e52cc.png)

**Comment by JasonYeMSFT** [comment]
The issue shares the cause with #3036.

**Comment by v-xianya** [comment]
This issue is fixed on build master/20200602.3. Close it.
