### ISSUE TITLE
Pop up an error dialog when saving one access policy for one emulator queue

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3059]
**Storage Explorer Version:** 1.14.0-dev
**Build**: 20200529.3
**Branch**: master
**Platform/OS:** Windows 10
**Architecture**: ia32
**Azurite Version:** 3.7.0
**Regression From:** Previous release (1.13.1)

**Steps to reproduce:**
1. Install and run Azurite -> Launch Storage Explorer.
2. Expand Local & Attached -> Storage Accounts-> (Emulator - Default Ports) (Key) -> Queues.
3. Create a queue -> Right click it -> Click 'Manage Stored Access Policies...'.
4. Add one access policy -> Click 'Save'.
5. Check the result.

**Expect Experience:**
No error occurs.

**Actual Experience:**
Pop up an error dialog.
![image](https://user-images.githubusercontent.com/41351993/83247876-c8abd880-a1d6-11ea-9def-769e3138d1dc.png)

**More Info:**
This issue doesn't reproduce when using Emulator version 5.10.

**Comment by jinglouMSFT** [comment]
@craxal can you please investigate for 1.14? Thanks.

**Comment by craxal** [comment]
@v-xianya What version of Azurite did you install? It's possible the version you have doesn't support access policies.

**Comment by v-xianya** [comment]
@craxal 
1. Azurite Version：3.7.0.
2. Using the same version of Azurite in 1.13.1. This issue doesn't reproduce.

**Comment by craxal** [comment]
@v-xianya Unable to repro using code from current master. This may have been fixed along with #2995. An updated package is still in the works, so please wait until a new package is created before verifying.
