### ISSUE TITLE
Connections in the explorer should be removable

### ISSUE THREAD

**Issue by Petapacket** [microsoft/AzureStorageExplorer#3060]
**Is your feature request related to a problem? Please describe.**
I have deleted Azure subscriptions which still have references in Azure Storage client.

**Describe the solution you'd like**
Button to remove connections, on right click, from the explorer pane.

**Describe alternatives you've considered**
Not using the application.

**Additional context**

**Comment by MRayermannMSFT** [comment]
@Petapacket could you elaborate some more on what you mean by "connections"? Maybe share some screenshots about the things you want to remove?

Also, when you say "deleted Azure subscriptions", do you mean you signed out from Storage Explorer or do you mean that those subscriptions were literally deleted.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.

**Comment by Smille02a** [comment]
How many Goddam posts do you have make to convey this?


Thank you.
--
Regards,
Stephen W.  Miller
smille02@msn.com<mailto:smille02@msn.com>  @Smille02  Skype:live:smille02
Cell: +1 917.704.5934<tel:+1%20917.704.5934> Fax:  +1 212.225.8247<tel:+1%20212.225.8247>
www.linkedin.com/in/swmps<http://www.linkedin.com/in/swmps>

On Jun 29, 2020, at 1:54 PM, Matthew Rayermann <notifications@github.com> wrote:

﻿

Closed #3060<https://eur06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FAzureStorageExplorer%2Fissues%2F3060&data=02%7C01%7C%7C5f1bb8676cbc4babda7808d81c557693%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637290500664861338&sdata=p0vgKpulTUzTXv6A0tRNKZZuWeHuJDCUcQFtlmWSeoM%3D&reserved=0>.

**Comment by MRayermannMSFT** [comment]
@Smille02a , are you receiving lots of notification emails about our repo? If so, you can edit your GitHub notification settings here: https://github.com/settings/notifications

If at some point you "starred" or "watched" this repo, that might be contributing to the emails you received.
