### ISSUE TITLE
Remove 'Detach' action for attached storage accounts under Quick Access node

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3063]
**Storage Explorer Version:** 1.14.0-dev
**Build**: 20200602.3
**Branch**: master
**Platform/OS:** Windows 10/ macOS Mojave
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Attach one storage account via 'SAS' or 'Name and Key'.
2. Add the attached storage account to Quick Access.
3. Check the context menu of the attached storage account under Quick Access node.

**Expect Experience:**
No 'Detach' action displays.

**Actual Experience:**
The action 'Detach' displays well.

**Comment by MRayermannMSFT** [comment]
Fix merged to main
