### ISSUE TITLE
The blobs doesn't auto display after pasting one blob container to one name & key attached account

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3067]
**Storage Explorer Version:** 1.14.0-dev
**Build**: 20200602.3
**Branch**: master
**Platform/OS:** Windows 10/ macOS Mojave
**Architecture**: ia32/x64
**Regression From:** Previous release(1.13.1)

**Steps to reproduce:**

1. Attach one Non-ADLS Gen2 storage account via name & key.
2. Expand the attached storage account -> Blob Containers.
3. Paste one blob container which contains the blobs to it.
4. Check whether the blobs auto display or not.

**Expect Experience:**
The blobs auto display.

**Actual Experience:**
The blobs doesn't auto display.
![image](https://user-images.githubusercontent.com/54055206/83506326-9dd4c380-a4f9-11ea-8498-888a012a9021.png)

**More Info:**
The blobs display after manually refreshing.

**Comment by v-xianya** [comment]
Verified this issue on build 20200609.1. Reproduce. So we re-open it.

**Comment by JasonYeMSFT** [comment]
The corresponding CloudExplorer has been updated. This issue should have been fixed.

**Comment by v-xianya** [comment]
Verified this issue on build 20200610.2. Fixed.
