### ISSUE TITLE
The QA queues with a same name share one tab when using 'Open' to open them

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3068]
**Storage Explorer Version:** 1.14.0-dev
**Build**: 20200602.3
**Branch**: master
**Platform/OS:** Windows 10/ macOS Mojave
**Architecture**: ia32/x64
**Regression From:** Previous release(1.13.1)

**Steps to reproduce:**

1. Add the several queues with a same name from different storage accounts to Quick Access.
2. Click 'Open' on the context menu of the several queues under Quick Access.
3. Check the result. 

**Expect Experience:**
Display the respective tabs.

**Actual Experience:**
Display one tab.

**Comment by craxal** [comment]
Related to #3002. This bug has already been addressed and a fix merged.

**Comment by v-xianya** [comment]
Verified this issue on build master/20200609.1. Fixed.
