### ISSUE TITLE
Make sure service endpoints in connection objects contains the trailing slash

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#3070]
Azure service returns service endpoints with the trailing slash. We should privilege this behavior.

**Comment by MRayermannMSFT** [comment]
Jason will spend time in 1.15 breaking down what places we are modifying the URL the server returns for no reason.

**Comment by JasonYeMSFT** [comment]
We are currently not modifying the urls except when comparing against the known azure domain endpoint strings, which don't have the trailing slash character.
