### ISSUE TITLE
Archive status and last activate time missing in storage explorer but its available in portal

### ISSUE THREAD

**Issue by nilabjaball** [microsoft/AzureStorageExplorer#3071]
**Is your feature request related to a problem? Please describe.**
When you change tier, portal provides tier status and last tier change time. Can we add this capability in Azure storage explorer. User has know idea that the request has been accepted when they click on storage account

**Describe the solution you'd like**
add extra two columns in the blob section 

**Describe alternatives you've considered**
use azure portal

**Additional context**
![arc](https://user-images.githubusercontent.com/15369895/83571607-bbc81580-a545-11ea-805e-5bb295083355.png)

**Comment by MRayermannMSFT** [comment]
Related to https://github.com/microsoft/AzureStorageExplorer/issues/176

**Comment by MRayermannMSFT** [comment]
@nilabjaball as of 1.15.0, the tier last modified time and rehydration status are available in a variety of places:

- tier last modified time: blob explorer data table, properties dialog for blob
- rehydrration status: properties dialog for the blob

**Comment by MRayermannMSFT** [comment]
<img width="313" alt="image" src="https://user-images.githubusercontent.com/21112697/94622628-638cf000-0267-11eb-9b7e-484aca1f848f.png">
<img width="166" alt="image" src="https://user-images.githubusercontent.com/21112697/94622649-6c7dc180-0267-11eb-93ac-02c3f9d842ef.png">
