### ISSUE TITLE
The dragged column shows strangely for one queue

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3074]
**Storage Explorer Version:** 1.14.0-dev
**Build**: 20200603.4
**Branch**: master
**Platform/OS:** Windows 10/ macOS Mojave / Linux Ubuntu 16.04
**Architecture:** ia32/x64
**Regression From:** Previous release(1.13.1)

**Steps to reproduce:**

1. Expand one storage account -> Queues.
2. Open one queue -> Try to drag one column in Editor.
3. Check the result.

**Expect Experience:**
The dragged column shows well.
![image](https://user-images.githubusercontent.com/54055206/83611318-662a5200-a5b3-11ea-9ded-cac50d5ea0c1.png)

**Actual Experience:**
The dragged column shows strangely.
![image](https://user-images.githubusercontent.com/54055206/83611325-688cac00-a5b3-11ea-8aef-eaf6790e9a2f.png)

**Comment by craxal** [comment]
This is a known issue in webview-based editors, such as for managed disks. This is not a regression.

See https://devdiv.visualstudio.com/DevDiv/_git/3501f1c0-e3a3-4daa-8e89-af3efe91dd48/pullrequest/201300 for the original change introduced for managed disks.

**Comment by MRayermannMSFT** [comment]
Make sure drag and drop works, minus the column being a giant rectangle. If so, put in 15, otherwise fix the drag and drop ASAP.

**Comment by craxal** [comment]
Drag and drop still works as expected, so moving to 1.15.0.

**Comment by v-xianya** [comment]
This issue has been fixed on build 20200922.5. So close it.
