### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by sylvain-fr** [microsoft/AzureStorageExplorer#3075]
Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: 584a26e0-32d6-489f-bf0f-409ce22e277f, Error: {
  "name": "Error",
  "message": "self signed certificate in certificate chain",
  "stack": "Error: self signed certificate in certificate chain\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at TLSSocket.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at TLSSocket.emit (events.js:182:13)\n    at TLSSocket._finishInit (_tls_wrap.js:631:8)",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}
Tenant Id: f8cdef31-a31e-4b4a-93e4-5f571e91255a, Error: {
  "name": "Error",
  "message": "self signed certificate in certificate chain",
  "stack": "Error: self signed certificate in certificate chain\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at TLSSocket.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at TLSSocket.emit (events.js:182:13)\n    at TLSSocket._finishInit (_tls_wrap.js:631:8)",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}

**Comment by JasonYeMSFT** [comment]
Could you please try the steps in our [trouble shooting guide](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C1904#error-self-signed-certificate-in-certificate-chain-and-similar-errors) to see if it can resolve the problem?

**Comment by sylvain-fr** [comment]
yes, it solved it. I've impored self signed certificate and now it's
working fine.
Thanks for support !

**Comment by sylvain-fr** [comment]
import self signed certificate like described in trouble shooting guide solves the issue
