### ISSUE TITLE
The deleted emulator blobs do not show under 'Active and delete blobs' view with Soft Delete enabled

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3076]
**Storage Explorer Version:** 1.14.0-dev
**Build**: 20200604.2
**Branch**: master
**Platform/OS:** Windows 10
**Architecture**: ia32
**Azurite Version:** 3.7.0
**Regression From:** Not a regression

**Steps to reproduce:**
1. Install and run Azurite -> Launch Storage Explorer.
2. Expand Local & Attached -> Storage Accounts-> (Emulator - Default Ports) (Key). 
3. Right click the Blob Containers node -> Select 'Configure Soft Delete Policy...' -> Check the option 'Enable Soft Delete' -> Click 'Save'.
4. Create a new blob container -> Upload one file.
5. Delete the uploaded file -> Switch to 'Active and deleted blobs' view.
6. Check whether there shows the deleted blob or not.
 
**Expect Experience:**
Show the deleted blob.

**Actual Experience:**
No deleted blob shows.

**Comment by JasonYeMSFT** [comment]
I have confirmed with Azurite team that soft delete isn't supported even though it is responding to soft delete policy related requests.

**Comment by v-xianya** [comment]
Hi @JasonYeMSFT Got it. Thanks for your sharing.
