### ISSUE TITLE
Miss the queue name in one attached queue's URL

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3077]
**Storage Explorer Version:** 1.14.0-dev
**Build**: 20200604.2
**Branch**: master
**Platform/OS:** Windows 10/ macOS Mojave / Linux Ubuntu 16.04
**Architecture:** ia32/x64
**Regression From:** Previous release(1.13.1)

**Steps to reproduce:**
1. Expand one storage account -> Queues.
2. Create a new queue -> Attach it via SAS.
3. Check the attached queue's URL on Properties panel.

**Expect Experience:**
Show a complete URL.

**Actual Experience:**
The queue name is missed in the URL.

**More Info:**
This issue also reproduces for Azure AD attached queues.

**Comment by craxal** [comment]
@v-xianya Unable to repro based on current master. Queue extension package still needs an update, so please wait to verify until then.

**Comment by v-xianya** [comment]
Hi @craxal Got it. Thanks for you update.
