### ISSUE TITLE
An error pops up when using blobs direct link to open Storage Explorer

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3078]
**Storage Explorer Version:** 1.14.0-dev
**Build**: 20200604.2
**Branch**: master
**Platform/OS:** Windows 10 / MacOS Mojave
**Architecture:** ia32/x64
**Regression From:** Previous release(1.13.1)

**Steps to reproduce:**

1. Expand one storage account -> Blob Containers.
2. Select one blob container -> Right click it.
3. Click 'Copy Direct Link to Blob Container' -> Paste the copied direct link to browser -> Open Storage Explorer.
4. Check the result.

**Expect Experience:**

1. The linked blob container is selected and auto opens.
2. No error pops up.

**Actual Experience:**
An error pops up.
![image](https://user-images.githubusercontent.com/54055206/83739855-b4f5eb80-a688-11ea-8d3e-7e94ce64241a.png)

**Comment by JasonYeMSFT** [comment]
I have verified that this has been fixed on latest master.
