### ISSUE TITLE
Unable to re-size columns in Table output

### ISSUE THREAD

**Issue by mandrie** [microsoft/AzureStorageExplorer#3079]
**Storage Explorer Version**: 1.12
**Build Number**:  20200114.3
**Platform/OS**: Windows 10?
**Architecture**: ia32  (should be x64 but this is what I see in your help --> about
**Regression From**:  N/A

## Bug Description ##
In the output of a Table query I am unable to make one of the columns wider by dragging to the right. Even if I limit the number of columns shown in the output to just 2, and the one column is very narrow each columns takes up half the space.

## Steps to Reproduce ##
1. Issue a Table query and get at least one very long column and one short column. In my example I have a timestamp and an error message
2. try to expand the size of the column or re-order to allow for the larger column to have more screen realestate

## Expected Experience ##
that you can make a column bigger to see more of its data

## Actual Experience ##
Each column takes up the same amount of space

**Comment by mandrie** [comment]
![image](https://user-images.githubusercontent.com/11774594/83758641-3c127780-a627-11ea-85ba-f8e9aaf8b654.png)

**Comment by JasonYeMSFT** [comment]
@mandrie, just to confirm, are you hiding any column from the "Column Options" button? I can only reproduce the issue when some column is hidden from there.

**Comment by mandrie** [comment]
Yes I am hiding some columns. Also I played around with it some more after making sure I was on the latest version and I think it seems to only repro with the `TimeStamp` column. If I switch to using `PreciseTimeStamp` and `Message` columns then I can resize columns just fine. But if I refresh and try again sometimes it works and sometimes it doesn't. I haven't figured out precise repro steps that repo everytime :(

**Comment by craxal** [comment]
We switched some time ago to a new DataGrid component that handles column sizing much better. Each column's size is preserved across sessions and can be auto sized by content with a double-click. If your issues persist, you may open a new issue.
