### ISSUE TITLE
The value of the property AccessTierInferred is null after changing one blob's access tier

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3082]
**Storage Explorer Version:** 1.14.0-dev
**Build**: 20200604.10
**Branch**: master
**Platform/OS:** Windows 10/ macOS Mojave / Linux Ubuntu 16.04
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one GPV2 storage account -> Blob Containers.
2. Create a blob container -> Upload one **block** blob.
3. Open its properties dialog and check the value of property AccessTierInferred.
4. Right click the blob then select 'Change Access Tier...' -> Click 'Apply' on the Update Access Tier dialog.
5. Open the blobs properties dialog and check the value of property AccessTierInferred.

**Expect Experience:**
It would be better to set the value to false.

**Actual Experience:**
The value is null.
![image](https://user-images.githubusercontent.com/41351993/83847938-b0d8d500-a73f-11ea-8b11-5e97a07dfe97.png)

**More Info:**
The default AccessTierInferred value for new uploaded blobs.
![image](https://user-images.githubusercontent.com/41351993/83847954-b59d8900-a73f-11ea-8098-dbffbc605ed2.png)

**Comment by MRayermannMSFT** [comment]
Let's ask the platform team to make false be returned.

**Comment by v-xianya** [comment]
@JasonYeMSFT This issue reproduces on build master/20200715.1.
