### ISSUE TITLE
I could not add my account

### ISSUE THREAD

**Issue by mgvaldmx** [microsoft/AzureStorageExplorer#3084]
Hello,

I just downloaded the Azure Storage Explorer, but I couldn't add my account, I get the error message shown on the following screenshot:

![image](https://user-images.githubusercontent.com/66494904/83921418-eaabda80-a743-11ea-934b-acdff530bf26.png)

![image](https://user-images.githubusercontent.com/66494904/83921454-fdbeaa80-a743-11ea-89dc-519cfcdc2919.png)

Please let me know if I should provide further details.

Thank you!
Martin.

**Comment by MRayermannMSFT** [comment]
Are you behind a proxy? If so, have you configured the proxy settings in Storage Explorer? See our trouble shooting guide (Help -> Troubleshooting Guide) for more information.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having issues, please open up a new issue, thanks.
