### ISSUE TITLE
Shared throughput option during collection creation

### ISSUE THREAD

**Issue by arupnayak** [microsoft/AzureStorageExplorer#3085]
**Is your feature request related to a problem? Please describe.**
There should be an option to select shared throughput option during creation of collection like in portal. We created few collections without this option and it spike up our bill as the collections got created with dedicated thoughput.

**Describe the solution you'd like**
Shared thoughput checkbox should be available when creating collection.

**Describe alternatives you've considered**
The alternative to this creating collection through portal or CLI. But both these options are not user friendly.

**Comment by jinglouMSFT** [comment]
CosmosDB support in Storage Explorer has been retired. Closing this feature request.
