### ISSUE TITLE
Storage Explorer window is not visible on macOS and fails to start with --disable-gpu flag

### ISSUE THREAD

**Issue by SamVanhoutte** [microsoft/AzureStorageExplorer#3086]
**Storage Explorer Version**: 1.13.1
**Build Number**: cannot start up, so don't know how to find it
**Platform/OS**: macOS Catalina 10.15.4
**Architecture**: x64
**Regression From**:  It worked before indeed

## Bug Description ##
- Since a while, I cannot manage to start Azure Storage Explorer anymore on my mac.
- The app opens, but the window is hidden/invisible to be used
- I have been using the Storage Explorer in the browser since then, but that got disabled, so I really need this to be fixed now
- I have an eGPU (for data science purposes), so I guess this is related to #2277 
- However, when I start up I get a message indicating there is a problem with the GPU and I should restart, passing the --disable-gpu flag: 
> A problem caused Storage Explorer to restart with GPU acceleration disabled.  If this problem persists, launch Storage Explorer from the command line with the '--disable-gpu' switch.

## Steps to Reproduce ##
- Connect eGPU with macbook

### First attempt (default behavior)
- Try to start Azure Storage Epxlorer
- __Result__: empty screen

### Second attempt (--disable-gpu switch)
- Create Apple Script
- `do shell script "open -a '/Applications/AzureStorageExplorer.app/Contents/MacOS/Microsoft Azure Storage Explorer' --args --disable-gpu"``
- Run script
- __Result__: error as mentioned above

### Third attempt (disable gpu in appState.json)
- Update appState.json to contain the following content:
```json
{"lastWindowState":{"rect":{"x":0,"y":1126,"width":1,"height":22},"maximized":false},"disableGpu":true}
```
- Start Storage Explorer
- __Result__: error as mentioned above

## Expected Experience ##
It should just work and start up

## Actual Experience ##
Storage explorer never comes available and the window is hidden

**Comment by JasonYeMSFT** [comment]
@SamVanhoutte Please open the package.json at '/Applications/AzureStorageExplorer.app/Contents/Resources/app/package.json' and get the "version" field for us. That is the Storage Explorer version you are having problem with.

Also during you first attempt, are you just seeing an empty screen without any error or are you seeing the GPU error prompt and no window for Storage Explorer?

**Comment by SamVanhoutte** [comment]
@JasonYeMSFT thanks for getting back
The version field is 1.13.1

My first attempt indeed was an empty screen without an error.  The screen was not visible at all.  And when I right clicked the icon in the task bar and then selected 'show all windows', I could only see my desktop background, but when I hovered the place where the 'invisible' window apparently is, I see a blue border, but nothing of the application itself.

**Comment by MRayermannMSFT** [comment]
@SamVanhoutte can you try installing and opening VS Code?

**Comment by SamVanhoutte** [comment]
@MRayermannMSFT - I have VS Code open all the time, every day, multiple instances.  Why are you asking ?

**Comment by SamVanhoutte** [comment]
any insights, please ?

**Comment by rdotsch** [comment]
I am experiencing the very same issue on MacOS 10.15.5. Has been working fine for months, and now in the past couple of weeks, the storage explorer window simply doesn't appear anymore.  

The version field in the package is 1.12.0 (I updated storage explorer hoping it would fix the issue, but I had this problem with the previous version as well, don't know the version number though).

**Comment by MRayermannMSFT** [comment]
@SamVanhoutte @rdotsch I have a private build available of our next version. It is using a newer version of Electron. We're hoping this newer version will fix whatever issue is occurring with y'all's external GPUs. Please give it a try and let us know. Thanks!

Build link: https://storageexplorerpublish.blob.core.windows.net/privatebuilds/1.14.0-20200614.1/StorageExplorer-darwin-x64.zip

**Comment by SamVanhoutte** [comment]
I just gave it a try (version nr that popped up was something like 14.x.dev), but it's still the same behavior.  Do we need to pass a specific start up flag or something ?

**Comment by MRayermannMSFT** [comment]
@SamVanhoutte no, it should just work. Can you share what eGPU you're using? We're going to try and see if the Electron team can be of any help on this as at this point we're not sure what else to try.

**Comment by SamVanhoutte** [comment]
Hello, 
It's The BLackMagic design eGPU

**Comment by rdotsch** [comment]
Sorry, I might not have been clear in my previous post, but the issue occurs here without eGPU. The new build didn't solve this issue.

**Comment by gromag** [comment]
I had exactly the same problem for months (no GPU error though) with an empty desktop when opening Storage Explorer and blue empty rectangle and like @SamVanhoutte described, "when I right clicked the icon in the task bar and then selected 'show all windows', I could only see my desktop background, but when I hovered the place where the 'invisible' window apparently is, I see a blue border, but nothing of the application itself."

Accidentally I just found the problem and managed to revert it back to normal!

My system is macOS 10.14.6, I downloaded various version of Storage Explorer in the past months all having this problem including latest 1.17.0.

Steps I took to fix:

- connected an external monitor ( I don't think this is needed but it slowed me down with my pointer and increased my attention as I was trying to work out on in what screen the dock was available), maybe change the background to white or black to enhance contrast instead.
- noticed in the bottom left part of my Macbook Pro screen a small gray vertical bar the same size of a text entry cursor sitting on top of my desktop background image (I believe the location is specific to my circumstances)
- hovered it and my trackpad pointer turned in double arrow (as for resizing) 
- click-dragged and voila' my Storage Explorer window expanded from there!
- tried to resize it back to a cursor bar to take a screenshot to share here but I was not able to, the top left corner buttons (close, minimise and expand) seem now to define the boundaries of the minimum size the window will go if I try to squash it down.

So it seems that the Storage Explorer windows, somehow was allowed to be shrunk to a single vertical line the size of a text cursor but I cannot squash it down to this size again once resized.

Completely coincidental how I spotted, came to this post as I was painfully bugged by this very problem for months, I hope this helps.

**Comment by invisibleaxm** [comment]
FWIW i was experiencing the same issue and after reading the previous response I found out that I also was able to "restorore" the window by carefully hovering my mouse over the left border of my monitor until I had the double arrow and resize that window. I normally work with 2 monitors however this past weekend i was working with my laptop standalone and disconnected the external monitor which I believe had some sort of negative impact on the behavior.

**Comment by SamVanhoutte** [comment]
still this is really not the behavior I'm hoping for and really would hope this could get fixed, instead of a tedious work around to start up

**Comment by machive** [comment]
I have this exact same problem under 1.20, the newest release, and it is driving me crazy. 

I pick Show All Windows and I see nothing. I bring up new window, Accept the license, and it shows nothing. 

I authenticated in a browser window, it says I authenticated, but, again, no windows. 

Help.

**Comment by machive** [comment]
I went back to 1.17 and the same behavior. I accept the license terms, over and over, and see no windows.

**Comment by JasonYeMSFT** [comment]
@machive Are you using multiple monitors? For unknown reason, Storage Explorer window may be resized to have 0 width. Could you follow Invisibleaxm's comment in this thread to see if it is the case?

**Comment by machive** [comment]
Jason, 

  Thanks for the reply. I'm trying to get the double arrow at the left side of the laptop and have been having no luck. I don't remember working with two monitors recently but I have in the past. I do remember moving the Azure Storage Explorer window out of the way quickly only to see it disappear and never come back. I have tried plugging in a second monitor but have not been able to find the window. 
  
    Any other ideas?

**Comment by machive** [comment]
Wow, somehow, I found it in the lower left on my laptop but it was basically invisible! 

Thanks for your help.

**Comment by brenoalvs** [comment]
> Wow, somehow, I found it in the lower left on my laptop but it was basically invisible!
Me too! I've found a very small line on the lower left of my screen.
The window was completely minimized on both directions.

What I've done:
1. Right click on Storage Explorer icon > Show All Windows
2. The small line should be highlighted with a blue border on the lower left of your screen.
3. Double click it to expand horizontally
3. Then double click it again to expand it vertically.

**Comment by AJ1039593** [comment]
> 2\. he lower left of your screen

could please take a screen

I have the same screen as @crizzs

**Comment by crizzs** [comment]
Thanks!! You made life easier for Mac users!!

**Comment by phawxby** [comment]
This is such a weird stupid issue. I've just spent the last hour trying to make it work. Thanks to the folks above, their fix works perfectly.

**Comment by crizzs** [comment]
ikr......Weird! lolol

**Comment by myamma** [comment]
Thanks Gromag! I would not have noticed that small vertical bar if not for your post

**Comment by hadasdavid** [comment]
I was juts minimized! Can't believe I spent an hour on this!!!

**Comment by Siraj-Qazi** [comment]
Was facing the same issue on macOS Monterey (12.2.1) on my MacBook Air (M1, 2020) with or without using the external display
Couldn't see the small cursor-like window of Azure Storage Explorer until I lowered my display resolution from System Preferences > Displays and choosing "Scaled" with the "Larger Text" option (I believe it is 1024x640)
Then I closed all other windows, went to the desktop and opened Mission control, it showed "No available windows" popup, but I was able to see a small black cursor in the very bottom left. Was able to then drag and resize it.

**Comment by TRybina132** [comment]
Found it in the middle of screen, I had to change my wallpaper to find it

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/98330987/214156339-a9784892-edbf-4298-835f-3c8f8266c98f.png">

**Comment by poseidon0206** [comment]
> I had exactly the same problem for months (no GPU error though) with an empty desktop when opening Storage Explorer and blue empty rectangle and like @SamVanhoutte described, "when I right clicked the icon in the task bar and then selected 'show all windows', I could only see my desktop background, but when I hovered the place where the 'invisible' window apparently is, I see a blue border, but nothing of the application itself."
> 
> Accidentally I just found the problem and managed to revert it back to normal!
> 
> My system is macOS 10.14.6, I downloaded various version of Storage Explorer in the past months all having this problem including latest 1.17.0.
> 
> Steps I took to fix:
> 
> * connected an external monitor ( I don't think this is needed but it slowed me down with my pointer and increased my attention as I was trying to work out on in what screen the dock was available), maybe change the background to white or black to enhance contrast instead.
> * noticed in the bottom left part of my Macbook Pro screen a small gray vertical bar the same size of a text entry cursor sitting on top of my desktop background image (I believe the location is specific to my circumstances)
> * hovered it and my trackpad pointer turned in double arrow (as for resizing)
> * click-dragged and voila' my Storage Explorer window expanded from there!
> * tried to resize it back to a cursor bar to take a screenshot to share here but I was not able to, the top left corner buttons (close, minimise and expand) seem now to define the boundaries of the minimum size the window will go if I try to squash it down.
> 
> So it seems that the Storage Explorer windows, somehow was allowed to be shrunk to a single vertical line the size of a text cursor but I cannot squash it down to this size again once resized.
> 
> Completely coincidental how I spotted, came to this post as I was painfully bugged by this very problem for months, I hope this helps.

Thank you good sir. Saved my day!

**Comment by ichivers** [comment]
This is still happening with version 1.32.1.  Open Script Editor app and run this script:

tell application "System Events" to tell process "Microsoft Azure Storage Explorer"
	tell window 1
		set {size, position} to {{1280, 800}, {50, 50}}
	end tell
end tell

This will recover the window so you can see it!  I tried the method described above, including setting my wallpaper to black but I didn't have a grey bar.
