### ISSUE TITLE
CosmosDB Query Tab does not show "Execute Query" button in dark theme

### ISSUE THREAD

**Issue by blugri** [microsoft/AzureStorageExplorer#3087]
**Storage Explorer Version**: 1.13.1>
**Build Number**: 20200515.1 
**Platform/OS**: macOS Catalina
**Architecture**: x64
**Regression From**:  No

## Bug Description ##
The "Execute Query" button of the Open Query Tab for CosmoDB is not visible in the Dark theme

## Steps to Reproduce ##
1. Select Dark Theme
2. Navigate to a CosmosDB container
3. right click and select "Open Query Tab"

## Expected Experience ##
Buttons should be visible

## Actual Experience ##
Buttons are only visible on mouseover

## Additional Context ##
none

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
