### ISSUE TITLE
No longer able to drag a file from windows explorer to a blob container.

### ISSUE THREAD

**Issue by DevilsChargers** [microsoft/AzureStorageExplorer#3088]
**Storage Explorer Version**: 1.13.1
**Build Number**: 20200515.1
**Platform/OS**: Window 10
**Architecture**: x64
**Regression From**:  unsure of last working version

## Bug Description ##
I can no longer drag a file from windows explorer into a blob container.

## Steps to Reproduce ##
Navigate to a blob container in Storage Explorer, try to drag a txt or csv file into the contents pane.  Cursor is the blocking symbol.  Used to be able to do this easily.  Now have to use the upload menu and browse to my file.

## Expected Experience ##
Used to be just be able to drag a file into a blob container.

## Actual Experience ##
Dragging a file into the container is blocked.  Have to use the upload menue

**Comment by jinglouMSFT** [comment]
How did you connect to the Azure storage resources?  I just tried drag&drop while I am signed into Azure on a regular Blob container and an ADLS Gen2 enabled container, both worked just fine.  Any additional information you can provide probably could help us narrow down the case.  Thanks.

**Comment by DevilsChargers** [comment]
I used the typical sign on via a web authentication that pops up.  Same as if I were signing into the portal.  This was working for the year or more I've been using the explorer.  The other day I updated to the latest version, and now this happens.

Would removing the account and re-adding it help possibly?  I've been using the same couple of accounts for some time.

**Comment by DevilsChargers** [comment]
Closing.  Whatever was happening was something else on my system.  When I encountered the issue I restarted the application, several times, rebooted my machine, and the problem remained.  However, 2 days after opening the issue, the problem is gone and I can drag files into containers again.
