### ISSUE TITLE
The attached queue works well under Quick Access after detaching the original queue

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3090]
**Storage Explorer Version:** 1.14.0-dev
**Build**: 20200609.1
**Branch**: master
**Platform/OS:** Windows 10/ macOS Mojave / Linux Ubuntu 16.04
**Architecture:** ia32/x64
**Regression From:** Previous release(1.13.1)

**Steps to reproduce:**

1. Expand one storage account -> Queues.
2. Create a queue -> Attach it via SAS -> Add the attached queue to Quick Access.
3. **Detach** the queue.
4. Check the attached queue under Quick Access.

**Expect Experience:**
The attached queue doesn't work under Quick Access.

**Actual Experience:**
The attached queue works well under Quick Access.

**More Info:**

1. This issue also reproduces for the Azure AD attached queues.
2. This issue still reproduces after manually refreshing.
3. All actions work well in Editor.

**Comment by craxal** [comment]
@jinglouMSFT Do we really want Quick Access items from SAS items to stop working if the SAS item is detached?

**Comment by v-xianya** [comment]
This issue is fixed on build 20200611.4. So we close it.
