### ISSUE TITLE
A blob with 0 byte is not sorted by size

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3091]
**Storage Explorer Version:** 1.14.0-dev
**Build**: 20200609.1
**Branch**: master
**Platform/OS:** Windows 10/ macOS Mojave / Linux Ubuntu 16.04
**Architecture:** ia32/x64
**Regression From:** Previous release(1.13.1)

**Steps to reproduce:**

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload multiple blobs and one blob with 0 byte.
3. Sort by 'Size' -> Check the result.

**Expect Experience:**
The blob with 0 byte is sorted by size.

**Actual Experience:**
The blob with 0 byte is not sorted by size.

**Comment by v-xianya** [comment]
This issue is fixed on build 20200611.4. So we close it.
