### ISSUE TITLE
Cannot open new tabs using the 'Open in New Tab' for one opened queue

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3092]
**Storage Explorer Version:** 1.14.0-dev
**Build**: 20200609.1
**Branch**: master
**Platform/OS:** Windows 10/ macOS Mojave / Linux Ubuntu 16.04
**Architecture:** ia32/x64
**Regression From:** Previous release(1.13.1)

**Steps to reproduce:**

1. Expand one storage account -> Queues.
2. Create a queue -> Open it. 
3. Right click the queue -> Click 'Open in new Tab'.
4. Check the result.

**Expect Experience:**
A new tab opens.

**Actual Experience:**
No new tab opens.

**Comment by v-xianya** [comment]
Verified on build 20200611.4. Fixed. So we close it.
