### ISSUE TITLE
Download file stuck

### ISSUE THREAD

**Issue by lx1054331851** [microsoft/AzureStorageExplorer#3093]
**Storage Explorer Version**:  1.13.1
**Build Number**:  20200515.1
**Platform/OS**:  win10
**Architecture**: 
**Regression From**:  

## Bug Description ##

After I click the download button, the download progress does not change, it always show as below picture
![image](https://user-images.githubusercontent.com/12423206/84137941-0c78ca80-aa80-11ea-8523-403447b4ad5d.png)

**Comment by MRayermannMSFT** [comment]
@lx1054331851 is this consistently reproducing for you? What Azure environment (public Azure, Azure China, Azure Germany, etc.) are you working with? Does this only happen with this container?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having issues, please open up a new issue, thanks.
