### ISSUE TITLE
Unable to connect to subscription/resource group

### ISSUE THREAD

**Issue by sampathkg-git** [microsoft/AzureStorageExplorer#3094]
**Storage Explorer Version**: <1.13.1 -->
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:  

## Bug Description ##
<Storage explorer doesn't display storage accounts associated with subscription>

## Steps to Reproduce ##
<Just installed new version and could not get details on existing storage accounts-->
 

## Expected Experience ##
<Be able to navigate to any of the storage accounts in the subscription -->

## Actual Experience ##
<Can't see any of the storage accounts or containers -->

## Additional Context ##
<Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: 271df5c2-953a-497b-93ad-7adf7a4b3cd7, Error: {
  "name": "Error",
  "message": "self signed certificate in certificate chain",
  "stack": "Error: self signed certificate in certificate chain\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at TLSSocket.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at TLSSocket.emit (events.js:182:13)\n    at TLSSocket._finishInit (_tls_wrap.js:631:8)",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}
>

**Comment by jinglouMSFT** [comment]
Can you try to follow this troubleshooting guide to see if you can fix your issue first?  https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C1904#error-self-signed-certificate-in-certificate-chain-and-similar-errors 
Thanks.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you're still having problems.
