### ISSUE TITLE
Account Disappeared shortly after logging in - 1.13.1

### ISSUE THREAD

**Issue by zexu-ms** [microsoft/AzureStorageExplorer#3096]
![image](https://user-images.githubusercontent.com/66660732/84288362-a8cfc980-ab73-11ea-8516-a87a420f8b0e.png)

## Bug Description ##
This day, the account just disappear in the account management. After I logged in, just a few minutes it happens again.

Prompting that "Cannot read property 'OriginalAccountObj' of undefined".

**Comment by MRayermannMSFT** [comment]
@zexu-ms do you mean an error dialog came up, or did you see that message somewhere else?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems. Thanks.
