### ISSUE TITLE
Sign-in error

### ISSUE THREAD

**Issue by ah6511** [microsoft/AzureStorageExplorer#3097]
Mac version 1.13.1.
With VPN connection, try to add account with workplace, after 2 factor authentication,
wait for a while and then got error: 'The operation was canceled'.

**Comment by MRayermannMSFT** [comment]
Huh, that is very odd. @ah6511, can you do the following for me?

1. Open Storage Explorer
2. Go to settings -> application -> sign in
3. Make sure both "Microsoft Authentication Library (preview)" and "Verbose Authentication Logging" are checked
4. Close Storage Explorer
5. Delete all files in `/Users/<your username>/.ServiceHub/logs`
6. Re open Storage Explorer
7. Reproduce the issue
8. Close Storage Explorer
9. Zip up `/Users/<your username>/.ServiceHub/logs` and attach it here.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems. Thanks.
