### ISSUE TITLE
Version 1.13.1 is showing all User Properties for a blob file as having lowercase keys

### ISSUE THREAD

**Issue by chitoiur** [microsoft/AzureStorageExplorer#3098]
It is quite easy to reproduce. Upload a file, right click and select Properties. Add user property whose key starts with an uppercase and Save. Then, open Properties again and your property key now shows up as lowercase. It seems to save them as lowercase, because when I read it from code, they are lowercase. But also, if I use code to save them with uppercase, when I go to Properties, they are now lowercase.

v1.12.0 works fine.

![Before](https://user-images.githubusercontent.com/272443/84400166-b87cfb80-abcf-11ea-9204-173f52aff54b.PNG)
![After](https://user-images.githubusercontent.com/272443/84400169-b9159200-abcf-11ea-8dce-f94612760e1d.PNG)

**Comment by JasonYeMSFT** [comment]
@chitoiur, there is a behavior change in the storage SDK we are using. FYI, the metadata keys are supposed to treated case-insensitively so this behavior change isn't breaking their spec. https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-properties-metadata#set-and-retrieve-metadata

**Comment by chitoiur** [comment]
Thanks Jason. When you say storage SDK, do you mean Microsoft.Azure.WebJobs.Extensions.Storage? Our application uses 3.x and it seems it is case sensitive. Is v4 not case sensitive?

**Comment by JasonYeMSFT** [comment]
No, we are using the NodeJS SDK for storage (https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage). Since the doc says it should be case insensitive, the implementation is free to choose whether to preserve the casing or not.

**Comment by chitoiur** [comment]
So it seems like the implementation (Microsoft.Azure.WebJobs.Extensions.Storage) didn't follow the docs. We seem to be stuck on 1.12.0 for the foreseeable future, because our keys are case sensitive.

Thanks for the help, feel free to close.
