### ISSUE TITLE
Users must be able to duplicate a row displayed on Azure Storage Explorer

### ISSUE THREAD

**Issue by Arash-Sabet** [microsoft/AzureStorageExplorer#3099]
**Is your feature request related to a problem? Please describe.**
There are occasions when a new row/record in a table would be slightly different from another existing one. It's frustrating to create a brand new table row and copy/paste values from the other existing row.

**Describe the solution you'd like**
The best and most intuitive UI experience would be to be able to duplicate an existing row, tweak the wanted value(s) and then apply the changes to the storage.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by jinglouMSFT** [comment]
Is this request for Table or for CosmosDB?  If Table, this is a duplicate of #2547

**Comment by Arash-Sabet** [comment]
> Is this request for Table or for CosmosDB? If Table, this is a duplicate of #2547

Azure Storage Tables. So I am closing it due to duplication. When will #2547 be released?
