### ISSUE TITLE
Do not allow account label to be modified in connect with Connection string 

### ISSUE THREAD

**Issue by xyh1** [Microsoft/AzureStorageExplorer#31]
**Storage Explorer Version:** 0.9.6

**OS Version:** Windows 10

**Steps to Reproduce:**

1. Right Click "Storage Accounts"
2. Select "Connect to Azure Storage"
3. Select "Use a connection string or a shared access signature URI"
4. Enter "Connection string:"
5. Modify Account Label to be anything you want, invalid account name with uppercase letters and or special characters

**Expected Experience:**
Do not allow Account label to be modified as the connection string has everything that the customer needs already. The account label overwrites the account name in the connection string

Connection string should be the only input allowed.

**Actual Experience:**
Able to successfully mount invalid accounts names, which modified the connection string

![image](https://user-images.githubusercontent.com/2829937/38157547-d4aff6ca-343c-11e8-88a4-63925db781d1.png)
![image](https://user-images.githubusercontent.com/2829937/38157630-8a90c74e-343d-11e8-8002-215c8203ddf3.png)

**Comment by MRayermannMSFT** [comment]
Merged into @craxal 's feature branch.
