### ISSUE TITLE
Add "View Error..." action for all Quick Access node types

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3101]
**Storage Explorer Version:** 1.14.0-dev
**Build**: 20200611.9
**Branch**: master
**Platform/OS:** Windows 10/ macOS Catalina/ Linux Ubuntu 18.04
**Architecture:** ia32/x64
**Regression From:** Previous release (1.13.1)

**Steps to reproduce:**
1. Attach one blob container & file share & queue & table via SAS.
2. Add the attached services to QA.
3. Detach the attached services -> Refresh the Quick Access node.
4. Check the QA attached services context menu.

**Expect Experience:**
Keep consistent actions on the context menu.

**Actual Experience:**
1. Display 'Remove from Quick Access' for blob container & file share & table.
2. Display 'View Error...' & 'Remove from Quick Access' for queue.
![image](https://user-images.githubusercontent.com/41351993/84478855-92855300-acc4-11ea-8b8e-f8d102a238bd.png)

**Comment by craxal** [comment]
@v-xianya This is not a regression. This is intended, brand new behavior that we have added for queues. We will add the same behavior for other node types at a later point.

**Comment by v-xianya** [comment]
Update:
Verified on the build main 20211125.2.
1. The 'View Error' action has been added for 'File Shares/Queue/Blob Container'. 
2. Reproduce for tables.

Details. The error info and the title of the dialog are inconsistent when clicking 'View Error...' for 'File Shares/Queue/Blob Container'
@MRayermannMSFT Could you please help to take a look at this and tell us which one is the most accurate?😊
![image](https://user-images.githubusercontent.com/41351993/143390519-50a200b2-96fe-4a77-9d00-8725fb1fe5f6.png)

**Comment by v-xianya** [comment]
This issue has been fixed on the build rel/1.24.0 20220421.6. 
There is a similar issue [5523](https://github.com/microsoft/AzureStorageExplorer/issues/5523) for the Comments. We are going to close this bug.
