### ISSUE TITLE
Keep a consistent time format for 'Last Modified' between blob containers and file shares

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3102]
**Storage Explorer Version:** 1.14.0-dev
**Build**: 20200611.9
**Branch**: master
**Platform/OS:** Windows 10/ macOS Catalina / Linux Ubuntu 18.04
**Architecture**: ia32/x64
**Regression From**: Previous release (1.13.1)

**Steps to reproduce:**

1. Expand one storage account -> Blob Containers.
2. Select one blob container -> Check the 'Last Modified' time format on 'Properties' panel.

**Expect Experience:**
Keep a consistent time format.
![image](https://user-images.githubusercontent.com/54055206/84481107-2ad10700-acc8-11ea-9cc7-89842068ea93.png)
![image](https://user-images.githubusercontent.com/54055206/84480738-9d8db280-acc7-11ea-9382-6e3c69d6993c.png)

**Actual Experience:**
The blob container's 'Last Modified' is inconsistent.
![image](https://user-images.githubusercontent.com/54055206/84479521-ac736580-acc5-11ea-8e46-4d83b3281932.png)

**More Info:**
This issue doesn't reproduce for one new created blob container.

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
