### ISSUE TITLE
Update the text input on the ADLS Gen2 blobs 'Rename File' dialog

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3103]
**Storage Explorer Version:** 1.14.0-dev
**Build**: 20200611.9
**Branch**: master
**Platform/OS:** Windows 10/ macOS Catalina / Linux Ubuntu 18.04
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a new blob container -> Upload one blob to it.
3. Click 'Rename...' -> Check the text input in the popped dialog. 

**Expect Experience:**
The text input shows below.
![image](https://user-images.githubusercontent.com/54055206/84480397-13454e80-acc7-11ea-8620-f9b022c843a8.png)

**Actual Experience:**
The text input is not updated.
![image](https://user-images.githubusercontent.com/54055206/84481356-8e5b3480-acc8-11ea-88c8-feb45f7e0df1.png)

**More Info:**
This issue also reproduces on **'Rename Folder'** dialog.

**Comment by MRayermannMSFT** [comment]
Fix merged into master for 1.15.0
