### ISSUE TITLE
Subscriptions for the follwowing tenants could not be retrieved: Tenant Id: zzz, Error: {"code":"EAI_AGAIN","errno":"EAI_AGAIN","syscall":"getaddrinfo","hostname":"management.azure.com","host":"management.azure.com","port":443}

### ISSUE THREAD

**Issue by devenderninaniya** [microsoft/AzureStorageExplorer#3104]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:

**Comment by MRayermannMSFT** [comment]
@devenderninaniya are you behind a proxy?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems. Thanks.
