### ISSUE TITLE
Azure Storage Explorer said file uploaded but actually didn't

### ISSUE THREAD

**Issue by nirnaymsft** [microsoft/AzureStorageExplorer#3106]
**Storage Explorer Version**: 
1.13.0
**Build Number**: 
1.13.0
**Platform/OS**: 
Windows 10
**Architecture**: 
x64
**Regression From**:  
Don't know

## Bug Description ##

I elevated myself as Administrator on Subscription via JIT
Usually JIT takes time, but I still tried to upload the file
Storage Explorer showed File uploaded (green). But actually it didn't.

To prove this theory, I tried uploading the same file from Azure Portal and there it gave me error:
AccessControlException: [aadedd4a-e34a-4fac-9157-8bdedd1b2037] Access Denied : /assemblies/Payout.Payable.Extensions.dll[2020-06-13T15:59:30.6594580-07:00]

This is correct error, because I don't have permission. But Storage Explorer didn't showed any error.

## Steps to Reproduce ##

Elevate to Admin using JIT
Don't wait and upload the file
See Green Uploaded confirmation in Storage Explorer
Check file, it is still old.

## Expected Experience ##

File should be new after Green confirmation

## Actual Experience ##

Check file, it is still old.
![error](https://user-images.githubusercontent.com/48266262/84580918-c332be80-ad90-11ea-94cc-d2aab77fabb6.png)

**Comment by MRayermannMSFT** [comment]
@nirnaymsft is this for Blobs, ADLS Gen1, or ADLS Gen2?

**Comment by nirnaymsft** [comment]
Azure Data Lake Storage Gen1

**Comment by MRayermannMSFT** [comment]
@nirnaymsft have you seen this in ADLS Gen2?

**Comment by nirnaymsft** [comment]
Not tried.

**Comment by jinglouMSFT** [comment]
The retirement of ADLS Gen1 is now less than three months away. As [previously announced](https://azure.microsoft.com/en-us/updates/action-required-switch-to-azure-data-lake-storage-gen2-by-29-february-2024/) the service will be retired on 29 February 2024. With this date now close approaching we are going to close this issue as "won't fix". Documentation on how to migrate your data to ADLS Gen2/blob storage can be found here: https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-migrate-gen1-to-gen2-azure-portal

If you have any non ADLS Gen1 feedback for Storage Explorer, please feel free to open a new issue: https://github.com/microsoft/AzureStorageExplorer/issues/new/choose

This issue will now no longer be monitored.
