### ISSUE TITLE
No 'Lease Status' property displays for one ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3107]
**Storage Explorer Version:** 1.14.0-dev
**Build**: 20200614.2
**Branch**: rel/1.14.0
**Platform/OS:** Windows 10/ macOS Catalina / Linux Ubuntu 18.04
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a new blob container -> Check its Properties panel.

**Expect Experience:**
The property 'Lease Status' displays.

**Actual Experience:**
No property 'Lease Status' displays.
![image](https://user-images.githubusercontent.com/41351993/84634469-71bb3880-af24-11ea-9f96-5ae652f5f81a.png)

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT 
 Verified this issue on build master/20200630.1.
1. The property 'Lease Status' displays well for one existing ADLS Gen2 blob container.
![image](https://user-images.githubusercontent.com/41351993/86078116-f333ce80-babf-11ea-95ec-e2a8ef24e934.png)

2. The property 'Lease Status' doesn't auto display for one **new created ADLS Gen2** blob container.

**Comment by MRayermannMSFT** [comment]
Ok, fix fully checked into master now. Closing.
