### ISSUE TITLE
Unable to download file from File Storage

### ISSUE THREAD

**Issue by hildo** [microsoft/AzureStorageExplorer#3109]
**Storage Explorer Version**: 1.13.1
**Build Number**: 20200515.1
**Platform/OS**: Windows 10
**Architecture**:  ia32
**Regression From**:  1.12.0

## Bug Description ##
I am attempting to download a file from a File Storage account.  I can navigate through Storage Explorer fine, and can see the file.  However, when I attempt to download it fails with the message "Transfer of 'filename' to 'location' failed (used SAS)" (filename and location snipped for brevity).

Using an older version of Storage Explorer (1.12.0) on a different PC, but against the same account / file in Azure, the download succeeds

## Steps to Reproduce ##
Use Storage explorer to find a file in a File Storage container
Click download in Storage Explorer

## Expected Experience ##
I expected the file to download

## Actual Experience ##
The download fails

**Comment by hildo** [comment]
The azcopy log from the failed transfer

2020/06/16 01:49:13 AzcopyVersion  10.4.2
2020/06/16 01:49:13 OS-Environment  windows
2020/06/16 01:49:13 OS-Architecture  amd64
2020/06/16 01:49:13 Log times are in UTC. Local time is 16 Jun 2020 11:49:13
2020/06/16 01:49:13 Job-Command copy https://cluster30file.file.core.windows.net/app-services/support/floridacanyon/mstarFiles/nodes/default/logs/minestar-site.log?se=2020-07-16t01%3A49%3A05z&sig=-REDACTED-&sp=rl&sr=s&sv=2018-03-28 C:\SiteData\FloridaCanyon\logs\minestar-site.log --output-type=json --overwrite=prompt --cancel-from-stdin --recursive --from-to=FileLocal --check-md5 FailIfDifferent 
2020/06/16 01:49:13 Number of CPUs: 12
2020/06/16 01:49:13 Max file buffer RAM 6.000 GB
2020/06/16 01:49:13 Max concurrent network operations: 192 (Based on number of CPUs. Set AZCOPY_CONCURRENCY_VALUE environment variable to override)
2020/06/16 01:49:13 Check CPU usage when dynamically tuning concurrency: true (Based on hard-coded default. Set AZCOPY_TUNE_TO_CPU environment variable to true or false override)
2020/06/16 01:49:13 Max concurrent transfer initiation routines: 64 (Based on hard-coded default. Set AZCOPY_CONCURRENT_FILES environment variable to override)
2020/06/16 01:49:13 Max enumeration routines: 64 (Based on hard-coded default. Set AZCOPY_CONCURRENT_SCAN environment variable to override)
2020/06/16 01:49:13 Max open files when downloading: 2147482995 (auto-computed)
2020/06/16 01:49:13 Failed to check if the destination is a folder or a file (Azure Files). Assuming the destination is a file: -> github.com/Azure/azure-storage-file-go/azfile.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.7.0/azfile/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=ResourceNotFound) =====
Description=The specified resource does not exist.
RequestId:0bc58aa5-901a-0068-6c80-433564000000
Time:2020-06-16T01:49:12.2734138Z, Details: 
   Code: ResourceNotFound
   GET https://cluster30file.file.core.windows.net/app-services/support/floridacanyon/mstarFiles/nodes/default/logs/minestar-site.log?restype=directory&se=2020-07-16t01%3A49%3A05z&sig=-REDACTED-&sp=rl&sr=s&sv=2018-03-28&timeout=901
   User-Agent: [Microsoft Azure Storage Explorer, 1.13.1, win32,  AzCopy/10.4.2 Azure-Storage/0.7.0 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [29180d0d-e623-434e-4759-04d3a00da56f]
   X-Ms-Version: [2019-02-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 404 The specified resource does not exist.
   Content-Length: [223]
   Content-Type: [application/xml]
   Date: [Tue, 16 Jun 2020 01:49:11 GMT]
   Server: [Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0]
   Vary: [Origin]
   X-Ms-Client-Request-Id: [29180d0d-e623-434e-4759-04d3a00da56f]
   X-Ms-Error-Code: [ResourceNotFound]
   X-Ms-Request-Id: [0bc58aa5-901a-0068-6c80-433564000000]
   X-Ms-Version: [2019-02-02]



2020/06/16 01:49:13 Any empty folders will be processed, because source and destination both support folders
2020/06/16 01:49:13 Final job part has been created
2020/06/16 01:49:13 PERF: primary performance constraint is Unknown. States: C:  0, R:  0, W:  0, F:  0, H:  0, B:  0, S:  0, P:  0, Q:  0, D:  0, E:  0, T:  0, GRs:  1
2020/06/16 01:49:13 scheduling JobID=baf7b1ac-90be-1345-6882-abc91beed52a, Part#=0, Transfer#=0, priority=0
2020/06/16 01:49:13 Final job part has been scheduled
2020/06/16 01:49:13 INFO: [P#0-T#0] has worker 33 which is processing TRANSFER
2020/06/16 01:49:15 PERF: primary performance constraint is Unknown. States: C:  0, R:  0, W:  0, F:  0, H:  0, B:  0, S:  0, P:  0, Q:  0, D:  0, E:  0, T:  0, GRs: 192
2020/06/16 01:49:17 PERF: primary performance constraint is Unknown. States: C:  0, R:  0, W:  0, F:  0, H:  0, B:  0, S:  0, P:  0, Q:  0, D:  0, E:  0, T:  0, GRs: 192
2020/06/16 01:49:19 PERF: primary performance constraint is Unknown. States: C:  0, R:  0, W:  0, F:  0, H:  0, B:  0, S:  0, P:  0, Q:  0, D:  0, E:  0, T:  0, GRs: 192
2020/06/16 01:49:21 PERF: primary performance constraint is Unknown. States: C:  0, R:  0, W:  0, F:  0, H:  1, B:  0, S:  0, P:  0, Q:  0, D:  0, E:  0, T:  1, GRs: 192
2020/06/16 01:49:22 ==> REQUEST/RESPONSE (Try=1/959.4315ms, OpTime=3.4398148s) -- RESPONSE SUCCESSFULLY RECEIVED
   GET https://cluster30file.file.core.windows.net/app-services/support/floridacanyon/mstarFiles/nodes/default/logs/minestar-site.log?se=2020-07-16t01%3A49%3A05z&sig=-REDACTED-&sp=rl&sr=s&sv=2018-03-28&timeout=901
   X-Ms-Request-Id: [ff26bfbc-901a-0057-4280-43fdc7000000]

2020/06/16 01:49:22 ERR: [P#0-T#0] DOWNLOADFAILED: https://cluster30file.file.core.windows.net/app-services/support/floridacanyon/mstarFiles/nodes/default/logs/minestar-site.log?se=2020-07-16t01%3A49%3A05z&sig=-REDACTED-&sp=rl&sr=s&sv=2018-03-28 : 000 : Azure File modified during transfer. When Azure File modified during transfer. X-Ms-Request-Id: 

   Dst: %5C%5C?\C:\SiteData\FloridaCanyon\logs\minestar-site.log
2020/06/16 01:49:22 INFO: [P#0-T#0] Error reading body of reply. Next try (if any) will be Try=2. Will NOT retry. Error: context canceled. Offset: 512  Count: 6791474 URL: https://cluster30file.file.core.windows.net/app-services/support/floridacanyon/mstarFiles/nodes/default/logs/minestar-site.log?se=2020-07-16t01%3A49%3A05z&sig=-REDACTED-&sp=rl&sr=s&sv=2018-03-28
2020/06/16 01:49:22 INFO: [P#0-T#0] https://cluster30file.file.core.windows.net/app-services/support/floridacanyon/mstarFiles/nodes/default/logs/minestar-site.log?se=2020-07-16t01%3A49%3A05z&sig=-REDACTED-&sp=rl&sr=s&sv=2018-03-28 Deleting incomplete destination file Dst: %5C%5C?\C:\SiteData\FloridaCanyon\logs\minestar-site.log
2020/06/16 01:49:22 JobID=baf7b1ac-90be-1345-6882-abc91beed52a, Part#=0, TransfersDone=1 of 1
2020/06/16 01:49:22 all parts of entire Job baf7b1ac-90be-1345-6882-abc91beed52a successfully completed, cancelled or paused
2020/06/16 01:49:23 PERF: primary performance constraint is Unknown. States: C:  0, R:  0, W:  0, F:  0, H:  0, B:  1, S:  0, P:  0, Q:  0, D:  0, E:  0, T:  1, GRs: 192

**Comment by MRayermannMSFT** [comment]
@hildo are you still seeing this?

Towards the bottom of the log we see "Azure File modified during transfer. When Azure File modified during transfer." So this was probably just a temporary issue. Try to only download/upload files when you are the only person accessing it.

**Comment by hildo** [comment]
Thanks @MRayermannMSFT I have tried again and it succeeds now.

For context, this file is a log file for services running in a service fabric cluster, and this particular file is the active log file (the log file rotates every 24 hour period).  Being the active log file, it's hard to guarantee being the only process accessing it (and it's not clear to me if there was another user attempting to download the same file -- I didn't think there was, but the cloud being the cloud).

All that said, it didn't seem to be a problem with an earlier release of Storage Explorer.  That's why it looked like a regression, from my perspective.

**Comment by MRayermannMSFT** [comment]
No worries. Just know in the future you might have to try a few times for this file.

**Comment by Cloudmersive** [comment]
Why is this issue closed?  This is super broken

**Comment by efd7887** [comment]
Its still broken
