### ISSUE TITLE
Add an option to use custom domain when copying Blob URLs

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3110]
**Storage Explorer Version:** 1.14.0
**Build**: 20200616.5
**Branch**: rel/1.14.0
**Platform/OS:** Windows 10/ macOS Catalina / Linux Ubuntu 18.04
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Right click the blob -> Check the 'Copy URL' action on its context menu.

**Expect Experience:**
Display a sub-menu for 'Copy URL' action.

**Actual Experience:**
No sub-menu displays for 'Copy URL' action.

**Comment by MRayermannMSFT** [comment]
@v-xianya the submenu only appears if there is a custom domain configured for the storage account. Is there a custom domain configured for the account you were using to test?

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT Thanks for your clarification. We tried to figure out configure a custom domain for one storage account but still no idea how to create a storage account with a custom domain. Is there an storage account can be provided?🙃

**Comment by MRayermannMSFT** [comment]
@craxal will help y'all set something up.

**Comment by v-xianya** [comment]
Hi @craxal Thank you for the help.

 Also there are two things need to confirm with you😀 Are these expected?
1. For one new created blob container, It requires a refresh to show the 'Custom Domain'.
2. For one new created blob container and its property 'Custom Domain' already shows, then upload one blob to it. It need to reopen the blob container to make the sub-menu of Copy URL shows.

**Comment by craxal** [comment]
@v-xianya

**Comment by v-xianya** [comment]
Hi @craxal Thanks for the updates
1. Yes, It needs to refresh 'Blob Containers' node to show the 'Custom Domain' for one new created blob container.
(New bug: [3110](https://github.com/microsoft/AzureStorageExplorer/issues/3273))
