### ISSUE TITLE
Can't switch to the whitespace directory by clicking the directory in the blob path view

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3111]
**Storage Explorer Version:** 1.14.0
**Build**: 20200616.5
**Branch**: rel/1.14.0
**Platform/OS:** Windows 10/ macOS Catalina / Linux Ubuntu 18.04
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob (input '/1/ /2' into Destination directory).
3. Try to switch to the whitespace directory by clicking the directory in the path view.
4. Check the result.

**Expect Experience:**
Succeed to switch to the directory.

**Actual Experience:**
Nothing happens.
![image](https://user-images.githubusercontent.com/41351993/84753464-9b8e6100-aff1-11ea-9b17-cfd0fe3d74b1.png)

**Comment by MRayermannMSFT** [comment]
Related to #45

**Comment by craxal** [comment]
@v-xianya Not able to reproduce from master branch. Can you try again using a more recent master branch build? A blue border should also appear when hovering your cursor over the breadcrumb.

![image](https://user-images.githubusercontent.com/3473026/87990084-28688680-ca98-11ea-98bb-a0493d352826.png)

**Comment by v-xianya** [comment]
Hi @craxal
Verified this issue on build master/20200720.3. 
1. This issue doesn't reproduce for one regular blob container.
2. **It reproduces for one ADLS Gen2 blob container,** Could you help to take a look?

**Comment by craxal** [comment]
There's still a PR out got ADLS Gen2 that should address this issue, and I am unable to reproduce with the change in that PR.
