### ISSUE TITLE
'Requeue Message' action doesn't work for one emulator queue 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3112]
**Storage Explorer Version:** 1.14.0
**Build**: 20200616.5
**Branch**: rel/1.14.0
**Platform/OS:** Windows 10
**Emulator:** (5.10.0.0)
**Architecture:** x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Make sure Storage Emulator(5.10.0.0) is started.
2. Expand 'Local & Attached' -> 'Storage Accounts' -> '(Emulator - Default Ports)(Key)' -> 'Queues'.
3. Create a new queue -> Add a message -> Try to requeue the message.
4. Check the result.

**Expect Experience:**
Succeed to requeue the message.

**Actual Experience:**
The 'Requeue Message' action doesn't work.

**More Info:**
This issue doesn't reproduce in Azurite (3.7.0)

**Comment by craxal** [comment]
The time to live for the requeued message is the original message's remaining time to live, which is calculated by subtracting the insertion time from the expiration time. This doesn't work well if the message's time to live was set to -1, which appears as an expiration time of 9999-12-31T23:59:59.000Z. The best solution here is to default to 7 days (the maximum time to live) in the case of emulators (or Azure Stack).

**Comment by MRayermannMSFT** [comment]
@v-limu , we're going to change to something other than what Craig said. We're going to:

- make the default time to live 7 days, just like it was in version 1.13.0 and older
- if requeue fails, an error message is going to be shown

**Comment by v-limu** [comment]
Hi @MRayermannMSFT  Got it. Thanks for your the updates.
