### ISSUE TITLE
Miss 'Custom Domain' for one blob container under Quick Access

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3114]
**Storage Explorer Version:** 1.14.0
**Build**: 20200616.5
**Branch**: rel/1.14.0
**Platform/OS:** Windows 10/ macOS Catalina / Linux Ubuntu 18.04
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one storage account -> Blob Containers.
2. Select one blob container -> Add the blob container to Quick Access. 
3. Check its Properties panel under Quick Access.

**Expect Experience:**
Display 'Custom Domain'.

**Actual Experience:**
Miss 'Custom Domain'.

**Comment by MRayermannMSFT** [comment]
@v-limu the submenu only appears if there is a custom domain configured for the storage account. Is there a custom domain configured for the account you were using to test?

**Comment by MRayermannMSFT** [comment]
@v-limu  ?

**Comment by v-limu** [comment]
Hi @MRayermannMSFT  Details as below:😊
1. 'Custom Domain' property displays on 'Properties' panel after selecting one blob container. 
![image](https://user-images.githubusercontent.com/54055206/86073739-fd9d9a80-bab6-11ea-8176-677dc568104d.png)

2. No 'Custom Domain' property displays after adding the blob container to Quick Access. 
![image](https://user-images.githubusercontent.com/54055206/86074350-5ae61b80-bab8-11ea-9d1e-3f520218b89f.png)

**Comment by v-limu** [comment]
Verified on build 20200731.3. This issue has been fixed. So close it.
![image](https://user-images.githubusercontent.com/54055206/89005880-1a3c2500-d338-11ea-8fdd-0c764554102f.png)
