### ISSUE TITLE
Succeed to upload one adls gen2 blob when inputting destination directory as '/ /'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3115]
**Storage Explorer Version:** 1.14.0
**Build**: 20200616.5
**Branch**: rel/1.14.0
**Platform/OS:** Windows 10/ macOS Catalina / Linux Ubuntu 18.04
**Architecture**: ia32/x64
**Regression From**: Previous release (1.12.0)

**Steps to reproduce:**

1. Expand one ADLS Gen2  storage account -> Blob Containers.
2. Create a new blob container -> Click 'Upload' -> Select 'Upload Files...'.
3. Select one file then input '/ /' as destination directory -> Click 'Upload'.
4. Check the result.

**Expect Experience:**
Fail to upload.
![image](https://user-images.githubusercontent.com/41351993/84760299-65a1aa80-affa-11ea-95f0-f0596fafc5ee.png)

**Actual Experience:**
Succeed to upload.
![image](https://user-images.githubusercontent.com/41351993/84760408-8e29a480-affa-11ea-8b15-3810582eca31.png)

**Comment by JasonYeMSFT** [comment]
Since this is allowed by the platform, there is no reason for us to block it.
