### ISSUE TITLE
Decimal values of Maximum Transfer Rate not supported. [Not Reproducible]

### ISSUE THREAD

**Issue by Brondahl** [microsoft/AzureStorageExplorer#3116]
***Disclaimer: I could pseudo reproduce this on v `1.12.0` It was happening repeatedly when I did it by accident. I upgraded to vLatest (`1.13.1`) before logging this bug and I can no longer reproduce this. Perhaps it was a version-specific bug. Perhaps actually I just needed to restart ASE on my machine? Since I'd already written out 90% of the Issue, I'll raise this in the expectation that it'll get immediately closed, but at least there's a record for the next person. :(***

**Storage Explorer Version**:  Observed on a `1.12.0` install. Not reproducible on a `1.13.1` install.
**Build Number**: 20200116.10
**Platform/OS**: Windows
**Architecture**: ia32
**Regression From**:  N/A

## Bug Description ##
When I attempt to upload a file to blob storage, with a decimal value specified in Maximum Transfer Rate, I get an error.

## Steps to Reproduce ##
_**(Not reproducible now! See top)**_
* Establish access to a Blob Storage account.
* Entirely clear the `Maximum Transfer Rate` field in Settings > Transfer.
* Upload a file (thus demonstrating that upload is generally functional)
* Upload the file again selecting "Replace". Succeeds (thus demonstrating that re-uploads are functional)
* Enter "1" into Settings > Transfer > `Maximum Transfer Rate`
* Upload the file again. Succeeds (thus demonstrating that integer values are functional)
* Enter "1.5" into Settings > Transfer > `Maximum Transfer Rate`
* Upload the file again. Failure.
* Error message `{"message": "UnexpectedQuit" }`

## Expected Experience ##
Upload succeeds, with Upload rate throttled to the appropriate decimal value.

## Actual Experience ##
Error message popup, saying:
 Error message `{"message": "UnexpectedQuit" }`
No log file appears to be created in `.azcopy`

## Additional Context ##
Uplink bandwidth is around 1.8-2.0 Mbps.
Upload runs very happily with no limit, or with limit set to "1" or "2". (if not constrained to <2, then upload saturates the uplink, damaging the downlink performance, as previously documented on #1099.
If limit is set to 0.5 or 1.5 then the error occurs.

Current other settings are Network and File Concurrency both set to "1".

**Comment by Brondahl** [comment]
@JasonYeMSFT see above. Not reproducible, in the end.

**Comment by JasonYeMSFT** [comment]
I tried several combinations around and found you would encounter "unexpected quit" if you set decimal values for file concurrency instead of maximum transfer rate.

**Comment by JasonYeMSFT** [comment]
The updated description for "concurrency files" setting is checked in.

**Comment by Brondahl** [comment]
Ugh. 🤦 Sorry to waste your time on that, if that's what I'd been doing :(
