### ISSUE TITLE
Self-signed certificate issue

### ISSUE THREAD

**Issue by Coegmen** [microsoft/AzureStorageExplorer#3118]
Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: f8cdef31-a31e-4b4a-93e4-5f571e91255a, Error: {
  "name": "Error",
  "message": "self signed certificate in certificate chain",
  "stack": "Error: self signed certificate in certificate chain\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at TLSSocket.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at TLSSocket.emit (events.js:182:13)\n    at TLSSocket._finishInit (_tls_wrap.js:631:8)",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}
Tenant Id: a6d03e26-042b-485e-adac-9b0daf5efc81, Error: {
  "name": "Error",
  "message": "self signed certificate in certificate chain",
  "stack": "Error: self signed certificate in certificate chain\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at TLSSocket.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at TLSSocket.emit (events.js:182:13)\n    at TLSSocket._finishInit (_tls_wrap.js:631:8)",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}

**Comment by MRayermannMSFT** [comment]
@Coegmen please see our troubleshooting guide for information on how to deal with self signed certs: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C1804#error-self-signed-certificate-in-certificate-chain-and-similar-errors

**Comment by ArunKrishnamoorthi** [comment]
MS Link Provided is not resolving the issue

**Comment by MRayermannMSFT** [comment]
@ArunKrishnamoorthi can you elaborate on what you've tried from the troubleshooting link?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having issues, please open up a new issue, thanks.
