### ISSUE TITLE
Fail to delete one adls gen2 blob folder named " "

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3119]
**Storage Explorer Version:** 1.14.0
**Build**: 20200617.5
**Branch**: rel/1.14.0
**Platform/OS:** Windows 10/ macOS Catalina / Linux Ubuntu 18.04
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Bug Descriptions:**
Failed to run actions **'Delete' &'New Folder' & 'Rename' & 'Manage Access' & 'Properties'** for one adls gen2 blob folder named " ".

**Steps to reproduce:**

1. Expand one ADLS Gen2  storage account -> Blob Containers.
2. Create a new blob container -> Click 'Upload' -> Select 'Upload Files...'.
3. Select one file then set '/ /' as destination directory -> Click 'Upload'.
4. Try to delete the uploaded folder -> Check the result.

**Expect Experience:**
Succeed to delete.

**Actual Experience:**
Fail to delete.
![image](https://user-images.githubusercontent.com/41351993/84868840-dd7ddc80-b0af-11ea-98c8-5c24bb15997f.png)

Error details:
`  "message": "\"failed to perform remove command due to error: cannot start job due to error: cannot verify resource due to error: -> github.com/Azure/azure-storage-azcopy/azbfs.newStorageError, `

**More Info:**
1. Fail to delete the content in the folder.
2. Fail to manage access for the folder and the blobs in it
3. Fail to create new folder under the folder.
4. Fail to rename the folder and the blobs in it.
5. Fail to get properties for the folder.

![image](https://user-images.githubusercontent.com/41351993/84869503-b4118080-b0b0-11ea-886a-119bc98ffc76.png)

**Comment by MRayermannMSFT** [comment]
We need to figure out if this is our problem or AzCopy's problem before bringing it up with them.

**Comment by v-xianya** [comment]
@MRayermannMSFT This issue also reproduces when ADLS Gen2 blob folder name contains **'?'**.

One difference: The folder and its contents '?' can be deleted. 
![image](https://user-images.githubusercontent.com/41351993/90108837-7a41bb00-dd7d-11ea-8bf7-9a74f289f077.png)

Same behaviors: 
1. Failed to **rename & move** folder and blobs inside it.
![image](https://user-images.githubusercontent.com/41351993/90108795-6e55f900-dd7d-11ea-8b9e-ed253e0da8fa.png)

2. Fail to **manage access** for folder and blobs inside it.
3. Fail to get **properties** for the folder.

**Comment by JasonYeMSFT** [comment]
The "get properties" on folders whose name are " " now works. Unfortunately, the rest of the commands still don't work even if we use the new SDK.

- Delete " /". AzCopy attempts to HEAD the directory and receives an "invalid url" error.
- Create directory in " /". The SDK receives an "invalid url" error upon its PUT request for the new directory.
- Manage ACL of " /".  The SDK receives an undefined 400 Error upon the HEAD request to get its access control.
- Move/Rename children of " /". The SDK receives an "invalid url" error upon its PUT request for the destination.

**Comment by JasonYeMSFT** [comment]
According to the service team's response, ADLS Gen2 aren't supposed to support directories whose names are entirely whitespaces. This issue is by design then. We currently don't allow user to create directories with such names and if anyone uses external tools to get that, we will tell them that it is not supported.
