### ISSUE TITLE
Remove the default red border for required fields in 'Connect with Name and Key' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#312]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Windows 10/Linux Ubuntu 16.04/MacOS High Sierra
**Architecture**: ia32/x64
**Build Number**: 20180614.2
**Commit**: 5dbf0913
**Regression From**: This issue doesn't reproduce on previous release 1.2.0(20180605.1)

#### Steps to Reproduce: ####
1. Go to (Subscription) -> Storage Accounts -> 'Copy Primary Key' for one account.
2. Select 'Use a storage account name and key' in Connect dialog -> 'Next'.

#### Expected Experience: ####
No default red border displays for required fields in 'Connect with Name and Key' dialog and 'Next' button is disabled.

#### Actual Experience: ####
Display the red border for required fields and 'Next' button is disabled.
![redborder](https://user-images.githubusercontent.com/34729022/41462777-845a0dcc-7083-11e8-9507-8e34f99637fb.png)

**Comment by MRayermannMSFT** [comment]
@craxal  merged a fix for this into his feature branch.
