### ISSUE TITLE
Is it possible for the `Max Transfer Rate` Setting (MTR) to be applied dynamically?

### ISSUE THREAD

**Issue by Brondahl** [microsoft/AzureStorageExplorer#3121]
**Is your feature request related to a problem? Please describe.**
For me, the optimal upload rate for large uploads varies depending on other usage of the network.
* Overnight I'd be happy for it to be fully saturating the uplink, in order to maximise capacity, and it damaging download usage (see #1099) is not a problem.
* During the majority of the day, I'm happy for it to run at, say, 80% to ensure that download usage is not impacted.
* During a conference call it'd be ideal if it were limited to say 10-20% of the uplink bandwidth.

The `Max Transfer Rate` (hereafter `MTR`) setting allows me to decide on the usage at the start of an upload, but it appears to set it once, at the start of the upload.

**Describe the solution you'd like**
If an upload is currently in progress, and the `MTR` is modified (or removed entirely!) then the in-progress upload should honour that new limit (or non-limit, as the case may be)

**Describe alternatives you've considered**
Currently I have to cancel and restart the uploads, which is OK, but a little annnoying.
The log files get noisier every time I restart, and it's more effort.
Would be great if it were completely trivial.

**Additional context**
For reference, I'm currently in the process of uploading ~100GB of data, over ~1,000 files, over a domestic 2Mbps upload (Woo, Coronavirus!). It'll take about a week to do at 1.5Mbps.

**Comment by Brondahl** [comment]
As I understand it, in this context, ASE is just a wrapper around AzCopy, which I think is a synchronous call, not an async one, so I suspect this may not be possible without very drastic changes to AzCopy?

But figured I'd ask in case someone knows a way around that makes it more plausible.

**Comment by MRayermannMSFT** [comment]
@Brondahl your initial thoughts are correct. AzCopy doesn't support changing it's bandwidth limits to a set number in the middle of a transfer. 😟 I'd recommend heading over to their repository and asking for that as a feature request.

In the meantime, maybe you could:

1. at night, set transfer limit to something high
2. start a transfer which should finish while you sleep
3. wake up, set transfer limit to something smaller
4. start ta transfer which should finish by night time

Repeat until all data uploaded.

You could also try scripting it, have the night time and day time transfers not start until the right time?

Just some ideas. :)

**Comment by Brondahl** [comment]
Thanks for the confirmation.

Yes, that's roughly what I'm doing, although I'm actually just using the relatively nice "Cancel" and "Re-upload" handling:

* Set everything to upload with no limit as I go to bed.
* Cancel it when I wake up (losing the last 5-20 minutes, but nbd)
* Set limit to something safe.
* Reupload everything and select the "Do not Reupload" option for duplicates.
* Cancel that when I'm about to go to bed.
* *Repeat*

**Comment by Brondahl** [comment]
Scripting it sounds like it would be a good call if I needed this long-term. Fortunately I should be done pretty soon, and won't need it again once the data is on Azure.

**Comment by JasonYeMSFT** [comment]
The support to dynamically change the max transfer rate for each transfer is added to our 1.25.0 release.
