### ISSUE TITLE
Query in  CosmosDB in Azure Storage Explorer always starts with "SELECT * FROM c"

### ISSUE THREAD

**Issue by fabio770** [microsoft/AzureStorageExplorer#3122]
Differently from the Azure Portal, when I want do query for a document in CosmosDB in Azure Storage Explorer, the query has always to start with "SELECT * FROM c". 

I was wondering if it would be possible to have more flexibility to change this. For example, sometimes I have to know the number of documents in the database that satisfy a certain condition and if I want to do "SELECT count(c) FROM c where c.Type = 2" I have to go to the Azure Portal in order to do that.

Thank you!

**Comment by southpolesteve** [comment]
The Cosmos team recently deprecated our integration with Azure Storage Explorer. [Here is the full deprecation notice from the 1.15.1 Storage Explorer release notes:](https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.15.1)

> The Azure Cosmos DB integration with Storage Explorer has been deprecated. Any existing functionality will not be removed for a minimum of one year from this release. Users should use the Azure Portal, the Azure Portal desktop app, or the standalone Cosmos Explorer instead – all of which contain many new features that aren’t currently supported in Storage Explorer. Additionally, the Azure Cosmos DB team has also open sourced the data explorer project and will be investing in their own desktop tooling at a later date. Please keep an eye on their repository for more information. 

Currently, we are not prioritizing new features or bug fixes for Cosmos in Azure Storage Explorer. If you the issue you are reporting also applies to the Azure Portal or https://cosmos.azure.com, please file an issue in [our open source Cosmos Explorer repo](https://github.com/Azure/cosmos-explorer)
