### ISSUE TITLE
Storage Explorer using a proxy fails to upload/download files from Azure Storage Account with error "x509: certificate signed by unknown authority"

### ISSUE THREAD

**Issue by bobsun0917** [microsoft/AzureStorageExplorer#3126]
**Storage Explorer Version**: 1.13.1
**Build**: 20200515.1
**Azcopy Version**:10.4.2
**Platform/OS**: Windows
**Architecture**: amd64
**Regression From**: Not a regression

**Issue Descriptions**: 
We're using a **proxy** to connect to azure storage account with azure storage explorer. We can successfully set up the connection using storage explorer and view the files in the container, but fail to upload/download files from container. 

Checking the logs in %USERPROFILE%\.azcopy, it shows following errors:

2020/06/17 08:00:00 ==> REQUEST/RESPONSE (Try=1/63.005ms, OpTime=63.005ms) -- REQUEST ERROR
HEAD https://blob-service-url
User-Agent: [Microsoft Azure Storage Explorer, 1.13.1, win32,  AzCopy/10.4.2 Azure-Storage/0.7 (go1.13; Windows_NT)]
ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/error.go:154
**HTTP request failed**

Head https://blob-service-url: **_x509: certificate signed by unknown authority_**

**More Info**:
We followed TSG https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&tabs=Windows%2C2004#error-self-signed-certificate-in-certificate-chain-and-similar-errors, but can't find any self-signed certificates. --ignore-certificate-errors flag doesn't work for us either. 

Please help us out. Thanks!

**Comment by adreed-msft** [comment]
Hi there! We recommend adding the certificate to your machine(s)' root certificate store as that's where our trusted authorities live in AzCopy. This should resolve your issue.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you continue to see this problem, please open a new issue. Thanks!
