### ISSUE TITLE
StorageExplorer does not acknowledge a moved Downloads folder when downloading a blob.

### ISSUE THREAD

**Issue by stevu236** [microsoft/AzureStorageExplorer#313]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Windows
**Architecture**: ia32

#### Steps to Reproduce: ####
1. In Windows Explorer, Right click your user Downloads folder.
2. Select the Location tab.
3. Click the "Move..." button on the dialog, and select a new location for your Downloads folder.
4. Once your Downloads folder has moved, Download a blob file in Storage Explorer. 

#### Expected Experience: ####
On startup, Storage Explorer should default to the new location of the Windows Downloads folder. 

#### Actual Experience: ####
Storage Explorer will open the Windows "Save as" dialog at the old location of the Downloads folder. 
For example, if the original location of your downloads folder was "C:\Users\Username\Downloads", but you then moved the folder to "D:\Downloads". On startup, Storage Explorer will use the original location of the Downloads folder, instead of the new location.

I would like to note that this bug only happens when you first start the app - after you select the correct folder to download the blob to in Storage Explorer, the Windows prompt will remember this location for the rest of the application session.

**Comment by brcrista** [comment]
@craxal I would call this a bug, albeit a common gotcha on Windows.  This can happen if an app is trying to construct the path itself like  `%USERPROFILE%\Downloads`.  The only reliable way to get the paths to special folders is to call [SHGetKnownFolderPath](https://docs.microsoft.com/en-us/windows/desktop/api/shlobj_core/nf-shlobj_core-shgetknownfolderpath).

**Comment by lenardg** [comment]
It also happens when exporting CSV from table storage. The Save dialog shows you a Downloads folder, but it is not the actual location if you moved the folder.

**Comment by craxal** [comment]
The best we can really do here is use the Electron API `app.getPath`. I checked the code, and we do something like `path.join(remote.app.getPath("home"), "Downloads");`. Obviously, we should do `app.getPath("downloads")`. I'm not sure if this calls the Windows API as mentioned by @brcrista, but like I say, that's about all we can do without writing any complicated native packages.
