### ISSUE TITLE
Blob container context menu Refresh item fails to refresh the view

### ISSUE THREAD

**Issue by InteXX** [microsoft/AzureStorageExplorer#3130]
**Storage Explorer Version**: 1.13.1
**Build Number**: 20200512.1
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  Unknown

## Bug Description ##
The Refresh menu item on the blob container context menu fails to refresh the view. However, clicking the 'More' ellipsis on the ToolBar and selecting Refresh does refresh the view.

## Steps to Reproduce ##
- Right-click on a blob container
- Left-click the Refresh context menu item
- Note that the view fails to refresh
- Left-click to select a blob container
- Left-click the 'More' ellipsis in the ToolBar
- Left-click the Refresh menu item
- Note that the view refreshes as expected

## Expected Experience ##
The view representing the blob objects should be refreshed

## Actual Experience ##
The view representing the blob objects is not refreshed

## Additional Context ##
No other context

**Comment by MRayermannMSFT** [comment]
@InteXX the refresh in the tree view is for refreshing that node. If you want to refresh the view on the right side, you should use the refresh button in the toolbar (as you discovered).

**Comment by InteXX** [comment]
Very good, thank you.
