### ISSUE TITLE
ADLS2, "Create Folder" not working, Proxy involved

### ISSUE THREAD

**Issue by KSoehner** [microsoft/AzureStorageExplorer#3132]
Connecting, downloading, uploading works, creating a folder does not. Connection to the net via Proxy. Error message:

{
  "name": "FetchError",
  "message": "request to https://mandalaewesteurope.dfs.core.windows.net/mandalae/EnBW%2FDressRehearsal01%2FNeuer%20Ordner?resource=directory&timeout=60 failed, reason: self signed certificate in certificate chain",
  "type": "system",
  "errno": "SELF_SIGNED_CERT_IN_CHAIN",
  "code": "SELF_SIGNED_CERT_IN_CHAIN",
  "stack": "FetchError: request to https://mandalaewesteurope.dfs.core.windows.net/mandalae/EnBW%2FDressRehearsal01%2FNeuer%20Ordner?resource=directory&timeout=60 failed, reason: self signed certificate in certificate chain\n    at ClientRequest.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1455:11)\n    at ClientRequest.emit (events.js:182:13)\n    at TLSSocket.socketErrorListener (_http_client.js:391:9)\n    at TLSSocket.emit (events.js:182:13)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"
}

**Comment by MRayermannMSFT** [comment]
@KSoehner what version of Storage Explorer are you using?

**Comment by KSoehner** [comment]
1.13.1

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MRayermannMSFT** [comment]
Thanks. Can you please:
- upgrade to the lastest version
- go through the steps in our troubleshooting guide to try and resolve this issue: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C1804#error-self-signed-certificate-in-certificate-chain-and-similar-errors

**Comment by MRayermannMSFT** [comment]
Closing due to lack of follow-up. @KSoehner if you're still having problems, please open a new issue.
