### ISSUE TITLE
write EPIPE

### ISSUE THREAD

**Issue by natalieorsi** [microsoft/AzureStorageExplorer#3137]
Tried to upload a zip file to a MS gov cloud blob via ASE, this is try 3. Error popup instructed me to report the following here:

```
{
  "name": "Error",
  "message": "write EPIPE",
  "stack": "Error: write EPIPE\n    at WriteWrap.afterWrite [as oncomplete] (net.js:788:14)",
  "errno": "EPIPE",
  "code": "EPIPE",
  "syscall": "write"
}
```

I upload zip files to this blob all the time, but today it's not working.

**Comment by MRayermannMSFT** [comment]
@natalieorsi what version of Storage Explorer are you using? At point in the upload process are you seeing this error?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response from original issue opener. Please open a new issue if you are continuing to have problems.
