### ISSUE TITLE
Set public access is not available for adlsgen2 blob containers

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#3138]
Although it is possible to, there is no option to set public access level for adls gen2 blob containers.

**Comment by MRayermannMSFT** [comment]
test

**Comment by MRayermannMSFT** [comment]
test

**Comment by MRayermannMSFT** [comment]
In about 30min a PR will be merged that fixes this. @v-xianya, when verifying this bug, please do a variety of exploratory testing around the set public access level and manage access policies features. I'm going to close this now so I can get offline. Thanks!

**Comment by v-xianya** [comment]
@MRayermannMSFT 
Got it. Verified this issue on build 20210129.3. Fixed. Also we will do a variety of exploratory testing around the set public access level and manage access policies features.
