### ISSUE TITLE
About folder statistics

### ISSUE THREAD

**Issue by 123Jun321** [microsoft/AzureStorageExplorer#3139]
Hi  Team, We are trying to get container usage of Storage Account using SDK, we foud when there are more blobs, it will spend more time to get all blobs of the container. But we found it just spend 1-2 seconds to calculate it with clicking folder statistics.

Could you tell me how you did this?

I know this may be over the scope, but it will be very appreciated if you give us some advice.

**Comment by MRayermannMSFT** [comment]
@123Jun321 we simply list all the blobs under the selected folders and blobs and add up their size. Does that answer your question?

**Comment by 123Jun321** [comment]
Hi  @MRayermannMSFT 

Thanks for your answer, you can close this case. Thanks  a lot!
