### ISSUE TITLE
I cant login on Microsoft Azure Storage Explorer

### ISSUE THREAD

**Issue by Basgar** [microsoft/AzureStorageExplorer#3140]
Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: a2399009-0c6f-4b24-87b3-d7e23c17d37a, Error: {
  "name": "Error",
  "message": "connect ETIMEDOUT 13.73.240.225:443",
  "__zone_symbol__error": {
    "originalStack": "Error: connect ETIMEDOUT 13.73.240.225:443\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at exceptionWithHostPort (internal/errors.js:345:14)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)",
    "zoneAwareStack": "Error: connect ETIMEDOUT 13.73.240.225:443\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at exceptionWithHostPort (internal/errors.js:345:14)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)"
  },
  "stack": "Error: connect ETIMEDOUT 13.73.240.225:443\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)",
  "originalStack": "Error: connect ETIMEDOUT 13.73.240.225:443\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at exceptionWithHostPort (internal/errors.js:345:14)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)",
  "zoneAwareStack": "Error: connect ETIMEDOUT 13.73.240.225:443\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at exceptionWithHostPort (internal/errors.js:345:14)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)",
  "__zone_symbol__stack": "Error: connect ETIMEDOUT 13.73.240.225:443\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at exceptionWithHostPort (internal/errors.js:345:14)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)",
  "__zone_symbol__name": "Error",
  "__zone_symbol__message": "connect ETIMEDOUT 13.73.240.225:443",
  "__zone_symbol__originalStack": "Error: connect ETIMEDOUT 13.73.240.225:443\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at exceptionWithHostPort (internal/errors.js:345:14)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)",
  "__zone_symbol__zoneAwareStack": "Error: connect ETIMEDOUT 13.73.240.225:443\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at exceptionWithHostPort (internal/errors.js:345:14)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)",
  "errno": "ETIMEDOUT",
  "code": "ETIMEDOUT",
  "syscall": "connect",
  "address": "13.73.240.225",
  "port": 443
}

**Comment by MRayermannMSFT** [comment]
@Basgar a couple questions:

- What version of Storage Explorer are you using?
- Are you behind a proxy? You can look at our troubleshooting guide for more info on how to setup your proxy settings: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C1804#proxy-issues

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response from original issue opener. Please open a new issue if you are continuing to have problems.
