### ISSUE TITLE
The Queues node can't expand under (Attached Containers) after attaching one emulator queue

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3141]
**Storage Explorer Version:** 1.14.0
**Build**: 20200624.3
**Branch**: rel/1.14.0
**Platform/OS**: Windows 10
**Emulator:** (5.10.0.0)
**Architecture:** x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Make sure Storage Emulator(5.10.0.0) is started.
2. Expand 'Local & Attached' -> 'Storage Accounts' -> '(Emulator - Default Ports)(Key)' -> 'Queues'.
3. Create a new queue -> Attach it via SAS.
4. Check the Queues node under (Attached Containers).

**Expect Experience:**
The Queues node works well.

**Actual Experience:**
The Queues node can't expand.
![image](https://user-images.githubusercontent.com/54055206/85520432-7f17a780-b635-11ea-83b4-fda85327ac2e.png)
![image](https://user-images.githubusercontent.com/54055206/85520440-82ab2e80-b635-11ea-9c6a-f8dd63c59805.png)

**More Info:**

1. Please see the record.
https://web.microsoftstream.com/video/20fba3ff-0400-a521-a87d-f1eab5f72474
2. This issue doesn't reproduce in Azurite (3.7.0).
3. On release 1.13.1: An error info occurs on connect dialog when creating a SAS for one emulator queue.
![image](https://user-images.githubusercontent.com/54055206/85520753-e897b600-b635-11ea-804b-1c6030973f01.png)

**Comment by MRayermannMSFT** [comment]
@v-limu , we're unable to repro this. Please reopen if you can still repro.

**Comment by v-limu** [comment]
Hi @MRayermannMSFT 

Verified this issue with **Emulator (5.10.0.0) and Azurite (3.7.0)** on build 20200630.1. This issue still reproduces.😢 

**More Info:** Miss account name in the queue SAS URI. 
![image](https://user-images.githubusercontent.com/54055206/86111755-b8e72300-baf9-11ea-8faa-e53ae6163f08.png)
