### ISSUE TITLE
Unable to access Files Shares: Network timeout error: connect ETIMEDOUT 

### ISSUE THREAD

**Issue by LuyandaMdanda** [microsoft/AzureStorageExplorer#3143]
**Storage Explorer Version**: 1.13.1
**Build Number**: 20200515.1
**Platform/OS**:  Windows 10
**Architecture**: ia32
**Regression From**:  Worked in the same version

## Bug Description ##
I am unable to access any of the File Shares folders in any of my Storage Accounts. When I click on a File Shares folder it attempts to load the child resources, then an error message appears.

Then I receive an error that states:
Unable to retrieve child resources.
Details:
Network timeout error: connect ETIMEDOUT <followed by an IP address>
(Excluding because I am not too sure how sensitive this information is)

## Steps to Reproduce ##
1. Select a Subscription
2. Select a Storage Account
3. Select a File Share within that Storage Account
--> Attempts to load child resources then errors

## Expected Experience ##
Access to folders and data within my File Share

## Actual Experience ##
Error message.
![image](https://user-images.githubusercontent.com/24789373/85539922-3b885380-b5cb-11ea-8fca-4c424a511e33.png)

**Comment by JasonYeMSFT** [comment]
Have you turned on any proxy?

**Comment by MRayermannMSFT** [comment]
Do you have any firewalls setup with your file shares? Are you able to access other resource types, likes blobs, queues, or tables?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response from original issue opener. Please open a new issue if you are continuing to have problems.
