### ISSUE TITLE
Obscure Storage Account Secrets in UX

### ISSUE THREAD

**Issue by sskone** [microsoft/AzureStorageExplorer#3144]
**Is your feature request related to a problem? Please describe.**
The Azure Storage Explorer UX exposes account keys, SAS, etc.. in the lower left corner of the screen. During screen sharing sessions, it is possible for secrets to be exposed. A user could simply expand or widen the left nav. 

**Describe the solution you'd like**
Add an option to obscure the secret values (e.g., secure string, ****, etc..)

**Describe alternatives you've considered**
Tried collapsing the properties section in the lower left of the UX, but there is still risk the section could accidently be expanded and the secret exposed.

**Comment by MRayermannMSFT** [comment]
Use 1.16 to investigate this issue.

**Comment by MRayermannMSFT** [comment]
<img width="338" alt="image" src="https://user-images.githubusercontent.com/21112697/93376504-8e5e5980-f80e-11ea-8a96-65d03cbd7820.png">

**Comment by MRayermannMSFT** [comment]
The following feature areas had secrets obscured:

- subscription storage accounts
- attached storage accounts
- attached containers
- cosmos db accounts
