### ISSUE TITLE
Unable to open BlobContainer

### ISSUE THREAD

**Issue by lgrobost** [microsoft/AzureStorageExplorer#3147]
Unable to retrieve child resources.

Details:
["RestError:﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:28e149f9-101e-0021-2a06-4b55a6000000\nTime:2020-06-25T15:35:16.8331024Z</Message><AuthenticationErrorDetail>Issuer validation failed. Issuer did not match.</AuthenticationErrorDetail></Error>"]

**Comment by MRayermannMSFT** [comment]
@lgrobost how are you connecting to your Azure Storage? Are you Attaching with Azure AD, or browsing resources under a subscription?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response from original issue opener. Please open a new issue if you are continuing to have problems.
