### ISSUE TITLE
The localized string 'Search by prefix (case sensitive)' shows incompletely in Japanese

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3150]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200627.2
**Branch**: master
**Language**: Japanese
**Platform/OS:** Windows 10/ macOS Catalina
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '日本語' -> Restart Storage Explorer.
3. Expand one storage account -> Blob Containers.
4. Open one blob container -> Observe the localized string in **search by prefix** box.

**Expect Experience:**
The string shows completely.
![image](https://user-images.githubusercontent.com/41351993/85943608-b8b51f00-b963-11ea-9a4c-acff5db2866d.png)

**Actual Experience:**
The string shows incompletely.
![image](https://user-images.githubusercontent.com/41351993/85943603-b4890180-b963-11ea-8a88-a41504c562b5.png)

**More Info:**
This issue doesn't reproduce on Linux.

**Comment by v-xianya** [comment]
Verified this issue on build 20200924.2.
1. Not reproduce on Windows.
2. Reproduce on Mac.

**Comment by JasonYeMSFT** [comment]
@v-xianya Could you share screenshots of the issue? I cannot reproduce it on Mac.

**Comment by v-xianya** [comment]
@JasonYeMSFT 
Verified this issue on build 20200925.2. Not reproduce.
