### ISSUE TITLE
There are untranslated strings in Rename Table dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3152]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200627.2
**Branch**: master
**Language**: All
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '日本語' -> Restart Storage Explorer.
3. Expand one storage account -> Tables.
4. Select one table then right click it -> Click the localized rename action '名前の変更...'.
5. Check the strings in Rename Table dialog.

**Expect Experience:**
All the strings are translated.

**Actual Experience:**' 
There are untranslated strings in Rename dialog.
![image](https://user-images.githubusercontent.com/41351993/85994196-0bf1a500-ba2a-11ea-9954-f666adb9ce8c.png)

**Comment by v-xianya** [comment]
This issue still reproduces on build 20210206.3.

**Comment by MRayermannMSFT** [comment]
This appears to be fixed on main.
