### ISSUE TITLE
Storage Explorer fails to detect an emulator running on another machine is an emulator, leading to errors

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#3153]
1. Start Storage Emulator on another machine
2. Connect Storage Explorer to that emulator
3. Do something where Storage Explorer has special behavior if the target of an operation is an emulator, like deleting blobs

Expected: special logic works and operation succeeds 
Actual: special logic fails and operation potentially fails

**Comment by MRayermannMSFT** [comment]
Example of this happening from: https://github.com/microsoft/AzureStorageExplorer/issues/2818#issuecomment-640617319

> @MRayermannMSFT I get same "UnexpectedQuit" error while deleting.

> ![image](https://user-images.githubusercontent.com/809278/84037697-93646f00-a9bc-11ea-945c-a29bf4aa4225.png)


> AzCopy command output:
`$env:AZCOPY_CRED_TYPE = "Anonymous";
./azcopy.exe remove "http://10.0.0.19:18888/devstoreaccount1/test/Sada-1.jpg?REDACTED" --recursive
$env:AZCOPY_CRED_TYPE = "";`

> I have installed Azurite inside VM on Ubuntu 18.04.4 OS on VirtualBox. Running it with following command:

> `$  azurite --silent --location ~/.azurite/ --debug ~/.azurite/debug.log --blobHost 0.0.0.0 --blobPort 18888 --queueHost 0.0.0.0 --queuePort 18889 -L`

> My host system in Windows 10 and running 'Microsoft Azure Storage Explorer' tool. The above screenshot is from same tool. The connection was successful and modified connection string is:
`DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://10.0.0.19:18888/devstoreaccount1;QueueEndpoint=http://10.0.0.19:18889/devstoreaccount1;`


> On click of details link in the link gives only this much:
![image](https://user-images.githubusercontent.com/809278/84038343-71b7b780-a9bd-11ea-9ad8-16e7c05ff815.png)


> Please help ....

**Comment by MRayermannMSFT** [comment]
@harshithjv , can you explain why you're running you emulator on a remote machine? We believe that is the root of your issue.

**Comment by MRayermannMSFT** [comment]
@harshithjv ?

**Comment by MRayermannMSFT** [comment]
Let's get a good cost of how much it'll take to fix this. Anything more than a day we should discuss.

**Comment by harshithjv** [comment]
@MRayermannMSFT 

Hey Rayermann,

I wasn't aware of this being moved to as a new issue until today. I had placed it on VM(thereby accessing through IP address like a remote resource) as I had installed dependencies for the project on Windows system. Also wanted to test if we could do this such that multiple developers can access this storage service on a LAN while developing and connect to actual storage on Azure for production code. Minimizing billing while developing.

**Comment by MRayermannMSFT** [comment]
I think we've made some good progress on this issue. We're doing more thorough and consistent checks if a connection looks like an emulator. If anyone is using this scenario and has a specific issue where it looks like Storage Explorer isn't doing something right when an emulator is remote vs local please open an issue specific to it.
