### ISSUE TITLE
When Storage Explorer is in dark mode the text color inside the Text Box to query in Azure Cosmos DB becomes white when mouse is over it

### ISSUE THREAD

**Issue by strykerin** [microsoft/AzureStorageExplorer#3155]
**Storage Explorer Version**: 1.14.0
**Build Number**: 20200624.3
**Platform/OS**:Windows 10

## Bug Description ##
When Storage Explorer is in dark mode, the text color inside the Text Box to query in Azure Cosmos DB becomes white when mouse is over it. 

When I query for a particular document in a collection there is a Text Box that starts with: "SELECT * FROM c" and then I write down the query. When I put the mouse over this text box in order to edit my query the text becomes white and unreadable. Here below is some pictures:

- My query:
![image](https://user-images.githubusercontent.com/19648581/86064592-e5d8fe80-ba43-11ea-8b54-bc69167a291e.png)

- When the mouse is over it:
![image](https://user-images.githubusercontent.com/19648581/86064639-01dca000-ba44-11ea-9909-40fc22a7cda0.png)

- When I select to edit the query:
![image](https://user-images.githubusercontent.com/19648581/86064663-128d1600-ba44-11ea-8977-c9d1dadf9af8.png)

Thank you!

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
