### ISSUE TITLE
Can open multiple Settings tabs

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3156]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200630.1
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture:** ia32/x64
**Regression From:** Previous release (1.13.1)

**Steps to reproduce:**

1. Restart Storage Explorer.
2. Click the Settings icon continuously -> Check the result.

**Expect Experience:**
Only one Settings tab is opened.

**Actual Experience:**
Multiple Settings tabs are opened.
![image](https://user-images.githubusercontent.com/41351993/86077129-05ad0880-babe-11ea-9fde-c05cf326b085.png)

**More Info:**
Record: https://msit.microsoftstream.com/video/91c6a3ff-0400-a521-41c4-f1eaba712ead

**Comment by MRayermannMSFT** [comment]
@v-xianya I can only repro this by clicking very fast on the settings button, and only the first time you attempt to open the settings panel. Therefore we're going to won't fix. If you're able to reproduce it another way, please ping me on teams. Thanks!

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT Ok, got it.
