### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by Geraint87** [microsoft/AzureStorageExplorer#3157]
**Storage Explorer Version**: 1.14 (also happened before I upgraded)
**Build Number**: 20200624.3
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  This working a few weeks ago. Not aware of an upgrade that happened to break it. 

## Bug Description ##
I am trying to load the local Storage Emulator but the connection times out with error message:
```
Unable to retrieve child resources.

Details:
["FetchError:request to http://127.0.0.1:10001/devstoreaccount1/?include=metadata&comp=list&timeout=30 failed, reason: connect ECONNREFUSED 127.0.0.1:10001"]
```

```
The requested action could not be completed.

Details:
["FetchError:request to http://127.0.0.1:10001/devstoreaccount1/?include=metadata&comp=list&timeout=30 failed, reason: connect ECONNREFUSED 127.0.0.1:10001"]
```

## Steps to Reproduce ##
1. Open Storage Explorer
2. Connect with Azure account (and I tried just connecting to local storage emulator)
3. Expand Storage Accounts > Emulator > Queues

## Expected Experience ##
My existing local queues should appear

## Actual Experience ##
Error messages (above) appear.

## Additional Context ##
I don't have a proxy set up on my local network, but it is on a company laptop, I have tried this while connected to and disconnected from the VPN and have tried when on my home wifi with proxy settings disabled.

**Comment by JasonYeMSFT** [comment]
The error is usually caused by local storage emulator not running on the port you specified (10001 in your example). Could you please verify if the emulator is running and you are running it at the correct port? The port for the emulator services will be printed on its startup in the console.

**Comment by Geraint87** [comment]
Thanks! 😅  I didn't realise Storage Emulator had stopped! Saying that in the error message would be better, and a way of starting the emulator from Storage Explorer too.
