### ISSUE TITLE
Cosmos DB results in Parse Error: Header overflow (HPE_HEADER_OVERFLOW)

### ISSUE THREAD

**Issue by jstawski** [microsoft/AzureStorageExplorer#3161]
**Storage Explorer Version**: 1.14.0
**Build Number**: 20200624.3
**Platform/OS**: macOS 10.15.4 (Catalina)
**Architecture**: x64
**Regression From**:  Yes

## Bug Description ##
Running very simple queries against `Cosmos DB results in Parse Error: Header overflow`

## Steps to Reproduce ##
Query a Cosmos Db Collection. Some queries work others don't.
This query is not working for me: `select * from c where c.EmailStatus = 'Invalid'`

## Expected Experience ##
It should return results

## Actual Experience ##
Returning the following error: (sorry I can't seem to copy the error)

![image](https://user-images.githubusercontent.com/873800/86155276-2ed79400-bad2-11ea-833b-3120effd0b3a.png)

## Additional Context ##
HPE_HEADER_OVERFLOW is in the error message

**Comment by mjgabriel** [comment]
Same issue as OP. 

Storage Explorer Version: 1.14.0
Build Number: 20200624.3
Platform/OS: Windows
Architecture: ia32

## Bug Description
Running very simple queries against Cosmos DB results in Parse Error: Header overflow

## Steps to Reproduce
Run a simple query against a container/collection. Some work, others, for some reason, do not.

**Failing Query:**
`SELECT * FROM c where c.ProcessStatus='Processed'`  

If I change the process status to one of the others we use the query runs as expected
`SELECT * FROM c where c.ProcessStatus='Failed'`

## Result in Storage Explorer
![image](https://user-images.githubusercontent.com/6546788/86293132-e6d67100-bba6-11ea-9a86-7b9d3c5c64c1.png)

**Comment by southpolesteve** [comment]
Unfortunately, this is a known issue with the Cosmos V1 JavaScript SDK which is used by Storage Explorer. It will exceed the header limits under certain query conditions. We fixed it in V3 SDK but we have not yet been able to switch Storage Explorer to the new SDK. You will need to use the Azure Portal or https://cosmos.azure.com/ as a workaround.

**Comment by mjgabriel** [comment]
How is it the past versions of Storage Explorer didn't toss this error? Curious.

**Comment by southpolesteve** [comment]
It's probably due to picking up new versions of Electron and Node. NodeJS decreased their max header size significantly a while back https://github.com/nodejs/node/issues/24731

**Comment by mjgabriel** [comment]
Thanks @southpolesteve for the extra info.

I've returned to an earlier version of the app (v 1.12.0) for the time being.

**Comment by ericsson007** [comment]
I have the same problem but as a workaround I added ' OFFSET 0 LIMIT 100' to the end of the query. You may have to set LIMIT to a smaller nr....

**Comment by pjbates** [comment]
Same issue on 1.15.0 
Adding OFFSET 0 LIMIT 100 to the query "fixes" it.

**Comment by southpolesteve** [comment]
The Cosmos team recently deprecated our integration with Azure Storage Explorer. [Here is the full deprecation notice from the 1.15.1 Storage Explorer release notes:](https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.15.1)

> The Azure Cosmos DB integration with Storage Explorer has been deprecated. Any existing functionality will not be removed for a minimum of one year from this release. Users should use the Azure Portal, the Azure Portal desktop app, or the standalone Cosmos Explorer instead – all of which contain many new features that aren’t currently supported in Storage Explorer. Additionally, the Azure Cosmos DB team has also open sourced the data explorer project and will be investing in their own desktop tooling at a later date. Please keep an eye on their repository for more information. 

Currently, we are not prioritizing new features or bug fixes for Cosmos in Azure Storage Explorer. If you the issue you are reporting also applies to the Azure Portal or https://cosmos.azure.com, please file an issue in [our open source Cosmos Explorer repo](https://github.com/Azure/cosmos-explorer)

**Comment by github5775** [comment]
FYI, updated the [Cosmos Graph Api "Studio" project](https://github.com/github5775/GremlinStudio) if it may be of benefit to others in this space.
