### ISSUE TITLE
auhenticationFailed : unable to retrieve child resources 

### ISSUE THREAD

**Issue by snowman907** [microsoft/AzureStorageExplorer#3163]
["RestError:﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:6efbdc78-601e-0081-4814-4f3158000000\nTime:2020-06-30T19:27:39.0331292Z</Message><AuthenticationErrorDetail>Signature not valid in the specified time frame: Start [Fri, 22 May 2020 18:45:17 GMT] - Expiry [Tue, 30 Jun 2020 18:45:00 GMT] - Current [Tue, 30 Jun 2020 19:27:39 GMT]</AuthenticationErrorDetail></Error>"]

**Comment by MRayermannMSFT** [comment]
@snowman907 how are you accessing your storage? Are you:

- signing in and browsing all resources underneath a subscription
- signing in and then attaching a specific resource via attach with Azure AD

**Comment by JasonYeMSFT** [comment]
@snowman907 I just noticed that in the error message, it points out that your SAS has expired since the "Current" time is after the "Expiry" time.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response from original issue opener. Please open a new issue if you are continuing to have problems.
