### ISSUE TITLE
The value of 'Access Tier Last Modified' doesn't display after changing access tier for one blob

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3165]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200701.3
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture:** ia32/x64
**Regression From:** Not a regression 

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Expand one GPV2 or Blob storage account -> Blob Containers.
3. Create a blob container -> Upload a blob -> Update its access tier.
4. Check whether the 'Access Tier Last Modified' value displays or not.

**Expect Experience:**
The value of  'Access Tier Last Modified' displays well.

**Actual Experience:**
The value of  'Access Tier Last Modified' doesn't display.

**Comment by v-xianya** [comment]
Verified this issue on build 20200831.3.
1. This issue doesn't reproduce for blobs under regular GPV2 and Blob storage accounts.
2. This issue still reproduces for blobs under ADLS Gen2 storage accounts.

**Comment by MRayermannMSFT** [comment]
@v-xianya please reverify this bug. I can no longer repro it.

**Comment by v-xianya** [comment]
@MRayermannMSFT Verified this issue on build 20201009.1. Not reproduce.

**Comment by MRayermannMSFT** [comment]
Fixed when I changed "changed access tier" to refresh the current view instead of doing a manual insert.
