### ISSUE TITLE
The value of 'Access Tier Last Modified' disappears after acquiring lease for one blob

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3166]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200701.3
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture:** ia32/x64
**Regression From:** Not a regression 

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Expand one GPV2 or Blob storage account -> Blob Containers.
3. Create a blob container -> Upload a blob -> Update its access tier.
4. Refresh the editor to make sure the value of 'Access Tier Last Modified' displays.
5. Acquire lease for the blob -> Check the Value of 'Access Tier Last Modified'.

**Expect Experience:**
The value of 'Access Tier Last Modified' displays well.

**Actual Experience:**
The value of 'Access Tier Last Modified' disappears.

**Comment by v-xianya** [comment]
Verified this issue on build 20201009.1. Fixed.

**Comment by MRayermannMSFT** [comment]
Fixed when I changed "acquire lease" to refresh the current view instead of doing a manual insert.
