### ISSUE TITLE
Opening 'File/New Window' does not show 'Local & Attached' Storage Accounts visible in first one.

### ISSUE THREAD

**Issue by jdobr** [microsoft/AzureStorageExplorer#3168]
**Storage Explorer Version**: 1.14
**Build Number**: 20200624.3
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**: Not tested on previous versions

## Bug Description ##
Opening 'File/New Window' does not show 'Local & Attached' Storage Accounts visible in first window.

## Steps to Reproduce ##
Initial window of MASE Local&Attached -> right click on Storage Accounts -> add some storage account by key. See it in the list.
File/New Window will not show this added storage account.
Only visible 
(Attached Containers)
(Emulator - Default Ports)

## Expected Experience ##
New window should show me attached storage accounts as first window is showing.

## Actual Experience ##
First window
![first_window](https://user-images.githubusercontent.com/61420001/86251513-4128ff00-bbb2-11ea-9fae-bf2253badc56.png)

File/New window
![second_window](https://user-images.githubusercontent.com/61420001/86251512-40906880-bbb2-11ea-9073-ea9763599a77.png)

## Additional Context ##
None

**Comment by MRayermannMSFT** [comment]
Related to https://github.com/microsoft/AzureStorageExplorer/issues/241

**Comment by MRayermannMSFT** [comment]
Related to https://github.com/microsoft/AzureStorageExplorer/issues/723

**Comment by MRayermannMSFT** [comment]
Also @jdobr for our curiosity, can you let us know how/why you're using the "new window" feature? Thanks!

**Comment by jdobr** [comment]
I wanted to use it to copy/paste couple of separate folders from one storage account to another storage account and not to have to jump between source target so much. Because when I get back to source storage account after first paste in target, I get back to container level each time.

**Comment by MRayermannMSFT** [comment]
Thanks!
