### ISSUE TITLE
Unable to load containers in Azure Storage Explorer

### ISSUE THREAD

**Issue by FelixMerlin** [microsoft/AzureStorageExplorer#3170]
Version: 1.14.0
AzCopy Version: 10.4.2

Platform: Windows
Architecture: ia32 
Build Number: 20200624.3 
Commit: b41cec93f 
Support ID: d20220bb-1f3d-f120-8020-242085690395 

## Bug Description ##
Unable to retrieve child resources.  Details: ["FetchError:request to https://xxxxxxx.blob.core.windows.net/?include=metadata&comp=list failed, reason: unable to get local issuer certificate"]

Read the documentation, https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#error-self-signed-certificate-in-certificate-chain-and-similar-errors. 

Followed the steps, but still I am getting the same exception.

**Comment by MRayermannMSFT** [comment]
@FelixMerlin what so far have you tried from the trouble shooting steps?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response from original issue opener. Please open a new issue if you are continuing to have problems.
