### ISSUE TITLE
Not able to access container

### ISSUE THREAD

**Issue by pradeepthampi** [microsoft/AzureStorageExplorer#3171]
Unable to retrieve child resources.

Details:
getaddrinfo ENOTFOUND bck0207.file.core.windows.net

**Comment by MRayermannMSFT** [comment]
@pradeepthampi do you have a storage firewall or anything like that on the file service of your storage account? Are you able to use other desktop tools to access your file shares?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response from original issue opener. Please open a new issue if you are continuing to have problems.
