### ISSUE TITLE
No way to add CosmosDB emulator account to Quick Access

### ISSUE THREAD

**Issue by abatishchev** [microsoft/AzureStorageExplorer#3172]
**Is your feature request related to a problem? Please describe.**

I can right click on Storage emulator account to add it to Quick Access:

![image](https://user-images.githubusercontent.com/351644/86293182-f9e94100-bba6-11ea-9caa-1235a72219dc.png)

However I cannot do that for CosmosDB emulator account:

![image](https://user-images.githubusercontent.com/351644/86293230-14231f00-bba7-11ea-8770-ace6caa753e3.png)

**Describe the solution you'd like**

Add contest menu "Add to Quick Access" at `Cosmos DB Accounts (Preview) -> localhost:8081`

**Describe alternatives you've considered**

I can add individual database but not an account as the whole.

**Additional context**

ASE version 1.14.0

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
