### ISSUE TITLE
Provide Option To Disable Checking For Updates

### ISSUE THREAD

**Issue by mjgabriel** [microsoft/AzureStorageExplorer#3174]
**Is your feature request related to a problem? Please describe.**
Currently I am using an older version of Storage Explorer due to [issue 3161](https://github.com/microsoft/AzureStorageExplorer/issues/3161). 

**Describe the solution you'd like**
I would like to disable checking for updates so I don't have to dismiss the update notification whenever I use Storage Explorer.

**Describe alternatives you've considered**
We'll use Azure Portal as well, but prefer the app.

**Additional context**
Storage Explorer is used quite regularly during development and frequently in efforts to track down issues/problems in production.

Thank you

**Comment by MRayermannMSFT** [comment]
Hey @mjgabriel. This isn't something we would add to Storage Explorer. It is important that we encourage users to stay up-to-date. Not only do newer versions of Storage Explorer provide new features, they often contain security fixes. We understand you not wanting to update in this case b/c of issue 3161, and we'll do our best to get the CosmosDB folks to address that issue.

**Comment by mjgabriel** [comment]
Could you reconsider having it only pop-up once at app start-up and not repeatedly pop-up while the app is open?

Thank you :)

**Comment by Ty89** [comment]
I second motion this
