### ISSUE TITLE
The azure account was added via the deleted environment still shows well on the account panel

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3175]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200702.2
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open connect dialog -> Select 'Add New Environment' -> Next.
3. Input the environment a name and arm endpoint (https://management.azure.com) -> Click 'Next'.
4. Enter the credentials for one azure account.
5. Delete the environment then check the ACCOUNT MANAGEMENT panel. 

**Expect Experience:**
The account was added via the deleted environment no longer be visible on the account panel.

**Actual Experience:**
The account was added via the deleted environment still shows well on the account panel.

**Comment by v-xianya** [comment]
Verified this issue on build 20200720.3. Reproduce. So we re-open it.

**Comment by JasonYeMSFT** [comment]
We have merged the fix back to master. This should not reproduce anymore.

**Comment by v-limu** [comment]
Verified this issue on build 20200723.3. Fixed. So close it.
