### ISSUE TITLE
The QA blob container shows as broken with associated account removed

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3176]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200702.10
**Branch**: master
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture**: ia32/x64
**Regression From:** Previous release(1.12.0)

**Steps to reproduce:**

1. Create a storage account -> Launch Storage Explorer.
2. Create the four new services under the storage account. **(Do not add any RBAC permissions)**
3. Add the storage account and the four services to Quick Access.
4. Remove the account associated with the storage account. 
5. Check the status of the items under Quick Access.

**Expect Experience:**
The blob container shows well.
![image](https://user-images.githubusercontent.com/54055206/86439355-04d4da80-bd3b-11ea-9211-80d2aee12fcc.png)

**Actual Experience**
The blob container shows as broken.
![image](https://user-images.githubusercontent.com/54055206/86437951-2c767380-bd38-11ea-9483-9c8f31b7944d.png)

**More Info:**

1. The storage account shows as broken.
2. The file share / table / queue shows well.

**Comment by MRayermannMSFT** [comment]
By design/this change was intentional. We intend to bring this behavior to other services someday as well. If the account is removed, then Storage Explorer shouldn't be able to access the thing anymore.
