### ISSUE TITLE
Microsoft Azure Storage Explorer doesn't see any documents in container

### ISSUE THREAD

**Issue by Marusyk** [microsoft/AzureStorageExplorer#3178]
<img width="270" alt="Screenshot_1" src="https://user-images.githubusercontent.com/9221694/86500151-e0f3b200-bd97-11ea-8fb8-1d69e698ec81.png">

**Platform/OS**: Windows 10
**Architecture**: x64

## Bug Description ##

Storage Explorer doesn't see any documents in any containers

<img width="542" alt="Screenshot_2" src="https://user-images.githubusercontent.com/9221694/86500193-1ef0d600-bd98-11ea-8da6-fd72169afc19.png">

On portal
<img width="274" alt="Screenshot_2" src="https://user-images.githubusercontent.com/9221694/84502974-02460e80-acc2-11ea-87a6-cba8508160be.png">

## Steps to Reproduce ##
1. Open Explorer
2. Select CosmosDb
3. Select database
4. Click on Documents

## Expected Experience ##
Display data like in the portal

## Actual Experience ##
No data in containers

**Comment by Marusyk** [comment]
I found that it doesn't show any documents when I don't have Discriminator for data. In EF:

`builder.HasNoDiscriminator`

**Comment by Marusyk** [comment]
Are there any plans to fix that?

**Comment by Marusyk** [comment]
Hi @southpolesteve are there any plans to fix that?

**Comment by southpolesteve** [comment]
The Cosmos team recently deprecated our integration with Azure Storage Explorer. [Here is the full deprecation notice from the 1.15.1 Storage Explorer release notes:](https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.15.1)

> The Azure Cosmos DB integration with Storage Explorer has been deprecated. Any existing functionality will not be removed for a minimum of one year from this release. Users should use the Azure Portal, the Azure Portal desktop app, or the standalone Cosmos Explorer instead – all of which contain many new features that aren’t currently supported in Storage Explorer. Additionally, the Azure Cosmos DB team has also open sourced the data explorer project and will be investing in their own desktop tooling at a later date. Please keep an eye on their repository for more information. 

Currently, we are not prioritizing new features or bug fixes for Cosmos in Azure Storage Explorer. If you the issue you are reporting also applies to the Azure Portal or https://cosmos.azure.com, please file an issue in [our open source Cosmos Explorer repo](https://github.com/Azure/cosmos-explorer)
