### ISSUE TITLE
Succeed to upload folders in the 'Upload Files' dialog

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3180]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200704.2
**Branch**: master
**Platform/OS:** Linux Ubuntu 18.04
**Architecture**: x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer -> Expand one storage account.
2. Open one blob container -> Click 'Upload' -> Click 'Upload Files…'.
3. Select one folder from 'Recent' to upload.
4. Check the result.

**Expect Experience:**
Can't select the folders.

**Actual Experience:**
The folder can be selected and upload successfully.

**More Info:**

1. This issue also reproduces for one file share.
2. The record: https://web.microsoftstream.com/video/3a5da1ff-0400-a521-b5c0-f1eabf625098

**Comment by MRayermannMSFT** [comment]
Going to won't fix this. Super edge case, bug is either in OS or electron itself (I'd say most likely OS). If customer raises this issue then we can open a bug in Electron.
