### ISSUE TITLE
The 'Visibility timeout' text box shows red border when typing one invalid character in TTL text box

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3187]
**Storage Explorer Version:** 1.14.1
**Build**: 20200707.4
**Branch**: hotfix/1.14.1
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Expand one storage account -> Queues.
3. Create a queue -> Click 'Add Message'.
4. Type on invalid character to 'Time to Live' text box -> Check the result.

**Expect Experience:**
The Visibility timeout text box border shows normal.

**Actual Experience:**
The Visibility timeout text box shows red border.
![image](https://user-images.githubusercontent.com/41351993/86762361-2d314180-c079-11ea-8c7f-36787abf3b90.png)

**Comment by MRayermannMSFT** [comment]
They are both invalid. We just show only 1 error at a time.
