### ISSUE TITLE
The attached account doesn't auto expand under Custom Connections

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#319]
Storage Explorer Version: 1.2.0
Platform/OS Version: Windows 10/Linux Ubuntu 16.04/MacOS High Sierra
Architecture: ia32/x64
Build Number: 20180614.2
Commit: 5dbf0913
Regression From: Not a regression

#### Steps to Reproduce: ####
1. Go to (Subscription) -> Storage Accounts.
2. Right click one blob account -> Select 'Get Shared Access Signature...' -> Copy the generated connection string to 'Attach with Connection String' dialog -> 'Connect'.
3. Check whether the attached account auto expands or not.

#### Expected Experience: ####
The attached account auto expands under Custom Connections.

#### Actual Experience: ####
The attached account doesn't auto expand under Custom Connections.

**Comment by burbuzug** [comment]
[CYBERCRiME-05-12-18.txt](https://github.com/Microsoft/AzureStorageExplorer/files/2130385/CYBERCRiME-05-12-18.txt)
