### ISSUE TITLE
ECONNREFUSED FetchError 

### ISSUE THREAD

**Issue by allyson-dev** [microsoft/AzureStorageExplorer#3190]
**Storage Explorer Version**: v1.14.0
**Build Number**: 20200624.3  
**Platform/OS**:  macOS Catalina V 10.15.5
**Architecture**:  x64 
**Regression From**:   Not sure - did not attempt in a previous version
## Bug Description ##
When attempting to upload more than one subsequent file through storage explorer - The app freezes and then the Fetch Error - EconnRefused is presented. I am also now unable to access the storage account via the azure website portal saying that my endpoint is not accessible.

## Steps to Reproduce ##
1. Log into Azure AD through Azure Storage explorer to connect with Storage Account - the issue persists with either using AD or or storage account keys
2. Upload one folder from local drive using the upload folder option
3. Once successful add another file following the above procedure. 
4. This will stall and then not connect correctly and the error will result. "Unable to retrieve Child Resources" 
5. Go to azure portal website and click into the container for which you uploaded the file and you'll now be unable to see the container or access it.

## Expected Experience ##
Expected to be able to upload multiple files through azure storage, copy and manipulate storage folders into different directories. As well as see them in the portal website. 

## Actual Experience ##
Storage explorer is able to upload one folder or file and then any subsequent attempt is met with the error. Furthermore you are locked out of the azure storage account on azure's portal website. Effectively locking you out of the storage account. 

## Additional Context ##
I have checked the firewall issue and contacted Microsoft about this. They do not know what may be causing it. Thought I'd report the bug to see if it's a mac issue related. The issue seemed to be fixed if I simply deleted the app and restarted my computer - getting rid of any cpu cookies. But I've restarted my computer three times now and the issue persists with Storage Explorer and I'm unable to access the account via the portal website.

**Comment by JasonYeMSFT** [comment]
@allyson-dev Upload in Storage Explorer are done independently and it is very unlikely that our logic between uploads is causing this issue. If this issue happens to occur after a successful upload, I would guess it is because something is configured to react to data written events in the storage account, which causes it to be locked. So to help us investigate, could you please try the following:
- See if this issue occurs on any other storage account
- Check if there is any trigger reacting to data written events.

**Comment by MRayermannMSFT** [comment]
Closed due to lack of response. If you are still having issues please open a new issue.
