### ISSUE TITLE
No 'Create Snapshot' action shows on one regular blob container's toolbar

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3192]
**Storage Explorer Version:** 1.14.1
**Build**: 20200707.18
**Branch**: hotfix/1.14.1
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture**: ia32/x64
**Regression From:** Previous release(1.13.1)

**Steps to reproduce:**

1. Expand one Non-ADLS Gen2 storage account -> Blob Containers.
2. Select one blob container then open it.
3. Check whether the action 'Create Snapshot' shows or not on the toolbar.

**Expect Experience:**
The action 'Create Snapshot' shows on the toolbar.
![image](https://user-images.githubusercontent.com/41351993/86899397-87dfa180-c13c-11ea-829c-dc3f38c2f159.png)

**Actual Experience:**
No action 'Create Snapshot' shows on the toolbar.
![image](https://user-images.githubusercontent.com/41351993/86899377-844c1a80-c13c-11ea-91f5-c5cc88be9cd0.png)

**Comment by JasonYeMSFT** [comment]
This is by design. It is recommended to use blob version feature in the future and we have decided to remove this button and let only people use it from the context menu.

**Comment by v-xianya** [comment]
Hi @JasonYeMSFT 

Thanks for your updates!
Do we need to apply this for ADLS Gen2 blob containers?
The screenshot for one ADLS Gen2 blob container toolbar.
![image](https://user-images.githubusercontent.com/41351993/86992575-5c0ffa80-c1d4-11ea-81c4-6af8ff7922ee.png)

**Comment by JasonYeMSFT** [comment]
@v-xianya, not for ADLS Gen2 because blob versioning is not supported for ADLS Gen2 yet.
