### ISSUE TITLE
seeing this error while using Azure Storage explorer

### ISSUE THREAD

**Issue by vpernankil** [microsoft/AzureStorageExplorer#3195]
Unable to retrieve child resources.

Details:
["FetchError:request to http://127.0.0.1:10000/devstoreaccount1/?include=metadata&comp=list failed, reason: connect ECONNREFUSED 127.0.0.1:10000"]

**Comment by vpernankil** [comment]
2020/07/08 10:30:16 AzcopyVersion  10.4.2
2020/07/08 10:30:16 OS-Environment  windows
2020/07/08 10:30:16 OS-Architecture  amd64
2020/07/08 10:30:16 Log times are in UTC. Local time is 8 Jul 2020 16:00:16
2020/07/08 10:30:16 Job-Command copy D:\Simplilear_Trainings\Az-104\important_links.txt https://vivnewstorageaccount.blob.core.windows.net/filetest/important_links.txt?se=2020-08-07t10%3A30%3A16z&sig=-REDACTED-&sp=rwl&sr=c&sv=2018-03-28 --output-type=json --cancel-from-stdin --overwrite=prompt --from-to=LocalBlob --blob-type BlockBlob --follow-symlinks --put-md5 --follow-symlinks --recursive 
2020/07/08 10:30:16 Number of CPUs: 4
2020/07/08 10:30:16 Max file buffer RAM 2.000 GB
2020/07/08 10:30:16 Max concurrent network operations: 32 (Based on number of CPUs. Set AZCOPY_CONCURRENCY_VALUE environment variable to override)
2020/07/08 10:30:16 Check CPU usage when dynamically tuning concurrency: true (Based on hard-coded default. Set AZCOPY_TUNE_TO_CPU environment variable to true or false override)
2020/07/08 10:30:16 Max concurrent transfer initiation routines: 64 (Based on hard-coded default. Set AZCOPY_CONCURRENT_FILES environment variable to override)
2020/07/08 10:30:16 Max enumeration routines: 64 (Based on hard-coded default. Set AZCOPY_CONCURRENT_SCAN environment variable to override)
2020/07/08 10:30:16 Max open files when downloading: 2147483171 (auto-computed)
2020/07/08 10:30:16 Any empty folders will not be processed, because source and/or destination doesn't have full folder support
2020/07/08 10:30:16 JobID=ce1aef7d-3de0-1440-69c2-ad2ee25c8dca, credential type: Anonymous
2020/07/08 10:30:16 scheduling JobID=ce1aef7d-3de0-1440-69c2-ad2ee25c8dca, Part#=0, Transfer#=0, priority=0
2020/07/08 10:30:16 Final job part has been scheduled
2020/07/08 10:30:16 Final job part has been created
2020/07/08 10:30:16 PERF: primary performance constraint is Unknown. States: R:  0, D:  0, W:  0, F:  0, B:  0, E:  0, T:  0, GRs: 32
2020/07/08 10:30:16 INFO: [P#0-T#0] has worker 25 which is processing TRANSFER
2020/07/08 10:30:16 INFO: [P#0-T#0] Starting transfer: Source "%5C%5C?\\D:\\Simplilear_Trainings\\Az-104\\important_links.txt" Destination "https://vivnewstorageaccount.blob.core.windows.net/filetest/important_links.txt?se=2020-08-07t10%3A30%3A16z&sig=-REDACTED-&sp=rwl&sr=c&sv=2018-03-28". Specified chunk size 8388608
2020/07/08 10:30:17 ==> REQUEST/RESPONSE (Try=1/209.8601ms, OpTime=953.7872ms) -- RESPONSE SUCCESSFULLY RECEIVED
   HEAD https://vivnewstorageaccount.blob.core.windows.net/filetest/important_links.txt?se=2020-08-07t10%3A30%3A16z&sig=-REDACTED-&sp=rwl&sr=c&sv=2018-03-28&timeout=901
   X-Ms-Request-Id: [520466fb-e01c-0077-0612-552709000000]

2020/07/08 10:30:18 ==> REQUEST/RESPONSE (Try=1/206.5128ms, OpTime=207.5109ms) -- RESPONSE STATUS CODE ERROR
   PUT https://vivnewstorageaccount.blob.core.windows.net/filetest/important_links.txt?se=2020-08-07t10%3A30%3A16z&sig=-REDACTED-&sp=rwl&sr=c&sv=2018-03-28&timeout=901
   Content-Length: [755]
   User-Agent: [Microsoft Azure Storage Explorer, 1.14.0, win32,  AzCopy/10.4.2 Azure-Storage/0.7 (go1.13; Windows_NT)]
   X-Ms-Blob-Cache-Control: []
   X-Ms-Blob-Content-Disposition: []
   X-Ms-Blob-Content-Encoding: []
   X-Ms-Blob-Content-Language: []
   X-Ms-Blob-Content-Md5: [Mmnl8j3+NJBkzo/3OMnMqA==]
   X-Ms-Blob-Content-Type: [text/plain; charset=utf-8]
   X-Ms-Blob-Type: [BlockBlob]
   X-Ms-Client-Request-Id: [b206bd19-89bf-4e9f-572e-97cd76ac26cd]
   X-Ms-Version: [2019-02-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 400 Block blobs are not supported.
   Content-Length: [220]
   Content-Type: [application/xml]
   Date: [Wed, 08 Jul 2020 10:30:12 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [b206bd19-89bf-4e9f-572e-97cd76ac26cd]
   X-Ms-Error-Code: [BlobTypeNotSupported]
   X-Ms-Request-Id: [5204678b-e01c-0077-1612-552709000000]
   X-Ms-Version: [2019-02-02]
Response Details: ﻿<?xml version="1.0" encoding="utf-8"?> <Error><Code>BlobTypeNotSupported</Code><Message>Block blobs are not supported. </Message>

2020/07/08 10:30:18 ERR: [P#0-T#0] UPLOADFAILED: %5C%5C?\D:\Simplilear_Trainings\Az-104\important_links.txt : 400 : 400 Block blobs are not supported.. When Uploading blob. X-Ms-Request-Id: 5204678b-e01c-0077-1612-552709000000

   Dst: https://vivnewstorageaccount.blob.core.windows.net/filetest/important_links.txt?se=2020-08-07t10%3A30%3A16z&sig=-REDACTED-&sp=rwl&sr=c&sv=2018-03-28
2020/07/08 10:30:18 ==> REQUEST/RESPONSE (Try=1/207.3875ms, OpTime=207.3875ms) -- RESPONSE STATUS CODE ERROR
   GET https://vivnewstorageaccount.blob.core.windows.net/filetest/important_links.txt?blocklisttype=all&comp=blocklist&se=2020-08-07t10%3A30%3A16z&sig=-REDACTED-&sp=rwl&sr=c&sv=2018-03-28&timeout=31
   User-Agent: [Microsoft Azure Storage Explorer, 1.14.0, win32,  AzCopy/10.4.2 Azure-Storage/0.7 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [a5253b69-d1ac-4d8c-651a-959346759a6c]
   X-Ms-Version: [2018-11-09]
   --------------------------------------------------------------------------------
   RESPONSE Status: 400 Block blobs are not supported.
   Content-Length: [220]
   Content-Type: [application/xml]
   Date: [Wed, 08 Jul 2020 10:30:13 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [BlobTypeNotSupported]
   X-Ms-Request-Id: [520467e8-e01c-0077-7312-552709000000]
   X-Ms-Version: [2018-11-09]
Response Details: ﻿<?xml version="1.0" encoding="utf-8"?> <Error><Code>BlobTypeNotSupported</Code><Message>Block blobs are not supported. </Message>

2020/07/08 10:30:18 JobID=ce1aef7d-3de0-1440-69c2-ad2ee25c8dca, Part#=0, TransfersDone=1 of 1
2020/07/08 10:30:18 all parts of entire Job ce1aef7d-3de0-1440-69c2-ad2ee25c8dca successfully completed, cancelled or paused
2020/07/08 10:30:18 PERF: primary performance constraint is Unknown. States: R:  0, D:  0, W:  0, F:  0, B:  0, E:  0, T:  0, GRs: 32

**Comment by JasonYeMSFT** [comment]
It seems you are having two different issues.
Issue 1. Could you verify that only the emulator is running at port 10000. This type of error sometimes show when the port is occupied.
Issue 2. The log tells us that you are trying to upload a file to the blob container as a Block Blob but the storage account doesn't support this type of blob. Could you find out what type of storage account the "vivnewstorageaccount" is? You can find it under the properties panel "Account Kind" field.
For example,
<img width="600" alt="image" src="https://user-images.githubusercontent.com/39359541/88317370-09533a00-ccce-11ea-952f-2b705f089e32.png">

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response from original issue opener. Please open a new issue if you are continuing to have problems.
