### ISSUE TITLE
Error while uploading files

### ISSUE THREAD

**Issue by dpetrek** [microsoft/AzureStorageExplorer#3197]
When uploading 654MB file to Azure Cool Blob tier, there is an error which youll find attached.
Smaller files pass without problem.
Tried uploading as block blob, page blob and append blob.

[5e89b287-df99-aa4d-47c2-0b12da4c097c.log](https://github.com/microsoft/AzureStorageExplorer/files/4890431/5e89b287-df99-aa4d-47c2-0b12da4c097c.log)

Please advise.

**Comment by MRayermannMSFT** [comment]
@dpetrek are you still seeing this issue? Are you getting this error with other files as well?

**Comment by dpetrek** [comment]
Its OK now, thanks.

**Comment by MRayermannMSFT** [comment]
Ok.
