### ISSUE TITLE
Can we make Refresh button usable without going via "... More" button please?

### ISSUE THREAD

**Issue by ppanyukov** [microsoft/AzureStorageExplorer#3199]
**Is your feature request related to a problem? Please describe.**
Refresh button is the one I (and maybe many others) use a lot.
Since it is on the far right of the toolbar, it is hidden behind "..." for me.
This makes it super super inconvenient to use!
See screenshots

<img width="881" alt="image" src="https://user-images.githubusercontent.com/300031/86952458-edd32580-c14a-11ea-8737-f9ad4c54baf8.png">

<img width="921" alt="image" src="https://user-images.githubusercontent.com/300031/86953262-16a7ea80-c14c-11ea-8bd8-b369634a502a.png">

**Describe the solution you'd like**
Make Refresh button usable without having to press "...".
Could be achieved with the following:
- move to the utmost left so it is first button
- option to make buttons smaller
- use space more efficiently -- there is tons of space left and yet there is still "..."
- add ability to customise toolbar
- provide and *document* keyboard shortcut for refresh. I *think* it is CMD+R on a Mac, but I can't see this anywhere.

**Describe alternatives you've considered**
- Zoom out. Kinda makes the button work but then I can't see anything else -- it's too tiny! It seems to soom in/out with massive increments (25%? no idea, doesn't say anywhere).

**Additional context**
- none

**Comment by JasonYeMSFT** [comment]
Unfortunately it is a consequence of our current Toolbar design. For now, a more convenient way to refresh is to use the keyboard shortcut Ctrl+R or Cmd+R.

**Comment by MRayermannMSFT** [comment]
@ppanyukov just curious, what's the size of your screen? Both the physical size and what resolution are you running at.

**Comment by ppanyukov-poq** [comment]
> @ppanyukov just curious, what's the size of your screen? Both the physical size and what resolution are you running at.

I'm on min-2015 MacBook Pro with default resolution. It says it looks like 1440x900. The fact that I have the dock on the left probably doesn't help the toolbar issue :) 

Oh well, I will use CMD+R to refresh. It *would* be nice to have this shortcut mentioned somewhere in the UI tho.

![image](https://user-images.githubusercontent.com/60924263/87463172-ed360580-c608-11ea-8c58-147d6fee9267.png)

**Comment by ppanyukov** [comment]
> @ppanyukov just curious, what's the size of your screen? Both the physical size and what resolution are you running at.

I'm on mid-2015 MacBook Pro with default resolution. It says it looks like 1440x900. 

The fact that I have the dock on the left probably doesn't help the toolbar issue :)

Oh well, I will use CMD+R to refresh. It would be nice to have this shortcut mentioned somewhere in the UI tho.

<img width="661" alt="image" src="https://user-images.githubusercontent.com/300031/87463494-65043000-c609-11ea-9007-888fad9c2992.png">

**Comment by JasonYeMSFT** [comment]
@ppanyukov I am experimenting with a denser toolbar design such that we may be able to fit more items in the toolbar. Here is a mock up (Please ignore the Test Error button)

![image](https://user-images.githubusercontent.com/39359541/87581572-05039d00-c68e-11ea-9d46-40e1f583fe6b.png)

It would be great if you can provide feedback about which part do you like it or not like it.

**Comment by ppanyukov** [comment]
@JasonYeMSFT I think this looks very nice!

**Comment by MRayermannMSFT** [comment]
@ppanyukov in 1.20 we shipped a "small button" feature for the toolbar in data explorers. These small buttons are automatically switched to at certain window sizes, and we also have a setting to have them permanently be small/normal:
![image](https://user-images.githubusercontent.com/21112697/124840291-7c85a880-df3f-11eb-9b50-b32477cfc7b1.png)
Please let us know if you have any feedback regarding this new capability and how it relates to this issue. You can download the latest Storage Explorer here: https://storageexplorer.com Thanks!

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. If you are still having issues with the refresh button, please open a new issue instead.
