### ISSUE TITLE
Feature Request: Additional Information in Delete Confirmation Popup

### ISSUE THREAD

**Issue by RyadMSFT** [microsoft/AzureStorageExplorer#320]
Currently, when deleting things in Storage Explorer such as Tables or Blob Containers, the confirmation dialogue simply lists the name of the thing being deleted.  

This can lead to confusions in workflows where multiple subscriptions or storage accounts may mirror each other in terms of Table/Blob Container layout (ex. a test environment mirroring prod), if a user accidentally clicks into a new account or subscription, the additional bit of information in the dialogue box (ex. "Are you sure you want to delete 'TableName' in 'StorageAccountName'?") might help prevent a mixup.

**Comment by jinglouMSFT** [comment]
Jason, please add this while working on soft delete.
