### ISSUE TITLE
An error dialog pops up when trying to save one document under a MongoDB account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3201]
**Storage Explorer Version:** 1.14.1
**Build**: 20200707.18
**Branch**: hotfix/1.14.1
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Created a CosmosDB account with MongoDB API in portal.
2. Launch Storage Explorer -> Expand Cosmos DB Accounts (Preview).
3. Right click the created CosmosDB account -> Create one database -> Create a collection.
4. Expand the collection -> Open the Documents.
5. Click 'New Document' -> Click 'Save' -> Check the result.

**Expect Experience:**
Succeed to save.

**Actual Experience:**
An error dialog pops up.
![image](https://user-images.githubusercontent.com/41351993/87021718-1ff68d00-c208-11ea-8f02-55eded3f922c.png)

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
