### ISSUE TITLE
The editor doesn't close when removing its corresponding item from Quick Access node

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3202]
**Storage Explorer Version:** 1.14.1
**Build**: 20200707.18
**Branch**: hotfix/1.14.1
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Select one service -> Add it to quick access.
2. Open the service under the Quick Access node.
3. Remove the service from the Quick Access node -> Check the state of the editor.

**Expect Experience:**
The editor is closed. 

**Actual Experience:**
The editor doesn't close.

**Comment by MRayermannMSFT** [comment]
Typically we auto-close editors when Storage Explorer is removing access to something. So like the thing was deleted, detached, subscription/account it belongs to is removed from Storage Explorer.

But for removing from quick access, Storage Explorer still has access.
