### ISSUE TITLE
Keep a consistent behavior when dragging files to one regular blob and ADLS Gen2 blob snapshots view

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3203]
**Storage Explorer Version:** 1.14.1
**Build**: 20200707.18
**Branch**: hotfix/1.14.1
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one storage account -> Open one blob snapshot view -> Try to drag files to it -> Check the result.
2. Expand one ADLS Gen2 storage account -> Open one blob snapshot view -> Try to drag files to it -> Check the result.

**Expect Experience:**
Keep a consistent behavior.

**Actual Experience:**
Show an inconsistent behavior.
1. Pop up an error for one regular blob.
![image](https://user-images.githubusercontent.com/54055206/87022594-4668f800-c209-11ea-8904-9a77e60c158a.png)
2. Show a failed activity log for one ADLS Gen2 blob.
![image](https://user-images.githubusercontent.com/54055206/87022627-541e7d80-c209-11ea-8443-e476d2af614c.png)

**Comment by MRayermannMSFT** [comment]
@craxal when you fix this, let's put the errors in the activity log, but, the error message should be like how it is for blobs. We shouldn't be trying to invoke AzCopy in snapshot mode.
