### ISSUE TITLE
bloop storage explorer error

### ISSUE THREAD

**Issue by vnahal** [microsoft/AzureStorageExplorer#3204]
Unable to retrieve child resources.

Details:
This request is not authorized to perform this operation.
RequestId:c4676178-6002-0003-60e4-5568f8000000
Time:2020-07-09T11:31:11.5141839Z

**Comment by MRayermannMSFT** [comment]
@vnahal this means you don't have the permissions needed to do what you were trying to do.

- What type of resource were you trying to load? Storage accounts, blob containers, queues, file shares?
- Are you relying on RBAC permissions or do you have access to storage account keys?
- If you're using RBAC, can you please verify that you have the required RBAC permissions to access your resources? Let us know if you need help with that.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response from original issue opener. Please open a new issue if you are continuing to have problems.
