### ISSUE TITLE
Storage Explorer doesn't show empty Storage Account

### ISSUE THREAD

**Issue by jhauray** [microsoft/AzureStorageExplorer#3205]
**Storage Explorer Version**: 1.14.0
**Build Number**: 20200624.3
**Platform/OS**: Linux Ubuntu 20.04 LTS (Snap package)
**Architecture**: x64
**Regression From**:  I don't know

## Bug Description ##
Storage Explorer doesn't show an empty Storage Account (without container), created from Azure Web Portal.
The Storage become visible after creation of the first blob container.

## Steps to Reproduce ##
1. Create an empty Storage Account V2 from cli or portal.
2. Open Storage Explorer and connect to the subscription.
3. Refresh Explorer : Storage Account is not visible.
4. Via cli or portal, add a blob container in the storage account.
5. Refresh Explorer : Storage Account is now visible.

## Expected Experience ##
All Storage Account must always be visible.

## Actual Experience ##
Freshly empty created Storage Account is not visible in Storage Explorer.

## Additional Context ##
Storage Explorer is installed from Snap package : https://snapcraft.io/storage-explorer
Storage Explorer was connected to password manager with command :  `snap connect storage-explorer:password-manager-service :password-manager-service`

**Comment by MRayermannMSFT** [comment]
@jhauray we are not able to reproduce this. Was this possibly just a timing issue?

 
<img width="203" alt="image" src="https://user-images.githubusercontent.com/21112697/87338888-af4abb80-c4fa-11ea-994b-32f530e7a0b7.png">

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response from original issue opener. Please open a new issue if you are continuing to have problems.
