### ISSUE TITLE
Storage Explorer prevents other applications from launching in Ubuntu

### ISSUE THREAD

**Issue by klineberry** [microsoft/AzureStorageExplorer#3206]
**Storage Explorer Version**: 1.14.0
**Build Number**: 20200624.3
**Platform/OS**: Ubuntu 20.04
**Architecture**: x64
**Regression From**:  Unknown

## Bug Description ##
After a short time, launching other applications fail. 

## Steps to Reproduce ##
Start Storage Explorer.
Open a few blob containers.
Attempt to launch a different program.

## Expected Experience ##
Program launches.

## Actual Experience ##
Program silently fail to launch.

## Additional Context ##
Syslog shows the following:
storage-explorer_storage-explorer.desktop[221230]: Maximum number of clients reachedFailed to setup connection to X server.

This led me to research failed to setup connection errors. Using lsof -U, the number of unix sockets in use is significant and grows dramatically with even minimal usage. After browsing just two containers, the number of sockets dedicated to Storage Explorer is about 20% of the total for the whole system.

**Comment by JasonYeMSFT** [comment]
@klineberry, Are you using the .tar.gz or the snap? There might be some code path that we are not closing the X server connections properly. I am going to refactor some code to make sure we are closing the connections properly and give you a private build to try.

**Comment by JasonYeMSFT** [comment]
I have inspected the code and fixed some code paths where we are not properly closing XDisplay connections. Here is private build with the fix.
https://aka.ms/linux-xdisplay-fix

If you installed Storage Explorer using snap, let us know so we can get you a snap build and instructions on how to install a snap manually.

**Comment by fjans** [comment]
Hello @JasonYeMSFT, I have the exact same problem with all X server connections being used within few clicks around the explorer and I have to restart.
I installed it using snap:

$ snap list storage-explorer
Name              Version  Rev  Tracking       Publisher            Notes
storage-explorer  1.14.0   13   latest/stable  msft-storage-tools✓  -

If you can provide a new snap I would be happy to test it a bit.

**Comment by JasonYeMSFT** [comment]
@fjans, we have just released our 1.14.1 which contains the fix. You can upgrade from snap to get 1.14.1 now.

**Comment by JasonYeMSFT** [comment]
Since there is no response, I am going to close this issue. Please open another one if you are still seeing the problem.
