### ISSUE TITLE
Drag to reorder tabs

### ISSUE THREAD

**Issue by LarsKemmann** [microsoft/AzureStorageExplorer#3208]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I intuitively try to drag tabs around to rearrange them but they don't respond to being dragged.

**Describe the solution you'd like**
I'd like a standard drag-to-reorder mechanism for tabs in Storage Explorer.

**Describe alternatives you've considered**
Rising up against the machine and injecting a virus into the Matrix. Unfortunately it sent a Terminator after me.

**Additional context**
None, the context menus on tabs are just fine the way they are. ;)

**Comment by MRayermannMSFT** [comment]
"Rising up against the machine and injecting a virus into the Matrix. Unfortunately it sent a Terminator after me."
😂😂😂😂😂

**Comment by MRayermannMSFT** [comment]
Duplicate of #501

**Comment by LarsKemmann** [comment]
Thanks! Sorry, I must have missed the other issue.
