### ISSUE TITLE
Storage Explorer Timing Out When Accessing Azure Tables

### ISSUE THREAD

**Issue by robertalorro** [microsoft/AzureStorageExplorer#3210]
**Storage Explorer Version**: 1.14
**Build Number**: 20200624.3
**Platform/OS**: Windows 10
**Architecture**: ia32
**Regression From**:  yes

## Bug Description ##

Details:
Network timeout error: connect ETIMEDOUT 52.239.177.70:443
Also, tried accessing the tables via Azure Portal's Storage Explorer via a web browser (Chrome) and am receiving the message "StorageError". This problems seems intermittent in which I'll access a table and it will return results. Then when going to another table it then times out.

## Steps to Reproduce ##
Select Tables located under the Storage Account. It comes back with the message:

Unable to retrieve child resources.
Details:
Network timeout error: connect ETIMEDOUT 52.239.177.70:443

After several attempts at refreshing it will finally display the tables. But then after a while it will begin to timeout again.

**Comment by MRayermannMSFT** [comment]
@robertalorro ETIMEDOUT means your network is taking a long time to talk to Azure Storage, such a long time, that Storage Explorer/the portal gives up waiting for a response. Are you on a meterted or unstable network? Any idea what kind of download speeds your network has?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response from original issue opener. Please open a new issue if you are continuing to have problems.
