### ISSUE TITLE
Keep same behaviors for inserting an entity with empty PartitionKey and Rowkey to tables under storage accounts and Cosmos DB accounts 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3211]
**Storage Explorer Version:** 1.14.1
**Build**: 20200710.5
**Branch**: hotfix/1.14.1
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Tables.
2. Create a new table -> Click 'Add' -> Click 'Insert' on the 'Add Entity' dialog. -> Check the behavior.
3. Select one CosmosDB account with Table API -> Create a table -> Expand the table. 
4. Open 'Entities' -> Click 'Add' -> Click 'Insert' on the 'Add Entity' dialog -> Check the behavior.

**Expect Experience:**
The two behaviors keep same.

**Actual Experience:**
The two behaviors are different.
1. For one table under a storage account, **succeed to insert an entity with PartitionKey and RowKey value empty.**
2. For one table under a CosmosDB account, **fail to insert an entity with PartitionKey or RowKey value empty.**
![image](https://user-images.githubusercontent.com/41351993/87109757-0dc42f80-c298-11ea-890b-7c2839ee23a0.png)

**Comment by MRayermannMSFT** [comment]
Won't fix. CosmosDB and table are just inherently different services/APIs.
