### ISSUE TITLE
The deleted snapshot doesn't auto disappear for one ADLS Gen2 blob

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3214]
**Storage Explorer Version:** 1.14.1
**Build**: 20200710.5
**Branch**: hotfix/1.14.1
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Go to 'Settings' -> 'Services' -> 'Storage Accounts' -> Enable the setting 'Enable ADLS Gen2 snapshots (preview)' -> Restart Storage Explorer.
2. Expand one ADLS Gen2 storage account -> Blob Containers.
3. Create one blob container -> Upload one blob to it -> Right click the blob then select 'Create Snapshots'.
4. Switch to snapshots view -> Try to delete the snapshot.
5. Check the result.

**Expect Experience:**
The snapshot auto disappears.

**Actual Experience:**
The snapshot doesn't auto disappear.

**More Info:**
1. The snapshot disappears after manually refreshing.
2. The behaviors are same whenever the setting 'Auto-refresh on change' is enabled or not.

**Comment by MRayermannMSFT** [comment]
For craig to investigate when he gets back. Make sure that things are consistent, or that at least gen2 is respecting the auto refresh setting if possible.

**Comment by craxal** [comment]
The problem is the promote job handler passes an `IBlobContainerRef` argument with the `refresh` event, but the handler in the explorer view model is expecting an `IBlobContainerConnection`. So, the `isMatchingContext` function doesn't return true, and the editor refresh doesn't occur.

**Comment by v-xianya** [comment]
Hi @craxal Verified this issue on build master/20200812.2. Still reproduce. So we are going to re-open it.

**Comment by craxal** [comment]
@v-xianya The Cloud Explorer reference was not up to date for 20200812.2. Please verify again with a newer build.

**Comment by v-xianya** [comment]
Hi @craxal Thanks for the updates. Verified this issue on build master/20200813.4. Fixed.
