### ISSUE TITLE
No refresh notification pops up after promoting snapshot for one ADLS Gen2 blob

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3215]
**Storage Explorer Version:** 1.14.1
**Build**: 20200710.5
**Branch**: hotfix/1.14.1
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Go to 'Settings' -> 'Data Explorers' -> Uncheck the setting 'Auto-refresh on change'.
2. Go to 'Settings' -> 'Services' -> 'Storage Accounts' -> Enable the setting 'Enable ADLS Gen2 snapshots (preview)' -> Restart Storage Explorer.
3. Expand one ADLS Gen2 storage account -> Blob Containers.
4. Create one blob container -> Upload one blob to it -> Create one snapshot for the blob.
5. Switch to snapshots view -> Click 'Promote Snapshot' -> Check the result.

**Expect Experience:**
Pop up a refresh notification.
![image](https://user-images.githubusercontent.com/41351993/87136038-7da0dd00-c2cd-11ea-9daf-157dbaec9575.png)

**Actual Experience:**
No refresh notification pops up.

**More Info:**
1. It also needs to manually refresh under snapshots view after promoting snapshot with 'Auto-refresh on change' enabled.

**Comment by MRayermannMSFT** [comment]
For craig to investigate when he gets back. Make sure that things are consistent, or that at least gen2 is respecting the auto refresh setting if possible.

**Comment by craxal** [comment]
The problem is the promote job handler passes an `IBlobContainerRef` argument with the `refresh` event, but the handler is expecting an `IBlobContainerConnection`. So, the `isMatchingContext` function doesn't return true, and the editor refresh doesn't occur.

**Comment by v-xianya** [comment]
Hi @craxal Verified this issue on build  master/20200812.2. Reproduce. So we are going to re-open it.

**Comment by craxal** [comment]
@v-xianya The Cloud Explorer reference was not up to date for 20200812.2. Please verify again with a newer build.

**Comment by v-xianya** [comment]
Hi @craxal Thanks for the updates. Verified this issue on build master/20200813.4. Fixed.
