### ISSUE TITLE
The pasted blob doesn't show when copying blobs under folders between regular and ADLS Gen2 blob containers

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3216]
**Storage Explorer Version:** 1.14.1
**Build**: 20200710.5
**Branch**: hotfix/1.14.1
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create one blob container -> Create a new folder -> Upload one blob to the folder.
3. Copy the blob to **one regular blob container**.
4. Check the result.

**Expect Experience:**
The blob shows in editor.

**Actual Experience:**

1. The blob doesn't show in editor.
2. Show a successful activity log.
![image](https://user-images.githubusercontent.com/54055206/87137774-07ea4080-c2d0-11ea-8909-ef9163accf7a.png)

**More Info:**

1. This blob still doesn't show after manually refreshing.
2. This issue also reproduces when copying one regular blob under one folder to one ADLS Gen2 blob container.
![image](https://user-images.githubusercontent.com/54055206/87136832-9eb5fd80-c2ce-11ea-828a-5e35c78c7611.png)
3. The result in release 1.14.0 shows below:
![image](https://user-images.githubusercontent.com/54055206/87137113-fce2e080-c2ce-11ea-9ef7-7d981da1d397.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into hotfix branch
