### ISSUE TITLE
Succeed to rename one ADLS Gen2 blob with snapshots

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3218]
**Storage Explorer Version:** 1.14.1
**Build**: 20200710.5
**Branch**: hotfix/1.14.1
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Go to 'Settings' -> 'Services' -> 'Storage Accounts' -> Enable the setting 'Enable ADLS Gen2 snapshots (preview)' -> Restart Storage Explorer.
2. Expand one ADLS Gen2 storage account -> Blob Containers.
3. Create one blob container -> Upload one blob to it -> Create snapshots for the blob.
4. Try to rename the blob -> Check the result.

**Expect Experience:**
Fail to rename the blob.

**Actual Experience:**
Succeed to rename the blob.

**More Info:**
The snapshots's name also changed after renaming the blob.
![image](https://user-images.githubusercontent.com/54055206/87141395-90b7ab00-c2d5-11ea-97f6-ba075aac342e.png)

**Comment by MRayermannMSFT** [comment]
Closing as by design.  ADLS Gen2's "rename" is server side. Since the snapshots are preserved, it seems the server is handling things ok when the rename happens.

**Comment by v-xianya** [comment]
@MRayermannMSFT Thanks for your update!

Could you help to elaborate the ‘rename’ mechanism for one ADLS Gen2 blob ? Does it directly delete the original blob?
