### ISSUE TITLE
Azure Storage Explorer issue while exploring a storage account 

### ISSUE THREAD

**Issue by amarsatpute** [microsoft/AzureStorageExplorer#3219]
**Storage Explorer Version**: V1.14
**Build Number**: 20200624.3
**Platform/OS**:Windows 10
**Architecture**: ia32
**Regression From**:  It was working in previous versions

## Steps to Reproduce ##
1. Connect to Azure storage using SAS URI
2.  After connecting try to access the storage account.
3. Following error is there

Unable to retrieve child resources.

Details:
["RestError:﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:2c25ad7c-a01e-0004-04a3-56c77b000000\nTime:2020-07-10T10:16:22.8096444Z</Message><AuthenticationErrorDetail>Signature not valid in the specified time frame: Start [Thu, 09 Jul 2020 10:11:03 GMT] - Expiry [Thu, 09 Jul 2020 18:11:03 GMT] - Current [Fri, 10 Jul 2020 10:16:22 GMT]</AuthenticationErrorDetail></Error>"]

**Comment by JasonYeMSFT** [comment]
The error message tells that the SAS has expired. See "Expiry" time is "[Thu, 09 Jul 2020 18:11:03 GMT]" while the time you access the resources "Current" is "[Fri, 10 Jul 2020 10:16:22 GMT]". Please get a new SAS to access the resource.

**Comment by amarsatpute** [comment]
Thanks for response

I have created a new token with 
Unable to retrieve child resources.

Details:
["RestError:﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:96144b2f-d01e-0044-1417-59ee95000000\nTime:2020-07-13T13:11:24.4539254Z</Message><AuthenticationErrorDetail>Signature not valid in the specified time frame: Start [Mon, 13 Jul 2020 13:12:50 GMT] - Expiry [Sun, 28 Feb 2021 21:12:50 GMT] - Current [Mon, 13 Jul 2020 13:11:24 GMT]</AuthenticationErrorDetail></Error>"]


This is new token with expiry date of year 21. still getting same issue

Can you please help me here

**Comment by MRayermannMSFT** [comment]
@amarsatpute your SAS still is not valid due to the start expiry time. As the error message says:
It starts at: Mon, **13 Jul** 2020 **13:12:50** GMT
It ends at: Sun, 28 Feb 2021 21:12:50 GMT
And the server thinks the time is: Mon, **13 Jul** 2020 **13:11:24** GMT

So you're using the SAS about 10min before it is valid.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response from original issue opener. Please open a new issue if you are continuing to have problems.
