### ISSUE TITLE
Impossible to login to Storage Explorer

### ISSUE THREAD

**Issue by irongut** [microsoft/AzureStorageExplorer#3221]
**Storage Explorer Version**: 1.14.0
**Build Number**: 20200624.3
**Platform/OS**: Windows 10 Pro 2004
**Architecture**: x64
**Regression From**:  It was barely working in the previous version.

## Bug Description ##
I am unable to login to Storage Explorer with with either of my Azure accounts.

I have been having problems logging into Storage Explorer for months now. My accounts have 2FA and MS Authenticator set up on them. With previous versions of Storage Explorer I found that if I had last logged in using MS Authenticator and tried to log in using it again then it would go into an infinite loop of authenticate, 2FA code, repeat. Similarly if I had previously logged in using my password and tried to use my password again I would get a loop of password, 2FA, repeat. The only way to log in was to use a different method to my last login.

The latest verison has become worse. No matter which method of authentication I choose I have an infinite loop of authenticate/password, 2FA and repeat. After about 10 tries I gave up and pressed cancel which then required me to cancel the sign in dialogs another 5 or more times before they stopped appearing over all other windows.

Now Storage Explorer is telling me "We didn't find any Microsoft Azure subscriptions associated with your account." The Azure portal would disagree, it lets me log in and access my subscription no problem. I now have no way to authenticate for that account, the option has been removed (see pic below).

## Steps to Reproduce ##
1. Open Storage Explorer and close the "Error:Unable to retrieve authentication token." dialogs that always appear.
2. Go to Manage Accounts.
3. Click Reenter Credentials for your account.
4. Click for an authenticatior notification or enter password.
5. Enter 2FA code.
6. Repeat from step 4.

## Expected Experience ##
Being able to log in using either authentication method but preferably the same one I used last time.
Not being told my Azure subscription does not exist - this is panic inducing.

## Actual Experience ##
Complete inability to login.

## Additional Context ##
![StorageExplorerAuthIssue](https://user-images.githubusercontent.com/27953302/87166221-26960a80-c2c3-11ea-9ff2-92e45dc879c8.png)

**Comment by MRayermannMSFT** [comment]
@irongut can you try enabling MSAL? Go to Settings (gear on the left) -> Application -> Sign-in -> Enable Microsoft Authentication Library (MSAL). It has much better for support for 2FA. Try that out, and let us know if the sign in experience improves.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response from original issue opener. Please open a new issue if you are continuing to have problems.
