### ISSUE TITLE
Selection focus jumps after pending operations complete, causing unintended file deletion

### ISSUE THREAD

**Issue by riazjahangir** [microsoft/AzureStorageExplorer#3222]
**Storage Explorer Version**: 1.14.0
**Build Number**: 20200624.3 
**Platform/OS**: macOS Catalina
**Architecture**: x64

## Bug Description ##
When viewing Blob Container contents, selection focus jumps to the top of the list after a pending operation completes. This may cause the wrong file to be deleted 

## Steps to Reproduce ##
1. Open a Blob Container
2. Perform a copy or delete operation that will take enough time for you to perform the next steps while the operation is in progress
3. Select any item in the view that is not the first item, and click Delete. Do not click Yes on the Delete confirmation dialog.
4. When the pending operation from step 2 completes, the selection jumps to the first item in the view
5. Now click Yes on the Delete confirmation. Storage Explorer deletes the first item in the view rather than the item you had selected when you clicked Delete.

## Expected Experience ##
The file that is selected when you click the Delete button should be deleted irrespective of what is selected when you click Yes in the Delete confirmation dialog. Including the name of the file to be deleted in the confirmation dialog would be valuable here as well.

## Actual Experience ##
The first item in the list gets deleted no matter what item was selected when Delete was clicked.

**Comment by MRayermannMSFT** [comment]
Wow @riazjahangir thank you for bringing this up. There's a few different places this can happen with deletes. We're going to patch the delete cases for 1.14.1, and then do another pass through all of our actions, and make sure this doesn't happen for anything: deletes, copies, open, etc. for 1.15.

**Comment by MRayermannMSFT** [comment]
@riazjahangir , due to some signing issues we were unable to include this fix in 1.14.1. The built-in release notes will say it is fixed but it is **not**. Once the signing issues are fixed we'll work on figuring out when to include the fix. Apologies for the delay.

**Comment by riazjahangir** [comment]
Ok @MRayermannMSFT , thanks for the update and the focus on this.

**Comment by JasonYeMSFT** [comment]
Unfortunately due to some issue of our build pipeline, our build containing the actual fix for 1.14.1 wasn't able to finish. We will include the actual fix in 1.14.2.
