### ISSUE TITLE
Make sure every command executes on the selected items when the button is clicked

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#3223]
Inspired by #3222 

Our current logic for some commands are:
1. User click button
2. We optionally prompt to confirm for execution
3. We read the selected items
4. Execute the command

If something that can change current selection goes between 1 and 4, the command may executed on unexpected items. Let's make sure we do it in the following order instead:
1. User click button
2. Upon click, the selection information is immediately read and cached
3. We optionally prompt to confirm for execution
4. Execute the command

## Command sets to fix:

- [x] Blobs
- [x] ADLS Gen2 blobs
- [x] Files
- [x] Queues
- [x] Tables
- [x] Managed disks

**Comment by craxal** [comment]
- [x] Blobs
- [ ] ADLS Gen2 blobs
- [ ] Files
- [ ] Queues
- [ ] Tables
- [ ] Managed disks
