### ISSUE TITLE
Manually deleted folder is is shown as present in azure databricks

### ISSUE THREAD

**Issue by Jigar191089** [microsoft/AzureStorageExplorer#3224]
I manually deleted a folder from Blob containers.
however when I check execute the command 'os.path.exists(path of deleted folder folder)' it return True.
When I delete the folder using 'shutil.rmtree(path)' the command 'os.path.exists(path)' return False which is correct

**Comment by MRayermannMSFT** [comment]
Couple of questions:

- Is your storage account and ADLS Gen2 account (is HNS enabled)?
- Do you have soft delete turned on?
- If you go and look today, do you see the folder in Storage Explorer?
- Do any other non-command-line/non programming tools show the folder? Say, the blob viewer at the Azure Portal?

**Comment by Jigar191089** [comment]
Is your storage account and ADLS Gen2 account (is HNS enabled)? - Yes
Do you have soft delete turned on? - Yes
If you go and look today, do you see the folder in Storage Explorer? - No, the folders were not showing from the moment they were deleted
Do any other non-command-line/non programming tools show the folder? Say, the blob viewer at the Azure Portal? Nope, it is not showing  in blob viewer of azure portal

**Comment by MRayermannMSFT** [comment]
If you have soft delete enabled then maybe it's possible that databricks considers soft deleted blobs to affect whether or not a folder exists. You should check with the databricks team about if this is true or not. Does that make sense?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response from original issue opener. Please open a new issue if you are continuing to have problems.
