### ISSUE TITLE
Unable to retrieve child resources.

### ISSUE THREAD

**Issue by dkollangodeseshamani** [microsoft/AzureStorageExplorer#3226]
Team,

I am unable to see all my collections in the selected database.
Receiving the following error: "### Unable to retrieve child resources."

**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:

**Comment by welch1pr** [comment]
Unable to retrieve child resources.

Details:
self signed certificate in certificate chain

**Comment by welch1pr** [comment]
Same here, worked last week.

**Comment by dkollangodeseshamani** [comment]
It got resolved for me.  Issue is with my laptop time not in sync.
