### ISSUE TITLE
Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by rlopezcoalicion** [microsoft/AzureStorageExplorer#3228]
**Storage Explorer Version**: 1.14.0
**Build Number**: 20200624.3
**Platform/OS**:  Windows 10
**Architecture**: X64
**Regression From**:  Yes, 1.13.1

## Bug Description ##
Cannot read property 'version' of undefined

**Comment by rlopezcoalicion** [comment]
Is there any way to rollback to the previous version?

**Comment by JasonYeMSFT** [comment]
Please check the troubleshooting steps to see if it can mitigate your issue. [troubleshooting guide](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#error-occurred-while-adding-new-connection-typeerror-cannot-read-property-version-of-undefined)

To rollback to the previous version, you can download and re-install an older release from https://github.com/microsoft/AzureStorageExplorer/releases

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response from original issue opener. Please open a new issue if you are continuing to have problems.
