### ISSUE TITLE
Storage explorer unable to connect to local emulator

### ISSUE THREAD

**Issue by dhmuralikrishna** [microsoft/AzureStorageExplorer#3231]
Storage Explorer Version: 1.14.1
Build Number: 20200711.2
Platform/OS:  Windows 10
Architecture: x64

## Bug Description ##
Storage explorer is unable to connect to local storage emulator. Proxy is disabled.
I tried deleting %appdata%storage explorer folder and tried restart  storage explorer multiple times

![image](https://user-images.githubusercontent.com/17012246/87441976-bbe61700-c5c1-11ea-891c-3c197ce4bb1a.png)

![image](https://user-images.githubusercontent.com/17012246/87441734-71fd3100-c5c1-11ea-9197-8d3f66c94425.png)

Storage emulator is up and running. V5.10
![image](https://user-images.githubusercontent.com/17012246/87441794-87725b00-c5c1-11ea-9b31-bc5f515e39a4.png)

## ERROR ##
["FetchError:request to http://127.0.0.1:10001/devstoreaccount1/?include=metadata&comp=list&timeout=30 failed, reason: tunneling socket could not be established, statusCode=302"]

**Comment by JasonYeMSFT** [comment]
Do you have a system proxy configured?

**Comment by dhmuralikrishna** [comment]
Machine has proxy setup. 

![image](https://user-images.githubusercontent.com/17012246/87729021-5a28d700-c792-11ea-880a-04d8cb4b202c.png)

**Comment by MRayermannMSFT** [comment]
@dhmuralikrishna did this work for you before/in the past?

- Maybe your system proxy is affecting the emulator, thus maybe you do need to setup the proxy settings in Storage Explorer?
- Alternatively can you try using Azurite?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
