### ISSUE TITLE
Can't access blob containers "Unable to retrieve child resources"

### ISSUE THREAD

**Issue by ckraulerson** [microsoft/AzureStorageExplorer#3233]
I'm unable to access my resources, even though the connection is successful. I'm trying to connect with the "Use a storage account and key" option. This is the versioning of the Storage Explorer: 

```
Version: 1.14.1
AzCopy Version: 10.5.0

Platform: macOS
Architecture: x64 
Build Number: 20200711.2 
Commit: c4a35df74 
Support ID: 990a7eab-67e9-1c36-0c25-38b3859465fb 
```

I'm getting this error: 

```
Unable to retrieve child resources.

Details:
["RestError:﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.\nRequestId:2a789efa-201e-00b6-59ef-592d51000000\nTime:2020-07-14T15:00:18.1472277Z</Message></Error>"]
```

I have tried:

- Closing Storage Explorer, removing the StorageExplorer folder, reopening Storage Explorer, and re-entering my credentials. 
- Uninstalling Storage Explorer, and resetting with a fresh install
- Checking for a self-assigned certificate ([StorageExplorer Troubleshooting](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004)). I did not find any. 

I know that the credentials work, because my co-workers have successfully used them all day.

**Comment by ckraulerson** [comment]
I was able to resolve this on my own.

**Comment by mbaserdem** [comment]
Hello ckraulerson.    I encountered same problem.  How did you resolve yours?
