### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by t-dipeke** [microsoft/AzureStorageExplorer#3234]
**Storage Explorer Version**:  1.14.1. 

## Bug Description ##
I've been using the following tutorial for Azure AD join and automatic MDM enrollment validation (https://onedrive.live.com/view.aspx?resid=7B176DA1FE1D885D!475991&cid=D9DDBB4D-B176-4D1A-A043-F2B5F822A0CE&ithint=file%2cdocx&wdLOR=c826F18E4-8FC2-4EEF-94D1-6D242D039DE4&authkey=!AHSU7A5o_L21Fnw) and am running into problems with step 7 where I need to access the vhd folder in blob containers.

## Expected Experience ##

**Trying to access vhd subfolder within the blob containers**

## Actual Experience ##

**Unable to retrieve child resources.

Details:
["RestError:﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:e67346a2-401e-0060-4309-5aacea000000\nTime:2020-07-14T18:05:01.6996854Z</Message><AuthenticationErrorDetail>The MAC signature found in the HTTP request 'TXQSYimAD2VRBxWYb6/AsYg+BonbUnVd8T73OKZmMxQ=' is not the same as any computed signature. Server used following string to sign: 'GET\n\n\n\n\n\n\n\n\n\n\n\nx-ms-client-request-id:2e81ff0a-9ed6-494f-90ad-5e49450eebea\nx-ms-date:Tue, 14 Jul 2020 18:05:01 GMT\nx-ms-version:2019-07-07\n/wvdsharedimage/\ncomp:list\ninclude:metadata'.</AuthenticationErrorDetail></Error>"]**

**Comment by manjudna** [comment]
Facing same issue with Azure Storage Explorer, when try to create new table

**Comment by JasonYeMSFT** [comment]
@t-dipeke The tutorial gives you a connection string with storage account key. It is likely that the account key has been rotated so that the key provided in the tutorial is no longer valid. Please contact the author of the tutorial to see if it is the case.

@manjudna, are you also following the tutorial like t-dipeke did? If not, it is very likely you are seeing a different issue, please consider open a new one describing your repro steps.

**Comment by t-dipeke** [comment]
Hi Jason,

Thanks for getting back to me. It seems as though the document I was working off of had an outdated connection string. Thank you for your help nevertheless.

Best,
Dina

**Comment by MRayermannMSFT** [comment]
Closing since original issue was mitigated.
