### ISSUE TITLE
Not able to see the text typed in Cosmos DB filter criteria text box in Dark theme mode

### ISSUE THREAD

**Issue by ravishankar54** [microsoft/AzureStorageExplorer#3237]
**Storage Explorer Version**: 1.14.1
**Build Number**: 20200711.2
**Platform/OS**: Windows
**Architecture**: ia32
**Regression From**:  

## Bug Description ##
For Cosmos DB Accounts(Preview) option in dark theme not see the text in filter criteria text box as it becoming white in color.

![image](https://user-images.githubusercontent.com/13334733/87527265-7e5cb900-c6a9-11ea-8c26-2eea2c450f28.png)

## Steps to Reproduce ##
1.Change the theme to Dark , view=>theme=>Dark
2.Connect to any CosmosDB account, in left side panel => select collection then go to documents,
right side panel click on filter option, then you wont able to see the text you type in filter criteria text box.

## Expected Experience ##
Should be able to see the text typed in filter criteria in dark theme mode for cosmos db documents

## Actual Experience ##
![image](https://user-images.githubusercontent.com/13334733/87527672-1490df00-c6aa-11ea-9a6d-a7d0f43f6296.png)

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
