### ISSUE TITLE
Properties panel showing error for storage accounts of locked resource group

### ISSUE THREAD

**Issue by YECHUNAN** [microsoft/AzureStorageExplorer#324]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Windows 10
**Architecture**: ia32
**Regression From**: N/A

#### Steps to Reproduce: ####
1. Add a lock to the resource group for a storage account
2. Open Storage Explorer
3. Navigate to the node of that storage account on the left

#### Expected Experience: ####
Properties in the properties panel are displayed or set to empty ""/"not available".

#### Actual Experience: ####
The "...Key" fields have value "Error loading property". It also creates uncaught errors that can be seen from the console.

**Comment by craxal** [comment]
I'm not familiar with resource group locks. Can you post those errors?

**Comment by JasonYeMSFT** [comment]
The current Nodejs library/Rest API doesn't support getting lock information. This has to be configured by the user outside Storage Explorer for now.
