### ISSUE TITLE
ssl error

### ISSUE THREAD

**Issue by irishmaninusa** [microsoft/AzureStorageExplorer#3241]
**Storage Explorer Version**: 1.14.1 
**Build Number**: 20200711.2 
**Platform/OS**: Windows
**Architecture**: ia32
**Regression From**:   

## Bug Description ##
SSL is not being recognised

[8:54 AM] Daly, J
    Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: 0b5ac31e-e17a-4021-9d04-550f86320765, Error: {
  "name": "Error",
  "message": "self signed certificate in certificate chain",
  "stack": "Error: self signed certificate in certificate chain\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1331:34)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at TLSSocket.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at TLSSocket.emit (events.js:210:5)\n    at TLSSocket._finishInit (_tls_wrap.js:804:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:618:12)",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}

## Steps to Reproduce ##
Logging in with my user account
Do the duo sign off
and then nothing appears

## Expected Experience ##
to work

## Actual Experience ##
Does not work

## Additional Context ##
Adding in the ignore ssl appears to work - but would much prefer not have to do this.

**Comment by irishmaninusa** [comment]
And I have followed the steps on this page and no luck

https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C1804#error-self-signed-certificate-in-certificate-chain-and-similar-errors

**Comment by MRayermannMSFT** [comment]
@irishmaninusa which steps have you tried from the troubleshooting? Have you not been able to identify where the cert is coming from?

**Comment by Surbhi23916** [comment]
I can't find the self signed certificates

**Comment by MRayermannMSFT** [comment]
@Surbhi23916  which steps did you try?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you're still encountering this problem, please open a new issue. Thanks!
