### ISSUE TITLE
Unable to launch AzureStorageExplorer 1.14.1 on MacOS 10.15.5

### ISSUE THREAD

**Issue by lukapril** [microsoft/AzureStorageExplorer#3242]
**Storage Explorer Version**: 1.14.1
**Build Number**: 20200711.2
**Platform/OS**: MacOS 10.15.5
**Architecture**: x64
**Regression From**:  1.12

## Bug Description ##
AzureStorageExplorer was working fine yesterday, today seems like something went wrong and the whole window closed. So I went and download the latest version 1.14.1. Launch AzureStorageExplorer and it just sits there, there's no prompt, no window. All I have is the app on the menu bar. I tried to click on Settings, nothing happened.

## Steps to Reproduce ##
1. Download latest from https://azure.microsoft.com/en-us/features/storage-explorer/
2. Launch the app, nothing happened

## Expected Experience ##
The app should at least launch 

## Actual Experience ##
Nothing happened

<img width="580" alt="Screen Shot 2020-07-15 at 8 25 42 AM" src="https://user-images.githubusercontent.com/682004/87558336-3a9c8c00-c676-11ea-8f0d-0a9824b1111d.png">

**Comment by JasonYeMSFT** [comment]
Maybe related to https://github.com/microsoft/AzureStorageExplorer/issues/3086. Could you try installing 1.13.0/1.13.1 to see if can launch? We would like to know starting from which version this happens.

**Comment by Joshua33333** [comment]
I have the same issue. It was working normally, then I accidentally pressed a key combination on the keyboard and since then I am unable to see the app, but it is running. I believe is hidden somewhere.

**Comment by Joshua33333** [comment]
> Maybe related to #3086. Could you try installing 1.13.0/1.13.1 to see if can launch? We would like to know starting from which version this happens.

I tried 1.13.1 and it does not work either.

**Comment by Joshua33333** [comment]
I solved the issue by deleting the application support directory
.../Library/Application Support/StorageExplorer/
Then start the storage explorer and it works fine. Even version 1.14.2.

**Comment by MRayermannMSFT** [comment]
@lukapril 

First can you try deleting `~/Library/Application Support/StorageExplorer/appState.json` and then run Storage Explorer.

And then if that doesn't work, delete everything in ~/Library/Application Support/StorageExplorer/` and then run Storage Explorer.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you're still encountering this problem, please open a new issue. Thanks!

**Comment by vjranagit** [comment]
> @lukapril
> 
> First can you try deleting `~/Library/Application Support/StorageExplorer/appState.json` and then run Storage Explorer.
> 
> And then if that doesn't work, delete everything in `~/Library/Application Support/StorageExplorer/` and then run Storage Explorer.

resolved the issue thanks
