### ISSUE TITLE
Updates keep dropping my Quick Access list

### ISSUE THREAD

**Issue by mbacon-edocs** [microsoft/AzureStorageExplorer#3246]
**Storage Explorer Version**: All
**Build Number**: Multiple
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  n/a

## Bug Description ##
Every time I update this application my quick access list gets dropped

## Steps to Reproduce ##
1. Add things to quick access
2. Wait for an update
3. Install update
4. Quick access is now blank

## Expected Experience ##
Quick access links stay there across updates

## Actual Experience ##
Quick access is empty after an update

## Additional Context ##
It's happened pretty much every time I update, from memory. I don't update very frequently now, because it wastes more time than it saves at the moment

**Comment by MRayermannMSFT** [comment]
@mbacon-edocs
1. What version were you on previously and to what version did you upgrade to?
2. What types of resources did you have in Quick Access?

**Comment by mbacon-edocs** [comment]
1. In this case it was to 1.14.2, from 1.14.1 - although as I said, this seems to be an ongoing issue
2. I had a mix of queues, blob containers and tables. Possibly worth mentioning that they were mostly, if not all, from a classic blob account

**Comment by MRayermannMSFT** [comment]
@mbacon-edocs ok thanks. We'll test out that upgrade a few times, but in general this isn't something we've ever been able to consistently reproduce. We'll keep investigating and see if there's anything we can do to increase the reliability of the QA settings not getting lost.

**Comment by munael** [comment]
Possibly related: I didn't "lose" my Quick Access list, but it's gone all the same. See:
![image](https://user-images.githubusercontent.com/5769148/108187343-07900e80-7117-11eb-818c-5d4433249500.png)
All the ones with `x` in the icons are inaccessible _through Quick Access_. Even though I can navigate to where they are add them again.

**Comment by MRayermannMSFT** [comment]
We haven't been able to reproduce this and we haven't heard of similar reports from anyone else. If you are still seeing this in newer releases (as of writing, the latest is 1.20), please let us know with a new issue.
