### ISSUE TITLE
The editor doesn't auto close when trying to delete one opened queue from Quick Access node

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3248]
**Storage Explorer Version:** 1.14.2
**Build**: 20200715.2
**Branch**: hotfix/1.14.2
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture**: ia32/x64
**Regression From:** Previous release (1.13.1)

**Steps to reproduce:**
1. Expand one storage account -> Queues.
2. Create one queue and keep its editor open.
3. Add the queue to Quick Access -> Delete the queue from Quick Access node.
4. Check whether the editor is closed or not.

**Expect Experience:**
The editor is auto closed.
 
**Actual Experience:**
The editor doesn't auto close.

**More Info:**
1. This issue also reproduces for one blob container.
2. This issue doesn't reproduce for one file share & table.

**Comment by MRayermannMSFT** [comment]
Let's make sure Delete is not available in Quick Access queues.

**Comment by v-xianya** [comment]
Verified this issue on build 20201116.2. The delete action is removed from one QA queue's context menu. 
![image](https://user-images.githubusercontent.com/41351993/99205169-a47a9d00-27f2-11eb-9a1a-c6e401b54f01.png)
