### ISSUE TITLE
The error link append to one failed activity log isn't match with its opened dialog's title when creating snapshot for disks

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3249]
**Storage Explorer Version:** 1.14.2
**Build**: 20200715.2
**Branch**: hotfix/1.14.2
**Platform/OS:** Windows 10/  Linux Ubuntu 18.04 / macOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Open one resource group -> Upload one disk to it.
2. Click 'Create Snapshot' on toolbar-> Type an empty name in dialog.
3. Click 'Create Snapshot Error' in activity log -> Check the popped dialog's title.

**Expect Experience:**
Keep consistent name between the activity log and the popped dialog.

**Actual Experience:**
Show an inconsistent.
![image](https://user-images.githubusercontent.com/54055206/87656631-4f6b4380-c78c-11ea-8979-209bf6619afc.png)

**More Info:**
This issue also reproduces in copy error's activity when pasting one disk with the same resource.
![image](https://user-images.githubusercontent.com/54055206/87656623-4da18000-c78c-11ea-8745-9ab76829b493.png)

**Comment by MRayermannMSFT** [comment]
Low pri. Won't fix.
