### ISSUE TITLE
The editors of one file share and ADLS Gen2 blob container always show blank

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3252]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200717.1
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture**: ia32/x64
**Regression From:** Previous release (1.14.2)

**Steps to reproduce:**
1. Expand one storage account -> File Shares.
2. Create a file share -> Check its editor.
3. Try to create one folder or upload one file.
4. Check its editor.

**Expect Experience:**
1. The editor shows well.
2. The new folder or uploaded file shows well.

**Actual Experience:**
The editor always shows blank.
 
![image](https://user-images.githubusercontent.com/41351993/87762611-ff50b780-c845-11ea-87e9-397892e2c622.png)

**More Info:**
1. This issue also reproduces for one ADLS Gen2 blob container.

**Comment by v-limu** [comment]
Verified on build 20200718.3. This issue has been fixed. So close it.
