### ISSUE TITLE
Fail to save properties for one blob container connected via public blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3254]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200717.1
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Create one blob container -> Right click it -> Click 'Set Public Access Level...'.
3. Select 'Public read access for container and blobs' -> Click 'Apply'.
4. Copy the blob's URL -> Open connect dialog -> Select 'Connect to public blob container' -> Click 'Next'.
5. Paste the URL then input the display name -> Click 'Next' -> Click 'Connect'.
6. Right click the public connected blob container -> Click 'Properties...'.
7. Click 'Save' -> Check the activity log.

**Expect Experience:**
Display a reasonable activity log.

**Actual Experience:**
Display a failed activity log and the error details doesn't make sense.
![image](https://user-images.githubusercontent.com/41351993/87764806-88b5b900-c849-11ea-8f70-bca4e811a502.png)

**More Info:**
1. This issue also reproduces for blobs under the Public connected blob container.
2. This issue also reproduces for one public blob container connected from one emulator node.

**Comment by MRayermannMSFT** [comment]
By design. Cannot write (make changes to) public containers or their contents.
