### ISSUE TITLE
Nothing happens when selecting 'Snapshot original blob then upload' for one file under Public connected blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3255]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200717.1
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Create one blob container -> Upload one text file
3. Right click it -> Click 'Set Public Access Level...'.
3. Select 'Public read access for container and blobs' -> Click 'Apply'.
4. Copy the blob's URL -> Open connect dialog -> Select 'Connect to public blob container' -> Click 'Next'.
5. Paste the URL then input the display name -> Click 'Next' -> Click 'Connect'.
6. Open the public connected blob container -> Open the text file and make some changes -> Save it.
7. Select 'Snapshot original blob then upload' -> Click 'Apply'.
7. Check the result.

**Expect Experience:**
Show activity logs at least.

**Actual Experience:**
Nothing happens.

**More Info:**
Show the below error after selecting 'Upload' option on File Changes Detected dialog.
![image](https://user-images.githubusercontent.com/41351993/87766536-e0edba80-c84b-11ea-89be-ab45ae1dc48b.png)

**Comment by JasonYeMSFT** [comment]
We should not be prompting at all since it is not possible to upload/snapshot to a public blob container.
