### ISSUE TITLE
It is better to auto fill the display name after pasting container URL on 'Connect to public blob container' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3256]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200717.1
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Select one blob container which 'Public Read Access' is container.
3. Copy its URL -> Open connect dialog -> Select 'Connect to public blob container' -> Click 'Next'.
4. Paste the copied URL -> Check the display name is auto filled or not.

**Expect Experience:**
It would be better to auto fill the display name.

**Actual Experience:**
Need to manually input the display name.
![image](https://user-images.githubusercontent.com/41351993/87767361-1f37a980-c84d-11ea-88d3-9b6f6ecd85b2.png)

**Comment by v-limu** [comment]
Verified on build 20200812.2. This issue has been fixed. So close it.
