### ISSUE TITLE
Miss 'Change Access Tier…' action for one blob

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3257]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200717.1
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture**: ia32/x64
**Regression From:** Previous release(1.14.2)

**Steps to reproduce:**

1. Expand one storage account -> Blob Containers.
2. Create one blob container -> Upload one blob to it -> Open its context menu.
3. Check whether the 'Change Access Tier...' action shows or not.

**Expect Experience:**
Show 'Change Access Tier...' on the context menu.

**Actual Experience:**
No 'Change Access Tier....' shows on the context menu.
![image](https://user-images.githubusercontent.com/54055206/87765379-4c368d00-c84a-11ea-97fe-0dc047b15fdc.png)

**Comment by v-xianya** [comment]
Verified this issue on master build 20200720.3. Reproduce.

**Comment by v-limu** [comment]
Hi @JasonYeMSFT  Verified on build 20200720.3. 

1. This issue reproduces for one blob under one **new created regular v2 blob container**. 
2. This issue reproduces when cloning/ pasting one blob container. 

This action appears after manually refreshing Blob Containers node.

**Comment by v-xianya** [comment]
Verified this issue on build master/20200722.6. Fixed.
