### ISSUE TITLE
 Display values for 'Access Tier Last Modified' against emulator blobs with inferred access tier

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3261]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200717.1
**Branch**: master
**Platform/OS:** Windows 10
**Architecture**: ia32/x64
**Azurite Version** : 3.8.0
**Emulator Version**: 5.10.0.0
**Regression From:** Not a regression

**Steps to reproduce:**
1. Install and run Azurite 3.8.0 -> Launch Storage Explorer.
2. Expand Local & Attached -> Storage Accounts -> (Emulator - Default Ports) (Key) -> Blob Containers.
3. Create a blob container -> Upload files.
4. Check the column of 'Access Tier Last Modified'.

**Expect Experience:**
No value displays.

**Actual Experience:**
Display values.
![image](https://user-images.githubusercontent.com/41351993/87768525-da147700-c84e-11ea-9936-2b020e84e5fb.png)

**More Info:**
The screenshot when using Emulator 5.10.0.0.
![image](https://user-images.githubusercontent.com/41351993/87768613-fd3f2680-c84e-11ea-8e77-b848ba10b67d.png)

**Comment by MRayermannMSFT** [comment]
It looks like inferred access tier is not supported by the .NET emulator. By design.
