### ISSUE TITLE
Show a failed activity log when clicking 'Folder Statistics' for one attached emulator public blob container 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3263]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200717.1
**Branch**: master
**Platform/OS:** Windows 10
**Emulator**: (5.10.0.0)
**Azurite Version**: 3.8.0
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Install and run Emulator -> Launch Storage Explorer.
2. Expand Local & Attached -> Storage Accounts-> (Emulator - Default Ports) (Key) -> Blob Containers.
3. Select one blob container which 'Public Read Access' is container -> Attach it via 'Connect to public blob container'.
4. Open the attached blob container -> Click 'Folder Statistics'.
5. Check the result.

**Expect Experience:**
Show a successful activity log.

**Actual Experience:**
Show a failed activity log.
![image](https://user-images.githubusercontent.com/54055206/87771275-b94e2080-c852-11ea-80b3-d1c6cbc84f98.png)

**Comment by JasonYeMSFT** [comment]
Let's wait until customers are asking for supporting this scenario, like SAS attached local emulator account/containers.

**Comment by MRayermannMSFT** [comment]
Ya we're not worried about attaching emulator containers.
