### ISSUE TITLE
Try to connect Azure Resource get failure

### ISSUE THREAD

**Issue by ROBINLEI** [microsoft/AzureStorageExplorer#3264]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:

**Comment by MRayermannMSFT** [comment]
@ROBINLEI could you please fill out the information in the issue template?

**Comment by MRayermannMSFT** [comment]
@ROBINLEI please open a new issue with the template filled out.
