### ISSUE TITLE
Unable to retrieve child resources.

### ISSUE THREAD

**Issue by Fcakiroglu16** [microsoft/AzureStorageExplorer#3265]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:

**Comment by MRayermannMSFT** [comment]
@Fcakiroglu16 could you please fill out the information in the issue template?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of information. Please open a new issue if you are still having problems, and please fill out the template when you do so. Thanks!
