### ISSUE TITLE
Unable to retrieve children. socket hang up

### ISSUE THREAD

**Issue by duezito** [microsoft/AzureStorageExplorer#3267]
Details:
["FetchError:request to http://127.0.0.1:10000/devstoreaccount1/?include=metadata&comp=list failed, reason: socket hang up"]

I´m trying to create a blob container on a local Storage account. 
I created a localDB and I tried clearing up %appData%/StorageExplorer but to no avail.

Could you help me?

**Comment by MRayermannMSFT** [comment]
Do you have proxy settings enabled?

**Comment by duezito** [comment]
No. I didn´t..



Em seg., 20 de jul. de 2020 às 14:41, Matthew Rayermann <
notifications@github.com> escreveu:

**Comment by MRayermannMSFT** [comment]
@duezito can you please answer all questions? Thanks!

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
