### ISSUE TITLE
Default key for new metadata in adls gen2 is wrong

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3270]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200718.3
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture:** ia32/x64
**Regression From:** Previous release(1.13.1)

**Steps to reproduce:**

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Open one blob container -> Select one folder -> Click 'Properties...'.
3. Check the Properties dialog.

**Expect Experience:**
Show a matched button in 'Properties' dialog.

**Actual Experience:**
Show an unmatched button in 'Properties' dialog.
![image](https://user-images.githubusercontent.com/54055206/87920925-78e9df00-caac-11ea-8fb6-a793547f1107.png)

**More Info:**

1. This issue doesn't reproduce for blobs / blob containers.
2. This issue doesn't reproduce for one file share.

**Comment by MRayermannMSFT** [comment]
Fix merged into master.

**Comment by v-limu** [comment]
Hi @MRayermannMSFT 

Verified on build 20200806.6. The button has been fixed. But the **metadata Key** doesn't match. Can you take a look?😃
![image](https://user-images.githubusercontent.com/54055206/89485644-d0d65480-d7d3-11ea-9583-8a8c645640fa.png)

**Comment by MRayermannMSFT** [comment]
I checked in a fix to the new metadata prefix to master.
