### ISSUE TITLE
No 'Custom Domain' shows for one new created blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3273]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200720.3
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Create a new blob container.
3. Check whether there shows 'Custom Domain' on its properties panel.

**Expect Experience:**
Show 'Custom Domain' on its Properties panel.

**Actual Experience:**
No 'Custom Domain' on its Properties panel.

**More Info:**
The 'Custom Domain' shows after manually refreshing the 'Blob Containers' node.

**Comment by craxal** [comment]
Related to #3110.
