### ISSUE TITLE
A conflict dialog pops up when cloning one file share contains a folder which named ';'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3274]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200720.3
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture:** ia32/x64
**Regression From:** Previous release(1.12.0)

**Steps to reproduce:**
1. Expand one storage account -> File Shares.
2. Create a new file share -> Create a folder with name ';'. 
![image](https://user-images.githubusercontent.com/41351993/88025147-6b912b00-cb66-11ea-82bc-4d048e6e70a7.png)

3. Clone the file share -> Check the result.

**Expect Experience:**
No conflict dialog pops up.

**Actual Experience:**
A conflict dialog pops up.
![image](https://user-images.githubusercontent.com/41351993/88023187-2dded300-cb63-11ea-9eed-408e74e25a63.png)

**More Info:**
This issue also reproduces for file shares 'copy & paste' actions.

**Comment by JasonYeMSFT** [comment]
We do receive a conflict prompt from AzCopy, we should ask why AzCopy thinks there is a conflict.

**Comment by JasonYeMSFT** [comment]
Reported in https://github.com/Azure/azure-storage-azcopy/issues/1107

**Comment by MRayermannMSFT** [comment]
Also reproduces if name is just a ','

**Comment by JasonYeMSFT** [comment]
This fixed by AzCopy.
