### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by koljada** [microsoft/AzureStorageExplorer#3275]
**Storage Explorer Version**: 1.14.2
**Build Number**: 20200715.2
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  It was working earlier but I don't know in which version

## Bug Description ##
I cannot use local emulator. When I'm trying to expand Tables or Blob Containers it gives me next error:

> Unable to retrieve child resources.
> 
> Details:
> Server encountered an internal error. Please try again after some time.
> RequestId:ab1ce6c8-3252-4e48-99f6-ac72ac9f1b4d
> Time:2020-07-21T08:29:57.9614500Z

I believe it's also a reason why I can't run my azure functions locally. It's very annoying.
I double checked that Azure Storage Emulator is initialized and running.

**Comment by JasonYeMSFT** [comment]
@koljada, are you using the .Net storage emulator or Azurite? which version are you using? From the error details, it says that server encountered an internal error so it is possible that the problem is in your local emulator's configuration.

**Comment by koljada** [comment]
I'm using the latest version of Azure Storage Emulator. And it seems like the issue was related to emulator: for some reason schema in LocalDB was no created. After I reinstalled SqlServer it's working. If it's not related to Azure Storage Explorer then this issue can be closed. The error message is not very helpful anyway.

**Comment by MRayermannMSFT** [comment]
Thanks!
