### ISSUE TITLE
Azure Storage Explorer - Cannot connect to IoT Edge Local Blob Storage

### ISSUE THREAD

**Issue by SeshagiriSriram** [microsoft/AzureStorageExplorer#3276]
**Storage Explorer Version**: 1.14.2 
**Build Number**: 20200715.2
**Platform/OS**: Windows 10 Professional
**Architecture**: x64
**Regression From**:  unsure 

## Bug Description ##
Storage Explorer throws exception when navigating to Blob Containers and File shares.

## Steps to Reproduce ##
Installed Azure IoT Blob on Ubuntu 18.04 server per https://docs.microsoft.com/en-us/azure/iot-edge/how-to-deploy-blob
Docker is up and running and reported in IoT Edge
<img width="904" alt="issue_azure_blob" src="https://user-images.githubusercontent.com/3693855/88031749-a725f800-cb5a-11ea-92ef-3cb4ff23be62.png">
Set up a connection in Azure Storage explorer using account name and Key. 
IOT Edge device can be pinged. 
Navigating to Blob Containers/File containers throws errors. Ditto with Table/Queue
[issue_file_container.txt](https://github.com/microsoft/AzureStorageExplorer/files/4952282/issue_file_container.txt)

[issue_blob_container.txt](https://github.com/microsoft/AzureStorageExplorer/files/4952255/issue_blob_container.txt)
<img width="725" alt="connection_string" src="https://user-images.githubusercontent.com/3693855/88032093-1f8cb900-cb5b-11ea-8c57-685e6e9efd6a.png">
[issue_queue.txt](https://github.com/microsoft/AzureStorageExplorer/files/4952291/issue_queue.txt)

## Expected Experience ##
Since ping/docker is all reporting OK, I would expect this to connect to IoT Edge Local Blob Storage. 

## Actual Experience ##
Clicking/expanding on the containers throws errors as outlined in the attached text files. 

## Additional Context ##
Reference for deploying Blob storage taken from here. https://docs.microsoft.com/en-us/azure/iot-edge/how-to-deploy-blob 
Occaisionaly get "account has been disabled" message.

**Comment by SeshagiriSriram** [comment]
For reference I am also adding the deployment manifest json file 
[deployment.manifest.txt](https://github.com/microsoft/AzureStorageExplorer/files/4952334/deployment.manifest.txt)

**Comment by mbialecka** [comment]
@seshagc What is the connection string you used in Storage Explorer to connect to blob storage container? Side note - only "Blob Containers" option should work.

**Comment by SeshagiriSriram** [comment]
https://localblobstorage.blob.core.windows.net
I have a windows host. I have an Ubuntu Box running on Vagrant and local blob storage is created on this Ubuntu box.

**Comment by mbialecka** [comment]
@SeshagiriSriram This doesn't seem correct. Plese follow these instructions: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-store-data-blob#connect-to-your-local-storage-with-azure-storage-explorer

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response from issue opener. Please open a new issue if you still need help.
