### ISSUE TITLE
Display a successful activity log when pasting one deleted blob to another blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3277]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200720.3
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture:** ia32/x64
**Regression From:** Previous release(1.14.0)

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Create one blob container -> Upload one file.
3. Copy the file then delete it -> Paste the file to another blob container.
4. Check the result.

**Expect Experience:**
Fail to paste.
![image](https://user-images.githubusercontent.com/41351993/88032358-6cc75580-cb70-11ea-8af4-35b5e8aa47e3.png)

**Actual Experience:**
1. Display a successful activity log.
2. The pasted file doesn't display in the destination blob container's editor.
![image](https://user-images.githubusercontent.com/41351993/88031704-87e59580-cb6f-11ea-866c-8e726c1f706b.png)

**More Info:**
1. This issue also reproduces for ADLS Gen2 blob containers.
2. This issue also reproduces when downloading one deleted blob.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240526.2. Fixed. So, we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/9010e797-a911-429b-aac6-8a8f19a80aa0)
