### ISSUE TITLE
No action 'Copy Direct Link to Blob Container' displays for one new created blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3282]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200722.6
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture:** ia32/x64
**Regression From:** Previous release(1.14.2)

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Created a new blob container -> Check its context menu.

**Expect Experience:**
The action 'Copy Direct Link to Blob Container' displays on the context menu.

**Actual Experience:**
No action 'Copy Direct Link to Blob Container' displays on the context menu.
![image](https://user-images.githubusercontent.com/41351993/88149843-33a3e980-cc33-11ea-9ba7-992d2cd83e76.png)

**More Info:**
The 'Copy Direct Link to Blob Container' displays after refreshing the Blob Containers node.

**Comment by craxal** [comment]
Related to #3273. Code that generates new blob nodes is different than code that lists blob nodes. New node code needs to be moved to the blob extension.

**Comment by v-xianya** [comment]
Verified this issue on build master/20200724.1. Fixed.
