### ISSUE TITLE
The blob name is not surrounded by quotes in 'Promote Snapshot' activity log

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3283]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200722.6
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**

1. Expand one storage account -> Blob Containers.
2. Select one blob container -> Upload one blob to it -> Create snapshots for the blob -> Manage Snapshots.
3. Select one blob snapshot -> Click 'Promote Snapshot'.
4. Check the activity log.

**Expect Experience:**
The blob name is surrounded by quotes.

**Actual Experience:**
The blob name isn't surrounded by quotes.
![image](https://user-images.githubusercontent.com/54055206/88158823-14ab5480-cc3f-11ea-9a68-580372c826c7.png)

**Comment by MRayermannMSFT** [comment]
Would like to fix this by moving our promote snapshot code to use AzCopy code path, but Azurite does not currently support put block from URL.

https://github.com/Azure/Azurite/issues/699

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240526.2. Fixed. So, we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/bf726bc0-3841-4266-874b-18af9a4f2121)
