### ISSUE TITLE
storage Explorer issue

### ISSUE THREAD

**Issue by sudhaguda** [microsoft/AzureStorageExplorer#3285]
Unable to retrieve child resources.

Details:
["Error:connect ENOENT \\\\?\\pipe\\51fe928aee3946a0ada30c54055ff8f3"]

**Comment by MRayermannMSFT** [comment]
@sudhaguda 

Can you give us some more info like:
1. What OS are you on? 
32352. What version of Storage Explorer are you using?
235. At what point in the tree did you get this error message? Expanding a subscription, Storage Account, Blob Containers?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
