### ISSUE TITLE
Unable to retrieve child resources.

### ISSUE THREAD

**Issue by NaanKaran** [microsoft/AzureStorageExplorer#3288]
Unable to retrieve child resources.

Details:
["FetchError:request to http://127.0.0.1:10000/devstoreaccount1/?include=metadata&comp=list failed, reason: connect ECONNREFUSED 127.0.0.1:10000"]

**Comment by MRayermannMSFT** [comment]
Hi @NaanKaran
1. Do you have proxy settings enabled in Storage Explorer?
2. Do you have proxy settings enabled for your OS?
2. Have you tried more than once?
3. Which emulator are you using?
4. If you are using the .NET Emulator can you try using Azurite?
4. Which version of the emulator are you using?
5. What version of Storage Explorer are you using?
6. Are you on Windows, macOS, or Linux?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
