### ISSUE TITLE
Update the localized action 'Clone with New Name' to 'Clone' for file shares in non-EUN

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3289]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200723.3
**Branch**: master
**Language**: All 
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '한국어' -> Restart Storage Explorer.
3. Expand one storage account -> File Shares.
4. Open one file share -> Check toolbar. 
5. Select one file/folder -> Check its context menu.

**Expect Experience:**
Show a localized action 'Clone'.
![image](https://user-images.githubusercontent.com/54055206/88270362-1ab93800-cd08-11ea-85cf-c979d4c3b3d2.png)

**Actual Experience:**
Show a localized action 'Clone with New Name'.
![image](https://user-images.githubusercontent.com/54055206/88270356-18ef7480-cd08-11ea-957b-e61c07ffea2b.png)

**More Info:**
1. This issue doesn't reproduce on one file share's context menu.
2. This issue doesn't reproduce for one blob container.

**Comment by cristianosuzuki77** [comment]
I'm the loc pm. I'll address this issue. Please to tag me in future loc issues.

**Comment by v-xianya** [comment]
Verified this issue on build 20200924.2. Fixed.
