### ISSUE TITLE
Opening one attached table with SAS doesn't display the notification after renaming the original table

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#329]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Windows 10
**Architecture**: ia32
**Build Number**: 20180619.1
**Commit**: 3b2233d5
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Go to Subscription -> Storage Accounts.
2. Attach one table with SAS -> Rename the original table after attaching successfully -> Try to open the attached table.
3. Check whether the notification displays or not.

#### Expected Experience: ####
The notification "the table does not exist" displays.
![notification](https://user-images.githubusercontent.com/34729022/41644105-b5d44cb4-745c-11e8-914e-8b7b0fff2b8e.png)

#### Actual Experience: ####
No notification doesn't display after opening the attached table.

#### More info: ####
1. This issue also reproduces for blob container and file share.
2. The notification displays well after opening the attached table more times.

**Comment by craxal** [comment]
Explain more about what happens. Does an editor open up successfully? What's the SAS in question?

**Comment by v-xuanzh** [comment]
Yes. The editor of attached table is opened successfully after renaming the original table. But no data dispalys on the table editor. 

More info: 
The notification<The table does not exist> will pop up after opening the attached table more times.

The attached SAS: https://apec.table.core.windows.net/amy?st=2018-06-25T10%3A28%3A42Z&se=2018-06-26T10%3A28%3A42Z&sp=ra&sv=2017-07-29&tn=amy&sig=2BggBk1h0Kl8AwgHBu6dX6Lp0ZIxRoQv1p0sy0M94vQ%3D

**Comment by craxal** [comment]
What's the time frame we're looking at? Do you open the editor within just seconds of the rename? What if you wait for about a minute?

**Comment by v-xuanzh** [comment]
Yes, I opened the attached table within just seconds of the rename. 
This issue doesn't reproduce after waiting for about 2 minutes.

**Comment by craxal** [comment]
Then my guess is the platform just takes a minute or two to delete the old-name table. The SAS is trying to access a deleted table, and the error message is expected.
