### ISSUE TITLE
No information bar pops up after switching to one deleted directory for ADLS Gen2 blob containers

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3291]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 202000724.1
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Create a new folder -> Open the folder.
3. Click 'Back' -> Delete the folder.
4. Click 'Recent Locations' -> Select the deleted folder.
5. Check the result.

**Expect Experience:**
Pop up an information bar. Like below:
![image](https://user-images.githubusercontent.com/41351993/88357039-72a17e80-cd9c-11ea-9479-7d38248d7689.png)

**Actual Experience:**
No information bar pops up and the deleted folder name shows well in the path.

**More Info:**
For file shares, the below information bar pops up after executing the steps.
![image](https://user-images.githubusercontent.com/41351993/88357161-e6438b80-cd9c-11ea-9bfb-28e399d991bf.png)

**Comment by MRayermannMSFT** [comment]
The service doesn't return an error if we browse to a directory that doesn't exist. This is similar to the blobs experience, which ADLS Gen2 is related to. Additionally, once at a nonexistent directory, the user is able to do things like uploading files.
