### ISSUE TITLE
The 'Copy' action is enabled for one blob under Azure AD attached blob containers

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3293]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200724.1
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture**: ia32/x64
**Regression From:** Previous release(1.14.2)

**Steps to reproduce:**

1. Select one blob container.
2. Give RBAC access to the blob container 'Blob Data Owner Role'.
3. Attach this blob container via Azure Active Directory (Azure AD).
4. Open the attached blob container -> Check whether the 'Copy' action is disabled or not.

**Expect Experience:**
The 'Copy' action is disabled.

**Actual Experience:**

1. The 'Copy' action is enabled.
2. Pop up an error dialog when clicking the 'Copy' action.
![image](https://user-images.githubusercontent.com/54055206/88376547-34be4d80-cdd0-11ea-9a9c-c91fa3d74776.png)

**More Info:**

1. This issue also reproduces for one Azure AD attached ADLS Gen2 blob containers.
2. The 'Copy' button is disabled in Release 1.14.2:

![image](https://user-images.githubusercontent.com/54055206/88376670-75b66200-cdd0-11ea-8963-22b2a9790bfb.png)

**Comment by MRayermannMSFT** [comment]
By design.
