### ISSUE TITLE
"Device authentication is required" error when trying add account with MFA on Ubuntu 16.04

### ISSUE THREAD

**Issue by Triamus** [microsoft/AzureStorageExplorer#3298]
**Storage Explorer Version**: 1.14.2
**Build Number**: 20200715.2
**Platform/OS**: Linux Ubuntu 16.04
**Architecture**: x64
**Regression From**:  No

## Bug Description ##
When trying to add Azure account in storage explorer UI it directs me to corporate page where I sign in and MFA is triggered and approved on mobile device. Following error is thrown:

```
{
  "message": "\"AADSTS50097: Device authentication is required.\\r\\nTrace ID: aadd274d-4965-413f-b811-88f68ec34a00\\r\\nCorrelation ID: afc3a753-cfbb-43c5-997d-2e4f86eec46a\\r\\nTimestamp: 2020-07-27 09:01:27Z\""
}
```

## Steps to Reproduce ##
Go to `Manage Accounts` and hit `Add an account`. Select `Add an Azure account` and select `Azure environment` as `Azure`. Finish authentication in browser and approve MFA triggered request in azure authenticator mobile app.

## Expected Experience ##
Successful login.

## Actual Experience ##
Error as shown above.

## Additional Context ##
No proxy or network limitations.
I also ran `snap connect storage-explorer:password-manager-service :password-manager-service`.

**Comment by MRayermannMSFT** [comment]
@Triamus, this is a requirement from your organization (who you work for, who owns a tenant you're signing into). The default sign in library used by Storage Explorer doesn't support this scenario, but our next library (currently in preview) does. You can enable it by going to Settings -> Application -> Sign In -> Enable Microsoft Authentication Library (preview).

A big caveat to this though. **I don't know if this will work on Linux?** Please let us know if it does, but my guess is it won't. I'll double check on our side if there's anything we can do to support it if so. But if not, you'll most likely be restricted to using Windows, unless you can talk to your organization and figure out a way to let you uses Linux.

**Comment by Triamus** [comment]
@MRayermannMSFT sorry I didn't get it. What is the org requirement that you are talking about? The MFA of course is a requirement and I also perform it. It just errors. The preview might be an option but I'm not too keen to use it at this stage.

**Comment by MRayermannMSFT** [comment]
@Triamus the error "Device authentication is required" means that your organization (the company you work for, whoever owns the tenant your account belongs to) requires your device to be domain joined. Also, I did some more research, I don't think checking domain joined status is supported on Linux. So you'll either need to use a different OS or talk to your organization admins to figure out how you can use Linux.

Feel free to still try the preview auth library though. It may work out.

**Comment by MRayermannMSFT** [comment]
We're going to go ahead and close this issue now. As we said, device authentication is not supported for Ubuntu. If you'd like more help, we'd recommend either raising an Azure support ticket or talking to your tenant admin.
