### ISSUE TITLE
Display 'off' for 'BlobPublicAccess' on blob container's properties dialog when 'Public Read Access' is off

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3301]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200725.1
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Create one blob container then right click it  -> Select 'Set Public Access Level...' -> Select 'No public access' -> Click 'Apply'.
3. Observe the value of ‘Public Read Access’ on Properties panel.
4. Open the blob container's properties dialog -> Observe the value of property 'BlobPublicAccess'.

**Expect Experience:**
Display 'off' instead of blank for 'BlobPublicAccess' on blob container's properties dialog.

**Actual Experience:**
Display blank for 'BlobPublicAccess' on blob container's properties dialog.
![image](https://user-images.githubusercontent.com/41351993/88527405-caa3e380-d02f-11ea-950c-53e963091e18.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
