### ISSUE TITLE
No error detail shows in the activity log when pasting one deleted file share

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3305]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200728.2
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture**: ia32/x64
**Regression From:** Previous release(1.14.2)

**Steps to reproduce:**
1. Expand one storage account -> File Shares.
2. Create a file share -> Copy the file share then delete it.
3. Paste the file share to another storage account.
4. Check the activity log.

**Expect Experience:**
Show error detail in the activity log.
![image](https://user-images.githubusercontent.com/41351993/88638125-a1498d00-d0ed-11ea-885a-e59d7e4ff11c.png)

**Actual Experience:**
No error detail shows in the activity log.
![image](https://user-images.githubusercontent.com/41351993/88637662-0a7cd080-d0ed-11ea-9277-ef82d0ed9aeb.png)

**Comment by v-limu** [comment]
**More Info:**
This issue also reproduces when pasting one existing file share.
![image](https://user-images.githubusercontent.com/54055206/88897382-bbb27080-d27d-11ea-8b16-3028153e1838.png)

**Comment by v-xianya** [comment]
Verified this issue on build master 20200804.6. Fixed
