### ISSUE TITLE
1Gb large file fails to upload

### ISSUE THREAD

**Issue by yoktan** [microsoft/AzureStorageExplorer#3309]
**Storage Explorer Version**: 1.14.2
**AZCopy Version**: 10.5.0
**AZCopy Settings**: all NULL except for SAS Duration which is set to 30
**Build Number**: 20200715.2
**Platform/OS**: macOS
**Architecture**: I guess x64 (recent Mac)

## Bug Description ##
Uploading a 1Gb file into a blob container fails: shows activity but never finishes

## Steps to Reproduce ##
I tried 2 methods:
A1. Upload directly into a specific blob
A2. Choose to overwrite the existing file there (a small 2Mb file)

and

B1. Upload a full directory/folder to the root

## Expected Experience ##
Finish uploading

## Actual Experience ##
The app shows activity:
- Uploading using SAS (and in the case of uploading a directory, it states: "using SAS, discovery completed")
- Upload speed changes constantly from 4 to 5 Mbps (so it definitely looks like something is happening)
- But next to that speed reading it forever just states "1%"
- After 2 or 3 hours nothing is changed from the above…
- It's only 1Gb so at 4 Mbps it should have finished a long time ago

**UPDATE** After running for 5 hours now, and reporting speeds of 4 to Mbps, the progress meter displays only 5%… – this is only a 1 Gb file… If I upload it via HTTP to a website, it takes only 10-20 minutes max.

## Additional Context ##
Note: I know nothing about Azure protocols or tech. So if you ask me to provide additional info, please let me know how to retrieve this info if it's not obvious.

Thanks!

**Comment by MRayermannMSFT** [comment]
@yoktan 
- how fast is your network's upload speed?
- can you try changing AzCopy concurrency to be "Adjust dynamically" and make sure all other settings are blank except for SAS duration.
- if the upload still doesn't finish in a reasonable time after trying that, can you share your AzCopy log with us? You can find it under `~/.azcopy/logs`. The most recent log will be for the most recent operation.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
