### ISSUE TITLE
Issue while opening containers in storage explorer

### ISSUE THREAD

**Issue by shibashish13999** [microsoft/AzureStorageExplorer#3312]
The requested action could not be completed.

Details:
["FetchError:request to https://azureermmachinelestorage.blob.core.windows.net/?include=metadata&comp=list failed, reason: unable to get local issuer certificate"]

**Comment by jinglouMSFT** [comment]
Could you try to follow the troubleshooting guide here to see if you can isolate and fix the issue?  https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#error-self-signed-certificate-in-certificate-chain-and-similar-errors

**Comment by igitur** [comment]
We have a proxy that intercepts and replaces the certificates. I'm pretty sure I imported all the required certificates as per the instructions mentioned in that link. But I still get the error.

Firstly, it would be nice if Azure Storage Explorer could show the certificate chain and where exactly in the chain the failure is. That would help me narrow down if I have to reimport or am missing any certificates.

**Comment by igitur** [comment]
Here are the first few lines op my openssl output:
```
[] C:\>openssl.exe
OpenSSL> s_client -showcerts -connect microsoft.com:443
CONNECTED(000001C0)
depth=1 C = US, ST = Washington, L = Redmond, O = Microsoft Corporation, OU = Microsoft IT, CN = Microsoft IT TLS CA 1
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = microsoft.com
verify return:1
```
I can paste the full output, but I'm unsure whether that contains sensitive information.

**Comment by MRayermannMSFT** [comment]
@igitur did you also enable proxy settings in storage explorer?

**Comment by igitur** [comment]
> @igitur did you also enable proxy settings in storage explorer?

Hi, yes, proxy settings are populated correctly.

**Comment by MRayermannMSFT** [comment]
> It would be nice if Azure Storage Explorer could show the certificate chain and where exactly in the chain the failure is. That would help me narrow down if I have to reimport or am missing any certificates.

Agreed. Unfortunately NodeJS doesn't tell us what cert is causing problems. 

> I can paste the full output, but I'm unsure whether that contains sensitive information.

You can email the full output to sehelp at microsoft.com. Please include your issue number in the subject line. Thanks!

**Comment by igitur** [comment]
I think I've managed to solve this. I did a few things and I'm not sure exactly which (if not all of them) are required:

- The steps outlined [here](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#error-self-signed-certificate-in-certificate-chain-and-similar-errors) mentions only the `*.microsoft.com` domain (and subdomains). I also had to view my certificate chain for my actual Azure app (e.g. https://myappname.blob.core.windows.net ) and retrieve the CA certificates in that chain. 
- Even though the link explicitly states that I should have saved the certificates as `Base-64 encoded X.509 (.cer)` I think I originally saved them as binary .cer files. I re-retrieved them as Base-64 encoded ones.

I imported all the .cer files into Azure Storage Explorer and that solved my `unable to get local issuer certificate` problem. In hindsight, the steps may have been obvious, but hopefully this is useful for someone else.

**Comment by MRayermannMSFT** [comment]
@igitur thank you so much for the detailed write-up. These cert issues are the hardest ones for us to help y'all fix, and unfortunately switching our networking stack to help reduce these errors is still just slightly out of reach.

We'll probably incorporate some of what you've said into our troubleshooting guide.

Thank you again so much, truly. 😊

**Comment by backerman** [comment]
Can this issue be fixed by just using the system certificate store? It seems like there are already packages to do that in npm. Using the system store would be extremely helpful for the aforementioned intercepting proxy as well as disconnected environments.

**Comment by MRayermannMSFT** [comment]
@backerman can you point us to the packages you are referring to?

Pretty soon here, we're going to start migrating to the Electron Net module: https://www.electronjs.org/docs/api/net. That will get us the cert stuff AND better support for other proxy types.

**Comment by backerman** [comment]
> @backerman Brad Ackerman FTE can you point us to the packages you are referring to?

[win-ca][1], [mac-ca][2], [linux-ca][3] - but having built-in support in Electron is even better.

[1]: https://www.npmjs.com/package/win-ca
[2]: https://www.npmjs.com/package/mac-ca
[3]: https://www.npmjs.com/package/linux-ca

**Comment by MRayermannMSFT** [comment]
> but having built-in support in Electron is even better.

Glad you agree! Starting with 1.20 we'll have the option to go through the electron (aka chromium) networking stack. That should mean (for most people), no more entering in proxy hostnames, importing certificates, etc.

The reason I say for most people is that not all of our features will support that option. 😢  But we're working on it!

**Comment by MRayermannMSFT** [comment]
I'm going to close this issue now. Once 1.20 is shipped, new proxy documentation will be going live. This documentation includes the advice given by @igitur. Additionally, we'll be adding a new option to "Use System Proxy". This new option will also be covered in the documentation update.

The system proxy option will, in short, have Storage Explorer make HTTP requests via the Chromium networking stack. This will enable, among other things, automatic usage of the OS SSL certificate store!

That said, this feature will initially be in a preview state. Not all of Storage Explorer's features are ready to take advantage of this new feature. We will be continuing to work on that. You can roughly track the progress of that work, with these issues:

- #4475
- #4474
- #4483
