### ISSUE TITLE
Get Subscriptions Failure Details

### ISSUE THREAD

**Issue by GaleMacp** [microsoft/AzureStorageExplorer#3315]
Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: f2baf195-6705-441b-912a-3b2997d976fd, Error: {
  "name": "Error",
  "message": "self signed certificate in certificate chain",
  "stack": "Error: self signed certificate in certificate chain\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1331:34)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at TLSSocket.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at TLSSocket.emit (events.js:210:5)\n    at TLSSocket._finishInit (_tls_wrap.js:804:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:618:12)",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}

**Comment by MRayermannMSFT** [comment]
@galemacp can you try following this guide and let us know if it helps?

https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C1804#error-self-signed-certificate-in-certificate-chain-and-similar-errors

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
