### ISSUE TITLE
issue when opening containers in storage explorer

### ISSUE THREAD

**Issue by lrh-albert** [microsoft/AzureStorageExplorer#3317]
After being connected into azure storage using SAS, error below occurred when I was opening Blob Containers inside of this azure storage. There should be 2 blob containers there, yet, either of them was listed in storage explorer.

`"FetchError:request to https://albpjsain01template50.blob.core.windows.net/?sv=2019-12-12&ss=bfqt&srt=sco&sp=rwdlacupx&se=2020-07-30T09:51:49Z&st=2020-07-30T01:51:49Z&spr=https&sig=kQ9NtpDDyOEIKIBYHgikNT07AA3vuTclWBOHJ%2Fw2Hew%3D&include=metadata&comp=list failed, reason: connect ECONNREFUSED 52.239.145.132:443"`

**Comment by jinglouMSFT** [comment]
The error message indicated that the connection was refused.  What permissions do you have?

**Comment by lrh-albert** [comment]
this issue just fixed after changing tenant id, thanks!
