### ISSUE TITLE
No 'Upload Conflict' dialog pops up when uploading an exist large blob 

### ISSUE THREAD

**Issue by v-haiz** [Microsoft/AzureStorageExplorer#332]
**Storage Explorer Version**: 1.2.0
**Platform**: Windows 10
**Architecture**: ia32
**Build Number**: 20180619.1
**Commit**: 3b2233d5
**Regression From**: This issue doesn't reproduce on released Storage Explorer 20180605.1.

**Steps to Reproduce**:
1. Launch Storage Explorer. Go to (subscription) > Storage Accounts.
2. Choose one blob container which contains a large blob at least. Upload an existing large blob.
3. Check whether the 'Upload Conflict' dialog pops up or not.

**Expected Experience**:
The 'Upload Conflict' dialog pops up.
![expect](https://user-images.githubusercontent.com/37653604/41649106-40ae1196-746a-11e8-9956-2b3bf103111e.png)

**Actual Experience**:
No 'Upload Conflict' dialog pops up and fails to upload the existing large blob with the below error .
![actual3](https://user-images.githubusercontent.com/37653604/41649258-b439af30-746a-11e8-8fd4-418a208f84ec.PNG)

**Comment by JasonYeMSFT** [comment]
Hi @v-haiz ,

Does this only happen on "large" blobs? And in terms of "large", could you please give us some size threshold so we can reproduce this bug?

**Comment by v-haiz** [comment]
Yes, JasonYeMSFT, this only happen on large blobs, you can reproduce this bug through using about 30GB. Yesterday, I use the blob size of 30GB and use blobs more than 30GB also reproduce this bug.

**Comment by craxal** [comment]
@v-haiz Can you share with us what you find when clicking **Details...**? The error information there can help us pinpoint the problem.

**Comment by v-haiz** [comment]
Below is the picture when clicking **Details...**

**Comment by MRayermannMSFT** [comment]
Bug reported as fixed. Closing.

**Comment by jinglouMSFT** [comment]
JasonYeMSFT fixed it. Should be in 1.3.0.

**Comment by craxal** [comment]
Awesome.

@v-haiz When sharing errors like this, you can just click the **Copy Details and Report Issue to GitHub** button to copy the text to your clipboard. Then you can paste it right here. No screenshots necessary!

**Comment by v-haiz** [comment]
@craxal OK, thanks for your friendly reminder.
