### ISSUE TITLE
'Download' action is enabled under a new path which created in one file share's address bar 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3320]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200730.1
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one storage account -> File Shares.
2. Open one file share -> Upload folders and files to it.
3. Type a new name in address bar -> Press 'Enter' -> Click 'Close' in the popped information bar.
4. Check the toolbar.

**Expect Experience:**
'Download' is disabled.

**Actual Experience:**
'Download' is enabled.
![image](https://user-images.githubusercontent.com/54055206/88902912-65e1c680-d285-11ea-890f-bc7a266c285a.png)

**More Info:**

1. This issue also reproduces for 'Open'/ 'Copy'/ 'Clone'/ 'Delete' actions.
2. Show a failed activity log after executing the actions.
3. This issue doesn't reproduce after manually refreshing.
4. This issue doesn't reproduce for one blob container.
![image](https://user-images.githubusercontent.com/54055206/88902967-7bef8700-d285-11ea-9f88-aca001efe2f5.png)

**Comment by craxal** [comment]
In the past, we would kill the editor entirely if the user tried navigating to a nonexistent folder. This is not a good experience. However, we don't yet have a mechanism for communicating whether the current path is valid or not. We'll need to investigate for a potential solution.

**Comment by craxal** [comment]
The affected commands rely on changes to the list view model, but for some reason, those updates aren't triggered if an error is caught while fetching items in `FileListViewModel`. It seems the codepath that handles errors in `FileListViewModel` interrupts the normal page refresh flow.
