### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by Karthik-Nagendiran** [microsoft/AzureStorageExplorer#3321]
Whenever opening Azure storage explorer getting the following error, even though my credentials are already saved in it.

Unable to retrieve child resources.

Details:
["Error:Unable to retrieve authentication token."]

**Comment by MRayermannMSFT** [comment]
@Karthik-Nagendiran at what point in the tree are you getting the error? Or in other words, after expanding what node are you seeing this error?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
