### ISSUE TITLE
'Snapshots View' doesn't display when clicking 'View Share Snapshots' under one folder

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3323]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200730.1
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ macOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Previous release(1.14.2)

**Steps to reproduce:**

1. Expand one storage account -> File Shares.
2. Open the file share -> Create a new folder.
3. **Open the folder** -> **Click 'View Share Snapshots' under the folder.**
4. Check the result.

**Expect Experience:**
'Snapshots View' display well.

**Actual Experience:**
'Snapshots View' doesn't display.

**Comment by craxal** [comment]
Duplicate of #3268.

**Comment by v-limu** [comment]
Hi @craxal 
Snapshot View shows when directly clicking the 'View Share Snapshots' action. But it doesn't show when clicking the action **under one folder.**

**Comment by craxal** [comment]
@v-limu Understood. I'll reopen, but I have a PR out that should fix this.
