### ISSUE TITLE
Unable to retrieve child resources (proxy issue)

### ISSUE THREAD

**Issue by TamasSzerb** [microsoft/AzureStorageExplorer#3325]
**Storage Explorer Version**: 1.14.2
**Build Number**: 20200715.2
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  first version tried

## Steps to Reproduce ##

launching azurite installed from npm install -g azurite in WSL then:
`$ azurite --location $HOME/azurite --debug $HOME/log/azurite.log`
`Azurite Blob service is starting at http://127.0.0.1:10000`
`Azurite Blob service is successfully listening at http://127.0.0.1:10000`
`Azurite Queue service is starting at http://127.0.0.1:10001`
`Azurite Queue service is successfully listening at http://127.0.0.1:10001`

then launching Azure Storage Explorer in the host Win10, clicking on power plug icon "Open Connect Dialog", selecting "Attach to a local emulator", clicking on "Next" button, entering "Display name": azurite (instead of local-1), leaving "Blobs port" 10000, and "Queues port" 10001, "Tables port" 10002 as default, clicking "Next" button. then displaying those setting, clicking "Connect".

It displays the new "azurite" connection properties:

Primary Key: Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
Primary Connection String: AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=http;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;

Expanding on "Blob Containers" subsection in tree of connection of "azurite", then clicking on "load more" which reports the error: 

Unable to retrieve child resources.

Details:
`
["RestError:<!DOCTYPE html>\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\n<body>\n</body>\n</html>"]
`
No proxy set in Storage Explorer in its settings.

## Expected Experience ##
having data without error message

## Actual Experience ##
I suspect that Storage Explorer does not connect to locally running azurite because I see no access in azurite stdout, but I can hit it by hand. After a while I fugured out that I got similar error message on _ANY_ port:

`$ curl localhost:32465`
`<!DOCTYPE html>`
`<html xmlns="http://www.w3.org/1999/xhtml">`
`<body>`
`</body>`

Which indicates, that since the desktop is behind of corporate proxy, the response is above provided by it. So the Storage Explorer however not set, but using system setting's proxy.

## Additional Context ##
azurite runs in Windows 10 WSL, Storage Explorer in native Windows, but same happens with VS Code's Azurite plugin.

Please advise.

**Comment by TamasSzerb** [comment]
We need a proxy settings, where Storage Explorer does not inherit the Windows10's system settings for proxy, because now we cannot turn off completely the use of proxy.

**Comment by MRayermannMSFT** [comment]
@ TamasSzerb can you check your Windows environment variable setting and see if you have a environment variable/s called HTTP_PROXY or HTTPS_PROXY?

**Comment by TamasSzerb** [comment]
@MRayermannMSFT thank you, this workaround is working for me. When we can expect the fix for "Do not use proxy" to indeed not use proxy? Now, it's misleading.

**Comment by MRayermannMSFT** [comment]
@TamasSzerb unfortunately this behavior has been around for quite a while. It is only recently that we've seen issues arising from it. So we're taking our time to figure out how we want to address it without breaking anyone who has been relying on it. So I don't have an ETA to share with you right now.
