### ISSUE TITLE
 User with UPN suffix changed will not able to login (enter ADFS authentication loop)

### ISSUE THREAD

**Issue by IamVincentLin** [Microsoft/AzureStorageExplorer#333]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Windows 10 Version 1703 (OS Build : 15063.1155)
**Architecture**: ia32
**Regression From**: n/a

#### Steps to Reproduce: ####
1. Setup a AAD : e.g. vilinlab1.onmicrosoft.com
2. Setup two custom domain: 
   - vilin.msftonlinelab.com
   - vilinlab1.cu.cc
3. Setup AAD Connect to federate with On-Prem's ADFS server with custom domain (vilin.msftonlinelab.com)
4. Setup one user so the UPN is like  - e.g. vilin@vilin.msftonlinelab.com
5. Install Azure Storage Explorer and login with vilin@vilin.msftonlinelab.com ---> it works fine
6. Run AAD Connect again to change the federation domain to vilinlab1.cu.cc
7. Change the user UPN suffix -- e.g.  vilin@vilin.msftonlinelab.com to vilin@vilinlab1.cu.cc
8.  Confirm the modification has been synced to Azure AD
9. When the access/refresh token expired, open Azure Storage Explorer again. in account tab , it will be  prompted to reenter the credentials. However when we reenter the credential. It will enter the following loop:
   a.  enter vilin@vilinlab1.cu.cc
   b.  it will redirect to ADFS for authentication & enter password
   c.  wait for a while, it will still show redirecting to your organization then redirect to ADFS again.
   d. after enter credential, it will still be redirected to ADFS again.
10. If we login the user - vilin@vilinlab1.cu.cc on other windows machine. It works fine so it should not be Azure AD or ADFS issue
11. try to uninstall/reinstall Azure Storage Explorer on problematic client. The issue still occurs.

#### Expected Experience: ####

After we change the user's UPN suffix, we should still able to login with new UPN

#### Actual Experience: ####

User will not able to login with new UPN and it enters loop for ADFS authentication

**Comment by IamVincentLin** [comment]
Could you help on this issue? I also try to perform the below actions but I can only perform the #1/#2.
I cannot find the files in #3 so the issue still occurs, please advise it. Thanks

Cleaning up Cache files (Windows) 
1.	Make sure you have installed latest version of Storage Explorer.  
2.	Navigate to %appData%/StorageExplorer.  Delete the contents of the cache folders.  
3.	Delete the contents of sign-in cache files if the issue is related to sign in.  They are in:  
C:\users\username\.adalcache 
c:\users\username\.devaccounts 
c:\users\username\.extaccounts

**Comment by MRayermannMSFT** [comment]
If the users UPN has changed then the identity cache needs to be cleared since AAD will send the same identity GUID but different ID token content. ADAL does not note the updated UPN information and therefore does not handle updating the cache correctly. 

To clear the identity cache, close Storage Explorer and then delete %localappdata%\.identityservice. This will delete the account store and the adal cache, at which point you can try adding the account again.

**Comment by IamVincentLin** [comment]
After clearing the files in %localappdata%.identityservice, we can add the account without issue. Thanks for the information.

**Comment by MRayermannMSFT** [comment]
Closing since you became unblocked. 😄
