### ISSUE TITLE
Unable to retrieve child resources.

### ISSUE THREAD

**Issue by maninderjitsinghdhaliwal** [microsoft/AzureStorageExplorer#3330]
Unable to retrieve child resources.

Details:
["RestError:﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.\nRequestId:71ead8f0-f01e-0117-7f4d-683cd2000000\nTime:2020-08-01T21:46:11.7295001Z</Message></Error>"]

**Comment by MRayermannMSFT** [comment]
@maninderjitsinghdhaliwal  how are you connecting to your storage? 
- Sign in and then look at resources under a subscription?
- Attach with SAS?
- Attach with key?
- Attach with Azure AD?

Also, what type of resources are you trying to work with?

**Comment by maninderjitsinghdhaliwal** [comment]
I am using Azure Storage explorer. I use to work few days ago.

**Comment by MRayermannMSFT** [comment]
@maninderjitsinghdhaliwal, please answer my questions from above. Without this information I cannot help you. 🙂

How are you connecting to your storage? 
- Sign in and then look at resources under a subscription?
- Attach with SAS?
- Attach with key?
- Attach with Azure AD?

Also:
- what type of resources are you trying to work with?
- what version of Storage Explorer are you using?

**Comment by maninderjitsinghdhaliwal** [comment]
i open Azure Storage Explorer.
It ask to sign in so i sign in with microsoft account. 
it loads subscriptions then i am trying to open blobs in my MSDN subscription and it do not let me and the error i pasted in the original message

**Comment by MRayermannMSFT** [comment]
@maninderjitsinghdhaliwal, at what point in the tree are you seeing the error? Is it:
- after expanding the subscription
- after expanding "Storage Accounts"
- after expanding a specific storage account
- after expanding "Blob Containers"

?

**Comment by maninderjitsinghdhaliwal** [comment]
Here

[A screenshot of a social media post  Description automatically generated]

**Comment by MRayermannMSFT** [comment]
@maninderjitsinghdhaliwal if you want to share a screenshot on github you'll need to do it via the website. Not via email.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having issues please open a new issue.
