### ISSUE TITLE
Failed to create blob containers

### ISSUE THREAD

**Issue by lhf552004** [microsoft/AzureStorageExplorer#3331]
**Storage Explorer Version**: 1.14.2
**Build Number**: 20200715.2
**Platform/OS**:  Windows 10
**Architecture**:  x64
**Regression From**:  First time to use

## Bug Description ##
Failed to create blob container.
Zscaler makes the internet safe for businesses by protecting their employees from malware, viruses, and other security threats

## Steps to Reproduce ##
1.  Launch Azurite via command line: azurite --silent --location c:\azurite --debug c:\azurite\debug.log
2.  Launch Azure Storage Explorer
3.  Create container on emulater.

## Expected Experience ##
A document images container is expected to create.

## Actual Experience ##
Popup an error, says failed to create blob container.
![image](https://user-images.githubusercontent.com/10030850/89139509-72aa3700-d571-11ea-9791-86777aad3e58.png)

**Comment by MRayermannMSFT** [comment]
@lhf552004 do you have proxy settings enabled? If you don't then, can you check your Windows environment variable setting and see if you have a environment variable/s called HTTP_PROXY or HTTPS_PROXY?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.

**Comment by lhf552004** [comment]
Hi @MRayermannMSFT, yes it works! thank you. sorry delay to response.
