### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by lhf552004** [microsoft/AzureStorageExplorer#3332]
**Storage Explorer Version**: 1.14.2
**Build Number**: 20200715.2
**Platform/OS**:  Windows 10
**Architecture**:  x64
**Regression From**:  First time to use

## Bug Description ##
Unable to retrieve child resources.

Details:
["FetchError:request to http://127.0.0.1:10000/devstoreaccount1/?include=metadata&comp=list failed, reason: tunneling socket could not be established, statusCode=403"]

## What I tried
I have add access rights of my account to the folder of azurite

Strange thing is, I switch network to my hotspot of my phone, It pop up an error says timeout to connect 10.10.5.18, which is our company's proxy. I have reset my internet options. And I also close proxy settings of the explorer. The question is where is the proxy setting from?
 
![image](https://user-images.githubusercontent.com/10030850/89141422-2d890380-d577-11ea-9182-f9a3cfe20cc6.png)
![image](https://user-images.githubusercontent.com/10030850/89141466-498ca500-d577-11ea-9660-d575303f48aa.png)

**Comment by MRayermannMSFT** [comment]
@lhf552004 can you check your Windows environment variable setting and see if you have a environment variable/s called HTTP_PROXY or HTTPS_PROXY?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
