### ISSUE TITLE
It would be better to update 'OK' to 'Move' on the 'Move Files' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3333]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200801.4
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create one blob container -> Upload one file -> Click 'Move'.
3. Check the 'Move Files' dialog.

**Expect Experience:**
Display 'Remove' instead of 'OK' on the dialog.

**Actual Experience:**
Display 'OK' on the dialog.

**More Info:**
1. It would be better to update 'OK' to 'Rename' on rename dialog.
2. The screenshot of the 'Move' dialog for one ADLS Gen1 file.
![image](https://user-images.githubusercontent.com/41351993/89151865-77341700-d594-11ea-9866-5c9a438f2c87.png)

**Comment by v-limu** [comment]
Verified on build 20200804.5. This issue has been fixed. so close it.
