### ISSUE TITLE
Show an activity log against creating action when deleting one blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3334]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200801.4
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one storage account -> Blob Containers.
2. Select one blob container -> Delete the blob container.
3. Check its activity log.

**Expect Experience:**
Show an activity log against deleting action. 

**Actual Experience:**
Show an activity log against creating action.
![image](https://user-images.githubusercontent.com/41351993/89150964-62568400-d592-11ea-9f55-4e9bed428d45.png)

**Comment by v-limu** [comment]
Verified on build 20200804.5. This issue has been fixed. so close it.
