### ISSUE TITLE
Disable the 'OK' button on 'Move Files' dialog when the destination directory is not valid

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3335]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200801.4
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create one blob container -> Upload one file -> Click 'Move'.
3. Check the 'OK' button on the Move Files dialog.

**Expect Experience:**
The 'OK' button is disabled.

**Actual Experience:**
The 'OK' button is enabled.
![image](https://user-images.githubusercontent.com/41351993/89151512-bb72e780-d593-11ea-95a9-76478ec8bab1.png)

**Comment by v-limu** [comment]
Verified on build 20200804.5. This issue has been fixed. so close it.
