### ISSUE TITLE
Add a colon mark next to the string 'Destination directory' on the 'Move Files' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3336]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200801.4
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create one blob container -> Upload one file -> Click 'Move'.
3. Check whether a colon mark shows next to the string 'Destination directory'.

**Expect Experience:**
Show a colon mark next to the string 'Destination directory'.

**Actual Experience:**
No colon mark shows to the string 'Destination directory'.
![image](https://user-images.githubusercontent.com/41351993/89151026-8dd96e80-d592-11ea-9061-0fd2444ce085.png)

**Comment by v-limu** [comment]
Verified on build 20200804.5. This issue has been fixed. so close it.
