### ISSUE TITLE
The descriptions of the error details are incorrect when moving one file to an invalid directory

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3338]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200801.4
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create one blob container -> Upload one file -> Click '**Move**'.
3. Type an invalid path in the 'Destination directory'.
4. Click the 'Details... ' next to the failed activity log -> Check the description. 

**Expect Experience:**
Show a correct description.

**Actual Experience:**
Show an incorrect description.
![image](https://user-images.githubusercontent.com/54055206/89167995-be2f0600-d5ae-11ea-925a-36e4fc554e13.png)
![image](https://user-images.githubusercontent.com/54055206/89168001-bff8c980-d5ae-11ea-889a-afe0b2cae79d.png)

**Comment by MRayermannMSFT** [comment]
Both are errors returned by the service. Won't fix for nwo
