### ISSUE TITLE
some GUI issues with Input box for Gremlin code (CosmosDB Graph) in Storage Explorer

### ISSUE THREAD

**Issue by y-dima** [microsoft/AzureStorageExplorer#3339]
**Storage Explorer Version**: 1.14.2
**Build Number**: 20200715.2
**Platform/OS**: Windows 10
**Architecture**: ia32

## Bug Description ##
Input box for Gremlin code is too small and its size dose not change with the change of the Storage Explorer window size. 
Input box is a singe line and I cannot see my code even if it is relatively short. 
There are no scroll bars to see the code comfortably. 
The [x] button that clears the script covers part of the code and I cannot see entered text.

## Steps to Reproduce ##
Enter any sufficiently long text in the query box for CosmosDB Graph API.

## Expected Experience ##
1) Query text box should be changed to the multi-line text area;
2) The size of the query text box should change with the change of size of the main window;
3) The [x] clear text button should be located near query box, not inside of it.
4) The input text area for the code should contain scroll bars.

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
