### ISSUE TITLE
It would be nice to update the title of move dialog from 'Move Files' dialog to 'Move'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3341]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200804.6
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create one blob container -> Upload one file to the blob container.
3. Create a new folder.
4. Select the uploaded file and the created folder -> Click 'Move' button.
5. Check the title of the popped dialog.

**Expect Experience:**
It would be nice to display 'Move' as the title.

**Actual Experience:**
Display 'Move Files' as the title.

**Comment by MRayermannMSFT** [comment]
Won't fixing.
