### ISSUE TITLE
Display a duplicate folder after selecting 'Do not upload' on the pasting conflict dialog for ADLS Gen1 file systems

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3343]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200804.6
**Branch**: master
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand 'Data Lake Storage Gen1(Preview)' node -> Open one file system.
2. Upload one folder which contains files.
3. Copy the folder and paste it to the same destination.
4. Select 'Do not upload' on the popped conflict dialog -> Click 'Apply to All'.
5. Check the result.

**Expect Experience:**
No duplicate folder displays.

**Actual Experience:**
Display a duplicate folder on the editor.
![image](https://user-images.githubusercontent.com/41351993/89281366-9017f780-d67c-11ea-87b3-ae2d37e45e6e.png)

**More Info:**
This issue also reproduces after closing the popped conflict dialog.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220902.1. Fixed. So, we are going to close this issue.
