### ISSUE TITLE
Keep a consistent behavior in the 'Move Messages' dialog between SAS attached queues and Azure AD attached queues

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3348]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200804.19
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one storage account -> Queues.
2. Create a new queue -> Attach it via SAS -> Open the attached queue -> Click 'Move Message' -> Check the dialog.
3. Create a new queue -> Attach it via Azure Active Directory (Azure AD) -> Open the attached queue -> Click 'Move Message' 
  -> Check the dialog.

**Expect Experience:**
Keep a consistent behavior in the 'Move Message' dialog.

**Actual Experience:**
Show an inconsistent behaviors in the 'Move Message' dialog.
1. The queues show in the 'Move Message' dialog for one Azure AD attached queue.
2. Do not show the queues and unable to search for one SAS attached queue.

   ![image](https://user-images.githubusercontent.com/54055206/89397095-fc106380-d741-11ea-99f5-d2f60ffe4324.png)

**Comment by MRayermannMSFT** [comment]
Move messages is going to be disabled if the queue is attached with a SAS URI.

**Comment by v-xianya** [comment]
@MRayermannMSFT Is it actionable to disable 'Move Messages' for  Azure AD attached queue?
The current screenshot of Move Messages dialog for one Azure AD attached queue.
![image](https://user-images.githubusercontent.com/41351993/89484695-9c619900-d7d1-11ea-911e-21dbc849e690.png)
