### ISSUE TITLE
The action 'Change Access Tier...' is enabled when selecting more than one Append blob

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3349]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200804.19
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Previous release(1.14.2)

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Create one blob container -> Upload two blobs as **Append** blob.
3. Select the two **Append** blobs -> Right click the selected blobs.
4. Check the state of the action 'Change Access Tier...' on the context menu.

**Expect Experience:**
The action 'Change Access Tier...' is disabled.
![image](https://user-images.githubusercontent.com/41351993/89397614-a5eff000-d742-11ea-943f-63bc4129d570.png)

**Actual Experience:**
The action 'Change Access Tier...' is enabled and can be executed successfully.
![image](https://user-images.githubusercontent.com/41351993/89397735-cc159000-d742-11ea-85b6-8539af571337.png)

**More Info:**
This issue also reproduces for Page blobs.

**Comment by v-xianya** [comment]
Hi @JasonYeMSFT 
Verified this issue on build master/20200812.2. 

The action 'Change Access Tier...' is enabled when selecting one Page/ (Append) blob and one Block blob.
This issue also reproduces when selection Page/ (Append) blobs and Folders.
![image](https://user-images.githubusercontent.com/41351993/89969842-f8249a00-dc89-11ea-847b-937c7a5eff9c.png)

**Comment by JasonYeMSFT** [comment]
@v-xianya The current behavior is by design. The intention is to not block users when their selection include blobs that don't have access tier. If they change access tier on them, those blobs will be ignored.

**Comment by v-xianya** [comment]
@JasonYeMSFT OK, thank you for the clarifying. We are going to close this issue.
