### ISSUE TITLE
Storage Explorer unable to open File Shares

### ISSUE THREAD

**Issue by ahughes584** [microsoft/AzureStorageExplorer#3352]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:

**Comment by MRayermannMSFT** [comment]
@ahughes584 please fill out the issue template and describe your issue. Thanks!

**Comment by MRayermannMSFT** [comment]
@ahughes584 since you haven't filled out the template we are going to close this. Please open a new issue if you are still having problems.
