### ISSUE TITLE
The path on one file share's snapshot view is changed after clicking the 'Restore Down' button

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3354]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200806.6
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Previous release(1.14.2)

**Steps to reproduce:**
1. Expand one storage account -> File Shares.
2. Create a file share -> Click 'View Share Snapshots' button on its toolbar -> Observe the path.
3. Click 'Restore Down' button on the top-right corner.
4. Observe the path.

**Expect Experience:**
The path is not changed.

**Actual Experience:**
The path is changed.
![image](https://user-images.githubusercontent.com/41351993/89507452-1bb99180-d7ff-11ea-8724-0786f4b64d0d.png)

**More Info:**
1. This issue also reproduces by clicking '**Zoom In**' or '**Zoom Out**'.
2. This issue also reproduces when closing snapshots view in the state that the path shows 'Snapshots for fileshare'.
![image](https://user-images.githubusercontent.com/41351993/89507677-6c30ef00-d7ff-11ea-9d0c-bf9727fc2f52.png)

**Comment by craxal** [comment]
There is a PR already in the works that addresses this issue.

**Comment by v-xianya** [comment]
Verified this issue on build master/20200807.6. Fixed.
