### ISSUE TITLE
Put the error message in the activity log when dragging and dropping files to the file share snapshot's editor

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3355]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200806.6
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> File Shares.
2. Create a file share -> Click 'View Share Snapshots' button on its toolbar.
3. Drag and drop one file to the current editor -> Check the result.

**Expect Experience:**
The error message shows in the activity log.

**Actual Experience:**
The error message shows in an information bar.
![image](https://user-images.githubusercontent.com/41351993/89508692-da29e600-d800-11ea-95d9-91fdce620f9c.png)

**More Info:**
For blobs, the error message shows in the activity log.
![image](https://user-images.githubusercontent.com/41351993/89508703-dd24d680-d800-11ea-968a-c8b557048fe5.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into main
