### ISSUE TITLE
Show an incorrect message after pasting one file's URI into the connect dialog and changing 'sr' value from 'f' to 's'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3356]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200806.6
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Previous release (1.12.0)

**Steps to reproduce:**
1. Expand one storage account -> File Shares.
2. Create a file share -> Upload one file.
3. Right click the file -> Click 'Get Shared Access Signature...' -> Copy the URI.
4. Open the connect dialog -> Select 'Use a shared access signature (SAS) URI' -> Paste the URI.
5. Change the '**sr**' value to '**s**' -> Check the result.

**Expect Experience:**
No message shows. 

The screenshot in version 1.12.0.
![image](https://user-images.githubusercontent.com/41351993/89511094-05fa9b00-d804-11ea-9d39-1eb2ac490f73.png)

**Actual Experience:**
Show an incorrect message.
![image](https://user-images.githubusercontent.com/41351993/89511017-ecf1ea00-d803-11ea-816d-f7e251c2211d.png)

**Comment by craxal** [comment]
@v-xianya The original behavior is actually a bug. You should not be able to use a SAS URI pointing to a file to connect to a share. We'll fix the error message.

**Comment by v-xianya** [comment]
Hi @craxal Thanks for the updates. 
Verified this issue on build master/20200807.4. The error message makes sense now.
![image](https://user-images.githubusercontent.com/41351993/89599754-ff673480-d892-11ea-95be-1555dda3d4bc.png)
