### ISSUE TITLE
The URL of the ADLS Gen2 folder shows incorrectly in the 'Properties' dialog

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3357]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200806.6
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a new blob container -> Create a new folder -> Click 'Properties' in the toolbar.
3. Check the URL in the dialog.

**Expect Experience:**
The URL shows correctly in the 'Properties' dialog.
![image](https://user-images.githubusercontent.com/54055206/89512592-0431d700-d806-11ea-8213-47ed29c6bf83.png)
**Actual Experience:**
The URL shows incorrectly in the 'Properties' dialog.
![image](https://user-images.githubusercontent.com/54055206/89512634-11e75c80-d806-11ea-9ae0-1ec74fbe2cb2.png)

**Comment by MRayermannMSFT** [comment]
gen2 apis -> use dfs endpoint -> folders only real in gen2 apis
blob apis -> use blob endpoint -> folders not real in blob apis

So for a folder, showing dfs endpoint makes sense. 

Once interop supports folder properties, we can move the impl of "show folder properties" to using the blob SDK, and this URL will change to be a blob endpoint URL.

@craxal should check with platform team if interop supports folder properties yet.

**Comment by MRayermannMSFT** [comment]
Related to #3056

**Comment by craxal** [comment]
Currently communicating with the client library team to understand the expected behavior of @azure/storage-blob and @azure/storage-file-datalake. We currently use @azure/storage-blob to list blobs for both standard and ADLS Gen2 blob containers. It does return last modified properties for blob items, but not for blob prefixes (folders).

**Comment by craxal** [comment]
According to the client library team, the blobs library does support folder properties; folders are grouped with other blobs and have a special property.

**Comment by MRayermannMSFT** [comment]
Am going to move manage properties for gen2 paths to blob ext. And for gen2, we will show both blob and dfs paths.

**Comment by MRayermannMSFT** [comment]
All gen2 property dialogs show now include a DFS and a Blob url.

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT thanks for the update! Now there are both DFS & Blob URL properties for one ADLS Gen2 file. 
What would be the exact URL when using the action 'Copy URL'?

**Comment by MRayermannMSFT** [comment]
It should be the blob URL, both for gen2 and blobs.
