### ISSUE TITLE
Succeed to paste one deleted table

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3358]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200806.6
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one storage account -> Tables.
2. Create a new table -> Copy the table then delete it -> paste the table to another account.
3. Check the result.

**Expect Experience:**
Fail to paste the deleted table.

**Actual Experience:**

1. Show a failed activity log.
![image](https://user-images.githubusercontent.com/54055206/89513005-94701c00-d806-11ea-91f1-7cebebfd9d6a.png)
2. The deleted table shows in the destination accounts.
![image](https://user-images.githubusercontent.com/54055206/89513011-976b0c80-d806-11ea-9165-fcd408539d81.png)

**More Info:**
This issue doesn't reproduce for one blob container/ file share.

**Comment by MRayermannMSFT** [comment]
Ideally we would split out activities showing that creating the new table was successful, but that copying the entities over failed. Or before attempting anything we could double check that the source table still exists. 

For now, the failure in the activity log is good enough for tables.
