### ISSUE TITLE
Unable to Import or delete files within Azure Storage Explorer

### ISSUE THREAD

**Issue by KaraboM2** [microsoft/AzureStorageExplorer#3359]
**Storage Explorer Version**:  10.5.0
**Build Number**:  20200715.2 (Help > About) version 1.15.2
**Platform/OS**:  Windows 10 -- 1909
**Architecture**: -- i86 
## Bug Description ##
{
  "message": "\"Authentication Failed. The SAS is not correct or expired or does not have the correct permission ->
 github.com/Azure/azure-storage-blob-go/azblob.newStorageError, 
/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42\\n===== RESPONSE ERROR (ServiceCode=AuthorizationPermissionMismatch) =====\\nDescription=This request is not authorized to perform this operation using this permission.\\nRequestId:###########\\nTime:2020-08-05T15:36:31.4921673Z,
 Details: \\n   Code: AuthorizationPermissionMismatch\\n  
 DELETE https:"SAS URL"REDACTED-&sr=c&sv=2015-04-05&timeout=901\\n   User-Agent: [Microsoft Azure Storage Explorer, 1.14.2, win32,  AzCopy/10.5.0 Azure-Storage/0.10 (go1.13; Windows_NT)]\\n   X-Ms-Client-Request-Id: [#####]\\n   X-Ms-Version: [2019-02-02]\\n   --------------------------------------------------------------------------------\\n   RESPONSE Status: 403 This request is not authorized to perform this operation using this permission.\\n   Content-Length: [279]\\n   Content-Type: [application/xml]\\n   Date: [Wed, 05 Aug 2020 15:36:30 GMT]\\n   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]\\n   X-Ms-Client-Request-Id: [#########\\n   X-Ms-Error-Code: [AuthorizationPermissionMismatch]\\n   X-Ms-Request-Id: [##########]\\n   X-Ms-Version: [2019-02-02]\\n\\n\\n\""
}

## Steps to Reproduce ##
 1. Login to Azure Storage Explorer using SAS URL 
 2. I get this error when I try to delete any item with the ingestadata blob storage 
 3. I also can no longer see PST files I import using Azure Storage AzCopy

## Expected Experience ##
I expect to delete any file without error within a blob storage
Also I expect all PST files imported to Azure Storage Explorer to appear there

## Actual Experience ##
I can't deleted any files that currently residing within Azure Storage Explorer 

## Additional Context ##
I have an open proxy

**Comment by jinglouMSFT** [comment]
The error indicated that your authentication failed. So several things to check.  Make sure you actually have the permission to delete, your proxy settings are set correctly. Most likely you didn't have the delete permission when you attached using SAS URL. Can you double check?  Thanks.

**Comment by JasonYeMSFT** [comment]
@KaraboM2 To check your SAS permissions, look for the "d" permission in the "sp" parameter in your SAS url.
What do you mean by "import"? Do you mean "upload"? Are you saying that you aren't able to import files or you are not seeing the imported files?

**Comment by KaraboM2** [comment]
@jinglouMSFT funny thing is I do have the permission to delete - I was able to delete some objects within the blob storage a few days back

@JasonYeMSFT  I can confirm that I do have the proper permission - I have read, write & delete permission for an administrator.  Import = Upload, I'm not see any  files I'm importing into Microsoft Azure Storage Explorer. Privously I was I able to all my imported/uploaded files within MS ASE

**Comment by KaraboM2** [comment]
@jinglouMSFT funny thing is I do have the permission to delete - I was able to delete some objects within the blob storage a few days back. My proxy does allow communication between Microsoft Azure and my on prem environment

@JasonYeMSFT I can confirm that I do have the proper permissions - I have read, write & delete permissions for an administrator. Import = Upload, I'm not seeing any 'new' files I'm importing into Microsoft Azure Storage Explorer. Previously I was able to view all my imported/uploaded files within MS ASE

**Comment by MRayermannMSFT** [comment]
@KaraboM2 it sounds most likely that your SAS has expired. Can you check the expiration time of the SAS. It should be near something like `se=<date time here>`.

**Comment by KaraboM2** [comment]
@MRayermannMSFT I have restarted my machine and all services running on it, also I logged out of my Azure portal then logged back in - I still get "The SAS is not correct or expired or does not have the correct permission" - error every time

**Comment by MRayermannMSFT** [comment]
@KaraboM2 it sounds most likely that your SAS has expired. Can you check the expiration time of the SAS. It should be near something like se=<date time here>. For example:

https://someaccount.blob.core.windows.net/bc13?sv=2019-07-07&st=2020-08-17T18%3A04%3A38Z&**se=2020-08-18T18%3A04%3A38Z**&sr=c&sp=rl&sig=E%2FcQFDAFSsefsBGkHfe%2FBDea%2BF4to40kRk%3D

That bold part is what we are looking for. If you have `%3A` in the URL, you can treat those as :, so:
`2020-08-18T18%3A04%3A38Z` is `2020-08-18T18:04:38Z`.

Ok?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having issues please open a new issue.
