### ISSUE TITLE
Disable the 'Clone' action when using "." as the new name for one blob

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3361]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200806.6
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Previous release (1.14.2)

**Steps to reproduce:**
1. Expand one storage account -> Blob containers.
2. Create a blob container -> Upload one blob.
3. Clone the blob with name '.' -> Check the result.

**Expect Experience:**
The action can't be completed.
![image](https://user-images.githubusercontent.com/41351993/89517333-23336780-d80c-11ea-84c5-827c2fa2f239.png)

**Actual Experience:**
1. Show a successful activity log.
![image](https://user-images.githubusercontent.com/41351993/89518524-98536c80-d80d-11ea-8a09-799eec6c1102.png)

2. Show an extra folder with empty name and contains the original blob.
![image](https://user-images.githubusercontent.com/41351993/89518606-b751fe80-d80d-11ea-8611-1f98f3365b42.png)

    <1>. Show the below behavior after opening the extra folder.
   ![image](https://user-images.githubusercontent.com/41351993/89518719-e4061600-d80d-11ea-9ec3-3b9678a61646.png)

**More Info:**
1. For blobs under one folder, succeed to clone and no extra folder shows.
![image](https://user-images.githubusercontent.com/41351993/89523388-55959280-d815-11ea-877d-9aba27c6a493.png)

2. For folders. The behaviors as below:
On version 1.15.0 - dev
![image](https://user-images.githubusercontent.com/41351993/89524422-21bb6c80-d817-11ea-8335-15301199d72c.png)

   On version 1.14.2
  ![image](https://user-images.githubusercontent.com/41351993/89525831-621bea00-d819-11ea-8df2-d0c06794f800.png)

    On version 1.11.2
    ![image](https://user-images.githubusercontent.com/41351993/89524269-d6a15980-d816-11ea-88eb-925db51cd4a6.png)

**Comment by MRayermannMSFT** [comment]
Related to #3363

**Comment by v-xianya** [comment]
Verified this issue on build 20201116.2. fixed.
![image](https://user-images.githubusercontent.com/41351993/99205530-c32d6380-27f3-11eb-9769-eb3cc431f529.png)

**Comment by v-xianya** [comment]
Verified this issue on build 20201118.2. Fixed.
