### ISSUE TITLE
The table auto refresh after canceling the file import 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3362]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200806.6
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one storage account -> Tables.
2. Create a new table -> Click 'Import' action in the toolbar -> Click 'Cancel' button in the file explorer.
3. Check the result.

**Expect Experience:**
The table doesn't refresh. 
(Unnecessary auto refreshing will make the table loading a long time when one table has a large number of entities).

**Actual Experience:**
The table auto refresh.

**Comment by MRayermannMSFT** [comment]
Won't fix. Minor table issue.
