### ISSUE TITLE
Copy Paste RAW Names from Tree view

### ISSUE THREAD

**Issue by vkuehn** [microsoft/AzureStorageExplorer#3364]
**Is your feature request related to a problem? Please describe.**
Sometimes in a Dialog with Colleges just the Name of a container is needed but there is no context menu for that

**Describe the solution you'd like**
Right click "copy Name as text" or even as az cli command list or what ever programing tool is currently wanted

**Describe alternatives you've considered**
copy direct link but that is to much fiddling

**Additional context**
probably not needed

**Comment by MRayermannMSFT** [comment]
@vkuehn for now, I'd recommend looking in the properties grid in the bottom left. Some resource types have a dedicated "name" property, while others have a URL, which you can pretty easily extract the name from.

**Comment by vkuehn** [comment]
Thanks adding it to the list !

**Comment by vkuehn** [comment]
Thanks for the work but I am closing this as there is now a StorageExplorer in the Azure Frontend (Beta) which works fine for me.
Thought that is the location where all tools should reside
