### ISSUE TITLE
The 'Conflict' dialog doesn't pop up after uploading an existing blob

### ISSUE THREAD

**Issue by v-xinda** [microsoft/AzureStorageExplorer#3365]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200807.6
**Branch**: master
**Platform/OS:** Windows 10 / CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Previous release(1.14.2)

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob to it -> Upload the blob to same destination again.
3. Check the result.

**Expect Experience:**
Pop up the 'Conflict' dialog.

**Actual Experience:**
The 'Conflict' dialog doesn't pop up.

**More Info:**
This issue doesn't reproduce for the File Shares.

**Comment by v-limu** [comment]
Verified on build 20200807.13. This issue has been fixed.
