### ISSUE TITLE
The added metadata is not preserved in Properties dialog for the cloned blob container

### ISSUE THREAD

**Issue by v-xinda** [microsoft/AzureStorageExplorer#3366]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200807.6
**Branch**: master
**Platform/OS:** Windows 10 / CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one regular storage account -> Blob Containers.
2. Right click the Blob Containers -> Click 'Properties...' -> Add metadata -> Save.
3. Clone this blob container with a new name.
4. Check the properties for the cloned blob container.

**Expect Experience:**
The added metadata shows well in Properties dialog.

**Actual Experience:**
The added metadata is not preserved in Properties dialog.

**More Info:**
1. This issue doesn't reproduce for the emulator blob container.
2. This issue doesn't reproduce when copying the blob container.

**Comment by MRayermannMSFT** [comment]
1. Determine if actually not a regression. Use the portal to test against old versions of storage explorer. The portal also has the ability to look at container metadata. So validate if on container clone we have always not preserved if.
2. If not a regression, remove milestone to triage again.
3. If regression, fix for 1.15.

**Comment by craxal** [comment]
The issue appears to be that `canCopyProperties` is not defined when `Azure.Storage.BlobContainer.renameContainer` is called. I don't think this is a regression, but the fix is small.
