### ISSUE TITLE
Keep a consistent result when using a name ended with whitespaces to clone one blob for the emulator and regular blob container

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3367]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200807.6
**Branch**: master
**Platform/OS:** Windows 10
**Emulator**: 5.10.0.0
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**

1. Install and run Emulator -> Launch Storage Explorer.
2. Open one emulator blob container -> Clone one blob -> Add whitespaces append to the default blob name in the clone 
  dialog -> Click 'Clone' -> Check the result.
3. Open one regular blob container -> Clone one blob -> Add whitespaces append to the default blob name in the clone 
  dialog -> Click 'Clone' -> Check the result. 

**Expect Experience:**
Keep a consistent result for the emulator and regular blob container.

**Actual Experience:**
Show inconsistent results.
1. The cloned blob which name ended with whitespaces shows well in the editor for the regular blob container.

2. Pop up an error dialog for the emulator blob container.
![image](https://user-images.githubusercontent.com/54055206/89626854-97cddb00-d8cc-11ea-8ada-581c4fbb0a8e.png)

**More Info:**
The cloned file which name ended with whitespaces shows well in the editor for one file share.

**Comment by MRayermannMSFT** [comment]
Won't fix because:
- this is an emulator exclusive issue
- for clone, emulator is still using our JS code path
- adding whitespaces to the end of a blob name is a bit of an edge case
