### ISSUE TITLE
There are a part of strings not localized in Services part of Settings panel

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3368]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200807.6
**Branch**: master
**Language**: Chinese(ZH-CN)/ Turkish/ Russian/ Portuguese (Portugal)/Japanese/ Italian/ French/ Czech
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文（简体）' -> Restart Storage Explorer.
3. Open 'Settings' -> Check whether all the strings in 'Services' part are localized or not.

**Expect Experience:**
All the strings that need to be localized are localized.

**Actual Experience:**' 
The strings 'Enable ADLS Gen2 snapshots (preview)' and its descriptions are not localized.
![image](https://user-images.githubusercontent.com/41351993/89629576-9ef6e800-d8d0-11ea-92ab-d063cd6d68f0.png)

**Comment by cristianosuzuki77** [comment]
I'm the loc pm. I'll address this issue. Please to tag me in future loc issues.

**Comment by cristianosuzuki77** [comment]
The string was recently marked by developer as not for translation (see the <cmt>):
![image](https://user-images.githubusercontent.com/18152472/91491794-6e6bf380-e869-11ea-801b-52c54033993a.png)

The translation was performed few months ago but this comment prevents the translations from being returned.

@craxal could you please triage with your team?

**Comment by craxal** [comment]
Ah, that's right. The string is temporary. When ADLS Gen 2 snapshots is made GA, we will remove the setting and permanently enable the feature.

@v-xianya This is intentional; we won't be fixing.
