### ISSUE TITLE
Feature Request: Add 'Documents' to graph collections

### ISSUE THREAD

**Issue by ChiefWiggum** [microsoft/AzureStorageExplorer#337]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Windows 10

#### Feature Request ####
CosmosDB collections of the type _graph_ currently only show in the menu a "graph" view that allows the user to query the graph with gremlin queries, but not "Documents" option which allows us to use "sql" queries, even though the azure portal allows us both query types.

**Comment by ziyel** [comment]
@ChiefWiggum Thanks a lot for your feedback.
Add the SQL query tab to the graph account has already in our backlog. We will prioritize it.

**Comment by ChiefWiggum** [comment]
Any update on this?
I found the following [here](https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/33767920-storage-explorer-cosmos-db-graph-api-show-docu):

> There is a workaround if you use the documents endpoint in the Azure storage explorer. This will let you see the Documents.

But I fail to understand what they mean by this.

**Comment by jinglouMSFT** [comment]
CosmosDB has been removed from Storage Explorer.
