### ISSUE TITLE
Facing issue while Upload and Downlaod of data from Storage explorer.

### ISSUE THREAD

**Issue by Sandeepjhanwar** [microsoft/AzureStorageExplorer#3370]
**Storage Explorer Version**: <1.13.1>
**Build Number**: <20200515.1>
**Platform/OS**: < Windows 10?>
**Architecture**: <x64>
**Regression From**:  <Was working in same version but issue started recently >

## Bug Description ##
Issue while downloading and uploading file from storage explorer

## Steps to Reproduce ##
1. Select any file/folder from container 
2. Press download

## Expected Experience ##
File should be downloaded properly

## Actual Experience ##
Download failed with error message in log:: JobID=963fe84c-c4ca-724b-7658-8240f2e683c9, Part#=0 failed to refresh token, please check error details and try to log in with azcopy login command again. (Error details: get cached token failed in Token Store Mode(SE), segmented token broken, failed to read azcopy/***token/6832/10, Element not found.)

## Additional Context ##
Same issue is occured while upload, if I am trying to download and upload file from azure portal its working fine

**Comment by MRayermannMSFT** [comment]
@Sandeepjhanwar has downloading with Storage Explorerr worked before the past for you?

Can you please do the following:

0. close storage explorer
1. win + r
2. type in `rundll32.exe keymgr.dll,KRShowKeyMgr` then hit enter
3. look for any entries like `azcopy/aadtoken/...`
4. remove those entries

And then try doing the operation again?

**Comment by MRayermannMSFT** [comment]
Also, please update to the latest version if possible.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having issues please open a new issue.
