### ISSUE TITLE
Can MAC use RBAC to login to Azure fileshare 

### ISSUE THREAD

**Issue by Hundet** [microsoft/AzureStorageExplorer#3371]
I'm trying to connect Mac 10.12 and 10.15 to an Azure File Share using RBAC authentication.  Everything works perfectly on Windows 10 PC's so I know the RBAC setup is correct and working.

I can connect to the Azure share with the master key, but that of course circumvents my user permissions.  I've had a ticket open with MS for over 2 weeks, but we are not getting anywhere.  I'm looking for any ideas.

**Comment by MRayermannMSFT** [comment]
@Hundet the answer kind of depends on what you mean by RBAC. All storage services support RBAC at the management layer. As in, you can have an RBAC role which grants you access to the account key, and then you can use the key to authenticate against the data layer.

Only blobs and queues support RBAC at the data layer. As in, you can have an RBAC role which grants you access to blob container/s.

This is true regardless of OS.

So I'm not sure how your RBAC was working on Windows. Can you share what roles you have for your storage account?

**Comment by MRayermannMSFT** [comment]
@Hundet are you using Storage Explorer? This GitHub repo is for issues with the Storage Explorer desktop tool.

**Comment by MRayermannMSFT** [comment]
It doesn't seem like this is related to Storage Explorer. If it is, please open a new issue with more information describing how it is. Thanks.

**Comment by Hundet** [comment]
Close the ticket.  I e given up on file storage in Azure.
