### ISSUE TITLE
Can't delete or copy files using Microsoft Azure Storage Explorer

### ISSUE THREAD

**Issue by boe1** [microsoft/AzureStorageExplorer#3372]
**Storage Explorer Version**: 
1.14.2
**Build Number**: 
20200715.2
**Platform/OS**: 
Windows 10 1903
**Architecture**: 
ia32
**Regression From**:  

## Bug Description ##
Can't download, upload or delete using microsoft storage explorer

## Steps to Reproduce ##
Open Storage explorer
Open Connect Dialog
Click the button for use a shared access signature URL
Paste in the address from protection.office.com /information governance/ import pst
I can see the files I was able to copy using azcopy (not storage explorer) In storage accounts, attached, blob, blob name
I drag a file to the screen, it says copy, it prompts if I want to overwrite - doesn't matter no previous file of that name
Transfer of filename failed - used sas
I click on one of the files that was placed there using azcopy - deletion of file completed - 0 completed

## Expected Experience ##
I expected when I click on a file to delete it would delete the file
I expected when I copied a file to the folder it would show up there after a refresh

## Actual Experience ##
Nothing happened - files can't be created nor destroyed - I think that is a law by Newton or Lavoisier

## Additional Context ##
AZcopy works

**Comment by MRayermannMSFT** [comment]
@boe1, can you please share your SAS with us?

**IMPORTANT**: **PLEASE REDACT THE SIG BEFORE SHARING THE SAS WITH US**

So we're looking for this:

sv=2019-02-02&ss=btqf&srt=sco&st=2020-08-10T17%3A26%3A01Z&se=2020-08-11T17%3A26%3A01Z&sp=rl&sig=REDACTED

**IMPORTANT**: **PLEASE REDACT THE SIG BEFORE SHARING THE SAS WITH US**

Also to confirm, you're saying that even if there is not a file with the same name you are still seeing the conflict dialog?

**Comment by boe1** [comment]
I'd love to give my info but not sure how to set it for redacted.
My sas looks something like
sv=2015-04-05&sr=c&si=IngestionSasForAzCopy202007251302322396&sig=hcdubpTQpiTG4zmRD0fvTNrKlauXXXXXXXXXXXXXXXXXXXX&se=2020-09-04T19%XXXX%XXXXX  

My url looks something like - https://XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.blob.core.windows.net/ingestiondata 

(this is according to the properties listed at the bottom of MASE

I am not copying a file that is in conflict however before you even start a copy it will ask you what to do in the event of a conflict so what I'm saying is it doesn't matter.


I just dragged a pdf from my computer (that is not in the the blob yet) and dragged it to the Microsoft Azure Storage explorer
It gives me a choice
Storage Access Policy Detected
Staroage Explorer cannot determine what permissions have been granted to by your SAS token because the permissions are provided by a stored access policy.    These permissions affect AZCopy's ability to prompt for conflicts and validate data integrity at the end of each transfer.  How would you like to proceed?
Prompt for conflicts or overwrite - doesn't matter which I select it will still fail.

Here are the contents of that log file with some info xxxed out
2020/08/10 20:59:00 AzcopyVersion  10.5.0
2020/08/10 20:59:00 OS-Environment  windows
2020/08/10 20:59:00 OS-Architecture  amd64
2020/08/10 20:59:00 Log times are in UTC. Local time is 10 Aug 2020 13:59:00
2020/08/10 20:59:00 Job-Command copy C:\Users\XXXXXX\Desktop\16LED-instructions-Sample[1064].pdf https://XXXXXXXXXXXXXXXXXXX.blob.core.windows.net/ingestiondata/16LED-instructions-Sample%5B1064%5D.pdf?se=2020-09-04t19%3A48%3A20z&si=ingestionsasforazcopy202007251302322396&sig=-REDACTED-&sr=c&sv=2015-04-05 --output-type=json --cancel-from-stdin --overwrite=prompt --from-to=LocalBlob --blob-type Detect --follow-symlinks --check-length=true --put-md5 --follow-symlinks --recursive 
2020/08/10 20:59:00 Number of CPUs: 12
2020/08/10 20:59:00 Max file buffer RAM 6.000 GB
2020/08/10 20:59:00 Max concurrent network operations: 192 (Based on number of CPUs. Set AZCOPY_CONCURRENCY_VALUE environment variable to override)
2020/08/10 20:59:00 Check CPU usage when dynamically tuning concurrency: true (Based on hard-coded default. Set AZCOPY_TUNE_TO_CPU environment variable to true or false override)
2020/08/10 20:59:00 Max concurrent transfer initiation routines: 64 (Based on hard-coded default. Set AZCOPY_CONCURRENT_FILES environment variable to override)
2020/08/10 20:59:00 Max enumeration routines: 16 (Based on hard-coded default. Set AZCOPY_CONCURRENT_SCAN environment variable to override)
2020/08/10 20:59:00 Parallelize getting file properties (file.Stat): false (Based on AZCOPY_PARALLEL_STAT_FILES environment variable)
2020/08/10 20:59:00 Max open files when downloading: 2147483048 (auto-computed)
2020/08/10 20:59:00 ISO 8601 START TIME: to copy files that changed after this job started, use the parameter --include-after=2020-08-10T20:58:55Z
2020/08/10 20:59:00 Any empty folders will not be processed, because source and/or destination doesn't have full folder support
2020/08/10 20:59:00 JobID=f980c2a7-1914-9444-5d2b-deeceed90f80, credential type: Anonymous
2020/08/10 20:59:00 scheduling JobID=f980c2a7-1914-9444-5d2b-deeceed90f80, Part#=0, Transfer#=0, priority=0
2020/08/10 20:59:00 Final job part has been scheduled
2020/08/10 20:59:00 Final job part has been created
2020/08/10 20:59:00 PERF: primary performance constraint is Unknown. States: X:  0, O:  0, M:  0, L:  0, R:  0, D:  0, W:  0, F:  0, B:  0, E:  0, T:  0, GRs: 14
2020/08/10 20:59:00 0.0 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total, 
2020/08/10 20:59:00 INFO: [P#0-T#0] has worker 63 which is processing TRANSFER
2020/08/10 20:59:00 INFO: [P#0-T#0] Starting transfer: Source "%5C%5C?\\C:\\Users\\XXXXXXX\\Desktop\\16LED-instructions-Sample[1064].pdf" Destination "https://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.blob.core.windows.net/ingestiondata/16LED-instructions-Sample%5B1064%5D.pdf?se=2020-09-04t19%3A48%3A20z&si=ingestionsasforazcopy202007251302322396&sig=-REDACTED-&sr=c&sv=2015-04-05". Specified chunk size 8388608
2020/08/10 20:59:00 ==> REQUEST/RESPONSE (Try=1/69.0495ms, OpTime=298.8072ms) -- RESPONSE STATUS CODE ERROR
   HEAD https://XXXXXXXXXXXXXXXXXXXXXXXXXX.blob.core.windows.net/ingestiondata/16LED-instructions-Sample%5B1064%5D.pdf?se=2020-09-04t19%3A48%3A20z&si=ingestionsasforazcopy202007251302322396&sig=-REDACTED-&sr=c&sv=2015-04-05&timeout=901
   User-Agent: [Microsoft Azure Storage Explorer, 1.14.2, win32,  AzCopy/10.5.0 Azure-Storage/0.10 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [30a569e3-ede8-4939-4406-555d78a05275]
   X-Ms-Version: [2019-02-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation using this permission.
   Date: [Mon, 10 Aug 2020 20:59:01 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   Vary: [Origin]
   X-Ms-Client-Request-Id: [30a569e3-ede8-4939-4406-555d78a05275]
   X-Ms-Error-Code: [AuthorizationPermissionMismatch]
   X-Ms-Request-Id: [7f68cfec-101e-003c-7659-6f5d13000000]
   X-Ms-Version: [2019-02-02]
Response Details: 

2020/08/10 20:59:00 ERR: [P#0-T#0] UPLOADFAILED: %5C%5C?\C:\Users\jmillerick\Desktop\16LED-instructions-Sample[1064].pdf : 000 : Could not check destination file existence. -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthorizationPermissionMismatch) =====
Description=403 This request is not authorized to perform this operation using this permission., Details: (none)
   HEAD https://9b59ff502a0f40c39991e32.blob.core.windows.net/ingestiondata/16LED-instructions-Sample%5B1064%5D.pdf?se=2020-09-04t19%3A48%XXXXX&si=ingestionsasforazcopy202007251302322396&sig=-REDACTED-&sr=c&sv=2015-04-05&timeout=901
   User-Agent: [Microsoft Azure Storage Explorer, 1.14.2, win32,  AzCopy/10.5.0 Azure-Storage/0.10 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [30a569e3-ede8-4939-4406-555d78a05275]
   X-Ms-Version: [2019-02-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation using this permission.
   Date: [Mon, 10 Aug 2020 20:59:01 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   Vary: [Origin]
   X-Ms-Client-Request-Id: [30a569e3-ede8-4939-4406-555d78a05275]
   X-Ms-Error-Code: [AuthorizationPermissionMismatch]
   X-Ms-Request-Id: [7f68cfec-101e-003c-7659-6f5d13000000]
   X-Ms-Version: [2019-02-02]



   Dst: https://9b59ff502a0f40c39991e32.blob.core.windows.net/ingestiondata/16LED-instructions-Sample%5B1064%5D.pdf?se=2020-09-04t19%3A48%XXXXX&si=ingestionsasforazcopy202007251302322396&sig=-REDACTED-&sr=c&sv=2015-04-05
2020/08/10 20:59:00 JobID=f980c2a7-1914-9444-5d2b-deeceed90f80, Part#=0, TransfersDone=1 of 1
2020/08/10 20:59:00 all parts of entire Job f980c2a7-1914-9444-5d2b-deeceed90f80 successfully completed, cancelled or paused
2020/08/10 20:59:02 PERF: primary performance constraint is Unknown. States: X:  0, O:  0, M:  0, L:  0, R:  0, D:  0, W:  0, F:  0, B:  0, E:  0, T:  0, GRs: 192

**Comment by MRayermannMSFT** [comment]
@boe1 for the log you shared, it looks like you chose to check for conflicts. Based on the log though, the access policy used by your SAS does not have read permissions, which means AzCopy cannot check for conflicts.

Can you please try the upload again, and when you see the "Storage Access Policy Detected" dialog, pick the option that doesn't check for conflicts. Then if the upload fails, share that AzCopy log with us.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having issues please open a new issue.
