### ISSUE TITLE
Succeed to clone one file using '\uE000' as the new name under one file share

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3374]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200807.13
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Previous release (1.13.1)

**Steps to reproduce:**
1. Expand one storage account -> File Shares.
2. Create a file share -> Upload one file and right click it -> Click 'Clone...'.
3. Enter the new name '\uE000' -> Check the result.

**Expect Experience:**
The action can't be completed.
![image](https://user-images.githubusercontent.com/41351993/89765987-f6dc5b80-db29-11ea-8ce0-c6c072b54557.png)

**Actual Experience:**
Succeed to clone and show 'uE000' as the cloned name.

![image](https://user-images.githubusercontent.com/41351993/89768111-c1397180-db2d-11ea-852b-06ebfdf6f65a.png)
![image](https://user-images.githubusercontent.com/41351993/89766765-41120c80-db2b-11ea-91a6-a0aec8e9cdf2.png)

**More Info:**
This issue also reproduces for folders under file shares.

**Comment by MRayermannMSFT** [comment]
We shouldn't allow people to use /'s in file and folder names. Especially for file shares.

**Comment by MRayermannMSFT** [comment]
Merged for 1.18
