### ISSUE TITLE
Make it possible to rename a local/attached storage account

### ISSUE THREAD

**Issue by nspiteri** [microsoft/AzureStorageExplorer#3375]
**Is your feature request related to a problem? Please describe.**
If you attach to a storage account and afterwards you want to change the name, you're unable to do it

**Describe the solution you'd like**
I'd like to be able to right click and change the storage account name

**Describe alternatives you've considered**
Detaching and attaching the storage account

**Comment by craxal** [comment]
Duplicate of #2819.
