### ISSUE TITLE
Add readonly option to access Azure storage data

### ISSUE THREAD

**Issue by pawanitbhu** [microsoft/AzureStorageExplorer#338]
**Storage Explorer Version**: 1.20
**Architecture**: ia32
**Regression From**: 

#### Steps to Reproduce: ####
1. This is an ask for new feature. The new feature is to add read-only access feature for storage explorer.

#### Expected Experience: ####
User can select if he should have readonly access or read-write.

#### Actual Experience: ####
None

**Comment by MRayermannMSFT** [comment]
@pawanitbhu if you'd like to enforce read only vs read-write, please use existing permission techniques such as:
- SAS permissions
- RBAC roles
- ACLs (if using ADLS Gen2)
