### ISSUE TITLE
Keep a consistent behavior between file shares and ADLS Gen2 blob containers when using the name 'a/b/c' to create a new folder

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3381]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200811.2
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Previous release (1.14.2)

**Steps to reproduce:**
1. Expand one ADLS Gen2 storage account -> File Shares and Blob Containers.
2. Create a file share and a blob container.
3. Click 'New Folder' both in the file share and blob container -> Input 'a/b/c' as the new folder name -> Click 'OK'.
3. Check the results.

**Expect Experience:**
Show a consistent behavior.

**Actual Experience:**
Show inconsistent behaviors.
![image](https://user-images.githubusercontent.com/41351993/89883836-4ccd0400-dbfb-11ea-98f2-6839815739c5.png)

**More Info:**
The screenshot on version: 1.14.2.
![image](https://user-images.githubusercontent.com/41351993/89883931-6b32ff80-dbfb-11ea-9f3b-e2bcc4b41b86.png)

**Comment by v-xianya** [comment]
@craxal Verified this issue on build master/20200816.2. Fixed.
Could you help to take a look a this scenario?

When using name 'a\b\c' to create a new folder.
1. For ADLS Gen2 blob containers, succeed to create a folder.
![image](https://user-images.githubusercontent.com/41351993/90350829-e1f35100-e070-11ea-88f0-24806717e859.png)

2. For File shares, fail to create a folder.
![image](https://user-images.githubusercontent.com/41351993/90350923-30085480-e071-11ea-9d79-36c521118ee7.png)

**Comment by craxal** [comment]
@v-xianya This looks like a separate issue. Can you open a new bug, try it with forward slashes, try it on multiple platforms, etc.?

**Comment by v-xianya** [comment]
@craxal Verified the issue on 3 platform, the behaviors are the same.
The new opened bug: https://github.com/microsoft/AzureStorageExplorer/issues/3415
