### ISSUE TITLE
Fail to move one ADLS Gen2 blob which name contains '#'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3383]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200811.2
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Select one blob container -> Select one blob -> Rename it with a name contains '#' (like: '**te#st**').
3. Try to move the blob to an valid folder -> Check the result.

**Expect Experience:**
Succeed to move.

**Actual Experience:**
Fail to move.
![image](https://user-images.githubusercontent.com/41351993/89995853-a9442800-dcbc-11ea-928c-15ab5d7c78a1.png)
 
Error details:
  `"message": "[{\"code\":\"InvalidSourceUri\",\"statusCode\":400,\"request\":{\"streamResponseBody\":false,\"url\":\"https://akristine0811.dfs.core.windows.net/adlsblob01/New%20Folder%2FNew%20Text%23%20Document.txt`

**More Info:**
1. This issue also reproduces for 'Rename' action.
![image](https://user-images.githubusercontent.com/41351993/89996610-967e2300-dcbd-11ea-99f3-55964d7c61aa.png)
2. This issue also reproduces for folders under ADLS Gen2 blob containers.

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
