### ISSUE TITLE
An extra action 'Set Public Access Level...' shows for one premium blob container under Quick Access

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3384]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200812.2
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**

1. Expand one premium storage account -> Blob containers.
2. Create a blob container -> Check its context menu.
3. Add the blob container to Quick Access -> Check its context menu under Quick Access.

**Expect Experience:**
No extra action 'Set Public Access Level...' shows.
![image](https://user-images.githubusercontent.com/54055206/90085626-fff84300-dd4a-11ea-814f-063bdfb6d78e.png)

**Actual Experience:**
An extra action 'Set Public Access Level...' shows.
![image](https://user-images.githubusercontent.com/54055206/90085515-c6bfd300-dd4a-11ea-929d-c11c3339e4f6.png)

**Comment by v-limu** [comment]
**More Info:**
This issue also reproduces under one Name & Key attached premium storage account.

**Comment by JasonYeMSFT** [comment]
For Quick Access container nodes, since we don't store the skuTier information of its account, we always enable the action. For Name & Key attached storage accounts, we are not loading its skuTier which is a bug we can fix.

**Comment by JasonYeMSFT** [comment]
I just found that the Account level API for getting accountKind doesn't support using just account name and account key. Move to 1.16.0 to see if we can support it via the blob SDK.

**Comment by JasonYeMSFT** [comment]
Move to 1.17.0 since this is not feasible with the current SDK.

**Comment by JasonYeMSFT** [comment]
I added attributes for such containers nodes to get skuTier and accountKind for them. Key attached storage accounts should be able to show/hide this action properly now.
