### ISSUE TITLE
Keep a consistent 'Public Read Access' value between one pasted and cloned blob container

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3385]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200812.2
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**

1. Expand one storage account -> Blob containers.
2. Create a blob container -> Set the 'Public Read Access' to 'container'.
3. Copy the blob container -> Paste it to another account -> Check the 'Public Read Access' of the **pasted blob container**.
4. Clone the blob container -> Check the 'Public Read Access' of the **cloned blob container**.

**Expect Experience:**
Keep a consistent 'Public Read Access' value between one pasted and cloned blob container

**Actual Experience:**
Show inconsistent values.

1. The 'Public Read Access' shows 'container' for the pasted blob container.
![image](https://user-images.githubusercontent.com/54055206/89996457-66368480-dcbd-11ea-9c5d-a393ed39a7aa.png)

2. The 'Public Read Access' shows 'off' for the cloned blob container. 
![image](https://user-images.githubusercontent.com/54055206/89996450-63d42a80-dcbd-11ea-9be7-ed6392d2ed87.png)

**Comment by MRayermannMSFT** [comment]
It looks like this was fixed when https://github.com/microsoft/AzureStorageExplorer/issues/3366 was fixed
