### ISSUE TITLE
The editor of one file share shows blank 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3387]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200813.4
**Branch**: master
**Platform/OS**: Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Previous release(1.14.2)

**Steps to reproduce:**

1. Expand one storage account ->File Shares.
2. Open one file share -> Check the editor.

**Expect Experience:**
The editor shows well.

**Actual Experience:**
The editor shows blank.

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
