### ISSUE TITLE
The copied URL is different from the URL in the 'Properties' dialog for one blob under SAS attached blob containers 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3388]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200813.4
**Branch**: master
**Platform/OS**: Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Previous release(1.12.0)

**Steps to reproduce:**

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob to it -> Attach the blob container via SAS.
3. Open the attached blob container -> Right click one blob -> Click 'Copy URL' -> Check the pasted URL.
4. Open the 'Properties' dialog for this blob -> Check the URL in the dialog.

**Expect Experience:**
The pasted URL is the same as the URL in the 'Properties' dialog.

**Actual Experience:**
The pasted URL is different from the URL in the 'Properties' dialog.

1. The pasted URL:
![image](https://user-images.githubusercontent.com/54055206/90116400-022cc280-dd88-11ea-8b4f-dfa72fcf857f.png)
2. The URL in the 'Properties' dialog:
![image](https://user-images.githubusercontent.com/54055206/90116453-183a8300-dd88-11ea-9346-77c83d01d332.png)

**More Info:**
1. This issue also reproduces for one SAS attached storage account.
2. This issue doesn't reproduce for one file share.

**Comment by MRayermannMSFT** [comment]
I would consider the current behavior to be more correct.
