### ISSUE TITLE
Display '<no name>' in the path of the blob when setting '//' as the uploaded blob's destination directory

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3389]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200813.4
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Previous release(1.14.2)

**Steps to reproduce:**
1. Expand one non-ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Click 'Upload' -> Select 'Upload Files...'.
3. Select one file -> Type '//' in the 'Destination directory' box -> Click 'Upload'.
4. Check the path of the uploaded blob after uploading successfully.

**Expect Experience:**
The path is normal.

**Actual Experience:**
The path is odd.
![image](https://user-images.githubusercontent.com/41351993/90119439-28ecf800-dd8c-11ea-87af-1619f81c3712.png)

**More Info:**
1. This issue also reproduces when selecting 'Upload Folder...'.
2. The screenshots on version 1.14.2 & 1.13.1.
**1.14.2**
![image](https://user-images.githubusercontent.com/41351993/90119655-694c7600-dd8c-11ea-93ca-39236c9b7ab2.png)
**1.13.1**
![image](https://user-images.githubusercontent.com/41351993/90119672-6ea9c080-dd8c-11ea-9bd3-200de0999e8a.png)

**Comment by JasonYeMSFT** [comment]
This is by design. Blob storage supports no name directories so we removed the logic to trim the duplicated "/" characters. The user needs to ensure there is no extra "/" characters which indicate no name directories.

**Comment by v-xianya** [comment]
@JasonYeMSFT Thank you for the sharing.
Colud you help to take a look at the below scenarios? Are these also by design?
1. When typing '\\' in the Destination directory:
![image](https://user-images.githubusercontent.com/41351993/90220110-1e893780-de3a-11ea-8b13-ad3fa9f4cd4f.png)
Show two layers directory <no name> against the uploaded blob.
![image](https://user-images.githubusercontent.com/41351993/90220222-5abc9800-de3a-11ea-8a1f-9c31e27208c6.png)
When typing '/' in the Destination directory:
![image](https://user-images.githubusercontent.com/41351993/90220251-6e67fe80-de3a-11ea-9af2-ff90ab3ac760.png)
Show one layer directory <no name> against the uploaded blob.
![image](https://user-images.githubusercontent.com/41351993/90220317-8c356380-de3a-11ea-8a28-b2cfcf18788c.png)

2. When creating one folder named '\\' then upload one blob to it. The uploaded blob doesn't display under the current view.
![image](https://user-images.githubusercontent.com/41351993/90220543-f9e18f80-de3a-11ea-9fd9-0c3ad2e8d2b6.png)
When creating one folder named '/' then upload one blob to it. The uploaded blob displays under the current view.
![image](https://user-images.githubusercontent.com/41351993/90220642-2b5a5b00-de3b-11ea-8813-cb20c48c971a.png)
