### ISSUE TITLE
It would be better to filter out the duplicate directories under the 'Recent locations' dropdown list

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3391]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200813.4
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one folder.
3. Open the folder for several times.
4. Click the 'Recent locations' -> Observe the dropdown list.

**Expect Experience:**
No duplicate directory shows.

**Actual Experience:**
Show duplicate directories.
![image](https://user-images.githubusercontent.com/41351993/90122042-4ff8f900-dd8f-11ea-8ba8-b9ea5ad44034.png)

**Comment by MRayermannMSFT** [comment]
The inclusion of duplicate locations is intentional. Not only are we trying to show places the user recently viewed, we're also trying to provide an exact history of what they've viewed.
