### ISSUE TITLE
Unable to download to ZFS mount using snap install

### ISSUE THREAD

**Issue by superstator** [microsoft/AzureStorageExplorer#3392]
**Storage Explorer Version**: 1.14.2
**Build Number**: 20200715.2
**Platform/OS**: Ubuntu 20.04
**Architecture**: x64
**Regression From**:  unknown

## Bug Description ##
Azure Storage Explorer snap install is unable to access zfs mounts

## Steps to Reproduce ##
Create a ZFS pool and mount, and verify access to it via other apps (terminal, GUI apps, etc)
Install storage-explorer via Snap Store
Select item in Storage Explorer and click 'Download'
File dialog appears, but any mounted ZFS filesystems are missing

## Expected Experience ##
Expect ZFS mounts/volumes to appear normally in dialog, and to be able to download data to them

## Actual Experience ##
ZFS mounts are missing. Clicking a bookmark to a ZFS mount just sends the user to /

**Comment by MRayermannMSFT** [comment]
@superstator if you try downloading a file in Chrome/Chromium, does the ZFS pool show up?

**Comment by superstator** [comment]
Yes, other apps show the ZFS pool in the file dialog and can save files there.

**Comment by MRayermannMSFT** [comment]
What other apps did you try?

**Comment by superstator** [comment]
Chrome, VSCode, RStudio, Evolution, Firefox. All can access the pool fine. So far StorageExplorer is the only place I've seen I can't access it.

**Comment by MRayermannMSFT** [comment]
Ok, thanks, we'll try to look into this when we have time.

**Comment by craxal** [comment]
[How to create a ZFS pool](https://ubuntu.com/tutorials/setup-zfs-storage-pool#1-overview)

**Comment by craxal** [comment]
@superstator Using the .tar installation, I can see a ZFS pool. I also tried connecting the `removable-media` interface, but that didn't work.

According to [this forum post](https://forum.snapcraft.io/t/vlc-cannot-play-files-on-zfs-raid-array/4624) it looks like snaps are unable to see other files systems not under the /media folder. It looks like there's a way around that limitation using `mount bind`. Maybe give that a try? I'm attempting to do the same on my end.

**Comment by craxal** [comment]
I haven't heard from the author in a while after posting about the workaround, so I'm going to close. If you encounter this problem again, please open a new issue.

**Comment by superstator** [comment]
Sorry, this has been way down my list too. I just tried your bind mount workaround and that does appear to make it visible. Thanks!
