### ISSUE TITLE
Can't change the access tiers for blobs on its folder level

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3393]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200813.10
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ macOS Catalina
**Architecture:** ia32/x64
**Regression From:** Previous build (20200813.4)

**Steps to reproduce:**

1. Expand one storage account -> Blob Containers.
2. Create one blob container -> Create one folder -> Upload files as block blob to it.
3. Right click the folder -> Select 'Change Access Tier...' -> Select one access tier -> Click 'Apply'.
4. Check the result.

**Expect Experience:**
Succeed to change the access tiers for the blobs in the folder.
![image](https://user-images.githubusercontent.com/41351993/90229544-aa0ac480-de4a-11ea-8069-7589702f5ee8.png)

**Actual Experience:**
Can't change the access tiers for the blobs in the folder.
![image](https://user-images.githubusercontent.com/41351993/90229500-97908b00-de4a-11ea-8842-14939897169a.png)

**More Info:**
Fail to change access tier when selecting more than one blob.
![image](https://user-images.githubusercontent.com/41351993/90229352-5bf5c100-de4a-11ea-8f7a-ddcb3f15b7ef.png)
Error details:
  `"message": "[{\"name\":\"RestError\",\"statusCode\":404,\"request\":{\"streamResponseBody\":false,\"url\":\"https://ayan0811.blob.core.windows.net/aaaaaaaaa/undefined?comp=tier\",\"method\":\"PUT\",\"headers\":{\"_headersMap\":{\"x-ms-access-tier\":{\"name\":\"x-ms-access-tier\",\"value\":\"Cool\"},\"x-ms-version\":{\"name\":\"x-ms-version\",\"value\":\"2019-12-12\"},\"user-agent\":{\"name\":\"user-agent\",\"value\":\"azsdk-js-storageblob/12.2.0-preview.1 (NODE-VERSION v12.13.0; Windows_NT 10.0.19041)\"},\"x-ms-client-request-id\"`

**Comment by JasonYeMSFT** [comment]
There seems to be some unpublished change for this code path. I will re-publish the package and it should be fixed.

**Comment by v-xianya** [comment]
@JasonYeMSFT Verified this issue on build master/20200818.4. Reproduce.

**Comment by v-xianya** [comment]
This issue has been fixed on build master/20200820.5. So close it.
