### ISSUE TITLE
azure storage explorer

### ISSUE THREAD

**Issue by emimassa** [microsoft/AzureStorageExplorer#3395]
**Storage Explorer Version**: 1.14.2
**Build Number**: 
**Platform/OS**:  Windows 10
**Architecture**: 
**Regression From**:  

## Bug Description ##
No se pueden recuperar los recursos secundarios.

Detalles:
["Error:connect ENOENT \\\\?\\pipe\\19dbeeaa71444ef4877103921c1506cc"]

**Comment by MRayermannMSFT** [comment]
Similar to #3285?

**Comment by MRayermannMSFT** [comment]
@emimassa

Can you give us some more info like:
-     What OS are you on?
-     What version of Storage Explorer are you using?
-     At what point in the tree did you get this error message? Expanding a subscription, Storage Account, Blob Containers?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having issues please open a new issue.
