### ISSUE TITLE
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature

### ISSUE THREAD

**Issue by SeshagiriSriram** [microsoft/AzureStorageExplorer#3396]
**Storage Explorer Version**:  1.14.2
**Build Number**: 20200715.2
**Platform/OS**: Windows 10 Professional
**Architecture**:  X64 
**Regression From**:  Not sure

## Bug Description ##
I created an IOT Edge device and deployed the Blob Storage as listed in below links: 
**Install Azure IOT Edge on Linux:** 
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux 
**Deploy Blob on IOT Edge:** 
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-deploy-blob

The account key is 64 byte length and generated via Generate Plus (https://generate.plus/en/base64) as suggested.
From Azure portal I can see the connection is correct. 

![image](https://user-images.githubusercontent.com/3693855/90300793-e7f30180-deb9-11ea-9fa2-c257b6f04dd7.png)
![image](https://user-images.githubusercontent.com/3693855/90300836-17097300-deba-11ea-88f7-4954ed2a2391.png)

When I try to view this via Storage explorer, I get following error: ```

```
Unable to retrieve child resources.
Details:
["RestError:﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:bd09a56f-a01e-00d5-7b96-7278ab000000\nTime:2020-08-14T23:59:36.1029406Z</Message><AuthenticationErrorDetail>The MAC signature found in the HTTP request '+VTwdCPyW8pFfFkx5H066znUM6HRUZCu3aoUWCOO1cA=' is not the same as any computed signature. Server used following string to sign: 'GET\n\n\n\n\n\n\n\n\n\n\n\nx-ms-client-request-id:688de322-f68b-4711-bf08-bd2eac95d18c\nx-ms-date:Fri, 14 Aug 2020 23:59:35 GMT\nx-ms-version:2019-07-07\n/localstorageaccount/\ncomp:list\ninclude:metadata'.</AuthenticationErrorDetail></Error>"]

```

## Steps to Reproduce ##
Start Storage Explorer. 
attach a new Storage account- passing Account Name/Key (or) Connection String. Connection gets added with no issues. 
Click on BloB Containers and error message will be deployed. 

## Expected Experience ##
The error should not have occurred. 

## Actual Experience ##
The error happens and one cannot view containers/files in the local storage account. 

## Additional Context ##
The iot Edge Device is running on a vagrant ubuntu box in WIndows 10 and storage explorer is invoked from Windows. I can ping to the machine and port 11002 is indeed open.

**Comment by mbialecka** [comment]
@SeshagiriSriram Connection won't work with account name/key, you need to use connection string in the format `DefaultEndpointsProtocol=http;BlobEndpoint=http://<host device name>:11002/<your local account name>;AccountName=<your local account name>;AccountKey=<your local account key>;`

as specified in our docs: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-store-data-blob#connect-to-your-local-storage-with-azure-storage-explorer

What is the connection string you are using? Please sanitize the account key before posting.

**Comment by SeshagiriSriram** [comment]
Sorry I did see the document but since Azure Storage Explorer allowed me to enter Account Name/Key, I assumed it will also be supported. After changing the connection string as specified by @mbialecka, this works just fine and this issue can be closed.
