### ISSUE TITLE
Unable to retrieve child resources.

### ISSUE THREAD

**Issue by richaverma01** [microsoft/AzureStorageExplorer#3397]
Unable to retrieve child resources.

Details:
["RestError:﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.\nRequestId:ff7999a6-801e-0041-653d-742939000000\nTime:2020-08-17T02:24:49.1632346Z</Message></Error>"]

**Comment by MRayermannMSFT** [comment]
@richaverma01 how are you connecting to your resource/s? If it is Azure AD attach, please make sure you selected the correct tenant when attaching.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having issues please open a new issue.
