### ISSUE TITLE
blob container

### ISSUE THREAD

**Issue by yanniekhoo** [microsoft/AzureStorageExplorer#3398]
cant seem to create a blob container

**Comment by MRayermannMSFT** [comment]
@yanniekhoo can you please give us more details about your issue? Specifically:
- the information from the issue template (Storage Explorer version, OS, etc.)
- how you are connecting to your resources
- any error messages you are seeing

**Comment by yanniekhoo** [comment]
Hello, I cant seem to create blob container
[cid:image003.jpg@01D6756F.FF5EC970]

**Comment by MRayermannMSFT** [comment]
@yanniekhoo if you're trying to upload an image you can only do that from the github website. You cannot do it via email.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having issues please open a new issue.
