### ISSUE TITLE
Int64 values are incorrectly limited to ±2^53-1

### ISSUE THREAD

**Issue by craxal** [Microsoft/AzureStorageExplorer#34]
**Storage Explorer Version:** 0.9.6

**OS Version:** ???

**Steps to Reproduce:**

1. Open a storage table.
2. Click the Add Entity toolbar button
3. Add an Int64 property.
4. Enter a valid Int64 value greater than 2<sup>53</sup>.

**Expected Experience:**
The value is valid.

**Actual Experience:**
The value is invalid.

**Comment by craxal** [comment]
If anyone is blocked by this, here’s a fairly simple workaround that will allow you to bypass normal validation:
1. With the Add/Edit Entity dialog open, Hit F12 to open the developer tools.
2. In the Sources tab, hit Ctrl+P and enter EntityPropertyValueValidator.js.
3. Locate line 140:
   ```js
   success = (EntityPropertyValidationCommon.ValidationRegExp.Integer.test(value) && Utilities.isSafeInteger(value));
   ```
4. Edit this line to be:
   ```js
   success = true;
   ```

**WARNING**: Without validation, make sure the values are correctly formatted. We can't guarantee Azure or Storage Explorer will behave correctly if you attempt to enter malformed data.

**Comment by craxal** [comment]
A simple fix has bee merged. I loosened the validation on Int64 values such that you can now enter values within the proper range of Int64. However, because JavaScript integers have a smaller range than Int64 values, we can't validate the actual value, so it's currently still possible to enter invalid values (Azure will report these errors).

A better fix will be available in the next milestone.

**Comment by MRayermannMSFT** [comment]
Not going to worry about this.
