### ISSUE TITLE
The undeleted blob doesn't auto move from 'Deleted blobs'

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/AzureStorageExplorer#340]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Linux
**Architecture**: x64
**Build Number**: 20180622.1
**Commit**: d667aec0
**Regression From**: Not a Regression

#### Steps to Reproduce: ####
1. Right click 'Blob Containers' node and select 'Configure Soft Delete Policy' to enable soft delete.
2. After saving the configuration successfully, delete one blob from 'Active blobs(default)'.
3. Navigate to 'Deleted blobs' and undelete the deleted blob in Step2.
4. Check whether the undeleted blob auto moves from 'Deleted blobs' or not.

#### Expected Experience: ####
The undeleted blob auto moves from 'Deleted blobs'.

#### Actual Experience: ####
The undeleted blob doesn't auto move from 'Deleted blobs'
![undelete](https://user-images.githubusercontent.com/34729092/41842529-9692f718-785a-11e8-8ef2-2863c4838f00.png)

**Comment by JasonYeMSFT** [comment]
Currently we require a manual refresh to reflect the change. Does the blob move to the correct place after refreshing the editor?

**Comment by v-dantch** [comment]
Got it. Thanks for your update. And the undeleted blob moves to the correct place after refreshing manually.

**Comment by JasonYeMSFT** [comment]
This will no longer be an issue since we decided to remove the "deleted blobs only" view. The auto refreshing for the "active only" and "active+deleted" has already been merged.

**Comment by v-dantch** [comment]
Got it. Thanks a lot for your update.
