### ISSUE TITLE
Cannot connect to Azure storage explorer for MacOS

### ISSUE THREAD

**Issue by pepicesVeloz** [microsoft/AzureStorageExplorer#3400]
{
  "message": "\"AADSTS50097: Device authentication is required.\\r\\nTrace ID: f3d1be59-470b-4cbc-975d-f54538b78200\\r\\nCorrelation ID: 9c1d444f-e52d-4cab-9bf3-6318e2a806fc\\r\\nTimestamp: 2020-08-17 08:53:12Z\""
}

**Any help?**

### Note: About Storage Explorer

Version: 1.14.2
AzCopy Version: 10.5.0

Platform: macOS
Architecture: x64 
Build Number: 20200715.2 
Commit: c8e3bc3d2 
Support ID: bd1e20c1-3d43-b0da-2af7-b40cae1e2e8a

**Comment by MRayermannMSFT** [comment]
@pepicesVeloz this is a requirement from your organization (who you work for, who owns a tenant you're signing into). The default sign in library used by Storage Explorer doesn't support this scenario, but our next library (currently in preview) does. You can enable it by going to Settings -> Application -> Sign In -> Enable Microsoft Authentication Library (preview).

A big caveat to this though. I don't think this will work on macOS? Please let us know if it does, but my guess is it won't. Assuming that it doesn't, you will need to talk to an administrator of your tenant to figure out how you can keep using Storage Explorer on macOS.

**Comment by pepicesVeloz** [comment]
@MRayermannMSFT thank you for your support. As you mentioned, it doesn't work on macOS, same answer, so I'll ask my subscription administrator.

Thank you very much for your support! keep in touch.
Juan

**Comment by MRayermannMSFT** [comment]
@pepicesVeloz ok. We'll close this issue for now then. Please open a new one if there's something else you need or if you have additional questions.
