### ISSUE TITLE
Show a successful activity log when dragging and dropping one file to 'Versions' view for one blob

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3402]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200816.2
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core)/ macOS Catalina
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one non-ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one blob -> Right click the blob -> Click 'Manage History -> Manage Versions'.
3. Drag and drop one file to this editor under 'Versions' view.
4. Check the result.

**Expect Experience:**
This action can't be completed.

**Actual Experience:**
1. Show a successful activity log.
![image](https://user-images.githubusercontent.com/41351993/90378637-2e0fb700-e0ac-11ea-8eca-0be0740bd8fa.png)
2. Show a file in the editor of the blob container.
![image](https://user-images.githubusercontent.com/41351993/90378778-60b9af80-e0ac-11ea-9935-9731daeba1c2.png)

**More Info:**
This issue also reproduces when dragging and dropping one **folder/ files**.

**Comment by MRayermannMSFT** [comment]
Should disable drag and drop, same as snapshots.
