### ISSUE TITLE
The action 'Delete' is disabled for one blob under 'Versions' view

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3404]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200816.2
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core)/ macOS Catalina
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one non-ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Right click the blob -> Click 'Manage History -> Manage Versions'.
4. Check the context menu of the blob.

**Expect Experience:**
The action 'Delete' is enabled.

**Actual Experience:**
The action 'Delete' is disabled.
![image](https://user-images.githubusercontent.com/41351993/90381485-07ec1600-e0b0-11ea-90e3-7da73663a41c.png)

**Comment by JasonYeMSFT** [comment]
We intentionally disable the Delete action on the current version. If you select a previous version (an item with a timestamp next to the blob name), the delete action will be enabled.

**Comment by v-xianya** [comment]
@JasonYeMSFT This issue is fixed on build master/20200818.4. so we are going to close it.
![image](https://user-images.githubusercontent.com/41351993/90504516-ca58bd00-e183-11ea-9bea-14733e41e9bf.png)
