### ISSUE TITLE
Add the permission 'Delete version' to 'Access Policies' dialog for one blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3405]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200816.2
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core)/ macOS Catalina
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one non-ADLS Gen2 storage account -> Blob Containers.
2. Select one blob container then right click it -> Click 'Mange Access Policies...'.
3. Click 'Add' -> Check the permissions on the dialog.

**Expect Experience:**
The permission 'Delete Versions' displays.

**Actual Experience:**
The permission 'Delete Versions' doesn't display.
![image](https://user-images.githubusercontent.com/41351993/90382619-957c3580-e0b1-11ea-8b6c-35198fc6cd4a.png)

**Comment by JasonYeMSFT** [comment]
I have check the access policy API in our SDK, it still doesn't support "Delete version" yet.

**Comment by MRayermannMSFT** [comment]
If the final non-beta SDK allows for this maybe add it? Consider risk once we know if it is possible please.

**Comment by JasonYeMSFT** [comment]
Put in 1.17.0 and we'll revisit when this is supported.

**Comment by MRayermannMSFT** [comment]
If by 1.18 we still don't have an ETA for when the SDK/service will support this, then move to future.

**Comment by JasonYeMSFT** [comment]
Tested with the current API and it still doesn't support these new permissions.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220901.1. Fixed. So, we are going to close it.
![image](https://user-images.githubusercontent.com/41351993/187817981-4c687f09-21b0-4e6e-9470-ac465915ed5b.png)
