### ISSUE TITLE
Pop up an error when clicking 'Manage version' for one premium blob

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3406]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200816.2
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core)/ macOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one premium storage account -> Blob Containers.
2. Create one blob container -> Upload one blob to it.
3. Right click the blob -> Click 'Manage History -> Manage Versions'.
4. Check the result.

**Expect Experience:**
No error pops up.

**Actual Experience:**
1. Pop up an error.
![image](https://user-images.githubusercontent.com/54055206/90382464-5d74f280-e0b1-11ea-8c0a-951f97fc3300.png)

2. The blob container is closed after clicking the 'Close' in the error box.

**More Info:**
1. This issue doesn't reproduce for one BlockBlobStorage storage account.
2. This issue also reproduces when switching to 'Active blobs and blobs without current version' view.
3. This issue also reproduces when switching to 'All blobs and blobs without current version' view.

**Comment by JasonYeMSFT** [comment]
I have tried the action in BlockBlobStorage, BlobStorage, classic accounts and StorageV2 and haven't seen this issue. Could you please share a connection to the storage account offline with us?

**Comment by JasonYeMSFT** [comment]
I see what the problem is. There are still regions where the versioning feature is not supported. See [doc](https://docs.microsoft.com/en-us/azure/storage/blobs/versioning-overview?tabs=powershell#about-the-preview). In those regions, the parameters for versioning won't be recognized.
