### ISSUE TITLE
Update the string 'Promote version' to 'Promote Version' for one blob

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3407]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200816.2
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core)/ macOS Catalina
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one non-ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Right click the blob -> Click 'Manage History -> Manage Versions'.
4. Check the toolbar.

**Expect Experience:**
Display 'Promote Version'.

**Actual Experience:**
Display 'Promote version'.
![image](https://user-images.githubusercontent.com/41351993/90383060-38cd4a80-e0b2-11ea-904e-274b27b79edb.png)

**Comment by v-limu** [comment]
Verified on build 20200819.5. This issue has been fixed. So close it.
