### ISSUE TITLE
Allow the empty metadata values for one file under file shares

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3408]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200816.2
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core)/ macOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one storage account -> File Shares.
2. Create one file share -> Upload files and folders to it -> Right click one file -> Click 'Properties...'.
3. Add Metadata in the 'File Property' dialog -> Type an empty metadata value -> Check the result.

**Expect Experience:**
No error displays.

**Actual Experience:**
An error displays.
![image](https://user-images.githubusercontent.com/54055206/90380150-4b458500-e0ae-11ea-8a56-247f5dfc7941.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into main.
