### ISSUE TITLE
Cannot access my internal tables

### ISSUE THREAD

**Issue by Danlough96** [microsoft/AzureStorageExplorer#3410]
Unable to retrieve child resources.

Details:
Network timeout error: connect ECONNREFUSED 127.0.0.1:10002

Tried to access an internal storage table. I've tried creating a new table but for some reason it wont allow me to acess any of them

**Comment by MRayermannMSFT** [comment]
@Danlough96 do you have proxy settings enabled in the app? Alternatively, do you have either of these environment variables set?
- HTTP_PROXY
- HTTPS_PROXY

Also, what OS are you on and what version of Storage Explorer are you running?

**Comment by Danlough96** [comment]
Hi sorry wasted your time. Didnt set up my environment properly be a it usually does it automatically. Human error! My bad
