### ISSUE TITLE
Not able to open my blob containers for local storage accounts

### ISSUE THREAD

**Issue by VishalCodingNinja** [microsoft/AzureStorageExplorer#3412]
**Storage Explorer Version**: latest version
**Build Number**: 
**Platform/OS**:  Windows 10
**Architecture**:  x64
**Regression From**:  Yes

## Bug Description ##

Not able to access the local storage blob containers
## Expected Experience ##

It should show local storage blob containers
## Actual Experience ##

not able to load local storage blob containers
## Additional Context ##

![image](https://user-images.githubusercontent.com/37198555/90459633-82a04a00-e11f-11ea-988e-8a22d6f690f2.png)

**Comment by VishalCodingNinja** [comment]
After trying restart, it resolved automatically.

Thanks 💯

**Comment by MRayermannMSFT** [comment]
@VishalCodingNinja did you restart storage explorer or the emulator?
