### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by shary-sharath** [microsoft/AzureStorageExplorer#3414]
I recently updated my Storage Explorer and getting following error:

**Unable to retrieve child resources.

Details:
Invalid IV length**
![image](https://user-images.githubusercontent.com/51996588/90493609-30334d80-e160-11ea-9115-a1acc904d556.png)

Storage explorer details:
Version: 1.14.2
AzCopy Version: 10.5.0

Platform: Windows
Architecture: ia32 
Build Number: 20200715.2 
Commit: c8e3bc3d2 
Support ID: 6af5193e-69d8-677c-f80e-5de0785294f0 

Copyright © 2020 Microsoft. All rights reserved.

**Comment by MRayermannMSFT** [comment]
At what point in the app does this happen for y'all. Is it on startup or sometime later?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having issues please open a new issue.
