### ISSUE TITLE
Keep a consistent behavior between file shares and ADLS Gen2 blob containers when using the name 'a\b\c' to create a new folder

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3415]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200818.4
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Previous release (1.14.2)

**Steps to reproduce:**
1. Expand one ADLS Gen2 storage account -> File Shares and Blob Containers.
2. Create a file share and a blob container.
3. Click 'New Folder' both in the file share and blob container -> Input 'a\b\c' as the new folder name -> Click 'OK'.
3. Check the results.

**Expect Experience:**
Show a consistent behavior.

**Actual Experience:**
Show inconsistent behaviors.
![image](https://user-images.githubusercontent.com/41351993/90500011-e4db6800-e17c-11ea-9f80-23e4f537537a.png)

**Comment by MRayermannMSFT** [comment]
Won't fix. Today we decided that we are not going to allow people to input \'s and expect them to be treated as delimiters by Storage Explorer. So for example, that means if you enter `a\b\c\d` in the new folder dialog we will treat to mean "you want to create a folder whose name is a\b\c\d" in as literal a way as possible. At that point it is up to the service to determine if that's a valid name.

My observations:
- for file shares, it is not a valid folder name
- for gen2, the service will treat \'s as delimiters
- for blobs, you can create blobs with \'s in their name, but when we parse those we won't treat \'s as delimiters

Also, it appears AzCopy tends to convert \'s to /'s as well. We'll probably have a discussion about that with them.
