### ISSUE TITLE
Keep a consistent behavior when uploading one blob to one folder named '/' or '\' under one regular blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3416]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200818.4
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**
1. Expand one non-ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Create a folder -> Input '/' as the folder name.
3. Upload or paste one blob to the folder -> Check the behavior.
4. Repeat steps 2-3 (use '\\' instead of '/' as the folder name).
5. Check the behavior.

**Expect Experience:**
Keep a consistent behavior.

**Actual Experience:**
Show inconsistent behaviors.
When inputting '/' as the folder name, the uploaded or pasted blob displays under the current view.
![image](https://user-images.githubusercontent.com/41351993/90501956-bad77500-e17f-11ea-9b97-f08c91560a7a.png)
When inputting '\\' as the folder name, The uploaded or pasted blob doesn't display under the current view.
![image](https://user-images.githubusercontent.com/41351993/90502022-d3e02600-e17f-11ea-8c6a-6ae7a15e81d0.png)

**More Info:**
1. On version 1.13.1
The uploaded blob will locate on the root directory regardless upload it to a folder named '/' or '\\'.
2. <1> When typing '\\' in the Destination directory:
![image](https://user-images.githubusercontent.com/41351993/90220110-1e893780-de3a-11ea-8b13-ad3fa9f4cd4f.png)
  Show two layers directory <no name> against the uploaded blob.
![image](https://user-images.githubusercontent.com/41351993/90220222-5abc9800-de3a-11ea-8a1f-9c31e27208c6.png)
<2>When typing '/' in the Destination directory:
![image](https://user-images.githubusercontent.com/41351993/90220251-6e67fe80-de3a-11ea-9af2-ff90ab3ac760.png)
Show one layer directory <no name> against the uploaded blob.
![image](https://user-images.githubusercontent.com/41351993/90220317-8c356380-de3a-11ea-8a28-b2cfcf18788c.png)

**Comment by JasonYeMSFT** [comment]
This is a very rare use case and we are not going to support creating resources with such names (/s and \s).
