### ISSUE TITLE
Fail to promote version for a non-current version of one blob

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3418]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200818.4
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**
1. Select one non-ADLS Gen2 storage account (make sure the blob versioning is enabled).
2. Expand the storage account -> Blob Containers.
3. Upload one blob -> Modify the blob (like: change its properties).
4. Right click the blob -> Click 'Manage History -> Manage Versions'.
5. Right click the previous version -> Click 'Promote version'.
6. Check the result.

**Expect Experience:**
Succeed to promote version.

**Actual Experience:**
Fail to promote version.
![image](https://user-images.githubusercontent.com/41351993/90505910-0260ff80-e186-11ea-9991-997d053186e1.png)

**Comment by v-xianya** [comment]
@JasonYeMSFT 
According the above steps to verify this issue on the build 20200825.4. Reproduce.
So we reopen it.

**Comment by MRayermannMSFT** [comment]
Jason, let's keep tracking this.

**Comment by JasonYeMSFT** [comment]
Blob versioning has GAed. I have verified on the storage account that it is now working in the problematic storage account.
