### ISSUE TITLE
It would be better to pop up a dialog when executing 'Promote version' action

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3419]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200818.4
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**
1. Select one non-ADLS Gen2 storage account (make sure the blob versioning is enabled).
2. Expand the storage account -> Blob Containers.
3. Upload one blob -> Modify the blob (like: change its properties).
4. Right click the blob -> Click ' Manage History -> Manage Versions'.
5. Right click the previous version -> Click 'Promote version'.
6. Check the result.

**Expect Experience:**
It would be better to pop up a dialog when executing 'Promote version' action.

**Actual Experience:**
No dialog pops up.

**Comment by JasonYeMSFT** [comment]
I have added a warning dialog which will pop up when a soft deleted base blob is detected since that is the only scenario data loss may occur.

**Comment by v-xianya** [comment]
Hi @JasonYeMSFT  Verified on build master/20200820.5. We did not see a warning dialog pops up.
 So we re-open it.

**Comment by JasonYeMSFT** [comment]
@v-xianya Could you please share your repro steps? This is mine:
1. Get a blob container with versioning enabled
2. Upload a blob
3. Modify its metadata to create a version
4. Delete the current version
5. Disable blob versioning
6. Upload the same blob to get a non-version base
7. Soft delete the non-version base
8. Promote a previous version and see if the dialog prompts

The dialog will only prompt if the current base blob is a soft deleted non-version blob.

**Comment by v-xianya** [comment]
@JasonYeMSFT  Following your steps, the warning dialog pops up. 
![image](https://user-images.githubusercontent.com/41351993/90844812-5b53b200-e397-11ea-8c88-e4dc331f1b22.png)
