### ISSUE TITLE
Fail to configure delete policy when inputting a valid number prefixed with 0

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/AzureStorageExplorer#342]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Windows10/ MacOS High Sierra /Linux Ubuntu 16.04
**Architecture**: x64
**Build Number**: 20180622.1
**Commit**: d667aec0
**Regression From**: Not a Regression

#### Steps to Reproduce: ####
1. Right click 'Blob Containers' node and select 'Configure Soft Delete Policy'.
2. Check 'Enable soft delete' and type '01' for 'Retention days, then click 'Save''.

#### Expected Experience: ####
Succeed to configure delete policy.

#### Actual Experience: ####
Fail to configure delete policy.
![error](https://user-images.githubusercontent.com/34729092/41843615-7c58e17a-785d-11e8-83e7-c4af3db5c3f5.png)

**Comment by MRayermannMSFT** [comment]
@v-dantch , it looks like Jason merged a fix for this into his feature branch. Next time he has you test the feature branch, or after we merge it into master, you can verify the fix.

**Comment by v-dantch** [comment]
@MRayermannMSFT . Hi Matthew, thanks a lot for your update. This issue has fixed on the latest master branch 20180724.4.
