### ISSUE TITLE
The deleted blob doesn't show under 'Active and soft deleted blobs' view with the Blob versioning enabled

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3420]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200818.4
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account (Blob versioning enabled) -> Blob Containers (Make sure the soft delete policy enabled).
2. Create one blob container -> Upload one blob to it -> Delete the blob.
3. Switch to 'Active and soft deleted blobs' view.
4. Check whether the deleted blob shows or not.

**Expect Experience:**
The deleted blob shows.

**Actual Experience:**
The deleted blob doesn't show.

**More Info:**
This issue doesn't reproduce for one storage account with Blob versioning disabled.

**Comment by JasonYeMSFT** [comment]
This is by design. When versioning is enabled, the base blob will become a non-current version instead of a soft deleted blob. The 'Active and soft deleted blobs' view doesn't show non-current versions.
