### ISSUE TITLE
Fail to delete multiple non-current versions at a time

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3421]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200818.4
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**
1. Select one non-ADLS Gen2 storage account (make sure the blob versioning is enabled).
2. Expand the storage account -> Blob Containers.
3. Upload one blob -> Modify the blob multiple times.
4. Right click the blob -> Click 'Manage History -> Manage Versions'.
5. Select the multiple non-current versions -> Click 'Delete'.
6. Check the result.

**Expect Experience:**
Succeed to delete the multiple non-current versions.

**Actual Experience:**
Fail to delete the multiple non-current versions.
Error details:
```
![image](https://user-images.githubusercontent.com/41351993/90507927-4c97b000-e189-11ea-9ded-23840e3f5d55.png)
 "message": "\"Authentication Failed. The SAS is not correct or expired or does not have the correct permission -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.1-0.20200803174240-68b8d8870657/azblob/zc_storage_error.go:42\\n===== RESPONSE ERROR (ServiceCode=OperationNotAllowedOnAutomaticSnapshot) =====\\nDescription=The specified operation is not allowed on version.\\nRequestId:461cdb15-e01e-00f9-3952-75f4a1000000\\nTime:2020-08-18T11:27:03.8257199Z, Details: \\n
```

**Comment by v-limu** [comment]
Verified on build 20200820.5. This issue has been fixed. So we close it.
