### ISSUE TITLE
No blob shows in the editor of the destination blob container after pasting one version without current version

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3422]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200818.4
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**
1. Select one non-ADLS Gen2 storage account (make sure the blob versioning is enabled).
2. Expand the storage account -> Blob Containers.
3. Upload one blob -> Modify the blob.
4. Right click the blob -> Click 'Manage History -> Manage Versions'.
5. Delete the current version -> Copy one non-current version.
6. Paste it to another blob container -> Check the result.

**Expect Experience:**
Succeed to paste and the blob shows in the editor of the destination blob container.

**Actual Experience:**
1. Show a successful activity log.
![image](https://user-images.githubusercontent.com/41351993/90509575-1f003600-e18c-11ea-95a6-7d6498331eb2.png)
2. The blob doesn't show in the editor of the destination blob container.

**More Info:**
1. This issue doesn't reproduce for non-current version without current version.
2. This issue also reproduces when cloning one non-current version without current version.
![image](https://user-images.githubusercontent.com/41351993/90510331-5de2bb80-e18d-11ea-8f72-dc4339c15e06.png)

**Comment by JasonYeMSFT** [comment]
This is not something we intend to support right now. I will disable the copy command on non-current versions.

**Comment by v-xianya** [comment]
@JasonYeMSFT Verified this issue on build master/20200819.5. Now the 'Copy' action is disable for one non-current versions.

For one non-current version under 'Active blobs and bobs without current version' / 'All blobs and blobs without current version', **the 'Clone...' action is enabled.**

**Comment by v-xianya** [comment]
@JasonYeMSFT Hi  Verified this issue on build master/20200820.6. Fixed.
The '**Clone...**' action is still enabled on the below scenario.
Steps:
1. Upload one blob -> Delete it.
2. Switch to 'Active blobs and blobs without current version'.
3. Right click the blob version -> Check the 'Clone…' action.
![image](https://user-images.githubusercontent.com/41351993/90732114-3448a200-e2fd-11ea-9189-1ab6ed51ca24.png)

**Comment by v-xianya** [comment]
This issue is fixed on build master/20200821.5. Close it.
