### ISSUE TITLE
Fail to change access tier for one non-current version

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3425]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200819.5
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one Non-ADLS Gen2 storage account (make sure the blob versioning is enabled) -> Blob Containers.
2. Create one blob container -> Upload one blob.
3. Add metadata for the blob -> Click 'Save'.
4. Right click the blob -> Click 'Manage History -> Manage Versions'.
5. Select one non-current version -> Change access tier for it -> Check the result.

**Expect Experience:**
Succeed to change access tier.

**Actual Experience:**
Fail to change access tier.
![image](https://user-images.githubusercontent.com/41351993/90620122-a7daa880-e244-11ea-93b3-beabf141ac54.png)

Error details:
`"name": "RestError",
  "message": "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.\nRequestId:4c820242-501e-0061-170e-76626d000000\nTime:2020-08-19T09:51:35.6414279Z</Message><QueryParameterName>versionid</QueryParameterName><QueryParameterValue>2020-08-19T09:48:55.2902514Z</QueryParameterValue><Reason>This operation is only allowed on the root blob. Version id should not be provided.</Reason></Error>",`

**Comment by MRayermannMSFT** [comment]
@v-xianya can you still repro this. We aren't able to. If yes, please specify what tier you are changing from and to.

**Comment by JasonYeMSFT** [comment]
I can reproduce this on one of our test accounts in "eastus2" region. It seems like something else the service needs fix.

**Comment by JasonYeMSFT** [comment]
The service is also rolling out a fix for this. Please re-verify this issue and let us know if it is working now.

**Comment by v-xianya** [comment]
@JasonYeMSFT Verified this issue on build 20200825.4. Reproduce.

**Comment by v-xianya** [comment]
@JasonYeMSFT 
Verified this issue on build 20200825.9. Fixed. So we are going to close it.
