### ISSUE TITLE
No active non-current version displays under 'All blobs and blobs without current version' view after deleting one of the non-current versions

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3426]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200819.5
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one Non-ADLS Gen2 storage account (make sure the blob versioning is enabled) -> Blob Containers.
2. Create one blob container -> Upload one blob.
3. Modify the blob -> Delete the blob.
4. Switch to 'Active blobs and blobs without current version' view -> Delete the non-current version.
5. Switch to 'All blobs and blobs without current version' view.
6. Check whether an active non-current version displays.

**Expect Experience:**
Display an active non-current version.

**Actual Experience:**
No active non-current version displays.
![image](https://user-images.githubusercontent.com/41351993/90624302-546b5900-e24a-11ea-8035-b21a0944c41e.png)

**Comment by JasonYeMSFT** [comment]
This is by design. We display the latest version for the blob in each view, including or excluding deleted ones. In "Active blobs and blobs without current version", it displays the latest active version. In "All blobs and blobs without current version", since there is a later soft deleted version, it will display that instead.

**Comment by v-xianya** [comment]
@JasonYeMSFT Thanks for the updates. Could you help to clarify the below behavior?
When using Mange Versions command to filter out. There are display a non-current version and the latest soft deleted non-current version under "All blobs and blobs without current version". 
![image](https://user-images.githubusercontent.com/41351993/90705790-570b9400-e2c6-11ea-8014-e5ac0d71e6c2.png)

**Comment by JasonYeMSFT** [comment]
This means the following:
`active.txt (Wed, 19 Aug 2020 10:28:32 GMT)` is an active non-current version of the blob `active.txt`.
`active.txt (Wed, 19 Aug 2020 10:28:40 GMT)` is a soft deleted non-current version of the blob `active.txt`.
The blob `active.txt` doesn't have a current version.
