### ISSUE TITLE
Transfer of files in Blob Container failed

### ISSUE THREAD

**Issue by ChantalRou** [microsoft/AzureStorageExplorer#3427]
**Storage Explorer Version**: <1.12.0>
**Build Number**: <20200116.10>
**Platform/OS**: <Windows 10>
**Architecture**: <ia32>

## Bug Description ##
<Transfer of files failed. 0 items transferred. error: UnexpectedQuit>

## Steps to Reproduce ##
<Drag the same folders to Blob Containers>

## Expected Experience ##
<Expected complete transfer of files>

**Comment by MRayermannMSFT** [comment]
@ChantalRou can you please provide us with some more information, specifically could you fill out the issue template? Also, please update to the latest version of Storage Explorer.

**Comment by ChantalRou** [comment]
In the end, I found out the problem was not with Storage Explorer, it was my external hard drive.

I can’t update the latest software version because I don’t have an administrator password.

By the way, is there a way to make the Storage Explorer show a thumbnail of picture and video files instead of an icon? It’s impossible to explore and locate image files without thumbnails.

Thanks,

Chantal

**Comment by MRayermannMSFT** [comment]
Ok, glad you fixed the issue. And no, thumbnails are not possible at this time.

**Comment by JasonYeMSFT** [comment]
There is already a feature opened for the thumbnails. Please track it here #2427
