### ISSUE TITLE
Copy isnot available in gen2 blob containers for azure ad only scenarios

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#3428]
Although we've added support for copy in non-gen2 blob containers for Azure AD only scenarios, the action continues to be disabled in the gen2 case. This is because although there are APIs that make it possible, those APIs only work if the user's permissions are coming from RBAC. Since the great vast majority of users obtain Gen2 permissions via ACL, then it doesn't make sense to introduce the feature that'll fail for so many people.

**Comment by kk921dbg** [comment]
This still seems to be an issue with copy and paste being greyed out.  Why is this as you can Move and Rename?  How does a user copy and paste within an ADLS Gen2 container with Azure AD permissions using DFS endpoint?

**Comment by keen85** [comment]
Hi @MRayermannMSFT, any news on this issue?
Are you planning to fix this?

**Comment by tksrc** [comment]
All of our clients and us are using RBAC for access management to the gen2 containers. Is it possible to still implement the feature and let everyone who's using RBAC to benefit from copy and paste? (and clone)

**Comment by roxxette** [comment]
I don't get it. Normally we use ACL to add additional permission upon RBAC. So enable copy/paste button by RBAC won't fail many people. Am I right?
At least, we should add an option to let user decide...

**Comment by JasonYeMSFT** [comment]
The work has been done to support the mentioned scenarios. Please upgrade to the latest version to get it.
