### ISSUE TITLE
Error de autenticación: Request date header too old: 'Wed, 19 Aug 2020 01:04:51 GMT'

### ISSUE THREAD

**Issue by apismarcos** [microsoft/AzureStorageExplorer#3429]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:

**Comment by MRayermannMSFT** [comment]
@apismarcos can you please provide us with some more information, specifically could you fill out the issue template?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response and/or information. Please open a new issue if you are still having problems, and fill out the issue template when you do.
