### ISSUE TITLE
Disable the 'Upload/New Folder' after switching to 'Deleted blobs'

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#343]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180622.2
**Commit**: d667aec0
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Go to Subscription -> Storage Accounts.
2. Select one blob container and enable soft delete -> Open the blob container and switch to 'Deleted blobs' -> Check the toolbar.

#### Expected Experience: ####
'Upload/New Folder' are disabled. 

#### Actual Experience: ####
'Upload/New Folder' are enabled.
![disable](https://user-images.githubusercontent.com/34729022/41842920-a48d0786-785b-11e8-87d9-202bf322093c.png)

**Comment by JasonYeMSFT** [comment]
Why do you expect the "Upload/New Folder" to be disabled in the "Deleted blobs" viewing context? The viewing context has nothing to do with the commands. "Upload/New Folder" are supposed to be working as usual.

**Comment by v-xuanzh** [comment]
Hi @JasonYeMSFT , Please get detail using the below steps.
1. Enable soft delete -> Open one blob container then switch to 'Deleted Blobs'.
2. If support to 'Upload/New Folder' under 'Deleted blobs'.
    
     -> Expect: The uploaded blob/New folder doesn't display under 'Deleted blobs'. 
     
     -> Actually: The uploaded blob/New folder displays under 'Deleted blobs'. 
So we think should disable the 'Upload/New Folder' under 'Deleted blobs'.
![support](https://user-images.githubusercontent.com/34729022/41886473-029dfbd8-78ec-11e8-970c-558ec1ed854a.png)

More info:
1. No way to delete the dispalyed folder under 'Deleted blobs'(The folder displays again after refreshing the editor)
2. The uploaded blob will displays under 'Active blobs' after refreshing.

**Comment by JasonYeMSFT** [comment]
This will no longer be the issue. We decided to have only "Active" and "Active and deleted" views where Upload/New Folder will always make sense.
