### ISSUE TITLE
No 'items transferred' shows in the activity log after downloading multiple versions under Versions view

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3433]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200820.5
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one Non-ADLS Gen2 storage account (make sure the blob versioning is enabled) -> Blob Containers.
2. Create one blob container -> Upload one blob to it -> Modify the blob multiple times.
3. Right click the blob -> Click 'Manage History -> Manage Version'.
4. Download the all versions -> Check the activity log.

**Expect Experience:**
The 'items transferred' shows in the activity log.
![image](https://user-images.githubusercontent.com/54055206/90751228-70353480-e308-11ea-91f4-2db8814cd96b.png)

**Actual Experience:**
The 'items transferred' doesn't show in the activity log.
![image](https://user-images.githubusercontent.com/54055206/90749813-7e825100-e306-11ea-96bf-56123f4c71bd.png)

**Comment by v-xianya** [comment]
This issue has been fixed on build 20200911.5. So close it.
