### ISSUE TITLE
Unable to retrieve child resources: ENOTFOUND

### ISSUE THREAD

**Issue by gantta** [microsoft/AzureStorageExplorer#3436]
**Storage Explorer Version**: 1.14.2
**Build Number**: 20200715.2
**Platform/OS**: Windows 10
**Architecture**: ia32
**Regression From**:  New install

## Bug Description ##
Unable to retrieve child resources.

Details:
["RestError:request to https://<account>.blob.core.windows.net/?include=metadata&comp=list failed, reason: getaddrinfo ENOTFOUND <account>.blob.core.windows.net"]

## Steps to Reproduce ##
1. Expand Local and Attached
2. Expand Storage Account as connected by Key
3. Expand Blob Containers
4. Received bug description above.

## Expected Experience ##
Expect to see the list of containers in the storage account.

## Actual Experience ##
Error details window opens with the Bug Description above

## Additional Context ##
This storage account is associated with an Azure GovCloud client. We receive the bug description when connected to the VPN, however when not connected to the VPN, we receive the following error message:

Unable to retrieve child resources.

Details:
["FetchError:request to https://<account>.blob.core.windows.net/?include=metadata&comp=list failed, reason: getaddrinfo EAI_AGAIN <account>.blob.core.windows.net"]

**Comment by MRayermannMSFT** [comment]
@gantta are you intentionally removing your Storage Account name from the error message, or is that exactly the error message showed by Storage Explorer?

**Comment by gantta** [comment]
I removed the account name from the message. The actual message specifies the account name.

**Comment by dipesh-kumar** [comment]
I am having the same issue at India.

**Comment by MRayermannMSFT** [comment]
@gantta maybe you need to setup proxy settings in storage explorer to have it successfully work with your VPN? We don't auto detect your proxy settings, so if yes you'll need to do that.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having issues please open a new issue.

**Comment by gantta** [comment]
Ended up resolving the issue by removing the storage account and adding it again.
