### ISSUE TITLE
Support copying from Blob versions in "Archive" tier

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#3439]
**Storage Explorer Version**: 1.15.0
**Platform/OS**: Windows 10/macOS/Linux
**Architecture**: x64
**Regression From**:  Not a regression

## Bug Description ##
Cannot change access tier of a Blob version from "Archive" to "Hot" or "Cool".

## Steps to Reproduce ##
1. Set access tier of a Blob version to "Archive"
2. Try to set its access tier to "Cool"

## Expected Experience ##
Succeed in the operation.

## Actual Experience ##
Fail with service returning error: BlobOperationNotSupported.

**Comment by MRayermannMSFT** [comment]
Service bug. Jason emailed service team in early August, still hasn't heard anything back. Let's keep tracking this issue and try to get to the bottom of it.

**Comment by JasonYeMSFT** [comment]
Update: Up to now, the only way to restore data from an archived blob version is through an asynchronous copy. https://github.com/microsoft/AzureStorageExplorer/issues/3439. We need to support this scenario later utilizing this approach.

**Comment by JasonYeMSFT** [comment]
Update: After investigation, even the documented async copy doesn't seem to work with archived blob version. Checked with Portal and it doesn't support bringing archive version back to cool/hot neither.

**Comment by JasonYeMSFT** [comment]
Duplicate of #1950
