### ISSUE TITLE
Display versions for Windows executables etc

### ISSUE THREAD

**Issue by sicklittlemonkey** [microsoft/AzureStorageExplorer#3440]
Am I missing something or does ASX not display versions for EXEs, DLLs etc with version resources?

**Comment by MRayermannMSFT** [comment]
@sicklittlemonkey which EXEs or DLLs are you looking to get version numbers from, and what version numbers are you expecting for those things?

**Comment by sicklittlemonkey** [comment]
Hi @MRayermannMSFT. Sorry, if I wasn't clear. We have a cloud solution built by a third party (so the terminology is fairly new to me) and the installers for our product are stored in a Storage Account Blob Container. These files are regularly updated and referred to in other scripts that we don't want to have to update, so we can't, say, embed the version number in the filename.

So from Storage Explorer we can view the installer file blobs, but right-clicking and getting properties doesn't show the file version from the file's version resource. I suppose that's Windows-specific functionality. The only option seems to be to manually add metadata properties, which I guess we could script if we script the uploading of new installers.

**Comment by MRayermannMSFT** [comment]
> I suppose that's Windows-specific functionality

Yes, you're exactly right. This is not something we can feasibly add.

> The only option seems to be to manually add metadata properties, which I guess we could script if we script the uploading of new installers.

Yep, that would probably be a good solution.
