### ISSUE TITLE
The "Blob Containers" node displays under the attached account when attaching a Storage account without Blobs service

### ISSUE THREAD

**Issue by v-xinda** [microsoft/AzureStorageExplorer#3441]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200821.4
**Branch**: master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Previous release (1.13.0)

**Steps to reproduce:**
1. Right click one storage account -> Select 'Get Shared Access Signature...'.
2. Uncheck the service '**Blobs**' -> 'Create' -> Copy the connection string.
3. Attach the storage account via 'Use a connection string'.
4. Expand the attached account -> Check the result.

**Expect Experience:**
The "Blob Containers" node doesn't display under the attached account.

**Actual Experience:**
The "Blob Containers" node displays under the attached account.
![image](https://user-images.githubusercontent.com/57662131/90874042-ac809780-e3d1-11ea-8554-a2566247d365.png)

**More Info:**
An unexpected error occurs when expanding the Blob containers.
![image](https://user-images.githubusercontent.com/57662131/90874060-b30f0f00-e3d1-11ea-8af1-19603e39f2ea.png)
Details:
`["RestError:﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:4a51ab1d-101e-000e-199a-77586d000000\nTime:2020-08-21T09:11:03.0113759Z</Message><AuthenticationErrorDetail>Signature did not match. String to sign used was undefined\nrl\nq\nsco\n2020-08-21T08:39:59Z\n2020-08-22T08:39:59Z\n\n\n2019-02-02\n</AuthenticationErrorDetail></Error>"]`

**Comment by v-limu** [comment]
Verified on build 20200824.2. This issue has been fixed. So close it.
