### ISSUE TITLE
storageV2 blob containers dont open on Azure Storage Explorer tool (web consoleworks fine)

### ISSUE THREAD

**Issue by pardhivchunduri** [microsoft/AzureStorageExplorer#3444]
**Storage Explorer Version**: 1.14.2
**Build Number**: 20200715.2
**Platform/OS**: Windows 10
**Architecture**: ia32
**Regression From**:  NA
![image](https://user-images.githubusercontent.com/56335785/90943025-f024d280-e3cc-11ea-8d38-2c0bda1298d9.png)

## Bug Description ##
Unable to retrieve child resources.

Details:
["FetchError:request to https://ae041030fspstg.blob.core.windows.net/?include=metadata&comp=list failed, reason: read ECONNRESET"]
![image](https://user-images.githubusercontent.com/56335785/90943050-06cb2980-e3cd-11ea-9f3d-4a5d08da1b37.png)

## Steps to Reproduce ##
1. Add an Azure account.
2. click on storage account(storageV2)
2. expand blob container.
Note: storage account of type BlobStorage opens fine.

## Expected Experience ##
full access to files in storage

## Actual Experience ##
unable to load file list.

**Comment by MRayermannMSFT** [comment]
@pardhivchunduri are you consistently seeing this error? Does it happen when trying to load blobs in other storage accounts?

**Comment by pardhivchunduri** [comment]
Yes @MRayermannMSFT , the issue applies to **all Storage accounts** with "Account Kind" = "StorageV2" || "Storage", irrespective of which subscription they belong to. the only ones opening are "Account Kind" = "BlobStorage". and just to be clear all these open perfectly on the Azure web console.

**Comment by MRayermannMSFT** [comment]
@pardhivchunduri are your storage accounts behind a virtual private network or maybe a storage firewall that would prevent them from being accessed from your machine?

**Comment by pardhivchunduri** [comment]
I have raised the issue to my admin department, they are investigating the issue. once i have something, i will update or close this ticket. Thanks.

**Comment by MRayermannMSFT** [comment]
@pardhivchunduri we're going to go ahead and close this. If you ever have an update, please open a new issue and include a link back to this one. Thanks!
