### ISSUE TITLE
Error in Azure Storage Explorer Desktop Version

### ISSUE THREAD

**Issue by bssindiana** [microsoft/AzureStorageExplorer#3445]
Unable to retrieve child resources.

Details:
Network timeout error: connect ETIMEDOUT 20.150.28.134:443

**Comment by MRayermannMSFT** [comment]
@bssindiana is there a proxy on your network? If so, then you'll need to configure proxy settings in Storage Explorer, see more here:

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having issues please open a new issue.
