### ISSUE TITLE
Unable to retrieve child resources.  Details: Network timeout error: connect ECONNREFUSED 127.0.0.1:10002

### ISSUE THREAD

**Issue by beige112279** [microsoft/AzureStorageExplorer#3448]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:

**Comment by MRayermannMSFT** [comment]
@beige112279 do you have proxy settings enabled, either in the application settings (gear icon on the left), or via OS environment variables (look for either HTTP_PROXY or HTTPS_PROXY in your OS environment variables).

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having issues please open a new issue.
