### ISSUE TITLE
Error: unable to retrieve child resources

### ISSUE THREAD

**Issue by Tjianke** [microsoft/AzureStorageExplorer#3449]
**Storage Explorer Version**: v1.14.2
**Build Number**: 20200715.2
**Platform/OS**: Windows 10
**Architecture**: x86_64
**Regression From**: Not sure

## Bug Description ##
Having trouble loading local attached blob container, after long hold pops this 
![image](https://user-images.githubusercontent.com/34013484/91019545-bd284c00-e623-11ea-9d6f-ce415dc86708.png)

## Steps to Reproduce ##
1. open local & attached
2. open storage accounts
3. open up local1.blob container(created by myself)

## Additional Context ##

**Comment by MRayermannMSFT** [comment]
@Tjianke do you have proxy settings enabled, either in the application settings (gear icon on the left), or via OS environment variables (look for either HTTP_PROXY or HTTPS_PROXY in your OS environment variables).

**Comment by Tjianke** [comment]
thx, fixed after turning off HTTP_PROXY

**Comment by MRayermannMSFT** [comment]
Good.
