### ISSUE TITLE
Add the word 'Preview' next to the string 'Data Lake Storage Gen1' on the Settings Services part

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3452]
**Storage Explorer Version:** 1.15.0
**Build**: 20200824.2
**Branch**: rel/1.15.0
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04 / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer -> Open 'Settings' -> Click 'Services'.
2. Check the service string 'Data Lake Storage Gen1'.

**Expect Experience:**
Display 'Data Lake Storage Gen1 (Preview)'.

**Actual Experience:**
Display 'Data Lake Storage Gen1'.
![image](https://user-images.githubusercontent.com/41351993/91024933-37a89a00-e62b-11ea-8912-98d9f92197f1.png)

**More Info:**
Display 'Data Lake Storage Gen1 (Preview)' on the tree view.
![image](https://user-images.githubusercontent.com/41351993/91024997-5149e180-e62b-11ea-9b35-1145da931dda.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
