### ISSUE TITLE
The results are inconsistent when uploading an empty folder to one ADLS Gen2 blob container and one file share

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3453]
**Storage Explorer Version:** 1.15.0
**Build**: 20200824.2
**Branch**: rel/1.15.0
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04 / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one ADLS Gen2 storage account -> Blob Containers and File Shares.
2. Create one blob container and one file share.
3. Upload one empty folder to the new created blob container and the file share.
4. Check the results.

**Expect Experience:**
The results keep consistent.

**Actual Experience:**
The results are inconsistent.
1. For the file share, the empty folder shows.
2. For the blob container, no folder shows.
![image](https://user-images.githubusercontent.com/41351993/91025555-2318d180-e62c-11ea-932f-13f56d9a5802.png)

**Comment by JasonYeMSFT** [comment]
This is expected. In file share, a real folder is created while in blob containers, no folder persists since no real folder exists.

**Comment by v-xianya** [comment]
@JasonYeMSFT 
Yes, In file share, a real folder is created while in blob containers, no folder persists since no real folder exists.
But in ADLS Gen2 blob containers, the folders are real. why the behaviors are different for ADSL Gen2 blob containers and file shares? Could you help to elaborate?

**Comment by JasonYeMSFT** [comment]
We use blob endpoints for upload in Gen2 containers, where the service doesn't have the capability to tell whether it is HNS enabled or not. Thus it won't preserve empty folders. Let's re-prioritize this issue if customers ask for it.
