### ISSUE TITLE
Can't undelete for one folder with the soft deleted version

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3454]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200824.2
**Branch**: rel/1.15.0
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one Non-ADLS Gen2 storage account (make sure the blob versioning is enabled) -> Blob Containers (make sure the soft delete policy is enabled).
2. Create one blob container -> Upload one folder with blobs to it.
3. Open the folder -> Delete one blob -> Switch to 'All blobs and blobs without current' view -> Delete the version.
4. Right click the folder -> Click 'Undelete -> Undelete Selected' -> Click 'Ok'.
5. Check the result.

**Expect Experience:**
Succeed to undelete the version.

**Actual Experience:**
Can't undelete the version.
![image](https://user-images.githubusercontent.com/54055206/91026260-1b0d6180-e62d-11ea-929b-b24fd690fe45.png)

**More Info:**
This issue also reproduces when clicking 'Undelete by Date…'.

**Comment by JasonYeMSFT** [comment]
When blob versioning is enabled, the listing won't include blobs without current version so we won't undelete previous versions of them. Attempting to include versions may slow down the undelete since all the versions will be in the listing response.

**Comment by MRayermannMSFT** [comment]
I have updated the undelete confirmation dialog to make it clear what will be undeleted.
