### ISSUE TITLE
Miss the action 'Delete' on the context menu of one QA blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3456]
**Storage Explorer Version:** 1.15.0
**Build**: 20200824.2
**Branch**: rel/1.15.0
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04 / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Previous release(1.14.2)

**Steps to reproduce:**

1. Expand one non-ADLS Gen2 storage account -> Blob Containers.
2. Select one blob container -> Add it to 'Quick Access'.
3. Check the context menu of the QA blob container.

**Expect Experience:**
No action is missed.

**Actual Experience:**
The action 'Delete' is missed.
![image](https://user-images.githubusercontent.com/41351993/91031131-be14aa00-e632-11ea-8daa-2bead449a433.png)

**Comment by craxal** [comment]
By design. Deleting the container would make the Quick Access node a "broken" node. We decided to remove delete functionality for a cleaner experience.

**Comment by v-xianya** [comment]
@craxal For file share, the action 'Delete' displays on the context menu of one QA file share.
Is there any difference between the QA file share and the QA blob container?  [The QA file share doesn't display broken after deleting it]

**Comment by craxal** [comment]
@v-xianya Blob container nodes were reimplemented recently in our blob extension. Fire share nodes are using older code. The decision to exclude Delete from QA nodes was recently made. We are aware that there is some inconsistency.

**Comment by v-xianya** [comment]
@craxal Got it. thanks for your sharing!
