### ISSUE TITLE
The Properties Panel doesn't auto refresh after enabling soft delete 

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#346]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180622.2
**Commit**: d667aec0
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Go to Subscription -> Storage Accounts.
2. Right click 'Blob Containers' node -> Select 'Configure Soft Delete Policy' -> Check 'Enable soft delete' with a valid Retention days -> Save.

#### Expected Experience: ####
The Properties Panel auto refreshes after enabling the soft delete.

#### Actual Experience: ####
The Properties Panel doesn't auto refresh after enabling the soft delete.
![refresh](https://user-images.githubusercontent.com/34729022/41844022-81ab80f0-785e-11e8-8ffa-47753b1cbcab.png)

**Comment by JasonYeMSFT** [comment]
Currently, we are not auto-refreshing the Properties Panel. Close this as won't fix.
