### ISSUE TITLE
The deleted blobs disappear after uploading the same blobs

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#347]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180622.2
**Commit**: d667aec0
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Go to Subscription -> Storage Accounts.
2. Enable soft delete -> Open one blob container and upload one blob to it.
3. Delete the uploaded blob then make sure it displays under 'Deleted blobs'.
4. Upload the same blob again and check the deleted blobs.

#### Expected Experience: ####
The deleted blob in step2 still displays under 'Deleted blobs'.

#### Actual Experience: ####
The deleted blob in step2 disappears under 'Deleted blobs'.

**Comment by JasonYeMSFT** [comment]
If you upload a new blob with the same name of some deleted blob, the deleted blob and all its snapshots become deleted snapshots of the new uploaded blob. This is by design since this is the default behavior of the blob storage service.

**Comment by JasonYeMSFT** [comment]
This is a service behavior and it is very unlikely that a user upload blobs of different types with the same name. We will reconsider this if some one complains about it.
