### ISSUE TITLE
Emulators don't support blob versions

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3473]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200825.4
**Branch**: rel/1.15.0
**Platform/OS:** Windows 10
**Azurite Version:** 3.8.0
**Architecture**: ia32
**Regression From:** Not a regression

**Steps to reproduce:**

1. Install and run Azurite -> Launch Storage Explorer.
2. Expand 'Local & Attached' -> Storage Accounts -> (Emulator - Default Ports) (Key).
3. Right click the Blob Containers node -> Create a blob container.
4. Switch to 'All blobs and blobs without current version' view on the blob container's editor.
5. Check the result.

**Expect Experience:**
No error occurs.

**Actual Experience:**
1. An error information bar pops up.
2. The current blob tab is auto closed.
![image](https://user-images.githubusercontent.com/41351993/91157215-9dfaee80-e6f7-11ea-92b3-aaa4af7fe72b.png)

**More Info:**
1. This issue also reproduces when switching to 'Active blobs and blobs without current version' view.
2. Show the same experience when clicking 'Manage Versions' for one Emulator blob.

**Comment by MRayermannMSFT** [comment]
Let's check up on this in 1.17

**Comment by MRayermannMSFT** [comment]
Not for us to fix. Whenever they support blob versions is when they do.
