### ISSUE TITLE
Disable the option of the permission 'Delete version' when creating a SAS URL against one Emulator blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3475]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200825.4
**Branch**: rel/1.15.0
**Platform/OS:** Windows 10
**Azurite Version:** 3.8.0
**Architecture**: ia32
**Regression From:** Not a regression

**Steps to reproduce:**

1. Install and run Azurite -> Launch Storage Explorer.
2. Expand 'Local & Attached' -> Storage Accounts -> (Emulator - Default Ports) (Key).
3. Right click the Blob Containers node -> Create a blob container.
4. Right click the blob container -> Click 'Get Shared Access Signature...'.
5. Check the 'Permissions' part on the 'Shared Access Signature' dialog.

**Expect Experience:**
The option of the permission 'Delete version' is disabled.

**Actual Experience:**
1. The permission 'Delete version' is enabled.
2. An error occurs when creating a SAS URL with the permission 'Delete version' is checked.
![image](https://user-images.githubusercontent.com/41351993/91158250-f1ba0780-e6f8-11ea-94cd-935036bef022.png)

**More Info:**
This issue also reproduces for one Emulator blob.

**Comment by MRayermannMSFT** [comment]
Let's check up on this in 1.17

**Comment by MRayermannMSFT** [comment]
Closing to just track #3473
