### ISSUE TITLE
Machine proxy settings being invoked in ASE 1.14.2/AzCopy 10.5.0

### ISSUE THREAD

**Issue by ZeffyReport** [microsoft/AzureStorageExplorer#3481]
Since the latest update, ASE is ignoring application defined proxy settings (or lack there of) when copying to storage account, and taking the machine proxy settings (winHTTP).

This is preventing storage transfers from taking place.

A modified view of the logs is attached

Geoff
[nomachineproxy.txt](https://github.com/microsoft/AzureStorageExplorer/files/5127180/nomachineproxy.txt)
[machineproxy.txt](https://github.com/microsoft/AzureStorageExplorer/files/5127181/machineproxy.txt)

**Comment by MRayermannMSFT** [comment]
@ZeffyReport what was the last version of Storage Explorer you were using?

In our latest version, 1.15, we added a setting to disable AzCopy's proxy auto detection feature. You can find it under settings -> transfers -> azcopy -> Disable AzCopy Proxy Usage.

**Comment by ZeffyReport** [comment]
Hi team,

Thanks for the update. As per topic, I was using 1.14.2, and will try out 1.15.0.

Geoff

**Comment by ZeffyReport** [comment]
Hi Matt,

This option does indeed allow transfers to occur, but requires me to change settings ASE in multiple locations whether I am on premise or off premises.

I think a preferred option for AzCopy would be for the checkbox to enable AzCopy to follow ASE settings, or unchecked to follow AzCopy default settings.

Geoff

**Comment by MRayermannMSFT** [comment]
> I think a preferred option for AzCopy would be for the checkbox to enable AzCopy to follow ASE settings, or unchecked to follow AzCopy default settings.

Yep. We agree. Doing that is on our backlog.
