### ISSUE TITLE
A11y_Azure Tools Storage Explorer_Settings_Transfers_Keyboard: Keyboard focus is going on non actionable heading content.  

### ISSUE THREAD

**Issue by RohitJadhav-TCS** [microsoft/AzureStorageExplorer#3485]
GitHubTags: #C&AI_Aug2020_BMAzure Tools Storage Explorer;#A11yMAS;#A11YTCS;#DesktopApp;#Azure Tools Storage Explorer;#WCAG2.1.1;#Win32;#A11ySev2;#Benchmark;#Keyboard;#FTP;

### **Environment Details:**
Application Name: Azure Tool Storage Explorer
Application version: 1.14.2
Windows Version - Windows10
Screen Reader : JAWS(2020.2006.12ILM),NVDA(2020.2)

### **Repro Steps:**

1. Launch Storage Explorer
2. Navigate to Setting menu on left pane and click on it.
3. Navigate to Transfers on right pane and  click on it.
4. "Transfers" screen gets opened.
5. Verify keyboard focus.

### **Actual:**
Keyboard focus is going on non actionable heading content.  
When we enter any of the section keyboard focus is going on non actionable Heading like "Transfers". 

Note: Similar issue observed with all fours setting tabs.

### **Expected:**
Keyboard focus should not go on non actionable content. 

### **User Impact:**
Keyboard only users will get confused if keyboard focus going on non actionable content.

### **Attachment:**
https://microsoft-my.sharepoint.com/:v:/p/v-rojad/EfBv4FBu3mhNvigzA7zGIeABZJyNTjKJQZzLKgEpSZP1vg?e=sNSKQP

**Comment by JasonYeMSFT** [comment]
@RohitJadhav-TCS Could you please verify and close this issue if it is fixed?

**Comment by 12-shweta** [comment]
Github Tags:#Closed;
