### ISSUE TITLE
A11y_Azure Tools Storage Explorer_Settings_Application_AI4D: Name property does not exist for "Proxy" checkbox.

### ISSUE THREAD

**Issue by RohitJadhav-TCS** [microsoft/AzureStorageExplorer#3486]
GitHubTags: #C&AI_Aug2020_BMAzure Tools Storage Explorer;#A11yMAS;#A11YTCS;#DesktopApp;#Azure Tools Storage Explorer;#WCAG4.1.2;#Win32;#A11ySev2;#Benchmark; #FTP; 

### **Environment Details:**
Application Name: Azure Tool Storage Explorer
Application version: 1.14.2
Windows Version - Windows10
Screen Reader : JAWS(2020.2006.12ILM),NVDA(2020.2)

### **Repro Steps:**

1. Launch Storage Explorer
2. Navigate to Setting menu on left pane and click on it.
3. Navigate to Application on right pane and  click on it.
4. "Application" screen gets opened.
5. Turn on Accessibility Insight for desktop and Hover on "Proxy" checkbox and see Name property.

### **Actual:**
Name property does not exist for "Proxy" checkbox.

### **Expected:**
Name property should exist for "Proxy" checkbox.

### **User Impact:**
Screen reader users will not get the correct value of check box.

### **Attachment:**
https://microsoft-my.sharepoint.com/:i:/p/v-rojad/ERCevMvLwi5Ppef5sBbM3bMBKOY2G7w4eO2EjfLZgOBJiw?e=adBWZ9

**Comment by JasonYeMSFT** [comment]
@RohitJadhav-TCS The fix for this bug has been merged. Could you please verify it?

**Comment by JasonYeMSFT** [comment]
@craxal Since you are changing this component, please make sure the accessibility bug is addressed in the new design.

**Comment by RohitJadhav-TCS** [comment]
Verified in Microsoft Azure Storage Explorer Version 1.16.0-dev Issue is no longer reproducing hence closing bug. Attached screenshot for reference. 
![image](https://user-images.githubusercontent.com/52035395/96442635-13cb9400-1229-11eb-9a96-8d66a0d19aae.png)

**Comment by 12-shweta** [comment]
Github Tags:#Closed;
