### ISSUE TITLE
Auth seems to be cached: Unable to retrieve child resources.

### ISSUE THREAD

**Issue by dotnetprofessional** [microsoft/AzureStorageExplorer#3488]
**Storage Explorer Version**: 1.14.2
**Build Number**: (really should make that copyable!)
**Platform/OS**: Win
**Architecture**: x64
**Regression From**:  No

## Bug Description ##
When using AAD Auth to connect to resources and you don't have permissions and attempt to access the resource you get the error "Unable to retrieve child resources." This is expected, however if you then grant yourself access (think JIT access), so you have access you still can't access the resources. I tried refresh but that didn't work, it seems something is being cached but only at a single resource level. If I try to access a different resource that I hadn't previously it will work as expected. Only the resource that I failed on continues to fail.

## Steps to Reproduce ##
1. Try to access a resource you don't have access to (error)
2. Grant yourself access to the resource
3. Attempt to access again via Refresh.

## Expected Experience ##
The expected behavior is that the resources should now be available.

## Actual Experience ##
Resources are not available, when they should be.

## Additional Context ##
This is likely mostly a concern to those who have to elevate privileges on a as need basis - ie don't always have permission to access resources.

**Comment by JasonYeMSFT** [comment]
@dotnetprofessional Could you verify if this persists? If you change roles, it may take some time for the permission to be propagated to take effect in the data center. It is thus not recommended to use roles to grant JIT permissions. If you are temporarily granting a specific permission to someone, consider using SAS instead.

**Comment by dotnetprofessional** [comment]
Its not a propagation issue. If I access a resource that is under the same security that I didn't access previously then it works just fine. For example I have a CosmosDb and Storage Account, if I access the storage account prior to elevation it still won't work after elevation, but if I access the CosmosDb, its fine. Its only resources that I have accessed prior that are not accessible. Also restarting the tool resolves the issue (that's my current workaround). As I mentioned in the Bug I'm using JIT Access (ie Just in Time, the same as you use to access prod systems), so SAS isn't an option.

**Comment by MRayermannMSFT** [comment]
@dotnetprofessional what type of resource are you getting JIT access to, and where are you seeing the error that you can't access it? If the error is coming while browsing in the tree, you might need to refresh the tree, or refresh the parent node of the thing you're trying to work with.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having problems, please open a new issue.
