### ISSUE TITLE
[localization][query] Translation support

### ISSUE THREAD

**Issue by cristianosuzuki77** [microsoft/AzureStorageExplorer#3489]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:  

## Bug Description ##
Does the string in loc\en\src\Standalone\resources\Azure.json  "LabelEmptyNameDirectory": "\<no name\>" require translation?

**Comment by JasonYeMSFT** [comment]
Yes, it does. This is the name for a special type of resources whose actual name is an empty string "". The translation may be the translation of "no name" wrapped by "<>".

**Comment by MRayermannMSFT** [comment]
@cristianosuzuki77 do you have any other questions regarding this resource?
