### ISSUE TITLE
Disable the action 'Get Shared Signature Access' for deleted blobs

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#349]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180622.2
**Commit**: d667aec0
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Go to Subscription -> Storage Accounts.
2. Enable soft delete -> Open one blob container and upload one blob to it.
3. Delete the uploaded blob -> Switch to 'Deleted blobs' -> Right click the deleted blob then check the context menu.

#### Expected Experience: ####
The action 'Get Shared Signature Access' is disabled.

#### Actual Experience: ####
The action 'Get Shared Signature Access' is enabled and fail to display the blob contents after pasting the SAS URI to IE.
![ie](https://user-images.githubusercontent.com/34729022/41844684-7b440c44-7860-11e8-9491-1d98f8d94d3f.png)

**Comment by MRayermannMSFT** [comment]
@v-xuanzh  , it looks like Jason merged a fix for this into his feature branch. Next time he has you test the feature branch, or after we merge it into master, you can verify the fix.

**Comment by v-xuanzh** [comment]
OK, thanks you. :)
