### ISSUE TITLE
[localization][query] Translation assistance

### ISSUE THREAD

**Issue by cristianosuzuki77** [microsoft/AzureStorageExplorer#3490]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:  

## Bug Description ##
Question for the string "If enabled, Storage Explorer will automatically download updates when available. Storage Explorer must be restarted for this setting to be applied. This setting does not apply to Snap installs of Storage Explorer." found in the file loc\en\src\Standalone\resources\Shell.json, 
- does "Snap installs" mean the installation of Snap package or quick installation?

**Comment by JasonYeMSFT** [comment]
It means installing Storage Explorer from the Snapstore. See [Storage Explorer snap](https://snapcraft.io/storage-explorer)

**Comment by MRayermannMSFT** [comment]
@cristianosuzuki77 do you have any other questions regarding this resource?
