### ISSUE TITLE
[localization][query] Translation assistance

### ISSUE THREAD

**Issue by cristianosuzuki77** [microsoft/AzureStorageExplorer#3491]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:  

## Bug Description ##
Question for the string "Clone..." found in the file "loc\en\src\Standalone\resources\Azure.json" 

- Could you give more context of this string? What is it intent?

**Comment by JasonYeMSFT** [comment]
This is the label of a button that will prompt a dialog for the user to enter a name and then clone the resource with the new name. So the translation would be the translation of "clone" followed by "...", where the "..." means the button will prompt a dialog.

**Comment by MRayermannMSFT** [comment]
@cristianosuzuki77 do you have any other questions regarding this resource?
