### ISSUE TITLE
Microsoft storage explorer error

### ISSUE THREAD

**Issue by spgituser** [microsoft/AzureStorageExplorer#3492]
**Is your feature request related to a problem? Please describe.**
Details:
["FetchError:request to https://myblobstorage.blob.core.windows.net/?sv=2019-12-12&ss=bfqt&srt=sco&sp=rwdlacupx&se=2021-03-31T06:03:14Z&st=2020-08-27T23:03:14Z&spr=https&sig=oJRNpdRbXEfSR2acxff%2F%2FYpeIPYycW1LQ%3D&include=metadata&comp=list failed, reason: unable to get local issuer certificate"]

please recommend what needs to be done to resolve this

**Comment by MRayermannMSFT** [comment]
Please try following our troubleshooting guide for cert issues: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C1804#error-self-signed-certificate-in-certificate-chain-and-similar-errors

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
