### ISSUE TITLE
Error: unable to get local issuer certificate

### ISSUE THREAD

**Issue by steskalja** [microsoft/AzureStorageExplorer#3494]
**Storage Explorer Version**: 1.15.0
**Build Number**: 20200827.3
**Platform/OS**: Windows 10 2004
**Architecture**: x64

## Bug Description ##
Unable to retrieve child resources.

Details:
unable to get local issuer certificate

## Steps to Reproduce ##
1. Attach storage account using account name and key
2. Expand storage account
3. Select File Shares
4. Expand File Shares

## Expected Experience ##
See all files shares enumerated

## Actual Experience ##
Error occurs:

Unable to retrieve child resources.

Details:
unable to get local issuer certificate

## Additional Context ##
Behind a zScaler proxy

**Comment by MRayermannMSFT** [comment]
Please refer to the trouble shooting guide for help with certs: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C1804#error-self-signed-certificate-in-certificate-chain-and-similar-errors

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
