### ISSUE TITLE
cannot accest any storage account, fails on auth even though proper auth is in place

### ISSUE THREAD

**Issue by An1matedDavid** [microsoft/AzureStorageExplorer#3495]
**Storage Explorer Version**: 1.15.0
**Build Number**: 20200827.3 
**Platform/OS**: macOS Catalina
**Architecture**: x64 
**Regression From**:  was working in 1.14.2

## Bug Description ##
cannot accest any storage account. fails auth even though i have proper auth and was working previously with no change.
error:
Unable to retrieve child resources.

Details:
["RestError:﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.\nRequestId:92733108-301e-007c-6768-7d1c6f000000\nTime:2020-08-28T18:24:36.7750860Z</Message></Error>"]

**Comment by jinglouMSFT** [comment]
When did you exactly get this error message?  Did you get it right after you upgraded SE on the first start of the new Storage Explorer?  Have you tried to re-authenticate to see if it resolved the problem? Thanks.

**Comment by elvogel** [comment]
Getting this too after the recent upgrade to 1.15.0 - whenever I try expanding a storage account I get this:

```
Unable to retrieve child resources.

Details:
["TypeError:Object prototype may only be an Object or null: undefined"]
```

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having problems please open a new issue.
