### ISSUE TITLE
Unable to add Azure account with device code flow enable and receiving "Unable to sign in: Could not get the list of tenants" 

### ISSUE THREAD

**Issue by rs64454** [microsoft/AzureStorageExplorer#3496]
**Storage Explorer Version**: 1.14.2
**Build Number**: 20200715.2
**Platform/OS**: Windows 10
**Architecture**: ia32
**Regression From**:  no

## Bug Description ##

The user is trying to add Azure account with device code flow. After the code has been entered and user authenticated the browser window redirects back to the Storage Explorer and it shows "Unable to sign in: Could not get the list of tenants."

## Steps to Reproduce ##
1. Enable device code in the settings 
2. Right click on the Storage Account --> Add Account
3. Copy the device code and paste into browser that pops up for the device code
4. After picking the user account, the browser window will display message that the user can close
5. The Storage Explorer gets focus and it does not show the account and shows the error under the "Activities" Pane.

## Expected Experience ##
It should have added and displayed the users subscription  

## Actual Experience ##
Nothing gets added.

## Additional Context ##
This is being done via the corporate VPN

**Comment by MRayermannMSFT** [comment]
@rs64454 

Is there a reason you are using device code flow? If you are having issues with the default sign in setting, we recommend trying the following configurations in this order:
- enable Microsoft Authentication Library (MSAL), disable device code flow
- enable Microsoft Authentication Library (MSAL), enable device code flow
- disable Microsoft Authentication Library (MSAL), enable device code flow

Please try the first bullet and let us know if that works.

Beyond that point, was there any additional error details beyond just "Unable to sign in: Could not get the list of tenants."?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having problems please open a new issue.
