### ISSUE TITLE
couldint Open Blob Containers

### ISSUE THREAD

**Issue by AmeenMS** [microsoft/AzureStorageExplorer#3498]
Unable to retrieve child resources.

Details:
["RestError:﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.\nRequestId:360e6e5d-401e-00ec-4def-7e36ef000000\nTime:2020-08-30T17:02:37.3294355Z</Message></Error>"]

**Comment by MRayermannMSFT** [comment]
@AmeenMS what type of resource are you trying to access?
- blob container (ADLS Gen2)
- blob container (non-ADLS Gen2)
- queue
- file share
- table

**Comment by MRayermannMSFT** [comment]
Closing due to lack of follow-up by the original issue author. Please open a new issue if you are still having problems.
