### ISSUE TITLE
'Undelete' is enabled when there is no deleted blob

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/AzureStorageExplorer#350]
Storage Explorer Version: 1.2.0
Platform/OS Version: Windows10/ MacOS High Sierra /Linux Ubuntu 16.04
Architecture: x64
Build Number: 20180622.1
Commit: d667aec0
Regression From: Not a Regression

Steps to Reproduce:
1. Right click 'Blob Containers' node and select 'Configure Soft Delete Policy' to enable soft delete.
2. Navigate to 'Deleted blobs' and make sure there is no deleted blob.
3. Check the ''Undelete' button.

#### Expected Experience: ####
'Undelete' is disabled when there is no deleted blob

#### Actual Experience: ####
'Undelete' is enabled when there is no deleted blob
![actual](https://user-images.githubusercontent.com/34729092/41845331-aa4ed800-7862-11e8-87aa-58b8a1502c05.png)

**Comment by MRayermannMSFT** [comment]
@v-dantch , it looks like Jason merged a fix for this into his feature branch. Next time he has you test the feature branch, or after we merge it into master, you can verify the fix.
