### ISSUE TITLE
Unable to retrieve child resources.  Details: ["FetchError:request to https://stapacsalesdldevncus.blob.core.windows.net/?include=metadata&comp=list failed, reason: self signed certificate in certificate chain"]

### ISSUE THREAD

**Issue by nasunkar** [microsoft/AzureStorageExplorer#3504]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:

**Comment by MRayermannMSFT** [comment]
Please follow our troubleshooting guide for addressing self signed cert issues: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C1804#error-self-signed-certificate-in-certificate-chain-and-similar-errors

Also, some additional questions:
- was this working for you in a previous version of Storage Explorer? Or did you upgrade to 1.15 recently and this broke then?
- how are you connecting to your storage resource?
   - sign in and browse subscription
   - attach storage account directly
   - attach container directly

**Comment by MRayermannMSFT** [comment]
Closing due to lack of follow-up by the original issue author. Please open a new issue if you are still having problems.
