### ISSUE TITLE
Auto retry for "The specified table is being deleted. Try operation later."

### ISSUE THREAD

**Issue by etm-admin** [microsoft/AzureStorageExplorer#351]
We are using the latest version. 

If would be great if ASE could retry automatically if it encounters a "specified table is being deleted" error e.g. during a paste of a table to another storage account.

**Comment by craxal** [comment]
Please provide the following when posting new issues:
- Storage Explorer version
- Platform
- Architecture
- Regression
- Repro steps
- Expected behavior
- Actual behavior

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
