### ISSUE TITLE
Azure Storage Explorer for mac (ver 1.15) - Unable to retrieve child resources.

### ISSUE THREAD

**Issue by ah6511** [microsoft/AzureStorageExplorer#3511]
Unable to retrieve child resources.

Details:
["FetchError:request to https://az-204-train.blob.core.windows.net/?include=metadata&comp=list failed, reason: tunneling socket could not be established, statusCode=503"]

**Comment by MRayermannMSFT** [comment]
@ah6511 some questions:
- was this working for you in a previous version of Storage Explorer? Or did you upgrade to 1.15 recently and this broke then?
- how are you connecting to your storage resource?
   - sign in and browse subscription
   - attach storage account directly
   - attach container directly
- do you have any in app proxy settings enabled?
- do you have environment variables `HTTP_PROXY` `HTTPS_PROXY` set at your OS level?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of follow-up by the original issue author. Please open a new issue if you are still having problems.
