### ISSUE TITLE
not able to get a container-level shared access signature

### ISSUE THREAD

**Issue by stein321** [microsoft/AzureStorageExplorer#3513]
**Storage Explorer Version**: 1.15.0
**Build Number**: 20200827.3 
**Platform/OS**: macOS Catalina
**Architecture**: x64
**Regression From**: two versions ago

## Bug Description ##
UI for "generate container-level shared access signature URI" has disappeared from the options when selecting "get shared access signature" on a vhd.

## Steps to Reproduce ##

1. have a vhd to share
2. Right click on on a vhd and click "get shared access signature"
2. ideally see https://docs.microsoft.com/en-us/azure/marketplace/partner-center-portal/media/vm/create-sas-uri-storage-explorer.png , but I don't see that bottom checkbox 
![image](https://user-images.githubusercontent.com/5521816/91778906-d5aae000-eba8-11ea-9d27-f590b39917a3.png). documentation for this is here: https://docs.microsoft.com/en-us/azure/marketplace/partner-center-portal/get-sas-uri.

**Comment by JasonYeMSFT** [comment]
@stein321 You can create a container level SAS from the context menu of the container node in the left hand side tree view. This is for preventing people from accidentally sharing resources because the receiver of the SAS url can modify the path of the blob and poke for other blobs in the container.

**Comment by stein321** [comment]
@JasonYeMSFT can you link documentation on how to do that?

**Comment by JasonYeMSFT** [comment]
Unfortunately there is no documentation for that. I put a screenshot indicating how to do that. Basically you can go to the container node on the left hand side and select the "Get Shared Access Signature..." action and follow the instructions in the dialog. It will generate a container level SAS for the container you selected.

<img width="677" alt="image" src="https://user-images.githubusercontent.com/39359541/92153950-df675a00-edd9-11ea-93cb-31ac466d6d4d.png">
