### ISSUE TITLE
The account name is missed in the SAS URI of one Emulator queue

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3514]
**Storage Explorer Version:** 1.15.0
**Build**: 20200831.3
**Branch**: master
**Platform/OS:** Windows 10
**Emulator Version:** 5.10.0.0
**Architecture**: ia32
**Regression From:** Previous release(1.13.1)

**Steps to reproduce:**

1. Install and run Emulator -> Launch Storage Explorer.
2. Expand 'Local & Attached' -> Storage Accounts -> (Emulator - Default Ports) (Key).
3. Right click the Queues node -> Create a queue.
4. Right click the queue -> Click 'Get Shared Access Signature...' -> Click the 'Create' button on the 'Shared Access Signature' dialog.
5. Observe the URI on the 'Shared Access Signature' dialog.

**Expect Experience:**
The account name displays in the URI.
![image](https://user-images.githubusercontent.com/41351993/91828750-1838ef00-ec73-11ea-92d5-4b0758028810.png)

**Actual Experience:**
The account name is missed in the URI.
![image](https://user-images.githubusercontent.com/41351993/91828726-12dba480-ec73-11ea-9fd7-98a262a45249.png)

**Comment by JasonYeMSFT** [comment]
@v-xianya I have tried it and it seems already fixed. Could you help verify if this still reproduces?

**Comment by v-xianya** [comment]
@JasonYeMSFT Verified this issue on build 20200922.5. Reproduce.

**Comment by JasonYeMSFT** [comment]
A fix has been merged.
