### ISSUE TITLE
Display an extra file '.DS_Store' in the uploaded folder after uploading the folder which contains an empty folder and a non-empty folder/file 

### ISSUE THREAD

**Issue by v-xinda** [microsoft/AzureStorageExplorer#3516]
**Storage Explorer Version:** 1.15.0
**Build**: 20200831.3
**Branch**: master
**Platform/OS:** MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Create a file share -> Upload one folder contains an empty folder and a non-empty folder/file.
2. Expand the folder and check the result.

**Expect Experience:**
There is no extra file display in the folder. 

**Actual Experience:**
Display an extra file '.DS_Store' in the folder.
![image](https://user-images.githubusercontent.com/57662131/91834897-3a366f80-ec7b-11ea-9659-4d302cc4f6f9.png)

**More Info:**
This issue also reproduces for the blob container.

**Comment by MRayermannMSFT** [comment]
@v-xinda .DS_Store is a hidden file present in all directories on macOS. It is expected that the file is uploaded as well if you upload an entire folder.
