### ISSUE TITLE
Url contains an extra / when attaching with Azure AD

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#3518]
**Storage Explorer Version**: 1.15.0
**Platform/OS**: Windows/macOS/Linux
**Regression From**:  1.14.2

## Bug Description ##
When attaching with Azure AD to a Gen2 path, we incorrectly store a url with an extra slash, causing the listing of resources return nothing.

## Steps to Reproduce ##
Attach to a Gen2 path using Attach With Azure AD
Open that attachment

## Expected Experience ##
See the resources.

## Actual Experience ##
See an empty list of resources.

**Comment by MRayermannMSFT** [comment]
This was probably a reporting of this bug: https://github.com/microsoft/AzureStorageExplorer/issues/3512
