### ISSUE TITLE
Client does not handle 'AccessDeniedByFirewall' well

### ISSUE THREAD

**Issue by rolanddb** [microsoft/AzureStorageExplorer#3520]
We have protected our Data Lake so that it is only accessable from the office IP and VPN.

If I forgot to connect to the VPN, the web portal will give a very clear error:

```
ERROR
AccessDeniedByFirewall

MESSAGE
The client IP '1.2.3.4' is not allowed, meanwhile the request doesn't originate from an allowed virtual network, based on the configuration of the Azure Data Lake account 'my_account_name'.
```

However, Azure Storage Explorer does not handle this specific error, and suggests to reauthenticate. This will never solve the problem, and sends users in a frustrating, never ending loop.

![Capture](https://user-images.githubusercontent.com/445130/91957254-12d8b480-ed06-11ea-80ce-639d2fa00eb9.PNG)

It would be much more user friendly if the specific error (AccessDeniedByFirewall) is shown to the user, so that they are not send down the wrong path.

**Comment by MRayermannMSFT** [comment]
@rolanddb is this for ADLS Gen1, ADLS Gen2?

Additionally, is the firewall protecting a specific ARM resource, or the subscription as a whole? 

Did you follow any docs to setup this firewall, and if so, could you share those with us?

**Comment by MRayermannMSFT** [comment]
@rolanddb ? Are you still seeing this issue? Can you answer the questions in my previous reply. Thanks!

**Comment by rolanddb** [comment]
@MRayermannMSFT This is with ADLS gen1. Firewall setup was done in another team. I no longer work for the company where this occured, so unfortunately I am unable to recover more details. Sorry!
