### ISSUE TITLE
Storage Explorer complains about .NET Core 2.1

### ISSUE THREAD

**Issue by dontmesswithbill** [microsoft/AzureStorageExplorer#3522]
**Storage Explorer Version**: 1.15.0
**Build Number**: unknown
**Platform/OS**: CentOS 7.8
**Architecture**: x64
**Regression From**:  

## Bug Description ##
When snap run storage-explorer is ran, Storage Explorer comes up, but then it displays the following error message: To run Microsoft Azure Storage Explorer on Linux, you must have .NET Core 2.1 installed. Please make sure .NET Core 2.1 is properly installed before launching the application again.

## Steps to Reproduce ##
1. Follow [instructions to install storage explorer](https://snapcraft.io/install/storage-explorer/centos).
2. snap run storage-explorer

**Comment by MRayermannMSFT** [comment]
@dontmesswithbill have you run storage explorer from snap on your machine before?

**Comment by dontmesswithbill** [comment]
I was able to install and run storage explorer on an identical machine before. That was a previous version and I don't recall what I did to get around this error, but I don't know even if it will work with this updated version but I figured it's a common error.

**Comment by MRayermannMSFT** [comment]
@dontmesswithbill for snap installs this is a pretty uncommon error. Snap is supposed to take care of installing dependencies (such as .NET core). Unfortunately the dev who is our expert on Linux/snap is on vacation this week, so I'll need some time to spin up a VM and get some snap specific troubleshooting steps for you.

**Comment by dontmesswithbill** [comment]
Thanks, I'm also interested in getting this working without snap, because it has other drawbacks. For example to upgrade storage explorer, it requires deleting all the snap/azure-explorer subdirectories that exist for every user that has used it. I've tried untarring the archive and running it but I get an error about a password manager server. Is this something you can help with here, or should I create a separate ticket?

**Comment by dontmesswithbill** [comment]
Hi, any update on this? This is coming from internal Microsoft, is there a better place where I can open a ticket?

**Comment by dontmesswithbill** [comment]
Update: This morning I tried launching storage explorer on a machine and got the error message. Then I tried it again later today and it worked with no error. It seems random.

**Comment by teknoraver** [comment]
I have the same error on Fedora 33, even with .NET 2.1 installed:

```
$ rpm -qa 'dotnet-*'
dotnet-runtime-deps-2.1-2.1.23-1.x86_64
dotnet-host-3.1.9-1.fc33.x86_64
dotnet-hostfxr-2.1-2.1.23-1.x86_64
dotnet-runtime-2.1-2.1.23-1.x86_64
```

**Comment by MRayermannMSFT** [comment]
Are y'all seeing this on the latest release/s of storage explorer?

**Comment by teknoraver** [comment]
I have a different error now:

The authentication library used by Storage Explorer has failed to start properly. Please ensure you have .NET Core 2.1 installed. If .NET Core 2.1 is already installed then refer to the troubleshooting guide for help. Verbose authentication logging has been enabled.

TypeError:Cannot read property 'getAllAccounts' of undefined

I still have the runtime:
$ rpm -qa 'dotnet-*'
dotnet-runtime-deps-2.1-2.1.28-1.x86_64
dotnet-hostfxr-2.1-2.1.28-1.x86_64
dotnet-runtime-2.1-2.1.28-1.x86_64
dotnet-host-5.0.7-1.fc34.x86_64

**Comment by MRayermannMSFT** [comment]
@teknoraver are you able to run `dotnet --info`?

**Comment by teknoraver** [comment]
@MRayermannMSFT
```
$ dotnet --info

Host (useful for support):
  Version: 2.1.28
  Commit:  612cb8b183

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.1.28 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by nolanwagener** [comment]
@MRayermannMSFT I actually have this same error. Here's my output for `dotnet --info`:
```
.NET SDK (reflecting any global.json):
 Version:   5.0.400
 Commit:    d61950f9bf

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.400/

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  5.0.400 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.9 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

I cannot find the logs you are referring to.

**Comment by nolanwagener** [comment]
Now Storage Explorer is working on my machine, even though I did not do anything...

**Comment by MRayermannMSFT** [comment]
Yay? I guess I'll close this as mitigated for now then. Feel free to open a new issue if things start breaking again. Alternatively, you can also try our snap distribution. :)

**Comment by vahirua** [comment]
I had the same issue after snap install on Kubuntu 20.04.
But it only appeared when starting Explorer from the application menu.
Just starting it with `storage-explorer` in bash worked fine.
So my solution was to just change the command used for the application menu entry to `storage-explorer` and now it starts without complaining.
