### ISSUE TITLE
Unable to create a disk due to disk size, how do I fix?

### ISSUE THREAD

**Issue by the-data-detective** [microsoft/AzureStorageExplorer#3523]
Storage Explorer was unable to create the disk

Service response: {
  "name": "Error",
  "message": "The upload size in bytes 63276241408 - 512 bytes for the VHD footer (63276240896 in this case) must be a multiple of MiB.",
  "stack": "Error: The upload size in bytes 63276241408 - 512 bytes for the VHD footer (63276240896 in this case) must be a multiple of MiB.\n    at new RestError (C:\\Users\\jason\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\ms-rest-js\\dist\\msRest.node.js:2400:28)\n    at C:\\Users\\jason\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\ms-rest-js\\dist\\msRest.node.js:3544:37\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
  "code": "BadRequest",
  "statusCode": 400,
  "request": {
    "streamResponseBody": false,
    "url": "https://management.azure.com/subscriptions/84dcfa23-08cb-48a8-9089-b2009ef27100/resourceGroups/SandA/providers/Microsoft.Compute/disks/quickbooks2export-i-08757318c5c9ce2c0?api-version=2019-03-01",

**Comment by MRayermannMSFT** [comment]
@the-data-detective the error from the server is pretty clear. The size of VHD file you are using is not compatible. I think you'll need to resize the VHD.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
