### ISSUE TITLE
The default size of the 'Shared Access Signature' dialog for a storage account is unfriendly on Windows

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3526]
**Storage Explorer Version:** 1.15.0
**Build**: 20200903.1
**Branch**: main
**Platform/OS:** Windows 10
**Architecture**: ia32
**Regression From:** Not a regression

**Steps to reproduce:**
1. Right click one non-ADLS Gen2 storage account -> Click 'Get Shared Access Signature...'.
2. Observe the opened dialog.

**Expect Experience:**
Users can see the string 'Learn more about permissions' directly.

**Actual Experience:**
Users can't see string 'Learn more about permissions' directly and may miss it.
![image](https://user-images.githubusercontent.com/41351993/92098018-51a46280-ee0b-11ea-975f-5fd72b7638e5.png)

**Comment by craxal** [comment]
I would expect the several lists to have scrollbars, especially the Permissions list. I think something changed.
