### ISSUE TITLE
The action items and properties of the Blob Containers node are incorrect under SAS attached ADLS Gen2 storage accounts

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3527]
**Storage Explorer Version:** 1.15.1
**Build**: 20200904.2
**Branch**: main
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04 / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Attach one ADLS Gen2 storage account via SAS.
2. Expand the SAS attached ADLS Gen2 storage account -> Right click the **Blob Containers** node.
3. Check the **action items** on the context menu and the **properties** on its Properties panel.

**Expect Experience:**
The action items and properties are correct.
![image](https://user-images.githubusercontent.com/41351993/92218556-e078b400-eecb-11ea-9dfc-3f35a481a6d7.png)

![image](https://user-images.githubusercontent.com/41351993/92218532-d8b90f80-eecb-11ea-860b-8cab645c68db.png)

**Actual Experience:**
The action items and properties are incorrect.
![image](https://user-images.githubusercontent.com/41351993/92218505-d060d480-eecb-11ea-9e65-dee4206ba72a.png)
![image](https://user-images.githubusercontent.com/41351993/92218520-d5be1f00-eecb-11ea-81fc-98dd4f5dade3.png)

**More Info:**
This issue also reproduces for blob containers and blobs under SAS attached ADLS Gen2 storage accounts.

**Comment by JasonYeMSFT** [comment]
Even though we added generating Gen2 account SAS, we haven't fully supported SAS attachment of Gen2 account because we don't have a way to tell if it is a Gen2 vs blob account using a SAS.

**Comment by MRayermannMSFT** [comment]
Jason is going to re-disable generate SAS for gen2.
