### ISSUE TITLE
Add the string 'ADLS Gen2' append to the name of one SAS attached ADLS Gen2 storage account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3530]
**Storage Explorer Version:** 1.15.1
**Build**: 20200904.2
**Branch**: main
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04 / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regresssion

**Steps to reproduce:**
1. Attach one ADLS Gen2 storage account via SAS.
2. Check the SAS attached storage account.

**Expect Experience:**
Display the string 'ADLS Gen2' append to name of the SAS attached storage account.
Like the name & key attached ADLS Gen2 storage account.
![image](https://user-images.githubusercontent.com/41351993/92224182-099d4280-eed4-11ea-96bf-a035f875328e.png)

**Actual Experience:**
The string 'ADLS Gen2' doesn't display append to name of the SAS attached storage account.

**Comment by MRayermannMSFT** [comment]
@v-xianya Jason is going to re-disable generate SAS for gen2 until we're able to fix this experience.
