### ISSUE TITLE
It would be better to add the option 'Target Access Tier' to the upload dialog of ADLS Gen2 blobs

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3531]
**Storage Explorer Version:** 1.15.1
**Build**: 20200904.2
**Branch**: main
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04 / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regresssion

**Steps to reproduce:**
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Click 'Upload' -> Click 'Upload Folder...' or 'Upload Files...'.
3. Check the opened dialog.

**Expect Experience:**
It would be better to add the option 'Target Access Tier' to the dialog.

**Actual Experience:**
No option 'Target Access Tier' displays in the dialog.

**Comment by craxal** [comment]
This was implemented some time ago.
