### ISSUE TITLE
Storage explorer first downloads update and then prompt about the new version available

### ISSUE THREAD

**Issue by apgapg** [microsoft/AzureStorageExplorer#3535]
**Storage Explorer Version**: v1.15.1 and lower also
**Build Number**: 20200902.9 
**Platform/OS**: macOS
**Architecture**: x64
**Regression From**:  since beginning may be from 2 yrs back

## Bug Description ##
Whenever a new version is available, storage explorer first download it in background and then prompt the new version available. 
Now if i discard or leave notification as it is, then on restarting it again download the whole new update and again prompt the new update available

## Expected Experience ##
The prompt must be first displayed to user and on allowing by him then download the new update zip.

## Actual Experience ##
New update zip download occurs first and then prompt is displayed. Also everytime on restart then it downloads whole update again unless we update it to new version

**Comment by MRayermannMSFT** [comment]
@apgapg the current update behavior is by design. If you do want Storage Explorer to auto download updates you can disable that by going to Settings -> Application -> Updates -> Auto Download Updates, and un-check the checkbox.
