### ISSUE TITLE
Storage Explored Failure

### ISSUE THREAD

**Issue by shary-sharath** [microsoft/AzureStorageExplorer#3536]
**Storage Explorer Version**: 1.15.1
**Build Number**: 20200827.3
**Platform/OS**: Windows 10
**Architecture**: ia32
**Regression From**:  It was not working from last release 1.15.0.

## Bug Description ##
As soon as I open the Storage Explorer, it is throwing error:
Unable to retrieve child resources.

Details:
Invalid IV length

## Steps to Reproduce ##
1. Download latest version (1.15.1 or 1.15.0) of Azure Storage Explorer on Windows 10
2. Install the executable
3. Open Azure Storage Explorer (recently installed) and it will pop up a dialog box with above mentioned error. (Refer image1)

## Expected Experience ##
Azure explorer should open and list all the attached storage accounts, Azure subscriptions

## Actual Experience ##
Showing up a dialog box with error **Unable to retrieve child resources.** but listing up storage accounts (connected via Storage Connection String).
Not able to login to Azure subscription. Clicking on "Manage Account" -> "Add an account" option is allowing me to enter my login credentials but not happening anything after that. It keep showing a blank screen. Behind this blank screen, there would be another dialog box with message "Waiting for Authentication" (Refer Image 2)

## Additional Context ##
It is a serious issue and needs to be resolved as early as possible. It's impacting the business.

## Image 1 ##
![image](https://user-images.githubusercontent.com/51996588/92360014-c9270a00-f109-11ea-900d-56a1e74a6eb7.png)

## Image 2 ##
![image](https://user-images.githubusercontent.com/51996588/92360173-08555b00-f10a-11ea-8aaa-e62864b9e5f0.png)

**Comment by JasonYeMSFT** [comment]
The first error message is from the NodeJS's crypto module. Most likely it is due to a proxy cert. If you have imported a cert for your proxy, you may need to check if that is the correct one.

For the blank sign-in page, have you tried enabling MSAL (Microsoft authentication library)? You can find it in Settings -> Application - Sign-in

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. If you still run into this issue, please open a new one instead.
