### ISSUE TITLE
The translations of the string 'Blob Container' are inconsistent between strings 'Blob Container' and 'Blob Container (ADLS Gen2)' on the 'Attach with Azure AD' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3538]
**Storage Explorer Version:** 1.15.1
**Build**: 20200904.2
**Branch**: main
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04 / MacOS Catalina
**Architecture**: ia32/x64
**Language:** German
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Deutsch' -> Restart Storage Explorer.
3. Open connect dialog -> Select the localized option 'Add a resource via Azure Active Directory (Azure AD)' -> Click 'Next'.
4. Select one account -> Click 'Next' -> Expand the dropdown list of the 'Resource type' on the 'Attach with Azure AD' dialog.
5. Check the localized string.

**Expect Experience:**
The translations of the string 'Blob Container' are consistent between strings 'Blob Container' and 'Blob Container (ADLS Gen2)'.

**Actual Experience:**
The translations of the string 'Blob Container' are inconsistent between strings 'Blob Container' and 'Blob Container (ADLS Gen2)'

![image](https://user-images.githubusercontent.com/41351993/92369534-b6bdc800-f12b-11ea-83e0-96fd1fdd915c.png)

**More Info:**
1. This issue doesn't reproduce on other languages.
2. The screenshot in ENU.
![image](https://user-images.githubusercontent.com/41351993/92369487-aad20600-f12b-11ea-8556-4cb2d2eeca07.png)

**Comment by MRayermannMSFT** [comment]
These resources no longer exist.
