### ISSUE TITLE
range header for Blob service operations not work

### ISSUE THREAD

**Issue by unnhao** [microsoft/AzureStorageExplorer#3539]
**Storage Explorer Version**: 1.15.1
**Build Number**: 20200902.9
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  no

## Bug Description ##
According [specifying-the-range-header-for-blob-service-operations](https://docs.microsoft.com/en-us/rest/api/storageservices/specifying-the-range-header-for-blob-service-operations)

`Format 1: bytes=startByte-`
Format 1 Can't work! This problem I don't know what's going on, `Format 2` can work, but I need to use
HTML video tag to play the video,  video tag src can't set custom header to let requests have `Format2`. I am very troubled without this feature,

## Steps to Reproduce ##
1. Upload a video to the blob container
2. Use postman to get that video and enter header `Range: bytes=0-`
3. You will get 200 return, not 206. (I think this part wrong)
4. Use postman to get that video and enter header `Range: bytes=0-255`
5. You will get 206. 

## Expected Experience ##
Expected  `Range: bytes=0-` can also return 206;

## Actual Experience ##
get 200

## Additional Context ##
none

**Comment by MRayermannMSFT** [comment]
@unnhao this repo (and the issues for it) are for issues related to the Storage Explorer desktop application. Unfortunately we cannot help with your issue. If you're having problems with an API we recommend either:

- Open a support ticket
- If you are using an SDK, go to the repo for that SDK and ask the question there
