### ISSUE TITLE
Storage Exploer login issue on Windows 7 Professional Service pack 1

### ISSUE THREAD

**Issue by Sheikhin** [microsoft/AzureStorageExplorer#354]
**Storage Explorer Version**: 1.2
**Platform/OS Version**: Windows 7 Professional Service Pack 1 
**Architecture**: 64 bit .Net Framework 4.6.2
**Regression From**: Yes, it was working 2-3 months back
**Proxy server** : No Proxy server

#### Steps to Reproduce: ####
1. Latest version installed (1.2)
2. Launch the explorer and click on add account
3. Enter your Azure user name which is my email address.
4. It says redirecting to your company's login page
5. Not redirected and showing white blank screen

#### Expected Experience: ####

1. Should present the login screen to enter user name and password
2. Should show all my subscription in a tree view

#### Actual Experience: ####

Not redirecting to company login page

#### Tried so far: ####
1. Deleted the cache folder content
2. Deleted all the credentials from windows credentials manager 
3. Deleted all 3 .adalcache files
4. Installed again but no luck
5. SAS URI and connection string working fine

**Comment by craxal** [comment]
What version of .NET is installed on your machine?

**Comment by Sheikhin** [comment]
.NET Framework 4.6.2

**Comment by craxal** [comment]
Are you operating through any kind of proxy server?

**Comment by Sheikhin** [comment]
No proxy server.

**Comment by Sheikhin** [comment]
Any pointer or help?

**Comment by craxal** [comment]
Have you looked through our [troubleshooting guide](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?toc=%2fazure%2fstorage%2fqueues%2ftoc.json). Look for sign-in and certificate sections. Do any of those help?

**Comment by Sheikhin** [comment]
Yes, Tried all these steps and the same version is working fine on same network with Windows Server 2012 R2 Standard but it has VS 2017 installed on it so I need to first login on VS 2017 for cloud explorer and then Storage Explorer works fine and redirect and get the subscription properly.

**Comment by craxal** [comment]
My only guess is that maybe your workplace uses it's own certificates for authentication? @MRayermannMSFT, do you know anything that might help?

**Comment by Sheikhin** [comment]
I was thinking the same earlier then I tried on another machine having window Server 2012 and it worked (both machine are in same network) but to make it work I need to start the Visual Studio and open the cloud explorer. I don't know the relationship between login into cloud explorer and Azure Storage explorer.

**Comment by craxal** [comment]
Storage Explorer uses the same identity service used by Visual Studio. So if you have Visual Studio installed and you sign in from there, Storage Explorer will pick up the same credentials and vice-versa.

I don't think ADFS alone should cause problems, though we have been getting a lot of reports about issues with it. I can't think of what Visual Studio might've done to suddenly make Storage Explorer work, though...

Is #333 related at all to your issue?

**Comment by MRayermannMSFT** [comment]
Hey @Sheikhin , unfortunately  if you're getting a blank white screen we can only make guesses as to what might be going on. If you want, attacb the following fiddler traces (log out of everything before doing these):

- Logging into VS
- Logging into Stg Exp (and it failing of course)
- Logging into the Portal (use a private browser window and Chrome if possible)

That way we can try and find out where in the redirect process Storage Explorer/Chromium are failing.

**Comment by MRayermannMSFT** [comment]
@sheikhin , are you still having problems with the latest version of storage explorer, 1.12.0? If so, please try enabling and using MSAL. You can do this via Settings (gear icon on the left) -> Application -> Sign-In -> Enable Microsoft Authentication Library (MSAL)

**Comment by JasonYeMSFT** [comment]
Closing for now. Please open a new issue if you still encounter any problem.
