### ISSUE TITLE
About Manage Access in Storage Explorer 

### ISSUE THREAD

**Issue by go-shinyashiki** [microsoft/AzureStorageExplorer#3541]
**Storage Explorer Version**: 1.15.0
**Build Number**: 20200827.3
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  No

## Bug Description ##
I am using Storage Explorer and wants to grant per-user or per-group access to the folders in the storage account's BLOB containers (all sub-folders in the hierarchy).
I have set up users in Storage Explorer's Manage Access, but I can access all BLOB containers and folders in Storage Explorer.
Also, some BLOB containers can be accessed by accessing the Portal containers and some BLOB containers cannot be accessed.

[QUESTION]
1. In the Portal container, only the test container is visible, and the other containers are not visible. Why is this?
2. Why is all four containers visible in Storage Explorer?
3. Why is the test container configured to control user access but access restrictions are not working?
4. I want to deny a user access for a specific folder of container in Storage Explorer. What is the workaround?

## Steps to Reproduce ##
In Portal, only the test container is visible. 
![1](https://user-images.githubusercontent.com/63278166/92374866-4fa80f80-f13b-11ea-831e-29919fc9ab46.png)

Storage Explorer, there are In Storage Explorer, 4 containers visible.
![2](https://user-images.githubusercontent.com/63278166/92374884-56cf1d80-f13b-11ea-8b29-c7a4ea949dd4.png)

In Storage Explorer (preview) of Portal, 4 containers visible.
![3](https://user-images.githubusercontent.com/63278166/92374895-5a62a480-f13b-11ea-9a26-3d650376122f.png)

Manage Access setting of test container. The test container is set to User B. User A is not set.
![4](https://user-images.githubusercontent.com/63278166/92374909-5f275880-f13b-11ea-8ffa-eff951172ba6.png)

**Comment by MRayermannMSFT** [comment]
@go-shinyashiki 

> 2 In the Portal container, only the test container is visible, and the other containers are not visible. Why is this?
> 3 Why is all four containers visible in Storage Explorer?
> 4 Why is the test container configured to control user access but access restrictions are not working?

Is it possible that you still have/your users still have access to the keys of the Storage Account? Click on the node for the account and then look in the bottom left for primary and secondary key. If they are still there then that'll explain it. Storage Explorer always attempts to list keys (unless you disable that in settings). And if it can get the keys, it'll let you do things with them/it'll use them to list containers and blobs.

The other option is that you've given some sort of RBAC roles which are allowing you/users to see more than you intend. You can check under "Access Control (IAM)" in the portal to see what roles you've given yourself and users.

> I want to deny a user access for a specific folder of container in Storage Explorer. What is the workaround?

Assuming you've set everything up correctly, this should be possible with ACLs.

**Comment by go-shinyashiki** [comment]
Thanks for the reply. I will refer to it.
