### ISSUE TITLE
récupérer les ressources enfants

### ISSUE THREAD

**Issue by EMoh8** [microsoft/AzureStorageExplorer#3543]
Hi, 
I have the following issue, do you have an idea of what's problem :

Impossible de récupérer les ressources enfants.

Détails :
["FetchError:request to https://prodcampusmanuels.blob.core.windows.net/?include=metadata&comp=list failed, reason: read ECONNRESET"]

**Comment by MRayermannMSFT** [comment]
@EMoh8 the error ECONNRESET means that the network connection was reset.

- Are you seeing this consistently?
- Does this reproduce on other networks?
- Does this happen for other resources you try to access in Storage Explorer, or just this container?
- Are you behind a proxy?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still encountering this problem.
