### ISSUE TITLE
An extra scroll bar displays in the 'Undelete Blobs by Date' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3548]
**Storage Explorer Version:** 1.15.1
**Build**: 20200904.2
**Branch**: main
**Platform/OS**: Windows 10
**Architecture**: ia32
**Language:** Czech/ German/ French/ Hungarian/ Dutch
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Deutsch' -> Restart Storage Explorer.
3. Expand one storage account -> Blob Containers.
4. Upload one folder -> Right click it -> Select 'Undelete -> Undelete by Date...'.
5. Check the dialog.

**Expect Experience:**
No scroll bar displays in the dialog.

**Actual Experience:**
An extra scroll bar displays in the dialog.
![image](https://user-images.githubusercontent.com/41351993/92456856-0bc61080-f1f6-11ea-8d08-5fd35a648cac.png)

**Comment by MRayermannMSFT** [comment]
Let's make this a wee bit taller by default.
