### ISSUE TITLE
All strings are not localized in the 'Move Messages' dialog

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3549]
**Storage Explorer Version:** 1.15.1
**Build**: 20200904.2
**Branch**: main
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04 / MacOS Catalina
**Architecture**: ia32/x64
**Language**: ALL
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Deutsch' -> Restart Storage Explorer.
3. Expand one storage account -> Queues.
4. Open one queue -> Click 'Move -> Move Selected...' -> Check the 'Move Messages' dialog.

**Expect Experience:**
All strings are localized in the 'Move Messages' dialog.

**Actual Experience:**
All strings are not localized in the 'Move Messages' dialog.
![image](https://user-images.githubusercontent.com/54055206/92454894-99ecc780-f1f3-11ea-8061-6ef95764cb8a.png)

**More Info:**
This issue also reproduces after clicking 'Move -> Move All'.

**Comment by MRayermannMSFT** [comment]
I forgot to add the resource namespace to the loc project.
