### ISSUE TITLE
ADFS - Unable to retrieve configuration. Please verify that the ARM endpoint is correct.

### ISSUE THREAD

**Issue by tsjija** [microsoft/AzureStorageExplorer#355]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Windows 7 and Windows Server 2016
**Architecture**: x64
**Regression From**: None

#### Steps to Reproduce: ####
1. I have followed the exact steps from this guide: https://docs.microsoft.com/en-us/azure/azure-stack/user/azure-stack-storage-connect-se#connect-to-an-azure-stack-subscription-with-ad-fs-account
2. On step 4 in the guide we add an environment name and our custom Azure Resource Manager endpoint.
3. On step 5 in the guide, we try to press Sign in... But we get an error message.

#### Expected Experience: ####
Successfull sign in and we can now choose an active subscription.

#### Actual Experience: ####
An error is visible with this message: **Unable to retrieve configuration. Please verify that the ARM endpoint is correct.**

#### More info ####
I have tried to connect to the custom endpoint using a browser, and that works. So the endpoint is working.

**Comment by MRayermannMSFT** [comment]
@tsjija , can you please do the following.

1. Go to <your arm endpoint>/metadata/endpoints?api-version=1.0, for an example, if I was doing this for public Azure I would go to `https://management.azure.com/metadata/endpoints?api-version=1.0`
2. Copy and paste the response into a comment on this issue.

Thanks

**Comment by tsjija** [comment]
I have done your steps. I got an StatusCode: 200 and StatusDescription: OK , as a response. I don´t want to post the endpoints here. Do you need all of the json-response?

**Comment by MRayermannMSFT** [comment]
Yes, having the response will help me determine what is going wrong. You can send it to sehelp@microsoft.com if you are ok with us (Storage Explorer developers) seeing it. If not, then feel free to post a redacted version here (replace any sensitive parts of the URL with something else/more generic).

**Comment by tsjija** [comment]
Email sent to sehelp@microsoft.com

**Comment by MRayermannMSFT** [comment]
Hey @tsjija , did you do the [Prepare for connecting to Azure Stack
](https://docs.microsoft.com/en-us/azure/azure-stack/user/azure-stack-storage-connect-se#prepare-for-connecting-to-azure-stack) sectoin? If no, please do that section first. If yes, then can you please do the following:

1. Start Storage Explorer
2. Open dev tools (f12)
3. Use ctrl+p to open AzureEnvironmentsManager.js
4. Set a breakpoint on line 127, 'case 0: return [4 /*yield*/, identity_client_1.createConfigurationFromManagementEndpoint(mangagementEndpoint)];' by clicking on the line number
5. Use the connect dialog to add your custom environment
6. When the breakpoint is hit, use the step in button to step into the fuction
![image](https://user-images.githubusercontent.com/21112697/42233022-14e7b00e-7ea5-11e8-9d28-7177243e438e.png)
7. Once in the function (which is in a new file), set a breakpoint on line 143
8. Click continue (blue arrow near the step in button) to get to that breakpoint
9. Click the step over button (arrrow going over a dot, next to the continue button)

If you are now on line 144, hover over 'endpoints' in 'let endpoints = yield ...' and make sure they match the values you sent us. Continue to use the step over button to progress through the function until you get to the 'return config'.

If at any point an error occurs (you'll know this if the debugger leaves the function you entered in step 7), try to inspect debug values to find an error message, or, send us a screenshot of what you see and we'll let you know what variable has the error message.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
