### ISSUE TITLE
Authentication connects to the wrong organization

### ISSUE THREAD

**Issue by ttelcl** [microsoft/AzureStorageExplorer#3550]
**Storage Explorer Version**: 1.15.1
**Build Number**: 20200902.9
**Platform/OS**: Windows 10
**Architecture**: ia32
**Regression From**:  

## Bug Description ##
I try to authenticate to my "work account". In the authentication dialog I enter my e-mail address and select "professional/work account". So far everything is normal. However, instead of redirecting me to my employer's organizational login page, I get redirected to the login for one of the organizations where I have a "guest" account (not tied to any of my actual azure resources). I guess my e-mail is used as identifier for both, and somehow the wrong provider for my e-mail gets chosen instead of the default one

## Steps to Reproduce ##
1. Select the "accounts" tab
2. Select the "Add an account..." link
3. Select "Add an Azure Account", keep "Azure environment" on "Azure", click Next
4. The Microsoft Azure dialog appears. I enter my e-mail address
5. Select "Work or School account"
6. The "redirecting to my organization" step now redirects to the sign in page of an organization where I have a guest account, instead of to the sign in page of my employer.

### Additional:
7. Close that sign in page (without reacting to it). Another sign in page appears, now for yet another organization where I have a guest account
8. Close that sign in page as well.
9. Only now my employer's sign in finally appears

## Expected Experience ##
In step 6: see the sign in page of my employer (the e-mail's "main" organization), not any guest accounts

## Actual Experience ##
See steps 6, 7, 8, 9 above

## Additional Context ##
I haven't seen this weird sign in experience in other apps using azure login

**Comment by MRayermannMSFT** [comment]
@ttelcl I think what we're doing for #460 solves this issue. So I'm going to close this as duplicate. Please read through that thread, try the latest private build, and give us your feedback. If there are still problems related to auth/account mgmt, we can look into making new issues for those things.
