### ISSUE TITLE
Getting a certificate error

### ISSUE THREAD

**Issue by jellis6gaig** [microsoft/AzureStorageExplorer#3551]
**Storage Explorer Version**: 1.14.2
**Build Number**: 20200715.2
**Platform/OS**:  Windows 10? -->
**Architecture**:  x64? -->
**Regression From**: yes

## Bug Description ##

Get error when trying to load container
Unable to retrieve child resources.

Details:
["FetchError:request to https://ststatefileaccount.blob.core.windows.net/?include=metadata&comp=list failed, reason: unable to get local issuer certificate"]

## Steps to Reproduce ##

Unable to retrieve child resources.

Details:
["FetchError:request to https://ststatefileaccount.blob.core.windows.net/?include=metadata&comp=list failed, reason: unable to get local issuer certificate"]

## Expected Experience ##
The container contents should load

## Actual Experience ##
The container contents doesnt load says "Load more"

**Comment by aroradheeraj** [comment]
facing same issue from last 4 months.

**Comment by MRayermannMSFT** [comment]
Hey y'all, we have tips in our troubleshooting guide for addressing self signed cert issues: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C1804#error-self-signed-certificate-in-certificate-chain-and-similar-errors

Have y'all given any of those tips a shot?

**Comment by jellis6gaig** [comment]
I need to close this issue and it was a internal network error

**Comment by MRayermannMSFT** [comment]
@aroradheeraj please follow the troubleshooting guide. If you cannot resolve the cert issue after following the guide, please open a new issue.
