### ISSUE TITLE
The values of properties and the properties are not aligned sometimes when opening one table

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3552]
**Storage Explorer Version:** 1.15.1
**Build**: 20200909.3
**Branch**: main
**Platform/OS:** Windows 10
**Architecture**: ia32
**Regression From:** Previous release (1.14.2)

**Steps to reproduce:**
1. Expand one storage account -> Tables.
2. Create a table -> Add an entity for the table.
3. Close the table -> Reopen it several times.
4. Check the layout of the table.

**Expect Experience:**
The values of properties and the properties are always aligned.

**Actual Experience:**
The values of properties and the properties are not aligned sometimes.
![image](https://user-images.githubusercontent.com/41351993/92579350-a9d1dd80-f2bf-11ea-8126-57baed6fd34e.png)

**More Info:**
1. This issue also reproduces for one SAS attached table.
2. The values of properties and the properties are aligned after manually refreshing or **clicking on the table tab.**
3. The more details please see the record.
https://web.microsoftstream.com/video/85e9a3ff-0400-96f3-3dbe-f1eaf27ce8fa

**Comment by craxal** [comment]
I don't think this is a regression. I've seen this issue before; it's a problem with the jQuery datatable extension that allows columns to be resized. It can be reproduced by resizing columns when the table width is wider than the view.

**Comment by v-xianya** [comment]
We are going to close this issue because the table explorer is updated. (Build 20231025.1)
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/07050a95-0e1e-45eb-ac01-f07c4d12a7bb)
