### ISSUE TITLE
Allow auto-rehydrate for "download" operation

### ISSUE THREAD

**Issue by artisticcheese** [microsoft/AzureStorageExplorer#3553]
**Is your feature request related to a problem? Please describe.**
Right now when you click "download" a container with blobs process will download only the blobs with `readable` status (hot,cool) but will get stuck on `archive` tier and will not progress anymore (this is a bug on it's own). I think it would be good option to prompt user in such cases if they want to auto-rehydrate archived blobs.

**Describe the solution you'd like**
Upon download operation Azure Storage Explorer will check if any underlying blobs are in Archive tier and give an option to end user to auto-rehydrate or don't download those at all

**Describe alternatives you've considered**
Rehydrate blobs one by one or in bulk first before stating download operation

**Comment by MRayermannMSFT** [comment]
@artisticcheese rehydration can take a variable amount of time, sometimes multiple hours. Therefore, this isn't something we would add. We recommend you rehydrating your blobs manually before downloading.
