### ISSUE TITLE
Download file from Azure Storage Explorer shows path failed

### ISSUE THREAD

**Issue by Scarlettliuyc** [microsoft/AzureStorageExplorer#3555]
**Storage Explorer Version**: 1.15.1
**Build Number**: 
**Platform/OS**: Windows 10
**Architecture**:
**Regression From**:  

## Bug Description ##
When download file from Storage Explorer to the local on-prem Net drive, sometimes it shows path error. 
But the path can use and work for a long time.
This error happen already many months, It can happen once a week. 
When restart the Storage Explorer or restart PC it can work.
Almost more than five people have this issue, please help to check about it!!

## Steps to Reproduce ##
Login Storage Explorer->find the file, click download->save to on-prem Net drive. it shows error, not happen every time 

## Expected Experience ##
Please help to fix the issue, it's quite disturbed to restart Storage Explorer  every time
## Actual Experience ##

![image](https://user-images.githubusercontent.com/69622329/92676599-80af5c80-f354-11ea-81c3-69ff93f105e4.png)

## Additional Context ##

In addition, are there any way we can check the failed logs from Storage Explorer. Every time finish an action it can show in the bottom, but when close it and reopen the log disappeared. is it possible to  check the log history 

![image](https://user-images.githubusercontent.com/69622329/92676728-c2d89e00-f354-11ea-9f8f-7f4a6fc75b44.png)

Please help to check about this issue, we are appreciated for your reply.

**Comment by MRayermannMSFT** [comment]
@Scarlettliuyc whenever there is a failed download, can you please upload the AzCopy log file? You can find it by clicking "Open AzCopy Log" in the Activities panel.

**Comment by Scarlettliuyc** [comment]
thanks Matthew, this issue happened this morning 
I cannot attachment file. here is the part for path error,  it shows 404  Code: ResourceNotFound , but the path can work before, 
2020/09/14 23:39:42 Max open files when downloading: 2147483224 (auto-computed)
2020/09/14 23:39:42 ISO 8601 START TIME: to copy files that changed after this job started, use the parameter --include-after=2020-09-14T23:39:37Z
2020/09/14 23:39:42 WARN: Failed to check if the destination is a folder or a file (Azure Files). Assuming the destination is a file: -> github.com/Azure/azure-storage-file-go/azfile.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.8.0/azfile/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=ResourceNotFound) =====
Description=The specified resource does not exist.
RequestId:3922cfbf-b01a-001e-33f0-8a20f3000000
Time:2020-09-14T23:39:42.6423397Z, Details: 
   Code: ResourceNotFound
   GET https://sanzplibrary.file.core.windows.net/downloads/Serials/1.contents/Vanuatu_Daily_Post_contents.htm?restype=directory&se=2020-10-14t23%3A39%3A37z&sig=-REDACTED-&sp=rwl&sr=s&sv=2018-03-28&timeout=901
   User-Agent: [Microsoft Azure Storage Explorer, 1.14.2, win32,  AzCopy/10.5.0 Azure-Storage/0.8.0 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [fcc36a64-48dc-4354-76fd-91bc68d43a77]
   X-Ms-Version: [2019-02-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 404 The specified resource does not exist.
   Content-Length: [223]
   Content-Type: [application/xml]
   Date: [Mon, 14 Sep 2020 23:39:42 GMT]
   Server: [Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [fcc36a64-48dc-4354-76fd-91bc68d43a77]
   X-Ms-Error-Code: [ResourceNotFound]
   X-Ms-Request-Id: [3922cfbf-b01a-001e-33f0-8a20f3000000]
   X-Ms-Version: [2019-02-02]

**Comment by MRayermannMSFT** [comment]
@Scarlettliuyc since you've opened an ICM, please communicate through that only. Having 3 active forms of communication for 1 issue is not helpful.
