### ISSUE TITLE
Unable to retrieve child resources.  Details: ["FetchError:request to http://127.0.0.1:10000/devstoreaccount1/?include=metadata&comp=list failed, reason: connect ECONNREFUSED 127.0.0.1:10000"]

### ISSUE THREAD

**Issue by markmcdon7** [microsoft/AzureStorageExplorer#3558]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:

**Comment by markmcdon7** [comment]
Win10. storage explorer 1.15.1

Open blob in emulator gives error. AAD User has data contrib role.

**Comment by markmcdon7** [comment]
Emulator section just doesnt work. But don't need that anyway.

**Comment by MRayermannMSFT** [comment]
@markmcdon7 did you start the emulator before using Storage Explorer?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having problems please open a new issue.
