### ISSUE TITLE
High CPU usage from Chrome Helper on Mac after awaking from sleep

### ISSUE THREAD

**Issue by chlandsi** [microsoft/AzureStorageExplorer#3560]
**Storage Explorer Version**: 1.15.1
**Build Number**: 20200902.9 
**Platform/OS**: Mac
**Architecture**: x64
**Regression From**:  not sure, also observed from 1.14.1 on

## Bug Description ##
Storage Explorer uses a full CPU constantly, even when it's idle, after the mac is awakened from sleep. The CPU usage also stays present after closing the Storage Explorer app.

## Steps to Reproduce ##
1. Start storage explorer
2. Let the Mac go to sleep
3. Awake it; observe CPU in activity monitor and Chrome's Task Manager

<img width="463" alt="Screenshot 2020-09-10 at 13 39 59" src="https://user-images.githubusercontent.com/42998057/92724764-6d5bbb80-f36b-11ea-93c8-b279a101be8f.png">

## Expected Experience ##
Storage Explorer should not consume significant CPU when it's idle.

## Actual Experience ##
CPU usage is> 80% (see screenshot) constantly

**Comment by MRayermannMSFT** [comment]
@chlandsi that isn't Storage Explorer. This is what our processes look like:
<img width="365" alt="image" src="https://user-images.githubusercontent.com/21112697/93122375-3511f100-f67b-11ea-885a-4bf5a291b637.png">

**Comment by chlandsi** [comment]
Indeed, this was about Azure *Data* Explorer. Sorry for the noise.
