### ISSUE TITLE
Unable to retrieve child resources.

### ISSUE THREAD

**Issue by Eliutrod** [microsoft/AzureStorageExplorer#3562]
**Storage Explorer Version**: 1.15.1
**Build Number**: 20200902.9
**Platform/OS**: Windows Server 2012 R2
**Architecture**: x64
**Regression From**: First installation of 1.15.1 on the server

## Bug Description ##
We deployed an Azure storage account for Azure File Service. The File Share is active and integrated to AD for AD SMB/authentication. Storage Explorer was installed on the server that we need to move from to Azure File; we add a connection with a storage account and key. The connection is successful but, opening File Shares the error "Unable to retrieve child resources" popup. Here is the complete error message:

Unable to retrieve child resources.

Details:
This request is not authorized to perform this operation.
RequestId:a48af9d0-d01a-005e-7e8c-8714d6000000
Time:2020-09-10T16:05:02.0575539Z

## Actual Experience ##
We verify the IAM for proper permits. The account has Storage Account Contributor, Storage Blob Data Contributor, Storage Blob Data Reader. The Firewall/virtual networks configuration is active by - Selected networks with two public IP and Allow trusted Microsoft services. If we try to access from Azure Portal/Storage Explorer, it work and we can browse the File Shares.

Additional troubleshooting, we remove/detach the connection, restart Storage Explorer, add the account but, same error. Also, verify the Release Notes for 1.15.1 and some post but without any success.

## Additional Context ##
Only to update the post. We just tested with Storage Explorer 1.14.2 on Windows 10 Pro and it work without any issue. Next, we will test on the Windows Server 2012 R2 with version 1.14.2.

**Comment by MRayermannMSFT** [comment]
Jing, please try connecting with account name and key in 1.15 and see if you can access file shares.

**Comment by jinglouMSFT** [comment]
I can't repro this with 1.15.1 on Windows 10.  Name/Key connection worked as expected.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having problems please open a new issue.
