### ISSUE TITLE
Add the properties 'Last Modified' & 'Public Read Access' to the Properties panel for one ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3567]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20200911.5
**Branch**: main
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04 / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Check its Properties panel.

**Expect Experience:**
The properties 'Last Modified' & 'Public Read Access' display on the Properties panel.

**Actual Experience:**
No properties 'Last Modified' & 'Public Read Access' display on the Properties panel.
![image](https://user-images.githubusercontent.com/41351993/92892499-63a98500-f44b-11ea-9317-10ed5b5e7883.png)

**More Info:**
The properties 'BlobPublicAccess' and 'LastModified' display on the Properties dialog of one ADLS Gen2 blob container.
![image](https://user-images.githubusercontent.com/41351993/92891567-9dc65700-f44a-11ea-9f6c-88e0bc3072bf.png)

**Comment by rjallaMSFT** [comment]
@v-xianya @MRayermannMSFT 
In addition to the Property Panel, the LastModified column is also missing in the view as shown in the below picture. Will this be fixed part of this issue? Appreciate your response!

![image](https://user-images.githubusercontent.com/71530411/93727901-6f075980-fb8b-11ea-9bae-d9efbd27855a.png)

**Comment by MRayermannMSFT** [comment]
I added blob public access in 1.18, taking care of last modified now.

**Comment by MRayermannMSFT** [comment]
@v-xianya @rjallaMSFT the behavior in your latest screenshot is expected.

**Comment by v-xianya** [comment]
@MRayermannMSFT 
Thank you for the updates!
The 'Public Read Access' is added in the Properties panel.
![image](https://user-images.githubusercontent.com/41351993/111248723-6cbb1f00-8645-11eb-97bf-fe7888309ec0.png)

**Comment by v-limu** [comment]
This issue has been fixed on build 20210319.2. so we close it.
![image](https://user-images.githubusercontent.com/54055206/111722730-60310380-889d-11eb-95b5-ed1eca924db6.png)
