### ISSUE TITLE
Fail to download one version without current version under one connected public blob container

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3569]
**Storage Explorer Version:** 1.15.1
**Build**: 20200911.5
**Branch**: main
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04 / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one storage account (make sure the blob versioning is enabled) -> Blob Containers (make sure the soft delete is enabled).
2. Create one blob container (set its 'Public Read Access' to 'container') -> Upload one blob to it -> Delete the blob.
3. Connect the blob container to public blob container -> Open the connected public blob container.
4. Switch to 'All blobs and blobs without current version' view -> Try to download the version -> Check the result.

**Expect Experience:**
Succeed to download the version without current version.

**Actual Experience:**
Fail to download the version without current version.
![image](https://user-images.githubusercontent.com/54055206/92898712-cbae9a00-f450-11ea-8061-a4514339b68e.png)
![image](https://user-images.githubusercontent.com/54055206/92898726-cea98a80-f450-11ea-8067-f9d464b8686e.png)

**More Info:**
In release 1.15.1:
![image](https://user-images.githubusercontent.com/54055206/92898812-dff29700-f450-11ea-8ebd-964509027a2b.png)
![image](https://user-images.githubusercontent.com/54055206/92898827-e254f100-f450-11ea-84a8-cc92f0825925.png)

**Comment by JasonYeMSFT** [comment]
I tested in our latest build and this seems to already been fixed.

**Comment by v-limu** [comment]
Verified on build 20210506.3. This issue doesn't reproduce. So we close it.
