### ISSUE TITLE
Unable to download PST file from Azure Storage explorer

### ISSUE THREAD

**Issue by kaushalyapoothera** [microsoft/AzureStorageExplorer#357]
**Storage Explorer Version**: 
**Platform/OS Version**: 
**Architecture**: 
**Regression From**: 

#### Steps to Reproduce: ####
1. 
2.

**Comment by kaushalyapoothera** [comment]
{
  "name": "StorageError",
  "message": "Forbidden",
  "stack": "Error\n    at Function.StorageServiceClient._normalizeError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:1191:23)\n    at Object.StorageServiceClient._processResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:738:50)\n    at Request.processResponseCallback [as _callback] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:311:37)\n    at Request.self.callback (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\node_modules\\request\\request.js:186:22)\n    at emitTwo (events.js:125:13)\n    at Request.emit (events.js:213:7)\n    at Request.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\node_modules\\request\\request.js:1163:10)\n    at emitOne (events.js:115:13)\n    at Request.emit (events.js:210:7)\n    at IncomingMessage.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\node_modules\\request\\request.js:1085:12)",
  "code": "Forbidden",
  "statusCode": 403,
  "requestId": "36b82bc8-801e-0084-7260-0d979b000000"
}

**Comment by kaushalyapoothera** [comment]
Cna someone please tell me what is this forbidden error issue on Azure Storage Explorer?

**Comment by jinglouMSFT** [comment]
Can you please provide more info on exactly what you did?  What type of account you used?  Was it an Exchange 365 storage account? Thanks.

**Comment by craxal** [comment]
Please take a look at the first comment of this issue and provide the information listed when opening new issues.

**Comment by kaushalyapoothera** [comment]
Hello, 

Its an hosted exchange account. 
I exported the PST from hosted exchange on premises server. Uploaded it to azure storage explorer using Azure command line. 
And then when i download the pst file to my local computer, it gives me this error

**Comment by craxal** [comment]
@kaushalyapoothera, please look at the very first comment up top of this issue and provide the indicated information. We can't properly investigate your issue without this information.

**Comment by kaushalyapoothera** [comment]
Hello Craxal, 

We are moving our on premises Microsoft Hosted Exchange mailboxes ( mailboxes currently present in ON PREMISES SERVER ) to Microsoft Exchange online Plan 1 (O365). We are exporting the PSTs and giving the server path as \\server\foldername\file.pst for storing the same on the server.

Then we have gone ahead and uploaded those PSTs into Azure Storage Explorer using Azure command line as mentioned in this link **https://support.office.com/en-us/article/use-network-upload-to-import-your-organization-s-pst-files-to-office-365-103f940c-0468-4e1a-b527-cc8ad13a5ea6#step2**. 

I have attached the screenshot on how it looks in the end, 
![image](https://user-images.githubusercontent.com/32931614/41954308-b7ee48e4-79eb-11e8-9305-8762872f511d.png)

Now there's this option called as download as seen here : 
![1](https://user-images.githubusercontent.com/32931614/41954926-e97812ac-79ee-11e8-8016-6d1f4175d281.png)

Now when I click on download option, it says initializing download and then says download failed after a while. please check this 
![2](https://user-images.githubusercontent.com/32931614/41954980-240dcfd8-79ef-11e8-8f7a-1038a1d1c882.png)

When clicked on Details, it displays the message I have pasted in my question
![3](https://user-images.githubusercontent.com/32931614/41955048-68f37256-79ef-11e8-9481-eb5a8ee9ad6e.png)

**I am copy pasting the error message here again:** 


<Add any additional details about this error>

Error details:
{
  "name": "StorageError",
  "message": "Forbidden",
  "stack": "Error\n    at Function.StorageServiceClient._normalizeError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:1181:23)\n    at Object.StorageServiceClient._processResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:736:50)\n    at Request.processResponseCallback [as _callback] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:311:37)\n    at Request.self.callback (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\node_modules\\request\\request.js:187:22)\n    at emitTwo (events.js:106:13)\n    at Request.emit (events.js:194:7)\n    at Request.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\node_modules\\request\\request.js:1044:10)\n    at emitOne (events.js:96:13)\n    at Request.emit (events.js:191:7)\n    at IncomingMessage.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\node_modules\\request\\request.js:965:12)",
  "code": "Forbidden",
  "statusCode": 403,
  "requestId": "3898927c-001e-007b-03d8-0daa03000000"
}


Any and all help would be appreciated guys! Thank you!

**Comment by craxal** [comment]
@kaushalyapoothera, it appears that you are connected to this account using a SAS URL. The "Forbidden" error is likely due to a lack of permissions or expired token. Can you share with us the SAS token you received from Office 365 (minus the signature portion)?

How long was your download running before it failed? Did you click retry or start another download? If so, was the outcome any different?

We're still missing some very basic information from you. If the above is not part of the issue, we need the following if we're going to move forward:
- The version of Storage Explorer you're using.
- The platform/OS version you're running on.
- Your machine's architecture.
- Specific steps to help us reproduce your issue.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
