### ISSUE TITLE
Succeed to move an empty subfolder to the root directory which has one same folder

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3570]
**Storage Explorer Version:** 1.15.1
**Build**: 20200911.5
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create one blob container -> Create a folder -> Open the folder.
3. Create a subfolder using the same name -> Right click the subfolder.
4. Click 'Move...' action -> Type '/' in the 'Destination directory' box -> Click 'Move'.
5. Check the result.

**Expect Experience:**
Fail to move the empty subfolder.

**Actual Experience:**
Succeed to move the empty subfolder.
![image](https://user-images.githubusercontent.com/54055206/92902675-0a921f00-f454-11ea-9354-dcaf2bb8dc15.png)

**Comment by JasonYeMSFT** [comment]
This is kind of by design. The behavior of the Move API is that
- If no folder/file with the name exists, the file/folder is moved to the in the destination directory
- If a folder with the name exists, the file/folder is moved under that folder
- If a file with the name exists, the move fails.
