### ISSUE TITLE
Use session.resolveProxy

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#3573]
https://www.electronjs.org/docs/api/session#sesresolveproxyurl

We should be able to use the above API to provide some sort of auto proxy URL detection via that API. Ideas/options include:

- tell user that we think a proxy exists and offer to set the proxy settings for them
- just auto fill in proxy settings without asking
- etc.

**Comment by craxal** [comment]
I'm going to close this, as the point of this issue is to detect system proxy settings, and we have a work item for that already.
