### ISSUE TITLE
Figure out a better UX when existing proxy env variables exist

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#3574]
When there are HTTP_PROXY/HTTPS_PROXY env variables at the OS, Storage Explorer picks those variables up on startup. This can lead to confusion when the in app proxy settings are blank but Storage Explorer is talking to a proxy! This experience needs to be improved.

**Comment by craxal** [comment]
Storage Explorer has replaced the "Use Proxy" setting with the new "Proxy Configuration" setting. This setting lets you choose from where Storage Explorer will retrieve its configuration setting. The options are:

- **Do not use proxy** - disables the use of a proxy. This has the same functionality as the old disabled "Use Proxy" setting, except that Storage Explorer will ignore proxy environment variables.
- **Use environment variables** - reads the values of HTTPS_PROXY and HTTP_PROXY environment variables to determine the proxy configuration. If no suitable values are found, Storage Explorer acts like like proxy is configured. Storage Explorer will ignore proxy environment variables if this option is not set.
- **Use app proxy settings** - reads the values of the Protocol, Hostname, and Port app settings to determine the proxy configuration. If credentials are enables and present, Storage Explorer will also use those credentials. This has the same functionality as the old enabled "Use Proxy" setting, except that Storage Explorer will ignore proxy environment variables.
