### ISSUE TITLE
Uploading a CSS file appends a semicolon to content type

### ISSUE THREAD

**Issue by MarcAnnous** [microsoft/AzureStorageExplorer#3575]
**Storage Explorer Version**: 1.15.1
**Build Number**: 20200902.9
**Platform/OS**: Windows 10 Pro
**Architecture**: x64
**Regression From**:  Not Tested

## Bug Description ##
Uploading a CSS file appends a semicolon to the content type (resulting in text/css;). The file is served normally and that does not create any apparent issue. However, when served through Azure's CDN with compression enabled, the file is not compressed because the returned content-type response header is text/css; which cannot be in the list of formats to compress.
This happens only with CSS. It does not happen with application/javascript or image/jpeg.
The workaround is to change the content type after uploading so the bug is minor but it took a week of investigation so this may save time for someone else.

## Steps to Reproduce ##
1. Select a blob container.
2. Upload a CSS file to any location.
3. After the upload is complete, check the blob's content type.

## Expected Experience ##
Content type should be text/css.

## Actual Experience ##
Content type is text/css;.

**Comment by MRayermannMSFT** [comment]
@MarcAnnous when you say "the returned content-type response header is text/css; which cannot be in the list of formats to compress", is the list of compressable content-types something that Azure CDN defines? And if so, do you have a link to any Azure CDN docs which list out all compresssable types?

**Comment by MarcAnnous** [comment]
There's a pre-defined list: https://docs.microsoft.com/en-us/azure/cdn/cdn-improve-performance
This list cannot be modified currently on Azure CDN Standard by Microsoft.

On Azure CDN by Verizon and Akamai the list can be changed but it only accepts valid mime types without additional characters.
Screenshot:
![cdncompressionvalidmime](https://user-images.githubusercontent.com/20798084/93121707-9199fe00-f6c5-11ea-894a-53d03f9964d4.jpg)

**Comment by JasonYeMSFT** [comment]
AzCopy is going to ship a fix for this bug in their 10.6.1 release.

**Comment by MRayermannMSFT** [comment]
We'll be shipping a new version of AzCopy in our 1.16.0 release, and that version will have the fix as well.
