### ISSUE TITLE
Update 'undefined service' to 'Table service' in CORS Settings log for the Table service

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3578]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20200912.3
**Branch**: main
**Platform/OS:** Windows 10 / CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Right click the 'Tables' node.
2. Click 'Configure CORS Settings...' -> Click 'Save' button on the popped dialog.
3. Check the activity log.

**Expect Experience:**
Display 'Table service' in the activity log.

**Actual Experience:**
Display 'undefined service' in the activity log.
![image](https://user-images.githubusercontent.com/41351993/93067688-209b1c00-f6ae-11ea-9661-5d60d5323306.png)

**Comment by JasonYeMSFT** [comment]
A fix has been merged.
