### ISSUE TITLE
Keep the descriptions of the CORS Setting logs consistent between the four services

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3579]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20200912.3
**Branch**: main
**Platform/OS:** Windows 10 / CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one normal storage account.
2. Configure and save the CORS rules for Blob, File Share, Table and Queue services.
3. Check the activity logs.

**Expect Experience:**
The descriptions of CORS Setting logs are consistent.

**Actual Experience:**
The descriptions of CORS Setting logs are inconsistent.
![image](https://user-images.githubusercontent.com/41351993/93068979-b4211c80-f6af-11ea-9034-a93f328db12c.png)

**More Info:**
1. Show the below activity log when the CORS Setting dialog of queue service opens.
2. For Blob, File Share and Table services, no such activity log shows.
![image](https://user-images.githubusercontent.com/41351993/93069172-f21e4080-f6af-11ea-8f0a-8dc2cd5bf42c.png)

**Comment by JasonYeMSFT** [comment]
A fix has been merged.
