### ISSUE TITLE
Bigger font shows after refreshing one store procedure editor

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#358]
Storage Explorer Version: 1.2.0
Platform/OS Version: Windows 10/MacOS High Sierra/Linux Ubuntu 16.04
Architecture: ia32/x64
Build Number: 20180627.6
Commit: 6fdb639d
Regression From: Not a regression

#### Steps to Reproduce: ####
1. Go to Subscription -> Create one document account.
2. Drill down from Document Account -> Database -> Collection -> Create a storage procedure.
3. Make sure the editor is opened then click the 'Refresh' button on the toolbar.

#### Expected Experience: ####
The font size doesn't change after refreshing the editor.

#### Actual Experience: ####
Bigger font shows after refreshing the editor.
![font](https://user-images.githubusercontent.com/34729022/41966191-08979154-79ee-11e8-9f5b-695a83e83b61.png)

**Comment by MRayermannMSFT** [comment]
Bug reported as fixed. Closing.
