### ISSUE TITLE
Keep a consistent behavior when typing a number to the metadata keys between blob containers and file shares

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3581]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20200912.3
**Branch**: main
**Platform/OS:** Windows 10 / CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one storage account -> Blob Containers and File Shares.
2. Open one blob container -> Select one blob -> Click 'Properties...' -> Add Metadata -> Type a number for the metadata key.
3. Check the result.
4. Open one file share -> Select one file -> Click 'Properties...' -> Add Metadata -> Type a number for the metadata key.
5. Check the result.

**Expect Experience:**
Keep a consistent behavior when typing a number for the metadata keys between blob containers and file shares.

**Actual Experience:**
Show inconsistent behaviors when typing a number for the metadata keys between blob containers and file shares.

![image](https://user-images.githubusercontent.com/54055206/93069305-1a0da400-f6b0-11ea-8615-abfb2ce6074b.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into main.
