### ISSUE TITLE
No 'Rehydration priority' option shows in Update Access Tier dialog when selecting several blob

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3583]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20200912.3
**Branch**: main
**Platform/OS:** Windows 10 / CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload two blobs as block blob.
3. Select the two blobs then right click -> Click 'Change Access Tier...'.
4. Check whether the 'Rehydration priority' option shows on the 'Update Access Tier' dialog.

**Expect Experience:**
Display the 'Rehydration priority' option.

**Actual Experience:**
No 'Rehydration priority' option displays.
![image](https://user-images.githubusercontent.com/41351993/93072791-7bd00d00-f6b4-11ea-9556-673fe952a350.png)

**More Info:**
This issue also reproduces for Blob folders.

**Comment by v-limu** [comment]
Verified 20200916.1. This issue has been fixed. So close it
