### ISSUE TITLE
Error popup when opening app

### ISSUE THREAD

**Issue by ZippoLag** [microsoft/AzureStorageExplorer#3585]
**Storage Explorer Version**: started happening after 1.15.1 update, did not resolve on installing older builds
**Platform/OS**: Windows Server 2012 R2
**Architecture**: x64
**Regression From**:  was working fine before update, but unsure which version I had previously

## Bug Description ##
As soon as I open the Microsoft Azure Storage Explorer I get a pop-up with a unexpected error invalid integer 1#3427 on zone-node.js from AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError with "Restart", "Close Application" and "Ignore" buttons. "Ignore" seems to allow me to use the application normally on v1.14.2, but any time the app is started I still get the same message.

## Steps to Reproduce ##
1. Open the app

## Expected Experience ##
App should open without an error message

## Actual Experience ##
The following error message ensues anytime the app is opened:
![image](https://user-images.githubusercontent.com/755062/93118636-f25e1200-f696-11ea-8928-07fb834ef509.png)

## Additional Context ##
I've tried removing my account details, uninstalling Storage Explorer and re-installing other versions to no avail.

**Comment by MRayermannMSFT** [comment]
Duplicate of #3607
