### ISSUE TITLE
Storage don't load

### ISSUE THREAD

**Issue by BrunnaMaiaradaSilva** [microsoft/AzureStorageExplorer#3586]
Não é possível recuperar recursos filho.

Details
["RestError:﻿<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:***\nTime:2020-09-14T18:35:04.5097617Z</Message><AuthenticationErrorDetail>Authentication scheme Bearer is not supported in this version.</AuthenticationErrorDetail></Error>"]

**Comment by MRayermannMSFT** [comment]
@BrunnaMaiaradaSilva 
- what version of Storage Explorer are you using
- what are you trying to do, work with blobs, file shares, queues, tables, disks, cosmos db, etc?

**Comment by MRayermannMSFT** [comment]
@BrunnaMaiaradaSilva were you able to fix the issue? If so, can you share your resolution?
