### ISSUE TITLE
Unable to View Contents of IoT Edge Device's Blob Storage Module

### ISSUE THREAD

**Issue by ejectbutton** [microsoft/AzureStorageExplorer#3587]
**Storage Explorer Version**: 1.15.1
**Build Number**: 20200902.9
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  1.13.1

## Bug Description ##
I have an IoT Edge device running a local blob storage module. When updating to v1.15.1, I can now no longer connect to this storage via a connection string.

## Steps to Reproduce ##
1. Install blob storage module on an Edge device
2. Open Azure Storage Explorer v1.15.1
3. Choose Connect to Azure Storage with 'Use a connection string' option
4. Follow this format for your connection string: DefaultEndpointsProtocol=http;BlobEndpoint=http://**youripaddress**:11002/**accountName**;AccountName=**accountName**;AccountKey=**accountKey**

## Expected Experience ##
When I attempt to expand my Blob Containers, I see a list of all existing containers.

## Actual Experience ##
I get an error with the following description:

Unable to retrieve child resources.

Details:
["RestError:﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>InvalidHeaderValue</Code><Message>The value for one of the HTTP headers is not in the correct format.\nRequestId:b4386115-66bd-4784-9b75-ba4cf6b1e507\nTime:2020-09-14T18:46:06.7653884Z</Message><HeaderName>x-ms-version</HeaderName><HeaderValue>2019-12-12</HeaderValue><ExceptionDetails><ExceptionMessage>The value 2019-12-12 provided for request header x-ms-version is invalid.</ExceptionMessage><StackTrace>Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.InvalidHeaderProtocolException: The value 2019-12-12 provided for request header x-ms-version is invalid.\r\n   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.RunVersionCheck()\r\n   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.ProcessImpl(AsyncIteratorContext`1 async)+MoveNext()</StackTrace></ExceptionDetails></Error>"]

## Additional Info ##

* My blob storage module is using this URI:  mcr.microsoft.com/azure-blob-storage:latest
* When using v1.13.1, this approach works as expected. I've temporarily reverted back to 1.13.1 for my use cases.

**Comment by MRayermannMSFT** [comment]
@ejectbutton the latest version of Storage Explorer is unfortunately incompatible with the latest version of Blobs IoT. As you discovered, you'll need to revert back to 1.13.1. The Blobs IoT team is aware of this and has plans to update Blobs IoT.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response/known workaround.

**Comment by shawnweisfeld** [comment]
FYI: you can download v 1.13.1 here: https://github.com/Microsoft/AzureStorageExplorer/releases/tag/v1.13.1
