### ISSUE TITLE
snap complains that it can't connect to the password manager service

### ISSUE THREAD

**Issue by dontmesswithbill** [microsoft/AzureStorageExplorer#3588]
**Storage Explorer Version**: 1.15.1
**Build Number**: Unknown
**Platform/OS**: CentOS 7.8
**Architecture**: x64
**Regression From**:  Was working in a previous version, version unkonwn.

## Bug Description ##
An error message comes up when starting storage explorer that says, "Microsoft Azure Storage Explorer must be connected to the system's password manager service to keep your data safe, but the service plug has not been connected yet. Please run the following command before launching the application again: snap connect storage-explorer:password-manager-service :password-manager-service"

Even after running that command, the error message still comes up.

## Steps to Reproduce ##
1. install snap
2. install storage explorer
3. snap run storage-explorer

## Expected Experience ##
No popup error message.

## Actual Experience ##
Error message. Then when clicking OK the program exits.

## Additional Context ##
These are muilti-user Linux machine with hundreds of users, some of them want to use Storage Explorer on these machines so that they can transfer files which exist on NFS mounts. Installing Storage Explorer on their own Windows machines does not work as a solution.

**Comment by craxal** [comment]
Related to #3522.

**Comment by sampeson** [comment]
I got this working by running `snap connect storage-explorer:password-manager-service` without the last part. I could not copy the command from the dialog, needed to write it by hand which is error-prone. 

`$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.10
DISTRIB_CODENAME=groovy
DISTRIB_DESCRIPTION="Ubuntu 20.10"
$ snap list storage-explorer
Name              Version  Rev  Tracking       Publisher            Notes
storage-explorer  1.18.1   21   latest/stable  msft-storage-tools✓  -
`

**Comment by craxal** [comment]
@dontmesswithbill Is this still an issue for you? If so, have you tried @sampeson's suggestion?
