### ISSUE TITLE
Display a confused warning message when dequeueing an expired message

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#359]
Storage Explorer Version: 1.2.0
Platform/OS Version: Windows 10/MacOS High Sierra/Linux Ubuntu 16.04
Architecture: ia32/x64
Build Number: 20180627.6
Commit: 6fdb639d
Regression From: Not a regression

#### Steps to Reproduce: ####
1. Go to Subscription -> Storage Accounts.
2. Open one queue -> Add a new message and make sure it will expire in a short time.
3. Wait for it to expire then dequeue the expired the message.(Without refreshing the queue editor)
4. Check the popped warning message.

#### Expected Experience: ####
It should display '... has been removed or expired...'

#### Actual Experience: ####
Dispaly a confused warning message.
![message](https://user-images.githubusercontent.com/34729022/41967017-25276036-79f0-11e8-8876-3072d6daccbb.png)

**Comment by craxal** [comment]
It says "...has been removed *or* modified by someone else". Two possibilities. Either the message doesn't actually exist in the queue anymore or it's been modified. I'm not sure how this message is confusing.

**Comment by v-xuanzh** [comment]
Hi Craig, I'm confused about the warning message:

The expired messages are hidden and don't dispaly in the current queue, but its not that have been removed.
