### ISSUE TITLE
Exployer Load Container Folder List Very Slow

### ISSUE THREAD

**Issue by sccds** [microsoft/AzureStorageExplorer#3590]
**Storage Explorer Version**:  1.15.1
**Build Number**: 20200902.9
**Platform/OS**: macOS High Sierra
**Architecture**: x64
**Regression From**:  

## Bug Description ##
Loading file list in a large size container is very slow

## Steps to Reproduce ##
Blob Disk Storage
my container include 55 files (include metadata file) in the container root path  
statistics for the container: Statistics for xxx/result: 1,406,230 blobs; 18,874,826,244,046 bytes (not including snapshots); Completed at Tue Sep 15 2020 14:13:28 GMT+0800 (China Standard Time)  
double click container, load list takes very long time

## Expected Experience ##
List folders in <= 10s, can split pages

## Actual Experience ##
The full list loading time is >= 55s

## Additional Context ##
I understand
Compare with Azure Portal, if we check the Azure Portal api, it sends many sub requests. and get a split data.

**Comment by MRayermannMSFT** [comment]
@sccds some questions for you:

- What is "Blob Disk Storage"?
- Is the 55 seconds to load the root or a sub folder?
- You say that the Azure Portal sends many sub requests, can you elaborate on that?
- Have you looked to see what/how many requests Storage Explorer is sending, and if so, what did you see?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still encountering this problem.
