### ISSUE TITLE
Storage Explorer crashes when directly searching one resource on Linux and Mac

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3592]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20200915.3
**Branch**: main
**Platform/OS:** CentOS 7.6.1810 (Core) / Ubuntu 16.04 / macOS High Sierra
**Architecture**: x64
**Regression From:** Previous release(1.13.1)

**Steps to reproduce:**

1. Launch Storage Explorer -> Input one resource to the Search box -> Search.
2. Wait a moment (Linux no more than 2 minutes / Mac no more than 6 minutes) -> Check the result.

**Expect Experience:**
Storage Explorer works well and the resource shows well.

**Actual Experience:**
Storage Explorer crashes.
![image](https://user-images.githubusercontent.com/54055206/93189854-3de6ed80-f775-11ea-8896-da52d1984478.png)

**Comment by MRayermannMSFT** [comment]
A fix for this was merged into main for 1.16.
