### ISSUE TITLE
Only display ‘More’ on the toolbar for tabs opened in quick succession against ADSL Gen1 accounts

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3593]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20200915.3
**Branch**: main
**Platform/OS:** Windows 10 / CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand 'Data Lake Storage Gen1 (Preview)'.
2. Open at least two accounts tab via double clicking in quick succession.
3. Check the toolbar of the opened tabs except the last opened tab.

**Expect Experience:**
The actions display well on the toolbar. 
![image](https://user-images.githubusercontent.com/41351993/93195200-886b6880-f77b-11ea-8141-2ef33e8c9dc5.png)

**Actual Experience:**
Only display ‘More’ on the toolbar.
![image](https://user-images.githubusercontent.com/41351993/93195094-6a056d00-f77b-11ea-96bf-8882d8e6ef98.png)

**More Info:**
1. Details please see the record: https://web.microsoftstream.com/video/2b40a1ff-0400-96f3-dbab-f1eaf738b824
2. The actions display well after resize the editor.
3. Related bug: [2809](https://github.com/microsoft/AzureStorageExplorer/issues/2809)

**Comment by JasonYeMSFT** [comment]
We have added code to manually raise a "resize" event to recalculate the layout of the toolbar items while working on https://github.com/microsoft/AzureStorageExplorer/issues/5908. The same code change will also fix this issue.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220728.1. Fixed.
