### ISSUE TITLE
Unable to open and view contents of Blob Container

### ISSUE THREAD

**Issue by cjmcgnow** [microsoft/AzureStorageExplorer#3595]
Unable to retrieve child resources.

Details:
["RestError:﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.\nRequestId:b7039efa-401e-0020-6388-8b8c67000000\nTime:2020-09-15T17:51:25.5367916Z</Message></Error>"]

**Comment by MRayermannMSFT** [comment]
@cjmcgnow this error message means you don't have the permissions needed to do what you are trying to do.

Can you give some more details like:

- When did this happen?
- What are you trying to access?
- What type of authentication are you using, sign in, SAS, key?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still encountering this problem.
