### ISSUE TITLE
["Error:Unable to retrieve authentication token."]

### ISSUE THREAD

**Issue by RCMatos** [microsoft/AzureStorageExplorer#3596]
Unable to retrieve child resources.

Details:
["Error:Unable to retrieve authentication token."]

**Comment by MRayermannMSFT** [comment]
@RCMatos at what point in the application does this happen?

**Comment by ytsruh** [comment]
I can confirm I get the same issue. Storage Explorer for Max v1.15.1

I get the error whenever I open or reopen the application. I am logged out of my account and I need to re-authenticate 3 times before I can access my account.

I've tried removing my account and re-adding without any success. I've also tried to uninstall & re-install the application without any success

**Comment by MRayermannMSFT** [comment]
@rcmatos and @ytsruh can you please try going to Settings (gear on the left) -> Services -> Disks, uncheck the checkbox, and then restart storage explorer?

**Comment by ytsruh** [comment]
Hi all, sorry to report that this didn't resolve the issue for me. However it did take the number of times that I had to re authenticate from 3 down to 2.

Any other suggestions?

**Comment by ytsruh** [comment]
Just a quick note to say that enabling "Microsoft Authentication Library (Preview)" appears to have resolved this issue for me
