### ISSUE TITLE
Fail to change the public read access for one Premium blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3598]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20200916.1
**Branch**: main
**Platform/OS:** Windows 10 / CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one premium storage account -> Blob Containers.
2. Create a blob container -> Right click it -> Click 'Set Public Access Level...'.
3. Select the option 'Public read access for container and blobs' on the popped dialog -> Click 'Apply'.
4. Check the result.

**Expect Experience:**
Succeed to change the public read access.

**Actual Experience:**
Fail to change the public read access.
![image](https://user-images.githubusercontent.com/41351993/93312229-8d8eed00-f839-11ea-8f77-8bbe0b1e05b8.png)

Error details:
`"message": "One of the headers specified in the request is not supported.\n`

**More Info:**
This issue also reproduces when selecting the option 'Public read access for blobs only'.

**Comment by MRayermannMSFT** [comment]
Did some research. Public access is not supported for premium premium gpv1 and premium gpv2 accounts. You can confirm this in the portal:
![image](https://user-images.githubusercontent.com/21112697/104361686-a34eaf00-54c7-11eb-9875-59dc779064b7.png)
![image](https://user-images.githubusercontent.com/21112697/104361727-b06b9e00-54c7-11eb-9ce3-c7fb8155951e.png)
We'll switch to hiding the action in that case.

**Comment by MRayermannMSFT** [comment]
Fix merged into main.
