### ISSUE TITLE
Fail to get tags for one blob

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3599]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20200916.1
**Branch**: main
**Platform/OS:** Windows 10 / CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Right click the blob -> Click 'Edit tags...' -> Check the result.

**Expect Experience:**
Succeed to get tags.

**Actual Experience:**
Fail to get tags.
![image](https://user-images.githubusercontent.com/41351993/93314129-f4ada100-f83b-11ea-8e06-4a715f8b31ee.png)

Error details:
` "message": "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<Error><Code>FeatureNotEnabled</Code><Message>A required feature for this operation is not enabled on the account.\nRequestId:61de05dd-801e-0070-7704-8c1aee000000\nTime:2020-09-16T08:38:06.8878283Z</Message><FeatureName>BlobIndex</FeatureName></Error>",`

**Comment by JasonYeMSFT** [comment]
I was planning to communicate this today. The feature is only enabled in certain regions and you need to enroll your subscription to enable the feature. See https://docs.microsoft.com/en-us/azure/storage/blobs/storage-manage-find-blobs?tabs=azure-portal#setting-blob-index-tags for details.

**Comment by v-xianya** [comment]
@JasonYeMSFT Got it. thanks for the updates. We are going to close this issue.
