### ISSUE TITLE
Blob Container view looks like it has focus when it doesn't

### ISSUE THREAD

**Issue by JakeRadMSFT** [Microsoft/AzureStorageExplorer#36]
**Storage Explorer Version:1.0.0 RC 1**

**OS Version: All**

**Steps to Reproduce:**
1. Open Blob Container
2. Select Blob
3. Move focus to toolbar

**Expected Experience:**
Blob should still be selected but should be grey
**Actual Experience:**
Blob is still selected but blue which makes it look like it still has focus

**Comment by MRayermannMSFT** [comment]
Same for actions and properties items.

**Comment by MRayermannMSFT** [comment]
Fixed in 1.0.0!
