### ISSUE TITLE
The deleted directory can be downloaded successfully

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#360]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180627.6
**Commit**: 6fdb639d
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Go to Subscription -> Storage Accounts.
2. Open one file share which contains one directory at least -> Delete the directory.
3. When the directory is being deleted -> 'Download' this directory(do not click 'Save') ->Click 'Save' after deleting the directory successfully.

#### Expected Experience: ####
Fail to download the directory with 'resource not found' like below.
![expect](https://user-images.githubusercontent.com/34729022/41967714-b9494dfa-79f1-11e8-9897-61da0b96faf6.png)

#### Actual Experience: ####
The directory can be downloaded successfully.

**Comment by craxal** [comment]
Curious. My guess is perhaps the download request somehow gets received before the delete request (it does take some time for activities to get started). Does the delete operation eventually start? If so, how long does it take and does it successfully delete?

**Comment by v-xuanzh** [comment]
The delete opreation can be completed. 
The time it takes depend on whether the deleted directory is large or not.
If the directiry is small, it will be deleted successfully in a short time.

**Comment by craxal** [comment]
If that's the case, I'm not worried about this situation. Downloads and deletes operate in different processes, so it seems very possible, if you're fast enough, to download something you started a delete operation for. I don't think that's something most users are going to try and do.
