### ISSUE TITLE
Update the string 'Edit tags…' to 'Edit Tags…' for one blob

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3602]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20200917.2
**Branch**: main
**Platform/OS:** Windows 10 / CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one storage account -> Blob Containers.
2. Open one blob container -> Upload one blob to it.
3. Check the context menu of the blob.

**Expect Experience:**
Display 'Edit Tags...' in the context menu.

**Actual Experience:**
Display 'Edit tags...' in the context menu.
![image](https://user-images.githubusercontent.com/54055206/93441399-533d5280-f902-11ea-8bdb-4140d30a802a.png)

**More Info:**
 Update the string 'Add tag' to 'Add Tag' in the Blob Tags dialog.
![image](https://user-images.githubusercontent.com/54055206/93441344-4f113500-f902-11ea-8c55-8a6cf600337b.png)

**Comment by v-xianya** [comment]
Verified this issue on build 20200929.1. Fixed.
