### ISSUE TITLE
It is better to remove the action 'Add tag' in the Blob Tags dialog for one blob snapshot

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3603]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20200917.2
**Branch**: main
**Platform/OS:** Windows 10 / CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one storage account (make sure the 'blob tags' feature is enabled) -> Blob Containers.
2. Create a new blob container -> Upload one blob to it.
3. Create snapshot for the blob -> Right click the blob snapshot -> Click 'Edit tags...'.
4. Check the Blob Tags dialog.

**Expect Experience:**
It is better to remove the action 'Add tag' in the Blob Tags dialog.

**Actual Experience:**
An extra action 'Add tag' shows in the Blob Tags dialog.
![image](https://user-images.githubusercontent.com/54055206/93446096-c4313a00-f903-11ea-91ff-802243250aeb.png)

**More Info:**
Show a failed activity log after saving the blob tags for the blob snapshot.
![image](https://user-images.githubusercontent.com/54055206/93446528-e75be980-f903-11ea-9260-d61653494f14.png)
![image](https://user-images.githubusercontent.com/54055206/93446545-ea56da00-f903-11ea-87a4-04dda4892a7f.png)

**Comment by v-xianya** [comment]
Verified this issue on build 20200930.3. Fixed.
