### ISSUE TITLE
The tags of the blob are not updated after promoting one version

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3604]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20200917.2
**Branch**: main
**Platform/OS:** Windows 10 / CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one storage account (make sure the 'blob tags' and the 'blob versioning' features are enabled)  -> Blob Containers.
2. Create a new blob container -> Upload one blob to it -> Add tags and metadatas for the blob.
3. Click 'Manage History -> Manage Versions' -> Update tags for the blob.
5. Select one version -> Click 'Promote Version'.
6. Check the Blob Tags dialog for the blob.

**Expect Experience:**
The tags of the blob are updated.

**Actual Experience:**
The tags of the blob are not updated.

**More Info:** 
This issue doesn't reproduce after promoting one blob snapshot.

**Comment by v-xianya** [comment]
@JasonYeMSFT  Verified this issue on build 20201009.2. 
The current behavior: The tags for the current version **shows empty** after promoting version.
Details please see the record:
https://msit.microsoftstream.com/video/e868a1ff-0400-9fb2-4566-f1eb0a1092f5

**Comment by JasonYeMSFT** [comment]
The standard copy api requires us to specify which tags to set instead of copying the tags over. 
![image](https://user-images.githubusercontent.com/39359541/95613447-d2153f00-0a19-11eb-9e00-599a0144e989.png)

I will add this support for this when AzCopy supports uploading with tags.

**Comment by v-xianya** [comment]
This issue is fixed on build rel/1.16.0 20201030.5. so close it.
