### ISSUE TITLE
Error:Hub Controller process exited prematurely with signal 'SIGABRT'.

### ISSUE THREAD

**Issue by JCKodel** [microsoft/AzureStorageExplorer#3605]
**Storage Explorer Version**: 1.15.1
**Build Number**: 20200902.9
**Platform/OS**: MacOS Catalina
**Architecture**: x64

## Bug Description ##
The requested action could not be completed.

Details:
["Error:Hub Controller process exited prematurely with signal 'SIGABRT'."]

![image](https://user-images.githubusercontent.com/379339/93556357-f1570a00-f94e-11ea-82bf-73f06bd2c294.png)

## Steps to Reproduce ##
1. Just open it on MacOS.

## Expected Experience ##
To actually work

## Actual Experience ##
Doesn't work

**Comment by Harshithj88** [comment]
@JCKodel I did upgrade the version of storage explorer to Version 1.15.1 and it is working fine.

**Comment by MRayermannMSFT** [comment]
@JcKodel can you:

1. In Storage Explorer settings, turn on Verbose Authentication Logging under, Application -> Sign-in
2. Close Storage Explorer
3. Delete ~/.ServiceHub/logs
4. Start Storage Explorer
5. Do everything you do to reproduce this problem
6. After it reproduces, zip up ~/.ServiceHub/logs, and attach it here

Thanks.

**Comment by JCKodel** [comment]
@MRayermannMSFT 

Retrying the operation generates no log (I guess I need to restart Storage Explorer for the log option to activate?), but doing so fixes the problem (until the next day or so).

If I click on Reenter credentials, the "Connect to Azure Storage" just freezes (the circular progress keep spinning, but nothing happens).

![image](https://user-images.githubusercontent.com/379339/93834714-2f0ba980-fc53-11ea-8840-5788baac491a.png)

After quitting and reopening, the following error immediately appears: 
```
Unable to retrieve child resources.

Details:
["Error:Unable to retrieve authentication token."]
```

At this point, this is the log: 
[1.zip](https://github.com/microsoft/AzureStorageExplorer/files/5258754/1.zip)

Now I deleted all log and clicked Reenter credentials (now the amazing Microsoft Login takes places... such a simple task, so poorly implemented):

First, I pick my account (I have this account since 2004  or 2005, I guess, it's ancient).
<img width="636" alt="Screen Shot 2020-09-21 at 21 45 14" src="https://user-images.githubusercontent.com/379339/93834878-c53fcf80-fc53-11ea-8aea-087a3661cce9.png">

Then, for no reason, I'm redirected to GitHub ¬¬
<img width="680" alt="Screen Shot 2020-09-21 at 21 45 44" src="https://user-images.githubusercontent.com/379339/93834909-dab4f980-fc53-11ea-98bb-1bbb68a53652.png">

Then, I need to reenter my e-mail and 20 characters password, EVERY FREAKING TIME.
<img width="680" alt="Screen Shot 2020-09-21 at 21 46 28" src="https://user-images.githubusercontent.com/379339/93834940-f7513180-fc53-11ea-8704-bf522eafd3fe.png">

Then, I have to deal with 2FA because MS is too lazy to implement a TRUST THIS COMPUTER.
<img width="680" alt="Screen Shot 2020-09-21 at 21 47 33" src="https://user-images.githubusercontent.com/379339/93834980-1cde3b00-fc54-11ea-8cc9-fa9a61ef4047.png">

Finally, because of the will of Odin, I'm redirect to login in a company that I don't work for about 1 year now.
<img width="636" alt="Screen Shot 2020-09-21 at 21 49 03" src="https://user-images.githubusercontent.com/379339/93835027-49925280-fc54-11ea-908f-b1d989dbe3b4.png">

I know clicking my e-mail won't do nothing, but, what other option do I have? Doing so, it redirects me to GitHub (WTF?????)
<img width="680" alt="Screen Shot 2020-09-21 at 21 50 04" src="https://user-images.githubusercontent.com/379339/93835065-6e86c580-fc54-11ea-97a5-6bda26840563.png">

And I have to retype my e-mail and 20 character password (I'll just copy and paste the screenshot above, it's the same)
<img width="680" alt="Screen Shot 2020-09-21 at 21 46 28" src="https://user-images.githubusercontent.com/379339/93834940-f7513180-fc53-11ea-8704-bf522eafd3fe.png">

2FA kicks in again and I have to, one more time, authorize it from my mobile phone.

All that to get to this:
<img width="680" alt="Screen Shot 2020-09-21 at 21 51 50" src="https://user-images.githubusercontent.com/379339/93835140-ad1c8000-fc54-11ea-81bc-efec1ef395b0.png">

Just tell me, HOW IN THE HELL do you guys can mess up a simple login??? Get my e-mail, password and 2FA and authenticate me! It's not that hard!

Now the only option I have is to cancel this operation, closing the authentication window. This is the log so far:
[eebbbc5e-AadAccountProviderClient-4657-8pZG7I-4657-1.log](https://github.com/microsoft/AzureStorageExplorer/files/5258769/eebbbc5e-AadAccountProviderClient-4657-8pZG7I-4657-1.log)
(there is only one file)

And now, the grand finalle! After quitting Storage Explorer and reopening, ta-da! It's authenticated! So easy!

After this walk in the park, very easy and uneventful authentication, this is the log:
[Archive.zip](https://github.com/microsoft/AzureStorageExplorer/files/5258772/Archive.zip)

**Comment by MRayermannMSFT** [comment]
Glad it eventually worked. Sorry you had to go through such a frustrating experience. We'll keep working on this scenario.
