### ISSUE TITLE
Exception at start up

### ISSUE THREAD

**Issue by nhwilly** [microsoft/AzureStorageExplorer#3607]
**Storage Explorer Version**: 1.15.1
![2020-09-19_13h54_54](https://user-images.githubusercontent.com/7560842/93685770-b43e6500-fa7f-11ea-83d6-0da187841bdf.png)

![2020-09-19_13h56_01](https://user-images.githubusercontent.com/7560842/93685807-ddf78c00-fa7f-11ea-827c-972264cf08ee.png)

## Bug Description ##
I get this exception on launch.  I select "ignore" and it works, but I've installed/uninstalled multiple times and I can't get it to quit this at start up.

## Steps to Reproduce ##
Launch the app.

![2020-09-19_13h41_36](https://user-images.githubusercontent.com/7560842/93685838-02536880-fa80-11ea-94a7-3ef9b0068f31.png)

Do I need to update something else?

FYI and TIA.

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
