### ISSUE TITLE
Allow selecting of multiple items (tables/containers/etc)

### ISSUE THREAD

**Issue by a-vishar** [microsoft/AzureStorageExplorer#361]
We generate a large number of tables/containers/queues/blobs/etc for testing purposes and would like to be able to remove selections of them (think shift+click or ctrl+click) to delete en masse.

**Comment by MRayermannMSFT** [comment]
Re-evaluate during 1.16 timeframe

**Comment by jinglouMSFT** [comment]
Dup of #852 https://github.com/microsoft/AzureStorageExplorer/issues/852
