### ISSUE TITLE
MAC signature not the same as any computed signature

### ISSUE THREAD

**Issue by dbouchard1** [microsoft/AzureStorageExplorer#3610]
when accessing my file share via storage explorer that use to work, I now get this message.
any clue as to why that would be?
Authentication error: The MAC signature found in the HTTP request 'KEY CODE I REMOVED' is not the same as any computed signature. Server used following string to sign: 'GET

x-ms-client-request-id:9946a030-fc2a-11ea-8868-cf3f186f1007
x-ms-date:Mon, 21 Sep 2020 16:50:47 GMT
x-ms-version:2018-03-28
/systems/
_:1600707047862
comp:list
maxresults:25'.

**Comment by MRayermannMSFT** [comment]
@dbouchard1 how are you connecting to Azure Storage? Sign in, account name and key, a connection string, SAS, etc.?

**Comment by dbouchard1** [comment]
by account name and key

**Comment by dbouchard1** [comment]
Ok fixed it. it was the name being the same for display and account name. now its working.

thanks for your help

**Comment by MRayermannMSFT** [comment]
@dbouchard1 can you elaborate on how you fixed the problem?
