### ISSUE TITLE
Succeed to edit tags for one blob version

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3614]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20200923.3
**Branch**: main
**Platform/OS:** Windows 10 / CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account (Make sure the **Blob versioning** is enabled)-> Blob Containers.
2. Create a new blob container -> Upload one blob -> Change its properties to create a blob version.
3. Right click the blob -> Click 'Manage History -> Manage Versions'.
4. Right click the blob version -> Click 'Edit tags...' -> Add tags then click 'Save'.
5. Check the result.

**Expect Experience:**
Fail to save tags.

**Actual Experience:**
Succeed to save tags.

**Comment by JasonYeMSFT** [comment]
This shows as success because we incorrectly call it on the base blob instead of the version. We won't allow user to edit tags or add new tags if he view tags of a version.

**Comment by v-xianya** [comment]
Verified this issue on build 20200930.3. Fixed.
