### ISSUE TITLE
Subscription could not be loaded

### ISSUE THREAD

**Issue by aokiyuriko** [microsoft/AzureStorageExplorer#3618]
**Storage Explorer Version**: 1.12.0
**Build Number**: 20200116.10
**Platform/OS**: Windows 10 
**Architecture**: x64
**Regression From**:  This is the first time I downloaded Storage Explorer 

## Bug Description ##
 I downloaded the explorer and launched it for the first time as admin under corporate wifi. I succeeded in logging in my corporate Microsoft account but  subscription could not be loaded. I have tried relaunched it, reentered credential, removed and readded my account but nothing changed.

[storage explorer error.txt](https://github.com/microsoft/AzureStorageExplorer/files/5273187/storage.explorer.error.txt)

## Steps to Reproduce ##
 I have described above. 

## Expected Experience ##

It should be like this:
![image](https://user-images.githubusercontent.com/44343768/94108250-8be4ab00-fe71-11ea-86de-6e5eaf4bced0.png)

## Actual Experience ##
Mine is like this:
![image](https://user-images.githubusercontent.com/44343768/94108289-a159d500-fe71-11ea-9d89-13022af841d3.png)

## Additional Context ##
I'm not sure if my corporate network has anything to do with this problem.

**Comment by MRayermannMSFT** [comment]
@aokiyuriko it looks like Storage Explorer is trying to talk to a proxy at 127.0.0.1:80 before going to Azure.

This proxy information is most likely coming from an environment variable at your OS level. Can you check for HTTP_PROXY or HTTPS_PROXY environment variables?

**Comment by aokiyuriko** [comment]
> @aokiyuriko it looks like Storage Explorer is trying to talk to a proxy at 127.0.0.1:80 before going to Azure.
> 
> This proxy information is most likely coming from an environment variable at your OS level. Can you check for HTTP_PROXY or HTTPS_PROXY environment variables?

Thanks I stop using proxy and then it goes right.
