### ISSUE TITLE
Succeed to clone one blob with an existing folder's name

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3619]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20200925.2
**Branch**: main
**Platform/OS:** Windows 10/ Fedora release 29/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Create one blob container -> Upload folders and blobs to it.
3. Clone one blob with an existing folder's name.
4. Check the result.

**Expect Experience:**
Can't complete the action and tells that '**a file or directory with that name already exists**'.

**Actual Experience:**
Succeed to clone the blob.

**More Info:**
Pop up a conflict dialog when trying to clone one folder with an existing blob's name.
![image](https://user-images.githubusercontent.com/41351993/94244999-3b8e4b80-ff4c-11ea-8789-1320af7be6e5.png)

**Comment by MRayermannMSFT** [comment]
@v-xianya is this in a gen2 blob container?

**Comment by JasonYeMSFT** [comment]
I have tried this and cannot reproduce the issue, could you please double check?

**Comment by v-xianya** [comment]
Verified this issue on build 20200929.1. The current behaviors as below:
1. Succeed to clone one blob with an existing folder's name.
2. Succeed to clone one folder with an existing blob's name.

More details please see the record:
https://msit.microsoftstream.com/video/00fda0ff-0400-9fb2-373a-f1eb01fc0771

**Comment by JasonYeMSFT** [comment]
If both way succeeds, then that is expected.
