### ISSUE TITLE
It would be better to display the value of the public read access in the log for the action 'Set Public Access Level'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3620]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20200925.2
**Branch**: main
**Platform/OS:** Windows 10/ Fedora release 29/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Click 'Set Public Access Level...' -> Select one option -> Click 'Apply'.
3. Observe the activity log.

**Expect Experience:**
It would be better to display the value of the access in the activity log.

**Actual Experience:**
The value of the access doesn't display in the activity log.
![image](https://user-images.githubusercontent.com/41351993/94246322-2dd9c580-ff4e-11ea-9ac9-fc357576eda5.png)

**Comment by MRayermannMSFT** [comment]
In about 30min a PR will be merged that fixes this. It will affect both non-adls gen2s and adls gen2 blob containers. @v-xianya, when verifying this bug, please do a variety of exploratory testing around the set public access level feature. Going to close this now so I can get offline. Thanks!

**Comment by v-xianya** [comment]
@MRayermannMSFT 
Hi Matthew, Verified this issue on build 20210129.3.
Now the activity log shows: Successfully changed public access level for blob container 'ablob'
![image](https://user-images.githubusercontent.com/41351993/106238021-0fa50e80-623b-11eb-8908-bc9b40e00e52.png)

Is there any possible to make the activity log as below?
Successfully changed public access level from '**container**' to '**blob**' for blob container 'ablob'

**Comment by MRayermannMSFT** [comment]
Sure
