### ISSUE TITLE
It is better to display the property 'rehydration -priority' in one blob's Properties dialog

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3621]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20200925.2
**Branch**: main
**Platform/OS:** Windows 10/ Fedora release 29/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one storage account -> Blob Containers.
2. Create one blob container -> Upload one blob to it.
3. Check the blob's Properties dialog.

**Expect Experience:**
The property 'rehydration -priority' displays in the blob's Properties dialog.

**Actual Experience:**
The property 'rehydration -priority' doesn't display in the blob's Properties dialog.

**More Info:**
For the blobs are rehydrating, users may want to confirm its rehydration -priority status in the blob's Properties dialog.

**Comment by v-limu** [comment]
Verified on build 20210319.2. The property 'RehydrationPriority' has been added in the Properties dialog. But its value is empty when changing the priority of the access tier.
![image](https://user-images.githubusercontent.com/54055206/111723843-252fcf80-889f-11eb-8fc1-2a1fb362cfd0.png)

**Comment by MRayermannMSFT** [comment]
@v-limu how exactly did you test this? I was able to see a priority by:

1. - Change access tier of a blob to archive
2. - Wait a few minutes
3. - Change access their back to hot or cold
4. - Check priority

![image](https://user-images.githubusercontent.com/21112697/112543403-ee602a80-8d72-11eb-9579-0d6a3cc181d0.png)
![image](https://user-images.githubusercontent.com/21112697/112543518-1c456f00-8d73-11eb-9c68-ddc89a56f063.png)

I did not see a priority when going from hot to cold (or vice versa). I also was unable to change priority once a blob was rehydrating.

**Comment by v-limu** [comment]
Hi @MRayermannMSFT Thanks for your updates. 
We use your steps to verify this issue on build 20210326.3. This issue doesn't reproduce for one regular blob. But this issue reproduces for one ADLS Gen2 blob.

**Comment by MRayermannMSFT** [comment]
@v-limu I've been told this is due to a bug on the server. Going to close this as merged for now. The server team is aware of the bug and will be fixing it in the future.

**Comment by v-limu** [comment]
Verified on build  20210406.2. This issue has been fixed for the ADLS Gen2 blob.
