### ISSUE TITLE
Nothing happens when trying to download blobs

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3622]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20200926.5
**Branch**: main
**Platform/OS:** Windows 10/ Fedora release 29/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Previous build (20200925.2)

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Create a blob container ->Upload blobs to it.
3. Select one blob and try to download it (By selecting 'Download' on the toolbar or on the context menu).
4. Check the result.

**Expect Experience:**
Succeed to start the download action.

**Actual Experience:**
Nothing happens.

**More Info:**
1. This issue doesn't reproduce when downloading one disk or ADLS Gen1 files.
2. This issue also reproduces when downloading files and folders under one file share.

**Comment by JasonYeMSFT** [comment]
This is caused by "SystemLocation" object being undefined, from which we should be getting the default download location of the system.

**Comment by craxal** [comment]
The `se-storage-explorer-sdk` package version wasn't updated in Standalone. `SystemLocation` is defined in a newer version.
