### ISSUE TITLE
Azure Storage Explorer Stopped Working

### ISSUE THREAD

**Issue by barmanroys** [microsoft/AzureStorageExplorer#3623]
**Storage Explorer Version**: <1.15.1>
**Build Number**: <20200902.9>
**Platform/OS**: <Linux Mint 20 Ulyana>
**Architecture**: < x64>
**Regression From**:  <The same version was working yesterday>

## Bug Description ##
I configured several storage accounts (accessed with account name and key). But all of them suddenly stopped working. Even when I try to add them again, it throws this error 

Unable to retrieve child resources.

Details:
["FetchError:request to http://127.0.0.1:10001/devstoreaccount1/?include=metadata&comp=list&timeout=30 failed, reason: connect ECONNREFUSED 127.0.0.1:10001"]

**Comment by MRayermannMSFT** [comment]
@barmanroys 

- is your emulator running?
- do you have OS environment variables for either http_proxy or https_proxy?

**Comment by escobarjj** [comment]
Something similar is happening to me, but with a different error detail: 
Unable to retrieve child resources.

Details:
["Error:Unable to retrieve authentication token."]

**Comment by a1spareparts** [comment]
Could anyone help me with this?

Unable to retrieve child resources.

Details:
["Error:Unable to retrieve authentication token."]

**Comment by barmanroys** [comment]
Seems it's fixed after reconnecting the password manager to the snap store

**Comment by MRayermannMSFT** [comment]
@escobarjj @a1spareparts for your error message, please go to Settings (gear on the left) -> Services -> Disks, uncheck the checkbox, and then restart storage explorer. If you're still having issues after that, please open a new issue.

Since barmanroys fixed his is problem, I'm going to close his issue.
