### ISSUE TITLE
How to create custom environment to connect to Dogfood?

### ISSUE THREAD

**Issue by abatishchev** [microsoft/AzureStorageExplorer#3624]
**Is your feature request related to a problem? Please describe.**

I'm trying to add new custom Environment in order to connect to Microsoft Azure Dogfood:

**Describe the solution you'd like**

I'd like the dialog to prompt for all the necessary URLs such as both ARM and AAD.

**Describe alternatives you've considered**

No other options from the Step 1 seems to be related.

**Additional context**

![image](https://user-images.githubusercontent.com/351644/94493414-66251200-01a1-11eb-948f-d08a6aea2b68.png)

![image](https://user-images.githubusercontent.com/351644/94493420-6a512f80-01a1-11eb-84f0-ca962b8d6c91.png)

Application version: 1.15.1

**Comment by abatishchev** [comment]
Related: https://github.com/MicrosoftDocs/azure-stack-docs/issues/1059

**Comment by MRayermannMSFT** [comment]
@abatishchev this isn't possible today I think. Are you internal/work at MSFT?

**Comment by abatishchev** [comment]
@MRayermannMSFT hi, yes, I am (alexbat).

**Comment by MRayermannMSFT** [comment]
Talked to @abatishchev offline. He's ok for now but will reach back out to me if needed.
