### ISSUE TITLE
Pop up an error dialog when trying to add entity for one SAS attached table with entity restrictions

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3625]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20200929.1
**Branch**: main
**Platform/OS:** Windows 10/ Fedora release 29/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Tables.
2. Create a table -> Add several entities.
3. Right click the table -> Click 'Get Shared Access Signature...'.
4. Select all permissions -> Enter the valid 'partition keys' and 'row keys' to the Entity restrictions part.
5. Create and copy the URI -> Attach the table using the URI.
6. Add an entity to the SAS attached table -> Check the result.

**Expect Experience:**
Succeed to add the entity.

**Actual Experience:**
Fail to add the entity and pop up an error dialog.
![image](https://user-images.githubusercontent.com/41351993/94539810-4f052380-0278-11eb-8877-fc921b423656.png)

**Comment by MRayermannMSFT** [comment]
@v-xianya we think this is to be expected. Can you share some more information:

- can you make an example table
- repro the bug with that table
- let us know what restrictions you used when generating the SAS
- let us know what values you used when creating the new entity

Thanks.

**Comment by v-xianya** [comment]
@MRayermannMSFT More information see the record, Please!
Record: https://msit.microsoftstream.com/video/8f0fa1ff-0400-9fb2-dde4-f1eb0a08bc2c

**Comment by MRayermannMSFT** [comment]
@v-xianya this is expected. Since you tried inserting an entity outside the range of the SAS restriction, the server returns an error.
