### ISSUE TITLE
Change Access Tier from archive to cool not working

### ISSUE THREAD

**Issue by MikeFerreira** [microsoft/AzureStorageExplorer#3627]
Azure Storage Explorer
### AZCopy Version: 10.6.0

**Change access tier from archive to cool not working but azcopy command displays as successful**

1. Tried a single file access tier archive to cool, did not work
2. Tried multiple files change access tier archive to cool, did not work

Did the access tier change in the Azure Portal, it worked.

**Comment by MRayermannMSFT** [comment]
@MikeFerreira there should be something like "Error details" or "Details" after the change access tier fails. Can you click on that and share the error with us?

**Comment by MRayermannMSFT** [comment]
@MikeFerreira additional question, are you by chance trying to change access tier of blob versions?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you're still having problems.
