### ISSUE TITLE
Can't view folder with error

### ISSUE THREAD

**Issue by lhdmkoch** [microsoft/AzureStorageExplorer#3628]
Unable to retrieve child resources.

Details:
["FetchError:request to https://pdwmigrationstore.blob.core.windows.net/?include=metadata&comp=list failed, reason: connect ETIMEDOUT 52.239.232.68:443"]

**Comment by MRayermannMSFT** [comment]
@lhdmkoch are you behind a proxy?

**Comment by lhdmkoch** [comment]
Hi Matthew,
Thanks for your email. The issue has been fixed.

Regards
Lin

Lin De Mello Koch 
IT Data Architect

T: +27 11 780 7000 
F: 
C: +27 78 019 8144
E:lin.dmkoch@suninternational.com
W: www.suninternational.com
Disclaimer (http://mail76.mimecast.co.za/mimecast/site?account=CSA38A3&code=b1f368d342399b8e6c4ffab5687a67b8) 

-------- Original Message --------
Subject: Re: [microsoft/AzureStorageExplorer] Can't view folder with error (#3628)
From: Matthew Rayermann
To: microsoft/AzureStorageExplorer
CC: Lin De Mello Koch ,Mention


@lhdmkoch<https://github.com/lhdmkoch> are you behind a proxy?

**Comment by MRayermannMSFT** [comment]
@lhdmkoch how did you fix your issue?
