### ISSUE TITLE
An unexpected error occurs when launching Storage Explorer

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#363]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180628.2
**Regression From**: Works well on previous build 20180627.6

#### Steps to Reproduce: ####
1. Launch Storage Explorer.

#### Expected Experience: ####
No error occurs.

#### Actual Experience: ####
An expected error "Can't find module 'junit-report-builder'"occurs.
![error](https://user-images.githubusercontent.com/34729022/42011653-ecffe4a0-7a83-11e8-991c-eebbc9d6ec26.png)

**Comment by craxal** [comment]
@MRayermannMSFT, CTI reports that this issue is still occurring in Linux. Can you verify?

**Comment by MRayermannMSFT** [comment]
Yes, I should have some down time this weekend to investigate.

**Comment by v-xuanzh** [comment]
Hi @craxal @MRayermannMSFT , This issue also reprodces for 32-bit Storage Explorer on Windows64Bit on the latest build [20180701.1](https://devdiv.visualstudio.com/DevDiv/Cloud%20Explorer/_build/results?buildId=1823721)

**Comment by craxal** [comment]
@v-xuanzh, you should get 32-bit Storage Explorer from Windows32Bit and 64-bit Storage Explorer from WIndows64Bit. I don't know why we're getting four sets of bits in these combinations, but you should not be getting stuff from mismatched folders.

**Comment by MRayermannMSFT** [comment]
This should now be fixed in latest master builds.
