### ISSUE TITLE
Cloning a block blob does not preserve its break down in multiple blocks.

### ISSUE THREAD

**Issue by YvainRaeymaekers** [microsoft/AzureStorageExplorer#3630]
**Storage Explorer Version**: 1.14.2
**Build Number**: 20200715.2 
**Platform/OS**: Windows
**Architecture**: ia32 

## Bug Description ##
After cloning a block blob, the newly created blob does not have the same blocks and blockIDs as the source blob. It appears that all the blocks have been merged into a single one with a random GUID as BlockID.
Copying a blob through the C++ REST API works fine though. In this case, the different blocks, their content and their blockID are preserved.

## Steps to Reproduce ##
- Create a block blob with multiple blocks 
- In the explorer, right click and select clone with a new name
- The resulting blob does not have multiple blocks 

## Expected Behaviour ##
That copying a block blob in the Azure Storage Explorer behaves in the same way as the copy through the C++ REST API.

**Comment by MRayermannMSFT** [comment]
@YvainRaeymaekers would you be able to give us an example blob you see this happening for?

Also, what APIs/tools are you using to create the initial blob?

**Comment by YvainRaeymaekers** [comment]
Here some code I used to create an example blob for which the problem arises when copied with the Azure Storage Explorer.
The API is Azure Storage Client Library for C++ v7.0.0 (https://github.com/Azure/azure-storage-cpp)

```c++
#include <was/blob.h>
#include <was/storage_account.h>
#include <cpprest/interopstream.h>
#include <cpprest/rawptrstream.h>
#include <cpprest/asyncrt_utils.h>

namespace azs = azure::storage;
namespace cs = concurrency::streams;
namespace uc = utility::conversions;

void uploadBlock(azs::cloud_block_blob& blob, const std::vector<char>& data, const std::string& id, std::vector<azs::block_list_item>& ids)
{
    auto is = cs::rawptr_stream<unsigned char>::open_istream(reinterpret_cast<const unsigned char*>(data.data()), data.size());
    auto blockId = uc::to_string_t(util::base64::encode(id)); // you'll need to provide your own base64 function if you want to run this code
    blob.upload_block(blockId, is, azs::checksum_none);
    ids.push_back(blockId);
}

int main(int argc, char* argv[])

{
    const std::string azAccount = "_________";
    const std::string azPassword = "_________";
    const std::string containerId  = "_________";

    const auto storageCredentials = azs::storage_credentials(uc::to_string_t(azAccount), uc::to_string_t(azPassword));
    const bool useHttps = true;

    auto storageAccount = azs::cloud_storage_account(storageCredentials, useHttps);
    auto client = storageAccount.create_cloud_blob_client();

    auto container = client.get_container_reference(uc::to_string_t(containerId));
    bool res = container.create_if_not_exists();

   // we create a blob with 2 blocks
    auto testBlob = container.get_block_blob_reference(uc::to_string_t("testblob"));
    std::vector<azs::block_list_item> ids;
   
    std::vector<char> buffer1(1024);
    std::fill(buffer1.begin(), buffer1.end(), char(33));
    uploadBlock(testBlob, buffer1, "block1", ids);

    std::vector<char> buffer2(1024);
    std::fill(buffer2.begin(), buffer2.end(), char(42));
    uploadBlock(testBlob, buffer2, "block2", ids);

    testBlob.upload_block_list(ids);
```

**Comment by JasonYeMSFT** [comment]
@YvainRaeymaekers We had a talk with the AzCopy team and this turns out to be the by-design behavior. Neither AzCopy nor us have seen people requesting such fine-grained management over block blobs. Could you share with us the scenario where you want to preserve block structures?

**Comment by YvainRaeymaekers** [comment]
Yes of course:
We are writing a software that works a bit like Git. We store in a block blob a list of revisions. Each block containing the revision data. We designed it like that rather than to store the revisions in separate blobs since each revision does not take much space ( ~1KByte) and we also need to be able to append revisions to the list. 
When we want to navigate in our history, we use the .download_block_list() method on an azure::storage::cloud_block_blob and do a search over the BlockIDs to identify the relevant block and proceed to download it. 

Since block blobs get all their blocks merged into one after a copy, this behaviour completely breaks our revision lookup code. This a bit troublesome for us because it prevents us from using the azure portal or the azure storage explorer when we want to backup a project.

**Comment by zezha-msft** [comment]
Hi @YvainRaeymaekers, thanks for reaching out! I work on the AzCopy project.

I've logged an item to look into your requirement. In the meantime, I have a few questions:

1. Is there any other reason why the revisions have to be inside one blob? There is always the risk of using a tool that copies the blobs and loses the block list, so for your customers, even if we fixed it in AzCopy, this may still become a problem for them.
1. Have you considered separating the revisions into different blobs? Ex: blobname-revisionID. This way you don't have to figure out the exact range of a single blob to read.

**Comment by YvainRaeymaekers** [comment]
Hi thanks for looking into this.
About question 1: I don't think there is another reason. The main reason we designed things this way was to avoid having a huge quantity of small blobs. Is it truly fine to have thousands of small 1Ko blobs in a blob container ? And about the the risk of having an azure tool losing the blob list during a copy is why I submitted this bug report. In order to consider the problem fixed, we would expect any Azure tool or any operation in the Azure portal to preserve the block list from now on (or at least have an option to enable this behaviour). 

We actually have another scenario for splitting a blob into multiple blocks: In some blobs we store a texture file with all of its pregenerated mipmap levels. When downloading a texture we want to be able to download the smaller levels first. Relying on having the mip levels stored separate blocks is a convenient way to achieve that. If the blob list is lost during some copy operations, it looks like it undermines a lot the block blob feature. What is the use of this feature if the block list is not considered stable ? 

About question 2: Yes that's something we have been considering. We've also been considering writing our own copy tool using the C++ Rest API but that would prevent us from using any tool blob management provided by Azure.

Changing the way we use the blobs in our application would require for us a non trivial dev effort. Before doing anything I'd rather wait to know if you take a decision on whether the block list is something devs can consider stable or not.

**Comment by zezha-msft** [comment]
Hi @YvainRaeymaekers, thanks for the additional context!

We may certainly log an item to add the functionality of preserving block list in AzCopy, but I'm afraid that it won't be possible to ensure that all tools interacting with Storage can behave the way you want it to. The reason is that in addition to the official tools like AzCopy and StgExp, there are a variety of other data transferring tools made by 3rd parties that are not under our control. If your customers can freely move their data around, then it's very possible that someone might mess up the block list at some point, either due to the tool that they were using or the option that they forgot to turn on. Do you think this is a fair reason to justify changing your data scheme?

In terms of performance, I don't think the two schemes (one big blob vs a bunch of tiny blobs) matter in terms of everyday reads/writes, since it sounds like you are reading and writing in terms of these small blocks anyways. But in terms of copy performance, it's true that copying one big blob is much faster than copying a bunch of small ones with the same total size, since there is an overhead per blob.

**Comment by MRayermannMSFT** [comment]
AzCopy is choosing not to do this for now. If you'd like to further argue your case, please go open an issue in their repo: https://github.com/Azure/azure-storage-azcopy
