### ISSUE TITLE
Inject host in SDK loader

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#3631]
## Summary

SDK loader should be refactored such that environment-specific hosts can be injected instead of pulled from old SDK.

## Benefits

- Removes hard-to-see dependency on a globally defined host
- Enables earlier use of the SDK in any environment; good for startup logging

## Tasks

- [ ] Provide general-purpose SDK implementations that accept an `IHost` when constructed
- [ ] Abstract the `SDKLoader` class and write environment-specific implementations that provide the appropriate host implementation.

**Comment by MRayermannMSFT** [comment]
This is done.
