### ISSUE TITLE
Configure Soft Delete Policy fails on Emulator

### ISSUE THREAD

**Issue by asgoe** [microsoft/AzureStorageExplorer#3632]
I am getting the following error while trying to set the soft delete on Azure storage emulator. This is happening with 2 versions of emulator 1.12 and 1.15.1 

{
  "name": "StorageError",
  "message": "XML specified is not syntactically valid.\nRequestId:046520c8-e84c-45fe-86bd-3a144bcad2b7\nTime:2020-10-01T03:18:01.6645487Z",
  "stack": "StorageError: XML specified is not syntactically valid.\nRequestId:046520c8-e84c-45fe-86bd-3a144bcad2b7\nTime:2020-10-01T03:18:01.6645487Z\n    at Function.StorageServiceClient._normalizeError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:1205:23)\n    at Object.StorageServiceClient._processResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:751:50)\n    at Request.processResponseCallback [as _callback] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:319:37)\n    at Request.self.callback (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:185:22)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at Request.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at Request.emit (events.js:210:5)\n    at Request.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1157:10)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at Request.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at Request.emit (events.js:210:5)\n    at IncomingMessage.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1079:12)\n    at Object.onceWrapper (events.js:299:28)",
  "code": "InvalidXmlDocument",
  "linenumber": "1",
  "lineposition": "66",
  "reason": "Element 'DeleteRetentionPolicy' is not recognized.",
  "statusCode": 400,
  "requestId": "046520c8-e84c-45fe-86bd-3a144bcad2b7"
}

**Comment by MRayermannMSFT** [comment]
@asgoe soft delete is not supported by either storage emulator. You can open a feature request against azurite here: https://github.com/Azure/Azurite

**Comment by JasonYeMSFT** [comment]
Storage Emulator doesn't support it at all. Azurite is on the way supporting it. You can see Azurite respond to the configure soft delete policy requests but the policy doesn't have any effect.
