### ISSUE TITLE
Unable to delete files and folders

### ISSUE THREAD

**Issue by Canis-Lupis** [microsoft/AzureStorageExplorer#3634]
**Storage Explorer Version**: 1.15.1
**Build Number**: 20200902.9
**Platform/OS**: Windows 10
**Architecture**: x64?
**Regression From**:  

## Bug Description ##
After uploading folders using AzCopy, I am unable to delete them.  Error message is 
{
  "message": "\"Authentication Failed. The SAS is not correct or expired or does not have the correct permission -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.1-0.20200812020820-59b3010ad575/azblob/zc_storage_error.go:42\\n===== RESPONSE ERROR (ServiceCode=AuthorizationPermissionMismatch) =====\\nDescription=This request is not authorized to perform this operation using this permission.\\nRequestId:9409ebf7-501e-0068-5402-980df8000000\\nTime:2020-10-01T14:52:05.0399139Z, Details: \\n   Code: AuthorizationPermissionMismatch\\n   DELETE https://df9f4bfffd684d4cbc84f60.blob.core.windows.net/ingestiondata/aagular/archive2.pst?se=2020-10-31t14%3A51%3A36z&si=ingestionsasforazcopy202008281621210729&sig=-REDACTED-&sr=c&sv=2015-04-05&timeout=901\\n   User-Agent: [Microsoft Azure Storage Explorer, 1.15.1, win32,  AzCopy/10.6.0 Azure-Storage/0.10 (go1.13; Windows_NT)]\\n   X-Ms-Client-Request-Id: [66b6fc0c-3bf7-4d2b-4e9f-a4412aac0d75]\\n   X-Ms-Version: [2019-12-12]\\n   --------------------------------------------------------------------------------\\n   RESPONSE Status: 403 This request is not authorized to perform this operation using this permission.\\n   Content-Length: [279]\\n   Content-Type: [application/xml]\\n   Date: [Thu, 01 Oct 2020 14:52:04 GMT]\\n   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]\\n   X-Ms-Client-Request-Id: [66b6fc0c-3bf7-4d2b-4e9f-a4412aac0d75]\\n   X-Ms-Error-Code: [AuthorizationPermissionMismatch]\\n   X-Ms-Request-Id: [9409ebf7-501e-0068-5402-980df8000000]\\n   X-Ms-Version: [2019-12-12]\\n\\n\\n\""
}

## Steps to Reproduce ##
1. Upload folders with AzCopy
2. Use SAS URL from Office 365 Info Governance\Import to connect in Azure Storage Explorer
3.  Try to delete folders uploaded.

## Expected Experience ##
I expect files/folders to be removed when deleted

## Actual Experience ##
Receive error message.

**Comment by JasonYeMSFT** [comment]
@Canis-Lupis How do you connect to the blob container? Are you signed-in, attaching with Azure AD or attaching with SAS? 
The error message says you are missing the delete permission. There should be a "sp=rdl" parameter in the url "https://df9f4bfffd684d4cbc84f60.blob.core.windows.net/ingestiondata/aagular/archive2.pst?se=2020-10-31t14%3A51%3A36z&si=ingestionsasforazcopy202008281621210729&sig=-REDACTED-&sr=c&sv=2015-04-05&timeout=901". Could you check if it exists and if a "d" exists in the parameter?

**Comment by Canis-Lupis** [comment]
Attaching with SAS per the instructions on importing psts:  https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?view=o365-worldwide

[https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png]<https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?view=o365-worldwide>
Use network upload to import your organization's PST files - Microsoft 365 Compliance | Microsoft Docs<https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?view=o365-worldwide>
For a high-level overview of the PST Import process, see How the import process works section in this article.. Step 1: Copy the SAS URL and install AzCopy. The first step is to download and install the AzCopy tool, which is the tool that you run in Step 2 to upload PST files to Office 365.
docs.microsoft.com

________________________________

**Comment by JasonYeMSFT** [comment]
Oh, I see. Your SAS is using an access policy which specifies your permissions (in the 'si=ingestionsasforazcopy202008281621210729'). It is possible that the access policy didn't grant you delete permission, could you check with the provider of the SAS to see if delete permission is granted?

**Comment by Canis-Lupis** [comment]
Microsoft is the provider.  There's nothing listed about what the permissions are.  Please see link I sent previously.  Also, below is a screenshot from protection.office.com where I'm getting the SAS:
[cid:7b2325cd-a033-4606-9781-72235c137a97]
________________________________

**Comment by JasonYeMSFT** [comment]
The instruction says the SAS "provides you with the necessary permissions to upload PST files to your Azure Storage location". Delete permission is not needed for upload. If you want to delete those files/folders in Storage Explorer, you'll need to either
- sign-in to get the subscription of the blob container "df9f4bfffd684d4cbc84f60"
- Attach to the blob container with Azure AD
- Find the container owner who can generate a SAS with delete permission for you

In the 1st and the 2nd approach, it also requires you to have the role that grants you delete permission (e.g. https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#storage-blob-data-contributor).

Let me know if you still have any questions.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you're still encountering this problem, please open a new issue. Thanks!
