### ISSUE TITLE
How long does it take for a blob to update in Azure Blob Storage?

### ISSUE THREAD

**Issue by Joaveinz** [microsoft/AzureStorageExplorer#3636]
I am using Azure Blob storage to store images for my new website. The access tier is "Hot".

When I have an image called background.jpg and replace it with a different image, but with the same name (background.jpg) it can take up to a week to actually change to the new image on the website.

The only way to test it is to either visit the website through a VPN or use someone else's machine (who's never accessed the website before).

I have cleared my local storage and cache multiple times.

It's almost as if blob storage has it's own caching mechanism on the server side.

I've had a look at the Microsoft Docs, but they are not so straight-forward to understand in this area.

Thanks in advance!

**Comment by MRayermannMSFT** [comment]
@Joaveinz do you know if you are using Azure CDN? Alternatively, what geo replication setting is currently set for your storage account?

Note: you might have better luck with this issue by opening a support ticket via the portal:
<img width="292" alt="image" src="https://user-images.githubusercontent.com/21112697/95111746-ce6d7980-06f4-11eb-9113-68226e20228b.png">
In general, this page is for raising issues about the Storage Explorer application, and we like to keep it on that topic as much as possible.

**Comment by Joaveinz** [comment]
@MRayermannMSFT Thanks.

I am using LRS without a CDN.

This "issue" is not mission critical, but I was really just curious about how this works as the documentation is not so straight forward

Thanks for pointing me in the right direction though.

I'll close this issue
