### ISSUE TITLE
Error on storeage explorer

### ISSUE THREAD

**Issue by vijaimohan-accenture** [microsoft/AzureStorageExplorer#3638]
Error message:
The requested action could not be completed.

Details:
getaddrinfo ENOTFOUND accenture.com.file.core.windows.net

**Storage Explorer Version**: 1.15.1
**Build Number**: 20200902.9
**Platform/OS**: Windows
**Architecture**: x64
**Regression From**:  

## Bug Description ##
The requested action could not be completed.

Details:
getaddrinfo ENOTFOUND accenture.com.file.core.windows.net

## Steps to Reproduce ##
Login to Storage explorer, under storage account, clicked refresh to sync the file storage. This is throwing the mentioned error.

## Expected Experience ##
Sync of the folders between the online storage account and the storage explorer

## Actual Experience ##
Error occured.
The requested action could not be completed.

Details:
getaddrinfo ENOTFOUND accenture.com.file.core.windows.net

**Comment by MRayermannMSFT** [comment]
@vijaimohan-accenture the storage endpoint `accenture.com.file.core.windows.net` is a little odd. Normally that type of URL is something like:

<storage account name>.file.core.windows.net

I don't think you have have "accenture.com" as a Storage Account name. How are you connecting to this storage account/file share? Sign in or some sort of attach?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you're still encountering this problem, please open a new issue. Thanks!
