### ISSUE TITLE
Can no longer access storage

### ISSUE THREAD

**Issue by dxkaufman** [microsoft/AzureStorageExplorer#3639]
Version: 1.15.1
AzCopy Version: 10.6.0

Platform: macOS
Architecture: x64 
Build Number: 20200902.9 
Commit: 2e31227ac 
Support ID: d78b3fe4-29ad-cfee-b44f-c41ec5bd8062 

**Storage Explorer Version**: 1.15.1
**Build Number**: 20200902.9
**Platform/OS**: Mac OS 10.14.6
**Architecture**: Intel Core i7
**Regression From**:  1.14.2

## Bug Description ##
I just installed 1.15.1 (by having it download the zip and then unzipping into the Applications folder and overwriting the old version), and now when I try to access storage in either of two subscriptions, I get the following error message:

```
Unable to retrieve child resources.

Details:
["TypeError:Object prototype may only be an Object or null: undefined"]
```
It fails even after I remove my account from Storage Explorer and add it back in. I am able to access the account through the portal just fine.

## Steps to Reproduce ##

1. open 1.15.1
2. 'Storage Accounts' is already open, showing the storage account, as shown in the screenshot below.

![image](https://user-images.githubusercontent.com/26446314/95117630-bea66300-06fd-11eb-98ea-e001f42ae948.png)

3. click the arrow next to the storage account name, or double click the name
4. error shows up

**Comment by lxalln** [comment]
I am receiving the same error, using the same version, on Linux.

**Comment by MRayermannMSFT** [comment]
@dxkaufman and @lxalln 

Do y'all have access to any other storage accounts? If yes, does this repro with them as well?
Are y'all able to access the troublesome storage accounts from other machines?
If you single click on the node for the storage account, do you see any properties in the bottom left/do any of the properties have an error/bad looking value?

**Comment by dxkaufman** [comment]
@MRayermannMSFT It is happening with 2 storage accounts, both accessed with the same Azure user ID. Single clicking looks fine. I'll have to check on the other machine later.

**Comment by dxkaufman** [comment]
@MRayermannMSFT I installed 1.15.1 on a Mac laptop, and it seems to be working there.

**Comment by lxalln** [comment]
@MRayermannMSFT I have added an additional Microsoft account with storage accounts, and I get the same error on all storage accounts, in all subscriptions.

I can get to the storage accounts/containers from within the Azure Portal.

I can see the properties of the storage accounts, nothing looks to be strange:
![image](https://user-images.githubusercontent.com/2781908/95834758-43fcc980-0d35-11eb-9c42-89e15d99cae0.png)

**Comment by MRayermannMSFT** [comment]
@dxkaufman @lxalln can y'all try doing a clean install of storage explorer on the affected machines?

For macOS, you should:
- delete the .app from the Applications folder
- re-download from https://storageexplorer.com
- unzip
- drag and drop into the Applications folder

For linux, if you used .tar.gz package, this should mean:
- delete all files you extracted from the package
- redownload package
- extract and install where you'd like

If you did snap, then:
- `snap remove storage-explorer`
- `snap install storage-explorer`
- `snap connect storage-explorer:password-manager-service :password-manager-service`

**Comment by dxkaufman** [comment]
@MRayermannMSFT I'm now getting this error message:
```
Unable to retrieve child resources.

Details:
["Error:Hub Controller process exited prematurely with signal 'SIGABRT'."]
```

**Comment by lxalln** [comment]
@MRayermannMSFT I removed the package and re-installed. Same error.
However, I was still authenticated, are there more files I should remove in order to test this? The files in ~ perhaps?

**Comment by MRayermannMSFT** [comment]
@lxalln are you installing via Snap or .tar.gz?

**Comment by lxalln** [comment]
@MRayermannMSFT AUR. But I'll try the tar.gz directly next.

**Comment by MRayermannMSFT** [comment]
It seems like y'all are most likely having issues with the library we use for auth/the process that hosts that library. So let's see if we can diagnose that. I'm going to give you some steps.

So the steps for both of y'all will be the same, the difference is the value for the term "ServiceHub logs directory".

For snap, this is going to be: ~/snap/storage-explorer/current/.ServiceHub/logs
For macOS, this is going to be: ~/.ServiceHub/logs

So here's the steps:
1. Start Storage Explorer
2. Go to settings (gear on the left) -> Application -> Sign-In and enable Verbose Authentication Logging
3. Then do Help -> Reset, select "Authentication" only, and click ok (**This will sign you out of all accounts, if you don't want to do this, then next best thing is to only sign out of the account that is giving you issues.**)
3. Close Storage Explorer
4. Delete everything in the ServiceHub logs directory
5. Start Storage Explorer
6. Reproduce the your issue your facing/get to the point you see an error
7. Close Storage Explorer
8. Zip up the contents of the ServiceHub logs directory and attach that zip to this issue (**Some files in the log dir might have your email address or other PII, if you don't want that out in the open, then either redact it, or let me know that you'd rather share the zip another way and we can figure something out**)

Thanks!

**Comment by dxkaufman** [comment]
At some point, I was forced to change my Azure password, and then Storage Explorer wanted me to log in again, and since I did, it's working fine.

**Comment by lxalln** [comment]
@MRayermannMSFT  Here you go:

[servicehub-logs.zip](https://github.com/microsoft/AzureStorageExplorer/files/5482750/servicehub-logs.zip)

**Comment by MRayermannMSFT** [comment]
@lxalln I looked at the logs and nothing stood out to me. I'm pretty stumped on this one. :( Did you every try using a different machine? Doing that will rule out either install/machine issue vs Azure account issue.

**Comment by lxalln** [comment]
@MRayermannMSFT I tested it on another machine and it worked fine, although I noticed it had updated to 1.16.0...

I just updated to 1.16.0 here too, and everything is working now! Perhaps related to #3247 

Anyway, it's working now! Thank you whoever fixed whatever it was you fixed.

**Comment by MRayermannMSFT** [comment]
Welp, ok then. As far as I know we changed nothing. I'm glad it is working now though.
