### ISSUE TITLE
Unexpected Cancel?

### ISSUE THREAD

**Issue by kkennett** [microsoft/AzureStorageExplorer#3640]
Files are not uploading.

{
  "message": "\"UnexpectedCancel\""
}

Very unhelpful error message
![Capture](https://user-images.githubusercontent.com/10833689/95118444-2ad59680-06ff-11eb-8454-e0d5216d5290.PNG)

**Comment by raviabhiram** [comment]
I get the same error

**Comment by MRayermannMSFT** [comment]
@kkennett @raviabhiram 

A couple of starter questions:

1. Storage Explorer version?
2. Operating system?
3. What are you transferring to and from?

Finally, after you see this error message, can you check your azcopy logs directory (<user dir>/.azcopy) for a log file which has a date created at about the same time you started the transfer? If so can you please share that log file here.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
