### ISSUE TITLE
Cannot open $web folder of storage account, access denied for root account

### ISSUE THREAD

**Issue by anupdg** [microsoft/AzureStorageExplorer#3641]
**Storage Explorer Version**: 1.15.1
**Platform/OS**: Windows 10
**Architecture**: x64? 

I am getting this error-

Unable to retrieve child resources.
Details:
["RestError:﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.\nRequestId:9976121b-101e-003a-4de9-9ba431000000\nTime:2020-10-06T14:00:16.5643411Z</Message></Error>"]

I have valid user name and password.

I have even tried to login to portal.azure.com as my root user details. On click on the storage account => Containers>$web or static website, getting the following error-

Access denied
You do not have access
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:e702c228-101e-0031-57eb-9bbc45000000 Time:2020-10-06T14:18:37.2510426Z
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

Access control -> my access -> is  " Service Administrator | Has full access to all resources in the subscription"

I am currently running on trial, getting expired on next 6 days.

Thanks
Anup

**Comment by MRayermannMSFT** [comment]
@anupdg ﻿AuthorizationPermissionMismatch means there's is some issue with your permissions/level of access.

1. Is it possible your trial had already expired?
2. Are you certain that static websites are supported for trial subscriptions?
3. Can you try give yourself a roles like "Blob Data Owner" at the Storage Account level?

**Comment by MRayermannMSFT** [comment]
Also, we don't see any built in Service Administrator role: https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles

So that's probably the issue. It sounds like maybe that is a classic role?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
