### ISSUE TITLE
[loc] Assistance with translation: "TitleAdlsGen2BlobSnapshots"

### ISSUE THREAD

**Issue by cristianosuzuki77** [microsoft/AzureStorageExplorer#3642]
**String Resource ID**: 0; "TitleAdlsGen2BlobSnapshots"
**Source String**: Enable ADLS Gen2 snapshots (preview)
**Filename**: src\Standalone\resources\Shell.json
**Question**: Please let us know current Dev Comment is outdated or not.

**Comment by cristianosuzuki77** [comment]
VCQ 307486

**Comment by craxal** [comment]
Yes, this comment is still valid. The string is in relation to a temporary setting. Once the feature becomes generally available, the string will no longer be needed.
