### ISSUE TITLE
[loc] Asistance with translation: "ConfigureFileCorsFailure"

### ISSUE THREAD

**Issue by cristianosuzuki77** [microsoft/AzureStorageExplorer#3643]
**String Resource ID:** 0; "ConfigureFileCorsFailure"
**Source String:** Failed to configure File Share service CORS rules for storage account '%1$s'
**Filename:** Standalone\resources\Azure.json
**Question:** Is this entry translatable? Due to context (also mentions "Blob service, File service... which are nontranslatable) we leave this service in English by now as well. Please, confirm.

**Comment by cristianosuzuki77** [comment]
VCQ 313658

**Comment by craxal** [comment]
Yes, this string should be translated. We understand that terms like "File Share service" or "File service" are not translated, and that's fine.
