### ISSUE TITLE
Unable to retrieve child resources.

### ISSUE THREAD

**Issue by Tjianke** [microsoft/AzureStorageExplorer#3647]
Unable to retrieve child resources.

Details:
["RestError:{\"info\":\"Invalid request!\"}"]

**Comment by MRayermannMSFT** [comment]
@Tjianke can you give some more context about what you were doing at the time of this error?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
