### ISSUE TITLE
Show an odd string '%1$s' in the descriptions on the blob's delete dialog when soft delete is disabled

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3649]
**Storage Explorer Version:** 1.16.0-dev
**Build**:  20201009.2
**Branch**: main
**Platform/OS:** Windows 10/ Fedora release 29/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Previous release (1.15.1)

**Steps to reproduce:**

1. Expand one storage account -> Blob Containers (Make sure the soft delete is disabled).
2. Create one blob container -> Upload one blob -> Try to delete the blob.
3. Check the descriptions on the delete dialog.

**Expect Experience:**
No odd string shows in the descriptions.
The screenshot in version 1.15.1.
![image](https://user-images.githubusercontent.com/41351993/95569388-1a535200-0a58-11eb-8494-f4ce108d1751.png)

**Actual Experience:**
Show an odd string '%1$s' in the descriptions.
![image](https://user-images.githubusercontent.com/41351993/95569377-16273480-0a58-11eb-9c07-e6d88eb202e5.png)

**More Info:**
This issue also reproducers when deleting one folder.
![image](https://user-images.githubusercontent.com/41351993/95569538-4b338700-0a58-11eb-9524-065b75113cdc.png)

**Comment by v-limu** [comment]
Verified on build 20201010.4. This issue has been fixed. So close it.
