### ISSUE TITLE
Pop up an error infor bar when clicking 'Configure Proxy' in 'Edit' menu

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3655]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20201010.4
**Branch**: main
**Platform/OS**: Windows 10/ Fedora release 29/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Previous release(1.15.1)

**Steps to reproduce:**

1. Lanuch Storage Explorer.
2. Click 'Edit' menu -> Click 'Configure Proxy'.
3. Check the result.

**Expect Experience:**
The 'Configure Proxy' dialog pops up.

**Actual Experience:**
Pop up an error infor bar.
![image](https://user-images.githubusercontent.com/54055206/95649988-57304f00-0b13-11eb-8576-953a83659e2a.png)
Detials:
![image](https://user-images.githubusercontent.com/54055206/95649994-5d263000-0b13-11eb-83da-c0e9b648fcf3.png)

**Comment by v-xianya** [comment]
Verified this issue on build 20201014.3. Fixed.
