### ISSUE TITLE
Pop up an error dialog when clicking 'Get Shared Access Signature…' for one storage account 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3658]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20201010.4
**Branch**: main
**Platform/OS**: Windows 10/ Fedora release 29/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Previous release(1.15.1)

**Steps to reproduce:**

1. Select one Non-ADLS Gen2 storage account -> Click 'Get Shared Access Signature...'.
2. Check the result.

**Expect Experience:**
Pop up the 'Shared Access Signature' dialog.

**Actual Experience:**
An error dialog pops up.

![image](https://user-images.githubusercontent.com/54055206/95650218-bf336500-0b14-11eb-9387-88807b3f6df5.png)

**More Info:**

1. This issue also reproduces for blob containers and blobs.
2. This issue also reproduces for file shares and files.
3. This issue also reproduces for tables.
4. Pop up the below error dialog for queues.
![image](https://user-images.githubusercontent.com/54055206/95650262-19342a80-0b15-11eb-90a8-e5afa1902904.png)

**Comment by v-xianya** [comment]
Verified this issue on build 20201014.3. Fixed.
