### ISSUE TITLE
Show a failed activity log when clicking 'Manage Access…' for one ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3661]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20201010.4
**Branch**: main
**Platform/OS:** Windows 10/ Fedora release 29/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Previous release(1.15.1)

**Steps to reproduce:**

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a new blob container -> Right click it -> Click 'Manage Access...'.
3. Check the result.

**Expect Experience:**
The 'Manage Access' dialog pops up.

**Actual Experience:**
No 'Manage Access' dialog pops up and show a failed activity log.
![image](https://user-images.githubusercontent.com/54055206/95650672-8ba60a00-0b17-11eb-9a44-b6b09fbd2e02.png)
Detials:
![image](https://user-images.githubusercontent.com/54055206/95650674-8fd22780-0b17-11eb-942a-11e1d3f6f662.png)

**More Info:**
This issue also reproduces for one ADLS Gen2 blob and folder.

**Comment by v-xianya** [comment]
Verified this issue on build 20201014.3. Fixed.
