### ISSUE TITLE
Pop up an error information bar when clicking 'Apply Filters' with the default filter

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3662]
**Storage Explorer Version:** 1.16.0-dev
**Build**:  20201010.4
**Branch**: main
**Platform/OS:** Windows 10/ Fedora release 29/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one non-ADLS Gen2 storage account -> Blob Containers.
2. Create one blob container -> Click 'Show Filter Panel' -> Select the option 'Filters' -> Click 'Apply Filters'.
3. Check the result.

**Expect Experience:**
No error occurs.

**Actual Experience:**
Pop up an error information bar.
![image](https://user-images.githubusercontent.com/41351993/95651156-e12fe600-0b1a-11eb-959d-a85a8ddea46d.png)

`﻿<?xml version="1.0" encoding="utf-8"?> <Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid. RequestId:61720e17-601e-0003-24e4-9e8bf8000000 Time:2020-10-10T09:05:53.3571959Z</Message><QueryParameterName>comp</QueryParameterName><QueryParameterValue>blobs</QueryParameterValue></Error>`

**Comment by JasonYeMSFT** [comment]
Blob tags is in preview. Please refer to https://docs.microsoft.com/en-us/azure/storage/blobs/storage-manage-find-blobs?tabs=azure-portal on how to enable the feature.
