### ISSUE TITLE
Secondary Drive won't upload with AzCopy 10.60

### ISSUE THREAD

**Issue by infopipe** [microsoft/AzureStorageExplorer#3663]
**Storage Explorer Version**: Microsoft Azure Storage Explorer 1.15.1  AzCopy 10.6.0
**Build Number**: 
**Platform/OS**: Windows 10
**Architecture**: x64? 

**Regression From**:  

## Process Failed ##
message": "The specified cookie value in VHD footer indicates that disk 'abcd' with blob https://md-impexp-zlq4pdrgffcm.blob.core.windows.net:8443/mrtwhbmsxwlg/abcd is not a supported VHD. Disk is expected to have cookie value 'conectix'."  There are other messages in the attached log file.

## Steps to Reproduce ##
1.  Ran vhd resizer on copied vhd file.  Resized to multiple sizes ranging from 204 to 220 Gb.  Fixed Size (not dynamic:  The first OS drive uploaded after attempting fixed size.  That drive was 130 Gb.
2.  Attempted upload with Azure Storage Explorer. Failed.

## Expected Experience ##
File should upload.

## Actual Experience ##
Upload failed.

## Additional Context ##
Any help would be greatly appreciated.

[c622821e-db03-634f-65aa-1b467d8b05f9.log](https://github.com/microsoft/AzureStorageExplorer/files/5359140/c622821e-db03-634f-65aa-1b467d8b05f9.log)

[Error_File.txt](https://github.com/microsoft/AzureStorageExplorer/files/5359145/Error_File.txt)

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
