### ISSUE TITLE
Add droplist of recent filters (query predicates) in CosmosDB Documents Filter edit line

### ISSUE THREAD

**Issue by ariehf** [microsoft/AzureStorageExplorer#3664]
After selecting CosmosDB Documents, and then "Filter", one is presented with "SELECT * FROM c" and an edit line with the example text "Type a query predicate (e.g. WHERE c.id = '1')".
After entering a query predicate for a certain collection and pressing Apply, and then entering a different query predicate (in the same collection or different collection, but without pressing "Keep Open"), then the initial query predicate entered needs to be reentered.
A droplist of recent query predicates used for the current collection would be very useful in populating the edit line.

**Comment by southpolesteve** [comment]
The Cosmos team recently deprecated our integration with Azure Storage Explorer. [Here is the full deprecation notice from the 1.15.1 Storage Explorer release notes:](https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.15.1)

> The Azure Cosmos DB integration with Storage Explorer has been deprecated. Any existing functionality will not be removed for a minimum of one year from this release. Users should use the Azure Portal, the Azure Portal desktop app, or the standalone Cosmos Explorer instead – all of which contain many new features that aren’t currently supported in Storage Explorer. Additionally, the Azure Cosmos DB team has also open sourced the data explorer project and will be investing in their own desktop tooling at a later date. Please keep an eye on their repository for more information. 

Currently, we are not prioritizing new features or bug fixes for Cosmos in Azure Storage Explorer. If you the issue you are reporting also applies to the Azure Portal or https://cosmos.azure.com, please file an issue in [our open source Cosmos Explorer repo](https://github.com/Azure/cosmos-explorer)
