### ISSUE TITLE
Event Based Trigger not working as Expected

### ISSUE THREAD

**Issue by shibashish13999** [microsoft/AzureStorageExplorer#3666]
**Storage Explorer Version**: 1.14.2
**Build Number**: 20200715.2
**Platform/OS**:  Windows 10
**Architecture**: ia32
**Regression From**:  Not sure

Hello All,

 I have created a event based trigger for triggering some pipelines. So the issue is when i try to add csv files manually through storage explorer to designated blob location my trigger is working perfectly, but when an external source like I have a backend python code which is pushing the files into the blob location, when this is happening the event based trigger is not triggering. I just checked the content type for manual upload the content type is vnd.ms-excel and for python code based upload is octet-stream. Is the issue something related to this or any other. My Storage explorer version is 1.14.2.

Thanks,
Shibashish

**Comment by JasonYeMSFT** [comment]
Copied from #2289. AzCopy did some work to associate content types with certain file extensions. If you want the same behavior, you need to handle that in the python code.

**Comment by MRayermannMSFT** [comment]
@shibashish13999 what JasonYeMSFT has said is most likely true. Since what you're having issues with is uploading with the python functions SDK, we would recommend going to their repo for further help. Thanks!
