### ISSUE TITLE
Show a successful activity log when pasting one existing empty emulator blob container

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3667]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20201010.6
**Branch**: main
**Platform/OS**: Windows 10
**Emulator**: 5.10.0.0
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**

1. Install and run Emulator -> Launch Storage Explorer.
2. Expand Local & Attached -> Storage Accounts -> (Emulator - Default Ports) (Key) -> Blob Containers.
3. Create a new blob container and copy it -> Right click the Blob Containers node -> Paste the blob container.
4. Check the activity log.

**Expect Experience:**
Show a failed activity log.

**Actual Experience:**
Show a successful activity log.
![image](https://user-images.githubusercontent.com/54055206/95726123-1c611f00-0cab-11eb-8b0e-244612d472a0.png)

**More Info:**

1. Show a failed activity log when pasting one existing table.
 ![image](https://user-images.githubusercontent.com/54055206/95726355-6944f580-0cab-11eb-9a8d-66f6878ebd67.png)
2. This issue doesn't reproduce for nomarl accounts.

**Comment by MRayermannMSFT** [comment]
edge case won't fix
