### ISSUE TITLE
Display an incorrect title on the 'New Vertex' dialog for one graph 

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#367]
**Storage Explorer Version**: 1.2.0 
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180628.5
**Commit**: a855d63f
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Go to subscription -> Graph account -> Database -> Graph.
2. Click 'New Vertex' on the toolbar of the editor - > Check the title of the dialog.

#### Expected Experience: ####
It displays as 'Microsoft Azure Storage Explorer - New Vertex' on the dialog

#### Actual Experience: ####
It displays as  'Microsoft Azure Storage Explorer - New Collection' on the dialog.
![title](https://user-images.githubusercontent.com/34729022/42080226-7f410a0e-7b71-11e8-865a-f6d3880d6dfc.png)

**Comment by MRayermannMSFT** [comment]
Bug reported as fixed. Closing.
