### ISSUE TITLE
Azure Storage Explorer is failing to connect to Cloud with AD

### ISSUE THREAD

**Issue by sguha-v** [microsoft/AzureStorageExplorer#3671]
**Storage Explorer Version**: 1.15.1
**Build Number**: 20200902.9
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  Never worked

## Bug Description ##
Azure Storage Explorer is failing to connect to Cloud with AD

## Steps to Reproduce ##
Steps: 
Microsoft Azure Storage Explorer >  Add an account >  Add an Azure account > sguha@company.com > 
Pick an account: Picked up my Azure AD account

## Expected Experience ##
The Azure Storage should be connected

## Actual Experience ##
Got message:
sguha@company.com
Subscription could not be loaded. Please try reentering credentials or removing and re-adding the account.

## Additional Context ##
Did both of the above but no luck.

**Comment by sguha-v** [comment]
Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: e796cf6d-fb86-4621-99b5-6764cafeee58, Error: {
  "name": "Error",
  "message": "self signed certificate in certificate chain",
  "stack": "Error: self signed certificate in certificate chain\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1331:34)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at TLSSocket.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at TLSSocket.emit (events.js:210:5)\n    at TLSSocket._finishInit (_tls_wrap.js:804:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:618:12)",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}

**Comment by MRayermannMSFT** [comment]
@sguha-v please see our troubleshooting guide for help with this issue: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C1804#error-self-signed-certificate-in-certificate-chain-and-similar-errors

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
