### ISSUE TITLE
The layout of the descriptions in the 'Sign In' dialog is unsightly when using device code flow sign-in

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3672]
**Storage Explorer Version:** 1.16.0-dev
**Build**:  20201012.5
**Branch**: main
**Platform/OS:** Windows 10/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Previous release (1.15.1)

**Steps to reproduce:**
1. Launch Storage Explorer -> Open 'Settings -> Application' -> Enable the setting 'Use device code flow sign-in'.
2. Open connect dialog -> Click 'Next' -> Check the popped dialog.

**Expect Experience:**
The layout of the descriptions in the dialog is normal.
![image](https://user-images.githubusercontent.com/41351993/95835994-7f1cee00-0d71-11eb-98cb-56c0f9c43bda.png)

**Actual Experience:**
The layout of the descriptions in the dialog is unsightly.
![image](https://user-images.githubusercontent.com/41351993/95835974-7a583a00-0d71-11eb-9dbf-9c7394172efc.png)

**Comment by v-xianya** [comment]
@JasonYeMSFT Verified this issue on build 20201014.3. The current dialog as below. Is it by design to add a Sub-title 'Sign In' to the dialog?
![image](https://user-images.githubusercontent.com/41351993/95935105-09626200-0e05-11eb-8392-1ab8e764e427.png)

**Comment by JasonYeMSFT** [comment]
@v-xianya Yes, this is expected.

**Comment by v-xianya** [comment]
got it. we are going to close this issue.
