### ISSUE TITLE
Self signed certificate error

### ISSUE THREAD

**Issue by bigdatamnl** [microsoft/AzureStorageExplorer#3674]
I have already tried the troubleshooting steps in this link, but still faces the same issue.

https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004

Unable to retrieve child resources.

Details:
["FetchError:request to https://appsproductsupply.blob.core.windows.net/?include=metadata&comp=list failed, reason: self signed certificate in certificate chain"]

**Comment by MRayermannMSFT** [comment]
@bigdatamnl which steps from the troubleshooting guide have you tried so far?

**Comment by MRayermannMSFT** [comment]
Close due to lack of response. Please open a new issue if you are still having problems.
