### ISSUE TITLE
Crashes a table with the error rowA[col]._.toLowerCase is not a function

### ISSUE THREAD

**Issue by raholland79** [microsoft/AzureStorageExplorer#3675]
I have a particular Blob Storage table that I can not open.  I get the error 

`rowA[col]._.toLowerCase is not a function`

Nothing loads, blank tab.

Version `1.15.1`

I Physically deleted and re-created the table, no dice.

Accessing the table via .NET core in an Azure Function works fine.  It's just the Storage Explorer.

**Comment by MRayermannMSFT** [comment]
@raholland79 is it possible for you to share the table with us, maybe via a SAS URI?

Also, to be clear, are you talking about "tables" like this?
![image](https://user-images.githubusercontent.com/21112697/96492192-211c5a80-11f8-11eb-823a-bafc2f9d2345.png)

**Comment by raholland79** [comment]
"table" like that, exactly.

Can I send you the SAS URI privately?  

It seems to be a column setting .  I can fire up a vm and open the dataset just fine with a fresh install.  

So I think we would need to examine those settings, wherever they are stored.

**Comment by MRayermannMSFT** [comment]
@raholland79 maybe it is this issue that we just fixed for our next release? https://github.com/microsoft/AzureStorageExplorer/issues/271

Could we send you a private/preview build of 1.16.0 and you see if you can still repro your problem in that version?

**Comment by raholland79** [comment]
That issue very well could be the cause, we have booleans that may be null.

I would gladly try the preview build.

**Comment by craxal** [comment]
@raholland79 I'm assuming you're on Windows? You can download the preview build [right here](https://cralvordtest02.blob.core.windows.net/customer-share/release/20201027.6/StorageExplorer-ia32.exe).

**Comment by raholland79** [comment]
Preview build solved the issue.

Thanks a lot!
