### ISSUE TITLE
The blobs under folders are not counted when using 'Folder Statistics' for one emulator blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3679]
**Storage Explorer Version:** 1.16.0-dev
**Build**:  20201014.3
**Branch**: main
**Platform/OS:** Windows 10
**Architecture**: ia32
**Azurite:** 3.9.0
**Regression From:** Not a regression

**Steps to reproduce:**
1. Install and start Azurite -> Launch Storage Explorer.
2. Expand Local & Attached -> (Emulator - Default Ports) (Key) -> Blob Containers.
3. Create a blob container -> Upload one folder.
4. Click the icon 'Folder Statistics' -> Check the activity log.

**Expect Experience:**
The blobs under the folder are counted.
![image](https://user-images.githubusercontent.com/41351993/95968614-3aac5380-0e40-11eb-8438-5e320da631c9.png)

**Actual Experience:**
The blobs under the folder are not counted. 
![image](https://user-images.githubusercontent.com/41351993/95968604-3718cc80-0e40-11eb-8f76-46096bf7c8f4.png)

**More Info:**
This issue doesn't reproduce when using Emulator.

**Comment by MRayermannMSFT** [comment]
Won't fix. We need to re-implement statistics in v12 SDK, and this bug does not meet the bar for immediately fixing.
