### ISSUE TITLE
The red border still displays for the new added metadata after updating the existing metadata name 

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#368]
**Storage Explorer Version**: 1.2.0 
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180628.5
**Commit**: a855d63f
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Go to subscription -> Storage Accounts.
2. Open one blob container which contrains one blob -> Open the 'Properties' dialog for the blob -> Add the first metadata named 'metadata1' -> Add the second metadata with the same name 'metadate1' -> Update the first metadata with 'metadata2'(Make sure these two metadata with a different name).
3. Check the second metadata.

#### Expected Experience: ####
No red border displays.

#### Actual Experience: ####
The red border still displays.
![redborder](https://user-images.githubusercontent.com/34729022/42081415-e872140c-7b74-11e8-9dc3-ac0ea8e010df.png)

**Comment by MRayermannMSFT** [comment]
@craxal , fix for 1.2.0?

**Comment by MRayermannMSFT** [comment]
Merged into rel/1.3.0

**Comment by craxal** [comment]
Reopening this issue since CTI reported this as still reproducible.

**Comment by craxal** [comment]
Merged some fixes.
