### ISSUE TITLE
Unable to copy disk from one region to another using Storage Explorer 

### ISSUE THREAD

**Issue by ashok624443** [microsoft/AzureStorageExplorer#3680]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:  

![image](https://user-images.githubusercontent.com/10362602/96037536-98ae5a80-0e83-11eb-98a9-47ea244f19d4.png)

**Comment by ashok624443** [comment]
![image](https://user-images.githubusercontent.com/10362602/96037569-a2d05900-0e83-11eb-9777-1145d8f11a90.png)

**Comment by MRayermannMSFT** [comment]
@ashok624443 what error are you getting when you attempt the copy?

**Comment by ashok624443** [comment]
This issue resolved.

Thank you.
