### ISSUE TITLE
Azure Storage explorer

### ISSUE THREAD

**Issue by Rohitkulkarni77** [microsoft/AzureStorageExplorer#3681]
Hello Team,

I am trying to access the container in storage account at that time i getting error :
Details:
["RestError:﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.\nRequestId:3403ffb8-101e-0075-04b3-a26029000000\nTime:2020-10-15T05:28:07.3698027Z</Message></Error>"]

Regards
Rk

**Comment by MRayermannMSFT** [comment]
@Rohitkulkarni77 means that the credentials you are using to connect probably don't have the needed permissions to access what you want to access.

What type of credentials are you using to access your resources?

- Have you signed in and are looking under a subscription?
- Attached with Azure AD?
- Attach with connection string, and if so, SAS or key?
- Attach with SAS URI?
- Attach with name and key?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you're still having problems.
