### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by timzhan** [microsoft/AzureStorageExplorer#3682]
**Storage Explorer Version**:  v1.15.1
**Build Number**:  Aug 2020
**Platform/OS**:  Windows 10
**Architecture**:  x64
**Regression From**:   Yes. 

## Bug Description ##
 Unable to retrieve child resources while using connection string to connect to a local blob storage. Was suggested to open an issue on Github.

## Steps to Reproduce ##

Local & Attached -> Storage Accounts -> Right Click -> Connect to Azure Storage -> Use a connection string -> paste the Connection String for local blob -> it shows "Successfully added new connection" -> Double click Blob Containers -> Error is prompted.

## Additional Context ##

Unable to retrieve child resources.

Details:
["RestError:﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>InvalidHeaderValue</Code><Message>The value for one of the HTTP headers is not in the correct format.\nRequestId:37893296-9d02-4318-8ae5-cf6664409f9d\nTime:2020-10-15T06:24:36.9082711Z</Message><HeaderName>x-ms-version</HeaderName><HeaderValue>2019-12-12</HeaderValue><ExceptionDetails><ExceptionMessage>The value 2019-12-12 provided for request header x-ms-version is invalid.</ExceptionMessage><StackTrace>Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.InvalidHeaderProtocolException: The value 2019-12-12 provided for request header x-ms-version is invalid.\n   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.RunVersionCheck() in F:\\Storage-XStore\\src\\XFE\\common\\Protocols\\REST\\src\\BasicHttpProcessorWithAuthAndAccountContainerBase.cs:line 788\n   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.ProcessImpl(AsyncIteratorContext`1 async)+MoveNext() in F:\\Storage-XStore\\src\\XFE\\common\\Protocols\\REST\\src\\BasicHttpProcessorWithAuthAndAccountContainerBase.cs:line 1537</StackTrace></ExceptionDetails></Error>"]

![2020-10-15_142810](https://user-images.githubusercontent.com/66768111/96086033-3ccfea00-0ef4-11eb-98cf-f8880278c95f.png)
![2020-10-15_143520](https://user-images.githubusercontent.com/66768111/96086041-3e99ad80-0ef4-11eb-893d-e89065bd2d1c.png)

**Comment by MRayermannMSFT** [comment]
@timzhan are you connecting to an emulator or something else? If an emulator, is it azurite or the .net emulator? If something else, what is it?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you're still having problems.
