### ISSUE TITLE
The selected permissions 'Tag' and 'Filter' do not display on one SAS attached storage account's properties panel

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3683]
**Storage Explorer Version:** 1.16.0-dev
**Build**:  20201014.18
**Branch**: main
**Platform/OS:** Windows 10/Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Select one normal storage account -> Attach it via SAS (Select full permissions).
2. After successfully attached -> Check the permissions on the attached storage account's properties panel.

**Expect Experience:**
The permissions display well.

**Actual Experience:**
The permissions 'Tag' and 'Filter' do not display.
![image](https://user-images.githubusercontent.com/41351993/96092664-c20bcc80-0efd-11eb-94f6-554f79577910.png)

![image](https://user-images.githubusercontent.com/41351993/96092656-bf10dc00-0efd-11eb-96ae-2e89cca73b07.png)

**Comment by v-xianya** [comment]
Verified this issue on build 20201016.4. Reproduce. We will verify this issue on a newer build.

**Comment by v-limu** [comment]
Verified this issue on build 20201020.3. This issue has been fixed. So close it.
