### ISSUE TITLE
Unable to sign in: La méthode 'get_SerializationSettings' du type 'Microsoft.Azure.Management.ResourceManager.SubscriptionClient' de l'assembly 'Microsoft.Azure.Management.ResourceManager, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' n'a pas d'implémentation.

### ISSUE THREAD

**Issue by RaijinDS** [microsoft/AzureStorageExplorer#3684]
**Storage Explorer Version**: 1.15.1 
**AzCopy Version**: 10.6.0
**Build Number**: 20200902.9
**Platform/OS**: Windows 10 Enterprise v1903
**Architecture**: x64

## Bug Description ##
I installed Microsoft Azure Storage Explorer. I tried to connect to my azure account. After typing my credential (only my mail, ADFS makes the authentication),  Microsoft Azure Storage Explorer fired an exception : 

{
  "message": "\"La méthode 'get_SerializationSettings' du type 'Microsoft.Azure.Management.ResourceManager.SubscriptionClient' de l'assembly 'Microsoft.Azure.Management.ResourceManager, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' n'a pas d'implémentation.\""
}

## Steps to Reproduce ##
Launch Microsoft Azure Storage Explorer.
Add Account.
Add an Azure Account.
Type your mail address on the popup, 
Click on Next
Wait for organization auth page
See the error.

![1](https://user-images.githubusercontent.com/57623002/96101455-c1f7d680-0ed5-11eb-98dc-4ed3bf720a70.png)
![2](https://user-images.githubusercontent.com/57623002/96101460-c3290380-0ed5-11eb-8176-f8856e1e0bd6.png)
![3](https://user-images.githubusercontent.com/57623002/96101458-c2906d00-0ed5-11eb-8300-9656f59c8908.png)

## Expected Experience ##
Be connected and see my subscription

## Actual Experience ##
Unable to see anything because I can't log in...

**Comment by MRayermannMSFT** [comment]
@RaijinDS we had another user open a similar issue a few months ago. I'm going to direct you over to that issue.

**Comment by MRayermannMSFT** [comment]
See issue #2244
