### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by IvNen** [microsoft/AzureStorageExplorer#3689]
**Storage Explorer Version**:1.15.1 
**Build Number**: 20200902.9
**Platform/OS**: Windows
**Architecture**: is32
**Regression From**:  

## Bug Description ##

Attempt to access Local Storage Emulator and getting and error:

The requested action could not be completed.

Details:
Network timeout error: connect ECONNREFUSED 127.0.0.1:10002

## Steps to Reproduce ##
Attempt 1: Updated Storage Explorer to latest version.
Attempt 2: Installed latest version on a fresh machine.
Both times same error

## Additional Context ##

![111](https://user-images.githubusercontent.com/35492007/96351489-8155b400-10b3-11eb-9756-be9eab7a7b8b.PNG)
![2222](https://user-images.githubusercontent.com/35492007/96351490-81ee4a80-10b3-11eb-93e5-ea6a44ab580f.PNG)

**Comment by IvNen** [comment]
Have managed to recreate this with a 
ElementaryOS 5.1.7 Hera
Built on Ubuntu 18.04.4 LTS
Linux 4.15.0-36-generic
GTK+ 3.22.30

Installed using following commands:
sudo apt install snapd
sudo snap install storage-explorer
sudo snap connect storage-explorer:password-manager-service :password-manager-service

Upon starting and attempting to access local tables or blobs receive the same error message as above

**Comment by eclausengit** [comment]
Same issue.  Doesn't matter which storage space I attempt to open.

**Comment by Olatunji-Longe** [comment]
Same issue here ... Same version as @IvNen on a windows machine ... even though it was previously working fine just before restarting my windows machine.

**Comment by MRayermannMSFT** [comment]
@IvNen  @Olatunji-Longe  @eclausengit did y'all start your emulators?

**Comment by IvNen** [comment]
Yes I did

**Comment by dhir78** [comment]
Same issue on Windows as well as on MAC OS.

**Comment by MRayermannMSFT** [comment]
@IvNen in your screenshot you are on Windows, and in a late comment you say you are on Linux.

This is important because in your screenshot you are trying to access Tables for the emulator storage account. Only the older, Windows only, .NET emulator currently supports tables. So if you are using Azurite, then this is basically expected.

**Comment by IvNen** [comment]
Sorry for the very late reply. I was on a latest Linux machine which is Ubuntu 20.04 and the windows is a work machine which by work policy is always up to date. I did however restarted the machine and reinstalled table storage and seemed to have fixed it. Have not had the issue since then.

**Comment by MRayermannMSFT** [comment]
Huh weird. Ok then.
