### ISSUE TITLE
The icon of the button is unclear when clicking the button of one extension in 'High Contrast -Black' theme 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3696]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20201021.4
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Click 'File -> Open Extension' -> Choose an extension bundle -> Restart Storage Explorer.
3. Click ‘View’ menu -> Click ‘Theme -> High Contrast –Black’.
4. Open Extensions Panel -> Click the button of the extension.
5. Check the icon of the button.

**Expect Experience:**
The icon of the button is clear.
![image](https://user-images.githubusercontent.com/54055206/96702124-03035580-13c4-11eb-87e7-1a44965cb2a4.png)

**Actual Experience:**
The icon of the button is unclear.
![image](https://user-images.githubusercontent.com/54055206/96702236-262e0500-13c4-11eb-8296-78ab3ac87053.png)

**More Info:**
This issue also reproduces in 'High Contrast -White' theme.
![image](https://user-images.githubusercontent.com/54055206/96702372-4231a680-13c4-11eb-9d4f-0320fb85973a.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into main.
