### ISSUE TITLE
 It is better to use quotes to surround the extension path in the prompt dialog

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3697]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20201021.4
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Click 'File -> Open Extension' -> Choose one unknown extension bundle.
3. Check the prompt dialog.

**Expect Experience:**
The extension path is surrounded by quotes in the prompt dialog.

**Actual Experience:**
The extension path is not surrounded by quotes in the prompt dialog.
![image](https://user-images.githubusercontent.com/54055206/96702892-cc7a0a80-13c4-11eb-85b5-5995c1055e8d.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into main.
