### ISSUE TITLE
It would be better to use 'Send Feedback' instead of 'Give Feedback' in the extensions panel

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3698]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20201021.4
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer -> Make sure one or more extensions are installed.
2. Go to 'INSTALLED EXTENSIONS' panel.
3. Click the extension button -> Check the actions items.

**Expect Experience:**
It would be better to use 'Send Feedback' instead of 'Give Feedback'.
![image](https://user-images.githubusercontent.com/41351993/96706077-afdfd180-13c8-11eb-84f3-f434dddaf690.png)

**Actual Experience:**
Show 'Give Feedback'.

**More Info:**
It would be better to update the opened webpage for the link 'Send Feedback'.
Now: https://github.com/Microsoft/AzureStorageExplorer/issues
Update to：https://github.com/microsoft/AzureStorageExplorer/issues/new/choose

**Comment by v-xianya** [comment]
@MRayermannMSFT 
Verified on build 20201023.5. Show 'Send Feedback' in the Extensions panel. 
![image](https://user-images.githubusercontent.com/41351993/96954983-285ca480-1527-11eb-82c9-04d777f0f57d.png)
In addition, is there a plan to update the link for the below icon 'Send Feedback'?
![image](https://user-images.githubusercontent.com/41351993/96955177-943f0d00-1527-11eb-97fd-8f21ab1470ec.png)

**Comment by MRayermannMSFT** [comment]
Oh my apologies. I merged a change in for this to main.
