### ISSUE TITLE
Search not working, when you have multiple pages and have a file that start with G, search does not find any files with G, you need to go to the pages that have files beginning with G to find the file

### ISSUE THREAD

**Issue by DiptiChauhan** [microsoft/AzureStorageExplorer#3699]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:

**Comment by JasonYeMSFT** [comment]
In which storage type did you encounter this issue (e.g. Blob, File Share, ADLS Gen1)?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.

**Comment by DiptiChauhan** [comment]
I have only received I notification to know you were closing this issue, hence lack of response.

ADLS Gen1
Explorer version 1.11.1

Windows 10
