### ISSUE TITLE
X button focus border is under search button

### ISSUE THREAD

**Issue by JakeRadMSFT** [Microsoft/AzureStorageExplorer#37]
**Storage Explorer Version: 1.0.0 RC 1**

**OS Version: Mac**

**Steps to Reproduce:**
1. get focus on X button

**Expected Experience:**
Focus border should be over Search button.

**Actual Experience:**
Focus border is under Search button. (Resolution: Change z-index on focus)

**Comment by MRayermannMSFT** [comment]
Fixed!
