### ISSUE TITLE
The tags that added in the upload dialog are not preserved after uploading

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3702]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20201022.3
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Select one blob container (make sure it supports tags)-> Click 'Upload -> Upload Files...'. -> Select one file then add some tags -> Click 'Upload'.
3. Right click the uploaded blob -> Click 'Edit Tags...'. 
4. Check the popped dialog.

**Expect Experience:**
The added tags show well.

**Actual Experience:**
No tag shows.

**Comment by JasonYeMSFT** [comment]
We haven't integrated the AzCopy bits to do this. When that is done,  I will test it and close this issue.

**Comment by v-limu** [comment]
Verified on build 20201029.1. This issue has been fixed. So close it.
