### ISSUE TITLE
It would be better to use a faster way to remove the added tags in the upload dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3703]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20201022.3
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Select one blob container (make sure it supports tags)-> Open one upload dialog -> Add several tags.
3. Try to remove the added tags.

**Expect Experience:**
It would be better to use a faster way to remove the added tags in the upload dialog.

**Actual Experience:**
The tags can be removed when both Key and Value are empty.

**Comment by JasonYeMSFT** [comment]
I changed to use explicit "X" buttons to handle removing entries.

**Comment by v-xianya** [comment]
This issue is fixed on build 20201023.5. So close it.
![image](https://user-images.githubusercontent.com/41351993/96954679-73c28300-1526-11eb-884a-1ed60580f12b.png)
