### ISSUE TITLE
The value of the property 'Supports Tags' is empty for one SAS attached blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3704]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20201022.3
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Open one storage account -> Blob Containers.
2. Select one blob container -> Attach it via SAS with full permissions.
3. Check the properties for the SAS attached blob container.

**Expect Experience:**
Show a value for the existing property 'Supports Tags'.

**Actual Experience:**
The value of the property 'Supports Tags' is blank.
![image](https://user-images.githubusercontent.com/41351993/96847025-41147e00-1485-11eb-8c51-6c210f67c53c.png)

**More Info:**
This issue also reproduces for one Public attached blob container.

**Comment by JasonYeMSFT** [comment]
For SAS attached blob container, that value is undefined because we may not know whether the feature is actually supported or not.

**Comment by MRayermannMSFT** [comment]
So let's put "Unknown" then.

**Comment by v-xianya** [comment]
This issue is fixed on build 20201023.5. So close it.
![image](https://user-images.githubusercontent.com/41351993/96954484-10385580-1526-11eb-9e1b-ed2c40f6b388.png)
