### ISSUE TITLE
Show a failed activity log when changing access tier for one ADLS Gen2 folder with subfolder

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3705]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20201022.3
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a new blob container -> Create a new folder -> Open the folder -> Upload one folder with blobs to it.
3. Right click the new folder -> Click 'Change Access Tier...' -> Apply.
4. Check the activity log.

**Expect Experience:**
Show a successful activity log.

**Actual Experience:**
Show a failed activity log.
![image](https://user-images.githubusercontent.com/54055206/96852309-92c00700-148b-11eb-8b82-aa5112b9bf5d.png)
![image](https://user-images.githubusercontent.com/54055206/96852314-93f13400-148b-11eb-93ca-5e0066275b08.png)

**Comment by MRayermannMSFT** [comment]
@v-limu I'm not able to repro this issue. Can you share:

- Did you access the container via: sign-in, attach with azure AD, attach with SAS URI, or attach with connection string?
- What access tier did you try to set the folder to?
- Are you able to reproduce this again?
- Can you take a video please?
- If you do repro, instead of taking a screenshot of the error dialog, please copy and paste the error message?

**Comment by v-limu** [comment]
Hi @MRayermannMSFT. This issue still reproduces in the build 20201023.5. Details show as below:

**Rero steps:**

1. Select one ADLS Gen2 blob container -> Create a new folder -> Open the folder -> Create a folder with blobs.
2. Right click the new folder -> Click ‘Change Access Tier…’ -> Select ‘Hot’ tier -> Apply.

**Actual:**
Show a failed activity log.
![blob-adls](https://user-images.githubusercontent.com/54055206/96947549-19b9c180-1516-11eb-8531-f32daa85dfc2.gif)


**More info:**

1. This issue reproduces for ADLS Gen2 blob container that is accessed via sign-in, attach with azure AD, attach with name & key.
2. This issue also reproduces when changing access tier to ‘Cool’ and ‘Archive’.
3. The error details show below:
[ErrorDetails.txt](https://github.com/microsoft/AzureStorageExplorer/files/5426794/ErrorDetails.txt)

**Comment by MRayermannMSFT** [comment]
Thank you for the additional help! I can reproduce this now. 👍

**Comment by MRayermannMSFT** [comment]
Fix merged into main.
