### ISSUE TITLE
Nothing happens after clicking 'Upload' button in the 'Upload Files' dialog with the tags feature is disabled

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3706]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20201022.3
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Previous release(1.15.1)

**Steps to reproduce:**

1. Expand one storage account (make sure the tags feature is disabled)-> Blob Containers.
2. Create a new blob container -> Click 'Upload -> Upload Files...'.
3. Selected files to the upload dialog -> Click 'Upload' button.
4. Check the result.

**Expect Experience:**
Succeed to upload the files.

**Actual Experience:**
Nothing happens.

**More Info:**
1. This issue also reproduces for one file share.
2. This issue also reproduces in the 'Upload Folder' dialog.
3. This issue doesn't reproduce for the storage account which the tags feature is enabled.

**Comment by JasonYeMSFT** [comment]
A fix has been merged.

**Comment by v-xianya** [comment]
This issue is fixed on build 20201023.5. So close it.
