### ISSUE TITLE
The file selected for the first time doesn't show in the 'Upload Files' dialog with the tags feature is disabled

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3707]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20201022.3
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Previous release(1.15.1)

**Steps to reproduce:**

1. Expand one storage account (make sure the tags feature is disabled)-> Blob Containers.
2. Create a new blob container -> Click 'Upload -> Upload Files...'.
3. Try to selected files in the upload dialog -> Check whether the selected files show or not.

**Expect Experience:**
The selected files show well in the upload dialog.

**Actual Experience:**
The selected files doesn't show in the upload dialog.
![file-upload](https://user-images.githubusercontent.com/54055206/96850250-2e9c4380-1489-11eb-9bfe-3fd6eddd3c88.gif)

**More Info:**
1. This issue only reproduces when the file selected for the first time.
2. This issue also reproduces in the 'Upload Folder' dialog.
3. This issue also reprodcues for one file share.
4. This issue doesn't reproduce for the storage account which the tags is enabled.

**Comment by JasonYeMSFT** [comment]
A fix has been merged.

**Comment by v-xianya** [comment]
This issue is fixed on build 20201023.5. So close it.
