### ISSUE TITLE
An extra 'Tags' shows in the 'upload Files' dialog for one new created blob container with the tags feature is disabled

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3710]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20201023.5
**Branch**: main
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**

1. Expand one storage account (**make sure the tags feature is disabled**)-> Blob Containers.
2. Create a new blob container -> Click 'Upload -> Upload Files...'.
3. Check whether the 'Tags' shows in the 'Upload Files' dialog or not.

**Expect Experience:**
 No 'Tags' shows in the 'Upload Files' dialog.

**Actual Experience:**
An extra 'Tags' shows in the 'Upload Files' dialog.
![extar](https://user-images.githubusercontent.com/54055206/96988930-91f4a700-1557-11eb-8e1e-c248e75421b0.gif).

**More Info:**

1. This issue also reproduces for one new cloned blob container.
2. This issue also reproduces in the 'Upload Folder' dialog.
3. This issue doesn't reproduce after manually refreshing the Blob Containers node.

**Comment by v-xianya** [comment]
This issue is fixed on build rel/1.16.0_20201030.5. so close it.
