### ISSUE TITLE
Azure Storage Explorer -- Get Subscriptions Failure Details

### ISSUE THREAD

**Issue by ShirleyVA** [microsoft/AzureStorageExplorer#3713]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:

**Comment by MRayermannMSFT** [comment]
@ShirleyVA can you please fill out the information in the template. Most importantly:
**Storage Explorer Version**: In which Storage Explorer version was the bug encountered?
**Build Number**: What is the build number (Help > About) 
**Platform/OS**: Linux Ubuntu? macOS High Sierra? Windows 10?
**Regression From**:  Was this working in a previous version? If so, which one?
**Any error messages you are seeing:

**Comment by ShirleyVA** [comment]
Thanks for contacting me. Our sys administrator has fixed my connection problem

**Comment by MRayermannMSFT** [comment]
@ShirleyVA that is great to hear. If by chance you know how your sys admin fixed it, feel free to let us know here. It may be of help to other people in the future. 🙂
