### ISSUE TITLE
unable to load Tables on  Storage Explorer

### ISSUE THREAD

**Issue by pluo2000** [microsoft/AzureStorageExplorer#3714]
Unable to retrieve child resources.

Details:
self signed certificate in certificate chain

**Comment by MRayermannMSFT** [comment]
@pluo2000 please see our troubleshooting guide for help with this issue:

https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C1804#error-self-signed-certificate-in-certificate-chain-and-similar-errors

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you're still having problems.
