### ISSUE TITLE
Fail to upload files to one blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3716]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20201027.2
**Branch**: main
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Previous build (20201023.5)

**Steps to reproduce:**
1. Expand the Subscription 'StorageExplorer' -> Storage Accounts -> Expand the storage account 'aytestissue'.
2. Select one blob container -> Upload one file to the blob container.
3. Check the result.

**Expect Experience:**
 Succeed to upload.

**Actual Experience:**
Fail to upload the blob.
![image](https://user-images.githubusercontent.com/41351993/97281352-5c61fd80-1878-11eb-9a7a-8cd62f514bf0.png)

**More Info:**
1. This issue also reproduces when trying to upload one folder.
2. This issue also reproduces for ADLS Gen2 blob containers.
3. This issue also reproduces for blob containers under one name & key attached storage account.
4. This issue doesn't reproduce for blob containers under one SAS attached storage account.

**Comment by v-limu** [comment]
Verified on build 20201029.1. This issue has been fixed. So close it.
