### ISSUE TITLE
Keep a consistent case for the property 'Etag' in the properties dialog between one blob and one file

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3717]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20201028.3
**Branch**: main
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**
1. Expand one storage account -> File Shares.
2. Create one file share -> Upload one file -> Check its properties.
3. Expand one storage account -> Blob Containers.
4. Create one blob container -> Upload one blob -> Check its properties.

**Expect Experience:**
Keep a consistent case for the property 'Etag'.

**Actual Experience:**
1. Show 'Etag' in the file's properties dialog.
2. Show 'ETag' in the blob's properties dialog.
![image](https://user-images.githubusercontent.com/41351993/97421993-24c28680-1948-11eb-83b7-df7e8cf2f029.png)

**More Info:**
1. Show 'Uri' in one file's properties dialog while show 'URL' in one blob's properties dialog.

**Comment by MRayermannMSFT** [comment]
I fixed this. :)
