### ISSUE TITLE
Timestamp query filter for Comos DB Table doesn't work 

### ISSUE THREAD

**Issue by andriysavin** [microsoft/AzureStorageExplorer#3718]
**Storage Explorer Version**: 1.15.1
**Build Number**: 20200902.9
**Platform/OS**:  Windows 10
**Architecture**: x64
**Regression From**:  N/A

## Bug Description ##
I have a Cosmos DB Table with some records. When I try to filter the records by the Timestamp column I alwas get 0 records regardles of timestamp filter settings. I tried the same functioinality at the Azure portal Data Eplorer, and it works correctly there.

## Steps to Reproduce ##
1. Have any Cosmos DB Table with some rows;
2. Open Entities in the tree view;
3. Click Query button;
4. Remove all existing query conditions, if any;
5. Add a condition which filters by Timestamp column. Choose value to compare which definitely includes some of your rows timestamps, e.g. "Last 365 days". (text representation: Timestamp ge datetime'2019-10-29T17:48:09.514Z');
6. Run the query.
  
![image](https://user-images.githubusercontent.com/12996633/97476656-5727b000-1957-11eb-9d55-fe0dc729aa04.png)

## Expected Experience ##
Rows with timestamps falling into the filter range are shown.
## Actual Experience ##
No rows are shown.

**Comment by southpolesteve** [comment]
The Cosmos team recently deprecated our integration with Azure Storage Explorer. [Here is the full deprecation notice from the 1.15.1 Storage Explorer release notes:](https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.15.1)

> The Azure Cosmos DB integration with Storage Explorer has been deprecated. Any existing functionality will not be removed for a minimum of one year from this release. Users should use the Azure Portal, the Azure Portal desktop app, or the standalone Cosmos Explorer instead – all of which contain many new features that aren’t currently supported in Storage Explorer. Additionally, the Azure Cosmos DB team has also open sourced the data explorer project and will be investing in their own desktop tooling at a later date. Please keep an eye on their repository for more information. 

Currently, we are not prioritizing new features or bug fixes for Cosmos in Azure Storage Explorer. If you the issue you are reporting also applies to the Azure Portal or https://cosmos.azure.com, please file an issue in [our open source Cosmos Explorer repo](https://github.com/Azure/cosmos-explorer)
