### ISSUE TITLE
Recall tab state between sessions

### ISSUE THREAD

**Issue by mjgabriel** [microsoft/AzureStorageExplorer#372]
Feature Request

Automatically recall tab state between sessions or someway to store the current state of open tabs so it can be manually loaded/recalled the next time storage explorer is spun up. If possible.

Thanks for considering.

**Comment by craxal** [comment]
As a workaround, you can add the resources with open tabs to Quick Access.

**Comment by mms-** [comment]
Would want any tab state such as query for a table saved as well. Basically this should be for Azure storage what Postman is for api dev.

**Comment by JasonYeMSFT** [comment]
Some basic support will be added in 1.25.0 for restoring opened tabs from the previous session. https://github.com/microsoft/AzureStorageExplorer/issues/1504

We are not supporting restoring table query results this time. If you would like to see additional state information being carried between sessions, please open a new feature request with more details about what you would like to see.
