### ISSUE TITLE
"Clone blob container" doesn't include directories in emulator blob containers

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#3720]
**Storage Explorer Version**: ^1.12.0
**Platform/OS**: macOS/Windows
**Regression From**:  Not sure

## Bug Description ##
As titled.

## Steps to Reproduce ##
1. Create an emulator blob container
2. Upload blobs a/b.txt, c.txt to it, producing "c.txt" and "a/" at the root level
3. Clone that container

## Expected Experience ##
The cloned container contains a/b.txt and c.txt.

## Actual Experience ##
It only contains c.txt.

**Comment by MRayermannMSFT** [comment]
Fixed in the merged statistics rewrite.

**Comment by v-xianya** [comment]
@MRayermannMSFT 
Verified this issue on build 20201209.5. Reproduce.
So we re-open it.

**Comment by MRayermannMSFT** [comment]
@v-xianya can you give more details to how you reproduced this? I was not and am still not able to.

**Comment by MRayermannMSFT** [comment]
Oh @v-xianya , this was just for the new folder statistics. Clone is still broken.

**Comment by v-xianya** [comment]
@MRayermannMSFT yes, Reproduce for clone action.

**Comment by MRayermannMSFT** [comment]
Oh ok. I'll rename the bug then and move it. :)

**Comment by MRayermannMSFT** [comment]
fix merged into main
