### ISSUE TITLE
No warning message shows when adding tags with the same key in the upload dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3721]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20201029.1
**Branch**: rel/1.16.0
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Select one blob container (make sure the 'Supports Tags' is True) -> Click 'Upload -> Upload Files'.
3. Add two tags with the same key -> Check the result.

**Expect Experience:**
Show a warning message saying that keys must be unique.

**Actual Experience:**
No warning message shows.
![image](https://user-images.githubusercontent.com/41351993/97537963-93601c80-19fa-11eb-98c7-68aad111ade1.png)

**More Info:**
The screenshot of the 'Edit Tags' dialog.
![image](https://user-images.githubusercontent.com/41351993/97537400-b938f180-19f9-11eb-862a-54f0f6957fe6.png)

**Comment by JasonYeMSFT** [comment]
I have merged the PR for validating duplicate keys.

**Comment by v-xianya** [comment]
Verified on build rel/1.16.0 20201103.2. Fixed.
