### ISSUE TITLE
The 'Edit Tags…' action of the blob is disabled for one cloned blob container with the 'Supports Tags' is 'True'

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3723]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20201029.1
**Branch**: main
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one storage account -> Blob Containers (make sure the 'Supports Tags' is True).
2. Select one blob container with blobs -> Right click the blob container -> Clone it with a new name.
3. Check the 'Edit Tags...' action for the blob in the cloned blob container.

**Expect Experience:**
The 'Edit Tags...' action is enabled.

**Actual Experience:**
The 'Edit Tags...' action is disabled.

**More Info:**
This issue doesn't reproduce after re-opening the cloned blob container.

**Comment by v-xianya** [comment]
This issue is fixed on build rel/1.16.0 20201030.5. so close it.
