### ISSUE TITLE
The property 'Support Tags' is 'Unknown' for one blob container under one SAS attached storage account without the 'Filter' permission

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3724]
**Storage Explorer Version:** 1.16.0-dev
**Build**: 20201029.1
**Branch**: main
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**
1. Select one storage account which supports tags -> Attach it via SAS with full permissions except the 'Filter' permission.
2. Expand the attached storage account -> Blob Containers.
3. Select one blob container -> Check the value of the property 'Supports Tags'.

**Expect Experience:**
The value is 'True'.

**Actual Experience:**
The value is 'Unknown'.

**More Info:**
This issue doesn't reproduce for the storage account which does not support tags. Details as below:

Steps:
1. Select one storage account which do not support tags -> Attach it via SAS with full permissions except the 'Filter' permission.
2. Expand the attached storage account -> Blob Containers.
3. Select one blob container -> Check the value of the property 'Supports Tags'.

Actual:
The value of the property is 'False'.

**Comment by JasonYeMSFT** [comment]
The property "Supports Tags" is supposed to show whether the service is available. Our detection logic attempts to filter by tags to see if the service returns error like "invalid header". The reason why we leave it as unknown is that it is still possible that the user has "t" permission or the permission maybe changed later such as from roles.

**Comment by v-xianya** [comment]
@JasonYeMSFT ok, got it.
