### ISSUE TITLE
[loc]  Assistance with translation of ErrorUninstallExtensionDoesntExist

### ISSUE THREAD

**Issue by cristianosuzuki77** [microsoft/AzureStorageExplorer#3725]
String Resource ID | 0; "ErrorUninstallExtensionDoesntExist"
-- | --
Source String | Failed to uninstall extension with ID %1$s No such extension is installed.
Filename | loc\en\src\Standalone\resources\ExtensionManager.json
Question | Source seems to be consising of two sentences, but there is no period in between. Can we translate as below? Failed to uninstall extension with ID %1$s. No such extension is installed.It would be better though if the source string is updated to contain the period. Either way works.

**Comment by cristianosuzuki77** [comment]
VCQ 325375

**Comment by MRayermannMSFT** [comment]
@cristianosuzuki77 this is a bug on our part. The period is supposed to be there. Thanks for catching this. We'll fix the english version. :)

**Comment by MRayermannMSFT** [comment]
I updated the resource to include a .
