### ISSUE TITLE
[Loc] Placeholder: Does the placeholder stand for the row number?

### ISSUE THREAD

**Issue by cristianosuzuki77** [microsoft/AzureStorageExplorer#3726]
String Resource ID | 0; "AriaLabelTagDelete"
-- | --
Source String | Delete tag entry row %1$d
Filename | loc\en\src\components\se-az-copy-extension\resources\UploadBlobsDlg.json
Question | Does the placeholder stand for the row number? We assumed so for now, please advise. Similar strings: Tag key row %1$d Tag value row %1$d 0; "AriaLabelTagKey" 0; "AriaLabelTagValue"

**Comment by cristianosuzuki77** [comment]
vcq 328650

**Comment by MRayermannMSFT** [comment]
Yes, it does refer to the row number.

**Comment by MRayermannMSFT** [comment]
@cristianosuzuki77 do you have any other questions regarding this resource?
