### ISSUE TITLE
Display 'undefined' instead of 'version id' in the group activity log of the promote version action

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3727]
**Storage Explorer Version:** 1.16.0
**Build**: 20201030.5
**Branch**: rel/1.16.0
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Regression From**: Previous build (20201029.1)

**Steps to reproduce:**
1. Select one storage account -> Enable blob versioning.
2. Expand the storage account -> Blob Containers.
3. Create a blob container -> Upload one blob -> Modify its metadata to create a version.
4. Switch to the versions view -> Promote the blob version.
5. Observe the activity log.

**Expect Experience:**
The activity log shows normal.
![image](https://user-images.githubusercontent.com/41351993/97677875-e951c480-1acd-11eb-869c-5f005d2bdf53.png)

**Actual Experience:**
Display 'undefined' instead of 'version id' in the activity log.
![image](https://user-images.githubusercontent.com/41351993/97677949-04bccf80-1ace-11eb-84af-1f6f9abe9dff.png)

**Comment by JasonYeMSFT** [comment]
I have merged the fix for this issue.

**Comment by v-xianya** [comment]
Verified on build rel/1.16.0 20201103.2. Fixed
