### ISSUE TITLE
The layout of the release notes shows unfriendly

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3728]
**Storage Explorer Version:** 1.16.0
**Build**: 20201030.5
**Branch**: rel/1.16.0
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**
1. Open Storage Explorer -> Go to 'Help -> View Release Notes'.
2. Observe the layout of the release notes.

**Expect Experience:**
The layout shows well.

**Actual Experience:**
 Two parts show unfriendly. 

The screenshots:
![image](https://user-images.githubusercontent.com/41351993/97680556-d640f380-1ad1-11eb-95e7-965b09f894a2.png)

![image](https://user-images.githubusercontent.com/41351993/97680738-24ee8d80-1ad2-11eb-95cc-9491fb90f03c.png)

**Comment by MRayermannMSFT** [comment]
Fixed the heading level, removed the sentence about regions.
