### ISSUE TITLE
Show inconsistent AzCopy version in 'Releases Notes' and 'About' dialog

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3729]
**Storage Explorer Version:** 1.16.0
**Build**: 20201030.5
**Branch**: rel/1.16.0
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Click 'Help -> View Releases Notes' -> Check the AzCopy version.
3. Click 'Help -> About' -> Check the AzCopy version.

**Expect Experience:**
Keep a consistent current AzCopy version.

**Actual Experience:**
Show inconsistent AzCopy version.

1. In Release Notes:
![image](https://user-images.githubusercontent.com/54055206/97683518-6469a980-1ad3-11eb-9fd3-6b90403883bc.png)
2. In 'About' dialog. 
![image](https://user-images.githubusercontent.com/54055206/97683545-66336d00-1ad3-11eb-8565-5759849d0259.png)

**Comment by JasonYeMSFT** [comment]
This is the private build we use for testing. We will be replacing it with a public release when we ship.

**Comment by v-limu** [comment]
Verified on build 20201107.1. This issue has been fixed. So close it.
![image](https://user-images.githubusercontent.com/54055206/98504237-772d6c80-2291-11eb-83d5-c83a8ac10da7.png)
