### ISSUE TITLE
Unable to retrieve authentication token

### ISSUE THREAD

**Issue by chadwillson** [microsoft/AzureStorageExplorer#3730]
**Storage Explorer Version**: Version: 1.15.1
**Build Number**: 20200902.2
**Platform/OS**: Windows
**Architecture**: x64
**Regression From**:  worked before

## Bug Description ##
Unable to retrieve child resources.

Details:
["Error:Unable to retrieve authentication token."]

## Steps to Reproduce ##
open application

## Expected Experience ##
able to connect to multiple storage accounts

## Actual Experience ##
not able to connect to personal azure account

## Additional Context ##
on vpn at work, having issues connecting to portal.azure.com which is persistent: 

you were identified as a customer using Azure Policy with Guest Configuration who may not have been able to see the latest compliance results.

**Comment by MRayermannMSFT** [comment]
Can you go to Settings -> Services -> Disks, uncheck the checkbox and then restart? That should unblock you (assuming you don't need to work with disks).

Also, please check the account panel for any accounts which are asking you to re-enter your credentials, and if there are any, then do so.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response
