### ISSUE TITLE
Log files need to have descriptive words in titles

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#3735]
For example, the log file with activities should have ActivityLog in the file name

**Comment by craxal** [comment]
To do this, we need to be able to:
- Create a Log module implementation that uses a custom file name. The current implementation already allows this.
- Allow customization in how SDK module implementations are created by the SDK loader. The current SDK loader creates SDK module instances the exact same way regardless of environment. This makes it very difficult to customize the log file name depending on the environment.
