### ISSUE TITLE
unable to retrieve child resource in version 1.15.1

### ISSUE THREAD

**Issue by dianweih73** [microsoft/AzureStorageExplorer#3736]
**Storage Explorer Version**: 1.15.1
**Build Number**: 
**Platform/OS**: windows 10 
**Architecture**:i86 
**Regression From**: First time use it

## Bug Description ##
When I click Blob containers trying to list all resources, I see error "unable to retrieve child resorces".
I used connection string to connect my storage account. It worked for a couple of hours. After I closed it and re-started explorers, I found the error. Not sure whether my connection string was expired or not.

## Steps to Reproduce ##
1. start storage explorer
2. click storage account
3. expand blob containers
4. loading is always there. 

## Expected Experience ##
I expected to see my folders

## Actual Experience ##
loading hung up

**Comment by MRayermannMSFT** [comment]
@dianweih73 was there any additional error info other than "unable to retrieve child resources"?

At what point did the error pop up? Like was it when it you expanded your Storage Account node or something else?

**Comment by dianweih73** [comment]
Hi Matt,

FetchError:request to https://***/&include=metadata&comp=list<https://fsidls0012prdftsmrt01.blob.core.windows.net/?sv=2019-12-12&ss=b&srt=sco&sp=rwlac&se=2022-11-03T00:01:48Z&st=2020-11-02T17:01:48Z&spr=https&sig=y5j7E6fwH9phv0otLunwp%2FfJV7w5i%2FGNgBqXkJ%2FVQKA%3D&include=metadata&comp=list> failed, reason: connect ETIMEDOUT 52.239.184.42:443"]


When I tried to expand the folders under blob containers. When I used SAS URI from local & attached --> storage account. When I used my company account, still the same error. With/Without proxy, the error was still there.

Best,
Dianwei

**Comment by alejjime** [comment]
Hi, I have the same error in the same situation, trying to expand blob containers from storage account. 
I attach the message below, it says failure because authorizations, but I have tried assigning all the auths I think my account needs and nothing works. 

Message when error: 

> Unable to retrieve child resources.
> 
> Details:
> ["RestError:﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.\nRequestId:6ea8db5d-f01e-008e-316d-b175af000000\nTime:2020-11-02T23:09:59.1694637Z</Message></Error>"]

**Comment by dianweih73** [comment]
Hi All,

We already figured out the issue.

  1.  Add SAS key at local & attached, storage account.
  2.  Set up proxy. Using login username and password.
Hope it helps.

Best,
Dianwei
