### ISSUE TITLE
The auth panel shows subscriptions, but does not let me select it and Apply (v1.2.0)

### ISSUE THREAD

**Issue by datarchitect** [microsoft/AzureStorageExplorer#374]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Windows 10 and Windows Server 2016
**Architecture**: ia32
**Regression From**: N/A

#### Steps to Reproduce: ####
1. Open Storage Explorer
2. Try signing in to Azure subscription

#### Expected Experience: ####
Storage explorer lets you select required subscriptions, apply and explore storage.

#### Actual Experience: ####
I get the below error. Explorer does show the name of all subscriptions I have, but does not let me click Apply and proceed.

Error Details.
 Subscriptions for the follwowing tenants could not be retrieved:
 Tenant Id: 22529389-206f-490d-b222-2c0ac87b3edf, Error: "AuthenticationNeededError"

**Comment by datarchitect** [comment]
No errors in event log.

**Comment by MRayermannMSFT** [comment]
@datarchitect are you still having this problem with the latest version of storage explorer, 1.12.0?

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. Please open a new issue if you still encounter any problem.
