### ISSUE TITLE
Unable to Open Azure storage explorer 

### ISSUE THREAD

**Issue by vamsikt** [microsoft/AzureStorageExplorer#3740]
Unable to retrieve child resources.

Details:
["Error:Hub Controller process exited prematurely with signal 'SIGABRT'."]

<img width="551" alt="Screen Shot 2020-11-02 at 11 01 46 PM" src="https://user-images.githubusercontent.com/9420290/97948720-62b41600-1d5f-11eb-9539-d955dc02cee9.png">

Version: 1.15.1
AzCopy Version: 10.6.0

Platform: macOS
Architecture: x64 
Build Number: 20200902.9 
Commit: 2e31227ac 
Support ID: 69c6a782-2bfd-dc3b-3d9d-e6b4e630ae46 

Copyright © 2020 Microsoft. All rights reserved.

**Comment by MRayermannMSFT** [comment]
Can you please do the following?


2. In Storage Explorer, go to Settings (gear on the left) -> Application -> Sign In -> check "Enable verbose authentication logging"
3. Close Storage Explorer
1. Delete ~/.ServiceHub/logs
4. Start Storage Explorer
5. Repro your issue
6. Zip up ~/.ServiceHub/logs and share the zip here. 

Thanks!

**Comment by vamsikt** [comment]
@MRayermannMSFT thanks for the reply, just to confirm is there any sensitive data in that logs (as I see there are a bunch of logging info)

**Comment by MRayermannMSFT** [comment]
@vamsikt the most common thing that you might want to redact from those logs is your email address. I don't think there are any passwords or auth tokens....like I'm 99% certain. If you're concerned and don't feel confident in redacting everything, you can put the zip in a public blob container/some other file sharing service and then email a link to:

sehelp at microsoft dot com

**Comment by vamsikt** [comment]
@MRayermannMSFT Doing clean reinstalling worked with out any issues.thanks!
