### ISSUE TITLE
The layout of the 'Undelete' dialog shows unfriendly for one blob

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3741]
**Storage Explorer Version:** 1.16.0
**Build**: 20201103.2
**Branch**: rel/1.16.0
**Platform/OS**: Windows 10
**Architecture**: ia32
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one Non-ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one folder to it.
3. Right click the folder -> Click 'Undelete -> Undelete Selected'.
4. Check the dialog.

**Expect Experience:**
The layout of the dialog shows friendly.

**Actual Experience:**
The layout of the dialog shows unfriendly.
![image](https://user-images.githubusercontent.com/54055206/97969011-63e65100-1dfa-11eb-8f55-7167fc58089d.png)

**More Info:**
This issue also reproduces in the 'Delete' dialog when the blob name is long enough.
![image](https://user-images.githubusercontent.com/54055206/97969174-a314a200-1dfa-11eb-9b3e-fc5f3a39cc7f.png)

**Comment by MRayermannMSFT** [comment]
Going to fix the first problem, but for the delete dialog, that's basically by design. The message box dialog will show a scrollbar when the message is too big, and therefore the user will need to resize the dialog.

**Comment by v-limu** [comment]
Hi @MRayermannMSFT Got it. Thanks for your updates!

**Comment by v-limu** [comment]
Verifie on build 20201116.2. This issue has been fixed. So close it.
![image](https://user-images.githubusercontent.com/54055206/99227634-7911a580-2826-11eb-8664-848a7efc1329.png)
