### ISSUE TITLE
Feature request: Option to play a sound at the end of a transfer

### ISSUE THREAD

**Issue by NathanS-Microsoft** [microsoft/AzureStorageExplorer#3742]
Some transfers are large (minutes). I'd like the ability for the system to play a sound when a transfer completes or blocks so I can minimize and go on to other things.

**Comment by jinglouMSFT** [comment]
That's an interesting idea.  We probably need to do more than just a sound to be accessibility compliant however.  Good idea. We'll think about how we can do this.  Thanks.

**Comment by NathanS-Microsoft** [comment]
Blink a taskbar icon or minimized task.

**Comment by MRayermannMSFT** [comment]
> Blink a taskbar icon or minimized task.

This is very possible, I've seen the Electron docs before on how to do it. Thanks for the feature request!

**Comment by MRayermannMSFT** [comment]
This has been merged into main for 1.20! We will flash in the task bar/bounce in the dock at the end of pastes/uploads/downloads if the main window is not currently focused.
