### ISSUE TITLE
It would be better to forbid renaming one ADLS Gen2 blob with a name include a slash

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3744]
**Storage Explorer Version:** 1.16.0
**Build**: 20201103.3
**Branch**: rel/1.16.0
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ MacOS Catalina
**Architecture**: ia32/ x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Rename the blob with a name include a slash -> Check the result.

**Expect Experience:**
It would be better to forbid renaming one ADLS Gen2 blob with a name include a slash.

**Actual Experience:**
No warning message shows in the rename dialog and show a failed activity log after renaming.
![image](https://user-images.githubusercontent.com/41351993/98095310-5b0e8180-1ec5-11eb-8837-5010c8c94b54.png)

![image](https://user-images.githubusercontent.com/41351993/98095044-0a972400-1ec5-11eb-918a-d76a2d174da6.png)

Error details:
`
"name": "Error",
  "message": "The parent directory of the destination path does not exist.\nRequestId:4ab5f59c-d01f-008b-5a5a-b20df5000000\nTime:2020-11-04T03:27:44.0955959Z",
`

**More Info:**

The screenshot for one regular blob.
![image](https://user-images.githubusercontent.com/41351993/98095292-55b13700-1ec5-11eb-924f-958eab5e618f.png)

**Comment by MRayermannMSFT** [comment]
Similar to other bugs in 1.17

**Comment by MRayermannMSFT** [comment]
fix merged into main
