### ISSUE TITLE
AzureStorageExplorer Error

### ISSUE THREAD

**Issue by rokanshakil** [microsoft/AzureStorageExplorer#3745]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:

**Comment by JasonYeMSFT** [comment]
@rokanshakil Could you fill the bug template to tell us what exactly error you encountered?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
