### ISSUE TITLE
How to change directories?

### ISSUE THREAD

**Issue by stevenhurwitt** [microsoft/AzureStorageExplorer#3746]
**Storage Explorer Version**: 1.14.2
**Build Number**: 20200715.2 
**Platform/OS**: macOS High Sierra

## Bug Description ##
I can authenticate with Azure but cannot switch directories after that.

## Steps to Reproduce ##
1. Azure authentication
2. Unable to change directory

**Comment by MRayermannMSFT** [comment]
@stevenhurwitt as of today, by default you are signed into all directories. There is no directory switching. Does that make sense?

**Comment by stevenhurwitt** [comment]
yeah i'll have to try it out now, awesome!
