### ISSUE TITLE
Double converted to int

### ISSUE THREAD

**Issue by rasmuschristensen** [microsoft/AzureStorageExplorer#375]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Windows
**Architecture**: 1a32
**Regression From**: -

#### Steps to Reproduce: ####
Create an object to persist
Make one property a double and set it to 0.0 when saving.
Check storage explorer, the number is now 0.
Loading the object from code also results in 0, not 0.0
If edited with storage explorer, the same thing happens.

It's a bit like this old issue
https://github.com/Studio3T/robomongo/issues/622

#### Expected Experience: ####
I would expect 0.0 to be the value saved into cosmosdb and retrived again. It works if I save something like 0.1

#### Actual Experience: ####
The value is saved as 0

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
