### ISSUE TITLE
No traffic shows in the Fiddler when executing 'Column Options' for one table with entities 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3750]
**Storage Explorer Version:** 1.16.0
**Build**: 20201105.3
**Branch**: rel/1.16.0
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Click 'Edit -> Configure Proxy' -> Select 'Use app proxy settings' -> Set 'http_proxy=http://localhost:8888'.
3. Restart Storage Explorer.
4. Expand one storage account -> Tables -> Create a new table -> Add an entity.
5. Click 'Column Options' in the toolbar > Click 'OK'.
6. Check whether the traffic shows in the Fiddler.

**Expect Experience:**
 The traffic shows in the Fiddler.

**Actual Experience:**
No traffic shows in the Fiddler.
![tables](https://user-images.githubusercontent.com/54055206/98233508-1b659980-1f9a-11eb-9038-bd2b0d6dd203.gif)

**More Info:**
This issue doesn't reproduce for one table without entity.
![empty-table](https://user-images.githubusercontent.com/54055206/98233494-17d21280-1f9a-11eb-90e1-1186165f7629.gif)

**Comment by craxal** [comment]
By design. The Columns Options operation doesn't make any network requests, so you won't see anything in Fiddler. I suspect you're seeing a separate network request to retrieve entities when no entities are visible, which is also expected.
