### ISSUE TITLE
CosmosDB Stored Procedure Tab will not execute without partition key

### ISSUE THREAD

**Issue by acrov** [microsoft/AzureStorageExplorer#3752]
**Storage Explorer Version**: 1.15.1
**Build Number**: 20200902.9
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  No

## Bug Description ##
In the CosmosDB Stored Procedure Tab entering a partition key is mandatory and the procedure cannot be executed without one.  This makes it impossible to run cross partition queries and IMHO is not correct as the partition key should allow null. The web tool Microsoft Cosmos DB Explorer does not have this unnecessary restriction.

## Steps to Reproduce ##
1. Create a new stored procedure and open it.
2. Try to execute it without completing the red-outlined partition key input box.

## Expected Experience ##
Entering a partition key is optional

## Actual Experience ##

![image](https://user-images.githubusercontent.com/49073938/98260286-0f1e1400-1f7b-11eb-840d-cf92555219d4.png)

**Comment by southpolesteve** [comment]
This is expected. Stored procedures require a partition key and do in the portal too. https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-write-stored-procedures-triggers-udfs

> For partitioned containers, when executing a stored procedure, a partition key value must be provided in the request options. Stored procedures are always scoped to a partition key. Items that have a different partition key value will not be visible to the stored procedure. This also applied to triggers as well.

**Comment by acrov** [comment]
Apologies for not realising this.  I am just getting started and the local cosmos emulator web interface does allow this.  Sorry for wasting your time.
