### ISSUE TITLE
not able to get into blob storage

### ISSUE THREAD

**Issue by amtsha09** [microsoft/AzureStorageExplorer#3753]
Not able to get into blob storage.

<img width="203" alt="Screen Shot 2020-11-05 at 12 51 55 PM" src="https://user-images.githubusercontent.com/26030918/98283815-d0ca2a00-1f65-11eb-94b5-0d061347313b.png">

Unable to retrieve child resources.

Details:
["RestError:﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.\nRequestId:b0ea28e7-601e-0084-4ca4-b3cb83000000\nTime:2020-11-05T18:49:24.0149811Z</Message></Error>"]

Macbook Pro - version 10.15.7 (19H2)

Azure Storage Explorer
Version: 1.15.1
AzCopy Version: 10.6.0

Platform: macOS
Architecture: x64 
Build Number: 20200902.9

**Comment by jinglouMSFT** [comment]
The error indicated that you might not have access to the blob container. How do connect to the source? Sign-in? Attach?  Is this working against an emulator?

**Comment by amtsha09** [comment]
@jinglouMSFT  
No, it is not the authentication issue.
I log-in with same azure account into windows storage explorer and i can access everything there.

**Comment by MRayermannMSFT** [comment]
@amtsha09 is it possible your storage has a firewall/network restrictions that make it not possible for you to access the account from the network your mac machine is on?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having issues, please either reopen this issue or open a new issue.
