### ISSUE TITLE
Search Function

### ISSUE THREAD

**Issue by marshgm** [microsoft/AzureStorageExplorer#3757]
Search Bar to search any key word. Not the exact string.

**Comment by MRayermannMSFT** [comment]
@marshgm, what search feature are you referrring to? Blobs, file shares, gen2, tree view, something else?

**Comment by alexcui2010** [comment]
Is your feature request related to a problem? 
Yes, Azure Storage explorer can not search blob file by name with wildcard . Now it only have prefix search function.

Describe the solution you'd like A clear and concise description of what you want to happen.
In Azure Storage explorer search function, we can use blob list function to list all the object to local cache and then filter it locally.
Some third party vendor had this implementation. And it is a reasonable customer requirement as if customer back up file with sub folder to blob. They need to have a file system like tool to locate their by file name search.
*Blob index search is a choice so far as it has azure end configuration . And the search wildcard is not similiar to linux or windows. 

Describe alternatives you've considered A clear and concise description of any alternative solutions or features you've considered.
I do have some reference sample for you . You can leave me message and I will give you my microsoft mail contact for detail discussion.
Additional context Add any other context or screenshots about the feature request here.
So far no.

**Comment by MRayermannMSFT** [comment]
@alexcui2010 what 3rd party vendor provides the functionality you are looking for?

In general the reason we do not have wildcard search is because the APIs do not support it.

**Comment by MRayermannMSFT** [comment]
Closing this issue due to lack of followup by alexcui2010. As explained previously, we limit our search offerings to what the storage APIs provide. If you know of a different product with a more robust search, please let us know, and we can evaluate further development of our search features. Thanks!
