### ISSUE TITLE
Enable grouping storages in Storage Accounts tree

### ISSUE THREAD

**Issue by lu2Github** [microsoft/AzureStorageExplorer#3759]
**We have a lot of storages**
We have a lot of subsystems storages with DEV TEST PROD suffix.
Some storages have different names. It is confusing to find related storages.

**Enable grouping storages**
It should be nice to enable grouping storages to group

**subsystem1 (group)**

- storage account DEV
- storage account TEST
- storage account PROD
- ...

**Comment by MRayermannMSFT** [comment]
Duplicate of #2952
