### ISSUE TITLE
Add query tab to Cosmos DB MongoDB API

### ISSUE THREAD

**Issue by pavlea** [microsoft/AzureStorageExplorer#376]
AzureStorageExplorer app is semi-operational on Mac. I cannot query cosmos DB data. I'm using MongoDB API. That's very bad because I have a lot of data and cannot just scroll infinitely to find what I need.

**Comment by craxal** [comment]
@pavlea Please use the following format for filing new issues. We can't properly investigate your issue without this information.

```
**Storage Explorer Version**: <!-- Enter the Storage Explorer version in which you encountered your issue. -->
**Platform/OS Version**: <!-- Enter the OS and version (see About dialog). -->
**Architecture**: <!-- Enter the architecture of the app (see About dialog). -->
**Regression From**: <!-- Was this working on a previous version? If so, which one? -->

#### Steps to Reproduce: ####
1. <!-- Describe the steps necessary to reproduce your issue. -->
2. <!-- Be as detailed as you can. -->

#### Expected Experience: ####
<!-- Describe the outcome you expect when performing the above steps. -->

#### Actual Experience: ####
<!-- Describe the outcome that actually occurs when performing the above steps. -->
```

**Comment by ziyel** [comment]
@pavlea Thanks for the feedback.
Adding the query tab for Mongo API is already in our plan.

**Comment by craxal** [comment]
@ziyel Do you have an existing bug or feature item you can reference here?

**Comment by pavlea** [comment]
Ok great to hear it's in your plan already, it would be great to have it, so I can throw Mongo client away!
Tnx for info, don't have any existing bugs.

**Comment by ziyel** [comment]
@craxal We have not traced this feature item in Github for now.
We can use this issue as the feature item.

**Comment by jinglouMSFT** [comment]
CosmosDB have been removed from Storage Explorer.
