### ISSUE TITLE
Enhanced support for copying and pasting file paths from user interface

### ISSUE THREAD

**Issue by jasonhorner** [microsoft/AzureStorageExplorer#3762]
As a user I often need to quickly get file and folder path information from storage explorer this is more difficult than it needs to be and not intuitive. by clicking inside the dialog and choosing CTRL-A you can grab the path.

I'd like the Properties U/I to show a copy icon similar to the design in azure portal
![image](https://user-images.githubusercontent.com/7981510/98614165-1748bd00-22b5-11eb-8f69-d36b69f25ff9.png)

This should be added to the properties dialog in azure storage explorer:
![image](https://user-images.githubusercontent.com/7981510/98614475-bd94c280-22b5-11eb-88d7-a925b4f4be05.png)

Ideally the current right click URL option would be extended to support the copying of just the file name in additional to the fullpath.

![image](https://user-images.githubusercontent.com/7981510/98614668-2714d100-22b6-11eb-8342-0323b83c7037.png)

**Comment by JasonYeMSFT** [comment]
@jasonhorner Thanks for asking. We will put this in our backlog and figure out the time to make it happen.

**Comment by MRayermannMSFT** [comment]
@jasonhorner with regards to additional actions in the context menu, which of these do you want more (or do you want them the same):
- Copy path (includes the name)
- Copy name 
And could you explain your reasoning. Thanks!

**Comment by jasonhorner** [comment]
Hmm, I think that  full url would be the most helpful but don't have a strong rationale for why
I guess it easiest to remove the missing parts from the other pieces..

**Comment by MRayermannMSFT** [comment]
> Hmm, I think that full url would be the most helpful but don't have a strong rationale for why

But we already have copying the full URL in the context menu....? I'm trying to ask which of the things you proposed here:

> Ideally the current right click URL option would be extended to support the copying of **just the file name** in additional to **the fullpath**.

Is more important to you/if they are the same importance.

**Comment by jasonhorner** [comment]
Sorry for the confusion.. for the rightclick dialog a relative url from container would be best... note the primary scenario is to add the copy icons to the property dialog as shown on the screenshot... if I recall correctly the issue i have with the current copy paste full irl is that it come out url encoded which isn't useful for my typical use cases whic is copy and pasting into scripts hope this helps

**Comment by MRayermannMSFT** [comment]
>  if I recall correctly the issue i have with the current copy paste full irl is that it come out url encoded which isn't useful for my typical use cases whic is copy and pasting into scripts hope this helps

Ahhhhh interesting! We actually have users where not giving an encoded URL would **break** their typical use cases. 🙃

So are your scripts using URLs or paths?

**Comment by MRayermannMSFT** [comment]
@jasonhorner one final question: any preference on paths starting or not starting with a `/`? For example if you do "copy path" on this blob:
![image](https://user-images.githubusercontent.com/21112697/118736728-21192300-b7f8-11eb-95f1-1e1baa89be9c.png)
Which of these do you expect:
- `/New Folder/New Folder/tslint.json`
- `New Folder/New Folder/tslint.json`

**Comment by jasonhorner** [comment]
the second one seems most flexible but either would be acceptable

**Comment by MRayermannMSFT** [comment]
@jasonhorner cool, I've added the "Copy Path" action to blobs, gen2 blobs, and file shares.
![image](https://user-images.githubusercontent.com/21112697/119177571-58b6e380-ba21-11eb-9ae7-0feaa86b37b4.png)

For now though we're going to skip out on the copy button in the properties dialog. If we hear more feedback from other users about wanting that for other properties then we'll revisit that. It seems like for getting blob paths, this action will let you get those very quickly now.

Also, just incase you didn't know, both "Copy URL" and "Copy Path" can be used on multiple things once! Maybe that knowledge will be helpful to you too. :)

Finally, if you're willing, would you be up for telling me more about the "scripts" that you use these paths in? I'm interested in knowing more about how you integrate Storage Explorer into your workflows, and if it'd be possible for us to give you ways to improve that integration. If you're interested, I can let you know how to contact me. Thanks!

**Comment by jasonhorner** [comment]
Awesome thanks.. I look forward to use this I can put together a quick sample workflow. There are probably better ways to do what I'm doing but the use case for for adhoc / exploratory development. primarily in Azure Synapse. Really appreciate your work on this

**Comment by jasonhorner** [comment]
@MRayermannMSFT  sorry to bring this one back from the dead but it looks like the copy provides the blob url if an account has HNS enabled it should provide the abfss path:

![image](https://user-images.githubusercontent.com/7981510/172917231-6ba526a7-1431-4ea8-b7cc-c5950c9c373b.png)

https://XXXX.blob.core.windows.net/dls/demo/GL00201.snappy.parquet

should be 

https://XXXX.dfs.core.windows.net/dls/demo/GL00201.snappy.parquet


this would allow me to directly paste into scripts within SSMS(and other tools or scripts that rely on a full url):
![image](https://user-images.githubusercontent.com/7981510/172918566-ac5629c4-4777-42fd-afc4-a82613720efb.png)

this also related to : https://github.com/microsoft/AzureStorageExplorer/issues/3056

**Comment by JasonYeMSFT** [comment]
@jasonhorner Could you open a separate issue as a feature request? We do have lots of users who don't care about the dfs url of the blobs so we are going to add that, it's going to be on top of what we have instead of replacing it.

**Comment by balaupp** [comment]
> @MRayermannMSFT sorry to bring this one back from the dead but it looks like the copy provides the blob url if an account has HNS enabled it should provide the abfss path:
> 
> ![image](https://user-images.githubusercontent.com/7981510/172917231-6ba526a7-1431-4ea8-b7cc-c5950c9c373b.png)
> 
> https://XXXX.blob.core.windows.net/dls/demo/GL00201.snappy.parquet
> 
> should be
> 
> https://XXXX.dfs.core.windows.net/dls/demo/GL00201.snappy.parquet
> 
> this would allow me to directly paste into scripts within SSMS(and other tools or scripts that rely on a full url): ![image](https://user-images.githubusercontent.com/7981510/172918566-ac5629c4-4777-42fd-afc4-a82613720efb.png)
> 
> this also related to : #3056

It looks like it only provides the blob url with https and not abfss path. When you code in pyspark or scala, it becomes very important
