### ISSUE TITLE
Storage is running but not showing the dialog on Catalina 10.15.7 (19H15)

### ISSUE THREAD

**Issue by mmohl** [microsoft/AzureStorageExplorer#3763]
Hi, I cannot see the dialog explorer but it running on the process.

**Comment by JasonYeMSFT** [comment]
Could you try a clean re-install?

For macOS, you should:
- delete the .app from the Applications folder
- re-download from https://storageexplorer.com
- unzip
- drag and drop into the Applications folder

We have seen this kind issue when for some reason the window size/position pair values are corrupted and they turns out to be out of screen. If a clean re-install doesn't solve the problem, then something else is wrong. It may be something special to the new OS X system.

Thanks.

**Comment by JasonYeMSFT** [comment]
There is someone who encountered similar issue due to Storage Explorer window being shrunk.
https://github.com/microsoft/AzureStorageExplorer/issues/3086

**Comment by tux2323** [comment]
I had a similar issue on my Mac, what I did to solve the problem:

1. Delete the app from the Applications folder 
2. re-download from <https://storageexplorer.com>
3. Delete existing settings `rm -Rf ~/Library/ApplicationSupport/StorageExplorer` and `rm -Rf ~/Library/Preferences/com.microsoft.StorageExplorer.plist`
4. Unzip the latest app and drag & drop the app into the Applications folder
5. Start the app and the storage explorer window is displayed!

**Comment by craxal** [comment]
@mmohl @tux2323 Do you use multiple monitors?

Next time this happens, can you share the contents of your appState.json file? You should find it in ~/Library/ApplicationSupport/StorageExplorer. We use Electron's `screen.getDisplayMatching(rect)` function and do some math to make sure the size and position of the app window stays within the bounds of whichever display it was on last. As @JasonYang-MSFT mentioned, it's possible the math could have been thrown off if the values in appState.json were corrupted. This is why deleting appState.json would fix the problem.

**Comment by mmohl** [comment]
> I had a similar issue on my Mac, what I did to solve the problem:
> 
> 1. Delete the app from the Applications folder
> 2. re-download from https://storageexplorer.com
> 3. Delete existing settings `rm -Rf ~/Library/ApplicationSupport/StorageExplorer` and `rm -Rf ~/Library/Preferences/com.microsoft.StorageExplorer.plist`
> 4. Unzip the latest app and drag & drop the app into the Applications folder
> 5. Start the app and the storage explorer window is displayed!

Sorry for the slow reply, this is working and it really helps me a lot. Thank you so much

**Comment by mmohl** [comment]
> @mmohl @tux2323 Do you use multiple monitors?
> 
> Next time this happens, can you share the contents of your appState.json file? You should find it in ~/Library/ApplicationSupport/StorageExplorer. We use Electron's `screen.getDisplayMatching(rect)` function and do some math to make sure the size and position of the app window stays within the bounds of whichever display it was on last. As @JasonYang-MSFT mentioned, it's possible the math could have been thrown off if the values in appState.json were corrupted. This is why deleting appState.json would fix the problem.

Yes, next time I will put the log also. Thanks for the response. I think I could close this.
