### ISSUE TITLE
无法检索子资源。

### ISSUE THREAD

**Issue by liangrui-online** [microsoft/AzureStorageExplorer#3764]
无法检索子资源。

详细信息:
["RestError:request to https://lins.blob.core.windows.net/?include=metadata&comp=list failed, reason: getaddrinfo ENOTFOUND lins.blob.core.windows.net"]

**Comment by JasonYeMSFT** [comment]
Does your storage account have firewall enabled or private link enabled? This error usually occurs when the dns name cannot be resolved.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having issues, please either reopen this issue or open a new issue.
