### ISSUE TITLE
Show traffic for some operations after switching the proxy from 'Use app proxy settings' to 'Do not use proxy'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3768]
**Storage Explorer Version**: 1.16.0
**Build Number**: 20201111.5
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Regression From**:  Not a regression

## Bug Description ##
When switching the proxy setting from ‘Use app proxy settings’ to ‘Do not use proxy’, show traffic for some actions.

## Steps to Reproduce ##
1.	Launch Fiddler.
2.	Launch Storage Explorer, and configure proxy to use localhost:8888.
3.	Open a file share -> Create a new folder.
4.	Observe traffic in Fiddler.
5.	Switch the proxy setting to 'Do not use proxy'.
6.	Open the file share -> Create a new folder.
7.	Observe traffic in Fiddler.

## Expected Experience ##
No traffic in Fiddler.

## Actual Experience ##
Show traffic in Fiddler.

## Additional Context ##
This issue also reproduces for the below scenarios:

- [x] ADLS Gen2: All actions except action ‘Manage Access’.
- [x] Blobs: Actions except ‘Get Shared Access Signature/ Manage Access Policies/ Download/ Open’.
- [x] Files: Actions except ‘Get Shared Access Signature/ Create Snapshot/ View Snapshot/ Connect VM/ Properties/ Manage Access Policies/ Download/ Open’.
- [x] Queues: All actions.
- [x] Tables: All actions.
- [x] Managed Disks: All actions.

**Comment by JasonYeMSFT** [comment]
@v-xianya I have merged a fix for this issue. Could you please help verify it?

**Comment by v-xianya** [comment]
@JasonYeMSFT 
Verified this issue on build main/20201201.3.
This issue reproduces against the **table service's actions** (Like: Create a table/ Generate SAS/ Add to Quick Access/ Refresh/ Add or Delete entities/ Execute Query etc.)
![tableproxy](https://user-images.githubusercontent.com/41351993/100711883-e0b21e00-33ec-11eb-87f9-3f6c2935f381.gif)

**Comment by JasonYeMSFT** [comment]
I found why table is not taking proxy updates.

**Comment by v-xianya** [comment]
Verified this issue on build main/20201203.3. Fixed.

**Comment by JasonYeMSFT** [comment]
Another fix has been merged for Table. I actually also fixed it for the ADLS Gen1 folder stats command.
