### ISSUE TITLE
Linux authentication failed or no subscription list

### ISSUE THREAD

**Issue by vtslab** [microsoft/AzureStorageExplorer#377]
**Storage Explorer Version**: 1.2
**Platform/OS Version**: Ubuntu 17.10 
**Architecture**:AMD64
**Regression From**: -

#### Steps to Reproduce: ####
On an 'new' system
Installed core .net 2.1 by https://www.microsoft.com/net/download/linux-package-manager/ubuntu17-10/runtime-2.1.0
Downloaded AzureStorageExplorer from: https://go.microsoft.com/fwlink/?LinkId=722418
unzipped
run: ./StorageExplorer

#### Expected Experience: ####
After adding azure account I expect to see it

#### Actual Experience: ####
ASE starts. A popup asks to connect to azure storage
I choose 'Add azure account'
Azure environment ' azure'
choose 'sign in'
I enter account name
I choose work/school account
I enter password
'waiting for authentication' shows for about a minute, then closes
ASE now only shows account 'local and attached' and NOT my azure account
![ase_loclaaccountonly](https://user-images.githubusercontent.com/6702316/42246376-a2888d58-7f1c-11e8-963d-27a7a5fcaea3.png)

No error message.
The output of the terminal:
$ ./StorageExplorer
Received message 'get-dialog-result'
Received message 'dialog-ready'
Received message 'dialog-execute-operation'
Received message 'dialog-execute-operation'
Received message 'did-execute-operation'
Received message 'did-execute-operation'
Received message 'dialog-execute-operation'
Received message 'did-execute-operation'
Received message 'dialog-did-init'
Received message 'dialog-execute-operation'
Received message 'did-execute-operation'
Received message 'dialog-execute-operation'
Received message 'did-execute-operation'
Received message 'did-get-dialog-result'
Received message 'closed'

I think authentication failed because the waiting for authentication window showed for about a minute. 
Yes, my credentials are OK. I checked on a Windows PC with ASE :)
With FireFox logging in portal.azure.com also works fine.

**Comment by lmaisons** [comment]
I am on pure Arch, I see the same symptoms too, starting with Storage Explorer 1.0.0.

Version 0.9.6 does not have this problem.

This change in behaviour correlates with changes to how Storage Explorer stores credentials, with things now going through a central credential store [gnome-keyring in my case], that used to be managed internally.  My suspicion (though I don't have strong evidence) is that these are causally connected.

**Comment by MRayermannMSFT** [comment]
Hey @roberthawdon , more info is not needed at this point, so I'll remove the tag, and apologies for not getting to y'all.

Long term, we hope to solve Linux dependency issues by switching to [Snapcrafts](https://snapcraft.io/). Short term, we can help you try and figure out what's going on, but due to time limitations, our focus will be on making sure we work with Ubuntu. Feel free to join in on the below troubleshooting steps though, and I'll do my best to answer questions.

Can y'all do the following for me?

1. Open dev tools (f12)
2. Use ctrl+p to open IdentityUserAccountsManager.js
3. Set a breakpoint (by clicking on the line numbers on the left) on lines 176 and 178
4. Try to sign in
5. Line 176 should get hit
6. Click continue (blue arrow at top right of the dev tools, or F8)
7. Line 178 should get it (I wouldn't be surprised if it isn't hit though...)
8. If it is hit, then click step over (arrow going over a dot at top right of the dev tools, or F10)
9. If you're suddenly taken to what looks like error handling code, mouse hover over different variables looking for any sort of error messages or stack traces you can send us. If you instead just happily continue to line 179, then mouse over the authResult object and let us know what is inside of it.

I'll try to spin up a Ubuntu 17.10 machine later this week and see if I can repro locally.

**Comment by bacongobbler** [comment]
Hey @MRayermannMSFT, thank you SO MUCH for the in-depth debugging instructions. With your instructions, I was able to reproduce and capture the stack trace. Line 178 was hit after I authenticated, and after stepping through here's what I got:

The stack trace was triggered on line 133 of tslib.js:

```
    op = body.call(thisArg, _);
} catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
```

The value of `op` was `(2) [1, TypeError: Cannot read property 'Account' of null
    at ElectronAadAccountProviderClient.<anonymous…]`

And here's the stack trace:

> TypeError: Cannot read property 'Account' of null at ElectronAadAccountProviderClient.<anonymous> (/home/bacongobbler/Downloads/storage-explorer/resources/app/node_modules/identity-client/dist/AadAccountProviderClient.js:140:31) at Generator.next (<anonymous>) at fulfilled (/home/bacongobbler/Downloads/storage-explorer/resources/app/node_modules/identity-client/dist/AadAccountProviderClient.js:7:58) at ZoneDelegate.invoke (/home/bacongobbler/Downloads/storage-explorer/resources/app/node_modules/zone.js/dist/zone-node.js:242:26) at Zone.run (/home/bacongobbler/Downloads/storage-explorer/resources/app/node_modules/zone.js/dist/zone-node.js:113:43) at /home/bacongobbler/Downloads/storage-explorer/resources/app/node_modules/zone.js/dist/zone-node.js:535:57 at ZoneDelegate.invokeTask (/home/bacongobbler/Downloads/storage-explorer/resources/app/node_modules/zone.js/dist/zone-node.js:275:35) at Zone.runTask (/home/bacongobbler/Downloads/storage-explorer/resources/app/node_modules/zone.js/dist/zone-node.js:151:47) at drainMicroTaskQueue (/home/bacongobbler/Downloads/storage-explorer/resources/app/node_modules/zone.js/dist/zone-node.js:433:35) at ZoneTask.invoke (/home/bacongobbler/Downloads/storage-explorer/resources/app/node_modules/zone.js/dist/zone-node.js:349:25) at args.(anonymous function) (/home/bacongobbler/Downloads/storage-explorer/resources/app/node_modules/zone.js/dist/zone-node.js:1497:25) at _combinedTickCallback (internal/process/next_tick.js:131:7) at process._tickCallback (internal/process/next_tick.js:180:9)

Let me know if you need further information. I'll see if I can do some digging myself and hopefully submit a patch for this :)

**Comment by rnsc** [comment]
I have the same exact error on a 18.04 install (same js, same line).
This should really gets addressed because it has been going on for quite some time now.

**Comment by markoschnecke** [comment]
Same here. Running Manjaro and having the error in the same lib in the same line. Even a workaround would be greatly appreciated.

**Comment by ephimee** [comment]
I have the same issue. I'm on 16.04 using 1.5.0 but when I add the breakpoints, I cannot click the blue arrow unless I close the popup window. When I open F12 in the popup window, I do not have IdentityUserAccountsManager.js listed.
It does stop at the first breakpoint, but if I close the popup window, the login is aborted.
I also tried deleting ~/.IdentityService/ but that did not work.

**Comment by rnsc** [comment]
Is anyone actively looking into this? Ubuntu 18.04 has been out for a while now and there's no solution.
If you only have 2 storage accounts, then, of course it's easy to add them individually, but when you have more than a hundred, it's just impossible.

**Comment by BzSpi** [comment]
I have issue on Ubuntu 18.10 after an OS reinstall.
However, this was working fine before the OS reinstall (still Ubuntu 18.10 with Storage Explorer 1.6.X).
So, there should be a way to have it working.

**Comment by jamietelford** [comment]
Same error in Debian Stretch

**Comment by markoschnecke** [comment]
@MRayermannMSFT did you have the chance to find a solution? Or do you need more information?

**Comment by MRayermannMSFT** [comment]
This issue is fairly old at this point. If anyone is still having issues with the latest version of Storage Explorer, please open up a new issue with your details. Thanks.
