### ISSUE TITLE
Azure AD copy fails to download

### ISSUE THREAD

**Issue by kfroe** [microsoft/AzureStorageExplorer#3772]
trying to download from 
https://devicesamd.dfs.core.windows.net/orpheusengagement/Users/MikeG/MEMORY_VR_2.198.0_0x3b.zip

details:
{
  "message": "\"UnexpectedQuit\""
}

**Comment by JasonYeMSFT** [comment]
@kfroe Could you copy the azcopy command and try it with the AzCopy cmd tool and send us the output + the log? You can get AzCopy cmd tool [here](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10).

When you run the azcopy command using the cmd tool, please add one argument --output-type=json at the end to help us troubleshoot. We internally rely on the json output to determine the job status when it finishes.

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. If you are still having issue, please open a new one instead.
