### ISSUE TITLE
Unable to retrieve child resources.

### ISSUE THREAD

**Issue by shary-sharath** [microsoft/AzureStorageExplorer#3781]
**Storage Explorer Version**: 1.16.0
**Build Number**: 20201109.5
**Platform/OS**: Windows
**Commit**: d7220f770 
**Architecture**: ia32
**Regression From**:  1.12
**AzCopy Version**: Unknown
**Support ID**: 6af5193e-69d8-677c-f80e-5de0785294f0

## Bug Description ##
**Error Details**
If you cannot resolve this issue on your own, you may open an issue on the Storage Explorer GitHub site. Please include the details below to help us diagnose your issue. Make sure to redact any personal information you do not wish to make public before posting.

Unable to retrieve child resources.

Details:
Invalid IV length

## Expected Experience ##
Stop showing this error.
I should be able to list all storage accounts under my subscriptions

## Actual Experience ##
I am not able to list the storage accounts for my subscription and currently I am connecting using "Storage connection string"

**Comment by JasonYeMSFT** [comment]
@shary-sharath The error is a syntax error. How did you get the connection string?

**Comment by MRayermannMSFT** [comment]
Close due to lack of response. Please open a new issue if you are still having problems.
