### ISSUE TITLE
Fail to download one disk when the proxy setting is set to 'Use app proxy settings' and the setting 'Disable AzCopy Proxy Usage' is checked

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3782]
**Storage Explorer Version**: 1.16.0
**Build Number**: 20201116.9
**Platform/OS**: Windows
**Architecture**: i32
**Regression From**:  Not a regression

## Steps to Reproduce ##
1. Launch Fiddler -> Launch Storage Explorer.
2. Go to 'Settings' -> 'Transfers' -> Make sure the setting 'Disable AzCopy Proxy Usage' is checked.
2. Configure the proxy setting to 'Use app proxy settings'.
3. Expand 'Disks' -> Open one resource group which contains a disk with 4GB.
4. Try to download the disk -> Observe the result.

## Expected Experience ##
Succeed to download.

## Actual Experience ##
Keep the start downloading state for about 17 minutes and eventually failed.
![image](https://user-images.githubusercontent.com/41351993/99379752-08d95180-2904-11eb-91d6-ffaf46c3ddf1.png)

**Error details:**
`AzCopy failed to complete the transfer: %s

AzCopy error message: failed to perform copy command due to error: cannot use directory as source without --recursive or a trailing wildcard (/*)

AzCopy log file can be found at undefined`

**Comment by JasonYeMSFT** [comment]
Related to #3770, there are various issues when both "Use app proxy settings" and "Disable AzCopy Proxy Usage" is selected.

**Comment by JasonYeMSFT** [comment]
I have made a fix to this bug (also applies to #3770).

**Comment by v-xianya** [comment]
Verified this issue on build 20201120.3. Fixed.
