### ISSUE TITLE
The string 'Property Name' is not translated in the localized 'Add Entity' dialog on languages 'Czech/ French'

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3783]
**Storage Explorer Version:** 1.16.0
**Build**: 20201117.3
**Branch**: main
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04 / MacOS Catalina
**Architecture**: ia32/x64
**Language**: Czech/ French
**Regression From**: Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Čeština' -> Restart Storage Explorer.
3. Expand one storage account -> Tables.
4. Open one table -> Click the localized action 'Add' on the toolbar.
5. Check the strings in the localized 'Add Entity' dialog.

**Expect Experience:**
All strings are translated.

**Actual Experience:**
The string 'Property Name' is not translated.
![image](https://user-images.githubusercontent.com/54055206/99365631-83997100-28f2-11eb-8c7f-a315d1b6a16a.png)

**Comment by MRayermannMSFT** [comment]
@cristianosuzuki77 any idea why we aren't seeing translations for these in `cs` and `fr`? Resource is `src/Standalone/resources/EntityEditorDialog` -> `HeaderPropertyName`.

**Comment by MRayermannMSFT** [comment]
Rechecked today, `cs` and `fr`still in English.

**Comment by cristianosuzuki77** [comment]
Feedback provided to translators. The fix will come in future PR.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20221226.3. Fixed.
![image](https://user-images.githubusercontent.com/87792676/209944743-e66d7f64-6323-46f0-8e4a-07cf156f7f18.png)
