### ISSUE TITLE
The string 'Time to live' is not translated in the localized 'Add Message' dialog

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3784]
**Storage Explorer Version:** 1.16.0
**Build**: 20201117.3
**Branch**: main
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04 / MacOS Catalina
**Architecture**: ia32/x64
**Language**: Czech / Japanese/ Korean / Dutch / Swedish
**Regression From**: Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Čeština' -> Restart Storage Explorer.
3. Expand one storage account -> Queues.
4. Open one queue -> Click the localized action 'Add Message'.
5. Check the strings in the localized 'Add Message' dialog.

**Expect Experience:**
All strings are translated.

**Actual Experience:**
The string 'Time to live' is not translated.
![image](https://user-images.githubusercontent.com/54055206/99371188-8ba8df00-28f9-11eb-9473-bad0750cd62f.png)

**Comment by MRayermannMSFT** [comment]
It looks like this string is not translated in quite a few languages. Loc team, thoughts?
![image](https://user-images.githubusercontent.com/21112697/100006431-51b75d00-2d7f-11eb-892b-4c3688e70030.png)

**Comment by cristianosuzuki77** [comment]
Feel free to tag me with future loc questions.
The string 'Time To Live' is a term, and as such have specific way to be translated.
The example in Czech, the source string in English was 'Time to live value' to which the translation containing the expected term in Czech became 'Hodnota TTL (Time to Live)'
Same with the other languages.

**Comment by MRayermannMSFT** [comment]
Thanks for the clear answer! :)
