### ISSUE TITLE
The folder name with non-ENU character is inconsistent between the editor and Uri

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3786]
**Storage Explorer Version:** 1.16.0
**Build**: 20201117.3
**Branch**: main
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04 / MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**

1. Expand one storage account -> File Shares.
2. Open one file share -> Click 'New Folder' -> Type '新建文件夹' in the folder name box -> Click 'OK'.
3. Right click the folder -> Click the 'Properties...'.
4. Check the 'Uri' in the 'Properties' dialog.

**Expect Experience:**
The folder name is consistent between the editor and Uri.

**Actual Experience:**
The folder name is inconsistent between the editor and Uri.
![image](https://user-images.githubusercontent.com/54055206/99370793-176e3b80-28f9-11eb-8de4-2235cec1d892.png)

**More Info:**

1. This issue doesn't reproduce for one ADLS Gen2 blob folder.
![image](https://user-images.githubusercontent.com/54055206/99370621-de35cb80-28f8-11eb-8773-91b4b39325b1.png)

2. This issue also reproduces for one file and blob.
3. This issue reproduces on lanuages Chinese (Traditional)/ Czech/ Japanese/ Korean.

**Comment by MRayermannMSFT** [comment]
Interesting. This is likely due to differences in the Gen2 private SDK and the v12 SDKs.

I think we should change it to using encode characters like we do else where, **BUT**, if we do, we need to make sure that URL still plays nicely with "Attach with Azure AD".

**Comment by MRayermannMSFT** [comment]
Additional info, if you do Copy URL on the folder the chars are encoded. Copy URL is typically how I test attach with Azure AD, so my guess is that the encoded chars do work with the scenario. Should still check though.

**Comment by MRayermannMSFT** [comment]
@v-limu after some thinking and experimenting, it seems showing the encoded chars for "Copy Url" and the Properties dialog is our best bet. Everything except for gen2 properties dialog is consistent with this, so I'm going to go ahead and fix that and then close this bug. Thanks!

**Comment by v-limu** [comment]
Hi @MRayermannMSFT OK. got it. We will continue to pay attention to this issue.

**Comment by MRayermannMSFT** [comment]
Fix merged into main. You should now see encoded chars in the properteis dialog for gen2 blobs.
