### ISSUE TITLE
Error "Unable to retrieve child resources" thrown when accessing files from a RA-GRS Storage account set up as Data Lake Store

### ISSUE THREAD

**Issue by rgknp** [microsoft/AzureStorageExplorer#3787]
**Storage Explorer Version**: 1.16.0
**Build Number**: 20201109.5
**Platform/OS**: Windows
**Architecture**: ia32
**Regression From**:  Never worked in any version before

## Bug Description ##
Error thrown when connecting to secondary endpoint of a RA-GRS enabled Azure Storage Account set up with Hierarchical namespace (ADLS Gen2)

## Steps to Reproduce ##
1. Create a Azure Storage Account with RA-GRS and enable Data Lake Storage, hierarchical namespace
2. Create a new container and upload a sample data file (like data.csv)
3. Open storage explorer and connect to storage account using account name and key
4. Provide secondary endpoint and access key
5. Try to connect and access the file and error is thrown

## Expected Experience ##
No error should be thrown because storage account is RA-GRS, file should be accessible without any errors.

## Actual Experience ##
A pop up error message appears, after canceling error message, file is accessible.

## Additional Context ##

[StorageExplorerSecondaryAccountBug.txt](https://github.com/microsoft/AzureStorageExplorer/files/5555219/StorageExplorerSecondaryAccountBug.txt)

**Comment by ankitgadhiya** [comment]
I'm also facing exactly the same issue. Error keeps on popping even after I close the error window - 

Unable to retrieve child resources.

Details:
["RestError:﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>OutOfRangeInput</Code><Message>One of the request inputs is out of range.\nRequestId:9d139b77-201e-0049-8066-bc19f2000000\nTime:2020-11-16T22:15:52.1112573Z</Message></Error>"]

**Comment by rgknp** [comment]
Correction to my original issue. Files in Secondary storage are not accessible at all. I had a window open which showed files from the primary account. Storage Explorer is never able to enlist container from secondary endpoint.

**Comment by jinglouMSFT** [comment]
This is a dup of feature request #421
