### ISSUE TITLE
The background color is inconsistent between the editor and other panels under 'Dark' theme

### ISSUE THREAD

**Issue by v-haiz** [Microsoft/AzureStorageExplorer#379]
**Storage Explorer Version**: 1.3.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20180704.1
**Commit**: 865aab62
**Regression From**: Not a regression

**Steps to Reproduce**:
1. Launch Storage Explorer -> Change the current theme to 'Dark' theme.
2. Go to subscription -> Storage Accounts -> Open one blob container.
3. Verify the background color between the container editor and other panels.

**Expected Experience**:
The background color is consistent.

**Actual Experience**:
The background color is inconsistent 
![theme](https://user-images.githubusercontent.com/37653604/42273434-b03e72a8-7f78-11e8-8c78-66e8ebe5f675.PNG)

**More info**:
This issue doesn't reproduce for other themes.

**Comment by craxal** [comment]
This is the expected color for dark theme. @jinglouMSFT, should we consider changing this?

**Comment by jinglouMSFT** [comment]
This is by-design to indicate that the user is actually in an editor on the right hand side.  When there is no editor open, the background color on the right hand side is the same as the left hand's.

**Comment by v-haiz** [comment]
Ok, thanks for your update.
