### ISSUE TITLE
Succeed to paste blobs which support access tier to a BlockBlobStorage blob container with the setting 'Preserve blob access tier' is enabled

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3792]
**Storage Explorer Version**: 1.16.0
**Build Number**: 20201119.2
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: i32/x64
**Regression From**:  Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Go to 'Settings -> Transfers' -> Enable the setting 'Preserve blob access tier'.
2. Expand one GPV2 storage account -> Blob Containers -> Create a blob container.
3. Upload a block blob -> Copy the blob.
4. Expand one BlockBlobstorage account -> Blob Containers -> Open one blob container -> Paste the blob.
5. Check the result.  

## Expected Experience ##
Fail to paste the blob.

## Actual Experience ##
Succeed to paste the blob.

**Comment by JasonYeMSFT** [comment]
Confirmed with AzCopy that it should proceed without setting the access tier. I will change the text of the setting's description.

**Comment by v-xianya** [comment]
@JasonYeMSFT 
Failed to paste blobs which support access tier to one Classic blob container with the 'Preserve blob access tier' is enabled.
Could you help to take a look?

![image](https://user-images.githubusercontent.com/41351993/99753569-5e3e7a00-2b21-11eb-8cdb-58201019b8e8.png)

**Comment by JasonYeMSFT** [comment]
Could you use the latest version to try "pasting to a classic storage account" to see if it is working now?

**Comment by v-xianya** [comment]
@JasonYeMSFT 
Verified on the latest build main/20210416.2. 
Fail to paste one block blob to one classic blob container with 'Preserve blob access tier' enabled.
![image](https://user-images.githubusercontent.com/41351993/114961095-f0f9ff80-9e9a-11eb-8ffb-7eaea9cb13f4.png)

Error in Azcopy:
   `RESPONSE Status: 400 Blob access tier is not supported on this storage account type.`

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220518.1. Fixed.
