### ISSUE TITLE
Show a failed log when promoting version for one append blob and then a current version shows after manually refreshing

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3793]
**Storage Explorer Version**: 1.16.0
**Build Number**: 20201119.2
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: i32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one GPV2 storage account (make sure the blob versioning is enabled) -> Blob Containers.
2. Create a blob container -> Upload one append blob (not 0 B).
3. Delete the blob -> Switch to 'All blobs and blob without current version' view -> Promote the blob version.
4. Refresh the editor after the activity is finished (Show a failed activity log in Activities).
5. Observe the result.

## Expected Experience ##
The actual behavior and the log are consistent.

## Actual Experience ##
The actual behavior and the log are inconsistent.

The failed activity log:
![image](https://user-images.githubusercontent.com/41351993/99652052-4bc92f80-2a92-11eb-8b9f-eafa9b941cb2.png)

The screenshot of the editor：
![image](https://user-images.githubusercontent.com/41351993/99652079-5257a700-2a92-11eb-9777-37160984c8a3.png)

## Additional Context ##
This issue also reproduces for one page blob.

**Comment by JasonYeMSFT** [comment]
I can reproduce this on an append blob but not on a page blob. I logged a bug for AzCopy [1253](https://github.com/Azure/azure-storage-azcopy/issues/1253).

**Comment by v-xianya** [comment]
@JasonYeMSFT The behavior for promoting one page blob version as the below:
![attach](https://user-images.githubusercontent.com/41351993/99748975-8d042280-2b18-11eb-9d57-176201c2bb77.gif)

**Comment by v-xianya** [comment]
Verified this issue on the build 20210915.4. Fixed. Going to close this issue.
![image](https://user-images.githubusercontent.com/41351993/133389626-7151f83a-3b0d-483d-94d2-f6dffda02feb.png)
