### ISSUE TITLE
Error accessing cosmoDB provides no hint at all.

### ISSUE THREAD

**Issue by andrea-cassioli-maersk** [microsoft/AzureStorageExplorer#3795]
**Storage Explorer Version**: 1.16.0
**Build Number**: 20201109.5
**Platform/OS**: macOs
**Architecture**: macOS
**Regression From**:  NA

## Expected Experience ##

* I would like to have an error message that give me some hint!
* If I click `Copy and Report Issue` I would expect to land in a pre-filled bug report, at least with basic information.

## Actual Experience ##

*No clue on what's going on
*Clicking the `Copy and Report Issue` does not help at all.

## Additional Context ##
I can connect to other similar cosmosDB in the same subscription. I could connect to that DB until two days ago. And the DB is perfectly up and running (I can access visa Azure Portal).

**Comment by andrea-cassioli-maersk** [comment]
bump?

**Comment by southpolesteve** [comment]
The Cosmos team recently deprecated our integration with Azure Storage Explorer. [Here is the full deprecation notice from the 1.15.1 Storage Explorer release notes:](https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.15.1)

> The Azure Cosmos DB integration with Storage Explorer has been deprecated. Any existing functionality will not be removed for a minimum of one year from this release. Users should use the Azure Portal, the Azure Portal desktop app, or the standalone Cosmos Explorer instead – all of which contain many new features that aren’t currently supported in Storage Explorer. Additionally, the Azure Cosmos DB team has also open sourced the data explorer project and will be investing in their own desktop tooling at a later date. Please keep an eye on their repository for more information. 

Currently, we are not prioritizing new features or bug fixes for Cosmos in Azure Storage Explorer. If you the issue you are reporting also applies to the Azure Portal or https://cosmos.azure.com, please file an issue in [our open source Cosmos Explorer repo](https://github.com/Azure/cosmos-explorer)
