### ISSUE TITLE
Copy and Paste to the same folder no longer works: Failed to start transfer: Cannot transfer data when the source is the same as the destination

### ISSUE THREAD

**Issue by jasonhorner** [microsoft/AzureStorageExplorer#3796]
**Storage Explorer Version**: 1.16
**Build Number**: 
**Platform/OS**: Windows 10
**Architecture**:  x64? 
**Regression From**:  1.12

## Bug Description ##
in azure storage explorer 1.12 I can copy a file and paste it to the same location (this may seem silly but I'm using this to effectively perform a unix touch command to update the timestamp)

## Steps to Reproduce ##

1. chose a file
2. chose **copy** from menu
3. chose **paste** 

error message "Failed to start transfer: Cannot transfer data when the source is the same as the destination"

## Expected Experience ##
you are allowed to overwrite the file when copying and pasting to the same location. you do  get a warning dialog but can chose to proceed. once the file is overwritten the  modified timestamp is updated

## Actual Experience ##
you are blocked with the error message "Failed to start transfer: Cannot transfer data when the source is the same as the destination"

## Additional Context ##
I basically am using this as a mechanism to update the files modified attributes. While I do think this a regression I'm going to open a feature request to emulate the ability to update the file attributes

**Comment by MRayermannMSFT** [comment]
Hi again @jasonhorner . This is by design. Because how AzCopy handles copy and paste, pasting to the same blob name is no longer feasible. It'll result in data corruption, which we are certain people do not want. That's why we've blocked it.

**Comment by jasonhorner** [comment]
@MRayermannMSFT I guess this makes #3797 more relevant then thanks for providing an explanation. it might be useful to add some text to the warning message as to why the operation is disallowed. especially for folks that maybe be relying on that behavior in downlevel versions
