### ISSUE TITLE
allow the ability to add a folder or file path to "Quick Access"  

### ISSUE THREAD

**Issue by jasonhorner** [microsoft/AzureStorageExplorer#3798]
**Is your feature request related to a problem? Please describe.**
currently I can save a storage account under quick access, I'd like to extend this out to save a path or file  location. Effectively pin a short cut to the item under the quick access tab.

**Describe the solution you'd like**
see above

**Describe alternatives you've considered**
 N/A

**Additional context**
this would be useful to allow quick navigation to a specific location or url within storage explorer

**Comment by MRayermannMSFT** [comment]
Duplicate of #2710
