### ISSUE TITLE
Fail to save the changed access level for one blob container

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#380]
**Storage Explorer Version**: 1.3.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180704.1
**Commit**: 865aab62
**Regression From**: Works well on previous release 1.2.0(20180604.2)

#### Steps to Reproduce: ####
1. Go to subscription -> Storage Accounts.
2. Right click one blob container ->Change the default access level -> 'Save'.
3. Reopen the 'Set Container Public Access Level' dialog then check whether the changed level is saved or not.

#### Expected Experience: ####
The changed access level is saved.

#### Actual Experience: ####
The changed access level isn't saved.

**Comment by craxal** [comment]
Did you wait for the activity to complete? Did you refresh the node?

@MRayermannMSFT, we should consider refreshing the node automatically when the access level is set. We're getting the access level from an attribute, which needs to be refreshed if the access level is changed.

**Comment by MRayermannMSFT** [comment]
Yes. This is the same issue as the access tier. Let me try and find if there is a way to do it.

**Comment by MRayermannMSFT** [comment]
Ok @v-xuanzh , into the 1.3.0 branch I've merged a change that refreshes the public access level property after you change it (there may be a slight delay, just give it a sec). It'll be in the build I send out tonight.

**Comment by v-xuanzh** [comment]
Thanks for your updating.
Now the access level property can auto refresh after changing it. :)
