### ISSUE TITLE
Refresh does not directly refresh

### ISSUE THREAD

**Issue by TurtleBeach** [microsoft/AzureStorageExplorer#3800]
**Storage Explorer Version**: 1.16.0
**Build Number**: 20201109.5
**Platform/OS**: Windows 10 Pro
**Architecture**: x64
**Regression From**:  Problem for months

## Bug Description ##
Clicking refresh when a table is being viewed (first page of n cached items) does not fully refresh storage explorer. An entity added to the table since the last refresh should appear after (1) clicking refresh then (2) clicking the timestamp column to sort so that most recent item is at top in the current (first page view). This does not happen.

## Steps to Reproduce ##
View a table with multiple entities (first page - default sorted by partition key).
Ensure (visual inspection) that table is current at that point in time.
Add (programmatically, independently, via a function) an entity to the table.
Click Refresh (still viewing first page, items still sorted by Partition Key).
Click Timestamp column (twice) to sort by most recent time stamp
The newly added entity does not appear on first page, as expected.
In order to view the newest entity, it is necessary to view another page (e.g., click, say, 5 in the row of numbers at the bottom of the view to go to another page). Then click 1 to return to the first page. Then sort again and the most recent entry appears.
Requires 5 or  6 clicks (AND remembering to do that) to be able to view  the most recent entry.

## Expected Experience ##
Refresh should truly refresh, and sorting by a temporal column should reflect the most recent entry.

## Actual Experience ##
Requires bogus multiple clicks and viewing other pages to get Storage Explorer to accurate reflect the most recent status of a table.

**Comment by MRayermannMSFT** [comment]
@TurtleBeach how many entities do you have in your table? If it's a lot, then likely the problem is with step (2). When you sort by a column header, you are only sorting what Storage Explorer has so far fetched from the server. So if your new entity has not yet been fetched, then you will not see it.

Unfortunately the storage APIs do not let us fetch by timestamp (or other arbitrary column headers), so this is basically by design. Before I close though, can you confirm if you have a table with lots of entities in it?

**Comment by TurtleBeach** [comment]
While I am not sure I would consider this _a lot_, there are currently 1773 entries in the table.
What does the refresh button do, if not update the cached items? When the first page is visible, and the annotation at the bottom says say, _Showing 1 to 100 of 1,773_ cached items. If then an item is added, and I click refresh, the bottom annotation changes to showing 1 of 100, without a total.  If I then click to sort by a column, I would expect it to affect all cached items - and it appears to do so, but the effect is only visible after I navigate to another page, then back to the first page. That is what leads me to think there is a problem. I note that for this current test, the row key assigned (a GUID) put the new item on 11th page of 100 entities (showing 1,101 to 1200 of 1774 entities). Does that mean a fetch gets 1000 entities?

**Comment by MRayermannMSFT** [comment]
@TurtleBeach ok, then the experience is working as expected. If you click refresh, it's like you close and reopen the tab. We initially load 1000 rows, so if your new entity is after 1000 for the default sort, then it won't show up after refresh until you click "Load more" as needed to get to the page it is on.

**Comment by TurtleBeach** [comment]
OK. Understanding what is going on is helpful. I will close the issue.
