### ISSUE TITLE
Target folder for downloads does not persist

### ISSUE THREAD

**Issue by kennypage** [microsoft/AzureStorageExplorer#3802]
Starting with release 1.16.0 (Windows), when you download a file from a blob storage account, the "select a folder for download" picker now *always* defaults to the users default downloads folder from their userprofile, not the last folder used (which was the previous behaviour).

Whilst this may be required for privacy when the first attempt is made to download a file per session, it is sub-optimal when multiple seperate downloads are being performed in the same session and the application reverts back to the users default downloads folder for each item.

**Comment by MRayermannMSFT** [comment]
@kennypage, thanks for reporting this. You're right, it is a revert in behavior. We'll get it fixed for our next release.

**Comment by MRayermannMSFT** [comment]
@kennypage I'm almost done working on the fix for this. Let me know if you'd like to preview it incase there's something we missed. Otherwise, look for it to come out in our next release. 🙂

**Comment by kennypage** [comment]
@MRayermannMSFT - no need for a preview, i'm happy to wait for it in a future release, ta! 👍

**Comment by MRayermannMSFT** [comment]
Fix merged into main. Will be included in 1.17.0 release.
