### ISSUE TITLE
No 'start timestamp' and 'completion time' show in the AzCopy activity log when deleting one blob

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3803]
**Storage Explorer Version**: 1.16.0
**Build Number**: 20201121.3
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**:  Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create a new blob container -> Upload one blob to it ->Delete the blob.
3. Check whether the 'start timestamp' and 'completion time' show in the activity log.

## Expected Experience ##
It is better to show the 'start timestamp' and 'completion time' in the activity log.
![image](https://user-images.githubusercontent.com/54055206/99945379-7e836880-2daf-11eb-8b85-9b073bea202c.png)

## Actual Experience ##
No 'start timestamp' and 'completion time' show in the activity log.
![image](https://user-images.githubusercontent.com/54055206/99944550-06687300-2dae-11eb-9e12-0c36fd94fb88.png)

## Additional Context ##
This issue also reproduces when deleting one file under file shares.

**Comment by v-xianya** [comment]
Verified on the build main/20201202.1. Fixed.
