### ISSUE TITLE
No se pueden recuperar los recursos secundarios

### ISSUE THREAD

**Issue by lfrz74** [microsoft/AzureStorageExplorer#3804]
No se pueden recuperar los recursos secundarios.

Detalles:
This request is not authorized to perform this operation.
RequestId:e7d33a18-4002-0022-69b2-c190e2000000
Time:2020-11-23T16:07:54.1515751Z

**Comment by MRayermannMSFT** [comment]
@lfrz74 what type of resources are you trying to load?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of responses. If you are still having problems, please open a new issue. Thanks!
