### ISSUE TITLE
An error 'Server failed to authenticate the request' occurs when renaming a blob under one SAS attached ADLS Gen2 storage account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3806]
**Storage Explorer Version**: 1.16.0
**Build Number**: 20201124.2
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**:  Not a regression

## Steps to Reproduce ##
1. Attach one ADLS Gen2 storage account via SAS -> Expand the attached storage account -> Blob Containers.
2. Create one blob container -> Upload one blob -> Try to rename the blob with a valid name.
3. Check whether the blob is renamed successfully or not.

## Expected Experience ##
The blob is renamed successfully.

## Actual Experience ##
1. Failed to rename the blob.
2. Show an error 'Server failed to authenticate the request'.
![image](https://user-images.githubusercontent.com/41351993/100066987-ac7cb180-2e70-11eb-8d69-e6aa98c86b8c.png)

Error details:
`"name": "Error",
  "message": "Server failed to authenticate the request. Please refer to the information in the www-authenticate header.\nRequestId:a1e47a80-901f-0054-3e3a-c29595000000\nTime:2020-11-24T08:16:57.7400670Z",`

## Additional Context ##
1. This issue reproduces when creating a new folder under one SAS attached ADLS Gen2 storage account.
2. This issue reproduces when moving files under one SAS attached ADLS Gen2 storage account.

**Comment by JasonYeMSFT** [comment]
There is no way to use account SAS to authenticate this operation. When we enable attaching with account SAS in 1.18.0, this action will be disabled.

**Comment by v-xianya** [comment]
Verified this issue on build 20210129.3. The 'Rename & Move' actions are disabled. So close this issue.
![image](https://user-images.githubusercontent.com/41351993/106255954-a252a700-6255-11eb-814a-4e82ff28c4a7.png)
