### ISSUE TITLE
Fail to get properties for one folder under one SAS attached ADLS Gen2 storage account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3807]
**Storage Explorer Version**: 1.16.0
**Build Number**: 20201124.2
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Attach one ADLS Gen2 storage account via SAS -> Expand the attached storage account -> Blob Containers.
2. Create one blob container -> Upload one folder.
3. Right click the folder -> Click 'Properties...'.
4. Check whether the properties dialog pops up or not.

## Expected Experience ##
The properties dialog pops up.

## Actual Experience ##
1. No properties dialog pops up.
2. Failed to get properties for the folder.
![image](https://user-images.githubusercontent.com/41351993/100068017-edc19100-2e71-11eb-8682-8fdd75c26e4c.png)
![image](https://user-images.githubusercontent.com/41351993/100068070-fca84380-2e71-11eb-9e8c-701e61fe4d02.png)

## Additional Context ##
This issue doesn't reproduce for one blob under a SAS attach ADLS Gen2 storage account.

**Comment by JasonYeMSFT** [comment]
A fix has been merged for this bug.

**Comment by v-limu** [comment]
Verified this issue on build main/20201204.2. Fixed. So we close it.
