### ISSUE TITLE
Failed to start delete one blob with an error 'Insufficient credentials' under one SAS attached ADLS Gen2 storage account 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3808]
**Storage Explorer Version**: 1.16.0
**Build Number**: 20201124.2
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**:  ia32/x64
**Regression From**:  Not a regression

## Steps to Reproduce ##
1. Attach one ADLS Gen2 storage account via SAS -> Expand the attached storage account -> Blob Containers.
2. Create one blob container -> Upload one blob -> Delete the blob.
3. Check whether the blob is deleted successfully or not.

## Expected Experience ##
The blob is deleted successfully.

## Actual Experience ##
Failed to start delete with an error 'Insufficient credentials'.
![image](https://user-images.githubusercontent.com/41351993/100070452-ea7bd480-2e74-11eb-8761-ad8de31c8313.png)

## Additional Context ##
1. This issue also reproduces when deleting one folder under one SAS attached ADLS Gen2 storage account.
2. This issue doesn't reproduce when deleting one snapshot under one SAS attached ADLS Gen2 storage account.

**Comment by MRayermannMSFT** [comment]
@v-xianya what permissions did you generate your SAS with?

**Comment by v-xianya** [comment]
@MRayermannMSFT With the full permissions when generating SAS.

**Comment by JasonYeMSFT** [comment]
A fix has been merged for this bug.

**Comment by v-xianya** [comment]
Verified this issue on build main/20201203.1. Fixed.
