### ISSUE TITLE
An extra log message displays after saving access policies for one blob container

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#381]
**Storage Explorer Version**: 1.3.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180704.1
**Commit**: 865aab62
**Regression From**: Previous release 1.2.0(20180604.2)

#### Steps to Reproduce: ####
1. Go to subscription -> Storage Accounts.
2. Right click one blob container -> Select 'Manage Access Policies...' -> Add one policy then save it.
3. Check whether the log message displays or not.

#### Expected Experience: ####
No log message displays in Activities window.

#### Actual Experience: ####
An extra log message which is same as the action 'Set Public Access Level' displays.
![log](https://user-images.githubusercontent.com/34729022/42275205-074a4ea4-7f7f-11e8-8fff-6f102a90b040.png)

**Comment by craxal** [comment]
The is expected, because we have to set the public access level along with they access policies. Otherwise they will overwrite each other.

**Comment by MRayermannMSFT** [comment]
Yep this is expected. We really need to get better at updating test cases. I'll try to find some time to do that. Thank you for the report though @v-xuanzh !

**Comment by v-xuanzh** [comment]
Hi @craxal @MRayermannMSFT ,
Is the log message just apply for blob containers? Because we noticed that no log message displays when updating access policies for file shares/queues/tables.

**Comment by MRayermannMSFT** [comment]
Correct. We'll eventually be adding log messages for the other ones as well (probably next release).

**Comment by v-xuanzh** [comment]
Do we need to log a bug for other ones?

**Comment by MRayermannMSFT** [comment]
I'll open a work item. 😄
