### ISSUE TITLE
Upload fails at 100% for 30 GB VHD file to Azure

### ISSUE THREAD

**Issue by bwarren18** [microsoft/AzureStorageExplorer#3814]
**Storage Explorer Version**: 1.16.0
**Build Number**: 20201109.5
**Platform/OS**: Windows 10 version 20H2
**Architecture**: x64
**Regression From**:  N/A

## Bug Description ##
I am trying to upload a large file (30GB VHD) to an Azure Resource Group.
After a few failed uploads, and retries/resumes it reached 100% but then failed with this error.

An unhandled exception occured while attempting to complete this operation: {
  "message": "{\"type\":\"Unhandled\",\"error\":\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"Unable to retrieve authentication token while creating compute client for Disks.\\\\nValue cannot be null.\\\\r\\\\nParameter name: accessToken\\\",\\n  \\\"stack\\\": \\\"Error: Unable to retrieve authentication token while creating compute client for Disks.\\\\nValue cannot be null.\\\\r\\\\nParameter name: accessToken\\\\n    at Object.<anonymous> (C:\\\\\\\\Program Files (x86)\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\se-managed-disks-extension\\\\\\\\dist\\\\\\\\src\\\\\\\\AzureSdkHelpers\\\\\\\\CredentialFactory.js:29:31)\\\\n    at step (C:\\\\\\\\Program Files (x86)\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\tslib\\\\\\\\tslib.js:141:27)\\\\n    at Object.next (C:\\\\\\\\Program Files (x86)\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\tslib\\\\\\\\tslib.js:122:57)\\\\n    at fulfilled (C:\\\\\\\\Program Files (x86)\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\tslib\\\\\\\\tslib.js:112:62)\\\\n    at runMicrotasks (<anonymous>)\\\\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\\\"\\n}\"}"
}

## Steps to Reproduce ##
In ASE, navigate to Resource Group, click Upload, select VHD file, set OsType to Linux, hit Create.

## Expected Experience ##
The process should complete without interruption and a valid file should be uploaded.

## Actual Experience ##
Several times the upload failed.  Each time I repeated the same steps and it appears to resume from where the download left off.  The last time it failed I restarted my computer and the upload started from 0% but reached 100% and failed with a different error.

**Comment by MRayermannMSFT** [comment]
@bwarren18 how long is your upload taking? Additionally, after the upload fails, if you go to the account panel, does it say you need to re-enter your credentials? I wonder if your account is going stale in the time it takes to do the upload...

**Comment by bwarren18** [comment]
Hi, 
I deleted the file it created previously that did not work and then did the upload again from scratch.
It actually completed without error this time, I guess third time was the charm.
The upload reached 100% and took about 20 minutes.

**Comment by MRayermannMSFT** [comment]
Hm. 20 minutes probably shouldn't be long enough for you account to go stale. Since it finished this time, I think I'm going to close this. If you see it again and can't get past it after trying again once or twice, feel free to open a new issue...
