### ISSUE TITLE
[Localization] Assistance with translation

### ISSUE THREAD

**Issue by cristianosuzuki77** [microsoft/AzureStorageExplorer#3815]
String Resource ID | 0; "TitleAdlsGen2BlobSnapshots"
-- | --
Source String | Enable ADLS Gen2 snapshots (Preview)
Filename | loc\en\src\Standalone\resources\Shell.json
Question | Please confirm this is still temporary and should NOT be translated.

**Comment by MRayermannMSFT** [comment]
Correct.
