### ISSUE TITLE
Subscriptions could not be loaded.

### ISSUE THREAD

**Issue by darshanoza** [microsoft/AzureStorageExplorer#3818]
**Storage Explorer Version**: 1.16.0
**Build Number**: 20201109.5
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  Not aware. This is the first time i am using the windows 10 client for Azure storage explorer.

## Bug Description ##
On "Manage Accounts" tab, i get a message "Subscriptions could not be loaded. Please try reentering the credentials or removing and readding the account"

## Steps to Reproduce ##
Add a new account in the "Manage Accounts" tab

## Expected Experience ##
Subscriptions and Storage accounts should have loaded

## Actual Experience ##
Subscriptions and Storage accounts didnt  load
On "Manage Accounts" tab, i get a message "Subscriptions could not be loaded. Please try reentering the credentials or removing and readding the account"

## Additional Context ##

Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: badc35f2-5751-41fa-a23c-87fa38f35eb2, Error: {
  "name": "Error",
  "message": "connect ETIMEDOUT fdcb:872:dc62:7777::d46:4a41:443",
  "__zone_symbol__error": {
    "originalStack": "Error: connect ETIMEDOUT fdcb:872:dc62:7777::d46:4a41:443",
    "zoneAwareStack": "Error: connect ETIMEDOUT fdcb:872:dc62:7777::d46:4a41:443"
  },
  "stack": "Error: connect ETIMEDOUT fdcb:872:dc62:7777::d46:4a41:443\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14)",
  "originalStack": "Error: connect ETIMEDOUT fdcb:872:dc62:7777::d46:4a41:443",
  "zoneAwareStack": "Error: connect ETIMEDOUT fdcb:872:dc62:7777::d46:4a41:443",
  "__zone_symbol__stack": "Error: connect ETIMEDOUT fdcb:872:dc62:7777::d46:4a41:443",
  "__zone_symbol__name": "Error",
  "__zone_symbol__message": "connect ETIMEDOUT fdcb:872:dc62:7777::d46:4a41:443",
  "__zone_symbol__originalStack": "Error: connect ETIMEDOUT fdcb:872:dc62:7777::d46:4a41:443",
  "__zone_symbol__zoneAwareStack": "Error: connect ETIMEDOUT fdcb:872:dc62:7777::d46:4a41:443",
  "errno": "ETIMEDOUT",
  "code": "ETIMEDOUT",
  "syscall": "connect",
  "address": "fdcb:872:dc62:7777::d46:4a41",
  "port": 443
}

**Comment by vladonemo** [comment]
I have the same issue.

**Comment by MRayermannMSFT** [comment]
@darshanoza ETIMEDOUT means there Storage Explorer wasn't able to reach the server (Azure). Are you behind a proxy? If so, you need to set that up in settings.

**Comment by darshanoza** [comment]
Thanks Mate! That was the issue indeed. It works after entering the correct proxy settings.

Cheers
