### ISSUE TITLE
There is a typo ‘trtailing’ in the error message when using ‘.’ as the name to rename one blob folder

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3819]
**Storage Explorer Version**: 1.16.0
**Build Number**: 20201126.2
**Branch**: main
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture:** ia32/x64
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Create a new folder.
3. Right click the folder -> Click 'Rename...'  -> Type '.' as the new name.
4. Check whether there is a typo in the error message.

## Expected Experience ##
There is no typo in the error message. 
![image](https://user-images.githubusercontent.com/54055206/100327363-2befb980-3006-11eb-86ce-73e77b5aeb33.png)

## Actual Experience ##
There is a typo ‘trtailing’ in the error message. 
![image](https://user-images.githubusercontent.com/54055206/100326246-acadb600-3004-11eb-86c7-69c32eda8aba.png)

## Additional Context ##

1. This issue doesn't reproduce for one ADLS Gen2 blob.
2. This issue doesn't reproduce for one regular blob/ blob folder /file.

**Comment by MRayermannMSFT** [comment]
Fix merged in build #20201204.3 and later.

**Comment by v-xianya** [comment]
@MRayermannMSFT Thank you for the update！
Verified this issue on build 20201204.3 and 20201204.4. Reproduce.
We are going to re-open this bug and verify it on the later build. We will close it once fixed.

**Comment by MRayermannMSFT** [comment]
Oh, I didn't mean to close this. This has **not** been fixed yet.

**Comment by v-limu** [comment]
Verified on build 20201206.2. This issue has been fixed. So close it.
![image](https://user-images.githubusercontent.com/54055206/101317980-6af6e980-3814-11eb-84d6-d93ce6e30a8c.png)
