### ISSUE TITLE
Slight delay when saving added access policies for blob containers

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#382]
**Storage Explorer Version**: 1.3.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180704.1
**Commit**: 865aab62
**Regression From**: Previous release 1.2.0(20180604.2)

#### Steps to Reproduce: ####
1. Go to subscription -> Storage Accounts.
2. Right click one blob container -> Select 'Manage Access Policies...' -> Add one policy then save it.

#### Expected Experience: ####
The 'Manage Access Policies' dialog disappear immediately after saving the added access policies.

#### Actual Experience: ####
The 'Manage Access Policies' dialog keeps about 5 seconds.

#### More info: ####
This issue doesn't reproduce for file shares/queues/tables.

**Comment by MRayermannMSFT** [comment]
Yes! So the way the Manage Access Policies dialog works is that it calls the provider, and then closes. A better experience (in my opinion) would to do the opposite. Call provider -> provider call/code that the provider called open the dialog -> dialog closes -> setting happens.

**Comment by MRayermannMSFT** [comment]
So I'll leave this open for 1.4.0
