### ISSUE TITLE
The empty ADLS Gen2 folder disappears after using the character '?' to rename it

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3820]
**Storage Explorer Version**: 1.16.0
**Build Number**: 20201126.2
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create one new empty folder with the default name -> Rename the folder with the character '?'.
3. Check the result.

## Expected Experience ##
Fail to rename the folder.

## Actual Experience ##
The new empty folder disappears and show a successful activity log.
![image](https://user-images.githubusercontent.com/41351993/100336134-c2c17380-3010-11eb-9abf-20f2ad5fbc7d.png)

## Additional Context ##
1. Fail to create a new folder using the character '?'.
![image](https://user-images.githubusercontent.com/41351993/100334266-82f98c80-300e-11eb-9476-66a7cb71fb2d.png)
2. Fail to rename one non-empty folder using the character '?'.
![image](https://user-images.githubusercontent.com/41351993/100334517-dc61bb80-300e-11eb-8ef6-6dc4556cc7f2.png)

**Comment by MRayermannMSFT** [comment]
Probably just not encoding the ? correctly or something like that.

**Comment by JasonYeMSFT** [comment]
The reason was that the rename source considers the string after ? as the query parameter of the rename source. We need to encode the name before sending it to the SDK.

**Comment by v-xianya** [comment]
@JasonYeMSFT Verified this issue on build 20210203.5.
All actions against one ADLS Gen2 folder named '?' work fine. Like 'create/ rename/delete/get properties... '. 
Is this the expected behavior (Allow '?' as a valid name for one ADLS Gen2 folder)?

**Comment by JasonYeMSFT** [comment]
@v-xianya. Yes, since the service accept encoded ? as a part of the file/folder/name.

**Comment by v-xianya** [comment]
@JasonYeMSFT ok, we are going to close this bug.
