### ISSUE TITLE
There are 'File Shares' and 'Queues' and 'Tables' nodes under one classic premium storage account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3821]
**Storage Explorer Version**: 1.16.0
**Build Number**: 20201126.2
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Create a classic premium storage account from portal -> Expand the storage account.
2. Check whether there are 'File Share' & 'Queues' & 'Tables' nodes.

## Expected Experience ##
There no 'File Shares' and 'Queues' and 'Tables' nodes.

## Actual Experience ##
There are 'File Shares' and 'Queues' and 'Tables' nodes.
![image](https://user-images.githubusercontent.com/41351993/100423967-de3b8580-30c7-11eb-9ca3-c52c9d4ecd27.png)

## Additional Context ##
The properties for the classic storage account.
![image](https://user-images.githubusercontent.com/41351993/100423654-49d12300-30c7-11eb-8735-5d589d91f41c.png)

**Comment by MRayermannMSFT** [comment]
@v-xianya did you mean "classic or premium", or did you somehow make an account which is both classic AND premium.

**Comment by v-xianya** [comment]
@MRayermannMSFT 
This account is a Classic account with Premium performance.
![image](https://user-images.githubusercontent.com/41351993/100687384-2ce46a80-33bb-11eb-8eb6-f42247da2939.png)

**Comment by MRayermannMSFT** [comment]
Fix for this merged into main.
