### ISSUE TITLE
One part of the localized descriptions for the Blob Explorer part in Settings is unclear on Chinese(zh-CN)

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3822]
**Storage Explorer Version**: 1.16.0
**Build:** 20201126.2
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04 / MacOS Catalina
**Architecture**: ia32/x64
**Language**: Chinese (zh-CN)
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Open 'Settings' -> Application (Regional Settings).
2. Select '中文(简体)' -> Restart Storage Explorer.
3. Switch to the 'Settings' -> 'Data Explorers' -> Observe the descriptions of the Blob Explorer part.
4. Check whether the localized descriptions are clear.

## Expected Experience ##
The localized descriptions are clear.

## Actual Experience ##
One part of the localized descriptions is unclear. 
![image](https://user-images.githubusercontent.com/41351993/100431034-90784a80-30d2-11eb-81ab-37f0874e11d8.png)

**Comment by MRayermannMSFT** [comment]
@v-xianya can you explain what part of the translation is unclear? That way translation team can address your feedback directly.

**Comment by v-xianya** [comment]
@MRayermannMSFT Thank you for the update!
The screenshot in English:
![image](https://user-images.githubusercontent.com/41351993/100687912-21de0a00-33bc-11eb-83b9-40c546736b94.png)

There are extra character '吧' and double brackets in the translation of the sentence 'When performing an operation on a stub blob, such as delete'.

The clear translation would be '对存根Blob执行操作，例如删除它时，' not '对存根 吧Blob执行操作，(例如删除它)时'。

**Comment by JasonYeMSFT** [comment]
I think this is a more natural way to express it in Simplified Chinese. "对存根Blob执行操作时（例如删除），......". @cristianosuzuki77 Could you please help bring these two suggestions to the translator?
- "对存根Blob执行操作时（例如删除），......"
- "对存根Blob执行操作，例如删除它时, ......"

Including the original translation, they can pick the best one they think among them.

**Comment by cristianosuzuki77** [comment]
Feedback provided. The modifications to this resource will be coming in a future PR (if the suggestions are accepted)

**Comment by v-xianya** [comment]
Verified this issue on the build main 20220808.1. Fixed. So, we are going to close it.
![image](https://user-images.githubusercontent.com/41351993/183382070-b53da4d1-ee3f-4e66-aa40-398fb2043d09.png)
