### ISSUE TITLE
Storage Accounts missing in list view

### ISSUE THREAD

**Issue by ranasch** [microsoft/AzureStorageExplorer#3824]
**Storage Explorer Version**: 1.16
**Build Number**: 20201109.5
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  unknown

## Bug Description ##
I connected Storage Explorer with my account, who has owner permission on several subscriptions. When I browse the subscription and Azure Accounts, not all accounts are listed. I can see in Azure portal additional accounts, but cannot access them via Storage Explorer by account access.

## Steps to Reproduce ##
1. In Azure Storage Explorer, open Account Management and add an account with subscription permission
1. Switch to Explorer view and drill down to Storage Accounts
1. Compare with Storage accounts listed in Azure portal to that subscription

## Expected Experience ##
1. All Storage Accounts where my account has access permission to are listed

## Actual Experience ##
1. Some Storage accounts are not listed. Also after a refresh. Sometime, restarting the storage explorer helps, so the missing accounts are listed.

**Comment by MRayermannMSFT** [comment]
@ranasch 
Can you double check that you're working with the correct subscriptions? Often times subscriptions have the same names, so you can double check by comparing subscription IDs.

If that isn't the problem, is it possible you need to click "Load more" under the list of storage accounts?

**Comment by ranasch** [comment]
Yes, I can confirm that its the right subscription and there is no "load more". They are simply missing (in side by side view with portal). Sometimes they re-appear after restarting SE. My workaround is adding them by key,

**Comment by MRayermannMSFT** [comment]
@ranasch are you still seeing this occur?

**Comment by ranasch** [comment]
checked today I didn´t see a repo anymore. So I take it its fixed... Thanks!

**Comment by MRayermannMSFT** [comment]
Was likely a server side thing so 🤷‍♀️
