### ISSUE TITLE
Collapse + decollapse items in CosmosDB

### ISSUE THREAD

**Issue by SvenVandenbrande** [microsoft/AzureStorageExplorer#3825]
**Describe the solution you'd like**
Is it possible to collapse, decollapse items in the storage explorer for cosmos db collections?
Just like you can do in the data explorer in the Azure Portal.

**Additional context**
See example in screenshot from the data explorer in the Azure portal, removed some confidential info in the screenshot.
![Collapse](https://user-images.githubusercontent.com/1930936/100738220-940f1880-33d5-11eb-8594-3372dc126a1c.jpg)

**Comment by southpolesteve** [comment]
The Cosmos team recently deprecated our integration with Azure Storage Explorer. [Here is the full deprecation notice from the 1.15.1 Storage Explorer release notes:](https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.15.1)

> The Azure Cosmos DB integration with Storage Explorer has been deprecated. Any existing functionality will not be removed for a minimum of one year from this release. Users should use the Azure Portal, the Azure Portal desktop app, or the standalone Cosmos Explorer instead – all of which contain many new features that aren’t currently supported in Storage Explorer. Additionally, the Azure Cosmos DB team has also open sourced the data explorer project and will be investing in their own desktop tooling at a later date. Please keep an eye on their repository for more information. 

Currently, we are not prioritizing new features or bug fixes for Cosmos in Azure Storage Explorer. If you the issue you are reporting also applies to the Azure Portal or https://cosmos.azure.com, please file an issue in [our open source Cosmos Explorer repo](https://github.com/Azure/cosmos-explorer)

**Comment by SvenVandenbrande** [comment]
Ok, thank you for the information.
