### ISSUE TITLE
Impossible access Azure Storage content with error SELF_SIGNED_CERT_IN_CHAIN

### ISSUE THREAD

**Issue by mcmpmkt** [microsoft/AzureStorageExplorer#3826]
Não é possível recuperar recursos filho.

Detalhes:
{
  "name": "FetchError",
  "message": "request to https://pmkt.blob.core.windows.net/?include=metadata&comp=list failed, reason: self signed certificate in certificate chain",
  "__zone_symbol__error": {
    "originalStack": "Error: request to https://pmkt.blob.core.windows.net/?include=metadata&comp=list failed, reason: self signed certificate in certificate chain\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files

...

Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:141:62)\n    at step (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)",
  "type": "system",
  "errno": "SELF_SIGNED_CERT_IN_CHAIN",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}

**Comment by MRayermannMSFT** [comment]
Please see the troubleshooting guide: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C1804#error-self-signed-certificate-in-certificate-chain-and-similar-errors

**Comment by MRayermannMSFT** [comment]
Closing due to lack of responses. If you are still having problems, please open a new issue. Thanks!
