### ISSUE TITLE
Localize "Accounts" in "Storage Accounts", "Cosmos DB Accounts"

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#3827]
When running Storage Explorer in languages other than English,  The string "Accounts" in "Storage Accounts", "Cosmos DB Accounts" should be localized.  The words "Preview" or "Deprecated" should also be localized.  The customer expects us to have a consistent experience in terms of translation/localization.  Here is an example screenshot running Storage Explorer in French:

![image](https://user-images.githubusercontent.com/10081483/100800499-89578200-33db-11eb-80cc-526b856a46c1.png)

These strings appear in:
shell.json: "Storage Accounts"
AzureStorageAccountV2ResourceTypeConfig.js: "Storage Accounts"
AzureDocumentDBAccountConfig.js  / AzureDocumentDBAccountResourceTypeConfig.js: "Cosmos DB Accounts"
AzureDataLakeStorageResourceTypeConfig.js: "Data Lake Storage Gen1"

Please make sure we make these strings localizable, then assign the bug to Cristiano Suzuki for loc.  Thanks.

**Comment by v-xianya** [comment]
@JasonYeMSFT Verified this issue on build 20210202.9. Reproduce, so we are going to re-open it.
1. The string 'Data Lake Storage Gen1 (Preview)' is not localized. 
Reproduce on ZHTW/Russian/Portuguese(Portugal)/Dutch/Korean/Spanish/Czech.

    The screenshot in ZH-TW:
    ![image](https://user-images.githubusercontent.com/41351993/106558718-2b702380-655f-11eb-93c1-a42cd031ae21.png)

2. The string 'Storage Accounts/ Cosmos DB Accounts (Deprecated)/ Data Lake Storage Gen1 (Preview)' are not localized.
Reproduce on ZH-CN/Turkish/Swedish/Portuguese(Brazil)/Polish/Japanese/Italian/Hungarian/French/German.

    The screenshot in ZH-CN:
    ![image](https://user-images.githubusercontent.com/41351993/106558796-50649680-655f-11eb-9eb7-9c2c0b00a733.png)

**Comment by JasonYeMSFT** [comment]
These strings should have been translated.

**Comment by v-xianya** [comment]
Verified this issue on build 20210205.4. Still reproduces. Same behaviors as the above comments.

**Comment by JasonYeMSFT** [comment]
All should have been translated now.

**Comment by v-xianya** [comment]
Verified this issue on build 20210220.2. 
The string 'Data Lake Storage Gen1 (Preview)' is not translated for all languages.

![image](https://user-images.githubusercontent.com/41351993/108580795-14f00780-7368-11eb-8dce-74164a8bcdc2.png)

**Comment by JasonYeMSFT** [comment]
We are not going to translate Data Lake Storage Gen1 because they are going to be deprecated.
