### ISSUE TITLE
The Connect dialog doesn't auto display after reopening Storage Explorer without account added

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#383]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**:  Linux Ubuntu 16.04
**Architecture**: x64
**Build Number**: 20180704.1
**Commit**: 865aab62
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Launch Storage Explorer and sign in with your account.
2. Remove the added account -> Close Storage Explorer.
3. Reopen Storage Explorer and check whether the Connect dialog auto displays or not.

#### Expected Experience: ####
The Connect dialog auto displays after reopening Storage Explorer.

#### Actual Experience: ####
The Connect dialog doesn't auto display after reopening Storage Explorer.

**Comment by MRayermannMSFT** [comment]
Do you have anything attached? For the dialog to appear you have to have:

- No attached accounts or resources
- Not be signed in

**Comment by v-xuanzh** [comment]
I tried this again according to the provided states. The Connect dialog appears. Could you help to resolve this issue. Thanks~

**Comment by MRayermannMSFT** [comment]
Yep!
