### ISSUE TITLE
The blobs in the virtual folder are not counted at the folder level with 'Blob versioning' enabled

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3833]
**Storage Explorer Version**: 1.16.0
**Build Number**: 20201203.3
**Branch**: main
**Platform/OS**: Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Select one GPV2 or Blob storage account with 'Blob versioning' enabled.
2. Expand the selected storage account -> Blob Containers.
3. Create a blob container -> Create a virtual folder and upload one blob to it.
4. Right click the folder -> Click 'Selection Statistics 2'.
5. Observe the activity log -> Check whether the blob is counted or not.

## Expected Experience ##
The blob is counted.

## Actual Experience ##
The blob is not counted.

**The log for the activity 'Selection Statistics 2':**
![image](https://user-images.githubusercontent.com/41351993/100986965-d7f64f00-3588-11eb-8ebe-9e369bee664d.png)
**The log for the activity 'Selection Statistics':**
![image](https://user-images.githubusercontent.com/41351993/100986974-daf13f80-3588-11eb-914a-409793c16c51.png)

## Additional Context ##
This issue doesn't reproduce when 'Blob versioning' is disabled.

**Comment by MRayermannMSFT** [comment]
Fix merged in build #20201204.3 and later.
