### ISSUE TITLE
Fail to perform the action 'Selection Statistics 2' for one blob version without current version

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3834]
**Storage Explorer Version**: 1.16.0
**Build Number**: 20201203.3
**Branch**: main
**Platform/OS**: Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Select one GPV2 or Blob storage account with 'Blob versioning' enabled.
2. Expand the selected storage account -> Blob Containers.
3. Create a new blob container -> Upload one blob -> Delete the blob.
4. Switch to 'All blobs and blobs without current version' -> Perform the action 'Selection Statistics 2'.
5. Observe whether the action is performed successfully or not.

## Expected Experience ##
The action is performed successfully.

## Actual Experience ##
Fail to perform the action.
![image](https://user-images.githubusercontent.com/41351993/100990560-f8280d00-358c-11eb-9752-7b89e45a6be0.png)

**Error info:**
`
Failed to inspect gdhgew.csv, error: {
  "name": "Error",
  "message": "Unable to get size of gdhgew.csv",
  "stack": "Error: Unable to get size of gdhgew.csv\n    at ActiveState.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-blob-extension\\dist\\src\\JobHandlers\\BlobStatistics\\States\\ActiveState.js:207:35)\n    at step (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-blob-extension\\node_modules\\tslib\\tslib.js:140:27)\n    at Object.next (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-blob-extension\\node_modules\\tslib\\tslib.js:121:57)\n    at fulfilled (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-blob-extension\\node_modules\\tslib\\tslib.js:111:62)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
}

`

**Comment by MRayermannMSFT** [comment]
Fix merged in build #20201204.3 and later.

**Comment by MRayermannMSFT** [comment]
@v-xianya and @v-limu , for this scenario, it is expected that "selections statistics 2" does **not** count a blob version with out current version towards the statistics. The statistics feature is supposed to only count **active** blobs. It should not count non-active blob versions, soft deleted blobs, and snapshots. The fact that the old statistics counts those is a bug.

**Comment by v-xianya** [comment]
@MRayermannMSFT Hi Matthew, thank you for the clarification. It is clear.😀
