### ISSUE TITLE
The statistics result is incorrect when executing 'Selection Statistics 2' for an ADLS Gen2 folder with one subfolder

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3836]
**Storage Explorer Version**: 1.16.0
**Build Number**: 20201203.3
**Branch**: main
**Platform/OS**: Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From**:  Not a regression

## Steps to Reproduce ##

1. Expand one ADLS Gen2 account -> Blob Containers.
2. Create a new blob container -> Create a new folder **then create a subfolder in it.**
3. Right click the folder -> Click 'Selection Statistics 2'.
4. Check whether the blob statistics is correct. 

## Expected Experience ##
The blob statistics result is correct (the stats is '0 blobs').

## Actual Experience ##
The blob statistics result is incorrect (the stats is '1 blobs').
![image](https://user-images.githubusercontent.com/54055206/100989853-3cff7400-358c-11eb-8c87-44ec0faff435.png)

## Additional Context ##
The blob statistics result is '0 blobs' for one ADLS Gen2 folder without subfolders.

**Comment by v-xianya** [comment]
Verified this issue on build main/20201204.1. Fixed.
