### ISSUE TITLE
The blob container name is not surrounded by quotation marks in the activity log of the blob statistics 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3837]
**Storage Explorer Version**: 1.16.0
**Build Number**: 20201203.3
**Branch**: main
**Platform/OS**: Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create a new blob container -> Upload one blob to it.
3. Right click the blob -> Click 'Selection Statistics 2'.
4. Observe the activity log -> Check whether the blob container name is surrounded by quotation marks.

## Expected Experience ##
The blob container name is surrounded by quotation marks. 

## Actual Experience ##
The blob container name is not surrounded by quotation marks.
![image](https://user-images.githubusercontent.com/54055206/100994897-0dec0100-3592-11eb-93bb-8e3dfb1c99ef.png)

**Comment by v-xianya** [comment]
Verified this issue on build main/20201204.1.  Fixed.
