### ISSUE TITLE
Subscriptions not visible in Explorer, but selected on Accounts Page

### ISSUE THREAD

**Issue by MichelZ** [microsoft/AzureStorageExplorer#384]
**Storage Explorer Version**: 1.2
**Platform/OS Version**:  Windows 10 1803 - x64
**Architecture**: ia32
**Regression From**: No

#### Steps to Reproduce: ####
1. Add a couple of accounts
2. Select all subscriptions in all accounts
3. Navigate to the Explorer where you can see the subscriptions

#### Expected Experience: ####
All subscriptions that have been selected on the Accounts page are visible

#### Actual Experience: ####
Only subscriptions from a couple of accounts are visible (2 accounts out of 4)

The list of subscriptions loads successfully on the Manage Accounts page.

**Comment by MRayermannMSFT** [comment]
Hey @MichelZ , can you please do the following?

1. Open the dev tools (F12)
2. Go to the "Application" tab
3. Expand the "Local Storage" node in the tree view and click on file://
4. Find the row with Key StorageExplorer.AzureSubscriptionsManager.subscriptionCache
5. Double click on the value of that row, and paste it somewhere where you can make it easier to read (I would suggest using a [JSON formatting website](https://jsonformatter.curiousconcept.com/) to do this, but if you are worried about your info getting stolen, you can just use your text editor)
6. Go through the data and make sure all your subscriptions are there, and that the ones you have selected in the account panel all have `"selected":true`. 
7. Let me know what you find.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
