### ISSUE TITLE
[Visual requirements - ADF - Azure data factory] Controls are getting disappeared after resizing to 200% Azure data factory window.

### ISSUE THREAD

**Issue by Shalini3457** [microsoft/AzureStorageExplorer#3844]
**User Experience:**
User will find difficulty to interact with the control if that control is getting disappeared as user won't get the actual UI and also will miss the functionality of such control.

**Test Environment:**
Application Version: 1.16.0-dev
Build Number: 20200921.1

**Pre-Requisite:**
- Set to 200% from System Display-> Advance system settings.
- Navigate to the storage expoler.exe and select it. 

**Repro Steps:​**
- Launch Azure Storage Explorer app.
- Navigate and select Add data factory control at left panel.
- Now, navigate to various control like Account, Subscription, etc. on Azure data factory window.
- Verify each control after resizing to 200%.

**Actual Result:**
Controls(Account, Subscription, etc.) are getting disappeared after resizing the screen to 200% on Azure support page and due to user won't be see such control and won't be interact with that control too.

**Expected Result:**
Controls(Account, Subscription, etc.) should not get disappeared after resizing the screen to 200% on Azure support page so that user could easily interact with such control.

![MAS1 4 4_Azure data factory](https://user-images.githubusercontent.com/72871089/101138429-2e6d9700-3636-11eb-9492-e188451a55e7.png)

**Comment by albertli-msft** [comment]
> Regarding this one, I believe we already have it fixed by putting a scroller bar aside since v0.1.4 and could close it.

![image](https://user-images.githubusercontent.com/69623692/109247752-693f2f80-781f-11eb-8a1d-559ccdd82171.png)

**Comment by MRayermannMSFT** [comment]
Our part in fixing this ended up being fixing the disappearing vertical divider bug.
