### ISSUE TITLE
The existing files/directories of original file share are deleted after renaming it with snapshots

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#385]
**Storage Explorer Version**: 1.3.0 
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180704.1
**Commit**: 865aab62
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Go to Subscription -> Storage Accounts.
2. Open one file share -> Upload one file/directory at least -> Create snapshot for the file share.
3. Rename the file share(Display error in Activities window) ->Check the items on the original file share.

#### Expected Experience: ####
The existing files/directories of original file share still display.

#### Actual Experience: ####
The existing files/directories of original file share are deleted.

#### More info: ####
This issue doesn't reproduce when directly deleting the file share with snapshots.

**Comment by v-xianya** [comment]
Verified on the latest build 20190614.7. This issue also reproduces.

**Comment by v-xianya** [comment]
This issue still reproduces on build 20191204.2.

**Comment by v-xianya** [comment]
Rename for one file share has been replaced with 'Clone with New Name'. So we close it.
