### ISSUE TITLE
All blob's metadata keys are displayed and saved in lowercase. 

### ISSUE THREAD

**Issue by koljada** [microsoft/AzureStorageExplorer#3856]
**Storage Explorer Version**: 1.16
**Build Number**: 20201109.5
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  I'm not sure, but it was working fine recently

## Bug Description ##
All blob's metadata keys are displayed and saved in lowercase. 

## Steps to Reproduce ##
1. Create a blob with metadata which contains entry with uppercase characters. I was using C# SDK or azure portal. 
2. Find that blob in the explorer.
3. Open properties for that blob.
4. Observe: metadata keys are in lowercase. However, in the azure portal they are displayed correctly.

## Expected Experience ##
Metadata properties are displayed and saved as they are.

## Actual Experience ##
Metadata properties are displayed and saved in lowercase.

**Comment by MRayermannMSFT** [comment]
@koljada there is no guarantee that the casing of metadata will be preserved. Blob metadata are simply HTTP headers so you should treat them case insensitively.

See here: https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-properties-metadata?tabs=dotnet#set-and-retrieve-metadata

**Comment by pharring** [comment]
@MRayermannMSFT you're (probably) _technically_ correct, but Storage Explorer differs from the Azure Portal experience when viewing blob metadata (as the OP stated).

The relevant part from the doc you cited is:
> Metadata names maintain the case used when they were created
and we're just asking that Storage Explorer preserves the casing too.

Would you reconsider?

**Comment by jinglouMSFT** [comment]
Let's re-evaluate in our next triage.

**Comment by MRayermannMSFT** [comment]
@pharring you leave off an important part of the sentence from your quote:

> but are case-insensitive when set or read

And above that it says:

> should be treated as case-insensitive.

From what we understand, when you are reading your metadata, you shouldn't be expecting a specific casing.

We just tested the behavior though and we are seeing what you are seeing. We'll ask the JS SDK team if they can be consistent with the other tools/languages.

**Comment by MRayermannMSFT** [comment]
I'm still going to open the SDK issue, but do not get your hopes up. Based on what I have found this is not likely to be fixed. But I'll keep my fingers crossed just in-case.

**Comment by MRayermannMSFT** [comment]
Just kidding, I'm not going to create a new V12 SDK issue. It seems they've had two issues which have gone over this already. If someone feels strongly about this issue though, then feel free to go create a new issue in that repo.

Existing issues:
- https://github.com/Azure/azure-sdk-for-js/issues/8117
- https://github.com/Azure/azure-sdk-for-js/issues/4966

**Comment by pharring** [comment]
Thanks for reconsidering. I made the comment [here](https://github.com/microsoft/AzureStorageExplorer/issues/2573#issuecomment-802231319) that Storage Explorer users don't care about deficiencies in the Azure SDK for JS -- nor should they.

bugsinspace

**Comment by jeremymeng** [comment]
@MRayermannMSFT while we cannot fix this in our core library when our underlying Http stack only returns header keys in lower case, I believe I found a workaround using a custom Http Client.  Could you take a look to see if it's usable in your case? https://github.com/Azure/azure-sdk-for-js/issues/8117#issuecomment-853259040
