### ISSUE TITLE
The opened dialog doesn't follow the mouse when dragging it to anywhere

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#386]
**Storage Explorer Version**: 1.3.0 
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180704.1
**Commit**: 865aab62
**Regression From**:Previous release 1.2.0(20180604.2)

#### Steps to Reproduce: ####
1. Go to Subscription -> Storage Accounts.
2. Open any of dialogs like 'Connect File Share to VM'.
3. Drag the opened dialog to anywhere.

#### Expected Experience: ####
The opened dialog will follow the mouse.

#### Actual Experience: ####
The opened dialog doesn't follow the mouse when dragging it
![drag](https://user-images.githubusercontent.com/34729022/42316690-f7bb4ba8-8039-11e8-9d17-371d723ad522.png)

**Comment by MRayermannMSFT** [comment]
@v-xuanzh , how consistently did this repro for you? Was it actually on all 3 platforms? I am unable to repro. See attached image.
![dragdialog](https://user-images.githubusercontent.com/21112697/42334655-b1916ac4-8032-11e8-829e-67eaf1f41e0d.gif)

**Comment by v-xuanzh** [comment]
Hi Matthew, It seems that was related to machines. I tried again on another machine using the same build, but it doesn't reproduce. Clould you help to resolve it with 'Not repro'?

**Comment by MRayermannMSFT** [comment]
Sure thing! Closing as no repro.
