### ISSUE TITLE
some file was locked and cannot be removed

### ISSUE THREAD

**Issue by zhuzeyuan** [microsoft/AzureStorageExplorer#3861]
**Storage Explorer Version**: doesn't matter
**Build Number**: doesn't matter
**Platform/OS**: doesn't matter
**Architecture**: doesn't matter
**Regression From**:  doesn't matter

## Bug Description ##
![image](https://user-images.githubusercontent.com/6199078/101314024-85c56000-380c-11eb-9670-374758180fab.png)
****

## Steps to Reproduce ##
simply try to delete that file yourself. Only this file is locked; all other files are okay.

## Expected Experience ##
file cannot be deleted.

## Actual Experience ##
file cannot be deleted

## Additional Context ##
n/a

**Comment by MRayermannMSFT** [comment]
@zhuzeyuan what do you mean by locked? Would you be willing to share the AzCopy log file with us? You can find it either:

- clicking on "Go to AzCopy Log File" in the activities panel (if you haven't closed storage explorer)
- going to "<your user folder>/.azcopy" and finding the log file for the operation you were having to do

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having problems please open a new issue.
