### ISSUE TITLE
It is best to adapt the size of the 'Propagation Access Control List' dialog to its content

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3862]
**Storage Explorer Version**: 1.16.0
**Build Number**: 20201206.2
**Branch**: main
**Platform/OS:** Windows 10
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Create a new folder.
3. Right click the folder -> Click 'Propagate Access Control Lists...'.
4. Check whether the size of the 'Propagation Access Control List' dialog is adaptive to its content.

## Expected Experience ##
The size of the 'Propagation Access Control List' dialog is adaptive to its content.

## Actual Experience ##
The size of the 'Propagation Access Control List' dialog isn't adaptive to its content.
![image](https://user-images.githubusercontent.com/54055206/101335504-40f50400-38b4-11eb-856b-ac03593bcf63.png)

## Additional Context ##
This issue doesn't reproduce on Linux & Mac.
![image](https://user-images.githubusercontent.com/54055206/101332890-e312ed00-38b0-11eb-970a-f532f15c35fb.png)

**Comment by MRayermannMSFT** [comment]
Dialog was made bigger as of build #20201208.6
