### ISSUE TITLE
It would be better to remove the action 'Propagate Access Control Lists…' for ADLS Gen2 files other than disable it

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3864]
**Storage Explorer Version**: 1.16.0
**Build Number**: 20201206.2
**Branch**: main
**Platform/OS**: Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Right click the blob -> Observe its context menu.
4. Check there is no action 'Propagate Access Control Lists...'.

## Expected Experience ##
It would be better to remove the action 'Propagate Access Control Lists...'.

## Actual Experience ##
There is an action 'Propagate Access Control Lists...'.
![image](https://user-images.githubusercontent.com/41351993/101337792-1193c680-38b7-11eb-9858-0775054c8b6e.png)

**Comment by MRayermannMSFT** [comment]
@v-xianya going to won't fix this. Doing what you suggest would not be consistent. See "generate shared access signature" in blob containers as an example.

This action is only enabled when a single blob is selected. If you select multiple things or a folder though, then it is still in the context menu, but disabled.
