### ISSUE TITLE
The path of the target folder is not specified in the 'Propagate Access Control List' dialog 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3865]
**Storage Explorer Version**: 1.16.0
**Build Number**: 20201206.2
**Branch**: main
**Platform/OS**: Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one folder.
3. Right click the folder -> Click the 'Propagate Access Control Lists...'.
4. Observe the prompted dialog -> Check whether the path of the target folder is specified. 

## Expected Experience ##
The path of the target folder is specified.

## Actual Experience ##
The path of the target folder is not specified.
![image](https://user-images.githubusercontent.com/41351993/101338059-6cc5b900-38b7-11eb-861a-8ad122696cf0.png)

**Comment by MRayermannMSFT** [comment]
Fixed as of build #20201208.6
