### ISSUE TITLE
Disable the action 'Propagate Access Control Lists…' when there is no data available in ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3866]
**Storage Explorer Version**: 1.16.0
**Build Number**: 20201206.2
**Branch**: main
**Platform/OS**: Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Right click the note 'No data available in this blob container'.
3. Observe the context menu -> Check whether the action 'Propagate Access Control Lists...' is disabled or not.

## Expected Experience ##
The action 'Propagate Access Control Lists...' is disabled.

## Actual Experience ##
The action 'Propagate Access Control Lists...' is enabled.
![image](https://user-images.githubusercontent.com/41351993/101339488-7b14d480-38b9-11eb-857b-78888299e166.png)

**Comment by MRayermannMSFT** [comment]
Fixed as of #20201209.5

**Comment by v-xianya** [comment]
Verified this issue on build 20201209.5. Fixed.
