### ISSUE TITLE
Search doesn't work across multiple pages

### ISSUE THREAD

**Issue by DiptiChauhan** [microsoft/AzureStorageExplorer#3867]
**Storage Explorer Version**: 1.11.1
**Build Number**: 
**Platform/OS**: Windows 10
**Regression From**:  

## Bug Description ##
Search not working in ADLS Gen1, when you have multiple pages and have a file that start with G, search does not find any files with G, you need to go to the pages that have files beginning with G to find the file.

**Comment by DiptiChauhan** [comment]
To do with ticket: https://github.com/microsoft/AzureStorageExplorer/issues/3699

ADLS Gen1
Explorer version 1.11.1

Windows 10

**Comment by jinglouMSFT** [comment]
The retirement of ADLS Gen1 is now less than three months away. As [previously announced](https://azure.microsoft.com/en-us/updates/action-required-switch-to-azure-data-lake-storage-gen2-by-29-february-2024/) the service will be retired on 29 February 2024. With this date now close approaching we are going to close this issue as "won't fix". Documentation on how to migrate your data to ADLS Gen2/blob storage can be found here: https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-migrate-gen1-to-gen2-azure-portal

If you have any non ADLS Gen1 feedback for Storage Explorer, please feel free to open a new issue: https://github.com/microsoft/AzureStorageExplorer/issues/new/choose

This issue will now no longer be monitored.
