### ISSUE TITLE
Unable to create SAS token on storage explorer for objects

### ISSUE THREAD

**Issue by prensoni0143** [microsoft/AzureStorageExplorer#3869]
When creating SAS token for Objects on storage explorer on Mac, it isn't able to right click onn Objects under blob to create SAS token but on portal and windows, object-level SAS token can be created.
Resulting URL generated on MAC storage explorer doesn't work.

Error:
<Error>
<Code>AuthenticationFailed</Code>
<Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:02648e6c-f01e-009a-2f0c-cde31b000000 Time:2020-12-08T02:48:19.9842391Z</Message>
<AuthenticationErrorDetail>Signature did not match. String to sign used was rl 2020-12-07T08:42:28Z 2020-12-08T08:42:28Z /blob/sqlvatlzxwebks5i3m/$root 2019-12-12 c </AuthenticationErrorDetail>
</Error>

**Comment by JasonYeMSFT** [comment]
@prensoni043 Are you trying to generate the SAS for a blob in a regular blob container or an ADLS Gen2 blob container? We don't support generating SAS for ADLS Gen2 blobs for now. I know that portal supports it but there should be no difference between our Windows and Mac version. Let me know if you can see the "generate SAS" action in context menu from our Windows version but not on Mac for the same regular blob.

Where did you get the sas URL and how are you using it? The error messages suggests you are using a container level SAS to your $root container. On my Mac, I can generate a container sas for a $root container and connect to it.
<img width="318" alt="image" src="https://user-images.githubusercontent.com/39359541/101674496-6fd2bd80-3a0d-11eb-93c7-2b7caf35a130.png">

**Comment by prensoni0143** [comment]
Hi Jason,
I am trying to create SAS for objects under blob container but it doesn't allow right-click, I am not sure if it's regular or ADLS Gen2.
I have verified that windows based storage explorer app can right-click on the object and able to generate SAS url, whereas my Mac is unable to do it.
![1201607572894_ pic](https://user-images.githubusercontent.com/34119534/101720915-c3164000-3ae1-11eb-9be4-eb3848775f2b.jpg)

URL by windows machine:
https://sqlvatlzxwebks5i3m.blob.core.chinacloudapi.cn/jatin-blob/qqqq.png?sv=2019-02-02&st=2020-12-10T03%3A49%3A51Z&se=2020-12-11T03%3A49%3A51Z&sr=b&sp=r&sig=qsIZ7dtn40hwfGhI6qVT6eg3%2FkivhjysXhkeNBYhvlE%3D

**Comment by MRayermannMSFT** [comment]
@prensoni0143 on macOS, can you try using `Shift+F10` to open the context menu?

**Comment by prensoni0143** [comment]
> @prensoni0143 on macOS, can you try using `Shift+F10` to open the context menu?

My Mac keyboard doesn't have F10 but have F0(after F9) and pressing it with Shift or Shift+Fn doesn't happen anything while selecting an object under Storage Account app

**Comment by MRayermannMSFT** [comment]
@prensoni0143 your keyboard doesn't have F10, F11, or F12? What type of keyboard are you using lol? Can you get another keyboard that does have it? 

Can you tell us how you're attempting to do a right click? Are you using a track pad or mouse?

**Comment by prensoni0143** [comment]
> @prensoni0143 your keyboard doesn't have F10, F11, or F12? What type of keyboard are you using lol? Can you get another keyboard that does have it?
> 
> Can you tell us how you're attempting to do a right-click? Are you using a trackpad or mouse?

This is how my Macbook Pro keyboard looks. (Right-click by: Ctrl + TouchPad)
![Uploading image.png…]()

**Comment by JasonYeMSFT** [comment]
The keyboard shares the function keys (f1-f12) with utility keys. If you press fn (the left bottom key) + f1-f2 (above the number keys, see the small label), you should be able to use the function keys. For shift + f10, now it will be shift + fn + f10.

**Comment by MRayermannMSFT** [comment]
> Right-click by: Ctrl + TouchPad

Ah! Can you try doing a two finger click instead? I wouldn't be surprised if trying to use Ctrl to right click is broken due the same cause for this bug: https://github.com/microsoft/AzureStorageExplorer/issues/3230

**Comment by MRayermannMSFT** [comment]
Ok. Looked into the root cause more. This isn't related to that bug. But your method of opening context menu is valid:
https://support.apple.com/guide/mac-help/right-click-mh35853/mac
So we should fix this in the future. I'm going to move it to our 1.19 release for now. Until then, please try using two finger click and let us know if that works.

**Comment by prensoni0143** [comment]
> Ok. Looked into the root cause more. This isn't related to that bug. But your method of opening context menu is valid:
> https://support.apple.com/guide/mac-help/right-click-mh35853/mac
> So we should fix this in the future. I'm going to move it to our 1.19 release for now. Until then, please try using two finger click and let us know if that works.

That's perfect, yes it works with 2 finger clicks but not with ctrl + TouchPad
And I can generate SASAccesToken with this.

**Comment by prensoni0143** [comment]
> The keyboard shares the function keys (f1-f12) with utility keys. If you press fn (the left bottom key) + f1-f2 (above the number keys, see the small label), you should be able to use the function keys. For shift + f10, now it will be shift + fn + f10.

Also works the same, thank you :)
