### ISSUE TITLE
(double)-clicking on blob container icon doesn't bring me to the root of container

### ISSUE THREAD

**Issue by KonstantinTr** [microsoft/AzureStorageExplorer#387]
**Storage Explorer Version**:1.2.0
**Platform/OS Version**: Ubuntu 17.10 (LXDE Desktop Environment)
**Architecture**: x64
**Regression From**: The only version I've used
#### Steps to Reproduce: ####
1. Navigate to blob containers
2. Select any container
3. Navigate to any folder within container
4. Click on the parent blob container icon

#### Expected Experience: ####
I expect to be returned to the root of the container (e.g. file explorer tree navigation)

#### Actual Experience: ####
Nothing happens.

**Comment by JasonYeMSFT** [comment]
As for now, if you really want a short cut to go back to the root level of the blob container, you can click the root folder in the address bar (like "container2" in the screenshot).
![image](https://user-images.githubusercontent.com/39359541/42467751-a1af643e-8367-11e8-9521-b4960f96c7ce.png)

**Comment by JasonYeMSFT** [comment]
Closing since this is not a common use case and there is a easy enough workaround.
