### ISSUE TITLE
Make the error details specific when the action 'propagate ACLs...' is failed

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3870]
**Storage Explorer Version**: 1.16.0
**Build Number**: 20201208.7
**Branch**: main
**Platform/OS**: Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one folder which contains files.
3. Add one account which do not has access to the container as the 'owner' for the container by performing manage ACLs action.
4. Then add the account as the 'owner' for the folder in the container.
5. Azure AD attach this blob container by selecting the account.
6. Open the Azure AD attached blob container -> Right click the folder -> Click 'Propagate Access Control Lists...'
7. Check the notification option -> Click 'OK'.
8. Observe the failed activity log -> Click 'Details...' to check whether there are specific error details.
 

## Expected Experience ##
There are specific error details.

## Actual Experience ##
There no specific error details.
![image](https://user-images.githubusercontent.com/41351993/101465274-b1665880-397a-11eb-8fab-65c9793e0ce9.png)

**Comment by MRayermannMSFT** [comment]
Should be fixed as of build #20201209.5

**Comment by v-xianya** [comment]
Verified this issue on build main/20201209.5. Fixed.
![image](https://user-images.githubusercontent.com/41351993/101569320-3c912e00-3a0f-11eb-8339-624d461c6b93.png)
