### ISSUE TITLE
Cannot delete a folder....

### ISSUE THREAD

**Issue by AlejandraLemmo** [microsoft/AzureStorageExplorer#3873]
**Storage Explorer Version**: 1.16.0 and 1.15.0
**Build Number**: 20201109.5
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  yes before 1.15.0

## Bug Description ##
{
  "message": "\"failed to perform remove command due to error: cannot start job due to error: cannot verify resource due to error: -> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/error.go:157\\nHTTP request failed\\n\\nHead https://vapdevretailcomlakesa.dfs.core.windows.net/staging/kp-de/TestCopyActivity?timeout=901: BlankAuthenticationPage\\n.\\n\""
}

**Comment by JasonYeMSFT** [comment]
Update: Sorry I forgot that AzCopy don't log for DFS delete jobs. I'll contact them to see what's behind this error message.

**Comment by AlejandraLemmo** [comment]
Ahh ok, because I couldn't ....

![image](https://user-images.githubusercontent.com/74055699/101678875-d92eec80-3a5e-11eb-9871-c5d98870c68e.png)

**Comment by JasonYeMSFT** [comment]
@AlejandraLemmo is your machine behind a proxy? If you are, if possible, could you please try doing the same thing in public internet? This isn't a typical error that AzCopy or Azure storage returns. A hypothesis is that a proxy intercepts the request and returns that error message.

**Comment by AlejandraLemmo** [comment]
Yes, the computer is behind a proxy but I am sorry I don't have Internet if
I close the proxy, I am wondering if there is a configuration that I can
write the number of the proxy?
like: *Go to "Edit" and select "Configure Proxy" ??*

Thanks

**Comment by JasonYeMSFT** [comment]
Yes, that is the place you can configure the proxy. We only support the most basic type of proxy where you enter the hostname and port to your proxy server, optionally with a username+password authentication. Does your proxy sever accept authentication info in this way?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having problems please open a new issue.
