### ISSUE TITLE
Storage explorer web version fails to load blobs and thorws unhelpful message.

### ISSUE THREAD

**Issue by cloudhubzawsaz** [microsoft/AzureStorageExplorer#3874]
**Storage Explorer Version**: Web Version from console.
**Build Number**: NA
**Platform/OS**:  macOS Catalina
**Architecture**:  x64?
**Regression From**:  NA

## Bug Description ##
Storage explorer web version fails to load storage account and shows cryptic error message

## Steps to Reproduce ##
Browse to a storage account.
Try to open any of the blobs listed.

## Expected Experience ##
The explorer should list blobs in the account.

## Actual Experience ##
The explorer throws unhelpful error message.
![image](https://user-images.githubusercontent.com/69479762/101658802-47fb4e00-3a3d-11eb-8cae-8d7f35f847f8.png)

**Comment by JasonYeMSFT** [comment]
@cloudhubzawsaz We don't own the web version of Storage Explorer. We only have control over the desktop version of Storage Explorer. If possible, please try the desktop version to see if solves your problem. You can download our application from here https://azure.microsoft.com/features/storage-explorer/

**Comment by JasonYeMSFT** [comment]
BTW, if #3875 is what you see after trying our desktop app, let's close this issue and investigate that one there.

**Comment by cloudhubzawsaz** [comment]
Happy to close the issue. Where can I log the issue for the Web version please?

**Comment by JasonYeMSFT** [comment]
The web version is a part of Portal, you can go to https://portal.azure.com and submit a support ticket from the "smile face" button at the top.
<img width="260" alt="image" src="https://user-images.githubusercontent.com/39359541/101673074-8415bb00-3a0b-11eb-8c78-ab408e966649.png">
