### ISSUE TITLE
Azure storage account explorer fails to load blobs with error : Unable to load delete retention policy properties: getaddrinfo 

### ISSUE THREAD

**Issue by cloudhubzawsaz** [microsoft/AzureStorageExplorer#3875]
**Storage Explorer Version**: Version: 1.16.0
**Build Number**: Build Number: 20201109.5 
**Platform/OS**:  macOS Catalina 
**Architecture**:  x64
 
## Bug Description ##
Azure storage account explorer fails to load blobs with error: Unable to load dlete retention policy properties: getaddrinfo ENOTFOUND

## Steps to Reproduce ##
Open storage explorer
Browse to any given blob under a storage explorer.

## Expected Experience ##
The storage explorer should load blobs in the account.

## Actual Experience ##
Azure storage account explorer fails to load blobs with error: Unable to load dlete retention policy properties: getaddrinfo ENOTFOUND
<img width="1584" alt="image" src="https://user-images.githubusercontent.com/69479762/101664059-4fbdf100-3a43-11eb-98bc-4ee15735bb36.png">

**Comment by JasonYeMSFT** [comment]
The error message indicates that the storage account you are accessing cannot be found, which may be due to:
- The storage account is deleted
- The key you are using has been rotated so it doesn't match the current key of the storage account

Please confirm if any of these applies.

**Comment by cloudhubzawsaz** [comment]
> The error message indicates that the storage account you are accessing cannot be found, which may be due to:
> 
> * The storage account is deleted
> * The key you are using has been rotated so it doesn't match the current key of the storage account
> 
> Please confirm if any of these applies.

The account is very much there are visible on the console. The key is also valid.

**Comment by JasonYeMSFT** [comment]
This error also sometimes occur due to unconfigured proxy settings. Are you behind a proxy?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having problems please open a new issue.
