### ISSUE TITLE
The 'Queue endpoint' text box is editable in the 'Attach with SAS URI' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3877]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20201210.6
**Branch**: rel/1.17.0
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Previous build (20201208.7) 

## Steps to Reproduce ##
1. Launch Storage Explorer -> Open connect dialog.
2. Click 'Use a shared access signature (SAS) URI' -> Observe the prompted dialog.
3. Check whether the 'Queue endpoint' text box is not editable.

## Expected Experience ##
The 'Queue endpoint' text box is not editable.
![image](https://user-images.githubusercontent.com/41351993/101733550-067ca880-3afa-11eb-9c6a-8f37b2636100.png)

## Actual Experience ##
The 'Queue endpoint' text box is editable.
![image](https://user-images.githubusercontent.com/41351993/101733485-ee0c8e00-3af9-11eb-8c87-c8b585f2591d.png)

**Comment by MRayermannMSFT** [comment]
Fix merged to rel branch
