### ISSUE TITLE
There is a typo 'accesss' in 'Release Notes -> New -> ADLS Gen2' part

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3878]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20201210.6
**Branch**: rel/1.17.0
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04 / MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Open Storage Explorer -> Click 'Help -> View Release Notes'.
2. Observe the ADLS Gen2 part in the New section.
3. Check there is no typo.

## Expected Experience ##
There is no typo.

## Actual Experience ##
There is a typo 'accesss' in the 'recursive accesss control list (ACL) APIs'.
![image](https://user-images.githubusercontent.com/41351993/101734618-8c4d2380-3afb-11eb-8299-9bf5281564db.png)

**Comment by MRayermannMSFT** [comment]
Fix merged to rel branch
