### ISSUE TITLE
The 'Users, groups and service principals' part is invisible in the 'Manage Access' dialog of one folder which name is too long

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3879]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20201210.6
**Branch**: rel/1.17.0
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04 / MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Previous build (20201209.5)

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Create a folder with a name is long enough.
3. Right click the folder -> Click 'Manage Access Control Lists...'.
4. Observe the contents in the prompted dialog.

## Expected Experience ##
The 'Users, groups and service principals' part is visible.
![image](https://user-images.githubusercontent.com/41351993/101739473-860e7580-3b02-11eb-935b-2dd380db9cc4.png)

## Actual Experience ##
The 'Users, groups and service principals' part is invisible.
![image](https://user-images.githubusercontent.com/41351993/101742513-77758d80-3b05-11eb-83a2-202f0f9861da.png)

## Additional Context ##
This issue also reproduces on one ADLS Gen2 blob which name is long enough.

**Comment by MRayermannMSFT** [comment]
Fix merged to rel branch
