### ISSUE TITLE
Transfer of '<any file name> failed: error: UnexpectedQuit (used Azure AD, discovery not completed)

### ISSUE THREAD

**Issue by kfroe** [microsoft/AzureStorageExplorer#3881]
I cannot upload any file, I always get the above error.  I CAN create folders.  How do I fix this?

**Comment by MRayermannMSFT** [comment]
@kfroe what OS are you on and what version of Storage Explorer?

Additionally, if you download AzCopy v10 separately and try to run the upload on the command line does it work? You can get a copy of the command storage explorer is using by clicking "Copy AzCopy Command to Clipboard".

Please try the command twice, once exactly as it is copied to your clipboard, and again with an additional argument: `--output-type=json`.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having problems please open a new issue.
