### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by rohits2000** [microsoft/AzureStorageExplorer#3884]
Unable to retrieve child resources.

Details:
Network timeout error: connect ECONNREFUSED 127.0.0.1:10002

**Comment by guywou** [comment]
having the same issue.  Can't connect to my subscription resources since yesterday...

**Comment by JasonYeMSFT** [comment]
@rohits2000 There are two possible reasons for this error
1. The local emulator is not running
2. Something else is using the same port on localhost

@guywou The error message above is for accessing local storage emulator, not subscription on Azure cloud. Could you please open a separate issue explaining your issue instead?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having problems please open a new issue.
