### ISSUE TITLE
The action 'Copy'  is enabled in the context menu when selecting one blob and its blob snapshots

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3886]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20201210.19
**Branch**: rel/1.17.0
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04 / MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Previous release(1.15.1)

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload a blob to it -> Create snapshots for the blob.
3. Select the blob and its blob snapshots under 'Manage Snapshot' view.
4. Observe the context menu.
5. Check whether the action 'Copy' is disabled or not.

## Expected Experience ##
The action 'Copy' is disabled in the context menu.

## Actual Experience ##
The action 'Copy' is enabled in the context menu.
![image](https://user-images.githubusercontent.com/54055206/101871109-f29a7a80-3bbd-11eb-8261-5eb41621c2bb.png)

## Additional Context ##

1. This issue doesn't reproduce in the toolbar.
![image](https://user-images.githubusercontent.com/54055206/101871118-f5956b00-3bbd-11eb-9637-c8c998bb0afa.png)

2. This issue doesn't reproduce for one ADLS Gen2 blob container.

**Comment by MRayermannMSFT** [comment]
Fix merged into rel branch
