### ISSUE TITLE
Cannot connect to the deployed blob storage module in IoT Edge

### ISSUE THREAD

**Issue by JoshuaRoi** [microsoft/AzureStorageExplorer#3887]
**Storage Explorer Version**: v1.5
**Build Number**:  20181026.3
**Platform/OS**: Linux Ubuntu/ Windows 10
**Architecture**:  x64

I'm working on Blob Storage module in IoT edge and after deployment, I need to create a container manually with the help of Azure Storage Explorer but I can't access the deployed local blob storage. 
![image](https://user-images.githubusercontent.com/66566030/101908902-bb48bf80-3bf7-11eb-90ab-c3d05858d7ed.png)

I've provisioned a windows 10 vm and an ubuntu server vm, and tried followed the docs in deploying an blob storage in iot edge. 
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-store-data-blob?view=iotedge-2018-06

I used this as the connection string but still no luck.
DefaultEndpointsProtocol=http;BlobEndpoint=http://<host device name>:11002/<your local account name>;AccountName=<your local account name>;AccountKey=<your local account key>;
I used the VM's IP in host device name.

**Comment by wvangeem** [comment]
I have the same problem using Storage Explorer. Using this connection string:
DefaultEndpointsProtocol=https;BlobEndpoint=http://192.168.31.153:11002/blobaccount;AccountName=blobaccount;AccountKey=6YF7UgUsGDmmtYsVS2CTXAJPeQ1ZsuyM/BM2U9FXft4wmkcpnLIdYhZv7Advtw9+SbABqmqSkRcsqRBSpJC1uQ==
I get the error: The value for one of the HTTP headers is not in the correct format

I have the same error when connecting through C# when Azure.Storage.Blobs package 12.7.0
The Connection string is refused.
If I add "UseDevelopmentStorage=true" to the connection string in c#, the validation passes, but still not able to connect.

Looking for this problem for hours.

**Comment by JasonYeMSFT** [comment]
@wvangeem I redacted the IP address and the account key in the connection string. Not sure if it is critical since it is in local storage but just in case.

And could you try v1.14? we have seen people running into a similar issue https://github.com/microsoft/AzureStorageExplorer/issues/3160

**Comment by JoshuaRoi** [comment]
i tried using v1.14 but the error still persist. any more tips? thank you

**Comment by JoshuaRoi** [comment]
![image](https://user-images.githubusercontent.com/66566030/102051588-c1b98000-3e1f-11eb-98b5-ec2741874cc6.png)
the black line is the IP of my VM

**Comment by wvangeem** [comment]
Hi, I tried with v1.14.0 and I succeeded in connecting.
@JoshuaRoi I first had the same error message as you, but my address was incorrect (the one you greyed out).
Check if it's reachable, and firewall is not blocking 11002.
@JasonYeMSFT  I have now the same problem with NuGet Azure.Storage.Blobs 12.7.0, refusing the connection string and when adding the UseDevelopmentStorage=true option it passes, but giving also the HTTP error. I suspect I will also have to downgrade to an older package.

**Comment by JoshuaRoi** [comment]
> Hi, I tried with v1.14.0 and I succeeded in connecting.
> @JoshuaRoi I first had the same error message as you, but my address was incorrect (the one you greyed out).
> Check if it's reachable, and firewall is not blocking 11002.
> @JasonYeMSFT I have now the same problem with NuGet Azure.Storage.Blobs 12.7.0, refusing the connection string and when adding the UseDevelopmentStorage=true option it passes, but giving also the HTTP error. I suspect I will also have to downgrade to an older package.

What address did you used? I configured the networking settings in azure and added ICMP protocol so I can ping the VM.
and how do you check if the firewall is not blocking 11002? Thank you in advanced

**Comment by wvangeem** [comment]
@JoshuaRoi You should use the ip-adress that you can ping.
In my case http://192.168.31.153:11002/blobaccount. Try if you can "browse" to it with a browser. You will get an error of cause, but not the fact that it is unreachable.
In your comment I notice you are using an Azure VM. You should configure the Azure firewall of the VM in the Azure portal AND the firewall inside the VM. For Ubuntu the command is `sudo ufw status`. If it's disabled, then you only should configure Azure Firewall.

**Comment by JoshuaRoi** [comment]
> @JoshuaRoi You should use the ip-adress that you can ping.
> In my case http://192.168.31.153:11002/blobaccount. Try if you can "browse" to it with a browser. You will get an error of cause, but not the fact that it is unreachable.
> In your comment I notice you are using an Azure VM. You should configure the Azure firewall of the VM in the Azure portal AND the firewall inside the VM. For Ubuntu the command is `sudo ufw status`. If it's disabled, then you only should configure Azure Firewall.

Thank you so much, for anyone that gets the same problem as mine: I just added the port 11002 in VM>Networking>Add inbound port rule

**Comment by MRayermannMSFT** [comment]
Thanks for helping each other out! :)
