### ISSUE TITLE
Keep the timestamps formats consistent for one file share snapshot between in the editor and Activities

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3890]
**Storage Explorer Version:** 1.17.0
**Build Number:** 20201211.10
**Branch:** rel/1.17.0
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture:** ia32/x64
**Regression From:** Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Create a snapshot for the file share -> Click 'View Share Snapshots'.
3. Check the timestamps formats of the file share snapshot in the editor and Activities.
4. Check whether the timestamps are consistent.

## Expected Experience ##
 The timestamps are consistent.

## Actual Experience ##
The timestamps are inconsistent.
![image](https://user-images.githubusercontent.com/41351993/102055518-f597a400-3e25-11eb-9337-61d5348e80ab.png)

## Additional Context ##
This issue also reproduces for ADLS Gen2 blobs.
![image](https://user-images.githubusercontent.com/41351993/102055845-6c34a180-3e26-11eb-82a5-496eeaf39e29.png)

**Comment by JasonYeMSFT** [comment]
I also updated the snapshot dropdown for file share to use the raw snapshot id for display.

**Comment by v-xianya** [comment]
@JasonYeMSFT 
1.This issue is fixed for file share.
2.This issue also reproduces for ADLS Gen2 blobs.
![image](https://user-images.githubusercontent.com/41351993/104534858-066b4d80-5650-11eb-9cd2-2dbbbb8bb4f4.png)

**Comment by v-xianya** [comment]
Verified this issue on build 20210127.3. Fixed.
