### ISSUE TITLE
The SAS attached blob container doesn't automatically display on the tree view

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3896]
**Storage Explorer Version:** 1.17.0
**Build Number:** 20201216.1
**Branch:** main
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture:** ia32/x64
**Regression From:** Previous releases (1.17.0) 

## Steps to Reproduce ##
1. Expand one storage account ->Blob Containers.
2. Create a blob container -> Attach the blob container via SAS.
3. Check whether the attached blob container automatically displays on the tree view.

## Expected Experience ##
 The attached blob container automatically displays.

## Actual Experience ##
The attached blob container doesn't automatically display.

## Additional Context ##
1. The attached blob container displays after manually refreshing.
2. This issue also reproduces for one SAS attached ADLS Gen2 blob container.

**Comment by craxal** [comment]
This error occurs in CloudExplorerActions in `se-blob-extension` when attempting to reference a `value` property on a `isHnsEnabled` attribute that isn't found.

@JasonYang-MSFT I'm passing this to you, as you've been doing work in this area.

**Comment by JasonYeMSFT** [comment]
Fix to this issue will be included as a part of migrating our local SAS attachments to use V2 connection data type.

**Comment by v-xianya** [comment]
Verified this issue on build main/20201218.3. Fixed.
