### ISSUE TITLE
The 'Display name' text box is not filled after pasting one queue SAS that created by one access policy to 'Attach with SAS URI' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3897]
**Storage Explorer Version:** 1.17.0
**Build Number:** 20201216.1
**Branch:** main
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture:** ia32/x64
**Regression From:** Previous releases (1.16.0) 

## Steps to Reproduce ##
1. Expand one storage account ->Queues.
2. Create one queue -> Right click the queue -> Click 'Manage Stored Access Policies...'.
3. Add one access policy and save it.
4. Right click the queue -> Click 'Get Shared Access Signature...' -> Select the access policy from the Access policy drop down list -> Create and copy the SAS URI.
5. Open connect dialog -> Select 'Use a shared access signature (SAS) URI' -> Click 'Next'.
6. Paste the copied SAS URI to the URI text box.
7. Check whether the 'Display name' text box is filled or not.

## Expected Experience ##
 The 'Display name' text box is filled.

## Actual Experience ##
The 'Display name' text box is not filled.
![image](https://user-images.githubusercontent.com/41351993/102322923-c6666b80-3fba-11eb-8945-c7a011e81ecb.png)

## Additional Context ##
1. The generated SAS URI is the same as in the previous release.
2. The 'Queue endpoint' textbox is not filled.

**Comment by v-limu** [comment]
Verified on build 20201219.2. This issue has been fixed. So close it.
