### ISSUE TITLE
No error icon shows when typing an illegal character to one queue name

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3899]
**Storage Explorer Version:** 1.17.0
**Build Number:** 20201216.1
**Branch:** main
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture:** ia32/x64
**Regression From:** Previous releases (1.13.1) 

## Steps to Reproduce ##
1. Expand one storage account ->Right click the node 'Queues' -> Click 'Create Queue'.
2. Type three legal characters then type one illegal character (like: 'que;').
3. Check whether an error icon shows.

## Expected Experience ##
An error icon shows.
![image](https://user-images.githubusercontent.com/41351993/102326003-d08a6900-3fbe-11eb-9eee-753deba86cc3.png)

## Actual Experience ##
No error icon shows.
![image](https://user-images.githubusercontent.com/41351993/102325996-cec0a580-3fbe-11eb-8b92-3cdb6e7eefaa.png)

## Additional Context ##
1. This issue occurs when typing illegal characters after there are three legal characters.
2. Failed to create the queue with the name 'que;'.
![image](https://user-images.githubusercontent.com/41351993/102323919-172a9400-3fbc-11eb-9cea-fe034752c89f.png)

Error details:
`  "name": "RestError",
  "message": "The specifed resource name contains invalid characters.\nRequestId:b6332bce-c003-0010-3d88-d3d55c000000\nTime:2020-12-16T08:48:30.1281868Z",`

**Comment by v-xianya** [comment]
Verified this issue on build 20201218.3. Reproduce.

**Comment by JasonYeMSFT** [comment]
I have updated the missing package.

**Comment by v-limu** [comment]
Verified on build 20201219.2. This issue has been fixed. So close it.
![image](https://user-images.githubusercontent.com/54055206/102743720-e1afde80-430c-11eb-8284-8390cb8877a7.png)
