### ISSUE TITLE
Release Notes Doesn't Take Focus

### ISSUE THREAD

**Issue by JakeRadMSFT** [Microsoft/AzureStorageExplorer#39]
**Storage Explorer Version: 1.0.0 RC2**

**OS Version: Windows**

**Steps to Reproduce:**
1.Try to tab into Release Notes

**Expected Experience:**
Can tab into release notes.
**Actual Experience:**
Can't :(

**Comment by MRayermannMSFT** [comment]
You can tab into the release notes now. Unfortunately web views are little bit buggy when it comes to force focusing elements in them, so clicking on the tab does not set focus into the editor reliably.
