### ISSUE TITLE
Remove the 'Access Tier/Access Tier Last Modified' columns for GPV1/classic/premium account

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#390]
**Storage Explorer Version**: 1.3.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180706.1
**Commit**: 99a0e75f
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Go to subscription -> Storage Accounts.
2. Expand one GPV1 account -> Open one blob container.
3. Check whether 'Access Tier/Access Tier Last Modified' columns display or not.

#### Expected Experience: ####
The 'Access Tier/Access Tier Last Modified' columns don't display.

#### Actual Experience: ####
The 'Access Tier/Access Tier Last Modified' columns display.
![column](https://user-images.githubusercontent.com/34729022/42372274-57fdbb8c-8101-11e8-98db-9615d175669c.png)
#### More info: ####
1. These columns should display well after upgrading to GPV2.
2. No way to upgrade the Classic/Premium accounts, so the two column should remove.

**Comment by craxal** [comment]
We intend to add functionality to configure which columns are visible.
