### ISSUE TITLE
The permissions 'Execute' and 'Ownership' show 'Move' in the 'Connection Summary' dialog after pasting the SAS of one ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3900]
**Storage Explorer Version**: 1.17.0
**Build Number:** 20201216.1
**Branch**: main
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##

1. Expand one ADLS Gen2 account -> Blob Containers.
2. Create a blob container -> Right click it -> Click 'Get Shared Access Signature...'.
3. Check all permissions -> Click 'Create' then copy the URI.
4. Open the connect dialog -> Select 'Use a shared access signature(SAS) URI' -> Paste the URI.
5. Check whether the permissions 'Execute' and 'Ownership' show correctly in the 'Connection Summary' dialog.

## Expected Experience ##
The permissions 'Execute' and 'Ownership' show correctly. 
![image](https://user-images.githubusercontent.com/54055206/102326942-011ed280-3fc0-11eb-8cae-3173f7614033.png)

## Actual Experience ##
The permissions 'Execute' and 'Ownership' show 'Move'.
![image](https://user-images.githubusercontent.com/54055206/102326653-9ff6ff00-3fbf-11eb-94b4-dc28f0520c86.png)

**Comment by v-xianya** [comment]
Verified this issue on build main/20201218.3. Fixed.
![image](https://user-images.githubusercontent.com/41351993/102570335-1875d100-4122-11eb-8b86-d3537b724094.png)
