### ISSUE TITLE
The activity log always keep loading when clicking 'Folder Statistics' action for one blob container

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3901]
**Storage Explorer Version**: 1.17.0
**Build Number:** 20201216.1
**Branch**: main
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Previous release(1.17.0)

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload blobs to it.
3. Click 'Folder Statistics' in the toolbar.
4. Check whether the activity log shows successfully in Activities.

## Expected Experience ##
The activity log shows successfully.

## Actual Experience ##
The activity log always keep loading.
![image](https://user-images.githubusercontent.com/54055206/102327646-fdd81680-3fc0-11eb-8b1d-b692ab784d1a.png)

## Additional Context ##
1. This issue also reproduces when clicking 'Selection Statistics'.
2. This issue also reproduces when clicking 'Properties…' for one ADLS Gen2 folder.
3. This issue also reproduces when clicking 'Manage Access Control Lists...' for one ADLS Gen2 folder.(The dialog doesn't pop up)
4. This issue also reproduces when clicking 'Propagate Access Control Lists...' for one ADLS Gen2 folder.
5. This issue also reproduces after performing 'Move' action in ADLS Gen2 blob containers.

**Comment by v-xianya** [comment]
Verified this issue on build main/20201217.3. Fixed.
