### ISSUE TITLE
The keyword 'Leased' doesn't automatically display next to one Emulator blob container after acquiring lease for it 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3902]
**Storage Explorer Version**: 1.17.0
**Build Number:** 20201216.1
**Branch**: main
**Platform/OS:** Windows 10
**Emulator**: 5.10.0.0
**Architecture**: ia32/x64
**Regression From**: Previous release(1.17.0)

## Steps to Reproduce ##

1. Install and run Emulator -> Launch Storage Explorer.
2. Expand 'Local & Attached' -> Storage Accounts -> (Emulator - Default Ports) (Key) -> Blob Containers.
3. Create a blob container -> Right click it -> Click 'Acquire Lease'.
4. Check whether the keyword 'Leased' automatically display next to the blob container.

## Expected Experience ##
The keyword 'Leased' automatically display.

## Actual Experience ##
The keyword 'Leased' doesn't automatically display.

## Additional Context ##

1. This issue doesn't reproduce after manually refreshing.
2. This issue also reproduces for the action 'Break Lease'.

**Comment by v-limu** [comment]
Verified on build 20201217.3. 

1. The 'Leased' keyword occurs **after waiting 30 seconds** on Emulator.
2. This issue doesn't reproduce on Azurite 3.8.0.

**Comment by craxal** [comment]
@v-limu How long does it take for the activity in the Activity Log to complete? What version of Azurite does this bug reproduce with? Does this reproduce with standard Azure nodes?

**Comment by v-limu** [comment]
Hi @craxal 😊 Verified on build 20201217.3
1. This issue only reproduces for one blob container on Emulator 5.10.0.0. It doesn't reproduce on the standard Azure nodes and Azurite 3.8.0.
![image](https://user-images.githubusercontent.com/54055206/102562345-d80e5700-4111-11eb-829d-5610c2a4e03e.png)
2. The completion time of the activity log takes about 1~2 seconds. **But the 'Leased' keyword doesn't occur immediately**.

**Comment by craxal** [comment]
@v-limu Sounds like it's a problem with Emulator, then. It may be the emulator is actually taking a while to establish the lease.

@MRayermannMSFT @JasonYeMSFT If it's alright with you, I'd like to close this as Won't Fix.

**Comment by MRayermannMSFT** [comment]
I investigated this bug. The slowdown is a result of switching to a newer API to see if HNS is enabled. That API is not supported by the .NET emulator, so it takes time to call the API -> fail -> retry -> fail -> retry -> etc.

@v-xianya based on this, we expect that you may notice other things in the tree view which are now slow for the .NET emulator. If you notice something, check if it is also slow for Azurite and report that in the bug. There is no need however to go looking for these bugs. Thanks!
