### ISSUE TITLE
No error dialog pops up when using an existing specified name to clone one blob folder 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3903]
**Storage Explorer Version**: 1.17.0
**Build Number:** 20201216.1
**Branch**: main
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Previous releases (1.15.1)

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload a folder with the name '**New Folder**'.
3. Upload another folder with the name '**New**'.
4. Right click the folder named '**New Folder**' -> Click 'Clone…' action -> Type character '**New**' -> Click 'Clone'.
5.  Check whether an error dialog pops up.

## Expected Experience ##
An error dialog pops up.
![image](https://user-images.githubusercontent.com/54055206/102325391-0c70fe80-3fbe-11eb-9c8c-f9d63be1d840.png)

## Actual Experience ##

1. No error dialog pops up.
2. Pop up a conflict dialog.

## Additional Context ##

1. This issue doesn't reproduce for one ADLS Gen2 blob folder.
2. This issue doesn't reproduce for one file share.
3. This issue reproduces for the above same folder name format.

**Comment by JasonYeMSFT** [comment]
The blob service isn't returning the exact match as the first item in the response when listing with prefix. It does for Gen2 though.

**Comment by v-xianya** [comment]
Verified this issue on build 20210202.9. Fixed.
