### ISSUE TITLE
The 'Light(default)' theme is always selected in the Theme menu after selecting other themes on Linux

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3906]
**Storage Explorer Version**: 1.17.0
**Build Number:** 20201216.1
**Branch**: main
**Platform/OS**:  Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Launch Storage Explorer.
2. Click 'View' menu -> Click ‘Theme' -> Click 'Dark'.
3. Open the Theme menu again.
4. Check whether the current theme is selected in the Theme menu.

## Expected Experience ##
The current theme is selected in the Theme menu.

## Actual Experience ##

1. The current theme isn't selected in the Theme menu.
2. The 'Light(defalut)' theme is always selected.

![image](https://user-images.githubusercontent.com/54055206/102332105-a177f580-3fc6-11eb-83d1-418e2c08aef0.png)

## Additional Context ##

1. This issue also reproduces after selecting 'High Contrast-Black and 'High Contrast -White'.
2. This issue doesn't reproduce on Windows & Mac.

**Comment by JasonYeMSFT** [comment]
I tried it on my own Ubuntu 18.04 and it does check the correct theme. There is probably a bug in Electron for that OS version.

**Comment by MRayermannMSFT** [comment]
Issue specific to Ubuntu 16. We are unable to fix. Closing.
