### ISSUE TITLE
Unable to create virtual directory with slashes

### ISSUE THREAD

**Issue by yasseriz** [microsoft/AzureStorageExplorer#3908]
Hi, I'm trying to create a virtual directory using storage explorer to host the challenge requests for DNS domain ownership check. I am unable to create a virtual directory for "\.well-known\acme-challenge" as seen in the image below. 

Was wondering if this is by design as I have seen articles where users were able to use this before. Link to an example can be found [here](https://intelequia.com/blog/post/1012/automating-azure-application-gateway-ssl-certificate-renewals-with-let-s-encrypt-and-azure-automation)

![image](https://user-images.githubusercontent.com/14288616/102338330-aa6cc500-3fce-11eb-8bd4-c2412de74bd8.png)

**Comment by JasonYeMSFT** [comment]
We only support using forward slash as delimiter.

**Comment by yasseriz** [comment]
Same problem? Or am I missing something?
![image](https://user-images.githubusercontent.com/14288616/102426533-7a630780-404a-11eb-93d7-5debc42d8b62.png)

**Comment by JasonYeMSFT** [comment]
Which Storage Explorer version are you using? Your dialog seems from an older version. I checked our latest 1.17.0 and the validation seems working fine. 
<img width="613" alt="image" src="https://user-images.githubusercontent.com/39359541/102525838-afbe2400-404f-11eb-9475-2102622b9d4a.png">

**Comment by yasseriz** [comment]
I was using the Storage Explorer feature in the portal which I believe is still in preview. That might be part of the problem. Will use the application and see how it goes. Thank you
