### ISSUE TITLE
Can't display the "Copy Direct Link to Blob Container" after renaming the container name unless refresh

### ISSUE THREAD

**Issue by supervicky42** [Microsoft/AzureStorageExplorer#391]
**Storage Explorer Version**: 1.2.0
**Build Number**: 20180706.1
**Platform/OS Version**: Windows 10
**Build Number**: 20180706.1

#### Steps to Reproduce: ####
1. Randomly pick up one blob container in the SE
2. Rename it
3. After renaming successfully right click on the container

#### Expected Experience: ####
Can see the "Copy Direct Link to Blob Container"

#### Actual Experience: ####
Can't see it unless refresh it

**Comment by MRayermannMSFT** [comment]
Hey  @v-xuanzh , can you take some time and verify if this still repros with 1.4.0? Thanks!

**Comment by v-xuanzh** [comment]
This issue is fixed in 1.4.0. Could you help to resolve it?

**Comment by MRayermannMSFT** [comment]
Yep!
