### ISSUE TITLE
Error logs created by Synapse COPY INTO activity cannot be downloaded using the client tool

### ISSUE THREAD

**Issue by dudu-markovitz** [microsoft/AzureStorageExplorer#3910]
The files could be loaded using the Azure portal Storage Explorer.

2020/12/16 16:35:41 AzcopyVersion  10.7.0
2020/12/16 16:35:41 OS-Environment  windows
2020/12/16 16:35:41 OS-Architecture  amd64
2020/12/16 16:35:41 Log times are in UTC. Local time is 16 Dec 2020 18:35:41
2020/12/16 16:35:41 Job-Command copy https://dumarkovadlsgen2.blob.core.windows.net/dudi/errorsfolder/_rejectedrows/20201216_104011/QID272_10_C.Error.Txt?se=2021-01-15t16%3A35%3A37z&sig=-REDACTED-&sp=rl&sr=c&sv=2019-12-12 C:\Users\dumarkov\Downloads\QID272_10_C.Error.Txt --output-type=json --cancel-from-stdin --overwrite=prompt --check-md5 FailIfDifferent --from-to=BlobLocal --recursive 
2020/12/16 16:35:41 Number of CPUs: 4
2020/12/16 16:35:41 Max file buffer RAM 2.000 GB
2020/12/16 16:35:41 Max concurrent network operations: 32 (Based on number of CPUs. Set AZCOPY_CONCURRENCY_VALUE environment variable to override)
2020/12/16 16:35:41 Check CPU usage when dynamically tuning concurrency: true (Based on hard-coded default. Set AZCOPY_TUNE_TO_CPU environment variable to true or false override)
2020/12/16 16:35:41 Max concurrent transfer initiation routines: 64 (Based on hard-coded default. Set AZCOPY_CONCURRENT_FILES environment variable to override)
2020/12/16 16:35:41 Max enumeration routines: 16 (Based on hard-coded default. Set AZCOPY_CONCURRENT_SCAN environment variable to override)
2020/12/16 16:35:41 Parallelize getting file properties (file.Stat): false (Based on AZCOPY_PARALLEL_STAT_FILES environment variable)
2020/12/16 16:35:41 Max open files when downloading: 2147483224 (auto-computed)
2020/12/16 16:35:41 ISO 8601 START TIME: to copy files that changed after this job started, use the parameter --include-after=2020-12-16T16:35:32Z
2020/12/16 16:35:41 Any empty folders will not be processed, because source and/or destination doesn't have full folder support
2020/12/16 16:35:41 Final job part has been created
2020/12/16 16:35:41 PERF: primary performance constraint is Unknown. States: C:  0, R:  0, W:  0, F:  0, H:  0, B:  0, S:  0, P:  0, Q:  0, D:  0, E:  0, T:  0, GRs:  0
2020/12/16 16:35:41 0.0 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total, 
2020/12/16 16:35:41 JobID=e979bd19-10d8-0741-5a63-7122bbabea14, credential type: Anonymous
2020/12/16 16:35:41 scheduling JobID=e979bd19-10d8-0741-5a63-7122bbabea14, Part#=0, Transfer#=0, priority=0
2020/12/16 16:35:41 Final job part has been scheduled
2020/12/16 16:35:41 INFO: [P#0-T#0] has worker 45 which is processing TRANSFER
2020/12/16 16:35:41 ==> REQUEST/RESPONSE (Try=1/318.9916ms, OpTime=634.0021ms) -- RESPONSE SUCCESSFULLY RECEIVED
   GET https://dumarkovadlsgen2.blob.core.windows.net/dudi/errorsfolder/_rejectedrows/20201216_104011/QID272_10_C.Error.Txt?se=2021-01-15t16%3A35%3A37z&sig=-REDACTED-&sp=rl&sr=c&sv=2019-12-12&timeout=901
   X-Ms-Request-Id: [3b931c53-501e-0061-7fc9-d384b3000000]

2020/12/16 16:35:41 ERR: [P#0-T#0] DOWNLOADFAILED: https://dumarkovadlsgen2.blob.core.windows.net/dudi/errorsfolder/_rejectedrows/20201216_104011/QID272_10_C.Error.Txt?se=2021-01-15t16%3A35%3A37z&sig=-REDACTED-&sp=rl&sr=c&sv=2019-12-12 : 000 : the MD5 hash of the data, as we received it, did not match the expected value, as found in the Blob/File Service. This means that either there is a data integrity error OR another tool has failed to keep the stored hash up to date. (NOTE In the specific case of downloading a Page Blob that has been used as a VM disk, the VM has probably changed the content since the hash was set. That's normal, and in that specific case you can simply disable the MD5 check. See the documentation for the check-md5 parameter.). When Checking MD5 hash. X-Ms-Request-Id: 

   Dst: %5C%5C?\C:\Users\dumarkov\Downloads\QID272_10_C.Error.Txt
2020/12/16 16:35:41 INFO: [P#0-T#0] https://dumarkovadlsgen2.blob.core.windows.net/dudi/errorsfolder/_rejectedrows/20201216_104011/QID272_10_C.Error.Txt?se=2021-01-15t16%3A35%3A37z&sig=-REDACTED-&sp=rl&sr=c&sv=2019-12-12 Deleting incomplete destination file Dst: %5C%5C?\C:\Users\dumarkov\Downloads\QID272_10_C.Error.Txt
2020/12/16 16:35:41 JobID=e979bd19-10d8-0741-5a63-7122bbabea14, Part#=0, TransfersDone=1 of 1
2020/12/16 16:35:41 all parts of entire Job e979bd19-10d8-0741-5a63-7122bbabea14 successfully completed, cancelled or paused
2020/12/16 16:35:43 PERF: primary performance constraint is Unknown. States: C:  0, R:  0, W:  0, F:  0, H:  0, B:  0, S:  0, P:  0, Q:  0, D:  0, E:  0, T:  0, GRs: 32

**Comment by JasonYeMSFT** [comment]
@dudu-markovitz If the error is false alarm, you can try disabling the MD5 hash check from "Settings -> Transfers -> AzCopy -> Check MD5" and select No Check or Log only. That should unblock you from this error. If the file does get corrupted, then the error is expected.

**Comment by dudu-markovitz** [comment]
Yep. That did the work.
We still need to understand if the MD% hash check is problematic or there is something wrong with the files (which might be related to the ADLS gen 2 API)

David (דודו) Markovitz
Sr. Cloud Solution Architect, Data & AI      Mobile: +972-525-834-304
Microsoft Israel                                              Office: +972-747-119-274

[cid:image001.png@01D6D453.39F240C0]

**Comment by MRayermannMSFT** [comment]
@dudu-markovitz the MD5 hash is meant to be updated by any tools interacting with the data. So try to think about any tooling that touches your data and check to see if they are all doing MD5 updates. By default, storage explorer (really azcopy), will put/update the MD5 when modifying blobs. So I don't think we're the responsible ones. But if you investigate and think that we are, please let us know! Since this immediate issue is fixed, I'll close it. Feel free to open another if you think there's an issue with Storage Explorer not updating the MD5 hash. Thanks!
