### ISSUE TITLE
The ‘Queue endpoint’ text box is auto filled when changing the value of 'sr' in one file's SAS URI on 'Attach with SAS URI' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3913]
**Storage Explorer Version:** 1.17.0
**Build Number:** 20201217.3
**Branch:** main
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture:** ia32/x64
**Regression From:** Previous releases (1.16.0) 

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Upload one file.
3. Right click the file -> Click 'Get Shared Access Signature...' -> Create the SAS and copy it.
4. Open connect dialog -> Select 'Use a shared access signature (SAS) URI' -> Paste the URI.
5. Update the value of 'sr' from 'f' to 's' in the URI.
6. Check the 'Queue endpoint' text box is empty.

## Expected Experience ##
The 'Queue endpoint' text box is empty.

## Actual Experience ##
The 'Queue endpoint' text box is filled.
![image](https://user-images.githubusercontent.com/41351993/102465009-165f3400-4088-11eb-8092-1866b98bef6d.png)

## Additional Context ##
This issue also reproduces when changing the value of 'sr' in one blob's SAS URI.

**Comment by JasonYeMSFT** [comment]
Similar issue to #3897, will be fixed together with that one.

**Comment by v-xianya** [comment]
Verified this issue on build main/20201222.1. Fixed.
