### ISSUE TITLE
The value of the property 'HNS Enabled' is 'false' for one SAS attached ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3915]
**Storage Explorer Version:** 1.17.0
**Build Number:** 20201218.3
**Branch:** main
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture:** ia32/x64
**Regression From:** Previous build (20201217.3) 

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Attach it via SAS.
3. Observe the properties of the attached ADLS Gen2 blob container.
4. Check the value of the property 'HNS Enabled'.

## Expected Experience ##
The value of the property 'HNS Enabled' is true.

## Actual Experience ##
The value of the property 'HNS Enabled' is false.

## Additional Context ##
The attached ADLS Gen2 blob show as a Non-HNS blob container.

**Comment by JasonYeMSFT** [comment]
I updated the missing package.

**Comment by v-limu** [comment]
Verified on build 20201219.2. This issue has been fixed. So close it.
