### ISSUE TITLE
No context menu occurs when right clicking one blob/ folder in a blob container's editor

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3916]
**Storage Explorer Version:** 1.17.0
**Build Number:** 20201218.3
**Branch:** main
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture:** ia32/x64
**Regression From:** Previous build (20201217.3) 

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob -> Right click the blob .
3. Check whether the context menu occurs.

## Expected Experience ##
The context menu occurs.

## Actual Experience ##
No context menu occurs.

## Additional Context ##
1. This issue also reproduces when right clicking one item in a file share's editor.
2. This issue also reproduces when right clicking one entity in a table's editor.

**Comment by v-xianya** [comment]
Verified this issue on build main/20201222.1. Fixed.

**Comment by tansaku** [comment]
I seem to be getting this same issue in 

Version: 1.30.0
AzCopy Version: 10.19.0

Platform: macOS
Architecture: x64 
Build Number: 20230609.2 
Commit: 8d5719a5ab 
Support ID: 48608a58-811a-ea5b-80a6-ea638d0fa2ef 

on OSX 12.6.3 (21G419)
