### ISSUE TITLE
The created queue is focused under the SAS attached storage account after creating one queue under the original storage account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3917]
**Storage Explorer Version:** 1.17.0
**Build Number:** 20201218.3
**Branch:** main
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture:** ia32/x64
**Regression From:** Previous release (1.13.1) 

## Steps to Reproduce ##
1. Select one storage account -> Attach the storage account via SAS.
2. Expand the original storage account -> Queues -> Create a queue.
3. Check whether the created queue is focused under the original storage account.

## Expected Experience ##
The queue under the original storage account is focused.

## Actual Experience ##
The queue under the SAS attached storage account is focused.

## Additional Context ##
This issue doesn't reproduce for one blob container/ file share/ table.

**Comment by JasonYeMSFT** [comment]
In "QueueServiceActions", if multiple service nodes matches the new created queue, `addCloudExplorerNode` will add it to all such service nodes and set focus to the first added queue node among all of them. Let's re-triage and determine if we want to
- Only add queue node to the service node that create is executed on
- Figure out which new node is under the service node that create is executed on

**Comment by MRayermannMSFT** [comment]
We should keep adding to all valid service nodes, but, we should use the node id which is sent during the invocation of the action to correctly associate the right added node.

**Comment by craxal** [comment]
The problem appears to be an easy fix, but I've been having trouble reproducing it. My guess is Cloud Explorer returns nodes in an undefined order.

**Comment by v-xianya** [comment]
Verified this issue on build 20210218.1 Fixed.
