### ISSUE TITLE
A loading icon always shows in the editor of one SAS attached file share 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3918]
**Storage Explorer Version:** 1.17.0
**Build Number:** 20201218.3
**Branch:** main
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture:** ia32/x64
**Regression From:** Previous build (20201217.3)

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Attach the file share via SAS.
3. Check the Properties panel of the attached file share.

## Expected Experience ##
The properties show correct.
![image](https://user-images.githubusercontent.com/41351993/102597575-d36b9200-4155-11eb-8d99-ba470b2492e3.png)

## Actual Experience ##
1. Miss the property 'Shared Access Signature'.
2. Show an incorrect value '/' for the property 'URL'.
![image](https://user-images.githubusercontent.com/41351993/102597636-e9795280-4155-11eb-98ee-0f1636f04e55.png)

## Additional Context ##
Always show a loading icon in the auto opened file share's editor.
![image](https://user-images.githubusercontent.com/41351993/102599035-e2534400-4157-11eb-8800-838b9d9d955d.png)

**Comment by JasonYeMSFT** [comment]
I did find a bug causing problem with loading files. However, I cannot reproduce the problem where the properties are incorrectly. If you can still reproduce this issue, could you share a sas url that you can use to reproduce the issue?

**Comment by v-xianya** [comment]
@JasonYeMSFT 
Try to reproduce this issue on build main/20201219.2
1. The properties issue doesn't reproduce, the attached file shares properties show correctly now.
2. The loading issue reproduces.

**Comment by v-xianya** [comment]
Hi @JasonYeMSFT 
I updated the title of this bug in order to track it specifically.

**Comment by v-xianya** [comment]
Verified this issue on build 20210120.8. Fixed.
