### ISSUE TITLE
[Loc] Assistance with Translation

### ISSUE THREAD

**Issue by cristianosuzuki77** [microsoft/AzureStorageExplorer#3919]
.|  .
-- | --
String Resource ID | 0; "BlobStatisticsActiveStateActivityText"
Source String | Calculating statistics in %1$s: %2$s items inspected
Filename | loc\en\src\components\se-blob-extension\resources\BlobContainerActions.json
Question | What will the placeholder %1$s be replaced with? This query also applies to the following ResIDs: 0; "BlobStatisticsCanceledActivityText" 0; "BlobStatisticsExitStateMessageFailedToInspect" 0; "BlobStatisticsExitStateNoErrorsActivityText" 0; "BlobStatisticsExitStateYesErrorsActivityText"

**Comment by cristianosuzuki77** [comment]
vcq 346699

**Comment by JasonYeMSFT** [comment]
The %1$s will be replaced with the resource path that the "get statistics" action is applied on.
- If applied on a single blob, it will be `${accountName}/${containerName}/${blobPath}`
- If applied on a single directory, it will be `${accountName}/${containerName}/${directoryPath}`
- If applied on multiple items, it will be `${accountName}/${containerName}/Multiple items`

**Comment by cristianosuzuki77** [comment]
Thank you.
