### ISSUE TITLE
Ability to add local storage account to Quick Access

### ISSUE THREAD

**Issue by davidgruar** [Microsoft/AzureStorageExplorer#392]
**Storage Explorer Version**: 1.2.0

#### Steps to Reproduce: ####
1. Navigate to (Local and Attached) > Storage Accounts > Development
2. Right-click on Development

#### Expected Experience: ####
It would be useful to be able to add the development storage account to Quick Access, to avoid having to navigate several levels deep.

#### Actual Experience: ####
No option to add to Quick Access. (Conversely, it is possible to add a local Cosmos DB database.)

**Comment by MRayermannMSFT** [comment]
Thanks for the feature request @davidgruar ! We'll take a look into making this possible with an upcoming refresh of our Local and Attached feature areas.
