### ISSUE TITLE
Storage explorer issue when accessing ADLS containers

### ISSUE THREAD

**Issue by madanmohansatna** [microsoft/AzureStorageExplorer#3921]

**Comment by JasonYeMSFT** [comment]
Could you please describe at which step are you encountering the issue and what the issue is?

**Comment by madanmohansatna** [comment]
Hi,

I am successfully logged in and when expanding blob container, I am
getting the following error

**Comment by JasonYeMSFT** [comment]
The picture cannot be posted through phone. You can login to Github in a browser to post the picture.

**Comment by MRayermannMSFT** [comment]
Also, please clarify if this is for ADLS Gen1 or Gen2, and let us know your storage explorer version and what OS you are on. Thanks.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of followup. If you are still having this problem, then please open a new issue. Thanks!
