### ISSUE TITLE
Connectivity Issue with Storage Container 

### ISSUE THREAD

**Issue by xfzhang1974** [microsoft/AzureStorageExplorer#3922]
I recently keep running into connectivity issue with azcopy, either programmatically or with Azure Storage Explorer.
{
  "message": "\"failed to perform remove command due to error: cannot start job due to error: cannot verify resource due to error: -> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/error.go:154\\nHTTP request failed\\n\\nHead https://xxxxxxxxxxx.dfs.core.windows.net/YYYYYYYY/ZZZZZ.json?timeout=901: read tcp X.X.X.X:XX->X.X.X.X:XX wsarecv: An existing connection was forcibly closed by the remote host.\\n.\\n\""
}
Not sure if it is with the bandwidth or vpn or else.
I can browse the folder content of blob storage account, but cannot download | delete | copy & paste.

**Comment by JasonYeMSFT** [comment]
Maybe the vpn is running some inspection on the request we sent and for some reason it "rejects" the requests for transfers. A good way to debug is to try the same steps without vpn and see if it works. If you cannot access internet without the vpn, you can  use a local network debugging tool (e.g. Fiddler) to log the network traffic and see which entity is "rejecting" the request. I found a pretty good blob describing how to setup Fiddler for this [Fiddler setup](https://www.chrisjohnson.io/2017/10/06/sniffing-azure-storage-explorer-traffic/). You also need to configure Fiddler to forward its requests to your vpn.

**Comment by xfzhang1974** [comment]
Will try Fiddler. Thank you.

**Comment by xfzhang1974** [comment]
Jason, it turns out that my coworker using Mac is still be able to download the exact same file with Azure Storage Explorer over the same vpn connection. The issue I run into could not be Windows specific, isn't? 
On the other hand, I has recently leveraged azure.storage.blob.sharedaccesssignature lib to programmatically generate sas token to be used to bulk load files to blob storage. Is there any limit on how many sas tokens could be generated and if so, how may I clean up? Many Thanks.

sas = BlobSharedAccessSignature(az_acct_name, az_acct_key)
    c_sas = sas.generate_container (
        container_name=az_container_name,
        permission=ContainerPermissions(read=True, write=True, list=True),
        start=datetime.now(tz=pytz.utc),
        expiry= datetime.now(tz=pytz.utc) + timedelta(days = 1)
    )

**Comment by xfzhang1974** [comment]
Never mind. It seems what I run into is a known issue with Windows 10. https://github.com/microsoft/AzureStorageExplorer/issues/2553
