### ISSUE TITLE
Error while expanding Blob Containers node

### ISSUE THREAD

**Issue by SavinPrakash** [microsoft/AzureStorageExplorer#3926]
![image](https://user-images.githubusercontent.com/76483861/102897042-268b6080-4446-11eb-8e5e-6c52f7039b00.png)

**Comment by JasonYeMSFT** [comment]
Some entity in the network route is refusing the connection. Could you check the IP address 20.38.102.68 to see what it is? If it is a proxy server, you'll need to make sure that port 443 is the correct port and make sure you have configured the proxy setting and credentials in Storage Explorer. Let us know if it is something else.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of followup. If you are still having this problem, then please open a new issue. Thanks!
