### ISSUE TITLE
Authentication with Device Code  Flow doesnt logging

### ISSUE THREAD

**Issue by poudigne** [microsoft/AzureStorageExplorer#3929]
![image](https://user-images.githubusercontent.com/704541/103037976-2c16a280-453b-11eb-963f-d99d8deb6cbf.png)

## Bug Description ##
I am having issue loggin in to Azure Storage Explorer for some unknown reason, the logging windows becomes blank (I have 2FA activated on my work account). So, after reading a bit. I saw that I could activate the Device Code Flow to log in. I tried it, but when I logged in, Azure Storage Explorer does nothing.... I tried logging in using FireFox, Edge and Edge Incognito mode. Nothing. ASE would never do anything.

## Steps to Reproduce ##
1- Activate Device Code Flow
2- Try logging in with an account that has 2FA activated.

## Expected Experience ##
well, Figured that I would end up being logged in.

## Actual Experience ##
The window with the link and the code still show and nothing happen.

## Additional Context ##
Work account, activate directory, two factor authentication. I don't know enough about AAD to tell you more.

**Comment by JasonYeMSFT** [comment]
@poudigne I can reproduce this issue on one of my personal account. I am not sure how this happens since we haven't touched this code path for a while. I will contact our identity service team to figure out what happened.

**Comment by JasonYeMSFT** [comment]
BTW, could you try enabling Microsoft Authentication Library (another setting under the Sign-in category) without device code flow to see if it works?

**Comment by poudigne** [comment]
> @poudigne I can reproduce this issue on one of my personal account. I am not sure how this happens since we haven't touched this code path for a while. I will contact our identity service team to figure out what happened.

This might help.. I came back the day after and I was logged In...I don't know how or why.

**Comment by poudigne** [comment]
@JasonYeMSFT I logged in today and had the same issue. However, the app popped an update, updated it and checked the MAL settings you asked me to try. I logged in using the code, and when I got back in Azure Storage Explorer the popup had disappear and I was logged in. I don't know what fixed the issue, however. But it worked. Thanks.
