### ISSUE TITLE
Not able to create blob container using Azure storage explorer

### ISSUE THREAD

**Issue by payalgaikwad42** [microsoft/AzureStorageExplorer#3930]
Hi, 
I have deployed azure blob storage as a azure iotedge module on windows machine with linux container.
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-store-data-blob?view=iotedge-2018-06

IoT Edge version : 1.0.10.2
I am using azure storage explorer 1.14.0 to connect to local account using connection string. I am successfully connected to local account but not able to create blob container in local storage account . It fails with error: 

> Failed to create blob container.
> 
> Details:
> Server encountered an internal error. Please try again after some time.
> RequestId:4a9e45d4-bbe4-4126-9be8-df3b7f2b4473
> Time:2020-12-24T05:04:27.5361186Z

I have previously downloaded ;latest version of azure storage explorer 1.17.0 but encountered same issue. It was failing to create local blob container with error: "one of the header format is incorrect". thats why I downgraded the version. 

connection string is: "DefaultEndpointsProtocol=http;BlobEndpoint=http://gb9qmwt2e:11002/myaccount;AccountName=myaccount;AccountKey=qeNvPfS0pgzmqFcVnONiUQUI8U6AqNR6xtOkRkmg+c1wXagvL4pn5nuJuR6lN/ipqrNBUIqJTbo6eo15mVdSnA==;"

can anyone please guide me to the right version of azure storage explorer?

**Comment by payalgaikwad42** [comment]
Image 1: azure storage explorer says unable to upload the image
![image](https://user-images.githubusercontent.com/42204123/103064275-adbd0d80-45d9-11eb-8c56-ed9c7d72101f.png)

image 2: I can see the image in directory which I have mentioned in bind option in azure iotedge deployment
![image](https://user-images.githubusercontent.com/42204123/103064296-ba416600-45d9-11eb-8b52-581585466ad5.png)

**Comment by payalgaikwad42** [comment]
The log file for upload blob to local container is as follow:
[a5c0ac98-d5fc-314d-454c-e06e828d0786.log](https://github.com/microsoft/AzureStorageExplorer/files/5763198/a5c0ac98-d5fc-314d-454c-e06e828d0786.log)

**Comment by payalgaikwad42** [comment]
Is there anyone from Microsoft who can help me look into this ?

**Comment by MRayermannMSFT** [comment]
@payalgaikwad42 so to clarify, you are using Storage Explorer version 1.14.0 right? Also, if you'd like to try with even older versions, you can download those here: https://github.com/microsoft/AzureStorageExplorer/releases

**Comment by MRayermannMSFT** [comment]
Also, since this is Blob IoT, do you have access to any log files from that? It does look like this is indeed a server issue.

**Comment by payalgaikwad42** [comment]
> The log file for upload blob to local container is as follow:
> [a5c0ac98-d5fc-314d-454c-e06e828d0786.log](https://github.com/microsoft/AzureStorageExplorer/files/5763198/a5c0ac98-d5fc-314d-454c-e06e828d0786.log)

these are the logs from local blob container which azure storage explorer generates.

**Comment by payalgaikwad42** [comment]
update on this issue:  with version 1.14 I am able to create blob container in azure storage  explorer and upload empty txt file to local container. but as soon as I try to upload txt file with some content azure storage explorer throws error as follow:
[3d898a10-46d1-2545-4bad-fb6d0a625e4e.log](https://github.com/microsoft/AzureStorageExplorer/files/5768176/3d898a10-46d1-2545-4bad-fb6d0a625e4e.log)

**Comment by JasonYeMSFT** [comment]
@payalgaikwad42 It may be related to the API version of the request. Could you try copying the AzCopy command and add an environment variable to specify a lower api version? 

AZCOPY_DEFAULT_SERVICE_API_VERSION = previous_version
You can find previous versions here. https://docs.microsoft.com/en-us/rest/api/storageservices/previous-azure-storage-service-versions

**Comment by payalgaikwad42** [comment]
With azure storage explorer version 1.14 and azure iotedge blob storage image with tag "1.4-linux-amd64" this is working fine.

Thank you!
