### ISSUE TITLE
In Dark theme, the cosmosDb filter query editor text color does not change on mouse hover which makes the text invisible

### ISSUE THREAD

**Issue by merajkhateeb** [microsoft/AzureStorageExplorer#3931]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20201211.10
**Platform/OS**: Windows 10
**Architecture**: ia32
**Regression From**:  Not sure. Installed this version only

## Bug Description ##
In Dark theme, the cosmosDb filter query editor text color does not change on mouse hover which makes the text invisible

## Steps to Reproduce ##
1. Goto Setting and select Dark Theme
2. Open any cosmos db and click on Documents under that 
3. Click on filter which will display a text field
4. enter some filter criteria in the text field (or just enter any text)
5. Mouse hover the text field and observe the text which you had entered in the text field

## Expected Experience ##
The text entered in the text field should be visible and readable when hovered

## Actual Experience ##
The text entered in the text field is invisible and NOT readable when hovered

## Additional Context ##

![AzureStorageExplorer-Issue](https://user-images.githubusercontent.com/48912622/103067886-f24ca700-45e1-11eb-8391-e0c9d286ed42.png)

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
