### ISSUE TITLE
Update the tooltip of the icon 'Select All' from 'Select all entities' to 'Select all items' in a file share's toolbar

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3936]
**Storage Explorer Version:** 1.17.0
**Build Number:** 20201222.4
**Branch:** main
**Platform/OS:** ia32/x64
**Architecture:** Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina 
**Regression From:** Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Hover over the 'Select All' icon in the toolbar.
3. Check the tooltip.

## Expected Experience ##
The tooltip shows 'Select all items'.
![image](https://user-images.githubusercontent.com/41351993/103130231-c19a6980-46d6-11eb-847f-6f8424a61389.png)

## Actual Experience ##
The tooltip shows 'Select all entities'
![image](https://user-images.githubusercontent.com/41351993/103130233-c5c68700-46d6-11eb-81c4-a20ccb219599.png)

**Comment by MRayermannMSFT** [comment]
Checked in, waiting for strings to update before publishing new ext version

**Comment by MRayermannMSFT** [comment]
Fix merged into main
