### ISSUE TITLE
It is hard to see the dropdown arrow in 'Access Policies' dialog under 'Dark' theme

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3937]
**Storage Explorer Version:** 1.17.0
**Build Number:** 20201222.4
**Branch:** main
**Platform/OS:** ia32/x64
**Architecture:** Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina 
**Regression From:** Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Change the theme to 'Dark'.
2. Expand one storage account -> Right click a blob container and click 'Manage Access Policies...'. 
3. Click 'Add' button and focus on dropdown arrow under Start time in 'Access Policies' dialog.
4. Check whether it is clear to see the dropdown arrow.

## Expected Experience ##
It is clear to see the dropdown arrow.
![image](https://user-images.githubusercontent.com/41351993/103201607-3d8cef80-492b-11eb-98a7-891b649c8d74.png)

## Actual Experience ##
It is hard to see the dropdown arrow.
![image](https://user-images.githubusercontent.com/41351993/103200547-960ebd80-4928-11eb-93d8-732b898849be.png)

## Additional Context ##
1. This issue also reproduces on 'High Contrast - Black' theme.
2. This issue also reproduces for 'Shared Access Signature' dialog.
3. The TFS bug [401218](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/401218).

**Comment by v-limu** [comment]
Verified on build 20210426.5. The time tool has been changed. So this issue doesn't reproduce.
![image](https://user-images.githubusercontent.com/54055206/116220453-8bf7a280-a701-11eb-886a-bba8e8d98abb.png)
