### ISSUE TITLE
Don't pop up the "Connect to Azure Storage" dialog by default

### ISSUE THREAD

**Issue by atrauzzi** [microsoft/AzureStorageExplorer#3938]
**Is your feature request related to a problem? Please describe.**
When I run Azure Storage Explorer, it's mainly to connect to a local emulator (azurite) which is running using the default development connection string/credentials.

This means that the following entry is already sufficient:
![image](https://user-images.githubusercontent.com/115199/103242463-dca9eb00-491b-11eb-9476-c7549f0f393f.png)

**Describe the solution you'd like**
Don't pop this window up on startup:
![image](https://user-images.githubusercontent.com/115199/103242409-aec4a680-491b-11eb-897f-0093f720e175.png)

After it's been shown once, it should be permanently suppressed for all future launches, regardless of whether a connection is configured or not.

**Describe alternatives you've considered**
N/A

**Additional context**
I get that there's a desire to offer a first-run experience, but to have this dialog pop up every time the app opens even after being dismissed the first time is annoying.  I have no reason to configure a connection because the one I want is already available in the list.

**Comment by MRayermannMSFT** [comment]
@atrauzzi thanks for this feedback. You make a really good point. We'll look into exposing turning off the behavior with a setting.

**Comment by atrauzzi** [comment]
@MRayermannMSFT - Mm, please note: It should automatically disable after the first run.

Requiring a setting is just as bad as requiring someone configure a connection to disable it.

At the very worst, it should have a "don't show again" button.  But honestly, forcing the dialogue for a singular add operation based an assumption of the user's intent for opening the application is definitely a UX antipattern in the first place...

**Comment by MRayermannMSFT** [comment]
@atrauzzi how would you feel about a checkbox in the dialog that says something like "auto open on start if no connections exist", and then you could turn that off. Like this:
![image](https://user-images.githubusercontent.com/21112697/144104779-86cc1122-3aa9-4338-bdbb-d95f2802aa46.png)

**Comment by atrauzzi** [comment]
Not showing the dialog is best.  But obviously just making the behaviour possible is always nice.

**Comment by JasonYeMSFT** [comment]
In 1.25.0 we added our own Getting Started panel, like the VSCode one in the screenshot above. In the Getting Started panel there is a checkbox that allows you to dismiss the panel so that it won't show up.
