### ISSUE TITLE
The value of the property 'ContentMD5' is editable for a file under one file share

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3940]
**Storage Explorer Version:** 1.17.0
**Build Number:** 20201222.4
**Branch:** main
**Platform/OS:** ia32/x64
**Architecture:** Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina 
**Regression From:** Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Upload a file.
3. Right click the file then open its Properties dialog.
4. Check whether the value of the property 'ContentMD5' is editable.

## Expected Experience ##
The value of the property 'ContentMD5' is not editable.

## Actual Experience ##
The value of the property 'ContentMD5' is editable.
![image](https://user-images.githubusercontent.com/41351993/103261424-7cc74900-49dc-11eb-9e4b-81e928772067.png)

## Additional Context ##
1. This issue doesn't reproduce for blobs.
2. TFS bug: [544298](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/544298).
3. Related bug: [2235](https://github.com/microsoft/AzureStorageExplorer/issues/2235).

**Comment by MRayermannMSFT** [comment]
We're going to leave this as is for now, and also not touch similar areas even if they are inconsistent. We'll wait on user feedback to see if people have a preference one way or another for this.
