### ISSUE TITLE
Clicking the opened tab doesn't focus on the corresponding container after refreshing the tree view

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3942]
**Storage Explorer Version:** 1.17.0
**Build Number:** 20201222.4
**Branch:** main
**Platform/OS:** ia32/x64
**Architecture:** Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina 
**Regression From:** Not a regression

## Steps to Reproduce ##
1. Select and expand one storage account.
2. Select one blob container and open it.
3. Refresh the tree view -> Expand the storage account selected in step1 -> Blob Containers.
4. Click the opened container tab and check whether the container on the tree view is focused or not.

## Expected Experience ##
The container on the tree view is focused.

## Actual Experience ##
The container on the tree view is not focused.

**Comment by MRayermannMSFT** [comment]
Expected (for now)/won't fix. If you refresh the tree, associations between nodes and tabs are lost.
