### ISSUE TITLE
Refresh from tree does not refresh editor

### ISSUE THREAD

**Issue by vitomaz-msft** [Microsoft/AzureStorageExplorer#395]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Windows 10
**Architecture**: ia32
**Regression From**: Don't know

#### Steps to Reproduce: ####
1. Right click on blob container and pick Refresh
2. Refresh from right click on the blob container doesn't seem to work

#### Expected Experience: ####
Refresh the blob container contents

#### Actual Experience: ####
Does nothing.

![image](https://user-images.githubusercontent.com/40804779/42506281-58aa240e-8439-11e8-9d77-557990da5b69.png)

**Comment by JasonYeMSFT** [comment]
Currently, refreshing from the blob container node is updating the properties of that blob container at the bottom. Refreshing the editor (in the editor toolbar) handles updating the blob container content.

**Comment by vitomaz-msft** [comment]
Thank you for the clarification, should it be change to 'Refresh properties' or something?

**Comment by craxal** [comment]
I don't know if that's sufficient. The Refresh action on the left-hand side refreshes properties _and_ child nodes.
