### ISSUE TITLE
StorageExplorer.exe - Entry Point Not Found

### ISSUE THREAD

**Issue by roboter** [microsoft/AzureStorageExplorer#3950]
**Storage Explorer Version**: v1.17.0
**Build Number**: v1.17.0
**Platform/OS**: Windows 10
**Architecture**:  x64
**Regression From**:  

## Bug Description ##

downloaded from: https://github.com/microsoft/AzureStorageExplorer/releases/download/v1.17.0/Windows_StorageExplorer.exe

## Steps to Reproduce ##

download
install
[x] run after install checked
got error

\---------------------------
StorageExplorer.exe - Entry Point Not Found
\---------------------------
The procedure entry point av_buffer_create could not be located in the dynamic link library C:\Program Files (x86)\Microsoft Azure Storage Explorer\StorageExplorer.exe. 
\---------------------------
OK   
\---------------------------

## Expected Experience ##
expect app to start

![image](https://user-images.githubusercontent.com/386485/103566312-7b10f000-4eca-11eb-8ec3-b9f0d1df8ca2.png)

**Comment by roboter** [comment]
additional info, I also tried to install slack and get same problem, 
so it is common issue for electron app, but Azure Data Studio is working
Also I did successfully install StorageExplorer on different computer

**Comment by MRayermannMSFT** [comment]
@roboter this isn't an error we haven't really seen before. Likely there is something messed up with your Windows install, related to a .dll that is responsible for this av_buffer_create procedure. We did a quick search for ways to fix it but couldn't find anything. At this point all we can recommend is you reinstall windows, but with additional time spent searching for soluations you might be able to fix this without having to do that.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are continue to have issues please open a new issue. Thanks.
