### ISSUE TITLE
I can´t access to Blob Container

### ISSUE THREAD

**Issue by shadowalker25403** [microsoft/AzureStorageExplorer#3954]

**Comment by MRayermannMSFT** [comment]
@shadowalker25403 can you give us some more information?
- What OS are you on
- What version of storage explorer are you using
- What do you mean by "I can´t access to Blob Container"?
- Are you seeing errors, and if so, what are they?
- Has this worked for you before?
- Have you tried from another machine and/or network?
- Is this issue specific to your account/can others that you know do this successfully?
- Are you behind a proxy and if so have you setup your proxy settings?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are continue to have issues please open a new issue. Thanks.
