### ISSUE TITLE
A folder with the name '&' shows blank in the 'Recent locations' dropdown list

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3955]
**Storage Explorer Version**: 1.17.0
**Build**: 20201222.4
**Branch**: master
**Platform/OS**: Windows 10/ Linux Ubuntu16.04 / MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> File Shares.
2. Create a file share -> Click 'New Folder' -> Input '&' as the new folder name -> Click 'OK'.
3. Open the folder -> Click 'Recent locations'.
4. Check whether the folder name '&' shows in the 'Recent locations' dropdown list.

## Expected Experience ##
The folder name '&' shows well in the 'Recent locations' dropdown list.

## Actual Experience ##
The folder name shows blank in the 'Recent locations' dropdown list.
![image](https://user-images.githubusercontent.com/54055206/103601089-df23ca80-4f43-11eb-9ca0-f64eeacc67e0.png)

**More Info:**
This issue also reproduces for one blob container.

**Comment by craxal** [comment]
Electron folks are updating their documentation. We can escape the & with another &.

**Comment by v-xianya** [comment]
Hi @craxal
Verified this issue on build 20210223.2. There are some problems on this scenario.
We are going to re-open it. Could you help to take a look?

The folder named '&&' show as '&' under the recent locations; 
![image](https://user-images.githubusercontent.com/41351993/108820256-e2a80980-75f6-11eb-928b-cc35e6e04d12.png)

The folder named '&&&&' show as '&&' under the recent locations;
![image](https://user-images.githubusercontent.com/41351993/108820219-d58b1a80-75f6-11eb-9167-9eefeb7520c1.png)

**Comment by craxal** [comment]
Argh! Apparently `String.replace` rather unintuitively replaces the first occurrence of the pattern _unless_ the pattern is a global regular expression. In other words:

```typescript
"&&".replace("&", "&&"); // Returns "&&&", not what we want
"&&".replace(/&/g, "&&"); // Returns "&&&&", which is what we want
```
