### ISSUE TITLE
Unable to sign in an Azure account on Linux 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3958]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20210106.4
**Platform/OS**: Linux Ubuntu18.04 / MacOS Catalina
**Architecture**: ia32
**Regression From**:  Previous release(1.17.0)

## Steps to Reproduce ##

1. Extract 'StorageExplorer-linux-x64.tar.gz' on Linux.
2. Launch Storage Explorer -> Click 'Open Connect Dialog'.
3. Select 'Add an Azure Account -> Azure' -> Sign in an Azure account.
4. Check whether the account sign in successfully.

## Expected Experience ##
The account sign in successfully.

## Actual Experience ##
An error 'Unable to sign in...' shows in Activities.
![image](https://user-images.githubusercontent.com/54055206/103871616-3d010f80-5108-11eb-83b4-9f6cb7f53236.png)
Details:
![image](https://user-images.githubusercontent.com/54055206/103871892-9a955c00-5108-11eb-9a41-358a0141a22e.png)

## Additional Context ##
1. This issue also reproduces on Linux when using 'device code flow sign-in' to sign in.
2. This issue reproduces on Mac when using 'device code flow sign-in' to sign in.
3. This issue doesn't reproduce when signing in an Azure China and Black forest account.

**Comment by v-limu** [comment]
This issue doesn't reproduces after enabling MASL to sign-in.

**Comment by MRayermannMSFT** [comment]
Based on what I've read so far about some new company policies, this is expected.
