### ISSUE TITLE
Erroneous "Subscriptions could not be loaded. Please try reentering credentials"

### ISSUE THREAD

**Issue by dumbledad** [microsoft/AzureStorageExplorer#3960]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20201211.10
**Platform/OS**: Windows 10 (20H2, Build 19042.685)
**Architecture**: x64
**Regression From**:  Not sure

## Bug Description ##
The Azure Storage Explorer claims that:

Subscriptions could not be loaded. Please try reentering credentials or removing and readding the account.

When I re-add the account the same thing happens. If I try to reenter the credentials there are two possible routes:
1) It says "we have sent a notification to your mobile device" but I do not receive one, despite successfully running a test at our phoneregistration site (which does result in an approval prompt on the phone).
2) I am told I can "Use a verification code from my mobile app" but the account in the Android authenticator app has no way to generate a code.

Strangely I *can* still access the storage accounts in my subscriptions. I *can* successfully upload and download data.

## Steps to Reproduce ##
This happens whenever I open the Azure Storage Explorer

## Expected Experience ##
Given that the subscriptions are loading and functioning normally I would not expect to be told that the subscriptions could not be loaded and that I need to re-enter my credentials

## Actual Experience ##
The Azure Storage Explorer claims that:

Subscriptions could not be loaded. Please try reentering credentials or removing and readding the account.

**Comment by MRayermannMSFT** [comment]
Can you try upgrading to at least version 1.19.0, try signing in, and then we can troubleshooting if you're still having issues with that version?

**Comment by dumbledad** [comment]
@MRayermannMSFT, bingo! That worked. Well done and thanks for the fix.
