### ISSUE TITLE
Unable to retrieve child resources.

### ISSUE THREAD

**Issue by Fanna71** [microsoft/AzureStorageExplorer#3962]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20200902.9
**Platform/OS**: 
**Architecture**: 
**Regression From**:  

## Bug Description ##
Unable to retrieve child resources.

Details:
["RestError:﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.\nRequestId:5a43c064-401e-0068-1f99-e5a566000000\nTime:2021-01-08T08:34:17.7750306Z</Message></Error>"]

**Comment by MRayermannMSFT** [comment]
@Fanna71 can you tell us a little bit more about what you are trying to access and how you are accessing it (attach, sign in, etc.)? At what point are you seeing this error? `﻿AuthorizationFailure` typically indicates you do not have the needed permissions to access what you are trying to access.

**Comment by Fanna71** [comment]
Ciao Matthew
It happens when I try to access this:
[cid:image001.png@01D6E8BB.0F213050]
I do not have this problem if I access using portal.azure
[cid:image002.png@01D6E8BB.215DEBA0]
Ciao
F

**Comment by MRayermannMSFT** [comment]
@Fanna71 it looks like you tried so send an image over email. Unfortunately that doesn't work. You'll need to post your response directly on github to successfully attach an image.
