### ISSUE TITLE
The broken Azure AD attached blob container doesn't disappear after detaching it

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3963]
**Storage Explorer Version:** 1.17.0
**Build Number:** 20210106.4
**Branch:** main
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina 
**Architecture:**  ia32/x64
**Regression From:** Previous release (1.14.2)

## Steps to Reproduce ##
1. Select one blob container.
2. Give RBAC access to the blob container 'Blob Data Owner Role'.
3. Attach this blob container via Azure Active Directory (Azure AD).
4. Remove the account associated with the Azure AD attached blob container.
5. Expand Local & Attached node -> (Attached Containers) -> Blob Containers.
6. Right click the broken blob container -> Select 'Detach'.
6. Check whether the blob container disappears from the tree view.

## Expected Experience ##
The blob container disappears.

## Actual Experience ##
The blob container does not disappear.

## Additional Context ##
1. The blob container disappears after manually refreshing the tree view.
2. This issue doesn't reproduce for one Azure AD attached queue.

**Comment by JasonYeMSFT** [comment]
I have tried in our latest build and it doesn't reproduce. Could you please verify in the latest build if this can be reproduced by attaching/detaching? If this only applies to legacy local attachments before 1.14.2, I think this would be won't fix.

**Comment by v-xianya** [comment]
@JasonYeMSFT 
Verified this issue on the latest build 20210112.1. Reproduce.
For an Azure AD attached queue, Not reproduce.
![video](https://user-images.githubusercontent.com/41351993/104263082-cd05d700-54c3-11eb-85ee-d70dc73e29f2.gif)

**Comment by v-xianya** [comment]
Verified this issue on build 20210114.3.  Fixed.
