### ISSUE TITLE
Unable to upload 32GB .tif file.failed 0 items transfered(used SAS discovery completed) 

### ISSUE THREAD

**Issue by mahmood2103015** [microsoft/AzureStorageExplorer#3965]
**Storage Explorer Version**: 1.13.1
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:  

## Bug Description ##
Unable to upload 32GB .tif file in ADLS Gen2 using Storage explorer. Its showing error message, failed 0 items transferred(used SAS discovery completed). Please help me soon to resolve as this is blocker for me.
![S Explorer Issue](https://user-images.githubusercontent.com/76705507/104088368-677bd580-528c-11eb-95f4-a39b41502da1.png)

**Comment by MRayermannMSFT** [comment]
@mahmood2103015 can you please share the AzCopy log file with us? You can get it by clicking on Go To AzCopy Log File. Or, if you have already closed Storage Explorer, you can look in C:\users\your-username\.azcopy for the log file.

Also, since you're still on version 1.13.1, you should also update and try again. AzCopy has been updated quite a bit over the past year.

**Comment by mahmood2103015** [comment]
@MRayermannMSFT Thanks, ill share it soon.

**Comment by mahmood2103015** [comment]
@MRayermannMSFT After upgrading version i am able to upload the file.
Before upgrading version i was getting below mentioned error.
$env:AZCOPY_CRED_TYPE = "Anonymous";
./azcopy.exe copy "C:\Users\amit.kumar07\Desktop\testing_output_4.topo.json" "https://sgidevadls.blob.core.windows.net/data/test/Russia/RU_CHURN_2020_11_30/RAW_DATA/testing_output_4.topo.json?sv=2019-12-12&ss=bfqt&srt=sc&sp=rwdlacupx&se=2021-01-16T18%3A49%3A49Z&st=2021-01-07T10%3A49%3A49Z&spr=https&sig=t%2FGUHcuRNqPvJncQaUCd6oBEanHp1stCeHQTlsbwvlQ%3D" --overwrite=prompt --from-to=LocalBlob --blob-type Detect --follow-symlinks --put-md5 --follow-symlinks --recursive;
$env:AZCOPY_CRED_TYPE = "";

Thanks.

**Comment by MRayermannMSFT** [comment]
@mahmood2103015 what you pasted was the AzCopy command, please share the text from "Go to AzCopy Log File":
![image](https://user-images.githubusercontent.com/21112697/105080147-44e47c00-5a45-11eb-8cdb-9c17b495b81c.png)
