### ISSUE TITLE
Storage Account Explorere can't log into Shared Storage 

### ISSUE THREAD

**Issue by agendT** [microsoft/AzureStorageExplorer#3966]
**Storage Explorer Version**: 1.17.0 (& earlier)
**Build Number**: 20201211.1
**Platform/OS**: Windows 10
**Architecture**: x 64
**Regression From**:   It's working from a copy installed on my AWS WorkSpace (Win10 Server)

## Bug Description ##

Unable to retrieve child resources.

Details:
write EPROTO 199509600:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

## Steps to Reproduce ##
 It applies to all versions running on Azure VMs

Azure Subscription: 3934995f-5453-4366-9227-2e7720ea****
## Additional Context ##

Only thing I could find online referred to a Firewall issue being at the core, but no details given as to how to solve.

**Comment by MRayermannMSFT** [comment]
Maybe similar to 3810?

**Comment by JasonYeMSFT** [comment]
@agendT The error is about an invalid user certificate. Have you imported any user certificate to Storage Explorer? If yes, could you double check if they are correct?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of reply. Please open a new issue if you are still encountering this problem.
