### ISSUE TITLE
It takes about 15 seconds to display the connected public emulator blob container on the tree view

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3967]
**Storage Explorer Version:** 1.17.0
**Build Number:** 20210109.1
**Branch:** main
**Emulator:** Azurite 3.10.0, Microsoft Azure Storage Emulator 5.10.0
**Platform/OS:** Windows 10 
**Architecture:**  ia32
**Regression From:** Previous release (1.17.0)

## Steps to Reproduce ##
1. Install and run 'Microsoft Azure Storage Emulator 5.10.0' -> Open Storage Explorer.
2. Expand the node 'Local & Attached' -> 'Storage Accounts' -> (Emulator - Default Ports) (Key) -> Blob Containers.
3. Create a blob container -> Set its public access level to 'container'.
4. Connect the blob container to public blob container.
5. Observe whether the connected blob container displays on the tree view immediately.

## Expected Experience ##
The connected blob container displays on the tree view immediately .

## Actual Experience ##
It takes about 15 seconds to display the connected public emulator blob container on the tree view. The specific details please see the record.
![record1](https://user-images.githubusercontent.com/41351993/104158861-34227d80-5429-11eb-953a-61c80c0f3dca.gif)

## Additional Context ##
This issue doesn't reproduce when using Azurite 3.10.0.

**Comment by MRayermannMSFT** [comment]
I investigated this bug. The slowdown is a result of switching to a newer API to see if HNS is enabled. That API is not supported by the .NET emulator, so it takes time to call the API -> fail -> retry -> fail -> retry -> etc.

@v-xianya based on this, we expect that you may notice other things in the tree view which are now slow for the .NET emulator. If you notice something, check if it is also slow for Azurite and report that in the bug. There is no need however to go looking for these bugs. Thanks!

**Comment by v-xianya** [comment]
@MRayermannMSFT 
Got it. thanks for the update! if we notice there is something slow on the tree view for the .NET Emulator. we will report it.
