### ISSUE TITLE
Move over remaining Blob actions over to Job Handler pattern for better Errors/Error Details

### ISSUE THREAD

**Issue by JakeRadMSFT** [microsoft/AzureStorageExplorer#397]
#### Expected Experience: ####
Clear Error messages.

#### Actual Experience: ####
Often cryptic or minimally detailed messages in Activity log.

**Comment by beroder** [comment]
The following would be useful to have in the error logs:

1. Time stamp.
2. Server Request ID.
3. HTTP Status code returned from the Azure storage service.
4. Any error message returned from the Azure storage service.
