### ISSUE TITLE
The toolbar of one ADLS Gen1 folder shows blank when opening the folder from 'Quick Access' 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3972]
**Storage Explorer Version:** 1.17.0
**Build Number:** 20210112.1
**Branch:** main
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ MacOS Catalina 
**Architecture:**  ia32/x64
**Regression From:** Previous release (1.17.0)

## Steps to Reproduce ##
1. Expand 'Data Lake Storage Gen1 (Preview)' node -> Open one ADLS Gen1 account.
2. Upload one folder -> Pin the folder to quick access.
3. Navigate to Quick Access -> Right click the pinned folder -> Click 'Open'.
4. Check the toolbar of the opened folder.

## Expected Experience ##
The toolbar shows well.
![image](https://user-images.githubusercontent.com/41351993/104293057-8a122680-54f8-11eb-9394-bd99c4a9996a.png)

## Actual Experience ##
The toolbar shows blank.
![image](https://user-images.githubusercontent.com/41351993/104292826-44edf480-54f8-11eb-94f1-84298ccf613f.png)

**Comment by JasonYeMSFT** [comment]
This may be relevant to the latest toolbar component work.

**Comment by v-xianya** [comment]
Verified this issue on build 20210205.4. Fixed.
