### ISSUE TITLE
An error pops up after attaching one ADLS Gen2 folder via Azure AD

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3973]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20210112.1
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Previous release(1.1.7.0)

## Steps to Reproduce ##

1. Expand one ADLS Gen2 account -> Blob  Containers.
2. Create a blob container -> Upload one folder.
3. Give RBAC access to the blob container 'Blob Data Owner Role'.
4. Attach the ADLS Gen2 folder via Azure AD.
5. Check there is no error.

## Expected Experience ##
No error pops up.

## Actual Experience ##
An error pops up.
![image](https://user-images.githubusercontent.com/54055206/104294865-b3cc4d00-54fa-11eb-84b6-7d8841e8cfac.png)

## Additional Context ##
This issue also reproduces when attaching one ADLS Gen2 folder via SAS.

**Comment by JasonYeMSFT** [comment]
A necessary Cloud Explorer update has been merged today. Could you please verify this issue?

**Comment by v-limu** [comment]
Verified on build 20210113.4. This issue has been fixed. So close it.
