### ISSUE TITLE
High memory usage on upload

### ISSUE THREAD

**Issue by suhrab** [microsoft/AzureStorageExplorer#3974]
**Storage Explorer Version**: 1.16.0
**Build Number**: 20201109.5
**Platform/OS**: Windows 10
**Architecture**: x64

## Bug Description ##
High memory usage when uploading a file to blob storage.
![image](https://user-images.githubusercontent.com/4409852/104411043-d9f1fb80-5593-11eb-9324-93be95eb0507.png)

## Steps to Reproduce ##
I was uploading 6GB file. Storage Explorer memory usage was also about 6GB. After upload completed memory usage decreased to 200MB

**Comment by MRayermannMSFT** [comment]
@suhrab when doing transfers the things being transferred will be read into memory. If you expand the process group for Storage Explorer, you should see that most of the memory usage is coming from AzCopy (the thing doing the transfers).

Ok?

**Comment by JasonYeMSFT** [comment]
If the memory usage is causing problems, please consider tweaking the max buffer size that AzCopy can use. You can configure it at "Settings -> Transfers -> Buffer Size".

**Comment by suhrab** [comment]
@JasonYeMSFT Thanks!!
