### ISSUE TITLE
An error pops up when clicking the blob container's name in the address bar for one SAS attached ADLS Gen2 folder

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3975]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20210113.4
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 account -> Blob Containers.
2. Create a blob container -> Upload one folder.
3. Right click the folder -> Click 'Get Shared Access Signature...'.
4. Select all permissions and copy URI in the 'Shared Access Signature' dialog -> Attach the folder via SAS.
5. Open the SAS attached folder -> Click the blob container's name in the address bar.
6. Check there is no error.

## Expected Experience ##
No error pops up.

## Actual Experience ##
An error pops up.
![image](https://user-images.githubusercontent.com/54055206/104417966-2c8de080-55b1-11eb-99bc-1f34c4031cdd.png)
![ADLS ATTACHED](https://user-images.githubusercontent.com/54055206/104419772-e8e8a600-55b3-11eb-9b28-4bae0c4c2d4c.gif)

## Additional Context ##
This issue doesn't reproduce for one Azure AD attached ADLS Gen2 folder.

**Comment by JasonYeMSFT** [comment]
The user aren't supposed to have access to any directory beyond the directory that is attached. An auth error is expected but there are some service side issue causing a 500 error to be returned.

For Azure AD attached directories, if the user don't have permissions to access parent directories, an error will also pop up.

**Comment by v-limu** [comment]
Thanks your updates. Got it.
