### ISSUE TITLE
Storage service returns 500 error when getting container property with directory scoped SAS

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3976]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20210113.4
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 account -> Blob Containers.
2. Create a blob container -> Upload one folder.
3. Right click the folder -> Click 'Get Shared Access Signature...'.
4. Select all permissions and copy URI in the 'Shared Access Signature' dialog -> Attach the folder via SAS.
5. Open the SAS attached folder -> Paste one blob to it.
6. Check whether the blob is successfully pasted.

## Expected Experience ##
Succeed to paste the blob.

## Actual Experience ##
The activity log always keep loading.
![image](https://user-images.githubusercontent.com/54055206/104417582-9a85d800-55b0-11eb-88f2-23aaf33f22c9.png)

## Additional Context ##
This issue doesn't reproduce for one Azure AD attached ADLS Gen2 folder.

**Comment by JasonYeMSFT** [comment]
There is caused by a storage service bug.

**Comment by MRayermannMSFT** [comment]
Let's disable copy paste, and then move this out to 1.19. We will continue to monitor the service bug and will re-enable paste when it is fixed.

**Comment by MRayermannMSFT** [comment]
Please rename bug after doing that.

**Comment by JasonYeMSFT** [comment]
The root cause of the bug is that the Storage service returns 500 (internal error) when getting container properties. AzCopy attempts to retry on 500 error and thus keep retrying without making any progress.

**Comment by v-xianya** [comment]
Verified this issue on build 20210219.2. Fixed.
'Paste' is disabled for files under one SAS attached ADLS Gen2 directory.
