### ISSUE TITLE
The 'sr' field is 'c' in an ADLS Gen2 blob's SAS URI which generated with access policy

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3978]
**Storage Explorer Version:** 1.17.0
**Build Number:** 20210113.4
**Branch:** main
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ MacOS Catalina 
**Architecture:**  ia32/x64
**Regression From:** Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container and right click it -> Select 'Manage Access Policies...' -> Add one access policy -> Save it.
3. Upload one blob to the blob container -> Right click the blob -> Select 'Get Shared Access Signature...'.
4. Select the access policy in the drop down menu -> Click 'Create'.
4. View the generated SAS URI -> Check whether the 'sr' field is 'b'.

## Expected Experience ##
The 'sr' field is 'b'.

## Actual Experience ##
The 'sr' field is 'c'.
![image](https://user-images.githubusercontent.com/41351993/104432442-fe65cc00-55c3-11eb-90c7-8893d6c9296e.png)

## Additional Context ##
1. This issue also reproduces for one ADLS Gen2 folder.
2. Show the error `The SAS URI path appears to reference a blob. Attaching to blobs or directories is not supported.` when pasting the SAS URI to the 'Attach with SAS URI' dialog, 
![image](https://user-images.githubusercontent.com/41351993/104433277-e0e53200-55c4-11eb-9815-f03d4f421c71.png)

**Comment by JasonYeMSFT** [comment]
Access policy only grants container level access so the sr=c is expected. We should update the warning message.

**Comment by v-xianya** [comment]
@JasonYeMSFT 
Thanks for the update! when we used a stored access policy to creating a blob SAS, 
the 'sr=b' is correct for one regular blob ；the 'sr=c' is expected for one ADLS Gen2 blob.
Could you help to explain why this happens? Thank you！

**Comment by JasonYeMSFT** [comment]
The SDK is missing a similar fix for blob SDK. https://github.com/Azure/azure-sdk-for-js/issues/13223

**Comment by v-limu** [comment]
Verified on build 20210209.6. This issue has been fixed. So we close it.
![image](https://user-images.githubusercontent.com/54055206/107331843-5d98fc80-6aee-11eb-886b-6d272a94ca5c.png)
