### ISSUE TITLE
Clear Cache Button/Reset Storage Explorer Button

### ISSUE THREAD

**Issue by JakeRadMSFT** [microsoft/AzureStorageExplorer#398]
#### Expected Experience: ####
Be able to reset Storage Explorer and clear all cache and settings.

#### Actual Experience: ####
Customer's get into configuration issues or machine issues and it's difficult to get into a clean state.

**Comment by MRayermannMSFT** [comment]
Start with #149

**Comment by JasonYeMSFT** [comment]
It is already there.
