### ISSUE TITLE
Unable to upload files to Blob Storage using Azure Storage Explorer

### ISSUE THREAD

**Issue by everton-o** [microsoft/AzureStorageExplorer#3982]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20201211.10
**Platform/OS**: Windows 10
**Architecture**: i86
**Regression From**:  

## Bug Description ##
Unable to upload data to blob storage or data lake using Azure Storage Explorer. The error message : "error occurred while cancelling the job 28bb3518-a79e-c740-530f-119e067c381e: Can't cancel JobID=28bb3518-a79e-c740-530f-119e067c381e because it has already completed"

## Steps to Reproduce ##
1. Option 1: Drag and drop any file into the Storage Explorer Area
2. Option 2: In the Storage Explorer tool, click on the "upload" button, select a file, the error should appear after the action is "Queued".

## Expected Experience ##
To be able to upload the file to a container

## Actual Experience ##
![image](https://user-images.githubusercontent.com/54533122/104718875-82829580-5723-11eb-84aa-cc9296dd4080.png)

**Comment by MRayermannMSFT** [comment]
@everton-o did you try to cancel the upload or did that message just appear all on its own? Can you share the log file with us? You can click on "Go to AzCopy Log File" to see where the log file is located.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having this problem please open a new issue.
