### ISSUE TITLE
 An error pops up after attaching one ADLS Gen2 folder which name contains spaces

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3984]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20210116.6
**Platform/OS**: Windows 10/ CentOS 7.6.1810 (Core)/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**:  Not a regression

## Steps to Reproduce ##

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a new blob container -> Create a new folder named 'New Folder'.
3. Right click the folder -> Click 'Get Shared Access Signature...' -> Create and copy the 'URI' in the Shared Access Signature dialog.
4. Attach it via SAS -> Check there is no error.

## Expected Experience ##
No error pops up and the folder name shows well.

## Actual Experience ##
An error pops up.
![image](https://user-images.githubusercontent.com/54055206/104890658-d4891c80-59aa-11eb-8f71-2d7da0a2cca1.png)

**Comment by MRayermannMSFT** [comment]
Please make sure this still works for Azure AD scenario as well.

**Comment by v-limu** [comment]
Verified on build 20210209.6. This issue has been fixed. So we close it.
