### ISSUE TITLE
An error message 'UnexpectedQuit' occurs when deleting one folder which name contains '%'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3986]
**Storage Explorer Version:** 1.17.0
**Build Number:** 20210119.2
**Branch:** main
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core)/ MacOS Catalina
**Architecture:**  ia32/x64
**Regression From:** Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Create a folder by typing the name 'test%'.
3. Delete the folder -> Check the result.

## Expected Experience ##
1. Show a successful activity log.
2. The folder auto disappears from the editor.

## Actual Experience ##
1. Show a failed activity log and the details is 'UnexpectedQuit'.
2. The folder disappears after manually refreshing. 
![image](https://user-images.githubusercontent.com/41351993/105008580-6446cd80-5a74-11eb-99d9-c383a4e138ac.png)

## Additional Context ##
1. Fail to get properties for one folder which name contains '%'.
![image](https://user-images.githubusercontent.com/41351993/105008656-7aed2480-5a74-11eb-877a-73aab515398e.png)
Error details:
`	"name": "Error",
  "message": "Unable to extract shareName and filePath/directoryPath with provided information."`
2. The folder which name contains '%' can be successfully deleted from Portal.
![image](https://user-images.githubusercontent.com/41351993/105009002-eb944100-5a74-11eb-9108-ea446a39c23a.png)

**Comment by MRayermannMSFT** [comment]
AzCopy is crashing in this case. Will need to report to AzCopy team

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20230216.5. Fixed.
![image](https://user-images.githubusercontent.com/87792676/219322447-0a299365-66bd-4b7a-b348-3c5b144dc452.png)
