### ISSUE TITLE
Fail to create one ADLS Gen2 folder with name contains '%'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3987]
**Storage Explorer Version:** 1.17.0
**Build Number:** 20210119.2
**Branch:** main
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core)/ MacOS Catalina
**Architecture:**  ia32/x64
**Regression From:** Previous release (1.17.0)

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Create a folder with name contains '%'.
3. Check whether the folder can be successfully created.

## Expected Experience ##
Succeed to create the folder.
![image](https://user-images.githubusercontent.com/41351993/105011154-8e4dbf00-5a77-11eb-8244-ba8867776354.png)

## Actual Experience ##
Fail to create the folder.
![image](https://user-images.githubusercontent.com/41351993/105011150-8d1c9200-5a77-11eb-89e7-029cbc9ef806.png)
![image](https://user-images.githubusercontent.com/41351993/105011160-9148af80-5a77-11eb-821c-beb3950bfd5f.png)

## Additional Context ##
Succeed to create a folder with name contains '%' from Portal.

**Comment by JasonYeMSFT** [comment]
The error is an SDK internal error. The cause is that decodeURIComponent("New%Folder") throws.

**Comment by v-xianya** [comment]
Verified on build 20210127.3. Fixed.
