### ISSUE TITLE
Update the name of the 'Query' button to 'Close Query' in the toolbar after opening query builder

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3989]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20210120.2
**Branch**: main
**Platform/OS**: Windows 10/ CentOS 7.6.1810 (Core)/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Previous release (1.17.0)

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Open one table -> Click the button 'Query' in the toolbar.
3. Check whether the button name is 'Close Query'.

## Expected Experience ##
The button name is 'Close Query'.
![image](https://user-images.githubusercontent.com/54055206/105153137-08974580-5b43-11eb-8534-440012d0a60d.png)

## Actual Experience ##
The button name is 'Query'.
![image](https://user-images.githubusercontent.com/54055206/105153302-3b413e00-5b43-11eb-8bc3-dfca50f709f9.png)

**Comment by v-limu** [comment]
Verified on build 20210210.2. This issue still reproduces and we will continue to verify it.

**Comment by craxal** [comment]
Cloud Explorer is updated, so fix should be available now.

**Comment by v-xianya** [comment]
This issue has been fixed on build main/20210218.1.

**Comment by v-limu** [comment]
This issue occurs again when executing test cases on the main/20210511.3.  And this issue doesn't reproduce on main/20210508.4. So we re-open it.
![image](https://user-images.githubusercontent.com/54055206/117784707-6aa4c380-b276-11eb-8540-28ef53da32d2.png)

**Comment by v-limu** [comment]
Hi @JasonYeMSFT Verified on the lasted build main/20210512.2. The name has been fixed. But the tooltip of the button 'Close Query' is incorrect.
![image](https://user-images.githubusercontent.com/54055206/117910972-8314ec80-b30f-11eb-8682-cbf46fddaa27.png)

**Expect**:
![image](https://user-images.githubusercontent.com/54055206/117911068-af306d80-b30f-11eb-9d2f-846102139213.png)

**Comment by v-xianya** [comment]
Verified on build 20210513.1. Fixed.
