### ISSUE TITLE
Nothing happens when clicking 'Edit Tags...' for one blob under a folder which name contains '%'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3990]
**Storage Explorer Version:** 1.17.0
**Build Number:** 20210120.2
**Branch:** main
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core)/ MacOS Catalina 
**Architecture:**  ia32/x64
**Regression From:** Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers -> Select one blob container with the property 'Supports Tags' is 'True'.
2. Create a new folder with a name contains '%' -> Upload a blob to the folder.
3. Right click the blob -> Click 'Edit Tags...'.
4. Check whether the 'Edit Tags' dialog pops up.

## Expected Experience ##
The 'Edit Tags' dialog pops up.
![image](https://user-images.githubusercontent.com/41351993/105157008-81000580-5b47-11eb-84dc-fa478ba847e5.png)

## Actual Experience ##
Nothing happens.

## Additional Context ##
Other actions against the blob work normal.

**Comment by v-limu** [comment]
Verified on build 20210203.5. This issue has been fixed. So we close it.
