### ISSUE TITLE
ASE: Copy and Paste in ADLS Gen 2 container/folder authenticated using Azure AD (currently greyed out)

### ISSUE THREAD

**Issue by kk921dbg** [microsoft/AzureStorageExplorer#3992]
When we connect to an ADLS Gen 2 DFS endpoint for a container using Azure AD connection (Add a resource via Azure Active Directory (Azure AD)) the copy and paste is greyed out even though authenticated user has RWX ACL permissions on the Container and folders.

Would like to know if this feature is in the works as we currently can only Move and Rename in storage explorer, so there is no way for a user to copy using ACLs without downloading and uploading again especially with large data.  I

Are there any alternative ways to copy and paste within an ADLS Gen 2 container and/or folder as using Add a resource via Azure Active Directory (Azure AD) does not work.  We would like our users to manage their data themselves within ASE and not have to use ADF or other external tools.

**Comment by MRayermannMSFT** [comment]
@kk921dbg we are not currently able to support copy and paste in ADLS Gen2 containers when authenticating only with Azure AD. We're actively working with the platform team to get support for this.

**Comment by JasonYeMSFT** [comment]
Related to https://github.com/microsoft/AzureStorageExplorer/issues/5242
We have implemented Azure AD based copy/paste/clone features for ADLS Gen2 for our next 1.25.0 release.
