### ISSUE TITLE
Unable to import CSV or delete rows in local azurite (but can delete an entire table)

### ISSUE THREAD

**Issue by devology-rob** [microsoft/AzureStorageExplorer#3993]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20201211.10
**Platform/OS**: macOS
**Architecture**: x64
**Regression From**:  Yes, unknown version number - sorry just upgraded

## Bug Description ##
I created a couple of tables and then tried to import the test data from CSVs but they failed to import.  I then tried to manually insert rows which worked.  Deleting a row then fails with an error.

## Steps to Reproduce ##

- Add a table called 'application'
- Drag in the CSV file from a backup
- The error "Importing '/Users/rob/Desktop/application.csv' into table 'devstoreaccount1/application': Failed: Cannot read property 'tableName' of undefined (0 entities imported)"
- Manually insert a row (this works)
- Try to delete the row just added 
- The error "Deleting entities from table 'devstoreaccount1/xxx': Failed: Cannot read property 'tableName' of undefined" appears

## Expected Experience ##
I should be able to import from a CSV file and delete rows added.

## Actual Experience ##
Can't import and can't delete rows.

## Additional Context ##

I'm using a Local Azure deployment.

I can delete the table in its entirety, but not individual rows.

The Azurite terminal also has some output with 501 errors, note below is when I was testing with 'xxx' instead of 'application' - but the end result is the same.

Azurite, Version 2.7.1
A lightweight server clone of Azure Storage

Azure Table Storage Emulator listening on port 10002
Azure Queue Storage Emulator listening on port 10001
Azure Blob Storage Emulator listening on port 10000
GET /devstoreaccount1/?restype=account&comp=properties 501 2.609 ms - 229
GET /devstoreaccount1/?restype=account&comp=properties 501 0.420 ms - 229
GET /devstoreaccount1/Tables?%24top=25&_=1611154391361 200 4.577 ms - 198
GET /devstoreaccount1/Tables(%27$MetricsHourPrimaryTransactionsBlob%27)?_=1611154391370 404 8.596 ms - 133
GET /devstoreaccount1/Tables(%27$MetricsHourPrimaryTransactionsFile%27)?_=1611154391371 404 8.459 ms - 133
GET /devstoreaccount1/Tables(%27$MetricsHourPrimaryTransactionsTable%27)?_=1611154391371 404 8.036 ms - 133
GET /devstoreaccount1/Tables(%27$MetricsHourPrimaryTransactionsQueue%27)?_=1611154391372 404 7.663 ms - 133
GET /devstoreaccount1/Tables(%27$MetricsMinutePrimaryTransactionsBlob%27)?_=1611154391372 404 7.327 ms - 133
GET /devstoreaccount1/Tables(%27$MetricsMinutePrimaryTransactionsFile%27)?_=1611154391373 404 7.033 ms - 133
GET /devstoreaccount1/Tables(%27$MetricsMinutePrimaryTransactionsTable%27)?_=1611154391375 404 6.667 ms - 133
GET /devstoreaccount1/Tables(%27$MetricsMinutePrimaryTransactionsQueue%27)?_=1611154391375 404 6.370 ms - 133
GET /devstoreaccount1/Tables(%27$MetricsHourSecondaryTransactionsBlob%27)?_=1611154391375 404 6.068 ms - 133
GET /devstoreaccount1/Tables(%27$MetricsHourSecondaryTransactionsFile%27)?_=1611154391376 404 5.760 ms - 133
GET /devstoreaccount1/Tables(%27$MetricsHourSecondaryTransactionsTable%27)?_=1611154391376 404 5.433 ms - 133
GET /devstoreaccount1/Tables(%27$MetricsHourSecondaryTransactionsQueue%27)?_=1611154391377 404 5.113 ms - 133
GET /devstoreaccount1/Tables(%27$MetricsMinuteSecondaryTransactionsBlob%27)?_=1611154391377 404 4.804 ms - 133
GET /devstoreaccount1/Tables(%27$MetricsMinuteSecondaryTransactionsFile%27)?_=1611154391377 404 4.102 ms - 133
GET /devstoreaccount1/Tables(%27$MetricsMinuteSecondaryTransactionsTable%27)?_=1611154391378 404 3.816 ms - 133
GET /devstoreaccount1/Tables(%27$MetricsMinuteSecondaryTransactionsQueue%27)?_=1611154391379 404 3.539 ms - 133
GET /devstoreaccount1/Tables(%27$MetricsCapacityBlob%27)?_=1611154391379 404 3.250 ms - 133
GET /devstoreaccount1/application?%24top=1000 200 0.843 ms - 165
GET /devstoreaccount1/application?%24top=1000 200 0.517 ms - 165
POST /devstoreaccount1/$batch 501 1.035 ms - 45
DELETE /devstoreaccount1/Tables(%27application%27) 204 1.073 ms - -
GET /devstoreaccount1/applicationProtocol?%24top=1000 200 0.421 ms - 101
DELETE /devstoreaccount1/Tables(%27applicationProtocol%27) 204 0.533 ms - -
DELETE /devstoreaccount1/Tables(%27company%27) 204 0.457 ms - -
GET /devstoreaccount1/device?%24top=1000 200 0.389 ms - 88
DELETE /devstoreaccount1/Tables(%27device%27) 204 0.749 ms - -
POST /devstoreaccount1/Tables 204 1.060 ms - -
GET /devstoreaccount1/xxx?%24top=1000 200 0.434 ms - 85
POST /devstoreaccount1/$batch 501 0.548 ms - 45
POST /devstoreaccount1/$batch 501 0.554 ms - 45
POST /devstoreaccount1/$batch 501 0.463 ms - 45
GET /devstoreaccount1/xxx?%24top=1000 200 0.378 ms - 85
POST /devstoreaccount1/xxx 204 0.843 ms - -
GET /devstoreaccount1/xxx?%24top=1000 200 0.437 ms - 157
POST /devstoreaccount1/$batch 501 0.455 ms - 45
GET /devstoreaccount1/xxx?%24top=1000 200 0.431 ms - 157
GET /devstoreaccount1/xxx?%24top=1000 200 0.409 ms - 157

**Comment by MRayermannMSFT** [comment]
@devology-rob Azurite support for Tables is still in preview. Please open an issue against Azurite first:

https://github.com/Azure/Azurite

**Comment by jongio** [comment]
@devology-rob - Did you open an issue in Azurite repo?

**Comment by devology-rob** [comment]
Sorry - I did not.  

In the end I used the Azure storage for my dev use (rather than my local machine) 

I'm closing this as advised it should be an Azurite issue.
