### ISSUE TITLE
Fail to execute 'Create queue' & 'Configure CORS Settings…' & 'Refresh' actions for Queues node

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3997]
**Storage Explorer Version:** 1.17.0
**Build Number:** 20210120.8
**Branch:** main
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ MacOS Catalina
**Architecture:** ia32/x64
**Regression From:** Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Right click the 'Queues' node.
2. Try to execute the actions on the context menu one by one.
3. Check whether all the actions can be executed successfully.

## Expected Experience ##
Succeed to execute all the actions.

## Actual Experience ##
Fail to execute 'Create queue' & 'Configure CORS Settings…' & 'Refresh' actions.
![image](https://user-images.githubusercontent.com/41351993/105320222-e19f4900-5c00-11eb-8f83-0e4c972b30f3.png)

Error details:
`"name": "Error",
	  "message": "Unable to extract accountName with provided information.",
  "stack": "Error: Unable to extract accountName with provided information.\n    at getAccountNameFromUrl`

**Comment by MRayermannMSFT** [comment]
Fix merged into main
