### ISSUE TITLE
Show which Storage Account a tab is from without hovering

### ISSUE THREAD

**Issue by JakeRadMSFT** [microsoft/AzureStorageExplorer#4]
Storage Explorer Version: 0.9.6

OS Version: Windows 10 (All)

Steps to Reproduce:

1. Open Blob Container form Storage Account A
2. Open Blob Container form Storage Account B

Expected Experience:
Able to see which account a blob container is from. 

Actual Experience:
If you have two blob containers with the same name it's hard to tell where they're from.

**Comment by MRayermannMSFT** [comment]
@richardmsft please come up with a UX design and API design proposal for the team.
