### ISSUE TITLE
Fail to create one ADLS Gen2 folder

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4002]
**Storage Explorer Version:** 1.17.0
**Build Number:** 20210120.8
**Branch:** main
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ MacOS Catalina
**Architecture:** ia32/x64
**Regression From:** Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Try to create a new folder.
3. Check whether the folder can be created successfully.

## Expected Experience ##
Succeed to create the folder.

## Actual Experience ##
Fail to create a new folder.
![image](https://user-images.githubusercontent.com/41351993/105325154-3fcf2a80-5c07-11eb-98e5-ffc9acf01727.png)

`
"name": "RestError",
  "message": "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<Error><Code>MissingRequiredHeader</Code><Message>An HTTP header that&apos;s mandatory for this request is not specified.\nRequestId:6e854533-f01e-0007-1c9a-ef61b6000000\nTime:2021-01-21T02:10:17.1650204Z</Message><HeaderName>x-ms-blob-type</HeaderName></Error>",
`

**Comment by MRayermannMSFT** [comment]
Fix merged into main
