### ISSUE TITLE
Fail to execute 'Manage Access Control Lists…' action for one ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4003]
**Storage Explorer Version:** 1.17.0
**Build Number:** 20210120.8
**Branch:** main
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ MacOS Catalina
**Architecture:** ia32/x64
**Regression From:** Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Right click the blob container.
3. Select 'Manage Access Control Lists...' -> Check whether the 'Manage Access' dialog pops up.

## Expected Experience ##
The 'Manage Access' dialog pops up.

## Actual Experience ##
1. No dialog pops up.
2. A failed activity log displays.
![image](https://user-images.githubusercontent.com/41351993/105326527-cdf7e080-5c08-11eb-876c-edad43684073.png)
Details:
![image](https://user-images.githubusercontent.com/41351993/105326497-c59fa580-5c08-11eb-9799-6a5fe4cb2824.png)

## Additional Context ##
This issue also reproduces on one ADLS Gen2 blob/ folder.

**Comment by MRayermannMSFT** [comment]
Fix merged into main
