### ISSUE TITLE
Fail to execute 'Propagate Access Control Lists...' action for one ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4004]
**Storage Explorer Version:** 1.17.0
**Build Number:** 20210120.8
**Branch:** main
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ MacOS Catalina
**Architecture:** ia32/x64
**Regression From:** Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Right click the blob container.
3. Select 'Propagate Access Control Lists...' -> Click 'OK' on the 'Propagate Access Control Lists' dialog.
4. Check whether the action can be executed successfully.

## Expected Experience ##
Succeed to execute the action.

## Actual Experience ##
Fail to execute the action.
![image](https://user-images.githubusercontent.com/41351993/105329183-d43b8c00-5c0b-11eb-9626-4b6c9c90655a.png)

## Additional Context ##
This issue also reproduces on one ADLS Gen2 folder.

**Comment by MRayermannMSFT** [comment]
Fix merged into main
