### ISSUE TITLE
An error pops up when expanding the services node under one name & key attached account

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#4005]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20210120.8
**Branch**: main
**Platform/OS**: Windows 10/ CentOS 7.6.1810 (Core)/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**:  Not a regression

## Steps to Reproduce ##
1. Select one storage account -> Right click it -> Click 'Copy Primary Key'.
2. Open connect dialog -> Attach the account via name & key.
3. Observe the attached account -> Try to expand 'Blob Containers/ File Shares/ Queues/ Tables' node.
4. Check the results.

## Expected Experience ##
No error pops up.

## Actual Experience ##
An error pops up.
![image](https://user-images.githubusercontent.com/54055206/105330301-17e2c580-5c0d-11eb-8f94-7f6b446c5fd9.png)

## Additional Context ##
This issue also reproduces for one name & key attached ADLS Gen2 account.

**Comment by JasonYeMSFT** [comment]
Have you tried entering the correct endpoint when attaching?

![image](https://user-images.githubusercontent.com/39359541/106970944-c2291580-6702-11eb-8240-ee544c9fa164.png)

For example, enter "storage.azure.net/" as the Storage domain for the test storage account.

**Comment by v-limu** [comment]
Hi @JasonYeMSFT 

1. I selected the default domain 'Azure' as the Storage domain when attaching the test storage account. An error pop up after expanding the attached account.
![image](https://user-images.githubusercontent.com/54055206/106982381-f81bd780-679e-11eb-8e7b-50a7f8b454cd.png)
2. I try to enter 'storage.azure.net/' as the Storage domain when attaching the account. This issue still reproduces.
![image](https://user-images.githubusercontent.com/54055206/106983107-4d0c1d80-67a0-11eb-91cf-c4dc993ba010.png)

**Comment by JasonYeMSFT** [comment]
We will add support for attaching these devex storage accounts by adding the connection string with key method in the new connect experience.

This will be related to #4177.

**Comment by JasonYeMSFT** [comment]
I have split the connection method to "Connection string (Key or SAS)" and "Shared access signature URL". From the user point of view, this should work by getting connection string with account name and key. We will consider adding support for this type of accounts in the name/key connection method if we have time left.

**Comment by v-limu** [comment]
Hi @JasonYeMSFT Got it. Thanks for your updates. 
Verified on build 20210312.1. The attached account doesn't work when getting the connection string with the account in portal. 
![image](https://user-images.githubusercontent.com/54055206/110916393-b6f58500-8353-11eb-8b35-aa36449afc1c.png)

The error shows below:
![image](https://user-images.githubusercontent.com/54055206/110917200-9aa61800-8354-11eb-8cd8-d1dc772f4c41.png)

**Comment by JasonYeMSFT** [comment]
Portal has a bug for giving the wrong service endpoints in the connection string. Could you test with connection strings generated in Storage Explorer?

**Comment by v-limu** [comment]
Hi @JasonYeMSFT  Verified on build 20210313.6.

1. The attached account works well when the connection string with account name and key generated in Storage Explorer. 
2. We will verify the account name/key connection method if you have time to fix it.
