### ISSUE TITLE
Fail to rename one ADLS Gen2 folder

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4006]
**Storage Explorer Version:** 1.17.0
**Build Number:** 20210120.8
**Branch:** main
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ MacOS Catalina
**Architecture:** ia32/x64
**Regression From:** Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one folder.
3. Rename the folder with a valid name.
4. Check whether the folder can be renamed successfully. 

## Expected Experience ##
Succeed to rename the folder.

## Actual Experience ##
Fail to rename the folder.
![image](https://user-images.githubusercontent.com/41351993/105330535-5f695180-5c0d-11eb-97c3-370afdaf8eb7.png)
`  "name": "Error",
  "message": "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<Error><Code>MissingRequiredHeader</Code><Message>An HTTP header that&apos;s mandatory for this request is not specified.\nRequestId:2b4e7a8b-a01e-009c-69d6-efec8e000000\nTime:2021-01-21T09:20:33.7717316Z</Message><HeaderName>x-ms-blob-type</HeaderName></Error>",`

## Additional Context ##
This issue also reproduces on one ADLS Gen2 blob.

**Comment by MRayermannMSFT** [comment]
Fix merged into main
