### ISSUE TITLE
An extra ‘/’ shows in the activity log of the action 'Folder Statistics'

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#4007]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20210120.8
**Branch**: main
**Platform/OS**: Windows 10/ CentOS 7.6.1810 (Core)/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**:  Not a regression

## Steps to Reproduce ##
1. Select one storage account -> Blob Containers
2. Create a blob container -> Upload blobs to it -> Click 'Folder Statistics' action in the toolbar.
3. Observe the activity log -> Check whether an extra '/' shows in front of the blob container name.

## Expected Experience ##
No the extra '/' shows in front of the blob container name.

## Actual Experience ##
An extra '/' shows in front of the blob container name.
![image](https://user-images.githubusercontent.com/54055206/105328037-94c07000-5c0a-11eb-8491-a2136d2462c9.png)

## Additional Context ##
1. This issue also reproduces for one blob container when clicking the action 'Selection Statistics'. 
2. This issue also reproduces when pasting one blob container /file share.
3. This issue doesn't reproduce in one public connected blob container.

**Comment by MRayermannMSFT** [comment]
Fix merged into main
