### ISSUE TITLE
Auto-fill bug template on "Copy and Open GitHub"

### ISSUE THREAD

**Issue by JakeRadMSFT** [microsoft/AzureStorageExplorer#401]
- [x] Use GitHub issue forms to guide users and enforce required information.
- [ ] Implement issue form in Storage Explorer to be submitted to GitHub.

#### Expected Experience: ####
Make "Copy and Open GitHub" should be our bug template.

**Comment by craxal** [comment]
To make it easier for users to provide useful bug reports, we should modify the information that is copied to the clipboard such that it already conforms to the bug report template we have on GitHub, automatically filling information we can easily query while in the application.

**Comment by craxal** [comment]
After reviewing the work involved, I think we can do even better with designing a better bug reporting experience for users. I want to take as much of the ambiguity out as possible and provide a clean experience that also gets us the information we need.

**Comment by MRayermannMSFT** [comment]
Moving this due to changes in dev resources for 1.19

**Comment by craxal** [comment]
GitHub appears to have a preview feature known as issue forms that can be configured with YAML files. Work looking into those to see if we can avoid needing to implement UI in Storage Explorer.
