### ISSUE TITLE
Authentication error: Signature size is invalid

### ISSUE THREAD

**Issue by lizquierdo22** [microsoft/AzureStorageExplorer#4010]

**Comment by MRayermannMSFT** [comment]
@lizquierdo22 can you share with us:

- What version of Storage Explorer are you using?
- What is your OS?
- Have you been able to sign in before?
- Can you sign in with a different account?
- Can you try this on a different machine or network?

**Comment by lizquierdo22** [comment]
1.  What version of Storage Explorer are you using? >>>> 1.17.0

AzCopy Version: 10.7.0

Platform: Windows

Architecture: ia32

Build Number: 20201211.10

  1.  What is your OS? >>>>Windows 10 Pro, Version:20H2
  2.  Have you been able to sign in before? YES
  3.  Can you sign in with a different account? YES
  4.  Can you try this on a different machine or network? YES
Thank you for your help.

Best regards,

Luis Izquierdo

**Comment by MRayermannMSFT** [comment]
@lizquierdo22 soooo did you try any of those things and if so what was the result?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having this problem please open a new issue.
