### ISSUE TITLE
An error dialog pops up when executing 'Propagate Access Control Lists…' for a SAS attached ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4018]
**Storage Explorer Version:** 1.17.0
**Build Number:** 20210127.3
**Branch:** main
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ MacOS Catalina
**Architecture:**  ia32/x64
**Regression From:** Previous build (20210123.6)

**Steps to reproduce:**
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Attach it via SAS with full permissions.
3. Right click the SAS attached blob container -> Click 'Propagate Access Control Lists...' -> Click 'OK'.
4. Check there no error dialog pops up.

**Expect Experience:**
No error dialog pops up.

**Actual Experience:**
An error dialog pops up.
![image](https://user-images.githubusercontent.com/41351993/105967749-2de6ff00-60c1-11eb-80d8-0ad1cb83b22e.png)

**Comment by v-limu** [comment]
Verified on build 20210128.3. This issue has been fixed. So we close it.
