### ISSUE TITLE
A successful activity log shows when using an existing folder name to rename another ADLS Gen2 folder

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#4019]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20210127.3
**Branch**: main
**Platform/OS**: Windows 10/ CentOS 7.6.1810 (Core)/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Previous build (20210123.6)

## Steps to Reproduce ##

1. Expand one ADLS Gen2 account -> Blob Containers.
2. Create a blob container -> Create two folders to it.
3. Use a folder name to rename another folder.
4. Check whether a failed activity log shows or not.

## Expected Experience ##
A failed activity log shows.
![image](https://user-images.githubusercontent.com/54055206/105969220-fa0cd900-60c2-11eb-8086-fc37e4a4873a.png)

## Actual Experience ##
A successful activity log shows.

**Comment by MRayermannMSFT** [comment]
Fix merging into main in ~15min.

**Comment by v-limu** [comment]
Hi @MRayermannMSFT      Verified on build 20210128.6. Nothing happens after clicking the 'Rename' action in the ADLS Gen2 blob container. So we re-open this issue and will keep eye on it.

**Comment by v-limu** [comment]
Verified on build 20210129.2. This issue has been fixed. So we close it.
