### ISSUE TITLE
The 'Rename Folder' dialog isn't localized for one ADLS Gen2 folder

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#4021]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20210127.3
**Branch**: main
**Language**: All
**Platform/OS**: Windows 10/ CentOS 7.6.1810 (Core)/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Previous release(1.17.0)

## Steps to Reproduce ##

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Magyar' -> Restart Storage Explorer.
3. Expand one ADLS Gen2 account -> Blob Containers.
4. Open a blob container -> Right click one folder -> Click the localized 'Rename...' action.
5. Check whether the 'Rename Folder' dialog is localized or not.

## Expected Experience ##
The 'Rename Folder' dialog is localized.

## Actual Experience ##
The 'Rename Folder' dialog isn't localized.
![image](https://user-images.githubusercontent.com/54055206/105969892-b5357200-60c3-11eb-8d87-47f88177e140.png)

## Additional Context ##
This issue also reproduces for one ADLS Gen2 blob.
![image](https://user-images.githubusercontent.com/54055206/105969875-b1095480-60c3-11eb-96b3-0dad2dbd658d.png)

**Comment by v-xianya** [comment]
Verified this issue on build 20210206.3. Fixed.
