### ISSUE TITLE
There are untranslated strings in the 'Acquire/Break Lease' dialog for one blob container

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#4028]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20210128.6
**Branch**: main
**Language**: All
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core)/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Previous release(1.17.0)

## Steps to Reproduce ##

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Magyar' -> Restart Storage Explorer.
3. Expand one ADLS Gen2 account -> Blob Containers.
4. Create a blob container -> Right click it.
5. Click 'Acquire Lease' -> Check whether all strings in the dialog are translated or not.

## Expected Experience ##
All strings in the dialog are translated.

## Actual Experience ##
There are untranslated strings in the dialog.
![image](https://user-images.githubusercontent.com/54055206/106114555-a5cd2c00-618a-11eb-9e17-bf54dff70718.png)

## Additional Context ##

1. This issue also reproduces in the 'Break Lease' dialog.
 ![image](https://user-images.githubusercontent.com/54055206/106114596-b2518480-618a-11eb-86d7-773fc4d6379c.png)
2. This issue also reproduces for one ADLS Gen2 blob container.

**Comment by MRayermannMSFT** [comment]
Strings were moved to a diff resource file. I'll track this.

**Comment by v-xianya** [comment]
Verified this issue on build 20210206.3.
This issue still reproduces on **Japanese/ Turkish/ Polish**.
Japanese:
![image](https://user-images.githubusercontent.com/41351993/107139035-280bdc00-6953-11eb-82aa-8c3dbddaf0fe.png)

Polish:
![image](https://user-images.githubusercontent.com/41351993/107139016-10ccee80-6953-11eb-88e1-970396e9bfa3.png)

Turkish:
![image](https://user-images.githubusercontent.com/41351993/107138966-d5cabb00-6952-11eb-87f6-0547e406e6e9.png)

**Comment by MRayermannMSFT** [comment]
@cristianosuzuki77 I'm seeing the message in this dialog still missing a Turkish translation. The resource is `src/components/se-blob-extension/resources/BlobContainerActions` -> `MessageContainerAcquireLeaseConfirmation`.

**Comment by cristianosuzuki77** [comment]
Addressing this.

**Comment by cristianosuzuki77** [comment]
Pull request 320593 completed.

**Comment by v-xianya** [comment]
Verified on the build 20210820.5. Fixed.
