### ISSUE TITLE
The new added metadata isn't sorted with the saved metadata for one ADLS Gen2 folder

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#4029]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20210128.6
**Branch**: main
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core)/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Previous release(1.17.0)

## Steps to Reproduce ##

1. Expand one ADLS Gen2 account -> Blob Container.
2. Create a blob container -> Upload one folder.
3. Right click the folder -> Click 'Properties...' -> Click 'Add Metadata' and save it.
4. Open the properties dialog again -> Click 'Add Metadata'.
5. Check whether the new added metadata is sorted with the saved metadata.

 
## Expected Experience ##
The new added metadata is sorted with the saved metadata.
![image](https://user-images.githubusercontent.com/54055206/106115490-cea1f100-618b-11eb-9990-04e975cbc507.png)

## Actual Experience ##
The new added metadata isn't sorted with the saved metadata.
![image](https://user-images.githubusercontent.com/54055206/106115450-c5b11f80-618b-11eb-9911-130e30499b9c.png)

## Additional Context ##
This issue doesn't reproduce for one ADLS Gen2 blob.

**Comment by JasonYeMSFT** [comment]
It is expected that those metadata aren't saved because they have equivalent keys with the existing ones. Our duplicate key validation logic has a bug here.

**Comment by v-xianya** [comment]
Verified this issue on build 20210129.2. Fixed.
