### ISSUE TITLE
Unable to sign in: User returned by service does not match user in the request

### ISSUE THREAD

**Issue by TroyShane** [microsoft/AzureStorageExplorer#4031]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20201211.10
**Platform/OS**: Win10_x64
**Architecture**:  x64
**Regression From**:  Not aware, first re-install of this tool in more than a year

## Bug Description ##
When I add my work account through either my alias (e.g. frank@microsoft.com) or Full name (e.g. frank.smith@microsoft.com) and I authenticate properly through MFA (MS Authenticator) I receive the message:

"Subscriptions could not be loaded. Please try reentering credentials or removing and readding account."
In the Activities window are 2 messages:
 - Unable to sign in: User 'frank.smith@microsoft.com' returned by service does not match user 'frank@microsoft.com' in the request.
 - Added Azure account 'frank@microsoft.com'
I have attempted to authenticate with both alias and full email address and both end in the same message.

## Steps to Reproduce ##
Add account
Enter either alias@microsoft.com or first.last@microsoft.com
Successfully authenticate through MFA
Storage explorer returns me the above message

## Expected Experience ##
I authenticate and am able to access my storage across my subscriptions.

## Actual Experience ##
I am continually prompted that one or more account requires authentication

**Comment by MRayermannMSFT** [comment]
@TroyShane how long ago did you create the alternative address (frank.smith)?

**Comment by TroyShane** [comment]
Same day I started working at this company. One is just the alias of the other.

**Comment by MRayermannMSFT** [comment]
Can you:
1. Upgrade to at least version 1.19.0
2. Try these steps: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#reauthentication-loop-or-upn-change

**Comment by TroyShane** [comment]
V 1.19 seems to have resolved it.

Thanks Matthew!

Troy Shane
Strategic Partnerships Team, SAP on Azure
Microsoft
Teams:     +1 (613) 212-3883
Mobile:    +1 (425) 802-1131
***@***.******@***.***>
***@***.***D73AA0.4023B7E0]
