### ISSUE TITLE
An error information bar prompts when attaching one blob container with SAS generated by access policy

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4032]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20210129.3
**Branch:** main
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Previous release (1.17.0)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Right click the blob container.
3. Click 'Manage Access Policies...' -> Add one access policy and save it.
4. Generate a SAS for the blob container by selecting the access policy.
5. Attach the blob container using the SAS.
6. Check no error information bar prompts.

## Expected Experience ##
No error information bar prompts.

## Actual Experience ##
An error information bar prompts.
![image](https://user-images.githubusercontent.com/41351993/106248356-d32dde80-624b-11eb-99af-a9e7ac428257.png)

`Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:63e00d21-901e-0008-0915-f65edf000000 Time:2021-01-29T08:04:54.8724938Z`
## Additional Context ##
1. This issue also reproduces for one ADLS Gen2 blob container.
2. A similar bug: [3996](https://github.com/microsoft/AzureStorageExplorer/issues/3996).

**Comment by MRayermannMSFT** [comment]
@v-xianya what permissions are you using for the access policy, and is it being used before the expiration of the policy/what is the expiration date?

**Comment by JasonYeMSFT** [comment]
I tried without latest main but cannot reproduce this issue.

**Comment by v-xianya** [comment]
@MRayermannMSFT @JasonYeMSFT 
The access policy with permissions 'Read, Add, Create, Write, Delete, List'.
Verified this issue on build 202102020.9. Reproduce.
![issue](https://user-images.githubusercontent.com/41351993/106560763-82c3c300-6562-11eb-895f-4d1afb7fab51.gif)

**Comment by v-xianya** [comment]
Verified this issue on build 20210204.2. Fixed.
