### ISSUE TITLE
The public connected ADLS Gen2 blob container displays as a regular blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4033]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20210129.3
**Branch:** main
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Right click the blob container.
3. Select 'Set Public Access Level...' -> Set the container public access level to 'container'.
4. Connect to the public blob container.
5. Observe the public connected blob container -> Check whether it displays as an ADLS Gen2 blob container.

## Expected Experience ##
The public connected blob container displays as an ADLS Gen2 blob container.

## Actual Experience ##
The public connected ADLS Gen2 blob container displays as a regular blob container.
![image](https://user-images.githubusercontent.com/41351993/106254381-9a920300-6253-11eb-9f75-c99c3de7aee6.png)

**Comment by MRayermannMSFT** [comment]
By design. When connected publicly, we cannot detect HNS being enabled. Additionally, when connecting publicly, you cannot use any of the Gen2 specific features anyways.
