### ISSUE TITLE
Emulator - Local-1 - Shared Access Signature

### ISSUE THREAD

**Issue by Kf-GaryNewport** [microsoft/AzureStorageExplorer#4036]
How can I obtain the SAS token for the local storage account ?
The properties have a provision for it, but its not populated.

I know I can get a SAS token for each individual resource, but that is not manageable. 
Thanks

**Comment by MRayermannMSFT** [comment]
@Kf-GaryNewport we don't currently support generating a SAS for an emulator storage account. Can you tell us why you want to get one?
