### ISSUE TITLE
Unable to retrieve child resources.

### ISSUE THREAD

**Issue by YanlinWang** [microsoft/AzureStorageExplorer#4041]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:  

## Bug Description ##

Unable to retrieve child resources.

Details:
["Error:Unable to retrieve authentication token."]

**Comment by bandmask** [comment]
Experienced same issue for a resource, but found there was an IP restriction on the database.
Might not be your case though.

**Comment by MRayermannMSFT** [comment]
Can you please check if your account is requiring reauthentication? Go to the account panel to check this.
