### ISSUE TITLE
Unable to view contents of storage account

### ISSUE THREAD

**Issue by ChrisKoenig** [microsoft/AzureStorageExplorer#4046]
This storage account is tied to a Functions app that is now no longer working as the file storage seems to be corrupted, or some kind of error is going on. I am an admin for the subscription (I'm the one that provisioned it) and I made sure that I am an "Owner" on the storage account.  Here's the error:

Unable to retrieve child resources.

Details:
["RestError:﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.\nRequestId:0c44111e-201e-00a3-6c47-fa5770000000\nTime:2021-02-03T16:15:42.8192406Z</Message></Error>"]

**Comment by arindamdawn** [comment]
I am not able to access the contents of a file share. This is the error message I am getting.
Authentication error: Signature not valid in the specified time frame: Start [Sun, 08 Nov 2020 15:13:53 GMT] - Expiry [Sun, 31 Jan 2021 23:13:53 GMT] - Current [Thu, 04 Feb 2021 06:05:25 GMT]

**Comment by MRayermannMSFT** [comment]
@ChrisKoenig are you connecting via sign-in or have you attached the account?
It sounds like you are able to list the file shares in the account but not actually view any data in them, is that correct?
Can you click on the node for the storage account, and then check the properties panel in the bottom left to see if there is a Storage Account Key property for the account (make sure to click the eye to reveal to see if the value actually loaded)?

@arindamdawn your SAS is expired, you need to have a new SAS generated for you and re-attach.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having this problem please open a new issue.
