### ISSUE TITLE
Fail to get permissions for one Azure AD attached ADLS Gen2 folder

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#4047]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20210204.2
**Branch**: main
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core)/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Previous build(20210129.3)

## Steps to Reproduce ##

1. Expand one ADLS Gen2 account -> Blob Containers.
2. Create a blob container -> Upload one folder.
3. Give RBAC access to the blob container 'Blob Data Owner Role'.
4. Attach the folder via Azure AD -> Right click the attached folder under the 'Attached Containers -> Blob Containers' node.
5. Click 'Manage Access Control Lists...' -> Check whether the 'Manage Access' dialog pops up.

## Expected Experience ##
The 'Manage Access' dialog pops up.

## Actual Experience ##

1. The 'Manage Access' dialog doesn't pop up.
2. The activity log shows 'Fail to get permissions for adls/folder'.
![image](https://user-images.githubusercontent.com/54055206/106864910-70ce5580-6705-11eb-86fa-bb9a4b461a44.png)
![image](https://user-images.githubusercontent.com/54055206/106864920-7330af80-6705-11eb-83c4-98ef686db328.png)

## Additional Context ##
This issue also reproduces for one Azure AD attached ADLS Gen2 folder via ACLs.

**Comment by v-limu** [comment]
Hi @JasonYeMSFT  Verified on build 20210205.4. 

1. This issue reproduces when the URL is generated from 'Copy URL' of the folder. (A '/' shows next to the folder'). Regression from: previous build (20210129.3)
 ![image](https://user-images.githubusercontent.com/54055206/106983894-990b9200-67a1-11eb-80ad-be1053140366.png)

2. This issue doesn't reproduce when copying the blob container url then append folder name to it. (No '/' shows next to the folder) 
![image](https://user-images.githubusercontent.com/54055206/106984480-a5dcb580-67a2-11eb-8681-ad2cad9f2637.png)

**Comment by JasonYeMSFT** [comment]
Similar to #4048, we shouldn't allow the user to attach to gen2 directory with a trailing /.

**Comment by v-limu** [comment]
Verified on the build main/20210219.1. This issue has been fixed. So we close it.
![image](https://user-images.githubusercontent.com/54055206/108482055-ef192300-72d3-11eb-9769-349b3d0c2647.png)
