### ISSUE TITLE
An error dialog pops up when executing 'Propagate Access Control Lists…'  for one Azure AD attached ADLS Gen2 folder

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#4048]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20210204.2
**Branch**: main
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core)/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Previous build(20210129.3)

## Steps to Reproduce ##
1. Expand one ADLS Gen2 account -> Blob Containers.
2. Create a blob container -> Upload one folder.
3. Give RBAC access to the blob container 'Blob Data Owner Role'.
4. Attach the folder via Azure AD -> Right click the attached folder under the 'Attached Containers -> Blob Containers' node.
5. Click 'Propagate Access Control Lists...' -> Click 'OK'.
6. Check there is no error dialog.

## Expected Experience ##
No error dialog pops up.

## Actual Experience ##
An error dialog pops up.
![image](https://user-images.githubusercontent.com/54055206/106865262-e33f3580-6705-11eb-8bf2-f50b264674f7.png)

## Additional Context ##
This issue also reproduces for one Azure AD attached ADLS Gen2 folder via ACLs.

**Comment by v-limu** [comment]
Hi @JasonYeMSFT  verified on build 20210205.4. This issue still reproduces. please see the record.
![adls](https://user-images.githubusercontent.com/54055206/106978800-f7337780-6797-11eb-96b2-26df2730bdb8.gif)

**Comment by JasonYeMSFT** [comment]
Ah, this is expected. The ADLS Gen2 directory path shouldn't contain the trailing / to work properly. Since we are working on a new connect dialog, let's make sure we invalidate the case with trailing /.

**Comment by v-limu** [comment]
Hi @JasonYeMSFT OK. Got it. We will continue to verify it on main branch.

**Comment by v-limu** [comment]
Verified on the build main/20210219.1. This issue has been fixed. So we close it.
![image](https://user-images.githubusercontent.com/54055206/108482055-ef192300-72d3-11eb-9769-349b3d0c2647.png)
