### ISSUE TITLE
No error warning displays when typing a number to the metadata key for one ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#4049]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20210204.2
**Branch**: main
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core)/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##

1. Expand one ADLS Gen2 account -> Blob Containers.
2. Create a blob container -> Right click it.
3. Click 'Properties...' -> Click 'Add Metadata' -> Type a number '1' to the metadata key.
4. Check whether an error warning displays or not.

## Expected Experience ##
An error warning displays.
![image](https://user-images.githubusercontent.com/54055206/106865863-b8091600-6706-11eb-9966-e2aaa01e1bc3.png)

## Actual Experience ##
No error warning displays.
![image](https://user-images.githubusercontent.com/54055206/106865814-a7f13680-6706-11eb-904c-8902e481ee25.png)

## Additional Context ##

1. This issue also reproduces for one ADLS Gen2 blob/folder. 
2. This issue doesn't reproduce for one file share and regular blob container.

**Comment by MRayermannMSFT** [comment]
@v-limu  I can't seem to repro this anymore. Are you still able to?

**Comment by v-limu** [comment]
Hi @MRayermannMSFT Verified on build 20210206.3. 
This issue doesn't reproduce for one ADLS Gen2 blob container and blob. But. This issue reproduces for one ADLS Gen2 folder.
![folder](https://user-images.githubusercontent.com/54055206/107134757-efa6d680-692f-11eb-8c58-d47427290d00.gif)

**Comment by MRayermannMSFT** [comment]
Thanks! Will fix that ASAP. :)

**Comment by MRayermannMSFT** [comment]
Fix merged into main.
