### ISSUE TITLE
Unable to retrieve child resources - microsoft azure storage explorer

### ISSUE THREAD

**Issue by ervcabrita** [microsoft/AzureStorageExplorer#4050]
local and attached
storage accounts
emulator default ports
blob containers
tables

can't access/create blob or tables

Unable to retrieve child resources.

Details:
Server encountered an internal error. Please try again after some time.
RequestId:76706f06-820b-49e6-a904-21aec7868a17
Time:2021-02-04T11:40:36.9134606Z

**Comment by MRayermannMSFT** [comment]
@ervcabrita the error says to try again later. Did you try again later?

It looks like you're probably working with an emulator? Which emulator is it, Azurite or the old .NET emulator? Can you look at the terminal where you started your emulator from for any error messages? Have you tried restarting your emulator?

**Comment by ervcabrita** [comment]
Hi.
It is Microsoft azure storage emulator v5.10.

I did restart everything.
After a few days still same issue.
In between working and not working I had a domain migration, but everything else is working by now.

Emulator log looks ok
:
C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator>AzureStorageEmulator.exe start
Windows Azure Storage Emulator 5.10.0.0 command line tool
The storage emulator was successfully started.

C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator>cmd /K AzureStorageEmulator.exe help
Windows Azure Storage Emulator 5.10.0.0 command line tool
Usage:
    AzureStorageEmulator.exe init            : Initialize the emulator database and configuration.
    AzureStorageEmulator.exe start           : Start the emulator.
    AzureStorageEmulator.exe stop            : Stop the emulator.
    AzureStorageEmulator.exe status          : Get current emulator status.
    AzureStorageEmulator.exe clear           : Delete all data in the emulator.
    AzureStorageEmulator.exe help [command]  : Show general or command-specific help.

See the following URL for more command line help: http://go.microsoft.com/fwlink/?LinkId=392235

**Comment by ervcabrita** [comment]
Could only be fixed after uninstall all azure apps/microsoft sdk, clearing all cache and temp files, and reinstalling.
Path variables didn't mention any of the affected paths.
