### ISSUE TITLE
File snapshots on ADLS Gen2

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#4056]

**Comment by craxal** [comment]
@MRayermannMSFT This is already implemented. The platform feature is currently in preview. What else do we need to do here?

**Comment by MRayermannMSFT** [comment]
@craxal you need to reach out to Sachin and make sure there were no breaking changes that we need to adjust to vs do we just need to disable it being behind a flag.

**Comment by craxal** [comment]
ADLS Gen2 snapshots has feature parity with ordinary blobs. No additional features have been requested as of yet. I'll keep this issue open and close with snapshots is made GA.

**Comment by jinglouMSFT** [comment]
@craxal I was told that there have been some changes done since the preview release. Please reach out to Sachin to find out the differences and incorporate them to ASE if needed. Thanks.

**Comment by craxal** [comment]
That's not what Sachin told me, but I will schedule some time with him to make absolutely sure nothing needs to be done.

**Comment by craxal** [comment]
Sachin and I reviewed functionality in Storage Explorer, and everything looked fine on his end. Nothing else for us to do.
