### ISSUE TITLE
Write Documentation for Features and Create a  "Start Page"

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#406]
Customers sometimes reach out to support asking for help on how to use certain features. Let's do a better job of documenting features, and then exposing the docs from something like a "Start Page". If anyone has requests for what they'd like documented, feel free to comment on this issue.

**Comment by MRayermannMSFT** [comment]
No one commented. 😢

**Comment by craxal** [comment]
A start page has been designed for 1.25.0 in response to #5555.
