### ISSUE TITLE
Sign-In Error

### ISSUE THREAD

**Issue by crappie2007** [microsoft/AzureStorageExplorer#4066]
{
  "message": "\"Unexpected token format: https://login.microsoftonline.com/common/oauth2/nativeclient?error=access_denied&error_description=AADSTS90123%3a+The+token+can%27t+be+issued+because+the+identity+or+claim+issuance+provider+denied+the+request.+Response+code%3a+access_denied.%0d%0aTrace+ID%3a+9a828e4e-c258-4476-9a00-ef1bfd8fa501%0d%0aCorrelation+ID%3a+a534a12d-55b0-4408-b9a5-8db90d7a4ded%0d%0aTimestamp%3a+2021-02-05+01%3a42%3a49Z\""
}

**Comment by MRayermannMSFT** [comment]
@crappie2007 can you please update to at least version 1.19.0, try signing in, and then if things don't work we can go from there?
