### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by mukerjimca** [microsoft/AzureStorageExplorer#4067]
Access provided.
![Screenshot](https://user-images.githubusercontent.com/78594176/107023473-b43fc700-67cc-11eb-99ed-54d25238f711.jpg)

**Comment by MRayermannMSFT** [comment]
@mukerjimca 
- is the URL correct (is the storage account name typed correctly)?
- are you behind a proxy? See our troubleshooting guide for more help with proxy: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#proxy-issues
- have you tried doing this on another network?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having this problem please open a new issue.
