### ISSUE TITLE
The button 'Clone' is not translated in the localized 'Clone Blob with New Name' dialog for one blob

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#4072]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20210206.3
**Branch**: main
**Language**: All
**Platform/OS**: Windows 10/ CentOS 7.6.1810 (Core)/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Previous release(1.17.0)

## Steps to Reproduce ##

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Italiano' -> Restart Storage Explorer.
3. Expand one storage account -> Blob Containers.
4. Create a blob container -> Upload blobs to it -> Right click one blob -> Click the localized action 'Clone...'.
5. Observe the localized dialog -> Check whether the button 'Clone' is translated or not.

## Expected Experience ##
The button 'Clone' is translated.
![image](https://user-images.githubusercontent.com/54055206/107141467-d28bfb00-6963-11eb-9796-98346bcad165.png)

## Actual Experience ##
The button 'Clone' is not translated.
![image](https://user-images.githubusercontent.com/54055206/107141465-cef87400-6963-11eb-89e0-3f316bec2931.png)

## Additional Context ##

1. This issue also reproduces for one blob folder.
2. This issue doesn't reproduce for one blob container.

**Comment by MRayermannMSFT** [comment]
This was fixed at some point: 
![image](https://user-images.githubusercontent.com/21112697/114242725-3a4ccb00-9940-11eb-91fc-e1eddea1e5bf.png)
