### ISSUE TITLE
The string 'Signing key' is not localized in the 'Shared Access Signature' dialog for one blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4074]
**Storage Explorer Version:** 1.17.0
**Build Number:** 20210206.3
**Branch:** main
**Language:** All
**Platform/OS:** ia32/x64
**Architecture:** Windows 10/ CentOS 7.6.1810 (Core)/ MacOS Catalina 
**Regression From:** Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Italiano' -> Restart Storage Explorer.
3. Expand one storage account -> Blob Containers.
4. Create a blob container and right click it.
5. Click the localized 'Get Share Access Signature...'.
6. Check whether all the strings in the 'Shared Access Signature' dialog are localized or not. 

## Expected Experience ##
All strings are localized.

## Actual Experience ##
The string 'Signing key' is not localized.
![image](https://user-images.githubusercontent.com/41351993/107142578-fe5eaf00-696a-11eb-94c6-536fcc7aace1.png)

**Comment by JasonYeMSFT** [comment]
Waiting for translation.

**Comment by MRayermannMSFT** [comment]
@cristianosuzuki77 any idea why this hasn't been translated for more/all languages yet? I'm only seeing translations for `nl` and `hu`.

**Comment by cristianosuzuki77** [comment]
Are you building from main?
The translation for main in the internal ADO for Italian shows the translated resource.

**Comment by MRayermannMSFT** [comment]
@cristianosuzuki77 yep, this appears to have been addressed in the past 18 days. Thanks!
