### ISSUE TITLE
Error while viewing queues in latest storage emulator (v 5.6.0.0)

### ISSUE THREAD

**Issue by mithunshanbhag** [Microsoft/AzureStorageExplorer#408]
**Storage Explorer Version**: 1.3.0
**Platform/OS Version**: Windows
**Architecture**: ia32
**Regression From**: Previous version (after "checking for updates" in previous version, I updated to this version 1.3.0).

#### Steps to Reproduce: ####
1. After "checking for updates" in previous version, I updated to version 1.3.0.
2. When attempting to check queues in my local storage emulator, the storage explorer complained about the emulator's REST API having changed and it offered to auto-download the newest version of the storage emulator (unfortunately I don't remember the exact popup dialog text).
3. After it auto-downloaded the latest storage emulator (5.6.0.0), it is now showing below error dialog whenever I attempt to view any queue/table/blob in local storage emulator.

#### Expected Experience: ####
I'd expect to be able to view my queues/tables/blobs from local storage emulator.

#### Actual Experience: ####
I get the error dialogs (pasted below). Please let me know if any additional details are required to troubleshoot this. 

![image](https://user-images.githubusercontent.com/2327905/42618617-3286145e-85d3-11e8-8866-e12bc17e8bf4.png)

![image](https://user-images.githubusercontent.com/2327905/42626606-60f54d68-85e8-11e8-9652-00c936b52881.png)

![image](https://user-images.githubusercontent.com/2327905/42618910-00b5f5b0-85d4-11e8-9252-fe89c5d2bd55.png)

![image](https://user-images.githubusercontent.com/2327905/42619013-65f39bee-85d4-11e8-9c01-8de43f0277e7.png)

**Comment by craxal** [comment]
Did you restart the emulator after updating? Storage Explorer doesn't autorun the emulator anymore.

**Comment by mithunshanbhag** [comment]
Ok, yes that's it. Thanks.
Had to manually restart the emulator to get it working. 
Closing this issue/bug now.

**Comment by craxal** [comment]
For future reference, you can check the [Get Started](https://docs.microsoft.com/en-us/azure/vs-azure-tools-storage-manage-with-storage-explorer?tabs=windows#work-with-local-development-storage) page (we just updated the documentation).
