### ISSUE TITLE
Fail to expand the services under one attached local emulator account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4080]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20210208.7
**Branch**: feature/connect
**Emulator:** Azurite 3.10.0, Microsoft Azure Storage Emulator 5.10.0
**Platform/OS**: Windows 10
**Architecture**: ia32
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Install and start Microsoft Azure Storage Emulator 5.10.0 -> Open Storage Explorer.
2. Open connect dialog by right clicking the second plug button in the vertical toolbar.
3. Select 'Local storage emulator' -> Click 'Next' (Keep the default ports) -> Click 'Connect'.
4. Try to expand the services under the local attached account 'Local-1 (Key)'.
5. Check whether it is succeed to expand the services.

## Expected Experience ##
Succeed to expand.

## Actual Experience ##
Fail to expand.

The error screenshot when trying to expand the 'Blob Containers' node:
![image](https://user-images.githubusercontent.com/41351993/107336335-ee260b80-6af3-11eb-8fb6-118cdd98687b.png)

## Additional Context ##
1. This issue also reproduces when using Azurite 3.10.0.
2. This issue doesn't reproduce when checking the option 'Use HTTP (not recommended)'.

**Comment by craxal** [comment]
@v-xianya Does this reproduce if you attach using the old dialog? Does this reproduce on a build from the main branch?

**Comment by craxal** [comment]
Ah, yes, the problem is we're inserting HTTPS, which doesn't work. Easy fix.
