### ISSUE TITLE
There is no warning message 'The name of the account is required' after pasting the primary key to the 'connect info' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4083]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20210208.7
**Branch**: feature/connect
**Platform/OS**: Windows 10/ CentOS 7.6.1810 (Core)/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Select one storage account -> Right click it -> Click 'Copy Primary Key'.
2. Open connect dialog by right clicking the second plug button in the vertical toolbar.
3. Select 'Storage account -> Account name and key' -> Click 'Next'.
4. Paste the primary key to the 'Account key' text box.
5. Observe whether there is a warning message.

## Expected Experience ##
There is a warning 'The name of the account is required'.
![image](https://user-images.githubusercontent.com/41351993/107340111-5545bf00-6af8-11eb-9ad0-314ab460149e.png)

## Actual Experience ##
There is no warning message 'The name of the account is required'.
![image](https://user-images.githubusercontent.com/41351993/107339707-f41deb80-6af7-11eb-9d81-9ef6dc535d49.png)

## Additional Context ##
The warning message shows after typing the account name and then deleting it.

**Comment by craxal** [comment]
I don't think this is something that needs to be fixed. As long as the Next button id disabled, a warning message isn't necessary until the user has actually entered something that needs to be validated.
