### ISSUE TITLE
No error warning displays when typing other service's URL in the 'Anonymously connect blob container' dialog

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#4084]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20210208.7
**Branch**: feature/connect
**Platform/OS**: Windows 10/ CentOS 7.6.1810 (Core)/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##

1. Open connect dialog by right clicking the second plug button in the vertical toolbar.
2. Select 'Blob Container -> Anonymously(my blob container allows public access)'.
3. Type the URL of one file share to the 'Blob container URL' text box.
4. Check whether an error warning displays or not.

## Expected Experience ##
An error warning displays.
![image](https://user-images.githubusercontent.com/54055206/107341929-9212b580-6afa-11eb-9b8c-d611e59e0661.png)

## Actual Experience ##
No error warning displays.
![image](https://user-images.githubusercontent.com/54055206/107341945-963ed300-6afa-11eb-91fd-ccc492faa10b.png)

## Additional Context ##
This issue also reproduces for one ADLS Gen2 blob container.

**Comment by craxal** [comment]
By design. Azure supports custom domains for blob endpoints, which can take any form.

**Comment by craxal** [comment]
We had some discussion about how to handle cases like this. We will use the following rules when validating URLs:

1. If the URL entered has a default endpoint suffix, but the service type doesn't match what the user is trying to connect to, we will consider that an error and block advance (for example, acct.blob.core.windows.net is not valid for attaching to a file service).
2. If the URL entered does not have a default endpoint suffix for any service, we display a warning but let the user advance (for example, mycustomendpoint.com will raise a warning but can be used to connect to any service).
