### ISSUE TITLE
Fail to upload files to one SAS attached blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4087]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20210208.7
**Branch**: feature/connect
**Platform/OS**: Windows 10/ CentOS 7.6.1810 (Core)/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container.
3. Right click the blob container -> Generated a SAS with full permissions.
4. Attach the blob container via the connect dialog opened by the second plug icon.
5. Upload one blob to the SAS attached blob container.
6. Check the result.

## Expected Experience ##
Succeed to upload.

## Actual Experience ##
Fail to upload.
![image](https://user-images.githubusercontent.com/41351993/107349968-d0f93900-6b03-11eb-86cb-620aea506c0d.png)
`
RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
`
## Additional Context ##
1. This issue also reproduces for the Copy & Paste/ Clone/ Delete actions.
2. This issue also reproduces for ADLS Gen2 blob containers (Upload/ Copy & Paste) actions.

**Comment by craxal** [comment]
@v-xianya Does this reproduce if you attach using the old dialog? Does this reproduce on a build from the main branch? Can you share the SAS that you used to attach?

**Comment by craxal** [comment]
Looks like the problem is I forgot to strip off the "?" when storing the connection. Easy fix.
