### ISSUE TITLE
Fail to rename one blob under one SAS attached ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4088]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20210208.7
**Branch**: feature/connect
**Platform/OS**: Windows 10/ CentOS 7.6.1810 (Core)/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one blob to it.
3. Right click the blob container -> Generated a SAS with full permissions.
4. Attach the blob container via the connect dialog opened by the second plug icon.
8. Open the SAS attached blob container -> Rename the blob.
9. Check whether the blob can be renamed successfully.

## Expected Experience ##
Succeed to rename.

## Actual Experience ##
Fail to rename.
`"name": "RangeError",
  "message": "Destination path should not contain more than one query string",
  "stack": "RangeError: Destination path should not contain more than one query `
  
## Additional Context ##
1. Fail to delete one blob under the SAS attached blob container.
`"message": "\"failed to perform remove command due to error: cannot start job due to error: cannot verify resource due to error: -> github.com/Azure/azure-storage-azcopy/azbfs.newStorageError, `

2. Fail to move one blob under the SAS attached blob container.
`{
  "message": "[{}]"
}`

**Comment by craxal** [comment]
@v-xianya Did you use the new or the old experience? Does this reproduce on a build from the main branch? Can you share the SAS that you used to attach?

**Comment by craxal** [comment]
Looks like the problem is I forgot to strip off the "?" when storing the connection. Easy fix.
