### ISSUE TITLE
There is no error when using an ADLS Gen2 blob container's URL to Azure AD attach

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4090]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20210208.7
**Branch**: feature/connect
**Platform/OS**: Windows 10/ CentOS 7.6.1810 (Core)/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Add a RBAC role 'Storage Blob Data Owner' and assign it to one member.
3. Copy the URL of the blob container.
4. Open connect dialog by right clicking the second plug button in the vertical toolbar.
5. Select 'ADLS Gen2 Blob container or directory -> Sign in using Azure Active Directory (Azure AD)' -> Click 'Next'.
6. Select the Azure account with access to the blob container -> Click 'Next'.
6. Paste the 'URL' to the 'Blob container or directory URL' text box.
7. Check whether an error occurs.

## Expected Experience ##
An error occurs.
![image](https://user-images.githubusercontent.com/41351993/107356358-ac08c400-6b0b-11eb-9373-2601241195c5.png)

## Actual Experience ##
1. No error occurs.
![image](https://user-images.githubusercontent.com/41351993/107355759-e45bd280-6b0a-11eb-9bdb-616dd9c43da5.png)

2. The Azure AD attached blob container works fine.

## Additional Context ##
This issue also reproduces for one ADLS Gen2 directory.

**Comment by craxal** [comment]
By design. Both blob and DFS endpoints are accepted when connecting to an ADLS Gen2 resource.
