### ISSUE TITLE
azure account verification does not work

### ISSUE THREAD

**Issue by agribot2** [microsoft/AzureStorageExplorer#4092]
**Storage Explorer Version**:  1.17
**Build Number**:  20201211.10
**Platform/OS**:  Windows 10
**Architecture**: laptop using intel i5 
**Regression From**:  this defect was seen from the very first time the storage explorer was installed ( today feb 09 )

## Bug Description ##
the account log on and verification does not work. It just repeatedly loops in the verification mode ... send code ... enter code..sign in to account ... it just displays the sign in and then the verification screens, even when I correctly enter account details and the code that the system emails to my account. After about 3 - 5 time, it eventually accepts the data entered and displays the cloud based azure data and resources.

## Steps to Reproduce ##
launch the storage explorer
select my user account
enter my user account password
go through the verification process
enter the code emailed to me
go through the account sign in screens ( again )
go through the verification process again
enter the new code in a new email
loop again
loop again
eventually the storage explorer detects my azure account  and displays storage accounts and discs, etc

## Expected Experience ##
something better than this !

**Comment by easp** [comment]
+1 I've had the same experience since I first tried using this a week and a half ago on MacOS.

**Comment by JasonYeMSFT** [comment]
Are you using the default ADAL sign-in or MSAL? You can find it the settings panel under Settings -> Sign-in -> Microsoft Authentication Library. If you haven't tried MSAL, could you try it and see if it works better?

The reason why you are seeing multiple account verification is that your account is in multiple tenants. Each tenant needs to be verified independently.

**Comment by easp** [comment]
Thanks for the reply. MSAL is not enabled, so I guess that means I'm using ADAL?

One thing is for sure, I don't have these issues when using the various VS code extensions to access CosmosDB and Blob storage.
