### ISSUE TITLE
Unable to see some folders while trying to upload

### ISSUE THREAD

**Issue by kashyap-bhatt-by** [microsoft/AzureStorageExplorer#4093]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20201211.10
**Platform/OS**: Linux. Ubuntu 18.04
**Architecture**: x64
**Regression From**: Don't know. First time.

## Bug Description ##
* In a Gen2 storage account. I click `Upload -> File` and try to select folder `workspaces` (which is a link to another folder) the file selection dialog closes and selects `workspaces` as the file to upload.
* If I open file explorer (`pcmanfm`) and drag and drop files from inside this workspaces folder into a folder in storage explorer (some container) it does nothing. If I goto `Desktop` and do same for some other file, it works, i.e. the file is uploaded to that container.
* If I goto `/` I do not see `/disk2` at all in Storage Explorer's file selector.

```
kash@kash-lubuntu:~$ ls -ld /home/kash/workspaces
lrwxrwxrwx 1 kash kash 17 Jan 24  2019 /home/kash/workspaces -> /disk2/workspaces
kash@kash-lubuntu:~$ ls -la /disk2/
total 32
drwxrwxrwx  5 root root  4096 Jun 12  2020 .
drwxr-xr-x 26 root root  4096 Jan 28 17:08 ..
drwx------  2 root root 16384 Jan 24  2019 lost+found
drwx------  5 kash kash  4096 Jan  6 16:15 .Trash-1000
drwxrwxr-x 33 kash kash  4096 Jan 22 22:13 workspaces
kash@kash-lubuntu:~$ mount | grep disk2
/dev/sdb1 on /disk2 type ext4 (rw,relatime,errors=remount-ro,data=ordered)
kash@kash-lubuntu:~$ 
```

OS
```
kash@kash-lubuntu:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
kash@kash-lubuntu:~$ 
```

## Steps to Reproduce ##
* Add a new disk to your machine.
* Mount it.
* Try to upload files from it.

![See this Image for some visual description](https://i.imgur.com/7sC42wX.png)

Note the icons for `workspace` folder in File Open dialog vs File Manager.

**Comment by JasonYeMSFT** [comment]
Out of curiosity, if you navigate into that directory in the File Manager, what is the path of the files in that directory? Could you create the folder in Storage Explorer first, enter the directory and then try drag and drop files to Storage Explorer to upload the files?

**Comment by kashyap-bhatt-by** [comment]
> if you navigate into that directory in the File Manager, what is the path of the files in that directory?

Didn't quite understand that. Path is "that directory", the one I navigate to.

> Could you create the folder in Storage Explorer first, enter the directory and then try drag and drop files to Storage Explorer to upload the files?

Not sure what you want me to do? From "File Open" dialog of Storage Explorer, I can not go into `workspaces`. Because it's not recognized as a folder, if I double click it then it is selected as a file and File Open dialog closes, instead of navigating into `workspaces` and showing it's sub-folders.

**Comment by JasonYeMSFT** [comment]
In "File Manager" (not our File Open dialog), if you double click on a folder, it navigates into the folder and show you the files/folders in it, right? What I am asking you to try is to double click on the "workspace" folder to navigate into it in your File Manager and show me what's the path being displayed in the address bar, like this 
![image](https://user-images.githubusercontent.com/39359541/109203322-de93fd00-7758-11eb-9344-9ab397406871.png)

And since you can see files in the "workspace" directory, you can try dragging them to Storage Explorer to see if they can be uploaded.

**Comment by kashyap-bhatt-by** [comment]
That's part of OP.

> If I open file explorer (pcmanfm) and drag and drop files from inside this workspaces folder into a folder in storage explorer (some container) it does nothing. If I goto Desktop and do same for some other file, it works, i.e. the file is uploaded to that container.

**Comment by JasonYeMSFT** [comment]
Gotcha. This is something we haven't seen so far. We'll investigate where things get broken.

**Comment by JasonYeMSFT** [comment]
I attempted to reproduce this issue on a Ubuntu 18.04 but wasn't able to. What I did was
- Connect an external drive to the machine, which shows up at /media/user_name/drive_name
- Create a symlink in the user's root directory /home/user_name/directory -> /media/user_name/drive_name
- Open it in File Manager and try opening it in the Upload dialog

In both cases, I am able to see the symlink showing up as a directory. I am able to upload that directory using the .tar.gz build but I run into some disk permission issue when using the snap install.

So in your case @kashyap-bhatt-by
- Are you using snap install or the .tar.gz? If you are using snap, would you like to try the .tar.gz build?
- How did you create the symlink? I created mine using just the -s option.

**Comment by kashyap-bhatt-by** [comment]
@JasonYeMSFT 

>     * Connect an external drive to the machine, which shows up at /media/user_name/drive_name
A few differences from OP:
* Mine was an Ubuntu VM on an Oracle Virtual Box.
* Disk was added by going to VM Settings->Storage->Add hard disk
* It appeared under `/dev/` (not `/media`), which is `root` owned (and not `user_name` owned like home)

>     * Are you using snap install or the .tar.gz? If you are using snap, would you like to try the .tar.gz build?

Using snap. Can try tar. Can you provide link to any specific version you want me to try?

> 
>     * How did you create the symlink? I created mine using just the -s option.
Same. Used `ln -s`.

**Comment by JasonYeMSFT** [comment]
To use the tar.gz build, download the 1.18.1 Linux_StorageExplorer-x64.tar.gz, extract it and execute the StorageExplorer executable in the directory. You might need to install some dependencies depending on your OS image.

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. If you have tried the tar.gz and still run into problems, please open a new issue instead.
