### ISSUE TITLE
Not able to authenticate using AAD

### ISSUE THREAD

**Issue by saumyabahuk** [microsoft/AzureStorageExplorer#4094]

**Comment by JasonYeMSFT** [comment]
@saumyabahuk Could you give more info on the Storage Explorer version, platform running on and exact steps you tried to hit the issue?

**Comment by saumyabahuk** [comment]
> @saumyabahuk Could you give more info on the Storage Explorer version, platform running on and exact steps you tried to hit the issue?

Hi Jason, 
The version of storage explorer being used is 1.14.1
To repro the issue- tried to connect to a gen2 preprod resource using an alternate account on storage explorer. On using the pin for authentication, it gives an error mentioning no valid credentials found, inspite of the alt card working fine.

**Comment by MRayermannMSFT** [comment]
@saumyabahuk please upgrade to the latest version of Storage Explorer. You can download it at https://www.storageexplorer.com .

**Comment by MRayermannMSFT** [comment]
Closing due to a lack of response. If you are still seeing this problem please open a new issue. Thanks.
