### ISSUE TITLE
It is hard to see the icon of the resource 'Local storage emulator' under the 'High Contrast -Black' theme

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4096]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20210210.3
**Branch**: feature/connect
**Platform/OS**: Windows 10/ CentOS 7.6.1810 (Core)/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ## 
1. Open Storage Explorer -> Go to the 'View' menu -> Change the theme to 'High Contrast - Black'.
2. Open the new connect dialog.
3. Check whether all icons are clear to see.

## Expected Experience ##
All icons are clear to see.

## Actual Experience ##
It is hard to see the icon of the resource 'Local storage emulator'.
![image](https://user-images.githubusercontent.com/41351993/107481451-0ec18600-6b33-11eb-943f-6563c573767b.png)

  
## Additional Context ##
This issue also reproduces under the 'Dark' theme.

**Comment by craxal** [comment]
@v-xianya Thanks for noticing. It was just a placeholder icon, but we've swapped it out with a proper one.
