### ISSUE TITLE
Authentication error: undefined

### ISSUE THREAD

**Issue by maeehart** [microsoft/AzureStorageExplorer#4097]
**Storage Explorer Version**: <1.17
**Build Number**: 20201211.10
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  Was working previously and still works on Linux.

## Bug Description ##
When I try to connect using a connection string that worked previously and still works on Linux, the connection seems to work. However, when I try to open the Tables, I get an error message "Authentication error: undefined".

![image](https://user-images.githubusercontent.com/7577988/107506040-3271e400-6ba6-11eb-8a9a-5acfc5170cbc.png)

## Steps to Reproduce ##
See above

## Expected Experience ##
I see the tables

## Actual Experience ##
Error message: Authentication error: undefined
## Additional Context ##
Nothing unusual.

**Comment by JasonYeMSFT** [comment]
@maeehart Does this constantly reproduce? Have you tried this in 1.17.0 and does it work there? Also could you share the connection string after redacting your credentials (e.g. account key, etc.)?

**Comment by maeehart** [comment]
It reproduced constantly for some days. No matter if I reinstalled Storage explorer or what. Al the time, the connection string worked on Linux.

Now, a couple of days ago it started working without me having to do anything. Cannot reproduce the problem anymore, so I will close.
