### ISSUE TITLE
Search speed times are WAY too slow

### ISSUE THREAD

**Issue by ahyerman** [microsoft/AzureStorageExplorer#4098]
**Is your feature request related to a problem? Please describe.**
When searching for a container in blob it took me 20 min to complete a basic operation because finding the right blob took WAY too long to search for.

**Describe the solution you'd like**
I'd like search to return within 5 seconds.

**Describe alternatives you've considered**
An alternative would be to allow bulk downloads directly from portal.azure.com

**Additional context**
None necessary.

**Comment by JasonYeMSFT** [comment]
Are you trying to search for a blob container with a known name? Will the proposed solution here meet your needs? https://github.com/microsoft/AzureStorageExplorer/issues/75

**Comment by craxal** [comment]
Duplicate of #2326.

**Comment by ahyerman** [comment]
@JasonYeMSFT I used the same solution as recommended in #75 - "search from here" and times were still unbelievably slow.

**Comment by JasonYeMSFT** [comment]
Sorry I didn't make it clear, it is something we are going to add which isn't in the product yet. We will make it fast enough so it can bee a workaround.
