### ISSUE TITLE
The uploaded page blob displays 'P10' under 'Access Tier' column for one premium account

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#410]
**Storage Explorer Version**: 1.3.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180711.4
**Commit**: 47039639
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Go to Subscription -> Storage Accounts.
2. Choose one premium account -> Open one blob container and upload one page blob.
3. Check the item under 'Access Tier' column.

#### Expected Experience: ####
No access tier displays under 'Access Tier' column.

#### Actual Experience: ####
'P10' displays under 'Access Tier' column.
![p10](https://user-images.githubusercontent.com/34729022/42625942-9412d90c-85b8-11e8-8338-665ab37c9412.png)

#### More info: ####
1. It doesn't display after refreshing the editor.
2. It still displays on 'Properties' dialog for the page blob.

**Comment by craxal** [comment]
Actually, we should _expect_ that to appear in the Access Tier column. P10 is a perfectly valid access tier for page blobs in premium storage.

**Comment by v-xuanzh** [comment]
P10 doesn't display in the Access Tier column after refreshing the editor. Is it still expect?

**Comment by craxal** [comment]
Yes, we can't do much about that. The platform doesn't always give us the value.
