### ISSUE TITLE
Can't resize Cosmos DB Documents view enough to see full ID

### ISSUE THREAD

**Issue by 1RedOne** [microsoft/AzureStorageExplorer#4100]
**Storage Explorer Version**: 1.17.0
**Build Number**:  20201211.10
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  No

## Bug Description ##
When viewing a list of Cosmos Documents, I cannot resize the view to see the ID of my data.

## Steps to Reproduce ##
1. Have a Cosmos DB  account attached
2. Have some documents
3. Try to resize the view
4. It won't allow you to resize!

![image](https://user-images.githubusercontent.com/1247626/107803123-329deb00-6d30-11eb-901a-2beed42f06b3.png)

## Expected Experience ##
It would be expected to resize the view to see the full id column.  

## Actual Experience ##
Right now, it's truncated and you cannot resize beyond 25% or chose your columns, and you also cannot resize the viewing area eiteher.  

![image](https://user-images.githubusercontent.com/1247626/107803307-6f69e200-6d30-11eb-8d27-df3f8d4fb63f.png)
![image](https://user-images.githubusercontent.com/1247626/107803455-97594580-6d30-11eb-9c22-d217736258a0.png)

The true underlying issue is probably that this ViewArea is made of a stack panel and the left element has a maximum size of 25%.  If this were increased, then the user could freely resize.

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
