### ISSUE TITLE
Unable to create folder in Data lake from Storage explorer - Intermittent issue

### ISSUE THREAD

**Issue by betinaalex26** [microsoft/AzureStorageExplorer#4103]
{
  "name": "FetchError",
  "message": "request to https://hostname/data/AA%2FBB%2FCC%2FDD%2FEE?resource=directory&timeout=60 failed, reason: tunneling socket could not be established, statusCode=407",
  "type": "system",
  "errno": "ECONNRESET",
  "code": "ECONNRESET",
  "stack": "FetchError: request to https://hostname/data/AA%2FBB%2FCC%2FDD%2FEE?
resource=directory&timeout=60 failed, reason: tunneling socket could not be established, statusCode=407\n    at ClientRequest.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1455:11)\n    at ClientRequest.emit (events.js:182:13)\n    at ClientRequest.onConnect (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\ms-rest-js\\node_modules\\tunnel\\lib\\tunnel.js:157:23)\n    at Object.onceWrapper (events.js:273:13)\n    at ClientRequest.emit (events.js:182:13)\n    at Socket.socketOnData (_http_client.js:474:11)\n    at Socket.emit (events.js:182:13)\n    at addChunk (_stream_readable.js:283:12)\n    at readableAddChunk (_stream_readable.js:264:11)\n    at Socket.Readable.push (_stream_readable.js:219:10)"
}

**Comment by JasonYeMSFT** [comment]
This may be due to your proxy server not being available all the time.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem please open a new issue. Thanks!
