### ISSUE TITLE
Update 'SAS URL' to 'SAS URI' in the 'Connect Info' dialog when using the SAS URI to attach one resource

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4107]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20210218.1
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ## 
1. Open Storage Explorer -> Open the connect dialog.
2. Select 'Blob container' -> Select 'Shared access signature (SAS)' -> Click 'Next'.
3. Observe the string 'Blob Container SAS URL'.

## Expected Experience ##
Show 'Blob container SAS URI'.

## Actual Experience ##
Show 'Blob container SAS URL'
![image](https://user-images.githubusercontent.com/41351993/108328625-cc213d00-7207-11eb-9d78-0feec72c8942.png)

## Additional Context ##
This issue also reproduces for one ADLS Gen2 blob & directory/ file share/ queue/ table.

**Comment by craxal** [comment]
@v-xianya By design. We decided to use the term "URL" from now on, as it is more accurate for what we need users to enter here.
