### ISSUE TITLE
The shortcut of 'Ctrl+V' works well on blob snapshot editor

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#411]
**Storage Explorer Version**: 1.3.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180711.4
**Commit**: 47039639
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Go to Subscription -> Storage Accounts.
2. Open one blob container and upload one blob to it.
3. Open the manage snapshot editor for the blob -> Copy another blob then press 'Ctrl+V' on the editor.

#### Expected Experience: ####
'Ctrl+V' doesn't work.

#### Actual Experience: ####
The shortcut of 'Ctrl+V' works well.
![ctrlv](https://user-images.githubusercontent.com/34729022/42627848-c4501eea-85bd-11e8-850b-a84ac7768b2a.png)

**Comment by v-xianya** [comment]
Verified with build 20181220.1. 
The shortcut of 'Ctrl+V' still works well but the blob can't be copied successfully.
![image](https://user-images.githubusercontent.com/41351993/50396535-96a67380-07a5-11e9-8cf9-5c8ec416e9d7.png)

**Comment by jinglouMSFT** [comment]
This works fine for me on 1.6.1 (build 20181218.1).  @v-xianya can you try this on v1.6.1 and also let us know which branch you used for build 20181220.1?  Thanks.

**Comment by v-xianya** [comment]
Thanks for your updates. Verified on 1.6.1(build 20181218.1), **Ctrl+V** works well and the copied blob doesn't show in Snapshots editor after refreshing manually.
![image](https://user-images.githubusercontent.com/41351993/50624568-92741600-0f5c-11e9-8f3a-88b55d7dd57f.png)

And we used hotfix/1.6.1 branch for build [20181220.1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2290278&view=results).

**Comment by v-xianya** [comment]
@jinglouMSFT  Hi, Jing
Verified this issue on build [20191220.9](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3338616). 
1. Ctrl+V works well in the snapshot editor.
2. The copied blob displays in the blob container editor.
![image](https://user-images.githubusercontent.com/41351993/71573010-b5f48100-2b1c-11ea-9ac0-5c81a6fffab4.png)

**Comment by MRayermannMSFT** [comment]
When in the snapshot view, ctrl+v should not do anything. The snapshot view is read only, and paste is a write operation. Let's double check that this the reality in the product, and if not fix it.

**Comment by v-xianya** [comment]
This issue is fixed on build master/ [20200509.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3715211&view=results). So we close it.
