### ISSUE TITLE
The attached regular blob container displays as an ADLS Gen2 blob container when using the 'ADLS Gen2 Blob container or directory' sas dialog to attach

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#4110]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20210218.1
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Select one blob container then creating a SAS URI -> Copy the SAS URI.
3. Open connect dialog -> Select 'ADLS Gen2 Blob container or directory -> Shared access signature(SAS)'.
4. Paste the URI then clicking 'Next' -> Click 'Connect'.
5. Observe the attached blob container -> Check whether the attached regular blob container displays normal.

## Expected Experience ##
The attached regular blob container displays normally.

## Actual Experience ##
The attached regular blob container displays as an ADLS Gen2 blob container.

## Additional Context ##
This issue doesn't reproduce for one ADLS Gen2 blob container via the 'Blob container' sas dialog to attach.

**Comment by JasonYeMSFT** [comment]
Our logic for detecting HNS info will be overridden when the user selects to connect to ADLS Gen2 blob containers, because it sometimes doesn't work due to type of credentials used. We aren't going to fix this for now since we expect people to choose the correct resource type to connect to.
