### ISSUE TITLE
The 'Back' button is disabled on the 'Sign In' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4118]
**Storage Explorer Version:** 1.17.0
**Build Number:** 20210219.2
**Branch:** main
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture:** ia32/x64
**Regression From:** Previous build (20210218.1)

## Steps to Reproduce ##
1. Launch Storage Explorer -> Open the connect dialog.
2. Click 'Subscription' -> Click 'Next'.
3. Check whether the 'Back' button is enabled or not on the 'Sign In' dialog.

## Expected Experience ##
The 'Back' button is enabled.
![image](https://user-images.githubusercontent.com/41351993/108487011-b8460b80-72d9-11eb-8536-1352e48395c7.png)

## Actual Experience ##
The 'Back' button is disabled.
![image](https://user-images.githubusercontent.com/41351993/108486996-b419ee00-72d9-11eb-8b27-7d963928a01e.png)

**Comment by craxal** [comment]
@v-xianya I don't think this can be considered a regression, as this hasn't shipped yet. This is by design. However, we should probably consider whether it makes sense to enable the Back button for device code flow scenarios.

**Comment by v-xianya** [comment]
Hi @craxal This issue still reproduces for normal sign in scenarios.
![image](https://user-images.githubusercontent.com/41351993/108579614-c7bd6700-7362-11eb-92f6-6105772a0f2c.png)

**Comment by v-xianya** [comment]
Verified this issue on build rel/1.18.0 20210223.2. Fixed.
