### ISSUE TITLE
Remove the default red border for the 'Display name' on 'Attach to Local Emulator' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#412]
**Storage Explorer Version**: 1.3.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180711.4
**Commit**: 47039639
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Go to Subscription -> Storage Accounts.
2. Open the 'Connect' dialog and select 'Attach to a local emulator'.

#### Expected Experience: ####
No default red border displays for the Display name.

#### Actual Experience: ####
A red border displays for the Display name.
![red](https://user-images.githubusercontent.com/34729022/42626896-fd11ecc0-85ba-11e8-8739-e80be75427e1.png)

**Comment by MRayermannMSFT** [comment]
Let's give this field a default value of like "Emulator1", "Emulator2" etc.
