### ISSUE TITLE
Explorer issue on mac 

### ISSUE THREAD

**Issue by gsajwan** [microsoft/AzureStorageExplorer#4121]
I just installed explorer on Mac and the below pop-up window came up. 

Unable to retrieve child resources.

Details:
{
  "name": "Error",
  "message": "Hub Controller process exited prematurely with signal 'SIGABRT'.",
  "__zone_symbol__error": {
    "originalStack": "Error: Hub Controller process exited prematurely with signal 'SIGABRT'.\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at ControllerConnection.onControllerProcessExited (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:135:21)\n    at ChildProcess.<anonymous> (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:96:93)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:275:35)\n    at Zone.runTask (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:151:47)\n    at ChildProcess.ZoneTask.invoke (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:345:33)\n    at ChildProcess.emit (events.js:215:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)",
    "zoneAwareStack": "Error: Hub Controller process exited prematurely with signal 'SIGABRT'.\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at ControllerConnection.onControllerProcessExited (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:135:21)\n    at ChildProcess.<anonymous> (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:96:93)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:275:35)\n    at Zone.runTask (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:151:47)\n    at ChildProcess.ZoneTask.invoke (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:345:33)\n    at ChildProcess.emit (events.js:215:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)"
  },
  "stack": "Error: Hub Controller process exited prematurely with signal 'SIGABRT'.\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at ControllerConnection.onControllerProcessExited (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:135:21)\n    at ChildProcess.<anonymous> (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:96:93)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:275:35)\n    at Zone.runTask (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:151:47)\n    at ChildProcess.ZoneTask.invoke (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:345:33)\n    at ChildProcess.emit (events.js:215:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)\nFrom previous event:\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at defer (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/node_modules/q/q.js:582:19)\n    at Promise.then (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/node_modules/q/q.js:828:20)\n    at ControllerConnection.connectImpl (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:48:14)\n    at Function.ControllerConnection.connect (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:31:27)\n    at HubLookup.getLocationService (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/hubLookup.js:20:80)\n    at HubClient.requestServiceWithRetries (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/hubClient.js:74:21)\n    at HubClient.requestService (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/hubClient.js:62:21)\n    at ElectronAadAccountProviderClient.<anonymous> (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/identity-client/dist/AadAccountProviderClient.js:57:74)\n    at Generator.next (<anonymous>)\n    at /private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/identity-client/dist/AadAccountProviderClient.js:10:71\n    at new ZoneAwarePromise (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:551:29)\n    at __awaiter (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/identity-client/dist/AadAccountProviderClient.js:6:12)\n    at /private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/identity-client/dist/AadAccountProviderClient.js:56:27",
  "originalStack": "Error: Hub Controller process exited prematurely with signal 'SIGABRT'.\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at ControllerConnection.onControllerProcessExited (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:135:21)\n    at ChildProcess.<anonymous> (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:96:93)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:275:35)\n    at Zone.runTask (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:151:47)\n    at ChildProcess.ZoneTask.invoke (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:345:33)\n    at ChildProcess.emit (events.js:215:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)",
  "zoneAwareStack": "Error: Hub Controller process exited prematurely with signal 'SIGABRT'.\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at ControllerConnection.onControllerProcessExited (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:135:21)\n    at ChildProcess.<anonymous> (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:96:93)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:275:35)\n    at Zone.runTask (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:151:47)\n    at ChildProcess.ZoneTask.invoke (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:345:33)\n    at ChildProcess.emit (events.js:215:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)",
  "__zone_symbol__stack": "Error: Hub Controller process exited prematurely with signal 'SIGABRT'.\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at ControllerConnection.onControllerProcessExited (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:135:21)\n    at ChildProcess.<anonymous> (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:96:93)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:275:35)\n    at Zone.runTask (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:151:47)\n    at ChildProcess.ZoneTask.invoke (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:345:33)\n    at ChildProcess.emit (events.js:215:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)\nFrom previous event:\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at defer (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/node_modules/q/q.js:582:19)\n    at Promise.then (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/node_modules/q/q.js:828:20)\n    at ControllerConnection.connectImpl (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:48:14)\n    at Function.ControllerConnection.connect (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:31:27)\n    at HubLookup.getLocationService (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/hubLookup.js:20:80)\n    at HubClient.requestServiceWithRetries (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/hubClient.js:74:21)\n    at HubClient.requestService (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/hubClient.js:62:21)\n    at ElectronAadAccountProviderClient.<anonymous> (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/identity-client/dist/AadAccountProviderClient.js:57:74)\n    at Generator.next (<anonymous>)\n    at /private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/identity-client/dist/AadAccountProviderClient.js:10:71\n    at new ZoneAwarePromise (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:551:29)\n    at __awaiter (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/identity-client/dist/AadAccountProviderClient.js:6:12)\n    at /private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/identity-client/dist/AadAccountProviderClient.js:56:27",
  "__zone_symbol__name": "Error",
  "__zone_symbol__message": "Hub Controller process exited prematurely with signal 'SIGABRT'.",
  "__zone_symbol__originalStack": "Error: Hub Controller process exited prematurely with signal 'SIGABRT'.\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at ControllerConnection.onControllerProcessExited (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:135:21)\n    at ChildProcess.<anonymous> (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:96:93)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:275:35)\n    at Zone.runTask (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:151:47)\n    at ChildProcess.ZoneTask.invoke (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:345:33)\n    at ChildProcess.emit (events.js:215:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)",
  "__zone_symbol__zoneAwareStack": "Error: Hub Controller process exited prematurely with signal 'SIGABRT'.\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)\n    at ControllerConnection.onControllerProcessExited (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:135:21)\n    at ChildProcess.<anonymous> (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/microsoft-servicehub/controllerConnection.js:96:93)\n    at Object.onceWrapper (events.js:300:26)\n    at ZoneDelegate.invokeTask (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:275:35)\n    at Zone.runTask (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:151:47)\n    at ChildProcess.ZoneTask.invoke (/private/var/folders/r1/4p0ytqhd6pqb2bqrv_fprb9w0000gp/T/AppTranslocation/67D774D4-B16A-49BC-888B-3825171CBA84/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:345:33)\n    at ChildProcess.emit (events.js:215:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)",
  "signal": "SIGABRT"
}

**Comment by JasonYeMSFT** [comment]
Could you try getting the logs for service hub as instructed in this issue? https://github.com/microsoft/AzureStorageExplorer/issues/3860

**Comment by MRayermannMSFT** [comment]
Closing due to lack of reply. Please open a new issue if you are still encountering this problem.
