### ISSUE TITLE
The error of an empty custom domain doesn’t disappear after switching from the ‘Other:’ domain to ‘Azure’ domain

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#4123]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20210220.4
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu16.04 / MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##

1. Launch Storage Explorer -> Open connect dialog.
2. Click 'Storage account ->  Account name and key'.
3. Focus on 'Storage domain:' in the dialog -> Select 'Other:' -> Delete the default domain.(An error displays)
4. Switch to 'Azure' -> Check whether the error disappears.

## Expected Experience ##
The error disappears.

## Actual Experience ##
The error still shows.
![image](https://user-images.githubusercontent.com/54055206/108682471-4a911e00-752b-11eb-8898-bdd725541672.png)

![image](https://user-images.githubusercontent.com/54055206/108681936-aa3af980-752a-11eb-8bc9-ee68cd690ca2.png)

## Additional Context ##
This issue also reproduces when switching to 'Azure China'/ 'Azure Germany'/ 'Us Government'.

**Comment by v-xianya** [comment]
Verified this issue on build rel/1.18.0 20210223.2. Fixed.

**Comment by v-limu** [comment]
Hi @craxal This issue reproduces again on the build main/20210601.8. So we re-open it.
![image](https://user-images.githubusercontent.com/54055206/120431690-666a5280-c3ab-11eb-8f2d-e8024813675b.png)
