### ISSUE TITLE
Unable to load the containers into storage explorer

### ISSUE THREAD

**Issue by user212475** [microsoft/AzureStorageExplorer#4124]
Unable to retrieve child resources.

Details:
{
 unable to get local issuer certificate",
 "name": "FetchError",
reason: unable to get local issuer certificate\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError;
reason: unable to get local issuer certificate\n    at ClientRequest.<anonymous> ;
(C:\\Users\\212475\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)",
  "type": "system",
  "errno": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY",
  "code": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"
}

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem please open a new issue. Thanks!
