### ISSUE TITLE
There are extra properties in the 'Properties' dialog for one ADLS Gen2 folder

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#4127]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20210223.1
**Branch**: rel/1.18.0
**Platform/OS**: Windows 10/ Linux Ubuntu16.04 / MacOS Catalina
**Architecture**:  ia32/x64
**Regression From**: Previous release(1.17.0)

## Steps to Reproduce ##

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one folder to it.
3. Right click the folder -> Click 'Properties...'.
4. Observe the dialog -> Check no extra properties shows. 

## Expected Experience ##
No extra properties shows.

## Actual Experience ##
There are the extra properties.
![image](https://user-images.githubusercontent.com/54055206/108823535-84c9f080-75fb-11eb-9024-dc9efbf6dff8.png)

**Comment by v-limu** [comment]
Hi @JasonYeMSFT verified on build 20210224.3. The extra properties 'LeaseState & LeaseDuration & LeaseStatus' still show in the dialog. So we re-open it.
![image](https://user-images.githubusercontent.com/54055206/108938495-07a37900-7605-11eb-86bb-033c8297c6c4.png)

**Comment by JasonYeMSFT** [comment]
These properties actually matters for folders. If the stub blob for leasing a directory is leased, the directory itself won't be able to be deleted. So we decided to leave it there but not supporting leasing on directories.

**Comment by v-limu** [comment]
Hi @JasonYeMSFT OK. Got it. Thanks for your updates. we will close it.😊
