### ISSUE TITLE
There are extra actions 'Upload & New Folder' in the toolbar of one public attached HNS blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4128]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20210223.2
**Branch**: rel/1.18.0
**Platform/OS**: Windows 10/ Linux ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Select one blob container -> Right click the blob container -> Select 'Set Public Access Level...'.
3. Set the container public access level to 'public read access for container and blobs'.
4. Public attach the blob container.
5. Observe the toolbar of the public attached blob container.
6. Check there is no extra actions. 

## Expected Experience ##
There are no extra actions.

The screenshot against one public regular blob container.
![image](https://user-images.githubusercontent.com/41351993/108824405-a11a5d00-75fc-11eb-99f1-e88039e79081.png)

## Actual Experience ##
There are extra actions.
![image](https://user-images.githubusercontent.com/41351993/108824180-64e6fc80-75fc-11eb-9908-6e023340900e.png)

## Additional Context ##
The screenshot against one blob/ directory under one public HNS attached blob container.
![image](https://user-images.githubusercontent.com/41351993/108824727-0706e480-75fd-11eb-906e-6c98f5baa5cb.png)

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT Verified this issue on build 20210224.3.

The action '**Create Snapshot**' for one blob under the public attached HNS blob container is enabled .
![image](https://user-images.githubusercontent.com/41351993/108942084-48e16a80-7691-11eb-9b5f-52d4977b89e6.png)

**Comment by MRayermannMSFT** [comment]
I'm 99.9% sure all actions which need to be disabled/hidden for anon attached gen2 containers are now correctly done. Let me know if I missed anything.

**Comment by v-xianya** [comment]
Verified this issue on build 20210225.4. Fixed.
