### ISSUE TITLE
Endless "Reenter credentials"

### ISSUE THREAD

**Issue by dumbledad** [microsoft/AzureStorageExplorer#4129]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20201211.10
**Platform/OS**: Windows 10 
**Architecture**: x64
**Regression From**:  It was, but many moons ago

## Bug Description ##
Storage explorer is constantly asking me to reenter my credentials. That drops me into a look where I am asked to 

> Approve sign in request
> We've sent a notification to your mobile device. Please open the Microsoft Authenticator app to respond.

or to

> Enter code
> Please type in the code displayed on your authenticator app from your device

But the authenticator app on my mobile device (Android, Pixel 4) does not receive any sign in request, nor does it offer the facility to generate a code. Other sign-ins to other services that need my corporate login work without issue.

## Steps to Reproduce ##
Install Storage Explorer
Try to log in to my microsoft.com account (timregan).

## Expected Experience ##
Logging in, seeing my subscriptions, browsing containers.

## Actual Experience ##
Repeated failures to load containers in some subscriptions, but not others
Repeatedly asked to reenter my credentials.

## Additional Context ##
This happens on multiple machines: laptops and Azure VMs. I do not have this issue with other services (like, say, the Azure portal) which also rely on corporate authentication.

**Comment by scovetta** [comment]
I don't know if this is the same issue, but for past few weeks, I am re-prompted to do a full auth flow each time I use Storage Explorer. At some point in the past, it was picking up my auth token automatically from the OS, but now, I have to do the full flow, which is painful to do each time I start the app.

**Comment by jinglouMSFT** [comment]
@scovetta Can you try to use MSAL auth instead?

**Comment by scovetta** [comment]
Ahh, wonderful, yes, no prompt now. Thank you!

**Comment by dumbledad** [comment]
Why is this closed? I can see you have a work around for @scovetta's issue, but that does not fix the original issue.
