### ISSUE TITLE
The detached account doesn't display as broken after detaching the added account from Quick Access

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#413]
**Storage Explorer Version**: 1.3.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180711.4
**Commit**: 47039639
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Go to Subscription -> Storage Accounts.
2. Attach one account with SAS -> Add the attached account to Quick Access.
3. Detach the account from Quick Access -> Check whether is displays as broken or not.

#### Expected Experience: ####
The detached account displays as broken after detaching the added account from Quick Access.

#### Actual Experience: ####
The detached account doesn't display as broken after detaching the added account from Quick Access.

**Comment by craxal** [comment]
We're already aware of this. Trying to get this working would be tricky, so unless it becomes a big issue with users, we won't worry about it.
