### ISSUE TITLE
The 'Delete' dialog pops up when using keyboard shortcut for one blob under one public connected HNS blob container

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#4136]
**Storage Explorer Version**: 1.18.0
**Build**: 20210225.12
**Branch**: rel/1.18.0
**Platform/OS**: Windows 10/ Linux Ubuntu 1604/ macOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Select one blob container -> Set it public access level to 'Public read access for container and blobs'.
3. Open connect dialog -> Select 'ADLS Gen2 container or directory -> Anonymously (my blob container allows public access)' -> Attach the blob container.
4. Open the attached blob container -> Select one blob -> Try to press keyboard shortcut 'Delete'.
5. Check whether the 'Delete' dialog pops up or not.

## Expected Experience ##
The 'Delete' dialog doesn't pop up.

## Actual Experience ##
The 'Delete' dialog pops up.
![image](https://user-images.githubusercontent.com/54055206/109250432-a8bc4a80-7824-11eb-8fae-71095b05e8bf.png)

## Additional Context ##
This issue doesn't reproduce for one public connected regular blob container.

**Comment by MRayermannMSFT** [comment]
Fixing for 1.19

**Comment by v-limu** [comment]
Verified on build 20210227.4. This issue has bee fixed. So we close it.
