### ISSUE TITLE
Reenter credentials

### ISSUE THREAD

**Issue by NonlinearMusings** [microsoft/AzureStorageExplorer#4138]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20201211.10
**Platform/OS**: Windows 10
**Architecture**: x64?
**Regression From**:  Don't know

## Bug Description ##
I cannot successfully add my Microsoft account to Storage Explorer

## Steps to Reproduce ##
1. Add an Azure Account with xxx@microsoft.com
2. Select the correct number from the Authenticator phone app 
3. Then prompted to pick an account
4. Select the correct number from the Authenticator phone app
5. Get message in Authenticator app telling me that "The notification is for an account that is no longer available..."
6. The sign-in dialog displays a message "Approve sign in request. We've sent a notification to your mobile device. Please open the Microsoft Authenticator app to respond."

## Expected Experience ##
I expect to be able to access my Microsoft storage resources using my Microsoft ID.

## Actual Experience ##
Unable to access storage resources using my Azure Account.

## Additional Context ##
This is a new problem for me because it used to work. I am wondering if the fact that my Microsoft ID is now being used in other, non-Microsoft tenants and subscriptions is some how contributing to the problem?

**Comment by jinglouMSFT** [comment]
Can you switch to use MSAL for auth?  You can do this on the Settings page under Edit->Settings->Application->Sign-in.  Check MSAL then restart Storage Explorer.

**Comment by NonlinearMusings** [comment]
Changed to MSAL and restarted. Different experience. Same end result.
![image](https://user-images.githubusercontent.com/37161470/109343594-3737c880-7833-11eb-968d-ffbd19db2d0c.png)

**Comment by jennifermarsman** [comment]
I'm having the same problem.

**Comment by MRayermannMSFT** [comment]
Can all of y'all please upgrade to v1.19.0 (or greater) and let us know if things are working for you then? If not, we can troubleshoot from there. Thanks!
