### ISSUE TITLE
Keep loading when expanding one attached local emulator

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#414]
**Storage Explorer Version**: 1.3.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180711.4
**Commit**: 47039639
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Go to Subscription -> Storage Accounts.
2. Make the Azure Storage Emulator has been installed.
3. Open the 'Connect' dialog and select 'Attach to a local emulator' -> Input a display name then click 'Connect'.
4. Try to drill down the  attached local emulator -> Blob Containers.

#### Expected Experience: ####
The Blob Containers node can be expanded successfully.

#### Actual Experience: ####
Keep loading when expand the Blob Containers node.
![loading](https://user-images.githubusercontent.com/34729022/42627174-c5216cfe-85bb-11e8-9d14-5edf4f96f983.png)

**Comment by mithunshanbhag** [comment]
FWIW - I too see the same "loading..." indicator when attempting to view any blob/queue/table in my local emulator. It ultimately times out and displays an error dialog mentioned in issue: #408 .

**Comment by craxal** [comment]
Did you actually start the emulator first?

**Comment by jinglouMSFT** [comment]
Starting from 1.2.0, we don't automatically start the emulator anymore per customer request. You need to manually start the emulator.  If this is not the case, please provide us a bit more info on how to repro your case @mithunshanbhag. Thanks.

**Comment by craxal** [comment]
For future reference, you can check the Get Started page (we just updated the documentation).
