### ISSUE TITLE
Use 'You can now attach...' instead of 'You can attach now...' in the 'New -> Blobs' part for the release notes

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4140]
**Storage Explorer Version**: 1.18.0
**Build Number**: 20210227.4
**Branch**: rel/1.18.0
**Platform/OS**: Windows 10/ Linux ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Open Storage Explorer -> Go to 'Help' -> Click 'View Release Notes'. 
2. Observe the first sentence in the 'New -> Blobs' part.

## Expected Experience ##
Show 'You can **now attach** ADLS Gen2 containers and folders via a SAS URL'.

## Actual Experience ##
Show 'You can **attach now** ADLS Gen2 containers and folders via a SAS URL'.
![image](https://user-images.githubusercontent.com/41351993/109489396-c4904c80-7ac1-11eb-8b54-d273bbd7600a.png)

**Comment by craxal** [comment]
@MRayermannMSFT We're doing a hot fix, so let's fix this.

**Comment by MRayermannMSFT** [comment]
Forgot to fix. Oh well.
