### ISSUE TITLE
Please bring back Cosmos DB Accounts

### ISSUE THREAD

**Issue by 1RedOne** [microsoft/AzureStorageExplorer#4143]
**Is your feature request related to a problem? Please describe.**
Not sure why, but Cosmos DB accounts show as deprecated and I can't view them anymore.  This was a great feature for me and now I have to go back to the Azure console all the time again. 

I loved Azure Storage Explorer **because I didn't have to go to the Azure Portal**

**Describe the solution you'd like**
Keep supporting Cosmos DB Accounts until the heat death of the universe

**Describe alternatives you've considered**
Alternatives involve me crying / using the Azure Portal instead

**Additional context**

**Comment by MRayermannMSFT** [comment]
@1RedOne you should still be able to view CosmosDB accounts in Storage Explorer. They are not going to be removed until a later date. Can you go to Settings (gear icon on the left) -> Services -> CosmosDB and make sure the checkbox there is checked?

**Comment by 1RedOne** [comment]
Thank you for the reply, to be specific, I get this error when trying to view CosmosDB resources.  

![image](https://user-images.githubusercontent.com/1247626/109702545-5ea7d180-7b62-11eb-9e78-1eaa2897f92b.png)

**Comment by MRayermannMSFT** [comment]
@1RedOne can you share what else is in the dialog....?

**Comment by ilaiyarajak** [comment]
I also get the same error "Unable to retrieve child resources."
Here is the full error screenshot
![Cosmos-Screenshot from 2021-03-21 16-00-51](https://user-images.githubusercontent.com/3032056/111901504-aa151780-8a5e-11eb-8acd-35562f5dc61c.png)

I double checked that I enabled CosmosDB checkbox in settings
![Cosmos2Screenshot from 2021-03-21 16-02-30](https://user-images.githubusercontent.com/3032056/111901543-dfba0080-8a5e-11eb-9ce6-7842bed9efb7.png)

**Comment by 1RedOne** [comment]
This is precisely what I see.

**Comment by MRayermannMSFT** [comment]
@ilaiyarajak in your screenshot that is for a cosmosdb emulator account. Is your emulator running?

@1RedOne is your issue also with an emulator account?

**Comment by 1RedOne** [comment]
Mine is for real actual cosmos db, not an emulated one.

**Comment by ilaiyarajak** [comment]
@MRayermannMSFT I also created the real cosmos db with table api in azure portal. May be I don't know how to connect to real cosmos db with table api from azure storage explorer. 
Meantime I also see https://cosmos.azure.com/ (We can use this online too using connection string or portal credentials) become handy in my use case and https://portal.azure.com/App/Download (Azure Portal Desktop App) .

**Comment by 1RedOne** [comment]
My MSFT id is **stowen** if you'd like to ping me to gather some extra info. , @MRayermannMSFT

**Comment by 1RedOne** [comment]
I have tested this again today, and my Cosmos accounts are listed as 'Deprecated', and won't expand when I click them.  I can right-click the account and jump to it in Azure, so that does work.

It was very useful to have Cosmos DB Accounts in Storage Explorer, before.  When I go to settings, there is a checkbox related to Cosmos, but this checkbox actually will **hide** my accounts, so they do not appear anymore, not what I was looking for!

**Comment by MRayermannMSFT** [comment]
Cosmos DB says you need to either use the portal or cosmos.azure.com to work around this issue. Sorry y'all.

**Comment by 1RedOne** [comment]
I tried a few options to still get some non-Azure Portal cosmos interaction.

There is a new (in April 2021) Azure Databases Extension which is *fantastic* for working with Cosmos.  In my humble opinion, anyone who was using Azure Storage Explorer will be happy as a peach with the new plugin for VS Code.
