### ISSUE TITLE
Unable to Start Storage Explorer from Windows 10... what is the executable?

### ISSUE THREAD

**Issue by JVega1988** [microsoft/AzureStorageExplorer#4144]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20201211.10
**Platform/OS**: Windows 10
**Architecture**: don't know
**Regression From**:  works but I can't start it

## Bug Description ##
I've installed Azure Storage Explorer twice now but it does not create a start menu item to run it again.
If my machine re-boots, I don't know how to turn on Azure Storage Explorer since the installer did not add a shortcut anywhere.
How do I start Azure Storage Explorer on my laptop?
Is there an executable somewhere which I can then create a shortcut?
Note, when I installed Azure Storage, I had to do it from an elevated shared folder at my company since I don't have admin rights to my laptop.  So that may be why a short cut or start menu item was not created.

Thanks.

## Steps to Reproduce ##
Install Azure Storage Explorer but not as an "admin".  I'm on a company laptop which does not allow me to have "admin" rights.

## Expected Experience ##
I need to be able to turn on Azure Storage Explorer from the Windows 10 start menu

## Actual Experience ##
I'm unable to start Azure Storage Explorer.  I had to re-install it, just to get it working again.

## Additional Context ##
none.

**Comment by jinglouMSFT** [comment]
By default, Storage Explorer is installed here:  C:\Program Files (x86)\Microsoft Azure Storage Explorer.  The executable is storageexplorer.exe.

**Comment by JVega1988** [comment]
I found the “StorageExplorer.exe” in a different directory which is this one:

C:\Users\vegaJ\AppData\Local\Programs\Microsoft Azure Storage Explorer

Once found I was able to pin it to my “Start” menu and now I can easily access it.

Thanks.

**Comment by JVega1988** [comment]
I was able to find “StorageExplorer.exe” in this directory path:

C:\Users\vegaJ\AppData\Local\Programs\Microsoft Azure Storage Explorer

Once found I was able to pin it to my “Start” menu and now I can easily access it.
