### ISSUE TITLE
Unable to connect to storage account using SAS URL with new version 1.18.0

### ISSUE THREAD

**Issue by jimtr123** [microsoft/AzureStorageExplorer#4149]
**Is your feature request related to a problem? Please describe.**
In the previous version it was easy to attach to azure storage, just and new storage, paste the SAS token and it connected. I have tried every option available and it will not accept the SAS token and connect. I tried via powershell and it works so I know my token is good

**Describe the solution you'd like**
Go back to the simple connect that worked in the previous version

**Describe alternatives you've considered**

**Additional context**

**Comment by jinglouMSFT** [comment]
Thanks for the feedback. If you don't mind, could you please walk us through the steps you went through to connect? That will help us to understand the issue a bit better.  Thanks.

**Comment by jimtr123** [comment]
right mouse on storage account, choose connect to Azure storage/Storage Account/SAS/past in SAS token. Error "The connection string is missing an account hey or SAS token" These same steps work in previous version with same SAS URI. 
![Connectionerror](https://user-images.githubusercontent.com/40601121/109726902-72166500-7b81-11eb-8daf-01ae6c3b4e21.JPG)
Error attached.

**Comment by JasonYeMSFT** [comment]
Are you getting the url from Portal? The url you pasted here points to the Blob service of that storage account. The text box here is expecting the "Connection String" which includes all the service endpoints of the storage account. See the "Connection string" part in the screenshot.
![image](https://user-images.githubusercontent.com/39359541/109727752-c01f6e80-7b69-11eb-80dd-8d132c24df99.png)

**Comment by jimtr123** [comment]
I am getting the URL from an internal site. What option do I need to use for that URL to work in 1.18 as it did in 1.17 and all versions before? This is the option I used to choose that allowed the connection
![Untitled](https://user-images.githubusercontent.com/40601121/109799013-7b3b1c80-7be9-11eb-9bbd-0edd9a6e45c2.png)

**Comment by JasonYeMSFT** [comment]
Unfortunately that option was accidentally removed in 1.18.0. We are working on a hotfix to add it back. At the moment, you can construct a connection string using the SAS url you have to connect to the storage account.
For example, given the SAS url "https://contoso.blob.core.windows.net/?SAS_TOKEN"

The connection string would look like "BlobEndpoint=https://contoso.blob.core.windows.net/;QueueEndpoint=https://contoso.queue.core.windows.net/;FileEndpoint=https://contoso.file.core.windows.net/;TableEndpoint=https://contoso.table.core.windows.net/;SharedAccessSignature=SAS_TOKEN"

Also, does the internal site produce anything else when you got the url? Could you ask the owner of the internal site to make sure their SAS generation experience to align with Azure Portal? We recommend 3rd party tools to be consistent when generating SAS so the generated SAS can be best supported in our tools.

**Comment by jimtr123** [comment]
Thank you, I'll pass it along, we are an internal group in Microsoft and it has always worked until the latest update. You can ping me internally for more details, alias jimtr

**Comment by JasonYeMSFT** [comment]
We have merged fixes for this bug and created a hotfix release candidate. Would you like to try it and see if it fixes your problem?

Windows: [windows 1.18.1](https://storageexplorerpublish.blob.core.windows.net/privatebuilds/1.18.1-hotfix/Windows_StorageExplorer.exe?sv=2020-04-08&st=2021-03-04T02%3A36%3A45Z&se=2021-03-16T01%3A36%3A00Z&sr=b&sp=r&sig=7KzP7nB3QYmedpUKQA4xIxQAWPNzgUXaA50cBRGecZE%3D)
macOS: [macOS 1.18.1](https://storageexplorerpublish.blob.core.windows.net/privatebuilds/1.18.1-hotfix/Mac_StorageExplorer.zip?sv=2020-04-08&st=2021-03-04T02%3A38%3A42Z&se=2021-03-17T01%3A38%3A00Z&sr=b&sp=r&sig=%2FJwyQ%2F0GZPqOs2MUh%2Bx6LKyY%2FYAVCFiljUJIeDjQxkk%3D)
linux: [linux 1.18.1](https://storageexplorerpublish.blob.core.windows.net/privatebuilds/1.18.1-hotfix/Linux_StorageExplorer-x64.tar.gz?sv=2020-04-08&st=2021-03-04T02%3A39%3A01Z&se=2021-03-17T01%3A39%3A00Z&sr=b&sp=r&sig=1pPYKQZ04jLvKkIEiZLLgJlzWhbLD4%2BxVoCmnUrJcK4%3D)

If they work well for you, they will be the exact bits we release for 1.18.1.

**Comment by jimtr123** [comment]
That works, thank you.
