### ISSUE TITLE
Can't upload files to blob container

### ISSUE THREAD

**Issue by eyalellenbogen** [microsoft/AzureStorageExplorer#415]
**Storage Explorer Version**: 1.3
**Platform/OS Version**: Windows 10 1803
**Architecture**: ia32
**Regression From**: Can't answer this one... first time trying to upload manually.

#### Steps to Reproduce: ####
1. exported a bacpac file from an SQL DB (~170mb)
2. Used the upload wizard to upload the file to a blob container

#### Expected Experience: ####
Upload should succeed

#### Actual Experience: ####
It was stuck on "initializing" for more than 30 minutes and eventually failed with

```
{
  "name": "Error",
  "message": "connect ECONNABORTED 52.239.154.132:443",
  "stack": "Error: connect ECONNABORTED 52.239.154.132:443\n    at Object._errnoException (util.js:1024:11)\n    at _exceptionWithHostPort (util.js:1046:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)",
  "code": "ECONNABORTED",
  "errno": "ECONNABORTED",
  "syscall": "connect",
  "address": "52.239.154.132",
  "port": 443,
  "innerError": {
    "code": "ESOCKETTIMEDOUT",
    "connect": false,
    "innerError": {
      "code": "ESOCKETTIMEDOUT",
      "connect": false,
      "innerError": {
        "code": "ESOCKETTIMEDOUT",
        "connect": false
      }
    }
  }
}
```

**Comment by craxal** [comment]
Tell us more about the environment and container you're attempting to upload to. What kind of storage account does it belong to? How are you connecting to the container (did you sign in, use an account or service SAS, or use an account key)? Are you operating through any special network configurations, like a proxy server?

**Comment by akd110** [comment]
More or less the same problem here: big problems uploading large files with Azure Storage Explorer, 25 Mbps upload costant speed (dedicated).
Small files are uploaded without any problem.

`{
  "name": "Error",
  "message": "getaddrinfo ENOTFOUND ad*********.blob.core.windows.net ad*******.blob.core.windows.net:443",
  "stack": "Error: getaddrinfo ENOTFOUND ad********.blob.core.windows.net ad*******.blob.core.windows.net:443\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
  "code": "ENOTFOUND",
  "errno": "ENOTFOUND",
  "syscall": "getaddrinfo",
  "hostname": "ad*******.blob.core.windows.net",
  "host": "ad*********.blob.core.windows.net",
  "port": "443",
  "innerError": {
    "code": "ESOCKETTIMEDOUT",
    "connect": false,
    "innerError": {
      "code": "ESOCKETTIMEDOUT",
      "connect": false,
      "innerError": {
        "code": "ESOCKETTIMEDOUT",
        "connect": false,
        "innerError": {
          "code": "ESOCKETTIMEDOUT",
          "connect": false,
          "innerError": {
            "code": "ESOCKETTIMEDOUT",
            "connect": false,
            "innerError": {
              "code": "ESOCKETTIMEDOUT",
              "connect": false,
              "innerError": {
                "code": "ESOCKETTIMEDOUT",
                "connect": false,
                "innerError": {
                  "code": "ESOCKETTIMEDOUT",
                  "connect": false,
                  "innerError": {
                    "code": "ESOCKETTIMEDOUT",
                    "connect": false,
                    "innerError": {
                      "code": "ESOCKETTIMEDOUT",
                      "connect": false,
                      "innerError": {
                        "code": "ESOCKETTIMEDOUT",
                        "connect": false,
                        "innerError": {
                          "code": "ESOCKETTIMEDOUT",
                          "connect": false,
                          "innerError": {
                            "code": "ESOCKETTIMEDOUT",
                            "connect": false,
                            "innerError": {
                              "code": "ESOCKETTIMEDOUT",
                              "connect": false,
                              "innerError": {
                                "code": "ESOCKETTIMEDOUT",
                                "connect": false,
                                "innerError": {
                                  "code": "ESOCKETTIMEDOUT",
                                  "connect": false,
                                  "innerError": {
                                    "code": "ESOCKETTIMEDOUT",
                                    "connect": false,
                                    "innerError": {
                                      "code": "ESOCKETTIMEDOUT",
                                      "connect": false,
                                      "innerError": {
                                        "code": "ESOCKETTIMEDOUT",
                                        "connect": false,
                                        "innerError": {
                                          "code": "ESOCKETTIMEDOUT",
                                          "connect": false,
                                          "innerError": {
                                            "code": "ESOCKETTIMEDOUT",
                                            "connect": false,
                                            "innerError": {
                                              "code": "ESOCKETTIMEDOUT",
                                              "connect": false,
                                              "innerError": {
                                                "code": "ESOCKETTIMEDOUT",
                                                "connect": false,
                                                "innerError": {
                                                  "code": "ESOCKETTIMEDOUT",
                                                  "connect": false,
                                                  "innerError": {
                                                    "code": "ESOCKETTIMEDOUT",
                                                    "connect": false,
                                                    "innerError": {
                                                      "code": "ESOCKETTIMEDOUT",
                                                      "connect": false,
                                                      "innerError": {
                                                        "code": "ESOCKETTIMEDOUT",
                                                        "connect": false,
                                                        "innerError": {
                                                          "code": "ESOCKETTIMEDOUT",
                                                          "connect": false,
                                                          "innerError": {
                                                            "code": "ESOCKETTIMEDOUT",
                                                            "connect": false,
                                                            "innerError": {
                                                              "code": "ESOCKETTIMEDOUT",
                                                              "connect": false,
                                                              "innerError": {
                                                                "code": "ESOCKETTIMEDOUT",
                                                                "connect": false,
                                                                "innerError": {
                                                                  "code": "ESOCKETTIMEDOUT",
                                                                  "connect": false,
                                                                  "innerError": {
                                                                    "code": "ESOCKETTIMEDOUT",
                                                                    "connect": false,
                                                                    "innerError": {
                                                                      "code": "ESOCKETTIMEDOUT",
                                                                      "connect": false,
                                                                      "innerError": {
                                                                        "code": "ESOCKETTIMEDOUT",
                                                                        "connect": false,
                                                                        "innerError": {
                                                                          "code": "ESOCKETTIMEDOUT",
                                                                          "connect": false,
                                                                          "innerError": {
                                                                            "code": "ETIMEDOUT",
                                                                            "errno": "ETIMEDOUT",
                                                                            "syscall": "connect",
                                                                            "address": "52.239.137.68",
                                                                            "port": 443,
                                                                            "innerError": {
                                                                              "code": "ESOCKETTIMEDOUT",
                                                                              "connect": false,
                                                                              "innerError": {
                                                                                "code": "ESOCKETTIMEDOUT",
                                                                                "connect": false,
                                                                                "innerError": {
                                                                                  "code": "ESOCKETTIMEDOUT",
                                                                                  "connect": false,
                                                                                  "innerError": {
                                                                                    "code": "ESOCKETTIMEDOUT",
                                                                                    "connect": false,
                                                                                    "innerError": {
                                                                                      "code": "ESOCKETTIMEDOUT",
                                                                                      "connect": false,
                                                                                      "innerError": {
                                                                                        "code": "ESOCKETTIMEDOUT",
                                                                                        "connect": false,
                                                                                        "innerError": {
                                                                                          "code": "ESOCKETTIMEDOUT",
                                                                                          "connect": false,
                                                                                          "innerError": {
                                                                                            "code": "ESOCKETTIMEDOUT",
                                                                                            "connect": false,
                                                                                            "innerError": {
                                                                                              "code": "ESOCKETTIMEDOUT",
                                                                                              "connect": false,
                                                                                              "innerError": {
                                                                                                "code": "ESOCKETTIMEDOUT",
                                                                                                "connect": false,
                                                                                                "innerError": {
                                                                                                  "code": "ECONNRESET",
                                                                                                  "errno": "ECONNRESET",
                                                                                                  "syscall": "write",
                                                                                                  "innerError": {
                                                                                                    "code": "ESOCKETTIMEDOUT",
                                                                                                    "connect": false,
                                                                                                    "innerError": {
                                                                                                      "code": "ESOCKETTIMEDOUT",
                                                                                                      "connect": false,
                                                                                                      "innerError": {
                                                                                                        "code": "ESOCKETTIMEDOUT",
                                                                                                        "connect": false,
                                                                                                        "innerError": {
                                                                                                          "code": "ESOCKETTIMEDOUT",
                                                                                                          "connect": false,
                                                                                                          "innerError": {
                                                                                                            "code": "ESOCKETTIMEDOUT",
                                                                                                            "connect": false,
                                                                                                            "innerError": {
                                                                                                              "code": "ESOCKETTIMEDOUT",
                                                                                                              "connect": false,
                                                                                                              "innerError": {
                                                                                                                "code": "ESOCKETTIMEDOUT",
                                                                                                                "connect": false,
                                                                                                                "innerError": {
                                                                                                                  "code": "ESOCKETTIMEDOUT",
                                                                                                                  "connect": false,
                                                                                                                  "innerError": {
                                                                                                                    "code": "ESOCKETTIMEDOUT",
                                                                                                                    "connect": false,
                                                                                                                    "innerError": {
                                                                                                                      "code": "ESOCKETTIMEDOUT",
                                                                                                                      "connect": false,
                                                                                                                      "innerError": {
                                                                                                                        "code": "ESOCKETTIMEDOUT",
                                                                                                                        "connect": false,
                                                                                                                        "innerError": {
                                                                                                                          "code": "ESOCKETTIMEDOUT",
                                                                                                                          "connect": false,
                                                                                                                          "innerError": {
                                                                                                                            "code": "ESOCKETTIMEDOUT",
                                                                                                                            "connect": false,
                                                                                                                            "innerError": {
                                                                                                                              "code": "ESOCKETTIMEDOUT",
                                                                                                                              "connect": false,
                                                                                                                              "innerError": {
                                                                                                                                "code": "ESOCKETTIMEDOUT",
                                                                                                                                "connect": false,
                                                                                                                                "innerError": {
                                                                                                                                  "code": "ESOCKETTIMEDOUT",
                                                                                                                                  "connect": false,
                                                                                                                                  "innerError": {
                                                                                                                                    "code": "ESOCKETTIMEDOUT",
                                                                                                                                    "connect": false,
                                                                                                                                    "innerError": {
                                                                                                                                      "code": "ESOCKETTIMEDOUT",
                                                                                                                                      "connect": false,
                                                                                                                                      "innerError": {
                                                                                                                                        "code": "ESOCKETTIMEDOUT",
                                                                                                                                        "connect": false,
                                                                                                                                        "innerError": {
                                                                                                                                          "code": "ESOCKETTIMEDOUT",
                                                                                                                                          "connect": false,
                                                                                                                                          "innerError": {
                                                                                                                                            "code": "ESOCKETTIMEDOUT",
                                                                                                                                            "connect": false,
                                                                                                                                            "innerError": {
                                                                                                                                              "code": "ESOCKETTIMEDOUT",
                                                                                                                                              "connect": false,
                                                                                                                                              "innerError": {
                                                                                                                                                "code": "ESOCKETTIMEDOUT",
                                                                                                                                                "connect": false,
                                                                                                                                                "innerError": {
                                                                                                                                                  "code": "ESOCKETTIMEDOUT",
                                                                                                                                                  "connect": false,
                                                                                                                                                  "innerError": {
                                                                                                                                                    "code": "ESOCKETTIMEDOUT",
                                                                                                                                                    "connect": false,
                                                                                                                                                    "innerError": {
                                                                                                                                                      "code": "ESOCKETTIMEDOUT",
                                                                                                                                                      "connect": false,
                                                                                                                                                      "innerError": {
                                                                                                                                                        "code": "ESOCKETTIMEDOUT",
                                                                                                                                                        "connect": false,
                                                                                                                                                        "innerError": {
                                                                                                                                                          "code": "ESOCKETTIMEDOUT",
                                                                                                                                                          "connect": false,
                                                                                                                                                          "innerError": {
                                                                                                                                                            "code": "ESOCKETTIMEDOUT",
                                                                                                                                                            "connect": false,
                                                                                                                                                            "innerError": {
                                                                                                                                                              "code": "ESOCKETTIMEDOUT",
                                                                                                                                                              "connect": false,
                                                                                                                                                              "innerError": {
                                                                                                                                                                "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                "connect": false,
                                                                                                                                                                "innerError": {
                                                                                                                                                                  "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                  "connect": false,
                                                                                                                                                                  "innerError": {
                                                                                                                                                                    "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                    "connect": false,
                                                                                                                                                                    "innerError": {
                                                                                                                                                                      "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                      "connect": false,
                                                                                                                                                                      "innerError": {
                                                                                                                                                                        "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                        "connect": false,
                                                                                                                                                                        "innerError": {
                                                                                                                                                                          "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                          "connect": false,
                                                                                                                                                                          "innerError": {
                                                                                                                                                                            "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                            "connect": false,
                                                                                                                                                                            "innerError": {
                                                                                                                                                                              "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                              "connect": false,
                                                                                                                                                                              "innerError": {
                                                                                                                                                                                "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                "connect": false,
                                                                                                                                                                                "innerError": {
                                                                                                                                                                                  "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                  "connect": false,
                                                                                                                                                                                  "innerError": {
                                                                                                                                                                                    "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                    "connect": false,
                                                                                                                                                                                    "innerError": {
                                                                                                                                                                                      "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                      "connect": false,
                                                                                                                                                                                      "innerError": {
                                                                                                                                                                                        "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                        "connect": false,
                                                                                                                                                                                        "innerError": {
                                                                                                                                                                                          "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                          "connect": false,
                                                                                                                                                                                          "innerError": {
                                                                                                                                                                                            "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                            "connect": false,
                                                                                                                                                                                            "innerError": {
                                                                                                                                                                                              "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                              "connect": false,
                                                                                                                                                                                              "innerError": {
                                                                                                                                                                                                "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                "connect": false,
                                                                                                                                                                                                "innerError": {
                                                                                                                                                                                                  "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                  "connect": false,
                                                                                                                                                                                                  "innerError": {
                                                                                                                                                                                                    "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                    "connect": false,
                                                                                                                                                                                                    "innerError": {
                                                                                                                                                                                                      "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                      "connect": false,
                                                                                                                                                                                                      "innerError": {
                                                                                                                                                                                                        "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                        "connect": false,
                                                                                                                                                                                                        "innerError": {
                                                                                                                                                                                                          "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                          "connect": false,
                                                                                                                                                                                                          "innerError": {
                                                                                                                                                                                                            "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                            "connect": false,
                                                                                                                                                                                                            "innerError": {
                                                                                                                                                                                                              "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                              "connect": false,
                                                                                                                                                                                                              "innerError": {
                                                                                                                                                                                                                "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                                "connect": false,
                                                                                                                                                                                                                "innerError": {
                                                                                                                                                                                                                  "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                                  "connect": false,
                                                                                                                                                                                                                  "innerError": {
                                                                                                                                                                                                                    "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                                    "connect": false,
                                                                                                                                                                                                                    "innerError": {
                                                                                                                                                                                                                      "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                                      "connect": false,
                                                                                                                                                                                                                      "innerError": {
                                                                                                                                                                                                                        "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                                        "connect": false,
                                                                                                                                                                                                                        "innerError": {
                                                                                                                                                                                                                          "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                                          "connect": false,
                                                                                                                                                                                                                          "innerError": {
                                                                                                                                                                                                                            "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                                            "connect": false,
                                                                                                                                                                                                                            "innerError": {
                                                                                                                                                                                                                              "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                                              "connect": false,
                                                                                                                                                                                                                              "innerError": {
                                                                                                                                                                                                                                "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                                                "connect": false,
                                                                                                                                                                                                                                "innerError": {
                                                                                                                                                                                                                                  "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                                                  "connect": false,
                                                                                                                                                                                                                                  "innerError": {
                                                                                                                                                                                                                                    "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                                                    "connect": false,
                                                                                                                                                                                                                                    "innerError": {
                                                                                                                                                                                                                                      "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                                                      "connect": false,
                                                                                                                                                                                                                                      "innerError": {
                                                                                                                                                                                                                                        "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                                                        "connect": false,
                                                                                                                                                                                                                                        "innerError": {
                                                                                                                                                                                                                                          "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                                                          "connect": false,
                                                                                                                                                                                                                                          "innerError": {
                                                                                                                                                                                                                                            "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                                                            "connect": false,
                                                                                                                                                                                                                                            "innerError": {
                                                                                                                                                                                                                                              "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                                                              "connect": false,
                                                                                                                                                                                                                                              "innerError": {
                                                                                                                                                                                                                                                "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                                                                "connect": false,
                                                                                                                                                                                                                                                "innerError": {
                                                                                                                                                                                                                                                  "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                                                                  "connect": false,
                                                                                                                                                                                                                                                  "innerError": {
                                                                                                                                                                                                                                                    "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                                                                    "connect": false,
                                                                                                                                                                                                                                                    "innerError": {
                                                                                                                                                                                                                                                      "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                                                                      "connect": false,
                                                                                                                                                                                                                                                      "innerError": {
                                                                                                                                                                                                                                                        "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                                                                        "connect": false,
                                                                                                                                                                                                                                                        "innerError": {
                                                                                                                                                                                                                                                          "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                                                                          "connect": false,
                                                                                                                                                                                                                                                          "innerError": {
                                                                                                                                                                                                                                                            "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                                                                            "connect": false,
                                                                                                                                                                                                                                                            "innerError": {
                                                                                                                                                                                                                                                              "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                                                                              "connect": false,
                                                                                                                                                                                                                                                              "innerError": {
                                                                                                                                                                                                                                                                "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                                                                                "connect": false,
                                                                                                                                                                                                                                                                "innerError": {
                                                                                                                                                                                                                                                                  "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                                                                                  "connect": false,
                                                                                                                                                                                                                                                                  "innerError": {
                                                                                                                                                                                                                                                                    "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                                                                                    "connect": false,
                                                                                                                                                                                                                                                                    "innerError": {
                                                                                                                                                                                                                                                                      "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                                                                                      "connect": false,
                                                                                                                                                                                                                                                                      "innerError": {
                                                                                                                                                                                                                                                                        "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                                                                                        "connect": false,
                                                                                                                                                                                                                                                                        "innerError": {
                                                                                                                                                                                                                                                                          "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                                                                                          "connect": false,
                                                                                                                                                                                                                                                                          "innerError": {
                                                                                                                                                                                                                                                                            "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                                                                                            "connect": false,
                                                                                                                                                                                                                                                                            "innerError": {
                                                                                                                                                                                                                                                                              "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                                                                                              "connect": false,
                                                                                                                                                                                                                                                                              "innerError": {
                                                                                                                                                                                                                                                                                "code": "ESOCKETTIMEDOUT",
                                                                                                                                                                                                                                                                                "connect": false,
                                                                                                                                                                                                                                                                                "innerError": {
                                           
                                                                                                                                                                                                                                       .... and so on....

**Comment by craxal** [comment]
@akd110 Same questions as above.

1.3.0 is pretty old now. Please make sure you're updated to the latest version. If you're still encountering problems, consider turning on AzCopy by selecting **Experimental** > **Use AzCopy for Improved Blob Upload and Download** from the menu.

**Comment by akd110** [comment]
Hello craxal, actually I am using the latest version, the 1.6.2.
Answer questions above:

**-environment and container you're attempting to upload to.** 
I created a blob container in my storage account, under the free evaluating subscription (but I think I will pass to a pay per use if everything will work). Within that blob container, I was trying to upload a folder, containing several 2 GB files for a total of about 350GB. 
Firewall showed a lot of traffic, even a bit faster than my maximum average bandwith, but all file kept failing upload for the reason posted above.
Just a bunch of small files did upload correctly

**-What kind of storage account does it belong to?**
You mean the free subscription?

 **-How are you connecting to the container (did you sign in, use an account or service SAS, or use an account key)?** 
Signed in with my azure account (which is my 365 account).

**-Are you operating through any special network configurations, like a proxy server?**
No, straight to the firewall without limitations on that machine (just some QoS)

Now I am trying the experimental AZCopy as you suggested, let's see what happens. By non I see a upload bandwith more usual for me, and I don't see all files in the folder uploading, but just one process, and it's percentage.
Will keep this post updated.

Thank you craxal.

**Comment by craxal** [comment]
@akd110 No, not subscription types. There are several types of storage accounts you can create: Storage, StorageV2, Blob, Premium, etc. Usually, this shouldn't matter, but it's useful to know when trying to reproduce issues.

Let's check a few things next:
1. Since you're signed in, can you verify whether you're using RBAC to access the blob container? You can easily check this by selecting the account node in Storage Explorer and looking for the Primary or Secondary Key properties. If you don't see them, you're using RBAC.
2. If you are using RBAC, please verify that the permissions you have allow you write blobs. This may seem silly if you're the account admin, but I've found that you still need to assign the proper roles. I think it's because admin roles only have management-level permissions, not data-level.

**Comment by akd110** [comment]
@craxal Ok, so my storage is StorageV2, Sku Standard, Default access tier Cool.

I can see Primary and Secondary keys in properties, bit no sign of RBAC.

In the meanwhile, uploading is still going well, increasing its percentage. We are at 50% now and still going.

**Comment by craxal** [comment]
Yeah, I think performance for a Cool account may be a bit different than a Hot one, since cool access is configured to expect as much access.

Hopefully AzCopy works better for you! We're planning on using it as the de facto method of uploading/downloading in the future, since they handle things more efficiently than we do.

**Comment by akd110** [comment]
Failed upload a couple of times, now I am trying the 3rd time with different configs on pc, let's see what happen

**Comment by akd110** [comment]
Ok I am uploading a bunch uf files per time now, since the "upload folder" function kept failing.
Now it's better, but I have to reupload several files, since it fail some upload.

Could it help if I pasted errors here?

**Comment by craxal** [comment]
Sure, go ahead and share those. Be sure to redact any sensitive information.

**Comment by akd110** [comment]
Ok, main problem is "AzCopy quitted unexpectedly". No other infos

**Comment by MRayermannMSFT** [comment]
@eyalellenbogen @akd110  are you still having this problem with the latest version of Storage Explorer?

**Comment by eyalellenbogen** [comment]
@MRayermannMSFT It has been a while since I last worked on that project. I haven't used the Storage Explorer since. I can't check it any time soon. You can treat my "ticket" as closed.

**Comment by MRayermannMSFT** [comment]
Ok. :)
