### ISSUE TITLE
An unexpected error occured on startup. Invalid integer: 1#2826

### ISSUE THREAD

**Issue by t2tviking** [microsoft/AzureStorageExplorer#4150]
**Storage Explorer Version**: 1.18.0 (but been having it for earlier versions as well)
**Build Number**: 20210227.4
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  No

## Bug Description ##
When starting the program, this pop-up (see attachment) shows up every time. Clicking "Ignore" takes it away and I don't experience anything negative because of it, but still annoying.

![storage-explorer-exception](https://user-images.githubusercontent.com/1827924/109774033-31a9fc00-7c00-11eb-84e9-814d7b786084.JPG)

**Comment by mglowienka** [comment]
I am experiencing nearly the same issue. 

![image](https://user-images.githubusercontent.com/88370542/127977186-7c2a4400-d236-4993-9ace-e9d9b97b2de4.png)

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
