### ISSUE TITLE
Impossible to browse accounts since upgrade to 1.18, reverted back to 1.17

### ISSUE THREAD

**Issue by anogues-danone** [microsoft/AzureStorageExplorer#4151]
**Storage Explorer Version**: 1.18
**Build Number**: Latest
**Platform/OS**: Win 10
**Architecture**: x64
**Regression From**:  Working fine till 1.17, stopped working in 1.18

## Bug Description ##
Hi.

Impossible to browse any storage accounts fetched with AZ AD Login acfter upgrading to 1.18. When i click on the arrow to show the containers ands types it shows all storage accounts blank. With 1.17 works fine. I reverted back and worked again

## Steps to Reproduce ##
Log In with any Azure AD account and load all your storage accounts
Try to browse any container --> none shows up

## Expected Experience ##
Working in 1.17 and containers should be found.

**Comment by Kyle8329** [comment]
Have the same issue on some accounts.  Noticed that I had the Contributor role in portal.azure.com for an account I could access.  Didn't see this role on an account I couldn't access.

**Comment by mnidza** [comment]
+1. Can list contents under some of my storage accounts, but not all. I *do* have Storage Blob Data Contributor role under at least one account that I *cannot* list.

**Comment by JasonYeMSFT** [comment]
Could anyone of you do something to help us investigate what goes wrong?
1. Open Storage Explorer
2. Open the developer tools (you can press F12, or go to app menu Help -> Toggle Developer Tools
3. Under the Sources tab, ctrl/cmd + P and open AzureStorageAccountAttributeLoader.js
4. Set a break point at line 79, 84, 112 and 117. These lines catches the error thrown while loading storage account attributes.
5. Go to the tree view and try to expand the storage accounts you have problem with.

If the break point is hit, please share the content of either the `error` object or the `error_2` object with us.

**Comment by JurritBZ** [comment]
This is what I find in error:

error: TypeError: Cannot read property '0' of undefined at Object.getStorageAccountV2Attributes (file:///C:/Program%20Files%20(x86)/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Common/AzureStorageUtilities.js:189:37) at AzureStorageAccountAttributeLoader.<anonymous> (file:///C:/Program%20Files%20(x86)/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/Azure/Loaders/AzureStorageAccountAttributeLoader.js:108:72) at step (file:///C:/Program%20Files%20(x86)/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/Azure/Producers/AzureStorageProducer.js:35:23) at Object.next (file:///C:/Program%20Files%20(x86)/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/Azure/Producers/AzureStorageProducer.js:16:53) at fulfilled (file:///C:/Program%20Files%20(x86)/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/Azure/Producers/AzureStorageProducer.js:7:58)

**Comment by JasonYeMSFT** [comment]
@JurritBZ Thanks for the help! I am able to reproduce the issue and will get it fixed asap.

**Comment by JasonYeMSFT** [comment]
We have merged fixes for this bug and created a hotfix release candidate. Would you like to try it and see if it fixes your problem?

Windows: [windows 1.18.1](https://storageexplorerpublish.blob.core.windows.net/privatebuilds/1.18.1-hotfix/Windows_StorageExplorer.exe?sv=2020-04-08&st=2021-03-04T02%3A36%3A45Z&se=2021-03-16T01%3A36%3A00Z&sr=b&sp=r&sig=7KzP7nB3QYmedpUKQA4xIxQAWPNzgUXaA50cBRGecZE%3D)
macOS: [macOS 1.18.1](https://storageexplorerpublish.blob.core.windows.net/privatebuilds/1.18.1-hotfix/Mac_StorageExplorer.zip?sv=2020-04-08&st=2021-03-04T02%3A38%3A42Z&se=2021-03-17T01%3A38%3A00Z&sr=b&sp=r&sig=%2FJwyQ%2F0GZPqOs2MUh%2Bx6LKyY%2FYAVCFiljUJIeDjQxkk%3D)
linux: [linux 1.18.1](https://storageexplorerpublish.blob.core.windows.net/privatebuilds/1.18.1-hotfix/Linux_StorageExplorer-x64.tar.gz?sv=2020-04-08&st=2021-03-04T02%3A39%3A01Z&se=2021-03-17T01%3A39%3A00Z&sr=b&sp=r&sig=1pPYKQZ04jLvKkIEiZLLgJlzWhbLD4%2BxVoCmnUrJcK4%3D)

If they work well for you, they will be the exact bits we release for 1.18.1.

Sorry about the broken experience.

**Comment by JurritBZ** [comment]
@JasonYeMSFT The issue I had is resolved.

**Comment by anogues-danone** [comment]
Solved for me too. Thanks!

BR,
Albert

**Comment by mnidza** [comment]
Fixed for me too. Thanks.
