### ISSUE TITLE
Version 1.17.0 - Sorting by Last Modified column does not always work

### ISSUE THREAD

**Issue by rrJNK** [microsoft/AzureStorageExplorer#4152]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20201211.10
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  N/A

## Bug Description ##
When using the Last Modified column to sort, the sortation does not always show the last file written.

## Steps to Reproduce ##
1. Open container
2. Click on arrow on Last Modified column to sort contents.
3. Contents do now always sort to show the latest data (even if you click sort multiple times to sort in both directions)

## Expected Experience ##
I expect to see my latest files (as I see using the explorer in azure portal.

## Actual Experience ##
Do not always see latest files (misleading).

## Additional Context ##
N/A

**Comment by craxal** [comment]
@rrJNK Are the items visible still in the expected order?

Are you expecting to see the last written file from the entire container? Sorting columns only sorts items that have been cached. That is, it only sorts items Storage Explorer has received from the service. The service does not provide an API for retrieving items ordered by some arbitrary search criteria. They only way we could do what you want is to retrieve _all_ items from your blob container. Many users have millions of blobs in their containers, and this would extremely slow.

I'm also not sure what you mean by the Azure portal, as I am unable to sort the contents of a container by any column.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
