### ISSUE TITLE
Version 1.18.0 - Storage Containers do not populate

### ISSUE THREAD

**Issue by xkellyly** [microsoft/AzureStorageExplorer#4153]
**Storage Explorer Version**: 1.18.0
**Build Number**: 20210227.4
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  1.12

## Bug Description ##
Storage Accounts populate but when trying to open the account to see blob containers, nothing appears. Worked previously and currently works in version 1.12. In the properties list, a lot of properties have an "error loading property" message.  
Made sure credentials and account information are all correct. 

## Steps to Reproduce ##
Clicked on Storage Account, Open Container, nothing populates.

**Comment by JasonYeMSFT** [comment]
Could you try 1.17.0? We have seen many others reporting this regression from 1.17.0. We would like to know if yours is the same issue.

**Comment by xkellyly** [comment]
It seems to be working when I am using version 1.17.0

**Comment by JasonYeMSFT** [comment]
Gotcha. We have a very similar issue opened at #4151. Let's merge and continue the discussion there.
