### ISSUE TITLE
Cannot view a table that exists in a Graph DB

### ISSUE THREAD

**Issue by dorfire** [microsoft/AzureStorageExplorer#4154]
**Storage Explorer Version**: 1.18.0
**Build Number**: 20210227.4
**Platform/OS**: macOS Mojave
**Architecture**: x64

## Bug Description ##
I have a graph-API Cosmos DB. **However, in it, there are some tables that are regular tables and not graphs.**
Storage Explorer won't let me view the table or its document, because it thinks it's a graph.

## Steps to Reproduce ##
1. Create graph DB in Cosmos DB
2. Create a regular non-graph table in it
3. Attempt to view it in Storage Explorer

## Expected Experience ##
<!-- A clear and concise description of what

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
