### ISSUE TITLE
Unable to access ADLS Gen2 storage accounts since version 1.18.0

### ISSUE THREAD

**Issue by JurritBZ** [microsoft/AzureStorageExplorer#4155]
**Storage Explorer Version**: 1.18.0
**Build Number**: 20210227.4
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  1.17.0

## Bug Description ##
In version 1.18.0 of the storage explorer. I am unable to access "ADLS Gen2 storage accounts" which I can access with version 1.17.0 of the storage explorer. 

On this storage account I have the Reader role. Further access is managed per individual at container and folder level.

## Steps to Reproduce ##
Install Storage Explorer 1.18.0 and start the application

## Expected Experience ##
Being able to access ADLS Gen2 with Storage Explorer 1.18.0 on all my subscription like in version 1.17.0.

## Actual Experience ##
Under properties everything from Account Name and below shows with the message: "Error loading property". 
![image](https://user-images.githubusercontent.com/36889064/109857170-b295e180-7c5a-11eb-8a5c-d9af2506dea2.png)

All other normal storage accounts on the subscription I can access normally.

On one of my subscriptions I have Contributer Role on the storage account. Here I can also still access the "ADLS Gen2 storage account"

I think it is has to do with some permission. It would help to understand what changed in this area between version 1.17.0 and 1.18.0 for ADLS Gen2.

I have tried to log out and re-log, this did not fix the issue.

**Comment by rizal-ang** [comment]
I'm facing the same issue, had to downgrade to 1.17 to access containers.

**Comment by swapnil-nucleusteq** [comment]
Facing similar issue. Will downgrade the version.

**Comment by JasonYeMSFT** [comment]
We have a very similar issue opened at #4151. Let's merge and continue the discussion there.
