### ISSUE TITLE
File Storage Cannot Be Seen

### ISSUE THREAD

**Issue by deguzman-b** [microsoft/AzureStorageExplorer#4157]
Storage Explorer Version: 1.18
Build Number: 20210227.4
Platform/OS: Windows 10
Architecture: ia32
Regression From:  Yes cannot remember but it's the previous before this one

Bug Description
Error encountered when adding file share:

Unable to retrieve child resources.

Details:
Cannot read property 'version' of undefined

Steps to Reproduce
1. Connect to Azure Storare > FIle Share > Paste URL (SAS)  > Next 

Expected Experience
For the File Share added to appear under File share folder 

Actual Experience
File Share does not appear under File share folder

**Comment by JasonYeMSFT** [comment]
@deguzman-b Could you try this in 1.17.0 to see if it works? Also, could you share the url with us after redacting your personal information in the url? For example, if your original SAS url is "https://accountname.file.core.windows.net/sharename?sv=....sig=ABC"

The redacted SAS url can be "https://contoso.file.core.windows.net/dummy?sv=....sig=redacted"

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. If you still have issue, please open a new one instead.
