### ISSUE TITLE
browser window for authentication does not open

### ISSUE THREAD

**Issue by jpsebasti** [microsoft/AzureStorageExplorer#4158]
**Storage Explorer Version**: 1.18.0
**Build Number**: Mac Cataline 10.15.7
**Platform/OS**: 
**Architecture**: x64
**Regression From**:  

## Bug Description ##

Trying to connect to an Azure subscription.  The screen says a browser window will open to authenticate me.  Nothing happens.

**Comment by JasonYeMSFT** [comment]
Could you check your settings and tell us if your have device code flow and MSAL enabled? Is it possible that your browser is minimized and the sign-in page is opened silently in it? Also, what browser are you using, e.g Firefox, Chrome, etc.? In some cases, we have seen delay for the sign-in page to be opened in the system browser. Could you try waiting a little longer to see if shows up?

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. If you still have issue, please open a new one instead.
