### ISSUE TITLE
Support using storage account connection string to connect in the connect dialog

### ISSUE THREAD

**Issue by yepyao** [microsoft/AzureStorageExplorer#4159]
**Is your feature request related to a problem? Please describe.**
The new connect dialog doesn't support using connection string anymore. This is hard to use.
I usually copy the connection string directly from portal of azure/azure stack hub, and paste it directly into the storage explorer.

**Describe the solution you'd like**
Add back the options that support to using storage connection string when I select "I want to connect to a storage account"

**Describe alternatives you've considered**
no

**Additional context**
no

**Comment by craxal** [comment]
@yepyao Thanks for your feedback. We can use this to improve the experience.

The new dialog _does_ support connecting using a connection string. What kind of connection string do you have? Do you have an account key or a SAS? If it's a SAS connection string, just select the SAS option and paste the connection string as usual. If it's an account key, you can work around this issue for now by selecting the account name and key option pasting the account name and key in place.

**Comment by yepyao** [comment]
@craxal  Thanks for your reply. 

In this issue, I mean the connection string with storage key, not the SAS token.
And yes, I am using the work around way, thanks for that.

Could you please still bring back the connection string page? It's much more convenient. 
Also, seems the work around way doesn't support to specify different endpoints for blob/queue/table which the origin connection string can support.

**Comment by craxal** [comment]
@yepyao I've created #4177 to track adding connection by connection string for multiple resource types.

**Comment by MRayermannMSFT** [comment]
Will track via #4177 for now.
