### ISSUE TITLE
MS Azure Storage Explorer freezes when I delete a blob

### ISSUE THREAD

**Issue by Jake-Breaks-Stuff** [microsoft/AzureStorageExplorer#416]
**Storage Explorer Version**: 1.3.0
**Platform/OS Version**: Windows 10
**Architecture**: ia32/x64
**Build Number**: 20180706.3
**Commit**: 5319bc48
Regression From: Not a regression
**Regression From**: 

#### Steps to Reproduce: ####
1. Added a blob to a blob container (tried folders, plain text, pdf, images, video)
2. Deleted blob
3. Software froze, and remained for ~30 mins, and had to be force quit.

#### Expected Experience: ####
The blob to be deleted.

#### Actual Experience: ####
Step 3.

**Comment by Nyoiks** [comment]
Jake-Breaks-Stuff,

Uninstalled and Reinstalled but same issue. I regret "upgrading" to a product that was not tested comprehensively.

**Comment by vcjdmartinez** [comment]
I'm having the same issue here. Confused as to why it's closed with no resolution.

**Comment by MRayermannMSFT** [comment]
@vcjdmartinez @nyoiks @Jake-Breaks-Stuff  are any of y'all still having this issue in the latest version of Storage Explorer?
