### ISSUE TITLE
Why I am getting this issue in azure storage?>

### ISSUE THREAD

**Issue by v-barose** [microsoft/AzureStorageExplorer#4164]
![image](https://user-images.githubusercontent.com/80118266/110144406-4d4f0700-7da6-11eb-98a3-55a356f45549.png)
 
I get this when trying to access storage info in the azure portal

**Comment by craxal** [comment]
@v-barose First, can you provide us with:
- Storage Explorer version you are using
- OS version
- Steps you followed to come to this error
- What resource you were attempting to expand or open when this error appeared
- How you are authenticating with Azure (sign in, attach via Azure AD, attach via SAS, etc.)

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. If you still have issue, please open a new one instead.
