### ISSUE TITLE
New build is MUCH faster!

### ISSUE THREAD

**Issue by 1RedOne** [microsoft/AzureStorageExplorer#4165]
Hi guys, just installed version 1.18.0 and it is **MUCH FASTER** than before!  

Nice wokr!

**Comment by jinglouMSFT** [comment]
Thanks for your feedback.  Yes, we did some work to improve the install speed.  There was also work done for the startup experience, but you may not notice the differences. We have a few more perf work items in the next couple of milestones.

**Comment by 1RedOne** [comment]
Not only install but the experience of using it!

**Comment by MRayermannMSFT** [comment]
> the experience of using it

If you have any time to elaborate on specifically feels faster, and any parts which you wish were faster, please feel free to do so. :)
