### ISSUE TITLE
Search for resource should allow interacting with that resource

### ISSUE THREAD

**Issue by guiserrato** [microsoft/AzureStorageExplorer#4166]
I have access to several subscriptions and each has dozens of storage accounts so sometimes I like to search for an account.
I can find the account I am looking for, but once I find it I want to do things with it like look at the blob containers, but the UI does not show them in that view, so what are my options? add to quick view? exit search and go find it in the tree?

**Comment by craxal** [comment]
@guiserrato One question. Do you usually know the name of the storage account you want ahead of time? If so, we have #4168 on our backlog.

**Comment by guiserrato** [comment]
I did for the one I was looking for today so that command would have helped me, but I guess my question is what do I gain by searching for a storage account if I then can't look inside? 
My expectation would be to be able to do the same things that I can do in the same view with no search. There are probably good reasons that is not the case today. If just showing its children is not feasible, then maybe a "go-to here"?

**Comment by MRayermannMSFT** [comment]
> exit search and go find it in the tree?

If you exit search, the node which was last selected will be selected in the tree. We actually fixed a bug around this behavior in 1.18.x. Can you try this?

**Comment by guiserrato** [comment]
yes. that's what I was looking for, thanks!
