### ISSUE TITLE
Auth error while registering account with Storage Explorer v 1.18.1

### ISSUE THREAD

**Issue by nidewa** [microsoft/AzureStorageExplorer#4167]
Hi there,

I am getting Auth error while registering account with Storage Explorer v 1.18.1. This has been happening since 3/3/2021, before that I was able to successfully authenticate and use the tool for my storage accounts.

Error: 
This application contains sensitive information and can only be accessed from:
Devices or client applications that meet Microsoft management compliance policy.
The current browser is not supported, please use Microsoft Edge, Internet Explorer or Chrome to access this application.

Attaching the screenshot for reference.
![Screenshot 2021-03-05 141322](https://user-images.githubusercontent.com/29931952/110181217-2b627e00-7dc0-11eb-9b56-2ef982db0cb4.png)

**Comment by jinglouMSFT** [comment]
Can you try to switch to use MSAL? You can do so by going to the Edit menu, then Setting. Enable MSAL in the Sign-in section under the Application tab.

**Comment by nidewa** [comment]
> Can you try to switch to use MSAL? You can do so by going to the Edit menu, then Setting. Enable MSAL in the Sign-in section under the Application tab.

Thanks! That worked..
