### ISSUE TITLE
Unable to import edm.geographypoint data into a new table.

### ISSUE THREAD

**Issue by joshross4** [Microsoft/AzureStorageExplorer#417]
**Storage Explorer Version**: 1.3.0
**Platform/OS Version**: Microsoft Windows [Version 10.0.17134.137]
**Architecture**: ia32
**Regression From**: n/a

#### Steps to Reproduce: ####
1. Export CVS from an SQL query containing a Geography column.
2. Try to import that Geography Column into new table. There isn't an option to import edm.geographypoint data.

#### Expected Experience: ####
If I can manually create a table with a column typed edm.geographypoint, then I should be able to import one too.

#### Actual Experience: ####
I can convert the edm.geographypoint into a edm.string, but that doesn't help me much.

**Comment by craxal** [comment]
Just to clarify, the file is for sure CSV formatted? And it has EDM-typed columns? Can you share a sample of the file you're trying to import?

You might also try making the file extension ".typed.csv".

**Comment by joshross4** [comment]
geo,geo@type,PartitionKey,PartitionKey@type,RowKey,RowKey@type
0xE6100000010C60E5D022DBE34540C86C1CF3B29B55C0,Edm.GeographyPoint,"na",Edm.String,1,Edm.Int32
0xE6100000010C8195438B6C1F454093A98251491955C0,edm.GeographyPoint,"na",Edm.String,2,Edm.Int32
0xE6100000010C5C8FC2F528544540B65D2E030A6B55C0,Edm.GeographyPoint,"na",Edm.String,3,Edm.Int32
0xE6100000010C0C93A98251194540832059236FD054C0,Edm.GeographyPoint,"na",Edm.String,4,Edm.Int32
0xE6100000010C54742497FF364540D578E92631BA54C0,Edm.GeographyPoint,"na",Edm.String,5,Edm.Int32

**Comment by joshross4** [comment]
Even if I had the data format wrong, I would expect to see Edm.GeographyPoint in this drop down list.

<img width="500" alt="screen shot 2018-07-12 at 5 45 31 pm" src="https://user-images.githubusercontent.com/4054637/42661431-27a1f886-85fc-11e8-99df-fbbee505eff1.png">

**Comment by craxal** [comment]
Whoa,`Edm.GeographyPoint`? That data type isn't even supported by the Tables service (see [documentation](https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-the-table-service-data-model#property-types)), so neither does Storage Explorer.

Looks to me like you're going to need to do some processing. You'll need to convert your geo-points into strings you can easily identify before trying to import them into a table.

I'm curious about what you're trying to accomplish importing data from a SQL query into an Azure table. Azure Tables aren't as robust as SQL databases. You might want to consider an [Azure Data Lake](https://azure.microsoft.com/en-us/solutions/data-lake/) solution.

**Comment by joshross4** [comment]
Sorry, I thought that `Edm.GeographyPoint` was a support Table Service datatype.
