### ISSUE TITLE
Querying cosmosDB gave an exception on Azure Storage Exporer

### ISSUE THREAD

**Issue by trungdang194** [microsoft/AzureStorageExplorer#4170]
**Storage Explorer Version**: 1.18.1
**Build Number**: 20210304.5
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  have not checked another version

## Bug Description ##
Error when trying the query SELECT * FROM c Where c.RemovalReason = 31 in CosmosDB query

## Steps to Reproduce ##
With simple data
{
 "RemovalReason": 31
},
{
 "RemovalReason": 21
},
Navigate to cosmosDB container and collection
Right click on the Collection - Documents and select Open Query tab
Enter the query :
SELECT * FROM c Where c.RemovalReason = 31

## Expected Experience ##
Expected to return record has RemovalReason = 31

## Actual Experience ##
Receiving exception 
![image](https://user-images.githubusercontent.com/13807246/110199223-04707e80-7e8a-11eb-9408-3204068724db.png)
![image](https://user-images.githubusercontent.com/13807246/110199316-734dd780-7e8a-11eb-9561-d70f6a2d1a47.png)

## Additional Context ##
another query also produce same exception 
SELECT * FROM c Where c.RemovalReason > 21
![image](https://user-images.githubusercontent.com/13807246/110199330-8365b700-7e8a-11eb-88aa-3ef447a1e834.png)

while entering 
SELECT * FROM c Where c.RemovalReason = 21 
it will work, return expected data
![image](https://user-images.githubusercontent.com/13807246/110199308-69c46f80-7e8a-11eb-8ff9-5021581b2840.png)

* On azure portal, querying to CosmosDB Data explorer will return expected result,
![image](https://user-images.githubusercontent.com/13807246/110199414-db042280-7e8a-11eb-8059-b48175a2e40f.png)

**Comment by southpolesteve** [comment]
This is a known issue with an older version of the Cosmos SDK that is used by Storage Explorer. Please see this thread for more information https://github.com/microsoft/AzureStorageExplorer/issues/3161
