### ISSUE TITLE
There is a red wavy line under the strings in text boxes

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4172]
**Storage Explorer Version**: 1.18.0
**Build Number**: 20210306.4
**Branch**: main
**Platform/OS**: Windows 10/ Linux ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Previous release (1.18.1)

## Bug Description ##
There are a red line under the strings in text boxes.

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create one blob container then right click it -> Select 'Properties...'
3. Click 'Add Metadata'.
4. Check there is no red line under the added metadata key.

## Expected Experience ##
There is no red wavy line.

## Actual Experience ##
There is a red wavy line.
![image](https://user-images.githubusercontent.com/41351993/110285974-159ec400-801f-11eb-8053-7d394595a8c5.png)

## Additional Context ##
1. This issue also reproduces for the default access policy id on the 'Access Policies' dialog.
2. This issue also reproduces for one Account key/ Service URI/Connection string/SAS URL to the 'Enter Connection Info' dialog.
![image](https://user-images.githubusercontent.com/41351993/110285710-9f01c680-801e-11eb-93bc-06caf395f2cb.png)

3. This issue also reproduces for the 'Clone' blob dialog.
![image](https://user-images.githubusercontent.com/41351993/110285720-a1fcb700-801e-11eb-96b6-c664f26d9c2e.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into main
