### ISSUE TITLE
Unable to retrieve child resource when working with proxy

### ISSUE THREAD

**Issue by eedokl** [microsoft/AzureStorageExplorer#4174]
**Storage Explorer Version**: 1.18.0, 1.18.1
**Build Number**: 20210304.5
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  1.17.x

## Bug Description ##
When I double click on "Blob containers" in a storage account I get an error "Unable to retrieve child resources.", see error details below.
I am working behind a proxy. So I used either a local proxy or put a proxy in the settings.
This worked fine until 1.17.0. With 1.18.x I get the error.
Interestingly, the error disappears when I toggle once the proxy settings off/on in a running session.
However, when I restart storage explorer it shows the error again (until I toggle proxy settings once).

## Steps to Reproduce ##
hen I double clock on a blob storage container

## Expected Experience ##
Get a list of containers

## Actual Experience ##
Error: "Unable to retrieve child resources."

## Additional Context ##
Error Details:

```
Unable to retrieve child resources.

Details:
{
  "name": "RestError",
  "message": "request to https://xdrmeasurements.blob.core.windows.net/?include=metadata&comp=list failed, reason: getaddrinfo ENOTFOUND xdrmeasurements.blob.core.windows.net",
  "__zone_symbol__error": {
    "originalStack": "Error: request to https://xdrmeasurements.blob.core.windows.net/?include=metadata&comp=list failed, reason: getaddrinfo ENOTFOUND xdrmeasurements.blob.core.windows.net\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:197:55)\n    at step (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:141:62)\n    at step (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)",
    "zoneAwareStack": "Error: request to https://xdrmeasurements.blob.core.windows.net/?include=metadata&comp=list failed, reason: getaddrinfo ENOTFOUND xdrmeasurements.blob.core.windows.net\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:197:55)\n    at step (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:141:62)\n    at step (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)"
  },
  "stack": "RestError: request to ....blob.core.windows.net/?include=metadata&comp=list failed, reason: getaddrinfo ENOTFOUND ....blob.core.windows.net\n    at new RestError (C:\\Program Files (x86)\\Microsoft Azure Storage 
...
```

**Comment by MRayermannMSFT** [comment]
> when I toggle once the proxy settings off/on

To confirm, are you doing this via the proxy dialog (edit -> proxy settings) or the settings page?

Can you also share your settings.json file with us. You can find it by going to:

`C:\Users\<your username>\AppData\Roaming\StorageExplorer`

Look for the file called settings.json and attach it to this issue. Thanks.

**Comment by eedokl** [comment]
I used the setting page. I did not check if the same occurs with the proxy dialog yet.

The settings.json is rather limited...

{
  "application.telemetry.userId": "a....2",
  "application.proxy.source": "environmentVariable"
}

**Comment by MRayermannMSFT** [comment]
Can you share your proxy environment variables with us? You can do this by opening powershell, and pasting in:
```
$env:HTTPS_PROXY
$env:HTTP_PROXY
```
and then press enter. Thanks!

**Comment by eedokl** [comment]
http://localhost:3128
http://localhost:3128

**Comment by MRayermannMSFT** [comment]
@eedokl so do you have a proxy server at that address you need to use? If no, then you should either remove those environment variables or change the proxy source setting to be "do not use proxy".

**Comment by eedokl** [comment]
Yes, I am working at Bosch behind a company firewall and I need to setup a proxy (in my case PX) or have to use a company specific proxy to be able to work to access my data with Storage Explorer. When I disable the proxy, it cannot connect.
Actually, this worked all fine up until 1.17.x. With 1.18.x (and still with 1.19.0) my problem is that when I start Storage Explorer it will not use my proxy, i.e. it behaves like no "do not use proxy" even though it starts up with proxy usage enabled.
When I now click on the proxy on/off dropdown menu and select "do not use proxy" and then switch back to using a proxy all works fine again until I start Storage Explorer newly.

**Comment by craxal** [comment]
@eedokl Can you share the Storage Explorer logs with us? You can find them by selecting Help > Open Logs Directory. Please share at least "main" and "se-blob-extension".

**Comment by eedokl** [comment]
@craxal and @MRayermannMSFT 
Attached the logs. In the renderer log we see that my proxy is known to the tool, but in blob extension we see its given as undefined...
[2021-04-28_080522_renderer.log](https://github.com/microsoft/AzureStorageExplorer/files/6389421/2021-04-28_080522_renderer.log)

[2021-04-28_080522_main.log](https://github.com/microsoft/AzureStorageExplorer/files/6389418/2021-04-28_080522_main.log)
[2021-04-28_080522_se-blob-extension_9240.log](https://github.com/microsoft/AzureStorageExplorer/files/6389419/2021-04-28_080522_se-blob-extension_9240.log)

**Comment by eedokl** [comment]
When I now toggle the proxy settings to off and on again the problem is gone for the running session.
[2021-04-28_080522_renderer.log](https://github.com/microsoft/AzureStorageExplorer/files/6389515/2021-04-28_080522_renderer.log)

**Comment by craxal** [comment]
Based on the logs, it looks like the blob extension isn't getting the proxy setting at startup. Switching the setting off and on sends a message with the proxy settings to the extension, which then properly uses them in requests.

Thank's for reporting this issue! We'll investigate further for a fix.

**Comment by eedokl** [comment]
@craxal We are working with Blob Storage on ADLS Gen2 Containers  (without hierarchical file system)

**Comment by craxal** [comment]
@eedokl Thanks. Yeah, I looked through the code, and it looks like the ADLS Gen2 module isn't reacting to proxy changes, which is probably why you're experiencing problems. This should be fixed for 1.20.0. As a workaround, does restarting Storage Explorer restore proper functionality?

**Comment by craxal** [comment]
@eedokl So, I did find an issue, but I'm not sure it's actually related to your issue.

I looked back at your comments, and I have a few more questions for you:
1. You said you've set your `HTTPS_PROXY` and `HTTP_PROXY` environment variables to "localhost:3128". Does that mean you have a proxy server running on your _local machine_? The app's proxy is usually only set to localhost if we're using something like Fiddler to examine network calls.
2. You've said that you're using environment variables. How did you set those environment variables? Are you sure the Storage Explorer main process is receiving those variables? Setting environment variables is best done if you're setting them and running Storage Explorer from the command line.
3. Did you try setting `STG_EXP_HTTPS_PROXY` and `STG_EXP_HTTP_PROXY`?

**Comment by eedokl** [comment]
@craxal 
1) Restarting Storage Explorer will not help. What does help is when I started Storage Explorer, I toggle the proxy configuration to "no proxy" and then back to either "Environment Variables" or "App Settings". This is what we had seen also from logs where you earlier mentioned 
"_Based on the logs, it looks like the blob extension isn't getting the proxy setting at startup. Switching the setting off and on sends a message with the proxy settings to the extension, which then properly uses them in requests._"

2) 
1. I have several options for proxy in my company. There are some proxy servers, or I can use tools like cntlm or px to run a local proxy server. The latter is required sometimes as the server proxy we have may not fullfill all developer needs. Anyway, Storage Explorer as such runs with both solutions - once I toggle the setting off/on
2. In Storage Explorer Proxy settings I select "use environment variables" in the GUI. Then in my environment I have px installed and HTTPS_PROXY and HTTP_PROXY set. I assumed that this is taken up by Storage Explorer because it works for me, after toggling off/on.
3. However, as I also ask my colleagues to work with Storage Explorer, and I dont want them to install px, I changed my typical setup from "use environment variables" to "app proxy setting" and fill protocol (http), hostname and port to one of our companys server proxy - as that one is available also for my co-workers/users. Still, we need to toggle off/on before it works after starting.
4. I did not try to set STG_EXP_...
5. I may add again that all worked fine until including version 1.17.x, and broke with 1.18.x onwards

**Comment by craxal** [comment]
@eedokl
> Then in my environment I have px installed and HTTPS_PROXY and HTTP_PROXY set.

I'm still unclear as to how you actually set your environment variables. Can you elaborate on that? Also, when you say you switch the settings off/on, I assume that means you set Proxy Source to "Do not use proxy" then "Use environment variables"?

We've done some work on proxy recently. Would you be open to trying out a private build to see if it fixes the problem?

**Comment by craxal** [comment]
@eedokl Do you have an update since the last comment I posted?

As a heads up, we've been revamping our proxy functionality in order to support NO_PROXY situations. I expect those changes to make at least a few previous proxy issues go away, so stay tuned.

**Comment by eedokl** [comment]
@craxal Sorry, seems your June 9th question went to my spam filter.

I'm still unclear as to how you actually set your environment variables. Can you elaborate on that? Also, when you say you switch the settings off/on, I assume that means you set Proxy Source to "Do not use proxy" then "Use environment variables"?

I go to "Settings Icon" on the left, and in the section "Proxy" I either use "Use environment variables" where I have set my proxy settings to HTTPS_PROXY and HTTP_PROXY. Alternatively I set the proxy settings by using "Use app proxy settings", "https:" and set hostname and port in the respective fields. I do not need to authenticate in my environment.

When storage explorer starts freshly, both such setting options do not work for me starting with version 1.18 (i.e. no problem existed in version 1.17 and before).

When I say I switch on/off what I mean is that when I started storage explorer the setting is set to "Use app proxy settings" from a previous session. Now, I get errors to access my blobs storage. What I then do is to change the proxy selection from  "Use app proxy settings" to "do not use proxy" and right after that I change it back to "Use app proxy settings".

Once I have done this access to my storage works as wanted, and in addition we can see in logs of se_blob-extension:
...
[2021-04-28T06:20:53.964Z] (se-blob-extension_9240) Blob extension notified of proxy change: { credential: undefined }
[2021-04-28T06:20:57.307Z] (se-blob-extension_9240) Blob extension notified of proxy change: { ... }
[2021-04-28T06:21:08.131Z] (se-blob-extension_9240) API call for BlobServiceClient.listContainersSegment succeeded

I can surely try out a private build or new version.

**Comment by craxal** [comment]
@eedokl
> ...where I have set my proxy settings to HTTPS_PROXY and HTTP_PROXY.

This is the part I was asking about. How did you set these environment variables? Did you set them from the command line, and if so, what command did you use? Also, how are you launching Storage Explorer? Is it also from the command line?

**Comment by eedokl** [comment]
@craxal
I have set the environment variables someday via windows command shell using setx, I. e. they are persistent in my Windows environment since long time as I need them for various tools regularly. 
I start Storage Explorer by double click of its desktop icon.

**Comment by craxal** [comment]
@eedokl Thanks. I suspect Storage Explorer is not getting the environment variables for some reason. Can you try the following?

1. Launch a new cmd prompt.
2. Execute `echo %HTTPS_PROXY%` or `echo %HTTP_PROXY%`.
3. Does this print out the correct values? If so, try launching Storage Explorer from this same prompt and see if everything works.

If that doesn't work, try these steps:

1. Launch a new PowerShell prompt.
2. Execute `echo $env:HTTPS_PROXY` or `echo $env:HTTP_PROXY`.
3. Does this print out the correct values? If not, set the environment variables with the same values as your persistent variables:
   ```powershell
   $env:HTTPS_PROXY = "myproxy.com"
   $env:HTTP_PROXY = "myproxy.com"
   ```
3. Launch Storage Explorer from this same command prompt and see if everything works.

**Comment by eedokl** [comment]
@craxal I tried as above with cmd prompt, variables are there with correct values, launching from prompt is not working. Anyway, the problem is gone with the recent release of 1.20.1.

**Comment by craxal** [comment]
@eedokl OK, thanks. I'll mark this issue as mitigated, then. If you continue to have problems, please open a new issue, and we'll look into it further.
