### ISSUE TITLE
On mac, it is not even loading

### ISSUE THREAD

**Issue by harlandgomez** [microsoft/AzureStorageExplorer#4175]
it hangs when opening the app, it cannot even show the login process. I have already allow all access to keychain.

Version 1.18.1
AzCopy Version 10.8.0
Platform: macOs BigSur

**Comment by MRayermannMSFT** [comment]
@harlandgomez can you elaborate on what you mean by "it hangs when opening the app".
- Are you able to get past the splash screen?
- If yes, are you able to open the connect dialog after the main window appears?
- If yes, are you able to open a login window (the window where you enter your username and password)?
- Have you tried restarting your machine?

**Comment by harlandgomez** [comment]
After splash screen it does not show anything anymore so it does not come to connect dialog at all. 

I can see the menu items, I can choose File -> New Window and it will open two instances then the Terms And Condition will sometimes show that I have to click the "I Agree" button and after that it is gone again. I can do it and it creates another instance but does nothing. It used to be fine with the lower version but I could not find the lower version of the app anymore.

I have restarted many times and even shutdown.

**Comment by MRayermannMSFT** [comment]
@harlandgomez can you try deleting `~/Library/Application Support/StorageExplorer/appState.json`, and then if that doesn't work, also try deleting everything in `~/Library/Application Support/StorageExplorer/`?

**Comment by harlandgomez** [comment]
> @harlandgomez can you try deleting `~/Library/Application Support/StorageExplorer/appState.json`, and then if that doesn't work, also try deleting everything in `~/Library/Application Support/StorageExplorer/`?

It works even by just deleting appState.json.. Thank you!!

**Comment by MRayermannMSFT** [comment]
@harlandgomez I regret not asking this

**Comment by harlandgomez** [comment]
@MRayermannMSFT, sorry I used "rm" command to remove the file because I could locate that folder thru Finder. In any case it happens again, I will contact you directly.

**Comment by MRayermannMSFT** [comment]
Ok :(
