### ISSUE TITLE
Change "Select Authentication Method" panels to "Select Connection Method" panels

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#4177]
A significant number of users still use connection strings to connect to resources, specifically storage accounts and emulators. Currently, we ask for an "authentication method" in the new connect experience.

This feature request proposes we modify the authentication selection panels to be "Select Connection Method" panels. These panels will retain their current selection options, but we can also add connection string options where appropriate. This will also simplify validation in the connection entry panels.

**Comment by craxal** [comment]
@jinglouMSFT @MRayermannMSFT @JasonYeMSFT Please consider triage for 1.19.0. I don't expect this work to be very expensive, as the connect experience scaffolding is already in place.

**Comment by MRayermannMSFT** [comment]
That or just add connection string as an option like:

"Connection String (Key or SAS)"

**Comment by v-xianya** [comment]
Verified this issue on build 20210312.1. Fixed.
![image](https://user-images.githubusercontent.com/41351993/110908151-5d885880-8349-11eb-97c0-4fbb343b0ba2.png)

**Comment by craxal** [comment]
@JasonYeMSFT I'm reopening this issue, because the descriptions still use the word "authenticate". The description should be changed to say something like, "How will you connect to the \<resource\>?"

**Comment by craxal** [comment]
Looks like I already merged this in a previous PR.
