### ISSUE TITLE
Unable to set up a share file folder on Azure VM drive

### ISSUE THREAD

**Issue by nagarajukshirasagarldmglobal** [microsoft/AzureStorageExplorer#4178]
Unable to retrieve child resources.

Details:
getaddrinfo ENOTFOUND bootdiagv55j74dhcxg4g.file.central.cayman.azurestack.ky

**Comment by MRayermannMSFT** [comment]
@nagarajukshirasagarldmglobal is your VM behind a proxy, if so you'll need to set that up: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#proxy-issues

Are you able to access your resources via Storage Explorer on another machine? Do you have other tools that can access your resources from this VM?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
