### ISSUE TITLE
An unexpected error occurs when starting Storage Explorer on Linux without .NET Core Runtime installed

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4181]
**Storage Explorer Version**: 1.18.1
**Build Number**: 20210308.1
**Branch**: main
**Platform/OS**: Linux ubuntu 18.04
**Architecture**: x64
**Regression From**: Previous release (1.18.1)

## Steps to Reproduce ##
1. Create a clean Linux virtual machine with OS (ubuntu 18.04).
2. Download the Storage Explorer .tar.gz file -> Extract it.
3. Open 'Terminal' -> Go to the path '/StorageExplorer-linux-x64'.
4. Run the command './StorageExplorer' to start Storage Explorer.
5. Check there is no unexpected error.

## Expected Experience ##
1. There is no unexpected error.
2. A dialog pops up with the reminder 'you must have .NET Core 2.1 installed'.
![image](https://user-images.githubusercontent.com/41351993/110439198-21a78600-80f2-11eb-983e-15e3e993d157.png)

## Actual Experience ##
There is an unexpected error.
![image](https://user-images.githubusercontent.com/41351993/110439207-253b0d00-80f2-11eb-8cbc-7e7ddba49328.png)

## Additional Context ##
This issue doesn't reproduce when having the .NET Core Runtime installed.

**Comment by MRayermannMSFT** [comment]
I think this is fixed. @v-xianya can you verify if this still repros?

**Comment by v-xianya** [comment]
@MRayermannMSFT 
Verified this issue on build 20210324.5. Not reproduce. so we are going to close it.
