### ISSUE TITLE
I cannot login my account after updated to version 1.18.1

### ISSUE THREAD

**Issue by itaowei** [microsoft/AzureStorageExplorer#4182]
Request Id: a66d7d5c-5f1e-4f53-b81a-c7f2686c0200
Correlation Id: 040adca5-fb56-45fd-a820-fd2b7ee36020
Timestamp: 2021-03-09T08:53:31.109Z
App name: Microsoft Azure CLI
App id: 04b07795-8ddb-461a-bbee-02f9e1bf7b46
IP address: 167.220.233.13
Device identifier: Not available
Device platform: Windows 10
Device state: Unregistered

**Comment by jinglouMSFT** [comment]
How did you sign-in?  Can you try using MSAL? You can do this by checking Edit->Settings->Application->Sign-in->MSAL. Restart Storage Explorer then sign in again.

**Comment by asthanarht** [comment]
i am also not able to login in new build 

Troubleshooting details
If you contact your administrator, send this info to them.
Copy info to clipboard
Request Id: 051fe02f-038b-4306-af64-9ed43f4d1e00
Correlation Id: 2379509e-d435-4b6e-a9e4-c0cdf20d8ed7
Timestamp: 2021-03-10T23:24:08.751Z
App name: Microsoft Azure CLI
App id: 04b07795-8ddb-461a-bbee-02f9e1bf7b46
IP address: 73.42.174.190
Device identifier: Not available
Device platform: Windows 10
Device state: Unregistered
Flag sign-in errors for review: Enable flagging
If you plan on getting help for this problem, enable flagging and try to reproduce the error within 20 minutes. Flagged events make diagnostics available and are raised to admin attention.

**Comment by jinglouMSFT** [comment]
@asthanarht - you need to switch to use MSAL for your sign-in.

**Comment by itaowei** [comment]
Thanks for MS teams! The problem solved!
