### ISSUE TITLE
An unexpected error occurs after deleting the custom environment which has an azure account signed in

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4184]
**Storage Explorer Version**: 1.18.1
**Build Number**: 20210308.1
**Branch**: main
**Platform/OS**: Windows 10/ Linux ubuntu 18.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Previous release (1.18.1)

## Steps to Reproduce ##
1. Open Storage Explorer -> Make sure the settings 'MASL' & 'Code Flow' are enabled.
2. Open the connect dialog -> Select 'Subscription -> Custom Environment' -> Click 'Manage custom environments...'.
3. Add one custom environment (enter 'https://management.azure.com' to the ARM endpoint field).
4. Use the custom environment to sign in.
5. Delete the custom environment after successfully signing in.
6. Check no error occurs.

## Expected Experience ##
No error occurs.

## Actual Experience ##
An unexpected error occurs.
![image](https://user-images.githubusercontent.com/41351993/110462573-d4381280-810b-11eb-86be-d92d0b645bf3.png)

The specific steps please see the video:
![custom](https://user-images.githubusercontent.com/41351993/110459198-a5b83880-8107-11eb-9b36-e5702a0bc4c7.gif)

## Additional Context ##
1. This issue can't be reproduced consistently.
2. Display a duplicate account when signing in with 'MSAL' enabled selecting Custom Environment (on a fully clean VM).
3. There is a similar issue [2836](https://github.com/microsoft/AzureStorageExplorer/issues/2836).

**Comment by MRayermannMSFT** [comment]
I think this is fixed. @v-xianya can you verify if this still repros?

**Comment by v-xianya** [comment]
@MRayermannMSFT Verified this issue on build 20210324.5. Not reproduce.
