### ISSUE TITLE
Not possible to add a File Share using a File share SAS URL

### ISSUE THREAD

**Issue by Wiszanyel** [microsoft/AzureStorageExplorer#4185]
**Storage Explorer Version**: 1.18.1
**Build Number**: 20210304.5
**Platform/OS**: Windows 10 Enterprise Edition
**Architecture**: x64
**Regression From**:  It was working on version 1.17.0

## Bug Description ##
Trying to add a File Share using a File share SAS URL is failing with the error: The SAS contains an invalid resource parameter. Only file share resources ('sr=s') are supported.

## Steps to Reproduce ##
1. Create a SAS for the File share service.
2. Open Azure Storage Explorer.
3. Open the connect dialog and select File share.
4. Put the File service SAS URL in that field, and check the error.

## Expected Experience ##
Be able to add the File share with the File service SAS URL.

## Actual Experience ##
When trying to add the File share using SAS URL, the following error appears: The SAS contains an invalid resource parameter. Only file share resources ('sr=s') are supported

**Comment by MRayermannMSFT** [comment]
@Wiszanyel are you trying to use an account level SAS? You can check by looking for `ss=<some letters>` in your SAS token.

If yes, then for now you can work around this by:
1. Remove the name of your file share from the SAS URL
2. Use that URL to attach a storage account via SAS

That will attach the entire storage account, and give you access to all shares in it for which the SAS is authorized.

**Comment by Wiszanyel** [comment]
Hi @MRayermannMSFT I'm trying to mount only for File Services (ss=f).

If I remove the name of the file share in the SAS URL, the following error appears:
The URL is missing a path to the resource.

Using the SAS URL on the "connect storage account menu" works (already test it).

Is this a bug on the Connect > File Share module? Because per my understanding, using the SAS URL should grant access to that File Share itself, or at least do the same thing as adding the File Share using the Connect > Storage account module.

Thank you for your response!

**Comment by craxal** [comment]
@Wiszanyel Just to simplify things, can you share your SAS with us (redact the signature, and feel free to remove the account name from the endpoint)? It sounds like you're using an account SAS, but I want to be sure.

**Comment by Wiszanyel** [comment]
SAS URL = https://<saname>.file.core.windows.net/?sv=2020-02-10&ss=f&srt=sco&sp=rwdlc&se=2021-03-16T05:47:06Z&st=2021-03-15T21:47:06Z&spr=https&sig=nsClvWh7ipb0N4wzaA9Fg69%2FfBojLUdde9MZVoRXWzA%3D

**Comment by craxal** [comment]
@Wiszanyel Are you trying to connect to a _single_ file share, or are you trying to connect to the file share _service_ and get to all the file shares in that service?

If you want to connect to a file service, you should select "Storage account" from the Select Resource panel and select the SAS URL option, and that should work. We can clarify that in the Select Resource panel by changing the label to be "Storage account or service" or something like that.

If you want to connect to a single file share, we do have make some modifications so that the panel access account-level SAS again.

**Comment by Wiszanyel** [comment]
Thank you for checking this @craxal. I wanted to add a single file share with the new module to add File Share, for testing purposes.

**Comment by craxal** [comment]
@Wiszanyel Out of curiosity, are you able to connect to other sources with the same SAS? For example, if you selected "Blob container" and entered https://saname.blob.core.windows.net/?sv=2020-02-10&ss=b&srt=sco&sp=rwdlc&se=2021-03-16T05:47:06Z&st=2021-03-15T21:47:06Z&spr=https&sig=REDACTED, does that connect successfully?

**Comment by Wiszanyel** [comment]
@craxal it is possible. Using a Blob SAS URL I'm able to connect to a specific container.

Blob SAS URL: https://<saname>.blob.core.windows.net/bla/?sv=2020-02-10&ss=b&srt=sco&sp=rwdlacx&se=2021-03-20T07:43:47Z&st=2021-03-19T23:43:47Z&spr=https&sig=x1Tt06dBpmmq6htxDztdymA3aLVr6szI9uKyffIOtrI%3D

**Comment by JasonYeMSFT** [comment]
We have merged a fix for this. The fix will be included in the next 1.19.0 release.
