### ISSUE TITLE
KWallet Is Not Recognised As A Password Manager

### ISSUE THREAD

**Issue by opticyclic** [microsoft/AzureStorageExplorer#4190]
**Storage Explorer Version**: 1.18.1
**Build Number**: 20210304.5
**Platform/OS**:  KUbuntu 20.04 LTS
**Architecture**: x64

## Bug Description ##

When I try to start Storage Explorer it says:

> Microsoft Azure Storage Explorer must be connected to the system's 
> password manager service to keep your data safe, but the service 
> plug has not been connected yet. Please run the following command 
> before launching the application again: 
> 
> sudo snap connect storage-explorer:password-manager-service :password-manager-service 

This does nothing and thus I am unable to start the application.

KWallet is installed and is working with other applications just fine.

I get the same error when running from the tar as well as the snap.

## Steps to Reproduce ##

 - Install KUbuntu 20.04 LTS
 - Install Storage Explorer as a snap
 - Start Storage Explorer

## Expected Experience ##

I expect it to start and connect to KWallet.

## Actual Experience ##

It refuses to connect to KWallet and fails to start with the error in the description.

**Comment by craxal** [comment]
@opticyclic Storage Explorer uses the `keytar` native Node module to access your machine's password manager. As of 1.18.0, we use version 5.6.0. The error message you're seeing comes up after we run a quick test with `keytar`. If `keytar` is unable to function, we show the error message.

I know that [`keytar`](https://www.npmjs.com/package/keytar) is supposed to use the `libsecret` API. Does KWallet use that API as well?

**Comment by guattang** [comment]
Issue still exists in a completely fresh install of Kubuntu 22.04.

**Comment by craxal** [comment]
@guattang @opticyclic Is KWallet compatible with the `libsecret` API? As explained above, we use `keytar`, which uses `libsecret` on Linux machines. If `libsecret` is not installed, Storage Explorer will not work properly.

**Comment by radekgala** [comment]
I was able to run it on KDE after install Gnome Keyring 
sudo apt-get -y install gnome-keyring

**Comment by craxal** [comment]
@radekgala Yes, that's because Gnome Keyring uses the `libsecret` API, which is compatible with the `keytar` package we use.

The question still remains, does KWallet use `libsecret` as well? It seems it should be supported since KDE Framework 5.97.0 (according to [this page](https://wiki.archlinux.org/title/KDE_Wallet)).

**Comment by craxal** [comment]
@Vernando The error message you received is being thrown before Storage Explorer can check for any password manager or keyring issues. You need to resolve auth library issues first.

Are you using the snap distribution or the .tar.gz distribution? If using the .tar.gz, you need to make sure .NET 6 is installed on your machine and functional (use the `dotnet` command, for example). .NET 6 comes bundled with the snap distribution.
