### ISSUE TITLE
Keep a consistent display for the character ':' in the URLs of one file share snapshot and blob snapshot

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4191]
**Storage Explorer Version**: 1.18.1
**Build Number**: 20210309.6
**Branch**: main
**Platform/OS**: Windows 10/ Linux ubuntu 18.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account.
2. Create one blob container -> Upload one blob then create one snapshot for the blob.
3. Right click the blob snapshot -> Click 'Copy URL' -> Paste the URL to one .txt file.
4. Create one file share then right click it -> Click 'Create Snapshot'.
5. Right click the file share snapshot -> Click 'Copy URL' -> Paste the URL to one .txt file.
6. Compare the two URLs, check whether there is a consistent display for the character ':'

## Expected Experience ##
There is a consistent display for the character ':'.

## Actual Experience ##
There is an inconsistent display for the character ':'.

For file share snapshot : The character ':' displays as '%3A' in the URL.
`https://account0308adls.file.core.windows.net/file?sharesnapshot=2021-03-10T05%3A54%3A13.0000000Z
`

For blob snapshot: Display ':' in the URL.
`https://account0308.blob.core.windows.net/one/StorageExplorer.exe?snapshot=2021-03-10T06:09:29.4530301Z`

**Comment by JasonYeMSFT** [comment]
Both urls are correct. The file share v2 SDK is using a deprecated url.resolve() function which unnecessarily encodes : characters.
