### ISSUE TITLE
The SAS attached storage account name displays '(Unknown)' in the copied table activity log

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4192]
**Storage Explorer Version**: 1.18.1
**Build Number**: 20210309.6
**Branch**: main
**Platform/OS**: Windows 10/ Linux ubuntu 18.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Select one storage account.
2. Use SAS connection string to attach the storage account with full permissions.
3. Expand the SAS attached storage account -> Tables.
4. Select one table then right click it -> Click 'Copy Table' -> Paste the table.
5. Check whether the SAS attached storage account name shows well in the activity log.

## Expected Experience ##
The SAS attached storage account name shows well.

## Actual Experience ##
The SAS attached storage account name shows '(Unknown)'.
![image](https://user-images.githubusercontent.com/41351993/110601660-28043380-81c0-11eb-88cd-bd3ab021f24e.png)

## Additional Context ##
This issue doesn't reproduce for one file share/ blob container.

**Comment by JasonYeMSFT** [comment]
This is due to a legacy SasUri class not supporting the new endpoint. Since the connect dialog has been rewritten, we should migrate things depending on it to use the new StorageUrl class.

**Comment by v-xianya** [comment]
@JasonYeMSFT 
Verified this issue on build 20210313.6. Are the below behaviors expected?
There is a 'https://' that precedes the SAS attached storage account name in the copied table activity log.
![image](https://user-images.githubusercontent.com/41351993/111095460-71fe6800-8578-11eb-9dd8-7bc242692752.png)

There is no 'https://' precedes the SAS attached storage account in the copied blob container/ file share activity log.
![image](https://user-images.githubusercontent.com/41351993/111095542-9c502580-8578-11eb-995b-ae94f32a226e.png)
