### ISSUE TITLE
Miss the services endpoint and account name in the 'Summary' dialog when attaching one storage account via the service URL

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#4193]
**Storage Explorer Version**: 1.18.1
**Build Number**: 20210309.6
**Branch**: main
**Platform/OS:** Windows 10/ Linux ubuntu 18.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##

1. Select one storage account -> Click 'Open in portal' -> Copy one Blob service SAS URL with full permissions and full services in the portal.
2. Open the connect dialog -> Click 'Storage account -> Shared access signature(SAS)'.
3. Paste the URL ->Observe the 'Summary' dialog.
4. Check whether the services endpoint and the account name show.

## Expected Experience ##
All services endpoint show well.

## Actual Experience ##

The services endpoint and the account name do not show.
![image](https://user-images.githubusercontent.com/54055206/110604730-5a636000-81c3-11eb-9f60-4beb77509ede.png)

## Additional Context ##
This issue doesn't reproduce for one connection string attached storage account.
![image](https://user-images.githubusercontent.com/54055206/110607194-ed04fe80-81c5-11eb-8b4e-bf3055efe141.png)

**Comment by v-xianya** [comment]
Verified this issue on build 20210312.1. Fixed.
