### ISSUE TITLE
Fail to delete items under one ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4194]
**Storage Explorer Version**: 1.18.1
**Build Number**: 20210309.6
**Branch**: main
**Platform/OS**: Windows 10/ Linux ubuntu 18.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account.
2. Right click the 'Blob Containers' node -> Create a blob container.
2. Open the blob container -> Create a folder -> Try to delete the folder.
3. Check whether succeed to delete the folder.

## Expected Experience ##
Succeed to delete the folder.

## Actual Experience ##
Fail to delete the folder.
![image](https://user-images.githubusercontent.com/41351993/110607387-1b82d980-81c6-11eb-98c7-9543e9d5cca4.png)

![image](https://user-images.githubusercontent.com/41351993/110607727-73214500-81c6-11eb-942d-02355921760e.png)

## Additional Context ##
This issue also reproduces when deleting one ADLS Gen2 blob.

**Comment by JasonYeMSFT** [comment]
I added a trusted endpoint suffix setting that by default trusts *.storage.azure.net" endpoints. As long as that setting is there, AzCopy should be able to work.

**Comment by v-xianya** [comment]
Verified on build main/20210326.4. Fixed.
