### ISSUE TITLE
There is an extra 'Back' button on the Sign in panel when using 'Integrated Sign-in'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4197]
**Storage Explorer Version**: 1.18.1
**Build Number**: 20210311.3
**Branch**: main
**Platform/OS**: Windows 10/ Linux ubuntu 18.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Previous release (1.18.1)

## Steps to Reproduce ##
1. Open Storage Explorer -> Open 'Settings -> Application-> Sign-in ' -> Select 'Integrated Sign-in'.
2. Open the connect dialog -> Click 'Subscription' -> Click 'Next'.
3. Check there is no 'Back' button on the Sign in panel.

## Expected Experience ##
There is no 'Back' button on the Sign in panel.
![image](https://user-images.githubusercontent.com/41351993/110766646-5bae8e80-8290-11eb-810e-39005b6395d6.png)

## Actual Experience ##
There is an extra 'Back' button on the Sign in panel.
![image](https://user-images.githubusercontent.com/41351993/110766540-3b7ecf80-8290-11eb-8048-a8bea3852c6b.png)

## Additional Context ##
Show the below behavior after clicking the 'Back' button.
![image](https://user-images.githubusercontent.com/41351993/110766737-741ea900-8290-11eb-88e3-19a2f0aabdfe.png)

**Comment by MRayermannMSFT** [comment]
We can't get rid of the back button, but I believe I have fixed the crashing. Please confirm that has at least been fixed.

**Comment by v-xianya** [comment]
@MRayermannMSFT 
Verified this issue on build 20210315.7. The crashing is fixed. Show the below behavior after clicking 'Back':

The Sign in dialog exits and show the activity log 'Unable to sign in: User canceled authentication.'

**Comment by v-xianya** [comment]
Update:
The expected behavior after clicking 'Back'
Go back to the 'Sign In' dialog, as below screenshot.
![image](https://user-images.githubusercontent.com/41351993/112248741-66eeba80-8c91-11eb-85c5-9f1831d35959.png)
