### ISSUE TITLE
The connect dialog is closed after closing the 'Sign in' dialog with the 'Integrated Sign-in' option 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#4198]
**Storage Explorer Version**: 1.18.1
**Build Number**: 20210311.3
**Branch**: main
**Platform/OS:** Windows 10/ Linux ubuntu 18.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Previous release(1.18.1)

## Steps to Reproduce ##

1. Launch Storage Explorer -> Open the 'Settings' -> Select '**Integrated Sign-in**'.
2. Open Connect dialog -> Click 'Subscription -> Azure' -> Click 'Next'.
3. A 'Sign in' dialog pops up -> Close the dialog.
4. Check the connect dialog is not closed.

## Expected Experience ##
The connect dialog is not closed.
![image](https://user-images.githubusercontent.com/54055206/110761675-fb691e00-828a-11eb-8d58-cb2f6a0d93c2.png)

## Actual Experience ##

1. The connect dialog is closed.
2. An error shows in the activity log.
![image](https://user-images.githubusercontent.com/54055206/110761141-58b09f80-828a-11eb-96c9-d76e1a7441e0.png)
Details:
{
  "message": "\"User canceled authentication.\""
}

**Comment by MRayermannMSFT** [comment]
Fix merged for 1.18

**Comment by v-limu** [comment]
Verified on build 20210323.4. The 'Sign in' dialog doesn't pop up when opening connect dialog with the 'Integrated Sign-in' option. It always show 'Waiting for authentication...'. This issue is blocked. So we re-open it.
![image](https://user-images.githubusercontent.com/54055206/112113521-dd3be000-8bf1-11eb-99dd-61820a7998bd.png)

**Comment by MRayermannMSFT** [comment]
I have restored integrated sign in working. :)
