### ISSUE TITLE
The progress spinning wheel in activity log is not in high contract color

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#42]
Storage Explorer Version:  1.0.0
OS Version:  Windows 10

![image](https://user-images.githubusercontent.com/10081483/38838459-0094ef1a-418b-11e8-80bc-37c6477c3ed4.png)

**Comment by JasonYeMSFT** [comment]
A change is merged to make the progress spinner's color adjust according to the theme.
