### ISSUE TITLE
This application contains sensitive information and can only be accessed from: Devices or client applications that meet Microsoft management compliance policy.

### ISSUE THREAD

**Issue by saurk** [microsoft/AzureStorageExplorer#4201]
sauku@ 
You can't get there from here
This application contains sensitive information and can only be accessed from:
Devices or client applications that meet Microsoft management compliance policy.
The current browser is not supported, please use Microsoft Edge, Internet Explorer or Chrome to access this application.

IP address: 24. 
Device identifier: Not available
Device platform: Windows 10
Device state: Unregistered
Flag sign-in errors for review: Enable flagging
If you plan on getting help for this problem, enable flagging and try to reproduce the error within 20 minutes. Flagged events make diagnostics available and are raised to admin attention.

**Comment by jinglouMSFT** [comment]
Can you please turn on the option to use MSAL?  Go to Edit->Setting->Applications->Sign-in->MSAL.  Restart Storage Explorer. MSAL will be the default in our next release.

**Comment by JasonYeMSFT** [comment]
@saurk Could you elaborate on detailed steps from getting Storage Explorer (the application) to how you see the "You can't get there from here" error? Do you know if there is any special policy on your device? Storage Explorer is a public facing application and it shouldn't be blocked at the application level.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem, feel free to open a new issue. Thanks.
