### ISSUE TITLE
Can't login on Microsoft Azure Storage Explorer

### ISSUE THREAD

**Issue by Han76024** [microsoft/AzureStorageExplorer#4202]
After I upgrade to Azure storage explorer v1.18.1 I cannot login using my microsoft account, please see the screen shot for error message below:
You can't get there from here
This application contains sensitive information and can only be accessed from:
Devices or client applications that meet Microsoft management compliance policy.
The current browser is not supported, please use Microsoft Edge, Internet Explorer or Chrome to access this application.

Troubleshooting details
If you contact your administrator, send this info to them.
Copy info to clipboard
Request Id: 94c7a221-2489-416e-948a-566314391f00
Correlation Id: b3f5fe5c-34e2-4bf5-bf68-037511b2f54a
Timestamp: 2021-03-11T23:53:34.790Z
App name: Microsoft Azure CLI
App id: 04b07795-8ddb-461a-bbee-02f9e1bf7b46
IP address: 71.231.206.225
Device identifier: Not available
Device platform: Windows 10
Device state: Unregistered
Flag sign-in errors for review: Disable flagging
If you plan on getting help for this problem, enable flagging and try to reproduce the error within 20 minutes. Flagged events make diagnostics available and are raised to admin attention.

**Comment by jinglouMSFT** [comment]
Please use MSAL for your authentication. You can do so by enabling MSAL from Edit->Settings->Application->Sign-in, then check MSAL and restart Storage Explorer.

**Comment by Han76024** [comment]
I can login now, thank you!
