### ISSUE TITLE
Azure Storage Explorer overloads system on large uploads

### ISSUE THREAD

**Issue by JorickvdHoeven** [microsoft/AzureStorageExplorer#4206]
When uploading large files on resource constrained hardware, the azure storage explorer does not set AZCOPY_CONCURRENCY_VALUE=AUTO. This causes azcopy to use a huge amount of threads locking up the system and ultimately severely negatively impacting the transfer speed. 

For example, on my system (Macbook Pro 15" i7) it spins up 256 threads for concurrent upload even though when running azcopy manually with the concurrency value enabled it stabilized on 4-8 concurrent upload threads due to other activities on my machine and the available bandwidth.

The storage explorer should set AZCOPY_CONCURRENCY_VALUE=AUTO as an env variable before executing azcopy commands.

**Comment by MRayermannMSFT** [comment]
@JorickvdHoeven at this time the AzCopy team has recommended to use that we not use AUTO as the default value of AZCOPY_CONCURRENCY_VALUE. If you wish to use that value though, you can configure that via the in app settings. Go to:

Settings -> Transfers -> Network Concurrency -> choose Adjust dynamically

This is the equivalent of AUTO. Let us know if you have any further questions.
