### ISSUE TITLE
Accessing Tables results in "Authentication error: undefined"

### ISSUE THREAD

**Issue by Pierre450** [microsoft/AzureStorageExplorer#4207]
In Azure Storage Explorer, I am logged in with domain admin rights. I can access Blob Containers without any issues. When I try to access Tables, I get the error "Authentication error: undefined". 

I have been able to access Tables without issues in the past. This is a recent error.

I am using Azure Storage Explorer 1.18.1

**Comment by MRayermannMSFT** [comment]
@Pierre450 do you have access to your storage account keys as well? You can check by:
1. click on the storage account node for the account you are having trouble with
2. go to the properties panel in the bottom left and look for 'Primary Key' or the 'Secondary Key' properties
3. click on the eye icon
4. check if the value there is a key and is the correct key for the storage account and then let us know

**Comment by Pierre450** [comment]
@MRayermannMSFT Thank you for your answer. I figured out the answer late last night. It turns out that the clock on my computer didn't adjust for daylight savings time. Once I changed the time on my computer, everything started working correctly again.
