### ISSUE TITLE
Add Built-in support for secondary endpoint for GRS storage accounts

### ISSUE THREAD

**Issue by beroder** [microsoft/AzureStorageExplorer#421]
**Storage Explorer Version**: 1.3
**Platform/OS Version**: Windows 10 version 1803
**Architecture**: ia32
**Regression From**: Not a regression

#### Steps to Reproduce: ####
N/A

#### Expected Experience: ####
Provide built-in support for access a storage account's secondary endpoint.  The secondary endpoint should be accessible after connecting to the primary.  The storage account key is the same the only difference is the string '-secondary' gets appended to the storage account name in the storage endpoint URL.

#### Actual Experience: ####
You can connect to the secondary endpoint but it requires a second connection and you have to manually fix up the connection string to point to the secondary endpoint.

### Work ###
- [x] Add secondary endpoint attributes to storage accounts
- [x] Add secondary endpoint support to relevant node actions
- [x] Hide secondary endpoint properties if not present
- [x] Hide write actions for secondary endpoint nodes
- [x] Add Location property if account has secondary endpoints

**Comment by jinglouMSFT** [comment]
Make it a P1 per Kris Fritz's request.

**Comment by ankitgadhiya** [comment]
When can we expect a solution on this issue? Any other workaround?
