### ISSUE TITLE
Unable to sign in: Could not get list of tenants

### ISSUE THREAD

**Issue by rgraham7503** [microsoft/AzureStorageExplorer#4214]
**Storage Explorer Version**: Version: 1.18.1
**Build Number**: 20210304.5 
**Platform/OS**:  macOS Big Sur 11.2.3
**Architecture**: x64 
**Regression From**:  1.17.x

## Bug Description ##
Says I have to reenter my credentials...I do and I have done this for multiple accounts, I login successfully then get 
"Unable to sign in: Could not get the list of tenants"

{
  "message": "\"Could not get the list of tenants\""
}

## Steps to Reproduce ##
Try to login to any active azure portal account in storage explorer

## Expected Experience ##
View my storage and generate a SAS

## Actual Experience ##
Cant view any storage in any account

## Additional Context ##
This just started

**Comment by dspringer59** [comment]
I have exactly the same problems. Already tried to switch MSAL on, but impossible to log in after upgrading to 1.18.1.

**Comment by rgraham7503** [comment]
Pretty serious problem as of now I cannot login to any of my customers storage, nor my own!!!!

**Comment by rgraham7503** [comment]
Something else bigger seems to be wrong on the Azure portal side. I logged into 3 accounts new browser...shows no subscriptions for any of them! some are corporate accounts that obviously have subscriptions, and I am getting welcome and a tour questions on these!?>!?!??!?!?!? WTF

**Comment by rgraham7503** [comment]
https://downdetector.com/status/windows-azure/
Well here you go! DOWN

**Comment by dspringer59** [comment]
It seems to be solved, can login again at three different servers, so must have been the Azure problems.

**Comment by MRayermannMSFT** [comment]
Sounds like this issue was created during last weeks AAD outage. If any of y'all are continuing to have issues, please either contact support or open a new issue here. Thanks!
