### ISSUE TITLE
Fail to upload one append blob to one HNS blob container with the setting 'Enable ADLS Gen2 append blob (Preview)' enabled

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4218]
**Storage Explorer Version**: 1.19.0-dev
**Build Number**: 20210315.8
**Branch**: main
**Platform/OS**: Windows 10/ Linux ubuntu 18.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Open Storage Explorer.
2. Go to 'Settings -> Services' -> Enable the setting 'Enable ADLS Gen2 append blob (Preview)'.
3. Expand one ADLS Gen2 storage account -> Blob Containers.
4. Create one blob container -> Upload one append blob to the blob container.
5. Check whether succeed to upload the append blob.

## Expected Experience ##
Succeed to upload the append blob.

## Actual Experience ##
Fail to upload the append blob.

1. Show a failed activity log.
![image](https://user-images.githubusercontent.com/41351993/111285770-757b1780-867c-11eb-8dcd-88caf7564f44.png)

2. Show the append blob with 0 B size in the editor after manually refreshing.
![image](https://user-images.githubusercontent.com/41351993/111285781-78760800-867c-11eb-80fd-c6f655fba8f0.png)

## Additional Context ##
This issue also reproduces when coping & pasting one append blob.

**Comment by JasonYeMSFT** [comment]
You need to enroll in the feature to be able to use it. You can find a form to enroll a subscription here https://azure.microsoft.com/updates/append-blob-support-for-azure-data-lake-storage-preview/

**Comment by v-xianya** [comment]
OK, got it. We are going to close this issue.
