### ISSUE TITLE
Version: 1.18.1 - The SAS is missing a required services ('ss') parameter.

### ISSUE THREAD

**Issue by PavelKrastev85** [microsoft/AzureStorageExplorer#4221]
**Storage Explorer Version**: Version: 1.18.1
**Build Number**: 20210304.5
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  1.17.0

## Bug Description ##
When attempting to add a storage account using SAS URI, an error is displayed and does not let you progress
error 'missing required parameter 'ss' in SAS token

## Steps to Reproduce ##
1. Create a storage account.
2. Create blob container via console storage explorer.
3. Right click blob container and select 'Get Shared Access Signature'.
4. Choose Access policy and Start/Expiry times and click Create.
5. Container, URL and Query string values are displayed.
6. Copy URL into Storage Explorer URI field.

## Expected Experience ##
A clear and concise description of what you expected to happen. If applicable, add screenshots to help explain what you expected. 

## Actual Experience ##
"error 'missing required parameter 'ss' SAS token" is displayed, next button is disabled.

## Additional Context ##
Also tested using the cloud powershell commands and got the same result.
This bug is similar to [1517](https://github.com/microsoft/AzureStorageExplorer/issues/1517)

**Comment by MRayermannMSFT** [comment]
@PavelKrastev85 the step to focus on here is:

> Right click blob container and select 'Get Shared Access Signature'.

When you generate a SAS for a container, that SAS can only access resources in that container. Therefore, you can't use that SAS to attach an **entire** storage account. You need to generate a Storage Account level SAS token if you want to attach your entire account. You can do that by right clicking on the storage account node and choosing 'Get Shared Access Signature'.

Alternatively, you can use the SAS you have already generated to attach that specific container.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of reply. Please open a new issue if you are still encountering this problem.

**Comment by patelamit06** [comment]
I am trying to generate SAS token for container and then I get error The SAS is not a valid account SAS. An account SAS with service ('ss') and resource type ('srt') parameters is required.
