### ISSUE TITLE
Upload does not complete when transfer limit is enabled.

### ISSUE THREAD

**Issue by s0ar** [microsoft/AzureStorageExplorer#4225]
**Storage Explorer Version**: 1.18.1
**Build Number**: 20210404.5
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  
**AzCopy-Version**: 10.8.0  

## Bug Description ##
When using a data transfer limit, the upload never completes

## Steps to Reproduce ##
1. Go to Settings: Configure transfer limit of i.e. 5 MBit/s
2. Upload a large file (in my case 4.4 GB)
3. The upload starts and show the upload rate of 5 Mbits

## Expected Experience ##
There is a progress in percent shown and finally the upload completes successfully.
(When no transfer limit is set, a progress in percent is displayed.)

## Actual Experience ##
The progress percent value is missing, the upload never completes. After several hours i got an error message, something like that the SAS expired.

## Additional Context ##
Gave it another try, after several hours the upload was not completed although the Windows Resource Manager showed that constantly 5MBit/s were transferred. Cancelled the upload.
I removed the transfer limit, uploaded again: Upload completed successfully.

The corresponding AZCopy Command was:
./azcopy.exe copy "somefile" "https://someaccount.windows.net/url/file?sv=2020-04-08&se=2021-04-15T11%3A49%3A33Z&sr=c&sp=rwl&sig=somesig" --overwrite=prompt --from-to=LocalBlob --blob-type Detect --follow-symlinks --cap-mbps 5 --put-md5 --follow-symlinks --block-blob-tier=Archive --recursive;

**Comment by MRayermannMSFT** [comment]
@s0ar are you sure the error message was that the SAS had expired? There is an in app setting which controls how long of a SAS token will be generated for doing uploads/downloads/copies. By default the length of time is 30 days. Looking at the command you provided, it seems like you haven't changed the value for that setting.

If you want to try this again with a limited upload rate can you also try changing the network setting?
![image](https://user-images.githubusercontent.com/21112697/112037422-f2841200-8afe-11eb-9dfe-f14dd5bbff10.png)
You can try either choosing the 2nd option or trying to find a custom number which seems to work well.

We've heard from the AzCopy team before that if you set your transfer limit very low, you might need to also adjust your network concurrency. When you don't, the vast number of network connections AzCopy opens to the server will timeout and that can cause problems.

If you'd like additional help tuning your AzCopy settings to fit your needs, we suggest going and asking the AzCopy team more questions at https://github.com/Azure/azure-storage-azcopy

**Comment by MRayermannMSFT** [comment]
Closing due to lack of reply. Please open a new issue if you are still encountering this problem.
