### ISSUE TITLE
Update the action item 'Select all' to 'Select All' under the 'Edit' menu

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4228]
**Storage Explorer Version**: 1.19.0-dev
**Build Number**: 20210317.3
**Branch**: main
**Platform/OS**: Windows 10/ Linux ubuntu 18.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Open Storage Explorer.
2. Click 'Edit' menu -> Check the action items under the menu.
3. Check whether show 'Select All' under the menu.

## Expected Experience ##
Show 'Select All'.

## Actual Experience ##
Show 'Select all'.
![image](https://user-images.githubusercontent.com/41351993/111453453-8dbb6700-874e-11eb-8595-2c71b9ecae1b.png)

**Comment by v-limu** [comment]
Verified on build 20210324.5. This issue has been fixed. So we close it.
