### ISSUE TITLE
Fail to focus on the new attached container/share/queue/table

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/AzureStorageExplorer#423]
**Storage Explorer Version**: 1.3.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180711.4
**Commit**: 47039639
**Regression From**: Previous Release 1.2.0(20180605.1)

#### Steps to Reproduce: ####
1. Click 'Refresh All', then drill down from storage account -> queue.
2. Right click this queue and attach it using SAS URI.
3. Check the result.

#### Expected Experience: ####
Succeed to focus on the new attached queue.

#### Actual Experience: ####
Fail to focus on the new attached queue.

More Info:
This issue also reproduces for blob containers/file shares/tables.

**Comment by craxal** [comment]
I think this has been fixed. @v-dantch, please verify.

**Comment by v-dantch** [comment]
@craxal Hi Craig, please get more information form below.

Actual:
The attached queue isn't focused and even the 'Local&Attached -> Storage Accounts -> (SAS-Attached Services) -> Queues' doesn't expand. 

Screenshot:
![compare](https://user-images.githubusercontent.com/34729092/43299550-25718c58-914a-11e8-93e6-bd577c2a880c.PNG)

**Comment by craxal** [comment]
@v-dantch, as mentioned earlier, the bug doesn't reproduce, so I'm going to close this.

**Comment by v-haiz** [comment]
@craxal 
**Fail to focus on the new attached blob container/file share/queue** in the latest release candidate build 1.4.0(20180730.1)

**Screenshot:**
![comparefocus](https://user-images.githubusercontent.com/37653604/43449427-ef908b4e-949f-11e8-8891-9fd6d147bec1.PNG)
