### ISSUE TITLE
Unable to retrieve child resources.

### ISSUE THREAD

**Issue by ck2270** [microsoft/AzureStorageExplorer#4231]
**Storage Explorer Version**: 1.15.1
**Build Number**: 20200902.9
**Platform/OS**: Win 10
**Architecture**: ia32

## Bug Description ##
 unable to get local issuer certificate

## Steps to Reproduce ##
1 . Connect to Storage Account
2 . Attempt to open any child resource

## Expected Experience ##
Open child resource

## Actual Experience ##
Error
["FetchError:request to https://xxxxxxstorage.blob.core.windows.net/?include=metadata&comp=list failed, reason: unable to get local issuer certificate"]

**Comment by trigurl** [comment]
Same here!  How to resolve this?

**Comment by tvance-vant4ge** [comment]
Same

**Comment by JasonYeMSFT** [comment]
Are you using a proxy? If you do, you'll need to import your cert to Storage Explorer. See https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting#error-self-signed-certificate-in-certificate-chain-and-similar-errors

**Comment by MRayermannMSFT** [comment]
Closing due to lack of reply. Please open a new issue if you are still encountering this problem.
