### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by trigurl** [microsoft/AzureStorageExplorer#4232]
**Storage Explorer Version**: March 2021 (Version 1.18.1)
**Build Number**: Version 1.18.1
**Platform/OS**:  Windows 10
**Architecture**: x64
**Regression From**:  I haven't used Storage Explorer for many months so I don't know what version I had prior to upgrading.

## Bug Description ##
1) Login with Azure Storage Explorer with my name and key and I get Unable to retrieve child resources

## Steps to Reproduce ##
1. Login to access my storage blob with Azure Storage Explorer with my name and key 

## Expected Experience ##
I should be able to access my storage blob

## Actual Experience ##
Unable to retrieve child resources.

Details:
getaddrinfo ENOTFOUND <ACCOUNTNAME>.file.core.windows.net

## Additional Context ##
Causing some of our automation to fail since we can't access our storage.  I work at MS so please email me for more info.

**Comment by JasonYeMSFT** [comment]
@trigurl Could you verify if the storage account still exists and if the key has is up to date?

**Comment by trigurl** [comment]
Let me see if I can figure out who on our team created it.  If the account doesn't exist anymore can the contents still be retrieved?

**Comment by trigurl** [comment]
So found out who the owner was, and it looks like the account was taken down just recently, is there any way we can still retrieve the contents of our storage?

**Comment by JasonYeMSFT** [comment]
Theoretically the contents are deleted when the storage accounts are deleted. You need to contact the support team asap to see if they can recover the data before it really gets garbage collected.

**Comment by shawnweisfeld** [comment]
There are good instructions on how to do what @JasonYeMSFT is suggesting here: https://docs.microsoft.com/en-us/azure/storage/common/storage-account-recover

**Comment by shawnweisfeld** [comment]
moreover, for future accounts, we have tools to prevent it from getting accidently deleted in the first place https://azurestorage.com/docs/application-and-user-data/basics/azure-blob-storage-data-protection-features/

**Comment by MRayermannMSFT** [comment]
Closing this issue as there is nothing we (the storage explorer team) can do to help data recovery. Please use the links provided by everyone above to get that process started and prevent things like this from happening in the future.
