### ISSUE TITLE
Unable to get child resources.

### ISSUE THREAD

**Issue by huismansander** [microsoft/AzureStorageExplorer#4233]
Unable to get child resources.

Details:
write EPROTO 245628296:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

**Comment by tvance-vant4ge** [comment]
i signed into my personal subscription/account ... and then it stopped giving me this error and I could see the data.  Even though it wasnt connected with my account.  Weird.

**Comment by JasonYeMSFT** [comment]
@huismansander The error is about an incorrect certificate. Could you verify if you imported any proxy related cert and if they are correct?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of reply. Please open a new issue if you are still encountering this problem.
