### ISSUE TITLE
Sign-In Error

### ISSUE THREAD

**Issue by pgavril** [microsoft/AzureStorageExplorer#4234]
Upon sighning with Hello certificate - getting an error:
{
  "message": "\"Attempted to access an element as a type incompatible with the array.\""
}

**Comment by MRayermannMSFT** [comment]
@pgavril wen you say "Upon sighning with Hello certificate" do you mean you did something like getting here and choosing one of the certificates?

![image](https://user-images.githubusercontent.com/21112697/112035808-278f6500-8afd-11eb-8a05-7d241d9b4fef.png)

**Comment by pgavril** [comment]
yes

Best Regards

Peter Gavriliouk
954 338 8208

**Comment by MRayermannMSFT** [comment]
@pgavril 

Can you try going to Settings (gear icon on the left) -> Application -> Sign In -> check the checkbox for Microsoft Authentication Library, restart, and try signing in. You should be asked to sign in with your browser. Let us know if that works.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of reply. Please open a new issue if you are still encountering this problem.
