### ISSUE TITLE
Unable to create a new Container(Collection) in Cosmos Db database.

### ISSUE THREAD

**Issue by timetraveller432** [microsoft/AzureStorageExplorer#4237]
**Storage Explorer Version**: 1.17.0 and the Azure Portal Cosmos Db Explorer as well.
**Build Number**: 20201211.10
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  Not sure.

## Bug Description ##
This happens both in Azure Cosmos Web Explorer and the Azure Storage Explorer. When I try to create a new container with default settings in a database, the error pops up.

```
Failed to create collection.

Details:
{"code":400,"body":"{\"code\":\"BadRequest\",\"message\":\"Setting offer throughput or autopilot on container is not supported for serverless accounts.\\r\\nActivityId: <ActivityId here> Microsoft.Azure.Documents.Common/2.11.0\"}","activityId":<ActivityId here>}
```

## Steps to Reproduce ##

1. Right-click on the database name in the Cosmos Db Storage Explorer
2. Click Create a new collection
3. Fill in the defaults
4. Error shows up.

## Expected Experience ##
Should be able to create a new collection.

## Actual Experience ##
Error

**Comment by timetraveller432** [comment]
It seems to work fine if created programmatically. 
After filing the issue I thought of trying it by creating one using the C# Azure function binding. It succeeded.

```
[FunctionName("FunctionName-here")]
public static async Task RunAsync(
    [TimerTrigger("*/30 * * * * *")] TimerInfo myTimer,
    [CosmosDB(databaseName: "DbName-here",
              collectionName: "CollectionName-here",
              CreateIfNotExists = true,
              PartitionKey = "PartitionKey-here",
              ConnectionStringSetting = "Conn-String-here")]
              IAsyncCollector<OutDoc> outputDocument,
              ILogger log) {
.
.
.
.
}
)
```

**Comment by southpolesteve** [comment]
@timetraveller432 can you file a support ticket via the Azure Portal? 

If creation is not working for you via the Azure Portal it means there is something else going on here and the issue isn't specific to Storage Explorer
