### ISSUE TITLE
It would be better to use 'Specify' instead of 'Choose' in the description for the 'Paste Disk' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4239]
**Storage Explorer Version**: 1.19.0-dev
**Build Number**: 20210320.3
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Open one resource group -> Upload one disk.
2. Copy the blob then click paste -> Observe the description in the 'Paste Disk' dialog. 
3. Check whether the description is accurate or not.

## Expected Experience ##
1. The description is accurate.
2. Use 'Specify' instead of 'Choose'.

## Actual Experience ##
The description is not accurate.
![image](https://user-images.githubusercontent.com/41351993/111950827-c461fa80-8b1d-11eb-8f55-3edcc6fe9b5d.png)

## Additional Context ##
The description in the 'Create Snapshot' dialog.
![image](https://user-images.githubusercontent.com/41351993/111951132-30446300-8b1e-11eb-96f2-873b145feae3.png)

**Comment by v-xianya** [comment]
@MRayermannMSFT 
Verified this issue on build 20210324.5. 
The word 'Choose' has been updated to 'Specify' but there is an extra 'and' in the description. 

Details please see the screenshot. we are going to open this issue.

![image](https://user-images.githubusercontent.com/41351993/112247149-c0091f00-8c8e-11eb-93bc-f549ebd6a448.png)

**Comment by MRayermannMSFT** [comment]
Fixed.
