### ISSUE TITLE
Microsoft Azure storage explorer - Query Search issue

### ISSUE THREAD

**Issue by Desai042** [microsoft/AzureStorageExplorer#4240]
![ASTE_Bug](https://user-images.githubusercontent.com/37859664/111958602-6f20eb80-8b13-11eb-89c5-b30b45fe6316.PNG)
Hi While searching Query using Microsoft azure storage table found one issue in the Operator column.  if we select string field operator dropdown showing wrong values. it should be like =, contains,
 starts with, or ends with.

**Comment by MRayermannMSFT** [comment]
@Desai042 the operators "=", ">", "<", etc. are the operators which are available even for string types. The available operators to us are limited by what the table service supports. With regards to querying tables, the table supports OData queries, which use the operators you are seeing: https://docs.microsoft.com/en-us/rest/api/storageservices/querying-tables-and-entities#supported-comparison-operators
