### ISSUE TITLE
Unable to retrieve child resources.

### ISSUE THREAD

**Issue by obum** [microsoft/AzureStorageExplorer#4241]
Unable to retrieve child resources.

Details:
{
  "name": "RestError",
  "message": "This request is not authorized to perform this operation.\nRequestId:52903a3b-f01e-0036-1039-1f5303000000\nTime:2021-03-22T16:33:10.0359937Z",
  "__zone_symbol__error": {
    "originalStack": "Error: This request is not authorized to perform this operation.\nRequestId:52903a3b-f01e-0036-1039-1f5303000000\nTime:2021-03-22T16:33:10.0359937Z\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError 

Error message after - trying to create a container
Failed to create blob container 'images': This request is not authorized to perform this operation.
RequestId:8f66c8bc-c01e-0070-6b39-1f6784000000
Time:2021-03-22T16:34:33.1144462Z

**Comment by MRayermannMSFT** [comment]
@obum we need some more information from you:

- How have you authenticated? Are you signed in? Did you attach with key/SAS/Azure AD?
- What version of Storage Explorer are you in?
- Is this a new issue for you/was what you are trying to do working before?

**Comment by obum** [comment]
Yes I have been authenticated . I am using a sandbox account

 using a SAS token

Storage explorer version is 1.8

This is a new issue for me

**Comment by MRayermannMSFT** [comment]
@obum Storage Explorer 1.8??? Did you mean to type 1.18? 

With regards to your SAS token?
- Has it expired. Check the "se=" field in the SAS to see the expiration time.
- Can you share the SAS permissions with us? That would be everything in the "sp=" field.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of reply. Please open a new issue if you are still encountering this problem.
