### ISSUE TITLE
Cannot find Azure Storage Explorer on SAW

### ISSUE THREAD

**Issue by laserljy** [microsoft/AzureStorageExplorer#4244]
**Storage Explorer Version**:  v1.17.0
**Build Number**:  No build number
**Platform/OS**:  Windows 10, on SAW
**Architecture**:   x64
**Regression From**:    

## Bug Description ##

After installing Azure Storage Explorer in "Software Center" on SAW, and restart SAW, I cannot find Azure Storage Explorer on Start menu, or anywhere. 

## Steps to Reproduce ##

Described as above.

## Expected Experience ##

I can open Azure Storage Explorer on SAW and use it.

## Actual Experience ##

Described as above in Bug Description

**Comment by MRayermannMSFT** [comment]
@laserljy have you talked to SAW support about this? We don't have any insight into how Software Center handles installation of our app.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of reply. Please open a new issue if you are still encountering this problem.
