### ISSUE TITLE
Miss the legal hold properties and policy properties for one new created blob container

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#4246]
**Storage Explorer Version:** 1.19.0-dev
**Build Number**: 20210323.4
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create a new blob container -> Observe its properties in the 'Properties' panel.
3. Check the legal hold properties and policy properties show well.

## Expected Experience ##
The legal hold properties and policy properties show well.

## Actual Experience ##
Miss the legal hold properties and policy properties.

## Additional Context ##

1. This issue also reproduces for one cloned blob container.
2. This issue doesn't reproduce after manually refreshing.

**Comment by v-limu** [comment]
Verified on build 20210324.5. This issue is fixed for one new created blob container. **But this is reproduces for one new cloned blob container.**

**Comment by JasonYeMSFT** [comment]
I found a similar issue for paste container. When I say this is merged, please help me verify that scenario as well.

**Comment by v-limu** [comment]
Ok. Got it. We will verify that scenario when this is merged.😊

**Comment by v-limu** [comment]
Verified on build 20210326.4. This issue has been fixed for one cloned and pasted blob container. So we closed it.
