### ISSUE TITLE
There is a mismatch description in the 'Open Container by Name' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4247]
**Storage Explorer Version**: 1.19.0-dev
**Build Number**: 20210323.4
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Bug Description ##
The description 'If you know the name of a blob container, you can open it directly without having to wait for Storage Explorer to find it for you.' does not apply to the current dialog.

For the current dialog, You need to press the 'Search' button even if you type the whole blob container name.
![image](https://user-images.githubusercontent.com/41351993/112131201-43c9f980-8c04-11eb-8a78-6b5ab015483c.png)

## Steps to Reproduce ##
1. Expand one storage account -> Right click the 'Blob Containers' node.
2. Click 'Open Container by Name...' -> Observe the description on the opened dialog.
3. Check whether the description matches.

## Expected Experience ##
The description matches.

## Actual Experience ##
The description doesn't match.
![image](https://user-images.githubusercontent.com/41351993/112130128-19c40780-8c03-11eb-84fc-ad1cf12a502e.png)

**Comment by MRayermannMSFT** [comment]
Let's make it about not having to click "Load more".

**Comment by v-xianya** [comment]
@craxal 
Verified this issue on build 20210407.5. The description is not updated. so we are going to re-open this issue.
![image](https://user-images.githubusercontent.com/41351993/113854685-bbd21b00-97d1-11eb-9515-0b47464a5309.png)

**Comment by v-xianya** [comment]
Verified this issue on build main/20210408.5. Fixed.
![image](https://user-images.githubusercontent.com/41351993/113959956-4a887b80-9856-11eb-9f48-c1e9fe9196c4.png)
