### ISSUE TITLE
Loc Assistance

### ISSUE THREAD

**Issue by cristianosuzuki77** [microsoft/AzureStorageExplorer#4255]
String Resource ID : 0; "WarningUnknownTableEndpoint"
Source String : The endpoint suffix is not a known blob suffix. Make sure the URL is correct before continuing.
Filename : loc/en/src/Standalone/resources/ConnectDialog.json
Question :  According to the resource id - 0; "WarningUnknownTableEndpoint", It seems 'a known blob suffix' should be 'a known table suffix'. So we translated 'blob suffix' as 'table suffix'. Please check it.

**Comment by MRayermannMSFT** [comment]
The source string is wrong, so that's a bug we need to fix.

**Comment by JasonYeMSFT** [comment]
We have fixed the English string to be "...table suffix". Thanks for catching this.
