### ISSUE TITLE
Connection string option to connect is required

### ISSUE THREAD

**Issue by humblejay** [microsoft/AzureStorageExplorer#4259]
Not able to use Storage Explorer with IoT Edge Blob module, which was possible in earlier version 1.17.0.  This is because option to use connection string has been removed in 1.18.0

**Describe the solution you'd like**
Provide option to use connection string to connect with Blob Storage

**Describe alternatives you've considered**
Alternative to use Account Name + Key is not working as it does not capture all the necessary parameters such as "BlobEndpoint"  or  different port numbers

**Additional context**

**Comment by MRayermannMSFT** [comment]
@humblejay yes that was an overlooked scenario during the refresh of the connect dialog. It is coming back in 1.19 though. @JasonYeMSFT has already done the work and it will be included with that release. In the meantime, you can download older versions of Storage Explorer from here: https://github.com/microsoft/AzureStorageExplorer/releases
