### ISSUE TITLE
Tried to re-enter login details - Error Details Window Pop Up 

### ISSUE THREAD

**Issue by ciph3rwoman** [microsoft/AzureStorageExplorer#4260]
**Storage Explorer Version**:  v.1.17.0
**Build Number**: 
**Platform/OS**:  Windows 10 
**Architecture**: 
**Regression From**:   This was working yesterday without any issues. 

## Bug Description ##

This is the bug that I am getting. 

Unable to retrieve child resources.

Details:
{
  "name": "Error",
  "message": "Unable to retrieve authentication token while creating ARM client for Disks.\nFailed to refresh access token",
  "__zone_symbol__error": {
    "originalStack": "Error: Unable to retrieve authentication token while creating ARM client for Disks.\nFailed to refresh access token\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError 

## Steps to Reproduce ##

- When I navigate to enter credentials, I do not get to the enter in credential section.

## Actual Experience ##

When I login it automatically has an Error Details Window pop up in Azure Storage Explorer. 

## Additional Context ##

Please see screenshot below. 
<img width="749" alt="Error Details" src="https://user-images.githubusercontent.com/32854599/112421081-4d359c00-8d93-11eb-828b-ee9ee46384da.png">

**Comment by ciph3rwoman** [comment]
Please feel free to make some troubleshooting suggestion. It is much appreciated.

**Comment by JasonYeMSFT** [comment]
@ciph3rwoman Could you try upgrading to 1.18.1 and use the MSAL to sign-in? To enable MSAL, you can go to Settings (gear icon on the left) -> Application -> Sign In -> check the checkbox for Microsoft Authentication Library, restart, and try signing in. You should be asked to sign in with your browser. Let us know if that resolves the error.

**Comment by ciph3rwoman** [comment]
It works now after upgrade. Closing this issue now. Thanks for your help.

**Comment by ciph3rwoman** [comment]
Closing this - Issue has been resolved.
