### ISSUE TITLE
The error details are unclear when creating a disk snapshot with whitespaces

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4262]
**Storage Explorer Version**: 1.19.0-dev
**Build Number**: 20210325.3
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand the 'Disks' node -> Open one resource group.
2. Upload one disk to it -> Click 'Create Snapshot'.
3. Delete the default snapshot name then type whitespaces as the snapshot name -> Click 'Create'.
4. Check whether the error details are clear.

## Expected Experience ##
The error details are clear.

## Actual Experience ##
The error details are unclear.
![image](https://user-images.githubusercontent.com/41351993/112449431-5708d080-8d8e-11eb-85f0-7789d241aa68.png)

## Additional Context ##
1. Show the below behavior when trying to type whitespaces as the disk/ disk snapshot name.
![image](https://user-images.githubusercontent.com/41351993/112450478-68061180-8d8f-11eb-9416-17fdd02d5690.png)

2. This issue also reproduces when uploading one disk then specify whitespaces as the disk name.
 
![image](https://user-images.githubusercontent.com/41351993/112449646-946d5e00-8d8e-11eb-9f6e-5b5a23a3a2cf.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into main.

**Comment by v-xianya** [comment]
@MRayermannMSFT 
I added this to the regular test case and marked it as P2.
