### ISSUE TITLE
Miss a '/' at the end of the DFS Endpoint for one SAS attached ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#4265]
**Storage Explorer Version**: 1.19.0-dev
**Build Number**: 20210326.4
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Previous release(1.18.1)

## Steps to Reproduce ##

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Select one blob container -> Attach it via SAS.
3. Click the SAS attached blob container -> Observe its DFS Endpoint on its Properties panel.
4. Check there is a '/' at the end of the DFS Endpoint.

## Expected Experience ##
The DFS Endpoint shows well.
![image](https://user-images.githubusercontent.com/54055206/112603751-618b9e80-8e50-11eb-8ad6-c774429433a4.png)

## Actual Experience ##
Miss a '/' at the end of the DFS Endpoint.
![image](https://user-images.githubusercontent.com/54055206/112603927-9566c400-8e50-11eb-83a1-deaf2f6cb012.png)

## Additional Context ##

1. This issue reproduces for one SAS attached ADLS Gen2 directory. 
2. This issue reproduces for one public connected ADLS Gen2 blob container.
3. This issue reproduces for one Azure AD attached ADLS Gen2 blob container and directory. 
4. This issue also reproduces for one blob container under name & key attached ADLS Gen2 account.

**Comment by JasonYeMSFT** [comment]
The trailing slash shouldn't affect any feature. We have been storing and accepting service endpoints with/without the trailing slash. So won't fix.
