### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by CameronKancans** [microsoft/AzureStorageExplorer#4267]
Connecting using SAS URI link, after adding it to file share, it gives me this error. I am using the latest Storage Explorer version.
----------------------
Unable to retrieve child resources.

Details:
Network timeout error: connect ECONNREFUSED 127.0.0.1:10002

**Comment by MRayermannMSFT** [comment]
@CameronKancans that URL is for a local emulator. Or in other words, an emulator running on the machine you are using.
- Have you started the emulator?
- Why are you using a SAS URI to connect to an emulator?

**Comment by CameronKancans** [comment]
Hi Matthew, 
Where can I start the emulator from? I am using my corporate account and our subscription to AZURE, to access the Azure Storage Explorer. We have always used SAS URI keys to access data shared on the file share.

Today I noticed, that my subscription seems missing. Maybe thats the reason. I have blanked out my company name and email.
![zure](https://user-images.githubusercontent.com/81437835/112879453-262ee100-9097-11eb-9936-e6344555b1e2.png)

**Comment by asf139** [comment]
Have the same error since last update. Could not connect to local emulator with my user anymore, but it works with local admin account.

**Comment by MRayermannMSFT** [comment]
@CameronKancans for more information on using/what is a storage emulator please see here: https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite

With regards to no subscription being visible:
1. Are you signed into the right account?
2. Can you see the subscription in the Azure Portal?

@asf139 
1. When you say "normal user" and "local admin account" are you talking about like accounts on your computer?
2. Are you actually starting the emulator when you try to use it? It is possible VS is launching your emulator for you? Storage Explorer does not start your emulator for you.

**Comment by CameronKancans** [comment]
Hi,

This issue got resolved. Thank you, Matthew, for the help.

Kind Regards,
Edgars Kancans
Professional Services Consultant
