### ISSUE TITLE
Invalid 'Set Public Access Level' action for premium blob container

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#427]
**Storage Explorer Version**: 1.3.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180711.4
**Commit**: 47039639
**Regression From**: previous release 1.2.0(20180605.1)

#### Steps to Reproduce: ####
1. Go to Subscription -> Storage Accounts.
2. Right click one premium blob container -> Check the context menu.

#### Expected Experience: ####
There is no 'Set Public Access Level' for the premium blob container.

#### Actual Experience: ####
An extra 'Set Public Access Level' dispalys on the context menu.
![extra](https://user-images.githubusercontent.com/34729022/42684353-5306909e-867f-11e8-93c6-61faa352ebf5.png)

**Comment by craxal** [comment]
Please explain why this is not expected.

**Comment by v-xuanzh** [comment]
The log message says that the request is not support after updating the public access level for one premium blob container. So we think the action 'Set Public Access Level' is extra.
![not support](https://user-images.githubusercontent.com/34729022/42744259-958f71be-88ba-11e8-99d8-15d83c71b891.png)

**Comment by v-xuanzh** [comment]
Hi @craxal ,This issue doesn't reproduce for an existing premium blob container.
But it still reproduces for one new creted premium blob container. So re-open this issue.

**Comment by craxal** [comment]
Merged some fixes.

**Comment by v-xuanzh** [comment]
Hi @craxal @MRayermannMSFT , The invalid action 'Set Public Access Level' shows on the context menu of the premium blob container which is added to Quick Access. So re-opened this issue. 
![accesslevel](https://user-images.githubusercontent.com/34729022/43451335-39b85270-94a4-11e8-9c83-3a9927d9243c.png)

**Comment by craxal** [comment]
Merged some more fixes. 😄
