### ISSUE TITLE
The tab doesn't temporarily open when clicking one ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#4270]
**Storage Explorer Version:** 1.19.0-dev
**Build Number:** 20210326.10
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Previous release(1.18.1)

## Steps to Reproduce ##

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Select one blob container (no opened tabs in the explorer).
3. Click the blob container -> Check whether the tab temporarily opens.

## Expected Experience ##
The tab temporarily opens.
![image](https://user-images.githubusercontent.com/54055206/112817542-2342e900-90b5-11eb-9537-f9598b7f61d6.png)

## Actual Experience ##
The tab doesn't temporarily open.
![image](https://user-images.githubusercontent.com/54055206/112817560-29d16080-90b5-11eb-96b2-1bfab6970fb2.png)

## Additional Context ##
This issue doesn't reproduce for one regular blob container.

**Comment by v-xianya** [comment]
Verified on build main/20210330.6. Fixed.
