### ISSUE TITLE
Downloads are stuck in "queued transfer"

### ISSUE THREAD

**Issue by lovettchris** [microsoft/AzureStorageExplorer#4272]
**Storage Explorer Version**: 1.18.1
**Build Number**: 20210304.5
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  N/A

## Bug Description ##
Downloads appear to be stuck like this for days:
![image](https://user-images.githubusercontent.com/18707114/112880935-f32d2300-907f-11eb-9311-1d18f88c0446.png)

## Steps to Reproduce ##
1. open a blob container from a Azure StorageV2 (general purpose v2) account.
2. select a file in the container and click "Download"

## Expected Experience ##
Downloads should start at some point.  Or they should provide a cancel button so I can get rid of them and unblock this log jam.

## Actual Experience ##
They appear to be stuck forever.  I can provide my machine for debugging this.  

## Additional Context ##
you can email me, my email address is first letter of first name + last name at microsoft.

**Comment by JasonYeMSFT** [comment]
This may happen when the first AzCopy job crashed in a way that we cannot handle (e.g. local OS blocking the executable). If you can reproduce this issue after restarting Storage Explorer, could you try starting Storage Explorer from the terminal and see if there is any error in the console that might be relevant?

We also track canceling queued AzCopy job here #1306.

**Comment by lovettchris** [comment]
Hmmm, weird, well after restarting storageexplorer.exe from console window so I can see the log output the problem no longer reproduces...  But if it happens again I'll try this trick again to grab some logs.  So I closed this for now as "no repro".  THanks.
