### ISSUE TITLE
Does the Azure Storage Explorer using Key 1 as default when creating service SAS with stored access policy?

### ISSUE THREAD

**Issue by Shanon666** [microsoft/AzureStorageExplorer#4274]
**Storage Explorer Version**: 1.12.0 (or versions previous of 1.18)
**Platform/OS**: Windows 10
**Architecture**: x64

## Bug Description ##
Is the Key 1 was used by default  to create the service SAS with stored access policy in Version 1.12.0 (or versions previous of 1.18)
Note: per the release description of 1.18.0 and 1.18.1  , it mentioned "When generating shared access signatures for blobs and blob containers you can now choose which account key to use. #1659"

## Steps to Reproduce ##
1. go to a certain container -->Manage  Access Policies --> add a new access policy
2. get SAS --> select a access policy --> create

## Expected Experience ##
None

## Actual Experience ##
None

## Additional Context ##
None

**Comment by JasonYeMSFT** [comment]
Yes, key 1 used to be the only key that we use for creating SAS.

**Comment by JasonYeMSFT** [comment]
@Shanon666 Did you have any issue with generating SAS due to the key selection?

**Comment by MRayermannMSFT** [comment]
@Shanon666 we're going to go ahead and close this since we've answered your question. If you have a feature request or something else related to this, please open a new issue.
