### ISSUE TITLE
Scroll bar

### ISSUE THREAD

**Issue by g7cnp** [microsoft/AzureStorageExplorer#4276]
**Storage Explorer Version**: 1.18.1
**Build Number**: 20210304.5
**Platform/OS**: win 10
**Architecture**: x64
**Regression From**:  

## Bug Description ##
When running in a maximized window, running a query with output that exceeds what can be displayed on the screen, no vertical scrollbar appears, works fine if the app isn't maximised.

## Steps to Reproduce ##
Maximise the app
Execute a Query that results in more output rows than can be displayed.

## Expected Experience ##
Scroll bar needs to appear.

**Comment by JasonYeMSFT** [comment]
Do you mean Table query or CosmosDB query?

**Comment by g7cnp** [comment]
Sorry, Table

Regards

    Huw Weatherhead


________________________________

**Comment by JasonYeMSFT** [comment]
I wasn't able to reproduce it by executing query. After executing the query, the editor adjust its size and show the scroll bar. However, I do see that when opening the query builder, the editor doesn't adjust its size so the bottom status bar and the scroll bar aren't displayed correctly. Does that match what you saw?

**Comment by MRayermannMSFT** [comment]
@g7cnp please try to share a screenshot if possible.

**Comment by g7cnp** [comment]
Yes that's correct

Regards

    Huw Weatherhead


________________________________

**Comment by MRayermannMSFT** [comment]
@g7cnp you'll need to open this issue in your browser to attach a screenshot:
![image](https://user-images.githubusercontent.com/21112697/115284858-0d4ba580-a102-11eb-8c23-21e38e8db27d.png)

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. If you still run into this issue, please open a new one instead.
