### ISSUE TITLE
This request is not authorized to perform this operation - Randomly appears

### ISSUE THREAD

**Issue by AizazAlam2000** [microsoft/AzureStorageExplorer#4277]
We have a working set of credentials for various of our azure file system environments. However from time to time azure storage explorer starts to throw these errors randomly: 

![image](https://user-images.githubusercontent.com/60495380/113029523-863a8b80-915a-11eb-8108-ae5bb9afd7d6.png)

Sometimes after restarting the program many times it works ok. 
I can provide more information if required.

**Comment by JasonYeMSFT** [comment]
There seems to be something wrong on the server side. We send almost identical requests to the service so they should consistently work/fail. Let's see if this keeps happening.

**Comment by markcovert007** [comment]
I get the same error consistently...


![image](https://user-images.githubusercontent.com/57302767/114736642-40fa8a00-9d14-11eb-91ff-33bd1ee9fe39.png)

**Comment by AizazAlam2000** [comment]
@JasonYeMSFT my team mates are seeing this consistently as well.

**Comment by MRayermannMSFT** [comment]
@AizazAlam2000 @markcovert007 can y'all share the full error message? Also, your best bet for getting this solved might be to just up an Azure support ticket.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are continue to encounter this problem and would still like help.
