### ISSUE TITLE
Delete is failing randomly due to authorization access issue

### ISSUE THREAD

**Issue by Kreestyan** [microsoft/AzureStorageExplorer#4279]
**Storage Explorer Version**: 1.18.1 
**Build Number**: 20210304.5 
**Platform/OS**: Windows 10 
**Architecture**: x64 
**Regression From**:  yes 

## Bug Description ##

Delete is failing randomly

## Steps to Reproduce ##

Select one or more files/folder and attempt to delete them

## Expected Experience ##

Resource is successfully deleted and removed

## Actual Experience ##

Failed with following error:
```
{
	"message": "\"failed to perform remove command due to error: cannot start job due to error: cannot list files due to reason -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.1-0.20201022074806-8d8fc11be726/azblob/zc_storage_error.go:42\\n===== RESPONSE ERROR (ServiceCode=AuthorizationFailure) =====\\nDescription=This request is not authorized to perform this operation.\\nRequestId:24e02f26-501e-0046-3734-26fce5000000\\nTime:2021-03-31T13:48:09.9603956Z, Details: \\n   Code: AuthorizationFailure\\n   GET https://vpntazne.blob.core.windows.net/$web?comp=list&delimiter=%2F&include=metadata&prefix=stage.20210330.1%2F&restype=container&se=2021-04-30t13%3A48%3A07z&sig=-REDACTED-&sp=rdl&sr=c&sv=2020-04-08&timeout=901\\n   User-Agent: [Microsoft Azure Storage Explorer, 1.18.1, win32, azcopy-node, 2.0.0, win32,  AzCopy/10.8.0 Azure-Storage/0.10 (go1.13; Windows_NT)]\\n   X-Ms-Client-Request-Id: [bfe74326-c5f6-4984-6d36-21a240858eed]\\n   X-Ms-Version: [2019-12-12]\\n   --------------------------------------------------------------------------------\\n   RESPONSE Status: 403 This request is not authorized to perform this operation.\\n   Content-Length: [246]\\n   Content-Type: [application/xml]\\n   Date: [Wed, 31 Mar 2021 13:48:09 GMT]\\n   Server: [Microsoft-HTTPAPI/2.0]\\n   X-Ms-Client-Request-Id: [bfe74326-c5f6-4984-6d36-21a240858eed]\\n   X-Ms-Error-Code: [AuthorizationFailure]\\n   X-Ms-Request-Id: [24e02f26-501e-0046-3734-26fce5000000]\\n\\n\\n.\\n\""
}
```
## Additional Context ##

The authorization access issue does not make sense because simply trying again without closing, or refreshing the page may work (or not). It seems to be totally random

**Comment by JasonYeMSFT** [comment]
There might be something wrong on the service side. We are sending almost exactly the same command to AzCopy and it should work consistently.

**Comment by Kreestyan** [comment]
I figured it out. The storage resource had Network filtering to accept incoming request only from known network and it was missing some IP ranges which were the ones used by our host pipeline agent. Since all the possible IP ranges have been added in the Network filtering property, then I have not seen again that issue.
