### ISSUE TITLE
Add the 'Resource/Account name' label on 'Connection Summary' dialog when attaching one account with SAS

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#428]
**Storage Explorer Version**: 1.3.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180711.4
**Commit**: 47039639
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Go to Subscription -> Storage Accounts.
2. Right clik one account -> Select 'Get Shared Access Signature ...' -> 'Create' -> Paste the created connection string to 'Attach with Connection String' dialog -> Next.
3. Check the labels on the 'Connection Summary' dialog.

#### Expected Experience: ####
'Resource/Account name' displays on the dialog.

#### Actual Experience: ####
No 'Resource/Account name' label dispalys on the dialog.
![resourcename](https://user-images.githubusercontent.com/34729022/42684291-2933ddda-867f-11e8-9faa-2ea8a2313927.png)

**Comment by craxal** [comment]
Can you please share the connection string you are using to connect?

Generally, the name of the resource is neither needed or obtainable from an account SAS connection string. All you need is the SAS and some endpoints. All in all, this is expected behavior.
