### ISSUE TITLE
There are inconsistent titles of the SAS URL field on the 'Shared Access Signature' and 'Enter Connection Info' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4280]
**Storage Explorer Version**: 1.19.0-dev
**Build Number**: 20210401.2
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Select one blob container then right click it.
2. Click 'Get Shared Access Signature...' -> Click the 'Create' button on the 'Shared Access Signature' dialog.
3. Observe the title of the SAS URL field on the dialog.
4. Open the connect dialog -> Select 'Blob container -> Shared access signature URL (SAS)' -> Click the 'Next' button.
5. Observe the title of the SAS URL field on the 'Enter Connection Info' dialog.
6. Check whether the two titles are consistent.

## Expected Experience ##
Show a consistent 'SAS URL'.

## Actual Experience ##
Show inconsistent titles.
1. Show 'URI' on the 'Shared Access Signature' dialog.
2. Show 'SAS URL' on the 'Enter Connection Info' dialog.
![image](https://user-images.githubusercontent.com/41351993/113237200-025add80-92d9-11eb-904d-41a39f8d5e69.png)
![image](https://user-images.githubusercontent.com/41351993/113237218-0981eb80-92d9-11eb-8f68-d47514d273f1.png)

## Additional Context ##
This issue also reproduces for one file share/table/queue.

**Comment by JasonYeMSFT** [comment]
We will change to URL.

**Comment by v-xianya** [comment]
@JasonYeMSFT Show 'URI' in the tooltip of the 'Copy' button
![image](https://user-images.githubusercontent.com/41351993/113654009-83dfb080-96c9-11eb-8e4c-56631ee3e73d.png)

**Comment by JasonYeMSFT** [comment]
I have updated that one and the strings in the connect dialog to say "URL" instead of "URI".
