### ISSUE TITLE
The 'Pick an account' dialog pops up again after re-authenticating an account with the 'Integrated Sign-in' option

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#4281]
**Storage Explorer Version**: 1.19.0-dev
**Build Number**: 20210401.2
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##

1. Open Storage Explorer -> Sign in an azure account.
2. Expire the account -> Select 'Integrated sign-in' option in the Settings.
3. Click 'Reauthenticate now...' for the expired account -> The 'Sign in' and 'Pick an account' dialog pop up.
4. Select the account -> Type its password then signing with your phone.
5. Check no dialog pops up after successful phone verification.

## Expected Experience ##
 No dialog pops up.

## Actual Experience ##
The 'Pick an account' dialog pops up again.
![sign](https://user-images.githubusercontent.com/54055206/113267537-0bfc3980-9309-11eb-803f-59e5b8e01133.gif)

## Additional Context ##

1. Wait a minute. The 'Sign In' dialog disappears and the subscriptions succeed to expand under the account. But the 'Pick an account' dialog still displays.  
2. Close the 'Pick an account' dialog. An error shows in the activity log. (the subscriptions succeed to expand under the account)
![image](https://user-images.githubusercontent.com/54055206/113273380-2a653380-930f-11eb-92f7-b4ac555a12fa.png)

**Comment by MRayermannMSFT** [comment]
@v-limu can you describe how you are doing the "Expire the account" step? Also, when you add the account are you using integrated sign-in, or something else?

**Comment by v-limu** [comment]
Hi @MRayermannMSFT 
This is our expiration method at the moment:
Sign in an account in yesterday -> Install and launch Storage Explorer in today -> The account is expired. 
We add the account that is the integrated sign-in option. Details please see the above record.

**Comment by MRayermannMSFT** [comment]
If you click on the "Error details...." what do you see?

**Comment by v-limu** [comment]
Hi @MRayermannMSFT The 'Error details...' for one expired account shows below:
![image](https://user-images.githubusercontent.com/54055206/113646080-aa4a1f80-96ba-11eb-98fe-c488fce61992.png)

**Comment by MRayermannMSFT** [comment]
@v-limu I've now been able to repro this 2 times. When it repros for me I have to do the following only **twice**:

1. enter password
2. perform MFA (approve something on my phone, get a code from a text or email, etc.)

Is it also only **twice** for you?

**Comment by v-limu** [comment]
Hi @MRayermannMSFT Yes. It is also twice for me.😀

**Comment by MRayermannMSFT** [comment]
@v-limu I'll try to test this tomorrow once my account expires again, but does the **twice** thing still happen if you are using system browser? It's ok if you can't get that tested today. I know you have to wait for the token to expire.

**Comment by v-limu** [comment]
Hi @MRayermannMSFT  I can get the expired accounts today.😀
Verify on build/20210409.4. The twice thing still reproduces when using the 'Integrated Sign-in' option. **And the twice thing doesn't reproduce when using system browser.**

**Comment by MRayermannMSFT** [comment]
Identified as a bug in the identity service. Will take a fix from them in 1.20.

**Comment by MRayermannMSFT** [comment]
So I think we now have received a fix from the identity team on this. @v-limu can you see if you can are still able to repro this?

**Comment by v-xianya** [comment]
@MRayermannMSFT Verified this issue on the build 20210809.3. Reproduce. so we are going to reopen this issue.

**Comment by MRayermannMSFT** [comment]
Talked to identity team...need to take yet another version....

**Comment by MRayermannMSFT** [comment]
Ok, merged new version, and self verified as well.  

@v-xianya now you try!

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20210816.1.Fixed.
