### ISSUE TITLE
Make deletion of container a little more strict than just hitting the "yes/no" button by also asking for the container name, similar to the portal experience

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#4282]
This was requested by CSS for a customer. 

- Improve container delete operation:
	Not just `Yes or No`
	Please `Type the name` like delete resource group on the Portal.

It's a part of the support trackingID#2103310060003973

**Comment by JasonYeMSFT** [comment]
Let's discuss this with Portal so we can have a consistent design of the experience.

**Comment by MRayermannMSFT** [comment]
We're deciding not to do this in order to keep experiences consistent between us and portal.
