### ISSUE TITLE
Sign-in with certificate is impossible on Mac OS

### ISSUE THREAD

**Issue by lamaks** [microsoft/AzureStorageExplorer#4283]
Version: 1.18.1
AzCopy Version: 10.8.0
Platform: macOS
Architecture: x64 
Build Number: 20210304.5 
Commit: 212714a38 
Support ID: 0722d21e-29d3-1f95-7e4f-51edeca247fa 

Mac OS Big Sur
11.2.3 (20D91)

## Bug Description ##
When adding new Azure subscription account during sign in the certificate selection popup window never appears. Sign in with certificate is impossible because no certificate selection dialog is presented by the app.

Compare with [Azure Batch Explorer](https://azure.github.io/BatchExplorer/) The Batch explorer app presents certificate selection dialog and sign in with certificate is **possible**.

## Steps to Reproduce ##
1. Select **Manage Accounts**
2. Select **Add an account...**
3. Select **Subscription**
4. Select **Azure**
5. Enter email account that required certificate to sign in
6. Select **Sign in using a certificate**
7. Observer **An error occurred** message

## Expected Experience ##
When **Sign in using a certificate** option is selected the pop up window with list of available certificates should appear. After selecting a certificate and input correct security card pin sign in should succeed

## Actual Experience ##
Window with list of available certificates never appears. Sign in with certificate is impossible

**Comment by JasonYeMSFT** [comment]
@lamaks 

Can you try going to Settings (gear icon on the left) -> Application -> Sign In -> check the checkbox for Microsoft Authentication Library, restart, and try signing in. You should be asked to sign in with your browser. Let us know if that works.

**Comment by MRayermannMSFT** [comment]
@lamaks yes you will need to enable MSAL for this right now. Starting with our next release though, MSAL will be enabled by default.

**Comment by lamaks** [comment]
Sign in with web browser in version 1.19.0 works
