### ISSUE TITLE
AuthenticationErrorDetail:  Signature did not match

### ISSUE THREAD

**Issue by ericjoppru** [microsoft/AzureStorageExplorer#4290]
**Storage Explorer Version**: 1.18.1
**Build Number**: 20210304.5
**Platform/OS**: macOS Catalina
**Architecture**: x64
**Regression From**:  Not sure on this one - it's worked in the past.   Previous to resetting my password

## Bug Description ##
I use MS Azure Explorer for moving/copying large amounts of data between subscriptions, storage accounts, and folders.  It's very fast and has worked great in the past.  However, I'm not getting this error when using the UI to copy data from one location to another.  This occurs even if the data is in the same storage account (moving into a 'test' folder):

"
Description=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
  
AuthenticationErrorDetail: Signature did not match. String to sign used was rl
"

I've this application on an employer-owned laptop (MacBook Pro) and needed to reset my password last week.  When I launched MS Azure Storage Explorer this week, I needed to Remove my existing account and re-add the account to make the change occur, and it now shows all of my subscriptions (Account Management and Explorer views).

## Steps to Reproduce ##
Select a directory from the Explorer view for an existing folder within a container and storage account I've access to.  Select 'Copy'.  Navigate to a separate folder (could be any storage account of or container I've access to) and then select 'Paste'

Error log shows in the Activities window at the bottom right of screen.

## Expected Experience ##
I followed this process for many months on a near-daily basis without issue for copying/moving files.

## Actual Experience ##
Errors are thrown related to the locations of the copy/paste with the primary errors (as I see them) being:  

Description=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
  
AuthenticationErrorDetail: Signature did not match. String to sign used was rl

## Additional Context ##
If it's helpful to have the full error message, please let me know.  It may be proprietary, so I'll have to comb through it first.  Also, I started receiving this error about 30-40 days ago.  I wasn't using the tool as often, so I could work around the copy/move issues.  Then two weeks ago, I was recreating it for a tech group (to see if they had any ideas) and it just started working again.  Strange.  But with my need to change my password last week, I'm wondering if I'm back to the same issue.  

So my process for updating the change here was to Remove my existing account.  And then add it back, following the guidelines to copy a provided code into a browser window.  Occasionally, I would also get a verification sent to my Authenticator app that includes both my work laptop for the VPN and this account for me to verify.

**Comment by ericjoppru** [comment]
After logging into MS Azure Explorer this morning, I've been able to move files without this error occurring.  I haven't made any changes to my side.  So I'm good to go, but if anyone has an idea why this could occur (and a way I can prevent this in the future!) that would be great.  thanks!

**Comment by fcavaco** [comment]
am having the same issue...

  "parsedHeaders": {
      "requestId": "5910a30a-801e-0075-63f9-2a182a000000",
      "errorCode": "AuthenticationFailed",
      "content-length": "512",
      "content-type": "application/xml",
      "date": "Tue, 06 Apr 2021 15:30:12 GMT",
      "server": "Microsoft-HTTPAPI/2.0"
    }
  },
  "details": {
    "requestId": "5910a30a-801e-0075-63f9-2a182a000000",
    "errorCode": "AuthenticationFailed",
    "content-length": "512",
    "content-type": "application/xml",
    "date": "Tue, 06 Apr 2021 15:30:12 GMT",
    "server": "Microsoft-HTTPAPI/2.0",
    "message": "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:5910a30a-801e-0075-63f9-2a182a000000\nTime:2021-04-06T15:30:12.5127439Z",
    "code": "AuthenticationFailed",
    "AuthenticationErrorDetail": "Signature did not match. String to sign used was {REDACTED}"
  }
}

**Comment by JasonYeMSFT** [comment]
@ericjoppru I am pretty sure that the issue was due to the storage account key for your storage account is rotated so the generated SAS from the old key is no longer valid. We cannot refresh keys for container level nodes in Quick Access or local attachments, but we do that for storage accounts under subscriptions.

@fcavaco If you are getting the SAS from a container in Quick Access or local attachment. Try re-adding the node from the subscription -> storage account -> container or re-attach it with the latest key/SAS.

**Comment by ericjoppru** [comment]
Thank you for the detailed feedback, JasonYeMSFT!  It's very helpful in debugging this issue in the future.
