### ISSUE TITLE
This request is not authorized to perform this operation.

### ISSUE THREAD

**Issue by gatoyperro** [microsoft/AzureStorageExplorer#4294]
I am trying to access our blob storage but can't go through. Please see attached screenshot. Thank You!

<img width="618" alt="not authorized" src="https://user-images.githubusercontent.com/82087071/113838506-6857d100-97c1-11eb-8b84-d735ff7e7ed3.PNG">

**Comment by JasonYeMSFT** [comment]
The screenshot is for Azutre Portal owned by another team. Give you also see a similar error in Storage Explorer #4293, it is possible your account isn't given the correct permission to access the resource. Let's track the issue in the other thread.
