### ISSUE TITLE
Unable to connect to subscription after login changed by ad sync

### ISSUE THREAD

**Issue by metag** [microsoft/AzureStorageExplorer#4296]
**Storage Explorer Version**: 1.18.1
**Build Number**: 20210304.5
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  Don't know

## Bug Description ##
I was able to connect to my azure account using my company login first.last@company.com. About a week back we had to sync my on-prem AD account and my Azure account using Azure AD Connect. after the sync, my login becomes flast@company.com. first.last@company.com is now just my primary email address. I can sign in pretty much everything except Azure Storage Explorer.
 
## Steps to Reproduce ##
Add an account then choose add a subscription
Enter my account credential flast@phesi.com

## Expected Experience ##
sign in and connect to subscription

## Actual Experience ##
prompted again to pick an account. if I choose from the account I just signed in, I got asked for credentials again. This keeps going on forever.

If I attempt to connect to the subscription that I connected using first.last@company.com before, I would get:
{
  "message": "\"User 'flast@company.com' returned by service does not match user 'first.last@company.com' in the request\""
}

## Additional Context ##
login is changed after ad sync. due to conflicts, a hard match has to be done. during the process, the immutable id of my azure account was changed.

**Comment by JasonYeMSFT** [comment]
It might be relevant to a UPN change on your account. Could you try following the steps here? https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#reauthentication-loop-or-upn-change

**Comment by metag** [comment]
Thank you! This fixed the reauthentication loop for me.
