### ISSUE TITLE
No default blob container name shows in the 'Clone' dialog for one local emulator blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4298]
**Storage Explorer Version**: 1.19.0-dev
**Build Number**: 20210408.5
**Branch**: main
**Platform/OS**: Windows 10
**Emulator Version**: Azurite 3.11.0/ Microsoft Azure Storage Emulator 5.10.0.0
**Architecture**: ia32
**Regression From**: Previous release (1.18.1)

## Steps to Reproduce ##
1. Install and run Azurite 3.11.0 -> Launch Storage Explorer.
2.  Expand 'Local & Attached -> Storage Accounts -> (Emulator - Default Ports) (Key)'.
3.  Right click the 'Blob Containers' node -> Create a new blob container.
4.  Right click the blob container -> Click 'Clone...'.
5. Check whether the default blob container name shows in the dialog.

## Expected Experience ##
The default blob container name shows.

![image](https://user-images.githubusercontent.com/41351993/114008315-b5f13e00-9894-11eb-9f69-81023f91dcb6.png)

## Actual Experience ##
No default blob container name shows.
![image](https://user-images.githubusercontent.com/41351993/114008306-b25db700-9894-11eb-90b0-7f666cdc6798.png)
## Additional Context ##
The error message keeps showing after typing one valid blob container name.
![image](https://user-images.githubusercontent.com/41351993/114008377-c1dd0000-9894-11eb-8c6b-f41b4a53fd74.png)

**Comment by v-limu** [comment]
Verified on build 20210409.4. This issue has been fixed. So we close it.
