### ISSUE TITLE
Fail to upload blobs to one SAS attached blob container with full permissions after disabling 'Optimize block size (requires write permissions)'

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#4299]
**Storage Explorer Version**: 1.19.0-dev
**Build Number**: 20210408.5
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Right click it -> Click 'Manage Access Policies…' -> Click 'Add' then select permissions 'Read, Add, Create, Write, Delete, List' -> Click 'Save'.
3. Use the access policy to create a SAS URL for the blob container -> Attach the SAS URL.
4. Open the attached blob container -> Upload one blob with 1KB size.
5. The 'Storage Access Policy Detected' dialog pops up -> Uncheck the 'Optimize block size (requires write permissions)' -> Click 'OK'.
6. Check whether succeed to upload the blob.

## Expected Experience ##
Succeed to upload the blob.

## Actual Experience ##
Fail to upload the blob.
![image](https://user-images.githubusercontent.com/54055206/114008517-e802a000-9894-11eb-81d8-06aa0cd224a8.png)
AzCopy Log File: [6e8a36b8-d354-d748-6373-1726d35b2442.log](https://github.com/microsoft/AzureStorageExplorer/files/6277798/6e8a36b8-d354-d748-6373-1726d35b2442.log)

## Additional Context ##

1. This issue also reproduces when pasting one blob.
2. This issue doesn't reproduce for one file share.

**Comment by MRayermannMSFT** [comment]
Hey @v-limu, similar questions for you that I had in my email:

- What size file were you using?
- Can you share the AzCopy log file?
- If you deleted the files that were there after refresh, and tried again, does it ever work?
- Can you keep trying this with files in smaller sizes, decrementing by like 5MB, are you able to get this to work?

**Comment by v-limu** [comment]
Hi @MRayermannMSFT 
1. The uploaded block blob size is 1KB size.
2. AzCopy Log File (the failed uploaded block blob): [6e8a36b8-d354-d748-6373-1726d35b2442.log](https://github.com/microsoft/AzureStorageExplorer/files/6282857/6e8a36b8-d354-d748-6373-1726d35b2442.log)
3. No blob shows in the editor after manually refreshing. Still shows a failed activity log after clicking 'Retry' to enable overwrite for the blob.
4. Fail to upload one block/append blob with 0B size. the result is the same as below.
5. Succeed to upload one page blob with 0B size.

Details please see the below '**Steps to Reproduce**'.😄
