### ISSUE TITLE
An extra 'File Shares' node displays for one attached emulator

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#431]
**Storage Explorer Version**: 1.3.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180711.4
**Commit**: 47039639
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Go to Subscription -> Storage Accounts.
2. Make sure the Storage Emulator is started -> Select 'Attach to a local emulator' -> Input a valid name -> Connect ->Expand the attached emulator.

#### Expected Experience: ####
No  'File Shares' node dispalys under the emulator.

#### Actual Experience: ####
An extra 'File Shares' node dispalys for the attached emulator. And pops up the below error after expanding 'File Shares' node.
![error](https://user-images.githubusercontent.com/34729022/42688131-a9cc8eaa-868a-11e8-9f81-9dc321bae34b.png)

**Comment by craxal** [comment]
How was this connection created? What are the service endpoints?
