### ISSUE TITLE
Key shortcut for the filter panel

### ISSUE THREAD

**Issue by ptd-cloud-admin** [microsoft/AzureStorageExplorer#4310]
I know many people who tried to search inside the blob container and thought they couldn't. 

Maybe the button is not very intuitive at the moment.

I had to search on google to find the option.

Anyway, it would help search faster is there was a key shortcut to open the Filter Panel.

I suggest CTRL + F since it's a known shortcut for searching inside many application.

I would have probably found the filter option by myself if the key shortcut opened it the first time I tried to search.

Thanks in advance

**Comment by JasonYeMSFT** [comment]
I have already added a ctrl/cmd+F shortcut for the filter panel. In a blob container explorer, ctrl/cmd+F will try to open the side panel and try to focus the search box.
