### ISSUE TITLE
Quick Access does not exist

### ISSUE THREAD

**Issue by JeffGoldner** [Microsoft/AzureStorageExplorer#432]
**Storage Explorer Version**: 1.3.0 and 1.3.1
**Platform/OS Version**: Windows 10/Windows Server 2016
**Architecture**: ia32
**Regression From**: unknown

#### Steps to Reproduce: ####
1. Quick access is not available for any items. 
2. No Add to Quick Access, only a blank Quick Access in the tree view

#### Expected Experience: ####
I expect to be able to pin _something_ to Quick Access

#### Actual Experience: ####
No outcome. Can't add anything to quick access. Tried on multiple systems.

**Comment by craxal** [comment]
That's odd. I'm running 1.3.1, and I see the menu options where they should be. Can you share any screenshots? Do any errors appear in the F12 console window?

**Comment by craxal** [comment]
Ah, I see. Local & Attached items can't as of yet be pinned to Quick Access. However, we're fixing this for the next version!
