### ISSUE TITLE
Azure Storage Explorer

### ISSUE THREAD

**Issue by tatekantaro** [microsoft/AzureStorageExplorer#4322]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:  

## Additional Context ##

Azure Storage Explorerにて、アクセス層が「ホット(推定)」となるドキュメントはIOSアプリ上で更新できていないと思われます。（ホット）にするには、どのような操作が必要なのでしょうか？

他に必要な説明がありましたら、状況を伝えますので、どなたか教えていただけますでしょうか。

**Comment by MRayermannMSFT** [comment]
Hi @tatekantaro, we do not read Japanese, so we put your issue into Google translate. This is what we are working with:

> In Azure Storage Explorer, it seems that the document whose access layer is "hot (estimated)" has not been updated on the IOS app. What kind of operation is required to make it (hot)?
> 
> If you have any other necessary explanations, I will tell you the situation, so could anyone please tell me?

When you say "hot" are you talking about the access tier of a blob? If yes, then it can take some time for the access tier of a blob to update, especially depending on what the previous tier of the blob was. For example, if a blob was archived, it can take a very long time for that to move to hot.

When you say iOS, are you trying to say that you are using sort of app on your phone? What app is it?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are continue to encounter this problem and would still like help.
