### ISSUE TITLE
On Windows, Select the Downloads folder by default

### ISSUE THREAD

**Issue by shaunm-msft** [microsoft/AzureStorageExplorer#4324]
When I download a file on Windows, I get a dialog box that asks me to select a folder. But there isn't one select. And Downloads is a special folder. It's easy to navigate to the folder, but not easy to navigate to the parent in order to select it. So I have to type the path c:\users\me\Downloads. Can we have the Downloads folder selected by default on Windows?

**Comment by MRayermannMSFT** [comment]
@shaunm-msft what folder are you seeing and what are you downloading (blobs, files, disks, or gen1 files)? By default we open your downloads folder.

`This PC > Downloads` is the same as `This PC > Windows (C:) > Users > YourName > Downloads`

![image](https://user-images.githubusercontent.com/21112697/115282539-2d2d9a00-a0ff-11eb-99a1-aaad952a5c54.png)

**Comment by shaunm-msft** [comment]
When I start up Storage Explorer today, the Downloads folder is selected. And if I select the Downloads folder in the Quick Access section, it selects. In both cases, I can click the Select Folder button. That wasn't the behavior when I logged the issue. So this issue seems resolved now.

**Comment by MRayermannMSFT** [comment]
@shaunm-msft it's possible that you ran into our behavior of "remembering last selected folder". For the duration of a session, we keep track of what folder you last used when selecting a save location. And then the next time you do something like that, we use that same location by default. 

Anyways, I'm going to close this as no repro for now. Feel free to open another issue if you are able to find something wrong in the future. Thanks.
