### ISSUE TITLE
Streamline sign-in

### ISSUE THREAD

**Issue by shaunm-msft** [microsoft/AzureStorageExplorer#4325]
When I start Storage Explorer, it prompts me to sign in. Since I have an organization sign-in this is several clicks. Then there is the screen to select subscriptions where I have to click Apply.

1. On Windows can we sign in as current user? That's a single click.
2. Only show the "select subscriptions" once. I can always click on something to select more subscriptions later. I don't need go through that list every time I start Storage Explorer.

**Comment by MRayermannMSFT** [comment]
Hi @shaunm-msft 

> On Windows can we sign in as current user? That's a single click.

In the latest version of Storage Explorer (1.19.0 and greater), depending on your browser/if you've signed into it before, you should see this option.

> Only show the "select subscriptions" once. I can always click on something to select more subscriptions later. I don't need go through that list every time I start Storage Explorer.

I think you might be encountering an issue we just discovered and are fixing in our hotfix release. :)

**Comment by MRayermannMSFT** [comment]
Talked offline with @shaunm-msft regarding this issue. 1.19.0 addresses his two points. He may open some new issue/s regarding auto-expansion of nodes in the tree though.
