### ISSUE TITLE
No border shows on the 'Search by prefix(case-sensitive)' box when the box is focused

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4328]
**Storage Explorer Version**: 1.19.0
**Build Number**: 20210414.2
**Branch**: rel/1.19.0
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Previous release (1.18.1)

## Steps to Reproduce ##
1.  Expand one non-ADLS Gen2 storage account -> Blob Containers.
2.  Create a blob container -> Press 'Ctrl+F' to open the filter panel after the blob container is opened.
3.  Check whether a border shows on the 'Search by prefix (case-sensitive)' box.

## Expected Experience ##
A border shows.
![image](https://user-images.githubusercontent.com/41351993/114667428-0acc0300-9d32-11eb-8972-a2f9ba59e842.png)

## Actual Experience ##
No border shows.
![image](https://user-images.githubusercontent.com/41351993/114667204-c6406780-9d31-11eb-8e38-bf9d95f8134a.png)

**Comment by v-limu** [comment]
Verified on build 20210428.4. This issue has been fixed. So we close it.
