### ISSUE TITLE
The strings 'Prefix' and 'Tag' show incompletely on the filter panel when opened using Ctrl+F

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4329]
**Storage Explorer Version**: 1.19.0
**Build Number**: 20210414.2
**Branch**: rel/1.19.0
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Regression From**: Previous release (1.18.1)

## Steps to Reproduce ##
1.  Expand one non-ADLS Gen2 storage account -> Blob Containers.
2.  Create a blob container -> Press 'Ctrl+F' to open the filter panel after the blob container is opened.
3.  Check whether the strings 'Prefix' and 'Tag' show well.

## Expected Experience ##
The strings 'Prefix' and 'Tag' show well.
![image](https://user-images.githubusercontent.com/41351993/114671039-3a7d0a00-9d36-11eb-9522-46191bc0467f.png)
## Actual Experience ##
The strings 'Prefix' and 'Tag' show incompletely.
![image](https://user-images.githubusercontent.com/41351993/114671214-6ac4a880-9d36-11eb-8690-d45517b13e5a.png)

## Additional Context ##
1. This issue doesn't reproduce on Mac.
2. This issue doesn't reproduce after clicking 'Reset Zoom'.

**Comment by JasonYeMSFT** [comment]
I merged a mitigation for this issue. Now the side panel will have a scroll bar when the browser focus causes the element to take more space.

**Comment by v-limu** [comment]
Verified on build main/20210428.4. There is a scroll bar in the side panel. So we close it.
![image](https://user-images.githubusercontent.com/54055206/116354292-0d583f00-a7ad-11eb-8922-33e338568521.png)
