### ISSUE TITLE
Cannot sign in on MAC nor Windows 10 VM

### ISSUE THREAD

**Issue by ksun91** [microsoft/AzureStorageExplorer#433]
**Storage Explorer Version**: 1.3.0
**Platform/OS Version**: MacOS High Sierra Version 10.13.6 / Windows 10 VM 
**Architecture**: ?
**Regression From**: This is my first time using Microsoft Azure Storage Explorer for my company (a new tool used/developed by my company) and my first time getting this error.

#### Steps to Reproduce: ####
1. After opening Microsoft Azure Storage Explorer, click on the person icon on the left tool bar.
2. Click on "Add an account..."
3. Click on the radio button "Add an Azure Account", and the Azure Environment is "Azure". Click "Sign-in"
4. Sign in to my Microsoft Azure account "username@mycompany.com" 
5.My company's logo pops up and I need to sign in with my organization account and my organization's password
6. Got the error saying "Subscriptions could not be loaded. Please try reentering credentials or removing and readding the account."
7. When I click on more information I get the following error message: 

Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: 36da45f1-dd2c-4d1f-af13-5abe46b99921, Error: {"code":"SELF_SIGNED_CERT_IN_CHAIN"}

#### Expected Experience: ####
I expect to be signed into my account

#### Actual Experience: ####
I can't sign in due since my "subscription cannot be loaded" and get the following error: 

Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: 36da45f1-dd2c-4d1f-af13-5abe46b99921, Error: {"code":"SELF_SIGNED_CERT_IN_CHAIN"}

I also clicked on Edit -> SSL Certificates -> View imported Certificates / I see that there is nothing in my "certs" folder.

**Comment by craxal** [comment]
Based on the error message, it sounds like your company is using custom certificates for network communications. You need to import these certificates into Storage Explorer from the **Edit** > **SSL Certificates** > **Import Certificates** menu option. If you don't know where these certificates are stored, an IT expert at your company should know. Note that the certificate needs to be in a file, not in the registry or credentials manager.

One way to test if this will work is to run Storage Explorer from the command line with a special flag:

```bash
./StorageExplorer.exe --ignore-certificate-errors
```

Keep in mind this is not secure, and therefore not recommended you run Storage Explorer for long periods with this option.

See our [Troubleshooting Guide](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?toc=%2fazure%2fstorage%2ffiles%2ftoc.json) for more info.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you're still having problems.
