### ISSUE TITLE
Unable to rename a file in Storage Explorer

### ISSUE THREAD

**Issue by PramodCoke** [microsoft/AzureStorageExplorer#4335]
**Storage Explorer Version**:1.81.1
**Build Number**: 20210304.5
**Platform/OS**: Windows
**Architecture**: ia32
**Regression From**:  

## Bug Description ##
Unable to rename File name in Storage Explorer

## Steps to Reproduce ##
Copy file and paste the file 
Try Renaming the filename 

## Expected Experience ##
Allow user to rename file

## Actual Experience ##
Getting error as below:
{
  "name": "RestError",
  "message": "The source path for a rename operation does not exist.\nRequestId:5c22a17e-c01f-0094-4d51-318bf6000000\nTime:2021-04-14T17:17:03.3987874Z",
  "stack": "RestError: The source path for a rename operation does not exist.\nRequestId:5c22a17e-c01f-0094-4d51-318bf6000000\nTime:2021-04-14T17:17:03.3987874Z\n    at new RestError (Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:2359:28)\n    at handleErrorResponse (Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:3242:17)\n    at \\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:3178:18\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
  "code": "SourcePathNotFound",
  "statusCode": 404,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "***************************************?mode=legacy",
    "method": "PUT",
    "headers": {
      "_headersMap": {
        "x-ms-rename-source": {
          "name": "x-ms-rename-source",
          "value": "******* "
        },
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2020-04-08"
        },
        "user-agent": {
          "name": "user-agent",
          "value": "Microsoft Azure Storage Explorer, 1.18.1, win32 azsdk-js-storagedatalake/12.3.1 (NODE-VERSION v12.13.0; Windows_NT 10.0.17763)"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "186bbb88-29cc-4b47-b0cb-6b881ad576b2"
        },
        "x-ms-date": {
          "name": "x-ms-date",
          "value": "Wed, 14 Apr 2021 17:17:02 GMT"
        },
        "authorization": {
          "name": "Authorization",
          "value": ""
        },
        "content-type": {
          "name": "Content-Type",
          "value": ""
        },
        "cookie": {
          "name": "Cookie",
          "value": ""
        }
      }
    },

**Comment by MRayermannMSFT** [comment]
@PramodCoke a couple of questions:

- Can you share the URL of the thing you were trying to rename?
- Does the thing you were trying to rename still exist at the time/after you clicked "ok" after inputting the new name?
- How are you connected to this container? Did you sign in and go into a subscription? Or did you attach, and if so, how did you attach (SAS, key, Azure AD)?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are continue to encounter this problem and would still like help.
