### ISSUE TITLE
Cannot sign in on Ubuntu 1804

### ISSUE THREAD

**Issue by ehotinger** [microsoft/AzureStorageExplorer#434]
**Storage Explorer Version**: 1.3.1
**Platform/OS Version**: Linux Ubuntu 18.04
**Architecture**: x64

#### Steps to Reproduce: ####
1. ./StorageExplorer
2. Add an account, sign in
3. Enter password; 2FA phone auth
4. Multi-factor auth is successful; "waiting for authentication" exits as if it's successful
5. No account information appears in the side bar

#### Expected Experience: ####
Subscriptions to be loaded in the side bar after successful MFA.

PS: Tried running with sudo, deleting the config cache, ignoring cert errors, etc. Not sure what else there is to do from the TSG.

**Comment by craxal** [comment]
We haven't moved support up to 18.04 just yet, so we don't have any guarantees that everything should work.

That said, do you get any error messages in the F12 console window? If you launch Storage Explorer from the command line, do you get any error messages from the output?

**Comment by craxal** [comment]
Tell me more about your network/environment. Are you running in a Docker container? Working behind a proxy? Using alternate certificates?

**Comment by ehotinger** [comment]
None of the above. Just MSFT corpnet. Anywho, I think this is a gnome-keyring issue. Tried reinstalling it completely to no avail for now.

**Comment by NjengaSaruni** [comment]
Hi ehotinger, I am having the exact same issue. Did you perhaps find a solution, or workaround?

**Comment by rnsc** [comment]
Hello, I have the exact same issue on Linux Mint 19 (Ubuntu 18.04).
The login windows stays on after entering my password to "Waiting for authentication" and nothing happens.
At first, it was asking for my credentials every time but I could just continue use the app.
Then I decided to follow the troubleshooting guide and deleted the cache and identity folder and now I cannot log in anymore. (it was working on Linux Mint 18.3 (Ubuntu 16.04)).
Nothing in the debug console.

**Comment by pviotti** [comment]
**Storage Explorer Version**: 1.4.2 (installed from [this AUR](https://aur.archlinux.org/packages/storageexplorer/))
**Platform/OS Version**: Arch Linux (current)
**Architecture**: x64

Same steps to reproduce, same outcome.

```bash
$ gnome-keyring version
gnome-keyring: 3.28.2
```
I get this error upon startup:
```javascript
Debug.js:39 Unexpected end of JSON input
error @ Debug.js:39
```

**Comment by rnsc** [comment]
It's still an issue with 1.4.2 release on Ubuntu 18.04 for me.

**Comment by rnsc** [comment]
> See #600 for possible workaround.

It is highly unpractical when dealing with more than a couple storage accounts :(

**Comment by craxal** [comment]
@rnsc, not really sure what you're referring to. If you look a little further in the conversation, @oh54 suggests running the following on the command line:

```bash
sudo apt install libgnome-keyring-common libgnome-keyring-dev
```
https://superuser.com/questions/1233459/error-running-gitkraken-even-though-dependencies-installed/1255172

Again, please keep in mind that we do not officially support Linux 18.* as of yet.

**Comment by rnsc** [comment]
Hey @craxal, those packages are installed on my system and still, it doesn't work.
I'm willing to help if you need more info.

**Comment by fontmaniac** [comment]
I observe the same issue with the latest release of Azure Storage Explorer (1.6.1) on the following platforms:
- ArchLabs (Arch Linux with Openbox WM) - with latest Dotnet Core (2.2.101) from AUR;
- Debian 9 - clean install with only Dotnet Core 2.2.101, Azure CLI and ASE;
- Mint 18.3 xfce (based on Ubuntu 16.04) - clean install with only Dotnet Core 2.2.101, Azure CLI and ASE;
ASE works fine for me on Windows 7 and on Windows 10.

**Comment by jinglouMSFT** [comment]
Could you please make sure you have the following dependencies installed?  Quoted from the Troubleshooting guide:

For Linux distros other than Ubuntu 16.04, you may need to manually install some dependencies. In general, the following packages are required:

.NET Core 2.x
libsecret
libgconf-2-4
Up-to-date GCC

Depending on your distro, there may be other packages you need to install. The Storage Explorer Release Notes contain specific steps for some distros.

**Comment by rnsc** [comment]
Hello @jinglouMSFT 

Here are the deps I have installed on U 18.04:

`Package: aspnetcore-runtime-2.1
Status: install ok installed
Priority: standard
Section: devel
Installed-Size: 70803
Maintainer: Microsoft <nugetaspnet@microsoft.com>
Architecture: amd64
Version: 2.1.6-1`

`Package: libgconf2-4
Status: install ok installed
Priority: optional
Section: oldlibs
Installed-Size: 364
Maintainer: Ubuntu Desktop Team <ubuntu-desktop@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: same
Source: gconf
Version: 3.2.6-4ubuntu1`

`Package: libsecret-1-0
Status: install ok installed
Priority: optional
Section: libs
Installed-Size: 347
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: same
Source: libsecret
Version: 0.18.6-1`

`Package: gcc
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 50
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Source: gcc-defaults (1.176ubuntu2.1)
Version: 4:7.3.0-3ubuntu2.1`

And still, it doesn't work.

**Comment by diegodgs** [comment]
I have the same issue here. all deps are installed. I get the following output on terminal

Received message 'get-dialog-result'
Received message 'dialog-ready'
Received message 'dialog-execute-operation'
Received message 'did-execute-operation'
Received message 'dialog-execute-operation'
Received message 'did-execute-operation'
Received message 'dialog-execute-operation'
Received message 'did-execute-operation'
Received message 'dialog-execute-operation'
Received message 'did-execute-operation'
Received message 'dialog-execute-operation'
Received message 'did-execute-operation'
Received message 'dialog-execute-operation'
Received message 'did-execute-operation'
Received message 'dialog-did-init'
Received message 'dialog-execute-operation'
Received message 'did-execute-operation'
Received message 'dialog-execute-operation'
Received message 'did-execute-operation'
Received message 'dialog-execute-operation'
Received message 'did-execute-operation'
Received message 'dialog-execute-operation'
Received message 'did-execute-operation'
Received message 'did-get-dialog-result'
Received message 'closed'

**Comment by craxal** [comment]
@rnsc, it says you have ASP.NET Core installed. That's not the same as .NET Core.

**Comment by shikharsg** [comment]
Am running in to same issue: asks me to sign in, then "Waiting for Authentication", then that screen disappears and no account details appear in the explorer. Here is a screenshot of the console error:

![storageexplorerloginerror](https://user-images.githubusercontent.com/8643775/55148864-fa439280-5140-11e9-8a6b-028c5f68e80c.png)

**Comment by jinglouMSFT** [comment]
@shikharsg Could you please try the workaround outlined in #1142?  Thanks.

**Comment by shikharsg** [comment]
@jinglouMSFT, thank you for that link, it works now

**Comment by MRayermannMSFT** [comment]
Been a while since this issue had any comments.

With regards to Ubuntu 18 support here's where we stand:
- we now have a storage explorer snap, it is the recommended way of installing storage explorer on linux, please use it!
- we still have the .tar.gz, but you need to install the dependencies manually

If anyone is still having ubuntu 18 problems, please open a new issue. Thanks!
