### ISSUE TITLE
It would be better to update 'Select all' to 'Select All' on the 'Reset Storage Explorer' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4341]
**Storage Explorer Version**: 1.19.0
**Build Number**: 20210416.2
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Open Storage Explorer -> Click the menu 'Help' -> Click 'Reset'.
3. Check whether show 'Select All' on the 'Reset Storage Explorer' dialog.

## Expected Experience ##
Show 'Select All'.

## Actual Experience ##
Show 'Select all'.
![image](https://user-images.githubusercontent.com/41351993/115002195-0725b100-9ed7-11eb-9c61-354136d687f5.png)

**Comment by MRayermannMSFT** [comment]
Double check if this is supposed to lowercase or uppercase.
