### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Kikemestan** [microsoft/AzureStorageExplorer#4345]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:  

## Additional Context ##

{"name":"Error","message":"getaddrinfo ENOTFOUND emestanza.file.core.cloudapi.de","stack":"Error: getaddrinfo ENOTFOUND emestanza.file.core.cloudapi.de\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26)","errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"emestanza.file.core.cloudapi.de"}

**Comment by MRayermannMSFT** [comment]
@Kikemestan, are you behind a proxy? If yes you need to setup your proxy settings: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#proxy-issues
