### ISSUE TITLE
Miss a reminder when selecting an access policy in one blob's 'Shared Access Signature' dialog under one name & key attached account

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#4349]
**Storage Explorer Version**: 1.19.1
**Build Number**: 20210417.6
**Branch**: hotfix/1.19.1
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Previous release(1.17.0)

## Steps to Reproduce ##
1. Select one storage account -> Attach it via name & key.
2. Expand the attached storage account -> Open one blob container.
3. Right click one blob -> Click 'Get Shared Access Signature…'.
4. Select one saved access policy -> Check whether a reminder shows in the dialog.

## Expected Experience ##
A reminder shows.
![image](https://user-images.githubusercontent.com/54055206/115209703-6f230400-a130-11eb-9b9f-d62df466ccc2.png)

## Actual Experience ##
Miss a reminder.
![image](https://user-images.githubusercontent.com/54055206/115209227-fde35100-a12f-11eb-9e60-095431e2f04e.png)

## Additional Context ##

1. This issue also reproduces for one ADLS Gen2 blob/folder.
2. This issue also reproduces for one file under one file share.
3. There is no 'Signing key' in the 'Shared Access Signature' dialog.

**Comment by JasonYeMSFT** [comment]
Merged a fix for blobs. We didn't have the warning for file share so I defer adding that if I have time at the end of this release cycle.

**Comment by v-limu** [comment]
Verified on build main/20210430.3. This is has been fixed for blobs.

**Comment by JasonYeMSFT** [comment]
The waring for file share is added back as well.

**Comment by v-xianya** [comment]
Verified on the latest build 20210701.7. Fixed.
