### ISSUE TITLE
The error message is incorrect for one Azure AD attached queue after removing its associated account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4350]
**Storage Explorer Version**: 1.19.1
**Build Number**: 20210417.6
**Branch**: hotfix/1.19.1
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Select one queue -> Give a RBAC role to it then assign to one account.
1. Sign in with the account -> Attach the queue via Azure AD.
2. Remove the account.
3. The Azure AD attached queue got broken -> Right click the broken queue -> Click 'View Error...'.
4. Check whether the error message is correct.

## Expected Experience ##
The error message is correct.

The screenshot of the error message for one broken blob container.
![image](https://user-images.githubusercontent.com/41351993/115212672-5405c380-a133-11eb-8ad1-25c0fe58e6b5.png)

## Actual Experience ##
The error message is incorrect.
![image](https://user-images.githubusercontent.com/41351993/115212680-5700b400-a133-11eb-8df5-c034a60747b8.png)

**Comment by MRayermannMSFT** [comment]
Merged into main, but opening a new issue to track something I noticed: https://github.com/microsoft/AzureStorageExplorer/issues/4412
