### ISSUE TITLE
No tooltip 'invalid' shows when hovering over the icon of the error message 'Please enter a valid filter key' on the filter panel

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4352]
**Storage Explorer Version**: 1.19.1
**Build Number**: 20210417.6
**Branch**: hotfix/1.19.1
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one non-ADLS Gen2 storage account.
2. Right click the 'Blob Containers' node -> Create one new blob container.
3. Open its filter panel -> Select the option 'Tag Filters'.
4. Delete the default filter key -> There is an error message.
5. Hover over the icon of the error message.
6. Check whether there is a tooltip.

## Expected Experience ##
There is a tooltip 'invalid'.

![image](https://user-images.githubusercontent.com/41351993/115217831-777f3d00-a138-11eb-9c11-cb0b765fc37e.png)

## Actual Experience ##
There is no tooltip.

![image](https://user-images.githubusercontent.com/41351993/115217531-2ff8b100-a138-11eb-9661-76661664d55b.png)

**Comment by JasonYeMSFT** [comment]
We have decided to not show tooltips for icons/images.
