### ISSUE TITLE
An Azure AD attached resource does not auto display broken after removing its associated account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4354]
**Storage Explorer Version**: 1.19.1
**Build Number**: 20210417.6
**Branch**: hotfix/1.19.1
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Previous release (1.18.1)

## Steps to Reproduce ##
1. Select one queue -> Give a RBAC role to it then assign to one account.
2. Sign in with the account -> Attach the queue via Azure AD.
3. Go to 'ACCOUNT MANAGEMENT' panel -> Remove the account.
4. Click 'Open Explorer' -> Check whether the Azure AD attached queue shows broken.

## Expected Experience ##
The queue shows broken.

## Actual Experience ##
1. The queue does not show broken.
2. The queue shows broken after manually refreshing.
![image](https://user-images.githubusercontent.com/41351993/115223338-44d84300-a13e-11eb-9865-00b3ccf7a8f5.png)

## Additional Context ##
1. This issue also reproduces for Azure AD attached blob containers.
2. The broken Azure AD attached resources do not auto fix after sign-in back the removed account.

**Comment by MRayermannMSFT** [comment]
The "Blob Containers" and "Queues" nodes under "Attached Containers" should now refresh after leaving the account panel (every time).
