### ISSUE TITLE
Can't expand the 'Blob Containers' node which contains Azure AD attached blob container when its associated account is expired

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4357]
**Storage Explorer Version**: 1.19.1
**Build Number**: 20210420.1
**Branch**: hotfix/1.19.1
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Previous build (20210417.6)

## Steps to Reproduce ##
1. Select one blob container -> Give a RBAC role to it then assign to one account.
2. Sign in with the account -> Attach the blob container via Azure AD.
3. Expire the account -> Click 'Open Explorer'.
4. Go to 'Local & Attached' -> 'Storage Accounts' -> 'Attached Containers'.
5. Expand 'Blob Containers' node -> Check whether the node can be expanded.

## Expected Experience ##
The node can be expanded.

## Actual Experience ##
1. The node can't be expanded.
2. The info bar pops up.
3. Switch to 'ACCOUNT MANAGEMENT' panel.
![issue0420](https://user-images.githubusercontent.com/41351993/115330115-06866680-a1c6-11eb-8f83-6ceadba044e2.gif)
## Additional Context ##
1. This issue also reproduces when attaching one blob container.
2. This issue doesn't reproduce for File Share/ Queue/ Table.

**Comment by MRayermannMSFT** [comment]
@v-xianya how did you expire the account?
