### ISSUE TITLE
getting error when ASDL V2 is refreshed in storage explorer.

### ISSUE THREAD

**Issue by bkatra** [microsoft/AzureStorageExplorer#4358]
Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://scminbounddl.blob.core.windows.net/?include=metadata&comp=list failed, reason: unable to get local issuer certificate",
  "stack": "FetchError: request to https://scminbounddl.blob.core.windows.net/?include=metadata&comp=list failed, reason: unable to get local issuer certificate\n    at ClientRequest.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1461:11)\n    at ClientRequest.emit (events.js:310:20)\n    at TLSSocket.socketErrorListener (_http_client.js:426:9)\n    at TLSSocket.emit (events.js:310:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)",
  "type": "system",
  "errno": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY",
  "code": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"
}

**Comment by MRayermannMSFT** [comment]
Please see the troubleshooting guide https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#error-self-signed-certificate-in-certificate-chain-and-similar-errors
