### ISSUE TITLE
There is no visible 'X' button next to one tag filter item under the 'High Contrast - Black' theme

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4359]
**Storage Explorer Version**: 1.19.1
**Build Number**: 20210420.1
**Branch**: hotfix/1.19.1
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Open Storage Explorer -> Apply the theme 'High Contrast - Black'.
2. Expand one non-ADLS Gen2 storage account -> Blob Containers.
3. Select one blob container then open it -> Open its filter panel.
4. Select 'Tag Filters' -> Check whether there is a visible 'X' button next to one tag filter item.

## Expected Experience ##
There is a visible 'X' button.
![image](https://user-images.githubusercontent.com/41351993/115347046-85d66300-a1e3-11eb-96e2-c0af4aa9e985.png)

## Actual Experience ##
There is no visible 'X' button.
![image](https://user-images.githubusercontent.com/41351993/115347085-8d960780-a1e3-11eb-8731-c59054af68c4.png)

## Additional Context ##
1. This issue doesn't reproduce under the 'Light (default)/Dark' theme.
2. This issue also reproduces under the 'High Contrast - White' theme.
 ![image](https://user-images.githubusercontent.com/41351993/115347062-8969ea00-a1e3-11eb-9a41-865b9fe28016.png)

**Comment by v-xianya** [comment]
@JasonYeMSFT 
For the Operator part, Is there supposed to have a border?

![image](https://user-images.githubusercontent.com/41351993/116019797-9a00e100-a677-11eb-917e-4b3e9a675576.png)

**Comment by v-limu** [comment]
Verified on build 20210428.4. This issue has been fixed. So we close it.
