### ISSUE TITLE
Version 1.3.1 - Unable To Retrieve Child Resources

### ISSUE THREAD

**Issue by sahgilbert** [Microsoft/AzureStorageExplorer#436]
**Storage Explorer Version**: Version 1.3.1
**Platform/OS Version**: Microsoft Windows 8.1
**Architecture**: ia32
**Regression From**: Version 1.0.0

#### Steps to Reproduce: ####
1. Launch Azure Storage Explorer.
2. Navigate to (Local and Attached) -> Storage Accounts -> (Development) -> Tables

#### Expected Experience: ####
For the local development tables to be loaded and shown, thus allowing me to browse them.

#### Actual Experience: ####
Receive an error stating that the application was
<img width="883" alt="screenshot 2018-07-15 20 42 53" src="https://user-images.githubusercontent.com/13452745/42737743-12066766-8870-11e8-8941-7c76212b0140.png">

#### Additional Things To Note: ####
I've reverted to Version 1.0.0, and this now works again.
However, it appears to have deleted all my local tables and data, including the blobs.

**Comment by craxal** [comment]
Did you actually start the emulator before expanding any nodes?

Older versions of Storage Explorer will try to automatically start Azure Storage Emulator for you, but we're moving away from that in favor of supporting multiple emulators.

**Comment by sahgilbert** [comment]
@craxal All I did was launch the application like I always have done, and got the aforementioned result. 

I will try testing Version 1.3.1 by launching the Azure Storage Emulator first.

Thank you.

**Comment by felipedourado** [comment]
Just delete folder %%AppData/Roaming/StorageExplorer

Open again Storage Explorer and will works

hope help you

**Comment by felipedourado** [comment]
Close Storage Explorer

Next delete folder %%AppData/Roaming/StorageExplorer

Open again Storage Explorer and will works!!!

hope help you

**Comment by craxal** [comment]
Haven't heard any buzz here for awhile, so closing this and assuming this has been mitigated.

**Comment by craxal** [comment]
@mavaddat Are you also trying access a running emulator? If so, what emulator and what version? Have you launched the emulator? Can you share any console output from the emulator?

If not, please open a separate issue and provide any application logs you can.
