### ISSUE TITLE
MS Azure Storage Explorer - Required argument table for function getUrl is not defined

### ISSUE THREAD

**Issue by PanLuce** [microsoft/AzureStorageExplorer#4361]
**Storage Explorer Version**: 1.19.0
**Build Number**: 20210414.2
**Platform/OS**: macOS

## Bug Description ##
When I open Azure Table Storage Explorer and navigate to already previously connected local storages (default connection string: AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=http;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;
I receive the message 
"Unable to retrieve child resources.

Details:
Required argument table for function getUrl is not defined"

## Steps to Reproduce ##
1) start Azurite via default Storage Connection String (see above)
2) Open MS Azure Storage Explorer
3) Connect to local storage via default Storage Connection String (see above)
4) Expand Tables -> Error Details message pops up
<img width="521" alt="Screenshot 2021-04-20 at 11 51 32" src="https://user-images.githubusercontent.com/65348936/115376973-764d1f00-a1cf-11eb-8c01-b157e83197dd.png">

## Expected Experience ##
List of Tables should be expanded.

## Actual Experience ##
Error message (see above) is displayed.

**Comment by craxal** [comment]
@PanLuce What version of Azurite are you using? According to their GitHub page, tables aren't supported in Azurite 3, so if you're using that version, you may want to consider downgrading to v2 if you need table support.

**Comment by JasonYeMSFT** [comment]
@PanLuce I have installed Azurite v2.7.1 and tried the repro steps but I cannot reproduce. On my machine, listing tables is successful. Could you check your running Azurite to see if it is reporting any error? Also could you try restarting Azurite to see if it fixes the problem?

**Comment by PanLuce** [comment]
I've managed to fix my table storage by downgrading to earlier version (2.7.0) and back to higher version (2.7.1) and it started working. No idea if this is correct resolution but I cannot reproduce the issue anymore so consider this one as closed. Nevertheless thanks for reaching out to me.
