### ISSUE TITLE
Azure Storage Explorer Listing Tables Fails

### ISSUE THREAD

**Issue by arashsaghafian** [microsoft/AzureStorageExplorer#4364]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.0

### Platform

Windows

### OS Version

Windows 10

### Architecture

x64

### Regression From

1.18.0

### Bug Description

Expanding the Tables under a storage account gives me an error message popup saying "Authenthication failed: Undefined". It works when expanding Blob Containers.

### Steps to Reproduce

1. Launch Storage Explorer
2. Expand Tables

### Actual Experience

When expanding the Tables section the error message appears (screen shot in swedish):

![image](https://user-images.githubusercontent.com/8975964/115514663-9f7bb700-a284-11eb-9e8f-1007cf4d2167.png)

### Expected Experience

Tables being listed

### Additional Context

It seems like this started happening when a new account management was introduced in 1.19.0.

**Comment by MRayermannMSFT** [comment]
@arashsaghafian can you:
1. click on the node for the storage account giving you problems
2. go to "properties" in the bottom left
3. scroll down to they key properties
4. reveal the keys by clicking on the eye icon
5. make sure the keys are there and look ok

Additional questions:
- Are you seeing this for all storage accounts or just some?
- For the affected storage accounts, are they in Azure or in emulators?
- If in Azure, which Azure environment? (public, germany, china, us govt, stack, etc.)

**Comment by arashsaghafian** [comment]
Hi there,

Big thanks for getting back to me.. and sorry for the late reply. In regards to your questions, yes the keys seem allright.

This issue happens to all storage accounts, in different subscriptions and accounts as well. It applies to storage accounts in Azure and not Emulators... it works just fine in Emulators.

I'm using public cloud model with North Europe and West Europe as regions (in different subscriptions).

Cheers,

**Comment by MRayermannMSFT** [comment]
@arashsaghafian 

So to double check, the keys look like real keys?

Do you know if the VNet or firewall settings were recently changed for your storage accounts?

Can you install 1.18 again (https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.18.1) and confirm that this does work on that version still? We're asking because we don't think any changes made for 1.19 could cause an issue like this for tables.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue we recommend:
- opening an Azure support ticket
- opening a new issue here

Thanks.
