### ISSUE TITLE
Feature Request - smart compression on upload with limited bandwidth

### ISSUE THREAD

**Issue by cforbin1** [microsoft/AzureStorageExplorer#4366]
My ISP provides an asymmetric connection, as many other people have.  My upload bandwidth is only a tenth of my download bandwidth.

It would be WONDERFUL if AzureStorageExplorer provided some assistance with this.

The BEST incarnation of this would be to automatically detect upload speeds (and local processor speed), and silently compress the data stream at my end, uncompressing at the Azure end, so it's totally transparent and the compression/transmission is optimized for minimum time to upload.

However, that might be too hard / complicated / consuming of developer time.

A SIMPLER incarnation might be to offer an option where you select file(s) and choose a menu option "optimize upload", and it then:
* Tests your upload speed (briefly)
* Does some quick compression calculations involving the selected files
* Compresses the files into ZIP using the optimal amount of compression to balance the time spent doing that against the time in transmission
* Failing that, at least gives the user the settings to use for an Open Source ZIP or 7z compressor.

**Comment by MRayermannMSFT** [comment]
@cforbin1 we'll pass along this feedback to the service team, but unfortunately the main thing you're asking for ("compress the data stream at my end, uncompressing at the Azure end") is out of our scope. :(

With regards to upload speeds though, it sounds like you should try changing the Network Concurrency setting to "Adjust dynamically":
![image](https://user-images.githubusercontent.com/21112697/115901158-b00f6700-a415-11eb-92ff-64d8a4aaf42b.png)
(Settings, aka, gear on the left toolbar > Transfers > AzCopy > Network Concurrency)

That mode will have AzCopy throttle and test itself more aggressively than normal.

You can also of course compress your files yourself and then upload them. But they will be compressed on the server and need to be decompressed after you download them. There's also a transfer setting for "Decompress Files":
![image](https://user-images.githubusercontent.com/21112697/115901499-201ded00-a416-11eb-869a-9948f86d8e5c.png)

So if you were to compress each of your files to .gz/.gzip/.zz, then on upload they should be given a content-type that indicates their compression. And when you download them, if that setting is enabled, AzCopy will decompress them.

Could you elaborate a bit more on what you mean by this though?
> Failing that, at least gives the user the settings to use for an Open Source ZIP or 7z compressor.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you'd like to give us more information about what you meant by 
> Failing that, at least gives the user the settings to use for an Open Source ZIP or 7z compressor.
Feel free to open a new issue.

If you'd like to talk to the AzCopy team about a better default value for their Network Concurrency setting, we'd recommend going to their GitHub and opening an issue there. Thanks.
