### ISSUE TITLE
Show extended location for Edge Zone

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#4368]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Show extended location for Edge Zone - Request from Azure Edge Zone 

### Desired Solution

For Storage account, managed disk and snapshot, display the extended location information for resources created to Edge Zone (Microsoft/Operator/Enterprise)

### Additional Context

NeedByDate: 9/30/21

**Comment by jinglouMSFT** [comment]
From George - SDK has already added the ability to show extended location to Storage, Compute, Network SDKs of all languages.

**Comment by GeorgeH-MS** [comment]
APIs which contains extended location:
SRP: https://github.com/Azure/azure-rest-api-specs/tree/master/specification/storage/resource-manager/Microsoft.Storage/stable/2021-01-01, sample: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/storage/resource-manager/Microsoft.Storage/stable/2021-01-01/storage.json
CRP (Disk part): https://github.com/Azure/azure-rest-api-specs/tree/master/specification/compute/resource-manager/Microsoft.Compute/stable/2020-09-30, sample: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2020-09-30/disk.json
CRP (VM part): https://github.com/Azure/azure-rest-api-specs/tree/master/specification/compute/resource-manager/Microsoft.Compute/stable/2020-12-01, sample: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2020-12-01/compute.json

**Comment by GeorgeH-MS** [comment]
SDKs support extended location:
SRP:
Python: https://pypi.org/project/azure-mgmt-storage/17.0.0/
.Net: https://www.nuget.org/packages/Microsoft.Azure.Management.Storage/19.0.0
Go: https://github.com/Azure/azure-sdk-for-go/releases/tag/v52.0.0
Java: https://github.com/Azure/azure-sdk-for-java/tree/azure-resourcemanager-storage_2.2.0/sdk/resourcemanager/azure-resourcemanager-storage/
NodeJS: https://www.npmjs.com/package/@azure/arm-storage/v/15.3.0
C++: no management moduel

CRP:
Python: https://pypi.org/project/azure-mgmt-compute/19.0.0/
.Net: https://www.nuget.org/packages/Microsoft.Azure.Management.Compute/44.0.0
Go: https://github.com/Azure/azure-sdk-for-go/releases/tag/v51.2.0
Java: https://github.com/Azure/azure-sdk-for-java/tree/azure-resourcemanager-storage_2.2.0/sdk/resourcemanager/azure-resourcemanager-storage/
NodeJS: https://www.npmjs.com/package/@azure/arm-compute/v/16.0.0
C++: no management module

**Comment by MRayermannMSFT** [comment]
I have reached out to George with some Qs.
