### ISSUE TITLE
'Unable to find the specified location' displays after clicking 'Search From Here' against one new checked subscription

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4370]
**Storage Explorer Version**: 1.19.1
**Build Number**: 20210422.2
**Branch**: hotfix/1.19.1
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Previous release (1.18.1)

## Steps to Reproduce ##
1. Launch Storage Explorer -> Sign in one account -> Select one subscription -> Click 'Open Explorer'.
2. Right click the subscription node -> Click 'Search From Here'.
3. Check whether the subscription node displays.

## Expected Experience ##
The subscription node displays.
![image](https://user-images.githubusercontent.com/41351993/115647018-bb9b5900-a355-11eb-87b5-3daeb9b2973d.png)

## Actual Experience ##
Display 'Unable to find the specified location'.
![image](https://user-images.githubusercontent.com/41351993/115646390-a2de7380-a354-11eb-8229-af61831499ab.png)

## Additional Context ##
This issue also reproduces for the items under the subscription.
![search](https://user-images.githubusercontent.com/41351993/115646919-9575b900-a355-11eb-8fbf-f9a4672cac71.gif)

**Comment by MRayermannMSFT** [comment]
Fixed. @v-xianya as part of verifying this bug, please do additional testing around searching and scoped searching

**Comment by v-xianya** [comment]
@MRayermannMSFT Ok, we will do additional testing around searching and scoped searching.
