### ISSUE TITLE
An extra black bar shows under the dropdown list of the empty 'Custom Environment'

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#4371]
**Storage Explorer Version**: 1.19.1
**Build Number**: 20210422.2
**Branch**: hotfix/1.19.1
**Platform/OS**: Windows 10
**Architecture**: ia32
**Regression From**: Previous release (1.18.1)

## Steps to Reproduce ##

1. Launch Storage Explorer -> Open Connect dialog -> Click 'Subscription -> Custom Environment'.(Make sure there is no custom environment).
2. Click the dropdown list of the 'Custom Environment'.
3. Check there is no extra black bar.

## Expected Experience ##
There is no extra black bar.
![image](https://user-images.githubusercontent.com/54055206/115677905-87d72800-a383-11eb-8b5b-b737a01c8f69.png)

## Actual Experience ##
There is an extra black bar.
![image](https://user-images.githubusercontent.com/54055206/115677841-7aba3900-a383-11eb-973c-2485b9eac886.png)

**Comment by craxal** [comment]
This is probably just what dropdown controls do when they have no options to choose from. We should probably disable the control if that's the case.
