### ISSUE TITLE
Cannot bulk download documents when applying a tag-based filter

### ISSUE THREAD

**Issue by LuckyDavid** [microsoft/AzureStorageExplorer#4372]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.0

### Platform

Windows

### OS Version

Windows 10

### Architecture

x64

### Build Number

20210414.2

### Bug Description

I am accessing a storage account where I have a few blob containers configured. If I go into any of these containers and select multiple blobs I am given the option to download them - this will actually download every single document I previously selected into a folder I have specified in one go - This is great

If I now try and apply a filter (by going into "Show filter panel <" and apply a few tag filters) the query will return OK but when I select more than one blob returned by my query, the download option gets grayed out. I am still able to download them individually one by one, but I was hoping to get a more streamlined experience for the end users.

### Steps to Reproduce

Pre-requisite: 
Some of the blobs need to be created with index tags so that you can use tag filters

1. Launch Storage Explorer
2. Expand blob containers and go into blob container
3. Click on "Show filter panel <" and select Tag Filters
4. add a valid filter that you know will return multiple blobs
5. Select "Apply Filter"
6. Select at least 2 blobs
7. The "download" option will now be grayed out thus not allowing you to download the documents at the same time. This is the bug

### Actual Experience

This was already explained in the previous steps but essentially, once I select multiple blobs that were returned from a filter query using index tags, the download option is grayed out:

### Expected Experience

I expect to be able to multiple blobs at the same time even when I apply a filter before I select them.

**Comment by JasonYeMSFT** [comment]
This is due to our limitation on handling downloads for blobs who don't share a common parent directory. We need to amend our AzCopy command construction logic to support that.

**Comment by jraddemaria** [comment]
Wanted to follow-up on this feature and see if any progress has been made. Although tagging blobs is a great future, from a filtering point it's almost useless if you can't download the blobs in bulk you have isolated. Hoping this get's moved up as a prioirty.

**Comment by richardMSFT** [comment]
Bulk download for tag-based filters has been added and will ship with 1.28.0.
