### ISSUE TITLE
The unchecked subscription under another account shows after running 'Search From Here' for the subscription under one account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4373]
**Storage Explorer Version**: 1.19.1
**Build Number**: 20210423.2
**Branch**: hotfix/1.19.1
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Previous release (1.18.1)

## Steps to Reproduce ##
1. Sign in two Azure accounts (A and B) that have the same subscription (like: '**subscription1**').
2. Check  '**subscription1**' for the two accounts -> Click 'Open Explorer'.
4. Go to 'ACCOUNT MANAGEMENT' panel -> Uncheck '**subscriptioin1**' for account A -> Click 'Open Explorer'.
5. Right click '**subscription1**' -> Click 'Search From Here'.
6. Check whether there is only one '**subscription1**'

## Expected Experience ##
There is only one '**subscription1**'.
![image](https://user-images.githubusercontent.com/41351993/115834288-a3a40200-a447-11eb-9af8-ed163bd722e0.png)

## Actual Experience ##
There are two '**subscription1**'.
![image](https://user-images.githubusercontent.com/41351993/115834053-5b84df80-a447-11eb-9e99-22d670b6c061.png)

**Comment by v-xianya** [comment]
Hi Matthew, 
This issue also reproduces following the below steps:

1. Sign in two Azure accounts that have the same subscription (like: 'subscription1').
2. Check 'subscription1' for the two accounts -> Click 'Open Explorer'.
3. Select one of the **subscription1** -> Right click it -> Click ‘Search From Here’ -> **Observe the focused item** -> Reset the search box.
4. Go to 'ACCOUNT MANAGEMENT' panel -> Uncheck '**subscriptioin1**' for the account **which was focused in Step3** -> Click 'Open Explorer'.
5. Right click existing '**subscription1**' -> Click 'Search From Here'.
6. There are two ‘**subscription1**’ in the tree view.

![issue4373](https://user-images.githubusercontent.com/41351993/115983052-89962b00-a5d1-11eb-87ac-ebfda378d4f7.gif)

**Comment by MRayermannMSFT** [comment]
@v-xianya the behavior you are now seeing (as specified in [this comment](https://github.com/microsoft/AzureStorageExplorer/issues/4373#issuecomment-826266440)), that is **not** a regression? Correct? I tested on 1.18.1 and I see the subscription two times in the tree view, once for each of the Azure accounts which have access to it. Let me know if you see the same thing.

**Comment by v-xianya** [comment]
@MRayermannMSFT It is a regression. I verified on 1.18.1 following the steps in comment. Not reproduce.
![attach](https://user-images.githubusercontent.com/41351993/119286703-90b76400-bc77-11eb-8a4a-79dd7c88079e.gif)

**Comment by MRayermannMSFT** [comment]
@v-xianya ah I misread the instructions! I'll have a fix for this shortly.

**Comment by MRayermannMSFT** [comment]
@v-xianya I've checked in a fix for this. :)
