### ISSUE TITLE
The window popped up when downloading an item auto closes after creating a new destination folder

### ISSUE THREAD

**Issue by v-xinda** [microsoft/AzureStorageExplorer#4378]
**Storage Explorer Version**: 1.19.1
**Build Number**: 20210425.1
**Branch**: hotfix/1.19.1
**Platform/OS**: MacOS Catalina 10.15.7
**Architecture**: x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Open a blob container. 
2. Select one blob -> Click 'Download'.
3. Click 'New Folder' on the popped up Window -> Type a folder name -> Click 'Create'.
4. Check whether the opened window is closed or not.

## Expected Experience ##
The popped up window is not closed.

## Actual Experience ##
The popped up window is closed.

## Additional Context ##
This issue also reproduces for the file share and disk.

**Comment by MRayermannMSFT** [comment]
@v-xinda what version of macOS are you on? You can check by clicking on the Apple icon at the top left, and clicking "About this Mac":
![image](https://user-images.githubusercontent.com/21112697/116126998-26ad9e00-a67c-11eb-86fe-21e8c39ce183.png)

**Comment by MRayermannMSFT** [comment]
@v-xinda @JasonYeMSFT says he can reproduce the same behavior, except, the finder window isn't being closed, it is simply behind storage explorer. Or in other words:

1. click crate
2. finder window vanishes
3. move storage explorer main window out of the way/to the side
4. can see finding window again

**Comment by MRayermannMSFT** [comment]
@v-xinda?

**Comment by v-xianya** [comment]
In addition, we tried to reproduce this issue on MacOS Big Sur Version 11.3.

There is no way to create a new folder on the opened window. Below is the opened window.
![image](https://user-images.githubusercontent.com/41351993/117775995-a1c2a700-b26d-11eb-9e97-34b11c10baaf.png)
The weird thing is  when downloading one blob in Azure Storage Extension, There is 'New Folder' button on the opened window.
![image](https://user-images.githubusercontent.com/41351993/117776294-fbc36c80-b26d-11eb-9b14-579328456334.png)

**Comment by v-xianya** [comment]
@JasonYeMSFT please see the below video.

https://user-images.githubusercontent.com/41351993/117911191-ec94fb00-b30f-11eb-8538-842225d165ef.mov

**Comment by v-xianya** [comment]
@JasonYeMSFT 
Verified this issue with the latest build 20210514.4 on MacOS Catalina 10.15.7 & MacOS Big Sur 11.3 . 
Fixed. so we are going to close it.
