### ISSUE TITLE
Display an unmatched error message after inputting invalid account key on 'Connect with Name and Key' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#438]
**Storage Explorer Version**: 1.3.1
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180714.1
**Commit**: 47039639
**Regression From**: Previous release 1.3.1(20180711.1)

#### Steps to Reproduce: ####
1. Open the Connect dialog then select 'Use a storage account name and key' -> Check the default error message on the 'Connect with Name and Key' dialog.
2. Input an invalid Account key then check the error message.

#### Expected Experience: ####
For step1: No default error message displays.
For step2: Display the matched error message like 'Invalid account key....' after inputting the invalid account key.

#### Actual Experience: ####
Display an unmatched error message after inputting the invalid account key.
![errormessage](https://user-images.githubusercontent.com/34729022/42745811-3a514232-88c4-11e8-9368-b6baefd81584.png)

**Comment by v-xuanzh** [comment]
This issue has been fixed on [feature/rbac_20180914.1](https://devdiv.visualstudio.com/DevDiv/Cloud%20Explorer/_build/results?buildId=2056606&view=results). Could you help to resolve it?

**Comment by craxal** [comment]
We haven't touched any of this code in that feature branch. Please verify against the master branch. If it appears resolved, we'll close the bug.

**Comment by v-xianya** [comment]
Verified on [master\20190411.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2580412), This issue doesn't reproduce. Could you help to resolve it?

**Comment by jinglouMSFT** [comment]
Per Xian, closing.
