### ISSUE TITLE
The values of column properties for a blob which is filtered by tag show blank except the properties 'Name & Status'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4380]
**Storage Explorer Version**: 1.19.1
**Build Number**: 20210425.1
**Branch**: hotfix/1.19.1
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
 1. Expand one non-ADLS Gen2 storage account -> Blob Containers.
 2. Create one blob container -> Upload one blob with a tag1 -> Open the 'Filter Panel'.
 3. Select 'Tag Filters' -> Add the tag1 as a filter -> Click 'Apply Filters'.
 4. Click 'Hide Filter Panel' -> Check whether all values of the column properties show well for the blob.

## Expected Experience ##
All values of the column properties show well for the blob.
![image](https://user-images.githubusercontent.com/41351993/115987827-4e9ff180-a5e9-11eb-8620-c466b182e09e.png)

## Actual Experience ##
1. Only the values of the column properties 'Name' & 'Status' show well.
2. The values of the properties 'Access Tier/Latest Modified/Blob Type/Content Type/Size' show blank.
![image](https://user-images.githubusercontent.com/41351993/115987836-5f506780-a5e9-11eb-884e-02ce4210361a.png)

**More Info:**
1. For one leased blob, its leased icon does not show after applying filters.
2. The actions 'Clone.../Change Access Tier.../Acquire Lease' are disabled.
![image](https://user-images.githubusercontent.com/41351993/115987906-afc7c500-a5e9-11eb-92a2-1b9b09517f8a.png)

**Comment by JasonYeMSFT** [comment]
This is by design due to the service limitation. The filter API doesn't return those properties unlike the list API.
