### ISSUE TITLE
The nonmatched blob doesn't auto disappear after applying a new tag filter

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4381]
**Storage Explorer Version**: 1.19.1
**Build Number**: 20210425.1
**Branch**: hotfix/1.19.1
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one non-ADLS Gen2 storage account -> Blob Containers.
2. Select one blob container -> Upload several blobs.
3. Add different tags for these blobs separately -> Open the 'Filter Panel'.
4. Select 'Tag Filters' -> Input one blob's tag as the filter.
5. Click 'Apply Filters' -> Check the specific blob displays in the editor.
6. Update the filter to another blob's tag -> Click 'Apply Filters'.
7. Check the matched blob displays and the nonmatched blob disappears.

## Expected Experience ##
1. The matched blob displays.
2. The nonmatched blob disappears.

## Actual Experience ##
1. The matched blob displays.
2. The nonmatched blob doesn't disappear.

## Additional Context ##
The nonmatched blob disappear after manually refreshing.

**Comment by v-limu** [comment]
Verified on build main/20210428.4. This issue has been fixed. So we close it.
