### ISSUE TITLE
no connect my suscription

### ISSUE THREAD

**Issue by erickalvarezsamayoa** [microsoft/AzureStorageExplorer#4382]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.0

### Platform

Windows

### OS Version

Windows 10

### Architecture

x64

### Build Number

20210414.2

### Regression From

1.18.0

### Bug Description

This tenant's subscriptions could not be uploaded. You may need to re-authenticate. See the error details for more information.

{
  "message": "\"{\\n  \\\"message\\\": \\\"\\\\\\\"El recurso al que intenta acceder se encuentra en un inquilino que está filtrado. Quite el filtro para acceder al recurso.\\\\\\\"\\\"\\n}\""
}

### Steps to Reproduce

{
  "message": "\"{\\n  \\\"message\\\": \\\"\\\\\\\"El recurso al que intenta acceder se encuentra en un inquilino que está filtrado. Quite el filtro para acceder al recurso.\\\\\\\"\\\"\\n}\""
}

### Actual Experience

not connect

### Expected Experience

d

### Additional Context

```text
d
```

**Comment by MRayermannMSFT** [comment]
@erickalvarezsamayoa can you please try signing out and then signing back in?

**Comment by erickalvarezsamayoa** [comment]
thank you, but if I started session from the outside in the browser and then went back to azure storage, but I didn't upload my subscription, I'd better go back to version 1.18.1

**Comment by MRayermannMSFT** [comment]
@erickalvarezsamayoa if there's an issue with 1.19 we'd prefer to fix it. If you have time to retry 1.19.0, and sign out and then back in, please do so.

**Comment by erickalvarezsamayoa** [comment]
Yes I log in, but it does not connect with my subscription and files

![Captura](https://user-images.githubusercontent.com/83183167/116275801-2925fb80-a741-11eb-968f-5b198ad549ed.JPG)

**Comment by erickalvarezsamayoa** [comment]
Yes I log in, but it does not connect with my subscription and files

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Matthew ***@***.***>
Enviado: martes, 27 de abril de 2021 10:00
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [microsoft/AzureStorageExplorer] no connect my suscription (#4382)


@erickalvarezsamayoa<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ferickalvarezsamayoa&data=04%7C01%7C%7C9b25141062c040ed4f5808d90995896f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637551360120204391%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Q9Dm36ZGN0dl6nObLkTs1jD0mkog36txq7c8S6Md36Y%3D&reserved=0> if there's an issue with 1.19 we'd prefer to fix it. If you have time to retry 1.19.0, and sign out and then back in, please do so.

**Comment by MRayermannMSFT** [comment]
> Yes I log in, but it does not connect with my subscription and files

Can you share a screenshot of what you are seeing? Do you know what tenant (directory) the subscription you want to access is in?

**Comment by erickalvarezsamayoa** [comment]
Directory:  Apliper

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Matthew ***@***.***>
Enviado: martes, 27 de abril de 2021 13:11
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [microsoft/AzureStorageExplorer] no connect my suscription (#4382)


Yes I log in, but it does not connect with my subscription and files

Can you share a screenshot of what you are seeing? Do you know what tenant (directory) the subscription you want to access is in?

**Comment by MRayermannMSFT** [comment]
@erickalvarezsamayoa is the checkbox for that directory checked? If not, then check it. If it is, please try un-checking it, waiting a moment, and then re-checking it. Thanks.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue we recommend:
- opening an Azure support ticket
- opening a new issue here

Thanks.
