### ISSUE TITLE
disable login to Azure Storage Explorer with Azure AD User ID

### ISSUE THREAD

**Issue by yujeny** [microsoft/AzureStorageExplorer#4383]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Anyone who knows the Azure AD User ID/Password can login to Azure through Storage Explorer can remove storage account.

### Desired Solution

There should be the way to disable login to Azure Storage Explorer with Azure AD User ID in Storage Explorer

**Comment by jinglouMSFT** [comment]
Didn't we all agree in the email/IcM that the appropriate solution to the customer issue is to use AAD RBAC permission to limit the ability to delete?  Not allowing users to login in the client app isn't the correct solution.  Even IF we limit the user from logging into Storage Explorer, s/he can still log into other client apps and delete.  So, this is not the correct solution.  Also, the user can't delete storage account from within Storage Explorer, by the way.  The user can only filter what accounts to show in Storage Explore, but not delete from the service.
