### ISSUE TITLE
When the container is removed, there should be confirm message like 'Yes' or 'No'

### ISSUE THREAD

**Issue by yujeny** [microsoft/AzureStorageExplorer#4385]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

When removing storage container, there is no confirm dialog not to make mistake.

### Desired Solution

There should be confirm dialog to assure that this container will be really removed.

**Comment by MRayermannMSFT** [comment]
Hi @yujeny can you confirm what you mean by "remove container"? When I try either:
- detach an attached blob container
- delete a blob container

I get a warning message each time:
![image](https://user-images.githubusercontent.com/21112697/116119771-a3884a00-a673-11eb-9bc3-2ffaeadcfe21.png)
![image](https://user-images.githubusercontent.com/21112697/116119805-adaa4880-a673-11eb-982c-e124a9a024e0.png)

Are you doing something other than these actions?

**Comment by jinglouMSFT** [comment]
This is how the Yes/No dialog looks like on Windows.  When deleting a blob container, we DO show a warning dialog.  Let us know how you repro'ed the problem of not getting a warning.  I believe your original ask in email was to also ask the user to type in the name of the container, which I entered as a feature request in #4282.  

![image](https://user-images.githubusercontent.com/10081483/116124953-ca497f00-a679-11eb-8c07-af9ef4434392.png)
