### ISSUE TITLE
Fail to undelete a soft-deleted blob by date with the correct date range under 'Manage Versions' view

### ISSUE THREAD

**Issue by v-xinda** [microsoft/AzureStorageExplorer#4386]
**Storage Explorer Version**: 1.19.1
**Build Number**: 20210425.1
**Branch**: hotfix/1.19.1
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account then enable soft delete for 'Blob Containers'.
2. Create a new blob container then upload a blob to it.
3. Delete the uploaded blob -> Switch to 'Active and soft deleted blobs'.
4. Right click the deleted blob then select 'Manage History -> Manage Versions'.
5. Right click the deleted blob then select 'Undelete By Date' -> Specify a date range contains the deleted blob.
6. Check whether the deleted blob is undeleted successfully.

## Expected Experience ##
The deleted blob is undeleted successfully.

## Actual Experience ##
The deleted blob is not undeleted with a warning 'The time of deletion is out of range'.
![image](https://user-images.githubusercontent.com/57662131/116048706-0693d400-a6a8-11eb-8e36-71eeaf536562.png)

## Additional Context ##
This issue doesn't reproduce under the current view and 'Manage Snapshot' view.

**Comment by JasonYeMSFT** [comment]
Undeleting snapshot/version is equivalent to undeleting the base, I added some logic to force undelete the blob if a version or snapshot is included.

**Comment by v-limu** [comment]
Verified on build main/20210428.4. This issue has been fixed. So we close it.

**Comment by v-xianya** [comment]
@JasonYeMSFT 
Verified this issue on build main/20210428.4. 

The current behavior as below:
The soft-deleted blob under Snapshots/Versions view can be undeleted by date even if **the time of the deletion is out of range.**

Is this what you mean 'force undelete'?

**Comment by JasonYeMSFT** [comment]
Correct. Basically the date filter will only affect base blobs. Versions and snapshots will be undeleted no matter when they are deleted.
