### ISSUE TITLE
The 'Sign In' dialog doesn't disappear after reauthenticating an account with 'Device Code Flow (Deprecated)'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4387]
**Storage Explorer Version**: 1.19.1
**Build Number**: 20210425.1
**Branch**: hotfix/1.19.1
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Regression From**: Previous release (1.18.1)

## Steps to Reproduce ##

1. Launch Storage Explorer -> Make sure there is an expired account.
2.  Go to 'Settings -> Application -> Sign-in' -> Sign in with 'Device Code Flow (Deprecated)'.
3. Click 'Reauthenticate now...' on the 'ACCOUNT MANAGEMENT' panel.
4. Click 'Copy Code and Open Browser' on the popped up 'Sign In' dialog.
5. Paste the code -> Click 'Next' -> Select the account -> Sign in it.
6. After signed in -> Go to Storage Explorer.
7. Check whether the 'Sign In' dialog disappears.

## Expected Experience ##
The 'Sign In' dialog disappears.

## Actual Experience ##
The 'Sign In' dialog doesn't disappear.
![image](https://user-images.githubusercontent.com/41351993/116051939-bcaced00-a6ab-11eb-9a0b-6cf4af52b80f.png)

## Additional Context  ##
We can't reproduce this issue on Mac, because the accounts signed in Mac do not expire as Windows & Linux do.

**Comment by MRayermannMSFT** [comment]
We're actually going to won't fix this for now. Device code flow is deprecated, and since user can just close the dialog, it's no big deal.
