### ISSUE TITLE
'A property with this name already exists' doesn't disappear when deleting the first added one from the two same names

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#4388]
**Storage Explorer Version**: 1.19.1
**Build Number**: 20210425.1
**Branch**: hotfix/1.19.1
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create a table -> Click 'Add' in its toolbar.
3. Click 'Add Property' in the 'Add Entity' dialog -> Type a name 'test' in its 'Property Name'.
4. Click 'Add Property' again -> Type the name 'test' in its 'Property Name' again. (An error shows for the text box)
5. Delete the first added property -> Check whether the error disappears.

## Expected Experience ##
The error disappears.

## Actual Experience ##
The error doesn't disappear.
![image](https://user-images.githubusercontent.com/54055206/116058343-9730cc80-a634-11eb-8e14-d459722ccdbf.png)

## Additional Context ##
This issue also reproduces in the 'Edit Entity' dialog.

**Comment by MRayermannMSFT** [comment]
Merged into main for 1.20
