### ISSUE TITLE
File explorer has no date/time column

### ISSUE THREAD

**Issue by joesimpk** [microsoft/AzureStorageExplorer#439]
**Storage Explorer Version**: 1.3.0

Where is the date/time column for files?  This would be extremely useful when browsing folders/files.

**Comment by craxal** [comment]
Date/time for what exactly? Are you referring to a Last Modified time?

**Comment by joesimpk** [comment]
Yes

Joseph Simpkins
Virscidian, Inc.
Office: 919-809-7651
M: 919-412-2839
________________________________

**Comment by joesimpk** [comment]
Like you get in FileExplorer in windows so you can sort by date

Joseph Simpkins
Virscidian, Inc.
Office: 919-809-7651
M: 919-412-2839
________________________________

**Comment by danielsjf** [comment]
At the moment, the file shares only support the fields Name and Size. Right clicking on a file shows the LastModified date. Unfortunately this isn't available to filter on, similar to Windows File Explorer (where the filter is called Date modified).

I very frequently miss this feature. Certainly in folders with many files where the paginated view isn't very helpful.

**Comment by nmarler** [comment]
Considering some of the other features that the product supports (e.g., dark mode), it's very surprising that this most basic of file-exploring features is missing. It's not possible to sort by Date Modified?

**Comment by MRayermannMSFT** [comment]
Unfortunately the list API for file shares doesn't return last modified information at this time[1]. We'll continue passing this feedback along to the platform team.

[1]: https://docs.microsoft.com/en-us/rest/api/storageservices/list-directories-and-files

**Comment by JasonYeMSFT** [comment]
It seems like they do now. We can prioritize adding these columns.

**Comment by JasonYeMSFT** [comment]
This will be added in 1.26.0.
