### ISSUE TITLE
Blob containers - Unable to retrieve child resources.

### ISSUE THREAD

**Issue by tomasimenna** [microsoft/AzureStorageExplorer#4392]
Hello,
When I connect to my account and navigate to the blob containers, I get the error query below

------------------------------------------------------
Unable to retrieve child resources.

Details:
{
  "name": "RestError",
  "message": "This request is not authorized to perform this operation.\nRequestId:34129c49-201e-001f-2041-3bf1b3000000\nTime:2021-04-27T08:46:33.2384741Z",
  "stack": "RestError: This request is not authorized to perform this operation.\nRequestId:34129c49-201e-001f-2041-3bf1b3000000\nTime:2021-04-27T08:46:33.2384741Z\n    at new RestError 
[...]
[...]
------------------------------------------------------
It is supposed that I have all the permission to perform such actions, wat could be the problem then?

Thanks

**Comment by MRayermannMSFT** [comment]
@tomasimenna do you know what permissions you have?

- Are you signed in or attached?
- If attached, how are you authenticating the attachment? Name and key, SAS, Azure AD?
- If you are signed in, do you have key access or RBAC permissions for the account?
- If you have RBAC permissions, do you know which roles you have?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue we recommend:
- opening an Azure support ticket
- opening a new issue here

Thanks.
