### ISSUE TITLE
Failed to create database.  Details: "Cannot connect to this CosmosDB account. The account may in create or delete process. Please refresh the accounts list later and try again."

### ISSUE THREAD

**Issue by abhinavrai66** [microsoft/AzureStorageExplorer#4393]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.0

### Platform

macOS

### OS Version

bug sur

### Architecture

i86

### Bug Description

Failed to create database.

Details:
"Cannot connect to this CosmosDB account. The account may in create or delete process. Please refresh the accounts list later and try again."

### Steps to Reproduce

create database

### Actual Experience

Failed to create database.

Details:
"Cannot connect to this CosmosDB account. The account may in create or delete process. Please refresh the accounts list later and try again."

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
