### ISSUE TITLE
Unable to retrieve child resources.

### ISSUE THREAD

**Issue by HannahMayThorpe** [microsoft/AzureStorageExplorer#4394]
Error Details:
["FetchError:request to https://aldprdocc3ts3urs4ggtnw.blob.core.windows.net/?sv=2019-12-12&ss=b&srt=sco&sp=rwlacx&se=2022-01-01T04:59:59Z&st=2020-12-01T05:00:00Z&spr=https&sig=XXXXXXXX&include=metadata&comp=list failed, reason: connect EACCES 20.38.118.132:443"]

Is this a widely known error and any ideas on fix/problem?

**Comment by MRayermannMSFT** [comment]
@HannahMayThorpe can you try doing whatever you were doing again? Perhaps this was a temporary issue? Can you also tell us what you were trying to do before this error came up?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue we recommend:
- opening an Azure support ticket
- opening a new issue here

Thanks.
