### ISSUE TITLE
Display an incorrect error message 'A read permission ('sp=r') is required' when pasting one table's SAS URL without 'Query' permission

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4398]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 20210428.4
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Select one table then right click it -> Click 'Get Shared Access Signature...' -> Create a SAS URL without 'Query' permission.
3. Copy the SAS URL -> Open the connect dialog -> Select 'Table' -> Paste the copied SAS URL to 'Table SAS URL' field.
4. Check whether the error message is correct.

## Expected Experience ##
The error message is correct. [**The SAS has inadequate permissions. A query permission ('sp=r) is required**].

## Actual Experience ##
The error message is incorrect.
![image](https://user-images.githubusercontent.com/41351993/116378220-c7a87000-a7c6-11eb-921f-1da245ea8f7e.png)

**Comment by craxal** [comment]
@v-xianya This is by design. The Query permission is supposed to be an "r" according to the documentation. We should probably change the error message, though, to read "A query permission ('sp=r') is required".

**Comment by v-xianya** [comment]
Updated the expect experience.
