### ISSUE TITLE
Storage Explorer can't handle blob names starting with forward slash

### ISSUE THREAD

**Issue by ckarras** [microsoft/AzureStorageExplorer#440]
**Storage Explorer Version**: 1.3.1
**Platform/OS Version**: Windows 10 Version 1709 (OS Build 16299.431)
**Architecture**: ia32
**Regression From**: Yes (not sure which version I had before upgrading to 1.3.1)

#### Steps to Reproduce: ####
1. Using a tool that allows it (in my case, the NodeJS library for Azure Storage), upload a blob with name 
starting with /, for example "/a/b/c/test.txt"
2. In Azure Storage Explorer, select the storage container where the blob was created
3. Navigate the folder structure:
3.1. Click on folder with blank name (representing the first forward slash)
3.2. Navigate the subfolder structure to reach the last folder (example: click on a, then b, then c)

#### Expected Experience: ####
Azure Storage Explorer should be able to handle any blob name that is valid for Azure Storage, even if it is not valid in local file system (NTFS, etc) conventions.

#### Actual Experience: ####
Once the last folder is reached, Storage Explorer says "No data available in this blob container", even though there are several files with the prefix.

A workaround is to enter the path in the "Search by prefix" field (for example /a/b/c). This will correctly list the files under that path.

**Comment by shizhMSFT** [comment]
This bug is still not resolved in version 1.6.2

**Comment by craxal** [comment]
Does anyone have a sample container they'd be willing to share that has these blob names?

**Comment by thiruma0203** [comment]
@craxal This issue can be reproduced with Azure portal.

1. Navigate to blob container menu on Azure portal.
2. Click on "Upload" button.
3. Expand "Advanced" settings, and put "Upload to folder" part like "/a/b/c" (start with forward slash.)
 Then upload any local files.
4. Navigate this blob container with Azure Storage Explorer, and the issue reproduces.

**Comment by MRayermannMSFT** [comment]
If churn is too big to do this in 1.10, move to 1.12.

**Comment by JasonYeMSFT** [comment]
This issue is being tracked at #1512. Essentially a blob whose name starts with / is considered under a directory with name "".
