### ISSUE TITLE
The 'Next' button becomes disabled after switching from 'Summary' dialog to 'Enter Connection Info' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4400]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 20210428.4
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Previous release (1.19.1)

## Steps to Reproduce ##
1. Select one storage account -> Copy its connection string.
2. Open the connect dialog -> Select 'Storage account or service -> Connection string (Key or SAS)' -> Click 'Next'.
3. Paste the connection string to 'Connection string' filed -> Click 'Next' -> Click 'Back'.
4. Check the 'Next' button is enabled.

## Expected Experience ##
The 'Next' button is enabled.

## Actual Experience ##
The 'Next' button becomes disabled.
![image](https://user-images.githubusercontent.com/41351993/116384763-02ada200-a7cd-11eb-891d-2f145e921948.png)

## Additional Context ##
1. There are red borders for the text fields.
2. This issue also reproduces for Blob Containers/File Shares/Queues/Tables.

**Comment by v-limu** [comment]
Hi @craxal Verified on the lasted build 20210526.1. This issue still reproduces.

**Comment by craxal** [comment]
@v-limu The commit containing the fix for this got lost somehow. Please verify again.

**Comment by v-xianya** [comment]
Hi @craxal Verified this issue on the latest build 20210526.7. Fixed.
