### ISSUE TITLE
TIMEOUT ERROR

### ISSUE THREAD

**Issue by kimhyunchae91** [microsoft/AzureStorageExplorer#4401]
Hello All -
I have received an error message that says that I cannot resolve this by myself.

steps I taken before it went down:
- I moved 1 blob from root folder to another virtual directory within the container
- I deleted an old archived virtual directory called 2021/ from the root folder which deleted about 650k blobs
- I refreshed the container to this error message:
![image](https://user-images.githubusercontent.com/25262401/116433515-6f8d6000-a7fe-11eb-8a47-845907ad90f3.png)

**Comment by MRayermannMSFT** [comment]
@kimhyunchae91 can you try this again? Maybe it was a temporary issue? Alternatively, has your network changed? Are you now behind a proxy? If yes, then you will need to configure proxy settings in the app.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue we recommend:
- opening an Azure support ticket
- opening a new issue here

Thanks.
