### ISSUE TITLE
Can see Azure Storage Account contents in WebApp, but not in Windows Storage Explorer App.  Error: Unable to retrieve child resources. Error Name: FetchError

### ISSUE THREAD

**Issue by thommy-santiago** [microsoft/AzureStorageExplorer#4402]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.0

### Platform

Windows

### OS Version

Windows 10

### Architecture

x64

### Build Number

20210414.2

### Regression From

No

### Bug Description

Setup ADLS Gen2 Storage Account.  I can access containers via the online version of Storage Explorer (preview) in Azure.  However when I use the MS Azure Storage Explorer App in Windows I get "Fetch Error".  I'm able to sign in into Azure account via subscription and can see our Storage Acct, but we can't view contents.

![Azure Online Storage Explorer (preview)](https://user-images.githubusercontent.com/83361287/116437003-95246480-a812-11eb-8dce-687218adefbc.jpg)

![MS Azure Storage Explorer Windows App (error)](https://user-images.githubusercontent.com/83361287/116437049-a1a8bd00-a812-11eb-83ba-c2ebd75022f4.jpg)

### Steps to Reproduce

1. Launch MS Azure Storage Explorer App in Windows
2. Select Subscription and log in to Azure
3. Expand corresponding ADLS Gen2 Storage Account under "Storage Accounts"
4. Expand Blob Containers under Storage Account
5. Get error message

Added screenshots to "Bug Description"

### Actual Experience

Setup ADLS Gen2 Storage Account.  I can access containers via the online version of Storage Explorer (preview) in Azure.  However when I use the MS Azure Storage Explorer App in Windows I get "Fetch Error".  I'm able to sign in into Azure account via subscription and can see our Storage Acct, but we can't view contents.

![Azure Online Storage Explorer (preview)](https://user-images.githubusercontent.com/83361287/116437003-95246480-a812-11eb-8dce-687218adefbc.jpg)

![MS Azure Storage Explorer Windows App (error)](https://user-images.githubusercontent.com/83361287/116437049-a1a8bd00-a812-11eb-83ba-c2ebd75022f4.jpg)

### Expected Experience

Expected to access blob storage contents in Windows App as we can access in Azure Web App.

**Comment by MRayermannMSFT** [comment]
@thommy-santiago are you behind a proxy and if so have you setup your proxy settings?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue we recommend:
- opening an Azure support ticket
- opening a new issue here

Thanks.
