### ISSUE TITLE
Provide "copy to new partition/row" for Table rows

### ISSUE THREAD

**Issue by NeilMacMullen** [microsoft/AzureStorageExplorer#4404]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I have  a table entity that needs to be duplicated across two partitions.  Due to a code error it was only placed in one. 

### Desired Solution

It would be desirable if I could just right click on a table row  and choose "copy to new partition/row"

### Alternatives and Workarounds

No workaround apart from manually copying each property in turn to a new entry or writing code to do so.

### Additional Context

Unrelated remarks - not sure if this is a github template issue but being force to enter multi-line descriptions in a fixed-width single-line text box is a terrible UI.  Any chance you could at least used a multi-line text box?  (To be clear, I'm talking about the github "new feature" issue page for this project,   not any part of StorageExplorer

**Comment by craxal** [comment]
We added a Duplicate Entity command in 1.26.0. If you right-click and entity, you can specify a new partition and row key to copy all of it's properties to.
