### ISSUE TITLE
Unable to download the files from storage explorer tool

### ISSUE THREAD

**Issue by suvarna-03** [microsoft/AzureStorageExplorer#4405]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.18

### Platform

Windows

### Architecture

x64

### Build Number

Build 19042.928

### Bug Description

User is unable to download the files from storage explorer tool. He is able to access the same files irrespective of the size from Portal and storage explorer preview from portal.

### Steps to Reproduce

1. Open storage explorer.
2. Then choose file which more than 3MB.
3. Simply download the file from explorer tool.
4. It goes on and on in downloading stage and download never completes.
5. Version is 1.18 

### Actual Experience

User is unable to download the file size greater than 3MB from explorer tool. The same file, file with higher size even 12 MB he is able to download from portal as well as portal explorer preview. 

He did same testing from different machine and different network as well. However the result is same. 

Download never gets completed. Machine Windows 10 Professional, version 20H2 (OS Build 19042.928)

Only difference we saw was there is a cap on Maximum transfer rate.  Storage explorer tool- > Edit-> settings-> Transfers. There is a cap given in the Maximum transfer rate as 10.

When there is bo value in this transfer cap then download is successful even if it is 10MB file as well.

 
 
 

### Expected Experience

What could be the reason behind this issue? Is it expected behavior? What can be done to achieve successful download from the explorer tool. 

### Additional Context

```text
NA
```

**Comment by MRayermannMSFT** [comment]
@suvarna-03 a transfer rate of "10" is pretty slow. The transfer limit is in the units of **Mbps**, note the lowercase **b**. Do you really need a transfer limit that small? AzCopy does not recommend setting a limit of too low, because if your blobs are big enough/your blob's blocks are big enough, it can lead to issues like this.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue we recommend:
- opening an Azure support ticket
- opening a new issue here

Thanks.
