### ISSUE TITLE
Storage Explorer Startup Error

### ISSUE THREAD

**Issue by rodolfosparapan** [microsoft/AzureStorageExplorer#4407]
When storage explorer starts, the following error occours:

<img width="323" alt="storage-error" src="https://user-images.githubusercontent.com/4260356/116753146-057ee180-a9dd-11eb-8585-b43d83bd30b5.png">

"The authentication library used by Storage Explorer has failed to start properly. Please ensure you have .NET Framework 4.7.2 or greater installed. If .NET Framework 4.7.2 or greater is already installed then refer to the troubleshooting guide for help. Verbose authentication logging has been enabled.

Error:spawn UNKNOWN"

System: Windows 10 Enterprise
Storage Explorer version: 1.19.0
Logs from: C:\Users\<your username>\AppData\Local\Temp\servicehub\logs

```
04/30/2021 17:56:01 : Information : Log configuration: $SERVICEHUBTRACELEVEL="ALL"
04/30/2021 17:56:01 : Information : Loading 'C:\Users\u004195\AppData\Local\Programs\Microsoft Azure Storage Explorer\resources\app\ServiceHub\MSAL-Services\servicehub.config.json'
04/30/2021 17:56:02 : Error : Attempted connection to service 'StorageServiceClient': location is null
```

[logs.zip](https://github.com/microsoft/AzureStorageExplorer/files/6416473/logs.zip)

**Comment by MRayermannMSFT** [comment]
@rodolfosparapan there should more files in the logs dir. Please share all files in the directory. Thanks.

**Comment by rodolfosparapan** [comment]
> @rodolfosparapan there should more files in the logs dir. Please share all files in the directory. Thanks.

The logs are attached now. Thanks

**Comment by guipcarvalho** [comment]
I'm experiencing the same problem here, with the same information on the log.

**Comment by MRayermannMSFT** [comment]
@rodolfosparapan were you running VS at the same time, and if so, what version? Also, what version of VS do you have installed? Finally, I hate to ask you to do this, can you:
1. close any VS/Storage Explorer instance
2. clear out the logs folder
2. run storage explorer
3. upload the contents of the logs dir

There's still log files missing that I'd expect to see. 

@guipcarvalho please do the same, and feel free to answer the question about running VS side by side/what versions of VS you might have installed.

**Comment by guipcarvalho** [comment]
Hi @MRayermannMSFT! 

Yes, i'm running Visual studio Professional 2019 version 16.8.3 and Visual Studio Code 1.55.2. I was running both when I tried to use Storage Explorer.

I'll try what you asked me and get back to you.

**Comment by sjh37** [comment]
I too have this issue.
![image](https://user-images.githubusercontent.com/4190514/124251014-587c2e80-db1d-11eb-84ec-1bf6f108e547.png)

Using Visual Studio Pro 2019 v16.10.2
Logs attached
[logs.zip](https://github.com/microsoft/AzureStorageExplorer/files/6753487/logs.zip)

**Comment by MRayermannMSFT** [comment]
@sjh37 based on the error in your logs you may want to try the steps another user suggested here: https://github.com/microsoft/AzureStorageExplorer/issues/4418#issuecomment-870470501

**Comment by MRayermannMSFT** [comment]
It seems like the linked issue is most likely also the solution for this issue. Given that no one else has replied in the past 28 days we are going to close this issue.

**Comment by m0rd3cai** [comment]
I had the EXACT same issue with Authentication Library not starting. What worked for me was installing Storage Explorer for All Users instead of just Current User. After that, It loads and works perfectly. Hopefully that helps someone.

**Comment by sjh37** [comment]
It was working perfectly, then installed the `1.27.2` update today (8th Feb 2023) and now I get this:
![image](https://user-images.githubusercontent.com/4190514/217610200-588bb196-4abb-4545-88fc-3d238b8f312b.png)

**Comment by csharpner** [comment]
Same for me, though I have 1.26.1 and that didn't work either.  1.27.2 is the latest version I have and it too gets the error.  Also 1.27.1.  But 1.27.2 started working after I uninstalled all versions of .Net and then installed .Net 7, then after a week or so, Linux updated .Net 7 and now Storage Explorer is broken again - all version I have (1.27.2, 1.27.1, 1.26.1, 1.26.0)

I can't keep doing this.
