### ISSUE TITLE
Tables "Load More" is broken

### ISSUE THREAD

**Issue by gdignard** [microsoft/AzureStorageExplorer#4409]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.1

### Platform

Windows

### OS Version

Windows 10 Pro

### Architecture

x64

### Build Number

OS build 19041.867

### Regression From

1.18

### Bug Description

Storage table with ~10K items

"Showing 1 to 100 of 1,000 cached items" (expected)
Click "Load more"
"Showing 901 to 1,000 of 2,000 cached items" (Not exactly expected but I don't recall which slice of 100 records were shown. Page 10 is correctly shown as the selected page)
Click "Load more"
"Showing 1,901 to 2,000 of 3,000 cached items"
Click "Load more"
"Showing 2,901 to 3,000 of 4,000 cached items"
Click "Load more"
"Showing 3,901 to 4,000 of 5,000 cached items"
Click "Load more"
"Showing 4,901 to 5,000 of 6,000 cached items"
Click "Load more"

List of records vanishes. Now showing "No matching records found"
Status becomes "Showing 5,901 to 1,000 of 1,000 cached items"

Load more is dimmed. No page is selected. If I select a page, it then behaves as it would after the first "Load more" (i.e. it shows 20 pages and the status area displays "Showing 1 to 100 of 2,000 cached items" and the "Load more" is once again available.)

If clicked, the "Load more" now appears to behave normally and I can continue to click until all 13,000+ records appear.

### Steps to Reproduce

1. Launch Storage Explorer
2. Follow steps described in Bug Description
3. 

### Actual Experience

Described in Bug Experience

### Expected Experience

"Load more" button would function correctly

**Comment by MRayermannMSFT** [comment]
@gdignard were you also running a query?

**Comment by gdignard** [comment]
Your insight is correct, though the walkthrough I described was on the entire table. There *had* been a query constructed, and it, too had acted oddly, though the query had been turned off. I don't recall the exact details but returning into the query hadn't behaved as expected, though I don't recall exactly how.

I can't do it today but in the next day or so I'll try to recreate the problem w/r/t the query and post any results back here.

**Comment by MRayermannMSFT** [comment]
@gdignard ok thanks. Let us know if you're able to come up with more exact steps/repro it again. In the meantime we'll look into this.

**Comment by gdignard** [comment]
I'm at my home office which has a very different setup and it's happening (reliably) here too.

I tried with a number of other tables with a similar number of entries and they all seem to work fine. That one table, though, every single time it melts down at the same spot.

I exported the records, created a new table, imported the records into that, and it failed again.

If there's a way to get the file to you privately, let me know. I'd be happy to send you the .csv which, if imported into a table, appears to trigger the bug.

**Comment by gdignard** [comment]
Matthew - 

I'm wondering if you've been able to reproduce this on your own. As mentioned, I do have a file which triggers the bug. Do you need it or can I return it to the bit-bucket?

Cheers,

- Gilles

**Comment by craxal** [comment]
@gdignard We haven't been able to reproduce with a similarly sized table. You can send the sample .csv file to sehelp@microsoft.com, and we can continue investigating.

**Comment by gdignard** [comment]
I sent the file to the address. I'm following up, however, as I have isolated the circumstance triggering the bug.

One of the records in the affected table contained a string field whose text included the '[' and ']' characters.

Editing that record to remove the characters from the field resulted in the bug no longer being triggered.

**Comment by craxal** [comment]
@gdignard Thanks for the update. Does surrounding the value with double quotes also fix the problem?

**Comment by gdignard** [comment]
So I've been playing around with this, and it seems to be just the close square brackets ']' symbol. If the '[' symbol appears in the string it seems to work fine.

I tried surrounding the ] with quotation marks and that doesn't affect the issue.

Could it be a json parsing bug somewhere along the way? When a query happens, the entity is returned in a JSON structure like

`{
  "odata.metadata": "https://myaccount.table.core.windows.net/$metadata#mytable",
  "value": [
    {
      "odata.type": "myaccount.mytable",
      "odata.id": "https://myaccount.table.core.windows.net/mytable(PartitionKey='defaultPK',RowKey='defaultRK')",
      "odata.etag": "W/\"datetime'2021-06-11T18%3A23%3A58.512215Z'\"",
      "odata.editLink": "mytable(PartitionKey='defaultPK',RowKey='defaultRK')",
      "PartitionKey": "defaultPK",
      "RowKey": "defaultRK",
      "Timestamp@odata.type": "Edm.DateTime",
      "Timestamp": "2021-06-11T18:23:58.512215Z",
      "StringField": "[problem text]",
      "OtherField": "no problem"
    }
  ]
}
`

so if the parser wasn't properly checking for quote levels, would try to end the array on the ']' that's inside the "StringField" kvp value.

**Comment by craxal** [comment]
@gdignard FYI, we have been updating our table code base to use a much newer version of the Azure SDK library which may help resolve this issue. Would you like to try a test build to see if the problem reproduces for you?

**Comment by gdignard** [comment]
Sure. Repro was pretty straight forward. We've since cleaned that table to avoid the problem, but I'm pretty sure I stashed away a pre-cleaning version of the data and I'd be happy to dig it out and test against that.

**Comment by craxal** [comment]
@gdignard You can download the test build from this link:

https://cralvordtest02.blob.core.windows.net/customer-share/internal/1.22.0/StorageExplorer-ia32.exe?sv=2020-10-02&st=2021-11-19T18%3A29%3A55Z&se=2021-11-21T07%3A30%3A00Z&sr=b&sp=r&sig=SAVq%2FHGFz5a3aLwOh5VcstMVf4XhJGM0A0NpyrzjJEo%3D

**Comment by craxal** [comment]
@gdignard Did you get a chance to download the internal build? I'm going to move on and close this issue. If you encounter this issue again, let me know, and I'll reopen.
