### ISSUE TITLE
Version 1.19.1 on both Mac and Windows

### ISSUE THREAD

**Issue by jpsebasti** [microsoft/AzureStorageExplorer#4411]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.1

### Platform

Windows

### OS Version

Windows 10 and macOS 10.15.7 Catalina

### Architecture

x64

### Build Number

20210425.1

### Regression From

1.17.1

### Bug Description

I generate a SAS signature on the Azure Portal, I then try to create a new SAS connection to my storage account with Storage Explorer 1.19.1.   I copy the SAS URL from the Azure portal and drop it into the Blob container SAS URL: box in Storage Explorer and a red warning lights up with the error message "The URL is missing a path to the resource."

### Steps to Reproduce

Launch Storage explorer 1.19.1.
Click Add Account
Click Blob container on Select Resource Screen
Select Shared access signature (SAS) on Select Connection Method
Paste the Blob service SAS URL copied from the Azure Portal and I just generated
Storage Explorer lights up a red ! with the error "The URL is missing a path to the resource"

This all worked in version 1.17.1.  Also in version 1.17.1 when I would drop the SAS URL into the box, it would also populate the Display name box with the name of the storage account, that is not occurring in 1.19.1

### Actual Experience

[SA_SAS_problem.docx](https://github.com/microsoft/AzureStorageExplorer/files/6416071/SA_SAS_problem.docx)

### Expected Experience

I expect to be able to connect with the generated SAS URL from the Azure Portal

**Comment by MRayermannMSFT** [comment]
@jpsebasti if you are trying to attach a *storage account* then you need to pick *storage account* on the first page of the connect dialog:
![image](https://user-images.githubusercontent.com/21112697/116911114-45231480-abfb-11eb-838c-d9217392435a.png)
and from there you should pick SAS:
![image](https://user-images.githubusercontent.com/21112697/116911169-5704b780-abfb-11eb-8e13-278a351c9337.png)

**Comment by jpsebasti** [comment]
I was trying to attach the Blob Container.  In the Azure Portal, the SAS for the Blob is entitled "Blob service SAS URL".  If I pick Blob Container in Storage Explorer v1.19 and then choose Shared Access Signature URL (SAS) and drop the Blob service SAS URL into the text box, the error is generated.  
I now see that on a blob container, one can generate another SAS specifically for the Blob Container.  Can you see the confusion?  Why would the portal call the SAS Signature generated on the Storage Account a Blob services SAS URL?  This needs to be way more clear.

I have the URL working from your response though, thank you.
