### ISSUE TITLE
Uploading many, large files silently errors and then any queued transfers are never run

### ISSUE THREAD

**Issue by munael** [microsoft/AzureStorageExplorer#4413]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.0

### Platform

Windows

### OS Version

Windows 10

### Architecture

x64

### Build Number

20210414.2

### Bug Description

Queued transfers of many, large files will fail shortly after starting with no useful error message. No transfers queued after this failure is ever started. You have to restart ASE.

### Steps to Reproduce

1. Azure Premium storage blob.
2. Have many, large files ready to upload. I was trying with `1024 * 300MB` files.
3. Try uploading to any nested path on the blob.
4. Transfer will run for a bit (around 5GB) then fail.

### Actual Experience

Queued transfers of many, large files will fail shortly after starting with no useful error message. No transfers queued after this failure is ever started. You have to restart ASE.

### Expected Experience

ASE can handle uploading arbitrary amounts of files with any size so long as the target storage supports it. Only failure expected would be due to connection issues or Token expiry.

**Comment by MRayermannMSFT** [comment]
@munael have you changed any of the AzCopy settings?

Can you:
1. Repro the issue
2. Go to `C:\users\<your username>\.azcopy`
3. Share the most recent (by date modified) log file with us?

**Comment by munael** [comment]
Shared.

**Comment by MRayermannMSFT** [comment]
@munael where did you share the log file....? I don't see it anywhere. 😢

**Comment by MRayermannMSFT** [comment]
I believe @JasonYeMSFT addressed this with you offline? If not, please ping him on teams as he was supposed to. :)

**Comment by munael** [comment]
It should have a fix on 1.20!

**Comment by JasonYeMSFT** [comment]
@munael Could you share the log file we asked for so we can tell whether the bug we found is really the cause in your case?

**Comment by munael** [comment]
> @munael Could you share the log file we asked for so we can tell whether the bug we found is really the cause in your case?

Shared.

**Comment by JasonYeMSFT** [comment]
In the log file, AzCopy keeps reporting this error "503 Ingress is over the account limit" and that's why it cannot make any progress. I think what you can do is to follow this doc page https://docs.microsoft.com/en-us/azure/storage/common/scalability-targets-standard-account to see if any limit is hit in your case. It the root cause is the transfer rate or number of concurrent requests, you can configure to let AzCopy limit its number of connections or transfer rate at "Settings -> Transfers -> AzCopy"

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. If you run into other data transfer issues, please open new issues for them.
