### ISSUE TITLE
unable to retrieve child resources for blob container in Azure Storage Explorer

### ISSUE THREAD

**Issue by persisesther** [microsoft/AzureStorageExplorer#4414]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.1

### Platform

macOS

### OS Version

macOS Catalina Version 10.15.7

### Architecture

x64

### Build Number

20210425.1

### Bug Description

After signing into my Azure account in Storage Explorer, I am able to view my storage accounts, but when i try to expand on "Blob Containers", I get a pop up error: unable to retrieve child resources. I am able to view the blob containers in Azure Web portal. I have Owner access

### Steps to Reproduce

1. Open Azure Storage Explorer
2. Ensure you are signed in
3. Expand a Storage account seen in the navigating pane on the left 
4. Click on "Blob Container" to try to expand
5. Note error in pop up window
6. Try opening the same Storage account in Azure Web portal
7. I am able to see the blob containers easily

### Actual Experience

5. Not able to view blob containers that a part od the storage account
Pop up error says
Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://sosbstorage.blob.core.windows.net/?include=metadata&comp=list failed, reason: unable to get issuer certificate",
  "stack": "FetchError: request to https://sosbstorage.blob.core.windows.net/?include=metadata&comp=list failed, reason: unable to get issuer certificate\n    at ClientRequest.<anonymous> (/private/var/folders/5f/9tm7crws4s3fm4xnz8y2njghns7_hx/T/AppTranslocation/BE937731-103F-4192-9BDD-0FC321CB83B7/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/node-fetch/lib/index.js:1461:11)\n    at ClientRequest.emit (events.js:310:20)\n    at TLSSocket.socketErrorListener (_http_client.js:426:9)\n    at TLSSocket.emit (events.js:310:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)",
  "type": "system",
  "errno": "UNABLE_TO_GET_ISSUER_CERT",
  "code": "UNABLE_TO_GET_ISSUER_CERT"
}

### Expected Experience

I should be able to view containers present within the storage account in Azure Storage Explorer, just as i can view them at portal.azure.com

**Comment by persisesther** [comment]
I tried importing a self signed certificate using the steps on https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004
but I did not see anything that have s: and i: the exact same. The closet i found was 
s:/C=US/ST=California/O=Zscaler Inc./OU=Zscaler Inc./CN=Zscaler Intermediate Root CA (zscloud.net) (t) 
   i:/C=US/ST=California/O=Zscaler Inc./OU=Zscaler Inc./CN=Zscaler Intermediate Root CA (zscloud.net)/emailAddress=support@zscaler.com
so i used that

**Comment by weblakey** [comment]
**persisesther**, did what you found and tried fix the issue?  I'm getting what looks to be the same error:

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://management.azure.com/subscriptions/db5e8945-f308-4ddb-a061-e58473c2c016/resourcegroups?api-version=2020-06-01 failed, reason: self signed certificate in certificate chain",
  "stack": "FetchError: request to https://management.azure.com/subscriptions/db5e8945-f308-4ddb-a061-e58473c2c016/resourcegroups?api-version=2020-06-01 failed, reason: self signed certificate in certificate chain\n    at ClientRequest.<anonymous> (C:\\Users\\bill.blakey\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1461:11)\n    at ClientRequest.emit (events.js:310:20)\n    at TLSSocket.socketErrorListener (_http_client.js:426:9)\n    at TLSSocket.emit (events.js:310:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)",
  "type": "system",
  "errno": "SELF_SIGNED_CERT_IN_CHAIN",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}

**Comment by persisesther** [comment]
Nope, not fixed yet

**Comment by MRayermannMSFT** [comment]
@persisesther it's very odd that you're only getting this at the blob container level. Normally this happens higher up in the tree, like it did for @weblakey . Do you know if you're Storage Account is in a VNet or something like that? Are you behind a proxy and is it maybe doing something weird for requests to your Storage Account's endpoints?

**Comment by ALZDBA** [comment]
Same issue over here when I go from the **Storage account downward.**

**Fails with Blob containers, file share, queues and tables  !**

"_Unable to retrieve child resources.
Details:
{
  "name": "FetchError",
  "message": "request to https://myblomstorage.blob.core.windows.net/?include=metadata&comp=list failed, reason: self signed certificate in certificate chain",
  "stack": "FetchError: request to https://myblobstorage.blob.core.windows.net/?include=metadata&comp=list failed, 
  reason: self signed certificate in certificate chain
  \n    at ClientRequest.<anonymous> 
  (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1461:11)
  \n    at ClientRequest.emit (events.js:310:20)
  \n    at TLSSocket.socketErrorListener (_http_client.js:426:9)
  \n    at TLSSocket.emit (events.js:310:20)
  \n    at emitErrorNT (internal/streams/destroy.js:92:8)
  \n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
  \n    at processTicksAndRejections (internal/process/task_queues.js:84:21)",
  "type": "system",
  "errno": "SELF_SIGNED_CERT_IN_CHAIN",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}_"

**Comment by MRayermannMSFT** [comment]
Can y'all try using system proxy? You can read about in our networking documentation: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network

**Comment by conawayrn** [comment]
This started happening to us as well when using the Azure Storage Explorer tool.  Works fine from portal.

**Comment by MRayermannMSFT** [comment]
@conawayrn are you behind a proxy? Did you try the System Proxy setting or have you tried manually configuring app proxy settings?

**Comment by persisesther** [comment]
I thought I left a comment here earlier, but I don't see it. Anyway, this issue was resolved for me. I needed to import a cert that my DevOps team forwarded me.. I was able to see the files after that. 
It still is strange that I was able to see the folders within the container before importing the certificate
