### ISSUE TITLE
Snap crashes on startup

### ISSUE THREAD

**Issue by rijnhard** [microsoft/AzureStorageExplorer#4415]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.1

### Platform

Linux

### OS Version

Linux Mint 20.1

### Architecture

x64

### Regression From

previous snap release

### Bug Description

on startup snap dependency errors prevent the application from launching

upon investigating it looks very similar to this issue: 
https://github.com/microsoft/vscode/issues/100940

### Steps to Reproduce

1. launch snap version of Storage explorer

### Actual Experience

application fails to launch

### Additional Context

```text
env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/storage-explorer_storage-explorer.desktop /snap/bin/storage-explorer
[2021-05-04T15:21:19.369Z] ( main) <NONE> Log file: /home/rijnhard/snap/storage-explorer/23/.config/StorageExplorer/StorageExplorer/logs/2021-05-04_172119/2021-05-04_172119_main.log
[2021-05-04T15:21:19.377Z] ( main) <NONE> Log level: info
Gtk-Message: 17:21:21.491: Failed to load module "xapp-gtk3-module"
93710 (Provider) >>> Loading '/snap/storage-explorer/23/resources/app/out/app/main/Resources/ResourceProvider'
93710 (Provider) >>> Loading '/snap/storage-explorer/23/resources/app/out/app/main/Configuration/ConfigurationProvider'
Resolved resource module './resources/Shell': '/snap/storage-explorer/23/resources/app/resources/Shell.json'
Resolved resource module './resources/Azure': '/snap/storage-explorer/23/resources/app/resources/Azure.json'
Resolved resource module './resources/Host': '/snap/storage-explorer/23/resources/app/resources/Host.json'
Resolved resource module './resources/Activities': '/snap/storage-explorer/23/resources/app/resources/Activities.json'
Resolved resource module './resources/Dialogs': '/snap/storage-explorer/23/resources/app/resources/Dialogs.json'
Resolved resource module './resources/ExtensionManager': '/snap/storage-explorer/23/resources/app/resources/ExtensionManager.json'
93710 (Provider) >>> Loading '/snap/storage-explorer/23/resources/app/out/app/main/UserAccountManagement/ServiceHubProvider'
(node:93710) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
** Message: 17:21:21.937: Remote error from secret service: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.239" (uid=1000 pid=93710 comm="/snap/storage-explorer/23/StorageExplorerExe --no-" label="snap.storage-explorer.storage-explorer (enforce)") interface="org.freedesktop.Secret.Service" member="OpenSession" error name="(unset)" requested_reply="0" destination=":1.9" (uid=1000 pid=3801 comm="/usr/bin/gnome-keyring-daemon --daemonize --login " label="unconfined")

(StorageExplorerExe:93710): Gtk-WARNING **: 17:21:22.652: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:/build/gtk+3.0-24RAPQ/gtk+3.0-3.22.24/./gtk/gtkiconhelper.c:493:ensure_surface_for_gicon: assertion failed: (destination)
Aborted (core dumped)
```
```

**Comment by craxal** [comment]
@rijnhard Very likely related. If the snap crashes on startup, it's possible Storage Explorer was trying to open a dialog to show an error message. We do that if Storage Explorer can't access .NET Core or `keytar` for some reason.

Is there any additional output visible in the console? You should also have log files; can you can share those?

**Comment by rijnhard** [comment]
No, no additional output... Where do I find the logs?

**Comment by craxal** [comment]
Assuming you have the latest snap installed, you should find the logs under ~/snap/storage-explorer/current/.config/StorageExplorer/StorageExplorer/logs.

**Comment by craxal** [comment]
@rijnhard Were you able to find your app logs?

**Comment by craxal** [comment]
Closing due lack of response. If you continue to have problems, please open a new issue.

**Comment by rijnhard** [comment]
@craxal apologies but its no longer an issue, randomly. so it can stay closed.

**Comment by craxal** [comment]
@rijnhard Glad you resolved it. If there was anything you think would be helpful for other Linux users, feel free to share.
