### ISSUE TITLE
Support Alt+Enter shortcut for viewing properties

### ISSUE THREAD

**Issue by pharring** [microsoft/AzureStorageExplorer#4416]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Pressing Alt+Enter when a blob is selected results in downloading the blob

### Desired Solution

Pressing Alt+Enter should bring up the Properties for the selected blob

### Additional Context

A few times now I've accidentally (muscle memory from other apps) pressed Alt+Enter when a blob was highlighted intending to show the Properties window. The (very large) blob downloaded and tried to open. Not what I wanted.

**Comment by MRayermannMSFT** [comment]
@pharring is alt-enter a Windows specific shortcut?

**Comment by MRayermannMSFT** [comment]
If we did this, `cmd + i` may be suitable for macOS. That brings up the "Get Info" window in Finder.

**Comment by MRayermannMSFT** [comment]
@RichardMSFT please do this for react blob
@Craxal please do this for react file share
