### ISSUE TITLE
Error:Cannot execute 'SetAccountStoragePrefixAsync'. The underlying stream has closed.

### ISSUE THREAD

**Issue by ArushiJindal** [microsoft/AzureStorageExplorer#4418]
When launching Azure Storage explorer, the error comes, and after pressing "OK" it closes the storage explorer. I am unable to even start it.

Error:Cannot execute 'SetAccountStoragePrefixAsync'. The underlying stream has closed.
[logs.zip](https://github.com/microsoft/AzureStorageExplorer/files/6425147/logs.zip)

**Comment by katerina-bi** [comment]
Same to me. Is there a solution on that?

**Comment by MRayermannMSFT** [comment]
Ok @ArushiJindal , I'm seeing in some of the logs that you sent me an error regarding `Could not load file or assembly 'System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'`. I'll get back to you later today on having us try to work through that together.

@katerina-bi if you would like help then you'll need to [upload your logs ](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#authentication-logs)to as Arushi did.

**Comment by bb980701** [comment]
Same error for me. I was obliged to stick to version 1.18. Any progress on this  issue ?

**Comment by ArushiJindal** [comment]
Any further feedback? I am also keeping myself to previous version, which has other problems.

**Comment by sghokie** [comment]
I am having the same issue on one server. I get the same vectors issue in the log.
I was able to install on to other servers with no issue.

**Comment by aphoenix01** [comment]
Has anyone managed to resolve this yet?

**Comment by stevenboeckmans** [comment]
I had similar issue with visual studio. That took me 2 weeks before I read the solution. So I was able to fix this in 5 min.  :) Open C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\ServiceHub\MSAL-Services\IdentityService\Microsoft.Developer.IdentityService.dll.config and add there the below assembly redirect. Then it should startup fine.
    <dependentAssembly>
          <assemblyIdentity name="System.Numerics.Vectors" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
          <bindingRedirect oldVersion="0.0.0.0-4.1.4.0" newVersion="4.1.4.0" />
     </dependentAssembly>

**Comment by MRayermannMSFT** [comment]
Thanks Steven for figuring that out. If that doesn't work for anyone please let us know.

**Comment by sjh37** [comment]
Thanks. That works now :-)
Strangely, its a similar fix for MSBuild when that got moved to the GAC, the fix for that is below for MS developer reference.

Fix MSBUILD in visual studio v16.8.3
----------------------
"C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\gacutil.exe" /u "Microsoft.Build.Framework, Version=15.1.0.0"
cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin"
"C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\gacutil.exe" /i Microsoft.Build.Framework.dll
See https://stackoverflow.com/a/65230952
Run notepad in admin mode and edit "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe.config"
add
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
        <dependentAssembly>
            <assemblyIdentity name="System.Numerics.Vectors" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-4.1.3.0" newVersion="4.1.4.0" />
        </dependentAssembly>
    </assemblyBinding>

**Comment by MRayermannMSFT** [comment]
It seems like Steven's solution is what we were missing. Given that no one else has replied in the past 28 days we are going to close this issue. Thank you very much again to Steven for figuring out the secret sauce!

**Comment by BastiaanvanUtrecht** [comment]
When launching Azure Storage explorer, the error comes, and after pressing "OK" it closes the storage explorer. I am unable to even start it.

Error:Cannot execute 'SetAccountStoragePrefixAsync'. The underlying stream has closed.

The solution provided by steven is not working for me.
[logs.zip](https://github.com/microsoft/AzureStorageExplorer/files/8605777/logs.zip)
.

**Comment by m0rd3cai** [comment]
I had the EXACT same issue with Authentication Library not starting. What worked for me was installing Storage Explorer for All Users instead of just Current User. After that, It loads and works perfectly. Hopefully that helps someone.

**Comment by TWINOGF** [comment]
I have the same error again after update to 1.27.1 version.
1. Uninstall Azure Storage Explorer
2. Install Azure Storage Explorer
3. Open Azure Storage Explorer and can´t open. Error again
4. Follow steps modifing MSBuild.exe.config but error persists.
5. Attach log files
[AzureStorageExplorerError.zip](https://github.com/microsoft/AzureStorageExplorer/files/10350652/AzureStorageExplorerError.zip)
Can you help me? Thanks
