### ISSUE TITLE
Microsoft.Developer.IdentityService keychain password constantly needed after opening Storage Explorer

### ISSUE THREAD

**Issue by egieseking** [microsoft/AzureStorageExplorer#4419]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.1

### Platform

macOS

### OS Version

macOs Big Sur

### Architecture

x64

### Build Number

20210425.1

### Regression From

1.18.0

### Bug Description

After opening up Microsoft Storage Explorer I am prompted for a password for the Microsoft.Developer.IdentityService keychain item multiple times, even after choosing Always Allow. While the application is running I am prompted repeatedly for the password. 

### Steps to Reproduce

1. Launch Storage Explorer

### Actual Experience

After opening up Microsoft Storage Explorer I am prompted for a password for the Microsoft.Developer.IdentityService keychain item multiple times, even after choosing Always Allow. While the application is running I am prompted repeatedly for the password. 

### Expected Experience

After choosing Always allow should not be asked again.

### Additional Context

```text
I am also running Visual Studio 2019 for Mac. The experience is similar to this report, which appears to have been closed without resolution: https://developercommunity.visualstudio.com/t/microsoftdeveloperidentityservice-keychain-passwor/485500
```

**Comment by MRayermannMSFT** [comment]
@egieseking this has been a known issue for a while due to how the macOS kecyhain works. Let me see if there's been any new developments on this front.

**Comment by MRayermannMSFT** [comment]
Unfortunately there's been no developments on this issue. Also, I found the original issue for this, so closing this as dupe: https://github.com/microsoft/AzureStorageExplorer/issues/3487

**Comment by egieseking** [comment]
in version 1.19.1 of storage explorer with macOS big sur 11.4 this issue has stopped occurring.
