### ISSUE TITLE
Remove the '…' for the action 'Select Statistics…' on blob context menu

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#442]
**Storage Explorer Version**: 1.3.1
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180716.1
**Commit**: 47039639
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Expand one storage account and open one blob container.
2. Upload one blob to it -> Check the context menu for the blob.

#### Expected Experience: ####
It displays **'Select Statistics'** on the blob context menu.

#### Actual Experience: ####
It displays **'Select Statistics...'** for the blob context menu.
![remove](https://user-images.githubusercontent.com/34729022/42808912-d042086e-89a3-11e8-82f9-c62d025458be.png)

1. This issue doesn't reproduce for files/directories.
2. Add '...' for the **'Set Default Access Tier'** on one GPV2 account context menu.
![add](https://user-images.githubusercontent.com/34729022/42810050-8a765e7c-89a6-11e8-9a52-f3bdb6b17e82.png)

**Comment by craxal** [comment]
The reason the "…" should be removed is because this menu option doesn't open a dialog.

**Comment by v-xianya** [comment]
**More Info:** 
 Add '...' next to 'Change Access Tier' for one blob under GPV2 accounts.

**Comment by v-xuanzh** [comment]
This issue has been fixed on latest master build 20190709.5 for blobs.
But it still reproduces for files. So keep it open to track.
![image](https://user-images.githubusercontent.com/34729022/60935150-85fdbb00-a2fb-11e9-94e9-2f75a7017f87.png)

**Comment by v-xianya** [comment]
This issue has been fixed on build master/20190719.7. So we close it.
