### ISSUE TITLE
An unclear error occurs when creating one disk with a name which length is greater than 80

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4425]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 20210506.3
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ MacOS Big Sur 11.3
**Architecture**: ia32/x64
**How found**: exploratory test
**Regression From**: Not a regression

## Bug description ##
The error is confusing when creating disk/ disk snapshots using name which length is greater than 80. Details see the below.

In Storage Explorer:
1. When creating a disk/ disk snapshot with a name which length is greater than 80. Show an unclear error in the Activities panel.
`Error:The value of parameter disk.name is invalid.`
2. When creating a disk/ disk snapshot with a name which length is greater than 260. Show the error: `Error:The provided resource name 'xxxxxx' has a length of '270' which exceeds the maximum length of '260'.`

In Portal:
When creating a disk/ disk snapshot with a name which length is greater than 80. Show the error `The value must have a length of at most 80.`

## Steps to Reproduce ##
1. Expand the Disks node -> Open one resource group which has one disk at least.
2. Select the disk -> Click 'Copy' -> Click 'Paste'.
3. Type a name which length is between [80-260] as the disk name. (Like this name which length is 82 'disk--namedisk--namedisk--namedisk--namedisk--namedisk--namedisk--namedisk--name82')
4. Check whether the error is clear.

## Expected Experience ##
The error message is clear.

Screenshot when creating one disk in the Portal.
![image](https://user-images.githubusercontent.com/41351993/117290203-19748880-aea0-11eb-8a7f-aead6daf9e5a.png)

## Actual Experience ##
The error message is unclear.
`Error:The value of parameter disk.name is invalid.`

![image](https://user-images.githubusercontent.com/41351993/117289425-23e25280-ae9f-11eb-883b-8143607aadb7.png)

## Additional Context ##
1. This issue also reproduces when uploading one disk/creating disk snapshots.
2. Show the below error when trying to create one disk with a name which length is greater than 260.
`Error:The provided resource name '4g-snapsho4g-snapsho4g-snapsho4g-snapsho4g-snapsho4g-snapsho4g-snapsho4g-snapsho4g-snapsho4g-snapsho4g-snapsho4g-snapsho4g-snapsho4g-snapsho4g-snapsho4g-snapsho4g-snapsho4g-snapsho4g-snapsho4g-snapsho4g-snapsho4g-snapsho4g-snapsho4g-snapsho4g-snapsho4g-snapsho4g-snapsho' has a length of '270' which exceeds the maximum length of '260'.`
![image](https://user-images.githubusercontent.com/41351993/117289722-84718f80-ae9f-11eb-9f97-d4ec704088c2.png)

**Comment by v-xianya** [comment]
Will verify this when there is a successful build.

**Comment by v-xianya** [comment]
Reproduce on the build 20210914.1.

**Comment by MRayermannMSFT** [comment]
Validation should now include 80 character checking.

**Comment by v-xianya** [comment]
Verified on the latest main branch 20210917.3. fixed.
![image](https://user-images.githubusercontent.com/41351993/133737592-a8d0c000-b567-478d-9616-1d5e95b7c657.png)
