### ISSUE TITLE
Configure Soft Delete Policy on "Blob Containers" result in JSON parse error parsing XML.

### ISSUE THREAD

**Issue by martinstenhoff** [microsoft/AzureStorageExplorer#4426]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.1

### Platform

Windows

### OS Version

Windows 10 2020H2

### Architecture

i86

### Build Number

20210425.1

### Regression From

Yes, judging from screenshots but unsure which version

### Bug Description

It seem as if Configure Soft Delete Policy is expecting JSON but is receiving XML.

```
{
  "name": "RestError",
  "message": "Error \"SyntaxError: Unexpected token ﻿ in JSON at position 0\" occurred while parsing the response body - ﻿<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<StorageServiceProperties><Cors/><DeleteRetentionPolicy><Enabled>true</Enabled><Days>7</Days><AllowPermanentDelete>false</AllowPermanentDelete></DeleteRetentionPolicy></StorageServiceProperties>.",
  "stack": "RestError: Error \"SyntaxError: Unexpected token ﻿ in JSON at position 0\" occurred while parsing the response body - ﻿<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<StorageServiceProperties><Cors/><DeleteRetentionPolicy><Enabled>true</Enabled><Days>7</Days><AllowPermanentDelete>false</AllowPermanentDelete></DeleteRetentionPolicy></StorageServiceProperties>.\n    at new RestError (C:\\Users\\<USER_REDACTED>\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:2362:28)\n    at errorHandler (C:\\Users\\<USER_REDACTED>\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:3292:17)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
  "code": "PARSE_ERROR",
  "statusCode": 200,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://<STORAGE_ACCOUNT>.blob.core.windows.net/?restype=service&comp=properties",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2020-04-08"
        },
        "user-agent": {
          "name": "user-agent",
          "value": "Microsoft Azure Storage Explorer, 1.19.1, win32 azsdk-js-storageblob/12.4.1 (NODE-VERSION v12.16.3; Windows_NT 10.0.19042)"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "71f4c493-8c5f-4416-8d80-59fe92c785a2"
        },
        "x-ms-date": {
          "name": "x-ms-date",
          "value": "Fri, 07 May 2021 07:25:01 GMT"
        },
        "authorization": {
          "name": "Authorization",
          "value": "SharedKey <STORAGE_ACCOUNT_REDACTED>:<SHARED_KEY_REDACTED>"
        },
        "cookie": {
          "name": "Cookie",
          "value": ""
        }
      }
    },
...
```

### Steps to Reproduce

1. Launch Storage Explorer
2. Right click a "Blob Containers" node in a Storage account (mine is a Premium storage account) and select "Configure Soft Delete Policy..."
3. Get error

### Actual Experience

![image](https://user-images.githubusercontent.com/21321853/117424441-11f5c380-af22-11eb-81df-0381dcc67c14.png)

### Expected Experience

To be able to Configure Soft Delete Policy

**Comment by JasonYeMSFT** [comment]
This is a known issue and there is still a discussion on whether the SDK or the service should fix this issue. #3773
