### ISSUE TITLE
Nothing happens when inserting an entity with an existing PartitionKey and RowKey

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#4427]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 20210507.3
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Big Sur 11.3
**Architecture**: ia32/x64
**How found:** From executing a test case
**Regression From**: Previous release(1.19.1)

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create a new table -> Click 'Add' in its toolbar -> Type two values to the 'PartitionKey' & 'RowKey' -> Click 'Insert'.
3. Click 'Add' -> Type the same values again -> Click 'Insert'.
4. Check whether an error dialog pops up.

 ## Expected Experience ##
An error dialog pops up.
![image](https://user-images.githubusercontent.com/54055206/117428264-7c295b00-af58-11eb-9740-fb80dea516a7.png)

## Actual Experience ##
Nothing happens.

**Comment by v-limu** [comment]
Hi @craxal Verified on the lasted build 20210526.1. This issue still reproduces.

**Comment by craxal** [comment]
@v-limu Sorry, closed the wrong bug.

**Comment by v-limu** [comment]
Verified on build 20210526.8. This issue has been fixed. So we closed it.
