### ISSUE TITLE
The color of the 'X button is inconsistent between 'Edit Entity' and 'Properties' dialogs

### ISSUE THREAD

**Issue by v-haiz** [microsoft/AzureStorageExplorer#443]
**Storage Explorer Version**: 1.3.1
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180716.1
**Commit**: 293c2d62 
**Regression** From: Not a Regression 

**Steps to Reproduce**:
1. Open one **blob container**/**file share** which contains one **blob**/**file** at least.
2. Open 'Properties' dialog of the **blob**/**file** then add a metadata for it -> Check the color of the 'X' button.
3. Open 'Edit Entity' dialog of one **table**-> Add a property for the entity -> Check the color of the 'X' button again.
4. Check whether the color of the 'X' button is consistent between 'Edit Entity' and 'Properties' dialogs or not.  

**Expected Experience**:
These two color of 'X' button are consistent.
 
**Actual Experience**:
These two color of 'X' button are inconsistent. Please see the below picture.
![actual2](https://user-images.githubusercontent.com/37653604/42809646-99dc05f2-89a5-11e8-99d9-c998a04f3db2.PNG)

**Comment by MRayermannMSFT** [comment]
Won't fix since tables
