### ISSUE TITLE
Nothing happens after clicking 'Go to AzCopy Log File' with 'Log Level' set to None

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4432]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 20210508.4
**Branch**: main
**Platform/OS**: Windows 10/MacOS Big Sur 11.3
**Architecture**: ia32/x64
**How found**: ad-hoc test
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Go to 'Settings -> Transfers -> AzCopy -> Log Level' -> Select 'None'.
2. Expand one storage account -> Blob Containers.
3. Open one blob container -> Upload one file as block blob to it.
4. Upload a same file as append blob to the same destination.
5. Select 'Replace' -> Click 'Apply'.
6. There is a failed activity log -> Click 'Go to AzCopy Log File' next to the activity log.
7. Check the result.

## Expected Experience ##
The file explorer opens and go to the azcopy logs location.

## Actual Experience ##
Nothing happens.

## Additional Context ##
This issue doesn't reproduce on Linux.

**Comment by MRayermannMSFT** [comment]
AzCopy shouldn't give us a log file location if there is no log file! Will raise an issue with them.

**Comment by MRayermannMSFT** [comment]
Fixed merged into main.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240830.6. The action 'Go to AzCopy Log File' has been removed.
![image](https://github.com/user-attachments/assets/036b3a00-e211-4ea2-8253-a6e3b185611c)
