### ISSUE TITLE
There is no setting 'Resource type' on the Summary dialog when attaching one file share

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4439]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 20210511.3
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ MacOS Big Sur 11.3
**Architecture**: ia32/x64
**How found**: exploratory test
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Select one file share -> Generate its shared access signature -> Copy the SAS.
3. Open the connect dialog -> Select 'File share' -> Paste the copied SAS to the 'File share SAS URL' filed -> Click 'Next'.
4. Check whether there is the setting 'Resource type' on the Summary dialog.

## Expected Experience ##
There is the setting 'Resource type' on the Summary dialog.

The screenshot for one blob container:
![image](https://user-images.githubusercontent.com/41351993/117783073-c9693d80-b274-11eb-8898-b0c2014eb488.png)

## Actual Experience ##
There is no setting 'Resource type' on the Summary dialog.
![image](https://user-images.githubusercontent.com/41351993/117783082-cbcb9780-b274-11eb-9210-2638804c209f.png)

## Additional Context ##
1. This issue doesn't reproduce for one blob container.
2. This issue reproduces for one table & queue.

**Comment by v-xianya** [comment]
@craxal 
Verified this issue on build 20210524.3. 

1. Fixed for one file share.
2. Still reproduce for one queue/table.

So we are going to re-open this issue.

![image](https://user-images.githubusercontent.com/41351993/119316624-c412e680-bca9-11eb-9c0e-8ef027781e99.png)

**Comment by craxal** [comment]
@v-xianya I will do this for table and queue. May I suggest that in the future, you mention all areas that need fixing in the title or bug description? For example, "...when attaching file share, queue, or table". The Additional Context area is meant more supplemental information, such as for helping describe or reproduce the bug, not important information such as other areas that need fixing.

**Comment by v-xianya** [comment]
@craxal Got it. thanks for your response and clarification!
 We will mention all areas that need fixing in the title or bug description.
