### ISSUE TITLE
Support to retry the failed activity when changing the Access Tier for one blob

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#444]
**Storage Explorer Version**: 1.3.1
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180716.1
**Commit**: 47039639
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Choose one GPV2 account -> Open one blob container which contains one blob at least.
2. Create snapshot for the blob -> Try to change the current access tier for the original blob -> Check the failed message in Activities.

#### Expected Experience: ####
Support to retry the failed activity.

#### Actual Experience: ####
Not support to retry the failed activity.
![retry](https://user-images.githubusercontent.com/34729022/42809271-c2315292-89a4-11e8-9f8a-ebc5006ab6ff.png)

**Comment by craxal** [comment]
You expect a Retry action to be available for the change access tier activity? That won't do any good. The message says "This operation is not permitted because the blob has snapshots." That's pretty clear about why it failed, and no amount of retrying is going to change the outcome.

**Comment by v-xuanzh** [comment]
Hi @craxal ,We expect to use the 'Retry' action directly after deleting the created blob snapshots. We think it is convenient for users.

**Comment by craxal** [comment]
Let's wait for users to ask for this before committing to anything.
