### ISSUE TITLE
Unable to retrieve child resources.

### ISSUE THREAD

**Issue by 1011602032** [microsoft/AzureStorageExplorer#4442]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.1

### Platform

Windows

### OS Version

windows 10

### Architecture

x64

### Bug Description

https://ak0232.blob.core.windows.net/container1/Screenshot (1006).png

### Steps to Reproduce

https://ak0232.blob.core.windows.net/container1/Screenshot (1006).png

### Actual Experience

Unable to retrieve child resources.

Details:
getaddrinfo ENOTFOUND azure0232.file.core.windows.net

**Comment by 1011602032** [comment]
copy the full link and paste it in the browser then you will get screenshot of my issue

**Comment by grtiplad** [comment]
I'm having the same issue on my SAW (max version available is 1.17) for any Storage Account I attach using Storage Account Name and Key

**Comment by MRayermannMSFT** [comment]
@1011602032 we cannot access your image. Can you just drag and drop it directly into a reply to this issue? Thanks.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue, you can either open an Azure support ticket from the Azure portal (recommended), or open a new issue here. Thanks.
