### ISSUE TITLE
There are no status strings in the editor of one blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4445]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 20210512.2
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04
**Architecture**: ia32/x64
**How found**: exploratory testing
**Regression From**: Previous release (1.19.1)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Open one blob container.
3. Check whether there are status strings on the left bottom of the editor. 

## Expected Experience ##
There are status strings.
![image](https://user-images.githubusercontent.com/41351993/117934320-2298a600-b335-11eb-9050-95034e977afd.png)

## Actual Experience ##
There are no status strings.
![image](https://user-images.githubusercontent.com/41351993/117934325-23c9d300-b335-11eb-9a59-17896f24c6bc.png)

## Additional Context ##
1. This issue doesn't reproduce on MacOS Big Sur 11.3.
1. Status strings display after resizing the editor.
2. This issue also reproduces for one file share/queue/table/resource group.
![status](https://user-images.githubusercontent.com/41351993/117935712-97b8ab00-b336-11eb-97fc-3013c60f0822.gif)

**Comment by JasonYeMSFT** [comment]
It seems the cause is the toolbar rendering. We probably need to send a resize event after rendering the toolbar items.

**Comment by craxal** [comment]
@v-xianya As @JasonYeMSFT mentioned, it appears the toolbar rendering has something to do with it. When the panel first appears, the toolbar is only a few pixels high. But when the buttons render, it pushes the bottom portion of the panel below the bottom edge.

I have made some changes to the toolbar which seem to resolve the issue. Can you please verify with the latest build?

**Comment by v-xianya** [comment]
Hi @craxal Verified this issue on the latest build main/20210610.4. Fixed. So we are going to close it.
