### ISSUE TITLE
No error info displays in the 'Error Details' dialog after clicking the 'Details...' next to a promote version failed activity log

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4447]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 20210512.2
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ MacOS Big Sur 11.3
**Architecture**: ia32/x64
**How found**: exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand the storage account -> Blob Containers.(Make sure blob versioning is enabled)
2. Create one blob container -> Upload one blob to it.
3. Change the blob to get the blob version -> Right click the blob -> Click 'Manage History -> Manage Versions'.
4. Acquire lease for the blob -> Select the previous version -> Click 'Promote Version'.
5. Click the 'Details...' next to the activity log -> Check whether an error info displays in the 'Error Details' dialog.

## Expected Experience ##
An error info displays.

## Actual Experience ##
No error info displays, just display {} in the 'Error Details' dialog.
![image](https://user-images.githubusercontent.com/41351993/117948558-d1dc7980-b343-11eb-89dc-94503e7c3444.png)

**Comment by v-xianya** [comment]
@JasonYeMSFT 
Verified this issue on the lasted build 20210514.4. 
The link 'Details...' is removed. Is this intentional?
![image](https://user-images.githubusercontent.com/41351993/118214878-25190e00-b4a3-11eb-8d1b-b378aa647ea4.png)

**Comment by JasonYeMSFT** [comment]
Yes, that's intentional. I added the logic to hide that action when there is nothing to display. You may be able to see the action if there is an error that we can display in the dialog.
