### ISSUE TITLE
Display the same log message for the 'Set Public Access Level' and 'Manage Access Policies' actions

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#445]
**Storage Explorer Version**: 1.3.1
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180716.1
**Commit**: 47039639
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Expand any accounts and select one blob container.
2. Right click the blob container then select 'Set Public Access Level' -> Check the message on Activities.
3. Right click the same blob container then select 'Manage Access Policies' -> Check the message on Activities again.

#### Expected Experience: ####
Display two differnet log messages for these actions.

#### Actual Experience: ####
Display the same log message for these two actions.
![log](https://user-images.githubusercontent.com/34729022/42809518-57a8eb5a-89a5-11e8-9bb4-e747e7a0313b.png)

**Comment by craxal** [comment]
This is intentional. The same library function is used to set access level and access policies. We're planning on joining the two dialogs in a future release.
