### ISSUE TITLE
Show the blob rehydration status in blob list view

### ISSUE THREAD

**Issue by beroder** [microsoft/AzureStorageExplorer#4451]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

When you set the blob tier or an archived blob to hot or cool the access tier property will not immediately change to the new tier since rehydrating a blob can take several hours.  This is expected.  When a blob is rehydrating a call to Get Blob Properties will return the archive status and show rehydrate-pending-to-hot  or rehydrate-pending-to-cool depending on the tier it is being rehydrated to.  If you query blob properties in ASE it is showing this property.

### Desired Solution

Can you add a column to the list view output of a container called ‘Archive Status’ that would also show the archive status of the blob? Instead of using exact value returned from Storage it would be better to convert it to text that was more meaningful e.g. ‘Rehydrating to hot tier’ or Rehydrating to cool tier’.  We are already showing the Access Tier and Access Tier Last Modified status.  With the Access Tier Last Modified and the Archive Status a user can know that the blob is still rehydrating.  We see support cases where customers don’t know if the blob is still rehydrating or not so having the archive status property will give them that visual queue that they need.

**Comment by MRayermannMSFT** [comment]
It should also be in the list response:

From: https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs#response-body
> For version 2017-04-17 and above...If the blob is in rehydrate pending state then ArchiveStatus element is returned with one of the valid values rehydrate-pending-to-hot/rehydrate-pending-to-cool. For detailed information about block blob tiering see [Hot, cool and archive storage tiers](https://docs.microsoft.com/en-us/azure/storage/storage-blob-storage-tiers).

Assuming that works, then simply grab the value from there. If it is not working/if the only way to get this info is a properties call, we'll need to have service team add the info to listing response. In that case, communicate this to Brian so he can get them to do that and then we can complete this.

**Comment by craxal** [comment]
@beroder Blob explorers have quite a few columns as is. We could combine `ArchiveStatus` with `AccessTier` and `AccessTierInferred` such that the "Access Tier" column would display values such as:
* Hot (inferred)
* Cool
* Archive
* Archive (rehydrating to Cool)
* Archive (rehydrating to Hot)

Does that work for you? Or would you rather have a separate column for the archive status?
