### ISSUE TITLE
Manage ACLs - failed to get permission

### ISSUE THREAD

**Issue by robathija** [microsoft/AzureStorageExplorer#4452]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.1

### Platform

Windows

### OS Version

Windows 10

### Architecture

x64

### Build Number

20210425.1

### Bug Description

I get failed to get permissions for 'container/folder'

with the below error log

{
  "message": "\"{\\n  \\\"name\\\": \\\"FetchError\\\",\\n  \\\"message\\\": \\\"request to https://xxxxxxxxxxx.dfs.core.windows.net/client1/data?action=getAccessControl&upn=true failed, reason: unable to get local issuer certificate\\\",\\n  \\\"type\\\": \\\"system\\\",\\n  \\\"errno\\\": \\\"UNABLE_TO_GET_ISSUER_CERT_LOCALLY\\\",\\n  \\\"code\\\": \\\"UNABLE_TO_GET_ISSUER_CERT_LOCALLY\\\",\\n  \\\"stack\\\": \\\"FetchError: request to https://xxxxxxxxxxxx.dfs.core.windows.net/client1/data?action=getAccessControl&upn=true failed, reason: unable to get local issuer certificate\\\\n    at ClientRequest.<anonymous> (C:\\\\\\\\Users\\\\\\\\xxxxx\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\node-fetch\\\\\\\\lib\\\\\\\\index.js:1461:11)\\\\n    at ClientRequest.emit (events.js:310:20)\\\\n    at TLSSocket.socketErrorListener (_http_client.js:426:9)\\\\n    at TLSSocket.emit (events.js:310:20)\\\\n    at emitErrorNT (internal/streams/destroy.js:92:8)\\\\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\\\\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)\\\"\\n}\""
}

### Steps to Reproduce

1. Launch Storage Explorer
2. Click on Manage ACLs (or right click)

### Actual Experience

As described above - please help in resolving the failed to get permissions error

**Comment by MRayermannMSFT** [comment]
@robathija have you attached your container or did you sign in and expand a subscription & storage account nodes to get to it?

**Comment by robathija** [comment]
@MRayermannMSFT Sorry I missed updating this issue, after breaking my head as to what was going wrong I narrowed it down to zscaler causing the issue as I was able to able to access it successfully on my personal laptop

I will close this issue, thanks
