### ISSUE TITLE
Fail to paste one blob to an attached blob container with SAS permissions (Read, List, Create)

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4453]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 20210513.1
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ MacOS Big Sur 11.3
**Architecture**: ia32/x64
**How found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Select and right click one blob container -> Click 'Get Shared Access Signature... '.
2. Select permissions 'Read, List, Create' to create a SAS -> Copy the SAS.
3. Attach the blob container with the SAS.
4. Copy one blob and paste to the SAS attached blob container.
5. Check the result.

## Expected Experience ##
Succeed to paste.

## Actual Experience ##
Fail to paste with an error "UnexpectedCancel".
![image](https://user-images.githubusercontent.com/41351993/118090093-b2088c80-b3fb-11eb-84fa-34b896f0779a.png)

Error Details:
`{
  "message": "\"UnexpectedCancel\""
}`

## Additional Context ##
AzCopy Log:
[4d76d8db-2f73-3f4f-7e04-1df954fc238e.log](https://github.com/microsoft/AzureStorageExplorer/files/6470809/4d76d8db-2f73-3f4f-7e04-1df954fc238e.log)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230516.9. Fixed. So, we are going to close it.
