### ISSUE TITLE
There is a successful activity log after copying one blob and pasting to one folder in the same attached blob container with access policy permissions (List, Write)

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4454]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 20210513.1
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ MacOS Big Sur 11.3
**Architecture**: ia32/x64
**How found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Select one blob container -> Upload one folder to it.
2. Add an access policy with 'List, Write' permissions for the blob container.
3. Generate SAS for the blob container by selecting the access policy.
4. Attach the blob container by the generated SAS.
5. Upload one blob(6MB) to the blob container (Disable 'Prompt for conflicts').
6. Copy the blob and paste it into the folder in the same blob container.
7. Check the result.

## Expected Experience ##
Show a failed activity log and indicate a clear error.

## Actual Experience ##
1. Show a successfully activity '0 items transferred'.
![image](https://user-images.githubusercontent.com/41351993/118087952-edee2280-b3f8-11eb-9e8e-4a33602b555a.png)
2. The pasted blob doesn't display in the editor.

## Additional Context ##
1. The result have nothing to do with the option state in the 'Storage Access Policy Detected' dialog.
1. This issue doesn't reproduce when copying one blob from another blob container.
2. For one file share, show the below error:
![image](https://user-images.githubusercontent.com/41351993/118087423-1f1a2300-b3f8-11eb-840f-2aa95dda268a.png)

**Comment by MRayermannMSFT** [comment]
@v-xianya just to make sure we are on the same page, this should fail because you cannot **read** the blob you are trying to copy.

**Comment by MRayermannMSFT** [comment]
@v-xianya one more thing, can you repro this again, and upload the AzCopy log file for the transfer to this GitHub issue. Thanks!

**Comment by v-xianya** [comment]
@MRayermannMSFT 
Yep, The transfer should fail and this is because of no 'read' permission.

I can reproduce this issue on the latest build 20210518.4. but there is no way to get the AzCopy log file (due to without link Go to AzCopy Log File).
![image](https://user-images.githubusercontent.com/41351993/118582227-95869e80-b7c5-11eb-9356-cc502236f198.png)

**Comment by MRayermannMSFT** [comment]
Maybe revisit when AzCopy adds detect conflicts via list

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230627.1. Fixed. So, we are going to close it.
