### ISSUE TITLE
Getting issue while installing Azure storage locally on Mac

### ISSUE THREAD

**Issue by nishant2803** [microsoft/AzureStorageExplorer#4458]
Hi : I installed a Azure local storage but getting below issue
Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to http://127.0.0.1:10000/devstoreaccount1?include=metadata&comp=list failed, reason: connect ECONNREFUSED 127.0.0.1:10000",
  "stack": "FetchError: request to http://127.0.0.1:10000/devstoreaccount1?include=metadata&comp=list failed, reason: connect ECONNREFUSED 127.0.0.1:10000\n    at ClientRequest.<anonymous> (/private/var/folders/0g/bs20hvp137bgt9_0j2fqc_b00000gn/T/AppTranslocation/48029833-8E44-46F9-990C-DCD2AE12EAD8/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/node-fetch/lib/index.js:1461:11)\n    at ClientRequest.emit (events.js:310:20)\n    at Socket.socketErrorListener (_http_client.js:426:9)\n    at Socket.emit (events.js:310:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)",
  "type": "system",
  "errno": "ECONNREFUSED",
  "code": "ECONNREFUSED"
}

**Comment by MRayermannMSFT** [comment]
@nishant2803 are you trying to work with an emulator? If yes, then you will need to start the emulator before using it. I ask/say this because `http://127.0.0.1:10000/devstoreaccount1?include=metadata&comp=list` is indicative of trying to work with an emulator. If you are not, then please let us know. Thanks.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue, you can either open an Azure support ticket from the Azure portal (recommended), or open a new issue here. Thanks.
