### ISSUE TITLE
Unexpected error after copying a newly created file share 

### ISSUE THREAD

**Issue by v-haiz** [Microsoft/AzureStorageExplorer#446]
**Storage Explorer Version**: 1.3.1
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180717.9
**Commit**: 633ce83b
**Regression From**: Previous release 1.3.1(20180711.1)

**Steps to Reproduce**:
1. Create a new **file share**.
2. Right click the new file share and click 'Copy File Share'.
3. Check whether the created file share can be copied successfully or not.

**Expected Experience**:
The new created file share can be copied successfully.

**Actual Experience**:
Pop up an error after copying a new created file share. 

And the new created file share can be copied successfully after refreshing the 'File Shares' node.

**Comment by MRayermannMSFT** [comment]
@v-haiz , what was the error?

**Comment by v-haiz** [comment]
@MRayermannMSFT Below is the error message:
![actual](https://user-images.githubusercontent.com/37653604/43054228-0da8b0ce-8e20-11e8-92bc-d1f1849cb471.PNG)

**Comment by MRayermannMSFT** [comment]
I can no longer repro this. @v-haiz , please confirm with the latest release candidate build.

**Comment by v-haiz** [comment]
@MRayermannMSFT Yes. This issue does not repro in the latest release candidate build(●'◡'●).
