### ISSUE TITLE
Transferring to File share goes on forever

### ISSUE THREAD

**Issue by saimanoj18** [microsoft/AzureStorageExplorer#4463]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.91.1

### Platform

Windows

### OS Version

Windows 10

### Architecture

x64

### Bug Description

![image](https://user-images.githubusercontent.com/4462455/118510506-50189180-b731-11eb-9d36-26b8d2000be0.png)
I am trying to upload a folder that has a few files in it. I tried many times but the transfer/uploads goes on forever, even after 2 hrs, its still transferring.

### Steps to Reproduce

1. Launch Storage explore and try to upload a folder whose contents are of size 4 GB in total

### Actual Experience

I have tried multiple times and yet the transferring never finishes.

**Comment by MRayermannMSFT** [comment]
@saimanoj18 

- How many files are in the folder? The screenshot says 7 have been transferred. Is that all of them?
- The screenshot says your current upload speed is ~2.1 Mbps. For 4 GB we think that would take about 9 hours to finish.
- While running an upload, you can monitor AzCopy's log file to see if it is encountering any issues. You can find the log file at `C:\users\<your name>\.azcopy`. You can also look at old log files to see if there's anything wrong. Feel free to share log files with us here if you're not sure what to look for.

**Comment by saimanoj18** [comment]
@MRayermannMSFT - Thank you for taking up my queries :)
1. There are six folders and each folder has exactly one file of about 600-700 MB
2. I didn't realize that it would take 9 hrs for this. I calculated it now, and found that it would a few hrs. I was expecting it to be over in 30 mins to an hour.
3. Thanks for this, I have started a fresh upload and will share with you the logfiles if something fails.

Is there a faster way to upload ? Uploading to OneDrive or Dropbox for 4 GB is quite faster on my side. Why is it that to Azure fileshare, it takes significantly more time ? 

In Storage explorer, can we know how much percentage has been uploaded and how much time it takes more ?

Also what is the use of "Copy AzCopy command to clipboard" ?

**Comment by MRayermannMSFT** [comment]
@saimanoj18 

> Is there a faster way to upload ? Uploading to OneDrive or Dropbox for 4 GB is quite faster on my side. Why is it that to Azure fileshare, it takes significantly more time ?

Behind the scenes, we use [AzCopy](https://github.com/Azure/azure-storage-azcopy) for performing transfers to, from, and between Azure. It is pretty good at being as fast as possible by default. Have you possibly changed some AzCopy settings away from their default values? You can check by doing to Settings (gear on the left) -> Transfers -> AzCopy section and see if you've done anything like restricting the network speed.

> In Storage explorer, can we know how much percentage has been uploaded and how much time it takes more ?

AzCopy will sometimes/eventually report a percentage to us. Displaying a ETA for completion is not possible at this time.

> Also what is the use of "Copy AzCopy command to clipboard" ?

That is there for you to use if you would like to run the same transfer directly against AzCopy, or if you would like to use that command as the starting point for running a different command, or if you'd like to learn how to write an AzCopy command, etc.
