### ISSUE TITLE
Unable to copy storage blobs from Azure Stack Hub to public Azure

### ISSUE THREAD

**Issue by wturner123** [microsoft/AzureStorageExplorer#4464]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.1

### Platform

Windows

### OS Version

Windows Server 2019

### Architecture

i86

### Build Number

20210425.1

### Regression From

1.13.1

### Bug Description

Unable to copy blobs from a storage container in Azure Stack Hub, to another container in public Azure.

### Steps to Reproduce

1. Ensure Storage Explorer is targeting the Azure Stack APIs (Edit --> Target Azure Stack APIs)
2. Add a new account --> Subscription --> Create custom environment with ARM endpoint for the Stack
_NB: The account I'm using here has access to both a subscription in Azure Stack Hub, as well as public Azure. Adding a subscription connection for the Stack also adds a connection to the subscription in public Azure, not sure if this is intended? Also adds some duplicate entries for the Stack sub, see below._
![image](https://user-images.githubusercontent.com/61973249/118511774-2445dd80-b72a-11eb-9576-75ef37f9201f.png)
3. Open a blob container in Azure Stack Hub and find a blob
4. Click Copy
5. Open a blob container in public Azure
6. Click Paste

### Actual Experience

The action fails with the below error message (values removed):
```
Failed to copy '{stack blob location}' to '{azure blob location}': The value for one of the HTTP headers is not in the correct format.
RequestId:dcd192c9-d01e-001c-0429-4b5139000000
Time:2021-05-17T14:31:11.9401219Z
```

```
{
  "name": "StorageError",
  "message": "The value for one of the HTTP headers is not in the correct format.\nRequestId:dcd192c9-d01e-001c-0429-4b5139000000\nTime:2021-05-17T14:31:11.9401219Z",
  "stack": "StorageError: The value for one of the HTTP headers is not in the correct format.\nRequestId:dcd192c9-d01e-001c-0429-4b5139000000\nTime:2021-05-17T14:31:11.9401219Z\n    at Function.StorageServiceClient._normalizeError (C:\\Users\\wturner\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:1205:23)\n    at Object.StorageServiceClient._processResponse (C:\\Users\\wturner\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:751:50)\n    at Request.processResponseCallback [as _callback] (C:\\Users\\wturner\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:319:37)\n    at Request.self.callback (C:\\Users\\wturner\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:185:22)\n    at Request.emit (events.js:310:20)\n    at Request.<anonymous> (C:\\Users\\wturner\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1157:10)\n    at Request.emit (events.js:310:20)\n    at IncomingMessage.<anonymous> (C:\\Users\\wturner\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1079:12)\n    at Object.onceWrapper (events.js:416:28)\n    at IncomingMessage.emit (events.js:322:22)",
  "code": "CannotVerifyCopySource",
  "statusCode": 400,
  "requestId": "dcd192c9-d01e-001c-0429-4b5139000000"
}
```
Created the environment variable `STG_EX_LOG_LEVEL` with the value `debug` for additional logging, but couldn't see anything other than the ActivityProvider logs which are the same as the ones seen in the client:
```
[2021-05-17T14:31:06.650Z] (ActivityProvider_2296) <INFO> Activity added {
  title: "Queued copy blob from '{stack blob location}' to '{azure blob location}'",
  message: '',
  speed: undefined,
  progress: 0,
  status: 0,
  actions: []
}
[2021-05-17T14:31:11.977Z] (ActivityProvider_2296) <INFO> Activity finalized {
  title: "Failed to copy '{stack blob location}' to '{azure blob location}'",
  message: 'The value for one of the HTTP headers is not in the correct format.\n' +
    'RequestId:dcd192c9-d01e-001c-0429-4b5139000000\n' +
    'Time:2021-05-17T14:31:11.9401219Z',
  speed: undefined,
  progress: 0,
  status: 3,
  actions: [ 'Details...', 'Retry' ]
}
```

### Expected Experience

The blob is successfully copied from one storage account to another.

### Additional Context

```text
* The last release where this works is 1.13.1, which coincidently was the version I was using up until recently. Have tested in every major release (14, 15, 16, 17, 18 & 19).
* Copying the other way around works fine (i.e. public Azure --> Azure Stack Hub), as well as copying from Stack to Stack or Azure to Azure.
```

**Comment by MRayermannMSFT** [comment]
@wturner123 when did you last try this in 1.13?

Can you try downloading 1.13 from [here](https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.13.1), and trying copying the **exact same files** in the **exact same way** and let us know if it actually works?

**Comment by cblackuk** [comment]
It is worth pointing out - we tested ALL other versions higher than 1.13.1 - and all of them are sadly not working.

**Comment by wturner123** [comment]
@MRayermannMSFT - after testing the other versions yesterday, I reinstalled 1.13.1 to ensure it still worked (which it did). It was downloaded from the GitHub release as per your link.

**Comment by MRayermannMSFT** [comment]
@wturner123  @cblackuk when testing the previous versions, did you try 1.14.0 or 1.14.1, or maybe both? I ask because in 1.14.1 the version of AzCopy that we use changed while in 1.14.0 it was the same as 1.13.1.

**Comment by wturner123** [comment]
@MRayermannMSFT - Just installed 1.14.0, but unfortunately I can't test the copy as none of the Azure Stack Hub blob containers are able to be listed in this version for some reason.

**Comment by JasonYeMSFT** [comment]
@wturner123 Matt is oof right now. We will discuss this further with Matt when he gets back.

**Comment by MRayermannMSFT** [comment]
@wturner123 when using 1.14.2, and doing the copy, does it look like Storage Explorer is using AzCopy? One way to tell is, do you see a "Copy AzCopy Command to Clipboard" near the status message for the copy operation?

**Comment by wturner123** [comment]
@MRayermannMSFT Doesn't look like it from what I can tell
![image](https://user-images.githubusercontent.com/61973249/122895197-c8c9c980-d33f-11eb-84f0-11783a5c1dd7.png)

```
{
  "name": "StorageError",
  "message": "The value for one of the HTTP headers is not in the correct format.\nRequestId:61fc85b9-401e-0056-6143-67615e000000\nTime:2021-06-22T08:52:07.1649868Z",
  "stack": "StorageError: The value for one of the HTTP headers is not in the correct format.\nRequestId:61fc85b9-401e-0056-6143-67615e000000\nTime:2021-06-22T08:52:07.1649868Z\n    at Function.StorageServiceClient._normalizeError (C:\\Users\\wturner\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:1205:23)\n    at Object.StorageServiceClient._processResponse (C:\\Users\\wturner\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:751:50)\n    at Request.processResponseCallback [as _callback] (C:\\Users\\wturner\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:319:37)\n    at Request.self.callback (C:\\Users\\wturner\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:185:22)\n    at Request.emit (events.js:210:5)\n    at Request.<anonymous> (C:\\Users\\wturner\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1157:10)\n    at Request.emit (events.js:210:5)\n    at IncomingMessage.<anonymous> (C:\\Users\\wturner\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1079:12)\n    at Object.onceWrapper (events.js:299:28)\n    at IncomingMessage.emit (events.js:215:7)",
  "code": "CannotVerifyCopySource",
  "statusCode": 400,
  "requestId": "61fc85b9-401e-0056-6143-67615e000000"
}
```

**Comment by MRayermannMSFT** [comment]
@wturner123 I finally got access to an internal stack and tried this out. I cannot get this scenario to work for 1.13.0, 1.14.2, or 1.20.1 (latest version). Let me go over all of my observations thus far:

- In 1.13.0:
    - **AzCopy was used** for copies that involved an Azure Stack source and/or destination
    -  I was not able to copy from public Azure -> Azure Stack, saw a `400/The value for one of the HTTP headers is not in the correct format`
    - I was not able to copy from Azure Stack -> public Azure, saw a `500/Operation could not be completed within the specified time`
- In 1.14.2
    - **AzCopy was not used** for copies that involved an Azure Stack source and/or destination
    - I was able to copy from public Azure -> Azure Stack
    - I was not able to copy from Azure Stack -> public Azure, saw a `500/Operation could not be completed within the specified time`
- In 1.20.1
    - **AzCopy was not used** for copies that involved an Azure Stack source and/or destination
    - I was able to copy from public Azure -> Azure Stack
    - I was not able to copy from Azure Stack -> public Azure, saw a `500/Operation could not be completed within the 

Are you sure you are able to do copies from Azure Stack -> public Azure in 1.13.0? If yes then:

- Can you confirm that AzCopy is being used
- If it is, can you go to Help > About and tell me what AzCopy version # you see?

**Comment by wturner123** [comment]
@MRayermannMSFT Just installed **1.13.0** to test this out.

* Set Storage Explorer to target Azure Stack APIs - **Can you double-check that you've done this as well please?**
* Failed to copy a blob from public Azure --> Azure Stack Hub, `400 The value for one of the HTTP headers is not in the correct format.`
* Successfully copied a blob from Azure Stack Hub --> public Azure

Both used AzCopy, as seen below:
![image](https://user-images.githubusercontent.com/61973249/130758899-12b09f93-9f22-4b06-8a10-69f8bcd4fc70.png)

The version of AzCopy being used is **10.4.2**, as seen in the below screenshot:
![image](https://user-images.githubusercontent.com/61973249/130757091-a8971894-6a24-4935-a74c-2473d124331a.png)

One thing I've noticed is that you're getting a **500** error when trying to copy from Azure Stack --> public Azure, even on the later versions where I was getting a **400** error. This makes me think that there is something else on your end which is causing the copy to fail? Other than targeting the wrong APIs, I can't think of what else would cause this at the moment.

**Comment by cblackuk** [comment]
Hi @MRayermannMSFT, did you get my email? :-)

**Comment by MRayermannMSFT** [comment]
@cblackuk no I did not get your email. :( I've double checked and the address I gave is correct. Maybe I could email you?

**Comment by cblackuk** [comment]
@MRayermannMSFT sure - cblack@ukcloud.com

**Comment by MRayermannMSFT** [comment]
Sent!

**Comment by cblackuk** [comment]
Replied :-)

**Comment by wturner123** [comment]
Hi @MRayermannMSFT, I've been testing on v1.21.0 with the tweak that you sent over to Chris privately the other day (enforcing AzCopy for Stack operations).

Trying to copy blobs from either Stack --> Azure or Azure --> Stack fails both ways with the same errors. The first error in the log is like so:
```
2021/09/24 11:27:50 WARN: failed to initialize destination container bootdiagnostics-hypervtes-2000a91e-26e1-4354-b3ae-a0e5a4be4d2e; the transfer will continue (but be wary it may fail): -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.13.1-0.20210823171415-e7932f52ad61/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=) =====
Description=This request is not authorized to perform this operation.
RequestId:812f0906-e01e-0014-7c37-b14a4a000000
Time:2021-09-24T11:27:50.7522156Z, Details: 
   Code: AuthorizationFailure
   PUT https://hypervtestingdiag.blob.core.windows.net/bootdiagnostics-hypervtes-2000a91e-26e1-4354-b3ae-a0e5a4be4d2e?restype=container&se=2021-10-24t11%3A27%3A47z&sig=-REDACTED-&sp=rwl&sr=c&sv=2019-02-02&timeout=180
   User-Agent: [Microsoft Azure Storage Explorer, 1.21.0, win32, azcopy-node, 2.0.0, win32,  AzCopy/10.12.1 Azure-Storage/0.14 (go1.16; Windows_NT)]
   X-Ms-Client-Request-Id: [79d9c589-b46e-40e8-6f34-ad2fd8b1b257]
   X-Ms-Version: [2017-04-17]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation.
   Content-Length: [246]
   Content-Type: [application/xml]
   Date: [Fri, 24 Sep 2021 11:27:50 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Request-Id: [812f0906-e01e-0014-7c37-b14a4a000000]
   X-Ms-Version: [2017-04-17]
```
It's then followed afterwards by the 400 errors that we've seen before, like below:
```
2021/09/24 11:27:50 ==> REQUEST/RESPONSE (Try=1/4.3479ms, OpTime=38.2582ms) -- RESPONSE STATUS CODE ERROR
   GET https://<removed>/bootdiagnostics-w2019-30842ad8-3a6c-491b-9369-c03de772eefe/W2019.30842ad8-3a6c-491b-9369-c03de772eefe.serialconsole.log?comp=pagelist&se=2021-10-01t11%3A12%3A41z&sig=-REDACTED-&sp=rl&sr=c&st=2021-09-24t11%3A12%3A41z&sv=2019-02-02&timeout=901
   User-Agent: [Microsoft Azure Storage Explorer, 1.21.0, win32, azcopy-node, 2.0.0, win32,  AzCopy/10.12.1 Azure-Storage/0.14 (go1.16; Windows_NT)]
   X-Ms-Client-Request-Id: [7c5274af-146c-4242-5541-36de65c89308]
   X-Ms-Version: [2020-08-04]

   --------------------------------------------------------------------------------
   RESPONSE Status: 400 The value for one of the HTTP headers is not in the correct format.
   Content-Length: [328]
   Content-Type: [application/xml]
   Date: [Fri, 24 Sep 2021 11:27:50 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
   X-Ms-Request-Id: [6ea523fb-0b93-021b-5005-db434b2d19c9]
Response Details: ﻿<Code>InvalidHeaderValue</Code><Message>The value for one of the HTTP headers is not in the correct format. </Message><HeaderName>x-ms-version</HeaderName><HeaderValue>2020-08-04</HeaderValue>
```

I've attached the full sanitised log for reference: [4716bc72-400c-ab44-6333-5d9db2d53472.log](https://github.com/microsoft/AzureStorageExplorer/files/7226717/4716bc72-400c-ab44-6333-5d9db2d53472.log)

Chris is out of office for the next week, so if you'd like to discuss anything privately then please email me at wturner@ukcloud.com

**Comment by MRayermannMSFT** [comment]
I finally got the AzCopy private build! Better late than never I guess. I'll get something to y'all as soon as I have a chance.

**Comment by MRayermannMSFT** [comment]
I've spend the past day doing some testing and I have both good news and bad news.
- Good news: the fix the AzCopy team gave me works. From what I see in Fiddler, AzCopy is now respecting the API version we use for all API calls.
- Bad news: for small files, AzCopy is using an API from a version that is not supported by any version of Azure Stack at this time.

So, with that in mind, I think we could still get some value via y'all validating the "good news" against your Azure Stack setup. Just when you do, you'll need to use large files. Think in the size range of like ~100 MB or more. 

Also, I've upped the API version we use for Azure Stack from 2017-04-17 to 2019-07-07. Hopefully that works out good. :)

Here's a build: https://storageexplorerpublish.blob.core.windows.net/privatebuilds/4464/StorageExplorer-ia32.exe

That should install Storage Explorer with build number: 
![image](https://user-images.githubusercontent.com/21112697/144689693-538a9627-cb90-4cd4-88dc-9f13123ac107.png)

**Comment by wturner123** [comment]
Thanks for the update.

So I've been testing and I'm seeing some odd results.

With a 200MB text file, copying from Stack --> Azure or Azure --> Stack fails, as well as cloning within a Stack container:
![image](https://user-images.githubusercontent.com/61973249/145006360-c01fad18-f5d7-4d40-937d-b79140ed68aa.png)

But with a smaller ~1MB file, cloning works from Stack --> Azure, but not the other way round.

Fiddler confirms that all the requests are using the API version 2019-07-07.

Either way, is it possible to change the API version for Azure Stack operations to 2019-06-01? This is based on the resource provider API version for the latest Azure Stack Hub API profile, which lists version 2019-06-01 for the storage provider. [As seen here](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-profiles-azure-resource-manager-versions?view=azs-2102#overview-of-the-2020-09-01-hybrid-profile).

Let me know what you think. Happy to collect more logs/info if needed.

**Comment by MRayermannMSFT** [comment]
> With a 200MB text file, copying from Stack --> Azure or Azure --> Stack fails, as well as cloning within a Stack container:

> But with a smaller ~1MB file, cloning works from Stack --> Azure, but not the other way round.

For each of these, can you post the AzCopy log files? And if you could send Fiddler traces to the email address I shared before that'd be cool too.

> Either way, is it possible to change the API version for Azure Stack operations to 2019-06-01? This is based on the resource provider API version for the latest Azure Stack Hub API profile, which lists version 2019-06-01 for the storage provider. As seen here.

The API for that "API version" is the management level Storage API. The API I'm referring to is the service API, and the value I I picked is the latest service version supported by stack 2008. For management API though, the private build does include an upping of the management API version from 2016-01-01 to 2018-02-01, which is the latest management version supported by stack 2008. But that shouldn't have any effect on AzCopy operations.

Here's the full list of what is supported by the various Azure Stack versions: https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-acs-differences?view=azs-2102#api-version

**Comment by wturner123** [comment]
> The API for that "API version" is the management level Storage API. The API I'm referring to is the service API, and the value I I picked is the latest service version supported by stack 2008. For management API though, the private build does include an upping of the management API version from 2016-01-01 to 2018-02-01, which is the latest management version supported by stack 2008. But that shouldn't have any effect on AzCopy operations.

Ah I see, thanks for clarifying.

> For each of these, can you post the AzCopy log files? And if you could send Fiddler traces to the email address I shared before that'd be cool too.

I've sent over a zip containing all the AzCopy log files and Fiddler traces for various scenarios to the sehelp email and cc'd you in just in-case. Let me know if you haven't received these for some reason.

One odd thing that I only noticed today when collecting these is that the Stack --> Azure copy only worked with a ~0.042mb (42kb) file, and did not work with either a 0.6mb or 200mb file. Every other transfer failed.

**Comment by MRayermannMSFT** [comment]
@wturner123 I got the logs! I know where I need to go investigate next, will get back to you once I have more info.

**Comment by MRayermannMSFT** [comment]
@wturner123 quick update for you. Turns out that although Azure Stack now supports newer storage API versions, that support is not quite...real. Apparently that "support" is just meant to unblocks apps with user newer API versions but not any APIs from them. Or in other words, the support does include implementing any new APIs that come with the API version. 😡 So that's of no help to us because AzCopy exclusively uses "new" APIs for service to service transfers!

I'll be talking with the AzCopy team to see if we can find a solution independent of Stack, and I'm going trying to find out from the stack team when the heck they'll actually support the API versions they claim to support.

**Comment by MRayermannMSFT** [comment]
Hey all, after much discussion among various teams, there isn't going to be any more progress on this issue. We couldn't find a path forward for AzCopy to support "public Azure" -> "Azure Stack" copies or vice versa. Therefore, you will need to download data from your source to an intermediate location, and then upload back to your destination. If you have any feedback regarding this decision, the best place to send that will be your Azure Stack feedback channels. We have provided all feedback from here to the relevant teams, and going forward it will be best for y'all to provide that directly to them.
