### ISSUE TITLE
Gen2 Move Path Does Not Work For Non-Root Paths That Start With /

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#4465]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.0

### Platform

Windows

### Architecture

x64

### Regression From

1.17.0

### Bug Description

Move a file or folder in gen2 to a non-root directory, start the path in the dialog box with a slash.

### Steps to Reproduce

See description.

### Actual Experience

It doesn't work.

### Expected Experience

It should work.

**Comment by MRayermannMSFT** [comment]
@v-xianya @v-limu while I'm working on a fix for this, can y'all add a (p1 or p2) test case for this? Basically, for Gen2 rename, it should not matter if what you input starts/ends with a / or not.

For example, if I'm moving `.DS_Store` into `test`:
![image](https://user-images.githubusercontent.com/21112697/118724171-215af380-b7e3-11eb-80e3-995b00340d1e.png)
All of these inputs should work:
- `untitled folder/test`
- `/untitled folder/test`
- `untitled folder/test/`
- `/untitled folder/test/`

**Comment by v-xianya** [comment]
@MRayermannMSFT 
Got it. thank you for the reminder. we added this to regular test cases and marked as P1.

**Comment by v-xianya** [comment]
Verified this issue on the latest build 20210521.3. Fixed.
