### ISSUE TITLE
Support CopyBlob for archived blobs

### ISSUE THREAD

**Issue by fhryo-msft** [microsoft/AzureStorageExplorer#4466]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

SetBlobTier would change the tier of archived blobs directly. Potentially it involves early deletion penalty.

### Desired Solution

Support CopyBlob to read archived blobs to avoid early deletion penalty.

**Comment by MRayermannMSFT** [comment]
Duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/1950
