### ISSUE TITLE
The location of the toolbar sub-menus show unfriendly on Linux

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#4467]
**Storage Explorer Version:** 1.20.0-dev
**Build Number:** 20210518.7
**Branch**: main
**Platform/OS**: Linux Ubuntu 16.04/18.04
**Architecture**: x64
**How found**: From running test case
**Regression From**: Previous build (20210511.3)

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Open one blob container -> Click 'Upload' -> Observe the sub-menus.
3. Check whether the location of the sub-menus show friendly. 

## Expected Experience ##
The location of the sub-menus show friendly.

## Actual Experience ##
The location of the sub-menus show unfriendly.
On Ubuntu 16.04:
![image](https://user-images.githubusercontent.com/54055206/118622903-4f97fd80-b7fa-11eb-8a50-f579a187c030.png)
On Ubuntu 18.04:
![image](https://user-images.githubusercontent.com/54055206/118622954-5c1c5600-b7fa-11eb-90c0-c0468adb17d9.png)

## Additional Context ##

1. This issue reproduces for other buttons with sub-menus.
2. This issue also reproduces for one file share/queue/table.

**Comment by JasonYeMSFT** [comment]
I downloaded the same build and I was able to reproduce it. However, at some point, it suddenly stops reproducing?! I didn't do anything in between and I have no idea what happened. Could you please check if you can reproduce it consistently in a VM and share it with us?

**Comment by v-limu** [comment]
Hi @JasonYeMSFT I verified on the lasted build main/20210518.9. 

1. On Linux 16.04: This issue reproduces consistently. I share the VM with you on Teams.
2. On Linux 18.04: This issue reproduces inconsistently.

**Comment by craxal** [comment]
@v-limu I also can't reproduce consistently on Linux 20.04. It only seems to happen early on first launch, and I can't really get it to happen again afterwards. If you folks can find a reliable way to reproduce, let's revisit.

**Comment by v-limu** [comment]
Hi @craxal  We will pay attention to this issue in testing. if we find a reliable way to reproduce and we will report you.
