### ISSUE TITLE
There is no traffic for some operations when the proxy setting is 'Use system proxy (preview)'

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#4468]
**Storage Explorer Version:** 1.20.0-dev
**Build Number:** 20210518.6
**Branch**: main
**Platform/OS**: Windows 10
**Architecture**: x32
**How found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##

1. Launch Fiddler.
2. Create a clean virtual machine ->  Install and launch Storage Explorer.
3. Click 'Edit' menu -> Select 'Configure Proxy -> Use system proxy (preview)'.
4. Expand one storage account -> Blob Containers.
5. Open one blob container with blobs -> Click 'Folder Statistics'.
6. Check there is traffic in Fiddler.

## Expected Experience ##
There is traffic in Fiddler.

## Actual Experience ##
There is no traffic in Fiddler.

## Additional Context ##

1. This issue also reproduces when clicking 'Selection Statistics' for one blob container.
2. This issue also reproduces when clicking 'View Messages' for one queue.
3. This issue also reproduces **unstably** when clicking 'Dequeue' for one queue.
4. This issue also reproduces **unstably** for the 'Listing resource groups' action.

**Comment by MRayermannMSFT** [comment]
@v-limu

Folder & Selection Statistics: I cannot repro no network calls for these actions. I am always seeing at least one network call.

View Message: we should remove this from the list of features to "check for network activity". When you click "View Message" we don't actually make any network calls. My apologies.

Dequeue: can you describe what you mean by unstably? I am always seen at least a DELETE request in Fiddler:
![image](https://user-images.githubusercontent.com/21112697/118687206-9a455580-b7b9-11eb-9618-daabc0e17adf.png)

Listing resource groups: can you describe what you mean by unstably? If you mean you don't see any when clicking "Load more", then that's probably something we should note down as expected. The following goes true for any "Load more" in the tree view. When you click "Load more", the newly loaded things may have already been retrieved from Azure, and the "Load more" is just creating the nodes for those already retrieved things. I think technically, the only time it is guaranteed that you'll see a network call for loading nodes in the tree view is for the first load. It is possible to see it later, but the first load is a for sure.

**Comment by v-limu** [comment]
Hi @MRayermannMSFT Verified on build main/20210518.9. The mean of 'unstably' is that we executing multiple times for these actions. The traffic doesn't show every time.
1. Folder & Selection Statistics: We can see some network calls for this actions. But may be related to the network, sometimes there is no traffic. Please see the record:
![sts](https://user-images.githubusercontent.com/54055206/118795817-9571c600-b8cd-11eb-8fc6-d85c030d720b.gif)
2. View Message: OK, Got it. Thanks for your updates! We will remove this action from the list of features to "check for network activity" testing.
3. Dequeue: The traffic is not always visible every time when it is executed.
4. Every thing is clear for 'Listing resource groups'. Thanks your updates!

**Comment by MRayermannMSFT** [comment]
@v-limu

Can you go into Fiddler, go to Tools -> Options, and then check the first two checkboxes and restart. Try the test again, you should be seeing traffic that shows up in a darker text color. It looks like you're only seeing the "Tunnel" traffic. If after that you still don't see more stuff, you may also have to click Actions -> Trust Root Certificate, and then restart and try again.

![image](https://user-images.githubusercontent.com/21112697/119205404-025f9a00-ba4d-11eb-9e5b-439e2d83fd6f.png)

Let me know how that goes.

**Comment by v-limu** [comment]
Hi @MRayermannMSFT Thanks for your guide! We follow the below settings to verify Folder & Selection statistics actions and Dequeue action. Everything works well and we can see traffic that shows up in a darker text color.

1. Go to Fiddler -> Tools -> Check the first two checkboxes. 
2. Click Actions -> Trust Root Certificate and restart.
3. Execute those actions.

So this issue doesn't reproduce and we close it.
