### ISSUE TITLE
Cannot log into multiple Azure accounts

### ISSUE THREAD

**Issue by aleonard763** [microsoft/AzureStorageExplorer#4469]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.1

### Platform

Windows

### OS Version

Windows 10

### Architecture

x64

### Build Number

20210425.1

### Regression From

1.16.0

### Bug Description

I am unable to connect to a second account. This is likely due to the newer login process using a browser instead of the previous standalone login dialog.

### Steps to Reproduce

1. Launch Storage Explorer.
2. Connect to an account.
3. Attempt to connect to a different account.

### Actual Experience

A message appears in the browser stating "Something went wrong
There is a problem with your Microsoft account. To fix this, sign in to account.live.com from a browser." 
The only way I know to "sign in to account.live.com from a browser" is to change my Windows default browser, something I am unwilling to do.

### Expected Experience

My login attempt succeeds - as in the past - and I am able to connect to multiple accounts in Storage Explorer.

**Comment by MRayermannMSFT** [comment]
Hi @aleonard763 

While we encourage you to use the default browser option, if you really do need to go back to the old way of sign in (the smaller dialog box), you can do that in our settings. Please read the following documentation for more info: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-sign-in#changing-where-sign-in-happens

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you need additional help please open a new issue.
