### ISSUE TITLE
The font colors are inconsistent between temporary and permanent tabs under Dark theme

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#447]
**Storage Explorer Version**: 1.3.1
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180717.9
**Commit**: 293c2d62 
**Regression** From: Not a Regression

#### Steps to Reproduce: ####
1. Change the current theme to Dark.
2. Open two blob containers in sequence(Displays as permanent tabs) -> Single click another blob container(Displays as temporary tab).
3. Focus on the second permanent tab -> Check the font color between the first permanent tab and the temporary tab.

#### Expected Experience: ####
The font colors are consistent.

#### Actual Experience: ####
The font colors are inconsistent.
![color](https://user-images.githubusercontent.com/34729022/42872905-a23c01fc-8a6d-11e8-9e20-2df2ba75bdd1.png)

1. This issue doesn't reproduce on other themes.
2. It displays a consistent color after focusing on the temporary tab.

**Comment by craxal** [comment]
I don't think this is a big deal. Temporary tabs are different already, so a slight color difference isn't that out of place.
