### ISSUE TITLE
Unable to Connect to Blob Storage through MS Storage Explorer

### ISSUE THREAD

**Issue by mandeep051186** [microsoft/AzureStorageExplorer#4471]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.1

### Platform

Windows

### OS Version

Windows 10

### Architecture

x64

### Build Number

20210425.1

### Bug Description

Unable to retrieve child resources.

Details:
{
  "name": "TypeError",
  "message": "Only absolute URLs are supported",
  "stack": "TypeError: Only absolute URLs are supported\n    at getNodeRequestOptions (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1305:9)\n    at C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1410:19\n    at new Promise (<anonymous>)\n    at fetch (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1407:9)\n    at NodeFetchHttpClient.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:2708:39)\n    at step (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.next (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:124:57)\n    at C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:117:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:113:16)"
}

### Steps to Reproduce

Launch Storage Explorer
Connect to Blob with name and key
Then am receiving the above error

### Actual Experience

unable to access Blob Storage

### Expected Experience

Should be able to access

### Additional Context

```text
NA, you can contact me on +919844596040 if needed.
```

**Comment by MRayermannMSFT** [comment]
@mandeep051186 you say you are using name and key. Does that mean you went through this screen?
![image](https://user-images.githubusercontent.com/21112697/119384241-3e774280-bc79-11eb-8281-198c798e91c9.png)
Or did you instead provide your own connection string?

**Comment by MRayermannMSFT** [comment]
@mandeep051186 Could you also please share your Storage Explorer logs? See here for [info](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#storage-explorer-logs) on how to get those.

**Comment by mandeep051186** [comment]
Yes, I went through this screen and not through connection string. Thanks.

*Warm Regards*,

*Mandeep A Kumar* | MBA | +91 98445 96040 ***@***.*** |
***@***.*** ***@***.***>



*P **Please consider the environment before printing this e-mail*

*Have a Great Day!!!!!!*

**Comment by JasonYeMSFT** [comment]
@mandeep051186 Could you please share the log with us?

**Comment by mandeep051186** [comment]
Sorry I am unable to get the logs, it would be great if we could get into a
call and sort this out. Thanks.

*Warm Regards*,

*Mandeep A Kumar* | MBA | +91 98445 96040 ***@***.*** |
***@***.*** ***@***.***>



*P **Please consider the environment before printing this e-mail*

*Have a Great Day!!!!!!*

**Comment by MRayermannMSFT** [comment]
@mandeep051186 we would want to look at logs first before considering the possibility of a phone call. Here are instructions on how to grab the logs we need: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#storage-explorer-logs

For this issue, you probably do not need to modify the log level.

**Comment by mandeep051186** [comment]
Hi Matthew,

Attached is the logs for your reference, thanks.


*Warm Regards*,

*Mandeep A Kumar* | MBA | +91 98445 96040 ***@***.*** |
***@***.*** ***@***.***>



*P **Please consider the environment before printing this e-mail*

*Have a Great Day!!!!!!*

**Comment by MRayermannMSFT** [comment]
@mandeep051186 unfortunately your logs did not get sent. To attach files to an issue, you must go to github.com (aka https://github.com/microsoft/AzureStorageExplorer/issues/4471) and drag and drop the attachments. You can not add files via email reply.

**Comment by mandeep051186** [comment]
Attached is the log for your reference, let me know if this helps, thanks.
[ca4ecc2e-AadAccountProviderClient-57508-ai57sx-57508-1.log](https://github.com/microsoft/AzureStorageExplorer/files/6985980/ca4ecc2e-AadAccountProviderClient-57508-ai57sx-57508-1.log)

**Comment by MRayermannMSFT** [comment]
@mandeep051186 there should have been more than 1 file in that folder. Are you sure that was the only one?

**Comment by mandeep051186** [comment]
Yes,  I could find only this file. Thanks.

**Comment by JasonYeMSFT** [comment]
@mandeep051186 Please try to upgrade to the latest version to see if it still has the issue. The logs you shared is the authentication log, not Storage Explorer logs. To find Storage Explorer logs, you can use App Menu > Help > Open Logs Directory. If your current session had reproduced the issue, the most recent directory should contain the correct log files.
