### ISSUE TITLE
There is a background color for the last property value on 'Properties' panel after switching to the next item by pressing 'Tab'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4478]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 20210519.5
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ MacOS Big Sur 11.3
**Architecture**: ia32/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Select one item which has properties on its Properties panel (Like one queue).
2. Press 'Tab' to switch among the current items.
3. After switch from the last property value on the Properties panel to the next item.
4. Check there is no background color for the last property value.

## Expected Experience ##
There is no background color for the property value.

## Actual Experience ##
There is a background color for the property value.
![image](https://user-images.githubusercontent.com/41351993/118955317-29f12c80-b991-11eb-8398-0a3548f80ca6.png)

**Comment by craxal** [comment]
The property values are displayed in `<input>` elements, which are in part styled by the system. Try as I might, I can't modify the color of the selection in an obvious manner, nor can I programmatically remove the selection range.

I noticed the text highlight goes away when focus wraps back around into Cloud Explorer from the top and comes back after Shift-tabbing out again. It's possible this is a weird quirk with the Cloud Explorer iframe.

**Comment by craxal** [comment]
Turns out the weird behavior is somehow related to the fact that the inputs are read-only. However, the selection color can be fixed with a combination of `input::selection` and `input:focus::selection` CSS selector.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220410.3. Fixed,
