### ISSUE TITLE
There are no expanded icon for the sub-nodes under one subscription after reauthenticating an azure account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4480]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 20210521.3
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ MacOS Big Sur 11.3
**Architecture**: ia32/x64
**How Found**: Exploratory testing
**Regression From**: Previous release(1.18.1)

## Steps to Reproduce ##
1. Reauthenticate one azure account -> Check the subscription which was applied before the account expires.
2. Click 'Open Explorer' -> Check the sub-nodes under the subscription.
3. Check whether there are expanded icons for the sub-nodes.

## Expected Experience ##
There are expanded icons for the sub-nodes or the sub-nodes auto refresh.
![image](https://user-images.githubusercontent.com/41351993/119076936-04fac900-ba26-11eb-83a0-c34196ecf86f.png)

## Actual Experience ##
There is no expanded icon for the sub-node.
![image](https://user-images.githubusercontent.com/41351993/119076008-65890680-ba24-11eb-9b62-eaaad72c0772.png)

**Comment by MRayermannMSFT** [comment]
Should look into doing:

- AuthPanel -> tenant.reAuthenticate
- after reAuthenticate returns, call into Azure Provider which can call "refresh'' on any subscription nodes which belong to the account/tenant that was reauthenticated

**Comment by MRayermannMSFT** [comment]
I looked into this and got some work done but I have not had time to test my fix. Going to move this into 1.21

**Comment by MRayermannMSFT** [comment]
I merged what I believe is a fix for this. @v-xianya  please verify

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20210816.1.Fixed.
