### ISSUE TITLE
The number of the displayed tables are changed constantly when refreshing 'Tables' node multiple times

### ISSUE THREAD

**Issue by v-haiz** [Microsoft/AzureStorageExplorer#449]
**Storage Explorer Version**: 1.3.1
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180717.9
**Commit**: 633ce83b
**Regression From**: Previous release 1.3.1(20180711.1)

**Steps to Reproduce**:
1. Expand one **Tables** which contains two tables at least->Refresh the Tables node .
2. Check the number of the displayed tables under Tables node.     

**Expected Experience**:
The number of displayed tables are invariant.

**Actual Experience**:
The number of displayed tables are changed constantly. ~~Please see the video from: DELETED.~~

**Comment by craxal** [comment]
Highly unusual. Does this happen for different accounts? What kinds of accounts/subscriptions are involved?

**Comment by v-haiz** [comment]
@craxal This issue happens for all accounts with Azure Tools Manual Testing1/Azure Tools Manual Testing 2.

**Comment by MRayermannMSFT** [comment]
Fix merged into master.

**Comment by craxal** [comment]
For reference, this issue was we weren't holding on to the aggregate collection of promises running the list table operations, so an asynchronous operation was returning prematurely with fewer tables than expected.
