### ISSUE TITLE
An error pops up after restarting Storage Explorer then reopening the 'Proxy Settings' dialog (the previous saved setting is 'Do not use proxy' and the saved port is empty)

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#4490]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 20210524.7
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ MacOS Big Sur 11.3
**Architecture**: ia32/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##

1. Launch Storage Explorer -> Click 'Edit' menu -> Click 'Configure Proxy'.
2. Select 'Use app proxy settings' -> Delete the value of the 'Port' -> Switch to 'Do not use proxy' -> Click 'OK'.
3. Restart Storage Explorer -> Click 'Edit' menu -> Click 'Configure Proxy'.
4. Check whether the 'Proxy Settings' dialog pops up.

## Expected Experience ##
The 'Proxy Settings' dialog pops up.

## Actual Experience ##
The 'Proxy Settings' dialog doesn't pop up and an error pops up.
 
![image](https://user-images.githubusercontent.com/54055206/119469200-b5940000-bd79-11eb-9ff1-01fca0f84602.png)

**Comment by craxal** [comment]
@v-limu We recently merged a significant change to our proxy features and functionality. Can you run this again to see if the bug reproduces?

**Comment by v-xianya** [comment]
@craxal we are blocked to reproduce this bug by the new issue [4690 ](https://github.com/microsoft/AzureStorageExplorer/issues/4690).

**Comment by v-xianya** [comment]
Verified this issue on the build 20210730.1. Fixed.
