### ISSUE TITLE
Unable to authenticate properly after adding the self signed certificates

### ISSUE THREAD

**Issue by lchave** [microsoft/AzureStorageExplorer#4491]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.1

### Platform

Windows

### OS Version

Windows 10

### Architecture

x64

### Build Number

19043.985

### Bug Description

{
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"self signed certificate in certificate chain\\\",\\n  \\\"stack\\\": \\\"Error: self signed certificate in certificate chain\\\\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1484:34)\\\\n    at TLSSocket.emit (events.js:310:20)\\\\n    at TLSSocket._finishInit (_tls_wrap.js:927:8)\\\\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:697:12)\\\",\\n  \\\"code\\\": \\\"SELF_SIGNED_CERT_IN_CHAIN\\\"\\n}\""
}

### Steps to Reproduce

1. Launch explorer when needing to re-authenticate
2. Enter credentials for Azure ADa and confirm the authentication completed in the browser. 
3. Return to Storage Explorere Account Management and see the error where could not access resources for this tenenat. Need to re-authticate

### Actual Experience

I'm unable to access resources using this tool.

### Expected Experience

NA

**Comment by JasonYeMSFT** [comment]
Have you followed [troubleshooting](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#error-self-signed-certificate-in-certificate-chain-and-similar-errors) to add your self signed local certificate to Storage Explorer's trusted list?

**Comment by lchave** [comment]
Yes, the self-signed certs have been uploaded into the Storage explorer. Still experiencing the same issue.

**Comment by MRayermannMSFT** [comment]
@lchave can you confirm that the certs are in a base64 format? The easiest way to confirm is to just open it in a text editor, and then you should see something like this:
![image](https://user-images.githubusercontent.com/21112697/121062060-7aca9880-c779-11eb-9641-ae944ea536cb.png)

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still have problems, please open a support ticket from the Azure portal, or open a new issue here. Thanks.

**Comment by jglisson** [comment]
I am receiving this same error. I have imported the self-signed cert into Storage Explorer as described in the troubleshooting guide, but am still getting the error. I have confirmed the cert looks like the screenshot above. I copied/pasted the cert from OpenSSL like the troubleshooting guide describes.

Any other tips?
