### ISSUE TITLE
There is a blank line in the dropdown list of the 'Operator' part for one table

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4492]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 20210526.1
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ MacOS Big Sur 11.3
**Architecture**: ia32/x64
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Click 'Query' -> Click 'Add new clause'.
3. Expand the dropdown list of the 'Operator' part.
4. Check there is no blank line. 

## Expected Experience ##
There is no blank line.

## Actual Experience ##
There is a blank line.
![Screen Shot 2021-05-26 at 3 00 54 PM](https://user-images.githubusercontent.com/41351993/119616424-2cd99a80-be33-11eb-9105-66cc7cd866b0.png)

**Comment by craxal** [comment]
So...the blank is is due to a literal empty string added at the end of the array containing the options. No idea why it was put there.
