### ISSUE TITLE
The entire table is reset after executing the action 'Reset Column Order'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4493]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 20210526.1
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ MacOS Big Sur 11.3
**Architecture**: ia32/x64
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Add more than one entity.
3. Reorder the 'PartitionKey' column -> Switch the order of the 'RowKey' and 'Timestamp' columns.
4. Right click the 'PartitionKey' property on the table -> Click 'Reset Column Order'.
5. Check the result.

## Expected Experience ##
1. The 'PartitionKey' column is reset.
2. The order of the 'RowKey' and 'Timestamp' columns is not reset.

## Actual Experience ##
The entire table is reset.
1. The 'PartitionKey' column is reset.
2. The order of the 'RowKey' and 'Timestamp' columns is reset.

**Comment by JasonYeMSFT** [comment]
This is by design. The 'Reset Column Order' button will reset the column order of all columns and the row ordering to the default state.
