### ISSUE TITLE
Support Archive Priority Update on Rehydration

### ISSUE THREAD

**Issue by fhryo-msft** [microsoft/AzureStorageExplorer#4494]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Archive storage supports priority update on blobs that are being rehydrated with SetBlobTier. We need to surface this capability to customers as well.

### Desired Solution

For blobs that are being rehydrated, ASE allows customers to change priority from standard to high.

**Comment by JasonYeMSFT** [comment]
We will consider this for 1.22.0 milestone.

**Comment by JasonYeMSFT** [comment]
Storage Explorer has already supported setting rehydration priority and checking them in the Properties dialog. As suggested, we can show those information in the Set Access Tier dialog and the priority information in the activity.

**Comment by fhryo-msft** [comment]
it would be awesome! thanks for the support.
