### ISSUE TITLE
Blob path navigation, enter path text in blob Location field

### ISSUE THREAD

**Issue by OzBob** [microsoft/AzureStorageExplorer#45]
**Storage Explorer Version:** 1.0.0

**OS Version:** Windows 10

**Enhancement:**
1. Navigate to Blob Containers
2. Open Container
3. Container name displayed
4. OPTION: enter in blob path directly input next to search
![image](https://user-images.githubusercontent.com/1796771/38916337-965ab266-4319-11e8-8219-0ecbff768bc9.png)

This works well for if there are many pages of blobs to navigate through until 'my blob' is found. 
Especially useful if it is a 'folder' e.g. \\container\blobfolder\blobfile1.json

**Comment by JakeRadMSFT** [comment]
#136 also wanted to work with the address bar.

Expected Experience: 
Should be able to edit it, paste in new path and the explorer should navigate to the pasted in path if it is valid

**Comment by MRayermannMSFT** [comment]
This will be included in 1.15!
