### ISSUE TITLE
Copy never completes when copying attached blob container to another account

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#450]
**Storage Explorer Version**: 1.3.1
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180717.9
**Commit**: 293c2d62 
**Regression** From: Previous release 1.3.1(20180711.1)

#### Steps to Reproduce: ####
1. Create a SAS URL for one blob container.
2. Open the Connect dialog and attach the container using the SAS URL. 
3. Expand the Local & Attached > Storage Accounts > (SAS-Attached Services) > Blob Containers nodes and copy the attached blob container to other accounts.
4. Check whether the attached blob container can be copied successfully or not.

#### Expected Experience: ####
The attached blob container can be copied successfully.

#### Actual Experience: ####
Keep copying more than 10 mins when coping it to another account.
![loding](https://user-images.githubusercontent.com/34729022/42873812-5b81f512-8a6f-11e8-9a1c-e41cf48623aa.png)

**Comment by craxal** [comment]
Are there any console messages or errors to go on?

**Comment by v-xuanzh** [comment]
No any error occurs and the status is going on.

**Comment by v-xianya** [comment]
Verified on build 20190104.2. This issue doesn't reproduce. Could you help to resolve it?

**Comment by jinglouMSFT** [comment]
closing.
