### ISSUE TITLE
SSLV3_ALERT_CLOSE_NOTIFY error

### ISSUE THREAD

**Issue by EtienneCoumont** [microsoft/AzureStorageExplorer#4501]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.1

### Platform

Windows

### OS Version

Windows 10

### Architecture

x64

### Build Number

20210425.1

### Bug Description

Hello,

I am unable to retrieve the blob containers of my storages.
I have checked that I have no proxy or weird internet settings.
Could you please tell me what I can do ?

Thank you,

Etienne

Unable to get child resources
Details :
{
  "name": "FetchError",
  "message": "request to https://***.blob.core.windows.net/?include=metadata&comp=list failed, reason: write EPROTO 245231464:error:100003e8:SSL routines:OPENSSL_internal:SSLV3_ALERT_CLOSE_NOTIFY:../../third_party/boringssl/src/ssl/tls_record.cc:592:SSL alert number 0\n",
  "stack": "FetchError: request to https://***.blob.core.windows.net/?include=metadata&comp=list failed, reason: write EPROTO 245231464:error:100003e8:SSL routines:OPENSSL_internal:SSLV3_ALERT_CLOSE_NOTIFY:../../third_party/boringssl/src/ssl/tls_record.cc:592:SSL alert number 0\n\n    at ClientRequest.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1461:11)\n    at ClientRequest.emit (events.js:310:20)\n    at TLSSocket.socketErrorListener (_http_client.js:426:9)\n    at TLSSocket.emit (events.js:310:20)\n    at errorOrDestroy (internal/streams/destroy.js:108:12)\n    at onwriteError (_stream_writable.js:424:5)\n    at onwrite (_stream_writable.js:445:5)\n    at internal/streams/destroy.js:50:7\n    at TLSSocket.Socket._destroy (net.js:677:5)\n    at TLSSocket.destroy (internal/streams/destroy.js:38:8)",
  "type": "system",
  "errno": "EPROTO",
  "code": "EPROTO"
}

### Steps to Reproduce

Login to Azure account is ok.
Storages are listed correctly.
Error happen when I try to list the Blob containers.

### Actual Experience

I am unable to retrieve the blob containers of my storages.

**Comment by EtienneCoumont** [comment]
OK. Windows Update told me I was up to date, but when I forced the check it proposed an update for .Net framework 3.5 and 4.8. After install and reboot the above issue seems to be solved.

Hope it helps if someone encounter the same issue. :)

**Comment by JasonYeMSFT** [comment]
Since it is mitigated, we are going to close the issue. Please let us know if you still run into any issue later on.
