### ISSUE TITLE
Could not access resources for this tenant. You may need to reauthenticate. See the error details for more information.

### ISSUE THREAD

**Issue by tyagia-HPdev** [microsoft/AzureStorageExplorer#4506]
{
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"connect ETIMEDOUT 13.71.173.192:443\\\",\\n  \\\"stack\\\": \\\"Error: connect ETIMEDOUT 13.71.173.192:443\\\\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)\\\",\\n  \\\"errno\\\": \\\"ETIMEDOUT\\\",\\n  \\\"code\\\": \\\"ETIMEDOUT\\\",\\n  \\\"syscall\\\": \\\"connect\\\",\\n  \\\"address\\\": \\\"13.71.173.192\\\",\\n  \\\"port\\\": 443\\n}\""
}

**Comment by JasonYeMSFT** [comment]
Are you using a proxy? It seems that you are trying to connect to a proxy server but didn't get a response. Also could you provide the basic information for
- Which version of Storage Explorer are you using?
- What OS you are using?
- What are the steps you take before you see this error?

**Comment by chaoqinglin** [comment]
Recently I somehow cannot connect to Azure storage server, even reinstall the new Azure version,  remove the account and reset the personal signing info, but still encounter the error below:
1. connect to Blob Container and presents below error:
The resource you are attempting to access is in a tenant which is currently filtered out. Un-filter it to access this resource.
2. open account management and observe below error:
Could not access resources for this tenant. You may need to reauthenticate. See the error details for more information.
click "Error details", show the error info below:
{
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"connect ETIMEDOUT 52.231.19.208:443\\\",\\n  \\\"stack\\\": \\\"Error: connect ETIMEDOUT 52.231.19.208:443\\\\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)\\\",\\n  \\\"errno\\\": \\\"ETIMEDOUT\\\",\\n  \\\"code\\\": \\\"ETIMEDOUT\\\",\\n  \\\"syscall\\\": \\\"connect\\\",\\n  \\\"address\\\": \\\"52.231.19.208\\\",\\n  \\\"port\\\": 443\\n}\""
}

Storage Explorer ver:1.19.1
OS:18363.1556
how to encounter this issue: 
open Storage Explorer and try to connect Blob Container, even without any proxy.
actually with the same configuration, i can connect the Blob container successfully two weeks ago, however i somehow cannot connect to blob container this week without any change.

**Comment by JasonYeMSFT** [comment]
@chaoqinglin Have you re-authenticated for that tenant?

**Comment by tyagia-HPdev** [comment]
@JasonYeMSFT... Many Thanks for looking into the issue.

Thanks for the follow-up ... for me this issue is resolved.

I tried with and without proxy but still can't connect but when i tried "use app proxy settings" it authenticated good and working now.



Which version of Storage Explorer are you using? Storage Explorer ver:1.19.1
What OS you are using? Win10 20H2 (19042.985)
What are the steps you take before you see this error?

**Comment by chaoqinglin** [comment]
@JasonYeMSFT ,
yes, i have re-authenticated for the tenant, but still not workable.

**Comment by chaoqinglin** [comment]
@JasonYeMSFT ,
after tried "use app proxy settings" and re-authenticated again, this issue gone. thanks a lot !
