### ISSUE TITLE
storage account can access data in blob storage with 'contributor' role only

### ISSUE THREAD

**Issue by manjubn64** [microsoft/AzureStorageExplorer#4507]
I have a storage account running in production and has only 'contributor' role. 
there is no data-place rules assigned. but it can enumerate blob storage operations like , put , get delate etc... 
How is this possible ? 
In the storage account log I see this as authenticated,
2.0;2021-05-28T10:56:40.3719911Z;PutBlob;Success;201;5;1;authenticated;storage account ; storage account ;blob;"https://storageaccount.blob.core.windows.net/azure-webjobs/heartbeats/

--> How is this possible ? 
--> How can I troubleshoot how storage account is getting permission to access data-plane data or enumerate blob storage only with 'contributor' role from control-plane.

**Comment by JasonYeMSFT** [comment]
If you sign-in to Portal and go to your storage account -> Access Control blade -> Roles -> "details" on the role you are interested in, you can see the full list of allowed/disallowed actions given by that role.

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response.
