### ISSUE TITLE
Queue Message Text column can't resize back to small

### ISSUE THREAD

**Issue by OzBob** [microsoft/AzureStorageExplorer#4508]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.1

### Platform

Windows

### OS Version

Windows 10

### Architecture

x64

### Build Number

20210425.1

### Bug Description

resizing column in Queue window does not reduce in size after it has been dragged to be very big

### Steps to Reproduce

Open Storage Explorer
Make window full size, 
Open Azure Storage Queue
Drag right hand column marker of Message Text column from default size to as big as it can go, pause, Drag more (it gets bigger).
Drag right hand column marker to the left, colum size snaps back to very big.
Double click right hand column marker , no change

### Actual Experience

![image](https://user-images.githubusercontent.com/1796771/120127643-830f5a80-c1f2-11eb-8bab-a83701769ac4.png)

### Expected Experience

As per classic win32/winRT grid view, double click when small should max to max column content or to max possible based on window size
double click when maximised should shrink to 'default' size.

### Additional Context

```text
Message Text is 4237 characters in length
```

**Comment by JasonYeMSFT** [comment]
@OzBob We recognize this is a problem. The cause of the problem lies in the data table library we are using and it is not easy to come up with a good solution quickly. We are planning to address it with all other data table related problems some time in the future.
