### ISSUE TITLE
Pop up an error when renaming one created new file share

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#451]
**Storage Explorer Version**: 1.3.1
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180717.9
**Commit**: 293c2d62 
**Regression** From: Not a Regression

#### Steps to Reproduce: ####
1. Expand one account then create a new file share.
2. Right click it and select 'Rename...'

#### Expected Experience: ####
No error dialog pops up after clicking 'Rename…'.

#### Actual Experience: ####
Pop up an error dialog after clicking 'Rename…'.
![error](https://user-images.githubusercontent.com/34729022/42874145-eb81b2ce-8a6f-11e8-992a-a191515adc8d.png)

This issue doesn't reproduce after refreshing the 'File Shares' node

**Comment by craxal** [comment]
Several of us are unable to repro. May have been fixed since then?
