### ISSUE TITLE
No file shows after pasting the path of one file in one folder to 'Search by prefix (case-sensitive)'

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#4510]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 20210601.2
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Big Sur 11.3
**Architecture**: ia32/x64
**How Found**: From exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> File Shares.
2. Open one file share -> Upload one folder with one file -> Right click the file -> Click 'Copy Path'.
3. Open one new tab for this file share -> Paste the copied path to 'Search by prefix (case-sensitive)'.
4. Check whether the file shows.

## Expected Experience ##
The file shows.

## Actual Experience ##
No file shows.
![image](https://user-images.githubusercontent.com/54055206/120284033-69533d80-c2ee-11eb-8cba-37df176e5be6.png)

## More Info ##
This issue doesn't reproduce for one blob container.
![image](https://user-images.githubusercontent.com/54055206/120284169-90aa0a80-c2ee-11eb-9558-f25158b03e53.png)

**Comment by craxal** [comment]
@v-limu File share search doesn't work the same way as blob search. It doesn't actually support prefix search to arbitrary directory depths. The search is actually implemented on our end by filtering the results of a List operation using a string comparison (`endsWith`).

@jinglouMSFT @JasonYeMSFT I'm inclined to leave this as Won't Fix unless we get user feedback about this. Thoughts?
