### ISSUE TITLE
Error when Connection to Subscription 

### ISSUE THREAD

**Issue by Megan060** [microsoft/AzureStorageExplorer#4512]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.1

### Platform

Windows

### Architecture

i86

### Build Number

20210425.1

### Bug Description

{
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"unable to get local issuer certificate\\\",\\n  \\\"stack\\\": \\\"Error: unable to get local issuer certificate\\\\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1484:34)\\\\n    at TLSSocket.emit (events.js:310:20)\\\\n    at TLSSocket._finishInit (_tls_wrap.js:927:8)\\\\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:697:12)\\\",\\n  \\\"code\\\": \\\"UNABLE_TO_GET_ISSUER_CERT_LOCALLY\\\"\\n}\""
}

### Steps to Reproduce

1. Go to Account Management
2. Reauthenticate now
3. Will pop up new tab to authenticate
4. Will error out.

### Actual Experience

The new window will pop open to authenticate but it always fails.

**Comment by chinumari** [comment]
Same issue has been observed after downloading the latest version of Azure Storage Explorer 1.19.

**Comment by JasonYeMSFT** [comment]
@chinumari A common cause of this error is the webserver not handling the certificates properly. Are you using a proxy server? If yes, could you verify if it is handling certificates properly? You can verify by directly connecting to resources without going through the proxy and see if it works.

**Comment by chinumari** [comment]
@JasonYeMSFT - Thanks for the reply.  I verified.  There is no proxy setup.   Also,  Yesterday,  the same system and same configuration was able to connect for few hours.  I was surprised.    Again the problem reappeared.   Any thoughts for troubleshooting ?

**Comment by JasonYeMSFT** [comment]
@chinumari If this is really a server issue, then maybe someone did something that mitigates the issue for a while (e.g. reboot) and then it reproduces on the server side. Or maybe your traffic goes through a different route which don't have a problematic server in the middle during that period of time. Even if you are not configuring a proxy, there is still a chance that some node in the route from your machine to Azure data center have problem handling certificates (e.g. company network gateway router). At this point, there is nothing we can do to help on the client side. There are certain things you can do to further investigate or even resolve the issue
- If you are in a company network or school network, ask your IT for help.
- Debug the network trace to locate at which point the certificates error is raised. Then contact the owner of the server to fix the problem.
- Try to use a VPN to force your network traffic to go through a different route. If that can mitigate the issue, it also confirms that the default network route is problematic.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you still need help, please either open a support ticket from the portal, or open a new issue here.
