### ISSUE TITLE
The string in the address bar overflows when the path is too long against one blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4517]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 20210602.8
**Branch**: main
**Platform/OS**: Windows 10/ MacOS Big Sur 11.3
**Architecture**: ia32/x64
**How Found**: Exploratory testing 
**Regression From**: Previous release (1.18.1)

## Steps to Reproduce ##
1. Expand one non-ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container with name 'blobcontainer01blobcontainer01blobcontainer01blobcontainer01' -> Create a folder with name 'anewvirtualblobdirectory'.
3. Upload a blob to the folder.
4. Click the address bar to show the path -> Click the blank part in the editor.
5. Press Tab.
6. Check the string in the address bar doesn't overflow.

## Expected Experience ##
The string in the address bar doesn't overflow.
![image](https://user-images.githubusercontent.com/41351993/120615086-7dcc3d00-c48a-11eb-8e70-9771fe2b5020.png)

## Actual Experience ##
The string in the address bar overflows.
![image](https://user-images.githubusercontent.com/41351993/120615049-71e07b00-c48a-11eb-8c18-f92b95dd1556.png)

## Additional Context ##
1. This issue doesn't reproduce on Linux Ubuntu 18.04.
2. Here is the video to reproduce this issue.
![testissue](https://user-images.githubusercontent.com/41351993/120619125-4790bc80-c48e-11eb-9c16-7bc7e1cb4dfc.gif)

**Comment by craxal** [comment]
@v-xianya I am not able to reproduce this. Can you please verify using the latest build?

**Comment by v-xianya** [comment]
@craxal Verified on the latest build main/20210610.4. Reproduce.
![image](https://user-images.githubusercontent.com/41351993/121456041-ff1a5700-c9d7-11eb-8e0c-46d0a75ec182.png)

**Comment by craxal** [comment]
@v-xianya OK, looks like there was a repro step missing. I can only get it to reproduce by tabbing after the address bar is in edit mode. Still works fine if I hit Enter or click elsewhere.

**Comment by v-xianya** [comment]
Hi @craxal thanks for being patience. 

Yes, this issue can be reproduced by pressing Tab when the address bar is in edit mode. And it works fine if press Enter.
BTW. I can still reproduce this issue by clicking on the blank part of the blob container's editor when the address bar is in edit mode.🙁
