### ISSUE TITLE
The blob displays in the destination blob container after pasting its folder which has the same name with the blob and only contains the blob

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4518]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 20210602.8
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ MacOS Big Sur 11.3
**Architecture**: ia32/x64
**How Found**: Exploratory testing 
**Regression From**: Previous release (1.12.0)

## Steps to Reproduce ##
1. Expand a storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Create a folder -> Type its name with the name of the blob.
4. Upload the same blob to the folder.
5. Copy the folder and paste it to another blob container.
6. Check whether the folder displays in the destination blob container.

## Expected Experience ##
The folder displays in the destination blob container.

## Actual Experience ##
The blob displays in the destination blob container.

##  Additional Context ##
This issue doesn't reproduce for one file share/ADLS Gen2 blob container.

**Comment by JasonYeMSFT** [comment]
This is a known issue of AzCopy. Currently AzCopy don't have the capability to transfer blobs and directories with the same name.

**Comment by JasonYeMSFT** [comment]
I merged a fix for this single blob/directory copy->paste scenario by tweaking AzCopy command. Due to the same limitation, cloning such a blob/directory where same name blob/directory both exists will still suffer from this issue. AzCopy will wait for customer feedback before prioritizing loosening that limitation.

**Comment by v-xianya** [comment]
Verified on the build 20210708.2. Fixed.
