### ISSUE TITLE
Why you guys are deprecating cosmos Support ? 

### ISSUE THREAD

**Issue by vikramdadwal** [microsoft/AzureStorageExplorer#4519]
Please do not deprecate Cosmos support in Explorer. The recommended Azure portal version is no good. A dedicated windows client is needed.

**Comment by southpolesteve** [comment]
The surface area of the Cosmos service has grown far beyond what is available in our storage explorer integration. Some resources created using newer tools (Azure Portal, new SDKs, CLIs) are incompatible with the much older SDK used by our Storage Explorer code resulting in a poor customer experience. We decided to deprecate and focus our limited resources on the [shared codebase that powers the Azure Portal and cosmos.azure.com](https://github.com/Azure/cosmos-explorer). If you are having a poor experience in the portal please let us know we can improve by filing an issue in that repo.

We have also heard feedback that some customers prefer a desktop tool. During the next year we are investigating integrations with [Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/download-azure-data-studio?view=sql-server-ver15) as well as releasing our own desktop experience that wraps the shared codebase linked above. 

Customers preferring desktop can also continue to use supported versions of Storage Explorer or the [Azure Databases extension for VSCode](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-cosmosdb).
