### ISSUE TITLE
Appears to delete wrong item if similarly named

### ISSUE THREAD

**Issue by 5w33n** [microsoft/AzureStorageExplorer#452]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: 2K8r2
**Architecture**: x64
**Regression From**: ??

#### Steps to Reproduce: ####
1. Moderately nested Directory structure contained a folder and a file with the exact same name ("wf" in my case)
2. Right-click delete the **file** not the folder

#### Expected Experience: ####
Expected the file to be deleted

#### Actual Experience: ####
The *folder* appeared to be deleted

Tried to delete file and got an error message, which caused me to refresh the folder and to my relief, the folder wasn't deleted after all.

Here are the 2 status messages from the operations log pane(most recent first):

Deleting blob from '<company-specific-folder-names>/remits/archive': 0 completed, 1 error(s): Deleting '<company-specific-folder-names>/remits/archive/wf': The specified blob does not exist. RequestId:998eec18-401e-00b3-5a7c-1e56a1000000 Time:2018-07-18T09:46:53.4079200Z

Deleted blob from '<company-specific-folder-names>/remits/archive': 1 completed

**Comment by craxal** [comment]
Sounds like an issue with our cache maintenance.

**Comment by 5w33n** [comment]
Not too common a scenario I know, but sufficiently alarming (I thought I had deleted a PROD archive of financial data for example!) and hopefully easy to address.

**Comment by craxal** [comment]
Sadly, not the easiest, so I can't say when this will get fixed. However, this is something we want to improve, so we'll keep your issue on hand. Thanks for finding this!

**Comment by JasonYeMSFT** [comment]
@5w33n , do you know the content-type of the file you tried to delete? We are using content-types to match the items in the cache and this should be a very rare edge case.

**Comment by 5w33n** [comment]
Understood, and thanks for taking a look so quickly,

I believe the blob was an extension-less file named "wf", and in terms of content it was a zip file that contained a single text file named 'nodata.txt' and that text file had zero-length content.

Just to be clear, ASE _did_ successfully delete the blob I selected in Azure - the file - the problem is the UI made it look like I had deleted the folder. The failure status message came from my _subsequent_ attempt to delete the remaining UI representation of a file (it mustn't have been able to find it)  Refreshing the view was the key to re-syncing with Azure properly and getting a true picture of the current state.

I can certainly work around the issue, so it's not urgent for me personally, but let me know if you need any more.

**Comment by 5w33n** [comment]
BTW - happens with rename too... (which was my attempt at a workaround)

**Comment by craxal** [comment]
Not surprising since rename is a copy and a delete.

**Comment by JasonYeMSFT** [comment]
This is no longer a problem since we have deprecated our heuristic cache manipulation and refresh the table to reflect the latest state now.
