### ISSUE TITLE
An error is reported after connecting to a shared file

### ISSUE THREAD

**Issue by Lemuli** [microsoft/AzureStorageExplorer#4520]
Connect Storage File through SAS URL, the connection is successful, but you need to check the File Shares error, the error information is as follows
Unable to retrieve subresources.
Details:
This request is not authorized to perform this operation.
RequestId:508485eb-a01a-001f-6318-590d3b000000
Time: 2021-06-04 T08:03:33. 5552851 z

**Comment by Lemuli** [comment]
Sorry, the problem may be because I have restricted the Internet

**Comment by MRayermannMSFT** [comment]
@Lemuli can you confirm that was indeed the issue?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still have problems, please open a support ticket from the Azure portal, or open a new issue here. Thanks.
