### ISSUE TITLE
The button of one action is still focused after closing the dialog opened by executing the action

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4521]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 20210604.1
**Branch**: main
**Platform/OS**: Linux Ubuntu 18.04/ MacOS Big Sur 11.3
**Architecture**: x64
**How Found**: Exploratory testing 
**Regression From**: Previous release (1.19.1)

## Bug Descriptions ##
The button of one action is still focused after closing the dialog opened by executing the action.
This issue reproduces for toolbar items in blob, file share, queue, table, managed disks and ADLS Gen2 data explorers. 

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Click 'New Folder' -> Click 'Cancel' on the 'New Folder' dialog.
3. Check the button 'New Folder' on the toolbar is not focused.

## Expected Experience ##
The button 'New Folder' is not focused.
Here is the screenshot on 1.19.1 release version:
![image](https://user-images.githubusercontent.com/41351993/120769908-2abcbd80-c550-11eb-8a24-7b574b9dac27.png)

## Actual Experience ##
The button 'New Folder' is focused.
![image](https://user-images.githubusercontent.com/41351993/120769901-285a6380-c550-11eb-8245-6871ac36fea5.png)

##  Additional Context ##
This issue doesn't reproduce on Windows 10.

**Comment by craxal** [comment]
@v-xianya Actually, I think the old behavior is unusual. It makes more sense to me for focus to remain on the toolbar button that was clicked after the dialog closes. So I'm going to resolve this as by design.

@JasonYeMSFT @jinglouMSFT Feel free to reopen and comment if you have a different opinion.

**Comment by v-xianya** [comment]
Hi @craxal Thanks for the comments. 
If the current behavior is expected.  It would be better to keep the same behavior on Windows.

**Comment by JasonYeMSFT** [comment]
@v-xianya I just tested our latest main branch on Windows and it has the same behavior of focusing on the newly clicked button. If you can verify that, we can conclude this issue as closed.

**Comment by v-xianya** [comment]
@JasonYeMSFT Verified on the build main/20210610.4. The behavior on Windows keep same with Linux & Mac.
