### ISSUE TITLE
The closed dialog which previously opened by clicking one action on the 'Actions' panel pops up again after pressing Enter

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4522]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 20210604.1
**Branch**: main
**Platform/OS**: Linux Ubuntu 18.04/ MacOS Big Sur 11.3
**Architecture**: x64
**How Found**: Exploratory testing 
**Regression From**: Not a regression

## Bug Descriptions ##
Open a dialog by clicking one action on the 'Actions' panel ->  Close the dialog without executing any operation -> Press 'Enter' then the dialog pops up.

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Select the 'Blob Containers' node -> Go to its 'Actions' panel.
3. Click 'Open Container by Name...' -> Closed the prompt dialog by clicking 'X' or 'Cancel' button.
4. Press 'Enter' -> Check no dialog pops up.

## Expected Experience ##
No dialog pops up.

## Actual Experience ##
The 'Open Container by Name...' dialog pops up.

## Additional Context ##
This issue doesn't reproduce on Windows 10.

**Comment by MRayermannMSFT** [comment]
@v-xianya for this test case, the behavior you are seeing on mac and linux is expected. So the bug here is against windows. We will look into this.

**Comment by MRayermannMSFT** [comment]
@v-xianya it seems this is a regression, at least for 1.19.1?

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT yes, you are right. It is a regression from 1.19.1 on Windows.

**Comment by v-xianya** [comment]
Hi @JasonYeMSFT Could you help to take a look at bug [4521](https://github.com/microsoft/AzureStorageExplorer/issues/4521)?
