### ISSUE TITLE
Storage Explorer panel is moved with the dialog when trying to move one dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4523]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 20210604.1
**Branch**: main
**Platform/OS**: Linux Ubuntu 18.04
**Architecture**: x64
**How Found**: Exploratory testing 
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Open any one dialog (Like 'New Folder' dialog).
2. Move the dialog -> Check the Storage Explorer panel is not moved.

## Expected Experience ##
The Storage Explorer panel is not moved.

## Actual Experience ##
The Storage Explorer panel is moved with the dialog.

## Additional Context ##
1. This issue doesn't reproduce on Linux Ubuntu16.04.
2. This issue doesn't reproduce on Windows 10 & MacOS Big Sur 11.3.
3. Here is the video of the steps：
![testmove](https://user-images.githubusercontent.com/41351993/120783692-db7d8980-c55d-11eb-9b4c-a45e6e40ca72.gif)

**Comment by craxal** [comment]
@v-xianya It looks like this is the expected behavior for the updated version of Gnome Desktop used in Ubuntu. I opened gedit and selected Save As... to open a system dialog. Dragging the dialog also drags the app window.

**Comment by v-xianya** [comment]
Hi @craxal Got it. It make sense to deal with issue as by design due to the platform reason.

Add more info:
1. This issue also reproduces on CentOS 7.6.1810. 
2. On Ubuntu 20.04. The Storage Explore panel will become almost the same size as the currently moved dialog and is moved with it.
