### ISSUE TITLE
Ressources not available

### ISSUE THREAD

**Issue by Mindbl2000** [microsoft/AzureStorageExplorer#4526]
Untergeordnete Ressourcen können nicht abgerufen werden.

Details:
{
  "name": "FetchError",
  "message": "request to http://127.0.0.1:10000/devstoreaccount1?include=metadata&comp=list failed, reason: connect ECONNREFUSED 127.0.0.1:10000",
  "stack": "FetchError: request to http://127.0.0.1:10000/devstoreaccount1?include=metadata&comp=list failed, reason: connect ECONNREFUSED 127.0.0.1:10000\n    at ClientRequest.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1461:11)\n    at ClientRequest.emit (events.js:310:20)\n    at Socket.socketErrorListener (_http_client.js:426:9)\n    at Socket.emit (events.js:310:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)",
  "type": "system",
  "errno": "ECONNREFUSED",
  "code": "ECONNREFUSED"
}

**Comment by MRayermannMSFT** [comment]
@Mindbl2000 did you start your emulator? Storage Explorer does not start your emulator for you.

**Comment by swiftysix** [comment]
I ran into this issue as well and was pretty confused by @MRayermannMSFT 's answer. Here's what you should check/do if you're not sure if your storage emulator is running: [Start and initialize the Storage Emulator](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator#start-and-initialize-the-storage-emulator)

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. As @swiftysix said, you need to ensure the Azure local emulator is started and running.
