### ISSUE TITLE
There is no conflict dialog when pasting one blob snapshot to where its original blob exists

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4528]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 20210605.1
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ MacOS Big Sur 11.3
**Architecture**: ia32/x64
**How Found**: From running test case
**Regression From**: Previous release (1.19.1)

## Steps to Reproduce ##
1. Expand a storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Create a snapshot for the blob -> Copy the snapshot.
4. Exit the snapshot mode -> Click 'Paste'.
5. Check whether there is a conflict dialog.

## Expected Experience ##
There is a conflict dialog.
![image](https://user-images.githubusercontent.com/41351993/120992252-ff86d800-c7b4-11eb-9f8a-76478c152b85.png)

## Actual Experience ##
1. There is no conflict dialog.
2. A failed activity log displays.
![image](https://user-images.githubusercontent.com/41351993/120991937-af0f7a80-c7b4-11eb-9a74-249406d38aae.png)

##  Additional Context ##
Here is the AzCopy Log:
[bfb08cd9-312d-164c-79ce-4611c47a97e9.log](https://github.com/microsoft/AzureStorageExplorer/files/6607577/bfb08cd9-312d-164c-79ce-4611c47a97e9.log)

**Comment by MRayermannMSFT** [comment]
It seems like AzCopy is seeing the paste as a "copy source is same as destination". That's not the case here. The snapshot is a different source than the destination. So false positive basically.

**Comment by MRayermannMSFT** [comment]
New RC of AzCopy has been integrated which I have observed as fixing this.
