### ISSUE TITLE
Authentication Error Message Not Descriptive

### ISSUE THREAD

**Issue by ch53k** [Microsoft/AzureStorageExplorer#453]
**Storage Explorer Version**: 1.3.1
**Platform/OS Version**: Windows 10 1803
**Architecture**: x64
**Regression From**: Unknown

#### Steps to Reproduce: ####
1. Set your clock to be at least 15 minutes behind the current time.
2. Try to navigate to a table on a storage account. 

#### Expected Experience: ####
I expect the dialog box to be consistent between the storage types and be descriptive (whether it be a credential issue or otherwise). 

#### Actual Experience: ####
When you expand the table listing you'll get a dialog box that said:

> "Authentication error"

This message was not very descriptive, so I tried troubleshooting the issue. Some of the things I tried were removing the Azure account, adding the storage account directly, none of these things worked. It wasn't until I tried to expand the Blob storage list that I got a new message that solved my problem. This one said:

> "Authentication Error. Request date header too old: <date time>

**Comment by craxal** [comment]
That's, unfortunately, an issue with the Azure API. We're just forwarding the errors returned by Azure to the dialog. We decided a while back we weren't going to try and interpret errors, because it's easy to get them wrong, and it makes diagnosing different problems harder.
