### ISSUE TITLE
Storage explorer not getting the storage details 

### ISSUE THREAD

**Issue by mmkhan76** [microsoft/AzureStorageExplorer#4531]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.1

### Architecture

x64

### Platform

Windows

### OS Version

windows 10

### Bug Description

{
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"self signed certificate in certificate chain\\\",\\n  \\\"stack\\\": \\\"Error: self signed certificate in certificate chain\\\\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1484:34)\\\\n    at TLSSocket.emit (events.js:310:20)\\\\n    at TLSSocket._finishInit (_tls_wrap.js:927:8)\\\\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:697:12)\\\",\\n  \\\"code\\\": \\\"SELF_SIGNED_CERT_IN_CHAIN\\\"\\n}\""
}

### Steps to Reproduce

lunch storage explorer , connect to subscription 

### Actual Experience

![bloberror](https://user-images.githubusercontent.com/85532898/121108330-2ce07f80-c7cf-11eb-8c9f-20fa8ab2dbd7.jpg)
After connecting to my azure account i get the attach error 

### Expected Experience

Expecting to see storage account associated to my account
![AzurePortal](https://user-images.githubusercontent.com/85532898/121108561-96608e00-c7cf-11eb-9e61-9d2b501da568.jpg)
Attach is what i was expecting

**Comment by MRayermannMSFT** [comment]
@mmkhan76 please follow these steps to troubleshoot self-signed certificate issues:

https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#error-self-signed-certificate-in-certificate-chain-and-similar-errors

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you still need help, please either open a support ticket from the portal, or open a new issue here.
