### ISSUE TITLE
无法检索子资源。

### ISSUE THREAD

**Issue by tombluemoon** [microsoft/AzureStorageExplorer#4535]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.0

### Architecture

x64

### Platform

Windows

### OS Version

windows sever 12

### Bug Description

连接本地模拟器时，报了一下的错误

无法检索子资源。

详细信息:
socket hang up

### Steps to Reproduce

1.launch the explorer
2.refresh the connection

### Actual Experience

连接本地模拟器时，报了一下的错误

无法检索子资源。

详细信息:
socket hang up

**Comment by MRayermannMSFT** [comment]
@tombluemoon are you behind a proxy? At what point in the tree are you getting this error?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you still need help, please either open a support ticket from the portal, or open a new issue here.
