### ISSUE TITLE
Nothing happens when I click Configure CORS Settings

### ISSUE THREAD

**Issue by mvanstelle** [microsoft/AzureStorageExplorer#454]
**Storage Explorer Version**: 1.4.1
**Platform/OS Version**: Windows 10 Home
**Architecture**:  ia32
**Regression From**:  1.2

#### Steps to Reproduce: ####
1.  Expand Local And Attached > Storage Accounts > Development > Blob Containers
2.  Right-Click and choose configure CORS Settings
3. Observe that nothing happens

#### Expected Experience: ####
The CORS Settings dialog should open

#### Actual Experience: ####
 Nothing happens

**Comment by mvanstelle** [comment]
@craxal What additional info would you like? This happened again on a new machine, Azure 1.4.1, on a fresh Windows 10 install

**Comment by craxal** [comment]
Can you update your repro steps? The Development node has since been removed, and you need to create a connection to your emulator. Also, what emulator are you using?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you're still having problems.
