### ISSUE TITLE
$logs leads to InvalidResourceName Error 

### ISSUE THREAD

**Issue by DerTreeMan** [microsoft/AzureStorageExplorer#4540]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.0

### Regression From

don't know

### Architecture

x64

### Storage Explorer Build Number

20210425.1

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Hi,

I installed and started azurite via npm today. When I try to access the emulated storage account with Storage Explorer, I get an error message that the specified resource name contains invalid characters.

Strange thing is that the emulated storage account was set up right before and so there are no containers created by me yet.

In the error message you can see that apparently the request to:

`http://127.0.0.1:10000/devstoreaccount1/%24logs?restype=container` 

leads to the error.

I have attached the entire error message as a file.
[error.txt](https://github.com/microsoft/AzureStorageExplorer/files/6623451/error.txt)

### Steps to Reproduce

1. Download azurite via npm

`npm install -g azurite`
2. Start azurite via cmd
3. Start Storage Explorer
4. Open "(Emulator - Default Ports) (Key)" in Explorer View
5. Expand Blob Containers

At this point a window opens with the error message:

![image](https://user-images.githubusercontent.com/47403587/121347644-b7d48d80-c927-11eb-801c-a3f8ad238a6d.png)

### Actual Experience

I have already uninstalled and reinstalled azurite as well as Storage Explorer, neither of which has been successful unfortunately. 

Furthermore, I was able to reproduce the same behavior on three independent Windows 10 x64 machines.

**Comment by trpedersen** [comment]
Hi - I have exactly the same issue, but with version 1.19.1. No problems viewing blob containers on Azure, issue arises when connecting to Azurite (running in Docker.)

**Comment by DerTreeMan** [comment]
Hi,

specifying version 3.13.1 also fixed the problem for me for now.

Thanks!
