### ISSUE TITLE
Azure Storage Explorer 1.19.1

### ISSUE THREAD

**Issue by tramanemoulton** [microsoft/AzureStorageExplorer#4541]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.1

### Architecture

x64

### Storage Explorer Build Number

20210425.1 

### Platform

macOS

### OS Version

Big Sur

### Bug Description

Upon opening in the explorer column is the loading icon animation indefinitely

When clicking the User icon and attempting to sign in, web page for O365 authentication never opens

### Steps to Reproduce

1. Close ASE
2. Download latest version
3. Delete old version
4. Install latest version
5. Open Azure Storage Explorer
6. Window loads and Spinning Loaing animation is seen
7. Click the User Icon
8. Click Add Account
9. Click Subscription
10. Select Azure radio button
11. Click Next
12. Message is displayed "Your browser should now open and redirect you to a login page. Waiting for authentication..."
13. Browser window no longer opens
14. No authentication is initiated

### Actual Experience

![image](https://user-images.githubusercontent.com/55512415/121391589-87d3bd00-c91c-11eb-80a1-3c0db367e81c.png)

![image](https://user-images.githubusercontent.com/55512415/121391653-a043d780-c91c-11eb-8fc1-4e6e6c192b74.png)

![image](https://user-images.githubusercontent.com/55512415/121391725-b2be1100-c91c-11eb-8d60-e298ae000619.png)

![image](https://user-images.githubusercontent.com/55512415/121391483-6a9eee80-c91c-11eb-9a67-d7c37499efa4.png)

### Expected Experience

Browser window should open and ask me to sign in.

I am already signed into Azure account, browser windo closes and Azure Account is displayed in product

### Additional Context

Unable to close by using the red circle
Unable to close by clicking in title bar and choosing quit
Unable to close by Command + Q

Only way to close is by Force Quit

**Comment by MRayermannMSFT** [comment]
@tramanemoulton this likely sounds like an issue with our authentication/account management process not starting correctly. Can you please generate and share some authentication logs with us? Here are some steps on how to do that: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#authentication-logs

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
