### ISSUE TITLE
Feature Request: Data/File preview for viewing schema

### ISSUE THREAD

**Issue by AliviaB** [microsoft/AzureStorageExplorer#4543]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Can we have a data or file preview option similar to ADF dataset?

### Desired Solution

A preview button at top were we can select a file in azure storage and view the file schema and few sample rows.

**Comment by MRayermannMSFT** [comment]
@AliviaB, what do you mean by "schema" and "rows"? Is this for a specific type of file you have in your container? Like `.csv` or something like that?

**Comment by AliviaB** [comment]
Hi @MRayermannMSFT  , 
Schema and row will are with respect to the csv files correct, but I was looking for a feature to preview files like text/json/parquet ect. Basically a snick peak into the file..

**Comment by MRayermannMSFT** [comment]
Gotcha. We already have an issue open for this. #2427

So closing this as a dupe. Feel free to go give that issue a thumbs up, a +1, or something like that. :)
