### ISSUE TITLE
It would be better to disable the action 'Undelete by Date...' for one soft-deleted blob version

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4545]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 20210610.4
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 20.04/ MacOS Big Sur 11.3
**Architecture**: ia32/x64
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers (make sure the blob versioning is enabled).
2. Create one blob container -> Upload one blob.
3. Delete the blob to create a blob version.
4. Disable the blob versioning.
5. Switch to 'All blobs and blobs without current version' -> Soft delete the blob version.
6. Right click the soft-deleted blob version -> Click 'Undelete'.
7. Check whether the action 'Undelete by Date...' is disabled.

## Expected Experience ##
The action 'Undelete by Date...' is disabled.

## Actual Experience ##
The action 'Undelete by Date...' is enabled.
![image](https://user-images.githubusercontent.com/41351993/121497374-f5abe180-ca0d-11eb-90ef-a3e61f7e3a09.png)

**Comment by JasonYeMSFT** [comment]
I will take this issue and figure out what is the expected behavior of undelete on soft-deleted versions/snapshots.

**Comment by v-xianya** [comment]
@JasonYeMSFT FYI, there is a similar issue [508](https://github.com/microsoft/AzureStorageExplorer/issues/508).
