### ISSUE TITLE
The behaviors are inconsistent between 'Open Container by Name' and 'Open Queue by Name' dialog after typing '/' to search

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4548]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 20210610.4
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 20.04/ MacOS Big Sur 11.3
**Architecture**: ia32/x64
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account.
2. Right click 'Blob Containers' node -> Click 'Open Container by Name...'.
3. Type '/' in the search box -> Click 'Search' -> Observe the behavior.
4. Right click 'Queues' node -> Click 'Open Queue by Name...'.
5. Type '/' in the search box -> Click 'Search' -> Observe the behavior.
6. Check the behaviors are consistent.

## Expected Experience ##
The behaviors are consistent.

## Actual Experience ##
The behaviors are inconsistent.
![image](https://user-images.githubusercontent.com/41351993/121506501-59d2a380-ca16-11eb-9fcb-f6aee50b1299.png)

**Comment by craxal** [comment]
@v-xianya I don't think this worth trying to fix. Blob and queue APIs are different, so if one returns an error and the other doesn't there isn't really anything we can do.

**Comment by v-xianya** [comment]
Ok, got it.
