### ISSUE TITLE
Select Resource pop up shows on every launch

### ISSUE THREAD

**Issue by elTopop** [microsoft/AzureStorageExplorer#4549]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.1

### Architecture

x64

### Platform

Windows

### Bug Description

Select Resource pop up shows on every launch. 

### Steps to Reproduce

1. Launch Storage Explorer
2. Pop up appears every time with no option to not have this open every time
3. Close pop up

### Actual Experience

Pop up is not useful to me, having to close it every launch is annoying. Add a "don't show this" check box or other option.

If there is an option already in the settings, pls point me to it!

Cheers

**Comment by MRayermannMSFT** [comment]
@elTopop the dialog should only pop up if both of these conditions are true:

- you are not signed in
- you have not attached any resources to Storage Explorer

So are both of those true for you? If yes, then what are you using Storage Explorer for? Maybe do you use it just for working with your emulator? Or do you sign out/detach resources every time before closing the app?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you would like to continue discussing this behavior, please open a new issue.
