### ISSUE TITLE
Shows 'Local and Attached' not 'Local & Attached'

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#455]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: x64
**Build Number**: 20180719.13
**Commit**: 4f4341b4
**Regression From**: Previous release 1.3.1(20180711.1)

#### Steps to Reproduce: ####
1. Launch Storage Explorer.
2. Check whether it shows 'Local & Attached' or not.

#### Expected Experience: ####
It shows 'Local & Attached'

#### Actual Experience: ####
It shows 'Local and Attached'.
![localattached](https://user-images.githubusercontent.com/34729022/42990899-9b3f8ec8-8bf3-11e8-8c6e-488ba17c0e15.png)

**Comment by craxal** [comment]
Please try again with the latest build. A change was recently pushed that may already have fixed this.

**Comment by MRayermannMSFT** [comment]
@v-xuanzh can you check if this bug is fixed?

**Comment by v-xuanzh** [comment]
Yes! It has been fixed on latest master build 20180724.5. Could you help to resolve it?
