### ISSUE TITLE
Undelete on deep/wide directories crashes the app

### ISSUE THREAD

**Issue by munael** [microsoft/AzureStorageExplorer#4557]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.1

### Architecture

x64

### Storage Explorer Build Number

20210425.1

### Platform

Windows

### OS Version

19042

### Bug Description

Undelete by date on a deep directory may crash the entire app.

### Steps to Reproduce

1. Have a large directory (nested folders, many files, possibly large files?)
2. Delete the directory.
3. Select the directory in Undelete view.
4. Undelete the directory by date from around an hour before the delete command.

### Actual Experience

ASE crashes while undeleting. I have to go through the directory manually and do it in chunks.

**Comment by MRayermannMSFT** [comment]
@munael 

- Do you see any error messages or does the app just crash without any explanation? 
- Does it seem like the issue is more related to number of files or the depth/width of the directory structure?
- If you think it is number of files, about how many files does it seem for it to repro for you?
- If you think it is depth/width of the directory structure, can you tell us more about the layout/size of your directory structure?
- Does this only happen for undelete by date?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue with more information if you would like to continue.

**Comment by munael** [comment]
I'll try to repro at some point and post another bug then. These stats are from running on _1.19.1_:
- No errors. UI disappears, processes exit.
- Depth. I could do it fine by going in so the target directories were all shallow, then do them one by one, as directories.
- Seems to be depth. Still, I had close to 2000 files total in the structure.
- 4 nested levels with hundreds of directories at level 2 (from the bottom).
- Haven't tried otherwise.
