### ISSUE TITLE
'Add Account' button doesn't work

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#456]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: x64
**Build Number**: 20180719.13
**Commit**: 4f4341b4
**Regression** From: Previous release 1.3.1(20180711.1)

#### Steps to Reproduce: ####
1. Launch Storage Explorer and click 'Add Account' button.
2. Check whether the button works well or not.

#### Expected Experience: ####
The 'Connect' dialog pops up.

#### Actual Experience: ####
The 'Add Account' button doesn't work.

1. Pop up an error when attaching the created URL to Connect dialog which is opened using the context menu.
![error](https://user-images.githubusercontent.com/34729022/42991149-49072926-8bf4-11e8-801c-77556524c71a.png)
2. This issue doesn't reproduce on Windows.

**Comment by craxal** [comment]
Please try again with the latest build. A change was recently pushed that may already have fixed this.

**Comment by MRayermannMSFT** [comment]
@v-xuanzh can you check if this bug is fixed?

**Comment by v-xuanzh** [comment]
Yes! It has been fixed on latest master build 20180724.5
