### ISSUE TITLE
Filtered tenants/subscriptions are not preserved after reauthentication

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#4560]
I often work with a small subset of subscriptions available to me through my Azure account. But when I have to reauthenticate that account, all the tenants or subscriptions I had filtered out are added back in. It would be much more convenient if we remembered what tenants or subscriptions were filtered between reauthentication attempts.

Related to #2290

**Comment by kimjamia** [comment]
This just happened to me. My account is in multiple tenants where I don't even have access to any subscriptions. It's very annoying to uncheck them all again. Naturally the UI complains that "one or more accounts require reauthentication". Related to #5774.

**Comment by rscottwatson** [comment]
Yikes this is still open, I have about 500 subscriptions and and only need about 10 selected.  Is there a config file somewhere I can manually update to say that I am only interested in these subscriptions for a specific tenant?  Ideally, there would be a unselect all or select none and then I could filter and choose which ones to select but for the time being I would be happy to just update a config file with the subs I am concerned with.

**Comment by craxal** [comment]
We're actually adding a feature to 1.29.0 that will let you hide subscriptions you don't care about (see #5774)!
