### ISSUE TITLE
Pop up an error after adding one resource to Quick Access

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#457]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: x64
**Build Number**: 20180719.13
**Commit**: 4f4341b4
**Regression** From: Previous release 1.3.1(20180711.1)

#### Steps to Reproduce: ####
1. Choose one account and add it to Quick Access.
2. Check whether it can be added successfully or not.

#### Expected Experience: ####
The account can be added successfully.

#### Actual Experience: ####
Pop up the error 'The requested action could not be completed'.
![quickaccess](https://user-images.githubusercontent.com/34729022/42994184-e122ffca-8bfc-11e8-8fb7-acb14eefc215.png)

**Comment by craxal** [comment]
Please try again with the latest build. A change was recently pushed that may already have fixed this.

**Comment by MRayermannMSFT** [comment]
@v-xuanzh can you check if this bug is fixed?

**Comment by v-xuanzh** [comment]
Yes! It has been fixed on latest master build 20180724.5
