### ISSUE TITLE
Inconsistent borders between tabs in dark theme

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#4572]
Some borders between tabs look dark and bezeled. Other borders look light.

![image](https://user-images.githubusercontent.com/3473026/122123212-96214d80-cde2-11eb-896d-72e81c694b50.png)

**Comment by JasonYeMSFT** [comment]
The problem is caused by CSS rounding. The width of each tab may contain fractional numbers. Due to rounding, the right border of some tabs appear a little wider than the rest.

**Comment by craxal** [comment]
@JasonYeMSFT Is there a solution? Can we force integer widths?

**Comment by JasonYeMSFT** [comment]
There is no non-JS way to force integer widths. I had an idea to visually mitigate this issue.
