### ISSUE TITLE
A blob container can be opened by the direct link to one deleted blob container with the same name

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4578]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 20210616.2
**Branch**: main
**Platform/OS**: Windows 10/ MacOS Big Sur 11.3
**Architecture**: ia32/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Bug Descriptions ##
Copy direct link to one service -> Delete the service -> Open the link from the browser.
The direct link can find and open a service which has the same name as the deleted service in a different storage account.

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Right click one blob container -> Click 'Copy Direct Link to Blob Container'.
3. Then delete the blob container.
4. Expand another storage account -> Blob Containers.
5. Create a blob container using the same name of the blob container which is deleted in Step3.
6. Paste the copied link to browser -> Open the link.
7. Check there is an info bar indicates that `Unable to find resource 'XXX'. It may have been deleted or you may not have access to it`.

## Expected Experience ##
There is an info bar.
![image](https://user-images.githubusercontent.com/41351993/122200565-bed24180-cecd-11eb-98ab-eae54208bd3a.png)

## Actual Experience ##
1. There is no info bar.
2. Able to find and open the blob container under another storage account.

## Additional Context ##
Here is the video:
![link](https://user-images.githubusercontent.com/41351993/122205205-91d45d80-ced2-11eb-99f0-71dd82c0234c.gif)

**Comment by JasonYeMSFT** [comment]
I checked with 1.19.1 and it does report the error. Maybe this is a regression.

**Comment by JasonYeMSFT** [comment]
I cannot reproduce this bug on the latest release candidate. Could you save the direct link and share one that can reproduce the bug with us?

**Comment by v-xianya** [comment]
@JasonYeMSFT Verified on the latest 1.20.0 branch build. Reproduce.
The direct link comes from the deleted blob container 'donotdelete' under the account 'a0615account'. 
When opening the link it will find and open the blob container 'donotdelete' under the account 'alinkyan0617'.

Here is the direct link to repro:

storageexplorer://v=1&accountid=%2Fsubscriptions%2F92be7e56-8a60-427c-a3e3-0ebd54a827a1%2FresourceGroups%2Fcti-kristine%2Fproviders%2FMicrosoft.Storage%2FstorageAccounts%2Fa0615account&subscriptionid=92be7e56-8a60-427c-a3e3-0ebd54a827a1&resourcetype=Azure.BlobContainer&resourcename=donotdelete

 
![image](https://user-images.githubusercontent.com/41351993/122365658-71b5a480-cf8d-11eb-9d0e-188fe21799d4.png)

**Comment by JasonYeMSFT** [comment]
I see. The bug will only reproduce if the container is already loaded in the tree.

**Comment by JasonYeMSFT** [comment]
I did some investigation of the implementation and this seems to be by design. The current implementation has a dedicated code path to search all the service level group nodes available in the tree for the node when the group node in the direct link cannot be found. Let me bring up with the team to see if it still make sense.

**Comment by v-xianya** [comment]
Verified on the build main/20211109.2. Fixed.
