### ISSUE TITLE
SDL renewal

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#4579]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

SDL renewal

### Desired Solution

SDL renewed

### Additional Context

Due at the end of July

**Comment by MRayermannMSFT** [comment]
We finished SDL work.
