### ISSUE TITLE
Pop up an error after configuring Soft Delete Policy for 'Blob Containers'

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#458]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: x64
**Build Number**: 20180719.13
**Commit**: 4f4341b4
**Regression** From: Not a regression

#### Steps to Reproduce: ####
1. Expand one GPV2 account and right click 'Blob Containers' node.
2. Click 'configure Soft Delete Policy'

#### Expected Experience: ####
The 'Soft Delete' dialog pops up.

#### Actual Experience: ####
Pop up an error 'The requested action could not be completed'
![softdelete](https://user-images.githubusercontent.com/34729022/42994392-82157af2-8bfd-11e8-894b-928d732a225c.png)

**Comment by craxal** [comment]
Please try again with the latest build. A change was recently pushed that may already have fixed this.

**Comment by MRayermannMSFT** [comment]
@v-xuanzh can you check if this bug is fixed?

**Comment by v-xuanzh** [comment]
Yes! It has been fixed on latest master build 20180724.5
