### ISSUE TITLE
Download show error but file is on the disk. Download hang forever. 

### ISSUE THREAD

**Issue by NtgTNabet** [microsoft/AzureStorageExplorer#4588]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.1

### Architecture

x64

### Storage Explorer Build Number

202110425.1

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Sometimes download display error while the file is properly download to disk.
When it does happen download can also hang forever in pending status

**AzCopy command**

`$env:AZCOPY_CRED_TYPE = "Anonymous";
./azcopy.exe copy "https://**********.blob.core.windows.net/file.json?sv=2020-04-08&se=2021-07-17T07%3A44%3A33Z&sr=c&sp=rl&sig=t6Qd7hVG%2BnpqZlc%2BDLKqur6YaCt1%2F%2BETCfPsBrr%2B5O0%3D" "C:\******\file.json" --overwrite=prompt --check-md5 FailIfDifferent --from-to=BlobLocal --blob-type BlockBlob --recursive --trusted-microsoft-suffixes=;
$env:AZCOPY_CRED_TYPE = "";
`

**AzCopy log**

` 2021/06/17 07:44:50 AzcopyVersion  10.10.0
2021/06/17 07:44:50 OS-Environment  windows
2021/06/17 07:44:50 OS-Architecture  amd64
2021/06/17 07:44:50 Log times are in UTC. Local time is 17 Jun 2021 09:44:50
2021/06/17 07:44:50 Job-Command copy https://*******.blob.core.windows.net/file.json?se=2021-07-17t07%3A44%3A33z&sig=-REDACTED-&sp=rl&sr=c&sv=2020-04-08 C:\******\file.json --output-type=json --cancel-from-stdin --overwrite=prompt --check-md5 FailIfDifferent --from-to=BlobLocal --blob-type BlockBlob --recursive --trusted-microsoft-suffixes= 
2021/06/17 07:44:50 Number of CPUs: 4
2021/06/17 07:44:50 Max file buffer RAM 2.000 GB
2021/06/17 07:44:50 Max concurrent network operations: 32 (Based on number of CPUs. Set AZCOPY_CONCURRENCY_VALUE environment variable to override)
2021/06/17 07:44:50 Check CPU usage when dynamically tuning concurrency: true (Based on hard-coded default. Set AZCOPY_TUNE_TO_CPU environment variable to true or false override)
2021/06/17 07:44:50 Max concurrent transfer initiation routines: 64 (Based on hard-coded default. Set AZCOPY_CONCURRENT_FILES environment variable to override)
2021/06/17 07:44:50 Max enumeration routines: 16 (Based on hard-coded default. Set AZCOPY_CONCURRENT_SCAN environment variable to override)
2021/06/17 07:44:50 Parallelize getting file properties (file.Stat): false (Based on AZCOPY_PARALLEL_STAT_FILES environment variable)
2021/06/17 07:44:50 Max open files when downloading: 2147483224 (auto-computed)
2021/06/17 07:44:50 ISO 8601 START TIME: to copy files that changed before or after this job started, use the parameter --include-before=2021-06-17T07:44:45Z or --include-after=2021-06-17T07:44:45Z
2021/06/17 07:44:50 Any empty folders will not be processed, because source and/or destination doesn't have full folder support
2021/06/17 07:44:50 Final job part has been created
2021/06/17 07:44:50 PERF: primary performance constraint is Unknown. States: C:  0, R:  0, W:  0, F:  0, H:  0, B:  0, S:  0, P:  0, Q:  0, D:  0, E:  0, T:  0, GRs:  0
2021/06/17 07:44:50 0.0 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total, 
2021/06/17 07:44:50 JobID=b9a1a5d0-13b6-3a4b-7c38-d611124c3cd2, credential type: Anonymous
2021/06/17 07:44:50 scheduling JobID=b9a1a5d0-13b6-3a4b-7c38-d611124c3cd2, Part#=0, Transfer#=0, priority=0
2021/06/17 07:44:50 Final job part has been scheduled
2021/06/17 07:44:50 INFO: [P#0-T#0] has worker 48 which is processing TRANSFER
2021/06/17 07:44:50 ==> REQUEST/RESPONSE (Try=1/41.9812ms, OpTime=126.7536ms) -- RESPONSE SUCCESSFULLY RECEIVED
   GET https://******.blob.core.windows.net/*****/file.json?se=2021-07-17t07%3A44%3A33z&sig=-REDACTED-&sp=rl&sr=c&sv=2020-04-08&timeout=901
   X-Ms-Request-Id: [f6313ad9-801e-005b-7c4c-636ce9000000]

2021/06/17 07:44:50 INFO: [P#0-T#0] DOWNLOADSUCCESSFUL: \\?\C:\********\file.json
2021/06/17 07:44:50 JobID=b9a1a5d0-13b6-3a4b-7c38-d611124c3cd2, Part#=0, TransfersDone=1 of 1
2021/06/17 07:44:50 all parts of entire Job b9a1a5d0-13b6-3a4b-7c38-d611124c3cd2 successfully completed, cancelled or paused
`

### Steps to Reproduce

1. Launch storage explorer.
2. Try to download a blob.
3. Failed
4. Try to download another blob
5. Infinite load.

### Actual Experience

Hanging forever : 

![image](https://user-images.githubusercontent.com/86045507/122357538-23d07a80-cf54-11eb-8ed6-0734af72ed59.png)

**Comment by apurvchandra** [comment]
I am facing similar issue on a clients machine the download gets stuck in queue with error 
**Error:spawn UNKNOWN**

` 19808 (Provider) >>> Loading 'C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\providers\SessionManagerProvider'
NODE PROCESS PROXY (Main 20252) >>> Launched Node process 21308 for module 'NodeProcessHostProxy'
NODE PROCESS PROXY (Main 20252) >>> Node process 21308 ack received for module 'NodeProcessHostProxy'
PROVIDER (Main 20252) >>> Launched Node process 21308 for provider 'JobHandlerProvider'
[2021-06-21T13:58:36.744Z] (JobHandlerProvider_21308) <NONE> Log file: C:\Users\608407386\AppData\Roaming\StorageExplorer\Microsoft Azure Storage Explorer\logs\2021-06-21_192740\2021-06-21_192740_JobHandlerProvider_21308.log

[2021-06-21T13:58:36.746Z] (JobHandlerProvider_21308) <NONE> Log level: info

21308 (ParentProcessProxy) >>> Loading SSL Settings
21308 (ParentProcessProxy) >>> Injecting certs found in C:\Users\608407386\AppData\Roaming\StorageExplorer\certs\

21308 (ParentProcessProxy) >>> Sending init acks back to parent process

21308 (Provider) >>> Loading 'C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\providers\JobHandlerProvider'

19808 (Provider) >>> Loading 'C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\providers\SettingsProvider'
21308 (Job) DEBUG >>> New job starting:  {
  protocol: 'http:',
  hostname: 'clientproxy.REDACTED.com',
  port: 8080,
  useCredentials: false
}

21308 (Job) DEBUG >>> Proxy variables set: 'http://clientproxy.xx.com:8080' 'http://clientproxy.xx.com:8080' 'localhost, 127.0.0.1'

Error:spawn UNKNOWN `

**Comment by JasonYeMSFT** [comment]
@NtgTNabet I fixed a bug in our job queue that might cause a dead lock. The cancelation of the job was due to the worker process not responding in time. I fine tuned some of our timing parameters as well to reduce its likelihood. Here is a test build for our 1.20.0 release [1.20.0 test build](https://storageexplorerpublish.blob.core.windows.net/privatebuilds/1.20.0-rc/StorageExplorer-ia32.exe?sv=2020-04-08&st=2021-06-21T20%3A02%3A40Z&se=2021-06-25T20%3A02%3A00Z&sr=b&sp=r&sig=rOchgFBQJKQ8ZznCbd2yIn2mii02YOpWTVqaudbwdS4%3D) If possible, you can try to use this build and see if the issue still occurs. Once we ship 1.20.0, you can upgrade to 1.20.0.

@apurvchandra I am pretty sure that your issue has a different cause from the original author's. Could you please open a new issue instead and provide us with some additional information such as the Storage Explorer version and if this is a regression? The error is about NodeJS failing to spawn a child process and there are many possible causes. Could you try running Storage Explorer as admin and see if the issue still reproduces?

**Comment by NtgTNabet** [comment]
Thanks @JasonYeMSFT.

I can't install the latest build.  Setup seems to hang forever 

![image](https://user-images.githubusercontent.com/86045507/122886141-fa429500-d33f-11eb-840b-69ab8924d599.png)

**Comment by JasonYeMSFT** [comment]
That's not the case on my machine. Probably because it is an unsigned build. Let me just give you a signed one instead. [real signed build](https://storageexplorerpublish.blob.core.windows.net/privatebuilds/1.20.0-rc/StorageExplorer-ia32-1.20.0-test-rc.exe?sv=2020-04-08&st=2021-06-22T08%3A00%3A05Z&se=2021-06-27T08%3A00%3A00Z&sr=b&sp=r&sig=ZiRhFbobGIE5gwPp887EI1wWsNho%2BgZ3E5FoNSO9SvA%3D)

**Comment by NtgTNabet** [comment]
> That's not the case on my machine. Probably because it is an unsigned build. Let me just give you a signed one instead. [real signed build](https://storageexplorerpublish.blob.core.windows.net/privatebuilds/1.20.0-rc/StorageExplorer-ia32-1.20.0-test-rc.exe?sv=2020-04-08&st=2021-06-22T08%3A00%3A05Z&se=2021-06-27T08%3A00%3A00Z&sr=b&sp=r&sig=ZiRhFbobGIE5gwPp887EI1wWsNho%2BgZ3E5FoNSO9SvA%3D)

Thanks it worked. I will use the release and close the issue next week if it disappeared.

**Comment by JasonYeMSFT** [comment]
We have shipped 1.20.0. We are going to track this issue in 1.21.0.

**Comment by apurvchandra** [comment]
@JasonYeMSFT We tried the latest version and it all worked fine. So all good we don't need another issue 😄 .
