### ISSUE TITLE
The new inputted name disappears after pressing 'Enter' in the address bar of one ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#4589]
**Storage Explorer Version**: 1.20.0-dev
**Build Number:** 202100617.4
**Branch**: rel/1.20.0
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Big Sur 11.3
**Architecture**: ia32/x64
**How Found**: From running test case
**Regression From**: Previous release(1.19.1)

## Bug Description ##
The new inputted name disappears after pressing 'Enter' in the address bar of one ADLS Gen2 blob container.
The new inputted name disappears after pressing 'Enter' in the address bar of one file share.

## Steps to Reproduce ##

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Open one blob container -> Input a name to the address bar -> Press 'Enter'.
3. Check whether the new inputted name shows well.

## Expected Experience ##
The new inputted name shows well.

## Actual Experience ##
The new inputted name disappears.

## Actual Experience ##
This issue doesn't reproduce for one regular blob container.

**Comment by craxal** [comment]
@v-limu Can you expand on what you mean by "inputted name shows well"? Do you mean that the breadcrumbs should update appropriately? Or do you mean that the input should remain active and the text should remain unchanged?

**Comment by v-xianya** [comment]
Hi @craxal Please see the below videos, hope its helpful.

The behaviors on the latest rel/1.20.0 branch:
![actual120](https://user-images.githubusercontent.com/41351993/122521885-ed742780-d047-11eb-829d-1b8ac391b075.gif)
The behaviors on the previous release 1.19.1:
![expect](https://user-images.githubusercontent.com/41351993/122522219-4a6fdd80-d048-11eb-92ca-dbb374ca88c5.gif)

**Comment by v-xianya** [comment]
Verified this issue on latest  rel/1.20.0 build 20210618.7. Fixed.
