### ISSUE TITLE
Storage explorer should support latest emulator version installed by Visual Studio 2017

### ISSUE THREAD

**Issue by onionhammer** [Microsoft/AzureStorageExplorer#459]
Currently Visual Studio 2017 only installs version 5.4 of the storage emulator, the latest version of Storage Explorer now errors when opening up local storage.

![image](https://user-images.githubusercontent.com/969938/43021865-d9f1aade-8c2a-11e8-8cc5-58e8d3777f4c.png)

![image](https://user-images.githubusercontent.com/969938/43021830-b662988a-8c2a-11e8-8e2f-78983219bd1a.png)

This disconnect causes some pretty big annoyance, especially since upgrading your storage emulator means losing all your test data

**Comment by craxal** [comment]
Storage Explorer should still work with any emulator! Recent versions have stopped automatically installing and running the Azure Storage Emulator as we move to more flexible connection options. Please take a look at our [Getting Started](https://docs.microsoft.com/en-us/azure/vs-azure-tools-storage-manage-with-storage-explorer?tabs=linux#work-with-local-development-storage) page.

Note also that in our 1.4.0 release, we will be adding some features that should make connecting to any emulator easier.

**Comment by onionhammer** [comment]
@craxal The emulator is definitely already installed and running when I see the above error message. Storage Explorer simply isnt compatible with that version, and prompts you to download a more recent version of the storage emulator

**Comment by craxal** [comment]
Seems odd that you can't preserve test data between versions of the emulator. What versions of the Azure API does 5.4 use? How about the current version of the emulator?

What services do you test against the emulator usually? You might consider using [Azurite](https://github.com/azure/azurite), which is multiplatform and is being actively developed.
