### ISSUE TITLE
View Queues

### ISSUE THREAD

**Issue by folarina-cloud** [microsoft/AzureStorageExplorer#4590]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19

### Regression From

1.18

### Architecture

x64

### Platform

Windows

### Bug Description

Unable to retrieve child resources.

<Details>
{
  "name": "RestError",
  "message": "request to https://ewd56ymmx0d69pplkbnloo3.queue.core.windows.net/?include=metadata&comp=list&timeout=30 failed, reason: getaddrinfo ENOTFOUND ewd56ymmx0d69pplkbnloo3.queue.core.windows.net",
  "stack": "RestError: request to https://ewd56ymmx0d69pplkbnloo3.queue.core.windows.net/?include=metadata&comp=list&timeout=30 failed, reason: getaddrinfo ENOTFOUND ewd56ymmx0d69pplkbnloo3.queue.core.windows.net\n    at new RestError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:2362:28)\n    at NodeFetchHttpClient.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:2547:35)\n    at step (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.throw (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:124:57)\n    at rejected (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:69)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
  "code": "REQUEST_SEND_ERROR",
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://ewd56ymmx0d69pplkbnloo3.queue.core.windows.net/?include=metadata&comp=list&timeout=30",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2020-04-08"
        },
        "user-agent": {
          "name": "user-agent",
          "value": "Microsoft Azure Storage Explorer, 1.19.1, win32 azsdk-js-storagequeue/12.3.1 (NODE-VERSION v12.16.3; Windows_NT 10.0.19043)"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "699ff5ef-6a11-4278-81a2-0051e1414511"
        },
        "x-ms-date": {
          "name": "x-ms-date",
          "value": "Thu, 17 Jun 2021 10:51:16 GMT"
        },
        "authorization": {
          "name": "authorization",
          "value": "SharedKey ewd56ymmx0d69pplkbnloo3:2pET1e2l/zIYXJD+ky/8lotvTn5F5zgCRAxC3C0/zKE="
        },
        "cookie": {
          "name": "Cookie",
          "value": ""
        }
      }
    },
    "withCredentials": false,
    "timeout": 0,
    "keepAlive": true,
    "requestId": "699ff5ef-6a11-4278-81a2-0051e1414511",
    "operationSpec": {
      "httpMethod": "GET",
      "urlParameters": [
        {
          "parameterPath": "url",
          "mapper": {
            "required": true,
            "serializedName": "url",
            "defaultValue": "",
            "type": {
              "name": "String"
            }
          },
          "skipEncoding": true
        }
      ],
      "queryParameters": [
        {
          "parameterPath": [
            "options",
            "prefix"
          ],
          "mapper": {
            "serializedName": "prefix",
            "type": {
              "name": "String"
            }
          }
        },
        {
          "parameterPath": [
            "options",
            "marker"
          ],
          "mapper": {
            "serializedName": "marker",
            "type": {
              "name": "String"
            }
          }
        },
        {
          "parameterPath": [
            "options",
            "maxPageSize"
          ],
          "mapper": {
            "serializedName": "maxresults",
            "constraints": {
              "InclusiveMinimum": 1
            },
            "type": {
              "name": "Number"
            }
          }
        },
        {
          "parameterPath": [
            "options",
            "include"
          ],
          "mapper": {
            "serializedName": "include",
            "type": {
              "name": "Sequence",
              "element": {
                "type": {
                  "name": "Enum",
                  "allowedValues": [
                    "metadata"
                  ]
                }
              }
            }
          },
          "collectionFormat": ","
        },
        {
          "parameterPath": [
            "options",
            "timeoutInSeconds"
          ],
          "mapper": {
            "serializedName": "timeout",
            "constraints": {
              "InclusiveMinimum": 0
            },
            "type": {
              "name": "Number"
            }
          }
        },
        {
          "parameterPath": "comp",
          "mapper": {
            "required": true,
            "isConstant": true,
            "serializedName": "comp",
            "defaultValue": "list",
            "type": {
              "name": "String"
            }
          }
        }
      ],
      "headerParameters": [
        {
          "parameterPath": "version",
          "mapper": {
            "required": true,
            "isConstant": true,
            "serializedName": "x-ms-version",
            "defaultValue": "2020-04-08",
            "type": {
              "name": "String"
            }
          }
        },
        {
          "parameterPath": [
            "options",
            "requestId"
          ],
          "mapper": {
            "serializedName": "x-ms-client-request-id",
            "type": {
              "name": "String"
            }
          }
        }
      ],
      "responses": {
        "200": {
          "bodyMapper": {
            "xmlName": "EnumerationResults",
            "serializedName": "ListQueuesSegmentResponse",
            "type": {
              "name": "Composite",
              "className": "ListQueuesSegmentResponse",
              "modelProperties": {
                "serviceEndpoint": {
                  "xmlIsAttribute": true,
                  "xmlName": "ServiceEndpoint",
                  "required": true,
                  "serializedName": "ServiceEndpoint",
                  "type": {
                    "name": "String"
                  }
                },
                "prefix": {
                  "xmlName": "Prefix",
                  "required": true,
                  "serializedName": "Prefix",
                  "type": {
                    "name": "String"
                  }
                },
                "marker": {
                  "xmlName": "Marker",
                  "serializedName": "Marker",
                  "type": {
                    "name": "String"
                  }
                },
                "maxPageSize": {
                  "xmlName": "MaxResults",
                  "required": true,
                  "serializedName": "MaxResults",
                  "type": {
                    "name": "Number"
                  }
                },
                "queueItems": {
                  "xmlIsWrapped": true,
                  "xmlName": "Queues",
                  "xmlElementName": "Queue",
                  "serializedName": "QueueItems",
                  "type": {
                    "name": "Sequence",
                    "element": {
                      "type": {
                        "name": "Composite",
                        "className": "QueueItem"
                      }
                    }
                  }
                },
                "continuationToken": {
                  "xmlName": "NextMarker",
                  "required": true,
                  "serializedName": "NextMarker",
                  "type": {
                    "name": "String"
                  }
                }
              }
            }
          },
          "headersMapper": {
            "serializedName": "service-listqueuessegment-headers",
            "type": {
              "name": "Composite",
              "className": "ServiceListQueuesSegmentHeaders",
              "modelProperties": {
                "requestId": {
                  "serializedName": "x-ms-request-id",
                  "type": {
                    "name": "String"
                  }
                },
                "version": {
                  "serializedName": "x-ms-version",
                  "type": {
                    "name": "String"
                  }
                },
                "date": {
                  "serializedName": "date",
                  "type": {
                    "name": "DateTimeRfc1123"
                  }
                },
                "clientRequestId": {
                  "serializedName": "x-ms-client-request-id",
                  "type": {
                    "name": "String"
                  }
                },
                "errorCode": {
                  "serializedName": "x-ms-error-code",
                  "type": {
                    "name": "String"
                  }
                }
              }
            }
          }
        },
        "default": {
          "bodyMapper": {
            "serializedName": "StorageError",
            "type": {
              "name": "Composite",
              "className": "StorageError",
              "modelProperties": {
                "message": {
                  "xmlName": "Message",
                  "serializedName": "Message",
                  "type": {
                    "name": "String"
                  }
                },
                "code": {
                  "xmlName": "Code",
                  "serializedName": "Code",
                  "type": {
                    "name": "String"
                  }
                }
              }
            }
          },
          "headersMapper": {
            "serializedName": "service-listqueuessegment-headers",
            "type": {
              "name": "Composite",
              "className": "ServiceListQueuesSegmentHeaders",
              "modelProperties": {
                "requestId": {
                  "serializedName": "x-ms-request-id",
                  "type": {
                    "name": "String"
                  }
                },
                "version": {
                  "serializedName": "x-ms-version",
                  "type": {
                    "name": "String"
                  }
                },
                "date": {
                  "serializedName": "date",
                  "type": {
                    "name": "DateTimeRfc1123"
                  }
                },
                "clientRequestId": {
                  "serializedName": "x-ms-client-request-id",
                  "type": {
                    "name": "String"
                  }
                },
                "errorCode": {
                  "serializedName": "x-ms-error-code",
                  "type": {
                    "name": "String"
                  }
                }
              }
            }
          }
        }
      },
      "isXML": true,
      "serializer": {
        "modelMappers": {
          "CorsRule": {
            "serializedName": "CorsRule",
            "type": {
              "name": "Composite",
              "className": "CorsRule",
              "modelProperties": {
                "allowedOrigins": {
                  "xmlName": "AllowedOrigins",
                  "required": true,
                  "serializedName": "AllowedOrigins",
                  "type": {
                    "name": "String"
                  }
                },
                "allowedMethods": {
                  "xmlName": "AllowedMethods",
                  "required": true,
                  "serializedName": "AllowedMethods",
                  "type": {
                    "name": "String"
                  }
                },
                "allowedHeaders": {
                  "xmlName": "AllowedHeaders",
                  "required": true,
                  "serializedName": "AllowedHeaders",
                  "type": {
                    "name": "String"
                  }
                },
                "exposedHeaders": {
                  "xmlName": "ExposedHeaders",
                  "required": true,
                  "serializedName": "ExposedHeaders",
                  "type": {
                    "name": "String"
                  }
                },
                "maxAgeInSeconds": {
                  "xmlName": "MaxAgeInSeconds",
                  "required": true,
                  "serializedName": "MaxAgeInSeconds",
                  "constraints": {
                    "InclusiveMinimum": 0
                  },
                  "type": {
                    "name": "Number"
                  }
                }
              }
            }
          },
          "GeoReplication": {
            "serializedName": "GeoReplication",
            "type": {
              "name": "Composite",
              "className": "GeoReplication",
              "modelProperties": {
                "status": {
                  "xmlName": "Status",
                  "required": true,
                  "serializedName": "Status",
                  "type": {
                    "name": "String"
                  }
                },
                "lastSyncOn": {
                  "xmlName": "LastSyncTime",
                  "required": true,
                  "serializedName": "LastSyncTime",
                  "type": {
                    "name": "DateTimeRfc1123"
                  }
                }
              }
            }
          },
          "ListQueuesSegmentResponse": {
            "xmlName": "EnumerationResults",
            "serializedName": "ListQueuesSegmentResponse",
            "type": {
              "name": "Composite",
              "className": "ListQueuesSegmentResponse",
              "modelProperties": {
                "serviceEndpoint": {
                  "xmlIsAttribute": true,
                  "xmlName": "ServiceEndpoint",
                  "required": true,
                  "serializedName": "ServiceEndpoint",
                  "type": {
                    "name": "String"
                  }
                },
                "prefix": {
                  "xmlName": "Prefix",
                  "required": true,
                  "serializedName": "Prefix",
                  "type": {
                    "name": "String"
                  }
                },
                "marker": {
                  "xmlName": "Marker",
                  "serializedName": "Marker",
                  "type": {
                    "name": "String"
                  }
                },
                "maxPageSize": {
                  "xmlName": "MaxResults",
                  "required": true,
                  "serializedName": "MaxResults",
                  "type": {
                    "name": "Number"
                  }
                },
                "queueItems": {
                  "xmlIsWrapped": true,
                  "xmlName": "Queues",
                  "xmlElementName": "Queue",
                  "serializedName": "QueueItems",
                  "type": {
                    "name": "Sequence",
                    "element": {
                      "type": {
                        "name": "Composite",
                        "className": "QueueItem"
                      }
                    }
                  }
                },
                "continuationToken": {
                  "xmlName": "NextMarker",
                  "required": true,
                  "serializedName": "NextMarker",
                  "type": {
                    "name": "String"
                  }
                }
              }
            }
          },
          "Logging": {
            "serializedName": "Logging",
            "type": {
              "name": "Composite",
              "className": "Logging",
              "modelProperties": {
                "version": {
                  "xmlName": "Version",
                  "required": true,
                  "serializedName": "Version",
                  "type": {
                    "name": "String"
                  }
                },
                "deleteProperty": {
                  "xmlName": "Delete",
                  "required": true,
                  "serializedName": "Delete",
                  "type": {
                    "name": "Boolean"
                  }
                },
                "read": {
                  "xmlName": "Read",
                  "required": true,
                  "serializedName": "Read",
                  "type": {
                    "name": "Boolean"
                  }
                },
                "write": {
                  "xmlName": "Write",
                  "required": true,
                  "serializedName": "Write",
                  "type": {
                    "name": "Boolean"
                  }
                },
                "retentionPolicy": {
                  "xmlName": "RetentionPolicy",
                  "required": true,
                  "serializedName": "RetentionPolicy",
                  "type": {
                    "name": "Composite",
                    "className": "RetentionPolicy"
                  }
                }
              }
            }
          },
          "Metrics": {
            "serializedName": "Metrics",
            "type": {
              "name": "Composite",
              "className": "Metrics",
              "modelProperties": {
                "version": {
                  "xmlName": "Version",
                  "serializedName": "Version",
                  "type": {
                    "name": "String"
                  }
                },
                "enabled": {
                  "xmlName": "Enabled",
                  "required": true,
                  "serializedName": "Enabled",
                  "type": {
                    "name": "Boolean"
                  }
                },
                "includeAPIs": {
                  "xmlName": "IncludeAPIs",
                  "serializedName": "IncludeAPIs",
                  "type": {
                    "name": "Boolean"
                  }
                },
                "retentionPolicy": {
                  "xmlName": "RetentionPolicy",
                  "serializedName": "RetentionPolicy",
                  "type": {
                    "name": "Composite",
                    "className": "RetentionPolicy"
                  }
                }
              }
            }
          },
          "QueueItem": {
            "xmlName": "Queue",
            "serializedName": "QueueItem",
            "type": {
              "name": "Composite",
              "className": "QueueItem",
              "modelProperties": {
                "name": {
                  "xmlName": "Name",
                  "required": true,
                  "serializedName": "Name",
                  "type": {
                    "name": "String"
                  }
                },
                "metadata": {
                  "xmlName": "Metadata",
                  "serializedName": "Metadata",
                  "type": {
                    "name": "Dictionary",
                    "value": {
                      "type": {
                        "name": "String"
                      }
                    }
                  }
                }
              }
            }
          },
          "QueueServiceProperties": {
            "xmlName": "StorageServiceProperties",
            "serializedName": "QueueServiceProperties",
            "type": {
              "name": "Composite",
              "className": "QueueServiceProperties",
              "modelProperties": {
                "queueAnalyticsLogging": {
                  "xmlName": "Logging",
                  "serializedName": "Logging",
                  "type": {
                    "name": "Composite",
                    "className": "Logging"
                  }
                },
                "hourMetrics": {
                  "xmlName": "HourMetrics",
                  "serializedName": "HourMetrics",
                  "type": {
                    "name": "Composite",
                    "className": "Metrics"
                  }
                },
                "minuteMetrics": {
                  "xmlName": "MinuteMetrics",
                  "serializedName": "MinuteMetrics",
                  "type": {
                    "name": "Composite",
                    "className": "Metrics"
                  }
                },
                "cors": {
                  "xmlIsWrapped": true,
                  "xmlName": "Cors",
                  "xmlElementName": "CorsRule",
                  "serializedName": "Cors",
                  "type": {
                    "name": "Sequence",
                    "element": {
                      "type": {
                        "name": "Composite",
                        "className": "CorsRule"
                      }
                    }
                  }
                }
              }
            }
          },
          "QueueServiceStatistics": {
            "xmlName": "StorageServiceStats",
            "serializedName": "QueueServiceStatistics",
            "type": {
              "name": "Composite",
              "className": "QueueServiceStatistics",
              "modelProperties": {
                "geoReplication": {
                  "xmlName": "GeoReplication",
                  "serializedName": "GeoReplication",
                  "type": {
                    "name": "Composite",
                    "className": "GeoReplication"
                  }
                }
              }
            }
          },
          "RetentionPolicy": {
            "serializedName": "RetentionPolicy",
            "type": {
              "name": "Composite",
              "className": "RetentionPolicy",
              "modelProperties": {
                "enabled": {
                  "xmlName": "Enabled",
                  "required": true,
                  "serializedName": "Enabled",
                  "type": {
                    "name": "Boolean"
                  }
                },
                "days": {
                  "xmlName": "Days",
                  "serializedName": "Days",
                  "constraints": {
                    "InclusiveMinimum": 1
                  },
                  "type": {
                    "name": "Number"
                  }
                }
              }
            }
          },
          "ServiceGetPropertiesHeaders": {
            "serializedName": "service-getproperties-headers",
            "type": {
              "name": "Composite",
              "className": "ServiceGetPropertiesHeaders",
              "modelProperties": {
                "requestId": {
                  "serializedName": "x-ms-request-id",
                  "type": {
                    "name": "String"
                  }
                },
                "version": {
                  "serializedName": "x-ms-version",
                  "type": {
                    "name": "String"
                  }
                },
                "clientRequestId": {
                  "serializedName": "x-ms-client-request-id",
                  "type": {
                    "name": "String"
                  }
                },
                "errorCode": {
                  "serializedName": "x-ms-error-code",
                  "type": {
                    "name": "String"
                  }
                }
              }
            }
          },
          "ServiceGetStatisticsHeaders": {
            "serializedName": "service-getstatistics-headers",
            "type": {
              "name": "Composite",
              "className": "ServiceGetStatisticsHeaders",
              "modelProperties": {
                "requestId": {
                  "serializedName": "x-ms-request-id",
                  "type": {
                    "name": "String"
                  }
                },
                "version": {
                  "serializedName": "x-ms-version",
                  "type": {
                    "name": "String"
                  }
                },
                "date": {
                  "serializedName": "date",
                  "type": {
                    "name": "DateTimeRfc1123"
                  }
                },
                "clientRequestId": {
                  "serializedName": "x-ms-client-request-id",
                  "type": {
                    "name": "String"
                  }
                },
                "errorCode": {
                  "serializedName": "x-ms-error-code",
                  "type": {
                    "name": "String"
                  }
                }
              }
            }
          },
          "ServiceListQueuesSegmentHeaders": {
            "serializedName": "service-listqueuessegment-headers",
            "type": {
              "name": "Composite",
              "className": "ServiceListQueuesSegmentHeaders",
              "modelProperties": {
                "requestId": {
                  "serializedName": "x-ms-request-id",
                  "type": {
                    "name": "String"
                  }
                },
                "version": {
                  "serializedName": "x-ms-version",
                  "type": {
                    "name": "String"
                  }
                },
                "date": {
                  "serializedName": "date",
                  "type": {
                    "name": "DateTimeRfc1123"
                  }
                },
                "clientRequestId": {
                  "serializedName": "x-ms-client-request-id",
                  "type": {
                    "name": "String"
                  }
                },
                "errorCode": {
                  "serializedName": "x-ms-error-code",
                  "type": {
                    "name": "String"
                  }
                }
              }
            }
          },
          "ServiceSetPropertiesHeaders": {
            "serializedName": "service-setproperties-headers",
            "type": {
              "name": "Composite",
              "className": "ServiceSetPropertiesHeaders",
              "modelProperties": {
                "requestId": {
                  "serializedName": "x-ms-request-id",
                  "type": {
                    "name": "String"
                  }
                },
                "version": {
                  "serializedName": "x-ms-version",
                  "type": {
                    "name": "String"
                  }
                },
                "clientRequestId": {
                  "serializedName": "x-ms-client-request-id",
                  "type": {
                    "name": "String"
                  }
                },
                "errorCode": {
                  "serializedName": "x-ms-error-code",
                  "type": {
                    "name": "String"
                  }
                }
              }
            }
          },
          "StorageError": {
            "serializedName": "StorageError",
            "type": {
              "name": "Composite",
              "className": "StorageError",
              "modelProperties": {
                "message": {
                  "xmlName": "Message",
                  "serializedName": "Message",
                  "type": {
                    "name": "String"
                  }
                },
                "code": {
                  "xmlName": "Code",
                  "serializedName": "Code",
                  "type": {
                    "name": "String"
                  }
                }
              }
            }
          }
        },
        "isXML": true
      }
    }
  }
}

### Steps to Reproduce

Click Queues

### Actual Experience

Bug on click queues

### Expected Experience

View queues to blob store

### Additional Context

queues

**Comment by MRayermannMSFT** [comment]
@folarina-cloud 

- What does "view queues to blob store" mean?
- Has anything changed in your environment since installing 1.19?
- Are you behind a proxy?
- Can you try downloading and installing 1.18 again and confirming that this is a regression from 1.19? You can find that here https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.18.1

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
