### ISSUE TITLE
The 'Name' column can't be moved for one File Share & ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4595]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 202100618.7
**Branch**: rel/1.20.0
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Big Sur 11.4
**Architecture**: ia32/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Bug Descriptions ##
The 'Name' column can't be moved for one File Share & ADLS Gen2 blob container. 

## Steps to Reproduce ##
1. Open one storage account -> File Shares.
2. Select one file share -> Open it.
3. Try to move the 'Name' column.
4. Check whether it can be moved.

## Expected Experience ##
It can be moved.

## Actual Experience ##
It can not be moved.
![actualmove](https://user-images.githubusercontent.com/41351993/122732271-b5225280-d2ae-11eb-8d12-9883ccce87ba.gif)

## Addition Context ##
This issue doesn't reproduce for one regular blob container & resource group.
![regular](https://user-images.githubusercontent.com/41351993/122732217-a50a7300-d2ae-11eb-9652-bdf3fb320d05.gif)

**Comment by MRayermannMSFT** [comment]
Won't fix for now. We expect this to be fixed in the future when we move to new version data tables col reorder plugin for Gen2 and File Shares.
