### ISSUE TITLE
The blob versions can't be filtered by the blob tags

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4596]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 202100618.7
**Branch**: rel/1.20.0
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Big Sur 11.4
**Architecture**: ia32/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one GPV2 storage account -> Blob Containers (Make sure the blob versioning is enabled).
2. Create a blob container -> Upload one blob.
3. Right click the blob -> Click 'Edit Tags...'.
4. Add a blob tag [tag key ='key1', tag value='v1'] -> Save it.
5. Then delete the blob -> Switch to 'All blobs and blobs without current version'.
6. Click 'Show Filter Panel' -> Select 'Tag Filters'.
7. Add Filter [tag key ='key1', tag value='v1'] -> Click 'Apply Filters'.
8. Check whether there is a blob version.

## Expected Experience ##
There is a blob version.

## Actual Experience ##
There is no blob version.

**Comment by MRayermannMSFT** [comment]
For 1.21, just look at the options and come up with a plan for a future milestone (Not the "future" milestone, but like a milestone in the literal future, sometime after 1.21, do you get what I mean? Hopefully you do.)

**Comment by v-xianya** [comment]
I got what you mean.😂

**Comment by JasonYeMSFT** [comment]
This is by design. Currently get blob by tags uses a different API from listing. That API will only filter blobs that are "active" (non-soft deleted and current version if blob versioning is enabled).
