### ISSUE TITLE
Cannot generate 'Shared Acess Signature' for a blob container

### ISSUE THREAD

**Issue by sakinaLaanani** [microsoft/AzureStorageExplorer#4597]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.17.0

### Architecture

x64

### Platform

macOS

### OS Version

macOS Big Sur

### Bug Description

Cannot generate 'Shared Acess Signature' for a blob container

### Steps to Reproduce

1. Launch Storage Explorer
2. Expand the storage account list
3. Expand a specific storage account
4. Expand the blob containers list
5. Right click on a specific blob container
6. The menu does not display ‘shared access signature’ anymore 

If you go to the storage account
1. Right click on a storage account
2. The option ‘’shared access signature’ appears has usual, click on it
3. Click on create
4. A pop up with the message ‘Erreur durant l'appel de Stockage Azure :{}’ appears

### Actual Experience

Impossible to generate a Shared Access Signature from the desktop app for any blob container. However it's still possible to generate a shared access signature from the web app : portal.azure.com 

When trying to generate a shared access signature for a blob container the option does not appear in the menu

When trying to generate a shared access signature for all blob containers in a storage account, the option appears and when trying to create the signature an error message appears in the pop up

<img width="568" alt="Capture d’écran 2021-06-21 à 12 54 47" src="https://user-images.githubusercontent.com/25738927/122751364-f5260d00-d28f-11eb-9cd3-80f01f72af15.png">

<img width="500" alt="Capture d’écran 2021-06-21 à 12 56 09" src="https://user-images.githubusercontent.com/25738927/122751500-1dae0700-d290-11eb-80cb-880822c3273e.png">

<img width="553" alt="Capture d’écran 2021-06-15 à 09 59 46" src="https://user-images.githubusercontent.com/25738927/122742217-036f2b80-d286-11eb-87a1-eaafb23b9c21.png">

**Comment by MRayermannMSFT** [comment]
@sakinaLaanani can you confirm if you have access to the keys to the storage account? To do so:

1. Click on the node for the storage account
2. In the bottom left of the application, click on "Properties"
3. Scroll down in the properties view until you see "Primary Key" and "Secondary Key"
4. Click on the eye icons next to those to reveal the values
5. Check and see if the keys for the account are there and corrrect

**Comment by sakinaLaanani** [comment]
@MRayermannMSFT  Indeed, I dont have access to the keys, when I click on the eye icon I see the message 'Error while loading this property'
How can I solve this ?
What roles do I need ?

**Comment by sakinaLaanani** [comment]
Hi @MRayermannMSFT,
Please can you help me figure out the roles needed to fix this issue ?

**Comment by JasonYeMSFT** [comment]
@sakinaLaanani You will need to go to portal.azure.com, navigate to your storage account and enable listing keys for that storage account.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you still need help, we recommend you either:
1. open up an azure support ticket from the portal
2. open a new issue here
