### ISSUE TITLE
Unable to save a file directly to ASE from a software application. 

### ISSUE THREAD

**Issue by cyschray** [microsoft/AzureStorageExplorer#4600]
Recently migrated files from Gameshare storage to ASE. With several computers and equipment in the lab this is not a smooth operation. 
We identified a limitation or inefficiency that we’re unable to save a file directly from an application to Azure Storage Explorer. We have to save the file locally to the local drive or USB drive and then upload it to ASE.

Is this a tool limitation? Is there an explanation for this? Do you have a work around?

**Comment by JasonYeMSFT** [comment]
@cyshray Could you elaborate what you mean by "save a file directly to ASE from a software application"? Do you know what data transfer protocol the software application is using?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you still need help, we recommend you either:
1. open up an azure support ticket from the portal
2. open a new issue here
