### ISSUE TITLE
Error: Hub Controller process exited prematurely with exit code 3221225701

### ISSUE THREAD

**Issue by schrollm** [microsoft/AzureStorageExplorer#4607]
Hi,

I have a user who is receiving the following attached error when launching Storage Explorer:
![2021-06-22_14-28-15](https://user-images.githubusercontent.com/86320731/122979850-0a6d6b00-d366-11eb-8006-d8740d5fd7d6.png)

The PC is running Windows 10 build 19041 (version 2004).  
So far, I have done:
Install/Reinstall including deleting StorageExplorer folder in %appdata%
Ran .net repair tool
Ran DISM and SFC with no issues found
Cleared stored creds and disconnected any MS accounts in settings
Issue present in another profile

Attached are the logs from %temp%\servicehub\logs and %appdata%\StorageExplorer\Microsoft Azure Storage Explorer
[Temp_Servicehublogs.zip](https://github.com/microsoft/AzureStorageExplorer/files/6696683/Temp_Servicehublogs.zip)
[AppData_StorageExplorer.zip](https://github.com/microsoft/AzureStorageExplorer/files/6696684/AppData_StorageExplorer.zip)

**Comment by schrollm** [comment]
This issue is resolved.  It turned out to be a firewall/AV issue.

**Comment by pablospe** [comment]
@schrollm Could you provide more details how you fixed it?
