### ISSUE TITLE
The created snapshots for one blob doesn't display on manage snapshot editor

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#461]
**Storage Explorer Version**:1.4.0
 **Platform/OS Version**: Windows
**Architecture**: ia32
**Build Number**: 20180721.2
**Commit**: 9a25a7d2
**Regression From**: Previous release 1.3.1(20180711.1)

#### Steps to Reproduce: ####
1. Expand one account and open one blob container. 
2. Create a snapshot for one blob -> Right click the blob then select 'Manage Snapshots'.
3. Check whether the created snapshot displays well or not.

#### Expected Experience: ####
The created snapshot displays well on the manage snapshot editor.

#### Actual Experience: ####
The snapshot doesn't display on the manage snapshot editor.

**Comment by v-xianya** [comment]
Verified this issue on the latest master build 20180724.5. Fixed. Could you help to resolve it?

**Comment by JasonYeMSFT** [comment]
Fixed in release branch. Closed.
