### ISSUE TITLE
There is no update notification when running '/StorageExplorer --add-update-group=CTI' to open Storage Explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4611]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 202100623.3
**Branch**: rel/1.20.0
**Platform/OS**: Linux Ubuntu 16.04/Linux Ubuntu 20.04
**Architecture**: x64
**How Found**: From running test case
**Regression From**: Previous release (1.19.1)

## Steps to Reproduce ##
1. Download and extra 'StorageExplorer-linux-x64.tar.gz' -> Install the .NET Core Runtime.
2. Open Terminal -> Use cd to the path where the folder 'StorageExplorer-linux-x64' is located.
3. Run './StorageExplorer --add-update-group=CTI' to open Storage Explorer.
4. Check whether there is an update notification asking you to update to 1.1.0.

## Expected Experience ##
There is an update notification.

## Actual Experience ##
There is no update notification.

## Additional Context ##
This issue doesn't reproduce on Windows & MacOS.

**Comment by MRayermannMSFT** [comment]
Fix merged into main.
