### ISSUE TITLE
There is an error when clicking 'Copy' for one blob in an Azure AD attached blob container (rbac role 'Storage Blob Data Reader')

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4612]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 202100623.3
**Branch**: rel/1.20.0
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Big Sur 11.4
**Architecture**: ia32/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Select one non-ADLS Gen2 blob container which contains blobs -> Add the rbac role 'Storage Blob Data Reader' then assign to one azure account.
2. Attach the blob container via Azure AD.
3. Open the attached blob container -> Click 'Copy' on the toolbar.
4. Check whether there is an error.

## Expected Experience ##
There is no error.

## Actual Experience ##
There is an error.
![image](https://user-images.githubusercontent.com/41351993/123069970-ea14dd80-d445-11eb-9995-336ec45906be.png)

## Additional Info ##
1. This issue doesn't reproduce when adding rbac role 'Storage Blob Data Reader/Owner/Contributor' at storage account level.
2. This issue also reproduces when adding 'Storage Blob Data Owner/Contributor' role at blob container level.
3. There is a similar issue: [3293](https://github.com/microsoft/AzureStorageExplorer/issues/3293).

**Comment by JasonYeMSFT** [comment]
The error was due to a request to get a user delegation key to be able to generate the SAS using user's Azure AD credential. The only thing we can do is to improve the error message.

**Comment by JasonYeMSFT** [comment]
Error message updated to be "Unable to get user delegation key. Please check the permission of your Azure AD credential.".

**Comment by v-xianya** [comment]
Verified this issue on the build 20210708.1. The error message has been updated!

**Comment by v-xianya** [comment]
Update:
On the latest build main 20220719.17.(V1.25.0) 
There is no error when clicking 'Copy'.
