### ISSUE TITLE
The title of the dialog 'Propagate Access Control Lists' is replaced by the title of the dialog which is opened previously

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4614]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 202100623.3
**Branch**: rel/1.20.0
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Big Sur 11.4
**Architecture**: ia32/x64
**How Found**: Exploratory testing
**Regression From**: Previous release (1.19.1)

## Steps to Reproduce ##
1. Launch Storage Explorer.
2. Expand one ADLS Gen2 storage account -> Blob Containers.
3. Select one blob container -> Right click it.
4. Click 'Propagate Access Control Lists...' -> Observe the title of the dialog -> Close the dialog.
5.  Right click the blob container -> Click 'Properties...' -> Close the 'Properties' dialog.
6. Then open the 'Propagate Access Control Lists' dialog again.
7. Check whether the title of the dialog is replaced or not.

## Expected Experience ##
The title of the dialog is not replaced.

## Actual Experience ##
The title of the dialog is replaced.
![image](https://user-images.githubusercontent.com/41351993/123087070-b8584280-d456-11eb-991a-a03dec66f640.png)

## Additional Context ##
According to the title of other dialog, it would be better to update the title of dialog from 'StorageExplorer' to 'Propagate Access Control Lists'. 
![image](https://user-images.githubusercontent.com/41351993/123085394-c60cc880-d454-11eb-962b-efee567b87c5.png)

**Comment by craxal** [comment]
Ah, so the Propagate dialog doesn't declare a view model, so the preload script doesn't run a particular block of code. The code block in question is responsible for setting the window title.
