### ISSUE TITLE
Storage Explorer hangs when disk space is depleted by it's logs

### ISSUE THREAD

**Issue by choukimasri** [microsoft/AzureStorageExplorer#4615]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

latest

### Regression From

N/A

### Architecture

x64

### Platform

Windows

### OS Version

Windows 10 2004

### Bug Description

Hello !

Storage explorer hanged when my disk space was depleted as I was trying to move big files between az storage accounts

I couldn't retry the failed jobs as they are not guarded after exit

Storage explorer should be able to manage its log stack and propose to delete old logs when it hits storage capacity.

Best Regards !

### Steps to Reproduce

1. produce logs to fill your disk space
2.  the current operation will hang or fail

### Actual Experience

Transfer hangs queued awaiting log code to allocate disk space probably

### Expected Experience

Clear old logs prompt. and the session to be saved when explorer is restarted.

**Comment by MRayermannMSFT** [comment]
@choukimasri do you know if the issue was being caused by the Storage Explorer logs or the AzCopy logs?

**Comment by choukimasri** [comment]
@MRayermannMSFT probably the azcopy as they are stored in %Users%/user/.azcopy/
Storage Explorer exits ignoring active transfers.

**Comment by MRayermannMSFT** [comment]
@choukimasri we've decided to not go through with any sort of auto log cleaning. We'd rather this be something you/users do on their own. Here's some things to help you going foward:
- Docs on an azcopy command that helps you clean the log folder (assuming you don't want to just delete everything in there): https://docs.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-jobs-clean?toc=/azure/storage/blobs/toc.json
- There is a setting in Storage Explorer for decreasing the AzCopy log verbosity. If you are getting ready to start a long running transfer and you are low on disk space, you can consider turning the verbosity down or completely off to decrease the chance of what you saw happening. You can find the setting under Settings > Transfers > AzCopy > Log Level.
![image](https://user-images.githubusercontent.com/21112697/135684570-50a6d973-dddc-4c0c-84e6-0c6f5d2c2a0d.png)

**Comment by choukimasri** [comment]
Plain shameful, it's probably the easy way to solve issues nowadays, time to seek  alternatives to Azure Storage Explorer
