### ISSUE TITLE
Error when trying to access a connection string

### ISSUE THREAD

**Issue by MahadiPelican** [microsoft/AzureStorageExplorer#4616]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.0

### Regression From

1.18.0

### Architecture

i86

### Platform

Windows

### Bug Description

{
  "name": "TypeError",
  "message": "Cannot read property 'uids' of undefined",
  "stack": "TypeError: Cannot read property 'uids' of undefined\n    at StorageExplorerProvider.<anonymous> (file:///C:/Users/Peter%20Watson/AppData/Local/Programs/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/StorageExplorer/StorageExplorerProvider.js:290:51)\n    at step (file:///C:/Users/Peter%20Watson/AppData/Local/Programs/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/StorageExplorer/StorageExplorerProvider.js:48:23)\n    at Object.next (file:///C:/Users/Peter%20Watson/AppData/Local/Programs/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/StorageExplorer/StorageExplorerProvider.js:29:53)\n    at fulfilled (file:///C:/Users/Peter%20Watson/AppData/Local/Programs/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/StorageExplorer/StorageExplorerProvider.js:20:58)"
}

### Steps to Reproduce

Select Resource
Clicked storage account or service.
Pasted the connection string

### Actual Experience

{
  "name": "TypeError",
  "message": "Cannot read property 'uids' of undefined",
  "stack": "TypeError: Cannot read property 'uids' of undefined\n    at StorageExplorerProvider.<anonymous> (file:///C:/Users/Peter%20Watson/AppData/Local/Programs/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/StorageExplorer/StorageExplorerProvider.js:290:51)\n    at step (file:///C:/Users/Peter%20Watson/AppData/Local/Programs/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/StorageExplorer/StorageExplorerProvider.js:48:23)\n    at Object.next (file:///C:/Users/Peter%20Watson/AppData/Local/Programs/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/StorageExplorer/StorageExplorerProvider.js:29:53)\n    at fulfilled (file:///C:/Users/Peter%20Watson/AppData/Local/Programs/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/CloudHub/js/Providers/StorageExplorer/StorageExplorerProvider.js:20:58)"
}

**Comment by JasonYeMSFT** [comment]
@MahadiPelican Could you share your connection string after redacting your sensitive information (e.g. storage account name, sas token, key, etc.)?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you still need help, we recommend you either:
1. open up an azure support ticket from the portal
2. open a new issue here
