### ISSUE TITLE
Azure Blob Storage- Unable to retrieve Blob Container after successful connection 

### ISSUE THREAD

**Issue by Apiwe-Nombanga-by** [microsoft/AzureStorageExplorer#4617]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.1

### Architecture

i86

### Storage Explorer Build Number

20210425.1

### Platform

Windows

### Bug Description

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://byuserstorage50.blob.core.windows.net/?include=metadata&comp=list failed, reason: tunneling socket could not be established, statusCode=503",
  "stack": "FetchError: request to https://byuserstorage50.blob.core.windows.net/?include=metadata&comp=list failed, reason: tunneling socket could not be established, statusCode=503\n    at ClientRequest.<anonymous> (C:\\Users\\1026574\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1461:11)\n    at ClientRequest.emit (events.js:310:20)\n    at ClientRequest.onConnect (C:\\Users\\1026574\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\node_modules\\tunnel\\lib\\tunnel.js:157:23)\n    at Object.onceWrapper (events.js:417:26)\n    at ClientRequest.emit (events.js:310:20)\n    at Socket.socketOnData (_http_client.js:503:11)\n    at Socket.emit (events.js:310:20)\n    at addChunk (_stream_readable.js:286:12)\n    at readableAddChunk (_stream_readable.js:268:9)\n    at Socket.Readable.push (_stream_readable.js:209:10)",
  "type": "system",
  "errno": "ECONNRESET",
  "code": "ECONNRESET"
}

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/69901765/123111021-e3359d00-d43c-11eb-801e-6136776a177b.png)

### Actual Experience

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://byuserstorage50.blob.core.windows.net/?include=metadata&comp=list failed, reason: tunneling socket could not be established, statusCode=503",
  "stack": "FetchError: request to https://byuserstorage50.blob.core.windows.net/?include=metadata&comp=list failed, reason: tunneling socket could not be established, statusCode=503\n    at ClientRequest.<anonymous> (C:\\Users\\1026574\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1461:11)\n    at ClientRequest.emit (events.js:310:20)\n    at ClientRequest.onConnect (C:\\Users\\1026574\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\node_modules\\tunnel\\lib\\tunnel.js:157:23)\n    at Object.onceWrapper (events.js:417:26)\n    at ClientRequest.emit (events.js:310:20)\n    at Socket.socketOnData (_http_client.js:503:11)\n    at Socket.emit (events.js:310:20)\n    at addChunk (_stream_readable.js:286:12)\n    at readableAddChunk (_stream_readable.js:268:9)\n    at Socket.Readable.push (_stream_readable.js:209:10)",
  "type": "system",
  "errno": "ECONNRESET",
  "code": "ECONNRESET"
}

### Expected Experience

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://byuserstorage50.blob.core.windows.net/?include=metadata&comp=list failed, reason: tunneling socket could not be established, statusCode=503",
  "stack": "FetchError: request to https://byuserstorage50.blob.core.windows.net/?include=metadata&comp=list failed, reason: tunneling socket could not be established, statusCode=503\n    at ClientRequest.<anonymous> (C:\\Users\\1026574\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1461:11)\n    at ClientRequest.emit (events.js:310:20)\n    at ClientRequest.onConnect (C:\\Users\\1026574\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\node_modules\\tunnel\\lib\\tunnel.js:157:23)\n    at Object.onceWrapper (events.js:417:26)\n    at ClientRequest.emit (events.js:310:20)\n    at Socket.socketOnData (_http_client.js:503:11)\n    at Socket.emit (events.js:310:20)\n    at addChunk (_stream_readable.js:286:12)\n    at readableAddChunk (_stream_readable.js:268:9)\n    at Socket.Readable.push (_stream_readable.js:209:10)",
  "type": "system",
  "errno": "ECONNRESET",

  "code": "ECONNRESET"
}

![Azure](https://user-images.githubusercontent.com/69901765/123110815-b8e3df80-d43c-11eb-9043-3ccf83b04819.PNG)
![Azure](https://user-images.githubusercontent.com/69901765/123110967-db75f880-d43c-11eb-94f1-4b833db3e118.PNG)

### Additional Context

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://byuserstorage50.blob.core.windows.net/?include=metadata&comp=list failed, reason: tunneling socket could not be established, statusCode=503",
  "stack": "FetchError: request to https://byuserstorage50.blob.core.windows.net/?include=metadata&comp=list failed, reason: tunneling socket could not be established, statusCode=503\n    at ClientRequest.<anonymous> (C:\\Users\\1026574\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1461:11)\n    at ClientRequest.emit (events.js:310:20)\n    at ClientRequest.onConnect (C:\\Users\\1026574\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\node_modules\\tunnel\\lib\\tunnel.js:157:23)\n    at Object.onceWrapper (events.js:417:26)\n    at ClientRequest.emit (events.js:310:20)\n    at Socket.socketOnData (_http_client.js:503:11)\n    at Socket.emit (events.js:310:20)\n    at addChunk (_stream_readable.js:286:12)\n    at readableAddChunk (_stream_readable.js:268:9)\n    at Socket.Readable.push (_stream_readable.js:209:10)",
  "type": "system",
  "errno": "ECONNRESET",
  "code": "ECONNRESET"
}

****

**Comment by Apiwe-Nombanga-by** [comment]
Hi I need this fixed soon please

**Comment by JasonYeMSFT** [comment]
@Apiwe-Nombanga-by Are you behind a proxy? You can refer to https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#proxy-issues to learn how to configure proxy in Storage Explorer.

**Comment by MRayermannMSFT** [comment]
@Apiwe-Nombanga-by please also refer to https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network to learn about the various Storage Explorer proxy options. You may want to try using System Proxy or you will need to setup your app proxy settings.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you're still having problems we recommend opening an azure support ticket via the portal, or you can open a new issue here.
