### ISSUE TITLE
The uploaded folder disappear after backing to its parent directory

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#462]
**Storage Explorer Version**:1.4.0
 **Platform/OS Version**: Windows
**Architecture**: ia32
**Build Number**: 20180721.2
**Commit**: 9a25a7d2
**Regression From**: Previous release 1.3.1(20180711.1)

#### Steps to Reproduce: ####
1. Expand one account and open one blob container.
2. Upload a blob folder which is contains one blob file at least to it.
3. Open the uploaded blob folder then back to the parent directory.
4. Check whether the folder displays well or not. 

#### Expected Experience: ####
 The folder displays well on the parent directory.

#### Actual Experience: ####
The folder disappears after backing to the parent directory.

The blob files under the uploaded folder display on the parent directory directly.

**Comment by v-xianya** [comment]
Verified this issue on the latest master build 20180724.5. Fixed. Could you help to resolve it?

**Comment by JasonYeMSFT** [comment]
Fixed in release branch. Closed.
