### ISSUE TITLE
Keep a same URL between the 'Properties' dialog and 'Copy URL' for one ADLS Gen2 folder

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4621]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 202100624.6
**Branch**: rel/1.20.0
**Platform/OS**: Windows 10/ Linux Ubuntu 20.04/ MacOS Big Sur 11.4
**Architecture**: ia32/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Create a new folder.
3. Open the folder's properties dialog -> Copy the Blob URL then paste to the clipboard.
4. Close the dialog -> Right click the folder -> Click 'Copy URL'.
5. Paste the URL to the clipboard.
6. Check whether the URLs are the same.

## Expected Experience ##
The URLs are the same.

## Actual Experience ##
The URLs are different. (The URL from 'Copy URL' does end with a slash while the URL in the Properties dialog not)

1. Blob URL:
![image](https://user-images.githubusercontent.com/41351993/123230232-9b307c00-d509-11eb-8554-1f343eb738d6.png)

2. Copy URL: https://arbacadls.blob.core.windows.net/adls1/New%20Folder/

**Comment by JasonYeMSFT** [comment]
There is no universal correct way to show the urls. Won't fix for now.
