### ISSUE TITLE
issue with Azure Storage Explorer

### ISSUE THREAD

**Issue by dneedles** [microsoft/AzureStorageExplorer#4623]
Unable to retrieve child resources.

Details:
["RestError:﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.\nRequestId:312b57e4-d01e-006a-3b49-6928b4000000\nTime:2021-06-24T22:38:03.6245257Z</Message></Error>"]

**Comment by a1explorer** [comment]
I'm experiencing this issue as well.

**Comment by JasonYeMSFT** [comment]
@dneedles Did you meant to open this issue for #4627? If so, please track the communication there. @a1explorer Could you open a separate issue explaining details of you issue and provide basic information like Storage Explorer version, your OS, etc.?

**Comment by dneedles** [comment]
Looks like the problem is solved.  You can close the ticket.

Denise

**Comment by jinglouMSFT** [comment]
Closing...
