### ISSUE TITLE
There is an extra scrollbar in the 'Edit Tags' dialog

### ISSUE THREAD

**Issue by v-xinda** [microsoft/AzureStorageExplorer#4624]
**Storage Explorer Version:** 1.20.0-dev
**Build Number:** 20210625.5
**Branch:** rel/1.20.0
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ MacOS Big Sur 11.4
**How Found:** Exploratory testing
**Architecture:** ia32/x64
**Regression From**: Not a Regression

## Steps to Reproduce ##
1. Expand a storage account -> Blob Containers -> Create a blob container -> Upload one blob.
2. Right click the blob -> Click 'Edit Tags...' -> Pop up a 'Edit Tags' dialog.
3. Check whether there is no extra scrollbar in the dialog.

## Expected Experience ##
There is no extra scrollbar.

## Actual Experience ##
There is an extra scrollbar.
![image](https://user-images.githubusercontent.com/57662131/123390760-dbf1c900-d5cd-11eb-8f40-f72eb5d0788e.png)

**Comment by v-xianya** [comment]
Verified on build 20210710.1. Fixed.
