### ISSUE TITLE
It would be better to display the string 'Search Results' in the address bar when applying 'search by prefix' in one blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4625]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 202100625.5
**Branch**: rel/1.20.0
**Platform/OS**: Windows 10/ Linux Ubuntu 20.04/ MacOS Big Sur 11.4
**Architecture**: ia32/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Click 'Show Filter Panel'.
3. Type a character to the 'Search by prefix (case-sensitive)' box -> Click 'Hide Filter Panel'.
4. Observe the address bar.
5. Check whether the string 'Search Results' displays in the address bar.
 
## Expected Experience ##
The string 'Search Results' displays in the address bar.

## Actual Experience ##
The blob container name displays in the address bar.

## Additional Context ##
The string 'Filter Results' displays in the address bar after applying filters.
![image](https://user-images.githubusercontent.com/41351993/123399393-23c91e00-d5d7-11eb-9dc8-d6e8e77b1e26.png)

**Comment by MRayermannMSFT** [comment]
I did this!

**Comment by MRayermannMSFT** [comment]
![image](https://user-images.githubusercontent.com/21112697/129795128-22dae116-ff8d-4896-81d8-24c8f108aa37.png)
