### ISSUE TITLE
Fail to promote version in an Azure AD attached blob container with an error 'Insufficient credentials' (rbac role 'Storage Blob Data Owner')

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4626]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 202100625.5
**Branch**: rel/1.20.0
**Platform/OS**: Windows 10/ Linux Ubuntu 20.04/ MacOS Big Sur 11.4
**Architecture**: ia32/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Select one blob container (make sure the blob versioning is enabled) -> Add rbac role 'Storage Blob Data Owner' to it then assign to an azure account.
2. Attach the blob container via Azure AD.
3. Upload one blob -> Update its metadata to create a blob version.
4. Right click the blob -> Click 'Manage History -> Manage Versions'.
5. Select the blob version -> Click 'Promote Version'.
6. Check whether succeed to promote version.
 
## Expected Experience ##
Succeed to promote version.

## Actual Experience ##
Fail to promote version with an error 'Fail to start transfer: Insufficient credentials'.
![image](https://user-images.githubusercontent.com/41351993/123415304-a528ac80-d5e7-11eb-9c92-6b84032d3ee7.png)

## Additional Context ##
1. In this case, succeed to delete a blob and blob version.
2. This issue doesn't reproduce when adding rbac role 'Storage Blob Data Owner' at the storage account level.

**Comment by JasonYeMSFT** [comment]
At this point, service to service, which promote versions depends on, requires SAS generation. To generate a SAS using Azure AD credential, the user needs to be granted the permission to get user delegation key. In this case, the AAD credential doesn't grant such permission so this is expected.

Using both Auth credential for source and destination is unsupported right now. So this will be blocked until AzCopy add that support.

**Comment by MRayermannMSFT** [comment]
By design. Jason's explanation is correct.

**Comment by v-xianya** [comment]
Verified this issue on the build 1.26.0-dev/20220915.4.
Succeed to promote version in one Azure AD attached blob container with the rbac role 'Storage Blob Data Owner'.
![image](https://user-images.githubusercontent.com/41351993/190375517-20d36b35-dbfc-4cf6-9005-41872b6d1c01.png)
