### ISSUE TITLE
The error info is not translated when opening a SAS attached service whose original one has been deleted

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4628]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 20210628.1
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 20.04/ MacOS Big Sur 11.4
**Language**: All
**Architecture**: ia32/x64
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to reproduce ##
1. Launch Storage Explorer -> Open 'Settings' -> Application (Regional Settings) -> Select 'Français' -> Restart Storage Explorer.
2. Expand one storage account -> Queues.
3. Create a queue -> Attach the queue via SAS.
4. Delete the original queue -> Open the SAS attached queue.
5. There is an error info bar.
6. Check whether the error info is translated or not.

## Expect Experience ##
The error info is translated.

## Actual Experience ##
The error info is not translated. 
![image](https://user-images.githubusercontent.com/41351993/123621710-16619d00-d83e-11eb-8cb0-c7c18e27fd68.png)

**Comment by JasonYeMSFT** [comment]
This string comes from the service. We cannot translate this string.
