### ISSUE TITLE
An error reminder dialog still pops up when opening Storage Explore (.tar.gz file) with Linux dependencies installed

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4629]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 20210628.1
**Branch**: main
**Platform/OS**: Linux Ubuntu 20.04
**Architecture**: x64
**How Found**: From running test case
**Regression From**: Previous release (1.20.0)

## Steps to reproduce ##
1. Open a clean Linux machine with OS version Ubuntu 20.04
2. Download Linux signed build as tar.gz file then extract it.
3. Open terminal -> Navigate to where the Storage Explorer executable is located.
4. Open Storage Explorer by run './StorageExplorer'.
5. An error reminder dialog pops up.
6. Install the dependencies by running the below commands:
wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb; \
  sudo dpkg -i packages-microsoft-prod.deb; \
  sudo apt-get update; \
  sudo apt-get install -y apt-transport-https && \
  sudo apt-get update && \
  sudo apt-get install -y dotnet-runtime-2.1
7. Go to terminal -> Run './StorageExplorer'.
8. Check no error reminder dialog pops up.

## Expect Experience ##
No error reminder dialog pops up.

## Actual Experience ##
The error reminder dialog still pops up.
![image](https://user-images.githubusercontent.com/41351993/123625605-7eb27d80-d842-11eb-81bc-ef4715cb4884.png)

**Comment by MRayermannMSFT** [comment]
@v-xianya for 1.20, we'll be switching to .NET Core 3.1. I need to update the string in this dialog. Will use this issue to track that.

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT Thank you for the updates. This issue doesn't reproduce after installing ,NET Core 3.1.
