### ISSUE TITLE
High amount of errors when using 'copy blob container'

### ISSUE THREAD

**Issue by da1rren** [Microsoft/AzureStorageExplorer#463]
**Storage Explorer Version: 1.3.1**: 
**Platform/OS Version**: Windows 10 Builkd 20180711.1 
**Architecture**: ia32 
**Regression From**: Unknown 

#### Steps to Reproduce: ####
1. Copy container from azure to storage emulator using the 'Paste Blob Container' right click option

#### Expected Experience: ####

No or few error

#### Actual Experience: ####

I'm encountering a lot of errors.  They all read something like:
```
Server encountered an internal error. Please try again after some time. RequestId:6b307f74-15b9-4b94-a2d6-f3dc502bcfda Time:2018-07-23T11:49:42.7596018Z
Server encountered an internal error. Please try again after some time. RequestId:54787e78-6519-4bf0-abdb-197a14b3c2aa Time:2018-07-23T11:53:19.8344014Z
```
I don't think the issue is Azure side as we have no issues with the application and the connection I'm using is rock steady.

**Comment by craxal** [comment]
What emulator are you using? It's quite possible the issue is with the emulator, since the "server encountered an internal error".
