### ISSUE TITLE
stuck at splash screen

### ISSUE THREAD

**Issue by villora** [microsoft/AzureStorageExplorer#4631]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19

### Regression From

1.18.1

### Architecture

x64

### Platform

Windows

### Bug Description

Hi
I have an issue that is not shown in the troubleshooting guide.
Since I updated from 1.8.1 to 1.9.0 in Windows 10, I can't open storage explorer. It is stuck at splash screen and thats all
Regards

### Steps to Reproduce

Launch Storage Explorer

### Actual Experience

The application doesn't start

**Comment by JasonYeMSFT** [comment]
Could you try delete your app data and retry? You can find the app data at `C:\users\<username>\AppData\Roaming\StorageExplorer` or `%APPDATA%\Roaming\StorageExplorer`. Delete that app data directory and restart Storage Explorer.

**Comment by albertleigh** [comment]
I had a bad feeling that it might be the adf-extension-1.0.0; since there was a breaking change of the getTheme Api, we adopted it and bumped the adf-ext-version to 1.0.1. 
If users upgraded the ASE w/o the latest adf-ext@1.0.1, they would suck on the splash screen, meanwhile ase failed to init the old adf-ext and stuck there.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you still need help, we recommend you either:
1. open up an azure support ticket from the portal
2. open a new issue here
