### ISSUE TITLE
Network timeout error: connect ECONNREFUSED 20.38.104.166:443

### ISSUE THREAD

**Issue by jcherri689** [microsoft/AzureStorageExplorer#4632]
Unable to retrieve child resources.

Details:
Network timeout error: connect ECONNREFUSED 20.38.104.166:443

**Comment by jcherri689** [comment]
Failed to access the service endpoint "https://txcpastorage.table.core.windows.net/" (status code: 0, status text: "error"). This failure could be due to your network blocking access to the endpoint, for instance through a firewall. Click on this box to open the endpoint in a new tab. If the page fails to load, make sure your network allows access to the endpoint.

**Comment by JasonYeMSFT** [comment]
@jcherri689 Could you please tell us what version of Storage Explorer you are using and what platform you are on? As mentioned by your 2nd comment, do you have a firewall enabled for your storage account? And are you using a proxy?

**Comment by jcherri689** [comment]
This is working now. No firewall enabled and all services were working except table storage.

**Comment by Patle-Himanshi** [comment]
> Failed to access the service endpoint "https://txcpastorage.table.core.windows.net/" (status code: 0, status text: "error"). This failure could be due to your network blocking access to the endpoint, for instance through a firewall. Click on this box to open the endpoint in a new tab. If the page fails to load, make sure your network allows access to the endpoint.

**Comment by Patle-Himanshi** [comment]
Hi Team, 

I am getting the same error; I am using Azure platform and StorageV2 (general purpose v2)
