### ISSUE TITLE
Attached Storage Account 

### ISSUE THREAD

**Issue by ddsmatt** [microsoft/AzureStorageExplorer#4638]
Unable to load attached Storage Account. Error: Cannot read property 'version' of undefined

**Comment by MRayermannMSFT** [comment]
@ddsmatt, can you try following these troubleshooting steps? https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#error-occurred-while-adding-new-connection-typeerror-cannot-read-property-version-of-undefined

Let us know if you are still stuck after that.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you're still having problems we recommend opening an azure support ticket via the portal, or you can open a new issue here.
