### ISSUE TITLE
Can't access attached local hard disks

### ISSUE THREAD

**Issue by VictorSago** [microsoft/AzureStorageExplorer#4641]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.20.0

### Architecture

x64

### Storage Explorer Build Number

20210625.5

### Platform

Linux

### OS Version

Ubuntu 20.04

### Bug Description

Trying to access a local hard drive results in "Error opening directory '<Local-Directory-Path>': Permission denied". The directory is on an extra internal hard disk, has all the correct permissions set and is readily accessible through any other means: from any file manager or from the shell.

### Steps to Reproduce

1. Launch Storage Explorer
2. Expand Blob containers node
3. Select a container
4. Click 'Upload' button
5. Navigate to a HD device mounted in /media or to any symlinked directory located on such device

### Actual Experience

Storage explorer reports an error with "Permission denied" message (see screenshot).
![Screenshot_20210630_114501](https://user-images.githubusercontent.com/13367992/123939725-bcc1b580-d998-11eb-95fd-2e015dbcb0e9.png)

### Expected Experience

The directory should be traversed without any trouble.

### Additional Context

The Storage Explorer is installed from snapstore

**Comment by JasonYeMSFT** [comment]
Maybe a duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/4093. Unfortunately the exact cause is still an unknown to us except that we already noticed that our snap is restricted to access external drives. We will see if there is anything we can configure for our snap to remove the restriction.

**Comment by VictorSago** [comment]
Thanks for the reply, @JasonYeMSFT.
Yes, it does sound similar. Especially what you write in your comment from [24th of March](https://github.com/microsoft/AzureStorageExplorer/issues/4093#issuecomment-805402385)
I am able to see the symlink as a directory in the Storage Explorer's File Upload dialogue, but trying to navigate to it results in "Permission denied" message. All other ways of navigating to these directories work without any problems. Even if I try navigating there with Chromium -- another application installed from Snapstore -- it shows everything correctly. The problem occurs only in Storage Explorer.
I will try the .tar.gz build when I have time and I'll get back here with the results.

**Comment by craxal** [comment]
@VictorSago You may need to connect the `removable-media` interface, which doesn't automatically connect when you install Storage Explorer. According to the Snapcraft documentation, this interface is what you need to access removable media, like your external hard drive. Storage Explorer already includes the `removable-media` plug, so you should be able to connect it by running:
```
snap connect storage-explorer:removable-media :removable-media
```

Give that a try and let us know if that solves your problem.

**Comment by craxal** [comment]
Haven't received a response from the author yet, so I'm going to close this issue.

@VictorSago If you are still experiencing this issue, please reply or open a new issue.

**Comment by ArunasFalcon** [comment]
> @VictorSago You may need to connect the `removable-media` interface, which doesn't automatically connect when you install Storage Explorer. According to the Snapcraft documentation, this interface is what you need to access removable media, like your external hard drive. Storage Explorer already includes the `removable-media` plug, so you should be able to connect it by running:
> 
> ```
> snap connect storage-explorer:removable-media :removable-media
> ```
> 
> Give that a try and let us know if that solves your problem.

@craxal  I had the same problem, tried your solution, it works now. Thanks.

**Comment by leighghunt** [comment]
> @VictorSago You may need to connect the `removable-media` interface, which doesn't automatically connect when you install Storage Explorer. According to the Snapcraft documentation, this interface is what you need to access removable media, like your external hard drive. Storage Explorer already includes the `removable-media` plug, so you should be able to connect it by running:
> 
> ```
> snap connect storage-explorer:removable-media :removable-media
> ```
> 
> Give that a try and let us know if that solves your problem.

Just to add data points, I was experiencing the same issue, ran the command above, and issue resolved without even having to restart Storage Explorer. Thanks :-)
