### ISSUE TITLE
Hardly see the expand icon in the 'Activities' under the 'High Contrast -Black' theme

### ISSUE THREAD

**Issue by v-xinda** [microsoft/AzureStorageExplorer#4648]
**Storage Explorer Version:** 1.21.0-dev
**Build Number:** 20210702.1
**Branch:** main
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04/ MacOS Big Sur 11.4
**How Found:** Exploratory testing
**Architecture:** ia32/x64
**Regression From:** Previous release (1.20.0)

## Steps to Reproduce ##
1. Open Storage Explorer -> Go to the 'View' menu -> Change the theme to 'High Contrast - Black'.
2. Expand a storage account -> Blob Containers -> Create a blob container.
3. Right click the blob container -> Click 'Clone...' -> Type a valid name -> Click ‘Clone'.
4. Check whether the expand icon is clear to see in the 'Activities'.

## Expected Experience ##
The expand icon is clear to see in the 'Activities'.
![image](https://user-images.githubusercontent.com/57662131/124243304-4ebfee80-db50-11eb-86d0-12c62eec4ae1.png)

## Actual Experience ##
Hardly see the expand icon in the 'Activities'.
![image](https://user-images.githubusercontent.com/57662131/124243601-a5c5c380-db50-11eb-8e98-6d69ab445287.png)

**Comment by craxal** [comment]
Oops, my bad. Looks like I missed a spot!
