### ISSUE TITLE
Error connecting blob container

### ISSUE THREAD

**Issue by pixparker** [microsoft/AzureStorageExplorer#4649]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.20.1

### Architecture

x64

### Platform

Windows

### OS Version

10

### Bug Description

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://127.0.0.1:10000/devstoreaccount1?include=metadata&comp=list failed, reason: write EPROTO 239022224:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:\n",
  "stack": "FetchError: request to https://127.0.0.1:10000/devstoreaccount1?include=metadata&comp=list failed, reason: write EPROTO 239022224:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:\n\n    at ClientRequest.<anonymous> (C:\\Users\\pixpa\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1461:11)\n    at ClientRequest.emit (events.js:310:20)\n    at TLSSocket.socketErrorListener (_http_client.js:426:9)\n    at TLSSocket.emit (events.js:310:20)\n    at errorOrDestroy (internal/streams/destroy.js:108:12)\n    at onwriteError (_stream_writable.js:424:5)\n    at onwrite (_stream_writable.js:445:5)\n    at internal/streams/destroy.js:50:7\n    at TLSSocket.Socket._destroy (net.js:677:5)\n    at TLSSocket.destroy (internal/streams/destroy.js:38:8)",
  "type": "system",
  "errno": "EPROTO",
  "code": "EPROTO"
}

### Steps to Reproduce

1. Lunch storage explorer
2. add a connection for local storage emulator
3. open blob containers

### Actual Experience

1. Lunch storage explorer
2. add a connection for local storage emulator
3. open blob containers

### Expected Experience

connect

**Comment by Apiwe-Nombanga-by** [comment]
This is also happening to me.

**Comment by MRayermannMSFT** [comment]
@pixparker and @Apiwe-Nombanga-by , there are some additional steps you need to do to use Storage Explorer with HTTPS enabled Azurite. Please refer to this blog post for more information: https://blog.jongallant.com/2020/04/local-azure-storage-development-with-azurite-azuresdks-storage-explorer/

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you're still having problems we recommend opening an azure support ticket via the portal, or you can open a new issue here.

**Comment by pixparker** [comment]
Sorry for the latency in response, I thinks there was a problem with my OS because the other functionality of services was affected too. after installing a fresh Windows 10, everything just worked fine.
Thanks.
