### ISSUE TITLE
ADFS/global Azure Stack storage account doesn't load resources/properties

### ISSUE THREAD

**Issue by supervicky42** [Microsoft/AzureStorageExplorer#465]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**:win10 x64
#### Steps to Reproduce: ####
1. Download the August Storage Explorer Version**: 1.4.0 and install it.
2. Open it and log on the storage account
3.Click the Storage account
#### Expected Experience: ####
The corresponding blob container, table, queue, property display normally.
#### Actual Experience: ####
Nothing displays and it's property indicates :Error Loading property

**Comment by craxal** [comment]
We recently updated the API version for management endpoints to 2017-10-01 in order to fix #229. My guess that's what broke Azure Stack?
