### ISSUE TITLE
ACL entity search - No results

### ISSUE THREAD

**Issue by samdobson** [microsoft/AzureStorageExplorer#4650]
When attempting to search for a user, group or service principal to add to an ACL, no results are returned. This is regardless of whether name, email, UPN, or OID is provided.

![image](https://user-images.githubusercontent.com/1309834/124451250-1a7d4580-dd7d-11eb-8645-f844e30e25a5.png)

I suspect some kind of permissions issue but there is nothing to indicate this in the error message, nor, as far as I can see, in the logs.

Using Version 1.20.0

**Comment by MRayermannMSFT** [comment]
Hi @samdobson, unfortunately we don't have super good self-logging for these search queries right now, so to investigate this will be a bit involved on your part.

To try and see what's going wrong can you please follow Part 1 of these instructions: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#network-logs

Once you have that done, try doing your search and then watch Fiddler. You should see network calls appear. If you see any with errors, take a look/feel free to share the error messages with us.

If all of that is too complex for you, let me know and we can try to figure something else out.

**Comment by samdobson** [comment]
Thanks @MRayermannMSFT . Fiddler unfortunately is a no-go in my (restrictive) environment. After some more digging, it seems the problem only occurs with the "Use system proxy (preview)" proxy setting. After switching to "Use environment variables" the problem disappears. I'm closing this issue because the solution is satisfactory for me.

**Comment by MRayermannMSFT** [comment]
@samdobson

> After some more digging, it seems the problem only occurs with the "Use system proxy (preview)" proxy setting.

Ah ok, so were you using System Proxy and it was working for you? Assuming yes: cool! Let us know if you have any other feedbacks for it. This post actually made me realize that although I put "Managing ACLS" on the list of features supported by system proxy, that the code for searching for entities isn't. 🤦‍♂️

I'm working on making it compatible with system proxy, and that will hopefully be added in 1.21.
