### ISSUE TITLE
SAS tokens for storage accounts no longer work

### ISSUE THREAD

**Issue by andy-scott** [microsoft/AzureStorageExplorer#4651]
Generating a new SAS token via Storage Explorer, then using the generated URL to link no longer works you get missing paramenter ss as the error.
![image](https://user-images.githubusercontent.com/3709093/124455316-587c6880-dd81-11eb-9e78-af99e39142cf.png)
click copy
![image](https://user-images.githubusercontent.com/3709093/124455515-96798c80-dd81-11eb-8611-58c13e804a15.png)

**Comment by MRayermannMSFT** [comment]
@andy-scott you're trying to use a *container* level SAS token to attach an *account*. This is not possible. What you need to do is go back to the first page of the connect dialog and choose "Blob Container" instead of "Storage Account".

**Comment by andy-scott** [comment]
Thanks @MRayermannMSFT I completly missed the blob container piece, when sending the token to a supplier, we both made the same mistake.
