### ISSUE TITLE
The context menu of one new created blob container as same as the attached context menu

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#466]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180724.4
**Commit**: 2605f1c9
**Regression From**: Previous release 1.3.1(20180711.1)

#### Steps to Reproduce: ####
1. Expand one account and create one blob container.
2. Right click the created blob container.
3. Check whether the context menu of the created blob container displays well or not. 

#### Expected Experience: ####
The context menu of the created blob container displays well.

#### Actual Experience: ####
The context menu of the created blob container as same as the attached context menu.

**Comment by craxal** [comment]
Same root cause #482.
