### ISSUE TITLE
Not able to open local storage container

### ISSUE THREAD

**Issue by akashSharma2505** [microsoft/AzureStorageExplorer#4660]
Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to http://127.0.0.1:10000/devstoreaccount1?include=metadata&comp=list failed, reason: connect ECONNREFUSED 127.0.0.1:10000",
  "stack": "FetchError: request to http://127.0.0.1:10000/devstoreaccount1?include=metadata&comp=list failed, reason: connect ECONNREFUSED 127.0.0.1:10000\n    at ClientRequest.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1461:11)\n    at ClientRequest.emit (events.js:310:20)\n    at Socket.socketErrorListener (_http_client.js:426:9)\n    at Socket.emit (events.js:310:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)",
  "type": "system",
  "errno": "ECONNREFUSED",
  "code": "ECONNREFUSED"
}

**Comment by JasonYeMSFT** [comment]
@akashSharma2505 Have you started your local emulator?

**Comment by VarunSaiTeja** [comment]
@akashSharma2505 Please start your local emulator

![image](https://user-images.githubusercontent.com/35555010/125184517-21ec9500-e23c-11eb-9d18-b312850df46b.png)

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you're still having problems we recommend opening an azure support ticket via the portal, or you can open a new issue here.

**Comment by kgehint** [comment]
Facing Same issue
