### ISSUE TITLE
The 'Enable Soft Delete' button is focused by default on the 'Delete' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4661]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210708.1
**Branch**: main
**Platform/OS**:  Linux Ubuntu 18.04
**Architecture**: x64
**How Found**: Exploratory testing
**Regression From**: Previous release (1.19.1)

## Steps to Reproduce ##
1. Expand one non-ADLS Gen2 storage account -> Blob Containers. (Make sure the soft delete is disabled)
2. Create a blob container -> Upload one blob.
3. Select the blob -> Click 'Delete'.
4. Check the whether the 'Yes' button is focused on the 'Delete' dialog.
 
## Expected Experience ##
The 'Yes' button is focused.
![image](https://user-images.githubusercontent.com/41351993/124879153-8242c300-dfff-11eb-8fb5-2d673fe53d1b.png)

## Actual Experience ##
The 'Enable Soft Delete' button is focused.
![image](https://user-images.githubusercontent.com/41351993/124879839-393f3e80-e000-11eb-9198-e5ee780efffb.png)

## Additional Info ##
There is a similar issue: [4424
](https://github.com/microsoft/AzureStorageExplorer/issues/4424)

**Comment by MRayermannMSFT** [comment]
Will look at this since I'm also looking into the related issue.

**Comment by craxal** [comment]
@v-xianya I am no longer able to reproduce this on the current main. Can you verify whether this still reproduces?

**Comment by v-xianya** [comment]
@craxal Verified this issue using the build 20210803.3. Reproduce.
![image](https://user-images.githubusercontent.com/41351993/127964342-84e6ef0a-4017-400c-8614-e22dd0770094.png)

**Comment by craxal** [comment]
@v-xianya This still doesn't reproduce for me. I used the exact same build. I noticed that you are using Ubuntu 18.04, but that is not the current LTS version. I am running on Ubuntu 20.04. Can you please verify whether this reproduces on Ubuntu 20.0.4?

**Comment by v-xianya** [comment]
Hi @craxal This issue reproduces both on Ubuntu 18.04 and Ubuntu 20.04.

**Comment by craxal** [comment]
@v-xianya I can't reproduce this in 1.20.1 or the current main branch. I'm going to mark this as not reproducible, but we'll keep an eye on this in case users encounter this problem also.

**Comment by v-xianya** [comment]
@craxal Agree! plus, if you need to investigate this issue, I can provide a repro vm.

**Comment by MRayermannMSFT** [comment]
@craxal it reproduces for all but the first dialog you open. Please address this in 1.22 either by fixing the root cause or by undo-ing the "reuse dialog window" change from 1.20.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20211112.4. Fixed.
![image](https://user-images.githubusercontent.com/87792676/141400639-fdd29d36-85fd-476b-83fb-993ead8557d8.png)
