### ISSUE TITLE
Remove tiering to the same tier

### ISSUE THREAD

**Issue by fhryo-msft** [microsoft/AzureStorageExplorer#4664]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.20.0

### Architecture

x64

### Storage Explorer Build Number

20210625.5

### Platform

Windows

### Bug Description

ASE 1.20.0 and steps:
Select an archived blob
Click context menu to Update Access Tier
Hot, Cool, Archive are listed option and Archive is opted in by default.
Since it's an archived blob, archive should not be listed as tiering destination.
Don't change anything, click Apply.
SetBlobTier is called and shown in logs.
Tiering to the same tier should not be allowed.

### Steps to Reproduce

ASE 1.20.0 and steps:
Select an archived blob
Click context menu to Update Access Tier
Hot, Cool, Archive are listed option and Archive is opted in by default.
Since it's an archived blob, archive should not be listed as tiering destination.
Don't change anything, click Apply.
SetBlobTier is called and shown in logs.
Tiering to the same tier should not be allowed.

### Actual Experience

Hot, Cool, Archive are listed option and Archive is opted in by default.
SetBlobTier is called and shown in logs.

### Expected Experience

Since it's an archived blob, archive should not be listed as tiering destination.
Tiering to the same tier should not be allowed.

**Comment by MRayermannMSFT** [comment]
Let's:
1. Communicate current tier in the dialog prompt
2. If current tier is archive, then archive should not be an option

**Comment by fhryo-msft** [comment]
To make it consistent to all tiers, you might want to "If current tier is X, then X should not be an option".
