### ISSUE TITLE
Choose the delimiter when a Azure Table is exported as a .csv file

### ISSUE THREAD

**Issue by gioce90** [microsoft/AzureStorageExplorer#4665]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I'm unable to choose a different delimiter when I export a Azure Table to .csv file

### Desired Solution

I want the possibility to choose a different delimiter from the default one (a comma delimiter). For example a ; or a | symbols.

**Comment by gioce90** [comment]
This issue is still open?

**Comment by craxal** [comment]
@gioce90 Do you require the ability to manually choose the delimiter? Or do you just want export to use your system's list separator character based on your locale?

See #6247 for related discussion.

**Comment by gioce90** [comment]
Is a bit hard to remember the exactly use case which pushed me to open this issue by now, but I think that the reason was something related the difficulty to distinguish between data inside a column who already uses commas. 

I think that leave the user the freedom to choose a delimiter different from the default (or the Regional setting default) can be a better options. IMHO.
