### ISSUE TITLE
The deleted blob container doesn't auto disappear on the tree view

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#467]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180724.4
**Commit**: 2605f1c9
**Regression From**:Previous release 1.3.1(20180711.1)

#### Steps to Reproduce: ####
1. Expand one account and delete a blob container.
2. Check whether the deleted blob container exists or not.

#### Expected Experience: ####
The deleted blob container does not exist.

#### Actual Experience: ####
The deleted blob container still exists.

The deleted blob disappears after manually refreshing.

**Comment by craxal** [comment]
Fixed along with #142, #482, and #484.

**Comment by v-haiz** [comment]
This issue reproduces on Storage Explorer 20181008.2 again. So reopen it.

**Comment by v-xianya** [comment]
Verified on build 20190104.2. This issue doesn't reproduce. Could you help to resolve it?

**Comment by jinglouMSFT** [comment]
Closing
