### ISSUE TITLE
The ADLS Gen2 folder displays as a soft-deleted block blob after soft deleting it

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4672]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210710.1
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ MacOS Big Sur 11.4
**Architecture**: ia32/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Create a new folder.
3. Soft delete the new folder -> Switch to 'Active and deleted blobs' view.
4. Check whether the soft-deleted folder displays.

## Expected Experience ##
The soft delete folder displays.

## Actual Experience ##
The folder displays as a soft-deleted block blob.
![image](https://user-images.githubusercontent.com/41351993/125424988-14f5b7d8-d257-4f34-becc-29827480c5c5.png)

## Additional Context ##
Here is the screenshot from Portal:
![image](https://user-images.githubusercontent.com/41351993/125425891-437db95d-fe0f-4c13-a50e-b02a51a367b8.png)

**Comment by JasonYeMSFT** [comment]
I think we can make our datatable can hide the details of this blob and display it as a directory instead.

**Comment by v-xianya** [comment]
@JasonYeMSFT Verified this issue on the build 20210719.1. Fixed. 
![image](https://user-images.githubusercontent.com/41351993/126093750-e92e91d2-31be-406a-9bd1-a65f96232019.png)

**One question needs to confirm.** No blob displays after opening one soft-deleted folder which contains active blobs. Is this expected?

**Comment by JasonYeMSFT** [comment]
> No blob displays after opening one soft-deleted folder which contains active blobs. Is this expected?

Yes.

**Comment by v-xianya** [comment]
@JasonYeMSFT On the build 20210720.1. The 'open' action is disabled for one soft-deleted folder. It seems expected, right?
BTW, I logged a new bug [4693 ](https://github.com/microsoft/AzureStorageExplorer/issues/4693)for the action items against soft-deleted blob. 
![image](https://user-images.githubusercontent.com/41351993/126267930-f954070c-2c32-4293-9d17-8b8fb90c06d5.png)
