### ISSUE TITLE
It would be better to give more helpful error info when creating one folder with an invalid name

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4673]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210710.1
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ MacOS Big Sur 11.4
**Architecture**: ia32/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Click 'New Folder'.
3. Delete the default folder name on the 'New Folder' dialog.
4. Check the error info.

## Expected Experience ##
It would be better to give more helpful error info.

Here is the screenshot from Portal:

![image](https://user-images.githubusercontent.com/41351993/125431598-ea9ee262-59d4-4c84-842a-aeadebdc3c0d.png)

## Actual Experience ##
The error info as below:
![image](https://user-images.githubusercontent.com/41351993/125431343-5f7f93ae-4437-4f14-89d0-4dacb542ce7d.png)

**Comment by MRayermannMSFT** [comment]
Ya, let's update the error message to include all the requirements. So something like:

"Folder name must not be empty. Folder name must be no more than 255 characters in length..." etc.

**Comment by MRayermannMSFT** [comment]
Merged into main for 1.20

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20210819.3, it reproduces. So reopen it.
![image](https://user-images.githubusercontent.com/87792676/129997499-ba0f18ce-31db-4822-8d25-5778182b68c1.png)
