### ISSUE TITLE
Query fails when defining Table Query using QueryBuilder with apostrophe in Value field

### ISSUE THREAD

**Issue by wilcomp** [microsoft/AzureStorageExplorer#4674]
When defining a Table Query using QueryBuilder then any apostrophe in Value field makes the query fail.
Only when I switch from QueryBuilder to TextEditor mode, and replace the apostrophe characters by XML encoded version &apos; then the query does actually run

`PartitionKey ge '2021-07-07' and Message eq 'Invoice query filter: [Status = &apos;Posted&apos; and Balance > 0]' and ThreadName eq 'ZuoraEventWorker#0'`

**Comment by JasonYeMSFT** [comment]
When you say "apostrophe" do you actually mean the ascii character ' (single quote) or really a apostrophe character? In the documentation, it says you need to escape single quote in the query. https://docs.microsoft.com/en-us/rest/api/storageservices/querying-tables-and-entities#single-quote-

**Comment by wilcomp** [comment]
I think I mean the single quote, but I thought that is the same as an apostrophe, because the XML representation of a single quote is &apos;
It is confusing. Anyway, I mean the text delimiter in query expressions

Met vriendelijke groet / Kind regards,

Wilco Schreurs // Solution Architect
***@***.***D7796B.46603250]

PossibilIT | +31 (0)6 11 41 16 17  | ***@***.******@***.***> | www.possibilit.nl<http://www.possibilit.nl/>

PossibilIT B.V. Office: +31 (0)30 760 03 70
Hoofdstraat 23, 3971 KA Driebergen-Rijsenburg
https://www.possibilit.nl<https://www.possibilit.nl/>
[Facebook]<http://www.facebook.com/#!/wemakeITpossible> [Twitter] <http://www.twitter.com/possibilit>  [Linkedin] <http://www.linkedin.com/company/696341>
Dit e-mailbericht is vertrouwelijk en persoonlijk. Indien dit bericht niet voor u bestemd is, verzoeken wij u dit onmiddellijk aan afzender te melden en het bericht te verwijderen. U mag dit bericht en/of bijlagen niet verder verspreiden. Afzender controleert al haar uitgaande e-mail op aanwezigheid van virussen. Afzender is niet aansprakelijk voor en/of in verband met alle mogelijke gevolgen en/of schade voortvloeiend uit dit e-mailbericht, zoals schade door virussen. Werknemers zijn niet bevoegd namens PossibilIT BV via e-mail een bindende overeenkomst te sluiten met een andere partij, zonder uitdrukkelijke schriftelijke toestemming van een directeur van PossibilIT BV. Voor bevoegdheden van werknemers verwijzen wij naar de registratie bij de Kamer van Koophandel.

**Comment by MRayermannMSFT** [comment]
@wilcomp soooo are you good/is this issue resolved for you?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still facing this problem and still want help please open an Azure support ticket from the Azure portal or open a new issue. Thanks.
