### ISSUE TITLE
There is an extra empty folder under 'Active and deleted blobs' view after soft deleting a folder which contains soft-deleted blobs

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4677]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210715.1
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ MacOS Big Sur 11.4
**Architecture**: ia32/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Create a folder -> Upload two blobs to the folder.
3. Soft delete one blob -> Then soft delete the folder.
4. Switch to the 'Active and deleted blobs' view.
5. Check there is no extra empty folder.

## Expected Experience ##
There is no extra empty folder.

## Actual Experience ##
There is an extra empty folder.
![image](https://user-images.githubusercontent.com/41351993/125743698-9c22be21-1b18-4f4d-8d73-41d42efae223.png)

## Additional Context ##
This issue doesn't reproduce when the folder does not contain soft-deleted blobs.

**Comment by JasonYeMSFT** [comment]
We will show soft-deleted folders as folders and hide this "active" folder.

**Comment by v-xianya** [comment]
@JasonYeMSFT  Verified this on the build 20210720.1. Fixed.

one more question needs to confirm with you.
What's the expected behavior when creating a new folder with the same name of one soft-delete folder?
**Actual:** Succeed to create and the folder only displays under 'Active blobs(default) view'

**Comment by JasonYeMSFT** [comment]
@v-xianya This is not expected and there are service issues blocking us from doing anything. I am going to close this issue since the original issue has been fixed. I will be talking to the service team on the blocking issues and come up with a solution to the new one.
