### ISSUE TITLE
An error 'Unable to retrieve configuration' appears when adding a custom environment with the correct ARM endpoint

### ISSUE THREAD

**Issue by v-xinda** [microsoft/AzureStorageExplorer#4678]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210715.1
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ MacOS Big Sur 11.4
**How Found**: From running test cases
**Architecture**: ia32/x64
**Regression From**: Previous release (1.20.0)

## Steps to Reproduce ##

1. Open 'Connect to Azure Storage' dialog via the plug icon.
2. Select 'Subscription' -> Click 'Manage custom environments...'. -> Click 'Add' button.
3. Type a valid Environment name then input 'https://management.azure.com' as the ARM endpoint.
4. Click 'Add' button -> Check whether succeed to add.

## Expected Experience ##
Succeed to add.

## Actual Experience ##
An error 'Unable to retrieve configuration. Please verify that the ARM endpoint is correct.' appears after clicking 'Add' button.
![image](https://user-images.githubusercontent.com/57662131/125763821-ff9d1359-8eee-4d00-8955-85f3eb7b9e4e.png)

**Comment by v-xianya** [comment]
Verified this issue on the build 20210728.1. Not reproduce. So close it.
