### ISSUE TITLE
The 'warn before exit' dialog will not pop up even if there are unfinished activities when it was last closed via 'X'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4679]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210715.1
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ MacOS Big Sur 11.4
**Architecture**: ia32/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one resource group -> Click 'Upload'.
2. Select one large vhd file -> Click 'Create'.
3. Reload/Quit/Close the Storage Explorer when the vhd file is uploading.
4. A warning dialog pops up -> Close the dialog by clicking 'X'.
5. Reload/Quit/Close the Storage Explorer. (Make sure the upload is still in progress)
6. Check whether the waring dialog pops up.

## Expected Experience ##
The warning dialog pops up.

## Actual Experience ##
1. No warning dialog pops up.
2. Succeed to reload/quit/close Storage Explorer.

**Comment by MRayermannMSFT** [comment]
I believe I have fixed this on main....

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT  Verified this issue on the build 20210726.1. Reproduce. So we are going to reopen it.

**Comment by MRayermannMSFT** [comment]
@v-xianya I just checked in some additional logging around this scenario. Can you do the following for me?
1. Increase your [storage explorer log level ](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#storage-explorer-logs)to `debug`
2. Launch storage explorer
3. Reproduce the issue
4. Get the logs for the instance of storage explorer that just closed
5. Zip them up, send to me on teams
Thanks!

**Comment by v-xianya** [comment]
@MRayermannMSFT Ok. got it. I will send the log. 
Add one more info, this issue doesn't reproduce when closing Storage Explorer via the 'X' on the top right corner.

**Comment by MRayermannMSFT** [comment]
Ok, try again now. I think I've nailed it. :)

**Comment by MRayermannMSFT** [comment]
@v-xianya, feel free to verify, but I just now thought of a scenario that is probably broken. Unfortunately I need to go for now, but I'm going to reopen this, and then next week see if my intuition is right. If it is, I'll fix that and let you know so you can add it to your test cases.

**Comment by v-xianya** [comment]
@MRayermannMSFT Verified this issue on the build 20210809.3. Fixed.
