### ISSUE TITLE
Cannot access resources and may need to reauthenticate

### ISSUE THREAD

**Issue by abernal2** [microsoft/AzureStorageExplorer#4681]
Hello,

I have not been able to access any data and have tried to reauthenticate but I still get nothing. I get the following error:

{
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"read ECONNRESET\\\",\\n  \\\"stack\\\": \\\"Error: read ECONNRESET\\\\n    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)\\\",\\n  \\\"errno\\\": \\\"ECONNRESET\\\",\\n  \\\"code\\\": \\\"ECONNRESET\\\",\\n  \\\"syscall\\\": \\\"read\\\"\\n}\""
}

Has someone encountered this? 

Best,

**Comment by MRayermannMSFT** [comment]
Hi, it sounds like you may be behind a proxy. In this case we recommend:
- Try using system proxy, which you can read about in our networking documentation: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network 
- Try setting up proxy manually. You can read the proxy section in our troubleshooting guide for additional help with that: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#proxy-issues

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still facing this problem and still want help please open an Azure support ticket from the Azure portal or open a new issue. Thanks.
