### ISSUE TITLE
The 'Undelete' dialog shows blank for one soft-deleted ADLS Gen2 blob/folder

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4689]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210719.1
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ MacOS Big Sur 11.4
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous build (20210715.1)

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload a blob.
3. Soft delete the blob -> Switch to 'Active and deleted blobs' view.
4. Right click the soft-deleted blob -> Click 'Undelete -> Undelete Selected'.
5. Check whether the 'Undelete' dialog shows well.

## Expected Experience ##
The 'Undelete' dialog shows well.

## Actual Experience ##
The 'Undelete' dialog shows blank.
![image](https://user-images.githubusercontent.com/41351993/126093849-12c1da09-eaf8-4b9b-bbaa-59f9ebcaf9e9.png)

**Comment by JasonYeMSFT** [comment]
It was due to using an incorrect version of the package.

**Comment by v-xianya** [comment]
Verified on the build 20210720.1. Fixed.
