### ISSUE TITLE
The deleted blob doesn't directly disappear after deleting it from 'Active and deleted blobs' with soft delete disabled

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#469]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180724.4
**Commit**: 2605f1c9
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Expand one account and make sure the soft delete is **disabled** for 'Blob Containers'.
2. Open one blob container which contains one blob at least.
3. Switch to 'Active and deleted blobs' -> Delete one blob then check the lists.

#### Expected Experience: ####
The deleted blob disappear under the 'Active and deleted blobs'.

#### Actual Experience: ####
The deleted blob displays with strikethrough.
It will disappear after refreshing the editor.

**Comment by JasonYeMSFT** [comment]
Thanks for pointing this out. Will fix it.
