### ISSUE TITLE
No 'Conflict' dialog pops up after retrying 'Prompt for overwrite' option for one of the download conflict transfers on the 'Retry Azcopy' dialog

### ISSUE THREAD

**Issue by v-xinda** [microsoft/AzureStorageExplorer#4694]
**Storage Explorer Version**: 1.21.0
**Build Number**:  20210715.14
**Branch**: hotfix\1.20.1
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ MacOS Big Sur 11.4
**How Found**: From running test cases
**Architecture**: ia32/x64
**Regression From**: Previous release (1.18.1) 

## Steps to Reproduce ##

1. Create a storage account -> Create a blob container -> Upload two blobs.
2. Download two blobs at one time.
3. Download them to same destination again -> Pop up a 'Conflict' dialog -> Select 'Do not download' -> Click 'Apply to All Conflicts' .
4. Click 'Retry...' action next to the activity log.
5. Uncheck one transfer and make sure the 'Overwrite' option is 'Prompt for overwrite' in the popped up 'Retry Azcopy' dialog 
-> Click 'Retry Selected'. 
6. Check whether the 'Conflict' dialog pops up or not.

## Expected Experience ##
The 'Conflict' dialog pops up.

## Actual Experience ##
The 'Conflict' dialog doesn't pop up.

## Additional Context ##
1. A successful log displays in the 'Activities' after retrying 'Prompt for overwrite' option.
2. This issue also reproduces for file share.
3. This issue also reproduces when pasting the blobs.

**Comment by MRayermannMSFT** [comment]
Fix merged into hotfix branch for release.
