### ISSUE TITLE
The blob is not deleted when retrying 'Deleted blobs with snapshots' with one of the source items is selected on 'Retry AzCopy' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4695]
**Storage Explorer Version**: 1.20.1
**Build Number**: 20210715.14
**Branch**: hotfix\1.20.1
**Platform/OS**: Windows 10/ Linux Ubuntu 20.04/ MacOS Big Sur 11.4
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.18.1)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload two blobs.
3. Create snapshot for the two blobs -> Try to delete the two blobs.
4. There is a warning activity log -> Click 'Retry...' next to the activity log.
5. Only check one item under the 'Source' column on the 'Retry Azcopy' dialog.
6. Select 'Delete blobs with snapshots' -> Click 'Retry Selected'.
7. Check whether the selected blob is deleted.

## Expected Experience ##
The selected blob is deleted.

## Actual Experience ##
The selected blob is not deleted.
![image](https://user-images.githubusercontent.com/41351993/126288913-6864c4f7-eb1e-4553-9ae6-852b41f96808.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into hotfix branch for release.
