### ISSUE TITLE
Miss the action 'Copy Direct Link to File Share' for one cloned file share

### ISSUE THREAD

**Issue by v-xinda** [microsoft/AzureStorageExplorer#4697]
**Storage Explorer Version:** 1.20.1
**Build Number:** 20210715.14
**Branch:** hotfix/1.20.1
**Platform/OS:** Windows 10/ MacOS Big Sur 11.4
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand a storage account -> File Shares.
2. Right click one file share -> Click 'Clone' on the context menu.
3. Input a valid name -> Click 'Clone'.
4. Right click the cloned file share -> check whether the action 'Copy Direct Link to File Share' displays on the context menu.

## Expected Experience ##
The action 'Copy Direct Link to File Share' displays on the context menu.
![image](https://user-images.githubusercontent.com/57662131/126305220-d69fc3ff-33bb-4945-a337-d2e88ef34c37.png)

## Actual Experience ##
No action 'Copy Direct Link to File Share' displays on the context menu.
![image](https://user-images.githubusercontent.com/57662131/126305171-0ace231e-14ba-476a-b168-b2a87b85ab80.png)

## More Info ##
1. The action 'Copy Direct Link to File Share'  displays after manually refreshing.
2. This issue also reproduces on a pasted file share.
3. This issue doesn't reproduce on blob container.
4. This issue is similar to [1515](https://github.com/microsoft/AzureStorageExplorer/issues/1515).

**Comment by v-xianya** [comment]
Verified this issue on the build main/20211220.2. Reproduce.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220414.17. Fixed.
