### ISSUE TITLE
It would be better to list all properties of the entity in the 'Edit Entity' dialog

### ISSUE THREAD

**Issue by v-xinda** [microsoft/AzureStorageExplorer#4698]
**Storage Explorer Version:** 1.20.1
**Build Number:** 20210715.14
**Branch:** hotfix/1.20.1
**Platform/OS:** Windows 10/ Linux Ubuntu 20.04/ MacOS Big Sur 11.4
**Architecture:** ia32/x64
**How Found:** Exploratory testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand a storage account -> Tables -> Create a table.
2. Import an entity that contains more than three properties ('PartitionKey' , 'RowKey' , 'Timestamp').
3. Click 'Add' -> Only type the value for 'PartitionKey' and 'RowKey' properties (Make sure other properties' value is default). 
3. Select the added entity  -> Click 'Edit'.
4. Check the contents of the 'Edit Entity' dialog.

## Expected Experience ##
List all properties in the 'Edit Entity' dialog.

## Actual Experience ##
Only list the properties which value is not _**null**_.

**Comment by MRayermannMSFT** [comment]
By design for now, but something we could readdress in the future if a customer requested it.
