### ISSUE TITLE
Authentication Error on build 20180415.2

### ISSUE THREAD

**Issue by MLeslie7** [Microsoft/AzureStorageExplorer#47]
Updated Mac OS to Hi-Sierra 10.13.4 today, installed the newest version of Storage Explorer (build 20180415.2) and now storage explorer will not authenticate using credentials, it will only connect using a string or key not as the user. It displays an error 
<img width="1001" alt="screenshot 2018-04-18 15 29 55" src="https://user-images.githubusercontent.com/13472511/38956732-1bd6cb74-431e-11e8-8b3b-adc562d2f757.png">
<img width="453" alt="screenshot 2018-04-18 15 33 35" src="https://user-images.githubusercontent.com/13472511/38956733-1beb46a8-431e-11e8-97d8-9dfd390ae5ed.png">

**Comment by MRayermannMSFT** [comment]
HI @MLeslie7 , thank you for reporting this issue. I have a couple of clarifying questions to ask:
1.  Sign in (user name and password) worked for you prior to 1.0.0 and is now not working, yes?
2.  Assuming #1, does the info bar pop up with any errors after you try to sign in? Does the auth screen stay blank? Basically, what are you seeing when you try to sign in?
3.  Are you, or are you not able, to use SAS/name and key attach?

Thanks!

**Comment by MLeslie7** [comment]
Thanks for the quick response
1. Yes it did before the OS update
2. A)No - I attached a screen shot of the login page. B)Yes always blank c) see the new screenshot
3. Update it did accept the conn string but would not allow for browsing the storage account an unauthorized popup, and have not tried a sas key yet.

This is my sups laptop we are on the road and might be offline this evening, but will be online tomorrow around 8 am cst to provide more info if needed.

1.  Open Storage Explorer
2. Click - Add Account - Sign In
This window pops up and is blank for a minute then displays the pop up error (the screen shot from original post)
<img width="1000" alt="screenshot 2018-04-18 15 30 42" src="https://user-images.githubusercontent.com/13472511/38960255-64d90840-4329-11e8-9420-8f4b7e0703fb.png">

**Comment by MLeslie7** [comment]
The screen shot of the error message was from after we had added an account with the conn string, it did not allow browsing the account. The login page error was the very first attempt to connect after installing the updated Azure Explorer and before adding the account with a conn string, thats why you can see nodes to browse

**Comment by MRayermannMSFT** [comment]
@MLeslie7 , I'm still a little confused. Let's start by focusing on sign in. So:

1.  You click "Add Account", and then the connect dialog pops up to the initial page.
2. You click "Sign in..." and then you see this page:
![image](https://user-images.githubusercontent.com/21112697/38961602-19ff0f32-431e-11e8-8fc3-e4e9db399157.png)
3. At this point, I would expect you to see this pop up on top of the connect dialog:
![image](https://user-images.githubusercontent.com/21112697/38961609-25bc663a-431e-11e8-8c9a-24fdb7375469.png)
But you're not seeing that, right? If so, I want you to try two things. First, three finger swipe up on your track pad. Let's make sure that the window from step 3 isn't hiding. If it is, doing a three finger swipe should make it visible. Second, if it isn't hiding, then close the Connect dialog, and launch the dev tools (Help -> Toggle Developer Tools, or f12). Then go to the console tab and filter by warnings.
![image](https://user-images.githubusercontent.com/21112697/38961755-d2d6207c-431e-11e8-9318-39d9673013b3.png)
If you see any (yellow or red text, can you screenshot what you see and post it here?

Thanks.

**Comment by MLeslie7** [comment]
Will be offline until tomorrow morning.

________________________________

**Comment by MLeslie7** [comment]
Hello,
Tried and the window was not hiding, here is the screen shot of the errors from the console. 
<img width="1635" alt="screenshot 2018-04-19 09 26 24" src="https://user-images.githubusercontent.com/13472511/38998093-7927da02-43b4-11e8-8fc9-d5a17907b890.png">

If you need more info will be on a flight this afternoon (12 pm CST) until 5

**Comment by MRayermannMSFT** [comment]
Can you expand some of the arrows? We're probably most interested in the one next to "Object"s. Ideally just expand all of the arrows until you see some more information (stack traces, what the actual error is). Also, thank you for being willing to do this back and forth.

**Comment by MLeslie7** [comment]
Ok that is no problem you need info to find the issue, talking more there have been 3 things updated in the last week
MacOS update was released this week
The signin page to Azure/Office 365 changed this week (I noticed the appearance is different)
Storage Explorer got a update as well
Between the 3 updates it looks like something is not correct, I can get any more info you need, thanks for the quick responses.

These are shots of the 3 different errors - different error codes, there are more errors but they are the same from the repeated attempts

<img width="1407" alt="screenshot 2018-04-19 09 57 55" src="https://user-images.githubusercontent.com/13472511/39000002-98e61d5a-43b8-11e8-9e54-141596ffe0fc.png">
<img width="1413" alt="screenshot 2018-04-19 09 58 06" src="https://user-images.githubusercontent.com/13472511/39000003-98f87d24-43b8-11e8-88db-9d25439a2876.png">
<img width="1421" alt="screenshot 2018-04-19 09 58 22" src="https://user-images.githubusercontent.com/13472511/39000004-990cf5b0-43b8-11e8-86f6-659491a8cdfb.png">

**Comment by MRayermannMSFT** [comment]
Ah ok. I know who to reach out to now about this issue. Something is going wrong when we try to store your authentication token in your Mac keychain. I'll be back in a few hours with either some resolution steps or further diagnostic steps.

Until then, you can download the previous version of Storage Explorer at the bottom of this page if you need to be unblocked: https://azure.microsoft.com/en-us/features/storage-explorer/

**Comment by MRayermannMSFT** [comment]
Ok, here's what I'd like you to try:
1. Launch "Keychain Access" (cmd + space, type in keychain, hit enter)
2. In the filter at the top right, type in identityservice, you should now see an entry with the Name "Microsoft.Developer.IdentityService." If you don't, then stop here and let me know.
3. Right click on the entry, choose "Get Info", and go to the "Access Control" tab
4. There should be one program which has access to this password, ServiceHub.Host.CLR.x64
![image](https://user-images.githubusercontent.com/21112697/39015242-9fda3e98-43d1-11e8-8875-768b631755c6.png)

If you see don't see ServiceHub.Host.CLR.x64 in the list then:
1. Open finder, go to your applications, and find Microsoft Azure Storage Explorer
2. Right click on it, and choose "Show Package Contents"
3. Navigate to `Contents/Resources/app/ServiceHub/Hosts/ServiceHub.Host.Core.CLR.x64/`
4. Look for the file with the name "ServiceHub.Host.CLR.x64" and copy it to your desktop
5. Go back to Keychain Access, where the info window for IdentityService should still be open, click on the plus, and use the finder window that appears to select the file you copied to your desktop in step 4, and then click Add
6. Save changes
7. Try to sign in
8. If you can't sign in, try the steps below

If you see ServiceHub.Host.CLR.x64 in the list then:
1. Select the "Allow all applications to access this item" option, and then save changes
2. Try to sign in

If none of that works, then I'll need to do some more investigation.

**Comment by MLeslie7** [comment]
Sorry for the delay travel...
It was set to allow all. I added the file as requested and saved changes but it doesn’t save.
I kept it on allow all but still no dice.
![screenshot 2018-04-20 12 04 52](https://user-images.githubusercontent.com/13472511/39064552-82f95660-4494-11e8-8cbc-a8e291a487ce.png)
![screenshot 2018-04-20 12 05 02](https://user-images.githubusercontent.com/13472511/39064554-8581bbe8-4494-11e8-9d73-7e5981497306.png)

**Comment by MRayermannMSFT** [comment]
What do you mean by it won't save?

**Comment by MRayermannMSFT** [comment]
Also, can you do/attach the following?

0. Close Storage Explorer
1. Open finder
2. Go to /users/<your username>/.ServiceHub/logs
3. Delete the contents of the folder (should just be a bunch of .log files), don't close the window, we'll be coming back here
4. Start Storage Explorer and try to sign in
5. Once the Waiting dialog disappears, close Storage Explorer
6. Go back to finder, zip up the files (select all, right click, choose "Compress"), and attach the zip to this issue:
![image](https://user-images.githubusercontent.com/21112697/39065258-11f759c0-4486-11e8-8320-d48036bd9152.png)

**Comment by MLeslie7** [comment]
No errors it just closes.

**Comment by paulceli** [comment]
Hey, I have the exact same problem with version 1.0.0
I created the log files you asked for. You can find them in attachment.

Also the link on the bottom of the page to download the previous version seems to link to the last version also..
If you have another link to previous version, that would be helpful.

thanks.

[logs.zip](https://github.com/Microsoft/AzureStorageExplorer/files/1938159/logs.zip)

**Comment by MRayermannMSFT** [comment]
Hey y'all, can you try the following:

1. Close Storage Explorer
2. Open keychain
3. Select the "login" keychain on the right hand side
4. Click the padlock icon to lock the keychain (the padlock will animate to a locked position when complete, it may take a few seconds depending on what apps you have open)
![image](https://user-images.githubusercontent.com/21112697/39140751-6f08d00c-46da-11e8-8f8f-14fd25d1f5fb.png)
5. Launch Storage Explorer
6. A pop up should appear saying something like "Service hub wants to access the keychain", enter your Mac admin account password and click **Always Allow** (or **Allow** if **Always Allow** is not available)
7. Try to sign in

**Comment by MLeslie7** [comment]
That worked thanks!
________________________________

**Comment by MRayermannMSFT** [comment]
Awesome!!!! :D I'll get this added to our documentation.

**Comment by alberto-coolshop** [comment]
I have exactly the same error with version 1.2.0,
but steps you described don't solve the problem for me.
The login popup after locking the Keychain does not opens.
I do not have in the Keychain the item "Microsoft.Developer.IdentityService"

here there is what i find in the logs of Service Hub:

`
 alberto$ cat AadAccountProviderService-50236-*
07/06/2018 12:57:17 : Error : SecKeychainFindGenericPassword, for serviceName Microsoft.Developer.IdentityService and accountName AdalCache
Status: '-25300'
Failed, item not found

07/06/2018 12:57:17 : Error : SecKeychainFindGenericPassword, for serviceName Microsoft.Developer.IdentityService and accountName AdalCache
Status: '-25300'
Failed, item not found

07/06/2018 12:57:17 : Error : SecKeychainFindGenericPassword, for serviceName Microsoft.Developer.IdentityService and accountName AdalCache
Status: '-25300'
Failed, item not found

07/06/2018 12:57:17 : Error : SecKeychainFindGenericPassword, for serviceName Microsoft.Developer.IdentityService and accountName AdalCache
Status: '-25300'
Failed, item not found
`
