### ISSUE TITLE
The context menu of the deleted blob doesn't refresh after deleting it from 'Active and deleted blobs'

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#470]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180724.4
**Commit**: 2605f1c9
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Expand one account then enable the soft delete for 'Blob Containers'.
2. Open one blob container which contains one blob at least.
3. Switch to 'Active and deleted blobs' -> Delete one blob -> Check the context menu after deleting successfully.

#### Expected Experience: ####
The context menu for the deleted blob is auto updated.

#### Actual Experience: ####
The context menu for  the deleted blob doesn't change.
![contextmenu](https://user-images.githubusercontent.com/34729022/43134793-c39ae5ec-8f32-11e8-9ce8-0bbb774f5e48.png)

**Comment by JasonYeMSFT** [comment]
We currently don't dynamically update the context menu/the tool bar when the selected items have internal changes. We won't fix it for 1.4.0.

**Comment by v-xianya** [comment]
Verified on build 20190515.1. This issue doesn't reproduce. Could you help to resolve it?

**Comment by v-xianya** [comment]
This issue has been fixed. So we close it.
