### ISSUE TITLE
The version doesn't auto display after modifying one blob's metadata to create a version under 'Version' view

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4700]
**Storage Explorer Version**: 1.20.1
**Build Number**: 20210720.10
**Branch**: hotfix\1.20.1
**Platform/OS**: Windows 10/ Linux Ubuntu 20.04/ MacOS Big Sur 11.4
**Architecture**: ia32/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Right click the blob -> Click 'Manage History-> Manage Versions'.
4. Modify the blob's metadata to create a version.
5. Check whether the version auto displays.
 
## Expected Experience ##
The version auto displays.

## Actual Experience ##
The version doesn't auto display.

**Comment by MRayermannMSFT** [comment]
Won't fix for now, but could be something to address if a customer would like this to happen.
