### ISSUE TITLE
Fail to overwrite a blob by one blob with tags after retrying 'Enable overwrite' option

### ISSUE THREAD

**Issue by v-xinda** [microsoft/AzureStorageExplorer#4702]
**Storage Explorer Version:** 1.20.1
**Build Number:** 20210720.10
**Branch:** hotfix\1.20.1
**Platform/OS:**Windows 10/ Linux Ubuntu 18.04/ MacOS Big Sur 11.4
**Architecture:** ia32/x64
**How Found:** From running test case
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Create a storage account -> Create a blob container -> Upload one blob.
2. Click 'Upload' -> Choose a file which has the same name with the uploaded blob.
3. Add a tag on 'Upload Files' dialog -> Click 'Upload'.
4. Click 'Do not upload' -> Click 'Apply to All Conflicts' -> Click 'Retry...' action next to the activity log.
5.  Make sure the 'Overwrite' option is 'Enable overwrite' in the popped up 'Retry Azcopy' dialog-> Click 'Retry Selected'.
6. Check whether the blob uploads successfully.

## Expected Experience ##
 The blob uploads successfully.

## Actual Experience ##
The blob doesn't upload successfully, and an error message appears on activity log.
![image](https://user-images.githubusercontent.com/57662131/126476734-9f010937-7c6a-4065-a82d-7ae387571d66.png)

## Additional Context ##

1. This issue also reproduces when choosing 'Prompt for overwrite' option in the popped up 'Retry Azcopy' dialog.
2. This issue doesn't reproduce when choosing 'Replace' on the firstly popped up 'Conflict' dialog.

**Comment by MRayermannMSFT** [comment]
Looks like we are probably missing the tag permission when we regenerate the SAS for retry.

**Comment by MRayermannMSFT** [comment]
Fix merged into main.
