### ISSUE TITLE
Fail to open the 'File Properties' dialog for one file which name contains '%'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4703]
**Storage Explorer Version**: 1.20.1
**Build Number**: 20210720.10
**Branch**: hotfix\1.20.1
**Platform/OS**: Windows 10/ Linux Ubuntu 20.04/ MacOS Big Sur 11.4
**Architecture**: ia32/x64
**How Found**: Exploratory testing
**Regression From**: Previous release (1.17.0)

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Upload one file.
3. Clone the file with a name which contains '%' (like: New%file.txt).
4. Right click the cloned file -> Click 'Properties...'.
5. Check whether succeed to open the 'File Properties' dialog.
 
## Expected Experience ##
Succeed to open the 'File Properties' dialog.
![image](https://user-images.githubusercontent.com/41351993/126607290-ca6b881a-9e4c-4c22-83e6-a0e5cd39defb.png)

## Actual Experience ##
Fail to open the 'File Properties' dialog.
![image](https://user-images.githubusercontent.com/41351993/126606985-0feec6ff-1a4b-498b-8bef-85404e4d1730.png)

Error Details:
` "name": "Error",
  "message": "Unable to extract shareName and filePath/directoryPath with provided information.",`

## Additional Context ##
Similar issue [3986](https://github.com/microsoft/AzureStorageExplorer/issues/3986).

**Comment by MRayermannMSFT** [comment]
Fix merged into main
