### ISSUE TITLE
Succeed to execute 'Move' action under one attached HNS blob container which is attached via a SAS URL without permission 'Move'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4704]
**Storage Explorer Version**: 1.20.1
**Build Number**: 20210720.10
**Branch**: hotfix\1.20.1
**Platform/OS**: Windows 10/ Linux Ubuntu 20.04/ MacOS Big Sur 11.4
**Architecture**: ia32/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload a blob and a folder.
3. Right click the blob container -> Click 'Get Shared Access Signature...'.
4. Select permissions 'Read, Add, Create, Write, Delete, List' -> Create and copy the SAS URL.
5. Open the connect dialog -> Attach the blob container via the copied SAS URL.
6. Switch to the attached blob container.
7. Move the blob to the folder -> Check the result of the move action.
 
## Expected Experience ##
Fail to move due to insufficient permission.

## Actual Experience ##
Succeed to move.

## Additional Context ##
This issue doesn't reproduce for the attached blob which is attached by SAS with stored access policy(Read, Add, Create, Write, Delete, List).
`  "message": "[{\"name\":\"RestError\",\"code\":\"AuthorizationPermissionMismatch\",\"statusCode\":403,\]`

**Comment by JasonYeMSFT** [comment]
Unless restricted by user delegation parameters (which we don't support right now), if the user has read permission on the source and write permission on the destination, he should be able to move. So for this issue, the actual experience is expected.

However, the additional info looks like a bug to me. I don't know why access policy doesn't work in this case.

**Comment by JasonYeMSFT** [comment]
Get confirmation from the SDK team that not being able to Move with such access policy is a bug. We will track this issue until it is fixed.

**Comment by v-xianya** [comment]
@JasonYeMSFT This issue also reproduces for 'Rename' action.
1. Select one ADLS Gen2 blob container -> Add one access policy with permissions 'Read, Add, Create, Write, Delete, List'.
2. Generate a SAS URL with the added access policy.
3. SAS attach the ADLS Gen2 blob container.
4. Try to rename one item under the SAS attached ADLS Gen2 blob container.

**Actual:**
Fail to rename with the below error: 
![image](https://user-images.githubusercontent.com/41351993/131307934-b04b80c9-f121-4f79-bbf4-d7236a6a2638.png)
`message": "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.`

**Comment by JasonYeMSFT** [comment]
Verified that this has been fixed in our latest build.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20221215.4. 
Succeed to execute 'Rename & Move' actions under the attached blob container which is attached by SAS with stored access policy (Read, Add, Create, Write, Delete, List).
