### ISSUE TITLE
No error info prompts when switching proxy setting from 'Do not use proxy' to 'Use app proxy settings' without configuring the correct proxy

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4706]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210723.3
**Branch**: main
**Platform/OS**: Windows 10
**Architecture**: ia32
**How Found**: From running test cases
**Regression From**: Previous release (1.20.1)

## Steps to Reproduce ##
1. Launch Storage Explorer -> Make sure the proxy setting is 'Do not use proxy' -> Close Storage Explorer.
2. Download Fiddler.
3. Configure Fiddler from https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#network-logs.
4. Open Storage Explorer -> Switch to 'Use app proxy settings'.
5. Check whether an error info bar prompts.

## Expected Experience ##
An error info bar prompts.
![image](https://user-images.githubusercontent.com/41351993/126762651-f4c8fe78-630a-482d-a96a-713e7805fc13.png)

## Actual Experience ##
No error info bar prompts.

## Additional Context ##
There is no traffic for operations like 'upload, delete blobs...' after configuring the correct settings for 'Use app proxy settings'.

**Comment by craxal** [comment]
@v-xianya Fiddler _is_ a valid proxy; it's just a proxy that runs on your local machine. Therefore, no error message is expected if you configure Storage Explorer to go through Fiddler.

For the additional context, can you please provide the proxy settings you used? If you have configured the Bypass setting with, for example, blob endpoint patterns, you will not see any blob operations in Fiddler, because Storage Explorer is bypassing FIddler for those endpoints.

**Comment by v-xianya** [comment]
Hi @craxal We can reproduce this issue by the below steps:
1. Launch Storage Explorer. (Without Fiddler is installed and downloaded)
2. Open 'Settings -> Application -> Proxy' -> Select 'Use app proxy settings'. (Keep the default Hostname empty and Port: 80)
3. Check whether an error info bar prompts.

Actual: No error info bar prompts.

To answer your question:
For the additional context, I configured 'http://localhost:8888' for the proxy setting. 
I have not configured the bypass setting, it keeps empty.

**Comment by v-xianya** [comment]
@craxal To reproduce issue, We need to make sure the proxy setting have never been set to 'Use environment variables or Use system proxy(system). We change the proxy from 'Do not use proxy' to 'Use app proxy settings'.

**Comment by craxal** [comment]
@v-xianya I think the problem is the hostname is empty. We default to an empty string ("") in that case, but that's not a valid hostname. So we should modify the default.
