### ISSUE TITLE
The EXPLORER panel shows blank when first launching Storage Explorer in a clean VM

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4707]
**Storage Explorer Version**: 1.21.0
**Build Number**: 20210723.3
**Branch**: main
**Platform/OS**: Windows 10
**Architecture**: ia32
**How Found**: From running test case
**Regression From**: Previous release (1.20.1)

## Steps to Reproduce ##
1. Create a clean VM (Windows-10-Enterprise-20H2).
2. Download and install Storage Explorer.
3. A connect dialog pops up -> Sign in.
4. Check whether the EXPLORER panel shows well.
 
## Expected Experience ##
The EXPLORER panel shows well.

## Actual Experience ##
The EXPLORER panel shows blank.
![image](https://user-images.githubusercontent.com/41351993/126757385-612917e5-8f04-440e-91c9-fedf4800eb1d.png)

## Additional Context ##
1. This issue doesn't reproduce after reloading.
2. I created 2 clean VMs. this issue only reproduces on one VM.
3. Here is the record.
 ![accountmanagement](https://user-images.githubusercontent.com/41351993/126757418-6e43a52d-97d8-47ba-bc30-fd6e9c7fe3ec.gif)

**Comment by craxal** [comment]
@v-xianya Can you see if this repros more than once? Not a lot of info for us to go on, and we've yet to experience this. If a restart gets around it, I don't think we'll need to look into this more.

**Comment by v-xianya** [comment]
@craxal This issue only occurred once for now.

**Comment by craxal** [comment]
I'm going to close as unreproducible for now. If it happens again fairly consistently, we can reopen.
