### ISSUE TITLE
'Enter' doesn't work on delete blob dialog

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#471]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180724.4
**Commit**: 2605f1c9
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Expand one account then enable the soft delete for 'Blob Containers'.
2. Open one blob container which contains one blob at least.
3. Right click one blob and select 'Delete' -> Press 'Enter' on the delete dialog directly.

#### Expected Experience: ####
'Enter' works well on the delete dialog.

#### Actual Experience: ####
'Enter' doesn't work on delete blob dialog.

**Comment by JasonYeMSFT** [comment]
The behavior has been changed from that you can directly press 'Enter' to confirm to that you need to tab to the 'Delete' button and then press 'Enter' to confirm. We believe that this is still accessible and beneficial to prevent unexpected data loss.

**Comment by jinglouMSFT** [comment]
Can you title the dialog window with the word "Delete"? Similar to the Rename dialog. Thanks.

**Comment by craxal** [comment]
To clarify, the Delete dialog now has additional options beyond a simple "Yes" or "No".

**Comment by JasonYeMSFT** [comment]
A fix for this is pending now.
