### ISSUE TITLE
Can't open a table

### ISSUE THREAD

**Issue by SuperNose** [microsoft/AzureStorageExplorer#4710]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.20.1

### Architecture

x64

### Storage Explorer Build Number

20210720.10

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Trying to open a table crashes SE with an exit dialog: "A renderer process crash caused storage explorer to stop working correctly".
Architecture: ia32; was not selectable in this BUG reporting wizard.
![image](https://user-images.githubusercontent.com/38764778/126860127-556f8078-e422-47a3-8465-fe7575559074.png)

### Steps to Reproduce

1. Launch SE
2. Open the (huge) table
3. Wait a few moments until the crash comes

### Actual Experience

SE is crashed

### Expected Experience

Table is opened

### Additional Context

The table contains quite a lot of binary data (split into more columns) and is also not opening from the Azure Portal. I can happily open the table from my own code and never realized the tools can't. Also, VS2019 is able to open the table from the "Cloud Explorer" normally, although it takes some while and keeps loading more records in the background.

**Comment by MRayermannMSFT** [comment]
@SuperNose

This is...interesting. If we gave you an email to send a SAS to would you be willing to share the table with us? The SAS could just have read permissions?
- Do you have an estimate of how big each row is?
- How many columns are there?
- How big is the size of the data in each column?
- What's the raw size of the binary data you are storing in each row?
- Can you tell us more about the shape of the binary data?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you still encountering this problem and still want help we reccommend opening an Azure support ticket from the portal You can also open a new issue here.
