### ISSUE TITLE
There is no red border for the tagValue field when typing one invalid tag key

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4712]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210726.1
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 20.04/ MacOS Big Sur 11.4
**Architecture**: ia32/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one Non-ADLS Gen2 storage account -> Blob Containers.
2. Select one blob container -> Click 'Show View Options'.
3. Select the 'Tag Query' option -> Type an invalid tagValue (Like: tagValu"e).
4. Check whether there is a red border for the tagValue field.

## Expected Experience ##
There is a red border.

Here is the screenshot when typing an invalid tagkey:
![image](https://user-images.githubusercontent.com/41351993/126966981-24d4f5a3-6438-4ac8-a67c-c583da6fbec8.png)

## Actual Experience ##
There is no red border.
![image](https://user-images.githubusercontent.com/41351993/126967330-ff07b1b1-6cbe-418d-902a-4a390a0ecfe4.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into main.
