### ISSUE TITLE
Keep consistent behaviors for the tag group query on the navigate bar and filter panel after clicking 'Reset'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4714]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210726.1
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 20.04/ MacOS Big Sur 11.4
**Architecture**: ia32/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##

1. Expand one Non-ADLS Gen2 storage account -> Blob Containers.
2. Select one blob container and open it -> Click 'Show View Options'.
3. Select 'Tag Query' -> Click 'Apply'.
4. Click 'Add Clause' -> Type a valid tagkey and tagvalue -> Click 'Apply'.
5. Click 'Add Clause' -> Type a valid tagkey and tagvalue -> Click 'Apply'.
7. Click 'Reset' -> Observe the navigation bar and the filter panel.
9. Check whether the behaviors are consistent.

## Expected Experience ##
The behaviors are inconsistent.

## Actual Experience ##
The behaviors are consistent.
![image](https://user-images.githubusercontent.com/41351993/126970782-4d90567e-c6eb-43c9-a441-c7177d380019.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into main.
