### ISSUE TITLE
A blob which belongs to blob container A can be queried by tag in the blob container B (Under the same storage account)

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4716]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210726.1
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 20.04/ MacOS Big Sur 11.4
**Architecture**: ia32/x64
**How Found**: Exploratory testing
**Regression From**: Previous release (1.20.1) 

## Steps to Reproduce ##

1. Expand one Non-ADLS Gen2 storage account -> Blob Containers.
2. Select one blob container -> Upload a blob with a valid tag [such as: key=tag, value=v1].
3. Create a new blob container -> Reopen the blob container.
4. Click 'Show View Options' -> Select the option 'Tag Query'.
5. Enter the tag of the blob which is uploaded in the step2 -> Click 'Apply'.
6. Check no item displays.

## Expected Experience ##
No item displays.

## Actual Experience ##
The blob which is uploaded in the step2 displays.

**Comment by JasonYeMSFT** [comment]
The query string is missing a @container={containerName} clause.

**Comment by MRayermannMSFT** [comment]
Fix merged into main.
