### ISSUE TITLE
The pasted blob doesn't display on the destination when the source is using the 'Flat' list mode

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4717]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210726.1
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 20.04/ MacOS Big Sur 11.4
**Architecture**: ia32/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Create a folder -> Upload a blob to the folder.
3. Click 'Show View Options' -> Select 'Flat' as the list mode.
5. Hide the view options -> Copy the blob.
6. Create a new blob container -> Paste the blob.
7. Check whether the blob displays on the destination.

## Expected Experience ##
The blob displays on the destination.

## Actual Experience ##
1. The blob doesn't display on the destination.
2. Display a successfully activity log indicating '0 items transferred'.
![image](https://user-images.githubusercontent.com/41351993/126982813-6b5a6d79-d435-46ea-8494-72c99973d886.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into main. Download is now disabled when the selection includes blobs in different directories. For example, if you can the blobs:

- a/b/foo.txt
- a/bar.txt
- g/h/i/j/wat.txt
- cool.txt

Then download is disabled because they are all in different directories.
