### ISSUE TITLE
Add '...' next to the 'Configure Soft Delete' on the context menu of 'Blob Containers'

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#472]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180724.4
**Commit**: 2605f1c9
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Expand one account and right click 'Blob Containers'.
2. Check the context menu.

#### Expected Experience: ####
It displays **'Configure Soft Delete...**' on the context menu. 

#### Actual Experience: ####
It displays 'Configure Soft Delete' on the context menu. 
![default](https://user-images.githubusercontent.com/34729022/43135593-7a0d6bfe-8f35-11e8-942b-6cc6c8c06898.png)

**Comment by JasonYeMSFT** [comment]
OK, will fix it.
