### ISSUE TITLE
Only delete blobs under one folder at once when trying to delete all items under flat list mode

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4720]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210727.2
**Branch**: main
**Platform/OS**: Windows 10
**Architecture**: ia32
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one Non-ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Create a folder then upload one blob to it.
3. Back to the root -> Create another folder and upload one blob to it.
4. Click 'Show View Options' -> Select 'Flat'.
5. Hide view options panel -> Select the two blobs then delete them.
6. Check whether the two blobs are deleted.

## Expected Experience ##
The two blobs are deleted.

## Actual Experience ##
Only one blob is deleted.
![image](https://user-images.githubusercontent.com/41351993/127084442-380b0d14-b11b-4b43-976e-2706c475372d.png)

## Additional Context##
1. If each folder contains at least two blobs. Select all of them to delete. Here are the behaviors.

> Only blobs under one folder are deleted.
> There are display 'total number completed' In the delete activity log when trying to delete them.

If I have two root folders and each folder has two blobs. Like the below. When deleting all items, Only the blobs under test1 folder are deleted. but display '4 completed' in the activity log.
![image](https://user-images.githubusercontent.com/41351993/127084774-6d10db22-18f4-4cdb-8f1f-73cf865048fe.png)
![image](https://user-images.githubusercontent.com/41351993/127084813-38945b25-2782-4174-9d29-fa4314fe63dd.png)

**Comment by MRayermannMSFT** [comment]
Fixed
