### ISSUE TITLE
Only download one folder's blobs when trying to download all blobs under flat list mode

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4721]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210727.2
**Branch**: main
**Platform/OS**: Windows 10
**Architecture**: ia32
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one Non-ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Create a new folder then upload blobs to it.
3. Back to the root -> Create another folder -> Upload blobs to it. <make sure no same blobs with the step2 blobs>
4. Click 'Show View Options' -> Select 'Flat'.
5. Hide view options panel -> Select all items -> Click 'Download'.
6. Check whether all the blobs are downloaded.

## Expected Experience ##
All blobs are downloaded.

## Actual Experience ##
Only the blobs under one folder are downloaded.

**Comment by MRayermannMSFT** [comment]
Fix merged into main. Download is now disabled when the selection includes blobs in different directories. For example, if you can the blobs:

- a/b/foo.txt
- a/bar.txt
- g/h/i/j/wat.txt
- cool.txt

Then download is disabled because they are all in different directories.

**Comment by v-xianya** [comment]
Update:
Verified on version 1.30.0
Download/Download All is enabled and succeeds to download blobs under the scenarios.
