### ISSUE TITLE
'Undelete Selected' is enabled for one blob folder with soft delete disabled

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#473]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180724.4
**Commit**: 2605f1c9
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Expand one account and make sure the soft delete is disabled for 'Blob Containers'.
2. Open one blob container and make sure under 'Active blobs(default)' -> Upload one folder to it.
3. Check the context menu for the uploaded folder.

#### Expected Experience: ####
The 'Undelete Selected' is disabled on the context menu.

#### Actual Experience: ####
The 'Undelete Selected' is enabled on the context menu.
![enabled](https://user-images.githubusercontent.com/34729022/43135623-8e10cf7e-8f35-11e8-991f-2df7ddf030ce.png)

**Comment by JasonYeMSFT** [comment]
Undelete is enabled if selection only has folders and deleted items. It is independent of the current delete policy.
