### ISSUE TITLE
Fail to get properties for one emulator blob

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4732]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210729.4
**Branch**: main
**Platform/OS**: Windows 10
**Architecture**: ia32
**Azurite Version**: 3.14.0
**How Found**: From running test cases
**Regression From**: Previous release (1.20.1)

## Steps to Reproduce ##
1. Install and start Azurite 3.14.0.
2. Launch Storage Explorer -> Expand 'Local & Attached -> Storage Accounts -> (Emulator - Default Ports)(Key)'.
3. Right click the 'Blob Containers' node -> Create a blob container.
4. Upload one blob -> Right click the blob -> Click 'Properties...'.
5. Check whether succeed to get the properties.

## Expected Experience ##
Succeed to get the properties.
![image](https://user-images.githubusercontent.com/41351993/127455779-c76d42ba-d4e0-43d9-a658-153cfa787432.png)

## Actual Experience ##
Fail to get the properties.
![image](https://user-images.githubusercontent.com/41351993/127455220-5962c51c-cd16-4e6a-9c58-cb7e1f89a14f.png)
![image](https://user-images.githubusercontent.com/41351993/127455277-9fc85243-abe5-4766-ba90-4a8360e1da2b.png)

**Comment by JasonYeMSFT** [comment]
This is caused by upgrading to v12.6.0 Blob SDK.
https://github.com/Azure/Azurite/issues/977

**Comment by v-xianya** [comment]
@MRayermannMSFT 
This issue doesn't reproduce when adding 'loose' flag.
