### ISSUE TITLE
Support shortcuts to open in new tab

### ISSUE THREAD

**Issue by Odwerneh** [microsoft/AzureStorageExplorer#4733]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Usually I need to have multiple Tables and Containers opened when analyzing an issue. It would be very helpful to have same options to "Open in new tab" as in other SW users are used to (web browsers, Windows GUI, ...) - CTLR + click and middle click. I think this change should be fairly simple but much appreciated.

### Desired Solution

I would appreciate if there will be an option to open a container, table or other storages in new tab by both mouse middle click and CTRL + left click. Currently the use must do right click -> open in new tab. 

### Alternatives and Workarounds

Right click -> open in new tab

**Comment by MRayermannMSFT** [comment]
Thanks for the feature request @Odwerneh ! You can track this issue if you'd like to follow the issue's development.

**Comment by MRayermannMSFT** [comment]
Maybe we can get this done in 1.22 during accessibility work? If not, then 1.23 is fine.

**Comment by JasonYeMSFT** [comment]
Ctrl/Cmd + click for opening as new tab is added for 1.23.0.
