### ISSUE TITLE
macOS Storage Explorer takes forever to start file transfer process when downloading from an Azure file share

### ISSUE THREAD

**Issue by rringham** [microsoft/AzureStorageExplorer#4735]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.20.1

### Architecture

x64

### Storage Explorer Build Number

20210720.10

### Platform

macOS

### OS Version

11.4

### Bug Description

It takes _forever_ for Storage Explorer to start transfering files when downloading them from an Azure File Share. Even just to get to the point where it pops up the "do you want to overwrite files?" dialog. It's very slow.

### Steps to Reproduce

1. Launch Storage Explorer
2. Navigate to a set of files in a folder in an Azure File Share
3. Select multiple large files (hundreds of MBs / GBs)
4. Press download

It takes several minutes before the transfer process actually starts, which makes no sense. It should start immediately - Azure Storage Explorer clearly knows what files are there. Just start downloading them one by one, immediately.

### Actual Experience

It takes several minutes before the transfer process actually starts, which makes no sense. It should start immediately - Azure Storage Explorer clearly knows what files are there. Just start downloading them one by one, immediately.

### Expected Experience

It should **not** take 5-10 minutes for Azure Storage Explorer to think about downloading files before it starts downloading them.

It takes several minutes before the transfer process actually starts, which makes no sense. It should start immediately - Azure Storage Explorer clearly knows what files are there. Just start downloading them one by one, immediately.

**Comment by MRayermannMSFT** [comment]
@rringham

What do you mean by "before the transfer process actually starts"? Do you mean:
- Any sort of UI feedback appears indicating that the transfer has been queued/started
- The activity for the download says something specific, and if so what?
- You see a conflict dialog?
Can you elaborate on that?

Also, can:

1. Do a download that reproduces the issue.
2. After it finishes, go to `~/.azcopy`
3. In that directory, find the newest `.log` file
4. Attach that in a response to this issue, you cannot attach the file via email, you will need to come to GitHub and attach the file directly:
![image](https://user-images.githubusercontent.com/21112697/127903233-8433e257-ec9a-43fd-9888-e2fdbfe8762b.png)

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you still need help with this problem, we recommend opening an Azure support ticket from the portal, or you can open a new issue here.
