### ISSUE TITLE
Program crash after deleting a Blob Container and clicking on an item in the list too quickly

### ISSUE THREAD

**Issue by MisterDoug99** [microsoft/AzureStorageExplorer#4736]
When I delete a Blob Container, if I click on an element in the remaining list too soon after the delete confirmation window disappears, the program crashes.

![image](https://user-images.githubusercontent.com/42181023/127523844-9cb97196-593e-473a-8718-0b222bf72a7f.png)

**Comment by MRayermannMSFT** [comment]
@MisterDoug99 
1. What version of Storage Explorer are you using? If you are not on the latest, please upgrade to the latest by going to https://storageexplorer.com 
2. Can you reliably reproduce this issue?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you still need help with this problem, we recommend opening an Azure support ticket from the portal, or you can open a new issue here.
