### ISSUE TITLE
query by timestamp return nothing

### ISSUE THREAD

**Issue by xckai** [microsoft/AzureStorageExplorer#4738]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.20.1

### Architecture

x64

### Platform

Windows

### Bug Description

query by timestamp return nothing;
origin data:
![image](https://user-images.githubusercontent.com/5928422/127596247-0406bf1c-597e-49d8-b902-2ce251c3c73e.png)
 
 query by timestamp return nothing;
![image](https://user-images.githubusercontent.com/5928422/127596287-6fc683b7-93db-4443-9ec0-c78fd5556696.png)
![image](https://user-images.githubusercontent.com/5928422/127596309-49ce7b1b-3bea-4d2e-956e-72f4a5f4d0f3.png)

### Steps to Reproduce

using Serilog.Sinks.AzureTableStorage to general some  log;
query log data by timestamp;

### Actual Experience

I'm using Serilog.Sinks.AzureTableStorage in my project for updating logs to Azure Cosmos Db, and I want query some logs order by log item‘s timestamp, and it return no data when I query by timestamp key works;

**Comment by MRayermannMSFT** [comment]
@xckai a couple of questions:
1. How did you connect to your table?
2. Can you click on this button:
![image](https://user-images.githubusercontent.com/21112697/127902130-a47ce12d-22a8-4fb9-a31d-2f0382362661.png)
and share the text representation of the query with us:
![image](https://user-images.githubusercontent.com/21112697/127902186-52317510-6072-4cfb-bb2e-89f928f5a12e.png)

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you still need help with this problem, we recommend opening an Azure support ticket from the portal, or you can open a new issue here.
