### ISSUE TITLE
The border in the 'Retry Azcopy' dialog is incomplete under the theme 'Light (default)'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4739]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210801.1
**Branch**: main
**Platform/OS**: Windows 10
**Architecture**: ia32
**How Found**: From running test cases
**Regression From**: Previous release (1.20.1)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload two blobs.
3. Create snapshots for the two blobs.
4. Select the two blobs -> Delete them.
5. Click 'Retry...' next to the activity log.
6. Observe the Azcopy dialog -> Observe the border in it is complete.

## Expected Experience ##
The border is complete.
![image](https://user-images.githubusercontent.com/41351993/127827946-79e1c2af-877a-4fc3-8a9e-ed2316c9b158.png)

## Actual Experience ##
The border is incomplete.
![image](https://user-images.githubusercontent.com/41351993/127827660-750d92d2-1407-485b-8d05-2a5ceeb475a3.png)

## Addition Info ##
1. This issue doesn't reproduce on Linux & MacOS.
2. This issue only reproduces on 'Light (default)' theme.
3. This issue also reproduces in the Azcopy dialog when there are overwrite conflicts for files/blobs.
![image](https://user-images.githubusercontent.com/41351993/127827765-c85645b5-75b5-45cb-8ce6-9a8943ce4c53.png)

**Comment by JasonYeMSFT** [comment]
I merged a fix which raises an "resize" event on the dialog window to force re-flow the elements.

**Comment by v-xianya** [comment]
Hi @JasonYeMSFT 
Verified this issue on the build 20210803.3. Reproduce. So reopen it.

**Comment by JasonYeMSFT** [comment]
After some additional investigation, the cause seems to be the Electron upgrade and we don't know how to fix it entirely.

**Comment by v-xianya** [comment]
@craxal Thank you for the reminder. Verified this issue on the latest build 20210829.9. Fixed.
