### ISSUE TITLE
There is an extra property 'Last Modified' with a value 'Error loading property' on the Properties panel of one SAS attached blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4740]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210801.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: From running test cases
**Regression From**: Previous release (1.20.1)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Select one blob container.
3. Attach the blob container via SAS URL.
4. Observe the 'Properties...' panel of the SAS attached blob container.
5. Check there is no property 'Last Modified'.

## Expected Experience ##
There is no property 'Last Modified'.
![image](https://user-images.githubusercontent.com/41351993/127830239-627d6591-5b03-4a32-b25a-21797074c85f.png)

## Actual Experience ##
There is an extra property 'Last Modified' with a value 'Error loading property'.
![image](https://user-images.githubusercontent.com/41351993/127830229-52a42d11-4f02-4e4a-99d8-f9d1d761c3c6.png)

## Addition Info ##
This issue also reproduces for one SAS attached ADLS Gen2 blob container/directory.

**Comment by v-xianya** [comment]
Verified this issue on the build 20210803.3. Reproduce.

**Comment by craxal** [comment]
@v-xianya The change that fixes this did not make it into last night's build. Please reverify with the next build.

**Comment by v-xianya** [comment]
@craxal got it. we will verify this issue once there is a new build.
