### ISSUE TITLE
The characters 'ཕྱི་དྲོ་' displays in the value of the property 'Last Modified' against blob containers/file shares/blobs

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4742]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210801.1
**Branch**: main
**Platform/OS**: MacOS Big Sur 11.4
**Architecture**: x64
**How Found**: From running test cases
**Regression From**: Previous release (1.20.1)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Select one blob container -> Observe its Properties panel.
3. Check the value of the property 'Last Modified' displays well.

## Expected Experience ##
The value displays well.

## Actual Experience ##
The character ''ཕྱི་དྲོ་' displays in the value.
![image](https://user-images.githubusercontent.com/41351993/127837519-d67234f9-11b7-4cb5-b6a3-0d433560fea2.png)

## Additional Info ##
This issue doesn't reproduce on Linux & Windows.

**Comment by craxal** [comment]
@v-xianya
* Just for clarity, what locale is Storage Explorer running with?
* What locale is the OS running with?
* Can you please take a screenshot of your Language & Region settings?

**Comment by jinglouMSFT** [comment]
The interesting character itself is in Tibetan.

**Comment by v-xianya** [comment]
Hi @craxal 
1. Storage Explorer running with is 'English'.
2. The OS running with is 'English'.
3. Here is the screenshot:
![image](https://user-images.githubusercontent.com/41351993/127948632-fd549b13-fbf9-4eb8-b758-a9bde3d734e8.png)

**Comment by v-xianya** [comment]
@craxal 
This is because the language 'Tibetan' is the primary language in the preferred languages panel.
This issue doesn't reproduce after we remove the language 'Tibetan'. So it is okay to close this bug.

**Comment by craxal** [comment]
@v-xianya Thanks! Since the problem goes away, and you opened another bug, I'll close this one.
