### ISSUE TITLE
Hitting spacebar/enter on toolbar buttons doesn't execute buttons

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#4743]
😢 Observed on main, commit da530cb6a38c9ef7d3c6ed14d993f1f49f3b1596

**Comment by craxal** [comment]
I'm marking this as a regression, because this was definitely working before. It might be due to the Electron update, but I'm not sure why default `<button>` behavior would suddenly stop working.
