### ISSUE TITLE
Show "expired" info in status display

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#4744]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

It is hard to tell if a SAS attachment has expired

### Desired Solution

An "expired" status display is on the Node

- [x] Storage Account
- [x] Blob Containers
- [x] File Share
- [x] Queue
- [ ] #5247

**Comment by JasonYeMSFT** [comment]
- [ ] Storage Account
- [ ] Blob Containers
- [ ] File Share
- [ ] Queue
- [ ] Table

**Comment by JasonYeMSFT** [comment]
Pushing adding support for File Share and Table to 1.22.0.

**Comment by MRayermannMSFT** [comment]
I completed this for file shares.

**Comment by JasonYeMSFT** [comment]
The Table container level nodes hasn't been moved to extension yet.

**Comment by craxal** [comment]
@JasonYeMSFT Working on it.
