### ISSUE TITLE
Support empty end date in 'Undelete Blobs by Date' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#475]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180724.4
**Commit**: 2605f1c9
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Expand one account and enable soft delete for 'Blob Containers'.
2. Open one blob container which contains one blob at least.
3. Delete one blob -> Switch to 'Active and deleted blobs' -> Right click the deleted blob and select 'Undelete by Date'.
4. Set the 'End Date' is empty on 'Undelete Blobs by Date' dialog.

#### Expected Experience: ####
The empty end date is valid and it default as the current date.

#### Actual Experience: ####
The empty date is invalid.

**Comment by JasonYeMSFT** [comment]
When the dialog is prompted, the default timestamp for the end date is the current date. There is no need to make it empty to set it to current date. By the way, it is not very clear for a new user that empty timestamp is representing current date.

**Comment by v-xuanzh** [comment]
OK, thanks for your sharing. :)
