### ISSUE TITLE
There is a 'Leased' icon for the snapshot when creating the snapshot for one leased blob under snapshot view

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4751]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210803.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload a blob.
3. Right click the blob -> Click 'Manage History -> Manage Snapshots'.
4. Acquire lease for the blob -> Create snapshot for the leased blob.
5. Check there is no leased icon for the snapshot.

## Expected Experience ##
There is no leased icon for the snapshot.

## Actual Experience ##
There is a leased icon for the snapshot.
![image](https://user-images.githubusercontent.com/41351993/128142544-b1656ca0-1fc3-45dc-afd2-68dc6467eb83.png)

## Additional Info ##
The leased icon disappears after manfully refreshing.

**Comment by MRayermannMSFT** [comment]
If the fix is fast go for it otherwise won't fix for now.
![](https://media.giphy.com/media/HdcimOKferlkI/giphy.gif)

**Comment by v-xianya** [comment]
@craxal Verified this issue on the build 20210810.8.
1. Fixed on the normal blobs.
2. Reproduces on the ADLS Gen2 blobs.
