### ISSUE TITLE
The left side of the scrollbar extends beyond the border in the 'Retry Azcopy' dialog of one emulator blob

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4753]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210803.3
**Branch**: main
**Platform/OS**: Windows 10
**Architecture**: ia32
**Azurite Version**: 3.14.0
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Install and start Azurite 3.14.0.
2. Launch Storage Explorer -> Expand 'Local & Attached -> Storage Accounts -> (Emulator - Default Ports)(Key)'.
3. Right click the 'Blob Containers' node -> Create a blob container.
4. Upload one blob -> Upload the blob again.
5. Select 'Do not upload' -> Click 'Apply'.
6. Click 'Retry...' next to the activity log.
7. Observe the scrollbar on the Retry Azcopy log shows well.

## Expected Experience ##
The scrollbar shows well.

## Actual Experience ##
The left side of the scrollbar extends beyond the border.
![image](https://user-images.githubusercontent.com/41351993/128166833-9d7aefc7-d778-445c-ae43-bf1042c5d894.png)

## Additional Info ##
1. There is an extra vertical scrollbar under 'Dark/High-Contrast - Black/High Contrast - White' themes.
![image](https://user-images.githubusercontent.com/41351993/128167313-e4561ff6-1c1f-4ca1-b22f-d3b669d688bc.png)

**Comment by JasonYeMSFT** [comment]
According to our layout, this is by design. The "table" has a left padding which results in the "indentation" while the scrollbar is on the whole html container so it will extend a little bit.

**Comment by v-xianya** [comment]
@JasonYeMSFT No more question for this issue based on your comments. Are you planning to fix the extra scrollbar in additional info? I missed this scenario when opening the bug. [4685](https://github.com/microsoft/AzureStorageExplorer/issues/4685)😯

**Comment by MRayermannMSFT** [comment]
Remove padding? If margin preserves indentation and fixes bug then do margin, otherwise YEET that indentation outta here.

**Comment by v-xianya** [comment]
Verified this issue on the build 20210810.8. Fixed.
![image](https://user-images.githubusercontent.com/41351993/128798075-9626e73b-06de-4e48-9c65-620ef7c56972.png)
