### ISSUE TITLE
Migrate blob path related utility functions to @storage-explorer/azure-connections

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#4754]
We have lots of duplicate implementations of blob path related utility functions and they should be merged to one place.
- [x] AzCopy
- [x] Blob extension
- [x] Standalone

**Comment by MRayermannMSFT** [comment]
Please also satisfy https://github.com/microsoft/AzureStorageExplorer/issues/4731, though I believe these are basically the same issue.

**Comment by JasonYeMSFT** [comment]
Done for the blob extension. Will await the changes in rel/1.24.0 before checking the box. Move Standalone work to 1.25.0.
