### ISSUE TITLE
Can't reset tag queries which in the address bar when navigating to the Snapshots/Versions view previously

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4756]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210803.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Container.
2. Create one blob container -> Upload one blob.
3. Right click the blob -> Click 'Edit Tags...' -> Add one tag for the blob.
4. Open the view options panel -> Select the 'Tag Query' -> Input the blob's tag -> Click 'Apply'.
5. Click 'Manage History -> Manage Snapshots/Manage Versions' -> Exit the Snapshots/Versions' view.
6. Reset the tag query -> Check whether succeed to reset tag queries in the address bar.

## Expected Experience ##
Succeed to reset.

## Actual Experience ##
1. Can't reset tag queries.
2. Navigate to the Snapshots/Versions view.
![image](https://user-images.githubusercontent.com/41351993/128316174-c4004d24-8707-40f6-94cb-3c051ba89a4d.png)

## Additional Context ##
Here is the record:
![issuerecord](https://user-images.githubusercontent.com/41351993/128321644-ae5eda41-78f3-4fbc-b374-5f0c1527e4bf.gif)

**Comment by v-xianya** [comment]
Verified this issue on the latest build main/20210812.3. Reproduce.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20210817.3.Fixed.
