### ISSUE TITLE
Succeed to execute 'Rename' action under one attached SAS ADLS blob container with permissions 'List, Read, Move'

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#4759]
**Storage Explorer Version:** 1.21.0-dev
**Build Number:** 20210806.4
**Branch:** main
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ MacOS Big Sur 11.4
**Architecture:** ia32/x64
**How Found:** Exploratory testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload a blob.
3. Right click the blob container -> Click 'Get Shared Access Signature...'.
4. Select permissions 'Read, List, Move' -> Create and copy the SAS URL.
5. Open the connect dialog -> Attach the blob container via the copied SAS URL.
6. Switch to the attached blob container.
7. Rename the blob -> Check the result of the rename action.

## Expected Experience ##
Fail to rename the blob due to insufficient permission.

## Actual Experience ##
Succeed to rename.

**Comment by craxal** [comment]
@v-kellyluo A rename is a move operation. Rename and move use the same API. Therefore, this is by design.
