### ISSUE TITLE
Public access is not permitted on this storage account.

### ISSUE THREAD

**Issue by Rohanluthraknack** [microsoft/AzureStorageExplorer#4764]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.20.1

### Architecture

x64

### Storage Explorer Build Number

Windows

### Platform

Windows

### OS Version

Windows 10

### Bug Description

I am trying to Public access in storage account.

We have Azure account from SAP Commerce

Here is an error code.

{
  "name": "RestError",
  "message": "Public access is not permitted on this storage account.\nRequestId:39f1a9dc-b01e-008a-0f35-8d84de000000\nTime:2021-08-09T15:45:44.3331245Z",
  "stack": "RestError: Public access is not permitted on this storage account.\nRequestId:39f1a9dc-b01e-008a-0f35-8d84de000000\nTime:2021-08-09T15:45:44.3331245Z\n    at new RestError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:2390:28)\n    at handleErrorResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:3274:17)\n    at C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:3210:18\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
  "code": "PublicAccessNotPermitted",
  "statusCode": 409,
  "request": {
    "streamResponseStatusCodes": {},

### Steps to Reproduce

1. Add storage account
2. Goto Blob container.
3. Update public access properties.
4. We have the issue there. 

### Actual Experience

Not allowing to change.

**Comment by MRayermannMSFT** [comment]
@Rohanluthraknack it possible that when your storage account was created the **AllowBlobPublicAccess** property was set to false. Storage Explorer does not currently expose this property, but there are docs on how you can check it yourself.

This doc page: https://docs.microsoft.com/en-us/azure/storage/blobs/anonymous-read-access-configure?tabs=portal#allow-or-disallow-public-read-access-for-a-storage-account shows you how to set/check the value for Portal, CLI, and PowerShell. 

Let us know if you have any other questions regarding this issue.

**Comment by Rohanluthraknack** [comment]
@MRayermannMSFT I couldn't able to find this setting but As we have it with SAP so might be we do not have options to check it.

Thanks and please let me know if you know how to have it working SAP Commerce Hotfolder functionality.

**Comment by MRayermannMSFT** [comment]
@Rohanluthraknack unfortunately I'm not familiar with SAP Commerce Hotfolder. It seems like at this point your best bets are probably:
- open an Azure support ticket (you can do this via the Azure Portal)
- reach out to SAP Commerce and ask them if they storage accounts they provision for you have public access turned off

**Comment by MRayermannMSFT** [comment]
Closing due to this issue being out of our hands.
