### ISSUE TITLE
.azdownload files are present on dev. I have to remove them daily. How to fix this issue

### ISSUE THREAD

**Issue by omptech** [microsoft/AzureStorageExplorer#4769]

**Comment by MRayermannMSFT** [comment]
@omptech as long as your downloads finish then .azdownload files should be auto-deleted. Are your dowloads failing/are you cancelling?

**Comment by omptech** [comment]
No

**Comment by MRayermannMSFT** [comment]
@omptech hmmm well that's odd if true. Can you please:

1. Clear out any .azdownload files you currently have
2. Going forward, after any successful downloads using Storage Explorer or AzCopy v10, check if there are .azdownload files
3. If there are, then send us the latest AzCopy log file, which can be found in `~/.azcopy`. You can send/attach a file by replying to this issue directly on GitHub. Also if possible give us a full/partial list of the .azdownload files you see.
4. After any not-successful/canceled downloads, consider clearing out the .azdownload files (in this situation it would be expected to see them) as to not cause confusion when checking for them after successful downloads.

Thanks.

**Comment by MRayermannMSFT** [comment]
@omptech , since you haven't come back with any further repros, we're going to go ahead and close this issue. If you do encounter the .azdownload files in `dev` after a successful transfer, please follow the above steps and open a new issue with all relevant information.

**Comment by mike-westaway** [comment]
I had the .azdownload files issue which is now resolved. I’ve added ‘echo off’ at the top of the batch file (containing the azcopy commands) and now its not writing the command output to the window (which was likely interfering with the renaming of the working file).

**Comment by ajallooeian** [comment]
In case someone needs to do it automatically:

```
from azure.storage.blob import BlobServiceClient
import os

def delete_azdownload_files(container_name, connection_string):
    blob_service_client = BlobServiceClient.from_connection_string(connection_string)
    container_client = blob_service_client.get_container_client(container_name)

    blobs_list = container_client.list_blobs()
    for blob in blobs_list:
        if '.azDownload' in blob.name:
            print(f"Deleting blob: {blob.name}")
            container_client.delete_blob(blob.name)

if __name__ == "__main__":
    container_name = "your container name"
    connection_string ="you connection string"
    delete_azdownload_files(container_name, connection_string)
```
