### ISSUE TITLE
An error dialog prompts with the info 'BadRequest' when clicking 'Configure CORS Settings...' for emulator 'Tables' node 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4770]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210810.8
**Branch**: main
**Platform/OS**: Windows 10
**Architecture**: ia32
**Emulator Version**: Azurite 3.14.0
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Install and run Azurite 3.14.0 -> Launch Storage Explorer.
2. Expand 'Local & Attached -> Storage Accounts -> (Emulator - Default Ports)(Key)'.
3. Right click the 'Tables' node -> Click 'Configure CORS Settings'.
4. Check no error occurs.

## Expected Experience ##
No error occurs.

## Actual Experience ##
An error dialog prompts.
![image](https://user-images.githubusercontent.com/41351993/128817996-e18ebd07-04a3-4708-a86c-22d3f391d04b.png)
![image](https://user-images.githubusercontent.com/41351993/128818045-575df93a-0786-40bc-885a-a7fd6b1a5069.png)

## Additional Context ##
This issue doesn't reproduce when using Azure Storage Emulator 5.10.0.0.

**Comment by craxal** [comment]
Azurite does not currently support CORS for tables (see Azure/Azurite#958).

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20211220.2, it doesn't reproduce. So we are going to close it.
