### ISSUE TITLE
It would be better to disable the action 'Undelete' when the selection contains soft deleted items with the same name 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4772]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210810.8
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one blob -> Soft delete the blob.
3. Upload the same blob -> Soft delete the blob.
4. Switch to the 'Deleted only' context -> Select the two soft-deleted blobs.
5. Right click them -> Check whether the action 'Undelete' is disabled.

## Expected Experience ##
The action 'Undelete' is disabled.

## Actual Experience ##
The action 'Undelete' is enabled.

**Comment by JasonYeMSFT** [comment]
This has been fixed for blobs. Due to a known issue #4808, you won't be able to select just a soft deleted directory if an active directory exists.

**Comment by v-xianya** [comment]
@JasonYeMSFT Verified this issue on the build 20210819.3. Reproduce.
![image](https://user-images.githubusercontent.com/41351993/129999412-586d1d2d-0860-464b-9e05-2aab342e8c40.png)

**Comment by JasonYeMSFT** [comment]
I merged another change to disable undelete when there are duplicates of deleted item in the selection

**Comment by v-xianya** [comment]
Verified this issue on the build 20210822.1. Fixed.
![image](https://user-images.githubusercontent.com/41351993/130396591-5def8446-0728-4f96-8601-d0c545ffd962.png)

**Comment by rgnanaprakash** [comment]
Is it possible to undelete the blob from Azure Storage Explorer?  assume soft delete is enabled

**Comment by JasonYeMSFT** [comment]
@rgnanaprakash I think so. To view the deleted blobs you will need to select a view context that includes deleted items. Once you see them, you can select them and execute "Undelete" command from the toolbar or context menu.

![image](https://user-images.githubusercontent.com/39359541/195904081-72cbfb8e-4c53-40a0-8ab3-85e3e93d89b0.png)

**Comment by rgnanaprakash** [comment]
thanks Jason. Good to know its possible. How do you enable to get this dropdown. Can you please help with the steps?

**Comment by JasonYeMSFT** [comment]
Could you open a new issue providing some basic information and describing where you are at in Storage Explorer? The dropdown is in the blob explorer by default. If you aren't seeing it you probably haven't connected to that container yet so it might take more steps before undeleting your blobs.

**Comment by rgnanaprakash** [comment]
sure. Iam connected to  the container and able to browse all the blobs.  I see the deletion id, remaining days, deleted time columns showing up but not the dropdown list.

<img width="446" alt="image" src="https://user-images.githubusercontent.com/71672910/195908554-3bfa23e1-441c-4bec-8fc4-638cffcbfe2f.png">

**Comment by JasonYeMSFT** [comment]
Oh, I see. You are using ADLS Gen2. You need to enable this feature flag to turn on that dropdown. 
![Screen Shot 2022-10-14 at 10 52 33 AM](https://user-images.githubusercontent.com/39359541/195910272-9891f6e8-c8c6-49bb-b8a1-4d132871ca14.png)

**Comment by rgnanaprakash** [comment]
Cool. Got it. Thanks a lot @JasonYeMSFT. Really appreciate your help!
