### ISSUE TITLE
It would be much better to remove the description "if you are looking for deleted blobs, try switching to the 'Deleted only' context" under the 'Deleted only' context

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4773]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210810.8
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Check the description on its editor.
3. Switch to the 'Deleted only' context.
4. Observe the description.

## Expected Experience ##
It would be much better to remove `if you are looking for deleted blobs, try switching to the "Deleted only" context` from the description.

## Actual Experience ##
Still show the same description.
![image](https://user-images.githubusercontent.com/41351993/128827647-3cdb088d-156c-4b37-a28a-62d937656e21.png)

**Comment by JasonYeMSFT** [comment]
Currently the 2nd view context "Active and soft deleted" doesn't give back all the soft delete items. Any orphaned soft deleted blobs is only accessible via the 3rd deleted only view context. I decided to add that additional string just to help people find their data in some cases.  I understand that if they have active items and orphaned items mixed together this doesn't help but I think this is better than nothing.

**Comment by JasonYeMSFT** [comment]
The data table API doesn't seem to allow us dynamically changing that string. Won't fix for now.
