### ISSUE TITLE
The string in the address bar is different between the two split tabs for ADLS Gen1 explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4776]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210810.8
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Create a data lake store account in portal.
2. Launch Storage Explorer and open the created data lake store account.
3. Click 'New Folder' -> Keep the default name then click 'OK'.
4. Repeat step3.
5. Right click the tab -> Click 'Split'.
6. Check whether the two tabs keep the same.

## Expected Experience ##
The two tabs keep the same.

## Actual Experience ##
The string in the address bar is different between the two tabs.
![image](https://user-images.githubusercontent.com/41351993/128844222-5e1e2b23-fe90-4c92-a4e5-69b3caee4e68.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20210817.3.Fixed.
