### ISSUE TITLE
No red border shows for the 'Username' field when there is an error message indicating that username is required

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4783]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210811.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer.
2. Click 'Edit -> Configure Proxy' -> Switch the source to 'Use app proxy settings'.
3. Check the option 'Use a username and password'.
4. There is an error message indicating the username is required.
5. Verify whether a red border shows for the 'Username' field.

## Expected Experience ##
A red border for the 'Username' field.

## Actual Experience ##
No red border shows for the 'Username' field.
![image](https://user-images.githubusercontent.com/41351993/128978414-f6e8ae6b-2143-49ab-b776-c7270e9af120.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20210817.3.Fixed.
