### ISSUE TITLE
The content of Bypass field is incorrect if setting proxy to 'Use app proxy settings' then reopen Proxy Settings dialog

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#4784]
**Storage Explorer Version:** 1.21.0-dev
**Build Number:** 20210811.4
**Branch:** main
**Platform/OS:** Windows 10
**Architecture:** ia32
**How Found:** From running test cases
**Regression From:** Not a regression
## Steps to Reproduce ##

1. Launch Storage Explorer -> Click 'Edit -> Configure Proxy'.
2. Select 'Use app proxy settings' -> Click 'OK'
4. Click 'Edit -> Configure Proxy'.
5. Check whether the content of Bypass field is correct.

## Expected Experience ##
The content of Bypass field is correct.

## Actual Experience ##
The content of Bypass field is incorrect.
![image](https://user-images.githubusercontent.com/87792676/129012540-48886b59-d72c-4229-a2e8-96725b01464d.png)

## More Info ##
For Settings panel. Here is the behavior.

Repo Steps:

1. Go to 'Settings -> Application -> Proxy' -> Select 'Use app proxy settings'.
2. Set 'Hostname' to 'localhost' and set 'Port' to 8888.
3. Close 'Settings' tab and reopen.
4. Observe the content of Bypass.

![image](https://user-images.githubusercontent.com/87792676/129015442-3c38eb0f-69dc-42f2-a840-7042b296dddb.png)

**Comment by craxal** [comment]
@v-kellyuo What was the value of Bypass at the beginning of the repro steps? What is the "correct" value? That is, what value are you expecting?

I suspect this is in part due to a bug somewhere in the configurations system, because "localhost, 127.0.01" keeps getting inserted when it shouldn't be (it's the default value).

**Comment by v-kellyluo** [comment]
@craxal 
1. At the beginning of the repo steps, the value of 'Hostname' is 'localhost', and the 'Port' is '8888'.
2. There is an extra ',' in the content of Bypass field. If we delete the  ',' and then reopen 'Proxy Settings' dialog, the content of Bypass field is as below.
![image](https://user-images.githubusercontent.com/87792676/129127853-f5fe68af-8c76-49d3-8e09-56794f62f85a.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20210817.3.Fixed.
