### ISSUE TITLE
Can't access storage account from Azure Storage Explorer

### ISSUE THREAD

**Issue by james-camacho-ab** [microsoft/AzureStorageExplorer#4786]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

latest version

### Regression From

no

### Architecture

x64

### Platform

Windows

### OS Version

Windows 10

### Bug Description

{
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"self signed certificate in certificate chain\\\",\\n  \\\"stack\\\": \\\"Error: self signed certificate in certificate chain\\\\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1484:34)\\\\n    at TLSSocket.emit (events.js:310:20)\\\\n    at TLSSocket._finishInit (_tls_wrap.js:927:8)\\\\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:697:12)\\\",\\n  \\\"code\\\": \\\"SELF_SIGNED_CERT_IN_CHAIN\\\"\\n}\""
}

### Steps to Reproduce

Launch Storage Explorer
By default doesn't connect

### Actual Experience

![image](https://user-images.githubusercontent.com/85585586/129092898-62483a75-da01-4a06-967e-0eab878d5543.png)

**Comment by MRayermannMSFT** [comment]
Hi, it sounds like you may be behind a proxy. First, please upgrade to the latest version of storage explorer if not already done so. You can download it from https://storageexplorer.com.

After you update, we recommend:

- Try using system proxy, which you can read about in our networking documentation: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network
- Try setting up proxy manually. You can read the proxy section in our troubleshooting guide for additional help with that: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#proxy-issues

If neither of those help feel free to come back here to let us know what happaned.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue we suggest:
- try the above troubleshooting steps
- open an Azure support ticket via the portal
- open a new issue here
