### ISSUE TITLE
The red border on the Bypass field doesn't disappear after switching the source to 'Do not use proxy'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4787]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210812.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Bug Descriptions ##
Enter an invalid pattern to Bypass field, then switch the source to 'Do not use proxy/Use environment variables/Use system proxy(preview)', the red border on the Bypass field doesn't disappear.

## Steps to Reproduce ##
1. Launch Storage Explorer.
2. Click 'Edit -> Configure Proxy' -> Switch the source to 'Use app proxy settings'.
3. Input an invalid pattern to the Bypass field.
4. An error message occurs and a red border shows on the Bypass field.
5. Switch the source to 'Do not use proxy'.
6. Check the error message and the red border disappear.

## Expected Experience ##
The error message and the red border disappear.

## Actual Experience ##

1. The error message disappears.
2. The red border doesn't disappear.
![image](https://user-images.githubusercontent.com/41351993/129129355-f4f0ec37-97a5-4fa1-8cb9-02af088b7dc9.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20210817.3.Fixed.
