### ISSUE TITLE
1.4.0 build 20180723.11 (RC1) Unable to retrieve child resource when clicking on the storage account node after installation

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#479]
**Storage Explorer Version**: v1.4.0 build 20180723.11
**Platform/OS Version**:  Windows 10
**Architecture**: 64 bit
**Regression From**: v1.3.1

#### Steps to Reproduce: ####
1. Install 20180723.11 to replace 1.3.1
2. Launch Storage Explorer after the installation completed. Click to expand one of my subscriptions in the treeview. 

#### Expected Experience: ####
All my storage resources under that subscription should expand on the left side. 

#### Actual Experience: ####
Getting the below error and none of the accounts was expanded. They all showed message "Load more".
"Unable to retrieve child resources.
 Details: Cannot read property 'connectionString' of undefined"

Going back to the "Manage Accounts" tab and clicking on the Apply button w/o modify anything.  Then redo'ing what's done the first time, the problem went away. 

![image](https://user-images.githubusercontent.com/10081483/43160977-8d36cf30-8f3b-11e8-9958-b83f78b9dbde.png)

**Comment by jinglouMSFT** [comment]
This doesn't repro on 20180724.4 anymore.  Closing.

**Comment by pauldispace** [comment]
Version: 1.4.0
Platform: macOS
Architecture: x64
Build Number: 20180803.3

I'm getting this issue on Mac, version 1.4.0. Happens after I've attached a local storage emulator, and occurs every time the app is started.

<img width="1920" alt="fullscreen_07_08_2018__18_13" src="https://user-images.githubusercontent.com/42138886/43791565-f90d4eb8-9a6d-11e8-913b-c29b671c855c.png">
