### ISSUE TITLE
It would be better to navigate to its specific part after clicking the learn more link in 'Shared Access Signature' dialog for services

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4797]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210813.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Bug Descriptions ##
Referred to the learn link in the 'Access Policies' dialog, it would be better to navigate to its specific part after clicking the learn more link in 'Shared Access Signature' dialog for services (blob containers/file shares/queues/tables).

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Right click one blob container -> Click 'Get shared Access Signature...'.
3. Click the link 'Learn more about permissions'.
4. Check whether it navigates to the blob containers part.

## Expected Experience ##
It navigates to the blob containers part.

## Actual Experience ##
It doesn't navigate to the blob containers part.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20210817.3.Fixed.
