### ISSUE TITLE
The option 'Prefix' that has been filled in will be selected after clicking 'Reset' to reset tag queries

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4798]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210813.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Select one blob container -> Then open it.
3. Open view options panel -> Type a character like 'a' into prefix field.
4. Then select the 'Tag Query' -> Add a valid clause -> Click 'Apply'.
5.  Observe the path shows filter by tag query -> Click 'Reset'.
7. Check whether the clause is reset and the option 'Tag Query' is still selected.

## Expected Experience ##
The clause is reset and  the option 'Tag Query' is selected.

## Actual Experience ##
The clause is reset and  the option 'Prefix' is selected.
![optionview](https://user-images.githubusercontent.com/41351993/129337866-a192f453-ffef-4d22-8641-0b818bdb11c6.gif)

**Comment by MRayermannMSFT** [comment]
Given our new design of "reset", I don't think there's anything we can do about this. It is a minor change in behavior. Good find though @v-xianya. This is not something we had thought about. Won't fixing for now, but maybe I'll revisit if I can think of something.
