### ISSUE TITLE
Add a feature to allow receiving blob from others

### ISSUE THREAD

**Issue by xiaomi7732** [Microsoft/AzureStorageExplorer#48]
User Story:
My customer has some big files. As a business, I want to give the customer a quick & easy way to upload files. We both have Storage Explorer installed already. I want to right click on the blob container to get some link; Send it over to the customer; The customer click the link, bring up the storage explorer and have a space to drop the file in already.

There are some existing features like Copy Direct Link to the Blob & SAS token. Each have some limitations.
* The direct link is easy to use for the customer, but it requires the Customer to have access to my Azure storage resource;
* SAS has permission control, but:
1. it is still a multi-step operation.
2. it requires the customer to actively click on the 'Add Account' button - not as easy as clicking a hyperlink.

**Comment by MRayermannMSFT** [comment]
We're going to resolve this as won't fix as sending someone a SAS and then having them attach it isn't that many steps and we don't want to create links that automatically attach things.
