### ISSUE TITLE
An extra scrollbar displays in the 'Access Policies' dialog when adding the maximum number of access policies on Windows

### ISSUE THREAD

**Issue by v-xinda** [microsoft/AzureStorageExplorer#4800]
**Storage Explorer Version:** 1.21.0-dev
**Build Number:** 20210816.1
**Branch:** main
**Platform/OS:** Windows 10
**How Found:** Exploratory testing
**Architecture:** ia32
**Regression From**: Previous release (1.20.1)

## Steps to Reproduce ##
1. Expand a storage account -> Queues -> Create a queue.
2. Right click the queue -> Click 'Manage Stored Access Policies...' -> Pop up a 'Access Policies' dialog.
3. Add the maximum number of access policies it allows to add. 
4. Check whether there is no extra scrollbar in the dialog.

## Expected Experience ##
No extra scrollbar displays in the 'Access Policies' dialog.

## Actual Experience ##
An extra scrollbar displays in the 'Access Policies' dialog.
![actual](https://user-images.githubusercontent.com/57662131/129531989-728d6c36-eea6-4112-8eea-50518bfc3ba4.gif)

## Additional Context ##
This issue also reproduces for blob container, file share and table.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20210817.3, the extra scrollbar appears for a while, and then it disappears automatically.

![extra](https://user-images.githubusercontent.com/87792676/129662930-0233638c-b6bd-46fc-b504-106f7d012e0d.gif)

**Comment by v-xianya** [comment]
Verified on the build main/20211016.1. Fixed.
