### ISSUE TITLE
There is no action 'Open Secondary Location' on the context menu of one new created blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4805]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210817.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account which has GRS enabled -> Blob Containers.
2. Create a new blob container -> Right click the blob container.
3. Check whether there is an action 'Open Secondary Location' on its the context menu.

## Expected Experience ##
There is an action 'Open Secondary Location' on its the context menu.
![image](https://user-images.githubusercontent.com/41351993/129671646-07422963-feb0-4981-8a3f-9a16d6e77e18.png)

## Actual Experience ##
There is no action 'Open Secondary Location' on its the context menu.
![image](https://user-images.githubusercontent.com/41351993/129671497-3830442f-7b13-4ea0-a78f-533c517194b4.png)

## Additional Context ##
1. This issue doesn't reproduce after manually refreshing the Blob Containers node.
2. This issue also reproduces for one pasted blob container.

**Comment by craxal** [comment]
@v-xianya Can you please provide more information about the paste scenario? Do both the source and destination accounts have GRS enabled?

**Comment by craxal** [comment]
@v-xianya Never mind! I found the problem and have a fix ready.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20210825.3. Fixed.
