### ISSUE TITLE
No red border shows on the Bypass field and no error message occurs when inputting an invalid pattern to the Bypass filed

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#4807]
**Storage Explorer Version:** 1.21.0-dev
**Build Number:** 20210817.3
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture:** ia32\x64
**How Found:** From running test cases
**Regression From:** Previous build(20210811.4)

## Steps to Reproduce ##

1. Launch Storage Explorer.
2. Click 'Edit -> Configure Proxy' -> Switch the source to 'Use app proxy settings'.
3. Input an invalid pattern ", localhost, 127.0.0.1" to the Bypass field.
4. Verify whether the error message occurs and a red border shows on the Bypass field.

## Actual Experience ##
No error message shows and no red border shows on the Bypass field.
![image](https://user-images.githubusercontent.com/87792676/129705796-1ca71cde-0153-4895-9bc7-80b09b513dce.png)

## Expected Experience ##
An error message occurs and a red border shows on the Bypass field.
![image](https://user-images.githubusercontent.com/87792676/129707325-1f753a8c-f035-4465-a513-21c6d7686519.png)

## More info ##
For Settings panel. Here is the behavior.

Repo Steps:

1. Go to 'Settings -> Application -> Proxy' -> Select 'Use app proxy settings'.
2. Input an invalid pattern ", localhost, 127.0.0.1" to the Bypass field.
3. Close the Settings panel then reopen it.

Actual: The Bypass filed is empty.

**Comment by craxal** [comment]
I'm removing the regression label, because this has not shipped in any release of Storage Explorer yet.
