### ISSUE TITLE
Suffix (secondary) in the address bar for a secondary ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4812]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210818.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one non-ADLS Gen2 storage account which has GRS enabled -> Blob Containers.
2. Right click one blob container -> Click 'Open Secondary Location'.
3. A secondary blob explorer tab is opened.
4. Observe the string in the address bar -> Check whether there is a suffix (secondary).

## Expected Experience ##
There is a suffix (secondary).

## Actual Experience ##
There is no suffix (secondary).
![image](https://user-images.githubusercontent.com/41351993/129843782-8f2e2fd9-0bd5-4fc6-b461-0729bb58b84f.png)

## Additional Context ##
This issue doesn't reproduces for one ADLS Gen2 blob container.

**Comment by craxal** [comment]
By design. "(secondary)" is just a label for nodes and tabs to help distinguish which endpoint is being used, but the actual container name, and thus the path, is the same as the primary.

**Comment by v-xianya** [comment]
@craxal Thank you for the clarification.
while for ADLS Gen2, the suffix (secondary) displays in the address bar. Could you help to take a look for this? 
We are going to re-open this issue for track.
![image](https://user-images.githubusercontent.com/41351993/129996220-7cc5a808-ca2c-43ba-93c3-f78df0d6d9a3.png)

**Comment by craxal** [comment]
This has the same root cause as #4813.
