### ISSUE TITLE
Fail to paste one secondary ADLS Gen2 blob/folder

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4813]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210818.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Open one blob container -> Upload one blob to it.
3. Right click the blob container -> Click 'Open Secondary Location'.
4. Copy the blob under the secondary blob explorer -> Paste it to another blob container.
5. Check whether succeed to paste.

## Expected Experience ##
Succeed to paste.

## Actual Experience ##
Fail to paste with the below error.

Error detail:
` "message": "\"failed to perform copy command due to error: cannot start job due to error: cannot list files due to reason -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.1-0.20210407023846`
![image](https://user-images.githubusercontent.com/41351993/129858215-d2df10ef-4616-4f76-8ac7-28a885149d94.png)

## Additional Context ##
1. Here is the AzCopy Command:
$env:AZCOPY_BUFFER_GB = "4";
$env:HTTPS_PROXY = "dummy.invalid";
$env:NO_PROXY = "*";
./azcopy.exe copy "https://arbaadls0817-secondary.blob.core.windows.net/ablob%20(secondary)/file2.txt?sv=2020-08-04&st=2021-08-18T08%3A10%3A24Z&se=2021-08-25T08%3A10%3A24Z&sr=c&sp=rl&sig=3Pt%2B8yyO8T3d5udLZcHUJsBxk7XSm1Sqr9f2Fk4JXao%3D" "https://arbaadls0817.blob.core.windows.net/blob1/file2.txt?sv=2020-08-04&se=2021-09-17T08%3A25%3A51Z&sr=c&sp=rwl&sig=8eyqBN75S1fNQyFX53ufiNZtazMWI650yZdZFOkUk44%3D" --overwrite=prompt --s2s-preserve-access-tier=false --recursive --trusted-microsoft-suffixes= --log-level=DEBUG;
$env:AZCOPY_BUFFER_GB = "";
$env:HTTPS_PROXY = "";
$env:NO_PROXY = "";

2. Succeed to copy & paste one secondary non-ADLS Gen2 blob.
![image](https://user-images.githubusercontent.com/41351993/129864374-b07582e1-dd56-47fa-bb33-dcaa46ee8aab.png)

**Comment by JasonYeMSFT** [comment]
Let's investigate if this is supported for Gen2.

**Comment by JasonYeMSFT** [comment]
We are passing the incorrect container name "realname (secondary)" so AzCopy constructs the incorrect endpoint.
