### ISSUE TITLE
The current queue is not selected on the 'Move Messages' dialog for one emulator queue

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#4815]
**Storage Explorer Version:** 1.21.0-dev
**Build Number:** 20210818.3
**Branch:** main
**Platform/OS:** Windows 10
**Architecture:** ia32\x64
**How Found:**  Exploratory testing
**Regression From:** Not a regression
## Steps to Reproduce ##

1. Install and start Azurite 3.14.0.
2. Launch Storage Explorer -> Expand 'Local & Attached -> Storage Accounts -> (Emulator - Default Ports)(Key)'.
3. Right click the 'Queues' node -> Create two queues.
4. Add a message to one queue -> Click 'Move Messages -> Move Selected...'.
4. Check whether the current queue is selected on the 'Move Messages' dialog.

## Expected Experience ##
The current queue is selected.
![image](https://user-images.githubusercontent.com/87792676/129878406-5ad0b719-a301-408f-a6b5-c60e60cbbf3b.png)

## Actual Experience ##
 The current queue is not selected.
![image](https://user-images.githubusercontent.com/87792676/129861559-4277e9d3-c542-4390-84e6-b092334c6a51.png)

**Comment by MRayermannMSFT** [comment]
I'll try to find a moment to look at this.

**Comment by MRayermannMSFT** [comment]
@v-kellyluo the expectation should be that the first search result/queue is selected. So yes there is/was a bug, but it wasn't quite what you thought. :) Anyways, I've merged a fix for the bug now.
