### ISSUE TITLE
Cannot load my Azure Subscription 

### ISSUE THREAD

**Issue by AlejandraLemmo** [microsoft/AzureStorageExplorer#4816]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.20.1

### Regression From

1.16

### Architecture

x64

### Storage Explorer Build Number

20210720.10

### Platform

Windows

### OS Version

WIndows 10

### Bug Description

Unable to retrieve child resources. Load the storage accounts related to my subscriptions

### Steps to Reproduce

launch Storage Explorer and my storages account cannot load. See the  erorr attached.

### Actual Experience

Cannot load  storage account related to my 2 Azure subscription. 

### Expected Experience

See my subscriotions

### Additional Context

Details:
{
  "name": "FetchError",
  "message": "request to http://127.0.0.1:10000/devstoreaccount1?include=metadata&comp=list failed, reason: connect ECONNREFUSED 127.0.0.1:10000",
  "stack": "FetchError: request to http://127.0.0.1:10000/devstoreaccount1?include=metadata&comp=list failed, reason: connect ECONNREFUSED 127.0.0.1:10000\n    at ClientRequest.<anonymous> (C:\\Users\\acz22\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1461:11)\n    at ClientRequest.emit (events.js:310:20)\n    at Socket.socketErrorListener (_http_client.js:426:9)\n    at Socket.emit (events.js:310:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)",
  "type": "system",
  "errno": "ECONNREFUSED",
  "code": "ECONNREFUSED"
}

**Comment by MRayermannMSFT** [comment]
@AlejandraLemmo the error indicates you are trying to use the storage emulator. The storage emulator is a program you run on your computer that imitates Azure Storage. Are you intending to do this? If so, you need to download and start the emulator yourself. Storage Explorer does not do that for you.
