### ISSUE TITLE
I can not connect to Storage Explorer

### ISSUE THREAD

**Issue by tidecoder** [microsoft/AzureStorageExplorer#4817]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.20.0

### Regression From

1.20.0

### Architecture

x64

### Platform

Windows

### Bug Description

{
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"self signed certificate in certificate chain\\\",\\n  \\\"stack\\\": \\\"Error: self signed certificate in certificate chain\\\\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1484:34)\\\\n    at TLSSocket.emit (events.js:310:20)\\\\n    at TLSSocket._finishInit (_tls_wrap.js:927:8)\\\\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:697:12)\\\",\\n  \\\"code\\\": \\\"SELF_SIGNED_CERT_IN_CHAIN\\\"\\n}\""
}

### Steps to Reproduce

launch Storage Explorer;
connect to my blob files;

### Actual Experience

i can not connect to my Storage Explorer

**Comment by MRayermannMSFT** [comment]
Hi, it sounds like you are having self signed certificates issues. We have to recommended paths forward for you:

1. Try using system proxy, which you can read about in our networking documentation: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network There are some limitations to it, so make sure you understand those.
2. Try setting certificates manually. You can read about this process in our troubleshooting guide for additional help with that: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#ssl-certificate-issues
If neither of those help feel free to come back here to let us know what happened.

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. If you still run into the issue, please open a new issue instead.
