### ISSUE TITLE
The context menu of new created queue is incomplete 

### ISSUE THREAD

**Issue by v-haiz** [Microsoft/AzureStorageExplorer#482]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180724.5
**Commit**: 3947e25b
**Regression From**: Previous release 1.3.1(20180711.1)

**Steps to Reproduce**:
1. Go to Subscription -> Storage Accounts.
2. Create a new queue.
3. Check whether the context menu of created queue is complete or not..

**Expected Experience**:
The context menu of created queue is complete.

**Actual Experience**:
The context menu of new created queue is incomplete.
![comparequeues](https://user-images.githubusercontent.com/37653604/43197163-d250e236-8ff9-11e8-8d6f-5241dbb0d721.PNG)
This issue also reproduces on table/file share.
This issue doesn't reproduce after refreshing Queues/Tables/File Shares node.

**Comment by craxal** [comment]
Related to #484 due to same root cause.
