### ISSUE TITLE
The active blob with the same name is selected under the snapshot view when managing snapshot for the soft-deleted blob 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4821]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210819.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload a blob.
3. Soft delete the blob -> Switch to the 'Active and soft deleted blobs' context.
4. Upload the same blob.
5. Right click the soft-deleted blob -> Click 'Manage Snapshots'.
6. Check whether the soft-deleted blob is selected under the snapshot view.

## Expected Experience ##
The soft-deleted blob is selected.

## Actual Experience ##
The active blob is selected.
![image](https://user-images.githubusercontent.com/41351993/130031516-1309c0ea-03de-44ff-ba63-9ace4d0b0a62.png)

**Comment by JasonYeMSFT** [comment]
This is expected. When switching between listing contexts (normal listing to snapshot, open a folder), we simply select the first item in the table.
