### ISSUE TITLE
An extra snapshot with strikethrough displays after promoting for one blob snapshot

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#483]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180724.5
**Commit**: 2605f1c9
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Expand one account and enable soft delete for 'Blob Containers'.
2. Open one blob container which contains one blob at least.
3. Create a snapshot for the blob -> Go to manage snapshot editor for the same blob then switch to 'Active and deleted blobs' -> Right click the blob snapshot and select 'Promote Snapshot' -> Refresh the editor.

#### Expected Experience: ####
No extra snapshot with strikethrough displays.

#### Actual Experience: ####
An extra snapshot with strikethrough displays.
![extra_snapshot_strikethrough](https://user-images.githubusercontent.com/34729022/43192279-ae51add2-8fec-11e8-9042-260206977c37.png)

**Comment by JasonYeMSFT** [comment]
This is by design of the platform. When a block gets overwritten by the same type of blob, a soft deleted snapshot will be automatically generated.

See the doc https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-soft-delete if you need more detailed information.

**Comment by v-xuanzh** [comment]
Hi @JasonYeMSFT ,Thanks for your updates.
Automatically generating a soft deleted snapshot is safe and convenient to protect user data.
But we think it is clearer if shows a log message in Activities log during the process of it. : )
