### ISSUE TITLE
The results are different between the Queue service and other three services when adding CORS Rule which Max Age is set to 0

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4834]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210820.5
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one non-ADLS Gen2 storage account.
2. Select the four services node separately.
3. Click 'Configure CORS Settings...' -> Add a CORS Rule with the Max Age is set to 0.
4. Check whether the results are the same.

## Expected Experience ##
The results are the same.

## Actual Experience ##
The results are not the same.

1. For services 'Blob/File Share/Table', display successful activity logs.
2. For service 'Queue', display a failed activity log.

![image](https://user-images.githubusercontent.com/41351993/130204916-cb5f93a4-2f85-4892-ba74-0fb0ba24c531.png)
Error details:
` "name": "Error",
  "message": "properties.Cors.MaxAgeInSeconds with value 0 must be of type number.",`

**Comment by craxal** [comment]
This is an error returned by the server and therefore nothing for us to do. We could ask the Storage team more about it, but this doesn't feel like a large discrepancy that many users will be concerned about.
