### ISSUE TITLE
See if we can do release pipeline on scale set pools to allow for || deployment

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#4837]

**Comment by JasonYeMSFT** [comment]
We should upgrade the agent pool running the release job since the current one will be deprecated in mid 2022.

**Comment by JasonYeMSFT** [comment]
Component release pipelines are moved to scale set agent pool running VS2019

**Comment by JasonYeMSFT** [comment]
The "Parallelism" config for the release pipeline might be the key to enable parallel deployments. Not going to test it in 1.23.0.

**Comment by JasonYeMSFT** [comment]
I set the maximum number of parallel deployments to 5. The config is at pre-deployment conditions.
