### ISSUE TITLE
unable to open an azure storage account CONTAINER via Azure Storage Explorer

### ISSUE THREAD

**Issue by BEBBEBBEB** [microsoft/AzureStorageExplorer#4839]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.20.1.

### Architecture

x64

### Platform

Windows

### OS Version

Window 10

### Bug Description

{"name":"Error","message":"unable to get local issuer certificate","stack":"Error: unable to get local issuer certificate\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1484:34)\n    at TLSSocket.emit (events.js:310:20)\n    at TLSSocket._finishInit (_tls_wrap.js:927:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:697:12)","code":"UNABLE_TO_GET_ISSUER_CERT_LOCALLY"}

### Steps to Reproduce

1. Launch Storage Explorer
2. Expand a blob container node

### Actual Experience

when trying to open a blob in Azure storage explorer, I had the error above.

**Comment by MRayermannMSFT** [comment]
Hi, it sounds like you are having self signed certificates issues. We have to recommended paths forward for you:

1. Try using system proxy, which you can read about in our networking documentation: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network There are some limitations to it, so make sure you understand those.
2. Try setting certificates manually. You can read about this process in our troubleshooting guide for additional help with that: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#ssl-certificate-issues
If neither of those help feel free to come back here to let us know what happened.

**Comment by BEBBEBBEB** [comment]
Hi,
Thank You very much.
In fact, it works when I use System proxy (I did this setup thanks to the documentation you mentioned above).
