### ISSUE TITLE
The new created queue is broken after adding it to Quick Access

### ISSUE THREAD

**Issue by v-haiz** [Microsoft/AzureStorageExplorer#484]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180724.5
**Commit**: 3947e25b
**Regression From**: Previous release 1.3.1(20180711.1)

**Steps to Reproduce**:
1. Go to Subscription -> Storage Accounts.
2. Create a new **queue**->Add the created queue to Quick Access.
3. Check the state of the queue under Quick Access node.

**Expected Experience**:
The queue is available under Quick Access node.

**Actual Experience**:
The queue is broken under Quick Access node. 
And the **new created blob container/file share/table** also is broken after adding it to Quick Access.

This issue doesn't reproduce after refreshing Blob Containers/File Shares/Tables node.

**Comment by craxal** [comment]
Related to #482 due to same root cause.
