### ISSUE TITLE
Unable to create folders in an Container via Storage Explorer using "ADLS Gen2 container or directory" connection method with SAS

### ISSUE THREAD

**Issue by Karthik-41** [microsoft/AzureStorageExplorer#4840]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.20.1

### Architecture

x64

### Storage Explorer Build Number

20210720.10

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Created an ADLS Gen2 container and connected with Azure Storage Explorer using SAS.

Tried to create folders but got failed and throwed below error.

`{
  "name": "FetchError",
  "message": "request to https://dlssdlea001.dfs.core.windows.net/dtccodes/20241?sv=2020-04-08&si=rule_drop_files_5years&sr=c&AzureSAS Token Redacted&resource=directory failed, reason: self signed certificate in certificate chain",
  "type": "system",
  "errno": "SELF_SIGNED_CERT_IN_CHAIN",
  "code": "SELF_SIGNED_CERT_IN_CHAIN",
  "stack": "FetchError: request to https://dlssdlea001.dfs.core.windows.net/dtccodes/20241?sv=2020-04-08&si=rule_drop_files_5years&sr=c&AzureSAS Token Redacted&resource=directory failed, reason: self signed certificate in certificate chain\n    at ClientRequest.<anonymous> (C:\\Users\\karthik.karuppusamy\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1461:11)\n    at ClientRequest.emit (events.js:310:20)\n    at TLSSocket.socketErrorListener (_http_client.js:426:9)\n    at TLSSocket.emit (events.js:310:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}`

### Steps to Reproduce

1. Create ADLS Gen2 and create an container under that.
2. Create SAS using Access policy.
3. Use SAS and connect with Container via Storage Explorer using "ADLS Gen2 container or directory" connection method.
4. Try creating folders under that.

### Actual Experience

<img width="701" alt="Screenshot-2021-08-23-185701" src="https://user-images.githubusercontent.com/43632004/130455397-d0f38fd8-d8fb-42f1-af9d-bf2cedc76c20.png">

**Comment by MRayermannMSFT** [comment]
Hi, it sounds like you are having self signed certificates issues. We have to recommended paths forward for you:

1. Try using system proxy, which you can read about in our networking documentation: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network There are some limitations to it, so make sure you understand those.
2. Try setting certificates manually. You can read about this process in our troubleshooting guide for additional help with that: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#ssl-certificate-issues
If neither of those help feel free to come back here to let us know what happaned.

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. If you still have this issue, please open a new issue instead.
