### ISSUE TITLE
The content in the address bar is different between two split tabs when the original blob explorer's address bar is in the edit mode

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4841]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210824.5
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Open one blob container -> Click the address bar to make it in edit mode.
3. Split the blob explorer tab.
4. Observe the address bar between the two tabs.
5. Check whether keep the same content.

## Expected Experience ##
Keep the same content.

## Actual Experience ##
The content is different.
![image](https://user-images.githubusercontent.com/41351993/130579970-3e309f9a-8485-4488-9573-429d5eceb22d.png)

## Additional Context ##
1. This issue doesn't reproduce for one ADLS Gen2 blob container.
For one ADLS Gen2 blob container, the address bar will exit the edit mode when splitting the tab.
![image](https://user-images.githubusercontent.com/41351993/130578167-93adc4e9-1ede-4dfa-bcb0-360ef922508e.png)

**Comment by JasonYeMSFT** [comment]
The split explorer is correctly inheriting the path from the left explorer. Due to blob explorers live in an isolated webview environment, it doesn't have the knowledge of the mouse event on elements outside the explorer and won't react by exiting the edit mode.

Overall speaking, I think this level of inconsistency is acceptable.

**Comment by craxal** [comment]
@JasonYeMSFT Agreed. Furthermore, it's important to note that when the address bar is in edit mode, the displayed text is just state for the control. It is not committed in any way, and therefore it does not accurately represent the actual path that the explorer is displaying.
