### ISSUE TITLE
The displayed font of ‘Delete Blobs' dialog is bigger than other dialogs

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#485]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180724.5
**Commit**: 2605f1c9
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Go to Subscriptions -> Storage Accounts.
2. Open one blob container then upload a blob to it.
3. Right click the uploaded blob then select 'Delete' -> Check the displayed font on the dialog.

#### Expected Experience: ####
The displayed font of the dialog as same as other dialogs.

#### Actual Experience: ####
The displayed font of the ‘Delete Blobs' dialog is bigger than other dialogs.
![font](https://user-images.githubusercontent.com/34729022/43192588-6630624a-8fed-11e8-891c-ea2f9e17fab1.png)

**Comment by JasonYeMSFT** [comment]
Thanks for catching it. Will fix it.
