### ISSUE TITLE
Refresh data table, then show the new change after create/edit/delete

### ISSUE THREAD

**Issue by t-leonkanMSFT** [microsoft/AzureStorageExplorer#4850]
Currently refresh the page will result reload the entire configuration store, and land on the first page after refresh completes. To provide a better experience, I want to propose a new behavior: 1) refresh and show the last page with new changes if any, 2) Highlight the new/modified row. Since it's extra work, we need to discuss if worth it and if it's feasible.

**Comment by JasonYeMSFT** [comment]
Covered by the new implementation.
