### ISSUE TITLE
The strange characters '%C5%5C?' display in the conflict Retry Azcopy dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4852]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210826.2
**Branch**: main
**Platform/OS**: Windows 10
**Architecture**: ia32
**How Found**: Ad-hoc testing
**Regression From**: Previous release (1.20.1)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Upload the same blob -> Apply 'Do not upload' in the conflict dialog.
4. Click 'Retry...' next to the activity log.
5. Check no strange characters display in the Retry Azcopy dialog.

## Expected Experience ##
No strange characters display in the Retry Azcopy dialog.

## Actual Experience ##
The strange characters '%5C%5C?' display in the Retry Azcopy dialog.
![image](https://user-images.githubusercontent.com/41351993/130919092-3f6555a3-adb3-4cf8-8b7a-a7ff890cc79c.png)

## Additional Context ##
This issue also reproduces for download conflict Retry Azcopy dialog.
![image](https://user-images.githubusercontent.com/41351993/130919238-01e0954c-6713-4a23-bad3-18966ef3c51b.png)

**Comment by MRayermannMSFT** [comment]
AzCopy 10.12.1 merged into main which should resolve this issue.

**Comment by v-xianya** [comment]
Fixed on the rel/1.21.0 build 20210903.4.
