### ISSUE TITLE
The break lease activity logs display for non-leased blobs when breaking lease for multi blobs that contain non-leased blobs

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4853]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210826.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload two blobs.
3. Acquire lease for one blob -> Select the two blobs.
4. Break lease -> Observe only display break lease activity log for the leased blob.

## Expected Experience ##
Only display break lease activity log for the leased blob.

## Actual Experience ##
Display break lease activity logs for the two blobs.

## Additional Context ##
This issue also reproduces when acquiring lease several blobs which contains leased blob.

**Comment by MRayermannMSFT** [comment]
Hi, it sounds like you are having self signed certificates issues. We have to recommended paths forward for you:

1. Try using system proxy, which you can read about in our networking documentation: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network There are some limitations to it, so make sure you understand those.
2. Try setting certificates manually. You can read about this process in our troubleshooting guide for additional help with that: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#ssl-certificate-issues
If neither of those help feel free to come back here to let us know what happaned.

**Comment by MRayermannMSFT** [comment]
This is by design.

**Comment by v-xianya** [comment]
@MRayermannMSFT I checked this in Portal, It just displays the number of the blobs that actually Acquire/Break lease.
