### ISSUE TITLE
It takes about 16 seconds to pop up the 'Delete' dialog in a SAS attached ADLS Gen2 folder

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4855]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210827.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 18.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: From running test cases
**Regression From**: Previous release (1.20.1)

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one non-empty folder.
3. Right click the folder -> Click 'Get Shared Access signature...' -> Select all permissions -> Create and copy the SAS URL.
4. Attach the ADLS Gen2 folder via the copied SAS URL.
5. The SAS attached folder auto opened after successfully attaching.
6. Click 'Delete' on the toolbar of the attached folder.
7. Check whether the 'Delete' dialog pops up immediately.

## Expected Experience ##
The 'Delete' dialog pops up immediately.

## Actual Experience ##
It takes about 16 seconds to pop up the 'Delete' dialog.

**Comment by JasonYeMSFT** [comment]
I have merged a workaround to the rel branch. We will check for the credential type and only peek the soft delete policy if not using a service level SAS.

**Comment by v-xianya** [comment]
@JasonYeMSFT 
Verified this issue on the rel/1.21.0 build 20210831.4. Fixed.
