### ISSUE TITLE
Unable to get local issuer certificate

### ISSUE THREAD

**Issue by guillaumecourtonne** [microsoft/AzureStorageExplorer#4856]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.20.1

### Architecture

x64

### Storage Explorer Build Number

20210720.10

### Platform

Windows

### OS Version

Windows 10

### Bug Description

When i want to explore Table, I Have this error.

For information, I have no proxy.

Impossible de récupérer les ressources enfants.

Détails :
unable to get local issuer certificate

### Steps to Reproduce

Open Storage Explorer and deploy Table

### Actual Experience

--

**Comment by MRayermannMSFT** [comment]
Hi, it sounds like you are having self signed certificates issues. We have to recommended paths forward for you:

1. Try using system proxy, which you can read about in our networking documentation: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network There are some limitations to it, so make sure you understand those.
2. Try setting certificates manually. You can read about this process in our troubleshooting guide for additional help with that: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#ssl-certificate-issues
If neither of those help feel free to come back here to let us know what happaned.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you still need help please at least try the above suggestions. If that does not help we recommend you either:

- Open a support ticket via the Azure Portal
- Open a new issue here

Thanks.
