### ISSUE TITLE
Queues Explorer - Can't copy / export multiple message from queue

### ISSUE THREAD

**Issue by sharonbl** [microsoft/AzureStorageExplorer#4857]
I will be a great option to be able to copy or export multiple messages for a queue.
Currently one can multiple select messages in queue, but there is no option to copy / export them.

**Comment by MRayermannMSFT** [comment]
Similar to #3831

@sharonbi could you tell us more about what you would expect for this feature:

- In what file format would queue messages be exported to?
- When you say "copy" do you mean something like:
  1. select message/s
  2. click copy
  3. go to another queue
  4. click paste
  5. messages in first queue are left there, but now in the second queue there are messages with the same content and whose expiration time is the same (the length of time that is).

**Comment by sharonbl** [comment]
@MRayermannMSFT Thanks for your quick response.

I meant much simpler copy -> copy to clipboard or export to file as text.
During my day to day work I need messages from queues for other usages. Currently I double click on a single message and copy its text.
It will be great to be able to select multiple messages and ctrl+c / right-click-copy / right-click-export-to-file and get all the selected messages.
Since a message contains more fields, other than the message text, I guess export can think of a JSON format for each message, containing all the fields.

I hope it makes the request more clear.
Thank you in advance!

**Comment by MRayermannMSFT** [comment]
Let's just focus on copying the message content for now. Let's do similar to blob/file where we have "Copy URL", so we can add "Copy Message Text". Thinking appending "Text" might be good to make it clear this isn't copying the literal azure queue message item.

**Comment by MRayermannMSFT** [comment]
This will be included in 1.32.

**Comment by richardMSFT** [comment]
With 1.32 you will be able to select and copy texts from multiple queue messages in the clipboard. This works through the context menu action or using the keyboard shortcut Ctrl/Cmd+C.

![Screenshot 2023-10-09 at 4 12 54 PM](https://github.com/microsoft/AzureStorageExplorer/assets/111301956/ec462e6d-72a1-46a3-9194-cb0b2f8aab14)
