### ISSUE TITLE
Fail to delete one blob which has deleted snapshots with soft delete disabled

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#486]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180724.5
**Commit**: 2605f1c9
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Expand a storage account and **enable** soft delete for 'Blob Containers'.
2. Open one blob container which contains one blob at least.
3. Create a snapshot for the blob -> Go to the manage snapshots editor of the blob then delete the created snapshot -> Swith to 'Active and deleted blobs' and make sure the deleted snapshot displays with strikethrough.
4. **Disable** soft delete for 'Blob Containers' under the same account.
5. Try to delete the same blob in step3.

#### Expected Experience: ####
The blob can be deleted successfully.

#### Actual Experience: ####
Fail to delete the blob with the below error message.
![error](https://user-images.githubusercontent.com/34729022/43193440-89387474-8fef-11e8-9edb-2248cbbaa7eb.png)

**Comment by JasonYeMSFT** [comment]
This is by design of the platform. We are having consistent behavior with the Portal and there is nothing we can do to change it.
