### ISSUE TITLE
A conflict dialog pops up when uploading one folder to a file share

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4861]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210831.4
**Branch**: rel/1.21.0
**Platform/OS**: Windows 10/Linux Ubuntu 18.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: From running test cases
**Regression From**: Previous release (1.20.1)

## Bug Descriptions ##
A conflict dialog pops up when uploading a folder to one file share or cloning/pasting one file share which contains folders.

## Steps to Reproduce ##
1. Expand a storage account -> File Shares.
2. Create a file share -> Upload one folder to the file share.
3. Check no conflict dialog pops up.

## Expected Experience ##
No conflict dialog pops up.

## Actual Experience ##
A conflict dialog pops up.
![image](https://user-images.githubusercontent.com/41351993/131463650-b4b4431d-ecf0-4b58-886f-d82ed69241d7.png)

**Comment by MRayermannMSFT** [comment]
AzCopy 10.12.1 merged into main which should resolve this issue.

**Comment by v-xianya** [comment]
Fixed on the rel/1.21.0 build 20210903.4.
