### ISSUE TITLE
Proxy bypass text box in proxy dialog needs prompt/some extra validation

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#4864]
Text box should have a prompt saying what the correct format is, especially given that the format is different from the settings page. Also, let's build in validation that helps people avoid doing list formats they may expect to be correct, like ; or \n separated values.

**Comment by craxal** [comment]
@MRayermannMSFT Semicolons are already permitted in the dialog, so we just need to add newline characters.
