### ISSUE TITLE
It would be better to remove the string 'If you are looking for deleted blobs, try switching to the "Deleted only" context' when the ADLS Gen2 soft delete setting is disabled

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4867]
**Storage Explorer Version**: 1.21.0
**Build Number**: 20210901.7
**Branch**: rel/1.21.0
**Platform/OS**: Windows 10/Linux Ubuntu 18.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Open 'Settings -> Services'.
2. Check the setting 'Enable ADLS Gen2 soft delete (Preview)' is disabled (if not then disable the setting and restart Storage Explorer).
3. Expand one ADLS Gen2 storage account -> Blob Containers.
4. Create a blob container -> Observe the description on its editor.
5. Check the string 'If you are looking for deleted blobs, try switching to the "Deleted only" context' has been removed.

## Expected Experience ##
The string 'If you are looking for deleted blobs, try switching to the "Deleted only" context' has been removed.

## Actual Experience ##
The string 'If you are looking for deleted blobs, try switching to the "Deleted only" context' displays.
![image](https://user-images.githubusercontent.com/41351993/131635259-04f2c1a9-3ba7-4064-8cd2-91e460ea1fd4.png)

**Comment by JasonYeMSFT** [comment]
It is kinda hard to adjust this string based on the configuration value. And the impact is low if the user isn't using soft delete so won't fix for now.
