### ISSUE TITLE
The blob version which has the current version displays under the 'Active blobs and blobs without current version' context view after switching to 'Flat' mode

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4869]
**Storage Explorer Version**: 1.21.0
**Build Number**: 20210901.7
**Branch**: rel/1.21.0
**Platform/OS**: Windows 10/Linux Ubuntu 18.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one non-ADLS Gen2 storage account -> Blob Containers.(Make sure the blob versioning is enabled)
2. Create a blob container (Make sure the list mode is 'Hierarchical')-> Upload one blob.
3. Right click the blob -> Click 'Properties' -> Modify its metadata to create a blob version for the blob.
4. Switch to 'Active blobs and blobs without current version' context view -> Only display the blob.
5. Open the view options panel -> Set the list mode to 'Flat'.
6. Check whether only display the blob. 

## Expected Experience ##
Only display the blob. 

## Actual Experience ##
The blob version also displays.
![image](https://user-images.githubusercontent.com/41351993/131644318-e5e4864f-d7ec-4c9a-a2a8-bc7b0a7b6339.png)

## Additional Context ##
This issue also reproduces under the 'All blobs and blobs without current version' context view.

**Comment by JasonYeMSFT** [comment]
@v-xianya We have merged a fix to suppress the blob items under "flat" mode and the "Active blobs and blobs without current version"/"All blobs and blobs without current version" so that they only show their latest version, if there are multiple ones. Please help us verify the fix and please try to see if anything else related to listing is accidentally changed.

**Comment by v-xianya** [comment]
@JasonYeMSFT Got it. thank you for the fix.

This issue has been fixed 20210905.1 and we will do some additional testing around this.
