### ISSUE TITLE
The property of 'Soft Delete' still displays as Disabled after enabling it from 'Delete Blob' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#487]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180724.5
**Commit**: 2605f1c9
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Expand one account and make sure the soft delete is disabled for 'Blob Containers'.
2. Open one blob container -> Choose a blob then click 'Delete' -> Click 'Enable Soft Delete' button on the dialog.
3. Check the property of 'Soft Delete' in Properties panel after enabling soft delete successfully.

#### Expected Experience: ####
The property of the 'Soft Delete' displays as 'Enabled'

#### Actual Experience: ####
The property of the 'Soft Delete' still displays as 'Disabled'.

This issue also reproduces after changing the soft delete policy from the attached account.

**Comment by JasonYeMSFT** [comment]
Our code currently doesn't have the ability to update the properties panel from the editor. It won't be fixed for 1.4.0. We will investigate how to do it.

**Comment by v-xianya** [comment]
The property of the 'Soft Delete' displays as 'Enabled' after **refreshing** the Blob Containers node.

**Comment by MRayermannMSFT** [comment]
Won't fix per future feature work disrupting soft delete.
