### ISSUE TITLE
It takes at least 34 seconds to pop up the warning dialog when reloading/quitting/closing the Storage Explorer if there is an unfinished activity

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#4870]
**Storage Explorer Version:** 1.21.0
**Build Number:** 20210901.7
**Branch:** rel/1.21.0
**Platform/OS:** Windows 10
**Architecture:** ia32
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Click 'Upload -> Upload Folder' -> Select a folder (I used the folder 'StorageExplorer-win32-ia32' which is extracted from the artifact 'StorageExplorer-win32-ia32.zip').
3. Make sure the upload activity is in progress.
4. Reload/Quit/Close the Storage Explorer.
5. Check whether the warning dialog pops up immediately.

## Expected Experience ##
The warning dialog pops up immediately.

## Actual Experience ##
It takes at least 34 seconds to pop up the warning dialog.

## Additional Context ##
This issue doesn't reproduce on Linux & MacOS.

**Comment by MRayermannMSFT** [comment]
@v-kellyluo can you please:
1. enable `debug` level logging by setting the STG_EX_LOG_LEVEL environment variable
2. reproduce the issue
3. share the logs with me

Thanks!

**Comment by MRayermannMSFT** [comment]
Please do this with at least build 20210902.4 or newer

**Comment by v-kellyluo** [comment]
Hi @MRayermannMSFT,

1. Verified this issue on the build 20210902.4, it reproduces.
2. I set the environment variable STG_EX_LOG_LEVEL to debug, here are the logs.
[2021-09-01_202446.zip](https://github.com/microsoft/AzureStorageExplorer/files/7096147/2021-09-01_202446.zip)

**Comment by MRayermannMSFT** [comment]
@v-kellyluo can you:
- tell me the specs of the machine/VM you are using
- try using build 20210902.13 and tell me how the speed of the dialog appearing compares to previous builds

Thanks!

**Comment by v-kellyluo** [comment]
Hi @MRayermannMSFT,

1. Verified this issue on the build 20210902.4, it takes more than 1 minute to pop up the warning dialog.
    Verified this issue on the build 20210902.13, it doesn't repo, it takes about 1 second to pop up the warning dialog.
2. Here is the specs of the machine I used
![image](https://user-images.githubusercontent.com/87792676/131955874-cb1bca90-4ae1-4957-80df-da83867276c2.png)

**Comment by MRayermannMSFT** [comment]
@v-kellyluo thank you for the information. I have merged the changes from that build into our rel brach. So this issue should now be resolved in our rel builds.

**Comment by v-kellyluo** [comment]
Fixed on the rel/1.21.0 build 20210905.1.
