### ISSUE TITLE
Lease status of secondary node is "borrowed" from primary when first created

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#4872]
### Repro Steps
1. Expand a storage account node with a secondary location.
2. Expand Blob Containers, right-click a blob container node, and acquire a lease for it. "(Leased)" should appear.
3. Right-click the same blob container node and open the secondary endpoint.

The secondary endpoint will also have "(Leased)" next to its name.

**Comment by MRayermannMSFT** [comment]
Check with service side peeps on what they think is a good expectation for this. It might make sense to show leased if the primary is leased as well? But if we do that, we should make sure it goes away if the primary's lease is broken. If that's too complex to do, then probably no big deal to not leased then unless the expectation to show it is really strong.

**Comment by craxal** [comment]
I'm not even sure if it makes sense to lease the secondary at all, because the secondary is read-only. I'll have to double-check with the platform.

**Comment by craxal** [comment]
It looks like, regardless of which location is queries for blob container properties, the lease state/status is the same between the primary and the secondary location. So this is by design.
