### ISSUE TITLE
There is an extra scroll bar in the CORS Settings dialog under the 'High Contrast - White' theme

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4878]
**Storage Explorer Version**: 1.21.0
**Build Number**: 20210902.4
**Branch**: rel/1.21.0
**Platform/OS**: Windows 10/Linux Ubuntu 18.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account.
2. Right click on the Blob Containers node -> Click 'Configure CORS Settings...'.
3. Check there is no extra scroll bar in the CORS Settings dialog.

## Expected Experience ##
There is no extra scroll bar because the size of the edit box is dynamically adjusted according to the number number of CORS rules.

## Actual Experience ##
There is an extra scroll bar.

![image](https://user-images.githubusercontent.com/41351993/131810773-0aaec2d6-f730-48b0-9753-b6d7b5739a2f.png)

## Additional Context ##
1. This issue also reproduces on the 'Dark & High Contrast - Black' themes.
2. Related issue: [2344](https://github.com/microsoft/AzureStorageExplorer/issues/2344).

**Comment by MRayermannMSFT** [comment]
Won't fix for now.
