### ISSUE TITLE
All the deleted snapshots display active after undeleting one blob snapshot

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#488]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180724.5
**Commit**: 2605f1c9
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Expand a storage account and enable soft delete for 'Blob Containers'.
2. Open one blob container which contains a blob at least.
3. Create multiple snapshots for the blob -> Go to manage snapshots editor for the blob -> Delete all the created snapshots.
4. Switch to 'Active and deleted blobs' -> Select one deleted blob snapshot then undelete it -> Refresh the editor.

#### Expected Experience: ####
Only the undeleted snapshot displays active.

#### Actual Experience: ####
All the deleted snapshots display active.
![active](https://user-images.githubusercontent.com/34729022/43194969-3ca5c41e-8ff3-11e8-8834-a87cad0d6010.png)

**Comment by JasonYeMSFT** [comment]
Thanks for catching it. Will fix it.

**Comment by v-xuanzh** [comment]
This issue also reproduces on latest rel/1.4.0_20180726.4. So reopened this issue.

**Comment by JasonYeMSFT** [comment]
This is the platform's behavior on undeleting blob snapshots. Therefore, the UI reaction has been changed so that all snapshots will be active after undelete is done and no refreshing is needed.
