### ISSUE TITLE
The 'Yes' button is not selected on the popped up dialog when deleting a file for one attached file share with permissions 'Read, List, Delete'

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#4881]
**Storage Explorer Version:** 1.21.0
**Build Number:** 20210903.4
**Branch:** rel/1.21.0
**Platform/OS:** Windows 10/MacOS Big Sur 11.4
**Architecture:** ia32\x64
**How Found:** From running test case
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> File Shares.
2. Select one file share -> Upload one file.
3. Right click the  file share-> Click 'Get Shared Access Signature...'.
4. Select permissions 'Read, List, Delete' -> Create and copy the SAS URL.
5. Open the connect dialog -> Attach the file share via the copied SAS URL.
6. Switch to the attached file share-> Delete the file.
7. Click the 'Yes' button on the 'Delete Files' dialog.
8. Check whether the 'Yes' button is selected on the popped up dialog.

## Expected Experience ##
The 'Yes' button is selected.

## Actual Experience ##
The 'Yes' button is not selected.
![image](https://user-images.githubusercontent.com/87792676/131984231-3b818f94-fdc3-48a5-826b-4253eb666021.png)

## Additional Context ##
This issue doesn't reproduce on Linux.
![image](https://user-images.githubusercontent.com/87792676/131984378-cec5ad2c-01a5-40c4-a284-879451d9c5a7.png)

**Comment by craxal** [comment]
Could be the same root cause as #4661.

**Comment by craxal** [comment]
Looks like a default button wasn't actually specified.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20211112.4. Fixed.
