### ISSUE TITLE
Toolbar context menus open in the wrong place

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#4883]
When selecting a toolbar item with context menu options, the context menu opens far below and to the right of where it should be. The relative offset between toolbar items appears to be correct, though.

![image](https://user-images.githubusercontent.com/3473026/132051456-8cb41b88-2620-435c-b706-14daa4bea83f.png)

**Comment by MRayermannMSFT** [comment]
Looks like this is probably related to the dialog reuse change. @craxal please try to repro this again after you revert that change. If it still reproduces then you can send back to me and I'll continue investigating.

**Comment by MRayermannMSFT** [comment]
Cannot repro against 1.22
