### ISSUE TITLE
Fail to enable soft delete for local account

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#489]
**Platform/OS Version**: Windows 10
**Architecture**: ia32/x64
**Build Number**: 20180724.5
**Commit**: 2605f1c9
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Make sure the Stoeage Emulator installed and started.
2. Open 'Connect' dialog then choose 'Attach to a local emulator' ->' Connect'.
3. Expand **(Local & Attached) -> Storage Accounts -> The attached local emulator** -> Try to enable soft delete for 'Blob Containers'.

#### Expected Experience: ####
'Soft Delete' can be enabled successfully.

#### Actual Experience: ####
Fail to enable soft delete for local account.
![localemulator](https://user-images.githubusercontent.com/34729022/43195330-4c82e366-8ff4-11e8-9353-5e90146c1cb4.png)

**Comment by JasonYeMSFT** [comment]
Local emulator doesn't support Soft Delete. It is fine to have the error message in Activity Log.
