### ISSUE TITLE
Azure Storage Explorer Troubleshooting: "unable to retrieve child resources” or “The request action could not be completed

### ISSUE THREAD

**Issue by moinshaikh888** [microsoft/AzureStorageExplorer#4890]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.20.1

### Architecture

x64

### Platform

All

### OS Version

Windows 10

### Bug Description

},
"clientRequestId": {
"serializedName": "x-ms-client-request-id",
"type": {
"name": "String"
}
},
"errorCode": {
"serializedName": "x-ms-error-code",
"type": {
"name": "String"
}
}
}
}
},
"StaticWebsite": {
"serializedName": "StaticWebsite",
"type": {
"name": "Composite",
"className": "StaticWebsite",
"modelProperties": {
"enabled": {
"xmlName": "Enabled",
"required": true,
"serializedName": "Enabled",
"type": {
"name": "Boolean"
}
},
"indexDocument": {
"xmlName": "IndexDocument",
"serializedName": "IndexDocument",
"type": {
"name": "String"
}
},
"errorDocument404Path": {
"xmlName": "ErrorDocument404Path",
"serializedName": "ErrorDocument404Path",
"type": {
"name": "String"
}
},
"defaultIndexDocumentPath": {
"xmlName": "DefaultIndexDocumentPath",
"serializedName": "DefaultIndexDocumentPath",
"type": {
"name": "String"
}
}
}
}
},
"StorageError": {
"serializedName": "StorageError",
"type": {
"name": "Composite",
"className": "StorageError",
"modelProperties": {
"message": {
"xmlName": "Message",
"serializedName": "Message",
"type": {
"name": "String"
}
},
"code": {
"xmlName": "Code",
"serializedName": "Code",
"type": {
"name": "String"
}
}
}
}
},
"UserDelegationKey": {
"serializedName": "UserDelegationKey",
"type": {
"name": "Composite",
"className": "UserDelegationKey",
"modelProperties": {
"signedObjectId": {
"xmlName": "SignedOid",
"required": true,
"serializedName": "SignedOid",
"type": {
"name": "String"
}
},
"signedTenantId": {
"xmlName": "SignedTid",
"required": true,
"serializedName": "SignedTid",
"type": {
"name": "String"
}
},
"signedStartsOn": {
"xmlName": "SignedStart",
"required": true,
"serializedName": "SignedStart",
"type": {
"name": "String"
}
},
"signedExpiresOn": {
"xmlName": "SignedExpiry",
"required": true,
"serializedName": "SignedExpiry",
"type": {
"name": "String"
}
},
"signedService": {
"xmlName": "SignedService",
"required": true,
"serializedName": "SignedService",
"type": {
"name": "String"
}
},
"signedVersion": {
"xmlName": "SignedVersion",
"required": true,
"serializedName": "SignedVersion",
"type": {
"name": "String"
}
},
"value": {
"xmlName": "Value",
"required": true,
"serializedName": "Value",
"type": {
"name": "String"
}
}
}
}
}
},
"isXML": true
}
}
}
}

### Steps to Reproduce

1.launch storage account
2. expanding blob getting ab error child idem can be retrieved

### Actual Experience

1.launch storage account
2. expanding blob getting ab error child idem can be retrieved

**Comment by moinshaikh888** [comment]
![image](https://user-images.githubusercontent.com/90199716/132227444-ba7bc5ec-8b6f-4aa9-b122-c2bd2e90ef23.png)

**Comment by munish16** [comment]
I am facing the exact same issue:

![image](https://user-images.githubusercontent.com/14263081/132250539-06d1ef2a-d36f-4a7b-b405-c54cd9bd8701.png)

**Comment by Takahatamo** [comment]
Same error. Please help I need to have this thing working so that I can finish my assignment:

![Screenshot 2021-09-08 211815](https://user-images.githubusercontent.com/71511640/132606321-05e71921-3169-4efc-adcc-f568d1792d0c.png)

**Comment by jinglouMSFT** [comment]
@Takahatamo The error message in your case indicated that you don't have the permission to perform the operation. What were you trying to do and what permissions you have?

**Comment by moinshaikh888** [comment]
Hi ,
I have owner permission on that storage account , Still do I need to assignee any blob level permission e.g storage blob contributor ?

From: jinglouMSFT ***@***.***>
Sent: Thursday, September 9, 2021 11:53 PM
To: microsoft/AzureStorageExplorer ***@***.***>
Cc: moinshaikh888 ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/AzureStorageExplorer] Azure Storage Explorer Troubleshooting: "unable to retrieve child resources” or “The request action could not be completed (#4890)

This message is from an EXTERNAL SENDER - be CAUTIOUS, particularly with links and attachments.
________________________________


@Takahatamo<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Takahatamo&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=v2LTsQV-rV3CSsHGwOZbd9O-W1-LbsyMw88jWDNKJgg&m=fvqRIcWJUHDE40gBmgwPgR3AO2gd4uKTkPXjjZMykZM&s=9NCGEFX5vogEwCnI0pOk6p4NEB1m06sAXI1cmhLvMKc&e=> The error message in your case indicated that you don't have the permission to perform the operation. What were you trying to do and what permissions you have?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_microsoft_AzureStorageExplorer_issues_4890-23issuecomment-2D916333740&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=v2LTsQV-rV3CSsHGwOZbd9O-W1-LbsyMw88jWDNKJgg&m=fvqRIcWJUHDE40gBmgwPgR3AO2gd4uKTkPXjjZMykZM&s=vMZoapKkBYx_2huL7NU3p2efWJxScd-o6Sc6izIQi_c&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AVQFNJHV2TV2UBXILORLDWLUBD3PTANCNFSM5DQQCBSQ&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=v2LTsQV-rV3CSsHGwOZbd9O-W1-LbsyMw88jWDNKJgg&m=fvqRIcWJUHDE40gBmgwPgR3AO2gd4uKTkPXjjZMykZM&s=vs2WQRWGXT9TGSNEoBhUCp2RXzgQHa81Wi4U34Z3aIQ&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=v2LTsQV-rV3CSsHGwOZbd9O-W1-LbsyMw88jWDNKJgg&m=fvqRIcWJUHDE40gBmgwPgR3AO2gd4uKTkPXjjZMykZM&s=q7iwpJMCascYnsyNW-XbZkitSA9EQ9SfiDh0HXwlgvY&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=v2LTsQV-rV3CSsHGwOZbd9O-W1-LbsyMw88jWDNKJgg&m=fvqRIcWJUHDE40gBmgwPgR3AO2gd4uKTkPXjjZMykZM&s=XrcJCTcYMqlx5fw0iC3TArwCyDmDJ3PXMD8KmBoB4jM&e=>.

________________________________

This message is for the designated recipient only and may contain privileged, proprietary, or otherwise confidential information. If you have received it in error, please notify the sender immediately and delete the original. Any other use of the e-mail by you is prohibited. Where allowed by local law, electronic communications with Accenture and its affiliates, including e-mail and instant messaging (including content), may be scanned by our systems for the purposes of information security and assessment of internal compliance with Accenture policy. Your privacy is important to us. Accenture uses your personal data only in compliance with data protection laws. For further information on how Accenture processes your personal data, please see our privacy statement at https://www.accenture.com/us-en/privacy-policy.
______________________________________________________________________________________

www.accenture.com

**Comment by MRayermannMSFT** [comment]
@moinshaikh888 how are you accessing your resources? It looks like maybe you attached with a User delegated SAS?

@munish16 for your screenshot, it looks like you're trying to access your emulator. For that, please make sure your emulator is installed and is running. Storage Explorer neither ships with an emulator nor does it start any emulators for you.

**Comment by Takahatamo** [comment]
Hello I forgot to send that the problem was resolve I just had to remove the resource and fix it up a bit when I set it up
________________________________

**Comment by moinshaikh888** [comment]
Hi @ Takahatamo
Could you please specify bit more what resources you removed and what steps you followed that will be really helpful and appreciated.

From: Takahatamo ***@***.***>
Sent: Friday, September 10, 2021 11:06 PM
To: microsoft/AzureStorageExplorer ***@***.***>
Cc: moinshaikh888 ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [microsoft/AzureStorageExplorer] Azure Storage Explorer Troubleshooting: "unable to retrieve child resources” or “The request action could not be completed (#4890)

This message is from an EXTERNAL SENDER - be CAUTIOUS, particularly with links and attachments.
________________________________

Hello I forgot to send that the problem was resolve I just had to remove the resource and fix it up a bit when I set it up
________________________________

**Comment by JasonYeMSFT** [comment]
@moinshaikh888 Reading through your error detail, I noticed that the url looks weird "https://wabcf.blob.blob.core.windows.net/?include=metadata&comp=list" since it has two .blob. in the endpoint. Could you double check the url/endpoint you used to connect to your resource and see if there is a typo there?

**Comment by moinshaikh888** [comment]
> I am facing the exact same issue:
> 
> ![image](https://user-images.githubusercontent.com/14263081/132250539-06d1ef2a-d36f-4a7b-b405-c54cd9bd8701.png)

I have managed to solve this issue please check your network configuration , also confirm that its normal storage account or ADLS v2 storage account accordingly i will share steps and CMD commands.

**Comment by moinshaikh888** [comment]
> @moinshaikh888 Reading through your error detail, I noticed that the url looks weird "https://wabcf.blob.blob.core.windows.net/?include=metadata&comp=list" since it has two .blob. in the endpoint. Could you double check the url/endpoint you used to connect to your resource and see if there is a typo there?

Hi Thanks for your reply it was typo error here, i have solved tis issue by modifying network setting in Azure.
