### ISSUE TITLE
Don't open a new taskbar icon when the app is already pinned to the taskbar

### ISSUE THREAD

**Issue by LarsKemmann** [microsoft/AzureStorageExplorer#4891]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I get frustrated when opening Storage Explorer from the taskbar, where I have it pinned, and it opens as a new icon off to the side rather than using the existing pinned icon.

### Desired Solution

Use the existing pinned icon for the running application instance.

### Alternatives and Workarounds

There is no workaround or alternative for the end user.

### Additional Context

https://pasteboard.co/KjobLRZ.png

**Comment by MRayermannMSFT** [comment]
@LarsKemmann can you try:

1. Close Storage Explorer
2. Unpin Storage Explorer from the task bar
3. Restart your computer
3. Go to your install folder and launch Storage Explorer
4. After it launches, pin that instance to the taskbar
5. Close and reopen, see if the issue reproduces?

**Comment by LarsKemmann** [comment]
Thank you @MRayermannMSFT - that worked!
