### ISSUE TITLE
unable to see anything on the whole page and cannot connect to any account

### ISSUE THREAD

**Issue by ruccccc012** [microsoft/AzureStorageExplorer#4892]
![image](https://user-images.githubusercontent.com/46606209/132274549-e6cb7fc4-4679-4993-a407-3554096236ef.png)
Nothing shows up after installing the software. I tried reinstallation and restart the laptop, still nothing.

**Comment by v-xianya** [comment]
@ruccccc012 
Can you try to delete Storage Explorer data under the path 
C:\Users\<username>\AppData\Roaming? then start Storage Explorer. see if the issue can be resolved.

**Comment by ruccccc012** [comment]
> @ruccccc012
> Can you try to delete Storage Explorer data under the path
> C:\Users<username>\AppData\Roaming? then start Storage Explorer. see if the issue can be resolved.

![Uploading image.png…]()         
Still nothing on the left side.

**Comment by ruccccc012** [comment]
@v-xianya  thanks, but still nothing shows up on the left side...

**Comment by amjad-Alhusseini** [comment]
@ruccccc012 as a workaround you can try running the Storage Explorer as Administrator, just right click then "Run as Administrator", this should fix the issue.
Consider it as a workaround till the engineering team look up for a solution

**Comment by sk185606** [comment]
Hello Team,

I am also not able to see anything in the explorer version 1.20.1 but the workaround seems to do the job. Running it as administrator show me everything.

Thank you @amjad-Alhusseini

**Comment by ruccccc012** [comment]
@amjad-Alhusseini  this workaround didn't solve my issue, I think I might start to consider whether it's because my computer setting

**Comment by MRayermannMSFT** [comment]
Possible duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/4768 ?

**Comment by MRayermannMSFT** [comment]
@ruccccc012  I'm going to close this in favor of #4768. Please go read that thread for what we have identified as a workaround. We will likely ship this workaround in 1.23. Thanks!
