### ISSUE TITLE
A failed activity log displays when executing "Undelete" for active folders under one Azure AD attached HNS folder

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4893]
**Storage Explorer Version**: 1.21.0
**Build Number**: 20210905.1
**Branch**: rel/1.21.0
**Platform/OS**: Windows 10/Linux Ubuntu 18.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: From running test case
**Regression From**: Not a regression

## Bug Descriptions ##
A failed activity log displays when executing "Undelete" for active folders under one attached HNS folder (Both SAS attached with full permissions and Azure AD attached).

## Steps to Reproduce ##
1. Make sure the setting "Enable ADLS Gen2 soft delete (Preview)" is enabled.
2. Expand one ADLS Gen2 storage account -> Blob Containers.
3. Create a blob container -> Add the rbac role 'Storage Blob Data Contributor' then assign to one azure account.
4. Create a folder in the blob container -> Create a subfolder in the folder -> Attach the parent folder via Azure AD.
5. The Azure AD attached folder is auto opened -> Click 'Undelete -> Undelete Selected' -> Click 'OK'.
6. Check whether display a successful activity log.

## Expected Experience ##
Display a successful activity log.
![image](https://user-images.githubusercontent.com/41351993/132317498-5a6f09a2-248a-4964-8482-d2506bc249c4.png)

## Actual Experience ##
Display a failed activity log.
![image](https://user-images.githubusercontent.com/41351993/132316749-2a65f03e-b4e0-4046-8aaa-4ec52e42ad16.png)

## Additional Context ##
1. This issue also reproduces with rbac role "Storage Blob Data Owner".
2. This issue also reproduces when adding the rbac role on the storage accounts level.
3. This issue also reproduces when the subfolder contains soft-deleted blobs.
4. This issue also reproduces when using "Undelete by Date...".

**Comment by JasonYeMSFT** [comment]
The endpoint used to send the undelete request incorrectly include path of the attached directory.

**Comment by v-xianya** [comment]
@JasonYeMSFT Verified on the main build 20210918.3. Fixed.

One question needs to confirm:
It directly opens the folder after Azure AD attaching the HNS folder, as the below:
![image](https://user-images.githubusercontent.com/41351993/133869520-019e6cfd-3073-4606-bde1-2c2387641f30.png)
No error occurs when clicking 'Back' to switch to the its parent directory . Is this intentional?
![image](https://user-images.githubusercontent.com/41351993/133869565-a92b9718-afdd-47d0-afd5-f0216cf6a4ce.png)

**Comment by JasonYeMSFT** [comment]
That's expected. The attachment is intended to let user bypass directories he doesn't have access to. If they do, they can still go backwards.
