### ISSUE TITLE
A blob can be overwritten by a different type of blob with the same name under an Azure AD attached blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4895]
**Storage Explorer Version**: 1.21.0
**Build Number**: 20210905.1
**Branch**: rel/1.21.0
**Platform/OS**: Windows 10/Linux Ubuntu 18.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Add the rbac role 'Storage Blob Data Contributor' then assign to one azure account.
3. Azure AD attach the blob container.
4. Upload one file as block blob to the Azure AD attached blob container.
5. Upload the same file as append blob to the Azure AD attached blob container.
6. There is a conflict dialog -> Apply 'Replace' -> There is a failed activity log.
7. Click 'Retry...' next to the activity log -> Select 'Enable overwrite' -> Click 'Retry Selected'.
8. Check whether the failed activity log still displays.

## Expected Experience ##
The failed activity log still displays.
![image](https://user-images.githubusercontent.com/41351993/132335374-020cf0cf-3b8b-450b-bbf8-a2b9ea98a06b.png)

## Actual Experience ##
A successful activity log displays.

![image](https://user-images.githubusercontent.com/41351993/132335339-517acdc7-aaf8-44e9-bf70-e76b17cff263.png)

## Additional Context ##
1.  This issue also reproduces when applying 'Do not upload' on the 'Conflict' dialog -> Then retry 'Enable overwrite' on the 'Retry Azcopy' dialog.
2. For ADLS Gen2 blob containers, when soft delete is disabled, the block blob is just replaced by the append blob.
when soft delete is enabled, there is a soft-deleted block blob. As the below:
![image](https://user-images.githubusercontent.com/41351993/132335310-8cf16585-35ab-4f3f-b785-976c180a515e.png)
3. For regular blob containers, the result keeps same no matter the soft delete is enabled or not.  (the block blob is just replaced by the append blob, no soft-deleted item is created)
![image](https://user-images.githubusercontent.com/41351993/132337902-7935060d-bfdf-4856-a826-0b9b6b99675f.png)

**Comment by JasonYeMSFT** [comment]
The overwriting behavior is expected. Let's find out why AzCopy reports an error when the user selects "Replace" in the conflict dialog.

**Comment by JasonYeMSFT** [comment]
@v-xianya Could you help me check after the initial AzCopy failure. Does the original block blob still exist in the container? AzCopy might be accidentally deleting the original blob, which explains why the consecutive retry succeeds.

**Comment by v-xianya** [comment]
@JasonYeMSFT The original block blob disappears after manfully refreshing.

**Comment by MRayermannMSFT** [comment]
Private build of AzCopy merged which should address this issue. Overwrites with a different blob type should now fail with HTTP error 409.

**Comment by v-xianya** [comment]
Fixed on the hotfix build 20210918.4.
