### ISSUE TITLE
Progress Spinning wheel keeps on spinning

### ISSUE THREAD

**Issue by daveaod** [Microsoft/AzureStorageExplorer#49]
**Storage Explorer Version:** 1.0.0

**OS Version:** Windows 10

**Steps to Reproduce:**

1. I've set up the Azure Storage Explorer
2. Log in using the SAS URI and I'm able to connect.
3. When I click on the ingestiondata container all I get is the Blue spinning wheel in the middle of the screen.
4. I'm able to upload data via the Azure Powershell as my colleague can see the data I've uploaded but I'm just not able to see any data in the ingestiondata container myself.

Is there anything I need to check ? or can two or more people view the same ingestiondata container at the same time ?

**Comment by jinglouMSFT** [comment]
What permission do you have on the SAS URI?
