### ISSUE TITLE
Display a confused error dialog after inputting a large message for one queue

### ISSUE THREAD

**Issue by v-haiz** [Microsoft/AzureStorageExplorer#490]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180724.5
**Commit**: 3947e25b
**Regression From**: Not a Regression

**Steps to Reproduce**:
1. Go to Subscription -> Storage Accounts.
2. Create a new **queue** -> Add a large message for it -> Check the popped error dialog after saving the message.

**Expected Experience**:
Display the limit of inputting message size like Visual Studio.
![sizeexpect](https://user-images.githubusercontent.com/37653604/43197614-3519a348-8ffb-11e8-8470-d25ddcdbe736.PNG)

**Actual Experience**:
Display a confused error dialog after inputting a large message. 
![size](https://user-images.githubusercontent.com/37653604/43197730-94545d80-8ffb-11e8-87be-93e9cd182ec3.PNG)

**Comment by craxal** [comment]
Once again, we're avoiding interpreting server errors. I think this message is fairly clear about the problem.
