### ISSUE TITLE
The snapshot doesn't display when switching to 'Active blobs and blobs without current version' view context under 'Flat' mode

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4900]
**Storage Explorer Version**: 1.21.0
**Build Number**: 20210908.7
**Branch**: rel/1.21.0
**Platform/OS**: Windows 10/Linux Ubuntu 18.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: From running test case
**Regression From**: 20210903.4

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob -> Create a snapshot for the blob.
3. Open view options panel -> Select 'Flat' mode -> Hide the view options panel.
4. Right click the blob -> Click 'Manage History -> Manage Snapshots'.
5. The blob and its snapshot display in the editor.
6. Switch the view context to 'Active blobs and blobs without current version' or 'All blobs and blobs without current version'.
7. Check whether the snapshot still displays.

## Expected Experience ##
The snapshot still displays.

## Actual Experience ##
The snapshot doesn't display.
![image](https://user-images.githubusercontent.com/41351993/132465624-f015daa1-110c-4b04-9ff1-8a1db3baa137.png)

**Comment by MRayermannMSFT** [comment]
@JasonYeMsft it looks like a condition check for listing snapshots is probably missing here:
![image](https://user-images.githubusercontent.com/21112697/132542656-93d8709d-4cf6-4c1b-b31f-2a07224bf167.png)
The scenario for this is pretty edge case, so we'll leave this for 1.22 or a possible 1.21.1.

**Comment by v-xianya** [comment]
Verified on the latest main build/20210923.3. Fixed.
![image](https://user-images.githubusercontent.com/41351993/134460106-8da043c6-6a10-48a1-9c80-5edc5ce80199.png)
