### ISSUE TITLE
The 'No' button is selected on the promote snapshot dialog for the ADLS Gen2 blob snapshot

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4904]
**Storage Explorer Version**: 1.21.0
**Build Number**: 20210908.7
**Branch**: rel/1.21.0
**Platform/OS**: Windows 10/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Create snapshot for the blob -> Right click the blob -> Click 'Manage Snapshots'.
4. Select the blob snapshot -> Click 'Promote Snapshot'.
5. Check whether the 'Yes' button is selected.

## Expected Experience ##
The 'Yes' button is selected.

## Actual Experience ##
The 'No' button is selected.
![image](https://user-images.githubusercontent.com/41351993/132646505-76503ff4-7e8c-4d61-b8b1-74e1eed74ce9.png)

## Additional Context ##
1. The screenshot of the ADLS Gen2 blob promote snapshot on the Linux Ubuntu 20.04:
![image](https://user-images.githubusercontent.com/41351993/132647007-16e85be8-82eb-4c48-bc37-431f7feaa90a.png)

**Comment by JasonYeMSFT** [comment]
ADLS Gen2 is using an old system dialog which we set No to be the default button.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20211110.13. Fixed.
