### ISSUE TITLE
The current version doesn't display the directory name after promoting its previous version at the root level (Flat mode)

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4907]
**Storage Explorer Version**: 1.21.0
**Build Number**: 20210908.7
**Branch**: rel/1.21.0
**Platform/OS**: Windows 10//Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one non-ADLS Gen2 storage account -> Blob Containers (Blob versioning is enabled).
2. Create a blob container -> Create a folder -> Upload a blob.
3. Click 'Back' to the root level.
4. Open view options panel -> Select 'Flat' mode -> Hide view options panel.
5. Delete the blob -> Switch to view context 'All blobs and blobs without current version'.
6. There is a previous version displaying the directory name -> Click 'Promote Version'.
7. Check whether the current version displays the directory name.

## Expected Experience ##
The current version displays the directory name and the previous version disappears.

## Actual Experience ##
The current version doesn't display the directory name.
![image](https://user-images.githubusercontent.com/41351993/132787830-3c423264-e8f2-4be9-8745-4f05b9389d5d.png)

## Additional Context ##
1. This issue also reproduces under view context 'Active blobs and blobs without current version'.
2. This issue doesn't reproduce when skipping the step3.
![image](https://user-images.githubusercontent.com/41351993/132788614-7d648eac-30f8-4a4e-b5e5-e93d8176a1c3.png)

**Comment by MRayermannMSFT** [comment]
Fix merged to hotfix branch

**Comment by v-xianya** [comment]
Fixed on the rel/build 20210916.5.
