### ISSUE TITLE
The 'Paste' button is always disabled on the toolbar of one SAS attached ADLS Gen2 folder

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4909]
**Storage Explorer Version**: 1.21.0
**Build Number**: 20210908.7
**Branch**: rel/1.21.0
**Platform/OS**: Windows 10//Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one folder which contains blobs.
3. Right click the folder -> Click 'Get Shared Access Signature...' -> Select full permissions -> Click 'Create'.
4. Copy the SAS URL -> Attach the folder via the SAS URL.
5. Click 'Copy' on the toolbar of the attached folder.
6. Check whether the 'Paste' button is enabled.

## Expected Experience ##
The 'Paste' button is enabled.

## Actual Experience ##
The 'Paste' button is disabled.
![image](https://user-images.githubusercontent.com/41351993/132812460-20855710-56ca-4c17-ba62-70adf7bb027a.png)

**Comment by JasonYeMSFT** [comment]
It is currently disabled due to https://github.com/microsoft/AzureStorageExplorer/issues/3976. I can verify if that bug has been fixed.

**Comment by v-xianya** [comment]
Thank you for the updates! we are going to close this bug.
