### ISSUE TITLE
Uploading the same blob displays an extra snapshot with strikethrough after deleting it with soft delete enabled

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#491]
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180724.5
**Commit**: 2605f1c9
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Expand one account then enable soft delete for 'Blob Containers'.
2. Open one blob container and upload a blob to it.
3. Delete the uploaded blob -> Switch to 'Active and deleted blobs' and make sure the deleted blob displays with strikethrough.
4. Upload the same blob again -> Go to manage snapshots editor for the blob.

#### Expected Experience: ####
There is no extra blob snapshot with strikethrough.

#### Actual Experience: ####
An extra blob snapshot with displays.
![line](https://user-images.githubusercontent.com/34729022/43197979-7b7bd22e-8ffc-11e8-8606-df481072fcb0.png)

**Comment by JasonYeMSFT** [comment]
This is by design of the platform. The soft deleted snapshot has the content of the old soft deleted blob. 
See `Put Block` API in the doc https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-soft-delete
