### ISSUE TITLE
Sonarqube upgrade from 7.7 to 9. community edition in Azure app service with existing DB

### ISSUE THREAD

**Issue by ashifalibd** [microsoft/AzureStorageExplorer#4910]
Hi
We’ve deployed Sonarqube 7.7 community version in Azure app service with an Azure SQL database. Now I’ve created a new environment in Azure app service with a new Azure SQL database, and it’s operating perfectly. Now I’d like to move data from the old Azure database to the new Azure database. However, I am unable to do so since Azure requires an empty database. So, could somebody give me some pointers? Actually, my goal is to upgrade/migrate existing data from Sonarqube 7.7 azure app service to Sonarqube 9.0 azure app service.

**Comment by MRayermannMSFT** [comment]
Hi @ashifalibd , this GitHub repo is for Azure Storage Explorer. So unfortunately we will not be able to help you with this issue. Here's some resources you may find help using:
- Opening an Azure support ticket from the portal
- https://stackoverflow.com
- https://www.reddit.com/r/AZURE/
