### ISSUE TITLE
Fail to undelete all soft-deleted items when the selection contains soft-deleted blobs and its soft-deleted root directory

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#4911]
**Storage Explorer Version:** 1.21.0
**Build Number:** 20210908.7
**Branch:** rel/1.21.0
**Platform/OS:** Windows 10//Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture:** ia32\x64
**How Found:** From running test case
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Create a new folder A.
3. Upload folder B which contains one blob to folder A.
4. Soft delete the blob in the folder B -> Then soft delete the folder A.
5. Switch to 'Delete only' context -> Click 'Select All -> Select All in Page'.
6. Click 'Undelete -> Undelete Selected'.
6. Check whether succeed to undelete.

## Expected Experience #
Succeed to undelete.

## Actual Experience ##
Only succeed to undelete folder A.
![image](https://user-images.githubusercontent.com/87792676/132835501-031ad789-f012-47c4-9257-b51e7f6828c4.png)

Error Details:
![image](https://user-images.githubusercontent.com/87792676/132832252-b2e707a5-7ec6-43fd-bf1b-aaf83eff8385.png)

## Additional Context ##
Related issue: [4775](https://github.com/microsoft/AzureStorageExplorer/issues/4775)

**Comment by JasonYeMSFT** [comment]
The dependency tracking logic didn't catch this scenario where the a dependent directory is not the immediate parent directory of the child.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20210930.3. Fixed.
