### ISSUE TITLE
Storage Explorer - Unable to retrieve child resources

### ISSUE THREAD

**Issue by SR123321** [microsoft/AzureStorageExplorer#4914]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.0

### Architecture

i86

### Storage Explorer Build Number

20210908.7

### Platform

Windows

### Bug Description

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://marsanalyticsdevadls.blob.core.windows.net/?comp=list&include=metadata failed, reason: unable to get local issuer certificate",
  "stack": "FetchError: request to https://marsanalyticsdevadls.blob.core.windows.net/?comp=list&include=metadata failed, reason: unable to get local issuer certificate\n    at ClientRequest.<anonymous> (C:\\Users\\rangaswa\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1461:11)\n    at ClientRequest.emit (events.js:315:20)\n    at TLSSocket.socketErrorListener (_http_client.js:469:9)\n    at TLSSocket.emit (events.js:315:20)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
  "type": "system",
  "errno": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY",
  "code": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"
}

### Steps to Reproduce

1. Launch Storage Explorer
2. Click on Blob Containers

### Actual Experience

When I click on "Blob containers" I get the error. Have tried uninstall and reinstall. Delete the %app%Storageexplorer folder etc, but the issue still exists.

### Additional Context

![image](https://user-images.githubusercontent.com/57729422/132903782-a9618185-d986-449a-b379-efc120a8e81a.png)

**Comment by jinglouMSFT** [comment]
Have you tried to follow this troubleshooting guide to resolve the issue?  https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#ssl-certificate-issues
Thanks.

**Comment by Denisjc** [comment]
I have the same issue on installing this version , was working fine just before the install and now not.  Will revert to a previous version of your tool as I need to get my work done without errors.

**Comment by SR123321** [comment]
Installing a older version did not solve my issue.
