### ISSUE TITLE
V12 File Share Statistics

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#4916]

**Comment by MRayermannMSFT** [comment]
@v-xianya file share statistics has been rewritten and merged into main. Please verify that there are no negative regressions in behavior with the new rewrite.

**Comment by v-xianya** [comment]
@MRayermannMSFT Ok, we will verify this after finishing hotfix testing😊

**Comment by v-xianya** [comment]
Verified on the latest main build 20210923.3. No new issue was found.
