### ISSUE TITLE
Use the current cultural format for displaying dates like 'Last Modified'

### ISSUE THREAD

**Issue by deangoddard** [microsoft/AzureStorageExplorer#4917]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

DateTime fileds are displayed in US date time format.  Australians use day/month/year, not month/day/year.

### Desired Solution

The Windows OS supplies the current cultural format for you.  In C# its => DateTime.Now.ToString(CultureInfo.CurrentUICulture.DateTimeFormat);

### Alternatives and Workarounds

Use a pre-configured region => new CultureInfo("en-GB").DateTimeFormat

**Comment by deangoddard** [comment]
![image](https://user-images.githubusercontent.com/12726531/133012902-9ec1c96a-bb6a-4f7e-ba76-7640b4681ca6.png)
Last Modified datetime format is not using the current local format which in this case is Australian dd/MM/yyyy

**Comment by MRayermannMSFT** [comment]
@deangoddard can you confirm for us what version of Storage Explorer you are using? We are in the process of rolling out version 1.21.0 and it includes what you are asking for (or at least it should...). If you have not yet received the update, please download and install manually from https://storageexplorer.com and let us know if it solves this for you. Thanks!

**Comment by deangoddard** [comment]
Hi Matthew,

Version 1.20.1
AzCopy Version: 10.11.0

Build Number 20210720.10

Cheers,

Dean Goddard
Champion Technology Officer
FunKey Solutions
Mobile: 0434 298 412 | Email: ***@***.***

----------------------------------------

**Comment by deangoddard** [comment]
All fixed with version 1.21.0.

Thanks.
