### ISSUE TITLE
blob container won't create

### ISSUE THREAD

**Issue by AiturganSu** [microsoft/AzureStorageExplorer#4918]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21

### Architecture

x64

### Storage Explorer Build Number

20210908.7 

### Platform

macOS

### OS Version

MacOs

### Bug Description

I can't create a blob container

### Steps to Reproduce

Open Microsoft Azure Storage Explorer > Expand Storage Account> Expand Blob Container>Action Create blob container > Enter blob container name> Enter

### Actual Experience

Failed to create blob container 'db-bacpac-aiturgan': This request is not authorized to perform this operation.
RequestId:2060d043-101e-0032-41ca-a891f5000000
Time:2021-09-13T18:09:39.2063510Z
<img width="1329" alt="Screen Shot 2021-09-13 at 3 26 58 PM" src="https://user-images.githubusercontent.com/71417803/133134828-45eca44d-db34-452d-a130-7364b128a06b.png">
![Uploading Screen Shot 2021-09-13 at 3.27.08 PM.png…]()

### Expected Experience

create a blob container

**Comment by MRayermannMSFT** [comment]
@AiturganSu 
- Do you have key access to this storage account? You can check by clicking on the node for the account, going the the properties panel below the tree view, look for the key properties, and see if they have values by clicking on the eye icon next to them?
- If you do not have key access, what RBAC roles do you have for this account?

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response.
