### ISSUE TITLE
The 'Yes' button is not selected on the popped up dialog when opening a blob with untrusted extension

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#4920]
**Storage Explorer Version:** 1.21.0
**Build Number:** 20210914.1
**Branch:** main
**Platform/OS:** Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture:** ia32\x64
**How Found:** From running test case
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Launch Storage Explorer -> Settings.
2. Go to Settings -> Transfers -> File Open -> Trusted File Extensions.
3. Make sure the .csv extension is not included in Trusted File Extensions.
4. Open one regular blob container -> Upload one .csv blob.
5. Open the blob -> Check whether the 'Yes' button is selected on the popped up dialog.

## Expected Experience ##
The 'Yes' button is selected.

## Actual Experience ##
The 'Yes' button is not selected.
![image](https://user-images.githubusercontent.com/87792676/133230937-ee222f1d-4e4d-4328-9afc-daa799dd4aba.png)

## Additional Context ##
This issue doesn't reproduce on Linux.
![image](https://user-images.githubusercontent.com/87792676/133231033-c64e17c4-0964-4d52-95b5-d7d4a0c9cdf3.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20211110.13.
 1. The 'No' button is selected on Windows.
![image](https://user-images.githubusercontent.com/87792676/141226229-db495446-4d0f-42bb-94ff-49b41c4fb03a.png)
2. The 'Yes' button is selected on Linux.
![image](https://user-images.githubusercontent.com/87792676/141226322-7066936d-93ce-430a-b5cd-013acf0ee614.png)

**Comment by craxal** [comment]
@kellyluo We decided that defaulting to No was preferrable, as we don't want to eagerly open potentially unsafe files. If users bring this up, we'll switch back to Yes as default.

**Comment by v-kellyluo** [comment]
Hi @craxal Verified this issue on the build main/20211112.4. 

1. It works well on the storage explorer which is installed by tar. But the 'Yes' button is selected if it was installed by snap, do we need to notice that?
2. Here is the screenshot:

![image](https://user-images.githubusercontent.com/87792676/141403196-4e084185-37ee-4167-8530-b924ff72b8bb.png)

**Comment by craxal** [comment]
Try again on a newer build. It's possible the change was not picked up.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20211114.9, it works well.
