### ISSUE TITLE
CosmosDB: Unable to retrieve child resources.

### ISSUE THREAD

**Issue by jayatipathak** [microsoft/AzureStorageExplorer#4921]
I am trying to connect to Cosmos DB account to which I have permissions. But everytime I get below error.
I tried re-installing the storage explorer app, but no luck. Please check.

Unable to retrieve child resources.

![image](https://user-images.githubusercontent.com/28723607/133254089-75bab3aa-fc72-4231-a3ae-8e1e8a599679.png)

**Comment by jayatipathak** [comment]
If there is a workaround for this issue, please suggest to unblock.
I already tried removing \AppData\Roaming\StorageExplorer folder looking at some other suggestions for similar issue, and it did not work.

**Comment by NatashaProt** [comment]
I have the same error for a long time. But no other details in the error window. So I re-installed the application to the newest version. It didn't help.
I try to connect to CosmosDB for my working project. My team provided several connection strings (AccountEndpoint and AccountKey), but the error is the same. When I close the error window, I can't see any table in DB.
Other colleagues can connect and open the DB with visible tables.

**Comment by jinglouMSFT** [comment]
@NatashaSavchuk The CosmosDB team has decided to deprecate the CosmosDB support in Storage Explorer as you probably have seen in other CosmosDB related issues posted/commented in this repo.  The suggestion was to use the portal instead.  See more comments in this issue: https://github.com/microsoft/AzureStorageExplorer/issues/3161.

**Comment by NatashaSavchuk** [comment]
@jinglouMSFT could you please share the link for portal which I can use for adding conenction string?

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
