### ISSUE TITLE
Azure Storage Explorer v1.21.0 don't read inside huge container 

### ISSUE THREAD

**Issue by cosmospuglisi** [microsoft/AzureStorageExplorer#4922]
I cannot see the folder inside a container including TB of data and thousand subfolders. no problem with previous version

**Comment by JasonYeMSFT** [comment]
Could you elaborate on some details of the issue?
- Are you accessing a blob container or an ADLS Gen2 blob container?
- Are you unable to see any folder inside the container or some specific ones that you know exists?
- Is the folder under the root of the container or within some other directories?
- Which view context are you in? The view context is chosen from a dropdown in the address bar.
<img width="456" alt="Screen Shot 2021-09-14 at 9 35 59 AM" src="https://user-images.githubusercontent.com/39359541/133298132-5e7baa06-419f-45d2-8002-d15566b017f3.png">
- If you haven't loaded all the pages, please try loading all the pages and see if the folder shows up. 
<img width="901" alt="Screen Shot 2021-09-14 at 9 39 38 AM" src="https://user-images.githubusercontent.com/39359541/133298616-f0d5de49-385c-47fb-baa2-1f5a7f56cd4d.png">

**Comment by JasonYeMSFT** [comment]
Might be related to https://github.com/microsoft/AzureStorageExplorer/issues/4931. If you can try the previous release, could you check the creation time of the missing directories?

**Comment by cosmospuglisi** [comment]
Which operating system you are on (Windows, macOS, Linux)? Windows
    Are you accessing a blob container or an ADLS Gen2 blob container? ADLS GEn2 
    Are you unable to see any folder inside the container or some specific ones that you know exists? Any folder
    Is the folder under the root of the container or within some other directories? any folder
    Which view context are you in? The view context is chosen from a dropdown in the address bar.

**Comment by cosmospuglisi** [comment]
> 
> 
> @cosmospuglisi
> Might be related to #4931. If you can try the previous release, could you check the creation time of the missing directories?

Yes, it's the same error, but the container I cannot see has this last date
![image](https://user-images.githubusercontent.com/140662/134153100-ccee68d2-20ef-42e0-9681-9ed5b2a16fbd.png)

**Comment by cosmospuglisi** [comment]
sorry, I've closed the issue for error

**Comment by JasonYeMSFT** [comment]
@cosmospuglisi I mean the creation time of the missing folders. You can view those info by installing Storage Explorer 1.20.1 and use the "Properties" command to get them in the `CreatedOn` field .

![image](https://user-images.githubusercontent.com/39359541/134213150-2f2cca8a-7d65-4939-8371-c5470b99ac61.png)
![image](https://user-images.githubusercontent.com/39359541/134213186-2df00cb9-b054-478a-aaa1-6797473e0166.png)

**Comment by cosmospuglisi** [comment]
Using powershell cmdlet the result is:
CreatedOn             : 1/1/1601 12:00:00 AM +00:00

**Comment by JasonYeMSFT** [comment]
OK, it is indeed the same issue. We will ship the fix with 1.21.1 so that those folders will be accessible again.

**Comment by JasonYeMSFT** [comment]
We have published 1.21.1. Please upgrade to fix this issue.
