### ISSUE TITLE
Failed to create blob container

### ISSUE THREAD

**Issue by GouthamGeek** [microsoft/AzureStorageExplorer#4924]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.0

### Architecture

x64

### Storage Explorer Build Number

20210908.7

### Platform

Windows

### OS Version

windows 10

### Bug Description

Unable to retrieve child resources.

Details:
{
  "name": "RestError",
  "message": "This request is not authorized to perform this operation using this permission.\nRequestId:0b6bdf5b-001e-004a-1f8c-a92cf7000000\nTime:2021-09-14T17:20:15.2020277Z",
  "stack": "RestError: This request is not authorized to perform this operation using this permission.\nRequestId:0b6bdf5b-001e-004a-1f8c-a92cf7000000\nTime:2021-09-14T17:20:15.2020277Z\n    at handleErrorResponse (C:\\Users\\14167\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:3134:19)\n    at C:\\Users\\14167\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:3070:49\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async StorageRetryPolicy.attemptSendRequest (C:\\Users\\14167\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\storage-blob\\dist\\index.js:14657:24)\n    at async StorageClientContext.sendOperationRequest (C:\\Users\\14167\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:4681:31)\n    at async BlobServiceClient.listContainersSegment (C:\\Users\\14167\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\storage-blob\\dist\\index.js:23490:20)",
  "code": "AuthorizationPermissionMismatch",
  "statusCode": 403,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://storage309goutham.blob.core.windows.net/?comp=list&include=metadata",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2020-08-04"

### Steps to Reproduce

1. Launch Storage Explorer
2. Expand storage accounts
3. Expand blob container
4. Create Blob container (but doesn't create)

### Actual Experience

When creating a blob container I get an error "Failed to create blob container 'database-bacpac-goutham': This request is not authorized to perform this operation.
RequestId:eacd2476-501e-0025-3e88-a92604000000
Time:2021-09-14T16:48:30.4745698Z"

**Comment by MRayermannMSFT** [comment]
@GouthamGeek how are you accessing your Storage resources?

If you've signed into your Azure account:

- What type of access/permissions do you have for this account?
- Do you have the ability to list the keys for the Storage Account?
- Do you have any RBAC roles on the Storage Account? If so, what roles do you have?

If you've attached with SAS:

- What permissions does your SAS have?
- Are the permissions included in the SAS or are they coming from a stored access policy?

**Comment by JasonYeMSFT** [comment]
I found this to be a duplicate issue of #4918 so I am going to close this issue and track the problem there.
