### ISSUE TITLE
Can't create blob container in Storage Explorer 

### ISSUE THREAD

**Issue by mbutt19** [microsoft/AzureStorageExplorer#4928]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.0

### Regression From

na

### Architecture

x64

### Storage Explorer Build Number

20210908.7

### Platform

Windows

### OS Version

10

### Bug Description

I am unable to create blob containers in Storage Explorer. It fails to create every time.  

 I also get an "unable to retrieve child resources" message when I initially expand the Blob node in my storage account. This happens on the first load and on clicking refresh all in the explorer pane. I have played around with the permissions and properties but still cannot locate the cause of the error. 

I am following a tutorial but am stuck on this step. 

### Steps to Reproduce

1. Launch Storage Explorer
2. Expand storage account
3. Expand blob container
4. Create Blob container (but doesn't create)
5. Refresh all
6. Expand blob container

### Actual Experience

Launch Storage Explorer
Expand storage account
Expand blob container
"Child Resources" error
Create Blob container (but doesn't create)
"Failed to Create" error
Refresh all
Expand blob container
"Child Resources" error

### Expected Experience

For the blob container to be created

### Additional Context

Unable to retrieve child resources.

Details:
{
  "name": "RestError",
  "message": "This request is not authorized to perform this operation using this permission.\nRequestId:0dcdbdb5-401e-006f-7fb1-a97541000000\nTime:2021-09-14T21:42:16.9813319Z",
  "stack": "RestError: This request is not authorized to perform this operation using this permission.\nRequestId:0dcdbdb5-401e-006f-7fb1-a97541000000\nTime:2021-09-14T21:42:16.9813319Z\n    at handleErrorResponse (C:\\Users\\eagle\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:3134:19)\n    at C:\\Users\\eagle\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:3070:49\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async StorageRetryPolicy.attemptSendRequest (C:\\Users\\eagle\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\storage-blob\\dist\\index.js:14657:24)\n    at async StorageClientContext.sendOperationRequest (C:\\Users\\eagle\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:4681:31)\n    at async BlobServiceClient.listContainersSegment (C:\\Users\\eagle\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\storage-blob\\dist\\index.js:23490:20)",
  "code": "AuthorizationPermissionMismatch",
  "statusCode": 403,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://storage309mustafa.blob.core.windows.net/?comp=list&include=metadata",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2020-08-04"
        },
        "accept": {
          "name": "accept",
          "value": "application/xml"
        },
        "user-agent": {
          "name": "user-agent",
          "value": "Microsoft Azure Storage Explorer, 1.21.0, win32 azsdk-js-storageblob/12.7.0 (NODE-VERSION v14.16.0; Windows_NT 10.0.19043)"
        },

**Comment by JasonYeMSFT** [comment]
@mbutt19 Could you check if you have any firewall settings configured on the storage account? They might lead to permission errors even if your credential has the right permission.
