### ISSUE TITLE
Accessing a File Share on a Storage Account with an app specific proxy results in a timeout issue

### ISSUE THREAD

**Issue by soloji** [microsoft/AzureStorageExplorer#4930]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.0

### Regression From

1.10.1

### Architecture

i86

### Storage Explorer Build Number

20210908.7

### Platform

Windows

### OS Version

Windows 10 Enterprise 1909 

### Bug Description

File Share doesn't seem to uses the application specified proxy.
We have specified an app specific proxy for Azure Storage Explorer but when attempting to browse to the "File Share" of an account the access times out with the image below. 
In the old version we would see traffic on the proxy server when opening File Shares such as 
_.file.core.windows.net:443_. 
However in this version we see no traffic attempting to reach the specified proxy.

![image](https://user-images.githubusercontent.com/5194303/133354406-e1bb3f69-5a92-4cf1-a482-4e3378495279.png)

![image](https://user-images.githubusercontent.com/5194303/133354168-3b6e1d93-4c56-42b7-82b2-3bae06c6c452.png)

![image](https://user-images.githubusercontent.com/5194303/133354237-9a251c37-9074-4e1e-a173-3b31ad0cdb0b.png)

### Steps to Reproduce

1. Launch Storage Explorer
2. Specify application specific proxy - no bypass specified
3. Add account
4. Attempt to navigate to File Share that you have permission to (note that blobs work as expected)
5. Error will appear

### Actual Experience

When attempting to open File Shares I get the following error that seems to indicate that traffic is not being direct to the specified proxy

![image](https://user-images.githubusercontent.com/5194303/133354168-3b6e1d93-4c56-42b7-82b2-3bae06c6c452.png)

![image](https://user-images.githubusercontent.com/5194303/133354237-9a251c37-9074-4e1e-a173-3b31ad0cdb0b.png)

### Expected Experience

Able to open the File Share when using a application specific proxy

### Additional Context

This is a major jump in version for our organisation 1.10.1 to 1.21.0 and I appreciated this might of broken in much earlier versions.

**Comment by soloji** [comment]
I was able to get our teams to install 1.20.1 and the issue is not present in that version. I am able to browse to the File Share as expected and I can see the traffic on the proxy.

**Comment by craxal** [comment]
The error message says that it's trying to go through the local host (127.0.0.1), which suggests the wrong proxy settings are being used. Can you please share your log files with us for both "main" and "se-file-extension"? You can find the log files by selecting **Help** > **Open Logs Directory** from the menu.

**Comment by soloji** [comment]
Thanks craxal,
Because of corporate environment it is hard to override system proxy settings or environment variables and our users aren't very tech savvy to say the least. Getting them to use the GUI is very useful for me,
I have attached the logs and done the breakpoint as requested all seem to point to the external proxy.

Is it possible that your fiddler is working because it is listening locally on 3128 and the error indicates that it is trying to connect to 127.0.0.1:3128 - thus would work with a local fiddler that is listening on 127.0.0.1?

Have you tried with an external proxy - squid should be about 20mins of work to get running on another machine or maybe fiddler listening on another machine?


![image](https://user-images.githubusercontent.com/5194303/133536265-3309b64d-ea48-4285-9ed5-d1a631ce2b73.png)
[2021-09-16_114127_se-managed-disks-extension_16916.log](https://github.com/microsoft/AzureStorageExplorer/files/7174355/2021-09-16_114127_se-managed-disks-extension_16916.log)
[2021-09-16_114127_main.log](https://github.com/microsoft/AzureStorageExplorer/files/7174356/2021-09-16_114127_main.log)

**Comment by craxal** [comment]
@soloji Can you also provide the logs for the "se-file-extension" process? Since the problem you're having is with file shares, that may be more informative. Have you also confirmed that you are using the correct protocol, username, and password?

If your OS is already configured to go through the same proxy, it may be easier for you to change Storage Explorer's settings to "Use system proxy".

I will try setting up a real proxy on my end and see if I can reproduce the issue. To confirm, what kind of authentication does your proxy server use?

**Comment by MRayermannMSFT** [comment]
> it may be easier for you to change Storage Explorer's settings to "Use system proxy".

@craxal this will not work, file share features are not onboarded to system proxy at this time.

**Comment by craxal** [comment]
@soloji FYI, I've been wrestling with Squid and other proxy options for a while but have not been successful in getting anything to work except Fiddler locally, let alone get Storage Explorer to work with it.

I mentioned it before, but I want to make sure. The log files indicate that you have a username and password, but "Use credentials" is turned off. Assuming your proxy uses Basic authentication, does your proxy expect a username and password?

**Comment by soloji** [comment]
@craxal  Good morning, thanks for trying to reproduce!
Our proxy is not expecting a user name and password.  It uses no authentication

I will get the logs of the file that you requested shortly

**Comment by soloji** [comment]
Two findings this morning
1. No logs are generated for the se-fileextension-process, it only seems to generate logs for the successful 
2. The tables feature also suffers the same issue (we don't use this, so I hadn't checked till you prompted me, thanks!)
One difference between the file and tables is that tables fails immediately compared to tables that fails after a while (I expect that is just a retry/wait logic on the files vs tables)

![image](https://user-images.githubusercontent.com/5194303/133691473-d770c56e-cb6e-4989-b9c8-7887295f9f0a.png)

**Comment by craxal** [comment]
@soloji Thanks for the info. I was able to reproduce the same behavior using a simple Node script to act as a proxy on a different machine. Blobs and Queues work, but Files and Tables do not. The key difference is we use different SDK versions, and so setting up the proxy is different for each version.

Since you say it doesn't reproduce in 1.20.1, can you follow the same steps above involving the dev tools with that version? I'm curious to see if the proxy value is different between versions.

**Comment by craxal** [comment]
I think I found the problem. In 1.21.0, we changed just a little bit how we set proxy settings for the File and Table clients. However, the documentation was wrong, so we were passing the settings in the wrong format. Not entirely sure why this error is only apparent when working with a non-local proxy, but I tested the fix, and it seems to be working.

@soloji Would you like to try out a private build to see if the change fixes your issue?

**Comment by soloji** [comment]
@craxal  great news! I always think that once an expert can reproduce, the fix is not far away

would be happy to test, might take a business day or two as I need to get things whitelisted but I should be able to test by early next week.

**Comment by craxal** [comment]
@soloji You can download the build from [here](https://cralvordtest02.blob.core.windows.net/customer-share/internal/1.21.1/StorageExplorer-ia32.exe?sv=2020-08-04&st=2021-09-17T01%3A42%3A55Z&se=2021-09-25T01%3A42%3A00Z&sr=b&sp=r&sig=231jaiHPDDKcMtuI0xMg%2FLL3ENCCeh9qjPDWnhh%2Fl5k%3D). It's possible we may ship a hotfix early next week, so the sooner you can try out this build and verify it works, the better.

**Comment by soloji** [comment]
@craxal I have installed the build you provided and the file and table function is working with our proxy.
Thank  you very much for the fast turn around on this issue
