### ISSUE TITLE
Can't delete more than one blob at the same time under the <no name> path

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4934]
**Storage Explorer Version**: 1.21.1
**Build Number**: 20210916.5
**Branch**: hotfix/1.21.1
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Create a folder with name "/".
3. Display ![image](https://user-images.githubusercontent.com/41351993/133570353-5043d593-ba9d-439d-8b6e-ff90d9fa2585.png)in the address bar.
4. Upload two blobs to the path.
5. Select two blobs -> Delete them.
6. Check whether succeed to delete.

## Expected Experience ##
Succeed to delete.

## Actual Experience ##
Can't delete and show a successful activity log as below:
![image](https://user-images.githubusercontent.com/41351993/133570058-b6352fa3-1535-48aa-81fc-c0d61d6cfcd9.png)

## Additional Context ##
1. The blobs can be successfully deleted respectively.
2. This issue doesn't reproduce on Portal.

**Comment by JasonYeMSFT** [comment]
AzCopy has limitation operating on urls that end with multiple slashes. And this is a very edge case so we won't fix for now.
