### ISSUE TITLE
Unable to retrieve child resources from storage account

### ISSUE THREAD

**Issue by scsicat5** [microsoft/AzureStorageExplorer#4935]
Unable to retrieve child resources.

Details:
This request is not authorized to perform this operation.
RequestId:45d2f000-801a-0038-3513-ab7baf000000
Time:2021-09-16T15:59:13.7900141Z

**Comment by JasonYeMSFT** [comment]
@scsicat5 Could you tell us more information including:
- Which Storage Explorer version are you using
- Which node to be expanded triggers this error
- What type of credentials are you using to access that resource (e.g. Key, SAS, Signed-in subscription). If you are signed-in, what rbac roles do you have on that resource?

**Comment by NatashaProt** [comment]
@JasonYeMSFT I have the same error for a long time. So I re-installed the application to the newest version. I try to connect to CosmosDB for my working project. My team provided several connection strings (AccountEndpoint and AccountKey), but the error is the same. When I close the error window, I can't see any table in DB.
![image](https://user-images.githubusercontent.com/12084986/135246769-e9649c3f-e2ba-4a39-ac60-a81d7eec1d07.png)
 Other colleagues can connect and open the DB with visible tables.

**Comment by JasonYeMSFT** [comment]
@natashaSavchuk Could you share the steps from attaching the Table using the connection string up to getting this error?

By the way, if you are trying to list the tables under the "Cosmos DB Accounts" node, we won't be able to do anything on it since it will be retired in our next release #4935. If you are using its Table endpoint to connect, we might need to add some more error logging to figure out the cause.

**Comment by NatashaSavchuk** [comment]
You're right. I user Cosmos DB account for SQL API string. What we can use in this case?

**Comment by MRayermannMSFT** [comment]
@NatashaSavchuk for CosmosDB, the current recommendation is to try using either:
- the portal: https://portal.azure.com
- the online cosmos explorer: https://cosmos.azure.com

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having issues you can either:
- open an Azure support ticket via the portal
- open a new issue here
Thanks.
