### ISSUE TITLE
Add wildcard search in Filter Prefix while searching a file in a folder.

### ISSUE THREAD

**Issue by avinashgupta-gep** [microsoft/AzureStorageExplorer#4937]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Search a file easily.

### Desired Solution

wildcard search in Filter Prefix

**Comment by MRayermannMSFT** [comment]
Duplicate of #1667
