### ISSUE TITLE
Can't list containers due to AuthorizationPermissionMismatch

### ISSUE THREAD

**Issue by Johnny-shin** [microsoft/AzureStorageExplorer#4939]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.0

### Architecture

x64

### Platform

macOS

### OS Version

macOS Bigsur

### Bug Description

Unable to retrieve child resources.

Details:
```JSON
{
  "name": "RestError",
  "message": "This request is not authorized to perform this operation using this permission.\nRequestId:d5a0e494-401e-0064-5dc2-ab7ee0000000\nTime:2021-09-17T12:52:04.6105795Z",
  "stack": "RestError: This request is not authorized to perform this operation using this permission.\nRequestId:d5a0e494-401e-0064-5dc2-ab7ee0000000\nTime:2021-09-17T12:52:04.6105795Z\n    at handleErrorResponse (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/@azure/core-http/dist/index.js:3134:19)\n    at /Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/@azure/core-http/dist/index.js:3070:49\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async StorageRetryPolicy.attemptSendRequest (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/@azure/storage-blob/dist/index.js:14657:24)\n    at async StorageClientContext.sendOperationRequest (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/@azure/core-http/dist/index.js:4681:31)\n    at async BlobServiceClient.listContainersSegment (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/@azure/storage-blob/dist/index.js:23490:20)",
  "code": "AuthorizationPermissionMismatch",
  "statusCode": 403,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://storage309hyunjong.blob.core.windows.net/?
```

### Steps to Reproduce

1. Launch Storage Explore through Azure web portal
2. Expand a blob container node.

### Actual Experience

I'm currently using a school account for lab session. Many of students are facing same issue which is not able to expand a blob container node. Plus, some of them are able to expand and create new child node but whenever they upload bacpac file. The content of table is always empty.

**Comment by jinglouMSFT** [comment]
@Johnny-shin can you confirm whether this is the storage explorer in the portal, or the desktop application of storage explorer?  If desktop, did you sign into Azure then access your storage or did you attach to the storage?

**Comment by vKaides** [comment]
Hi, i got the same problem did you know how to fix it?

**Comment by MRayermannMSFT** [comment]
@vKaides did you sign into Azure then access your storage or did you attach to the storage? If you attached, how did you attach (SAS, connection string, name and key, attach with Azure AD)?

**Comment by Johnny-shin** [comment]
> @Johnny-shin can you confirm whether this is the storage explorer in the portal, or the desktop application of storage explorer? If desktop, did you sign into Azure then access your storage or did you attach to the storage?

I tried both. Also I signed-in properly because I was able to use other services in Azure

**Comment by MRayermannMSFT** [comment]
@Johnny-shin if you are seeing issues both in the Storage Explorer desktop client and when trying to use the Azure portal in your browser then we recommend you open an Azure support ticket.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having issues you can either:
- open an Azure support ticket via the portal
- open a new issue here
Thanks.
