### ISSUE TITLE
It is always in a verified state when adding one custom environment if using 'https://telerik.com/download/fiddler' as the ARM endpoint

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#4942]
**Storage Explorer Version:** 1.21.1
**Build Number:** 20210918.4
**Branch:** hotfix/1.21.1
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture:** ia32\x64
**How Found:** Exploratory testing
**Regression From:** Previous release (1.19.1)

## Steps to Reproduce ##

1. Launch Storage Explorer
2. Open the connect dialog -> Select 'Subscription -> Custom Environment:' -> Click 'Manage custom environments...'.
3. Click 'Add' -> Type a valid Environment name -> Type 'https://telerik.com/download/fiddler' to ARM endpoint.
4. Click 'Add' -> Check whether error message appears.

## Expected Experience ##
Error message appears.
![image](https://user-images.githubusercontent.com/87792676/133869613-113c67d7-7434-4a42-b59e-13e6a35a7ada.png)

## Actual Experience ##
It is always in a verified state.
![image](https://user-images.githubusercontent.com/87792676/133869678-abb52b98-450f-449c-a42d-7ad6e29292bf.png)

**Comment by JasonYeMSFT** [comment]
We are not correctly catching an exception thrown in AzureEnvironmentsManager.ts while calling `addCustomAadProviderFromManagementEndpoint`

**Comment by JasonYeMSFT** [comment]
For users who run into this issue, please go back and re-add with the correct ARM endpoint.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main 20211009.1. Fixed.
