### ISSUE TITLE
It navigates to the versions/snapshots view after resetting the tag query if managing versions/snapshots previously

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4943]
**Storage Explorer Version**: 1.21.1
**Build Number**: 20210918.4
**Branch**: hotfix/1.21.1
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one non-ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Click 'Manage History -> Manage Versions/Manage Snapshots'.
4. Click 'Back' to exit versions/snapshots view.
5. Open view options panel -> Select 'Tag Query' -> Click 'Apply' -> Click 'Reset'.
6. Observe the address bar -> Check whether back to the blob container view.

## Expected Experience ##
Back to the blob container view.

## Actual Experience ##
Navigate to the versions/snapshots view.
![issue1](https://user-images.githubusercontent.com/41351993/133878919-0c76c4f6-f6ae-48c9-9615-cf522b823b38.gif)

**Comment by JasonYeMSFT** [comment]
This is by design. Going back from the snapshot to parent directory don't add a segment to the history.
