### ISSUE TITLE
'Hot' is always selected in the 'Update Access Tier' dialog when selecting more than one blob at the same time

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#4946]
**Storage Explorer Version:** 1.21.1
**Build Number**: 20210918.4
**Branch:** hotfix/1.21.1
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture:** ia32\x64
**How Found:** Exploratory testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload two blobs and set the access tier to 'Cool'.
3. Click 'Select All -> Select All in Page'.
4. Right click two blobs -> Click 'Change Access Tier'.
5. Check whether 'Cool' is selected in the 'Update Access Tier' dialog.

## Expected Experience ##
'Cool' is selected.

## Actual Experience ##
'Hot' is selected.

**Comment by JasonYeMSFT** [comment]
This is by design. When multiple blobs are selected, in case there are blobs with different tiers in the selection, we don't care what they are and always select Hot by default.
