### ISSUE TITLE
A user with the following RBAC (Storage Blob Data Contributor) should perform a copy/rename

### ISSUE THREAD

**Issue by GMarckofff** [microsoft/AzureStorageExplorer#4948]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

A user with IAM READER level on storage account and full rights on the content of a container (Read, write, exec) can't copy/paste  folder and files

### Desired Solution

Allow copy/paste on folder and files

**Comment by JasonYeMSFT** [comment]
I assume you are seeing the Copy button disabled when you are using Azure AD credential to access your ADLS Gen2 data. The reason of disabling the button is explained in https://github.com/Azure/azure-storage-azcopy/issues/1304 and https://github.com/microsoft/AzureStorageExplorer/issues/3992.

If that's the case, we will be tracking this feature request in #3992. If not, please reopen the issue and elaborate on your case.
