### ISSUE TITLE
Remove CosmosDB from Storage Explorer documentation

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#4949]
We need to remove the CosmosDB section in this doc:  https://docs.microsoft.com/en-us/azure/vs-azure-tools-storage-manage-with-storage-explorer?tabs=windows

**Comment by MRayermannMSFT** [comment]
Draft PR ready for right before we ship: https://github.com/MicrosoftDocs/azure-docs-pr/pull/180770
