### ISSUE TITLE
Add a setting or heuristic to disable the "untrusted extension"  popup

### ISSUE THREAD

**Issue by RocketPop** [microsoft/AzureStorageExplorer#4953]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

When downloading files with no extension the "untrusted extension" popup is pointless and adds friction. (i.e. when the filename is a GUID or some generated key)

### Desired Solution

I would like to see a toggle to disable this feature.

### Alternatives and Workarounds

Alternatively if you detect no file extension, don't prompt me.

### Additional Context

I'm an adult, I can click any file I please. I click things for a living and this is a tool for professionals :)

**Comment by JasonYeMSFT** [comment]
You can just add a "" in the trusted file extension for files without a extension. Like this,
![image](https://user-images.githubusercontent.com/39359541/134387170-0e772890-014a-43eb-bc1f-4f81cd797491.png)

**Comment by RocketPop** [comment]
Ah, that's a nice workaround - thanks for the quick answer! Perhaps this could be automatic since this behavior is not documented?

**Comment by MRayermannMSFT** [comment]
@RocketPop we'll consider adding no extension to the default list. If we don't then we'll make sure the format for "no extension" is included in the example.

**Comment by JasonYeMSFT** [comment]
I added a tip in the description to inform the users that a "" can tell Storage Explorer to trust files without an extension.
