### ISSUE TITLE
Fail to upload one folder when the 'Destination directory' field value is '//'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4954]
**Storage Explorer Version**: 1.21.1
**Build Number**: 20210921.5
**Branch**: hotfix/1.21.1
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Bug Descriptions ##
Fail to upload more than one file at the same time/one folder when the 'Destination directory' field value is '//'.

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Click 'Upload -> Upload Folder...'.
3. Select one folder -> Type '/' into the 'Destination directory' field -> '//' displays in the 'Destination directory' field.
4. Click 'Upload' -> Check whether succeed to upload.

## Expected Experience ##
Succeed to upload.

## Actual Experience ##
Fail to upload.
![image](https://user-images.githubusercontent.com/41351993/134309316-e566c435-5fa0-4b3c-987c-427bfe77c599.png)

## Additional Context ##
1. Here is the AzCopy log.
[265a63d2-4889-5a44-74c6-37c3eb70830b.log](https://github.com/microsoft/AzureStorageExplorer/files/7209112/265a63d2-4889-5a44-74c6-37c3eb70830b.log)
2. This issue doesn't reproduce when uploading only one file.
![image](https://user-images.githubusercontent.com/41351993/134311000-bbf7af65-d97b-4ab0-beba-1e3c72cf59ed.png)

**Comment by MRayermannMSFT** [comment]
Let's:
1. Consider looking for consecutive slashes in dst directory text box when uploading to file shares
2. We should probably see what's going on in the single file case, and open a bug against AzCopy? The behavior may be unintentional on their part.

**Comment by v-xianya** [comment]
Verified on the build main/20211220.2. Fixed.
For file shares/ ADLS Gen2. The '//' is not supported in the destination directory field.
![image](https://user-images.githubusercontent.com/41351993/146724471-a78ade41-37fb-4381-88a9-050659c9ecee.png)
