### ISSUE TITLE
It is hard to see the string 'Current' under file share snapshots view

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4955]
**Storage Explorer Version**: 1.21.1
**Build Number**: 20210921.5
**Branch**: hotfix/1.21.1
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Change the theme to 'Dark'.
2. Expand one storage account -> File Shares.
3. Create a file share -> Click 'View Share Snapshots'.
4. Check whether it is easy to see the string 'Current' in the context view.

## Expected Experience ##
It is easy to see the string 'Current' in the context view.

## Actual Experience ##
It is hard to see the string 'Current' in the context view.
![image](https://user-images.githubusercontent.com/41351993/134318552-3af80512-66f6-4cfa-bb0d-5312fdc40abb.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20211208.5. Fixed.
