### ISSUE TITLE
Nothing happens when trying to paste one deleted disk

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4956]
**Storage Explorer Version**: 1.21.1
**Build Number**: 20210921.5
**Branch**: hotfix/1.21.1
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand 'Disks' node -> Open one resource group.
2. Upload one disk -> Copy the disk.
3. Delete the disk -> After the disk is successfully deleted.
4. Click 'Paste' -> Click 'Paste' on the 'Paste Disk' dialog.
5. Check whether there is a failed activity log.

## Expected Experience ##
There is a failed activity log.

## Actual Experience ##
Nothing happens.

**Comment by MRayermannMSFT** [comment]
Should now see this:
![image](https://user-images.githubusercontent.com/21112697/135682913-9a1f7250-283e-4949-b996-3121ad71502f.png)
