### ISSUE TITLE
Open in Explorer shows "currently filtered out" message despite all subscriptions being enabled.

### ISSUE THREAD

**Issue by Kolichikov** [microsoft/AzureStorageExplorer#4959]
(copied this from #220)
Storage Explorer Version: 1.21.1

Platform: Windows
Architecture: ia32
Build Number: 20210921.5
Commit: 66118044b

Steps to Reproduce:
Navigate through the Azure portal to a storage account.
In the storage account, click the button/link to 'Open in Explorer'.
Expected Experience:
The Azure Storage Explorer is expected to open and automatically show the storage account that was selected in the portal.

Actual Experience:
The Azure Storage Explorer opens and shows the message 'The subscription for this resource is currently filtered out. You need to select the subscription in the account settings panel to see the resource.'
Pressing Select does nothing, and every subscription seems to be enabled.

The explorer used to work fine, and is still working fine on another machine (1.20.1, Build 20210720.10)

**Comment by jinglouMSFT** [comment]
Thanks for the report. We'll look into this.

**Comment by MRayermannMSFT** [comment]
@Kolichikov clicking "select" should be taking you to the account management panel where you can select your subscription. 

Can you please confirm:
- Clicking select is not taking you to the account panel (see below screenshot).
- The subscription is definitely selected whenever you do go the account panel. Verify by looking for the subscription with the same ID and making sure there is a check mark in its box (see below screenshot).

![image](https://user-images.githubusercontent.com/21112697/135357113-932015dd-507d-4cc6-bb2a-59f777b12af7.png)

![image](https://user-images.githubusercontent.com/21112697/135357289-de480a3c-e0eb-468e-8a6f-76b5300e70e3.png)

**Comment by mechdeveloper** [comment]
I am facing the same issue, subscription is selected but unable to see the storage account -

![image](https://user-images.githubusercontent.com/35438333/140649100-c9796bf8-bbc1-4ebd-837b-60c2c12627c1.png)

Storage account is not visible in storage explorer -
![image](https://user-images.githubusercontent.com/35438333/140649129-2d603864-df96-49d7-905b-53bd4d5bbe77.png)

Storage account is present and visible in azure portal -
![image](https://user-images.githubusercontent.com/35438333/140649187-bb8973c8-4cb7-4c55-a43a-600ae648da58.png)

When I try to open storage explorer from Azure Portal 
![image](https://user-images.githubusercontent.com/35438333/140649226-8e3e2638-71d3-4324-b2c3-6c1cae3b0d4b.png)

I get this message in Storage Explorer -
![image](https://user-images.githubusercontent.com/35438333/140649259-b6a3a626-69bc-4e18-b7ad-dc6293fbfa05.png)


When I choose select I can see all teneants and subscriptions are selected
![image](https://user-images.githubusercontent.com/35438333/140649319-2f36a7f4-a593-4264-ae00-2d524faecd22.png)

Storage Explorer Version -
![image](https://user-images.githubusercontent.com/35438333/140649337-08604565-53e8-4ea0-a7c5-0e00f30563bc.png)

**Comment by MRayermannMSFT** [comment]
@mechdeveloper so given your update:

> After waiting for about 30-45 minutes finally I can see the storage account in storage explorer -

Are you all good? I was about to come close this issue since the original poster never got back to me, but if you need help I'm here!

**Comment by mechdeveloper** [comment]
@MRayermannMSFT thanks a ton for your support, I am all good for now, but storage explorer took significant time to show me my storage account, also was giving incorrect message that subscription is filtered out, probably this needs to be better as it confuses end-user 🙂.

**Comment by MRayermannMSFT** [comment]
> @MRayermannMSFT thanks a ton for your support, I am all good for now, but storage explorer took significant time to show me my storage account, also was giving confusing message that subscription is filtered out, probably this needs to be better as it confuses end-user 🙂

Yes, the deep link experience needs some significant TLC. We have a feature coming up in 1.23 which adds a new type of deeplink. I'm hoping that we'll also be able to fix up the existing deep link type at the same time. Thanks for the feedback. :)

**Comment by dev0nizer** [comment]
Hi there, I'm on 1.24.3 and experiencing the same issue. I have added two new storage accounts and none of them is showing in the explorer. The older ones that were added months before work fine.
I tried cheching this on another computer and everything shows up fine, so I have no idea what's wrong. Tried reinstalling the app and re-login about 99999 times.
