### ISSUE TITLE
Missing "Set Default Access Tier" option for attached GPV2/Blob account

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#496]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180724.5
**Commit**: 2605f1c9
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Choose one GPV2/Blob account then attach it with connection string.
2. Right click the attached account and check the context menu.

#### Expected Experience: ####
'Set Default Access Tier' displays on the context menu.

#### Actual Experience: ####
No 'Set Default Access Tier' display on the context menu.

**Comment by craxal** [comment]
Please provide the connection string used when attaching resources!

Regardless, setting the access tier is a management-level operation. Attached connections don't have management endpoint information, so you can't set the access tier this way.

**Comment by v-xuanzh** [comment]
Got it. Thanks for your updates.
