### ISSUE TITLE
The file share snapshots do not auto display when creating snapshots under the snapshots view

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4960]
**Storage Explorer Version**: 1.22.0-dev
**Build Number**: 20210923.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: Ad-hoc testing
**Regression From**: Previous release (1.21.1)

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Click 'View Share Snapshots'.
3. Create a snapshot for the file share -> Check whether the snapshot auto displays.

## Expected Experience ##
The snapshot auto displays.

## Actual Experience ##
The snapshot doesn't auto display.

## Additional Context ##
1. The snapshot displays after manfully refreshing.
2. The (read-only snapshot) view doesn't auto display under the context dropdown view after creating snapshot for one file share.
![image](https://user-images.githubusercontent.com/41351993/134467003-cf6b79dd-56ac-4097-8b20-984451b2c30d.png)
3. Related issue: [63](https://github.com/microsoft/AzureStorageExplorer/issues/63).

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20210928.2. Fixed
