### ISSUE TITLE
The localized string 'Add new clause' shows in two lines after clicking 'Query' in tables

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#4962]
**Storage Explorer Version:** 1.22.0-dev
**Build Number:** 20210923.3
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture:** ia32\x64
**Language:** Czech/ German/ Spanish/ French/ Hungarian/ Italian/ Dutch/ Polish/ Portuguese/ Russian/ Turkish 
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Español' -> Restart Storage Explorer.
3. Expand one storage account -> Tables.
4. Open one table -> Click 'Query'.
5. Check whether the string 'Add new clause' shows correctly.

## Expected Experience ##
The string 'Add new clause' shows correctly.

## Actual Experience ##
The string 'Add new clause' shows in two lines.
![image](https://user-images.githubusercontent.com/87792676/134476656-4003384b-b1a3-41f7-a9e3-37c4b170330d.png)

**Comment by v-xianya** [comment]
Verified this issue on the build main 20220415.4. Fixed.
