### ISSUE TITLE
It would be better to prevent pasting a blob which name is space to one ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#4963]
**Storage Explorer Version:** 1.22.0-dev
**Build Number:** 20210923.3
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture:** ia32\x64
**How Found:** Ad-hoc testing
**Regression From:** Not a regression

## Bug description ##
If pasting a regular blob which name is space to one adls gen2 blob container, actions 'Delete' & 'Rename' & 'Move' will fail for the pasted blob.

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Clone the blob with the name space.
4. Right click the cloned blob -> Click 'Copy'.
5. Paste the blob to one ADLS Gen2 blob container.
6. Check whether the pasted behavior is prevented.

## Expected Experience ##
It would be better to prevent pasting a blob which name is space to one ADLS Gen2 blob container.

## Actual Experience ##
 The pasted behavior is not prevented.

## Additional Context ##
Related bug: [3119](https://github.com/microsoft/AzureStorageExplorer/issues/3119)

**Comment by MRayermannMSFT** [comment]
Going to won't fix for now. I reviewed our conversations with the service team regarding but #3119 and it turns out whitespace only named files are also not supported. If a user comes and complains that we allowed them to get in this situation we can look into more proactive measures.
