### ISSUE TITLE
Failed to delete huge table

### ISSUE THREAD

**Issue by Cage-e** [microsoft/AzureStorageExplorer#4964]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.20.1

### Architecture

x64

### Platform

Windows

### Bug Description

I have a table with around a million rows on the emulator. Trying to delete the table, it fails with the following error:
Details:
Operation could not be completed within the specified time.

### Steps to Reproduce

1. create a table with a million or two rows. 
2. delete table by right clicking on it explorer

### Actual Experience

Failed to delete table.

**Comment by MRayermannMSFT** [comment]
@Cage-e which emulator are you using?

**Comment by Cage-e** [comment]
I think I've already answered it in the body of the issue or I don't understand what you mean? 
Microsoft Azure Storage Explorer on Windows

**Comment by MRayermannMSFT** [comment]
@Cage-e are you using Azurite or the .NET Microsoft Storage Emulator?

**Comment by kian-beetroot** [comment]
Microsoft Azure Storage Emulator v5.1

**Comment by jinglouMSFT** [comment]
It's likely a timeout issue, possibly on the emulator side.  Have you tried to use the Emulator command line to clear the table?  The command is AzureStorageEmulator.exe clear [table].  You can find more info here:  https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator
Windows storage emulator is now deprecated as you can see from the doc linked above.  The SDK team and us recommend using Azurite instead. The latest release of Azurite does support Tables.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having issues you can either:
- open an Azure support ticket via the portal
- open a new issue here
Thanks.
