### ISSUE TITLE
The filter string in the address bar overflows when switching back from the snapshots/versions view

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4966]
**Storage Explorer Version**: 1.22.0-dev
**Build Number**: 20210924.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob with a tag.
3. Open the view options panel -> Select 'Tag Query -> input the blob's tag' -> Click 'Apply'.
4. Hide the view options panel -> Resize the blob editor until the '=' displays as '...' in the address bar.
5. Click 'Manage History -> Manage Snapshots/Versions' -> Click 'Back'.
6. Check the filter string in the address bar doesn't overflow.

## Expected Experience ##
The filter string in the address bar doesn't overflow.

## Actual Experience ##
The filter string in the address bar overflows.
![image](https://user-images.githubusercontent.com/41351993/134643687-d8943872-c438-4a86-9583-5ae75ba1800a.png)

## Additional Context ##
1. This issue also reproduces when using "Search by prefix".
![image](https://user-images.githubusercontent.com/41351993/134651534-e77077d4-fa6f-4de4-928b-19fc91be7be7.png)

2. Here is the record:
![record](https://user-images.githubusercontent.com/41351993/134644720-46129855-508e-486a-bfbc-e094c018c963.gif)

**Comment by JasonYeMSFT** [comment]
I have re-implemented the address bar and it seems to have fixed this problem. Could you please help verify?

**Comment by v-xianya** [comment]
Verified this issue on the build main/20211215.5. Do not reproduce.
