### ISSUE TITLE
AzureStorageExplorer keeps crashing randomly

### ISSUE THREAD

**Issue by Jigar191089** [microsoft/AzureStorageExplorer#4967]
My azure storage explorer keeps crashing randomly. I have observed that this happens when I have copied some text from say like xls file or chrome. I am using the latest version

**Comment by JasonYeMSFT** [comment]
@Jigar191089 Which OS are you on. Also what do you mean by crashing? Is Storage Explorer prompting an error dialog and suggest you to close the app? If so, what does the error message say?

**Comment by Jigar191089** [comment]
I am on WIndows 10 Enterprise 64 bit version. I observed that it doesn't crashes but get stuck and then after sometime it turns normal.
![image](https://user-images.githubusercontent.com/57526133/135057745-4003bcd3-2723-47de-8d89-633657d22afa.png)

**Comment by Jigar191089** [comment]
Also when this happens at that time my copy-paste stops working and it starts only after the storage explorer has returned to normal state

**Comment by MRayermannMSFT** [comment]
@Jigar191089 can you give us an example of what you are copy and pasting? Please:

- Take a screenshot of the selection in whatever app (excel or chrome) you are copying from and share that as a reply to this issue
- Paste the selection as well as a reply to this issue
