### ISSUE TITLE
There is no error when typing an invalid query in the text editor for one emulator table

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#4970]
**Storage Explorer Version:** 1.22.0-dev
**Build Number:** 20210924.14
**Branch:** hotfix/1.21.2
**Platform/OS:** Windows 10
**Architecture:** ia32\x64
**Emulator Version:** Azurite 3.14.0
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Install and start Azurite 3.14.0.
2. Launch Storage Explorer -> Expand 'Local & Attached -> Storage Accounts -> (Emulator - Default Ports)(Key)'.
3. Right click the 'Tables' node -> Create a table.
4. Click 'Query' -> Click 'Text editor'.
5. Input an invalid query in the text editor -> Click 'Execute query (F5)'.
6. Check whether there is an error.

## Expected Experience ##
There is an error.
![image](https://user-images.githubusercontent.com/87792676/134802058-8dd0eb37-f0dd-429f-b3a4-ce9c82610ac7.png)

## Actual Experience ##
There is no error.
![image](https://user-images.githubusercontent.com/87792676/134802050-70809785-c0a2-49d3-a8b8-ce8ac2857f15.png)

**Comment by MRayermannMSFT** [comment]
Pretty sure this is a bug in Azurite? I think we validate custom queries as part of sending the query to the server. If that's true, then it looks like Azurite probably isn't returning the right error for an invalid query. Let's verify this is the case, and if so we can open a bug against Azurite.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20211119.4, it reproduces, so we are going to re-open it.
![image](https://user-images.githubusercontent.com/87792676/142558923-67eecbf8-3ffc-4e85-b525-9054f03e53a8.png)

**Comment by craxal** [comment]
Yeah, looks like this is still an Azurite issue, as this doesn't reproduce for regular Azure tables. I've opened Azure/Azurite#1185.

**Comment by craxal** [comment]
This is resolved as of Azurite 3.17.1.

**Comment by v-kellyluo** [comment]
Will verify this bug when the bug https://github.com/microsoft/AzureStorageExplorer/issues/5721 got fixed.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220516.1 with Azurite 3.17.1. Fixed.
