### ISSUE TITLE
Copy between Azure Files and Blob/ADLS Gen2

### ISSUE THREAD

**Issue by yuharucan** [microsoft/AzureStorageExplorer#4971]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I' am unable to copy files/directories between Azure Files and Blob/ADLS Gen2  by Storage Explorer.

### Desired Solution

I'd like Storage Explorer to support copy files/directories between Azure Files and Blob/ADLS Gen2.

### Alternatives and Workarounds

It is supported to copy files/directories between Azure Files and Blob/ADLS Gen2  by AzCopy.

**Comment by JasonYeMSFT** [comment]
We are going to support copying blobs/files among blob containers, ADLS Gen2 containers and file shares on the explorer side. The container level copy will still be limited to the same type of service.
