### ISSUE TITLE
Remove dependencies on Daytona

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#4972]
Now we have our own ways for the theming and accessibility requirements, let's remove the dependencies on Daytona.
Per agreement, this needs to be done by the end of June 2022

**Comment by MRayermannMSFT** [comment]
Marshalers
- [ ]TelemetryMarshaler
- [ ] EnvironmentMarshaler
- [ ] AzureMarshaler
- [ ] AzureFileMarshaler
- [ ] AzureBlobMarshaler

Views
- [ ] ActivityLog
- [ ] TreeView
- [ ] Gen1 Explorer
- [ ] Gen2 Explorer
- [ ] File Share Explorer
- [ ] Table Explorer

**Comment by MRayermannMSFT** [comment]
Closing this group issue. Separate work item exists for the tree view and we've moved to our fork. No need for this group issue.
