### ISSUE TITLE
Cannot access azure table with Storage Table Data Reader

### ISSUE THREAD

**Issue by ShimmiDemi** [microsoft/AzureStorageExplorer#4973]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.1

### Architecture

x64

### Platform

Windows

### Bug Description

Added our security group as the role of Storage Table Data Reader in the storage access control, but still can't access the table storage.

### Steps to Reproduce

1. Launch the storage explorer.
2. find the subscription -> storage account -> tables
3. no access to the tables.

### Actual Experience

1. Launch the storage explorer.
2. find the subscription -> storage account -> tables
3. no access to the tables.

**Comment by MRayermannMSFT** [comment]
@ShimmiDemi this is expected right now. We do not yet support RBAC for Tables. We are in the process of completing this work. You can track progress of that here: #4542

**Comment by ShimmiDemi** [comment]
@MRayermannMSFT , thanks for your response, do you have an ETA when it is available?
