### ISSUE TITLE
There is an extra '>' in the address bar of the split tab for an ADLS Gen1 explorer if backing to the root from one directory in the original bar before splitting it

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4974]
**Storage Explorer Version**: 1.21.2
**Build Number**: 20210924.14
**Branch**: hotfix/1.21.2
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.5.2
**Architecture**: ia32\x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand the node 'Data Lake Storage Gen1' node -> Open one adls gen1 account.
2. Click 'New Folder' -> Keep the default name -> Click 'OK'.
3. It navigates to the folder path -> Click 'Back' to the root.
4. Split the tab -> Observe the split tab.
5. Check there is no extra '>' in the address bar.

## Expected Experience ##
There is no extra '>' in the address bar.

## Actual Experience ##
There is an extra '>' in the address bar.
![image](https://user-images.githubusercontent.com/41351993/135050111-3114fd3d-6a86-4e73-8bac-d1d7043fc605.png)

**Comment by MRayermannMSFT** [comment]
Fix if/when someone encounters this.

**Comment by JasonYeMSFT** [comment]
Clicking on the segment before the extra '>' can quickly workaround this issue and make everything work again.
