### ISSUE TITLE
The split tabs are inconsistent after creating a folder if applying 'Filter by prefix' previously

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#4975]
**Storage Explorer Version:** 1.21.2
**Build Number:** 20210924.14
**Branch:** hotfix/1.21.2
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.5.2
**Architecture:** ia32\x64
**How Found:** Ad-hoc testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Open the view options panel.
3. Select 'Prefix' -> Type a letter to the 'Filter by prefix' box. 
4. Hide the view options panel.
5. Click 'New Folder' ->  Keep the default name -> Click 'OK'.
6. Split the tab.
7. Observe the split tabs -> Check whether they are consistent.

## Expected Experience ##
They are consistent.

## Actual Experience ##
They are inconsistent.
![image](https://user-images.githubusercontent.com/87792676/135055155-134da8ff-ef19-4596-95cf-f4276d66950a.png)

**Comment by MRayermannMSFT** [comment]
@v-kellyluo this is by design. When you do a split, we do not preserve the full path history/path segments.
