### ISSUE TITLE
A11y_Azure Tools Storage Explorer_ Manage Access policies_ Keyboard: Keyboard focus is not going to "Learn more about access policy permissions" link in the "Manage Access policies" dialog box.

### ISSUE THREAD

**Issue by v-inanda** [microsoft/AzureStorageExplorer#4977]
### GitHubTags:
#A11yTCS;#A11ySev2;#A11yWCAG;#DesktopApp;#Azure Tools Storage Explorer;#BM-AzureToolsStorageExplorer-Win32-Sep2021;#WCAG2.1.1;#Keyboard;#Benchmark;#Win32

### Environment Details:​
Application Name: Azure Tools Storage Explorer
Windows Version: Windows 10

### Repro Steps:​
1.Open Azure Tools Storage Explorer
2.Tab till the "Blob containers" and press Enter.
3.Right click on any existing blob container.
4.Tab till "Manage Access policies" and press enter.
5.Verify whether the keyboard focus is going to "Learn more about access policy permissions" link or not.

### Actual Result:
keyboard focus is not going to "Learn more about access policy permissions" link in "Manage Access policies" dialog box .

### Expected Result: ​
keyboard focus should go to "Learn more about access policy permissions" link in "Manage Access policies" dialog box .

### User Impact:
Keyboard users will find difficult in finding the "Learn more about access policy permissions" link if the keyboard focus is not going to "Learn more about access policy permissions" link in "Manage Access policies" dialog box .

### Attachments:
![A11y_Azure Tools Storage Explorer_ Manage Access policies_ Keyboard Keyboard focus is not going to Learn more about access policy permissions link in the Manage Access policies dia](https://user-images.githubusercontent.com/91525824/135076255-44e87044-ffca-45eb-82f3-159a9fb08c78.gif)

**Comment by MRayermannMSFT** [comment]
Related https://github.com/microsoft/AzureStorageExplorer/issues/4976

**Comment by Latha2564** [comment]
Closing this bug as it is an Electron App .For Electronic apps no need to log AI bugs

**Comment by v-inanda** [comment]
Regressed the bug in the Version :1.22.0-dev
AzCopy version: 10.12.2
The issue is fixed so closing the bug. Please find the attachment for reference.
![4977_Fix](https://user-images.githubusercontent.com/91525824/138219053-64137f43-f5eb-4539-8d21-5c9c8df17a09.gif)

**Comment by Sobi261** [comment]
#Closed;
