### ISSUE TITLE
A11y_Azure Tools Storage Explorer_SAS URL_AI4D: (StorageExplorer/text ' ') The Name property must not contain only space characters.

### ISSUE THREAD

**Issue by v-kanve** [microsoft/AzureStorageExplorer#4978]
**GitHubTags**

#A11yTCS;#A11ySev2;#A11yWCAG;#DesktopApp;#AI4D;#Azure Tools Storage Explorer;#BM-AzureToolsStorageExplorer-Win32-Sep2021;#WCAG4.2.1;#Benchmark;Win32;#A11yAuto;

**Environment Details:**
Application Name: Azure Tools Storage Explorer
Windows Version: Windows 10

**Note section**
This issue is also observed in Toggle Explorer Pane - Tree View and Add Manage Access Policies

**Repro Steps:**
1.Open Azure Tools Storage Explorer
2.Tab till the "Blob containers" and press Enter.
3.Click on any existing blob container.
4.Navigate to "Upload" button and Upload a blob/file by using "Upload Files" control.
5. Blob gets uploaded, right click on blob and select "Get Shared Access Signature" control and hit enter. Navigate to "Create" button and hit enter.
6.Open AI4D and Verify

**Element path:** 
text ' '

**Issue Details:** 
The Name property must not contain only space characters. [Section 508 502.3.1](https://www.access-board.gov/ict/#502-interoperability-assistive-technology)

**How To Fix:** 
Provide a UI Automation Name property that concisely identifies the element.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information and download this tool at https://aka.ms/AccessibilityInsights.

![Screenshot (862)](https://user-images.githubusercontent.com/83453606/135080900-564eeeb1-3e38-4c9c-96e9-69a0cd5b9890.png)

**Comment by MRayermannMSFT** [comment]
I think the `display: table` we have is messing things up.

**Comment by Latha2564** [comment]
Closing this bug as it is an Electron App .For Electronic apps no need to log AI bugs

**Comment by MRayermannMSFT** [comment]
Oh ok. That works too!

**Comment by Sobi261** [comment]
#closed
