### ISSUE TITLE
A11y_Azure Tools Storage Explorer_SAS URL_AI4D : (StorageExplorer/button 'Copy') Focusable sibling elements must not have the same Name and LocalizedControlType.

### ISSUE THREAD

**Issue by v-inanda** [microsoft/AzureStorageExplorer#4979]
### GitHubTags:
#A11yTCS;#A11ySev2;#A11yWCAG;#DesktopApp;#AI4D;#A11yAuto;#Azure Tools Storage Explorer;#BM-AzureToolsStorageExplorer-Win32-Sep2021;#WCAG 4.1.2;#Benchmark;#Win32

### Environment Details:​
Application Name: Azure Tools Storage Explorer
Windows Version: Windows 10

### Repro Steps:​
1.Open Azure Tools Storage Explorer
2.Tab till the "Blob containers" and press Enter.
3.Click on any existing blob container.
4.Navigate to "Upload" button and Upload a blob/file by using  "Upload Files" control.
5. Blob gets uploaded, right click on blob and select "Get Shared Access Signature" control and hit enter. Navigate to "Create" button and hit enter.
6.Open AI4D and Verify.

### **Element path:
button 'Copy'

### **Issue Details:
Focusable sibling elements must not have the same Name and LocalizedControlType. [WCAG 4.1.2](https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-rsv.html)

### **How To Fix:
Provide unique names for sibling controls that have the same ControlType property.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information and download this tool at https://aka.ms/AccessibilityInsights.

### Attachment:
![A11y_Azure Tools Storage Explorer_SAS URL_AI4D  (StorageExplorerbutton 'Copy') Focusable sibling elements must not have the same Name and LocalizedControlType](https://user-images.githubusercontent.com/91525824/135078990-e7a552b9-13c7-4d63-b605-23142c09523d.PNG)

**Comment by Latha2564** [comment]
Closing this bug as it is an Electron App .For Electronic apps no need to log AI bugs

**Comment by MRayermannMSFT** [comment]
Oh ok, that works too!

**Comment by Sobi261** [comment]
#Closed;
