### ISSUE TITLE
No prompt pops up when expanding the attached local account without installing storage emulator

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#498]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180724.5
**Commit**: 2605f1c9
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Make sure the storage emulator is not installed or started.
2. Open 'Connect' dialog -> Select 'Attach to a local emulator' ->'Connect'.
3. Try to expand the attached local account.

#### Expected Experience: ####
Pop up the prompt like 'you need to install or start storage emulator'.

#### Actual Experience: ####
No prompt pops up and keeps loading long time after expanding the attached local account.

**Comment by v-xianya** [comment]
Fixed on the build main/20211125.2.
![image](https://user-images.githubusercontent.com/41351993/143410437-613cb7fb-3299-43e1-ab1d-644a9a9332f5.png)
