### ISSUE TITLE
A11y_Azure Tools Storage Explorer _Get Shared Access Signature_ Usability: No status message appear on the screen if the Start date is selected as future date compared to Expiry date in "Get Shared Access Signature "dialog box

### ISSUE THREAD

**Issue by Latha2564** [microsoft/AzureStorageExplorer#4984]
### GitHubTags:
#A11y_Azure Tools Storage Explorer; #A11ySev4; #A11yTCS; #A11yUsable; #DesktopApp; #Azure Tools Storage Explorer; #MAC; #BM-AzureToolsStorageExplorer-MAC-Sep2021; #AINotInScope;

### Environment Details:​
Application Name: Azure Tools Storage Explorer
Standard Violated: Usable

### Repro Steps:​
1.Open Azure Tools Storage Explorer
2.Tab till the "Blob containers" and press Enter.
3.Right click on any existing blob container.
4.Tab till "Get Shared Access Signature" and press enter.
5.Verify whether any status message is appear on the screen if the "start date" is selected as future date compared to "expiry date" in "Get Shared Access Signature "dialog box.

### Actual Result:
No status message is appear on the screen if the Start date is selected as future date compared to Expiry date in "Get Shared Access Signature "dialog box.

### Expected Result: ​
Status message should appear on the screen if the Start date is selected as future date compared to Expiry date in "Get Shared Access Signature "dialog box.

### User Impact:
All users may fid difficult in finding the error clearly if no status message appear on the screen if the Start date is selected as future date compared to Expiry date in "Get Shared Access Signature "dialog box.

### Attachments:
![No status message appear ](https://user-images.githubusercontent.com/89508906/135089372-bab421dc-cc39-4511-9c40-e75d19607fac.gif)

**Comment by MRayermannMSFT** [comment]
Related https://github.com/microsoft/AzureStorageExplorer/issues/4988

**Comment by v-xianya** [comment]
Fixed on the main build 20211008.1.
![image](https://user-images.githubusercontent.com/41351993/136524277-b08ebedb-c6f1-4d85-95a2-3e8b5883b754.png)

**Comment by Latha2564** [comment]
The bug is repro in the latest build version

**Comment by JasonYeMSFT** [comment]
@Latha2564 Have you had a chance to verify this bug in the new build?

**Comment by Latha2564** [comment]
<img width="688" alt="Screenshot 2021-11-22 at 11 34 31 AM" src="https://user-images.githubusercontent.com/89508906/142808903-89370a2e-0355-492b-8ab7-41fb8f7a3f7d.png">
Regressed the bug .The bug is fixed.Hence closing this bug.

**Comment by Latha2564** [comment]
<img width="688" alt="4984_Bug is fixed" src="https://user-images.githubusercontent.com/89508906/142809138-ca217f42-2dec-41cf-ad6f-1a80fd88ef2d.png">
Regressed the bug.The bug is fixed.Hence closing the bug.

**Comment by fsteffi** [comment]
GithubTags:#Closed;
