### ISSUE TITLE
A11y_Azure Tools Storage Explorer_SAS URL_AI4D: (StorageExplorer/table '') An element of the given ControlType must support the Grid pattern.

### ISSUE THREAD

**Issue by v-kanve** [microsoft/AzureStorageExplorer#4986]
**GitHubTags**

#A11yTCS;#A11ySev2;#A11yWCAG;#DesktopApp;#AI4D;#Azure Tools Storage Explorer;#BM-AzureToolsStorageExplorer-Win32-Sep2021;#WCAG4.2.8;#Benchmark;Win32;#A11yAuto;

**Environment Details**
Application Name: Azure Tools Storage Explorer
Windows Version: Windows 10

**Note Section**
This issue is also observed in Toggle Explorer Pane - Tree View and Add Manage Access Policies

**Repro Steps**
1.Open Azure Tools Storage Explorer
2.Tab till the "Blob containers" and press Enter.
3.Click on any existing blob container.
4.Navigate to "Upload" button and Upload a blob/file by using "Upload Files" control.
5. Blob gets uploaded, right click on blob and select "Get Shared Access Signature" control and hit enter. Navigate to "Create" button and hit enter.
6.Open AI4D and Verify

**App:** 
StorageExplorer

**Element path:**
 table ''

**Issue Details:** 
An element of the given ControlType must support the Grid pattern. [Section 508 502.3.10](https://www.access-board.gov/ict/#502-interoperability-assistive-technology)

**How To Fix:** 
1. Make sure the element has the appropriate ControlType property for its function.
2. If the current ControlType is correct, modify the element to support the Grid pattern.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information and download this tool at https://aka.ms/AccessibilityInsights.

![Screenshot (866)](https://user-images.githubusercontent.com/83453606/135086557-4f966088-47a9-4ed7-bf23-c297064acf24.png)

**Comment by MRayermannMSFT** [comment]
Related to #4978 , I think the `display: table` we have is messing things up.

**Comment by MRayermannMSFT** [comment]
Oh ok. That works too!

**Comment by Sobi261** [comment]
#closed;
