### ISSUE TITLE
The children items disappear after refreshing the parent node of the searched resource

### ISSUE THREAD

**Issue by v-haiz** [microsoft/AzureStorageExplorer#499]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180724.5
**Commit**: 3947e25b
**Regression From**: Not a Regression

**Steps to Reproduce**:
1. Choose a storage account -> Right click it and select 'Search From Here'.
2. Refresh the parent node **'Storage Account'** of the searched account -> Check whether the searched account exists or not.

**Expected Experience**:
The searched account still exists in the searched result.

**Actual Experience**:
The searched account disappears after refreshing the parent node of the searched account.
![expect](https://user-images.githubusercontent.com/37653604/43256448-3d86bbd0-90bc-11e8-888c-6546659e2c65.PNG)

**Comment by MRayermannMSFT** [comment]
Won't fix. Edge case of search and we also aren't fans of our current search experience...also Jason says it doesn't repro anymore. 🤷‍♀️
