### ISSUE TITLE
Typo is latest Windows Release File Name

### ISSUE THREAD

**Issue by ld0614** [microsoft/AzureStorageExplorer#4991]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.1

### Regression From

1.21.0

### Architecture

x64

### Platform

Windows

### Bug Description

The latest Release has a typo is the Windows file name which breaks out automatic download

![image](https://user-images.githubusercontent.com/20439950/135101438-1ebcacfd-426d-4b10-b2e8-ea93574de93d.png)

is it possible to update the name of the release asset please?

### Steps to Reproduce

Attempt to download the package Windows_**S**torageExplorer.exe

### Actual Experience

No Release Found

### Expected Experience

Release Found

**Comment by MRayermannMSFT** [comment]
@ld0614 we've changed the file name. Please let us know if you still see it as broken.

**Comment by ld0614** [comment]
Thanks for the fix, its working now 😄
