### ISSUE TITLE
Blob Container: duplicate file/folder

### ISSUE THREAD

**Issue by keen85** [microsoft/AzureStorageExplorer#4997]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

When copy and pasting a file within a blob container from/to the same folder, an error occurs. 

### Desired Solution

I'd like the same behaviour as in Windows Explorer: the file/folder would be duplicated and the file/folder name would receive a suffix (like "_copy")

### Alternatives and Workarounds

Create a temporary folder, copy the desired file/folder to the temp folder, rename the file/folder, move the duplicated file/folder to it's target location, remove the temp folder

**Comment by MRayermannMSFT** [comment]
@keen85 can you try using clone?
![image](https://user-images.githubusercontent.com/21112697/135895804-e8811650-7150-4103-9447-181e62a2e13f.png)

**Comment by keen85** [comment]
Hi @MRayermannMSFT ,

in my Azure Storage Explorer 1.20.1 installation, this button is not present:
![image](https://user-images.githubusercontent.com/29750255/135900845-b12b7cf7-6b38-4ad9-bd8e-8e177b04f31e.png)

I'm working on a Blob Container (ADLS Gen2)

**Comment by keen85** [comment]
I just realized, that I did not have the most recent version installed. Apparently the build-in update functionality did not work.

I updated manually to 1.21.2.
However, still no "clone" button for me. Do I need to activate insider builds?

**Comment by MRayermannMSFT** [comment]
@keen85 ah ok. You are in a Gen2 storage account. We currently do not offer clone in such scenario. We will evaluate adding this in the future. :)

**Comment by keen85** [comment]
@MRayermannMSFT so, there is already a "clone file/folder" functionality in Azure Storage Explorer - but it only works for "ordinary" Blob Storage?
Why is that?

**Comment by JasonYeMSFT** [comment]
@keen85 It used to be due to us not being able to us auth credentials for the copy source. Now the limitation is gone and we have added clone/copy to gen2 storage accounts.

**Comment by keen85** [comment]
Hi @JasonYeMSFT ,
First of all: that's great news! Thank you!

However, I am still missing the "**Clone**" button as mentioned above by @MRayermannMSFT:
!(Clone)[https://user-images.githubusercontent.com/21112697/135895804-e8811650-7150-4103-9447-181e62a2e13f.png]

Yes I can **_copy_** and **_paste_** files. But I can copy and paste (= duplicate/clone) it to the same location.

**Comment by JasonYeMSFT** [comment]
I see. Apparently our user study went a little off. We thought people would always want to use the atomic "Rename" and "Move" command in ADLS Gen2 since they are efficient and don't involve copying data. I will try to add it in 1.26.0 so it can be available together with Rename and Move.

**Comment by JasonYeMSFT** [comment]
We have released our 1.26.0 on GitHub. The clone feature will be available once you upgrade.
