### ISSUE TITLE
problems in connection to the blob azure - "Cannot retrieve secondary resources." 

### ISSUE THREAD

**Issue by junjibienestar** [microsoft/AzureStorageExplorer#4999]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.18.1

### Architecture

x64

### Platform

Windows

### Bug Description

{
  "name": "RestError",
  "message": "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including th
![error blob azure](https://user-images.githubusercontent.com/88163316/135350335-74611736-5849-44ba-bfa6-47a7400caed6.png)
[error blob.txt](https://github.com/microsoft/AzureStorageExplorer/files/7255171/error.blob.txt)

### Steps to Reproduce

Trying to enter the repository, the following error appears "Cannot retrieve secondary resources." 

### Actual Experience

not loading my blob repository 

Trying to enter the repository, the following error appears "Cannot retrieve secondary resources." 
![error blob azure](https://user-images.githubusercontent.com/88163316/135352093-8951e0ea-ecf0-498c-a867-4dbd650cc98a.png)

### Expected Experience

Trying to enter the repository, the following error appears "Cannot retrieve secondary resources." 
![error blob azure](https://user-images.githubusercontent.com/88163316/135352130-53ddb356-b749-4019-a8cc-3dccc59c8468.png)

**Comment by jinglouMSFT** [comment]
Have you tried this in the latest release?  Should be version v1.21.2.  Thanks.

**Comment by junjibienestar** [comment]
Download the latest version!
the same error continues:
![error blob azure2](https://user-images.githubusercontent.com/88163316/135354718-6c6ac2e5-282a-4ae3-8da3-1f9bdcdcc470.png)

says: temporary deletion

Secondary resources cannot be recovered.

Details:
{
   "name": "RestError",
   "message": "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. \ .....

**Comment by MRayermannMSFT** [comment]
@junjibienestar it looks like you have attached with name & key or a connection string that contains the account name & key.

- When attaching/in your connection string is the name of your account spelled correctly? You can check via going to the Propiedades panel and looking at the various properties that have the name of your account in them and making sure it is spelled correctly.
- Is the key you used to attach still valid? It is possible someone rotated the keys for your storage account.
- Is the key you used to attach still valid, then make sure it is spelled correctly as well.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having issues you can either:
- open an Azure support ticket via the portal
- open a new issue here
Thanks.
