### ISSUE TITLE
View -> Account Management is spelt incorrectly

### ISSUE THREAD

**Issue by JakeRadMSFT** [Microsoft/AzureStorageExplorer#5]
Storage Explorer Version: 0.9.6

OS Version: Windows 10 (All)

Steps to Reproduce:

1. Open View Menu
2. Observe Account Mangement 

Expected Experience:
Should be Account Management

Actual Experience:
Lists Account Mangement

**Comment by MRayermannMSFT** [comment]
Fixed on master.
