### ISSUE TITLE
Expiry/Start time still display as the default time in SAS dialog after applying a set access policy

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#50]
**Storage Explorer Version:** 1.0.0(20180415.2)

**OS Version:** Windows 10/Mac/Linux

**Regression:** Works well on 0.9.6 release

**Steps to Reproduce:**

1. Launch Storage Explorer and expand Storage Accounts. 
2. Right click one blob container and select 'Manage Access Policies...'.
3. Add an access policy and modify the Start/Expiry time.
4. Right click the same blob container and select 'Get Shared Access Signature...' -> Apply the set access policy in step3.
5. Check the Start/Expiry time in the dialog.

**Expected Experience:**
The Start/Expiry time are same as the applied access policy.

**Actual Experience:**
The Start/Expiry time still display as the default time. --Please see the below attachment.
![expiry time](https://user-images.githubusercontent.com/34729022/38982229-d4ca1f7c-43b0-11e8-8fb3-30c2f5f7e210.png)

**Comment by craxal** [comment]
Looks like the problem is in the Access Policies dialog. The modified start/expiry times weren't being saved properly.
