### ISSUE TITLE
Unable to add two tables with the same name to Quick Access

### ISSUE THREAD

**Issue by JasonYeMSFT** [Microsoft/AzureStorageExplorer#500]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: WIndows 10
**Architecture**: ia32
**Regression From**: 1.3.1
#### Steps to Reproduce: ####
1. Create table named 'table1' in two storage accounts
2. Try to add both of them to Quick Access

#### Expected Experience: ####
Both of them are added. This is the behavior of 1.3.1

#### Actual Experience: ####
Once the first one gets added to Quick Access, the second one can no longer be added to Quick Access.

**Comment by craxal** [comment]
Duplicate of #493.

**Comment by craxal** [comment]
Duplicate of #493,
