### ISSUE TITLE
There is an extra active folder in the  'Active and soft deleted blobs' context after deleting a folder which contains undeleted blob

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5000]
**Storage Explorer Version:** 1.22.0-dev
**Build Number:** 20210930.3
**Branch:** main
**Platform/OS:** Windows 10//Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture:** ia32\x64
**How Found:** Exploratory testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Create a new folder.
3. Upload one blob to the folder -> Soft delete the blob.
4. Switch to 'Delete only' context ->Undelete the blob.
5. Switch to 'Active blobs (default)' context -> Delete the folder.
6. Switch to 'Active and soft deleted blobs' context.
7. Check whether there is no extra active folder.

## Expected Experience ##
There is no extra active folder.

## Actual Experience ##
There is an extra active folder.

## Additional Context ##
This issue doesn't reproduce if the folder doesn't contain undeleted blobs.

**Comment by JasonYeMSFT** [comment]
Given that ADLS Gen2 soft delete is GA now I would call this by design for now. We can re-evaluate if any customer complains.
