### ISSUE TITLE
Time out for blob container Private Endpoint

### ISSUE THREAD

**Issue by vamshisiram** [microsoft/AzureStorageExplorer#5003]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.20.1

### Architecture

x64

### Storage Explorer Build Number

20210720.10

### Platform

Windows

### OS Version

1909 windows 10

### Bug Description

Created a storage account with private endpoint, and added a private link for the private endpoint using Azure Private DNS zone in our Hub network. then when attempting to access the storage account either via azure portal or azure file storage explorer getting a time out error for the private endpoint.

Here is the catch though, i created another Storage account with same setup yesterday, and it is working fine, just the new storage account is having the issue. 

below is the error details for the new one failing:

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://accountname.blob.core.windows.net/?include=metadata&comp=list failed, reason: connect ETIMEDOUT 10.XXX.XX.XX:443",
  "stack": "FetchError: request to https://accountname.blob.core.windows.net/?include=metadata&comp=list failed, reason: connect ETIMEDOUT 10.XXX.XX.XX:443\n    (C:\\Users\\vsiram1\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1461:11)\n    at ClientRequest.emit (events.js:310:20)\n    at TLSSocket.socketErrorListener (_http_client.js:426:9)\n    at TLSSocket.emit (events.js:310:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)",
  "type": "system",
  "errno": "ETIMEDOUT",
  "code": "ETIMEDOUT"
}

### Steps to Reproduce

launch storage explorer
Connect either a storage account with connection string or just the blob container with SAS key

### Actual Experience

Created a storage account with private endpoint, and added a private link for the private endpoint using Azure Private DNS zone in our Hub network. then when attempting to access the storage account either via azure portal or azure file storage explorer getting a time out error for the private endpoint.

Here is the catch though, i created another Storage account with same setup yesterday, and it is working fine, just the new storage account is having the issue. 

below is the error details for the new one failing:

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://accountname.blob.core.windows.net/?include=metadata&comp=list failed, reason: connect ETIMEDOUT 10.XXX.XX.XX:443",
  "stack": "FetchError: request to https://accountname.blob.core.windows.net/?include=metadata&comp=list failed, reason: connect ETIMEDOUT 10.XXX.XX.XX:443\n    (C:\\Users\\vsiram1\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1461:11)\n    at ClientRequest.emit (events.js:310:20)\n    at TLSSocket.socketErrorListener (_http_client.js:426:9)\n    at TLSSocket.emit (events.js:310:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)",
  "type": "system",
  "errno": "ETIMEDOUT",
  "code": "ETIMEDOUT"
}

### Expected Experience

work as normal and see container without issue

### Additional Context

i am not trying this with latest storage explorer because the container is not accessible via azure portal too.

**Comment by MRayermannMSFT** [comment]
@vamshisiram since you are also seeing issues with the Azure portal when trying to access this account, then the issue is almost certainly out of the scope of what we can help you with. We recommend opening an Azure support ticket for private link/private endpoint:
![image](https://user-images.githubusercontent.com/21112697/135899263-d0e77d89-35d6-49cd-8d3d-27500474c8cb.png)
