### ISSUE TITLE
Cannot create a table - Emulator Default ports - Azurite

### ISSUE THREAD

**Issue by sunilsydney** [microsoft/AzureStorageExplorer#5007]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.2

### Regression From

not tried

### Architecture

x64

### Storage Explorer Build Number

20210924.14 

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Not able to create a table in a local storage account. 
Official latest docker image of Azurite is used. 
Able to create new blob and new queue using Azure Storage explorer. Only creating new table fails.

Azurite docker image: https://hub.docker.com/_/microsoft-azure-storage-azurite

### Steps to Reproduce

1. Start Azurite docker image with default settings (Please see additional context section for logs)
2. Select: Local & Attached --> Storage Accounts --> (Emulator - Defaukt ports) (key)
3. Expand it
4. Right click Blob containers --> Create Blob container (works fine)
5. Right click Queues --> Create queue (works fine)
6. Right click Tables --> Create table --> Provide name: tabletest
7. Observe that nothing happens
8. Now right click on Tables --> Refresh
9. Observe the following error message 

Unable to retrieve child resources.

Details:
Network timeout error: connect ECONNREFUSED 127.0.0.1:10002

### Actual Experience

1. Looks like the new table is not getting created
2. Getting this error in Storage explorer:
```
Unable to retrieve child resources.
Details:
Network timeout error: connect ECONNREFUSED 127.0.0.1:10002
```
Note: Primary connection string is:
AccountName=devstoreaccount1;AccountKey=_HIDDEN_;DefaultEndpointsProtocol=http;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;

### Expected Experience

1. New table gets created (just like how new blob and new queue were created)
2. The newly created table shows up in Storage explorer under  Local & Attached --> Storage Accounts --> (Emulator - Defaukt ports) (key) --> Tables

### Additional Context

**Microsoft Azure Storage Explorer**
Version: 1.21.2
AzCopy Version: 10.12.2
Platform: Windows
Architecture: ia32 
Build Number: 20210924.14 
Commit: 6b2f1e601 
Support ID: 4a143645-37c8-76d1-aea5-239570309f79 

**Azurite logs**
```
Azurite Blob service is starting at http://0.0.0.0:10000
Azurite Blob service is successfully listening at http://0.0.0.0:10000
Azurite Queue service is starting at http://0.0.0.0:10001
Azurite Queue service is successfully listening at http://0.0.0.0:10001
Azurite Table service is starting at http://0.0.0.0:10002
Azurite Table service is successfully listening at http://0.0.0.0:10002
172.17.0.1 - - [03/Oct/2021:00:09:00 +0000] "GET /devstoreaccount1?comp=properties&restype=account HTTP/1.1" 200 -

172.17.0.1 - - [03/Oct/2021:00:11:19 +0000] "GET /devstoreaccount1?comp=properties&restype=account HTTP/1.1" 200 -

172.17.0.1 - - [03/Oct/2021:00:11:19 +0000] "GET /devstoreaccount1?comp=properties&restype=account HTTP/1.1" 200 -

172.17.0.1 - - [03/Oct/2021:00:11:19 +0000] "GET /devstoreaccount1?comp=properties&restype=account HTTP/1.1" 200 -

172.17.0.1 - - [03/Oct/2021:00:11:33 +0000] "GET /devstoreaccount1?comp=properties&restype=account HTTP/1.1" 200 -

172.17.0.1 - - [03/Oct/2021:00:12:40 +0000] "GET / HTTP/1.1" 400 -

172.17.0.1 - - [03/Oct/2021:00:12:40 +0000] "GET /favicon.ico HTTP/1.1" 400 -

172.17.0.1 - - [03/Oct/2021:00:14:45 +0000] "GET /devstoreaccount1?comp=list&include=metadata HTTP/1.1" 200 -

172.17.0.1 - - [03/Oct/2021:00:14:45 +0000] "GET /devstoreaccount1/%24logs?restype=container HTTP/1.1" 404 -

172.17.0.1 - - [03/Oct/2021:00:14:45 +0000] "GET /devstoreaccount1?restype=service&comp=properties HTTP/1.1" 200 -

172.17.0.1 - - [03/Oct/2021:00:14:50 +0000] "PUT /devstoreaccount1/blob1test?restype=container HTTP/1.1" 201 -

172.17.0.1 - - [03/Oct/2021:00:14:50 +0000] "GET /devstoreaccount1/blob1test?restype=container HTTP/1.1" 200 -

172.17.0.1 - - [03/Oct/2021:00:14:50 +0000] "GET /devstoreaccount1/blob1test?comp=properties&restype=account HTTP/1.1" 200 -

172.17.0.1 - - [03/Oct/2021:00:14:51 +0000] "GET /devstoreaccount1?comp=blobs&where=%22fakeTagKey%22%3D%27fakeTagValue%27 HTTP/1.1" 400 -

172.17.0.1 - - [03/Oct/2021:00:14:51 +0000] "GET /devstoreaccount1/blob1test?comp=list&maxresults=1000&restype=container&include=metadata&delimiter=%2F HTTP/1.1" 200 -

172.17.0.1 - - [03/Oct/2021:00:15:00 +0000] "GET /devstoreaccount1?comp=list&include=metadata&timeout=30 HTTP/1.1" 200 -

172.17.0.1 - - [03/Oct/2021:00:15:05 +0000] "PUT /devstoreaccount1/q1test?timeout=30 HTTP/1.1" 201 -

172.17.0.1 - - [03/Oct/2021:00:15:05 +0000] "GET /devstoreaccount1/q1test/messages?numofmessages=32&peekonly=true&timeout=30 HTTP/1.1" 200 -

172.17.0.1 - - [03/Oct/2021:00:15:05 +0000] "GET /devstoreaccount1/q1test?comp=metadata&timeout=30 HTTP/1.1" 200 -

172.17.0.1 - - [03/Oct/2021:00:15:21 +0000] "POST /devstoreaccount1/q1test/messages?visibilitytimeout=0&messagettl=25200&timeout=30 HTTP/1.1" 201 -

172.17.0.1 - - [03/Oct/2021:00:15:21 +0000] "GET /devstoreaccount1/q1test/messages?numofmessages=32&peekonly=true&timeout=30 HTTP/1.1" 200 -

172.17.0.1 - - [03/Oct/2021:00:15:21 +0000] "GET /devstoreaccount1/q1test?comp=metadata&timeout=30 HTTP/1.1" 200 -
```

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having issues you can either:
- open an Azure support ticket via the portal
- open a new issue here
Thanks.
