### ISSUE TITLE
Microsoft Storage Explorer are not woring

### ISSUE THREAD

**Issue by ericnoarin** [microsoft/AzureStorageExplorer#5008]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

cannot open the fraud report

### Desired Solution

i dont have

### Alternatives and Workarounds

report to Service cafe

### Additional Context

no

**Comment by ericnoarin** [comment]
![StorageExplorer issue](https://user-images.githubusercontent.com/91822341/135745303-173df8c7-f5e5-4e90-b9e2-a4e25502ef36.jpg)

**Comment by SaiGuttaRocking** [comment]
+1

**Comment by MRayermannMSFT** [comment]
@ericnoarin it looks like you have attached a storage account via SAS URL.

- Is your URL correct? Did you maybe misspell the name of the account in the URL?
- Is the SAS expired?
- Does the SAS have permissions to list containers?
- Does the SAS have any sort of IP restriction?
- Can you please update to the latest version of Storage Explorer.

@SaiGuttaRocking if your error message is not exactly the same, if you are also not trying to attach a storage account via SAS URL, or if you do not work with the original issue author, please open a new issue and share the error message you are seeing. The questions we have asked above are specific to the error message shared.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having issues you can either:
- open an Azure support ticket via the portal
- open a new issue here
Thanks.
