### ISSUE TITLE
Idea/Feature: Tab re-ordering

### ISSUE THREAD

**Issue by mishal153** [microsoft/AzureStorageExplorer#501]
**Storage Explorer Version**: 1.3.1
**Platform/OS Version**: windows
**Architecture**: ia32

#### Steps to Reproduce: ####
for example when i open a blob container in a 'new tab', followed by a table in a 'new tab', followed by another blob container in a 'new tab', I could prefer to have the 2 container tabs side by side. Cannot be done as of today. 
#### Expected Experience: ####
When >1 tab is open, I should be able to drag a tab to re-order it horizontally

#### Actual Experience: ####
Tabs are always lined up in the order of opening them

**Comment by JasonYeMSFT** [comment]
We are going to track the issue in #1504. Closed.
