### ISSUE TITLE
Unable to fetch files from  Azure File Share 

### ISSUE THREAD

**Issue by SriKatakam21** [microsoft/AzureStorageExplorer#5013]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.0

### Architecture

x64

### Platform

Windows

### Bug Description

Unable to retrieve child resources.

Details:
self signed certificate in certificate chain

### Steps to Reproduce

1. Launch Storage explorer 
2. Expand storage account Unable to retrieve child resources.

Details:
self signed certificate in certificate chain

### Actual Experience

Unable to retrieve child resources.

Details:
self signed certificate in certificate chain

### Expected Experience

Unable to retrieve child resources.

Details:
self signed certificate in certificate chain

### Additional Context

Unable to retrieve child resources.

Details:
self signed certificate in certificate chain

**Comment by MRayermannMSFT** [comment]
Closing this issue due to lack of response. If you are still encountering this issue we recommend:
- trying any suggested troubleshooting steps
- opening an Azure support ticket via the portal for additional help
- opening a new issue here.
