### ISSUE TITLE
Unable to connect to Azure Storage File Share

### ISSUE THREAD

**Issue by jtorgrimson** [microsoft/AzureStorageExplorer#5016]
Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to http://127.0.0.1:10001/devstoreaccount1?comp=list&include=metadata&timeout=30 failed, reason: connect ECONNREFUSED 127.0.0.1:10001",
  "stack": "FetchError: request to http://127.0.0.1:10001/devstoreaccount1?comp=list&include=metadata&timeout=30 failed, reason: connect ECONNREFUSED 127.0.0.1:10001\n    at ClientRequest.<anonymous> (C:\\Users\\jtorgrimson\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1483:11)\n    at ClientRequest.emit (events.js:315:20)\n    at Socket.socketErrorListener (_http_client.js:469:9)\n    at Socket.emit (events.js:315:20)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
  "type": "system",
  "errno": "ECONNREFUSED",
  "code": "ECONNREFUSED"
}

**Comment by MRayermannMSFT** [comment]
@jtorgrimson this message indicates you were trying to access the blob containers node for your storage emulator. Were you indeed trying to do so? If yes, please be aware that Storage Explorer does not ship with an emulator and it does not start your emulator for you. You must do those on your own.

**Comment by MRayermannMSFT** [comment]
Closing this issue due to lack of response. If you are still encountering this issue we recommend:
- trying any suggested troubleshooting steps
- opening an Azure support ticket via the portal for additional help
- opening a new issue here.
