### ISSUE TITLE
Feature Request:  display timezone for data

### ISSUE THREAD

**Issue by Meister1867** [microsoft/AzureStorageExplorer#5026]
On some projects we're working with data that may span time zones.  When I look at "Last Modified"  I don't know if that is Universal Time, Eastern, Central, Mountain, Indian, Moscow, etc... It would be great if there was a code indicating what time zone I'm looking at.

**Comment by MRayermannMSFT** [comment]
Closing this issue due to lack of response. If you have further questions please open a new issue.
