### ISSUE TITLE
The cloned rehydrated blob doesn't auto display

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#5033]
**Storage Explorer Version**: 1.22.0-dev
**Build Number**: 20211008.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.5
**Architecture**: ia32\x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one non-ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one blob -> Change the access tier to 'Archive'.
3. Right click the archived blob -> Click 'Clone and Rehydrate'.
4. Input a valid destination blob name -> Click 'Apply'.
5. Check whether the cloned rehydrated blob auto displays.

## Expected Experience ##
The cloned rehydrated blob auto displays.

## Actual Experience ##
The cloned rehydrated blob does not auto display.

## Additional Context ##
The cloned rehydrated blob displays after manually refreshing.

**Comment by v-xianya** [comment]
@JasonYeMSFT thanks for the update!
The cloned blob displays on the split tab. is this by design?

![image](https://user-images.githubusercontent.com/41351993/136642053-dde1754a-b589-442c-873c-ff3a35fc5c09.png)

**Comment by MRayermannMSFT** [comment]
Let's make sure the activities associated with rehydrating indicate that the operation may take a long long while and it is up to the user to keep checking to see if the operation is finished.
