### ISSUE TITLE
Fail to upload one blob with the same name if there is a cloned rehydrated blob got deleted

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5034]
**Storage Explorer Version:** 1.22.0-dev
**Build Number:** 20211008.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.5
**Architecture:** ia32\x64
**How Found:** Ad-hoc testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one non-ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload two blobs -> Change one blob's access tier to 'Archive'.
3. Right click the archived blob -> Click 'Clone and Rehydrate'.
4.  Input another existing blob name -> Click 'Apply'.
5. Delete the cloned rehydrated blob.
6. Try to upload a blob which name is the same as the cloned rehydrated blob.
7. Check whether succeed to upload.

## Expected Experience ##
Succeed to upload.

## Actual Experience ##
Fail to upload.
![image](https://user-images.githubusercontent.com/87792676/136530588-69d31fa8-1884-40ea-bf42-c0f6d48aad53.png)

## Additional Context ##
1. After deleting, wait five minutes then try to upload, it still reproduces.
2. Here is the Azcopy Log:
[cfdcf97d-932e-7f40-6612-d0954b4fa72b.log](https://github.com/microsoft/AzureStorageExplorer/files/7310187/cfdcf97d-932e-7f40-6612-d0954b4fa72b.log)

**Comment by JasonYeMSFT** [comment]
The backend has some protection mechanism to prevent corrupting data that is being rehydrated. Let's wait for a day or two and see if it allows re-upload the data.

**Comment by v-kellyluo** [comment]
This issue also reproduces in the following steps:

1. Expand one storage account -> Blob Containers. (Make sure the soft delete is enabled)
2. Create a blob container -> Upload one blob.
3. Chang its access tier to 'Archive' -> Change its access tier to 'Cool'/'Hot'.
4. Delete the blob -> Upload a blob whose name is same as the deleted blob.
5. Check succeeds to upload the blob.

## Actual Experience ##
Fail to upload the blob.
![image](https://user-images.githubusercontent.com/87792676/151330428-a2ad92da-994b-462a-8f21-ee897ef15124.png)

**Comment by v-xianya** [comment]
Verified this issue on the build 20230516.9. Not allow to use an existing name to clone and rehydrate. So we are going to close it.
Refer to [6655](https://github.com/microsoft/AzureStorageExplorer/issues/6655)
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/9929b8c6-dc12-4771-88a1-16193a7d53b1)
