### ISSUE TITLE
Fail to execute the action 'Clone and Rehydrate' for one archived emulator blob

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5047]
**Storage Explorer Version:** 1.22.0-dev
**Build Number:** 20211009.1
**Branch:** main
**Platform/OS:** Windows 10
**Architecture:** ia32
**Emulator Version:** Azurite 3.14.0
**How Found:** Ad-hoc testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Install and run Azurite 3.14.0 -> Launch Storage Explorer.
2. Expand 'Local & Attached -> Storage Accounts -> (Emulator - Default Ports)(Key)' -> Blob Containers.
3. Create a blob container -> Upload one blob -> Update the access tier to 'Archive'.
4. Right click the blob -> Click 'Clone and Rehydrate'.
5. Input a valid destination blob name -> Click 'Apply'.
6. Check whether succeed to execute the action 'Clone and Rehydrate'.

## Expected Experience ##
 Succeed to execute the action 'Clone and Rehydrate'.

## Actual Experience ##
 Fail to execute the action 'Clone and Rehydrate'.
![image](https://user-images.githubusercontent.com/87792676/136650932-b16709a1-4927-496a-8a4c-9076de2e7c72.png)

## Additional Context ##
Error details:
```
  "name": "TypeError",  "message": "tags.blobTagSet is not iterable".
```

**Comment by JasonYeMSFT** [comment]
I'll hide this action in emulator explorers.

**Comment by JasonYeMSFT** [comment]
The error is about getting tags. Since I have added code to support copying bypassing tags, it is supposed to work in emulator as well. However, I found that it still doesn't https://github.com/Azure/Azurite/issues/1146. I'll disable this action in emulator as planned for now.

**Comment by v-xianya** [comment]
Verified on the build 20211102.7. Fixed.(The action is disabled)
![image](https://user-images.githubusercontent.com/41351993/140003962-01ddca7b-b4b8-4015-aec4-377b56291441.png)
