### ISSUE TITLE
Download all Blobs in Container/current directory

### ISSUE THREAD

**Issue by ld0614** [microsoft/AzureStorageExplorer#5050]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I am trying to download all blobs in a container with a single action

### Desired Solution

Either a dropdown on the download selected button to allow a Download All or when you right click on the container it offers a download all selection

### Alternatives and Workarounds

Currently the select all functionality is paginated, you have to:

1. Select the container
2. Ctrl + A
3. Select Download
4. Navigate to the next page
5. Repeat

### Additional Context

My use case is primarily revolving around the Azure Image Builder packerlog service which creates a new folder and file in a container.  I want to be able to download all of these folders to analyse the blob data locally and removing the need to manually paginate the data would make this process significantly easier

**Comment by MRayermannMSFT** [comment]
Make sure to pay attention to the conversation on https://github.com/microsoft/AzureStorageExplorer/issues/6139
