### ISSUE TITLE
Can't access any files in my subscription from Azure Storage Explorer

### ISSUE THREAD

**Issue by kaioccarvalho** [microsoft/AzureStorageExplorer#5051]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.2

### Architecture

x64

### Storage Explorer Build Number

20210924.14

### Platform

Windows

### OS Version

Windows 10

### Bug Description

When I tried to connect in my subscription (home tenant), I received this error "Could not access resources for this tenant. You may need to reauthenticate. See the error details for more information.". Then, I tried to reauthenticate twice again, but the error was still there. That's the _Error_details_ shows:

{
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"unable to get local issuer certificate\\\",\\n  \\\"stack\\\": \\\"Error: unable to get local issuer certificate\\\\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)\\\\n    at TLSSocket.emit (events.js:315:20)\\\\n    at TLSSocket._finishInit (_tls_wrap.js:932:8)\\\\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)\\\",\\n  \\\"code\\\": \\\"UNABLE_TO_GET_ISSUER_CERT_LOCALLY\\\"\\n}\""
}

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/10812374/136792983-badeda51-a4d2-4715-9180-45df3881425e.png)

### Actual Experience

I can't access all files in my subscription due to the error.

### Expected Experience

I wanna access to all files from Azure Storage Explorer.

### Additional Context

There are no additional comments.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having trouble from this issue, we recommend either:

- Opening an Azure support ticket via the portal
- Opening a new issue here

**Comment by ChunchuSrinivas** [comment]
![Az_Storage_Explorer](https://user-images.githubusercontent.com/87190755/194799818-bbcd383e-4542-41b1-a036-82c27fea728d.PNG)

Please suggest. Trying to connect from free-trail azure subscription to azure storage explorer in windows. getting those errors. attached a screenshot. Thanks
