### ISSUE TITLE
Upload Confirmation Dialog Box appears on Main monitor even though app is running on a secondary monitor

### ISSUE THREAD

**Issue by shanselman** [microsoft/AzureStorageExplorer#5053]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.2

### Architecture

x64

### Storage Explorer Build Number

20210924.14

### Platform

Windows

### OS Version

Windows 11 - 22000.194

### Bug Description

Upload Confirmation Dialog Box appears on Main monitor even though app is running on a secondary monitor

### Steps to Reproduce

1. Run Storage Explorer on a system with 2-3 monitors. Put it on Monitor 2 or 3. Close it
2. Run Storage Explorer. It'll appear on the remembered monitor.
3. Upload a blob that overwrites another blob.
4. Observe the "override blob" dialog appears centered in Monitor 1.

### Actual Experience

1. Run Storage Explorer on a system with 2-3 monitors. Put it on Monitor 2 or 3. Close it
2. Run Storage Explorer. It'll appear on the remembered monitor.
3. Upload a blob that overwrites another blob.
4. Observe the "override blob" dialog appears centered in Monitor 1.

**Comment by MRayermannMSFT** [comment]
Related: https://github.com/microsoft/AzureStorageExplorer/issues/4343

**Comment by craxal** [comment]
Several other Storage Explorer developers and testers were also unable to reproduce this issue. If anyone encounters this issue again, we can reopen and continue the investigation.
