### ISSUE TITLE
Fail to execute the action ''Clone and Rehydrate' in one attached blob container which SAS URL is created by an access policy (All permissions)

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5054]
**Storage Explorer Version:** 1.22.0-dev
**Build Number:** 20211012.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.6
**Architecture:** ia32\x64
**How Found:** Ad-hoc testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one non-ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one blob -> Update the access tier to 'Archive'.
3. Right click the blob container -> Click 'Manage Access Policies...'.
4. Add one access policy with all permissions -> Generate a SAS URL via the access policy.
5. Attach the blob container via the SAS URL.
6. Switch to the attached blob container.
7. Right click the blob -> Click 'Clone and Rehydrate'.
8. Input a valid destination blob name -> Click 'Apply'.
9. Check whether succeed to execute the action 'Clone and Rehydrate'.

## Expected Experience ##
Succeed to execute the action 'Clone and Rehydrate'.

## Actual Experience ##
Fail to execute the action 'Clone and Rehydrate'.
![image](https://user-images.githubusercontent.com/87792676/136923907-a4963431-f194-4191-822c-475d06d8d6c5.png)

## Additional Context ##
1. This issue also reproduces when attaching via SAS permissions  (Read, Add, Create, Write, Delete, Delete version, List).
2. This issue doesn't reproduce when attaching via SAS permissions (All permissions).
3. Error details:
```
 "name": "RestError",
  "message": "This request is not authorized to perform this operation using this permission".
```

**Comment by JasonYeMSFT** [comment]
This is due to tags. Access policies don't grant permissions to read tags. I'll add a prompt to let user confirm if they want to continue without preserving tags.

**Comment by JasonYeMSFT** [comment]
Work to allow cloning an archived blob bypassing tags is merged.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20211102.2. Fixed. So close this bug.
