### ISSUE TITLE
Getting error "unable to get local issuer certificate" when accessing my FS in Storage Explorer

### ISSUE THREAD

**Issue by Brizzriel** [microsoft/AzureStorageExplorer#5059]
Unable to retrieve child resources.

Details:
unable to get local issuer certificate

Whenever I try to open my FS I get the above error. I cannot figure out how to fix it. I am running the latest ver of Storage Explorer 1.21.2 and I can access the FS when in portal.azure.com so I know it is not missing. How do I replace my cert?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having issues we recommend either:
- opening an azure support ticket via the azure portal
- opening a new issue here
