### ISSUE TITLE
An extra 'Tables' node displays under one Blob account

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#506]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180724.5
**Commit**: 2605f1c9
**Regression From**: Previous release 1.3.1(20180711.1)

#### Steps to Reproduce: ####
1. Expand one Blob account then check the children nodes.

#### Expected Experience: ####
No 'Tables' node displays under the account.

#### Actual Experience: ####
An extra 'Tables' node displays under the account.
![tables](https://user-images.githubusercontent.com/34729022/43309106-55104818-9173-11e8-91f8-b4539b8dfb8a.png)

**Comment by craxal** [comment]
This is by design. Metrics can be collected for blob accounts and stored in tables. The Tables node here lets users view the account metrics.
