### ISSUE TITLE
Storage explorer not workable

### ISSUE THREAD

**Issue by fjbsaper** [microsoft/AzureStorageExplorer#5060]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.2

### Architecture

i86

### Storage Explorer Build Number

20210924.14

### Platform

Windows

### OS Version

Window10

### Bug Description

Performance is abominable. You can go and take a coffee after each action. Antivirus is set to scan on access. The product just can not work with this setting.
Can't even access the storage or the subscriptions, it takes so long...

### Steps to Reproduce

1. Download and Launch Storage Explorer
2. Sign in using subscription
3. Click on the Tree
4. wait until forever

### Actual Experience

Nothing shows up in the activities window. When you go to exit the Storage Explorer a dialog comes up saying that you have uncompleted actions...

### Expected Experience

Better error messaging. Simple instructions on what to do to prevent or remediate the problem. If it has to do with SSL keys, I'd expect it to work with the windows keys or the browser's keys... so I would have nothing to do.
The way it is it is just not acceptable. The experiance is worse than a beta product.

**Comment by JasonYeMSFT** [comment]
Do you know what the antivirus tool do when you set it to "scan on access"? If we can figure out what is triggering its activity, we might be able to trim some of the unnecessary actions.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having issues we recommend either:
- opening an azure support ticket via the azure portal
- opening a new issue here

**Comment by fjbsaper** [comment]
There's been an update since and that seems to have fixed the problem.
