### ISSUE TITLE
Last Modified Sort on column header does not work

### ISSUE THREAD

**Issue by DataEngineerVienna** [Microsoft/AzureStorageExplorer#5063]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.2

### Architecture

x64

### Platform

Windows

### OS Version

10

### Bug Description

Click on the "Modified" column header does not sort the file list

### Steps to Reproduce

Click on header

### Actual Experience

nothing happens, not sorted

### Expected Experience

should resort the file list

### Additional Context

.

**Comment by JasonYeMSFT** [comment]
We had a similar issue #5048. Could you share a sample of the dates that aren't sorted correctly? Also could you share the date format on your machine (e.g. mm/dd/yyyy or dd/mm/yyyy)?
