### ISSUE TITLE
Revisit nedb

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#5064]
Replacement notes/requirements:
- Predicates, do not need query objects
- Don't need to have DB on disk
- Given less than 100k entities, operations should take less than ~10ms
- Concurrent reads, sequential writes (on same documents at least)
- Keep roughly same footprint of memory as Nedb
- Start with map go from there

Migrate:
- [x] Activity Log Manager
- [x] Job Queue Manager
- [x] Shared Data Manager
- [x] Updates Manager

Post main work...
- [x] Make test names more consistent in shared data package
- [x] Use ECMA privates in share data package
- [x] Refactor test harness in comparison tests in simple db package to reduce code duplication
- [x] JSDoc SimpleDb
- [x] Make sure all package dirs are renamed
- [x] Make sure all packages have as few dependencies as possible

**Comment by MRayermannMSFT** [comment]
We no longer will be shipping nedb.
