### ISSUE TITLE
Unable to retrieve child resources.  Details: Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by Mich0311** [microsoft/AzureStorageExplorer#5065]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.2

### Regression From

1.09.0

### Architecture

x64

### Storage Explorer Build Number

20210924.14

### Platform

Windows

### OS Version

Windows 10

### Bug Description

![image](https://user-images.githubusercontent.com/92510557/137314230-251d131c-b24c-4818-883e-ab340d74629b.png)
[](url
<img width="396" alt="Capture" src="https://user-images.githubusercontent.com/92510557/137314389-ea6f2d1c-7a40-4065-8170-4ccf2b6088f8.PNG">
)

### Steps to Reproduce

<img width="396" alt="Capture" src="https://user-images.githubusercontent.com/92510557/137314723-07f4663e-921d-4e0f-9e4c-9bdb6837c787.PNG">

### Actual Experience

<img width="396" alt="Capture" src="https://user-images.githubusercontent.com/92510557/137314422-53568b28-2eab-4038-ae7a-eb38e1ca5b07.PNG">

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having issues we recommend either:
- opening an azure support ticket via the azure portal
- opening a new issue here
