### ISSUE TITLE
The deleted cloned rehydrated blob displays in the secondary explorer if the blob versioning is enabled

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5072]
**Storage Explorer Version**: 1.22.0-dev
**Build Number**: 20211019.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.6
**Architecture**: ia32\x64
**How Found**: Exploratory testing 
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one non-ADLS Gen2 storage account ->Blob Containers (Make sure the blob versioning is enabled).
2. Create a blob container -> Upload one blob -> Change its access tier to 'Archive'.
3. Clone and rehydrate the blob -> Wait a second -> Refresh the editor.
4. The cloned rehydrated blob displays -> Delete it.
5. Right click the blob container -> Click 'Open Secondary Location'.
6. Check whether the cloned rehydrated blob doesn't display in the secondary explorer.

## Expected Experience ##
The cloned rehydrated blob doesn't display in the secondary explorer.

## Actual Experience ##
The cloned rehydrated blob displays in the secondary explorer.
![image](https://user-images.githubusercontent.com/41351993/137868281-85909e34-0f13-45ea-943e-8097c0622122.png)

## Additional Context ##
1. The cloned rehydrated blob still displays after manually refreshing.
2. This issue can't be reproduced consistently.

**Comment by JasonYeMSFT** [comment]
@v-xianya Let's check if they go away after waiting for some time for the secondary location to sync with the primary location. At the mean time, I will confirm with the service team on the expected behavior of deleting a blob being rehydrated.

**Comment by JasonYeMSFT** [comment]
OK, I have reproed this bug and I'll wait longer to see if the rehydrated copy in the secondary location will be eventually garbage collected.

**Comment by JasonYeMSFT** [comment]
Confirmed with the service team that this is a service bug.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20230228.2. Fixed. So, we are going to close it.
