### ISSUE TITLE
Unable to connect File Store

### ISSUE THREAD

**Issue by ApoorvaKantale** [microsoft/AzureStorageExplorer#5073]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.1

### Architecture

x64

### Platform

Windows

### OS Version

Windows 10

### Bug Description

unable to connect file share 

### Steps to Reproduce

unable to connect file share 

### Actual Experience

unable to connect file share 

### Expected Experience

Connect and show the drive

**Comment by ApoorvaKantale** [comment]
![image](https://user-images.githubusercontent.com/78148795/137954079-2ced78d4-f75c-4c2d-ad6a-f72ed9310857.png)

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having issues we recommend either:
- opening an azure support ticket via the azure portal
- opening a new issue here
