### ISSUE TITLE
Download of Large Files from Blob Storage to a Windows NTFS volume not working

### ISSUE THREAD

**Issue by amish1971** [microsoft/AzureStorageExplorer#5077]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.1

### Architecture

x64

### Platform

Windows

### Bug Description

Hi,

I am seeing something similar like campibh mentioned.  I have a few 6TB and larger files in my blob storage and when i try to download them to my Windows Server (using storage explorer) which has an 10TB NTFS volume it fails.  Below are the messages that i see

Transfer of 'downloads/BW4HANA/63DS-ScaleOut/COMPLETE_DATA_BACKUP_TENANTDB_63DS_databackup_4_1' to 'F:\BW4H_63DS_Backup' failed: 0 items transferred (used SAS, discovery completed)
Started at: 10/19/2021, 5:37:30 PM, Duration: 3 seconds

its a 6.9TB file that i am trying to download.  I had uploaded this files into the Blob from another Windows Server.  As the two Windows server were not on the same network, blob was the only way for me to go. 

Here are the version details

![image](https://user-images.githubusercontent.com/35819788/137963288-6867b2c1-6573-4889-b613-510451eef232.png)

Storage Explorer - 1.19.1
azcopy - 10.10.0

Any help would be appreciated.

Amish

### Steps to Reproduce

1. Launch the Storage Explorer.
2. Browse to the Blob Storage.
3. Select the file and download.

### Actual Experience

All i do is select the file and try to download and it fails.  I have tried smaller files from the same blob storage and those work just fine.  The file which are giving me errors are all 6TB and larger.

**Comment by JasonYeMSFT** [comment]
@amish1971 Could you get the AzCopy log using the "Open AzCopy logs" in the activity and send us the .log file for the failed transfer? Could you double check if your local machine has enough disk space for the large file?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having issues we recommend either:
- opening an azure support ticket via the azure portal
- opening a new issue here

**Comment by livrish** [comment]
How do I reopen this because I have the same issue. Also I am having a couple of other issues such as with the select all ... and the goto end
