### ISSUE TITLE
Review provider function names

### ISSUE THREAD

**Issue by craxal** [Microsoft/AzureStorageExplorer#5085]
Provider function names are becoming more numerous and harder to discern as to their purpose without some form of convention. We should review function names and settle on a convention to avoid further confusion.

**Comment by MRayermannMSFT** [comment]
We reviewed names and have a shared understanding of what names should be going forward.

**Comment by craxal** [comment]
@MRayermannMSFT Can you please document those names here? That'll prevent that "shared understanding" from getting lost over time.
