### ISSUE TITLE
Accessing Azure Storage Account Using Azure Storage Explorer from behind a Proxy

### ISSUE THREAD

**Issue by nlaymon1980** [microsoft/AzureStorageExplorer#5090]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.2

### Regression From

No 

### Architecture

x64

### Storage Explorer Build Number

20210924.14

### Platform

Windows

### OS Version

Windows Server 2016 Standard

### Bug Description

Unable to list out Azure storage account blob containers using Storage Explorer from an on-premise Server behind a Proxy (proxy does not require authentication). 

Microsoft TrackingID#2110040040007117

### Steps to Reproduce

1. Launch Storage Explorer
2. Add an Account
3. Select Subscription
3. Enter credentials
4. Explore to the Storage Account
4. Expand Storage Account
5. Expand Blob Containers

### Actual Experience

Receive the following error message when listing out blobs:

From Storage Explorer Error Details:
Unable to retrieve child resources.

Details:
{
  "name": "RestError",
  "message": "This request is not authorized to perform this operation.\nRequestId:9f4a97f1-f01e-0068-3f74-c72b57000000\nTime:2021-10-22T18:43:45.3588188Z",

Repetitive log messages in StorageUtilitiesSingleton-4256-s2c1fvxq-1.log.

10/22/2021 13:10:43 : Error : [MSAL.Extension][2021-10-22T18:10:43.5083616Z] An exception was encountered while reading data from the MsalCacheStorage : System.Security.Cryptography.CryptographicException: Key not valid for use in specified state.

   at System.Security.Cryptography.ProtectedData.Unprotect(Byte[] encryptedData, Byte[] optionalEntropy, DataProtectionScope scope)
   at Microsoft.Identity.Client.Extensions.Msal.DpApiEncryptedFileAccessor.Read()
   at Microsoft.Identity.Client.Extensions.Msal.MsalCacheStorage.ReadData(Boolean ignoreExceptions)
10/22/2021 13:10:43 : Error : [MSAL.Extension][2021-10-22T18:10:43.5903824Z] An exception was encountered while reading data from the MsalCacheStorage : System.Security.Cryptography.CryptographicException: Key not valid for use in specified state.

### Expected Experience

Should be able to list blob containers with credentials that have been verified to have access (using an external machine) and the proxy server's external IP address added to the storage account network rules.

### Additional Context

Microsoft has recommended I open a Storage Explorer Issue and look at the following options:

a. Configure token caching so that it does not fail on encryption errors. In this case, MSAL will store tokens in memory only. The user will have to re-login into their app after they restart it, but at least things will work.
b. If encryption is not available, it is possible to store tokens in clear using a protected HDD folder that only the user has access to.

**Comment by MRayermannMSFT** [comment]
I believe this issue is now being handled by an ICM opened via a customer support ticket.

**Comment by Michael-Kagnew** [comment]
> I believe this issue is now being handled by an ICM opened via a customer support ticket.

Has there been any update to this? Currently, we can only upload files to our storage account via Synapse Studio. Furthermore, disabling vnet security seems to resolve all issues. We are behind a VPN but there was no problem with that in the past.

**Comment by MRayermannMSFT** [comment]
Hi @Michael-Kagnew do you work with/are you related to the original author of this issue, or are you just someone else also seeing this error message:

> An exception was encountered while reading data from the MsalCacheStorage : System.Security.Cryptography.CryptographicException: Key not valid for use in specified state.

**Comment by Michael-Kagnew** [comment]
Hello @MRayermannMSFT , I'm not related with the original poster in anyway, however we are dealing with the same issue at my organization, where the first snippet of the error states:

> "message": "This request is not authorized to perform this operation

**Comment by MRayermannMSFT** [comment]
@Michael-Kagnew unfortunately the reasons for getting the error "This request is not authorized to perform this operation" are far and wide. Common reasons for it include:

- RBAC permissions not setup correctly (I encourage you to double check)
- Firewall rules
- IP restrictions
- SAS tokens expiring/stored access policies expiring

If you don't think any of those apply to you (and have checked), then I would recommend opening a support ticket via the portal. They can help you dig into the exact reasoning why better than we can here on GitHub.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having problems, we suggest opening an Azure support ticket via the portal.
