### ISSUE TITLE
Folder Statistics should be enhanced to more user friendly

### ISSUE THREAD

**Issue by jasonhorner** [microsoft/AzureStorageExplorer#5092]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I want to quickly assess the size of my blobs

### Desired Solution

I'd like Folder Statistics to display in the most user friendly Units

### Alternatives and Workarounds

Run the calculation from bytes to TB, GB, MB

### Additional Context

Ideally, folder statistics should use the best units for the size of the blobs and label appropriately and also continue to provide the details in bytes

**Comment by MRayermannMSFT** [comment]
![image](https://user-images.githubusercontent.com/21112697/196548626-ce7a5ebb-1823-491a-a96e-c538be0cdef8.png)
👀

**Comment by jasonhorner** [comment]
Nice!!!!

**Comment by MRayermannMSFT** [comment]
Sorry it took so long. 😅

**Comment by MRayermannMSFT** [comment]
Will be available in 1.27
