### ISSUE TITLE
Folders Created on Azure programmatically are not seen in Azure Storage Explorer

### ISSUE THREAD

**Issue by Elencon** [microsoft/AzureStorageExplorer#5093]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.20.1

### Architecture

x64

### Storage Explorer Build Number

20210720.10

### Platform

Windows

### Bug Description

I Created folders programmatically using using Azure.Storage.Files.Shares library. Code executes properly. I do not see folders in Explorer, with refresh, with changing folders and so on. But, when I create new folder with Explorer in the same share they suddenly appear

### Steps to Reproduce

1) Launch Explorer. 
2 Create folders programmatically in empty share . 
3 Refresh.
4. See nothing.
5. Create one folder with New Folder button
6. All my folders suddenly uppear

### Actual Experience

I Created folders programmatically using using Azure.Storage.Files.Shares library. Code executes properly. I do not see folders in Explorer, with refresh, with changing folders and so on. But, when I create new folder with Explorer in the same share they suddenly appear

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having trouble from this issue, we recommend either:

- Opening an Azure support ticket via the portal
- Opening a new issue here
