### ISSUE TITLE
The permission 'Immutable storage' is displayed as 'unknown' in the 'Summary' dialog when attaching one storage account by the connection string (SAS) which is created from portal

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5094]
**Storage Explorer Version**: 1.22.0-dev
**Build Number**: 20211026.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 18.04/MacOS Big Sur 11.6
**Architecture**: ia32\x64
**How Found**: Exploratory testing 
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Select one non-ADLS Gen2 storage account -> Open the storage account in portal.
2. Make sure all the allowed permissions are selected -> Click 'Generate SAS and connection string'.
3. Copy the connection string.
4. Go to storage explorer -> Open the connect dialog -> Click 'Storage account or service'.
5. Select 'Connection string (Key or SAS)' -> Click 'Next'.
6. Paste the connection string -> Click 'Next'.
7. Observe the permissions in the 'Summary' dialog.
8. Check all permissions display well.

## Expected Experience ##
All permissions display well.

## Actual Experience ##
The permission 'Immutable storage' is displayed as 'unknown'.
![image](https://user-images.githubusercontent.com/41351993/138836929-1ce52506-49a0-40f8-8c59-28f7d37b9225.png)

## Addition Context ##
1. The allowed permissions for one non-ADLS Gen2 storage account.
![image](https://user-images.githubusercontent.com/41351993/138837251-7bbd2ba5-1cc5-43ba-bc88-82084d48ea49.png)
2. For one ADLS Gen2 storage account, the permission 'Immutable storage' can't be selected.

**Comment by v-xianya** [comment]
Verified this issue on the build 20211115.2. **Reproduce**. 
So we are going to reopen this bug and verified it on a newer build.

**Comment by craxal** [comment]
I misread the repro steps, as I thought this was for a blob SAS. But that panel also needed the missing permission.

**Comment by v-xianya** [comment]
Verified on the build main 20211116.4. Reproduce.
Will verify this issue on a newer build.

**Comment by v-xianya** [comment]
Reproduce on the latest build 20211117.3. so we are going to re-open it and keep eyes on this issue.
Will close this issue once it got fixed.

**Comment by v-xianya** [comment]
Update:

This issue does not reproduce when using 'SAS URL'.
![image](https://user-images.githubusercontent.com/41351993/142160954-0f10faf2-e102-4535-b989-6534cde48bd5.png)

This issue reproduces when using 'Connection string'.
![image](https://user-images.githubusercontent.com/41351993/142161087-aa8bff7a-c905-4409-9ca7-408448d8cf7c.png)

The screenshot from Portal:
![image](https://user-images.githubusercontent.com/41351993/142160855-13f86944-bc23-4365-b8f0-90b50f828a87.png)

**Comment by craxal** [comment]
New change has been merged that fixes permission labels for account connection strings.
