### ISSUE TITLE
terraform deploy azurerm_storage_share.sharedstorage - storage explorer browse File Shares results in unable to retrieve child...

### ISSUE THREAD

**Issue by g-spencer** [microsoft/AzureStorageExplorer#5095]
Unable to retrieve child resources.

Details:
This request is not authorized to perform this operation.
RequestId:44a6b1ed-d01a-0043-674a-ca56ba000000
Time:2021-10-26T09:16:41.4607047Z

**Comment by MRayermannMSFT** [comment]
@g-spencer how are you authenticating to your file share? Did you:
- sign into Storage Explorer
- attach your storage account with a SAS connection string
- attach your file share with a SAS URI
- attach your storage account with name and key/key connection string

If you did either of the SAS attach options, can you share your SAS token? **Please redact the `sig` from the token before sharing it though!**

If you signed in, can you click on the node for the storage account, go down to the properties in the bottom left, and make sure you have a key?

Finally, for either sign in or attaching with key, please make sure that the key you have in the properties is the correct key. You can cross check against the key value in the azure portal.

**Comment by g-spencer** [comment]
Hi Matthew,
we have found that this issue is related to the azure devops release hosted agent not having access to the storage account during deployment if we are deploying with network rules default action 'deny'.

I wrongly assumed incorporating a network rules 'bypass' statement allowing 'AzureServices' would accommodate the necessary accesses during deployment, but experience has proven me wrong on this.

The list of IP addresses for each region are listed at: https://www.microsoft.com/en-us/download/details.aspx?id=56519, however I find incorporating this massive list into my TF configuration prohibitive, and have progressed on the basis I will deploy with a default action 'allow' and just configure the network rules post deployment.

It would be useful if there were a mechanism that provided for easy inclusion of the hosted agent subnet ranges for releases that could be called by the deployment, as the list may be updated weekly and would avoid necessity to recheck the list before deployment.

thanks,

G.
