### ISSUE TITLE
No button is selected by default on the prompt dialog when there is no running emulator

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5096]
**Storage Explorer Version**: 1.22.0-dev
**Build Number**: 20211026.1
**Branch**: main
**Platform/OS**: Windows 10/MacOS Big Sur 11.6
**Architecture**: ia32\x64
**How Found**: Exploratory testing 
**Regression From**: Not a regression

## Bug Descriptions ##
No button is selected by default. 
It navigates to the below page when clicking the link 'Learn More/Install Azurite', 

![image](https://user-images.githubusercontent.com/41351993/138849964-494793a3-cef4-466d-98a6-3b162bdc62aa.png)

## Steps to Reproduce ##
1. Make sure no storage emulator or Azurite is running -> Launch Storage Explorer.
2. Expand Local & Attached -> Storage Accounts -> (Emulator - Default Ports) (Key).
3. A dialog pops up -> Check whether a button is selected by default.

## Expected Experience ##
A button is selected by default.

## Actual Experience ##
No button is selected by default.
![image](https://user-images.githubusercontent.com/41351993/138849142-ee502377-4702-480c-961b-8aef514ad1ca.png)

## Additional Context ##
1. On Linux, the first button 'Learn more' is selected.
![image](https://user-images.githubusercontent.com/41351993/138852162-9e5e7c6e-bec4-44e2-8084-db64fcca56e0.png)

**Comment by MRayermannMSFT** [comment]
Most likely related to: https://github.com/microsoft/AzureStorageExplorer/issues/5089

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20211110.13. Fixed.
![image](https://user-images.githubusercontent.com/87792676/141226628-65716d83-86f0-4433-826f-8dc95245b78a.png)
