### ISSUE TITLE
Failed to create database. Details: {"name":"Error","errno":-3008,"code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"cosmos10632.documents.azure.com"}

### ISSUE THREAD

**Issue by Aarti0910** [microsoft/AzureStorageExplorer#5098]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

i am unable to create  a database called products in Azure Cosmos DB.

### Desired Solution

please give me solution

**Comment by amyk20011** [comment]
same

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
