### ISSUE TITLE
Casing of 'Auto-Resolve behavior' is wrong

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#51]
**Storage Explorer Version:** 1.0.0(20180415.2)

**OS Version:** Windows 10/Mac/Linux

**Regression:** Not a regression

**Steps to Reproduce:**

1. Launch Storage Explorer and expand Storage Accounts. 
2. Open one file share and copy an existing file to it.
3. Check the Casing of 'Auto-Resolve behavior' in Activities Panel.

**Expected Experience:**
It should display as Auto-resolve Behavior.

**Actual Experience:**
It displays as Auto-Resolve behavior.
![case](https://user-images.githubusercontent.com/34729022/38983077-08265b0e-43b3-11e8-814a-cf5c2680f557.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
