### ISSUE TITLE
Subscription IDs are not shown

### ISSUE THREAD

**Issue by StenPetrov** [microsoft/AzureStorageExplorer#510]
**Storage Explorer Version**: 1.3.1
**Platform/OS Version**: Windows
**Architecture**: ia32
**Regression From**: not a regression

#### Steps to Reproduce: ####
Add an account with multiple subscriptions, you get a list of the subscription names but can't see their IDs

#### Expected Experience: ####
Portal, CLI tools use Subscription ID more consistently, using a combination of tools is not very easy when you can't see or select the Subscription ID. Hover-over would be OK, Properties should show it too.

Also when selecting the subscriptions for an account it would be nice to be able to sort by Subscription ID

#### Actual Experience: ####
Terrible, when Subscription ID is the primary way of navigating around your task.

**Comment by craxal** [comment]
I assume by "account" you're referring to Azure accounts and not individual storage accounts. This seems odd; you should be able to see subscription IDs very easily when signing in. Do you have a screenshot of your Account Management panel?

**Comment by MRayermannMSFT** [comment]
This is fixed. Subscription IDs are shown in the account panel:
<img width="201" alt="image" src="https://user-images.githubusercontent.com/21112697/76788362-01abe380-6778-11ea-9dc4-8d39506288f2.png">
