### ISSUE TITLE
Storage explorer error "Unable to retrieve child resources"

### ISSUE THREAD

**Issue by sureshnilam** [microsoft/AzureStorageExplorer#5102]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.3

### Architecture

x64

### Storage Explorer Build Number

20211020.2 

### Platform

macOS

### OS Version

Big Sur

### Bug Description

Details:
{
  "name": "FetchError",
  "message": "request to http://127.0.0.1:10000/bsdataservicespoc?comp=list&include=metadata failed, reason: connect ECONNREFUSED 127.0.0.1:10000",
  "stack": "FetchError: request to http://127.0.0.1:10000/bsdataservicespoc?comp=list&include=metadata failed, reason: connect ECONNREFUSED 127.0.0.1:10000\n    at ClientRequest.<anonymous> (/private/var/folders/mh/ks9w5hy51557vspt0jy0s92h0000gn/T/AppTranslocation/AA9589AA-45A0-4A03-B338-0079A839F1BB/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/node-fetch/lib/index.js:1483:11)\n    at ClientRequest.emit (events.js:315:20)\n    at Socket.socketErrorListener (_http_client.js:469:9)\n    at Socket.emit (events.js:315:20)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
  "type": "system",
  "errno": "ECONNREFUSED",
  "code": "ECONNREFUSED"
}

### Steps to Reproduce

Expand the blob container

### Actual Experience

Very bad

**Comment by aldostellato** [comment]
I have the same issue with my install on my Mac.

**Comment by MRayermannMSFT** [comment]
@sureshnilam @aldostellato this message indicates you were trying to access the blob containers node for your storage emulator. Were you indeed trying to do so? If yes, please be aware that Storage Explorer does not ship with an emulator and it does not start your emulator for you. You must do those on your own.

**Comment by fansofdetective** [comment]
@MRayermannMSFT  What do you mean by storage emulator? I have same issue here, and it only happens when I'm not connected to MSFT VPN. This has only happened in recent week. It seems to be something with IP restrictions changes.

**Comment by MRayermannMSFT** [comment]
@fansofdetective it sounds like you are internal to Microsoft? Can you reach out to me on teams? I'd like to see what it is you are experiencing.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
