### ISSUE TITLE
There is a failed activity log when attaching one table in the search results if only selecting the 'Tables' option

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5103]
**Storage Explorer Version:** 1.22.0-dev
**Build Number:** 20211028.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.6
**Architecture:** ia32\x64
**How Found:** Exploratory testing
**Regression From:** Not a regression

## Bug Descriptions ##

1. An error appears when attaching one table in the search results if only selecting the 'Tables' option.
2. An error appears when attaching one storage account if only selecting the 'Storage Accounts' option.
3. An error appears when attaching one table in the 'Search From Here' results.
4. An error appears when attaching one storage account in the 'Search From Here' results.

## Steps to Reproduce ##

1. Launch Storage Explorer -> Click Filter button in the search box.
2. Only select the 'Tables' option ->  Type 'Tables' in the search box -> Execute 'Search'.
3. Select one table -> Try to attach it.
4. Check there is a successful activity log.

## Expected Experience ##
There is a successful activity log.

## Actual Experience ##

1. Succeed to attach this table.
2. There is a failed activity log.
![image](https://user-images.githubusercontent.com/87792676/139221796-1f1b22a3-8ec0-4dd1-9c1e-392139c5662e.png)

## Additional Context ##

1. This issue doesn't reproduce for blob container/ file share/ queue.
2. This issue doesn't reproduce if selecting all filter options.
3. This issue can't be reproduced consistently.

**Comment by JasonYeMSFT** [comment]
This happens when the search results doesn't include the local attached group node. Since this is not a regression, and attaching a resource while searching is an edge case, we can defer fixing this in 1.23.0.

**Comment by v-kellyluo** [comment]
@craxal verified this issue on the build main/20220208.1, it doesn't reproduce for tables, but it also reproduces for storage accounts, so we are going to reopen this issue.

**Comment by v-kellyluo** [comment]
Verified this on the build main/20220211.3. Fixed. So close it.
