### ISSUE TITLE
The 'Clone and Rehydrate' dialog is not localized

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5105]
**Storage Explorer Version:** 1.22.0-dev
**Build Number:** 20211029.4
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.6
**Architecture:** ia32\x64
**Language:** All languages
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Deutsch' -> Restart Storage Explorer.
3. Expand one storage account -> Blob Containers.
4. Create a blob container -> Upload one blob ->  Change its access tier to 'Archive'.
5. Right click the blob -> Click 'Clone and Rehydrate'.
6. Check whether the 'Clone and Rehydrate' dialog is localized.

## Expected Experience ##
 The 'Clone and Rehydrate' dialog is localized.

## Actual Experience ##
 The 'Clone and Rehydrate' dialog is not localized.
![image](https://user-images.githubusercontent.com/87792676/139400384-ef4cb839-0567-4ac6-9022-9f35ba1091e5.png)

**Comment by MRayermannMSFT** [comment]
@JasonYeMSFT please track during 1.22. Feel free to put in loc milestone to look into now and then.

**Comment by JasonYeMSFT** [comment]
I have added the resource files to our loc config. Unfortunately the strings won't be ready for 1.22.0.

**Comment by JasonYeMSFT** [comment]
This dialog should have been localized on main.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20211215.5. Fixed.
