### ISSUE TITLE
"self signed certificate in certificate chain" error on Azure storage explorer

### ISSUE THREAD

**Issue by ihaman** [microsoft/AzureStorageExplorer#5107]
Hi 

I am getting "self signed certificate in certificate chain" error on Azure storage explorer with the organization account . 
I tried the steps on https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004 but i dont have any self signed certificate

**Comment by MRayermannMSFT** [comment]
@ihaman did you give system proxy a try? Read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by mgmage** [comment]
I have a similar issue with the same error text. In the storage explorer I can connect to my azure subscription and I can also access the blob-container storage of my storage account but when I try to access the table-storage (within the same storage account) I get the "self signed certificate chain" error. (tried system proxy (preview) as well)

**Comment by MRayermannMSFT** [comment]
@mgmage unfortunately table features do not yet support system proxy. :( We are working hard to get all features supporting it as soon as possible but we aren't quite there yet. In the meantime, you will need to manually workaround/resolve the issue. Please see these troubleshooting steps: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#ssl-certificate-issues

**Comment by MRayermannMSFT** [comment]
Hi all, at this point tables support system proxy. Please try enabling it and see if that resolves the certificate issues. If it does not, please let us know. Thanks!

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue we recommend opening a support ticket via the Azure Portal. Alternatively you can open a new issue here.
