### ISSUE TITLE
Port forwarding info is needed

### ISSUE THREAD

**Issue by fjbsaper** [microsoft/AzureStorageExplorer#5108]
The documentation needs to be improved and the port forwarding needs need to be specified. I am not able to login if I am behind the second router. But I can login fine from behind the first. 

All my internet access works just fine from behind the second router.... so it has to be something with port forwarding...

Thanks

**Comment by MRayermannMSFT** [comment]
@fjbsaper do you have any issues with other Microsoft apps, like VS Code, VS, etc.? Have you tried other Microsoft apps? Have you had issues with non-Microsoft apps? We're not really sure what you're looking for here. Are you getting any error messages in Storage Explorer that you can share? Could you tell us more about the specifics of your networking setup?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue we recommend either:
- opening an Azure support ticket via the portal
- opening a new issue here
