### ISSUE TITLE
The uploading activity is continuous after canceling the individual file upload of a large file

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#511]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180727.7
**Commit**: 3fd8ad34
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Choose one account then open one file share.
2. Upload one large file like 127G to the opened file share.
3. Expand the uploading group in Activities -> Click 'Cancel' next to the children process -> Check the result.

#### Expected Experience: ####
The uploading activity is canceled.

#### Actual Experience: ####
The uploading activity is continuous until the large file is uploaded successfully.
![uploaded](https://user-images.githubusercontent.com/34729022/43392329-e2f0e630-93e2-11e8-9bd3-bd15b9f7b3d8.png)

**Comment by craxal** [comment]
I don't think this is new. @MRayermannMSFT or @JakeRadMSFT might have more info?

**Comment by MRayermannMSFT** [comment]
File shares are still in the old pattern so I'm not sure how long its supposed to take for the message to change to "cancelling". Other than that, cancel is known to take a while, so... *shrug* ?

**Comment by v-xianya** [comment]
Verified on build 20190108.2. This issue doesn't reproduce. Could you help to resolve it?

**Comment by jinglouMSFT** [comment]
Closing.
