### ISSUE TITLE
Convert knockout toolbar component to React toolbar component

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#5110]

**Comment by JasonYeMSFT** [comment]
A prototype is implemented and ready for discussion. Move to 1.25 for further polishing and potentially start using it in product.

**Comment by JasonYeMSFT** [comment]
The work is done to keep the prototype feature up-to-date with the in-prod toolbar.

**Comment by MRayermannMSFT** [comment]
For 1.27, get component ready to use.
