### ISSUE TITLE
On an InsertOrReplace Explorer never shows the updated record

### ISSUE THREAD

**Issue by DarklyPure** [microsoft/AzureStorageExplorer#5116]
When I perform an InsertOrReplace using the C# Microsoft.Azure.Cosmos.Table library. The record is inserted or replaced, but Azure Storage Explorer never shows the updated version, only the original. The record is definitely inserted/replaced, but storage explorer never reflects this.

**Comment by StefArroyo** [comment]
Hi @DarklyPure!

Thank you for your feedback, we have retired support for Cosmos DB in Azure Storage Explorer v.1.22.0. We are actively working on an alternative solution using Azure Data Studio, a unified desktop tooling experience exclusively for Azure databases. In the meantime, you can continue to use the following options: [version 1.21.3 of Azure Storage Explorer](https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.21.3) which integrates with Azure Cosmos DB, the [Azure Portal](https://portal.azure.com/), [Azure Portal desktop app](https://portal.azure.com/App/Download) or the standalone [Azure Cosmos DB Explorer](https://docs.microsoft.com/en-us/azure/cosmos-db/data-explorer).
