### ISSUE TITLE
The imported entities do not auto display in the table explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5119]
**Storage Explorer Version**: 1.22.0-dev
**Build Number**: 20211102.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 18.04/MacOS Big Sur 11.6
**Architecture**: ia32/x64
**How Found**: From running test cases 
**Regression From**: Previous release (1.21.3)

## Steps to Reproduce ##
1. Expand one storage account.
2. Right click the 'Tables' node -> Create a new table.
3. The table will displays under the 'Tables 2' node and being focused.
4. Open the table under the 'Tables' node -> Click 'Import' Import entities.
5. After successfully importing -> Check whether the entities auto displays.

## Expected Experience ##
The entities auto displays.

## Actual Experience ##
The entities do not auto display.

## Additional Context ##
This issue doesn't reproduce when importing entities under 'Tables 2' node.

**Comment by craxal** [comment]
Since the import work was moved to a job, there's no easy way to tell the table explorer when the job is finished. Therefore, getting this to work again may be difficult.

@MRayermannMSFT @JasonYeMSFT Thoughts?

**Comment by JasonYeMSFT** [comment]
You can take a look at the ExitState of AzCopy copy state machine. It sends an event to the table explorer to trigger a refresh in the explorer when a job finishes.

**Comment by v-xianya** [comment]
Verified on the build main/20211116.4. Fixed.
