### ISSUE TITLE
There is an error when updating one entity with an empty partitionkey/rowkey value

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5121]
**Storage Explorer Version**: 1.22.0-dev
**Build Number**: 20211102.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 18.04/MacOS Big Sur 11.6
**Architecture**: ia32/x64
**How Found**: From running test cases 
**Regression From**: Previous release (1.21.3)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Open one table -> Click 'Add'.
3. Click 'Insert' on the 'Add Entity' dialog -> Right click the entity.
4. Click 'Edit...' -> Click 'Update'.
5. Check there is no error.

## Expected Experience ##
There is no error.
## Actual Experience ##
There is an error.
![image](https://user-images.githubusercontent.com/41351993/139825055-0484584f-92e5-49b2-9a9c-af3b704ed7c3.png)

**Comment by craxal** [comment]
Related to #5120.

**Comment by craxal** [comment]
The SDK team have come out with several updates in response to issues we've found. I'm not able to reproduce with the current main, so I believe this is fixed.

**Comment by v-xianya** [comment]
Verified on the build 20211119.4. Fixed.
