### ISSUE TITLE
Miss the action 'Show in folder' next to the activity log when exporting entities

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5122]
**Storage Explorer Version:** 1.22.0-dev
**Build Number:** 20211102.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.6
**Architecture:** ia32\x64
**How Found:** From running test cases
**Regression From:** Previous release (1.21.3)

## Steps to Reproduce ##

1. Launch Storage Explorer -> Expand one storage account -> Tables.
2. Create a table -> Add one entity.
3. Select this entity -> Click 'Export -> Save'.
4. Check whether the action 'Show in folder' shows next to the activity log.

## Expected Experience ##
The action 'Show in folder' shows next to the activity log.
![image](https://user-images.githubusercontent.com/87792676/139819671-14e0e356-d8e1-4260-bcfa-c07336b8054a.png)

## Actual Experience ##
No action 'Show in folder' shows next to the activity log.
![image](https://user-images.githubusercontent.com/87792676/139819680-63e4adad-4833-4993-b1b2-3c3473f04a4e.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20211103.7, it still reproduces.

**Comment by craxal** [comment]
@v-kellyluo Yes, this issue is currently under "Verifying"; it's not closed yet. We still need to create an updated se-table-extension package. Once we've done that, we'll close as merged.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20211106.4. Fixed.
