### ISSUE TITLE
Fail to import entities that contain empty partitionkey/rowkey value

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5123]
**Storage Explorer Version**: 1.22.0-dev
**Build Number**: 20211102.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 18.04/MacOS Big Sur 11.6
**Architecture**: ia32/x64
**How Found**: From running test cases 
**Regression From**: Previous release (1.21.3)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Open one table -> Add an entity with the partitionkey/rowkey value is default.
3. Export the entities -> Then import the entities to a new created table.
4. Check whether succeed to import.

## Expected Experience ##
Succeed to import.
## Actual Experience ##
Fail to import with a failed activity log.

**Errors:**
`Unable to import entity with partition key '' and row key ''.`
![image](https://user-images.githubusercontent.com/41351993/139827398-6f089038-2db0-4faa-b305-b94b93f29d4a.png)

**Comment by craxal** [comment]
@v-xianya A few questions:
1. Please clarify what you mean by "default partition/row key value". What are the default values? If they are empty, this would seem to conflict with #5120 and #5121.
2. Please share the contents of the CSV file you tried to import. This will help isolate the problem more effectively.

**Comment by v-xianya** [comment]
@craxal 
1. Click 'Add' then click 'Insert' button without any changes on the Add Entity.(as the screenshot)
![image](https://user-images.githubusercontent.com/41351993/140000720-08eada80-0469-4124-92c9-0e22cfbd4de2.png)
2. The .csv file to reproduce this issue.
[atabley.csv](https://github.com/microsoft/AzureStorageExplorer/files/7464932/atabley.csv)

**Comment by craxal** [comment]
This appears to be due to some subtle differences in how keys are validated for `createEntity` vs `upsertEntity`. The platform definitely accepts entities with "" for partition or row keys, so it looks like a bug in the SDK. I've opened a new issue for them: Azure/azure-sdk-for-js#18521.

**Comment by craxal** [comment]
The SDK issue is still open, but I'm not able to repro with the current SDK version and current main, so I'm going to close.

**Comment by v-xianya** [comment]
Verified on the build 20211119.4. Fixed.
