### ISSUE TITLE
An error occurs when creating or opening one table under attached storage accounts

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5124]
**Storage Explorer Version**: 1.22.0-dev
**Build Number**: 20211102.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 18.04/MacOS Big Sur 11.6
**Architecture**: ia32/x64
**How Found**: From running test cases 
**Regression From**: Previous release (1.21.3)

## Steps to Reproduce ##
1. Select one storage account -> Attach it via SAS.
2. Expand the attached storage account.
3. Right click 'Tables' -> Create a new table.
4. Check no error occurs.

## Expected Experience ##
No error occurs.
## Actual Experience ##
An error 'name and key must be non-empty strings' prompts.

![image](https://user-images.githubusercontent.com/41351993/139829193-34a4b35d-4552-41d5-86f7-a992498d7e96.png)

## Additional Context ##
An error 'url cannot be null' occurs when creating or opening one table under Name & Key attached storage accounts.
![image](https://user-images.githubusercontent.com/41351993/139829776-bc2ebf78-0bfb-49e5-8f8b-c925043d7f33.png)

**Comment by v-xianya** [comment]
Updates: Verified on the build 20211110.13.
When opening one SAS attached table/table under SAS attached storage account. An error info bar prompts with the below error:
`{"odata.error":{"code":"NotImplemented","message":{"lang":"en-US","value":"The requested operation is not implemented on the specified resource.\nRequestId:fb990614-d002-0055-39a2-d6f770000000\nTime:2021-11-11T02:22:25.5333875Z"}}}`

**Comment by v-xianya** [comment]
Verified one the latest main build 20211116.4. 
1. Fixed for one SAS attached scenarios.
2. This issue also reproduces when opening one table under the **name & key** attached storage account.
![image](https://user-images.githubusercontent.com/41351993/141888661-4862ca06-1f34-4336-adb3-604f6c1fd3a2.png)

**Comment by craxal** [comment]
I updated the SDK as well as fixed a few attributes, and I'm not seeing this reproduce.

**Comment by v-xianya** [comment]
Verified on the build 20211119.4. 
This issue still reproduces for tables under one **Name & Key** attached storage account. So we are going to re-open it and verify on a newer build.

**Comment by v-xianya** [comment]
Verified on the build 20211121.3. Fixed.
