### ISSUE TITLE
The formats of the Timestamp value are inconsistent between the first added entity and other entities

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5125]
**Storage Explorer Version**: 1.22.0-dev
**Build Number**: 20211102.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 18.04/MacOS Big Sur 11.6
**Architecture**: ia32/x64
**How Found**: From running test cases 
**Regression From**: Previous release (1.21.3)

## Steps to Reproduce ##
1. Expand one storage account -> Right click 'Tables' node.
2. Create a table.
3. Add one entity -> Observe the Timestamp value.
4. Add another entity -> Observe the Timestamp value.
5. Check whether the format of the Timestamp values are consistent.

## Expected Experience ##
The formats are consistent.
![image](https://user-images.githubusercontent.com/41351993/139831525-ccc71149-a630-4e19-84de-6085ccc31ac2.png)

## Actual Experience ##
The formats are inconsistent.
![image](https://user-images.githubusercontent.com/41351993/139831510-b5d2bab1-2b06-46f2-8fa0-668c8f82af8c.png)

## Additional Context ##
This issue doesn't reproduce after manually refreshing.

**Comment by craxal** [comment]
The difference comes from the fact that we're reading the `date` value of the insert result, which has a different precision than the value in the etag. Refreshing gets the actual timestamp. So looks like we should probably use the etag.

**Comment by v-xianya** [comment]
Verified on the build main/20211110.13. Fixed.
