### ISSUE TITLE
There is a failed activity log when renaming/pasting one table

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5127]
**Storage Explorer Version:** 1.22.0-dev
**Build Number:** 20211102.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.6
**Architecture:** ia32\x64
**How Found:** From running test cases
**Regression From:** Previous release (1.21.3)

## Steps to Reproduce ##

1. Launch Storage Explorer -> Expand one storage account -> Tables.
2. Create a table -> Right click this table -> Click 'Rename...'.
3. Type a valid name -> Click 'Rename'.
4. Check whether there is a successful activity log.

## Expected Experience ##
There is a successful activity log.

## Actual Experience ##

1. The original table and renamed table all exist.
2. There is a failed activity log.
![image](https://user-images.githubusercontent.com/87792676/139824195-7100bdb4-252f-4d18-b35c-6ef966698a44.png)

**Comment by craxal** [comment]
This is expected, as this requires creating a table, and creating tables has not been moved the v12 SDK yet. We're also going to change "Rename" to "Clone", because we want to avoid data loss situations.
