### ISSUE TITLE
Unable to retrieve child resources.

### ISSUE THREAD

**Issue by aliibraheemshash** [microsoft/AzureStorageExplorer#5137]
Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to http://127.0.0.1:10000/devstoreaccount1?comp=list&include=metadata failed, reason: connect ECONNREFUSED 127.0.0.1:10000",
  "stack": "FetchError: request to http://127.0.0.1:10000/devstoreaccount1?comp=list&include=metadata failed, reason: connect ECONNREFUSED 127.0.0.1:10000\n    at ClientRequest.<anonymous> (C:\\Users\\Ali Shash\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1483:11)\n    at ClientRequest.emit (events.js:315:20)\n    at Socket.socketErrorListener (_http_client.js:469:9)\n    at Socket.emit (events.js:315:20)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
  "type": "system",
  "errno": "ECONNREFUSED",
  "code": "ECONNREFUSED"
}

**Comment by MRayermannMSFT** [comment]
@aliibraheemshash this message indicates you were trying to access the blob containers node for your storage emulator. Were you indeed trying to do so? If yes, please be aware that Storage Explorer does not ship with an emulator and it does not start your emulator for you. You must do those on your own.

**Comment by OzBob** [comment]
Also fails when idle for a few hours and try to create a queue:

Details:
{
  "name": "FetchError",
  "message": "request to http://127.0.0.1:10001/devstoreaccount1?comp=list&include=metadata&timeout=30 failed, reason: connect ECONNREFUSED 127.0.0.1:10001",
  "stack": "FetchError: request to http://127.0.0.1:10001/devstoreaccount1?comp=list&include=metadata&timeout=30 failed, reason: connect ECONNREFUSED 127.0.0.1:10001\n    at ClientRequest.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1483:11)\n    at ClientRequest.emit (events.js:315:20)\n    at Socket.socketErrorListener (_http_client.js:469:9)\n    at Socket.emit (events.js:315:20)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
  "type": "system",
  "errno": "ECONNREFUSED",
  "code": "ECONNREFUSED"
}

**Comment by MRayermannMSFT** [comment]
Hey @OzBob is your emulator running?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having problems, we suggest opening an Azure support ticket via the portal.
