### ISSUE TITLE
Deleting message in Batches  - Storage Queue (Feature request)

### ISSUE THREAD

**Issue by apsarpasha** [microsoft/AzureStorageExplorer#514]
**Storage Explorer Version**: 1.1.0
**Platform/OS Version**:  Windows 
**Architecture**: 64 Bit
**Regression From**: Not sure
#### Steps to Reproduce: ####
1. 

In storage explorer, I could not see any option to delete the messages from queue(storage) in Batches.  (example, If need to delete below highlighted messages at a time, I do not see any options)

1.	Clear queue – which delete all the messages 
2.	Dequeue Message  - which deletes first message.
3.	Delete the queue  - deleting queue as whole. 

2. 

#### Actual Experience: ####

![image](https://user-images.githubusercontent.com/33099220/43406870-caa7313a-943a-11e8-9281-124c9b821aff.png)
![storage explorer](https://user-images.githubusercontent.com/33099220/43406905-de9badd8-943a-11e8-83dd-6029891aa4cf.PNG)

**Comment by richardMSFT** [comment]
Hi! This feature will be shipping with 1.30.
