### ISSUE TITLE
Navigate directly to blob resource by URL

### ISSUE THREAD

**Issue by mjpost** [microsoft/AzureStorageExplorer#5140]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

This is a repeat of an old issue (#3279), but that one seems to have been ignored. The problem is that ASE does not seem to support navigating directly to an Azure blob, even when provided with a URL that ASE itself generated!

This is the #1 pain point for me when using ASE. To me, the fact that you can't do this almost breaks the tool. An analogous situation is if someone gave you the URL `https://github.com/microsoft/AzureStorageExplorer/issues/5140`, and instead of typing it directly in the browser address bar, you had to:

* Go to the com domain
* Scroll down to find "github"
* Page through all the accounts until you found the "microsoft" account
* Page through its projects and select "AzureStorageExplorer"
* Click on the "Issues" tab
* Page through to get to issue 5140

### Desired Solution

I should be able to paste in the URL and ASE would load the blob directly, instead of requiring me to click there, top-down.

**Comment by mjpost** [comment]
This is a repeat of an old issue (#3279), but that one seems to have been ignored.

This is the #1 pain point for me when using ASE. To me, the fact that you can't do this almost breaks the tool. An analogous situation is if someone gave you the URL `https://github.com/microsoft/AzureStorageExplorer/issues/5140`, and instead of typing it directly in the browser address bar, you had to:

* Go to the com domain
* Scroll down to find "github"
* Page through all the accounts until you found the "microsoft" account
* Page through its projects and select "AzureStorageExplorer"
* Click on the "Issues" tab
* Page through to get to issue 5140

**Comment by emjotde** [comment]
Same, hear our pleas.
That's one of those things that makes me wonder if the developer of AzureStorageExplorer are actually using it themselves for anything :)

**Comment by JasonYeMSFT** [comment]
Thanks for bringing this up. I have moved the mentioned feature request to a different milestone so it is guaranteed to be revisited in our next planning meeting. I am going to close this issue as a dup and continue the discussion there.

If possible, could you take a look at my follow up question in #3279 so we can better understand how the feature suppose to work?
