### ISSUE TITLE
'no data available' information for fileshares

### ISSUE THREAD

**Issue by JochemBoersma** [microsoft/AzureStorageExplorer#5141]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.23.1

### Regression From

not known

### Architecture

x64

### Storage Explorer Build Number

20211020.2

### Platform

Windows

### OS Version

Windows 10

### Bug Description

information when selecting empty fileshares is incorrect:

![image](https://user-images.githubusercontent.com/17458761/140418155-cab206ec-3c38-4619-9322-d39e91c745e3.png)

'blob container' should be 'file share'

### Steps to Reproduce

1. Launch Storage Explorer
2. Select an empty Fileshare (create one, if needed)
3. Look at the main window.

### Actual Experience

information when selecting empty fileshares is incorrect:

![image](https://user-images.githubusercontent.com/17458761/140418155-cab206ec-3c38-4619-9322-d39e91c745e3.png)

'blob container' should be 'file share'

### Expected Experience

information when selecting empty fileshares is incorrect
'blob container' should be 'file share'

**Comment by MRayermannMSFT** [comment]
@JochemBoersma to be clear, you are simply reporting that the string is wrong, correct?

**Comment by JochemBoersma** [comment]
Indeed. 
Although it's uttermost easy, it confused me 4 or 5 seconds when i saw this messages, since I had both blob storage and file shares in particular storage account...

I think it can be fixed in same time :).

**Comment by MRayermannMSFT** [comment]
> I think it can be fixed in same time :).

😛

**Comment by MRayermannMSFT** [comment]
![image](https://user-images.githubusercontent.com/21112697/141875178-edf63f25-8832-4d41-b17a-1a89839d733a.png)
Removed any notion of blob container as file share since we also show this message for empty folders!
