### ISSUE TITLE
Data Lake Store won't browse to more than 100 folder items

### ISSUE THREAD

**Issue by ivberg-zz** [microsoft/AzureStorageExplorer#515]
**Storage Explorer Version**: 1.3.1 (Latest)
**Platform/OS Version**: Win10 - 17715.1001
**Architecture**: ia32? (amd64)
**Regression From**: no

#### Steps to Reproduce: ####
1. Open Sub with Data Lake Store. Browse folder structure. If a folder has more than 100 items there is no way to see more.
2. UI shows "Showing 1 to 100 of 175 cache items", but there is no way to get to next 100

#### Expected Experience: ####
That I can browse all folders / data in Azure Data Lake

#### Actual Experience: ####
I cannot get to the folder I need to as it's alphabetically not in the front of the alphabet

**Comment by ziyel** [comment]
@ivberg could you try the latest version of Azure Storage Explorer?
There has paging to handle this.
![image](https://user-images.githubusercontent.com/1286176/56635122-074b9700-6697-11e9-93b6-2e3a7690bbee.png)

**Comment by jinglouMSFT** [comment]
The retirement of ADLS Gen1 is now less than three months away. As [previously announced](https://azure.microsoft.com/en-us/updates/action-required-switch-to-azure-data-lake-storage-gen2-by-29-february-2024/) the service will be retired on 29 February 2024. With this date now close approaching we are going to close this issue as "won't fix". Documentation on how to migrate your data to ADLS Gen2/blob storage can be found here: https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-migrate-gen1-to-gen2-azure-portal

If you have any non ADLS Gen1 feedback for Storage Explorer, please feel free to open a new issue: https://github.com/microsoft/AzureStorageExplorer/issues/new/choose

This issue will now no longer be monitored.
