### ISSUE TITLE
The 'Search by prefix (case-sensitive)' box is not case sensitive when running search

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5168]
**Storage Explorer Version**: 1.22.0-dev
**Build Number**: 20211110.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous releases (1.21.3)

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a new file share -> Upload one file which name is beginning with a lower case.
3. Type its upper case of the first character of the file name to 'Search by prefix (case-sensitive)' box.
4. Check the file doesn't display.

## Expected Experience ##
The file doesn't display.

## Actual Experience ##
The file displays.
![image](https://user-images.githubusercontent.com/41351993/141067658-e5a7d4de-bd1e-4c06-a129-c68ddd4cf1d8.png)

**Comment by MRayermannMSFT** [comment]
It seems like newer versions of the storage api let make prefix for listing files and directories case-insensitive. We'll update the string.

**Comment by MRayermannMSFT** [comment]
String has been changed.

**Comment by v-xianya** [comment]
Verified on the build 20211116.4. Reproduce. so we are going to reopen it and verify on a newer build.

**Comment by MRayermannMSFT** [comment]
@v-xianya to be clear, the new expectation is that the prefix search for file share explorer is case-insensitive, and the string should reflect that:
![image](https://user-images.githubusercontent.com/21112697/142037563-e5ea0234-9820-4d5e-9461-c75154ec41d4.png)
