### ISSUE TITLE
An error dialog pops up when cloning/pasting one file share

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5169]
**Storage Explorer Version**: 1.22.0-dev
**Build Number**: 20211110.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous releases (1.21.3)

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Select one file share -> Clone the file share with a valid name.
3. Check whether succeed to clone.

## Expected Experience ##
Succeed to clone.

## Actual Experience ##
An error dialog pops up.
![image](https://user-images.githubusercontent.com/41351993/141063800-964b030f-b46c-487c-a88e-c07983eca5b8.png)
![image](https://user-images.githubusercontent.com/41351993/141063848-cae6ca4c-0d7c-4d2c-973f-816af55d6b53.png)

## More Info ##
1. There is an ongoing activity log even though the error dialog is closed.
![image](https://user-images.githubusercontent.com/41351993/141064227-1414d61b-5165-4698-8b71-233e0b052cf2.png)
2. The cloned file share displays on the tree view.

**Comment by JasonYeMSFT** [comment]
That PR has been merged.

**Comment by MRayermannMSFT** [comment]
Thanks!

**Comment by v-xianya** [comment]
Verified on the build main 20211110.13. Fixed.
