### ISSUE TITLE
Setting a custom proxy breaks access to local resources (Azure Storage Emulator)

### ISSUE THREAD

**Issue by oddeirik** [microsoft/AzureStorageExplorer#517]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Windows 10 Enterprise b1607
**Architecture**: ia32
**Regression From**: n/a

#### Steps to Reproduce: ####
1. Set a custom proxy in Edit -> Configure Proxy
2. Try to access Azure Storage Emulator storage account under "(Local and attached)"
3. You should get an error message:

![image](https://user-images.githubusercontent.com/10148/43449254-40000680-94b0-11e8-8bc2-bcec09f74af0.png)

4. Disable custom proxy
5. Access to local resources should now work again

#### Expected Experience: ####
The proxy should not be used for local resources

#### Actual Experience: ####
The proxy seems to be used to try and access local resources, which causes it to fail.

**Comment by craxal** [comment]
We've released 1.4.0 recently, which changes how we interact with emulators. Please update to 1.4.0 and use the following steps to connect to the emulator:

1. Click the **Add Account** button (plug button on the left).
2. Select "Attach to a local emulator" and click **Next*.
3. Enter the port numbers that the emulator services will listen on.
4. Create the connection and start the emulator.

**Comment by craxal** [comment]
Do you have actual Azure resources you can try to access through your proxy? Can you connect to them successfully?

Unfortunately, there does not appear to be a way to bypass proxy settings for local connections using the Azure client library we have at the moment. Perhaps, when the library makes HTTP requests for configurable, we can continue to look into this.

**Comment by oddeirik** [comment]
Yes, I can access Azure resources with the custom proxy defined just fine. This is a corporate environment, so all external traffic has to go through the proxy.

It's not a big issue, it's just a matter of turning the proxy off in Storage Explorer when dealing with the storage emulator. A minor annoyance, that's all 😃

**Comment by MRayermannMSFT** [comment]
@oddeirik , ok, sounds good. As @craxal said, we'll look into being more smart about when not to use proxy once the azure storage node library is able to provide us with some more complex behaviors. 😄

**Comment by craxal** [comment]
@anmolbk, thank you for your suggestion. That's actually been on our fix list for a very long time. We will definitely add it in when we're able.

**Comment by btshowers** [comment]
I don't know if you want a new issue or not, but I've found that while using Storage Explorer 1.6.2 to connect to Azure Stack on prem, I have to toggle from No Proxy to Use proxy and then back to No proxy to connect.  Let me know if you want a separate issue for this.

**Comment by dterziev** [comment]
> I don't know if you want a new issue or not, but I've found that while using Storage Explorer 1.6.2 to connect to Azure Stack on prem, I have to toggle from No Proxy to Use proxy and then back to No proxy to connect. Let me know if you want a separate issue for this.

Similar issue with Storage Explorer 1.7.0 - if proxy is set, it is being used to connect to the local emulator on 127.0.0.1 and that does not work. When I toggle to No Proxy and refresh the storage accounts, it shows the blob containers in the local emulator, but when trying to access any of them it still uses the old proxy settings. Restarting the application fixes the issue, but then I can't access my Azure storage accounts because that requires a proxy. 

Seems like the proxy settings are not immediately applied everywhere when set.

Would it be possible to add an option to bypass the proxy when connecting to local emulators, or maybe add proxy settings per storage account?

**Comment by MRayermannMSFT** [comment]
Related to #1534

**Comment by MRayermannMSFT** [comment]
@craxal, please notify all commenters on this issue that this should be fixed in 1.16, after we ship.

**Comment by JasonYeMSFT** [comment]
@oddeirik @btshowers @dterziev We have shipped a fix for this in 1.16.0. If you are still running into problems, please open a new issue instead. Thanks.
