### ISSUE TITLE
Inconsistent casing in CORS activity log messages

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5175]
**Storage Explorer Version**: 1.22.0-dev
**Build Number**: 20211110.13
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous releases (1.21.3)

## Steps to Reproduce ##
1. Expand one storage account -> Right click the 'Blob Containers' node.
2. Click 'Configure CORS Settings...' -> Click 'Save'.
3. Observe the activity log -> Check whether the first character of the word 'blob' is capitalized.

## Expected Experience ##
The first character of the word 'blob' is capitalized.
![image](https://user-images.githubusercontent.com/41351993/141257181-092888e5-3515-4f50-8323-3033e8a8cdf0.png)

## Actual Experience ##
The first character of the word 'blob' is not capitalized.
![image](https://user-images.githubusercontent.com/41351993/141257503-226576cd-1ddf-49eb-8545-0efe2a960fe4.png)

**Comment by MRayermannMSFT** [comment]
Going to flip this issue around. We prefer the lowercasing!

**Comment by craxal** [comment]
This is already fixed for tables after table functionality was moved to the extension.

**Comment by v-xianya** [comment]
Verified this issue on the build 20220308.2. Fixed for tables.
![image](https://user-images.githubusercontent.com/41351993/157154804-addf77cb-83b1-4385-961a-68a0a1959971.png)

**Comment by v-xianya** [comment]
Will verify this issue when there is a new build.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220315.1. Fixed.

![image](https://user-images.githubusercontent.com/41351993/158292108-60e15cc0-d182-4244-ae2d-f2dac7a1492e.png)
