### ISSUE TITLE
Table query doesn't work correctly (can't filter the matched entities)

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5176]
**Storage Explorer Version**: 1.22.0-dev
**Build Number**: 20211110.13
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous releases (1.21.3)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Add some entities.
3. Click 'Query' -> Add clauses to query.
4. Check whether filter the matched entities.
## Expected Experience ##
Filter the matched entities.

## Actual Experience ##
Do not filter the matched entities (still show all entities).

**Comment by craxal** [comment]
@v-xianya This is strange, as I haven't seen this lately. Can you please share some screenshots or the query that you're building?

**Comment by v-xianya** [comment]
Hi @craxal Here is the screenshot
![image](https://user-images.githubusercontent.com/41351993/141397217-13a216eb-fd02-4318-8f1f-4f13caf55208.png)

**Comment by v-xianya** [comment]
Verified on the build main/20211115.2. Fixed.
