### ISSUE TITLE
My blob storage disappeared

### ISSUE THREAD

**Issue by cjrmtou** [microsoft/AzureStorageExplorer#5181]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.3

### Architecture

x64

### Storage Explorer Build Number

20211020.2

### Platform

Windows

### OS Version

Windows 10

### Bug Description

see file attached.
[errorReport.txt](https://github.com/microsoft/AzureStorageExplorer/files/7534321/errorReport.txt)

### Steps to Reproduce

1. Launch Azure storage explorer;
2. Open the only blob container I have;
3. Nothing left in my container;

### Actual Experience

The above steps are exactly my experience.

### Expected Experience

get my files back

**Comment by MRayermannMSFT** [comment]
Hi @cjrmtou 

The error you provided looks to be from expanding a Blob Containers node in the tree view. It also indicates that perhaps you are simply missing the right RBAC roles to list containers. Can you share what RBAC roles you have for the storage account you are attempting to work with?

**Comment by cjrmtou** [comment]
Thanks for your response, MRayermannMSFT.
I figured out it's b/c my 30 day free trial expired. After I renewed my subscription, everything comes back. 
Thank you!
