### ISSUE TITLE
A new file share tab is opened even though there is a file share tab which is opened by attaching it

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5183]
**Storage Explorer Version:** 1.22.0-dev
**Build Number:** 20211115.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> File Shares.
2. Create a file share -> Right click the file share.
3. Click 'Get Shared Access Signature...' -> Create and copy the SAS URL.
4. Attach this file share via the SAS URL -> A file share tab is opened.
5. Right click the attached file share -> Click 'Open'.
6. Check no new file share tab is opened.

## Expected Experience ##
No new file share tab is opened.

## Actual Experience ##
A new file share tab is opened.

## Additional Context ##
This issue also reproduces when double clicking the attached file share.

**Comment by v-xianya** [comment]
Verified on the build main/20211201.1. Fixed.
