### ISSUE TITLE
error to open blob containers

### ISSUE THREAD

**Issue by JianJiao16** [microsoft/AzureStorageExplorer#5185]
Hi Team,

Can anyone please help with the issue below? It used to work. 

Here are the error message. 

Unable to retrieve child resources.

Details:
{
  "name": "RestError",
  "message": "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:77fab281-e01e-002a-524f-da580e000000\nTime:2021-11-15T18:37:13.7196084Z",
  "stack": "RestError: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:77fab281-e01e-002a-524f-da580e000000\nTime:2021-11-15T18:37:13.7196084Z\n    at new RestError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:2390:28)\n    at handleErrorResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:3274:17)\n    at C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:3210:18\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
  "code": "AuthenticationFailed",
  "statusCode": 403,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://bingadseuunifiedstorage.blob.core.windows.net/?include=metadata&comp=list",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2020-04-08"
        },
        "user-agent": {
          "name": "user-agent",
          "value": "Microsoft Azure Storage Explorer, 1.20.1, win32 azsdk-js-storageblob/12.4.1 (NODE-VERSION v12.16.3; Windows_NT 10.0.17763)"
        },
       ....
    "status": 403,
    "bodyAsText": "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:77fab281-e01e-002a-524f-da580e000000\nTime:2021-11-15T18:37:13.7196084Z</Message><AuthenticationErrorDetail>The MAC signature found in the HTTP request 'NQmCjqKSUMxKyMQHnSwKUI1ewEu5TP0dW3BiWqVcklA=' is not the same as any computed signature. Server used following string to sign: 'GET\n\n\n\n\n\n\n\n\n\n\n\nx-ms-client-request-id:63c3821d-f4d4-4267-9bfe-40a5fa4a0ec6\nx-ms-date:Mon, 15 Nov 2021 18:37:13 GMT\nx-ms-version:2020-04-08\n/bingadseuunifiedstorage/\ncomp:list\ninclude:metadata'.</AuthenticationErrorDetail></Error>",
    "parsedBody": {
      "message": "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:77fab281-e01e-002a-524f-da580e000000\nTime:2021-11-15T18:37:13.7196084Z",
      "code": "AuthenticationFailed",
      "AuthenticationErrorDetail": "The MAC signature found in the HTTP request 'NQmCjqKSUMxKyMQHnSwKUI1ewEu5TP0dW3BiWqVcklA=' is not the same as any computed signature. Server used following string to sign: 'GET\n\n\n\n\n\n\n\n\n\n\n\nx-ms-client-request-id:63c3821d-f4d4-4267-9bfe-40a5fa4a0ec6\nx-ms-date:Mon, 15 Nov 2021 18:37:13 GMT\nx-ms-version:2020-04-08\n/bingadseuunifiedstorage/\ncomp:list\ninclude:metadata'."
    },
    "parsedHeaders": {
      "requestId": "77fab281-e01e-002a-524f-da580e000000",
      "errorCode": "AuthenticationFailed",
      "content-length": "741",
      "content-type": "application/xml",
      "date": "Mon, 15 Nov 2021 18:37:13 GMT",
      "server": "Microsoft-HTTPAPI/2.0"
    }
  },
  "details": {
    "requestId": "77fab281-e01e-002a-524f-da580e000000",
    "errorCode": "AuthenticationFailed",
    "content-length": "741",
    "content-type": "application/xml",
    "date": "Mon, 15 Nov 2021 18:37:13 GMT",
    "server": "Microsoft-HTTPAPI/2.0",
    "message": "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:77fab281-e01e-002a-524f-da580e000000\nTime:2021-11-15T18:37:13.7196084Z",
    "code": "AuthenticationFailed",
    "AuthenticationErrorDetail": "The MAC signature found in the HTTP request 'NQmCjqKSUMxKyMQHnSwKUI1ewEu5TP0dW3BiWqVcklA=' is not the same as any computed signature. Server used following string to sign: 'GET\n\n\n\n\n\n\n\n\n\n\n\nx-ms-client-request-id:63c3821d-f4d4-4267-9bfe-40a5fa4a0ec6\nx-ms-date:Mon, 15 Nov 2021 18:37:13 GMT\nx-ms-version:2020-04-08\n/bingadseuunifiedstorage/\ncomp:list\ninclude:metadata'."
  }
}

**Comment by shijieyao** [comment]
Facing the same problem.
Pinged @MRayermannMSFT thru MSFT internal Teams.

**Comment by shijieyao** [comment]
Solved.
By updating the password in the connection string, I don't see such error anymore.

**Comment by MRayermannMSFT** [comment]
For

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having problems, we suggest opening an Azure support ticket via the portal.
