### ISSUE TITLE
The value of the 'Timestamp' for one emulator entity displays as [object Object]

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5186]
**Storage Explorer Version**: 1.22.0-dev
**Build Number**: 20211116.5
**Branch**: main
**Platform/OS**: Windows 10
**Architecture**: ia32
**Azurite Version**: 3.14.3
**How Found**: From running test cases
**Regression From**: Previous releases (1.21.3)

## Steps to Reproduce ##
1. Install and running Azurite 3.14.3 -> Launch Storage Explorer.
2. Expand 'Local & Attached -> Storage Accounts -> (Emulator - Default Ports) (Key)'.
3. Right click the 'Tables' node -> Create a new table -> Add one entity.
4. Check whether the value of the 'Timestamp' displays well.

## Expected Experience ##
The value of the 'Timestamp' displays well.

## Actual Experience ##
The value of the 'Timestamp' displays as [object Object].
![image](https://user-images.githubusercontent.com/41351993/141937320-67df22da-8d82-471e-9daa-bbbc957e2655.png)

**Comment by craxal** [comment]
This is a known issue in Azurite: Azure/Azurite#/1162

**Comment by craxal** [comment]
Added a small workaround that normalizes the form we use in the code.

**Comment by v-xianya** [comment]
Verified on the build main/20211201.1. Reproduce, so we are going to re-open it.
![local](https://user-images.githubusercontent.com/41351993/144160942-31c2f8cf-b041-4912-b51c-513443fc7b36.gif)

**Comment by craxal** [comment]
@v-xianya We just need to update the extension version (sorry, I was a bit eager). I was waiting till a few more fixes got in before updating.

**Comment by v-xianya** [comment]
Verified on the build main/20211202.7. Fixed.
