### ISSUE TITLE
No upload dialog pops up when clicking 'Upload Files...'/'Upload Folder...' for blob containers/file shares

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5188]
**Storage Explorer Version:** 1.22.0-dev
**Build Number:** 20211116.5
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Previous releases (1.21.3)

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Click 'Upload -> Upload Folder...'.
3. Check whether the 'Upload Folder' dialog pops up.

## Expected Experience ##
The 'Upload Folder' dialog pops up.

## Actual Experience ##
No 'Upload Folder' dialog pops up.

**Comment by v-xianya** [comment]
Verified on the build 20211116.13. Fixed.
