### ISSUE TITLE
The 'Add' button is disabled on the 'Add Custom Environment' dialog even though closing the error dialog caused by typing 'https://azure.com' as the ARM endpoint then typing a correct ARM endpoint

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5190]
**Storage Explorer Version**: 1.22.0-dev
**Build Number**: 20211116.5
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**Architecture**: ia32/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Open the connect dialog.
2. Click 'Subscription -> Custom Environment' -> Click 'Manage custom environments...'.
3. Click 'Add' -> Type a valid environment name -> Type 'https://azure.com' to the 'ARM endpoint' field.
4. Click 'Add' -> An error dialog pops up.
5. Close the error dialog -> Type the correct ARM endpoint 'https://management.azure.com'.
6. Check whether the 'Add' button is enabled.

## Expected Experience ##
The 'Add' button is enabled.

## Actual Experience ##
The 'Add' button is disabled.
![image](https://user-images.githubusercontent.com/41351993/141954746-9f59b9d0-0731-4d15-a6a7-8e751e5d7e74.png)

## Additional Context ##
Here is the error screenshot:
![image](https://user-images.githubusercontent.com/41351993/141954604-45550b06-c990-4111-9a12-497809fe511b.png)

**Comment by v-xianya** [comment]
@MRayermannMSFT 
Verified on the build main/20211123.1. 
There is an error when typing the correct 'ARM endpoint'. Could you help to take a look?
![image](https://user-images.githubusercontent.com/41351993/142960099-56ca77e5-9ce2-4d46-86d9-c2e76718d02d.png)

**Comment by MRayermannMSFT** [comment]
@v-xianya in tonight's build I've added some logging to this code path. Can you please repro what you are seeing and then share your log files here? I am unfortunately unable to repro this.

**Comment by v-xianya** [comment]
@MRayermannMSFT 
The log files get from C:\Users\AzureTest\AppData\Roaming\StorageExplorer\Microsoft Azure Storage Explorer\logs
[2021-11-23_183447_renderer.log](https://github.com/microsoft/AzureStorageExplorer/files/7592417/2021-11-23_183447_renderer.log)
[2021-11-23_183447_se-blob-extension_10696.log](https://github.com/microsoft/AzureStorageExplorer/files/7592418/2021-11-23_183447_se-blob-extension_10696.log)

Here is the record:
![test12](https://user-images.githubusercontent.com/41351993/143162702-1e9647e4-2fa3-416f-8bd4-8699e3d145c2.gif)

**Comment by MRayermannMSFT** [comment]
@v-xianya OHHHHH I understand the bug now. 😆  I thought you clicked "add" and the add failed again with an error. I will gladly fix this. Thanks for the gif!

**Comment by MRayermannMSFT** [comment]
Ok fixed.

**Comment by v-xianya** [comment]
Verified on the build 20211125.2. Fixed.
