### ISSUE TITLE
The 'Settings' panel is not clear when the system is in High Contrast Black/White mode and the storage explorer is in High Contrast White/Black mode

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5191]
**Storage Explorer Version:** 1.22.0-dev
**Build Number:** 20211117.3
**Branch:** main
**Platform/OS:** Windows 10
**Architecture:** ia32
**How Found:** From running test cases
**Regression From:** Previous build (20211028.1)

## Bug Description ##
When the system is in High Contrast Black mode, storage explorer is in High Contrast White or Light mode:

  - The 'Settings' panel is not clear.
  - The 'Release Notes' panel is not clear.
  - The 'ACCOUNT MANAGEMENT' panel is not clear.

When the system is in High Contrast White mode and storage explorer is in High Contrast Black mode, these panels are not clear.

## Steps to Reproduce ##

1. Turn on the system High Contrast Black mode.
2. Launch Storage Explorer -> Go to the 'View' menu -> Change the theme to 'Light' or 'High Contrast - White'.
3. Click 'Settings' -> Check whether the 'Settings' panel is clear.

## Expected Experience ##
The 'Settings' panel is clear.

## Actual Experience ##
The 'Settings' panel is not clear.
![image](https://user-images.githubusercontent.com/87792676/142172859-15322555-86c6-404e-accf-2dc55005cab8.png)

## Additional Context ##
This issue doesn't reproduce on Linux & Mac.

**Comment by craxal** [comment]
This is the same problem as #4636. There is an open bug against Electron.
