### ISSUE TITLE
It would be better to add an error and disable the 'Create' button when creating snapshot for one disk whose name has 80 characters

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5193]
**Storage Explorer Version:** 1.22.0-dev
**Build Number:** 20211118.3
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**Architecture:** ia32/x64
**How Found:** Exploratory testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand the 'Disks' node -> Open one resource group.
2. Upload one disk whose name has 80 characters ->  Click 'Create Snapshot'.
3. The 'Create Snapshot' dialog pops up -> The default snapshot name is more than 80 characters.
5. Check an error occurs and the 'Create' button is disabled.

## Expected Experience ##
An error occurs and the 'Create' button is disabled.

## Actual Experience ##

1. No error occurs and the 'Create' button is enabled.
2. There is a failed activity log after clicking 'Create' button.
![image](https://user-images.githubusercontent.com/87792676/142382892-51dc0a16-bc38-48f2-8a15-d43553596357.png)

**Comment by MRayermannMSFT** [comment]
We will no longer suggest a name that is too long.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20211123.1. Fixed.
