### ISSUE TITLE
No error occurs when creating a table named 'Table' if there is already a table named 'table'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5194]
**Storage Explorer Version**: 1.22.0-dev
**Build Number**: 20211118.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.21.3)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a new table using the name 'table'.
3. Create another table using the name 'Table'.
4. Check an error occurs.

## Expected Experience ##
An error occurs.
![image](https://user-images.githubusercontent.com/41351993/142390175-e4801225-1027-45be-8cc9-0e468276c172.png)

## Actual Experience ##
No error occurs and succeed to create a table with name 'Table'.
![image](https://user-images.githubusercontent.com/41351993/142390424-d3bb28b7-3e71-42f8-ba2c-b1b3d76d17d4.png)

## Additional Context ##
The table 'Table' disappears after manually refreshing.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20211121.3. Fixed
