### ISSUE TITLE
Unable to view Containers

### ISSUE THREAD

**Issue by amillion8** [microsoft/AzureStorageExplorer#5195]
I am unable to view Containers for storage accounts, even after repeatedly reconnecting to my Azure account:

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://edpanalyticsdev.blob.core.windows.net/?comp=list&include=metadata failed, reason: unable to get local issuer certificate",
  "stack": "FetchError: request to https://edpanalyticsdev.blob.core.windows.net/?comp=list&include=metadata failed, reason: unable to get local issuer certificate\n    at ClientRequest.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1483:11)\n    at ClientRequest.emit (events.js:315:20)\n    at TLSSocket.socketErrorListener (_http_client.js:469:9)\n    at TLSSocket.emit (events.js:315:20)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
  "type": "system",
  "errno": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY",
  "code": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"
}

**Comment by MRayermannMSFT** [comment]
Hi, it sounds like you are having an SSL certificates issue. We have to recommended paths forward for you:

- Try using system proxy, which you can read about in our networking documentation: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network There are some limitations to it, so make sure you understand those.
- Try setting certificates manually. You can read about this process in our troubleshooting guide for additional help with that: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#ssl-certificate-issues

If neither of those help feel free to come back here to let us know what happened.

**Comment by amillion8** [comment]
Thank you Matthew, I was able to resolve the issue
