### ISSUE TITLE
StorageExplorerのプレフィックス検索の項目が表示されない

### ISSUE THREAD

**Issue by Mio-Biplogy** [microsoft/AzureStorageExplorer#5196]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.3

### Architecture

x64

### Storage Explorer Build Number

20211020.2

### Platform

Windows

### OS Version

Windows10

### Bug Description

StorageExplorerのプレフィックス検索の項目が表示されません。

SRにて最新バージョンの再インストールをご提案いただきましたが、改善されませんでした。

状況としては、プレフィックス検索の項目が常に表示されないわけではなく、1度だけ出たこともあります。

### Steps to Reproduce

StorageExplorerを起動します。コンテナをクリックして右側にそのリソースが表示されますが、プレフィックス検索項目が表示されるべきボックス左側には何も表示されません。

### Actual Experience

StorageExplorerを起動します。コンテナをクリックして右側にそのリソースが表示されますが、プレフィックス検索項目が表示されるべきボックス左側には何も表示されません。

### Expected Experience

StorageExplorerを起動します。コンテナをクリックして右側にそのリソースが表示され、ボックス右側にプレフィックス検索項目が表示されることが期待されます。

**Comment by MRayermannMSFT** [comment]
@Mio-Biplogy we ran your issue through Google translate and I think we understand what it is you are talking about? Are you saying that you don't see the "search by prefix" text box when looking at a container? If so:

- For the containers where you do not see the "search by prefix" text box, do the account nodes for those containers have a "(ADLS Gen2)" next to them? If yes then please understand that Storage Explorer does not currently support search by prefix for ADLS Gen2 containers.
- For non-ADLS Gen2 containers, we recently moved the "search by prefix" text box behind a button:
![image](https://user-images.githubusercontent.com/21112697/142917038-bc9d0c43-df9f-4e97-af4a-48f6afea3ff5.png)
Perhaps you just need to click that button?

If our understanding of our issue is wrong, could you please try recording a video or taking some screenshots that can help us understand. Thank you!

**Comment by Mio-Biplogy** [comment]
Thanks, MRayermannMSFT 

I got that Storage Explorer does not currently support search by prefix for ADLS Gen2 containers.
Do you have any plans to support it for ADLSGen2 someday?

**Comment by MRayermannMSFT** [comment]
> Do you have any plans to support it for ADLSGen2 someday?

Yes. Please follow this issue: https://github.com/microsoft/AzureStorageExplorer/issues/2189

Does that answer/resolve this issue?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please follow the issue we linked for updates on prefix search in gen2.
