### ISSUE TITLE
The QA table doesn't display as broken when deleting the original table

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5197]
**Storage Explorer Version**: 1.22.0-dev
**Build Number**: 20211119.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.21.3)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Add the table to quick access.
3. Delete the table -> Check whether the QA table displays as broken.

## Expected Experience ##
The QA table displays as broken.

## Actual Experience ##
The QA table displays well.

**Comment by craxal** [comment]
I've observed the same behavior with blob containers and file shares as well. I don't think we need to fix this for 1.22.0.

**Comment by v-xianya** [comment]
@craxal Verified this issue on the build 20220211.3. Fixed.
The QA table auto displays as broken when deleting the original table.

For blob container and file share, there are bugs [1389](https://github.com/microsoft/AzureStorageExplorer/issues/1389), [2671](https://github.com/microsoft/AzureStorageExplorer/issues/2671) that were closed as Won't fix:
