### ISSUE TITLE
Casing of 'Query string' is wrong on 'Generate Shared Access Signature' dialog

### ISSUE THREAD

**Issue by v-dantch** [microsoft/AzureStorageExplorer#520]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Win10 /MacOS High Sierra /Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20180730.1
**Commit**: 17eb92a4
**Regression From**: Not a Regression

#### Steps to Reproduce: ####
1. Right click one storage account -> select 'Get Shared Access Signature...' ->click 'Create' on 'Generate Shared Access Signature' dialog.
2. Check the 'Query string'.

#### Expected Experience: ####
Display 'Query **String**'.

#### Actual Experience: ####
Display 'Query **string**'.
![string](https://user-images.githubusercontent.com/34729092/43453006-66d88d7a-94a8-11e8-93c6-8979d85b6455.png)

**Comment by v-xianya** [comment]
Verified on the latest build 20190614.7. This issue doesn't reproduce. So we close it.
