### ISSUE TITLE
Succeed to create a table using the name of one table which is being deleted

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5201]
**Storage Explorer Version**: 1.22.0-dev
**Build Number**: 20211121.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.21.3)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Delete the table -> Then create a table using the name of the deleted table.
3. Check whether fail to create the table.

## Expected Experience ##
1. Fail to create the table.
2. An error indicating 'The specified table is being deleted' occurs.
![image](https://user-images.githubusercontent.com/41351993/142819488-491cdb85-2561-49be-8839-46d3c554db57.png)

## Actual Experience ##
1. Succeed to create the table.
2. The table is auto opened and an error info bar prompts.

![image](https://user-images.githubusercontent.com/41351993/142819892-7c2d0aa0-18be-47de-b191-dded23549ba9.png)

**Error info:**
`{"odata.error":{"code":"TableNotFound","message":{"lang":"en-US","value":"The table specified does not exist.\nRequestId:ef3b5f9d-f002-004e-5871-df3cc7000000\nTime:2021-11-22T07:19:07.4894971Z"}}}`
## Additional Context ##
The created table disappears after manually refreshing.

**Comment by craxal** [comment]
Appears to be the same root cause as #5200. The `createTable` function doesn't throw an error as expected.

Creating a table with the same name as one that's been deleted is not likely to be a common scenario. Even so, just waiting a few seconds is usually long enough to try creating the table again. We can address this for a future release once the SDK comes out with a fix.

**Comment by craxal** [comment]
See Azure/azure-sdk-for-js#18865.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220212.2. Fixed.
![image](https://user-images.githubusercontent.com/41351993/153824279-ccf3152e-ede6-4b6c-b746-d9bef6fcac91.png)

**Comment by craxal** [comment]
The "undefined" part is still a little unpolished feeling, so I'll make one change to fix that.
