### ISSUE TITLE
An extra scrollbar displays in the 'Shared Access Signature' dialog for tables when timestamp validation error occurs

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5202]
**Storage Explorer Version:** 1.22.0-dev
**Build Number:** 20211121.3
**Branch:** main
**Platform/OS:** Linux Ubuntu 20.04
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.21.3)

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create a table -> Right click the table -> Click 'Get Shared Access Signature...'.
3. Change the start time to make it is greater than the expire time.
4. There is an error message -> Check whether no extra scrollbar displays.

## Expected Experience ##
No extra scrollbar displays.

## Actual Experience ##
An extra scrollbar displays.
![image](https://user-images.githubusercontent.com/87792676/142825102-c546981f-386b-4f8a-8341-a3648ed90d5d.png)

## Additional Context ##
This issue doesn't reproduce on Windows & Mac.

**Comment by craxal** [comment]
The problem is the partition key/row key inputs have been forced onto separate lines. Not sure why they can't shrink in width to fit. Easiest solution is to increase the width of the dialog. We should think about reworking the dialog to use CSS grids instead of tables for better flexibility.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20211201.1. Fixed.
