### ISSUE TITLE
Support for Windows 11

### ISSUE THREAD

**Issue by aljbishop** [microsoft/AzureStorageExplorer#5203]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Unable to access the Explorer in Windows 11

### Desired Solution

Full support and access for Windows 11

**Comment by MRayermannMSFT** [comment]
Hi @aljbishop , as far as we have seen there is no issues related to trying to use Storage Explorer on Windows 11. Can you elaborate on what issues you are seeing? Have you tried reinstalling from https://storageexplorer.com ? Are you seeing any errors when trying to launch Storage Explorer?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having problems using Storage Explorer on Windows 11, please open a new issue with more specifics. Thanks!
