### ISSUE TITLE
The 'Row key' in the Entity restriction doesn't take effect when attaching one table

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5206]
**Storage Explorer Version**: 1.22.0-dev
**Build Number**: 20211123.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**Architecture**: ia32/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table (as the below).
![image](https://user-images.githubusercontent.com/41351993/142980889-12772f60-b836-40e0-a2da-e307975426e9.png)
3. Right click the table -> Click 'Get Shared Access Signature...'.
4. Type '1' to the 'Starting partition key' field -> Type '4' to the 'Starting row key' field.
5. Create SAS -> Copy the SAS URL -> Attach the table using the SAS URL.
6. Observe the entities of the attached table -> Check whether the row key takes effect.

## Expected Experience ##
The row key takes effect.

## Actual Experience ##
The row key doesn't take effect.
![image](https://user-images.githubusercontent.com/41351993/142987111-8b263a17-2b9d-405f-ba03-f32dba7dc290.png)

## Additional Context ##
You can get the table from [table.csv](https://github.com/microsoft/AzureStorageExplorer/files/7586208/table.csv).

**Comment by craxal** [comment]
@v-xianya Can you be more specific about the expected outcome?

Partition and row keys should not be considered as separate properties that you're filtering on in this case. It may be easier to think of them like 2D coordinates.

If we have a table like this:
Partition Key | Row Key
-|-
1|1
1|2
1|3
2|1
2|2
2|3
3|1
3|2
3|3

And we connect using a starting partition key of 2 and a starting row key of 2, you should see the following:
Partition Key | Row Key
-|-
2|2
2|3
3|1
3|2
3|3

**Comment by v-xianya** [comment]
@craxal Thank you for the sharing
For this issue, connect using a starting partition key of 2 and a starting row key of 4, the following would make sense.
I understand the starting point is (4,4)


<html>
<body>


Partition Key | Row Key
-- | --
4 | 4
5 | 5



</body>
</html>

BTW, What is the staring point if we set  a starting partition key of 2 and a starting row key of 5 for the below table?
<html>
<body>


Partition Key | Row Key
-- | --
1 | 2
2 | 3
3 | 4
4 | 5
5 | 6
6 | 7
7 | 8

</body></html>

**Comment by craxal** [comment]
@v-xianya I would expect the starting point would be (3, 4).
