### ISSUE TITLE
The original blob container tab is closed and no new blob container tab is opened after pasting the blob container to emulator Blob Containers node

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5207]
**Storage Explorer Version:** 1.22.0-dev
**Build Number:** 20211123.1
**Branch:** main
**Platform/OS:** Windows 10
**Architecture:** ia32
**Azurite Version:** 3.14.3
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create a blob container-> A blob container tab is opened.
3. Right click the blob container -> Click 'Copy Blob Container'.
4. Paste the blob container to emulator Blob Containers node.
5. Check whether a new blob container tab is opened.

## Expected Experience ##
A new blob container tab is opened.

## Actual Experience ##
The original blob container tab is closed and no new blob container tab is opened.

## Additional Context ##
This issue doesn't reproduce for tables.

**Comment by JasonYeMSFT** [comment]
The blob container copy targeting emulator is using the old JavaScript code so it still closes and will open the container if the copy succeeds. However, Azurite only supports copying data within the same instance so when the copy fails we don't open the new container https://github.com/Azure/Azurite/issues/767. However, according to https://github.com/Azure/Azurite/issues/699, copying external resources to the emulator is supported by the old .Net emulator. There is no way for us to distinguish whether the emulator supports copying from external resources so we will keep the copy/paste options enabled for now.
