### ISSUE TITLE
The first property is not focused after expanding the 'Properties' window

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/AzureStorageExplorer#521]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Win10 /MacOS High Sierra /Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20180730.1
**Commit**: 17eb92a4
**Regression From**: Not a Regression

#### Steps to Reproduce: ####
1. Select one storage account.
2. Click the group glyph to collapse the 'Properties' window.
3. Click the group glyph again to expand the 'Properties' window.

#### Expected Experience: ####
After Step2: The group glyph doesn't keep being focused.
After Step3: The first property is focused.

#### Actual Experience: ####
After Step2: Keep focusing the group glyph until after clicking elsewhere.
After Step3: The first property is not focused.
![focus](https://user-images.githubusercontent.com/34729092/43452193-5fd29c5c-94a6-11e8-8c51-93461608ca5b.png)

**Comment by craxal** [comment]
This is expected behavior. Why would you expect focus to jump to the first property?

**Comment by v-dantch** [comment]
Thanks for your update. Please get the reason from More Info.

More Info: 
The issue doesn't reproduce when expanding the 'Activities' windows. Please get the Repro 
Steps from below.

      Repro Steps:
      1. In 'Activities' window, make sure the first item 'Clear completed' link is not focused.
      2. Click the group glyph to collapse the 'Activities' window.
      3. Click the group glyph again to expand the 'Activities' window.

      Result:
      The first item - 'Clear completed' link is focused.

**Comment by craxal** [comment]
Not really sure why we have that behavior in the Activities panel. Either way, I don't consider this appropriate behavior. @jinglouMSFT can correct me if I'm wrong.

**Comment by jinglouMSFT** [comment]
The behavior with the property grid is what I had expected. The Activity's seems to be a bit odd. Did we modify the behavior when fixing the accessibility bugs (for the Activity window)?

**Comment by craxal** [comment]
My vague memory is in the past we reasoned it was "unproductive" for a user to expand the panel then tab to the next control, because how often would a user expand the panel but want to stay on the button? So we automatically transfer focus to the next control in the panel. But after our accessibility push, this behavior can actually be more confusing for users.
