### ISSUE TITLE
A new table tab can be opened by clicking 'Open' or double clicking the attached table even though a tab already opened by the attaching operation

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5210]
**Storage Explorer Version**: 1.22.0-dev
**Build Number**: 20211124.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**Architecture**: ia32/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Select one table -> SAS attach it.
3. A tab of the attached table is auto opened.
4. Right click the attached table -> Click 'Open'.
5. Check no new tab is opened.

## Expected Experience ##
No new tab is opened.

## Actual Experience ##
A new tab is opened.

## Additional Context ##
There is a '/' next to the path of the tab which is opened by the attaching operation. 
![image](https://user-images.githubusercontent.com/41351993/143196266-4df17fb0-0b50-4ffe-980f-8084385c0eb0.png)
There is no '/' next to the path of the tab by clicking 'Open' or double clicking the attached table.
![image](https://user-images.githubusercontent.com/41351993/143196277-929cd968-8b36-4b2b-8e0a-09d2b131af2a.png)

**Comment by MRayermannMSFT** [comment]
@craxal, can you double check if this is not a regression? If not, feel free to move to 1.23 .

**Comment by craxal** [comment]
Definitely not a regression from 1.23. Incidentally, attached file shares also has this problem. However, the fix is easy, as they both follow the same code path. They shouldn't need to append the slash when retrieving the node path.

**Comment by v-xianya** [comment]
Verified on the build main/20211201.1. Fixed.
