### ISSUE TITLE
The file name doesn't update after replacing the file using a file whose name just has case-differences

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5211]
**Storage Explorer Version**: 1.22.0-dev
**Build Number**: 20211124.5
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**Architecture**: ia32/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Upload one file 'test.txt'.
3. Then upload one file 'TEST.txt'.
4. There is a conflict dialog -> Select 'Replace' -> Click 'Apply'.
5. Check whether the file 'TEST.txt' displays.

## Expected Experience ##
The file 'TEST.txt' displays.

## Actual Experience ##
The file 'test.txt' displays. (the size of the file has been updated)
Here is the record:
![file](https://user-images.githubusercontent.com/41351993/143194144-5343957e-fe6a-4564-ac60-2ae83ffa30f3.gif)

**Comment by JasonYeMSFT** [comment]
Azure Files are case-preserving and case-insensitive. I guess once a file with an equivalent name is there, the new write operations will just be done on that file and won't update its name.

**Comment by MRayermannMSFT** [comment]
@JasonYeMSFT so we need AzCopy to fix this right?

**Comment by JasonYeMSFT** [comment]
It's done at the Azure Files service. AzCopy encodes the file name as is in the request, but the service matches the file to an existing one and ignores is case sensitive name.

**Comment by JasonYeMSFT** [comment]
![image](https://user-images.githubusercontent.com/39359541/143293287-a4991948-bc74-4caf-a37a-9a7d5d515bbd.png)

Won't fix for now since this is the service design.
