### ISSUE TITLE
It would be better to add the storage account name in the 'Table Statistics' activity log

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5216]
**Storage Explorer Version**: 1.22.0-dev
**Build Number**: 20211125.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**Architecture**: ia32/x64
**How Found**: Exploratory testing
**Regression From**: Previous release (1.21.3)
## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Click 'Tables Statistics' on the toolbar.
3. Observe the activity log -> Check whether the storage account name displays in the activity log.

## Expected Experience ##
The storage account name displays in the activity log.

## Actual Experience ##
The storage account name doesn't display in the activity log.
![image](https://user-images.githubusercontent.com/41351993/143416962-731787a2-8624-4c0b-9cfe-fa717da67bca.png)

## Additional Context ##
1. The screenshot from the previous release:
![image](https://user-images.githubusercontent.com/41351993/143416777-66950a00-491c-4920-859a-14dbf06a2ea6.png)

2. Related issue: [3380](https://github.com/microsoft/AzureStorageExplorer/issues/3380)

**Comment by MRayermannMSFT** [comment]
@craxal do we do this for file and blob stats? If so, then let's do it for table too. Otherwise probably fine to close as by design.

**Comment by v-xianya** [comment]
For files and blob stats, storage account name displays in the activity log.
![image](https://user-images.githubusercontent.com/41351993/143979239-9fa610c4-6e2d-42a7-8a4c-1b2a446beecb.png)

**Comment by v-xianya** [comment]
@craxal This issue reproduces on the build main 20211201.1.
 Is it not fixed yet? or won't fix?
![image](https://user-images.githubusercontent.com/41351993/144161532-e0cdc0aa-fb48-4580-be38-cf52e3053b34.png)

**Comment by craxal** [comment]
It is fixed, but I haven't updated the extension version just yet.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20211202.7. Fixed.
