### ISSUE TITLE
The orders of the blobs are inconsistent between the split tabs if the blobs are sorted by one column in original blob container before splitting it

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5217]
**Storage Explorer Version**: 1.22.0-dev
**Build Number**: 20211125.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**Architecture**: ia32/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload several blobs.
3. Order the blobs by the 'Name' column.
4. Split the tab of the blob container -> Observe the order of the blobs in the split tab.
5. Check whether the orders of the blobs are consistent between the two tabs.

## Expected Experience ##
The orders of the blobs are consistent between the two tabs.

## Actual Experience ##
The orders of the blobs are inconsistent between the two tabs.
![image](https://user-images.githubusercontent.com/41351993/143418316-35df55f6-0359-49f2-bbf4-e2a236eb566f.png)

**Comment by JasonYeMSFT** [comment]
The split view doesn't preserve the sorting order. This is by design at the moment and we are waiting for more feedback on it.
