### ISSUE TITLE
The strings in the 'Clone Table' dialog are not localized completely

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5218]
**Storage Explorer Version**: 1.22.0-dev
**Build Number**: 20211126.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**Architecture**: ia32/x64
**Languages**: French
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Français' -> Restart Storage Explorer.
3. Expand one storage account -> Tables.
4. Right click one table -> Click 'Clone...'.
5. Check whether the strings in the clone dialog are localized completely.

## Expected Experience ##
The strings in the clone dialog are localized completely.

## Actual Experience ##
The strings in the clone dialog are not localized completely.
![image](https://user-images.githubusercontent.com/41351993/143551250-9987caa2-d682-4d64-8c11-69858982b6ac.png)

## Additional Context ##
Verified this issue on all 18 languages, this issue doesn't reproduce in 'Korea'/Portuguese (Brazil)/'Swedish'.

**Comment by MRayermannMSFT** [comment]
@craxal make sure this is not hardcoded. If it isn't, feel free to move this to loc milestone and we can revisit later to make sure it got translated.

**Comment by craxal** [comment]
@MRayermannMSFT The string is not hardcoded. It's a new string, so translators will need time on it.
