### ISSUE TITLE
There is an extra scrollbar on the 'Upload' dialog for blobs

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5220]
**Storage Explorer Version:** 1.22.0-dev
**Build Number:** 20211126.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.6
**Architecture:** ia32\x64
**Language:** Japanese/Portuguese/Russian/French
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Français' -> Restart Storage Explorer.
3. Expand one non-ADLS Gen2 storage account -> Blob Containers.
4. Create a blob container -> Click 'Upload -> Upload Folder/Files...'.
5. Check there is no extra scrollbar on the 'Upload' dialog.

## Expected Experience ##
There is no extra scrollbar.

## Actual Experience ##
There is an extra scrollbar.
![image](https://user-images.githubusercontent.com/87792676/143551568-88c9d24a-a4c7-45d7-9839-866619fd6aa4.png)

**Comment by JasonYeMSFT** [comment]
I bumped the height of the dialog a little bit now the scroll bar should be gone.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20211130.2, it also reproduces on Japanese.
![image](https://user-images.githubusercontent.com/87792676/143977935-3553648f-3342-41c7-8f98-60770277682f.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20211201.1. Fixed.
![image](https://user-images.githubusercontent.com/87792676/144162612-9344ef60-0c3f-4ac2-94be-4f407f8022e4.png)
