### ISSUE TITLE
Failed to get properties for blob item.

### ISSUE THREAD

**Issue by johnholliday** [microsoft/AzureStorageExplorer#5225]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.3

### Architecture

i86

### Storage Explorer Build Number

20211020.2

### Platform

Windows

### OS Version

Windows 11

### Bug Description

Storage explorer fails to display properties for any blob item.

### Steps to Reproduce

1. Launch storage explorer
2. Select any blob item and right-click
3. Select 'properties' from the context menu

### Actual Experience

1. Activities pane displays message "Getting properties for '\<id\>'"
2. Times out after about a minute
3. Activities pane displays message "Failed to get properties for '\<id\>'"

### Expected Experience

Popup dialog showing properties for the selected blob item.

**Comment by MRayermannMSFT** [comment]
@johnholliday
- When the activity times out, is there something like a "Details..." or "Error details..." that you can click on? If yes, please click on that and share the error that appears.
- Could you do:
   1. Start Storage Explorer
   2. Reproduce the problem
   3. Help > Open Logs Folder
   4. In the file explorer window that opens, open the newest log folder
   5. Look for a file with "blob" in its name
   5. Share that file here
- Are you able to view properties of the blobs this issue reproduces for via the Azure Portal?
- Are you behind a proxy/is there anything special about the network you are on?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having problems, we suggest opening an Azure support ticket via the portal.
