### ISSUE TITLE
It would be better to remove the action item 'Refresh' for one blob container/file share/queue/table

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5226]
**Storage Explorer Version**: 1.22.0-dev
**Build Number**: 20211130.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**Architecture**: ia32/x64
**How Found**: AD hoc testing
**Regression From**: Not a regression

## Bug Description ##

It would be better to remove the 'Refresh' for the four services because there is no visible change when clicking 'Refresh' against one blob container/file share/queue/table.

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create one blob container -> Right click the blob container.
3. Observe there is a 'Refresh' action item on the context menu.
4. Click the 'Refresh' action -> It doesn't take any difference that can be observed.

## Expected Experience ##
It would be better to remove the 'Refresh' action item.

## Actual Experience ##
The 'Refresh' action item displays on the context menu.
![image](https://user-images.githubusercontent.com/41351993/144012206-177d5726-c785-43c4-be2d-ee79d89a9269.png)

**Comment by craxal** [comment]
By design. Apart from re-listing child nodes, Refresh also refreshes properties. It is possible for the properties of container nodes to change, since more than one person could be maintaining them.
