### ISSUE TITLE
Update icon on macOS to match the new UI language

### ISSUE THREAD

**Issue by dadepretto** [microsoft/AzureStorageExplorer#5233]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I'm always frustrated when I look at the dock of my Mac with macOS Big Sur/Monterey and see the Azure Storage Explorer icon popping out with its irregular design.

### Desired Solution

I'd like to see a new icon for macOS Big Sur/Monterey users that match the rest of the new UI language.

### Additional Context

I know it isn't a priority by any means. Still, other Microsoft tools received the update (Visual Studio Code, Azure Data Studio). And since it has been more than a year since macOS switched to the new icon language, the Azure Storage Explorer icon pops out.

<img width="509" alt="Schermata 2021-12-02 alle 00 18 59" src="https://user-images.githubusercontent.com/42669027/144404221-3517b66d-732b-4339-b263-b33aef35bb01.png">

**Comment by MRayermannMSFT** [comment]
@dadepretto thanks for pointing this out. We'll start talking to our icon team to get this fixed.
