### ISSUE TITLE
Server failed to authenticate the request

### ISSUE THREAD

**Issue by mteraiya** [microsoft/AzureStorageExplorer#5235]
Failed to inspect '', error: {
  "name": "RestError",
  "message": "Server failed to authenticate the request. Please refer to the information in the www-authenticate header.\nRequestId:52fc8ca1-601e-009b-6707-e9b1f2000000\nTime:2021-12-04T12:03:52.7456595Z",
  "stack": "RestError: Server failed to authenticate the request. Please refer to the information in the www-authenticate header.\nRequestId:52fc8ca1-601e-009b-6707-e9b1f2000000\nTime:2021-12-04T12:03:52.7456595Z\n    at handleErrorResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:3140:19)\n    at C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:3076:49\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async StorageRetryPolicy.attemptSendRequest (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-blob-extension\\node_modules\\@azure\\storage-blob\\dist\\index.js:14657:24)\n    at async StorageClientContext.sendOperationRequest (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:4687:31)\n    at async ContainerClient.listBlobFlatSegment (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-blob-extension\\node_modules\\@azure\\storage-blob\\dist\\index.js:22315:30)",
  "code": "InvalidAuthenticationInfo",

**Comment by MRayermannMSFT** [comment]
@mteraiya how have you connected your resource/s to Storage Explorer?
- If you signed in, what type of storage resource(blob, gen2 blob, queue, file share, table) are you accessing and are you relying RBAC, Gen2 ACLs, or do you have permission to list keys?
- If you attached with a key connection string/name and key, can you make sure you spelled the account name right and they key is still correct?
- If you attached with a SAS connection string or URL, can you make sure that your SAS has not expired, or if it is access policy based then that the policy still exists?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having problems, we suggest opening an Azure support ticket via the portal.
