### ISSUE TITLE
Can't open storage accounts

### ISSUE THREAD

**Issue by felipearaujokantar** [microsoft/AzureStorageExplorer#5236]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.3

### Architecture

x64

### Platform

Windows

### OS Version

Windows10

### Bug Description

Error message whenever I am trying to open storage Accounts

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://management.azure.com/subscriptions/136ecfc6-bf51-4274-b9bb-f56d5bd2f99e/resourcegroups?api-version=2021-01-01 failed, reason: write EPROTO 1337133480:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:\n",
  "stack": "FetchError: request to https://management.azure.com/subscriptions/136ecfc6-bf51-4274-b9bb-f56d5bd2f99e/resourcegroups?api-version=2021-01-01 failed, reason: write EPROTO 1337133480:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:\n\n    at ClientRequest.<anonymous> (C:\\Users\\jose.felipe\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1483:11)\n    at ClientRequest.emit (events.js:315:20)\n    at TLSSocket.socketErrorListener (_http_client.js:469:9)\n    at TLSSocket.emit (events.js:315:20)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
  "type": "system",
  "errno": "EPROTO",
  "code": "EPROTO"
}

### Steps to Reproduce

1. Launch Azure Storage Explorer
2. Expand Storage Accounts

### Actual Experience

An error message is being displayed and no storage accounts are listed.

### Expected Experience

Show my 2 storage accounts

**Comment by MRayermannMSFT** [comment]
@felipearaujokantar can you give system proxy a try? Read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview Please let us know if it does not solve this problem. Thanks!

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please give system proxy a try. If you continue having problems after trying to use it, please open a new issue. Thanks.
