### ISSUE TITLE
More Self-Signed Errors

### ISSUE THREAD

**Issue by BKDAmaughan** [microsoft/AzureStorageExplorer#5238]
I've imported my corporate certificate, but I still while navigating around find locations that say it can't connect because of a self-signed cert in chain.  The most recent example was file shares.

**Comment by MRayermannMSFT** [comment]
@BKDAmaughan we recently shipped a new feature called [System Proxy](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview) which should alleviate the need for you to find/import certificates to Storage Explorer. Unfortunately in our latest public release file shares doesn't support it yet. However, in our upcoming release (sometime this week), file shares will be supporting it. I'll let you know when that release drops so you can give it a try. Until then, you can always try the last resort step of disabling SSL cert verification in Storage Explorer: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#disabling-ssl-certificate-validation

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please give system proxy a try. If you continue having problems after trying to use it, please open a new issue. Thanks.

**Comment by BKDAmaughan** [comment]
Sorry I didn't respond.  I'm going to give the system proxy a try.
