### ISSUE TITLE
Add 'Delete Blobs' label on 'Delete' dialog like 'Rename Blobs'

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#524]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180730.1
**Commit**: 17eb92a4
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Open one blob container which contains one blob at least.
2. Right click one blob then select 'Delete' -> Check the 'Delete Blobs' dialog.

#### Expected Experience: ####
It Displays 'Delete Blobs' label on the dialog.

#### Actual Experience: ####
No 'Delete Blobs' label displays on the dialog.
![label](https://user-images.githubusercontent.com/34729022/43454223-e13b99d8-94ab-11e8-9156-55383889fe26.png)

**Comment by craxal** [comment]
I think this is fine for now. But since we want to start using this more generally in the app, let's loop in the UX folks and find out what this should look like in the end.

**Comment by JasonYeMSFT** [comment]
This new dialog is supposed to replace the native message boxes. None of the native message box has a explicit title label in the window.
