### ISSUE TITLE
Copy folders with Storage Account setting "allowSharedKeyAccess": false

### ISSUE THREAD

**Issue by RocketRob97** [microsoft/AzureStorageExplorer#5242]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Copying Folders based on AAD authentication not possible in the storage explorer

### Desired Solution

I would really appreciate if copying blobs/folders would be possible without relying on Keys

### Alternatives and Workarounds

Alternatively we are currently downloading and uploading folders, but this is not a good option for large files

**Comment by MRayermannMSFT** [comment]
@RocketRob97 is this for:
- non-ADLS Gen2 containers
- ADLS Gen2 containers
- file shares
?

**Comment by RocketRob97** [comment]
@MRayermannMSFT Thank you for your reply, it's a ADLS Gen2 container.

**Comment by ralphke** [comment]
@MRayermannMSFT FYI: RocketRob97 is my S500 Enterprise customer. He has disabled the storage account key to the ADLS Gen2 storage account to tighten security. But this breaks Storage Explorer when trying to rely on AAD authentication only!
Is this scenario part of the test metrics?

**Comment by MRayermannMSFT** [comment]
@ralphke , I'm guessing from @RocketRob97 's other issue that Gen2 ACLs are being used to help secure the data in the Storage Account. Unfortunately there are no APIs available that would allow us to do this.

For RBAC based permissions (which only have granularity as low as the container level), it is possible to copy blobs without key access. Basically a user needs to have RBAC roles:
- that let them read the copy source data
- that let them write at the copy destination
- that let them generate a **user delete SAS** for the source data

That 3rd par is the key. When we do a copy, we give the server a SAS token for the source data. So the user needs to be able to generate one. For the longest time you could only generate a SAS with an account key, but recently the concept of a user delegate SAS was added. Right now that only supports RBAC based permissions. So for this scenario, y'all would have to give users RBAC roles that defeat the purpose of the ACLs.

Let us know if you know of any alternative techniques we could use to make this scenario a reality though!

**Comment by ralphke** [comment]
@MRayermannMSFT You are refereeing to [this ](https://docs.microsoft.com/en-us/rest/api/storageservices/create-user-delegation-sas) documentation. So enabling user signed SAS tokens is the way to proceed.
On the other hand the restrictions on RBAC is significant. Is there a way to support also ACLs below the container level?
Thanks for your feedback.

**Comment by MRayermannMSFT** [comment]
> You are refereeing to this documentation.

Yes.

> Is there a way to support also ACLs below the container level?

For service to service copies? No, not that I know of. :( Best you can do right now is download the data locally and then reupload. :(

**Comment by JasonYeMSFT** [comment]
The support to copy data with Azure AD only credentials have been added in our 1.25.0 release.
