### ISSUE TITLE
reason: unable to get local issuer certificate",

### ISSUE THREAD

**Issue by seyal84** [microsoft/AzureStorageExplorer#5249]
Details:
{
  "name": "FetchError",
  "message": "request to https://cmsclaracuststorenatl.blob.core.windows.net/?sv=2020-08-04&ss=bfqt&srt=sco&sp=rlpitfx&se=2022-11-25T23:59:59Z&st=2021-11-25T15:28:43Z&spr=https&SAS Token Redacted&comp=list&include=metadata failed, reason: unable to get local issuer certificate",
  "stack": "FetchError: request to 
ttps://sss.blob.core.windows.net/?sv=2020-08-04&ss=bfqt&srt=sco&sp=rlpitfx&se=2022-11-25T23:59:59Z&st=2021-11-25T15:28:43Z&spr=https&SAS Token Redacted&comp=list&include=metadata failed, reason: unable to get local issuer certificate\n    at ClientRequest.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1483:11)\n    at ClientRequest.emit (events.js:315:20)\n    at TLSSocket.socketErrorListener (_http_client.js:469:9)\n    at TLSSocket.emit (events.js:315:20)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
  "type": "system",
  "errno": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY",
  "code": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"
}

**Comment by MRayermannMSFT** [comment]
@seyal84 can you give system proxy a try? Read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having problems we recommend opening a ticket from the Azure Portal.
