### ISSUE TITLE
The attached service from the second time isn't auto opened

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#525]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180730.1
**Commit**: 17eb92a4
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Create a SAS URL for one blob container
   **Display Name**: test1
   **URI**: https://alphaxuanacc.blob.core.windows.net/test1?st=2018-07-31T10%3A12%3A01Z&se=2018-08-03T10%3A12%3A00Z&sp=rwdl&sv=2018-03-28&sr=c&sig=YIa1iHLv2J5GDNoOqJ1Pm3wpY9FrSBxhxaF0qKKSNco%3D
2. Attach it with the default display name (make sure it is auto opened). Keep the first container editor is opened.
3. Create a SAS URL for another blob container
   **Display Name**: test2
   **URI**: https://alphaxuanacc.blob.core.windows.net/test2?st=2018-07-31T10%3A15%3A15Z&se=2018-08-04T10%3A15%3A00Z&sp=rwdl&sv=2018-03-28&sr=c&sig=RyCOkgN%2BJbt69hRwjQ6JneVanyzLgzj4KLhO9Jv2HP8%3D
4. Attach it with default display name.
5. Check whether the second attached service is suto opened or not.

#### Expected Experience: ####
The second attached blob container is auto opened.

#### Actual Experience: ####
The second attached blob container isn't auto opened.

**Comment by v-xuanzh** [comment]
The second acctached contaienr is auto opened after closing the first attached container editor.
But this issue reproduces when the first attached container is opened. Could you help to take look at it?

**Comment by craxal** [comment]
The issue is new SAS nodes are passing `null`/`undefined` for a node path, which is what we use to associate tabs with nodes. Since a tab for a SAS connection has already been opened (which is associated with a null path), because another new SAS connection also sends a null path, the tab manager things a tab for it is already open, so it doesn't open a new tab.
