### ISSUE TITLE
Unable to retrieve child resources.

### ISSUE THREAD

**Issue by Nicky90210** [microsoft/AzureStorageExplorer#5250]
Unable to retrieve child resources.

Details:
{
  "name": "RestError",
  "message": "This request is not authorized to perform this operation.\nRequestId:028b7c18-d01e-0006-134a-edcd7f000000\nTime:2021-12-09T22:19:55.5246040Z",
  "stack": "RestError: This request is not authorized to perform this operation.\nRequestId:028b7c18-d01e-0006-134a-edcd7f000000\nTime:2021-12-09T22:19:55.5246040Z\n    at handleErrorResponse (/Users/annelisemurillo/Desktop/Microsoft Azure Storage Explorer 4.app/Contents/Resources/app/node_modules/@azure/core-http/dist/index.js:3140:19)\n    at /Users/annelisemurillo/Desktop/Microsoft Azure Storage Explorer 4.app/Contents/Resources/app/node_modules/@azure/core-http/dist/index.js:3076:49\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async StorageRetryPolicy.attemptSendRequest (/Users/annelisemurillo/Desktop/Microsoft Azure Storage Explorer 4.app/Contents/Resources/app/node_modules/se-blob-extension/node_modules/@azure/storage-blob/dist/index.js:14657:24)\n    at async StorageClientContext.sendOperationRequest (/Users/annelisemurillo/Desktop/Microsoft Azure Storage Explorer 4.app/Contents/Resources/app/node_modules/@azure/core-http/dist/index.js:4687:31)\n    at async BlobServiceClient.listContainersSegment (/Users/annelisemurillo/Desktop/Microsoft Azure Storage Explorer 4.app/Contents/Resources/app/node_modules/se-blob-extension/node_modules/@azure/storage-blob/dist/index.js:23490:20)",
  "code": "AuthorizationFailure",
  "statusCode": 403,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://czohsadgcapplestudyp01.blob.core.windows.net/?comp=list&include=metadata",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2020-08-04"
        },
        "accept": {
          "name": "accept",
          "value": "application/xml"
        },
        "user-agent": {
          "name": "user-agent",
          "value": "Microsoft Azure Storage Explorer, 1.21.3, darwin azsdk-js-storageblob/12.7.0 (NODE-VERSION v14.16.0; Darwin 20.6.0)"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "23bf95aa-75fb-4a37-8d9a-43cbcbcf30c1"
        },
        "authorization": {
          "name": "authorization",
          "value": "Bearer JSON Web Token Redacted"
        },
        "cookie": {
          "name": "Cookie",
          "value": ""

**Comment by MRayermannMSFT** [comment]
@Nicky90210 it looks like you've signed into storage explorer are enumerating resources under a subscription. Is that correct? If yes, can you confirm for us what RBAC permissions you have for the storage account czohsadgcapplestudyp01?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having problems, we recommend opening an Azure support ticket via the portal.
