### ISSUE TITLE
Theme reverts to default when installing or updating Visual Studio 2022

### ISSUE THREAD

**Issue by ahawes-clarity** [microsoft/AzureStorageExplorer#5251]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.3

### Architecture

x64

### Storage Explorer Build Number

20211020.2

### Platform

Windows

### OS Version

Windows 10

### Bug Description

When installing or updating Visual Studio 2022 the theme of Azure Storage Explorer gets reset to the default theme.

I have Dark theme set but when I update Visual Studio 2022 the theme gets set back to normal light theme.

### Steps to Reproduce

Install or update Visual Studio 2022 with Azure Storage Explorer installed.

### Actual Experience

Theme changes

### Expected Experience

Theme does not change

**Comment by MRayermannMSFT** [comment]
@ahawes-clarity thanks for reporting this. We'll try to repro this and see what we find.

**Comment by MRayermannMSFT** [comment]
We were able to repro! We'll take a look into this weirdness.....

**Comment by ahawes-clarity** [comment]
Great. Thanks

**Comment by MRayermannMSFT** [comment]
Hi @ahawes-clarity thankfully it looks like we fixed the cause of this (on the Storage Explorer side) in our upcoming 1.22 release. Here's what's going on:

- When you change themes in VS, VS somehow triggers an OS level event for "OS theme changed", even though VS is not changing OS theme settings
- In Storage Explorer 1.22 and older, if a "OS theme changed" event is received, the Storage Explorer theme is changed to match the OS theme as closely as possible

So what happened to you is:
1. You are on Windows, running light theme
2. You have Storage Explorer installed, running a non-light theme
3. You have VS installed
4. You change the VS theme, it does not matter what you change it to
5. VS triggers the  OS level event for "OS theme changed"
6. Storage Explorer receives that event
7. Storage Explorer changes to match the OS light theme

But in Storage Explorer 1.23, we have added being able to explicitly say/not say (opt-in/opt-out) to wanting to match the OS theme by setting the Storage Explorer theme to "system". So after you receive 1.23, assuming you don't change the Storage Explorer theme to "system", steps 7 will not happen.

Make sense?

**Comment by ahawes-clarity** [comment]
Makes sense. Have you notified the VS team that they probably shouldn't be triggering an "OS theme changed" event?
