### ISSUE TITLE
The 'Export' action can't be cancelled by clicking 'Cancel' or 'X' on the prompt window

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5255]
**Storage Explorer Version**: 1.22.0-dev
**Build Number**: 20211209.9
**Branch**: rel/1.22.0
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**Architecture**: ia32/x64
**How Found**: AD hoc testing
**Regression From**:  Previous release (1.21.3)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Click 'Export'.
3. Click 'Cancel' on the prompt window.
4. Check the 'Export' action is cancelled

## Expected Experience ##
The 'Export' action is cancelled.

## Actual Experience ##
1. The 'Export' action is not cancelled
2. There is an exporting activity log.
![image](https://user-images.githubusercontent.com/41351993/145534956-defe1109-0115-4a84-bfc8-da425d09cd7e.png)

**Comment by craxal** [comment]
@v-xianya I am not able to reproduce on sufficiently large tables. How large is the table you are exporting? How long does the export take? It can take a few seconds for the cancel input to trickle down, so if the table is small or nearly done exporting, it's not likely the cancel will happen before things finish.

**Comment by v-xianya** [comment]
Verified on the rel build 20211211.2. Fixed

**Comment by v-xianya** [comment]
This issue reproduces on the latest build main/20211220.7.
