### ISSUE TITLE
The new added CORS rule doesn't display when opening the 'CORS Settings' dialog at the first time

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5257]
**Storage Explorer Version**: 1.22.0-dev
**Build Number**: 20211209.9
**Branch**: rel/1.22.0
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**Architecture**: ia32/x64
**How Found**: AD hoc testing
**Regression From**:  Previous release (1.21.3)

## Bug Descriptions ##
The new added CORS rule doesn't display when opening the 'CORS Settings' dialog at the first time.
The deleted CORS rule doesn't disappear when opening the 'CORS Settings' dialog at the first time.

## Steps to Reproduce ##
1. Expand one storage account.
2. Right click the 'Tables' node -> Click 'Configure CORS Settings...'.
3. Add one CORS rule and save it -> Click 'Save' on the CORS Settings dialog.
4. There is a successful activity log.
5. Right click the 'Tables' node -> Click 'Configure CORS Settings...'.
6. Check whether the added CORS rule displays well.

## Expected Experience ##
The added CORS rule displays well.

## Actual Experience ##
The added CORS rule doesn't display.

## Additional Context ##
The added CORS rule will display after opening the 'CORS Settings' dialog multi times.
![testtable](https://user-images.githubusercontent.com/41351993/145548757-9cfc7963-401e-4a90-b388-86de4c33789e.gif)

**Comment by MRayermannMSFT** [comment]
@craxal I thought CORS wasn't changed for 1.22?

**Comment by craxal** [comment]
@MRayermannMSFT Correct, CORS was not modified.

I don't think this is really a regression. I was able to repro this, but I don't think this is a problem on our end. After a few seconds, I opened the dialog again, and the new CORS rule appeared as expected. I also confirmed the portal showed the new CORS rule. I suspect it's just a delay in the platform. Nothing we need to do.
