### ISSUE TITLE
The activity log and the paste result are inconsistent when pasting one deleted table between storage accounts

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5258]
**Storage Explorer Version:** 1.22.0-dev
**Build Number:** 20211209.9
**Branch:** rel/1.22.0
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**Architecture:** ia32/x64
**How Found:** AD hoc testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create a Table -> Copy the table -> Then delete the table.
3. Paste the table to another storage account.
4. Check whether the activity log and the paste result are consistent.

## Expected Experience ##
The activity log and the paste result are consistent.

## Actual Experience ##

1. Succeed to paste the table.
2. There is a failed activity log.
![image](https://user-images.githubusercontent.com/87792676/145546062-30fcceeb-ae42-454d-bfcb-4a47715de04c.png)

## Additional Context ##

1. In the previous release (1.21.3), succeed to paste the deleted table and there is a successful activity log.
![image](https://user-images.githubusercontent.com/87792676/145547223-749f1aa0-1ba8-4bec-973a-3c43902a1251.png)

2. An error info bar prompts when pasting the deleted table to the original storage account, and the pasted table disappears after manually refreshing.
![image](https://user-images.githubusercontent.com/87792676/145546887-b4113317-254d-4d33-952f-98d08c89920b.png)

**Comment by craxal** [comment]
@v-kellyluo Can you explain what you mean by "succeed to paste the table"? If the activity log displays a failed message, how do you know the paste was successful?

**Comment by craxal** [comment]
After some discussion, unless we're misunderstanding, we believe the error is better than a success, because pasting a table that doesn't exist anymore should not succeed and cause an error.

**Comment by v-kellyluo** [comment]
Hi @craxal ,
The 'succeed to paste the table' means that the pasted table displays under another storage account, and it doesn't disappear after manually refreshing.
Here is the record:
![paste](https://user-images.githubusercontent.com/87792676/145739086-28757b1e-67de-44f2-be56-3e65260783bc.gif)

**Comment by craxal** [comment]
I'll go ahead and reopen to investigate for 1.23.0. I don't think this needs to be addressed for 1.22.0.

**Comment by craxal** [comment]
There's not much we can do to guard against starting a copy against a deleted table. It's entirely possible for some other party to delete the table during a copy, which is not something we can catch. However, we can add support for copying the table's properties, and that can help us detect early whether the table was deleted in addition to the benefit of copying table properties.

**Comment by craxal** [comment]
Since tables don't actually have properties, that's not going to help detect whether the source table has been deleted.

I don't think it's a problem to have a new table node somewhere when a copy fails. Copies can take a long time to complete, and I don't think it makes sense to discard any progress if an error is encountered. The user can delete the incomplete copy if they wish. As long as the activity log correctly reflects the outcome of the operation.
