### ISSUE TITLE
Default download directory

### ISSUE THREAD

**Issue by CurtMiller66** [microsoft/AzureStorageExplorer#5259]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Set a default directory for downloads different than the default directory for the browser

### Desired Solution

It would be great if you could set the default directory in settings.

### Additional Context

Every time I start explorer and download files, I have to change to a specific directory.  I would like to set that directory as the default.

**Comment by richardMSFT** [comment]
Default download directory setting has been implemented and should be shipped in 1.27.0.
