### ISSUE TITLE
Unix codes to upload and download data to/from Azure storage account using Azure Storage explorer

### ISSUE THREAD

**Issue by indranilroyc** [Microsoft/AzureStorageExplorer#526]
**Storage Explorer Version**: Latest
**Platform/OS Version**: RHEL 7.2

I have a requirement to upload and download data in our RHEL server without doing an SSH. For that I want to utilize storage explorer securely to download data into the VM from Azure File Share. I am looking for possible linux/CLI code to download the same from my Azure storage account.

Can you please share the cmdlet to download data from Azure File share using Linux script.

**Comment by craxal** [comment]
You seem to be asking for three different things: Storage Explorer, a cmdlet (PowerShell), and a Linux script (POSIX).

Storage Explorer is a GUI application, not a command line tool. You can certainly download files with it, but it's not well suited for high-intensity download jobs from file shares at the moment.

I don't think you're looking for a PowerShell cmdlet, so you probably want [AzCopy for Linux](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-linux).
