### ISSUE TITLE
Auth issue: The size of the request headers is too long.

### ISSUE THREAD

**Issue by Kizmar** [microsoft/AzureStorageExplorer#5260]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.3

### Architecture

x64

### Storage Explorer Build Number

202111020.2

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Trying to add a Microsoft account to access subscriptions, and when it opens the browser window for me to log in, I get the following error after logging in:

> Bad Request - Request Too Long
> HTTP Error 400. The size of the request headers is too long.

### Steps to Reproduce

1. Launch storage explorer
2. Click "Add an account"
3. Click "Subscription"
4. With "Azure" selected, click "Next"
5. It opens a browser tab, click on account to log in with (or enter email)
6. Log in
7. See error page
8. Storage explorer keeps spinning and never logs in

### Actual Experience

See steps to reproduce

### Expected Experience

After I log it in should go back to storage explorer and set up the subscriptions I just logged in for

**Comment by MRayermannMSFT** [comment]
@Kizmar it sounds like this is problem something to do with needing to clear cookies/data in your browser:

- https://stackoverflow.com/questions/6538926/chrome-returns-bad-request-request-too-long-when-navigating-to-local-iis-exp
- https://stackoverflow.com/questions/14778910/bad-request-request-too-long-http-error-400-the-size-of-the-request-headers-i
- https://techisours.com/fix-bad-request-request-too-long/

Can you try some of the steps suggested on those pages?

**Comment by Kizmar** [comment]
@MRayermannMSFT Well that's embarrassing. Yep, that fixed it. All I had to do was the ol' "clear your cache". Thank you. ;)
