### ISSUE TITLE
Unable to retrieve sub-resource

### ISSUE THREAD

**Issue by Joson-Z** [microsoft/AzureStorageExplorer#5261]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.3

### Architecture

x64

### Platform

Windows

### OS Version

win10

### Bug Description

无法检索子资源。

详细信息:
{
  "name": "RestError",
  "message": "{\"info\":\"Invalid request!\"}",
  "stack": "RestError: {\"info\":\"Invalid request!\"}\n    at handleErrorResponse (D:\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:3140:19)\n    at D:\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:3076:49\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async StorageRetryPolicy.attemptSendRequest (D:\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-blob-extension\\node_modules\\@azure\\storage-blob\\dist\\index.js:14657:24)\n    at async BlobApiVersionRequestPolicy.sendRequest (D:\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-blob-extension\\dist\\src\\Clients\\BlobStorageClient.js:24:16)\n    at async StorageClientContext.sendOperationRequest (D:\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:4687:31)\n    at async BlobServiceClient.listContainersSegment (D:\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-blob-extension\\node_modules\\@azure\\storage-blob\\dist\\index.js:23490:20)",
  "statusCode": 400,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "http://127.0.0.1:10000/devstoreaccount1?comp=list&include=metadata",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2019-07-07"
        },
        

### Steps to Reproduce

open AzureStorageExplorer
check Emulator-default port-->blob

### Actual Experience

It was good after installation yesterday, but I had a problem opening it again today.
I'm a novice,Not sure what happened

**Comment by Joson-Z** [comment]
I use a local emulator here

**Comment by MRayermannMSFT** [comment]
@Joson-Z what emulator and what version of it, are you using?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having problems we recommend opening a support ticket via the Azure Portal.
