### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by EdgarTTRRL** [microsoft/AzureStorageExplorer#5263]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.3

### Architecture

x64

### Storage Explorer Build Number

20211020.2

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Unable to retrieve child resources.

### Steps to Reproduce

1. launch Storage Explorer
2. Open blob container
3. behind a proxy 
4. netskope

### Actual Experience

Sorry unable to upload for security reasons

### Expected Experience

Be able to see storage accounts and blob containers.

### Additional Context

N/a

**Comment by MRayermannMSFT** [comment]
@EdgarTTRRL can you give system proxy a try? Read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having problems we recommend opening a support ticket via the Azure Portal.
