### ISSUE TITLE
Fail to clone one emulator folder which contains non-empty folders

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5266]
**Storage Explorer Version:** 1.23.0-dev
**Build Number:** 20211215.2
**Branch:** main
**Platform/OS:** Windows 10
**Architecture:** ia32
**Emulator Version:** Azurite 3.14.3
**How Found:** Ad-hoc testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Install and run Azurite 3.14.3 -> Launch Storage Explorer. 
2. Expand 'Local & Attached -> Storage Accounts -> (Emulator - Default Ports)(Key)' -> Blob Containers.
3. Create a blob container -> Create a new folder A.
4. Upload folder B which contains one blob to folder A.
5. Right click folder A -> Click 'Clone...'.
6. Type a valid name -> Click 'Clone'.
7. Check whether succeeds to clone the folder.

## Expected Experience ##
Succeed to clone the folder.

## Actual Experience ##
Fail to clone the folder.
![image](https://user-images.githubusercontent.com/87792676/146149277-6d17a800-b734-405c-931f-04cf9ede33d5.png)

**Comment by MRayermannMSFT** [comment]
Let's at least make sure we understand root cause.

**Comment by JasonYeMSFT** [comment]
When listing for clone, we incorrectly send "" as the delimiter to Azurite. The public blob service ignores that parameter but Azurite takes it and return blobs in hierarchy instead of in flat. Our old js copy code thus try to copy a directory which doesn't exist as a blob.
