### ISSUE TITLE
The theme setting on 'Settings' panel is not auto updated after changing theme setting from 'Edit -> Theme' if it is not in 'Application' interface

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5267]
**Storage Explorer Version:** 1.23.0-dev
**Build Number:** 20211215.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**Architecture:** ia32
**How Found:** Ad-hoc testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Launch Storage Explorer.
2. Click 'Settings -> Data Explorers'.
3. Click 'View -> Theme -> Dark'.
4. Click 'Application' on the 'Settings' panel.
5. Check whether the theme setting is auto updated.

## Expected Experience ##
The theme setting is auto updated.

## Actual Experience ##
The theme setting is not auto updated.
![theme](https://user-images.githubusercontent.com/87792676/146155243-930accbe-aabf-4af4-bb5c-07257680bf2c.gif)

**Comment by craxal** [comment]
@v-kellyluo I don't think this is specific to the theme setting. None of the settings in the Settings panel update if the settings are updated elsewhere (UI or editing the settings file). Please verify with another setting. We should consider adding handlers to update the Settings panel when settings change.

**Comment by v-kellyluo** [comment]
Hi @craxal ,Yes, it is right. I tested the following settings change, the settings on 'Settings' panel are not auto updated after changing settings from UI or settings file if it is not in corresponding setting interface.
1. Enable ADLS Gen2 soft delete
2. Preserve blob access tier
3. Show metrics tables
4. Enable ADLS Gen2 snapshots
5. Toolbar size

For proxy settings, there is a related bug [4435](https://github.com/microsoft/AzureStorageExplorer/issues/4435).

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20221028.2. Fixed.
