### ISSUE TITLE
There is an extra scrollbar in the localized 'Clone and Rehydrate' dialog

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5269]
**Storage Explorer Version:** 1.23.0-dev
**Build Number:** 20211215.5
**Branch:** main
**Platform/OS:** Windows 10
**Architecture:** ia32\x64
**Language:** Swedish/Portuguese/Dutch/Italian/Hungarian/Czech
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Svenska' -> Restart Storage Explorer.
3. Expand one storage account -> Blob Containers.
4. Create a blob container -> Upload one blob -> Change its access tier to 'Archive'.
5. Right click the blob -> Click 'Clone and Rehydrate...'.
6. Check there is no extra scrollbar in the 'Clone and Rehydrate' dialog.

## Expected Experience ##
There is no extra scrollbar.

## Actual Experience ##
There is an extra scrollbar.
![image](https://user-images.githubusercontent.com/87792676/146335567-0149ed8f-4adb-471a-8b69-0fa6a01303e6.png)

## Additional Context ##
This issue doesn't reproduce on Linux & Mac.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220808.1. Fixed. So, we are going to close it.
