### ISSUE TITLE
Unable to retrieve child resources. Local & Attached - Storage Accounts - Blob Containers

### ISSUE THREAD

**Issue by darrenb1** [microsoft/AzureStorageExplorer#5270]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.22.0

### Regression From

1.22.0

### Architecture

x64

### Storage Explorer Build Number

20211211.10

### Platform

Windows

### OS Version

Windows 10

### Bug Description

I am unable to view/create local & Attached blob containers. I receive an error stating unable to retrieve child resources.

### Steps to Reproduce

1. Expand Local & Attached
2. Expand Storage Accounts
3. Expand (Emulator - Default Ports)
4. Expand Blob Containers

### Actual Experience

![image](https://user-images.githubusercontent.com/96229138/146342423-46abe59b-30ee-416d-a381-ee833494d080.png)

Blob containers tries to load for around 10 seconds then shows the error details.

### Expected Experience

1. Expand Local & Attached
2. Expand Storage Accounts
3. Expand (Emulator - Default Ports)
4. Expand Blob Containers

Blob containers are displayed correctly.

### Additional Context

[ErrorDetails.txt](https://github.com/microsoft/AzureStorageExplorer/files/7725859/ErrorDetails.txt)

**Comment by MRayermannMSFT** [comment]
@darrenb1 what emulator are you using?

**Comment by darrenb1** [comment]
@MRayermannMSFT I am using Microsoft Azure Storage Emulator v5.10. I have managed to resolve the issue by adding a new rule in the firewall for ports 10000-10002. Storage explorer and the emulator were both working fine until I installed SQL Server 2019 and removed SQL Server 2017. Not sure what caused this to happen but it has now been resolved. Thanks for replying and sorry for wasting your time.
