### ISSUE TITLE
It would be better to remove 'Show in Folder' next to a cancelled download activity log

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5271]
**Storage Explorer Version**: 1.23.0-dev
**Build Number**: 20211215.5
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**Architecture**: ia32/x64
**How Found**: AD hoc testing
**Regression From**:  Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a new blob container -> Upload one large blob.
3. Download the blob to a place where no same blob exists -> Click 'Cancel' next to the download activity log.
4. Check there is no string 'Show in Folder' next to the activity log.

## Expected Experience ##
It would be better to remove 'Show in Folder' next to the activity log.

## Actual Experience ##
There is the string 'Show in Folder' next to the activity log.
![image](https://user-images.githubusercontent.com/41351993/146347002-8891fd03-9503-4eb0-9a0e-7e9d72b3b24e.png)

## Additional Context ##
1. Nothing happens when clicking 'Show in Folder'.
2. This issue doesn't reproduce when cancelling the activity that downloading several items at one time.
3. This issue also reproduces for file shares.

**Comment by MRayermannMSFT** [comment]
We're just going to leave this for now. Too many things to do. 😵
