### ISSUE TITLE
The blob displays after manually refreshing when its uploading activity is cancelled successfully

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5274]
**Storage Explorer Version**: 1.23.0-dev
**Build Number**: 20211217.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**Architecture**: ia32/x64
**How Found**: AD hoc testing
**Regression From**:  Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Click 'Cancel' next to the uploading activity log.
4. Refresh the blob explorer after cancelling successfully.
5. Check the blob doesn't display in the blob explorer.

## Expected Experience ##
The blob doesn't display in the blob explorer.

## Actual Experience ##
The blob displays in the blob explorer.
![aupload](https://user-images.githubusercontent.com/41351993/146524231-8fdb7876-1c07-4309-b66f-e32184392599.gif)

## Additional Context ##
1. The blob displays in the blob explorer after manually refreshing even though the uploading activity is still in progress.
2. This issue also reproduces for file shares.

**Comment by JasonYeMSFT** [comment]
This is by design. AzCopy creates the destination blob before writing its contents. We don't give AzCopy delete credentials to prevent accidental deletion of user data. If a blob has been created and AzCopy gets canceled. The user will have to delete it by himself.
