### ISSUE TITLE
Remove mention of properties and metadata in Clone Tables dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5277]
**Storage Explorer Version**: 1.23.0-dev
**Build Number**: 20211220.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**Architecture**: ia32/x64
**How Found**: AD hoc testing
**Regression From**:  Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a new table -> Right click the table.
3. Click 'Clone...' -> Observe the description in the 'Clone Table' dialog.
4. Check whether no unnecessary description displays in the dialog.

## Expected Experience ##
No unnecessary description displays in the dialog.

## Actual Experience ##
The unnecessary description 'Properties and metadata will not be preserved.' displays in the dialog.
![image](https://user-images.githubusercontent.com/41351993/146734250-d9d99d42-0d99-4511-a794-948a120e8a74.png)

**Comment by MRayermannMSFT** [comment]
@v-xianya why do you think that message is unnecessary?

**Comment by v-xianya** [comment]
@MRayermannMSFT 
Because there is no such message in Clone blob container/File Share dialog.(As the below)
![image](https://user-images.githubusercontent.com/41351993/148000921-8b77e4c3-4c45-486e-8e1b-8cfceae40b3e.png)
![image](https://user-images.githubusercontent.com/41351993/148000947-9a77770f-f7a0-4ac4-8d52-2dde07d73cac.png)

**Comment by craxal** [comment]
@v-xianya It's not there for blobs and files because cloning those resources actually copies the properties and metadata. Cloning tables currently _does not_ copy properties and metadata. Until it does, we need the message to remain, so users know we're not missing something accidentally.

**Comment by craxal** [comment]
@v-xianya On closer inspection, I realized the reason we didn't copy properties is because tables don't _have_ properties. So it looks like removing the extra part of the message is OK after all.

**Comment by v-xianya** [comment]
Reproduce on the latest build main/20220105.2.

**Comment by craxal** [comment]
@v-xianya Package containing the fix has not been updated yet. We are still verifying.

**Comment by v-xianya** [comment]
Verified this issue on the build 20220107.2. Fixed.
![image](https://user-images.githubusercontent.com/41351993/148480198-1eccf435-0243-49c9-b838-5ecaaf6e5271.png)
