### ISSUE TITLE
Copy Jobs are always queueing

### ISSUE THREAD

**Issue by chichms** [microsoft/AzureStorageExplorer#528]
**Storage Explorer Version**: 1.3.1
**Architecture**: ia32
**Regression From**: 

#### Steps to Reproduce: ####
1. I tried to copy tens of files from the source folder to the destination folder. The first few files are successfully copied but then all jobs are queued for ever.

**Comment by craxal** [comment]
What is the source location of files? Where are you copying them to? Are you working with the local file system, blob containers, or file shares?

**Comment by AquickCCBCC** [comment]
I'm having the same issue. Anytime I try to copy files from one directory to another within the same Storage Account, they queue forever.

**Comment by MRayermannMSFT** [comment]
@chichms @AquickCCBCC are either of you still having problems with the latest version of Storage Explorer?

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response.
