### ISSUE TITLE
There is no error dialog when importing a CSV file with no entities

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5283]
**Storage Explorer Version**: 1.23.0-dev
**Build Number**: 20211220.7
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**Architecture**: ia32/x64
**How Found**: AD hoc testing
**Regression From**:  Previous release (1.21.3)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a new table (do not add any entities) -> Click 'Export'.
3. Then click 'Import' -> Select the .CSV file which is exported in step 2.
4. Check there is an error dialog.

## Expected Experience ##
There is an error dialog.
![image](https://user-images.githubusercontent.com/41351993/147054553-ece2dcfc-8fea-4713-8758-508a9d93a973.png)

## Actual Experience ##
There is no error dialog.

**Comment by craxal** [comment]
Looks like the code just returns without displaying an error message like it did before, so we just need to put it back in.

**Comment by v-xianya** [comment]
Verified this issue on the build 20220107.2. Fixed.
![image](https://user-images.githubusercontent.com/41351993/148480198-1eccf435-0243-49c9-b838-5ecaaf6e5271.png)
