### ISSUE TITLE
Succeed to delete blobs in one secondary ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5284]
**Storage Explorer Version:** 1.23.0-dev
**Build Number:** 20211220.7
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**Architecture:** ia32/x64
**How Found:** AD hoc testing
**Regression From:** Not a regression

## Bug Description ##
In one ADLS Gen2 secondary blob container:

- Succeed to delete blobs.
- Succeed to create folders.
- Succeed to rename blobs.
- Succeed to move blobs.

## Steps to Reproduce ##

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload a blob.
3. Right click the blob container -> Click 'Open Secondary Location'.
4. Try to delete the blob in the secondary blob explorer.
5. Check whether fails to delete the blob.

## Expected Experience ##
Fail to delete the blob.

## Actual Experience ##
Succeed to delete the blob.
![image](https://user-images.githubusercontent.com/87792676/147070603-da7bd3f7-fea4-4004-be8e-0c43717e80cc.png)

**Comment by MRayermannMSFT** [comment]
If we are using the wrong endpoint, then this should be hotfixed.

**Comment by JasonYeMSFT** [comment]
We are using the correct secondary dfs endpoint. The operation done via the secondary dfs endpoint doesn't affect blobs in the primary endpoint. It seems to be an uncaught scenario by the storage service team.

**Comment by JasonYeMSFT** [comment]
The service team seems to have fixed this problem. Delete, Rename, Move on blobs/directories from a secondary endpoint now results in a "write operations are not permitted error".

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220214.5. Fixed.
