### ISSUE TITLE
There is a successful activity log when uploading more than one file that have been deleted in the source location

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5286]
**Storage Explorer Version**: 1.23.0-dev
**Build Number**: 20211220.7
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.6.1
**Architecture**: ia32/x64
**How Found**: AD hoc testing
**Regression From**:  Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Click 'Upload -> Upload Files...'.
3. Select two files from a native location.
4. Go to the native location -> Delete the two files.
5. Go to Storage Explorer -> Click 'Upload' on the 'Upload Files' dialog.
6. Check whether there is a failed activity log.

## Expected Experience ##
There is a failed activity log.

Here is the screenshot when trying to upload one file which has been deleted in the source location:
![image](https://user-images.githubusercontent.com/41351993/147212333-d4bc2322-6d73-4e08-9a5b-57b9aa73db01.png)

## Actual Experience ##
There is a successfully activity log indicating 0 items transferred.
![image](https://user-images.githubusercontent.com/41351993/147212237-34bb2689-31c6-4579-8aab-2a5c80b6d941.png)

## Additional Context ##
This issue also reproduces for file shares/ADLS Gen2 blobs.

**Comment by MRayermannMSFT** [comment]
Won't fix for now. AzCopy does not consider this to be a failure scenario.
