### ISSUE TITLE
The 'OK' button is still enabled in the 'Proxy Settings' dialog when inputting an invalid string in the 'URL' field

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5288]
**Storage Explorer Version**: 1.23.0-dev
**Build Number**: 20211220.7
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.6.1
**Architecture**: ia32/x64
**How Found**: AD hoc testing
**Regression From**: Previous release (1.20.1)

## Steps to Reproduce ##
1. Open Storage Explorer -> Click 'Edit -> Configure Proxy'.
2. Switch the source to 'Use app proxy settings' -> Delete the string in the 'URL' or 'Port' field.
3. There is an error message in the 'Proxy Settings' dialog.
4. Check whether the 'OK' button is disabled.

## Expected Experience ##
The 'OK' button is disabled.

## Actual Experience ##
The 'OK' button is enabled.
![image](https://user-images.githubusercontent.com/41351993/147337708-70780e26-65bd-426e-b085-028c1a88e1d9.png)

**Comment by craxal** [comment]
@v-xianya I only observe the OK button is enable for invalid URLs. It still disables for bad port numbers, as expected.

**Comment by v-xianya** [comment]
@craxal Thank you for pointing it out. I get it wrong😵. The OK button is disabled for bad port numbers. I will update the issue title.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220216.1. Fixed.
