### ISSUE TITLE
Recommendation: Make job's states selectively wait

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#529]
Current behavior:
In our current state machine pattern, in order not to make the state machine stuck when running in process. We need to let them yield after each update() call.

Meanwhile, it is beneficial for some states to wait since they may stay in one state for a long time, such as upload/download.

We should make each state determine whether they want to wait and how long should they wait to avoid unnecessary waiting and allow every state machine to run in process.

**Comment by MRayermannMSFT** [comment]
@JasonYeMSFT doesn't remember why he opened this. Closing! 🙃
