### ISSUE TITLE
The localized string and the search icon overlap in the Prefix filed for one blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5290]
**Storage Explorer Version**: 1.23.0-dev
**Build Number**: 20211220.7
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 18.04/MacOS Big Sur 11.6.1
**Language**: Japanese/Czech 
**Architecture** ia32\x64
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '日本語' -> Restart Storage Explorer.
3. Expand one non-ADLS Gen2 storage account -> Blob Containers.
4. Open one blob container -> Open the 'View Options' panel.
5. Observe the 'Prefix' field -> Check the string and the search icon do not overlap.

## Expected Experience ##
The string and the search icon do not overlap.

## Actual Experience ##
The string and the search icon overlap.
![image](https://user-images.githubusercontent.com/41351993/147455957-780862b8-e8e4-4efe-8ca4-074065eec3db.png)

## Additional Context ##
This issue reproduces on Japanese/Czech (Verify this issue on all languages).

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20210411.1. The search icon is located to the left of the Prefix field. So, we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/8e1d0765-2ddd-4079-a6d5-2a614d39093b)
