### ISSUE TITLE
There is an extra scroll bar in the localized delete blob containers dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5291]
**Storage Explorer Version**: 1.23.0-dev
**Build Number**: 20211220.7
**Branch**: main
**Platform/OS**: Windows 10
**Language**: Japanese
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '日本語' -> Restart Storage Explorer.
3. Expand one storage account -> Blob Containers.
4. Right click one blob container -> Click 'Delete'.
5. Check there is no extra scroll bar in the popped up dialog.

## Expected Experience ##
There is no extra scroll bar in the popped up dialog.

## Actual Experience ##
There is an extra scroll bar in the popped up dialog.
![image](https://user-images.githubusercontent.com/41351993/147457464-34f6283e-6731-447d-bb3a-5cc607b78b25.png)

## Additional Context ##
1. This issue also reproduces when deleting one blob(soft delete is disabled)/file share/queue/table.
2. This issue doesn't reproduce on Mac & Linux.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20210411.1. Fixed. So, we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/3cfa567e-d03b-4e4d-a67d-b29ee93843b9)
