### ISSUE TITLE
Unable to expand the blog container node in Storage account explorer

### ISSUE THREAD

**Issue by ssrinivasa1** [microsoft/AzureStorageExplorer#5295]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.22.0

### Regression From

1.19.0

### Architecture

x64

### Storage Explorer Build Number

20211211.10

### Platform

Windows

### OS Version

Windows 10

### Bug Description

i am unable to expand the blog container node using storage account explorer. facing error of "unable to retrieve child resource"

Attaching the issue.
[Storage Acc issue.txt](https://github.com/microsoft/AzureStorageExplorer/files/7780018/Storage.Acc.issue.txt)

### Steps to Reproduce

1. Launch the Storage Account Explorer.
2. Connected the Storage account using SAS key
3. Trying to expand the blog container node inside the storage account, but facing the error

### Actual Experience

Able to see the containers.

**Comment by JasonYeMSFT** [comment]
@ssrinivasa1 The error trace indicates that you are authenticating using AzureAD credentials, not SAS/Key. That would require you to have the correct rbac role to access the resource (something like "Storage Blob Contributor" or similar). Are you accessing the resources under the storage account node in your subscription or under a storage account node in local attachment?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having problems we recommend opening a ticket from the Azure Portal.
