### ISSUE TITLE
The action 'Copy' is enabled for one archived blob which is queried by tags

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5296]
**Storage Explorer Version**: 1.23.0-dev
**Build Number**: 20211220.7
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.6.1
**Architecture**: ia32/x64
**How Found**: AD hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one non-ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one blob with the default access tier.
3. Right click the blob -> Click 'Change Access Tier..' -> Select 'Archive' -> Click 'Apply'.
4. Right click the archived blob -> Click 'Edit Tags...' -> Add one tag and save it.
5. Observe the 'Copy' action is disabled for the archived blob.
5. Open the view options panel -> Select 'Tag Query' -> Apply the tag of the archived blob to query.
6. The archived blob displays in the editor.
7. Check whether the action 'Copy' is disabled.

## Expected Experience ##
The action 'Copy' is disabled.

The screenshot of one archived blob's toolbar:
![image](https://user-images.githubusercontent.com/41351993/147535387-53dd290e-a725-45f8-aace-9bc2cd5e82c5.png)

## Actual Experience ##
The action 'Copy' is enabled.
![image](https://user-images.githubusercontent.com/41351993/147535218-b50c4ed4-5e83-43c0-aee8-cdf6cee2cf1f.png)

**Comment by JasonYeMSFT** [comment]
When filtering by tags, the access tier information is not available so we enable it for all blobs so that it can still work for non-archived blobs.
