### ISSUE TITLE
Fail to add an entity that contains a boolean/int32 property in one emulator table

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5299]
**Storage Explorer Version:** 1.23.0-dev
**Build Number:** 20211220.7
**Branch:** main
**Platform/OS:** Windows 10
**Architecture:** ia32
**How Found:** AD hoc testing
**Emulator Version:** Azurite 3.14.3
**Regression From:** Previous release (1.21.3)

## Steps to Reproduce ##

1. Install and start Azurite 3.14.3.
2. Launch Storage Explorer -> Expand 'Local & Attached -> Storage Accounts -> (Emulator - Default Ports)(Key)'.
3. Right click the 'Tables' node -> Create a table.
4. Click 'Add' -> Add one boolean property -> Click 'Insert'.
5. Check whether succeeds to add the entity.

## Expected Experience ##
Succeed to add the entity.

## Actual Experience ##
Fail to add the entity.
![image](https://user-images.githubusercontent.com/87792676/147636481-1717f906-ca53-45be-83d2-91379a992e2e.png)

**Comment by craxal** [comment]
This appears to be an error with the emulator, as this is a valid scenario with Azure. See Azure/Azurite#1259.

**Comment by v-kellyluo** [comment]
This issue doesn't reproduce after installing Azurite 3.16.0. So close it.
