### ISSUE TITLE
The background of the selected items don't theme under HC-modes

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#53]
**Storage Explorer Version:** master/20180419.2

**OS Version:** Windows 10/Mac/Linux

**Regression:** Works well on 1.0.0 release

**Steps to Reproduce:** 

1. Launch Storage Explorer and expand Storage Accounts. 
2. Change the theme to HC-Black/White.
3. Open one container and check the background of the selected items.

**Expected Experience:**
The background of the selected items is themed.

**Actual Experience:**
The background of the selected items isn't themed.
![themed](https://user-images.githubusercontent.com/34729022/39040575-ffbe51b4-4476-11e8-95cb-7b4c8a931ce8.png)

**Comment by craxal** [comment]
Unable to reproduce on current master. Please check again and reopen the issue if it reproduces for you.
