### ISSUE TITLE
It would be better to adjust the size of the Acquire/Break Lease dialog for blob containers to remove the scroll bar

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5300]
**Storage Explorer Version**: 1.23.0-dev
**Build Number**: 20211220.7
**Branch**: main
**Platform/OS**: Windows 10/MacOS Big Sur 11.6.1
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob containers.
2. Create a blob container with a name that contains 63 characters.
3. Right click the blob container -> Click 'Acquire Lease'.
4. Observe the popped up dialog.

## Expected Experience ##
It would be better to adjust the size of the dialog according to the content.

## Actual Experience ##
The size of the dialog does not adjust to the content.
![image](https://user-images.githubusercontent.com/41351993/147647353-98e17e72-9307-48b4-9ba1-d38a23e8c75b.png)

## Additional Context ##
1. When deleting one blob container/file share/queue/table whose name contains 63 characters, the scroll bar displays in the deleted blob container dialog. **This only reproduces on Windows.**(Related issue: [3741](https://github.com/microsoft/AzureStorageExplorer/issues/3741))
![image](https://user-images.githubusercontent.com/41351993/147648253-e8bbd50e-5636-4b76-bc78-8f76c9cfa94b.png)
2. This issue doesn't reproduce on Linux Ubuntu 18.04.

**Comment by MRayermannMSFT** [comment]
Also double check the vertical alignment of the icon.

**Comment by MRayermannMSFT** [comment]
Icon is appropriately centered. As for increasing the dialog size, we're going to won't fix for now. We need a more comprehensive approach to resizing small dialogs that show very general content.
