### ISSUE TITLE
Microsoft Azure Storage Explorer

### ISSUE THREAD

**Issue by bigojessie** [microsoft/AzureStorageExplorer#5301]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.22.0

### Architecture

x64

### Platform

Windows

### Bug Description

When I load the software, a message pops up (see attached)

### Steps to Reproduce

1 - Launch Microsoft Azure Storage Explorer
2 - Click on Blob Containers
3 - After few seconds will pop up an error message

![image](https://user-images.githubusercontent.com/64664257/147676159-28e38556-cbef-486a-9f3d-40d4fc9ed16e.png)

### Actual Experience

![image](https://user-images.githubusercontent.com/64664257/147676175-55c8840d-bb33-45cd-b42b-4b086a6ea9a2.png)

**Comment by JasonYeMSFT** [comment]
@bigojessie Is this error message the same as the one you shared in https://github.com/microsoft/AzureStorageExplorer/issues/5302? If yes, let's close this one and keep the conversation there since it has more detailed information.
