### ISSUE TITLE
Error Microsoft Azure Storage Explorer

### ISSUE THREAD

**Issue by bigojessie** [microsoft/AzureStorageExplorer#5302]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.22.0

### Architecture

x64

### Storage Explorer Build Number

2021 1211.10

### Platform

Windows

### OS Version

Windows 10

### Bug Description

The bug is reported in the attached txt file, called issue.txt

[issue.txt](https://github.com/microsoft/AzureStorageExplorer/files/7789646/issue.txt)

### Steps to Reproduce

1. Launch Explorer

### Actual Experience

The Error appears as soon as the software is launched

**Comment by JasonYeMSFT** [comment]
According to the error message, a storage account at "http://127.0.0.1:10000/storage_account_1" is added to the resource tree and it encounters this error when trying to list its resources. Is this endpoint the correct endpoint to your resource? 

If yes, in most cases the endpoint reflects that it is to a customized local emulator. You will need to start your local emulator with the correct parameters to make it work (e.g. override storage account name from "devstoreaccount1" to "storage_account_1").

If the node was created by accident, could you go to your resource tree and check if under Quick Access or Local & Attached there is any storage account node that matches this endpoint. I believe the error will be gone once you detach that node.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having problems we recommend opening a support ticket via the Azure Portal.
