### ISSUE TITLE
Error when expand blob containers

### ISSUE THREAD

**Issue by luisrdzruiz** [microsoft/AzureStorageExplorer#5303]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.22.0

### Architecture

x64

### Storage Explorer Build Number

20211211.10

### Platform

Linux

### OS Version

Fedora 35

### Bug Description

When I expand the blob containers throw error.

Unable to retrieve child resources.

Details:
{
  "name": "TypeError",
  "message": "api.trace.setSpan is not a function",
  "stack": "TypeError: api.trace.setSpan is not a function\n    at setSpan (/opt/StorageExplorer/resources/app/node_modules/@azure/core-tracing/dist/index.js:49:22)\n    at /opt/StorageExplorer/resources/app/node_modules/@azure/core-tracing/dist/index.js:152:131\n    at BlobServiceClient.listContainersSegment (/opt/StorageExplorer/resources/app/node_modules/se-blob-extension/node_modules/@azure/storage-blob/dist/index.js:23488:42)\n    at BlobServiceClient.listSegments_1 (/opt/StorageExplorer/resources/app/node_modules/se-blob-extension/node_modules/@azure/storage-blob/dist/index.js:23724:78)\n    at listSegments_1.next (<anonymous>)\n    at resume (/opt/StorageExplorer/resources/app/node_modules/tslib/tslib.js:225:48)\n    at /opt/StorageExplorer/resources/app/node_modules/tslib/tslib.js:224:125\n    at new Promise (<anonymous>)\n    at Object.i.<computed> [as next] (/opt/StorageExplorer/resources/app/node_modules/tslib/tslib.js:224:67)\n    at /opt/StorageExplorer/resources/app/node_modules/se-blob-extension/dist/src/Clients/BlobServiceClient.js:52:39"
}

### Steps to Reproduce

1. Launch Storage Explorer
2. Expand Blob Containers

### Actual Experience

![image](https://user-images.githubusercontent.com/43277999/147695729-90c5701f-61da-42ae-8ee0-2310ef1c62ee.png)

### Expected Experience

When I expand Blob Containers, I want to see containers

### Additional Context

Unable to retrieve child resources.

Details:
{
  "name": "TypeError",
  "message": "api.trace.setSpan is not a function",
  "stack": "TypeError: api.trace.setSpan is not a function\n    at setSpan (/opt/StorageExplorer/resources/app/node_modules/@azure/core-tracing/dist/index.js:49:22)\n    at /opt/StorageExplorer/resources/app/node_modules/@azure/core-tracing/dist/index.js:152:131\n    at BlobServiceClient.listContainersSegment (/opt/StorageExplorer/resources/app/node_modules/se-blob-extension/node_modules/@azure/storage-blob/dist/index.js:23488:42)\n    at BlobServiceClient.listSegments_1 (/opt/StorageExplorer/resources/app/node_modules/se-blob-extension/node_modules/@azure/storage-blob/dist/index.js:23724:78)\n    at listSegments_1.next (<anonymous>)\n    at resume (/opt/StorageExplorer/resources/app/node_modules/tslib/tslib.js:225:48)\n    at /opt/StorageExplorer/resources/app/node_modules/tslib/tslib.js:224:125\n    at new Promise (<anonymous>)\n    at Object.i.<computed> [as next] (/opt/StorageExplorer/resources/app/node_modules/tslib/tslib.js:224:67)\n    at /opt/StorageExplorer/resources/app/node_modules/se-blob-extension/dist/src/Clients/BlobServiceClient.js:52:39"
}

**Comment by JasonYeMSFT** [comment]
This is an error from one of our indirect dependencies and we need more information to figure out what goes wrong. Could you try to reproduce the issue, then use App Menu -> Help -> Go to logs directory and get us the log files for that repro case (the folder with matching creation time)?

By the way, are you running directly from a .tar.gz or from a installed snap?

**Comment by luisrdzruiz** [comment]
Hi Jason,

Here the logs.
[2021-12-31_112239_main.log](https://github.com/microsoft/AzureStorageExplorer/files/7796749/2021-12-31_112239_main.log)
[2021-12-31_112239_se-managed-disks-extension_8921.log](https://github.com/microsoft/AzureStorageExplorer/files/7796750/2021-12-31_112239_se-managed-disks-extension_8921.log)

I'm running from .tar.gz

best regards.

**Comment by JasonYeMSFT** [comment]
@luisrdzruiz I cannot reproduce this issue on a Fedora 35 VM after installing Storage Explorer to my /opt/StorageExplorer directory. I would recommend re-installing the .tar.gz in a user directory and retry running it. If the problem still exists, could you try installing it from snap? It usually has less problem with dependencies.

**Comment by 616b2f** [comment]
@JasonYeMSFT can you provider the list of dependent package that you installed in fedora? This would be also helpful to document this somewhere, because there are many people out there that do not use snap.

**Comment by JasonYeMSFT** [comment]
I only installed .net core 3.1 runtime manually. The version to install is documented here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#targz-file. The installation command can be found at https://docs.microsoft.com/en-us/dotnet/core/install/linux-fedora#install-the-runtime. Although we only test and verify our .tar.gz on Ubuntu, it should work on many other distributions.

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. If you have additional questions, please open a separate issue instead.
