### ISSUE TITLE
Cannot upload files

### ISSUE THREAD

**Issue by SPUDC9** [microsoft/AzureStorageExplorer#5304]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.22.0

### Regression From

1.18.0

### Architecture

i86

### Storage Explorer Build Number

20211211.10

### Platform

Windows

### OS Version

Windows 10

### Bug Description

{
  "message": "\"UnexpectedCancel\""
}

### Steps to Reproduce

Launch Storage Explorer
Open Storage Accounts
Veeam Backup
File shares
filebackups
Drag file into file list
Small files < 1 MB copy
Large files > 1 GB fail

### Actual Experience

No larger files will transfer

### Expected Experience

In the past I have uploaded large files and folder to storage.  I need to be able to offload these files manually into Azure for offline backup.

**Comment by JasonYeMSFT** [comment]
We had a similar issue where uploading to a File Share exceeding its quota causes AzCopy to emit this confusing error. https://github.com/microsoft/AzureStorageExplorer/issues/2841 Could you verify if your File Share still has sufficient quota to host the file? You can check that at portal.azure.com.

If this doesn't the error, could you use the "Go to AzCopy Log File" action on the activity and share a log file for the failed transfer with us for further investigation?

**Comment by SPUDC9** [comment]
Hi, Jason

You have my undying gratitude.  You were correct, I had unknowingly reached the maximum quota for the share.

I have increased the quota and now the file is transferring.

Thank you for your assistance.

ed
