### ISSUE TITLE
Fail to delete one entity which has empty PartitionKey/RowKey value in one emulator table

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5307]
**Storage Explorer Version:** 1.23.0-dev
**Build Number:** 20211220.7
**Branch:** main
**Platform/OS:** Windows 10
**Architecture:** ia32
**How Found:** AD hoc testing
**Emulator Version:** Azurite 3.14.3
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Install and start Azurite 3.14.3.
2. Launch Storage Explorer -> Expand 'Local & Attached -> Storage Accounts -> (Emulator - Default Ports)(Key)'.
3. Right click the 'Tables' node -> Create a table.
4. Click 'Add' -> 'Click 'Insert' -> An entity displays.
5. Click 'Delete' -> Click 'Yes' on the prompt dialog.
6. Check whether succeeds to delete the entity.

## Expected Experience ##
Succeed to delete the entity.

## Actual Experience ##
Fail to delete the entity, an error dialog pops up.
![image](https://user-images.githubusercontent.com/87792676/147814851-6f284165-0cc3-4087-908a-9f78dfff9ec4.png)

## Additional Context ##
Related bug: [4577](https://github.com/microsoft/AzureStorageExplorer/issues/4577)

**Comment by MRayermannMSFT** [comment]
Probably just bad impl of the API by the emulator. So just need to open a bug against Azurite?

**Comment by craxal** [comment]
See Azure/Azurite#1264.

**Comment by craxal** [comment]
This is resolved as of Azurite 3.17.1.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20220513.1 with running azurite 3.17.1. Fixed.
