### ISSUE TITLE
The message 'Shows 0 to 0 of o entries' doesn't display on bottom left of the table editor after closing the query builder with deleting all the entities 

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#531]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows/Linux Ubuntu 16.04/Mac
**Architecture**: ia32/x64
**Build Number**:20180801.3
**Commit**: 7cdb5326
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Expand a storage account -> Create one new table.
2. Add some entities for the opened table -> Click 'Query' then delete all the added entities.
3. Click 'Close Query' -> Check the displayed message on the editor.

#### Expected Experience: ####
The message 'Shows 0 to 0 of o entries' shows on the bottom left of the editor.

#### Actual Experience: ####
The message 'Shows 0 to 0 of o entries' doesn't show on the bottom left of the editor.
![message](https://user-images.githubusercontent.com/34729022/43514614-12dd0f52-9570-11e8-8e28-f8a4a2f061af.png)

**Comment by v-xianya** [comment]
Verified on build 20190108.2. This issue doesn't reproduce. Could you help to resolve it?

**Comment by jinglouMSFT** [comment]
Closing.
