### ISSUE TITLE
The file share snapshot does not auto display when creating a snapshot under the snapshots view in one 'Name & Key' attached storage account

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5315]
**Storage Explorer Version:** 1.23.0-dev
**Build Number:** 20210106.12
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**Architecture:** ia32/x64
**How Found:** Ad-hoc testing
**Regression From:**  Previous release(1.21.3)

## Steps to Reproduce ##

1. Select one storage account -> Attach it by 'Name & Key'.
2. Switch to the attached storage account -> File shares.
3. Create a file share -> Click 'View Share Snapshots'.
4. Create a snapshot for the file share -> Check whether the snapshot auto displays.

## Expected Experience ##
The snapshot auto displays.

## Actual Experience ##
The snapshot doesn't auto display.

## Additional Context ##

The snapshot displays after manually refreshing.

**Comment by MRayermannMSFT** [comment]
@v-kellyluo I'm having a hard time repro'ing this. Can you share a screen recording or gif?

**Comment by v-kellyluo** [comment]
Hi @MRayermannMSFT ,here is the record:
![snapshot](https://user-images.githubusercontent.com/87792676/148867639-4384fca4-34d3-4338-8c86-1ed1f1559975.gif)

**Comment by MRayermannMSFT** [comment]
Ohhhh under the snapshot view. I was looking at the dropdown. Thanks!

**Comment by MRayermannMSFT** [comment]
Hmmm @v-kellyluo still having a hard time with this, can you repro and upload the logs folder? Thanks. 🧐

**Comment by v-kellyluo** [comment]
Hi @MRayermannMSFT , I reproduced this issue and here is the logs folder:
[2022-01-11_182553.zip](https://github.com/microsoft/AzureStorageExplorer/files/7851371/2022-01-11_182553.zip)

**Comment by MRayermannMSFT** [comment]
@v-kellyluo I understand the issue now, and why I wasn't able to repro. I should have paid more attention as you said " Attach it by 'Name & Key'.", which literally meant you picked the name & key option, as opposed to the connection string option. Thanks for the patience. I'll close this once a fix is merged.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20220120.6. Fixed.
