### ISSUE TITLE
An error dialog pops up when creating one table with a valid name

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5317]
**Storage Explorer Version**: 1.23.0-dev
**Build Number**: 20220107.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 18.04/MacOS Big Sur 11.6.1
**How Found**: From running test cases
**Regression From**: Previous release (1.22.0)

## Steps to Reproduce ##
1. Expand one storage account.
2. Right click the 'Tables' node -> Click 'Create Table'.
3. Type a valid name to create a table.
4. Check no error dialog pops up.

## Expected Experience ##
No error dialog pops up.

## Actual Experience ##
An error dialog pops up.
![image](https://user-images.githubusercontent.com/41351993/148485495-12d08693-40c7-4cd0-9a77-da06dba8aaea.png)

**Comment by craxal** [comment]
@v-xianya We updated the table extension several times since this was opened. Can you verify whether this reproduces?

**Comment by v-xianya** [comment]
@craxal Verified this issue on the build main/20220206.3. Fixed.
