### ISSUE TITLE
An error dialog pops up when clicking 'Configure CORS Settings...' on the 'Tables' node

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5318]
**Storage Explorer Version**: 1.23.0-dev
**Build Number**: 20220107.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 18.04/MacOS Big Sur 11.6.1
**How Found**: From running test cases
**Regression From**: Previous release (1.22.0)

## Steps to Reproduce ##
1. Expand one storage account.
2. Right click the 'Tables' node -> Click 'Configure CORS Settings...'.
3. Check no error dialog pops up.

## Expected Experience ##
No error dialog pops up.

## Actual Experience ##
An error dialog pops up.
![image](https://user-images.githubusercontent.com/41351993/148485775-95d82f66-fe2a-4f0e-b908-baf3d4e48fbc.png)

**Comment by craxal** [comment]
@v-xianya We updated the table extension several times since this was opened. Can you verify whether this reproduces?

**Comment by v-xianya** [comment]
@craxal This issue still reproduces on the latest build main/20220206.3.

**Comment by craxal** [comment]
The "Tables 2" is the one we want testing. It will become the new "Tables" node very soon. So, if this issue does not reproduce for "Tables 2", we can consider this issue resolved.

**Comment by v-xianya** [comment]
Verified this issue on the build 20220208.1. Fixed.
