### ISSUE TITLE
There is a successful activity log when pasting one blob container to emulator blob containers node which already has the same blob container

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5319]
**Storage Explorer Version:** 1.23.0-dev
**Build Number:** 20220107.2
**Branch:** main
**Platform/OS:** Windows 10
**How Found:** Ad-hoc testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Install and run Azurite 3.14.3 -> Launch Storage Explorer.
2. Expand 'Local & Attached -> Storage Accounts -> (Emulator - Default Ports)(Key)'.
3. Blob Containers -> Create a blob container.
4. Right click the blob container -> Click 'Copy Blob Container'.
5. Right click Blob Containers node -> Click 'Paste Blob Container'.
6. Check whether there is a failed dialog indicating the blob container already exists.

## Expected Experience ##
There is a failed activity log indicating the blob container already exists.

## Actual Experience ##
There is a successful activity log.
![image](https://user-images.githubusercontent.com/87792676/148515676-8c11003c-08d3-4c4a-899b-c61f2129db4a.png)

## Additional Context ##
This issue doesn't reproduce when creating a emulator blob container which already exists.

**Comment by MRayermannMSFT** [comment]
Since the paste is going through our old JS code, I'm going to put this in future for now. We should revisit this once emulator copy/paste for blob containers is using AzCopy code path.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220415.4. Fixed.
