### ISSUE TITLE
Storage Static website workflow enhancements

### ISSUE THREAD

**Issue by madaz** [microsoft/AzureStorageExplorer#532]
**Storage Explorer Version**: 1.3.1
**Platform/OS Version**: Windows
**Architecture**: ia32
**Regression From**: n/a

#### Steps to Reproduce: ####
1. Click the Storage Accounts storage account
2. Select the 'Properties' tab

#### Expected Experience: ####

No Zone Name in Storage account properties tab

[https://msdn.microsoft.com/en-us/library/azure/ee460802.aspx]( https://msdn.microsoft.com/en-us/library/azure/ee460802.aspx)

zone-name is required for the url.
[https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website)

_Or_

Ability to find the Static website url for the storage account by right clicking the `$web` folder and `Open in Browser` menu option

#### Actual Experience: ####
nothing

**Comment by craxal** [comment]
@madaz Are you asking for us to show the web endpoint of the storage account, if it has one?

**Comment by madaz** [comment]
@craxal  Yes please, make it easier to discover the azure static website feature of the storage acct and it's url

**Comment by craxal** [comment]
@madaz We can add a "Web Endpoint" property in the Properties tab pretty easily, which should provide what you need.
