### ISSUE TITLE
Unable to retrieve child resources.

### ISSUE THREAD

**Issue by nazmulbhuiyan** [microsoft/AzureStorageExplorer#5323]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.22.0

### Architecture

x64

### Storage Explorer Build Number

20211211.10

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Getting the below error when I tried to expand the blob container.

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://stbidatadev001.blob.core.windows.net/?comp=list&include=metadata failed, reason: unable to get local issuer certificate",
  "stack": "FetchError: request to https://stbidatadev001.blob.core.windows.net/?comp=list&include=metadata failed, reason: unable to get local issuer certificate\n    at ClientRequest.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1483:11)\n    at ClientRequest.emit (events.js:315:20)\n    at TLSSocket.socketErrorListener (_http_client.js:469:9)\n    at TLSSocket.emit (events.js:315:20)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
  "type": "system",
  "errno": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY",
  "code": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"
}

### Steps to Reproduce

1. Launch Storage Explorer
2. Expand the Blob Container Node

### Actual Experience

I'm getting the above-mentioned error. 
Works on my mac though

**Comment by MRayermannMSFT** [comment]
@nazmulbhuiyan can you give system proxy a try? Read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by MRayermannMSFT** [comment]
Closed due to lack of response. If you continue encountering this issue we recommend either opening an Azure Support ticket via the portal, or opening a new issue here.
