### ISSUE TITLE
Unable to retrieve child resources (Tables only - Blob containers work)

### ISSUE THREAD

**Issue by dariusonsched** [microsoft/AzureStorageExplorer#5324]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.22.0

### Architecture

i86

### Storage Explorer Build Number

20211211.10

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Two users are receiving the following error:

**Unable to retrieve child resources.**

Details:
Unable to perform operation 'TableServiceClient.listTables'. No suitable credentials provided.

Yet, these same two users:
- [x] Have the following roles assigned within the storage account: Storage Table Data Contributor, Storage Blob Data Contributor and Storage Queue Data Contributor
- [x] Are able to access the Blob containers in the storage account via Azure Storage Explorer for Windows
- [x] Are able to access the Tables via the Azure Portal's Storage Explorer (preview) web interface.

A user running the same version of Storage Explorer (1.22.0) also on Windows, who has the above three roles PLUS the Storage Account Contributor is able to successfully access the Tables list and enumerator the contents within Azure Storage Explorer for Windows.

I've never seen this issue before and there is not much help online.  While some have had this issue with Blob containers, we are only having this with Tables.

To reiterate, the affected users **_**have**_** Storage Table Data Contributor over the Storage Account.

Thank you

### Steps to Reproduce

1. Launch Storage Explorer
2. Authenticate via integrated/SSO Azure AD authentication with a user having Storage Table Data Contributor, Storage Blob Data Contributor and Storage Queue Data Contributor role assignments on the Storage Account.
2. Browse to a Storage Account and attempt to enumerate the tables list.

### Actual Experience

The following error appears in a modal dialog box:

**Unable to retrieve child resources.**

Details:
Unable to perform operation 'TableServiceClient.listTables'. No suitable credentials provided.

### Expected Experience

One should be able to browse the Table contents of a Storage Account using Storage Explorer when they have Storage Table Data Contributor role assigned.

**Comment by craxal** [comment]
@dariusonsched Are you trying to access tables via RBAC without keys? If so, this is not yet supported for tables, so it won't matter what roles you have unless you have access to account keys. We're working on adding support now (#4542).

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem we recommend opening a support ticket via the Azure Portal.
