### ISSUE TITLE
Unable to Launch Cosmos DB Accounts in MAC OS of Microsoft Azure Storage Explorer 1.22.0 version

### ISSUE THREAD

**Issue by vgovind-BRONGA** [microsoft/AzureStorageExplorer#5325]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.22.0

### Architecture

x64

### Platform

macOS

### OS Version

macBook Big Sur

### Bug Description

unable to launch as it shows in retires

### Steps to Reproduce

1.Launch Storage Explorer 
2. add database and create Lease container

### Actual Experience

not able to launch

### Expected Experience

Successfully launched

**Comment by StefArroyo** [comment]
Hi @vgovind-BRONGA ,

We have retired support for Cosmos DB on Azure Storage Explorer in the 1.22.0 release. We are actively working on an alternative solution using Azure Data Studio, a unified desktop tooling experience exclusively for Azure databases. In the meantime, you can continue to use the following options: [version 1.21.3 of Azure Storage Explorer](https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.21.3) which integrates with Azure Cosmos DB, the [Azure Portal](https://portal.azure.com/), [Azure Portal desktop app](https://portal.azure.com/App/Download) or the standalone [Azure Cosmos DB Explorer](https://docs.microsoft.com/en-us/azure/cosmos-db/data-explorer).
