### ISSUE TITLE
The queried entities do not disappear when executing query with typing '0' into the 'Show top results' field

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5328]
**Storage Explorer Version**: 1.22.1
**Build Number**: 20220112.8
**Branch**: hotfix/1.22.1
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.6.1
**How Found**: Ad-hoc testing
**Regression From**: Previous release (1.21.3)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Add several entities. (As the below)
![image](https://user-images.githubusercontent.com/41351993/149289114-4cab524d-759f-4d52-8acd-862cf00e1a04.png)
3. Run query `PartitionKey eq '1' and RowKey eq '1'` -> There is one queried entity.
4. Expand the 'Advanced Option' -> Type '0' into the 'Show top results' field -> Execute query.
5. Check whether the queried entity disappears.

## Expected Experience ##
The queried entity disappears.
![image](https://user-images.githubusercontent.com/41351993/149289789-cc9f03f2-bf72-4df2-87d8-380b3e597524.png)

## Actual Experience ##
The queried entity doesn't disappear.
![image](https://user-images.githubusercontent.com/41351993/149290069-af2cdf34-3c25-4fb6-a3bc-dab965c744d9.png)

**Comment by craxal** [comment]
I'd consider this a no-fix. Once again, "top" doesn't necessarily limit how many results you get back. It only controls the number of results the service returns _per continuation_. Regardless, 0 is not a meaningful value to use.

**Comment by craxal** [comment]
Did some digging, and this is due to an error in our own code:

```ts
public topValueNumber = ko.pureComputed<number | undefined>(() => Number.parseInt(this.topValue()) || undefined);
```

When the value is 0, `0 || undefined` evaluates to `undefined`, since 0 is falsey. We just need to fix the logic here.

**Comment by v-xianya** [comment]
Verified this issue on the build 20220113.2. Fixed.
