### ISSUE TITLE
Change .azcopy folder location in Users

### ISSUE THREAD

**Issue by clippy-coder** [microsoft/AzureStorageExplorer#5329]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I am unable to prevent the .azcopy folder from being created in my Users directory. I can't figure out how to change the path where this folder storing plans and logs is created on my machine.

### Desired Solution

I'd like to be able to configure the plans and logs location from the application settings, or atleast having the app cleaning and deleting these folders when being closed.

### Alternatives and Workarounds

Alternatively, it would be helpful to know if these locations can be changed through environment variables, the cmd, or any other way.

### Additional Context
![azcopy folder](https://user-images.githubusercontent.com/22932478/149304455-9f1ca9ff-2677-4f7b-8c62-475e1bbacb98.PNG)

**Comment by clippy-coder** [comment]
Hi @MRayermannMSFT,

Unfortunately, this did not help within the context of the Azure Storage Explorer app. 

I see how this documentation would help in the case of running myself the AzCopy command, but not when the application itself is doing it. I've tried to set the environment variable on my system to see if the ASE would pick up on that, but it doesn't.

I've decided to write a simple script that runs on startup which cleans the folder so that I don't have to keep on manually doing it myself.

Anyway, I appreciate your answer! Thank you very much.

**Comment by MRayermannMSFT** [comment]
> I've tried to set the environment variable on my system to see if the ASE would pick up on that, but it doesn't.

Hmmmm that doesn't sound right. That should have worked for you, I'll take a look at this and see if we're doing something we shouldn't.

**Comment by clippy-coder** [comment]
@MRayermannMSFT Thank you so much for your detailed answer. I've managed to make it work following the exact steps you've explained. 

It was important to:

- set both paths (logs and plans)
- set them in a place where the user account had access
- restart the ASE after that so that changes where picked up by the app

However, for some reason the .azcopy folder keeps getting created on the User account path, allthough **empty**.

I'd be awesome to also be able to avoid having this folder being created in the first place, since nothing seems to be stored in it anyway. Do you also get the same behaviour?

Regardless, thanks again for the top-notch answer!

**Comment by MRayermannMSFT** [comment]
> However, for some reason the .azcopy folder keeps getting created on the User account path, allthough empty.

I'll raise this issue with the AzCopy team. Glad you were able to get it figured out. :)
