### ISSUE TITLE
SAS URI ingestiondata keeps loading...

### ISSUE THREAD

**Issue by kiwani10** [Microsoft/AzureStorageExplorer#533]
**Storage Explorer Version**: 1.3.1
**Platform/OS Version**: Win 10 (latest version)
**Architecture**: ia32

#### Steps to Reproduce: ####
1. Set up the azure storage explorer
2. Log in using SAS URI, connect successfully
3. Ingestiondata folder keeps loading...

#### Expected Experience: ####
There should be PST files in it as I already uploaded some via AZCopy, but we want to use this tool right now. It is lot easier than AZCopy

Note: On a different computer it is working perfect with same steps, but this computer is not on the domain we need.

**Comment by kiwani10** [comment]
Emulator is started as this will be an answer.

**Comment by craxal** [comment]
It's unclear from your steps exactly how to repro. What kind of Azure service/resource are you trying to connect to? What SAS URI are you using? Where did you get the SAS URI? Can you share it here (minus the signature)? How does the emulator factor into this?

**Comment by kiwani10** [comment]
I am trying to access our SAS URI we generated by  using the security and compliance admin center when creating a new import job. https://773293111db14e62875165e.blob.core.windows.net (not the full link as it will be confidential). On this URL we uploaded a lot of PST files using AZCopy only within our network we are not able to see them. It will be some network settings, I already checked the Proxy they should be fine. Do you know other settings like firewall, etc? that might cause the problem.

**Comment by kiwani10** [comment]
We put a work around on the network now it is working.
Thanks for the support

**Comment by craxal** [comment]
Glad you found a workaround. Can you share any details in case someone encounters a similar issue?
