### ISSUE TITLE
Unable to start ASE

### ISSUE THREAD

**Issue by machowsk** [microsoft/AzureStorageExplorer#5331]
When I try to start ASE, I get the following error:

> The authentication library used by Storage Explorer has failed to start properly. Please ensure you have .NET Framework 4.7.2 or greater installed. If .NET Framework 4.7.2 or greater is already installed then refer to the troubleshooting guide for help. Verbose authentication logging has been enabled.
> 
> Error:Hub Controller process exited prematurely with exit code 3221225478.

OS: Win 10 Pro, 21H2
ASE Version: 1.22.0
I checked the prerequisites, and I have .NET versions:
PSChildName                      Version
-----------                      -------
v2.0.50727                       2.0.50727.4927
v3.0                             3.0.30729.4926
Windows Communication Foundation 3.0.4506.4926
Windows Presentation Foundation  3.0.6920.4902
v3.5                             3.5.30729.4926
Client                           4.8.04084
Full                             4.8.04084
Client                           4.0.0.0

Logs attached
[ASE_logs.zip](https://github.com/microsoft/AzureStorageExplorer/files/7866522/ASE_logs.zip)

**Comment by MRayermannMSFT** [comment]
@machowsk thank you so much for providing these logs from the get-go! Unfortunately this is not an error we've ever seen before. Let me forward this to the team that owns this library. Will get back to you once I hear from them.

**Comment by MRayermannMSFT** [comment]
@machowsk can you please try using Storage Explorer 1.26 and let me know if this still reproduces for you? We upgraded the version of the component that was causing your issue.
