### ISSUE TITLE
It would be better to adjust the size to remove the scroll bar in the 'Shared Access Signature' dialog when the access policy field has 63 characters

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5334]
**Storage Explorer Version:** 1.23.0-dev
**Build Number:** 20220113.2
**Branch:** hotfix/1.22.1
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**How Found:** Ad-hoc testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create a blob container.
3. Right click the blob container -> Click 'Manage Access Policies...'.
4. An 'Access Policy' dialog pops up -> Click 'Add' -> Type 63 characters to Id field -> Click 'Save'.
5. Right click the blob container -> Click 'Get Shared Access Signature...'.
6. A 'Shared Access Signature' dialog pops up.
7. Check there is no scroll bar.

## Expected Experience ##
There is no scroll bar.

## Actual Experience ##
There is an scroll bar.
![image](https://user-images.githubusercontent.com/87792676/149487800-3d7579be-1262-4a10-8a52-07ae3bc84a33.png)

## Additional Context ##

1. This issue doesn't reproduce for tables.
2. There are two scroll bars for file shares/queues.
![image](https://user-images.githubusercontent.com/87792676/149488997-f26a3df6-7b67-4abb-b17a-449914558c41.png)
3. There are two scroll bars for blob containers when pulling the dialog horizontally.

**Comment by JasonYeMSFT** [comment]
I am going to won't fix this issue for now since this is a very edge case.
