### ISSUE TITLE
Operations on FIle Shares failing, including deletion, upload, download

### ISSUE THREAD

**Issue by riyaintouch** [microsoft/AzureStorageExplorer#5336]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.22.0

### Regression From

1.18.0

### Architecture

x64

### Storage Explorer Build Number

20211211.10

### Platform

Windows

### OS Version

Windows 11

### Bug Description

{
  "message": "\"failed to perform remove command due to error: cannot start job due to error: -> github.com/Azure/azure-storage-file-go/azfile.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.6.1-0.20201111053559-3c1754dc00a5/azfile/zc_storage_error.go:42\\n===== RESPONSE ERROR (ServiceCode=) =====\\nDescription=failed to unmarshal response body, Details: (none)\\n   GET https://azqexecutionservicesa.file.core.windows.net/%0A/acishare/Test?restype=directory&se=2022-02-13t20%3A22%3A26z&sig=-REDACTED-&sp=rwdl&sr=s&sv=2020-10-02&timeout=901\\n   User-Agent: [Microsoft Azure Storage Explorer, 1.22.0, win32, azcopy-node, 2.0.0, win32,  AzCopy/10.13.0 Azure-Storage/0.8.0 (go1.16; Windows_NT)]\\n   X-Ms-Client-Request-Id: [659fe0b4-d606-484b-62f8-10d55f203a66]\\n   X-Ms-Version: [2019-12-12]\\n   --------------------------------------------------------------------------------\\n   RESPONSE Status: 400 Bad Request\\n   Content-Length: [324]\\n   Content-Type: [text/html; charset=us-ascii]\\n   Date: [Fri, 14 Jan 2022 20:22:29 GMT]\\n   Server: [Microsoft-HTTPAPI/2.0]\\n\\n\\nxml: (*azfile.storageError).UnmarshalXML did not consume entire <HTML> element\\n.\\n\""
}

### Steps to Reproduce

Try to delete a folder in File Share

### Actual Experience

Deletion fails

### Expected Experience

Deletion should not fail

**Comment by riyaintouch** [comment]
Uploads failing with this error: 2022/01/14 20:28:04 AzcopyVersion  10.13.0
2022/01/14 20:28:04 OS-Environment  windows
2022/01/14 20:28:04 OS-Architecture  amd64
2022/01/14 20:28:04 Log times are in UTC. Local time is 15 Jan 2022 01:58:04
2022/01/14 20:28:04 Job-Command copy C:\Users\madhudg\Desktop\Disk Repair.txt https://azqexecutionservicesa.file.core.windows.net/%0A/acishare/Test/Disk%20Repair.txt?se=2022-02-13t20%3A28%3A02z&sig=-REDACTED-&sp=rwl&sr=s&sv=2020-10-02 --output-type=json --cancel-from-stdin --overwrite=prompt --from-to=LocalFile --follow-symlinks --put-md5 --follow-symlinks --preserve-smb-info=true --disable-auto-decoding=false --recursive --log-level=INFO 
2022/01/14 20:28:04 Number of CPUs: 8
2022/01/14 20:28:04 Max file buffer RAM 4.000 GB
2022/01/14 20:28:04 Max concurrent network operations:  will be dynamically tuned up to 3000 (Based on auto-tuning limit. Set AZCOPY_CONCURRENCY_VALUE environment variable to override)
2022/01/14 20:28:04 Check CPU usage when dynamically tuning concurrency: true (Based on hard-coded default. Set AZCOPY_TUNE_TO_CPU environment variable to true or false override)
2022/01/14 20:28:04 Max concurrent transfer initiation routines: 64 (Based on hard-coded default. Set AZCOPY_CONCURRENT_FILES environment variable to override)
2022/01/14 20:28:04 Max enumeration routines: 16 (Based on hard-coded default. Set AZCOPY_CONCURRENT_SCAN environment variable to override)
2022/01/14 20:28:04 Parallelize getting file properties (file.Stat): false (Based on AZCOPY_PARALLEL_STAT_FILES environment variable)
2022/01/14 20:28:04 Max open files when downloading: 2147483119 (auto-computed)
2022/01/14 20:28:04 ISO 8601 START TIME: to copy files that changed before or after this job started, use the parameter --include-before=2022-01-14T20:27:58Z or --include-after=2022-01-14T20:27:58Z
2022/01/14 20:28:04 WARN: Failed to check if the destination is a folder or a file (Azure Files). Assuming the destination is a file: -> github.com/Azure/azure-storage-file-go/azfile.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.6.1-0.20201111053559-3c1754dc00a5/azfile/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=) =====
Description=failed to unmarshal response body, Details: (none)
   GET https://azqexecutionservicesa.file.core.windows.net/%0A/acishare/Test/Disk%20Repair.txt?restype=directory&se=2022-02-13t20%3A28%3A02z&sig=-REDACTED-&sp=rwl&sr=s&sv=2020-10-02&timeout=901
   User-Agent: [Microsoft Azure Storage Explorer, 1.22.0, win32, azcopy-node, 2.0.0, win32,  AzCopy/10.13.0 Azure-Storage/0.8.0 (go1.16; Windows_NT)]
   X-Ms-Client-Request-Id: [efb23dfb-d8a4-445f-762c-d2698a924ff7]
   X-Ms-Version: [2019-12-12]
   --------------------------------------------------------------------------------
   RESPONSE Status: 400 Bad Request
   Content-Length: [324]
   Content-Type: [text/html; charset=us-ascii]
   Date: [Fri, 14 Jan 2022 20:28:03 GMT]
   Server: [Microsoft-HTTPAPI/2.0]


xml: (*azfile.storageError).UnmarshalXML did not consume entire <HTML> element

2022/01/14 20:28:04 Any empty folders will be processed, because source and destination both support folders. For the same reason, properties defined on folders will be processed
2022/01/14 20:28:04 Final job part has been created
2022/01/14 20:28:04 Trying 4 concurrent connections (initial starting point)
2022/01/14 20:28:04 scheduling JobID=53b7cd94-a966-3b4e-5f2c-4093cd32c6c5, Part#=0, Transfer#=0, priority=0
2022/01/14 20:28:04 Final job part has been scheduled
2022/01/14 20:28:04 PERF: primary performance constraint is Unknown. States: X:  0, O:  0, M:  0, L:  0, R:  0, D:  0, W:  0, F:  0, B:  0, E:  0, T:  0, GRs:  4
2022/01/14 20:28:04 0.0 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total, 
2022/01/14 20:28:04 INFO: [P#0-T#0] has worker 7 which is processing TRANSFER 0
2022/01/14 20:28:04 WARN: [P#0-T#0] Block size 8388608 larger than maximum file chunk size, 4 MB chunk size used
2022/01/14 20:28:04 INFO: [P#0-T#0] Starting transfer: Source "\\\\?\\C:\\Users\\madhudg\\Desktop\\Disk Repair.txt" Destination "https://azqexecutionservicesa.file.core.windows.net/%0A/acishare/Test/Disk%20Repair.txt?se=2022-02-13t20%3A28%3A02z&sig=-REDACTED-&sp=rwl&sr=s&sv=2020-10-02". Specified chunk size 4194304
2022/01/14 20:28:04 ==> REQUEST/RESPONSE (Try=1/80.4868ms, OpTime=399.4791ms) -- RESPONSE STATUS CODE ERROR
   HEAD https://azqexecutionservicesa.file.core.windows.net/%0A/acishare/Test/Disk%20Repair.txt?se=2022-02-13t20%3A28%3A02z&sig=-REDACTED-&sp=rwl&sr=s&sv=2020-10-02&timeout=901
   User-Agent: [Microsoft Azure Storage Explorer, 1.22.0, win32, azcopy-node, 2.0.0, win32,  AzCopy/10.13.0 Azure-Storage/0.8.0 (go1.16; Windows_NT)]
   X-Ms-Client-Request-Id: [679b6834-7ec2-4d9f-7f69-3544e8fed722]
   X-Ms-Version: [2020-02-10]
   --------------------------------------------------------------------------------
   RESPONSE Status: 400 Bad Request
   Content-Length: [324]
   Content-Type: [text/html; charset=us-ascii]
   Date: [Fri, 14 Jan 2022 20:28:04 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
Response Details: 

2022/01/14 20:28:04 ERR: [P#0-T#0] UPLOADFAILED: \\?\C:\Users\madhudg\Desktop\Disk Repair.txt : 000 : Could not check destination file existence. -> github.com/Azure/azure-storage-file-go/azfile.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.6.1-0.20201111053559-3c1754dc00a5/azfile/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=) =====
Description=400 Bad Request, Details: (none)
   HEAD https://azqexecutionservicesa.file.core.windows.net/%0A/acishare/Test/Disk%20Repair.txt?se=2022-02-13t20%3A28%3A02z&sig=-REDACTED-&sp=rwl&sr=s&sv=2020-10-02&timeout=901
   User-Agent: [Microsoft Azure Storage Explorer, 1.22.0, win32, azcopy-node, 2.0.0, win32,  AzCopy/10.13.0 Azure-Storage/0.8.0 (go1.16; Windows_NT)]
   X-Ms-Client-Request-Id: [679b6834-7ec2-4d9f-7f69-3544e8fed722]
   X-Ms-Version: [2020-02-10]
   --------------------------------------------------------------------------------
   RESPONSE Status: 400 Bad Request
   Content-Length: [324]
   Content-Type: [text/html; charset=us-ascii]
   Date: [Fri, 14 Jan 2022 20:28:04 GMT]
   Server: [Microsoft-HTTPAPI/2.0]



   Dst: https://azqexecutionservicesa.file.core.windows.net/%0A/acishare/Test/Disk%20Repair.txt?se=2022-02-13t20%3A28%3A02z&sig=-REDACTED-&sp=rwl&sr=s&sv=2020-10-02
2022/01/14 20:28:04 JobID=53b7cd94-a966-3b4e-5f2c-4093cd32c6c5, Part#=0, TransfersDone=1 of 1
2022/01/14 20:28:04 all parts of entire Job 53b7cd94-a966-3b4e-5f2c-4093cd32c6c5 successfully completed, cancelled or paused
2022/01/14 20:28:04 is part of Job which 1 total number of parts done 
2022/01/14 20:28:06 PERF: primary performance constraint is Unknown. States: X:  0, O:  0, M:  0, L:  0, R:  0, D:  0, W:  0, F:  0, B:  0, E:  0, T:  0, GRs:  4

**Comment by riyaintouch** [comment]
I even tried uninstalling and installing by chocolatey, same error resulted

**Comment by riyaintouch** [comment]
Downloads fail with this error: 
{
  "message": "\"failed to perform copy command due to error: cannot start job due to error: -> github.com/Azure/azure-storage-file-go/azfile.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.6.1-0.20201111053559-3c1754dc00a5/azfile/zc_storage_error.go:42\\n===== RESPONSE ERROR (ServiceCode=) =====\\nDescription=failed to unmarshal response body, Details: (none)\\n   GET https://azqexecutionservicesa.file.core.windows.net/%0A/acishare/Runs/007da68a-07a1-4261-95d9-9c88142daae2/Scripts/CreateNetperfDeployment.ps1?restype=directory&se=2022-02-13t20%3A29%3A58z&sig=-REDACTED-&sp=rl&sr=s&sv=2020-10-02&timeout=901\\n   User-Agent: [Microsoft Azure Storage Explorer, 1.22.0, win32, azcopy-node, 2.0.0, win32,  AzCopy/10.13.0 Azure-Storage/0.8.0 (go1.16; Windows_NT)]\\n   X-Ms-Client-Request-Id: [f2aa82be-c786-4ded-4645-08d86f674166]\\n   X-Ms-Version: [2019-12-12]\\n   --------------------------------------------------------------------------------\\n   RESPONSE Status: 400 Bad Request\\n   Content-Length: [324]\\n   Content-Type: [text/html; charset=us-ascii]\\n   Date: [Fri, 14 Jan 2022 20:29:59 GMT]\\n   Server: [Microsoft-HTTPAPI/2.0]\\n\\n\\nxml: (*azfile.storageError).UnmarshalXML did not consume entire <HTML> element\\n.\\n\""
}

**Comment by JasonYeMSFT** [comment]
@riyaintouch Do you know why there is a line feed character in the endpoint (%0A)? That might happen when you used a corrupted url to connect to the resource. Could you try reconnecting to the resource with the url without that line feed character and retry these operations?

**Comment by riyaintouch** [comment]
I used the same connection string that was displayed in my Storage Account in Portal, file shares were accessible but I was not able to download/upload. Then I generated a new SAS from Storage Explorer for the same Storage Account (with read, write permission) and connected the File Share separately using the SAS. Then I was able to do the operations. Can you explain the reason for this observation?

**Comment by JasonYeMSFT** [comment]
I don't know for sure. We don't control how Azure Portal generates the connection string. You can submit a ticket on Portal for them to take a look.

**Comment by JasonYeMSFT** [comment]
Closing since the connection string issue is in Portal. If you can compare the connection string they generates and the ones we generate and find out the difference, feel free to let us know.
