### ISSUE TITLE
Error when attempting to navigate to file shares or blob storage [MacOS]

### ISSUE THREAD

**Issue by VenerableSpace** [microsoft/AzureStorageExplorer#5337]
Obtain error when navigating on storage explorer on macOS. Succesfully able to do so on Windows and through Linux with same account.

## OS: MacOS 11.6.1

Error details below:

```
Unable to retrieve child resources.

Details:
{
  "name": "Error",
  "message": "File Shares do not support Azure AD access",
  "stack": "Error: File Shares do not support Azure AD access\n    at FileServiceClient._createPipeline (/private/var/folders/zc/1hctf7cs17n8b70fdsq432dh0000gn/T/AppTranslocation/A2E8B5CD-073C-4FB7-8D7B-92C056D2F79A/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/se-file-extension/dist/index.js:2:34472)\n    at FileServiceClient.createClient (/private/var/folders/zc/1hctf7cs17n8b70fdsq432dh0000gn/T/AppTranslocation/A2E8B5CD-073C-4FB7-8D7B-92C056D2F79A/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/se-file-extension/dist/index.js:2:457882)\n    at FileServiceClient.runOperation (/private/var/folders/zc/1hctf7cs17n8b70fdsq432dh0000gn/T/AppTranslocation/A2E8B5CD-073C-4FB7-8D7B-92C056D2F79A/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/se-file-extension/dist/index.js:2:457171)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async Function.produceFileShareNodes (/private/var/folders/zc/1hctf7cs17n8b70fdsq432dh0000gn/T/AppTranslocation/A2E8B5CD-073C-4FB7-8D7B-92C056D2F79A/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/se-file-extension/dist/index.js:2:57393)\n    at async Object.Azure.Storage.FileShareProducer.produceFileShareNodes (/private/var/folders/zc/1hctf7cs17n8b70fdsq432dh0000gn/T/AppTranslocation/A2E8B5CD-073C-4FB7-8D7B-92C056D2F79A/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/se-file-extension/dist/index.js:2:76556)\n    at async Provider.executeOperation (/private/var/folders/zc/1hctf7cs17n8b70fdsq432dh0000gn/T/AppTranslocation/A2E8B5CD-073C-4FB7-8D7B-92C056D2F79A/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/providers/Provider.js:27:16)\n    at async NodeProcessHostProxy._handleExecuteRequest (/private/var/folders/zc/1hctf7cs17n8b70fdsq432dh0000gn/T/AppTranslocation/A2E8B5CD-073C-4FB7-8D7B-92C056D2F79A/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/node/NodeProcessHostProxy.js:217:31)\n    at async NodeProcessHostProxy._handleMessage (/private/var/folders/zc/1hctf7cs17n8b70fdsq432dh0000gn/T/AppTranslocation/A2E8B5CD-073C-4FB7-8D7B-92C056D2F79A/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/node/NodeProcessHostProxy.js:171:24)\n    at async /private/var/folders/zc/1hctf7cs17n8b70fdsq432dh0000gn/T/AppTranslocation/A2E8B5CD-073C-4FB7-8D7B-92C056D2F79A/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/node/NodeProcessHostProxy.js:65:17"
}
```

**Comment by MRayermannMSFT** [comment]
@VenerableSpace azure file shares requires you to have key access. Can you click on the node for the storage account you are working with, look at the properties panel (bottom left), and check that there is a "Primary Key"? You'll have to click on the eye icon to confirm that.

What error are you getting when accessing blobs?

**Comment by VenerableSpace** [comment]
@MRayermannMSFT 

Yes I see all 4 of primary key, secondary key, primary connection string, secondary connection string.

This storage account does not have anything in the blog storage. However I am able to access blog storages for other storage accounts under the same resource group.

**Comment by MRayermannMSFT** [comment]
@VenerableSpace your title says you also got an error when trying to navigate to blob storage. So if there wasn't an error, is your title a typo? 

When you say you see all 4 of those things, did you click on the eye icon to reveal the values, and made sure they were really there? Like this:
![image](https://user-images.githubusercontent.com/21112697/150844819-bd383089-f490-4632-920a-d6d188e634fc.png)

Finally, can you follow [these](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#storage-explorer-logs) steps for gathering Storage Explorer logs, and then share your logs with us? Please set the STG_EX_LOG_LEVEL to debug. Thanks!

**Comment by VenerableSpace** [comment]
The title is correct, I misinterpreted the error the last time around (ie. https://github.com/microsoft/AzureStorageExplorer/issues/5337#issuecomment-1017825435 comment is incorrect). There are blob storage in the storage account which I cannot access. sorry about that.

Yes I have revealed the values and they are present.

I have obtained logs for this. There seems to be some sensitive information in the logs (subscription ID, etc.) Are these logs ok to share?

**Comment by MRayermannMSFT** [comment]
@VenerableSpace you are free to redact whatever you'd like with the logs before posting them here. Alternatively, if you'd rather just not have to deal with redaction, or would be ok just redacting a few things (or nothing) if you could send us the logs more privately, then you could do that and electronically mail us your logs via sehelp àt microsoft dôt com.

**Comment by VenerableSpace** [comment]
Hello,

If its ok I will just email my logs internally. Its not just subscription ID but also the blob storage names that are being accessed that is sensitive (I wouldn’t want it being public).

Thanks


From: Matthew Rayermann ***@***.***>
Date: Wednesday, January 26, 2022 at 3:14 PM
To: microsoft/AzureStorageExplorer ***@***.***>
Cc: Farrukh Rahman ***@***.***>, Mention ***@***.***>
Subject: Re: [microsoft/AzureStorageExplorer] Error when attempting to navigate to file shares or blob storage [MacOS] (Issue #5337)

@VenerableSpace<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FVenerableSpace&data=04%7C01%7Cfarrukh.rahman%40microsoft.com%7Ca3a4d4c7991a4a73f30f08d9e1218a6f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637788356461477862%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=c%2BxNB0s2x2LgUfTMdr%2FIaclUgYM448KbSzi9rXo84i4%3D&reserved=0> you are free to redact whatever you'd like with the logs before posting them here. Alternatively, if you'd rather just not have to deal with redaction, or would be ok just redacting a few things (or nothing) if you could send us the logs more privately, then you could do that and electronically mail us your logs via sehelp àt microsoft dôt com.

—
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FAzureStorageExplorer%2Fissues%2F5337%23issuecomment-1022689122&data=04%7C01%7Cfarrukh.rahman%40microsoft.com%7Ca3a4d4c7991a4a73f30f08d9e1218a6f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637788356461477862%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FqqVGLky%2FX4dAf%2BRo94yRDgIKIk11aLXuzgx5iP%2F67w%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOCDXOL4I2C4A5AAEXZ2M2DUYB53TANCNFSM5MAKFCPA&data=04%7C01%7Cfarrukh.rahman%40microsoft.com%7Ca3a4d4c7991a4a73f30f08d9e1218a6f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637788356461477862%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=CfzSmvEvx4YlqF%2BS%2BCnuYxsfAc1%2FNxd3ONJze%2BGL%2Bkw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cfarrukh.rahman%40microsoft.com%7Ca3a4d4c7991a4a73f30f08d9e1218a6f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637788356461527836%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XKudhK2jnkqQpidjDzckJbJO2JSInf4uAjiqpMIeE9w%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cfarrukh.rahman%40microsoft.com%7Ca3a4d4c7991a4a73f30f08d9e1218a6f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637788356461527836%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yIt%2BY43mzWjuZ%2F38EJRvLyoiN6hrklyqCBAoAVfgUDM%3D&reserved=0>.

**Comment by MRayermannMSFT** [comment]
Issue resolved. Keys were obtained and correct. Issue was that the storage account had an ip restriction. Restriction was updated and things worked as normal.
