### ISSUE TITLE
Installed Azure File Explorer for the 1st time in my Windows device, could not able to add an account and even if it added it's thorwing an error while trying to open the child storage parameters

### ISSUE THREAD

**Issue by imtithewaves** [microsoft/AzureStorageExplorer#5338]
Hello there!

I am providing the error which am getting,

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://storagetestwav.file.core.windows.net/?comp=list failed, reason: self signed certificate in certificate chain",
  "stack": "FetchError: request to https://storagetestwav.file.core.windows.net/?comp=list failed, reason: self signed certificate in certificate chain\n    at ClientRequest.<anonymous> (C:\\Users\\sintiyaz\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\index.js:2:103326)\n    at ClientRequest.emit (events.js:315:20)\n    at TLSSocket.socketErrorListener (_http_client.js:469:9)\n    at TLSSocket.emit (events.js:315:20)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
  "type": "system",
  "errno": "SELF_SIGNED_CERT_IN_CHAIN",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}

**Comment by MRayermannMSFT** [comment]
@imtithewaves can you give system proxy a try? Read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by MRayermannMSFT** [comment]
Closed due to lack of response. If you continue encountering this issue we recommend either opening an Azure Support ticket via the portal, or opening a new issue here.
