### ISSUE TITLE
Both the duplicate metadata are in red border when the latter name is same as the former

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/AzureStorageExplorer#534]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Win10 /MacOS High Sierra /Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20180802.6
**Commit**: e9fc436c
**Regression From**: Not a Regression

#### Steps to Reproduce: ####
1. Create one file share-> upload one file at least ->right click it and select 'Properties'.
2. Add one metadata.
3. Repeat Step2 with same name.
4. Check the result.

#### Expected Experience: ####
The latter metadata is in red border.

#### Actual Experience: ####
Both the duplicate metadata are in red border.
![compare](https://user-images.githubusercontent.com/34729092/43575798-3b88992c-9637-11e8-9551-cfab47a31856.png)

**Comment by craxal** [comment]
By design now. It's just easier to show the matching names.

**Comment by v-dantch** [comment]
Got it. Thanks for your update.
