### ISSUE TITLE
An error dialog pops up when cloning one non-empty file share under one SAS attached storage account with permissions 'Read, List, Create'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5340]
**Storage Explorer Version**: 1.22.1
**Build Number**: 20220114.4
**Branch**: hotfix/1.22.1
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.6.1
**How Found**: Ad-hoc testing
**Regression From**: Previous release (1.21.3)

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Upload files to the file share.
3. Right click the storage account -> Click 'Get Shared Access Signature...' -> Create a connection string with 'Read, List, Create' permissions -> Copy the connection string.
3. Attach the storage account via the copied connection string.
4. Expand the attached storage account -> File Shares.
5. Clone the file share which is created in Step2.
6. Check no error dialog pops up.

## Expected Experience ##
No error dialog pops up.

## Actual Experience ##
An error dialog pops up with the error "Cannot read property 'latestSatus' of null".
![image](https://user-images.githubusercontent.com/41351993/149907680-ed0ddd64-7083-42ab-aafc-d7a49b356007.png)

## Additional  Context ##
1. This issue also reproduces for file shares under one SAS URL attached storage account with 'Read, List, Create' permissions.
2. The activity log keeps loading status after closing the error dialog.
![image](https://user-images.githubusercontent.com/41351993/149907762-dda2e15f-5116-4657-bedf-92f7c3d3aeba.png)

**Comment by MRayermannMSFT** [comment]
Fixed on main.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20220119.4. Fixed.
