### ISSUE TITLE
Azure Storage Explorer ADLS files should have preview UI

### ISSUE THREAD

**Issue by cesarjo** [microsoft/AzureStorageExplorer#5343]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Cannot view all file types in the ADLS container

### Desired Solution

Preview top 100 rows of any file in the ADLS containers. Should support all file extensions -- eg .tsv and .ss (Cosmos structured streams)

### Alternatives and Workarounds

Open file using other apps (outside of Azure Storage Explorer)

**Comment by MRayermannMSFT** [comment]
@cesarjo couple of clarifying questions:
- Are you talking about ADLS Gen1 or ADLS Gen2
- When you say "view all file types", what do you mean by view? Are the files you want to see not visible or do you mean something else?

**Comment by cesarjo** [comment]
Hello -
Sorry I was not clear in my description.

I am referring to ADLS Gen2. "View all files (formats)" means a feature/UI that will allow user to open file for viewing - e.g., able to look through the columns and rows for a csv or tsv file format. We also work with the structured stream (.ss extension) file format - i.e., Cosmos as it's referred to internally at Microsoft - and this feature would allow user to view contents of .ss files as well.

Thanks
-cesar

**Comment by MRayermannMSFT** [comment]
@cesarjo ok gotcha, right now our recommendation is to download the file yourself and open it in a program specifically designed for working with such file types. Is there a reason you don't want to do that?

**Comment by cesarjo** [comment]
Our data engineering team almost exclusively works with (Cosmos) structured streams --- the .ss extension file format. When working in the Cosmos big data platform (internal to Microsoft), the user can use Explorer web browser to navigate folder path and view contents (in table layout) of the data in .ss files -- there is native support in Cosmos to work with any web browser.

The migration to use Azure Data Lake, now prohibits using the web browser to navigate to (ADLS folder path) and view .ss files. There is no other program/app to view Cosmos structure stream file format. More and more data teams inside of Microsoft have motivations to migrate from Cosmos to the Azure Data Lake (ADLA/ADLS-Gen2), but there does not appear to be a clear user scenario for viewing structured streams that will continue to be the file format for processing datasets (Scope language is used, which is similar to U-SQL language).

thanks
-cesar

**Comment by MRayermannMSFT** [comment]
@cesarjo are you internal? Can you shoot me a message on teams. I'd like to learn more about what you're talking about.

**Comment by JasonYeMSFT** [comment]
@cesarjo In 1.26.0 we added a feature to let you preview blobs as text with known extensions, do you have a chance to try it?
