### ISSUE TITLE
Succeed to use Int32 property to query one entity which has Int64 property

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5346]
**Storage Explorer Version:** 1.22.1
**Build Number:** 20220118.2
**Branch:** hotfix/1.22.1
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.6.1
**How Found:** Ad-hoc testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create a table -> Add one entity with Int64 property. (Like the below)
![image](https://user-images.githubusercontent.com/87792676/150100786-d2778a18-f5be-4f5c-bbf2-a77a942f1890.png)
3. Click 'Query' -> Add one clause.
4. Select 'num' in the 'Field' field -> Select 'Int32' type -> Type '64' in the 'Value' field.
5. Run the query -> Check whether fails to query the entity.

## Expected Experience ##
Fail to query the entity.

## Actual Experience ##
Succeed to query the entity.

## Additional Context ##
This issue doesn't reproduce when using Int64 property to query one entity which has Int32 property.

**Comment by craxal** [comment]
@v-kellyluo I don't think this needs to be fixed. The data type is used only to validate the entered values. The query is reduced to a string that is passed to the network request, and the query syntax has no concept of data types. So, for example, if the query clause you have is "Field", "Int32", "64", this just get's reduced to "Field eq '64'".

**Comment by v-kellyluo** [comment]
Hi @craxal ,thanks for your update! As you said "the data type is used only to validate the entered values", so this issue seems to be expected, but if the entity contains one Int32 property, we cannot query it using Int64 type, and the query statement is `num eq 32L`, is there any difference between the two situations?

**Comment by craxal** [comment]
@v-kellyluo According to the [documentation](https://docs.microsoft.com/en-us/rest/api/storageservices/querying-tables-and-entities#filtering-on-numeric-properties), to filter on numeric types, you use a unquoted number constant. There's nothing to suggest that the query differentiates between data types.

Granted, I don't think the documentation goes into enough detail. Here are my findings based on some experimentation:
* Using an integer constant (like `123`) returns Int32, Int64, and Double results.
* Using a long integer constant (like `123L`) returns Int64 and Double results. Note that selecting Int64 in the query builder automatically applies the `L` suffix to the constant.
* Using a decimal constant (like `12.3`) returns only Double results.

Sounds to me like this is perfectly normal behavior, albeit a little unintuitive. The query builder could use some attention, but I don't think this is something we need to worry about unless users express some confusion about the behavior or the UI.

**Comment by v-kellyluo** [comment]
Hi @craxal, got it! Thanks for your patience, we are going to close this issue.
