### ISSUE TITLE
Table Import/Export Encoding

### ISSUE THREAD

**Issue by Phil-B** [microsoft/AzureStorageExplorer#5347]
Some characters are lost when using the export and import features.

When using the built-in editor I can successfully paste an `è` character into an Edm.String value. When this is exported it becomes `Ã`. When using the import feature, the `è` simply becomes `�`

Storage Explorer Version: 1.22.0
Build Number: 20211211.10
Platform/OS: Windows 10

**Comment by MRayermannMSFT** [comment]
Phil-B we aren't able to repro this, could you share:
- a read-only SAS to a table that we can use to repro the export side of the bug?
- a .csv file with us that we can repro the import side of the bug?

Also to be clear, when you say built-in editor, what do you mean? Are you talking about:
- adding an entity
- editing an entity
- some editor program on windows that you use to edit .csv files

**Comment by Phil-B** [comment]
Here's a SAS for a demo table:

https://31a9b3f.table.core.windows.net/Demo5347?st=2022-01-21T11%3A07%3A44Z&se=2023-01-22T11%3A07%3A00Z&sp=r&sv=2018-03-28&tn=demo5347&sig=%2F1kAWNlgdCfVkXGe8SMOkAaToGs3wZSasfmez3qwsRs%3D

Here's the file which is Exported
[Demo5347.csv](https://github.com/microsoft/AzureStorageExplorer/files/7912877/Demo5347.csv)

And here's a file which you can Import
[Demo5347Import.csv](https://github.com/microsoft/AzureStorageExplorer/files/7912901/Demo5347Import.csv)

When I refer to the built-in editor I mean when adding and editing entities in Storage Explorer.

Hope that helps

**Comment by Phil-B** [comment]
Just following up, I've now realised that when I open the exported file in notepad the character displays fine. It's only handled incorrectly in Excel. This looks like an excel issue which is already documented
