### ISSUE TITLE
Getting Couldn't access resources for this tenant in Azure Storage Explorer

### ISSUE THREAD

**Issue by sureshgottimukkala** [microsoft/AzureStorageExplorer#5348]
{
  "message": "\"{\\n  \\\"message\\\": \\\"\\\\\\\"The resource you are attempting to access is in a tenant which is currently filtered out. Un-filter it to access this resource.\\\\\\\"\\\"\\n}\""
}

**Comment by MRayermannMSFT** [comment]
@sureshgottimukkala can you go to the account panel (person icon on the left-hand vertical toolbar), and check the checkbox for the tenant which the resource you are trying to access is in? Though, looking at this message, I think we should try to see if we can get the tenant ID included in there....

**Comment by MRayermannMSFT** [comment]
Closed due to lack of response. If you continue encountering this issue we recommend either opening an Azure Support ticket via the portal, or opening a new issue here.
