### ISSUE TITLE
There is no deleted activity log when deleting one entity

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5353]
**Storage Explorer Version:** 1.22.1
**Build Number:** 20220120.1
**Branch:** hotfix/1.22.1
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.6.1
**How Found:** Ad-hoc testing
**Regression From:** Previous release (1.21.3)

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create a table -> Add one entity.
3. Delete the entity -> Check whether there is a deleted activity log.

## Expected Experience ##
There is a deleted activity log.
![image](https://user-images.githubusercontent.com/87792676/150301608-d1839a92-52b8-417b-a969-3e1500be2679.png)

## Actual Experience ##
There is no deleted activity log.

**Comment by v-xianya** [comment]
Verified this issue on the build hotfix 20220121.1. Fixed.
![image](https://user-images.githubusercontent.com/41351993/150478733-8d656f67-03c4-417d-a599-2effc64915e3.png)
