### ISSUE TITLE
The string 'Show x to x of x cached items' doesn't display on lower left corner of the table editor after clicking 'Refresh' at the query status (apply 'Clear All' on the Select Columns dialog)

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5354]
**Storage Explorer Version**: 1.22.1
**Build Number**: 20220120.1
**Branch**: hotfix/1.22.1
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.6.1
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Add some entities.
3. Click 'Query' -> Click 'Advanced Options -> Select Columns...'.
4. Click 'Clear All' on the 'Select Columns' dialog -> Click 'OK'.
5. Execute query -> Click 'Refresh'.
6. Check whether the status string 'Show x to x of x cached items' displays on the lower left corner of the editor.

## Expected Experience ##
The status string 'Show x to x of x cached items' displays on the lower left corner of the editor.

## Actual Experience ##
The status string 'Show x to x of x cached items' doesn't display on the lower left corner of the editor.
![image](https://user-images.githubusercontent.com/41351993/150342059-fdbd5050-e7b7-47b8-aeb4-3a8ecf5f6fc1.png)

## Additional Context ##
The related bug [531](https://github.com/microsoft/AzureStorageExplorer/issues/531) also reproduces.

**Comment by craxal** [comment]
It looks like the query builder is pushing the status message further down. If a window resizing event occurs, the status message and page buttons pop back into view. Also related to #4568

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220212.2. Fixed.
