### ISSUE TITLE
Please reintroduce support for CosmosDB

### ISSUE THREAD

**Issue by curia-damiano** [microsoft/AzureStorageExplorer#5355]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I'd like support for CosmosDB back

### Desired Solution

Reintroduce it

### Alternatives and Workarounds

Only the Azure Portal is available for personal subscriptions

### Additional Context

CosmosDB Explorer is not available for non-enterprise subscriptions. The current implementation was just fine, can you please reintroduce it as it is?

**Comment by MrDRamos** [comment]
Miss the ability to browse cosmosDB colletions. The ability to have more than 1 tab opened against the same collection was a great feature!

**Comment by StefArroyo** [comment]
Hello @curia-damiano and @MrDRamos,

Thank you so much for feedback on our desktop tooling, we appreciate the time you have taken to share your concerns. We are actively working on an alternative solution using Azure Data Studio, a unified desktop tooling experience exclusively for Azure databases. In the meantime, you can continue to use the following options: [version 1.21.3 of Azure Storage Explorer](https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.21.3) which integrates with Azure Cosmos DB, the [Azure Portal](https://portal.azure.com/), [Azure Portal desktop app](https://portal.azure.com/App/Download) or the standalone [Azure Cosmos DB Explorer](https://docs.microsoft.com/en-us/azure/cosmos-db/data-explorer).

**Comment by Normannei** [comment]
I have now been using version 1.21.3 of Azure Storage explorer for several years. Azure Cosmos DB Explorer is still lacking features and very buggy. Azure Data Studio still does not support Cosmos DB for Tables beyond a simple free text query and raw JSON response.

It is now 2 years since this thread was last commented. Why not reintroduce Cosmos DB in Azure Storage Explorer so that I can upgrade to the latest version? Waiting more than 3 years for an alternative does not sound reasonable.
