### ISSUE TITLE
No red border displays for the value field when changing an existing property type to another in 'Add Entity' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5357]
**Storage Explorer Version**: 1.22.1
**Build Number**: 20220121.1
**Branch**: hotfix/1.22.1
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.6.1
**How Found**: Ad-hoc testing
**Regression From**: Previous release (1.21.3)
## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Add one entity which contains at least one custom property. as the below:
![image](https://user-images.githubusercontent.com/41351993/150491464-5da64c93-c87f-487b-88c6-39fe4767b829.png)

3. Click 'Add' -> Change the property type (Not contains 'String').
4. Check whether a red border displays for the value field.

## Expected Experience ##
A red border displays for the value field.
![image](https://user-images.githubusercontent.com/41351993/150492106-3a1a2e52-1881-47ae-a419-e2b74ce7a891.png)

## Actual Experience ##
No red border displays for the value field.
![image](https://user-images.githubusercontent.com/41351993/150491621-b341c9f9-32d6-46cc-8df7-afac27042fdb.png)

**Comment by craxal** [comment]
@v-xianya Since nothing has actually been entered in the field yet, I think this is preferable and more consistent with behavior in other dialogs; we shouldn't invalidate something unless the user has actually entered something into the field.
