### ISSUE TITLE
Unable to fetch child resources Azure Storage explorer

### ISSUE THREAD

**Issue by omkardanke** [microsoft/AzureStorageExplorer#5358]
I am trying to connect to Azure containers using the Azure Storage Explorer from a 'WIndows Virtual Machine'. I am encountering the following error consistently. I do not use any proxy

Unable to retrieve child resources.

Details:
{
"name": "FetchError",
"message": "request to https://zwestmptdatalab1.blob.core.windows.net/?comp=list&include=metadata failed, reason: tunneling socket could not be established, cause=Client network socket disconnected before secure TLS connection was established",
"stack": "FetchError: request to https://zwestmptdatalab1.blob.core.windows.net/?comp=list&include=metadata failed, reason: tunneling socket could not be established, cause=Client network socket disconnected before secure TLS connection was established\n at ClientRequest.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1483:11)\n at ClientRequest.emit (events.js:315:20)\n at ClientRequest.onError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tunnel\\lib\\tunnel.js:183:21)\n at Object.onceWrapper (events.js:422:26)\n at ClientRequest.emit (events.js:315:20)\n at TLSSocket.socketErrorListener (_http_client.js:469:9)\n at TLSSocket.emit (events.js:315:20)\n at emitErrorNT (internal/streams/destroy.js:106:8)\n at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n at processTicksAndRejections (internal/process/task_queues.js:80:21)",
"type": "system",
"errno": "ECONNRESET",
"code": "ECONNRESET"

**Comment by MRayermannMSFT** [comment]
@omkardanke can you give system proxy a try? Read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by MRayermannMSFT** [comment]
Closed due to lack of response. If you continue encountering this issue we recommend either opening an Azure Support ticket via the portal, or opening a new issue here.
