### ISSUE TITLE
can't access tennant, and I set up this storage account

### ISSUE THREAD

**Issue by ti611h** [microsoft/AzureStorageExplorer#5359]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.0

### Regression From

1.18.0

### Architecture

x64

### Platform

Windows

### Bug Description

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://gespeastus2devstatt02.file.core.windows.net/?comp=list failed, reason: tunneling socket could not be established, cause=write EPROTO 953551272:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:\n",
  "stack": "FetchError: request to https://gespeastus2devstatt02.file.core.windows.net/?comp=list failed, reason: tunneling socket could not be established, cause=write EPROTO 953551272:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:\n\n    at ClientRequest.<anonymous> (C:\\Users\\ti611h\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\index.js:2:103326)\n    at ClientRequest.emit (events.js:315:20)\n    at ClientRequest.onError (C:\\Users\\ti611h\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\index.js:2:572093)\n    at Object.onceWrapper (events.js:422:26)\n    at ClientRequest.emit (events.js:315:20)\n    at TLSSocket.socketErrorListener (_http_client.js:469:9)\n    at TLSSocket.emit (events.js:315:20)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
  "type": "system",
  "errno": "ECONNRESET",
  "code": "ECONNRESET"
}

### Steps to Reproduce

 launch explorer
select supscrption GESP 21326
goto account gespeastus2devstatt02

try to open blob.  

in azure portal I can see 3 folders.  patters, best practice, and concepts.

can't see these in the explorer

I created this storage account.

### Actual Experience

can't access blob data

### Expected Experience

see my blog data

**Comment by MRayermannMSFT** [comment]
@ti611h can you give system proxy a try? Read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by ti611h** [comment]
that did the trick.  Thank you!
