### ISSUE TITLE
Support for socks proxy

### ISSUE THREAD

**Issue by tleepa** [microsoft/AzureStorageExplorer#5366]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I would like to be able to connect to storage accounts via their private IP addresses. Because of some network configurations, I cannot do it from the machines in allowed networks.

### Desired Solution

Supporting socks (v5, with hostname) either in the application or as environment variables would be great, so I could use with e.g. SSH tunnels.

### Additional Context

Currently AzureStorageExplorer supports only http(s) proxy, setting *_proxy environment variables to e.g. 'socks5h://127.0.0.1:1080' does not work.

**Comment by MRayermannMSFT** [comment]
@tleepa can you give using system proxy setting a try? You can read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by tleepa** [comment]
I may have forgotten to mention, that I am using Storage Explorer on Linux - so AFAIK system proxy settings are the same as environment variables?

**Comment by MRayermannMSFT** [comment]
@tleepa are they? I think that would greatly depend on your distro. How have you configured the proxy for your distro?

**Comment by tleepa** [comment]
Well, I haven't. Because I do not need proxy for regular use. I would only need it for specific purposes, like this one :)

BTW, my setup is a bit complicated. I have Fedora with KDE as my desktop OS, but installed Storage Explorer in https://github.com/89luca89/distrobox, under Ubuntu 20.04.

**Comment by MRayermannMSFT** [comment]
@tleepa , interesting. Well can you at least give the system proxy setting a try? The name may make it seem pointless given the situation you are in, but I think it would be good to try...?

**Comment by tleepa** [comment]
I will try using system proxy settings, but I would need to do it in a VM (setting proxy globally on my system would mean I will not be able to do anything else ;)) and I currently do not have much time for it.

In the meantime, I have managed to work this around using privoxy: I have set ASE to use privoxy's as HTTP proxy and privoxy forwards traffic to my SOCKS proxy using [forwarding settings](https://www.privoxy.org/user-manual/config.html#FORWARDING).
Nice thing about this setup is that you can use patterns to forward matching URLs to different proxies :)

**Comment by tleepa** [comment]
Just to confirm:

I have configured system proxy settings in KDE:
![image](https://user-images.githubusercontent.com/7734919/152784245-790b8afe-58b7-4ccb-9b6e-ac9a6a7c2393.png)

and after setting StorageExplorer to 'use system proxy (preview)', it worked - all traffic was routed via my socks proxy tunnel and I could see blob storage content via storage account's private IP address.

PS. I have also managed to run ASE directly from my Fedora desktop, not from distrobox container.

**Comment by MRayermannMSFT** [comment]
Awesome. It sounds like you've found a variety of ways to get things working for you. So I'm going to close this issue.

**Comment by jonath92** [comment]
> I will try using system proxy settings, but I would need to do it in a VM (setting proxy globally on my system would mean I will not be able to do anything else ;)) and I currently do not have much time for it.

This is true. Setting system proxy is not a good option for daily usage. Please review the request
