### ISSUE TITLE
An extra scroll bar displays in the 'Shared Access Signature' dialog for one ADLS Gen2 blob container when timestamp validation error occurs

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5368]
**Storage Explorer Version:** 1.23.0-dev
**Build Number:** 20220124.2
**Branch:** main
**Platform/OS:** Windows 10
**Architecture:** ia32\x64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Right click the blob container -> Click 'Get Shared Access Signature...'.
3. Change the start time to make it is greater than the expire time.
4. There is an error message -> Check whether no extra scroll bar displays.

## Expected Experience ##
No extra scroll bar displays.

## Actual Experience ##
An extra scroll bar displays.
![image](https://user-images.githubusercontent.com/87792676/150956912-a807047d-67be-4b9b-90be-9e8d7a37a9ad.png)

## Additional Context ##

1. This issue doesn't reproduce for file shares/queues/tables.
2. This issue doesn't reproduce for normal blob containers.
3. This issue doesn't reproduce on Linux & Mac.
4. This issue doesn't reproduce in 1.21.3 because there is no error message in the dialog.

**Comment by v-xianya** [comment]
Verified this issue on build 20220511.2.
![image](https://user-images.githubusercontent.com/41351993/167800989-433dceba-08d8-4da1-90f0-3d2f788c1053.png)
