### ISSUE TITLE
Detaching SAS service connections sometimes results in errors

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#537]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows 10
**Architecture**: ia32
**Regression From**: 1.3.1

#### Steps to Reproduce: ####
1. Attach several blob containers via SAS URI.
2. Refresh the **Local & Attached** > **Storage Accounts** > **(SAS-Attached Services)** > **Blob Containers** node.
3. Attempt to detach each connection made in step 1.

#### Expected Experience: ####
Detachment happens smoothly for each node.

#### Actual Experience: ####
An error occurs after attaching. The **Blob Containers** node no longer displays children. Clicking the **Load more** button resurfaces the same error.

![image](https://user-images.githubusercontent.com/3473026/43610922-7043f286-965c-11e8-8dda-adefbe8b4c6f.png)

#### Workaround: ####
Just refresh the **Blob Containers** node, and all the children appear normally.

**Comment by MRayermannMSFT** [comment]
I'm pretty sure we fixed this, and neither Jason nor I have seen it recently. I'll re verify today and close if it doesn't repro.

**Comment by MRayermannMSFT** [comment]
Unable to reproduce.
