### ISSUE TITLE
An error info bar pops up when opening one storage account/blob container/file share/queue/table using its direct link

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5374]
**Storage Explorer Version**: 1.23.0-dev
**Build Number**: 20220125.10
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.6.1
**How Found**: From running test case
**Regression From**: Previous release (1.22.0)

## Steps to Reproduce ##
1. Right click one storage account -> Click 'Copy Direct Link to Account'.
2. Paste the direct link to the Edge browser -> Open the link -> Storage Explorer is opened.
3. Check whether navigates to the storage account and no error pops up.

## Expected Experience ##
Navigate to the storage account.

## Actual Experience ##
An error info bar pops up indicating 'Cannot find the specified subscription for this resource. Please sign in or attach the resource using SAS or account name and key.'
![image](https://user-images.githubusercontent.com/41351993/151127820-93048f89-8dc5-4dfe-9980-383577a25f7a.png)

## Additional Context ##
Here is the record:
![issueyan](https://user-images.githubusercontent.com/41351993/151129944-296968d2-87d4-4480-9a38-1a61a5813d63.gif)

**Comment by MRayermannMSFT** [comment]
@v-xianya I'm having a hard time repro'ing this. I've added some additional logging to this code path. Can you increase log level to `debug`, repro, and then share your logs with me? Thanks!

**Comment by v-xianya** [comment]
@MRayermannMSFT 
Hi Matthew, Here is the logs [2022-01-26_185745.zip](https://github.com/microsoft/AzureStorageExplorer/files/7947233/2022-01-26_185745.zip)

**Comment by MRayermannMSFT** [comment]
@v-xianya It looks like your log level was set to `verbose`, can you do it again at level `debug`? I have some things that only log at `debug`, which is the highest logging level we have. Sorry about that!

**Comment by v-xianya** [comment]
@MRayermannMSFT Hi Matthew, Here is the logs folder, I set the log level to 'Debug'. 
[2022-01-27_224158.zip](https://github.com/microsoft/AzureStorageExplorer/files/7956384/2022-01-27_224158.zip)

BTW, what do you mean the log level 'verbose', it seems no 'verbose' option in the log level. 😲
![image](https://user-images.githubusercontent.com/41351993/151501198-b7222795-d8c3-4c25-928a-94517d091620.png)

**Comment by MRayermannMSFT** [comment]
@v-xianya, that is the log level for AzCopy. The storage explorer log level is different. To set that log level you have to set the `STG_EX_LOG_LEVEL` to the string matching the log level you want, in this case `debug`.

**Comment by v-xianya** [comment]
@MRayermannMSFT Got it. thank you for the updates! Here is the log:
[2022-01-28_181718.zip](https://github.com/microsoft/AzureStorageExplorer/files/7962807/2022-01-28_181718.zip)

**Comment by v-xianya** [comment]
Verified this issue on the build 20220217.2. Fixed.
