### ISSUE TITLE
No 'Tables' option displays on the filter panel after clicking Filter button in the search box

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5375]
**Storage Explorer Version:** 1.23.0-dev
**Build Number:** 20220125.10
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.6.1
**How Found:** From running test case
**Regression From:** Previous release (1.22.0)

## Steps to Reproduce ##

1. Launch Storage Explorer.
2. Click Filter button in the search box.
3. Check whether the 'Tables' option displays on the filter panel.

## Expected Experience ##
The 'Tables' option displays on the filter panel.
![image](https://user-images.githubusercontent.com/87792676/151135117-2bb72490-832a-4dbc-a351-0c77c7cc2b38.png)

## Actual Experience ##
No 'Tables' option displays on the filter panel.
![image](https://user-images.githubusercontent.com/87792676/151131631-e95c1214-fcf4-46ca-bf4a-367584e2ffb4.png)

**Comment by craxal** [comment]
This will be fixed once table nodes have been migrated to the extension.

**Comment by v-xianya** [comment]
Verified this issue on the build 20220127.4. Fixed.
