### ISSUE TITLE
The 'Enable Soft Delete' button is selected by default on the 'Delete' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5376]
**Storage Explorer Version**: 1.23.0-dev
**Build Number**: 20220125.10
**Branch**: main
**Platform/OS**: MacOS Big Sur 11.6.1
**How Found**: From running test case
**Regression From**: Previous release (1.22.0)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers. (Make sure the soft delete is disabled)
2. Create a blob container -> Upload one blob -> Click 'Delete'.
3. Check whether the 'Yes' button is selected by default.

## Expected Experience ##
The 'Yes' button is selected by default.

## Actual Experience ##
The 'Enable Soft Delete' button is selected by default.
![image](https://user-images.githubusercontent.com/41351993/151141655-e4c54c6f-06e1-487e-8a67-57de9f390830.png)

## Additional Context ##
This issue doesn't reproduce on Windows 10/Linux Ubuntu 20.04.

Duplicate issue: #5380
Related issue: #5377

**Comment by MRayermannMSFT** [comment]
Make sure #5380 is also fixed, but try not to disrupt the behavior for other dialogs as described in #5377

**Comment by craxal** [comment]
Mitigated temporarily by immediately showing the dialog window. This prevents a race condition between showing the window and setting focus on a control. The OS won't actually give focus to an invisible control, so we don't bother hiding the window at all.

In the future, this can be fixed by either moving the code that sets focus to a later part of the window lifecycle or by adding an obscuring element that can be cleared when initialization completes.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220216.1. Fixed.

**Comment by v-xianya** [comment]
@craxal Hi Craig, Could you help to take a look at the below issue?

On MacOS with build main/20220216.1.
The content in the dialog doesn't display at the same time with the dialog window. Here is the record:

https://user-images.githubusercontent.com/41351993/154234900-906c4305-2785-42cf-8bd9-79cff05bc8d2.mov

**Comment by craxal** [comment]
@v-xianya Yes, that is expected. It's a small compromise we had to make in order to get focus onto the default button. This should only be noticeable on macOS.
