### ISSUE TITLE
The value of the property 'Name' is focused when opening one item's Properties dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5377]
**Storage Explorer Version**: 1.23.0-dev
**Build Number**: 20220125.10
**Branch**: main
**Platform/OS**: MacOS Big Sur 11.6.1
**How Found**: From running test case
**Regression From**: Previous release (1.22.0)

## Bug Descriptions ##
1. The value of the property 'Name' is focused on the 'Properties' dialog.
1. The value of the 'Access Policy' is focused on 'Shared Access Signature' dialog.
2. The link 'Learn more about access tiers' is focused on the 'Update Access Tier' dialog.

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers. 
2. Right click one blob container -> Click 'Properties...'.
3. Check whether no item is focused on the dialog.

## Expected Experience ##
No item is focused on the dialog.

## Actual Experience ##
The value of the property 'Name' is focused.
![image](https://user-images.githubusercontent.com/41351993/151143878-7c4c984e-b72d-4fb5-b525-ea7e0521e2ac.png)

## Additional Context ##
1. This issue also reproduces for 'Shared Access Signature' dialog.
![image](https://user-images.githubusercontent.com/41351993/151154144-3f0635d0-0e09-4c74-86c8-ac5b439b57e4.png)

2. This issue also reproduces for 'Update Access Tier' dialog.
![image](https://user-images.githubusercontent.com/41351993/151153999-b83a2560-357a-472a-85fe-8b87c0349446.png)

**Comment by craxal** [comment]
@MRayermannMSFT @JasonYeMSFT I thought we wanted the first focusable element to get focus in each dialog. Is dialog accessibility adversely affected by this?
