### ISSUE TITLE
Unable to Retrieve Child Resources

### ISSUE THREAD

**Issue by dchavez3** [microsoft/AzureStorageExplorer#5378]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.0

### Regression From

1.18.0

### Architecture

x64

### Storage Explorer Build Number

Unknown

### Platform

Windows

### Bug Description

Unable to retrieve child resources.

Details:
["RestError:﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.\nRequestId:873fdddb-b01e-0053-5ace-125b58000000\nTime:2022-01-26T16:06:47.7530530Z</Message></Error>"]

### Steps to Reproduce

1. Launch Azure Storage Explorer
2. . Select blob container
3. . Receive the following error:
Unable to retrieve child resources.

Details:
["RestError:﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.\nRequestId:873fdddb-b01e-0053-5ace-125b58000000\nTime:2022-01-26T16:06:47.7530530Z</Message></Error>"]

### Actual Experience

Unable to retrieve child resources.

Details:
["RestError:﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.\nRequestId:873fdddb-b01e-0053-5ace-125b58000000\nTime:2022-01-26T16:06:47.7530530Z</Message></Error>"]

**Comment by craxal** [comment]
@dchavez3 A few questions for you:
1. Can you update to the latest version of Storage Explorer available? 1.19.0 is almost a year old.
2. How are you connecting to your blob container? Are you signing in, attaching via sign in, or attaching using a SAS URL?
   - If you are signing in or attaching via sign in, do you have the [necessary RBAC permissions](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#azure-rbac-permissions-issues) to access the blob containers in the storage account?
   - If you are [attaching using a SAS URL](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#issues-with-a-shared-access-signature-url), is the SAS token expired? Does the token have the necessary permissions? Is the token based on a shared access policy?
3. Are you operating behind a proxy server?

**Comment by MRayermannMSFT** [comment]
Closed due to lack of response. If you continue encountering this issue we recommend either opening an Azure Support ticket via the portal, or opening a new issue here.
