### ISSUE TITLE
5 Gb Files Freezes Storage Explorer

### ISSUE THREAD

**Issue by ricardoharripaul** [microsoft/AzureStorageExplorer#538]
**Storage Explorer Version**: 1.3.1
**OS/Platform**: Windows 7
**Architexture**: ia32
**Regression From**: Stopped working for last three versions of Storage Explorer

#### Steps to Reproduce: ####
1. Trying downloading a 5 Gb file
2.  I am trying to download from the Azure cloud a 5 Gb genomics bam file through storage explorer and it will run for a bit and then freeze and crash

#### Expected Experience: ####
It should download a single 5Gb file without freezing but I would like to queue more files than this

#### Actual Experience: ####
It stops and freezes and then crashes.  Sometimes a few Mb download but it then freezes

**Comment by craxal** [comment]
Are you downloading from a blob container or a file share? Have you signed into your Azure account, or are you using a SAS token to connect? Do you have any network settings that might be causing issues?

**Comment by ricardoharripaul** [comment]
Hi Craig,

I am downloading from the blob container and not a file share.  I am logged
into the Azure account.  There are no network issues because I can download
this from my browser Azure.

Ricardo

**Comment by MRayermannMSFT** [comment]
@ricardoharripaul about 8 months ago we switched to using AzCopy with Storage Explorer. Please download our latest version from https://storageexplorer.com and let us know if you're still having problems. Thanks!

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response.
