### ISSUE TITLE
Can't open Storage Explorer again if it was closed by clicking 'Yes' on the 'Warn before exit' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5381]
**Storage Explorer Version**: 1.23.0-dev
**Build Number**: 20220127.4
**Branch**: main
**Platform/OS**: MacOS Big Sur 11.6.1
**How Found**: From running test case
**Regression From**: Previous release (1.22.0)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Open one blob container -> Upload a large folder to it.
3. Quit Storage Explorer when the transfer activity is not completed.
4. There is a dialog indicating whether to quit -> Click 'Yes'.
5. Open Storage Explorer again -> Check whether succeeds to open Storage Explorer.

## Expected Experience ##
Succeed to open Storage Explorer.

## Actual Experience ##
Can't open Storage Explorer.

## Additional Context ##
1. Nothing happens when trying to open any folder on the MacOS.
2. The Storage Explorer displays blank when reloading Storage Explorer by clicking 'Yes' on the warn before exit dialog.

**Comment by MRayermannMSFT** [comment]
@v-xianya I was unable to repro, but I went ahead and took a guess at what could be happening, an added some code to help prevent it. Can you:
1. Try to repro this again with tonight's build, with logging level to `debug` (not `verbose`)
2. If you do repro then share the two newest log folders in the log directory (may be easier to just delete all log folders before you try to repro, and then after you repro, just share everything in the logs folder)

Thanks!

**Comment by v-xianya** [comment]
@MRayermannMSFT Hi Matthew, thank you for the prompt response!
Verified this issue on the latest build 20220127.17. Not reproduce. so close it.
