### ISSUE TITLE
The file share snapshot doesn't automatically disappear in the split tab after deleting the file share snapshot in the original tab

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5385]
**Storage Explorer Version:** 1.23.0-dev
**Build Number:** 20220127.17
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.6.1
**How Found:** Ad-hoc testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> File Shares.
2. Create a file share -> Right click the file share -> Click 'Create Snapshot'.
3. Go to the file share explorer -> Click ‘View Share Snapshots'.
4. Right click the file share tab -> Click 'Split'.
5. Delete the file share snapshot in the original tab.
6. Check whether the snapshot automatically disappears in the split tab.

## Expected Experience ##
The snapshot automatically disappears.

## Actual Experience ##
The snapshot doesn't automatically disappear.
![image](https://user-images.githubusercontent.com/87792676/151506994-b3147731-5bb1-4098-b22a-bff8adc7da47.png)

## Additional Context ##
The snapshot disappears after manually refreshing.

**Comment by JasonYeMSFT** [comment]
Our code manually reloads the data table where the snapshot is deleted instead of sending a refresh event to all the matching explorers. We should move to refreshing all matching explorers instead.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220904.1. Fixed. So, we are going to close it.
