### ISSUE TITLE
Error connecting to blob storage container 

### ISSUE THREAD

**Issue by JLente** [microsoft/AzureStorageExplorer#5389]
trying to connect and receiving the following error.   can see all is available through the console but cannot get Storage Explorer to connect.   First occurance of this issue at 4:00pm Mountain time   1/28/2022...  any insight appreciated

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://btfaentwestgenstorage.blob.core.windows.net/?comp=list&include=metadata failed, reason: connect ETIMEDOUT 10.15.229.228:443",
  "stack": "FetchError: request to https://btfaentwestgenstorage.blob.core.windows.net/?comp=list&include=metadata failed, reason: connect ETIMEDOUT 10.15.229.228:443\n    at ClientRequest.<anonymous> (C:\\Users\\jlente\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1483:11)\n    at ClientRequest.emit (events.js:315:20)\n    at TLSSocket.socketErrorListener (_http_client.js:469:9)\n    at TLSSocket.emit (events.js:315:20)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
  "type": "system",
  "errno": "ETIMEDOUT",
  "code": "ETIMEDOUT"
}

**Comment by MRayermannMSFT** [comment]
@Jlente, first things first, can you give using system proxy setting a try? You can read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview
