### ISSUE TITLE
Default Conflict Resolution isn't set from start

### ISSUE THREAD

**Issue by jim-jezioranski** [microsoft/AzureStorageExplorer#539]
**Storage Explorer Version**:
**Platform/OS Version**: Windows Server 2012 R2 (win2k12 r2)
**Architecture**:  VM on vmware - Xeon CPU E5-2670 2.6GHz
**Regression From**: 
#### Steps to Reproduce: ####
1. Drag and Drop a folder onto ASE

#### Expected Experience: ####
To be asked what to do with conflicts OR to allow a global setting of conflict resolution (overwrite, skip etc).

Even better would be to have a resume prior copy feature as this is primarily when this issue arises i.e. after a lockup and you have to restart the copy but don't want to have to recopy 40 GB of data

#### Actual Experience: ####
Copy starts and immediately failures start piling up. You need to quickly click on conflict resolution mode and select a mode. Often, this stops progress on transfers.

**Comment by craxal** [comment]
If I understand the details correctly, you're running Storage Explorer in a VM running on Windows Server? That can make network connections complicated.

- What version of Storage Explorer are you running?
- Are you uploading from a local FS to blob storage or a file share?
- Have you tried other operations to make sure they work?
- Does this work for smaller operations, such as for smaller or fewer files?
- What if you start the upload from the toolbar instead of dragging and dropping?

**Comment by jim-jezioranski** [comment]
ASE v 1.3.1 is used. The VM has mounted network storage (local NAS) and we are copying from there to ASE folder (file share) storage. It has worked for smaller copies. 5/6 copies have worked fine. All copies were folders containing 5000 folders and 10000+files in those folders. The one that fails is far larger than the others. The 5 that worked were 9-40GB and the failing one is 270GB. 

On my 3rd attempt with this, it is still running but having to answer questions during the process is very undesirable as you want it to run unattended. It asks about retries and conflicts (Auto-resolve behavior). If I could set these globally prior to transfer ti would run unattended. I realize I can set Auto-resolve behavior once the copy has started but AES seems to have issues when it has conflicts before you set this. So, when I have transferred 30GB and it fails and locks, I have to start from the beginning because it stalls if I try to restart and set the Auto-resolve behavior to Skip.

I tried the toolbar upload and it works for small new uploads but it had the same result with a restart upload - possibly even worked worse. Even if the setting wasn't globa - if you could select the Auto-resolve behavior on the upload panel where you select the folder (from toolbar) - that would be an improvement.

**Comment by craxal** [comment]
I agree we can add a default conflict resolution option before the operation starts. We'll note that going forward.

Just to be clear, does setting the auto-conflict resolution work?

Also, I still don't know what your source/destination environments are. We've made some performance improvements for Blob downloads and uploads but we're still working on File shares. Are you copying Blob&rarr;Blob? Blob&rarr;File? Local&rarr;Blob? File&rarr;Local? Knowing exactly what you're trying to do will help us improve the right components.

**Comment by jim-jezioranski** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  I'm going to file shares on Azure. The auto settings work but if enough errors kick in before you set it, it stalls                                                                                                                                                                        Sent from my BlackBerry - the most secure mobile device - via the Rogers Network                                                                                                                                                                           From: notifications@github.comSent: August 3, 2018 2:05 PMTo: AzureStorageExplorer@noreply.github.comReply-to: reply@reply.github.comCc: jimj@otecsolutions.com; author@noreply.github.comSubject: Re: [Microsoft/AzureStorageExplorer] Default Conflict Resolution isn't set from start (#539)  I agree we can add a default conflict resolution option before the operation starts. We'll note that going forward.
Just to be clear, does setting the auto-conflict resolution work?
Also, I still don't know what your source/destination environments are. We've made some performance improvements for Blob downloads and uploads but we're still working on File shares. Are you copying Blob→Blob? Blob→File? Local→Blob? File→Local? Knowing exactly what you're trying to do will help us improve the right components.

**Comment by jim-jezioranski** [comment]
To further clarify, we were migrating on premises servers to Azure, so a pretty typical and desirable circumstance for Azure. The on premise servers are w3k12 VM in a vmware environment. The storage is on a NetApp NAS which we mounted on one of the servers. We used ASE to drag the folders to an Azure File Share (not Blob)

**Comment by craxal** [comment]
If you're working on a migration project, I would consider some of the suggestions I made in #540. Either use the Connect VM button to get a command for mounting the file share to a drive letter or use AzCopy to copy your files using the command line. Although we're constantly trying to improve performance in Storage Explorer, you may find these options easier and more performant.

**Comment by JasonYeMSFT** [comment]
@jim-jezioranski We have designed a different experience together with the AzCopy integration for data transfers for blobs in our recent releases. If there is conflict, we would pause on those files with conflicts and prompt a dialog for you to choose the resolution type. All files without conflicts will be transferred in the background. In our next release v1.13.0, the same experience will be introduced to file share as well so that you won't need to answer the awkward "Auto-resolve behavior" during the upload/download/copy&paste.

Please let us know then if you have any issues with the new experience.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you aren't happy with the conflict experience in 1.13. Thanks.
