### ISSUE TITLE
Configure CORS Settings - Error

### ISSUE THREAD

**Issue by vmiokovic** [microsoft/AzureStorageExplorer#5391]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.22.1

### Architecture

x64

### Platform

Windows

### Bug Description

Hi,

When I try to enter Max Age in Configure CORS Settings whatever I do be it that I manually enter the number or use the numeric input with arrows I always get this error:

**"blobServiceProperties.Cors.MaxAgeInSeconds with value 86400 must be of type number."**

It only works if I the value for this input is 5 which is the default value I presume?

Tried the same thing on three different versions of Storage Explorer with same results.

### Steps to Reproduce

1. Launch Storage Explorer
2. Open up Configure CORS Settings
3. Try to set Max Age

### Actual Experience

The same as I provided in the Bug Description.

**Comment by MRayermannMSFT** [comment]
Thanks for reporting this. Unsure how this was missed for so long? The fix will get shipped in 1.23
