### ISSUE TITLE
Error when trying to add boolean property since version 1.22.0

### ISSUE THREAD

**Issue by alexastall** [microsoft/AzureStorageExplorer#5396]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.22.1

### Regression From

1.21.3

### Architecture

x64

### Storage Explorer Build Number

20220122.3

### Platform

All

### OS Version

Windows 10 & MacOS 12.1

### Bug Description

Get the following error when trying to add / amend a boolean property on a table:

Error adding table entity:
{"odata.error":
{"code": "Invalidinput", " message
":"lang":"en-US" "value":"An
error occurred while processing
this request.
InRequestld:d2f45f32-
e2a1-4a79-85ab-3a2af1f6c62b|
nTime:2022-01-31T23:41:16.385Z"}}}

<img width="695" alt="Screenshot 2022-01-31 at 23 48 22" src="https://user-images.githubusercontent.com/2225638/151891942-c2af0cc9-114a-4bb6-beb0-a8891806d5f5.png">

<img width="268" alt="Screenshot 2022-01-31 at 23 41 39" src="https://user-images.githubusercontent.com/2225638/151891594-c46ac683-9068-4033-8c8a-33c320028c16.png">

### Steps to Reproduce

1. Launch Storage Explorer
2. Expand a table container
3. Either create a new or edit and existing table
4. Add or edit an existing Boolean property
5. The error occurs

### Actual Experience

An error is thrown when trying to save changes to the table entity

### Expected Experience

Table entity is updated / created with Boolean property

**Comment by craxal** [comment]
@alexastall Can you share the `se-table-extension` log file?

**Comment by alexastall** [comment]
> @alexastall Can you share the `se-table-extension` log file?

Where can I find this file on Mac?

Thanks

**Comment by alexastall** [comment]
> @alexastall Can you share the `se-table-extension` log file?
[2022-02-02_105545_se-table-extension_61596.log](https://github.com/microsoft/AzureStorageExplorer/files/7985844/2022-02-02_105545_se-table-extension_61596.log)

**Comment by craxal** [comment]
@alexastall From the log, it looks like you're connecting to a storage emulator, correct? If that's true, this is an issue we are already aware of (#5299).

Does this issue still reproduce if you connect to a table in Azure?

**Comment by alexastall** [comment]
Agreed, this is only an issue on storage emulator. I didn't see the other issue prior to raising this. Happy to close and await fix for (#5299)

Thanks for your help!
