### ISSUE TITLE
Cannot Expand Tables in Storage Accounts/Emulator

### ISSUE THREAD

**Issue by vicrxl** [microsoft/AzureStorageExplorer#5398]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.22.1

### Architecture

x64

### Storage Explorer Build Number

20220122.3

### Platform

macOS

### Bug Description

Tables will not expand. It eventually times out with "Connection Refused."

Blob Containers and Queues work as expected.

### Steps to Reproduce

1. Launch Storage Explorer.
2. Expand Tables.

### Actual Experience

It just spins and then provides a "Connection Refused" error.

### Expected Experience

I expect Tables to expand.

**Comment by MRayermannMSFT** [comment]
@vicrxl 
- Did you start your emulator (it sounds like probably yes, but just double checking :) )?
- What emulator are you using, and what version of that emulator?
- Are you using the default emulator node, or did you create your own emulator connection? If you created your own, can you make sure that the port number is correct for the connection.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
