### ISSUE TITLE
The header of 'Actions/Properties' Panel isn't themed with Dark/HC-Black theme

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#54]
**Storage Explorer Version:** master/20180419.2

**OS Version:** Windows 10/Mac/Linux

**Regression:** Works well on 1.0.0 release

**Steps to Reproduce:**

1. Launch Storage Explorer and expand Storage Accounts. 
2. Change the theme to Dark/HC-Black.
3. Check the 'Actions/Properties' Panel.

**Expected Experience:**
The header of 'Actions/Properties' Panel is themed.

**Actual Experience:**
The header of 'Actions/Properties' Panel isn't themed.
![header](https://user-images.githubusercontent.com/34729022/39039724-8fcd5d56-4475-11e8-9a36-64bd985488fb.png)

**Comment by craxal** [comment]
Unable to reproduce on current master. Please check again and reopen the issue if it reproduces for you.
