### ISSUE TITLE
Endless number of processes launched if you choose 'Install and close' and there are pending operations

### ISSUE THREAD

**Issue by ShippyMSFT** [microsoft/AzureStorageExplorer#5403]
Running version 1.21.3. I got a notification about a new version available so I told it to 'Install on close'. When I closed the app I had forgotten that I had a large transfer still in progress. It popped up a dialog asking if I was sure I wanted to exit because of the operations in progress, but then it also tried to launch the upgrade which prompted me with a UAC dialog. Then it started doing this again... and again... and again. Non-stop confirmation dialogs along with attempted upgrade launches with associated UAC dialogs. Machine started running out of resources due to the number of processes and I was forced to completely sign out and lose my work in progress to get it to stop.

**Comment by MRayermannMSFT** [comment]
@ShippyMSFT thanks for reporting this. We'll take a look.

**Comment by MRayermannMSFT** [comment]
@ShippyMSFT I checked in a fix for this. Thanks for reporting the issue.
