### ISSUE TITLE
Can't connect to Storage container

### ISSUE THREAD

**Issue by hollidayh** [microsoft/AzureStorageExplorer#5404]
Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://dsvmstorage.file.core.usgovcloudapi.net/?sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupx&se=2023-01-01T02:40:25Z&st=2022-02-04T18:40:25Z&spr=https&SAS Token Redacted&comp=list failed, reason: self signed certificate in certificate chain",
  "stack": "FetchError: request to https://dsvmstorage.file.core.usgovcloudapi.net/?sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupx&se=2023-01-01T02:40:25Z&st=2022-02-04T18:40:25Z&spr=https&SAS Token Redacted&comp=list failed, reason: self signed certificate in certificate chain\n    at ClientRequest.<anonymous> (C:\\tools\\azure\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\index.js:2:103326)\n    at ClientRequest.emit (events.js:315:20)\n    at TLSSocket.socketErrorListener (_http_client.js:469:9)\n    at TLSSocket.emit (events.js:315:20)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
  "type": "system",
  "errno": "SELF_SIGNED_CERT_IN_CHAIN",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}

I updated, and it was pulling in my @army.mil credentials, had to re-authorize with @armyfc.onmicrosoft.com credentials, generated a SAS token, connects, but throws this error when I click on the "blob Storage" or "File Shares" to tree it out

**Comment by MRayermannMSFT** [comment]
@hollidayh can you give using system proxy setting a try? You can read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by hollidayh** [comment]
enabling the system proxy fixed the issue.  Thanks!
