### ISSUE TITLE
Incorrect text encoding while adding a message to Azure Storage Queue

### ISSUE THREAD

**Issue by AshishCMSingh** [microsoft/AzureStorageExplorer#5408]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.22.1

### Architecture

x64

### Storage Explorer Build Number

20220122.3

### Platform

macOS

### OS Version

macOS Monterey 12.1 (21C52)

### Bug Description

Wrong Encoding while Adding Message to Azure Storage Queue

If you select `UTF8` then the message will be added in a different encoding (not as Base64). If you select `Base64` then the message will be added as in UTF8.

<img width="498" alt="Wrong Encoding" src="https://user-images.githubusercontent.com/13658780/152838371-0a5ce887-f580-4ea9-9303-75f3f929aff8.png">

<img width="498" alt="image" src="https://user-images.githubusercontent.com/13658780/152839163-30667207-8808-4e5b-ba4d-0217aab0d748.png">

<img width="345" alt="image" src="https://user-images.githubusercontent.com/13658780/152839017-88acf086-8cb3-47eb-a479-844ca573e064.png">

### Steps to Reproduce

1. Launch Storage Explorer
2. Expand a Queues node.
3. Create Queue and select it.
4. Add 2 Messages (+) one with `Base64` encoding and another as `UTF8` 
5. Type a message that says `TEST`
6. Select `OK`
7. View the Message you added.
8. Verify the message text while toggling the encoding options.

### Actual Experience

Message Encoding should be correct.

**Comment by MRayermannMSFT** [comment]
@AshishCMSingh as far as I can tell everything is working fine.

By default, Storage Explorer assumes messages are Base64 encoded. While we can discuss the merits of that, that is how things have been for a long while now. Anyways, that assumption means that the message text of queue items are base64 decoded in the data table. And if you base64 decode "TEST" you get "LD " (the last character I am unable to paste properly). If you open the message and change the encoding type to be UTF-8 you should see "TEST" appear. Let me know if you have any further questions.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
