### ISSUE TITLE
Browsing subfolder after search by prefix doesn't work

### ISSUE THREAD

**Issue by hengyiliu** [microsoft/AzureStorageExplorer#541]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows 10
**Architecture**: ia32
**Regression From**: It used to work in 0.X release (IIRC).

#### Steps to Reproduce: ####
1. I have a lot of blobs under the path /folder1/folder2/folder3/
2. In Search by prefix box, enter folder1/folder2/folder3
3. It listed "folder3" in the list pane.
4. Double click on folder3, and it shows "no data available" because it goes to "container/folder3".

#### Expected Experience: ####
When I click on an item from the result of search by prefix, it should go to the full path of that item.

#### Actual Experience: ####
It shows "No data available in this blob container" because it doesn't use the full path.

**Comment by ppanyukov** [comment]
Yep, the folder browsing is broken *again*.  Now with this specific issue.  Affects OS X too.

I appreciate the explorer is a sophisticated app, but this is core functionality, would be nice if this kept working with every release.
