### ISSUE TITLE
Miss the table name in the URL of one table

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5410]
**Storage Explorer Version**: 1.23.0-dev
**Build Number**: 20220208.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**How Found**: From running test case
**Regression From**: Previous release (1.22.1)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Select one table -> Observe its URL in the Properties panel.
3. Check whether the URL displays completely.

## Expected Experience ##
The URL displays completely.
![image](https://user-images.githubusercontent.com/41351993/152941008-368f5a1c-498f-4290-ba2e-8e102ba52b77.png)

## Actual Experience ##
Miss the table name in the URL.
![image](https://user-images.githubusercontent.com/41351993/152941002-df9b7c2f-286f-4fd9-9d03-b993b99cbc3d.png)

## Additional Context ##
1. This issue also reproduces for one SAS attached table.
2. This issue also reproduces for one emulator table.

**Comment by v-xianya** [comment]
This issue still reproduces on the new build 20220210.3. Will verify on a newer build.

**Comment by craxal** [comment]
This should be fixed now that we've merged a new version of the table extension.

**Comment by v-xianya** [comment]
Verified on the build main 20220211.3. Fixed.
