### ISSUE TITLE
There is a successful activity log when creating one table using an existing table name

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5411]
**Storage Explorer Version**: 1.23.0-dev
**Build Number**: 20220208.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**How Found**: From running test case
**Regression From**: Previous release (1.22.1)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a new table with a valid name 'table'.
3. Create another table with the name 'table'.
4. Check whether there is a failed activity log.

## Expected Experience ##
There is a failed activity log.
![image](https://user-images.githubusercontent.com/41351993/152941903-8dc65998-3da0-458c-9412-3f00fe12ebd0.png)

## Actual Experience ##
There is a successful activity log.
![image](https://user-images.githubusercontent.com/41351993/152941678-723c428a-0e30-42a6-95be-f7d1ec767cf7.png)

**Comment by v-xianya** [comment]
This issue still reproduces on the new build 20220210.3. Will verify on a newer build.

**Comment by craxal** [comment]
This should be fixed now that we've merged a new version of the table extension.
