### ISSUE TITLE
The entity disappears when deleting one entity in an attached table with 'Query' permission which has more than one entity

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5412]
**Storage Explorer Version:** 1.23.0-dev
**Build Number:** 20220208.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**How Found:** Ad-hoc testing
**Regression From:** Previous release (1.21.3)

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create a Table -> Add two entities.
3. Right click the table-> Click 'Manage Access Policies...'.
3. Add one access policy with 'Query' permission -> Generate a SAS URL via the access policy.
4. Attach the table via the SAS URL.
5. Switch to the attached table -> Delete one entity.
6. Check whether the entity doesn't disappear.

## Expected Experience ##
The entity doesn't disappear. 

## Actual Experience ##
The entity disappears.

## Additional Context ##

1. This issue doesn't reproduce when deleting more than one entity.
2. The entity appears after manually refreshing.

**Comment by v-xianya** [comment]
This issue still reproduces on the new build 20220210.3. Will verify on the newer build.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220210.8. Fixed. So close it.
