### ISSUE TITLE
The table's tab is not closed when deleting the table

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5413]
**Storage Explorer Version**: 1.23.0-dev
**Build Number**: 20220208.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**How Found**: From running test case
**Regression From**: Previous release (1.22.1)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a new table -> The table's tab auto opens -> Delete the table.
3. Check whether the opened tab is closed.

## Expected Experience ##
The tab is closed.

## Actual Experience ##
The tab is not closed.

**Comment by v-xianya** [comment]
This issue still reproduces on the new build 20220210.3. Will verify on the newer build.

**Comment by craxal** [comment]
Should be fixed now that we've merged a new version of the extension.
