### ISSUE TITLE
Quick Access file share node doesn't display as broken when removing the Azure account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5414]
**Storage Explorer Version**: 1.23.0-dev
**Build Number**: 20220208.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**Architecture**: ia32\x64
**How Found**: From running test cases
**Regression From**: Previous release (1.22.1)

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Select one file share -> Add it to quick access.
3. Go to 'ACCOUNT MANAGEMENT' panel -> Remove the account.
4. Go to 'EXPLORER' panel -> Check whether the Quick Access file share displays as broken.

## Expected Experience ##
The Quick Access file share displays as broken.

## Actual Experience ##
The Quick Access file share displays well.

## Additional Context ##
Similar issue：[5069](https://github.com/microsoft/AzureStorageExplorer/issues/5069)

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220212.2. Fixed. So close it.

**Comment by MRayermannMSFT** [comment]
@v-kellyluo I merged a fix for this. Please note that any file shares put into quick access during the 1.23 development cycle may still not be broken. That is expected.

**Comment by v-xianya** [comment]
@MRayermannMSFT 
Thank you for the update. 
Verified this issue on today's build 20220216.1. Fixed.
