### ISSUE TITLE
The blob snapshot doesn't auto display in the split tab after creating a snapshot in the original tab

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5415]
**Storage Explorer Version:** 1.23.0-dev
**Build Number:** 20220208.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.0.1
**Architecture:** ia32/x64
**How Found:** Ad-hoc testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload a blob.
3. Right click the blob -> Click 'Manage History -> Manage Snapshots'.
4. Right click the blob container tab -> Click 'Split'.
5. Go to the original tab -> Right click the blob -> Click 'Create Snapshot'.
6. Check whether the snapshot auto displays in the split tab.

## Expected Experience ##
 The snapshot auto displays.

## Actual Experience ##
 The snapshot doesn't auto display.
![image](https://user-images.githubusercontent.com/87792676/152958105-a18aaea6-c34a-4a4a-996f-40d4d759ddea.png)

## Additional Context ##

1. This issue doesn't reproduce when deleting snapshots.
2. This issue doesn't reproduce for file shares.
3. The snapshot displays after manually refreshing.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220315.1. Fixed.
