### ISSUE TITLE
Azure Explorer and Azure Portal blobs don't sort correctly with "Last Modified"

### ISSUE THREAD

**Issue by colindesaulniers** [microsoft/AzureStorageExplorer#5417]
![image](https://user-images.githubusercontent.com/8417166/153005339-abc6c52b-4ce5-4988-88e9-ce14e3f6da5c.png)

I run backups every day (Full backup on the first of each month and incremental backups every other day)

When I need to check something that failed or just check to make sure things are working correctly, it's impossible to find the information I need because I can't correctly sort the dates. I can't change the name structure of how the files are saved, so I need to rely on the Last Modified column which doesn't sort correctly.

I THINK, it's sorting by day, month, year instead of month, day, year. I say this because I always see all my Full backups from the first of each month first.

What is shown in the screenshot is the first day of each of the months shown. At the top, that says Feb. 1 2022.
Thanks.

Please! Change the way the Last Modified column sorts so that I can sort in descending order and see the last backup files that are created and not have to search though so many pages. It's a waste of time.

**Comment by colindesaulniers** [comment]
I'm using version 1.22.1 (Latest version as of today).

I'm not really sure what the sorting behavior is doing, but it almost seems like some data is even missing. I know there's backups every day, But the last I see is from Feb. 1st.

I also noticed that if I go all the way to the end page, then go back to the first page, all of a sudden, I can see my missing dates in the correct order. If I click Refresh, it reverts back to missing dates.

First load and on refresh:
![image](https://user-images.githubusercontent.com/8417166/153929634-521b325f-c95f-4775-baab-db832af7606f.png)

Then if I click the last page and go back to first:
![image](https://user-images.githubusercontent.com/8417166/153929771-ad22765e-eedc-4600-b335-7f5aa8ea9120.png)

So there must be some other issue with the software that it's not finding all the files at first until the last page is viewed.

It's especially annoying because I don't have a way to click directly to the last page:
![image](https://user-images.githubusercontent.com/8417166/153929914-4f212179-197b-4773-9e36-66f5d4c8fc5f.png)

I have to click on "Load more" until I see the last page, then click "39" (last page):
![image](https://user-images.githubusercontent.com/8417166/153930017-8abba067-32f3-4136-970b-139690ca00d9.png)

Then, if I go back to the first page, everything is there and in the correct order.



So my initial comment is no longer correct, but this new information might help solve why I'm not seeing all the files on first load or refresh.

**Comment by JasonYeMSFT** [comment]
@colindesaulniers I see the problem now. We can only load blobs ordered by their names so the first batch of data may not contain blobs with consecutive last modified time. We have a work item in our backlog to increase the pagination options but it's worked on yet.

**Comment by JasonYeMSFT** [comment]
I am going to close this issue and track the cache problem in the linked issue.
