### ISSUE TITLE
Multiple requests to access Keychain

### ISSUE THREAD

**Issue by craxal** [Microsoft/AzureStorageExplorer#542]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: macOS
**Architecture**: x64
**Regression From**: 1.3.1

#### Steps to Reproduce: ####
1. Install 1.4.0.
2. Launch Storage Explorer

#### Expected Experience: ####
Only one or two requests for user password to access Keychain.

#### Actual Experience: ####
Many requests for user password (8+).

**Comment by craxal** [comment]
Each individual Local & Attached connection and Quick Access item saves confidential information to the system's credential manager as an individual "account". On macOS, accessing each account requires confirmation by password from the user.

Instead, we should save a single encryption key and use it to write confidential information to a file or local storage instead.

**Comment by JakeRadMSFT** [comment]
I believe this is only a Dev problem since we use both signed and unsigned versions ... if you only stick with signed ... I believe this never happens. (Users please correct me if I'm wrong).

**Comment by MRayermannMSFT** [comment]
I believe Jake is correct.
