### ISSUE TITLE
It would be better to allow edit the 'Blob container or directory URL' field in the 'Enter Connection Info' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5421]
**Storage Explorer Version**: 1.23.0-dev
**Build Number**: 20220209.5
**Branch**: main
**Platform/OS**: Windows 10
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account  -> Blob Containers. 
2. Create a blob container -> Create a new folder -> Upload one file to the folder.
3. Right click the file -> Click 'Copy Direct Link'.
4. Paste the direct link to Edge browser -> Open the direct link.
5. Click 'Attach Directory' option -> Select one Azure account -> Click 'Next'.
6. There is an error message in the 'Enter Connection Info' page.

## Expected Experience ##
It would be better to 'Blob container or directory URL' field.

## Actual Experience ##
Can't edit the 'Blob container or directory URL' field.
![image](https://user-images.githubusercontent.com/41351993/153145205-eeb3c43c-e19c-4eeb-9852-c018684baf63.png)

**Comment by MRayermannMSFT** [comment]
I've fixed this scenario that produced the error. Not having the text field be editable is on purpose.

**Comment by v-xianya** [comment]
Verified this issue on the build 20220210.3. No error occurs in the 'Enter Connection Info' when attaching Directory using a file which has a parent folder
![image](https://user-images.githubusercontent.com/41351993/153327518-af0fc02e-3cd8-49cb-b2a7-3f9ef898757d.png)
