### ISSUE TITLE
Wrong error displayed for broken Quick Access queue node

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#5423]
### Repro Steps

1. Launch Storage Explorer and sign in with an Azure account.
2. Expand nodes in the tree till you find a queue node.
3. Add the queue node to Quick Access.
4. Remove the account associated with the queue.
5. The queue node in Quick Access should change to a broken node. Click on the node to show the error.

### Expected

The error should say something like "The user account associated with this queue is not signed in. Please sign in to access the queue."

### Actual

The error shows something like:

```
{
  "name": "TypeError"
}
```

### Additional Context

I suspect this has something to do with the order of operations we take in order to determine whether a queue in Quick Access should be a broken node. For some reason, we test to see if the queue exists before checking whether the credentials in the connection object are even valid. We should be checking for valid auth or SAS credentials first.

**Comment by MRayermannMSFT** [comment]
Duplicate #4412
