### ISSUE TITLE
{   "message": "\"Ocorreu um erro ao enviar a solicitação.\"" }

### ISSUE THREAD

**Issue by Andrefridel** [microsoft/AzureStorageExplorer#5424]
Erro ao tentar logar

**Comment by MRayermannMSFT** [comment]
@Andrefridel were you trying to sign in when this error occurred? If yes, can you please follow [these](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#authentication-logs) steps? Thanks.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of reply. If you still need help we recommend opening an Azure support ticket via the portal.
