### ISSUE TITLE
Azure Storage Explorer hides the loading image before all blobs were listed

### ISSUE THREAD

**Issue by rjpramos** [microsoft/AzureStorageExplorer#5431]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.22.1

### Architecture

i86

### Storage Explorer Build Number

20220122.3

### Platform

Windows

### OS Version

Windows 10

### Bug Description

When listing files in a blob container containing many files, sometimes only part of the files/folders are shown when the loading image disappears. Then, after several seconds, more files are shown. This leads the user to believe that the files do not exist because the loading image is already gone and the files still take some time to appear.

### Steps to Reproduce

1. Launch Azure Storage Explorer
2. List files on a blob container that has many files and which takes some time to answer
3. The loading picture should appear, wait for it to disappear, some files will appear
4. Sometimes not all the files will appear and after some good seconds, the remaining ones will appear

### Actual Experience

Some files take longer to appear even though the loading information disappeared, which misleads the user to think that the files are not there

### Expected Experience

I expect the loading picture or some loading information to stay there and only disappear when all files were listed

**Comment by MRayermannMSFT** [comment]
Closing due to lack of reply. If you still need help we recommend opening an Azure support ticket via the portal.
