### ISSUE TITLE
Error opening table in Azure Storage Explorer (Reason: oom. Code -536870904.)

### ISSUE THREAD

**Issue by jkerie** [microsoft/AzureStorageExplorer#5435]
This error was happening on the previous version I was running (1.19.1??) and today I just installed a new version (1.22.1) and it behaves exactly as before. The error is 100% reproducible. It happens identically every time I try to open the table..

Steps:
1. Navigate to the subscription ID in the explorer tab
2. Open the storage account
3. Open Tables
4. Click on the "WADWindowsEventLogsTable"
5. The table attempts to open, beginning by showing only the two key column headings PartitionKey and RowKey (but no data)
6. It then spins while it attempts to load the rest and will eventually throw an error (after maybe 30-60 seconds)

The error message is: "A renderer process crash caused Storage Explorer to stop working correctly. Storage Explorer can try to restart the program. Reason: oom. Code -536870904.

I would guess that "oom" is out of memory. As the name suggests, this is simply the table that Azure is creates/saves the diagnostic information to. We only have 2 VMs in the cloud, so the volume of data is not massive. If I delete the table, Azure will automatically recreate it (as expected), and I will be able to open it for some time. However, in maybe only 24 hours, I will experience the issue that I cannot open the table anymore. From what I understand, the explorer should only be trying to fetch the first 1,000 records (which do accumulate quite quickly). I would not expect this to cause the kind of error it does. Other WAD tables in the same storage account open just fine, even ones with over 400,000 entries.

Incidentally, this issue is repeatable and identical whether I run Storage Explorer on a local Windows 10 PC, or if I run it on a Server 2016 VM in Azure.

**Comment by MRayermannMSFT** [comment]
@jkerie 

- How much RAM does your machine have?
- Prior to opening the table how much RAM is being used?
- As you open the table, can you watch the RAM usage and see how high it goes?
- Would it be possible for you to share a SAS url to the table with us? It can be read only. You can send it so sehelp @ microsoft dot com.

**Comment by craxal** [comment]
@jkerie Would you like to try using a test build to see if your problem is resolved?

https://cralvordtest02.blob.core.windows.net/customer-share/internal/1.23.0-table-rbac/StorageExplorer-darwin-x64.zip?sv=2020-10-02&st=2022-02-14T19%3A38%3A47Z&se=2022-02-21T19%3A38%3A00Z&sr=b&sp=r&sig=7MRYSOgAwO%2FutNgUaApjkzsv0NOPupvImedJ43QxQg0%3D

**Comment by jkerie** [comment]
Thank you. I will look at this tomorrow.

**Comment by jkerie** [comment]
I am going to try the test build, but wanted to update on the prior questions about RAM, etc.:

- System has 16GB RAM.
- At the time of opening only about 6.5GB was used.
- As it tried to process, it did gradually consumer more, but it wasn't a straight line progression. It wiggled a little as it went up. The error took about 2 minutes to reach and by that point, the memory usage had reached about 8GB (so still about 8GB remaining free).
- I will email you an SAS

**Comment by craxal** [comment]
@jkerie The table loads up normally on my end, so I think the test build should work for you. Let us know how it works out.

**Comment by jkerie** [comment]
Thanks, craxal. I downloaded the zip file, but I guess I wasn't sure how to run it. Do I need to compile it and with what? I am running Windows 10.

**Comment by craxal** [comment]
@jkerie Sorry, it wasn't clear from the bug description that you were running Windows. Here's another link for a Windows installer:

https://cralvordtest02.blob.core.windows.net/customer-share/internal/1.23.0-table-rbac/StorageExplorer-ia32.exe?sv=2020-10-02&st=2022-02-15T18%3A27%3A45Z&se=2022-02-21T18%3A27%3A00Z&sr=b&sp=r&sig=C7sKDwXRUfMMCvKkKbOxdH2YD4YvTJ31%2FQulG5ouO2U%3D

**Comment by jkerie** [comment]
Yes, that fixed it - it works again! Thanks! When do you expect this version to be officially released?

**Comment by craxal** [comment]
@jkerie Good to know! Assuming things go smoothly, we are locking down on changes for 1.23.0 now so that we can release sometime this month.
