### ISSUE TITLE
Error when trying to open a blob container in Azure Storage Explorer

### ISSUE THREAD

**Issue by maalcalar** [microsoft/AzureStorageExplorer#5436]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.22.1

### Architecture

x64

### Storage Explorer Build Number

20220122.3

### Platform

Windows

### OS Version

Windows 10

### Bug Description

When trying to open my blob container it pops up an error message with status code 403, I was using a previous version that were working fine until last year but not today so I updated to 1.22.1 version but it is still showing the same error message. Every time that I try to open or refresh the blob container is the same. I tried opening my blob container on Azure Portal but I can't see my container and it shows the same error message but different status code 400.

### Steps to Reproduce

1. Launch Azure Storage Explorer
2. Expand a blob container node

### Actual Experience

I launch Azure Storage Explorer, expand storage accounts and try to expand my blob containers.
![imagen](https://user-images.githubusercontent.com/16619579/153737022-0179172c-fe57-495b-8b4a-e585db401c16.png)

Then it shows this message
![imagen](https://user-images.githubusercontent.com/16619579/153737054-b13afe24-e5df-4f16-ae74-3dcf903bc87b.png)

### Additional Context

SO: Windows 10

I'm not using proxy.

Azure Storage Explorer (Desktop app) message detail:
```
{
  "name": "RestError",
  "message": "The specified account is disabled.\nRequestId:3f338e26-601e-0031-7589-200966000000\nTime:2022-02-13T03:27:11.1142242Z",
  "stack": "RestError: The specified account is disabled.\nRequestId:3f338e26-601e-0031-7589-200966000000\nTime:2022-02-13T03:27:11.1142242Z\n    at handleErrorResponse (C:\\Users\\******\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:3129:19)\n    at C:\\Users\\******\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:3065:49\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async StorageRetryPolicy.attemptSendRequest (C:\\Users\\******\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\storage-blob\\dist\\index.js:14086:24)\n    at async StorageClientContext.sendOperationRequest (C:\\Users\\******\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:4894:31)\n    at async BlobServiceClient.listContainersSegment (C:\\Users\\******\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\storage-blob\\dist\\index.js:23132:20)",
  "code": "AccountIsDisabled",
  "statusCode": 403,
......
}
```

Azure portal (Web app) message detail:
```
{
  "shellProps": {
    "sessionId": "d8b23a46f45349539d461fb24231571f",
    "extName": "Microsoft_Azure_Storage",
    "contentName": "BlobServiceBlade",
    "resourceId": "/subscriptions/eac0e7f6-b166-4816-8dd1-cadbdeaed5ba/resourcegroups/almacenamiento/providers/Microsoft.Storage/storageAccounts/******"
  },
  "error": {
    "message": "AccountIsDisabled",
    "code": 400,
    "details": {
      "htmlTemplate": "<p><ul><li><span style=\"word-break: break-word;\">The specified account is disabled.\nRequestId:3791c200-601e-001e-4c8a-2004ad000000\nTime:2022-02-13T03:31:34.5202824Z</span>&nbsp;</li></ul></p>"
    }
  }
}
```

**Comment by MRayermannMSFT** [comment]
@maalcalar it looks your azure account has been disabled. You'll need to reach out to Azure support for more help.
