### ISSUE TITLE
Miss the action 'Copy Direct Link to Table' for one new created/pasted table

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5437]
**Storage Explorer Version**: 1.23.0-dev
**Build Number**: 20220212.2
**Branch**: main
**Platform/OS**: Windows 10/macOS Monterey 12.2
**How Found**: From running test case
**Regression From**: Previous release (1.22.1)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a new table -> Observe its context menu.
3. Check whether there is the action 'Copy Direct Link to Table'.

## Expected Experience ##
There is the action 'Copy Direct Link to Table'.

## Actual Experience ##
There is no action 'Copy Direct Link to Table'.
![image](https://user-images.githubusercontent.com/41351993/153821040-cdf12ca5-6615-47cc-90be-cbec8ca3be09.png)

## Additional Context ##
The action 'Copy Direct Link to Table' displays after manually refreshing.

**Comment by v-xianya** [comment]
This issue reproduces on the build main/20220214.5. So reopen it and will verify on a newer build.

**Comment by craxal** [comment]
Some changes did not make it into that build.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220216.1. Fixed.

**Comment by v-xianya** [comment]
Verified this issue on the build 20220217.2. Fixed.
