### ISSUE TITLE
Still need to attach directory when there is already an Azure AD attached directory if opening the direct link of one file which has a parent directory

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5438]
**Storage Explorer Version**: 1.23.0-dev
**Build Number**: 20220212.2
**Branch**: main
**Platform/OS**: Windows 10/macOS Monterey 12.2
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Add the rbac role 'Storage Blob Data Contributor' then assign to one azure account.
3. Create a folder in the blob container -> Upload one file to the folder -> Attach the folder via Azure AD.
4. Right click the file -> Copy its direct link.
5. Open the direct link -> Observe the open direct link dialog.
6. Check whether no need to attach directory.

## Expected Experience ##
No need to attach directory.

## Actual Experience ##
Still need to attach directory.
![image](https://user-images.githubusercontent.com/41351993/153822201-0ded0d9a-66a8-4e6c-8c07-118b968ec9af.png)

**Comment by MRayermannMSFT** [comment]
@v-xianya I have merged a fix for this into main. However, at this time, detecting that an attachment already exists only works for new attachments going forward from here.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220216.1. Fixed.
