### ISSUE TITLE
No access to file share 

### ISSUE THREAD

**Issue by shishu98** [microsoft/AzureStorageExplorer#5447]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.22.1

### Regression From

1.18.0

### Architecture

x64

### Storage Explorer Build Number

1.22.1

### Platform

Windows

### OS Version

Windows10

### Bug Description

![image](https://user-images.githubusercontent.com/22905084/154128099-cd033eb3-1fcf-44eb-85eb-4c4cd52966f1.png)

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/22905084/154128372-3c5b5a7c-3d96-4ed5-a7ce-a345881de32a.png)

### Actual Experience

works with older version

### Expected Experience

expect to access the share

### Additional Context

[errorlog.txt](https://github.com/microsoft/AzureStorageExplorer/files/8073787/errorlog.txt)

**Comment by MRayermannMSFT** [comment]
@shishu98, first things first, can you give system proxy a try? Read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having problems, we recommend you open an Azure support ticket.
