### ISSUE TITLE
The custom property added under the query builder mode does not display in the 'Select Columns' dialog

### ISSUE THREAD

**Issue by v-sunnysun** [microsoft/AzureStorageExplorer#5449]
**Storage Explorer Version:** 1.23.0-dev
**Build Number:** 20220216.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.6.1
**Architecture:** ia32/x64
**How Found:** Ad-hoc testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create a Table -> Click 'Query' in its toolbar.
3. Add one entity with a custom property. (Like the below)
![image](https://user-images.githubusercontent.com/98519664/154246664-efa6b1c0-870d-4a6a-ae3c-0b3de149e402.png)
4. Expand 'Advanced Options' -> Click 'Select Columns...'.
5. The 'Select Columns' dialog pops up.
6. Check whether the custom property displays.

## Expected Experience ##
 The custom property displays.
## Actual Experience ##
 The custom property doesn't display.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220414.17. Fixed.
