### ISSUE TITLE
There is no warning when typing '-0.2' into the 'Show top results' field

### ISSUE THREAD

**Issue by v-sunnysun** [microsoft/AzureStorageExplorer#5451]
**Storage Explorer Version:** 1.23.0-dev
**Build Number:** 20220217.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.6.1
**Architecture:** ia32/x64
**How Found:** Ad-hoc testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create a table -> Click 'Query' in its toolbar.
3. Expand 'Advanced Options' -> Type '-0.2' into the 'Show top results' field.
4. Check whether there is an warning next to the 'Show top results'.

## Expected Experience ##
 There is an warning next to the 'Show top results'.
![image](https://user-images.githubusercontent.com/98519664/154416223-69de3d2d-a7ec-4831-b133-17d5bb383ad6.png)

## Actual Experience ##
There is no warning next to the 'Show top results'.
![image](https://user-images.githubusercontent.com/98519664/154416509-bf946252-8019-4bc5-baf9-20bbbe46070f.png)

**Comment by craxal** [comment]
I'm going suggest we not worry about this one. We use `Number.parseInt` in the code, which rounds all decimal numbers to integers. Specifically, it rounds numbers between -1 and 0 to 0, and 0 is a valid value for this field. I also think it's very unlikely for a user to accidentally enter a hyphen and a period.
