### ISSUE TITLE
There is no action 'Copy Direct Link to Blob Container' for one secondary ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5452]
**Storage Explorer Version**: 1.23.0-dev
**Build Number**: 20220217.2
**Branch**: main
**Platform/OS**: Windows 10/MacOS Monterey 12.2
**Architecture**: ia32/x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Select one blob container -> Right click it.
3. Click 'Open Secondary Location' -> Right click the secondary blob container -> Observe its context menu.
4. Check whether there is the action 'Copy Direct Link to Blob Container'.

## Expected Experience ##
There is the action 'Copy Direct Link to Blob Container'.
![image](https://user-images.githubusercontent.com/41351993/154433254-8e8089fb-2bfd-43d2-95b0-32820a7aea0e.png)

## Actual Experience ##
There is no action 'Copy Direct Link to Blob Container'.
![image](https://user-images.githubusercontent.com/41351993/154432636-ecac3099-3321-4be5-8f45-982e7a2f1791.png)

**Comment by MRayermannMSFT** [comment]
By design for now. For 1.23 we are not supporting direct link on the secondary container.
