### ISSUE TITLE
The content type of a folder whose name length is less than 4 displays between the 'Blob Type' and 'Content Type' columns

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5455]
**Storage Explorer Version**: 1.23.0
**Build Number**: 20220219.7
**Branch**: rel/1.23.0
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.2.1(MacBook Air M1)
**Architecture**: ia32\x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one non-ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Create a folder with the name 'f1'.
3. Upload one blob to the folder -> Go back to the root path.
4. Check whether the folder type displays under the 'Content Type' column.

## Expected Experience ##
The folder type displays under the 'Content Type' column.

The screenshot against one ADLS Gen2 blob container:
![image](https://user-images.githubusercontent.com/41351993/155079821-141b263b-5d8c-46c4-8ab0-651bafe5816b.png)

## Actual Experience ##
The folder type displays between the 'Blob Type' and 'Content Type' columns.
![image](https://user-images.githubusercontent.com/41351993/155079648-e91d5420-89d1-49a8-bb2d-d9e29279e358.png)

**Comment by MRayermannMSFT** [comment]
Not going to worry about this unless from customer feedback.
