### ISSUE TITLE
The filter option is switched from 'Prefix' to 'Tag Query' if changing the 'List Mode' under tag query status

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5456]
**Storage Explorer Version**: 1.23.0
**Build Number**: 20220219.7
**Branch**: rel/1.23.0
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.2.1(MacBook Air M1)
**Architecture**: ia32\x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one non-ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container.
3. Open the view options panel -> Select 'Tag Query' -> Click 'Apply'.
4. Select 'Prefix' -> Change the list mode.
5. Check whether the option 'Prefix' is still selected.

## Expected Experience ##
The option 'Prefix' is selected.

## Actual Experience ##
The option 'Tag Query' is selected.
![tag1222](https://user-images.githubusercontent.com/41351993/155084083-9242a2ce-da8f-498d-b61c-7b9cf6816c00.gif)

**Comment by MRayermannMSFT** [comment]
@v-xianya we're going to consider this as by design. Since you have not entered any text in the prefix text box you have not yet left the query mode. So when you then change list mode, we update the radio button to reflect the fact you are still viewing tag query results.
