### ISSUE TITLE
Succeed to create/clone/paste a table when there is already a table with an equivalent name

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5457]
**Storage Explorer Version**: 1.23.0
**Build Number**: 20220219.7
**Branch**: rel/1.23.0
**Platform/OS**: Windows 10
**Architecture**: ia32
**Azurite Version**: 3.15.0
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Install and run Azurite 3.15.0 -> Launch Storage Explorer.
2. Expand 'Local & Attached -> Storage Accounts -> (Emulator - Default Ports) (Key)'.
3. Right click 'Tables' node -> Create a table using name 'table'.
4. Then create a table using name 'TABLE'.
5. Check whether fails to create a table using name 'TABLE'.

## Expected Experience ##
Fail to create a table using name 'TABLE'.
![image](https://user-images.githubusercontent.com/41351993/155098062-f300e33b-9b0a-4d69-b224-19e90386977b.png)

## Actual Experience ##
Succeed to create a table using name 'TABLE'.
![image](https://user-images.githubusercontent.com/41351993/155098154-89d4fc35-e56a-4f2a-bdb3-9fab086166bc.png)

![image](https://user-images.githubusercontent.com/41351993/155098193-f74f5c53-962a-4733-9db8-40b4b73cc15e.png)

**Comment by craxal** [comment]
This is due to an issue in the emulator, likely because they are not handling table names in a case-insensitive manner.

https://github.com/Azure/Azurite/issues/1355

**Comment by craxal** [comment]
This is resolved as of Azurite 3.17.1.

**Comment by v-xianya** [comment]
Verified this issue on the build 20220513.1 with Azurite 3.17.1. Fixed.
