### ISSUE TITLE
Incorrect Content Type for Certain Extensions

### ISSUE THREAD

**Issue by computeronix** [microsoft/AzureStorageExplorer#5459]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.22.1

### Architecture

x64

### Storage Explorer Build Number

20220122.3

### Platform

Windows

### OS Version

Windows 10

### Bug Description

When uploading certain, known, extensions, the content type is changed to application/octet-stream

This is expected for generic content types but for known ones this should not happen

Examples this happens which then causes issues and needs to be manually changed

.svg -> should be image/svg+xml
.json -> should be application/json

Here is a cheat sheet of content types for reference -- many of them are auto-detected today
https://ppolyzos.com/2015/10/27/apply-proper-content-type-to-files-in-azure-storage-containers-based-on-file-extensions/

### Steps to Reproduce

1. Launch Storage Explorer
2. Connect to Storage Account (make sure storage account is setup as static website host)
3. Upload an svg and/or json
4. It should present the SVG / JSON in a website, but instead asks to download

### Actual Experience

Asks to download the SVG or JSON instead of presenting it in the website as hosted content

### Expected Experience

Present in the site rather than download as a normal image/data content

### Additional Context

As a workaround a script must be run manually each time content is uploaded to change the content type to the proper content type to correct this

**Comment by JasonYeMSFT** [comment]
We use AzCopy to handle the upload. On Windows, AzCopy will lookup your local registry to determine which contentType to use for the uploaded blobs. Once it's configured, your future uploads will have the correct content types set. See https://github.com/microsoft/AzureStorageExplorer/issues/2267 for more details.

**Comment by computeronix** [comment]
Thank you! This works! closing out
