### ISSUE TITLE
GPU process crash caused Storage Explorer to stop working correctly

### ISSUE THREAD

**Issue by kmathewmk** [microsoft/AzureStorageExplorer#5462]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.3

### Architecture

x64

### Storage Explorer Build Number

20211020.2

### Platform

Windows

### OS Version

Windows 10 Enterprise

### Bug Description

Storage Explorer starts with messages "A GPU process crash caused Storage Explorer to stop working correctly. Please close and restart the application" 

### Steps to Reproduce

Launch Storage Explorer

### Actual Experience

Since today, when the Storage Explorer starts up I get a bunch of messages of the kind "A GPU process crash caused Storage Explorer to stop working correctly. Please close and restart the application" 
![image](https://user-images.githubusercontent.com/52198810/155285873-c260c559-5d0d-478a-be09-310076b12405.png)

### Expected Experience

Error free startup

### Additional Context

Edition	Windows 10 Enterprise
Version	20H2
Installed on	‎11/‎09/‎2020
OS build	19042.1526
Experience	Windows Feature Experience Pack 120.2212.4170.0

**Comment by MRayermannMSFT** [comment]
@kmathewmk have you tried restarting/always restarting with the hardware acceleration disabled?

**Comment by kmathewmk** [comment]
No, I did not disable h/w acceleration for fear of it having an adverse impact on other applications. The problem started one day and stopped happening a little while later. Not clear what stopped the problem from happening. A simple restart of the Azure Storage Explorer app was not enough.

**Comment by MRayermannMSFT** [comment]
@kmathewmk can you try restarting/always restarting with the hardware acceleration disabled then?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem we recommend opening an Azure support ticket via the portal.
