### ISSUE TITLE
The existing table tab is opened when pasting one table if there is already a same table

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5463]
**Storage Explorer Version:** 1.23.0
**Build Number:** 20220223.4
**Branch:** rel/1.23.0
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.2.1(MacBook Air M1)
**Architecture:** ia32\x64
**How Found:** From running test cases
**Regression From:** Previous release (1.22.1)

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create a table -> Close the opened tab.
3. Copy the table -> Right click _same_ Tables node -> Click 'Paste Table'.
4. Check no new tab is opened.

## Expected Experience ##
No new tab is opened.

## Actual Experience ##
The existing table tab is opened.

## Additional Context ##
This issue doesn't reproduce when cloning/creating one table.

**Comment by craxal** [comment]
The paste code was indiscriminately creating a table node and opening an editor for it, regardless of the outcome of kicking off the copy operation. Easy fix: we just need to add a condition to create a node and open an editor if the table copy successfully creates a new table and kicks off the copy operation.

**Comment by v-kellyluo** [comment]
Verified this issue on the build hotfix/20220303.8. Fixed.
