### ISSUE TITLE
No new table tab is opened when cloning one table

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5464]
**Storage Explorer Version:** 1.23.0
**Build Number:** 20220223.4
**Branch:** rel/1.23.0
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.2.1(MacBook Air M1)
**Architecture:** ia32\x64
**How Found:** From running test cases
**Regression From:** Previous release (1.22.1)

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create a table -> Right click the table -> Click 'Clone...'.
3. Input a valid name -> Click 'Clone'.
4. Check whether a new table tab is opened.

## Expected Experience ##
A new table tab is opened.

## Actual Experience ##
No new table tab is opened.

## Additional Context ##
This issue doesn't reproduce when pasting one table.

**Comment by craxal** [comment]
Looks like we're just missing the code that actually opens the tab, so we just need to add it back in.

**Comment by v-kellyluo** [comment]
Verified this issue on the build hotfix/20220303.8. Fixed.
