### ISSUE TITLE
Fail to add one entity when the value of the 'PartitionKey/RowKey' property is '#'

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5465]
**Storage Explorer Version:** 1.23.0
**Build Number:** 20220223.4
**Branch:** rel/1.23.0
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.2.1(MacBook Air M1)
**Architecture:** ia32\x64
**How Found:** Exploratory testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create a table -> Click 'Add'.
3. Type "#" in the value field of the 'PartitionKey/RowKey' property -> Click 'Insert'.
4. Check whether succeeds to add the entity.

## Expected Experience ##
Succeed to add the entity.

## Actual Experience ##
Fail to add the entity, an error dialog pops up.
![image](https://user-images.githubusercontent.com/87792676/155301921-c06e2fe8-84fa-4767-bf6c-a2170926f9ce.png)

## Additional Context ##
This issue doesn't reproduce for emulator tables.

**Comment by MRayermannMSFT** [comment]
Let's make sure this is by design/an expected server error. And for it not repro'ing with emulator, let's confirm that's a bug on their end if this is by design.

**Comment by craxal** [comment]
As explained by the [Azure documentation](https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-the-table-service-data-model#characters-disallowed-in-key-fields), the "#" character is not allowed for keys. Therefore, this is by design in the service and a bug in the emulator.

I've opened https://github.com/Azure/Azurite/issues/1371 against Azurite.

**Comment by craxal** [comment]
This is resolved as of Azurite 3.17.1.

**Comment by v-xianya** [comment]
Will verify this bug when the bug [5721](https://github.com/microsoft/AzureStorageExplorer/issues/5721) got fixed.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220516.1 with Azurite 3.17.1. Fixed.
Fail to add one entity when the value of the 'PartitionKey/RowKey' property is '#' in one emulator table.
![image](https://user-images.githubusercontent.com/87792676/168508364-7c6e9d24-972d-4daa-8ca7-55b0925c0c67.png)
