### ISSUE TITLE
The local folder whose name is '%2A%3F' displays as '*?' when uploading it to the blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5467]
**Storage Explorer Version**: 1.23.0
**Build Number**: 20220223.14
**Branch**: rel/1.23.0
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.2(MacBook Air M1)
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload a non-empty folder with the name '%2A%3F'.
5. Check whether the folder '%2A%3F' displays in the blob editor.

## Expected Experience ##
The folder '%2A%3F' displays in the blob editor.

## Actual Experience ##
The folder '*?' displays in the blob editor.
![image](https://user-images.githubusercontent.com/41351993/155450494-9e6f4b58-da19-41ea-8427-c55176353026.png)

## Additional Context ##
1. This issue doesn't reproduce when copying & pasting one folder named '%2A%3F'.
2. This issue doesn't reproduce for file shares.

**Comment by MRayermannMSFT** [comment]
@v-xianya sorry for not paying closer attention earlier. I actually think this is expected. For any characters not allowed as file names on any of the supported OSs, AzCopy will encode those characters if they are in the names of blobs/folders being downloaded. And then when uploading files/folders with such encoded characters, they will be decoded. That is the behavior you are seeing.

If you go into the AzCopy settings and disable auto decoding:
![image](https://user-images.githubusercontent.com/21112697/156042965-937bfe0f-2b1c-400d-bde7-76a46471c038.png)

Then you should see the folder name be preserved as `%2A%3F`.

**Comment by v-xianya** [comment]
@MRayermannMSFT Thank you for the update!
For blob container, The folder name be preserved as %2A%3F if disabling the auto decode.

For file share, The folder name be preserved as %2A%3F regardless of disabling/enabling auto decoding.
Could you help to elaborate? thanks😊

**Comment by MRayermannMSFT** [comment]
> The folder name be preserved as %2A%3F regardless of disabling/enabling auto decoding.
Could you help to elaborate? thanks😊

That is by design. On the server side, file shares have the same restrictions as windows. We should update our setting description.

**Comment by v-xianya** [comment]
@MRayermannMSFT Thank you for the response!

**Comment by MRayermannMSFT** [comment]
Description was updated:
![image](https://user-images.githubusercontent.com/21112697/162837970-9499c923-2da0-449d-a93c-8771f79fc0c6.png)
