### ISSUE TITLE
It is hard to see the focus color in the 'Column Options' dialog under 'High Contrast-Black/White' theme

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5468]
**Storage Explorer Version:** 1.23.0
**Build Number:** 20220223.14
**Branch:** rel/1.23.0
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.2(MacBook Air M1)
**Architecture:** ia32\x64
**How Found:** Ad-hoc testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Launch Storage Explorer -> Go to the 'View' menu -> Change the theme to 'High Contrast - Black/White'.
2. Expand one storage account -> Tables.
3. Create a table -> Click 'Column Options'.
4. The 'Column Options' dialog pops up -> Select one available column.
5. Check whether it is easy to see the focus color.

## Expected Experience ##
It is easy to see the focus color.
The screenshot under the 'Light' theme:
![image](https://user-images.githubusercontent.com/87792676/155486721-d058f5fd-37ee-4f21-bfb1-342bcb1c3171.png)

## Actual Experience ##
It is hard to see the focus color.
![image](https://user-images.githubusercontent.com/87792676/155486544-10873290-8de1-4ab3-a6e5-6de77f1afe52.png)

**Comment by craxal** [comment]
We should use a dashed/dotted border like we do for most other elements.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220422.9. Fixed.
![image](https://user-images.githubusercontent.com/87792676/164585197-530c35be-d6b0-46fe-b8fc-940c26ab557a.png)
