### ISSUE TITLE
Can't open blob containers

### ISSUE THREAD

**Issue by Sophieleend** [Microsoft/AzureStorageExplorer#547]
**Storage Explorer Version**: 
**Platform/OS Version**: 
**Architecture**: 
**Regression From**: 

#### Steps to Reproduce: ####
1. 
2.

**Comment by craxal** [comment]
Please provide more information as indicated above. Make sure you include your version of Storage Explorer, steps to reproduce, and expected and actual outcomes.

**Comment by CarlosTenorio** [comment]
Steps to reproduce:
1. Update to 1.4
2. On the local storage accounts try to create or open a new container...

**Comment by craxal** [comment]
@CarlosTenorio, can you clarify what you mean by "local storage accounts"? Do you mean that you're expanding **Local & Attached** > Storage Accounts?

**Comment by Sophieleend** [comment]
hi it's already been solved :) it was something that didn't load right

**Comment by CarlosTenorio** [comment]
@craxal Yes, I add a pic trying to explain better my issue :) . With "local storage accounts" I mean the expansion of the **Local & Attached**. My issue is that with the v.1.4 I can not create a new blob container (first pic), but for example, on my Azure, I can (second pic)

![image](https://user-images.githubusercontent.com/15104332/43882072-a7bca760-9bae-11e8-83af-b736f07ef954.png)

![image](https://user-images.githubusercontent.com/15104332/43882297-7c3a3f5c-9baf-11e8-9bcb-2c08a2139bed.png)

**Comment by CarlosTenorio** [comment]
@MRayermannMSFT Thank you for the asnwer. Solved my problem.

**Comment by MRayermannMSFT** [comment]
Awesome! Closing the issue now. 😄
