### ISSUE TITLE
The pasted table displays in the tree view when there is a same table which is being deleted

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5471]
**Storage Explorer Version**: 1.23.0
**Build Number**: 20220223.14
**Branch**: rel/1.23.0
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.2(MacBook Air M1)
**Architecture** ia32\x64
**How Found**: exploratory testing
**Regression From**: Previous release (1.22.1)

## Steps to Reproduce ##
1. Expand storage account A -> Tables.
2. Create a table -> Copy the table and paste it to storage account B.
3. Delete the pasted table in the storage account B -> Paste the same table to storage account B.
4. Check whether fails to paste the table and no pasted table in the tree view.

## Expected Experience ##
Fail to paste the table.

## Actual Experience ##
1. There is a failed activity log.
2. The pasted table displays in the tree view and auto opened.
![image](https://user-images.githubusercontent.com/41351993/155521817-b5278a29-2c67-4d96-a6ed-c5d3486219f9.png)

## Additional Context ##
1. The similar issue [5201](https://github.com/microsoft/AzureStorageExplorer/issues/5201).
2. Here is the record:
![22222222](https://user-images.githubusercontent.com/41351993/155522216-d2b36fd6-3e77-4b90-8be2-595540d58397.gif)

**Comment by craxal** [comment]
The client library doesn't throw when a "table already exists" response from the service comes back. This was a conscious design choice made by the team. To mitigate this, we added code to test whether a table exists by attempting to list entities. If that throws, we assume the table doesn't exist.

Unfortunately, this code doesn't work when the table is being deleted. We need to implement another approach. We should be able to do this by using the `onResponse` option to intercept the service response and act accordingly.

**Comment by v-xianya** [comment]
@craxal 
Verified this issue on the build 20220305.7.
The current behavior as below:  Is the expected behavior?
1. The pasted table displays on the tree view.
2. Auto opens with an error info bar 'TableNotFound'.
3. There is an error activity log with error info'TableBeingDeleted'
![image](https://user-images.githubusercontent.com/41351993/156957341-e717f850-bd65-4261-b23b-e13ea8ec4417.png)


![image](https://user-images.githubusercontent.com/41351993/156957363-af209309-846f-49c1-8c61-7427b34f3b1d.png)

**Comment by craxal** [comment]
@v-xianya The changes were merged to a hotfix branch, but I hadn't merged those changes to main yet. Those changes should now be on main, so please verify again.

**Comment by v-xianya** [comment]
Verified this issue on the build 20220308.2. Fixed.
![image](https://user-images.githubusercontent.com/41351993/157151541-c662c05f-722f-4bf8-b653-711654b21503.png)
