### ISSUE TITLE
Error opening Blob Container under Storage

### ISSUE THREAD

**Issue by yabba1971** [microsoft/AzureStorageExplorer#5472]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.22.1

### Architecture

x64

### Storage Explorer Build Number

20220122.3

### Platform

Windows

### OS Version

11

### Bug Description

Unable to Retrieve child resources

### Steps to Reproduce

1. opened Storage Explorer
2. expanded Storage Accounts
3. expanded our container veeamcamvan
4. tried to expand the blob container and got an error

### Actual Experience

Expected to see our backup files in the Blob

**Comment by JasonYeMSFT** [comment]
The error is about not being able to resolve the domain name (your blob endpoint in the url). Could you ping the endpoint to see if it is accessible from your machine? For example, you can open a powershell window and run

```ps
nslookup stephen.duncan@glendimplexamericas.com.blob.core.windows.net
```

If it cannot find it, you might need to check your endpoint configuration to see if it is hidden in a private network.
