### ISSUE TITLE
The 'Add Entity' dialog pops up again when closing it on MacOS(M1)

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5476]
**Storage Explorer Version**: 1.23.0
**Build Number**: 20220223.14
**Branch**: rel/1.23.0
**Platform/OS**: MacOS Monterey 12.2.1(MacBook Air M1)
**Architecture** x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Bug Descriptions ##

This issue reproduces at the below scenarios, can't be reproduced consistently.

For Queue, Add message dialog.
For File Share/Blob Container, 'New Folder' dialog.
For Tables, Add Entity/Delete dialog.

## Steps to Reproduce ##
1. Expand one table -> Tables.
2. Create a table -> Click 'Add' -> Click 'Insert' on the 'Add Entity' dialog.
3. Observe no 'Add Entity dialog' pops up again.

## Expected Experience ##
No 'Add Entity dialog' pops up again.

## Actual Experience ##
The 'Add Entity dialog' pops up again.

## Additional Context ##
1. This issue doesn't reproduce on the MacOS Monterey 12.2.1(Mac mini).
2. Here is the record:

https://user-images.githubusercontent.com/41351993/155963304-09b173f1-81cc-407a-8ea2-048c55e8b5b3.mov

**Comment by MRayermannMSFT** [comment]
@v-xianya can you still repro this?

**Comment by v-xianya** [comment]
@MRayermannMSFT 
This issue doesn't reproduce on the build main/20220413.3. we are going to close it.
