### ISSUE TITLE
Cannot access local storage emulator

### ISSUE THREAD

**Issue by chris-walton** [microsoft/AzureStorageExplorer#548]
**Storage Explorer Version**: 1.4
**Platform/OS Version**:  Win10 64
**Architecture**: ia32
**Regression From**: 1.3

#### Steps to Reproduce: ####
1. Upgrade Storage Explorer to version 1.4
2. In the explorer navigate to Local & Attached -> Storage Accounts -> (Development)

#### Expected Experience: ####
The local emulator instance will appear and you can access tables/blogs/queues.

#### Actual Experience: ####
The only instance available is (SAS-Attached Services).  

I have tried:

1. Upgrading Visual Studio
3. Stopping/Starting the services
2. Clearing the tables and creating new ones via .NET library

**Comment by kyleweishaupt** [comment]
I'm having the same issue here. I even tried updating my storage emulator version (to 5.6) and still can't see it.

**Comment by darshanrampatel** [comment]
I am also seeing this.

I have also tried adding the local storage account via the below menu which seems to add it okay:

![image](https://user-images.githubusercontent.com/14162899/43906398-16695eba-9beb-11e8-93fc-0e9bae3ca2c1.png)

But when double-clicking on the storage account, I get the below error:

![image](https://user-images.githubusercontent.com/14162899/43906380-0b4dac20-9beb-11e8-9ac9-ac5d6829812c.png)

**Comment by MRayermannMSFT** [comment]
What @darshanrampatel said is correct. The (Development) node was removed, and now you just attach emulators from the connect dialog. This change lets you attach multiple emulators and customize what ports are used. See these docs here for more help: https://docs.microsoft.com/en-us/azure/vs-azure-tools-storage-manage-with-storage-explorer?tabs=macos#work-with-local-development-storage

**Comment by MRayermannMSFT** [comment]
Closing this issue due to lack of response. Please open a new issue if you are still encountering issues.
