### ISSUE TITLE
Local Table service Error deleting rows with valid RowKey but unusual character set

### ISSUE THREAD

**Issue by OzBob** [microsoft/AzureStorageExplorer#5483]
### Preflight Checklist

- ☑️ I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- ☑️ I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- ☑️ I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.22.1

### Architecture

x64

### Storage Explorer Build Number

20220122.3

### Platform

Windows

### OS Version

10 build 

### Bug Description

RowKey with bad char does not show Error when Insert or Delete
Bulk delete rows does show error
Error does not reflect reason for error.
' and % cause the issue

### Steps to Reproduce

create a new table row with
PartitionKey =1
RowKey
62788814-6154-41ed-bc37-78f7e034e28f'test
or
881b2163-bc89-4985-990f-63f1b7e7394e%test

If you select each individual row - select | Delete. no error. Click Refresh. the Row is back again!

If you select two rows, Delete. error in Activities (see log below).

Edit 'broken' row:
double click entity, change string property "FieldId" value from 2 to 3
click OK
odata.error:code:InvalidInput 

### Actual Experience

inconsistent error messages

### Expected Experience

delete table row with illegal odata invalid character in RowKey: Show Error in Activity
create table row with illegal character in RowKey: Show Error.
If character ' or % exist in RowKey then show error.
Do not allow insert of Row with RowKey with illegal characters using the DotNet library Microsoft.Azure.Cosmos.Table, Version=1.0.8.0
```TableOperation.Insert(tableItem);```

### Additional Context

<Details>
{
  "name": "RestError",
  "message": "The specified resource does not exist.\nRequestId:60b87ea1-714f-4988-8659-04b7cfa239a1\nTime:2022-03-01T02:47:05.417Z",
  "stack": "RestError: The specified resource does not exist.\nRequestId:60b87ea1-714f-4988-8659-04b7cfa239a1\nTime:2022-03-01T02:47:05.417Z\n    at handleBodyError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\data-tables\\dist\\index.js:4050:11)\n    at C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\data-tables\\dist\\index.js:4021:13\n    at Array.map (<anonymous>)\n    at parseTransactionResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\data-tables\\dist\\index.js:4010:36)\n    at InternalTableTransaction.submitTransaction (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\data-tables\\dist\\index.js:3976:20)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async TableClient.runOperation (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-table-extension\\dist\\src\\Clients\\TableStorageClient.js:75:24)\n    at async C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-table-extension\\dist\\src\\Actions\\TableActions.js:59:9\n    at async Promise.all (index 0)\n    at async Object.deleteEntities (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-table-extension\\dist\\src\\Actions\\TableActions.js:63:9)",
  "code": "ResourceNotFound",
  "statusCode": 400,
  "request": {
    "url": "http://127.0.0.1:10002/devstoreaccount1/$batch",
    "body": "--batch_22432861-8132-4226-91b9-f4e5ba384e94\r\ncontent-type: multipart/mixed; boundary=changeset_fbfb938b-255b-4f1f-9816-f25a10fd6ea8\r\n\r\n\r\n--changeset_fbfb938b-255b-4f1f-9816-f25a10fd6ea8\r\ncontent-type: application/http\r\ncontent-transfer-encoding: binary\r\n\r\nDELETE http://127.0.0.1:10002/devstoreaccount1/bft(PartitionKey='1',RowKey='d96c7db1-c11a-4141-a512-289f4da5486emtest') HTTP/1.1\r\nAccept: application/json;odata=minimalmetadata\r\nDataServiceVersion: 3.0\r\nIf-Match: *\r\n\r\n\r\n--changeset_fbfb938b-255b-4f1f-9816-f25a10fd6ea8\r\ncontent-type: application/http\r\ncontent-transfer-encoding: binary\r\n\r\nDELETE http://127.0.0.1:10002/devstoreaccount1/bft(PartitionKey='1',RowKey='d9787eef-0a82-4fd3-aea3-68379cf28d87%C2%A7test') HTTP/1.1\r\nAccept: application/json;odata=minimalmetadata\r\nDataServiceVersion: 3.0\r\nIf-Match: *\r\n\r\n\r\n--changeset_fbfb938b-255b-4f1f-9816-f25a10fd6ea8\r\ncontent-type: application/http\r\ncontent-transfer-encoding: binary\r\n\r\nDELETE http://127.0.0.1:10002/devstoreaccount1/bft(PartitionKey='1',RowKey='d9aac488-f21d-4358-9806-a4793cf3c43a%C3%88test') HTTP/1.1\r\nAccept: application/json;odata=minimalmetadata\r\nDataServiceVersion: 3.0\r\nIf-Match: *\r\n\r\n\r\n--changeset_fbfb938b-255b-4f1f-9816-f25a10fd6ea8\r\ncontent-type: application/http\r\ncontent-transfer-encoding: binary\r\n\r\nDELETE http://127.0.0.1:10002/devstoreaccount1/bft(PartitionKey='1',RowKey='d9e32139-be4a-49ed-84d1-01c04be64834%C3%ACtest') HTTP/1.1\r\nAccept: application/json;odata=minimalmetadata\r\nDataServiceVersion: 3.0\r\nIf-Match: *\r\n\r\n\r\n--changeset_fbfb938b-255b-4f1f-9816-f25a10fd6ea8\r\ncontent-type: application/http\r\ncontent-transfer-encoding: binary\r\n\r\nDELETE http://127.0.0.1:10002/devstoreaccount1/bft(PartitionKey='1',RowKey='db927cda-90ac-47ec-9ff7-5c2413c941d1%C3%B7test') HTTP/1.1\r\nAccept: application/json;odata=minimalmetadata\r\nDataServiceVersion: 3.0\r\nIf-Match: *\r\n\r\n\r\n--changeset_fbfb938b-255b-4f1f-9816-f25a10fd6ea8\r\ncontent-type: application/http\r\ncontent-transfer-encoding: binary\r\n\r\nDELETE http://127.0.0.1:10002/devstoreaccount1/bft(PartitionKey='1',RowKey='dc2aea2d-65bf-4b18-9cf4-8d5c39e3c920Jtest') HTTP/1.1\r\nAccept: application/json;odata=minimalmetadata\r\nDataServiceVersion: 3.0\r\nIf-Match: *\r\n\r\n\r\n--changeset_fbfb938b-255b-4f1f-9816-f25a10fd6ea8\r\ncontent-type: application/http\r\ncontent-transfer-encoding: binary\r\n\r\nDELETE http://127.0.0.1:10002/devstoreaccount1/bft(PartitionKey='1',RowKey='e355da77-e28a-4006-a53f-160494c7b9fd''test') HTTP/1.1\r\nAccept: application/json;odata=minimalmetadata\r\nDataServiceVersion: 3.0\r\nIf-Match: *\r\n\r\n\r\n--changeset_fbfb938b-255b-4f1f-9816-f25a10fd6ea8\r\ncontent-type: application/http\r\ncontent-transfer-encoding: binary\r\n\r\nDELETE http://127.0.0.1:10002/devstoreaccount1/bft(PartitionKey='1',RowKey='e3692e10-b6e7-4144-9290-4f5de317e785%C3%A4test') HTTP/1.1\r\nAccept: application/json;odata=minimalmetadata\r\nDataServiceVersion: 3.0\r\nIf-Match: *\r\n\r\n\r\n--changeset_fbfb938b-255b-4f1f-9816-f25a10fd6ea8\r\ncontent-type: application/http\r\ncontent-transfer-encoding: binary\r\n\r\nDELETE http://127.0.0.1:10002/devstoreaccount1/bft(PartitionKey='1',RowKey='e3e8ab55-0a25-496f-ac9f-0581aa69dc1d%C3%B4test') HTTP/1.1\r\nAccept: application/json;odata=minimalmetadata\r\nDataServiceVersion: 3.0\r\nIf-Match: *\r\n\r\n\r\n--changeset_fbfb938b-255b-4f1f-9816-f25a10fd6ea8\r\ncontent-type: application/http\r\ncontent-transfer-encoding: binary\r\n\r\nDELETE http://127.0.0.1:10002/devstoreaccount1/bft(PartitionKey='1',RowKey='e5dd05be-30b6-4d3c-96a0-5b5629d5e1e7%C2%B3test') HTTP/1.1\r\nAccept: application/json;odata=minimalmetadata\r\nDataServiceVersion: 3.0\r\nIf-Match: *\r\n\r\n\r\n--changeset_fbfb938b-255b-4f1f-9816-f25a10fd6ea8--\r\n--batch_22432861-8132-4226-91b9-f4e5ba384e94--\r\n",
    "headers": {
      "accept": "application/json",
      "x-ms-version": "2019-02-02",
      "dataserviceversion": "3.0;",
      "maxdataserviceversion": "3.0;NetFx",
      "content-type": "multipart/mixed; boundary=batch_22432861-8132-4226-91b9-f4e5ba384e94",
      "accept-charset": "UTF-8",
      "connection": "Keep-Alive",
      "x-ms-date": "Tue, 01 Mar 2022 02:47:05 GMT",
      "content-length": "3664",
      "authorization": "SharedKeyLite devstoreaccount1:3C7WhtKw8Wq0gUcjFdL1iycmOVlV4wqvSUNbmg2F5jg=",
      "accept-encoding": "gzip,deflate",
      "user-agent": "Microsoft Azure Storage Explorer, 1.22.1, win32 core-rest-pipeline/1.3.3 Node/v14.16.0 OS/(ia32-Windows_NT-10.0.19043)",
      "x-ms-client-request-id": "2e6ecd3a-b470-4a72-bd95-ae20aeb1bc92"
    },
    "method": "POST",
    "timeout": 0,
    "disableKeepAlive": false,
    "withCredentials": false,
    "tracingOptions": {
      "spanOptions": {},
      "tracingContext": {
        "_currentContext": {}
      }
    },
    "requestId": "2e6ecd3a-b470-4a72-bd95-ae20aeb1bc92",
    "allowInsecureConnection": true
  },
  "response": {
    "status": 202,
    "headers": {
      "server": "Azurite-Table/3.14.2",
      "content-type": "multipart/mixed; boundary=batchresponse_22432861-8132-4226-91b9-f4e5ba384e94",
      "x-ms-request-id": "60b87ea1-714f-4988-8659-04b7cfa239a1",
      "x-ms-version": "2020-10-02",
      "date": "Tue, 01 Mar 2022 02:47:05 GMT",
      "connection": "keep-alive",
      "keep-alive": "timeout=5",
      "transfer-encoding": "chunked"
    },
    "request": {
      "url": "http://127.0.0.1:10002/devstoreaccount1/$batch",
      "body": "--batch_22432861-8132-4226-91b9-f4e5ba384e94\r\ncontent-type: multipart/mixed; boundary=changeset_fbfb938b-255b-4f1f-9816-f25a10fd6ea8\r\n\r\n\r\n--changeset_fbfb938b-255b-4f1f-9816-f25a10fd6ea8\r\ncontent-type: application/http\r\ncontent-transfer-encoding: binary\r\n\r\nDELETE http://127.0.0.1:10002/devstoreaccount1/bft(PartitionKey='1',RowKey='d96c7db1-c11a-4141-a512-289f4da5486emtest') HTTP/1.1\r\nAccept: application/json;odata=minimalmetadata\r\nDataServiceVersion: 3.0\r\nIf-Match: *\r\n\r\n\r\n--changeset_fbfb938b-255b-4f1f-9816-f25a10fd6ea8\r\ncontent-type: application/http\r\ncontent-transfer-encoding: binary\r\n\r\nDELETE http://127.0.0.1:10002/devstoreaccount1/bft(PartitionKey='1',RowKey='d9787eef-0a82-4fd3-aea3-68379cf28d87%C2%A7test') HTTP/1.1\r\nAccept: application/json;odata=minimalmetadata\r\nDataServiceVersion: 3.0\r\nIf-Match: *\r\n\r\n\r\n--changeset_fbfb938b-255b-4f1f-9816-f25a10fd6ea8\r\ncontent-type: application/http\r\ncontent-transfer-encoding: binary\r\n\r\nDELETE http://127.0.0.1:10002/devstoreaccount1/bft(PartitionKey='1',RowKey='d9aac488-f21d-4358-9806-a4793cf3c43a%C3%88test') HTTP/1.1\r\nAccept: application/json;odata=minimalmetadata\r\nDataServiceVersion: 3.0\r\nIf-Match: *\r\n\r\n\r\n--changeset_fbfb938b-255b-4f1f-9816-f25a10fd6ea8\r\ncontent-type: application/http\r\ncontent-transfer-encoding: binary\r\n\r\nDELETE http://127.0.0.1:10002/devstoreaccount1/bft(PartitionKey='1',RowKey='d9e32139-be4a-49ed-84d1-01c04be64834%C3%ACtest') HTTP/1.1\r\nAccept: application/json;odata=minimalmetadata\r\nDataServiceVersion: 3.0\r\nIf-Match: *\r\n\r\n\r\n--changeset_fbfb938b-255b-4f1f-9816-f25a10fd6ea8\r\ncontent-type: application/http\r\ncontent-transfer-encoding: binary\r\n\r\nDELETE http://127.0.0.1:10002/devstoreaccount1/bft(PartitionKey='1',RowKey='db927cda-90ac-47ec-9ff7-5c2413c941d1%C3%B7test') HTTP/1.1\r\nAccept: application/json;odata=minimalmetadata\r\nDataServiceVersion: 3.0\r\nIf-Match: *\r\n\r\n\r\n--changeset_fbfb938b-255b-4f1f-9816-f25a10fd6ea8\r\ncontent-type: application/http\r\ncontent-transfer-encoding: binary\r\n\r\nDELETE http://127.0.0.1:10002/devstoreaccount1/bft(PartitionKey='1',RowKey='dc2aea2d-65bf-4b18-9cf4-8d5c39e3c920Jtest') HTTP/1.1\r\nAccept: application/json;odata=minimalmetadata\r\nDataServiceVersion: 3.0\r\nIf-Match: *\r\n\r\n\r\n--changeset_fbfb938b-255b-4f1f-9816-f25a10fd6ea8\r\ncontent-type: application/http\r\ncontent-transfer-encoding: binary\r\n\r\nDELETE http://127.0.0.1:10002/devstoreaccount1/bft(PartitionKey='1',RowKey='e355da77-e28a-4006-a53f-160494c7b9fd''test') HTTP/1.1\r\nAccept: application/json;odata=minimalmetadata\r\nDataServiceVersion: 3.0\r\nIf-Match: *\r\n\r\n\r\n--changeset_fbfb938b-255b-4f1f-9816-f25a10fd6ea8\r\ncontent-type: application/http\r\ncontent-transfer-encoding: binary\r\n\r\nDELETE http://127.0.0.1:10002/devstoreaccount1/bft(PartitionKey='1',RowKey='e3692e10-b6e7-4144-9290-4f5de317e785%C3%A4test') HTTP/1.1\r\nAccept: application/json;odata=minimalmetadata\r\nDataServiceVersion: 3.0\r\nIf-Match: *\r\n\r\n\r\n--changeset_fbfb938b-255b-4f1f-9816-f25a10fd6ea8\r\ncontent-type: application/http\r\ncontent-transfer-encoding: binary\r\n\r\nDELETE http://127.0.0.1:10002/devstoreaccount1/bft(PartitionKey='1',RowKey='e3e8ab55-0a25-496f-ac9f-0581aa69dc1d%C3%B4test') HTTP/1.1\r\nAccept: application/json;odata=minimalmetadata\r\nDataServiceVersion: 3.0\r\nIf-Match: *\r\n\r\n\r\n--changeset_fbfb938b-255b-4f1f-9816-f25a10fd6ea8\r\ncontent-type: application/http\r\ncontent-transfer-encoding: binary\r\n\r\nDELETE http://127.0.0.1:10002/devstoreaccount1/bft(PartitionKey='1',RowKey='e5dd05be-30b6-4d3c-96a0-5b5629d5e1e7%C2%B3test') HTTP/1.1\r\nAccept: application/json;odata=minimalmetadata\r\nDataServiceVersion: 3.0\r\nIf-Match: *\r\n\r\n\r\n--changeset_fbfb938b-255b-4f1f-9816-f25a10fd6ea8--\r\n--batch_22432861-8132-4226-91b9-f4e5ba384e94--\r\n",
      "headers": {
        "accept": "application/json",
        "x-ms-version": "2019-02-02",
        "dataserviceversion": "3.0;",
        "maxdataserviceversion": "3.0;NetFx",
        "content-type": "multipart/mixed; boundary=batch_22432861-8132-4226-91b9-f4e5ba384e94",
        "accept-charset": "UTF-8",
        "connection": "Keep-Alive",
        "x-ms-date": "Tue, 01 Mar 2022 02:47:05 GMT",
        "content-length": "3664",
        "authorization": "SharedKeyLite devstoreaccount1:3C7WhtKw8Wq0gUcjFdL1iycmOVlV4wqvSUNbmg2F5jg=",
        "accept-encoding": "gzip,deflate",
        "user-agent": "Microsoft Azure Storage Explorer, 1.22.1, win32 core-rest-pipeline/1.3.3 Node/v14.16.0 OS/(ia32-Windows_NT-10.0.19043)",
        "x-ms-client-request-id": "2e6ecd3a-b470-4a72-bd95-ae20aeb1bc92"
      },
      "method": "POST",
      "timeout": 0,
      "disableKeepAlive": false,
      "withCredentials": false,
      "tracingOptions": {
        "spanOptions": {},
        "tracingContext": {
          "_currentContext": {}
        }
      },
      "requestId": "2e6ecd3a-b470-4a72-bd95-ae20aeb1bc92",
      "allowInsecureConnection": true
    },
    "bodyAsText": "--batchresponse_22432861-8132-4226-91b9-f4e5ba384e94\r\nContent-Type: multipart/mixed; boundary=changesetresponse_fbfb938b-255b-4f1f-9816-f25a10fd6ea8\r\n\r\n--changesetresponse_fbfb938b-255b-4f1f-9816-f25a10fd6ea8\r\nContent-Type: application/http\r\nContent-Transfer-Encoding: binary\r\n\r\nHTTP/1.1 400 Bad Request\r\nContent-ID: 7\r\nDataServiceVersion: 3.0;\r\nContent-Type: application/json;odata=minimalmetadata;charset=utf-8\r\n\r\n{\"odata.error\":{\"code\":\"ResourceNotFound\",\"message\":{\"lang\":\"en-US\",\"value\":\"The specified resource does not exist.\\nRequestId:60b87ea1-714f-4988-8659-04b7cfa239a1\\nTime:2022-03-01T02:47:05.417Z\"}}}\r\n\r\n--changesetresponse_fbfb938b-255b-4f1f-9816-f25a10fd6ea8--\r\n--batchresponse_22432861-8132-4226-91b9-f4e5ba384e94--\r\n"
  }
}
</Details>

**Comment by craxal** [comment]
@OzBob I assume you're using Azurite for your local emulator storage, yes? This definitely appears to be a problem with Azurite. We've opened https://github.com/Azure/Azurite/issues/1377 to track this issue.

**Comment by OzBob** [comment]
for tracking this issue https://github.com/Azure/Azurite/pull/1422 is now merged into Azurite
