### ISSUE TITLE
Allow reordering of queued items

### ISSUE THREAD

**Issue by kennypage** [microsoft/AzureStorageExplorer#5484]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Sometimes, when I have multiple items queued for upload/download my priorities change and I would prefer an item later in queue is processed before other queued items

### Desired Solution

I'd like to be able to reorder the items that are queued for processing, allowing me to adjust my most pressing transfer to occur first.  Ideally add a small drag handle to the left of the queued items for the most simple UX.

### Alternatives and Workarounds

At the moment, I have to cancel items that are earlier in the queue, then requeue them so they occur later

**Comment by kennypage** [comment]
<img width="277" alt="Screenshot 2022-03-01 at 08 54 17" src="https://user-images.githubusercontent.com/21378/156137513-c4554ce9-ba2a-4a22-b413-8d034d065ad6.png">

**Comment by rollsch** [comment]
Is it possible to not queue at all and download in parallel?

**Comment by JasonYeMSFT** [comment]
Let's investigate allowing concurrent execution of at least small size of AzCopy jobs in 1.34.0.
