### ISSUE TITLE
storage explorer error

### ISSUE THREAD

**Issue by timovp** [microsoft/AzureStorageExplorer#5486]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.22.0

### Architecture

x64

### Storage Explorer Build Number

20211211.10

### Platform

Windows

### OS Version

windows 10

### Bug Description

Unable to retrieve child resources.

Details:
{
  "name": "RestError",
  "message": "This request is not authorized to perform this operation.\nRequestId:169a6abd-801e-0126-56a3-2dc8e6000000\nTime:2022-03-01T19:32:57.1709083Z",
  "stack": "RestError: This request is not authorized to perform this operation.\nRequestId:169a6abd-801e-0126-56a3-2dc8e6000000\nTime:2022-03-01T19:32:57.1709083Z\n    at handleErrorResponse (C:\\Users\\xxxxxx\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:3148:19)\n    at C:\\Users\\xxxxxxxxx\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:3084:49\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async StorageRetryPolicy.attemptSendRequest (C:\\Users\\xxxxxxxx\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\storage-blob\\dist\\index.js:14086:24)\n    at async StorageClientContext.sendOperationRequest (C:\\Users\\xxxxxx\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:4695:31)\n    at async BlobServiceClient.listContainersSegment (C:\\Users\\xxxxx\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\storage-blob\\dist\\index.js:23132:20)",
  "code": "AuthorizationFailure",
  "statusCode": 403,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://xxxxxxxx.blob.core.windows.net/?comp=list&include=metadata",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2020-10-02"
        },
        "accept": {
          "name": "Accept",
          "value": "application/xml"
        },
        "user-agent": {
          "name": "User-Agent",
          "value": "Microsoft Azure Storage Explorer, 1.22.0, win32 azsdk-js-storageblob/12.8.0 (NODE-VERSION v14.16.0; Windows_NT 10.0.19042)"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "xxxxxxx"
        },
        "x-ms-date": {
          "name": "x-ms-date",
          "value": "Tue, 01 Mar 2022 19:32:57 GMT"
        },
        "authorization": {
          "name": "Authorization",
          "value": "Signed SharedKey Redacted="
        },
        "cookie": {
          "name": "Cookie",
          "value": ""
        }
      }
    },
    "withCredentials": false,
    "timeout": 0,
    "keepAlive": true,
    "decompressResponse": false,
    "requestId": "xxxxxx",
    "operationSpec": {
      "path": "/",
      "httpMethod": "GET",
      "responses": {
        "200": {
          "bodyMapper": {
            "serializedName": "ListContainersSegmentResponse",
            "xmlName": "EnumerationResults",
            "type": {
              "name": "Composite",
              "className": "ListContainersSegmentResponse",
              "modelProperties": {
                "serviceEndpoint": {
                  "serializedName": "ServiceEndpoint",
                  "required": true,
                  "xmlName": "ServiceEndpoint",
                  "xmlIsAttribute": true,
                  "type": {
                    "name": "String"
                  }
                },
                "prefix": {
                  "serializedName": "Prefix",
                  "xmlName": "Prefix",
                  "type": {
                    "name": "String"
                  }
                },
                "marker": {
                  "serializedName": "Marker",
                  "xmlName": "Marker",
                  "type": {
                    "name": "String"
                  }
                },
                "maxPageSize": {
                  "serializedName": "MaxResults",
                  "xmlName": "MaxResults",
                  "type": {
                    "name": "Number"
                  }
                },
                "containerItems": {
                  "serializedName": "ContainerItems",
                  "required": true,
                  "xmlName": "Containers",
                  "xmlIsWrapped": true,
                  "xmlElementName": "Container",
                  "type": {
                    "name": "Sequence",
                    "element": {
                      "type": {
                        "name": "Composite",
                        "className": "ContainerItem"
                      }
                    }
                  }

### Steps to Reproduce

connecting to blobstorage

### Actual Experience

the error. 

### Expected Experience

connection to blob storage and see contaners. There might be network restrictions, but these should be lifted due to whitelisted ipadresses for the storage account network settings in azure portal networksettings.

**Comment by MRayermannMSFT** [comment]
@timovp given that you are using a name and key, I think likely this is a storage firewall/vnet issue. Your best bet for resolving such issues is opening an Azure support ticket.

**Comment by timovp** [comment]
Thanks! Vnet it was indeed
