### ISSUE TITLE
The copied 'Archive' blob shows well on destination container after copying the belonging blob container to another account

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#549]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180808.1
**Commit**: 93925d3c
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Expand one GPV2 account -> Create a blob container then upload a blob file to it.
2. Change the current default access tier to Archive for the uploaded blob.
3. Copy the created blob container to another account.

#### Expected Experience: ####
Fail to copy the Archive blob to another account with an error like 'Archive blob not support the operation'.

#### Actual Experience: ####
The Archive blob can be copied successfully to anther account with the below error.
![zrchive](https://user-images.githubusercontent.com/34729022/43826839-db2e45e4-9ae7-11e8-93d4-766445ef03cb.png)

**Comment by v-xianya** [comment]
Verified on build 20190108.2. This issue doesn't reproduce. Could you help to resolve it?

**Comment by jinglouMSFT** [comment]
Closing.
