### ISSUE TITLE
Unable to create a directory under dts/Partners

### ISSUE THREAD

**Issue by calichte** [microsoft/AzureStorageExplorer#5490]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.17.0

### Architecture

i86

### Storage Explorer Build Number

20201211.10

### Platform

Windows

### Bug Description

I was trying to create a directory for one of our vendors under dts/Partners but was unable to. I had been able to make directories in the past at this location.

I got the following error:

{
  "name": "Error",
  "message": "This request is not authorized to perform this operation using this permission.\nRequestId:8d78470c-701f-0063-5764-2ea3a6000000\nTime:2022-03-02T18:34:19.3025118Z",
  "stack": "Error: This request is not authorized to perform this operation using this permission.\nRequestId:8d78470c-701f-0063-5764-2ea3a6000000\nTime:2022-03-02T18:34:19.3025118Z\n    at new RestError (C:\\Users\\calichte\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\ms-rest-js\\dist\\msRest.node.js:2400:28)\n    at C:\\Users\\calichte\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\ms-rest-js\\dist\\msRest.node.js:3544:37\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
  "code": "AuthorizationPermissionMismatch",
  "statusCode": 403,
  "request": {
    "streamResponseBody": false,
    "url": "https://hwswshare.dfs.core.windows.net/dts/Partners%2FLiteOn?resource=directory&timeout=60",
    "method": "PUT",
    "headers": {
      "_headersMap": {
        "content-type": {
          "name": "content-type",
          "value": "application/json; charset=utf-8"
        },
        "if-none-match": {
          "name": "if-none-match",
          "value": "*"
        },
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2018-11-09"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "e4c92dd2-b50d-4cbf-a02e-3e0c11dd2503"
        },
        "user-agent": {
          "name": "user-agent",
          "value": "Microsoft Azure Storage Explorer, 1.17.0, win32,  Azure-Storage/12.2.0-preview (NODE-VERSION v12.13.0; Windows_NT 10.0.19043)"
        },
        "cookie": {
          "name": "cookie",
          "value": ""
        }
      }
    },
    "withCredentials": false,
    "abortSignal": {
      "onabort": null,
      "_aborted": false,
      "children": [],
      "abortEventListeners": [
        null
      ]
    },
    "timeout": 0,
    "operationSpec": {
      "httpMethod": "PUT",
      "path": "{filesystem}/{path}",
      "urlParameters": [
        {
          "parameterPath": "accountName",
          "mapper": {
            "required": true,
            "serializedName": "accountName",
            "defaultValue": "",
            "type": {
              "name": "String"
            }
          },
          "skipEncoding": true
        },
        {
          "parameterPath": "dnsSuffix",
          "mapper": {
            "required": true,
            "serializedName": "dnsSuffix",
            "defaultValue": "dfs.core.windows.net",
            "type": {
              "name": "String"
            }
          },
          "skipEncoding": true
        },
        {
          "parameterPath": "filesystem",
          "mapper": {
            "required": true,
            "serializedName": "filesystem",
            "constraints": {
              "MaxLength": 63,
              "MinLength": 3,
              "Pattern": {}
            },
            "type": {
              "name": "String"
            }
          }
        },
        {
          "parameterPath": "path",
          "mapper": {
            "required": true,
            "serializedName": "path",
            "type": {
              "name": "String"
            }
          }
        }
      ],
      "queryParameters": [
        {
          "parameterPath": [
            "options",
            "resource"
          ],
          "mapper": {
            "serializedName": "resource",
            "type": {
              "name": "Enum",
              "allowedValues": [
                "directory",
                "file"
              ]
            }
          }
        },
        {
          "parameterPath": [
            "options",
            "continuation"
          ],
          "mapper": {
            "serializedName": "continuation",
            "type": {
              "name": "String"
            }
          }
        },
        {
          "parameterPath": [
            "options",
            "mode"
          ],
          "mapper": {
            "serializedName": "mode",
            "type": {
              "name": "Enum",
              "allowedValues": [
                "legacy",
                "posix"
              ]
            }
          }
        },
        {
          "parameterPath": [
            "options",
            "timeout"
          ],
          "mapper": {
            "serializedName": "timeout",
            "constraints": {
              "InclusiveMinimum": 1
            },
            "type": {
              "name": "Number"
            }
          }
        }
      ],
      "headerParameters": [
        {
          "parameterPath": [
            "options",
            "cacheControl"
          ],
          "mapper": {
            "serializedName": "Cache-Control",
            "type": {
              "name": "String"
            }
          }
        },
        {
          "parameterPath": [
            "options",
            "contentEncoding"
          ],
          "mapper": {
            "serializedName": "Content-Encoding",
            "type": {
              "name": "String"
            }
          }
        },
        {
          "parameterPath": [
            "options",
            "contentLanguage"
          ],
          "mapper": {
            "serializedName": "Content-Language",
            "type": {
              "name": "String"
            }
          }
        },
        {
          "parameterPath": [
            "options",
            "contentDisposition"
          ],
          "mapper": {
            "serializedName": "Content-Disposition",
            "type": {
              "name": "String"
            }
          }
        },
        {
          "parameterPath": [
            "options",
            "xMsCacheControl"
          ],
          "mapper": {
            "serializedName": "x-ms-cache-control",
            "type": {
              "name": "String"
            }
          }
        },
        {
          "parameterPath": [
            "options",
            "xMsContentType"
          ],
          "mapper": {
            "serializedName": "x-ms-content-type",
            "type": {
              "name": "String"
            }
          }
        },
        {
          "parameterPath": [
            "options",
            "xMsContentEncoding"
          ],
          "mapper": {
            "serializedName": "x-ms-content-encoding",
            "type": {
              "name": "String"
            }
          }
        },
        {
          "parameterPath": [
            "options",
            "xMsContentLanguage"
          ],
          "mapper": {
            "serializedName": "x-ms-content-language",
            "type": {
              "name": "String"
            }
          }
        },
        {
          "parameterPath": [
            "options",
            "xMsContentDisposition"
          ],
          "mapper": {
            "serializedName": "x-ms-content-disposition",
            "type": {
              "name": "String"
            }
          }
        },
        {
          "parameterPath": [
            "options",
            "xMsRenameSource"
          ],
          "mapper": {
            "serializedName": "x-ms-rename-source",
            "type": {
              "name": "String"
            }
          }
        },
        {
          "parameterPath": [
            "options",
            "xMsLeaseId"
          ],
          "mapper": {
            "serializedName": "x-ms-lease-id",
            "constraints": {
              "Pattern": {}
            },
            "type": {
              "name": "String"
            }
          }
        },
        {
          "parameterPath": [
            "options",
            "xMsSourceLeaseId"
          ],
          "mapper": {
            "serializedName": "x-ms-source-lease-id",
            "constraints": {
              "Pattern": {}
            },
            "type": {
              "name": "String"
            }
          }
        },
        {
          "parameterPath": [
            "options",
            "xMsProperties"
          ],
          "mapper": {
            "serializedName": "x-ms-properties",
            "type": {
              "name": "String"
            }
          }
        },
        {
          "parameterPath": [
            "options",
            "xMsPermissions"
          ],
          "mapper": {
            "serializedName": "x-ms-permissions",
            "type": {
              "name": "String"
            }
          }
        },
        {
          "parameterPath": [
            "options",
            "xMsUmask"
          ],
          "mapper": {
            "serializedName": "x-ms-umask",
            "type": {
              "name": "String"
            }
          }
        },
        {
          "parameterPath": [
            "options",
            "ifMatch"
          ],
          "mapper": {
            "serializedName": "If-Match",
            "type": {
              "name": "String"
            }
          }
        },
        {
          "parameterPath": [
            "options",
            "ifNoneMatch"
          ],
          "mapper": {
            "serializedName": "If-None-Match",
            "type": {
              "name": "String"
            }
          }
        },
        {
          "parameterPath": [
            "options",
            "ifModifiedSince"
          ],
          "mapper": {
            "serializedName": "If-Modified-Since",
            "type": {
              "name": "String"
            }
          }
        },
        {
          "parameterPath": [
            "options",
            "ifUnmodifiedSince"
          ],
          "mapper": {
            "serializedName": "If-Unmodified-Since",
            "type": {
              "name": "String"
            }
          }
        },
        {
          "parameterPath": [
            "options",
            "xMsSourceIfMatch"
          ],
          "mapper": {
            "serializedName": "x-ms-source-if-match",
            "type": {
              "name": "String"
            }
          }
        },
        {
          "parameterPath": [
            "options",
            "xMsSourceIfNoneMatch"
          ],
          "mapper": {
            "serializedName": "x-ms-source-if-none-match",
            "type": {
              "name": "String"
            }
          }
        },
        {
          "parameterPath": [
            "options",
            "xMsSourceIfModifiedSince"
          ],
          "mapper": {
            "serializedName": "x-ms-source-if-modified-since",
            "type": {
              "name": "String"
            }
          }
        },
        {
          "parameterPath": [
            "options",
            "xMsSourceIfUnmodifiedSince"
          ],
          "mapper": {
            "serializedName": "x-ms-source-if-unmodified-since",
            "type": {
              "name": "String"
            }
          }
        },
        {
          "parameterPath": [
            "options",
            "xMsClientRequestId"
          ],
          "mapper": {
            "serializedName": "x-ms-client-request-id",
            "constraints": {
              "Pattern": {}
            },
            "type": {
              "name": "String"
            }
          }
        },
        {
          "parameterPath": [
            "options",
            "xMsDate"
          ],
          "mapper": {
            "serializedName": "x-ms-date",
            "type": {
              "name": "String"
            }
          }
        },
        {
          "parameterPath": "xMsVersion",
          "mapper": {
            "serializedName": "x-ms-version",
            "type": {
              "name": "String"
            }
          }
        }
      ],
      "responses": {
        "201": {
          "headersMapper": {
            "serializedName": "path-create-headers",
            "type": {
              "name": "Composite",
              "className": "PathCreateHeaders",
              "modelProperties": {
                "date": {
                  "serializedName": "date",
                  "type": {
                    "name": "String"
                  }
                },
                "eTag": {
                  "serializedName": "etag",
                  "type": {
                    "name": "String"
                  }
                },
                "lastModified": {
                  "serializedName": "last-modified",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsRequestId": {
                  "serializedName": "x-ms-request-id",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsVersion": {
                  "serializedName": "x-ms-version",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsContinuation": {
                  "serializedName": "x-ms-continuation",
                  "type": {
                    "name": "String"
                  }
                },
                "contentLength": {
                  "serializedName": "content-length",
                  "type": {
                    "name": "Number"
                  }
                }
              }
            }
          }
        },
        "default": {
          "bodyMapper": {
            "serializedName": "DataLakeStorageError",
            "type": {
              "name": "Composite",
              "className": "DataLakeStorageError",
              "modelProperties": {
                "error": {
                  "serializedName": "error",
                  "type": {
                    "name": "Composite",
                    "className": "DataLakeStorageErrorError"
                  }
                }
              }
            }
          }
        }
      },
      "serializer": {
        "modelMappers": {
          "DataLakeStorageError": {
            "serializedName": "DataLakeStorageError",
            "type": {
              "name": "Composite",
              "className": "DataLakeStorageError",
              "modelProperties": {
                "error": {
                  "serializedName": "error",
                  "type": {
                    "name": "Composite",
                    "className": "DataLakeStorageErrorError"
                  }
                }
              }
            }
          },
          "DataLakeStorageErrorError": {
            "serializedName": "DataLakeStorageError_error",
            "type": {
              "name": "Composite",
              "className": "DataLakeStorageErrorError",
              "modelProperties": {
                "code": {
                  "serializedName": "code",
                  "type": {
                    "name": "String"
                  }
                },
                "message": {
                  "serializedName": "message",
                  "type": {
                    "name": "String"
                  }
                }
              }
            }
          },
          "Path": {
            "serializedName": "Path",
            "type": {
              "name": "Composite",
              "className": "Path",
              "modelProperties": {
                "name": {
                  "serializedName": "name",
                  "type": {
                    "name": "String"
                  }
                },
                "isDirectory": {
                  "serializedName": "isDirectory",
                  "defaultValue": false,
                  "type": {
                    "name": "Boolean"
                  }
                },
                "lastModified": {
                  "serializedName": "lastModified",
                  "type": {
                    "name": "String"
                  }
                },
                "eTag": {
                  "serializedName": "eTag",
                  "type": {
                    "name": "String"
                  }
                },
                "contentLength": {
                  "serializedName": "contentLength",
                  "type": {
                    "name": "Number"
                  }
                },
                "owner": {
                  "serializedName": "owner",
                  "type": {
                    "name": "String"
                  }
                },
                "group": {
                  "serializedName": "group",
                  "type": {
                    "name": "String"
                  }
                },
                "permissions": {
                  "serializedName": "permissions",
                  "type": {
                    "name": "String"
                  }
                }
              }
            }
          },
          "PathCreateHeaders": {
            "serializedName": "path-create-headers",
            "type": {
              "name": "Composite",
              "className": "PathCreateHeaders",
              "modelProperties": {
                "date": {
                  "serializedName": "date",
                  "type": {
                    "name": "String"
                  }
                },
                "eTag": {
                  "serializedName": "etag",
                  "type": {
                    "name": "String"
                  }
                },
                "lastModified": {
                  "serializedName": "last-modified",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsRequestId": {
                  "serializedName": "x-ms-request-id",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsVersion": {
                  "serializedName": "x-ms-version",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsContinuation": {
                  "serializedName": "x-ms-continuation",
                  "type": {
                    "name": "String"
                  }
                },
                "contentLength": {
                  "serializedName": "content-length",
                  "type": {
                    "name": "Number"
                  }
                }
              }
            }
          },
          "PathDeleteHeaders": {
            "serializedName": "path-delete-headers",
            "type": {
              "name": "Composite",
              "className": "PathDeleteHeaders",
              "modelProperties": {
                "date": {
                  "serializedName": "date",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsRequestId": {
                  "serializedName": "x-ms-request-id",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsVersion": {
                  "serializedName": "x-ms-version",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsContinuation": {
                  "serializedName": "x-ms-continuation",
                  "type": {
                    "name": "String"
                  }
                }
              }
            }
          },
          "PathGetPropertiesHeaders": {
            "serializedName": "path-getproperties-headers",
            "type": {
              "name": "Composite",
              "className": "PathGetPropertiesHeaders",
              "modelProperties": {
                "acceptRanges": {
                  "serializedName": "accept-ranges",
                  "type": {
                    "name": "String"
                  }
                },
                "cacheControl": {
                  "serializedName": "cache-control",
                  "type": {
                    "name": "String"
                  }
                },
                "contentDisposition": {
                  "serializedName": "content-disposition",
                  "type": {
                    "name": "String"
                  }
                },
                "contentEncoding": {
                  "serializedName": "content-encoding",
                  "type": {
                    "name": "String"
                  }
                },
                "contentLanguage": {
                  "serializedName": "content-language",
                  "type": {
                    "name": "String"
                  }
                },
                "contentLength": {
                  "serializedName": "content-length",
                  "type": {
                    "name": "Number"
                  }
                },
                "contentRange": {
                  "serializedName": "content-range",
                  "type": {
                    "name": "String"
                  }
                },
                "contentType": {
                  "serializedName": "content-type",
                  "type": {
                    "name": "String"
                  }
                },
                "date": {
                  "serializedName": "date",
                  "type": {
                    "name": "String"
                  }
                },
                "eTag": {
                  "serializedName": "etag",
                  "type": {
                    "name": "String"
                  }
                },
                "lastModified": {
                  "serializedName": "last-modified",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsRequestId": {
                  "serializedName": "x-ms-request-id",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsVersion": {
                  "serializedName": "x-ms-version",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsResourceType": {
                  "serializedName": "x-ms-resource-type",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsProperties": {
                  "serializedName": "x-ms-properties",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsOwner": {
                  "serializedName": "x-ms-owner",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsGroup": {
                  "serializedName": "x-ms-group",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsPermissions": {
                  "serializedName": "x-ms-permissions",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsAcl": {
                  "serializedName": "x-ms-acl",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsLeaseDuration": {
                  "serializedName": "x-ms-lease-duration",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsLeaseState": {
                  "serializedName": "x-ms-lease-state",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsLeaseStatus": {
                  "serializedName": "x-ms-lease-status",
                  "type": {
                    "name": "String"
                  }
                }
              }
            }
          },
          "PathLeaseHeaders": {
            "serializedName": "path-lease-headers",
            "type": {
              "name": "Composite",
              "className": "PathLeaseHeaders",
              "modelProperties": {
                "date": {
                  "serializedName": "date",
                  "type": {
                    "name": "String"
                  }
                },
                "eTag": {
                  "serializedName": "etag",
                  "type": {
                    "name": "String"
                  }
                },
                "lastModified": {
                  "serializedName": "last-modified",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsRequestId": {
                  "serializedName": "x-ms-request-id",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsVersion": {
                  "serializedName": "x-ms-version",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsLeaseId": {
                  "serializedName": "x-ms-lease-id",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsLeaseTime": {
                  "serializedName": "x-ms-lease-time",
                  "type": {
                    "name": "String"
                  }
                }
              }
            }
          },
          "PathList": {
            "serializedName": "PathList",
            "type": {
              "name": "Composite",
              "className": "PathList",
              "modelProperties": {
                "paths": {
                  "serializedName": "paths",
                  "type": {
                    "name": "Sequence",
                    "element": {
                      "type": {
                        "name": "Composite",
                        "className": "Path"
                      }
                    }
                  }
                }
              }
            }
          },
          "PathListHeaders": {
            "serializedName": "path-list-headers",
            "type": {
              "name": "Composite",
              "className": "PathListHeaders",
              "modelProperties": {
                "date": {
                  "serializedName": "date",
                  "type": {
                    "name": "String"
                  }
                },
                "eTag": {
                  "serializedName": "etag",
                  "type": {
                    "name": "String"
                  }
                },
                "lastModified": {
                  "serializedName": "last-modified",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsRequestId": {
                  "serializedName": "x-ms-request-id",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsVersion": {
                  "serializedName": "x-ms-version",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsContinuation": {
                  "serializedName": "x-ms-continuation",
                  "type": {
                    "name": "String"
                  }
                }
              }
            }
          },
          "PathReadHeaders": {
            "serializedName": "path-read-headers",
            "type": {
              "name": "Composite",
              "className": "PathReadHeaders",
              "modelProperties": {
                "acceptRanges": {
                  "serializedName": "accept-ranges",
                  "type": {
                    "name": "String"
                  }
                },
                "cacheControl": {
                  "serializedName": "cache-control",
                  "type": {
                    "name": "String"
                  }
                },
                "contentDisposition": {
                  "serializedName": "content-disposition",
                  "type": {
                    "name": "String"
                  }
                },
                "contentEncoding": {
                  "serializedName": "content-encoding",
                  "type": {
                    "name": "String"
                  }
                },
                "contentLanguage": {
                  "serializedName": "content-language",
                  "type": {
                    "name": "String"
                  }
                },
                "contentLength": {
                  "serializedName": "content-length",
                  "type": {
                    "name": "Number"
                  }
                },
                "contentRange": {
                  "serializedName": "content-range",
                  "type": {
                    "name": "String"
                  }
                },
                "contentType": {
                  "serializedName": "content-type",
                  "type": {
                    "name": "String"
                  }
                },
                "date": {
                  "serializedName": "date",
                  "type": {
                    "name": "String"
                  }
                },
                "eTag": {
                  "serializedName": "etag",
                  "type": {
                    "name": "String"
                  }
                },
                "lastModified": {
                  "serializedName": "last-modified",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsRequestId": {
                  "serializedName": "x-ms-request-id",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsVersion": {
                  "serializedName": "x-ms-version",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsResourceType": {
                  "serializedName": "x-ms-resource-type",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsProperties": {
                  "serializedName": "x-ms-properties",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsLeaseDuration": {
                  "serializedName": "x-ms-lease-duration",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsLeaseState": {
                  "serializedName": "x-ms-lease-state",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsLeaseStatus": {
                  "serializedName": "x-ms-lease-status",
                  "type": {
                    "name": "String"
                  }
                }
              }
            }
          },
          "PathUpdateHeaders": {
            "serializedName": "path-update-headers",
            "type": {
              "name": "Composite",
              "className": "PathUpdateHeaders",
              "modelProperties": {
                "date": {
                  "serializedName": "date",
                  "type": {
                    "name": "String"
                  }
                },
                "eTag": {
                  "serializedName": "etag",
                  "type": {
                    "name": "String"
                  }
                },
                "lastModified": {
                  "serializedName": "last-modified",
                  "type": {
                    "name": "String"
                  }
                },
                "acceptRanges": {
                  "serializedName": "accept-ranges",
                  "type": {
                    "name": "String"
                  }
                },
                "cacheControl": {
                  "serializedName": "cache-control",
                  "type": {
                    "name": "String"
                  }
                },
                "contentDisposition": {
                  "serializedName": "content-disposition",
                  "type": {
                    "name": "String"
                  }
                },
                "contentEncoding": {
                  "serializedName": "content-encoding",
                  "type": {
                    "name": "String"
                  }
                },
                "contentLanguage": {
                  "serializedName": "content-language",
                  "type": {
                    "name": "String"
                  }
                },
                "contentLength": {
                  "serializedName": "content-length",
                  "type": {
                    "name": "Number"
                  }
                },
                "contentRange": {
                  "serializedName": "content-range",
                  "type": {
                    "name": "String"
                  }
                },
                "contentType": {
                  "serializedName": "content-type",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsProperties": {
                  "serializedName": "x-ms-properties",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsRequestId": {
                  "serializedName": "x-ms-request-id",
                  "type": {
                    "name": "String"
                  }
                },
                "xMsVersion": {
                  "serializedName": "x-ms-version",
                  "type": {
                    "name": "String"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "response": {
    "body": "{\"error\":{\"code\":\"AuthorizationPermissionMismatch\",\"message\":\"This request is not authorized to perform this operation using this permission.\\nRequestId:8d78470c-701f-0063-5764-2ea3a6000000\\nTime:2022-03-02T18:34:19.3025118Z\"}}",
    "headers": {
      "_headersMap": {
        "connection": {
          "name": "connection",
          "value": "close"
        },
        "content-length": {
          "name": "content-length",
          "value": "227"
        },
        "content-type": {
          "name": "content-type",
          "value": "application/json;charset=utf-8"
        },
        "date": {
          "name": "date",
          "value": "Wed, 02 Mar 2022 18:34:18 GMT"
        },
        "server": {
          "name": "server",
          "value": "Windows-Azure-HDFS/1.0 Microsoft-HTTPAPI/2.0"
        },
        "x-ms-error-code": {
          "name": "x-ms-error-code",
          "value": "AuthorizationPermissionMismatch"
        },
        "x-ms-request-id": {
          "name": "x-ms-request-id",
          "value": "8d78470c-701f-0063-5764-2ea3a6000000"
        },
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2018-11-09"
        }
      }
    },
    "status": 403
  },
  "body": {
    "error": {
      "code": "AuthorizationPermissionMismatch",
      "message": "This request is not authorized to perform this operation using this permission.\nRequestId:8d78470c-701f-0063-5764-2ea3a6000000\nTime:2022-03-02T18:34:19.3025118Z"
    }
  }
}

### Steps to Reproduce

1. Launch explorer
2. Go to dts/Partners
3. Click New Folder
4. ASE informs me it failed to make a new folder

### Actual Experience

![image](https://user-images.githubusercontent.com/100797989/156427868-c24549e6-8d19-4822-9c00-ae28c1c86f93.png)

**Comment by JasonYeMSFT** [comment]
@calichte Could you go to Portal to check if you still have the rbac role granting you access to this blob container?

**Comment by calichte** [comment]
@JasonYeMSFT - Do you have a link to that location?

**Comment by JasonYeMSFT** [comment]
@calichte You can go to portal.azure.com, sign in to your azure account and look for all resources. If you have the owner role, you should be able to see the subscription and the storage account the container is in. Then you can go to the "Access Control (IAM)" in the left navigation blade and click on "Role Assignments" on the right-hand side to see which roles are assigned to you.

If you are not the owner of the resource (the subscription and the storage account the container is in), you will need to contact the owner who give you access to the resource to verify if you still have access to it.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem we recommend opening an Azure support ticket via the portal.
