### ISSUE TITLE
The context menu of tables is not localized

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5492]
**Storage Explorer Version:** 1.24.0-dev
**Build Number:** 20220303.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.1 (Apple M1 Pro)
**Architecture:** ia32\x64
**Language:** All languages
**How Found:** From running test cases
**Regression From:** Previous release (1.22.1)

## Steps to Reproduce ##

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Español' -> Restart Storage Explorer.
3. Expand one storage account -> Tables.
4. Create a table -> Right click the table.
5. Check whether the context menu is localized.

## Expected Experience ##
The context menu is localized.
![image](https://user-images.githubusercontent.com/87792676/156510559-ad2cd8c8-808e-4d12-a6e9-1918387fadc6.png)

## Actual Experience ##
The context menu is not localized.
![image](https://user-images.githubusercontent.com/87792676/156510970-0791c157-a333-4741-ade7-db5c17f35c37.png)

**Comment by craxal** [comment]
Several resource files were missing from the loc project, so the loc team wasn't picking up the changes.

**Comment by craxal** [comment]
The new strings were only merged a few days ago. We need to create a new package version.

**Comment by v-xianya** [comment]
Will verify the localization issue when we do localization testing.

**Comment by v-xianya** [comment]
Verified this issue on the build rel\1.24.0 20220420.3.
On the language 'Portuguese(Brazil)', the action item 'Clone...' is not localized.
<img width="402" alt="Screen Shot 2022-04-19 at 19 32 56" src="https://user-images.githubusercontent.com/41351993/164135415-dd81569b-09e7-427f-9e29-9a5fbf9fa7a9.png">

**Comment by craxal** [comment]
The string still hasn't been translated for Portuguese (Brazil). We just need to wait for a translation update.

**Comment by craxal** [comment]
This appears to be fixed now. I am seeing translated strings for Spanish and Portuguese.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220613.1. Still reproduces on Portuguese (Brazil). 
So we are going to reopen it.
![image](https://user-images.githubusercontent.com/41351993/173265431-058af96b-28ca-440a-a53f-dbfa57f030c0.png)

**Comment by craxal** [comment]
@v-xianya "Clone" in Portuguese is "Clone". This is translated correctly.
