### ISSUE TITLE
The context menu of 'Tables' node is not localized completely

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5493]
**Storage Explorer Version:** 1.24.0-dev
**Build Number:** 20220303.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.1 (Apple M1 Pro)
**Architecture:** ia32\x64
**Language:** All languages
**How Found:** From running test cases
**Regression From:** Previous release (1.22.1)

## Steps to Reproduce ##

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Español' -> Restart Storage Explorer.
3. Expand one storage account -> Tables.
4. Right click 'Tables' node.
5. Check whether the context menu is localized completely.

## Expected Experience ##
The context menu is localized completely.
 ![image](https://user-images.githubusercontent.com/87792676/156509727-089aa0bf-3b1f-4b07-bf7a-4c9ffbef539f.png)

## Actual Experience ##
The context menu is not localized completely.
![image](https://user-images.githubusercontent.com/87792676/156509619-7adee2ee-f5f3-46d3-8fd9-6c63c51457f0.png)

**Comment by v-xianya** [comment]
This issue still reproduces on the build main/20220411.5.

**Comment by craxal** [comment]
The new strings were only merged a few days ago. We need to create a new package version.

**Comment by v-xianya** [comment]
Will verify the localization issue when we do localization testing.

**Comment by v-xianya** [comment]
Verified this issue on the build rel/1.24.0 20220420.3.
There is a new added string 'Open Table by Name...' is not localized.
@craxal Do we need to open a new issue for this?
<img width="266" alt="Screen Shot 2022-04-19 at 19 22 34" src="https://user-images.githubusercontent.com/41351993/164134284-ca5519e2-61b0-44a9-9922-d2f9d89a9af2.png">

**Comment by craxal** [comment]
No, we don't need to open a new issue. we already have this bug. The string is already translated and being referenced correctly, so we probably just need to update the package again. We're not going to worry about that for a release.

**Comment by v-xianya** [comment]
Got it, thank you for the response!

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220506.1. Fixed.
