### ISSUE TITLE
The error dialog is not localized when creating one table with an invalid name

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5494]
**Storage Explorer Version:** 1.24.0-dev
**Build Number:** 20220303.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.1 (Apple M1 Pro)
**Architecture:** ia32\x64
**Language:** All languages
**How Found:** From running test cases
**Regression From:** Previous release (1.22.1)

## Steps to Reproduce ##

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Español' -> Restart Storage Explorer.
3. Expand one storage account -> Tables.
4. Right click 'Tables' node -> Click 'Create Table'.
5. Input an invalid table name -> Type enter.
6. An error dialog pops up -> Check whether the error dialog is localized.

## Expected Experience ##
The error dialog is localized.
![image](https://user-images.githubusercontent.com/87792676/156511762-8bc97be1-f3b8-404f-a54d-93b77f5caa79.png)

## Actual Experience ##
The error dialog is not localized.
![image](https://user-images.githubusercontent.com/87792676/156511641-7d9ba781-f852-4513-a150-81faf9462461.png)

## Additional Context ##
The error message is also not localized when hovering over the text input.
![image](https://user-images.githubusercontent.com/87792676/156512930-efe62414-c5dd-45f8-89ec-c5ef3b136c33.png)

**Comment by craxal** [comment]
The new strings were only merged a few days ago. We need to create a new package version.

**Comment by v-xianya** [comment]
Will verify the localization issue when we do localization testing.

**Comment by v-xianya** [comment]
Verified this issue on the build rel/1.24.0 20220420.3. Fixed.
