### ISSUE TITLE
The content in the 'Change Default Access Tier' is not localized

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5495]
**Storage Explorer Version**: 1.24.0-dev
**Build Number**: 20220303.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.1(Apple M1 Pro)
**Reproduce Language**: All Languages
**Architecture** ia32\x64
**How Found**: From running test cases
**Regression From**: Previous release (1.23.0)

## Steps to Reproduce ##
1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select 'Español' -> Restart Storage Explorer.
3. Right click one storage account -> Click localized 'Set Default Access Tier...'.
4. Check whether the content in the 'Change Default Access Tier' dialog is localized or not.

## Expected Experience ##
The content in the 'Change Default Access Tier' is localized.
![image](https://user-images.githubusercontent.com/41351993/156514644-412c41cb-0002-4ed2-9169-515f94b42adb.png)

## Actual Experience ##
The content in the 'Change Default Access Tier' is not localized.

![image](https://user-images.githubusercontent.com/41351993/156516001-00a64c4a-6dd4-4336-acf5-998702fc4491.png)

## Additional Context ##
The ENU screenshot in 1.23.0:
![image](https://user-images.githubusercontent.com/41351993/156515536-78dfdd4d-7dfe-485c-9364-257fadad1045.png)

**Comment by MRayermannMSFT** [comment]
A result of work I am doing. I will keep an eye on this.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220401.7. Fixed.
![image](https://user-images.githubusercontent.com/87792676/161373206-f883f5f4-91e5-4654-863a-5c8d986e2ce1.png)
