### ISSUE TITLE
The localized strings 'Collapse All' and 'Refresh All' overlap if narrowing the EXPLORER panel

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5499]
**Storage Explorer Version**: 1.24.0-dev
**Build Number**: 20220303.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.1 (Apple M1 Pro)
**Reproduce Languages**: Russian/Portuguese/Polish/Dutch/Japanese/Italian/Hungarian/French/Spanish/German/Czech
**Architecture**: ia32/x64
**How Found**: exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select 'Español' -> Restart Storage Explorer.
3. Switch to 'EXPLORER' panel -> Narrow the EXPLORER panel.
4. Check the localized strings 'Collapse All' and 'Refresh All' do not overlap.

## Expected Experience ##
The localized strings 'Collapse All' and 'Refresh All' do not overlap.
![image](https://user-images.githubusercontent.com/41351993/156533167-298026af-b6e6-47ee-8dfd-d2d2e244d173.png)

## Actual Experience ##
The localized strings 'Collapse All' and 'Refresh All' overlap.
![image](https://user-images.githubusercontent.com/41351993/156531747-d0a77df6-10d4-4523-a7e2-3eab62083ef0.png)

## Additional Context ##
This issue doesn't reproduce on **zh-CN/zh-TW/Korean/Swedish/Turkish**.

**Comment by MRayermannMSFT** [comment]
Fixed on main
![image](https://user-images.githubusercontent.com/21112697/223592861-c3c2a6c9-6666-4d47-9c19-14533fd0f3f4.png)

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230307.6. Fixed.
