### ISSUE TITLE
Lose highlight after hovering the mouse to the selected item

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#55]
**Storage Explorer Version:** master/20180419.2

**OS Version:** Windows 10/Mac/Linux

**Regression:** Works well on 1.0.0 release

**Steps to Reproduce:**

1. Launch Storage Explorer and expand Storage Accounts. 
2. Change the theme to Dark.
3. Open one blob container and select one item.
4. Hover the mouse to it and check the highlight.

**Expected Experience:**
The highlight still displays.

**Actual Experience:**
Lose highlight after hovering the mouse to the selected item.
![highlight](https://user-images.githubusercontent.com/34729022/39040184-5ffd4aae-4476-11e8-9d7d-229aa9ffa029.png)

**Comment by craxal** [comment]
Unable to reproduce on current master. Please check again and reopen the issue if it reproduces for you.
