### ISSUE TITLE
The attached table doesn't display automatically if attaching it by Azure AD

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5500]
**Storage Explorer Version:** 1.24.0-dev
**Build Number:** 20220303.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.1 (Apple M1 Pro)
**Architecture:** ia32\x64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Tables -> Create a table.
2. Add the rbac role 'Storage Table Data Contributor' then assign to one azure account.
3. Attach the table by Azure AD.
4. Check whether the attached table displays automatically.

## Expected Experience ##
The attached table displays automatically.

## Actual Experience ##
The attached table doesn't display automatically.

## Additional Context ##
The attached table displays after manually refreshing.

**Comment by craxal** [comment]
@v-kellyluo This might have been fixed along with other node-related fixes, as this doesn't reproduce for me in the current state of main. Can you verify again?

**Comment by v-xianya** [comment]
@craxal Verified this issue on the build main/20220318.5. Fixed.

The answers to your question:
1. If the attached table is the first table Azure AD attachment , the table's explorer doesn't display.
2. If the attached table is NOT the first table Azure AD attachment ,both table node and the table explorer do not display.
