### ISSUE TITLE
diagnostics is unclear

### ISSUE THREAD

**Issue by marketresearchru** [microsoft/AzureStorageExplorer#5503]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.3

### Architecture

x64

### Platform

Windows

### OS Version

win 10

### Bug Description

When uploading a file got the message: 
{
  "message": "\"UnexpectedCancel\""
}

What does it mean????

### Steps to Reproduce

1 launch
2 choose a folder
3 upload file

### Actual Experience

I do not understand what does it mean and what to do

### Expected Experience

I would expect the description of the error and required action

**Comment by MRayermannMSFT** [comment]
@marketresearchru it means that AzCopy (the tool Storage Explorer uses behind the scenes for uploads and downloads) said that it quit due to being cancelled, but Storage Explorer didn't send a cancel command to the tool.

From here, we need to take a look at your AzCopy log files. You can find them in your user's home directory, in a folder called .azcopy. Please share the log files associated with the transfer you were doing. Thanks!

**Comment by marketresearchru** [comment]
Hi, @MRayermannMSFT ,
You explained to me the error: "_it quit due to being cancelled, but Storage Explorer didn't send a cancel command to the tool._" but it became even foggier...
Thank you for the proposal to check the log file, the explanation is inside - I have no upload authorisation. 
I hope, the developer team will change the error message to make it clear.
Logfile attached.
[afd849cf-c280-4041-6d9a-ea8cea1d4ba2.log](https://github.com/microsoft/AzureStorageExplorer/files/8203429/afd849cf-c280-4041-6d9a-ea8cea1d4ba2.log)
.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem, we recommend opening an Azure support ticket via the portal. You can also open a new issue here.
