### ISSUE TITLE
Succeed to create one emulator table with the name 'tables'

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5505]
**Storage Explorer Version:** 1.24.0
**Build Number:** 20220308.2
**Branch:** main
**Platform/OS:** Windows 10
**Architecture:** ia32
**Azurite Version:** 3.15.0
**How Found:** Ad-hoc testing
**Regression From:** Previous release (1.21.3)

## Steps to Reproduce ##

1. Install and run Azurite 3.15.0 -> Launch Storage Explorer.
2. Expand 'Local & Attached -> Storage Accounts -> (Emulator - Default Ports) (Key)'.
3. Right click 'Tables' node -> Create a table with the name 'tables'.
4. Check whether fails to create the table.

## Expected Experience ##
Fail to create a table with the name 'tables'.
![image](https://user-images.githubusercontent.com/87792676/157180314-8a7fc111-66c5-4f8c-982e-18d8ef530c34.png)

## Actual Experience ##
1. Succeed to create a table with the name 'tables'.
![image](https://user-images.githubusercontent.com/87792676/157180254-6c43d961-a90a-467b-a622-f994af4ac2e3.png)
2. There is a successful activity log when creating a table with the name 'Tables'.
![image](https://user-images.githubusercontent.com/87792676/157184650-7bfc51cc-0312-4207-a01e-842c87c98e06.png)

**Comment by craxal** [comment]
@v-kellyluo This is yet another Azurite bug. I have opened https://github.com/Azure/Azurite/issues/1379.

**Comment by craxal** [comment]
This is now resolved as of Azurite 3.17.1.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20220513.1 with running azurite 3.17.1. Fixed.
