### ISSUE TITLE
No new table tab is opened when attaching one table

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5506]
**Storage Explorer Version:** 1.24.0
**Build Number:** 20220308.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.1 (Apple M1 Pro)
**Architecture:** ia32\x64
**How Found:** From running test cases
**Regression From:** Previous release (1.23.0)

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create a table -> Right click the table-> Click 'Get Shared Access Signature...'.
3. Click 'Create' -> Copy the SAS URL.
4. Open the connect dialog -> Attach the table via the copied SAS URL.
5. Check whether a new table tab is opened.

## Expected Experience ##
A new table tab is opened.

## Actual Experience ##
No new table tab is opened.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220318.5. Fixed.
