### ISSUE TITLE
Azure Storage Explorer crashes shortly after starting

### ISSUE THREAD

**Issue by kovacevicit** [microsoft/AzureStorageExplorer#5507]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.22.3

### Regression From

1.22.0

### Architecture

x64

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Every time i open Azure Storage Explorer, 10 seconds goes by and then the it crashes(closes). No error code, no nothing, just closes and that is it? Does anyone know what is happening?

Regards.

### Steps to Reproduce

Launch storage explorer.
Wait 15 seconds
it exits

### Actual Experience

Every time i open Azure Storage Explorer, 10 seconds goes by and then the it crashes(closes). No error code, no nothing, just closes and that is it? Does anyone know what is happening?

Regards.

### Expected Experience

I just want it to work

**Comment by JasonYeMSFT** [comment]
@kovaceivcit Could you try starting Storage Explorer from a command line (like powershell) and see if there is anything significant in the console output?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem, we recommend opening an Azure support ticket via the portal. You can also open a new issue here.
