### ISSUE TITLE
Importing CSV to Table storage lacks end user friendliness

### ISSUE THREAD

**Issue by seanmcne** [microsoft/AzureStorageExplorer#5508]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

When importing a csv to a new table in a storage account strange errors are produced with zero suggested actions or suggested problems 

### Desired Solution

Common end user scenarios should support a guided workflow OR errors should suggest common problems

### Alternatives and Workarounds

n/a

### Additional Context
1. Expand tables on a storage account
2. Create a new table
3. Click Import CSV
![image](https://user-images.githubusercontent.com/2292260/157296112-33cf3119-76b3-46c4-9d63-492885617e8d.png)
4. Select a local csv file with (roughly) these contents
![image](https://user-images.githubusercontent.com/2292260/157297009-69be0d03-13b8-4876-89df-f43f4a6c49f1.png)

**Expected:** if there is a problem with this approach it should clearly tell you problems in a more user friendly way.
**Actual:** 
- Error: 
![image](https://user-images.githubusercontent.com/2292260/157296532-f5615fda-732f-4296-b1b0-5dd965efdb2e.png)

**Comment by seanmcne** [comment]
An error such as the following would be much more helpufl: "Column header values cannot contain spaces in Azure Table Storage. Please rename your columns to remove spaces [and special characters? maybe point to a spec?]" and retry your import."

**Comment by craxal** [comment]
@seanmcne That looks like an actual bug in the code and not so much related to an error in your import file. I'll take a closer look.
