### ISSUE TITLE
Increase height of scrollbar in tabs section

### ISSUE THREAD

**Issue by roelofpostmus** [microsoft/AzureStorageExplorer#5510]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I have trouble scrolling between tabs because the scrollbars is very low (only a view pixels high)

### Desired Solution

I like to have a normal height in scrollbar, same as in other scrollbars

### Alternatives and Workarounds

use the low scroll bar

**Comment by MRayermannMSFT** [comment]
@roelofpostmus we looked at the scrollbar this morning, and we think we probably need to make it easier to use/click/not miss-click.

In the mean time you can:
- Zoom in (view > zoom in) and that will make the scroll bar (and everything else) visually bigger
- When your mouse is in the tab list, use a scroll wheel (up and down) to scroll through the list

**Comment by roelofpostmus** [comment]
Thnx for the response. The mouse wheel option is a good work around.
Of course my request to improve the use/click/not miss-click has my
preference.
Good luck and regards,

Roelof Postmus
Product Owner

Mobile +31 6 29 54 63 74
Plotterweg 38, 3821 BB Amersfoort, The Netherlands
Visma | YouServe B.V.

Partner for HR and payroll service & software solutions

This communication is intended for the person(s) named above only. It
contains information that is confidential and legally privileged. If
received in error, please delete this e-mail and notify the sender.

**Comment by craxal** [comment]
Something I noticed is the little space between the scroll bar and the panel below has the same color as the scrollbar, which makes it hard to tell where you can or should click.
