### ISSUE TITLE
Can't connect to blob container after replacing computer

### ISSUE THREAD

**Issue by dlevison** [microsoft/AzureStorageExplorer#5513]
Unable to retrieve child resources.

Details:
{
  "name": "RestError",
  "message": "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:a0ea46d1-601e-00aa-13d5-330415000000\nTime:2022-03-09T16:49:29.6309162Z",
  "stack": "RestError: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:a0ea46d1-601e-00aa-13d5-330415000000\nTime:2022-03-09T16:49:29.6309162Z\n    at handleErrorResponse (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/@azure/core-http/dist/index.js:3129:19)\n    at /Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/@azure/core-http/dist/index.js:3065:49\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async StorageRetryPolicy.attemptSendRequest (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/@azure/storage-blob/dist/index.js:14086:24)\n    at async StorageClientContext.sendOperationRequest (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/@azure/core-http/dist/index.js:4894:31)\n    at async BlobServiceClient.listContainersSegment (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/@azure/storage-blob/dist/index.js:23132:20)",
  "code": "AuthenticationFailed",
  "statusCode": 403,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://<OUR ID>.blob.core.windows.net/?comp=list&include=metadata",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2020-10-02"
        },
        "accept": {
          "name": "Accept",
          "value": "application/xml"
        },
        "user-agent": {
          "name": "User-Agent",
          "value": "Microsoft Azure Storage Explorer, 1.22.1, darwin azsdk-js-storageblob/12.8.0 (NODE-VERSION v14.16.0; Darwin 21.2.0)"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "934add84-2a16-47c0-b247-f0f5f724f59e"
        },
        "x-ms-date": {
          "name": "x-ms-date",
          "value": "Wed, 09 Mar 2022 16:49:29 GMT"
        },
        "authorization": {
          "name": "Authorization",
          "value": "Signed SharedKey Redacted="
        },
        "cookie": {
          "name": "Cookie",
          "value": ""
        }
      }
    },
    "withCredentials": false,
    "timeout": 0,
    "keepAlive": true,
    "decompressResponse": false,
    "requestId": "934add84-2a16-47c0-b247-f0f5f724f59e",
    "operationSpec": {
      "path": "/",
      "httpMethod": "GET",
      "responses": {
        "200": {
          "bodyMapper": {
            "serializedName": "ListContainersSegmentResponse",
            "xmlName": "EnumerationResults",
            "type": {
              "name": "Composite",
              "className": "ListContainersSegmentResponse",
              "modelProperties": {
                "serviceEndpoint": {
                  "serializedName": "ServiceEndpoint",
                  "required": true,
                  "xmlName": "ServiceEndpoint",
                  "xmlIsAttribute": true,
                  "type": {
                    "name": "String"
                  }
                },
                "prefix": {
                  "serializedName": "Prefix",
                  "xmlName": "Prefix",
                  "type": {
                    "name": "String"
                  }
                },
                "marker": {
                  "serializedName": "Marker",
                  "xmlName": "Marker",
                  "type": {
                    "name": "String"
                  }
                },
                "maxPageSize": {
                  "serializedName": "MaxResults",
                  "xmlName": "MaxResults",
                  "type": {
                    "name": "Number"
                  }
                },
                "containerItems": {
                  "serializedName": "ContainerItems",
                  "required": true,
                  "xmlName": "Containers",
                  "xmlIsWrapped": true,
                  "xmlElementName": "Container",
                  "type": {
.......
......
                 "errorCode": {
                    "serializedName": "x-ms-error-code",
                    "xmlName": "x-ms-error-code",
                    "type": {
                      "name": "String"
                    }
                  }
                }
              }
            },
            "BlockBlobGetBlockListExceptionHeaders": {
              "serializedName": "BlockBlob_getBlockListExceptionHeaders",
              "type": {
                "name": "Composite",
                "className": "BlockBlobGetBlockListExceptionHeaders",
                "modelProperties": {
                  "errorCode": {
                    "serializedName": "x-ms-error-code",
                    "xmlName": "x-ms-error-code",
                    "type": {
                      "name": "String"
                    }
                  }
                }
              }
            }
          },
          "isXML": true
        }
      }
    },
    "status": 403,
    "bodyAsText": "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:a0ea46d1-601e-00aa-13d5-330415000000\nTime:2022-03-09T16:49:29.6309162Z</Message><AuthenticationErrorDetail>The MAC signature found in the HTTP request '<SIGNATURE>' is not the same as any computed signature. Server used following string to sign: 'GET\n\n\n\n\n\n\n\n\n\n\n\nx-ms-client-request-id:934add84-2a16-47c0-b247-f0f5f724f59e\nx-ms-date:Wed, 09 Mar 2022 16:49:29 GMT\nx-ms-version:2020-10-02\n/<ID>/\ncomp:list\ninclude:metadata'.</AuthenticationErrorDetail></Error>",
    "parsedBody": {
      "message": "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:a0ea46d1-601e-00aa-13d5-330415000000\nTime:2022-03-09T16:49:29.6309162Z",
      "code": "AuthenticationFailed",
      "AuthenticationErrorDetail": "The MAC signature found in the HTTP request '<SIGNATURE>' is not the same as any computed signature. Server used following string to sign: 'GET\n\n\n\n\n\n\n\n\n\n\n\nx-ms-client-request-id:934add84-2a16-47c0-b247-f0f5f724f59e\nx-ms-date:Wed, 09 Mar 2022 16:49:29 GMT\nx-ms-version:2020-10-02\n/<ID>/\ncomp:list\ninclude:metadata'."
    },
    "parsedHeaders": {
      "errorCode": "AuthenticationFailed",
      "content-length": "727",
      "content-type": "application/xml",
      "date": "Wed, 09 Mar 2022 16:49:29 GMT",
      "server": "Microsoft-HTTPAPI/2.0",
      "x-ms-request-id": "a0ea46d1-601e-00aa-13d5-330415000000"
    }
  },
  "details": {
    "errorCode": "AuthenticationFailed",
    "content-length": "727",
    "content-type": "application/xml",
    "date": "Wed, 09 Mar 2022 16:49:29 GMT",
    "server": "Microsoft-HTTPAPI/2.0",
    "x-ms-request-id": "a0ea46d1-601e-00aa-13d5-330415000000",
    "message": "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:a0ea46d1-601e-00aa-13d5-330415000000\nTime:2022-03-09T16:49:29.6309162Z",
    "code": "AuthenticationFailed",
    "AuthenticationErrorDetail": "The MAC signature found in the HTTP request '<SIGNATURE>' is not the same as any computed signature. Server used following string to sign: 'GET\n\n\n\n\n\n\n\n\n\n\n\nx-ms-client-request-id:934add84-2a16-47c0-b247-f0f5f724f59e\nx-ms-date:Wed, 09 Mar 2022 16:49:29 GMT\nx-ms-version:2020-10-02\n/<ID>/\ncomp:list\ninclude:metadata'."
  }
}

**Comment by MRayermannMSFT** [comment]
@dlevison It looks like you are trying to list the containers in your storage account, but something is wrong...

- If you attached your storage account manually, please make sure that the key you used is correct
- If you are accessing the account via sign in/if the key you used to attach is correct, please check the account for any storage firewall/restricted IP settings
