### ISSUE TITLE
Init Install in Linux

### ISSUE THREAD

**Issue by RiveraHan** [microsoft/AzureStorageExplorer#5517]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.23.0

### Architecture

x64

### Platform

Linux

### OS Version

Ubuntu 20.04

### Bug Description

No se pueden recuperar los recursos secundarios.

Detalles:
An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.400" (uid=1000 pid=45655 comm="/snap/storage-explorer/32/StorageExplorerExe --typ" label="snap.storage-explorer.storage-explorer (enforce)") interface="org.freedesktop.Secret.Service" member="OpenSession" error name="(unset)" requested_reply="0" destination=":1.70" (uid=1000 pid=6043 comm="/usr/bin/gnome-keyring-daemon --start --foreground" label="unconfined")

### Steps to Reproduce

1. launch storage explorer

### Actual Experience

No se pueden recuperar los recursos secundarios.

Detalles:
An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.400" (uid=1000 pid=45655 comm="/snap/storage-explorer/32/StorageExplorerExe --typ" label="snap.storage-explorer.storage-explorer (enforce)") interface="org.freedesktop.Secret.Service" member="OpenSession" error name="(unset)" requested_reply="0" destination=":1.70" (uid=1000 pid=6043 comm="/usr/bin/gnome-keyring-daemon --start --foreground" label="unconfined")

### Additional Context

No se pueden recuperar los recursos secundarios.

Detalles:
An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.400" (uid=1000 pid=45655 comm="/snap/storage-explorer/32/StorageExplorerExe --typ" label="snap.storage-explorer.storage-explorer (enforce)") interface="org.freedesktop.Secret.Service" member="OpenSession" error name="(unset)" requested_reply="0" destination=":1.70" (uid=1000 pid=6043 comm="/usr/bin/gnome-keyring-daemon --start --foreground" label="unconfined")

**Comment by MRayermannMSFT** [comment]
@RiverHan can you try:
```
snap connect storage-explorer:password-manager-service
```
If that doesn't work, then we recommend using the .tar.gz install of Storage Explorer.

**Comment by RiveraHan** [comment]
thanks @MRayermannMSFT

**Comment by RiveraHan** [comment]
Thanks 👍
