### ISSUE TITLE
Can't delete files/blob containers on ADLS Gen2 storage account with storage explorer

### ISSUE THREAD

**Issue by RheaZuo** [microsoft/AzureStorageExplorer#5519]
Hi team,
I have a ADLS Gen2 storage account.
I can create a blob container and upload files to it but afterward, I can not delete any files or blob through the storage explorer. 
Error:
{
  "message": "\"failed to perform remove command due to error: cannot start job due to error: cannot verify resource due to error: -> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/error.go:157\\nHTTP request failed\\n\\nHead https://testconruyisa.dfs.core.windows.net/test-connection/AntiStress%20karte.pdf?timeout=901: BlankAuthenticationPage\\n.\\n\""
}

It shows "Deletion of <filenameXXX> from <blob container> failed: (use name and key)"

The storage account is open to all networks. 
I am the admin and creator of the storage account. I can delete the exact file and blob container on Azure portal with the same account. And this is happening mainly on ADLS Gen2. 
I tried newest version of Storgae Exploer 1.23.0 and it has the same error with deleting files/blob containers. 
I tried different authentication methods(azure account and connection string) and it didn't help as well.

I tried LRS and GRS, west europe, north europe, it still has the same error.

This is impacting on me (admin) and as well as our customers. I am really clueless why it doesn't work with deleting files on storage explorer.

Any help will be appreciated.

Thank you for your time!

Best,

Ruyi

**Comment by JasonYeMSFT** [comment]
@RheaZuo The activity says you are using account name and key to authenticate the request. Did you attach that storage account with name and key in Storage Explorer? If so, could you verify if your account key has been rotated? On Portal, you are signed in and will be able to list keys to get the latest account key.

**Comment by JasonYeMSFT** [comment]
This is a very weird problem then. Could you see a "Copy AzCopy command" action on the failed activity? If so, please share it with us after redacting sensitive information like your storage account name, SAS token in the sig= parameter and leave all the arguments as is. And do you consistently get this error when trying to delete your files?

**Comment by JasonYeMSFT** [comment]
Ofc there is no problem keeping this open. If your work laptop is connected to some kind of private network, it might be intercepting your traffic and blocking certain requests. It's still weird though because you said Portal works just fine. I would recommend getting the command and repro it with AzCopy command line tool. If possible, you can also setup Fiddler to intercept the requests and see what request is sent and what response is returned. Usually when network or firewall are blocking traffic, the response contains a network error.

**Comment by RheaZuo** [comment]
> Ofc there is no problem keeping this open. If your work laptop is connected to some kind of private network, it might be intercepting your traffic and blocking certain requests. It's still weird though because you said Portal works just fine. I would recommend getting the command and repro it with AzCopy command line tool. If possible, you can also setup Fiddler to intercept the requests and see what request is sent and what response is returned. Usually when network or firewall are blocking traffic, the response contains a network error.


Hey I am back from vacation and can give an update on this topic again. 
The AzCopy Command to clipboard: 

$env:AZCOPY_CRED_TYPE = "SharedKey";
$env:ACCOUNT_NAME = <StorageAccountName>;
$env:ACCOUNT_KEY = <AccountKey>;
./azcopy.exe remove "https://<StorageAccountName>.dfs.core.windows.net/<BlobContainerName>/<FileName.pdf>" --recursive;
$env:AZCOPY_CRED_TYPE = "";
$env:ACCOUNT_NAME = "";
$env:ACCOUNT_KEY = "";

And Error messages in details: 
{
  "message": "\"failed to perform remove command due to error: cannot start job due to error: cannot verify resource due to error: -> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/error.go:157\\nHTTP request failed\\n\\nHead https://<StorageAccountName>.dfs.core.windows.net/<BlobContainerName>/<FileName.pdf>?timeout=901: BlankAuthenticationPage\\n.\\n\""
}


Interestingly,  I installed an ancient version of storage explorer 1.9.0 and it worked all fine with deleting files from v.1.9.0 storage explorer. I tested it with the same laptop, the same Azure account and storage account, blob containers etc.

Any ideas why is it like that? 
Any help or information will be appreciated. 

Thank you in advance.

**Comment by JasonYeMSFT** [comment]
There is nothing wrong with the command. The only thing I can think of is a breaking change in AzCopy but I am not sure what it is. I am going to contact the AzCopy team to see if they have any idea what might be causing it.

**Comment by RheaZuo** [comment]
Thank you! Then I will wait for their response ;)

**Comment by JasonYeMSFT** [comment]
Sorry for the late response. Unfortunately AzCopy team doesn't remember seeing this error so they don't know for sure what it is about. If you can reproduce it with azcopy command line tool, could you please open an issue in the AzCopy issue so they can triage it and assign someone to investigate? https://github.com/Azure/azure-storage-azcopy

**Comment by RheaZuo** [comment]
Hi Jason, thank you for your update. After diving into AzCopy cmd, we found that it was the issue of our proxy setting and it works fine after we disabled AzCopy Proxy Usage.
But this was really not foreseeable, I was mainly testing proxy configurations on the **Application** section in Settings and barely strolled down to the **Transfer** section.  It would be nice if you can add a redirect link or at least warnings in the proxy section about Azcopy as well. 

Thank you for your time, I am really happy the mystery is resolved.
