### ISSUE TITLE
There are extra actions 'Clone…' and 'Delete' in the context menu for one Azure AD attached table

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5522]
**Storage Explorer Version:** 1.24.0-dev
**Build Number:** 20220308.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.1 (Apple M1 Pro)
**Architecture:** ia32\x64
**How Found:** Ad-hoc testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create a table -> Attach it by Azure AD.
3. Right click the attached table -> The context menu displays.
4. Check whether there are no extra actions 'Clone…' and 'Delete'.

## Expected Experience ##
There are no extra actions 'Clone…' and 'Delete'.

## Actual Experience ##
There are extra actions 'Clone…' and 'Delete'.
![image](https://user-images.githubusercontent.com/87792676/158123105-92a9c212-02de-4bfc-9445-4d25b88e5cc8.png)

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220318.5. Fixed.
![image](https://user-images.githubusercontent.com/41351993/158928117-27d9584f-4514-4918-b862-2ef11afd8b5e.png)
