### ISSUE TITLE
The titles of error dialog for the broken blob container/file share/queue/table under QA node are inconsistent if the associated account is removed

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5523]
**Storage Explorer Version**: 1.24.0-dev
**Build Number**: 20220308.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.1 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Expand the four services node.
2. Add one blob container/file share/table/queue to the Quick Access node separately.
3. Go to ACCOUNT MANAGEMENT panel -> Remove the associated azure account.
4. Go to EXPLORE panel -> The QA items display as broken. 
5. Right click the broken items -> Click 'View Error...'.
6. Observe the titles of error dialog -> Check whether the titles are consistent.
## Expected Experience ##
The titles of the error dialog are consistent.

## Actual Experience ##
The titles of the error dialog are inconsistent.
![image](https://user-images.githubusercontent.com/41351993/158126719-c6e617d1-24bf-44d7-9a54-ae72282ab5b6.png)

**Comment by MRayermannMSFT** [comment]
All dialogs should have a consistent title. There is no expectation that the errors are consistent, beyond errors being at least slightly helpful about why the QA node is broken.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230107.3. Fixed. 
![image](https://user-images.githubusercontent.com/41351993/211231325-497a4721-188b-4318-a22d-e3a8d2bc84f7.png)
