### ISSUE TITLE
The Azure AD attached table does not auto display as broken if removing its associated azure account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5526]
**Storage Explorer Version**: 1.24.0-dev
**Build Number**: 20220315.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.1 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Attach the table via Azure AD.
3. Remove its associated azure account.
4. Check whether the Azure AD attached table auto displays as broken.

## Expected Experience ##
The Azure AD attached table doesn't auto display as broken.

## Actual Experience ##
The Azure AD attached table auto displays as broken.

## Additional Context ##
1. The Azure AD attached table displays as broken after manually refreshing.
2. It needs to manually refresh to make the broken Azure AD attached table display as normal after signing-in back the Azure Account.

**Comment by MRayermannMSFT** [comment]
Don't worry about this if it also reproduces with other services. I don't think we added any sort of auto refreshing to attached nodes after removing accounts.

**Comment by craxal** [comment]
@v-xianya As per Matthew's comment, can you determine whether this reproduces for blobs, files, or queues?

**Comment by craxal** [comment]
@v-xianya I confirmed that blobs and queues do automatically update, so tables need to as well.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220324.2. Fixed.
