### ISSUE TITLE
Unable to retrieve child resources.

### ISSUE THREAD

**Issue by SharanabasavaM** [microsoft/AzureStorageExplorer#5528]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.23

### Architecture

i86

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Unable to retrieve child resources.

Details:
{
  "name": "TypeError",
  "message": "Invalid URL",
  "stack": "TypeError [ERR_INVALID_URL]: Invalid URL\n    at new NodeError (node:internal/errors:371:5)\n    at onParseError (node:internal/url:552:9)\n    at new URL (node:internal/url:628:5)\n    at ConnectionString._inferredEndpoint (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\azure-connections\\dist\\src\\ConnectionString\\ConnectionString.js:79:19)\n    at ConnectionString.inferredTableEndpoint (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\azure-connections\\dist\\src\\ConnectionString\\ConnectionString.js:109:21)\n    at Function.produceTableServiceNode (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-table-extension\\dist\\src\\Nodes\\TableService\\TableServiceProducer.js:26:64)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Object.StorageExplorer.Table.Producer.produceTableServiceNode (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-table-extension\\dist\\src\\index.js:149:16)\n    at async Provider.executeOperation (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\providers\\Provider.js:28:16)\n    at async NodeProcessHostProxy._handleExecuteRequest (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:226:31)",
  "input": "https://100047 Custlog.table.core.windows.net",
  "code": "ERR_INVALID_URL"
}

### Steps to Reproduce

1. Launch Azure storage explorer.
2. Connect using the custlog file: REDACTED

Then we arrive at the following error

### Actual Experience

1. Launch Azure storage explorer.
2. Connect using the custlog file: REDACTED

Then we arrive at the following error.

**Comment by MRayermannMSFT** [comment]
@SharanabasavaM there's something wrong with the URLs you have given Storage Explorer to connect with. From the error, it looks like you have entered a table URL of `https://100047 Custlog.table.core.windows.net`. This is not a valid URL. Are you trying to connect to an emulator storage account or a storage account in Azure?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are continuing to run into this problem, we recommend opening an Azure support ticket. You can also open a new issue here.
