### ISSUE TITLE
'Paste Table' is always enabled in Tables context menu

### ISSUE THREAD

**Issue by v-dantch** [microsoft/AzureStorageExplorer#553]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180808.1
**Commit**: 93925d3c
**Regression From**: Not a regression 

#### Steps to Reproduce: ####
1. Right click one blob container -> Select 'Copy Blob Container'.
2. Right click one table -> Check the context menu.

#### Expected Experience: ####
'Paste Table' is disabled.

#### Actual Experience: ####
1. 'Paste Table' is enabled.
2. Pop up an error dialog after executing 'Paste Table'.
![error](https://user-images.githubusercontent.com/34729092/43830700-77cad33c-9af1-11e8-9fa2-173623105bb8.png)

**Comment by v-xuanzh** [comment]
This issue has been fixed on the real singed build 20190625.3. So close it.
