### ISSUE TITLE
Fail to open the connect dialog by clicking the plug icon

### ISSUE THREAD

**Issue by v-sunnysun** [microsoft/AzureStorageExplorer#5530]
**Storage Explorer Version:** 1.24.0-dev
**Build Number:** 20220316.5
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.1 (Apple M1 Pro)
**Architecture:** ia32\x64
**How Found:** From running test cases
**Regression From:** Previous release (1.23.0)

## Steps to Reproduce ##

1. Launch Storage Explorer.
2. Click the plug icon.
3. Check whether succeeds to open the connect dialog.

## Expected Experience ##
Succeed to open the connect dialog.

## Actual Experience ##
Fail to open the connect dialog.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220318.5. Fixed.
