### ISSUE TITLE
Can't select the soft-deleted blob or the active blob separately if they share the same name under the 'Active and soft deleted blobs' context view

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5533]
**Storage Explorer Version**: 1.24.0-dev
**Build Number**: 20220318.5
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.1 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: Exploratory testing
**Regression From**: Previous release (1.23.0)

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one blob -> Soft delete the blob.
3. Upload a same blob -> Switch to the context view 'Active and soft deleted blobs'.
4. There are one soft-deleted blob and one active blob.
5. Check whether we can select one of the blobs.

## Expected Experience ##
Can select one of the blobs.
![image](https://user-images.githubusercontent.com/41351993/158964435-5afff027-7896-4a1b-825d-49cbe27023e3.png)

## Actual Experience ##
1. Can't select one of the blobs.
2. The blobs are selected at the same time. 
![image](https://user-images.githubusercontent.com/41351993/158964346-5c5fc8e9-5161-4ebe-a9b8-70d47da28411.png)

## Additional Context ##
1. No 'Deletion ID' for soft deleted blobs/folders.
![image](https://user-images.githubusercontent.com/41351993/158972522-91abf160-6f32-4c6e-bdd6-ea3a25a75431.png)
2. Similar issue: [4808](https://github.com/microsoft/AzureStorageExplorer/issues/4808)

**Comment by JasonYeMSFT** [comment]
I tried with my containers but this doesn't reproduce. If you can consistently reproduce it, could you share a container with me so I can show the issue to the service team?

**Comment by v-xianya** [comment]
@JasonYeMSFT I can reproduce this consistently on the new build main/20220320.3.

BTW, there are no Deletion ID for soft deleted blobs.

You can reproduce this issue on the blob container '**bc0321**' Under Subscription '**Azure Tools Manual Testing 2**' -> Storage Account '**arbacadls** (ADLS Gen2)'  
![image](https://user-images.githubusercontent.com/41351993/159214087-628f4b66-797b-4e44-a02b-1b30f0ac6e27.png)

**Comment by JasonYeMSFT** [comment]
This should have been fixed in the new Gen2 explorer as well.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220406.4. Fixed.
