### ISSUE TITLE
AppArmor org.freedesktop.Secret.Service interface error during child resource loading

### ISSUE THREAD

**Issue by maniadapa** [microsoft/AzureStorageExplorer#5534]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.0

### Regression From

1.18.0

### Architecture

i86

### Platform

Windows

### OS Version

windows10

### Bug Description

Unable to retrieve child resources.

### Steps to Reproduce

Unable to retrieve child resources.

### Actual Experience

Unable to retrieve child resources.

### Expected Experience

Unable to retrieve child resources.

### Additional Context

Unable to retrieve child resources.

**Comment by OfficialMutazAwad** [comment]
Unable to retrieve child resources.

Details:
An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.667" (uid=1000 pid=35503 comm="/snap/storage-explorer/32/StorageExplorerExe --typ" label="snap.storage-explorer.storage-explorer (enforce)") interface="org.freedesktop.Secret.Service" member="OpenSession" error name="(unset)" requested_reply="0" destination=":1.26" (uid=1000 pid=1746 comm="/usr/bin/gnome-keyring-daemon --daemonize --login " label="unconfined")

**Comment by MRayermannMSFT** [comment]
@OfficialMutazAwad  can you try:
```
snap connect storage-explorer:password-manager-service
```
If that doesn't work, then we recommend using the .tar.gz install of Storage Explorer.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are continuing to run into this problem, we recommend opening an Azure support ticket. You can also open a new issue here.
