### ISSUE TITLE
There is a failed activity log when cloning one emulator blob container which has non-empty folder

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5535]
**Storage Explorer Version:** 1.24.0-dev
**Build Number:** 20220320.3
**Branch:** main
**Platform/OS:** Windows 10
**Architecture:** ia32
**Azurite Version:** 3.16.0
**How Found:** From running test cases
**Regression From:** Previous release (1.23.0)

## Steps to Reproduce ##

1. Install and run Azurite 3.16.0 -> Launch Storage Explorer.
2. Expand 'Local & Attached -> Storage Accounts -> (Emulator - Default Ports) (Key)' -> Blob Containers.
3. Create one blob container -> Upload one non-empty folder.
4. Right click the blob container -> Click 'Clone...'.
5. Type a valid name -> Click 'Clone'.
6. Check whether there is a successful activity log.

## Expected Experience ##
There is a successful activity log.

## Actual Experience ##

1. The cloned blob container displays under the Blob Containers node.
2. There is a failed activity log.
![image](https://user-images.githubusercontent.com/87792676/159229663-6c52234a-86ef-4c50-8916-c990740bed09.png)

## Additional Context ##
The error details dialog:
![image](https://user-images.githubusercontent.com/87792676/159232296-f1904ade-5fd9-4896-b4df-93bd73091b06.png)

**Comment by craxal** [comment]
@v-kellyluo Was the `transfers.js.enable` setting `true` or `false`? Please include how you set this setting in your repro steps.

**Comment by v-kellyluo** [comment]
@craxal This issue reproduces consistently regardless of whether the `transfers.js.enable` setting is `true` or `false`.
Here is the Settings file:
[Settings.txt](https://github.com/microsoft/AzureStorageExplorer/files/8329140/Settings.txt)

**Comment by craxal** [comment]
@v-kellyluo Does this reproduce with older versions of Azurite?

**Comment by v-kellyluo** [comment]
@craxal Yes, this issue also reproduces with Azurite 3.15.0.
![image](https://user-images.githubusercontent.com/87792676/159832300-85cb1a07-e552-4c80-93a4-21e98c153970.png)

**Comment by craxal** [comment]
I've reproduced this issue as well. I've also noticed that this does not reproduce with normal Azure containers, so some difference about the emulator is at the root of this. Looking at the Azurite output, the PUT operation for the folder is what's failing.

**Comment by JasonYeMSFT** [comment]
We are missing a showFlatBlobs flag when creating the query handler for the container copy jobs. Emulators are using the legacy JS copy job handler which will list directories but the copy logic assumes the listing results are blobs.

**Comment by JasonYeMSFT** [comment]
BTW, I noticed that the queued activity shows "containerName/undefined" as the copy source since we pass undefined as the source folder name. We should fallback to empty string when constructing the string.

**Comment by v-kellyluo** [comment]
Verified this issue on the build rel/20220421.6. Fixed.
