### ISSUE TITLE
There is a failed activity log when pasting one table with an entity whose PartitionKey is null to Emulator Tables node (running Azurite 3.16.0)

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5536]
**Storage Explorer Version**: 1.24.0-dev
**Build Number**: 20220320.3
**Branch**: main
**Platform/OS**: Windows 10
**Architecture** ia32
**Azurite Version** 3.16.0
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Install and run Azurite 3.16.0 -> Launch Storage Explorer.
2. Expand one storage account -> Tables.
3. Create a table -> Add one entity as below (Do not type any characters to PartitionKey field).
![image](https://user-images.githubusercontent.com/41351993/159239751-6b469387-f346-4b7c-bb29-3da5635dec49.png)
4. Copy and paste the table to Emulator Tables node.
5. Check whether the pasted table displays well and there is a successful activity log.

## Expected Experience ##
1. The pasted table displays well.
2. There is a successful activity log.

## Actual Experience ##
1. The pasted table displays well.
2. There is a failed activity log with the error '**Partition key not found in request**'.
![image](https://user-images.githubusercontent.com/41351993/159240674-302bdbea-9018-49af-ba3c-a7d6244c4e28.png)
![image](https://user-images.githubusercontent.com/41351993/159240708-c63a72f2-bd61-4af6-9b03-a6ee61b07fd4.png)

## Additional Context ##
This issue doesn't reproduce when using **Azurite 3.15.0**.

**Comment by craxal** [comment]
Same root cause as https://github.com/microsoft/AzureStorageExplorer/issues/5307.

**Comment by craxal** [comment]
This is resolved as of Azurite 3.17.1.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220513.1 with the Azurite 3.17.1. Fixed.
