### ISSUE TITLE
Unable to retrieve child resources.  Details: Invalid initialization vector

### ISSUE THREAD

**Issue by hw2153** [microsoft/AzureStorageExplorer#5537]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.23.0

### Regression From

no

### Architecture

x64

### Storage Explorer Build Number

the about will not open

### Platform

Windows

### Bug Description

Unable to retrieve child resources.

Details:
Invalid initialization vector

### Steps to Reproduce

1. Launch Storage Explorer

### Actual Experience

As soon as it opens the error is received. It pops up again after authentication and when I open explorer. Additionally, I cannot upload or download files and clicking on the About under Help does not work either.

### Expected Experience

No error message and the ability to upload and download files

**Comment by MRayermannMSFT** [comment]
@hw2153 it sounds like an encryption key Storage Explorer stores in the Windows credential store has either gone missing or has become corrupted. Can you:

1. Open the start menu
2. Type in "credential manager"
3. Open the result
4. Click on Windows Credentials
5. In the list of Generic Credentials look for "Microsoft_StorageExplorer/app"

And can you let us know:

- Is it there
- What is the Modified date

**Comment by hw2153** [comment]
***@***.***
Hope Morton || (915)261-6281 || System Engineer: CinglePoint
This email, and any attachments, is intended only for use by the addressee(s) named herein and may contain legally privileged and/or confidential information. It is the property of AT&T and its affiliates. If you are not the intended recipient of this email, you are hereby notified that any dissemination, distribution or copying of this email, any attachments thereto, and any use of the information contained is strictly prohibited. If you have received this email in error, please notify me at 915-261-6281 and permanently delete the original and any copy thereof.

**Comment by hw2153** [comment]
> @hw2153 it sounds like an encryption key Storage Explorer stores in the Windows credential store has either gone missing or has become corrupted. Can you:
> 
> 1. Open the start menu
> 2. Type in "credential manager"
> 3. Open the result
> 4. Click on Windows Credentials
> 5. In the list of Generic Credentials look for "Microsoft_StorageExplorer/app"
> 
> And can you let us know:
> 
> * Is it there
> * What is the Modified date

Yes, it is there. Last modified date is 1/31/2022.

**Comment by vats-ashish** [comment]
hi there I am also facing the same issue and for me, the last modified date is Jan/11/2021.

**Comment by MRayermannMSFT** [comment]
@hw2153 @vats-ashish ok so fair warning for the following instructions: you're going to lose your quick access items as part of this. Unfortunately there's nothing we can do about that. 😞 Please try the following:

Part 1: Delete existing encrypted quick access data:
1. Launch storage explorer
2. Press F12
3. In the window/panel that just opened, go to the application tab
![image](https://user-images.githubusercontent.com/21112697/161597878-3e9852fb-556a-418a-862d-e311dad9efa0.png)
4. In the application tab, go Local Storage > file:// and then look for "StorageExplorer_InPlaceQuickAccessItems_v1" ![image](https://user-images.githubusercontent.com/21112697/161598308-098940db-5739-41cf-b95c-c1af1ab6b719.png)
5. Click on the row with that key so it is selected, and then delete it with the X delete button: 
![image](https://user-images.githubusercontent.com/21112697/161598521-e1da2241-d8da-485d-a7a7-129fd1c4ad57.png)
6. Close Storage Explorer

Part 2: Remove existing (and probably corrupted?) encryption key
0. Close Storage Explorer
1.  Open the start menu
2.  Type in "credential manager"
3.  Open the result
4.  Click on Windows Credentials
5.  In the list of Generic Credentials look for "Microsoft_StorageExplorer/app"
6. Click Remove

Part 3: Try using Storage Explorer again
1. Open Storage Explorer
2. Try doing stuff

If that all doesn't work then we'll need to get y'all a private build with some additional logging to figure out what is going on when Storage Explorer attempts to interact with the windows credential store.

**Comment by vats-ashish** [comment]
worked for me thanks!!
