### ISSUE TITLE
Direct Links fail with "The subscription for this resource is currently filtered out" if Storage Explorer is not already open

### ISSUE THREAD

**Issue by MikePennington** [microsoft/AzureStorageExplorer#5538]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.23.1

### Architecture

x64

### Storage Explorer Build Number

20220223.14 

### Platform

macOS

### OS Version

macOS Monterey  / 12.0.1

### Bug Description

Direct link to a storage queue fails with the error "The subscription for this resource is currently filtered out. You need to select the subscription in the account settings panel to see the resource" if Azure Storage Explorer is closed when the link is clicked. If Azure Storage Explorer is already open when the link is clicked then the direct link works.

### Steps to Reproduce

1. Launch Azure Storage Explorer
2. Navigate to a storage queue
3. Right-click and select "Copy Direct Link to Queue"
4. Close Azure Storage Explorer
5. Paste link into a new browser window
6. Azure Storage Explorer will launch
7. Observe the error message appears and the queue does not come up
8. Keep Azure Storage Explorer open and paste the link into another browser window
9. Observe that the queue comes up correctly this time

### Actual Experience

Direct links do not work if Azure Storage explorer is not already open.

### Expected Experience

When using a direct link, Storage Explore should open to the correct location whether it is already opened or not.

### Additional Context

This same issue also exists with Blob Containers, File Shares, and Tables.

**Comment by MRayermannMSFT** [comment]
@MikePennington I'm having a hard time repro'ing this. I've prepared a debug build for you with some additional logging to help me see what is going on when you try to do this. Please:
1. Download this zip: https://storageexplorerpublish.blob.core.windows.net/privatebuilds/5538/StorageExplorer-darwin-x64.zip?sv=2021-04-10&st=2022-03-14T18%3A37%3A00Z&se=2022-05-15T18%3A37%3A00Z&sr=b&sp=r&sig=HagQdnZRJPgIEYyPkhg3247X6B2ffB1iqyL4UxXrpNY%3D
2. Extract the Storage Explorer .app from it
3. Place the app in your Applications folder
4. Reproduce the issue as you outlined
5. After you reproduce, go to Help -> Open Logs Directory
6. In that directory, zip up the 1st and 2nd newest folders (together or separate, whatever is easier for you) and upload that zip here

Thanks!

**Comment by MikePennington** [comment]
@MRayermannMSFT Thanks for the response. I tried to run that debug build, but authentication seems to be broken. Whenever I click "Reauthenticate now..." the "Connect to Azure Storage" window pops up for just a second and then closes and I am unable to login.

[Archive.zip](https://github.com/microsoft/AzureStorageExplorer/files/8492135/Archive.zip)

**Comment by MRayermannMSFT** [comment]
Ah, uh. Yes. There's a bug around reauth on our development branch right now. Let me send you a different build...apologies....

**Comment by MRayermannMSFT** [comment]
@MikePennington I've updated the bits at that link to not have the reauthentication issue. Can you try again? Thanks. :)

**Comment by MRayermannMSFT** [comment]
@MikePennington ?

**Comment by MikePennington** [comment]
Sorry @MRayermannMSFT , somehow I missed your last message.

Unfortunately I am unable to repro this with the debug build. However I uninstalled the debug build and reinstalled Version 1.23.1 and I was able to repro it there. I've added the logs anyways in case that helps.

[Archive.zip](https://github.com/microsoft/AzureStorageExplorer/files/8605909/Archive.zip)

**Comment by JasonYeMSFT** [comment]
I am still having trouble reproducing this issue even if I downgrade to 1.23.1. My best bet of this error is a race condition between querying storage account nodes and loading storage account nodes under the subscription. In 1.29.0 we introduced a new implementation of the tree view which may have mitigated this issue. Please upgrade to the latest Storage Explorer and see if you are still running into this problem.

**Comment by JasonYeMSFT** [comment]
@MikePennington Have you tried upgrading to a more recent version of Storage Explorer?

**Comment by MikePennington** [comment]
Closing thread. Microsoft is unable to repo and I no longer have need for it to be fixed.
