### ISSUE TITLE
Cannot add or edit binary values in Azure Tables

### ISSUE THREAD

**Issue by marcin-synak** [microsoft/AzureStorageExplorer#554]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows
**Architecture**: ia32
**Regression From**: it never worked

#### Steps to Reproduce: ####
1. Create a table in Azure Storage (classic or regular)
2. Create a row in Azure Storage Explorer using "Add Entity"
3. Try adding new property with "binary" type

Or, alternatively:
1. Create a table in Azure Storage (classic or regular)
2. Upload some rows into the table using any tool or API. Rows should contain some binary columns.
3. Try editing binary values

#### Expected Experience: ####
We'd like to have an ability to add binary data to Azure Tables using Azure Storage Explorer and edit existing binary data.
Azure Storage Explorer is able to display such data in Base64 format. I see no reason why it does not allow to enter the data in the same format (or other format, such as hex string).

#### Actual Experience: ####
Azure Storage Explorer does not allow adding new binary properties to Azure Tables. The "binary" option is grayed out.
Editing existing data also does not work. I can click "Edit entity" button and editor shows up, but any changes I make there are ignored.

My team stores MD5 and SHA256 hashes in binary format in Azure Tables. Now we cannot introduce any changes to those values without using external tools.

We understand that some limits may need to be introduced (e.g. you can edit a binary value as long as it is not larger than X bytes).

**Comment by jjxtra** [comment]
Still grayed out, c'mon Microsoft this is a 5 min project for a dev...

**Comment by KarpMac** [comment]
Is there any work being done with this issue?

**Comment by jjxtra** [comment]
It does seem like using hex would be pretty straightforward in the GUI...

**Comment by Robar666** [comment]
+1

**Comment by jagos2018** [comment]
+1

**Comment by jjxtra** [comment]
Yea!!!
