### ISSUE TITLE
The string in the address bar overflows if splitting one blob explorer with the address bar in edit mode

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5545]
**Storage Explorer Version**: 1.24.0-dev
**Build Number**: 20220322.15
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.1 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: From running test cases
**Regression From**: Previous release (1.22.1)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Click 'New Folder' -> Click 'OK'.
3. Make the address bar in the edit mode -> Split the blob container tab.
4. Click the original blob explorer.
5. Check whether the string in the address bar doesn't overflow.

## Expected Experience ##
The string in the address bar doesn't overflow.

## Actual Experience ##
The string in the address bar overflows.
![image](https://user-images.githubusercontent.com/41351993/159656432-e378b1c3-86e7-4f0e-810d-2780b597e7c3.png)

## Additional Context ##
1. This issue doesn't reproduce for ADLS Gen2 blob containers.
2. Here is the record:
![address](https://user-images.githubusercontent.com/41351993/159655891-3134bb42-d998-45e8-a1d4-8234e18f205e.gif)

**Comment by v-xianya** [comment]
This issue still reproduces on the new build main/20220324.2.

**Comment by JasonYeMSFT** [comment]
I merged another fix for this issue.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220325.1. Fixed.
