### ISSUE TITLE
Cannot access Storage Explorer subscription containers - password issue or account issue

### ISSUE THREAD

**Issue by nfporter** [microsoft/AzureStorageExplorer#5547]
This is the error message I received:

{
  "message": "\"Redirect Uri mismatch.  Expected (/favicon.ico) Actual (/). \""
}

**Comment by MRayermannMSFT** [comment]
@nfporter, when you do sign in, is it happening in your browser or in a small pop-up window?

**Comment by nfporter** [comment]
Thank you, but this issue has been resolved.

Regards,

Nadene Porter
Data Engineer, Contractor
Mission Data, ASL
Email: ***@***.******@***.***>



From: Matthew Rayermann ***@***.***>
Sent: Monday, March 28, 2022 1:17 PM
To: microsoft/AzureStorageExplorer ***@***.***>
Cc: Nadene Porter ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [microsoft/AzureStorageExplorer] Cannot access Storage Explorer subscription containers - password issue or account issue (Issue #5547)


@nfporter<https://secure-web.cisco.com/13Zs8613ZTeoztjhZTecnGadPia2qAtQOMDkPNUtlLaQCqKILGMsP92dksy-pk2FhF2lpJoAkZkvsVbJvRVlq3TXUk7VfZjqPEsNX_8_kafxb4iqPvtx6xvYiM2XB7C5lQNklK-gapQAdY72iV4SS2VszBKLgsLIv2xR1cURI7wKAnLzBsq5ztTmXnE0YsqRKQy-9TaRiV_yBOKzd7h6KqbeH6KfKB2XKXlxZMm-D8RgUccaYiKGaOIItA7ALTXNWxIPI5wfJMUpfiMKQRVUMAS0nLHJELhNvMVx3kohfpkgZbXHRYd5iiscFAXm5pOfWSl0_Qw5cfpRvwO4yMeiiBd9CKjJz3C4e2wFjnurvYBUBjt05qoA66XABZf2vS6epCdmTT3n4dVIukVycWsAj5qL7QAKrLf1LvVzWYbjYeEQcCH_cFR4FMIvRaK0oVgmaDhsJjGUh2BmSO9IDEQXzVA/https%3A%2F%2Fgithub.com%2Fnfporter>, when you do sign in, is it happening in your browser or in a small pop-up window?

**Comment by MRayermannMSFT** [comment]
@nfporter ok sounds good. If you could take the time to leave a comment sharing how you resolved this that'd be great. Thanks.
