### ISSUE TITLE
The path is incorrect for one QA resource group tab 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5551]
**Storage Explorer Version**: 1.24.0-dev
**Build Number**: 20220324.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.1 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Expand 'Disks' node.
2. Select one resource group -> Add it to the Quick Access node.
3. Open the QA resource group -> Hover over the opened tab.
4. Observe whether the path is correct.

## Expected Experience ##
The path is correct. (/Quick Access/Cti-kristine)

## Actual Experience ##
The path is incorrect.
![image](https://user-images.githubusercontent.com/41351993/159853464-920445df-8135-4ecc-be6a-472e0547f6ee.png)

**Comment by craxal** [comment]
I confirmed that the path of other QA node types is /Quick Access/*, so managed disks is inconsistent here.
