### ISSUE TITLE
Disable "File Changes Detected" globally

### ISSUE THREAD

**Issue by yaohualibin** [microsoft/AzureStorageExplorer#5552]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Disable "File Changes Detected" globally

### Desired Solution

Add an option to disable "File Changes Detected" dialog globally

**Comment by MRayermannMSFT** [comment]
Duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/1221
