### ISSUE TITLE
Unable to retrieve child resources.

### ISSUE THREAD

**Issue by dwillow316** [microsoft/AzureStorageExplorer#5553]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.23.0

### Regression From

na

### Architecture

x64

### Storage Explorer Build Number

1.23.0

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Authentication issue

### Steps to Reproduce

attempted to relogin

### Actual Experience

Unable to retrieve child resources.

Details:
{
  "name": "RestError",
  "message": "{\"odata.error\":{\"code\":\"AuthorizationPermissionMismatch\",\"message\":{\"lang\":\"en-US\",\"value\":\"This request is not authorized to perform this operation using this permission.\\nRequestId:0d6d16d9-2002-0074-6051-3f6bd7000000\\nTime:2022-03-24T07:34:56.8103843Z\"}}}",
  "stack": "RestError: {\"odata.error\":{\"code\":\"AuthorizationPermissionMismatch\",\"message\":{\"lang\":\"en-US\",\"value\":\"This request is not authorized to perform this operation using this permission.\\nRequestId:0d6d16d9-2002-0074-6051-3f6bd7000000\\nTime:2022-03-24T07:34:56.8103843Z\"}}}\n    at handleErrorResponse (C:\\Users\\dwilliams55\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-client\\dist\\index.js:1264:19)\n    at deserializeResponseBody (C:\\Users\\dwilliams55\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-client\\dist\\index.js:1199:45)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
  "statusCode": 403,
  "request": {
    "url": "https://poclab001.table.core.windows.net/Tables",
    "headers": {
      "accept": "application/json;odata=minimalmetadata",
      "x-ms-version": "2019-02-02",
      "dataserviceversion": "3.0",
      "accept-encoding": "gzip,deflate",
      "user-agent": "Microsoft Azure Storage Explorer, 1.23.0, win32 azsdk-js-data-tables/13.0.1 core-rest-pipeline/1.5.0 Node/v16.9.1 OS/(ia32-Windows_NT-10.0.19042)",
      "x-ms-client-request-id": "ffa03c5e-2bf7-472f-ae22-f8654a8e5b3a",
      "authorization": "Bearer JSON Web Token Redacted"
    },
    "method": "GET",
    "timeout": 0,
    "disableKeepAlive": false,
    "streamResponseStatusCodes": {},
    "withCredentials": false,
    "tracingOptions": {
      "spanOptions": {},
      "tracingContext": {
        "_currentContext": {}
      }
    },
    "requestId": "ffa03c5e-2bf7-472f-ae22-f8654a8e5b3a",
    "allowInsecureConnection": true,
    "enableBrowserStreams": false
  },
  "response": {
    "status": 403,
    "headers": {
      "cache-control": "no-cache",
      "transfer-encoding": "chunked",
      "content-type": "application/json;odata=minimalmetadata;streaming=true;charset=utf-8",
      "server": "Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0",
      "x-ms-request-id": "0d6d16d9-2002-0074-6051-3f6bd7000000",
      "x-ms-client-request-id": "ffa03c5e-2bf7-472f-ae22-f8654a8e5b3a",
      "x-ms-version": "2019-02-02",
      "x-content-type-options": "nosniff",
      "date": "Thu, 24 Mar 2022 07:34:56 GMT"
    },
    "request": {
      "url": "https://poclab001.table.core.windows.net/Tables",
      "headers": {
        "accept": "application/json;odata=minimalmetadata",
        "x-ms-version": "2019-02-02",
        "dataserviceversion": "3.0",
        "accept-encoding": "gzip,deflate",
        "user-agent": "Microsoft Azure Storage Explorer, 1.23.0, win32 azsdk-js-data-tables/13.0.1 core-rest-pipeline/1.5.0 Node/v16.9.1 OS/(ia32-Windows_NT-10.0.19042)",
        "x-ms-client-request-id": "ffa03c5e-2bf7-472f-ae22-f8654a8e5b3a",
        "authorization": "Bearer JSON Web Token Redacted"
      },
      "method": "GET",
      "timeout": 0,
      "disableKeepAlive": false,
      "streamResponseStatusCodes": {},
      "withCredentials": false,
      "tracingOptions": {
        "spanOptions": {},
        "tracingContext": {
          "_currentContext": {}
        }
      },
      "requestId": "ffa03c5e-2bf7-472f-ae22-f8654a8e5b3a",
      "allowInsecureConnection": true,
      "enableBrowserStreams": false
    },
    "bodyAsText": "{\"odata.error\":{\"code\":\"AuthorizationPermissionMismatch\",\"message\":{\"lang\":\"en-US\",\"value\":\"This request is not authorized to perform this operation using this permission.\\nRequestId:0d6d16d9-2002-0074-6051-3f6bd7000000\\nTime:2022-03-24T07:34:56.8103843Z\"}}}",
    "parsedBody": {
      "odataError": {
        "code": "AuthorizationPermissionMismatch",
        "message": {
          "lang": "en-US",
          "value": "This request is not authorized to perform this operation using this permission.\nRequestId:0d6d16d9-2002-0074-6051-3f6bd7000000\nTime:2022-03-24T07:34:56.8103843Z"
        }
      }
    },
    "parsedHeaders": {
      "cache-control": "no-cache",
      "transfer-encoding": "chunked",
      "content-type": "application/json;odata=minimalmetadata;streaming=true;charset=utf-8",
      "server": "Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0",
      "x-ms-request-id": "0d6d16d9-2002-0074-6051-3f6bd7000000",
      "x-ms-client-request-id": "ffa03c5e-2bf7-472f-ae22-f8654a8e5b3a",
      "x-ms-version": "2019-02-02",
      "x-content-type-options": "nosniff",
      "date": "Thu, 24 Mar 2022 07:34:56 GMT"
    }
  },
  "details": {
    "cache-control": "no-cache",
    "transfer-encoding": "chunked",
    "content-type": "application/json;odata=minimalmetadata;streaming=true;charset=utf-8",
    "server": "Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0",
    "x-ms-request-id": "0d6d16d9-2002-0074-6051-3f6bd7000000",
    "x-ms-client-request-id": "ffa03c5e-2bf7-472f-ae22-f8654a8e5b3a",
    "x-ms-version": "2019-02-02",
    "x-content-type-options": "nosniff",
    "date": "Thu, 24 Mar 2022 07:34:56 GMT",
    "odataError": {
      "code": "AuthorizationPermissionMismatch",
      "message": {
        "lang": "en-US",
        "value": "This request is not authorized to perform this operation using this permission.\nRequestId:0d6d16d9-2002-0074-6051-3f6bd7000000\nTime:2022-03-24T07:34:56.8103843Z"
      }
    }
  }
}

### Expected Experience

.

### Additional Context

.

**Comment by MRayermannMSFT** [comment]
@dwillow316 it looks like you are trying to list the tables in your storage account via the tree view, yes? It also seems like you don't have access to your storage account keys. This is fine, but you will need to have either the Table Data Reader or Table Data Contributor role first. Please confirm that your account has either of those roles assigned to them for this storage account.

**Comment by dwillow316** [comment]
THanks mate!
________________________________
