### ISSUE TITLE
Container missing via StorageExplorer but present via Portal or SDK

### ISSUE THREAD

**Issue by cristian-eriomenco** [microsoft/AzureStorageExplorer#5554]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.23.0

### Architecture

x64

### Storage Explorer Build Number

20220223.14

### Platform

Windows

### OS Version

Windows 10 Pro 21h1

### Bug Description

Some blob containers are reported as missing in storage explorer but visible via Azure Portal or via c# SDK.

### Steps to Reproduce

1. Launch Storage Explorer
2. Open a storage account
3. Right click on Blob Containers
4. Select Open Container By Name
5. Type name of an **existing container** and click Search
6. It could be that the container is not found "No results were found" even though it exists
7. Navigate to azure portal to the same storage account and search for same container name
8. Observe the container exists

### Actual Experience

![image](https://user-images.githubusercontent.com/7792886/159963090-1600f464-df91-4bb5-8132-bdedb186aff8.png)

### Expected Experience

Expected to see the container in storage explorer and in the azure portal

### Additional Context

When a container is found missing via the storage explorer, I've asked my colleagues to try to find same container via their own machines using storage explorer. Every single time the encounter exactly the same outcome -> container is showing as missing.

And if I ask them as well to go to the portal, the container would correctly show up.

If trying to get the container via code using the exactly same connectionstring as the StorageExplorer, the container will be present.

The container is accessed using AccountName+AccountKey with full control over it.
The container does contain actual files it is not empty, and it is not deleted or altered.
We've seen at least 5 cases with no specific pattern, on any machine.
The container creation time varies from weeks to years.
The storage account connection is established via connectionString with accountName+key (not via sas token or azure subscription)
We've seen this bug happening in past releases too (at least 6 months).

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having this problem we recommend opening an Azure support ticket. Alternatively you can open a new issue here.
