### ISSUE TITLE
User study - A more intuitive and discoverable flow after sign-in (to show connected Azure resources)

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#5555]
It was not very obvious to the participants that after sign-in, one already has connected to his/her Azure resources.  A large % of the participants needed hints to switch from the account management panel to the treeview panel.  Didn't register to click the "Open Explorer" to the treeview panel.

**Comment by MRayermannMSFT** [comment]
Have initial meeting to decide what changes to experience we want to do.
