### ISSUE TITLE
User study - "Local & Attached" needs a more explicit description

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#5556]
The name of the "Local & Attach" node was not very descriptive to the participants, which led to unnecessary confusion or guess, especially on the "Local" part.

**Comment by MRayermannMSFT** [comment]
Have initial meeting to discuss what we might want to do (changing terms, separating, etc.). Go from there.

**Comment by jinglouMSFT** [comment]
Change to:  "Emulator & Attached" per discussion.
