### ISSUE TITLE
User study - The blob search experience

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#5557]
- All participants attempted to used the address bar to search for individual blobs.  We do list the folder if one types the name of the folder in the address, which makes the experiences more confusing.
- Most didn't register "Filter" as "Search"
- The "View filter panel" was always the last to be looked at when asked to search for a specific blob
- Suggested to have a toolbar button or reposition the current "View filter panel" button
- Wanted "Search prefix" as the label for the toolbar button

One proposal is to change the icon for the "View filter panel" and likely the tooltip as well. We can further discuss if we should reposition the button somewhere else.  We should also address the address bar misuse issue in the top bullet above.

**Comment by MRayermannMSFT** [comment]
Icon has been changed to a "filter" icon to make it more obvious filtering is in the side panel. The filter related things are also now at the top of the side panel.
