### ISSUE TITLE
User study - Confusion between ACL permissions and Access Policies

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#5558]
Most participants had issues on telling the differences between the ACL permission and the Access Policies on the context menu.  It's also possible that some didn't know the differences between the two services.

**Comment by MRayermannMSFT** [comment]
Related:

- https://github.com/microsoft/AzureStorageExplorer/issues/4062
- https://github.com/microsoft/AzureStorageExplorer/issues/4061
- https://github.com/microsoft/AzureStorageExplorer/issues/4060
- https://github.com/microsoft/AzureStorageExplorer/issues/4059
