### ISSUE TITLE
Add to quick access does not do anything

### ISSUE THREAD

**Issue by theelderwand** [microsoft/AzureStorageExplorer#556]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows
**Architecture**: ia32
**Regression From**: First time trying this

#### Steps to Reproduce: ####
1. Navigate to a cosmos db from a subscription
2. Right click on the resource and click on "Add to Quick Access"

#### Expected Experience: ####
Expect the resource to be available in Quick Access

#### Actual Experience: ####
No resource is available in Quick Access.

**Comment by Hamaze** [comment]
I'm experiencing the same

**Comment by DonFrazier** [comment]
Version 1.12.0.  Quick Access shows the animated dots and Loading ...
Platform: WIndows
Build: 20200116.10
Commit: 0a86d4ecc
It never goes away
I can't add anything to Quick Access

There should be a Copy to clipboard button on Help -> About so I don't have to transcribe this.

**Comment by JasonYeMSFT** [comment]
@DonFrazier This may happen when there exists some problematic nodes such that the SDK cannot load its attributes. We have fixed a bug where we almost infinitely retry on those nodes, which blocks all the nodes that are still good and will include in our v1.13.0 release. You can either wait for the fix or go to Dev tools -> Applications -> "StorageExplorer_InPlaceQuickAccessItems_v1" and clear its data. That way, all the quick access nodes will be gone and you can re-add valid Quick Access nodes.

**Comment by DonFrazier** [comment]
Thanks for the upcoming fix.  I'm on 1.12 and can't seem to find a Dev Tools option.  Could you point out where I'm missing it?

**Comment by JasonYeMSFT** [comment]
You can either access it through F12 on keyboard or go to Help -> Toggle Dev Tools

**Comment by JasonYeMSFT** [comment]
@DonFrazier Are you still having issue with the Quick Access?

**Comment by DonFrazier** [comment]
After updating to 1.13.0 Quick Access appears to be working.
