### ISSUE TITLE
User study - Add Quick Access status to the activity log

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#5560]
When adding a node to Quick Access, we should add a status in the Activity log.  We currently don't have any visual cue.  If one has a long list of resources and QA is off screen, it's hard to tell where to verify whether the action was successful.

**Comment by jinglouMSFT** [comment]
Per discussion, let's add a status update to the activity log:
- when/after pining a node to Quick Access
- when/after unpinning a node from Quick Access

Also, add a clickable action to go to the node in Quick Access. The clickable action should be right-aligned.

**Comment by craxal** [comment]
Adding an activity when adding or removing Quick Access items is super easy. There seems to be a problem, however, with the action that selects the newly added Quick Access item. The node IDs returned by the query used to find the node to select don't coincide with the IDs of the actual Quick Access child nodes, meaning we can't use the find result to actually select the node. Looking into this further.

**Comment by craxal** [comment]
Node selection problem has been addressed. Code has been merged.
