### ISSUE TITLE
User study - Provide search on the Settings page

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#5561]
We have lots of parameters users can customize that are a little hard to find now. Suggestion was to add a search capability.

- [x] Ensure configuration type definitions in SDK are up to date.
- [x] Display all settings on one page and modify category click behavior to scroll page.
- [x] Add search box that hides widgets (and empty categories?) not matching search criteria.

**Comment by MRayermannMSFT** [comment]
Design and determine scope in 1.26
