### ISSUE TITLE
Rename option missing

### ISSUE THREAD

**Issue by Gourab3129** [microsoft/AzureStorageExplorer#5566]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.23.0

### Architecture

x64

### Storage Explorer Build Number

20220223.14

### Platform

Windows

### OS Version

Windows 10 pro

### Bug Description

There is no rename option/feature on the explorer for which I'm not able to rename my resources. Does anyone have the same issue?

![image](https://user-images.githubusercontent.com/102390779/160207720-cb437f63-216c-4bd7-9a07-bec25691f394.png)

### Steps to Reproduce

1. Launch explorer
2. Select the blob you want to edit
3. Click on the file 

### Actual Experience

As there is no rename feature/option, I'm not able to edit the names of my files.

**Comment by MRayermannMSFT** [comment]
@[Gourab3129](https://github.com/Gourab3129) for certain services (such as non-gen2 blobs), rename was removed in favor of clone. This was done for services where a rename API is not available from the storage service. If you'd like to do a rename you will need to use "Clone". That will create a copy of the thing you are cloning in the same location with whatever name you'd like. After you do the clone you can then delete the original copy.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having this problem we recommend opening an Azure support ticket. Alternatively you can open a new issue here.
