### ISSUE TITLE
ORDER BY c.id returns blank page

### ISSUE THREAD

**Issue by ZehuaZhang** [microsoft/AzureStorageExplorer#557]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows
**Architecture**: ia32

#### Steps to Reproduce: ####
1. Select and Open a document and write ORDER BY c.id

#### Expected Experience: ####
ORDER BY c._ts works, but ORDER BY c.id not working

#### Actual Experience: ####
ORDER BY c.id returns blank page

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
