### ISSUE TITLE
Only display a successful activity log if selecting one of the source items on the 'Retry Azcopy' dialog regardless of whatever option is selected in the Overwrite part

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5570]
**Storage Explorer Version**: 1.23.0
**Build Number**: 20220329.2
**Branch**: hotfix/1.23.1
**Platform/OS**: Windows 10
**Architecture** ia32
**How Found**: Exploratory testing 
**Regression From**: Not a regression

## Bug Description ##
Only display a successful activity log if selecting one of the source items on the 'Retry Azcopy' dialog regardless of whatever option is selected in the Overwrite part.
![image](https://user-images.githubusercontent.com/41351993/160589208-19c634b5-63f1-4118-b6a2-c6fff49a77cb.png)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create one blob container -> Upload two blobs from one server.
3. Upload the same two blobs from the same source.
4. There is a conflict dialog -> Select 'Do not upload' -> Click 'Apply to All Conflicts'.
5. There is a skip activity log -> Click 'Retry...'.
6. Select one item on the 'Retry Azcopy' -> Select 'Prompt for overwrite' -> Click 'Retry Selected'.
7. Check whether there is a conflict dialog. 

## Expected Experience ##
There is a conflict dialog.

## Actual Experience ##
1. There is no conflict dialog.
2. There is a successful activity log.
![image](https://user-images.githubusercontent.com/41351993/160586907-8da46591-6427-4b02-af3a-ac84fce0fbbe.png)

## Additional Context ##
1. This issue also reproduces for file shares.
2. Similar issue: [4694](https://github.com/microsoft/AzureStorageExplorer/issues/4694).

**Comment by v-xianya** [comment]
This issue still reproduces on the latest main build/20220406.4. I will share the reproduces file to you in the teams.

**Comment by JasonYeMSFT** [comment]
We do have a bug in the retry code. Let me see if I can fix it.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220410.3. Fixed,
