### ISSUE TITLE
Can't upload some files or folder from my local disk

### ISSUE THREAD

**Issue by Nico26-sw** [microsoft/AzureStorageExplorer#5572]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.23.0

### Architecture

x64

### Storage Explorer Build Number

20220223.14

### Platform

Linux

### OS Version

Ubuntu 20.04

### Bug Description

When I want to upload a local file or folder, my local `/work` folder is not selectable in the "Choose folder to upload". It is not even listed. Here is the content of my root file system:

```
$ ls -al /
total 184
drwxr-xr-x  21 root    root     4096 Oct  7  2020 ./
drwxr-xr-x  21 root    root     4096 Oct  7  2020 ../
lrwxrwxrwx   1 root    root        7 Aug 23  2019 bin -> usr/bin/
drwxr-xr-x   4 root    root     4096 Mar 24 09:21 boot/
drwxrwxr-x   2 root    root     4096 Aug 23  2019 cdrom/
drwxr-xr-x  25 root    root     5060 Mar 29 14:17 dev/
drwxr-xr-x 160 root    root    12288 Mar 29 09:03 etc/
drwxr-xr-x   3 root    root     4096 Oct 14 16:05 home/
lrwxrwxrwx   1 root    root       32 Jan  8  2020 initrd.img -> boot/initrd.img-5.0.0-38-generic
lrwxrwxrwx   1 root    root       32 Jan  8  2020 initrd.img.old -> boot/initrd.img-5.0.0-37-generic
lrwxrwxrwx   1 root    root        7 Aug 23  2019 lib -> usr/lib/
lrwxrwxrwx   1 root    root        9 Aug 23  2019 lib32 -> usr/lib32/
lrwxrwxrwx   1 root    root        9 Aug 23  2019 lib64 -> usr/lib64/
lrwxrwxrwx   1 root    root       10 Aug 23  2019 libx32 -> usr/libx32/
drwx------   2 root    root    16384 Aug 23  2019 lost+found/
drwxr-xr-x   3 root    root     4096 Sep  4  2019 media/
drwxr-xr-x   2 root    root     4096 Apr 16  2019 mnt/
drwxr-xr-x  14 root    root     4096 Jun  8  2021 opt/
dr-xr-xr-x 421 root    root        0 Mar 24 15:21 proc/
drwx------  10 root    root     4096 Sep 10  2021 root/
drwxr-xr-x  42 root    root     1320 Mar 25 11:15 run/
lrwxrwxrwx   1 root    root        8 Aug 23  2019 sbin -> usr/sbin/
drwxr-xr-x  16 root    root     4096 Nov 22 14:22 snap/
drwxr-xr-x   2 root    root     4096 Apr 16  2019 srv/
dr-xr-xr-x  13 root    root        0 Mar 24 15:21 sys/
drwxrwxrwt  33 root    root    98304 Mar 29 14:40 tmp/
drwxr-xr-x  14 root    root     4096 May  6  2020 usr/
drwxr-xr-x  14 root    root     4096 Apr 16  2019 var/
drwxr-xr-x  10 njoyeux njoyeux  4096 Dec  9 18:40 work/
```

Here is what I can select:
![image](https://user-images.githubusercontent.com/54840037/160615315-b729a939-d47d-4279-9462-8fa66c63bd8e.png)

I changed the ownership of work folder to root, no change.
I checked Storage Explorer logs but didn't see any errors.

Also, I noticed this weird `writable` file, don't know if it is related tho.

### Steps to Reproduce

Actually I don't know how to reproduce it, I imagine this bug is somehow related to a group or permission issue. Any help would be appreciated.

### Actual Experience

I can't upload any file or folder located on my local disk.

### Expected Experience

I can upload any file or folder located on my local disk.

### Additional Context

I have a classical ubuntu 20.04 installation.

**Comment by MRayermannMSFT** [comment]
@Nico26-sw am I correct in assuming you installed via Snap store? If so, then yes, I agree this is probably some sort of permission issue with the folder.

> I changed the ownership of work folder to root, no change.

Darn, I was going to suggest this!

- Is `work` on a separate partition/drive/removable device?
- Can you access stuff in your home dir?
- If yes, then if you create a similar folder/make a copy of `work`/move `work` to your home dir can you access it?
-

**Comment by Nico26-sw** [comment]
Hi @MRayermannMSFT 
Thanks for taking some time to look at my issue.

Yes I installed it via snap store

```
$ sudo snap info storage-explorer
name:      storage-explorer
summary:   Optimize your Azure storage management
publisher: Microsoft Azure Storage Tools (msft-storage-tools✓)
store-url: https://snapcraft.io/storage-explorer
license:   unset
description: |
  Upload, download, and manage Azure blobs, files, queues, and tables, as well as Azure Cosmos DB
  and Azure Data Lake Storage entities. Easily access virtual machine disks, and work with either
  Azure Resource Manager or classic storage accounts. Manage and configure cross-origin resource
  sharing rules.
  
  - Management for all your storage accounts and multiple subscriptions across Azure, Azure Stack,
  and government cloud
  - Accessible, intuitive, feature-rich graphical user interface (GUI) for full management of cloud
  storage resources
  - Robust security features like cross-origin resource sharing and shared access signature to help
  protect your data access wherever you are
  
  Learn more at https://azure.microsoft.com/en-us/features/storage-explorer.
  
  Storage Explorer requires the use of a password manager, which may need to be connected manually
  before Storage Explorer will work correctly. You can connect Storage Explorer to your system's
  password manager with the following command:
  
      snap connect storage-explorer:password-manager-service :password-manager-service
commands:
  - storage-explorer
snap-id:      mOjZRL1yFULZQ1JKXR8lFteDZ5s1BtRh
tracking:     latest/stable
refresh-date: 33 days ago, at 09:07 CET
channels:
  latest/stable:    1.23.0 2022-03-02 (32) 208MB -
  latest/candidate: 1.23.0 2022-03-02 (32) 208MB -
  latest/beta:      1.23.0 2022-03-02 (32) 208MB -
  latest/edge:      1.23.0 2022-03-02 (32) 208MB -
installed:          1.23.0            (32) 208MB -
```

To answer your questions

- `work` is in the same partition/drive than the rest. I actually have one partition on my SSD.
- Yes I can access everything in my home dir from the dialog box
- I partially copied `work` to my home dir (too huge to be wholly copied) and I was able to access it from the dialog box.

HTH

**Comment by Nico26-sw** [comment]
Hi,
Thanks for pointing out the issue might be related to snap. I uninstalled the snap version and installed the tar version and the issue is gone.
So I confirm the problem is related to snap. I'm sorry I can't help anymore in debugging the issue as described here.
Feel free to close the ticket, or let me know if you want me to give more details about my file system permissions or other info.
Thanks

**Comment by Nico26-sw** [comment]
On a separate subject, the tar version is way faster than the snap one, thanks!!
