### ISSUE TITLE
There is an extra scrollbar in the 'Clone and Rehydrate' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5574]
**Storage Explorer Version**: 1.24.0-dev
**Build Number**: 20220330.3
**Branch**: main
**Platform/OS**: Windows 10
**Architecture** ia32
**How Found**: From running test case
**Regression From**: Previous release (1.23.1)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create one blob container -> Upload one blob and set its 'Target Access Tier' to 'Archive'.
3. Right click the blob -> Click 'Clone and Rehydrate...'.
4. Check there is no extra scrollbar in the 'Clone and Rehydrate' dialog.

## Expected Experience ##
There is no extra scrollbar.

## Actual Experience ##
There is an extra scrollbar.
![image](https://user-images.githubusercontent.com/41351993/160743024-de9cdd34-2bcc-4ac1-a064-e0341f33a57e.png)

## Additional Context ##
This issue doesn't reproduce on Linux/Mac.

**Comment by JasonYeMSFT** [comment]
Our auto-resizing logic for dialog is weird. This problem only seems to happen at 100% zoom level and below that's why I didn't catch it.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220407.3. Fixed.
