### ISSUE TITLE
RestError: One of the request inputs is not valid

### ISSUE THREAD

**Issue by Saumil13** [microsoft/AzureStorageExplorer#5579]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.23.0

### Regression From

1.22.0

### Architecture

x64

### Storage Explorer Build Number

20220223.14

### Platform

Windows

### OS Version

Windows 11

### Bug Description

{
  "name": "RestError",
  "message": "{\"odata.error\":{\"code\":\"InvalidInput\",\"message\":{\"lang\":\"en-US\",\"value\":\"One of the request inputs is not valid.\\nRequestId:33b42560-e002-0021-6d09-45dc76000000\\nTime:2022-03-31T14:11:57.0020853Z\"}}}",
  "stack": "RestError: {\"odata.error\":{\"code\":\"InvalidInput\",\"message\":{\"lang\":\"en-US\",\"value\":\"One of the request inputs is not valid.\\nRequestId:33b42560-e002-0021-6d09-45dc76000000\\nTime:2022-03-31T14:11:57.0020853Z\"}}}\n    at handleErrorResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-client\\dist\\index.js:1264:19)\n    at deserializeResponseBody (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-client\\dist\\index.js:1199:45)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
  "statusCode": 400,
  "request": {
    "url": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx?NextPartitionKey=1!48!M2IzMDNiYmUtNDcwNi00ZTY4LTQ2MTgtZDE4ODFiNjNiN2Vj&NextRowKey=",
    "headers": {
      "accept": "application/json;odata=minimalmetadata",
      "x-ms-version": "2019-02-02",
      "dataserviceversion": "3.0",
      "accept-encoding": "gzip,deflate",
      "user-agent": "Microsoft Azure Storage Explorer, 1.23.0, win32 azsdk-js-data-tables/13.0.1 core-rest-pipeline/1.5.0 Node/v16.9.1 OS/(ia32-Windows_NT-10.0.22000)",
      "x-ms-client-request-id": "e981d8f2-7116-43fe-b100-e1d433e5b56f",
      "x-ms-date": "Thu, 31 Mar 2022 14:11:57 GMT",
      "authorization": "SharedKeyLitexxxxxxxxxxxxxstate:M+Apox+8JihiWWfxcxSOJqx+iWE12s55TaPN6iRZhsQ="
    },
    "method": "GET",
    "timeout": 0,
    "disableKeepAlive": false,
    "streamResponseStatusCodes": {},
    "withCredentials": false,
    "tracingOptions": {
      "spanOptions": {},
      "tracingContext": {
        "_currentContext": {}
      }
    },
    "requestId": "e981d8f2-7116-43fe-b100-e1d433e5b56f",
    "allowInsecureConnection": true,
    "enableBrowserStreams": false
  },
  "response": {
    "status": 400,
    "headers": {
      "content-length": "199",
      "content-type": "application/json",
      "server": "Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0",
      "x-ms-request-id": "33b42560-e002-0021-6d09-45dc76000000",
      "x-ms-client-request-id": "e981d8f2-7116-43fe-b100-e1d433e5b56f",
      "x-ms-version": "2019-02-02",
      "x-ms-error-code": "InvalidInput",
      "date": "Thu, 31 Mar 2022 14:11:56 GMT"
    },
    "request": {
      "url": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx?NextPartitionKey=1!48!M2IzMDNiYmUtNDcwNi00ZTY4LTQ2MTgtZDE4ODFiNjNiN2Vj&NextRowKey=",
      "headers": {
        "accept": "application/json;odata=minimalmetadata",
        "x-ms-version": "2019-02-02",
        "dataserviceversion": "3.0",
        "accept-encoding": "gzip,deflate",
        "user-agent": "Microsoft Azure Storage Explorer, 1.23.0, win32 azsdk-js-data-tables/13.0.1 core-rest-pipeline/1.5.0 Node/v16.9.1 OS/(ia32-Windows_NT-10.0.22000)",
        "x-ms-client-request-id": "e981d8f2-7116-43fe-b100-e1d433e5b56f",
        "x-ms-date": "Thu, 31 Mar 2022 14:11:57 GMT",
        "authorization": "SharedKeyLitexxxxxxxxxxxxxstate:M+Apox+8JihiWWfxcxSOJqx+iWE12s55TaPN6iRZhsQ="
      },
      "method": "GET",
      "timeout": 0,
      "disableKeepAlive": false,
      "streamResponseStatusCodes": {},
      "withCredentials": false,
      "tracingOptions": {
        "spanOptions": {},
        "tracingContext": {
          "_currentContext": {}
        }
      },
      "requestId": "e981d8f2-7116-43fe-b100-e1d433e5b56f",
      "allowInsecureConnection": true,
      "enableBrowserStreams": false
    },
    "bodyAsText": "{\"odata.error\":{\"code\":\"InvalidInput\",\"message\":{\"lang\":\"en-US\",\"value\":\"One of the request inputs is not valid.\\nRequestId:33b42560-e002-0021-6d09-45dc76000000\\nTime:2022-03-31T14:11:57.0020853Z\"}}}",
    "parsedBody": {
      "odataError": {
        "code": "InvalidInput",
        "message": {
          "lang": "en-US",
          "value": "One of the request inputs is not valid.\nRequestId:33b42560-e002-0021-6d09-45dc76000000\nTime:2022-03-31T14:11:57.0020853Z"
        }
      }
    },
    "parsedHeaders": {
      "errorCode": "InvalidInput",
      "content-length": "199",
      "content-type": "application/json",
      "server": "Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0",
      "x-ms-request-id": "33b42560-e002-0021-6d09-45dc76000000",
      "x-ms-client-request-id": "e981d8f2-7116-43fe-b100-e1d433e5b56f",
      "x-ms-version": "2019-02-02",
      "date": "Thu, 31 Mar 2022 14:11:56 GMT"
    }
  },
  "details": {
    "errorCode": "InvalidInput",
    "content-length": "199",
    "content-type": "application/json",
    "server": "Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0",
    "x-ms-request-id": "33b42560-e002-0021-6d09-45dc76000000",
    "x-ms-client-request-id": "e981d8f2-7116-43fe-b100-e1d433e5b56f",
    "x-ms-version": "2019-02-02",
    "date": "Thu, 31 Mar 2022 14:11:56 GMT",
    "odataError": {
      "code": "InvalidInput",
      "message": {
        "lang": "en-US",
        "value": "One of the request inputs is not valid.\nRequestId:33b42560-e002-0021-6d09-45dc76000000\nTime:2022-03-31T14:11:57.0020853Z"
      }
    }
  }
}

### Steps to Reproduce

1. Open storage explorer
2. Try to load the table - It failed with the following error. 
3. Note: I am able to load the table from the web [Storage explorer failed]

### Actual Experience

Should able to load table from Storage explorer similar to web

**Comment by craxal** [comment]
@Saumil13 We've had several issues opened very similar to this (see #5407, #5434)

Take a close look at the query parameter in the request URL. Notice that the `NextPartitionKey` parameter has a value but the `NextRowKey` parameter does not. That's where your problem is coming from. Removing the empty `NextRowKey` parameter will resolve the REST error.

We've already merged a fix for this issue and will be available in a release very soon.
