### ISSUE TITLE
Please add a button to clear the content of a blob container (delete all files)

### ISSUE THREAD

**Issue by hannesne** [microsoft/AzureStorageExplorer#558]
At the moment I can only see how to delete all the cached files. I want to clear my container, which contains more blobs than what is cached.

**Comment by jinglouMSFT** [comment]
Any particular reasons why deleting the container and all its contents doesn't serve the purpose?  Thanks.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.

**Comment by MRayermannMSFT** [comment]
Won't fix. We recommend just deleting the container. It'll be much faster.
