### ISSUE TITLE
Import activity error message no longer reports success/error counts

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5580]
**Storage Explorer Version**: 1.24.0-dev
**Build Number**: 20220401.2
**Branch**: hotfix/1.23.1
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.3 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: Exploratory testing
**Regression From**: Not a regression 

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Import the below csv file.
[table.csv](https://github.com/microsoft/AzureStorageExplorer/files/8395418/table.csv)

4. Check whether the activity log info matches the actual behavior.

## Expected Experience ##
The activity log info matches the actual behavior.

## Actual Experience ##
The activity log info doesn't match the actual behavior.
1. There is a failed activity log.
![image](https://user-images.githubusercontent.com/41351993/161214979-a31242db-96a6-481b-b6bd-729f2437d8fe.png)
![image](https://user-images.githubusercontent.com/41351993/161214994-b6559caa-c4fc-464d-9060-38624aa74df9.png)

2. There are imported entities after manually refreshing the editor.
![image](https://user-images.githubusercontent.com/41351993/161215870-d0504201-71c0-4520-9638-d44421eeb5b7.png)

**Comment by craxal** [comment]
This looks like expected behavior to me. Imports happen in batches, and each batch must have the same partition key. It's entirely possible for one batch to fail when others succeeded. In this case, two previous batches succeeded. The third batch failed because of a bad property name.

That said, we aren't doing any validation for type annotated files, so we could consider adding that.

**Comment by craxal** [comment]
It looks like the code is only refreshing the explorer on a successful import, but since imports are technically happening even when errors occur, we should probably refresh. I'd consider this a separate issue, so please open a new work item.

**Comment by v-xianya** [comment]
@craxal Thank you for the response! 
We opened a new bug [5620](https://github.com/microsoft/AzureStorageExplorer/issues/5620) for the question.
