### ISSUE TITLE
There is an extra scroll bar in the 'Upload' dialog for one emulator blob container

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5582]
**Storage Explorer Version:** 1.24.0-dev
**Build Number:** 20220401.7
**Branch:** main
**Platform/OS:** Windows 10
**Architecture:** ia32
**Azurite Version:** 3.16.0
**Language:** Czech/German/Spanish/French /Italian/Japanese/Dutch Polish/Portuguese/Russian/Swedish 
**How Found:** From running test cases
**Regression From:** Previous release (1.21.3)

## Steps to Reproduce ##

1. Install and run Azurite 3.16.0 -> Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Deutsch' -> Restart Storage Explorer.
3. Expand 'Local & Attached -> Storage Accounts -> (Emulator - Default Ports) (Key)' -> Blob Containers.
4. Create a blob container -> Click 'Upload -> Upload Folder/Files...'.
5. Check there is no extra scrollbar in the 'Upload' dialog.

## Expected Experience ##
There is no extra scrollbar.
![image](https://user-images.githubusercontent.com/87792676/161372292-f33d7efa-8274-4dc7-8677-041262f566d8.png)

## Actual Experience ##
There is an extra scrollbar.
![image](https://user-images.githubusercontent.com/87792676/161371762-8233264a-ccdf-48eb-95d2-2413d0b8b94c.png)

**Comment by MRayermannMSFT** [comment]
We should have the upload dialog be the same width regardless if the container is emulator or not....

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220610.4. Fixed.
