### ISSUE TITLE
Attempting to delete more than 101 rows in StorageTable results in an error

### ISSUE THREAD

**Issue by kon-iro** [microsoft/AzureStorageExplorer#5585]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.23.0

### Regression From

1.21.0

### Architecture

i86

### Storage Explorer Build Number

20220223.14

### Platform

Windows

### OS Version

Windows11

### Bug Description

Attempting to delete more than 101 rows in StorageTable results in an error

` "name": "RestError",
 "message": "99:The batch request operation exceeds the maximum 100 changes per change set.\nRequestId:0076cebe-0002-0012-6588-484ca9000000\nTime:2022-04-05T01:03:13.2742193Z",
 "stack": "RestError: 99:The batch request operation exceeds the maximum 100 changes per change set.\nRequestId:0076cebe-0002-0012-6588-484ca9000000\nTime:2022-04-05T01:03:13.2742193Z\n    at handleBodyError (C:\\Users\\mizu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\data-tables\\dist\\index.js:4050:11)\n    at C:\\Users\\mizu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\data-tables\\dist\\index.js:4021:13\n    at Array.map (<anonymous>)\n    at parseTransactionResponse (C:\\Users\\mizu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\data-tables\\dist\\index.js:4010:36)\n    at InternalTableTransaction.submitTransaction (C:\\Users\\mizu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\data-tables\\dist\\index.js:3976:20)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async TableClient.runOperation (C:\\Users\\mizu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-table-extension\\dist\\src\\Clients\\TableStorageClient.js:76:24)\n    at async C:\\Users\\mizu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-table-extension\\dist\\src\\Actions\\TableActions.js:62:9\n    at async Promise.all (index 0)\n    at async Object.deleteEntities (C:\\Users\\mizu\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-table-extension\\dist\\src\\Actions\\TableActions.js:66:9)"`

### Steps to Reproduce

1. Select 101 or more rows in the Storage Table
2. Delete

### Actual Experience

The selected row is not deleted,

### Additional Context

In Version 1.21.0, even if you selected 101 or more rows, you could delete them without any problem.

**Comment by gdignard** [comment]
Came here to report the same thing. Looks like the batch code got killed off.

There's obviously a workaround (delete 100 at a time) but that VERY quickly becomes unworkable for larger deletes.

This really needs more attention than it seems to be getting... Almost a week and not even a comment or triage?

**Comment by craxal** [comment]
Yes, this is a bug. The service limits batch sizes to 100, and we're not breaking up the entities into batches of no more than 100.

@kon-iro @gdignard Can you explain in more detail exactly how you selected more than 100 entities? Did you use the "Select all cached" command? Are you trying to delete all entities or just a subset of entities in the table?

If you're encountering this issue, we recommend the following workarounds:
* If you're trying to delete all entities from the table, consider whether deleting the entire table is a suitable option.
* As suggested above, limit your deletes to one page (100 entities) at a time.
* Revert to a previous version until this issue is fixed.

**Comment by gdignard** [comment]
In my case, it was a result of a query though it was far too large to do it 100 at a time.

Our resolution was to perform the query and delete via the API.

We'll revert and look forward to 1.24!

**Comment by craxal** [comment]
Even with a query, you should only be able to select one page's worth unless you use "Select all cached".

**Comment by kon-iro** [comment]
I was having problems with the two patterns.
1. Hold down the shift key and select the range you want to delete over several pages.
2. Select "Select all cached" from the query results
