### ISSUE TITLE
The blob whose name contains ': or "' can't be opened by clicking 'Yes' on the security warning dialog popped up by executing open action

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5589]
**Storage Explorer Version**: 1.23.1
**Build Number**: 20220406.1
**Branch**: hotfix/1.23.1
**Platform/OS**: Windows 10
**Architecture** ia32
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob whose name contains ': or "'.
3. Try to open the blob -> Click 'Yes' on the security warning dialog if there is one.
4. Check whether the blob is opened.

## Expected Experience ##
The blob is opened.

## Actual Experience ##
The blob is not opened.
Here is a record:
![atest0406](https://user-images.githubusercontent.com/41351993/161928465-2fab87ac-2fba-44b5-b21c-faa9d320c470.gif)

## Additional Context ##
1. There is a security warning dialog when opening one blob which has a trusted extension if the blob name contains ': or "'.
2. This issue doesn't reproduce on Mac/Linux.

**Comment by MRayermannMSFT** [comment]
Need to find the duplicate. Issue is that AzCopy is renaming the file due to invalid Windows characters, so our open code fails.

**Comment by MRayermannMSFT** [comment]
Actually, Jason remembers doing a workaround for the file name mismatch. Something new is probably broken. Should investigate.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220610.4. Fixed.
