### ISSUE TITLE
 Unable to create container in blob storage module Edge

### ISSUE THREAD

**Issue by ksh7393** [microsoft/AzureStorageExplorer#5590]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.23.0

### Architecture

i86

### Storage Explorer Build Number

20220223.14

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Unable to create blob container in blob storage module Edge. 

**Note**: VM is up and running with modules.

Getting below error in azure storage explorer

Unable to retrieve child resources.

**Details:
{
  "name": "FetchError",
  "message": "request to http://xxxxxx:11002/cvtlocal?comp=list&include=metadata failed, reason: connect ETIMEDOUT xxxx:11002",
  "stack": "FetchError: request to http://xxxxx:11002/cvtlocal?comp=list&include=metadata failed, reason: connect ETIMEDOUT xxxx:11002\n    at ClientRequest.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1491:11)\n    at ClientRequest.emit (node:events:394:28)\n    at Socket.socketErrorListener (node:_http_client:447:9)\n    at Socket.emit (node:events:394:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "ETIMEDOUT",
  "code": "ETIMEDOUT"
}**

### Steps to Reproduce

1. Launch Storage explorer
2. Connect to edge blob storage account using connection string in the below format
**DefaultEndpointsProtocol=http;BlobEndpoint=http://<host device name>:11002/<your local account name>;AccountName=<your local account name>;AccountKey=<your local account key>;**
3. expand the blob containers
4. create new container
 

### Actual Experience

getting error popup with connection timeout

### Expected Experience

Container is successfully created

**Comment by hirez-masmith** [comment]
I'm seeing this same callstack when trying to view the containers of a premium blob storage account. Getting similar errors from the web portal. Started around the same time as this was logged. 
I've tried removing and re-adding my public IP address for direct storage explorer access with no luck.


```
Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://***.blob.core.windows.net/?comp=list&include=metadata failed, reason: connect ETIMEDOUT ****:443",
  "stack": "FetchError: request to https://*****.blob.core.windows.net/?comp=list&include=metadata failed, reason: connect ETIMEDOUT ****:443\n    at ClientRequest.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1491:11)\n    at ClientRequest.emit (node:events:394:28)\n    at TLSSocket.socketErrorListener (node:_http_client:447:9)\n    at TLSSocket.emit (node:events:394:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "ETIMEDOUT",
  "code": "ETIMEDOUT"
}
```

Storage explorer version 1.23.0
Storage explorer build number 20220223.14
Architecture: ia32
Windows 10

**Comment by MRayermannMSFT** [comment]
Can y'all give using system proxy setting a try? You can read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by hirez-masmith** [comment]
I opened a ticket with Azure support as this issue was also reflected within the web portal. 
Support got back to me with some troubleshooting steps, and magically, with me doing nothing, everything started working again.
Pretty sure I was hand-wave fixed, but not told what the issue was... Sorry I can't repro any longer.

**Comment by MRayermannMSFT** [comment]
Ok, no worries. Glad magic came through for you.
