### ISSUE TITLE
Fail to delete ADLS Gen2 blob snapshots

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5593]
**Storage Explorer Version**: 1.24.0-dev
**Build Number**: 20220407.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.3 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: From running test cases
**Regression From**: Previous release (1.23.0)

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Select one blob container which contains blobs.
3. Select one blob -> Create snapshot for it -> Switch to snapshot view -> Delete the snapshot.
4. Check whether succeeds to delete the blob snapshot.

## Expected Experience ##
Succeed to delete the blob snapshot.

## Actual Experience ##
Fail to delete the blob snapshot.
![image](https://user-images.githubusercontent.com/41351993/162146367-9ec09dc1-7247-42cf-b1cb-4796555b9168.png)
Error details:
`Required argument container for function deleteBlob is not defined`

![image](https://user-images.githubusercontent.com/41351993/162146470-56a2a58b-011a-4be4-8fa5-5c653f83df60.png)

## Additional Context ##
This issue has nothing to do with soft delete policy.

**Comment by JasonYeMSFT** [comment]
I noticed that deleting snapshots of a Gen2 blob doesn't trigger refreshing nor prompting for refresh. I need to take a look at what goes wrong there.

**Comment by v-xianya** [comment]
Verified this issue on the build main//20220414.17. Fixed.

BTW, there is a refresh prompt when deleting one snapshot. we are going to close it.
