### ISSUE TITLE
The first uploaded ADLS Gen2 blob is not selected

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5594]
**Storage Explorer Version**: 1.24.0-dev
**Build Number**: 20220407.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.3 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: From running test cases
**Regression From**: Previous release (1.23.0)

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Check whether the blob is selected.

## Expected Experience ##
The blob is selected.
![image](https://user-images.githubusercontent.com/41351993/162145196-48d18a8b-6587-4756-83fc-b9c9e7b60b3e.png)

## Actual Experience ##
The blob is not selected.
![image](https://user-images.githubusercontent.com/41351993/162145182-26a26a13-552a-4b39-b200-65c1f603e1c2.png)

## Additional Context ##
1. If we select the blob, then refresh the editor, the blob will not be selected.
2. If we select the blob, switch to snapshot view, the blob will not be selected.
![image](https://user-images.githubusercontent.com/41351993/162145737-ae61a9cd-69f4-4d5d-aa47-23adeee32778.png)
3. This issue also reproduces when pasting one blob to the ADLS Gen2 blob explorer.

**Comment by JasonYeMSFT** [comment]
If I remember correctly, the actual behavior is that we automatically select the first item in the data table after each reload. I think these kinds of manual adjustment of the selection is disturbing and should be avoided. Clearing the selection on refresh is by design right now.

**Comment by v-xianya** [comment]
@JasonYeMSFT Thank you for the response!

Will this new refresh mechanism be used for regular blob containers and file shares?

**Comment by JasonYeMSFT** [comment]
Not yet. We will migrate file explorer and table explorer so they will have this behavior too. Blob Explorer is at the bottom of the priority so it won't be touched anytime soon.
