### ISSUE TITLE
The tab is not closed when deleting one ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-sunnysun** [microsoft/AzureStorageExplorer#5596]
**Storage Explorer Version:** 1.24.0-dev
**Build Number:** 20220407.3
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.3 (Apple M1 Pro)
**Architecture:** ia32\x64
**How Found:** From running test case
**Regression From:** Previous release (1.23.0)

## Steps to Reproduce ##

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> The blob container 's tab auto opens -> Delete the blob container.
3. Check whether the opened tab is closed.

## Expected Experience ##
The tab is closed.

## Actual Experience ##
The tab is not closed.

## Additional Context ##
This issue also reproduces when detaching one ADLS Gen2 blob container.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220414.17. Fixed.
