### ISSUE TITLE
It would be better to adjust the size of the 'Clone and Rehydrate' dialog to remove the scrollbar

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5598]
**Storage Explorer Version**: 1.24.0-dev
**Build Number**: 20220407.3
**Branch**: main
**Platform/OS**: Windows 10
**Architecture** ia32
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one non-ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one blob and set its 'Target Access Tier' to 'Archive'.
3. Right click the Archive blob -> Click 'Clone and Rehydrate...'.
4. Type a non-exist blob container name -> There is an error message.
5. Check there is no scrollbar in the dialog.

## Expected Experience ##
It would be better to adjust the dialog size to remove the scrollbar.
![image](https://user-images.githubusercontent.com/41351993/162156001-03a41135-43bd-4163-8f85-5cb783a1e88a.png)

## Actual Experience ##
There is a scrollbar.

**Comment by JasonYeMSFT** [comment]
I expect most of the users to deal with one validation error at a time so this should be very rare. Besides, the scroll bar isn't a big issue. I am going to won't fix this issue.
