### ISSUE TITLE
Remove 'Back'/'Next' buttons on 'Connect to Cosmos DB' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#560]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180808.1
**Commit**: 93925d3c
**Regression From**: Not a regression 

#### Steps to Reproduce: ####
1. Apply subscriptions -> Right click 'Cosmos DB Accounts(Preview)' -> Select 'Connect to Cosmos DB...'.
2. Check the popped dialog.

#### Expected Experience: ####
There is no 'Back'/'Next' buttons.

#### Actual Experience: ####
An extra 'Back'/'Next' buttons display.
![warning](https://user-images.githubusercontent.com/34729022/43889149-e9c2def0-9bb2-11e8-9cbe-88296595ed4d.png)

**More info:**
1. Remove the default displayed warning message **'Connection string should not be empty'**.
2. **'Ok**' should display as '**OK**'.

**Comment by v-xianya** [comment]
This issue has been fixed on build master/20190722.3. So we close it.
