### ISSUE TITLE
An error info bar pops up when opening one storage account/service by its direct link

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5606]
**Storage Explorer Version**: 1.24.0-dev
**Build Number**: 20220408.6
**Branch**: main
**Platform/OS**: Windows 10/MacOS Monterey 12.3 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: From running test cases
**Regression From**: Previous release (1.23.0)

## Steps to Reproduce ##
1. Right click one storage account -> Click 'Copy Direct Link to Account'.
2. Past the direct link to the browser -> Open it.
3. Check whether succeeds to select the storage account.

## Expected Experience ##
Succeed to select the storage account.

## Actual Experience ##
There is an error info bar indicating '**The subscription for this resource is currently filtered out. You need to select the subscription in the account settings panel to see the resource**.'
![image](https://user-images.githubusercontent.com/41351993/162399812-07184b70-e3f4-4fb3-97ba-f3b832fe071b.png)

## Additional Context ##
This issue also reproduces for the four services.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220413.3. Fixed.
