### ISSUE TITLE
There is no '...' next to the action 'Set Default Access Tier' for one storage account

### ISSUE THREAD

**Issue by v-sunnysun** [microsoft/AzureStorageExplorer#5608]
**Storage Explorer Version:** 1.24.0-dev
**Build Number:** 20220410.3
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.3 (Apple M1 Pro)
**Architecture:** ia32\x64
**How Found:** From running test cases
**Regression From:** Previous release (1.23.0)

## Steps to Reproduce ##

1. Launch Storage Explorer.
2. Select and right click one storage account -> The context menu displays.
3. Check whether there is the '...' next to the action 'Set Default Access Tier'.

## Expected Experience ##
There is the '...' next to the action 'Set Default Access Tier'.
![image](https://user-images.githubusercontent.com/98519664/162697193-08749d3c-07ae-4152-a7b0-ad44d499eee5.png)

## Actual Experience ##
There is no '...' next to the action 'Set Default Access Tier'.
![image](https://user-images.githubusercontent.com/98519664/162696606-b6f52a63-ec93-4f2c-84ee-3feb9f58a44e.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220413.3. Fixed.
