### ISSUE TITLE
Include Filter permissions while generating SAS token at the container level.

### ISSUE THREAD

**Issue by SivaVilla** [microsoft/AzureStorageExplorer#5609]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem
Customer requirement: customer wants to give access to their clients on the storage container along with Blob tag index permission. Since filter permission is not available for the container SAS, customers were unable to filter the blob index values.
![image](https://user-images.githubusercontent.com/88868201/162708171-481f62dc-655a-4248-8578-63c7c4c56a17.png)

### Desired Solution

It would really helpful to have Filter permissions while generating SAS token for a container similar to the storage account level.

Below is the screen shot at the storage account level.
![image](https://user-images.githubusercontent.com/88868201/162708427-b855f402-1b8c-4e71-9338-0d73477b14f5.png)

Container level.
![image](https://user-images.githubusercontent.com/88868201/162708746-31bd414f-2c9f-433b-9863-e6dd072e9db8.png)

**Comment by JasonYeMSFT** [comment]
The permission is added as "Find" and will be shipped in our 1.25.0 release.
