### ISSUE TITLE
The renamed blob container is not highlighted after clicking Search icon again

### ISSUE THREAD

**Issue by v-dantch** [microsoft/AzureStorageExplorer#561]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180808.1
**Commit**: 93925d3c
**Regression From**: Not a regression 

#### Steps to Reproduce: ####
1. Expand one storage account -> Create at least 1 blob container.
2. Right click 'Blob Containers' node -> Select 'Search From Here' -> Type the blob container name into the Search Box -> Click the Search Icon.
3. After searching, rename the blob container containing the original name from the searched result -> Click Search Icon again.
4. Check whether the renamed blob container is highlighted or not.

#### Expected Experience: ####
The renamed blob container is highlighted. 

#### Actual Experience: ####
The renamed blob container is not highlighted.
![rename](https://user-images.githubusercontent.com/34729092/43889270-3e4ae94a-9bb3-11e8-8f72-33282f450ee2.png)

#### More Info: ####
1. The renamed blob container is highlighted after refreshing 'Blob Containers' node.
2. This issue also reproduces for file shares.
3. This issue doesn't reproduce for tables.

**Comment by JasonYeMSFT** [comment]
This is an edge case. Won't fix.

**Comment by v-dantch** [comment]
Got it. Thanks for your update.
