### ISSUE TITLE
No borders display in the Properties panel under the 'High Contrast - Black/White' theme

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5611]
**Storage Explorer Version:** 1.24.0-dev
**Build Number:** 20220410.3
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.3 (Apple M1 Pro)
**Architecture:** ia32\x64
**How Found:** From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##

1. Launch Storage Explorer -> Go to the 'View' menu -> Change the theme to 'High Contrast - Black/White'.
2. Select one storage account.
3. Check whether borders display in the Properties panel.

## Expected Experience ##
Borders display in the Properties panel.
The screenshot under the 'Dark' theme:
![image](https://user-images.githubusercontent.com/87792676/162716039-5cedd1e9-8419-4898-b89b-a03dfff15d03.png)

## Actual Experience ##
No borders display in the Properties panel.
![image](https://user-images.githubusercontent.com/87792676/162715895-f695b116-d987-4ca4-9cf1-afd118801df3.png)

**Comment by craxal** [comment]
When you say "border", are you referring to the background color? Either way, this is design. Borders would unnecessarily clutter the UI in high contrast. It would also make it harder to pick out which one is selected/has focus.
