### ISSUE TITLE
All snapshots have the same content as the first created snapshot even though the blob content has been changed before creating snapshots in one ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5612]
**Storage Explorer Version:** 1.24.0-dev
**Build Number:** 20220411.5
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.3 (Apple M1 Pro)
**Architecture:** ia32\x64
**How Found:** From running test cases
**Regression From:** Previous release (1.23.0)

## Steps to Reproduce ##

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload a blob to it.
3. Create snapshot -> Open the snapshot and verify its content.
4. Upload a same blob with different content -> Replace.
5. Create snapshot -> Open the snapshot and verify its content.
6. Check whether the snapshot content in Step5 is different from that in Step3.

## Expected Experience ##
The snapshot content in Step5 is different from that in Step3.

## Actual Experience ##
The snapshot content in Step5 is the same as that in Step3.

**Comment by JasonYeMSFT** [comment]
This might be related to https://github.com/microsoft/AzureStorageExplorer/issues/5599. The downloaded snapshot show the same content because we aren't actually downloading the snapshots. I'll verify this once that bug is fixed.

**Comment by JasonYeMSFT** [comment]
This should have been fixed together with #5595.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220414.17. Fixed.
