### ISSUE TITLE
Can't upload a non-empty folder named '! @ # $ % ^ & %2A %3F =,' to one blob container/file share

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5613]
**Storage Explorer Version**: 1.24.0-dev
**Build Number**: 20220411.5
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.3 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one non-empty folder named '**! @ # $ % ^ & %2A %3F =,** '.
3. Check whether succeeds to upload the folder.

## Expected Experience ##
Succeed to upload the folder.

## Actual Experience ##
1. The folder is not uploaded successfully.
2. There is a successful activity log indicating '0 items transferred'.
![image](https://user-images.githubusercontent.com/41351993/162906331-15c39481-4f45-44c3-aabd-2b8b44ead51b.png)

## Additional Context ##
1. This issue also reproduces for file shares.
2. On Mac and Linux, display the below activity log.
![image](https://user-images.githubusercontent.com/41351993/162907353-1bbfccea-6ac2-406d-9e98-547b328d668d.png)
Here is the azcopy log on Mac:
[6a95033c-8457-6449-4bbd-92400a7fc50b.log](https://github.com/microsoft/AzureStorageExplorer/files/8470616/6a95033c-8457-6449-4bbd-92400a7fc50b.log)

**Comment by MRayermannMSFT** [comment]
Issue is with the * character it seems. Also, I noticed that files adjacent to the troublesome folder get uploaded.

**Comment by MRayermannMSFT** [comment]
Passing along to Richard so he can get some AzCopy experience :)

**Comment by richardMSFT** [comment]
With 1.29.0 a temporary fix resolves this issue by escaping the `*` character. However, waiting on Azcopy for a more comprehensive fix.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20230516.3. Fixed. So, we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/f116e9ac-e85f-4187-80b5-1a95d215ba31)
