### ISSUE TITLE
v1.23.1 installer for Windows tries to install v1.23.0

### ISSUE THREAD

**Issue by horihiro** [microsoft/AzureStorageExplorer#5617]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.23.1

### Architecture

x64

### Platform

Windows

### OS Version

Windows 11

### Bug Description

An installer for v1.23.1 from https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.23.1 tries to install a wrong version (v1.23.0).  

### Steps to Reproduce

1. download the installer [`Windows_StorageExplorer.exe`](https://github.com/microsoft/AzureStorageExplorer/releases/download/v1.23.1/Windows_StorageExplorer.exe) from https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.23.1 . 
2. execute the installer

### Actual Experience

The installer tries to install v1.23.**0** as the following screenshot.

![image](https://user-images.githubusercontent.com/4566555/163131894-ba812ded-faa5-49d0-8958-5778eb4e5409.png)

**Comment by jinglouMSFT** [comment]
This should have been fixed now. Please let us know if you still have issues with the installer.  Thanks.

**Comment by horihiro** [comment]
@jinglouMSFT 
I tried to upgrade ASE by `winget`, but it was failed.

![image](https://user-images.githubusercontent.com/4566555/163281308-b4528ed3-62b0-4b59-ad7e-8f48a8466398.png)

According to the message in the above screenshot, `winget` downloaded the ASE installer from https://github.com/microsoft/AzureStorageExplorer/releases/download/v1.23.1/Windows_StorageExplorer.exe .
But a hash value of the installer doesn't match.

Do we need to update https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Microsoft/AzureStorageExplorer/1.23.1/Microsoft.AzureStorageExplorer.installer.yaml ?

**Comment by horihiro** [comment]
Looks like the SHA256 hash of the current installer is `16aad3aef473ef3226d8c1aebac77add570bb9fe958f96395341eab6dcfd62e9`.
![image](https://user-images.githubusercontent.com/4566555/163283926-5d61f9c9-cff4-4630-b924-8e53f13cdd72.png)

**Comment by jinglouMSFT** [comment]
You have to recalculate sha256 based on the new file uploaded today.  Sorry for the inconvenience.

**Comment by horihiro** [comment]
Sorry, the current issue is on a manifest file for `winget`, so I already filed a new issue on the repo.
