### ISSUE TITLE
There is a successful activity log when deleting one table under a SAS attached Storage account (with Read, List permissions)

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5618]
**Storage Explorer Version**: 1.24.0-dev
**Build Number**: 20220413.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.3 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: From running test cases
**Regression From**: Previous release (1.23.0)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table.
3. Attach the storage account via SAS URL with permissions 'Read, List'.
4. Expand the attached storage account -> Tables.
5. Select one table -> Delete it.
6. Check there is a failed activity log.

## Expected Experience ##
There is a failed activity log.
![image](https://user-images.githubusercontent.com/41351993/163131381-0515a889-83b3-49ee-970a-d5de4f984ac3.png)

Error:
`"name": "RestError",
  "message": "{\"odata.error\":{\"code\":\"AuthorizationPermissionMismatch\",\"message\":{\"lang\":\"en-US\",\"value\":\"This request is not authorized to perform this operation using this permission.\\nRequestId:bcb1db7d-7002-0024-2f0e-4f67f8000000\\nTime:2022-04-13T08:13:49.7130361Z\"}}}",`
## Actual Experience ##
1. There is a successful activity log.
![image](https://user-images.githubusercontent.com/41351993/163131563-73951e1d-dbd3-4e53-9e75-d3d4ec7f59a1.png)

2. The table disappears from the tree view.

## Additional Context ##
The table displays on the tree view after manually refreshing.

**Comment by craxal** [comment]
That's weird. The SDK isn't throwing an error even though the logs clearly show that the operation failed. Looks like the regression is in the SDK, as the expected error is thrown in slightly older versions of the SDK.

See https://github.com/Azure/azure-sdk-for-js/issues/21385.

**Comment by v-xianya** [comment]
Verified this issue on the build 20220418.1. Fixed.
