### ISSUE TITLE
Fail to reauthenticate one azure account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5619]
**Storage Explorer Version**: 1.24.0-dev
**Build Number**: 20220413.3
**Branch**: main
**Platform/OS**: Windows 10
**Architecture** ia32
**How Found**: From running test cases
**Regression From**: Previous release (1.23.0)

## Steps to Reproduce ##
1. Launch Storage Explorer -> Make sure there is expired azure account.
2. Go the ACCOUNT MANAGEMENT panel -> Click 'Reauthenticate now...'.
3. Check whether succeeds to reauthenciate.

## Expected Experience ##
Succeed to reauthenticate.

## Actual Experience ##
Fail to reauthenticate.
![image](https://user-images.githubusercontent.com/41351993/163135344-b16d15ce-219b-4059-a7f5-693c9555fc51.png)

## Additional Context ##
1. This issue has nothing to do with the sign-in method.
2. An error dialog pops up when launching Storage Explorer if there is an expired azure account.
![image](https://user-images.githubusercontent.com/41351993/163135851-37ad5d44-edae-4e01-87c6-1f3317d49c51.png)

**Comment by MRayermannMSFT** [comment]
Issue is in identity service. They are working on a fix.

**Comment by MRayermannMSFT** [comment]
Fix merged into rel branch. Both for re-autenticating and the error popping up.

**Comment by v-xianya** [comment]
Will verify this issue when there is a complete Windows build.

**Comment by v-xianya** [comment]
Verified on the build 20220424.1. Fixed.
