### ISSUE TITLE
No 'Last Modified' property displays for tables

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/AzureStorageExplorer#562]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180808.1
**Commit**: 93925d3c
**Regression From**: Not a regression 

#### Steps to Reproduce: ####
1. Expand one storage account -> Select one table.
2. Check the Properties window.

#### Expected Experience: ####
Display 'Last Modified' item.

#### Actual Experience: ####
No 'Last Modified' item displays.
![modified](https://user-images.githubusercontent.com/34729092/43889544-ff8afadc-9bb3-11e8-9a14-9247e7459174.png)

**Comment by MRayermannMSFT** [comment]
Closing as won't fix
