### ISSUE TITLE
It would be better to make the imported rows automatically display on the table explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5620]
**Storage Explorer Version**: 1.24.0-dev
**Build Number**: 20220413.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.3 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: Exploratory testing
**Regression From**: Not a regression 

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Import the below csv file.
[table.csv](https://github.com/microsoft/AzureStorageExplorer/files/8395418/table.csv)

4. Check whether the imported rows display on the table explorer automatically.

## Expected Experience ##
The imported rows display on the table explorer automatically.

## Actual Experience ##
The imported rows do not display on the table explorer automatically.

**Comment by craxal** [comment]
This is because we are only refreshing the explorer when the import completes successfully. Any failures transitions to a failure state, which doesn't send an update. We should add a refresh to the error state as well as the canceled state.

**Comment by v-xianya** [comment]
Verified this issue on the build 20220418.1. Fixed.
