### ISSUE TITLE
Fail to input English characters in the 'Open Service by Name' dialog

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5622]
**Storage Explorer Version:** 1.24.0-dev
**Build Number**: 20220413.3
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.3 (Apple M1 Pro)
**Architecture:** ia32\x64
**How Found:** From running test cases
**Regression From:** Previous release (1.23.0)

## Bug Description ##

1. Fail to input English characters to 'Table Name' field.
2. Succeed to input Chinese characters to 'Table Name' field, but fail to delete characters.

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Right click Tables node -> Click 'Open Table by Name...'.
3. The 'Open Table by Name' dialog pops up.
4. Check whether succeeds to input English characters to 'Table name' field.

## Expected Experience ##
Succeed to input English characters to 'Table name' field. 

## Actual Experience ##
Fail to input English characters to 'Table name' field.

## Additional Context ##
This issue also reproduces for other services.

**Comment by craxal** [comment]
Able to reproduce. Also noticed that F12 doesn't work, so I can't debug the dialog. Currently investigating cause.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220414.17. Fixed.
