### ISSUE TITLE
Release 1.23.1 downloads file version 1.23.0

### ISSUE THREAD

**Issue by ExpendaBubble** [microsoft/AzureStorageExplorer#5623]
https://github.com/microsoft/AzureStorageExplorer/releases/download/v1.23.1/Windows_StorageExplorer.exe is in fact version 1.23.0
![StorageAccountLol](https://user-images.githubusercontent.com/73191701/163202147-c7b63b74-ef0c-451f-8ea9-f2a5c9789d88.PNG)
.

**Comment by jinglouMSFT** [comment]
This should have been fixed now.  Thanks for letting us know and sorry for the inconvenience.
