### ISSUE TITLE
Unable to retrieve child resources.

### ISSUE THREAD

**Issue by bhargangreji** [microsoft/AzureStorageExplorer#5624]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.23.1

### Architecture

x64

### Storage Explorer Build Number

20220406.1

### Platform

Windows

### Bug Description

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://nareportingportal.file.core.windows.net/?comp=list failed, reason: unable to get local issuer certificate",
  "stack": "FetchError: request to https://nareportingportal.file.core.windows.net/?comp=list failed, reason: unable to get local issuer certificate\n    at ClientRequest.<anonymous> (C:\\Users\\<network id>\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:107389)\n    at ClientRequest.emit (node:events:394:28)\n    at TLSSocket.socketErrorListener (node:_http_client:447:9)\n    at TLSSocket.emit (node:events:394:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY",
  "code": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"
}

### Steps to Reproduce

1. Launch Storage Explorer
2. Click on "Subscription" > "Azure" Radio button > Click "Next" button > Login into Account
3. Click "Open Explorer"
4. Go to one of the storage account
5. Go to "File Share"
6. Error appears and no content is displayed.

### Actual Experience

![Unable to retrieve child resources](https://user-images.githubusercontent.com/103592865/163228649-206b2922-f2c0-4053-8404-f87e72663a5a.jpg)

### Expected Experience

Should open and display content of it

**Comment by MRayermannMSFT** [comment]
@bhargangreji can you give using system proxy setting a try? You can read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview
