### ISSUE TITLE
There is a failed activity log when deleting one ADLS Gen2 blob under one Azure AD attached folder

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5626]
**Storage Explorer Version**: 1.24.0-dev
**Build Number**: 20220414.17
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.2.1 (MacBook Air M1, 2020)
**Architecture** ia32\x64
**How Found**: From running test cases
**Regression From**: Previous release (1.23.1)

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account (with 'Storage Blob Data Owner' role and assigned to the specified user) -> Blob Containers. 
2. Select one blob container -> Upload one non-empty folder to it.
3. Azure AD attach the folder.
4. Go to the Azure AD attached folder -> Select one blob and delete it.
5. Check whether there is a successful activity log.

## Expected Experience ##
There is a successful activity log.

## Actual Experience ##
There is a failed activity log.
![image](https://user-images.githubusercontent.com/41351993/163347012-e0a642e2-f32a-49d8-9ac1-c6bd948de829.png)

![image](https://user-images.githubusercontent.com/41351993/163346976-40cd23c3-fd19-42b6-8fcc-a1fd7f2ce489.png)

## Additional Context ##
1.The deleted blob disappears after manually refreshing.
2. Here is the record:
![azureadnew](https://user-images.githubusercontent.com/41351993/163348206-30060e45-e6e0-4388-bdec-95e28a311037.gif)
3. Display the below activity log when deleting more than one blob.
![image](https://user-images.githubusercontent.com/41351993/163350689-fcb01b10-4fe1-4bab-a405-b6a431499b27.png)
![image](https://user-images.githubusercontent.com/41351993/163350759-c1486efd-5712-4afc-90b8-c361868752ca.png)

**Comment by JasonYeMSFT** [comment]
I was using the wrong endpoint [facepalm], which is the cause of the regression. However, AzCopy doesn't seem to recognize 202 (accepted) responses and attempts to retry a delete operation that has been done, which might also be a bug.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220415.4. Fixed.
