### ISSUE TITLE
The cloned table is opened under the SAS attached storage account when cloning one table under the subscription storage account

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5628]
**Storage Explorer Version:** 1.24.0-dev
**Build Number:** 20220414.17
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.2.1(MacBook Air M1, 2020)
**Architecture:** ia32\x64
**How Found:** Ad-hoc testing
**Regression From:** Previous release (1.22.1)

## Steps to Reproduce ##

1. Expand one storage account -> Tables -> Create a table.
2. SAS attach the storage account.
3. Go to the original storage account -> Tables.
4. Select and right click one table -> Click 'Clone...'.
5. Input a valid name -> Click 'Clone'.
6. Check whether the table is opened under the subscription storage account.

## Expected Experience ##
The table is opened under the subscription storage account.

## Actual Experience ##
The table is opened under the SAS attached storage account.

## Additional Context ##

1. This issue doesn't reproduce for blob containers/file shares.
2. This issue doesn't reproduce for Name & Key attached storage accounts.
3. Here is the record:
![table](https://user-images.githubusercontent.com/87792676/163347856-e36b4843-e202-42fd-943f-9ff3589cd361.gif)

**Comment by craxal** [comment]
The logic for getting the parent node of the table node we're cloning wasn't strict enough. This is easily solved by using the "get parent node" API we already have.

**Comment by v-xianya** [comment]
Verified this issue on the build 20220418.1. Fixed.
