### ISSUE TITLE
Context menus always use dark theme, regardless of overall theme setting

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/AzureStorageExplorer#5630]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.23.0

### Architecture

x64

### Storage Explorer Build Number

20220223.14

### Platform

Windows

### OS Version

Windows 11

### Bug Description

Context menus seem to be always using the dark theme, regardless of overall theme setting

### Steps to Reproduce

1. Choose "Light", "High Contrast - White", or "High Contrast - Black" theme
2. Open any context menu, e.g. by right clicking a resource

### Actual Experience

Example with "High Contrast - White" theme active:
![image](https://user-images.githubusercontent.com/36966225/163430217-3f70fadb-55ba-41e6-9eb0-1ffe804f091c.png)

### Expected Experience

Expected theme to be followed

**Comment by craxal** [comment]
@bwateratmsft The context menu theme comes from the system. Was the system using a dark theme?
