### ISSUE TITLE
Consider replacing `archiver` with a different dependency

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#5632]
We use `archiver` to create zip and tar.gz archives. It has not received any updates in 8 months though: https://github.com/archiverjs/node-archiver/commits/master 

We should consider finding a replacement if their security issues continue being ignored.

If we do, we should strive to use a dependency that seems maintained and brings in a small number of dependencies.

**Comment by craxal** [comment]
Each platform comes with a compression CLI tool. If we considered using those, we'd be able to eliminate the need for a dependency entirely.

**Comment by MRayermannMSFT** [comment]
`archiver` ultimately responded to the security issue in just 5 days. I think that's pretty good.
https://github.com/archiverjs/node-archiver/issues/583

Moving this to future...

**Comment by MRayermannMSFT** [comment]
Archiver seems to be releasing regular updates with fixes for dependency issues. Closing this.
