### ISSUE TITLE
When SAS Token expires, please display a message saying 'Your SAS token expired, please generate a new one'

### ISSUE THREAD

**Issue by FaronFaulk** [microsoft/AzureStorageExplorer#5634]
https://github.com/microsoft/AzureStorageExplorer/issues/5634#tasklist-block-4da9bcbc-6209-404a-9e7b-1b586111a770

...instead of this:

"Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:f6884515-501e-009f-41fe-505240000000 Time:2022-04-15T19:23:52.0482248Z"

**Comment by MRayermannMSFT** [comment]
@FaronFaulk it can be difficult trying to decide the various places where we should do deep investigations into error messages during runtime. Can you share with us what you were doing/where you saw this message appear?

**Comment by MRayermannMSFT** [comment]
Hi @FaronFaulk, if you'd like to use an image in your reply, you'll need to come to GitHub and reply there. Thanks.

**Comment by FaronFaulk** [comment]
![ASE-baderrormessage](https://user-images.githubusercontent.com/44375156/163849944-a8e33618-49ec-4210-a7bf-e0b81ea492a0.png)

**Comment by MRayermannMSFT** [comment]
Ok so during an explorer refresh, thank you!

**Comment by MRayermannMSFT** [comment]
We need to:
- Have team discussion regarding error reporting in explorers (deficiencies with using the info bar)
- Talk about checking SAS expiration in explorers
- Investigate experimenting with more obvious displays of SAS expiration in the tree (e.g. changing node icons to make it more obvious there is an issue)

**Comment by jcookems** [comment]
Is there a way to change the SAS token for an existing connection? It is nice to preserve open tabs from session to session. 

Our teams allows for getting 7-day SAS tokens for a container, and not being able to change the token for and existing connection means that those saved tabs get lost. Ideally, we could just update the SAS token for an existing connection, and everything else would continue to work:
![image](https://user-images.githubusercontent.com/1087451/191166705-984a106e-9499-43de-baa6-163e606f2505.png)

**Comment by craxal** [comment]
@jcookems That's a good suggestion. We can explore the possibility of renewing SAS-based connections with a new SAS token. I would consider this a separate issue, so I recommend opening a separate feature request.

**Comment by jcookems** [comment]
Thanks @craxal, I opened https://github.com/microsoft/AzureStorageExplorer/issues/6107 to track updating SAS token. I'd expect that the solution to this issue would be some sort of popup or link to update the SAS token in-place, as described in my issue.

**Comment by craxal** [comment]
@FaronFaulk @jcookems We've settled on the idea of displaying a warning message in the explorer when the SAS is due to expire within 1 hour and when the SAS actually expires. Is this sufficient for your needs? Do you still want to see the authentication error message when the SAS is expired?
