### ISSUE TITLE
The temporary tab doesn't become permanent if moving its split tab to the temporary tab view for one ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5640]
**Storage Explorer Version**: 1.24.0-dev
**Build Number**: 20220421.6
**Branch**: rel/1.24.0
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.3 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: From running test cases
**Regression From**: Previous release (1.23.1)

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Select one blob container -> Click it to open a temporary tab.
3. Split the tab -> Move the split tab to the temporary tab view.
4. Check whether the temporary tab becomes a permanent tab.

## Expected Experience ##
The temporary tab becomes a permanent tab.

## Actual Experience ##
The temporary tab doesn't become a permanent tab.

## Additional Context ##
This issue only reproduces for ADLS Gen2 blob containers.

**Comment by JasonYeMSFT** [comment]
Actually, I noticed that dragging a tab to the spacer area to clone the tab is broken. I will address that as well when fixing this issue.

**Comment by v-xianya** [comment]
Verified this issue on the build 20220424.1. Fixed.
