### ISSUE TITLE
There is an error message 'Folder name must not end with .' when creating a folder using a single character as the name in one file share

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5643]
**Storage Explorer Version:** 1.24.0-dev
**Build Number:** 20220421.6
**Branch:** rel/1.24.0
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.3 (Apple M1 Pro)
**Architecture:** ia32\x64
**How Found:** From running test cases
**Regression From:** Previous release (1.23.1)

## Steps to Reproduce ##

1. Expand one storage account -> File Shares.
2. Create a file share -> Click 'New Folder'.
3. Delete the default name -> Type 'X' in the 'New folder name' field.
4. Check whether there is no error message.

## Expected Experience ##
There is no error message.
![image](https://user-images.githubusercontent.com/87792676/164428249-1535b9ea-7761-4661-a004-1e0f65b72875.png)

## Actual Experience ##
There is an error message 'Folder name must not end with .'.
![image](https://user-images.githubusercontent.com/87792676/164428164-660028d6-0179-41eb-9571-b4e6eb2da516.png)

**Comment by v-xianya** [comment]
Verified this issue on the build 20220422.13. Fixed.
