### ISSUE TITLE
The descriptions are incorrect in the 'Undelete' dialog against one folder

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5644]
**Storage Explorer Version**: 1.24.0-dev
**Build Number**: 20220421.6
**Branch**: rel/1.24.0
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.3 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: Ad-hoc testing
**Regression From**: Previous release (1.20.1)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Create a folder -> Upload one blob to the folder.
3. Right click the folder -> Click 'Undelete -> Undelete Selected'.
6. Observe the descriptions in the 'Undelete' dialog -> Check whether the descriptions are correct.

## Expected Experience ##
The descriptions are correct.
![image](https://user-images.githubusercontent.com/41351993/164440729-9b366249-b450-4efe-b3a6-c02e816d806b.png)

## Actual Experience ##
The descriptions are incorrect.
![image](https://user-images.githubusercontent.com/41351993/164439553-a693b156-d262-46f2-a900-09b2826599fa.png)

**Comment by JasonYeMSFT** [comment]
The change of the string is intentional. We decided to make the strings more concise even though they may not be as explicit as the previous ones. The previous strings are too verbose to be effective.

**Comment by v-xianya** [comment]
@JasonYeMSFT Thank you for the response!
The current description doesn't make sense to me.
Now I select one folder and execute 'Undelete Selected'. The folder contains one active blob. also the active blob has a soft-deleted blob snapshot.
Refer to the description, 'For blobs in Selected Folders, they and their deleted versions or snapshots will be undeleted'.
In this case, the soft-deleted snapshot is not undeleted. Could you help to take a look?

https://user-images.githubusercontent.com/41351993/164587860-56c0f43e-6986-4532-85c6-c22b1f7fe678.mov

**Comment by JasonYeMSFT** [comment]
That's true, I should make it say "For deleted blobs in selected folders, ......".

**Comment by v-xianya** [comment]
Verified this issue on the build main 20220505.5. The descriptions have been updated. So, close this issue.
![image](https://user-images.githubusercontent.com/41351993/166871386-33f0bd12-a12c-4f85-8e4c-7942cd5b0f79.png)
