### ISSUE TITLE
It would be better to add a poured triangle icon next to the 'Export' action in one table's toolbar

### ISSUE THREAD

**Issue by v-sunnysun** [microsoft/AzureStorageExplorer#5645]
**Storage Explorer Version:** 1.24.0-dev
**Build Number:** 20220421.6
**Branch:** rel/1.24.0
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.3 (Apple M1 Pro)
**Architecture:** ia32\x64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create a new table -> Observe the toolbar.
3. Check whether there is a poured triangle icon next to the ‘Export’ action. 

## Expected Experience ##
There is a poured triangle icon next to the ‘Export’ action. (Refer to 'Select All')
![image](https://user-images.githubusercontent.com/98519664/164436956-95f2ddf2-657f-485b-8ad2-9e6877b6c618.png)

## Actual Experience ##
There is no poured triangle icon next to the ‘Export’ action.

**Comment by craxal** [comment]
We are already aware of this. I consciously chose not to add the triangle, because that would involve getting a new icon, and I am looking into improving the toolbar component we have to include the triangle automatically.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220516.1. Fixed.
![image](https://user-images.githubusercontent.com/87792676/168508000-15e33442-24c4-4f55-81fc-47710a709966.png)
