### ISSUE TITLE
Metadata Keys are always shown in lowercase

### ISSUE THREAD

**Issue by DadvDadv** [microsoft/AzureStorageExplorer#5646]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.23.1

### Architecture

x64

### Storage Explorer Build Number

20220406.1

### Platform

Windows

### OS Version

Windows 10

### Bug Description

When metadata are displayed, keys are lowercase even though they are stored in different cases.

### Steps to Reproduce

1. Launch Explorer
2. Expand a container
3. Rigth click on a blob
4. Select Properties
5. Add a metadata  ("Metadata1" - "Value")
6. Save
7. Rigth click on the same blob
8. "Metadata1" is  become "metadata1"

### Actual Experience

The metadata keys are lowers on save

### Expected Experience

The metadata keys should stay the same after save

### Additional Context

none

**Comment by MRayermannMSFT** [comment]
@DadvDadv thanks for self closing. You actually found issues I wasn't aware of! I'll go and get those cleaned up.

**Comment by DadvDadv** [comment]
You're welcome,

It seems that we have to wait for version 1.24 to have a fix to this problem ([8117](https://github.com/Azure/azure-sdk-for-js/issues/8117#issuecomment-1105378568))
