### ISSUE TITLE
Support/invalidate SAS query strings starting with ? when attaching with connection string

### ISSUE THREAD

**Issue by shouryab24** [microsoft/AzureStorageExplorer#5648]
Consistently getting the following error while trying to download any file. The container is otherwise browsable (no errors reported when attaching storage account using the SAS connection string)

{
  "message": "\"failed to perform copy command due to error: cannot start job due to error: cannot list files due to reason -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.13.1-0.20210823171415-e7932f52ad61/azblob/zc_storage_error.go:42\\n===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====\\nDescription=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\\nRequestId:7ce803f2-401e-0077-78b5-55cbd6000000\\nTime:2022-04-21T19:28:37.6167596Z, Details: \\n   AuthenticationErrorDetail: sr is mandatory. Cannot be empty\\n   Code: AuthenticationFailed\\n   GET https://wepod01ssemdspg4wq1d.blob.core.windows.net/0006d490-56b7-4249-845c-9678381eeb40?%3Fsv=2018-03-28&comp=list&delimiter=%2F&include=metadata&prefix=aftercleanup_2e5c32c6-b38e-460c-9083-5eb30228918b_06072019162148.zip%2F&restype=container&se=2022-04-28t17%3A16%3A46z&sig=-REDACTED-&sp=rl&spr=https&srt=sco&ss=b&st=2022-04-21t17%3A06%3A46z&timeout=901\\n   User-Agent: [Microsoft Azure Storage Explorer, 1.23.1, win32, azcopy-node, 2.0.0, win32,  AzCopy/10.13.0 Azure-Storage/0.14 (go1.16; Windows_NT)]\\n   X-Ms-Client-Request-Id: [30124c88-00ff-4832-7d6c-1af7b8655b80]\\n   X-Ms-Version: [2019-12-12]\\n   --------------------------------------------------------------------------------\\n   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\\n   Content-Length: [407]\\n   Content-Type: [application/xml]\\n   Date: [Thu, 21 Apr 2022 19:28:37 GMT]\\n   Server: [Microsoft-HTTPAPI/2.0]\\n   X-Ms-Error-Code: [AuthenticationFailed]\\n   X-Ms-Request-Id: [7ce803f2-401e-0077-78b5-55cbd6000000]\\n\\n\\n.\\n\""
}

**Comment by shouryab24** [comment]
The Exprorer UI seems to be generating the azcopy cmd incorrectly. There are some extra chars ("%3F") before the sv is passed. 
By manually removing those extra chars, azcopy cmd is working successfully from a console.

![image](https://user-images.githubusercontent.com/100740876/164552172-059b5c73-6090-4757-98ad-9b749b79d6c6.png)

**Comment by MRayermannMSFT** [comment]
@shouryab24 to confirm, you attached your storage account using SAS connection string? If so, could you share the connection string, but make sure to redact the sig parameter?

**Comment by JasonYeMSFT** [comment]
@shouryab24 If you have a chance, please verify if the SAS property in your connection string has a preceding question mark. For example,

SharedAccessSignature=?sv=2020-10-02&ss=btqf&srt=sco&st=2022-04-25T19%3A34%3A19Z&se=2022-04-30T19%3A34%3A00Z&sp=rwdxl&sig=

The correct value for that property should have no preceding question mark.
SharedAccessSignature=sv=2020-10-02&ss=btqf&srt=sco&st=2022-04-25T19%3A34%3A19Z&se=2022-04-30T19%3A34%3A00Z&sp=rwdxl&sig=

**Comment by shouryab24** [comment]
Yes, the SharedAccessSignature i used had a preceding question mark. But the same key (in connection string) was used to attach the storage account in the UI dialog screen and it did not complain about it there. 

![image](https://user-images.githubusercontent.com/100740876/165396490-5f0d5714-bbfa-4919-a710-2bc52126ad6c.png)

**Comment by JasonYeMSFT** [comment]
@shouryab24 Do you mean that you have both your account name and account key in the connection string? If that's the case we should be using the key and this error shouldn't occur. 

Or do you mean that you pasted the SAS connection string into the dialog and it doesn't give any validation error? That's something we missed in our connection string validation. If that's the case, I am going to edit the title of the issue and convert it to a work item for us to polish the validation logic.

**Comment by shouryab24** [comment]
I put the following in the "Connection String" dialog box (with BlobEndpoint and SAS key). It successfully connected to the storage account and i was able to browse the contents but trying to download any files had the exception.

BlobEndpoint=https://wepod01ssemdspg4wq1d.blob.core.windows.net/;SharedAccessSignature=?sv=2018-03-28&sig=<...>&spr=https&st=2022-04-21T17%3A06%3A46Z&se=2022-04-28T17%3A16%3A46Z&srt=sco&ss=b&sp=rl

**Comment by JasonYeMSFT** [comment]
Technically the SAS in the connection string shouldn't have the ? symbol. I merged a change so that our connect dialog can auto-correct such kind of error in the connection strings.
