### ISSUE TITLE
Display red borders after clearing the 'Start time' which is greater than 'Expiry time' on SAS dialog

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#565]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180808.1
**Commit**: 93925d3c
**Regression From**: Not a regression 

#### Steps to Reproduce: ####
1. Choose one storage account.
2. Right click one blob container -> Select 'Get Shared Access Signature...'.
3. Set the 'Start time' is **greater than** the default 'Expiry time' -> Clear the set 'Start time'.

#### Expected Experience: ####
No red border displays.

#### Actual Experience: ####
Display red borders with the message 'The expiry time must be greater than the start time'.
![red_border](https://user-images.githubusercontent.com/34729022/43888832-22d8469a-9bb2-11e8-99c6-e86a2ba7d749.png)

**Comment by MRayermannMSFT** [comment]
Closing as won't fix.
