### ISSUE TITLE
FetchError: ETimeout

### ISSUE THREAD

**Issue by kevinlanguedoc** [microsoft/AzureStorageExplorer#5652]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.23.1

### Architecture

x64

### Platform

Windows

### Bug Description

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://neapnpepgen2.blob.core.windows.net/?comp=list&include=metadata failed, reason: connect ETIMEDOUT 20.150.35.100:443",
  "stack": "FetchError: request to https://neapnpepgen2.blob.core.windows.net/?comp=list&include=metadata failed, reason: connect ETIMEDOUT 20.150.35.100:443\n    at ClientRequest.<anonymous> (C:\\Users\\Kevin.Languedoc\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1491:11)\n    at ClientRequest.emit (node:events:394:28)\n    at TLSSocket.socketErrorListener (node:_http_client:447:9)\n    at TLSSocket.emit (node:events:394:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "ETIMEDOUT",
  "code": "ETIMEDOUT"
}

### Steps to Reproduce

Launch App
Expand account
trying to expand blob containers ---> error

### Actual Experience

See bug description

**Comment by MRayermannMSFT** [comment]
@kevinlanguedoc can you give using system proxy setting a try? You can read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem we recommend opening an Azure support ticket from the portal. You can also open a new issue here.
