### ISSUE TITLE
Update 'set' to 'setting' in the descriptions of the part 'Respecting casing of metadata keys for blobs' on Release Notes page

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5653]
**Storage Explorer Version**: 1.24.0
**Build Number**: 20220424.1
**Branch**: rel/1.24.0
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.3 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Click 'Help -> View Release Notes'.
2. Go to the part 'Respecting casing of metadata keys for blobs'.
3. Observe there is no grammar problem in the description 'When set use...'.

## Expected Experience ##
Update 'When set use...' to 'When setting use...'.

## Actual Experience ##
There is a grammar problem in the description 'When set use...'.
![image](https://user-images.githubusercontent.com/41351993/164968619-c88b717f-a9bc-4de9-b70a-2b5b647da6d3.png)

**Comment by MRayermannMSFT** [comment]
Will change to "configured"

**Comment by v-xianya** [comment]
@MRayermannMSFT the string is not changed in the release note of the latest rel build.

**Comment by MRayermannMSFT** [comment]
It is now!

**Comment by v-xianya** [comment]
Fixed on the new build 20220429.4
