### ISSUE TITLE
The bypass setting doesn't take effect for tables

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5654]
**Storage Explorer Version:** 1.24.0
**Build Number:** 20220424.1
**Branch:** rel/1.24.0
**Platform/OS:** Windows 10
**Architecture:** ia32
**How Found:** From running test cases
**Regression From:** Previous release (1.23.1)

## Steps to Reproduce ##

1. Launch Storage Explorer.
2. Click 'Edit -> Configure Proxy' -> Select 'Use app proxy settings' -> Set 'http_proxy=http://localhost:8888'.
3. Input [".table.core.windows.net"] to the Bypass field -> Click 'OK' -> Open Fiddler.
4. Expand one storage account -> Tables -> Create a table.
5. Check whether there is no captured traffic in Fiddler.

## Expected Experience ##
There is no captured traffic in Fiddler.

## Actual Experience ##
There is some traffic in Fiddler.
![image](https://user-images.githubusercontent.com/87792676/164972405-d38704e2-9675-4873-8709-e34a95f8ad72.png)

## Additional Context ##
This issue also reproduces when using environment proxy.

**Comment by MRayermannMSFT** [comment]
@v-kellyluo. I have a merged a fix for this into the rel branch. Can you also do similar testing against storage accounts under subscriptions, and non-azcopy related disk features?

**Comment by v-kellyluo** [comment]
Verified this issue on the build rel/20220426.1. Fixed.
BTW, we did some similar testing against storage accounts and disk features, no new issue was found.
