### ISSUE TITLE
Unable to Retrieve Child Resources

### ISSUE THREAD

**Issue by Sidharth-123** [microsoft/AzureStorageExplorer#5655]
Unable to retrieve child resources.

Details:
{
  "name": "Error",
  "message": "File Shares do not support Azure AD access",
  "stack": "Error: File Shares do not support Azure AD access\n    at FileServiceClient._createPipeline (D:\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\index.js:2:34472)\n    at FileServiceClient.createClient (D:\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\index.js:2:457882)\n    at FileServiceClient.runOperation (D:\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\index.js:2:457171)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async Function.produceFileShareNodes (D:\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\index.js:2:57393)\n    at async Object.Azure.Storage.FileShareProducer.produceFileShareNodes (D:\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\index.js:2:76556)\n    at async Provider.executeOperation (D:\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\providers\\Provider.js:27:16)\n    at async NodeProcessHostProxy._handleExecuteRequest (D:\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:217:31)\n    at async NodeProcessHostProxy._handleMessage (D:\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:171:24)\n    at async D:\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:65:17"
}

**Comment by MRayermannMSFT** [comment]
@Sidharth-123  this error is a red herring. Can you:

1. Repro the problem
1. Click on Help -> Open Logs Directly
2. Go into the newest folder
3. Share the log file with the words "file-extension" in it to this issue.

Also, what version of Storage Explorer are you using? Thanks!

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem we recommend opening an Azure support ticket from the portal. You can also open a new issue here.
