### ISSUE TITLE
Graph: Allow to select the property shown instead of the ID (ala Azure Portal)

### ISSUE THREAD

**Issue by VincentK76** [microsoft/AzureStorageExplorer#566]
**Storage Explorer Version**: 1.3.1
**Platform/OS Version**: Windows 10 - 1803
**Architecture**: ia32
**Regression From**: none

#### Steps to Reproduce: ####
1) Open an CosmosDB using the Gremlin API.  
2) Execute a query ( g.V() )  
3) Notice that the results are listed with the vertex/edge ID
4) Notice that you are unable to select any other field for the results to display in

#### Expected Experience: ####
I expected this experience to match the experience in the Azure Portal where I can select the property used with the 'Style' => 'Show vertex (node) as' option

#### Actual Experience: ####
I see only the results with the ID. Since this is an GUID when you auto generate ID it's hard to walk through the results to verify that you have the correct selection

**Comment by MRayermannMSFT** [comment]
Hi @djlan , please traige. :)

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
