### ISSUE TITLE
Use MouseEvent.detail to detect double click on LHS

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#5663]
In some of our click event listener, we manually detect and differentiate single click and double clicks to execute different actions. By taking advantage of the MoustEvent.detail property, which gives the click count (double clicks will have even click counts), we no longer need to maintain state variables ourselves for it.

**Comment by MRayermannMSFT** [comment]
Taking care of this in the new tree view.
