### ISSUE TITLE
"$blobchangefeed" container isn't showing in ASE

### ISSUE THREAD

**Issue by GaneshMSFT** [microsoft/AzureStorageExplorer#5665]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.23.1

### Architecture

x64

### Platform

Windows

### Bug Description

Storage explorer isn't listing **$blobchangefeed** container when I expand Blob containers under my storage account.

### Steps to Reproduce

1. Enable blob change feed on Azure storage account
2. Launch storage explorer
3. Expand the storage blob containers
4. $blobchangefeed container isn't being listed

### Actual Experience

**$blobchangefeed** container should be shown under containers.

**Comment by JasonYeMSFT** [comment]
We currently don't support listing $blobchangefeed container. We will consider supporting it.

**Comment by MRayermannMSFT** [comment]
The container will show up starting in version 1.25
