### ISSUE TITLE
It doesn't return to the previous page when clicking the left arrow on the sign-in (authentication) page

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5667]
**Storage Explorer Version**: 1.24.0
**Build Number**: 20220427.2
**Branch**: rel/1.24.0
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.3 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Select 'Integrated Sign-in'.
2. Open the connect dialog -> Select 'Subscriptions -> Azure' -> Click 'Next'.
3. Enter one azure account -> Click 'Next' -> Click 'Password' -> Enter the password -> Click 'Sign in'.
4. Click the left arrow -> Check whether it returns to the previous page.

## Expected Experience ##
It returns to the previous page.

## Actual Experience ##
It doesn't return to the previous page.

![image](https://user-images.githubusercontent.com/41351993/165463055-91d351b7-4e4b-4d72-bfbf-2cf281b0adaf.png)

**Comment by MRayermannMSFT** [comment]
@v-xianya what does the button do for you? For me it goes back to the page where I can enter in an email address

**Comment by v-xianya** [comment]
@MRayermannMSFT Still stay in the current page when clicking the button.

**Comment by MRayermannMSFT** [comment]
I still am unable to repro this. Going to close as a mix of no repro/won't fix. Integrated sign in is no longer the default and it isn't recommended. If someone complains about this we can dig into it more.
