### ISSUE TITLE
External security challenge not satisfied. User will be redirected to another page or authentication provider to satisfy additional authentication challenges.

### ISSUE THREAD

**Issue by amusant** [microsoft/AzureStorageExplorer#5673]
I get the following error message from "storage explorer"  regarding "external security challenge" which then opens briefly the 
web browser (firefox) and returns to "storage explorer" . It does not ask for any security challenge. 

This happens when  I try to access storage blob. Everything else goes without errors.

**Comment by amusant** [comment]
exact error message:
{
  "message": "\"{\\n  \\\"message\\\": \\\"\\\\\\\"AADSTS50158: External security challenge not satisfied. User will be redirected to another page or authentication provider to satisfy additional authentication challenges.\\\\\\\\r\\\\\\\\nTrace ID: e4bc23d9-b60f-4e68-bd24-4787a7669000\\\\\\\\r\\\\\\\\nCorrelation ID: 6973b634-b1ec-400b-9a48-0eb54a110350\\\\\\\\r\\\\\\\\nTimestamp: 2022-04-28 09:48:43Z\\\\\\\"\\\"\\n}\""
}

**Comment by MRayermannMSFT** [comment]
amusant can you try going to Help > Reset, and then only have authentication checked, click reset, restart the app, and then try again?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue we recommend opening a support ticket via the Azure Portal. Alternatively you can open a new issue here.
