### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by saelder** [microsoft/AzureStorageExplorer#5676]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.23.1

### Regression From

1.20.0?

### Architecture

x64

### Storage Explorer Build Number

20220406.1

### Platform

Windows

### Bug Description

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://smdocumentstorage.file.core.windows.net/?comp=list failed, reason: connect ECONNREFUSED 20.60.178.168:443",
  "stack": "FetchError: request to https://smdocumentstorage.file.core.windows.net/?comp=list failed, reason: connect ECONNREFUSED 20.60.178.168:443\n    at ClientRequest.<anonymous> (C:\\Users\\Power\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:107389)\n    at ClientRequest.emit (node:events:394:28)\n    at TLSSocket.socketErrorListener (node:_http_client:447:9)\n    at TLSSocket.emit (node:events:394:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "ECONNREFUSED",
  "code": "ECONNREFUSED"
}

### Steps to Reproduce

1. Launch Storage Explorer
2. Attempt to open child node under File Shares

### Actual Experience

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://smdocumentstorage.file.core.windows.net/?comp=list failed, reason: connect ECONNREFUSED 20.60.178.168:443",
  "stack": "FetchError: request to https://smdocumentstorage.file.core.windows.net/?comp=list failed, reason: connect ECONNREFUSED 20.60.178.168:443\n    at ClientRequest.<anonymous> (C:\\Users\\Power\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:107389)\n    at ClientRequest.emit (node:events:394:28)\n    at TLSSocket.socketErrorListener (node:_http_client:447:9)\n    at TLSSocket.emit (node:events:394:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "ECONNREFUSED",
  "code": "ECONNREFUSED"
}

### Expected Experience

Child resources should expand

### Additional Context

N/A

**Comment by MRayermannMSFT** [comment]
@seadler can you give using system proxy setting a try? You can read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue, we recommend you either open a ticket via the Azure Portal or you can open a new issue here.
