### ISSUE TITLE
Empty subscription

### ISSUE THREAD

**Issue by michal890203** [Microsoft/AzureStorageExplorer#568]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows 10 Enterprise
**Architecture**: x64
**Regression From**: I not sure, but previous version I used was 1.2.0

#### Steps to Reproduce: ####
Please go to "Actual Experience"

#### Expected Experience: ####
I expect when I adding account in Azure Storage or VS2017 it's not involved to account in second one...

#### Actual Experience: ####
I see only 1 subscription (but I should see about 8 subscriptions) and it's empty (no expandable).

After I re-add (remove and add) account to MS Azure Storage it's everything OK in MS Azure storage, but my account in VS 2017 is gone. After I add account to VS 2017 I getting issue in MS Azure Account

---

After update to version 1.4.0 I can see any items in my subscription

![aaaaaa](https://user-images.githubusercontent.com/7962512/43941800-d74f893a-9c75-11e8-8906-d9fafc36ae91.PNG)

Subscprition is empty. This issue is can be solved remove account and re-add it. But then my account to TFS in VisualStudio disappering... after re-add account in Visual studio I have empty subscription in Azure Stroge explorer.

**Comment by MRayermannMSFT** [comment]
@michal890203 , do you happen to have 2 accounts with the same email?

**Comment by craxal** [comment]
@michal890203, can you please fill out the following template? It will really help us get to the bottom of your issue more quickly.

```
**Storage Explorer Version**: <!-- Enter the Storage Explorer version in which you encountered your issue. -->
**Platform/OS Version**: <!-- Enter the OS and version (see About dialog). -->
**Architecture**: <!-- Enter the architecture of the app (see About dialog). -->
**Regression From**: <!-- Was this working on a previous version? If so, which one? -->

#### Steps to Reproduce: ####
1. <!-- Describe the steps necessary to reproduce your issue. -->
2. <!-- Be as detailed as you can. -->

#### Expected Experience: ####
<!-- Describe the outcome you expect when performing the above steps. -->

#### Actual Experience: ####
<!-- Describe the outcome that actually occurs when performing the above steps. -->
```

**Comment by michal890203** [comment]
@MRayermannMSFT, yes. I have two accounts (personal and work) on this same adres

@craxal
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows 10 Enterprise
**Architecture**: x64
**Regression From**: I not sure, but previous version I used was 1.2.0

#### Steps to Reproduce: ####
Please go to "Actual Experience"

#### Expected Experience: ####
I expect when I adding accaunt in Azure Storage or VS2017 it's not involwed to account in second one...

#### Actual Experience: ####
I see only 1 subscription (but I should see about 8 subscriptions) and it's empty (no expandable).

After I re-add (remove and add) account to MS Azure Storage it's everything ok in MS Azure storage, but my account in VS 2017 is gone. After I add account to VS 2017 I geting issue in MS Azure Account

**Comment by MRayermannMSFT** [comment]
Can you try the patch I gave in this comment and let me know if it fixes your issue? https://github.com/Microsoft/AzureStorageExplorer/issues/580#issuecomment-412934272

Thanks.

**Comment by michal890203** [comment]
@MRayermannMSFT that patch works. I'm guessing that it comes from the older version?

Thanks

**Comment by MRayermannMSFT** [comment]
I'm not sure what you mean by comes from the older version. But, we will be shipping an update (hopefully this week?) that contains this fix. Feel free to use the patch until then. I'm going to close this issue now.
