### ISSUE TITLE
There was a problem interacting with your OS credential store during an AzCopy transfer. 

### ISSUE THREAD

**Issue by v-susab** [microsoft/AzureStorageExplorer#5680]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.23.1

### Regression From

?

### Architecture

i86

### Storage Explorer Build Number

20220406.0

### Platform

Windows

### OS Version

Windows 11 Enterprise

### Bug Description

There's a problem interacting with my OS credential store during an AzCopy transfer. 

### Steps to Reproduce

1. Launch Azure Storage Explorer
2. Transfer an mp4 file from a container to OneDrive on my PC for viewing and additional details
3. Partial transfer, then above error received. 
4. Outlook, Teams and internet crash
5. Reboot PC and can continue until the issue happens again.

### Actual Experience

![bloberror](https://user-images.githubusercontent.com/104790691/166309619-b734d5f9-58bf-424f-8262-56ac82a0aae0.png)
![bloberror1](https://user-images.githubusercontent.com/104790691/166309621-ea72283b-2aff-4bb7-bf4e-c21f0c1041f5.png)
![bloberror2](https://user-images.githubusercontent.com/104790691/166309624-16e1f898-5f72-4468-838f-701734e93cce.png)

### Expected Experience

My expectation is that the tool or Windows credentials manager would not crash my PC.

### Additional Context

I'm not sure about the architecture field above - here's a screenshot that should help.
![Screenshot 2022-05-02 121206](https://user-images.githubusercontent.com/104790691/166310144-9c45be67-f6e2-4b54-86a7-39c51669281a.png)

**Comment by MRayermannMSFT** [comment]
@v-susab can confirm:
1. How full is your HDD/SSD that you run programs off of?
2. How much memory do you have?

And can you: 
1. Monitor your RAM usage with task manager when doing this type of work, and let us know if the usage is particularly high
3. Try using less programs with Storage Explorer at the same time?

**Comment by v-susab** [comment]
Hello Matthew,

Hopefully the below screenshots answer most of your questions. Thanks for your help!


***@***.***


***@***.***

***@***.***



***@***.***

***@***.***

Every time I start the Azure storage tool I get this error on the first transfer:

***@***.***

In addition, when downloading a particularly large file (e.g. movs), the tool will crash.  This shuts down Internet, Outlook and Teams and requires a reboot.

The tool doesn't seem to have the same problem when transferring the same large files while uploading.

Here's another error I receive after a crash or at the end of the day when closing the tool and shutting down for the day:

***@***.***

**Comment by MRayermannMSFT** [comment]
@v-susab unfortunately you need to come to the issue on github to share images. You cannot do so through email reply.

**Comment by v-susab** [comment]
Let me know if I'm missing anything, thanks

**Comment by MRayermannMSFT** [comment]
@v-susab unfortunately nothing sticks out as reasons we'd be getting this error. You have plenty of system resources, despite what the error says. Can you try running as admin maybe? 😕

**Comment by v-susab** [comment]
Unfortunately the error still persists with running the tool as admin.

![image](https://user-images.githubusercontent.com/104790691/172495136-99d1e662-8530-49bd-9470-9a7d017b3770.png)

**Comment by v-susab** [comment]
A rebuild to the OS cleared the issue. Issue resolved.
