### ISSUE TITLE
Unable to authenticate  in Azure Storage Explorer after changing 2FA

### ISSUE THREAD

**Issue by sergey-rusakov** [microsoft/AzureStorageExplorer#5684]
Hello,
I am using Azure Storage Explorer for confidential file exchange with partner. It worked fine for a while, but then begin to fail authentication step. I thought my password expired or something there so I removed account in Azure Storage explorer then added it back. Azure explorer sends approve sign in to my phone okay, I approve it, Azure storage explorer sees authentication successul. But when I click on particular resource in Azure Storage Explprer I get this error

{
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"connect ETIMEDOUT 20.51.10.137:443\\\",\\n  \\\"stack\\\": \\\"Error: connect ETIMEDOUT 20.51.10.137:443\\\\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)\\\",\\n  \\\"errno\\\": -4039,\\n  \\\"code\\\": \\\"ETIMEDOUT\\\",\\n  \\\"syscall\\\": \\\"connect\\\",\\n  \\\"address\\\": \\\"20.51.10.137\\\",\\n  \\\"port\\\": 443\\n}\""
}

**Comment by sergey-rusakov** [comment]
![image](https://user-images.githubusercontent.com/97978133/166580246-7b8363ab-8797-4734-835d-e72e18c5407c.png)

**Comment by sergey-rusakov** [comment]
When I click on "Reauthenticate now..." link then Edge browser opens new tab briefly displays "Authenticated. You can return to Storage Explorer. You might need to authenticate again if you close this browser tab." text, and focus is transferred back to Azure Storage explorer which repeats the error, and "Reauthenticate now..." message stays.
Please help to solve this issue. Thank you

**Comment by MRayermannMSFT** [comment]
@sergey-rusakov can you try going to Help > Reset, and then only have authentication checked, click reset, restart the app, and then try again?

**Comment by sergey-rusakov** [comment]
Tried the suggested method. Still see the same error. Please see attached screen shot

**Comment by sergey-rusakov** [comment]
![image](https://user-images.githubusercontent.com/97978133/167507413-283439f7-faad-4653-8a7f-29554327cba5.png)

**Comment by DanielaZamoraUribe** [comment]
I am facing the same issue, @sergey-rusakov were you able to fix it?.

**Comment by sergey-rusakov** [comment]
I tried the suggested workaround once, and it appears to work for me, when working remotely today.
Will try more on Tuesday, but for now it works - big thanks !

**Comment by RamonFischer** [comment]
> Can y'all try turning on system proxy? Go to settings (gear on the left) > application > proxy > change the dropdown to say "System proxy (preview)".

It worked for me too! Thanks!!
