### ISSUE TITLE
Can't see the icons of the actions "Delete & Refresh" on the "Actions" panel under the (High Contrast - Black) theme

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5688]
**Storage Explorer Version**: 1.25.0
**Build Number**: 20220505.5
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.3 (MacBook Air M1 2020)
**Architecture** ia32\x64
**How Found**: From running test cases
**Regression From**: Previous release (1.24.0)

## Steps to Reproduce ##
1. Launch Storage Explorer -> Change the theme to "High Contrast - Black".
2. Expand one storage account -> File Shares.
3. Create a file share -> Select the file share.
4. Observe its "Actions" panel.
5. Check whether the icons of the actions "Delete & Refresh" are clear to see.

## Expected Experience ##
The icons of the actions "Delete" and "Refresh" are clear to see.
![image](https://user-images.githubusercontent.com/41351993/166881301-d69e920f-e2d8-4c0a-8cf6-d31e712b8c9a.png)

## Actual Experience ##
Can't see the icons of the actions "Delete" and "Refresh".
![image](https://user-images.githubusercontent.com/41351993/166880529-34b0f1a8-ff69-4b4f-a845-c8e53b0f2f38.png)

## Additional Context ##
1. Here is the screenshot under the Light theme.
![image](https://user-images.githubusercontent.com/41351993/166881425-c7094b9c-ac19-4104-93f0-b3a9a3c1745b.png)
2. This issue doesn't reproduce for Queues.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20220608.1. This issue only reproduces against tables now.

**Comment by MRayermannMSFT** [comment]
Related: https://github.com/microsoft/AzureStorageExplorer/issues/5693

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230117.7. Fixed. So, we are going to close it.
![image](https://user-images.githubusercontent.com/41351993/213074106-d06da858-819a-423f-8576-3d7781c9bc0d.png)
