### ISSUE TITLE
Items cannot be added to quickaccess

### ISSUE THREAD

**Issue by aftonstrale** [Microsoft/AzureStorageExplorer#569]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows 10
**Architecture**: ia32
**Regression From**: earlier recent version on other Windows 7 computer

#### Steps to Reproduce: ####
1. Expand subscription
2. Expand storage account
3. Expand Queues
4. Right click any queue and click "Add to Quick Access"
5. Nothing happens

#### Expected Experience: ####
I was expected to have the item added to my quick access list

#### Actual Experience: ####
Nothing happens at all

**Comment by craxal** [comment]
Likely a duplicate of #535.
