### ISSUE TITLE
Size Display at folder level

### ISSUE THREAD

**Issue by SudhirNune** [microsoft/AzureStorageExplorer#5691]
Storage Explorer does not who the Summarized Size at a folder level, is this a expected behavior or Bug ?

Below is the screenshot
![AZ-Storage](https://user-images.githubusercontent.com/12298924/167007065-2ab29e63-613b-4bbf-8e1a-311a5127cc5d.png)

**Comment by JasonYeMSFT** [comment]
This is the by design. For ADLS Gen2 blobs, There is no way for us to know the summarized size of blobs in a folder without listing blobs and summarize the results. You can select the folder and use the "Folder Statistics" action in the tool bar to get the summarized size of blobs in it.
