### ISSUE TITLE
Use/Allow Themeable Images for Action Icons

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#5693]
Actions panel currently does not theme images. Therefore images for action icons must be default colored such that they appear well for all themes. We've been moving towards images which change colors based on theme though, but we can't use them as action icons. If we just immediately changed to theming them we would mess up images which aren't meant to be themed. We should think about what we want to do about this....

**Comment by MRayermannMSFT** [comment]
Related: https://github.com/microsoft/AzureStorageExplorer/issues/5688

**Comment by JasonYeMSFT** [comment]
Extensions to swap to use the themed icons
- [ ] storage account
- [ ] blob
- [ ] file
- [ ] queue
- [ ] table
- [ ] disks
- [ ] app configuration
