### ISSUE TITLE
Authorization Failure: Can connect to Storage but cannot view blob containers, file shares, tables

### ISSUE THREAD

**Issue by vansree** [microsoft/AzureStorageExplorer#5695]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.23.0

### Architecture

x64

### Storage Explorer Build Number

20220223.14

### Platform

Windows

### Bug Description

Microsoft Azure Storage Explorer gives Authentication error when expanding Blob Containers, after successfully connecting to storage account

### Steps to Reproduce

Launch Storage Explorer

I can connect to the storage account using Microsoft Azure Storage Explorer and then it gives Authorization Failure error. It is US Government cloud / ADLS Gen 2 account.

FYI, I can connect to it using the browser, can view Storage Account, containers. I can upload and delete using the browser.

In the "Microsoft Azure Storage Explorer", after connecting to the storage account and when I try to expand Blob Containers or File Shares or Tables, it gives an error

> Error:
>
> This request is not authorized to perform this operation.
> 
> This storage account's 'Firewalls & virtual networks' settings may be blocking access to storage services. Try adding your client IP address to the firewall exceptions, or by allowing access from 'all networks' instead of 'selected networks'. To learn more about Azure Storage firewalls and virtual networks, visit http://go.microsoft.com/fwlink/?LinkId=845443.
> 
> Error Details:
> {
>   "name": "RestError",
>   "code": "AuthorizationFailure",
>   "statusCode": 403,
>   "request": {
>     "streamResponseStatusCodes": {},

### Actual Experience

AuthorizationFailure

### Expected Experience

To show the Blob Containers

**Comment by MRayermannMSFT** [comment]
@vansree did you check the account's 'Firewalls & virtual networks' settings as the message suggested?

**Comment by ProphetManX** [comment]
I am also having a similar issue.  Earlier this morning I was using Storage Explorer to look at my Storage Accounts/blobs, and I saw the popup for an update (so I did the update).  Now I'm on version 1.24.0, and I am no longer able to view the contents of the Storage Accounts.  I can see a listing of the Storage Accounts, but when I try to expand the carat to see a given accounts contents, it spins for a moment and then in the properties section all I see is the following:
![image](https://user-images.githubusercontent.com/35438914/167472026-7c8a329f-6314-4ce8-907c-365bf054fa3f.png)

I am however able to view the contents of the Disks section just fine.

**Comment by ProphetManX** [comment]
I just uninstalled 1.24.0 and found my previous installer (from when I initially installed the app) which happens to be 1.23.0 
Everything is working fine now.  I'm not sure if my issue matches the original post's, especially if I'm able to use v1.23 but not 1.24 and their post shows 1.23, but just wanted to share my findings with your team.

**Comment by MRayermannMSFT** [comment]
@ProphetManX we're tracking that issue here: https://github.com/microsoft/AzureStorageExplorer/issues/5699

We'll be releasing a hotfix for 1.24 in short order. For now, yes, continue to use 1.23. Thanks for sharing everything too.

**Comment by vansree** [comment]
> Firewalls & virtual networks

@MRayermannMSFT , 
I went to my Storage Account > Under Security + Networking > Networking > Firewalls and virtual networks.

Public network access: "Enabled from selected virtual networks and IP addresses"
Address range exists in the Firewall ... 
Exceptions: Allow Azure services on the trusted services list to access this storage account.

Please let me know, what else to check? 

In the Azure Storage Explorer, I can connect and see the storage account and it fails only when we expand the containers, blobs. My point is, Isn't this good enough to drill down? Am I missing something?

**Comment by MRayermannMSFT** [comment]
@vansree so....
1. Can you confirm that the IP address of your machine is in the allowed range?
2. Did you sign in or attach the storage account? If you signed in, can you make sure that you have appropriate RBAC roles to read blob data (blob data reader, blob data contributor, blob data owner) or that you have access to the storage account's keys?

**Comment by MRayermannMSFT** [comment]
@ProphetManX FYI we shipped 1.24.1 and you can find it here: https://github.com/microsoft/AzureStorageExplorer/releases

**Comment by vansree** [comment]
> @vansree so....
> 
> 1. Can you confirm that the IP address of your machine is in the allowed range?
> 2. Did you sign in or attach the storage account? If you signed in, can you make sure that you have appropriate RBAC roles to read blob data (blob data reader, blob data contributor, blob data owner) or that you have access to the storage account's keys?

I downloaded 1.24.1 and same issues persists. (I do see that you fixed other issue, but clarifying the issue exists)

For 1. I work remote and behind VPN. Looks like per your notes, it is ip address block. Please let me know where exactly I have to check Or what to check...  
(I already checked under Storage Account > Under Security + Networking > Networking > Firewalls and virtual networks)

For 2. I login with my account using Azure Storage Explorer.  I have these assignments, when I checked on the browser:
          Roles:
          - Reader
          - Storage Account Contributor
          - Storage Blob Data Contributor
          - Storage Blob Data Owner

**Comment by MRayermannMSFT** [comment]
@vansree given it seems like this is an issue with your firewall, I would suggest opening an Azure support ticket and talking to them for help. They are much better at helping diagnose such issues. You can do that via here: https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview

**Comment by vansree** [comment]
Thank you, will do that.

**Comment by vansree** [comment]
**Here is the update:**
1. I am working remote and connected to a vpn. I am able to login to a sandbox server and using the Azure Storage Explorer, I am able to create a blob container and upload files successfully. 

2. I can connect to the same files (which are uploaded) using Power BI Desktop from my local computer and also from the sandbox server. No issues in getting to the power bi desktop. 

3. The network person worked with me and says, as I am able to connect from the Power BI to the same location, it is not ip address or firewall issue or my account issue. I can process the data from Power BI.

He thinks the issue is with Azure Storage Explorer. I am in Catch 22 situation now ... 

**Error is the same "Authentication Error"**
Error "Authentication Error"

If you cannot resolve this issue on your own, you may open an issue on the Storage Explorer GitHub site. Please include the details below to help us diagnose your issue. Make sure to redact any personal information you do not wish to make public before posting.

========================
This request is not authorized to perform this operation.

This storage account's 'Firewalls & virtual networks' settings may be blocking access to storage services. Try adding your client IP address to the firewall exceptions, or by allowing access from 'all networks' instead of 'selected networks'. To learn more about Azure Storage firewalls and virtual networks, visit http://go.microsoft.com/fwlink/?LinkId=845443.

Error Details:
{
  "name": "RestError",
  "code": "AuthorizationFailure",
  "statusCode": 403,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://********.blob.core.usgovcloudapi.net/?comp=list&include=metadata",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2020-10-02"
        },
        "accept": {
          "name": "Accept",
          "value": "application/xml"
        },
        "user-agent": {
          "name": "User-Agent",
          "value": "Microsoft Azure Storage Explorer/1.24.1 (win32) azsdk-js-storageblob/12.8.0 (NODE-VERSION v16.13.2; Windows_NT 10.0.19044)"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "*********************"
        },
        "authorization": {
          "name": "authorization",
          "value": "Bearer JSON Web Token Redacted"
        },
        "cookie": {
          "name": "Cookie",
          "value": ""
        }
      }
    },
    "withCredentials": false,
    "timeout": 0,
    "keepAlive": true,
    "decompressResponse": false,
    "requestId": "*********************"
  },
  "response": {
    "headers": {
      "_headersMap": {
        "content-length": {
          "name": "content-length",
          "value": "246"
        },
        "content-type": {
          "name": "content-type",
          "value": "application/xml"
        },
        "date": {
          "name": "date",
          "value": "Mon, 23 May 2022 23:15:18 GMT"
        },
        "server": {
          "name": "server",
          "value": "Microsoft-HTTPAPI/2.0"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "*********************"
        },
        "x-ms-error-code": {
          "name": "x-ms-error-code",
          "value": "AuthorizationFailure"
        },
        "x-ms-request-id": {
          "name": "x-ms-request-id",
          "value": "*********************"
        }
      }
    },
    "request": {
      "streamResponseStatusCodes": {},
      "url": "https://*****************.blob.core.usgovcloudapi.net/?comp=list&include=metadata",
      "method": "GET",
      "headers": {
        "_headersMap": {
          "x-ms-version": {
            "name": "x-ms-version",
            "value": "2020-10-02"
          },
          "accept": {
            "name": "Accept",
            "value": "application/xml"
          },
          "user-agent": {
            "name": "User-Agent",
            "value": "Microsoft Azure Storage Explorer/1.24.1 (win32) azsdk-js-storageblob/12.8.0 (NODE-VERSION v16.13.2; Windows_NT 10.0.19044)"
          },
          "x-ms-client-request-id": {
            "name": "x-ms-client-request-id",
            "value": "*********************"
          },
          "authorization": {
            "name": "authorization",
            "value": "Bearer JSON Web Token Redacted"
          },
          "cookie": {
            "name": "Cookie",
            "value": ""
          }
        }
      },
      "withCredentials": false,
      "timeout": 0,
      "keepAlive": true,
      "decompressResponse": false,
      "requestId": "*********************"
    },
    "status": 403,
    "bodyAsText": "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.\nRequestId:*********************\nTime:2022-05-23T23:15:18.9662454Z</Message></Error>",
    "parsedBody": {
      "message": "This request is not authorized to perform this operation.\nRequestId:*********************\nTime:2022-05-23T23:15:18.9662454Z",
      "code": "AuthorizationFailure"
    },
    "parsedHeaders": {
      "errorCode": "AuthorizationFailure",
      "content-length": "246",
      "content-type": "application/xml",
      "date": "Mon, 23 May 2022 23:15:18 GMT",
      "server": "Microsoft-HTTPAPI/2.0",
      "x-ms-client-request-id": ""*********************",
      "x-ms-request-id": "*********************"
    }
  },
  "details": {
    "errorCode": "AuthorizationFailure",
    "content-length": "246",
    "content-type": "application/xml",
    "date": "Mon, 23 May 2022 23:15:18 GMT",
    "server": "Microsoft-HTTPAPI/2.0",
    "x-ms-client-request-id": "*********************",
    "x-ms-request-id": "*********************",
    "message": "This request is not authorized to perform this operation.\nRequestId:*********************\nTime:2022-05-23T23:15:18.9662454Z",
    "code": "AuthorizationFailure"
  }

**Comment by MRayermannMSFT** [comment]
> The network person worked with me

Was this a person at your company or a Microsoft support engineer?

**Comment by vansree** [comment]
@MRayermannMSFT ... This is from my company. (i.e., NOT Microsoft support engineer)

**Comment by MRayermannMSFT** [comment]
Ok, you should open a ticket from the Azure Portal to start a ticket with a Microsoft support engineer. They will be able to best help dive into this issue.

**Comment by ehmidH** [comment]
Hi all,

I have the same issue described by @vansree.
@vansree Can you help by updating this post with the solution you have found? 
I appreciate your time and help
