### ISSUE TITLE
A 'Copy Conflict' dialog pops up when cloning one emulator blob container which contains an archived blob

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5696]
**Storage Explorer Version:** 1.25.0
**Build Number:** 20220506.1
**Branch:** main
**Platform/OS:** Windows 10
**Architecture:** ia32
**Azurite Version:** 3.16.0
**How Found:** Ad-hoc testing
**Regression From:** Previous release (1.23.1)

## Steps to Reproduce ##

1. Install and run Azurite 3.16.0 -> Launch Storage Explorer.
2. Expand 'Local & Attached -> Storage Accounts -> (Emulator - Default Ports) (Key)'.
3. Blob Containers -> Create a blob container ->Upload a blob and set its access tier to Archive.
4. Right click the blob container -> Click 'Clone...'.
5. Input a valid name -> Click 'Clone'.
6. Check no 'Copy Conflict' dialog pops up.

## Expected Experience ##
No 'Copy Conflict' dialog pops up. 

## Actual Experience ##
A 'Copy Conflict' dialog pops up.
![image](https://user-images.githubusercontent.com/87792676/167247200-3d214971-740c-4e4e-9803-f367651f55af.png)

## Additional Context ##
This issue also reproduces when using Azurite 3.17.1.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220517. Fixed.
