### ISSUE TITLE
Cannot see the icons of the actions 'Download/Download & Open' on the 'Open Direct Link' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5698]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220509.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 18.04/MacOS Monterey 12.3 (MacBook Air M1 2020)
**Architecture** ia32\x64
**How Found**: From running test cases
**Regression From**: Previous release (1.24.0)

## Steps to Reproduce ##
1. Launch Storage Explorer -> Change the theme to 'High Contrast - Black'.
2. Expand one ADLS Gen2 storage account -> Blob Containers.
3. Create a blob container -> Upload one blob.
4. Right click the blob -> Click 'Copy Direct Link'.
5. Open the direct link from the browser -> Observe the 'Open Direct Link' dialog.
6. Check whether it is clear to see all icons.

## Expected Experience ##
It is clear to see all icons.
![image](https://user-images.githubusercontent.com/41351993/167380456-bccd06ed-42d9-46cf-8f77-4850ec7b3cf5.png)

## Actual Experience ##
Cannot see the icons of the actions 'Download/Download & Open'.
![image](https://user-images.githubusercontent.com/41351993/167380530-eec12368-00c1-4d84-af7c-e2b8ba64935b.png)

## Additional Context ##
Here is the screenshot on Light theme against two versions.
![image](https://user-images.githubusercontent.com/41351993/167380263-787e82c4-6575-4b02-903b-371f349533c0.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220513.1. Fixed.
