### ISSUE TITLE
Storage Accounts don't work with non-public Azure clouds in 1.24

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#5699]
There are several mandatory files we require in this
repository. A pull request has been opened to add the
missing files. When the pr is merged this issue will be
closed automatically.

[Merge this pull request]()

**Comment by srbrills** [comment]
Confirmed also getting this behavior.  Reinstalling and/or re-authenticating does not solve the issue.  Developer tools in explorer don't seem to add any useful info.  Downgrading back to 1.23.1 works as a workaround.

**Comment by MRayermannMSFT** [comment]
We're going to be shipping 1.24.1 today! It includes a fix for this.
