### ISSUE TITLE
Network error when accessing Tables node

### ISSUE THREAD

**Issue by michaeldaw** [Microsoft/AzureStorageExplorer#57]
**Storage Explorer Version:**
1.0.0
**OS Version:**
Windows 10
**Steps to Reproduce:**

1. Open a Storage Account node
2. Click on the Tables node

**Expected Experience:**
Display tables
**Actual Experience:**
Not always, but often the following popup displays:
![image](https://user-images.githubusercontent.com/8949148/39080265-af029a8e-44e7-11e8-9831-a898315138e2.png)
Seems to happen only in recent versions

**Comment by craxal** [comment]
Can you tell us more about your network environment? How's your speed? Any proxies or security settings? Are you accessing the account via sign-in, account name/key, or SAS?

**Comment by craxal** [comment]
Not necessarily. Sign-in is just more convenient for you, since you can get all your subscriptions and accounts you have access to.

Our release notes mentioned that you'll need to sign out and sign back in when upgrading to 1.0.0. Did you already do that?

And is it just tables that you're experiencing this?

**Comment by michaeldaw** [comment]
I believe I'd signed out, but I did it again now just to be certain.

I've only ever seen the problem while using tables, but I use tables far more than the other types of storage.

**Comment by craxal** [comment]
Hm, it's possible you're just experiencing bad connections. We'll need more network information to be sure. Can you provide a network trace using [Fiddler](https://www.telerik.com/fiddler)? I assume this is happening for every table service, regardless of account?

**Comment by craxal** [comment]
Actually, just kidding. Fiddler traces aren't going to provide much info. It doesn't play well with Node applications.

If you open the developer tools (hit F12), do you see any errors in the console tab/drawer when you run into this issue?

**Comment by michaeldaw** [comment]
I had no idea you could open the developer tools like that.

The following error appears whenever I expand a storage account node for the first time in a session, but not when expanding a table node (or any other node). Not sure if it's relevant.
```
Failed to load attribute: shouldPreExpandNodes
error @ Debug.js:39
(anonymous) @ BindingHandler.js:27
tryCatch @ -internal.js:195
invokeCallback @ -internal.js:210
publish @ -internal.js:178
publishRejection @ -internal.js:120
flush @ asap.js:98
```

**Comment by craxal** [comment]
Yeah, that's pretty benign. Has nothing to do with this.

Unfortunately, I'm out of ideas Storage Explorer side. How's the performance of the Azure portal? If tables take a while to load in the portal, then it may be an issue with the network or your table service.

**Comment by michaeldaw** [comment]
I understand. The portal performance *seems* fine. I agree that it seems like some kind of network problem. I'll try to look in to this. Thanks for the ideas. If I find something more concrete, I'll be sure to post the information.

**Comment by craxal** [comment]
Closing this bug as stale. If this continues to be an issue, please let us know, and we can reopen.
