### ISSUE TITLE
There is an extra scrollbar in the 'Open Table by Name' dialog when typing '\' to search emulator tables

### ISSUE THREAD

**Issue by v-sunnysun** [microsoft/AzureStorageExplorer#5701]
**Storage Explorer Version:** 1.24.1
**Build Number:** 20220510.2
**Branch:** hotfix/1.24.1
**Platform/OS:** Windows 10
**Architecture:** ia32
**Azurite Version:** 3.16.0
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Install and run Azurite 3.16.0 -> Launch Storage Explorer.
2. Expand 'Local & Attached -> Storage Accounts -> (Emulator - Default Ports) (Key)' -> Right click 'Tables' node.
3. Click 'Open Table by Name...' -> Type '\\' in the Table name field -> Click 'Search'.
4. There is an error message.
5. Check there is no extra scrollbar.

## Expected Experience ##
There is no extra scrollbar.

## Actual Experience ##
There is a scrollbar.
![image](https://user-images.githubusercontent.com/98519664/167592429-401beaff-3cb8-4709-82c3-4147dd515da5.png)

## Additional Context ##
1. Related bug: [5600](https://github.com/microsoft/AzureStorageExplorer/issues/5600).
2. There is no error message for emulator blob containers and queues.
3. There is no error message for normal tables.
![image](https://user-images.githubusercontent.com/98519664/167597118-5329dcb9-48f9-4d76-8563-83e90523aea4.png)

**Comment by craxal** [comment]
Likely another issue in the emulator, but I wouldn't consider this worth fixing, since '\' is not a valid character for a table name and would yield zero results regardless.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220613.1. Fixed.
![image](https://user-images.githubusercontent.com/41351993/173264700-214bfc69-752a-4185-86c8-2cf3859639df.png)
