### ISSUE TITLE
The 'Open Direct Link' dialog for files is opened when opening one soft deleted ADLS Gen2 folder's direct link

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5703]
**Storage Explorer Version**: 1.24.1
**Build Number**: 20220510.2
**Branch**: hotfix/1.24.1
**Platform/OS**: Windows 10/Linux Ubuntu 18.04/MacOS Monterey 12.3 (MacBook Air M1 2020)
**Architecture** ia32\x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Create a new folder.
3. Soft delete the folder -> Switch to 'Deleted only' context view.
4. Right click the soft deleted folder -> Click 'Copy Direct Link'.
5. Open the direct link from Browser -> There is an 'Open Direct Link' dialog.
6. Check whether the dialog is for folders.

## Expected Experience ##
The dialog is for folders.
![image](https://user-images.githubusercontent.com/41351993/167794146-0ebe689b-9c12-43d5-86ea-ae784f5ccecd.png)

## Actual Experience ##
The dialog is for files.

![image](https://user-images.githubusercontent.com/41351993/167794140-41e8e8d5-0f50-4080-b07a-dad5b2ad5f9e.png)

**Comment by MRayermannMSFT** [comment]
Won't fix for now. The direct link feature is not intended to be used with soft deleted folders. Can revisit if a user asks for it.
