### ISSUE TITLE
Cannot make connection to the storage

### ISSUE THREAD

**Issue by MiraliKPN** [microsoft/AzureStorageExplorer#5709]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.23.1

### Architecture

x64

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://bssdevstorage001sa.blob.core.windows.net/?comp=list&include=metadata failed, reason: connect ETIMEDOUT 10.28.163.5:443",
  "stack": "FetchError: request to https://bssdevstorage001sa.blob.core.windows.net/?comp=list&include=metadata failed, reason: connect ETIMEDOUT 10.28.163.5:443\n    at ClientRequest.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1491:11)\n    at ClientRequest.emit (node:events:394:28)\n    at TLSSocket.socketErrorListener (node:_http_client:447:9)\n    at TLSSocket.emit (node:events:394:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "ETIMEDOUT",
  "code": "ETIMEDOUT"
}

### Steps to Reproduce

1. Launch Explorer
2. Expand Storage
3. Try to open Blob Containers

### Actual Experience

I'm trying to open the Blob Containers, but I cannot open these connections.

**Comment by MRayermannMSFT** [comment]
@MiraliKPN can you give using system proxy setting a try? You can read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview
