### ISSUE TITLE
Exception  0x80000003 when trying to start StorageExplorer.exe

### ISSUE THREAD

**Issue by toastmastern** [microsoft/AzureStorageExplorer#5716]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.0

### Architecture

x64

### Storage Explorer Build Number

20220503.4

### Platform

Windows

### OS Version

Windows 10 Enterprise for Virtual Desktops, 21H2, 19044.1706

### Bug Description

When launching Storage Explorer the process runs shortly and dies with this event log

Faulting application name: StorageExplorer.exe, version: 1.24.0.0, time stamp: 0x626aa8db
Faulting module name: StorageExplorer.exe, version: 1.24.0.0, time stamp: 0x626aa8db
Exception code: 0x80000003
Fault offset: 0x0176177a
Faulting process id: 0x34f0
Faulting application start time: 0x01d866041d412a97
Faulting application path: C:\Users\"user"\AppData\Local\Programs\Microsoft Azure Storage Explorer\StorageExplorer.exe
Faulting module path: C:\Users\"user"\AppData\Local\Programs\Microsoft Azure Storage Explorer\StorageExplorer.exe
Report Id: 0cca6e8c-1525-4735-8f58-a93217f797be
Faulting package full name: 
Faulting package-relative application ID: 

### Steps to Reproduce

1. Launch Storage Explorer
2. Check task manager to see process die

### Actual Experience

Nothing happens, event log is written
I see a session folder being created in %APPDATA% (without content)
I see in console output below log folder but no such folder is created in AppData

If i run from command line the following is printed in console and then process die

[2022-05-12T13:36:36.897Z] (main:55732) <NONE> Log file: C:\Users\"user"\AppData\Roaming\StorageExplorer\logs\2022-05-12_153636\2022-05-12_153636_main_55732.log
[2022-05-12T13:36:36.899Z] (main:55732) <NONE> Log level: info
[2022-05-12T13:36:36.899Z] (main:55732) <INFO> Startup app state:  {
    lastWindowState: {
      rect: { x: 1304, y: 37, width: 1000, height: 768 },
      maximized: false
    },
    disableGpu: false,
    dialogAutoResponse: {}
  }

(the log file and folder above will not be created)

**Comment by JasonYeMSFT** [comment]
@toastmastern Is "Windows 10 Enterprise for Virtual Desktops" a special distribution of Windows or are you using Windows 10 Enterprise on a virtual machine? Also have you used Storage Explorer versions prior to 1.24.0 in the same environment? If not, could you try 1.23.1 to see if it works?

**Comment by toastmastern** [comment]
Hi, thanks for the quick reply, yes, we run this on Azure Virtual Desktop and they have their own version of windows AFAIK
We have been running on this environment since corona started with storage explorer so yes, several versions.

Will try downgrade early upcoming week + try 1.24.1. Also, one strange thing, did try running as administrator now and that did not throw exception, however have had intermittent reports about storage explorer from our other users so cannot say if it was a lucky shot or not.

**Comment by MRayermannMSFT** [comment]
@toastmastern have you tried downgrading yet? You can find old releases here: https://github.com/microsoft/AzureStorageExplorer/releases

**Comment by toastmastern** [comment]
Hi again, got reports from devs that it doesnt work.

Tested 1.23.1 (user installed) - works fine
Upgraded to 1.24.1 (user installed) - doesnt work (same error in event log as above)

Tried one more thing - started 1.24.1 in elevated (admin) mode - works(!)
Some kind of permission that has changed?

Let me know if i should try something else

**Comment by nhsedcmichaelross** [comment]
We are experiencing the same issue with AVD.  We have tried the current 1.24.0 and 1.24.1 on both SKU win10-21h1-avd-m365 and win10-21h2-avd-m365 (both gen 1) and are experiencing the same error.

I will roll it back to 1.23.1 today and get user feedback.

**Comment by MRayermannMSFT** [comment]
@toastmastern @nhsedcmichaelross did y'all install Storage Explorer for "all users" or only "current user"?

**Comment by MRayermannMSFT** [comment]
Turns out this is most likely an electron issue. If so, there is a fix in the version we are updating to in our next release. We will share a preview build of that later this week for you to try.

**Comment by toastmastern** [comment]
> @toastmastern @nhsedcmichaelross did y'all install Storage Explorer for "all users" or only "current user"?

Tried both with same result

**Comment by nhsedcmichaelross** [comment]
> @toastmastern @nhsedcmichaelross did y'all install Storage Explorer for "all users" or only "current user"?

We are using All Users.

**Comment by MRayermannMSFT** [comment]
Hi @toastmastern and @nhsedcmichaelross , we are preparing to ship a hotfix to address this issue. Can you please try using this release candidate and see if it resolves the issue for you? All users on the shared machine will need to be using this version. Thanks! https://storageexplorerpublish.blob.core.windows.net/privatebuilds/1.24.2-rc1/StorageExplorer-ia32.exe

**Comment by nhsedcmichaelross** [comment]
Had four people test it at the same time on the same machine using win10 multisession on AVD and it seems to be working fine :)  Will do some more testing and report back shortly.

**Comment by nhsedcmichaelross** [comment]
Reports back are saying that all is well and it appears to be working normally again.
