### ISSUE TITLE
Succeed to create an emulator item with the same name of one item which is being deleted

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5719]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220513.1
**Branch**: main
**Platform/OS**: Windows 10
**Architecture** ia32\x64
**Azurite version** 3.17.1
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Install and run Azurite 3.17.1. 
2. Expand (emulator -Default Ports) (Key) -> Tables.
3. Create a table -> Delete the table.
4. Try to create a table with the deleting table's name.
5. Check whether fails to create the table.

## Expected Experience ##
Fail to create the table with the error 'TableBeingDeleted'.

## Actual Experience ##
Succeed to create the table.

## Additional Context ##
This issue reproduces for emulator blob containers/queues.

**Comment by JasonYeMSFT** [comment]
I believe for emulators, the delete is almost instantaneous because everything happens in the same machine. So unlike the online service the subsequent create will immediately happen for emulators.
