### ISSUE TITLE
The toolbar of one table/file share displays blank

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5721]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220513.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 18.04/MacOS Monterey 12.3 (MacBook Air M1 2020)
**Architecture** ia32\x64
**How Found**: From running test cases
**Regression From**: Previous release (1.24.1)

## Steps to Reproduce ##
1. Expand one storage account -> Tables/File Shares.
2. Open one table/file share.
3. Check the toolbar displays well.

## Expected Experience ##
The toolbar displays well.

## Actual Experience ##
The toolbar displays blank.
![image](https://user-images.githubusercontent.com/41351993/168237600-5c188b5c-4a57-43ae-9c1f-8d86e9aba2f1.png)

**Comment by craxal** [comment]
@v-xianya This is a known issue. I have been making changes to the toolbar that are not complete yet. You can forego reporting issues until I let you know.

**Comment by craxal** [comment]
@v-xianya I am unable to reproduce this issue in the current state of main. It's possible you got a build that did not have all the necessary changes in it. Please verify again.

**Comment by v-xianya** [comment]
Verified this issue on the build main/2022056.1. Fixed.
