### ISSUE TITLE
An error dialog pops up when clicking 'Change Access Tier…/Clone and Rehydrate…' for blobs

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5727]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220516.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 18.04/MacOS Monterey 12.3 (MacBook Air M1 2020)
**Architecture** ia32\x64
**How Found**: From running test case
**Regression From**: Previous release (1.24.1)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Right click the blob -> Click 'Change Access Tier...'.
4. Check whether the 'Update Access Tier' dialog pops up.

## Expected Experience ##
The 'Update Access Tier' dialog pops up.

## Actual Experience ##
An error dialog pops up.
![image](https://user-images.githubusercontent.com/41351993/168551011-5f7c7ecb-8257-4ebb-b3b0-08f5f33a9c1a.png)

## Additional Context ##
1. This issue also reproduces when clicking 'Change Access Tier…' for folders.
2. The error details:
`
error
The view model imported from 'C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\se-blob-extension\dist\src\Dialogs\SetAccessTier\SetAccessTierViewModel.js' does not inherit from 'DialogWindowViewModel', 'DialogViewModel', or 'MultipanelDialogViewModel'Error: The view model imported from 'C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\node_modules\se-blob-extension\dist\src\Dialogs\SetAccessTier\SetAccessTierViewModel.js' does not inherit from 'DialogWindowViewModel', 'DialogViewModel', or 'MultipanelDialogViewModel'
    at handleDialogInitWithViewModel (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\dialogs\Common\DialogView.js:164:19)
    at async handleDialogInit (C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\dialogs\Common\DialogView.js:110:17)
`

**Comment by JasonYeMSFT** [comment]
The imported view model classes in DialogView.ts should now be imported from the renamed package @storage-explorer/ui-components.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20220517.3. Fixed.
