### ISSUE TITLE
The new created file share/table under QA storage account does not auto display under its original storage account node which is already expanded

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5729]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220516.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 18.04/MacOS Monterey 12.3 (MacBook Air M1 2020)
**Architecture** ia32\x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Add the storage account to Quick Access.
2. Expand the QA storage account -> Create a new blob container/file share/queue/table.
3. Check whether the new created service auto displays under its original node.

## Expected Experience ##
The new created service auto displays under its original node.

## Actual Experience ##
1. The new created blob container/queue auto displays under its original node.
2. The new created file share/table does not auto display under its original node.

## Additional Context ##
On the previous release 1.22.1, the new created table auto displays under its original node.

**Comment by MRayermannMSFT** [comment]
Let's **not** support this behavior. Only the current instance of the account needs to be kept up to date.

**Comment by MRayermannMSFT** [comment]
Changes merged into main. Only the service node which was right clicked should be expanded and have the child node added.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20221101.2. Fixed.
