### ISSUE TITLE
Unable to Connect to Storage Account in AzureStorageExplorer

### ISSUE THREAD

**Issue by U362496** [microsoft/AzureStorageExplorer#573]
**Storage Explorer Version**: 
**Platform/OS Version**: 
**Architecture**: 
**Regression From**: 

#### Steps to Reproduce: ####
1. Whilst using AzureStorageExplorer to 'Connect' to my Azure Storage Account I am getting the below error message for storage account 'mdsdemo'
2. After a while, the 'Loading Subscriptions' message was replaced with the following error.

########################
Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: xxxxxxxx-c6bc-4fa7-bbd0-c0f9ffcda1b4, Error: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"xx.xxx.xxx.xxx","port":443}
########################

#### Expected Experience: ####
I expected to be able to  connect to my Azure Storage Account

#### Actual Experience: ####
The connection appears to be timing out.

**Comment by MRayermannMSFT** [comment]
Hmmmm, ya this looks like a network issue. Are you behind a proxy?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
