### ISSUE TITLE
Manually checking for updates should do its best to get you an update (Update check from v1.23.1 states No Update Available)

### ISSUE THREAD

**Issue by golaat** [microsoft/AzureStorageExplorer#5733]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.23.1

### Architecture

x64

### Storage Explorer Build Number

20220406.1

### Platform

Windows

### OS Version

Windows 10 20H2 (19042.1645)

### Bug Description

I have v1.23.1 of Storage Explorer installed on my machine in an Enterprise environment. We have a firewall which does SSL inspection of all outbound traffic and I have loaded that certificate into Storage Explorer. I can connect via Storage Explorer without issue to the Azure Environment.

If I go to the Help | Check for Updates menu in v1.23.1 of Storage Explorer It tells me that there are no updates, despite that v1.24.1 is available.

I have looked at the logs (under Help | Open Logs Directory) to see if there are any connectivity errors and I don't see anything in the log files to indicate that. 

### Steps to Reproduce

1. Install Storage Explorer v1.23.1
2. Launch Storage Explorer
3. Navigate to Help and then select Check for Updates

### Actual Experience

Storage Explorer reports "There is no update available"

### Expected Experience

I would expect Storage Explorer to inform me there is a newer version and as if I would like to install it.

**Comment by MRayermannMSFT** [comment]
@golaat thanks for being eager to update! As of when you posted your issue, although 1.24.1 was available via various channels (github releases page, azure.com page, snapstore), we hadn't yet sent out the in app update. It takes a few days for new releases to get propagated to all of the various download servers/CDNs so we delay sending out the in app update until a a few days after we upload the new release.

We're rolling out the in app update today though, and within a few hours you should expect the in app update to work. Of course, feel free to download the new version yourself directly from the releases page or azure.com right now if you'd like.

**Comment by golaat** [comment]
@MRayermannMSFT thanks for the detailed information. This explains the behavior we were seeing and fills the knowledge gaps I had.

**Comment by MRayermannMSFT** [comment]
> if a user manually invokes the Check for Update

Yes, that is indeed good feedback. I will think about how we can make this happen, either with our current updating setup or with some changes. Will use this issue to track that.

**Comment by MRayermannMSFT** [comment]
We've made a variety of changes to our mechanism to make this more posssible, most of which occurred in 1.27.0 I would say.
