### ISSUE TITLE
Unable to get local issuer certificate

### ISSUE THREAD

**Issue by zachdialwynnlasvegas** [microsoft/AzureStorageExplorer#5738]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.23.1

### Architecture

x64

### Storage Explorer Build Number

20220406.1

### Platform

Windows

### OS Version

Windows 10

### Bug Description

{
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"unable to get local issuer certificate\\\",\\n  \\\"stack\\\": \\\"Error: unable to get local issuer certificate\\\\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)\\\\n    at TLSSocket.emit (node:events:394:28)\\\\n    at TLSSocket._finishInit (node:_tls_wrap:944:8)\\\\n    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)\\\",\\n  \\\"code\\\": \\\"UNABLE_TO_GET_ISSUER_CERT_LOCALLY\\\"\\n}\""
}

### Steps to Reproduce

1. Launch Storage Explorer
2. Right Click Storage Accounts>Connect to Azure Storage
3. Select Subscription
4. Select Azure
5. Select Next
6. Successfully Authenticate to Azure
7. Error produces

### Actual Experience

Warning Message with Yellow ! shows under tenant with the following description when selecting error details:

{
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"unable to get local issuer certificate\\\",\\n  \\\"stack\\\": \\\"Error: unable to get local issuer certificate\\\\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)\\\\n    at TLSSocket.emit (node:events:394:28)\\\\n    at TLSSocket._finishInit (node:_tls_wrap:944:8)\\\\n    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)\\\",\\n  \\\"code\\\": \\\"UNABLE_TO_GET_ISSUER_CERT_LOCALLY\\\"\\n}\""
}

### Expected Experience

Workstation will connect to Azure storage without issue

**Comment by MRayermannMSFT** [comment]
@zachdialwynnlasvegas  can you give using system proxy setting a try? You can read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by Sreepathy-J** [comment]
Hi @MRayermannMSFT, I'm getting the same issue as well. Tried with all the different proxy settings.

**Comment by LillyBeast-TMO** [comment]
@MRayermannMSFT - I had the same issue as the OP just now. Switching to System proxy fixed it.
