### ISSUE TITLE
error when access azure storage 

### ISSUE THREAD

**Issue by jfernandes2022** [microsoft/AzureStorageExplorer#5739]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.0

### Architecture

x64

### Storage Explorer Build Number

20220503.4

### Platform

Windows

### OS Version

windows 10

### Bug Description

{
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"self signed certificate in certificate chain\\\",\\n  \\\"stack\\\": \\\"Error: self signed certificate in certificate chain\\\\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)\\\\n    at TLSSocket.emit (node:events:390:28)\\\\n    at TLSSocket._finishInit (node:_tls_wrap:944:8)\\\\n    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)\\\",\\n  \\\"code\\\": \\\"SELF_SIGNED_CERT_IN_CHAIN\\\"\\n}\""
}

### Steps to Reproduce

launch storage explorer
login 

### Actual Experience

i get authentication error
![image](https://user-images.githubusercontent.com/105778840/168993590-07af924b-2804-4745-b90e-260dc1bd62f4.png)

**Comment by jfernandes2022** [comment]
reauthenticate also does not help

**Comment by MRayermannMSFT** [comment]
@jfernandes2022 can you give using system proxy setting a try? You can read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue we recommend opening a support ticket from the Azure portal. Alternatively you can open a new issue here.
