### ISSUE TITLE
Unable to access storage account

### ISSUE THREAD

**Issue by SriKatakam21** [Microsoft/AzureStorageExplorer#5742]
{
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"self signed certificate in certificate chain\\\",\\n  \\\"stack\\\": \\\"Error: self signed certificate in certificate chain\\\\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)\\\\n    at TLSSocket.emit (node:events:394:28)\\\\n    at TLSSocket._finishInit (node:_tls_wrap:944:8)\\\\n    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)\\\",\\n  \\\"code\\\": \\\"SELF_SIGNED_CERT_IN_CHAIN\\\"\\n}\""
}

**Comment by MRayermannMSFT** [comment]
@SriKatakam21 can you give using system proxy setting a try? You can read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue we recommend opening a support ticket from the Azure portal. Alternatively you can open a new issue here.

**Comment by Sriharikatakam** [comment]
Thank you so much for the providing the documents and apologies for delay in response. My issue resolved after following the document.
