### ISSUE TITLE
order by size does not consider the unit

### ISSUE THREAD

**Issue by BruntonAndrewL** [microsoft/AzureStorageExplorer#5745]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.1

### Architecture

x64

### Storage Explorer Build Number

20220510.2

### Platform

Windows

### Bug Description

![image](https://user-images.githubusercontent.com/105824526/169162351-ca9efd7b-2fe8-4184-80b6-66694d75badd.png)

the order by size only consider the number without unit.

### Steps to Reproduce

order by size

### Actual Experience

cannot find the biggest one immediately.

**Comment by ian-bowler** [comment]
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEMAAABlCAYAAAAWP15YAAAHOklEQVR4Ae1cTU4jOxDmMslbz8sBRvPm6Z0CCbHgFEhZsBmxB4kDIAV2LLNBCkgIiWXYIySUA+QE9fTZLleV207oCQRmphZRd9x2/Xz1VXXHbmdnMBgSPl+//heO/P1PPO6w0w7GkByMlBkghYPhYMQ6ySWCj84MZ4YzY+2jg6eJp8l7psn4gm7v7tPngg4T2run13Q7Ga+lJ1fztz5++fI3ffv2T0c/2nCt1Ld5muyd0fROABjsndHJuI58qfw9v8PZh4cHen5+pu/f/82O4xxtuFYCsjkYYMUHRr8G6HD4F93d3dHV1RUdHR3R09NTAARA4BxtuIY+6MsyNgdjMKbzu3uanu5loSwcaRLaA3s4jeLxnNmjU2x6RruqoLGcnzkeHBzQy8sL7e/vZ0AYCLThGvpo2W8ABlJij06mhZODIWUwtIOaSfq81V+P7XleAgJGtIAAKG8EBteIyBKOeheMMZ2r6IcCmwtvYs4bp5wGZBUQ7wDGkAYq2hYMsOeaTvYYuAZzekZf07x1zoDUUkOP2ZwZ4wtiJkBwiHaKrgbjcHJv+gUjQr1Qd6J3AIKdBSD48PfacXMwVL0IzxpFGoQCGpy2BZQLbpkqGtiawe/Z9gZgCO3f09BtyHYwVGo6GA5GPbWdGc4MZ8bKZwzcrTxNPE0aaYJlRf9EDHZGoxH5J2LgYCgyOBgORr00ODOcGc6MtXdNT5ON0uRyTsvlMn4WMzpmYbp9OacJt+P4Y0aL2hjdZzSi45tFlr24Oa5EckLz5ZLq145ptlDXjD2qvdCpn7H6MSM4taDZj5hzk0dRcnw5ycAEpx4nyRk4UB+jDbFj6jk9Gk1ovljQQgeBnbuc0wLXGESA0bBB69Xn/cAwClLEa4YBNG5/1RgAVrCJnTTH2G/+uKT5pQVs8rig2c28AcaIELhyjAYC573A6EQvMKXrBPpxhPR5VF5xHHIeZ4HmMQWFSdbgNLYB8ETpHek+OjgGXAtoLzBi7ovzAZwc0ZizcIaBgCOvAgOGL1Xk8J2ZZYxnIKFLAIMORN3oSjK5vq1jRW9msHOsYHEzo3nF6ABSajcGBsfYIRWVjvOVPsVYkSt9pW1EhhmjmCY6SJZx0ZZ+zDBR6ioUBSpycDQXskad6dBYHBSZMFi3p3MUzlQ0V4FRgmPlbgwGjGGqHtPkUt0KTaR1PxshKWoxxZjKcMoAmIOgwYiyltmGSpqoIOg7Xw0ItPVkBoxJzxjKCAiCMk6fZa4jKRV0/hYGMgAx6pXnlwxEyYzEMiWvw4xs67IBbrIv6egJhh3cQvhXbXcwFPMcDAejnu7ODGeGM6MyJWBBycuL23gz5rPrcDBqa62fPWrbsM+Z4cxorMJvg36/ig5PE0+Tt0oT/eqzejUaqYD3w3l7lnntecUYTiE9tr2Zp723hbd58GvY4YV+tWMhtysmsG4+9kuTsIlGdgbAAVaiX6DH1qy8VWvFGDZiMBjTidq8o+VKH0QTWzSuaVoEIfQZX9AU11gOApC3awBEsdvKFJb0A8MoGFJwOhjW3T4BhwI7mmPEiNI4vRvBXoNTF3TOslWUDyfXdHJ60QAjstawVY1lHb3AMNGHsMyAaCTvWoRwdqg9pg1GBrJjcNLTAPiQt4FhnO4DO2tsKuT3AkOcj44ER8POxTYY7TENMOBE03DWY5kIOxB1DkCINOSomrGOFRjTDwzeXJOUTE/P0jYrNlIc1IZF0GJxlTHSl2kKRkied6+HmpG2jYp80S1tBTNScc/1pGAE6+8NBg8Mx0xFGylca1I9j7HONvsbw8XxDAwKZyqaq8AwaWNkih0bgAHDpEKH6HP1zrVEFEUQ7ZgMAPrz2IahMl62cQUmFTYwMKXz6JuvNXT0BAPO8LOEABENBTtq19pjMhhFfpfbu6J8AAtZAkaoRwrEDjOyrevSLwatJxhlpH+v7w6GShkHw8Gop7czw5nhzHj9tiy5l9dR+xOue83wmlFnvzPDmeHM8LtJn7ug14xNa0aYyMlTf+n/ucychJpzgLIw2ZPmOlrzm6/ps+I/wba/bsJzoGpChWm4Ox7nPxwzs17pP3l4QrY+49SdAavPSn2mdZNypklRjEEJR0Q5M6CYnarNgZZtZryu/FHWp1g3idNsZ43pPTHaTL9VmMEsYQBtf8gpAMygp/YGeNtdN0l1ITuD75kBMgfapTic4KWCFf8BWDqdvzPQDJKdjQeYsMmAmmzltZNsc0cmy+67bmKcb0cQRmWQQmGUghquFTXHOBGMZafF0MgiaZcxtbZtrJt0clkMYcrHo0ROjGbHKmMAsgaoo6c2Nsn5uHWTmApMOYnyHh2OFf01gwJdhRlhPSOlVl4qCDVClh7qd5wuE9Hv9uPWTdig7jNDNCy167UNvh3nNQwBRsBItOY+miUmxwtWgUGqr2FhCALb4+sma3+L2NTuW0BNlDiPf5+j/zZRAXYwHIx6ajsznBl1ZvwPpyWx0WmY/AcAAAAASUVORK5CYII=" alt="image">
The same folder in v1.23.0 of the explorer sorts properly. It appears as though the units are Megabytes and not Mebibytes

**Comment by JasonYeMSFT** [comment]
I see the bug now. We are trying to parseInt from the number string including the units. A number string "1.4 MiB" will become 1 after parse int causing it to appear smaller than "8 B" whose parse result is 8.

**Comment by JasonYeMSFT** [comment]
We will switch to use a new implementation of File Explorer which will have this issue fixed.

**Comment by JasonYeMSFT** [comment]
This bug has been fixed in our 1.25.0 release.
