### ISSUE TITLE
An error info prompts when executing query in one emulator table if there is no queried clause

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5746]
**Storage Explorer Version:** 1.25.0-dev
**Build Number:** 20220519.1
**Branch:** main
**Platform/OS:** Windows 10
**Architecture:** ia32
**Azurite Version:** 3.17.1
**How Found:** Ad-hoc testing
**Regression From:** Previous release (1.21.3)

## Steps to Reproduce ##

1. Install and run Azurite 3.17.1 -> Launch Storage Explorer.
2. Expand 'Local & Attached -> Storage Accounts -> (Emulator - Default Ports) (Key)' -> Tables.
3. Create a table -> Click 'Query' -> Don't add any clause.
4. Execute query -> Check whether no error info prompts.

## Expected Experience ##
No error info prompts.

## Actual Experience ##
An error info prompts.
![image](https://user-images.githubusercontent.com/87792676/169265345-695cfd11-1b6b-4cba-a841-2261825c6e3b.png)

## Additional Context ##
Error details:
`{"odata.error":{"code":"InvalidInput","message":{"lang":"en-US","value":"The query condition specified in the request is invalid.\nRequestId:cdc2ba30-2551-4b29-879c-0cef7593b668\nTime:2022-05-19T09:48:51.915Z"}}}`

**Comment by v-kellyluo** [comment]
@craxal , 
In a new created table, there is no default query clause after clicking query if no entity is added, 
This issue also reproduces when executing query if removing all clauses.
Here is the record:
![tab](https://user-images.githubusercontent.com/87792676/169434509-b6342427-390a-4825-9515-9436f542c136.gif)

**Comment by craxal** [comment]
This appears to be a problem with the emulator and not Storage Explorer. I believe trying to run a query with no clauses is an edge case that not many users will run into. I will file a bug (https://github.com/Azure/Azurite/issues/1573), but I consider this a lower priority to get fixed.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20221226.3, there is always at least one cluse, so close this bug.
![image](https://user-images.githubusercontent.com/87792676/210033596-f0193fde-6cef-4f2b-90f9-3787ff53c32e.png)
