### ISSUE TITLE
Temporary tab doesn't become permanent if clicking 'Open' or double clicking

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5747]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220519.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.3 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: Ad-hoc testing
**Regression From**: Previous release (1.23.1)

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Click one blob container to open a temporary tab.
3. Right click the blob container -> Click 'Open'.
4. Check whether the temporary tab becomes permanent.

## Expected Experience ##
The temporary tab becomes permanent.

## Actual Experience ##
The temporary tab doesn't become permanent.

## Additional Context ##
This issue doesn't reproduce for regular blobs/file shares/queues/tables/disks.

**Comment by JasonYeMSFT** [comment]
Our panel API doesn't have a way to programmatically promote a temporary tab. We should add that.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20220624.2. Fixed. So close it.
