### ISSUE TITLE
an unhandled win32 exception occured in [96280] storageExplore.exe

### ISSUE THREAD

**Issue by SusheelKD** [microsoft/AzureStorageExplorer#5749]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.1

### Regression From

1.24.1

### Architecture

i86

### Storage Explorer Build Number

20220510.2

### Platform

Windows

### OS Version

windows Server 2019

### Bug Description

On the same Server two users are unable to access storage Explore at the same time. When one user opens storage explorer other user facing " unable to respond" with error an unhandled win32 exception occurred in [96280] storageExplore.exe.

### Steps to Reproduce

1. removed all files from Temp folder in the local.
2. Renamed .identityservice.
3. Renamed Storage Explorer in the Roaming profile.
4. Reinstalled the latest version of ASE.

### Actual Experience

On the same Server two users are unable to access storage Explore at the same time. When one user opens storage explorer other user facing " unable to respond" with error an unhandled win32 exception occurred in [96280] storageExplore.exe.

### Expected Experience

All users should be able to access Azure Storage explorer parallelly.

**Comment by MRayermannMSFT** [comment]
@SusheelKD do you know if Storage Explorer was installed for "all users" or "current user"?
