### ISSUE TITLE
version 1.4 does not launch on MAC OS 10.10.5

### ISSUE THREAD

**Issue by alex-miro** [Microsoft/AzureStorageExplorer#575]
**Storage Explorer Version**: 1.4
**Platform/OS Version**: OSX 10.10.5 (MacOS)
**Architecture**:
**Regression From**: 0.8

#### Steps to Reproduce: ####
1.  Upgraded to the latest (1.4.x) version on MacOS  10.10.5
2. the App refuses to launch - get a system error that the app is not compatible with my OS version

#### Expected Experience: ####
should be able to ran the app

#### Actual Experience: ####

the App refuses to launch - get a system error that the app is not compatible with my OS version
<img width="424" alt="screenshot 2018-08-13 11 13 48" src="https://user-images.githubusercontent.com/12189890/44049815-fe98bbc6-9ee9-11e8-8697-7d0dd302e22d.png">

**Comment by MRayermannMSFT** [comment]
Hi @alex-miro , starting with Storage Explorer 1.0.0, the minimum version of macOS supported is High Sierra (version 10.12). This is due to a dependency on .NET Core 2.0.
