### ISSUE TITLE
Copy Container does not copy version history

### ISSUE THREAD

**Issue by devsbryan** [microsoft/AzureStorageExplorer#5750]
We need to be able to copy a blob container from one account to another and retain the version history. 

However when using Copy Container only the latest version of each blob is copied.

The same applies to the Clone Container option.

**Comment by MRayermannMSFT** [comment]
@devsbryan this isn't possible today. Blob versions are created at the point in time the change is made to a blob. So we cannot copy the version later than that point of time and have the same version timestamp.
