### ISSUE TITLE
The localized string and the search icon overlap in the 'Search by prefix' field for one file share

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5752]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220520.5
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 18.04/MacOS Monterey 12.3 (Apple M1 Pro)
**Language**: Japanese
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '日本語' -> Restart Storage Explorer.
3. Expand one storage account -> File Shares.
4. Open one file share -> Observe the 'Search by prefix' field.
5.  Check the string and the search icon do not overlap.

## Expected Experience ##
The string and the search icon do not overlap.
The ENU screenshot:
![image](https://user-images.githubusercontent.com/41351993/169473801-b136e49d-5f03-4c05-af66-ab08a57e4f77.png)

## Actual Experience ##
The string and the search icon overlap.
![image](https://user-images.githubusercontent.com/41351993/169473432-68f5193d-85dd-4c2c-8cef-d00b593afe3d.png)

## Additional Context ##
This issue reproduces on Japanese (Verify this issue on all languages).

**Comment by craxal** [comment]
Fix has been merged.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20221017.1. Fixed.
![image](https://user-images.githubusercontent.com/87792676/196074647-5e11f19b-6dbc-4dc7-bba7-55e3919e5c8a.png)
