### ISSUE TITLE
The error message is not localized in the 'Open Container/File Share by Name' dialog when typing '/' to search

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5753]
**Storage Explorer Version:** 1.25.0-dev
**Build Number:** 20220520.5
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.3 (Apple M1 Pro)
**Architecture:** ia32\x64
**Language:** All languages
**How Found:** Ad-hoc testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '日本語' -> Restart Storage Explorer.
3. Expand one storage account -> Blob Containers.
4. Right click 'Blob Containers' node -> Click 'Open Container by Name...'.
5. Type '/' in the Container name field -> Click 'Search'.
6. There is an error message -> Check whether the error message is localized.

## Expected Experience ##
The error message is localized.

## Actual Experience ##
The error message is not localized.
![image](https://user-images.githubusercontent.com/87792676/169479285-0d1fd44e-9dad-475e-bb90-7f3b06c24540.png)

**Comment by craxal** [comment]
@v-kellyluo This message comes from the service, so we can't localize it.
