### ISSUE TITLE
There is an extra scroll bar in the localized 'Shared Access Signature' dialog for one file share/queue 

### ISSUE THREAD

**Issue by v-sunnysun** [microsoft/AzureStorageExplorer#5754]
**Storage Explorer Version:** 1.25.0-dev
**Build Number:** 20220520.5
**Branch:** main
**Platform/OS:** Windows 10
**Architecture**: ia32
**Language**: Japanese
**How Found:** From running test cases
**Regression From:** Previous release (1.24.1)

## Steps to Reproduce ##

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '日本語' -> Restart Storage Explorer.
3. Expand one storage account -> File Shares.
4. Right click one file share -> Click 'Get Shared Access Signature...'.
5. Check there is no extra scroll bar in the popped up dialog.

## Expected Experience ##
There is no extra scroll bar in the popped up dialog.

## Actual Experience ##
There is an extra scroll bar in the popped up dialog.
![image](https://user-images.githubusercontent.com/98519664/169480154-374a4432-b50d-4392-8278-a465134603da.png)

## Additional Context ##
This issue doesn't reproduce on Mac & Linux.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220613.1. Fixed.
