### ISSUE TITLE
Investigate if our File Share folder stats may report inaccurate results

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#5755]
This comes from a customer support thread. It seems in some situations, our folder statistics feature may report inaccurate results. 

For example, when there are 192388 files in the folder and 144,573,325,353 bytes in total, our statistics report only 192271 files and 144,301,875,878 bytes in total.

We should try to reproduce it and see if there is a bug in our code.

**Comment by MRayermannMSFT** [comment]
We investigated manually and found no issues. I have also added an initial automated test to help verify the correctness of the file share statistics.
