### ISSUE TITLE
The QA attached storage account disappears after clicking 'Refresh All'  if detaching the storage account 

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5756]
**Storage Explorer Version:** 1.25.0-dev
**Build Number:** 20220523.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.3 (Apple M1 Pro)
**Architecture:** ia32\x64
**How Found:** From running test cases
**Regression From:** Previous release (1.24.1)

## Steps to Reproduce ##

1. Select one storage account -> Attach the storage account.
2. Add the attached storage account to Quick Access.
3. Detach the storage account -> Click 'Refresh All'.
4. Check whether the QA storage account displays as broken.

## Expected Experience ##
The QA storage account displays as broken.

## Actual Experience ##
The QA storage account disappears.

## Additional Context ##
This issue doesn't reproduce for services.

**Comment by MRayermannMSFT** [comment]
Accidentally pushed a commit to main.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220524.5. Fixed.
