### ISSUE TITLE
Error while connecting Azure account from Azure storage Explorer

### ISSUE THREAD

**Issue by sumanathenahealth** [microsoft/AzureStorageExplorer#5759]
{
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"tunneling socket could not be established, cause=self signed certificate\\\",\\n  \\\"stack\\\": \\\"Error: tunneling socket could not be established, cause=self signed certificate\\\\n    at ClientRequest.onError (C:\\\\\\\\Users\\\\\\\\Administrator\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\tunnel-agent\\\\\\\\index.js:177:17)\\\\n    at Object.onceWrapper (node:events:510:26)\\\\n    at ClientRequest.emit (node:events:390:28)\\\\n    at TLSSocket.socketErrorListener (node:_http_client:447:9)\\\\n    at TLSSocket.emit (node:events:390:28)\\\\n    at emitErrorNT (node:internal/streams/destroy:157:8)\\\\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\\\\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)\\\",\\n  \\\"code\\\": \\\"ECONNRESET\\\"\\n}\""
}
Please take this a priority and suggest the fix accordingly

**Comment by MRayermannMSFT** [comment]
@sumanathenahealth can you give using system proxy setting a try? You can read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue we recommend opening a support ticket via the Azure Portal. Alternatively you can open a new issue here.
