### ISSUE TITLE
A11y_Azure Tools Storage Explorer_Signing into Azure Storage_Toggle Explorer Pane - Tree View_ScreenReader: When the voiceover focus lands on one of the 'Storage Accounts' such as 'locals and attached', the user has to press 'Control + Option + Space' two successive times to expand.

### ISSUE THREAD

**Issue by bbarik06** [microsoft/AzureStorageExplorer#5761]
**GitHubTags:** #A11yMAS;#A11yTCS;#A11ySev2;#BM_AzureToolsStorageExplorer_May2022;#Azure Tools Storage Explorer;#MAC;#FTP;#DesktopApp;#WCAG4.2.9;#Voiceover;#AINotInScope;#External:VoiceOver;#A11ycaioh;#Closed;

## Environment Details:
Application Name: Azure Tools Storage Explorer 
Application Version: 1.24.0
Mac Version: macOS Monterey 12.3.1
Screen Reader: Voiceover

## Repro Steps:
1. Please do not close this bug. This bug should only be closed by TCS, C+AI Accessibility tester after verification of the fix.
2. Launch Azure Tools Storage Explorer.
3. Sign in to Azure.
4. Tab to 'Explorer' pane tree view.
5. Tab to any of the 'Storage Accounts' such as 'Locals and attached'.
6. Turn on voiceover and try to expand.

## Actual:
When the voiceover focus lands on one of the 'Storage Accounts' such as 'locals and attached', the user has to press 'Control + Option + Space' two successive times to expand.

## Expected:
When the voiceover focus lands on one of the 'Storage Accounts' such as 'locals and attached', the user should press 'Control + Option + Space' 1 times to expand.

## User Impact:
Screen reader users will face difficulty if they have to use multiple keyboard strokes to activate the control. It is not recommended.

## Attachment:
![3_AML V1](https://user-images.githubusercontent.com/98393966/169966318-e8dfaa43-9d54-4d8c-9bfa-a0a306a1ccff.gif)

**Comment by bbarik06** [comment]
@MRayermannMSFT, Here the issue is with screen reader and not with the normal keyboard usage. It works fine for a normal keyboard user and not for the screen reader user.

**Comment by craxal** [comment]
I've been able to reproduce this issue on a relatively simple `tree` in an HTML file running in Edge. The problem seems to crop up once I introduce the `aria-expanded` attributes. That is, VoiceOver only starts saying "0 items enclosed" when `aria-expanded` is defined. Otherwise VoiceOver says nothing about the number of child items.

However, I'm pretty darn sure we're implementing the tree correctly. NVDA, for reference, seems to get the number of child items right just fine.

```html
<ul role="tree">
  <li role="treeitem" aria-expanded="true">
    <div>Item 1</div>
    <ul role="group">
      <li role="treeitem" aria-expanded="true">
        <div>Item 2</div>
        <ul role="group">
          <li role="treeitem" aria-expanded="false">
            <div>Item 3</div>
          </li>
          <li role="treeitem">
            <div>Item 4</div>
          </li>
        </ul>
      </li>
      <li role="treeitem">
        <div>Item 5</div>
      </li>
    </ul>
  </li>
  <li role="treeitem">
    <div>Item 5</div>
  </li>
</ul>
```

I'll take this to accessibility hours just to make sure we're doing this right.

**Comment by craxal** [comment]
I'm not entirely sure why this is happening. But since the user only needs to press Spacebar to expand/collapse, I'll take this to offices hours to check whether we need to do anything.

**Comment by craxal** [comment]
Spoke with Ryan Shugart and Scott O'Hara at Accessibility office hours. This is due to the fact that Apple and VoiceOver don't support tree semantics; trees simply don't exist in Apple systems.  Therefore, there's nothing we can do to fix this.

**Comment by bbarik06** [comment]
Closing this bug as per above comment received.
