### ISSUE TITLE
A11y_Azure Tools Storage Explorer_Get Shared Access Signature_Keyboard: When the user closes the 'Calendar' control using keyboard 'esc' key, the dialog 'Shared access signature' closes automatically.

### ISSUE THREAD

**Issue by bbarik06** [microsoft/AzureStorageExplorer#5763]
**GitHubTags:** #A11yMAS;#A11yTCS;#A11ySev2;#BM_AzureToolsStorageExplorer_May2022;#Azure Tools Storage Explorer;#MAC;#FTP;#DesktopApp;#WCAG2.1.1;#Keyboard;#AINotInScope;#closed;

## Environment Details:
Application Name: Azure Tools Storage Explorer 
Application Version: 1.24.0
Mac Version: macOS Monterey 12.3.1

## Repro Steps:
1. Please do not close this bug. This bug should only be closed by TCS, C+AI Accessibility tester after verification of the fix.
2. Launch Azure Tools Storage Explorer.
3. Sign in to Azure.
4. Tab to 'Explorer' pane tree view.
5. Navigate to any of the file inside "Blob Containers"
6. Right click on any of the file and select 'Get shared access signature'.
7. Tab till 'Calendar' inside 'Start Time'
8. Use keyboard to access and close it.

## Actual:
When the user closes the 'Calendar' control using keyboard 'esc' key, the dialog 'Shared access signature' closes automatically.

### Same issue can be observed for the following scenario:

1. Manage Access Policies_Add (When the calendar is closed using 'esc' key, 'Access Policies' dialog closes automatically)

## Expected:
When the user closes the 'Calendar' control using keyboard 'esc' key, the dialog 'Shared access signature' should not get closed and focus should return back to the control that triggered it.

## User Impact:
Keyboard users will face difficulty in interacting if the controls such as dialog box gets closed forcefully due to interaction with other controls inside it.

## Attachment:
![9_CalendarWhenClosed](https://user-images.githubusercontent.com/98393966/169968796-c934d828-10b1-4d20-bbfd-e8d4ba6f85a2.gif)

**Comment by MRayermannMSFT** [comment]
Maybe related? https://bugs.chromium.org/p/chromium/issues/detail?id=980751

**Comment by craxal** [comment]
I posted a new Chromium issue, as I was able to repro this on a standard webpage.

https://bugs.chromium.org/p/chromium/issues/detail?id=1335590

**Comment by MRayermannMSFT** [comment]
Hi @bbarik06

Please verify that this bug is fixed using the Storage Explorer build at: https://storageexplorerpublish.blob.core.windows.net/privatebuilds/20220624.3-accessibility-testing/StorageExplorer-darwin-x64.zip
