### ISSUE TITLE
Changing Public Access Level through the side bar on a blob container does not change the access level

### ISSUE THREAD

**Issue by evolutionise** [Microsoft/AzureStorageExplorer#577]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows 10 - Version 10.0.17134 Build 17134

**Architecture**: ia32
**Regression From**: Before 1.4.0

#### Steps to Reproduce: ####
1. Not sure when this started, as it initially worked on this version. 
1.1 Using Local storage.
2. Create a container with at least two subfolders, one of which is written to by a function. 
3. Set the container access level to `Public read access for container and blobs` by right clicking on the container in the side menu and using the `Set Container Public Access Level` dialog.
4. Select `Apply`.
5. See `Container access permissions successfully changed` message in the Activities tab. 
6. Open the `Set Container Public Access Level` option from the side menu again. 
7. See that the access level has not changed.

#### Expected Experience: ####
I would expect to see that the public access level had changed. 
~I would also expect that when my application, running locally, would be able to access blobs in that container.~

#### Actual Experience: ####
When I reopen the Access Levels menu, the change I made is not applied and the container would not show `No public access`.
~I would also expect that my application would successfully read a blob and would not throw a `Blob does not exist` error.~ (this might've been due to something else, can't repro the failure to change access level to verify)

**Comment by evolutionise** [comment]
The workaround is pretty easy - restart the Storage Explorer fixes it :)

**Comment by MRayermannMSFT** [comment]
I think all you had to do was refresh the node. Once the change is complete, we ask the server (or in this case your emulator) for the policy. I could see there being a short race condition where we're asking for it a little too quickly. So if you refresh, that will once again get the policy. Glad you found a work around though. :)
