### ISSUE TITLE
The option 'Navigate to Container' displays in the 'Open Direct Link' dialog when opening the container's direct link if there is only its SAS attachment

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5773]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220524.5
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.3 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> SAS attach the blob container.
3. Right click the blob container -> Click 'Copy Direct Link to Blob Container'.
4. Open the direct link -> Observe the 'Open Direct Link' dialog.
5. Check whether there is an 'Attach Container' option.

## Expected Experience ##
There is an 'Attach Container' option.
![image](https://user-images.githubusercontent.com/41351993/169984417-85fe7775-e247-4842-9023-ef920124f8d6.png)

## Actual Experience ##
1. There is an 'Navigate to Container' option.
2. The SAS attached blob container is selected and opened.
![image](https://user-images.githubusercontent.com/41351993/169983931-c873ca88-d806-4fc7-bc99-ce0a63baf63f.png)

**Comment by MRayermannMSFT** [comment]
@v-xianya can you explain why you expect what you expect?

**Comment by v-xianya** [comment]
@MRayermannMSFT 
Hi Matthew, if there is no attachment for blob containers. Select to 'Attach Container' in 'Open Direct Link' dialog will create an Azure AD attachment. So, I guess it only navigates to Azure AD attachment. 😐

**Comment by MRayermannMSFT** [comment]
@v-xianya, ah ok. Ya for now it will recognize an existing attachment of any type. I can see how your thinking makes sense tho.
