### ISSUE TITLE
No Subscription Found after Successful Sign-In

### ISSUE THREAD

**Issue by mrw3050** [Microsoft/AzureStorageExplorer#5777]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.1

### Regression From

I don't Know

### Architecture

x64

### Storage Explorer Build Number

20220510.2

### Platform

Windows

### OS Version

Windows 10

### Bug Description

After successfully adding account associated with my azure subscription, I get a message in the Account Management tab underneath the "Microsoft account (home tenant)" dropdown that says "No subscription found". 

### Steps to Reproduce

1. Lauch Azure Storage Explorer
2. Click add account, add subscription
3. Login successful
4. "No subscription found" underneath account in account management tab

### Actual Experience

I am able to log in, but my active subscription is not found. I've tried to remove and re-add account several times, but my active subscription does not show up and I get a "Subscription not found" message. I am able to see the active subscription in my azure portal, but not in the Microsoft Azure Storage Explorer.

### Expected Experience

I expect my subscription to show after successfully logging in with my azure account. I also hope to see the subscription in the explorer tab, so I can access a storage account in the subscription.

**Comment by MRayermannMSFT** [comment]
@mrw3050 do you have any other tenants listed? They would be at the same logical level as the "Microsoft account (home tenant)". If so, is it possible your subscription is in one of those tenants? If so, please click on the checkboxes for those tenants.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue we recommend opening a support ticket from the Azure portal. Alternatively you can open a new issue here.

**Comment by demitry** [comment]
Thank you Matthew, It works, I clicked on the checkbox for the tenant at the same logical level.

**Comment by sisoje** [comment]
i also have this bug

**Comment by LemonyCell** [comment]
This workaround can be helpful - https://learn.microsoft.com/en-us/answers/questions/1121467/azure-storage-explorer-not-connecting-to-free-acco#:~:text=Go%20to%20Accounts%20tab.%20Click%20on%20settings%20icon%20next%20to%20Default%20Directory.%20Click%20Un%2Dfilter

**Comment by yanghoxom** [comment]
> This workaround can be helpful - https://learn.microsoft.com/en-us/answers/questions/1121467/azure-storage-explorer-not-connecting-to-free-acco#:~:text=Go%20to%20Accounts%20tab.%20Click%20on%20settings%20icon%20next%20to%20Default%20Directory.%20Click%20Un%2Dfilter

you save my life
