### ISSUE TITLE
How to build storage explorer extensions

### ISSUE THREAD

**Issue by NephorLabs** [microsoft/AzureStorageExplorer#5782]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I want to build a custom extension for Azure Storage Explorer

### Desired Solution

Point me to documentation as i could not find it anywhere

**Comment by MRayermannMSFT** [comment]
@NephorLabs can you tell us more about what you'd like to build?

Right now, extensibility is more limited than people seem to expect. So it would be helpful for us to know what you want to do.

**Comment by MRayermannMSFT** [comment]
@NephorLabs ?

**Comment by MRayermannMSFT** [comment]
@NephorLabs ?
