### ISSUE TITLE
unable to access storage explorer

### ISSUE THREAD

**Issue by sekarjntu** [microsoft/AzureStorageExplorer#5788]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.2

### Architecture

i86

### Platform

Windows

### Bug Description

{
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"getaddrinfo ENOTFOUND management.azure.com\\\",\\n  \\\"stack\\\": \\\"Error: getaddrinfo ENOTFOUND management.azure.com\\\\n    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)\\\\n    at __node_internal_ (node:internal/errors:686:10)\\\\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)\\\",\\n  \\\"errno\\\": -3008,\\n  \\\"code\\\": \\\"ENOTFOUND\\\",\\n  \\\"syscall\\\": \\\"getaddrinfo\\\",\\n  \\\"hostname\\\": \\\"management.azure.com\\\"\\n}\""
}

### Steps to Reproduce

1.launch storage explorer
2. login to your account

### Actual Experience

getting err
{
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"getaddrinfo ENOTFOUND management.azure.com\\\",\\n  \\\"stack\\\": \\\"Error: getaddrinfo ENOTFOUND management.azure.com\\\\n    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)\\\\n    at __node_internal_ (node:internal/errors:686:10)\\\\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)\\\",\\n  \\\"errno\\\": -3008,\\n  \\\"code\\\": \\\"ENOTFOUND\\\",\\n  \\\"syscall\\\": \\\"getaddrinfo\\\",\\n  \\\"hostname\\\": \\\"management.azure.com\\\"\\n}\""
}

**Comment by sekarjntu** [comment]
when i click on reauthenticate going to below link and no page found coming
http://[localhost](http://localhost:54071/?code=0.AREAsoGr54Qe90udy7b-wB7ROJV3sATbjRpGu-4C-eG_e0YRAI0.AgABAAIAAAD--DLA3VO7QrddgJg7WevrAgDs_wQA9P9oHB_LwhXvrzQJpSP6HUt8dU2PP319WEFgFbc9-SCvtxJiViEBkaItWiKHZqe-L2TvAswWgRz6gVkUSqxDahVNgZbQzc0EhRNs4MXBKgDcj4zvnOp-WXwhxxX6j1WVdG7h2dm0kNpCVn735wEpN_GhFWhbst3j13I4xS1tFiEqS5Z3lkJQPseolWaAPfQFcu7oqrgYwPGAp5E588CYcjN56p_2qhVtyHb2uRzedD_YieFKt2-XccjhS4qa__6-LIerJ9sBlfBxB3AT2M_SfEVHMvgju6BteatvFGFVerMRi3uFbm98x869JF8akHfJPOwYllWPd5kWCTxN4n2EBbvF6rKrvTGEON_7J12ntAkh7s0ul4ZNhrprao4Ec79LYGHaAaljCt-sQhNF1-XAjJpwj6SlVkIwOHyeVXLKhXE5qyhhlmaHZLH6FiwdPecRShkha1GyfMOgZX1PrvecwGmgMpNnz-MLub81po5289uYaTRJ-32Vs6cFzz1_jCinY3XUBxlOhjcy2e2X46ojsO6IuBM7ZcNKmxeKD0MVcvUp_AcDjfmT6CgcnihSvNcPooSShbbmwmhszkl0h-JV96OJkVmD614OFt8SYQpAnkkXysJcpGlf5HvNAKIR8_3cWH266wQ_ASabaNazdlhsDV-TJ5yE9_LD_BtOmOBv5MfUzT4KgsDeCrhoU4S5zhngkhgfMkgS5mxuYraU5EaWWU5iI6K9JTtUu0_d7BPtLJcbdbF7s4aPM5TTu6Fhrw3WIB6hhtrw7FJ0mN5CDsYxPT1g12IH5CJS-b0PYvwVNeq1H8RRLUWJ6632DSY15NwASDlTQS1B88EJLj68LQYNMmAx6THJalJmr6qjmCRcXaqHskpMdymeKiulU4L6BQ4wvDPXuPTcS5-CBNOsTKop4ub8ifw_y16ZQwtTvGcyTL22GE33J6hSCcD4dG3ZvF_V07ZDjKwSZZEyZGijxzkBOAv2Dc8gxP2ByN4NgKwyTAeqNoIWR6Q&state=dc48ffc1-b7ed-4639-9e44-33dbb3a9b8c17a27cf15-d787-4961-8056-7c43c1f8e341&session_state=c68bdeac-d573-4506-be86-8be1a47364b4):54071/?code=0.AREAsoGr54Qe90udy7b-wB7ROJV3sATbjRpGu-4C-eG_e0YRAI0.AgABAAIAAAD--DLA3VO7QrddgJg7WevrAgDs_wQA9P9oHB_LwhXvrzQJpSP6HUt8dU2PP319WEFgFbc9-SCvtxJiViEBkaItWiKHZqe-L2TvAswWgRz6gVkUSqxDahVNgZbQzc0EhRNs4MXBKgDcj4zvnOp-WXwhxxX6j1WVdG7h2dm0kNpCVn735wEpN_GhFWhbst3j13I4xS1tFiEqS5Z3lkJQPseolWaAPfQFcu7oqrgYwPGAp5E588CYcjN56p_2qhVtyHb2uRzedD_YieFKt2-XccjhS4qa__6-LIerJ9sBlfBxB3AT2M_SfEVHMvgju6BteatvFGFVerMRi3uFbm98x869JF8akHfJPOwYllWPd5kWCTxN4n2EBbvF6rKrvTGEON_7J12ntAkh7s0ul4ZNhrprao4Ec79LYGHaAaljCt-sQhNF1-XAjJpwj6SlVkIwOHyeVXLKhXE5qyhhlmaHZLH6FiwdPecRShkha1GyfMOgZX1PrvecwGmgMpNnz-MLub81po5289uYaTRJ-32Vs6cFzz1_jCinY3XUBxlOhjcy2e2X46ojsO6IuBM7ZcNKmxeKD0MVcvUp_AcDjfmT6CgcnihSvNcPooSShbbmwmhszkl0h-JV96OJkVmD614OFt8SYQpAnkkXysJcpGlf5HvNAKIR8_3cWH266wQ_ASabaNazdlhsDV-TJ5yE9_LD_BtOmOBv5MfUzT4KgsDeCrhoU4S5zhngkhgfMkgS5mxuYraU5EaWWU5iI6K9JTtUu0_d7BPtLJcbdbF7s4aPM5TTu6Fhrw3WIB6hhtrw7FJ0mN5CDsYxPT1g12IH5CJS-b0PYvwVNeq1H8RRLUWJ6632DSY15NwASDlTQS1B88EJLj68LQYNMmAx6THJalJmr6qjmCRcXaqHskpMdymeKiulU4L6BQ4wvDPXuPTcS5-CBNOsTKop4ub8ifw_y16ZQwtTvGcyTL22GE33J6hSCcD4dG3ZvF_V07ZDjKwSZZEyZGijxzkBOAv2Dc8gxP2ByN4NgKwyTAeqNoIWR6Q&state=dc48ffc1-b7ed-4639-9e44-33dbb3a9b8c17a27cf15-d787-4961-8056-7c43c1f8e341&session_state=c68bdeac-d573-4506-be86-8be1a47364b4

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue we recommend opening a support ticket via the Azure Portal. Alternatively you can open a new issue here.

**Comment by peixotto** [comment]
If still on time, it worked to me:
**Settings** (gear icon on the left vertical toolbar) > **Application** > **Proxy** > **Proxy configuration** > Change the drop down from 'Do not use proxy' to '**Use system proxy** (preview)'
