### ISSUE TITLE
Error loading property within a Korean Resource Group.

### ISSUE THREAD

**Issue by synsun** [microsoft/AzureStorageExplorer#5789]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.2

### Regression From

1.21.3

### Architecture

x64

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Storage account that with Korean named properties cannot read the values.

That account can show only "Account name, type, subscription, resource group, Location".

The others show as "Error loading property".

There are no error logs.

The other account with English Resource group shows well.

### Steps to Reproduce

1. Make resource group as Korean.
2. Make Storage account within above group.
3. Launch 1.24.2 version Storage Explorer.
4. Click that storage account on explorer.
5. Check Properties.

### Actual Experience

Valuese are shown as "Error loading property".

Leftside arrow(>) is gone.

### Expected Experience

Show values well.

Can click Leftside arrow and show "Blob Containers, File shares..."

**Comment by MRayermannMSFT** [comment]
@synsun yes this is an issue that another user raised with us via another channel. There is an issue with RGs that have unicode characters in their names. For now you should rollback to 1.23: https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.23.1

**Comment by MRayermannMSFT** [comment]
@synsun we're going to end up shipping a 3rd hotfix of 1.24. Included in it is a fix for this issue. If you have a moment, could you let us know if this release candidate resolves the issue for you?

https://storageexplorerpublish.blob.core.windows.net/privatebuilds/1.24.3-rc.2/StorageExplorer-ia32.exe

Please note that since this is a release candidate, we do not recommend using it with production data beyond verifying the bug. In general, please try to limit usage of the release candidate to just verifying the fix. Thanks!

**Comment by MRayermannMSFT** [comment]
@synssun we've shipped the hotfix. Please install from here (even if you've installed the release candidate build): https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.24.3

If you still see your issue with that, then please open a new issue.
