### ISSUE TITLE
Unable to Sign In to Account That Redirects to Organisation's Login Page

### ISSUE THREAD

**Issue by ishimmings** [microsoft/AzureStorageExplorer#579]
1.4.0: 
Windows 10: 
ia32: 

#### Steps to Reproduce: ####
1. Click on Add Account
2. In dialog click on Sign in...
3. On Sign In dialog, enter a valid account that will redirect to your organisation's login page and click Next

#### Expected Experience: ####
My organisation's browser based login page appears where I enter my organisation username and password then click Next and I am logged in.

#### Actual Experience: ####
The browser based login page appears with "401 - Unauthorized: Access is denied due to invalid credentials." title and "You do not have permission to view this directory or page using the credentials that you supplied." content. Note, this process works when logging in to other systems, including the organisation's email, the Azure portal, secure endpoints via Swagger or Postman, etc.

**Comment by MRayermannMSFT** [comment]
@ishimmings , are you behind a proxy?

**Comment by maartenhbe** [comment]
Currently experiencing the same issue with version 1.6.1 on Windows 10.

The issues seems to pop-up when we are required to change our AD-password and we are already signed in using an AD-account. We already tried clearing certain cache files (.adalcache, .devaccounts, .extaccounts), removing saved passwords via IE, rebooting after clearing data, etc. but nothing seems to work. For some users the issue resolves itself after a while and they can login in ASE again but for others it doesn't. Issue occurs when connected directly without proxy, via VPN, via office network...

My guess is that the logic should ask to re-enter your password if it gets a 401 (similar to RDP). Feel free to contact me for details.

**Comment by nbfowler** [comment]
I experience the exact same issue using version 1.6.1 on MacOS 10.12.6. I have tried doing every possible thing in the troubleshooting guide (removing cache files .adalcache, .devaccounts, .extaccounts; clearing the directory ~/.IdentityService, removing the directory ~/Library/Application Support/StorageExplorer, removing Storage Explorer entries from keychain, etc.) and nothing works. I always get a 401 error. I am not using a proxy.
 
![screen shot 2019-01-08 at 4 24 39 pm](https://user-images.githubusercontent.com/245593/50868145-04849a80-1363-11e9-945e-1e84ee0dc71a.png)

**Comment by MRayermannMSFT** [comment]
If you're still encountering this issue, please try using MSAL (Settings -> Application -> Sign-in -> Use Microsoft Authentication Library MSAL). If you're still encountering issues with that, then please open a new issue. Thanks!
