### ISSUE TITLE
Fail to launch Storage Explorer by using tar.gz

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5791]
**Storage Explorer Version:** 1.25.0-dev
**Build Number:** 20220531.1
**Branch:** main
**Platform/OS:** Linux Ubuntu 20.04
**Architecture:** x64
**How Found:** From running test case
**Regression From:** Previous release (1.24.2)

## Steps to reproduce ##

1. Open a clean Linux machine with OS version Ubuntu 20.04.
2. Download Linux build as tar.gz file then extract it.
3. Open terminal -> Navigate to where the Storage Explorer executable is located.
4. Open Storage Explorer by running './StorageExplorer'.
5. Check whether succeeds to launch Storage Explorer.

## Expect Experience ##
Succeed to launch Storage Explorer.

## Actual Experience ##

1. Fail to launch Storage Explorer.
2. An error reminder dialog pops up, it prompts to install .NET 6.

![image](https://user-images.githubusercontent.com/87792676/171124109-4906adac-948d-4211-808c-2a023902715b.png)

## Additional Context ##

1. Fail to install .NET 6 on terminal.
2. The error dialog still pops up after installing .NET 3.1.

**Comment by MRayermannMSFT** [comment]
@v-kellyluo how did you try to install .net 6?

**Comment by v-kellyluo** [comment]
@MRayermannMSFT , 

I tried to install .net 6 by the below commands:
```
wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb;
sudo dpkg -i packages-microsoft-prod.deb;
sudo apt-get update;
sudo apt-get install -y apt-transport-https &&
sudo apt-get update &&
sudo apt-get install -y dotnet-runtime-6
```
The running result is as below:
![image](https://user-images.githubusercontent.com/87792676/171309999-ab1e6af3-ad16-4434-987a-602c871409ab.png)

**Comment by MRayermannMSFT** [comment]
@v-kellyluo can you try `sudo apt-get install -y dotnet-runtime-6.0` instead? I believe you need the `.0` at the end:
<img width="902" alt="image" src="https://user-images.githubusercontent.com/21112697/171474676-c67c5ad8-f127-401b-af4e-9650b1d5aac5.png">

**Comment by v-kellyluo** [comment]
@MRayermannMSFT , Thank you for the updates, .NET 6 is installed successfully after using` sudo apt-get install -y dotnet-runtime-6.0`, and succeed to launch Storage Explorer.
