### ISSUE TITLE
I can't open the File Shares

### ISSUE THREAD

**Issue by AKEA46** [microsoft/AzureStorageExplorer#5794]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [x] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [x] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.2

### Architecture

x64

### Storage Explorer Build Number

20220527.5

### Platform

Windows

### OS Version

Windows 11

### Bug Description

When trying to open the connected File Shares, i get the following error message: 

Untergeordnete Ressourcen können nicht abgerufen werden.

Details:
{
  "name": "TypeError",
  "message": "Cannot read properties of undefined (reading 'version')",
  "stack": "TypeError: Cannot read properties of undefined (reading 'version')\n    at isConnectionV1 (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:75273)\n    at Function.getAttachedFileShareNode (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:63843)\n    at C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:62775\n    at Array.map (<anonymous>)\n    at Function.produceAttachedFileShareNodes (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:62745)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Object.Azure.Storage.FileShareProducer.produceAttachedFileShareNodes (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:82303)\n    at async Provider.executeOperation (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\providers\\Provider.js:28:16)\n    at async NodeProcessHostProxy._handleExecuteRequest (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:226:31)\n    at async NodeProcessHostProxy._handleMessage (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:179:24)"
}

### Steps to Reproduce

1. Launch Storage Explorer
2. Expand File Shares Node

### Actual Experience

Error message appears

**Comment by JasonYeMSFT** [comment]
@AKEA46 Could you try the steps in this section to see you can re-add the potentially corrupted custom connection?https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#error-occurred-while-adding-new-connection-typeerror-cannot-read-property-version-of-undefined

**Comment by AKEA46** [comment]
Thank you. This fixed the issue!
