### ISSUE TITLE
Update `macos-keychain` dependencies in AzCopy packages

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#5795]
Attempting to install Storage Explorer packages without legacy peer dependencies results in a dependency conflict. AzCopy has a peer dependency on `@storage-explorer/macos-keychain@2.0.0`, but Storage Explorer provides 3.0.0, which does not satisfy the dependency. AzCopy packages should be updated so that they have a dependency on at least `@storage-explorer/macos-keychain@^3.0.0` to resolve this conflict.

**Comment by JasonYeMSFT** [comment]
The work has been done by Craig.
