### ISSUE TITLE
Unable to retrieve child resources, unable to get local issuer certificate on windows 10 

### ISSUE THREAD

**Issue by juliensmiths** [microsoft/AzureStorageExplorer#5796]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.1

### Regression From

first use, for architecture it is ia32 

### Architecture

x64

### Storage Explorer Build Number

20220510.2

### Platform

Windows

### OS Version

WINDOWS 10

### Bug Description

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://sdfrenchcustoms.file.core.windows.net/?sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2023-05-23T20:44:22Z&st=2022-05-23T12:44:22Z&spr=https&SAS Token Redacted&comp=list failed, reason: unable to get local issuer certificate",
  "stack": "FetchError: request to https://sdfrenchcustoms.file.core.windows.net/?sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2023-05-23T20:44:22Z&st=2022-05-23T12:44:22Z&spr=https&SAS Token Redacted&comp=list failed, reason: unable to get local issuer certificate\n    at ClientRequest.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:111224)\n    at ClientRequest.emit (node:events:390:28)\n    at TLSSocket.socketErrorListener (node:_http_client:447:9)\n    at TLSSocket.emit (node:events:390:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY",
  "code": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"

### Steps to Reproduce

1 LAUNCH STORAGE EXPLORER
2 BE CONNECTED TO FILE SHARE DIRECTORY

### Actual Experience

I GET THE ERROR MESSAGE COPIED ABOVE

### Expected Experience

NA

### Additional Context

NA

**Comment by MRayermannMSFT** [comment]
Can y'all give using system proxy setting a try? You can read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue, we recommend opening a support ticket via the Azure Portal. Alternatively, you can open a new issue here.
