### ISSUE TITLE
Auto snapshot files when replacing a file via UI

### ISSUE THREAD

**Issue by rollsch** [microsoft/AzureStorageExplorer#5797]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Drag and drop a file to azure which replaces the existing file prompts to replace the file with no prompt to snapshot. Snapshots have to be done manually.

### Desired Solution

It would save a lot of time if the replace file prompt had a checkbox that says "Create snapshot".

Eg like below.

![image](https://user-images.githubusercontent.com/1109554/172290135-e1e462f3-6fdd-439a-a621-577bc6bbe70b.png)

### Alternatives and Workarounds

Manually right clicking, create snapshot. However when copying 20+ files this is very time consuming and tedious.

**Comment by JasonYeMSFT** [comment]
@rollsch There is a service feature called blob versioning you might be interested in. Mutations to your blobs will automatically create blob versions, which you can later access as backup data. https://docs.microsoft.com/en-us/azure/storage/blobs/versioning-overview. I believe using of blob versioning would be easier than manually managing the snapshots.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue, we recommend opening a support ticket via the Azure Portal. Alternatively, you can open a new issue here.
