### ISSUE TITLE
The attached service tab is not auto opened when attaching one service if the (Attached Containers) node is not expanded

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5798]
**Storage Explorer Version:** 1.25.0-dev
**Build Number:** 20220607.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture:** ia32\x64
**How Found:** From running test cases
**Regression From:** Previous release (1.24.2)

## Steps to Reproduce ##

1. Launch Storage Explorer. 
2. Make sure the (Attached Containers) node is not expanded.
3. Expand one storage account -> Blob Containers.
4. Create a blob container -> Attach the blob container.
5. Check whether the attached blob container tab is auto opened.

## Expected Experience ##
The attached blob container tab is auto opened.

## Actual Experience ##
The attached blob container tab is not auto opened.

## Additional Context ##

1. This issue also reproduces for file shares/queues/tables.
2. Here is the record:
![blob](https://user-images.githubusercontent.com/87792676/172326834-aedc901e-a4c8-46c2-af28-a9181c62e2f3.gif)

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220609.2. Fixed.
