### ISSUE TITLE
There is an extra scrollbar if clicking the link 'Learn more about access tiers' on the 'Clone and Rehydrate' dialog with an error message for 'Destination blob container' field

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5799]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220607.2
**Branch**: main
**Platform/OS**: Windows 10
**Architecture** ia32
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob -> Change the access tier to 'Archive'.
3. Right click the blob -> Click 'Clone and Rehydrate...'.
4. Type a valid name to 'Destination blob name' field-> Empty 'Destination blob container' field -> Press 'Enter'.
5. There is an error message -> Click the link 'Learn more about access tiers'.
6. Check there is no extra scrollbar.

## Expected Experience ##
There is no extra scrollbar.

## Actual Experience ##
There is an extra scrollbar.

## Additional Context ##
1. The scrollbar disappears after clicking the empty place in the dialog.
2. Here is the record:
![06072](https://user-images.githubusercontent.com/41351993/172335207-d5533a52-89b0-4438-bef4-97b9d66656b4.gif)

**Comment by JasonYeMSFT** [comment]
The extra space taken by the border on the link causes the scrollbar to show up.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20220725.1. This issue doesn't reproduce. So we are going to close it.
![image](https://user-images.githubusercontent.com/41351993/180750562-46219778-5ccc-4608-8777-22c38dbcd0ed.png)
