### ISSUE TITLE
Error Uploading SQL Server Database backup file to Azure Storage Account using Storage Explorer

### ISSUE THREAD

**Issue by agarwalarvind** [Microsoft/AzureStorageExplorer#58]
{
  "name": "StorageError",
  "message": "The specified blob or block content is invalid.\nRequestId:1738d0a0-201e-00e3-214e-d96ddf000000\nTime:2018-04-21T08:56:19.6862009Z",
  "stack": "Error\n    at Function.StorageServiceClient._normalizeError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:1189:23)\n    at Object.StorageServiceClient._processResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:736:50)\n    at Request.processResponseCallback [as _callback] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:311:37)\n    at Request.self.callback (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\node_modules\\request\\request.js:188:22)\n    at emitTwo (events.js:125:13)\n    at Request.emit (events.js:213:7)\n    at Request.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\node_modules\\request\\request.js:1171:10)\n    at emitOne (events.js:115:13)\n    at Request.emit (events.js:210:7)\n    at IncomingMessage.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\node_modules\\request\\request.js:1091:12)",
  "code": "InvalidBlobOrBlock",
  "statusCode": 400,
  "requestId": "1738d0a0-201e-00e3-214e-d96ddf000000"
}

**Comment by JakeRadMSFT** [comment]
@XiaoningLiu Could you help us investigate this issue?

**Comment by agarwalarvind** [comment]
Sure, what do you need from me?

**Comment by JakeRadMSFT** [comment]
@agarwalarvind Could you provide an example file without any private/personal data in it?

**Comment by agarwalarvind** [comment]
Sorry, unfortunately can’t do that – because that’s a MS sql server backup file from production and contains lot of customer documents. I have been able to successfully restore that backup so am sure that the file itself is not corrupt.

 

Had similar problem with 3 more files but they uploaded OK since version 1.0.0 of storage explorer has come out.

 

If it helps, it contains lot of documents (PDFs, Word doc etc) in one table field as binary data. Have uploaded few thousand of such files without any problem. Most files are in the range of 300 GB each.

**Comment by agarwalarvind** [comment]
FYI, have also tried uploading via AzCopy but that fails too.

**Comment by craxal** [comment]
Out of curiosity, what's the tier of the blob container/account you're trying to upload to (premium, hot, cold, archive)? I assume you're trying to upload as a block blob?

**Comment by agarwalarvind** [comment]
It's StorageV2 (general purpose v2)
Access Tier - Cool
Block Blob

**Comment by XiaoningLiu** [comment]
I cannot search detailed log for 1738d0a0-201e-00e3-214e-d96ddf000000, maybe it's too old. Any other failure requestIDs?

Seems AzCopy has similar issues, how about other tools or SDKs? Such as using Azure CLI 2.0 (based on Python) for a test.

**Comment by agarwalarvind** [comment]
Here is the latest message when I tried again


{
  "name": "StorageError",
  "message": "The specified blob or block content is invalid.\nRequestId:5bd440d9-601e-00cd-6372-dced18000000\nTime:2018-04-25T08:53:57.5491238Z",
  "stack": "Error\n    at Function.StorageServiceClient._normalizeError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:1189:23)\n    at Object.StorageServiceClient._processResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:736:50)\n    at Request.processResponseCallback [as _callback] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:311:37)\n    at Request.self.callback (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\node_modules\\request\\request.js:188:22)\n    at emitTwo (events.js:125:13)\n    at Request.emit (events.js:213:7)\n    at Request.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\node_modules\\request\\request.js:1171:10)\n    at emitOne (events.js:115:13)\n    at Request.emit (events.js:210:7)\n    at IncomingMessage.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\node_modules\\request\\request.js:1091:12)",
  "code": "InvalidBlobOrBlock",
  "statusCode": 400,
  "requestId": "5bd440d9-601e-00cd-6372-dced18000000"
}

**Comment by agarwalarvind** [comment]
So this means the container already has some information about the file and based upon that it's reporting that BlockId legth of BlockList does not match!!! 

I am uploading now to a different SA and it seems to be uploading on that. 

What do I need to do in terms of cleanup (if any) so that it'll upload to desired SA/Container?

**Comment by JakeRadMSFT** [comment]
@XiaoningLiu Is this something we can try clean up in a "filter"?

**Comment by XiaoningLiu** [comment]
@agarwalarvind @JakeRadMSFT 

There is maybe a `uncommited` blob previous partial uploaded with different block ID length. We can check this blob by calling `ListBlob` with `include='uncommittedblobs'`.

To delete this blob, just call 'deleteBlob' to delete this `uncommited` blob.

**Comment by MRayermannMSFT** [comment]
Hey @agarwalarvind , sorry this issue got stale! We're going to go ahead and close it, but please feel free to comment if you're still having issues and we can try @XiaoningLiu 's work around.
