### ISSUE TITLE
Show resources for these subscriptions acting funny

### ISSUE THREAD

**Issue by spottedmahn** [Microsoft/AzureStorageExplorer#580]
**Storage Explorer Version**:

![image](https://user-images.githubusercontent.com/14079228/44097284-6573f588-9fab-11e8-8aeb-4e4ee60bd47a.png)

#### Steps to Reproduce: ####
When signed in w/ my personal and business account that have the same email address the storage explorer is acting really weird.

I'm not sure how to reproduce it, sorry.  I'm happy to provide any details you need to track it down though!

#### Expected Experience: ####
That I can sign-in w/ both accounts and it works 😊

#### Actual Experience: ####
When I first opened the app today:

![image](https://user-images.githubusercontent.com/14079228/44097460-d097c27c-9fab-11e8-927e-0e28f11c71d4.png)

I removed the top one

![image](https://user-images.githubusercontent.com/14079228/44097483-de8c8188-9fab-11e8-8b2a-d7ed376b2373.png)

I clicked on `add an account` and signed in w/ my business account

![image](https://user-images.githubusercontent.com/14079228/44097533-f98ef646-9fab-11e8-83e5-54f234adbc9d.png)

Clicked Apply and went back

![image](https://user-images.githubusercontent.com/14079228/44097568-0d1c4eb6-9fac-11e8-9dbb-6a54169c2c4a.png)

Clicked apply

![image](https://user-images.githubusercontent.com/14079228/44097581-14893894-9fac-11e8-9e83-fc25e122d57b.png)

**Comment by spottedmahn** [comment]
Thanks @MRayermannMSFT!

Let me know how I can help.

I just poked around and found the Chrome dev tools...

I went back into my accounts and clicked apply

![image](https://user-images.githubusercontent.com/14079228/44104659-6cf87b50-9fbd-11e8-8126-bf1e4c57db36.png)

I see this error

![image](https://user-images.githubusercontent.com/14079228/44104638-57a7a2f8-9fbd-11e8-84fc-cc5b7bf6ba6f.png)

**Comment by spottedmahn** [comment]
here's more of the call stack if that helps:

![image](https://user-images.githubusercontent.com/14079228/44104736-9a163744-9fbd-11e8-859d-3af77ffb315c.png)

**Comment by spottedmahn** [comment]
![image](https://user-images.githubusercontent.com/14079228/44104855-f118f450-9fbd-11e8-95c1-01fcad3bf070.png)

**Comment by MRayermannMSFT** [comment]
I have a patch I'd like you to try out if you are willing. 

1. Download the attached .zip
2. Unzip it
3. Paste the file in the zip at `C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\UserAccountManagement` (your path may differ if you installed in a non default location)

[IdentityUserAccountsManager.zip](https://github.com/Microsoft/AzureStorageExplorer/files/2287743/IdentityUserAccountsManager.zip)

**Comment by spottedmahn** [comment]
Success 😊

![image](https://user-images.githubusercontent.com/14079228/44105139-bd27dad4-9fbe-11e8-8c7e-ccae8d619b0a.png)

**Comment by spottedmahn** [comment]
Man, this "new" Microsoft is awesome!!!  👏👏👏

How long would this have taken to get fixed in the old days?!

**Comment by MRayermannMSFT** [comment]
Probably too long. 😋 We'll include this fix in our next major release. Thanks for verifying!
