### ISSUE TITLE
The azure account expires if deleting the environment custom whose associated account is the same with the azure account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5800]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220607.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer.
2. Open the connect dialog -> Click 'Subscription' -> Select 'Azure' -> Click 'Next'.
4. Sign in one account.
5. Open the connect dialog -> Click 'Subscription' -> Select 'Custom Environment' -> Select one custom environment -> Click 'Next'.
6. Sign in the same account in step3.
7. Delete the custom environment used in the step5.
8. Click 'Open Explorer' -> Switch to the ACCOUNT MANAGEMENT panel.
9. Check the state of the account signed-in via Azure.

## Expected Experience ##
The account displays normal.

## Actual Experience ##
The account expires with the error detail 'No matching account found in MSAL cache'.

## Additional Context ##
1. This issue reproduces regardless of using 'Default Web Browser/Integrated Sign-in'.
2. In the previous releases, the account disappears.
3. Here is the record:
![0607](https://user-images.githubusercontent.com/41351993/172329382-66a26f20-18df-4929-9d5c-e04abdb656e7.gif)

**Comment by MRayermannMSFT** [comment]
@v-xianya I am unable to repro this. Can you please:

- Set your Storage Explorer log level env var to debug
- Enable the "Verbose Authentication Logging" setting

And then share your Storage Explorer and ServiceHub logs with me via Teams?

Thanks.

**Comment by v-xianya** [comment]
@MRayermannMSFT Got it.

**Comment by MRayermannMSFT** [comment]
@v-xianya did you send me those? I couldn't find them when I tried looking this morning. Perhaps they've been lost to teams scrolling history.

Could you try to repro this on latest main, and if it still repros then send me the logs again? Both authentication and Storage Explorer logs. Please make sure to set Storage Explorer log level to `debug` and enable verbose authentication logging. Personally I am still unable to repro. Tried 3 times this morning.

**Comment by v-xianya** [comment]
@MRayermannMSFT I reproduced this issue on the latest main build 20220815.1 and sent the log on teams.

**Comment by MRayermannMSFT** [comment]
Closing this as won't fix. This behavior is a result of the fact that within the MSAL cache, these are the same accounts. Identity team does not see this behavior being worth changing.
