### ISSUE TITLE
The editor can't be refreshed if using 'Ctrl+R' to refresh the table editor

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5804]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220608.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: From running test cases
**Regression From**: Previous release (1.24.2)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Open one table -> Press 'Ctrl+R'.
3. Check whether the editor is refreshed.

## Expected Experience ##
The editor is refreshed.

## Actual Experience ##
The editor is not refreshed.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220613.1. Fixed.

**Comment by v-xianya** [comment]
@craxal This issue reproduces on the build main/20220630.8. So we are going to re-open it.

**Comment by craxal** [comment]
@v-xianya When you made the temporary tab permanent, was focus actually in the table explorer? When I tabbed into the explorer, Ctrl+R worked just fine.

@MRayermannMSFT Is focus supposed to go into the panel when clicking on the "Keep Open" button in the tab?

**Comment by v-xianya** [comment]
@craxal The tab is focused if making the temporary tab permanent. If switching the focus to table explorer, 'Ctrl+R' works well. we are going to close it.
