### ISSUE TITLE
There is no border for the Timestamp's value field under Query builder

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5805]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220608.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: From running test cases
**Regression From**: Previous release (1.24.2)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Open one table -> Click 'Query'.
3. Click 'Add new clause' -> Switch the Field to 'Timestamp'.
4. Check whether there is a border for the Value field.

## Expected Experience ##
There is a border for the Value field.
![image](https://user-images.githubusercontent.com/41351993/172548872-bcd4b541-7db5-4abc-9577-c72448b4eb6d.png)

## Actual Experience ##
There is no border for the Value field.
![image](https://user-images.githubusercontent.com/41351993/172549076-3ab61a7d-ab30-45b6-a7d1-d5ee7c85d1bc.png)

**Comment by v-xianya** [comment]
Verified this issue on the build main/202206154. Reproduce.

**Comment by craxal** [comment]
The change is in a new package version which has not been integrated into Storage Explorer yet.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220620.1. Fixed.
