### ISSUE TITLE
Top of table explorer is cut off when opening query builder after refresh

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5806]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220608.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: From running test cases
**Regression From**: Previous release (1.24.2)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Import the [test.csv](https://github.com/microsoft/AzureStorageExplorer/files/8858786/test.csv) file (contains 25 entities) to the table.
3. Click 'Refresh' -> Click 'Query'.
4. Check whether the layout is friendly.

## Expected Experience ##
The layout is friendly.

## Actual Experience ##
The layout is unfriendly.
![image](https://user-images.githubusercontent.com/41351993/172545644-a5a90652-bcfe-440f-85df-1c6f09b68c25.png)

## Additional Context ##
1. This issue reproduces if there is no empty space for the table editor.
![image](https://user-images.githubusercontent.com/41351993/172545867-e6f888d9-3303-4f7e-8905-dc97a2ceef7c.png)
2. Here is the record:
![06081](https://user-images.githubusercontent.com/41351993/172545944-d43ef72d-40b7-44b8-ba08-44a80fc63fb5.gif)

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220622.1. Fixed. So close it.

**Comment by craxal** [comment]
This is a known issue related to the height calculations made for the table when a layout occurs. We're not sure what causes this yet. We added a small delay to the redraw to mitigate most occurrences of this issue. Does resizing the panel or window resolve the issue?

**Comment by v-xianya** [comment]
@craxal Verified this issue on the build 20220913.2. This issue can be resolved by resizing the panel.

**Comment by craxal** [comment]
We're currently working on a re-haul of the table explorer using React. Considering the complexity of the explorer as of now, and that the issue has an easy workaround, we may wait for the re-hauled explorer to be finished in order to resolve this issue.

**Comment by craxal** [comment]
React version of the explorer will take some time. We are currently investigating a quicker fix for the current Knockout/jQuery version that we could potentially provide for 1.27.0.

**Comment by OzBob** [comment]
workaround: resize('click and shake back and forth) the left hand explorer pane, until the right side top menu reappears. ugly but works.

**Comment by JasonYeMSFT** [comment]
I am going to make a stylesheet update to mitigate this issue.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20221025.2. Fixed. So, we are going to close it.

**Comment by OzBob** [comment]
@v-xianya i'm not sure this is fixed, i've just upgraded(v1.27.0 build 20221201.1) and am getting total banner dissapears in Queues
![image](https://user-images.githubusercontent.com/1796771/206600766-d57799f2-c870-4231-a359-b5a97ac7c768.png)

**Comment by v-xianya** [comment]
Hi @OzBob , yes, this issue is fixed, and it is about the table explorer.

I am not able to reproduce the queue issue you met on the (v1.27.0 build 20221201.1). Are there any extra steps for this issue to reproduce? thanks

**Comment by JasonYeMSFT** [comment]
@OzBob The original issue was for Table explorer. We haven't done anything in Queue explorer for this type of problem. If you have additional information on how to repro it, please open a new issue and we can investigate.
