### ISSUE TITLE
The table tab is not auto closed when deleting one table

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5807]
**Storage Explorer Version:** 1.25.0-dev
**Build Number:** 20220608.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture:** ia32\x64
**How Found:** From running test cases
**Regression From:** Previous release (1.24.2)

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create one table -> A table tab is opened.
3. Delete the table -> Check whether the table tab is auto closed.

## Expected Experience ##
The table tab is auto closed.

## Actual Experience ##
The table tab is not auto closed.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220620.1. Fixed.
