### ISSUE TITLE
No warning 'At least one column should be selected' displays in the 'Column Options' dialog when no column is selected

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5809]
**Storage Explorer Version:** 1.25.0-dev
**Build Number:** 20220608.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture:** ia32\x64
**How Found:** From running test cases
**Regression From:** Previous release (1.24.2)

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create a table -> Click 'Column Options' -> Uncheck all available columns.
3. Check whether a warning 'At least one column should be selected' displays.

## Expected Experience ##
A warning 'At least one column should be selected' displays.
![image](https://user-images.githubusercontent.com/87792676/172551542-1c089e31-b061-40c3-8664-2baa4dcfc940.png)

## Actual Experience ##
No warning 'At least one column should be selected' displays.
![image](https://user-images.githubusercontent.com/87792676/172551682-7534843f-c9de-469a-a7b3-c6fef3dc1d4d.png)

**Comment by craxal** [comment]
I forgot to put the alert piece back in. 🤦

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220616.8. Fixed.
