### ISSUE TITLE
Clear Queue Button Is Disabled When all Messages are hidden

### ISSUE THREAD

**Issue by hdesouky** [Microsoft/AzureStorageExplorer#581]
**Storage Explorer Version**: 1.3.0
**Platform/OS Version**: Windows 10
**Architecture**: 64 bit
**Regression From**: No

#### Steps to Reproduce: ####
1. Expand Azure Storage Queue Node
2. Select one of the queue with messages but all hidden
3. Try to clear the queue, the clear button is disabled however the queue has messages but hidden

#### Expected Experience: ####
Clear queue button should be enabled if the queue has all its messages hidden and no visible messages

#### Actual Experience: ####
Clear queue button is disabled when the queue has no visible messages and all messages are invisible

**Comment by MRayermannMSFT** [comment]
I just checked 1.3.1 and 1.4.0, and on both, clear queue is always enabled. Can I get a screenshot showing a disabled queue button with the about window? Something like this?
![image](https://user-images.githubusercontent.com/21112697/44158123-e4c5a080-a068-11e8-8ce9-1d264a57e038.png)

**Comment by MRayermannMSFT** [comment]
@hdesouky or @darshanrampatel ?

**Comment by darshanrampatel** [comment]
I've been unable to replicate this since I last posted so it is fine from my point of view.

**Comment by MRayermannMSFT** [comment]
Mmmk. I'm going to go ahead and close this. If someone does see clear queue not enabled, please let us know.

**Comment by hdesouky** [comment]
Sorry for late reply, my bad.

I confirm it was and update issue. 

Thanks for your attention and follow up
