### ISSUE TITLE
The table explorer is always loading when the value of the 'Show top results' field is less than the number of all entities

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5811]
**Storage Explorer Version:** 1.25.0-dev
**Build Number:** 20220608.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture:** ia32\x64
**How Found:** From running test cases
**Regression From:** Previous release (1.24.2)

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create a table -> Add at least two entities.
3. Click 'Query' -> Remove all clauses.
4. Type '1' into the 'Show top results' field -> Execute query.
5. Check whether there is an entity.

## Expected Experience ##
There is an entity.

## Actual Experience ##
The table explorer is always loading.
![image](https://user-images.githubusercontent.com/87792676/172554916-93e8a1f6-129a-40a9-89b1-aee5e41e0af5.png)

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220620.1. Fixed.
