### ISSUE TITLE
An error dialog pops up when detaching one broken Azure AD attached table whose associated account is removed

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5813]
**Storage Explorer Version:** 1.25.0-dev
**Build Number:** 20220608.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture:** ia32\x64
**How Found:** Ad-hoc testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create a table -> Azure AD attach the table.
3. Switch to 'ACCOUNT MANAGEMENT' panel -> Remove the associated account.
4. The Azure AD attached table displays as broken.
5. Right click the broken table -> Click 'Detach -> Yes'.
6. Check whether no error dialog pops up.

## Expected Experience ##
No error dialog pops up.

## Actual Experience ##
An error dialog pops up.
![image](https://user-images.githubusercontent.com/87792676/172552948-26b3cc32-b232-45bd-b229-15e3683d3a78.png)

## Additional Context ##

1. This issue doesn't reproduce for blob containers/queues.
2. After closing the error dialog, the broken table still displays, it disappears after manually refreshing.
3. In 1.24.2 version, this issue consistently reproduces when detaching the table if no table tab is opened.

**Comment by craxal** [comment]
@v-kellyluo Does this still reproduce for you in newer builds? I'm not able to reproduce.

**Comment by v-kellyluo** [comment]
This issue doesn't reproduce on the latest build main/20220630.8. So close it.
