### ISSUE TITLE
An error dialog pops up when clicking 'Detach' for one attached file share

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5814]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220608.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: From running test cases
**Regression From**: Previous release (1.24.2)

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share then right click it -> Click 'Get Shared Access Signature...'.
3. Click 'Create' -> Copy the URL -> Close the 'Get Shared Access Signature' dialog.
4. Open the connect dialog -> Click 'File share' -> Paste the copied URL to the 'File share SAS URL' field.
5. Click 'Next' -> Click 'Connect'.
7. Switch to the attached file share -> Right click it -> Click 'Detach'.
8. Check whether a prompt dialog pops up.

## Expected Experience ##
A prompt dialog pops up.

## Actual Experience ##
An error dialog pops up.
![image](https://user-images.githubusercontent.com/41351993/172571942-0e723c39-e21a-416a-8038-7f723a28b4e4.png)

## Additional Context ##
1. This issue reproduces when using SAS URL created by an access policy.
2. This issue doesn't reproduce for blob containers/queues/tables.

**Comment by JasonYeMSFT** [comment]
I have switched to use a new provider for detaching File Share connections. This bug should have been fixed by that.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220609.2. Fixed. So close it.
