### ISSUE TITLE
Nothing happens when pressing F5 to execute query in one table

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5815]
**Storage Explorer Version:** 1.25.0-dev
**Build Number:** 20220608.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture:** ia32\x64
**How Found:** From running test cases
**Regression From:** Previous release (1.24.2)

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create a table -> Add some entities.
3. Click 'Query' -> Press F5.
4. Check whether succeeds to execute query.

## Expected Experience ##
Succeed to execute query.

## Actual Experience ##
Nothing happens.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220613.1. Fixed.
