### ISSUE TITLE
The context menu of the node '(Emulator - Default Ports) (Key)' is incorrect

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5816]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220608.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: From running test cases
**Regression From**: Previous release (1.24.2)

## Steps to Reproduce ##
1. Expand 'Local & Attached' -> Storage Accounts.
2. Right click '(Emulator - Default Ports) (Key)'.
3. Check whether the context menu is correct.

## Expected Experience ##
The context menu is correct.
![image](https://user-images.githubusercontent.com/41351993/172588260-ba651130-92ae-4ba5-a46d-04695660bf2a.png)

## Actual Experience ##
The context menu is incorrect.
![image](https://user-images.githubusercontent.com/41351993/172588188-782ec968-b5ab-44c2-b5db-6d8ce24a9815.png)

**Comment by v-xianya** [comment]
@MRayermannMSFT Hi Matthew, Verified this issue on the build main/20220609.2.
There are two extra actions on the node context menu. So re-open this issue.
![image](https://user-images.githubusercontent.com/41351993/172746862-d18f2e99-be80-487b-b55f-cb2f64e22350.png)

**Comment by MRayermannMSFT** [comment]
My apologies Kristine, I meant to leave a comment here yesterday. I tested those to actions against the node and they both seem to work. If your testing shows the same, I don't see any reason for us not to show those actions here. I'm going to close this issue, but if you see any problems with those actions agains the emulator node, please feel free to reopen this issue or open a new issue to share your findings.

**Comment by v-xianya** [comment]
@MRayermannMSFT There is no error when clicking 'Get Shared Access Signature... & Copy Primary Key'.
If trying to SAS attach the "devstoreaccount", Fail to expand its service node with errors.
Here is the screenshot when expanding Blob Containers.
![image](https://user-images.githubusercontent.com/41351993/173043406-3c8c5a08-2f4a-4a65-9d8b-a8afa84183a1.png)
