### ISSUE TITLE
Can't download Big File from Blob

### ISSUE THREAD

**Issue by flixius** [microsoft/AzureStorageExplorer#582]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows 10 
**Architecture**: ia32
**Regression From**: I don't know

#### Steps to Reproduce: ####
I have a 13,6 GB File on my Azure Blob. The Blob Container has "No public access" as access Level. 
After i clicked "download" in the AzStorageExplorer the download starts as expected. 
After ~10-20% progress the download stops with the following exception message:
```
{
  "name": "Error",
  "message": "getaddrinfo ENOTFOUND myBlobAddress.blob.core.windows.net myBlobAddress.blob.core.windows.net:443",
  "stack": "Error: getaddrinfo ENOTFOUND myBlobAddress.blob.core.windows.net myBlobAddress.blob.core.windows.net:443\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
  "code": "ENOTFOUND",
  "errno": "ENOTFOUND",
  "syscall": "getaddrinfo",
  "hostname": "myBlobAddress.blob.core.windows.net",
  "host": "myBlobAddress.blob.core.windows.net",
  "port": "443",
  "innerError": {
    "code": "ECONNRESET",
    "errno": "ECONNRESET",
    "syscall": "read"
  }
}
```
The file i want to download is an AzureSQL database backup. The file was created from the azure portal under "SqlDb -> Export database"

#### Expected Experience: ####
The download will not be completed.

#### Actual Experience: ####
The download will not be completed.

Additional question: Is there another way to download a File (without writing an own application) from my Blob without using the MS AzureStorageExplorer? 

Thank you for your help!

**Comment by MRayermannMSFT** [comment]
Hey @flixius . The error you are seeing seems to a network connectivity issue. How reliably does this repro for you? Also, if you need this file urgently, there are two other methods we recommend for downloads and uploads:

- [AzCopy](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy), your best bet for big files.
- Use the Azure Portal, not the best for big files, but might work.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
