### ISSUE TITLE
The file share snapshot doesn't auto display when creating a snapshot under the snapshots view

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5823]
**Storage Explorer Version:** 1.25.0-dev
**Build Number:** 20220609.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture:** ia32\x64
**How Found:** From running test cases
**Regression From:** Previous release (1.24.2)

## Steps to Reproduce ##

1. Expand one storage account -> File Shares.
2. Create a file share -> Click 'View Share Snapshots'.
3. Right click the file share -> Click 'Create Snapshot'.
4. Check whether the snapshot auto displays.

## Expected Experience ##
The snapshot auto displays.

## Actual Experience ##
The snapshot doesn't auto display.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220610.4. Fixed. So close it.
