### ISSUE TITLE
Not able to expand blob container in storage explorer

### ISSUE THREAD

**Issue by A30007165** [microsoft/AzureStorageExplorer#5825]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.2

### Regression From

1.18.0

### Architecture

x64

### Platform

Windows

### Bug Description

Not able to expand blob container

### Steps to Reproduce

Not able to expand blob container

### Actual Experience

Not able to expand blob container
![image](https://user-images.githubusercontent.com/78339428/172828217-1983301d-7c75-4c57-ab41-2292901b26dc.png)

**Comment by A30007165** [comment]
Please fix it asap

**Comment by jinglouMSFT** [comment]
Have you tried any suggestions in here:  https://docs.microsoft.com/en-us/azure/storage/common/storage-network-security?tabs=azure-portal? Thanks.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue, we recommend opening a support ticket via the Azure Portal. Alternatively, you can open a new issue here.
