### ISSUE TITLE
When uploading a complete drive, driveletter is created as directory incl. colon as %3A

### ISSUE THREAD

**Issue by TTWill** [microsoft/AzureStorageExplorer#5826]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.2

### Architecture

x64

### Storage Explorer Build Number

20220527.5

### Platform

Windows

### OS Version

Windows 11, x64, 21H2

### Bug Description

When uploading a complete drive, driveletter is created as directory incl. colon as %3A, so uploading and selecting drive Z:\, the directory Z%3A is created. Furthermore the issue is aggrevated by
1. The dissability to move the containing folders outside the malformed folder
2. The inability to access the folder from a SMB device
3. The lack of support to delete the folder, unless in a powershell using the --force flag (because of files/folders copied with the readonly attribute set)

### Steps to Reproduce

1. Launch storage explorer
2. Find a suitable storageaccount and fileshare
3. Upload and select the drive root, for example an USB drive
4. Refresh the files pane

### Actual Experience

Follow the described steps and remember to select the whole drive as source. When uploading is finished, refresh the pane and nottice a folder is created named by the driveletter concatenated with "%3A".

### Expected Experience

The files and folders are copied to the destination folder without creating a "drive folder", but rather as it would work from within Windows Explorer when copying contents from one drive to another.
Or, create an error to prevent the user from creating a malformed file path.

**Comment by MRayermannMSFT** [comment]
@TTWill if you want the behavior you are expecting, then you should go into File Explorer, go into the drive you are working with, select all, and then drag and drop that into Storage Explorer. Alternatively, you can use Storage Explorer's upload dialog, and when selecting files & folders, go into the drive you are working with, select all and then click "Open" in the file picker.

**Comment by TTWill** [comment]
Sure, thanks for the hints, but I am not looking for a work-around, I'm doing a service to report an obvious issue. The fact is more serious, that you leave a folder with an inconsistent name "Z%3A" (in itself an encoding bug), making it very impractical to correct the error since the folder is invisible from SMB and neither Storage Explorer nor Azure portal allows renaming/moving the folder - an operation that seems to work flawlessly using SMB. Had the folder been named "Z", the mistake would be much more easy to fix, but the former naming hides the folder from SMB.

**Comment by MRayermannMSFT** [comment]
@TTWill I just tried this all out for myself. Here's what I found:
1. Yes, the ":" is encoded to "%3A". This has to happen because the drive is turned into a folder with a name like "C:", but ":" is not a valid character for file share folders.
2. Storage Explorer can see the resulting uploaded folder.
3. Storage Explorer can clone the folder to have a different name (just not "C:").

I am having a hard time testing what is seen over SMB though as I'm having port issues with my ISP. But given that Storage Explorer can clone the folder, I think we're going to close this unless you have something else to add. Thanks for raising it to our attention though.

**Comment by TTWill** [comment]
Sure, you can close the folder - although that is kind of hard if you copied 3 TB data to a folder, which you cannot clone, because the capacity limit is 4 TB. But let's close it at that, although I see a bright future for someone keen on bringing in some competition here.
