### ISSUE TITLE
Enhance Folder statistics functionality

### ISSUE THREAD

**Issue by jasonhorner** [microsoft/AzureStorageExplorer#5828]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I want to quickly assess the size of my folders

### Desired Solution

when executing the folder statistics command the size of the folders should be updated in the U/I. also you should be a able to select a single child folder to run folder statistics on

### Alternatives and Workarounds

you can navigate into the child folder

### Additional Context
I would expect that running folder statistics would update the relevant sizes for the sibling folders. also when I select a single folder the statistics operation should just calculate for the that folder and all sub folders not the siblings as it currently does.

![image](https://user-images.githubusercontent.com/7981510/172916035-b5729563-76e7-4b24-af0a-20581feb8667.png)

**Comment by jasonhorner** [comment]
@MRayermannMSFT I think this can be closed as completed.. the feature is awesome: 
![image](https://github.com/microsoft/AzureStorageExplorer/assets/7981510/499631bf-001e-4df3-a7bd-1310dd5a118c)
Many thanks!!! it sparks joy every time I use it.

**Comment by MRayermannMSFT** [comment]
> @MRayermannMSFT I think this can be closed as completed.. the feature is awesome: ![image](https://user-images.githubusercontent.com/7981510/283967606-499631bf-001e-4df3-a7bd-1310dd5a118c.png) Many thanks!!! it sparks joy every time I use it.

Ok, if you are happy, I'm happy.
