### ISSUE TITLE
Cannot login in 1.X versions of storage explorer

### ISSUE THREAD

**Issue by JoranDox** [Microsoft/AzureStorageExplorer#583]
**Storage Explorer Version**: 1.4
**Platform/OS Version**: apparently I can't copy from the about dialog any more either (also worked in 0.9) so here it is:
![image](https://user-images.githubusercontent.com/7152733/44197087-fd53ba80-a13d-11e8-999d-27cd3c74fdde.png)

**Architecture**: see above
**Regression From**: 0.9.6, broken since any later updates (tried 1.0, 1.1, 1.2, 1.3, 1.4, worked on 0.9)

#### Steps to Reproduce: ####
1. open storage explorer
2. get the prompt to log in in some way "Connect to Azure Storage"
1. "add an azure account" -> [sign in]
1. fill in my email (redirecting me to my company's login)
1. fill in my password
1. get the authenticator pop-up on my phone and press approve

#### Expected Experience: ####
I shortly see "Waiting for authentication..." end then I get access to the subscriptions connected to my account, and the storage accounts and blobs under those subscriptions (this is also what happens when I need to re-enter my password in 0.9).

#### Actual Experience: ####
It keeps spinning on "Waiting for authentication...", presumably until some timeout happens, after which I go back to an empty storage explorer.

**Comment by JoranDox** [comment]
I've checked issues #579 and #578 but they don't seem to be real duplicates, and I'm not behind a proxy.
It seems to be a duplicate from #434 but unlike there I actually see an error in the console after I press F12:
error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
error @ Debug.js:39
Debug.js:39 Unexpected end of JSON input
error @ Debug.js:39

and in the waiting for authentication box after pressing F12:
Uncaught (in promise) Object (followed by what I believe is a standard empty js object)

**Comment by JoranDox** [comment]
Running it from console shows no actual errors, same 
```
...
Received message 'dialog-execute-operation'
Received message 'did-execute-operation'
Received message 'dialog-execute-operation'
Received message 'did-execute-operation'
Received message 'did-get-dialog-result'
Received message 'closed'
```
 as in 434.

**Comment by mcqueene** [comment]
![image](https://user-images.githubusercontent.com/30414128/44211159-f8870a80-a12d-11e8-8d22-11256398ea9d.png)
I have seen the same issue since Aug 15 2018. Hitting F12 I also see the "Unexpected end of JSON input" error.

**Comment by craxal** [comment]
The key here is the "bad decrypt" error. This is related to #535. We encountered the problem when generating new encryption keys when one isn't found. I experienced this exact same problem when trying to sign in. We have a fix for this coming very soon.

@JoranDox, @mcqueene, if you like, can you follow the suggestions in #535 to see if the "Microsoft_StorageExplorer" key is present?

**Comment by craxal** [comment]
@JoranDox, you said you're still having issues. Are you still getting the "bad decrypt" error? Have you verified that you have a "Microsoft_StorageExplorer" key in your credentials store?

**Comment by JoranDox** [comment]
in the pop-up: still the uncaught (in promise):
![image](https://user-images.githubusercontent.com/7152733/45340486-12820480-b597-11e8-906a-e286dc02557a.png)

in the main window: still the bad decrypt:
![image](https://user-images.githubusercontent.com/7152733/45340543-49f0b100-b597-11e8-984b-7a21dffb34e3.png)

I have the key:
