### ISSUE TITLE
It would be better to keep order of the dropdown actions of 'Upload' button same between the new and old file share explorers

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5831]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220610.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: From running test cases
**Regression From**: Previous release (1.24.2)

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Click 'Upload'.
3. Observe the dropdown actions -> Check the order is the same as in the old explorer.

## Expected Experience ##
The order is the same as in the old explorer.
![image](https://user-images.githubusercontent.com/41351993/173014451-479bd3eb-3c96-477c-b5fa-f86e9ba8c325.png)

## Actual Experience ##
The order is not the same as in the old explorer.
![image](https://user-images.githubusercontent.com/41351993/173014491-a787379f-42f1-422b-ba6e-0d7a331be84a.png)

**Comment by JasonYeMSFT** [comment]
Hmmm. I always thought file is above folder so I did that without looking at the old code. I'll revert that.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220613.1. Reproduce. Will verify on the newer build.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220614.2. Fixed. so close it.
