### ISSUE TITLE
The file still displays in the explorer when using a mismatched prefix to search in one file share

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5832]
**Storage Explorer Version:** 1.25.0-dev
**Build Number:** 20220610.4
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture:** ia32\x64
**How Found:** From running test cases
**Regression From:** Previous release (1.24.2)

## Steps to Reproduce ##

1. Expand one storage account -> File Shares.
2. Create a file share -> Create a folder -> Open the new created folder -> Upload a file.
3. Type a character which is different from the first character of the file name to 'Search by prefix (case-insensitive)' box.
4. Check whether the filter string displays in the address bar and no file displays in the explorer.

## Expected Experience ##

1. The filter string displays in the address bar.
2. No file displays in the explorer.
![image](https://user-images.githubusercontent.com/87792676/173040649-56d78f72-2549-4ee9-bb77-69efa4056f75.png)

## Actual Experience ##
1. The filter string doesn't display in the address bar.
2. The file still displays in the explorer.
![image](https://user-images.githubusercontent.com/87792676/173041992-e96ed8f8-250d-4c69-afbe-6c39103ea883.png)

## Additional Context ##

1. This issue reproduces consistently when firstly executing search.
2. This issue cannot be reproduced consistently if emptying the character then typing it again.
3. Here is the record:
![onefile](https://user-images.githubusercontent.com/87792676/173042208-0b967159-63b4-4a59-82f3-9e5656797505.gif)

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220613.1. Reproduce. Will verify it on the newer build.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220614.2. Fixed. So close it.
