### ISSUE TITLE
Upload fails with UnexpectedCancel error

### ISSUE THREAD

**Issue by huyaoyu** [microsoft/AzureStorageExplorer#5835]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.2

### Architecture

x64

### Storage Explorer Build Number

20220527.5

### Platform

Windows

### OS Version

Windows 10 Education 21H2 build 19044.1706 Feature Experience Pack 120.2212.4170.0

### Bug Description

Get the following error when trying to upload a file. 
```json
{
  "message": "\"UnexpectedCancel\""
}
```

Screenshots
![image](https://user-images.githubusercontent.com/20142527/173243577-f8da9747-0f1c-459e-b0bd-000ee8be6069.png)
![Screenshot 2022-06-12 123741](https://user-images.githubusercontent.com/20142527/173243640-7cb291fb-2f69-4ae1-b12a-ebdb36aaca15.png)

No issues when download files.

The upload error is also experienced when using the Azure Portal. This time, the error message is more informative.

![Screenshot 2022-06-12 130710](https://user-images.githubusercontent.com/20142527/173244756-2872df5a-205c-4b8a-ab96-b524fd6af06b.png)

The IAM page shows that I have the full access to the Blob Container.

![Screenshot 2022-06-12 131150](https://user-images.githubusercontent.com/20142527/173244922-c2a7617a-9191-4cd7-a86a-6fdc3df276b7.png)

Same error with #5146

### Steps to Reproduce

With Azure Storage Explorer
1. Launch Storage Explorer.
2. Select one Blob Container.
3. Click the Upload button.
4. Select file to upload in the dialogue window.
5. Click the Upload button in the dialogue window.

On Azure Portal
Similar procedure, just a normal upload.

### Actual Experience

An error is shown in the Activities panel when using Storage Explorer. An error is shown on the upload page when using Azure Portal. Details are shown in the previous screenshots.

### Expected Experience

File uploaded without errors.

### Additional Context

The upload worked one week ago, with the exact same settings. I did not change anything on the Azure Portal side and I was keeping uploading files from my local computer through Azure Storage Explorer. Then suddenly, on June 10th EST, I began to experience this error.

**Comment by JasonYeMSFT** [comment]
This type of error sometimes indicates internal AzCopy error that we don't recognize. If you use the "Go to AzCopy Log" action on the activity, you can find the log files matching the start time of the job and see if there is any error reported in them. You can either check it yourself or share the log file with us. Your credentials have already been redacted by AzCopy before writing to the logs.

**Comment by huyaoyu** [comment]
Our IT engineer thinks this might be a billing error on our side. After contacting the support of Azure, we can upload again.

**Comment by asmaier** [comment]
In my case the problem was related to https://github.com/Azure/azure-storage-azcopy/issues/755 . When trying to copy a blob container from one storage to another it failed, because the firewall was activated. In Storage Explorer this generated the UnexpectedCancel error. The workaround was to first download the container from storage A to my local machine and the upload it again from my machine to storage B.
