### ISSUE TITLE
Sub-Folders not always showing up

### ISSUE THREAD

**Issue by DStradley** [microsoft/AzureStorageExplorer#5841]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.23.1

### Architecture

i86

### Storage Explorer Build Number

20220406.1

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Some sub-folders do not show up when first going to a folder location on File Shares.  You have to go to the last page (which usually involves using Load More first) then go back to page 1 to see them.  If you just go to page 10 and back to 1 then some of them will show up, but not all.  This occurs in folders with a large number of files and or sub-folders.

### Steps to Reproduce

1. Launch Storage Explorer
2. Select a File Shares Node that contains a lot of files and at least some folders
3. See that the folders, which should be listed first are not present
4. Click on Load More to see more pages
5. Go to the last page
6. See that the folders are not there either
7. Go back to page 1
8. The folders now appear as they should

### Actual Experience

This is repeatable every time going to the same location.
Here an example case of what I first see in my image-tests/Out folder:
![image](https://user-images.githubusercontent.com/48810710/173664256-be963678-0ad1-4cd4-bec6-fa1da8983d81.png)

After Load more twice to get to last page (27) and scrolling down I just see my last file and still no folders:
![image](https://user-images.githubusercontent.com/48810710/173664764-ccebd41d-bdfe-44a5-9873-0c0821029e03.png)

After then selecting page 1 again (and scrolling back up) I now see my missing folders:
![image](https://user-images.githubusercontent.com/48810710/173665066-0ec33e78-71d5-4d50-aade-16797d8101ed.png)

I have another case where there are a lot of sub-folders, and they show up the first time except for the first two that start with an underscore.  Again, I have to go to the end and back to get those to show up.  (Very annoying, since usually they are the ones I want to go to.)

Sometimes you don't have to go the last page, but you do have to do a load more, then go to the last shown page and back to 1 to get everything to show up.

### Expected Experience

I expect all of my subfolders (and files) to show up (and in order), to the limits of what fits on page 1, when I first select a location.

**Comment by MRayermannMSFT** [comment]
@DStradley, unfortunately this is by design. The list files & folders API for file shares lists:
- alphabetically
- no preference for folders first

See remarks: https://docs.microsoft.com/en-us/rest/api/storageservices/list-directories-and-files#remarks

Improving the loading of data in the explorers has always been something we want to do, but the current APIs very much limit us. Additional customer feedback regarding issues like this could help the service team prioritize API for these use cases, so if you have additional feedback channels you use consider sharing this with them.
