### ISSUE TITLE
Importing a CSV file to table storage is not working. Shows a duplicate PartitionKey column

### ISSUE THREAD

**Issue by danielmartind** [microsoft/AzureStorageExplorer#5843]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.2

### Regression From

1.21.3

### Architecture

i86

### Storage Explorer Build Number

20220527.5

### Platform

Windows

### OS Version

Windows 11

### Bug Description

I am unable to import csv data into table storage as I was previously. Last time I know it was working was around November/December 2021. When trying to import the file a dialog shows with the PartitionKey column duplicated. The first entry shows a blank sample value and the second entry shows the data in the file. I only have the column once in the file and it is in the first column. The insert button in disabled so I am unable to import the data.

### Steps to Reproduce

1. Launch storage explorer
2. navigate to storage account and select tables
3. create table
4. import csv
[Test.csv](https://github.com/microsoft/AzureStorageExplorer/files/8910705/Test.csv)

### Actual Experience

![Screenshot 2022-06-15 161452](https://user-images.githubusercontent.com/6793344/173863329-26527bcd-0ebd-48d9-b835-1c93730bb763.png)
Dialog adds a second PartitionKey column highlighted red and won't allow the import as the insert button is disabled.

### Expected Experience

The data should be imported into the table

**Comment by danielmartind** [comment]
I have just found that if I change the duplicate PartitionKey name to something and leave the cell red box goes and the import button is enabled. I can then change the name back to PartitionKey and the import works

**Comment by craxal** [comment]
@danielmartind Did the above suggestion about changing the file format work for you?

Also, we have made modifications such that Storage Explorer will account for the BOM. These changes will be available in a future release.

**Comment by danielmartind** [comment]
@craxal Hadn't needed to import anything as managed with my workaround. Just given it a go and using that format and all working fine. Thanks for taking the time to look into this and get back to me.
