### ISSUE TITLE
Storage Explorer crashes on startup with ICU version 71

### ISSUE THREAD

**Issue by tonibgd** [microsoft/AzureStorageExplorer#5848]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.2-1

### Regression From

1.24.2-1

### Architecture

x64

### Storage Explorer Build Number

20220527.5

### Platform

Linux (tar.gz)

### OS Version

Arch Linux / openSUSE Tumbleweed

### Bug Description

Azure Storage Explorer depends on `.NET Core 3.1` which has limitation of max ICU version it can use, which is `70`.

Azure Storage Explorer crashes on startup if the system has higher versoin installed, latest one is `71.1`.

- https://github.com/unicode-org/icu/releases/tag/release-71-1
- https://archlinux.org/packages/core/x86_64/icu/
- https://software.opensuse.org/package/icu

Error:
`Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.`

**Workaround**: using the environmanet variable `CLR_ICU_VERSION_OVERRIDE=71.1`.

- `dotnet --info`
```
.NET SDK (reflecting any global.json):
 Version:   6.0.301
 Commit:    43f9b18481

Runtime Environment:
 OS Name:     manjaro
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.301/

Host (useful for support):
  Version: 6.0.6
  Commit:  7cca709db2

.NET SDKs installed:
  3.1.414 [/usr/share/dotnet/sdk]
  6.0.301 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.20 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.20 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

- `pacman -Si icu`
```
Repository      : core
Name            : icu
Version         : 71.1-1
Description     : International Components for Unicode library
Architecture    : x86_64
URL             : https://icu.unicode.org
Licenses        : custom:icu
Groups          : None
Provides        : libicudata.so=71-64  libicui18n.so=71-64  libicuio.so=71-64  libicutest.so=71-64
                  libicutu.so=71-64  libicuuc.so=71-64
Depends On      : gcc-libs  sh
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 10.85 MiB
Installed Size  : 39.73 MiB
Packager        : Andreas Radke <andyrtr@archlinux.org>
Build Date      : Thu 14 Apr 2022 04:09:12 PM CEST
Validated By    : MD5 Sum  SHA-256 Sum  Signature
```

### Steps to Reproduce

1. Update `ICU` to the latest version (`71.1-1`)
2. Start `Azure Storage Explorer`

### Actual Experience

Azure Storage Explorer crashes on startup if the system has ICU version higher then `70`

![2022-06-18_23-39](https://user-images.githubusercontent.com/7096100/174457839-d01d331a-29fe-4790-83cc-f6c30d911572.png)

**Comment by tonibgd** [comment]
I am not blocked by the issue, setting the environment variable allows ASE to start.

I am not sure about .NET 6, but i think it doesn't have ICU version limitation.

**Comment by MRayermannMSFT** [comment]
Ok. I'm going to close this as mitigated then.
