### ISSUE TITLE
There is a successful activity log when undeleting a soft deleted blob under snapshots view with an active blob already exists

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5849]
**Storage Explorer Version**: 1.24.3
**Build Number**: 20220617.2
**Branch**: hotfix/1.24.3
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture** ia32/x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one blob -> Soft delete it.
3. Upload a same blob -> Switch to the context view 'Active and soft deleted blobs'.
4. Right click the active blob -> Click 'Manage Snapshots'.
5. Right click the soft deleted blob -> Click 'Undelete -> Undelete Selected'.
6. Check whether there is a failed activity log.

## Expected Experience ##
There is a failed activity log.
![image](https://user-images.githubusercontent.com/41351993/174552651-83f0b061-9ff6-452b-b7a1-80259f454ee8.png)

## Actual Experience ##
There is a successful activity log.
![image](https://user-images.githubusercontent.com/41351993/174552581-60bbdb2d-9657-407f-b4fa-eb402a8cdcda.png)

**Comment by JasonYeMSFT** [comment]
The behavior here is by design. ADLS Gen2 soft delete works differently from the Blob soft delete. The new active blob is independent from the one soft deleted. If you switch to "Active and Deleted items", you can see the soft deleted item with a unique "deletion ID" and you will need to undelete that item to recover the data. Besides, you will need to get rid of the active item so it can be undeleted.

**Comment by v-xianya** [comment]
@JasonYeMSFT Thank you for the update! For this scenario, I'd expect there is a failed activity log indicating that the blob already exists.
Switch to "Active and soft deleted blobs", The current behavior:
Under blob view, Undelete the soft deleted blob. There is a failed activity log.
Under snapshots view. Undelete the soft deleted blob. There is a successful activity log.

**The behaviors are different between Blob view and Snapshot view, Is this by design?**
Here is the record:



![adls](https://user-images.githubusercontent.com/41351993/174697083-273e6ae9-6183-4b2b-9211-d126fe091336.gif)
