### ISSUE TITLE
Export entities to a file is not working

### ISSUE THREAD

**Issue by sharmi-19** [microsoft/AzureStorageExplorer#5854]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.2

### Architecture

x64

### Platform

Linux (tar.gz)

### Bug Description

{
  "name": "Error",
  "message": "ENOSYS: function not implemented, write",
  "stack": "Error: ENOSYS: function not implemented, write",
  "errno": -38,
  "code": "ENOSYS",
  "syscall": "write"
}

### Steps to Reproduce

Try to export anything.

### Actual Experience

When am trying to do an export query, it throws the above error.

**Comment by pintmil** [comment]
Hi, a have the same issue, with the same error details. I can dowload blobs, just the export from tables is not working.
Storage Exporer About:
Version 1.24.3
AzCopy Version: 10.14.1

Platform: Linux
Architectur: x64
Build Number: 20220617.2
Commit: 3ccc8329e
Support ID: e86469b3-d13e-92ac-cbc8-071e9b19543f

-------------- Env ---------------
$snap list storage-explorer 
Name              Version  Rev  Tracking       Publisher            Notes
storage-explorer  1.24.3   38   latest/stable  msft-storage-tools✓  -

$lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

$uname -a
Linux ********* 5.13.0-51-lowlatency #58~20.04.1-Ubuntu SMP PREEMPT Tue Jun 14 12:26:40 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by craxal** [comment]
@sharmri-19 @pintmil Does the error have any more details you can share (is there a "Details..." action you can click on)?

**Comment by craxal** [comment]
@pintmil This is an error message I've seen before, though I haven't been able to narrow down of the cause as of yet. Are you using the .tar.gz or the snap? What location are you trying to save the export file to? Does the export succeed if you save somewhere within your user home directory?

**Comment by pintmil** [comment]
@craxal I installed the StorageExplorer from snap. I tried to save the export csv file into different folders, to my home directory too, but the same error happend in every case.

**Comment by craxal** [comment]
@pintmil Interesting. Based on some of my searching, it's possible this may be a hardware issue. What kind of hardware are you running Ubuntu on? Also, what file system format is your system using?

**Comment by MRayermannMSFT** [comment]
@pintmil any response to @craxal 's question? Your bug is interesting to say the least.

**Comment by pintmil** [comment]
@craxal @MRayermannMSFT sorry i was on holiday. I use the software on a HP Zbook g4 laptop my linux partition is on a nvme ssd with xfs filesystem, nothing special. Everything else of my softwares work fine. Also i can save the blobs with the AzureStorageExplorer, just the csv export fails.

**Comment by craxal** [comment]
@pintmil The only difference I can think of between blobs and tables as far as file system access is concerned is Blobs uses AzCopy, whereas Tables uses Node's `fs` module. Can you upload or download .csv blobs? Have you tried the .tar.gz distribution to see if it has the same problem?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue, we recommend opening a support ticket via the Azure Portal. Alternatively you can open a new issue here.
