### ISSUE TITLE
The authentication library used by Storage Explorer has failed to start properly. 

### ISSUE THREAD

**Issue by gscorrea** [microsoft/AzureStorageExplorer#5855]
OS:
` Edition	Windows 11 Pro
Version	22H2
Installed on	‎5/‎16/‎2022
OS build	22621.160
Experience	Windows Feature Experience Pack 1000.22632.1000.0
`
ASE: 1.24.2
.Net: 4.8
[ASE logs.zip](https://github.com/microsoft/AzureStorageExplorer/files/8950481/ASE.logs.zip)

**Comment by MRayermannMSFT** [comment]
@gscorrea can you try:
1. Run storage explorer as admin
2. Uninstall and reinstall

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still facing this issue we recommend opening an Azure support ticket from the portal. Alternatively you can open a new issue here.
