### ISSUE TITLE
Set role="img" and aria-label for icon container elements in DataTable

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#5856]
As suggested by https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/img_role.

Data tables that may need this to be done include
- Queue
- Blob (non-HNS)
- Disks
- App Config
- Gen 1

**Comment by MRayermannMSFT** [comment]
To be handled in new data table.
