### ISSUE TITLE
Facing Issue while uploading dataset in Azure Explorer blob container, below are details:

### ISSUE THREAD

**Issue by Shani-Sharma** [microsoft/AzureStorageExplorer#5857]
Unable to retrieve child resources.

Details:
{
  "name": "RestError",
  "message": "{\"name\":\"RestError\",\"code\":\"ETIMEDOUT\",\"request\":{\"url\":\"https://management.azure.com//subscriptions/5c7ccb25-ac91-4a4b-8c03-5eebffd370fb/resources?api-version=2014-04-01&$filter=resourceType%20eq%20%27Microsoft.ClassicStorage%2FstorageAccounts%27%20or%20resourceType%20eq%20%27Microsoft.Storage%2FstorageAccounts%27\",\"headers\":{\"authorization\":\"Bearer JSON Web Token Redacted\",\"user-agent\":\"Microsoft Azure Storage Explorer/1.24.1 (win32)\"},\"method\":\"GET\",\"timeout\":30000,\"disableKeepAlive\":false,\"withCredentials\":false,\"requestId\":\"cf6d8ea5-2fa2-4942-b931-dbd783fa8eb1\",\"allowInsecureConnection\":true,\"enableBrowserStreams\":false}}"
}

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still facing this issue we recommend opening an Azure support ticket from the portal. Alternatively you can open a new issue here.
