### ISSUE TITLE
An error occurs when trying to save query for tables

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5859]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220622.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture** ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.24.3)

## Steps to Reproduce ##
1. Expand one storage account -> Tables,
2. Create a table -> Click 'Query' -> Click 'Save query as...' -> Click 'Save'.
3. Check no error occurs.

## Expected Experience ##
No error occurs.

## Actual Experience ##
An error occurs.
![image](https://user-images.githubusercontent.com/41351993/174972693-0dc22cda-a264-46b6-ae4d-3c4f5171736a.png)

## Additional Context ##
This issue also reproduces when trying to open saved query.

**Comment by craxal** [comment]
Ah, this is because it can't find the referenced string, which is in an unloaded namespace. I think I just forgot to move the necessary strings to the extension.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220624.2. Fixed. So close it.
