### ISSUE TITLE
The new added entity doesn't display if PartitionKey and RowKey are null and no custom property

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5860]
**Storage Explorer Version:** 1.25.0-dev
**Build Number:** 20220622.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.24.3)

## Bug Description ##

1. The new added entity doesn't display if PartitionKey and RowKey are null and no custom property.
2. The Timestamp property doesn't display if PartitionKey or RowKey is not null and no custom property.

## Steps to Reproduce ##

1. Expand one storage account -> Tables,
2. Create a table -> Click 'Add -> 'Insert'.
3. Check whether the new added entity displays.

## Expected Experience ##
The new added entity displays.

## Actual Experience ##
The new added entity doesn't display.
![image](https://user-images.githubusercontent.com/87792676/174986001-04f7f178-5565-4617-904b-fe5b26678349.png)

## Additional Context ##
This issue doesn't reproduce if the new added entity has custom properties.

**Comment by craxal** [comment]
Yeah, so the entity is in the table. The problem is the keys are "" (empty string). Since whitespace is normally collapsed, the whole row gets collapsed. Strange, though, because I was expecting those values to be "null"...

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220624.2, it still reproduces.

**Comment by craxal** [comment]
I still can't get this to reproduce on my end. I created a brand new table and added a new entity with no custom properties and no values for the keys. The new entity renders just fine. By default, the table adds the Timestamp column, but even after modifying the column settings to hide that column, the row still renders normally.

Let me get a new version of the table extension merged. It might be your builds don't have the updated version yet.

**Comment by v-kellyluo** [comment]
@craxal ,I have installed the latest build main 20220627.1, it still reproduces😢, could you please take a look?
![one](https://user-images.githubusercontent.com/87792676/175854108-5d374934-058c-4fe6-9492-c995bc35a192.gif)

**Comment by craxal** [comment]
@v-kellyluo I can produce with the same build. I haven't merged a package update for tables yet. I will let you know when it's ready.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220629.2. Fixed. So close it.
