### ISSUE TITLE
The action 'Edit Tags…' is enabled on the context menu for one emulator blob

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5861]
**Storage Explorer Version:** 1.25.0-dev
**Build Number:** 20220623.3
**Branch:** main
**Platform/OS:** Windows 10
**Architecture:** ia32
**How Found:** From running test cases
**Regression From:** Previous release (1.24.3)

## Steps to Reproduce ##

1. Install and run Azurite 3.17.1 -> Launch Storage Explorer.
2. Expand 'Local & Attached -> Storage Accounts -> (Emulator - Default Ports) (Key)' -> Blob Containers.
3. Upload a blob -> Right click it -> The context menu displays.
4. Check whether the action 'Edit Tags...' is disabled.

## Expected Experience ##
The action 'Edit Tags...' is disabled.

## Actual Experience ##
The action 'Edit Tags...' is enabled.

## Additional Context ##
The 'Tag Query' option can be selected in the 'View Options' panel.
![image](https://user-images.githubusercontent.com/87792676/175257077-bead281e-dffa-4cdd-b70f-e9588017cf8f.png)

**Comment by JasonYeMSFT** [comment]
We removed the feature flag which used to be controlling the tags feature since it is GA now. I will add a special check for emulator containers.

**Comment by v-kellyluo** [comment]
Update: This issue also reproduces in regular blob containers under one attached storage account without 'Filter' permission.

**Comment by JasonYeMSFT** [comment]
For the public Azure services, we are going to always enable the features. In some situations we cannot know which exact permissions the user have so we leave it for the user to figure it out. If they don't have enough permission, the service will give permission errors. However, emulators are more unpredictable if you attempt to use non-supported features in it so we decided to disable the option in that case.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220629.2. Fixed.
