### ISSUE TITLE
Microsoft Speech Corpus (Indian languages)

### ISSUE THREAD

**Issue by dhanya-e** [microsoft/AzureStorageExplorer#5864]
I am not able to download the dataset from this location:
https://msropendataset01.blob.core.windows.net/microsoftspeechcorpusindianlanguages

I receive the below error:

<Error>
<Code>BlobNotFound</Code>
<Message>The specified blob does not exist. RequestId:b00318a7-601e-00db-0689-873e30000000 Time:2022-06-24T05:18:02.4337185Z</Message>
</Error>

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still facing this issue we recommend opening an Azure support ticket from the portal. Alternatively you can open a new issue here.
