### ISSUE TITLE
Error uploading CSV file to the blob.error: UnexpectedCancel (used Azure AD, discovery completed)

### ISSUE THREAD

**Issue by ahmad-beshr** [microsoft/AzureStorageExplorer#5865]
![image](https://user-images.githubusercontent.com/9280940/175473499-73f202c9-028e-4bb9-95c3-14be139fc3cf.png)

This error occurs in versions from 1.24.0 and above.

**Comment by MRayermannMSFT** [comment]
@ahmad-beshr is there a button/link for the AzCopy log file? If so, can you share that with us by dragging and dropping it into the issue response text box?

**Comment by ahmad-beshr** [comment]
> @ahmad-beshr is there a button/link for the AzCopy log file? If so, can you share that with us by dragging and dropping it into the issue response text box?

Hi, it appears to be a permission issue. We can close the case :)
