### ISSUE TITLE
There is a missed property 'DFS Endpoint' and an extra property 'Permissions' for one storage account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5866]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220624.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: Ad-hoc testing
**Regression From**: Previous release (1.24.3)

## Steps to Reproduce ##
1. Select one normal GPV2 storage account -> Observe its 'Properties' panel.
2. Check whether there is no missed and extra property.

## Expected Experience ##
There is no missed and extra property.
![image](https://user-images.githubusercontent.com/41351993/175507193-714f64cc-6f44-4b2d-9e0a-11c353fe78c0.png)

## Actual Experience ##
There is a missed property 'DFS Endpoint' and an extra property 'Permissions'.
![image](https://user-images.githubusercontent.com/41351993/175507453-50850b27-f6c6-4f0b-be3c-591423bbea1c.png)

**Comment by v-xianya** [comment]
@MRayermannMSFT Thank you for the updates.

For storage account that doesn't have HNS enabled. There is a 'Secondary DFS Endpoint' property. Is this intentional?
![image](https://user-images.githubusercontent.com/41351993/176331480-f732e8a6-cd84-4338-96f3-ae79e71cba12.png)

**Comment by MRayermannMSFT** [comment]
No, that is wrong! Thank you for pointing that out.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220630.8. Fixed.
