### ISSUE TITLE
The property 'Support Tags' doesn't display on the Properties panel for blob containers under one attached storage account

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5867]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220624.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.24.3)

## Steps to Reproduce ##

1. Select one storage account -> Right click it -> Click 'Get Shared Access Signature...'.
2. Select all permissions -> Create and copy the connection string.
3. Open the connect dialog -> Attach the storage account by the connection string.
4. Switch to the attached storage account -> Select one blob container.
5. Observe its Properties panel.
6. Check whether the property 'Support Tags' displays.

## Expected Experience ##
The property 'Support Tags' displays.
![image](https://user-images.githubusercontent.com/87792676/175508643-4c8f59de-1627-4086-b351-67b17a404c5b.png)

## Actual Experience ##
The property 'Support Tags' doesn't display.
![image](https://user-images.githubusercontent.com/87792676/175508000-e4578667-afcb-4544-b9a9-bb3f1e1b7af3.png)

**Comment by JasonYeMSFT** [comment]
This is by design. Blob Tags has been GA so we decided to stop checking for it by polling some of the tags APIs. This would reduce the chance that we incorrectly disable the features for some users.
