### ISSUE TITLE
The warning message will display in the text editor if narrowing the table explorer horizontally under the query mode

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5869]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220627.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: Ad-hoc testing
**Regression From**: Previous release (1.24.3)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create one table -> Click 'Query' -> Click 'Text editor'.
3. Narrow the table explorer horizontally.
4. Check the warning message doesn't display in the text editor.

## Expected Experience ##
The warning message doesn't display in the text editor.
![image](https://user-images.githubusercontent.com/41351993/175898593-6cd25466-5a2a-4a32-84ed-704b527980e8.png)

## Actual Experience ##
The warning message displays in the text editor.
![image](https://user-images.githubusercontent.com/41351993/175896305-c56805ba-d84a-4bde-b589-9887ef6889e5.png)

## Additional Context ##
This issue also reproduces for 'Select fields for query' part if narrowing the table explorer horizontally under the query mode.
![image](https://user-images.githubusercontent.com/41351993/175896560-d7d5eeae-9210-4525-b4f6-718acf3227bf.png)

**Comment by craxal** [comment]
@v-xianya Can you explain the additional context more? I don't see any overlapping text under the Advanced Options.

**Comment by v-xianya** [comment]
@craxal For the Advanced Options. this issue only reproduces if the 'Text editor' is opened.
Here is the record:
![0628](https://user-images.githubusercontent.com/41351993/176072242-a93ccc53-ad44-4bc7-9d6b-48bf6d05f393.gif)

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220630.1. The overlap issue has been fixed. So we are going to close it.
![image](https://user-images.githubusercontent.com/41351993/176578387-d2e67cc4-3caf-4e08-ae02-4ccf4cadeafd.png)
