### ISSUE TITLE
A loading icon displays if pressing 'F5' in one table explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5870]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220627.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: Ad-hoc testing
**Regression From**: Previous release (1.24.3)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a new table -> The new created table auto opens.
3. Press 'F5' -> Check whether no loading icon displays.

## Expected Experience ##
No loading icon displays.

## Actual Experience ##
A loading icon displays.

![image](https://user-images.githubusercontent.com/41351993/175904657-dd9e3bb6-c3fd-4cb0-a829-198c494a6286.png)

**Comment by craxal** [comment]
This is by design. F5 triggers the current query to run. If you hover over the Run button in the query builder in both the old and new explorers, you should see the keyboard shortcut in the tooltip. For some reason, in the old explorer, the shortcut wasn't wired up.

**Comment by v-xianya** [comment]
@craxal thank you for the update. 'F5' is the shortcut of 'Execute query' with the query builder is opened.

 F5 works without opening the 'query builder'. Is this also by design?

**Comment by craxal** [comment]
@v-xianya Hard to say, since it wasn't hooked up properly in the older explorer. But I wouldn't normally expect the query to run if the query builder was closed. I'll fix that. No need to open another issue for it.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220630.8. Fixed.
