### ISSUE TITLE
File Share explorer window not showing all metadata column headers, and there appear to be no options to enable them

### ISSUE THREAD

**Issue by bakoontz2** [microsoft/AzureStorageExplorer#5871]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.3

### Architecture

x64

### Storage Explorer Build Number

20220617.2

### Platform

Windows

### Bug Description

When viewing file shares in the Explorer window, there are no descriptive column headers other than Name and Size:

![image](https://user-images.githubusercontent.com/38893590/175976853-8136b670-6067-4980-b321-a2d5a9f41ecb.png)

There is no apparent way to add these.  However, the documentation clearly shows these column headers (at least for queues):

![image](https://user-images.githubusercontent.com/38893590/175977149-f4110021-cc84-4c36-ba3f-d5fd654f0ffa.png)

Is there any way to edit the Explorer window to display other file metadata other than Name and Size?

### Steps to Reproduce

1. Launch Explorer.
2. View a file in any File Share.

### Actual Experience

Only Name and Size metadata displayed, and there appear to be no way to add metadata columns.

### Expected Experience

Either have additional metadata columns, or a way to display them.

**Comment by MRayermannMSFT** [comment]
Hi @bakoontz2 . Thanks for opening an issue. Yes, the service recently added quite a bit of extra data to what it returns when listing files & directories. We have an issue open for adding these already. Please see here: https://github.com/microsoft/AzureStorageExplorer/issues/439 Feel free to comment on that issue with any additional information or context you would like to add. Thanks!
