### ISSUE TITLE
Unable to retrieve child resources issue on Storage Explorer

### ISSUE THREAD

**Issue by sanjaybhujbal** [microsoft/AzureStorageExplorer#5872]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.3

### Architecture

x64

### Storage Explorer Build Number

20220617.2

### Platform

Windows

### OS Version

Windows 10

### Bug Description

We are facing following issue when trying to connect to Blob or file storage using SAS connectio string.

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://nsprdeutoccsatestbench.file.core.windows.net/?sv=2020-08-04&ss=bfqt&srt=sco&sp=rltf&se=2024-03-22T13:18:53Z&st=2022-03-22T05:18:53Z&spr=https,http&SAS Token Redacted&comp=list failed, reason: unable to get local issuer certificate",
..
..

.

node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY",
  "code": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"
}

### Steps to Reproduce

1. Launch Storage Explorer
2. Connect using SAS connection String
3. 3. Open Blob Storage

### Actual Experience

Getting Error

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://nsprdeutoccsatestbench.file.core.windows.net/?sv=2020-08-04&ss=bfqt&srt=sco&sp=rltf&se=2024-03-22T13:18:53Z&st=2022-03-22T05:18:53Z&spr=https,http&SAS Token Redacted&comp=list failed, reason: unable to get local issuer certificate"

### Expected Experience

Should Connect to bob storage.

### Additional Context

This was working for a few days then stopped.

**Comment by MRayermannMSFT** [comment]
@sanjaybhujbal can you try using system proxy setting? You can read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having problems, we recommend opening an Azure support ticket from the Azure portal. Alternatively you can open a new issue here.
