### ISSUE TITLE
Open file and add extension to trusted extensions. 

### ISSUE THREAD

**Issue by jsuddsjr** [microsoft/AzureStorageExplorer#5873]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

The process of accepting a novel extension is unnecessarily complex

### Desired Solution

When opening a file with novel extension, confirm the file is OK and do not ask again. The extension is automatically added to a list of allowed extensions. 

### Alternatives and Workarounds

Edit the config file, if you can. The default list is readonly and cannot be edited. Opening the config JSON doesn't provide a key name, so.... best of luck.

### Additional Context

Just because you all are developers doesn't mean your users have the time or inclination to edit a JSON file to work around this feature.

**Comment by MRayermannMSFT** [comment]
At the same time we do this, let's also fix the `defaultValue` for `stringArray` settings to not be the textbox placeholder but actual text. That way it is easier to manually edit the list without losing the default list of trusted file extensions.

**Comment by MRayermannMSFT** [comment]
Done. Will be included in 1.28.
![image](https://user-images.githubusercontent.com/21112697/206767565-b4db4feb-e26a-4e92-8108-6cec83b7cab3.png)
