### ISSUE TITLE
Error during updating the new version of Azure Storage Explorer

### ISSUE THREAD

**Issue by pladee42** [microsoft/AzureStorageExplorer#5874]
I'm using Azure Storage Explorer V.1.2.3 and when I try to update the new version it shows this popup below.

![image](https://user-images.githubusercontent.com/75304546/176084979-616a6fdd-ba36-4c03-aa3d-f464151a945d.png)

**Comment by MRayermannMSFT** [comment]
@pladee42 it seems like for some reason you're going to either:
- Run Storage Explorer as admin and then click "Install"
- Download and install the update yourself from https://www.storageexplorer.com

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you're still running into this problem we recommend opening an Azure support ticket via the Azure Portal. Alternatively you can open a new issue here.
