### ISSUE TITLE
The default access tier for one blob is not localized

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5875]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220628.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Language**: All languages
**How Found**: From running test case
**Regression From**: Previous releases (1.24.3)

## Steps to Reproduce ##
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文（简体）' -> Restart Storage Explorer.
3. Expand one storage account -> Blob Containers.
4. Create a blob container -> Upload one blob with the default access tier.
5. Check whether the access tier is localized.

## Expected Experience ##
The access tier is localized.
![image](https://user-images.githubusercontent.com/41351993/176120242-3f8d2aa3-d058-4b65-ac35-c8b117ab640d.png)

## Actual Experience ##
The access tier is not localized.
![image](https://user-images.githubusercontent.com/41351993/176120263-6533c56e-f59c-40f6-a1ac-c838febe57c6.png)

**Comment by craxal** [comment]
This is due to an intentional string change to address #4451. This will be translated in due time.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220725.3. Fixed. So close it.
