### ISSUE TITLE
The string 'Adjust Bandwidth Limit…' is not localized on the Activities panel

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5876]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220628.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Language**: All languages
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文（简体）' -> Restart Storage Explorer.
3. Expand one storage account -> Blob Container.
4. Create a blob container -> Upload one blob.
5. Observe the string next to the activity log.
6. Check whether the string 'Adjust Bandwidth Limit...' is localized.

## Expected Experience ##
The string 'Adjust Bandwidth Limit...' is localized.

## Actual Experience ##
The string 'Adjust Bandwidth Limit...' is not localized.
![image](https://user-images.githubusercontent.com/41351993/176122136-af4cfa1a-b44d-4c01-8be5-0667e0eedb3c.png)

**Comment by JasonYeMSFT** [comment]
The strings are localizable but will need for the translators to replace them with localized strings.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220725.3. Fixed. So close it.
