### ISSUE TITLE
The characters on the toolbar are not localized for tables

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5877]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220628.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Language**: All languages
**How Found**: From running test case
**Regression From**: Previous releases (1.24.3)

## Steps to Reproduce ##
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文（简体）' -> Restart Storage Explorer.
3. Expand one storage account -> Tables -> Open one table.
4. Check whether the characters on the toolbar are localized.

## Expected Experience ##
The characters on the toolbar are localized.
![image](https://user-images.githubusercontent.com/41351993/176128664-a56a9e8a-9fe4-4b7d-b199-b592e43976c6.png)

## Actual Experience ##
The characters on the toolbar are not localized.
![image](https://user-images.githubusercontent.com/41351993/176131161-d09099b0-5b63-4455-9b21-496e4f8eb24b.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220725.3. Fixed. So close it.
