### ISSUE TITLE
The action 'Pin/Unpin to Quick Access' on the context menu is not localized

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5879]
**Storage Explorer Version:** 1.25.0-dev
**Build Number:** 20220628.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Language:** All languages
**How Found:** From running test case
**Regression From:** Not a regression
 
## Steps to Reproduce ##

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文（简体）' -> Restart Storage Explorer.
3. Right click one storage account -> The context menu displays.
4. Check whether the action 'Pin to Quick Access' is localized.

## Expected Experience ##
The action 'Pin to Quick Access' is localized.

## Actual Experience ##
The action 'Pin to Quick Access' is not localized.
![image](https://user-images.githubusercontent.com/87792676/176121286-43bae32f-cffe-4e36-b084-4273597d5743.png)

**Comment by MRayermannMSFT** [comment]
Due to moving of strings. I will keep an eye on this.

**Comment by MRayermannMSFT** [comment]
Published new package. Updated strings are available.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220719.17. Fixed.
