### ISSUE TITLE
After every application restart application propose to connect to new Azure Storage account

### ISSUE THREAD

**Issue by olgakorichkovskaya** [Microsoft/AzureStorageExplorer#588]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows 10 Enterprise
**Architecture**: ia32
**Regression From**: n/a

#### Steps to Reproduce: ####
1. Run application 
2. Dialog about connection to the new account appears 

#### Expected Experience: ####
After restart main application windows with already exiisting Storages is shown,

#### Actual Experience: ####
User get dialog with connection to one more Storate Account.

**Comment by MRayermannMSFT** [comment]
Fix merged into hotfix branch. Thank you for the report @olgakorichkovskaya .
