### ISSUE TITLE
The 'Application -> Logging' part is not localized on 'Settings' page

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5880]
**Storage Explorer Version:** 1.25.0-dev
**Build Number:** 20220628.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Language:** All languages
**How Found:** From running test case
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Launch Storage Explorer.
2. Open Settings -> Application (Regional Settings) -> Select '中文（简体）' -> Restart Storage Explorer.
3. Open Settings -> Application -> Observe the 'Logging' part.
4. Check whether this part is localized.

## Expected Experience ##
This part is localized.

## Actual Experience ##
This part is not localized.
![image](https://user-images.githubusercontent.com/87792676/176126140-05728b8a-3aac-443f-8c28-dc0daca240bb.png)

**Comment by MRayermannMSFT** [comment]
Will keep an eye and make sure these get translated.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220719.8. Fixed.
