### ISSUE TITLE
The action 'Detach' is not localized on the context menu for one attached storage account

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5881]
**Storage Explorer Version:** 1.25.0-dev
**Build Number:** 20220628.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Language:** All languages
**How Found:** From running test case
**Regression From:** Previous release (1.24.3)

## Steps to Reproduce ##

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文（简体）' -> Restart Storage Explorer.
3. Select one storage account -> Attach it.
4. Right click the attached storage account -> The context menu displays.
5. Check whether the action 'Detach' is localized.

## Expected Experience ##
The action 'Detach' is localized.
![image](https://user-images.githubusercontent.com/87792676/176122566-23f9daec-d8ce-4e11-bc4b-9ccd1580a106.png)

## Actual Experience ##
The action 'Detach' is not localized.
![image](https://user-images.githubusercontent.com/87792676/176122838-2314ed07-0369-48e2-9964-d2e5c8dd23b0.png)

## Addition Context ##
This issue doesn't reproduce for attached services.

**Comment by MRayermannMSFT** [comment]
Due to moving of strings. I will keep an eye on this.

**Comment by MRayermannMSFT** [comment]
Published new package. Updated strings are available.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220719.17. Fixed.
