### ISSUE TITLE
The action 'Connect to Azure Storage…' is not localized for the Storage Accounts node

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5882]
**Storage Explorer Version:** 1.25.0-dev
**Build Number:** 20220628.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Language:** All languages
**How Found:** From running test case
**Regression From:** Previous release (1.23.1)

## Steps to Reproduce ##

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文（简体）' -> Restart Storage Explorer.
3. Right click Storage Accounts node -> The context menu displays.
4. Check whether the action 'Connect to Azure Storage...' is localized.

## Expected Experience ##
The action 'Connect to Azure Storage...' is localized.
![image](https://user-images.githubusercontent.com/87792676/176124269-cdb0bec2-7f1a-456f-b0d6-fad89281c102.png)

## Actual Experience ##
The action 'Connect to Azure Storage...' is not localized.
![image](https://user-images.githubusercontent.com/87792676/176124500-e4a7c17d-816c-4b46-b589-cc235ce4f1d3.png)

**Comment by MRayermannMSFT** [comment]
Due to moving of strings. I will keep an eye on this.

**Comment by MRayermannMSFT** [comment]
Published new package. Updated strings are available.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220719.17. Fixed.
