### ISSUE TITLE
The 'Emulator & Attached' node is not localized

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5883]
**Storage Explorer Version:** 1.25.0-dev
**Build Number:** 20220628.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Language:** All languages
**How Found:** From running test case
**Regression From:** Previous release (1.24.3)

## Steps to Reproduce ##

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文（简体）' -> Restart Storage Explorer.
3. Check whether the 'Emulator & Attached' node is localized.

## Expected Experience ##
The 'Emulator & Attached' node is localized.

## Actual Experience ##
The 'Emulator & Attached' node is not localized.

## Additional Context ##
The nodes (Attached Containers) and (Emulator-Default Ports) (key) are not localized.
![image](https://user-images.githubusercontent.com/87792676/176138925-bab3d04c-c942-42bc-bb06-68da1f477696.png)

**Comment by MRayermannMSFT** [comment]
Due to moving of strings. I will keep an eye on this.

**Comment by MRayermannMSFT** [comment]
@v-kellyluo it looks like these strings are now localized. I'm going to close this issue.

**Comment by v-kellyluo** [comment]
@MRayermannMSFT, verified this issue on the build main/20220719.8:

1. The 'Emulator & Attached' node is localized.
2. The nodes (Attached Containers) and (Emulator-Default Ports) (key) are not localized.
![image](https://user-images.githubusercontent.com/87792676/179654984-d462e630-c9e5-4935-aea2-9f5941ed4c08.png)

**Comment by MRayermannMSFT** [comment]
The strings are now translated and I've updated the package.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220719.17. Fixed.
