### ISSUE TITLE
Local blob container not opening

### ISSUE THREAD

**Issue by deepakiim** [microsoft/AzureStorageExplorer#5884]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.3

### Architecture

x64

### Storage Explorer Build Number

20220617.2

### Platform

Linux (snap)

### OS Version

ubuntu 18.04

### Bug Description

Error Details
If you cannot resolve this issue on your own, you may open an issue on the Storage Explorer GitHub site. Please include the details below to help us diagnose your issue. Make sure to redact any personal information you do not wish to make public before posting.

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://127.0.0.1:10000/devstoreaccount1?comp=list&include=metadata failed, reason: write EPROTO 24146310299144:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:\n",
  "stack": "FetchError: request to https://127.0.0.1:10000/devstoreaccount1?comp=list&include=metadata failed, reason: write EPROTO 24146310299144:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:\n\n    at ClientRequest.<anonymous> (/snap/storage-explorer/38/resources/app/node_modules/node-fetch/lib/index.js:1491:11)\n    at ClientRequest.emit (node:events:390:28)\n    at TLSSocket.socketErrorListener (node:_http_client:447:9)\n    at TLSSocket.emit (node:events:390:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "EPROTO",
  "code": "EPROTO"
}

### Steps to Reproduce

open and view contents of container

### Actual Experience

popup with title Error details

**Comment by MRayermannMSFT** [comment]
Since you're using https with Azurite please either:
1. Try using system proxy (can be found under Settings (gear on the left hand side -> application -> proxy)
2. Following what this user did: https://github.com/microsoft/AzureStorageExplorer/issues/2598#issuecomment-616765993

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you're still running into this problem we recommend opening an Azure support ticket via the Azure Portal. Alternatively you can open a new issue here.

**Comment by deepakiim** [comment]
in the storage explorer there is a option to disable proxy for copy. selecting that solved this issue.
