### ISSUE TITLE
Retrieve blobs in reverse date order, most recent first

### ISSUE THREAD

**Issue by TonyGrayCanada** [microsoft/AzureStorageExplorer#5886]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I frequently use Storage Explorer to check for ongoing imported data.  It's very difficult to actually see what the latest blob is, since simply sorting by  'Last Modified' only does so for whichever blobs happen to be in the cache.  You have to page through, retrieving ALL blobs into the cache, then sort by date to see what the most recent one is.  I have to do this several times per day and it's really annoying.

### Desired Solution

Add 'true' sorting by date when retrieving from the API so I can see blobs in true descending date order.

### Alternatives and Workarounds

Alternatively, a way to pull all blob records into the cache at once to make the existing sorting work to find the newest blob.

**Comment by TonyGrayCanada** [comment]
I should have added - I like the Storage Explorer and am glad you made it.  I used it all the time, so please don't take this request as a complaint!

**Comment by MRayermannMSFT** [comment]
Hi @TonyGrayCanada thanks for the kind words. I'm also glad to see that you are aware of the API limitations we are constrained by. Unfortunately, at this time the platform team has not set a timeline for when the API will support additional ways to order the listing of blob. We will pass along your additional request to them, but I encourage you to reach out to Azure/Microsoft with whatever other feedback channels you have and ask for this via that as well. Such as some sort of account or sales person that you/your company works with.
