### ISSUE TITLE
Expand list of subscriptions

### ISSUE THREAD

**Issue by syspro-chrisvogt** [microsoft/AzureStorageExplorer#5887]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.3

### Architecture

x64

### Storage Explorer Build Number

20220617.2

### Platform

Windows

### OS Version

Windows 11

### Bug Description

When expanding the list of subscriptions for a given tenant they are all selected. There is no way to expand and see the list of subscriptions and then select a small subset of these, you have de-select all the unwanted subscriptions. This is not a problem in and of itself, but is a bit of a nightmare when you have a couple of hundred of subscriptions in your tenant. There is no way to expand and simply populate the list of subscriptions but all de-selected.

### Steps to Reproduce

1. Launch Storage Explorer
2. Go to the Account Management tab
3. Expand a tenant, all underlying subscriptions are selected

### Actual Experience

Expanding subscription states that it is filtered out
![Expanding subscription states that it is filtered out](https://user-images.githubusercontent.com/102591762/176354413-9a42d9bb-790c-4433-9ab5-808a9900ed92.png)

After ticking the subscription the list is populated and all are automatically selected
![After ticking the subscription the list is populated and all are automatically selected](https://user-images.githubusercontent.com/102591762/176354651-8c012520-160f-48b3-8efa-bde91b617b60.png)

### Expected Experience

When expanding the tenant the subscriptions should not all be selected by default. I'm not sure others will agree, when I am ambivalent myself as this is probably the expected behaviour and would ultimately then require a new "Select all" feature. I feel this could be accomplished though by the list of subscriptions being expanded de-selected and the tick box for the subscription either being unticked or a greyed out tick, which if then clicked again would select all the subscriptions below and become a blue tick.

**Comment by MRayermannMSFT** [comment]
@syspro-chrisvogt thanks for opening this issue. We had someone else already raise an issue for this, so I'm going to close this as a duplicate: https://github.com/microsoft/AzureStorageExplorer/issues/5774
