### ISSUE TITLE
403 Server faild to authenticated the request

### ISSUE THREAD

**Issue by wangkenpu** [microsoft/AzureStorageExplorer#5890]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.3

### Architecture

i86

### Storage Explorer Build Number

20220617.2

### Platform

Windows

### OS Version

Windows10

### Bug Description

I want to download a folder in Azure Storage Explorer, but facing an authentication error.

### Steps to Reproduce

1. Launch the Azure Storage Explorer
2. Navigate to the Storage Account -> Container
3. Right-click the folder and download

### Actual Experience

{
  "message": "\"failed to perform copy command due to error: cannot start job due to error: cannot list files due to reason -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.13.1-0.20210914164749-2d6cd3e07548/azblob/zc_storage_error.go:42\\n===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====\\nDescription=403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature., Details: (none)\\n   HEAD https://spsvclocusw2.blob.core.windows.net/referencemodels/0_zh-cn-20200721-1-1_HALIDE_DGI/adaptedLM*****************SAS token************&timeout=901\\n   User-Agent: [Microsoft Azure Storage Explorer, 1.24.3, win32, azcopy-node/2.5.0 (win32)  AzCopy/10.14.1 Azure-Storage/0.14 (go1.16.14; Windows_NT)]\\n   X-Ms-Client-Request-Id: [6bf5003e-a1ef-4f08-792d-c6bd47c3d1c6]\\n   X-Ms-Version: [2020-04-08]\\n   --------------------------------------------------------------------------------\\n   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\\n   Access-Control-Allow-Origin: [*]\\n   Access-Control-Expose-Headers: [x-ms-request-id,x-ms-error-code,Content-Length,Date,Transfer-Encoding]\\n   Date: [Thu, 30 Jun 2022 02:32:54 GMT]\\n   Server: [Microsoft-HTTPAPI/2.0]\\n   X-Ms-Error-Code: [AuthenticationFailed]\\n   X-Ms-Request-Id: [feaec06a-601e-008e-0729-8c9bb8000000]\\n\\n\\n.\\n\""
}

### Expected Experience

Download the folder successfully.

**Comment by jinglouMSFT** [comment]
Replied in email with the following questions:
Couple of questions:
-	How do you connect to Azure storage?  Do you sign into Azure to access the container?  Or do you use a SAS URL to attach to the container?  If SAS URL, has it been expired?
-	What permissions do you have on this container?  Are you a “contributor”?
-	Do you go through a firewall or VPN or such?  You can that on the storage account?

**Comment by wangkenpu** [comment]
Replied in email (more details can be found by emails).

1.	How do you connect to Azure storage?  Do you sign in to Azure to access the container?  Or do you use a SAS URL to attach to the container?  If SAS URL, has it been expired?
I used my Microsoft account to log in to the Azure storage. After login, I get permission to access the resources automatically. 

2.	What permissions do you have on this container?  Are you a “contributor”?
I have read/write/deletion permission. Yes. I’m a contributor. 

3.	Do you go through a firewall or VPN or such?  You can that on the storage account?
No. I used corp net to access the resources.

**Comment by jinglouMSFT** [comment]
1. From the Storage Explorer screenshot you included in the original email (below), it looks like the folder you tried to download is a part of the “Local & Attached”.  If this indeed is the case, you were accessing the blob container/folder using a SAS URL.  In this screenshot, the “Local & Attached” includes all access using the SAS URL and/or using a local emulator.  The “AzureTest…..@microsoft.com” is the Azure subscription (accessed through the sign-in). Anything under the subscription node is accessed through the sign-in authentication.  

![image](https://user-images.githubusercontent.com/10081483/177426862-044b3390-2c44-466b-919f-58061eb81868.png)

2. The 403 error message indicated to me that you either didn’t have the permission to list the content of the blob folder, or the SAS URL has expired or the key used to generate the SAS URL has been rotated which made your SAS URL invalid to access the blob folder anymore. Could you check to make sure your SAS URL gives the correct permissions?

**Comment by wangkenpu** [comment]
Thanks, @jinglouMSFT. The folder I tried to download is not a part of "Local & Attached", I just add quick access of this folder to "Quick Access". 
With your hint, I detect the shortcut or the folder in "Quick Access" and re-add it again. Then, everything seems OK. So I think the folder in the "Quick Access" may not get the latest SAS token, i.e., the SAS token maybe not be synced for the folder in "Quick Access" and in its original container.
![image](https://user-images.githubusercontent.com/15028609/177445872-891efb49-0ed2-42b0-9afd-d4effa491156.png)
