### ISSUE TITLE
Table cannot be deleted from Azure Storage Explorer

### ISSUE THREAD

**Issue by novarun** [microsoft/AzureStorageExplorer#5891]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.3

### Architecture

x64

### Platform

Windows

### OS Version

Windows 11

### Bug Description

**Table created from Storage Explorer; but cannot be deleted. Had to go to Azure portal to delete it.**

Error details:
{
  "name": "RestError",
  "message": "{\"odata.error\":{\"code\":\"AuthorizationPermissionMismatch\",\"message\":{\"lang\":\"en-US\",\"value\":\"This request is not authorized to perform this operation using this permission.\\nRequestId:6654c8d1-0002-0004-0a46-8c4598000000\\nTime:2022-06-30T05:58:52.9808534Z\"}}}",
  "stack": "RestError: {\"odata.error\":{\"code\":\"AuthorizationPermissionMismatch\",\"message\":{\"lang\":\"en-US\",\"value\":\"This request is not authorized to perform this operation using this permission.\\nRequestId:6654c8d1-0002-0004-0a46-8c4598000000\\nTime:2022-06-30T05:58:52.9808534Z\"}}}\n    at handleErrorResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-client\\dist\\index.js:1264:19)\n    at deserializeResponseBody (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-client\\dist\\index.js:1199:45)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
  "statusCode": 403,
  "request": {
    "url": "https://mod3asst1.table.core.windows.net/Tables('mod2asst3')?sv=2021-06-08&ss=bfqt&srt=sco&sp=rwlacpitfx&se=2022-06-30T13%3A32%3A53Z&st=2022-06-30T05%3A32%3A53Z&spr=https%2Chttp&SAS Token Redacted",
    "headers": {
      "x-ms-version": "2019-02-02",
      "accept": "application/json",
      "accept-encoding": "gzip,deflate",
      "user-agent": "Microsoft Azure Storage Explorer/1.24.3 (win32) azsdk-js-data-tables/13.1.1 core-rest-pipeline/1.8.0 Node/v16.13.2 OS/(ia32-Windows_NT-10.0.22000)",
      "x-ms-client-request-id": "73b00dbb-7350-4405-8e79-52243a809ba2"
    },
    "method": "DELETE",
    "timeout": 0,
    "disableKeepAlive": false,
    "streamResponseStatusCodes": {},
    "withCredentials": false,
    "tracingOptions": {
      "tracingContext": {
        "_contextMap": {}
      }
    },
    "requestId": "73b00dbb-7350-4405-8e79-52243a809ba2",
    "allowInsecureConnection": true,
    "enableBrowserStreams": false
  },
  "response": {
    "status": 403,
    "headers": {
      "cache-control": "no-cache",
      "transfer-encoding": "chunked",
      "content-type": "application/json;odata=minimalmetadata;streaming=true;charset=utf-8",
      "server": "Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0",
      "x-ms-request-id": "6654c8d1-0002-0004-0a46-8c4598000000",
      "x-ms-client-request-id": "73b00dbb-7350-4405-8e79-52243a809ba2",
      "x-ms-version": "2019-02-02",
      "x-content-type-options": "nosniff",
      "date": "Thu, 30 Jun 2022 05:58:52 GMT"
    },
    "request": {
      "url": "https://mod3asst1.table.core.windows.net/Tables('mod2asst3')?sv=2021-06-08&ss=bfqt&srt=sco&sp=rwlacpitfx&se=2022-06-30T13%3A32%3A53Z&st=2022-06-30T05%3A32%3A53Z&spr=https%2Chttp&SAS Token Redacted",
      "headers": {
        "x-ms-version": "2019-02-02",
        "accept": "application/json",
        "accept-encoding": "gzip,deflate",
        "user-agent": "Microsoft Azure Storage Explorer/1.24.3 (win32) azsdk-js-data-tables/13.1.1 core-rest-pipeline/1.8.0 Node/v16.13.2 OS/(ia32-Windows_NT-10.0.22000)",
        "x-ms-client-request-id": "73b00dbb-7350-4405-8e79-52243a809ba2"
      },
      "method": "DELETE",
      "timeout": 0,
      "disableKeepAlive": false,
      "streamResponseStatusCodes": {},
      "withCredentials": false,
      "tracingOptions": {
        "tracingContext": {
          "_contextMap": {}
        }
      },
      "requestId": "73b00dbb-7350-4405-8e79-52243a809ba2",
      "allowInsecureConnection": true,
      "enableBrowserStreams": false
    },
    "bodyAsText": "{\"odata.error\":{\"code\":\"AuthorizationPermissionMismatch\",\"message\":{\"lang\":\"en-US\",\"value\":\"This request is not authorized to perform this operation using this permission.\\nRequestId:6654c8d1-0002-0004-0a46-8c4598000000\\nTime:2022-06-30T05:58:52.9808534Z\"}}}",
    "parsedBody": {
      "odataError": {
        "code": "AuthorizationPermissionMismatch",
        "message": {
          "lang": "en-US",
          "value": "This request is not authorized to perform this operation using this permission.\nRequestId:6654c8d1-0002-0004-0a46-8c4598000000\nTime:2022-06-30T05:58:52.9808534Z"
        }
      }
    },
    "parsedHeaders": {
      "cache-control": "no-cache",
      "transfer-encoding": "chunked",
      "content-type": "application/json;odata=minimalmetadata;streaming=true;charset=utf-8",
      "server": "Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0",
      "x-ms-request-id": "6654c8d1-0002-0004-0a46-8c4598000000",
      "x-ms-client-request-id": "73b00dbb-7350-4405-8e79-52243a809ba2",
      "x-ms-version": "2019-02-02",
      "x-content-type-options": "nosniff",
      "date": "Thu, 30 Jun 2022 05:58:52 GMT"
    }
  },
  "details": {
    "cache-control": "no-cache",
    "transfer-encoding": "chunked",
    "content-type": "application/json;odata=minimalmetadata;streaming=true;charset=utf-8",
    "server": "Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0",
    "x-ms-request-id": "6654c8d1-0002-0004-0a46-8c4598000000",
    "x-ms-client-request-id": "73b00dbb-7350-4405-8e79-52243a809ba2",
    "x-ms-version": "2019-02-02",
    "x-content-type-options": "nosniff",
    "date": "Thu, 30 Jun 2022 05:58:52 GMT",
    "odataError": {
      "code": "AuthorizationPermissionMismatch",
      "message": {
        "lang": "en-US",
        "value": "This request is not authorized to perform this operation using this permission.\nRequestId:6654c8d1-0002-0004-0a46-8c4598000000\nTime:2022-06-30T05:58:52.9808534Z"
      }
    }
  }
}

### Steps to Reproduce

1. Connect to a storage account.
2. Create a Table.
3. Try to delete it.

### Actual Experience

It gives Failure errors.

**Comment by MRayermannMSFT** [comment]
@novarun using the Azure portal, can you check what RBAC permissions you have for this table?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you're still running into this problem we recommend opening an Azure support ticket via the Azure Portal. Alternatively you can open a new issue here.
