### ISSUE TITLE
Unable to authenticate after successful sign-in Storage Acct

### ISSUE THREAD

**Issue by babyharidelo** [microsoft/AzureStorageExplorer#5893]
{
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"self signed certificate in certificate chain\\\",\\n  \\\"stack\\\": \\\"Error: self signed certificate in certificate chain\\\\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)\\\\n    at TLSSocket.emit (node:events:390:28)\\\\n    at TLSSocket._finishInit (node:_tls_wrap:944:8)\\\\n    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)\\\",\\n  \\\"code\\\": \\\"SELF_SIGNED_CERT_IN_CHAIN\\\"\\n}\""
}

**Comment by MRayermannMSFT** [comment]
@babyharidelo can you try using system proxy setting? You can read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you're still running into this problem we recommend opening an Azure support ticket via the Azure Portal. Alternatively you can open a new issue here.
