### ISSUE TITLE
Unable to expand Tables of the storage Account

### ISSUE THREAD

**Issue by JainRah** [microsoft/AzureStorageExplorer#5894]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.3

### Architecture

x64

### Platform

Windows

### Bug Description

Unable to retrieve child resources.

Details:
{
  "name": "RestError",
  "message": "{\"odata.error\":{\"code\":\"AuthorizationPermissionMismatch\",\"message\":{\"lang\":\"en-US\",\"value\":\"This request is not authorized to perform this operation using this permission.\\nRequestId:de11ad18-3002-0070-3e07-8d6698000000\\nTime:2022-07-01T04:57:07.7933096Z\"}}}",
  "stack": "RestError: {\"odata.error\":{\"code\":\"AuthorizationPermissionMismatch\",\"message\":{\"lang\":\"en-US\",\"value\":\"This request is not authorized to perform this operation using this permission.\\nRequestId:de11ad18-3002-0070-3e07-8d6698000000\\nTime:2022-07-01T04:57:07.7933096Z\"}}}\n    at handleErrorResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-client\\dist\\index.js:1264:19)\n    at deserializeResponseBody (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-client\\dist\\index.js:1199:45)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
  "statusCode": 403,
  "request": {
    "url": "https://expressroutebvtmain.table.core.windows.net/Tables",
    "headers": {
      "accept": "application/json;odata=minimalmetadata",
      "x-ms-version": "2019-02-02",
      "dataserviceversion": "3.0",
      "accept-encoding": "gzip,deflate",
      "user-agent": "Microsoft Azure Storage Explorer/1.24.3 (win32) azsdk-js-data-tables/13.1.1 core-rest-pipeline/1.8.0 Node/v16.13.2 OS/(ia32-Windows_NT-10.0.19044)",
      "x-ms-client-request-id": "21617933-f1ec-415e-b749-23741bbb8e2d",
      "authorization": "Bearer JSON Web Token Redacted"
    },
    "method": "GET",
    "timeout": 0,
    "disableKeepAlive": false,
    "streamResponseStatusCodes": {},
    "withCredentials": false,
    "tracingOptions": {
      "tracingContext": {
        "_contextMap": {}
      }
    },
    "requestId": "21617933-f1ec-415e-b749-23741bbb8e2d",
    "allowInsecureConnection": true,
    "enableBrowserStreams": false
  },
  "response": {
    "status": 403,
    "headers": {
      "cache-control": "no-cache",
      "transfer-encoding": "chunked",
      "content-type": "application/json;odata=minimalmetadata;streaming=true;charset=utf-8",
      "server": "Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0",
      "x-ms-request-id": "de11ad18-3002-0070-3e07-8d6698000000",
      "x-ms-client-request-id": "21617933-f1ec-415e-b749-23741bbb8e2d",
      "x-ms-version": "2019-02-02",
      "x-content-type-options": "nosniff",
      "date": "Fri, 01 Jul 2022 04:57:07 GMT"
    },
    "request": {
      "url": "https://expressroutebvtmain.table.core.windows.net/Tables",
      "headers": {
        "accept": "application/json;odata=minimalmetadata",
        "x-ms-version": "2019-02-02",
        "dataserviceversion": "3.0",
        "accept-encoding": "gzip,deflate",
        "user-agent": "Microsoft Azure Storage Explorer/1.24.3 (win32) azsdk-js-data-tables/13.1.1 core-rest-pipeline/1.8.0 Node/v16.13.2 OS/(ia32-Windows_NT-10.0.19044)",
        "x-ms-client-request-id": "21617933-f1ec-415e-b749-23741bbb8e2d",
        "authorization": "Bearer JSON Web Token Redacted"
      },
      "method": "GET",
      "timeout": 0,
      "disableKeepAlive": false,
      "streamResponseStatusCodes": {},
      "withCredentials": false,
      "tracingOptions": {
        "tracingContext": {
          "_contextMap": {}
        }
      },
      "requestId": "21617933-f1ec-415e-b749-23741bbb8e2d",
      "allowInsecureConnection": true,
      "enableBrowserStreams": false
    },
    "bodyAsText": "{\"odata.error\":{\"code\":\"AuthorizationPermissionMismatch\",\"message\":{\"lang\":\"en-US\",\"value\":\"This request is not authorized to perform this operation using this permission.\\nRequestId:de11ad18-3002-0070-3e07-8d6698000000\\nTime:2022-07-01T04:57:07.7933096Z\"}}}",
    "parsedBody": {
      "odataError": {
        "code": "AuthorizationPermissionMismatch",
        "message": {
          "lang": "en-US",
          "value": "This request is not authorized to perform this operation using this permission.\nRequestId:de11ad18-3002-0070-3e07-8d6698000000\nTime:2022-07-01T04:57:07.7933096Z"
        }
      }
    },
    "parsedHeaders": {
      "cache-control": "no-cache",
      "transfer-encoding": "chunked",
      "content-type": "application/json;odata=minimalmetadata;streaming=true;charset=utf-8",
      "server": "Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0",
      "x-ms-request-id": "de11ad18-3002-0070-3e07-8d6698000000",
      "x-ms-client-request-id": "21617933-f1ec-415e-b749-23741bbb8e2d",
      "x-ms-version": "2019-02-02",
      "x-content-type-options": "nosniff",
      "date": "Fri, 01 Jul 2022 04:57:07 GMT"
    }
  },
  "details": {
    "cache-control": "no-cache",
    "transfer-encoding": "chunked",
    "content-type": "application/json;odata=minimalmetadata;streaming=true;charset=utf-8",
    "server": "Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0",
    "x-ms-request-id": "de11ad18-3002-0070-3e07-8d6698000000",
    "x-ms-client-request-id": "21617933-f1ec-415e-b749-23741bbb8e2d",
    "x-ms-version": "2019-02-02",
    "x-content-type-options": "nosniff",
    "date": "Fri, 01 Jul 2022 04:57:07 GMT",
    "odataError": {
      "code": "AuthorizationPermissionMismatch",
      "message": {
        "lang": "en-US",
        "value": "This request is not authorized to perform this operation using this permission.\nRequestId:de11ad18-3002-0070-3e07-8d6698000000\nTime:2022-07-01T04:57:07.7933096Z"
      }
    }
  }
}

### Steps to Reproduce

1. Launch Explorer

### Actual Experience

Tables should be displayed

**Comment by MRayermannMSFT** [comment]
@JainRah, using the Azure portal, can you check what RBAC permissions you have for this table?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you're still running into this problem we recommend opening an Azure support ticket via the Azure Portal. Alternatively you can open a new issue here.
