### ISSUE TITLE
There is a prompt dialog when pasting one local emulator blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5900]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220705.1
**Branch**: main
**Platform/OS**: Windows 10
**How Found**: Regular testing
**Azurite Version**: 3.18.0
**Regression From**: Previous release (1.24.3)

## Steps to Reproduce ##
1. Install and run Azurite 3.18.0 -> Launch Storage Explorer.
2. Expand 'Emulator & Attached -> Storage Accounts -> (Emulator - Default Ports) (Key)'.
3. Create a blob container -> Right click the new created blob container.
4. Click 'Copy Blob Container' -> Right chick the 'Blob Containers' node.
5. Click 'Paste Blob Container'.
6. Check whether there is no prompt dialog.

## Expected Experience ##
There is no prompt dialog.

## Actual Experience ##
There is a prompt dialog.
![image](https://user-images.githubusercontent.com/41351993/177271758-c4672d1d-b2dc-45ba-9682-f897a1326bcf.png)

**Comment by JasonYeMSFT** [comment]
We also incorrectly show this prompt when copying an account SAS attached container to some storage account. Could you please help verify that scenario to make sure it doesn't prompt?

I will disable copy/paste from emulator containers or to emulator since it won't work due to emulator limitations.

**Comment by v-xianya** [comment]
@JasonYeMSFT The issue only reproduces when pasting one local emulator blob container.
Verified this issue on build # 20220705.1 #20220706.1
There is no prompt when pasting one account SAS attached container.
![0706](https://user-images.githubusercontent.com/41351993/177447871-fc252b94-a977-4822-bcad-a4478d8a2281.gif)

**Comment by JasonYeMSFT** [comment]
That meets my expectation. My fix will also stop the key attached account's container from giving such prompt.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220707.4. Fixed. so, we are going to close it.
1. The action 'Copy/Past Blob Container' has been disabled for Emulator blob container.
2. There is no prompt when pasting one key attached account's container.
