### ISSUE TITLE
The deleted table displays after manually refreshing Tables node if cloning the table then deleting the original table

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5901]
**Storage Explorer Version:** 1.25.0-dev
**Build Number:** 20220705.1
**Branch:** main
**Platform/OS:** Windows 10
**Architecture:** ia32
**Azurite Version:** 3.18.0
**How Found:** Ad-hoc testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Install and run Azurite 3.18.0 -> Launch Storage Explorer.
2. Expand 'Emulator & Attached -> Storage Accounts -> (Emulator - Default Ports) (Key)' -> Tables.
3. Create a table named 'test' -> Right click the new created table -> Click 'Clone...'.
4. Type 'test123' to the 'New name' field -> Click 'Clone' -> The cloned table displays.
5. Delete table 'test' -> The deleted table disappears.
6. Refresh Tables node.
7. Check whether the deleted table 'test' doesn't display and the cloned table 'test123' displays.

## Expected Experience ##

1. The deleted table 'test' doesn't display.
2. The cloned table 'test123' displays.

## Actual Experience ##

1. The deleted table 'test' displays.
2. The cloned table 'test123' doesn't display.

## Additional Context ##
This issue only reproduces when the original table name is same as the first few characters of the cloned table name.

**Comment by craxal** [comment]
Yet another problem with Azurite and not Storage Explorer. See https://github.com/Azure/Azurite/issues/1584.

**Comment by craxal** [comment]
@v-kellyluo This appears to be fixed as of Azurite 3.19.0.

**Comment by v-kellyluo** [comment]
Verified this this issue after installing Azurite 3.19.0. Fixed.
