### ISSUE TITLE
Batch Update Access Tier

### ISSUE THREAD

**Issue by NickBrooks** [microsoft/AzureStorageExplorer#591]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows Home 17134.228
**Architecture**: ia32

I've uploaded a large batch of files into my Blob Container which I would like to batch Archive. I can only do this one by one.

### Updating access tier individually works fine

![individual](https://user-images.githubusercontent.com/4286755/44377432-f8826400-a4b9-11e8-912e-2d79297cb628.JPG)

### Batch access tier update is blanked out

![batch](https://user-images.githubusercontent.com/4286755/44377431-f7513700-a4b9-11e8-828b-fe5dc2e6e6b3.JPG)

**Comment by JasonSandwich** [comment]
Agreed.  This would be extremely helpful.

**Comment by Rafe-Smith** [comment]
Right click context menu for Change Access Tier at virtual folder level and blob container level too.

**Comment by jensf** [comment]
in addition, Change Access Tier for a directory (which would batch change all contents) as well.
