### ISSUE TITLE
There is a prompt info bar if refreshing the emulator blob container explorer when transferring page/append blobs

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5912]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220707.4
**Branch**: main
**Platform/OS**: Windows 10
**Architecture**: ia32
**Azurite Version** 3.18.0
**How Found**: Ad-hoc testing
**Regression From**: Previous release (1.24.3)

## Steps to Reproduce ##
1. Install and run Azurite 3.18.0 -> Expand 'Emulator & Attached -> Storage Accounts -> (Emulator - Default Ports) (Key)'.
2. Create a blob container -> Upload one large blob.
3. Refresh the blob container explorer when transferring.
4. Check whether there is no prompt info bar.

## Expected Experience ##
There is no prompt info bar.
## Actual Experience ##
There is a prompt info bar.
`The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined`
![image](https://user-images.githubusercontent.com/41351993/177726474-9f281eee-197d-47a6-a4ca-f7856a9693ec.png)

## Additional Context ##
This issue doesn't reproduce for regular/HNS blob container.

**Comment by v-xianya** [comment]
@JasonYeMSFT 
Verified this issue on the latest build. This issue reproduces if uploading 'Page/Append blobs'.

Here is the log: [log.txt](https://github.com/microsoft/AzureStorageExplorer/files/9068415/log.txt)

**Comment by JasonYeMSFT** [comment]
I have reproduced the error and I think I know why it occurs. I have filed an Azurite bug for this issue.
https://github.com/Azure/Azurite/issues/1592
