### ISSUE TITLE
It would be better to add '...' next to the dropdown actions 'Export Selected/Export All' for tables

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5913]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220707.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Click the dropdown arrow of the 'Export'.
3. Observe whether there is '...' next to the dropdown actions.

## Expected Experience ##
It would be better to add '...' next to the dropdown actions.

## Actual Experience ##
There is no '...' next to the dropdown actions.
![image](https://user-images.githubusercontent.com/41351993/177744232-2534d438-13fd-45e7-bfcf-44787fa6de82.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220712.2. Fixed.
![image](https://user-images.githubusercontent.com/87792676/178395891-58a29313-8d9f-45f8-9304-cd7a167b7f8c.png)
