### ISSUE TITLE
Update the subtitle 'Add Entity' to 'Edit Property Value' if clicking 'Edit property' on 'Add Entity' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5915]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220708.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.24.3)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Click 'Add' -> Click 'Add Property' -> Click 'Edit property'.
3. Observe the opened dialog.
4. Check whether the subtitle is 'Edit Property Value' or not.

## Expected Experience ##
The subtitle is 'Edit Property Value'.
![image](https://user-images.githubusercontent.com/41351993/177941790-9ef2ca7b-1ac3-4bee-b7e2-349869aa26bc.png)

## Actual Experience ##
The subtitle is 'Add Entity'.
![image](https://user-images.githubusercontent.com/41351993/177942068-536228c7-3a03-44eb-a063-8f9e5989aa15.png)

## Additional Context ##
This issue also reproduces when editing property on 'Edit Entity' dialog.
![image](https://user-images.githubusercontent.com/41351993/177942449-b16625f0-ccd5-4345-a91b-5fb24f7409dd.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220712.2. Fixed.
