### ISSUE TITLE
It would be better to update the default property type to 'Binary'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5916]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220708.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.24.3)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Open one table -> Click 'Add' -> Click 'Add Property'.
3. Check whether the default property type is 'Binary'.

## Expected Experience ##
The default property type is 'Binary'.
![image](https://user-images.githubusercontent.com/41351993/177948961-479a025a-7086-4f94-ad62-3cf1c393568e.png)

## Actual Experience ##
The default property type is 'String'.
![image](https://user-images.githubusercontent.com/41351993/177948805-fd37b3e5-c2fe-489b-afbd-afbe4ec91580.png)

## Additional Context ##
The type 'String' is the last one on the dropdown list.

**Comment by craxal** [comment]
@v-xianya I disagree. Binary types are not used very often. String values, by contrast, are very common and much more flexible and permissive in the values they can hold. Plus, the types are merely in alphabetical order; there isn't really an issue with defaulting to a value lower in the list.
