### ISSUE TITLE
Cannot log in the Blob System

### ISSUE THREAD

**Issue by AnaHdez9650** [microsoft/AzureStorageExplorer#5917]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.3

### Architecture

i86

### Platform

Windows

### Bug Description

No se pueden recuperar los recursos secundarios.

Detalles:
{
  "name": "FetchError",
  "message": "request to https://supittprdemsdatajabil01.blob.core.windows.net/?comp=list&include=metadata failed, reason: unable to get local issuer certificate",
  "stack": "FetchError: request to https://supittprdemsdatajabil01.blob.core.windows.net/?comp=list&include=metadata failed, reason: unable to get local issuer certificate\n    at ClientRequest.<anonymous> (C:\\Users\\3309650\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1491:11)\n    at ClientRequest.emit (node:events:390:28)\n    at TLSSocket.socketErrorListener (node:_http_client:447:9)\n    at TLSSocket.emit (node:events:390:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY",
  "code": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"
}

### Steps to Reproduce

Launch storage explorer

### Actual Experience

Cannot log in some items in the blob system

**Comment by MRayermannMSFT** [comment]
@AnaHdez9650 can you try using system proxy setting? You can read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you're still running into this problem we recommend opening an Azure support ticket via the Azure Portal. Alternatively you can open a new issue here.
