### ISSUE TITLE
Unable to import entity without a partition key and row key.

### ISSUE THREAD

**Issue by venkatx5** [microsoft/AzureStorageExplorer#5918]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.22.0

### Architecture

x64

### Storage Explorer Build Number

20211211.10

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Tried to import CSV with PartitionKey, RowKey field and 3 other string fields. 

### Steps to Reproduce

1. Launch Storage explorer.
2. Create CSV file with Partitionkey, RowKey, Field1 (String), Field2 (String, Field3 (Double). Keep few dummy records
3. Create a test table on storage account.
4. Import the csv data.

### Actual Experience

Unable to import entity without a partition key and row key.

Error details:

{
  "name": "Error",
  "message": "Unable to convert working entity to SDK entity without partition and row keys.",
  "stack": "Error: Unable to convert working entity to SDK entity without partition and row keys.\n    at convertWorkingEntityParamToSdkEntityParam (C:\\Users\\VR\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-table-extension\\dist\\src\\Common\\SdkEntity.js:89:15)\n    at ImportBatchState.#getEntity (C:\\Users\\VR\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-table-extension\\dist\\src\\Jobs\\ImportEntities\\States\\ImportBatchState.js:106:74)\n    at ImportBatchState.doUpdate (C:\\Users\\VR\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-table-extension\\dist\\src\\Jobs\\ImportEntities\\States\\ImportBatchState.js:51:41)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async ImportBatchState.update (C:\\Users\\VR\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-table-extension\\dist\\src\\Jobs\\ImportEntities\\States\\State.js:21:13)\n    at async ImportEntitiesContext.run (C:\\Users\\VR\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-table-extension\\dist\\src\\Jobs\\ImportEntities\\ImportEntitiesContext.js:59:33)\n    at async ImportEntitiesJobHandler.handleJob (C:\\Users\\VR\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-table-extension\\dist\\src\\Jobs\\ImportEntities\\ImportEntitiesJobHandler.js:19:13)\n    at async Provider.executeOperation (C:\\Users\\VR\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\providers\\Provider.js:27:16)\n    at async NodeProcessHostProxy._handleExecuteRequest (C:\\Users\\VR\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:217:31)\n    at async NodeProcessHostProxy._handleMessage (C:\\Users\\VR\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:171:24)"
}

### Expected Experience

The CSV rows should get imported on storage table.

### Additional Context

I tried on latest version 1.24.3 and got the error. So downgraded to 122.0. But the error is same.

**Comment by MRayermannMSFT** [comment]
@venkatx5 did you create the CSV file in Excel, and if so did you save as CSV UTF-8 or just CSV?
![image](https://user-images.githubusercontent.com/21112697/178325581-4f31f4c2-fe6b-4377-9ab0-d3900457f87b.png)

If you don't remember, can you try explicitly save as just CSV?
![image](https://user-images.githubusercontent.com/21112697/178325672-8b7cff39-8d52-4d40-b6c2-cb81499ea944.png)

**Comment by venkatx5** [comment]
@MRayermannMSFT I initially saved on CSV UTF-8 format.
Now I just tried as "Comma Separated Values (.csv)" and the file went thru. The import works fine. 
Thanks a lot for the solution.

**Comment by craxal** [comment]
@venkatx5 Thanks for letting us know! And so you know, we've made some improvements such that Storage Explorer will be able to handle this format. These changes will be available in 1.25.0.

**Comment by craxal** [comment]
Duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/5843.
