### ISSUE TITLE
An error dialog pops up when opening one service by using its direct link at the first time

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5919]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220711.1
**Branch**: main
**Platform/OS**: Windows 10/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.24.3)

## Steps to Reproduce ##
1. Launch Storage Explorer -> Expand one storage account -> Blob Containers.
2. Select one blob container -> Right click the blob container -> Click 'Copy Direct Link to Blob Container'.
3. Open the direct link from the Browser.
4. Check whether no error dialog pops up.

## Expected Experience ##
No error dialog pops up.

## Actual Experience ##
An error dialog pops up.
![image](https://user-images.githubusercontent.com/41351993/178210510-6489043e-4654-480a-8b53-517a026a6686.png)

## Additional Context ##
1. On mac. the same error dialog pops up when launching storage explorer.
2. This issue only reproduces when executing the 'open direct link' action at the first time.
3. This issue doesn't reproduce for one ADLS Gen2 blob container.

**Comment by MRayermannMSFT** [comment]
@v-xianya I'm having a hard time reproducing this? Can you please set the storage explorer log level to debug, repro the issue, and share the logs with me? Thanks!

**Comment by v-xianya** [comment]
@MRayermannMSFT Somehow, we failed to reproduce this issue on the build #20220711.1, #20220712.2.😶

**Comment by MRayermannMSFT** [comment]
@v-xianya Ok. 🤷‍♀️If it happens again, please share the debug logs!

**Comment by v-xianya** [comment]
@MRayermannMSFT Ok, will do.
