### ISSUE TITLE
The little arrow for the 'Undelete' action is disabled on one blob container's toolbar

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5920]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220711.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Open one blob container -> Observe its toolbar.
3. Check whether the little arrow for the 'Undelete' action is enabled or not.

## Expected Experience ##
The little arrow for the 'Undelete' action is enabled.

## Actual Experience ##
The little arrow for the 'Undelete' action is disabled.
![image](https://user-images.githubusercontent.com/41351993/178211741-819651ab-79c7-4237-93df-b254313f0b34.png)

**Comment by v-xianya** [comment]
@JasonYeMSFT The arrow icon for the 'Move Messages' is always enabled.
Refer to the comments: https://github.com/microsoft/AzureStorageExplorer/issues/5892#issuecomment-1176570547
![image](https://user-images.githubusercontent.com/41351993/178386456-0488d85c-9b62-4a1d-8a66-d4a548ddcb6e.png)

**Comment by v-xianya** [comment]
@JasonYeMSFT Verified this issue on the build main/20220713.1.
1. This issue has been fixed for regular blob containers.
2. This issue **reproduces** for ADLS Gen2 blob containers.

**Comment by JasonYeMSFT** [comment]
Sorry, I forgot that one. I merged a similar fix for the Gen2 undelete commands.
