### ISSUE TITLE
Unable to retrieve child resources.

### ISSUE THREAD

**Issue by chetana-cloud** [microsoft/AzureStorageExplorer#5922]
Details:
{
  "name": "FetchError",
  "message": "request to https://stgreltmineu001.blob.core.windows.net/?comp=list&include=metadata failed, reason: unable to get local issuer certificate",
  "stack": "FetchError: request to https://stgreltmineu001.blob.core.windows.net/?comp=list&include=metadata failed, reason: unable to get local issuer certificate\n    at ClientRequest.<anonymous> (C:\\Users\\cc\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1491:11)\n    at ClientRequest.emit (node:events:390:28)\n    at TLSSocket.socketErrorListener (node:_http_client:447:9)\n    at TLSSocket.emit (node:events:390:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY",
  "code": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"
}

**Comment by MRayermannMSFT** [comment]
@chetana-cloud can you try using system proxy setting? You can read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you're still running into this problem we recommend opening an Azure support ticket via the Azure Portal. Alternatively you can open a new issue here.
