### ISSUE TITLE
can not see the data

### ISSUE THREAD

**Issue by Conguyen12** [microsoft/AzureStorageExplorer#5923]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.3

### Architecture

i86

### Platform

Windows

### Bug Description

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://supittprdemsdatajabil01.file.core.windows.net/?comp=list failed, reason: unable to get local issuer certificate",
  "stack": "FetchError: request to https://supittprdemsdatajabil01.file.core.windows.net/?comp=list failed, reason: unable to get local issuer certificate\n    at ClientRequest.<anonymous> (C:\\Users\\nguyenc16\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:111224)\n    at ClientRequest.emit (node:events:390:28)\n    at TLSSocket.socketErrorListener (node:_http_client:447:9)\n    at TLSSocket.emit (node:events:390:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY",
  "code": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"
}

### Steps to Reproduce

1. Launch storage explorer

### Actual Experience

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://supittprdemsdatajabil01.file.core.windows.net/?comp=list failed, reason: unable to get local issuer certificate",
  "stack": "FetchError: request to https://supittprdemsdatajabil01.file.core.windows.net/?comp=list failed, reason: unable to get local issuer certificate\n    at ClientRequest.<anonymous> (C:\\Users\\nguyenc16\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:111224)\n    at ClientRequest.emit (node:events:390:28)\n    at TLSSocket.socketErrorListener (node:_http_client:447:9)\n    at TLSSocket.emit (node:events:390:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY",
  "code": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"
}

### Expected Experience

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://supittprdemsdatajabil01.file.core.windows.net/?comp=list failed, reason: unable to get local issuer certificate",
  "stack": "FetchError: request to https://supittprdemsdatajabil01.file.core.windows.net/?comp=list failed, reason: unable to get local issuer certificate\n    at ClientRequest.<anonymous> (C:\\Users\\nguyenc16\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:111224)\n    at ClientRequest.emit (node:events:390:28)\n    at TLSSocket.socketErrorListener (node:_http_client:447:9)\n    at TLSSocket.emit (node:events:390:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY",
  "code": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"
}

**Comment by MRayermannMSFT** [comment]
@Conguyen12 can you try using system proxy setting? You can read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem we recommend opening a support ticket via the Azure Portal. Alternatively you can open a new issue here. Thanks.

**Comment by Conguyen12** [comment]
Hi Matthew Rayermann

The issue is still happening, Can I book a meeting with you by MS team? please provide your suitable time.
[cid:278a83a6-7553-410e-9c25-60d5bbee0e37]

Thank and best regards

Co Nguyen
QE Lead

Cell:+84 <tel:%2B84%2093%20275%204422> 909088246

JABIL VIETNAM COMPANY LIMITED
Lot I8-1, Saigon Hi-Tech Park, Tan Phu Ward,
Thu Duc City , Ho Chi Minh City, Vietnam

________________________________
