### ISSUE TITLE
It would be better to add '...' next to the action 'Download' for blobs/files

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5924]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220712.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Right click the blob -> Observe the context menu.
4. Check whether there is '...' next to the action 'Download'.

## Expected Experience ##
It would be better to add '...' next to the action 'Download'.

## Actual Experience ##
There is no '...' next to the action 'Download'.
![image](https://user-images.githubusercontent.com/41351993/178440660-9e23e5b1-e754-4487-9d84-b4f5a59f86f9.png)

## Additional Context ##
There is '...' next to the action 'Download' for disks.
![image](https://user-images.githubusercontent.com/41351993/178440802-965575b7-bad8-4dfb-8fe4-442f022058c8.png)

**Comment by v-xianya** [comment]
Verified this issue on the build main 20220829.1.
1. This issue is fixed for regular blobs.
![image](https://user-images.githubusercontent.com/41351993/187115791-e5e71e47-bd91-499d-bf89-494311e1e888.png)

2. This issue still reproduces for files & ADLS Gen2 blobs.

**Comment by MRayermannMSFT** [comment]
Added it for gen2 as well.

**Comment by v-xianya** [comment]
@MRayermannMSFT 
Verified this issue on the build main/20220923.3. 
1. Fixed for ADLS Gen2 blob container.
![image](https://user-images.githubusercontent.com/41351993/191882353-8f0c247b-07f9-4db1-85a7-d75eaad3204e.png)
2. For items in one file share, still no '...' next to 'Download'. So, we are going to reopen this issue.
![image](https://user-images.githubusercontent.com/41351993/191882477-c312ac38-dd51-417f-b592-ceeb46fac6b3.png)

**Comment by MRayermannMSFT** [comment]
Thanks for pointing that out. Missed that you also said files needed it. That is now merged too.

**Comment by v-xianya** [comment]
Verified this issue on the build 20220926.1. Fixed.
![image](https://user-images.githubusercontent.com/41351993/192181502-0f2f1eaa-7290-440e-b54c-3908534313f7.png)
