### ISSUE TITLE
The tab is not auto closed after detaching one broken Azure AD attached blob container/queue

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5925]
**Storage Explorer Version:** 1.25.0-dev
**Build Number:** 20220712.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** Ad-hoc testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Azure AD attach the blob container.
3. The attached blob container auto opens.
4. Go to the ACCOUNT MANAGEMENT panel -> Remove the associated account.
5. Switch to EXPLORER panel.
6. Right click the broken Azure AD attached blob container -> Click 'Detach' 
7. Check whether the opened tab is auto closed.

## Expected Experience ##
The opened tab is auto closed.

## Actual Experience ##
The opened tab is not closed.

## Additional Context ##

1. This issue also reproduces for ADLS Gen2 blob containers/queues.
2. This issue doesn't reproduce for tables.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20221030.2. Fixed. So, we are going to close it.
