### ISSUE TITLE
Add support for Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by rickrain** [microsoft/AzureStorageExplorer#5926]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

There is no support for Ubuntu 22.04 LTS

### Desired Solution

Support for Ubuntu 22.04 LTS

### Additional Context

The docs [here](https://docs.microsoft.com/en-us/azure/vs-azure-tools-storage-manage-with-storage-explorer?tabs=linux#prerequisites) suggests that this is not available for Ubuntu 22.04.  However, 22.04 LTS has been out for about 3 months.

**Comment by MRayermannMSFT** [comment]
@rickrain thanks for opening this issue. We're in the process of verifying Storage Explorer working with 22.04. Have you ran into any issues with Storage Explorer on 22.04?

**Comment by rickrain** [comment]
No issues.

**Comment by MRayermannMSFT** [comment]
We've updated our docs to indicated that 22.04 is ok.
