### ISSUE TITLE
error connecting from company laptop

### ISSUE THREAD

**Issue by prasadvaze** [microsoft/AzureStorageExplorer#5927]
i am using storage explorer from company laptop and network. I am able to auth successfully to my company azure subscription but then it does not show storage accounts , instead gives below error
{
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"unable to get local issuer certificate\\\",\\n  \\\"stack\\\": \\\"Error: unable to get local issuer certificate\\\\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)\\\\n    at TLSSocket.emit (node:events:390:28)\\\\n    at TLSSocket._finishInit (node:_tls_wrap:944:8)\\\\n    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)\\\",\\n  \\\"code\\\": \\\"UNABLE_TO_GET_ISSUER_CERT_LOCALLY\\\"\\n}\""
}

**Comment by MRayermannMSFT** [comment]
@prasadvaze can you try using system proxy setting? You can read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem we recommend opening a support ticket via the Azure Portal. Alternatively you can open a new issue here. Thanks.
