### ISSUE TITLE
Shows a blank display name after pasting the connection string of one Germany account

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#593]
**Storage Explorer Version**:1.4.1
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture**:ia32/x64
**Build Number**:20180820.1
**Commit**:bbb595d2
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Sign in with one Germany account.
2. Create a SAS connection string for one account like below.
   ```
   AccountName=cawatest03;
   SharedAccessSignature=sv=2018-03-28&ss=bfqt&srt=sco&sp=rwdlacup&st=2018-08-21T10%3A04%3A12Z&se=2018-08-22T10%3A04%3A12Z&sig=uGGtL5jl9l99AYJxqV9d4T3AM7ABnindrz%2Fd%2FE5gphg%3D;
   BlobEndpoint=https://cawatest03.blob.core.cloudapi.de/;
   FileEndpoint=https://cawatest03.file.core.cloudapi.de/;QueueEndpoint=https://cawatest03.queue.core.cloudapi.de/;
   TableEndpoint=https://cawatest03.table.core.cloudapi.de/;
   ```
3. Open Connect dialog and pasting the created connection string -> Check whether the default account name auto shows under 'Display name' or not.

#### Expected Experience: ####
The default account name auto shows under 'Display name'.

#### Actual Experience: ####
Display a blank display name under 'Display name'.
![blank](https://user-images.githubusercontent.com/34729022/44396291-f6f18400-a52b-11e8-9393-92f6869d8254.png)

**Comment by craxal** [comment]
By design. We only auto-fill the display name if the connection string has an `AccountName` value.

**Comment by MRayermannMSFT** [comment]
I'm calling shenanigans on that @craxal . We auto fill the name for a public Azure SAS URI. I don't think this needs to be in 1.4.1, but I'm going to put it in 1.5.0.

**Comment by craxal** [comment]
Oh, whoops, you're right. Had to take a closer look at the code.

**Comment by v-xuanzh** [comment]
This issue also reproduces on the latest master build 20190813.3.

**Comment by craxal** [comment]
@v-xianya I am unable to reproduce this bug on main branch. Can you verify whether this reproduces on your end? If so, please provide more information that may be helpful.

**Comment by v-xianya** [comment]
@craxal Verified this issue on build main/20201201.2. Reproduce. The record please see the below.
![capture](https://user-images.githubusercontent.com/41351993/100689899-594eb580-33c0-11eb-89ec-58bfb19a32c4.gif)
