### ISSUE TITLE
{   "message": "\"UnexpectedCancel\"" }

### ISSUE THREAD

**Issue by kiran021993** [microsoft/AzureStorageExplorer#5933]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19

### Architecture

x64

### Platform

Windows

### OS Version

windows10

### Bug Description

new error

### Steps to Reproduce

error

### Actual Experience

3years

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem we recommend opening a support ticket via the Azure Portal. Alternatively you can open a new issue here. Thanks.
