### ISSUE TITLE
Extra 'Load more' displays under 'Storage Accounts' node after applying more than 3 subscriptions

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#594]
**Storage Explorer Version**:1.4.1
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture**:ia32/x64
**Build Number**:20180820.1
**Commit**:bbb595d2
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Sign in with one account and apply more than 3 subscriptions.
2. Expand **'Local & Attached'** -> **Storage Accounts.**
3. Check whether the 'Load more' displays or not.

#### Expected Experience: ####
No 'Load more' link displays under 'Storage Accounts' node.

#### Actual Experience: ####
Extra 'Load more' link displays under 'Storage Accounts' node.
![loadmore](https://user-images.githubusercontent.com/34729022/44395578-d4f70200-a529-11e8-93e9-5726feb0c38a.png)

**Comment by craxal** [comment]
Odd, but it shouldn't be blocking. Please add several account SAS connections. Do they all show up and are they still functional?

**Comment by v-xuanzh** [comment]
Hi @craxal , there is no attached account with SAS connection. I just applied multiple subscriptions then expanded the **'Local & Attached'** -> **Storage Accounts** directly on th tree view.

**Comment by craxal** [comment]
@v-xuanzh, I am aware that this involves subscriptions. But I want to verify that SAS attachments still show up despite this error, if not, we need to fix this ASAP. If yes, we don't need to worry about it for 1.4.1.

**Comment by craxal** [comment]
Also, I'm unable to reproduce with the current code (commit 14ea2643). I signed into my Azure account and selected 4-5 subscriptions, and no **Load More** button appears under the local storage accounts node.

**Comment by v-xuanzh** [comment]
Does it reproduces after Refreshing All?
Because this issue still reproduces in my side with the same configuration(commit 14ea2643).

**Comment by craxal** [comment]
I've tried refreshing, and I still get nothing. If customers start complaining, or if we find more precise repro steps, we'll reopen.
