### ISSUE TITLE
The action 'Reset Column Order' doesn't take effect for tables

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#5943]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220719.8
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.24.3)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Add one entity.
3. Change the column order -> Right click one column -> Click 'Reset Column Order'.
4. Check whether the column order is reset or not.

## Expected Experience ##
The column order is reset.
## Actual Experience ##
The column order is not reset.

## Additional Context ##
The column order is not reset after refreshing the editor.

**Comment by craxal** [comment]
Mistyped command ID was used, and so the reset command wasn't actually running.
