### ISSUE TITLE
The column order on the 'Column Options' dialog is not changed if changing the column order on the table

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5944]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220719.8
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.24.3)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Add one entity.
3. Change the column order -> Click 'Column Options'.
4. Check whether the column order on the 'Column Options' dialog is changed.

## Expected Experience ##
The column order on the 'Column Options' dialog is changed.
![image](https://user-images.githubusercontent.com/41351993/179705291-88342941-e996-428f-8717-be2968e7a1e9.png)

## Actual Experience ##
The column order on the 'Column Options' dialog is not changed.
![image](https://user-images.githubusercontent.com/41351993/179705599-c2fc7af6-60de-47f4-a099-235464f7d83d.png)

**Comment by craxal** [comment]
This was in part due to the fact we don't get notified about column order changes via drag. This can be solved by getting the column order from the data table component and mapping the indices to "column manager indices".

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220721.9. Fixed. So, we are going to close it.
