### ISSUE TITLE
Blob Container Access using Azure AD and RBAC - The request is not authorized to perform this operation using this permission

### ISSUE THREAD

**Issue by dfaivre-pcs** [microsoft/AzureStorageExplorer#5945]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.3

### Architecture

x64

### Storage Explorer Build Number

20220617.2

### Platform

Windows

### OS Version

Windows 10

### Bug Description

I have a storage account that is set to use only Azure AD authentication/access (no keys, SAS). In the portal storage browser, I have access to the container and can list its contents. In the desktop Storage Explorer, I get access denied.

My guess is that I'm missing something simple, but my Google searches have not been successful.

Log snippet:
```
[2022-07-19T17:01:00.921Z] (se-blob-extension:13500) <WARN> Fallback for operation 'BlobContainerClient.listBlobsSegment, count 1
[2022-07-19T17:04:17.551Z] (se-blob-extension:13500) <ERRO> API call for BlobContainerClient.listBlobsSegment failed
  GET https://pludeployst01.blob.core.windows.net/deploy-ids?comp=list&maxresults=1000&restype=container&include=metadata&delimiter=%2F - 403
  Credential used: Auth token - accountId: 26f2...b.d08...e4-5...d:9...C, tenantId: d...d
  RequestId: 8a66772b-b66d-4859-9378-b32539e231fe, Date sent: Tue, 19 Jul 2022 17:04:18 GMT, ApiVersion: 2020-10-02, ProxySettings: undefined
  ErrorCode: AuthorizationPermissionMismatch
```

### Steps to Reproduce

1. Create a storage account with [Shared Key authorization disabled](https://docs.microsoft.com/en-us/azure/storage/common/shared-key-authorization-prevent?tabs=portal)
2. Ensure your user has Blob Data Owner access to the container
3. Ensure that your user can fully access the container data in the portal
4. Open Storage Explorer, using the same Azure AD credentials
5. Try to view/modify the container data

### Actual Experience

Access is denied

![image](https://user-images.githubusercontent.com/28011906/179810590-357e4699-efbf-4c39-ab15-29c22bd7e2f7.png)

### Expected Experience

Access to be allowed

**Comment by JasonYeMSFT** [comment]
It might take a while for the rbac roles to be propagated among the data centers. Does this keep happening even after long enough? If so, could you share the request ID with us so we can ask someone for help to see what goes wrong?

**Comment by dfaivre-pcs** [comment]
@JasonYeMSFT  - that was it! Sorry, I was confused since the portal seems to have picked up the RBAC permissions quicker. Thank you so much for taking the time to point me in the right direction.
