### ISSUE TITLE
 can not access resources for this tenant

### ISSUE THREAD

**Issue by JamesJia666** [microsoft/AzureStorageExplorer#5946]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.3

### Regression From

1.24.3

### Architecture

x64

### Storage Explorer Build Number

20220617.2

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Could not access resources for this tenant. You may need to reauthenticate. See the error details for more information.

{
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"connect ECONNREFUSED 51.116.156.32:443\\\",\\n  \\\"stack\\\": \\\"Error: connect ECONNREFUSED 51.116.156.32:443\\\\n    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)\\\\n    at __node_internal_exceptionWithHostPort (node:internal/errors:642:12)\\\\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)\\\",\\n  \\\"errno\\\": -4078,\\n  \\\"code\\\": \\\"ECONNREFUSED\\\",\\n  \\\"syscall\\\": \\\"connect\\\",\\n  \\\"address\\\": \\\"51.116.156.32\\\",\\n  \\\"port\\\": 443\\n}\""
}

### Steps to Reproduce

1. get the right of Azure Storage
2. Reauthenticate
3. still can not access the resource of subscription

### Actual Experience

Can not access the resource of subscription through I have the right of this software and I have also reautheticated, but did not work.

**Comment by MRayermannMSFT** [comment]
@JamesJia666 can you try using system proxy setting? You can read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue, we recommend opening a support ticket via the Azure portal. Alternatively you can open a new issue here.
