### ISSUE TITLE
An error 'Invalid initialization vector' occurs when launching Storage Explorer

### ISSUE THREAD

**Issue by v-kellyluo** [Microsoft/AzureStorageExplorer#5948]
**Storage Explorer Version:** 1.25.0-dev
**Build Number:** 20220719.17
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.24.3)

## Bug Description ##

1. An error occurs when launching Storage Explorer.
2. An error occurs when executing 'Pin to Quick Access' action.
3. An error occurs when clicking 'Refresh All'.

## Steps to Reproduce ##

1. Launch Storage Explorer.
2. Check whether no error occurs.

## Expected Experience ##
No error occurs.

## Actual Experience ##
An error 'Invalid initialization vector' occurs.
![image](https://user-images.githubusercontent.com/87792676/179931150-1d1761c1-53e6-4119-a6af-5cfd65946b33.png)

**Comment by v-xianya** [comment]
Verified this issue on the build main 20220721.9. Fixed. So, we are going to close it.
