### ISSUE TITLE
The access tier value for page blobs displays empty under one Premium storage account

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5949]
**Storage Explorer Version:** 1.25.0-dev
**Build Number:** 20220719.17
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.24.3)

## Steps to Reproduce ##

1. Expand one Premium storage account -> Blob Containers.
2. Create a blob container -> Upload a page blob.
3. Check whether the access tier value displays as 'P10 (inferred)'.

 
## Expected Experience ##
 The access tier value displays as 'P10 (inferred).
![image](https://user-images.githubusercontent.com/87792676/179932999-6eea0ea0-07ee-4ac1-a24b-b5f25fce68d2.png)

## Actual Experience ##
The access tier value displays empty.
![image](https://user-images.githubusercontent.com/87792676/179932629-10c6b67e-ff9c-4115-aa43-7161efada314.png)

## Additional Context ##
The access tier value is 'P10' on the Properties dialog.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20220721.9. Fixed. So, we are going to close it.
