### ISSUE TITLE
No response after configuring soft delete with Azurite

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#595]
**Storage Explorer Version**:1.4.1
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture**:ia32/x64
**Build Number**:20180820.1
**Commit**:bbb595d2
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Launch Storage Explorer and install Azurite.
2. Open Connect dialog then attach to a local emulator.
3. Expand **'Local & Attached'** -> **Storage Accounts** -> The attached local emulator.
4. Right click Blob Containers node and select 'Configure Soft Delete Policy...'.

#### Expected Experience: ####
The 'Configure Soft Delete Policy' dialog pops up.

#### Actual Experience: ####
No response after clicking 'Configure Soft Delete Policy...'.

#### More info: ####
1. This issue also reproduces after clicking 'Configure CORS Settings...' for Blob Containers.
2. This issue doesn't reproduce after starting storage emulator.
3. Display the below error dialog after click 'Configuring CORS Settings...' for Queues/Tables.
![error](https://user-images.githubusercontent.com/34729022/44395136-74b39080-a528-11e8-8d6f-f96b18009548.png)

**Comment by craxal** [comment]
It's likely Azurite has not implemented soft delete features. Do any errors appear in the console?
