### ISSUE TITLE
The value of each service endpoint displays empty on the Properties panel for one Name & Key attached storage account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5950]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220719.17
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.24.3)

## Steps to Reproduce ##
1. Select one storage account -> Right click the storage account.
2. Click 'Copy Primary Key' -> Open the connect dialog.
3. Attach the storage account via Account name and key.
4. Select the attached storage account -> Observe its Properties panel.
5. Check whether the value of each service endpoint displays well.

## Expected Experience ##
The value of each service endpoint displays well.

## Actual Experience ##
The value of each service endpoint displays empty.
![image](https://user-images.githubusercontent.com/41351993/179939652-aadc9f5c-a069-4500-aa5b-698cf4c71155.png)

## Additional Context ##
1. Here is the screenshot for the original storage account:
![image](https://user-images.githubusercontent.com/41351993/179937191-ef7ffa4e-3dcc-4976-806c-10aeddb7b4e3.png)
2. Here is the screenshot on the previous release (1.24.3):
![image](https://user-images.githubusercontent.com/41351993/179938919-658f9bf8-ba8b-41d0-8327-168fffaed0a4.png)

**Comment by MRayermannMSFT** [comment]
Hi @v-xianya I have merged a fix which hides the empty endpoints for name & key attached accounts.

**Comment by v-xianya** [comment]
Verified this issue on the build 20220722.2. Fixed.
The service endpoint has been hidden for name & key attached accounts.
