### ISSUE TITLE
The red border is incomplete for property name field against entities

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5953]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220721.9
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.24.3)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Click 'Add' -> Click 'Add Property'.
3. There is a red border on the property name field.
4. Check whether the red border is complete.

## Expected Experience ##
The red border is complete.

## Actual Experience ##
The red border is incomplete.

![image](https://user-images.githubusercontent.com/41351993/180164454-8f86cc76-60ea-41fc-a9a6-11e798841e59.png)

## Additional Context ##
This issue doesn't reproduce for property value field.
![image](https://user-images.githubusercontent.com/41351993/180165070-8dc23141-168a-4221-a6e8-72ff1f1cde40.png)

**Comment by craxal** [comment]
@v-xianya This is a known issue. It is a result of addressing #5555.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220725.3. Fixed.
![image](https://user-images.githubusercontent.com/41351993/180904921-c76beb0a-aab4-40ed-bbc7-dadc7745435c.png)
