### ISSUE TITLE
FilterBlob request sent upon opening blob container without user operation

### ISSUE THREAD

**Issue by taiyokato** [microsoft/AzureStorageExplorer#5954]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.3

### Regression From

Unsure

### Architecture

i86

### Storage Explorer Build Number

20220617.2

### Platform

Windows

### OS Version

Windows 11 x64

### Bug Description

Storage Explorer seems to be sending out FilterBlob request on behalf of user secretly upon opening a blob container.
The FilterBlob request is sent to filter blobs with key: fakeTagKey value: fakeTagValue.
This request happens on both access key mode and AAD mode. Happens regardless of whether the user has sufficient AAD permissions (Storage Blob Data Owner)

> https://accountname.blob.core.windows.net/?comp=blobs&where=%22fakeTagKey%22%3D%27fakeTagValue%27

### Steps to Reproduce

Assume:
a. User has Contributor and Storage Blob Data Reader role
b. Storage Explorer is set to use AAD authentication instead of access keys
c. Storage Account has diagnostics log sent to log analytics workspace enabled.

1. Launch Storage Explorer
2. Open any Storage Account
3. Open any blob container
4. Check StorageBlobLogs

### Actual Experience

Upon opening a blob container, Storage Explorer calls ListBlob to obtain the list of blobs inside the container.
However around the same time it also sends out FilterBlob request with key: fakeTagKey value: fakeTagValue.

![image](https://user-images.githubusercontent.com/5071602/180139150-e44edef1-4b83-4f9d-8967-4b26bb10d24c.png)

This request is not done by the user, because user only has Storage Blob Data Reader role therefore Storage Explorer greys out the filter pane so that user cannot perform such request.
![image](https://user-images.githubusercontent.com/5071602/180139305-b2f3abec-8ada-4570-8588-0f9b96bcbc81.png)

### Expected Experience

Storage Explorer not sending unexpected FilterBlob request on behalf of user.

**Comment by JasonYeMSFT** [comment]
We send that request to determine if the user has the capability to do blob tag query. That's why we know whether to disable the controls for sending tag queries. Would you expect the controls to send tag queries to be always enabled instead?

**Comment by taiyokato** [comment]
> We send that request to determine if the user has the capability to do blob tag query. That's why we know whether to disable the controls for sending tag queries. 

D'oh! That sounds about right... Although I was a little more inclined to expecting the controls to be always enabled and return 403 Permission error when user tries to actually use it. Or at least sending filter blob requester with descriptive tag and value names such as "filterPermissionCheck: storagexplorer" instead of just "fakeTagKey: fakeTagValue".

Anyways, understood. Thanks.
