### ISSUE TITLE
There is no prompt indicating the extension could not be verified when opening one extension bundle without setting environment variable

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5956]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220721.9
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.24.3)

## Steps to Reproduce ##
1. Launch Storage Explorer -> Do not set environment variable.
2. Click 'File -> Open Extension' -> Select one compatible extension bundle -> Click 'Open'.
3. Check whether there is a prompt indicating the extension bundle could not be verified.

## Expected Experience ##
There is a prompt indicating the extension bundle can't be verified.
![image](https://user-images.githubusercontent.com/41351993/180175054-ad738758-d46f-47ac-ba6f-be521dd5d979.png)

## Actual Experience ##
There is no prompt indicating the extension bundle could not be verified.

**Comment by MRayermannMSFT** [comment]
Fixed a remote configuration value for this.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220722.2. Fixed.
