### ISSUE TITLE
Bottom of Table

### ISSUE THREAD

**Issue by g7cnp** [microsoft/AzureStorageExplorer#5957]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

When viewing tables i would like to see the most recent entries

### Desired Solution

Single click to jump to the 'Bottom/most recent' table entries

**Comment by MRayermannMSFT** [comment]
@g7cnp right now the storage APIs do not make it possible for us to immediately jump you to the most recent table entries. Some things you could do which would be similar:

1. You can click "Load more" in the table explorer until all pages are loaded and then sort by the Timestamp column
2. If you know roughly how old the newest entities are, you can run a query in your table where you say "timestamp newer than <time slightly older than the newest entities>", and then that should return a limited set of entities which you can immediately sort by the Timestamp column.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you have further questions about table queries to help you get to the newest entities, feel free to open a new issue.
