### ISSUE TITLE
No refresh notification prompts when deleting file share snapshots without checking 'Auto-refresh on change'

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5960]
**Storage Explorer Version:** 1.25.0-dev
**Build Number:** 20220722.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Click 'Settings -> Data Explorers' -> Uncheck setting 'Auto-refresh on change'.
2. Expand one storage account -> File Shares.
3. Create a file share -> Click 'View Share Snapshots'.
4. Right click the file share -> Click 'Create Snapshot' -> A refresh notification prompts -> Click 'Yes' .
5. Right click the snapshot -> Click 'Delete' -> Click 'Yes'.
6. Check whether a refresh notification prompts.

## Expected Experience ##
A refresh notification prompts.

## Actual Experience ##
No refresh notification prompts.

## Additional Context ##
In previous release, no refresh notification prompts when creating and deleting file share snapshots.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220831.1. Reproduce.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220901.1. Fixed.
