### ISSUE TITLE
The 'Quick Access' option is the second option not the last one on the 'Reset Storage Explorer' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5967]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220725.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Reproduce Languages**: Spanish/French/Hungarian /Italy/Japanese/Korea/polish/Portuguese (Brazil)/Portuguese (Portugal)/Russian/Turkish/Chinese (ZH-CN/Chinese (ZH-TW)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select 'Español' -> Restart Storage Explorer.
3. Click the localized 'Help -> Reset'.
4. Observe the options on the dialog.
5. Check whether the 'Quick Access' is the last option.

## Expected Experience ##
The 'Quick Access' is the last option.

The screenshot in ENU:
![image](https://user-images.githubusercontent.com/41351993/180954572-05d4a9f9-4ab7-4608-8b85-a5f2cb8cfe89.png)

## Actual Experience ##
The 'Quick Access' is the second option not the last one.
![image](https://user-images.githubusercontent.com/41351993/180955289-5199c1c1-9246-4397-a74c-d706657e609b.png)

**Comment by JasonYeMSFT** [comment]
We sort these options by their names so the order may change depending on the locale.

**Comment by JasonYeMSFT** [comment]
The sorting behavior is by design.
