### ISSUE TITLE
The value of the 'Timestamp' selected from 'Custom Timestamp Query' dialog doesn't display under the query builder

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5969]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220725.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.24.3)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Open one non-empty table -> Click 'Query'.
3. Select 'Timestamp' in the Field column -> Drop down the Value column -> Click 'Custom...'.
4. No need to make changes in the 'Custom Timestamp Query' dialog -> Click 'OK'.
5. Check the value 'Last 7 Days' displays on the Value field.

## Expected Experience ##
The value 'Last 7 Days' displays on the Value field.
![image](https://user-images.githubusercontent.com/41351993/180958506-83591893-948e-43fc-88ab-16af9c7f7fc1.png)

## Actual Experience ##
No value displays on the Value field.
![image](https://user-images.githubusercontent.com/41351993/180957092-78681828-2a50-436d-bfaf-85cddb912110.png)

**Comment by craxal** [comment]
@v-xianya Did you not get an error message? I did, which indicated there was a binding error, which is why the text doesn't show.

**Comment by v-xianya** [comment]
@craxal I did not see any error message when reproducing this issue.

Verified this issue on the build main/20220727.2. Fixed. So, we are going to close it.
