### ISSUE TITLE
Both a confused prompting message and an error dialog pops up after opening an expired queue attached with SAS

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#597]
**Storage Explorer Version**:1.4.1
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture**:ia32/x64
**Build Number**:20180822.1
**Commit**:14ea2643
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Add an access policy for one queue with expired date.
2. Create a SAS URL using the set access policy in step1.
3. Attach this queue like below:
**Display name:** equeue
**SAS URL:** https://devdiv.visualstudio.com/DevDiv/DevDiv%20Team/_build/results?buildId=1968283&_a=summary&view=results
4. Expand **'Local & Attached'** -> **'Storage Accounts'** -> **'Queues'** -> Attempt to open the attached queue.

#### Expected Experience: ####
Only display a prompting like below.
![expect](https://user-images.githubusercontent.com/34729022/44449065-9b330380-a5dc-11e8-8acd-5756f722fb6d.png)

#### Actual Experience: ####
Both a confused prompting message and an error dialog pops up.
![prompt_error](https://user-images.githubusercontent.com/34729022/44449549-fc0f0b80-a5dd-11e8-9430-57bc1cb55b8b.png)

#### More info: ####
This issue doesn't reproduce for blob containers/file shares/tables.

**Comment by craxal** [comment]
Doesn't sound critical. The issue is pretty clear in the message box.
