### ISSUE TITLE
There is an extra scroll bar on the 'Custom Timestamp Query' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5970]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220725.3
**Branch**: main
**Platform/OS**: Windows 10
**Reproduce Languages**: Spanish/Polish/Portuguese (Brazil)/Portuguese (Portugal)/Russian
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select 'Español' -> Restart Storage Explorer.
3. Expand one storage account -> Tables.
4. Open one non-empty table -> Click 'Query'.
5. Select 'Timestamp' in the Field column -> Drop down the Value column -> Click 'Custom...'.
6. Observe there is no extra scroll bar.

## Expected Experience ##
There is no extra scroll bar.

## Actual Experience ##
There is an extra scroll bar.
![image](https://user-images.githubusercontent.com/41351993/180960224-3d3047f0-3d95-4f15-b6a7-e0263e343794.png)

## Additional Context ##
This issue doesn't reproduce on Linux Ubuntu 22.04/MacOS Monterey 12.4 (Apple M1 Pro).

**Comment by craxal** [comment]
The title is forcing elements down, so we just need to widen the dialog a bit.

**Comment by v-xianya** [comment]
@craxal Verified this issue on the rel build 20220729.1.
1. This issue is fixed on Spanish/Russian.
2. This issue still reproduces on Polish/Portuguese (Brazil)/Portuguese (Portugal). So, we are going to reopen it.
Here is the screenshot on Polish.
![image](https://user-images.githubusercontent.com/41351993/181737652-4f61fae8-fa64-45f6-9344-dfe111374fe9.png)

**Comment by craxal** [comment]
Should be resolved now. Please verify.

**Comment by v-kellyluo** [comment]
Verified this issue on the build rel/20220803.8. Fixed.
