### ISSUE TITLE
The strings 'true' and 'false' are localized in the error message when typing an invalid value for the Boolean property

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5971]
**Storage Explorer Version:** 1.25.0-dev
**Build Number:** 20220725.3
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.3 (Apple M1 Pro)
**Language:** Spanish/Swedish/Polish/Portuguese
**Architecture:** ia32/x64
**How Found:** From running test case
**Regression From:** Previous release (1.24.3)

## Steps to Reproduce ##

1. Open 'Settings' -> Application (Regional Settings) -> Select 'España' -> Restart Storage Explorer.
2. Expand one storage account -> Tables.
3. Create a table -> Click 'Add -> Add Property'.
4. Input a valid property name -> Select Boolean type -> Observe the Value field.
5. Check whether the stings 'true' and 'false' are not localized.

 
## Expected Experience ##
The stings 'true' and 'false' are not localized.
![image](https://user-images.githubusercontent.com/87792676/180970432-a667ee22-a1d2-4a4a-8fde-ef1a4fb6c871.png)

## Actual Experience ##
The stings 'true' and 'false' are localized.
![image](https://user-images.githubusercontent.com/87792676/180970552-422f768a-5d63-47c7-b71a-0ef0670f5333.png)

**Comment by craxal** [comment]
@cristianosuzuki77 I will commit a comment. Can we get this fixed right away?

**Comment by craxal** [comment]
See https://ceapex.visualstudio.com/CEINTL/_workitems/edit/679758 for tracking.

**Comment by v-kellyluo** [comment]
This issue still reproduces on the latest build main/20220729.2.
BTW, the string 'true' in the placeholder is also localized.
![image](https://user-images.githubusercontent.com/87792676/181669152-b10b2765-c42b-4f2d-8710-9a5e9438557f.png)

**Comment by craxal** [comment]
@v-kellyluo Yes, we know. The issue has not bee closed yet, and the status is still "Verifying", meaning the devs are still working on it. We're waiting for a translation fix.

**Comment by v-xianya** [comment]
Verified this issue on the rel build  20220803.6. 
This issue reproduces on the languages Spanish/Swedish/Polish/Portuguese (Brazil). Will keep eyes on this issue.
Here is the screenshot on Portuguese (Brazil).
![image](https://user-images.githubusercontent.com/41351993/182513356-33219efd-195f-40b2-9893-22b980df79fc.png)

**Comment by craxal** [comment]
@v-xiany To be more precise, you are still seeing translated strings in the placeholder, not the error message, correct?

**Comment by craxal** [comment]
For reference, this issue was a result of addressing #289.

**Comment by JasonYeMSFT** [comment]
We have merged local string fixes to the 1.25.0 release. We will make sure the translator team give us updated strings to the main branch later.

**Comment by v-xianya** [comment]
> @v-xiany To be more precise, you are still seeing translated strings in the placeholder, not the error message, correct?

@craxal Yes. The translated strings in the placeholder.

**Comment by v-kellyluo** [comment]
Verified this issue on the build rel/20220803.8. Fixed.
