### ISSUE TITLE
Azure Storage Account - Unable to Connect

### ISSUE THREAD

**Issue by kjbecker85** [microsoft/AzureStorageExplorer#5975]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

Most Recent as of July 26 2022

### Regression From

I don't know

### Architecture

x64

### Platform

Windows

### OS Version

Windows 10

### Bug Description

I am unable to connect my Azure Storage Account to my data lake.  I have tried connecting using both subscription and access keys

The following is the error message I receive when trying to open my blobs in Azure Storage Account:
Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://synapsecoursekjbdl.blob.core.windows.net/?comp=list&include=metadata failed, reason: tunneling socket could not be established, cause=connect EAFNOSUPPORT 127.0.0.1:80 - Local (0.0.0.0:52315)",
  "stack": "FetchError: request to https://synapsecoursekjbdl.blob.core.windows.net/?comp=list&include=metadata failed, reason: tunneling socket could not be established, cause=connect EAFNOSUPPORT 127.0.0.1:80 - Local (0.0.0.0:52315)\n    at ClientRequest.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1491:11)\n    at ClientRequest.emit (node:events:390:28)\n    at ClientRequest.onError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tunnel\\lib\\tunnel.js:183:21)\n    at Object.onceWrapper (node:events:510:26)\n    at ClientRequest.emit (node:events:390:28)\n    at TLSSocket.socketErrorListener (node:_http_client:447:9)\n    at TLSSocket.emit (node:events:390:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "ECONNRESET",
  "code": "ECONNRESET"
}

### Steps to Reproduce

1. Launch Storage Explorer
2. Expand a blob container 

### Actual Experience

Doesn't open.  I receive this error message
Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://synapsecoursekjbdl.blob.core.windows.net/?comp=list&include=metadata failed, reason: tunneling socket could not be established, cause=connect EAFNOSUPPORT 127.0.0.1:80 - Local (0.0.0.0:52315)",
  "stack": "FetchError: request to https://synapsecoursekjbdl.blob.core.windows.net/?comp=list&include=metadata failed, reason: tunneling socket could not be established, cause=connect EAFNOSUPPORT 127.0.0.1:80 - Local (0.0.0.0:52315)\n    at ClientRequest.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1491:11)\n    at ClientRequest.emit (node:events:390:28)\n    at ClientRequest.onError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tunnel\\lib\\tunnel.js:183:21)\n    at Object.onceWrapper (node:events:510:26)\n    at ClientRequest.emit (node:events:390:28)\n    at TLSSocket.socketErrorListener (node:_http_client:447:9)\n    at TLSSocket.emit (node:events:390:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "ECONNRESET",
  "code": "ECONNRESET"
}

**Comment by jinglouMSFT** [comment]
Are you using Storage Explorer behind a proxy server?  If yes, please take a look at this section in the Storage Explorer troubleshooting guide: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#proxy-issues to see if any suggested solutions there are helpful. Thanks.

**Comment by kjbecker85** [comment]
> Are you using Storage Explorer behind a proxy server? If yes, please take a look at this section in the Storage Explorer troubleshooting guide: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#proxy-issues to see if any suggested solutions there are helpful. Thanks.

I don't understand the first thing about a proxy server.  I've adjusted my proxy settings to: "Use app proxy settings" and "Do not use proxy".  

I tried following the article you linked to.  Over my head.

![image](https://user-images.githubusercontent.com/68037987/181138920-c7b04f02-cc3d-42ea-a175-4166a0728322.png)

**Comment by jinglouMSFT** [comment]
There is a section in the Troubleshooting guide that discusses in details about the proxy settings.  Here is the link https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network.  The error on tunneling socket usually indicates that Storage Explorer can't talk to your Azure services, commonly caused by some network communication problems. Proxy settings and/or SSL certificates are the first things to look at to help resolve the issues. 

Are you on a company network or a private network, say your home network? If you are on a company network and not sure if you are behind a proxy, you can check with your network admin. Or, try "Use system proxy (preview)".  The link above explains the differences between the different proxy settings.

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. If you still have issue, please open a new issue with the additional information.
