### ISSUE TITLE
The value of the property Resource Group displays as lowercase on the App Configuration store Properties panel

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5977]
**Storage Explorer Version:** 1.25.0-dev
**Build Number:** 20220727.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Create an App Configuration store under the 'CTI-Kelly' resource group.
2. Launch Storage Explorer -> Install one extension bundle.
3. Expand the App Configurations node -> Click the App Configuration store.
4. Observe its Properties panel.
5. Check whether the value of the property Resource Group displays as 'CTI-Kelly'.

## Expected Experience ##
The value of the property Resource Group displays as 'CTI-Kelly'.

## Actual Experience ##
The value of the property Resource Group displays as 'cti-kelly'.
![image](https://user-images.githubusercontent.com/87792676/181197955-94ad4f80-7511-4fb8-8be7-af95281af8c5.png)

**Comment by JasonYeMSFT** [comment]
This is fine. Azure resource group names are case insensitive.
