### ISSUE TITLE
A new App Configuration store tab opens when clicking 'Open' even though there is already a restored App Configuration store tab

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5978]
**Storage Explorer Version:** 1.25.0-dev
**Build Number:** 20220727.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** Ad-hoc testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Create an App Configuration store in portal.
2. Launch Storage Explorer -> Open 'Settings -> Data Explorers' -> Enable the setting 'Preserve Explorer Session'.
3. Install one extension bundle -> Expand the App Configurations node.
4. Open the App Configuration store -> Restart Storage Explorer.
5. The App Configuration store tab is restored.
6. Right click the App Configuration store -> Click 'Open'.
7. Check whether no new App Configuration store tab opens.

## Expected Experience ##
No new App Configuration store tab opens.

## Actual Experience ##
A new App Configuration store tab opens.

## Additional Context ##
This issue doesn't reproduce for blob containers/file shares/queues/tables.

**Comment by JasonYeMSFT** [comment]
This is by design. The restored tabs lose the association with the node so opening the node will open a new tab.
