### ISSUE TITLE
The string 'View Azure resources' is translated incorrectly on the Get Started Panel in Chinese (zh-CN)

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5979]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220727.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Reproduce Languages**: Chinese (zh-CN)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select '中文(简体)' -> Restart Storage Explorer.
3. Click the localized 'Help -> Get Started'.
4. Observe the 'Tasks' part.
5. Check the string 'View Azure resources' is translated correctly.

## Expected Experience ##
The string 'View Azure resources' is translated correctly. (查看 Azure 资源)

## Actual Experience ##
The string 'View Azure resources' is translated incorrectly.
![image](https://user-images.githubusercontent.com/41351993/181213836-c58dfa3e-1983-4044-ba2a-ab668b62a5dd.png)

## Additional Context ##
Here is the screenshot in ENU:
![image](https://user-images.githubusercontent.com/41351993/181213875-b4c8bc23-0318-4813-8606-dabbc8a388c5.png)

**Comment by JasonYeMSFT** [comment]
This should have been fixed.

**Comment by v-xianya** [comment]
Verified this issue on the latest rel and main build. Reproduced.
Will keep eyes on this issue.

**Comment by JasonYeMSFT** [comment]
The translated strings are fixed but we need to update the package one more time to take them.

**Comment by v-xianya** [comment]
Verified this issue on the build rel 20220803.6. Fixed. So, we close it.
![image](https://user-images.githubusercontent.com/41351993/182510433-f8169e9a-6540-436b-af5c-a1be55ce6381.png)
