### ISSUE TITLE
Display a blank after clicking ''Contact support for more than 100,000 RU/s'' for 'Create Collection' dialog

### ISSUE THREAD

**Issue by v-dantch** [microsoft/AzureStorageExplorer#598]
**Storage Explorer Version**:1.4.1
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture**:ia32/x64
**Build Number**:20180822.1
**Commit**:14ea2643
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Open one DocumentDB account -> Create one database.
2. Right click this new database ->Select 'Create Collection...' ->Type a valid collection ID ->Select 'Unlimited' for 'Storage capacity'.
3. Click ''Contact support for more than 100,000 RU/s '' at the bottom of 'Create Collection' dialog.

#### Expected Experience: ####
1. ''Contact support for more than 100,000 RU/s '' displays as a string not link.
2. There is no changes after clicking ''Contact support for more than 100,000 RU/s ''.

#### Actual Experience: ####
1. ''Contact support for more than 100,000 RU/s '' displays as a link.
2. Display a blank after clicking ''Contact support for more than 100,000 RU/s''.
![compare](https://user-images.githubusercontent.com/34729092/44457271-52864500-a5f2-11e8-920c-a9ebd1900fc2.png)

**Comment by MRayermannMSFT** [comment]
Don't think we/Cosmos need to worry about this for 1.4.1

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
