### ISSUE TITLE
Azure storage connect error

### ISSUE THREAD

**Issue by helensui** [microsoft/AzureStorageExplorer#5980]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.3

### Architecture

x64

### Platform

Windows

### Bug Description

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://eqctoinasqlsa.blob.core.windows.net/?comp=list&include=metadata failed, reason: connect ETIMEDOUT 10.2.1.4:443",
  "stack": "FetchError: request to https://eqctoinasqlsa.blob.core.windows.net/?comp=list&include=metadata failed, reason: connect ETIMEDOUT 10.2.1.4:443\n    at ClientRequest.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1491:11)\n    at ClientRequest.emit (node:events:390:28)\n    at TLSSocket.socketErrorListener (node:_http_client:447:9)\n    at TLSSocket.emit (node:events:390:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "ETIMEDOUT",
  "code": "ETIMEDOUT"
}

### Steps to Reproduce

expand the Blob Containers

### Actual Experience

when expand the Blob Containers, got error above

**Comment by JasonYeMSFT** [comment]
This is a network error indicating that some network requests timeout without getting any response. Are you behind a proxy? Could you go to the settings panel and try enabling "use system proxy" under "Settings" -> "Application" -> "Proxy"

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. If you still have issue, please open a new issue with the additional information.
