### ISSUE TITLE
Conditionally showing the release notes vs the Get Started page

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#5984]
Let's investigate if the following is possible:
- if Storage Explorer install is an upgrade, we open the release notes tab by default.  
- if Storage Explorer is a new install, meaning manually launch the install executable, we open the Get Started page by default.

As of in 1.25.0, we open the Get Started page by default, which may not be as useful for our experienced users.

**Comment by MRayermannMSFT** [comment]
Hold off on doing this until Jing gives the go ahead.
