### ISSUE TITLE
Cosmos DB Tables with underscore in the name will not allow insert/delete

### ISSUE THREAD

**Issue by fekberg** [microsoft/AzureStorageExplorer#599]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows
**Architecture**: ia32
**Regression From**:  Haven't tried

#### Steps to Reproduce: ####
1. Create a Cosmos DB Table in the Azure portal, for instance: ToDo_New
2. Go to Microsoft Azure Storage Explorer and try to insert, or delete data in the table
3. You will no get an error saying "Deleting entities from table 'fekberg/ToDo_New': Failed: Table name format is incorrect."

#### Expected Experience: ####
Inserted or Deleted data

#### Actual Experience: ####
The error

**Comment by austinheinrichs** [comment]
Same behavior when you have a Cosmos DB table name that has a period.  Example: test.name
Any updates on this?
