### ISSUE TITLE
Unable to view the containers in storage explorer under storage account which I created 

### ISSUE THREAD

**Issue by venu564** [microsoft/AzureStorageExplorer#5993]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.3

### Architecture

x64

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Storage explorer not opening the containers

### Steps to Reproduce

1. Launch Storage explorer 
2. Expand the containers

### Actual Experience

Create storage account and blob container in azure and installed storage explorer to access it from tool.
Added the SA as local in explorer and while opening the containers, getting error

### Expected Experience

NA

### Additional Context

NA

**Comment by JasonYeMSFT** [comment]
@venu564 How did you connect to the storage account in Storage Explorer? Did you connect to it as a local attachment or from your signed-in azure account? What error did you get when trying to access it?

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. If you still have issue, please open a new issue with the additional information.
