### ISSUE TITLE
Error Copy disks

### ISSUE THREAD

**Issue by c0nfl1ct** [microsoft/AzureStorageExplorer#5994]
Storage Explorer was unable to get access a disk.
Disk 'NH-TS-HR_OsDisk_1' in 'NHAzure-VMPortugal' was likely created. You may need to delete this disk before retrying this operation.

Service response: {
  "name": "Error",
  "message": "Access not permitted because disk NH-TS-HR_OsDisk_1_4205d0bbd899436e9ad842dc73ee5175 is currently attached to running VM /subscriptions/7c66e049-990b-484e-bea9-5569758a568b/resourceGroups/MinorPortugal-Servers/providers/Microsoft.Compute/virtualMachines/NH-TS-HR.",
  "stack": "Error: Access not permitted because disk NH-TS-HR_OsDisk_1_4205d0bbd899436e9ad842dc73ee5175 is currently attached to running VM /subscriptions/7c66e049-990b-484e-bea9-5569758a568b/resourceGroups/MinorPortugal-Servers/providers/Microsoft.Compute/virtualMachines/NH-TS-HR.\n    at new RestError (C:\\Users\\T.Reis\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\ms-rest-js\\dist\\msRest.node.js:2480:28)\n    at C:\\Users\\T.Reis\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\ms-rest-js\\dist\\msRest.node.js:3687:37\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async ComputeArmClient.runOperation (C:\\Users\\T.Reis\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\azure-sdk-helpers\\dist\\src\\ArmClient.js:64:24)\n    at async GetAccessState._grantAccessToDisk (C:\\Users\\T.Reis\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-managed-disks-extension\\dist\\src\\StateMachines\\DiskCopy\\States\\GetAccessState.js:40:35)\n    at async GetAccessState.update (C:\\Users\\T.Reis\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-managed-disks-extension\\dist\\src\\StateMachines\\DiskCopy\\States\\GetAccessState.js:22:33)\n    at async DiskCopyContext.start (C:\\Users\\T.Reis\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-managed-disks-extension\\dist\\src\\StateMachines\\DiskCopy\\DiskCopyContext.js:51:17)\n    at async DiskCopyJobHandler.handleJob (C:\\Users\\T.Reis\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-managed-disks-extension\\dist\\src\\JobHandlers\\CopyDiskJobHandler.js:24:13)\n    at async Provider.executeOperation (C:\\Users\\T.Reis\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\providers\\Provider.js:28:16)\n    at async NodeProcessHostProxy._handleExecuteRequest (C:\\Users\\T.Reis\\AppData\\Local\\Programs\\Microsoft Azure Storage

**Comment by JasonYeMSFT** [comment]
@c0nfl1ct The error message indicates that the disk is used by an existing VM, could you check if that's the case? Also, to help us better diagnose the cause of the issue, could you provide the basic information such as the platform (OS info), Storage Explorer version, steps you take before running into this issue, and so on?

**Comment by c0nfl1ct** [comment]
@JasonYeMSFT, thanks for the reply. i solved the problem. i stop and deallocated the vm. now i able to copy the hdd.
Thanks again.
