### ISSUE TITLE
Need to Access ACL metadata for Azure File Share

### ISSUE THREAD

**Issue by MAkhtarHossain** [microsoft/AzureStorageExplorer#5997]
[akhtar-hossain.txt](https://github.com/microsoft/AzureStorageExplorer/files/9237544/akhtar-hossain.txt)
I have a storage account and a fileshare. I have tied this storage account with AD DS (installed on a Azure VM). I have then setup ACLs on the share. I need a way to access the metadata on the fileshare to see what is saved as the ACL permissions. Trying to get the ACL permission on the fileshare using Azure Storage Explorer I am getting the attached error:

[akhtar-hossain.txt](https://github.com/microsoft/AzureStorageExplorer/files/9237547/akhtar-hossain.txt)

**Comment by JasonYeMSFT** [comment]
@MAkhtarHossain The error your get is a network error. It is common seen if your client cannot resolve the hostname of the file share service to its IP address. Are you behind a proxy when using Storage Explorer? Are you running Storage Explorer on your local computer or an Azure VM?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem, we recommend opening a support ticket via the Azure portal alternatively you can open a new issue here.
