### ISSUE TITLE
SAS token generated in 1.25.0 fails to authenticate IoT blobs

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5999]
**Storage Explorer Version:** 1.25.0
**Build Number:** 20220802.4
**Branch:** rel/1.25.0
**Platform/OS:** Windows 10
**Architecture:** ia32
**How Found:** From running test cases
**Regression From:** Previous release (1.24.3)

## Bug Description ##

1. Fail to upload IoT blobs.
2. Fail to download IoT blobs.
3. Fail to open IoT blobs.
4. Fail to delete IoT blobs.

## Steps to Reproduce ##

1. Launch Storage Explorer.
2. Connect to a blob storage module on edge using the connection string.
3. Switch to the attached storage account -> Blob Containers.
4. Create a blob container -> Click 'Upload -> Upload Files...'.
5. Click the 'No files selected' box -> Select one file -> Click 'Open -> Upload'.
6. Check whether succeeds to upload the blob.

## Expected Experience ##
Succeed to upload the blob.

## Actual Experience ##
Fail to upload the blob.
![image](https://user-images.githubusercontent.com/87792676/182346584-10b3d7f3-9622-42cc-8bfe-205540533ef3.png)

## Additional Context ##
Here is the Azcopy log:
[ae33b95d-d200-4345-7285-14ff7e57a72d.log](https://github.com/microsoft/AzureStorageExplorer/files/9241070/ae33b95d-d200-4345-7285-14ff7e57a72d.log)

**Comment by JasonYeMSFT** [comment]
The blob storage module on IoT edge device is running the service at a much lower level than the main application. Our latest upgrade of the service version introduced a new service version that the module cannot handle. A workaround is to enable "targeting Azure Stack API" which will force our code to use a lower API version.

**Comment by JasonYeMSFT** [comment]
It was also recommended to use "Target Azure Stack API" in previous Storage Explorer versions to avoid getting server internal errors which affects the performance. https://github.com/microsoft/AzureStorageExplorer/issues/4099

**Comment by johnpatrick3** [comment]
I am having this same issue and the "Target Azure Stack API" selection does not seem to resolve the problem.  After selecting Target Azure Stack API, Azure Storage Explorer restarts successfully. Following restart, I reconnect to the edge storage account using the account's connection string but then am presented with the same issue when I go to upload a file to my edge blob container..

**Comment by JasonYeMSFT** [comment]
For everything who is suffering from this issue, starting from 1.29.0, there will be a more elegant workaround for this issue. Instead of forcing the whole product to stay at 2017-04-17, you can create an SAS of the edge storage account that sets both version and API version to 2017-04-17 and attach the Iot Edge storage account using the SAS connection string. It will tell the service to validate the SAS use the correct algorithm and it won't hit the problematic APIs which take very long to fail.

https://github.com/microsoft/AzureStorageExplorer/issues/2100
