### ISSUE TITLE
Cannot delete *any* blobs

### ISSUE THREAD

**Issue by thedavegray** [Microsoft/AzureStorageExplorer#60]
**Storage Explorer Version:** 1.0 
**OS Version:** Windows 10 

**Steps to Reproduce:**
1. Delete any blob in a warm storage account.

**Expected Experience:**
To be able to copy then delete blobs 

**Actual Experience:**
Copy works, delete does not.

Azure Storage explorer just hangs.  This started happening middle of last week.    No errors, just says "deleting blob", I left it trying to delete a 10gb blob for the entire weekend.  I can delete blobs in the portal and no security has changed.

**Comment by craxal** [comment]
Hm.... I just tried deleting a 16 GB blob from a standard hot blob container, and it worked just fine.

What exactly do you mean by "warm account"? Do you mean *hot*, *cool* or *archive* (see https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-storage-tiers)?

What was the last version this worked for you? Did you re-login to your accounts after installing 1.0.0 as described in the release notes (Help > View Release Notes)? Are you running under special network conditions, such as a proxy?

**Comment by darrengillis** [comment]
I am seeing a similar problem after upgrading to 1.2.  

In my case, I'm attempting to delete several folders in blob storage at once.  The Activities panel shows 'Deleting 285 blobs from [storage account]: 245 completed, 5 in progress, 35 pending'

Storage explorer basically locks up at this point.

**Comment by craxal** [comment]
@darrengillis The entire app locks up? Not just the activity? I'm curious about the performance numbers. What's the CPU/memory consumption for Storage Explorer processes?

**Comment by craxal** [comment]
Closing this bug as stale. If this continues to be an issue, please let us know, and we can reopen.

**Comment by darrengillis** [comment]
I'm seeing this issue occurring again.  @craxal yes, the entire app locks up.  cpu: .5%, memory/232mb

If I kill the process and return, the items are deleted.  Trying to delete any others, however, kills the app again.  

Currently on version 1.4.0

**Comment by craxal** [comment]
@xt0rted I'd suggest trying to delete blobs from an actual storage account first. If you are successful, it's likely a problem with Azurite.


@darrengillis We'll start some investigations. If you can provide any additional information, including information I asked for in earlier comments, that would be helpful.

**Comment by xt0rted** [comment]
@craxal I'm able to delete blobs from an actual storage account. My application can delete blobs from Azurite but the storage explorer can't.

**Comment by craxal** [comment]
Do you have a connection string you can share?

**Comment by xt0rted** [comment]
I used the `Attach to local emulator` option which asked for a name and the ports to use. The connection string shown in the storage explorer is:

```
AccountName=devstoreaccount1;AccountKey=...;DefaultEndpointsProtocol=http;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;
```

**Comment by craxal** [comment]
And have you configured your Azurite services to listen to those specific ports?

**Comment by xt0rted** [comment]
Yea, I can view & download blobs just fine, and can read/delete blobs with my .net console app, but if I try to delete them with the storage explorer nothing happens. I don't even get a confirmation popup like I do when working against a real storage account.

**Comment by craxal** [comment]
Let's see if we can narrow this down. Can you open the F12 dev tools and drop a breakpoint just inside the `doExecute` function found in DownloadCommand.js? Step through each line to make sure everything is executing (you might have to drop several, one in each switch case). Just ask if you're not sure what to do.

**Comment by darrengillis** [comment]
Just tried again after updating to the latest version: 
![image](https://user-images.githubusercontent.com/1687455/44848735-e88b2280-ac25-11e8-975a-5fa042ce40b5.png)
 
Tried deleting a folder and it locked up (note this is a live storage account - not local).  

Here is the activity window:
![image](https://user-images.githubusercontent.com/1687455/44848765-048ec400-ac26-11e8-927a-3d65720478ef.png)

And the running process:
![image](https://user-images.githubusercontent.com/1687455/44848665-acf05880-ac25-11e8-954a-021b3fd7aecd.png)

**Comment by darrengillis** [comment]
Maybe it has something to do with volume.  If I drill down into the folder, I can delete individual blobs.  I can delete a folder with a smaller amount of blobs (2-3).  At the highest level when attempting to delete a folder that, in this case, contains several hundred, it locks up.  

The only portion of the app that is responsive at this point is the menu - I can open it.  Any other action I attempt and the app is unresponsive.

**Comment by craxal** [comment]
OK, that's helpful info. Out of curiosity, what's your delete policy? We recently added support for soft delete, so it's possible our changes may have done something.

**Comment by darrengillis** [comment]
The delete policy for soft delete was set to disabled.  I tried setting it to enabled with a retention period of 7 days.  When clicking delete in SE now the dialog has changed to reflect the new policy setting, however, I'm still seeing the same behavior.

**Comment by craxal** [comment]
Those errors are coming from the Azure Node client library.

In the dev tools, search for BlobServiceManager.js and drop breakpoints in `getDeleteRetentionPolicyProperties`. Check the function parameters to make sure they're as expected. Consider dropping a breakpoint in the callback for `blobService.getServiceProperties` to see if an error or result gets through.

Also, in the dev tools, find the BlobManager.js file. Look for a function called `deleteBlob` and drop a breakpoint in there. Check the values of the parameters, particularly `connectionString`, `containerName`, and `blob`.

**Comment by xt0rted** [comment]
@craxal inside `getDeleteRetentionPolicyProperties` the code gets to `blobService.getServiceProperties()` but the callback function never runs.

What seems to be happening is [the following line](https://github.com/Azure/azure-storage-node/blob/d7b7e16f7d7e08852f4fa1fb477acbdf0cc281d7/lib/common/services/storageserviceclient.js#L1084) calls [`ServicePropertiesResult.parse()`](https://github.com/Azure/azure-storage-node/blob/d7b7e16f7d7e08852f4fa1fb477acbdf0cc281d7/lib/common/models/servicepropertiesresult.js#L455-L487) which ends up throwing.

`responseObject.error` is `null`
`responseObject.response`  is
```json
{
    "isSuccessful": true,
    "statusCode": 200,
    "body": "<?xml version='1.0'?>\n<StorageServiceProperties/>",
    "headers": {
        "x-powered-by": "Express",
        "x-ms-version": "2016-05-31",
        "date": "Fri, 31 Aug 2018 22:40:25 GMT",
        "content-length": "49",
        "x-ms-request-id": "da87c9a0-ad6e-11e8-a00e-51e6908c5f05",
        "content-type": "text/html; charset=utf-8",
        "etag": "W/\"31-usTw18yBJF6VsqQ0hU+cjasVvyU\"",
        "connection": "keep-alive"
    }
}
```

For some reason `responseObject.response.body.StorageServiceProperties` ends up being `undefiend` so when `ServicePropertiesResult.parse()` acts on it it throws.

**Comment by xt0rted** [comment]
@craxal if I set `servicePropertiesXml` to `{}` and then let the function run I'm prompted to delete the blob and it successfully deletes. So that's what the issue is.

**Comment by craxal** [comment]
OK. Before notifying them, check one more thing. Drop a breakpoint on the line containing the `blobService.getServiceProperties()` call. Double-check the parameters and make sure they're correct, especially the connection string.

Consider letting them know by posting an issue at [Microsoft/azure-storage-node](https://github.com/Azure/azure-storage-node). I'll let them know from my end as well.

**Comment by xt0rted** [comment]
@craxal this is the connection string being passed to `getDeleteRetentionPolicyProperties`
```
AccountName=devstoreaccount1;AccountKey=...;DefaultEndpointsProtocol=http;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;
```

The call to `blobService.getServiceProperties()` looks fine but never returns because of `ServicePropertiesResult.parse()` throwing.

I reported the issue in the [node sdk repo](https://github.com/Azure/azure-storage-node/issues/511) and they said it's a result of Azurite not responding with the right value, so I reported the issue in [the Azurite repo](https://github.com/Azure/Azurite/issues/86) as well.

For now I'm working around this by patching [servicepropertiesresult.js](https://github.com/Azure/azure-storage-node/blob/d7b7e16f7d7e08852f4fa1fb477acbdf0cc281d7/lib/common/models/servicepropertiesresult.js#L455-L487) like so until a new version of one of these projects is released which resolves it.
```diff
 exports.parse = function (servicePropertiesXml) {
   var serviceProperties = {};

+  if (!servicePropertiesXml) return serviceProperties;

   if (typeof servicePropertiesXml.Logging !== 'undefined') {
     serviceProperties.Logging = parseLogging(servicePropertiesXml.Logging);
   }
```

**Comment by craxal** [comment]
Thanks! For reference: Azure/Azurite#86.

**Comment by bunceg** [comment]
Still getting this, version 1.5. Has this patch been released?

Deleting blobs that exist in a folder at folder level will *always* lock up, needing to End-Task and terminate the process. If I go into the folder and delete then it seems to work fine.
