### ISSUE TITLE
Stuck on loading screen on linux

### ISSUE THREAD

**Issue by ryanvarley** [Microsoft/AzureStorageExplorer#600]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Ubuntu 18.04.1 LTS
**Architecture**: ?
**Regression From**: Only tried this version and it has never worked

#### Steps to Reproduce: ####
1. Install required packages
2. Launch the app from the command line with `./StorageExplorer`

#### Expected Experience: ####
A working app

#### Actual Experience: ####
The storage explorer loading screen pops up and continuously spins the loading icon. From the command line I get the output

```
An error ocurred while retrieving previous app state:
Error: ENOENT: no such file or directory, open '/home/ryan/.config/StorageExplorer/appState.json'
```

**Comment by craxal** [comment]
Strange. I doubt that's the real error, since the code should simply fill in some default values if that file isn't found or corrupted. If you want to be sure, create a file at the location mentioned in the error and enter something like this:
```json
{
    "lastWindowState": {
        "rect": {
            "x": 0,
            "y": 0,
            "width": 1000,
            "height": 800
        },
        "maximized": false
    }
}
```
Then start up Storage Explorer and see what happens.

**Comment by ryanvarley** [comment]
Yeah, adding this stops that error but I still have the same problem. There is no output to the console now. Is there a log or a verbose mode where I can get more information about whats happening?

**Comment by ryanvarley** [comment]
Yeah, same result

**Comment by craxal** [comment]
We very recently released 1.4.1. There was a bug for first-time users where the app wasn't creating the encryption key we need for storing credentials and such. Give that a try and see if that solves your problem.

**Comment by oedenfield** [comment]
I'm having the same issue (running on Ubuntu 18.04, I think we don't have support for 18.04 yet).  How do I force generation of the encryption key or can I just create one with ssh-keygen or something and then place the key somewhere?

**Comment by craxal** [comment]
@oedenfield No, we don't officially support 18.04 yet. That being said, did you install v1.4.1? We specifically addressed this issue in that version. See #535.

**Comment by ryanvarley** [comment]
Same issue with 1.4.1 for me unfortunately

**Comment by oedenfield** [comment]
@craxal I just deleted and re-downloaded to make sure, the splash screen also shows as version 1.4.1.  Same issue (showing the "Loading" screen and never actually coming up).  Manually creating the appState.json file resolved the error about retrieving previous app state but the tool still doesn't come up.

**Comment by craxal** [comment]
Ugh. That's not good. Sorry to say, it's likely a problem with Ubuntu 18.04. We've yet to iron out the requirements for that OS. If you have an Ubuntu 16 machine, we'd recommend using that until we find out what we need for 18.

We have plans to make use of [Snapcraft](https://snapcraft.io/), which we hope will eliminate the problems we keep running into between Linux distributions and OS versions. See #377 for more discussion. Unfortunately, I can't give you an estimate when we might have that ready.

**Comment by oh54** [comment]
I had the same problem with Ubuntu 17.10, I tried running an older version of Storage Explorer (1.3.1) and got an error message "libgnome-keyring.so.0: cannot open shared object file: No such file or directory" (1.4.1 produced no message, just stuck loading). 

I ran the commands from the answer to this question - https://superuser.com/questions/1233459/error-running-gitkraken-even-though-dependencies-installed/1255172, i.e.

 `sudo apt install libgnome-keyring-common libgnome-keyring-dev`

And this fixed the issues for both versions.

**Comment by oedenfield** [comment]
Thank you @oh54. Installing libgnome-keyring-common and libgnome-keyring-dev did allow the UI to open for me on 18.04. Now getting sign-in to work seems to be my next issue but we're getting there.

**Comment by ryanvarley** [comment]
This also got me past the loading screen. Unfortunately, like oedenfield I am now stuck on the "Waiting for authentication..." screen after trying to sign in with my Microsoft account.

**Comment by craxal** [comment]
That's really good to know! Thanks @oh54; maybe we'll be able to add that to our future release notes.

For further sign-in problems, consult #377, #434, #583, or open a new issue if none of these seem to match your situation.

**Comment by truestep** [comment]
AzureStorageExplorer 1.4.2 doesn't work on Ubuntu 18.04. Also there is nothing to consult for in #377, #434, #583 they are also not resolved. Is the whole Azure cloud works the same way?
