### ISSUE TITLE
The order of the property columns can be reset by manually refreshing

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6000]
**Storage Explorer Version**: 1.25.0
**Build Number**: 20220803.6
**Branch**: rel/1.25.0
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Ad-hoc testing
**Regression From**: Previous release (1.24.3)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Add one entity.
3. Reorder the property columns -> Click 'Refresh'.
4. Check whether the column order is not reset.

## Expected Experience ##
The column order is not reset.
![image](https://user-images.githubusercontent.com/41351993/182336498-b00adc60-f67f-4445-a1cf-8e5442dd6557.png)

## Actual Experience ##
The column order is reset.

## Additional Context ##
1. This issue doesn't reproduce on the previous rel build #20220802.4.
2. This issue also reproduces for the column order on the 'Column Options' dialog.

**Comment by craxal** [comment]
This behavior is a consequence of fixing #5998. However, this is not a regression. Contrary to what is mentioned here, I observe the same behavior in the previous release. Therefore, this is by design.

**Comment by v-xianya** [comment]
@craxal  
For the step2, **Reorder the columns by changing the column order on 'Column Options' dialog.** not drag the column in the editor to reorder. Sorry for not pointing this out.

The updated steps:

1. Expand one storage account -> Tables.
2. Create a table -> Add one entity.
3. Open 'Column Options' dialog -> Move the column order -> Click 'OK'.
4. The column order in the editor is changed.
5. Refresh the editor.

**Actual:**
The column order is reset (both in the editor and in the 'Column Options' dialog)

In the previous release and build. this issue doesn't reproduce.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220916.2. Reproduce. Will verify it on a newer build.

**Comment by craxal** [comment]
@v-xianya Not all changes are in. You don't need to check Verifying bugs until they're closed.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220920.2. Fixed.
