### ISSUE TITLE
Issue accessing Blob Containers in Azure Storage

### ISSUE THREAD

**Issue by drobisonoh** [microsoft/AzureStorageExplorer#6003]
this issue started today (8/4/22).  No issues with same access last night. 

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://nsspace.blob.core.windows.net/?comp=list&include=metadata failed, reason: getaddrinfo EAI_AGAIN nsspace.blob.core.windows.net",
  "stack": "FetchError: request to https://nsspace.blob.core.windows.net/?comp=list&include=metadata failed, reason: getaddrinfo EAI_AGAIN nsspace.blob.core.windows.net\n    at ClientRequest.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1491:11)\n    at ClientRequest.emit (node:events:394:28)\n    at TLSSocket.socketErrorListener (node:_http_client:447:9)\n    at TLSSocket.emit (node:events:394:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "EAI_AGAIN",
  "code": "EAI_AGAIN"
}

**Comment by JasonYeMSFT** [comment]
@drobisonoh The getaddrinfo EAI_AGAIN is a DNS related issue meaning that your DNS server cannot resolve the given hostname of your file share service. Are you running Storage Explorer behind a proxy? If not, please contact your network administrator to see if there is anything wrong with your DNS server configuration.

**Comment by drobisonoh** [comment]
Thanks....this helped and I was able to resolve.

**Comment by drobisonoh** [comment]
Thanks....this helped and I was able to resolve.
