### ISSUE TITLE
Attached Storage Account Error

### ISSUE THREAD

**Issue by ajayg233** [microsoft/AzureStorageExplorer#6004]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.3

### Architecture

x64

### Storage Explorer Build Number

20220617.2

### Platform

Windows

### OS Version

Windows 11 pro

### Bug Description

When i was trying to access Attached Storage getting this Error Attached Storage Account Error 
Unable to load attached Storage Account. Error: Cannot read properties of undefined (reading 'version')

![image](https://user-images.githubusercontent.com/110654223/183009107-737edc50-b071-4bd5-92b1-bf1310b9bfaf.png)

### Steps to Reproduce

1. Launch the storage explorer
2. Select storage accounts

### Actual Experience

When i was trying to access Attached Storage getting this Error Attached Storage Account Error 
Unable to load attached Storage Account. Error: Cannot read properties of undefined (reading 'version')

### Expected Experience

I need to access the storage accounts

**Comment by JasonYeMSFT** [comment]
This usually means some connection data has been corrupted. Could you follow the steps here to clean up the corrupted connections [troubleshoot guide](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#error-occurred-while-adding-new-connection-typeerror-cannot-read-property-version-of-undefined)?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem, we recommend opening a support ticket via the Azure portal alternatively you can open a new issue here.
