### ISSUE TITLE
Map root folder, or how to mirror folder structure locally

### ISSUE THREAD

**Issue by jsuddsjr** [microsoft/AzureStorageExplorer#6005]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I'd like to create a mirror of the VC structure on my local drive. 

### Desired Solution

In order to compile scripts locally, the tools normally download the files from the VC. However, if you've created a local folder structure that mirrors the VC, you can compile more quickly. I'd like to map the root storage account to a folder on disk, and as I download files, they would be copied to the same folder structure as the VC. 

### Alternatives and Workarounds

I'm currently recreating the folder structure by hand. 

### Additional Context

Folder copy already does this; however, as many of the folders contain very large files, I would quickly run out of space. An alternative approach would be to apply a filter to the folder copy, so that it would skip over large files, or copy only allowed extensions. 

### Related
- #5873 
- #5259

**Comment by JasonYeMSFT** [comment]
@jsuddsjr AzCopy has two flags named "include-pattern" and "include-regex" (or equivalent flags for exclusion) to let you filter at the root of your directory on what files to transfer. We haven't integrated them yet. You can construct an AzCopy command and manually execute it to do the work. Filtering by file size is not supported at the moment.

**Comment by MRayermannMSFT** [comment]
@jsuddsjr to be clear are you using blob containers? Because if you are instead using file shares, those can be mounted as drives over SMB. So something for you to consider?

Also, if you need additional help with constructing AzCopy commands, we would recommend working directly with the AzCopy team here: https://github.com/Azure/azure-storage-azcopy/issues

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem, we recommend opening a support ticket via the Azure portal alternatively you can open a new issue here.
