### ISSUE TITLE
A loading icon always displays in the editor of one non-empty blob container/queue against the language 'Hungarian'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6006]
**Storage Explorer Version**: 1.26.0-dev
**Build Number**: 20220808.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.5 (Apple M1 Pro)
**Reproduce Languages**: Hungarian
**Architecture**: ia32/x64
**How Found**: Verifying bug 5269
**Regression From**: Previous release (1.24.3)

## Steps to Reproduce ##
1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select 'magyar' -> Restart Storage Explorer.
3. Expand one non-ADLS Gen2 storage account -> Blob Container.
4. Open one non-empty blob container.
5. Check no loading icon displays in the editor.

## Expected Experience ##
No loading icon displays in the editor.

## Actual Experience ##
A loading icon always displays in the editor.
![image](https://user-images.githubusercontent.com/41351993/183364222-a726392d-6488-42a4-9840-2b904ff31c3c.png)

## Additional Context ##
1. Verified this issue on all languages, it only reproduces on 'Hungarian'.
2. Here is the log:
[2022-08-08_005447.zip](https://github.com/microsoft/AzureStorageExplorer/files/9279954/2022-08-08_005447.zip)

**Comment by JasonYeMSFT** [comment]
There is a typo in the hu localized string that causes errors to be thrown.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220808.4. Fixed. So, we are going to close it.
