### ISSUE TITLE
Hierarchical blobs fails with Azurite

### ISSUE THREAD

**Issue by sachabruttin** [Microsoft/AzureStorageExplorer#601]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows 10
**Architecture**: ia32
**Regression From**: 

#### Steps to Reproduce: ####
1. Install Azurite 2.6.5 and launch Storage Explorer
2. Browse Azurite Emulator

#### Expected Experience: ####
The blobs are displayed in hierarchical view and can be opened.

#### Actual Experience: ####
The blobs are displayed in a flat view with full filename. Trying to opening a file gives a 404 exception.
Using the .NET SDK, the blob are correctly written/read to Azurite.

![image](https://user-images.githubusercontent.com/2523409/44571976-be97b300-a782-11e8-959a-94f21169b154.png)

![image](https://user-images.githubusercontent.com/2523409/44572097-1b936900-a783-11e8-8e3a-e5e5fcc21669.png)

**Comment by craxal** [comment]
You're using backslashes "\\" to separate "folders". However, we default for _forward_ slashes "/" for folder delimiters. Try renaming your blobs to use forward slashes.

**Comment by sachabruttin** [comment]
It works thanks. Strange that Azure Storage Emulator is accepting "\" and "/" to separate "folders".
Anyway, I fixed my code..

**Comment by craxal** [comment]
I think you mean Storage Explorer only accepts "/" to separate folders?

Here's a useful [documentation page](https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata) that may be hepful.
