### ISSUE TITLE
Unable to retrieve child resources - "The specifed resource name contains invalid characters" 

### ISSUE THREAD

**Issue by thalesx** [microsoft/AzureStorageExplorer#6010]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.25.0

### Regression From

did not try on a previous version

### Architecture

x64

### Storage Explorer Build Number

20220803.8

### Platform

Windows

### OS Version

Windows 11

### Bug Description

I'm getting a "Unable to retrieve child resources" error with a "The specifed resource name contains invalid characters" message when I try to expand or refresh the Blob Container node of the local Emulator storage account. Other nodes of the same storage account work fine.

### Steps to Reproduce

1. Lauch Storage Explorer
2. Go to the **Emulator & Attached -> (Emulator - Default Ports)** node.
3. Expand the **Blob Containers** node.

### Actual Experience

Error happens and the Blob Containers node does not expand.

### Expected Experience

Node expands and shows blob containers.

### Additional Context

Error details (redacted to fit in form; happy to provide more details upon request):

{
    "name": "RestError",
    "message": "The specifed resource name contains invalid characters.\nRequestId:a7b978c4-a844-4e64-8cdd-6113a04ddbb2\nTime:2022-08-09T22:42:10.1049893Z",
    "stack": "RestError: The specifed resource name contains invalid characters.\nRequestId:a7b978c4-a844-4e64-8cdd-6113a04ddbb2\nTime:2022-08-09T22:42:10.1049893Z\n    at handleErrorResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:3159:19)\n    at C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:3095:49\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async StorageRetryPolicy.attemptSendRequest (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\storage-blob\\dist\\index.js:14445:24)\n    at async BlobApiVersionRequestPolicy.sendRequest (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-blob-extension\\dist\\src\\Clients\\BlobStorageClient.js:24:16)\n    at async StorageClientContext.sendOperationRequest (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:4932:31)\n    at async ContainerClient.getProperties (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\storage-blob\\dist\\index.js:22467:20)\n    at async ContainerClient.exists (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\storage-blob\\dist\\index.js:22382:13)\n    at async C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-blob-extension\\dist\\src\\Clients\\BlobServiceClient.js:64:25\n    at async Promise.all (index 1)",
    "code": "InvalidResourceName",
    "statusCode": 400,
    "request": {
        "streamResponseStatusCodes": {},
        "url": "http://127.0.0.1:10000/devstoreaccount1/%24blobchangefeed?restype=container",
        "method": "GET",
        "headers": {
            "_headersMap": {
                "x-ms-version": {
                    "name": "x-ms-version",
                    "value": "2019-07-07"
                },
                "accept": {
                    "name": "Accept",
                    "value": "application/xml"
                },
                "user-agent": {
                    "name": "User-Agent",
                    "value": "Microsoft Azure Storage Explorer/1.25.0 (win32) azsdk-js-storageblob/12.9.0 (NODE-VERSION v16.14.2; Windows_NT 10.0.22000)"
                },
                "x-ms-client-request-id": {
                    "name": "x-ms-client-request-id",
                    "value": "6822ce11-f6cb-4090-8fea-f205662d71e6"
                },
                "x-ms-date": {
                    "name": "x-ms-date",
                    "value": "Tue, 09 Aug 2022 22:42:10 GMT"
                },
                "authorization": {
                    "name": "Authorization",
                    "value": "Signed SharedKey Redacted="
                },
                "cookie": {
                    "name": "Cookie",
                    "value": ""
                }
            }
        },
        "withCredentials": false,
        "timeout": 0,
        "keepAlive": true,
        "decompressResponse": false,
        "requestId": "6822ce11-f6cb-4090-8fea-f205662d71e6"
    },
    "response": {
        "headers": {
            "_headersMap": {
                "content-length": {
                    "name": "content-length",
                    "value": "243"
                },
                "content-type": {
                    "name": "content-type",
                    "value": "application/xml"
                },
                "date": {
                    "name": "date",
                    "value": "Tue, 09 Aug 2022 22:42:10 GMT"
                },
                "server": {
                    "name": "server",
                    "value": "Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0"
                },
                "x-ms-error-code": {
                    "name": "x-ms-error-code",
                    "value": "InvalidResourceName"
                },
                "x-ms-request-id": {
                    "name": "x-ms-request-id",
                    "value": "a7b978c4-a844-4e64-8cdd-6113a04ddbb2"
                },
                "x-ms-version": {
                    "name": "x-ms-version",
                    "value": "2019-07-07"
                }
            }
        },
        "request": {
            "streamResponseStatusCodes": {},
            "url": "http://127.0.0.1:10000/devstoreaccount1/%24blobchangefeed?restype=container",
            "method": "GET",
        },
        "withCredentials": false,
        "timeout": 0,
        "keepAlive": true,
        "decompressResponse": false,
        "requestId": "6822ce11-f6cb-4090-8fea-f205662d71e6"
    },
    "status": 400,
    "bodyAsText": "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>InvalidResourceName</Code><Message>The specifed resource name contains invalid characters.\nRequestId:a7b978c4-a844-4e64-8cdd-6113a04ddbb2\nTime:2022-08-09T22:42:10.1049893Z</Message></Error>",
    "parsedBody": {
        "message": "The specifed resource name contains invalid characters.\nRequestId:a7b978c4-a844-4e64-8cdd-6113a04ddbb2\nTime:2022-08-09T22:42:10.1049893Z",
        "code": "InvalidResourceName"
    },
    "parsedHeaders": {
        "errorCode": "InvalidResourceName",
        "content-length": "243",
        "content-type": "application/xml",
        "date": "Tue, 09 Aug 2022 22:42:10 GMT",
        "server": "Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0",
        "x-ms-request-id": "a7b978c4-a844-4e64-8cdd-6113a04ddbb2",
        "x-ms-version": "2019-07-07"
    }
},
"details": {
    "errorCode": "InvalidResourceName",
    "content-length": "243",
    "content-type": "application/xml",
    "date": "Tue, 09 Aug 2022 22:42:10 GMT",
    "server": "Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0",
    "x-ms-request-id": "a7b978c4-a844-4e64-8cdd-6113a04ddbb2",
    "x-ms-version": "2019-07-07",
    "message": "The specifed resource name contains invalid characters.\nRequestId:a7b978c4-a844-4e64-8cdd-6113a04ddbb2\nTime:2022-08-09T22:42:10.1049893Z",
    "code": "InvalidResourceName"
}
}

**Comment by MRayermannMSFT** [comment]
@thalesx what emulator are you using and what version of it as well?

**Comment by MRayermannMSFT** [comment]
Two of us tested this today against Azurite 3.18.0 and we couldn't reproduce. Let us know if you see different. Though if you're using an older version of Azurite, we would ask that you update to the newest version. :)

**Comment by thalesx** [comment]
Thanks! Yes we are using an older emulator (Windows Azure Storage Emulator 5.10.0.0). I'll have to check our plans for upgrading to Azurite. Meanwhile I tested with Azure Storage Emulator 1.11.0 and it worked fine. As such we can close this issue as resolved.

**Comment by michaelo-numerik** [comment]
I'm getting the same error on Storage Explorer 1.25.1 when connecting to the same version of [Azure Storage Emulator](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator) as thalesx (5.10.0.0). 

While Azure Storage Emulator is deprecated in favor of Azurite, the Storage Explorer docs state that it is [still a supported emulator](https://docs.microsoft.com/en-us/azure/vs-azure-tools-storage-manage-with-storage-explorer?tabs=windows#local-storage-emulator). Is this correct, or should the old emulator no longer work as the `by design` label indicates?

I know that the two tools used to work together without problems, but I'm not sure which version of Storage Explorer introduced this error.

**Comment by kenqu-rs** [comment]
@MarcelMalke 
thank u very much!!!
