### ISSUE TITLE
An error occurs when clearing queue on one restored queue explorer with the language changed after restarting Storage Explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6011]
**Storage Explorer Version**: 1.26.0-dev
**Build Number**: 20220810.5
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.5 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Queues.
2. Create a queue -> Add messages.
3. Open 'Settings' -> Application (Regional Settings) -> Select '中文（简体）' -> Restart Storage Explorer. (Make sure the setting 'Preserve Explorer Session' is enabled).
4. There is a restored queue explorer-> Try to clear queue.
5. Check no error occurs.

## Expected Experience ##
No error occurs.

## Actual Experience ##
An error occurs.
![image](https://user-images.githubusercontent.com/41351993/183803239-1878ac10-ed77-4c8b-9648-7dfe86800ab0.png)

**Comment by JasonYeMSFT** [comment]
I fixed a few potential race conditions that may trigger this error. I am going to close this bug. If this ever reproduces, please reopen it and let us know.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20220825.4. Fixed.
