### ISSUE TITLE
Error on launch: Configuration system failed to initialize

### ISSUE THREAD

**Issue by dfran02** [microsoft/AzureStorageExplorer#6013]
Windows 10 Enterprise
Microsoft .NET Framework 4.8.1/4.8/4.7.2
Storage Explorer 1.25.0/1.24.0/1.24.3

Hi,
When I try to open Storage Explorer, I receive the error:

> The authentication library used by Storage Explorer has failed to start properly. Please ensure you have .NET Framework 4.7.2 or greater installed. If .NET Framework 4.7.2 or greater is already installed then refer to the troubleshooting guide for help. Verbose authentication logging has been enabled.
> 
> Error:Configuration system failed to initialize (ErrorKind: Error HResult: 80131500)

When I close the error, Storage Explorer also closes.

I've tried different versions of ASE and installed different versions of the .NET SDK, but get the same error every time.

I tried closing ASE and Visual Studio, clearing logs, then reopening ASE. The logs: [azure_storage_explorer_1.25_logs.zip](https://github.com/microsoft/AzureStorageExplorer/files/9303473/azure_storage_explorer_1.25_logs.zip)

**Comment by MRayermannMSFT** [comment]
I've passed your logs onto the responsible team. Will get back to you as soon as possible.

**Comment by MRayermannMSFT** [comment]
@dfran02 have you installed mono on your machine?

**Comment by dfran02** [comment]
No, but perhaps some other frameworks I have installed may clash: 
![image](https://user-images.githubusercontent.com/51128776/184195241-6eefd2e3-6273-49c3-87e9-5f5fc314cac3.png)

**Comment by MRayermannMSFT** [comment]
Hmmmmmmmmmmm. Can you check `C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\machine.config` (if you don't have a `v4.0.30319` then look for some other `v4` folder) and look for any proxy entries? It should have just this
```
<section name="defaultProxy" type="System.Net.Configuration.DefaultProxySection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"/>
```

**Comment by dfran02** [comment]
yes, I see that entry.

**Comment by MRayermannMSFT** [comment]
And no other proxy entries? Ok well then let's just try:
1. Open to `<Storage Explorer install dir>\resources\app\ServiceHub\MSAL-Services\IdentityService\Microsoft.Developer.IdentityService.exe.config`
2. Delete the line with `defaultProxy`
3. Try running Storage Explorer again
4. If it fails, share the new set of authentication logs with us

**Comment by dfran02** [comment]
That worked! Any chance you could explain _why_ it worked?

**Comment by MRayermannMSFT** [comment]
To be honest....nope! Something somewhere didn't like that section in the config. 🤷

**Comment by MRayermannMSFT** [comment]
Going to close this as mitigated now. Please open a new issue if something else comes up. We don't look at closed issues very frequently.
