### ISSUE TITLE
Support generating user delegation SAS and attaching with it for Blob/Gen2

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#6014]

**Comment by Andreas-Mi** [comment]
I just tested the feature using Azure Data Lake Storage Gen2 in AzureStorageExplorer (v1.27.2). I would assume the roles "Reader", "Storage Blob Data Contributor" and "Storage Blob Delegator" in combination should be sufficient to create a user delegation SAS. However, the "Get Shared Access Signature..." menu item does not appear in the context menu. 

When I additionally grant "Storage Account Key Operator Service Role" (providing Microsoft.Storage/storageAccounts/listkeys/action) the menu item appears and I am also able to select "User delegation key" as singing key. I there some historical check that requires account key access?

**Comment by JasonYeMSFT** [comment]
@Andreas-Mi Yes. https://github.com/microsoft/AzureStorageExplorer/issues/6457
