### ISSUE TITLE
Azure Storage Explorer is not working on WVD

### ISSUE THREAD

**Issue by itsme-sk** [microsoft/AzureStorageExplorer#6017]
The authentication library used by storage explorer is failed to start properly.

Windows 10 operating system 
The version of Azure storage Explorer is 1.19.1
The .Net framework version is 4.8

![Azure storage explorrer error](https://user-images.githubusercontent.com/58106698/184147727-03991715-4b51-4243-b04f-694556f72067.png)

[2022-08-10_223543_main.log](https://github.com/microsoft/AzureStorageExplorer/files/9309126/2022-08-10_223543_main.log)
[2022-08-10_223543_renderer.log](https://github.com/microsoft/AzureStorageExplorer/files/9309127/2022-08-10_223543_renderer.log)

**Comment by MRayermannMSFT** [comment]
@itsme-sk can you please try using the latest version of Storage Explorer (1.25)? If that still doesn't work, then please get us the [authentication logs ](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2204#authentication-logs)after reproducing with 1.25.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem, we recommend opening a support ticket via the Azure portal alternatively you can open a new issue here.
