### ISSUE TITLE
Use `fs.watch` and `FSWatcher` in file watcher module

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#6018]
Node documentation states that `fs.watch()` is more efficient and should be used instead of `fs.watchFile()` and `fs.unwatch()`. Furthermore, `fs.watch()` returns an `FSWatcher` object that can be saved instead of the listener function and be used to detach.

**Comment by MRayermannMSFT** [comment]
These caveats under the docs for `fs.watch()` make me nervous:

> If the underlying functionality is not available for some reason, then fs.watch() will not be able to function and may throw an exception. For example, watching files or directories can be unreliable, and in some cases impossible, on network file systems (NFS, SMB, etc) or host file systems when using virtualization software such as Vagrant or Docker.

Given we haven't had any issues with `fs.watchFile()`, it doesn't seem worth the risks to move to this other API. Going to close this as won't fix.
