### ISSUE TITLE
work and school (with same e-mail different passwords) accounts explorable

### ISSUE THREAD

**Issue by Markoolio** [Microsoft/AzureStorageExplorer#602]
**Storage Explorer Version**: 1.4
**Platform/OS Version**: Windows
**Architecture**: ia32
**Regression From**: 

#### Steps to Reproduce: ####
1. add work account x@y.com 
2. add personal account x@y.com
Now the accounts have been added but the resources of only one of them is viewable.

#### Expected Experience: ####
I would expect to be able to browse content on both of them and transfer content between the accounts.

#### Actual Experience: ####
only one of the accounts is browsable

**Comment by MRayermannMSFT** [comment]
Hey @Markoolio , can you try the latest version, 1.4.1? This bug should be fixed in it. Please try it and get back to me. 😄

**Comment by Markoolio** [comment]
Thank you very much for the bug fix, work perfectly now, makes my work
easier :)
