### ISSUE TITLE
Performance regression when copying big blob (e.g. 1TB) inside same account

### ISSUE THREAD

**Issue by blueww** [microsoft/AzureStorageExplorer#6021]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.25.0

### Regression From

0.9.01

### Architecture

x64

### Storage Explorer Build Number

20220803.8

### Platform

Windows

### OS Version

Windows 10

### Bug Description

On Storage Explorer 0.9.01, 

- the big blob copy inside same account is very quick, since it only copy the blob link, but not copy content. 
- The API to use is [Copy Blob (REST API) - Azure Storage | Microsoft Docs](https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob) ( Please note there are no header "x-ms-requires-sync:true".)

On Storage Explorer 1.25.0, 

- The big blob copy inside same account will take time, since it will copy content with AzCopy.
- The blob copy looks always use Sync Copy (e.g. for big page blob it will use https://docs.microsoft.com/en-us/rest/api/storageservices/put-page-from-url)

Suggestion: 
Please use Async blob copy when the source and destination blob are in same account with same blob type, it will be much quick than sync copy for big blob

### Steps to Reproduce

1. Copy a big blob (e.g. 1TB) inside same storage account with same blob type

### Actual Experience

On Storage Explorer 0.9.01,  it will finish very quick , in several seconds
On Storage Explorer 1.25.0, it will take a much long time (I don't wait for it finish). 

### Expected Experience

On Storage Explorer 1.25.0, the copy should also be finished in several seconds.

**Comment by MRayermannMSFT** [comment]
We're waiting on AzCopy to deliver us a flag which would allow us to use the server-side copy API. Once we have this flag we can investigate how we expose this flag. We'll put this in 1.27 for now, and at that time we'll re-evaluate where AzCopy is at with the flag.

Related to: https://github.com/microsoft/AzureStorageExplorer/issues/4464

**Comment by JasonYeMSFT** [comment]
AzCopy will not be delivering the flag in time for 1.28. We are going to move this issue further down the road for now.

**Comment by MRayermannMSFT** [comment]
Service team has requested that we do not make use of the server side copy. Therefore no flag will be added to AzCopy.
