### ISSUE TITLE
The soft deleted blob still displays with strikethrough after successfully undeleting it

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6022]
**Storage Explorer Version:** 1.26.0-dev
**Build Number:** 20220812.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.5 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.25.0)

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Switch to 'Active and soft deleted blobs' view.
4. Soft delete the blob -> The blob displays with strikethrough.
5. Undelete the blob.
6. Check whether the blob displays as active.

## Expected Experience ##
The blob displays as active.

## Actual Experience ##
The blob still displays with strikethrough.

## Additional Context ##

1. The blob displays as active after manually refreshing.
2. This issue doesn't reproduce on the build hotfix/20220810.2.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20220815.1. Fixed. So, we are going to close it.
