### ISSUE TITLE
Microsoft azure file storage error undefined reading 'version'

### ISSUE THREAD

**Issue by vidamaghami** [microsoft/AzureStorageExplorer#6023]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.25

### Regression From

1.10

### Architecture

x64

### Storage Explorer Build Number

20220803.08

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Manually adding a file share does work, but after a restart from Azure , same issue appears again.

Unable to retrieve child resources.

Details:
{
  "name": "TypeError",
  "message": "Cannot read properties of undefined (reading 'version')",
  "stack": "TypeError: Cannot read properties of undefined (reading 'version')\n    at isConnectionV1 (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:75535)\n    at FileShareNodeProducer.getAttachedFileShareNode (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:64098)\n    at C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:63030\n    at Array.map (<anonymous>)\n    at FileShareNodeProducer.produceAttachedFileShareNodes (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:63000)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Azure.Storage.FileShareProducer.produceAttachedFileShareNodes (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:84475)\n    at async Provider.executeOperation (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\providers\\Provider.js:28:16)\n    at async NodeProcessHostProxy._handleExecuteRequest (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:229:31)\n    at async NodeProcessHostProxy._handleMessage (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:182:24)"
}

### Steps to Reproduce

1. Launch Azure Storage 
2. Storage Accounts -> Attached Containers -> opening File Shares

### Actual Experience

Error message appears.

**Comment by JasonYeMSFT** [comment]
@vidamaghami Could you please follow the instructions in our [troubleshooting guide](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2204#error-occurred-while-adding-new-connection-typeerror-cannot-read-property-version-of-undefined) to clear the corrupted connection?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem we recommend opening a support ticket via the Azure portal. Alternatively you can open a new issue here.
