### ISSUE TITLE
There is no traffic in Fiddler when executing the action ''Reset Column Order' for tables

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6025]
**Storage Explorer Version:** 1.26.0-dev
**Build Number:** 20220815.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04
**Architecture:** ia32/x64
**How Found:** From running test case
**Regression From:** Previous release (1.24.3)

## Steps to Reproduce ##

1. Install and launch Fiddler -> Launch Storage Explorer.
2. Click 'Edit -> Configure Proxy' -> Select 'Use app proxy settings' -> Set the URL: 'http://localhost/' Port: '8888' -> Click 'OK'.
3. Expand one storage account -> Tables.
4. Create a new table -> Add one entity.
5. Right click the entity -> Click 'Reset Column Order'.
6. Check whether there is traffic in Fiddler.

## Expected Experience ##
There is traffic in Fiddler.

## Actual Experience ##
There is no traffic in Fiddler.

**Comment by craxal** [comment]
Network traffic is not a requirement to reset columns. Storage Explorer already has the column data it needs to reset column order without going to the server.
