### ISSUE TITLE
Cold tier support on Storage Explorer

### ISSUE THREAD

**Issue by fhryo-msft** [microsoft/AzureStorageExplorer#6027]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Storage is releasing Cold tier and looking for the support on tooling

### Desired Solution

Adding the support for new storage tier

### Alternatives and Workarounds

N/A

**Comment by jinglouMSFT** [comment]
Once SDK is ready for consumption, we will add the support.

**Comment by JasonYeMSFT** [comment]
We must have this fixed by the SDK or workaround it ourselves https://github.com/microsoft/AzureStorageExplorer/issues/6645
