### ISSUE TITLE
Connect to blob containers anonymously

### ISSUE THREAD

**Issue by shakanand** [microsoft/AzureStorageExplorer#603]
**Storage Explorer Version**:  1.4.0
**Platform/OS Version**: Windows
**Architecture**: ia32
**Regression From**: 

#### Steps to Reproduce: ####
Unable to connect to a public blob that is available at  (no keys are needed to access to this blob)
wasbs://2013@nytaxiblob.blob.core.windows.net/

This blob is used as a source for polybase in the below article. I would download the blob and move it to ADLS
 using Storage explorer
https://docs.microsoft.com/en-us/azure/sql-data-warehouse/load-data-from-azure-blob-storage-using-polybase

#### Expected Experience: ####
Connect to public blobs and browse the file system

#### Actual Experience: ####
Unable to connect to public blobs

**Comment by craxal** [comment]
It's unclear from your repro steps exactly what you're doing, so let me see if I understand correctly. You're trying to copy a blob from some storage account to an ADLS account, right? How are you attempting to connect to your storage account/blob container (sign-in, connection string, etc.)? How far do you get with your intended task? What error messages do you see? Can you provide any screenshots of your process?

Your blob account reference is confusing. I've never seen the "wasbs" protocol and have no idea how Storage Explorer is supposed to understand that. Also, the "2013@" portion of the hostname is unusual. I would expect just "nytaxiblob.blob.core.windows.net".

**Comment by shakanand** [comment]
I am trying to connect to blob using “connection string” option. This blob “nytaxiblob” is publicly available – there is no access key required to connect to this blob.
See the below error, access key is mandatory in Azure Storage explorer. But, the blob that I am trying to connect does not have any keys associated with it – it is publicly available for everyone.

Hope it is clear now. Let me know if you need more details.

[cid:image001.png@01D43F8D.D6A78B30]

**Comment by craxal** [comment]
I think I'm still confused. Is "nytaxiblob" the name of the _blob_ or the _storage account_ with a blob container that the blob is in?

If you're only trying to download a blob, you need a proper URL to the blob. You can enter that into a web browser, and the browser will download it. Storage Explorer doesn't support connecting to individual blobs.

**Comment by jrowlandjones** [comment]
@craxal how do I configure ASE to connect to a storage account which has one container with an access policy set to "container" to provide anonymous access to the container and its contents.
[https://docs.microsoft.com/en-us/azure/storage/blobs/storage-manage-access-to-resources](url)

Providing anonymous access is very useful for scenarios involving public datasets that need to be shared openly for read. @shakanand seems to want to have read access to the new york taxi dataset that someone has shared.

At the moment in 1.4.3 in ASE all options require some form of security to access a storage account. When trying to "connect with name and key" the account key cannot be left blank. The error message is "The key is not a valid base-64 value" and both the next and connect buttons are greyed out until an valid base-64 value has been added to the account key.
I have tried a few options: 
* specifying the container in the account name
* providing a dummy account key

Neither seems to work.

Any advice would be greatly appreciated.

**Comment by craxal** [comment]
Yet again (sorry for being slow), I'm unclear about the task you're trying to accomplish. Are you trying to access a specific blob and the data it contains or explore lists of blobs in a blob container? Is "nytaxiblob: the name of a _blob_, _blob container_, or _storage account_?

If it's a blob, Storage Explorer does not support "connecting" to an individual blob. All you need is a URL to the blob, and you can download it by entering the blob URL into your web browser.

If it's a blob container, you don't need to connect to the entire storage account. You can use a SAS URL to connect to the blob container.

If it's a storage account, you'll need a SAS token/connection string if you don't have the account key.

**Comment by apulliam** [comment]
The questions are regarding access to [Azure Open DataSets](https://azure.microsoft.com/en-us/services/open-datasets/catalog/).  The instructions for the these datasets provide instructions for accessing via Azure Notebooks and Databricks.  The python samples show a blank blob sas token.  For example:
```python
# Azure storage access info
azure_storage_account_name = "azureopendatastorage"
azure_storage_sas_token = r""
container_name = "gfsweatherdatacontainer"
folder_name = "GFSWeather/GFSProcessed"
```
It's not obvious whether Azure Storage Explorer allows anonymous access, and if it does, how to set up the connection.

**Comment by craxal** [comment]
@apulliam Anonymous access is indeed possible to set up in Storage Explorer:
1. Right-click the blob container you want to modify and select "Set Public Access Level..."
2. Select which level of access you want to permit for the container and click "Apply".

**Comment by craxal** [comment]
Closing this bug due to inactivity. If problems persist, please let us know and we'll revisit.

**Comment by craxal** [comment]
OK, so thanks to @apulliam, I managed to wrap my mind about what's being attempted here. 😆

In summation, if a container has been granted public access, theoretically, you should only need a URI to connect to it in Storage Explorer. However, Storage Explorer doesn't yet support connecting to public resources, because we always expect some form of authentication to be provided (sign-in, account key, or SAS).

With that cleared up, I'll reopen and tag this as a feature request.
