### ISSUE TITLE
Unable to retrieve child resources when working with .NET Windows storage emulator.

### ISSUE THREAD

**Issue by hithisiskathirvel** [microsoft/AzureStorageExplorer#6030]
Hi Team,
 I have faced below issue, Please help me out,

TIA

![image](https://user-images.githubusercontent.com/104485020/184826500-d562c32c-ab6b-40d3-bc20-8c96857ee8f0.png)

**Comment by sfrohreich83** [comment]
I am seeing this same issue

**Comment by hithisiskathirvel** [comment]
did u find  any solution

**Comment by sophiegonzalez3** [comment]
same here

**Comment by JasonYeMSFT** [comment]
Could you provide more details about the platform you are on, Storage Explorer version and what steps it takes for you to run into this issue? As the error messages suggests, you may have invalid characters in your resource name. What resource are you trying to access? Did you sign-in or attach to it?

**Comment by sfrohreich83** [comment]
I have restarted app and appears to be working now

**Comment by hithisiskathirvel** [comment]
> Could you provide more details about the platform you are on, Storage Explorer version and what steps it takes for you to run into this issue? As the error messages suggests, you may have invalid characters in your resource name. What resource are you trying to access? Did you sign-in or attach to it?


Azure storage explorer Version: 1.25.0

While creating a blob container it is created successfully. But once we give an refresh in the blob. The above mentioned error came.

Container Name: docrepo

**Comment by menozz** [comment]
same problem 
![image](https://user-images.githubusercontent.com/339491/185588540-3cfe596e-9403-4b90-89d8-450f2c2f4f25.png)

`  "name": "RestError",
  "message": "The specifed resource name contains invalid characters.\nRequestId:fb61c327-b595-40c8-8f1c-67034d15f503\nTime:2022-08-19T09:19:41.7299470Z",
  "stack": "RestError: The specifed resource name contains invalid characters.\nRequestId:fb61c327-b595-40c8-8f1c-67034d15f503\nTime:2022-08-19T09:19:41.7299470Z\n    at handleErrorResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:3159:19)\n    at C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:3095:49\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async StorageRetryPolicy.attemptSendRequest (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\storage-blob\\dist\\index.js:14445:24)\n    at async BlobApiVersionRequestPolicy.sendRequest (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-blob-extension\\dist\\src\\Clients\\BlobStorageClient.js:24:16)\n    at async StorageClientContext.sendOperationRequest (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:4932:31)\n    at async ContainerClient.getProperties (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\storage-blob\\dist\\index.js:22467:20)\n    at async ContainerClient.exists (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\storage-blob\\dist\\index.js:22382:13)\n    at async C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-blob-extension\\dist\\src\\Clients\\BlobServiceClient.js:64:25\n    at async Promise.all (index 1)",
  "code": "InvalidResourceName",
  "statusCode": 400
`

**Comment by MRayermannMSFT** [comment]
@robinstauntoncollins @menozz @hithisiskathirvel @sophiegonzalez3 @sfrohreich83 yes this is likely due to you using the deprecated .NET based storage emulator. You'll either need to migrate to Azurite or use a version 1.24 of Storage Explorer for now.

Can y'all enlighten us as to why you have not yet moved to Azurite? Doing so will help us understand how we treat this issue. Thanks.

**Comment by TurakKatase** [comment]
My team is impacted by this issue as well. The reason we hadn't yet moved to Azurite was due to the lack of support for table storage in v3 and some other needed feature missing from v2. That appears to have been solved.

**Comment by MRayermannMSFT** [comment]
We've restored compatibility with the old .NET emulator. Doing so was relatively easy. In the future though, we cannot guarantee that we will fix issues like this. We strongly recommend everyone move to Azurite as it is getting new features and fixes. If there is something blocking you from moving to Azurite please let them know here: https://github.com/Azure/Azurite/issues

**Comment by mithom** [comment]
> @robinstauntoncollins @menozz @hithisiskathirvel @sophiegonzalez3 @sfrohreich83 yes this is likely due to you using the deprecated .NET based storage emulator. You'll either need to migrate to Azurite or use a [version 1.24](https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.24.3) of Storage Explorer for now.
> 
> Can y'all enlighten us as to why you have not yet moved to Azurite? Doing so will help us understand how we treat this issue. Thanks.

We are not using azurite as visual studio 2019 does not support launching (or using if launched seperately) azurite. I have searched on how to configure it and could not find it. And it is said to not be backported. Since our license is version specific we do not plan to update to a new version of visual studio

**Comment by mithom** [comment]
For me the issue was resolved after updating
