### ISSUE TITLE
Unable to connect to edge storage blob on eflow from storage explorer

### ISSUE THREAD

**Issue by hakeemmissa** [microsoft/AzureStorageExplorer#6034]
Deployed eflow on windows 10 pro and confirmed edgeblobstorage modules running in docker with no errors

Connection string : 
DefaultEndpointsProtocol=https;BlobEndpoint=http://xx.xxx.24.254:11002/hmedgestoragesync;AccountName=hmedgestoragesync;AccountKey=sdgxoINCAKTMurbldr_UT17trog_6KdnvWM4ubskRBCLMGjQDa3yAW-Z2Xv2IhM3fsG7K8TL4SRhRO99pF6Wiw

Disabled firewall on windows host

Error
Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to http://xx.xxx.24.254:11002/hmedgestoragesync?comp=list&include=metadata failed, reason: connect ECONNREFUSEDxx.xxx.24.254:11002",

I have read about this error on several post but have not seen a solution that works for me. Thank you for your time.

**Comment by hakeemmissa** [comment]
Storage explorer version is 1.25.

**Comment by JasonYeMSFT** [comment]
ECONNREFUSED error usually indicates there is no service listening to the port at 11002. If you have access to the edge device, could you log into it and check if the IoT blob storage module is still running?

**Comment by hakeemmissa** [comment]
The service is indeed running on port 11002. the logs are fine and so is the result of inspecting the container
![image](https://user-images.githubusercontent.com/18409701/185231166-52f0a726-0d8a-4107-98a5-8346975e5662.png)

**Comment by hakeemmissa** [comment]
First line is a custom module that is writing to edge blob storage module on second line, that is synched with cloud blob storage

**Comment by hakeemmissa** [comment]
And maybe a related question is how do you copy a file out of eflow to the windows host?
I am unable to mount a share in eflow linux console because, apparently the "filesystem is readonly"

**Comment by JasonYeMSFT** [comment]
I did a little bit research and the container config looks correct to me. I think you can look at your docker host's network to see if there is any clue. Let's try pinging the host ip to see if it is reachable. Is you hosted machine a VM or a physical machine with an assigned public ip? If it's a VM maybe the ip address has changed (e.g. rebooted VM on Azure may get a different ip). Another potential cause is that there is a firewall blocking the requests.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still facing this issue we recommend opening a ticket via the Azure portal or you can open a new issue here.
