### ISSUE TITLE
Facing issue: Unable to retrieve blob containers

### ISSUE THREAD

**Issue by SindhuSami** [microsoft/AzureStorageExplorer#6036]
Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://mapssharedsthstorage01.blob.core.windows.net/?sv=2020-02-10&ss=bfqt&srt=sco&sp=rwlacuptfx&se=2030-06-22T16:45:28Z&st=2021-06-22T08:45:28Z&spr=https&SAS Token Redacted%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B&comp=list&include=metadata failed, reason: unable to get local issuer certificate",
  "stack": "FetchError: request to https://mapssharedsthstorage01.blob.core.windows.net/?sv=2020-02-10&ss=bfqt&srt=sco&sp=rwlacuptfx&se=2030-06-22T16:45:28Z&st=2021-06-22T08:45:28Z&spr=https&SAS Token Redacted%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B&comp=list&include=metadata failed, reason: unable to get local issuer certificate\n    at ClientRequest.<anonymous> (C:\\temp\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1491:11)\n    at ClientRequest.emit (node:events:526:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:526:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY",
  "code": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"
}

**Comment by JasonYeMSFT** [comment]
Could you try these steps to see if you can use system proxy or re-add the missing certificates? https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2204#ssl-certificate-issues

**Comment by j-c-servier** [comment]
> Could you try these steps to see if you can use system proxy or re-add the missing certificates? https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2204#ssl-certificate-issues

That worked for me!  I had same issue ("unable to get local issuer certificate") for File Shares.  Used system proxy and now I can access file shares.  Thank you, Jason.

**Comment by JasonYeMSFT** [comment]
Closing as mitigated.

**Comment by akpaul1** [comment]
https://dfwblobstorage.blob.core.windows.net/ewcmediacontainer/eatwisconsincheese/media/content/jawanfreehd6s.html
