### ISSUE TITLE
Access error to Storage Account from Microsoft Storage Account Explorer

### ISSUE THREAD

**Issue by byvalentino** [microsoft/AzureStorageExplorer#6038]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.25.1

### Architecture

x64

### Storage Explorer Build Number

1.25.1

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://ingeststtvdptst.file.core.windows.net/?comp=list failed, reason: unable to verify the first certificate",
  "stack": "FetchError: request to https://ingeststtvdptst.file.core.windows.net/?comp=list failed, reason: unable to verify the first certificate\n    at ClientRequest.<anonymous> (C:\\Users\\VAISE\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:114361)\n    at ClientRequest.emit (node:events:526:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:526:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "UNABLE_TO_VERIFY_LEAF_SIGNATURE",
  "code": "UNABLE_TO_VERIFY_LEAF_SIGNATURE"
}

### Steps to Reproduce

1. Launch Storage Explorer
2. Access Blob Storage
3. Expand 

### Actual Experience

Can't connect do data

### Expected Experience

Connect to data

### Additional Context

Encription error

**Comment by JasonYeMSFT** [comment]
Could you try these steps to see if you can use system proxy or re-add the missing certificates? https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2204#ssl-certificate-issues

**Comment by davsta90** [comment]
I have a related issue with the same build.
1. On Server 2022, the explorer lists the storage accounts of my group subscriptions, but on a PIM subscription I receive this error Unable to retrieve child resources.
Details:
{
  "message": "{}"
}
2. On Win11, instead, the storage accessed via PM is not listed and no error is triggered when I try to refresh.

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. If you still have problem after taking our recommended action, please open a new issue.

**Comment by RaphHaddad** [comment]
I can confirm I was having the above issue but your solution worked.

I had created the certificates, ran azurite using the created certificates, imported the certificates, but the explorer was not connecting to the emulated storage account. When I used 'system proxy' as you suggested, I was able to connect.
