### ISSUE TITLE
Download to Root of Local Drive Fails

### ISSUE THREAD

**Issue by philkloose** [microsoft/AzureStorageExplorer#6039]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.25.1

### Architecture

i86

### Storage Explorer Build Number

20220809.7

### Platform

Windows

### OS Version

Windows Server 2022 (OS Build 20348.887)

### Bug Description

I am unable to download blobs to my local disk if my destination is in the root of a drive.  Creating a folder in the root of the drive and using that as the destination is a reasonable workaround, but the error message I received in my original attempt would not have led me to that solution.

### Steps to Reproduce

1. Navigate to a container with a blob you'd like to download.
2. Right-click on the blob, select **Download**
3. Select the root of a drive (e.g. **MyDrive (H:)**)
4. Click **Select Folder**
5. The download will fail with an error shown in the Activities pane.

### Actual Experience

You'll see errors like the following in the AzCopy Log File --

`2022/08/18 18:45:51 ERR: [P#0-T#8] DOWNLOADFAILED: https://xxxxxxxxxxxxxxxxx.blob.core.windows.net/xxxxxxxxxxxx-rehydratedforrestore/2016%20Jan%20-%20Jun_rehydrated.bak?se=2022-09-17T18%3A45%3A43Z&sig=-REDACTED-&sp=rl&sr=c&sv=2021-04-10 : 000 : File Creation Error destination file has no known flags that could cause issue (current set: 0) and azcopy was unable to clear the flag(s), so access will be denied: Access is denied.`

### Expected Experience

I would expect this to work, but at the very least it would be nice if users weren't allowed to or warned against selecting the root of a drive as the download destination since the error message they will receive from AzCopy isn't helpful.

**Comment by JasonYeMSFT** [comment]
@philkloose Do you have Windows installed on the drive you are trying to download data to? I can only reproduce this error if I download data to my drive with Windows installed.

**Comment by philkloose** [comment]
@JasonYeMSFT I do not have Windows installed on the destination drive.  It was my H: drive and my Windows install lives on my C: drive.

**Comment by JasonYeMSFT** [comment]
@philkloose Could you check if there is any protection bit set on the drive you are trying to download to? Does it have bitlocker enabled?

**Comment by philkloose** [comment]
@JasonYeMSFT Nope, no BitLocker or protection bit that I'm aware of.  It's an Azure VM with a disk attached.  The H: drive is a GPT (primary) partition, Basic, single volume, NTFS.

**Comment by JasonYeMSFT** [comment]
I did some experimentation offline and this might be due to the security settings of the drive. On Windows, if I goto Properties of the drive -> Security and remove the write permission on the root of the drive (e.g. for the user group entry that grants write permission, make it only apply to subfolders and files), the same error will show up if I attempt to download to the drive.

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. If you have more clue on what might be blocking access to the local disk, please comment below or open a new issue.
