### ISSUE TITLE
The ADLS Gen1 explorer displays empty under the 'Light' theme

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6040]
**Storage Explorer Version:** 1.26.0-dev
**Build Number:** 20220818.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.5 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.25.1)

## Steps to Reproduce ##

1. Launch Storage Explorer -> Change the theme to "Light".
2. Expand 'Data Lake Storage Gen1 (deprecated)' node -> Open one ADLS Gen1 account.
3. Check whether the explorer displays well.

## Expected Experience ##
The explorer displays well.
The screenshot under the 'Dark' theme:
![image](https://user-images.githubusercontent.com/87792676/185580861-3c29ce95-618a-4728-9e04-97230bb74db6.png)

## Actual Experience ##
The explorer displays empty.
![image](https://user-images.githubusercontent.com/87792676/185580657-dc24c71d-cc6f-432a-987e-cd11667c8896.png)

## Additional Context ##
This issue only reproduces under the 'Light' theme.

**Comment by JasonYeMSFT** [comment]
May be related to https://github.com/microsoft/AzureStorageExplorer/issues/6031

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220826.1. Fixed.
