### ISSUE TITLE
Unable to retrieve child resources - after upgrade to the latest version

### ISSUE THREAD

**Issue by rene-medina** [microsoft/AzureStorageExplorer#6041]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.25.1

### Architecture

x64

### Storage Explorer Build Number

20220809.7

### Platform

Windows

### Bug Description

Unable to retrieve child resources.

Details:
{
  "name": "RestError",
  "message": "{\"name\":\"RestError\",\"code\":\"UNABLE_TO_GET_ISSUER_CERT_LOCALLY\",\"request\":{\"url\":\"https://management.azure.com//subscriptions/xxxxxxxxxxx/resources?api-version=2014-04-01&$filter=resourceType%20eq%20%27Microsoft.ClassicStorage%2FstorageAccounts%27%20or%20resourceType%20eq%20%27Microsoft.Storage%2FstorageAccounts%27\",\"headers\":{\"authorization\":\"Bearer JSON Web Token Redacted\",\"user-agent\":\"Microsoft Azure Storage Explorer/1.25.1 (win32)\"},\"method\":\"GET\",\"timeout\":30000,\"disableKeepAlive\":false,\"withCredentials\":false,\"requestId\":\"d7bbac7b-a474-4981-b169-419b87f36b14\",\"allowInsecureConnection\":true,\"enableBrowserStreams\":false}}"
}

### Steps to Reproduce

1. Upgrade to 1.25.1 - the error pops-up during installation

### Expected Experience

Install and resume in original window pre-installation

**Comment by JasonYeMSFT** [comment]
Could you try these steps to see if you can use system proxy or re-add the missing certificates? https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2204#ssl-certificate-issues

**Comment by davsta90** [comment]
I have a related issue with the same build.

On Server 2022, the explorer lists the storage accounts of my group subscriptions, but on a PIM subscription I receive this error Unable to retrieve child resources.
Details:
{
"message": "{}"
}
On Win11, instead, the storage accessed via PM is not listed and no error is triggered when I try to refresh.

importing the certificate did not help.
![image](https://user-images.githubusercontent.com/88048110/186488191-b97e1563-2a97-407e-b168-c6cf59514b87.png)

**Comment by rene-medina** [comment]
Thank you Jason, I'll give it a try and let you know, 
Thanks,
-RM 

    On Friday, August 19, 2022 at 05:04:12 PM EDT, JasonYeMSFT ***@***.***> wrote:  
 
 


Could you try these steps to see if you can use system proxy or re-add the missing certificates? https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2204#ssl-certificate-issues

**Comment by MRayermannMSFT** [comment]
Since we haven't heard anything from you in over 28 days we're going to close this issue. If you're still facing this issue, we recommend opening an Azure support ticket via the portal, or you can open a new issue here. Thanks.
