### ISSUE TITLE
The 'File Changes Detected' dialog pops up again when saving files with changes even if the checkbox is checked at its first change

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6042]
**Storage Explorer Version**: 1.26.0-dev
**Build Number**: 20220822.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.5 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Open the blob -> Make some changes then save it.
4. There is a detected dialog -> Select 'Upload' and check the checkbox -> Click 'Apply'.
5. Open the blob -> Make some changes then save it.
6. Check no detected dialog pops up.

## Expected Experience ##
No detected dialog pops up.

## Actual Experience ##
A detected dialog pops up.
![image](https://user-images.githubusercontent.com/41351993/185867049-3232d566-1ba7-4e44-84cf-a93c281ad664.png)

## Additional Context ##
This issue reproduces regardless of selecting any of the options in the 'File Changes Detected' dialog.

**Comment by MRayermannMSFT** [comment]
@v-xianya for clarification, in step 5, are you saying that you double clicked on the blob again in Storage Explorer? If so then this is expected. Every time you double click/use the open command on a blob, Storage Explorer will:
1. Download the blob to a unique location
2. Open it in the default editor
3. Watch that specific file for changes

The checkbox only applies to that specific file representation of the blob. Does that make sense?

**Comment by v-xianya** [comment]
@MRayermannMSFT Thanks for the clarification. It makes sense. 
We are going to close this issue.
