### ISSUE TITLE
error and can't reauthen to mystroageaccount using 

### ISSUE THREAD

**Issue by benjarongn** [microsoft/AzureStorageExplorer#6045]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.25.1

### Regression From

not sure

### Architecture

x64

### Storage Explorer Build Number

20220809.7

### Platform

Windows

### Bug Description

{
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80\\\",\\n  \\\"stack\\\": \\\"Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80\\\\n    at ClientRequest.onError (C:\\\\\\\\Users\\\\\\\\benjaron\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\tunnel-agent\\\\\\\\index.js:177:17)\\\\n    at Object.onceWrapper (node:events:646:26)\\\\n    at ClientRequest.emit (node:events:526:28)\\\\n    at Socket.socketErrorListener (node:_http_client:442:9)\\\\n    at Socket.emit (node:events:526:28)\\\\n    at emitErrorNT (node:internal/streams/destroy:157:8)\\\\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\\\\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)\\\",\\n  \\\"code\\\": \\\"ECONNRESET\\\"\\n}\""
}

### Steps to Reproduce

1. Explore storage 
2. Could not access resources for this tenant. You may need to reauthenticate. See the error details for more information
3. Error detail as above

### Actual Experience

![image](https://user-images.githubusercontent.com/81170385/186110474-ffb2d70a-4807-49eb-8e41-44808059ae0d.png)

### Expected Experience

can explore same as portal.

**Comment by JasonYeMSFT** [comment]
Are you behind a proxy? If you are, you will need to go to Settings and choose "Use app proxy" and enter your proxy settings or choose "Use system proxy".

**Comment by MRayermannMSFT** [comment]
Since we haven't heard anything from you in over 28 days we're going to close this issue. If you're still facing this issue, we recommend opening an Azure support ticket via the portal, or you can open a new issue here. Thanks.
