### ISSUE TITLE
Attached Blob Container Error

### ISSUE THREAD

**Issue by donpare** [microsoft/AzureStorageExplorer#6046]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.25.1

### Architecture

x64

### Storage Explorer Build Number

20220809.7

### Platform

Windows

### OS Version

Windows 11

### Bug Description

Cannot read properties of undefined (reading 'version') error when connecting to storage after login.

### Steps to Reproduce

Launch Storage Explorer
Login with Azure account credentials
Click on uploaded ingestiondata object

### Actual Experience

Launch Storage Explorer
Login with Azure account credentials
Click on uploaded ingestiondata object
Cannot read properties of undefined (reading 'version') error box appears.

### Expected Experience

view previously uploaded data (uploaded using AZCopy).

**Comment by TimothyFerrelli** [comment]
I had this same issue, I opened up Microsoft Azure Storage Explorer and Detached the ingestiondata blob storage. I then Connect to Azure resources
![image](https://user-images.githubusercontent.com/98750473/187210030-d5d1a9c3-f717-4b57-85de-fdb456f5fea6.png)

Blob Container
![image](https://user-images.githubusercontent.com/98750473/187209976-61af4081-3c50-4691-9f9d-f95c54f9b295.png)

Shared access signature URL (SAS) 
![image](https://user-images.githubusercontent.com/98750473/187209855-a6f4162e-e772-4e95-bba7-ca4e1e7487c6.png)

Once I did that, It opened up for me.

**Comment by JasonYeMSFT** [comment]
@donpare Could you try these steps to remove the potentially corrupted connection data and re-attach it? https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2204#error-occurred-while-adding-new-connection-typeerror-cannot-read-property-version-of-undefined
