### ISSUE TITLE
There is a successful activity log when deleting one empty folder in one attached file share which SAS URL is created by an access policy (List, Read)

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6047]
**Storage Explorer Version:** 1.26.0-dev
**Build Number:** 20220824.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.5 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** Ad-hoc testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> File Shares.
2. Create a file share -> Create a folder.
3. Right click the file share -> Click 'Manage Access Policies...'.
4. Add one access policy with 'Read, List' permissions -> Generate a SAS URL via the access policy.
5. Attach the file share via the SAS URL.
6. Switch to the attached file share -> Try to delete the folder.
7. Check whether there is a failed activity log.

## Expected Experience ##
There is a failed activity log.

## Actual Experience ##

1. There is a successful activity log
2. The folder still displays.

![image](https://user-images.githubusercontent.com/87792676/186360301-6e01b84c-b896-471d-918c-c9eafa5deab5.png)

## Additional Context ##

1. This issue doesn't reproduce when deleting one no-empty folder.
2. This issue doesn't reproduce when attaching via SAS permissions.

**Comment by JasonYeMSFT** [comment]
AzCopy attempts to list the directory to delete, get an 404 because it doesn't have enough permission and assumes it has been deleted. There is no way we can tell whether the access policy has the required permission. We'll keep this behavior as by design for now.

**Comment by v-kellyluo** [comment]
@JasonYeMSFT ,thank you for the update, but this issue doesn't reproduce for ADLS Gen2 folder, there is a failed activity log when deleting one empty ADLS Gen2 folder, is there any difference?
![image](https://user-images.githubusercontent.com/87792676/186558636-0872c5a4-35e1-48cf-a11f-76bafe683c71.png)
