### ISSUE TITLE
Bypass doesn't take effect for 'Table Statistics'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6048]
**Storage Explorer Version**: 1.26.0-dev
**Build Number**: 20220824.2
**Branch**: main
**Platform/OS**: Windows 10
**Architecture**: ia32
**How Found**: From running test case
**Regression From**: Previous release (1.21.3)

## Steps to Reproduce ##
1. Install and launch Fiddler -> Launch Storage Explorer.
2. Click 'Edit -> Configure Proxy' -> Select 'Use app proxy settings' -> Set the URL: 'http://localhost' Port: '8888' -> Click 'OK'.
3. Expand one storage account -> Tables.
4. Open one table -> Click 'Table Statistics' -> There is traffic in the Fiddler.
5. Click 'Edit -> Configure Proxy' -> Type [".table.core.windows.net"] to Bypass field -> Click OK.
6. Click 'Table Statistics' -> Check there is no traffic.

## Expected Experience ##
There is no traffic.

## Actual Experience ##
There is traffic.

## Additional Context ##
1. There is no traffic for 'Table Statistics' if cancelling the bypass for tables.

**Steps:**

- Install and launch Fiddler -> Launch Storage Explorer.
- Click 'Edit -> Configure Proxy' -> Select 'Use app proxy settings' -> Set the URL: 'http://localhost' Port: '8888'.
- Type [".table.core.windows.net"] to Bypass field -> Click OK.
- Expand one storage account -> Tables.
- Open one table -> Click 'Table Statistics' -> No traffic in the Fiddler.
- Click 'Edit -> Configure Proxy' -> Delete the string [".table.core.windows.net"] in the Bypass field -> Click OK.
- Click 'Table Statistics' -> Check there is traffic.

**Actual:** No traffic in the Fiddler.

2. This issue doesn't reproduce when using 'environment variables'.

**Comment by craxal** [comment]
From what I can gather, the correct proxy settings are getting passed to the constructor for the Azure table client. So it seems that the table client is not picking up the new proxy settings. I'm following up with the table client SDK team.

**Comment by craxal** [comment]
The SDK was working fine. The problem was that all worker processes were using environment variables to communicate the proxy settings which interfere with libraries based on `core-http` or `core-rest`. This was resolved by creating a new worker pool that uses more a predictable, dynamic means of communicating those proxy settings.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220922.3. Fixed.
