### ISSUE TITLE
Please add "Do not show again" for "Enable Soft Delete"

### ISSUE THREAD

**Issue by alvipeo** [microsoft/AzureStorageExplorer#6049]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Whenever I try to delete something from Blob storage I get asked if I want to "Enable Soft Delete"

### Desired Solution

Add a "Do not show again" checkbox

### Additional Context

If I wanted to have soft delete enabled I'd made it in the portal

**Comment by JasonYeMSFT** [comment]
The main purpose of the dialog is to let you confirm the delete action. Even if we hide the button we will still prompt every time in case you accidentally pressed Delete key.

**Comment by alvipeo** [comment]
Confirmation is fine! But asking to enable feature every time I just need to delete a blob - annoying really.

**Comment by MRayermannMSFT** [comment]
@alvipeo so to be clear, you are ok with there being a dialog to confirm deleting, you  just don't want it to have the 3rd button for enabling soft delete?

**Comment by alvipeo** [comment]
@MRayermannMSFT  yes, the delete confirmation is a must! But it has nothing to do with enabling features

**Comment by MRayermannMSFT** [comment]
Got it. We'll be evaluating this over the course of the next release cycle. If we choose to remove the button it'll happen in 1.27. We'll update this issue once we've made a decision. :)

**Comment by MRayermannMSFT** [comment]
Hey @alvipeo we've evaluated usage of the "Enable soft delete" button and based on what we're seeing, we're going to leave the button in the dialog. Data protection is very important to us, so if people are using it to help them learn about/enable soft delete we feel it is good to leave it in.

Is there anything we can do with the button other than removing it that would help you feel less annoyed by it?

**Comment by alvipeo** [comment]
I'd just add a checkbox "Do not ask again". Is that ok?

**Comment by MRayermannMSFT** [comment]
Sure.

**Comment by richardMSFT** [comment]
Will be available in 1.27.0
