### ISSUE TITLE
"Add an account..." is misleading for account management

### ISSUE THREAD

**Issue by kjhf** [microsoft/AzureStorageExplorer#6050]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

The "Add an account..." link in account management is misleading as it opens the "Connect to Azure Storage" window, when the user actually wants to do an azure sign-in. This is because of the overload of the term account, where in this context an account refers to an azure storage resource, but typically an account refers to a user account. This leads to a negative experience if the user wants to actually do an az login, rather than connect to a resource with a currently signed in tenancy

### Desired Solution

Clarify the "Add an account..." link to be "Connect to a resource", and/or make the subscription resource obvious for a new sign-in option to the Connect to Azure Storage window, and/or add a new link/button that allows for signin (instead)

### Alternatives and Workarounds

Use "Subscription" resource, or the Get Started page has sign in with Azure - this can be used instead

**Comment by craxal** [comment]
@kjhf Actually, "account" in this context is meant to refer to an Azure user account. This panel is meant only to manage signed in Azure accounts, tenants, and subscriptions. What we can do is modify the behavior of the "Add an account..." link to open the Connect dialog to the appropriate starting panel to prevent confusion.

**Comment by craxal** [comment]
Changes for the dialog that opens and clarifying the meaning of the link have been merged.
