### ISSUE TITLE
Accessing Storage Emulator Blob Containers Error: Unable to retrieve child

### ISSUE THREAD

**Issue by HassanBadir** [microsoft/AzureStorageExplorer#6053]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.25.1

### Regression From

1.24.3

### Architecture

x64

### Platform

Windows

### OS Version

Windows 11

### Bug Description

I can't work with Storage Emulator Blob Containers, the moment i try to access them Error window appear.

this worked fine on 1.24.3 version, it doesn't work on 1.25.1

I even uninstalled, and reinstalled to make sure both versions.

I attached the log file since it's too long, this is a short part of it.
```
Unable to retrieve child resources.

Details:
{
  "name": "RestError",
  "message": "The specifed resource name contains invalid characters.\nRequestId:3a11da26-23cd-4368-adcd-976d47d9a67a\nTime:2022-08-25T08:29:12.4769651Z",
  "stack": "RestError: The specifed resource name contains invalid characters.\nRequestId:3a11da26-23cd-4368-adcd-976d47d9a67a\nTime:2022-08-25T08:29:12.4769651Z\n    at handleErrorResponse (C:\\Users\\hassanbadir\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:3159:19)\n    at C:\\Users\\hassanbadir\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\core-http\\dist\\index.js:3095:49\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async StorageRetryPolicy.attemptSendRequest (C:\\Users\\hassanbadir\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@azure\\storage-blob\\dist\\index.js:14445:24)\n    at async BlobApiVersionRequestPolicy.sendRequest (C:\\Users\\hassanbadir\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-
```

[ErrorLog.txt](https://github.com/microsoft/AzureStorageExplorer/files/9422950/ErrorLog.txt)

### Steps to Reproduce

Simple opening Explorer -> Emulator -> Blob Containers ... immedietly i get error window 

![image](https://user-images.githubusercontent.com/37299319/186615555-cbecab17-ef86-42d3-b4a7-e729c030db5b.png)

### Actual Experience

Simple opening Explorer -> Emulator -> Blob Containers ... immedietly i get error window 

![image](https://user-images.githubusercontent.com/37299319/186615555-cbecab17-ef86-42d3-b4a7-e729c030db5b.png)

**Comment by dipalikorat** [comment]
I am getting the same issue. would you please give an estimate when this will be fixed? It's a blocker for my work.

**Comment by jinglouMSFT** [comment]
Thanks for the report. From the two attached log files, the "invalid" container was the $blobchangefeed container.  We added the support of this container in v1.25.0.  One question for you all, are you using Azurize as your emulator or the Windows storage emulator?  If Windows storage emulator, since it has already been deprecated (see here:    
https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator), it will not work with the $blobchangefeed container. We recommend using Azurite (https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio) as the storage emulator instead.  You should not run into the above error with Azurite.

**Comment by winseros** [comment]
I was using the [Azure Storage Emulator](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator) when faced the issue.

**Comment by jinglouMSFT** [comment]
@winseros Have you tried Azurite, a cross platform Azure storage emulator?

**Comment by dipalikorat** [comment]
I am using Azurite and still not working. It doesn't give me any error but not showing any containers either.

**Comment by jinglouMSFT** [comment]
Dup of #6030. Please follow #6030 for the latest update of the issue. Thanks.

**Comment by jinglouMSFT** [comment]
@dipalikorat If you just switched to Azurite from the Windows storage emulator, your existing content in the Windows storage emulator would exist in Azurite. Unfortunately the emulators don't have the export/import features.

**Comment by winseros** [comment]
> @winseros Have you tried Azurite, a cross platform Azure storage emulator?

For me everything works fine with Azurite,
