### ISSUE TITLE
Download an entire blob container

### ISSUE THREAD

**Issue by vanillajonathan** [microsoft/AzureStorageExplorer#6055]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I am unable to download the entire contents of a blob container.

### Desired Solution

Right-click on a blob container and have a "Download Container" entry.

### Alternatives and Workarounds

I have to select all blobs on one page (up to 100) and download those then click on next page, and repeat.

**Comment by jinglouMSFT** [comment]
Dup of #5050
