### ISSUE TITLE
There is an extra scrollbar in the 'Shared Access Signature' dialog for one table/storage account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6056]
**Storage Explorer Version**: 1.26.0-dev
**Build Number**: 20220826.1
**Branch**: main
**Platform/OS**: Windows 10
**Architecture**: ia32
**How Found**: From running test cases
**Regression From**: Previous release (1.25.1)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create one table -> Right click it.
3. Click 'Get Shared Access Signature...'.
4. Check there is no extra scrollbar in the 'Shared Access Signature' dialog.

## Expected Experience ##
There is no extra scrollbar.

## Actual Experience ##
There is an extra scrollbar.
![image](https://user-images.githubusercontent.com/41351993/186846640-1a5b4df1-66ed-446c-beea-7c42df912fef.png)

**Comment by v-xianya** [comment]
This issue also reproduces for storage account.
![image](https://user-images.githubusercontent.com/41351993/187339720-7c48538e-26bb-4eef-920c-fe667fb722ac.png)

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220901.1. 
1. There is no extra scrollbar for tables.
2. There is an extra scrollbar for storage accounts.

**Comment by JasonYeMSFT** [comment]
I have bumped the height of the account SAS dialog.

**Comment by v-kellyluo** [comment]
Verified this issue on the main build/20220914.3. Fixed. So, we are going to close it.
