### ISSUE TITLE
Load Storage Account Error

### ISSUE THREAD

**Issue by dipalikorat** [microsoft/AzureStorageExplorer#6057]
When I try to get access to any of the storage account, it gives me this error
Unable to establish connection using current proxy settings. Please verify current settings by accessing the proxy dialog in the toolbar.
The custom connection with ID 'storage account name' cannot be found.

This issue has started after I updated my storage explore version to v1.25.1.

**Comment by JasonYeMSFT** [comment]
Have you tried enabling proxy in the proxy settings?

**Comment by MRayermannMSFT** [comment]
Since we haven't heard anything from you in over 28 days we're going to close this issue. If you're still facing this issue, we recommend opening an Azure support ticket via the portal, or you can open a new issue here. Thanks.
