### ISSUE TITLE
There is no action 'Preview...' for blobs under the Snapshots/Versions view

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6059]
**Storage Explorer Version**: 1.26.0-dev
**Build Number**: 20220829.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: From running test cases
**Regression From**: Not a regression 

## Steps to Reproduce ##
1. Expand one non-ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Right click the blob -> There is an action 'Preview...'.
4. Click 'Manage History -> Manage Snapshots'.
5. Right click the blob -> Observe there is an action 'Preview...'.

## Expected Experience ##
There is an action 'Preview...'.

## Actual Experience ##
There is no action 'Preview...'.
![image](https://user-images.githubusercontent.com/41351993/187139805-19dd738f-a9e2-4e9e-b299-fb22676f4e72.png)

## Additional Context ##
1. This issue also reproduces for blobs under Version view.
![image](https://user-images.githubusercontent.com/41351993/187141437-3892c360-38fa-4d85-995f-087bd7181b24.png)

2. For one ADLS Gen2 blob, there is an action 'Preview...' under the Snapshots view.
![image](https://user-images.githubusercontent.com/41351993/187139493-6d6a6523-54bb-40ff-87ea-d599697c0923.png)

**Comment by JasonYeMSFT** [comment]
I think this would be good to have for this feature.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20220901.1. Fixed. So, we are going to close it.
![image](https://user-images.githubusercontent.com/41351993/187822089-065908b0-c0d0-4d25-86f6-06911df29b19.png)
