### ISSUE TITLE
Unable to authenticate to Azure

### ISSUE THREAD

**Issue by unknowndpi** [microsoft/AzureStorageExplorer#6062]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.25.1

### Architecture

i86

### Storage Explorer Build Number

20220809.7

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Can't login to Azure Storage Explorer as it redirects to a link that is a localhost.

### Steps to Reproduce

1. Launch Storage Explorer
2. Click 'Sign in with Azure'
3. Select 'Azure' as environment, click Next
4. Link to pick an account - https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize?scope=......
5. Once you click the account in step 4, it attempts to load a link to localhost which fails - https://localhost:22973/?code=0.ATEAS....

### Actual Experience

Unable to login to Azure Storage Explorer.

### Additional Context

Previously had Per-User MFA enabled, now conditional MFA, should be same result.

**Comment by unknowndpi** [comment]
Note no proxy is in use

**Comment by unknowndpi** [comment]
Switching settings from the recommended 'Default Web Browser' (Edge 104.0.1293.70) to 'Integrated Sign-in' is a workaround

**Comment by JasonYeMSFT** [comment]
What did you see in step 5 when it attempts to load from the localhost? Does the browser gives any error message or it doesn't respond?

**Comment by unknowndpi** [comment]
The connection for this site is not secure.
localhost sent an invalid response.
ERR_SSL_PROTOCOL_ERROR

**Comment by JasonYeMSFT** [comment]
The cause might be something forcing the localhost to use https, which isn't supported yet. Could you take a look at this issue and see if you can find anyone describing your situation? https://github.com/microsoft/AzureStorageExplorer/issues/4342

**Comment by unknowndpi** [comment]
Adding comments to both issue numbers in case someone searches it.

Disabling following flag is the solution in MS Edge (tested in version 104) - edge://flags/#edge-automatic-https 

Cache needs to be cleared otherwise HSTS will report 'localhost' domain with flag _dynamic_upgrade_mode: FORCE_HTTPS_
You can query HSTS by going to edge://net-internals/#hsts

Alternative workaround is as mentioned previously, change Azure Storage sign-in with setting to _Integrated Sign-in_

**Comment by CZEMacLeod** [comment]
Just had this same issue in the latest version of Azure Storage Explorer - so obviously this is still an issue and is not fixed.

[Window Title]
Microsoft Azure Storage Explorer

[Main Instruction]
Microsoft Azure Storage Explorer

[Content]
Version: 1.30.0
AzCopy Version: 10.19.0

Platform: Windows
Architecture: x64 
Build Number: 20230609.2 
Commit: 8d5719a5ab 
Support ID: 9671910f-e0d9-af3f-e597-c383464c87c2 

Copyright © 2023 Microsoft. All rights reserved.

[OK]

Did manage to work around this with using the integrated sign-in - but it wasn't easy to either find this issue or work out what was wrong.

**Comment by DimitryNechaev** [comment]
Just had the same experience, and funny enough my default browser is Edge, so it's all Microsoft environment all way through and it does not work. Got away by using the integrated sign-in, but that's shame they don't bother fixing so long-lasting bug that blocks using the app.
