### ISSUE TITLE
The value of Attributes column is not localized in one file share

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6064]
**Storage Explorer Version:** 1.26.0-dev
**Build Number:** 20220829.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.5 (Apple M1 Pro)
**Languages:** All languages
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select 'Deutsch' -> Restart Storage Explorer.
3. Expand one storage account -> File Shares.
4. Create a file share -> Upload a file -> Create a folder.
5. Check whether the value of Attributes column is localized.
 
## Expected Experience ##
The value of Attributes column is localized.

## Actual Experience ##
The value of Attributes column is not localized.
![image](https://user-images.githubusercontent.com/87792676/187174013-847295e0-e09b-44bc-8107-3619201cb6fd.png)

**Comment by JasonYeMSFT** [comment]
These strings directly come from the service. There is no way we can localize them.
