### ISSUE TITLE
Fail to clone/paste one blob under the attached blob container which SAS URL is created by 'User delegation key' (full permissions)

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6065]
**Storage Explorer Version**: 1.26.0-dev
**Build Number**: 20220830.1
**Branch**: main
**Platform/OS**: Windows 10
**Architecture** ia32
**How Found**: From running test cases
**Regression From**: Not a regression 

## Steps to Reproduce ##
1. Select one storage account -> Give the account with 'Storage Blob Data Contributor' rbac role.
2. Expand the storage account -> Blob Containers.
3. Create one blob container -> Upload one blob to it.
4. Right click the blob container -> Click 'Get Shared Access Signature...'.
5. Select 'User delegation key' -> Select all permissions -> Click 'Create'.
6. Copy the SAS URL -> Attach the blob container via the SAS URL.
7. Go to the attached blob container.
8. Select the blob -> Clone the blob with a valid name.
9. Check whether succeeds to clone it.

## Expected Experience ##
Succeed to clone it.

## Actual Experience ##
Fail to clone it.
![image](https://user-images.githubusercontent.com/41351993/187366462-69ab2cb8-259c-4a1c-874b-44b9b6a7e4fb.png)

`{
  "message": "\"UnexpectedCancel\""
}`
## Additional Context ##
1. This issue also reproduces when pasting one blob.
2. This issue doesn't reproduce when uploading/renaming one blob.

**Comment by JasonYeMSFT** [comment]
AzCopy uses Get Account Information API during the s2s copy if it is set to preserve access tier. and it doesn't support user delegation SAS at the moment. https://docs.microsoft.com/en-us/rest/api/storageservices/get-account-information#authorization. A workaround could be disabling preserve access tier.

**Comment by JasonYeMSFT** [comment]
Talked to AzCopy about this issue and they said they will improve the error reporting for this scenario. Other than that, the result is expected.
