### ISSUE TITLE
An error occurs when creating SAS URL by selecting 'User delegation key & access policy'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6066]
**Storage Explorer Version**: 1.26.0-dev
**Build Number**: 20220830.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.5 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: From running test cases
**Regression From**: Not a regression 

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Right click one blob container -> Click 'Manage Access Policies...'.
3. Add one access policy -> Save it.
4. Right click the blob container -> Click 'Get Shared Access Signature...'.
5. Select 'User delegation key' -> Select an access policy -> Click 'Create'.
6. Check no error occurs.

## Expected Experience ##
No error occurs.

## Actual Experience ##
An error occurs.
![image](https://user-images.githubusercontent.com/41351993/187376495-bef109f8-ae94-4989-88ed-7e9e5c9ad901.png)

**Comment by JasonYeMSFT** [comment]
If generating SAS with user delegation key, it cannot use an access policy. I am working on the UI change to hide and ignore the access policy if generating SAS with user delegation key.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20220901.1.
 The 'Access policy' option is hided when selecting 'User delegation key'. The issue got fixed. So, we are going to close it.
 
![image](https://user-images.githubusercontent.com/41351993/187819244-bd6e746b-e1bb-4ab2-979a-7b71fb6eceb3.png)
