### ISSUE TITLE
error on opening Blob Containers or File Shares

### ISSUE THREAD

**Issue by avn2006** [microsoft/AzureStorageExplorer#6067]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.25.1

### Regression From

1.22.1

### Architecture

x64

### Platform

Windows

### Bug Description

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://xxxx.blob.core.usgovcloudapi.net/?comp=list&include=metadata failed, reason: unable to get local issuer certificate",
  "stack": "FetchError: request to https://xxxx.blob.core.usgovcloudapi.net/?comp=list&include=metadata failed, reason: unable to get local issuer certificate\n    at ClientRequest.<anonymous> (C:\\Users\\xxxx\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1491:11)\n    at ClientRequest.emit (node:events:526:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:526:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY",
  "code": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"
}

### Steps to Reproduce

1. Launch Azure Storage Explorer
2. Connect to Azure Storage via Storage account or Service
3. Expand Storage Account that just connected
4. Expand Blob Containers

### Actual Experience

I got the following error when I tried to expand Blob Containers or File Shares folders

![image](https://user-images.githubusercontent.com/99277227/187696943-f75a693d-cf82-439b-b5ac-6366d3c0b393.png)

**Comment by MRayermannMSFT** [comment]
@avn2006 can you give using system proxy setting a try? You can read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by MRayermannMSFT** [comment]
@avn2006 are you able to browse those file shares/the contents of those file shares of that storage account via the Azure Portal?

**Comment by DTronD** [comment]
FWIW, I had the same problem then realized (thanks to @MRayermannMSFT 's suggestion) that I was not VPN'd to our Azure VLAN.  Once I connected with Azure VPN Client AND re-launched ASE, I could see the list of our Azure Fileshares and access them.

**Comment by MRayermannMSFT** [comment]
@DTronD glad you were able to figure it out. As for @avn2006 since you haven't replied in a while we're going to close this due to lack of response. If you are still having problems and want help, we recommend opening an Azure support ticket via the portal. You can also open a new issue here.
