### ISSUE TITLE
Error on opening Storage Explorer

### ISSUE THREAD

**Issue by NiyiAdekunle** [microsoft/AzureStorageExplorer#6068]
Unable to retrieve child resources.

Details:
Invalid initialization vector

![image](https://user-images.githubusercontent.com/88796954/187720948-c012eded-3981-4d23-850e-67ba9c31f79d.png)

**Comment by JasonYeMSFT** [comment]
@NiyiAdekunle This is an error from NodeJS crypto module. The encryption password may be corrupted. If you go to Windows credential manager, try to delete the entry named "Microsoft_StorageExplorer/app" and restart Storage Explorer. This will let Storage Explorer re-generate a new password for future crypto operations. However, this will break your existing local attachments, quick access and stored tab session (if any). You will need to re-add your local attachments and quick access nodes after resetting the password.

**Comment by NiyiAdekunle** [comment]
Thank you @JasonYeMSFT. Issue resolved.

**Comment by davidwanner-8451** [comment]
Worked for me, thank you @JasonYeMSFT
