### ISSUE TITLE
{   "message": "\"UnexpectedCancel\"" }

### ISSUE THREAD

**Issue by arneshchopra** [microsoft/AzureStorageExplorer#6071]
Trying to upload a file but keep getting the same error. It's a critical issue as an important daily use case depends on it.  I hope for a good and early reply. 

Thank you

**Comment by MRayermannMSFT** [comment]
@arneshchopra can you please share the AzCopy log file with us from the upload that failed? If you do not know which log file it is, you can:

1. Try the upload again
2. If it fails, go to `<your home directory>/.azcopy`
3. Drag and drop the newest log file to a reply to this issue

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue we recommend opening a support ticket via the Azure Portal. Alternatively you can open a new issue here.
