### ISSUE TITLE
An info bar prompts when attaching one secondary blob container which SAS URL is created by 'User delegation key' 

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6076]
**Storage Explorer Version:** 1.26.0-dev
**Build Number:** 20220904.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.5 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Select one storage account -> Give the account with 'Storage Blob Data Contributor' rbac role.
2. Expand the storage account -> Blob Containers.
3. Create one blob container -> Right click it -> Click 'Open Secondary Location'.
4. Right click the secondary blob container -> Click 'Get Shared Access Signature...'.
5. Select 'User delegation key' -> Click 'Create'.
6. Copy the SAS URL -> Try to attach the secondary blob container via the SAS URL.
7. Check whether no info bar prompts.

## Expected Experience ##
No info bar prompts.

## Actual Experience ##
An info bar prompts indicating "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature".
![image](https://user-images.githubusercontent.com/87792676/188591610-7786ce1a-8ced-49d8-b6d9-7a3d5cfb4666.png)

## Additional Context ##

1. This issue doesn't reproduce when attaching via Azure AD.
2. This issue doesn't reproduce when attaching via Anonymously.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220914.3. Fixed, so we are going to close it.
