### ISSUE TITLE
Query Builder cut in half and can not see Table top menu

### ISSUE THREAD

**Issue by OzBob** [microsoft/AzureStorageExplorer#6077]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.25.1

### Regression From

yes, unsure which version

### Architecture

x64

### Storage Explorer Build Number

20220809.7

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Open query builder randomly open halfway and the top table menu will be obscured

### Steps to Reproduce

Open Azure Storage table
Open query builder
Filter
Close query builder
Refresh
Open query builder - an randomly it will open half way and the top menu will be obscured

### Actual Experience

as per screen shot
![image](https://user-images.githubusercontent.com/1796771/188780860-bc75d6b8-8474-4949-861e-4a518e218a1f.png)

### Expected Experience

Open query bulder screen repaints Table top menu then query builder.

**Comment by MRayermannMSFT** [comment]
@OzBob if you resize the window, or resize the tab by dragging on the divider between the right and left hand sides of the app, does the issue fix iteself?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue we recommend opening a support ticket via the Azure Portal. Alternatively you can open a new issue here.

**Comment by OzBob** [comment]
@MRayermannMSFT this is OK now in version 1.26

**Comment by craxal** [comment]
Duplicate of #5806.
