### ISSUE TITLE
Unable to retrieve child resources.

### ISSUE THREAD

**Issue by abitosh-ac** [microsoft/AzureStorageExplorer#6078]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.25.1

### Architecture

x64

### Platform

Windows

### Bug Description

**Unable to retrieve child resources.**

Details:
{
  "name": "FetchError",
  "message": "request to https://xyz.net/?comp=list&include=metadata failed, reason: self signed certificate in certificate chain",
  "stack": "FetchError: request to https://xyz.blob.core.windows.net/?comp=list&include=metadata failed, reason: self signed certificate in certificate chain\n    at ClientRequest.<anonymous> (C:\\Users\\40107911\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1491:11)\n    at ClientRequest.emit (node:events:526:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:526:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "SELF_SIGNED_CERT_IN_CHAIN",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}

### Steps to Reproduce

1. Launched the storage explorer.
2. Singed in with the credentials.
3. Run the blob container as mentioned above.
4. Error (as mentioned above)

### Actual Experience

I tried to access the blob storage for accessing the database. However, when I clicked on the blob storage, it throwed an error. So I tried accessing it through the SAS link as well, but couldn't load the database.

**Comment by MRayermannMSFT** [comment]
@abitosh-ac please try enabling system proxy: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by abitosh-ac** [comment]
Thanks it worked!
