### ISSUE TITLE
Hide the "Preview" action if no blob is selected in the blob container view

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6079]
**Storage Explorer Version**: 1.26.0-dev
**Build Number**: 20220907.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: From running test cases
**Regression From**: Previous build (20220829.1)

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Open one empty file share.
3. Right click the string 'No data available' -> Observe the context menu.
4. Check there is a 'Preview' action.

## Expected Experience ##
There is a 'Preview' action.
![image](https://user-images.githubusercontent.com/41351993/188848950-67d9a66d-6a5b-4345-9dc7-1bf2ccf3e523.png)

## Actual Experience ##
There is no 'Preview' action.
![image](https://user-images.githubusercontent.com/41351993/188848635-c84f15c4-de8a-48f2-8d61-234019d3924e.png)

## Additional Context ##
1. There is a 'Preview' action for one empty blob container.
![image](https://user-images.githubusercontent.com/41351993/188848443-8d03273d-a758-45f2-b5bd-e83aa215e426.png)

2. On the previous build 20220829.1. There is a 'Preview' action for the File Share snapshot.
![image](https://user-images.githubusercontent.com/41351993/188847927-cae1303d-8b0f-4278-b275-038856c78240.png)

**Comment by JasonYeMSFT** [comment]
This change is intentional. The preview action will only show up if the view is for blob/file, as opposed to blob container/file share.

**Comment by v-xianya** [comment]
@JasonYeMSFT Thank you for the updates!

The 'Preview' action shows up on the empty blob container's editor.
No 'Preview' action shows up on the empty file share's editor.
I guess it might be better to make the behavior consistent. 😊
![image](https://user-images.githubusercontent.com/41351993/189792887-1a709266-c4f0-41b8-a47d-1689061822e7.png)

**Comment by JasonYeMSFT** [comment]
I will make the preview action be hidden if 0 items is selected in blob container view.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220916.2. Fixed. So, we are going to close it.
![image](https://user-images.githubusercontent.com/41351993/190539056-19b38244-6472-4681-a7a7-7fa5b06141f5.png)

**Comment by v-xianya** [comment]
The 'Preview' action is added back because the toolbar item added.
![image](https://user-images.githubusercontent.com/41351993/192229944-f2c8fa86-0435-45a9-be19-434cd8e190a1.png)
