### ISSUE TITLE
It is better to make a same state for the 'Preview' action against one 0B item between blob containers and file shares

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6082]
**Storage Explorer Version**: 1.26.0-dev
**Build Number**: 20220908.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.5 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Upload one .txt file with 0B size.
3. Right click the file.
4. Observe the 'Preview' action state.
5. Open one blob container -> Upload one .txt file with 0B size.
6. Right click the file.
7. Observe the 'Preview' action state.
8. Check whether the 'Preview' action state is the same.

## Expected Experience ##
The 'Preview' action state is the same.

## Actual Experience ##
The 'Preview' action state is not same.
1. The 'Preview' action is enabled for the 0B size item in one blob container.
2. The 'Preview' action is disabled for the 0B size item in on file share.
![image](https://user-images.githubusercontent.com/41351993/189091756-af3102e4-e6dc-415e-b7bb-727ab0944375.png)
## Additional Context ##
The 'Preview' action is enabled for one ADLS Gen2 blob which size is 0B.

**Comment by JasonYeMSFT** [comment]
The Preview command should now be enabled for 0B files in file share explorer.

**Comment by v-xianya** [comment]
Verified this issue on the main build/20220914.3. Fixed. So, we are going to close it.
![image](https://user-images.githubusercontent.com/41351993/190043134-1a9263c5-4705-4ba7-b713-a01927a7886a.png)
