### ISSUE TITLE
Azure copy paste between tenants failing

### ISSUE THREAD

**Issue by naemus** [microsoft/AzureStorageExplorer#6083]
When I attempt to copy a disk from one tenant to another it fails at end of the operation.
I've tried using a fix seen in issue 2048 by replacing the diskcopy folder but no success - the versioning of the releases is likely too major to work with my current storage explorer diskcopy.

AzCopy failed to complete the transfer: %s
Disk 'vmprdrafmap003_OsDisk_1_f93f9e06aa1f4e248d976cc958c1daf6' in 'rg-edp-prod-cac-001' was likely created. You may need to delete this disk before retrying this operation.

AzCopy error message: failed to perform copy command due to error: -> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/error.go:157
HTTP request failed

Head "https://md-impexp-wxb24sgj0mcr.z42.blob.storage.azure.net/wdxsmgkgck0h/abcd?si=7c0f6c50-9436-4a07-a30e-41d5dfdfd451&sig=-REDACTED-&sr=b&sv=2018-03-28&timeout=901": dial tcp: lookup md-impexp-wxb24sgj0mcr.z42.blob.storage.azure.net: no such host

AzCopy log file can be found at undefined

Storage Explorer was unable to revoke access to a disk.
The disks involved in this operation may still be in an 'Active SAS' or 'Active Upload' state. You may need to return the disks to an 'Unattached' state before retrying this operation, or before performing new operations on the disks.
[11654885-58c1-0048-5a9e-a5c32bc88fad-scanning.log](https://github.com/microsoft/AzureStorageExplorer/files/9527238/11654885-58c1-0048-5a9e-a5c32bc88fad-scanning.log)

**Comment by MRayermannMSFT** [comment]
@naemus it looks like AzCopy was not able to reach the storage account that was behind either the source or destination disk. If this keeps happening to you, you may need to download the disk locally and then reupload it. I can't think of any reason why the underlying storage account could not be reached for a disk.

**Comment by naemus** [comment]
Pending some further testing but this might have been a DNS issue. We switched some setups around to incorporate a dns forwarder in azure.  Our internal dns fwd zones might have been causing issues with the blob.core.windows.net

**Comment by vaishnav-dahake** [comment]
Hi @MRayermannMSFT / @JasonYeMSFT / Team,

I am facing similar issue when I am trying to copy huge data files (around 428GB) from HDFS on premise server to Azure blob storage using AZ COPY command 

If I search for "**error**" in my AZ copy log file , I get the below message :- 

_**Error description Observed :**_

2022/09/26 12:52:36 ==> REQUEST/RESPONSE (Try=1/35.586µs, OpTime=15.661585687s) -- REQUEST ERROR
   ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/error.go:157
2022/09/26 13:10:31 ==> REQUEST/RESPONSE (Try=1/58.576µs, OpTime=1m19.369584054s) -- REQUEST ERROR
   ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/error.go:157
2022/09/26 14:10:26 ==> REQUEST/RESPONSE (Try=1/36.891µs, OpTime=2m10.553818784s) -- REQUEST ERROR
   ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/error.go:157
2022/09/26 15:06:06 ==> REQUEST/RESPONSE (Try=1/42.014µs, OpTime=1m19.370463098s) -- REQUEST ERROR
   ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/error.go:157
2022/09/26 15:09:22 ==> REQUEST/RESPONSE (Try=1/35.036µs, OpTime=1m19.374628401s) -- REQUEST ERROR
   ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/error.go:157
2022/09/26 15:23:33 ==> REQUEST/RESPONSE (Try=1/43.077µs, OpTime=1m19.380015024s) -- REQUEST ERROR
   ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/error.go:157
2022/09/26 15:26:57 ==> REQUEST/RESPONSE (Try=1/43.425µs, OpTime=1m19.482507789s) -- REQUEST ERROR
   ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/error.go:157

If I search for "**Failed**" in my AZ COPY log file , I get the below error message :- 
HTTP request failed

Kindly help regarding this and please let me know if more information is required from my end.
