### ISSUE TITLE
The imported entities don't display automatically when successfully canceling the import activity

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6086]
**Storage Explorer Version:** 1.26.0-dev
**Build Number:** 20220909.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.5 (Apple M1 Pro)
**Architecture:** ia32\x64
**How Found:** Ad-hoc testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create a table -> Import the below csv file.
[table.csv](https://github.com/microsoft/AzureStorageExplorer/files/9533084/table.csv)
3. Make sure the import action is in progress.
4. Click 'Cancel' next to the activity log.
5. Check whether the imported entities display automatically.

## Expected Experience ##
The imported entities display automatically.

## Actual Experience ##
The imported entities don't display automatically.

## Additional Context ##
Related bug: [5620](https://github.com/microsoft/AzureStorageExplorer/issues/5620)

**Comment by craxal** [comment]
The import job uses a more unsynchronized, error prone way of handling cancelations. I need to add some code where the "importing" state checks for the cancelation before each batch and transitions to the "canceled" state.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220920.2. Fixed.
