### ISSUE TITLE
{   "message": "\"UnexpectedQuit\"" }

### ISSUE THREAD

**Issue by yanglinqiang** [microsoft/AzureStorageExplorer#6087]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.25.1

### Architecture

x64

### Storage Explorer Build Number

20220809.7

### Platform

macOS

### OS Version

macOS Big Sur(11.6.1)

### Bug Description

The same account use windows is ok. file list , download file, delete file. but use mac  only can see file list.cat not download file ,delete file. 
{
  "message": "\"UnexpectedQuit\""
}

### Steps to Reproduce

1. select a file
2. download zhe file

### Actual Experience

windows is ok
mac can not download file.

![image](https://user-images.githubusercontent.com/7391720/189795723-9ea4bc8c-e988-4b02-b3a5-301da42189cb.png)

**Comment by JasonYeMSFT** [comment]
@yanglinqiang Could you get the AzCopy log file for such a failed transfer and send it to us? The default log file directory is ~/.azcopy and each job is named by its job id. You can reproduce the error one more time and get the latest directory for its log files.

**Comment by s0yabean** [comment]
Hi, I have a similar issue even though I upgraded to 1.26.0. On Mac Catalina 10.15.7.

AzCopy Command:

export AZCOPY_CRED_TYPE=Anonymous;
export AZCOPY_CONCURRENCY_VALUE=AUTO;
./azcopy copy "<LINK>" "/var/folders/j_/71n3n97d5hz528y6_pf3z9fw58w6mf/T/16656314018240/info.html" --overwrite=prompt --check-md5 FailIfDifferent --from-to=BlobLocal --blob-type BlockBlob --recursive --log-level=INFO;
unset AZCOPY_CRED_TYPE;
unset AZCOPY_CONCURRENCY_VALUE;

Oddly enough inside the ~/.azcopy I don't see the logs for the failed jobs I only see so for the successful ones.

**Comment by JasonYeMSFT** [comment]
@s0yabean Maybe AzCopy crashed too early and thus haven't written any logs. If you can get an AzCopy executable, could you run the same command from terminal and share the error printed there? You can get AzCopy executables [here](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10)

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue, we recommend opening an Azure support ticket via the portal. Alternatively you can open a new issue here.
