### ISSUE TITLE
It would be better to update the title to 'Duplicate Entity' after clicking 'Duplicate...' for one entity

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6088]
**Storage Explorer Version:** 1.26.0-dev
**Build Number:** 20220913.2
**Branch:** feature/table-api-version
**Platform/OS:** Windows 10
**Architecture:** ia32\x64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create a table -> Add one entity.
3. Right click the entity -> Click 'Duplicate...' -> A dialog pops up.
4. Check whether the title of the dialog is 'Duplicate Entity'.

## Expected Experience ##
The title of the dialog is 'Duplicate Entity'.

## Actual Experience ##
The title of the dialog is 'Edit Entity'.
![image](https://user-images.githubusercontent.com/87792676/189870232-3f2036dc-b55b-408e-8478-2dd65e53091b.png)

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220916.2. Reproduce. Will verify it on a newer build.

**Comment by craxal** [comment]
@v-xianya Not all changes are in. You don't need to check Verifying bugs until they're closed.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220920.2. Fixed.
![image](https://user-images.githubusercontent.com/41351993/191150408-1da8435d-f1a1-424c-8733-c80312849e36.png)
