### ISSUE TITLE
Reopening the 'CORS Setting' dialog don't show the added rules after setting access policies for one file share

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#609]
**Storage Explorer Version**: 1.5.0 
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture**: ia32/x64
**Build Number**:20180828.2
**Commit**: ca058b20
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Drill down from one storage account -> File Shares.
2. Create a file share then add one access policy for it.
3. Right click the group node 'File Shares' -> Select 'Configure CORS Settings...' -> Add one rule to it -> Save.
4. Reopen the 'CORS Settings' dialog then check whether the added rule displays well or not.

#### Expected Experience: ####
The added rule displays well on 'CORS Settings' dialog.

#### Actual Experience: ####
The added rule doesn't display on 'CORS Settings' dialog.

#### More info: ####
1. The added rules display well after reopening the 'CORS Settings' dialog at the second time.
2. This issue doesn't reproduce for Blob Containers/Queues/Tables.

**Comment by craxal** [comment]
How long do you wait before reopening the dialog? It's possible the operation is just taking a bit longer for files.

**Comment by v-xuanzh** [comment]
I reopened the dialog immediately after setting access policies for file shares.
Now, The added rules displays well after waiting about two minutes. 
Looks like the operation was taking a bit longer. :)
