### ISSUE TITLE
It is better to add the service type in the 'pin/unpin to Quick Access' activity log

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6094]
**Storage Explorer Version**: 1.26.0-dev
**Build Number**: 20220915.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.5.1 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table named 'test1' -> Pin the table to Quick Access.
3. Observe the activity log.
4. Check whether the service type 'table' displays in the activity log.

## Expected Experience ##
It is better to add the service type 'table' display in the activity log. 
Like: **Pinned table 'test' to Quick Access.**
## Actual Experience ##
No service type 'table' displays in the activity log.
![image](https://user-images.githubusercontent.com/41351993/190342940-0608428a-3fa5-4472-b1e7-cf40e719cd47.png)

**Comment by craxal** [comment]
Getting the service type would be a lot more work. Considering the activity is directly in response to user input, it's very unlikely leaving the service type out will cause much confusion.
