### ISSUE TITLE
The QA table doesn't auto display as broken when deleting the original [The proxy setting is 'Use system proxy (preview)']

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6095]
**Storage Explorer Version**: 1.26.0-dev
**Build Number**: 20220915.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.5.1 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: Ad-hoc testing
**Regression From**: Previous release (1.25.1)

## Steps to Reproduce ##
1. Open 'Proxy Settings' dialog -> Set the Source to 'Use system proxy (preview)'.
2. Expand one storage account -> Tables.
3. Create a table -> Pin the table to Quick Access.
4. Delete the table.
5. Check whether the QA table auto displays as broken.

## Expected Experience ##
The QA table auto displays as broken.
## Actual Experience ##
The QA table doesn't auto display as broken.

## Additional Context ##
1. This issue doesn't reproduce for one queue.
2. This issue doesn't reproduce for one emulator table.

**Comment by craxal** [comment]
@v-xianya Can you use Fiddler to confirm that both delete and list entities requests are sent and responses received in the appropriate order? It's possible the delete operation and the list entities operation used to test whether the table is deleted are executed so closely together that the service hasn't had time to process the delete table operation when the list entities request comes in.

**Comment by craxal** [comment]
@v-xianya I observe that neither blob containers nor file shares auto-update to a broken link icon after deleting the originals, with or without a proxy. So, we are inconsistent across different service types.

**Comment by v-xianya** [comment]
@craxal For blob containers and file shares, there are known issues and were marked won't fix.

2[671](https://github.com/microsoft/AzureStorageExplorer/issues/2671), [1389](https://github.com/microsoft/AzureStorageExplorer/issues/1389).

**Comment by craxal** [comment]
I'll mark this as won't fix, since we aren't fixing this for other services.
