### ISSUE TITLE
Storage

### ISSUE THREAD

**Issue by kpattersonjll** [microsoft/AzureStorageExplorer#6096]
{
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"self signed certificate in certificate chain\\\",\\n  \\\"stack\\\": \\\"Error: self signed certificate in certificate chain\\\\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)\\\\n    at TLSSocket.emit (node:events:390:28)\\\\n    at TLSSocket._finishInit (node:_tls_wrap:944:8)\\\\n    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)\\\",\\n  \\\"code\\\": \\\"SELF_SIGNED_CERT_IN_CHAIN\\\"\\n}\""
}

**Comment by JasonYeMSFT** [comment]
@kpattersonjll Could you try the steps in our [troubleshooting guide](https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2204#ssl-certificate-issues) to see if it helps resolve your issue?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still facing this issue, we recommend opening a support ticket via the Azure portal. Alternatively you can open a new issue here.
