### ISSUE TITLE
AzCopy consuming too much memory while downloading

### ISSUE THREAD

**Issue by sausag3** [microsoft/AzureStorageExplorer#6097]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.25.1

### Architecture

x64

### Storage Explorer Build Number

1.25.1

### Platform

Windows

### OS Version

Windows 11

### Bug Description

I'm downloading a 23GB file from Azure blob storage to a local drive and I see AzCopy currently using 5.3GB of memory, which seems a crazy amount.

### Steps to Reproduce

1. Launch Storage Explorer
2. Browsed to the Azure Blob Storage container I wanted
3. Selected Download File and picked a folder.
4. When it was 60% downloaded I happened to glance at Task Manager to check if it was still downloading and noticed the high memory consumption.

### Actual Experience

High memory usage.

### Expected Experience

Low memory usage.

**Comment by JasonYeMSFT** [comment]
We had a chat with the AzCopy team. For downloading a 23 GB blob, using 5.3 GB of memory is expected since the buffer size has a positive effect on speeding up the download. If you need to limit that to reserve memory for other tasks, in Storage Explorer you can go to Settings -> Transfers -> AzCopy -> Buffer Size to set a limit.
