### ISSUE TITLE
How can I change the path to which az storage explorer download files?

### ISSUE THREAD

**Issue by Victor753** [microsoft/AzureStorageExplorer#6099]
Hi,

When I double click on a file on az storage explorer, it utilizes azcopy to transfer the file before opening it to my local temp folder: "C:\Users\user\AppData\Local\Temp"

How can I change this to choose a specific location/path to download files before opening them?  I don't see that possible in the settings Also I know that az storage explorer is the GUI for the azcopy but I couldn't figure out how to change this behavior

We don't need to save important files to the temp appdata path but to a path where we can specify and delete afterwards Otherwise people will forget to clean it up

Thanks for helping us

**Comment by JasonYeMSFT** [comment]
@Victor753 You should use the "Download" action which will let you specify the download location via a system dialog.

**Comment by MRayermannMSFT** [comment]
@Victor753 for some additional context, we refer to "double clicking a file" as opening it. We don't pop up a directory picker dialog as the open is supposed to be a way to quickly download a file and then open it in its default program. We put it in a temp folder so your OS will clean it up later.

If you'd like to download somewhere specific, then as JasonYeMSFT said, you should use "Download" from the toolbar or context menu.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you have further questions regarding our responses please open a new issue.

**Comment by pknameer** [comment]
If installed via snap, 'doube-click-to-open' would download it to a 'private' folder, and would not open.

Downloading is working fine btw.
