### ISSUE TITLE
All dialog's title doesn't show from the top-left

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#610]
**Storage Explorer Version**: 1.5.0 
**Platform/OS Version**: MacOS High Sierra
**Architecture**: ia32/x64
**Build Number**:20180828.2
**Commit**: ca058b20
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Expand one account. 
2. Open on blob container -> Attempt to delete a blob -> Check the 'Delete Blobs' title.

#### Expected Experience: ####
The title starts from top-left on the dialog.
![left](https://user-images.githubusercontent.com/34729022/44777181-6b9a7300-ab69-11e8-9fe8-bf034b81b4cb.png)

#### Actual Experience: ####
The title displays on the top-center of the dialog.
![middle](https://user-images.githubusercontent.com/34729022/44776927-c7183100-ab68-11e8-9cbd-e0a85381e86f.png)

**Comment by craxal** [comment]
That's expected behavior for Macs. Every Mac window does that.
