### ISSUE TITLE
Logout from Account?

### ISSUE THREAD

**Issue by DavidLangworthy** [microsoft/AzureStorageExplorer#6100]
How can I logout from an account?  I need to do this so I can log back in and pick up new JIT credentials.

**Comment by JasonYeMSFT** [comment]
You can use the Remove button next to your account. ![Screen Shot 2022-09-19 at 10 23 22 AM](https://user-images.githubusercontent.com/39359541/191076830-12233905-2c81-4f75-80db-b255f2d1e18a.png)

**Comment by DavidLangworthy** [comment]
Thank you @JasonYeMSFT .  However I do not want to remove the account and all the favorites I've set.  I just want to logout/login and pick up a new credential.

**Comment by MRayermannMSFT** [comment]
@DavidLangworthy logout and remove are the same thing in this context. If you find "Remove" is not working well enough for you, you can also try going to Help -> Reset -> Only have "Authentication" checked, press the "Reset" button, and then restart Storage Explorer.

**Comment by DavidLangworthy** [comment]
Thank you.  I'll use reset.
