### ISSUE TITLE
The string 'Sign in with Azure…' on the 'ACCOUNT MANAGEMENT' panel is not localized

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6102]
**Storage Explorer Version**: 1.26.0-dev
**Build Number**: 20220919.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.5.1 (Apple M1 Pro)
**Reproduce Languages**: All languages
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select 'français' -> Restart Storage Explorer.
3. Open the ACCOUNT MANAGEMENT panel.
4. Check whether the string 'Sign in with Azure...' is localized or not.

## Expected Experience ##
The string 'Sign in with Azure...' is localized.

## Actual Experience ##
The string 'Sign in with Azure...' is not localized.
![image](https://user-images.githubusercontent.com/41351993/190974169-0fd73fbc-f2ab-4650-838f-52bfcbf5ab2d.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20221203.4. Fixed. So, we are going to close it.
![image](https://user-images.githubusercontent.com/87792676/205585477-ed250ae7-916e-44e9-bea6-c7e5f8769090.png)
