### ISSUE TITLE
The 'Services -> Text preview extensions' part is not localized on 'Settings' part

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6103]
**Storage Explorer Version:** 1.26.0-dev
**Build Number:** 20220919.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.5.1 (Apple M1 Pro)
**Reproduce Languages:** All languages
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select 'Français' -> Restart Storage Explorer.
3. Open 'Settings' -> Services' -> Observe the 'Text preview extensions' part.
4. Check whether this part is localized.

## Expected Experience ##
This part is localized.

## Actual Experience ##
This part is not localized.
![image](https://user-images.githubusercontent.com/87792676/190975427-4d03fb25-9ac5-4c7b-8361-850fc87069ed.png)

**Comment by JasonYeMSFT** [comment]
Most of these strings are translated now.

**Comment by v-xianya** [comment]
@JasonYeMSFT 

Verified this issue on the build main/20220923.3. 
This issue still reproduces on languages 'Hungarian, Polish, Portuguese (Portugal)'. So, we are going to reopen it.

 
The screenshot on 'Hungarian'
![image](https://user-images.githubusercontent.com/41351993/191880802-5c0a7213-d1e6-4361-a782-5a3ae1cb0f37.png)

**Comment by JasonYeMSFT** [comment]
We have created the release branch so these strings won't be ready for 1.26.0.

**Comment by JasonYeMSFT** [comment]
The strings are ready for 1.27.0.
