### ISSUE TITLE
There is a scrollbar on the prompt dialog when clicking 'View Error...' for one broken 'Local-1 (Key)' node

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6105]
**Storage Explorer Version**: 1.26.0-dev
**Build Number**: 20220919.1
**Branch**: main
**Platform/OS**: Windows 10
**Reproduce Languages**: French/Spanish/Italian/Portuguese (Brazil)/Portuguese (Portugal)/Russian
**Architecture**: ia32
**Azurite Version**: 3.19.0
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Install and run Azurite 3.19.0.
2. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
3. Select 'français' -> Restart Storage Explorer.
4. Open the connect dialog -> Click 'Local storage emulator' -> Click 'Next' -> Click 'Connect'.
5. Add the 'local-1 (Key)' to Quick Access -> Detach the attachment 'local-1 (Key)'.
6. The QA 'local-1 (Key)' displays as broken -> Right click it -> Click 'View Error...'.
7. Check there is no scrollbar on the prompt dialog.

## Expected Experience ##
No scrollbar on the prompt dialog.
Here is the screenshot on ENU:
![image](https://user-images.githubusercontent.com/41351993/190986697-a47b3ff1-b607-48b1-b28d-72d5dca913a4.png)

## Actual Experience ##
There is a scrollbar on the prompt dialog.
![image](https://user-images.githubusercontent.com/41351993/190985745-a314cf79-0d0a-4768-927b-369e41838401.png)

## Additional Context ##
Verified this issue on all languages.

**Comment by JasonYeMSFT** [comment]
While working on this, please think of whether we can make the dialogs automatically adjust their sizes so we don't need to manually update the size each time the string differs.

**Comment by craxal** [comment]
Since this issue is technically resolved, I'm going to close this. See #1420 for tracking automatic dialog size adjustments.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20221116.8. Fixed.
