### ISSUE TITLE
The QA table displays as broken if the original is an Azure AD attached table without assigning rbac role to its associated azure account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6106]
**Storage Explorer Version**: 1.26.0-dev
**Build Number**: 20220920.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.5.1 (Apple M1 Pro)
**Reproduce Languages**: All languages
**Architecture**: ia32/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Copy the URL of the table.
3. Open the connect dialog -> Click 'Table -> Sign in using Azure Active Directory (Azure AD)' -> Click 'Next'.
4. Select one Azure account (Not assign rbac role)-> Click 'Next'.
5. Paste the URL -> Connect the table.
6. The attached table auto opens and there is an error info bar indicating 'AuthorizationPermissionMismatch'.
7. Right click the attached table -> Click 'Pin to Quick Access'.
8. Check the QA table shows well.

## Expected Experience ##
The QA table shows well.

## Actual Experience ##
The QA table shows as broken.
Here is the error details:
![image](https://user-images.githubusercontent.com/41351993/191209133-a71347f2-50ef-43ff-80bc-83e5adc80937.png)

## Additional Context ##
1. This issue doesn't reproduce for blob containers/queues.
2. The Azure account associated with the azure ad attached hasn't been assigned the rbac role.

**Comment by craxal** [comment]
@v-xianya I feel like the proper solution is to explain that the table does not exist or that you don't have access to it. Why do say that you expect the table node to show as normal when you haven't assigned an RBAC role granting access?

**Comment by v-xianya** [comment]
@craxal 
The QA node displays normal when running the repro steps for blob Containers/queues

**Comment by craxal** [comment]
Consistency in this case would be difficult to achieve as there isn't a standard way to check whether a resource exists. I will, however, change the text to be more accurate.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20220926.1. The error message has been updated.
![image](https://user-images.githubusercontent.com/41351993/192202377-37065298-4001-4701-9003-e82f467061f7.png)

**Comment by craxal** [comment]
@v-xianya Please note that this is a string change, and so translations may take a while to make it into the build.

**Comment by v-xianya** [comment]
@craxal ok, thanks for the notification.
