### ISSUE TITLE
Support to collapse/expand account subscriptions in Account Management Panel

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#611]
**Storage Explorer Version**: 1.5.0 
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture**: ia32/x64
**Build Number**:20180828.2
**Commit**: ca058b20
**Regression From**: Not a regression

#### Background: ####
There added several accounts which included multiple subscriptions, we think it is convenient to apply required subscriptions of one specific account if we can collapse the unused account subscriptions.
![collapse](https://user-images.githubusercontent.com/34729022/44774141-dcd62800-ab61-11e8-975f-f89a0d939843.png)

**Comment by JasonYeMSFT** [comment]
Will be tracked together with #1326
