### ISSUE TITLE
Remove the 'Delete' action from the context menu of one QA file share

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6110]
**Storage Explorer Version**: 1.26.0-dev
**Build Number**: 20220922.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.5.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Pin the file share to Quick Access.
3. Right click the QA file share.
4. Check no 'Delete' action displays.

## Expected Experience ##
No 'Delete' action displays.

## Actual Experience ##
The 'Delete' action displays.
![image](https://user-images.githubusercontent.com/41351993/191686414-9971f4c0-7052-476c-8174-e8ae0b3b0478.png)

## Additional Context ##
Related bug: [3557
](https://github.com/microsoft/AzureStorageExplorer/issues/3557).

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220927.1. Fixed.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220927.1. Fixed.
![image](https://user-images.githubusercontent.com/87792676/192415074-1b739aff-4e8a-4377-af3c-5c4dc1f1c245.png)
