### ISSUE TITLE
Automated updates of Azure Storage Explorer

### ISSUE THREAD

**Issue by jbauerrfid** [microsoft/AzureStorageExplorer#6111]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I need to update Azure Storage Explorer manually

### Desired Solution

Automated updates through Windows Update or package manager on Linux

**Comment by MRayermannMSFT** [comment]
For Linux, we already provide a snap package, and snaps auto update by default: https://snapcraft.io/docs/keeping-snaps-up-to-date

For Windows, we already have an issue tracking such a feature request: https://github.com/microsoft/AzureStorageExplorer/issues/2875
