### ISSUE TITLE
Refresh resets Column Options

### ISSUE THREAD

**Issue by Pelago** [microsoft/AzureStorageExplorer#6112]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.25.1

### Regression From

Do not know but if feels as if it has been working before

### Architecture

x64

### Storage Explorer Build Number

20220809.7

### Platform

Windows

### OS Version

windows 11 and windows 10

### Bug Description

If I open a Azure Table storage table and change the Column Options to just show for me relevant column and i need to refresh the table during development of a service the Column Options will be reset to showing all columns again. It is time consuming having to reset the Column Options i would like o have after every refresh.

### Steps to Reproduce

1. Launch Storage explorer
2. Open a Table from table Storage
3. Open Column Options and Clear all  Select a few columns to be shown and press okay
4. Press the refresh option in the menu bar on top.

All columns is back   :(

### Actual Experience

All columns is back   :(

### Expected Experience

Keeping the Colum Option at least in the current session would be preferred

**Comment by craxal** [comment]
@Pelago This is a known issue and has been fixed. It will be available for 1.26.0.
