### ISSUE TITLE
No Subscriptions found

### ISSUE THREAD

**Issue by DR93EHV** [microsoft/AzureStorageExplorer#6113]
Hi,

I just installed Storage Explorer and wanted to connect to my subscription through my Microsofot Azure account.
I connect succesfully but now it says that there are "No subscriptions found" while I do have 1 subscription.

Connecting directly to one of my storage accounts is on the other hand possible..
![Capture](https://user-images.githubusercontent.com/114287239/192091873-42616704-57a6-4896-8468-349cd049d6a8.PNG)

**Comment by MRayermannMSFT** [comment]
@DR93EHV can you please try checking the checkbox for the "Default Directory" tenant?

**Comment by DR93EHV** [comment]
> @DR93EHV can you please try checking the checkbox for the "Default Directory" tenant?

Thanks @MRayermannMSFT ! Works for me.

**Comment by kalatchev** [comment]
@MRayermannMSFT 
You suggestion did the job, but I wonder why I have wrong (expired) subscription even visible?

**Comment by ericle** [comment]
I'm also getting "No subscriptions found".
![screenshot](https://github.com/microsoft/AzureStorageExplorer/assets/2067976/bdd5616b-edbf-4960-966e-5d73ea7f590d)

I'm interested in the hotmail account, not the Buzzhorn one.

There's no "Default directory" checkbox.
