### ISSUE TITLE
The authentication library used by Storage Explorer has failed to start properly.

### ISSUE THREAD

**Issue by mohammad-anbari-maersk** [microsoft/AzureStorageExplorer#6114]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

v1.25.1

### Architecture

x64

### Platform

macOS

### OS Version

12.6

### Bug Description

I am using the mc book M1 pro
when I am opening the azure storage explore the error dialog pop up with the following error message:

"The authentication library used by Storage Explorer has failed to start properly. Please refer to the troubleshooting guide for help. Verbose authentication logging has been enabled.

Error:Hub Controller process exited prematurely with signal 'SIGABRT'."

### Steps to Reproduce

1. Launch the azure storage explorer on Mac M1 pro 

### Actual Experience

When I am opening the azure storage explore the error dialog pop up with the following error message:

"The authentication library used by Storage Explorer has failed to start properly. Please refer to the troubleshooting guide for help. Verbose authentication logging has been enabled.

Error:Hub Controller process exited prematurely with signal 'SIGABRT'."

**Comment by MRayermannMSFT** [comment]
@mohammad-anbari-maersk can you please reproduce the issue and then provide us with the authentication logs? Please see the troubleshooting guide for more info: https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2204#authentication-logs

**Comment by mohammad-anbari-maersk** [comment]
I have reproduced the issue and this the logs:
[logs.zip](https://github.com/microsoft/AzureStorageExplorer/files/9648526/logs.zip)

**Comment by mohammad-anbari-maersk** [comment]
Hi @MRayermannMSFT 
Is there any update ?

**Comment by mchalecki** [comment]
I also have this problem. Is there any follow-up?

**Comment by mohammad-anbari-maersk** [comment]
Hi @MRayermannMSFT 

It's worked for me after running those chmod commands,
Thanks a lot for your help and time.

**Comment by MRayermannMSFT** [comment]
Glad to worked out. I will close this issue as mitigated. If anyone else has this issue and the existing info does not resolve it for you, then please open a new issue. Thanks.
