### ISSUE TITLE
An extra string 'Retrieving configuration...' displays in the 'Manage Custom Environments' dialog on Ubuntu 22.04

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6115]
**Storage Explorer Version:** 1.26.0-dev
**Build Number:** 20220926.1
**Branch:** main
**Platform/OS:** Linux Ubuntu 22.04
**Architecture:** x64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Open the connect dialog.
2. Click 'Subscription -> Custom Environment -> Management custom environments...'.
3. Check no extra string 'Retrieving configuration...' displays.

## Expected Experience ##
No extra string 'Retrieving configuration...' displays.

## Actual Experience ##
An extra string 'Retrieving configuration...' displays.
![image](https://user-images.githubusercontent.com/87792676/192234648-28241c82-e5ba-40ff-a1de-ffc66dfcea84.png)

## Additional Context ##

1. This issue also reproduces in 'Add Custom Environment' dialog.
2. The string "Retrieving configuration..." flashes a bit on Ubuntu 20.04.
3. Here is the record on Ubuntu 20.04:
![20](https://user-images.githubusercontent.com/87792676/192238177-11bc2d19-d4d7-4bad-a9d4-fe2cd06aafb8.gif)

**Comment by craxal** [comment]
@v-kellyluo This is string is by design, because it takes some time to retrieve configurations. I'm assuming the message disappears after a little while?

**Comment by v-kellyluo** [comment]
@craxal Yes, it will disappear after a while.

1. On Ubuntu 20.04, the string flashes a bit.
2. On Ubuntu 22.04, it will disappear after a while, sometimes it takes more than 1 minute, sometimes it will take about ten seconds. It would be better to reduce the reaction time.

**Comment by craxal** [comment]
@v-kellyluo The time it takes to retrieve configurations can vary, and we can't really influence that. That's why we have the message there, so users know that the app is working.
