### ISSUE TITLE
Java Script error at each quit from Storage Explorer - Windows

### ISSUE THREAD

**Issue by gkep** [microsoft/AzureStorageExplorer#6116]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.25.0

### Architecture

x64

### Platform

Windows

### OS Version

10

### Bug Description

![image](https://user-images.githubusercontent.com/36948652/192241494-c357d1b9-8805-4c15-bf50-a9ebd40666bc.png)

This error is given each time I close the SE.

### Steps to Reproduce

1. Launch
2. Open some blob container
3. Quit

### Actual Experience

Error dialog from java.

**Comment by MRayermannMSFT** [comment]
Hi @gkep this is a known issue for which there is nothing to worry about. If you'd like to resolve it, please update Storage Explorer. You can do this by downloading the latest from https://storageexplorer.com, or if you wait long enough with the app open you should be presented with a message at the top asking you to update.

**Comment by MRayermannMSFT** [comment]
Merged a change to hide this error.
