### ISSUE TITLE
There is a successful activity log when cloning one ADLS Gen2 folder using an existing empty folder's name

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6117]
**Storage Explorer Version**: 1.26.0-dev
**Build Number**: 20220926.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.5.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Create two empty folders 'f1' & 'f2'.
3. Right click 'f1' -> Click 'Clone...'.
4. Type 'f2' as the new name.
5. Check whether there is a failed activity log.

## Expected Experience ##
There is a failed activity log indicating 'An object with the new name already exists'.

## Actual Experience ##
There is a successful activity log.
![image](https://user-images.githubusercontent.com/41351993/192245873-01b16733-c19b-41c3-9484-e3f95ab6fe8e.png)
## Additional Context ##
1. This issue doesn't reproduce for folders under file shares.
2. Clone empty folder using an existing non-empty folder's name, there is a failed activity log indicating 'An object with the new name already exists.' 
Clone non-empty folder using an empty folder's name, there is a successful activity log. the item under the non-empty folder will be pasted to the empty folder. 
![image](https://user-images.githubusercontent.com/41351993/192247952-2e6d3a31-b9bc-4ed6-a516-383e2e6e7e8a.png)

**Comment by JasonYeMSFT** [comment]
Based on our current implementation this is by design. Empty directories will appear to be non-existent during our existence check.
