### ISSUE TITLE
AZ COPY ISSUE : HTTPS Request Failed

### ISSUE THREAD

**Issue by vaishnav-dahake** [microsoft/AzureStorageExplorer#6118]
Hi @MRayermannMSFT / @JasonYeMSFT / Team,

I am facing similar issue when I am trying to copy huge data files (around 428GB) from HDFS on premise server to Azure blob storage using AZ COPY command 

If I search for "**error**" in my AZ copy log file , I get the below message :- 

_**Error description Observed :**_

2022/09/26 12:52:36 ==> REQUEST/RESPONSE (Try=1/35.586µs, OpTime=15.661585687s) -- REQUEST ERROR
   ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/error.go:157
2022/09/26 13:10:31 ==> REQUEST/RESPONSE (Try=1/58.576µs, OpTime=1m19.369584054s) -- REQUEST ERROR
   ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/error.go:157
2022/09/26 14:10:26 ==> REQUEST/RESPONSE (Try=1/36.891µs, OpTime=2m10.553818784s) -- REQUEST ERROR
   ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/error.go:157
2022/09/26 15:06:06 ==> REQUEST/RESPONSE (Try=1/42.014µs, OpTime=1m19.370463098s) -- REQUEST ERROR
   ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/error.go:157
2022/09/26 15:09:22 ==> REQUEST/RESPONSE (Try=1/35.036µs, OpTime=1m19.374628401s) -- REQUEST ERROR
   ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/error.go:157
2022/09/26 15:23:33 ==> REQUEST/RESPONSE (Try=1/43.077µs, OpTime=1m19.380015024s) -- REQUEST ERROR
   ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/error.go:157
2022/09/26 15:26:57 ==> REQUEST/RESPONSE (Try=1/43.425µs, OpTime=1m19.482507789s) -- REQUEST ERROR
   ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/error.go:157

If I search for "**Failed**" in my AZ COPY log file , I get the below error message :- 
HTTP request failed

Kindly help regarding this and please let me know if more information is required from my end.

_Originally posted by @vaishnav-dahake in https://github.com/microsoft/AzureStorageExplorer/issues/6083#issuecomment-1258248565_

**Comment by MRayermannMSFT** [comment]
@vaishnav-dahake can you share the log file with us?

**Comment by vaishnav-dahake** [comment]
Hi @MRayermannMSFT 
[Uploading 77657bed-2e86-3d40-5348-06881fd6d1a1.zip…]()

Please find the attached log file for your reference :- 

NOTE : I have compressed the original log file as it was 30 MB size and GitHub was not allowing me to upload.

**Comment by vaishnav-dahake** [comment]
Hi @MRayermannMSFT 


Please find the attached log file for your reference :-
[77657bed-2e86-3d40-5348-06881fd6d1a1.zip](https://github.com/microsoft/AzureStorageExplorer/files/9648842/77657bed-2e86-3d40-5348-06881fd6d1a1.zip)


NOTE : I have compressed the original log file as it was 30 MB size and GitHub was not allowing me to upload.

**Comment by JasonYeMSFT** [comment]
The log file says "use of closed network connection" in the logged error messages. It might be due to some network timing issue. At the end of the log file it says the upload has completed successfully. Are you seeing any error with the transfer in Storage Explorer?

**Comment by vaishnav-dahake** [comment]
hi @JasonYeMSFT 
The upload was completed successfully to ADLS.
But in my Python code its a step , and my code is built in such a way that next step starts based on previous step success
I check this via return code from azcopy command execution , normally when (return code == 0) , it means azcopy command is executed successfully otherwise it did not.

Refer below code for example :- 

```
import subprocess

 copy_to_azure = ("azcopy cp "+local_edge_path+adls_dir_name+"/"+" https://"+ storage_account +".blob.core.windows.net/"+ adls_dest_path + SAS_token_1_INT +" --recursive=true")
print(copy_to_azure)
copy_to_azure_proc = subprocess.Popen(copy_to_azure.split(" "),stdin=subprocess.PIPE,stdout=subprocess.PIPE,stderr=subprocess.PIPE)
copy_to_azure_proc.wait()

# STEP 4 return code and error message
step_4_returncode = copy_to_azure_proc.returncode           # return code == 0 if azcopy commands executes successfully
stdout,stderr = copy_to_azure_proc.communicate()
step_4_errormessage = stderr
```
Questions : - 

1. Now my concern is in cases of "network connection issues" will this **return code** from azcopy be "0" ?
2. For huge data (200GB +) transfer from ON PREM to ADLS , I see that even after copying all files , azcopy command gets stuck in linux, and my succeeding program as a result doesn't start ? Any workaround for this ?

**Comment by JasonYeMSFT** [comment]
@vaishnav-dahake You can better control AzCopy from code by using its JSON message channel. If you append the flag `--output-type=json`, AzCopy will emit its status message in JSON format which has a value indicating the state of the job (e.g. InProgress, EndOfJob, etc.). You can listen to the stdout of the process and parse those JSON messages to track the progress of AzCopy.

I am not sure why your code get stuck but you should be able to tell if you print the standard output and the return code. AzCopy exits when it has finished reporting the its job which may be later than when the transfer completes.

**Comment by JasonYeMSFT** [comment]
FYI, here is the official doc about AzCopy exit code https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-troubleshoot?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json#identifying-problems

**Comment by vaishnav-dahake** [comment]
hi @JasonYeMSFT 

Thanks for suggestions.

I observed that code was getting "deadlocked" as I was using "stdin =subprocess.PIPE", "stdout=subprocess.PIPE" and "stderr=subprocess.PIPE" with "Popen" and post that I was using ".wait()" command in my code

As per Python 2.7 documentation ( https://docs.python.org/2.7/library/subprocess.html ) , 
the deadlock happens in "Popen.wait()" due to below reason :

![image](https://user-images.githubusercontent.com/77481102/193164744-30ff9162-25af-417a-b9c5-4ec36dc59429.png)

Also as per the microsoft doc ( https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-optimize#turn-off-length-checking ) , AZ COPY checks the length of every file after transfer by default , this may have been an expensive time consuming operation in my case since data was of size 200 GB+, so I have "turned off length checking" by adding the flag"--check-length=false" in my code

![image](https://user-images.githubusercontent.com/77481102/193166333-292217d7-5ede-49e1-af5a-9aee1fae885b.png)

I feel this could have been the main reason in my case , as i was processing 200 GB+ data via azcopy, after slight code changes the azcopy command seems to be "working fine" in my case.


Old code : ( Getting deadlocked with 200 GB+ data )

```
import subprocess

copy_to_azure = ("azcopy cp "+local_edge_path+adls_dir_name+"/"+" https://"+ storage_account +".blob.core.windows.net/"+ adls_dest_path + SAS_token_1_INT +" --recursive=true")
print(copy_to_azure)
copy_to_azure_proc = subprocess.Popen(copy_to_azure.split(" "),stdin=subprocess.PIPE,stdout=subprocess.PIPE,stderr=subprocess.PIPE)
copy_to_azure_proc.wait()
```

New code : ( Working as expected )
```
copy_to_azure = ("azcopy cp "+local_edge_path+adls_dir_name+"/"+" https://"+ storage_account +".blob.core.windows.net/"+ 
adls_dest_path + SAS_token_1_INT +" --recursive=true --check-length=false")

# Added "--check-length=false" flag in the above azcopy statement in order to "turn off length checking" of files after transfer as per below microsoft doc guidance ( https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-optimize#turn-off-length-checking )

print(copy_to_azure)
copy_to_azure_proc = subprocess.Popen(copy_to_azure.split(" "))   # Removed stdin , stdout, stderr from Popen
copy_to_azure_proc.wait()

```

The Issue seems to be resolved now.
Thanks for your quick responses and suggestions , really appreciated the same. :)

**Comment by mawasif14** [comment]
iam facing this error while re running the azcopy copy command 
github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/error.go:157
HTTP request failed

any suggestions please

**Comment by JasonYeMSFT** [comment]
@mawasif14 If you think there is an issue in AzCopy it would be better to open an issue in the AzCopy repo https://github.com/Azure/azure-storage-azcopy. If you think it's related to Storage Explorer's AzCopy integration, please open a new issue and fill the issue template.
