### ISSUE TITLE
Wrong Version Connecting to File Share

### ISSUE THREAD

**Issue by ed-hakin** [microsoft/AzureStorageExplorer#6119]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.25.1

### Architecture

x64

### Storage Explorer Build Number

20220809.7

### Platform

Windows

### OS Version

Windows Server 2019

### Bug Description

Unable to connect to fileshare with below error:

{
  "name": "FetchError",
  "message": "request to https://edhakinfs.file.core.windows.net/?sv=2021-06-08&ss=f&srt=sco&sp=rwdlc&se=2022-09-27T03:55:49Z&st=2022-09-26T19:55:49Z&sip=10.236.130.4&spr=https&SAS Token Redacted&comp=list failed, reason: tunneling socket could not be established, cause=write EPROTO 1007995912:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:\n",
  "stack": "FetchError: request to https://edhakinfs.file.core.windows.net/?sv=2021-06-08&ss=f&srt=sco&sp=rwdlc&se=2022-09-27T03:55:49Z&st=2022-09-26T19:55:49Z&sip=10.236.130.4&spr=https&SAS Token Redacted&comp=list failed, reason: tunneling socket could not be established, cause=write EPROTO 1007995912:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:\n\n    at ClientRequest.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:114361)\n    at ClientRequest.emit (node:events:526:28)\n    at ClientRequest.onError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:599774)\n    at Object.onceWrapper (node:events:646:26)\n    at ClientRequest.emit (node:events:526:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:526:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "ECONNRESET",
  "code": "ECONNRESET"
}

### Steps to Reproduce

Connect to storage account with SAS url
Attempt to connect to fileshare
Error

### Actual Experience

Fileshare doesn't appear, produces SSL error instead

**Comment by JasonYeMSFT** [comment]
@edhakin Are you using a proxy? If so, you need to set either "use app settings" or "use system proxy" in the proxy setting.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem we recommend you open a support ticket via the Azure Portal. Alternatively you can open a new issue here.
