### ISSUE TITLE
An unexpected error occurs when launching Storage Explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#612]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**:  Linux Ubuntu 16.04
**Architecture**: x64
**Build Number**:20180828.2 
**Commit**: ca058b20
**Regression From**:Previous release 1.4.1(20180822.1)

#### Steps to Reproduce: ####
1. Launch Storage Explorer using double clicking the executable "StorageExplorer".

#### Expected Experience: ####
Storage Explorer is launched successfully.

#### Actual Experience: ####
Pop up an unexpected error as below.
![attachment](https://user-images.githubusercontent.com/41351993/44776924-c67f9a80-ab68-11e8-879a-5ea071376276.PNG)

**Comment by craxal** [comment]
Do you get any additional messages if you launch from the command line?

**Comment by v-limu** [comment]
This issue will no longer reproduces with the new launch feature. So we close it.
