### ISSUE TITLE
Can't access blob folder

### ISSUE THREAD

**Issue by chris-wise** [microsoft/AzureStorageExplorer#6121]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.25.1

### Architecture

x64

### Platform

Windows

### OS Version

Windows 11

### Bug Description

![Screenshot 2022-09-27 085348](https://user-images.githubusercontent.com/77530408/192467112-40d7fbce-9752-40e7-9317-46be2ad0bd49.png)

### Steps to Reproduce

Restarted blob but same error

### Actual Experience

Shown error above when trying to access folder

**Comment by JasonYeMSFT** [comment]
The error is an DNS error. Could check if you are using a proxy but haven't configured it in Storage Explorer? You can also try manually resolving it from the command line. If you cannot resolve it from the command line then you will need to contact your network administrator or internet service provider for help.

**Comment by rl0825** [comment]
Thank you,

Robbin Liggins
Sr. Program Project Manager
AT&T Retail Merchandising & Execution Data Team
770-371-9626 | ***@***.******@***.***>
MerchIt POG<https://attw.merchandising.cloud/> | MerchIt eStore<https://merchit.archwayconnect.com/> | Open Access<https://www.e-access.att.com/usersvcs/cspsaml/?service=jda-cloud&servicetype=prod> | User Management & Retail Help<https://attretail.service-now.com/>
AT&T Proprietary (Restricted) and Confidential | Authorized Individuals Only – Subject to NDA

**Comment by MRayermannMSFT** [comment]
@rl0825 so are you still facing this issue?

**Comment by chris-wise** [comment]
All sorted now thank you.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
