### ISSUE TITLE
Retrieval error & failure writing resources

### ISSUE THREAD

**Issue by christine1729** [microsoft/AzureStorageExplorer#6128]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.0

### Regression From

1.18.0

### Architecture

x64

### Platform

Windows

### Bug Description

1. not able to view child resources -> retrieval error
2. not able to write resources to the azure blob storage location -> failed ITP job due to failure writing

### Steps to Reproduce

1. launch app
2. expand to view child resources and got this retrieval error

### Actual Experience

1. not able to view child resources
2. not able to write resources to the azure blob storage location

**Comment by urihsam** [comment]
Similar error when I wanna copy data from blob to cosmos:
2022-10-05 20:56:25Z] [Status: Submitted]: Retriable error happened: Failed to read page blob with id XXX to blob in container bingads, offset 4030726144
[2022-10-05 20:56:25Z] [Status: Submitted]: Execution plan wasn't build and build will be delayed
[2022-10-05 20:57:28Z] [Status: Submitted]: Retriable error happened: Failed to list blobs in container bingads with prefix XXX
[2022-10-05 20:57:28Z] [Status: Submitted]: Execution plan wasn't build and build will be delayed

**Comment by MRayermannMSFT** [comment]
@urihsam can you share the exact errors you are seeing in storage explorer?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you still need help with this issue, we recommend opening a support ticket via the portal. Alternatively you can open a new issue here.
