### ISSUE TITLE
There is no icon for the action 'Search From Here' on the Actions panel

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6133]
**Storage Explorer Version**: 1.26.0-dev
**Build Number**: 20221006.3
**Branch**: feature branch
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.6 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.26.0)

## Steps to Reproduce ##
1. Launch Storage Explorer.
2. Select one node, like 'Quick Access' node -> Observe its Actions panel.
3. Check whether there is an icon for the action 'Search From Here'.

## Expected Experience ##
There is an icon for the action 'Search From Here'.
![image](https://user-images.githubusercontent.com/41351993/194696237-b11b3dd1-9db7-4b3f-80fb-e14cb378a82c.png)

## Actual Experience ##
There is no icon for the action 'Search From Here'.
![image](https://user-images.githubusercontent.com/41351993/194696227-6a09b36d-7d72-4f27-9333-9205403ea3ad.png)

**Comment by MRayermannMSFT** [comment]
Not fixed. Need to do SVG path, not raw SVG contents.

**Comment by v-xianya** [comment]
Verified this issue on the build 20221102.12. Fixed. So, we are going to close it.
