### ISSUE TITLE
The pasted file share doesn't auto display under the File Shares node

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6135]
**Storage Explorer Version:** 1.26.0-dev
**Build Number:** 20221006.3
**Branch:** feature branch
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.6 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.26.0)

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Right click the file share -> Click 'Copy File Share'.
3. Expand another storage account -> Right click File Shares node.
4. Click 'Paste File Share'.
5. Check whether the pasted file share auto displays.

## Expected Experience ##
The pasted file share auto displays.

## Actual Experience ##
The pasted file share doesn't auto display.

## Additional Context ##
1. The cloned file share also doesn't auto display. 
2. This issue doesn't reproduce for blob containers/tables.
3. The pasted file share displays after manually refreshing.

**Comment by v-xianya** [comment]
Verified this issue on the build 20221028.4. Fixed.
