### ISSUE TITLE
The resource groups cannot be searched 

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6138]
**Storage Explorer Version:** 1.26.0-dev
**Build Number:** 20221006.3
**Branch:** feature branch
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.6 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.26.0)

## Steps to Reproduce ##

1. Launch Storage Explorer.
2. Click the Filter button -> Make sure the 'Resource Groups (Disks)' option is selected.
3. Type a resource group name to the search box -> Execute 'Search'.
4. Check whether the resource group is searched.

## Expected Experience ##
The resource group is searched.
![image](https://user-images.githubusercontent.com/87792676/194701371-bb58b33b-73ff-43ed-bcce-f48f8166ec3f.png)

## Actual Experience ##
The resource group is not searched.
![image](https://user-images.githubusercontent.com/87792676/194701387-43514106-43c2-4caa-8760-a8d8db69c78a.png)

**Comment by v-xianya** [comment]
Verified this issue on the build 20221028.4. Fixed.
