### ISSUE TITLE
Download a specific folder in a Container

### ISSUE THREAD

**Issue by hholst80** [microsoft/AzureStorageExplorer#6139]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I am unable to find a specific folder and select only that

### Desired Solution

I want to be able to filter a directory sorting OR be able to download everything in the container that matches the current directory, as it is quite reasonable to change directory to the one that i want to download but then again it lacks a way to download *everything* similar to #5050 but for a subset.

### Alternatives and Workarounds

maunally scan the folders in the root and mark the one I want to download and press download. This does obviously not scale well when we have 1000s of folders in the container root.

**Comment by hholst80** [comment]
This would have been obvious if the developers of the software also where using it themselves. One of the most classical problem in software engineering. The developers are not the users of the thing they are developing. :-)

**Comment by MRayermannMSFT** [comment]
@hholst80 so to clarify, you want something like this?

1. Open container
2. Go to some directory/stay in root
3. Apply some sort of filter, like filtering by prefix or filtering by tags
4. Do a download of the results of that filter, without having to "click Load more until all results are loaded, select all, click download"

**Comment by hholst80** [comment]
Yes I would like to be able to select a single or multiple directories and have those downloaded recursively to my local storage.

No need to enter those just select and Download. A live filter/search would be great

**Comment by JasonYeMSFT** [comment]
@hholst80 We are working on enabling downloading all blobs from the current directory in the container view. However, you will still need to use the prefix to filter the directory and navigate into it before downloading stuff from it. Does that sound like a reasonable solution to you?

**Comment by hholst80** [comment]
Either navigating into the directory and being able to download it as a unit recursively or finding and selecting it would be good solutions to the problem I had in my use case. Thank you for investing time and trying to understand what I am doing and how you can help improve it.

**Comment by JasonYeMSFT** [comment]
I have merged the feature work for enabling this action to 1.27.0 dev branch. I am going to close this issue and track the verification in #5050.
