### ISSUE TITLE
Uploads are very slow compared to previous versions

### ISSUE THREAD

**Issue by MikaereAtSkyCity** [microsoft/AzureStorageExplorer#614]
**Storage Explorer Version**: 1.4.1
**Platform/OS Version**: Windows Server 2016
**Architecture**: ia32
**Regression From**: 1.2 IIRC

#### Steps to Reproduce: ####
1. Import a typed csv file into a table with only half a dozen columns
2. It takes many seconds before the upload is listed in the Activities section of the window
3. It takes a long time to load 100 entities.  I've watching it now for over a minute and it is stuck on 1700 entities in a table that has around 6000 rows.

#### Expected Experience: ####
Responsive feedback about progress, entities are uploaded quickly.

#### Actual Experience: ####
It's slower than a wet week.

**Comment by MRayermannMSFT** [comment]
This is a fairly old issue and many changes have been made to uploads & downloads since it was open. If you're still having problems with uploads & downloads, please open a new issue against the latest version of Storage Explorer. Thanks.
