### ISSUE TITLE
The action 'Actions and Properties' under the View menu doesn't take effect

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6140]
**Storage Explorer Version**: 1.26.0-dev
**Build Number**: 20221006.3
**Branch**: feature branch
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.6 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.26.0)

## Steps to Reproduce ##
1. Launch Storage Explorer -> Open the EXPLORER panel.
2. Click 'View -> Actions and Properties'.
3. Observe the 'Actions & Properties' panel.
4. Check whether the 'Actions & Properties' panel can be expanded or collapsed by clicking 'Actions and Properties'.

## Expected Experience ##
The 'Actions & Properties' panel can be expanded or collapsed by clicking 'Actions and Properties'.

## Actual Experience ##
The 'Actions & Properties' panel can't be expanded or collapsed by clicking 'Actions and Properties'.

## Additional Context ##
This issue also reproduces for the shortcut 'Ctrl+Shift+P'/'Cmd+Shift+P'.

**Comment by MRayermannMSFT** [comment]
Something broke with the fix.

**Comment by MRayermannMSFT** [comment]
Figured it out. :)

**Comment by v-xianya** [comment]
Verified this issue on the build 20221028.4. Fixed.
