### ISSUE TITLE
The strings 'EXPLORER' and 'Search for resources' are selected when clicking 'Edit -> Select All' if one item is highlighted on the tree view

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6144]
**Storage Explorer Version**: 1.26.0-dev
**Build Number**: 20221006.3
**Branch**: feature branch
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.6 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.26.0)

## Steps to Reproduce ##
1. Launch Storage Explorer -> Open the EXPLORER panel.
2. Select one node on the tree view and make it is highlighted.
3. Click 'Edit -> Select All'.
4. Check no string is selected on the EXPLORER panel.

## Expected Experience ##
No string is selected on the EXPLORER panel.

## Actual Experience ##
The strings 'EXPLORER' and 'Search for resources' are selected.
![image](https://user-images.githubusercontent.com/41351993/194743747-0acbc84f-da57-46a8-88df-f447de00dd88.png)

**Comment by MRayermannMSFT** [comment]
I have made it so the EXPLORER text is not selected. However, I am going to won't fix the part about the text box for now.

**Comment by v-xianya** [comment]
Verified this issue on the build 20221028.4. The current behavior matches the comments. 
1. The 'EXPLORER' text is not selected.
2. The search string is selected.
![image](https://user-images.githubusercontent.com/41351993/198477214-6b47bb17-ee13-4531-82c2-bbf13f4b633d.png)
