### ISSUE TITLE
Explorer never opens even though i am logged in to Azure and i can add storage resources successfully

### ISSUE THREAD

**Issue by venkaus** [microsoft/AzureStorageExplorer#6147]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.26.0

### Regression From

1

### Architecture

x64

### Storage Explorer Build Number

1.26.0

### Platform

Windows

### OS Version

Windows 10 enterprise

### Bug Description

I can log into azure, add new connection, but i cannot view any connection as the explorer does not open even after clicking multiple times.

### Steps to Reproduce

Launch storage explorer
connect to azure
launch Explorer/view azure resources already connected

### Actual Experience

I can log into azure, add new connection, but i cannot view any connection as the explorer does not open even after clicking multiple times.

**Comment by venkaus** [comment]
When i click on the first icon on the left, nothing happens.

**Comment by MRayermannMSFT** [comment]
@venkaus when you first start Storage Explorer, if you don't do anything and just leave it, what do you see after ~30 seconds?

Can you describe and if possible share a screenshot? Thanks!

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. If you still use Storage Explorer, please try to bump the timeout parameter as suggested and see if it helps.
