### ISSUE TITLE
There is no border when using 'Tab' to focus the tab 'Actions' or 'Properties'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6148]
**Storage Explorer Version**: 1.26.0-dev
**Build Number**: 20221006.3
**Branch**: feature branch
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.6 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.26.0)

## Steps to Reproduce ##
1. Launch Storage Explorer -> Open the EXPLORER panel.
2. Press 'Tab' to focus the tab 'Actions'.
3. Check whether there is a border.

## Expected Experience ##
There is a border.
![image](https://user-images.githubusercontent.com/41351993/194811752-9ea5ff8f-999e-4e25-9821-613e8cecb27f.png)

## Actual Experience ##
There is no border.
![image](https://user-images.githubusercontent.com/41351993/194811743-04079a43-ed4d-4403-b325-6f0d25bd0066.png)

**Comment by v-xianya** [comment]
Verified this issue on the build 20221102.12. Fixed.
@MRayermannMSFT One things needs to confirm.
If focus the Expand icon on the Actions&Properties panel. The border line as below. Is this expected?
![image](https://user-images.githubusercontent.com/41351993/199635614-895ce0dc-90c5-4d01-91fd-88ab37b8d227.png)

The screenshot in previous version:
![image](https://user-images.githubusercontent.com/41351993/199635818-a7d01806-1777-45de-8719-a608d124f6dc.png)

**Comment by MRayermannMSFT** [comment]
Yes, I think I will leave this one as is with the blue border....
