### ISSUE TITLE
The EXPLORER panel can be totally overwritten by the 'Actions & Properties' panel

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6149]
**Storage Explorer Version**: 1.26.0-dev
**Build Number**: 20221006.3
**Branch**: feature branch
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.6 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.26.0)

## Steps to Reproduce ##
1. Launch Storage Explorer -> Open the EXPLORER panel.
2. Drag the 'Actions & Properties' panel up.
3. Check the EXPLORER panel can't be overwritten.

## Expected Experience ##
The EXPLORER panel can't be overwritten.
![image](https://user-images.githubusercontent.com/41351993/194810182-d9ef21e8-29b0-4453-b051-53e64dca9fb6.png)
## Actual Experience ##
The EXPLORER panel can be totally overwritten.
![image](https://user-images.githubusercontent.com/41351993/194810174-41508de0-6eee-4b2e-8ff9-5cffe787beb8.png)

## Additional Context ##
Here is the record:
![panel](https://user-images.githubusercontent.com/41351993/194811274-a9d976fe-3128-445a-a814-12a4d8f9055e.gif)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20221028.4. Fixed.
