### ISSUE TITLE
Upgrade to 1.4.1 breaks existing Quick Access links

### ISSUE THREAD

**Issue by OzBob** [microsoft/AzureStorageExplorer#615]
**Storage Explorer Version**: 1.4.1
**Platform/OS Version**: Windows
**Architecture**: ia32
**Regression From**: 1.4.1 -1

#### Steps to Reproduce: ####
1. Install 1.4.0
2. Open Storage Account
3. Add to Quick Access
4. Upgrade to 1.4.1
5. Quick Access link has red cross, and doubleclicking has no action
6. Adding new quick access links is OK

#### Expected Experience: ####
Expect Quick Access links to remain functional

#### Actual Experience: ####
red cross on quick access links
![image](https://user-images.githubusercontent.com/1796771/45006498-d812e780-b02b-11e8-8eb9-f229a978eb81.png)

**Comment by darshanrampatel** [comment]
I am also seeing this upon upgrade to 1.4.1.

![image](https://user-images.githubusercontent.com/14162899/44854694-2eb1a780-ac61-11e8-88e6-0bda6c30ef93.png)


Note that it is only the storage accounts that are inaccessible, not the tables, queues, containers, etc.

**Comment by MRayermannMSFT** [comment]
Are the broken links blob containers, file shares, queues, tables, or storage accounts? Additionally, did they come from a subscription, or SAS attach, name and key attach, or connection string attach?

**Comment by darshanrampatel** [comment]
@MRayermannMSFT, @orhanmaden I had this happen to me as well (again). Similarly to last time, it was only the storage accounts that were inaccessible, not the tables, queues, containers, etc.

These were all added from a subscription.

**Comment by orhanmaden** [comment]
@MRayermannMSFT I'm facing the same as @darshanrampatel: All storage accounts added by subscription.

**Comment by MRayermannMSFT** [comment]
Unable to reproduce this with the latest version of Storage Explorer
