### ISSUE TITLE
The string 'EXPLORER' disappears if using 'arrow up & arrow down' to go through the tree view resource with 'Load more' showing

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6150]
**Storage Explorer Version**: 1.26.0-dev
**Build Number**: 20221006.3
**Branch**: feature branch
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.6 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: AD-hoc testing
**Regression From**: Previous release (1.26.0)

## Steps to Reproduce ##
1. Launch Storage Explorer -> Open the EXPLORER panel.
2. Expand the resource on the tree view. (Make sure there is a scroll bar for the tree view)
3. Select one item -> Press the 'arrow down' until the 'Load more' showing.
4. Then press 'arrow up'.
5. Check the 'EXPLORER' shows well.

## Expected Experience ##
The string 'EXPLORER' shows well.

## Actual Experience ##
The string 'EXPLORER' disappears.
![image](https://user-images.githubusercontent.com/41351993/194813844-d8e9c19a-ddc0-4ff6-8b39-22220cf3aaf1.png)

## Additional Context ##
Here is the record:
![Explorerdisappear](https://user-images.githubusercontent.com/41351993/194812270-98203104-9839-4678-9264-da9f97d4100f.gif)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20221028.4. Fixed.
