### ISSUE TITLE
There is an incorrect warning icon next to the input box when typing an invalid name to create one service

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6154]
**Storage Explorer Version**: 1.26.0-dev
**Build Number**: 20221006.3
**Branch**: feature branch
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.6 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: AD-hoc testing
**Regression From**: Previous release (1.26.0)

## Steps to Reproduce ##
1. Expand one storage account.
2. Right click the Blob Containers node -> Click 'Create Blob Container'.
3. Type a whitespace to the input box. 
4. Check whether there is a correct warning icon.

## Expected Experience ##
There is a correct warning icon.
![image](https://user-images.githubusercontent.com/41351993/194979051-b110ab5b-7d3f-4ef7-87ff-97a470a2c431.png)

## Actual Experience ##
There is an incorrect warning icon.
![image](https://user-images.githubusercontent.com/41351993/194978944-a453dd42-a10c-4a22-a76e-6d3aa5a9156c.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20221028.4. Fixed.
![image](https://user-images.githubusercontent.com/87792676/198457681-73139c78-5d5e-42c6-9bfa-88ec4c4e7f36.png)
