### ISSUE TITLE
It is better to add the helpful error details in the activity log if running upload with invalid characters were filled in the 'Destination directory' field

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6157]
**Storage Explorer Version**: 1.26.0-dev
**Build Number**: 20221012.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.6 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: AD-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> File Share.
2. Create a file share -> Click 'Upload -> Upload Files...'.
3. Select one file -> Type '?' to the Destination directory field.
4. Click 'Upload' -> There is a failed activity log.
5. Check whether we can directly get the error details from the activity log.

## Expected Experience ##
We can directly get the error details from the activity log.

## Actual Experience ##
Can't get the error details from the activity log.
![image](https://user-images.githubusercontent.com/41351993/195299528-93147690-3cf9-4b8a-90c3-f4e166e1b7e8.png)

## Additional Context ##
1. It would be better to remove the 'Retry...' next to the activity log. Here is the screenshot when clicking 'Retry...':
![image](https://user-images.githubusercontent.com/41351993/195299485-d6c46d4b-6ac7-43f9-9144-65f6cf41c503.png)
2. This issue also reproduces when typing " \ / : | < > * ? to the Destination directory field.
Below is the screenshot when creating a new folder under one file share:
![image](https://user-images.githubusercontent.com/41351993/195299884-9d5734c1-1f68-46ef-96c5-a77f5939d7a1.png)

**Comment by JasonYeMSFT** [comment]
There isn't much we can do in the activity log since the error details aren't exposed to us (they are in the logs). However, we should be able to tighten the validation logic in the upload dialog to prevent people from entering invalid paths for the destination directory.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230127.10. Fixed. So, we are going to close it.
![image](https://user-images.githubusercontent.com/41351993/215252584-5e417658-576e-4e3f-a22b-c6e9777d09db.png)
