### ISSUE TITLE
Update Storage Explorer icons from MDL2 to Fluent

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#6159]
MDL2 icons are being deprecated in favor of the Fluent System Library. We should review the icons we currently have and swap them out for Fluent icons.

We should consider doing this in tandem with our switch to React, since React will change how we consume and share icons across the app.

**Comment by MRayermannMSFT** [comment]
Please present a mock-up (no need to code, just simple and quick copy/paste editing of screenshots) of the icons in Storage Explorer so we can confirm if we want to make the move.

**Comment by craxal** [comment]
We received information that changing to Fluent icons is not required, nor are there any timelines. Since there are no requirements, we're just closing this item.
