### ISSUE TITLE
The attached two services which are different types and same name display inconsistent names

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#616]
**Storage Explorer Version**: 1.5.0 
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture**: ia32/x64
**Build Number**:20180829.1
**Commit**: c2183e19
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Attach one **blob container** with SAS URL using the default name.
**Display name**: xuantest
**SAS URL**: https://bloblcl1.blob.core.windows.net/xuantest?st=2018-08-30T08%3A55%3A40Z&se=2018-09-01T08%3A55%3A00Z&sp=rwdl&sv=2018-03-28&sr=c&sig=80CfImOnjgOwe5vLrv6z%2B6zcgCTHyQb0M7OZO9u7gzE%3D
2. Attach one **file share** which has the same name.
**Display name**: xuantest
**SAS URL**: https://bloblcl1.file.core.windows.net/xuantest?st=2018-08-30T08%3A57%3A20Z&se=2018-09-01T08%3A57%3A00Z&sp=rwdl&sv=2018-03-28&sr=s&sig=fTy3YmBAxOzyBhQqfBDcashKyrMBZG3oVaxWKxZ1w90%3D
3. Expand **'Local & Attached'** -> **Storage Accounts** -> **(SAS-Attached Service)** -> **Blob Containers and File Shares.**
4. Check the displayed names.

#### Expected Experience: ####
The attached two services display as the **same name**.

#### Actual Experience: ####
The attached two services display **different name**.
![sas](https://user-images.githubusercontent.com/34729022/44842557-be416100-ac35-11e8-9466-1c89ede3520c.png)

**Comment by v-limu** [comment]
This issue also reproduces on the latest build [20190927.10](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3091851).
