### ISSUE TITLE
Follow up - repeat issue - Query Builder cut in half and can not see Table top menu

### ISSUE THREAD

**Issue by OzBob** [microsoft/AzureStorageExplorer#6160]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.26.0

### Architecture

x64

### Storage Explorer Build Number

20221001.2

### Bug Description

Open query builder randomly open halfway and the top table menu will be obscured

### Steps to Reproduce

Open Azure Storage table
Open query builder
Filter
Close query builder
Refresh
Open query builder - randomly it will open half way and the top menu will be obscured

### Actual Experience

as per screen shot
![image](https://user-images.githubusercontent.com/1796771/188780860-bc75d6b8-8474-4949-861e-4a518e218a1f.png)

### Expected Experience

Open query bulder screen repaints Table top menu then query builder.

### Additional Context
repeat issue of #6077

changing the size of the main window does slowly creep the query builder back into it's proper spot.
the 'divider' if dragged left and right 20 times, does also slowly creep it back into view.

**Comment by MRayermannMSFT** [comment]
@OzBob can you try resizing the Storage Explorer window as whole? That should reset the UI. In the meantime we are working on a fix for this issue.

**Comment by craxal** [comment]
@OzBob Thanks for providing details on this issue. This is a known bug, and we are working on a solution. You can follow the status of this issue at #5806.
