### ISSUE TITLE
There is a prompt dialog when pasting one deleted blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6161]
**Storage Explorer Version**: 1.27.0-dev
**Build Number**: 20221013.5
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.6 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: AD-hoc testing
**Regression From**: Previous release (1.24.3)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Copy the blob container -> Delete the blob container.
3. Right click one 'Blob Containers' node -> Click 'Paste Blob Container'.
4. Check whether there is no prompt dialog.

## Expected Experience ##
There is no prompt dialog.

## Actual Experience ##
There is a prompt dialog.
![image](https://user-images.githubusercontent.com/41351993/195543922-cded8ec1-530c-44f0-8dba-c65ecef4cb4c.png)

## Additional Context ##
This issue also reproduces for one ADLS Gen2 blob container.

**Comment by JasonYeMSFT** [comment]
We believe this is an edge case (trying to paste a deleted container) so won't fix for now.
