### ISSUE TITLE
Nothing happens when clicking 'Show in Folder' action next to the activity log if downloading one folder named ' '

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6162]
**Storage Explorer Version:** 1.27.0-dev
**Build Number:** 20221013.5
**Branch:** main
**Platform/OS:** Windows 10
**Architecture:** ia32/x64
**How Found:** AD-hoc testing
**Regression From:** Previous release (1.24.3)

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Create a folder named ' '.
3. Upload a blob to the folder -> Download the folder.
4. There is a download activity log -> Click 'Show in Folder' next to the activity log.
5. Check whether File Explorer is opened and the folder is highlighted.

## Expected Experience ##
File Explorer is opened and the folder is highlighted.
## Actual Experience ##
Nothing happens.

## Additional Context ##

1. This issue doesn't reproduce on Mac & Linux Ubuntu 22.04.
2. File Explorer is opened and the folder is not highlighted for one file share.
3. In 1.24.3, the File Explorer is opened, but the folder is not highlighted.

**Comment by JasonYeMSFT** [comment]
According to this https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions. Having directories whose name ends with whitespace may lead to undefined behavior. I think we'll have to rely on the users to prevent doing this for now.
