### ISSUE TITLE
Explorer page is not working in 1.26 version

### ISSUE THREAD

**Issue by Parthajit16sep** [microsoft/AzureStorageExplorer#6163]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.26.0

### Regression From

1.22.0

### Architecture

i86

### Storage Explorer Build Number

20221001.2

### Platform

Windows

### OS Version

windows 10

### Bug Description

The Explorer page is not working in 1.26.0 version even after successfully signing into Azure portal and establishing a connection to the resource signing

### Steps to Reproduce

Launch Storage explorer

### Actual Experience

The Explorer page is not working in 1.26.0 version even after successfully signing into Azure portal and establishing a connection to the resource

**Comment by JasonYeMSFT** [comment]
Could you try the steps we commented in this issue to see if that resolves your issue? https://github.com/microsoft/AzureStorageExplorer/issues/6147

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue, we recommend opening an Azure support ticket via the portal. Alternatively you can open a new issue here.
