### ISSUE TITLE
The statistics result is incorrect when running 'Selection Statistics' for blobs/ADLS Gen2 blob

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6164]
**Storage Explorer Version**: 1.27.0-dev
**Build Number**: 20221014.6
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.6 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test case
**Regression From**: Previous release (1.26.0)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Right click the blob -> Click 'Selection Statistics'.
4. Observe the activity log.
5. Check whether displays a correct result.

## Expected Experience ##
Display a correct result.

## Actual Experience ##
Display an incorrect result.
![image](https://user-images.githubusercontent.com/41351993/195780936-dc01ea71-02ef-4fa3-bc06-32a41f2da983.png)

## Additional Context ##

1. This issue also reproduces for soft deleted blobs.
2. This issue also reproduces for ADLS Gen2 blobs.
3. This issue doesn't reproduce for folders.

**Comment by MRayermannMSFT** [comment]
Fix merged

**Comment by MRayermannMSFT** [comment]
JK. Don't verify this fix yet.

**Comment by MRayermannMSFT** [comment]
Ok, now it is merged!

**Comment by v-xianya** [comment]
Verified this issue on the main build 20221024.1. Reproduce. So we are going to reopen it and verify on the newer build.
![image](https://user-images.githubusercontent.com/41351993/197463659-5f69b3f1-03c8-4a99-ab7e-07b0ddb65d7a.png)

**Comment by MRayermannMSFT** [comment]
Ok....let's try this again. 😁 Fix merged into main.

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT 
We verified this issue on the build main 20221027.6.
There is a problem when running 'Selection Statistics' for soft-deleted ADLS Gen2 blobs/Regular blobs.
Could you help to take a look? Also, for the Statistics feature, we opened a new bug against ADLS Gen2: [6220](https://github.com/microsoft/AzureStorageExplorer/issues/6220)

![image](https://user-images.githubusercontent.com/41351993/198242932-b3cf8c04-503d-437d-863d-409fad27f77c.png)
ERROR:
`Failed to inspect 'atable123.txt', error: {
  "name": "Error",
  "message": "Unable to get size of atable123.txt",
  "stack": "Error: Unable to get size of atable123.txt\n    at ActiveState._inspectBlob (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-blob-extension\\dist\\src\\index.js:2:91188)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"
}`

**Comment by v-xianya** [comment]
Verified this issue on the main build 20221028.2. Fixed.
