### ISSUE TITLE
error - could not access resources for this tennant

### ISSUE THREAD

**Issue by jfernandes2022** [microsoft/AzureStorageExplorer#6165]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.26.0

### Architecture

x64

### Platform

Windows

### Bug Description

cant access storage account in the storage explorer app, but i can see it in the browser

here is the error details
{
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"self signed certificate in certificate chain\\\",\\n  \\\"stack\\\": \\\"Error: self signed certificate in certificate chain\\\\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)\\\\n    at TLSSocket.emit (node:events:526:28)\\\\n    at TLSSocket._finishInit (node:_tls_wrap:944:8)\\\\n    at ssl.onhandshakedone (node:_tls_wrap:725:12)\\\",\\n  \\\"code\\\": \\\"SELF_SIGNED_CERT_IN_CHAIN\\\"\\n}\""
}

### Steps to Reproduce

launch storage explorer
cant see the storage here

### Actual Experience

cant access storage account in the storage explorer app, but i can see it in the browser

### Expected Experience

shoul be able to access the storage account

**Comment by jfernandes2022** [comment]
![image](https://user-images.githubusercontent.com/105778840/195800237-d48a3edc-e314-4270-a608-919e15dcd343.png)

even Reuathenticate now doesnt work

**Comment by jfernandes2022** [comment]
even Reauthenticate now does not help

![image](https://user-images.githubusercontent.com/105778840/195800757-9d421f54-6a9e-4774-8bd1-00044c380f4d.png)

**Comment by MRayermannMSFT** [comment]
Can you give using system proxy setting a try? You can read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue, we recommend opening an Azure support ticket via the portal. Alternatively you can open a new issue here.
