### ISSUE TITLE
File Previewing doesn't respect Content Type attribute

### ISSUE THREAD

**Issue by miika-polea** [microsoft/AzureStorageExplorer#6166]
I have log messages in plain text files in blobs. Content Type of files is text/plain. However, these files can't be previewing because they don't have file extension txt.

**Comment by JasonYeMSFT** [comment]
If your blobs have some file extension, you can add that file extension to the allowed extensions list. Unfortunately we don't support previewing files without any file extension or previewing files based on their content type.

![image](https://user-images.githubusercontent.com/39359541/195950704-c64709ff-8414-4cf5-a822-9994f8bb235d.png)

**Comment by JasonYeMSFT** [comment]
I added a set of text/* content types on top of the file extension list. If the blob's content type matches any content type in the set, the preview action will be enabled.
