### ISSUE TITLE
"Encoding" dropdown is backwards when viewing messages in queue

### ISSUE THREAD

**Issue by jakraft** [microsoft/AzureStorageExplorer#6167]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.26.0

### Regression From

N/A (fresh install)

### Architecture

x64

### Storage Explorer Build Number

20221001.2

### Platform

Windows

### OS Version

Windows 11

### Bug Description

When viewing messages in an Azure Queue, the "Encoding" dropdown has the opposite expected behavior when selecting "Base64" versus "UTF8".

### Steps to Reproduce

1. Launch storage explorer
2. Create a new queue and add a message
3. Double click on the message to open the "View Message" dialogue.
4. Toggle through the "Encoding" dropdown options.

### Actual Experience

Here's what it looks like when Base64 is selected:
![image](https://user-images.githubusercontent.com/52800741/195962209-84cf8eb6-4feb-483a-8b7e-0ef7480ab811.png)

And here's what it looks like when UTF8 is selected:
![image](https://user-images.githubusercontent.com/52800741/195962223-d9c75d91-7464-4415-8a65-85096048aae2.png)

As you can see, the opposite encoding is used.

### Expected Experience

The selected encoding option should match the encoding used in the "message text" field.

**Comment by MRayermannMSFT** [comment]
@jakraft the dropdown is correct, though albeit confusing. When you select a value in the dropdown, you are basically saying "this message is stored as X, so decode it". So for example, for base64, you would select that if the message is encoded as base64 and you want it decoded so you can read it. We will try to update these labels to reduce confusion. Does that all make sense?

**Comment by MRayermannMSFT** [comment]
@jakraft what do you think about these new labels/values?

For adding a message:
![image](https://user-images.githubusercontent.com/21112697/197004560-de3693b8-dce3-4411-9159-5a8e6a597048.png)

For viewing a message:
![image](https://user-images.githubusercontent.com/21112697/197004694-56e0f1e4-4040-4d42-b932-0cded97593d1.png)

**Comment by jakraft** [comment]
@MRayermannMSFT thanks for the clarification! Agreed, I think those labels are much clearer.

**Comment by MRayermannMSFT** [comment]
New labels merged for 1.27
