### ISSUE TITLE
No product name 'Microsoft Azure Storage Explorer' displays on 'Delete Blob Container' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#617]
**Storage Explorer Version**: 1.5.0 
**Platform/OS Version**: MacOS High Sierra
**Architecture**: ia32/x64
**Build Number**:20180829.1
**Commit**: c2183e19
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Choose one account and attempt to delete one blob container.
2. Check the popped confirmation dialog.

#### Expected Experience: ####
It shows the product name 'Microsoft Azure Storage Explorer'.
![expect](https://user-images.githubusercontent.com/34729022/44844156-a79d0900-ac39-11e8-93d1-9b4d3a05afb9.png)

#### Actual Experience: ####
No product name 'Microsoft Azure Storage Explorer' displays
![no](https://user-images.githubusercontent.com/34729022/44844449-7ffa7080-ac3a-11e8-83cf-a9fe7e022459.png)

#### More info: ####
This issue also reproduces when promoting blob snapshots; Detaching services/account; Acquiring lease for one blob.

**Comment by MRayermannMSFT** [comment]
Looked into it, on macOS we cannot add a title to these types of system dialogs. We also cannot change to using our own dialog because that would break Cloud Explorer. Won't fix/external.
