### ISSUE TITLE
No confirmation dialog is displayed when uploading a file that already exists in a container - the file is simply overwritten

### ISSUE THREAD

**Issue by ziobernamac** [microsoft/AzureStorageExplorer#6171]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.26.0

### Regression From

1.25.1

### Architecture

x64

### Storage Explorer Build Number

20221001.2

### Platform

All

### OS Version

macOS Monterey

### Bug Description

No confirmation dialog is displayed when uploading a file that already exists in a container - the file is simply overwritten

### Steps to Reproduce

try to upload a file that already exists 

### Actual Experience

no confdirmation dialog for overwrite...the file is overwritten without permission

### Expected Experience

a confirmation dialog shoud appear

**Comment by MRayermannMSFT** [comment]
@ziobernamac

Are you working with File Shares, Blob Containers, ADLS Gen2 Blob Containers, or ADLS Gen1 Containers?

Can you try to document what you are seeing when you are able to reproduce this issue? We'd like to see:
1. Video or screenshots showing the issue being reproduced, make sure to show that the file exists in the container prior to being overwritten, and then show it again after being overwritten, with the modified data showing a new modified date time.
2. If you are working with  File Shares, Blob Containers, or ADLS Gen2 Blob Containers, then please also do the following before/during/after you reproduce the issue:
   1. Clean out the folder ~/.azcopy
   2. After you start Storage Explorer, go to: Settings (gear on the left) > Transfers > AzCopy > Log Level, and set the log level to be Debug
   3. After you reproduce the issue, share the contents of the ~/.azcopy folder with us

**Comment by ziobernamac** [comment]
From what I can understand the overwrite confirmation dialog does not appear only when an upload is made via drag'n drop ... using the upload button and selecting the file, the dialog appears correctly

**Comment by ziobernamac** [comment]
https://user-images.githubusercontent.com/61152773/196244686-b525c615-e639-40a9-a04e-60631e510f15.mp4

**Comment by MRayermannMSFT** [comment]
Thank you for the timely reply. We will be shipping a new build as soon as possible.

**Comment by MRayermannMSFT** [comment]
We have released 1.26.1 to address this issue.
