### ISSUE TITLE
The action 'Split' is disabled for the tab of one regular/emulator blob container 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6173]
**Storage Explorer Version**: 1.27.0-dev
**Build Number**: 20221017.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.6 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.26.0)

## Steps to Reproduce ##
1. Expand one non-ADLS Gen2 storage account -> Blob Containers.
2. Open one blob container -> Right click the opened tab.
3. Check whether the action 'Split' is enabled or not.

## Expected Experience ##
The action 'Split' is enabled.

## Actual Experience ##
The action 'Split' is disabled.
![image](https://user-images.githubusercontent.com/41351993/196113784-ed02a626-0a67-4db9-a9e8-fe1c2424bc22.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20221022.1. Fixed. So we are going to close it.
