### ISSUE TITLE
azcopy can be excessive, hurting performance and writing logs too large

### ISSUE THREAD

**Issue by munael** [microsoft/AzureStorageExplorer#6178]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.26.0

### Architecture

i86

### Platform

Windows

### OS Version

Windows 10; 17763

### Bug Description

Logs can become very big. Unusably so.

Happens when doing operations on a deep directory with a lot of files.

azcopy logging is quite useful for failed transactions. But can it be pruned a bit?

### Steps to Reproduce

1. Open a blob container with a lot (hundreds of thousands) of nested directories and files.
2. Do some operation that works on the full tree. Copy, delete, etc.
3. Check the logs at `"C:\Users\<user>\.azcopy"`.
4. See: 
![image](https://user-images.githubusercontent.com/5769148/196183607-ef8d5e0b-7a51-44fe-8d13-db5d27ccc1c5.png)

### Actual Experience

Logs grow large enough to possibly crash a system.

**Comment by MRayermannMSFT** [comment]
> BTW the setting to disable Log's does not disable all logs. In the subfolder 'plans' I still had a few GB's written in two days.

Storage Explorer doesn't have the ability to tell AzCopy to not-keep plan files around. We will talk to them about this.

> The default should likely not be info.

It has been recommended to us that we stick with Info. When something bad happens/something fails/something goes wrong, it is very helpful to have the log files around to confirm what has happened. Perhaps there is more we can in the UI though to help you out. Maybe a quick way to delete the logs/plans of a finished transfer?

**Comment by MRayermannMSFT** [comment]
We discussed this today and have decided to add a setting which when enabled will have Storage Explorer auto delete AzCopy logs of successful transfers. Unsure if we can do anything about the plan files though.

**Comment by richardMSFT** [comment]
The new auto delete log setting should be shipping with 1.28.0.
