### ISSUE TITLE
Upload VHD - Support for Linux ARM64

### ISSUE THREAD

**Issue by rbposborne** [microsoft/AzureStorageExplorer#6179]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Upload a VHD with  architecture ARM64

### Desired Solution

Include architecture field in upload panel

**Comment by MRayermannMSFT** [comment]
Done.
