### ISSUE TITLE
Fail to navigate to the original service in the tree view after clicking the tab of new created service in editor

### ISSUE THREAD

**Issue by v-dantch** [microsoft/AzureStorageExplorer#618]
**Storage Explorer Version**: 1.5.0 
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture**: ia32
**Build Number**:20180829.1
**Commit**: c2183e19
**Regression From**: Not a Regression

#### Steps to Reproduce: ####
1. Expand one storage account -> Right click 'Blob Containers' node ->Select 'Create Blob Container'.
2. After being created, make sure the new blob container is opened in the editor.
3. Collapse this storage account in tree view.
4. Click the tab of the new created blob container in editor.
5. Check whether succeed to navigate to the original one in the tree view or not.

#### Expected Experience: ####
This storage account is expanded and succeed to navigate to the original one in the tree view.
![expect](https://user-images.githubusercontent.com/34729092/44844061-5db42300-ac39-11e8-9f3d-22839600ccfb.PNG)

#### Actual Experience: ####
Fail to navigate to the original service in the tree view and this storage account is not expanded.

**Comment by v-xianya** [comment]
This issue still reproduces on the latest build [20190919.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3064513).

**Comment by v-limu** [comment]
This issue has been fixed on build [20191123.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3268481). So we close it.
