### ISSUE TITLE
Migrate to Find Blobs by Tags in Container API

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#6184]
Currently we are using https://learn.microsoft.com/en-us/rest/api/storageservices/find-blobs-by-tags
We should migrate to https://learn.microsoft.com/en-us/rest/api/storageservices/find-blobs-by-tags-container

The current API we use cannot properly authenticate with container level SAS and limits our capability.

We should also disable the view context dropdown when filtering by tags, as it has no meaning during tag filtering. Leave value as whatever it currently is, but the dropdown should be disabled.

**Comment by Venu-prahalad** [comment]
@MRayermannMSFT @JasonYeMSFT I downloaded latest version 1.27.0 and tried the scenario mentioned in current bug and merged bug #6259 I still didnt get it to work. Now I dont see authentication error as I saw earlier but I see the error instead "Value for one of the query parameters specified in the request URI is invalid. RequestId:5a73eade-101e-007a-0739-0608c0000000 Time:2022-12-02T10:34:26.6157119Z".
Below is the simple filter I have applied
![image](https://user-images.githubusercontent.com/32172428/205274547-da08e35a-b8ca-405b-a47a-0b0acd437e62.png)


log is
[2022-12-02T10:44:47.204Z] (se-blob-extension:24468) <ERRO> API call for BlobContainerClient.findBlobsByTags failed
  GET https://strgeastus2xx.blob.core.windows.net/containerxx?se=2023-08-01&sv=2021-04-10&si=intl091bd&sr=c&sig=AzureSAS Token Redacted&maxresults=5000&comp=blobs&where=%22ProcessStatus%22%3D'value1'&restype=container - 400
  Credential used: SAS token - se=2023-08-01&sv=2021-04-10&si=intl091bd&sr=c&sig=******
  RequestId: 93f553af-7755-4f5c-ae69-c88b8fffa5ec, Date sent: Fri, 02 Dec 2022 10:44:46 GMT, ApiVersion: 2017-04-17, ProxySettings: undefined
  ErrorCode: undefined

**Comment by JasonYeMSFT** [comment]
@Venu-prahalad Does you access policy (intl091bd) has the "Find" permission in it? You will need that permission to filter blobs in the container by tags. By the way, neither us/Azure Portal currently support generating access policy with the "Find" permission. You can either generate a SAS with the Find permission without using the access policy in Storage Explorer or have a separate script to edit that access policy.

**Comment by Venu-prahalad** [comment]
@JasonYeMSFT Thanks for responding. I confirm I have given almost all of the possible permissions on it. below is the permissions list granted which I retrieved from az commandlet.
![image](https://user-images.githubusercontent.com/32172428/205555625-3d869f09-336e-4b51-a198-edba42afbf39.png)
