### ISSUE TITLE
It is better to add the action 'Copy Table' with only Azure AD credentials

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6187]
**Storage Explorer Version**: 1.26.1
**Build Number**: 20221018.5
**Branch**: Release version (Get from release Github page)
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.6 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Azure AD attach the table.
3. Right click the azure AD attached table.
4. Check whether there is an action 'Copy Table'.

## Expected Experience ##
There is an action 'Copy Table'.

## Actual Experience ##
There is no action 'Copy Table'.
![image](https://user-images.githubusercontent.com/41351993/196634390-7b6e841a-33f9-457b-a64b-9ddc38a91790.png)

## Additional Context ##
There is the action 'Copy Blob Container' for one Azure AD attached blob container.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20230107.10. Fixed.
![image](https://user-images.githubusercontent.com/87792676/215239376-62245fba-0181-49fa-b414-35b827378e50.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20230127.10. Fixed.
![image](https://user-images.githubusercontent.com/87792676/215239391-bc7732ff-973f-40b5-8ef2-c7e971fb8089.png)
