### ISSUE TITLE
Quick access items stop working after keys are invalidated

### ISSUE THREAD

**Issue by motikadosh** [microsoft/AzureStorageExplorer#6188]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.26.1

### Architecture

x64

### Storage Explorer Build Number

20221018.5

### Platform

Windows

### OS Version

Windows 11

### Bug Description

Quick access items stop working after keys are invalidated.
After unpinning and creating new quick access items, it is working.

### Steps to Reproduce

1. Create Quick access item for some storage.
2. Rotate keys for that storage.
3. Try using the Quick access item - it should fail, specifying permission error.

### Actual Experience

Got unauthorized access error.

**Comment by MRayermannMSFT** [comment]
@motikadosh I'm a bit confused. You're saying you expected a "permission error". Right? And then you say you got an "unauthorized access error". Yes? Aren't those basically the same thing? You don't have the right permissions anymore so your attempt at access is unathorized?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue we recommend that you go ahead and open a ticket via the Azure Portal. Alternatively you can open a new issue here.
