### ISSUE TITLE
Prefix search option in Storage Explorer for File-shares

### ISSUE THREAD

**Issue by Naamavarthani** [microsoft/AzureStorageExplorer#6189]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I am unable to view contents of files or folders in the file shares account using Storage Explorer by specifying the prefix path in prefix search option.

### Desired Solution

I'd like to have support for search options in files/folder's/sub-folder's to view contents in the file share account.

### Alternatives and Workarounds

Even when the full prefix path of the file was given, we face no data available as result in the Main display

### Additional Context

The prefix match search option is not working as expected for file share

**Comment by MRayermannMSFT** [comment]
Done. Will be included in 1.28:
![image](https://user-images.githubusercontent.com/21112697/206767712-a5ecec26-1c53-4a6c-8367-c0b93f60fcdd.png)
