### ISSUE TITLE
The border size of the check boxes on the Settings page is changed by the descriptions' width

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6193]
**Storage Explorer Version**: 1.27.0-dev
**Build Number**: 20221020.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.6 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Ad-hoc testing
**Regression From**: Previous release (1.26.1)

## Steps to Reproduce ##
1. Open Settings panel -> Press 'Tab' to focus check boxes.
2. Observe the borders of the check boxes.
3. Check whether all the borders keep the same.

## Expected Experience ##
All the borders keep the same.
![image](https://user-images.githubusercontent.com/41351993/196881954-ba0db4c1-7837-4b09-9db7-cdbbb26433cc.png)

## Actual Experience ##
The border size changes by the descriptions' width.
![image](https://user-images.githubusercontent.com/41351993/196881822-de930174-75a9-488b-9f12-c5115996d795.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20221106.3. Fixed. So, we are going to close it.
