### ISSUE TITLE
After table refresh, when opening the Query builder, the upper part of query builder disappear and become unavailable.

### ISSUE THREAD

**Issue by asmundwego** [microsoft/AzureStorageExplorer#6194]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.26.1

### Architecture

ia32

### Storage Explorer Build Number

20221018.5

### Platform

Windows

### OS Version

Windows 11

### Bug Description

After doing a table refresh, and then opening the Query builder, the upper part of the query builder, including the toolbar buttons for the table, becomes unavailable.

### Steps to Reproduce

1. Open a table
2. Click to select one row in the table
3. Click Refresh button to refresh the table content
4. Click the Query button
5. Now the upper part, including the toolbar for the table is hidden.

### Actual Experience

It seems that the query builder is aligned to bottom of the area above the table data area, and the panel for toolbar and query builder is not resized correctly, so that the top content is hidden.

![image](https://user-images.githubusercontent.com/14922923/196892456-62222e8c-a611-4749-9633-8a50a8b55f58.png)

### Expected Experience

Query builder should show properly.
![image](https://user-images.githubusercontent.com/14922923/196894187-a7aad411-c139-45fc-a695-f6c5010d77f0.png)

### Additional Context

This is easy to reproduce. No unusual configurations.
If not selecting a row in the table, opening the query panel does not have issues after refresh. But if you have clicked on a row in the table, or have already performed a query before the refresh, the issue appears when opening the Query builder.

Another thing that is not related to this issue, but with the report form here on github:
In the Platform dropdown, there is only avalable options for "i86" and "x64", but in the About dialog in Azure Storage Explorer, the value for Architecture is "ia32":
![image](https://user-images.githubusercontent.com/14922923/196896131-46939e0e-beb1-4512-9bdb-2930cc2dce8d.png)

I edited this manually after initial post to fix the value in the Architecture section.

**Comment by JasonYeMSFT** [comment]
This is a known issue https://github.com/microsoft/AzureStorageExplorer/issues/6194. You can workaround it by resizing the app or table explorer until the layout become normal again. We are working on a fix to this problem right now.
