### ISSUE TITLE
It is better to enable the download arrow if both menu actions are disabled

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6200]
**Storage Explorer Version**: 1.27.0-dev
**Build Number**: 20221021.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.6 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one non-ADLS Gen2 storage account -> Blob Containers (Make sure the blob version is enabled).
2. Create a blob container -> Upload one blob.
3. Modify its property to get a blob version.
4. Right click the blob -> Click 'Manage History -> Manage Versions'.
5. Click 'Select All' on the toolbar.
6. Check whether the download arrow is enabled or not. 

## Expected Experience ##
The download arrow is enabled.

## Actual Experience ##
The download arrow is disabled.
![image](https://user-images.githubusercontent.com/41351993/197158003-a8159cab-70cb-4a26-8b51-6ff4927d145e.png)

**Comment by JasonYeMSFT** [comment]
We have decided to make the dropdown button be disabled if all actions in the menu are disabled.
