### ISSUE TITLE
Speed limit can not be disabled after it was enabled

### ISSUE THREAD

**Issue by goldengel** [microsoft/AzureStorageExplorer#6201]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.26.1

### Architecture

x64

### Storage Explorer Build Number

*1018.5

### Platform

Windows

### OS Version

Win 10

### Bug Description

Bandwith of 0 will not be accepted but it should disable the bandwith limitation

### Steps to Reproduce

Setup bandwith of 3 = 3Mbit/s.
Setup bandwith 0 = is ignored instead of disabled limitation

### Actual Experience

Setup bandwith of 3 = 3Mbit/s.
Setup bandwith 0 = is ignored instead of disabled limitation

**Comment by MRayermannMSFT** [comment]
@goldengel I am able to repro this as well. Will look into it.

**Comment by JasonYeMSFT** [comment]
We have a bug in the code that prevents setting bandwidth limit to 0. I will make a fix to this bug in 1.27.0.
