### ISSUE TITLE
Request for wild card search feature in Storage explores while searching files in Blob storage or ADLS storage

### ISSUE THREAD

**Issue by Shirishshetty20** [microsoft/AzureStorageExplorer#6202]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I am unable to search using wild card or any search for that matter using Storage explorer on Blob storage or ADLS storage

### Desired Solution

Some kind of wild search or Search button for that container/folder to search a file based on filename

### Alternatives and Workarounds

We use Azure portal container overview -to do a search on the files. Though it doesnt support wild character but some form of search is available there

**Comment by MRayermannMSFT** [comment]
@Shirishshetty20 can you take a screenshot of the search mechanism you are using on portal? Also, are you working with an ADLS Gen2 storage account or a non-ADLS Gen2 account?

**Comment by MRayermannMSFT** [comment]
@Shirishshetty20 ?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response since we aren't sure what portal feature you are referring to. If you decide to provide more info, please open a new feature request.
