### ISSUE TITLE
Access issue

### ISSUE THREAD

**Issue by cliffeby** [microsoft/AzureStorageExplorer#6203]
It's been two years since I've tried to use MS ASE.  It now appears that it won't accept my Azure account's personal email.  Is there a work around?  I use my hotmail account for business and do not have access to a "business" domain.

I am able to access the table with Microsoft Machine Learning Studio (classic)](https://studio.azureml.net/)

{
  "message": "{\"message\":\"AADSTS50020: User account '{EmailHidden}' from identity provider 'live.com' does not exist in tenant 'Microsoft Services' and cannot access the application '04b07795-8ddb-461a-bbee-02f9e1bf7b46'(Microsoft Azure CLI) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.\\r\\nTrace ID: a8d941d0-a954-4524-ae88-1bed05173b00\\r\\nCorrelation ID: a5b4c620-6308-45e9-825b-fc049332724c\\r\\nTimestamp: 2022-10-22 20:50:56Z\",\"lastError\":{}}"
}

**Comment by MRayermannMSFT** [comment]
@cliffeby based on the error, it looks like you are probably attaching an individual resource via Azure AD, and when doing so selecting the wrong tenant.

When you are on this step of the connection process:
![image](https://user-images.githubusercontent.com/21112697/197586931-f9a4a71b-ab83-4cce-ad1b-ccac3b502025.png)

You need to pick the tenant that the resource you are connecting to is in. Do not pick the "Microsoft account" tenant. That will not work.

**Comment by cliffeby** [comment]
Thanks for the response. I disconnected the table and tried again.  I signed in with Shared access signature URL (SAS) but no success.

![image](https://user-images.githubusercontent.com/1431998/197595631-f3bd5970-063c-4327-a7bc-6361f405a6d8.png)

I can use the access browser in Azure Portal without issue
![image](https://user-images.githubusercontent.com/1431998/197606623-0d1c2910-1bfe-4c2a-b90e-89966c9d7315.png)

**Comment by cliffeby** [comment]
**Version info**
Microsoft Azure Storage Explorer

[Main Instruction]
Microsoft Azure Storage Explorer

[Content]
Version: 1.26.1
AzCopy Version: 10.16.0

Platform: Windows
Architecture: ia32 
Build Number: 20221018.5 
Commit: 0988c52e1a 
Support ID: 218ee434-71f4-aa70-8773-04d2920da3c7 

Copyright © 2022 Microsoft. All rights reserved.

[OK]

Generally the sign in takes me to a browser tab that says **Authenticated. You can return to Storage Explorer. You might need to authenticate again if you close this browser tab.**

**Comment by MRayermannMSFT** [comment]
> Thanks for the response. I disconnected the table and tried again. I signed in with Shared access signature URL (SAS) but no success.

Why did you not use attach via Azure AD and select the correct tenant? Also in your screenshot I only see the table attached via Azure AD but you said you tried using a SAS URL?

**Comment by cliffeby** [comment]
Here is what i get when I use the SAS for the Storage Account.



Unable to retrieve child resources.

Details:
{
  "name": "RestError",
  "message": "{\"odata.error\":{\"code\":\"AuthorizationResourceTypeMismatch\",\"message\":{\"lang\":\"en-US\",\"value\":\"This request is not authorized to perform this operation using this resource type.\\nRequestId:a1792d4d-8002-00f0-0763-edaf75000000\\nTime:2022-10-31T20:04:32.4606223Z\"}}}",
  "stack": "RestError: {\"odata.error\":{\"code\":\"AuthorizationResourceTypeMismatch\",\"message\":{\"lang\":\"en-US\",\"value\":\"This request is not authorized to perform this operation using this resource type.\\nRequestId:a1792d4d-8002-00f0-0763-edaf75000000\\nTime:2022-10-31T20:04:32.4606223Z\"}}}\n    at handleErrorResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-table-extension\\dist\\src\\index.js:2:246507)\n    at deserializeResponseBody (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-table-extension\\dist\\src\\index.js:2:247221)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)",
  "statusCode": 403,
  "request": {
    "url": "https://duckpinjson.table.core.windows.net/Tables?sv=2021-06-08&ss=bfqt&srt=s&sp=rwdlacupiyx&se=2022-11-01T04%3A03%3A10Z&st=2022-10-31T20%3A03%3A10Z&spr=https&SAS Token Redacted",
    "headers": {
      "accept": "application/json;odata=minimalmetadata",
      "x-ms-version": "2019-02-02",
      "dataserviceversion": "3.0",
      "accept-encoding": "gzip,deflate",
      "user-agent": "Microsoft Azure Storage Explorer/1.26.1 (win32) azsdk-js-data-tables/13.1.2 core-rest-pipeline/1.9.0 Node/v16.14.2 OS/(ia32-Windows_NT-10.0.19044)",
      "x-ms-client-request-id": "fa9b01c7-a6e7-44a5-a0a2-d7c537d64a9d"
    },
    "method": "GET",
    "timeout": 0,
    "disableKeepAlive": false,
    "streamResponseStatusCodes": {},
    "withCredentials": false,
    "tracingOptions": {
      "tracingContext": {
        "_contextMap": {}
      }
    },
    "requestId": "fa9b01c7-a6e7-44a5-a0a2-d7c537d64a9d",
    "allowInsecureConnection": true,
    "enableBrowserStreams": false
  },
  "response": {
    "status": 403,
    "headers": {
      "cache-control": "no-cache",
      "transfer-encoding": "chunked",
      "content-type": "application/json;odata=minimalmetadata;streaming=true;charset=utf-8",
      "server": "Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0",
      "x-ms-request-id": "a1792d4d-8002-00f0-0763-edaf75000000",
      "x-ms-client-request-id": "fa9b01c7-a6e7-44a5-a0a2-d7c537d64a9d",
      "x-ms-version": "2019-02-02",
      "x-content-type-options": "nosniff",
      "date": "Mon, 31 Oct 2022 20:04:31 GMT"
    },
    "request": {
      "url": "https://duckpinjson.table.core.windows.net/Tables?sv=2021-06-08&ss=bfqt&srt=s&sp=rwdlacupiyx&se=2022-11-01T04%3A03%3A10Z&st=2022-10-31T20%3A03%3A10Z&spr=https&SAS Token Redacted",
      "headers": {
        "accept": "application/json;odata=minimalmetadata",
        "x-ms-version": "2019-02-02",
        "dataserviceversion": "3.0",
        "accept-encoding": "gzip,deflate",
        "user-agent": "Microsoft Azure Storage Explorer/1.26.1 (win32) azsdk-js-data-tables/13.1.2 core-rest-pipeline/1.9.0 Node/v16.14.2 OS/(ia32-Windows_NT-10.0.19044)",
        "x-ms-client-request-id": "fa9b01c7-a6e7-44a5-a0a2-d7c537d64a9d"
      },
      "method": "GET",
      "timeout": 0,
      "disableKeepAlive": false,
      "streamResponseStatusCodes": {},
      "withCredentials": false,
      "tracingOptions": {
        "tracingContext": {
          "_contextMap": {}
        }
      },
      "requestId": "fa9b01c7-a6e7-44a5-a0a2-d7c537d64a9d",
      "allowInsecureConnection": true,
      "enableBrowserStreams": false
    },
    "bodyAsText": "{\"odata.error\":{\"code\":\"AuthorizationResourceTypeMismatch\",\"message\":{\"lang\":\"en-US\",\"value\":\"This request is not authorized to perform this operation using this resource type.\\nRequestId:a1792d4d-8002-00f0-0763-edaf75000000\\nTime:2022-10-31T20:04:32.4606223Z\"}}}",
    "parsedBody": {
      "odataError": {
        "code": "AuthorizationResourceTypeMismatch",
        "message": {
          "lang": "en-US",
          "value": "This request is not authorized to perform this operation using this resource type.\nRequestId:a1792d4d-8002-00f0-0763-edaf75000000\nTime:2022-10-31T20:04:32.4606223Z"
        }
      }
    },
    "parsedHeaders": {
      "cache-control": "no-cache",
      "transfer-encoding": "chunked",
      "content-type": "application/json;odata=minimalmetadata;streaming=true;charset=utf-8",
      "server": "Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0",
      "x-ms-request-id": "a1792d4d-8002-00f0-0763-edaf75000000",
      "x-ms-client-request-id": "fa9b01c7-a6e7-44a5-a0a2-d7c537d64a9d",
      "x-ms-version": "2019-02-02",
      "x-content-type-options": "nosniff",
      "date": "Mon, 31 Oct 2022 20:04:31 GMT"
    }
  },
  "details": {
    "cache-control": "no-cache",
    "transfer-encoding": "chunked",
    "content-type": "application/json;odata=minimalmetadata;streaming=true;charset=utf-8",
    "server": "Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0",
    "x-ms-request-id": "a1792d4d-8002-00f0-0763-edaf75000000",
    "x-ms-client-request-id": "fa9b01c7-a6e7-44a5-a0a2-d7c537d64a9d",
    "x-ms-version": "2019-02-02",
    "x-content-type-options": "nosniff",
    "date": "Mon, 31 Oct 2022 20:04:31 GMT",
    "odataError": {
      "code": "AuthorizationResourceTypeMismatch",
      "message": {
        "lang": "en-US",
        "value": "This request is not authorized to perform this operation using this resource type.\nRequestId:a1792d4d-8002-00f0-0763-edaf75000000\nTime:2022-10-31T20:04:32.4606223Z"
      }
    }
  }
}
![Picture2](https://user-images.githubusercontent.com/1431998/199101467-e6323add-c104-41a3-bef0-b4aba123c000.png)

**Comment by cliffeby** [comment]
And when i try to access data in the Blob Containers, I get the following.  Data exist in both containers.

![Picture3](https://user-images.githubusercontent.com/1431998/199102038-7e49ed53-98d1-461b-b897-e9c079d220bc.png)

**Comment by JasonYeMSFT** [comment]
@cliffeby Your account SAS needs to have both container and object resource types to be able to access data in your table/blob container. It is the `srt` parameter in your current sas token. Instead of being "s", it should be "sco". Please regenerate the SAS token with the correct resource type and attach again.

"sv=2021-06-08&ss=bfqt&srt=s&sp=rwdlacupiyx&se=2022-11-01T04%3A03%3A10Z&st=2022-10-31T20%3A03%3A10Z&spr=https"

**Comment by cliffeby** [comment]
The **srt** parameter equal to **sco** allowed me to connect to the table but not the way I expected.  I had to use the Blob Service SASURL.  It attached a **duckpinjson-1 (SAS)** dropdown entity.  The resulting MASE pindata screenshot is shown.  Thank you.

When I tried to use the Table SASURL, I got the error shown in the second figure below.  If the expired credentials in this table present a risk, please advise.
![MASEpindata](https://user-images.githubusercontent.com/1431998/200412567-077adf73-0ddb-4569-9852-0c0d8629dfe9.png)
![tableSASURL](https://user-images.githubusercontent.com/1431998/200412598-6a526949-bc1d-4bc1-8c45-830a805929e2.png)

**Comment by JasonYeMSFT** [comment]
@cliffeby Technically speaking the expired credential won't present any risk but it is a good practice to not revealing any credential at all. The dialog you saw in the 2nd screenshot is for connecting to a Table which requires the url to specific which table to connect to (e.g. `https://acct.table.core.windows.net/<table_name>`). What you did in the first screenshot is to connect to the parent storage account containing the table you want to access, which works in your case because your credential is actually an account level SAS.

**Comment by cliffeby** [comment]
Thanks for the help. Seems more difficult than most Azure interfaces. 

Sent from my phone. 


On Nov 14, 2022, at 1:17 PM, JasonYeMSFT ***@***.***> wrote:

﻿
@cliffeby Technically speaking the expired credential won't present any risk but it is a good practice to not revealing any credential at all. The dialog you saw in the 2nd screenshot is for connecting to a Table which requires the url to specific which table to connect to (e.g. https://acct.table.core.windows.net/<table_name>). What you did in the first screenshot is to connect to the parent storage account containing the table you want to access, which works in your case because your credential is actually an account level SAS.
