### ISSUE TITLE
Cannot connect blob from MS storage explorer

### ISSUE THREAD

**Issue by yargolan** [microsoft/AzureStorageExplorer#6204]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

 1.26.1

### Architecture

x64

### Storage Explorer Build Number

20221018.5

### Platform

macOS

### OS Version

macOS Monterey 12.6

### Bug Description

- I am an admin of the account
- My CIDR exists in the Networking/Firewall section

### Steps to Reproduce

1. Launch the storage explorer
2. go to relevant storage account under the subscription's name
3. try to browse blobs

### Actual Experience

The following error message pops out:

This request is not authorized to perform this operation.

This storage account's 'Firewalls & virtual networks' settings may be blocking access to storage services. Try adding your client IP address to the firewall exceptions, or by allowing access from 'all networks' instead of 'selected networks'. To learn more about Azure Storage firewalls and virtual networks, visit http://go.microsoft.com/fwlink/?LinkId=845443.

Error Details:
{
  "name": "RestError",
  "code": "AuthorizationFailure",
  "statusCode": 403,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://da***att.blob.core.windows.net/?comp=list&include=metadata",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2021-08-06"
        },
        "accept": {
          "name": "Accept",
          "value": "application/xml"
        },
        "user-agent": {
          "name": "User-Agent",
          "value": "Microsoft Azure Storage Explorer/1.26.1 (darwin) azsdk-js-storageblob/12.11.0 (NODE-VERSION v16.14.2; Darwin 21.6.0)"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "1009da41-90c1-42ed-85b1-36e1dc564f8e"
        },
        "authorization": {
          "name": "authorization",
          "value": "Bearer JSON Web Token Redacted"
        },
        "cookie": {
          "name": "Cookie",
          "value": ""
        }
      }
    },
    "withCredentials": false,
    "timeout": 0,
    "keepAlive": true,
    "decompressResponse": false,
    "requestId": "1009da41-90c1-42ed-85b1-36e1dc564f8e"
  },
  "response": {
    "headers": {
      "_headersMap": {
        "content-length": {
          "name": "content-length",
          "value": "246"
        },
        "content-type": {
          "name": "content-type",
          "value": "application/xml"
        },
        "date": {
          "name": "date",
          "value": "Sun, 23 Oct 2022 13:45:33 GMT"
        },
        "server": {
          "name": "server",
          "value": "Microsoft-HTTPAPI/2.0"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "1009da41-90c1-42ed-85b1-36e1dc564f8e"
        },
        "x-ms-error-code": {
          "name": "x-ms-error-code",
          "value": "AuthorizationFailure"
        },
        "x-ms-request-id": {
          "name": "x-ms-request-id",
          "value": "7d9d9d7e-a01e-0013-5ae5-e6a4a8000000"
        }
      }
    },
    "request": {
      "streamResponseStatusCodes": {},
      "url": "https://da***att.blob.core.windows.net/?comp=list&include=metadata",
      "method": "GET",
      "headers": {
        "_headersMap": {
          "x-ms-version": {
            "name": "x-ms-version",
            "value": "2021-08-06"
          },
          "accept": {
            "name": "Accept",
            "value": "application/xml"
          },
          "user-agent": {
            "name": "User-Agent",
            "value": "Microsoft Azure Storage Explorer/1.26.1 (darwin) azsdk-js-storageblob/12.11.0 (NODE-VERSION v16.14.2; Darwin 21.6.0)"
          },
          "x-ms-client-request-id": {
            "name": "x-ms-client-request-id",
            "value": "1009da41-90c1-42ed-85b1-36e1dc564f8e"
          },
          "authorization": {
            "name": "authorization",
            "value": "Bearer JSON Web Token Redacted"
          },
          "cookie": {
            "name": "Cookie",
            "value": ""
          }
        }
      },
      "withCredentials": false,
      "timeout": 0,
      "keepAlive": true,
      "decompressResponse": false,
      "requestId": "1009da41-90c1-42ed-85b1-36e1dc564f8e"
    },
    "status": 403,
    "bodyAsText": "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.\nRequestId:7d9d9d7e-a01e-0013-5ae5-e6a4a8000000\nTime:2022-10-23T13:45:33.6176173Z</Message></Error>",
    "parsedBody": {
      "message": "This request is not authorized to perform this operation.\nRequestId:7d9d9d7e-a01e-0013-5ae5-e6a4a8000000\nTime:2022-10-23T13:45:33.6176173Z",
      "code": "AuthorizationFailure"
    },
    "parsedHeaders": {
      "errorCode": "AuthorizationFailure",
      "content-length": "246",
      "content-type": "application/xml",
      "date": "Sun, 23 Oct 2022 13:45:33 GMT",
      "server": "Microsoft-HTTPAPI/2.0",
      "x-ms-client-request-id": "1009da41-90c1-42ed-85b1-36e1dc564f8e",
      "x-ms-request-id": "7d9d9d7e-a01e-0013-5ae5-e6a4a8000000"
    }
  },
  "details": {
    "errorCode": "AuthorizationFailure",
    "content-length": "246",
    "content-type": "application/xml",
    "date": "Sun, 23 Oct 2022 13:45:33 GMT",
    "server": "Microsoft-HTTPAPI/2.0",
    "x-ms-client-request-id": "1009da41-90c1-42ed-85b1-36e1dc564f8e",
    "x-ms-request-id": "7d9d9d7e-a01e-0013-5ae5-e6a4a8000000",
    "message": "This request is not authorized to perform this operation.\nRequestId:7d9d9d7e-a01e-0013-5ae5-e6a4a8000000\nTime:2022-10-23T13:45:33.6176173Z",
    "code": "AuthorizationFailure"
  }
}

### Expected Experience

The blob is browsable and I can see the sub folders

**Comment by MRayermannMSFT** [comment]
@yargolan did you try any of recommendations from the message at the beginning of the error info?

**Comment by yargolan** [comment]
Sure,
I checked that my CIDR is in the range of allowed IP addresses

When looking at the issue again, i've noticed that the storage account was
established in a different region that all the other resources are located
at.
Creating a new storage account in the "right" region, allowed me to connect
to the blobs from the explorer

I am considering to cancel the ticket
