### ISSUE TITLE
There is an extra '…' next to the Download action on the toolbar for one ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6207]
**Storage Explorer Version:** 1.27.0-dev
**Build Number:** 20221025.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.6 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.26.1)

## Steps to Reproduce ##

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Open one blob container -> Observe the toolbar.
3. Check there is no '...' next to the 'Download' action.

## Expected Experience ##
There is no '...' next to the 'Download' action.

## Actual Experience ##
There is a '...' next to the 'Download' action.
![image](https://user-images.githubusercontent.com/87792676/197729546-39c3b24e-e1c0-401a-b0fc-096595a53ec6.png)

**Comment by v-xianya** [comment]
Verified this issue on the build 20221027.6. Fixed. So, we are going to close it.
![image](https://user-images.githubusercontent.com/41351993/198180669-092e31d7-cb0f-42c9-8160-0834909edf9d.png)
