### ISSUE TITLE
It is better to add 'Tables' in the description of the setting 'Auto-refresh on change'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6208]
**Storage Explorer Version**: 1.27.0-dev
**Build Number**: 20221025.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.6 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Open 'Settings -> Data Explorers'.
2. Uncheck the setting 'Auto-refresh on change'.
3. Expand one storage account -> Tables.
4. Create a table -> Try to add one entity.
5. There is a refresh prompt.
![image](https://user-images.githubusercontent.com/41351993/197739572-31f0f88b-b696-4f28-bad8-1f54d4680324.png)
6. Observe the setting 'Auto-refresh on change' description.
7. Check whether 'tables' is added in the description.

## Expected Experience ##
Tables is added in the description.

## Actual Experience ##
Tables is not added in the description.
![image](https://user-images.githubusercontent.com/41351993/197740055-2dec2600-d61c-4546-981c-401ed0b6c60e.png)

**Comment by MRayermannMSFT** [comment]
Get rid of calling out specific explorers in the description. At this point in time all data explorers should respect this setting.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20221104.1:
1. The setting 'Auto-refresh on change' description has been updated:
![image](https://user-images.githubusercontent.com/87792676/199930556-dc07b17c-1e46-49a8-bd25-97064e51cda0.png)
2. Queues doesn't match this setting currently, and there is a related bug: [3430](https://github.com/microsoft/AzureStorageExplorer/issues/3430).

**Comment by v-kellyluo** [comment]
Updates: On the build 20221104.1:
1. The setting 'Auto-refresh on change' description has been updated:
![image](https://user-images.githubusercontent.com/87792676/199930556-dc07b17c-1e46-49a8-bd25-97064e51cda0.png)
2. Queues doesn't match this setting currently, and there is a related bug: [3430](https://github.com/microsoft/AzureStorageExplorer/issues/3430).

**Comment by richardMSFT** [comment]
This should be closed now that the description removed any specific service/explorer in the description. The related bug [3430](https://github.com/microsoft/AzureStorageExplorer/issues/3430) should reflect the current description as well.
