### ISSUE TITLE
Count query with high count result return quickly with 0

### ISSUE THREAD

**Issue by thesourcerer** [microsoft/AzureStorageExplorer#621]
**Storage Explorer Version**: 1.4.1
**Platform/OS Version**: Windows 10
**Architecture**: ia32
**Regression From**:not sure

#### Steps to Reproduce: ####
running a count query on a collection style of:
SELECT VALUE count(1) FROM c WHERE ARRAY_CONTAINS(c.Types , "Group")
 on a small collection (few 100s of documents) we get a real result.
in a case where the result should be > 501000, the query that should be relatively slow returns alsmost immediately with 0.

Running the same query on the same collection from azure portal gives the correct number after runnign for a few minutes.

#### Expected Experience: ####
Get the correct result (or if reached some limit, get an error)

#### Actual Experience: ####
got a false result of 0.

**Comment by craxal** [comment]
Just to clarify, are you working with a CosmosDB account?

**Comment by thesourcerer** [comment]
I have many accounts and databases, I log in using my AAD credentials.
This specific test was done on a specific DB in a specific account, but when I checked I noticed it happens in other DBs as well.

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
