### ISSUE TITLE
File browser opens to the most recently download directory when downloading disks/exporting entities after executing 'set the default download directory -> download to a different directory -> set the default download directory again'

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6210]
**Storage Explorer Version:** 1.27.0-dev
**Build Number:** 20221025.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.6 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Open Settings -> Transfers -> Default Download Direction -> Type a valid path in the textbox.
2. Open one table -> Add some entities -> Click 'Export'.
3. File browser opens to the default download directory.
4. Select a different directory -> Click 'Save'.
5. Set the same default download directory as the Step3.
6. Open one table -> Click 'Export'.
7. Check whether File browser opens to the default download directory.

## Expected Experience ##
File browser opens to the default download directory.

## Actual Experience ##
File browser opens to the most recently download directory.

## Additional Context ##

1. This issue also reproduces for disks.
2. This issue doesn't reproduce for blob containers/file shares.

**Comment by richardMSFT** [comment]
Hey @v-kellyluo I haven't been able to reproduce the experience you describe even after downloading the build number and going through the same steps. Can you share a VM with the reproduction?

**Comment by v-kellyluo** [comment]
@richardMSFT, OK, I will share the VM on teams🙂.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20221104.1. Fixed.
For all 4 services, file browser opens to the most recently download directory if users set the same value default location in the second time.
