### ISSUE TITLE
Recent update has File Upload Browse Dialog made with library not aware of high DPI screen scaling.

### ISSUE THREAD

**Issue by RannyMeier** [microsoft/AzureStorageExplorer#6211]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.26.1

### Architecture

x64

### Storage Explorer Build Number

20221018.5

### Platform

Windows

### OS Version

Windows Server 2019

### Bug Description

![AzureStorageExplorerBrowse](https://user-images.githubusercontent.com/16782303/197920756-b68e2d7b-1d11-4e00-8c6d-bbbed399ff32.png)
For a long while previously the File Upload Browse dialog was scaled as expected.
We connect to an Azure VM running Windows Server 2019 using MSTSC.  Azure Storage Explorer had run fine on for a long while until most recently in the last week or so.  Suddenly the File Explorer control referenced in the File Browse window is such that is not aware of high DPI screen scaling.  This is like the MSTSC used to see when connecting to Windows Server 2012 for example.  Then with Windows 10 and Windows Server 2019 the scaling seemed to work well.  The Storage Explorer is not user friendly for us now as most all of our laptop computers now have high DPI screens.

### Steps to Reproduce

Connect from high DPI screen using MSTSC to an Azure VM running Windows Server 2019.
Start Azure Storage Explorer.
Attempt to Upload a file and notice that the File Explorer control that is used in the File Browse window is not scaled correctly.

### Actual Experience

The File Explorer control that is used in the File Browse window is not scaled and appears to tiny small to see.

**Comment by MRayermannMSFT** [comment]
@RannyMeier can you reinstall an older Storage Explorer to help confirm this is a regression in Storage Explorer and not MSTSC?

You can find old versions here: https://github.com/Microsoft/AzureStorageExplorer/releases

**Comment by MRayermannMSFT** [comment]
@RannyMeier ?

**Comment by RannyMeier** [comment]
The issue with the Windows Explorer file select dialog scale on high DPI screen is no longer happening with the latest Azure Storage Explorer version 1.26.1.   I noticed that the issue has stopped about a week ago.  Should try earlier version before 1.25 anyway?

**Comment by MRayermannMSFT** [comment]
No. I think if the issue has gone away then we can go ahead and say what you saw was probably due to something other than Storage Explorer. However, if you do see the behavior again, please feel free to open a new issue, and let us know if the behavior only reproduces with latest or Storage Explorer, or, latest and some set of old versions.
