### ISSUE TITLE
File Previewing, missing file formats (Version 1.26.1)

### ISSUE THREAD

**Issue by BastiaanA** [microsoft/AzureStorageExplorer#6212]
File previewing is a great feature.

But File Previewing does not work for:
- csv
- file names without extensions

October 2022 (Version 1.26.1)

**Comment by JasonYeMSFT** [comment]
We fixed a bug to enable previewing files without extensions by adding value "" to the allowed file extension list. We will also enable the preview action if the blob/file has a few well-known text content type (e.g. text/csv).
