### ISSUE TITLE
Can't empty the characters in the field on the settings panel

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6214]
**Storage Explorer Version**: 1.27.0-dev
**Build Number**: 20221026.5
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.6 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.26.1)

## Steps to Reproduce ##
1. Launch Storage Explorer -> Open the settings panel.
2. Click 'Application' -> Go to 'Proxy -> Port' -> Type numbers into the Port field if it is empty.
3. Empty the numbers in the Port field.
4. Check whether succeeds to empty the field.

## Expected Experience ##
Succeed to empty the field.

## Actual Experience ##
Can't empty the filed.
Here is the record:
![1026](https://user-images.githubusercontent.com/41351993/197969062-505a0af8-1026-4b39-b4db-384bc6a585be.gif)

**Comment by v-xianya** [comment]
Hi @JasonYeMSFT Verified this issue on the latest build 20221027.6.
The deleted number or string will show back if press tab or click other places on the settings panel.


![6214](https://user-images.githubusercontent.com/41351993/198182969-a8273fd4-f005-4429-8826-f5c444c89b25.gif)

**Comment by JasonYeMSFT** [comment]
@v-xianya This is the intended behavior. If the focus goes out of the text box, the actual value of the setting will be displayed. This also applies to string settings and string array settings.
