### ISSUE TITLE
There is an extra scroll bar in the localized 'Shared Access Signature' dialog for one table on Japanese

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6219]
**Storage Explorer Version**: 1.27.0-dev
**Build Number**: 20221027.6
**Branch**: main
**Platform/OS**: Windows 10
**Reproduce Languages**: Japanese
**Architecture**: ia32
**How Found**: From running test cases
**Regression From**: Previous release (1.25.1)

## Steps to Reproduce ##
1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select '日本語' -> Restart Storage Explorer.
3. Expand one storage account -> Tables.
4. Right click one table -> Click the localized 'Get Shared Access Signature...'.
5. Check there is no extra scroll bar on the dialog.

## Expected Experience ##
There is no extra scroll bar on the dialog.

## Actual Experience ##
There is an extra scroll bar on the dialog.
![image](https://user-images.githubusercontent.com/41351993/198231917-bf6b9d6b-50a6-460e-a7bf-172e5f04ef32.png)

**Comment by richardMSFT** [comment]
Fixed. Shipping with 1.27.0

**Comment by v-xianya** [comment]
Verified this issue on the build main 20221203.4. Fixed.
