### ISSUE TITLE
Window not shown on Mac High Sierra

### ISSUE THREAD

**Issue by tilumi** [microsoft/AzureStorageExplorer#622]
**Storage Explorer Version**: 1.4.1
**Platform/OS Version**: Mac OS High Sierra 10.13.6
**Architecture**: 
**Regression From**: 

#### Steps to Reproduce: ####
1. Launch the Explorer

#### Expected Experience: ####
Show window

#### Actual Experience: ####
Nothing happens, only the icon on my dock.
Few minutes later, the error shows:
![screenshot 2018-08-31 04 28 11](https://user-images.githubusercontent.com/734766/44877426-85a59400-acd6-11e8-8709-5b0d2eae5627.png)

**Comment by MRayermannMSFT** [comment]
@tilumi since both the version of Storage Explorer and the version of macOS you were using are now fairly old, we have a feeling this doesn't repro anymore. If you're still having problems though, please open a new issue. Thanks.
