### ISSUE TITLE
The download menu actions are not localized under one blob container explorer

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6222]
**Storage Explorer Version:** 1.27.0-dev
**Build Number:** 20221027.6
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.6 (Apple M1 Pro)
**Reproduce Languages:** Czech/German/Hungarian/Japanese/Portuguese (Portugal)/zh-TW
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select '日本語' -> Restart Storage Explorer.
3. Expand one storage account -> Blob Containers.
4. Open one blob container which contains items.
5. Click download arrow on the toolbar.
6. Check whether the menu actions are localized.

## Expected Experience ##
The menu actions are localized.

## Actual Experience ##
The menu actions are not localized.
![image](https://user-images.githubusercontent.com/87792676/198248260-1143db9b-2e8c-4d5d-a9d2-55e3d56e3610.png)

## Additional Context ##
1. The 'Download All...' action is not localized on the context menu.
![image](https://user-images.githubusercontent.com/87792676/198249427-e5755f13-3591-42b6-9474-5c5b1470c1b5.png)
2. The 'Download' action and the menu actions are not localized in one file share.
![image](https://user-images.githubusercontent.com/87792676/198248649-bc87134c-9a59-4293-8995-2d16ced9176c.png)

**Comment by JasonYeMSFT** [comment]
This string is translated now.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20221111.1:

1. The download menu actions and the context menu **are localized** under one blob container explorer.
2. The 'Download' action and the menu actions are **not localized** in one file share:

![image](https://user-images.githubusercontent.com/87792676/201278039-67a8c8db-ead1-406f-a502-ebb944c3bf1d.png)

3. The 'Download' action and 'Download All' action are **not localized** on the context menu in one file share:
![image](https://user-images.githubusercontent.com/87792676/201278131-7f711043-37f2-4476-b343-df08bdab1e8b.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20221111.1:
1. This issue has been fixed under one blob container explorer.
2. The 'Download' action and the menu actions are **not localized** in one file share:

![image](https://user-images.githubusercontent.com/87792676/201278039-67a8c8db-ead1-406f-a502-ebb944c3bf1d.png)

3. The 'Download' action and 'Download All' action are **not localized** on the context menu in one file share:
![image](https://user-images.githubusercontent.com/87792676/201278131-7f711043-37f2-4476-b343-df08bdab1e8b.png)

**Comment by v-xianya** [comment]
Verified this issue on the build main 20221203.4. Fixed.
