### ISSUE TITLE
It is better to add the cue message "does not include blobs in deleted folders" next to the active blob's statistic line

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6224]
**Storage Explorer Version**: 1.27.0-dev
**Build Number**: 20221028.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.6 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Create a folder -> Upload one blob to the folder.
3. Soft delete the folder -> Click 'Folder Statistics'.
4. Observe the activity log.

## Expected Experience ##
It is better to add the cue message (does not include blobs in deleted folders) next to the active blob's statistic line.

## Actual Experience ##
There is no cue message next to the active blob's statistic line.
![image](https://user-images.githubusercontent.com/41351993/198547204-15a5388a-8c4b-4372-8a96-a7d063e22b57.png)

**Comment by MRayermannMSFT** [comment]
We're going to leave the hints/cues as is. Will get customer feedback on them. See [other bug](https://github.com/microsoft/AzureStorageExplorer/issues/6226) for more information.
