### ISSUE TITLE
Adding Create and Add permissions for Acess Policy

### ISSUE THREAD

**Issue by shraboin** [microsoft/AzureStorageExplorer#623]
**Storage Explorer Version**: 1.4.1
**Platform/OS Version**: Windows 10

Issue with creating SAS that uses a Access Policy. In the portal when you create a Access Policy it gives the following permissions:

1. read
2. write
3. list
4. delete
5. create 
6. add

However in ASE it omits Create & Add:

1. read 
2. write 
3. list 
4. delete
 
Is there anyway we can add Create & Add on the container level?

**Comment by craxal** [comment]
It's likely these kinds of permissions are new, so we just haven't added them in yet. What kind of service are we talking about? Blobs, Files, Queues, or Tables?

**Comment by ghills** [comment]
I ran into this as well. For me it was in regards to the Blob service as I was trying to create a managed access policy that only allowed creation.

**Comment by MRayermannMSFT** [comment]
This was done at some point. Create and Add are available both when generating a sas and when managing access policies.
