### ISSUE TITLE
There are soft deleted blobs in the ADLS Gen2 blob containers (Soft delete blobs -> Switch to the view 'Active and soft deleted blobs/Deleted only' -> Disable the setting 'Enable ADLS Gen2 soft delete (Preview)' -> Restart Storage Explorer)

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6230]
**Storage Explorer Version**: 1.27.0-dev
**Build Number**: 20221030.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.0 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Ad-hoc testing
**Regression From**: Previous release (1.24.3)

## Steps to Reproduce ##
1. Launch Storage Explorer -> Enable the setting 'Enable ADLS Gen2 soft delete (Preview)' -> Restart Storage Explorer.
2. Expand one ADLS Gen2 storage account -> Blob Containers.
3. Create a blob container -> Upload one blob.
4. Soft delete the blob -> Switch to the context view 'Active and soft deleted blobs'.
5. There is the soft-deleted blob.
6. Open Settings -> Disable the setting 'Enable ADLS Gen2 soft delete (Preview)' -> Restart Storage Explorer.
7. Check there is no soft-deleted blob in the ADLS Gen2 blob container.

## Expected Experience ##
There is no soft-deleted blob.

## Actual Experience ##
There is a soft-deleted blob.
![image](https://user-images.githubusercontent.com/41351993/198948691-7c53863a-96c9-47b5-acf6-9c1dbc01c62c.png)

**Comment by MRayermannMSFT** [comment]
Good bug find, but too much of an edge case to be worth fixing at this time. Won't fix.
