### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by mktrem** [microsoft/AzureStorageExplorer#6232]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.26.1

### Architecture

x64

### Storage Explorer Build Number

20221018.5

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Every time I start MS Azure File Explorer I get a message indicating "Unable to retrieve child resources".
![Screenshot 2022-10-31 085425](https://user-images.githubusercontent.com/117088503/199013168-b6c6c3b5-c594-4bc0-8997-ebc46a11c1fb.png)

### Steps to Reproduce

1. Launch Explorer

### Actual Experience

Every time I start MS Azure File Explorer I get the attached error message regarding "Unable to retrieve child resources". I have since installed the latest update and the same message persists.  No functionality seems to be missing. I clear the message and can process successfully.

**Comment by shubhisethi** [comment]
I am having the same issue too.

**Comment by MRayermannMSFT** [comment]
@mktrem @shubhisethi can y'all tell us:

1. How are you connecting to your storage resources? Have you signed in and are listing resources under a subscription? Are you attaching a specific resource/s, and if so, how are you authenticating the attachment (SAS, account key, Azure AD)?
2. At what point in the resource tree are you seeing this error? Immediately?
3. Can you:
   1. Go to Settings (gear on the left) > Application > Logging > Log Level, and choose "Debug" in the dropdown
   2. Restart Storage Explorer
   3. Reproduce the error
   4. Once it reproduces, close the error dialog
   5. Go to Help > Open Logs Directory
   6. In the file explorer window, go to the newest folder
   7. Zip up all the files
   8. Upload the zip here

Thanks!

**Comment by mktrem** [comment]
1. My guess would be Azure AD because I don't "log in". I just click on the MS Azure Storage Explorer icon on my task bar... and I'm in.
2. Immediately
3.
[2022-10-31_131456.zip](https://github.com/microsoft/AzureStorageExplorer/files/9903408/2022-10-31_131456.zip)

**Comment by shubhisethi** [comment]
It's working for me, I just detached and reattached the container back.

**Comment by mktrem** [comment]
I just came into this issue to update it that I am no longer having this problem.
I just don't know why it says I closed the issue.  Perhaps I did it by accident.
