### ISSUE TITLE
The soft deleted ADLS Gen2 blobs are treated as active blobs when running 'Selection Statistics' if an active blob with the same name exists

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6233]
**Storage Explorer Version**: 1.27.0-dev
**Build Number**: 20221101.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.0 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Open one blob container -> Upload one blob then soft delete it.
3.  Upload the same blob -> Switch to the context view 'Active and soft deleted blobs'.
4. Right click the soft deleted blob -> Click 'Selection Statistics'.
5. Observe the activity log.
6. Check whether shows 1 deleted blob in the activity log.

## Expected Experience ##
Show 1 deleted blob in the activity log.

## Actual Experience ##
Show 1 active blob in the activity log.
![image](https://user-images.githubusercontent.com/41351993/199176930-8d6332e0-1813-4225-817b-490f0739ea62.png)

## Additional Context ##
1. This issue also reproduces under 'Deleted only' context view.
2. This issue does not reproduce for 'Folder Statistics'.
3. This issue does not reproduce when running 'Selection Statistics' on the directory level.

**Comment by MRayermannMSFT** [comment]
Fix merged into main.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20221102.1. Fixed.
