### ISSUE TITLE
The address bar is empty when the cursor focuses on the address bar if opening a folder in one file share

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6234]
**Storage Explorer Version:** 1.27.0-dev
**Build Number:** 20221101.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.0 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.26.1)

## Steps to Reproduce ##

1. Expand one storage account -> File Shares.
2. Create a file share -> Create a folder.
3. Open the folder -> Make the cursor focus on the address bar.
4. Check whether the folder name displays in the address bar.

## Expected Experience ##
The folder name displays in the address bar.
![image](https://user-images.githubusercontent.com/87792676/199181863-4c4acfe8-ec36-494f-9f59-14b79007b78f.png)

## Actual Experience ##
The address bar is empty.
![image](https://user-images.githubusercontent.com/87792676/199182040-eed39499-631e-470f-ace3-8514d907296e.png)

## Additional Context ##
This issue doesn't reproduce for blob containers.

**Comment by JasonYeMSFT** [comment]
We merged a new implementation of the Address Bar. It is currently only applied to File Explorer but I will apply it to ADLS Gen2 Explorer as well.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20221103.3. Fixed. So, we are going to close it.
