### ISSUE TITLE
The 'Preview' action is enabled for one .csv blob if there is no '.csv' extension in the 'Text preview extensions' field

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6235]
**Storage Explorer Version:** 1.27.0-dev
**Build Number:** 20221101.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.0 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.26.1)

## Steps to Reproduce ##

1. Open Settings -> Service -> Text preview extensions.
2. Make sure there is no '.csv' extension in the field.
3. Expand one storage account -> Blob Containers.
4. Open one blob container -> Upload a .csv blob -> Right click the blob.
5. Check whether the 'Preview' action is disabled.

## Expected Experience ##
The 'Preview' action is disabled.
![image](https://user-images.githubusercontent.com/87792676/199183359-b87e7095-5691-45be-a7cd-1bb240dadfde.png)

## Actual Experience ##
The 'Preview' action is enabled.
![image](https://user-images.githubusercontent.com/87792676/199183133-1b964e17-b175-4656-9cd6-0bcea053a459.png)

## Additional Context ##
This issue doesn't reproduce for file shares.

**Comment by JasonYeMSFT** [comment]
Due to https://github.com/microsoft/AzureStorageExplorer/issues/6166, the Preview action will now be enabled if the content type is a common text/* content type. If the blob in this issue has content type text/csv, this is by design.

**Comment by v-kellyluo** [comment]
@JasonYeMSFT , the 'Preview' button is disabled in one file share even though the content type is a common text/* content type, which is different from the blob container, is this by design?
![image](https://user-images.githubusercontent.com/87792676/215443821-9fbb5b3c-25eb-4fd9-8e18-6d63e3f15abf.png)
