### ISSUE TITLE
The results of the current selection statistics by selecting all and folder statistics are inconsistent if there are one deleted blob and its soft deleted parent folder under the 'Deleted only' context view

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6236]
**Storage Explorer Version**: 1.27.0-dev
**Build Number**: 20221101.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.0 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Open one blob container -> Create a folder -> Upload one blob to the folder.
3. Soft delete the blob -> Soft delete the folder.
4. Switch to 'Deleted only' context view.
5. Select all items -> Right click them -> Click 'Selection Statistics'.
6. Observe the activity log.
7. Click 'Folder Statistics' -> Observe the activity log.
8. Check the statistical results are consistent.

## Expected Experience ##
The statistical results are consistent.

## Actual Experience ##
The statistical results are inconsistent.
![image](https://user-images.githubusercontent.com/41351993/199184924-f33bad04-a894-4094-a1dd-2ab439d0a53f.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into main.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20221102.1.
![image](https://user-images.githubusercontent.com/41351993/199377231-d14718cd-d090-4fc8-a30c-3c830bbf9edd.png)
