### ISSUE TITLE
Soft deleted blob versions count as deleted blobs while soft deleted blob snapshots count as snapshots

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6237]
**Storage Explorer Version**: 1.27.0-dev
**Build Number**: 20221101.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.0 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers. (Blob versioning and soft delete are both enabled).
2. Create a blob container -> Upload one blob -> Create a snapshot.
3. Go to the snapshots view -> Soft delete the blob snapshot.
4. Switch to the 'Active and soft deleted blobs' context view -> Right click the soft deleted blob snapshot.
5. Click 'Selection Statistics' -> Observe the activity log.
![image](https://user-images.githubusercontent.com/41351993/199195609-8b25fc63-17dd-4d2e-bb4a-9f50238e1b37.png)

6. Go to the versions view -> Soft delete the blob version.
7. Switch to the 'Active and soft deleted blobs' context view -> Right click the soft deleted blob version.
8. Click 'Selection Statistics' -> Observe the activity log.
![image](https://user-images.githubusercontent.com/41351993/199195835-e2c9d204-33f4-40eb-9faf-59abc580da3e.png)
9. Check whether the soft deleted blob snapshots and the soft deleted blob version keep the same count mechanism.

## Expected Experience ##
Keep the same count mechanism.

## Actual Experience ##
The count mechanisms are different.

1. Soft deleted blob versions count as deleted blobs.
2. Soft deleted blob snapshots count as snapshots.

**Comment by MRayermannMSFT** [comment]
Fix merged into main.

**Comment by v-xianya** [comment]
Verified this issue on the build 20221102.1. Fixed.
Soft deleted version and snapshot are both count as soft deleted blobs.
