### ISSUE TITLE
The QA service tab is not closed after renaming it

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6238]
**Storage Explorer Version:** 1.27.0-dev
**Build Number:** 20221101.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.0 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Pin it to Quick Access.
3. Open the QA blob container.
4. Right click the QA blob container -> Click 'Rename ...'.
5. Type a valid name -> Click "Rename'.
6. Check whether the QA blob container tab is closed.

## Expected Experience ##
The QA blob container tab is closed.

## Actual Experience ##
The QA blob container tab is not closed.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20221113.2. Reproduce.
So, we are going to re-open it, will verify on a newer build and close it once it fixed.

**Comment by JasonYeMSFT** [comment]
By switching to use resourceUID, the node-tab association will be preserved after renaming so we don't need to close the tab. The tooltip of the tab (nodePath) will be incorrect but that's a minor issue at this point so we will address it later.

**Comment by JasonYeMSFT** [comment]
We will leave the tabs open after renaming quick access items.
