### ISSUE TITLE
propose that a json format "text" preview be added

### ISSUE THREAD

**Issue by lbilodeau** [microsoft/AzureStorageExplorer#6240]
Concerning Storage explorer's preview feature It would be nice if the file has a json suffix it tries to display the file in formatted JSON, preferable with collapsible nodes.

**Comment by JasonYeMSFT** [comment]
This is a duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/6195. We will consider the capability to toggle between original content and formatted JSON in the preview editor.
