### ISSUE TITLE
The 'Preview' action is disabled under the tag query mode for one blob with file extension .csv/.png

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6241]
**Storage Explorer Version**: 1.27.0-dev
**Build Number**: 20221102.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.0 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account ->Blob Containers.
2. Create a blob container -> Upload a blob with .csv file extension.
3. Right click the blob -> The action 'Preview' is enabled.
4. Add one tag for the blob -> Apply the tag to query.
5. Right click the blob under the tag query mode.
6. Check whether the action 'Preview' is enabled or not.

## Expected Experience ##
The action 'Preview' is enabled.

## Actual Experience ##
The action 'Preview' is disabled.
![image](https://user-images.githubusercontent.com/41351993/199423856-6d8770b2-e60f-407b-ac0e-e2a5cdd042db.png)

## Additional Context ##
 This issue does not reproduce for file extensions “.txt”, “.js”, “.html”, “.json”, “.avif”, “.bmp”, “.gif”, “.ico”, “.jpeg”, “.jpg”, “.svg”, “.webp”.

**Comment by MRayermannMSFT** [comment]
@v-xianya two things:
1. I cannot not repro this with a .png blob. Is the file extension of the blob you are using to repro is .PNG or .png?
2. Ignoring the .png case, this is unfortunately expected. There are two criteria we use to determine if we can preview a blob. A blob must meet one of these criteria for preview to be enabled:
   1.  Does the blob have a file extension that we support for preview? For text previewing, supported extensions come from the setting, for image previewing it is a hardcoded list of file extensions.
   2. Does the blob have a content type that we support for preview? For both text previewing and image previewing it is a hardcoded list of content types.
   
   But, when filtering blobs by tag, we do not have access to the blobs content type via listing. Thus, we are effectively only checking criteria 1 (is the file extension supported). So for text previewing, the blob's file extension must be in the setting, and for image previewing the blob's file extension must be in our hard coded list.

A note on the file extension checking: I noticed that we aren't doing a case insensitive comparison check of file extensions. So if the png blob you are testing with has an extension like .PNG then the check for criteria number 1 will always fail. I will fix this today.

**Comment by v-xianya** [comment]
@MRayermannMSFT Thank you for the details
1. I reproduced the issue on .PNG. In the latest main build 20221103.3. This issue doesn't reproduce.
2. This issue doesn't reproduce when adding the .csv to the setting 'Text preview extensions'. 
So, we are going to close it.
