### ISSUE TITLE
The toolbar actions can't be collapsed for one file share

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6242]
**Storage Explorer Version**: 1.27.0-dev
**Build Number**: 20221102.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.0 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Ad-hoc testing
**Regression From**: Previous release (1.26.1)

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Observe its toolbar -> Resize the toolbar.
3. Check whether the actions button on the toolbar can be collapsed.
## Expected Experience ##
The actions button on the toolbar can be collapsed.
![image](https://user-images.githubusercontent.com/41351993/199422998-0e20dd4f-9d5b-4121-a155-d49b9a3f979e.png)

## Actual Experience ##
The actions button on the toolbar cannot be collapsed.
![image](https://user-images.githubusercontent.com/41351993/199423005-e7fae877-d693-43a9-97c9-b5d0e409aef2.png)

**Comment by JasonYeMSFT** [comment]
I published a new file extension to recover my original fix to this problem.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20221103.3. Fixed. So, we are going to close it.
