### ISSUE TITLE
Fail to set bandwidth limit in one blob container/file share

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6245]
**Storage Explorer Version:** 1.27.0-dev
**Build Number:** 20221102.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.0 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.26.1)

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Open one blob container -> Upload one blob.
3. Click ''Adjust Bandwidth Limit...' -> Type a valid bandwidth limit value -> Click 'Save'.
4.  Reopen the 'Adjust Bandwidth Limit' dialog.
5. Check whether succeeds to set bandwidth limit.

## Expected Experience ##
Succeed to set bandwidth limit.

## Actual Experience ##
Fail to set bandwidth limit.

## Additional Context ##
The transfer activity log is always in progress after setting bandwidth limit.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20221104.1. Fixed. So, we are going to close it.
