### ISSUE TITLE
Cloning a blob with Tags does not copy the Tags

### ISSUE THREAD

**Issue by richardhauer** [microsoft/AzureStorageExplorer#6246]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.26.1

### Architecture

x64

### Storage Explorer Build Number

20221018.5

### Platform

Windows

### OS Version

Windows 11 25231

### Bug Description

When "cloning" a blob I would have expected all the Tags assigned to the source blob to be copied to the target blob, but no tags were copied.

### Steps to Reproduce

1. Open Storage Explorer
2. Navigate to Azure Storage Accounts
3. Open Blob Container
4. Set some Tags on a Blob
5. Clone Blob (into same folder - rename as 'copy')
6. Note that tags are missing

### Actual Experience

As per Steps

### Expected Experience

Cloning implies an exact copy of the source. I would have expected the Tags to also be copied in this case.

**Comment by JasonYeMSFT** [comment]
We currently don't copy tags because tags need to be set separately after copying the blobs. Currently clone and batch copy/paste are using the same code path and it is not feasible to set tags in batch. We should consider making single blob clone a special case by preserving tags for the cloned blob.

**Comment by JasonYeMSFT** [comment]
At the mean time, let's try to have a conversation with the service team to see if they can provide an API to atomically preserve tags for batch blob copy.

**Comment by JasonYeMSFT** [comment]
I will make our clone preserve tags in 1.28.0 by reading tags from the source and setting at destination. Copy/paste won't preserve tags since reading/setting tags for batch blobs isn't scalable.

**Comment by DaveSlinn** [comment]
@JasonYeMSFT  I just tried copying between storage accounts hoping to see the tags retained, but the AzCopy command I copied to the clipboard has s2s-preserve-blob-tag = false in the command:
```
$env:AZCOPY_CONCURRENCY_VALUE = "AUTO";
./azcopy.exe copy "https://xxxxxxxxx.blob.core.windows.net/files/2023/02/22/?sv=2021-10-04&st=2023-02-22T23%3A10%3A47Z&se=2023-03-01T23%3A10%3A47Z&sr=c&sp=rlt&sig=XXXXXXX" "https://yyyyyyy.blob.core.windows.net/files-dev/2023/02/?sv=2021-10-04&se=2023-03-24T23%3A26%3A00Z&sr=c&sp=rwlt&sig=JPlSsyyyyyyyyy" --overwrite=prompt --from-to=BlobBlob --s2s-preserve-access-tier=false --check-length=true --include-directory-stub=false --s2s-preserve-blob-tags=false --recursive --log-level=INFO;
$env:AZCOPY_CONCURRENCY_VALUE = "";
```
Can I enable this setting to be true in the settings?  I could, of course, use the command copied and change it myself, but I would prefer that when I use Azure Storage Explorer to execute the command for me for it to be true by default.

**Comment by JasonYeMSFT** [comment]
@DaveSlinn Depending on the storage account types, sku tier, there are corner cases where blindly attempting to preserve tags would block normal copy/paste scenario. We discovered that problem too late in the previous milestone and I didn't have time to make it work for all copy/paste scenarios. We'll investigate how to enable it without breaking anything existing UX.
