### ISSUE TITLE
Succeed to preview one blob which size is larger than 10 MiB under the tag query mode

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6249]
**Storage Explorer Version**: 1.27.0-dev
**Build Number**: 20221103.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.0 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob with .txt file extension which size is larger than 10 MiB.
3. Add one tag for the blob -> Apply the tag to query.
4. Right click the blob under the tag query mode -> Click 'Preview'.
5. Check whether there is a failed activity indicating 'The blob size must be less than 10 MiB'.

## Expected Experience ##
There is a failed activity indicating 'The blob size must be less than 10 MiB'.

## Actual Experience ##
Succeed to open the preview tab.

**Comment by MRayermannMSFT** [comment]
During filter by tags, we do not have the size of the blobs. Therefore the size limit restriction is not having any effect. We'll won't fix this for now and wait for user feedback.
