### ISSUE TITLE
Succeed to clone one ADLS Gen2 blob/regular blob using a name which just has file extension case difference

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6250]
**Storage Explorer Version**: 1.27.0-dev
**Build Number**: 20221103.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.0 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1.  Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob named file.txt.
3. Clone the blob with a new name file.TXT.
4. Check whether there is an error activity log indicating 'An item with the name 'file.TXT' already exists'.

## Expected Experience ##
There is an error activity log indicating 'An item with the name 'file.TXT' already exists'.
![image](https://user-images.githubusercontent.com/41351993/199662314-3d840150-ba9f-41c7-ac97-96e369cc392c.png)

## Actual Experience ##
Succeed to clone the blob.
![image](https://user-images.githubusercontent.com/41351993/199662545-f196a00b-29ab-4807-b191-4bfc17f31888.png)

## Additional Context ##
1. This issue also reproduces for ADLS Gen2 blobs.
2. This issue doesn't reproduce for file shares.

**Comment by MRayermannMSFT** [comment]
This is by design. In the view of the service, for blobs and gen2 blobs, they are different. However for file shares they are considered the same.
