### ISSUE TITLE
Couldn't connect to Azure storage

### ISSUE THREAD

**Issue by GNVRavikumar** [microsoft/AzureStorageExplorer#6251]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.26.1

### Architecture

x64

### Platform

Windows

### OS Version

Windows 10

### Bug Description

We are trying to connect Azure store which is giving "Unable to retrieve child resources." Exception.

### Steps to Reproduce

1. Launch Storage Explorer
2. Connect to Storage with Account Name & Key
3. Enter Storage name, Account name & Key
4. Throwing error while trying to connect as attached in the screenshot

### Actual Experience

Couldn't connect to Azure storage

![image](https://user-images.githubusercontent.com/117338065/199666593-f3125bb6-f088-4653-a04f-6aa2a4f1b317.png)

### Expected Experience

Should connect to Azure storage

**Comment by JasonYeMSFT** [comment]
Could you take a look at the certificates issue section in our troubleshooting guide to see if you can resolve the issue following any of the suggested steps? https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2204#ssl-certificate-issues

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem we recommend opening a support ticket from the portal. Alternatively you can open a new issue here.
