### ISSUE TITLE
There is a duplicate active folder under the 'Active and soft deleted blobs' context view after uploading blobs to the folder that contains all files deleted from the folder before it was soft deleted

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6253]
**Storage Explorer Version**: 1.27.0-dev
**Build Number**: 20221103.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.0 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 Storage account -> Blob Containers.
2. Create a blob container -> Create a folder -> Upload one blob to the folder.
3. Soft delete the blob -> Soft delete the folder.
4. Switch to the 'Active and soft deleted blobs' context view.
5. There is one active folder in the editor -> Open the folder.
6. Upload one blob to the folder -> Go back to the root.
7. Check whether there is no duplicate active folder.

## Expected Experience ##
There is no duplicate active folder.

## Actual Experience ##
There is a duplicate active folder.
![image](https://user-images.githubusercontent.com/41351993/199685639-05cd42c0-25fc-46f4-a8ae-7fcb56edd8c9.png)

**Comment by JasonYeMSFT** [comment]
This is a known service issue. At this point we cannot workaround it for various reasons. Let's make sure the user can access both the active and deleted blobs/directories.
