### ISSUE TITLE
Denial of Access for Azure Storage Account

### ISSUE THREAD

**Issue by Suvathyganesh** [microsoft/AzureStorageExplorer#6254]
Posting here the error details while connecting to the Storage account/ File Share in Azure Storage Explorer.

Have verified the network connection and access control permission.

Unable to retrieve child resources.

Details:
{
  "name": "Error",
  "message": "Unable to perform operation 'FileServiceClient.listSharesSegment'. No suitable credentials provided.",
  "stack": "Error: Unable to perform operation 'FileServiceClient.listSharesSegment'. No suitable credentials provided.\n    at FileServiceClient.runOperation (C:\\Users\\suvathyg\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:484162)\n    at FileServiceClient.listSharesSegment (C:\\Users\\suvathyg\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:33219)\n    at FileShareNodeProducer.produceFileShareNodes (C:\\Users\\suvathyg\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:62341)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Azure.Storage.FileShareProducer.produceFileShareNodes (C:\\Users\\suvathyg\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:84144)\n    at async Provider.executeOperation (C:\\Users\\suvathyg\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\providers\\Provider.js:28:16)\n    at async NodeProcessHostProxy._handleExecuteRequest (C:\\Users\\suvathyg\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:229:31)\n    at async NodeProcessHostProxy._handleMessage (C:\\Users\\suvathyg\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:182:24)\n    at async C:\\Users\\suvathyg\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:65:17"
}

**Comment by JasonYeMSFT** [comment]
@Suvathyganesh The error indicates that there is no credential available for us to access the file share service in your storage account. How did you connect to that storage account? Did you sign-in/use a connection string? Do you know if you are using a SAS token or storage account key to authenticate?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem we recommend opening a support ticket from the portal. Alternatively you can open a new issue here.
