### ISSUE TITLE
There is a failed activity log when running 'Folder Statistics' for one blob container under a Premium GPV2 storage account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6256]
**Storage Explorer Version**: 1.27.0-dev
**Build Number**: 20221107.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.0 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.26.1)

## Steps to Reproduce ##
1. Expand one Premium GPV2 Storage account -> Blob Containers.
2. Open a blob container -> Click 'Folder Statistics' on the toolbar.
3. Check whether there is a successful activity log.

## Expected Experience ##
There is a successful activity log.

## Actual Experience ##
There is a failed activity log.
![image](https://user-images.githubusercontent.com/41351993/200491069-15a29c7e-bad2-488c-93e0-a15fcb2793eb.png)

Error details:
`	Failed to inspect '', error: {
	  "name": "RestError",
	  "message": "Value for one of the query parameters specified in the request URI is invalid.\nRequestId:34d4a143-801c-0004-5216-f339eb000000\nTime:2022-11-08T02:08:18.0873549Z",
`
## Additional Context ##
This issue doesn't reproduce for the action 'Selection Statistics'.

**Comment by MRayermannMSFT** [comment]
Opened an ICM for now to see if we can get the server to not complain in this scenario (347652051).

**Comment by v-xianya** [comment]
Verified this issue on the build main/20221111.1. Fixed.
