### ISSUE TITLE
Not able to access a specific storage account containers

### ISSUE THREAD

**Issue by PrabhakarAtla** [microsoft/AzureStorageExplorer#6258]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.0

### Architecture

i86

### Platform

Windows

### Bug Description

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://dledwdev002.blob.core.windows.net/?comp=list&include=metadata failed, reason: connect ETIMEDOUT 10.23.26.8:443",
  "stack": "FetchError: request to https://dledwdev002.blob.core.windows.net/?comp=list&include=metadata failed, reason: connect ETIMEDOUT 10.23.26.8:443\n    at ClientRequest.<anonymous> (C:\\Users\\Prabhakar.Atla\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1491:11)\n    at ClientRequest.emit (node:events:526:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:526:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "ETIMEDOUT",
  "code": "ETIMEDOUT"
}

### Steps to Reproduce

1. Launch storage explorer.
2. Login and trying to open a storage account which I have access to and which I am able to access through Portal.azure.com
3. Getting the error mentioned in the description above.

### Actual Experience

1. Launch storage explorer.
2. Login and trying to open a storage account which I have access to and which I am able to access through Portal.azure.com
3. Getting the error mentioned in the description above.

**Comment by craxal** [comment]
@PrabhakarAtla Are you trying to connect through a proxy? Have you configured Storage Explorer's proxy settings to do so? Can you also share your log files (Help > Open Logs Directory)?

**Comment by PrabhakarAtla** [comment]
No, was not using any proxys. The issue is now resolved. It looks like the private endpoints that were in place for the storage account were deleted accidentally which caused the connectivity issues. We created them back to resolve the issue.
