### ISSUE TITLE
Can I export my settings from Azure Storage?

### ISSUE THREAD

**Issue by martinpurdy** [microsoft/AzureStorageExplorer#6262]
Moving to a new pc, I would like to get my Azure Storage Explorer settings with me.

Is that possible?

**Comment by craxal** [comment]
@martinpurdy It's possible to an extent. All you have to do is copy the contents of the settings.json file from your old PC to your new one. You can open your settings file by clicking the "Open settings file..." link on the Settings page.

Keep in mind this will copy over your settings but no Quick Access items or attachments. We're currently investigating ways to make exporting/importing these things easier (see #2880).
