### ISSUE TITLE
Local certificate issue

### ISSUE THREAD

**Issue by carlos-amador-hn** [microsoft/AzureStorageExplorer#6263]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.26.1

### Architecture

x64

### Platform

Windows

### OS Version

Windows 10 Enterprise

### Bug Description

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://fanssisstorage1.blob.core.windows.net/?comp=list&include=metadata failed, reason: unable to get local issuer certificate",
  "stack": "FetchError: request to https://fanssisstorage1.blob.core.windows.net/?comp=list&include=metadata failed, reason: unable to get local issuer certificate\n    at ClientRequest.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1491:11)\n    at ClientRequest.emit (node:events:526:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:526:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY",
  "code": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"
}

### Steps to Reproduce

1. Launch Microsoft Azure Storage Explorer
2. Going to Blob Containers (inside Storage Accounts)
3. Error appears

### Actual Experience

It stops and I coun't upload the file

**Comment by craxal** [comment]
@carlos-amador-hn Here are a few questions and suggestions:

* Are you using a proxy? If so, what are your Storage Explorer proxy settings? Have you tried the "System proxy" setting?
* Does your proxy require certificates? If you're using a proxy and the "System proxy" setting doesn't work, did you [import those certificates](https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2204#import-ssl-certificates)? 
* If none of the suggestions above work, can you share your log files here?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem we recommend you open an Azure support ticket via the portal. Alternatively you can open a new issue here.
