### ISSUE TITLE
It is better to make the downloaded items' parent folder selected when clicking 'Show in Folder' next to the 'Download All' activity log

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6265]
**Storage Explorer Version**: 1.27.0-dev
**Build Number**: 20221110.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.0 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Right click blob -> Download the blob by clicking 'Download -> Download All...'.
4. After the download complete -> Click 'Show in Folder' next to the activity log.
5. Check whether the downloaded blob's parent folder is selected.

## Expected Experience ##
It is better to make the downloaded blob's parent folder selected.

## Actual Experience ##
Navigate to the download path.
![image](https://user-images.githubusercontent.com/41351993/201028282-b64d178d-2cf2-4a35-aabd-71db474f6be4.png)

![image](https://user-images.githubusercontent.com/41351993/201027983-53a769aa-5948-4b91-ac58-38c7f4d09dfd.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into main.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20221116.3. Fixed.
