### ISSUE TITLE
There is an extra frame around the refresh icon in the explorer when resizing the property column then clicking 'Refresh' button

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6266]
**Storage Explorer Version:** 1.27.0-dev
**Build Number:** 20221110.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.0 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** Ad-hoc testing
**Regression From:** Previous release (1.24.3)

## Steps to Reproduce ##

1. Expand one storage account -> File Shares.
2. Create a file share -> Drag the first column to make it wider
3. Click 'Refresh' button -> Observe the explorer.
4. Check there is no extra frame around the refresh icon

## Expected Experience ##
There is no extra frame around the refresh icon.

## Actual Experience ##
There is an extra frame around the refresh icon.
![image](https://user-images.githubusercontent.com/87792676/201049095-80d9f5f1-49c3-44fb-9e2b-2934623184f7.png)

## Additional Context ##

1. This issue also reproduces for ADLS Gen2 blob containers/tables.
2. This issue doesn't reproduce for resource groups/regular blob containers/queues.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20221120.1. Fixed. So, we are going to close it.
