### ISSUE TITLE
The detached blob container/file share/table/storage account appears after manually refreshing

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6268]
**Storage Explorer Version:** 1.27.0-dev
**Build Number:** 20221111.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.0 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.26.1)

## Bug Description ##

1. The detached blob container/file share/table/storage account appears after manually refreshing.
2. The attached queue doesn’t disappear after detaching it.

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Attach the blob container.
3. Right click the attached blob container -> Click 'Detach -> Yes'.
4. The blob container disappears -> Refresh the Blob Containers node.
5. Check whether the detached blob container doesn't appear.

## Expected Experience ##
The detached blob container doesn't appear.

## Actual Experience ##
The detached blob container appears.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20221113.2. Fixed. 
So, we are going to closed it.
