### ISSUE TITLE
The 'Application' option is always selected when switching the options on the left side of the Settings panel

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6269]
**Storage Explorer Version:** 1.27.0-dev
**Build Number:** 20221111.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.0 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.26.1)

## Steps to Reproduce ##

1. Launch Storage Explorer.
2. Open 'Settings' -> Click 'Data Explorers'.
3. Observe the options on the left side of the Settings panel.
4. Check whether the 'Data Explorers' option is selected.

## Expected Experience ##
The 'Data Explorers' option is selected.
![image](https://user-images.githubusercontent.com/87792676/201301421-5c68e80b-7232-407c-b387-6435081f66ed.png)

## Actual Experience ##
The 'Application' option is selected.
![image](https://user-images.githubusercontent.com/87792676/201301231-6ae2b2b3-47e4-40c4-9d6d-17323c1f8008.png)

**Comment by craxal** [comment]
I noticed this was happening before the search feature was added. There doesn't appear to be any code to handle the change.

@JasoneYeMSFT Can you look into it?

**Comment by v-xianya** [comment]
Verified this issue on the build main 20221113.2. Fixed. So, we are going to close it.
