### ISSUE TITLE
ProxyAuthentication throws 407 ERROR (Credentials missing)

### ISSUE THREAD

**Issue by Gill-Bates** [microsoft/AzureStorageExplorer#627]
**Storage Explorer Version**: 1.4.1
**Platform/OS Version**: Windows 7

#### Steps to Reproduce: ####
1. Enable Proxy Authentication in Storage Explorer
2. Set Proxy, Username & PW
2. Try to login to Azure (login.microsoftonline.com)

#### Expected Experience: ####
Grant connection

#### Actual Experience: ####
"message": "\"ERR_TUNNEL_CONNECTION_FAILED\""

As you can see, Username and Password is not send to the Proxy:

2018-08-31 07:26:01 2 xx.xx.xx.xx TCP_DENIED 407 300 277 CONNECT tcp://login.microsoftonline.com:443/ - - - "Technology/Internet" DENIED - http.proxy "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) StorageExplorer/1.4.1 Chrome/61.0.3163.100 Electron/2.0.0 Safari/537.36"

**Comment by WTFMaster** [comment]
@craxal Yes, my result is what you described:

`http://user:password@xx.xx.xx.xx:8080`

![grafik](https://user-images.githubusercontent.com/25774289/44969994-dffd5980-af4f-11e8-8c0e-38f55ce5acc6.png)

**Comment by craxal** [comment]
What kind of proxy is your proxy server?

**Comment by sl092l** [comment]
HI, I have the same issue, but managed to speak to our Firewall team and get it working, bypassing Authentication and whitelist the SSL cert.

What we found that we need the software to be able to use NTLM authentication to get past our Proxy server (Mcafee Web Gateway), also it would be good it would send a Agent user string so that we can filter access on this.

**Comment by craxal** [comment]
@sl092l, unfortunately, Storage Explorer does not support NTLM proxy servers.

**Comment by WTFMaster** [comment]
We are using Symantec WebGateway. We do SSL Interception plus LDAP Authentificaton.

**Comment by craxal** [comment]
I'm guessing our Node/Electron framework doesn't support LDAP authenticating proxies, at least directly. Did you make sure you imported any certificates your proxy might be using?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you're still having problems. Thanks.
