### ISSUE TITLE
Lease operations are not supported on ADLS Gen2 directories

### ISSUE THREAD

**Issue by Arithmomaniac** [microsoft/AzureStorageExplorer#6272]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.26.1

### Architecture

i86

### Storage Explorer Build Number

20221018.5

### Platform

Windows

### OS Version

Windows 11 Enterprise 22H2

### Bug Description

Lease operations are not supported on ADLS Gen2 directories, just ADLS files. For example, one cannot acquire a lease on an ADLS directory.

### Steps to Reproduce

1. Launch Storage explorer
2. Open an ADLS Gen2 Blob Container.
3. Create a directory ("New Folder").
4. Right-click on the folder.

### Actual Experience

The "Acquire Lease" option is grayed out.

![image](https://user-images.githubusercontent.com/654897/201525367-a23223ca-b5ab-443f-8484-279a09f8006d.png)

### Expected Experience

It is not grayed out and I am able to acquire a lease.
If a lease is acquired, the red "lock" item appears on the file and the "Break Lease..." menu item is enabled.

### Additional Context

Taking leases on directories is supported in ADLS Gen2 (see, e.g. the [REST API](https://learn.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/path/lease) and [C# SDK](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.files.datalake.datalakeleaseclientextensions.getdatalakeleaseclient?view=azure-dotnet#azure-storage-files-datalake-datalakeleaseclientextensions-getdatalakeleaseclient(azure-storage-files-datalake-datalakepathclient-system-string)) documentation), but the lease does not affect child files and subdirectories - just the folder object itself.

(Note: the Architecture in "About" actually reads `ia32`, not `x86`.)

**Comment by JasonYeMSFT** [comment]
This will be supported in the next 1.28.0 release.
