### ISSUE TITLE
Succeed to rename the QA item if an same service with the same name already exists and share the same original storage account with the renamed QA item

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6274]
**Storage Explorer Version**: 1.27.0-dev
**Build Number**: 20221113.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.0 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create two blob containers -> Pin the two blob containers to 'Quick Access'.
3. Go the 'Quick Access' node.
4. Try to rename one QA blob container using another blob container's name.
5. Check whether fails to rename the QA blob container.

## Expected Experience ##
Fail to rename it.

## Actual Experience ##
Succeed to rename.

## Additional Context ##
This issue also reproduces for ADLS Gen2 blob containers/file shares/queues/tables.

**Comment by craxal** [comment]
Marking as Won't Fix. There are essentially no reasons to restrict what users may rename their Quick Access items to, because the name they use is for display only. Blocking users from using certain names is really just a way from preventing them from confusing themselves, but we decided this was an extreme edge case that we don't need to concern ourselves over.

**Comment by v-xianya** [comment]
@craxal Thank you for the updates!
One thing needs you confirm, according to this issue.
If there are two QA items that with the same name and same type, also share the same original storage account.
Only one tab is opened when trying to open the two QA items. Does this need attention?

**Comment by craxal** [comment]
@v-xianya Yes, that is a problem, but we already know about that. There's an issue opened for it, and we are addressing it.
