### ISSUE TITLE
The 'Rename' button is still enabled when there is a warning message on the 'Rename Connection' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6275]
**Storage Explorer Version**: 1.27.0-dev
**Build Number**: 20221113.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.0 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Select one file share -> Attach the file share.
3. Attach the file share again.
4. Right click one attached file share -> Click 'Rename Connection...'.
5. Type another attached file share's name in the 'File share connection name' field -> A warning message occurs.
6. Check whether the 'Rename' button is disabled.

## Expected Experience ##
The 'Rename' button is disabled.

## Actual Experience ##
The 'Rename' button is enabled.
![image](https://user-images.githubusercontent.com/41351993/201630668-62c39db6-4493-4838-bdae-b5d5ab85c37c.png)

**Comment by craxal** [comment]
Reproduces for all other service types.
