### ISSUE TITLE
error while copy large file

### ISSUE THREAD

**Issue by kuldeepmalhotra123** [microsoft/AzureStorageExplorer#6276]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19

### Architecture

x64

### Platform

Windows

### Bug Description

Getting some error while copying .5TB sql server .bak file from storage explorer to data lake gen2. 

 UnexpectedCancel (used SAS, discovery completed)

2022/11/14 19:12:00 ERR: [P#0-T#0] UPLOADFAILED: \\?\UNC\amlin.com\it\DBBackups_DBA_D1\D1_Restores\PPM Backup\PPM\PPM_FULL_01_of_16.bak : 403 : 403 Forbidden. When Staging block. X-Ms-Request-Id: 

   Dst: https://msalake.blob.core.windows.net/ppdbcopy/backup/PPM_FULL_01_of_16.bak?se=2022-12-14T18%3A15%3A29Z&sig=-REDACTED-&sp=rwl&sr=c&sv=2021-08-06
2022/11/14 19:12:00 JobID=b4bec8a2-dc23-aa4b-4a06-8616df7b4b0c canceled
2022/11/14 19:12:01 PERF: primary performance constraint is Disk. States: X:  0, O:  0, M:  0, L:  0, R:  0, D:  1, W:  0, F:  0, B:  0, E:  0, T:  1, GRs: 11
2022/11/14 19:12:01 16.5 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total, 2-sec Throughput (Mb/s): 294.7905 (Disk may be limiting speed)
2022/11/14 19:12:02 ==> REQUEST/RESPONSE (Try=1/675.6881ms, OpTime=675.6881ms) -- RESPONSE SUCCESSFULLY RECEIVED
   GET https://msalake.blob.core.windows.net/ppdbcopy/backup/PPM_FULL_01_of_16.bak?blocklisttype=all&comp=blocklist&se=2022-12-14T18%3A15%3A29Z&sig=-REDACTED-&sp=rwl&sr=c&sv=2021-08-06&timeout=31
   X-Ms-Request-Id: [2ea474e3-001e-0037-145c-f82581000000]

2022/11/14 19:12:02 ==> REQUEST/RESPONSE (Try=1/12.0049ms, OpTime=13.0064ms) -- RESPONSE STATUS CODE ERROR
   DELETE https://msalake.blob.core.windows.net/ppdbcopy/backup/PPM_FULL_01_of_16.bak?se=2022-12-14T18%3A15%3A29Z&sig=-REDACTED-&sp=rwl&sr=c&sv=2021-08-06&timeout=30
   User-Agent: [Microsoft Azure Storage Explorer, 1.26.1, win32, azcopy-node/2.7.1-rc.1 (win32)  AzCopy/10.16.0 Azure-Storage/0.15 (go1.17.9; Windows_NT)]
   X-Ms-Client-Request-Id: [dfb3f101-7e7b-4666-506a-8346c497f87a]
   X-Ms-Version: [2020-10-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation using this permission.
   Content-Length: [279]
   Content-Type: [application/xml]
   Date: [Mon, 14 Nov 2022 19:12:02 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [dfb3f101-7e7b-4666-506a-8346c497f87a]
   X-Ms-Error-Code: [AuthorizationPermissionMismatch]
   X-Ms-Request-Id: [2ea47743-001e-0037-395c-f82581000000]
   X-Ms-Version: [2020-10-02]
Response Details: ﻿<Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission. </Message>

2022/11/14 19:12:02 JobID=b4bec8a2-dc23-aa4b-4a06-8616df7b4b0c, Part#=0, TransfersDone=1 of 1
2022/11/14 19:12:02 all parts of entire Job b4bec8a2-dc23-aa4b-4a06-8616df7b4b0c successfully completed, cancelled or paused
2022/11/14 19:12:02 all parts of entire Job b4bec8a2-dc23-aa4b-4a06-8616df7b4b0c successfully cancelled
2022/11/14 19:12:02 is part of Job which 1 total number of parts done 
2022/11/14 19:12:03 PERF: primary performance constraint is Unknown. States: X:  0, O:  0, M:  0, L:  0, R:  0, D:  0, W:  0, F:  0, B:  0, E:  0, T:  0, GRs: 11
2022/11/14 19:12:03 0.0 %, 0 Done, 1 Failed, 0 Pending, 0 Skipped, 1 Total, 

### Steps to Reproduce

connect to azure data lake, create new folder ans use storage explorer to copy

### Actual Experience

error while copying

**Comment by MRayermannMSFT** [comment]
@kuldeepmalhotra123 how did you connect to your two containers? Did you attach each of them? Or for one/both of them, did you sign-in, and then go into a subscription?

**Comment by kuldeepmalhotra123** [comment]
via storage explorer. The files are at my machine, they are .5TB each.

**Comment by MRayermannMSFT** [comment]
Yes, I know you are using Storage Explorer. But how did you connect Storage Explorer to the destination container?
![image](https://user-images.githubusercontent.com/21112697/203135096-ff3e1c00-b1b6-4489-b912-f6bde9b1ae3a.png)
Did you choose the first option I marked in red, or the second?

Also, any chance something else is writing to the destination blob at the same time? Is there already a blob at the destination? E.g., as part of this upload are you overwriting existing data?

**Comment by kuldeepmalhotra123** [comment]
I am using first option and there is no existing data.   
  
  
  
  
  
  
  

  
  
>

**Comment by MRayermannMSFT** [comment]
@kuldeepmalhotra123 can you:
1. Try again in Storage Explorer, and if it fails...
2. Click "copy azcopy command to clipboard"
3. Paste and save that somewhere
4. Download AzCopy: https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10
5. Run the command yourself via the command line
6. See if AzCopy spits out any other errors?
7. Regardless of step 6, if running on the command line also fails, please go to `<your user directory>/.azcopy`, find the newest log file, and share with us here.

Unfortunately we are stumped right now.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem and need help, we recommend opening an Azure support ticket via the Azure portal.
