### ISSUE TITLE
The 'Quick Access' node is selected after renaming one attachment or QA item 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6277]
**Storage Explorer Version**: 1.27.0-dev
**Build Number**: 20221114.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.0 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Right click one storage account -> Pin it to the 'Quick Access' node.
2. Right click the QA storage account -> Click 'Rename...'.
3. Type a valid name into the Display name field -> Click 'Rename'.
4. Check whether the renamed QA item is selected.

## Expected Experience ##
The renamed QA item is selected.

## Actual Experience ##
The 'Quick Access' node is selected.

## Additional Context ##
1. This issue also reproduces when renaming one attachment.
2. This issue also reproduces for the four services & resource groups.

**Comment by craxal** [comment]
This is expected behavior. The tree has to recreate nodes; we do not modify an existing node.

@MRayermannMSFT Is it possible to preserve the selection between tree refreshes? With the resource UID, I'd think in theory it could be done.
