### ISSUE TITLE
The secondary blob container of one leased blob container doesn't show as leased

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6278]
**Storage Explorer Version**: 1.27.0-dev
**Build Number**: 20221114.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.0 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Ad-hoc testing
**Regression From**: Previous release (1.23.1)

## Bug Descriptions ##
The leased blob container's secondary blob container doesn't show as leased while a blob container which just break lease, its secondary blob container shows as leased

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Acquire lease for the blob container -> Click the blob container to make below properties show correct.
![image](https://user-images.githubusercontent.com/41351993/201892589-04c9de78-0282-4bff-abc0-cb1a71fd26a7.png)

3. Right click the leased blob container -> Click 'Open Secondary Location'.
4. Check whether the secondary blob container shows as leased.

## Expected Experience ##
The secondary blob container shows as leased.

## Actual Experience ##
The secondary blob container doesn't show as leased.
![image](https://user-images.githubusercontent.com/41351993/201891082-0274f7dd-e085-44a1-b69b-c69dbc1d9648.png)

## Additional Context ##
Here is the record:
![Bloblease](https://user-images.githubusercontent.com/41351993/201891382-063124f1-7055-4a52-b8eb-b695eeecd404.gif)

**Comment by JasonYeMSFT** [comment]
I am pretty sure this is a timing issue. If you keep refreshing the secondary container node. After a few attempts it will show (leased).
