### ISSUE TITLE
Download results in space character converted to %20 for "unknown" file extension

### ISSUE THREAD

**Issue by DarekDan** [microsoft/AzureStorageExplorer#628]
**Storage Explorer Version**: 1.4.1
**Platform/OS Version**: Windows 10
**Architecture**: ia32
**Regression From**: NOT SURE

#### Steps to Reproduce: ####
1. In an Azure Storage Account File Share, create a few files with spaces in their names and extensions of 7z and QBB
2. Download selected files to any location 
3. The 7z files will have spaces in their names. The QBB files will have %20 where the spaces used to be.

#### Expected Experience: ####
File names must remain intact

#### Actual Experience: ####
File name change from "a b.QBB" to "a%20b.QBB"

**Comment by JakeRadMSFT** [comment]
Or it might make it worse :). 

For blobs, we essentially use encodeURIComponent to get a window safe file name but it does convert spaces to %20. We could make it ignore spaces since those are generally safe.

**Comment by DarekDan** [comment]
Would it be possible to simply use URLRewrite.Decode() during save?

**Comment by MRayermannMSFT** [comment]
Going to go ahead and close this. We're moving to use AzCopy for file shares, and they will be handling all encoding.
