### ISSUE TITLE
Opening container/folder when clicking on the blob URL

### ISSUE THREAD

**Issue by ashkanaa** [microsoft/AzureStorageExplorer#6280]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

It's time consuming to open a blob from a shared link. You have to search and find the storage account, open list of containers, ....

### Desired Solution

Is there anyway to share a link to a container/blob that can be opened in Azure Explorer by clicking the link?

**Comment by JasonYeMSFT** [comment]
You can try using direct link. It allows you to generate a link with a custom protocol which can point to a specific blob container. When you open the link in your browser, if Storage Explorer is installed, it will be launched and automatically navigate to that container if you have access to it.
https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-direct-link

**Comment by JasonYeMSFT** [comment]
I created https://github.com/microsoft/AzureStorageExplorer/issues/6335 to track the proposed idea. At the meantime, @ashkanaa please let us know if the direct link solves your problem.

**Comment by knunery** [comment]
I would find this valuable as well. Only being able to navigate at the container level is nice but it would be a better time-saver if you could have it navigate to a "folder" inside of a container.

**Comment by ashaazami** [comment]
> I created #6335 to track the proposed idea. At the meantime, @ashkanaa please let us know if the direct link solves your problem.

direct link works, but it would be great and improve productivity if we can link to a folder too. Problem with direct link is that no one in our team is using that. I like the suggestion from @thammegowda, only problem with using the https://<storage_account>.blob.core.windows.net/<container_name>/<path>?a=<subscription_id>&r=<resource_group> and 
registering this https://*.blob.core.windows.net is we often share audio wav files using the URLs, and by clicking it will be opened and played in the browser. Maybe the link can be opened in Azure Storage Explorer if it is only pointing to a blob or folders and not a file! Just my though, the feature will definitely need more considerations, but it would be a huge time saver for me and many of my colleagues for sure.

**Comment by JasonYeMSFT** [comment]
From 1.33.0, if the direct link has a blobPath, the "navigate" action will not only open the container but also navigate to the directory.
