### ISSUE TITLE
local network issues when using Storage Explorer

### ISSUE THREAD

**Issue by matthiasdg** [microsoft/AzureStorageExplorer#6283]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.26.1

### Architecture

x64

### Storage Explorer Build Number

20221018.5

### Platform

Linux (snap)

### OS Version

Ubuntu 22.04

### Bug Description

This might be the same as https://github.com/microsoft/AzureStorageExplorer/issues/1099, but I'm not quite sure.
Situation: I have a 300Mbps internet connection at home, use LAN cable to the modem. I tried to copy a lot of folders within an Azure storage account (Data Lake Gen 2)using ASE on my laptop. I don't think this downloads and uploads the files to my local network, because my sent/received traffic stays low.

As soon as I start such a transfer, my girlfriend's laptop's VPN connection (she was also working from home) dies. As soon as I kill Storage Explorer, it comes up again. Saw some name lookup error at some point, so think DNS resolution was impacted. Meanwhile I did not seem to experience network issues; did a speedtest from my machine (fast.com) while the transfer was running, still hit +250Mbps and around my max upload speed (20Mbps), latency was normal too.
When I browsed to the azure portal with the transfer running, it worked okay, however when I clicked through to the blobs I tried to copy, the listing did not work. It proposed to run some kind of diagnostics, some checks passed, others failed (screenshot below). The transfer in Storage Explorer did also seem to hang. Since cancel takes some time, I just killed ASE and removed the target folders. I restarted it and tried again, same error.

~~Did not really think it would work, but I have a VirtualBox with Windows on the same machine, installed ASE in there, ran the same copy operation, completed without any hangs or causing network problems.~~ -> I thought this worked but must have been a coincidence, have the slow/hanging transfers +impact on network there as well (although it seems slightly faster but could be wrong)

### Steps to Reproduce

Not sure if this is very useful, since I'm not sure this happens every time or depends on external factors.
1. Launch ASE, copy a lot of folders (~around 400) within a storage account using copy and paste (ADLS Gen 2)
2. The transfer does not seem to progress and you may experience network issues.

### Actual Experience

Experiencing network issues when copying using ASE. On second thought, I don't think it's actually related to connection speed cf. https://github.com/microsoft/AzureStorageExplorer/issues/1099, cause I now did the same on my company WiFi and that only has 15Mbps down/up. Wondering how the copy works now, does it launch separate requests (too many simultaneous?) for every blob?
My company probably has a better (managed) switch, so maybe that has an impact?
Tried playing around with bandwidth limit, maximum concurrency... did not seem to have an impact.

If you can provide any instructions to trace down the cause (commands I can execute, log files that can help) I'd appreciate! Not sure if I can always reproduce, could e.g. also depend on external factors but willing to try.

### Additional Context
Screenshot of what I get in the azure portal while trying such a transfer:

![Screenshot from 2022-11-16 18-48-27](https://user-images.githubusercontent.com/853674/202256912-97eda470-0ade-49c3-afb9-dc5bd761e6ff.png)

**Comment by matthiasdg** [comment]
Experimented some more, seems that the "File Concurrency" under Settings can help to solve this. What's the default? It starts a copy operation for every individual file, all simultaneously? I put it to 4 and I got transfer speeds over 500Mbps and no issues

**Comment by MRayermannMSFT** [comment]
@matthiasdg AzCopy probably isn't opening a connection for every individual file right away, but it is for probably a large number of them. You can also try tweaking the Network Concurrency setting. Others have had success in similar situations after using "Adjust Dynamically" or a custom value.

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. If you still have this issue, please open a new issue instead.
