### ISSUE TITLE
unable to retrieve child resources

### ISSUE THREAD

**Issue by RanjithMadathil** [microsoft/AzureStorageExplorer#6284]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.26.1

### Architecture

x64

### Platform

Windows

### OS Version

Windows 10

### Bug Description

unable to expand the child file shares from a storage account

![Capture](https://user-images.githubusercontent.com/118368542/202205595-9eec83de-0532-49d4-9211-725719578d86.PNG)

### Steps to Reproduce

1. Launch explorer
2. expand storage account
3. expand file share
4. getting below error ( detailed error attached)
![Capture](https://user-images.githubusercontent.com/118368542/202206964-2c88694f-92f8-41ae-bebe-a24fb78b27eb.PNG)
[Storage explorer error.txt](https://github.com/microsoft/AzureStorageExplorer/files/10022628/Storage.explorer.error.txt)

### Actual Experience

getting error when expand file share

### Expected Experience

show the list of file share

**Comment by MRayermannMSFT** [comment]
@RanjithMadathil do you know if you have access to the keys for the storage account you are trying to list file shares for?

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. If you still have this issue, please open a new issue instead.
