### ISSUE TITLE
Slow tree loading on 1.27-dev macOS

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#6285]
Please list all situations you are able to check for repro/don't repro (OS version, processor type, package/build type, slow loading type (all tree UI vs nodes in the tree), tree type).

Example:

> Repro:
> - macOS 13.0, Intel, dev build, nodes in the tree, daytona tree view
> - macOS 13.0, Intel, test signed build, nodes in the tree, daytona tree view
> 
> Don't repro:
> - macOS 13.0, Intel, real signed build, nodes in the tree, daytona tree view

Also:
- Please make sure that you run a package/build type at least twice before claiming it repros. For example, if you download a signed build to check if you see slow tree loading, do not base "did/did not repro" on the 1st time you run that build. Base it instead on at least the second time you run it, or more ideally, run it a couple of times to see if it is consistent. Both macOS and AV might be doing weird things the first time executables, especially new or unsigned ones are ran.
- When running real/test signed builds, please move the .app into your Applications folder, or if you only repro when not in your Applications folder, then call that out in your bullet.

**Comment by craxal** [comment]
Repro:
* macOS 13.0.1, Intel, dev build, nodes in the tree, daytona tree view

**Comment by richardMSFT** [comment]
Repro:
- macOS 12.6.1, Apple M1 Max, dev build, nodes in the tree, (i don't know if daytona?).
- Next couple instances where I start the app the tree loads instantly. 

Logs from the repro:
[2022-11-16_153050.zip](https://github.com/microsoft/AzureStorageExplorer/files/10026457/2022-11-16_153050.zip)
[Auth Logs.zip](https://github.com/microsoft/AzureStorageExplorer/files/10026456/Auth.Logs.zip)

**Comment by richardMSFT** [comment]
Anecdotally there seems to be a pattern for me where this issue happens when I start the app after ~10 min of not having done it.

**Comment by richardMSFT** [comment]
Logs from normal load:
[2022-11-18_162031.zip](https://github.com/microsoft/AzureStorageExplorer/files/10045619/2022-11-18_162031.zip)
[Auth Log.zip](https://github.com/microsoft/AzureStorageExplorer/files/10045620/Auth.Log.zip)

**Comment by MRayermannMSFT** [comment]
No one has been able to repro with a CI build, only dev builds.
