### ISSUE TITLE
Implement File Share OAuth support behind feature flag

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#6287]
Jing has the email. Visit the topic in v1.28.0

**Comment by MRayermannMSFT** [comment]
Revisited. Likely going to be a 1.29 feature at this point. Will move back if work starts on it.

**Comment by MRayermannMSFT** [comment]
JS SDK will be ready by mid Feb

**Comment by MRayermannMSFT** [comment]
Phase 1:

- [ ] Create DualClient
- [ ] Create file share mgmt plane “SDK helper client”
- [ ] Update file share data plane “SDK helper clients” to declare what credential types operations supports
- [ ] Pass mgmt connection down the layers
- [ ] OAuth unit tests (especially for listing)

Phase 2:

- [ ] Use DualClient to create classes in file extension
- [ ] Use new classes where needed
- [ ] Update conditions for enabling/disabling actions based on mgmt connection existing

**Comment by MRayermannMSFT** [comment]
The above comment is no longer relevant.
