### ISSUE TITLE
The 'Enable Soft Delete' button still displays on the 'Delete' dialog even though the checkbox was checked "Don't ask again about enabling soft delete"

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6289]
**Storage Explorer Version**: 1.27.0-dev
**Build Number**: 20221117.5
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 18.04/MacOS Ventura 13.0 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers. (Soft delete is disabled)
2. Create a blob container -> Upload one blob.
3. Right click the blob -> Click 'Delete'.
4. Check the option "Don't ask again about enabling soft delete" -> Click 'Yes'.
5. Then upload a blob to the blob container.
6. Right click the blob -> Click 'Delete'.
7. Check no 'Enable Soft Delete' button displays on the 'Delete' dialog.

## Expected Experience ##
No 'Enable Soft Delete' button displays on the 'Delete' dialog.

## Actual Experience ##
The 'Enable Soft Delete' button displays on the 'Delete' dialog.
![image](https://user-images.githubusercontent.com/41351993/202400487-5ae7d7b0-f965-49ce-ac6d-8666c20bf704.png)

**Comment by richardMSFT** [comment]
Should be corrected with the most recent changes in main branch.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20221118.3. Fixed.
