### ISSUE TITLE
Storage Explorer is losing accounts when using VS for Mac

### ISSUE THREAD

**Issue by dei79** [microsoft/AzureStorageExplorer#629]
**Storage Explorer Version**: 1.4.1
**Platform/OS Version**: MacOS 10.13.6
**Architecture**: Intel x64
**Regression From**: Yes, 1.3.X

#### Steps to Reproduce: ####
1. Open Storage Explorer and add new account
2. Close Storage Explorer with Cmd + Q
3. Open Visual Studio whcih is using the same account
4. Close Visual Studio with Cmd + Q
5. Open Storage Explorer 
6. Accounts are removed

#### Expected Experience: ####
Accounts should not be removed

#### Actual Experience: ####
Accounts are removed

**Comment by ericdrobinson** [comment]
As a quick note, this may be related to [this issue](https://developercommunity.visualstudio.com/content/problem/485500/microsoftdeveloperidentityservice-keychain-passwor.html) on the VSfM community forums.

**Comment by MRayermannMSFT** [comment]
We're unable to reproduce this anymore. Please open a new issue if you are still having problems.
