### ISSUE TITLE
It is better to remove the checkbox "Don't ask again about enabling soft delete" from the 'Delete' dialog if the soft delete is already enabled

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6290]
**Storage Explorer Version**: 1.27.0-dev
**Build Number**: 20221117.5
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 18.04/MacOS Ventura 13.0 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers. (Soft delete is enabled)
2. Create a blob container -> Upload one blob.
3. Right click the blob -> Click 'Delete'.
4. Check there is no checkbox "Don't ask again about enabling soft delete" on the dialog.

## Expected Experience ##
It is better to remove the checkbox "Don't ask again about enabling soft delete" from the 'Delete' dialog.

## Actual Experience ##
There is a checkbox "Don't ask again about enabling soft delete" on the 'Delete' dialog.
![image](https://user-images.githubusercontent.com/41351993/202403273-08f1c39f-1118-47ba-809f-bb2f18a7af92.png)

## Addition Context ##
This issue also reproduces for ADLS Gen2 blobs when the setting "Enable ADLS Gen2 soft delete (Preview)" is disabled.

**Comment by richardMSFT** [comment]
Should be corrected with the most recent changes in main branch.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20221118.3. Fixed.
