### ISSUE TITLE
It is better to make the format of the subtitle on the 'Clone' dialog consistent between 'blob containers & file shares & tables'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6293]
**Storage Explorer Version**: 1.27.0-dev
**Build Number**: 20221118.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 18.04/MacOS Ventura 13.0 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create one table -> Right click the table -> Click 'Clone...'.
3. Observe the subtitle of the prompt dialog.
4. Expand Blob Containers node -> Right click one blob container -> Click 'Clone...'.
5. Observe the subtitle of the prompt dialog.
6.  Check whether the format of the subtitles is consistent between the two dialogs.

## Expected Experience ##
The format of the subtitles is consistent.
## Actual Experience ##
The format of the subtitles is inconsistent.
![image](https://user-images.githubusercontent.com/41351993/202647606-4f7af53a-54d0-42b7-be30-edfbe27aea09.png)

## Addition Context ##
Here is the screenshot of file share:
![image](https://user-images.githubusercontent.com/41351993/202647732-e3fccf35-c58b-4ba2-9b96-d48b0b865a55.png)

**Comment by MRayermannMSFT** [comment]
Merged new resources, but am not doing any publishing. Will close once I see someone else do a publish.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20221209.3. Fixed. So, we are going to close it.
![image](https://user-images.githubusercontent.com/41351993/206670729-29009029-d96e-4477-9eb3-1b1612efbb8c.png)
