### ISSUE TITLE
An error occurs when launching Storage Explorer on Windows

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6295]
**Storage Explorer Version**: 1.27.0-dev
**Build Number**: 20221118.3
**Branch**: main
**Platform/OS**: Windows 10
**Architecture**: ia32
**How Found**: From running test cases
**Regression From**: Previous release (1.26.1)

## Steps to Reproduce ##
1. Install and launch Storage Explorer.
2. Check whether no error occurs.

## Expected Experience ##
No error occurs.

## Actual Experience ##
An error occurs.
![image](https://user-images.githubusercontent.com/41351993/202665280-ca732536-a462-4a5c-b806-ee618165abd2.png)

## Addition Context ##
1. This issue can't be reproduced consistently.
2. The .NET Framework is already installed.
![image](https://user-images.githubusercontent.com/41351993/202665556-de5046af-90ea-44bb-b7e6-1582b24c2f23.png)

**Comment by MRayermannMSFT** [comment]
Merged something I think will fix this?

**Comment by v-xianya** [comment]
This issue doesn't reproduce on the new build 20221120.1.
