### ISSUE TITLE
More File Types Support for File Preview in Azure Storage Explorer

### ISSUE THREAD

**Issue by DOH-SXN2303** [microsoft/AzureStorageExplorer#6297]
The following three file types don't seem to be currently supported by the File Preview feature in Azure Storage Explorer. We use these file types regularly on our blob containers and would like them supported by File Preview.

The file types are
.log
.hl7
.xml

**Comment by MRayermannMSFT** [comment]
Hi @DOH-SXN2303 ...

First, in the version of Storage Explorer you can currently download, you can enable previewing for all these file types by going to Settings (gear on the left) > Services > Storage Accounts > Text preview extensions, and adding your file extensions to the list. So like:
```
[
  ".txt",
  ".js",
  ".html",
  ".json",
  ".log",
  ".hl7",
  ".xml"
]
```

Second, in a very soon to be released version of Storage Explorer, file previewing will also be enabled for any files which have some sort of `text` content type. So assuming your files do, then previewing will start being enabled for them without any action of your part.

Let us know if you have any further questions or need additional help.

**Comment by Edd-k** [comment]
Hi All,
I'm wondering how I can see a preview of Excel and Word files in the Azure storage explorer preview feature?
