### ISSUE TITLE
Don't default to all resource types when searching

### ISSUE THREAD

**Issue by Ginginho** [microsoft/AzureStorageExplorer#6298]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

More quickly search for the relevant resource

### Desired Solution

I'd like to see the search default to no resource types but additionally offer a search all tick box

### Alternatives and Workarounds

I can untick the other seven types of resources but that quickly becomes an irritation

![2022-11-22 09_31_25](https://user-images.githubusercontent.com/33085296/203278255-90266699-5da6-47c0-b062-7939cc5e283d.png)

**Comment by MRayermannMSFT** [comment]
@Ginginho which of these ideas do you prefer/not-prefer and why?

1. Storage Explorer remembering what checkboxes are checked across sessions
2. Having an "all" checkbox to un-check in one click
3. Not having any checkboxes checked by default at the start of each session

**Comment by Ginginho** [comment]
@MRayermannMSFT With hindsight, I think option #2 is probably the best for all users, especially those who are unsure what type of resource they are looking for. I know that option #3 was what I actually asked for and saves me a click but maybe not best for the majority. I'm not sure that there is much value in option #1 unless a user is only ever accessing a certain resource type.

**Comment by JasonYeMSFT** [comment]
I will try to create a solution combining option 1 and 2.
