### ISSUE TITLE
Log Manual Actions Taken by Users on Blobs using Azure Storage Explorer

### ISSUE THREAD

**Issue by DOH-SXN2303** [microsoft/AzureStorageExplorer#6299]
We would like to get the user's info captured in the logs along with the activity/operation performed when users perform those activities using Azure Storage Explorer. Some examples of the operations include.

1. Read
2. Write
3. Delete
4. Update

**Comment by MRayermannMSFT** [comment]
@DOH-SXN2303 can you elaborate on what you mean by "user's info"? Thanks!

**Comment by DOH-SXN2303** [comment]
@MRayermannMSFT - Our organization grants various Azure Active Directory accounts the necessary access (Reader, Contributor) using (Access Control (IAM)) to specific Azure Storage Accounts and Containers. So, If a person (Azure Active Directory account) uses his/her rights and accesses a storage container using Azure Storage Explorer, and maybe manually deletes/updates a blob in that container, we would want it recorded in logs so that we know which "user account" was used to edit/delete the blob, what DateTime was it edited, what rights they had, etc. That is basically what I meant by "user's info".

**Comment by MRayermannMSFT** [comment]
@doh-sxn2303 for what you want, our application logs probably aren't the best thing. We would recommend you look into the various monitoring, logging, and auditing features available for Azure storage. Here's some resources to get you started:

- https://learn.microsoft.com/en-us/azure/storage/common/storage-analytics-logging
- https://learn.microsoft.com/en-us/azure/storage/blobs/monitor-blob-storage?tabs=azure-portal
- https://learn.microsoft.com/en-us/azure/storage/common/storage-analytics
