### ISSUE TITLE
The default operation system isn't 'Linux' in Storage Explorer web portal

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#630]
**Storage Explorer Version**: 1.4.1
**Platform/OS Version**: Linux Ubuntu 16.04
**Architecture**: x64
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Go to https://azure.microsoft.com/en-us/features/storage-explorer/
2. Check the default operation system.

#### Expected Experience: ####
The default operation system is 'Linux'.

#### Actual Experience: ####
The default operation system is 'Windows'.
![defaultsystem](https://user-images.githubusercontent.com/34729022/45014848-6331b480-b00f-11e8-92c5-dfe804356008.png)

**Comment by craxal** [comment]
We're already aware of this. This is an issue with the web portal, not Storage Explorer.

@CawaMS, do we know if anything is being done about this?
