### ISSUE TITLE
It is better to disable the action 'Download All' if there are only soft-deleted blobs under the context view 'Active and soft deleted blobs'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6302]
**Storage Explorer Version**: 1.27.0-dev
**Build Number**: 20221122.31
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 18.04/MacOS Ventura 13.0.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Soft delete the blob -> Switch to the context view 'Active and soft delete blobs'.
4. Right click the soft deleted blob -> Click 'Download'.
5. Check whether the action 'Download All...' is disabled.

## Expected Experience ##
It would be better to disable the action 'Download All'.

## Actual Experience ##
1. The action 'Download All...' is enabled.
2. There is a successful activity log indicating '0 items transferred'.
![image](https://user-images.githubusercontent.com/41351993/203497594-42206cb8-c55e-49bb-b9ed-d6b647d1b3df.png)

3. [**On Windows**] An error occurs when clicking 'Show in Folder'.
![image](https://user-images.githubusercontent.com/41351993/203497567-7caade87-cc0d-4696-a287-01c2046d0731.png)

**Comment by MRayermannMSFT** [comment]
Merged a change into main which removes the open in folder action if nothing is downloaded. Disabling the action to prevent this situation is not feasible.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20221124.8. Fixed. The 'Show in Folder' action is removed.
![image](https://user-images.githubusercontent.com/87792676/203716074-7cd5a6d7-a676-40fd-be81-cda17092456f.png)
