### ISSUE TITLE
Table CSV Import: Extended import options (Default values and ignore columns)

### ISSUE THREAD

**Issue by MikaelPorttila** [microsoft/AzureStorageExplorer#6305]
https://github.com/microsoft/AzureStorageExplorer/issues/6305#tasklist-block-5bd53dbe-3b72-46ed-a9d0-0556421ac243

### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Imports are impractical and requires major pre-processing.

### Desired Solution

A desired solution would be the option to set fixed keys during imports, an example would be the partitionkey column, and for row-key i 'd like the option to select if a guid should be auto-generated. Another feature would be the option to ignore columns during imports and also the option to map column names to table columns. These options would make the import tool way more practical.

**Comment by craxal** [comment]
@MikaelPorttila These are some good suggestions. We might want to split this request into multiple feature requests, as they aren't all strictly related. Are you OK with that?

The easiest feature to add would be column mapping. This already exists when importing from CSV with no type annotations. The Import Entities dialog shows column names that can be modified. We can easily open the dialog for CSV with type annotations as well to provide the mapping feature.

Adding a column skip option would be the next easiest. The Import Entities dialog is only shown when importing from a CSV with no type annotations, but it includes some options that should also be made available for CSV with type annotations. The dialog also provides a nice summary of the columns being imported. It would be relatively simple to add check boxes to select which columns should be included in the import.

Fixed and auto-generated keys (or even values for any property) will require some thought. Not everyone will want to import data to the same partition, and not everyone will want GUIDs for keys. We'll want something powerful and flexible enough to make it convenient but simple enough to express clearly in the app's UI. If you have more input how you'd like this to look, we'd very much appreciate it.

**Comment by MikaelPorttila** [comment]
@craxal Sure split the features but all those are much needed together in the end for handling large CSV files without the need for external data transformation tools.

Regarding the GUIDs, in our specific use-case I wrote a simple import tool for myself instead and in that case a .Net Guid.NewGuid()-string was good enough for all of our tables. But sure there could be cases when people wants uppercase GUID without hypens, there might be a range of needs. but could that range be handled in a version 2.0 and a simple GUID might cover the need for a majority of users. 

auto-generated could also mean a counter but then you have the edge-case that you might need to set a lock on the table if you start counting based on a live table which might change during the export - Tricky!

**Comment by craxal** [comment]
@MikaelPorttila True, it sounds like a GUID is the safest approach, so perhaps a more sophisticated key generation mechanism isn't necessary at this time.

Another question that pops up is how do we determine _when_ to use fixed/auto keys? Do you find that you often want to import data where there are no "PartitionKey" and "RowKey" columns? Do you ever find yourself wanting to import data where some of the rows have their keys defined and others do not? And, while collisions with GUIDs are unlikely, there is a slim possibility that a generated key pair could match an entity already in the table. Is there some kind of safety net you would want in that case, or would you consider an overwrite/merge warning of some kind sufficient?
