### ISSUE TITLE
Can't navigate past first page when displaying a Blob Storage container with a Tag Query in List Mode 'Flat'

### ISSUE THREAD

**Issue by richardhauer** [microsoft/AzureStorageExplorer#6306]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.26.1

### Architecture

x64

### Storage Explorer Build Number

20221018.5

### Platform

Windows

### OS Version

Windows 11 22H2 25247.1000

### Bug Description

If I query a blob storage collection by tag the count, paging bar and first page of results are shown almost instantly. Clicking the paging bar to navigate to any other page causes the tab to hang and a spinning wait cursor to be shown indefinitely (I waited up to 5 minutes).

### Steps to Reproduce

1. Open blob storage with many objects containing tags
2. Set query filter for tags, list mode = flat
3. Attempt to navigate to the second page, or any other page

### Actual Experience

As per description - navigating to pages causes the tab to crash

### Expected Experience

Additional blob items should be shown from the result set

**Comment by JasonYeMSFT** [comment]
I can reproduce this in our current build. It seems to be a bug.
