### ISSUE TITLE
The selected option on the original settings page is changed after splitting the settings tab

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6307]
**Storage Explorer Version**: 1.27.0
**Build Number**: 20221124.10
**Branch**: rel/1.27.0
**Platform/OS**: Windows 10/Linux Ubuntu 18.04/MacOS Ventura 13.0 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Ad-hoc testing
**Regression From**: Previous release (1.26.1)

## Steps to Reproduce ##
1. Launch Storage Explorer -> Open 'Settings'.
2. Select one option like: **Data Explorers** on the settings page -> Right click the settings tab -> Click 'Split'.
3. Observe the original settings page.
4. Check whether the selected option is **Data Explorers**.

## Expected Experience ##
The selected option is **Data Explorers**.

## Actual Experience ##
The selected option is **Application**.

## Addition Context ##
1. This issue doesn't reproduce when the option '**Application**' is selected on the original settings page.
2. Go back the correct option after closing the split tab.
3. Here is the record:
![test1](https://user-images.githubusercontent.com/41351993/204234983-b70c7d3d-24f7-4fec-9c2b-6d41952d9b70.gif)

**Comment by craxal** [comment]
@MRayermannMSFT @JasonYeMSFT @richardMSFT Do we know if this preserving selected category was ever intentional? If so, how was this done?

**Comment by JasonYeMSFT** [comment]
I see what's happening now. The selected category is a passive reflection of what section is in the visible area in the settings panel. After splitting, since the space of visible area has changed, the selected category will be updated to reflect what is currently being displayed. This behavior is by design.
