### ISSUE TITLE
Connection with SAS key is not working 

### ISSUE THREAD

**Issue by nidewa** [microsoft/AzureStorageExplorer#6308]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.26.1

### Architecture

i86

### Storage Explorer Build Number

20221018.5

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Access the Azure Storage table with valid SAS key is not working and throws an error. Same SAS key based connection has been working until few days ago

Attached is error log from storage explorer 
[StorageExplorer-Error.txt](https://github.com/microsoft/AzureStorageExplorer/files/10106595/StorageExplorer-Error.txt)

### Steps to Reproduce

1. Open Storage Explorer
2. Connect with the SAS key
3. Try to open the storage account that you added and you get the error

### Actual Experience

Error while accessing the storage account that was added with a valid SAS key

**Comment by craxal** [comment]
@nidewa For clarity, it looks like you're using a storage account SAS. Is this correct? I assume you selected "Storage account" when you opened the Connect dialog? Do you know where you got your SAS token from? Are you able to reconnect with a new SAS?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem and need help, we recommend opening an Azure support ticket via the Azure portal.
