### ISSUE TITLE
The ADLS Gen2 blob container under Quick Access node is selected when clicking 'Navigate to Blob Container' on the 'Open Direct Link' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6309]
**Storage Explorer Version**: 1.27.0
**Build Number**: 20221128.3
**Branch**: rel/1.27.0
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.0.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Ad-hoc testing
**Regression From**: Previous release (1.26.1)

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Add the blob container to the Quick Access node.
3. Attach the blob container via Azure Active Directory.
4. Right click the blob container -> Click 'Copy Direct Link to Blob Container'.
5. Paste the direct link into browser to open storage explorer.
6. There is a dialog 'Open Direct Link' -> Click 'Navigate to Container'.
7. Check whether the Azure AD attached blob container is selected and opened.

## Expected Experience ##
The Azure AD attached blob container is selected and opened.

## Actual Experience ##
The blob container under Quick Access node is selected and opened.

## Addition Context ##
Here is the record:
![adls](https://user-images.githubusercontent.com/41351993/204468629-f956b27c-745e-4d80-ac5d-3bbc40172e7a.gif)

**Comment by JasonYeMSFT** [comment]
I had a fix for the bug. Since it is an edge case and we are close to 1.27.0 shipping, I am going to defer merging the bug fix for 1.28.0 release.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20221207.1. Fixed. So, we are going to close it.
