### ISSUE TITLE
Stop auto-refresh of Search Results after Add to Quick Access

### ISSUE THREAD

**Issue by NBelham** [microsoft/AzureStorageExplorer#631]
**Storage Explorer Version**: 1.4.1
**Platform/OS Version**: Windows
**Architecture**: ia32
**Regression From**: Not sure

#### Steps to Reproduce: ####
1. Recent upgrade of Azure Storage Explorer client cause all of my Quick Access items to be invalid so I have to re-define them
2. Using the "Search for resources" feature, I type part of a Resource name and wait some minutes for the search to be completed
3. In the results, I select one Resource, right-click and select "Add to Quick Access"
4. The item is added to Quick Access but the Explorer is refreshed which is annoying and I then have to collapse up the nodes to find the next matching Resource in the previous search results

#### Expected Experience: ####
Prefer to add to Quick Access but the Search Results to not auto-refresh

#### Actual Experience: ####
The search results is refreshed and I lose my context

**Comment by MRayermannMSFT** [comment]
No repro anymore.
