### ISSUE TITLE
The table layout is unfriendly if moving the triangle under the query mode then clicking 'Refresh'

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6310]
**Storage Explorer Version:** 1.27.0
**Build Number:** 20221128.3
**Branch:** rel/1.27.0
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.0.1 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.26.1)

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create a table -> Add one entity.
3. Click 'Query' -> There is a triangle on the right side of the entity.
4. Drop down the triangle -> Click 'Refresh'.
5. Check whether the layout is friendly.

## Expected Experience ##
The layout is friendly.

## Actual Experience ##
The layout is unfriendly.
![image](https://user-images.githubusercontent.com/87792676/204490938-48265995-a2e3-49c3-bff0-da8930c3d69b.png)

## Addition Context ##

1. This issue also reproduces if moving the triangle then closing the query mode.
2. In previous release, there is no triangle under the query mode.

**Comment by craxal** [comment]
@v-kellyluo I assume this is the triangle you're referring to? And when you say "drop down the triangle", do you mean "click and drag the triangle"?

<img width="41" alt="image" src="https://user-images.githubusercontent.com/3473026/204616033-1bedd3d9-af05-461e-9533-e602080d6b51.png">

**Comment by v-kellyluo** [comment]
Verified this issue on the build rel/2022129.3. Fixed. The triangle is removed.
