### ISSUE TITLE
The Quick Access node is selected after clicking 'Load more' under storage accounts tree view

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6311]
**Storage Explorer Version**: 1.27.0
**Build Number**: 20221128.3
**Branch**: rel/1.27.0
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.0.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand Storage Accounts node -> Make sure there is 'Load more' under storage accounts tree view.
2. Click 'Load more'.
3. Check whether the loaded storage account is selected.

## Expected Experience ##
The loaded storage account is selected.

## Actual Experience ##
The Quick Access node is selected.
## Addition Context ##
Here is the record:
![load](https://user-images.githubusercontent.com/41351993/204496292-e79e1e31-d1b7-4ad6-ae20-9d710f94697e.gif)

**Comment by JasonYeMSFT** [comment]
This will occur when loading the last batch of nodes. The current code selects the load more placeholder node which is soon removed. The tree view moves the selection to the first node (Quick Access) on its removal.
