### ISSUE TITLE
Unable to Get Issuer Cert Locally

### ISSUE THREAD

**Issue by artrapp** [microsoft/AzureStorageExplorer#6312]
How do I resolve this? I get this message when expanding Blob Containers

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://ibazdevdls02.blob.core.windows.net/?comp=list&include=metadata failed, reason: unable to get local issuer certificate",
  "stack": "FetchError: request to https://ibazdevdls02.blob.core.windows.net/?comp=list&include=metadata failed, reason: unable to get local issuer certificate\n    at ClientRequest.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1483:11)\n    at ClientRequest.emit (events.js:315:20)\n    at TLSSocket.socketErrorListener (_http_client.js:469:9)\n    at TLSSocket.emit (events.js:315:20)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
  "type": "system",
  "errno": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY",
  "code": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"
}

**Comment by JasonYeMSFT** [comment]
Could you see if this section in our troubleshooting guide help? https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows#ssl-certificate-issues

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem and need help, we recommend opening an Azure support ticket via the Azure portal.
