### ISSUE TITLE
Unable to create blob containers in Azure Iot Edge Blob storage

### ISSUE THREAD

**Issue by Arjun-Dinesh** [microsoft/AzureStorageExplorer#6314]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.26.1

### Architecture

i86

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Tried to create a new container under Blob Containers option in the Azure Blob Storage on IoT Edge. New container creation is not happening. The generated error log is attaching below. Please help.

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to http://XX.XXX.XX.XX:XXXXX/mycontainer?comp=list&include=metadata failed, reason: connect ETIMEDOUT XX.XXX.XX.XX:XXXXX",
  "stack": "FetchError: request to http://XX.XXX.XX.XX:XXXXX/mycontainer?comp=list&include=metadata failed, reason: connect ETIMEDOUT XX.XXX.XX.XX:XXXXX\n    at ClientRequest.<anonymous> (C:\\Users\\XXXXXX\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1491:11)\n    at ClientRequest.emit (node:events:526:28)\n    at Socket.socketErrorListener (node:_http_client:442:9)\n    at Socket.emit (node:events:526:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "ETIMEDOUT",
  "code": "ETIMEDOUT"
}

Where,
XX.XXX.XX.XX:XXXXX is the hostname:port

### Steps to Reproduce

1. Launch Storage Explorer
2. Login storage account using connection string
3. Expand a blob container node
4. Right click and select Create blob container option
5. Give a name to the blob container
6. It shows the message "Creating blob container" and the container creation fails 

### Actual Experience

<img width="929" alt="New blob container issue in Azure Blob Storage on IoT Edge" src="https://user-images.githubusercontent.com/119498765/204791647-92cef255-86bc-4a34-aec0-e58060c399f5.png">

### Additional Context

Added AzureBlobStorageonIoTEdge module (from Microsoft marketplace) in IoT Edge Device. Reffered the below tutorial:
https://learn.microsoft.com/en-us/azure/iot-edge/how-to-deploy-blob?view=iotedge-1.4
and added: 
Environmet Variable:
LOCAL_STORAGE_ACCOUNT_NAME: mycontainer
LOCAL_STORAGE_ACCOUNT_KEY: XXXXXXXXXXX

Container create options:
{
    "HostConfig": {
        "Binds": [
            "containerdata:/blobroot"
        ],
        "PortBindings": {
            "XXXXX/tcp": [
                {
                    "HostPort": "XXXXX"
                }
            ]
        }
    }
}

Module Twin settings:
{
    "deviceAutoDeleteProperties": {
        "deleteOn": true,
        "deleteAfterMinutes": 60,
        "retainWhileUploading": true
    },
    "deviceToCloudUploadProperties": {
        "uploadOn": true,
        "uploadOrder": "OldestFirst",
        "cloudStorageConnectionString": "DefaultEndpointsProtocol=https;AccountName=XXXXXXX;AccountKey=XXXXXXX; EndpointSuffix=core.windows.net;DefaultEndpointsProtocol=https",
        "storageContainersForUpload": {
            "containerdata": {
                "target": "edgelocalblobtest"
            }
        },
        "deleteAfterUpload": true
    }
}

**Comment by JasonYeMSFT** [comment]
Given the error it's possible your computer cannot reach your edge device. Could you try ping the edge device (e.g the host IP) and see if it is reachable?

**Comment by JasonYeMSFT** [comment]
I tried our latest build and it does have problem uploading data to blob IoT. The root cause is the SAS version which gets updated in the public Azure service but isn't supported by the blo IoT module. You can workaround this issue by using an older version of Storage Explorer (e.g. 1.24.3) or directly uploading it using [AzCopy](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10).

**Comment by Arjun-Dinesh** [comment]
Hi JasonYeMSFT,

Thank you so much for the quick response. As you suggested, I just installed older version of Storage Explorer (e.g. 1.24.3). It worked fine and I am able to upload files/images into the storage account - container in the edge device VM.

![image](https://user-images.githubusercontent.com/119498765/206282737-0478176a-c82e-4f9d-b167-e5b9a4bb94a1.png)

**Comment by Arjun-Dinesh** [comment]
> @Arjun-Dinesh Your AzCopy command is incorrect. Since you already have the previous version of Storage Explorer working. You can continue using it until we address this issue in a future release. If you are still interested in learning how to use AzCopy to perform the upload/download, you can learn how AzCopy works here https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10.

Hi JasonYeMSFT,

I tried to transfer a text file "sample-downlink-test.txt" from cloud blob to edge blob by executing azcopy sync command with Cloud blob SAS – Edge blob connection string
sudo azcopy sync "http://XXXXXXXXX.blob.core.windows.net/edgelocalblobtest?SAS" "DefaultEndpointsProtocol=http;BlobEndpoint=http://XX.XXX.XXX.XXX:PORT/myedgeblob;AccountName=myedgeblob;AccountKey=XXXXXXXXXXXXXX" --recursive=true

Output from the logs is showing :
Output is showing the Final Job Status: Completed
Total Number Of Copy Transfers: 2
Number of Copy Transfers Completed: 2

![image](https://user-images.githubusercontent.com/119498765/206946844-e02d34c9-3b02-46e6-9835-46f4ff4fa2c4.png)

-	text file (sample-downlink-test.txt) is not showing in the cont1 of Azure Edge Blob
![image](https://user-images.githubusercontent.com/119498765/206947130-09b5ed40-fcaf-4f4c-a3c6-11a2b7ff8632.png)

-	No file is copied to the mounted folder 
![image](https://user-images.githubusercontent.com/119498765/206947231-76267a22-aa3d-4d53-8dad-106d49643d80.png)

I tried to tail to the generated log file:
sudo tail -1500f /root/.azcopy/3d9328ba-409e-3546-7b46-88fedd3a07e9.log

It is showing ;

2022/12/09 12:18:21 AzcopyVersion  10.16.2
2022/12/09 12:18:21 OS-Environment  linux
2022/12/09 12:18:21 OS-Architecture  amd64
2022/12/09 12:18:21 Log times are in UTC. Local time is 9 Dec 2022 12:18:21
2022/12/09 12:18:21 ISO 8601 START TIME: to copy files that changed before or after this job started, use the parameter --include-before=2022-12-09T12:18:16Z or --include-after=2022-12-09T12:18:16Z
2022/12/09 12:18:21 Any empty folders will not be processed, because source and/or destination doesn't have full folder support
2022/12/09 12:18:21 Job-Command sync http://XXXXXXXXXX.blob.core.windows.net/edgelocalblobtest?SAS DefaultEndpointsProtocol=http;BlobEndpoint=http://XX.XXX.XXX.XXX:PORT/myedgeblob;AccountName=myedgeblob;AccountKey=XXXXXXXXXXXX --recursive=true
2022/12/09 12:18:21 Number of CPUs: 2
2022/12/09 12:18:21 Max file buffer RAM 1.000 GB
2022/12/09 12:18:21 Max concurrent network operations: 32 (Based on number of CPUs. Set AZCOPY_CONCURRENCY_VALUE environment variable to override)
2022/12/09 12:18:21 Check CPU usage when dynamically tuning concurrency: true (Based on hard-coded default. Set AZCOPY_TUNE_TO_CPU environment variable to true or false override)
2022/12/09 12:18:21 Max concurrent transfer initiation routines: 64 (Based on hard-coded default. Set AZCOPY_CONCURRENT_FILES environment variable to override)
2022/12/09 12:18:21 Max enumeration routines: 16 (Based on hard-coded default. Set AZCOPY_CONCURRENT_SCAN environment variable to override)
2022/12/09 12:18:21 Parallelize getting file properties (file.Stat): false (Based on AZCOPY_PARALLEL_STAT_FILES environment variable)
2022/12/09 12:18:21 Max open files when downloading: 1048152 (auto-computed)
2022/12/09 12:18:21 Final job part has been created
2022/12/09 12:18:21 JobID=3d9328ba-409e-3546-7b46-88fedd3a07e9, credential type: Anonymous
2022/12/09 12:18:21 scheduling JobID=3d9328ba-409e-3546-7b46-88fedd3a07e9, Part#=0, Transfer#=0, priority=0
2022/12/09 12:18:21 scheduling JobID=3d9328ba-409e-3546-7b46-88fedd3a07e9, Part#=0, Transfer#=1, priority=0
2022/12/09 12:18:21 Final job part has been scheduled
2022/12/09 12:18:21 INFO: [P#0-T#0] has worker 0 which is processing TRANSFER 0
2022/12/09 12:18:21 INFO: [P#0-T#1] has worker 32 which is processing TRANSFER 1
2022/12/09 12:18:22 ==> REQUEST/RESPONSE (Try=1/20.562932ms, OpTime=25.470912ms) -- RESPONSE SUCCESSFULLY RECEIVED
   GET http://XXXXXXXXXXXX.blob.core.windows.net/edgelocalblobtest/source-downlink-test.txt?XXXXXXXXXX-REDACTEDXXXXXXXXXXXXX&timeout=901
   X-Ms-Request-Id: [21ac8a0f-b01e-0068-2bc8-0b76a4000000]

2022/12/09 12:18:22 INFO: [P#0-T#1] DOWNLOADSUCCESSFUL: /home/edgebuildmachine/DefaultEndpointsProtocol=http;BlobEndpoint=http:/XX.XXX.XXX.XXX:PORT/myedgeblob;AccountName=myedgeblob;AccountKey=XXXXXXXXXX/source-downlink-test.txt
2022/12/09 12:18:22 JobID=3d9328ba-409e-3546-7b46-88fedd3a07e9, Part#=0, TransfersDone=1 of 2
2022/12/09 12:18:22 ==> REQUEST/RESPONSE (Try=1/20.928338ms, OpTime=26.638231ms) -- RESPONSE SUCCESSFULLY RECEIVED
   GET http://XXXXXXXXXXXXXXXX.blob.core.windows.net/edgelocalblobtest/sample-source.txt?XXXXXXXXXXXXXXX-REDACTED-&XXXXXXXXXXXXXX&timeout=901
   X-Ms-Request-Id: [46336642-c01e-0072-15c8-0b177b000000]

2022/12/09 12:18:22 INFO: [P#0-T#0] DOWNLOADSUCCESSFUL: /home/edgebuildmachine/DefaultEndpointsProtocol=http;BlobEndpoint=http:/XX.XXX.XXX.XXX:PORT/myedgeblob;AccountName=myedgeblob;AccountKey=XXXXXXXXXXXX/sample-source.txt
2022/12/09 12:18:22 JobID=3d9328ba-409e-3546-7b46-88fedd3a07e9, Part#=0, TransfersDone=2 of 2
2022/12/09 12:18:22 all parts of entire Job 3d9328ba-409e-3546-7b46-88fedd3a07e9 successfully completed, cancelled or paused
2022/12/09 12:18:22 is part of Job which 1 total number of parts done
2022/12/09 12:18:23 PERF: primary performance constraint is Unknown. States: C:  0, R:  0, W:  0, F:  0, H:  0, B:  0, S:  0, P:  0, Q:  0, D:  0, E:  0, T:  0, GRs: 32
2022/12/09 12:18:23 100.0 %, 2 Done, 0 Failed, 0 Pending, 2 Total, 2-sec Throughput (Mb/s): 0.0003
2022/12/09 12:18:23

Diagnostic stats:
IOPS: 0
End-to-end ms per request: 25
Network Errors: 0.00%
Server Busy: 0.00%

Job 3d9328ba-409e-3546-7b46-88fedd3a07e9 Summary
Files Scanned at Source: 2
Files Scanned at Destination: 21
Elapsed Time (Minutes): 0.0333
Number of Copy Transfers for Files: 2
Number of Copy Transfers for Folder Properties: 0
Total Number Of Copy Transfers: 2
Number of Copy Transfers Completed: 2
Number of Copy Transfers Failed: 0
Number of Deletions at Destination: 0
Total Number of Bytes Transferred: 76
Total Number of Bytes Enumerated: 76
Final Job Status: Completed

But, I can't find which local folder/edge blob location the transferred file resides in. Can you tell me the exact location where I can find the transferred file in edge blob. Please advise me on this matter.

**Comment by JasonYeMSFT** [comment]
Apparently AzCopy is treating your destination as a local path instead of your blob IoT module, as you can see from this segment in the logs
```
DOWNLOADSUCCESSFUL: /home/edgebuildmachine/DefaultEndpointsProtocol=http;BlobEndpoint=http:/XX.XXX.XXX.XXX:PORT/myedgeblob;AccountName=myedgeblob;AccountKey=XXXXXXXXXX/source-downlink-test.txt
```

I haven't used the sync command but I believe the destination should be similar to your source which will look like this
`http://XX.XXX.XXX.XXXX:PORT/myedgeblob/cont1?SASToken`. For example, this is a quote from AzCopy's command line help for sync

```
Sync a single blob:

   - azcopy sync "https://[account].blob.core.windows.net/[container]/[path/to/blob]?[SAS]" "https://[account].blob.core.windows.net/[container]/[path/to/blob]"
```

For one of my edge copy location, it looks like this

"http://my-ip:my-port/myaccountname/cont1/image.png?sv=2021-10-04&st=2022-12-12T05%3A34%3A19Z&se=2022-12-19T05%3A34%3A19Z&sr=c&sp=rl&sig=redacted"

AzCopy strongly discourages using a storage account key for transfers. Especially since your request is going through HTTP protocol, you should consider using a SAS to limit potential risk to leaking credentials. You can generate such a SAS token in Storage Explorer by right clicking the container (cont1) node and select the "Get Shared Access Signature" button.
