### ISSUE TITLE
Unable to Preview xml type files in blob containers

### ISSUE THREAD

**Issue by SarkarSh-nd-wahbe** [microsoft/AzureStorageExplorer#6316]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I'm Unable to preview the xml type files in blob containers

### Desired Solution

I'd like to see the blob contents for xml type files in preview panel

**Comment by MRayermannMSFT** [comment]
Hi @SarkarSh-nd-wahbe as of today, previewing is not automatically enabled for xml files. Please go to Settings (gear on the left) > Services > Storage Accounts > Text preview extensions, and add the xml extension to the list. So like:
```
[
  ".txt",
  ".js",
  ".html",
  ".json",
  ".xml"
]
```
We will evaluate automatically including .xml.

**Comment by SarkarSh-nd-wahbe** [comment]
> 

Thank you @MRayermannMSFT, this really helps!
