### ISSUE TITLE
Provide clear information in product on how proxy works with integrated AzCopy.

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#6317]

**Comment by shraboin** [comment]
@MRayermannMSFT is for updating this portion text:
![image](https://user-images.githubusercontent.com/37669678/205156884-3364df6d-ba05-4983-981f-9023413b9872.png)

**Comment by MRayermannMSFT** [comment]
Additional wording pointing to AzCopy proxy settings has been added. Can/will be found in 1.28
