### ISSUE TITLE
Edit Tag popup on a file fails to load when connected to container via ContainerSAS

### ISSUE THREAD

**Issue by Venu-prahalad** [microsoft/AzureStorageExplorer#6322]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.0

### Architecture

x64

### Storage Explorer Build Number

20221201.1

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Edit Tag on a file fails to load when connected to container via ContainerSAS

### Steps to Reproduce

1. Update to version 1.27.0
![image](https://user-images.githubusercontent.com/32172428/205271959-cc1ee78c-8abe-489c-bede-c9504c586da2.png)

2. use the Blob Container SAS generated for a particular container and connect
3. select a file in the connected container, right click and select Edit Tag. It throws the error  "Value for one of the query parameters specified in the request URI is invalid"

Attached is the detailed error message
[EditTagRESTError.txt](https://github.com/microsoft/AzureStorageExplorer/files/10140274/EditTagRESTError.txt)

### Actual Experience

Getting error as mentioned in steps to reproduce

### Expected Experience

Edit tag popup shows

### Additional Context

It doesnt work only on blob container SAS connection string

**Comment by JasonYeMSFT** [comment]
@Venu-prahalad This might have a similar cause of this issue #6184. You need the "Tag" permission in your SAS/access policy to be able to write tags.

**Comment by Venu-prahalad** [comment]
@JasonYeMSFT I confirm I have granted edit tag permissions. 
![image](https://user-images.githubusercontent.com/32172428/205555953-421d78b7-2c72-4777-8709-428d5ab86ca1.png)

**Comment by JasonYeMSFT** [comment]
Now I see why. Did you enabl "Target Azure Stack API"? It will force Storage Explorer to use a low API version 2017-04-17. The tags related features aren't supported at that API version so the service will reject the requests.

**Comment by Venu-prahalad** [comment]
@JasonYeMSFT Thank you for your help. Yes, I had not turned  "Target Azure Stack API". Moment I do it, It worked. I am closing this issue.
