### ISSUE TITLE
Nothing happens when clicking 'Show in Folder' next to the download activity log of one blob which name contains ':'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6323]
**Storage Explorer Version**: 1.27.0
**Build Number**: 20221201.1
**Branch**: rel/1.27.0
**Platform/OS**: Windows 10
**Architecture**: ia32
**How Found**: Ad-hoc testing
**Regression From**: Previous release (1.24.3)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload .txt file.
3. Right click the uploaded blob -> Clone it with a name contains ':'.
4. Download the blob -> There is a successful activity log.
5. Click 'Show in Folder' -> Check whether succeeds to open a local folder.

## Expected Experience ##
Succeeds to open a local folder.

## Actual Experience ##
Nothing happens.

**Comment by MRayermannMSFT** [comment]
Fix merged into **main**

**Comment by v-xianya** [comment]
Verified this issue on the build main 20221203.4. Fixed.
