### ISSUE TITLE
The blob name is incorrect when opening one blob which name contains ':'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6324]
**Storage Explorer Version**: 1.27.0
**Build Number**: 20221201.1
**Branch**: rel/1.27.0
**Platform/OS**: Windows 10
**Architecture**: ia32
**How Found**: Ad-hoc testing
**Regression From**: Previous release (1.24.3)

## Bug Description ##
1. If there is one letter in the front of the ':' in the blob name. The letter and the colon will not show.
2. If there is more than one letter in the front of the ':' in the blob name. The ':' will show as '%3A'.

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
3. Create a blob container -> Upload .txt file.
4. Right click the uploaded blob -> Clone it with a new name f:ile.txt.
5. Open the file with notepad.
6. Check whether the file name is correct.

## Expected Experience ##
The file name is correct.

## Actual Experience ##
The file name is incorrect.
![image](https://user-images.githubusercontent.com/41351993/205285313-c166b228-69c8-4043-bb20-66ee88b7b75b.png)

## Additional Context ##
On 1.24.3 release.
1. The security dialog pops up when trying to open the blob which name contains ':'.
![image](https://user-images.githubusercontent.com/41351993/205285009-30ad0736-9c43-4dda-8d15-6fa7994ef846.png)
2. Click 'Yes'.
3. Will open a temporary path.
![image](https://user-images.githubusercontent.com/41351993/205285103-8764b76b-de20-4722-b961-d55687e5c4ce.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into **main**

**Comment by v-xianya** [comment]
Verified this issue on the build main 20221203.4. Fixed.



![image](https://user-images.githubusercontent.com/41351993/205561196-325a6d77-cad4-4578-8f6f-40e3b3cd7b2b.png)
