### ISSUE TITLE
SStreams Corrupted on Copy

### ISSUE THREAD

**Issue by ivanthewebber** [microsoft/AzureStorageExplorer#6326]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.26.1

### Architecture

x64

### Storage Explorer Build Number

20221018.5

### Platform

Windows

### OS Version

Windows 11 Enterprise

### Bug Description

Using the Copy+Paste to copy a SStream file (.ss or .sstream extension) corrupts the contents.

### Steps to Reproduce

1. Launch Storage Explorer
2. Open ADL Gen 1 Storage
3. Secondary Click "Copy"
4. Move to another folder
5. Secondary Click "Paste"
6. (Corrupted) stream is written to disk.

### Actual Experience

The new copy is corrupted.

### Expected Experience

The new file is exactly the same (not corrupted).

### Additional Context

SStream is a format used internally at Microsoft similar to Parquet. Generally, it is the input/output of Cosmos SCOPE jobs.

**Comment by MRayermannMSFT** [comment]
@ivanthewebber 

1. Can you elaborate on what you mean by corrupted?
2. Did the copy say it succeeded in the activity log?

Also, on a related note, we recommend moving to ADLS Gen2 as Gen1 is being [retired](https://azure.microsoft.com/en-us/updates/action-required-switch-to-azure-data-lake-storage-gen2-by-29-february-2024/).

**Comment by ivanthewebber** [comment]
1. The contents of the file are altered in such a way that it cannot be read. Likely the file was copied as a text file and not a binary format.
2. Yes

**Comment by MRayermannMSFT** [comment]
@ivanthwebber does 1 mean that it is possible that this is simply an issue of wrong content-type?

**Comment by MRayermannMSFT** [comment]
Discussed offline. As far as I can tell, there is no corrupting happening. File contents are exactly the same after copying. Ivan may try to get more information from the service returning the error.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of new information. Please open a new issue if anything actionable for Storage Explorer comes up.
