### ISSUE TITLE
The string 'Search settings' is not localized in the Settings panel

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6327]
**Storage Explorer Version:** 1.28.0-dev
**Build Number:** 20221203.4
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.0.1 (Apple M1 Pro)
**Reproduce Languages:** All languages
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select '中文(简体)' -> Restart Storage Explorer.
3. Click 'Edit -> Settings' -> Observe the search box.
4. Check whether the string 'Search settings' is localized.

## Expected Experience ##
The string 'Search settings' is localized.

## Actual Experience ##
The string 'Search settings' is not localized.
![image](https://user-images.githubusercontent.com/87792676/205582133-e8167aae-a1cf-4c98-b492-dd2e68ff1c20.png)

**Comment by craxal** [comment]
The strings have been translated, so it looks like we just need to update the package version.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20221209.3. Fixed. So, we are going to close it.
