### ISSUE TITLE
Fail to upload changes for one regular/adls gen2 blob whose name contains ':'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6328]
**Storage Explorer Version**: 1.28.0-dev
**Build Number**: 20221203.4
**Branch**: main
**Platform/OS**: Windows 10
**Architecture**: ia32
**How Found**: Ad-hoc testing
**Regression From**: Previous release (1.24.3)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
3. Create a blob container -> Upload .txt file.
4. Right click the uploaded blob -> Clone it with a new name f:ile.txt.
5. Open the file -> Make some changes -> Save it.
6. Select 'Upload' -> Click 'Apply'.
7. Check whether succeeds to upload the changes.

## Expected Experience ##
Succeed to upload the changes.

## Actual Experience #
Fail to upload the changes.
![image](https://user-images.githubusercontent.com/41351993/205582870-45c5fbcf-d6e9-49b7-9646-cf7bfda57903.png)

## Additional Context ##
On 1.24.3 release.
1. The security dialog pops up when trying to open the blob whose name contains ':'.
![image](https://user-images.githubusercontent.com/41351993/205285009-30ad0736-9c43-4dda-8d15-6fa7994ef846.png)
2. Click 'Yes'.
3. Will open a temporary path.
![image](https://user-images.githubusercontent.com/41351993/205285103-8764b76b-de20-4722-b961-d55687e5c4ce.png)

**Comment by v-kellyluo** [comment]
Update: This issue also reproduces when uploading changes for one regular/adls gen2 blob whose name contains double quotes.

![image](https://user-images.githubusercontent.com/87792676/206147163-bd0c5140-d578-4103-bd35-60fc6b0b8104.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into main.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20221213.2. Fixed.
