### ISSUE TITLE
Javascript error during login with SAS URL

### ISSUE THREAD

**Issue by sunny322** [microsoft/AzureStorageExplorer#6329]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.0

### Architecture

x64

### Storage Explorer Build Number

Build Number: 20221201.1 

### Platform

macOS

### OS Version

12.6.1 

### Bug Description

Hi Team,

I have earlier connected to azure storage accounts and accessed storage accounts. recently, I detached the existing account and then when I tried to login using SAS URL, I'm facing some javascript error. Kindly help. Attached screenshot.

OS : MacOS 12 Monterey
**Storage Explorer** - 
Version: 1.27.0
AzCopy Version: 10.16.2

Platform: macOS
Architecture: x64 
Build Number: 20221201.1 
Commit: 9d5c1618f9 

### Steps to Reproduce

Launch Storage explorer. 
Pop appears wit Javascript error.

### Actual Experience

I have earlier connected to azure storage accounts and accessed storage accounts. Recently, I detached the existing [account,](url) and then when I tried to log in using SAS URL, I'm facing some javascript error. Kindly help. Attached screenshot.

<img width="800" alt="Javascript error" src="https://user-images.githubusercontent.com/5464377/205595862-c863b98a-1b94-4b5c-851e-418bf7550c57.png">

### Expected Experience

Should login successfully

**Comment by JasonYeMSFT** [comment]
@sunny322 Could you move the application to your Applications folder? Apple's AppTranslocation feature will confuse the application with where it resides, as you can see from the randomly generated path.

**Comment by JasonYeMSFT** [comment]
You can also open the app bundle (in terminal) and look for the permission bits of the "Your app bundle/Contents/Frameworks/Microsoft Azure Storage Explorer Helper.app/Contents/MacOS/Microsoft Azure Storage Explorer Helper" and see if it has the "x" (execute) bit set for your user?

**Comment by richardMSFT** [comment]
I tried replicating the issue on my macOS v12.6.1 machine with the 1.27.0 release and couldn't replicate.

**Comment by sunny322** [comment]
It is working now after many trials. I performed below steps to make it work -
I moved the app to the trash and then deleted all the files related to storage explorer and then deleted storage explorer helper from keychain access as well. Then it started connecting to the storage accounts.

Should we not attempt to detach storage accounts?  What happens when we do it? Will it cause any issues in the setup?

Is there a graceful way to uninstall storage explorer?

**Comment by sunny322** [comment]
I launched the keychain access app on mac and then navigated to login keychain, then deleted the storage explorer application password, and then tried to connect to a new storage account after some time and it started working again.
"Attaching and detaching storage accounts should just work properly"  - Not sure why it started giving me a javascript error after doing this activity.
"Optionally, you can delete your user data at /Users/<username>/Library/Application Support/StorageExplorer" -> performed this activity to delete the app but it did not successfully delete the app.

**Comment by JasonYeMSFT** [comment]
@sunny322 To fully remove Storage Explorer, you will need to move the .app folder to trash, which removes the application executables, and delete all files under /Users//Library/Application Support/StorageExplorer which removes all the user data. I still don't understand why removing the application password would have anything to do with the JavaScript error. I am going to close this issue as mitigated. If you have any additional thoughts on why this error might occur, please feel free to post it here.
