### ISSUE TITLE
Not able to add account in Microsoft azure explorer

### ISSUE THREAD

**Issue by RupaManchalla** [Microsoft/AzureStorageExplorer#633]
Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: 105b2061-b669-4b31-92ac-24d304d195dc, Error: {"code":"EPROTO","errno":"EPROTO","syscall":"write"}

**Comment by craxal** [comment]
Please copy and paste [this issue template](https://github.com/Microsoft/AzureStorageExplorer/issues/new) into your initial comment above then fill it out as completely as you can. This will help us help you more effectively!

**Comment by JakeRadMSFT** [comment]
Closing since the template and more information wasn't provided. Please re-open with the template filled out.
