### ISSUE TITLE
The query builder is not closed if using 'Ctrl+R' to refresh the table editor

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6337]
**Storage Explorer Version:** 1.28.0-dev
**Build Number:** 20221206.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.6 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.24.3)

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Open one table -> Click 'Query' -> Press 'Ctrl+R'.
3. There is a refresh icon in the editor.
4. Check whether the query builder is closed.

## Expected Experience ##
The query builder is closed.

## Actual Experience ##
The query builder is not closed.

**Comment by craxal** [comment]
We've decided we'll fix this bug, but we are agreed that this behavior is not very desirable; a refresh could disrupt a user trying to write or build a query.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20230127.10. Fixed.
