### ISSUE TITLE
It is better to update the action item 'View error...' to 'View Error...' for one broken QA app configuration

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6338]
**Storage Explorer Version**: 1.28.0-dev
**Build Number**: 20221206.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.0.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##

1. Expand the 'Application Configurations' node.
2. Select one app configuration -> Pin it to the Quick Access node.
3. Go to the ACCOUNT MANAGEMENT panel -> Remove the azure account that associated with the app configuration.
4. Open the explorer -> The QA app configuration shows as broken.
5. Right click the QA app configuration.
6. Check whether shows 'View Error...' on the context menu.

## Expected Experience ##
Show 'View Error...' on the context menu.
The screenshot for one broke QA storage account:

![image](https://user-images.githubusercontent.com/41351993/205869460-7fcfb252-bd33-43df-8f59-74dbf8fbea99.png)

## Actual Experience ##
Show 'View error...' on the context menu.
![image](https://user-images.githubusercontent.com/41351993/205870881-43b293c5-60d8-43cb-9a0d-eafe09904bfa.png)

**Comment by JasonYeMSFT** [comment]
The string is updated. It will be included the next time we release the extension.

**Comment by v-xianya** [comment]
@JasonYeMSFT could you please help to provide an extension build for us to verify this issue? thanks

**Comment by v-xianya** [comment]
Verified this issue using new extension build. Fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/15484461-0974-412c-a33a-301269b04d0f)
