### ISSUE TITLE
There is no snapshot id in the DFS URL for one ADLS Gen2 blob snapshot

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6339]
**Storage Explorer Version**: 1.28.0-dev
**Build Number**: 20221206.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.0.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Create a snapshot for the blob -> Switch to the snapshots view.
4. Right click the blob snapshot -> Click 'Properties...'.
5. Observe the DFS URL.
6. Check whether there is a snapshot id in the DFS URL.

## Expected Experience ##
There is a snapshot id in the DFS URL.

## Actual Experience ##
There is no snapshot id in the DFS URL.
![image](https://user-images.githubusercontent.com/41351993/205882759-064d894c-fb5d-45b2-9765-7594b5d8c3bb.png)

**Comment by JasonYeMSFT** [comment]
The snapshot is a concept exclusive to the blob endpoint. APIs on the DFS endpoints don't list "snapshot" as a valid parameter.

**Comment by v-xianya** [comment]
@JasonYeMSFT Thank you for the update! Is it possible to remove the DFS URL from the snapshot's properties? Since the APIs on the DFS endpoints don't list "snapshot" as a valid parameter.

**Comment by v-xianya** [comment]
@MRayermannMSFT ok, thank you!
