### ISSUE TITLE
Can't access TableStorage

### ISSUE THREAD

**Issue by Terrence77** [microsoft/AzureStorageExplorer#6343]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27

### Regression From

no

### Architecture

x64

### Platform

Windows

### Bug Description

Unable to retrieve child resources.

Details:
{
  "name": "RestError",
  "message": "getaddrinfo ENOTFOUND myaccount.table.core.windows.net",
  "stack": "RestError: getaddrinfo ENOTFOUND myaccount.table.core.windows.net\n    at ClientRequest.<anonymous> (C:\\Users\\terre\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-table-extension\\dist\\src\\index.js:2:182499)\n    at Object.onceWrapper (node:events:642:26)\n    at ClientRequest.emit (node:events:527:28)\n    at TLSSocket.socketErrorListener (node:_http_client:454:9)\n    at TLSSocket.emit (node:events:527:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "code": "ENOTFOUND",
  "request": {
    "url": "https://myaccount.table.core.windows.net/Tables",
    "headers": {
      "accept": "application/json;odata=minimalmetadata",
      "x-ms-version": "2019-02-02",
      "dataserviceversion": "3.0",
      "accept-encoding": "gzip,deflate",
      "user-agent": "Microsoft Azure Storage Explorer/1.27.0 (win32) azsdk-js-data-tables/13.1.2 core-rest-pipeline/1.9.0 Node/v16.16.0 OS/(ia32-Windows_NT-10.0.19044)",
      "x-ms-client-request-id": "3848fbf4-3c7f-476c-8e2c-317f7b1bdfdd",
      "x-ms-date": "Tue, 06 Dec 2022 22:42:50 GMT",
      "authorization": "Signed SharedKeyLite Redacted="
    },
    "method": "GET",
    "timeout": 0,
    "disableKeepAlive": false,
    "streamResponseStatusCodes": {},
    "withCredentials": false,
    "tracingOptions": {
      "tracingContext": {
        "_contextMap": {}
      }
    },
    "requestId": "3848fbf4-3c7f-476c-8e2c-317f7b1bdfdd",
    "allowInsecureConnection": true,
    "enableBrowserStreams": false
  }
}

### Steps to Reproduce

1. Launch
2. expand account tab
3. attempt to expand Tables 
4. boom, error appears. 

### Actual Experience

1. Launch
2. expand account tab
3. attempt to expand Tables 
4. boom, error appears. 

### Expected Experience

Show the 30 tables I have in my account

### Additional Context
I can access my blob containers fine.

none

**Comment by MRayermannMSFT** [comment]
Hi @Terrence77 please consider enabling system proxy: https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

If that does not work, we recommend you open an Azure support ticket via the portal to help you diagnose why your machine cannot reach your storage account.

**Comment by tpspencer** [comment]
I will take look at system proxy. 
Thank you.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still running into this problem we recommend you open an Azure support ticket via the portal. Alternatively you can open a new issue here.
