### ISSUE TITLE
Fail to reset tag queries which in the address bar when navigating to the Snapshots/Versions view previously

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6345]
**Storage Explorer Version:** 1.28.0-dev
**Build Number:** 20221207.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.0.1 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** Ad-hoc testing
**Regression From:** Previous release (1.21.3)

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create one blob container -> Upload one blob.
3. Right click the blob -> Click 'Edit Tags...' -> Add one tag for the blob.
4. Open the view options panel -> Select the 'Tag Query' -> Input the blob's tag -> Click 'Apply'.
5. Click 'Manage History -> Manage Snapshots/Manage Versions' -> Exit the 'Snapshots/Versions' view.
6. Reset the tag query -> Check whether succeeds to reset tag queries in the address bar.

## Expected Experience ##
Succeed to reset tag queries.

## Actual Experience ##

1. Fail to reset tag queries.
2. Navigate to the Snapshots/Versions view.

## Additional Context ##
Similar issue: [4756](https://github.com/microsoft/AzureStorageExplorer/issues/4756).

**Comment by v-kellyluo** [comment]
Verified this issue on the build main 20221211.1, it still reproduces.

**Comment by v-xianya** [comment]
Verified this issue on the build 20221222.8. Fixed. So, we are going to close it.
