### ISSUE TITLE
Can't access Storage Account's container, FetchError: ETIMEOUT

### ISSUE THREAD

**Issue by connershoop** [microsoft/AzureStorageExplorer#6349]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.0

### Architecture

x64

### Storage Explorer Build Number

20221201.1

### Platform

Windows

### OS Version

Windows 10

### Bug Description

When trying to access the containers of a specific storage account, the following error is thrown.
```

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://<storageAccountName>.blob.core.windows.net/?comp=list&include=metadata failed, reason: connect ETIMEDOUT 20.38.122.132:443",
  "stack": "FetchError: request to https://<storageAccountName>.blob.core.windows.net/?comp=list&include=metadata failed, reason: connect ETIMEDOUT 20.38.122.132:443\n    at ClientRequest.<anonymous> (C:\\Users\\cshoop\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-blob-extension\\dist\\src\\index.js:2:2440800)\n    at ClientRequest.emit (node:events:527:28)\n    at TLSSocket.socketErrorListener (node:_http_client:454:9)\n    at TLSSocket.emit (node:events:527:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "ETIMEDOUT",
  "code": "ETIMEDOUT"
}
```

After this failure, I cannot access the storage account's container in the azure portal either, as the blob endpoint connection will timeout.  Other's can access the same container without issue, the problem is specific to my system.

The only way I've found to resolve this containers broken state is to restart my local router.

### Steps to Reproduce

1. Launch App
2. expand storage account
3. trying to expand blob containers -> loading -> throws error

### Actual Experience

Storage explorer breaks my connection to a storage account's container

### Expected Experience

I can access a storage account's container

### Additional Context

Duplicate: https://github.com/microsoft/AzureStorageExplorer/issues/5652

**Comment by MRayermannMSFT** [comment]
@connershoop if you cannot access the container via Storage Explorer or Azure Portal from your machine, there is likely some sort of firewall/network configuration on your storage account blocking the connection. We recommend you open an Azure support ticket for this issue to help you diagnose what is wrong. This issue seems likely beyond the scope of Storage Explorer exclusively.

**Comment by connershoop** [comment]
Thank you, you are exactly correct, I have reproduced this problem via using the in azure storage explorer. Please feel free to close this
