### ISSUE TITLE
It would be better to update the title of the dialog prompted by clicking 'Save query as...' to 'Save query as'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6352]
**Storage Explorer Version**: 1.28.0-dev
**Build Number**: 20221208.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.0.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Open query builder.
3. Click 'Save query as...' -> There is a system dialog for choosing a save location.
4. Observe the title of the system dialog.

## Expected Experience ##
It would be better to update the title to 'Save query as'.

## Actual Experience ##
The title is 'Save query'.

**Comment by v-kellyluo** [comment]
This issue still reproduces on the build 20230307.3, will verify it on the newer build.

**Comment by v-xianya** [comment]
Because the windows build is failed. Will verify this issue on a newer build.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230413.5. Reproduce. So, we are going to reopen it and verify it on a new build.

**Comment by craxal** [comment]
There was a bad package update. Published a new version.
