### ISSUE TITLE
File Previewing, missing file formats (Version 1.27.0)

### ISSUE THREAD

**Issue by BastiaanA** [microsoft/AzureStorageExplorer#6353]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

The preview doesn't work for JSON files

### Desired Solution

The preview will work for JSON files

### Additional Context

When the content_type = application/json, please show a preview of the file. In plain text, or (even better) in readable formatted json

**Comment by MRayermannMSFT** [comment]
Hi @BastiaanA by default JSON files should be previewable, even if there is a application/json content-type. Can you let us know:

- What version of Storage Explorer you are using?
- In what way do you see JSON files not being previewable/how is previewing a JSON file not working for you?

![image](https://user-images.githubusercontent.com/21112697/206532120-93c0f24b-9307-448f-bf1c-223faf350cd4.png)

**Comment by BastiaanA** [comment]
Hi,
I am using the latest version (1.27.0),
The Preview button is grayed out for many. I've attached to image:
![image](https://user-images.githubusercontent.com/16972868/207063856-29fb8219-a8ae-4fe3-b4d7-5be59410344f.png)
No file extension, but ContentType=application/json

and 
![image](https://user-images.githubusercontent.com/16972868/207064362-629d967e-d9a2-454b-8205-34d153ca6e74.png)
File extension = csv, ContentType=application/octet-stream

**Comment by MRayermannMSFT** [comment]
@BastiaanA for now you can do the following:
1. Go to settings (gear on the left)
2. Go to services > storage accounts > text preview extensions
3. Add both `""` and `".csv"` to the list

@JasonYeMSFT let's get `application/json` added to the content type list. Also let's use this issue as further reason to implement the less-restrictive previewing experience.

**Comment by BastiaanA** [comment]
Workaround works. Preview is a very nice feature on the StorageExplorer; it's that additional spice for my team to start using Storage Explorer over the Azure Portal.

For me, you can close this issue, but if you want to keep it open for the addition of application/json to the content type list, it is fine with me.

**Comment by JasonYeMSFT** [comment]
We now allow previewing a text file if it has a content type and it matches any of these content types:

-   "text/calendar"
-   "text/css"
-   "text/csv"
-   "text/html"
-   "text/javascript"
-   "text/plain"
-   "text/xml"
-   "application/xml"
-   "application/json"

Please note that the json documents are previewed as is. We have a feature request investigating how to support formatting json documents in the preview panel. If you have suggestions on how you would like it be implemented please comment on that issue. https://github.com/microsoft/AzureStorageExplorer/issues/6195
