### ISSUE TITLE
Version 1.27.0 - Attached Storage Accounts not showing account names

### ISSUE THREAD

**Issue by jimmywim** [microsoft/AzureStorageExplorer#6355]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.0

### Architecture

x64

### Storage Explorer Build Number

20221201.1

### Platform

Windows

### OS Version

Windows 11 22H2

### Bug Description

After upgrading Azure Storage Explorer to 1.27.0, my attached Storage Accounts no longer show their names.

![image](https://user-images.githubusercontent.com/3036301/206702423-bdbfa92a-f5ac-4dba-88c1-23b723b85962.png)

After relaunching, the storage account names re-appear Ok.

### Steps to Reproduce

1. Update Storage Explorer after already having attached accounts
2. When it relaunches, observe an error popup (the text of the error mentioned an undefined reference reading `.toLower()`)*
3. Expand "Emulator & Attached" -> "Storage Accounts"

*I tried to relaunch again to get a screenshot of the error popup, but the issue went away, and the list of storage accounts appears as expected.

### Actual Experience

The list of attached storage accounts do not show their name.

When you re-launch Storage Explorer, the account names appear.

### Expected Experience

Storage accounts show their correct details on first launch.

### Additional Context

This is a minor bug, as relaunching fixed the issue for me.

I only noticed a relaunch fixed it as I tried to get the initially error dialog to show whilst filling out this bug report.

**Comment by craxal** [comment]
@jimmywin I suspect this is related to the work we did to enable renaming connections. We had to change the format we use to save attachment data a bit, but Storage Explorer should automatically convert the data to the appropriate format when it first reads that data.

Can you share your app log files with us? Are there any additional error details you can see if you open the developer tools with F12 and select the Console tab?

Can you try reproducing by doing the following (you may want to try this on a different machine or with a different user account):
1. Install a version of Storage Explorer prior to 1.27.0.
2. Launch Storage Explorer and attach a storage account.
3. Install Storage Explorer 1.27.0.
4. Launch Storage Explorer and check for the attached storage account.

**Comment by craxal** [comment]
@jimmywin Just so you know, I have been able to reproduce the issue on my end using the steps I detailed earlier.

**Comment by craxal** [comment]
Looks like the problem is due to a race condition. There's some asynchronous stuff that needs to be done when first loading up the attachment data, which includes the data format update I mentioned earlier. Apparently, that's too slow for the explorer tree. So we just need to make sure we await the initialization when retrieving attachments for tree nodes.

**Comment by jimmywim** [comment]
> Looks like the problem is due to a race condition. There's some asynchronous stuff that needs to be done when first loading up the attachment data, which includes the data format update I mentioned earlier. Apparently, that's too slow for the explorer tree. So we just need to make sure we await the initialization when retrieving attachments for tree nodes.

Sound - sorry I didn't get around to the repro, got distracted by other stuff today.

Good to hear it's a (relatively) straightforward fix!
