### ISSUE TITLE
File Preview Head

### ISSUE THREAD

**Issue by Kenneth-Fries** [microsoft/AzureStorageExplorer#6356]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

File Preview would benefit if larger files can be viewed using HEAD

### Desired Solution

I would like to have a function like HEAD to preview the first n lines of a file.  This should work for files of any size, and have an option to show hidden characters.

### Alternatives and Workarounds

Maybe an alternative is downloading the head -n lines for preview?  That might be easier than downloading whole files just to run bash for viewing the top of large files.  

### Additional Context

I frequently have to download files just to use bash for the purposes of running cat -A filename | head | column ...  It would be nice if file explorer had the ability to at least preview files using something with functionality like cat -A filename.txt | head -n 200.  The -A option would be really nice to allow the option for viewing hidden characters like carriage returns, newlines, tabs, non utf8 characters.  I work with files up to several GB, so it would be nice to at least see the head to see if a file is what we expect, or how we need to treat it.

**Comment by MRayermannMSFT** [comment]
@Kenneth-Fries in 1.28 we're going to enable partial previewing for text previews by showing the first 10MB of any file larger than 10MB. We'll look into the more involved feature of being able to denote `n` number of lines/bytes in the future/if more users come asking for that type of advanced functionality.

**Comment by MRayermannMSFT** [comment]
Code has been merged to allow for partial previewing of files larger than 10MB. Will be available in 1.28.0.
