### ISSUE TITLE
The blob name is incorrect in the Rename File dialog if there is one letter in the front of the ':' in the blob name

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6357]
**Storage Explorer Version:** 1.28.0
**Build Number:** 20221211.1
**Branch:** main
**Platform/OS:** Windows 10
**Architecture:** ia32
**How Found:** Ad-hoc testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload a blob.
3. Right click the uploaded blob -> Clone it with a new name t:es.csv.
4. Right click the cloned blob -> Click 'Rename...'.
5. Check whether the blob name is correct.

## Expected Experience ##
The blob name is correct.

## Actual Experience ##
The blob name is incorrect.
![image](https://user-images.githubusercontent.com/87792676/207012048-9c8b818e-3d8a-4f9a-b840-49bc01b406dc.png)

## Additional Context ##
This issue doesn't reproduce if there is more than one letter in the front of the ':' in the blob name.
![image](https://user-images.githubusercontent.com/87792676/207012080-182bb225-4d46-4979-b31b-9f627dc06aee.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into main

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20221216.1. Fixed.
![image](https://user-images.githubusercontent.com/87792676/208060826-c307a23b-e7d8-4dcb-9520-1ce52bf4ace0.png)
