### ISSUE TITLE
quickaccess problems

### ISSUE THREAD

**Issue by aftonstrale** [microsoft/AzureStorageExplorer#636]
**Storage Explorer Version**: 1.4.1
**Platform/OS Version**: Windows
**Architecture**: ia32
**Regression From**: varies, see details below

[1]
For every new update, patch or release of this tool, I need to recreate my quick access short cuts. This makes no sense at all, and I would appreciate if you could save the settings during upgrade.

This item has never worked.

[2]
Second item is the adding items to the quick access. I have several subscriptions for different region of the same solution, i.e. the same name exist in several subscriptions. Here are two problems

2a) If I add quick access to an item from one subscription, I can no longer add an item with the same name from another subscription. Nothing really happens, no error message, zip, nada, nothing. 

This has worked in previous release (i.e. before the recent bug when no items could be added at all)

2b) Name of shortcut. Today the quick access name is exactly the same as the item it is referring to. Here it would be good to set a custom display name for the short cut only (not the target item), to show easier which subscription it will point at.

This is a new feature request and have never worked before.

**Comment by craxal** [comment]
Your Quick Access items should be preserved between updates. For comparison, do you have any SAS/connection string attachments? Those connections should also be saved across updates. You should be able to see this data if you do the following:
1. Hit F12 and select the **Application** tab.
2. Select **Storage** > **Local Storage** > **file://**
3. Look for keys named "StorageExplorer_CustomConnections_*_v1" or "StorageExplorer_InPlaceQuickAccessItems_v1". The custom connection keys will just contain JSON formatted arrays of the names of your connections. The Quick Access key will contain a long string of encrypted data. We store the encryption key for this in the Credentials Manager, which should only need to be generated once.

For 2a, see #189.

For 2b, see #22.

**Comment by Rajas-Git** [comment]
Totally agree with @aftonstrale on [1]. My quick access shortcuts have broken with the latest update. I can't say that they break for every updates but that break very often with updates. They show up with a red cross mark after the update and I have to re-add those.

**Comment by craxal** [comment]
@aftonstrale, @Rajas-Git, to clarify, your Quick Access items still appear in the tree, correct? The problem is the links are just broken?

**Comment by Rajas-Git** [comment]
Yes, that's correct. 
I opened [another issue](https://github.com/Microsoft/AzureStorageExplorer/issues/638) for bug where Quick Access items do not appear at all in new window

**Comment by aftonstrale** [comment]
@craxal 
"Your Quick Access items should be preserved between updates."
Yes, that is the whole idea why I file this ticket. Because reality does not meet expectations here.


"For comparison, do you have any SAS/connection string attachments? Those connections should also be saved across updates."

I have subscriptions set-up that are preserved. This has worked fine in most versions.

However the quick access items are never preserved. Never. I am getting quite tired to need to add these back again for every update that is coming through.


"Do you notice any errors in the dev tools console when starting up after an update? "
Well, I have not been aware of this until now. And for the moment I have just recently re-added my items so the break-point is never hit. But I will repeat again after next update and when the problem occur again.


"For 2a, see #189."

My problem is not about opening items in the tree structure. My problem is about being allowed to add items to quick access when names are similar.
This have been working in previous release.


"For 2b, see #22."

Fair enough.
Do you have any ETA for this?
(After all, it is a quite old ticket you refer to.)

**Comment by aftonstrale** [comment]
@craxal 
"to clarify, your Quick Access items still appear in the tree, correct? The problem is the links are just broken?"

No not for me. After an update, the items are completely gone from quick access. 
And I have a hard time remember which items I want to add back.

**Comment by aftonstrale** [comment]
By the way,

I cannot judge if the problem exist in current release, since my quick access items were gone in the other recent update where it was introduced that I could no longer add quick access items.

And since there were nothing to keep in this current bug-fix then I cannot tell if problem still exist.

**Comment by yurasikone** [comment]
Just installed 1.6.1 and Quick Access links do not work anymore.   :( 
![image](https://user-images.githubusercontent.com/21167537/50246531-7aac6780-038a-11e9-9b68-437332c586db.png)

**Comment by MRayermannMSFT** [comment]
We're not seeing this repro anymore. We'll make sure to double check this going forward in the future.
