### ISSUE TITLE
Explorer tree after update disappears

### ISSUE THREAD

**Issue by vmachacek** [microsoft/AzureStorageExplorer#6360]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.0

### Architecture

x64

### Storage Explorer Build Number

20221201.1

### Platform

Windows

### OS Version

Windows 10

### Bug Description

after i opened tool after new update all my connections are gone

### Steps to Reproduce

Launch
.. no connections are present  although I had a ton before

### Actual Experience

Connections disappeared

### Expected Experience

Connections would still be there

**Comment by craxal** [comment]
@vmachacek 
* What exactly do you experience when you say your connections have disappeared? Can you share any screenshots of the issue?
* Have you tried opening Storage Explorer a second time to see if they are still absent?
* Can you follow the steps up to step 3 as shown in the [troubleshooting guide for connection issues](https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows#error-occurred-while-adding-new-connection-typeerror-cannot-read-property-version-of-undefined)? Can you share the data you see there?
* Do your connections come back when reverting to the previous version of Storage Explorer?

**Comment by craxal** [comment]
Possibly related to #6355.

**Comment by vmachacek** [comment]
Sorry for misleading title, what happened was when I click the first tab on the left menu which has a icon of tree structure 
![image](https://user-images.githubusercontent.com/2987885/207669932-785a2895-278a-4fbc-94fb-6d6584f61f77.png)
the panel right next to it was empty - which is listing storage accounts? I called that connections previously.

When that happened I just added the ones I needed for the current task

When I opened the Storage Explorer second time the state was same as when I exited last time

**Comment by craxal** [comment]
@vmachacek Sorry, I think it's still a little unclear what problem you're experiencing.

You can click the explorer tree button to toggle the panel on and off:
<img width="103" alt="image" src="https://user-images.githubusercontent.com/3473026/207936919-2ed929a3-9067-446e-a7a4-c49bc20992ff.png">
<img width="379" alt="image" src="https://user-images.githubusercontent.com/3473026/207936975-07d4ede2-d0a5-4d9d-b60c-3b69693f89e5.png">

Are you saying that the entire panel doesn't show when it's toggled on? Or is the panel visible, but there's nothing in it? Or do you see the search bar and links, but there are no tree nodes it it?

Also, when you say you "added the ones I needed for the current task", what do you mean? Are you saying that you attached to a storage account? A specific resource?

**Comment by vmachacek** [comment]
the panel shows fine, the problem it was empty and I had to manually add the storage accounts

**Comment by craxal** [comment]
@vmachacek Do you normally sign in with your Azure account? If so, did you try signing in again? Or do you normally attach to individual accounts (manually add accounts, as you say)?

**Comment by craxal** [comment]
@vmachacek We understand. Our follow-up questions are just us trying to clarify the details, get more information, and see if they are related to other issues we are aware of. Did _all_ of your accounts disappear? Or just some of them?

Just so you know, we are aware of two issues which may both be the same thing you're experiencing. We are releasing a new version very soon that should fix these issues (see #6360, #6364).

**Comment by vmachacek** [comment]
sweet, yes, all of the accounts disappeared

**Comment by craxal** [comment]
@vmachacek We have released 1.27.1. Can you install that version and see whether your issue is resolved?

**Comment by craxal** [comment]
@vmachacek Did you install 1.27.1. Does your issue persist?

**Comment by vmachacek** [comment]
I did, and nothing bad happened 👍
