### ISSUE TITLE
All accounts (under "Account Management") are gone after upgrade to v1.27.0

### ISSUE THREAD

**Issue by Jaans** [microsoft/AzureStorageExplorer#6364]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.0

### Regression From

-1

### Architecture

x64

### Storage Explorer Build Number

20221201.1

### Platform

Windows

### OS Version

Windows 10

### Bug Description

I had multiple accounts set up in ASE under the "Account Management" section.
After the upgrade to version 1.27.0, all of them are gone. There are no entries there at all.
I tend to install the latest version when prompted, so I was *NOT* running an old version.

### Steps to Reproduce

1. Launch Storage Explorer
2. Cannot access Azure blob stores because all of the entries under "Account Management" are gone after installing latest version of ASE 1.27.0 (upon being prompted to do so).

### Actual Experience

Nothing - no accounts there. Now I need to set them all up again.

### Expected Experience

Retain my existing storage account when upgrading.

**Comment by MRayermannMSFT** [comment]
Hi @Jaans , in 1.27 our auth library moved to a new account store format. From what we understand, there should have been no loss of sign in state. We're working with them now to figure out what went wrong. For now you'll need to re-sign in though. :(

**Comment by Jaans** [comment]
Thank you for acknowledging.

**Comment by MRayermannMSFT** [comment]
Merged a new auth library which doesn't have the broken porting of account stores.
