### ISSUE TITLE
Error:Hub Controller process exited prematurely with exit code 25 (ConfigurationError)

### ISSUE THREAD

**Issue by ieldevera** [microsoft/AzureStorageExplorer#6369]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.0

### Architecture

x64

### Platform

Windows

### OS Version

Windows 11

### Bug Description

I'm facing an issue regarding authentication library failed to start properly:

![image](https://user-images.githubusercontent.com/120625791/207793766-fff31987-75eb-4263-8782-e35105d9cfb5.png)

### Steps to Reproduce

1. Launched to Storage Explorer

### Actual Experience

After launching the Storage Explorer, I'm greeted with the issue regarding authentication library failed to start properly.

![image](https://user-images.githubusercontent.com/120625791/207793766-fff31987-75eb-4263-8782-e35105d9cfb5.png)

[logs.zip](https://github.com/microsoft/AzureStorageExplorer/files/10234503/logs.zip)

**Comment by MRayermannMSFT** [comment]
Hi @ieldevera, in order for us to investigate this, could you please turn on fusion log, try running storage explorer, and then upload the log files in a response? We will need you to enable/log all assembly bindings not just assembly binding failures.

You can find instructions for fusion log here: https://docs.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer 

Thanks.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem, we recommend you open an Azure support ticket from the portal. Alternatively you can open a new issue here.
