### ISSUE TITLE
Get Subscriptions Failure Details in Azure Storage Explorer

### ISSUE THREAD

**Issue by kmcinally** [microsoft/AzureStorageExplorer#637]
When trying to add an Azure account to Azure Storage Explorer I am getting the below error message. My co-workers are able to get the subscriptions to this Azure account, using the same version of Azure Storage Explorer. Has anyone else come across this error before?

Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: f8cdef31-a31e-4b4a-93e4-5f571e91255a, Error: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"51.140.203.121","port":443}
Tenant Id: 6ff18d7a-7d9e-4063-8fbb-89f033f4ae83, Error: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"51.140.203.121","port":443}
Tenant Id: 2b7f516e-1b14-479e-8d65-ac50c9127e5d, Error: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"51.140.203.121","port":443}
Tenant Id: e3890620-5c12-4015-ad5c-c552b7922027, Error: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"51.140.203.121","port":443}

**Comment by craxal** [comment]
Possible Azure has just been weird the last few days? Have you tried removing the account and adding it again? You could also try deleting the .devaccounts file and signing back in.

**Comment by djouallah** [comment]
same problem here,
Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: 7f68c7d0-74e8-4a66-84b7-fa27e36251b8, Error: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"13.75.216.21","port":443}

windows 10, EXPLORER 1.6

**Comment by LukaszBialek** [comment]
Same here: Has anybody solved the issue?

Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: f25493ae-1c98-41d7-8a33-0be75f5fe603, Error: {
  "name": "Error",
  "message": "getaddrinfo ENOTFOUND management.azure.com management.azure.com:443",
  "__zone_symbol__error": {
    "originalStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
    "zoneAwareStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)"
  },
  "stack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
  "originalStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
  "zoneAwareStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
  "__zone_symbol__stack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
  "__zone_symbol__name": "Error",
  "__zone_symbol__message": "getaddrinfo ENOTFOUND management.azure.com management.azure.com:443",
  "__zone_symbol__originalStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
  "__zone_symbol__zoneAwareStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
  "code": "ENOTFOUND",
  "errno": "ENOTFOUND",
  "syscall": "getaddrinfo",
  "hostname": "management.azure.com",
  "host": "management.azure.com",
  "port": 443
}
Tenant Id: b1e3937e-ba70-479d-a387-38ca10865f34, Error: {
  "name": "Error",
  "message": "getaddrinfo ENOTFOUND management.azure.com management.azure.com:443",
  "__zone_symbol__error": {
    "originalStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
    "zoneAwareStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)"
  },
  "stack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
  "originalStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
  "zoneAwareStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
  "__zone_symbol__stack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
  "__zone_symbol__name": "Error",
  "__zone_symbol__message": "getaddrinfo ENOTFOUND management.azure.com management.azure.com:443",
  "__zone_symbol__originalStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
  "__zone_symbol__zoneAwareStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:172:18)\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
  "code": "ENOTFOUND",
  "errno": "ENOTFOUND",
  "syscall": "getaddrinfo",
  "hostname": "management.azure.com",
  "host": "management.azure.com",
  "port": 443
}

**Comment by craxal** [comment]
Is anyone working behind a network proxy?

**Comment by LukaszBialek** [comment]
Yes, indeed this was the issue.
I used custom proxy settings. It works now.
Thanks!
