### ISSUE TITLE
Build custom storage explorer extensions

### ISSUE THREAD

**Issue by Venu-prahalad** [microsoft/AzureStorageExplorer#6379]
Hi,
I am using blob containers to store files to process/processed. I am in need to provide the tag details as a column in the storage explorer view and allow users to sort on it. Right now I have to apply a tag filter to obtain the blobs which are cumbersome and I want to make it simpler. 
My actual use case is: I apply tag 'ProcessedDate' and 'ProcessingStatus' tags on the blobs. Now if I want to visually see the file processing statuses it's hard. 
I believe just allowing to add of new custom columns which would show the tag values if present would be a great simplification to make for the user. 
Can you please help in guiding me on how to write my custom extension to achieve this?

Regards,
Venu C P

**Comment by MRayermannMSFT** [comment]
Hey @Venu-prahalad sorry to take so long to get to this. Two things:
1. What you would like to do is not supported by our current extensibility model.
2. Opening the extensibility model to 3rd parties is currently on hold. We'll make a formal announcement if that ever changes.

Sorry again to take so long to get back to you.
