### ISSUE TITLE
Top of queue explorer is cut off when opening listing for long messages

### ISSUE THREAD

**Issue by OzBob** [microsoft/AzureStorageExplorer#6380]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.0

### Regression From

1.26.0

### Architecture

x64

### Storage Explorer Build Number

20221201.1

### Platform

Windows

### OS Version

windows 10; build 19045.2364

### Bug Description

similar to #5806.
when the entities are long (have /r/n in them), the first view of the whole queue in a non-maximised AzStorageExplorer, has the top of queue explorer cut off.

### Steps to Reproduce

1. open a queue with more than 4 items, where each item has a field that is more than 8 lines and each line is formatted JSOn with /r/n, more items than would display on the visible form, so that there are vertical scrollbars

### Actual Experience

1. loading:
![image](https://user-images.githubusercontent.com/1796771/208342340-74580a4b-e24a-4640-8f72-779eec75ecde.png)
2. result
![image](https://user-images.githubusercontent.com/1796771/208342267-bb40be08-6a57-4169-9fcd-2faae968e56f.png)
3. maximise the window - the correct header icons appear
4. un-maximise the window - the correct header icons remain.

**Comment by craxal** [comment]
The queue explorer is still using it's own copy of the data table code. I think the best solution here would be to update the queue explorer to use our shared table component. The queue extension is fairly behind other extension, though, so it will take some time update everything.

**Comment by craxal** [comment]
@OzBob Can you go into a little more detail about how you got your messages to spread across multiple lines? I seem to be having trouble reproducing.

**Comment by OzBob** [comment]
just guessing but I believe it might be a Newtonsoft Json FOrmat option to have it 'pretty printed'. with line breaks.  you could try putting in /n or /r/n manually... 
i'll have a look.

**Comment by craxal** [comment]
Unfortunately, manually inserting "\r\n" did nothing, because the backslash isn't interpreted specially when typing it into a `<textarea>`.

**Comment by craxal** [comment]
See #6455 for tracking queue explorer work.
