### ISSUE TITLE
Roaming Profiles and Storage Explorer don't seem to work

### ISSUE THREAD

**Issue by iaingblack** [microsoft/AzureStorageExplorer#6381]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.0

### Architecture

x64

### Storage Explorer Build Number

20221201.1

### Platform

All

### OS Version

Windows 10

### Bug Description

We have a client trying to use Roaming Profiles so that connections in Azure Storage Explorer follow them around and there are issues, To replicate this, I manually zipped and copied the ```C:\Users\<username>\AppData\Roaming\StorageExplorer``` folder and copy it to a new machine and logged in as the same user, I expected that the application would read this roaming data and load any existing connections etc... into Azure Storage Explorer. But it seems like this does not work. The connections have broken link graphic and I get an error of;

 'Load Storage Account Error' and the message 'The custom connection with ID 'my_connection_name' cannot be found.'

Is this a supported scenario? Users with Roaming Profiles being able to launch Azure Storage Explorer from another machine and maintain their connections?

The error log records this also

```[2022-12-19T10:59:02.188Z] (main:11124) <INFO> Resolved resource module './resources/ErrorDetailsDialog': 'C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\resources\ErrorDetailsDialog.json'```

### Steps to Reproduce

1. Launch storage explorer
2. Add a connection from a blob
3. Close storage explorer
4. Copy contents of C:\Users\<username>\AppData\Roaming\StorageExplorer to another machine
5. Launch storage explorer
6. Attempt to connect to the storage account

### Actual Experience

See screenshot. Past connections appear in a certain sense, but are unusable

![image](https://user-images.githubusercontent.com/5280024/208410201-4a3b1b74-371c-4743-ac4d-970c3048966a.png)

### Expected Experience

I would expect the connection to work

### Additional Context

I could not find any documentation on Roaming Profile support for Azure Storage Explorer or any past issues. Is there any guidance on if this is a supported scenario or other items/regkeys that would have to also be synced?

**Comment by JasonYeMSFT** [comment]
We don't support roaming these data. First of all, the local attachments aren't stored in the user profile data. They are stored in your system's local credential manager. It is not easy to manually copy those data from there. Although not directly related, this section explains where these local attachments are stored if you are interested [find local attachments](https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows#error-occurred-while-adding-new-connection-typeerror-cannot-read-property-version-of-undefined). Secondly, some data in your user profile data are encrypted by a key in your local credential store. If you simply copy the data without setting the key the new profile won't work as expected. We have a feature request for exporting Quick Access items https://github.com/microsoft/AzureStorageExplorer/issues/2880. We can investigate how that can also be applied to user profiles.

**Comment by iaingblack** [comment]
Understandable, many thanks for the detailed explanation.
