### ISSUE TITLE
One or more accounts requires reauthentication

### ISSUE THREAD

**Issue by graham-benson-alinta** [microsoft/AzureStorageExplorer#6384]
Continually have to re-authenticate to view the containers in Storage Explorer  - 

Receiving the following error:
{
  "message": "\"{\\n  \\\"message\\\": \\\"\\\\\\\"No matching account found in MSAL cache\\\\\\\"\\\"\\n}\""
}

**Comment by MRayermannMSFT** [comment]
@graham-benson-alinta at most you should see this error once per account after upgrading to 1.27. If you're finding that you are continually seeing this error, can you please try:

1. Go to: Help -> Reset
2. Uncheck all items except "Authentication"
3. Click "Reset"
4. Restart storage explorer
5. Sign in again

And let us know if that resolves the issue.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem, we recommend you open an Azure support ticket from the portal. Alternatively you can open a new issue here.

**Comment by DarkNoir** [comment]
Resetting as per @MRayermannMSFT  fixed this issue for me on 1.37. 

Thanks!
