### ISSUE TITLE
Unable to retrieve child resources.

### ISSUE THREAD

**Issue by elchgarahmed** [microsoft/AzureStorageExplorer#6385]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.1

### Architecture

i86

### Platform

Linux (snap)

### OS Version

ubuntu 20.04

### Bug Description

Error when i tray to display the content on blob containers:

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to http://azure:10000/devstoreaccount1?comp=list&include=metadata failed, reason: getaddrinfo EAI_AGAIN azure",
  "stack": "FetchError: request to http://azure:10000/devstoreaccount1?comp=list&include=metadata failed, reason: getaddrinfo EAI_AGAIN azure\n    at ClientRequest.<anonymous> (/snap/storage-explorer/44/resources/app/node_modules/se-blob-extension/dist/src/index.js:2:2440800)\n    at ClientRequest.emit (node:events:527:28)\n    at Socket.socketErrorListener (node:_http_client:454:9)\n    at Socket.emit (node:events:527:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "EAI_AGAIN",
  "code": "EAI_AGAIN"
}

### Steps to Reproduce

1. connect to storage of local docker
2. 2. click in the blob containers

### Actual Experience

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to http://azure:10000/devstoreaccount1?comp=list&include=metadata failed, reason: getaddrinfo EAI_AGAIN azure",
  "stack": "FetchError: request to http://azure:10000/devstoreaccount1?comp=list&include=metadata failed, reason: getaddrinfo EAI_AGAIN azure\n    at ClientRequest.<anonymous> (/snap/storage-explorer/44/resources/app/node_modules/se-blob-extension/dist/src/index.js:2:2440800)\n    at ClientRequest.emit (node:events:527:28)\n    at Socket.socketErrorListener (node:_http_client:454:9)\n    at Socket.emit (node:events:527:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "EAI_AGAIN",
  "code": "EAI_AGAIN"
}

**Comment by MRayermannMSFT** [comment]
Hi @elchgarahmed please consider enabling system proxy: https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

If that does not work, we recommend you open an Azure support ticket via the portal to help you diagnose why your machine cannot reach your storage account.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem, we recommend you open an Azure support ticket from the portal. Alternatively you can open a new issue here.
