### ISSUE TITLE
Succeed to preview one blob whose size is larger than 10 MiB

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6386]
**Storage Explorer Version:** 1.28.0-dev
**Build Number:** 20221221.5
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.0.1 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.27.1)

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob with .txt file extension whose size is larger than 10 MiB.
3. Right click the blob -> Click 'Preview'.
4. Check whether there is a failed activity log indicating 'The blob size must be less than 10 MiB'.

## Expected Experience ##
There is a failed activity log indicating 'The blob size must be less than 10 MiB'.
![image](https://user-images.githubusercontent.com/87792676/209085880-15b94a8d-6a39-4d05-963c-c1ef5e4cf88d.png)

## Actual Experience ##
Succeed to open the preview tab.
![image](https://user-images.githubusercontent.com/87792676/209086066-41f585dc-963c-47e7-b944-36b0364325af.png)

## Additional Context ##
The screenshot under one file share:
![image](https://user-images.githubusercontent.com/87792676/209087647-31654a1c-b9ca-49ce-93a5-20585a36e813.png)

**Comment by MRayermannMSFT** [comment]
By design. We're now allowing to preview text files regardless of size, however, only up to the first 10MB of the file. As you can see, we show a banner indicating that the preview is only partial.
