### ISSUE TITLE
 last-modified field values at the folder level.

### ISSUE THREAD

**Issue by tlnarayana** [microsoft/AzureStorageExplorer#6387]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I'm unable to view last-modified field values at the folder level. The same holds true for files. 

### Desired Solution

Can the folder level's last modified field values be added? 

### Alternatives and Workarounds

NA

### Additional Context

NA

**Comment by MRayermannMSFT** [comment]
Hi @tlnarayana, due to how the blob service works, there is no concept of a last modified for folders. For non-gen2 blob containers, folders are entirely virtual/they are not real. Thus there is no last modified to track.
