### ISSUE TITLE
Unable to get local issuer certificate

### ISSUE THREAD

**Issue by markpisc** [microsoft/AzureStorageExplorer#6389]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.1

### Regression From

It was at some point, but I don't know which one.  Haven't used it in awhile

### Architecture

i86

### Storage Explorer Build Number

20221220.2

### Platform

Windows

### OS Version

Windows 10

### Bug Description

I get a message that says "Could not access resources for this tenant.  You may need to re-authenticate".  I tried re-authenticating but get the same message.  

Error Details:
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"unable to get local issuer certificate\\\",\\n  \\\"stack\\\": \\\"Error: unable to get local issuer certificate\\\\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1532:34)\\\\n    at TLSSocket.emit (node:events:527:28)\\\\n    at TLSSocket._finishInit (node:_tls_wrap:946:8)\\\\n    at ssl.onhandshakedone (node:_tls_wrap:727:12)\\\",\\n  \\\"code\\\": \\\"UNABLE_TO_GET_ISSUER_CERT_LOCALLY\\\"\\n}\""
}

About screen:
![image](https://user-images.githubusercontent.com/49036044/209222526-3e405897-6517-416d-82a3-eed886513899.png)

### Steps to Reproduce

1. Launch the application
2. click on my account
3. 
![image](https://user-images.githubusercontent.com/49036044/209222638-f02b7a36-97cd-4cfe-bf94-30a6602b7d95.png)

### Actual Experience

![image](https://user-images.githubusercontent.com/49036044/209222688-4f5b7b92-64f2-428b-967e-1b862a9215d7.png)

### Expected Experience

Get logged in and see my Storage Accounts

### Additional Context

I have another user in my company that is getting the same error.  Are there any specific certficates we need to put on our machines?

**Comment by MRayermannMSFT** [comment]
Hi @markpisc please consider enabling system proxy: https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by markpisc** [comment]
Thank you very much!!  That fixed it.

Mark Collins
Sr. IT Application Software Developer
Daikin Applied
Preferred method of contact, in order:
Microsoft Teams
612.581.7433 (cell)
763.553.5307 (office)
***@***.******@***.***> | www.daikinapplied.com<http://www.daikinapplied.com>
