### ISSUE TITLE
Fail to paste one blob with tags to one blob container under a BlobStorage account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6390]
**Storage Explorer Version**: 1.28.0-dev
**Build Number**: 20221222.8
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.27.1)

## Steps to Reproduce ##
1. Expand one GPV2 storage account -> Blob Containers.
2. Create a blob container -> Upload one blob -> Add tags for the blob -> Copy the blob.
3. Expand one Blob storage account -> Blob Containers.
4. Create a blob container -> Paste the copied blob.
5. Check whether succeeds to paste the blob.

## Expected Experience ##
Succeed to paste the blob.

## Actual Experience ##
Fail to paste the blob with an error 'Blob tags are only supported on General Purpose v2 storage accounts'.

## Additional Context ##
1. This issue doesn't reproduce when the destination is an ADLS Gen2 blob container.
2. This issue doesn't reproduce when the destination blob container is under one BlockBlobStorage account.
3. This issue doesn't reproduce when the destination blob container is under one StorageV2 Premium account.

**Comment by JasonYeMSFT** [comment]
I see. I should create a separate flag so that we can disable tags related feature flag for BlobStorage accounts.

**Comment by JasonYeMSFT** [comment]
I mitigated the issue by not letting copy/paste preserve tags so they can still work for BlobStorage storage accounts. Only clone actions will preserve tags.

**Comment by v-xianya** [comment]
Verified this issue on the build 20220106.1. Clone blob containers preserve tags now.
So, we are going to close this issue.
