### ISSUE TITLE
There is no value for the column property 'Lease State' for one ADLS Gen2 folder that has been acquired/broken lease

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6391]
**Storage Explorer Version**: 1.28.0-dev
**Build Number**: 20221222.8
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Create a folder.
3. Right click the folder -> Click 'Acquire Lease'.
4. There is a lock icon in the front of the folder
5. Check there is a value 'Leased' for the column property 'Lease State'.

## Expected Experience ##
There is a value 'Leased' for the column property 'Lease State'.

## Actual Experience ##
There is no value for the column property 'Lease State'.
![image](https://user-images.githubusercontent.com/41351993/209311108-970bff65-41f7-4214-9cea-9440bd7b3ff2.png)

**Comment by JasonYeMSFT** [comment]
I forget there is a column for the lease state.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230107.3. Fixed. So, we are going to close it.
![image](https://user-images.githubusercontent.com/41351993/211236142-35638818-f143-48cf-8939-5e39e1228ca0.png)
