### ISSUE TITLE
When deleting a queue the entire hierarchy of the storage account collapses

### ISSUE THREAD

**Issue by ahawes-clarity** [microsoft/AzureStorageExplorer#6393]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.0

### Architecture

i86

### Storage Explorer Build Number

20221201.1

### Platform

Windows

### OS Version

Windows 11

### Bug Description

First this Bug Report form does not provide an option to enter ia32 as the Architecture.

Whenever I delete a queue the entire storage account tree collapses. What I would expect is that only the queue I am deleting is removed from the tree and the tree remains expanded as it was.

This is particularly troublesome when I have multiple queues to delete as it requires me to re-expand the storage account for each queue I need to delete. 

### Steps to Reproduce

1. Launch Explorer
2. Expand a Storage Account
3. Expand the Queues node
4. Right-click on a Queue and select delete
5. The storage account immediately collapses

### Actual Experience

Whenever I delete a queue the entire storage account tree collapses. 

### Expected Experience

What I would expect is that only the queue I am deleting is removed from the tree and the tree remains expanded as it was.

**Comment by ahawes-clarity** [comment]
I forgot to mention that this behavior is not new and has existed as far back as I can remember. I am just now posting about it because I have the time. I guess I am very surprised that this issue has not been address yet. But maybe there is something else going on that I am not aware of.

**Comment by MRayermannMSFT** [comment]
@ahawes-clarity thanks for opening the issue. I tried to reproduce what you describe in both version 1.27 and 1.28. In neither version did I see the hierarchy collapse. Any chance you can use scren to gif (https://www.screentogif.com/) to record a reproduction of the bug? Perhaps there's a small/not-obviously-important detail we're missing in the reproduction steps.

**Comment by ahawes-clarity** [comment]
Recording attached. Maybe it is because I am in Quick Access? Yes, I think that might be it. I can't reproduce in the normal Queue listing.
[A screenshot of a computer  Description automatically generated with medium confidence]

**Comment by ahawes-clarity** [comment]
@MRayermannMSFT, my initial reply by email did not include the attachment so I edited it manually to include it.

**Comment by MRayermannMSFT** [comment]
Perfect! The missing detail was that your nodes are under quick access. I'll look into this now. Thanks!

**Comment by MRayermannMSFT** [comment]
![5774](https://user-images.githubusercontent.com/21112697/223493836-dad1a58c-191d-4a6e-be9d-5cd02f7927c8.gif)
😊

**Comment by ahawes-clarity** [comment]
@MRayermannMSFT Does that mean you found the issue or that you can't reproduce?

**Comment by MRayermannMSFT** [comment]
> @MRayermannMSFT Does that mean you found the issue or that you can't reproduce?

Apologies for the confusion. It means I've fixed the issue and we'll include the fix in our next release.

**Comment by MRayermannMSFT** [comment]
Merged into main. Will be included in 1.29.
