### ISSUE TITLE
Better display an error message in the "Enter Connection Information" dialog when the display name is the same as the renamed name of an existing attachment

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6394]
**Storage Explorer Version**: 1.28.0-dev
**Build Number**: 20221226.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Right click the blob container -> Click 'Get Shared Access Signature....' -> Click 'Create'.
3. Copy the SAS URL -> SAS attach the blob container.
4. Rename the blob container attachment with a valid name 'bc01'.
5. Open the connect dialog -> Select 'Blob container' -> Select 'Shared access signature URL (SAS)' -> Click 'Next'.
6. Paste the SAS URL copied in step3 -> Use the name 'bc01' as the display name.
7. Check whether there is a warning message "A connection with the name 'bc01' already exists. Detach the existing connection or provide a different name" on the "Enter Connection Info" dialog.

## Expected Experience ##
There is a warning message "A connection with the name 'bc01' already exists. Detach the existing connection or provide a different name" on the "Enter Connection Info" dialog.

## Actual Experience ##
1. There is no warning message.
2. There is a successful connection activity log.
3. The existing blob container attachment 'bc01' is selected.

## Additional Context ##
1. Follow the repro steps, 
For one blob container/ file share, there is one SAS attachment.
For one queue/table/storage account, there are two attachments.
![image](https://user-images.githubusercontent.com/41351993/209745548-93f26a04-6e11-4015-b4c1-c8b956a34750.png)

2. The 'Rename Blob Container Connection' dialog as below.
![image](https://user-images.githubusercontent.com/41351993/209746490-d3807340-e9f0-497c-80fa-3ded2656d364.png)

**Comment by craxal** [comment]
The name of a connection is now less important than its ID. We should go through these dialogs and relax the unique name requirement.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230127.10. 
Now,the display name of the attached resources are not required to be unique.
