### ISSUE TITLE
Fail to execute the action 'Clone and Rehydrate…' for one archived blob whose name contains '%3A'

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6395]
Storage Explorer Version: 1.28.0-dev
Build Number: 20221226.3
Branch: main
Platform/OS: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.1 (Apple M1 Pro)
Architecture: ia32/x64
How Found: From running test cases
Regression From: Not a regression

## Steps to Reproduce ##

1. Expand one non-ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one blob whose name contains '%3A'.
3. Update the access tier to 'Archive'.
4. Right click the blob -> Click 'Clone and Rehydrate'.
5. Input a valid destination blob name -> Click 'Apply'.
6. Check whether succeeds to execute the action 'Clone and Rehydrate'.

## Expected Experience ##
Succeed to execute the action.

## Actual Experience ##
Fail to execute the action.
![image](https://user-images.githubusercontent.com/87792676/209775197-036a896c-c92e-4d40-944c-5d013425e24a.png)
Error details:
![image](https://user-images.githubusercontent.com/87792676/209775303-e26e86a2-47e5-46ed-8a72-fa223325b760.png)

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230105.1. Fixed. So, we are going to close it.
![image](https://user-images.githubusercontent.com/41351993/210741182-e05c2612-f745-4e6e-b6a3-578aa806a54a.png)
