### ISSUE TITLE
Container not opening in storage account

### ISSUE THREAD

**Issue by Patle-Himanshi** [microsoft/AzureStorageExplorer#6397]
Hi Team,

I am getting the error as below,

Failed to access the service endpoint "https://abcastorage.table.core.windows.net/" (status code: 0, status text: "error"). This failure could be due to your network blocking access to the endpoint, for instance through a firewall. Click on this box to open the endpoint in a new tab. If the page fails to load, make sure your network allows access to the endpoint.

I am using Azure platform and StorageV2 (general purpose v2)
Firewall is enabled as below

![image](https://user-images.githubusercontent.com/109589278/209928518-b85fd6e6-00f7-43f9-b9cf-a760ec8a3adc.png)

Proxy is disabled

Please help to resolve the issue asap.

**Comment by MRayermannMSFT** [comment]
@Patle-Himanshi are you able to browse the contents of your tables via the Azure portal on the same machine?

Can you try using System Proxy? You can read more about it here: https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still running into this problem we recommend opening a support ticket from the Azure portal. You can also open a new issue.
