### ISSUE TITLE
The toolbar and editor for one app configuration are not localized

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6398]
**Storage Explorer Version:** 1.28.0-dev
**Build Number:** 20221226.3
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.1 (Apple M1 Pro)
**Reproduce Languages:** All
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select 'Español' -> Restart Storage Explorer.
3. Expand the 'Application Configurations' node.
4. Open one app configuration.
5. Check whether the toolbar and editor are localized.

## Expected Experience ##
The toolbar and editor are localized.

## Actual Experience ##
The toolbar and editor are not localized.
![image](https://user-images.githubusercontent.com/87792676/209936195-80dd446d-6eb6-42d6-addc-4f162fb0fca4.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20230115.3, it still reproduces.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230117.7 with the new app config extension package.
Fixed on all languages. So, we are going to close it.
![image](https://user-images.githubusercontent.com/41351993/213065993-184a8af3-bb31-4c43-82af-fdc6f5b69075.png)
