### ISSUE TITLE
ARM64 on Windows Support

### ISSUE THREAD

**Issue by MatthewSteeples** [microsoft/AzureStorageExplorer#6401]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I've recently acquired a Windows Dev Kit 2023. AzureStorageExplorer runs as an emulated x86 application. It would be beneficial from a performance perspective if this ran natively (as Teams does)

### Desired Solution

Build and ship a native ARM64 package

### Alternatives and Workarounds

Application works currently on ARM64 when emulation is supported

### Additional Context

Similar request (and possible limitations) as #5616

**Comment by MRayermannMSFT** [comment]
Hi @MAtthewSteeples, thank for asking for this! We have an existing issue for tracking Windows ARM64 support. Here: https://github.com/microsoft/AzureStorageExplorer/issues/6072

Please react to that issue:
![image](https://user-images.githubusercontent.com/21112697/210655038-63f56db4-c804-4efe-9e00-3c6d1c1d9536.png)

Or leave a comment to indicate your desire for that to be addressed. And going forward you can refer to that issue for progress on the issue.

**Comment by MatthewSteeples** [comment]
Apologies, could have sworn I searched for it before posting!
