### ISSUE TITLE
Unable to retrieve child resources.

### ISSUE THREAD

**Issue by kabilraj79** [microsoft/AzureStorageExplorer#6402]
Unable to retrieve child resources.

Details:
{
  "name": "RestError",
  "message": "request to https://test.blob.core.windows.net/?comp=list&include=metadata failed, reason: getaddrinfo ENOTFOUND sitenvtransinprod001.blob.core.windows.net",
  "stack": "RestError: request to https://test.blob.core.windows.net/?comp=list&include=metadata failed, reason: getaddrinfo ENOTFOUND test.blob.core.windows.net\n    at NodeFetchHttpClient.sendRequest (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-blob-extension\\dist\\src\\index.js:2:367093)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async CoreHttpLogHttpClient.sendRequest (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-blob-extension\\dist\\src\\index.js:2:965960)\n    at async StorageBearerTokenChallengeAuthenticationPolicy.sendRequest (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-blob-extension\\dist\\src\\index.js:2:741620)\n    at async StorageRetryPolicy.attemptSendRequest (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-blob-extension\\dist\\src\\index.js:2:736827)\n    at async StorageClientContext.sendOperationRequest (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-blob-extension\\dist\\src\\index.js:2:413043)\n    at async BlobServiceClient.listContainersSegment (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-blob-extension\\dist\\src\\index.js:2:901217)",
  "code": "REQUEST_SEND_ERROR",
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://test.blob.core.windows.net/?comp=list&include=metadata",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2021-10-04"
        },
        "accept": {
          "name": "Accept",
          "value": "application/xml"
        },
        "user-agent": {
          "name": "User-Agent",
          "value": "Microsoft Azure Storage Explorer/1.27.1 (win32) azsdk-js-storageblob/12.12.0 (NODE-VERSION v16.16.0; Windows_NT 10.0.22000)"
        },
    }

**Comment by MRayermannMSFT** [comment]
Can you try using System Proxy? You can read more about it here: https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still running into this problem we recommend opening a support ticket from the Azure portal. You can also open a new issue.
