### ISSUE TITLE
The string and the search icon overlaps in the 'Search by prefix' after opening one snapshot in the split file share tab

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6403]
**Storage Explorer Version:** 1.28.0-dev
**Build Number:** 20221231.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.1 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.26.1)

## Steps to Reproduce ##

1. Expand one storage account -> File Shares.
2. Create one file share -> Right click the file share -> Click 'Create Snapshot'.
3. Open the file share -> Click 'View Share Snapshots'.
4. Right click the file share tab -> Click 'Split'.
5. Switch to the split file share -> Open the snapshot.
6. Observe the 'Search by prefix (case-insensitive)' field.
7. Check whether the string and the search icon doesn't overlap.

## Expected Experience ##
The string and the search icon doesn't overlap.
![image](https://user-images.githubusercontent.com/87792676/210328947-f03785e5-13a9-48b8-b793-a267d601f2ef.png)

## Actual Experience ##
The string and the search icon overlaps.
![image](https://user-images.githubusercontent.com/87792676/210328713-7b12921c-3070-42a2-9db8-fb89a30e2391.png)

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230110.1. Fixed. So, we are going to close it.
