### ISSUE TITLE
Stop using 0 `height` to hide accessibility elements

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#6404]
Follow suggestions here: 
- https://snook.ca/archives/html_and_css/hiding-content-for-accessibility#:~:text=Position%20Absolute%20and%20Collapsed
- https://www.a11yproject.com/posts/how-to-hide-content/

Begin with investigating how much work this will take. We need a list of places in which we need to make fixes.

**Comment by richardMSFT** [comment]
For our use case where the hidden element is a live region that has the `status` role, the Voice Over is announcing the text within correctly. Therefore, I don't see a need to replace the current solution.
