### ISSUE TITLE
Unable to retrieve child resources.

### ISSUE THREAD

**Issue by anandbu** [microsoft/AzureStorageExplorer#6406]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.1

### Architecture

x64

### Storage Explorer Build Number

20221222.2

### Platform

All

### Bug Description

Unable to retrieve child resources.

Details:
{
  "name": "RestError",
  "message": "self signed certificate in certificate chain",
  "stack": "RestError: self signed certificate in certificate chain\n    at ClientRequest.<anonymous> (C:\\Users\\UchagawA\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-table-extension\\dist\\src\\index.js:2:182499)\n    at Object.onceWrapper (node:events:642:26)\n    at ClientRequest.emit (node:events:527:28)\n    at TLSSocket.socketErrorListener (node:_http_client:454:9)\n    at TLSSocket.emit (node:events:527:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "code": "SELF_SIGNED_CERT_IN_CHAIN",
  "request": {
    "url": "https://storageaccounttelee8bab.table.core.windows.net/Tables",
    "headers": {
      "accept": "application/json;odata=minimalmetadata",
      "x-ms-version": "2019-02-02",
      "dataserviceversion": "3.0",
      "accept-encoding": "gzip,deflate",
      "user-agent": "Microsoft Azure Storage Explorer/1.27.1 (win32) azsdk-js-data-tables/13.1.2 core-rest-pipeline/1.9.0 Node/v16.16.0 OS/(ia32-Windows_NT-10.0.22621)",
      "x-ms-client-request-id": "9325baf4-a0c9-42f1-b89e-d41d2cae59d0",
      "x-ms-date": "Wed, 04 Jan 2023 05:42:23 GMT",
      "authorization": "Signed SharedKeyLite Redacted="
    },
    "method": "GET",
    "timeout": 0,
    "disableKeepAlive": false,
    "streamResponseStatusCodes": {},
    "withCredentials": false,
    "tracingOptions": {
      "tracingContext": {
        "_contextMap": {}
      }
    },
    "requestId": "9325baf4-a0c9-42f1-b89e-d41d2cae59d0",
    "allowInsecureConnection": true,
    "enableBrowserStreams": false
  }
}

### Steps to Reproduce

1. Launch Storage Explorer
2. Connect resource with Connection String or from Azure Portal Login
3. Expand Storage-> Queues or Storage -> Tables.

Will get the error as mentioned above.

### Actual Experience

1. Launch Storage Explorer
2. Connect resource with Connection String or from Azure Portal Login
3. Expand Storage-> Queues or Storage -> Tables.

Will get the error as mentioned above.

### Expected Experience

1. Launch Storage Explorer
2. Connect resource with Connection String or from Azure Portal Login
3. Expand Storage-> Queues or Storage -> Tables.
4. Should be able to see the resources under Queues and Tables.

**Comment by MRayermannMSFT** [comment]
Can you try using System Proxy? You can read more about it here: https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by se7enack** [comment]
Also seeing this issue. I can confirm that setting the application's Proxy Configuration to "use system proxy" resolved the issue for us.
