### ISSUE TITLE
UnexpectedCancel (used Azure AD, discovery completed)

### ISSUE THREAD

**Issue by Sunny2k2000** [microsoft/AzureStorageExplorer#6407]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.1

### Architecture

x64

### Storage Explorer Build Number

20221220.2

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Hi, when I upload data to a blob container, it failed with error.
I can download, but unable to upload.
I can upload a file from Azure portal but not from Storage explorer. 

error below:

{
  "message": "\"UnexpectedCancel\""
}

### Steps to Reproduce

Expand one storage account -> Blob Containers.
Create a blob container -> Right click the blob container.
Click 'Manage Access Policies...' -> Add one access policy with 'Read, List' permissions.
Generate a SAS URL via the access policy.
Attach the blob container via the SAS URL.
Upload one blob to the attached blob container -> Click 'OK' on the prompt detected dialog.
Check whether a helpful error message displays in the activity log.

### Actual Experience

Error Details:
{ "message": "\"UnexpectedCancel\"" }

**Comment by MRayermannMSFT** [comment]
Hi @Sunny2k2000 ignoring the un-helpful error message, I would say that this is all expected. The SAS you created only has read and list permissions. You are trying to upload a blob. Therefore the SAS must have at least the permissions:
- write (lets Storage Explorer update existing blobs and create new blobs)
- list (lets Storage Explorer list your container contents)

But ideally it would have:
- write (lets Storage Explorer update existing blobs and create new blobs)
- read (lets Storage Explorer check for conflicts)
- list (lets Storage Explorer list your container contents)
