### ISSUE TITLE
It is better to keep consistent action items for the broken Azure AD attached blob containers/queues/tables

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6408]
**Storage Explorer Version**: 1.28.0-dev
**Build Number**: 20230103.8
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: AD hoc testing 
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Azure AD attach one blob container, queue, table separately (make sure already given the correct RBAC role).
2. After attaching successful.
3. Switch to the 'ACCOUNT MANAGEMENT' panel -> Remove the azure account that associated with the Azure AD attachments.
4. Switch to the 'EXPLORER' panel -> The Azure AD attachments display as broken.
5. Observe the context menu of the Azure AD attachments.
6. Check whether the action items are consistent.

## Expected Experience ##
The action items on the context menu are consistent.

## Actual Experience ##
The action items on the context menu are inconsistent.
![image](https://user-images.githubusercontent.com/41351993/210539888-11e46835-33f2-4505-9f24-7676860beef9.png)

**Comment by v-xianya** [comment]
Verified this issue on the latest build main 20230107.3. Reproduce. So, we are going to re-open it. And will verify it on a newer build.

**Comment by MRayermannMSFT** [comment]
Ah. I misread the bug title. I thought this was for things under QA.

**Comment by v-xianya** [comment]
Verified this issue on the build main 202301101. Fixed. Only show two actions on the context menu of the broken Azure AD attachments.
![image](https://user-images.githubusercontent.com/41351993/211483168-f053f762-e2b3-4b72-9bfd-9f6f1827a703.png)
![image](https://user-images.githubusercontent.com/41351993/211483308-4901c0f5-8b92-4a27-97af-c5aa195a096b.png)
