### ISSUE TITLE
I can't authenticate account, this redirect to localhost later than authenticate

### ISSUE THREAD

**Issue by Soader13** [microsoft/AzureStorageExplorer#6409]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.1

### Architecture

x64

### Platform

Windows

### Bug Description

this is code from error: 
{
  "message": "\"{\\n  \\\"message\\\": \\\"\\\\\\\"No matching account found in either MSAL cache\\\\\\\"\\\"\\n}\""
}

### Steps to Reproduce

1. authenticate my account
2. Redirect to localhost and not resolve mi account
3. show this error: {
  "message": "\"{\\n  \\\"message\\\": \\\"\\\\\\\"No matching account found in either MSAL cache\\\\\\\"\\\"\\n}\""
}

### Actual Experience

I can't use this explorer

**Comment by MRayermannMSFT** [comment]
@Soader13 unfortunately it seems like you will need to sign out and then sign back in. Please do so and let us know if that resolves the issue.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still running into this problem we recommend opening a support ticket from the Azure portal. You can also open a new issue.
