### ISSUE TITLE
Support to check file share's properties

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#641]
**Storage Explorer Version**: 1.5.0 
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture**: ia32
**Build Number**:20180905.3
**Commit**: 66ac14b9
**Regression From**: Not a regression

#### Background: ####
There is one file share which created multiple snapshots, each snapshot has different files/directories, Could you add an action to check these snapshots property such as 'Usage'/'Last Modified'...?
![support](https://user-images.githubusercontent.com/34729022/45208987-6af59100-b27b-11e8-84f6-dfeb89889802.png)

**Comment by MRayermannMSFT** [comment]
Done already.
