### ISSUE TITLE
Azure storage explorer does not show date last modified

### ISSUE THREAD

**Issue by joesalvati68** [microsoft/AzureStorageExplorer#6410]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.0

### Architecture

x64

### Storage Explorer Build Number

20221201.1

### Platform

Windows

### OS Version

Windows 11

### Bug Description

Azure Storage Explorer does not show date, size, status, vm name, last modified, etc.  Basically it doesn't show anything except a file name, which makes searching for things next to impossible. 

### Steps to Reproduce

Open storage explorer, pick a blob, open it and see how the folders are listed

### Actual Experience

Open storage explorer, pick a blob, open it and see how the folders are listed

### Expected Experience

To be able to sort by date, or modified date.

**Comment by MRayermannMSFT** [comment]
@joesalvati68 can you be more specific about what storage service you are working with? Options are:
- blobs not-adls gen2
- blobs adls gen2
- file shares
- adls gen1

Also, for each of these things, can you let us know on what types of items (options are blobs/files or folders) you are not seeing the thing?
- last modified date
- size
- vm name

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still running into this problem we recommend opening a support ticket from the Azure portal. You can also open a new issue.
