### ISSUE TITLE
Error message: `Authentication library failed to start properly` on startup

### ISSUE THREAD

**Issue by bit4n6** [microsoft/AzureStorageExplorer#6412]
OS : Linux Mint 21.1 Cinnamon Edition
Storage Explorer Version: 1.27.1
Prerequisites: Installed from tarball; checked required libs (has libxtables12 instead of libxtables11)
Authentication logs attached
[logs.zip](https://github.com/microsoft/AzureStorageExplorer/files/10350813/logs.zip)

**Comment by MRayermannMSFT** [comment]
@bit4n6 it seems your .net 6 instal isn't quite right. 

Can you please run `dotnet --info` and share the output here?

Ultimately the error we are dealing with is: A fatal error occurred. The folder [/usr/share/dotnet/host/fxr] does not exist

So you'll need to look into how to fix that on Mint.

**Comment by bit4n6** [comment]
Thanks for your response. As it seems, the issue was caused by conflicting packages from Microsoft / Ubuntu repositories. See [here](https://stackoverflow.com/questions/73753672/a-fatal-error-occurred-the-folder-usr-share-dotnet-host-fxr-does-not-exist) for details on how to fix it.
Issue is closed.
