### ISSUE TITLE
Make `getUrl` encode % characters in URL pathname

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#6415]
The SDK clients and various APIs require the non-url characters and % characters to be encoded. However, the URL class that getUrl util function we use don't encode % characters because it assumes they are part of the encoded characters, which forces us to make multiple local workarounds.

**Comment by MRayermannMSFT** [comment]
Following analysis only includes places which use `getUrl` in the presence of a connection with a `path`. So for example, code that is getting the url of an account is not included in this analysis.

Places that patch when they should:
- PathClient2
- BlobPathActions.cloneAndRehydrate

Places that don't patch when they should:
- Video previewing
- Blob properties (the url property)
- Promote snapshot

Places that don't patch when they shouldn't:
- BlobPathClient (different from PathClient2 as blob SDK exposes a `.getBlobClient` which handles path encoding).

**Comment by MRayermannMSFT** [comment]
Packages I should be responsible for updating:
- [ ] Gen2
- [ ] Blob
- [ ] File preview
