### ISSUE TITLE
How can I change the paths using "C:\Users\<user>\AppData\" Azure Storage Explorer

### ISSUE THREAD

**Issue by rjverstoep** [microsoft/AzureStorageExplorer#6417]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.26.1

### Architecture

i86

### Storage Explorer Build Number

1.26.1

### Platform

All

### OS Version

Windows 10

### Bug Description

Hi, 

We have installed Azure Storage Explorer in Citrix, that worked fine. 
But now we have the problem that we can't write files to the paths of "C:\Users\<user>\AppData\...". 
The problem now is that we can't donwload files or can see any logging and maybe other things aswell. All these paths writes to "C:\Users\<user>\AppData\". 

How can we change these setting to choose a specific location/path? We don't see that it is possible in the settings. 

### Steps to Reproduce

1. Launch Azure Storage Explorer
2. connect to a blob -storage
3. download a file from blob-storage
4. In activities you see something like the following "<name-connection>/IMG_20210618_190558__01__02 (2) - kopie.jpg naar C:\Users\<uername>\AppData\Local\Temp\16730006709050"

### Actual Experience

1. Launch Azure Storage Explorer
2. connect to a blob -storage
3. download a file from blob-storage
4. In activities you see something like the following "<name-connection>/IMG_20210618_190558__01__02 (2) - kopie.jpg naar C:\Users\<uername>\AppData\Local\Temp\16730006709050"

Also openingen the option in "Help->Open logfiles" opens the following path "C:\Users\<username>\AppData\Roaming\StorageExplorer\logs".

**Comment by jinglouMSFT** [comment]
Please try with the latest release v1.27.0.  It supports to customize the download location in the Settings page under the Transfer tab.  However, it won't change the log file path.

**Comment by rjverstoep** [comment]
We see the setting so that will help for now. Ashame the logging files (and maybe other files aswell) can't be configured. 
For now we found a selfmade (copy) solution for the logging files within Citrix. 
I will close this issue now, thanks for your advice.
