### ISSUE TITLE
Error when adding a storage account: Not enough memory resources are available to process this command

### ISSUE THREAD

**Issue by jennings** [microsoft/AzureStorageExplorer#6418]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.1

### Architecture

i86

### Storage Explorer Build Number

20221220.2

### Platform

Windows

### OS Version

Windows 11

### Bug Description

When trying to add Azurite with HTTPS as a storage account connection, I receive the following error in the Activities window:

> Error occurred while adding new connection: Error:Not enough memory resources are available to process this command.

This occurs whether I select "Storage account or service" (using a connection string) or "Local storage emulator" in the "Connect to Azure Storage" dialog.

I've tried immediately after rebooting my computer, which is a Surface Laptop 4 with 16 GB of RAM, so it doesn't seem like running out of memory should really be the problem here.

### Steps to Reproduce

1. Reboot the computer
2. Delete the entire `%APPDATA%\StorageExplorer` directory
3. Launch Storage Explorer
4. Right-click _Storage Accounts_ and select _Connect to Azure Storage..._
5. Do either of the following:
   a. Choose _Local storage emulator_, check _Use HTTPS_, and click _Next_
   b. Choose _Storage account or service_, and use the following connection string, then click _Next_: `DefaultEndpointsProtocol=https;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=https://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=https://127.0.0.1:10001/devstoreaccount1;TableEndpoint=https://127.0.0.1:10002/devstoreaccount1;`
6. Click _Connect_

### Actual Experience

The following error appears in the Activities window:

> Error occurred while adding new connection: Error:Not enough memory resources are available to process this command.

### Expected Experience

The new connection appears under the _Storage Accounts_ node in the _Explorer_ pane.

### Additional Context

After trying to add the storage account, the local storage key `StorageExplorer_CustomConnections_Accounts_v1` has the value:

```
[{"id":"devstoreaccount1","displayName":"devstoreaccount1"}]
```

If I restart Storage Explorer and expand the "Storage Accounts" node in the explorer pane, the node does not expand and the error dialog appears:

```
Unable to retrieve child resources.

Details:
{
  "name": "TypeError",
  "message": "Cannot read properties of undefined (reading 'version')",
  "stack": "TypeError: Cannot read properties of undefined (reading 'version')\n    at connectionIsV1 (C:\\Users\\StephenJennings\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\common\\CustomConnections\\IConnectionInfo.js:8:24)\n    at C:\\Users\\StephenJennings\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\common\\CustomConnections\\CustomConnectionStore.js:235:74\n    at Array.filter (<anonymous>)\n    at #sendTelemetry (C:\\Users\\StephenJennings\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\common\\CustomConnections\\CustomConnectionStore.js:235:14)\n    at async CustomConnectionStore.getCustomConnectionStore (C:\\Users\\StephenJennings\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\common\\CustomConnections\\CustomConnectionStore.js:44:9)\n    at async PersistentStorage.CustomConnections.getCustomConnections (C:\\Users\\StephenJennings\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\providers\\CustomConnectionsProvider.js:10:39)\n    at async Provider.executeOperation (C:\\Users\\StephenJennings\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\providers\\Provider.js:28:16)\n    at async ElectronRendererHostProxy._handleExecuteRequest (C:\\Users\\StephenJennings\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\ElectronRendererHostProxy.js:213:35)\n    at async ElectronRendererHostProxy._handleMessage (C:\\Users\\StephenJennings\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\ElectronRendererHostProxy.js:156:24)"
}
```

I did follow the troubleshooting guide, but could not find any entries in the Credential Manager with a name beginning with `StorageExplorer_CustomConnections_Accounts_v1`. The only one I saw was `Microsoft_StorageExplorer/app`, which I did try deleting but it did not solve the problem.

After turning on debug logging, this error was found in the renderer log, with no other obviously-relevant log messages:

```
[2023-01-06T20:56:36.039Z] (renderer:24236) <ERRO> Unable to set password. service:StorageExplorer_CustomConnections_Accounts_v1 account:devstoreaccount1 [Error: Not enough memory resources are available to process this command.
  ]
```

**Comment by craxal** [comment]
@jennings For the "not enough memory" issue, check the command line window from which you are running Azurite. Do you also see that error message there? If so, it may be your Azurite instance doesn't have enough memory or space. Do you have a lot of data stored in your Azurite instance?

For the other issues, we're currently investigating the problem. We recently made some changes to how we store attachments, which seems to have exposed some problems we didn't see earlier.

**Comment by jennings** [comment]
@craxal No, I don't see the error in Azurite's output. The error happens even if I start with a brand new Azurite database. I've learned it also happens if I try to attach to a real Azure storage account with a connection string. (I didn't notice this earlier because I always find my storage accounts through the subscription.)

**Comment by jennings** [comment]
@craxal I used the troubleshooting steps you mentioned in #6399 and found it's the `keytar.setPassword` function that's throwing the "Not enough memory resources" error. This is the stack trace immediately after the error is thrown:

```
"Error: Not enough memory resources are available to process this command.

    at setPassword (C:\Users\StephenJennings\AppData\Local\Programs\Microsoft Azure Storage Explorer\resources\app\node_modules\keytar\lib\keytar.js:22:58)
    at Object.setItem (C:\Users\StephenJennings\AppData\Local\Programs\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\common\PersistentStorage\ConfidentialStore.js:28:44)
    at PersistentStorage.Confidential.setItem (C:\Users\StephenJennings\AppData\Local\Programs\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\providers\ConfidentialPersistentStorageProvider.js:11:54)
    at Provider.executeOperation (C:\Users\StephenJennings\AppData\Local\Programs\Microsoft Azure Storage Explorer\resources\app\out\app\providers\Provider.js:28:59)
    at ElectronRendererHostProxy.executeOperation (C:\Users\StephenJennings\AppData\Local\Programs\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\ElectronRendererHostProxy.js:41:67)
    at CustomConnectionStore.setConfidentialData (C:\Users\StephenJennings\AppData\Local\Programs\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\common\CustomConnections\CustomConnectionStoreBase.js:43:26)
    at CustomConnectionStore.addCustomConnection (C:\Users\StephenJennings\AppData\Local\Programs\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\common\CustomConnections\CustomConnectionStore.js:80:22)
    at async Provider.executeOperation (C:\Users\StephenJennings\AppData\Local\Programs\Microsoft Azure Storage Explorer\resources\app\out\app\providers\Provider.js:28:16)
    at async ElectronRendererHostProxy.executeOperation (C:\Users\StephenJennings\AppData\Local\Programs\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\ElectronRendererHostProxy.js:41:20)
    at async addV1Connection (C:\Users\StephenJennings\AppData\Local\Programs\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\providers\ConnectProvider\ConnectProvider.js:130:5)"
```

**Comment by jennings** [comment]
A-ha. I used the Credential Manager GUI to try adding this entry and got the error:

> There is not enough space available in this vault to add credentials. Delete some existing credentials or create a new vault, and add this credential to that vault.

I seem to have dozens or hundreds of entries in here starting with `vscode-insidersvscode.microsoft-authentication...". After I deleted a few of them, Storage Explorer was able to attach a new storage account.

So, I guess the problem is that the Credential Manager API is unable to add more entries. I couldn't find any documentation about Credential Manager having a maximum size, but apparently it does.

I suppose that means this is no longer an issue Storage Explorer, so I'm closing this. Thank you for leading me down the path to figure this out, @craxal.

**Comment by jennings** [comment]
On second thought, if this _does_ happen, Azure Storage Explorer should avoid adding the connection to the `StorageExplorer_CustomConnections_Accounts_v1` list. That way, the user doesn't end up with a broken application.

**Comment by craxal** [comment]
@jennings Thank you for the detailed findings! Your suggestion is a good one, so we'll look into making connections more robust. In the meantime, you might consider bringing up this issue with VS Code. It seems weird that VS Code would be adding so many credentials without cleaning up after itself.

**Comment by craxal** [comment]
Since we have a tracking issue for making attachments more robust when the encrypted data side of things fails, and the out-of-memory issue is outside of Storage Explorer, I'm going to close this issue as Mitigated.
