### ISSUE TITLE
Error in blob container

### ISSUE THREAD

**Issue by sibani19** [microsoft/AzureStorageExplorer#6421]
I am getting this error while expanding blob container in storage account.

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://covidreportingdlnew16.blob.core.windows.net/?comp=list&include=metadata failed, reason: self signed certificate in certificate chain",
  "stack": "FetchError: request to https://covidreportingdlnew16.blob.core.windows.net/?comp=list&include=metadata failed, reason: self signed certificate in certificate chain\n    at ClientRequest.<anonymous> (C:\\Users\\Lenovo\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-blob-extension\\dist\\src\\index.js:2:2440800)\n    at ClientRequest.emit (node:events:527:28)\n    at TLSSocket.socketErrorListener (node:_http_client:454:9)\n    at TLSSocket.emit (node:events:527:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "SELF_SIGNED_CERT_IN_CHAIN",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}

**Comment by MRayermannMSFT** [comment]
Can you try using System Proxy? You can read more about it here: https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still running into this problem we recommend opening a support ticket from the Azure portal. You can also open a new issue.
