### ISSUE TITLE
It doesn't connect me to blob storage

### ISSUE THREAD

**Issue by JulioBravo78** [microsoft/AzureStorageExplorer#6428]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.2

### Architecture

x64

### Platform

Windows

### Bug Description

No se pueden recuperar los recursos secundarios.

Detalles:
{
  "name": "FetchError",
  "message": "request to https://iafconnectstorageprd.blob.core.windows.net/?comp=list&include=metadata failed, reason: self signed certificate in certificate chain",
  "stack": "FetchError: request to https://iafconnectstorageprd.blob.core.windows.net/?comp=list&include=metadata failed, reason: self signed certificate in certificate chain\n    at ClientRequest.<anonymous> (C:\\Users\\jenbravo\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1483:11)\n    at ClientRequest.emit (events.js:315:20)\n    at TLSSocket.socketErrorListener (_http_client.js:469:9)\n    at TLSSocket.emit (events.js:315:20)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
  "type": "system",
  "errno": "SELF_SIGNED_CERT_IN_CHAIN",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}

### Steps to Reproduce

execute microsoft storage explorer local in my computer
access blob container folder

### Actual Experience

It doesn't connect me to blob storage

**Comment by craxal** [comment]
@JulioBravo78 It looks like you're getting certificate errors.

Do you use a proxy? If so, did you configure Storage Explorer to use that proxy? You can do that by opening the Settings panel and selecting "Use system proxy":

![image](https://user-images.githubusercontent.com/3473026/211882919-d7bd0291-4f8b-473c-adef-c3a692953287.png)

If you're configuring the proxy manually, you'll need to import certificates that your proxy requires. Follow the steps in our [Troubleshooting Guide](https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows#ssl-certificate-issues) to do that.

Do any of these suggestions help resolve your issue?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still running into this problem we recommend opening a support ticket from the Azure portal. You can also open a new issue.
