### ISSUE TITLE
int32 invalid for Table Row property, int64 is the only valid integer type.

### ISSUE THREAD

**Issue by OzBob** [microsoft/AzureStorageExplorer#6432]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.0

### Architecture

x64

### Storage Explorer Build Number

20221220.2

### Platform

Windows

### OS Version

Windows 10

### Bug Description

add property, choose int32, insert, error popup: "Invalid Input"

### Steps to Reproduce

add table row
add property
choose int32
name property test
give type int32
give value 1
click insert
error popup: "Invalid Input"
Logs: [2023-01-11T08:23:59.858Z] (se-table-extension:45136) <ERRO> API call for TableClient.addEntity failed
  POST http://127.0.0.1:10002/devstoreaccount1/testaztbl - 400
  Credential used: Account name and key - account name: devstoreaccount1, account key: ******, keyName: key1
change type to int64
click insert
All OK

### Actual Experience

expecting no popup error

### Expected Experience

no error
or
validaiton warning needs more explanation
or
either int32 is removed as an option

**Comment by craxal** [comment]
@OzBob I am unable to reproduce this issue when connecting to Azure or the current version of Azurite (3.21.0). What version of Azurite are you using? Have you tried updating? I received notes that this issue should already have a fix in 3.21.0 (Azure/Azurite#1259).

**Comment by OzBob** [comment]
I'm not sure why the storage explorer would be picking up the old version.

VS2022 Preview should be using this one:
"C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\Extensions\Microsoft\Azure Storage Emulator\azurite.exe" -v
returns
3.20.1

but
c:>azurite.exe -v
returns
3.14.2

I can't find where the other one is installed. I've searched the whole C drive for another azurite.exe. any suggestions?

**Comment by craxal** [comment]
@OzBob Storage Explorer connects to Azurite using the local endpoint 127.0.0.1 and the default ports for each service. It will send network requests to that endpoint; whatever is listening at those ports, Storage Explorer doesn't really care. What matters is which version of Azurite you launch. How do you start the emulator?

**Comment by OzBob** [comment]
2nd azurite installed in NPM.
Found using ```npm list -g --depth=0```
Uninstalled  ```npm uninstall azurite -g```

Now VS and AzStorageExplorer use the latest version installed with VS
