### ISSUE TITLE
The QA table/queue doesn't show as broken after deleting the original one

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6433]
**Storage Explorer Version**: 1.28.0-dev
**Build Number**: 20230110.7
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.27.1)

## Steps to Reproduce ##
1. Expand one storage account -> Queues.
2. Create a new queue -> Pin it to the Quick Access node.
3. Delete the original queue.
4. Check whether the QA queue shows as broken.

## Expected Experience ##
The QA queue shows as broken.

## Actual Experience ##
The QA queue does not show as broken.

**Comment by MRayermannMSFT** [comment]
This was an intentional change to align with other services (blob and file).
