### ISSUE TITLE
The attached blob container/file share/queue/table explorer displays blank when the SAS URL is created by an access policy

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6435]
**Storage Explorer Version:** 1.28.0-dev
**Build Number:** 20230110.7
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.1 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.27.1)

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Right click the blob container.
3. Click 'Manage Access Policies...' -> Add one access policy.
4. Generate a SAS URL via the access policy.
5. Attach the blob container via the SAS URL -> The attached blob container auto opens.
6. Check whether the opened explorer displays well.

## Expected Experience ##
The opened explorer displays well.

## Actual Experience ##
The opened explorer displays blank.

## Additional Context ##

1. This issue only reproduces for regular blob container.
2. This issue doesn't reproduce when attaching via SAS permissions.

**Comment by v-kellyluo** [comment]
Update: Verified this issue on the build main/20230111.6, the attached blob container/file share/queue/table explorer all displays blank.

**Comment by v-kellyluo** [comment]
On the new build main/20230111.6, the ADLS Gen2 blob containers/file shares/queues/tables also have the same issue

**Comment by v-kellyluo** [comment]
On the new build main/20230111.6, the ADLS Gen2 blob containers/file shares/queues/tables also have the same issue.

**Comment by craxal** [comment]
@v-kellyluo Thanks, we're aware to problem affects all explorer types. We're working on a solution.

**Comment by v-xianya** [comment]
Verified this issue on the new build main 20230112.2. 
1. This issue has been fixed for ADLS Gen2 blob containers/file shares/queues/tables.
2. For blob container, we logged a new bug [6441](https://github.com/microsoft/AzureStorageExplorer/issues/6441).

**Comment by v-xianya** [comment]
Verified this issue on the build 20230115.3. Fixed for blob containers.
