### ISSUE TITLE
User unable to access Azure File storage through Azure Storage Explorer - Unable to retrieve child resources

### ISSUE THREAD

**Issue by DMLaub19** [microsoft/AzureStorageExplorer#6436]
OS: Windows 11 Business 64-bit

Currently have a user trying to access our file storage through the Azure file explorer, however we are receiving this error message. Confirmed that we are accessing this from the correct VPN tunnel to access this resource.

![Screenshot 2023-01-11 084501](https://user-images.githubusercontent.com/122458372/211821913-d7cc7103-34fa-43a1-8999-0ab4531b15b5.png)

**Comment by craxal** [comment]
@DMLaub19 How is your user actually connecting to the file share? Are they signing-in, using an account name and key, shared access signature?

**Comment by thirumalaicb** [comment]
I am an individual user and experiencing the same "error message", but with different stack trace.  This started after I changed my user password on my mac (company provided) a couple of days ago.  I am unable to access the storage accounts that I already had.  Please let me know if you require any further information.
Version: 1.27.1
AzCopy Version: 10.16.2
Platform: macOS M1
Architecture: x64 
Build Number: 20221220.2 
Stacktrace:
```
Unable to retrieve child resources.

Details:
{
  "name": "TypeError",
  "message": "Cannot read properties of undefined (reading 'version')",
  "stack": "TypeError: Cannot read properties of undefined (reading 'version')\n    at connectionIsV1 (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/renderer/common/CustomConnections/IConnectionInfo.js:8:24)\n    at /Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/renderer/common/CustomConnections/CustomConnectionStore.js:235:74\n    at Array.filter (<anonymous>)\n    at #sendTelemetry (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/renderer/common/CustomConnections/CustomConnectionStore.js:235:14)\n    at async CustomConnectionStore.getCustomConnectionStore (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/renderer/common/CustomConnections/CustomConnectionStore.js:44:9)\n    at async PersistentStorage.CustomConnections.getCustomConnections (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/renderer/providers/CustomConnectionsProvider.js:10:39)\n    at async Provider.executeOperation (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/providers/Provider.js:28:16)\n    at async ElectronRendererHostProxy._handleExecuteRequest (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/renderer/ElectronRendererHostProxy.js:213:35)\n    at async ElectronRendererHostProxy._handleMessage (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/out/app/renderer/ElectronRendererHostProxy.js:156:24)"
}
```

**Comment by craxal** [comment]
@thirumalaicb It appears you are connecting to your storage accounts by attachment (using an account name and key or a SAS) rather than signing in. Your issue is a known issue, and we are working on a solution (see #6399 for details).

**Comment by thirumalaicb** [comment]
@craxal Just to update, I see that v1.27.2 was released on 01/23.  I could update the version and did not see this issue anymore.  Thank you.

P.S. The month on https://github.com/microsoft/AzureStorageExplorer/releases page is mentioned incorrectly as Dec 2022, whereas it should be Jan 2023 for v1.27.2.

**Comment by craxal** [comment]
@thirumalaicb I'm glad your issue was resolved.

For clarification, 1.27.2 is based on 1.27.0, which was released in December 2022, meaning it is a hotfix release for our December 2022 release. The date in the release notes is intentional.

**Comment by craxal** [comment]
@DMLaub19 Are you able to find answers to the questions I asked earlier? How is your user actually connecting to the file share? Are they signing-in, using an account name and key, shared access signature...?

**Comment by DMLaub19** [comment]
@craxal

Sorry for the late reply here! They were signing in with their AAD creds with the Storage Explorer app.

I figured out what needed to be done -- I had to create a custom role that allowed access into that specific container, one of the roles that were assigned didn't have all the applicable permissions that were needed.
