### ISSUE TITLE
Change Tier from Hot to Archive failed

### ISSUE THREAD

**Issue by AllenHu2018** [microsoft/AzureStorageExplorer#6437]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.3

### Architecture

i86

### Platform

All

### OS Version

Azure visual Desktop

### Bug Description

{
  "message": "[{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220816%2F313443_830643%2F6_313443_830643.jpg?comp=tier failed, reason: connect EADDRINUSE 40.73.85.36:443\",\"type\":\"system\",\"errno\":\"EADDRINUSE\",\"code\":\"EADDRINUSE\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F311925_830682%2F3_311925_830682.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F311925_830682%2F4_311925_830682.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F311925_830682%2F5_311925_830682.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F311925_830682%2F6_311925_830682.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F311925_830682%2F7_311925_830682.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F311925_830682%2F8_311925_830682.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F311926_830683%2F1_311926_830683.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F311926_830683%2F2_311926_830683.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F311926_830683%2F311926_830683.txt?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F311926_830683%2F4_311926_830683.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F311926_830683%2F3_311926_830683.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F311926_830683%2F5_311926_830683.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F311926_830683%2F6_311926_830683.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F311926_830683%2F7_311926_830683.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F311927_830684%2F1_311927_830684.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F311927_830684%2F2_311927_830684.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F311927_830684%2F311927_830684.txt?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F311927_830684%2F3_311927_830684.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F311927_830684%2F4_311927_830684.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F311927_830684%2F5_311927_830684.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F311927_830684%2F6_311927_830684.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F311927_830684%2F7_311927_830684.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F311927_830684%2F8_311927_830684.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F311928_830685%2F1_311928_830685.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F311928_830685%2F2_311928_830685.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F311928_830685%2F3_311928_830685.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F311928_830685%2F311928_830685.txt?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F311928_830685%2F4_311928_830685.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F312811_830693%2F2_312811_830693.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F312811_830693%2F312811_830693.txt?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F312811_830693%2F3_312811_830693.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F312811_830693%2F4_312811_830693.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F312811_830693%2F5_312811_830693.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F312811_830693%2F6_312811_830693.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F312811_830693%2F7_312811_830693.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F312811_830693%2F8_312811_830693.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F312811_830693%2F9_312811_830693.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F313332_830650%2F1_313332_830650.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F313332_830650%2F2_313332_830650.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F313332_830650%2F313332_830650.txt?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F313332_830650%2F3_313332_830650.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F313332_830650%2F4_313332_830650.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F313332_830650%2F5_313332_830650.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F313334_830649%2F1_313334_830649.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F313334_830649%2F2_313334_830649.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F313334_830649%2F313334_830649.txt?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F313334_830649%2F3_313334_830649.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F313334_830649%2F4_313334_830649.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"},{\"message\":\"request to https://b2cprdcne2cmpsa0.blob.core.chinacloudapi.cn/cmp-kol-prd/20220817%2F313334_830649%2F5_313334_830649.jpg?comp=tier failed, reason: connect ENOBUFS 40.73.85.36:443 - Local (undefined:undefined)\",\"type\":\"system\",\"errno\":\"ENOBUFS\",\"code\":\"ENOBUFS\"}]"
}
...Truncated

### Steps to Reproduce

Select more than 10000 blobs 
change tier from hot to archive
some failed "Failures occur while changing access tier in container 'cmp-kol-prd' to 'Archive': success: 79817, failure: 598"

### Actual Experience

![image](https://user-images.githubusercontent.com/37926317/211849191-2e30be99-5373-4cb2-a923-574503c32fd1.png)

**Comment by JasonYeMSFT** [comment]
Does the issue consistently reproduce? If you wait for a while and retry the set tier operation on the failed blobs, do they still fail? Both EADDRINUSE and ENOBUFS are indicators that something goes wrong on the server side. If the issue consistently reproduce, I also recommend opening a support ticket to the storage blob service provider on Azure Portal.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still running into this problem we recommend opening a support ticket from the Azure portal. You can also open a new issue.
