### ISSUE TITLE
unnecessary 'Display name' validation errors

### ISSUE THREAD

**Issue by sedwardstx** [microsoft/AzureStorageExplorer#644]
**Storage Explorer Version**: 1.4.1
**Platform/OS Version**: Windows 10
**Architecture**: x64
**Build Number**: 20180820.1

#### Steps to Reproduce ####
1. Sign in with any account.
2. Open Connect dialog (Use a shared access signature URI) and paste the connection string below
   https://sampleaccount5.blob.core.windows.net/fabriclogs-abcdefgh-ijkl-mnop-qrst-uvwxyz?sv=2015-04-05&ss=bt&srt=sco&sp=rl&se=2018-09-08T00:02:17.4216163Z&sig=YYANsXflCoOQ%2BVk9AfWkpT5DOI1RyLduy10jVYmD0%2Fs%3D

#### Expected Experience ####
The default account name auto populates under 'Display name' and 'Connect' button is active

#### Actual Experience ####
The default account name auto populates under 'Display name' but 'Connect' button is not-active
 and there is a validation error.  User must still change/edit the display name is some way before they are allowed to proceed.  This is poor usability, the validation error should only show if the display name is blank for some reason.

![image](https://user-images.githubusercontent.com/5359924/45232558-69d15d80-b295-11e8-8c23-44c148d982d2.png)

**Comment by MRayermannMSFT** [comment]
We believe this has been fixed since this issue was opened. If you are still having issues, please upgrade to the latest Storage Explorer and let us know if your issue still occurs. Thanks.
