### ISSUE TITLE
An error reminder dialog pops up when opening Storage Explorer by snap for the first time

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6442]
**Storage Explorer Version:** 1.28.0-dev
**Build Number:** 20230113.1
**Branch:** main
**Platform/OS:** Linux Ubuntu 20.04
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.27.1)

## Steps to Reproduce ##

1. Open a Linux machine with OS version Ubuntu 20.04.
2. Download Linux build as snap file.
3. Open terminal -> Navigate to where the Storage Explorer executable is located.
4. Run the following commands to install Storage Explorer:
  sudo snap install StorageExplorer_latest_amd64.snap --dangerous
  snap connect storage-explorer:password-manager-service :password-manager-service
  storage-explorer
5. Check no error reminder dialog pops up.

## Expected Experience ##
No error reminder dialog pops up.
## Actual Experience ##
An error reminder dialog pops up.
![image](https://user-images.githubusercontent.com/87792676/212258694-00be7725-d286-4119-b151-0796eff54c73.png)

## Additional Context ##
This issue doesn't reproduce when opening Storage Explorer for the second time.

**Comment by MRayermannMSFT** [comment]
Tried on 20230116.1, was unable to reproduce. @v-kellyluo can you try one more time, but run this command before running the command `storage-explorer`:

`export SERVICEHUBTRACELEVEL=ALL`

If you then reproduce again then please do the following after the issue reproduces:
1. Close storage explorer.
2. Copy and paste all terminal output into a text file, and share file here.
3. Run the command `open ~/snap/storage-explorer/current/.ServiceHub/logs`, and share all of the files in that folder here. You can put them in a .zip or .tar.gz if you'd like.

**Comment by v-kellyluo** [comment]
@MRayermannMSFT , this issue still reproduces after running the command `export SERVICEHUBTRACELEVEL=ALL`.
Here is the logs: [logs.zip](https://github.com/microsoft/AzureStorageExplorer/files/10444093/logs.zip)

**Comment by MRayermannMSFT** [comment]
@v-kellyluo, can you please try seeing if the issue reproduces with this build?
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7209398&view=results

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT 
This issue doesn't reproduce on the build 20230118.2.
![image](https://user-images.githubusercontent.com/41351993/213428607-23c23920-3be3-4d0d-9c73-d5a2c48f335b.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20230127.10. Fixed.
