### ISSUE TITLE
The opened tab on the split view is selected when opening one file share/blob container/HNS blob container/table even through the split view is not the current selected view

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6443]
**Storage Explorer Version**: 1.28.0-dev
**Build Number**: 20230113.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Ad hoc testing
**Regression From**: Previous release (1.24.3)

## Steps to Reproduce ##
1. Open one tab -> Open one file share.
2. Split the file share tab -> Go back to the original view.
3. Close the original file share tab -> Open the file share again.
4. Check whether a new tab is opened in the original view.

## Expected Experience ##
A new tab is opened in the original view.

## Actual Experience ##
The split file share tab is selected.

## Additional Context ##
1. This issue doesn't reproduce for queues/resource groups/ADLS Gen1 accounts.
2. Here is the record:
![split](https://user-images.githubusercontent.com/41351993/212264415-d0691011-7e86-4778-be89-c3600d9cf5cf.gif)

**Comment by JasonYeMSFT** [comment]
Queue/Resource Group/Gen1 are using a deprecated API which doesn't support tracking open panels across different views. The current behavior of File Share/Blob/HNS Blob/Table are the expected behavior and will be applied to them in the future.

**Comment by JasonYeMSFT** [comment]
https://github.com/microsoft/AzureStorageExplorer/issues/6447
