### ISSUE TITLE
Make use of File Share file and directory rename APIs

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#6448]
- https://learn.microsoft.com/en-us/rest/api/storageservices/rename-directory
- https://learn.microsoft.com/en-us/rest/api/storageservices/rename-file

Make use of the above APIs to offer "Rename" and "Move" in the file explorer. Should allow for renaming & moving individual files and directories in a file share. See experiences in the ADLS Gen2 Blob explorer for the differences between "Rename" and "Move".

**Comment by richardMSFT** [comment]
Shipping with 1.29.0
