### ISSUE TITLE
Trailing dot support in Azure Files

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#6449]
1. First party apps (e.g. Storage Explorer) should enable trailing dot support by default.
2. Need SDK and AzCopy support. SDK probably available early March to mid-April.

**Comment by richardMSFT** [comment]
Investigate which operations in File Share Storage should now support trailing dots in the file or directory name (ie. create new file, directory, move file/directory, rename file/directory, etc.). 
- Modify the validations to accept trailing dots
- Make sure the trailing dot header is set when doing these operations
- Make sure existing tests pass
- Communicate to CTI how this impacts existing behaviors
