### ISSUE TITLE
Unable to browse SAS URL added storage

### ISSUE THREAD

**Issue by omartin2010** [Microsoft/AzureStorageExplorer#645]
**Storage Explorer Version**: 1.4.1
**Platform/OS Version**: Windows10
**Architecture**: ia32
**Regression From**: no

#### Steps to Reproduce: ####
1. Connect to a new blob using "Connect to Azure Storage", using a SAS URI, with too long of a URI, that includes the path to a blob that's too long (below the container name).
2. Then I see when I try another time that I'm not able to reuse the display name I've previously used before (which makes sense). However I'm unable to see the list of what was added because the first one that I've added seems like it's breaking the parser.

#### Expected Experience: ####
I expect that if it can't handle what I wrote, that it refuses me to add it. When I browse "Local & Attached/Storage Accounts/(SAS-Attached Services)/Blob Containers/display_name_1" (for example).

#### Actual Experience: ####
I see under "Local & Attached/Storage Accounts/(SAS-Attached Services)/Blob Containers/", the option "Load More" and if I click on Load More, I get the error messages : "Unable to retrieve child resources. Details : Container name must be between 3 and 63 characters". The first URI that I added (it was the first time I used this functionality) had the whole path to the actual blob (and not only the container). Once I click on "OK", I get the other message "The requested action could not be completed. Details: Container name must be between 3 and 63 characters long.".

I'm sure I can reset something but I'm also sure this could be fixed. I've removed and reinstalled Storage Explorer, and it came  up with the same configuration that likely is written outside of the directory where the program is. Can that location be shared so I can get going ?

**Comment by craxal** [comment]
You can delete the .adalcache file from your user directory (see our [Troubleshooting](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?toc=%2fazure%2fstorage%2fblobs%2ftoc.json) page).

It does sound like a weird parsing error. Can you share with us (minus any signatures, of course)? It may be a good test case for us to add.

Why is your URI so long? Are you trying to connect to a blob? You can only connect to blob containers in Storage Explorer. If you're trying to download the blob using a URI, you should just enter that into your web browser.

**Comment by omartin2010** [comment]
It basically was my naiveness of never having used this functionality and pasting something obviously too long that broke it. But it was still a URL pasted from sharing one particular blob (perhaps with a long path). Shouldn't break... but thanks for the queue to the troubleshooting page.
