### ISSUE TITLE
Can't list file shares when signed-in with Azure AD

### ISSUE THREAD

**Issue by ferronsw** [microsoft/AzureStorageExplorer#6451]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.0

### Regression From

no

### Architecture

x64

### Storage Explorer Build Number

20221201.1

### Platform

Windows

### OS Version

Windows 11

### Bug Description

```
Details:
{
  "name": "Error",
  "message": "Unable to perform operation 'FileServiceClient.listSharesSegment'. No suitable credentials provided.",
  "stack": "Error: Unable to perform operation 'FileServiceClient.listSharesSegment'. No suitable credentials provided.\n    at FileServiceClient.runOperation (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:491456)\n    at FileServiceClient.listSharesSegment (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:33003)\n    at FileShareNodeProducer.produceFileShareNodes (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:64557)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Azure.Storage.FileShareProducer.produceFileShareNodes (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:86697)\n    at async Provider.executeOperation (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\providers\\Provider.js:28:16)\n    at async NodeProcessHostProxy._handleExecuteRequest (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:229:31)\n    at async NodeProcessHostProxy._handleMessage (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:182:24)\n    at async C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:65:17"
}
```

### Steps to Reproduce

1. Launch storage explorer.
2.  Sign in with Azure AD Account
3.  Expand the subscription
4.  Expand the storage account
5.  Expand File Shares

### Actual Experience

Error message is shown like you can see in the bug description.

### Expected Experience

Show the files shares the user has permissions for.

### Additional Context

The problem I described doesn't occur when you are owner of the subscription (and probably many other high privileged roles).
The user who is experiencing this problem doesn't have any roles within Azure besides the one I specified for the storage account.

I've given this user reader access to the Azure Storage Account in question.
Besides that I've given him the following permission on the Azure Storage Account in question.

![image](https://user-images.githubusercontent.com/19926383/213418928-ec64ba37-59e1-4206-8b6e-07e77bdbacec.png)

I also tried these permissions on the fileshare itself instead of the storage account itself, but it doesn't make a difference. 

Current configuration regarding AAD for the storage account file shares:

![image](https://user-images.githubusercontent.com/19926383/213420065-d9355aff-3b2f-4aef-b7cd-c63d2d0d34d7.png)

**Comment by MRayermannMSFT** [comment]
@ferronsw , Azure file shares currently do not support authenticating with OAuth/RBAC over HTTP. It is only supported over SMB: https://learn.microsoft.com/en-us/azure/storage/files/storage-files-active-directory-overview

Whenever files shares do begin to support authenticating with OAuth/RBAC over HTTP, Storage Explorer will work to take advantage of that support as well.

> you are owner of the subscription (and probably many other high privileged roles)

Yes this is because with those other roles you will have access to the account keys, which can be used to authenticate HTTP requests.

**Comment by eskaufel** [comment]
> @ferronsw , Azure file shares currently do not support authenticating with OAuth/RBAC over HTTP. It is only supported over SMB: https://learn.microsoft.com/en-us/azure/storage/files/storage-files-active-directory-overview
> 
> Whenever files shares do begin to support authenticating with OAuth/RBAC over HTTP, Storage Explorer will work to take advantage of that support as well.
> 
> > you are owner of the subscription (and probably many other high privileged roles)
> 
> Yes this is because with those other roles you will have access to the account keys, which can be used to authenticate HTTP requests.

https://techcommunity.microsoft.com/t5/azure-storage-blog/general-availability-introducing-azure-ad-support-for-azure/ba-p/3826733

It is what you needed, right?

**Comment by ferronsw** [comment]
@eskaufel yes think so :)

**Comment by atmask** [comment]
This still seems to be an issue. We've created a custom role with the same permissions and assigned the role to users athe Storage Account and File Shared scope but they still cannot list file shares in Azure Storage Epxlorer
