### ISSUE TITLE
Ctrl+A not selecting all files and folders in currently selected folder

### ISSUE THREAD

**Issue by P47K0** [microsoft/AzureStorageExplorer#6454]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.1

### Architecture

i86

### Storage Explorer Build Number

20221220.2

### Platform

Windows

### OS Version

Windows 10

### Bug Description

When I press Ctrl+A in the explorer tab, all the text in the tab is selected (also the text from the buttons in the menu). I would expect that the files and folders listed are selected instead. So that I can copy or delete them all at once. Now I have to select them one by one.

### Steps to Reproduce

1. Launch Storage Explorer
2. Select a storage account with file shares
3. Select a file share
4. Press Ctrl+A

Step 3:
![image](https://user-images.githubusercontent.com/6309117/214037180-e5e5560b-04ea-476f-9be2-7973de509472.png)

Step 4:
![image](https://user-images.githubusercontent.com/6309117/214037260-05e62345-84cb-457a-9042-3c5f1ad4db25.png)

### Actual Experience

All the text in the tab is selected (also the text from the buttons in the menu)

### Expected Experience

The files and folders in the tab are selected

**Comment by JasonYeMSFT** [comment]
@P47K0 You need to focus the data grid (e.g. click into it) to be able to select files/folders in it. The select all action should work once your focus is in the data grid.

**Comment by P47K0** [comment]
I see that it works as expected when you select first one file.
But when you click on the white space below the files (in the same window part) it doesn't work. I would expect that it also works then (in windows explorer this works).

**Comment by JasonYeMSFT** [comment]
@P47K0 I understand this is not very well designed. We don't have shortcut listener at the root of the panel and selecting the text is the default behavior of the "ctrl+A" shortcut. We can look into bringing the shortcut up to the root of the panel.

**Comment by richardMSFT** [comment]
Shipping with 1.29.0.
