### ISSUE TITLE
Can't log into Azure using enterprise credentials.

### ISSUE THREAD

**Issue by tomcscott** [microsoft/AzureStorageExplorer#646]
**Storage Explorer Version**: 1.4.1
**Platform/OS Version**: Mac OS version 10.13.6
**Architecture**: ???
**Regression From**: ???

#### Steps to Reproduce: ####
1. 
2. 

#### Expected Experience: ####
After submitting credentials the screen hangs....

**Comment by craxal** [comment]
@tomcscott, please fill out the issue template as completely as possible. We can help you out much faster with the right information from the start.

**Comment by tomcscott** [comment]
Storage Explorer Version: Version: 1.4.1
Platform/OS Version: Mac OS version 10.13.6
Architecture: ?
Regression From: ?

Steps to Reproduce: I sent screenshots previously, but the issue occurs when I enter my credentials to add an account to Connect to Azure Storage

Expected Experience: after submitting credentials the screen hangs....

Actual Experience:

**Comment by craxal** [comment]
@tomcscott, you said you sent screenshots previously? Where are these screenshots? Are they in an earlier issue?

**Comment by craxal** [comment]
Oh, if you have a case open, then you should continue to work through them.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having issues, please upgrade to the latest Storage Explorer and let us know if your issue still occurs. Thanks.
