### ISSUE TITLE
Can't see the containers in storage explorer

### ISSUE THREAD

**Issue by CRana2022** [microsoft/AzureStorageExplorer#6463]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.0

### Architecture

x64

### Storage Explorer Build Number

20221201.1

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://ziplinefiles.blob.core.windows.net/?comp=list&include=metadata failed, reason: unable to get local issuer certificate",
  "stack": "FetchError: request to https://ziplinefiles.blob.core.windows.net/?comp=list&include=metadata failed, reason: unable to get local issuer certificate\n    at ClientRequest.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-blob-extension\\dist\\src\\index.js:2:2440800)\n    at ClientRequest.emit (node:events:527:28)\n    at TLSSocket.socketErrorListener (node:_http_client:454:9)\n    at TLSSocket.emit (node:events:527:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY",
  "code": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"
}

### Steps to Reproduce

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://ziplinefiles.blob.core.windows.net/?comp=list&include=metadata failed, reason: unable to get local issuer certificate",
  "stack": "FetchError: request to https://ziplinefiles.blob.core.windows.net/?comp=list&include=metadata failed, reason: unable to get local issuer certificate\n    at ClientRequest.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-blob-extension\\dist\\src\\index.js:2:2440800)\n    at ClientRequest.emit (node:events:527:28)\n    at TLSSocket.socketErrorListener (node:_http_client:454:9)\n    at TLSSocket.emit (node:events:527:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY",
  "code": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"
}

### Actual Experience

Cant connect to containers

### Expected Experience

All containers should be viewable. I am not able to see any containers. 

### Additional Context

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://ziplinefiles.blob.core.windows.net/?comp=list&include=metadata failed, reason: unable to get local issuer certificate",
  "stack": "FetchError: request to https://ziplinefiles.blob.core.windows.net/?comp=list&include=metadata failed, reason: unable to get local issuer certificate\n    at ClientRequest.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-blob-extension\\dist\\src\\index.js:2:2440800)\n    at ClientRequest.emit (node:events:527:28)\n    at TLSSocket.socketErrorListener (node:_http_client:454:9)\n    at TLSSocket.emit (node:events:527:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY",
  "code": ### **"UNABLE_TO_GET_ISSUER_CERT_LOCALLY"**
}
![StorageCapture](https://user-images.githubusercontent.com/100292576/214881904-06c1f58e-d35e-48de-a188-3c6af58b7e02.PNG)

**Comment by MRayermannMSFT** [comment]
Can you try using System Proxy? You can read more about it here: https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by CRana2022** [comment]
Yes, it worked.

Thanks,
Chandra Rana

From: Matthew Rayermann ***@***.***>
Sent: Monday, January 30, 2023 12:48 PM
To: microsoft/AzureStorageExplorer ***@***.***>
Cc: Chandra Rana ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/AzureStorageExplorer] Can't see the containers in storage explorer (Issue #6463)


Can you try using System Proxy? You can read more about it here: https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview<https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview>
