### ISSUE TITLE
Can't log in to Storage Explorer: Bad Request - Request Too Long

### ISSUE THREAD

**Issue by joelcochran** [microsoft/AzureStorageExplorer#6464]
![image](https://user-images.githubusercontent.com/1847996/214889949-df7f14da-98ef-4df7-8271-1053c43fbe28.png)

I've followed the steps in the documentation to reset the app and removed .IdentityService folder, but the error still prevents me from logging in to Azure in the app.

**Comment by joelcochran** [comment]
This is what happens in the app:
![image](https://user-images.githubusercontent.com/1847996/214894829-291886ab-b1a3-493b-a166-b34933b63aae.png)

And it never resolves.

**Comment by joelcochran** [comment]
I've tried clearing all cookies in Edge for microsoftonline.com, office365, and office.com as outlined in several web articles. Still not able to get past this issue.

**Comment by joelcochran** [comment]
I finally got around this by deleting all cookies in the browser. Would be good to know specifically which cookies I could delete so I don't have to nuke them all.

**Comment by joelcochran** [comment]
> i am running on [intel arc](https://www.lenovo.com/us/en/faqs/intel/intel-graphics/) and My problem is: every time i open Azure Storage Explorer, 10 seconds goes by and then the it crashes(closes). No error code, no nothing, just closes and that is it? Does anyone know what is happening?
> 
> Regards.

You should probably report this as a separate issue.

**Comment by MRayermannMSFT** [comment]
> i am running on [intel arc](https://www.lenovo.com/us/en/faqs/intel/intel-graphics/) and My problem is: every time i open Azure Storage Explorer, 10 seconds goes by and then the it crashes(closes). No error code, no nothing, just closes and that is it? Does anyone know what is happening?
> 
> Regards.

Yes, please open a separate issue for this!

**Comment by MRayermannMSFT** [comment]
> I finally got around this by deleting all cookies in the browser. Would be good to know specifically which cookies I could delete so I don't have to nuke them all.

Hi @joelcochran , I'm happy you were able to figure this out without us. With regards to specific cookies, I would say Microsoft cookies are likely the culprit. So if this ever happens again you just need to nuke cookies that are specifically Microsoft related.
