### ISSUE TITLE
Cant map storage

### ISSUE THREAD

**Issue by grharrisii** [microsoft/AzureStorageExplorer#6465]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.3

### Architecture

i86

### Storage Explorer Build Number

20220617.2

### Platform

All

### OS Version

Windows 10

### Bug Description

Trying map a file share

### Steps to Reproduce

Launch Storage Explorer 
Expand File Shares

### Actual Experience

I receive the error unable to retrieve child resources

### Expected Experience

Child Resources expand/open in storage explorer

### Additional Context

"status": 403,
    "bodyAsText": "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.\nRequestId:f134fe61-501a-004d-5dad-3160d8000000\nTime:2023-01-26T17:43:04.3404804Z</Message></Error>",
    "parsedBody": {
      "message": "This request is not authorized to perform this operation.\nRequestId:f134fe61-501a-004d-5dad-3160d8000000\nTime:2023-01-26T17:43:04.3404804Z",
      "code": "AuthorizationFailure"
    },
    "parsedHeaders": {
      "errorCode": "AuthorizationFailure",
      "content-length": "246",
      "content-type": "application/xml",
      "date": "Thu, 26 Jan 2023 17:43:03 GMT",
      "server": "Microsoft-HTTPAPI/2.0",
      "x-ms-client-request-id": "30846114-3599-4c54-b1a6-69199a5ced5e",
      "x-ms-request-id": "f134fe61-501a-004d-5dad-3160d8000000"
    }
  },
  "details": {
    "errorCode": "AuthorizationFailure",
    "content-length": "246",
    "content-type": "application/xml",
    "date": "Thu, 26 Jan 2023 17:43:03 GMT",
    "server": "Microsoft-HTTPAPI/2.0",
    "x-ms-client-request-id": "30846114-3599-4c54-b1a6-69199a5ced5e",
    "x-ms-request-id": "f134fe61-501a-004d-5dad-3160d8000000",
    "message": "This request is not authorized to perform this operation.\nRequestId:f134fe61-501a-004d-5dad-3160d8000000\nTime:2023-01-26T17:43:04.3404804Z",
    "code": "AuthorizationFailure"
  }
}

**Comment by MRayermannMSFT** [comment]
@grharrisii do you know how you are authenticating access to your resources?

- If you have attached with name&key/key connection string, can you make sure the account name is correct and that the keys have not been rotated?
- If you have attached with SAS URL/SAS connection string, can you make sure the SAS is not expired or just try generating a new SAS?
- If you have signed in and are listing resources under a subscription, can you check the RBAC roles your account has? 
- If you have signed in and attached with Azure AD, can you check the RBAC roles your account has for the container/check the ACL permissions you have for the container (if it is an ADLS Gen2 container)?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue we recommend opening an Azure support ticket from the portal. Alternatively you can open a new issue here.
