### ISSUE TITLE
Fix strings that say "search by prefix" to be "filter by prefix"

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#6470]

**Comment by v-xianya** [comment]
@MRayermannMSFT 
On the rel build 20230131.13. The string is 'Search by prefix'.
![image](https://user-images.githubusercontent.com/41351993/215932392-b338aefd-3164-410a-8fd6-620356a607d4.png)

**Comment by v-xianya** [comment]
Verified this issue on the build 20230202.3. Fixed.
