### ISSUE TITLE
Azure Error

### ISSUE THREAD

**Issue by bilgich** [microsoft/AzureStorageExplorer#6471]
Unable to retrieve child resources.

Details:
{
  "name": "RestError",
  "message": "{\"name\":\"RestError\",\"code\":\"ECONNRESET\",\"request\":{\"url\":\"https://management.azure.com/subscriptions/cbf879fb-2d14-474a-9fd5-cf145bd4759d/resources?api-version=2014-04-01&%24filter=resourceType+eq+%27Microsoft.ClassicStorage%2fstorageAccounts%27+or+resourceType+eq+%27Microsoft.Storage%2fstorageAccounts%27&%24skiptoken=eyJuZXh0UGFydGl0aW9uS2V5IjoiMSE4IVJVSkZRakktIiwibmV4dFJvd0tleSI6IjEhMjQwIVEwSkdPRGM1UmtJeVJERTBORGMwUVRsR1JEVkRSakUwTlVKRU5EYzFPVVJmUjFKTUxVRmFPakpFVWtjNk1rUkVRbEk2TWtSTlFVNUJSMFZFT2pKRVJFSlNVRkpQUkZWRFZGTlZVRkJNV1ZBeE1ERTZNa1JFTnpKR1YxZEZOMWRQUWxwSExVMUpRMUpQVTA5R1ZEb3lSVU5QVFZCVlZFVTZNa1pXU1ZKVVZVRk1UVUZEU0VsT1JWTTZNa1pDTkVNeU1qY3dSamhCT1RFMFFqbENRa1pCTVRnelFqSkdNekU0UXpBM05DMUZRVk5VVlZNeSJ9\",\"headers\":{\"authorization\":\"Bearer JSON Web Token Redacted\",\"user-agent\":\"Microsoft Azure Storage Explorer/1.24.2 (win32)\"},\"method\":\"GET\",\"timeout\":30000,\"disableKeepAlive\":false,\"withCredentials\":false,\"requestId\":\"8616980e-cabb-40a1-a2cd-31a45a8a26cc\",\"allowInsecureConnection\":true,\"enableBrowserStreams\":false}}"
}

**Comment by MRayermannMSFT** [comment]
Can you try using System Proxy? You can read more about it here: https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue we recommend opening an Azure support ticket from the portal. Alternatively you can open a new issue here.
