### ISSUE TITLE
Azure Storage Explorer in AVD not connecting to Storage Account with Private Link Enabled

### ISSUE THREAD

**Issue by ShubjeetPal** [microsoft/AzureStorageExplorer#6472]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.2

### Architecture

i86

### Storage Explorer Build Number

20230123.2

### Platform

Windows

### Bug Description

Azure Storage Explorer for windows installed in Azure virtual Desktop not connecting to Storage Account with Private Link Enabled

### Steps to Reproduce

1) I have 3 vnets for hub, spoke-dev and AVD.
2) Hub has VPN gateway and is peered with spoke-dev and AVD vnets with gateway transit enabled
3) Added storage account in spoke-dev vnet with private link. The private link has vnet link with hub, spoke-dev and AVD vnets
4) When accessing storage account from AVD remote desktop app for windows (from my laptop) getting below error
	a) request to https://devstgacct.blob.core.windows.net/?comp=list&include=metadata failed, reason: connect ETIMEDOUT
5) Created a vm in hub vnet. Logged in and same error from AVD remote desktop app for windows
6) Enabled private links for AVD and disabled public access from host pool and workspace
	a) Logged in again to vm in hub vnet. Same result from AVD remote desktop app for windows

### Actual Experience

Details:
{
  "name": "FetchError",
  "message": "request to https://devstgacct.blob.core.windows.net/?comp=list&include=metadata failed, reason: connect ETIMEDOUT 10.1.1.4:443",
  "stack": "FetchError: request to https://devstgacct.blob.core.windows.net/?comp=list&include=metadata failed, reason: connect ETIMEDOUT 10.1.1.4:443\n    at ClientRequest.<anonymous> (C:\\Users\\ShubjeetPal\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-blob-extension\\dist\\src\\index.js:2:2440800)\n    at ClientRequest.emit (node:events:527:28)\n    at TLSSocket.socketErrorListener (node:_http_client:454:9)\n    at TLSSocket.emit (node:events:527:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "ETIMEDOUT",
  "code": "ETIMEDOUT"
}

### Expected Experience

Connection Should work

**Comment by MRayermannMSFT** [comment]
@ShubjeetPal 

1. Can you try using System Proxy? You can read more about it here: https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview
2. If you make a SAS url to a blob in your container, and then try to use that SAS url in the browser in the AVD instance, is the browser able to reach the blob?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue we recommend opening an Azure support ticket from the portal. Alternatively you can open a new issue here.
