### ISSUE TITLE
It is better to keep a consistent format for the display names of broken Azure AD attachments

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6474]
**Storage Explorer Version**: 1.28.0-dev
**Build Number**: 20230127.10
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.27.2)

## Steps to Reproduce ##
1. Azure AD attach one blob container, queue, table separately using the default display name (make sure already given the correct RBAC role).
2. After attaching successful.
3. Switch to the 'ACCOUNT MANAGEMENT' panel -> Remove the azure account that associated with the Azure AD attachments.
4. Switch to the 'EXPLORER' panel -> The Azure AD attachments display as broken.
5. Observe the display names of the Azure AD attachments.
6. Check whether the display names keep a consistent format.

## Expected Experience ##
The display names keep a consistent format.
![image](https://user-images.githubusercontent.com/41351993/215317713-b5f3d0a8-729a-445c-9b4a-f8001fe230ec.png)

## Actual Experience ##
The display names do not keep a consistent format.
![image](https://user-images.githubusercontent.com/41351993/215317094-a0bad493-006d-401f-aac3-1a9fdb1a0d8a.png)

**Comment by craxal** [comment]
This only reproduces for blob containers.

**Comment by v-xianya** [comment]
Verified this issue on the rel build 20230123.5. Fixed.  So, we are going to close it.

![image](https://user-images.githubusercontent.com/41351993/215697522-639a77d6-1159-4349-9db3-22899fcd0c25.png)
