### ISSUE TITLE
An extra action item 'Rename...' displays on the context menu of one broken QA Azure AD attached blob container which associated user account has been removed

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6475]
**Storage Explorer Version**: 1.28.0-dev
**Build Number**: 20230127.10
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Azure AD attach one blob container (make sure already given the correct RBAC role).
2. After attaching successful -> Pin the attachment to Quick Access node.
3. Switch to the 'ACCOUNT MANAGEMENT' panel -> Remove the azure account that associated with the Azure AD attachments.
4. Switch to the 'EXPLORER' panel -> The QA Azure AD attachment displays as broken.
5. Right click the QA attachment -> Observe the action items.
6. Check no 'Rename' action item displays.

## Expected Experience ##
No 'Rename...' action item displays.

## Actual Experience ##
The 'Rename...' action item displays.
![image](https://user-images.githubusercontent.com/41351993/215318651-5a4fc139-41ad-4177-821a-101d309a3412.png)

## Additional Context ##
1. This issue also reproduces for ADLS Gen2 blob containers.
2. This issue doesn't reproduce for queues/tables.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20230304.8. Fixed.
![image](https://user-images.githubusercontent.com/87792676/223000888-f2018b90-1581-4927-b152-2c26f5c5747d.png)
