### ISSUE TITLE
Azure Storage Explorer issue with Self Signed Cert

### ISSUE THREAD

**Issue by janakipalli** [microsoft/AzureStorageExplorer#6477]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.2

### Regression From

1.27.2

### Architecture

x64

### Storage Explorer Build Number

1.27.2

### Platform

Windows

### Bug Description

Due to unknown self-signed cert issue, I could not access the account. an 

### Steps to Reproduce

1. Launch Storage Explorer
2. Auth account
3. Access Blob Container
4. Cert issue occurs

### Actual Experience

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://artifactdmz.blob.core.windows.net/?comp=list&include=metadata failed, reason: self signed certificate in certificate chain",
  "stack": "FetchError: request to https://artifactdmz.blob.core.windows.net/?comp=list&include=metadata failed, reason: self signed certificate in certificate chain\n    at ClientRequest.<anonymous> (C:\\Users\\JanakiM\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-blob-extension\\dist\\src\\index.js:2:2440800)\n    at ClientRequest.emit (node:events:527:28)\n    at TLSSocket.socketErrorListener (node:_http_client:454:9)\n    at TLSSocket.emit (node:events:527:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "SELF_SIGNED_CERT_IN_CHAIN",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}

### Additional Context

See log

**Comment by MRayermannMSFT** [comment]
Can you try using System Proxy? You can read more about it here: https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue we recommend opening an Azure support ticket from the portal. Alternatively you can open a new issue here.
