### ISSUE TITLE
The 'Duplicate' button is still enabled when there is an error in the 'Duplicate Entity' dialog

### ISSUE THREAD

**Issue by v-sunnsun** [microsoft/AzureStorageExplorer#6479]
**Storage Explorer Version** : 1.28.0-dev
**Build Number** : 20230127.10 
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create a table -> Add an entity.
3. Right click the entity -> Click 'Duplicate' for the context menu.
4. Delete the original 'PartitionKey' value and enter the same value again. 
5. An error displays in the dialog.
6. Check whether the 'Duplicate...' button is disabled.

## Expected Experience ## 
The 'Duplicate' button is disabled.

## Actual Experience ##
The 'Duplicate' button is enabled.
![image](https://user-images.githubusercontent.com/122582307/215428098-7b78ffec-0107-4309-b8fe-e792bcd98bca.png)

**Comment by v-xianya** [comment]
Verified this issue on the rel build 20230123.5. Fixed. 
![image](https://user-images.githubusercontent.com/41351993/215713544-9afa484f-e9fc-40b1-a965-83447a9afd43.png)
