### ISSUE TITLE
Can't copy vertex ID values from the graph explorer

### ISSUE THREAD

**Issue by LarsKemmann** [microsoft/AzureStorageExplorer#648]
**Storage Explorer Version**: 1.4.1
**Platform/OS Version**: Windows
**Architecture**: ia32
**Regression From**: N/A

#### Steps to Reproduce: ####
1. Select a vertex in a graph
2. Attempt to select the `id` property on the vertex, in order to copy it

#### Expected Experience: ####
I should get a fast-select-all experience, or at least be able to highlight the text manually.

#### Actual Experience: ####
Text is unselectable and cannot be copied.

**Comment by craxal** [comment]
Sorry, I got lost at step 1. Are we talking about a CosmosDB Graph API account?

**Comment by LarsKemmann** [comment]
@craxal Yes.

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
