### ISSUE TITLE
Please add FileId and ParentId field in file/directory properties [Azure File Share].

### ISSUE THREAD

**Issue by Gorlami96** [microsoft/AzureStorageExplorer#6480]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

The File Properties box (right click on any file -> Properties) should contain the FileId and the ParentId. This information is present in the Azure SCL whenever CloudFile.FetchAttributes() is called.

### Desired Solution

I would like Storage explorer to display File/Directory Id. It would be great if all the information retrieved by the FetchAttributes call (for both files and directories) is displayed in the properties box.

**Comment by MRayermannMSFT** [comment]
@Corlami96 adding the parent and file IDs should be relatively straightforward.

> It would be great if all the information retrieved by the FetchAttributes call (for both files and directories) is displayed in the properties box.

If there's something specific you'd like, please let us know. Otherwise we'd prefer to only focus on specific requests for adding more information.

**Comment by Gorlami96** [comment]
Specifically CreationTime, LastWriteTime, NtfsAttributes would be good to have

**Comment by MRayermannMSFT** [comment]
@Corlami96 can you elaborate on what you mean by NfsAttributes? I'm unfortunately not seeing anything in documentation regarding that. For CreationTime and LastWriteTime, we should be ok on that.

**Comment by Gorlami96** [comment]
https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.file.fileproperties.ntfsattributes?view=azure-dotnet

**Comment by MRayermannMSFT** [comment]
Thanks!

**Comment by MRayermannMSFT** [comment]
@Gorlami96 the NFS attributes are already visible. They can be found in the "Attributes" column. Let me know if you don't see them/what version of Storage Explorer you aren't seeing them in.
