### ISSUE TITLE
A confirmation dialog still pops up when opening the file with the same extension if check the option 'Always trust files with this extension' then click 'No' in the previously dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6481]
**Storage Explorer Version**: 1.28.0-dev
**Build Number**: 20230127.10
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Ad hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one .csv file.
3. Make sure .csv is not added to the setting 'Trusted File Extensions'.
4. Open the .csv file -> There is a confirmation dialog.
5. Check the option 'Always trust files with this extension' -> Click 'No'.
6. Open the .csv file again.
7. Check there is no confirmation dialog.

## Expected Experience ##
There is no confirmation dialog.

## Actual Experience ##
There is a confirmation dialog.
![image](https://user-images.githubusercontent.com/41351993/215444481-a52efd58-02ea-4c2b-bcda-06cd7b864e72.png)

**Comment by MRayermannMSFT** [comment]
@v-xianya this is expected. We believe that unless the user chooses to actually go through with the open, then we should not pay attention to the state of the checkbox.

**Comment by v-xianya** [comment]
@MRayermannMSFT 
For the delete dialog. The option "Don't ask again about enabling soft delete" will take effect if check it then click 'No'.
![image](https://user-images.githubusercontent.com/41351993/215700891-51656d39-826a-4f9a-abb1-2fa3093abfcb.png)
