### ISSUE TITLE
The string on the address bar is incorrect when opening one ADLS Gen2 sub-folder under the filter mode

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6497]
**Storage Explorer Version**: 1.28.0
**Build Number**: 20230131.13
**Branch**: rel/1.28.0
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2 (Apple M1 Pro)
**Architecture**: ia32/x64/arm64
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Create a folder A -> Open the folder A -> Create a sub-folder B.
3. Back to the root.
4. Type 'A/B' in the search by prefix box.
5. Open the folder 'B' -> Observe the address bar.
6. Check whether shows a correct string.

## Expected Experience ##
Show a correct string.

## Actual Experience ##
Show an incorrect string.
![image](https://user-images.githubusercontent.com/41351993/215994777-7af4d525-ac93-47e6-ad49-4c80c201816b.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20230203.13. Fixed. So, we are going to close it.
![image](https://user-images.githubusercontent.com/87792676/216867907-6e39ede1-0577-4cc7-abf8-25f49faafd8e.png)
