### ISSUE TITLE
Viewer for JSON

### ISSUE THREAD

**Issue by fausttiger** [microsoft/AzureStorageExplorer#6499]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

why is there no Viewer for JSON,  you keep adding lots of other file type viewers

### Desired Solution

viewer for JSON files in storage explorer

**Comment by JasonYeMSFT** [comment]
It will be added in 1.28.0.
