### ISSUE TITLE
Better to update the record of the 'Release Notes -> Sub-Directory Prefix Search in File Shares' part since the string 'Search by prefix' has been updated

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6502]
**Storage Explorer Version**: 1.28.0
**Build Number**: 20230202.3
**Branch**: rel/1.28.0
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2 (MacBook Air Intel)
**Architecture**: ia32/x64
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Open storage explorer -> Click 'Help -> Release Notes'.
2. Go to the 'Sub-Directory Prefix Search in File Shares' part.
3. Observe the search string in the record.
4. Check whether the string is 'Filter by prefix'.

## Expected Experience ##
The string is 'Filter by prefix'.

## Actual Experience ##
The string is 'Search by prefix'.
![image](https://user-images.githubusercontent.com/41351993/216266168-bff7cc39-ea85-42ee-9831-8cee91d92fc7.png)

**Comment by MRayermannMSFT** [comment]
I'm impressed y'all noticed this.

**Comment by v-xianya** [comment]
Verified this issue on the rel build 20230203.7. Fixed. So, we are going to close it.
