### ISSUE TITLE
Fail to delete/download/open files under sub-directory filter mode for file shares

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6503]
**Storage Explorer Version**: 1.28.0
**Build Number**: 20230202.3
**Branch**: rel/1.28.0
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2 (MacBook Air Intel)
**Architecture**: ia32/x64
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a new file share -> Create a folder 'New Folder'.
3. Upload one file to the folder.
4. Type 'New Folder/' into the 'Filter by prefix' box.
5. Select the file -> Try to delete it.
6. Check whether succeeds to delete the file.

## Expected Experience ##
Succeed to delete the file.
## Actual Experience ##
Fail to delete the file.
![image](https://user-images.githubusercontent.com/41351993/216273738-07199648-3d2c-40b1-9f11-f7aa8b7cc778.png)

Error details:
`{
  "message": "\"failed to perform remove command due to error: cannot start job due to error: -> github.com/Azure/azure-storage-file-go/azfile.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.6.1-0.20201111053559-3c1754dc00a5/azfile/zc_storage_error.go:42\\n===== RESPONSE ERROR (ServiceCode=ResourceNotFound) =====\\nDescription=The specified resource does not exist.\\nRequestId:fe9d0d81-c01a-0010-3ce1-369f1f000000\\nTime:2023-02-02T08:39:55.5750590Z, Details: \\n   Code: ResourceNotFound\\n   GET https://arbacadls.file.core.windows.net/share/New%20Text%20Document.txt?restype=directory&se=2023-03-04t08%3A39%3A53z&sig=-REDACTED-&sp=rwdl&sr=s&sv=2021-10-04&timeout=901\\n   User-Agent: [Microsoft Azure Storage Explorer, 1.28.0, win32, azcopy-node/2.11.0-rc.1 (win32)  AzCopy/10.17.0 Azure-Storage/0.8.0 (go1.19.2; Windows_NT)]\\n   X-Ms-Client-Request-Id: [dde39f3d-7ff4-4db3-5639-2f9c615acc4c]\\n   X-Ms-Version: [2020-10-02]\\n   --------------------------------------------------------------------------------\\n   RESPONSE Status: 404 The specified resource does not exist.\\n   Content-Length: [223]\\n   Content-Type: [application/xml]\\n   Date: [Thu, 02 Feb 2023 08:39:55 GMT]\\n   Server: [Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0]\\n   X-Ms-Client-Request-Id: [dde39f3d-7ff4-4db3-5639-2f9c615acc4c]\\n   X-Ms-Error-Code: [ResourceNotFound]\\n   X-Ms-Request-Id: [fe9d0d81-c01a-0010-3ce1-369f1f000000]\\n   X-Ms-Version: [2020-10-02]\\n\\n\\n.\\n\""
}`

## Additional Context ##
1. This issue doesn't reproduce for ADLS Gen2 blobs/Regular blobs.
2. Show a successful log below when trying to delete more than one file at the same time.
![image](https://user-images.githubusercontent.com/41351993/216274681-c83874e6-21bf-4b45-bf6e-0b2e83d29d5e.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20230203.13. Fixed. So, we are going to close it.
