### ISSUE TITLE
Fail to paste one ADLS Gen2 blob which is filtered by directory

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6505]
**Storage Explorer Version**: 1.28.0
**Build Number**: 20230202.3
**Branch**: rel/1.28.0
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2 (MacBook Air Intel)
**Architecture**: ia32/x64
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Create a folder 'A'.
3. Upload one blob to the folder 'A'.
4. Type 'A/' into the 'Filter by prefix' box.
5. Copy the blob -> Paste it.
6. Check whether succeeds to paste it.

## Expected Experience ##
Succeed to paste it.

## Actual Experience ##
Fail to paste it.
![image](https://user-images.githubusercontent.com/41351993/216283711-7dbf4a47-6456-4831-be1f-a1d6de8a3c1d.png)

Error details:
`{
  "message": "\"failed to perform copy command due to error: failed to initialize enumerator: The specified file was not found.\""
}`

## Additional Context ##
Show below successful activity log when pasting more than one ADLS Gen2 blob.
![image](https://user-images.githubusercontent.com/41351993/216285318-7417cb1c-be8e-4866-9bb1-26c0fd546a33.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20230203.13. Fixed. So, we are going to close it.
