### ISSUE TITLE
unable to Establish connection using current Proxy settings

### ISSUE THREAD

**Issue by SusheelHKD** [microsoft/AzureStorageExplorer#6510]
Hi Team, 

While i am truing to connect or after i open storage explorer it prompts "unable to Establish connection using current Proxy settings", below is the error message. kindly help to fix the issue.

 "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"tunneling socket could not be established, cause=read ECONNRESET\\\",\\n  \\\"stack\\\": \\\"Error: tunneling socket could not be established, cause=read ECONNRESET\\\\n    at ClientRequest.onError (C:\\\\\\\\Users\\\\\\\\PONSM\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\tunnel-agent\\\\\\\\index.js:177:17)\\\\n    at Object.onceWrapper (node:events:646:26)\\\\n    at ClientRequest.emit (node:events:526:28)\\\\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\\\\n    at TLSSocket.emit (node:events:526:28)\\\\n    at emitErrorNT (node:internal/streams/destroy:157:8)\\\\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\\\\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)\\\",\\n  \\\"code\\\": \\\"ECONNRESET\\\"\\n}\""
}

**Comment by JasonYeMSFT** [comment]
Could you verify if your proxy software is working properly? ECONNRESET means the connection is dropped by the server, which could be your proxy server in this case.

**Comment by mishrs9** [comment]
Hi Jason,

User got instructions to setup MS Azure Storage Explorer after installing program in our laptops more than 6 months ago and 
 it worked until now but suddenly since 2 weeks user is facing this issue.
proxy url :https://proxy
port: 80

From these values it was working earlier . 
Could you please help if they have to change proxy or if Storage Explorer itself fails or if there is another issue.

**Comment by mishrs9** [comment]
Hi Team , 

Do we have any update on the above comments 

Thanks

**Comment by MRayermannMSFT** [comment]
@mishrs9 did you look into if your proxy is functioning properly? Do you have proxy settings configured at your OS level? If so, please try using system proxy in storage explorer: https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem we recommend opening a support ticket via the Azure Portal. Alternatively you can open a new issue here.

**Comment by SusheelHKD** [comment]
Hi Matthew,

Thank you For your support and will get back to you if the issue still persists..


Thanks & Regards,
Susheel Dasari
HDF Platform Engineer
Mobile: +91 9959977917
***@***.******@***.***>
www.henkeldx.com<http://www.henkeldx.com/>

[Ein Bild, das Schild, Ende, sitzend, Front enthält.  Automatisch generierte Beschreibung]
Creating the Next



From: Matthew Rayermann ***@***.***>
Sent: Monday, March 13, 2023 6:47 PM
To: microsoft/AzureStorageExplorer ***@***.***>
Cc: Susheelkumar Dasari (ext) ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [microsoft/AzureStorageExplorer] unable to Establish connection using current Proxy settings (Issue #6510)

This message is from an EXTERNAL SENDER – be CAUTIOUS, particularly with links and attachments
________________________________

Closing due to lack of response. If you are still encountering this problem we recommend opening a support ticket via the Azure Portal. Alternatively you can open a new issue here.
