### ISSUE TITLE
Can't upload files.

### ISSUE THREAD

**Issue by DThomper21** [microsoft/AzureStorageExplorer#6512]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.0

### Architecture

i86

### Storage Explorer Build Number

20221201.1

### Platform

Windows

### Bug Description

I am receiving this error when trying to upload files.

{
  "message": "\"UnexpectedCancel\""
}

### Steps to Reproduce

Select upload
Select file or folder
Attach desired documents 
Unsuccessful upload renders this error listed above.

### Actual Experience

I receive this error trying to upload documents.

{
  "message": "\"UnexpectedCancel\""
}

### Expected Experience

{
  "message": "\"UnexpectedCancel\""
}

### Additional Context

{
  "message": "\"UnexpectedCancel\""
}

**Comment by JasonYeMSFT** [comment]
@DThomper21 The error usually indicates AzCopy crashed unexpectedly. Could you get the command by "Copy AzCopy Command", retry it on the command line using AzCopy and shared the output with us? Make sure you redact sensitive information such as your storage account, container name, credentials, etc. You can the AzCopy executable from https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#download-azcopy

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem, we recommend opening a support ticket via the Azure portal. Alternatively you can open a new issue here.
