### ISSUE TITLE
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

### ISSUE THREAD

**Issue by M-SQUARE-SYS** [microsoft/AzureStorageExplorer#6513]
Unable to access the blog azure storage. Access granted to public and even IP address to storage account link but when we open the static link or SAS URL in the browser, the storage link throwing an error. 
Error>
<Code>AuthenticationFailed</Code>
<Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:751ae88e-901c-0091-036d-391d11000000 Time:2023-02-05T14:21:42.6380687Z</Message>
</Error>

**Comment by JasonYeMSFT** [comment]
@M-SQUARE_SYS Are you using the link in Storage Explorer or did you get the link from Storage Explorer? If neither we are not the right team to help here.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem, we recommend opening a support ticket via the Azure portal. Alternatively you can open a new issue here.
