### ISSUE TITLE
Error details

### ISSUE THREAD

**Issue by Abdelkrim-B** [microsoft/AzureStorageExplorer#6514]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.2

### Architecture

x64

### Storage Explorer Build Number

20230123.2

### Platform

Windows

### Bug Description

Unable to retrieve child resources.

Details:
{
  "message": "{}"
}

### Steps to Reproduce

1 launch Storage Explorer
2. login to my subscription 
3. Create data storage account
4. Unable to retrieve child resources on the Storage explorer error details below

Details:
{
  "message": "{}"
}

### Actual Experience

Unable to retrieve child resources.

Details:
{
  "message": "{}"
}

**Comment by MRayermannMSFT** [comment]
@Abdelkrim-B can you please follow these steps to get your Storage Explorer logs: https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows#storage-explorer-logs

Please make sure that you:
1. Restart after changing the log level
2. Reproduce the issue before getting the logs

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem we recommend opening a support ticket via the Azure Portal. Alternatively you can open a new issue here.
