### ISSUE TITLE
Could not access resources for this tenant. You may need to reauthenticate

### ISSUE THREAD

**Issue by almobinR** [microsoft/AzureStorageExplorer#6517]
I tried everything, including proxy settings and SAS key, nothing is working.

{
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80\\\",\\n  \\\"stack\\\": \\\"Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80\\\\n    at ClientRequest.onError (C:\\\\\\\\Users\\\\\\\\Al Mobin Rahman\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\tunnel-agent\\\\\\\\index.js:177:17)\\\\n    at Object.onceWrapper (node:events:642:26)\\\\n    at ClientRequest.emit (node:events:527:28)\\\\n    at TLSSocket.socketErrorListener (node:_http_client:454:9)\\\\n    at TLSSocket.emit (node:events:527:28)\\\\n    at emitErrorNT (node:internal/streams/destroy:157:8)\\\\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\\\\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)\\\",\\n  \\\"code\\\": \\\"ECONNRESET\\\"\\n}\""
}

Using SAS, I got the storage but could not create any blob container.

error below:
"Failed to create blob container 'raw': request to https://formula1storagepr.blob.core.windows.net/raw?sv=2021-06-08&ss=bfqt&srt=so&sp=rwdlacupyx&se=2023-02-06T19:16:32Z&st=2023-02-06T11:16:32Z&spr=https&sig=QxcaeijktcWXFoDvGfimuKsMFVEzgMwOanNoe1K0k2s%3D&restype=container failed, reason: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80"

Could you please tell me whats happening?

Thank you

Regards
Al

**Comment by JasonYeMSFT** [comment]
Did you configured a proxy at 127.0.0.1:80? If it is expected, your proxy software might not be working properly. If it's not expected, you should turn off proxy in Storage Explorer settings.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem, we recommend opening a support ticket via the Azure portal. Alternatively you can open a new issue here.
