### ISSUE TITLE
Failed to move files in container 'myContainer'

### ISSUE THREAD

**Issue by yusuf-jkhan1** [microsoft/AzureStorageExplorer#6518]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.2

### Architecture

i86

### Storage Explorer Build Number

20230123.2

### Platform

Windows

### OS Version

Windows 10

### Bug Description

I have 'Owner' permissions on a ADLS Gen2 Storage Account. I am able to perform most actions, like uploading/downloading blobs, adding/deleting containers.

One thing I get a 403 unauthorized permission error on is when I try to move files from one folder to another within the same container. Meaning I have /parent_folder/child_folder/ and I try to highlight a set of files use the GUI to move it to /parent_folder/

The error message is a couple hundred lines long so I don't want to go through and redact everything to post it here but they key error message is a 403:

`"This request is not authorized to perform this operation.` 

I can't elevate my permissions any higher than they are, and even our admin who is owner on the whole subscription can't move the file. 

The way we are authenticating is by using the AD login flow which opens the browser. 

### Steps to Reproduce

1. Launch Azure Storage Explorer
2. Expand Storage Accounts >> Blob Containers
3. Select files that are in a subdirectory, either right click and select Move or select Move from the ribbon
4. Enter a different and confirmed valid directory
5. Hit okay

### Actual Experience

I have 'Owner' permissions on a ADLS Gen2 Storage Account. I am able to perform most actions, like uploading/downloading blobs, adding/deleting containers.

One thing I get a 403 unauthorized permission error on is when I try to move files from one folder to another within the same container. Meaning I have /parent_folder/child_folder/ and I try to highlight a set of files use the GUI to move it to /parent_folder/

The error message is a couple hundred lines long so I don't want to go through and redact everything to post it here but they key error message is a 403:

`"This request is not authorized to perform this operation.` 

I can't elevate my permissions any higher than they are, and even our admin who is owner on the whole subscription can't move the file. 

The way we are authenticating is by using the AD login flow which opens the browser. 

### Expected Experience

I should be able to move files from one folder to another given my permissions

### Additional Context

I get this regardless of Storage Explorer version. The 'Architecture' listed in the about menu is actually "ia32" which wasn't a drop down option in the issue defaults.

**Comment by JasonYeMSFT** [comment]
@yusuf-jkhan1 If you only have the "Owner" role and you are only authenticating with Azure AD you shouldn't be able to perform actions such as upload/download/create etc. It's possible that there are ACL's configured that grants you the permission to do such things. Since ACLs are finer level access control, it is possible that you are missing some of the required the ACL permissions on the source/destination. You can go to Azure Portal and manage the ACL of the directories to unblock yourself.

**Comment by yusuf-jkhan1** [comment]
Thank you for the response. We definitely did not set any ACL's at least explicitly. I also have contributor which is possibly where the permissions are coming from.

Although we learned today that if we turn off the network firewall to the storage account it works again, when we make it selected networks it stops working. We have a private endpoint on the storage account and our VPN DNS server is configured to route traffic appropriately for `*.core.windows.net` subdomains. But I assume the actions that throw the error like moving files possibly hit APIs that have different subdomains?

If you recommend, I can close this issue as it seems to be related to Network and the API endpoints that Storage Explorer hits during certain actions.

Thanks for the help, let me know

**Comment by JasonYeMSFT** [comment]
@yusuf-jkhan1 Thanks for the info! It's good to know the firewall may trigger such errors.
