### ISSUE TITLE
The authentication fails after my Azure account changes to validation with two factors.

### ISSUE THREAD

**Issue by FlavioKlein** [microsoft/AzureStorageExplorer#6522]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.2

### Architecture

x64

### Storage Explorer Build Number

20230123.2

### Platform

Windows

### OS Version

windows 10

### Bug Description

The navigation tab is opened and show the message with authentication ok. But storage explorer show me login error.
I don't have access to my cdn account.
Because don't carrie my assignatures.

### Steps to Reproduce

1. Launch explorer
2. Expand containers
3. Try sign with Azure.

### Actual Experience

I'm already logged in Azure.
I try sign in with storage explorer.
The navigation tab is opened and show the message with authentication ok. 
But storage explorer show me login error.
I don't have access to my cdn account.
Because don't carrie my assignatures.
Error detail:
{
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"read ECONNRESET\\\",\\n  \\\"stack\\\": \\\"Error: read ECONNRESET\\\\n    at __node_internal_captureLargerStackTrace (node:internal/errors:465:5)\\\\n    at __node_internal_errnoException (node:internal/errors:595:12)\\\\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)\\\",\\n  \\\"errno\\\": -4077,\\n  \\\"code\\\": \\\"ECONNRESET\\\",\\n  \\\"syscall\\\": \\\"read\\\"\\n}\""
}
![Erro01](https://user-images.githubusercontent.com/8942293/217138485-a7199bf2-ce23-4700-8941-3f48cc0bedac.png)
![Erro01](https://user-images.githubusercontent.com/8942293/217138568-f1a1e559-aed1-44c2-baf1-cc74a195ed8d.png)

**Comment by MRayermannMSFT** [comment]
Hi @FlavioKlien can you try the following steps:

1. Remove the account
2. Go to Help -> Reset, and then in the dialog, only select "Authentication", and then do the reset
3. Go to settings (gear on the left) -> application -> proxy -> and then in the dropdown, select "System Proxy"
4. Restart storage explorer
5. Try signing in again

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem we recommend opening a support ticket via the Azure Portal. Alternatively you can open a new issue here.
