### ISSUE TITLE
Error Details in Microsoft Azure Storage Explorer

### ISSUE THREAD

**Issue by Phjloi33** [microsoft/AzureStorageExplorer#6524]
Unable to retrieve child resources.

Details:
{
  "name": "RestError",
  "message": "getaddrinfo ENOTFOUND rdsresbotstaprdwe01.table.core.windows.net",
  "stack": "RestError: getaddrinfo ENOTFOUND rdsresbotstaprdwe01.table.core.windows.net\n    at ClientRequest.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-table-extension\\dist\\src\\index.js:2:182499)\n    at Object.onceWrapper (node:events:642:26)\n    at ClientRequest.emit (node:events:527:28)\n    at TLSSocket.socketErrorListener (node:_http_client:454:9)\n    at TLSSocket.emit (node:events:527:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "code": "ENOTFOUND",
  "request": {
    "url": "https://rdsresbotstaprdwe01.table.core.windows.net/Tables",
    "headers": {
      "accept": "application/json;odata=minimalmetadata",
      "x-ms-version": "2019-02-02",
      "dataserviceversion": "3.0",
      "accept-encoding": "gzip,deflate",
      "user-agent": "Microsoft Azure Storage Explorer/1.27.2 (win32) azsdk-js-data-tables/13.1.2 core-rest-pipeline/1.9.0 Node/v16.16.0 OS/(ia32-Windows_NT-10.0.19044)",
      "x-ms-client-request-id": "2c7342e3-f0d6-4ad9-bacd-80d68db0e024",
      "x-ms-date": "Wed, 08 Feb 2023 02:39:25 GMT",
      "authorization": "Signed SharedKeyLite Redacted="
    },
    "method": "GET",
    "timeout": 0,
    "disableKeepAlive": false,
    "streamResponseStatusCodes": {},
    "withCredentials": false,
    "tracingOptions": {
      "tracingContext": {
        "_contextMap": {}
      }
    },
    "requestId": "2c7342e3-f0d6-4ad9-bacd-80d68db0e024",
    "allowInsecureConnection": true,
    "enableBrowserStreams": false
  }
}

**Comment by MRayermannMSFT** [comment]
@Phjloi33:

1. Are you able to access your tables on the same machine via your browser & the Azure portal?
2. If yes, can you try enabling system proxy? You can learn more about it here: https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview
3. If no, then some sort of configuration on your storage account is blocking access from your machine. If you can't figure out what it is, we recommend opening an Azure support ticket for help.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem we recommend opening a support ticket via the Azure Portal. Alternatively you can open a new issue here.
