### ISSUE TITLE
An error dialog pops up when clicking 'Copy Blob Container' on the context menu of one Azure AD attached regular blob container (the rbac role is given on Blob Container level)

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6528]
**Storage Explorer Version**: 1.28.0
**Build Number**: 20230208.3
**Branch**: rel/1.28.0
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.2 (Apple M1 Pro)
**Architecture**: ia32/x64/arm64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one non-ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container.
3. Go to portal -> Give the rbac role 'Storage Blob Data Owner' to the blob container (on the blob container level).
4. Go back to storage explorer.
5. Attach the blob container via Azure AD.
6. After successfully attached the blob container.
7. Right click the blob container attachment -> Click 'Copy Blob Container'.
8. Check no error dialog pops up.

## Expected Experience ##
No error dialog pops up.

## Actual Experience ##
An error dialog pops up.
![image](https://user-images.githubusercontent.com/41351993/217492891-f55554e3-10a6-4d80-953d-d89ff9bd8966.png)

Error details:
`Details:
Unable to get user delegation key. Please check the permission of your Azure AD credential.`
## Additional Context ##
1. This issue also reproduces with the role 'Storage Blob Data Contirbutor/Reader'.
2. This issue doesn't reproduce when given the rbac role on storage account level.
3. This issue doesn't reproduce for ADLS Gen2 blob containers.

**Comment by JasonYeMSFT** [comment]
The error makes sense since the user delegation key requires the permission on the storage account. However, we should swallow the error and allow the copy to proceed with just the AAD credential.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230414.2. Fixed. So, we are going close it.
