### ISSUE TITLE
Storage Explorer using insane amount of GPU uploading one file

### ISSUE THREAD

**Issue by simeyla** [Microsoft/AzureStorageExplorer#653]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Win 10
**Architecture**: x64
**Regression From**: NA

#### Steps to Reproduce: ####

I have an i9 laptop with Core i9-8950HK and Intel integrated graphics. Basically the best laptop processor you can even buy.

1. Upload a large file (several 'minutes' long)
2. Observe GPU usage graph in Task manager
3. Minimize Storage Explorer
4. Observe GPU usage graph again
5. Repeat

#### Expected Experience: ####
Storage Explorer would have absolutely negligible effect on GPU especially when uploading one file!

#### Actual Experience: ####
I am doing nothing else with the GPU. 
Negligible usage in other apps.

**Storage Explorer is using almost a third of my GPU. The increase below is when I had it maximized.**

![image](https://user-images.githubusercontent.com/3656278/45325691-77414e80-b506-11e8-86ec-d099fc30ef29.png)

Like I said this is uploading ONE file. 
I minimized the window and GPU usage went down to almost zero (shown above). Once the file finished uploading the GPU usage went down to zero again.

The only thing that is animating is this little icon. It must be runnning at like 500fps!

![image](https://user-images.githubusercontent.com/3656278/45325031-af479200-b504-11e8-95a2-294483649c27.png)

Another test (the 6% is when it is minimized or not uploading).

![image](https://user-images.githubusercontent.com/3656278/45325147-fdf52c00-b504-11e8-90b3-b753b8e62479.png)

**Comment by JakeRadMSFT** [comment]
Thanks for reporting. What is your regular GPU usage vs downloading GPU usage?

Is it ~30% when downloading and ~4% when not downloading?

When downloading we try to only cause re-draws when the percentage changes but perhaps something else is triggering a re-draw.

**Comment by simeyla** [comment]
@JakeRadMSFT Thanks again for your quick response. I realize bug reports like this can often be false positives!

So here's another test - uploading two 45MB files. You can see the GPU usage corresponds exactly to the Wifi upload send graph, falling back to zero when the file completed. 

![image](https://user-images.githubusercontent.com/3656278/45330294-9bf2f180-b519-11e8-94b1-da2630f3077b.png)

For this test I left Storage Explorer maximized the whole time. At least I know how to fix it.

**Comment by simeyla** [comment]
Further testing:

Test 1
If I make the window small, but still include the spinner the GPU rate goes down to about 10%. This suggests to me the whole window or at least that panel - is being updated. As you can probably tell from the size of the screenshot I have a 4k screen - so there's a lot of pixels being moved around.

![image](https://user-images.githubusercontent.com/3656278/45334056-f8f8a280-b52d-11e8-9ae5-ef999e23d031.png)

Test 2
I left the window fullscreen and closed the 'Activities' panel. It went down to virtually 0%. Then I reopend the activities panel / tab and straight back to 30%.

![image](https://user-images.githubusercontent.com/3656278/45334109-39582080-b52e-11e8-8cb7-88f780635203.png)

If you don't have a 4k monitor you'll be getting 1/4 of the pixels for a full HD display so it won't be nearly as apparent.

Test 3 
So I actually have 2 x 4k monitors :-) 
I dragged the window across both screens and made the activities panel as large as I could - then it started taking 80% of my GPU!

I then minimized only that tab, and it went to almost zero. So definitely not *just* the spinner - the whole tab is causing the problem.

![image](https://user-images.githubusercontent.com/3656278/45334569-28101380-b530-11e8-9e65-8656d688ccc0.png)

**Comment by JakeRadMSFT** [comment]
Thanks for performing further tests! That's good to know that minimizing the activities panel reduces it to 0. So it seems like that frame is the culprit.

Thanks!

**Comment by JakeRadMSFT** [comment]
Can you try changing the site.css from 

.activity-log .log-entry .message-column .message-grid .status.InProgress::before {
  content: url(../../images/Common/Halo_ProgressSpinner.svg);
}

to 

.activity-log .log-entry .message-column .message-grid .status.Pending::before {
  content: url(../../images/Common/Time_16x.svg);
}

**Comment by JakeRadMSFT** [comment]
I'm not sure I could convince electron it's their bug. We're just animating it in a GPU intensive way ... we  fairly recently switched to SVGs away from GIF. As you may know, this allows the images to scale well and look great at many different monitor DPI and resolutions. 

Unfortunately, SVG animateTransform is apparently extremely inefficient. We'll have to find an alternative way to show in-progress or an alternative way to animate.

Thanks so much for reporting!

**Comment by simeyla** [comment]
No problem Jake. Glad to be able to help.

Remember to pass on the fact that is it far more noticable on 4k monitors -
about 4 times as much!
