### ISSUE TITLE
Can't re-authenticate.

### ISSUE THREAD

**Issue by sfatz** [microsoft/AzureStorageExplorer#6532]
I try to reauthenticate, it launches my browser to the microsoft sign-in page. I successfully receive and approve the two factor request via my authenticator.

At that point the browser redirects to: https://localhost:30414/?code=0.ATcA_PypQoj7Ak6myg6hAa-T8ZV3sATbjRpGu-4C-eG_e0YcANE.AgABAAIAAAD--DLA3VO7QrddgJg7WevrAgDs_wUA9P-alTGLG73FEiwxUp2gVk-Ah7VwOqFNRM8BAigiijZCZEbP0qCkTn6VzFkLy4AfxgEwOR06IgO-aJ0e67YKeqxHV10kh6Lis_MeRn7y-RzBanprazEsFWqjl7jvl4gSSD0zi455jqSDmyB4E9W-yEixKhF4MgxoMOEMQGZ6Ch90OXuCsAw7vCGfIuHgrm9-p3uLHPPnGUsHeV_4HyGBUDkRhlU7J7hg_5A-AHQUJpUTRcebbKJvysL7nycu4o7m9YbqtiUHp4pYrxhKyL1ujkcpY9IhbqZXxX-JJGgiiKCpowDMq5oe4N-EfNyCxbMvtacKtV5r1_b9dvl2FM0WwCOxiaG9Ad_Ujl0GxLGdwtil9p-tZoBHHM67Lpw1BAEhjzobx5ic12B6_H0-8dn5NMf2fYLZPhMZGQ8VeuZi0WwExHWOtuwJTz9sKl6Wdm2H9nMA2Kkg7vy5lypsBDEbjjHgLpLdQz6jPSzwcl0Iw4PKQzFYCLOw9ZGLXqB3lMKzmDx988ewUBDki8DEnzAxWbhPN0nVS98XHS0625OcRMc79yH54ayWT3Vc8l6X3-tQ0KVJnCUvfg9fz4NEz-2rUO_2Jv_wuJRaEApFWFNPWCRBXHVbpgcT3gTUbD3M30_aTIsI3f_C81Omobgl5I-S42JM_u0qdbVFAnB-Fzr8BtjjIDNwvfKZSJvGJ0mMcAsZG7gD4QHIeyXYdkIr1YJjchvCBBDUlEZrqQJuFVgip5XCTsRyoRD3FMmbig8CKhCDd66MhKQSiRWhuBTn4En8trMmiaAMKbEvVqV2-xU_6VlJ_Y__ivDN2E3ra6_qLPmYnn61UQjijIo5&client_info=eyJ1aWQiOiI2Mjk1OGIzOC1kOTM1LTQwYzQtYTdlZi0zZTY2YjM4MjMwZWQiLCJ1dGlkIjoiNDJhOWZjZmMtZmI4OC00ZTAyLWE2Y2EtMGVhMTAxYWY5M2YxIn0&state=052f7d81-b4ce-45fe-95c7-3f0fe34ac3200fd1981a-b295-4f11-87c2-fc7b1becd214&session_state=483f1637-79cc-44ba-86e3-65a953f230e6

The browser gives me an error when it redirects to localhost. Not sure *why* it redirects to localhost, but I get a browser error, probably because I have nothing running on that port on my local machine.

Storage Explorer never stops waiting for authentication.

**Comment by sfatz** [comment]
Also... the port changes each time... but it always redirects to localhost.

**Comment by MRayermannMSFT** [comment]
@sfatz Storage Explorer is listening on localhost for that redirect. Can you share the error your browser gives you?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem we recommend opening a support ticket via the Azure Portal. Alternatively you can open a new issue here.
