### ISSUE TITLE
Unable to access the content using Azure Storage Explorer published under the resource "ADLS Gen2"

### ISSUE THREAD

**Issue by SK-MSFT** [microsoft/AzureStorageExplorer#6533]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.2

### Architecture

i86

### Platform

Windows

### Bug Description

Hi, I Have access to the Azure Active Directory and required permissions but still unable to access the Windows CE Premium Sources using Azure Storage Explorer published under the resource "ADLS Gen2"

Getting this error, whenever I try to access the content "This request is not authorized to perform this operation using this permission. RequestId:1f3afe21-e01e-008c-0e02-3c7c38000000 Time:2023-02-08T21:15:22.7458847Z"

### Steps to Reproduce

1.	[Install Azure Storage Explorer](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fazure.microsoft.com%2Fen-us%2Ffeatures%2Fstorage-explorer%2F&data=02%7C01%7Cv-dhkuch%40microsoft.com%7C20668f4a2c8e46e8478008d7b0f66879%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637172444665831853&sdata=K5%2BIgZ4kVRR3VTgcWocdOudLt3gmFZRxl4GHWk%2BUWKk%3D&reserved=0)
2.	[Sign In](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fvs-azure-tools-storage-manage-with-storage-explorer%3Ftabs%3Dwindows%23sign-in-to-azure&data=02%7C01%7Cv-dhkuch%40microsoft.com%7C20668f4a2c8e46e8478008d7b0f66879%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637172444665841853&sdata=Caos%2BPBqORHAYb8kk%2FnOjWdB2bzCXNggtL7mQesCNc4%3D&reserved=0)
i.	Following sign-in, it is expected you WILL NOT see a Microsoft Subscription. 
3.	[Add Resource Via Azure Active Directory](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fvs-azure-tools-storage-manage-with-storage-explorer%3Ftabs%3Dwindows%23add-a-resource-via-azure-ad&data=02%7C01%7Cv-dhkuch%40microsoft.com%7C20668f4a2c8e46e8478008d7b0f66879%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637172444665841853&sdata=ukrlXPzS3dgIMjg4Cvc2fV%2FFbL4ZzldATw5p%2B3TMlpA%3D&reserved=0)
	Select your sign in
	Select the Tenant 
Microsoft (72f988bf-86f1-41af-91ab-2d7cd011db47)  
	Resource Type must be ADLS Gen2
	Container URL is [https://dtswsd.dfs.core.windows.net/cepremsourceprogram](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdtswsd.dfs.core.windows.net%2Fcepremsourceprogram&data=02%7C01%7Cv-dhkuch%40microsoft.com%7C20668f4a2c8e46e8478008d7b0f66879%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637172444665851841&sdata=%2BOCR7vHzwuOwsP%2FZeovDn4tbgknNM%2BonH7k2WqCWXlk%3D&reserved=0) 
	Connection Display is user defined and shows up as the connection name in Azure Storage Explorer. You can type in as you prefer.  Recommend last folder name in the path.

After the above steps are successful, you will be able to see the sources in “Blob Containers” in the “Local and Attached” section.

### Actual Experience

"This request is not authorized to perform this operation using this permission. RequestId:1f3afe21-e01e-008c-0e02-3c7c38000000 Time:2023-02-08T21:15:22.7458847Z

### Expected Experience

Should be able to see the content published here

**Comment by MRayermannMSFT** [comment]
@SK-MSFT ultimately if you're seeing this error it means you don't have permissions to view what you're trying to view. This is usually an issue of:
- You have a typo in your URL
- The ACLs on the container are not configured in a way that gives you access 

Please double check your URL for typos, and then talk to whoever administers the ACLs of the data you're trying to view to make sure you have all required permissions. This means at least:
- execute permission on all directories in the paths of directories you wish to access
- read permissions on all directories you wish to access

**Comment by SK-MSFT** [comment]
Worked after getting the permission to the required group. Thanks for all the help
