### ISSUE TITLE
Unable to load the blob under a storage account

### ISSUE THREAD

**Issue by gitFrancis0423** [microsoft/AzureStorageExplorer#6535]
I am new in storage explorer and I got this error when I wan to view a blob of a storage account.  Can you lend me your expertise?

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://cogucfuvcsa001.blob.core.windows.net/?comp=list&include=metadata failed, reason: tunneling socket could not be established, cause=write EPROTO 1129154824:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:\n",
  "stack": "FetchError: request to https://cogucfuvcsa001.blob.core.windows.net/?comp=list&include=metadata failed, reason: tunneling socket could not be established, cause=write EPROTO 1129154824:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:\n\n    at ClientRequest.<anonymous> (C:\\Users\\a000286893\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1491:11)\n    at ClientRequest.emit (node:events:394:28)\n    at ClientRequest.onError (C:\\Users\\a000286893\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tunnel\\lib\\tunnel.js:183:21)\n    at Object.onceWrapper (node:events:514:26)\n    at ClientRequest.emit (node:events:394:28)\n    at TLSSocket.socketErrorListener (node:_http_client:447:9)\n    at TLSSocket.emit (node:events:394:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "ECONNRESET",
  "code": "ECONNRESET"
}

**Comment by MRayermannMSFT** [comment]
Please try enabling system proxy. You can learn more about it here: https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem we recommend opening a support ticket via the Azure Portal. Alternatively you can open a new issue here.
