### ISSUE TITLE
AZCopy High Memory Usage - Uploading 2TB

### ISSUE THREAD

**Issue by unknowndpi** [microsoft/AzureStorageExplorer#6536]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.2

### Architecture

i86

### Storage Explorer Build Number

20230123.2

### Platform

Windows

### OS Version

Windows 10 Build 19045

### Bug Description

azcopy_windows_amd64.exe currently using 5.8GB of memory whilst uploading 2TB of data from a USB drive. It appears to use as much as possible and has been doing so for the last 12 hours. Mem usage currently at 95%.

Uploading data to a blob container.

### Steps to Reproduce

1. Launch Storage Explorer
2. Upload Folder to Blob using Archive tier from USB 3.0 drive. Large amount of files as well as data, totalling 2TB.

### Actual Experience

Program is running OK and uploading but anything else you want to do on the system is obviously very slow, ideally requires a dedicated system at the moment to upload.

### Expected Experience

AzCopy should not be reserving that amount of memory especially as the external disk transfer speed is likely limited to no more than 50Mbps

**Comment by MRayermannMSFT** [comment]
@unknowndpi , as you have seen, AzCopy is very good at using system resources. If you'd like to tone it down, there's a variety of settings in Storage Explorer you can use to do this.

Go to settings (gear on the left) > Transfers > AzCopy. Here you will find all of the AzCopy settings. Probably the easiest one to use is the Network Concurrency settings. Try changing it to adjust dynamically. Beyond that, you can play with any of the other settings to specifically reduce AzCopy's performance as you desire.

**Comment by unknowndpi** [comment]
Transfers > Buffer Size would likely have been the option. Closing off as should have RTFM. Thanks.
