### ISSUE TITLE
Can't cancel the 'changing access tier' activity by clicking 'Cancel' next to the activity log

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6537]
**Storage Explorer Version**: 1.28.0
**Build Number**: 20230209.2
**Branch**: rel/1.28.0
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.2 (Apple M1 Pro)
**Architecture**: ia32/x64/arm64
**How Found**: Exploratory testing
**Regression From**: Previous release (1.26.1)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload a folder contains about 200 files.
3. Right click the folder -> Click 'Change Access Tier...' -> Click 'Apply'.
4. There is an in-progress activity log -> Click 'Cancel' next to the activity log.
5. Check whether succeeds to cancel the activity. 

## Expected Experience ##
Succeed to cancel the activity.
![image](https://user-images.githubusercontent.com/41351993/217738383-c528aadd-5c6e-435f-be32-a88cf298555f.png)

## Actual Experience ##
Can't cancel the activity.

**Comment by JasonYeMSFT** [comment]
@v-xianay When you verify this bug, could you also verify if the "cancel" action on undelete activity also works? The fix was applied on both batch change access tier and batch undelete.

**Comment by v-xianya** [comment]
@JasonYeMSFT ok, thank you for the reminder!
Verified this issue on the build 20230211.3. Fixed.
Also, we tested the undelete activity today, no new issue was found.
