### ISSUE TITLE
An error dialog pops up when trying to create SAS URL for one Azure AD attached regular/ADLS Gen2 blob container (the Azure AD rbac role is given on Blob Container level)

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6540]
**Storage Explorer Version**: 1.28.0
**Build Number**: 20230209.2
**Branch**: rel/1.28.0
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.2 (Apple M1 Pro)
**Architecture**: ia32/x64/arm64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Select one storage account -> Open it in portal.
2. Click 'Containers' -> Add one blob container -> Open it.
3. Click 'Access Control (IAM)' -> Click 'Add -> Add role assignment'.
4. Type role 'Storage Blob Data Owner' -> Click 'Next' -> Select one member to give the rbac role for Azure AD attach.
5. Assign role to the member.
6. Click 'Access Control (IAM)' -> Click 'Add -> Add role assignment'.
7.  Type role 'Storage Blob Data Owner' -> Click 'Next' -> Select one member to give the rbac role for SAS attach via 'User delegation key'.
8. Assign role to the member.
9. Go back to storage explorer -> Select the blob container.
10. Azure AD attach it -> Right click the Azure AD attached blob container.
11. Click 'Get Shared Access Signature...' -> Click 'Create'.
12. Check no error occurs.

## Expected Experience ##
No error occurs.
## Actual Experience ##
An error dialog pops up.

![image](https://user-images.githubusercontent.com/41351993/217768591-3ed96b70-9a4d-4d36-876a-674cd6708e01.png)

## Additional Context ##
This issue also reproduces for ADLS Gen2 blob containers. Below is the error:
![image](https://user-images.githubusercontent.com/41351993/217768832-7e99b8ef-f540-4bc8-aae8-78a900bb34eb.png)

**Comment by JasonYeMSFT** [comment]
The error is expected. To generate a user delegation SAS, the user must have the permission to get the user delegation key, which is on the storage account level.

**Comment by v-xianya** [comment]
@JasonYeMSFT thank you for the update! Could you help to elaborate why the behaviors below are different?
Give one blob container rbac role for Azure AD attach on the storage account level.
1. If SAS attach the blob container via 'User delegation key', there is an error info bar telling 'This request is not authorized to perform this operation using this permission'. 
2.If Azure AD attach the blob container first -> Select the Azure AD attachment -> SAS attach the Azure AD attachment via 'User delegation key', There is no error info bar.

Here is the record:


https://user-images.githubusercontent.com/41351993/218671562-19f2859e-0d51-41de-9ea3-bc51c13c9558.mov

**Comment by JasonYeMSFT** [comment]
I don't know for sure. Could you send the logs to see which request fails?

**Comment by v-xianya** [comment]
sure. sent the logs in teams.
