### ISSUE TITLE
The associated node is not selected if clicking 'Refresh All' then clicking the opened tab

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6541]
**Storage Explorer Version**: 1.28.0
**Build Number**: 20230209.2
**Branch**: rel/1.28.0
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.2 (Apple M1 Pro)
**Architecture**: ia32/x64/arm64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Open one blob container.
3. Refresh the tree view by clicking 'Refresh All'.
4. Click the opened blob container tab.
5. Check whether the associated node is selected.

## Expected Experience ##
The associated node is selected.

## Actual Experience ##
Nothing happens to the tree view.

## Additional Context ##
1. This issue also reproduces for file shares/queues/tables/resource groups.
2. This issue also reproduces if clicking 'Refresh' on the context menu of the storage account.

**Comment by JasonYeMSFT** [comment]
This is by design. Refreshing the storage account will unload the container nodes which temporarily breaks the association because the node is no longer in the tree. If the user re-expand the container nodes and the container still exist the association will be restored.
