### ISSUE TITLE
There is a failed activity log when cloning one page blob under one premium account

### ISSUE THREAD

**Issue by v-sunnsun** [microsoft/AzureStorageExplorer#6542]
**Storage Explorer Version** : 1.28.0
**Build Number** : 20230209.2 
**Branch**: rel/1.28.0
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.2 (Apple M1 Pro)
**Architecture**:  ia32/x64/arm64
**How Found**: From running test case
**Regression From**: Previous release (1.27.2) 

## Steps to Reproduce 

1. Expand one premium storage account -> Blob Containers.
2. Create a blob container -> Upload one page blob to it.
3. Right click the blob -> Click 'clone...'
4. Input a valid name -> Click 'clone'.
5. Check whether there is a successful activity log.

## Expected Experience 
There is a successful activity log.
## Actual Experience 
There is a failed activity log with an error 'UnexpectedQuit'.
![image](https://user-images.githubusercontent.com/122582307/217993729-aa9fa861-72e0-49fa-a6af-72291031b4f3.png)

**Comment by v-xianya** [comment]
Verified this issue on the build 20230211.3. Fixed.
