### ISSUE TITLE
Better to keep a consistent format for the filter string on the address bar between blob containers and file shares

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6543]
**Storage Explorer Version**: 1.28.0
**Build Number**: 20230209.2
**Branch**: rel/1.28.0
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.2 (Apple M1 Pro)
**Architecture**: ia32/x64/arm64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Open one blob container -> Type 's' into the filter by prefix box.
3. Observe the filter string on the address bar.
4. Open one file share -> Type 's' into the filter by prefix box.
5. Observe the filter string on the address bar.
6. Check whether the filter string format is consistent.

## Expected Experience ##
The filter string format is consistent.

## Actual Experience ##
The filter string format is inconsistent.
![image](https://user-images.githubusercontent.com/41351993/218022606-45f8a739-cc27-4eba-890f-4ac69c95ecbd.png)

**Comment by richardMSFT** [comment]
Shipping with 1.29.0.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230217.3. Reproduce.
So, we are going to re-open it and verify it on a newer build. Will close it once it got fixed.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230226.1. Fixed.
The string for the regular blob container has been updated. So, we are going to close it.
![image](https://user-images.githubusercontent.com/41351993/221526412-0028bf4b-a897-4140-8321-373553c17dd8.png)
