### ISSUE TITLE
1.27.2 still requires System.Numerics.Vectors, Version=4.1.3.0

### ISSUE THREAD

**Issue by MC776237** [microsoft/AzureStorageExplorer#6544]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.2

### Architecture

i86

### Storage Explorer Build Number

can't open it

### Platform

Windows

### OS Version

Windows 11

### Bug Description

Storage Explorer refuses to start in the logs one can read:

are disconnecting from the rpc. Reason: StreamError, Description: ... FileLoadException: File or Assembly "System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" not found

Which is correct because I only have 4.1.4 in assembly cache
so if Storage Explorer needs this specific asembly it should deploy it!

### Steps to Reproduce

1. Launch Storage Explorer

### Actual Experience

can't use it

**Comment by MRayermannMSFT** [comment]
@MC776237 you will need to acquire the .dll yourself.
