### ISSUE TITLE
Sort by Last Modified Date treated as text

### ISSUE THREAD

**Issue by TLBannister** [microsoft/AzureStorageExplorer#655]
**Storage Explorer Version**: 1.4.1
**Platform/OS Version**: Windows
**Architecture**: 
**Regression From**: 

#### Steps to Reproduce: ####
1. View documents in an Active storage blob, click Last Modified column header to sort desc; 
Dates are sorted as text, and not a true Date

#### Expected Experience: ####
would expect to see all of January yyyy, followed by all of February yyyy, all of March yyyy

#### Actual Experience: ####
2/14/2018, followed by 3/14/2018. 4/14/2018. 5/14/2018, etc.

**Comment by dudeNumber4** [comment]
I don't see any way to "upvote" here.  But yeah, much pain.

**Comment by MRayermannMSFT** [comment]
This was fixed at some point. If you still seeing it after upgrading to the latest Storage Explorer please open a new issue.
