### ISSUE TITLE
storage account blobchangefeed delete feature

### ISSUE THREAD

**Issue by realDeveloper45** [microsoft/AzureStorageExplorer#6550]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I'm trying to delete the **blobchangefeed** logs from storage account. _Failed to delete 1 out of 1 blobs or directories: meta.json: The account being accessed does not have sufficient permissions to execute this operation_. It has accumulated lot of data and costing us dearly. When I try to delete the logs it says not authorized even though I have all the permissions. I can delete normal containers and blobs from the storage container.

### Desired Solution

I'd like to delete the log and index blobs from blobchangefeed container

**Comment by MRayermannMSFT** [comment]
@realDeveloper45 this is expected. You cannot delete the change feed logs yourself. You can control how long logs are kept by managing the blob change feed log retention settings in the portal. If you have trouble doing this, we recommend reaching out to Azure support for help.
