### ISSUE TITLE
An error occurs when launching Storage Explorer on Windows/Mac

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6551]
**Storage Explorer Version:** 1.28.0
**Build Number:** 20230211.3
**Branch:** rel/1.28.0
**Platform/OS:** Windows 10/MacOS Ventura 13.2 (Apple M1 Pro)
**Architecture:** ia32/x64/arm64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Install and launch Storage Explorer.
2. Check whether no error occurs.

## Expected Experience ##
No error occurs.

## Actual Experience ##
An error occurs.
![image](https://user-images.githubusercontent.com/87792676/218358672-d2feac1f-caae-4f10-96a9-c78fed37346c.png)

## Additional Context ##

1. This issue can't be reproduced consistently.
2. This issue doesn't reproduce on Linux.
3. This issue also reproduces after clicking 'Refresh All'.

**Comment by MRayermannMSFT** [comment]
@v-kellyluo can y'all please enable DEBUG logging and share logs with us whenever you reproduce this?

**Comment by v-kellyluo** [comment]
@MRayermannMSFT , here is the logs collected on Windows:
[2023-02-13_174818.zip](https://github.com/microsoft/AzureStorageExplorer/files/10727873/2023-02-13_174818.zip)

**Comment by v-kellyluo** [comment]
@MRayermannMSFT, here are the logs collected on Windows:
[2023-02-13_174818.zip](https://github.com/microsoft/AzureStorageExplorer/files/10727919/2023-02-13_174818.zip)

**Comment by MRayermannMSFT** [comment]
@v-kellyluo are y'all still able to reproduce this?

**Comment by v-kellyluo** [comment]
Hi @MRayermannMSFT , Yes, this issue still reproduces inconsistenly.

**Comment by MRayermannMSFT** [comment]
Thanks for the response. The new tree view has additional logging that the old one did not. Now that we're using the new tree view, can you share a newer set of logs?
