### ISSUE TITLE
A new ADLS Gen1 account tab opens by clicking 'Open' even though there is already an opened tab

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6552]
**Storage Explorer Version:** 1.28.0
**Build Number:** 20230211.3
**Branch:** rel/1.28.0
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.2 (Apple M1 Pro)
**Architecture:** ia32/x64/arm64
**How Found:** From running test cases
**Regression From:** Previous release (1.27.2)

## Steps to Reproduce ##

1. Expand 'Data Lake Storage Gen1 (Preview)' node.
2. Right click one ADLS Gen1 account -> Click 'Open'.
3. An ADLS Gen1 account tab opens.
4. Right click the ADLS Gen1 account again -> Click 'Open'.
5. Check whether no new tab opens.

## Expected Experience
No new tab opens.

## Actual Experience ##
A new tab opens.

## Additional Context ##
This issue also reproduces when double clicking the ADLS Gen1 account.

**Comment by JasonYeMSFT** [comment]
When we switched to use resourceUid to identify node-tab association, Gen1 isn't updated since it will be retired in 1.29.0.
