### ISSUE TITLE
The sub activity logs do not match the group activity log when cancelling undelete blobs activity

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6556]
**Storage Explorer Version**: 1.28.0
**Build Number**: 20230213.4
**Branch**: rel/1.28.0
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.2 (Apple M1 Pro)
**Architecture**: ia32/x64/arm64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload serval blobs.
3. Soft delete the blobs -> Switch to the context view 'Active and soft deleted blobs'.
4. Select the soft deleted blobs -> Click 'Undelete -> Undelete Selected'.
5. Click 'Cancel all' next to the undeleted activity log.
6. Expand the activity log.
7. Check whether the sub activity logs match the group activity log.

## Expected Experience ##
The sub activity logs match the group activity log.
## Actual Experience ##
The sub activity logs do not match the group activity log.
![image](https://user-images.githubusercontent.com/41351993/218659022-27833119-d9ac-4890-94e4-171a3b357903.png)

## Additional Context ##
1. The soft deleted blobs go back to active after manually refreshing.
2. This issue also reproduces for ADLS Gen2 blobs.

**Comment by v-xianya** [comment]
@JasonYeMSFT Verified this issue on the build main 20230226.1. The current behavior as below:
Could you help to have a look?
1. When trying to cancel undelete activity, display successfully undelete activity log.
2. The soft deleted blobs still show deleted status after showing 'undelete succeeded' in Activities. (the deleted blobs become active after manually refreshing).
![image](https://user-images.githubusercontent.com/41351993/221527611-34b2d21f-bf82-4440-a462-68c817e67b39.png)

**Comment by JasonYeMSFT** [comment]
That's expected. Even if you cancel, some of the in-progress requests may still succeed. We don't refresh as long as the user has clicked cancel and it's up to the user to figure out the partial result of the operations.
