### ISSUE TITLE
Stuck loading on MacOS

### ISSUE THREAD

**Issue by jmphotoimages** [microsoft/AzureStorageExplorer#656]
**Storage Explorer Version**: 1.4.1
**Platform/OS Version**: MacOS 10.12.6
**Architecture**: x64
**Regression From**: N/A

#### Steps to Reproduce: ####
1. Installed the app.
2. Tried to run the app.  Stuck at "Loading".

#### Expected Experience: ####
Present a sign in prompt or some sign of working.

#### Actual Experience: ####
App spins forever saying "Loading"

**Comment by balintlaca** [comment]
![Screenshot 2019-12-13 at 16 19 37](https://user-images.githubusercontent.com/58855935/70810963-06ea4280-1dc5-11ea-99a7-937d0b5e4852.png)
 It was working until the first "Quit". Since then I have this screen for hours.

**Comment by MRayermannMSFT** [comment]
@balintlaca and @ jmphotoimages  are you still having problems? Please upgrade to the latest Storage Explorer and let us know if your issue still occurs. Thanks.

**Comment by JasonYeMSFT** [comment]
@balintlaca May be related to https://github.com/microsoft/AzureStorageExplorer/issues/2463

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you're still having problems. Thanks.
