### ISSUE TITLE
Can't use SAS connection strings generated from a key-attached storage account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6560]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230215.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Select one storage account -> Use name & key to attach it.
2. Right click the name & key attached storage account.
3. Click 'Get Shared Access Signature...' -> Click 'Create'.
4. Copy the connection string -> Paste it to a clipboard or a text file.
5. Check whether the format of the connection string is correct.

## Expected Experience ##
The format of the connection string is correct.
## Actual Experience ##
The format of the connection string is incorrect.
![image](https://user-images.githubusercontent.com/41351993/218964581-00268fcb-9eb6-42d2-8c26-28da2dc09e9b.png)

**Comment by craxal** [comment]
Well, the connection string is clearly missing information. You can't connect to anything with just a SAS. You need endpoints, or at least an account name. So the problem is probably where the SAS is generated.

**Comment by v-xianya** [comment]
Hi @craxal Verified this issue on the main build 20230330.3.
The connection string is not correct but the error message has been removed. Could you please take a look?
![image](https://user-images.githubusercontent.com/41351993/228713702-e6487918-6e72-45b4-aba5-8fc044d7aff5.png)

**Comment by v-xianya** [comment]
@craxal the comments issue has been fixed with the bug[ 6737](https://github.com/microsoft/AzureStorageExplorer/issues/6737). 

This bug still reproduces on the new build 20230413.5. So we are going to re-open it.

**Comment by craxal** [comment]
I'm using the same build (20230413.5), but it doesn't reproduce on my end. Please verify again, and if it still reproduces, please share the connection string in text (not a screenshot) you use (be sure it's secure).

**Comment by v-xianya** [comment]
Hi @craxal 
To make sure we are on the same page.

- The behavior I expected is 'the connection string is correct when creating by clicking 'Get Shared Access Signature...' against a name & key attached storage account.

- The current behavior is 'the connection string created by clicking 'Get Shared Access Signature...' against a name & key attached storage account is incorrect. and prompts a clear error message when pasting on 'Connection string' field. 

For secure, I will share the connection string on teams.

**Comment by craxal** [comment]
@v-xianya Using build 20230416.3, the SAS dialog from my end appears to be generating a valid SAS. Are you still able to reproduce? Am I missing something?

**Comment by v-xianya** [comment]
@craxal I am able to reproduce on the new build 20230418.4. The SAS is created against a name & key attached storage account node.
![image](https://user-images.githubusercontent.com/41351993/232652144-c366c49d-5dd1-43da-b7f1-24db073e7171.png)

@MRayermannMSFT  
It's not a regression. For name & key attached storage account, the action 'Get Shared Access Signature...' is added from the version 1.25.0. The related issue [5818](https://github.com/microsoft/AzureStorageExplorer/issues/5818)

**Comment by craxal** [comment]
@v-xianya Oh, I see. The SAS was generated from an _attached_ storage account. That's what I wasn't understanding. Yeah, key-attached connection strings don't explicitly define the endpoints, so we will need to infer them when generating the SAS. I've got a fix.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230419.4. Fixed.
