### ISSUE TITLE
There is no action item 'Detach' for broken attachments

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6562]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230215.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.0)

## Steps to Reproduce ##
1. Use Azure AD attach to one blob container (make sure already given the correct RBAC role).
2. Switch to the 'ACCOUNT MANAGEMENT' panel -> Remove the azure account that associated with the Azure AD attachments.
3. Switch to the 'EXPLORER' panel.
4. The Azure AD attached blob container shows as broken.
5. Right click the broken attachment -> Observe the context menu.
6. Check there is an action item 'Detach'.

## Expected Experience ##
There is an action item 'Detach'.
![image](https://user-images.githubusercontent.com/41351993/218980353-b4524aec-0ba3-4f25-bfc6-c62b11802c15.png)

## Actual Experience ##
There is no action item 'Detach'.
![image](https://user-images.githubusercontent.com/41351993/218980646-edcdd962-07d7-4d23-8472-d228e828b0f9.png)

## Additional Context ##
This issue also reproduces for queues/tables.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20230304.8. Fixed.
![image](https://user-images.githubusercontent.com/87792676/223001150-f6beac67-2cda-4f31-8f53-e088f7ad3532.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20230304.8, this issue only fixed for broken blob containers.
It still reproduces for broken queues/tables, so we are going to reopen it.
![image](https://user-images.githubusercontent.com/87792676/223002272-45be3195-d1cc-447e-9136-a09254ba7457.png)

**Comment by MRayermannMSFT** [comment]
Ok, let's try again. 😀

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20230306.6. Fixed.
