### ISSUE TITLE
No new tab is opened when attaching one queue/table

### ISSUE THREAD

**Issue by v-sunnsun** [microsoft/AzureStorageExplorer#6563]
**Storage Explorer Version** : 1.29.0-dev
**Build Number** : 20230215.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.0)

## Steps to Reproduce 

1. Expand one storage account -> Queues.
2. Create a queue -> Right click the queue -> Click 'Get Shared Access Signature...'.
3. Click 'Create' -> Copy the SAS URL.
4. Open the connect dialog -> Attach the queue via the copied SAS URL.
5. Check whether a new queue tab is opened.

## Expected Experience 
A new queue tab is opened.
## Actual Experience ##
No new queue tab is opened.
## Additional Context  ##
This issue also reproduces for Azure AD attached queue.

**Comment by craxal** [comment]
@v-sunnsun The issue title also says "table". Does this also reproduce for tables, or is this just for queues?

**Comment by craxal** [comment]
I also encounter an error when I attempt to attach a table. This does not reproduce for blobs. Here's what it says in the log:

> [2023-02-23T19:24:13.233Z] (se-table-extension:29702) <CRIT> Unhandled rejection, reason: Error: Unable to execute operation 'CloudExplorer.ElementInteraction.getPathByUid'. No implementation has been registered.

@MRayermannMSFT I noticed that the line that registers the `CloudExplorer.ElementInteraction.getPathByUid` function is commented out. Yet for some reason it still works for some resource types and not for others. Any ideas?

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230302.17. Fixed.
So, we are going to close it.
