### ISSUE TITLE
The message order is incorrect

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6568]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230216.5
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.0)

## Steps to Reproduce ##
1. Expand one storage account -> Queues.
2. Create a queue -> Add three messages -> Type '1', '2', '3' as the message text orderly.
3. Check the order of the message is correct.

## Expected Experience ##
The order of the message is correct.
![image](https://user-images.githubusercontent.com/41351993/219288540-4699d9e6-b49d-4161-8a5a-238a3b6154f5.png)

## Actual Experience ##
The order of the message is incorrect.
![image](https://user-images.githubusercontent.com/41351993/219288567-a88586c3-4039-4760-908b-35b58c4072f3.png)

**Comment by craxal** [comment]
@v-xianya In the Actual screenshot, you are sorting by message ID, and the IDs are sorted correctly. If you click the Insertion Time column, do the columns sort correctly?

**Comment by v-xianya** [comment]
@craxal 
`If you click the Insertion Time column, do the columns sort correctly? `

Click the Insertion Time column, the Insertion Time & Message Text columns are sorted correctly.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20231226.1. Fixed.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20230226.1. Fixed.
