### ISSUE TITLE
All actions are enabled on the toolbar after dequeuing all messages or clear queue with one message got selected

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6571]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230216.5
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.0)

## Bug Descriptions ##
This issue reproduces for the actions 'Dequeue Message & Move Messages & Clear Queue'.

## Steps to Reproduce ##
1. Expand one storage account -> Queues.
2. Create a new queue -> Add one message -> Select the message -> Dequeue the message.
3. Observe the toolbar.
4. Check whether only the actions 'Add Message & Clear Queue' are enabled.

## Expected Experience ##
Only the actions 'Add Message & Clear Queue' are enabled.

## Actual Experience ##
All actions are enabled.
![image](https://user-images.githubusercontent.com/41351993/219310167-c614bc19-4fc7-4af4-952c-6ce2abc548e1.png)

## Additional Context ##
1. This issue doesn't reproduce for 'Clear Queue' when no message is selected.
2. This issue doesn't reproduce for the split tab.
![image](https://user-images.githubusercontent.com/41351993/219310258-2ad7b67d-2c59-408a-bf70-c2006a302a83.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20231226.1. Fixed.
![image](https://user-images.githubusercontent.com/87792676/221487403-4dc0e933-429a-4081-95aa-73018bf70eb1.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20230226.1. Fixed.
![image](https://user-images.githubusercontent.com/87792676/221487977-3f9868fc-4201-4989-9bca-0644e0e4f5d0.png)
