### ISSUE TITLE
The description of the status string is incorrect for one empty queue

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6573]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230216.5
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.0)

## Steps to Reproduce ##
1. Expand one storage account -> Queues.
2. Create a new queue.
3. Observe the status string on the queue explorer.
4. Check whether the description of the status string is correct.

## Expected Experience ##
The description of the status string is correct.

## Actual Experience ##
The description of the status string is incorrect.
![image](https://user-images.githubusercontent.com/41351993/219324022-ccec483f-7918-4666-ab2d-df12cca0ab7f.png)

## Additional Context ##
The screenshot on the 1.28.0 version:
![image](https://user-images.githubusercontent.com/41351993/219324216-e26d6932-d2ee-4003-9249-aad3aef67efb.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20230226.1. Fixed.
