### ISSUE TITLE
No status information is displayed and always keep loading when running search with the option 'All' checked

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6574]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230217.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.0)

## Steps to Reproduce ##
1. Launch storage explorer -> Open the search filter dropdown.
2. Check the option 'All'.
3. Type a string to 'Search for resources' box -> Run search.
4. Check whether the status information is displayed.

## Expected Experience ##
The status information is displayed.
![image](https://user-images.githubusercontent.com/41351993/219561790-648cc179-4321-4c9f-9cab-7ba02020440a.png)

## Actual Experience ##
1. No status information is displayed.
2. Always keep loading.
![image](https://user-images.githubusercontent.com/41351993/219561599-7159e309-b0e2-4666-bc8e-bdc60f47cf3c.png)

**Comment by MRayermannMSFT** [comment]
@JasonYeMSFT feel free to assign back to me if this is an issue with the new tree view instead of with the new 'All' option.

**Comment by v-xianya** [comment]
Verified this issue on the build 20230219.3. Fixed. So, we are going to close it.
