### ISSUE TITLE
There is no 'X' button on the search box when running search with the option 'All' checked

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6575]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230217.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.0)

## Steps to Reproduce ##
1. Launch storage explorer -> Open the search filter dropdown.
2. Check the option 'All'.
3. Type a string to 'Search for resources' box -> Run search.
4. Check whether there is a 'X' button on the search box.

## Expected Experience ##
There is a 'X' button on the search box.
![image](https://user-images.githubusercontent.com/41351993/219565068-b02c2a2c-0d1e-46a1-8026-2e3c08adaca9.png)

## Actual Experience ##
There is no 'X' button on the search box.
![image](https://user-images.githubusercontent.com/41351993/219565151-40332a0c-2c20-42ec-8ade-0bc2c8b3344a.png)

**Comment by MRayermannMSFT** [comment]
@JasonYeMSFT feel free to assign back to me if this is an issue with the new tree view instead of with the new 'All' option.

**Comment by v-xianya** [comment]
Verified this issue on the build 20230219.3. Fixed. So, we are going to close it.
