### ISSUE TITLE
Not possible to create subresources from file share

### ISSUE THREAD

**Issue by FabianoPaoliniAgo** [microsoft/AzureStorageExplorer#6578]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.2

### Architecture

x64

### Storage Explorer Build Number

20230123.2

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Not possible to create subresources from file share

Non è possibile recuperare le risorse figlio.

Dettagli:
{
  "name": "RestError",
  "message": "request to https://acidockerstorageago.file.core.windows.net/?comp=list failed, reason: getaddrinfo ENOTFOUND acidockerstorageago.file.core.windows.net",
  "stack": "RestError: request to https://acidockerstorageago.file.core.windows.net/?comp=list failed, reason: getaddrinfo ENOTFOUND acidockerstorageago.file.core.windows.net\n    at NodeFetchHttpClient.sendRequest (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:122907)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async CoreHttpLogHttpClient.sendRequest (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:476740)\n    at async StorageRetryPolicy.attemptSendRequest (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:347563)\n    at async StorageClientContext.sendOperationRequest (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:168771)\n    at async ShareServiceClient.listSharesSegment (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:415665)",
  "code": "REQUEST_SEND_ERROR",
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://acidockerstorageago.file.core.windows.net/?comp=list",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2021-10-04"
        },
        "accept": {
          "name": "Accept",
          "value": "application/xml"
        },
        "user-agent": {
          "name": "User-Agent",
          "value": "Microsoft Azure Storage Explorer/1.27.2 (win32) azsdk-js-storagefile/12.12.0 (NODE-VERSION v16.16.0; Windows_NT 10.0.19045)"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "e90ce385-ad80-4e02-944d-5f56fdb78d4a"
        },
        "x-ms-date": {
          "name": "x-ms-date",
          "value": "Fri, 17 Feb 2023 09:33:11 GMT"
        },
        "authorization": {
          "name": "authorization",
          "value": "Signed SharedKey Redacted="
        },
        "cookie": {
          "name": "Cookie",
          "value": ""
        }
      }
    },
    "withCredentials": false,
    "timeout": 0,
    "keepAlive": true,
    "decompressResponse": false,
    "requestId": "e90ce385-ad80-4e02-944d-5f56fdb78d4a",
    "operationSpec": {
      "path": "/",
      "httpMethod": "GET",
      "responses": {
        "200": {
          "bodyMapper": {
            "serializedName": "ListSharesResponse",
            "xmlName": "EnumerationResults",
            "type": {
              "name": "Composite",
              "className": "ListSharesResponse",
              "modelProperties": {
                "serviceEndpoint": {
                  "serializedName": "ServiceEndpoint",
                  "required": true,
                  "xmlName": "ServiceEndpoint",
                  "xmlIsAttribute": true,
                  "type": {
                    "name": "String"
                  }
                },
                "prefix": {
                  "serializedName": "Prefix",
                  "xmlName": "Prefix",
                  "type": {
                    "name": "String"
                  }
                },
                "marker": {
                  "serializedName": "Marker",
                  "xmlName": "Marker",
                  "type": {
                    "name": "String"
                  }
                },
                "maxResults": {
                  "serializedName": "MaxResults",
                  "xmlName": "MaxResults",
                  "type": {
                    "name": "Number"
                  }
                },
                "shareItems": {
                  "serializedName": "ShareItems",
                  "xmlName": "Shares",
                  "xmlIsWrapped": true,
                  "xmlElementName": "Share",
                  "type": {
                    "name": "Sequence",
                    "element": {
                      "type": {
                        "name": "Composite",
                        "className": "ShareItemInternal"
                      }
                    }
  
.....

### Steps to Reproduce

1. Launch Storage Explorer
2. Expand File Shares

### Actual Experience

Not possible to create subresources from file share

Non è possibile recuperare le risorse figlio.

Dettagli:
{
  "name": "RestError",
  "message": "request to https://acidockerstorageago.file.core.windows.net/?comp=list failed, reason: getaddrinfo ENOTFOUND acidockerstorageago.file.core.windows.net",
  "stack": "RestError: request to https://acidockerstorageago.file.core.windows.net/?comp=list failed, reason: getaddrinfo ENOTFOUND acidockerstorageago.file.core.windows.net\n    at NodeFetchHttpClient.sendRequest (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:122907)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async CoreHttpLogHttpClient.sendRequest (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:476740)\n    at async StorageRetryPolicy.attemptSendRequest (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:347563)\n    at async StorageClientContext.sendOperationRequest (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:168771)\n    at async ShareServiceClient.listSharesSegment (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:415665)",
  "code": "REQUEST_SEND_ERROR",
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://acidockerstorageago.file.core.windows.net/?comp=list",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2021-10-04"
        },
        "accept": {
          "name": "Accept",
          "value": "application/xml"
        },
        "user-agent": {
          "name": "User-Agent",
          "value": "Microsoft Azure Storage Explorer/1.27.2 (win32) azsdk-js-storagefile/12.12.0 (NODE-VERSION v16.16.0; Windows_NT 10.0.19045)"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "e90ce385-ad80-4e02-944d-5f56fdb78d4a"
        },
        "x-ms-date": {
          "name": "x-ms-date",
          "value": "Fri, 17 Feb 2023 09:33:11 GMT"
        },
        "authorization": {
          "name": "authorization",
          "value": "Signed SharedKey Redacted="
        },
        "cookie": {
          "name": "Cookie",
          "value": ""
        }
      }
    },
    "withCredentials": false,
    "timeout": 0,
    "keepAlive": true,
    "decompressResponse": false,
    "requestId": "e90ce385-ad80-4e02-944d-5f56fdb78d4a",
    "operationSpec": {
      "path": "/",
      "httpMethod": "GET",
      "responses": {
        "200": {
          "bodyMapper": {
            "serializedName": "ListSharesResponse",
            "xmlName": "EnumerationResults",
            "type": {
              "name": "Composite",
              "className": "ListSharesResponse",
              "modelProperties": {
                "serviceEndpoint": {
                  "serializedName": "ServiceEndpoint",
                  "required": true,
                  "xmlName": "ServiceEndpoint",
                  "xmlIsAttribute": true,
                  "type": {
                    "name": "String"
                  }
                },
                "prefix": {
                  "serializedName": "Prefix",
                  "xmlName": "Prefix",
                  "type": {
                    "name": "String"
                  }
                },
                "marker": {
                  "serializedName": "Marker",
                  "xmlName": "Marker",
                  "type": {
                    "name": "String"
                  }
                },
                "maxResults": {
                  "serializedName": "MaxResults",
                  "xmlName": "MaxResults",
                  "type": {
                    "name": "Number"
                  }
                },
                "shareItems": {
                  "serializedName": "ShareItems",
                  "xmlName": "Shares",
                  "xmlIsWrapped": true,
                  "xmlElementName": "Share",
                  "type": {
                    "name": "Sequence",
                    "element": {
                      "type": {
                        "name": "Composite",
                        "className": "ShareItemInternal"
                      }
                    }
  ....

**Comment by JasonYeMSFT** [comment]
The error is a DNS resolution error (Storage Explorer cannot find the server hosting your file share). Are you using a proxy? I recommend setting the proxy setting to "use system proxy" to see if the problem is resolved.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue we recommend opening an Azure support ticket from the Azure Portal. Alternatively you can open a new issue here.
