### ISSUE TITLE
The 'Filter by prefix (case-sensitive)' box is not localized for ADLS Gen2 blob containers/file shares

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6579]
**Storage Explorer Version:** 1.29.0-dev
**Build Number:** 20230219.3
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Reproduce Languages:** All languages
**Architecture:** ia32/x64
**How Found:** From running test case
**Regression From:** Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select 'España' -> Restart Storage Explorer.
3. Expand one ADLS Gen2 storage account -> Blob Containers.
4. Create a blob container -> Observe the explorer.
5. Check the 'Filter by prefix (case-sensitive)' box is localized.

## Expected Experience ##
The 'Filter by prefix (case-sensitive)' box is localized.

## Actual Experience ##
The 'Filter by prefix (case-sensitive)' box is not localized.
![image](https://user-images.githubusercontent.com/87792676/220037988-d31e633a-91d2-42c1-96d2-637847e17626.png)

## Additional Context ##
This issue also reproduces for file shares.

**Comment by richardMSFT** [comment]
Verified it is localized with most recent build on the main branch.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20230301.10. Fixed.
