### ISSUE TITLE
Display 'Deleted blob...'  not 'Deleted blobs...' on 'Delete blobs' dialog when deleting one blob

### ISSUE THREAD

**Issue by v-haiz** [Microsoft/AzureStorageExplorer#658]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture**: ia32
**Build Number**:20180911.1
**Commit**: 5a9d37a6
**Regression From**: Not a regression

**Steps to Reproduce**:
1. Open one blob container which contains one blob at least -> Delete one blob then check the message on the 'Delete' dialog.

**Expected Experience**:
 It displays "Deleted **blob** will be... "

**Actual Experience**:
It displays "Deleted **blobs** will be..."
![actual](https://user-images.githubusercontent.com/37653604/45415190-94902d00-b66c-11e8-9451-a807f9374bf7.png)

**More Info:**
Display '**entities**' when deleting one entity for a table.
![actual1](https://user-images.githubusercontent.com/37653604/45415003-29def180-b66c-11e8-8dfb-e96429f0cd24.PNG)

**Comment by craxal** [comment]
The blob deletion is by design the statement is about blobs in general, not the selected blobs. Note that the second sentence says "delete the selected _item_".

I don't think we're going to worry about tables unless a customer really wants it fixed.
