### ISSUE TITLE
The 'Collapse all' and 'Refresh all' strings are not localized

### ISSUE THREAD

**Issue by v-sunnsun** [microsoft/AzureStorageExplorer#6580]
**Storage Explorer Version** : 1.29.0-dev
**Build Number** : 20230219.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Reproduce Language**s: All languages
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.0)

## Bug Description ##

1. The 'EXPLORER' string is not localized.
2. The 'Search for resources' string in search box is not localized.
3. The 'Actions' and 'Properties' strings are not localized.
4. The 'Collapse all' and 'Refresh all' strings are not localized

## Steps to Reproduce 

1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select 'España' -> Restart Storage Explorer.
3. Switch to 'EXPLORER' panel.
4. Check the 'Collapse all' and 'Refresh all' strings are localized.

## Expected Experience 
The 'Collapse all' and 'Refresh all' strings are localized.
## Actual Experience ##
The 'Collapse all' and 'Refresh all' strings are not localized.
![image](https://user-images.githubusercontent.com/122582307/220048678-f37cc2a8-44e8-47a9-8108-ded76a8cea17.png)
![image](https://user-images.githubusercontent.com/122582307/220052211-ed583c90-6d86-4b14-8291-5ad155642bd2.png)

**Comment by MRayermannMSFT** [comment]
The strings are being translated now.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230307.6. Fixed.
