### ISSUE TITLE
The string 'Search From Here' is not localized

### ISSUE THREAD

**Issue by v-sunnsun** [microsoft/AzureStorageExplorer#6581]
**Storage Explorer Version** : 1.29.0-dev
**Build Number** : 20230219.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Reproduce Language**s: All languages
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.0)

## Steps to Reproduce 

1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select 'España' -> Restart Storage Explorer.
3. Switch to 'EXPLORER' panel.
4. Right click one storage account.
5. Check the string 'Search From Here' is localized.

## Expected Experience 
The string 'Search From Here' is localized.
## Actual Experience ##
The string 'Search From Here' is not localized.
![image](https://user-images.githubusercontent.com/122582307/220058180-06f46e60-b588-4da6-97df-d32c91d967ff.png)

## Additional Context
This issue also reproduces for Actions panel.

**Comment by MRayermannMSFT** [comment]
The strings are being translated now.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230307.6. Fixed.
