### ISSUE TITLE
Use user defined name

### ISSUE THREAD

**Issue by Jigar191089** [microsoft/AzureStorageExplorer#6582]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

same container name in different ADLS2, each container given custom name in quick access. When these containers are opened all have the same name. this leads to confusion

### Desired Solution

user defined name should be shown

**Comment by Jigar191089** [comment]
![snapshot](https://user-images.githubusercontent.com/57526133/220104011-79b0c0d3-7635-418a-96b3-ba2456815368.jpg)
screenshot explaining the request

**Comment by JasonYeMSFT** [comment]
We have an open work item tracking this issue. https://github.com/microsoft/AzureStorageExplorer/issues/543. I moved it out of future so we can go over it in our next triage.
