### ISSUE TITLE
Unable to access storage account using Azure Storage Explorer

### ISSUE THREAD

**Issue by anandfranklin** [microsoft/AzureStorageExplorer#6583]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.28.0

### Architecture

x64

### Storage Explorer Build Number

20230214.5

### Platform

Windows

### OS Version

Windows Server 2022

### Bug Description

This request is not authorized to perform this operation.

This storage account's 'Firewalls & virtual networks' settings may be blocking access to storage services. Try adding your client IP address to the firewall exceptions, or by allowing access from 'all networks' instead of 'selected networks'. To learn more about Azure Storage firewalls and virtual networks, visit http://go.microsoft.com/fwlink/?LinkId=845443.

Error Details:
{
  "name": "RestError",
  "code": "AuthorizationFailure",
  "statusCode": 403,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://bulkattachment.blob.core.windows.net/?sv=2021-06-08&ss=bfqt&srt=sco&sp=rwdlacupyx&se=2023-02-21T00:14:54Z&st=2023-02-20T16:14:54Z&spr=https&SAS Token Redacted&comp=list&include=metadata",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2021-10-04"
        },
        "accept": {
          "name": "Accept",
          "value": "application/xml"
        },
        "user-agent": {
          "name": "User-Agent",
          "value": "Microsoft Azure Storage Explorer/1.28.0 (win32) azsdk-js-storageblob/12.12.0 (NODE-VERSION v16.17.1; Windows_NT 10.0.20348)"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "f762b081-4555-4f84-9297-820b0b5568fd"
        },
        "cookie": {
          "name": "Cookie",
          "value": ""
        }
      }
    },
    "withCredentials": false,
    "timeout": 0,
    "keepAlive": true,
    "decompressResponse": false,
    "requestId": "f762b081-4555-4f84-9297-820b0b5568fd"
  },
  "response": {
    "headers": {
      "_headersMap": {
        "content-length": {
          "name": "content-length",
          "value": "246"
        },
        "content-type": {
          "name": "content-type",
          "value": "application/xml"
        },
        "date": {
          "name": "date",
          "value": "Mon, 20 Feb 2023 16:19:48 GMT"
        },
        "server": {
          "name": "server",
          "value": "Microsoft-HTTPAPI/2.0"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "f762b081-4555-4f84-9297-820b0b5568fd"
        },
        "x-ms-error-code": {
          "name": "x-ms-error-code",
          "value": "AuthorizationFailure"
        },
        "x-ms-request-id": {
          "name": "x-ms-request-id",
          "value": "10dcf698-601e-004f-5647-45e0f6000000"
        }
      }
    },
    "request": {
      "streamResponseStatusCodes": {},
      "url": "https://bulkattachment.blob.core.windows.net/?sv=2021-06-08&ss=bfqt&srt=sco&sp=rwdlacupyx&se=2023-02-21T00:14:54Z&st=2023-02-20T16:14:54Z&spr=https&SAS Token Redacted&comp=list&include=metadata",
      "method": "GET",
      "headers": {
        "_headersMap": {
          "x-ms-version": {
            "name": "x-ms-version",
            "value": "2021-10-04"
          },
          "accept": {
            "name": "Accept",
            "value": "application/xml"
          },
          "user-agent": {
            "name": "User-Agent",
            "value": "Microsoft Azure Storage Explorer/1.28.0 (win32) azsdk-js-storageblob/12.12.0 (NODE-VERSION v16.17.1; Windows_NT 10.0.20348)"
          },
          "x-ms-client-request-id": {
            "name": "x-ms-client-request-id",
            "value": "f762b081-4555-4f84-9297-820b0b5568fd"
          },
          "cookie": {
            "name": "Cookie",
            "value": ""
          }
        }
      },
      "withCredentials": false,
      "timeout": 0,
      "keepAlive": true,
      "decompressResponse": false,
      "requestId": "f762b081-4555-4f84-9297-820b0b5568fd"
    },
    "status": 403,
    "bodyAsText": "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.\nRequestId:10dcf698-601e-004f-5647-45e0f6000000\nTime:2023-02-20T16:19:48.7404842Z</Message></Error>",
    "parsedBody": {
      "message": "This request is not authorized to perform this operation.\nRequestId:10dcf698-601e-004f-5647-45e0f6000000\nTime:2023-02-20T16:19:48.7404842Z",
      "code": "AuthorizationFailure"
    },
    "parsedHeaders": {
      "errorCode": "AuthorizationFailure",
      "content-length": "246",
      "content-type": "application/xml",
      "date": "Mon, 20 Feb 2023 16:19:48 GMT",
      "server": "Microsoft-HTTPAPI/2.0",
      "x-ms-client-request-id": "f762b081-4555-4f84-9297-820b0b5568fd",
      "x-ms-request-id": "10dcf698-601e-004f-5647-45e0f6000000"
    }
  },
  "details": {
    "errorCode": "AuthorizationFailure",
    "content-length": "246",
    "content-type": "application/xml",
    "date": "Mon, 20 Feb 2023 16:19:48 GMT",
    "server": "Microsoft-HTTPAPI/2.0",
    "x-ms-client-request-id": "f762b081-4555-4f84-9297-820b0b5568fd",
    "x-ms-request-id": "10dcf698-601e-004f-5647-45e0f6000000",
    "message": "This request is not authorized to perform this operation.\nRequestId:10dcf698-601e-004f-5647-45e0f6000000\nTime:2023-02-20T16:19:48.7404842Z",
    "code": "AuthorizationFailure"
  }
}

### Steps to Reproduce

1) Launch Storage Explorer
2) Add the Storage account
3) Paste the SAS URL
4) Containers are not getting listed, but the attached error is shown.

### Actual Experience

We tried to access a storage account from Azure Storage Explorer using the generated SAS URL of an another subscription on a Windows Server 2022 VM with SQL Server 2019 running on Disk Encryption Sets using CMK.

**Comment by JasonYeMSFT** [comment]
Have you checked your storage account's 'Firewalls & virtual networks' settings as suggested by the error details?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue we recommend opening an Azure support ticket from the Azure Portal. Alternatively you can open a new issue here.
