### ISSUE TITLE
Show ACL/permission in file listings

### ISSUE THREAD

**Issue by mathieulongtin** [microsoft/AzureStorageExplorer#6584]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I'm trying to manage ACL on a large data lake. Not being able to see the ACL in the file listing makes this slow and tedious.

### Desired Solution

Add a column with the ACL in file listing pane

### Alternatives and Workarounds

There's is currently no easy way to see the ACL, not on the CLI, not on the portal.

**Comment by JasonYeMSFT** [comment]
Are you asking for showing the permissions for each file in the data explorer? If so, we have a work item tracking it and we plan to implement it in 1.29.0 (current milestone). If not, feel free to reopen this issue and elaborate on what you want.
https://github.com/microsoft/AzureStorageExplorer/issues/6130

**Comment by mathieulongtin** [comment]
I guess I'll wait for 1.29
