### ISSUE TITLE
Unable to access storage container (AZ DataLake Gen2

### ISSUE THREAD

**Issue by amcareem** [microsoft/AzureStorageExplorer#6585]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

v1.28.0

### Architecture

i86

### Storage Explorer Build Number

20230214.5

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Upon clicking the Blob container I'm getting an authentication error. This didn't solve even after relogging back in and by entering correct credentials.

his request is not authorized to perform this operation.

This storage account's 'Firewalls & virtual networks' settings may be blocking access to storage services. Try adding your client IP address to the firewall exceptions, or by allowing access from 'all networks' instead of 'selected networks'. To learn more about Azure Storage firewalls and virtual networks, visit http://go.microsoft.com/fwlink/?LinkId=845443.

Error Details:
{
  "name": "RestError",
  "code": "AuthorizationFailure",
  "statusCode": 403,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://purviewsqltest.blob.core.windows.net/?comp=list&include=metadata",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2021-10-04"
        },
        "accept": {
          "name": "Accept",
          "value": "application/xml"
        },
        "user-agent": {
          "name": "User-Agent",
          "value": "Microsoft Azure Storage Explorer/1.28.0 (win32) azsdk-js-storageblob/12.12.0 (NODE-VERSION v16.17.1; Windows_NT 10.0.19045)"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "9721579c-7156-41bc-97e9-acc9292055f8"
        },
        "authorization": {
          "name": "authorization",
          "value": "Bearer JSON Web Token Redacted"
        },
        "cookie": {
          "name": "Cookie",
          "value": ""
        }
      }
    },
    "withCredentials": false,
    "timeout": 0,
    "keepAlive": true,
    "decompressResponse": false,
    "requestId": "9721579c-7156-41bc-97e9-acc9292055f8"
  },
  "response": {
    "headers": {
      "_headersMap": {
        "content-length": {
          "name": "content-length",
          "value": "246"
        },
        "content-type": {
          "name": "content-type",
          "value": "application/xml"
        },
        "date": {
          "name": "date",
          "value": "Tue, 21 Feb 2023 03:37:39 GMT"
        },
        "server": {
          "name": "server",
          "value": "Microsoft-HTTPAPI/2.0"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "9721579c-7156-41bc-97e9-acc9292055f8"
        },
        "x-ms-error-code": {
          "name": "x-ms-error-code",
          "value": "AuthorizationFailure"
        },
        "x-ms-request-id": {
          "name": "x-ms-request-id",
          "value": "cbd4ba59-801e-0024-0da5-4515f2000000"
        }
      }
    },
    "request": {
      "streamResponseStatusCodes": {},
      "url": "https://purviewsqltest.blob.core.windows.net/?comp=list&include=metadata",
      "method": "GET",
      "headers": {
        "_headersMap": {
          "x-ms-version": {
            "name": "x-ms-version",
            "value": "2021-10-04"
          },
          "accept": {
            "name": "Accept",
            "value": "application/xml"
          },
          "user-agent": {
            "name": "User-Agent",
            "value": "Microsoft Azure Storage Explorer/1.28.0 (win32) azsdk-js-storageblob/12.12.0 (NODE-VERSION v16.17.1; Windows_NT 10.0.19045)"
          },
          "x-ms-client-request-id": {
            "name": "x-ms-client-request-id",
            "value": "9721579c-7156-41bc-97e9-acc9292055f8"
          },
          "authorization": {
            "name": "authorization",
            "value": "Bearer JSON Web Token Redacted"
          },
          "cookie": {
            "name": "Cookie",
            "value": ""
          }
        }
      },
      "withCredentials": false,
      "timeout": 0,
      "keepAlive": true,
      "decompressResponse": false,
      "requestId": "9721579c-7156-41bc-97e9-acc9292055f8"
    },
    "status": 403,
    "bodyAsText": "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.\nRequestId:cbd4ba59-801e-0024-0da5-4515f2000000\nTime:2023-02-21T03:37:40.7194938Z</Message></Error>",
    "parsedBody": {
      "message": "This request is not authorized to perform this operation.\nRequestId:cbd4ba59-801e-0024-0da5-4515f2000000\nTime:2023-02-21T03:37:40.7194938Z",
      "code": "AuthorizationFailure"
    },
    "parsedHeaders": {
      "errorCode": "AuthorizationFailure",
      "content-length": "246",
      "content-type": "application/xml",
      "date": "Tue, 21 Feb 2023 03:37:39 GMT",
      "server": "Microsoft-HTTPAPI/2.0",
      "x-ms-client-request-id": "9721579c-7156-41bc-97e9-acc9292055f8",
      "x-ms-request-id": "cbd4ba59-801e-0024-0da5-4515f2000000"
    }
  },
  "details": {
    "errorCode": "AuthorizationFailure",
    "content-length": "246",
    "content-type": "application/xml",
    "date": "Tue, 21 Feb 2023 03:37:39 GMT",
    "server": "Microsoft-HTTPAPI/2.0",
    "x-ms-client-request-id": "9721579c-7156-41bc-97e9-acc9292055f8",
    "x-ms-request-id": "cbd4ba59-801e-0024-0da5-4515f2000000",
    "message": "This request is not authorized to perform this operation.\nRequestId:cbd4ba59-801e-0024-0da5-4515f2000000\nTime:2023-02-21T03:37:40.7194938Z",
    "code": "AuthorizationFailure"
  }
}

### Steps to Reproduce

1. Launch Storage Explorer
2. Select the desired storage account
3. Click Blob Containers

### Actual Experience

Upon clicking the Blob container I'm getting an authentication error. This didn't solve even after relogging back in and by entering correct credentials.

### Expected Experience

I need to see the folder and files in the blob container

**Comment by JasonYeMSFT** [comment]
Have you checked your storage account's 'Firewalls & virtual networks' settings?
