### ISSUE TITLE
Not able to access the blobs in a container as it is reporting error

### ISSUE THREAD

**Issue by rk518y** [microsoft/AzureStorageExplorer#6588]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.28.0

### Regression From

1.26.0

### Architecture

i86

### Storage Explorer Build Number

20230214.5

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Not able to use the Microsoft Azure Storage Explorer

### Steps to Reproduce

1. Started and logged into the Azure Storage explorer. 
2. Tried to open the container blobs in a container of a storage account. It failed and reported an error mentioned in this ticket.

### Actual Experience

This request is not authorized to perform this operation.

This storage account's 'Firewalls & virtual networks' settings may be blocking access to storage services. Try adding your client IP address to the firewall exceptions, or by allowing access from 'all networks' instead of 'selected networks'. To learn more about Azure Storage firewalls and virtual networks, visit http://go.microsoft.com/fwlink/?LinkId=845443.

Error Details:
{
  "name": "RestError",
  "code": "AuthorizationFailure",
  "statusCode": 403,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://attbcdevsanatt01.blob.core.windows.net/?comp=list&include=metadata",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2021-08-06"
        },
        "accept": {
          "name": "Accept",
          "value": "application/xml"
        },
        "user-agent": {
          "name": "User-Agent",
          "value": "Microsoft Azure Storage Explorer/1.26.0 (win32) azsdk-js-storageblob/12.11.0 (NODE-VERSION v16.14.2; Windows_NT 10.0.19042)"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "b4849618-8517-4eee-98b6-f166620c6126"
        },
        "authorization": {
          "name": "authorization",
          "value": "Bearer JSON Web Token Redacted"
        },
        "cookie": {
          "name": "Cookie",
          "value": ""
        }
      }
    },
    "withCredentials": false,
    "timeout": 0,
    "keepAlive": true,
    "decompressResponse": false,
    "requestId": "b4849618-8517-4eee-98b6-f166620c6126"
  },
  "response": {
    "headers": {
      "_headersMap": {
        "content-length": {
          "name": "content-length",
          "value": "246"
        },
        "content-type": {
          "name": "content-type",
          "value": "application/xml"
        },
        "date": {
          "name": "date",
          "value": "Wed, 22 Feb 2023 01:55:36 GMT"
        },
        "server": {
          "name": "server",
          "value": "Microsoft-HTTPAPI/2.0"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "b4849618-8517-4eee-98b6-f166620c6126"
        },
        "x-ms-error-code": {
          "name": "x-ms-error-code",
          "value": "AuthorizationFailure"
        },
        "x-ms-request-id": {
          "name": "x-ms-request-id",
          "value": "ff80595b-501e-0049-0e60-4676b0000000"
        }
      }
    },
    "request": {
      "streamResponseStatusCodes": {},
      "url": "https://attbcdevsanatt01.blob.core.windows.net/?comp=list&include=metadata",
      "method": "GET",
      "headers": {
        "_headersMap": {
          "x-ms-version": {
            "name": "x-ms-version",
            "value": "2021-08-06"
          },
          "accept": {
            "name": "Accept",
            "value": "application/xml"
          },
          "user-agent": {
            "name": "User-Agent",
            "value": "Microsoft Azure Storage Explorer/1.26.0 (win32) azsdk-js-storageblob/12.11.0 (NODE-VERSION v16.14.2; Windows_NT 10.0.19042)"
          },
          "x-ms-client-request-id": {
            "name": "x-ms-client-request-id",
            "value": "b4849618-8517-4eee-98b6-f166620c6126"
          },
          "authorization": {
            "name": "authorization",
            "value": "Bearer JSON Web Token Redacted"
          },
          "cookie": {
            "name": "Cookie",
            "value": ""
          }
        }
      },
      "withCredentials": false,
      "timeout": 0,
      "keepAlive": true,
      "decompressResponse": false,
      "requestId": "b4849618-8517-4eee-98b6-f166620c6126"
    },
    "status": 403,
    "bodyAsText": "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.\nRequestId:ff80595b-501e-0049-0e60-4676b0000000\nTime:2023-02-22T01:55:36.7539127Z</Message></Error>",
    "parsedBody": {
      "message": "This request is not authorized to perform this operation.\nRequestId:ff80595b-501e-0049-0e60-4676b0000000\nTime:2023-02-22T01:55:36.7539127Z",
      "code": "AuthorizationFailure"
    },
    "parsedHeaders": {
      "errorCode": "AuthorizationFailure",
      "content-length": "246",
      "content-type": "application/xml",
      "date": "Wed, 22 Feb 2023 01:55:36 GMT",
      "server": "Microsoft-HTTPAPI/2.0",
      "x-ms-client-request-id": "b4849618-8517-4eee-98b6-f166620c6126",
      "x-ms-request-id": "ff80595b-501e-0049-0e60-4676b0000000"
    }
  },
  "details": {
    "errorCode": "AuthorizationFailure",
    "content-length": "246",
    "content-type": "application/xml",
    "date": "Wed, 22 Feb 2023 01:55:36 GMT",
    "server": "Microsoft-HTTPAPI/2.0",
    "x-ms-client-request-id": "b4849618-8517-4eee-98b6-f166620c6126",
    "x-ms-request-id": "ff80595b-501e-0049-0e60-4676b0000000",
    "message": "This request is not authorized to perform this operation.\nRequestId:ff80595b-501e-0049-0e60-4676b0000000\nTime:2023-02-22T01:55:36.7539127Z",
    "code": "AuthorizationFailure"
  }
}

### Expected Experience

To show all the blobs in the container

### Additional Context

Please get the issue resolved.

**Comment by JasonYeMSFT** [comment]
Have you checked your storage account's 'Firewalls & virtual networks' settings as suggested by the error details?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue we recommend opening an Azure support ticket from the Azure Portal. Alternatively you can open a new issue here.
