### ISSUE TITLE
Show a confusing message when copying block blobs to a premium blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#659]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture**: ia32/x64
**Build Number**: 20180911.1
**Commit**: 5a9d37a6
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Expand a non-premium storage account -> Open a blob container then try to upload a block blob to it.
2. Copy the uploaded block blob to one premium blob container.
3. Check the displayed error message on Activities.

#### Expected Experience: ####
This block blob cannot be copied successfully due to it doesn't support.

#### Actual Experience: ####
1. It shows a confusing error message on Activities.
2. The activity is successful after clicking 'Retry' and the copied block blob shows well on the editor after refreshing. 
![capture1](https://user-images.githubusercontent.com/41351993/45414004-f7cc9000-b669-11e8-8317-38e510a24557.PNG)

**Comment by v-limu** [comment]
This issue still reproduces on build [2190927.10](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3091851).

1. It shows a confusing error message on Activities.
![image](https://user-images.githubusercontent.com/54055206/65827191-3c04ef80-e2c2-11e9-919d-974d881c169c.png)
2. It still shows the confusing error after clicking 'Retry' or refreshing the editor.

**Comment by v-limu** [comment]
This issue has been fixed on build [20191123.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3268481). So we close it.
