### ISSUE TITLE
The selected message is still selected after refreshing the queue explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6590]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230221.6
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Queues.
2. Create one queue -> Add one message.
3. Select the message -> Refresh the queue explorer.
4. Check whether the message is not selected.

## Expected Experience ##
The message is not selected.
![image](https://user-images.githubusercontent.com/41351993/220534583-2d5d0b4a-d024-43c1-ac4e-3721c6a1194f.png)

## Actual Experience ##
The message is selected.
![image](https://user-images.githubusercontent.com/41351993/220534647-d4c57315-050a-4c3d-b6fb-5ecc5a0c4b38.png)

**Comment by v-xianya** [comment]
Hi @craxal we logged this issue with reference to the comments of the bug https://github.com/microsoft/AzureStorageExplorer/issues/5594#issuecomment-1091991788. Could you help to have a look for the comments? thank you!

**Comment by craxal** [comment]
@v-xianya Thanks for referencing that. I'll look into this further.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230226.1. Fixed. So, we are going to close it.
![queue](https://user-images.githubusercontent.com/41351993/221492755-abfbabeb-61c1-4b40-8382-c1c570c548ba.gif)
