### ISSUE TITLE
Keep a consistent function for 'F2' between ADLS Gen2 blob containers and file shares

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6591]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230221.6
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Create a folder.
3. Press 'F2' -> Observe the prompt dialog is 'Clone' dialog.
4. Expand one ADLS Gen2 storage account -> Blob Containers.
5. Create a blob container -> Create a folder.
6. Press 'F2' -> Observe the prompt dialog is 'Rename' dialog.

## Expected Experience ##
Keep a consistent function for 'F2' between ADLS Gen2 blob containers and file shares.

## Actual Experience ##
The function for 'F2' is different between ADLS Gen2 blob containers and file shares.

**Comment by MRayermannMSFT** [comment]
If a real rename command exists, F2 should invoke it, otherwise F2 should invoke clone (assuming a clone command exists). @richardMST please make sure F2 invokes rename in the file share explorer.

**Comment by v-xianya** [comment]
Verified this issue on the build 20230302.2
The 'Rename' dialog pops up after pressing 'F2' both in ADLS Gen2 blob explorer and file shares.
 So, we are going to close this issue.
