### ISSUE TITLE
'Ctrl + R' doesn't take effect in the explorer of ADLS Gen2 blob containers/file shares

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6592]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230221.6
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.23.1)

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Open one blob container.
3. Trun on the Caps Lock -> Press 'Ctrl + R'.
4. Check whether the blob explorer is refreshed or not.

## Expected Experience ##
The blob explorer is refreshed.

## Actual Experience ##
The blob explorer is not refreshed.

## Additional Context ##
This issue doesn't reproduce for regular blob containers/queues/tables.

**Comment by JasonYeMSFT** [comment]
When caps lock is enabled, on Windows the `event.key` becomes the uppercase letter ('r' -> 'R').

**Comment by craxal** [comment]
@v-xianya Please verify again. A change should have been merged by now.

**Comment by v-kellyluo** [comment]
@craxal , verified this issue on the build main/20230403.1, it doesn't reproduce for file shares, but it still reproduces for ADLS Gen2 blob containers.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230413.5. Fixed. So, we are going to close it.
