### ISSUE TITLE
The error message is incorrect when moving one directory if the directory already exists in the destination for file shares

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6593]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230221.6
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Create two folders 'f1', 'f2'.
3. Copy the folder 'f2' and paste it to 'f1'.
4. Go back to root -> Try to move 'f2' to 'f1'.
5. There is a failed activity log -> Click 'Details...'.
6. Check whether the error message is correct.

## Expected Experience ##
The error message is correct. 
Below is the screenshot from ADLS Gen2:

![image](https://user-images.githubusercontent.com/41351993/220547406-60877f8a-290c-422a-abc4-204a7a3546dd.png)

## Actual Experience ##
The error message is incorrect.
![image](https://user-images.githubusercontent.com/41351993/220545687-7bc35f76-11f5-4f57-b4de-8d5b31a5c31a.png)

**Comment by MRayermannMSFT** [comment]
Richard, please figure out why this is happening since we specify `replaceIfExists`.

**Comment by richardMSFT** [comment]
Looks like the Rest rename API does not support overwriting a directory. That's why there is a `RenameDirectoryOperationNotSupported` error.

https://learn.microsoft.com/en-us/rest/api/storageservices/rename-directory says "If the target is a directory, then the directory must not exist".
