### ISSUE TITLE
The blob tags can be edited in one SAS attached secondary blob container with all permissions

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6594]
**Storage Explorer Version:** 1.29.0-dev
**Build Number:** 20230221.6
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create one blob container -> Upload a blob.
3. Right click the blob container -> Click 'Open Secondary Location'.
4. SAS attach the secondary blob with all permissions.
5. Switch to the attached secondary blob container.
6. Right click the blob -> Click 'Edit Tags...'.
7. Check whether the blob tags are read-only.

## Expected Experience ##
The blob tags are read-only.

## Actual Experience ##
The blob tags can be edited.

## Additional Context ##
In previous release 1.24.3, the 'Edit Tags...' action is disabled in one SAS attached secondary blob container.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230304.8. Fixed. So, we are going to close it.
