### ISSUE TITLE
UnexpectedQuit (used SAS, discovery not completed)

### ISSUE THREAD

**Issue by kkkkkky** [microsoft/AzureStorageExplorer#6595]
Got this error on my MacOS(Apple Silicon) when I was trying to download file.
I've tried the latest common version(v1.28.0) and apple silicon dedicated version, none of them worked for me.
Attached is the azcopy command output. Pls suggest how to troubleshoot or solve it.
[azcopy_logs.txt](https://github.com/microsoft/AzureStorageExplorer/files/10801276/azcopy_logs.txt)

**Comment by JasonYeMSFT** [comment]
Could you give more details of the command you tried to execute? It would be great if you can share the command from the "Copy AzCopy command" action after redacting all the sensitive information (e.g. storage account name, container name, SAS token, account key, etc.). It would be easier to debug if we know which type of job causes AzCopy to crash.

**Comment by kkkkkky** [comment]
Here's the azcopy command it generated. 
`export AZCOPY_CRED_TYPE=Anonymous;
export AZCOPY_CONCURRENCY_VALUE=AUTO;
./azcopy copy "https://blahblah.blob.core.windows.net/test/sample.zip?sv=2021-10-04&se=2023-03-25T02%3A2S%3A12A&sr=c&sp=rl&sig=abcde%2Bj%2Br%2Fkk%2abcde%2B%abcde0%3D" "/Users/usera/Downloads/sample.zip" --overwrite=prompt --check-md5 FailIfDifferent --from-to=BlobLocal --recursive --log-level=INFO;
unset AZCOPY_CRED_TYPE;
unset AZCOPY_CONCURRENCY_VALUE;`

**Comment by kkkkkky** [comment]
Any update or anything I can do to help?

**Comment by MRayermannMSFT** [comment]
We're attempting to follow up with the AzCopy team on this. However, if you're able to reproduce this on the command line manually, opening an issue against AzCopy directly (here: https://github.com/Azure/azure-storage-azcopy/issues) may help get this issue more visible with them.

**Comment by kkkkkky** [comment]
Thank you for your response. I searched for a while in azcopy's issue pool, seems it's a [known bug](https://github.com/mattn/go-ieproxy/issues/35) to be fixed(Previously fixed but now has been reverted due to other problems the fix version caused.) 
I double checked that I can reproduce the same issue by just running "azcopy" in my terminal(after brew install azcopy), so it's not caused by AzureStorageExplorer.
Maybe I'll ask azcopy for resolution and you can close this issue. Thanks.

**Comment by MRayermannMSFT** [comment]
> Maybe I'll ask azcopy for resolution and you can close this issue. Thanks.

Yes, if you're willing to do that it would definitely simplify things!
