### ISSUE TITLE
Check output of 'Check Path Lengths' for files we don't need to ship for 1.29

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#6598]
Look at the output of the 'Check Path Lengths, and see if there's any files in the top 10 longest path lengths that we don't need to be shipping. Ideally, run the script looking at more than top 10 to check for even more files. If you find files we shouldn't ship in the output then:
1. Make sure they are actually being shipped
2. Either do the work yourself to stop shipping them, or create issues and assign them to others on the team for help

**Comment by JasonYeMSFT** [comment]
Done for 1.29.0.
