### ISSUE TITLE
Add the 'Connection string' info to 'Properties' of the Cosmos DB account

### ISSUE THREAD

**Issue by jinglouMSFT** [Microsoft/AzureStorageExplorer#66]
**OS Version:** Win10 Enterprise(32 bits)
**Storage Explorer:**  Storage Explorer_Windows_20171127.3

**Actual:** 
We need to copy the Cosmos DB account connection string on portal when the user attach it.

**Suggestion:**
Could we get the 'Connection string' info to 'Properties' window for better user experience?

This is TFS bug 530788.

**Comment by djlan** [comment]
Looking

**Comment by djlan** [comment]
close

**Comment by djlan** [comment]
Closed
