### ISSUE TITLE
No red border shows after inputting a Guid value with unmatched parentheses on 'Add Entity' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#660]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture**: ia32/x64
**Build Number**: 20180911.1
**Commit**: 5a9d37a6
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1, Expand a storage account -> Open one table then click 'Add'.
2, Add a property with ‘Guid’ type -> Input the value ‘(12345678-90ab-cdef-1234-567890abcdef}’ with    unmatched parentheses.
3, Check whether the red border shows or not.

#### Expected Experience: ####
Show a red border for the value field .

#### Actual Experience: ####
No red border shows for the value field.

#### More Info: ####
After clicking ‘Insert’ button, pops up an error dialog:
![capture2](https://user-images.githubusercontent.com/41351993/45415096-5e52ad80-b66c-11e8-9ba2-9677d35b4303.PNG)

**Comment by v-limu** [comment]
This issue has been fixed on build [20191123.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3268481). So we close it.
