### ISSUE TITLE
Not able to list the file share in storage explorer

### ISSUE THREAD

**Issue by SoubhagyaRamprasath** [microsoft/AzureStorageExplorer#6602]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.28.0

### Architecture

i86

### Storage Explorer Build Number

20230214.5

### Platform

Windows

### OS Version

Windows 10

### Bug Description

When I try listing the file shares in a storage account I get the below error

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://prdhmmss01sizetg.file.core.windows.net/?comp=list failed, reason: unable to get local issuer certificate",
  "stack": "FetchError: request to https://prdhmmss01sizetg.file.core.windows.net/?comp=list failed, reason: unable to get local issuer certificate\n    at ClientRequest.<anonymous> (C:\\Users\\solla\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:117261)\n    at ClientRequest.emit (node:events:527:28)\n    at TLSSocket.socketErrorListener (node:_http_client:454:9)\n    at TLSSocket.emit (node:events:527:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY",
  "code": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"
}

### Steps to Reproduce

1. Launch storage explorer
2. Open storage container
3. expand file shares

### Actual Experience

Getting the error mentioned
Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://prdhmmss01sizetg.file.core.windows.net/?comp=list failed, reason: unable to get local issuer certificate",
  "stack": "FetchError: request to https://prdhmmss01sizetg.file.core.windows.net/?comp=list failed, reason: unable to get local issuer certificate\n    at ClientRequest.<anonymous> (C:\\Users\\solla\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:117261)\n    at ClientRequest.emit (node:events:527:28)\n    at TLSSocket.socketErrorListener (node:_http_client:454:9)\n    at TLSSocket.emit (node:events:527:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY",
  "code": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"
}

### Expected Experience

Should open properly

### Additional Context

NA

**Comment by danieltroyer** [comment]
Similar issue: Unable to create new folder within existing blob

{
  "name": "FetchError",
  "message": "request to https://dev00datalake.dfs.core.windows.net/processed/Ski_repl?resource=directory failed, reason: unable to get local issuer certificate",
  "type": "system",
  "errno": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY",
  "code": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY",
  "stack": "FetchError: request to https://dev00datalake.dfs.core.windows.net/processed/Ski_repl?resource=directory failed, reason: unable to get local issuer certificate\n    at ClientRequest.<anonymous> (C:\\Users\\dtroyer\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-adls2-extension\\dist\\src\\index.js:2:59176)\n    at ClientRequest.emit (node:events:513:28)\n    at TLSSocket.socketErrorListener (node:_http_client:481:9)\n    at TLSSocket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)"
}

Steps:

- Navigate to blob
- create new folder
- enter name value
- save
- error pops

Environment:
Windows 10 - Version 10.0.19045 Build 19045

![image](https://user-images.githubusercontent.com/10080395/220991817-9efbbeda-f40f-45a8-8d54-f4ee98d13443.png)

**Comment by SoubhagyaRamprasath** [comment]
It didn't work out for me  :( Zscalar and VPN are not logged in and still getting error

**Comment by MRayermannMSFT** [comment]
Can y'all please try enabling system proxy? You can read more about it here: https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by SoubhagyaRamprasath** [comment]
Changed the proxy setting in storage explorer which resolved the issue. 
Steps to follow:
Click the gear icon in storage explorer
Update the proxy setting to: Use system proxy

It works then!

**Comment by SoubhagyaRamprasath** [comment]
![image](https://user-images.githubusercontent.com/122604147/221882376-ed220514-9c0b-44f6-9288-1ed4e98acb4c.png)
