### ISSUE TITLE
The 'Shared Access Signature' dialog displays empty for one storage account

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6604]
**Storage Explorer Version:** 1.29.0-dev
**Build Number:** 20230224.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.28.0)

## Steps to Reproduce ##

1. Right click one storage account -> Click 'Get shared Access Signature...'.
2. The 'Shared Access Signature' dialog pops up.
3. Check whether the dialog displays normal.

## Expected Experience ##
The dialog displays normal.

## Actual Experience ##
The dialog displays empty.
![image](https://user-images.githubusercontent.com/87792676/221115695-095437a6-6ffb-4c51-b87b-13e98b7a5b5c.png)

## Additional Context ##
This issue doesn't reproduce for blob containers/file shares/queues/tables.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230307.1. Fixed. So, we are going to close it.
