### ISSUE TITLE
Ctrl+R can't refresh the new table explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6606]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230224.3
**Branch**: feature/table-explorer-react
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.0)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a new table -> Close the opened tab.
3. Right click the table -> Click '[2] Open'.
4. Press 'Ctrl + R'.
5. Check whether the table editor is refreshed.

## Expected Experience ##
The table editor is refreshed.

## Actual Experience ##
The table editor is not refreshed.

## Additional Context ##
This issue has nothing to do with caps lock on/off.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230330.2. Fixed.
