### ISSUE TITLE
"Server failed to authenticate the request"

### ISSUE THREAD

**Issue by dnten12** [microsoft/AzureStorageExplorer#661]
I'm trying to create an web to upload encrypted file to Azure by my self( I use PHP to encrypt my file before I upload it). I downloaded and used the example code to upload a file to Azure on Github but it's not worked correctly.
My full fail is:

```
403: Fail: Code: 403 Value: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. details (if any): ﻿AuthenticationFailedServer failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:feab5a33-101e-007a-71bf-4a88ba000000 Time:2018-09-12T17:35:50.4027373ZThe MAC signature found in the HTTP request 'wiSjme4/A+zusTfOItNclcmpOdnwcIhgShHEI6Qz7jU=' is not the same as any computed signature. Server used following string to sign: 'PUT application/x-www-form-urlencoded Wed, 12 Sep 2018 17:35:52 GMT x-ms-blob-content-type:application/octet-stream x-ms-blob-type:BlockBlob x-ms-request-id:5b994e782d91d x-ms-version:2017-04-17 /demovdm/vmdblockblobsqbnzia/upload/abc.txt'..
```

  That's i try to upload the file named "abc.txt"

It is may code:
[my_code.txt](https://github.com/Microsoft/AzureStorageExplorer/files/2376271/my_code.txt)
Please help me!

**Comment by craxal** [comment]
What exactly are the steps you're following? Please edit your first comment and fill in [this template](https://raw.githubusercontent.com/Microsoft/AzureStorageExplorer/master/.github/issue_template.md) so we can better help you.

**Comment by MRayermannMSFT** [comment]
@dnten12 are you still having problems? Please upgrade to the latest Storage Explorer and let us know if your issue still occurs. Thanks.
