### ISSUE TITLE
The table explorer displays blank after deleting the last entity in one table which contains more than one entity

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6610]
**Storage Explorer Version:** 1.29.0-dev
**Build Number:** 20230224.3
**Branch:** feature/table-explorer-react
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.28.0)

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Right click one table -> Click '[2] Open'.
3. Add two entities.
4. Right click the last entity -> Click 'Delete -> Yes'.
5. Check whether the explorer displays normal.

## Expected Experience ##
The table explorer displays normal.

## Actual Experience ##
The table explorer displays blank.
![image](https://user-images.githubusercontent.com/87792676/221145569-61e41f7b-80f8-4f17-873f-5767f5f6fb4e.png)

## Additional Context ##
Deleting multiple entities will select the same number of entities by default.

**Comment by v-kellyluo** [comment]
This issue still reproduces on the build 20230307.3, will verify it on the newer build.

**Comment by craxal** [comment]
The root issue is related to cell focus, which needs to be reset when the collection of items in the grid changes. The issues has already bee addressed and is still in review.

**Comment by v-xianya** [comment]
Verified this issue on the build 20230317.1. Fixed. So, we are going to close it.
