### ISSUE TITLE
The selected entity is still selected after manually refreshing the table explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6617]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230224.3
**Branch**: feature/table-explorer-react
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.0)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
3. Right click one table -> Click '[2] Open'.
4. Add one entity -> Select the entity.
5. Click 'Refresh'.
6. Check whether the entity is selected or not.

## Expected Experience ##
The entity is not selected.

## Actual Experience ##
The entity is selected.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230307.3. Fixed.
