### ISSUE TITLE
Latest version changes show an abnormal behaviour when using the Azure blob for PST ingestion in M365

### ISSUE THREAD

**Issue by anepu** [microsoft/AzureStorageExplorer#6619]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.28.0

### Regression From

1.27.0

### Architecture

x64

### Storage Explorer Build Number

20230214.5

### Platform

Windows

### OS Version

Windows 11

### Bug Description

Latest version changes show an abnormal behaviour when using the Azure blob for PST ingestion in M365, specifically connecting to the blob itself works but there is a warning showing with text _The SAS used to connect to this blob container has expired_ which is actually misleading.

### Steps to Reproduce

1. Go to your M365 tenant on https://compliance.microsoft.com/informationgovernance?viewid=import
2. Create a new Import job
3. Go through the steps and click on Show network upload SAS URL and copy that in the clipboard
4. Start Microsoft Azure Storage Explorer 
5. Right click on storage accounts and Connect to Azure Storage -> Blob container
6. Shared Access Signature URL and paste the URL in the clipboard
7. The connection will be created and if there is data there it is shown, however the following warning shows _The SAS used to connect to this blob container has expired._ which is not true
8. Tested in previous version v1.27.0 and the warning was not there

### Actual Experience

It is just a misleading warning which is also not true as the SAS is not expired
![Screenshot 2023-02-28 164626](https://user-images.githubusercontent.com/86715305/221888286-faba7c28-b891-4ffa-a1fc-86dff2394254.jpg)

Example of SAS key:
https://ac63fc63205940f1bc91e59.blob.core.windows.net/ingestiondata?sv=2015-04-05&sr=c&si=IngestionSasForAzCopy**202302240723170845**&sig=XYZblablaabc&se=**2023-03-30**T14%3A41%3A49Z

**Comment by intrepidis** [comment]
I am also seeing this same issue. Older versions do not report the blob has expired, but the latest version does. I know the blob definitely hasn't expired yet.

**Comment by MRayermannMSFT** [comment]
@anepu @intrepidis thanks for opening this issue. Looking at the example SAS, I'm wondering about the expiration portion.

`**2023-03-30**T14%3A41%3A49Z`

Do y'all know where the `*` characters came from? Are those actually in the SAS URL the compliance portal gave you?

Also, can y'all please check that the clocks on your computer are at the correct time?

**Comment by MRayermannMSFT** [comment]
Nevermind all those previous questions. We also found this bug a two weeks ago: https://github.com/microsoft/AzureStorageExplorer/issues/6586

We have a fix ready for 1.29. Do all SAS tokens that this compliance portal generate have this issue?

**Comment by anepu** [comment]
@MRayermannMSFT according to my testing, yes, all SAS tokens generated from https://compliance.microsoft.com/informationgovernance?viewid=import have this behaviour. I've tested with multiple generated SAS tokens on different days on my tenant and I get the same and I got the same in a different tenant. See below latest example with the signature obfuscated:
IngestionSasForAzCopy202302240723170845&sig=this_is_a_dummy_signature&se=2023-04-06T06%3A57%3A21Z

**Comment by t00lxtz** [comment]
I`m having the same issue - any SaaS token will say "The SAS used to connect to this blob container has expired" I`m unable to import the PST's from the Blob storage to a mailbox. 

  | Error |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | --
2 | The PST (Test.pst) could not   be found in the storage account |  
3 | The PST (archive.pst) could not be   found in the storage account |  
4 | The PST (archive1.pst) could not be   found in the storage account |  
5 | The PST (archive2.pst) could not be   found in the storage account |

**Comment by MRayermannMSFT** [comment]
> I'm having the same issue - any SaaS token will say "The SAS used to connect to this blob container has expired" Im unable to import the PST's from the Blob storage to a mailbox.

This issue would not cause any issues beyond the message wrongly being displayed. Please double check that you put your files in blob storage correctly.

**Comment by MRayermannMSFT** [comment]
> @MRayermannMSFT according to my testing, yes, all SAS tokens generated...have this behavior

Thanks for confirming. We're going to hotfix our fix for this.

**Comment by MRayermannMSFT** [comment]
1.28.1 has been shipped. If you are running 1.28.0 you should already see an update notification. We'll release to other versions in a few days. As always, releases can be found here for manual download: https://github.com/microsoft/AzureStorageExplorer/releases
