### ISSUE TITLE
The renamed table isn’t focused during renaming

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#662]
Storage Explorer Version: 1.5.0
Platform/OS Version: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
Architecture: ia32/x64
Build Number: 20180912.4
Commit: 4cda9ef7
Regression From: Not a regression

#### Steps to Reproduce: ####
1. Expand a storage account -> Select a table and rename it.
2. Check whether the renamed table is focused or not during renaming.

#### Expected Experience: ####
The renamed table is focused during renaming.

#### Actual Experience: ####
The renamed table isn't focused during renaming but 'Quick Access' node is focused.

#### More info: ####
This issue doesn't reproduce for blobs and file shares.

**Comment by MRayermannMSFT** [comment]
Won't fix.
