### ISSUE TITLE
The entities disappear when navigating to more than the 10th page then manually refreshing

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6621]
**Storage Explorer Version:** 1.29.0-dev
**Build Number:** 20230224.3
**Branch:** feature/table-explorer-react
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.28.0)

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Right click one table -> Click '[2] Open'.
3. Import more than 1000 entities.
4. Click 'Load more' -> Switch to the 11th page -> Click 'Refresh'.
5. Check whether the entities still display.

## Expected Experience ##
The entities still display.

## Actual Experience ##
The entities disappear.
![image](https://user-images.githubusercontent.com/87792676/222055174-3ba8ddf6-d37d-49c6-997f-bb6489c75959.png)

## Additional Context ##
The page number changes to 1.
![image](https://user-images.githubusercontent.com/87792676/222055475-46d5cd70-6543-411d-916c-24a96c309dc6.png)

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230317.1. Fixed. So, we are going to close it.
