### ISSUE TITLE
The pasted item displays after refreshing the explorer if pasting one archived blob to one file share

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6622]
**Storage Explorer Version:** 1.29.0-dev
**Build Number:** 20230228.11
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload a blob and change its access tier to Archive.
3. Copy the archived blob -> Paste it to one file share.
4. There is a failed activity log -> Click 'Refresh'.
5. Check whether the pasted file doesn't display.

## Expected Experience ##
The pasted file doesn't display.

## Actual Experience ##
The pasted file displays.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230304.8. Fixed.
The paste action in file share explorer is disabled after clicking copy for one archive blob. So, we are going to close it.
