### ISSUE TITLE
The full path of the file shows in the 'Source VHD' field of the 'Upload VHD' dialog when uploading disks

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#6629]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230302.3
**Branch**: main
**Platform/OS**: Windows 10
**Architecture**: ia32
**How Found**: From running test cases
**Regression From**: Previous release (1.28.0)

## Steps to Reproduce ##
1. Expand the node 'Disks' -> Open one resource group.
2. Click 'Upload' -> Click the '...' button next to the 'Source VHD' field.
3. Select one file -> Click 'Open'.
4. Observe the value in the 'Source VHD' field.
5. Check whether shows the file name in the field.

## Expected Experience ##
Show the file name in the field.
![image](https://user-images.githubusercontent.com/41351993/222352796-31595fe0-16bb-4fe8-8d87-fe693ac7ca15.png)

## Actual Experience ##
Show the path of the file in the field.
![image](https://user-images.githubusercontent.com/41351993/222352679-c1ab9f8f-1379-45d2-8801-02d353d56281.png)

## Additional Context ##
This issue doesn't reproduce on Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro).

**Comment by v-xianya** [comment]
Hi @JasonYeMSFT 
Update: Now on Windows/ Linux Ubuntu/Mac platforms. Display file path on the Source VHD field. Is this expected?
![image](https://user-images.githubusercontent.com/41351993/223031520-60f99a1c-4bd0-4d89-b732-b07fd6d58d81.png)

**Comment by JasonYeMSFT** [comment]
Yes, I decided to change to show the full path since it is the purpose of that input.
