### ISSUE TITLE
Fail to view the parent blob container after attaching the blob with 'Generate container-level shared access signature URI' checked

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#663]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture**: ia32/x64
**Build Number**: 20180912.4
**Commit**: 4cda9ef7
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Open one blob container then upload a blob to it.
2. Create a SAS URI for the blob with 'Generate container-level shared access signature URI' checked.
**Blob name:** empty.txt
**SAS URI:** https://davidlisb1234.blob.core.windows.net/beyondsoft/empty.txt?st=2018-09-13T08%3A32%3A32Z&se=2018-09-20T08%3A32%3A00Z&sp=rwdl&sv=2018-03-28&sr=c&sig=9WhaM%2BRN21Em4kLcOApJzCy0%2BqyH%2BZdPx5ce5CmSQqg%3D
3. Drill down from the **Local & Attached -> Storage Accounts -> SAS-Attached Service -> Blob Containers**.
4. Attach the blob using the created URI and check whether the parent blob container shows or not.

#### Expected Experience: ####
The parent blob container is attached successfully and shows well.

#### Actual Experience: ####
1. The parent blob container doesn't show under the Blob Containers node.
2. Pop up an error dialog after attempting to refreshing Blob Containers.
![error](https://user-images.githubusercontent.com/34729022/45477963-61b06c80-b732-11e8-89f4-73e05356dbe6.png)

**Comment by craxal** [comment]
You're not supposed to be able to attach to _blobs_. Only _blob container_ SAS URIs work.

**Comment by v-xuanzh** [comment]
Hi @craxal ,I have one question need to your confirmation for this issue.

How to use the created container-level SAS URI with ''Generate container-level shared access signature URI'' checked?
![sas](https://user-images.githubusercontent.com/34729022/45725857-4a4b0680-bbac-11e8-969c-e265196d83fe.png)

**Comment by craxal** [comment]
The problem is in your URI. The URI is referring to a specific blob. If you want to use it to connect to a _container_, you have to modify the path in the URI to refer to the container:

https://davidlisb1234.blob.core.windows.net/beyondsoft?st=2018-09-13T08%3A32%3A32Z&se=2018-09-20T08%3A32%3A00Z&sp=rwdl&sv=2018-03-28&sr=c&sig=9WhaM%2BRN21Em4kLcOApJzCy0%2BqyH%2BZdPx5ce5CmSQqg%3D

**Comment by v-xuanzh** [comment]
OK, I See. Thank you.  😛
