### ISSUE TITLE
The copied direct link of one queue is not displayed as a link when pasting it to OneNote

### ISSUE THREAD

**Issue by v-jennazheng** [microsoft/AzureStorageExplorer#6631]
**Storage Explorer Version** : 1.29.0-dev
**Build Number** : 20230302.3
**Branch**: main
**Platform/OS**: Windows 10/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64 
**How Found**: Ad-hoc testing
**Regression From**:  Not a regression

## Steps to Reproduce 
1. Expand one regular storage account -> Queues.
2. Create a queue. 
3. Right click the queue -> Click 'Copy Direct Link to Queue'.
4. Open OneNote -> Paste the link to OneNote.
5. Check whether the copied direct link of the queue is displayed as a link.

## Expected Experience ##
The copied direct link of the queue is displayed as a link.

## Actual Experience ##
The copied direct link of the queue is not displayed as a link.

## Additional Context ##
This issue doesn't reproduce for blob container, file shares, tables.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230411.2. Fixed.
