### ISSUE TITLE
Need load all Storage Account in one click and also search is super slow 

### ISSUE THREAD

**Issue by rb1811** [microsoft/AzureStorageExplorer#6632]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

In Desktop app, I've to click "load more" multiple times. It takes like 5-6 clicks to load all storage accounts from all nodes. There should be 1 click and it should load all.  Also, the search for Storage Account, is not extremely slow.  

### Desired Solution

Need 1 single click to load all storage account. And the search should be quick. As quick as the browser version

**Comment by MRayermannMSFT** [comment]
@rb1811 some curiosity questions:
- Do you make use of/know about quick access?
- Do you make use of/know about "Search from here"?
- Do you make use of/know about the filters in the search dropdown?
- Can you tell us more about how your accounts are named/how you look for accounts?

**Comment by MRayermannMSFT** [comment]
Related to: https://github.com/microsoft/AzureStorageExplorer/issues/1527

**Comment by rb1811** [comment]
Hello,

1. Yes, I know about Quick Access, but since I work with multiple
subscriptions and multiple Storage accounts, pinning all of them is not
gonna solve the problem for me. Sometime I need to really search for
Storage Accounts.
2. Yes "Search from Here" with filters is still super slow.
3. Answered in #2
4. Accounts are just small case letters.  When I search it says searching
for nodes. It goes from 1-1000nodes sometimes. Its a corporate account.
Can't reveal much . But when I search for SA using browser, its super
quick. No log. Only via desktop app its happens. Plus the "load more"
option. WHich doesn't load all SA in one shot. I have to click multiple
times to properly load all the accounts,

**Comment by MRayermannMSFT** [comment]
> 2. Yes "Search from Here" with filters is still super slow.

To help us better understand why you're getting slow search from here:
- About how many storage accounts do you have in your subscription?
- About how many overall resources do you have in your subscription?

**Comment by JasonYeMSFT** [comment]
I am going to close this issue and track this and other similar issues collectively in https://github.com/microsoft/AzureStorageExplorer/issues/6757
