### ISSUE TITLE
An extra '…' shows next to the buttons under query mode when setting 'Toolbar Size' to 'Regular / Small'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6635]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230302.7
**Branch**: feature/table-explorer-react
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.0)

## Steps to Reproduce ##
1. Launch storage explorer -> Open 'Settings' -> Change the setting 'Toolbar Size' to 'Small'.
2. Expand one storage account -> Tables.
3. Right click one table -> Click '[2] Open'.
4. Click 'Query' -> Observe the buttons under the query mode.
5. Check whether no extra '...' shows.

## Expected Experience ##
No extra '...' shows.
![image](https://user-images.githubusercontent.com/41351993/222656483-1e8b835f-26ba-4bfa-a1a3-cc97c0042797.png)

## Actual Experience ##
An extra '...' shows.
![image](https://user-images.githubusercontent.com/41351993/222656446-c22ee195-25d2-46ab-bd96-513a4b24da38.png)

## Additional Context ##
The '...' disappears after manually refreshing.

**Comment by craxal** [comment]
@JasonYeMSFT I believe this is very similar to the problem I see with the main toolbar, where the toolbar fails to collapse extra buttons into the More button when it's first displayed. Can you investigate this?

**Comment by JasonYeMSFT** [comment]
I debugged the code. The toolbar resize logic is executed before the query panel elements get rendered. As a result, the code that are meant to hide the more button cannot do anything and at a later stage the query panel gets rendered which includes the more button.

**Comment by v-xianya** [comment]
Verified this issue on the build 20230317.1. Fixed. So, we are going to close it.
