### ISSUE TITLE
Nothing happens when trying to save query

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6637]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230302.7
**Branch**: feature/table-explorer-react
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.0)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Right click one table -> Click '[2] Open'.
3. Click 'Query' -> Type PartitionKey eq '1' to the text editor.
4. Try to save query by clicking the 'save query/save query as...' button.
5. Check whether a save query window pops up.

## Expected Experience ##
A save query window pops up.

## Actual Experience ##
Nothing happens.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230307.3. Fixed.
