### ISSUE TITLE
The query mode doesn't exit after clicking 'Refresh'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6638]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230302.7
**Branch**: feature/table-explorer-react
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.0)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Right click one table -> Click '[2] Open'.
3. Click 'Query' -> Click 'Refresh'.
4. Check whether the query mode exits.

## Expected Experience ##
The query mode exits.

## Actual Experience ##
The query mode does not exit.

**Comment by craxal** [comment]
This is by design. We decided it was not helpful to close the query builder if Refresh is clicked. (see the task list in #6026).

**Comment by v-xianya** [comment]
Hi @craxal Thank you for the update!
In this scenario, if click 'Refresh', the query will be executed. could you help to have a look?

**Comment by craxal** [comment]
@v-xianya Yes, if Refresh is clicked, the query will be executed. That is expected.
