### ISSUE TITLE
The selected entities are not highlighted if using 'Select All' action

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6639]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230302.7
**Branch**: feature/table-explorer-react
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.0)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Open one new table -> Add one entity.
3. Right click the table -> Click '[2] Open in New Tab'.
4. Click 'Select All'.
5. Check whether the selected entity is highlighted.

## Expected Experience ##
The selected entity is highlighted.
![image](https://user-images.githubusercontent.com/41351993/222673751-a8cab805-edd5-4d5c-a7b6-3cafd1d6067c.png)

## Actual Experience ##
The selected entity is not highlighted.
![image](https://user-images.githubusercontent.com/41351993/222673822-c5ef403e-2e74-4a39-8784-e57850f3f9a1.png)

**Comment by craxal** [comment]
@v-xianya Actually, the selected item _is_ highlighted. It's just highlighted in gray, because the table does not have focus. If you move focus to the table, the item will be highlighted in blue. This is easier to see of you have two or more entities, select just one, then move focus off the table.
