### ISSUE TITLE
The uri of the fixed bug #652 with wrong protocol 'hhttps' in ReleaseNotes.html

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#664]
**Storage Explorer Version**: 1.4.2
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture**: ia32/x64
**Build Number**: 20180913.1
**Commit**: 8db1a4da
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Launch Storage Explorer then open Release Notes.
2. Try to open the link of the fixed bug #652 under Hotfixes.

#### Expected Experience: ####
The fixed bug can be opened in browser successfully.

#### Actual Experience: ####
Fail to open the link of the fixed bug #652 due to it shows a wrong protocol 'hhttps' in ReleaseNotes.html.
![wrong](https://user-images.githubusercontent.com/34729022/45538355-5de61e00-b7f6-11e8-92d1-48a72a410097.png)

**Comment by JakeRadMSFT** [comment]
Merged into 1.4.2 Branch.
