### ISSUE TITLE
Fix Gen2 blob listing with new SDK

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#6645]
https://github.com/Azure/azure-sdk-for-js/issues/25121

The new SDK is required for cold tier support. We need to fix/workaround this issue in 1.29.0.

**Comment by JasonYeMSFT** [comment]
The issue is temporarily workaround in 1.29.0. Push the work for 1.30.0.

**Comment by JasonYeMSFT** [comment]
Currently waiting for resolution of https://github.com/Azure/azure-rest-api-specs/issues/24170. After that we can talk to SDK team to work on it.

**Comment by JasonYeMSFT** [comment]
The spec is not going to update anytime soon. However, the SDK team is kind enough to expose the raw response so we can workaround it. I will take advantage of it and get rid of the duplicated dependency in 1.32.0.

**Comment by MRayermannMSFT** [comment]
Work is merged and I have completed basic testing. @JasonYeMSFT can you bash on my work a bit more? Shoot this back my way with bug details if you find any issues. Thanks. 🥰
