### ISSUE TITLE
There is a successful activity log if typing '//' to the 'Destination directory' field to move files

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6647]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230307.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Upload one file.
3. Select the file -> Click 'Move'.
4. Type '//' into the 'Destination directory' field -> Click 'Move'.
5. Check whether there is a failed activity log.

## Expected Experience ##
There is a failed activity log.

## Actual Experience ##
There is a successful activity log.

## Additional Context ##
This issue doesn't reproduce for ADLS Gen2 blobs.
Here is the error:
![image](https://user-images.githubusercontent.com/41351993/223368960-503a16e4-0bd5-4a17-8652-592d1894de91.png)

**Comment by richardMSFT** [comment]
ADLS Gen2 uses a different API under the hood than File Share for the move command. This is expected given their respective apis.
