### ISSUE TITLE
No traffic shows in Fiddler for the actions "Export Selected"

### ISSUE THREAD

**Issue by v-sunnsun** [microsoft/AzureStorageExplorer#6649]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230307.6
**Branch**: main
**Platform/OS**: Windows 10
**Architecture**: ia32
**How Found**: From running test cases
**Regression From**:  Previous release (1.28.0)

## Bug Description ##

1. No traffic shows in Fiddler for the action 'Search From Here'.
2. No traffic shows in Fiddler for the action 'Detach'.

## Steps to Reproduce 

1. Install and launch Fiddler -> Launch Storage Explorer.
2. Click 'Edit -> Configure Proxy' -> Select 'Use app proxy settings' -> Set the URL: 'http://localhost' Port: '8888' -> Click 'OK'.
3. Expand one storage account -> Tables.
4. Create a new table -> Add one entity.
6. Select the entity -> Click 'Export -> Export Selected...' -> Click 'Save'.
7. Check whether shows traffic in Fiddler.

## Expected Experience 
Show traffic in Fiddler.

## Actual Experience ##
No traffic shows in Fiddler.

## Additional Context ##
This issue also reproduces when selecting proxy 'Use environment variables' and 'Use system proxy (preview)'.

**Comment by craxal** [comment]
@v-sunnsun Detach shouldn't be making any network requests other than perhaps to trigger a refresh of the tree. Does this reproduce also for import? Table copy? Table stats?

**Comment by v-sunnsun** [comment]
Hi @craxal 
1. The following picture shows the detach traffic in 1.28.0. (No traffic for detach action in 1.28.1)
![image](https://user-images.githubusercontent.com/122582307/231688466-45189a36-9af8-4b96-b62b-6e4adf01018b.png)
2. This issue does not reproduce for import/table copy/table statistics.
3. "Search from here" reproduces for storage account/blob container/file share/queue/disk resource types.

**Comment by craxal** [comment]
@v-sunnsun Can you create a separate issue for "Search from here" bug? Can you dig into the network requests a little more and find out what the requests are for (like, are we calling list APIs, or is it something else)? Does this issue reproduce when detaching other resource types?

**Comment by v-sunnsun** [comment]
Hi @craxal 
We logged a new bug for search from here '[6776](https://github.com/microsoft/AzureStorageExplorer/issues/6776)'

**Comment by craxal** [comment]
@v-sunnsun Since I would not expect to see any traffic for Detach, and that the problem is reproducible for all resource types, I'm not going to worry about that. Only the Export Selected scenario appears to be a valid concern.

**Comment by craxal** [comment]
@v-sunnsun Two questions:
1. Do you start getting traffic if you close and reopen Storage Explorer and try the export again?
2. Do you start getting traffic if you set the proxy setting to "Use system proxy" and try the export again?
