### ISSUE TITLE
The absolute path of the selected blob doesn't display in 'Upload' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#665]
**Storage Explorer Version**: 1.4.2
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture**: ia32/x64
**Build Number**: 20180913.1
**Commit**: 8db1a4da
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Choose one blob container and try to open the 'Upload blobs' dialog.
2. Select a specific blob then check whether its absolute path displays well or not.

#### Expected Experience: ####
The absolute path of the selected blob displays well.

#### Actual Experience: ####
Only display the selected blob name in 'Upload blobs' dialog.
![path](https://user-images.githubusercontent.com/34729022/45538881-c5509d80-b7f7-11e8-9fab-d1a7005afcb8.png)

#### More info: ####
1. This issue doesn't reproduce when uploading a blob folder to blob containers.
2. This issue also reproduces when uploading files/directories to file shares.

**Comment by v-xianya** [comment]
Verified this issue on build 20191220.9.
The layout of the upload dialog has changed. And for upload blob files or blob folders, the display format is consistent. So we close it.😊
![image](https://user-images.githubusercontent.com/41351993/71607627-f05e2c80-2bb5-11ea-8b29-3fccf4835d4d.png)
