### ISSUE TITLE
The error doesn't disappear after typing a blob name which already exists into 'Destination blob name' on the 'Clone and Rehydrate' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6655]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230310.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload two blobs.
3. Change one blob's access tier to 'Archive'.
4. Right click the archived blob -> Click 'Clone and Rehydrate...'.
5. Type the other blob's name into the 'Destination blob container' field -> Lose focus on the field.
6. Check whether the error disappears.

## Expected Experience ##
The error disappears.
![image](https://user-images.githubusercontent.com/41351993/224276870-22c371c0-7924-4162-afba-edea3f9ac586.png)

## Actual Experience ##
The error does not disappear.
![image](https://user-images.githubusercontent.com/41351993/224276925-8dc9d70f-f884-4f47-a49c-85abe740f5f0.png)

## Additional Context ##
1. This issue also reproduces for 'Copy and Rehydrate' dialog.
2. The error should disappear according to the description` 'If a blob with the specified name already exists, the existing blob will be overwritten.'` in the dialog.

**Comment by JasonYeMSFT** [comment]
Showing the validation error is the expected behavior. We want to prevent people from overwriting data even if we have warned them about it.

**Comment by JasonYeMSFT** [comment]
This is related to the fix of https://github.com/microsoft/AzureStorageExplorer/issues/6623. Beware that since the validation is async, it's still possible to rush applying the change before we are able to detect the conflict. We think that's an edge case so we won't do anything to prevent that.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230312.3. The description has been removed. So, we are going to close it.
![image](https://user-images.githubusercontent.com/41351993/224621943-ffe8e556-451c-4a91-8295-0b2f2894b909.png)
