### ISSUE TITLE
authentication error

### ISSUE THREAD

**Issue by Yash9577** [microsoft/AzureStorageExplorer#6656]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.28.1

### Architecture

i86

### Platform

All

### Bug Description

Unable to retrieve child resources.

Details:
{
  "name": "RestError",
  "message": "{\"name\":\"RestError\",\"code\":\"ECONNREFUSED\",\"request\":{\"url\":\"https://management.azure.com//subscriptions/990694a4-4746-4af1-937b-186408db1101/resources?api-version=2014-04-01&$filter=resourceType%20eq%20%27Microsoft.ClassicStorage%2FstorageAccounts%27%20or%20resourceType%20eq%20%27Microsoft.Storage%2FstorageAccounts%27\",\"headers\":{\"authorization\":\"Bearer JSON Web Token Redacted\",\"user-agent\":\"Microsoft Azure Storage Explorer/1.28.1 (win32)\"},\"method\":\"GET\",\"timeout\":30000,\"disableKeepAlive\":false,\"proxySettings\":{\"host\":\"https://localhost\",\"port\":80},\"withCredentials\":false,\"requestId\":\"7d1f0868-f8c5-4c08-a400-7ed533c2f910\",\"allowInsecureConnection\":true,\"enableBrowserStreams\":false,\"agent\":{\"_events\":{},\"_eventsCount\":0,\"timeout\":null,\"maxFreeSockets\":1,\"maxSockets\":1,\"maxTotalSockets\":null,\"sockets\":{},\"freeSockets\":{},\"requests\":{},\"options\":{},\"secureProxy\":true,\"proxy\":{\"hostname\":\"localhost\",\"port\":80,\"protocol\":\"https:\",\"headers\":{\"authorization\":\"Bearer JSON Web Token Redacted\",\"user-agent\":\"Microsoft Azure Storage Explorer/1.28.1 (win32)\"},\"host\":\"localhost\",\"ALPNProtocols\":[\"http 1.1\"]}}}}"
}

### Steps to Reproduce

1.open azure storage explorer
2. it says to sign in. I signed in.
3. It gives an error and says Could not access resources for this tenant. You may need to reauthenticate. See the error details for more information.

### Actual Experience

![image](https://user-images.githubusercontent.com/65841773/224509729-b95272e0-424b-4d78-b7a1-77af522a5652.png)
![image](https://user-images.githubusercontent.com/65841773/224509745-edface16-5565-4b1d-8012-26e2fc61df7c.png)

**Comment by MRayermannMSFT** [comment]
Can you please try using system proxy? https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. If you still have questions on this issue, please open a new one instead.
