### ISSUE TITLE
Undelete of "Block Blob" using either date or selected folder did not work

### ISSUE THREAD

**Issue by gordieharkins** [microsoft/AzureStorageExplorer#6659]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.27.1

### Regression From

I don't know

### Architecture

i86

### Storage Explorer Build Number

20221220.2

### Platform

Windows

### OS Version

Windows 10

### Bug Description

I could not undelete a directory and files by date.  I was trying to restore "Alexandria, City of\2023" and the files that were present in this structure.  I was able to undelete them from the Azure Portal.

### Steps to Reproduce

1.  Delete a blob folder (Alexandria, City of).
2. Click on "Undelete" -> Undelete by date -> enter date and time around deletion.

I never saw the directory or files.

In Microsoft Azure -> go to blob account -> Containers -> Navigate to directory -> "Show deleted blobs" -> select "Alexandria, City of" and the year and select files to undelete.

### Actual Experience

No visual clue they were undeleted.

### Expected Experience

Files restored.  After I restored from Microsoft Azure the files were present.  Azure Storeage explorer never undeleted files.

### Additional Context

No errors

**Comment by MRayermannMSFT** [comment]
@gordieharkins do you see anything in the Activities panel?

**Comment by gordieharkins** [comment]
On Mar 13, 2023, at 1:41 PM, Matthew Rayermann ***@***.***> wrote:﻿
@gordieharkins do you see anything in the Activities panel?

**Comment by JasonYeMSFT** [comment]
@gordieharkins We don't see the answer in your response. Could you post it on GitHub?

**Comment by gordieharkins** [comment]
![IMG_6314](https://user-images.githubusercontent.com/25595360/225357182-31855e95-0d12-451b-be29-f6fcda1f3474.jpeg)

There was information added to the "Activity" tab at the bottom as can be seen in the attached image.

**Comment by JasonYeMSFT** [comment]
The undelete by date feature still works for me on 1.27.1. Do you have blob versioning enabled? Could you share the deleted time and the date time range you used to undelete the blobs, which doesn't work as expected? You can get the deleted time in the "Deleted Time" column in the data table.

**Comment by gordieharkins** [comment]
I was able to undelete from the Azure Portal so I assume that means I have blob versioning enabled.  If you look at the image the directory (I realize it is virtual) was deleted 3/13/2023 at 9:26am and took 4-seconds.  I used times that included 3/13/2023 at 9:26am.  I don't recall the exact time spans I used but +- a few minutes from there.

**Comment by JasonYeMSFT** [comment]
Blob versioning is a feature that works on top of soft delete. If you have blob versioning enabled. Deleting a blob will make it an active non-current version instead of soft deleting it. The right way to restore it is to "promote" the non-current version to the current version. You cannot undelete that non-current version to restore. After deleting your blob, switch to the "All blobs and blobs without current version" view context and see if the deleted blob's name has a timestamp or if it has a strikethrough. The prior indicates that the blob becomes a non-current version. The latter indicates that the blob is soft deleted.

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. If you have additional information on how to reproduce the issue, please open a new issue.
