### ISSUE TITLE
Storage Explorer GPU Error occurs even with GPU Disabled flag and interrupts AzCopy process

### ISSUE THREAD

**Issue by yusuf-jkhan1** [microsoft/AzureStorageExplorer#6661]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.28

### Regression From

1.27

### Architecture

x64

### Storage Explorer Build Number

20230309.1

### Platform

All

### OS Version

Windows 10

### Bug Description

GPU Error pops up frequently. Even when launching with disable GPU flag. In version 1.28 it interrupts the AzCopy upload.

### Steps to Reproduce

1. Launch Storage Explorer
2. Wait for GPU error to pop up

Must be uploading something.

### Actual Experience

GPU Error pops up frequently. Even when launching with disable GPU flag. In version 1.28 it interrupts the AzCopy upload.

### Additional Context

Windows 10 Enterprise
NVIDIA Quadro T2000 GPUs

**Comment by yusuf-jkhan1** [comment]
Wanted to add my appState.json file does have this key-value setting `"disableGpu":true`, but I still get the error message ~10 times a day or so if I have the app open. Not sure what's triggering it though, its not triggered from a UI action, seems to be in the background.

**Comment by yusuf-jkhan1** [comment]
Hey, I do use VSCode, slack desktop and teams desktop. I haven't had any issues with them though.

**Comment by yusuf-jkhan1** [comment]
Also, forgot to mention it stacks errors too for some reason
![image](https://user-images.githubusercontent.com/73005876/227261865-e4f41935-d477-4209-9d3a-1eafee133049.png)

**Comment by MRayermannMSFT** [comment]
@yusuf-jkhan1 thanks for the additional info. Electron recently added a way for us to get more information when these errors happen. I've added the code to do so for our next release. So we don't have to wait until then, can you please try using this (https://storageexplorerpublish.blob.core.windows.net/privatebuilds/1.29.0-gpu-crash-issue/StorageExplorer-windows-ia32.exe?sv=2021-10-04&st=2023-03-28T00%3A09%3A50Z&se=2023-03-29T00%3A09%3A50Z&sr=b&sp=r&sig=K1ltrJrA8nNRZfJyrM7YAkRkUuXkw4afnpeG1ewVdrw%3D) private build and:

1. Install the build
2. Do something to trigger the issue
3. Go to Help > Open Logs directory
4. Find the newest folder
5. Zip it up
6. Share those logs here by dragging & dropping into a new response to the issue

Thanks.

**Comment by yusuf-jkhan1** [comment]
Hey @MRayermannMSFT , yeah I'd be happy to try this. I think the link expired though? It gives me this error when I try to click it:
```
Error>
<Code>AuthenticationFailed</Code>
<Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:135a11c2-d01e-009a-4c4d-620d7a000000 Time:2023-03-29T14:47:09.3914704Z</Message>
<AuthenticationErrorDetail>Signature not valid in the specified time frame: Start [Tue, 28 Mar 2023 00:09:50 GMT] - Expiry [Wed, 29 Mar 2023 00:09:50 GMT] - Current [Wed, 29 Mar 2023 14:47:09 GMT]</AuthenticationErrorDetail>
</Error>
```
I apologize I was away yesterday so I didn't have a chance to try. Can you please re-add the link?

**Comment by MRayermannMSFT** [comment]
Yes, sorry, it expired. I should have made it last longer. Here's a new one: https://storageexplorerpublish.blob.core.windows.net/privatebuilds/1.29.0-gpu-crash-issue/StorageExplorer-windows-ia32.exe?sv=2021-10-04&st=2023-03-29T16%3A02%3A45Z&se=2023-04-05T16%3A02%3A00Z&sr=b&sp=r&sig=gp0YP63nvUGxFci2ApqrK%2BPqgs6HkYrs4EX673cRhfs%3D

**Comment by JasonYeMSFT** [comment]
The change Matthew was talking about was merely for a new way to log the error. However, the change we made had side effects. If that's really what mitigated your issue, it means we were misclassifying some child process errors as gpu errors. We used to quit the app on all such errors. Now we only quit if the child process error is explicitly set to be an GPU error.

**Comment by MRayermannMSFT** [comment]
Ok, let's close the issue. The changes will be included in our next major release.
