### ISSUE TITLE
The associated node is not selected when clicking one opened tab if collapse its storage account node

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6664]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230315.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Open one blob container -> Click the opened tab.
3. The blob container on the tree view is selected.
4. Collapse the storage account node.
5. Click the opened tab.
6. Check whether the associated blob container is selected.

## Expected Experience ##
The associated blob container is selected.

## Actual Experience ##
1. The storage account node is not expanded.
2. The associated blob container is not selected.

## Additional Context ##
This issue also reproduces for file shares/queues/tables.

**Comment by JasonYeMSFT** [comment]
This is because the immediate parent of the container (service node) is expanded but the grandparent node (storage account) is not. Our expanding checks one level of parent each time and stops at the immediate parent.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230321.12. Fixed.
