### ISSUE TITLE
Unable to access file store in Storage account file share:

### ISSUE THREAD

**Issue by madouten** [microsoft/AzureStorageExplorer#6665]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.28.1

### Architecture

i86

### Storage Explorer Build Number

20230309.1

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Unable to access file store in Storage account file share:

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://eastus2app4ee.file.core.windows.net/?comp=list failed, reason: unable to get local issuer certificate",
  "stack": "FetchError: request to https://eastus2app4ee.file.core.windows.net/?comp=list failed, reason: unable to get local issuer certificate\n    at ClientRequest.<anonymous> (C:\\Users\\U8012993\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:118601)\n    at ClientRequest.emit (node:events:513:28)\n    at TLSSocket.socketErrorListener (node:_http_client:481:9)\n    at TLSSocket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY",
  "code": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"
}

### Steps to Reproduce

Launch Explorer
Got to storage blob
Expand FileShare

### Actual Experience

![image](https://user-images.githubusercontent.com/80466083/225354802-b56ef939-0393-4c52-a48c-2d4b9483723b.png)
Attached image

**Comment by MRayermannMSFT** [comment]
Can you please try using system proxy? https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. If you still have this problem, please open a new issue.
