### ISSUE TITLE
getting authentication error while creating a blob container

### ISSUE THREAD

**Issue by nagasaigiduthuri** [microsoft/AzureStorageExplorer#6669]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.28.1

### Architecture

x64

### Platform

Windows

### OS Version

Windows 11

### Bug Description

This request is not authorized to perform this operation.

This storage account's 'Firewalls & virtual networks' settings may be blocking access to storage services. Try adding your client IP address to the firewall exceptions, or by allowing access from 'all networks' instead of 'selected networks'. To learn more about Azure Storage firewalls and virtual networks, visit http://go.microsoft.com/fwlink/?LinkId=845443.

Error Details:
{
  "name": "RestError",
  "code": "AuthorizationFailure",
  "statusCode": 403,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://iaspirestorageprod.blob.core.windows.net/?comp=list&include=metadata",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2021-10-04"
        },
        "accept": {
          "name": "Accept",
          "value": "application/xml"
        },
        "user-agent": {
          "name": "User-Agent",
          "value": "Microsoft Azure Storage Explorer/1.28.0 (win32) azsdk-js-storageblob/12.12.0 (NODE-VERSION v16.17.1; Windows_NT 10.0.22000)"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "e1ef3f0c-c7cf-48c7-97ae-7a0dc69424cd"
        },
        "x-ms-date": {
          "name": "x-ms-date",
          "value": "Thu, 16 Mar 2023 06:26:20 GMT"
        },
        "authorization": {
          "name": "Authorization",
          "value": "Signed SharedKey Redacted="
        },
        "cookie": {
          "name": "Cookie",
          "value": ""
        }
      }
    },
    "withCredentials": false,
    "timeout": 0,
    "keepAlive": true,
    "decompressResponse": false,
    "requestId": "e1ef3f0c-c7cf-48c7-97ae-7a0dc69424cd"
  },
  "response": {
    "headers": {
      "_headersMap": {
        "content-length": {
          "name": "content-length",
          "value": "246"
        },
        "content-type": {
          "name": "content-type",
          "value": "application/xml"
        },
        "date": {
          "name": "date",
          "value": "Thu, 16 Mar 2023 06:26:19 GMT"
        },
        "server": {
          "name": "server",
          "value": "Microsoft-HTTPAPI/2.0"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "e1ef3f0c-c7cf-48c7-97ae-7a0dc69424cd"
        },
        "x-ms-error-code": {
          "name": "x-ms-error-code",
          "value": "AuthorizationFailure"
        },
        "x-ms-request-id": {
          "name": "x-ms-request-id",
          "value": "b89516e6-001e-0073-1fd0-578990000000"
        }
      }
    },
    "request": {
      "streamResponseStatusCodes": {},
      "url": "https://iaspirestorageprod.blob.core.windows.net/?comp=list&include=metadata",
      "method": "GET",
      "headers": {
        "_headersMap": {
          "x-ms-version": {
            "name": "x-ms-version",
            "value": "2021-10-04"
          },
          "accept": {
            "name": "Accept",
            "value": "application/xml"
          },
          "user-agent": {
            "name": "User-Agent",
            "value": "Microsoft Azure Storage Explorer/1.28.0 (win32) azsdk-js-storageblob/12.12.0 (NODE-VERSION v16.17.1; Windows_NT 10.0.22000)"
          },
          "x-ms-client-request-id": {
            "name": "x-ms-client-request-id",
            "value": "e1ef3f0c-c7cf-48c7-97ae-7a0dc69424cd"
          },
          "x-ms-date": {
            "name": "x-ms-date",
            "value": "Thu, 16 Mar 2023 06:26:20 GMT"
          },
          "authorization": {
            "name": "Authorization",
            "value": "SharedKey iaspirestorageprod:9LuMyMPC3Olr/ZkF4BSGH6Ox2B8a6/L38qewzia2syw="
          },
          "cookie": {
            "name": "Cookie",
            "value": ""
          }
        }
      },
      "withCredentials": false,
      "timeout": 0,
      "keepAlive": true,
      "decompressResponse": false,
      "requestId": "e1ef3f0c-c7cf-48c7-97ae-7a0dc69424cd"
    },
    "status": 403,
    "bodyAsText": "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.\nRequestId:b89516e6-001e-0073-1fd0-578990000000\nTime:2023-03-16T06:26:20.8826878Z</Message></Error>",
    "parsedBody": {
      "message": "This request is not authorized to perform this operation.\nRequestId:b89516e6-001e-0073-1fd0-578990000000\nTime:2023-03-16T06:26:20.8826878Z",
      "code": "AuthorizationFailure"
    },
    "parsedHeaders": {
      "errorCode": "AuthorizationFailure",
      "content-length": "246",
      "content-type": "application/xml",
      "date": "Thu, 16 Mar 2023 06:26:19 GMT",
      "server": "Microsoft-HTTPAPI/2.0",
      "x-ms-client-request-id": "e1ef3f0c-c7cf-48c7-97ae-7a0dc69424cd",
      "x-ms-request-id": "b89516e6-001e-0073-1fd0-578990000000"
    }
  },
  "details": {
    "errorCode": "AuthorizationFailure",
    "content-length": "246",
    "content-type": "application/xml",
    "date": "Thu, 16 Mar 2023 06:26:19 GMT",
    "server": "Microsoft-HTTPAPI/2.0",
    "x-ms-client-request-id": "e1ef3f0c-c7cf-48c7-97ae-7a0dc69424cd",
    "x-ms-request-id": "b89516e6-001e-0073-1fd0-578990000000",
    "message": "This request is not authorized to perform this operation.\nRequestId:b89516e6-001e-0073-1fd0-578990000000\nTime:2023-03-16T06:26:20.8826878Z",
    "code": "AuthorizationFailure"
  }
}

### Steps to Reproduce

1.launch storage explorer
2.Expand the storage accounts
3.When creating a new blob container

### Actual Experience

![Uploading Screenshot (410).png…]()

**Comment by JasonYeMSFT** [comment]
Have you checked your storage account's 'Firewalls & virtual networks' settings to see if it is blocking your access?

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. If you still have this problem, please double check your firewall & virtual networks settings and open a new issue with the new findings.
