### ISSUE TITLE
The current checkboxes status doesn't make sense if unhide one subscription when the checkbox 'Select All Subscriptions' is selected and all subscriptions are hidden

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6671]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230316.7
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Open ACCOUNT MANAGEMENT panel -> Hide all subscriptions under one azure account.
2. Check the checkbox for the 'Select All Subscriptions'.
3. Unhide one subscription.
4. Check whether the current checkboxes status makes sense.

## Expected Experience ##
The current checkboxes status makes sense.
![image](https://user-images.githubusercontent.com/41351993/225837559-86664257-d051-4a7e-9d89-6735935c605a.png)

## Actual Experience ##
The current checkboxes status doesn't make sense.
![image](https://user-images.githubusercontent.com/41351993/225833237-ef0815a8-2ce7-419d-947b-6a71bbaad615.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into main. Part of the fix was disabling select all when all subscriptions are hidden.

**Comment by v-xianya** [comment]
Verified this issue on the build 20230319.3. Fixed.
'Select All Subscriptions' is disabled when all subscriptions are hidden.
