### ISSUE TITLE
The 'Select All Subscriptions' checkbox is selected after switching to ACCOUNT MANAGEMENT panel even though there are unchecked subscriptions

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6672]
**Storage Explorer Version:** 1.29.0-dev
**Build Number:** 20230316.7
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.28.1)

## Steps to Reproduce ##

1. Open ACCOUNT MANAGEMENT panel -> Uncheck one subscription.
2. Observe the 'Select All Subscriptions' checkbox.
3. Switch to EXPLORER panel -> Switch to ACCOUNT MANAGEMENT panel.
4. Check whether the 'Select All Subscriptions' checkbox is not selected.

## Expected Experience ##
The 'Select All Subscriptions' checkbox is not selected.
![image](https://user-images.githubusercontent.com/87792676/225832281-5704ea05-2df5-489a-bf0c-afcdd764cda4.png)

## Actual Experience ##
The 'Select All Subscriptions' checkbox is selected.
![image](https://user-images.githubusercontent.com/87792676/225832525-243f1c05-8210-487d-bcb8-f4f81284e62b.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into main.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20230319.3. Fixed.
