### ISSUE TITLE
The selected subscriptions in previous version are not preserved after updating to the current version

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6673]
**Storage Explorer Version:** 1.29.0-dev
**Build Number:** 20230316.7
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.28.1)

## Steps to Reproduce ##

1. Install Storage Explorer 1.28.1.
2. Switch to ACCOUNT MANAGEMENT panel -> Select several subscriptions.
3. Uninstall Storage Explorer -> Install the current build.
4. Switch to ACCOUNT MANAGEMENT panel.
5. Check whether the selected subscriptions are preserved.

## Expected Experience ##
The selected subscriptions are preserved.

## Actual Experience ##
The selected subscriptions are not preserved.

**Comment by MRayermannMSFT** [comment]
@v-kellyluo when you say you "uninstalled" 1.28.0, can you elaborate on what that means? To be clear, the selected data is only preserved if you do an upgrade. If you literally uninstall, then the cached data will be removed.

In tonight's build I have added additional logging in the conversation process. If you are still able to reproduce this behavior during an upgrade, please:
1. Elaborate on what exactly you did
2. Share the Storage Explorer logs for 1.29.0-dev for each OS you reproduce the issue on

**Comment by v-kellyluo** [comment]
Hi @MRayermannMSFT , I uninstalled Storage Explorer on Control Panel, and then installed the current build. Verified this issue on the build main/20230319.3, it still reproduces, here are the results:

- 1.27.2 -> 1.28.1, the subscriptions are preserved.
- 1.28.1 -> 20230319.3, the subscriptions are not preserved.

**Comment by v-kellyluo** [comment]
Hi @MRayermannMSFT , I uninstalled Storage Explorer 1.28.1 on Control Panel, and then installed the current build. Verified this issue on the build main/20230319.3, it still reproduces, here are the results:

- 1.27.2 -> 1.28.1, the subscriptions are preserved.
- 1.28.1 -> 20230319.3, the subscriptions are not preserved.

**Comment by MRayermannMSFT** [comment]
@v-kellyluo I see selected subscriptions preserved using those steps, using build 20230319.3.

Please note that if you have previously run 1.29.0-dev on the machine then the selected subscriptions from then will be what is used when 1.29.0-dev is re-installed. So please test this on a clean machine, starting with 1.28 being the very first Storage Explorer ever installed on the machine.

If you can still repro, please share the logs from the first launch of 1.29.0-dev on the machine. Thanks.

**Comment by v-kellyluo** [comment]
@MRayermannMSFT , this issue doesn't reproduce on a clean machine by the following steps:

1. Install 1.28.0 -> Select some subscriptions -> Uninstall 1.28.0 on Control Panel.
2. Install 1.29.0-dev -> The subscriptions are preserved.

**Comment by MRayermannMSFT** [comment]
Ok good. That is expected. If you want to test this scenario on a non-clean machine you would have to do the following.

1. Open Storage Explorer
2. Open developer tools (F12)
3. Go to the "Application" tab
4. On that tab, look for Storage > Local Storage > file://
5. Click on file:// and look for the "StorageExplorer.AzureSubscriptionsManager.subscriptionCacheV2" key value pair
6. Click on the pair and then press the delete key, or click on the X above the list of key value pairs

Doing this will reset the 1.29.0+ selected subscriptions data, allowing you to test the upgrade process on a non-clean machine.

I'm going to close this now as it sounds to me like everything is working as expected. If you see otherwise or have any questions though, feel free to reopen the issue.

**Comment by v-kellyluo** [comment]
@MRayermannMSFT , thanks for the updates!
This issue doesn't reproduce after resetting the 1.29.0+ selected subscriptions data on an unclear machine.

**Comment by v-kellyluo** [comment]
@MRayermannMSFT , thanks for the updates!
This issue doesn't reproduce after resetting the 1.29.0+ selected subscriptions data on a non-clean machine.
