### ISSUE TITLE
The string 'Type' overlaps with the 'Type' field when scrolling the scrollbar under the query builder

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6675]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230317.1
**Branch**: feature/table-explorer-react
**Platform/OS**: Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Right click one table -> Click '[2] Open'.
3. Click 'Query' -> Click 'Add new clause'.
4. Add new clauses until there is a scrollbar.
5. Scroll the scrollbar -> Observe the 'Type' column.
6. Check the string 'Type' doesn't overlap with the 'Type' field.

## Expected Experience ##
The string 'Type' doesn't overlap with the 'Type' field.
![image](https://user-images.githubusercontent.com/41351993/225855652-58f93721-4852-4cf7-8352-61c755482b68.png)

## Actual Experience ##
The string 'Type' overlaps with the 'Type' field.
![image](https://user-images.githubusercontent.com/41351993/225849595-37e9b283-c82e-4f7f-88b2-481969bdbbda.png)

**Comment by craxal** [comment]
@v-xianya This is by design. When you have a tabular view of something, it's desirable to have the headers visible at all times.

**Comment by v-xianya** [comment]
Hi @craxal thank you for the response! It makes sense to have the headers visible at all times.
It's hard to see the string "Type" in this case, though. 
![image](https://user-images.githubusercontent.com/41351993/226233642-ecc13cfd-7a50-4c49-9d39-a1a5697cfccf.png)

**Comment by v-xianya** [comment]
Hi @craxal Verified this issue on the build 20230330.2. 
The current behavior as below:
1. The header strings display well when scrolling the scrollbar.
2. The hidden clauses is visible, do we need to pay attention to this?
![image](https://user-images.githubusercontent.com/41351993/228715049-009afc52-1450-4d48-adfc-7c30c8ca4150.png)

**Comment by v-xianya** [comment]
@craxal  Verified on the new build 20230406.3. 
The hidden clauses are visible when scrolling the scrollbar, do we need to pay attention to this?

![image](https://user-images.githubusercontent.com/41351993/230294837-156a0771-bf96-418b-a9fa-dc3bef9527ad.png)
