### ISSUE TITLE
The values in the 'Type' and 'Value' fields do not change if switch the value in the 'Field' under query builder

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6678]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230317.1
**Branch**: feature/table-explorer-react
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Right click one table -> Click '[2] Open'.
3. Add one entity that contains one property with Boolean type.
4. Click 'Query' -> Add one new clause.
5. Select the custom property for the 'Field' -> Select 'Boolean' as the type -> Type one value.
6. Switch the value in the 'Field' to 'PartitionKey'.
7. Check whether the values in the 'Type' and 'Value' fields change.

## Expected Experience ##
The values in the 'Type' and 'Value' fields change.
![image](https://user-images.githubusercontent.com/41351993/226265683-00d1d7dc-6528-4701-985b-3ce2c5493823.png)

## Actual Experience ##
The values in the 'Type' and 'Value' fields do not change.
![image](https://user-images.githubusercontent.com/41351993/226263349-2489d0ae-867c-4578-aaa6-6162bcd8b710.png)

**Comment by v-xianya** [comment]
Hi @craxal Verified this issue on the build 20230330.2. Reproduce.
So we are going to re-open it.
![test1](https://user-images.githubusercontent.com/41351993/228716517-023bd9ac-797f-4b2c-a77f-f8e4a017aec3.gif)

**Comment by craxal** [comment]
I'm not able to reproduce this in my current branch. Please verify again when a new build is available.

**Comment by v-xianya** [comment]
@craxal Verified this issue on the new build main 20230406.3. Reproduce.
 We are going to re-open it and verify on a newer build.

**Comment by craxal** [comment]
@v-xianya Can you please provide more details? Are you referring to the fact that the _value_ still doesn't change?

**Comment by v-xianya** [comment]
@craxal 
1. Switch to custom properties, the 'Type' and 'Value' do not change.
![image](https://user-images.githubusercontent.com/41351993/230528337-952c936c-2fea-445d-a909-24e3c6f6a971.png)

2. If switch to system properties, the 'Value' does not change.
![image](https://user-images.githubusercontent.com/41351993/230528353-495a5b25-e866-4e74-b5e0-422eac9c7fac.png)

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230413.5. Reproduce. So, we are going to reopen it and verify it on a new build.

**Comment by craxal** [comment]
There was a bad package update. Published a new version.

**Comment by v-xianya** [comment]
Hi @craxal 
Verified this issue on the build main 20230414.2. 

This issue reproduces when switching from 'Timestamp' to one custom property.

**Comment by v-xianya** [comment]
Hi @craxal 

**The current behavior:**
 When switching from Timestamp to a custom property.  
 The type remains on "DateTime", and the value remains on whatever it was before the switch. the 'Operator' value is not editable.
![image](https://user-images.githubusercontent.com/41351993/232363876-4a6da189-bb76-472d-88e9-45fa9ca0cf19.png)

**The expected behavior:**
 When switching from Timestamp to a custom property.  The type is the type changes from "DateTime" to "String", and the value is cleared and the 'Operator' value is editable.
![image](https://user-images.githubusercontent.com/41351993/232363910-c6ef0211-d01a-4b33-af2f-9fbab9f5d86e.png)

**Comment by craxal** [comment]
Merged a fix. Hopefully I've got it this time.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230418.4. Fixed. So, we are going to close it.
