### ISSUE TITLE
The length of the provided text is invalid

### ISSUE THREAD

**Issue by wierdal1** [microsoft/AzureStorageExplorer#668]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Windows Server 2016 Standard
**Architecture**: ia32
**Regression From**: New error haven't seen before

#### Expected Experience: ####
I am trying to upload old vmdks to some blob storage. Most are uploading correctly.

#### Actual Experience: ####
1 vmdk is failing. The VMDK is 9TB in question so not sure if it's too large to handle but the error code doesn't seem to suggest that. I've attached the error details here:
[ErrorDetails.txt](https://github.com/Microsoft/AzureStorageExplorer/files/2383277/ErrorDetails.txt)

Haven't found anything on google with the little information being provided but apologies if this was asked before.

**Comment by MRayermannMSFT** [comment]
@wierdal1 are you still having problems? Please upgrade to the latest Storage Explorer and let us know if your issue still occurs. Thanks.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you're still having problems. Thanks.
