### ISSUE TITLE
The toolbar is covered by the sub-toolbar under query builder if zoom in the storage explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6680]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230317.1
**Branch**: feature/table-explorer-react
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Right click one table -> Click '[2] Open'.
3. Click 'Query' -> Zoom in the storage explorer.
4. Check the toolbar is not covered by the sub-toolbar.

## Expected Experience ##
Toolbar is not covered by the sub-toolbar.
![image](https://user-images.githubusercontent.com/41351993/226284992-ce990959-6da0-421d-8cb5-94ef6a467d2f.png)

## Actual Experience ##
Toolbar is covered by the sub-toolbar.
![image](https://user-images.githubusercontent.com/41351993/226284074-06a697b6-d271-4585-a169-1f8f2f648fa1.png)

**Comment by craxal** [comment]
This appears to be a bug in the toolbar. Can be fixed with `height: min-content`.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230330.2. Fixed.
