### ISSUE TITLE
PARSE_ERROR

### ISSUE THREAD

**Issue by eagle-one78** [microsoft/AzureStorageExplorer#6684]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.28.1

### Architecture

x64

### Storage Explorer Build Number

20230309.1

### Platform

Windows

### OS Version

Windows 11

### Bug Description

{
  "name": "RestError",
  "message": "Error reading response as text: aborted",
  "stack": "RestError: Error reading response as text: aborted\n    at IncomingMessage.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-table-extension\\dist\\src\\Jobs\\TableJobsHandler.js:2:152007)\n    at IncomingMessage.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "code": "PARSE_ERROR"
}

### Steps to Reproduce

1. Launch Azure storage
2. Connect to your storage
3. choose tables
4. open a table
5. click "Export" -> Export all
6. the scanning process stops after a while with this error

### Actual Experience

We are trying to export a table from the Azur Storage Explorer. But we face an error after a while in the middle of the scanning process before the download starts.

### Expected Experience

An exported file with the data from the table

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. If you still have this problem, please gather the additional information and open a new issue.
