### ISSUE TITLE
Clicking the plug button or 'Connect to Azure Storage...' pops up an incorrect connect dialog if Storage Explorer has just restarted

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6689]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230320.5
**Branch**: main
**Platform/OS**: Windows 10
**Architecture**: ia32
**How Found**: exploratory testing
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Launch Storage Explorer -> Restart Storage Explorer.
2. Click the plug button in the vertical toolbar.
3. Check whether a correct connect dialog pops up.
## Expected Experience ##
A correct connect dialog pops up.
![image](https://user-images.githubusercontent.com/41351993/226542748-a5ac9bbc-f629-4d56-b392-ba25e1f960b7.png)

## Actual Experience ##
An incorrect connect dialog pops up.
![image](https://user-images.githubusercontent.com/41351993/226542615-6bee3ffb-79bf-45a8-bcb8-47361a4f7bfe.png)

## Additional Context ##
1. This issue also reproduces when restarting storage explorer then clicking 'Connect to Azure Storage...' on the context menu of the Storage Accounts node.
2. We met this issue on Linux Ubuntu 22.04 for once but failed to find repro steps.
3. We haven't seen this issue on MacOS Ventura 13.2.1 (Apple M1 Pro).
4. Here is the log:
[2023-03-20_log.zip](https://github.com/microsoft/AzureStorageExplorer/files/11025884/2023-03-20_log.zip)

**Comment by craxal** [comment]
@v-xianya What happens if you close and reopen the dialog. Does the same panel open, or does it open on the correct panel? I've noticed this behavior myself from time to time, but I also had no idea how to reproduce it.

**Comment by v-xianya** [comment]
Hi @craxal It will show a correct panel if re-open the dialog.

**Comment by v-xianya** [comment]
Update: We met this issue on MacOS Ventura 13.3 with build 20230410.1.

**Comment by craxal** [comment]
@v-xianya I am having trouble reproducing. Can you clarify how exactly you restart Storage Explorer? How long do you wait after restarting before clicking the button? Can you also provide the log files? Does this reproduce reliably each time, or does it only sometimes reproduce?

**Comment by v-xianya** [comment]
Hi @craxal 

1. Can you clarify how exactly you restart Storage Explorer?

    Click 'Reload' or quit storage explorer then launch it. 

2. How long do you wait after restarting before clicking the button?

    Wait for the tree view loads well, then click the button.

3. Does this reproduce reliably each time, or does it only sometimes reproduce?

    The day we logged the bug, we can reproduce the issue consistently. then we only met this issue yesterday on MacOS.

**Comment by craxal** [comment]
I think I found the problem. As part of the initialization process, Storage Explorer loads the dialog window HTML. Then looks for the first or default panel to display and hides the others. However, in the dialog window's HTML, it runs an asynchronous initialization script that nothing is awaiting. This results in a race condition where Storage Explorer might try to show the default panel before any panel components have been initialized yet. I can reproduce the error if I put a significant delay in the dialog window's initialization script.

A proper fix would be to add some communication between Storage Explorer and the dialog window to let Storage Explorer the window is done rendering HTML. But I think for now we can add some code that retries looking for the panels if it doesn't find them initially.
