### ISSUE TITLE
On dualscreen: Move Messages dialog only  appearing on one screen

### ISSUE THREAD

**Issue by ranasch** [microsoft/AzureStorageExplorer#6690]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.28.1

### Architecture

x64

### Storage Explorer Build Number

20230309.1

### Platform

Windows

### OS Version

Win 11

### Bug Description

the move messages dialog only appears on main monitor

### Steps to Reproduce

1. Having 2 monitors (i.e. notebook + monitor)
2. open SE queue on monitor
3. select message and click "move messages"
4. no dialog
5. move SE to notebook monitor
6. click move messages - dialog appears

### Actual Experience

no dialog opens

**Comment by MRayermannMSFT** [comment]
A couple of questions...

1. Can you share some screenshots showing:
   - How your multiple displays are arranged in windows settings?
   - Your displays' resolutions and display scalings?
3. If you don't do step 5 in your original steps, do you see the move messages dialog appear?
4. With your original steps, if you try to interact with the main Storage Explorer window, are you able to?
5. If yes, then can you use press they Windows key+left/right arrow keys a couple of different times to see if you can get the monitor to appear?

**Comment by MRayermannMSFT** [comment]
@ranasch ?

**Comment by ranasch** [comment]
OK, sorry for the delay:


  1.
Screenshots - 2nd monitor (3840x1600)
[cid:bdfe2c92-36cd-4859-abd2-84542e406d1b]
select "Move message" doesn´t popup any window.
  2.
Screenshot Notebook (2400x1600)
[cid:e3353680-47f8-45aa-b90d-ddbf69ed1078]
Dialog pops up after "Move selected" was clicked
  3.
No - I must move the SE to the Notebook monitor, clicking multiple times on "Move message" doesn´t trigger the popup otherwise
  4.
Yes, I can otherwise interact just fine. Sometimes the menu disappears:
[cid:8c77fa9f-fa59-4e09-8976-62b6fd02a31a]
  5.
WindowsKey + Left/ Right doesn´t show the dialog - it´s simply not there.

Thx,
Rainer

Rainer Nasch
Senior Consultant
Microsoft Industry Solutions
+49 (221) 8010-2340
Microsoft Deutschland GmbH – Niederlassung Köln | Holzmarkt 2a, D-50676 Köln

Microsoft Deutschland GmbH
Walter-Gropius-Straße 5, 80807 München
Microsoft - Official Home Page<https://www.microsoft.com/de-de?ql=2>
Home | News Center Microsoft<https://news.microsoft.com/de-de/>
Datenschutzerklärung von Microsoft – Microsoft-Datenschutz<https://privacy.microsoft.com/de-DE/privacystatement>

Geschäftsführer*in: Dr. Marianne Janik (Vorsitzende), Florian Deter, Benjamin O. Orndorff, Keith Dolliver | Amtsgericht München, HRB 70438


________________________________
Von: Matthew Rayermann ***@***.***>
Gesendet: Montag, 27. März 2023 20:21
An: microsoft/AzureStorageExplorer ***@***.***>
Cc: Rainer Nasch ***@***.***>; Author ***@***.***>
Betreff: Re: [microsoft/AzureStorageExplorer] On dualscreen: Move Messages dialog only appearing on one screen (Issue #6690)


A couple of questions...

  1.  Can you share some screenshots showing:
     *   How your multiple displays are arranged in windows settings?
     *   Your displays' resolutions and display scalings?
  2.  If you don't do step 5 in your original steps, do you see the move messages dialog appear?
  3.  With your original steps, if you try to interact with the main Storage Explorer window, are you able to?
  4.  If yes, then can you use press they Windows key+left/right arrow keys a couple of different times to see if you can get the monitor to appear?

**Comment by MRayermannMSFT** [comment]
@ranasch unfortunately screenshots cannot be shared over email response. You have to share them directly on GitHub.

**Comment by MRayermannMSFT** [comment]
Let's look into adding a bunch of logging around dialog window opening, size calculating, and position calculating, make a private build, and then share it.

**Comment by craxal** [comment]
@ranasch Can you please post your screenshots again? As mentioned earlier, you can't post screenshots via email response. You need to share them directly through the GitHub website.
