### ISSUE TITLE
When using Quick Access to the tables, I get an errormessage

### ISSUE THREAD

**Issue by ChrisTarget365** [microsoft/AzureStorageExplorer#6691]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.28.1

### Architecture

i86

### Platform

All

### Bug Description

When using Quick Access to the tables, I get an errormessage. When accessing the same tables the usual, long way, everything works fine. So there seems to be an issue with the user defined shortcuts. 

![image](https://user-images.githubusercontent.com/60473815/226549559-34ee33db-623b-4758-a875-229e3cf017bc.png)

### Steps to Reproduce

1. Create a Quick Access-link and pin it.
2. Click it
3. Error message

### Actual Experience

1. Create a Quick Access-link and pin it.
2. Click it
3. Error message

**Comment by MRayermannMSFT** [comment]
@ChrisTarget365 how are you originally connecting to your tables? Did you:
1. Sign in and either browse under a subscription or attach with Azure AD, and if so, do you have access to keys or are you relying on RBAC permissions?
2. Attach with SAS, and if so, is your SAS not-expired and what permissions does it have?
3. Attach with key, and if so, is the key still valid for the account?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you're still encountering this problem, feel free to open a new issue.
