### ISSUE TITLE
Strings on the 'Search for resources of type' panel overflow as the 'EXPLORER' panel narrows horizontally

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6695]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230322.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases 
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Launch Storage Explorer -> Narrow the EXPLORER panel horizontally.
2. Click the filter icon on the 'Search for resources' box.
3. Check whether no string overflows.

## Expected Experience ##
No string overflows.
![image](https://user-images.githubusercontent.com/41351993/227147390-07680abf-8b39-498e-ab84-971d71c6ff5e.png)

## Actual Experience ##
Two strings overflow.
![image](https://user-images.githubusercontent.com/41351993/227147424-2355fc81-be45-4b2b-83c2-2ea26889e508.png)

**Comment by MRayermannMSFT** [comment]
Not a regression. If you change the language to Russian, the issue reproduces in 1.28 and earlier.

**Comment by v-xianya** [comment]
Verified this issue on all languages using the build main 20230327.1. Fixed.
