### ISSUE TITLE
The location of the scrollbar on the 'Actions & Properties' panel changes if narrow the panel horizontally

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6696]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230322.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Exploratory testing
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Launch Storage Explorer -> Select one storage account.
2. Narrow its 'Actions & Properties' Panel horizontally.
3. Check whether the location of the scrollbar doesn't change.

## Expected Experience ##
The location of the scrollbar doesn't change.
![image](https://user-images.githubusercontent.com/41351993/227153943-d51feaed-f8c2-485a-b809-0ea93e090be1.png)

## Actual Experience ##
The location of the scrollbar changes.
![image](https://user-images.githubusercontent.com/41351993/227154066-e27dd64f-0e4d-4a6d-b067-fc4fc1144bfe.png)

## Additional Context ##
Here is the record:
![scrollbar](https://user-images.githubusercontent.com/41351993/227155685-5aa793c7-2c12-4898-a6ea-8c7176339712.gif)

**Comment by MRayermannMSFT** [comment]
Not a regression. If you change the language to Russian, the issue reproduces in 1.28 and earlier.

**Comment by MRayermannMSFT** [comment]
I will fix both the English case of having a scroll bar when viewing with max zoom and min width. Will also fix the issue of the bottom most horizontal scroll bar disappearing for non-English langs when viewing with max zoom and min width.

**Comment by v-xianya** [comment]
Verified this issue on all languages using the build main 20230327.1. Fixed.
