### ISSUE TITLE
The string 'Cold' is not translated on the 'Update Access Tier' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6699]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230324.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Language**: All languages
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文(简体)' -> Restart Storage Explorer.
3. Expand one storage account -> Blob Containers.
4. Create a blob container -> Upload one blob -> Update the blob access tier to 'Cold'.
5. Right click the blob -> Click 'Change access tier...'.
6. Check whether all strings are translated on the dialog.

## Expected Experience ##
All strings are translated on the dialog.

## Actual Experience ##
The string 'Cold' is not translated.
![image](https://user-images.githubusercontent.com/41351993/227444359-3160eef0-76dc-4bfa-805d-bd4008b6cf4f.png)

**Comment by JasonYeMSFT** [comment]
We added the string for translation. We will track the translation in this issue https://github.com/microsoft/AzureStorageExplorer/issues/6700
