### ISSUE TITLE
Uploading DaCPaC file onto Azure Storage error

### ISSUE THREAD

**Issue by oharbe** [microsoft/AzureStorageExplorer#670]
{
  "name": "Error",
  "message": "getaddrinfo ENOTFOUND traffictfs.blob.core.windows.net traffictfs.blob.core.windows.net:443",
  "stack": "Error: getaddrinfo ENOTFOUND traffictfs.blob.core.windows.net traffictfs.blob.core.windows.net:443\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
  "code": "ENOTFOUND",
  "errno": "ENOTFOUND",
  "syscall": "getaddrinfo",
  "hostname": "traffictfs.blob.core.windows.net",
  "host": "traffictfs.blob.core.windows.net",
  "port": "443",
  "innerError": {
    "code": "ESOCKETTIMEDOUT",
    "connect": false,
    "innerError": {
      "code": "ESOCKETTIMEDOUT",
      "connect": false,
      "innerError": {
        "code": "ESOCKETTIMEDOUT",
        "connect": false,
        "innerError": {
          "code": "ESOCKETTIMEDOUT",
          "connect": false,
          "innerError": {
            "code": "ESOCKETTIMEDOUT",
            "connect": false,
            "innerError": {
              "code": "ESOCKETTIMEDOUT",
              "connect": false
            }
          }
        }
      }
    }
  }
}

**Comment by MRayermannMSFT** [comment]
@oharbe are you still having issues?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you're still have problems. Thanks.
