### ISSUE TITLE
The localized strings for 'Cool' and 'Cold' are the same

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6700]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230324.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**Language**: Chinese (simplified)/Portuguese (Brazil)
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '中文(简体)' -> Restart Storage Explorer.
3. Expand one storage account -> Blob Containers.
4. Create a blob container -> Upload one blob with 'Hot' access tier.
5. Right click the blob -> Click 'Change access tier...'.
6. Check whether the localized strings for 'Cool' and 'Cold' are different.

## Expected Experience ##
The localized strings for 'Cool' and 'Cold' are different.

## Actual Experience ##
The localized strings for 'Cool' and 'Cold' are the same.
![image](https://user-images.githubusercontent.com/41351993/227444099-d9c5b5c1-2ad5-4108-98da-1af595c7beb9.png)

## Additional Context ##
1. This issue only reproduces on Chinese (simplified)/Portuguese (Brazil).
2. Here is the screenshot on Portuguese (Brazil).
![image](https://user-images.githubusercontent.com/41351993/227448982-b1ccb094-c327-4f74-99c6-51f9125f18be.png)

**Comment by JasonYeMSFT** [comment]
This would be a tricky problem to solve...

**Comment by JasonYeMSFT** [comment]
I manually edited the strings so that there shouldn't be any place where we show two identical strings, one for "Cool" and the other for "Cold". Please reopen the bug and let me know where there are still identical/ambiguous strings.

**Comment by v-xianya** [comment]
@JasonYeMSFT Verified this issue on the rel build 20230425.6. Reproduce. Both Chinese (simplified)/Portuguese (Brazil).

![image](https://user-images.githubusercontent.com/41351993/234155868-e8d3934a-cb61-4069-b97b-da63a4e8e417.png)

**Comment by v-xianya** [comment]
Verified this issue on the build 20230426.6. Fixed. So, we are going to close it.
![image](https://user-images.githubusercontent.com/41351993/234449346-2e625df7-07b5-4005-95bb-c0a844b4abd7.png)

**Comment by v-xianya** [comment]
Verified this issue on the 1.30.1 version. The localized strings 'Cold' & 'Cool' make sense.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/d0daf5be-8f52-4de5-8200-aa88192a53f9)
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/d07b4cca-3bef-4703-85b9-f93ff7e09a1a)
