### ISSUE TITLE
An error dialog pops up when clicking the action 'Copy Blob Container' or 'Copy File Share'

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6701]
**Storage Explorer Version:** 1.29.0-dev
**Build Number:** 20230324.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.28.1)

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Right click the blob container.
3. Click 'Copy Blob Container'.
4. Check whether no error dialog pops up.

## Expected Experience ##
No error dialog pops up.

## Actual Experience ##
An error dialog pops up.
![image](https://user-images.githubusercontent.com/87792676/227453845-5cc5d8ba-7a68-4227-8e36-044ec0afcb40.png)

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230328.3. Fixed. So, we are going to close it.
