### ISSUE TITLE
All icons are missed on the toolbar of one ADLS Gen2 blob container/file share

### ISSUE THREAD

**Issue by v-sunnsun** [microsoft/AzureStorageExplorer#6705]
**Storage Explorer Version** : 1.29.0-dev
**Build Number** : 20230327.1
**Branch**: main
**Platform/OS**: Windows 10
**Architecture**: ia32
**How Found**: From running test cases
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce 

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Observe the toolbar.
3. Check whether all icons are displayed normally.

## Expected Experience 
All icons are displayed normally.
![image](https://user-images.githubusercontent.com/122582307/227830352-69ab0fc6-7115-4611-a8ff-9cd3f6ee5cf6.png)

## Actual Experience
All icons are missed.
![image](https://user-images.githubusercontent.com/122582307/227830415-45347f72-69f4-481b-82d4-a26557f25313.png)

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230328.3. Fixed. So, we are going to close it.
