### ISSUE TITLE
Miss icons in the 'Manage Access' dialog for one ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-sunnsun** [microsoft/AzureStorageExplorer#6707]
**Storage Explorer Version** : 1.29.0-dev
**Build Number** : 20230327.1
**Branch**: main
**Platform/OS**: Windows 10
**Architecture**: ia32
**How Found**: From running test cases
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce 

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Right click one blob container -> Click 'Manage Access Control Lists...'.
3. Check whether no icon is missed in the 'Manage Access' dialog.

## Expected Experience 
No icon is missed in the 'Manage Access' dialog.
![image](https://user-images.githubusercontent.com/122582307/227871728-e2fc6e20-ab9d-4ea0-bb3f-3185cfd7f0d9.png)

## Actual Experience
Miss icons in the 'Manage Access' dialog.
![image](https://user-images.githubusercontent.com/122582307/227873359-b7236110-6975-4842-8d4a-41edde57684b.png)

## Additional Context ##
This issue does not reproduce on Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro).

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230328.3. Fixed. So, we are going to close it.
