### ISSUE TITLE
Fail to clone one blob under an Azure AD attached blob container with 'Storage Blob Data Contributor' role

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6709]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230327.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.27.2)

## Steps to Reproduce ##
1. Expand one non-ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Assign the rbac role 'Storage Blob Data contributor' to the blob container.
3. Attach the blob container via Azure AD.
4. Upload one blob to the Azure AD attached blob container.
5. Try to clone the blob.
6. Check whether succeeds to clone the blob.

## Expected Experience ##
Succeed to clone the blob.

## Actual Experience ##
Fail to clone the blob.
![image](https://user-images.githubusercontent.com/41351993/227896470-eae5df8c-15a6-4698-b50f-23456d51d970.png)

Error details:
`{
  "message": "\"UnexpectedQuit\""
}`

## Additional Context ##
This issue also reproduces when assigning rbac role 'Storage Blob Data contributor' on storage account level.

**Comment by JasonYeMSFT** [comment]
@richardmsft could you please investigate to see if this is our bug or azcopy bug?

**Comment by JasonYeMSFT** [comment]
According to Richard, this is due to Storage Blob Data Contributor role not granting the permission to read/write blob tags. We should make preserve tags optional when using Azure AD credentials.

**Comment by JasonYeMSFT** [comment]
Now for Azure AD credentials, we will prompt the user on whether to enable preserving tags. If they select yes and the permission isn't there, it will fail like this. Otherwise, they can disable it and unblock themselves.

**Comment by v-xianya** [comment]
@JasonYeMSFT Verified this issue on the build main 20230410.1. Fixed.

If 'preserve blob tags' option is checked, there is a failed activity log. Is it possible to make the error message helpful?
![image](https://user-images.githubusercontent.com/41351993/230809410-02530525-c097-41c7-a44f-45d1872e1725.png)

![image](https://user-images.githubusercontent.com/41351993/230809363-37bfe2b1-4de5-44f9-ae0d-52a7a525affa.png)

**Comment by JasonYeMSFT** [comment]
@v-xianya That needs to be done by the AzCopy team.
