### ISSUE TITLE
cannot read property 'connection string' of undefined

### ISSUE THREAD

**Issue by basilcherian** [microsoft/AzureStorageExplorer#671]
**Storage Explorer Version**: 1.4.1
**Platform/OS Version**: Windows 10 Enterprise April 2018 Update
**Architecture**: x64 bit
**Regression From**: The version prior to 1.4.1
#### Steps to Reproduce: ####
1. Open Azure Storage Explorer. It takes to my preset Subscription, but instead of showing me the Storage Accounts listed under the Subscription, it is throwing the error: **cannot read property 'connection string' of undefined**
2. I tried to remove my login and added back but still facing the same issue.

#### Expected Experience: ####
It should show me the list of Storage Accounts

#### Actual Experience: ####
Throwing an error as shown above

**Comment by gavintgh** [comment]
same issue

**Comment by MRayermannMSFT** [comment]
@basilcherian and @gavintgh are y'all still having issues?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
