### ISSUE TITLE
Status strings display incorrectly for one empty ADLS Gen2 blob container/file share

### ISSUE THREAD

**Issue by v-sunnsun** [microsoft/AzureStorageExplorer#6710]
**Storage Explorer Version** : 1.29.0-dev
**Build Number** : 20230328.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce 

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a new blob container.
3. Check the status strings in the left corner of the editor display correctly.

## Expected Experience 
The status strings display correctly.
![image](https://user-images.githubusercontent.com/122582307/228155880-e8bad472-4ed0-4c01-ad5b-0469994623d2.png)

## Actual Experience
The status strings display incorrectly.
![image](https://user-images.githubusercontent.com/122582307/228156194-e583fdf4-0185-4547-8c1c-d01692365ae2.png)

**Comment by v-xianya** [comment]
Verified this issue on the build 20230331.5. The status strings have been updated. 

For ADLS Gen2 blob container
![image](https://user-images.githubusercontent.com/41351993/229012295-54692ce1-194b-48f4-8819-a93850a456cc.png)

For file share
![image](https://user-images.githubusercontent.com/41351993/229012342-b840e3cb-c15f-46b3-b0ee-8f70b26719f4.png)
