### ISSUE TITLE
It is better to enable the action 'Properties...' for soft deleted blobs

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6711]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230328.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload a blob.
3. Soft delete the blob -> Switch to the context menu 'Active and soft deleted blobs'.
4. Right click the soft deleted blob -> Observe its context menu.
5. Check whether the action 'Properties...' is enabled.

## Expected Experience ##
It is better to enable the action 'Properties...'.

## Actual Experience ##
The action 'Properties...' is disabled.
![image](https://user-images.githubusercontent.com/41351993/228170485-35bbd0e7-0ad8-49b8-9b52-e9388776f580.png)
## Additional Context ##
On Portal, the action 'Properties' is enabled.
![image](https://user-images.githubusercontent.com/41351993/228170897-99f233db-31db-48ab-9dbf-b20429281abe.png)

**Comment by JasonYeMSFT** [comment]
We have presented almost all the available properties (only exception is content MD5 which isn't commonly read) in the data table so a separate properties dialog wouldn't be much more useful.
