### ISSUE TITLE
No explorer window is shown on Mac

### ISSUE THREAD

**Issue by mhansinger** [microsoft/AzureStorageExplorer#6713]
Version: 1.28.0
AzCopy-Version: 10.17.0

Plattform: macOS 13.2.1
Architektur: arm64 
Buildnummer: 20230214.4 
Commit: f07b271300 
Support-ID: 3ceaec8f-9b8e-84ef-3c22-7fcbceb60c13

**Problem:**
Storage Explorere Program is running, but I cannot open any explorer window. However, no error message is shown. 
Previous AZ Storage Explorer Versions did work on this Mac (however, cannot tell which exact version it was).

**Comment by MRayermannMSFT** [comment]
Hi @mhansinger a couple of questions:
1. Can you elaborate on what you mean when you say "but I cannot open any explorer window"? Do you mean there is literally 0 Storage Explorer UI, or do you mean you cannot browse the contents of any of your containers?
2. Are you using the macOS ARM64 preview? If no, can you please try using it? You can download from this link: https://storageexplorerpublish.blob.core.windows.net/macArm64

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. Please try the steps we have recommended and open a new issue if you still have this problem.
