### ISSUE TITLE
There is an extra action 'Pin to Quick Access' for one QA storage account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6714]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230329.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Select one storage account -> Pin it to the 'Quick Access' node.
2. Right click the QA storage account -> Observe its context menu.
3. Check there is no extra action.

## Expected Experience ##
There is no extra action.
![image](https://user-images.githubusercontent.com/41351993/228415834-83728cb9-914c-4cd5-9c87-962cb4b4b6ad.png)

## Actual Experience ##
There is an extra action 'Pin to Quick Access'.
![image](https://user-images.githubusercontent.com/41351993/228416241-3840638e-c4b8-45f8-998a-8119559e4509.png)

**Comment by richardMSFT** [comment]
This should be fixed in most recent build on main. I confirmed it on my end, but if it's still appearing on your end please open up the issue again. Thanks!

**Comment by v-xianya** [comment]
Hi @richardMSFT Verified this issue on the main build 20230330.3. Reproduce.
We are going to re-open this issue.

**Comment by v-xianya** [comment]
Update: This issue also reproduces for '(Emulator - Default Ports) (Key)' node under the 'Quick Access' node.
![image](https://user-images.githubusercontent.com/41351993/228755628-9e878d14-cad8-40e6-995b-198d6ae755ef.png)

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230331.5. Fixed. We are going to close it.
![image](https://user-images.githubusercontent.com/41351993/229006817-fe87837c-388f-434f-a357-42d81ed20c0f.png)
