### ISSUE TITLE
An error dialog pops up when using direct link to open one app configuration

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6715]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230329.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer.
2. Expand the 'Application Configurations' node.
3. Select one app configuration (Make sure already has a correct permission).
4. Right click the app configuration -> Click 'Copy Direct Link to App Configuration Store'.
5. Paste the link to the browser -> Open it.
6. Check no error dialog pops up.

## Expected Experience ##
No error dialog pops up.
## Actual Experience ##
An error dialog pops up.
![image](https://user-images.githubusercontent.com/41351993/228444363-dfc4bf97-e0ae-4309-acd1-d602fae665c0.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230509.5, Fixed. So, we are going to close it.
