### ISSUE TITLE
Use Azurite SSL Storage

### ISSUE THREAD

**Issue by Toso82** [microsoft/AzureStorageExplorer#6716]
### Preflight Checklist

- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).

### Storage Explorer Version

1.28.1

### Regression From

1.18.1

### Architecture

x64

### Storage Explorer Build Number

azurite@3.22.0

### Platform

All

### Bug Description

Non è possibile recuperare le risorse figlio.

Dettagli:
{
  "name": "FetchError",
  "message": "request to https://127.0.0.1:10000/devstoreaccount1?comp=list&include=metadata failed, reason: unable to verify the first certificate",
  "stack": "FetchError: request to https://127.0.0.1:10000/devstoreaccount1?comp=list&include=metadata failed, reason: unable to verify the first certificate\n    at ClientRequest.<anonymous> (C:\\Users\\Giacomo\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-blob-extension\\dist\\src\\index.js:2:2441854)\n    at ClientRequest.emit (node:events:513:28)\n    at TLSSocket.socketErrorListener (node:_http_client:481:9)\n    at TLSSocket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "UNABLE_TO_VERIFY_LEAF_SIGNATURE",
  "code": "UNABLE_TO_VERIFY_LEAF_SIGNATURE"
}

### Steps to Reproduce

1. Lunch Storage Explorer
2. Expand Azurite Blob Container
3. Error

### Actual Experience

I try to add SSL certificate but notthing 
I have Azurite certificate config with cert.pfx

**Comment by MRayermannMSFT** [comment]
Hi I believe there should be two options for getting this to work:
1. If you have added the certificate to your OS certificate store, you should be able to enable System Proxy (Settings > Application > Proxy > dropdown > System Proxy (preview))
2. You can manually import the certificate into Storage Explorer and use no proxy/app proxy settings/environment variable proxy settings. If you do this though, make sure that the certificate is in a base64 format. You cannot use the .pfx version of the certificate.

**Comment by Toso82** [comment]
Hi sorry for late i try with first solution:

1.   System Proxy (preview) 

Non è possibile recuperare le risorse figlio.

![image](https://user-images.githubusercontent.com/1615307/234774802-250a1362-7b1a-4c64-933a-fb29e202e266.png)

![image](https://user-images.githubusercontent.com/1615307/234774608-2fc5bc8d-1948-4d0d-ac6e-241b0c456781.png)

I use a Pfx Certificate in Azurite.

In witch catalog i must to import the certificate for sure i do well?

**Comment by JasonYeMSFT** [comment]
@Toso82 To import your certificate, search for "Certificate" in the start menu and select "Manage user certificates". In opened app window, expand "Tested Root Certification Authorities", right click 
Certificates" and select "All Tasks" > "Import". Then you can follow the wizard dialog to complete importing your certificate. If you still run into the error after importing your certificate, you might want to inspect the contents of the certificate to see if every field is supported by Azurite/Electron/NodeJS.

**Comment by Toso82** [comment]
@JasonYeMSFT  I import certificate as explain but give me same error

![image](https://user-images.githubusercontent.com/1615307/236910361-4bb90881-91a8-4aaf-843c-87640c4a02b6.png)

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue we recommend opening a support ticket via the Azure Portal. Alternatively you can open a new issue here.
