### ISSUE TITLE
The option 'App Configuration Store' on the 'Search for resources of type' panel is unchecked after restarting Storage Explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6718]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230329.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Launch Storage Explorer -> Install Azure App Configuration extension for Storage Explorer.
2. Open the panel 'Search for resources of type:'.
3. Check the option 'App Configuration Store'.
4. Restart Storage Explorer -> Open the panel 'Search for resources of type:'.
5. Check whether the option 'App Configuration Store' is checked or not.

## Expected Experience ##
The option 'App Configuration Store' is checked.
![image](https://user-images.githubusercontent.com/41351993/228479968-53474f7d-1f99-474a-a347-4c65025fa589.png)

## Actual Experience ##
The option 'App Configuration Store' is unchecked.
![image](https://user-images.githubusercontent.com/41351993/228479712-0699386a-0808-4d5a-b571-5041424fb808.png)

## Additional Context ##
This issue doesn't reproduce for other types.

**Comment by JasonYeMSFT** [comment]
The behavior described is expected. Instead of always selecting all options, Storage Explorer remembers the selected search options each time it starts a search. In this case, if you select the App Configuration Store option, start a search and then close Storage Explorer, it should be selected then.

**Comment by v-xianya** [comment]
Hi @JasonYeMSFT 
thank you for the response!
`if you select the App Configuration Store option, start a search and then close Storage Explorer, it should be selected then.`  -> It works as the description.

For other options, such as Resource Groups (Disks), will be selected after restarting Storage Explorer, regardless of whether the option is unchecked or checked. So, should we keep a consistent between 'App Configuration Store option' and other type options?

**Comment by JasonYeMSFT** [comment]
@v-xianya I checked the code. The logic to determine whether a search option is enabled is consistent for all services. If no search has been run, Storage Explorer by default checks all the options. If a search has been run, the previously selected options are checked. If you go to the settings file, manually remove this entry "tree.search.checkedTypes" and redo the repro steps I believe you will see the App Configuration option enabled.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230407.2. Fixed.
The option 'App Configuration Store' on the 'Search for resources of type' panel is checked after restarting Storage Explorer
