### ISSUE TITLE
Release macOS ARM Preview 1.28.1

### ISSUE THREAD

**Issue by mariussoutier** [microsoft/AzureStorageExplorer#6720]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Downloading ARM Preview only downloads 1.28.0

### Desired Solution

Please release 1.28.1 for macOS ARM

### Additional Context

Latest version on ARM is much much faster on M1 than Rosetta build

**Comment by MRayermannMSFT** [comment]
@mariussoutier can you check for updates again? You can do so manually by going to the app bar at the top of your screen and clicking "Microsoft Azure Storage Explorer" > "Check for Updates".

**Comment by mariussoutier** [comment]
👍 Updated correctly, thanks!
