### ISSUE TITLE
The context menu key doesn't take effect for new table explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6721]
**Storage Explorer Version**: 1.28.0-dev
**Build Number**: 20230330.2
**Branch**: feature/table-explorer-react
**Platform/OS**: Windows 10/Linux Ubuntu 22.04
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Right click one table -> Click '[2] Open'.
3. Add one entity -> Select the entity.
4. Press the context menu key.
5. Check whether the context menu shows.

## Expected Experience ##
The context menu shows.

## Actual Experience ##
No context menu shows.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20230406.3. Fixed.
