### ISSUE TITLE
The error message doesn't disappear after clearing invalid strings in text editor

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6722]
**Storage Explorer Version**: 1.28.0-dev
**Build Number**: 20230330.2
**Branch**: feature/table-explorer-react
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.0.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Right click one table -> Click '[2] Open'.
3. Click 'Query' -> Open the text editor.
4. Type '1' into the text editor -> Execute query.
5. There is an error message -> Click 'Clear query'.
6. Check whether the error message disappears.

## Expected Experience ##
The error message disappears.
![image](https://user-images.githubusercontent.com/41351993/228744281-9ac08446-f704-4f4e-8397-010212d7b732.png)

## Actual Experience ##
The error message doesn't disappear.
![image](https://user-images.githubusercontent.com/41351993/228744266-9e0336bf-2304-45f0-8fbd-7f770bf852c9.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the main/20230406.3. Fixed.
