### ISSUE TITLE
'Select All' or 'Select All in Page' doesn't take effect for tables

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6723]
**Storage Explorer Version:** 1.29.0-dev
**Build Number:** 20230330.2
**Branch:** feature/table-explorer-react
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture:** ia32/x64/arm64
**How Found:** From running test cases
**Regression From:** Previous release (1.28.1)

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create a table -> Right click the table -> Click '[2] Open'.
3. Add one entity -> Click 'Select All...'.
4. Check whether the entity is selected.

## Expected Experience ##
The entity is selected.

## Actual Experience ##
The entity is not selected.

## Additional Experience ##
This issue doesn't reproduce when clicking 'Select All -> Select All Cached'.

**Comment by craxal** [comment]
@v-kellylou I haven't observed this in some time. Please verify with a new build.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20230406.3.
