### ISSUE TITLE
The 'Query builder' action is disabled after clearing the query in text editor

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6724]
**Storage Explorer Version:** 1.29.0-dev
**Build Number:** 20230330.2
**Branch:** feature/table-explorer-react
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture:** ia32/x64/arm64
**How Found:** From running test cases
**Regression From:** Previous release (1.28.1)

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Right click one table -> Click '[2] Open' -> Add one entity.
3. Click 'Query' -> Open the text editor.
4. Clear the text editor.
5. Check whether the 'Query builder' action is enabled.

## Expected Experience ##
The 'Query builder' action is enabled.
![image](https://user-images.githubusercontent.com/87792676/228749513-400e3073-77e1-4053-9aa0-d642f9a10043.png)

## Actual Experience ##
The 'Query builder' action is disabled.
![image](https://user-images.githubusercontent.com/87792676/228749273-a1c9ccac-ddda-4684-a56b-8e0bba704947.png)

**Comment by craxal** [comment]
@v-kellyluo I have not observed this behavior for some time. Please reverify with a new build.

**Comment by craxal** [comment]
@v-kellyluo How did you clear the query? Did you click the Clear Query button, or did you backspace until the text was gone?

**Comment by v-kellyluo** [comment]
@craxal , I pressed backspace until the text was gone.
Verified this issue on the build main 20230406.3, it doesn't reproduce if pressing backspace until the text was gone, but it still reproduces if selecting all then pressing backspace.

**Comment by v-kellyluo** [comment]
@craxal , verified this issue on the build 20230508.1, the 'Query builder' action is still disabled if selecting all then pressing backspace, which is different from previous release, so we are going to reopen it.

**Comment by craxal** [comment]
@v-kellyluo I cannot reproduce on either 20230506.4 or 20230508.1. Can you provide a screenshot or GIF or a more detailed description of what you are doing and observing?

**Comment by craxal** [comment]
OK, I was able to reproduce if selecting all the text and deleting is the first thing I do. Before deletion, I can go back to the builder. Bit odd, and I'll look into it, but there is a workaround: edit the text and delete again.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230531.3. Fixed.
