### ISSUE TITLE
The 'Show top results' field is not cleared after clearing query

### ISSUE THREAD

**Issue by v-sunnsun** [microsoft/AzureStorageExplorer#6726]
**Storage Explorer Version** : 1.29.0-dev
**Build Number** : 20230330.2
**Branch**: feature/table-explorer-react
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce 

1. Expand one storage account -> Tables.
2. Right click one table -> Click '[2] Open' -> Click 'Query'.
3. Expand the 'Advanced Options' -> Type '2' into the 'Show top results' field -> Click 'Clear query'.
4. Check whether the 'Show top results' field is cleared.

## Expected Experience 
The 'Show top results' field is cleared.
![image](https://user-images.githubusercontent.com/122582307/228799298-e0808d72-306f-42e9-9bb3-09a488b17761.png)

## Actual Experience
The 'Show top results' field is not cleared.
![image](https://user-images.githubusercontent.com/122582307/228799150-d4eab9e7-c0e5-48a2-9c38-107947027a0b.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20230406.3. Fixed.
