### ISSUE TITLE
Add setting: Data Explorers > Listing Batch Size

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#6728]
Add the setting Data Explorers > Listing Batch Size. This setting should control both:
1. How many things are loaded on open by data explorers
2. How many things are loaded on load-more by data explorers

The setting should affect:
- Blob explorer
- Gen2 explorer
- File Share explorer
- Table explorer

Setting default should be 5000, as that is the max list size for all container data list calls.

Blob and Gen2 are P1, File Share is P2, Table is P3, for 1.29. If not all 4 are done, then move issue to 1.30 so not-completed explorers are done then.

**Comment by JasonYeMSFT** [comment]
Related to https://github.com/microsoft/AzureStorageExplorer/issues/1527
