### ISSUE TITLE
CSV ADLS Gen2 blobs are previewed as text

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6729]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230331.5
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3 (Apple M1 Air)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one csv blob. (Make sure the Content Type is text/csv)
3. Select the blob -> Click 'Preview'.
4. Check whether the blob is previewed in tabular form.

## Expected Experience ##
The blob is previewed in tabular form.

## Actual Experience ##
The blob is previewed as text.

## Additional Context ##
1. This issue doesn't reproduce for regular blobs/files.
2. This issue doesn't reproduce for CSV ADLS Gen2 blobs with content type 'application/vnd.ms-excel’.

**Comment by craxal** [comment]
Blocked by #6750.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230413.5. Fixed.
