### ISSUE TITLE
The copied directory's name doesn't display when copying a subdirectory to the top level of a file share

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#673]
Storage Explorer Version: 1.4.2
Platform/OS Version: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
Architecture: ia32/x64
Build Number: 20180917.1
Commit: f66de7ea
Regression From: Not a regression

#### Steps to Reproduce: ####
1. Open one file share which contains subdirectories -> Go to one directory then copy a subdirectory.
2. Back to the top level of the opened file share then paste the selected subdirectory.
3. Check whether the copied directory name displays well or not.

#### Expected Experience: ####
This copied directory's name displays well.

#### Actual Experience: ####
This copied directory's name doesn't display.
![capture1](https://user-images.githubusercontent.com/41351993/45673469-3f479600-bb1a-11e8-8807-482cd4bcbdcd.PNG)

#### More Info: ####
1. Only display one directory with empty name after copying multiple subdirectories to the top level of the file share.
2. Copied directories name display well after refreshing.

**Comment by v-xianya** [comment]
This issue still reproduces on build 20191220.9.

**Comment by MRayermannMSFT** [comment]
Jason make sure this works with AzCopy.

**Comment by JasonYeMSFT** [comment]
This will no longer be an issue since now we refresh/prompt for refresh after executing operations that my modify the table entries.
