### ISSUE TITLE
The row height is narrow for an entity whose visible column values are all empty

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6735]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230331.8
**Branch**: feature/table-explorer-react
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a new table -> Right click the table -> Click '[2] Open in New Tab'.
3. Click 'Add' -> Click 'Insert'.
4. Click 'Column Options' -> Clear 'Timestamp' column -> Click 'OK'.
5. Check the size of the entity shows normal.

## Expected Experience ##
The size of the entity shows normal.
![image](https://user-images.githubusercontent.com/41351993/229440982-595d9fee-5081-45ba-acbf-54ac25855254.png)

## Actual Experience ##
The size of the entity is narrowed.
![image](https://user-images.githubusercontent.com/41351993/229440591-506ea5f8-ee00-4c4f-9a4a-4f2c8ee61edc.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20230406.3. Fixed.

**Comment by craxal** [comment]
Reproduced in 20230420.4.

**Comment by craxal** [comment]
Merged changes to rel/1.29.0.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230421.4. Fixed.
