### ISSUE TITLE
The word 'expired' shows next to a SAS attached table which SAS URL is created by the access policy

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6736]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230331.8
**Branch**: feature/table-explorer-react
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Right click one table -> Click 'Managed Stored Access Policies...'.
3. Add one policy -> Click 'Save'.
4. Right click the table -> Click 'Get Shared Access Signature...'.
5. Using the access policy to create SAS URL.
6. Attach the table via SAS URL -> Observe the attached table node.
7. Check no word 'expired' shows.

## Expected Experience ##
No word 'expired' shows.
![image](https://user-images.githubusercontent.com/41351993/229455558-bd706f47-bf40-4049-91e5-d8f9d460d1e7.png)

## Actual Experience ##
The word 'expired' shows.
![image](https://user-images.githubusercontent.com/41351993/229455468-c9fc5d59-1570-4afc-82f8-f3a09ca2446c.png)

## Additional Context ##
This issue doesn't reproduce on main build 20230403.1.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20230406.3. Fixed.
