### ISSUE TITLE
There is no alert message when typing invalid string into 'Connection string' field on connect dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6737]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230403.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Open the connect dialog -> Click 'Storage account or service' -> Click 'Next'.
5. Type '1' into the 'Connection string' field.
6. Check there is an alert message.

## Expected Experience ##
There is an alert message.
![image](https://user-images.githubusercontent.com/41351993/229462375-606ea132-fc42-4bf6-91a4-bfa23601e663.png)

## Actual Experience ##
There is no alert message.
![image](https://user-images.githubusercontent.com/41351993/229462097-f416e169-56cb-433d-969d-022d687f4a79.png)

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230406.2. Fixed.
![image](https://user-images.githubusercontent.com/41351993/230251775-110a2012-472c-41d9-8f5f-77800cb4d6a2.png)

**Comment by v-xianya** [comment]
@craxal There is no alert message when pasting a connection string which is expired.
Could you please take a look?
![image](https://user-images.githubusercontent.com/41351993/230253007-b52189ea-689f-45b7-809a-6b41f4a568ff.png)

**Comment by craxal** [comment]
@v-xianya There's a new build that should be ready in a few minutes. Please verify again with that build.

**Comment by v-xianya** [comment]
@craxal Verified this issue on the build main 20230406.3. Reproduce.

**Comment by v-xianya** [comment]
Hi @craxal 
Verified the issue in [comment](https://github.com/microsoft/AzureStorageExplorer/issues/6737#issuecomment-1498386987). Reproduce. We are going to re-open this issue.

**Comment by craxal** [comment]
Fixes merged.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230413.5. Fixed.
