### ISSUE TITLE
Make "Load all" option for list expansion in Explorer frame

### ISSUE THREAD

**Issue by markstensgaard** [microsoft/AzureStorageExplorer#6738]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

If I need to find a particular blob container or group of similarly-named containers in a storage account with hundreds/thousands of containers, I need to repeatedly click "Load more" and scroll. 

### Desired Solution

Please add a "Load all" option, either in the Settings form, or next to "Load more" when expanding a list

### Alternatives and Workarounds

The "Open container by name" option is useful, but it requires a mix of mouse and keyboard, and needing to refocus the current window and placing the cursor, etc. It is just easier to scroll down a list sometimes.

### Additional Context

My particular need is for the blob container list, but I am certain there are others that have similar annoyances with all other list expansions in the Explorer frame.

**Comment by JasonYeMSFT** [comment]
Related to https://github.com/microsoft/AzureStorageExplorer/issues/282

**Comment by JasonYeMSFT** [comment]
I am going to close this issue and track this and other similar issues collectively in https://github.com/microsoft/AzureStorageExplorer/issues/6757
