### ISSUE TITLE
Microsoft Azure Storage Explorer for Windows

### ISSUE THREAD

**Issue by charleywjohnson** [microsoft/AzureStorageExplorer#6739]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.23.1

### Architecture

x64

### Storage Explorer Build Number

20220406.1

### Platform

Windows

### OS Version

Windows 10 21H2 Build 19044.2788

### Bug Description

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://oraustagstorac.file.core.windows.net/?comp=list failed, reason: self signed certificate in certificate chain",
  "stack": "FetchError: request to https://oraustagstorac.file.core.windows.net/?comp=list failed, reason: self signed certificate in certificate chain\n    at ClientRequest.<anonymous> (C:\\Users\\johnsoch\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:107389)\n    at ClientRequest.emit (node:events:394:28)\n    at TLSSocket.socketErrorListener (node:_http_client:447:9)\n    at TLSSocket.emit (node:events:394:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "SELF_SIGNED_CERT_IN_CHAIN",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}

### Steps to Reproduce

1. Launch Storage Explorer
2. open storage account
3. open file shares 

### Actual Experience

I get a pop up which has this message:
Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://oraustagstorac.file.core.windows.net/?comp=list failed, reason: self signed certificate in certificate chain",
  "stack": "FetchError: request to https://oraustagstorac.file.core.windows.net/?comp=list failed, reason: self signed certificate in certificate chain\n    at ClientRequest.<anonymous> (C:\\Users\\johnsoch\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:107389)\n    at ClientRequest.emit (node:events:394:28)\n    at TLSSocket.socketErrorListener (node:_http_client:447:9)\n    at TLSSocket.emit (node:events:394:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "SELF_SIGNED_CERT_IN_CHAIN",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}

### Expected Experience

I should get a list of the file shares for this account.

**Comment by stannynuytkens** [comment]
Same issue here. Generated using OpenSSL (3.1.0), running Azurite (latest container image) in docker and connecting with Azure Storage Explorer (1.28.0) following the docs.

Linked:
- https://github.com/Azure/Azurite/issues/1073
- https://github.com/microsoft/AzureStorageExplorer/issues/2859

**Comment by JasonYeMSFT** [comment]
@stannynuytkens Your issue is different from the one in the original post. If you are using certs generated from done dev-certs, we will be tracking the work to support it in your linked issue. If you need other kinds of help on your issue, please open a new one.

@charleywjohnson Are you using a proxy. Please follow the steps in this article to understand the error and see if you can mitigate it. https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows#ssl-certificate-issues

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. Please try the steps we suggested and open a new issue if you still have this problem.
