### ISSUE TITLE
No 'Preview' action shows for one soft deleted blob/archived blob

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6740]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230404.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one video blob.
3. Change the blob access tier to 'Archive'.
4. Right click the blob container -> Observe the context menu.
5. Check whether the 'Preview' action shows.

## Expected Experience ##
The 'Preview' action shows.
![image](https://user-images.githubusercontent.com/41351993/229706241-26f8b310-a77c-48c4-bbc1-2c378b130d61.png)

## Actual Experience ##
No 'Preview' action shows.
![image](https://user-images.githubusercontent.com/41351993/229704941-6d9c9b20-9480-4e3a-9d0c-e07d7e53b79b.png)

**Comment by JasonYeMSFT** [comment]
This is by design. We changed the logic controlling when to show the preview action. It will be hidden for deleted blobs and archive blobs.
