### ISSUE TITLE
The QA storage account is collapsed when deleting tables from it which are pinned to 'Quick Access' previously

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6741]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230404.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Pin one storage account to 'Quick Access' node.
2. Expand the QA storage account -> Queues.
3. Create a queue -> Pin the queue to 'Quick Access'.
4. Expand the QA storage account -> Queues.
5. Right click the queue -> Delete it.
6. Check whether the QA storage account it not collapsed.

## Expected Experience ##
The QA storage account is not collapsed.

## Actual Experience ##
The QA storage account is collapsed.

## Additional Context ##
This issue doesn't reproduce for blob containers/file shares.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230531.3. There is a new bug [6934 ](https://github.com/microsoft/AzureStorageExplorer/issues/6934)was found.

**Comment by v-xianya** [comment]
@MRayermannMSFT Verified this issue on the build main 20230531.13. 
1. Fixed of queues.
2. Reproduce for tables. So we are going to re-open this issue.

**Comment by MRayermannMSFT** [comment]
Oh I didn't notice the table part. I will defer fixing that until 1.31

**Comment by MRayermannMSFT** [comment]
This should now also be fixed for tables.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230712.4. Fixed.
