### ISSUE TITLE
There is no value when selecting 'Timestamp' as the 'Field' value in the clause

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6743]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230406.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Add one entity -> Click 'Query'.
3. Add a new clause -> Change the 'Field' value to 'Timestamp'.
4. Check whether there is a value in the 'Value' field.

## Expected Experience ##
There is a value in the 'Value' field.
![image](https://user-images.githubusercontent.com/41351993/230299486-b0737a89-3f3c-4c68-a4dd-1af0342dc91b.png)

## Actual Experience ##
There is no value in the 'Value' field.
![image](https://user-images.githubusercontent.com/41351993/230299295-33fdef07-7594-4f73-86b5-27660df7230d.png)

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230413.5. Reproduce. so, we are going to re-open it and will verify it on the newer build.

**Comment by craxal** [comment]
There was a bad package update. Published a new version.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230414.2. Fixed.
