### ISSUE TITLE
'Ctrl+S/Ctrl+Shift+S/F5' do not take effect under query builder

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6745]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230406.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Click 'Query'.
3. Press 'Ctrl+S'.
4. Check whether there is a system dialog.

## Expected Experience ##
There is a system dialog.
![image](https://user-images.githubusercontent.com/41351993/230306294-20430d20-d65a-4e45-8068-534a60596deb.png)

## Actual Experience ##
No system dialog pops up.

**Comment by craxal** [comment]
@v-xianya The system dialog will only pop up if no save file has been selected before. I'm assuming this is the first save?

**Comment by v-xianya** [comment]
@craxal Yes, it is the first save.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230413.5. Reproduce. So, we are going to reopen it and verify it on a new build.

**Comment by craxal** [comment]
There was a bad package update. Published a new version.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230414.2. Fixed.
