### ISSUE TITLE
The results for the actions "Select All in Page" and "Select All Cached" are mismatched

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6749]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230407.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Import one csv file which contains more than 100 entities.
3. Click 'Select All in Page' -> Observe the selected items next to the status string.
4. Navigate to the 2nd page.
5. Check the entities on the 2nd page are not selected.

## Expected Experience ##
The entities on the 2nd page are not selected.

## Actual Experience ##
The entities on the 2nd page are selected.

## Additional Context ##
Below is screenshot of the selected items for 'Select All in Page' & 'Select All Cached'.
![image](https://user-images.githubusercontent.com/41351993/230577055-d9b82473-2773-48bb-b8fa-68c85c83f66c.png)

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230413.5. Reproduce. So, we are going to reopen it and verify it on a new build.

**Comment by craxal** [comment]
There was a bad package update. Published a new version.
