### ISSUE TITLE
"Execute Query" button for Cosmos DB is dark-grey-on-black when using "Dark" theme and "High Contrast - Black" theme

### ISSUE THREAD

**Issue by scholtes** [microsoft/AzureStorageExplorer#675]
**Storage Explorer Version**: 1.4.1
**Build Number**: 20180822.1
**Platform/OS Version**: Windows 10 Enterprise (10.0.14393 Build 14393)
**Architecture**: ia32
**Regression From**: not determined

#### Steps to Reproduce: ####
1. Open Microsoft Azure Storage Explorer
2. Select menu "View > Themes > Dark"
3. Navigate to a Cosmos DB account in the Explorer pane on the left
4. Fold open a Database within the previously opened Cosmos DB account using the Explorer tree view
5. Fold open a Collection within the previously opened Database using the Explorer tree view
6. Right click the "Documents" object under the previously selected Collection
7. Select "Open Query Tab" from the dropdown menu
8. Observe the "Query for <collection name>" tab that opens on the right, and observe the "Execute Query" button at the top of the view 

#### Expected Experience: ####
The color contrast on the text "Expected Query" should be legible.  Either light-grey-on-black or white-on-black

#### Actual Experience: ####
The color  contrast on the text "Expected Query" is poor and shows as dark-grey-on-black.

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
