### ISSUE TITLE
The video file whose file extension is '.mov/.ogv/.m4v' can't be played when clicking 'Open in Browser' in the file share explorer

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6752]
**Storage Explorer Version:** 1.29.0-dev
**Build Number:** 20230410.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3 (Apple M1 Pro)
**Architecture:** ia32/x64/arm64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> File Shares.
2. Create a file share -> Upload one .m4v file.
3. Right click the file -> Click 'Play in Browser'.
4. Check whether succeeds to play the file,

## Expected Experience ##
Succeed to play the file,

## Actual Experience ##
Fail to play the file,

## Additional Context ##
1. Default browser: Microsoft Edge.
2. The content type of the .ogv file is video/ogg.
3. The content type of the .m4v file is video/mp4.
4. The default content type of one .mov file is video/quicktime, it cannot be played in browser, After changing its content type to video/mp4, it can be played under one blob container, it cannot be played under one file share.
5. This issue doesn't reproduce when using Firefox as the default browser.

**Comment by JasonYeMSFT** [comment]
I tried Safari, MS edge, Google Chrome and Fire Fox. I found two issues here.
1. video/quickTime is developed by Apple and it's not free. Only Safari and Fire Fox can play it.
2. Azure File service doesn't support Condition headers which is essential for many browsers to play those videos, except for Fire Fox.

I need to think about how to handle this situation.

**Comment by JasonYeMSFT** [comment]
We decided to won't fix this issue given that Fire Fox still works and ogv is not a very popular video format. I will list these caveats in the original feature request post for future reference.
