### ISSUE TITLE
An error 'fail to get source url' occurs when clicking 'Open in Browser' for video blobs under Azure AD attached blob containers (RBAC role is assigned on container level)

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6753]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230410.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3 (Apple M1 Pro)
**Architecture**: ia32/x64/arm64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload a video file.
3. Azure AD attach the blob container.
4. Go to the Azure AD attached blob container.
5. Right click the video file -> Click 'Play in Browser'.
6. Check whether succeeds to play the video file.

## Expected Experience ##
Succeed to play the video file.

## Actual Experience ##
There is an error activity log.
![image](https://user-images.githubusercontent.com/41351993/230850553-e5bafc7a-12b1-4fb8-9e67-dc3e3b219e76.png)

## Additional Context ##
1. This issue reproduces when assigning RBAC role on blob container level.
2. This issue doesn't reproduce when assigning RBAC role on storage account level.

**Comment by JasonYeMSFT** [comment]
To play the video we need to generate a SAS. For azure AD credentials, we need the permission to get the user delegation key which is at the account level. The error is expected.
