### ISSUE TITLE
It is better to specify the number for the setting 'Load Batch Size'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6754]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230410.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3 (Apple M1 Pro)
**Architecture**: ia32/x64/arm64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Open 'Settings -> Data Explorer -> Load Batch Size'.
2. Observe the description of the setting 'Load Batch Size'.

## Expected Experience ##
It is better to specify the number.

Like 'if the value is set to 10000, it will make two requests, each time loading 5000 items, and then stop',
Or 'set the value size to an integer multiple of 5000.'

## Actual Experience ##
No specific description for the number.
![image](https://user-images.githubusercontent.com/41351993/230856791-e4f62c3e-1b59-475b-b7fc-9db31764e524.png)

**Comment by JasonYeMSFT** [comment]
The default value of Load Batch Size is set to undefined meaning it will use the default batch size the explorer defines. We cannot guarantee that all services will use the same batch size in the future so not specifying it is intentional.
