### ISSUE TITLE
Fail to open the saved query in one table

### ISSUE THREAD

**Issue by v-sunnsun** [microsoft/AzureStorageExplorer#6755]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230410.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce 

1. Expand one storage account -> Tables.
2. Create a table -> Click 'Query'.
3. Add one clause -> Click 'Save query' -> Click 'Save'.
4. Click 'Open saved query' -> Choose the saved query -> Click 'Open'.
5. Check whether succeeds to open the saved query.

## Expected Experience 
Succeed to open the saved query.
![image](https://user-images.githubusercontent.com/122582307/230869810-9b895902-a17f-4e77-a1ee-a89b204d7f58.png)

## Actual Experience
Fail to open the saved query.
![image](https://user-images.githubusercontent.com/122582307/230869967-68594e7f-c944-4c57-ba45-d60c6ac105c2.png)

**Comment by craxal** [comment]
@v-sunnsun Please share the query file you tried to open.

**Comment by v-sunnsun** [comment]
Hi @craxal Here is the query file:
(.stgquery file cannot be uploaded here, so I pasted the contents to the txt file.)
[query.txt](https://github.com/microsoft/AzureStorageExplorer/files/11195599/query.txt)

**Comment by v-xianya** [comment]
Hi @craxal 
The query file is created by saving query on the new table explorer.

Here are the query files content we saved on 1.28.1 version and build #20230412.1 separately.
We noticed that on the old query files, it shows **"fileVersion":0.2**, on the new query file, it shows **"fileVersion": 1**

[old.txt](https://github.com/microsoft/AzureStorageExplorer/files/11207917/old.txt)
[new.txt](https://github.com/microsoft/AzureStorageExplorer/files/11207886/new.txt)

**Comment by craxal** [comment]
@v-xianya The "new.txt" file you just shared _is_ valid JSON. So why was the first file you shared missing all the quotes and colons?

The file version is wrong, though, so I'll look into it.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230413.5. Reproduce. Reopen it and will verify it on a newer build.

**Comment by craxal** [comment]
There was a bad package update. Published a new version.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230414.2. Fixed.
