### ISSUE TITLE
Unable to re-authenticate azure storage explorer

### ISSUE THREAD

**Issue by joesalvati68** [microsoft/AzureStorageExplorer#6756]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.28.1

### Architecture

x64

### Storage Explorer Build Number

20230309.1

### Platform

Windows

### OS Version

Windows 11

### Bug Description

When I open Azure storage explorer and it asks me to login to authenticate, once I click on Sign in With Azure and then next, it refuses to connect and I get this error message. 
{
  "name": null,
  "message": "\"{\\n  \\\"message\\\": \\\"\\\\\\\"No matching accounts found in any MSAL cache.\\\\\\\"\\\"\\n}\""
}

That account is very much in my subscription as I am able to access it directly through Azure.  I am the owner on the account.

### Steps to Reproduce

 1. Launch Storage Explorer
 2. Click Sign In
 3. Authenticate with Azure
 4. Click Next

### Actual Experience

After clicking next eventually it will time out and give me this:
It doesn't look like you're signed in yet. If you want to reattempt signing in, go back and try again with your selected environment.

**Comment by narayansinght88** [comment]
This request is not authorized to perform this operation.

This storage account's 'Firewalls & virtual networks' settings may be blocking access to storage services. Try adding your client IP address to the firewall exceptions, or by allowing access from 'all networks' instead of 'selected networks'. To learn more about Azure Storage firewalls and virtual networks, visit http://go.microsoft.com/fwlink/?LinkId=845443.

Error Details:
{
  "name": "RestError",
  "code": "AccountIsDisabled",
  "statusCode": 403,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://demo.blob.core.windows.net/?comp=list&include=metadata",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2021-10-04"
        },
        "accept": {
          "name": "Accept",
          "value": "application/xml"
        },
        "user-agent": {
          "name": "User-Agent",
          "value": "Microsoft Azure Storage Explorer/1.28.1 (win32) azsdk-js-storageblob/12.12.0 (NODE-VERSION v16.17.1; Windows_NT 10.0.22621)"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "e5ad39dc-5c64-457a-8f6a-cc9206725dd3"
        },
        "x-ms-date": {
          "name": "x-ms-date",
          "value": "Mon, 10 Apr 2023 14:15:55 GMT"
        },
        "authorization": {
          "name": "Authorization",
          "value": "Signed SharedKey Redacted="
        },
        "cookie": {
          "name": "Cookie",
          "value": ""
        }
      }
    },
    "withCredentials": false,
    "timeout": 0,
    "keepAlive": true,
    "decompressResponse": false,
    "requestId": "e5ad39dc-5c64-457a-8f6a-cc9206725dd3"
  },
  "response": {
    "headers": {
      "_headersMap": {
        "content-length": {
          "name": "content-length",
          "value": "220"
        },
        "content-type": {
          "name": "content-type",
          "value": "application/xml"
        },
        "date": {
          "name": "date",
          "value": "Mon, 10 Apr 2023 14:15:56 GMT"
        },
        "server": {
          "name": "server",
          "value": "Microsoft-HTTPAPI/2.0"
        },
        "x-ms-error-code": {
          "name": "x-ms-error-code",
          "value": "AccountIsDisabled"
        },
        "x-ms-request-id": {
          "name": "x-ms-request-id",
          "value": "8a838f22-701e-015a-2cb6-6b6496000000"
        }
      }
    },
    "request": {
      "streamResponseStatusCodes": {},
      "url": "https://demo.blob.core.windows.net/?comp=list&include=metadata",
      "method": "GET",
      "headers": {
        "_headersMap": {
          "x-ms-version": {
            "name": "x-ms-version",
            "value": "2021-10-04"
          },
          "accept": {
            "name": "Accept",
            "value": "application/xml"
          },
          "user-agent": {
            "name": "User-Agent",
            "value": "Microsoft Azure Storage Explorer/1.28.1 (win32) azsdk-js-storageblob/12.12.0 (NODE-VERSION v16.17.1; Windows_NT 10.0.22621)"
          },
          "x-ms-client-request-id": {
            "name": "x-ms-client-request-id",
            "value": "e5ad39dc-5c64-457a-8f6a-cc9206725dd3"
          },
          "x-ms-date": {
            "name": "x-ms-date",
            "value": "Mon, 10 Apr 2023 14:15:55 GMT"
          },
          "authorization": {
            "name": "Authorization",
            "value": "SharedKey demo:4ODLsvMXktkVWDP3VzF8slXawKVdXnsIQsqf7alCjSM="
          },
          "cookie": {
            "name": "Cookie",
            "value": ""
          }
        }
      },
      "withCredentials": false,
      "timeout": 0,
      "keepAlive": true,
      "decompressResponse": false,
      "requestId": "e5ad39dc-5c64-457a-8f6a-cc9206725dd3"
    },
    "status": 403,
    "bodyAsText": "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\nRequestId:8a838f22-701e-015a-2cb6-6b6496000000\nTime:2023-04-10T14:15:56.4575413Z</Message></Error>",
    "parsedBody": {
      "message": "The specified account is disabled.\nRequestId:8a838f22-701e-015a-2cb6-6b6496000000\nTime:2023-04-10T14:15:56.4575413Z",
      "code": "AccountIsDisabled"
    },
    "parsedHeaders": {
      "errorCode": "AccountIsDisabled",
      "content-length": "220",
      "content-type": "application/xml",
      "date": "Mon, 10 Apr 2023 14:15:56 GMT",
      "server": "Microsoft-HTTPAPI/2.0",
      "x-ms-request-id": "8a838f22-701e-015a-2cb6-6b6496000000"
    }
  },
  "details": {
    "errorCode": "AccountIsDisabled",
    "content-length": "220",
    "content-type": "application/xml",
    "date": "Mon, 10 Apr 2023 14:15:56 GMT",
    "server": "Microsoft-HTTPAPI/2.0",
    "x-ms-request-id": "8a838f22-701e-015a-2cb6-6b6496000000",
    "message": "The specified account is disabled.\nRequestId:8a838f22-701e-015a-2cb6-6b6496000000\nTime:2023-04-10T14:15:56.4575413Z",
    "code": "AccountIsDisabled"
  }
}

**Comment by JasonYeMSFT** [comment]
@narayansinght88 Your issue is different from the one in the original post. Your error message indicates that your storage account is disabled. Please open a new issue if you still need help.

@joesalvati68 Could you try resetting your login credential and see if it mitigates the problem? Try the steps we suggested in this issue https://github.com/microsoft/AzureStorageExplorer/issues/6384.

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. Please try the steps we suggested and open a new issue if you still have this problem.
