### ISSUE TITLE
Fail to upload/download/delete blobs for emulator blob containers

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6758]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230412.1
**Branch**: main
**Platform/OS**: Windows 10
**Architecture**: ia32
**Azurite Version** 3.23.0
**How Found**: From running test cases
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Install and run Azurite 3.23.0 -> Launch Storage Explorer.
2. Expand 'Emulator & Attached' -> Storage Accounts -> (Emulator - Default Ports) (Key) -> Blob Containers.
3. Create a blob container -> Try to upload one blob.
4. Check whether succeeds to upload the blob.

## Expected Experience ##
Succeed to upload the blob.

## Actual Experience ##
Fail to upload the blob.
![image](https://user-images.githubusercontent.com/41351993/231395484-dd22eacc-142e-4b93-a513-cd76f536d2a4.png)

Error details:
`{
  "message": "\"failed to perform copy command due to error: failed to resolve destination: lookup 127.0.0.1:10000: no such host\""
}`

## Additional Context ##
Here is the error when deleting one emulator blob.
![image](https://user-images.githubusercontent.com/41351993/231399574-bf2cff22-42f6-4ce4-bfbc-da09063d5872.png)

Error details:
`{
  "message": "\"failed to perform remove command due to error: failed to resolve source: lookup 127.0.0.1:10000: no such host\""
}`

**Comment by JasonYeMSFT** [comment]
Integrated AzCopy 10.18.1 which fixes this bug.

**Comment by v-xianya** [comment]
Verified this issue on the build 20230422.8. Fixed.
