### ISSUE TITLE
Can access smb share but not the blob containers

### ISSUE THREAD

**Issue by BuddyWalton** [microsoft/AzureStorageExplorer#6759]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.28.1

### Regression From

1.28.1

### Architecture

i86

### Storage Explorer Build Number

1.28.1

### Platform

Windows

### Bug Description

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://foundationcrmstoragedev.blob.core.windows.net/?comp=list&include=metadata failed, reason: connect ETIMEDOUT 10.12.18.29:443",
  "stack": "FetchError: request to https://foundationcrmstoragedev.blob.core.windows.net/?comp=list&include=metadata failed, reason: connect ETIMEDOUT 10.12.18.29:443\n    at ClientRequest.<anonymous> (C:\\Users\\waltowo\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1491:11)\n    at ClientRequest.emit (node:events:394:28)\n    at TLSSocket.socketErrorListener (node:_http_client:447:9)\n    at TLSSocket.emit (node:events:394:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "ETIMEDOUT",
  "code": "ETIMEDOUT"
}

### Steps to Reproduce

open storage account
click on containers

### Actual Experience

can't access blob only smb share

**Comment by MRayermannMSFT** [comment]
Can you please try using system proxy? https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview? Are you able to access your shares/their data from Azure Portal?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still facing this problem, we recommend opening a support ticket from the Azure portal. Alternatively you can open a new issue here.
