### ISSUE TITLE
Disable the 'Connect' button on 'Attach with Connection String' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#677]
Storage Explorer Version: 1.5.0
 Platform/OS Version: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
 Architecture: ia32/x64
 Build Number: 20180918.1
 Commit: 980c4e2f
 Regression From: Not a regression

#### Steps to Reproduce: ####
1. Open 'Connect' dialog -> Select ‘Use a connection string’ -> Click ‘Next’ button.
2. Check whether the 'Connect' button is disabled or not.

#### Expected Experience: ####
The 'Connect' button is disabled.
![capture1](https://user-images.githubusercontent.com/41351993/45741019-1bea1d00-bbe6-11e8-8d70-2e329f4f4849.PNG)

#### Actual Experience: ####
The 'Connect' button is enabled.

#### More Info: ####
There is no responding when clicking the 'Connect' button.

**Comment by craxal** [comment]
By design. You're supposed to click **Next** and confirm connection information.

**Comment by v-xianya** [comment]
It’s a right operation to click Next and confirm connection information, but in the current dialog Connect is disabled would be better.

**Comment by craxal** [comment]
Oh, I got the expected/actual turned around. I'll discuss with the team.

**Comment by v-xianya** [comment]
Verified this issue on build 20190626.4. It has been fixed. So we close it.
