### ISSUE TITLE
No traffic shows in Fiddler for the action 'Search From Here'

### ISSUE THREAD

**Issue by v-sunnsun** [microsoft/AzureStorageExplorer#6776]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230414.2
**Branch**: main
**Platform/OS**: Windows 10
**Architecture**: ia32
**How Found**: From running test cases
**Regression From**:  Previous release (1.28.0)

## Steps to Reproduce 

1. Install and launch Fiddler -> Launch Storage Explorer.
2. Click 'Edit -> Configure Proxy' -> Select 'Use app proxy settings' -> Set the URL: 'http://localhost' Port: '8888' -> Click 'OK'.
3. Right click 'Quick Access' node -> Click 'Search From Here'.
4. Check whether shows traffic in Fiddler.

## Expected Experience 
Show traffic in Fiddler.

## Actual Experience ##
No traffic shows in Fiddler.

## Additional Context ##

1. This issue also reproduces for storage account/blob container/file share/queue/disk resource types.
2. This issue also reproduces when selecting proxy 'Use environment variables' and 'Use system proxy (preview)'.

**Comment by MRayermannMSFT** [comment]
This is expected with the new tree view. Using search from here directly on a node previously would:
1. Get the node's path
2. Put the path in the search box
3. Run a query to find the node
4. When node is found, scope the tree to it

Step 3 is what generated traffic in fiddler. Now search from here directly on a node does:
1. Get the node's path
2. Put the path in the search box
3. Scope the tree to the node

So now the "Run a query to find the node" is gone, which means no Fiddler traffic.

That said, if you did something like this, then there should be fiddler traffic:
1. Run search from here directly on a node
2. Copy the path from the search box
3. Clear the search box
4. Past the path back into the box and hit enter

That will "Run a query to find the node", thus generating Fiddler traffic.
