### ISSUE TITLE
The highlight color for one selected entity is changed when moving the mouse off the entity

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6778]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230414.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test case
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Add one entity -> Select the entity.
3. Move the mouse off the entity.
4. Check whether the highlight color is not changed.

## Expected Experience ##
The highlight color is not changed.
![image](https://user-images.githubusercontent.com/41351993/231996932-546ec4b4-8b43-4e14-847e-90bde33dcf53.png)

## Actual Experience ##
The highlight color is changed.
![image](https://user-images.githubusercontent.com/41351993/231996639-e6789ff7-f317-440d-81aa-cdc033b62a0e.png)

## Additional Context ##
1. Here is the record:
![0414](https://user-images.githubusercontent.com/41351993/231998479-e0cb4f55-72ca-4d6c-b242-eef295237bb2.gif)
2. The highlight color is different when right clicking the entity in one same table.
![image](https://user-images.githubusercontent.com/41351993/232002808-48f17507-693b-4986-85e6-d15184323d22.png)

**Comment by craxal** [comment]
By design. Most applications use slightly different colors to distinguish selected items and interactive items under the mouse.

**Comment by v-xianya** [comment]
Hi @craxal 
1. For blobs/file shares/queues, there is no difference in highlight color whether the mouse leaves the selected item or not. Should Keep a consistent behavior with tables?
2. The color of the right-click highlight of an entity in the same table is different. can you take a look
![0417](https://user-images.githubusercontent.com/41351993/232368402-5c906995-aeac-422e-9c35-95e40b442e4f.gif)

**Comment by craxal** [comment]
@v-xianya In general, again, what you are seeing is by design. But I'll go into more detail.

1. Yes, they _should_ be consistent. But remember, the table explorer was completely redesigned. The resulting colors are a _refinement_ to what exists elsewhere. As we continue to modify other explorers, consistency will improve.
2. Can you be more specific about what inputs you make and what you observe? It's not clear from the previous GIF what the mouse and keyboard are doing. The brighter blue color comes from the mouse hover, and so it depends on what the mouse is hovering over. If you right-click to open the context menu and the color changes to a darker blue, it means the mouse is over the context menu, not the table. This is independent of the keyboard.

**Comment by v-xianya** [comment]
@craxal Thanks for the details.
`Can you be more specific about what inputs you make and what you observe?`

Repro steps:
1. Create one table -> Add two entities.
2. Move mouse to one entity -> Right click.
3. Move to another entity -> Right click.
4. Repeat the step2 and step3.
Actual: The highlight color is different for the same actions.

More info:
I am not moving mouse or running any other clicking after right clicking.

**Comment by craxal** [comment]
@v-xianya Thank you. Is it possible there's a tiny nudge to the mouse sometimes after the click? Even if that's not the case, it's all handled by CSS, so there's no way for us to "get it right" without possibly getting deep into tricks and workarounds. From what I can see, though, the colors still appear to be behaving as expected, so there's nothing to do here.

**Comment by v-xianya** [comment]
Hi @craxal 
Is it possible there's a tiny nudge to the mouse sometimes after the click? -> I don't think there is such a possibility😳
Anyway, thank you for the details！
