### ISSUE TITLE
The border overflows if hover over the last folder name on the address bar for ADLS Gen2 blobs/file shares

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6779]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230416.3
**Branch**: main
**Platform/OS**: Windows 10/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Click 'Upload -> Upload Files...'.
3. Select one file -> Type '1/2/3/4/5/' into 'Destination directory' field -> Click 'Upload'.
4. Navigate to the file path -> Resize the explorer.
5. Hover over the last folder name on the address bar.
6. Check whether the border doesn't overflow.

## Expected Experience ##
The border doesn't overflow.
![image](https://user-images.githubusercontent.com/41351993/232407640-f7657237-fc74-45a9-9388-ad03c2f9d0e7.png)

## Actual Experience ##
The border overflows.
![image](https://user-images.githubusercontent.com/41351993/232405961-7b87e40c-e149-4bd2-839f-f89de0b2b645.png)

## Additional Context ##
1. This issue reproduces for file shares.
2. This issue doesn't reproduce for regular blobs.
3. This issue doesn't reproduce on Linux Ubuntu 22.04.

**Comment by JasonYeMSFT** [comment]
The change is published in a major update to our ui components library which won't be in 1.30.0. Move to 1.31.0.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230627.1. Reproduce.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/fbba669a-bf77-452a-9ab5-3122268f4029)

**Comment by JasonYeMSFT** [comment]
The new ui components package is not used since it will break all the icons.

**Comment by MRayermannMSFT** [comment]
We're not to address this in the knockout version of the address bar component. Once file share is moved to React, please verify that this does not reproduce with the React address bar component.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230911.1. Fixed. So, we are going to close it.
