### ISSUE TITLE
An extra property ‘Primary Key’ shows for one attached account with SAS 

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#678]
Storage Explorer Version: 1.5.0
 Platform/OS Version: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
 Architecture: ia32/x64
 Build Number: 20180918.1
 Commit: 980c4e2f
 Regression From: Not a regression

#### Steps to Reproduce: ####
1. Attached one account with SAS.
Account name: 11yan
Connection String: SharedAccessSignature=sv=2018-03-28&ss=bfqt&srt=sco&sp=rl&st=2018-09-19T08%3A43%3A53Z&se=2018-09-20T08%3A43%3A53Z&sig=6%2FAdU%2FBzp6rBBISpwXfaTju37Hld3fCwp1ms4IRLUp8%3D;BlobEndpoint=https://11yan.blob.core.windows.net/;FileEndpoint=https://11yan.file.core.windows.net/;QueueEndpoint=https://11yan.queue.core.windows.net/;TableEndpoint=https://11yan.table.core.windows.net/;
2. Expand 'Local & Attached' -> 'Storage Accounts' -> Select the attached account.
3. Check the properties.

#### Expected Experience: ####
The property ‘Primary Key’ doesn’t show.
![capture2](https://user-images.githubusercontent.com/41351993/45741619-97000300-bbe7-11e8-8d0c-969a537cecdd.PNG)

#### Actual Experience: ####
An extra property ‘Primary Key’ shows.

#### More Info: ####
An extra property ‘Shared Access Signature’ shows for one attached account with Primary Key.
![capture3](https://user-images.githubusercontent.com/41351993/45743118-ef84cf80-bbea-11e8-856b-0b347d66519c.PNG)

**Comment by craxal** [comment]
Related to work we did to make account node types more standardized. We'd need to add some functionality to the property code to conditionally display. Won't fix.
