### ISSUE TITLE
Miss 'X' button next to the added metadata on 'Properties' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#679]
Storage Explorer Version: 1.5.0
 Platform/OS Version: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
 Architecture: ia32/x64
 Build Number: 20180918.1
 Commit: 980c4e2f
 Regression From: Previous release 1.4.1 

#### Steps to Reproduce: ####
1. Select one blob container which contains one blob at least.
2. Open one blob 'Properties' dialog -> Try to add metadata to it.
3. Check whether the 'X' button shows well or not.

#### Expected Experience: ####
The 'X' button shows well.

#### Actual Experience: ####
Miss 'X' button on the 'Properties' dialog.
![x](https://user-images.githubusercontent.com/34729022/45743011-bb111380-bbea-11e8-93d9-68331e1a8546.png)

**Comment by MRayermannMSFT** [comment]
This has been fixed.
