### ISSUE TITLE
Shared Access Signature Query String should not include '?', or it should be renamed

### ISSUE THREAD

**Issue by MattMcL4475** [microsoft/AzureStorageExplorer#6790]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.28.1

### Architecture

i86

### Storage Explorer Build Number

20230309.1

### Platform

Windows

### Bug Description

The `Get Shared Access Signature...` form has a technically incorrect label and/or it mistakenly includes a `?` in the query string.  The `?` is a delimiter and should be omitted; it is not technically part of the query string according to [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986).  This is likely leading to Azure user confusion.  Please see this thread:
https://github.com/MicrosoftDocs/azure-docs/issues/67749

### Steps to Reproduce

Right-click a storage account or container, and select `Get Shared Access Signature...`

### Actual Experience

The textbox is labeled `Query string:` and contains a string that begins with the question mark character `?`

### Expected Experience

The `?` is a delimiter and should be omitted; it is not technically part of the query string according to [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986).  Alternatively, if the `?` is included, it should not be labeled as a query string.  It is too ambiguous.

**Comment by MattMcL4475** [comment]
Please read this thread and my included analysis at the bottom: https://github.com/MicrosoftDocs/azure-docs/issues/67749

**Comment by MRayermannMSFT** [comment]
Discussions were had. We will:
1. Be changing the label from "Query string" to "SAS token"
2. The displaying of the token will no longer have the "?"
3. If you use the "Copy" button, a "?" will be prepended to the string, this is to avoid breaking user workflows.

**Comment by GregWoods** [comment]
>If you use the "Copy" button, a "?" will be prepended to the string, this is to avoid breaking user workflows.

So when I paste the SAS token into an Azure CLI command and it fails, and I then waste hours trying to figure it out what is going on, only to realise that somewhere, somebody's specific workflow needs a question mark prepending to the token, only this wasn't shown in the preview of what I thought I was copying. 

How, in any universe is this sensible?
