### ISSUE TITLE
Surface the error when generating SAS with incompatible parameters

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#6791]
For example, X permission can only be selected with version after 2019-10-10 as indicated in the error message. Make sure we surface the error message to help user troubleshoot. Currently we silently fail and show nothing in the generated SAS textarea.

**Comment by MRayermannMSFT** [comment]
I don't think this is something we need to worry about. I'd prefer to see this closed as won't fix.

**Comment by MRayermannMSFT** [comment]
Ignore my comment about won't fix.
