### ISSUE TITLE
The option 'Storage Accounts' is not selected on 'Search for resources of type' panel after restarting Storage Explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6793]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 202300418.4
**Branch**: main
**Platform/OS**: Windows 10
**Architecture**: ia32
**How Found**: From running test case
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Launch Storge Explorer -> Open the 'Search for resource of type' panel.
2. Select the option 'Storage Accounts'.
3. Restart Storage Explorer.
4. Open the 'Search for resource of type' panel.
5. Check whether the option 'Storage Accounts' is selected.

## Expected Experience ##
The option 'Storage Accounts' is selected.
![image](https://user-images.githubusercontent.com/41351993/232687037-b911d08f-135f-4c83-867a-6e8f7d08e480.png)

## Actual Experience ##
The option 'Storage Accounts' is not selected.
![image](https://user-images.githubusercontent.com/41351993/232686889-48dadd6b-5db6-4d80-b14a-365b178fb59f.png)

## Additional Context ##
This issue doesn't reproduce on Linux Ubuntu 22.04/MacOS Ventura 13.3.1 (Apple M1 Pro).

**Comment by MRayermannMSFT** [comment]
@v-xianya I believe this is to be expected. We now save the selected resource types. BUT, we only save them if you actually run a search with the types. So if you start Storage Explorer, and "Storage Accounts" is not selected, and then you select it, it will only be selected after restart if you run a search before restarting. @JasonYe sound correct?

**Comment by JasonYeMSFT** [comment]
What Matthew said is correct. I tried this on both Windows and Mac and they have the same behavior.

**Comment by v-xianya** [comment]
@MRayermannMSFT @JasonYeMSFT Thank you for the response!
