### ISSUE TITLE
Acknowledge error dialog pops up when trying to import a large .csv file

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6794]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230418.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04
**Architecture**: ia32/x64
**How Found**: From running test case
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Click 'Import'.
3. Select one large .csv file (contains 200x1million entities) -> Click 'Open'.
4. Check no error dialog pops up.

## Expected Experience ##
No error dialog pops up.

## Actual Experience ##
An error dialog pops up.
![image](https://user-images.githubusercontent.com/41351993/232688977-5ba7b9c9-b805-4c16-9f80-89fdc95c717d.png)

**Error info:**
Dialog window failed to acknowledge (19805357618500). The renderer process may be frozen.

## Additional Context ##
This issue doesn't reproduce on MacOS Ventura 13.3.1 (Apple M1 Pro).

**Comment by craxal** [comment]
@v-xianya How many columns does the CSV file have? Can you please share the file?

**Comment by v-xianya** [comment]
@craxal The file cannot be uploaded here because it is too large. I will share the file on teams.

**Comment by craxal** [comment]
@v-xianya Hmm...I'm not able to reproduce using the same file as of 20230419.1 (Windows 11, ia32). It does take a while (~30 seconds) for the properties to populate, but it succeeds for me. Does it still reproduce for you?

**Comment by v-xianya** [comment]
@craxal we verified this issue on rel build 20230420.4
1. This issue doesn't reproduce on Windows 11. and it takes 2 minutes for the properties to display.
2. This issue still reproduces on Windows 10.

**Comment by craxal** [comment]
@v-xianya How long does it take for the error dialog to show up? Is it immediate or does it take a while?

**Comment by v-xianya** [comment]
@craxal I will share the repro VM in teams.

**Comment by craxal** [comment]
@v-xianya I don't seem to be able to get into the machine with the credentials you provided.

**Comment by v-xianya** [comment]
Hi @craxal We verified this issue on the build 20230422.8, the error dialog disappears.
When importing .csv file table 200x200. there is a failed activity log. Could you help to take a look?
![image](https://user-images.githubusercontent.com/41351993/233822059-4ba23313-eb06-4a53-8061-547bb3fbdd89.png)

**Comment by craxal** [comment]
The same error occurs in 1.28.1. We've already verified not all rows get imported. I've narrowed down which batch is causing the problem, but the error from the server doesn't help much in pinpointing the error.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230602.2. Succeed to import a large .csv file.

**Comment by craxal** [comment]
@v-kellyluo We encountered that as well, but this is not related to this issue.
