### ISSUE TITLE
There is no search icon in 'Search' button on the 'Open Container by Name' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6796]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 202300418.4
**Branch**: main
**Platform/OS**: Windows 10
**Architecture**: ia32
**How Found**: From running test case
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Expand one storage account.
2. Right click 'Blob Containers' node.
3. Click 'Open Container by Name...'.
4. Check whether there is an icon in 'Search' button.

## Expected Experience ##
There is an icon in 'Search' button.
![image](https://user-images.githubusercontent.com/41351993/232695409-3c95d5fe-7887-407a-ade1-e2f59b47ee33.png)

## Actual Experience ##
There is no icon in 'Search' button.
![image](https://user-images.githubusercontent.com/41351993/232694812-d3c65465-b1ee-4535-bca0-fac9dedcf97d.png)

## Additional Context ##
1. This issue doesn't reproduce on Linux Ubuntu 22.04/MacOS Ventura 13.3.1 (Apple M1 Pro).
2. This issue also reproduces for ADLS Gen2 blob containers/file shares/queues/tables.
3. There are no loading icons when running a search.
![image](https://user-images.githubusercontent.com/41351993/232694995-c229f0d7-f5e0-49fa-bab8-cc4af0b63337.png)
4. This issue reproduces for 'Move Message' dialog.
![image](https://user-images.githubusercontent.com/41351993/232728302-18b28ded-f665-40f4-83b6-f5f992bb15d5.png)

**Comment by craxal** [comment]
I'm also seeing missing icons in the Connect dialog. This appears to be an issue with the icon binding. It's somehow adding a duplicate drive letter to the beginning of the path to the icon file.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230419.4. Fixed. So, we are going to close it.
