### ISSUE TITLE
  "code": "InvalidInput",   "statusCode": 400,

### ISSUE THREAD

**Issue by FocusAid** [microsoft/AzureStorageExplorer#6797]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.28.1

### Architecture

i86

### Storage Explorer Build Number

20230309.1

### Platform

macOS

### Bug Description

Impossible d’importer le lot commençant à l’entité avec la clé de partition 'FORMSUBS’ et la clé de ligne 'FORMSUBS1’ et se terminant par l’entité avec la clé de partition 'FORMSUBS’ et la clé de ligne 'FORMSUBS100'. 

### Steps to Reproduce

1. launch
2. Import a csv utf8
3. All fields validated
4. Element not imported

### Actual Experience

  "code": "InvalidInput",
  "statusCode": 400,
  "request": {
    "url": "https://csb10032000e5a7b49c.table.core.windows.net/$batch",
    "body": "--batch_e465f1ca-a81b-4976-b18d-d879a5ebbd6d\r\ncontent-type: multipart/mixed; boundary=changeset_4213004f-5a21-444c-86d3-3ad7f4e48af0\r\n\r\n\r\n--changeset_4213004f-5a21-444c-86d3-3ad7f4e48af0\r\ncontent-type: application/http\r\ncontent-transfer-encoding: binary\r\n\r\nPUT https://csb10032000e5a7b49c.table.core.windows.net/FORMSUBS(PartitionKey='FORMSUBS',RowKey='FORMSUBS1') HTTP/1.1\r\nContent-Type: application/json\r\nDataServiceVersion: 3.0\r\nAccept: application/json\r\n\r\n\r\n{\"PartitionKey\":\"FORMSUBS\",\"RowKey\":\"FORMSUBS1\",\"name\":\"Bleu\",\"name@odata.type\":\"Edm.String\",\"firstName\":\"Jean-Philippe\",\"firstName@odata.type\":\"Edm.String\",\"level\":\"Senior 7\",\"level@odata.type\":\"Edm.String\",\"Height\":\"175\",\"Height@odata.type\":\"Edm.Int32\",\"since\":\"C'est ma première année au CEA\",\"since@odata.type\":\"Edm.String\",\"next_continue\":\"Oui\",\"next_continue@odata.type\":\"Edm.String\",\"next_level\":\"Le même niveau\",\"next_level@odata.type\":\"Edm.String\",\"advice\":\"Non\",\"advice@odata.type\":\"Edm.String\",\"recommandation_rating\":\"7\",\"recommandation_rating@odata.type\":\"Edm.Int32\"}\r\n--changeset_4213004f-5a21-444c-86d3-3ad7f4e48af0\r\ncontent-type: application/http\r\ncontent-transfer-encoding: binary\r\n\r\nPUT 

### Expected Experience

it should be more interesting to have a direct issue and correction suggestion, because the 400 error doesn't tell me :
- for which field
- if it's coming from property fields or from row infos
- where is it located in the partition
- how to mainly correct it

**Comment by MRayermannMSFT** [comment]
@FocusAid the error comes straight from the server, so unfortunately we don't have much more information to expose to you regarding these types of errors. To narrow down what row/entity is causing the problem, you'll need to split up your data, import the smaller parts 1:1, to figure out which row/entity is causing the problem.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still experiencing this issue we recommend opening a support ticket from the Azure portal. Alternatively you can open a new issue here.
