### ISSUE TITLE
The last property column is not narrowed with its value

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6805]
**Storage Explorer Version**: 1.29.0
**Build Number**: 202300420.4
**Branch**: rel/1.29.0
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture**: ia32/x64/arm64
**How Found**: From running test case
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Add one entity.
3. Resize the last column.
4. Check whether the property column is narrowed with the value.

## Expected Experience ##
The property column is narrowed with the value.

## Actual Experience ##
The property column is not narrowed with the value.
![image](https://user-images.githubusercontent.com/41351993/233276287-8166c53a-0485-4636-956a-2c12b15671a1.png)

**Comment by craxal** [comment]
@v-xianya The text is just bleeding over the cell boundary. The other headers do this, too, but they're covered by the next header over. Column resizing is not blocked by this. I don't think it's worth the effort to try and fix.

**Comment by craxal** [comment]
Eh, changed my mind. It's an easy fix.

**Comment by v-xianya** [comment]
Verified this issue on the build 20230421.4. Fixed.
