### ISSUE TITLE
The 'Delimiter' in 'Import Entities' dialog uses comma instead of the system's regional list separator

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6806]
**Storage Explorer Version**: 1.29.0
**Build Number**: 202300420.4
**Branch**: rel/1.29.0
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture**: ia32/x64/arm64
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Change the 'List separator' to colon on Windows -> Save it. (Open 'Settings' -> Time & Language -> Language -> Administrative language settings - > Format -> Additional settings...')
2. Open Storage Explorer -> Expand one storage account -> Tables.
3. Open one table -> Click 'Import'.
4. Check whether the delimiter is colon on 'Import Entities' dialog.

## Expected Experience ##
The delimiter is colon.
![image](https://user-images.githubusercontent.com/41351993/233274093-af4c989c-8680-4bee-95fc-f5cc870ca22b.png)

## Actual Experience ##
The delimiter is comma.
![image](https://user-images.githubusercontent.com/41351993/233274019-bb194285-a67d-4bec-bfd7-22412698514b.png)

## Additional Context ##
This issue doesn't reproduce for 'Export Entities' dialog.

**Comment by MRayermannMSFT** [comment]
A comment on this, do we really want import to use the system delimiter? Why not use the delimiter that the file appears to be using?

**Comment by craxal** [comment]
@MRayermannMSFT

* Ideally, yes, we would like to detect the delimiter, but this is not trivial. There's currently no quick, easy, sure-fire way to determine the delimiter without human input. Files with a high degree of homogenous data would have roughly equal numbers of commas or semi-colons, making it very difficult to determine programmatically which is the proper delimiter. A heuristic approach may be more appropriate. If we want, we can spend some more time investigating the matter. But the bottom line is finding a decent solution was too costly for a relatively small feature and for everything else we're trying to accomplish for the 1.29.0 release.
* The dialog already does this. A subscription to both the file path and the delimiter kicks off a new parse every time there's a change.

**Comment by v-xianya** [comment]
Verified this issue on the build 20230421.4. Fixed.
