### ISSUE TITLE
The action 'Reset Columns' only works at the first time for resetting columns order/size

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6808]
**Storage Explorer Version**: 1.29.0
**Build Number**: 20230420.4
**Branch**: rel/1.29.0
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3 (Apple M1 Pro)
**Architecture**: ia32/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Add one entity.
3. Reorder the columns by dragging columns.
4. Right click one column or entity -> Click 'Reset Columns'.
5. The columns are reset -> Reorder the columns again.
6. Right click one column or entity -> Click 'Reset Columns'.
7. Check whether the property columns are reset.

## Expected Experience ##
The property columns are reset.

## Actual Experience ##
The property columns are not reset.

## Additional Context ##
This issue also reproduces against resetting the size of columns.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230421.4. Fixed.
