### ISSUE TITLE
Show Queue metadata

### ISSUE THREAD

**Issue by csalgo70** [microsoft/AzureStorageExplorer#681]
**Storage Explorer Version**:  1.4.1 
**Platform/OS Version**: Windows 10
**Architecture**: ia32
**Regression From**: NA

#### Expected Experience: ####
Currently there seems to be no option to view a Queue's metadata. Would be nice to show that under properties section when the queue is selected.

**Comment by JasonYeMSFT** [comment]
Related to #2664

**Comment by MRayermannMSFT** [comment]
Duplicate of 2664
