### ISSUE TITLE
Can't access file shares with SAS

### ISSUE THREAD

**Issue by vertices86** [microsoft/AzureStorageExplorer#6812]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.28.1

### Architecture

x64

### Storage Explorer Build Number

20230309.1

### Platform

All

### OS Version

macOS 

### Bug Description

I have a file share in a storage account that has no network restrictions. I can access the share with storage explorer ONLY doing this:

1. Hitting "Connect" up top in the portal, grabbing the key out of that string, and adding the entire account this way:
2. Add "Storage account or service"
3. Account name and key
4. Enter account name and key
5. Connect

What I want to do is make a SAS string to give to someone. But no matter what I select on the SAS creation screen, even selecting everything and making sure it the dates go a month in each direction it fails. I can add the account or file share using the strings, but when I try to access the file shares I get:

Unable to retrieve child resources.

Details:

{

"name": "RestError",

"message": "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:97366ffd-d01a-0081-5fa0-734024000000\nTime:2023-04-20T15:57:27.1467961Z",

"stack": "RestError: Serv

I have tried from Windows and macOS with the same result. Both work fine using the method I outlined above, so it's not network related. I would love to be able to make a read only connection string that works.

### Steps to Reproduce

1. Create SAS string via the portal
2. Add as many or as little permissions to the SAS string
3. Connect
4. Try to access file share and it fails with this error.

### Actual Experience

I get an error:
Unable to retrieve child resources.

Details:

{

"name": "RestError",

"message": "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:97366ffd-d01a-0081-5fa0-734024000000\nTime:2023-04-20T15:57:27.1467961Z",

"stack": "RestError: Serv

### Expected Experience

I can access a file share.

**Comment by JasonYeMSFT** [comment]
@vertices86 Could you elaborate on how you create the SAS from Portal and which options did you select in Storage Explorer's connect dialog when attempting to connect to it? I tried connecting to an account SAS connection string and a  file share SAS URL from Portal and both work as expected.

**Comment by vertices86** [comment]
Sure. Thank you. I have tried both of these configurations and neither work and both generate the same errors. 
This was my intent:
![image](https://user-images.githubusercontent.com/3171981/233490036-f8dccee3-4ac9-402f-a324-a4a00150f7cf.png)

After that wouldn't work I tried this as a test:
![image](https://user-images.githubusercontent.com/3171981/233489844-55c286dd-117c-4523-8ef5-31646db09b8e.png)


On the "What kind of Azure resource do you want to connect to?" screen I have tried adding the "Storage account or service" with the Connection String from both methods above, and I have also tried adding instead a "File Share" on the same screen and using the File service SAS URL from each of the above. 

Everything I do has some sort of error. It connects, shows me a list of Blob Containers, File Shares, Queues, and Tables if I use the Connection String with the account, but clicking on any of them results in the "Unable to retrieve child objects" error. Or if instead I just add the file share alone, with the File service SAS URL, when I try to add it gives me an error "The URL is missing a path to the resource.", but if I append /filesharename to the fqdn of the storage account, it lets me add it, but I get a "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. Req" error when I try to access it.

For that last one, to be specific, using a randomized name, the File share SAS URL might be https://1234567890.file.core.windows.net/?sv=2021-12-02&ss=bfqt&srt but I change that to:
https://1234567890.file.core.windows.net/servers/?sv=2021-12-02&ss=bfqt&srt

I don't know if that's right or not. I'd be fine if I could just connect the account level instead of the file share, and access the file share from the account level. Like I said, that File Share method may be wrong, but it's not clear how to make it work since copying direct from portal doesn't work.

Using the "Storage account or service" and using the Connection String does work copying from the portal with no manipulation, but I get the unable to retrieve child objects error when doing that.

**Comment by JasonYeMSFT** [comment]
All your approaches should have worked but I believe they failed due to the same reason. One of the potential cause I can think of is that your copied url contains invisible characters which would disrupt the SAS token validation. However, I am not sure because I have always been using the copy button on Portal but I never encountered this issue.

Could you try connecting using your intended approach and share the summary page of the connect dialog with us? It should look like this
<img width="920" alt="image" src="https://user-images.githubusercontent.com/39359541/233497151-1e53ff98-6faa-47a2-b519-8aa62bbdaa3a.png">

To protect your private data, please redact the display name, your storage account name and the "sig" query parameter in the SAS token. Keep everything else as is.

**Comment by vertices86** [comment]
I just realized I misspoke a bit. If I use my intended approach, image 1 above, then the Connection String doesn't work when trying to add it as a "Storage account or service". It's odd as when I uncheck "Blob" up top, the Connection String at the bottom after hitting genrate again doesn't remove blob, queues, tables, etc. I would think unchecking those up top would update the string but it does't, so I have to manually remove those otherwise when adding the Connection String I get an error in Storage Explorer

> The connection string has a blob service endpoint, but the SAS token does not grant blob service access. Remove the blob endpoint or use an account SAS with at least blob service access ('ss=b').

So if I remove the bits in the string regarding blobs, queues, tables, leaving only files I have:
FileEndpoint=https://1234567890.file.core.windows.net/;SharedAccessSignature=sv=2021-12-02&ss=f&srt=sco&sp=rl&se=2023-12-02T00:50:04Z&st=2023-03-01T16:50:04Z&spr=https&sig=xxxxxxxxxxxxxxxxxxxxxxxxx

That connection string connects and this is what it looks like:
![image](https://user-images.githubusercontent.com/3171981/233502506-ff98f161-1f20-425b-98fc-60000fbe5064.png)

However it has the same error, "Unable to retrieve child resources."

Still working with Image 1 above, only Files selected, read/list, but instead adding as a file share with the File service SAS URL with /servers (the name of the share) added:

![image](https://user-images.githubusercontent.com/3171981/233503050-70c57b55-5c9f-4277-babd-5d4613d615ab.png)

That also connects but when accessing gives error: "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:4f2b757f-a01"

So now switching to Image 2 above, my test with all boxes checked. I can copy the Connect String directly from the portal using the copy button. I add a "Storage account or service"
![image](https://user-images.githubusercontent.com/3171981/233503445-3264e3bc-a139-41f2-be43-ea0d9f8ba0c5.png)

That connects. But same thing "Unable to retrieve child resources." when trying to access any resources.

If I grabjust the File service SAS URL from this one. Add File Share: 
![image](https://user-images.githubusercontent.com/3171981/233503840-537b70c8-6bf1-4129-bf8b-ad5681aeab54.png)

That results again in the "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:4f2b757f-a01" error.

Thanks for the help!

**Comment by vertices86** [comment]
So today, all of the same stuff magically works for me. I have no issues. So I generated a new SAS, tested it, it works fine. Gave it to someone else and they have the same issue of unable to retrieve child resources. This shouldn't be so hard.

**Comment by vertices86** [comment]
According to them, after trying multiple times, detaching, reattaching, it eventually worked. idk.
