### ISSUE TITLE
The CSV file is not correctly parsed in preview on MacOS/Linux

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6814]
**Storage Explorer Version**: 1.29.0
**Build Number**: 20230421.4
**Branch**: rel/1.29.0
**Platform/OS**: Linux Ubuntu 22.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture**: x64/arm64
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one csv file (make sure its content type is text/csv).
3. Right click the file -> Click 'Preview'.
4. Check if the file is correctly previewed as a table.

## Expected Experience ##
The file is correctly previewed as a table.
![image](https://user-images.githubusercontent.com/41351993/233557754-50c55abb-44a8-4aae-8e62-7e7e3e7ba3e5.png)

## Actual Experience ##
The file is not correctly previewed as a table.
![image](https://user-images.githubusercontent.com/41351993/233558404-bd650477-c5b6-4451-ac0b-70736dafd8cc.png)

## Additional Context ##

1. This issue reproduces for ADLS Gen2 blobs/file shares.
2. This issue doesn't reproduce on Windows 10.

**Comment by craxal** [comment]
I am adding a control to the preview panel that lets the user choose the delimiter to use when parsing the CSV. This is needed, because the CSV may use a delimiter different than what the user's system list separator is, and we don't currently have a good way of guessing what it might be.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230422.8. Fixed.
