### ISSUE TITLE
New query builder clause should have '=' operator

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6815]
**Storage Explorer Version**: 1.29.0
**Build Number**: 20230421.4
**Branch**: rel/1.29.0
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture**: ia32/x64/arm64
**How Found**: From running test case
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Add one entity.
3. Click 'Query' -> Click 'Add new clause'.
4. Check whether the default operator is '='.

## Expected Experience ##
The default operator is '='.
![image](https://user-images.githubusercontent.com/41351993/233582184-baaa8791-0dbd-4aed-86eb-5e5485452a95.png)

## Actual Experience ##
The default operator is '>='.
![image](https://user-images.githubusercontent.com/41351993/233580316-bc7fa093-9752-427b-a576-6ade40b99b99.png)

## Additional Context ##
The default operator is '=' if reopen the table then click 'Query'.
![image](https://user-images.githubusercontent.com/41351993/233581964-1b340205-a545-4b90-bf96-897ce92c8f2e.png)

**Comment by craxal** [comment]
This is more for consistency with the previous query builder implementation than an actual bug.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230422.8. Fixed.
