### ISSUE TITLE
The tree view shows blank if click the 'Search' icon on the 'Search for resources' box after running the action 'Search From Here'

### ISSUE THREAD

**Issue by v-sunnsun** [microsoft/AzureStorageExplorer#6816]
**Storage Explorer Version**: 1.29.0
**Build Number**: 20230421.4
**Branch**: rel/1.29.0
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3 (Apple M1 Pro)
**Architecture**: ia32/x64/arm64
**How Found**: From running test cases
**Regression From**:  Previous release (1.28.1)

## Steps to Reproduce 

1. Select and right click one storage account -> Click 'Search From Here'.
2. Click the 'Search' icon on the 'Search for resources' box.
3. Check whether the tree view shows normally.

## Expected Experience 
The tree view shows normally.
![image](https://user-images.githubusercontent.com/122582307/233565388-ea1ee503-1042-4b71-a981-f22999fae864.png)

## Actual Experience ##
The tree view shows blank.
![image](https://user-images.githubusercontent.com/122582307/233571788-6aa5cbb4-fbce-4849-989c-1a15cb3d1998.png)

## Additional Context ##

1. This issue also reproduces for storage account/blob container/file share/queue/table resource types.
2. After 5 seconds, the tree view shows normally. (After clicking the 'Search' icon on 1.28.1, the storage account is not expanded, and it is expanded in 1.29.0.)
![image](https://user-images.githubusercontent.com/122582307/233579153-cbb525cd-1be4-4c11-8138-4f1aee21680a.png)

**Comment by MRayermannMSFT** [comment]
Will fix for 1.30.0. The blank is just what is shown while the tree is finding the node to scope to.

**Comment by MRayermannMSFT** [comment]
Going to won't fix this for now. The state management for the tree is pretty solid right now. Don't want to introduce any regressions for tying to fix *this* bug. Just not worth it. If a user complains we can look into it.
