### ISSUE TITLE
Ctrl+R doesn't take effect in table explorer if there is no selected entity

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6819]
**Storage Explorer Version**: 1.29.0
**Build Number**: 20230422.8
**Branch**: rel/1.29.0
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test case
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Open one table -> Press Ctrl+R.
3. Check whether the table explorer is refreshed.

## Expected Experience ##
The table explorer is refreshed.

## Actual Experience ##
The table explorer is not refreshed.

## Additional Context ##
This issue doesn't reproduce when clicking 'Refresh'.

**Comment by craxal** [comment]
@v-xianya Likely by design. Is focus in the table itself? If not, a refresh is not expected to happen. This is in line with making sure actions like Ctrl+A only work when the table has focus (see #6775).

**Comment by v-xianya** [comment]
Verified this issue on the build 20230425.6. Fixed. So we are going to close it.
