### ISSUE TITLE
'Secondary Key' property doesn't show in Properties for an account attached with Secondary Key

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#682]
Storage Explorer Version: 1.5.0
 Platform/OS Version: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
 Architecture: ia32/x64
 Build Number: 20180919.1
 Commit: a1c3df52
 Regression From: Not a regression

#### Steps to Reproduce: ####
1. Attached one account with Secondary Key.
Account name:v1county
Secondary Key:
gHTzQVTLTuZcpfdvdn7pV5J7GwWW1xArXuQ8qs545R6DKfc2BhVWJ3F8mzP4pzt8lbKWc2LUOWTV5pLfEEXXuA==
2. Expand ‘Local & Attached’ -> ‘Storage Accounts’ -> Select the attached account.
3. Check the properties.

#### Expected Experience: ####
The property ‘Secondary Key’ shows.

#### Actual Experience: ####
The property ‘Secondary Key’ doesn’t show.

#### More Info: ####
The property ‘Secondary Key’ doesn’t show but a property ‘Primary Key’ shows.
![capture1](https://user-images.githubusercontent.com/41351993/45805077-566abd00-bcad-11e8-84fe-c36cfacaf540.PNG)

**Comment by craxal** [comment]
Won't fix. It's arguably unimportant to differentiate which key is used to connect.
