### ISSUE TITLE
Only lowercase boolean values are accepted when importing CSV

### ISSUE THREAD

**Issue by francotiveron** [microsoft/AzureStorageExplorer#6821]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.28.1

### Regression From

1.27.0

### Architecture

x64

### Storage Explorer Build Number

20230309

### Platform

Windows

### OS Version

Windows 10

### Bug Description

TRUE/FALSE in boolean column cannot be imported from CSV

### Steps to Reproduce

1. Export a table with a Boolean column (storage explorer shows lowercase 'true'/'false'
2. Open in excel (the boolean column shows uppercase 'TRUE'/'FALSE'
3. Save the file so that the uppercase booleans are written to the disk
4. Import the csv

### Actual Experience

Import fails

### Expected Experience

Import should succeed

**Comment by MRayermannMSFT** [comment]
@craxal can you figure out if this is indeed a regression? If so let's see how much risk will come from adding it to 1.29.

**Comment by craxal** [comment]
@francotiveron I am not able to reproduce this in 1.28.1 or in our dev builds. The import succeeds as expected. Can you share a small file or data sample that reproduces the error? Can you also share the error message you get along with any log files?

**Comment by francotiveron** [comment]
[Market1.csv](https://github.com/microsoft/AzureStorageExplorer/files/11315184/Market1.csv)
Unable to import batch beginning at entity with partition key 'Asset' and row key 'AP' and ending at entity with partition key 'Asset' and row key 'AP'.

Error details:

{
  "name": "RestError",
  "message": "0:An error occurred while processing this request.\nRequestId:229d755a-eaae-41a2-a43f-5a0351fb5b0c\nTime:2023-04-24T22:56:32.679Z",
  "stack": "RestError: 0:An error occurred while processing this request.\nRequestId:229d755a-eaae-41a2-a43f-5a0351fb5b0c\nTime:2023-04-24T22:56:32.679Z\n    at handleBodyError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-table-extension\\dist\\src\\Jobs\\TableJobsHandler.js:2:273578)\n    at C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-table-extension\\dist\\src\\Jobs\\TableJobsHandler.js:2:272755\n    at Array.map (<anonymous>)\n    at parseTransactionResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-table-extension\\dist\\src\\Jobs\\TableJobsHandler.js:2:272423)\n    at C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-table-extension\\dist\\src\\Jobs\\TableJobsHandler.js:2:273069\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Object.withSpan (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-table-extension\\dist\\src\\Jobs\\TableJobsHandler.js:2:186387)\n    at async #t (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-table-extension\\dist\\src\\Jobs\\TableJobsHandler.js:2:3332)\n    at async TableClient.runOperation (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-table-extension\\dist\\src\\Jobs\\TableJobsHandler.js:2:352855)\n    at async ImportBatchWithTypesState.importEntities (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-table-extension\\dist\\src\\Jobs\\TableJobsHandler.js:2:31674)",
  "code": "InvalidInput",
  "statusCode": 400,
  "request": {
    "url": "http://127.0.0.1:10002/devstoreaccount1/$batch",
    "body": "--batch_cbd123f5-b4ba-4c59-a6fe-06daa43c97a8\r\ncontent-type: multipart/mixed; boundary=changeset_9d22c39b-00ba-4f95-83ae-26627d7b8c64\r\n\r\n\r\n--changeset_9d22c39b-00ba-4f95-83ae-26627d7b8c64\r\ncontent-type: application/http\r\ncontent-transfer-encoding: binary\r\n\r\nPATCH http://127.0.0.1:10002/devstoreaccount1/Market(PartitionKey='Asset',RowKey='AP') HTTP/1.1\r\nContent-Type: application/json\r\nDataServiceVersion: 3.0\r\nAccept: application/json\r\n\r\n\r\n{\"PartitionKey\":\"Asset\",\"RowKey\":\"AP\",\"Active\":\"FALSE\",\"Active@odata.type\":\"Edm.Boolean\",\"SessionStart\":\"18:00,America/New_York\",\"SessionStart@odata.type\":\"Edm.String\",\"Reference\":\"\",\"Reference@odata.type\":\"Edm.String\"}\r\n--changeset_9d22c39b-00ba-4f95-83ae-26627d7b8c64--\r\n--batch_cbd123f5-b4ba-4c59-a6fe-06daa43c97a8--\r\n",
    "headers": {
      "accept": "application/json",
      "x-ms-version": "2019-02-02",
      "dataserviceversion": "3.0;",
      "maxdataserviceversion": "3.0;NetFx",
      "content-type": "multipart/mixed; boundary=batch_cbd123f5-b4ba-4c59-a6fe-06daa43c97a8",
      "accept-charset": "UTF-8",
      "connection": "Keep-Alive",
      "accept-encoding": "gzip,deflate",
      "user-agent": "Microsoft Azure Storage Explorer/1.28.1 (win32) azsdk-js-data-tables/13.1.2 core-rest-pipeline/1.9.0 Node/v16.17.1 OS/(ia32-Windows_NT-10.0.19044)",
      "x-ms-client-request-id": "a6b8299f-1d68-4fc9-88d5-5148a60524fb",
      "x-ms-date": "Mon, 24 Apr 2023 22:56:32 GMT",
      "content-length": "762",
      "authorization": "Signed SharedKeyLite Redacted="
    },
    "method": "POST",
    "timeout": 0,
    "disableKeepAlive": false,
    "withCredentials": false,
    "tracingOptions": {
      "tracingContext": {
        "_contextMap": {}
      }
    },
    "requestId": "a6b8299f-1d68-4fc9-88d5-5148a60524fb",
    "allowInsecureConnection": true,
    "enableBrowserStreams": false
  },
  "response": {
    "status": 202,
    "headers": {
      "server": "Azurite-Table/3.23.0",
      "content-type": "multipart/mixed; boundary=batchresponse_cbd123f5-b4ba-4c59-a6fe-06daa43c97a8",
      "x-ms-request-id": "229d755a-eaae-41a2-a43f-5a0351fb5b0c",
      "x-ms-version": "2022-11-02",
      "date": "Mon, 24 Apr 2023 22:56:32 GMT",
      "connection": "keep-alive",
      "keep-alive": "timeout=5",
      "transfer-encoding": "chunked"
    },
    "request": {
      "url": "http://127.0.0.1:10002/devstoreaccount1/$batch",
      "body": "--batch_cbd123f5-b4ba-4c59-a6fe-06daa43c97a8\r\ncontent-type: multipart/mixed; boundary=changeset_9d22c39b-00ba-4f95-83ae-26627d7b8c64\r\n\r\n\r\n--changeset_9d22c39b-00ba-4f95-83ae-26627d7b8c64\r\ncontent-type: application/http\r\ncontent-transfer-encoding: binary\r\n\r\nPATCH http://127.0.0.1:10002/devstoreaccount1/Market(PartitionKey='Asset',RowKey='AP') HTTP/1.1\r\nContent-Type: application/json\r\nDataServiceVersion: 3.0\r\nAccept: application/json\r\n\r\n\r\n{\"PartitionKey\":\"Asset\",\"RowKey\":\"AP\",\"Active\":\"FALSE\",\"Active@odata.type\":\"Edm.Boolean\",\"SessionStart\":\"18:00,America/New_York\",\"SessionStart@odata.type\":\"Edm.String\",\"Reference\":\"\",\"Reference@odata.type\":\"Edm.String\"}\r\n--changeset_9d22c39b-00ba-4f95-83ae-26627d7b8c64--\r\n--batch_cbd123f5-b4ba-4c59-a6fe-06daa43c97a8--\r\n",
      "headers": {
        "accept": "application/json",
        "x-ms-version": "2019-02-02",
        "dataserviceversion": "3.0;",
        "maxdataserviceversion": "3.0;NetFx",
        "content-type": "multipart/mixed; boundary=batch_cbd123f5-b4ba-4c59-a6fe-06daa43c97a8",
        "accept-charset": "UTF-8",
        "connection": "Keep-Alive",
        "accept-encoding": "gzip,deflate",
        "user-agent": "Microsoft Azure Storage Explorer/1.28.1 (win32) azsdk-js-data-tables/13.1.2 core-rest-pipeline/1.9.0 Node/v16.17.1 OS/(ia32-Windows_NT-10.0.19044)",
        "x-ms-client-request-id": "a6b8299f-1d68-4fc9-88d5-5148a60524fb",
        "x-ms-date": "Mon, 24 Apr 2023 22:56:32 GMT",
        "content-length": "762",
        "authorization": "SharedKeyLite devstoreaccount1:fr6TA0aM2Nvkh9AecVOSEyKs0i7g4K2+2fEyPYx1GcI="
      },
      "method": "POST",
      "timeout": 0,
      "disableKeepAlive": false,
      "withCredentials": false,
      "tracingOptions": {
        "tracingContext": {
          "_contextMap": {}
        }
      },
      "requestId": "a6b8299f-1d68-4fc9-88d5-5148a60524fb",
      "allowInsecureConnection": true,
      "enableBrowserStreams": false
    },
    "bodyAsText": "--batchresponse_cbd123f5-b4ba-4c59-a6fe-06daa43c97a8\r\nContent-Type: multipart/mixed; boundary=changesetresponse_9d22c39b-00ba-4f95-83ae-26627d7b8c64\r\n\r\n--changesetresponse_9d22c39b-00ba-4f95-83ae-26627d7b8c64\r\nContent-Type: application/http\r\nContent-Transfer-Encoding: binary\r\n\r\nHTTP/1.1 400 Bad Request\r\nContent-ID: 1\r\nDataServiceVersion: 3.0;\r\nContent-Type: application/json;odata=minimalmetadata;charset=utf-8\r\n\r\n{\"odata.error\":{\"code\":\"InvalidInput\",\"message\":{\"lang\":\"en-US\",\"value\":\"0:An error occurred while processing this request.\\nRequestId:229d755a-eaae-41a2-a43f-5a0351fb5b0c\\nTime:2023-04-24T22:56:32.679Z\"}}}\r\n--changesetresponse_9d22c39b-00ba-4f95-83ae-26627d7b8c64--\r\n--batchresponse_cbd123f5-b4ba-4c59-a6fe-06daa43c97a8--\r\n"
  }
}

**Comment by craxal** [comment]
@francotiveron Thanks for sharing. Still not able to reproduce on my end. Since the error message isn't very helpful, let me see if I can get in touch with someone on the Azure end and demystify some things.

**Comment by francotiveron** [comment]
@craxal 
Don't know if is relevant... backend is azurite. With the old storage emulator this wasn't a problem

**Comment by craxal** [comment]
Ah, that is relevant. That would therefore, be a bug with Azurite.

**Comment by craxal** [comment]
I have created an issue for you: https://github.com/Azure/Azurite/issues/1947.
