### ISSUE TITLE
The columns order is incorrect after executing 'Reorder Columns Based on Schema' for one entity which has a non-empty custom property

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6822]
**Storage Explorer Version**: 1.29.0
**Build Number**: 20230424.2
**Branch**: rel/1.29.0
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture**: ia32/x64/arm64
**How Found**: ad-hoc testing
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Expand a storage account -> Tables.
2. Create a table -> Add one entity with a custom property.
3. Right click the entity -> Click 'Reorder Columns Based on Schema'.
4. Check whether the columns order is correct.

## Expected Experience ##
The columns order is correct.
![image](https://user-images.githubusercontent.com/41351993/233920227-37fa28b9-3767-42cb-8000-77d43e4a54c3.png)

## Actual Experience ##
The columns order is incorrect.
![image](https://user-images.githubusercontent.com/41351993/233920384-d0b61a3c-c9af-4ac9-8dac-14081331c90f.png)

**Comment by v-xianya** [comment]
@craxal Thanks for the response! One issue needs your confirmation.
If I reorder one custom property column, then click 'Add'. The Add Entity dialog as below.
This issue doesn't reproduces for Edit/Duplicate entity. 
Do we need to pay attention to this?
![image](https://user-images.githubusercontent.com/41351993/234160034-697ec255-50d0-4c58-bb95-47592778523a.png)

**Comment by craxal** [comment]
No, you don't need to pay attention to that. Though, we'll look into it.
