### ISSUE TITLE
The preview tab cannot be closed by clicking 'x' when there is a scroll bar for the preview tab

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6823]
**Storage Explorer Version:** 1.29.0
**Build Number:** 20230424.2
**Branch:** rel/1.29.0
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture:** ia32/x64/arm64
**How Found:** Ad-hoc testing
**Regression From:** Previous release (1.28.1)

## Steps to Reproduce ##

1. Expand a storage account -> Blob Containers.
2. Create a blob container -> Upload a blob.
3. Right click the blob -> Click 'Preview'.
4. Narrow the preview tab horizontally until there is a scroll bar.
5. Click 'x' on the preview tab.
6. Check whether the preview tab is closed.

## Expected Experience ##
The preview tab is closed.

## Actual Experience ##
The preview tab is not closed.

## Additional Context ##

1. This issue doesn't reproduce for one split service tab.
2. This issue doesn't reproduce when there is more than one tab in the split view.
3. Here is the record:
![pre](https://user-images.githubusercontent.com/87792676/233928716-b2886b88-9d7f-4a44-b72b-7584c06e246a.gif)

**Comment by v-kellyluo** [comment]
@JasonYeMSFT ,verified this issue on the build 20230425.6, the preview tab can be closed by clicking 'x'.
But one thing is different from before, now we must move the scroll bar then click 'x' rather than click the tab then click 'x', do we need to notice that?
![verify](https://user-images.githubusercontent.com/87792676/234157939-8935f603-6711-4b53-9850-1ca7a935914f.gif)

**Comment by JasonYeMSFT** [comment]
@v-kellyluo the new behavior is expected. You will need to find the close button and click on it to close the tab.
