### ISSUE TITLE
The previewed tabular file shows incorrectly when resizing one column

### ISSUE THREAD

**Issue by v-sunnsun** [microsoft/AzureStorageExplorer#6824]
**Storage Explorer Version**: 1.29.0
**Build Number**: 20230424.2
**Branch**: rel/1.29.0
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture**:  ia32/x64/arm64
**How Found**: Ad-hoc testing
**Regression From**:  Not a regression

## Steps to Reproduce 

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one csv file (make sure its content type is text/csv).
3. Right click the blob -> Click 'Preview'.
4. Resize one column.
5. Check whether the preview tab shows normally.

## Expected Experience 
The preview tab shows normally.

## Actual Experience ##
The preview tab shows incorrectly.

## Additional Context ##

1. Here is the test file:
[table.csv](https://github.com/microsoft/AzureStorageExplorer/files/11308913/table.csv)
2. Here is the record:

![record](https://user-images.githubusercontent.com/122582307/233960173-3e64e25b-2a97-4833-940e-37755510df1b.gif)

**Comment by craxal** [comment]
I think it's just because I forgot to put a minimum for the column size.

**Comment by v-sunnsun** [comment]
Verified this issue on the build 20230425.6. Fixed. So we are going to close it.
