### ISSUE TITLE
Feature wish: Update cache

### ISSUE THREAD

**Issue by flixius** [microsoft/AzureStorageExplorer#683]
When I modify a file and replace it in the AZ Storage Explorer, my Azure CDN is serving the cached version. 

Then I have to go to my CDN Settings and purge the folder to trigger an update of the cache. Then I have to wait for several hours until the files are updated.
I know that i can define the cache expire time when I upload files in C#. The expire time of 7 days is good for me unless I want to *modify* as css-file. 

It would be very useful when it would be possible to trigger a cache update of the modified file directly in the AZ Storage Explorer.

**Comment by MRayermannMSFT** [comment]
Duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/334
