### ISSUE TITLE
The columns order is not reset after reopening the table

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6836]
**Storage Explorer Version**: 1.29.0
**Build Number**: 20230425.6
**Branch**: rel/1.29.0
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture**: ia32/x64/arm64
**How Found**: ad-hoc testing
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Expand a storage account -> Tables.
2. Create a table -> Add one entity.
3. Reorder the column.
4. Close the table explorer -> Reopen it.
5. Check whether the columns order is reset.

## Expected Experience ##
The columns order is reset.
![image](https://user-images.githubusercontent.com/41351993/234216174-8e0dcfeb-6e66-4a09-aa62-146f3681827c.png)

## Actual Experience ##
The columns order is not reset.
![image](https://user-images.githubusercontent.com/41351993/234216092-3e086b4f-dd18-47b0-aa5b-5682163e8fe0.png)

## Additional Context ##
This issue also reproduces when resizing columns.

**Comment by craxal** [comment]
@v-xianya This is by design. Remembering the state of the table columns is a new feature. Please keep in mind that only the last 100 tables are saved, so if you open more than 100 tables, state for the earliest tables will be reset.
