### ISSUE TITLE
Not all entities on the current page are selected if sort entities by one column then click 'Select All/Select All in Page'

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6837]
**Storage Explorer Version:** 1.29.0
**Build Number:** 20230425.6
**Branch:** rel/1.29.0
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture:** ia32/x64/arm64
**How Found:** Ad-hoc testing
**Regression From:** Previous release (1.28.1)

## Steps to Reproduce ##

1. Expand a storage account -> Tables.
2. Create a table -> Import more than 100 entities.
3. Sort the table by one column -> Click 'Select All'.
4. Check whether all entities on the current page are selected.

## Expected Experience ##
All entities on the current page are selected.

## Actual Experience ##
Not all entities on the current page are selected.
![image](https://user-images.githubusercontent.com/87792676/234219318-aa07df5a-0760-4924-9849-400e28d9651a.png)

**Comment by craxal** [comment]
@v-kellyluo I think you'll find some rows on other pages are also selected.

The problem is the wrong indices are being used to find the selected items. The paged index of an item is internal to the data table, and the explorer has no way of knowing the paged index. I'll have to think a little more carefully about this.

**Comment by v-kellyluo** [comment]
@craxal , Verified this issue on the build 20230426.6, all entities on the first page are selected if sort entities then select all, but there is a new issue: Not all entities are selected on the current page if navigates beyond 1st page then click 'Select All', could you please help to take a look?

**Repro steps:**
1. Import more than 100 entities.
2. Navigate to the 2nd page -> Click 'Select All'.
3. Check whether all entities on the 2nd page are selected.

**Actual:**
Not all entities on the 2nd page are selected, some entities on the 1st page are selected.
![image](https://user-images.githubusercontent.com/87792676/234449868-8a890ef0-6258-46a2-b34b-ef9dafdf9f6e.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230427.5, the issue mentioned in [comments](https://github.com/microsoft/AzureStorageExplorer/issues/6837#issuecomment-1522671439) has been fixed, so we are going to close it.
