### ISSUE TITLE
All entities show duplicately in one pasted table

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6839]
**Storage Explorer Version:** 1.29.0
**Build Number:** 20230426.6
**Branch:** rel/1.29.0
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture:** ia32/x64/arm64
**How Found:** From running test cases
**Regression From:** Previous release (1.28.1)

## Steps to Reproduce ##

1. Expand a storage account -> Tables.
2. Create a table -> Import a .csv file. (Like: [test.csv](https://github.com/microsoft/AzureStorageExplorer/files/11330160/test.csv))

3. Right click the table -> Click 'Copy Table'.
4. Paste the table to another storage account.
5. Observe the pasted table.
6. Check whether no entity shows duplicately.

## Expected Experience ##
No entity shows duplicately.

## Actual Experience ##
All entities show duplicately.

## Additional Context ##

1. This issue can be resolved by manually refreshing.
2. This issue cannot be reproduced consistently.
3. Here is the record:
![copybug](https://user-images.githubusercontent.com/87792676/234502353-42ffbc1d-c011-4e75-a70f-b6aac5e2670a.gif)

**Comment by craxal** [comment]
I think this is what's happening:

The table explorer is registering for a refresh event with the Storage Explorer host. This is an asynchronous operation. The explorer does this in a React effect. While we can do async stuff in an effect, the effect itself can't await anything. Multiple refresh events are being fired, and the explorer doesn't have enough time to unregister the last event listener. The result is multiple calls to refresh occur, which is where the duplicates are ultimately coming from.

Investigating potential solutions.

**Comment by craxal** [comment]
@v-kellyluo Does this also happen if you clone a table in the same account?

I may have a fix to mitigate the issue, but it's hard to tell if it really resolves anything. Please verify during your next run on the latest build.

**Comment by v-kellyluo** [comment]
> Does this also happen if you clone a table in the same account?

Yes, this issue also reproduces when cloning one table.

@craxal ,this issue doesn't reproduce on the build 20230427.5. (tried more than ten times)
