### ISSUE TITLE
Fail to clone one non-empty blob container under a Premium GPV2 storage account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6840]
**Storage Explorer Version**: 1.29.0
**Build Number**: 20230426.6
**Branch**: rel/1.29.0
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture**: ia32/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.27.2)

## Steps to Reproduce ##
1. Expand one Premium GPV2 storage account -> Blob Containers.
2. Create a blob container -> Upload one page blob.
3. Try to clone the blob container.
4. Check whether succeeds to clone the blob container.

## Expected Experience ##
Succeed to clone the blob container.

## Actual Experience ##
Fail to clone the blob container.

![image](https://user-images.githubusercontent.com/41351993/234514781-51c4f587-b0bc-432d-a447-c3357eb906d8.png)

**Error details:**
` "message": "\"failed to perform copy command due to error: cannot start job due to error: cannot list files due to reason -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/zc_storage_error.go:42\\n===== RESPONSE ERROR (ServiceCode=InvalidQueryParameterValue) =====\\nDescription=Value for one of the query parameters specified in the request URI is invalid.\\n`

## Additional Context ##
Here is the log:
[2023-04-25_185608.zip](https://github.com/microsoft/AzureStorageExplorer/files/11330713/2023-04-25_185608.zip)

**Comment by JasonYeMSFT** [comment]
This bug is due to Premium page blob storage account not supporting listing blobs with tags. For now, users can workaround it by creating the container and copying blobs manually. Once we have the setting, people can opt out of preserving tags to more easily unblock the scenario. https://github.com/microsoft/AzureStorageExplorer/issues/6246

**Comment by JasonYeMSFT** [comment]
I have added the setting for "preserve blob tags" to explicitly turn it off. Could you verify this issue by turning it off, retrying cloning the container and see if it works? It should work once the setting is explicitly set to false.

**Comment by v-xianya** [comment]
@JasonYeMSFT Succeed to execute clone action when set the setting **Preserve Blob Tags** to "Don't preserve".
