### ISSUE TITLE
Data grid range selection does not work across pages

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#6841]

**Comment by MRayermannMSFT** [comment]
If a regression, hold off working on this until we have a better idea if we'll need to do a 1.29 hotfix. If not a regression, or if we don't do a hotfix, then just do in 1.30.0.

**Comment by craxal** [comment]
This is a regression from 1.28.1.

**Comment by v-xianya** [comment]
@craxal @MRayermannMSFT Verified this issue on build 20230506.4 following the steps mentioned in the email.

This issue reproduces when using 'Shift+click', does not reproduce when using 'Ctrl+click'.
In addition, the behaviors are the same on the previous version 1.28.1.

**Comment by craxal** [comment]
@v-xianya That build is outdated. Can you please verify on a build no older than 20230508.1?

**Comment by craxal** [comment]
@v-xianya I've tested Shift+Click using the same build you tested on, and I am not able to reproduce the problem. If I click on an item in page 1, navitigate to page 2, then Shift+Click an item on page 2, I clearly see that both items and all items in between are selected as expected. If this is not the same behavior that you are observing, can you please provide the steps you followed or a GIF illustrating what you observe?

Ctrl+Click is not range selection. It adds or removes an item to the current selection. I'm not sure why you were told this doesn't work across pages. I also observe that this behaves as expected in the test build.

What do you mean by "the behaviors are the same on the previous version 1.28.1"? Which behaviors are you referring to?
