### ISSUE TITLE
Azure Storage Explorer cannot see File Shares, though it can see Blob Containers

### ISSUE THREAD

**Issue by shendelin** [microsoft/AzureStorageExplorer#6842]
I'm new to Azure and learning how to use Azure Storage Explorer. When creating a Machine Learning workspace, some File Share was automatically created and that's where I saved code. I want to see those folders in Azure Storage Explorer (so that I can copy them to a different subscription). Yet I ran into the following error. Can you help?
****************** error message **********************
Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://parmazuremlwor5919507567.file.core.windows.net/?comp=list failed, reason: unable to get local issuer certificate",
  "stack": "FetchError: request to https://parmazuremlwor5919507567.file.core.windows.net/?comp=list failed, reason: unable to get local issuer certificate\n    at ClientRequest.<anonymous> (C:\\Users\\DSHEN\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:118601)\n    at ClientRequest.emit (node:events:513:28)\n    at TLSSocket.socketErrorListener (node:_http_client:481:9)\n    at TLSSocket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY",
  "code": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"
}

**Comment by craxal** [comment]
@shendelin Does your computer communicate through a proxy server? Have you configured Storage Explorer to use the proxy? You can do that using one of these methods:

* Set Application > Proxy > Proxy Configuration to "Use system proxy (preview)" to use the proxy settings used by your computer.
* Set Application > Proxy > Proxy Configuration to "Use app proxy settings" and fill in the proxy details in the other proxy settings.

If your proxy requires a certificate, you will need to follow our [troubleshooting guide](https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/storage-explorer-troubleshooting?tabs=Windows#ssl-certificate-issues) to import the certificate you need.

**Comment by shendelin** [comment]
It's working now. Our IT helped though I don't know the exact fix.
Thanks for the help!
