### ISSUE TITLE
The transfer activity log is always in progress when deleting the destination cloned blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6846]
**Storage Explorer Version**: 1.29.0
**Build Number**: 20230427.5
**Branch**: rel/1.29.0
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture**: ia32/x64/arm64
**How Found**: exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Open one blob container that contains several large blobs.
3. Try to clone the blob container.
4. Delete the clone blob container during transfer.
5. Check whether there is a failed activity log.

## Expected Experience ##
There is a failed activity log.

## Actual Experience ##
There is an in-progress activity log.

## Additional Context ##
This issue doesn't reproduce for ADLS Gen2 blobs/file shares.

**Comment by JasonYeMSFT** [comment]
AzCopy breaks down the big file into many trunks for separate upload. It doesn't realize that the destination container has been deleted so it keeps trying to upload the remaining trunks which takes a while before it quits. The user can still cancel the job to avoid blocking future transfers.

**Comment by JasonYeMSFT** [comment]
Opened an issue for AzCopy to consider enhancing this experience. https://github.com/Azure/azure-storage-azcopy/issues/2196
