### ISSUE TITLE
Cannot sign in to my azure account

### ISSUE THREAD

**Issue by saraashrafg** [microsoft/AzureStorageExplorer#6848]
{
  "name": null,
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"tunneling socket could not be established, cause=write EPROTO 1402141448:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:..\\\\\\\\..\\\\\\\\third_party\\\\\\\\boringssl\\\\\\\\src\\\\\\\\ssl\\\\\\\\tls_record.cc:231:\\\\n\\\",\\n  \\\"stack\\\": \\\"Error: tunneling socket could not be established, cause=write EPROTO 1402141448:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:..\\\\\\\\..\\\\\\\\third_party\\\\\\\\boringssl\\\\\\\\src\\\\\\\\ssl\\\\\\\\tls_record.cc:231:\\\\n\\\\n    at ClientRequest.onError (C:\\\\\\\\Program Files (x86)\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\tunnel-agent\\\\\\\\index.js:177:17)\\\\n    at Object.onceWrapper (node:events:628:26)\\\\n    at ClientRequest.emit (node:events:513:28)\\\\n    at TLSSocket.socketErrorListener (node:_http_client:481:9)\\\\n    at TLSSocket.emit (node:events:513:28)\\\\n    at emitErrorNT (node:internal/streams/destroy:157:8)\\\\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\\\\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)\\\",\\n  \\\"code\\\": \\\"ECONNRESET\\\"\\n}\""
}

**Comment by craxal** [comment]
@saraashrafg Does your computer communicate through a proxy server? Have you configured Storage Explorer to use the proxy? You can do that using one of these methods:

* Set Application > Proxy > Proxy Configuration to "Use system proxy (preview)" to use the proxy settings used by your computer.
* Set Application > Proxy > Proxy Configuration to "Use app proxy settings" and fill in the proxy details in the other proxy settings.

If your proxy requires a certificate, you will need to follow our [troubleshooting guide](https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/storage-explorer-troubleshooting?tabs=Windows#ssl-certificate-issues) to import the certificate you need.

**Comment by generalpattyn** [comment]
{
  "name": null,
  "message": "\"{\\n  \\\"message\\\": \\\"\\\\\\\"AADSTS50078: Presented multi-factor authentication has expired due to policies configured by your administrator, you must refresh your multi-factor authentication to access '797f4846-ba00-4fd7-ba43-dac1f8f63013'.\\\\\\\\r\\\\\\\\nTrace ID: c0a943f7-ba9d-4385-9a7b-57cfe73bb300\\\\\\\\r\\\\\\\\nCorrelation ID: b9369c3b-7e16-4e41-84b2-abdc21673e59\\\\\\\\r\\\\\\\\nTimestamp: 2023-05-03 13:16:41Z\\\\\\\"\\\"\\n}\""
}

**Comment by craxal** [comment]
@generalpattyn Have you tried signing out and signing back in? Or do you get this message every time you try?

**Comment by generalpattyn** [comment]
I get the message everytime.

Best Regards,

Greg

Greg Pattyn
GeneralPattyn.US
Tech Services
681 Blue Ridge Road
Pittsburgh, PA 15239
***@***.******@***.***>
Office (412) 744-9015 x1002
http://generalpattyn.us<http://generalpattyn.us/>
The Bridge Between Technology and You

Email requests for support to: ***@***.******@***.***>
