### ISSUE TITLE
Error Signing Into Storage Explorer

### ISSUE THREAD

**Issue by veneradsouza1** [microsoft/AzureStorageExplorer#6854]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.29.0

### Regression From

1.26.0

### Architecture

i86

### Storage Explorer Build Number

20230428.1

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Unable to access Azure Storage Explorer

### Steps to Reproduce

Launch Storage Explorer
Sign In

### Actual Experience

Unable to sign into the Azure account. Its displaying the below error:
![image](https://user-images.githubusercontent.com/60864857/236085266-701fbd08-52e5-4887-a776-fb5abd156a67.png)

{
  "name": "TypeError",
  "message": "Cannot delete property '0' of [object String]",
  "stack": "TypeError: Cannot delete property '0' of [object String]\n    at SubscriptionCache._removeOrphanSubscriptions (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\AzureSubscriptions\\SubscriptionCache.js:123:36)\n    at async SubscriptionCache._init (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\AzureSubscriptions\\SubscriptionCache.js:25:9)\n    at async SubscriptionCache.getSubscriptionsInCache (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\AzureSubscriptions\\SubscriptionCache.js:29:9)\n    at async SubscriptionCache.getSubscriptionsInCacheAsArray (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\AzureSubscriptions\\SubscriptionCache.js:51:38)\n    at async AzureSubscriptionsManager.sendTelemetry (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\AzureSubscriptions\\AzureSubscriptionsManager.js:109:42)\n    at async Provider.executeOperation (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\providers\\Provider.js:28:16)\n    at async ElectronRendererHostProxy.executeOperation (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\ElectronRendererHostProxy.js:37:20)"
}

### Expected Experience

In previous version, I was able to login to my Azure account and view the Storage Accounts and blobs, containers, etc

### Additional Context

Nil

**Comment by pavelm10** [comment]
Having the same issue.

Version: 1.29
Platform: Linux
Architecture: x64
Build number: 20230428.1

{
  "name": "TypeError",
  "message": "Cannot delete property '0' of [object String]",
  "stack": "TypeError: Cannot delete property '0' of [object String]\n    at SubscriptionCache._removeOrphanSubscriptions (/snap/storage-explorer/48/resources/app/out/app/renderer/AzureSubscriptions/SubscriptionCache.js:123:36)\n    at async SubscriptionCache._init (/snap/storage-explorer/48/resources/app/out/app/renderer/AzureSubscriptions/SubscriptionCache.js:25:9)\n    at async SubscriptionCache.getSubscriptionsInCache (/snap/storage-explorer/48/resources/app/out/app/renderer/AzureSubscriptions/SubscriptionCache.js:29:9)\n    at async SubscriptionCache.getSubscriptionsInCacheAsArray (/snap/storage-explorer/48/resources/app/out/app/renderer/AzureSubscriptions/SubscriptionCache.js:51:38)\n    at async AzureSubscriptionsManager.sendTelemetry (/snap/storage-explorer/48/resources/app/out/app/renderer/AzureSubscriptions/AzureSubscriptionsManager.js:109:42)\n    at async Provider.executeOperation (/snap/storage-explorer/48/resources/app/out/app/providers/Provider.js:28:16)\n    at async ElectronRendererHostProxy.executeOperation (/snap/storage-explorer/48/resources/app/out/app/renderer/ElectronRendererHostProxy.js:37:20)"
}

**Comment by MRayermannMSFT** [comment]
Thanks y'all. We're looking into this.

**Comment by veneradsouza1** [comment]
@MRayermannMSFT Thanks for your reply. 
Initial recommendation of removing account and restart, didn't help. But after deleting the entries for the suggested Keys; closing and reopening Storage Explorer, the issue is fixed! Thanks heaps

**Comment by MRayermannMSFT** [comment]
> @MRayermannMSFT Thanks for your reply. Initial recommendation of removing account and restart, didn't help. But after deleting the entries for the suggested Keys; closing and reopening Storage Explorer, the issue is fixed! Thanks heaps

Do you recall what the values of the entries happened to be? I was hoping to get some insight on how exactly the data had been corrupted (the errors y'all are sharing make it seem like the data somehow become corrupted).

**Comment by veneradsouza1** [comment]
I had the entry: 
 StorageExplorer.AzureSubscriptionsManager.subscriptionCacheV2 : undefined

**Comment by veneradsouza1** [comment]
Also the Logs Directory at the time of issue had these files. Happy to share if any of these are useful for finding root cause, just that some of them have lots of data and wasn't sure if there was any sensitive data, hence didn't share.
![image](https://user-images.githubusercontent.com/60864857/236367997-9495210a-93a9-435d-85a0-f2aec793e793.png)

**Comment by MRayermannMSFT** [comment]
If you could share all the logs since you updated to 1.29.0 that'd be great. So that would mean every log folder of the past ~28 hours.

**Comment by pavelm10** [comment]
@MRayermannMSFT  thanks for your help. For me the issue is fixed after removing StorageExplorer.AzureSubscriptionsManager.subscriptionCacheV2 : undefined
and restarting the explorer.

I am attaching zipped logs

From yesterday when the issue was still happening
[2023-05-04_090405.zip](https://github.com/microsoft/AzureStorageExplorer/files/11403817/2023-05-04_090405.zip)

From today morning, the issue is still there
[2023-05-05_082509.zip](https://github.com/microsoft/AzureStorageExplorer/files/11403824/2023-05-05_082509.zip)

After removing the key, issue is gone:
[2023-05-05_083100.zip](https://github.com/microsoft/AzureStorageExplorer/files/11403825/2023-05-05_083100.zip)

**Comment by Rutix** [comment]
@MRayermannMSFT I had the same problems and StorageExplorer.AzureSubscriptionsManager.subscriptionCacheV1 was undefined for me. Removing that key fixed me being able to authenticate.

[Logfiles.zip](https://github.com/microsoft/AzureStorageExplorer/files/11404235/Logfiles.zip)

Here are the zipped logfiles since I updated to 1.29.0 to now.

**Comment by Rutix** [comment]
> > StorageExplorer.AzureSubscriptionsManager.subscriptionCacheV1 was undefined for me. Removing that key fixed me being able to authenticate.
> 
> So to be clear @Rutix, V1 was undefined for you, not V2? Was there even a V2?

V1 was undefined and there was no V2.

**Comment by MRayermannMSFT** [comment]
@Rutix would you mind sharing some more logs prior to `2023-05-05_094240`? Maybe 3 or so folders?

**Comment by Rutix** [comment]
> @Rutix would you mind sharing some more logs prior to `2023-05-05_094240`? Maybe 3 or so folders?

Sure! See attached: 
[Logfiles-26th-04.zip](https://github.com/microsoft/AzureStorageExplorer/files/11445503/Logfiles-26th-04.zip)

**Comment by JasonYeMSFT** [comment]
We have made a 1.29.1 release which fixes this issue. Please upgrade and re-sign in to your azure account if needed. https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.29.1
