### ISSUE TITLE
It is better to add the shortcut 'Delete' for delete messages action

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6858]
**Storage Explorer Version**: 1.30.0-dev
**Build Number**: 20230505.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture**: x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Queues.
2. Create a queue -> Add one message.
3. Select the message -> Press 'Delete'.
4. Check whether the delete dialog pops up.

## Expected Experience ##
The delete dialog pops up.

## Actual Experience ##
No delete dialog pops up.

**Comment by JasonYeMSFT** [comment]
Let's add the shortcut since you are already working on the Delete command.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230511.3. Fixed. So, we are going to close it.
