### ISSUE TITLE
Stuck whilst loading - doesn't load blob containers created 

### ISSUE THREAD

**Issue by ilsamaria** [microsoft/AzureStorageExplorer#686]
**Storage Explorer Version**: 1.4.2
**Platform/OS Version**: Windows
**Architecture**: 
**Regression From**: 

#### Steps to Reproduce: ####
1.   Click Explorer 
2.  Click Storage Accounts 
3. Click on the specific storage account 
4. Click on blob containers 
5. Created blob containers do not show up, sticks on "loading" 

#### Expected Experience: ####

Expected experience is to get the the specific blob containers to be able to work with them 

#### Actual Experience: ####

I've tried deleting and reinstalling the app. 
Colleague (same network, same blob) doesn't see this issue

**Comment by MRayermannMSFT** [comment]
@ilsamaria are you still having issues with the latest version of Storage Explorer?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
