### ISSUE TITLE
No preview tab opens when trying to preview one .csv file under a file share/ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6860]
**Storage Explorer Version**: 1.30.0-dev
**Build Number**: 20230505.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture**: x64
**How Found**: From running test cases
**Regression From**: Previous release (1.29.0)

## Steps to Reproduce ##
1. Expand one storage account -> File Shares. (Make sure no .csv shows in the text preview file extensions setting)
2. Create a file share -> Upload one .csv file.
3. Select the .csv file -> Click 'Preview'.
4. Check whether the preview tab opens.

## Expected Experience ##
The preview tab opens.

## Actual Experience ##
No preview tab opens.

## Additional Context ##
For ADLS Gen2 blobs, this issue only reproduces for .csv files with content type 'text/csv' (Has nothing to do with the text preview file extensions setting)

**Comment by JasonYeMSFT** [comment]
The current main build doesn't have the correct implementation for csv preview command. I need to publish file and gen2 packages to include it.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230511.3. Fixed. So, we are going to close it.
