### ISSUE TITLE
Storage explorer not loading the storage accounts

### ISSUE THREAD

**Issue by sravanoddi** [microsoft/AzureStorageExplorer#6862]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.29.0

### Architecture

x64

### Platform

Linux (snap)

### OS Version

Unbuntu 22.04

### Bug Description

Storages are not loading in storage explorer. Seeing below error after login
{
  "name": "TypeError",
  "message": "Cannot delete property '0' of [object String]",
  "stack": "TypeError: Cannot delete property '0' of [object String]\n    at SubscriptionCache._removeOrphanSubscriptions (/snap/storage-explorer/48/resources/app/out/app/renderer/AzureSubscriptions/SubscriptionCache.js:123:36)\n    at async SubscriptionCache._init (/snap/storage-explorer/48/resources/app/out/app/renderer/AzureSubscriptions/SubscriptionCache.js:25:9)"
}

### Steps to Reproduce

1. Launch Storage explorer
2. Sign in to azure 
3. Check storages are loading in explorer

### Actual Experience

Opened storage explorer and logged into the account. Explorer panel is not displaying all the storages which i have access. only loading icon is displaying.

**Comment by MRayermannMSFT** [comment]
@sravanoddi Thanks for opening this issue. We've received other reports and are actively looking into the issue. Could you please:

   1. Launch Storage Explorer
   3. Go to Help -> Open Logs Directory
   4. Find all folders since you updated/installed 1.29.0
   5. Zip them
   6. Drag and drop it here
   7. Go back to Storage Explorer
   8. Press F12
   9. Go to the Application tab
   10. Look for Storage > Local Storage > file://, click that
   11. Look for entries with Keys of StorageExplorer.AzureSubscriptionsManager.subscriptionCacheV1 and StorageExplorer.AzureSubscriptionsManager.subscriptionCacheV2
   12. Double click on the values for each of those, and copy and paste them into a text file
   13. Redact your emails from the data pasted into the text file (if you'd like)
   14. Drag and drop the text file to here
   15. Click on each of the entries, and delete them (you can use your Delete key, or the X at the top of the list of entries)
   16. Restart

And after that you should no longer reproduce the issue. Thanks.

**Comment by ericthomas1** [comment]
I'm seeing the same issue today. Worked fine yesterday. 
**Version**: `1.29.0`
- ![image](https://user-images.githubusercontent.com/42788729/236567765-68484279-8e07-4b87-b509-a34ee079597b.png)

**Error**:

```
{
  "name": "TypeError",
  "message": "Cannot delete property '0' of [object String]",
  "stack": "TypeError: Cannot delete property '0' of [object String]\n    at SubscriptionCache._removeOrphanSubscriptions (C:\\Users\\b151659\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\AzureSubscriptions\\SubscriptionCache.js:123:36)\n    at async SubscriptionCache._init (C:\\Users\\b151659\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\AzureSubscriptions\\SubscriptionCache.js:25:9)\n    at async SubscriptionCache.getSubscriptionsInCache (C:\\Users\\b151659\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\AzureSubscriptions\\SubscriptionCache.js:29:9)\n    at async SubscriptionCache.getSubscriptionsInCacheAsArray (C:\\Users\\b151659\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\AzureSubscriptions\\SubscriptionCache.js:51:38)\n    at async AzureSubscriptionsManager.sendTelemetry (C:\\Users\\b151659\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\AzureSubscriptions\\AzureSubscriptionsManager.js:109:42)\n    at async Provider.executeOperation (C:\\Users\\b151659\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\providers\\Provider.js:28:16)\n    at async ElectronRendererHostProxy.executeOperation (C:\\Users\\b151659\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\ElectronRendererHostProxy.js:37:20)"
}
```

**Comment by ericthomas1** [comment]
I deleted the local storage `StorageExplorer.AzureSubscriptionsManager.subscriptionCacheV2` value, then restarted. 

Azure Storage Explorer is now working.

Thank you

**Comment by MRayermannMSFT** [comment]
@ericthomas1:

1. Do you recall what the value for that entry was?
2. Would you mind sharing your log folders since you updated? You can find logs at Help > Open Logs Folder.

**Comment by ericthomas1** [comment]
@MRayermannMSFT,
1. I believe it was `undefined`
2. I scanned the logs. Due to the info shown, I can't share. 
    - I'm willing to sanitize a small `main.log` for you, if thats of value.
3. I used ASE on 4/28, 5/4 and 5/5. I can't remember when I updated it to 1.29.0; whether it was on close 4/28, or on open/close 5/4. 
    - I know I didn't update ASE today (5/5)

**Comment by MRayermannMSFT** [comment]
> I scanned the logs. Due to the info shown, I can't share.

No worries. Can you tell me:
1. Do any logs contain the string "SubscriptionCache found V1 cache, converting it to V2"?
2. For the files that do, they also contain the string "SubscriptionCache converted V1 cache to V2 and wrote it to storage"?
3. On what days were those logs from?

**Comment by ericthomas1** [comment]
1. There are ~100 individual logs between ~4/26 - 5/5. 
    - Should I focus on the `_main_.log` or is there another specific log this could be found in?

**Comment by ShermanCAA** [comment]
Running into the same error but there are no values for SubscriptionCacheV2 in local storage

**Comment by JasonYeMSFT** [comment]
We have made a 1.29.1 release which fixes this issue. Please upgrade and re-sign in to your azure account if needed. https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.29.1
