### ISSUE TITLE
There are missed actions on the context menu in the 'Release Notes -> Tree View Context Menu Separators and Reordering' part

### ISSUE THREAD

**Issue by v-sunnsun** [microsoft/AzureStorageExplorer#6864]
**Storage Explorer Version**: 1.29.1
**Build Number**: 20230508.1
**Branch**: hotfix/1.29.1
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture**: ia32/x64/arm64
**How Found**: From running test cases
**Regression From**:  Not a regression

## Steps to Reproduce 

1. Open Release Notes -> Go to 'Tree View Context Menu Separators and Reordering' part.
2. Check whether there are no missed actions on the context menu.

## Expected Experience 
There are no missed actions on the context menu.
![image](https://user-images.githubusercontent.com/122582307/236766063-bad25495-1395-4160-a21e-23acf251f066.png)

## Actual Experience ##
There are missed actions on the context menu.
![image](https://user-images.githubusercontent.com/122582307/236762581-faa2fdb1-9838-4ca6-aaca-706046330f04.png)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230509.5. Fixed. So, we are going to close it.

**Comment by v-kellyluo** [comment]
@JasonYeMSFT , verified this issue on the build 20230509.3, the actions 'Manage Stored Access Policies...' and 'Set Public Access Level...' don't display in the context menu, could you please help to take a look?
![image](https://user-images.githubusercontent.com/87792676/236979093-5cdf7991-269c-41a6-85e3-69e7f2eefb4c.png)

**Comment by JasonYeMSFT** [comment]
@v-kellyluo Yes, that's expected. I took the new screenshots for the same container in 1.28.1 and 1.29.1 rc build. The purpose of the screenshot is to demonstrate the separator so it doesn't have to have every action it.
