### ISSUE TITLE
The group button is enabled even if the selected clauses have been formed into a group

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6865]
**Storage Explorer Version**: 1.29.1
**Build Number**: 20230508.1
**Branch**: hotfix/1.29.1
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture**: ia32/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Click 'Query' -> Add two clauses.
3. Select the two clauses -> Click group button.
4. After the clauses are grouped.
5. Check whether the group button is disabled.

## Expected Experience ##
The group button is disabled.
![image](https://user-images.githubusercontent.com/41351993/236776636-12ab06e1-7033-4860-b65b-1cb41a1d4e60.png)

## Actual Experience ##
The group button is enabled.
![image](https://user-images.githubusercontent.com/41351993/236776686-42d1dd4e-1404-4b0d-abd9-d811401313fa.png)

**Comment by JasonYeMSFT** [comment]
@craxal Could you find out if allowing to group clauses that are already in a group does anything unexpected?

**Comment by craxal** [comment]
@JasonYMSFT This was an intentional change. I already discussed this in a past meeting where I allowed clauses already in a group to be grouped again. It results in perfectly valid OData query syntax, and it does not have any observable side effects.
