### ISSUE TITLE
Could not access resources for this tenant. You may need to reauthenticate

### ISSUE THREAD

**Issue by NishanthSanjeevi** [microsoft/AzureStorageExplorer#6867]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.29.0

### Architecture

x64

### Platform

Windows

### Bug Description

{
  "name": "TypeError",
  "message": "Cannot delete property '0' of [object String]",
  "stack": "TypeError: Cannot delete property '0' of [object String]\n    at SubscriptionCache._removeOrphanSubscriptions (C:\\Users\\nisanjee\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\AzureSubscriptions\\SubscriptionCache.js:123:36)\n    at async SubscriptionCache._init (C:\\Users\\nisanjee\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\AzureSubscriptions\\SubscriptionCache.js:25:9)\n    at async SubscriptionCache.getSubscriptionsInCache (C:\\Users\\nisanjee\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\AzureSubscriptions\\SubscriptionCache.js:29:9)\n    at async SubscriptionCache.getSubscriptionsInCacheAsArray (C:\\Users\\nisanjee\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\AzureSubscriptions\\SubscriptionCache.js:51:38)\n    at async AzureSubscriptionsManager.sendTelemetry (C:\\Users\\nisanjee\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\AzureSubscriptions\\AzureSubscriptionsManager.js:109:42)\n    at async Provider.executeOperation (C:\\Users\\nisanjee\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\providers\\Provider.js:28:16)\n    at async ElectronRendererHostProxy.executeOperation (C:\\Users\\nisanjee\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\ElectronRendererHostProxy.js:37:20)"
}

### Steps to Reproduce

Opened Azure Storage Explorer and this issue occurred in random.
Not able to fix it even after uninstalling and reinstalling Azure storage explorer.

### Actual Experience

When I try to re-authenticate no new browser window opens.

**Comment by NishanthSanjeevi** [comment]
The subscriptionCacheV2 is undefined and there is no V1 Cache.
[cid:f65a854e-020b-4a1e-8f21-4dca4426b2fa]

Thanks,
Nishanth.

**Comment by JasonYeMSFT** [comment]
What you described meets our hypothesis of the bug. Do you remember if you have closed Storage Explorer when the application just started? The bug may be caused by the application being closed before writing the proper data back but we couldn't verify that.

**Comment by NishanthSanjeevi** [comment]
I do not remember doing something like that..

Thanks,
Nishanth.
________________________________

**Comment by JasonYeMSFT** [comment]
We have made a 1.29.1 release which fixes this issue. Please upgrade and re-sign in to your azure account if needed.
