### ISSUE TITLE
Unable to login via Azure account

### ISSUE THREAD

**Issue by Twinbat26** [microsoft/AzureStorageExplorer#6868]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.29.0

### Architecture

i86

### Platform

Windows

### Bug Description

{
  "name": null,
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"getaddrinfo ENOTFOUND management.azure.com\\\",\\n  \\\"stack\\\": \\\"Error: getaddrinfo ENOTFOUND management.azure.com\\\\n    at __node_internal_captureLargerStackTrace (node:internal/errors:484:5)\\\\n    at __node_internal_ (node:internal/errors:706:10)\\\\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)\\\",\\n  \\\"errno\\\": -3008,\\n  \\\"code\\\": \\\"ENOTFOUND\\\",\\n  \\\"syscall\\\": \\\"getaddrinfo\\\",\\n  \\\"hostname\\\": \\\"management.azure.com\\\"\\n}\""
}

### Steps to Reproduce

1. Launch storage explorer.
2. Sign in with the browser
3. Getting authentication error however the account shows up 

### Actual Experience

I am trying to login to Storage explorer for the first time and getting the error during authentication on my work account

**Comment by Twinbat26** [comment]
{   "name": null,   "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"getaddrinfo ENOTFOUND management.azure.com\\\",\\n  \\\"stack\\\": \\\"Error: getaddrinfo ENOTFOUND management.azure.com\\\\n    at __node_internal_captureLargerStackTrace (node:internal/errors:484:5)\\\\n    at __node_internal_ (node:internal/errors:706:10)\\\\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)\\\",\\n  \\\"errno\\\": -3008,\\n  \\\"code\\\": \\\"ENOTFOUND\\\",\\n  \\\"syscall\\\": \\\"getaddrinfo\\\",\\n  \\\"hostname\\\": \\\"management.azure.com\\\"\\n}\"" }

**Comment by JasonYeMSFT** [comment]
@Twinbat26 The error is a DNS lookup error. Are you using a proxy? If so, try selecting "use system proxy" in the proxy settings. If that doesn't work, please double check if you can resolve the host name "management.azure.com" from the command line or other tools.

**Comment by Twinbat26** [comment]
Internal

Hi Jason,

Thanks, It did solve the issue!

Twinkle Batham
CMP-Enablement/Automation

Allianz Technology SE | EON IT Park, Phase II, 12th Floor | Pune, Kharadi - 411014, Maharashtra, India
Phone : +49 89262039530 | Mobile : +91 (0) 8871798981 | E-mail: ***@***.***



From: JasonYeMSFT ***@***.***>
Sent: Tuesday, May 9, 2023 11:00 PM
To: microsoft/AzureStorageExplorer ***@***.***>
Cc: Batham, Twinkle (Allianz Technology) ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [microsoft/AzureStorageExplorer] Unable to login via Azure account (Issue #6868)


@Twinbat26<https://github.com/Twinbat26> The error is a DNS lookup error. Are you using a proxy? If so, try selecting "use system proxy" in the proxy settings. If that doesn't work, please double check if you can resolve the host name "management.azure.com" from the command line or other tools.
