### ISSUE TITLE
Cannot delete property '0' of [object String]

### ISSUE THREAD

**Issue by simongoldstone** [microsoft/AzureStorageExplorer#6869]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.29.30

### Architecture

x64

### Storage Explorer Build Number

20230428.1

### Platform

All

### OS Version

Windows 11

### Bug Description

{
  "name": "TypeError",
  "message": "Cannot delete property '0' of [object String]",
  "stack": "TypeError: Cannot delete property '0' of [object String]\n    at SubscriptionCache._removeOrphanSubscriptions (C:\\Users\\simon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\AzureSubscriptions\\SubscriptionCache.js:123:36)\n    at async SubscriptionCache._init (C:\\Users\\simon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\AzureSubscriptions\\SubscriptionCache.js:25:9)\n    at async SubscriptionCache.getSubscriptionsInCache (C:\\Users\\simon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\AzureSubscriptions\\SubscriptionCache.js:29:9)\n    at async SubscriptionCache.getSubscriptionsInCacheAsArray (C:\\Users\\simon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\AzureSubscriptions\\SubscriptionCache.js:51:38)\n    at async AzureSubscriptionsManager.sendTelemetry (C:\\Users\\simon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\AzureSubscriptions\\AzureSubscriptionsManager.js:109:42)\n    at async Provider.executeOperation (C:\\Users\\simon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\providers\\Provider.js:28:16)\n    at async ElectronRendererHostProxy.executeOperation (C:\\Users\\simon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\renderer\\ElectronRendererHostProxy.js:37:20)"
}

### Steps to Reproduce

1. Launch
2. Spinner icon is visible in the connection bar
3. Message appears: Could not access resources for this tenant. You may need to reauthenticate. See the error details for more information.
4. Attempt to "Reauthenticate"
5. Browser appears
6. Reauthenticate
7. Return to connection bar
8. Spinner continues
9. When clicking on "Error details", the error appears

### Actual Experience

1. Launch
2. Spinner icon is visible in the connection bar
3. Message appears: Could not access resources for this tenant. You may need to reauthenticate. See the error details for more information.
4. Attempt to "Reauthenticate"
5. Browser appears
6. Reauthenticate
7. Return to connection bar
8. Spinner continues
9. When clicking on "Error details", the error appears

**Comment by JasonYeMSFT** [comment]
This is the same bug as https://github.com/microsoft/AzureStorageExplorer/issues/6854. Could you workaround it for now by deleting the corrupted entry in local storage? The linked issue has instructions on how to do it.

**Comment by simongoldstone** [comment]
Yes, sorry missed that one. The fix in #6854 resolved the issue for me. Happy to close issue.

**Comment by simongoldstone** [comment]
Yes, sorry missed that one. The fix in #6854 resolved the issue for me. Happy to close issue. Thank you.
