### ISSUE TITLE
Re-authentication keeps failing in Azure Storage Explorer

### ISSUE THREAD

**Issue by lihuazhi** [microsoft/AzureStorageExplorer#6872]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.29.0

### Architecture

i86

### Platform

All

### OS Version

Windows 10

### Bug Description

Re-authentication keeps failing in Azure Storage Explorer

Error attached below.

{
  "name": null,
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"self signed certificate in certificate chain\\\",\\n  \\\"stack\\\": \\\"Error: self signed certificate in certificate chain\\\\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1538:34)\\\\n    at TLSSocket.emit (node:events:513:28)\\\\n    at TLSSocket._finishInit (node:_tls_wrap:952:8)\\\\n    at ssl.onhandshakedone (node:_tls_wrap:733:12)\\\",\\n  \\\"code\\\": \\\"SELF_SIGNED_CERT_IN_CHAIN\\\"\\n}\""
}

### Steps to Reproduce

Launch Azure Storage Explorer as admin from Windows 10.

### Actual Experience

![Capture](https://github.com/microsoft/AzureStorageExplorer/assets/17729481/b19f57b9-ceda-4bff-814c-ed39547638b5)

**Comment by craxal** [comment]
@lihuazhi We recently shipped 1.29.1 which addresses some sign in issues. Can you update to that version and try again?

**Comment by lihuazhi** [comment]
@craxal Thank you! I installed 1.29.1, unfortunately, the issue is still happening. Please refer to the screenshot below for detail.
![Capture-2](https://github.com/microsoft/AzureStorageExplorer/assets/17729481/c84101b0-7661-4807-9d8a-478e470c54f7)

**Comment by MRayermannMSFT** [comment]
Ah. Thank you for sharing the error message. For this error, please enable system proxy: https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue, we reccommend opening a support ticket via the Azure portal. Alternatively you can open a new issue here.
