### ISSUE TITLE
There is no error message when typing '&\' into the tag key field on 'Edit Tags' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6873]
**Storage Explorer Version**: 1.29.1
**Build Number**: 20230509.5
**Branch**: hotfix/1.29.1
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture**: ia32/x64/arm64
**App configuration:** 0.2.0
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand 'App Configurations' node -> Open one app configuration.
2. Add a key-value -> Right click the key-value.
3. Click 'Edit Tags...' -> Click 'Add Tag'.
5. Type '&\\' into the tag key field.
6. Check whether there is an error message. 

## Expected Experience ##
There is an error message. 
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/ded837e6-18a4-49c1-ae59-7997990548a2)

## Actual Experience ##
There is no error message. 
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/1134a921-862f-44c2-8327-6e1a3c31a2a2)

## Additional Context ##
1. Succeed to save the tag with the name '&\\'.
2. There is no error using spaces as the tag name but fail to save it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/28504453-6e91-4907-b60a-e69e5fd9317f)
Error details:
` "name": "RestError",
  "message": "{\"type\":\"https://azconfig.io/errors/invalid-argument\",\"title\":\"Invalid request parameter 'tags'\",\"name\":\"tags\",\"detail\":\"\",\"status\":400}",`
 3. There is an error when using '$' as the tag name.
 
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/e892ab59-9dc8-40d8-824c-c5b6bbf3dc9a)

**Comment by JasonYeMSFT** [comment]
The actual length limit is 256.

**Comment by v-xianya** [comment]
Verified this issue using the new app configuration extension. Fixed.
And the issues mentioned in comments are all fixed. So, we are going to close it. 
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/90de079b-e1ff-485f-a0a5-6b748eaab94a)
