### ISSUE TITLE
It is better to update 'Select all' to 'Select All' on the toolbar of app configuration explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6874]
**Storage Explorer Version**: 1.29.1
**Build Number**: 20230509.5
**Branch**: hotfix/1.29.1
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture**: ia32/x64/arm64
**App configuration version:** 0.2.0
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand 'App Configurations' node -> Open one app configuration.
2. Observe the toolbar actions.

## Expected Experience ##
It is better to update 'Select all' to 'Select All'.

## Actual Experience ##
Show 'Select all' on the toolbar.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/6e5bcb51-99a3-40f2-a4e0-7f68a4271d4d)

**Comment by JasonYeMSFT** [comment]
The string in this label matches the strings in the dropdown so won't fix for now.
