### ISSUE TITLE
It is hard to see the lock icon when selecting a locked key-value

### ISSUE THREAD

**Issue by v-sunnsun** [microsoft/AzureStorageExplorer#6877]
**Storage Explorer Version**: 1.29.1
**Build Number**: 20230509.5
**Branch**: hotfix/1.29.1
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture**:  ia32/x64/arm64
**App configuration**: 0.2.0
**How Found**: Exploratory testing
**Regression From**:  Not a regression

## Steps to Reproduce 

1. Expand 'App Configurations' node -> Open one app configuration.
2. Add a key-value -> Right click the key-value.
3. Click 'Lock' -> Select the key-value.
4. Check whether it is easy to see the lock icon.

## Expected Experience 
It is easy to see the lock icon.
Refer to leased icon for blobs:
![image](https://github.com/microsoft/AzureStorageExplorer/assets/122582307/331bbd8c-0ae8-4754-a7b6-2fc2e55dc43a)

## Actual Experience ##
It is hard to see the lock icon.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/122582307/59b3cf71-5d40-4bf9-b09a-4221b1229a92)

## Additional Context ##

1. This issue also reproduces under the 'High Contrast - White' theme:
![image](https://github.com/microsoft/AzureStorageExplorer/assets/122582307/a235f867-3944-4bb8-93a0-532d63830a1a)
2. This issue doesn't reproduce under the 'Dark/High Contrast - Black' themes:
![image](https://github.com/microsoft/AzureStorageExplorer/assets/122582307/897a3163-b78a-4e63-b386-07358d03d90c)
![image](https://github.com/microsoft/AzureStorageExplorer/assets/122582307/58b55f6a-fda1-4b06-aa68-6b20a360df09)

**Comment by v-xianya** [comment]
Verified this issue using the new app configuration extension. Fixed. So we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/01e31ec5-4713-48b3-8b0e-47a9ac7d1ede)
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/83779663-b18a-4b22-a672-fba0c741dd07)
