### ISSUE TITLE
It is better to add a scrollbar under 'Keys' and 'Labels' fields if narrow app configuration tab horizontally

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6878]
**Storage Explorer Version:** 1.29.1
**Build Number:** 20230509.5
**Branch:** hotfix/1.29.1
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture:** ia32/x64/arm64
**App configuration version:** 0.2.0
**How Found:** Exploratory testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand 'App Configurations' node -> Open one app configuration.
2. Narrow the tab horizontally.
3. Check whether there is a scrollbar under the 'Keys' and 'Labels' fields.

## Expected Experience ##
It is better to add a scrollbar.

## Actual Experience ##
There is no scrollbar.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/45a0527b-2c14-4f71-aec6-88a866f1ca1b)

## Additional Context ##
It is better to add 'Filter by' string to the 'Keys' and 'Labels' fields.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/087fc81d-6628-4ceb-ac65-1d9aa24f5dae)

**Comment by v-xianya** [comment]
Verified this issue using the new app configuration extension. Fixed. So, we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/f1e667fe-5d56-4aba-8d8f-131f2671ea40)
