### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by ktenneti-ai** [microsoft/AzureStorageExplorer#6879]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.29.1

### Architecture

i86

### Storage Explorer Build Number

20230509.5

### Platform

Windows

### OS Version

Windows 11

### Bug Description

This request is not authorized to perform this operation.

This storage account's 'Firewalls & virtual networks' settings may be blocking access to storage services. Try adding your client IP address to the firewall exceptions, or by allowing access from 'all networks' instead of 'selected networks'. To learn more about Azure Storage firewalls and virtual networks, visit http://go.microsoft.com/fwlink/?LinkId=845443.

Error Details:
{
  "name": "RestError",
  "code": "AuthorizationFailure",
  "statusCode": 403,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://abc.blob.core.windows.net/?comp=list&include=metadata",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2021-10-04"
        },
        "accept": {
          "name": "Accept",
          "value": "application/xml"
        },
        "user-agent": {
          "name": "User-Agent",
          "value": "Microsoft Azure Storage Explorer/1.29.1 (win32) azsdk-js-storageblob/12.12.0 (NODE-VERSION v18.12.1; Windows_NT 10.0.19044)"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "5afb7c1d-ebe6-42f5-a90f-98bddfca6ff3"
        },
        "authorization": {
          "name": "authorization",
          "value": "Bearer JSON Web Token Redacted"
        },
        "cookie": {
          "name": "Cookie",
          "value": ""
        }
      }
    },
    "withCredentials": false,
    "timeout": 0,
    "keepAlive": true,
    "decompressResponse": false,
    "requestId": "5afb7c1d-ebe6-42f5-a90f-98bddfca6ff3"
  },
  "response": {
    "headers": {
      "_headersMap": {
        "content-length": {
          "name": "content-length",
          "value": "246"
        },
        "content-type": {
          "name": "content-type",
          "value": "application/xml"
        },
        "date": {
          "name": "date",
          "value": "Thu, 11 May 2023 12:49:01 GMT"
        },
        "server": {
          "name": "server",
          "value": "Microsoft-HTTPAPI/2.0"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "5afb7c1d-ebe6-42f5-a90f-98bddfca6ff3"
        },
        "x-ms-error-code": {
          "name": "x-ms-error-code",
          "value": "AuthorizationFailure"
        },
        "x-ms-request-id": {
          "name": "x-ms-request-id",
          "value": "77159502-d01e-0040-5006-849850000000"
        }
      }
    },
    "request": {
      "streamResponseStatusCodes": {},
      "url": "https://abc.blob.core.windows.net/?comp=list&include=metadata",
      "method": "GET",
      "headers": {
        "_headersMap": {
          "x-ms-version": {
            "name": "x-ms-version",
            "value": "2021-10-04"
          },
          "accept": {
            "name": "Accept",
            "value": "application/xml"
          },
          "user-agent": {
            "name": "User-Agent",
            "value": "Microsoft Azure Storage Explorer/1.29.1 (win32) azsdk-js-storageblob/12.12.0 (NODE-VERSION v18.12.1; Windows_NT 10.0.19044)"
          },
          "x-ms-client-request-id": {
            "name": "x-ms-client-request-id",
            "value": "5afb7c1d-ebe6-42f5-a90f-98bddfca6ff3"
          },
          "authorization": {
            "name": "authorization",
            "value": "Bearer JSON Web Token Redacted"
          },
          "cookie": {
            "name": "Cookie",
            "value": ""
          }
        }
      },
      "withCredentials": false,
      "timeout": 0,
      "keepAlive": true,
      "decompressResponse": false,
      "requestId": "5afb7c1d-ebe6-42f5-a90f-98bddfca6ff3"
    },
    "status": 403,
    "bodyAsText": "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.\nRequestId:77159502-d01e-0040-5006-849850000000\nTime:2023-05-11T12:49:01.9332040Z</Message></Error>",
    "parsedBody": {
      "message": "This request is not authorized to perform this operation.\nRequestId:77159502-d01e-0040-5006-849850000000\nTime:2023-05-11T12:49:01.9332040Z",
      "code": "AuthorizationFailure"
    },
    "parsedHeaders": {
      "errorCode": "AuthorizationFailure",
      "content-length": "246",
      "content-type": "application/xml",
      "date": "Thu, 11 May 2023 12:49:01 GMT",
      "server": "Microsoft-HTTPAPI/2.0",
      "x-ms-client-request-id": "5afb7c1d-ebe6-42f5-a90f-98bddfca6ff3",
      "x-ms-request-id": "77159502-d01e-0040-5006-849850000000"
    }
  },
  "details": {
    "errorCode": "AuthorizationFailure",
    "content-length": "246",
    "content-type": "application/xml",
    "date": "Thu, 11 May 2023 12:49:01 GMT",
    "server": "Microsoft-HTTPAPI/2.0",
    "x-ms-client-request-id": "5afb7c1d-ebe6-42f5-a90f-98bddfca6ff3",
    "x-ms-request-id": "77159502-d01e-0040-5006-849850000000",
    "message": "This request is not authorized to perform this operation.\nRequestId:77159502-d01e-0040-5006-849850000000\nTime:2023-05-11T12:49:01.9332040Z",
    "code": "AuthorizationFailure"
  }
}

### Steps to Reproduce

Added the ip address to the exception list. 
logged into the portal and installed the storage explorer to view the contents of the blob storage. 

### Actual Experience

I could view the folders in the blob storage but when I clicked on any folder then I get a message Authentication failure.

**Comment by craxal** [comment]
@ktenneti Can you share more information about the task you are trying to accomplish? Is the container you're trying to access a blob container or an ADLS Gen2 container? How are you authenticating (sign in, SAS, account name and key)?
