### ISSUE TITLE
VHD upload from Storage Explorer Failed

### ISSUE THREAD

**Issue by Pkistampally** [Microsoft/AzureStorageExplorer#688]
{
  "name": "Error",
  "message": "getaddrinfo ENOTFOUND rndprod.blob.core.windows.net rndprod.blob.core.windows.net:443",
  "stack": "Error: getaddrinfo ENOTFOUND rndprod.blob.core.windows.net rndprod.blob.core.windows.net:443\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
  "code": "ENOTFOUND",
  "errno": "ENOTFOUND",
  "syscall": "getaddrinfo",
  "hostname": "rndprod.blob.core.windows.net",
  "host": "rndprod.blob.core.windows.net",
  "port": "443",
  "innerError": {
    "code": "ESOCKETTIMEDOUT",
    "connect": false,
    "innerError": {
      "code": "ESOCKETTIMEDOUT",
      "connect": false,
      "innerError": {
        "code": "ESOCKETTIMEDOUT",
        "connect": false,
        "innerError": {
          "code": "ESOCKETTIMEDOUT",
          "connect": false,
          "innerError": {
            "code": "ESOCKETTIMEDOUT",
            "connect": false,
            "innerError": {
              "code": "ESOCKETTIMEDOUT",
              "connect": false,
              "innerError": {
                "code": "ESOCKETTIMEDOUT",
                "connect": false,
                "innerError": {
                  "code": "ESOCKETTIMEDOUT",
                  "connect": false,
                  "innerError": {
                    "code": "ESOCKETTIMEDOUT",
                    "connect": false,
                    "innerError": {
                      "code": "ESOCKETTIMEDOUT",
                      "connect": false,
                      "innerError": {
                        "code": "ESOCKETTIMEDOUT",
                        "connect": false,
                        "innerError": {
                          "code": "ESOCKETTIMEDOUT",
                          "connect": false,
                          "innerError": {
                            "code": "ESOCKETTIMEDOUT",
                            "connect": false,
                            "innerError": {
                              "code": "ESOCKETTIMEDOUT",
                              "connect": false,
                              "innerError": {
                                "code": "ESOCKETTIMEDOUT",
                                "connect": false
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

**Comment by Pkistampally** [comment]
I have received above error after the VHD got uploaded 70%

**Comment by JakeRadMSFT** [comment]
Please re-open if you believe it's more than a lost connection bug.
