### ISSUE TITLE
storage explorer blob container copy between storage accounts fails

### ISSUE THREAD

**Issue by martin-shea** [microsoft/AzureStorageExplorer#6880]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.29.0

### Regression From

none

### Architecture

i86

### Storage Explorer Build Number

20230428.1

### Platform

Windows

### OS Version

Windows 10

### Bug Description

I an trying to copy data between two containers in two different storage accounts and am running into issue. I authenticate to each blob container with SS tokens, which seems to be working. I am attaching the log files here.

[logs_4_kushal.zip](https://github.com/microsoft/AzureStorageExplorer/files/11452982/logs_4_kushal.zip)

### Steps to Reproduce

1. Launch storage explorer
2. navigate to source directory in source blob container. Highlight the directory, right click and copy.
3. navigate to the target blob container and paste. Session logs containing the failure are uploaded above.

### Actual Experience

the session fails with the following in the storage explorer activity window...

Transfer of '1581423-4274364-pagaaspipdelc-8918880e-4685-9b0df11f/PID1581423/Tomcat/' to 'outgoing-to-vendor/Ellkay/TJU2017_ABJH_eCW_Gastro/PID1581423/' canceled: 0 items transferred, 1 item failed, error: UnexpectedCancel (used SAS, discovery completed)
Started at: 5/11/2023 9:26 AM, Duration: 4 seconds

### Expected Experience

expected experience is the transfer would complete

### Additional Context

log files attached above

**Comment by craxal** [comment]
@martin-shea The logs seem to indicate that the PUT operation was not authorized. What permissions do your SAS URLs have? How long until they expire?

**Comment by martin-shea** [comment]
If I'm reading it correctly, i notice the token was issued 18 months ago. I asked the company we're working with to issue a new token which I will try upon receipt. I really appreciate your responding.

**Comment by MRayermannMSFT** [comment]
@martin-shea at this point we're going to close this issue. If you are still encountering this issue we recommend opening a support ticket via the Azure Portal. Alternatively you can open a new issue here.
