### ISSUE TITLE
There is an extra action 'Copy Direct Link to App Configuration Store' for one app configuration on Linux

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6882]
**Storage Explorer Version:** 1.29.1
**Build Number:** 20230509.5
**Branch:** hotfix/1.29.1
**Platform/OS:** Linux Ubuntu 20.04
**Architecture:** x64
**App configuration version:** 0.2.0
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Open Storage Explorer on Linux -> Expand 'App Configurations' node.
2. Select and right click one app configuration.
3. Check whether there is no extra action 'Copy Direct Link to App Configuration Store'.

## Expected Experience ##
There is no extra action 'Copy Direct Link to App Configuration Store'.

## Actual Experience ##
There is an extra action 'Copy Direct Link to App Configuration Store'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/097ed9dc-52b9-45b5-a266-e241b3210a86)

**Comment by JasonYeMSFT** [comment]
I think it's ok to let Linux users generate direct links since it's meant for sharing. Although the link won't work on Linux, the user can still share it with people on Windows/Mac and it will work.
