### ISSUE TITLE
The row height is narrow when previewing a .csv file that contains only one entry with all empty column values

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6883]
**Storage Explorer Version**: 1.30.0-dev
**Build Number**: 20230512.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture**: x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.29.1)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one .csv file which content type is 'text/csv'. 
[table.csv](https://github.com/microsoft/AzureStorageExplorer/files/11459697/table.csv)

3. Preview the .csv file.
4. Check whether the row height of the entity is normal.

## Expected Experience ##
The row height of the entity is normal.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/a595a68d-5bcd-4f52-b29b-2988192a6573)

## Actual Experience ##
The row height of the entity is narrow.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/f2005187-0d66-4783-812a-03928eb8cb49)

## Additional Context ##
This issue also reproduces for files under file shares/ADLS Gen2 blob containers.

**Comment by craxal** [comment]
I also saw this. I think I just need to update the UI package version the preview extension is using, since this was already resolved for tables.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230518.4.Fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/514ac2d6-32e5-4b66-b630-b4545a42f110)
