### ISSUE TITLE
It is better to add the shortcut Ctrl+R for refresh action in app configuration explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6884]
**Storage Explorer Version**: 1.29.1
**Build Number**: 20230509.5
**Branch**: hotfix/1.29.1
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture**: ia32/x64/arm64
**App configuration version:** 0.2.0
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand 'App Configurations' node -> Open one app configuration.
2. Hover over on the Refresh button.
3. Check whether there is a shortcut 'Ctrl+R'.

## Expected Experience ##
There is a shortcut 'Ctrl+R'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/83aa3072-b14c-4556-bba0-ae787da90e24)

## Actual Experience ##
There is no shortcut 'Ctrl+R'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/6c9c9ce0-e613-453a-9e30-7b4a421ce3cd)

**Comment by JasonYeMSFT** [comment]
I added that to the tooltip.

**Comment by v-xianya** [comment]
@JasonYeMSFT Verified this issue using the new extension build. the tooltip has been added, but Ctrl+R doesn't take effect. could you help to have a look?
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/893fd468-ac83-42da-bac4-48ca5804c3c2)

**Comment by v-xianya** [comment]
Verified this issue on the updated extension, Ctrl+R takes effect. So, we are going to close it.
