### ISSUE TITLE
UnexpectedQuit when downloading files from Blob

### ISSUE THREAD

**Issue by cmolinacab** [microsoft/AzureStorageExplorer#6885]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.28.1

### Architecture

i86

### Storage Explorer Build Number

20230309.1

### Platform

macOS

### OS Version

macOS Monterey

### Bug Description

{
  "message": "\"UnexpectedQuit\""
}

When try to download any file from Blob

export AZCOPY_CRED_TYPE=Anonymous;
export AZCOPY_CONCURRENCY_VALUE=AUTO;
./azcopy copy "https://dlsdefensoriadev001.blob.core.windows.net/archivos/ocr_imagenes/azure_responses_5000_random_sample_3/?sv=2021-10-04&se=2023-06-11T06%3A35%3A50Z&sr=c&sp=rl&sig=redacted" "/Users/user/Downloads" --overwrite=prompt --check-md5 FailIfDifferent --from-to=BlobLocal --recursive --log-level=INFO;
unset AZCOPY_CRED_TYPE;
unset AZCOPY_CONCURRENCY_VALUE;

### Steps to Reproduce

1.Launch Storage Explorer
2.Expand Blob container
3.Select a file inside container
4.Click on Download
5.Select destination folder

### Actual Experience

AzCopy not working when downloading files from Blob. A UnexpectedQuit message appears

### Expected Experience

Download file to local drive

**Comment by JasonYeMSFT** [comment]
Usually this indicates that AzCopy exe crashed during the transfer. Could you try to find the AzCopy logs for the failed transfer and share it with us? The logs already have your credentials (e.g. SAS token, key, etc.) redacted. It should be under ~/.azcopy? If it's too hard to find the logs for that job, you can reproduce the problem and grab the latest created folder.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue, we recommend opening a support ticket via the Azure portal. Alternatively you can open a new issue here.
