### ISSUE TITLE
Fail to add a key-value when setting '%' as the key

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6886]
**Storage Explorer Version**: 1.29.1
**Build Number**: 20230509.5
**Branch**: hotfix/1.29.1
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture**: ia32/x64/arm64
**App configuration version:** 0.2.0
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand 'App Configurations' node -> Open one app configuration.
2. Click 'Add' -> Type '%' into the 'Key' field.
3. Click 'Add'.
4. Check whether succeeds to add the key-value.

## Expected Experience ##
Succeed to add the key-value.

## Actual Experience ##
Fail to add the key-value.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/b98a6704-b121-4eaa-9c6e-367a260b117f)

**Comment by JasonYeMSFT** [comment]
I added the new validation rules to the Add Key-value dialog

**Comment by v-xianya** [comment]
Verified this issue using the new extension build. Fixed. So, we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/6dc1e752-b731-4fd1-95cb-d725dee6eab2)
