### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by ksabi09** [microsoft/AzureStorageExplorer#6889]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.29.1

### Architecture

i86

### Platform

Windows

### Bug Description

This request is not authorized to perform this operation.

This storage account's 'Firewalls & virtual networks' settings may be blocking access to storage services. Try adding your client IP address to the firewall exceptions, or by allowing access from 'all networks' instead of 'selected networks'. To learn more about Azure Storage firewalls and virtual networks, visit http://go.microsoft.com/fwlink/?LinkId=845443.

Error Details:
{
  "name": "RestError",
  "code": "AuthorizationPermissionMismatch",
  "statusCode": 403,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://covid09suks.blob.core.windows.net/?comp=list&include=metadata",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2021-10-04"
        },
        "accept": {
          "name": "Accept",
          "value": "application/xml"
        },
        "user-agent": {
          "name": "User-Agent",
          "value": "Microsoft Azure Storage Explorer/1.29.1 (win32) azsdk-js-storageblob/12.12.0 (NODE-VERSION v18.12.1; Windows_NT 10.0.19042)"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "28401360-a017-4d19-9179-fa06037a8727"
        },
        "authorization": {
          "name": "authorization",
          "value": "Bearer JSON Web Token Redacted"
        },
        "cookie": {
          "name": "Cookie",
          "value": ""
        }
      }
    },
    "withCredentials": false,
    "timeout": 0,
    "keepAlive": true,
    "decompressResponse": false,
    "requestId": "28401360-a017-4d19-9179-fa06037a8727"
  },
  "response": {
    "headers": {
      "_headersMap": {
        "content-length": {
          "name": "content-length",
          "value": "279"
        },
        "content-type": {
          "name": "content-type",
          "value": "application/xml"
        },
        "date": {
          "name": "date",
          "value": "Mon, 15 May 2023 10:37:36 GMT"
        },
        "server": {
          "name": "server",
          "value": "Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "28401360-a017-4d19-9179-fa06037a8727"
        },
        "x-ms-error-code": {
          "name": "x-ms-error-code",
          "value": "AuthorizationPermissionMismatch"
        },
        "x-ms-request-id": {
          "name": "x-ms-request-id",
          "value": "e502318e-d01e-0069-5219-8789d7000000"
        },
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2021-10-04"
        }
      }
    },
    "request": {
      "streamResponseStatusCodes": {},
      "url": "https://covid09suks.blob.core.windows.net/?comp=list&include=metadata",
      "method": "GET",
      "headers": {
        "_headersMap": {
          "x-ms-version": {
            "name": "x-ms-version",
            "value": "2021-10-04"
          },
          "accept": {
            "name": "Accept",
            "value": "application/xml"
          },
          "user-agent": {
            "name": "User-Agent",
            "value": "Microsoft Azure Storage Explorer/1.29.1 (win32) azsdk-js-storageblob/12.12.0 (NODE-VERSION v18.12.1; Windows_NT 10.0.19042)"
          },
          "x-ms-client-request-id": {
            "name": "x-ms-client-request-id",
            "value": "28401360-a017-4d19-9179-fa06037a8727"
          },
          "authorization": {
            "name": "authorization",
            "value": "Bearer JSON Web Token Redacted"
          },
          "cookie": {
            "name": "Cookie",
            "value": ""
          }
        }
      },
      "withCredentials": false,
      "timeout": 0,
      "keepAlive": true,
      "decompressResponse": false,
      "requestId": "28401360-a017-4d19-9179-fa06037a8727"
    },
    "status": 403,
    "bodyAsText": "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.\nRequestId:e502318e-d01e-0069-5219-8789d7000000\nTime:2023-05-15T10:37:37.6433086Z</Message></Error>",
    "parsedBody": {
      "message": "This request is not authorized to perform this operation using this permission.\nRequestId:e502318e-d01e-0069-5219-8789d7000000\nTime:2023-05-15T10:37:37.6433086Z",
      "code": "AuthorizationPermissionMismatch"
    },
    "parsedHeaders": {
      "errorCode": "AuthorizationPermissionMismatch",
      "content-length": "279",
      "content-type": "application/xml",
      "date": "Mon, 15 May 2023 10:37:36 GMT",
      "server": "Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0",
      "x-ms-client-request-id": "28401360-a017-4d19-9179-fa06037a8727",
      "x-ms-request-id": "e502318e-d01e-0069-5219-8789d7000000",
      "x-ms-version": "2021-10-04"
    }
  },
  "details": {
    "errorCode": "AuthorizationPermissionMismatch",
    "content-length": "279",
    "content-type": "application/xml",
    "date": "Mon, 15 May 2023 10:37:36 GMT",
    "server": "Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0",
    "x-ms-client-request-id": "28401360-a017-4d19-9179-fa06037a8727",
    "x-ms-request-id": "e502318e-d01e-0069-5219-8789d7000000",
    "x-ms-version": "2021-10-04",
    "message": "This request is not authorized to perform this operation using this permission.\nRequestId:e502318e-d01e-0069-5219-8789d7000000\nTime:2023-05-15T10:37:37.6433086Z",
    "code": "AuthorizationPermissionMismatch"
  }
}

### Steps to Reproduce

1. Launch explorer
2.  Expand container

### Actual Experience

This request is not authorized to perform this operation.

This storage account's 'Firewalls & virtual networks' settings may be blocking access to storage services. Try adding your client IP address to the firewall exceptions, or by allowing access from 'all networks' instead of 'selected networks'. To learn more about Azure Storage firewalls and virtual networks, visit http://go.microsoft.com/fwlink/?LinkId=845443.

Error Details:
{
  "name": "RestError",
  "code": "AuthorizationPermissionMismatch",
  "statusCode": 403,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://covid09suks.blob.core.windows.net/?comp=list&include=metadata",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2021-10-04"
        },
        "accept": {
          "name": "Accept",
          "value": "application/xml"
        },
        "user-agent": {
          "name": "User-Agent",
          "value": "Microsoft Azure Storage Explorer/1.29.1 (win32) azsdk-js-storageblob/12.12.0 (NODE-VERSION v18.12.1; Windows_NT 10.0.19042)"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "28401360-a017-4d19-9179-fa06037a8727"
        },
        "authorization": {
          "name": "authorization",
          "value": "Bearer JSON Web Token Redacted"
        },
        "cookie": {
          "name": "Cookie",
          "value": ""
        }
      }
    },
    "withCredentials": false,
    "timeout": 0,
    "keepAlive": true,
    "decompressResponse": false,
    "requestId": "28401360-a017-4d19-9179-fa06037a8727"
  },
  "response": {
    "headers": {
      "_headersMap": {
        "content-length": {
          "name": "content-length",
          "value": "279"
        },
        "content-type": {
          "name": "content-type",
          "value": "application/xml"
        },
        "date": {
          "name": "date",
          "value": "Mon, 15 May 2023 10:37:36 GMT"
        },
        "server": {
          "name": "server",
          "value": "Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "28401360-a017-4d19-9179-fa06037a8727"
        },
        "x-ms-error-code": {
          "name": "x-ms-error-code",
          "value": "AuthorizationPermissionMismatch"
        },
        "x-ms-request-id": {
          "name": "x-ms-request-id",
          "value": "e502318e-d01e-0069-5219-8789d7000000"
        },
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2021-10-04"
        }
      }
    },
    "request": {
      "streamResponseStatusCodes": {},
      "url": "https://covid09suks.blob.core.windows.net/?comp=list&include=metadata",
      "method": "GET",
      "headers": {
        "_headersMap": {
          "x-ms-version": {
            "name": "x-ms-version",
            "value": "2021-10-04"
          },
          "accept": {
            "name": "Accept",
            "value": "application/xml"
          },
          "user-agent": {
            "name": "User-Agent",
            "value": "Microsoft Azure Storage Explorer/1.29.1 (win32) azsdk-js-storageblob/12.12.0 (NODE-VERSION v18.12.1; Windows_NT 10.0.19042)"
          },
          "x-ms-client-request-id": {
            "name": "x-ms-client-request-id",
            "value": "28401360-a017-4d19-9179-fa06037a8727"
          },
          "authorization": {
            "name": "authorization",
            "value": "Bearer JSON Web Token Redacted"
          },
          "cookie": {
            "name": "Cookie",
            "value": ""
          }
        }
      },
      "withCredentials": false,
      "timeout": 0,
      "keepAlive": true,
      "decompressResponse": false,
      "requestId": "28401360-a017-4d19-9179-fa06037a8727"
    },
    "status": 403,
    "bodyAsText": "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.\nRequestId:e502318e-d01e-0069-5219-8789d7000000\nTime:2023-05-15T10:37:37.6433086Z</Message></Error>",
    "parsedBody": {
      "message": "This request is not authorized to perform this operation using this permission.\nRequestId:e502318e-d01e-0069-5219-8789d7000000\nTime:2023-05-15T10:37:37.6433086Z",
      "code": "AuthorizationPermissionMismatch"
    },
    "parsedHeaders": {
      "errorCode": "AuthorizationPermissionMismatch",
      "content-length": "279",
      "content-type": "application/xml",
      "date": "Mon, 15 May 2023 10:37:36 GMT",
      "server": "Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0",
      "x-ms-client-request-id": "28401360-a017-4d19-9179-fa06037a8727",
      "x-ms-request-id": "e502318e-d01e-0069-5219-8789d7000000",
      "x-ms-version": "2021-10-04"
    }
  },
  "details": {
    "errorCode": "AuthorizationPermissionMismatch",
    "content-length": "279",
    "content-type": "application/xml",
    "date": "Mon, 15 May 2023 10:37:36 GMT",
    "server": "Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0",
    "x-ms-client-request-id": "28401360-a017-4d19-9179-fa06037a8727",
    "x-ms-request-id": "e502318e-d01e-0069-5219-8789d7000000",
    "x-ms-version": "2021-10-04",
    "message": "This request is not authorized to perform this operation using this permission.\nRequestId:e502318e-d01e-0069-5219-8789d7000000\nTime:2023-05-15T10:37:37.6433086Z",
    "code": "AuthorizationPermissionMismatch"
  }
}
!
<img width="504" alt="Capture" src="https://github.com/microsoft/AzureStorageExplorer/assets/133653289/7301a303-526c-49b0-86bc-7c3445d135f2">

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue, we recommend opening a support ticket via the Azure portal. Alternatively you can open a new issue here.

**Comment by frevds** [comment]
I have just successfully solved the issue "This request is not authorized to perform this operation using this permission." by **correcting the computer time** (was using a VM with time slightly off by being 20min back, which causes tokens not to validate).
