### ISSUE TITLE
Explorer not working after update

### ISSUE THREAD

**Issue by sw-ms-pradipbaria** [microsoft/AzureStorageExplorer#689]
**1.4.2**: 
**Windows 7**: 
**X64**: 
**Yes**: 

#### Steps to Reproduce: ####
Not able to connect to storage account after upgrading to the latest version. Already tried with re install of application, re login into account management.

**Comment by radmint** [comment]
Still experiencing this issue:
![image](https://user-images.githubusercontent.com/23347804/46095342-1d30c200-c171-11e8-8c74-6ffaf1f7913c.png)
![image](https://user-images.githubusercontent.com/23347804/46095369-30439200-c171-11e8-8d57-768a0bd7e2d1.png)

**Comment by jinglouMSFT** [comment]
How do you connect to your storage?  Sign-in or SAS connections?  Also, what was the version you used before the upgrade?  If this is blocking you, you can still download 1.4.0 from the storageexplorer.com. Go to the bottom of that page and there is link to the old build.

**Comment by sw-ms-pradipbaria** [comment]
@radmint, @tmutton Current workaround is downgrade to previous version as mentioned by @jinglouMSFT

**Comment by MRayermannMSFT** [comment]
@radmint, @tmutton @sw-ms-pradipbaria 

Are any of y'all still having issues?

**Comment by sw-ms-pradipbaria** [comment]
It is working fine with newer version(s), closing it.
