### ISSUE TITLE
There is a failed activity log when running Directory Statistics for a folder whose name contains a trailing dot and the setting "Disable file share trailing dot support" is checked

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6891]
**Storage Explorer Version**: 1.30.0-dev
**Build Number**: 20230516.9
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture**: x64/arm64
**How Found**: Exploratory testing
**Regression From**: Previous release (1.29.1)

## Steps to Reproduce ##
  1. Open Settings -> Make sure the setting 'Disable File Share Trailing Dot Support' is unchecked.
  2. Expand one storage account -> File Shares.
  3. Create a file share -> Create a folder named 'f1.'.
  4. Check the setting 'Disable File Share Trailing Dot Support'.
  5. Click 'Directory Statistics'.
  6. Check whether there is a successful activity log.
  
## Expected Experience ##
There is a successful activity log.

## Actual Experience ##
There is a failed activity log.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/8df5f77d-36e8-48ab-8003-1d5046dda556)

Error details:
`Failed to inspect 'f1.', error: {
  "name": "RestError",
  "message": "The specified resource does not exist.\nRequestId:a7f5d1a7-101a-0032-5869-88e4f3000000\nTime:2023-05-17T02:41:02.5425564Z",`
## Additional Context ##
This issue also reproduces for 'Selection Statistics'.

**Comment by richardMSFT** [comment]
After investigating, this behavior is by design. This is because Directory Statistics needs to list all the files in the directory and if trailing dot support is disabled and there is a file in the directory that has a trailing dot, the failure is expected. The azure file sdk will not be able to find the resource because the trailing dot will have been trimmed.

**Comment by richardMSFT** [comment]
I am reopening this issue, because we have decided that listing should always support trailing dot.

**Comment by v-xianya** [comment]
@richardMSFT Verified this issue on the latest rel build, the current behavior keeps the same as the Actual Experience in issues. Could you help to have a look?

**Comment by richardMSFT** [comment]
My apologies. The package-lock wasn't properly updated. The most recent build should reflect the expected experience now.

**Comment by v-xianya** [comment]
Verified this issue on the build 20230609.2. Fixed.
There is a successful activity log on the scenarios.
