### ISSUE TITLE
Fail to paste one file from a file share to a SAS attached blob container with permissions 'Read, List, Create'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6894]
**Storage Explorer Version**: 1.30.0-dev
**Build Number**: 20230518.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture**: x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
  1. Expand one storage account -> Blob Containers.
  2. Create a blob container -> Attach the blob container via SAS URL with permissions 'Read, List, Create'.
  3. Open one file share -> Copy one file.
  4. Go to the attached blob container -> Click 'Paste'.
  5. Check whether succeeds to paste the file.
  
## Expected Experience ##
Succeed to paste the file.

## Actual Experience ##
Fail to paste the file.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/8eb40bb8-f8f9-4fbc-bed0-de708e1aad65)

Error:
`{
  "message": "\"UnexpectedCancel\""
}`

## Additional Context ##
This issue also reproduces when pasting one file to attached ADLS Gen2 blob containers.

**Comment by MRayermannMSFT** [comment]
- When copying from a blob container to the attached blob container, scenario works, so long as block size is minimized.
- When copying from a file share to the attached blob container, scenario doesn't work, even when block size is minimized.

**Comment by MRayermannMSFT** [comment]
This will likely require reporting an issue against AzCopy.

**Comment by MRayermannMSFT** [comment]
Issue opened, moving this to a backlog milestone for now: https://github.com/Azure/azure-storage-azcopy/issues/2234

**Comment by MRayermannMSFT** [comment]
@v-xianya can you see if this still repros on main?

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT Verified this issue on the main build 20230731.1. this issue does not reproduce.
So, we are going to close this issue.
