### ISSUE TITLE
The context view shows as blank if the string on the address bar got changed for one Azure AD attached regular folder

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6898]
**Storage Explorer Version**: 1.30.0-dev
**Build Number**: 20230519.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
  1. Expand one storage account -> Blob Containers.
  2. Create a blob container and assigned a RBAC role 'Storage Blob Data Owner' to it.
  3. Go to the blob container -> Create a folder -> Upload one blob to the folder.
  4. Right click the folder -> Click 'Copy URL'.
  5. Open connect dialog -> Click 'Blob container or directory -> Sign in using Azure Active Directory (Azure AD)'.
  6. Attach the folder via Azure AD.
  7. Go to the attached folder -> Right click the blob -> Click 'Manage History -> Manage Versions'.
  8. Observe whether the context view shows well.
  
## Expected Experience ##
The context view shows well.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/b5f63675-1ab3-46f4-bace-493dd6107f60)

## Actual Experience ##
The context view shows as blank.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/39e1da0d-74db-4bc8-8d72-ffe79cf6a392)

## Addition Context ##
1. This issue reproduces with RBAC role 'Storage Blob Data Contributor'.
2. This issue reproduces when clicking 'Manage History -> Manage Snapshots'/creating a new folder/running filter by prefix/tag query.

**Comment by v-xianya** [comment]
Update: This issue also reproduces for a Public connect regular folder.

**Comment by JasonYeMSFT** [comment]
This should have been fixed in main.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230524.4. Fixed. So, we are going to close.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/c45e69e5-aec6-412b-ada4-1753bd7802be)
