### ISSUE TITLE
Security warning:  This file is potentially unsafe.  Are you sure you want to open it?

### ISSUE THREAD

**Issue by rhweaver50** [microsoft/AzureStorageExplorer#690]
**Storage Explorer Version**: 1.4.2
**Platform/OS Version**:  Windows
**Architecture**: ia32
**Build Number**: 20180917.1
**Regression From**: N/A

#### Steps to Reproduce: ####
Message is displayed when a file is downloaded from Storage Explorer to a desktop/laptop PC running Windows 10.

#### Expected Experience: ####
Storage Explorer configuration setting (in Settings) to turn this message ON or OFF for all file types or perhaps selected file types.

#### Actual Experience: ####
Message requires an "Yes" or "No" response requiring an extra click to down-load file.

**Comment by neilrees** [comment]
_Every single time_ I get that dialog I come back here to see if there's been any progress...

**Comment by craxal** [comment]
Duplicate of #164.
