### ISSUE TITLE
'Shift+click' action does not work across pages on the tabular preview tab

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6900]
**Storage Explorer Version:** 1.30.0-dev
**Build Number:** 20230519.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture:** x64/arm64
**How Found:** Exploratory testing
**Regression From:** Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Open one blob container -> Upload a csv blob which contains more than 100 items. (Make sure its content type is text/csv)
3. Right click the blob -> Click 'Preview'.
4. The tabular preview tab opens -> Click an item.
5. Navigate to page 2 -> Shift+click an item.
6. Check whether both items and all items in between are selected.

## Expected Experience ##
Both items and all items in between are selected.

## Actual Experience ##
Only the item on page 2 is selected.

**Comment by craxal** [comment]
@v-kellyluo When you say "only the item on page 2 is selected", what exactly are you seeing that indicates it is selected? Can you provide a screenshot please?

This is not a bug. Item selection is currently not allowed in tabular preview.

Range selection in the data grid has already been fixed (see #6841).

We have added row copy to tabular previews (see #6838), but the extension version update has yet to be built (waiting on a few more changes).

**Comment by v-kellyluo** [comment]
Hi @craxal , here is the record:
After navigating to page 2, Shift+click an item, only the item on page 2 is selected.
![tabular](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/df397249-24cd-4c1e-937c-5b5b76f376a8)

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20230527.2. Fixed. So, we are going to close it.
