### ISSUE TITLE
The strings 'Filter by Keys' and 'Filter by Labels' are localized incorrectly in the App Configuration explorer

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6902]
**Storage Explorer Version:** 1.30.0-dev
**Build Number:** 20230521.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Reproduce Languages:** All languages
**Architecture:** x64/arm64
**App configuration version:** 0.2.0
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select 'Français' -> Restart Storage Explorer.
3. Expand 'App Configurations' node -> Open one app configuration.
4. Check whether the strings 'Filter by Keys' and 'Filter by Labels' are localized correctly.

## Expected Experience ##
The strings 'Filter by Keys' and 'Filter by Labels' are localized correctly.
The screenshot in ENU:
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/53d5f1ca-be02-4e2a-be80-27866084eec5)

## Actual Experience ##
The strings 'Filter by Keys' and 'Filter by Labels' are localized incorrectly.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/bb5f5fe0-040c-4889-b2d1-fb4616e53341)

**Comment by JasonYeMSFT** [comment]
I will track all the app config localization related issues in its own repo.
