### ISSUE TITLE
‘Show/Hide All Subscriptions‘ strings are not localized on the ‘ACCOUNT MANAGEMENT’ panel

### ISSUE THREAD

**Issue by v-sunnsun** [microsoft/AzureStorageExplorer#6903]
**Storage Explorer Version**: 1.30.0-dev
**Build Number**: 20230521.1
**Branch**: main
**Platform/OS**:  Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Reproduce Language**: All languages
**Architecture**: x64/arm64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce 

1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select 'Français' -> Restart Storage Explorer.
3. Switch to ‘ACCOUNT MANAGEMENT’ panel.
4. Click the gear icon.
5. Check whether all strings are localized.

## Expected Experience 
All strings are localized.

## Actual Experience
'Show/Hide All Subscriptions' strings are not localized.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/122582307/ec61010b-fcec-4aa5-821c-944024603840)

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230526.3. Fixed on all languages.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/9bf8cb34-2413-4bf7-b3d0-a1a097921138)
