### ISSUE TITLE
The string 'Copy Direct Link' is not localized on the context menu for one regular blob

### ISSUE THREAD

**Issue by v-sunnsun** [microsoft/AzureStorageExplorer#6904]
**Storage Explorer Version**: 1.30.0-dev
**Build Number**: 20230521.1
**Branch**: main
**Platform/OS**:  Windows 10/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Reproduce Language**: All languages
**Architecture**: x64/arm64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce 

1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select 'Français' -> Restart Storage Explorer.
3. Expand one storage account -> Blob Containers.
4. Open one blob container -> Select one blob then right click it -> The context menu displays.
5. Check whether the string 'Copy Direct Link' is localized.

## Expected Experience 
The string 'Copy Direct Link' is localized.

## Actual Experience
The string 'Copy Direct Link' is not localized.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/122582307/d6da792d-ec80-4b9f-a261-fb2eb6b12dcd)

**Comment by JasonYeMSFT** [comment]
This string is localized now.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230603.6. Fixed.
