### ISSUE TITLE
The 'Preserve Blob Tags' part is not localized on the Settings panel

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6905]
**Storage Explorer Version:** 1.30.0-dev
**Build Number:** 20230521.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Reproduce Languages:** All languages
**Architecture:** x64/arm64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select 'Français' -> Restart Storage Explorer.
3. Open Settings -> Click 'Transfer'.
4. Check whether the 'Preserve Blob Tags' part is localized.

## Expected Experience ##
The 'Preserve Blob Tags' part is localized.

## Actual Experience ##
The 'Preserve Blob Tags' part is not localized.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/8bc01411-7dd8-4fde-8068-c0b41ccbe708)

**Comment by JasonYeMSFT** [comment]
This string is localized now.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230603.6. Fixed.
