### ISSUE TITLE
The string 'Advanced Options' is not localized under the query builder

### ISSUE THREAD

**Issue by v-sunnsun** [microsoft/AzureStorageExplorer#6906]
**Storage Explorer Version**: 1.30.0-dev
**Build Number**: 20230521.1
**Branch**: main
**Platform/OS**:  Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Reproduce Language**: All languages
**Architecture**: x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce 

1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select 'Français' -> Restart Storage Explorer.
3. Expand one storage account -> Tables.
4. Create a table -> Click 'Query'.
5. Check whether the string 'Advanced Options' is localized.

## Expected Experience 
The string 'Advanced Options' is localized.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/122582307/c01c746e-be49-4057-9870-48a400c6b2c7)

## Actual Experience
The string 'Advanced Options' is not localized.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/122582307/908d5297-d402-42d1-b568-f5159dcd770f)

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230526.3. Reproduce.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/9329282d-374a-44eb-a77b-ae6f8c1df895)
