### ISSUE TITLE
Cannot re-authenticate ASE

### ISSUE THREAD

**Issue by NguyeHe4** [microsoft/AzureStorageExplorer#6907]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.29.1

### Architecture

x64

### Storage Explorer Build Number

20230509.5

### Platform

Windows

### OS Version

Windows 10

### Bug Description

{
  "name": null,
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"self signed certificate in certificate chain\\\",\\n  \\\"stack\\\": \\\"Error: self signed certificate in certificate chain\\\\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1538:34)\\\\n    at TLSSocket.emit (node:events:513:28)\\\\n    at TLSSocket._finishInit (node:_tls_wrap:952:8)\\\\n    at ssl.onhandshakedone (node:_tls_wrap:733:12)\\\",\\n  \\\"code\\\": \\\"SELF_SIGNED_CERT_IN_CHAIN\\\"\\n}\""
}

### Steps to Reproduce

1. Launch ASE
2. ASE wants re-authentication --> finished that
3. browser says authenticated but ASE still requires authentication

### Actual Experience

ASE installed was old. I tried to download the mentioned version and re-authenticate, but I wasn't able to.

**Comment by MRayermannMSFT** [comment]
Please try enabling system proxy: https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview
