### ISSUE TITLE
Fail to import one .csv file that contains one empty Partitionkey/RowKey to a table with option 'Auto-generate empty or missing keys' unchecked

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6908]
**Storage Explorer Version**: 1.29.1
**Build Number**: 20230522.3
**Branch**: dev/cralvord/bug/cache-fill
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture**: x64/arm64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Click 'Import' -> Select one .csv file. Like:
[table1.csv](https://github.com/microsoft/AzureStorageExplorer/files/11541235/table1.csv)
3. Uncheck the option 'Auto-generate empty or missing keys'.
4. Click 'Import'.
5. Check whether succeeds to import the csv file.
  
## Expected Experience ##
Succeed to import the csv file.

## Actual Experience ##
Fail to import the csv file.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/35d4722d-cd82-4d3e-aa82-68607c5734aa)

**_Error Details:_**
`  "message": "Unable to convert working entity to SDK entity without a partition key.",`
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/df551378-23de-47dc-bd14-07ad1ee64118)

**Comment by craxal** [comment]
@v-xianya Is the "Ignore empty string values" option checked? Does unchecking that option result in a successful import?

**Comment by v-xianya** [comment]
@craxal Succeed to execute import when uncheck the option 'ignore empty string values".

Also, any update for the question?
•	If type new name for one PartitionKey or RowKey whose value is empty on Import Entities dialog (Option 'Auto-generate empty or missing keys’ is checked),
The new name property doesn’t display on the table. Is this expected?

**Comment by craxal** [comment]
@v-xianya I will answer the question through the email thread, as it's not part of this issue.
