### ISSUE TITLE
Cannot rename a file that contains a comma in the name

### ISSUE THREAD

**Issue by jcookems** [microsoft/AzureStorageExplorer#6911]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.29.1

### Regression From

Unknown

### Architecture

i86

### Storage Explorer Build Number

20230509.5 (Let me copy from the About dialog!)

### Platform

Windows

### OS Version

Win 10

### Bug Description

Trying to rename a file in ADL Gen2, but get an error. I suspect it is due to the comma in the file name:
DBSnap/Runtime_Sites/2023/05/23/2023-05-22_2032_08-waws-prod-j,.tsv

### Steps to Reproduce

1. Get a file named "DBSnap/Runtime_Sites/2023/05/23/2023-05-22_2032_08-waws-prod-j,.tsv"into an ADL gen 2 container.
2. Try to rename using AzureStorageExplorer

### Actual Experience

Get an error saying "Failed to rename ..."
```
{
  "name": "RestError",
  "message": "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:1a8c2608-701f-002b-2dd1-8d283b000000\nTime:2023-05-23T23:52:51.2238076Z",
...
```

### Expected Experience

Expect: Successfully rename the file

**Comment by JasonYeMSFT** [comment]
I created such a file and attempted to rename it to "helloworld" and it worked. What's the new name you were trying to rename to?

**Comment by jcookems** [comment]
After further investigation, it looks like the comma is not the issue
1. Connect to an ADLS Gen 2 container using a SAS token with RWLD
2. Attempt to rename any file (such as https://XXX.blob.core.windows.net/sharedscripts/user/jcooke/test.txt)

Does ADLS Gen 2 require additional SAS permissions to rename? 
```
    "error": {
      "code": "AuthenticationFailed",
      "message": "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:4909eed4-c01f-0073-112c-8ff064000000\nTime:2023-05-25T17:15:31.2239091Z",
      "detail": {
        "AuthenticationErrorDetail": "The version specified by the SignedVersion (sv) query parameter is not valid for this operation."
      }
```
The *sv* I'm using is old, but almost everything else works in ASE
```
    "url": "https://XXX.dfs.core.windows.net/sharedscripts/user/jcooke/test2.txt?sv=2018-03-28&sr=c&SAS Token Redacted&se=2023-05-29T22%3A09%3A09Z&sp=rwdl&mode=legacy",
```

Did the top-level error message send me down the wrong path?

Perhaps the real issue here is that ASE should crack apart the enormous JSON blob and expose the *important* parts to the user. There is a lot of space between "Failed to rename 'user/jcooke/test.txt' to 'test2.txt'" and the raw 6k line, 200kB JSON mess that is in the "Details..." link.

**Comment by JasonYeMSFT** [comment]
The error indicates the "rename" operation, aka. Path Create API, isn't supported in the service version specified by your SAS token (2018-03-28). The service requires higher service versions for newer APIs while supporting older APIs with older service versions. Could you try regenerating SAS with a higher service version? A rename operation basically needs the read permission on the source and the write permission on the destination. Your SAS permissions should already have both of them.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you're still encountering this issue, we recommend opening a support ticket via the Azure Portal. Alternatively you can open a new issue here.
