### ISSUE TITLE
Unable to retrieve child resources.

### ISSUE THREAD

**Issue by sofialexmc** [microsoft/AzureStorageExplorer#6914]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.20.0

### Architecture

i86

### Storage Explorer Build Number

20210625.5

### Platform

Windows

### OS Version

windows server 2012 r2

### Bug Description

[error_storage_key.txt](https://github.com/microsoft/AzureStorageExplorer/files/11554743/error_storage_key.txt)

### Steps to Reproduce

1. se agrega storage mediante el key.
2. se expande el storage y despues de un rato, aparece el msj de error.
![error_storage_key](https://github.com/microsoft/AzureStorageExplorer/assets/108024382/fb1abd63-44f7-4945-ae36-b890ee410366)

### Actual Experience

![error_storage_key](https://github.com/microsoft/AzureStorageExplorer/assets/108024382/ecf270be-100a-4c76-a041-cea6eebc3b39)

**Comment by JasonYeMSFT** [comment]
1.20.0 is out of support https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-support-policy-lifecycle. Could you try upgrading to the latest version? If you can upgrade, try setting the proxy setting to be "use system proxy" and see if it resolves your issue. If you cannot upgrade, check if you are using a proxy, set the proxy setting to "use app proxy settings" and enter the proxy info.

**Comment by MRayermannMSFT** [comment]
> windows server 2012 r2

Storage Explorer versions 1.28 and newer do not support Windows server 2012. The neweset version you can use is https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.27.2 .

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you still require assistance, we recommend that you open a support ticket via the Azure Portal. Alternatively you can open a new issue here.
