### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by NayanaDesh** [microsoft/AzureStorageExplorer#6916]
We have created storage account in Azure with option for Public Network access "Enabled from Selected Virtual Network and IP Addresses" and "Disabled."

we have created Private Endpoint and also added CIDR Range.
We are still getting below issue while accessing storage account(using connection string) in Azure Storage Explorer.
--------------------
This request is not authorized to perform this operation.

This storage account's 'Firewalls & virtual networks' settings may be blocking access to storage services. Try adding your client IP address to the firewall exceptions, or by allowing access from 'all networks' instead of 'selected networks'. To learn more about Azure Storage firewalls and virtual networks, visit http://go.microsoft.com/fwlink/?LinkId=845443.

Error Details:
{
  "name": "RestError",
  "code": "AuthorizationFailure",
  "statusCode": 403,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://strgpvtendpoint.blob.core.windows.net/?sv=2022-11-02&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2023-10-31T16:58:37Z&st=2023-05-25T08:58:37Z&spr=https&SAS Token Redacted&comp=list&include=metadata",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2021-10-04"
        },
        "accept": {
          "name": "Accept",
          "value": "application/xml"
        },
        "user-agent": {
          "name": "User-Agent",
          "value": "Microsoft Azure Storage Explorer/1.29.1 (win32) azsdk-js-storageblob/12.12.0 (NODE-VERSION v18.12.1; Windows_NT 10.0.19045)"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "073bdb4b-4798-4264-9156-8983adc884d6"
        },
        "cookie": {
          "name": "Cookie",
          "value": ""
        }
      }
    },
    "withCredentials": false,
    "timeout": 0,
    "keepAlive": true,
    "decompressResponse": false,
    "requestId": "073bdb4b-4798-4264-9156-8983adc884d6"
  },
  "response": {
    "headers": {
      "_headersMap": {
        "content-length": {
          "name": "content-length",
          "value": "246"
        },
        "content-type": {
          "name": "content-type",
          "value": "application/xml"
        },
        "date": {
          "name": "date",
          "value": "Thu, 25 May 2023 08:59:11 GMT"
        },
        "server": {
          "name": "server",
          "value": "Microsoft-HTTPAPI/2.0"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "073bdb4b-4798-4264-9156-8983adc884d6"
        },
        "x-ms-error-code": {
          "name": "x-ms-error-code",
          "value": "AuthorizationFailure"
        },
        "x-ms-request-id": {
          "name": "x-ms-request-id",
          "value": "7d288093-301e-0061-1ae7-8e6644000000"
        }
      }
    },
    "request": {
      "streamResponseStatusCodes": {},
      "url": "https://strgpvtendpoint.blob.core.windows.net/?sv=2022-11-02&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2023-10-31T16:58:37Z&st=2023-05-25T08:58:37Z&spr=https&SAS Token Redacted&comp=list&include=metadata",
      "method": "GET",
      "headers": {
        "_headersMap": {
          "x-ms-version": {
            "name": "x-ms-version",
            "value": "2021-10-04"
          },
          "accept": {
            "name": "Accept",
            "value": "application/xml"
          },
          "user-agent": {
            "name": "User-Agent",
            "value": "Microsoft Azure Storage Explorer/1.29.1 (win32) azsdk-js-storageblob/12.12.0 (NODE-VERSION v18.12.1; Windows_NT 10.0.19045)"
          },
          "x-ms-client-request-id": {
            "name": "x-ms-client-request-id",
            "value": "073bdb4b-4798-4264-9156-8983adc884d6"
          },
          "cookie": {
            "name": "Cookie",
            "value": ""
          }
        }
      },
      "withCredentials": false,
      "timeout": 0,
      "keepAlive": true,
      "decompressResponse": false,
      "requestId": "073bdb4b-4798-4264-9156-8983adc884d6"
    },
    "status": 403,
    "bodyAsText": "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.\nRequestId:7d288093-301e-0061-1ae7-8e6644000000\nTime:2023-05-25T08:59:12.1943090Z</Message></Error>",
    "parsedBody": {
      "message": "This request is not authorized to perform this operation.\nRequestId:7d288093-301e-0061-1ae7-8e6644000000\nTime:2023-05-25T08:59:12.1943090Z",
      "code": "AuthorizationFailure"
    },
    "parsedHeaders": {
      "errorCode": "AuthorizationFailure",
      "content-length": "246",
      "content-type": "application/xml",
      "date": "Thu, 25 May 2023 08:59:11 GMT",
      "server": "Microsoft-HTTPAPI/2.0",
      "x-ms-client-request-id": "073bdb4b-4798-4264-9156-8983adc884d6",
      "x-ms-request-id": "7d288093-301e-0061-1ae7-8e6644000000"
    }
  },
  "details": {
    "errorCode": "AuthorizationFailure",
    "content-length": "246",
    "content-type": "application/xml",
    "date": "Thu, 25 May 2023 08:59:11 GMT",
    "server": "Microsoft-HTTPAPI/2.0",
    "x-ms-client-request-id": "073bdb4b-4798-4264-9156-8983adc884d6",
    "x-ms-request-id": "7d288093-301e-0061-1ae7-8e6644000000",
    "message": "This request is not authorized to perform this operation.\nRequestId:7d288093-301e-0061-1ae7-8e6644000000\nTime:2023-05-25T08:59:12.1943090Z",
    "code": "AuthorizationFailure"
  }
}

**Comment by JasonYeMSFT** [comment]
On which machine were you running Storage Explorer? It might not be on the VNet that can resolve the private link. Could you try Azure Portal and see if you can access your storage account from there?

**Comment by tommyle225** [comment]
Following. I'm experiencing the same issue.  I have an Azure File Storage with private endpoints and disabled public access.  I'm trying to access the Azure File Storage using SAS URL in Storage Explorer and getting the error below.

Unable to retrieve child resources

ProducerError:{
  "name": "RestError",
  "message": "This request is not authorized to perform this operation.\nRequestId:602a5931-201a-00d9-2402-9b6040000000\nTime:2023-06-09T18:47:14.0582010Z",
  "stack": "RestError: This request is not authorized to perform this operation.\nRequestId:602a5931-201a-00d9-2402-9b6040000000\nTime:2023-06-09T18:47:14.0582010Z\n    at handleErrorResponse (C:\\Users\\xxxxxxxxx\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:166203)\n    at C:\\Users\\xxxxxxxxx\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:166887\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async StorageRetryPolicy.attemptSendRequest (C:\\Users\\xxxxxxxxx\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:383899)\n    at async StorageClientContext.sendOperationRequest (C:\\Users\\xxxxxxxxx\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:205004)\n    at async ShareServiceClient.listSharesSegment (C:\\Users\\xxxxxxxxx\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:451999)",
  "code": "AuthorizationFailure",
  "statusCode": 403,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://testiplafilestorage.file.core.windows.net/?sv=2022-11-02&ss=f&srt=sco&sp=rwdlc&se=2023-06-10T02:42:53Z&st=2023-06-09T18:42:53Z&spr=https&SAS Token Redacted&comp=list",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2021-10-04"
        },
        "accept": {
          "name": "Accept",
          "value": "application/xml"
        },
        "user-agent": {
          "name": "User-Agent",
          "value": "Microsoft Azure Storage Explorer/1.29.1 (win32) azsdk-js-storagefile/12.12.0 (NODE-VERSION v18.12.1; Windows_NT 10.0.22621)"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "b20869c2-f994-4835-b823-8204e1cefd1c"
        },
        "cookie": {
          "name": "Cookie",
          "value": ""
        }
      }
    },
    "withCredentials": false,
    "timeout": 0,
    "keepAlive": true,
    "decompressResponse": false,
    "requestId": "b20869c2-f994-4835-b823-8204e1cefd1c",
    "operationSpec": {
      "path": "/",
      "httpMethod": "GET",
      "responses": {
        "200": {
          "bodyMapper": {
            "serializedName": "ListSharesResponse",
            "xmlName": "EnumerationResults",
            "type": {
              "name": "Composite",
              "className": "ListSharesResponse",

**Comment by MRayermannMSFT** [comment]
@tommyle225 your account's 'Firewalls & virtual networks' settings may be blocking access to your file share. Can you try adding your client IP address to the firewall exceptions, or by allowing access from 'all networks' instead of 'selected networks'. To learn more about Azure Storage firewalls and virtual networks, visit http://go.microsoft.com/fwlink/?LinkId=845443.
