### ISSUE TITLE
Fail to download a blob version without current version by using 'Download' on 'Open Direct Link' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6917]
**Storage Explorer Version**: 1.30.0-dev
**Build Number**: 20230525.5
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4 (Apple M1 Pro)
**Architecture**: x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers (make sure the blob versioning is enabled and RBAC role 'Storage Blob Data Owner' has been assigned).
2. Create a blob container -> Upload one blob -> Delete the blob to generate a blob version.
3. Switch to 'All blobs and blobs without current version' -> Right click the version -> Click 'Copy Direct Link'.
4. Open the direct link from browser.
5. There is an 'Open Direct Link' dialog -> Click 'Download'.
6. Select the azure account -> Click 'Next' -> Click 'Finish'.
7. Select one folder to download.
8. Check whether succeeds to download the blob version.
  
## Expected Experience ##
Succeed to download the blob version.
  
## Actual Experience ##
Fail to download the blob version.
  
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/0fcd9a13-4603-47ea-9312-9c78cb4b1e9d)

**Details:**
`{
  "message": "\"failed to perform copy command due to error: failed to initialize enumerator: The specified file was not found.\""
}`
## Additional Context ##
1. This issue doesn't reproduce if the current version exists.
2. This issue also reproduces for rbac role 'Storage Blob Data Contributor' (It has nothing to do with the role is assigned on storage account level or container level).

**Comment by JasonYeMSFT** [comment]
The direct link doesn't support blob version. I will disable the action when selecting blob versions.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230527.2. The 'Copy Direct Link' action is disabled for blob versions/snapshots.
So, we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/5b56a4aa-6347-4d6c-9560-42861f4a45a7)
