### ISSUE TITLE
Seconds not shown when filtering using UTC date range

### ISSUE THREAD

**Issue by sixeyes** [microsoft/AzureStorageExplorer#6918]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.29.2

### Regression From

1.28.1

### Architecture

i86

### Storage Explorer Build Number

20230523.19

### Platform

All

### OS Version

Windows 10

### Bug Description

When applying a filter to a storage table, if requesting a date range, when using UTC the seconds are gone.

If you use a local date range the seconds are there.

In v1.28.1 and earlier the seconds were always available whether you specified a local or UTC date range.

### Steps to Reproduce

1. Open Azure Storage Explorer
2. Select a Storage Account
3. Expand Tables
4. Open a table
5. Click on query builder
6. Add new clause
7. Choose Timestamp
8. Click "Last 7 days"
9. Click "Custom..."
10. In Custom Timestamp Query click Range, UTC, OK
11. Dates added to the filter do not contain seconds

### Actual Experience

![image](https://github.com/microsoft/AzureStorageExplorer/assets/604902/aabfcb3c-bbd7-41dd-bb2a-a8d3812e9ab9)

### Expected Experience

![image](https://github.com/microsoft/AzureStorageExplorer/assets/604902/21f2d93f-d075-4e4c-9db5-07646f64741b)

**Comment by craxal** [comment]
@sixeyes I notice that when switching to timezones to or from UTC, the timestamp dialog sets the seconds to zero. But if I manually change the seconds to a non-zero, the seconds show up. Is this the same for you? Does the previous version not reset the seconds? If you switch to the query editor, does your query string contain the seconds and fractional seconds as expected?

**Comment by craxal** [comment]
It looks like we are trimming off the seconds when we convert between local and UTC. I'm not sure why we do that. I'll do some more digging and see about getting a fix for this.

**Comment by sixeyes** [comment]
OK, but that's not the only issue.

If you actually want 00 seconds, the seconds disappear so you can't change your mind later.
I thought it was a UTC issue but it's actually a 00 seconds issue

**Comment by craxal** [comment]
@sixeyes It looks like that can be rectified by adding a `step="1"` attribute to the input control.
