### ISSUE TITLE
'Right click' works when executing the actions from toolbar for all services

### ISSUE THREAD

**Issue by v-dantch** [microsoft/AzureStorageExplorer#692]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture**: ia32
**Build Number**: 20180924.1
**Commit**: 1a75b88f
**Regression From**: Not a Regression

#### Steps to Reproduce: ####
1. Open one blob editor.
2. Right click the actions from toolbar.
3. Check the result.

#### Expected Experience: ####
'Right click' doesn't work and nothing happens.

#### Actual Experience: ####
'Right click' works.

**Comment by MRayermannMSFT** [comment]
Won't fix.
