### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by serge-leb** [microsoft/AzureStorageExplorer#6920]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.29.2

### Regression From

1.13.1

### Architecture

i86

### Storage Explorer Build Number

20230523.19

### Platform

Windows

### OS Version

Win. 10 22H2

### Bug Description

I have had this working on my old laptop (Win.10 20H2) for years using Storage explorer 1.13.1 - It is a connection string configured storage account. Still connects and works fine.
Now trying to set this up on new laptop, using same connection string and seeing this error below
No proxy is used on old laptop connection, check same is configured on new storage explorer settings.

### Steps to Reproduce

Configure connection string connection, "Display name" is resolved.
Expand connection >Tables
Error is produce on pop-up

### Actual Experience

Unable to retrieve child resources

      }
    }
  }
}

### Additional Context

I have 2 laptops right next to each other, only difference I can see is the newer storage explorer version Vs older version. I must have to configure something else for newer one to work?

**Comment by JasonYeMSFT** [comment]
If I have to guess I think it's due to the API version change, could you capture two fiddler traces using the two versions and see what have changed in the requests that succeed in 1.13 but fail in 1.29? https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/storage-explorer-troubleshooting?tabs=Windows#network-logs

**Comment by serge-leb** [comment]
Thanks for the response,
Incorrect character in the key was the cause, this is now connecting on newer version.
