### ISSUE TITLE
It would be better to update 'Attach Container/Directory' to 'Attach to Container/Directory' on 'Open Direct Link' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6923]
**Storage Explorer Version**: 1.30.0-dev
**Build Number**: 20230526.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4 (Apple M1 Pro)
**Architecture**: x64/arm64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Right click it -> Click 'Copy Direct Link to Blob Container'.
3. Paste the link to browser to open storage explorer.
4. There is an 'Open Direct Link' dialog.
5. Observe the options on the dialog.
  
## Expected Experience ##
It would be better to update 'Attach Container' to 'Attach to Container'.
  
## Actual Experience ##
Show 'Attach Container' on the dialog.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/dd22049a-5e0e-49e3-b515-585a9a77d3d6)

## Additional Context ##
This issue also reproduces for 'Attach Directory' option.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/0c98e78e-72da-4665-b6d0-5c0961be0116)

**Comment by JasonYeMSFT** [comment]
This is a very minor change. Let's push to 1.31.0.

**Comment by JasonYeMSFT** [comment]
We had a discussion. Instead of adding the "to" to the title, we will remove the "to" from the description since "attach (the) container" is more precise than "attaching to container" in our scenario.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230815.5. Fixed. 
The "to" has been removed from the description. So, we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/b3381197-29eb-4b23-84ba-48faffc8d111)
