### ISSUE TITLE
Update 'when coping blobs' to 'when cloning blobs' in the description of the setting 'Preserve Blob Tags'

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6924]
**Storage Explorer Version:** 1.30.0-dev
**Build Number:** 20230526.3
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4 (Apple M1 Pro)
**Architecture:** x64/arm64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Launch Storage Explorer.
2. Open Settings -> Click 'Transfers'.
3. Observe the description of the setting 'Preserve Blob Tags'.

## Expected Experience ##
The description is 'when cloning blobs'.

## Actual Experience ##
The description is 'when coping blobs'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/0a904f72-0eb0-48ce-8789-053438baaf10)

## Additional Context ##
Related bug:[6390](https://github.com/microsoft/AzureStorageExplorer/issues/6390).

**Comment by MRayermannMSFT** [comment]
Perhaps do "when copying or cloning"?

**Comment by JasonYeMSFT** [comment]
Clone is a special kind of copy. Similar to how we refer to clone as copy in the copy to rehydrate scenario, I don't think we need to be too explicit in differentiating copy and clone.

**Comment by v-kellyluo** [comment]
Hi @JasonYeMSFT,  I understand your meaning, but Copy and Clone are two sperate actions, when copying blobs, the tags are not preserved, do we need to pay attention to it?

**Comment by v-kellyluo** [comment]
@JasonYeMSFT, verified this issue on the build 20230602.2, the tags will be preserved when coping blobs.
