### ISSUE TITLE
Columns in the previewed file are spaced widely when resizing one column

### ISSUE THREAD

**Issue by v-sunnsun** [microsoft/AzureStorageExplorer#6929]
**Storage Explorer Version**: 1.30.0-dev
**Build Number**: 20230527.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.4 (Apple M1 Pro)
**Architecture**:  x64/arm64
**How Found**: From running test case
**Regression From**:  Not a regression

## Steps to Reproduce 

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one .parquet file.
3. Right click the file -> Click 'Preview'.
4. Resize one column.
5. Check whether columns in the previewed file are spaced properly.

## Expected Experience 
Columns in the previewed file are spaced properly.

## Actual Experience ##
Columns in the previewed file are spaced widely.

## Additional Context ##

1. Here is the record:
![record](https://github.com/microsoft/AzureStorageExplorer/assets/122582307/f66c875e-d9ff-4f14-9318-24dc6aa5dd21)
2. This issue also reproduces for  .avro and .csv files.
3. This issue also reproduces for files under ADLS Gen2 blob containers/File Shares.

**Comment by craxal** [comment]
Oops, this was on me. I modified the data grid to send the new column size instead of the change in size, but I didn't update the preview code to take that change into account.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230531.3. Fixed.
