### ISSUE TITLE
Display a tedious message when opening blobs/files

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#693]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture**: ia32/x64
**Build Number**: 20180924.1
**Commit**: 1a75b88f
**Regression From**: Previous release 1.4.2(20180917.1)

#### Steps to Reproduce: ####
1. Open one blob container then upload a blob to it.
2. Try to open the uploaded blob -> Check the displayed message in Activities.

#### Expected Experience: ####
The tedious message disappears after opening the blob/file successfully.

#### Actual Experience: ####
Display a tedious message in Activities.
![tedious](https://user-images.githubusercontent.com/34729022/46002087-99a5a100-c09c-11e8-99a3-a753856e9673.png)

**Comment by v-xianya** [comment]
Feature change. The log message has been changed. So we close it.
![image](https://user-images.githubusercontent.com/41351993/71608009-d96d0980-2bb8-11ea-8d9f-2ab3cf1ca06f.png)
