### ISSUE TITLE
There is an extra action 'Copy Direct Link' for regular blobs/folders on Linux

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6930]
**Storage Explorer Version**: 1.30.0-dev
**Build Number**: 20230527.2
**Branch**: main
**Platform/OS**: Linux Ubuntu 20.04
**Architecture**: x64
**How Found**: From running test case
**Regression From**: Previous release (1.29.2)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Right click the blob.
4. Check whether there is no extra action 'Copy Direct Link'.
## Expected Experience ##
There is no extra action 'Copy Direct Link'.
  ![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/a59af3bd-083c-4066-babd-d4c61f0ee069)

## Actual Experience ##
There is an extra action 'Copy Direct Link'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/55d0d192-461a-4cb9-aabb-1de19c76afb3)

## Additional Context ##
This issue doesn't reproduce for ADLS Gen2 blobs/folders.

**Comment by JasonYeMSFT** [comment]
We intend to make deep link actions available on Linux as well.

**Comment by v-xianya** [comment]
@JasonYeMSFT On the new build main 20230531.3.

The action 'Copy Direct Link' has been added for one storage account/file share/queue/table.
For blob container/ADLS Gen2 blob container. there is no 'Direct Link'. Could you please help to have a look?

Also, does the direct link already supported to open storage explorer on Linux?

**Comment by JasonYeMSFT** [comment]
I will make the action show up for Blob Container and ADLS Gen2 container nodes. The direct links can only be opened via the dialog on Linux. It won't work if you open it from a web browser.
