### ISSUE TITLE
It is better to show the tooltip 'Copy SAS token to clipboard' instead of 'Copy query string to clipboard' on the Shared Access Signature dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6931]
**Storage Explorer Version**: 1.30.0-dev
**Build Number**: 20230527.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.4 (Apple M1 Pro)
**Architecture**: x64/arm64
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Right click one storage account -> Click 'Get Shared Access Signature...'.
2. Click 'Create' -> Hove over 'Copy' button for the SAS token part.
3. Observe the tooltip.
4. Check whether shows 'Copy SAS token to clipboard'.

## Expected Experience ##
It is better to show 'Copy SAS token to clipboard'.

## Actual Experience ##
It shows 'Copy query string to clipboard'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/13bca307-c11a-4f13-9b31-74e64f17c659)

## Additional Context ##
This issue also reproduces for four services.

**Comment by MRayermannMSFT** [comment]
New English string is merged. Translated string may or not make it in time for release.

**Comment by v-xianya** [comment]
Verified this issue on the build 20230531.3. Fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/76b8daba-ee48-441c-8f3f-e005fa6d6a2a)
