### ISSUE TITLE
The deleted queue doesn't auto disappear after deleting the queue

### ISSUE THREAD

**Issue by v-sunnsun** [microsoft/AzureStorageExplorer#6934]
**Storage Explorer Version**: 1.30.0-dev
**Build Number**: 20230531.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.4 (Apple M1 Pro)
**Architecture**:  x64
**How Found**: From running test case
**Regression From**:  Previous release (1.29.2)

## Steps to Reproduce 

1. Expand one storage account -> Queues.
2. Create one queue ->  The created queue displays on the tree view and auto opens. 
3. Delete the queue.
4. Check whether the deleted queue auto disappears.

## Expected Experience 
The deleted queue auto disappears.

## Actual Experience ##
The deleted queue doesn't auto disappear.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230531.13. Fixed. So, we are going to close it.
