### ISSUE TITLE
The base blob still shows on the Blob Snapshots View after retrying the failed activity of deleting base blob

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#694]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture**: ia32/x64
**Build Number**: 20180924.1
**Commit**: 1a75b88f
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Open one blob container then uploaded a blob to it.
2. Create a snapshot for the uploaded blob -> Open the blob snapshots view -> Try to delete the base blob directly -> The deleting activity is failed due to the base blob has snapshots.
3. Delete all the created snapshots -> Click the 'Retry' link next to the failed activity.

#### Expected Experience: ####
The failed activity becomes successful and the base blob disappears immediately from the blob snapshots view.

#### Actual Experience: ####
The failed activity becomes successful and the base blob still shows on the blob snapshots view.
It disappears after refreshing the editor.

**Comment by v-xianya** [comment]
This issue has been fixed on the build master/20190722.3. So we close it.
