### ISSUE TITLE
Error al inicializar con mi usuario de ad al storage acount con azure explorer

### ISSUE THREAD

**Issue by alexro21** [microsoft/AzureStorageExplorer#6940]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.29.2

### Regression From

1.29.2

### Architecture

i86

### Storage Explorer Build Number

windows 10

### Platform

Windows

### OS Version

windows

### Bug Description

{
  "name": null,
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"unable to get local issuer certificate\\\",\\n  \\\"stack\\\": \\\"Error: unable to get local issuer certificate\\\\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1538:34)\\\\n    at TLSSocket.emit (node:events:513:28)\\\\n    at TLSSocket._finishInit (node:_tls_wrap:952:8)\\\\n    at ssl.onhandshakedone (node:_tls_wrap:733:12)\\\",\\n  \\\"code\\\": \\\"UNABLE_TO_GET_ISSUER_CERT_LOCALLY\\\"\\n}\""
}

### Steps to Reproduce

1 inicie sesion en el explorer azure y me valide con directorio activo y me dice el error descrito

### Actual Experience

1 inicie sesion en el explorer azure y me valide con directorio activo y me dice el error descrito

### Expected Experience

deberia poder entrar al explorer y ver las suscripciones donde tengo el permiso

### Additional Context

1 inicie sesion en el explorer azure y me valide con directorio activo y me dice el error descrito

**Comment by Andrewzhouxin01** [comment]
I have exactly the same issue

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you still require assistance, we recommend that you open a support ticket via the Azure Portal. Alternatively you can open a new issue here.
