### ISSUE TITLE
Lower GPU usage of main screen

### ISSUE THREAD

**Issue by JohnTalen** [microsoft/AzureStorageExplorer#6941]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

GPU usage is 4% when main window is visible (Core i9, 9th Gen ; Win10)

### Desired Solution

Reduce graphical changes when only downloading files

### Alternatives and Workarounds

Hide screen, install extra solar panel ;)

### Additional Context

There is another request for a Mac which states it drains the accu even when idle, which is perhaps even worse...

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Feel free to open a new issue if the provided instructions do not work for you or if you have more information you'd like to share.
