### ISSUE TITLE
Unable to authenticate

### ISSUE THREAD

**Issue by yuriklyuzhin** [microsoft/AzureStorageExplorer#6943]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.29.2

### Regression From

NA

### Architecture

i86

### Storage Explorer Build Number

20230523.19

### Platform

Windows

### OS Version

Windows 11

### Bug Description

This request is not authorized to perform this operation.

This storage account's 'Firewalls & virtual networks' settings may be blocking access to storage services. Try adding your client IP address to the firewall exceptions, or by allowing access from 'all networks' instead of 'selected networks'. To learn more about Azure Storage firewalls and virtual networks, visit http://go.microsoft.com/fwlink/?LinkId=845443.

Error Details:
{
  "name": "RestError",
  "code": "AuthenticationFailed",
  "statusCode": 403,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://znssprod.blob.core.windows.net/?sv=2021-06-08&ss=bf&srt=sco&sp=rliyx&se=2024-10-28T02:39:13Z&st=2022-10-27T18:39:13Z&spr=https&SAS Token Redacted&comp=list&include=metadata",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2021-10-04"
        },
        "accept": {
          "name": "Accept",
          "value": "application/xml"
        },
        "user-agent": {
          "name": "User-Agent",
          "value": "Microsoft Azure Storage Explorer/1.29.2 (win32) azsdk-js-storageblob/12.12.0 (NODE-VERSION v18.12.1; Windows_NT 10.0.22621)"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "81923c31-bfdc-41f4-bbb7-018792071580"
        },
        "cookie": {
          "name": "Cookie",
          "value": ""
        }
      }
    },
    "withCredentials": false,
    "timeout": 0,
    "keepAlive": true,
    "decompressResponse": false,
    "requestId": "81923c31-bfdc-41f4-bbb7-018792071580"
  },
  "response": {
    "headers": {
      "_headersMap": {
        "content-length": {
          "name": "content-length",
          "value": "507"
        },
        "content-type": {
          "name": "content-type",
          "value": "application/xml"
        },
        "date": {
          "name": "date",
          "value": "Thu, 01 Jun 2023 22:45:29 GMT"
        },
        "server": {
          "name": "server",
          "value": "Microsoft-HTTPAPI/2.0"
        },
        "x-ms-error-code": {
          "name": "x-ms-error-code",
          "value": "AuthenticationFailed"
        },
        "x-ms-request-id": {
          "name": "x-ms-request-id",
          "value": "d1164e1d-101e-0064-16da-94011e000000"
        }
      }
    },
    "request": {
      "streamResponseStatusCodes": {},
      "url": "https://znssprod.blob.core.windows.net/?sv=2021-06-08&ss=bf&srt=sco&sp=rliyx&se=2024-10-28T02:39:13Z&st=2022-10-27T18:39:13Z&spr=https&SAS Token Redacted&comp=list&include=metadata",
      "method": "GET",
      "headers": {
        "_headersMap": {
          "x-ms-version": {
            "name": "x-ms-version",
            "value": "2021-10-04"
          },
          "accept": {
            "name": "Accept",
            "value": "application/xml"
          },
          "user-agent": {
            "name": "User-Agent",
            "value": "Microsoft Azure Storage Explorer/1.29.2 (win32) azsdk-js-storageblob/12.12.0 (NODE-VERSION v18.12.1; Windows_NT 10.0.22621)"
          },
          "x-ms-client-request-id": {
            "name": "x-ms-client-request-id",
            "value": "81923c31-bfdc-41f4-bbb7-018792071580"
          },
          "cookie": {
            "name": "Cookie",
            "value": ""
          }
        }
      },
      "withCredentials": false,
      "timeout": 0,
      "keepAlive": true,
      "decompressResponse": false,
      "requestId": "81923c31-bfdc-41f4-bbb7-018792071580"
    },
    "status": 403,
    "bodyAsText": "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:d1164e1d-101e-0064-16da-94011e000000\nTime:2023-06-01T22:45:30.6527959Z</Message><AuthenticationErrorDetail>Signature did not match. String to sign used was znssprod\nrliyx\nbf\nsco\n2022-10-27T18:39:13Z\n2024-10-28T02:39:13Z\n\nhttps\n2021-06-08\n\n</AuthenticationErrorDetail></Error>",
    "parsedBody": {
      "message": "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:d1164e1d-101e-0064-16da-94011e000000\nTime:2023-06-01T22:45:30.6527959Z",
      "code": "AuthenticationFailed",
      "AuthenticationErrorDetail": "Signature did not match. String to sign used was znssprod\nrliyx\nbf\nsco\n2022-10-27T18:39:13Z\n2024-10-28T02:39:13Z\n\nhttps\n2021-06-08\n\n"
    },
    "parsedHeaders": {
      "errorCode": "AuthenticationFailed",
      "content-length": "507",
      "content-type": "application/xml",
      "date": "Thu, 01 Jun 2023 22:45:29 GMT",
      "server": "Microsoft-HTTPAPI/2.0",
      "x-ms-request-id": "d1164e1d-101e-0064-16da-94011e000000"
    }
  },
  "details": {
    "errorCode": "AuthenticationFailed",
    "content-length": "507",
    "content-type": "application/xml",
    "date": "Thu, 01 Jun 2023 22:45:29 GMT",
    "server": "Microsoft-HTTPAPI/2.0",
    "x-ms-request-id": "d1164e1d-101e-0064-16da-94011e000000",
    "message": "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:d1164e1d-101e-0064-16da-94011e000000\nTime:2023-06-01T22:45:30.6527959Z",
    "code": "AuthenticationFailed",
    "AuthenticationErrorDetail": "Signature did not match. String to sign used was znssprod\nrliyx\nbf\nsco\n2022-10-27T18:39:13Z\n2024-10-28T02:39:13Z\n\nhttps\n2021-06-08\n\n"
  }
}

### Steps to Reproduce

1.Launched Storage Explorer
2. Accessed Blob Containers

### Actual Experience

Was not able to connect to syslog

**Comment by MRayermannMSFT** [comment]
Hi @yuriklyuzhin 

1: Have you done as the error message suggested?

> This storage account's 'Firewalls & virtual networks' settings may be blocking access to storage services. Try adding your client IP address to the firewall exceptions, or by allowing access from 'all networks' instead of 'selected networks'. To learn more about Azure Storage firewalls and virtual networks, visit http://go.microsoft.com/fwlink/?LinkId=845443.

2: The error indicates likely something is wrong with the SAS token you are using to connect. Can you generate a new SAS token and try again? Make sure not to modify the SAS token once the server returns it to you.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you still require assistance, we recommend that you open a support ticket via the Azure Portal. Alternatively you can open a new issue here.
