### ISSUE TITLE
Subscriptions cannot be retrieved on new storage explorer version 1.29.2

### ISSUE THREAD

**Issue by sriwee** [microsoft/AzureStorageExplorer#6944]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.29.2

### Architecture

i86

### Platform

Windows

### OS Version

Windows 10

### Bug Description

I cannot able to connect to the storage accounts from azure storage explorer. 
below is the error:
Microsoft account (home tenant)
Could not access resources for this tenant. You may need to reauthenticate. See the error details for more information.
Error Details
If you cannot resolve this issue on your own, you may open an issue on the Storage Explorer GitHub site. Please include the details below to help us diagnose your issue. Make sure to redact any personal information you do not wish to make public before posting.

### Steps to Reproduce

1. try to reauthenticate now, getting the same error message. 

### Actual Experience

Error Details
If you cannot resolve this issue on your own, you may open an issue on the Storage Explorer GitHub site. Please include the details below to help us diagnose your issue. Make sure to redact any personal information you do not wish to make public before posting.

### Expected Experience

Error Details
If you cannot resolve this issue on your own, you may open an issue on the Storage Explorer GitHub site. Please include the details below to help us diagnose your issue. Make sure to redact any personal information you do not wish to make public before posting.

### Additional Context

Error Details
If you cannot resolve this issue on your own, you may open an issue on the Storage Explorer GitHub site. Please include the details below to help us diagnose your issue. Make sure to redact any personal information you do not wish to make public before posting.
![Capture](https://github.com/microsoft/AzureStorageExplorer/assets/135308352/7c2f3a22-f93c-49b4-b159-f888759c978d)

**Comment by MRayermannMSFT** [comment]
For this error, please try enabling system proxy: https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you still require assistance, we recommend that you open a support ticket via the Azure Portal. Alternatively you can open a new issue here.
