### ISSUE TITLE
The string on the address bar overflows after creating snapshots for file shares

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6945]
**Storage Explorer Version**: 1.30.0-dev
**Build Number**: 20230602.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4 (Apple M1 Pro)
**Architecture**: x64/arm64
**How Found**: Exploratory testing
**Regression From**: Previous release (1.26.1)

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Create a folder and open it.
4. Resize the file share explorer (make sure there is no ... showing in address bar)-> Create a snapshot for the file share.
5. Observe the address bar.
6. Check whether the string does not overflow.
  
## Expected Experience ##
The string does not overflow.
  
## Actual Experience ##
The string overflows.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/b4846a20-e20d-48e7-96f6-c8d5acaf9820)

## Additional Context ##
Here is the record:
![0602](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/14404213-4893-443f-a97e-a01d7b3f9cf2)

**Comment by craxal** [comment]
@JasonYeMSFT If not already, consider updating to the new components to see if that resolves this issue.

**Comment by JasonYeMSFT** [comment]
I cannot simply upgrade the ui components unless we fix all the icons.

**Comment by MRayermannMSFT** [comment]
Fix as part of https://github.com/microsoft/AzureStorageExplorer/issues/7154
