### ISSUE TITLE
Delete folder in blob container

### ISSUE THREAD

**Issue by Sathyamn6** [microsoft/AzureStorageExplorer#6948]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.29.2

### Regression From

1.29.1

### Architecture

i86

### Platform

All

### OS Version

Windows 10

### Bug Description

{
  "message": "\"failed to perform remove command due to error: cannot start job due to error: cannot verify resource due to error: -> github.com/Azure/azure-storage-azcopy/v10/azbfs.newStorageError, /home/vsts/work/1/s/azbfs/zc_storage_error.go:41\\n===== RESPONSE ERROR (ServiceCode=PathNotFound) =====\\nDescription=404 The specified path does not exist., Details: (none)\\n   HEAD https://formula1datalaketest.dfs.core.windows.net/presentation/race_results?timeout=901\\n   Authorization: REDACTED\\n   User-Agent: [Microsoft Azure Storage Explorer, 1.29.2, win32, azcopy-node/2.12.0-rc.2 (win32)  AzCopy/10.18.1 Azure-Storage/0.1 (go1.19.8; Windows_NT)]\\n   X-Ms-Client-Request-Id: [9e1283b7-88d4-41c6-559a-f883c7fa2917]\\n   X-Ms-Date: [Mon, 05 Jun 2023 07:49:08 GMT]\\n   X-Ms-Version: [2018-11-09]\\n   --------------------------------------------------------------------------------\\n   RESPONSE Status: 404 The specified path does not exist.\\n   Date: [Mon, 05 Jun 2023 07:48:44 GMT]\\n   Server: [Windows-Azure-HDFS/1.0 Microsoft-HTTPAPI/2.0]\\n   X-Ms-Error-Code: [PathNotFound]\\n   X-Ms-Request-Id: [3b76a287-f01f-004e-3982-975b7b000000]\\n   X-Ms-Version: [2018-11-09]\\n\\n\\n.\\n\""
}

### Steps to Reproduce

Launch storage explorer
launch blob container

### Actual Experience

unable to delete folders in blob container

### Expected Experience

easily be able to delete folders in blob container

**Comment by MRayermannMSFT** [comment]
@Sathyamn6 the error indicates that the thing trying to be deleted doesn't exist. Can you confirm that someone else hasn't deleted it? If it hasn't, then could you please:
1. Try the delete agian
2. go to `<user folder>/.azcopy`
3. Look for the newest log file
4. Share it here
Thanks.

**Comment by Sathyamn6** [comment]
Hi Mathew,

Thanks for looking into this. This is resolved now.

Thanks,
Sathya
