### ISSUE TITLE
An error message occurs when typing a directory name ends with a dot on 'Clone Folder' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6949]
**Storage Explorer Version**: 1.30.0
**Build Number**: 20230603.6
**Branch**: rel/1.30.0
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4 (Apple M1 Pro)
**Architecture**: x64/arm64
**How Found**: From running testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch storage explorer -> Uncheck the setting 'Disable File Share Trailing Dot Support'.
2. Expand one storage account -> File Shares.
3. Create a file share -> Create a new folder named 'test'.
4. Select the folder -> Click 'Clone'.
5. Type 'test./' as the new name.
6. Check there is no error message.
  
## Expected Experience ##
There is no error message.
  
## Actual Experience ##
There is an error message.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/43d7659e-1bae-4154-9f89-383c2ea926a7)

**Comment by v-xianya** [comment]
Verified this issue on the build 20230606.6. Reproduce. So, we are going to reopen it.

**Comment by richardMSFT** [comment]
I am unable to reproduce the error on the most recent rel/1.30.0 branch.

![Screenshot 2023-06-06 at 10 34 56 AM](https://github.com/microsoft/AzureStorageExplorer/assets/111301956/34b8eaa9-3150-4469-ad5d-2c3955cff0d1)

If this persists can you send me a link to a machine where it is reproducing?

**Comment by v-xianya** [comment]
Hi @richardMSFT This issue still reproduces on the latest build. I shared the VM in the teams.

**Comment by richardMSFT** [comment]
Ok I think it should be good now. I tested it on a recent build and it should no longer reproduce. The problem was the package-lock.json file wasn't updated.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230608.6. Fixed.
