### ISSUE TITLE
Cannot undo in Cosmos DB query editor

### ISSUE THREAD

**Issue by thomaslevesque** [microsoft/AzureStorageExplorer#695]
**Storage Explorer Version**: 1.4.1
**Platform/OS Version**: Windows 10 x64
**Architecture**: ia32
**Regression From**: Maybe 1.4.0, I'm not sure. But I'm pretty sure it used to work at some point; I would have noticed if it didn't.

#### Steps to Reproduce: ####
Open a query tab on a CosmosDB collection
Type some text
Try to undo with Ctrl-Z

#### Expected Experience: ####
Should undo the last keystroke(s)

#### Actual Experience: ####
Nothing happens

Note: my keyboard has an AZERTY layout, in case it matters.

**Comment by thomaslevesque** [comment]
Any news on this? The issue is still there in 1.5.0.

**Comment by thomaslevesque** [comment]
Still there in 1.6.0. This should be a high priority issue...

**Comment by ziyel** [comment]
@thomaslevesque. Thanks for the feedback and sorry for the late response. 
We have prioritized this and plan to fix in version `1.7.0`.

**Comment by thomaslevesque** [comment]
Thanks @ziyel!

**Comment by thomaslevesque** [comment]
Hi @ziyel,

> We have prioritized this and plan to fix in version `1.7.0`.

I just installed 1.7.0, the problem doesn't appear to be fixed :(

**Comment by thomaslevesque** [comment]
1.9.0, still not fixed. Am I the only one using Azure Storage Explorer to query Cosmos DB?

**Comment by southpolesteve** [comment]
@thomaslevesque Does it work for you in the Azure Portal or https://cosmos.azure.com/

**Comment by thomaslevesque** [comment]
@southpolesteve yes it does. Both web versions work fine, the problem is only in Azure Storage Explorer.

**Comment by ishimmings** [comment]
Any news on this? Really annoying not being able to do basic undo/redo.

**Comment by thomaslevesque** [comment]
Is anyone looking into this? It's been more than a year...

And now there's also #2357. Frankly, Azure Storage Explorer is becoming almost unusable for Cosmos DB work, and it's the only desktop client for Cosmos DB as far as I know (since there hasn't been any progress towards supporting it in Azure Data Studio).

**Comment by thomaslevesque** [comment]
FWIW, I'm giving up on Azure Storage Explorer for working with Cosmos DB. If you don't intend to make Cosmos DB features work correctly, just remove support for Cosmos DB, because in its current state, it's barely usable.

**Comment by andreacassioli** [comment]
Any progress? Is it a very complex revolutionary functionality?? At least giving a feed back would be nice...

**Comment by southpolesteve** [comment]
@andreacassioli I have no updates or ETA. My recommendation is to use https://cosmos.azure.com/ (Which also powers the Azure Portal). Undo works there. Additionally, it has many other new query features like DISTINCT, LIMIT/OFFSET, and GROUP BY.

**Comment by andreacassioli** [comment]
@southpolesteve So what is the purpose of the explorer? I mean, we are taking about basic undo.... 

Anyway the portal is not much better (I cannot even see all my subscriptions...) and only the explorer in portal.azure.com seems to be OK. 

There is a merit in a stand-alone client when a portal is somehow slow, cumbersome and you work on a smaller screen.

**Comment by thomaslevesque** [comment]
Like I said before, if the Cosmos DB features in Azure Storage Explorer are not going to be maintained, they might as well be removed entirely, because currently they're basically useless.

**Comment by gorillapower** [comment]
Were also dying for an undo in the Storage Explorer as well as being able to collapse JSON.

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
