### ISSUE TITLE
The queried result is incorrect if clear 'Show top results' field then execute query

### ISSUE THREAD

**Issue by v-sunnsun** [microsoft/AzureStorageExplorer#6953]
**Storage Explorer Version**: 1.30.0
**Build Number**: 20230606.6
**Branch**: rel/1.30.0
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4 (Apple M1 Pro)
**Architecture**:  x64/arm64
**How Found**: From running test case
**Regression From**:  Previous release (1.29.1)

## Steps to Reproduce 

1. Expand one storage account -> Tables.
2. Create a table -> Add one entity.
3. Click 'Query' -> Expand the 'Advanced Options' -> Type '1' into the 'Show top results' field.
4. Press 'Backspace' to delete the 'Show top results' field -> Execute query.
5. Check whether the queried result is correct.

## Expected Experience 
The queried result is correct.

## Actual Experience ##
The queried result is incorrect.

**Comment by craxal** [comment]
@v-sunnsun Can you be more specific about what you mean by a "correct" vs an "incorrect" result? Do you mean that when you execute the query, you are getting the same number of results as though the "top" parameter was still present?

**Comment by v-sunnsun** [comment]
Hi @craxal 
No, no entity displays if clear top parameter then execute query.
1. When typing 1 as the top parameter, there is an entity after executing query. 
2. Don't change the query conditions, when typing 1 as the top parameter then clearing it, there is no entity after executing query.
3. Here is the record:
![record](https://github.com/microsoft/AzureStorageExplorer/assets/122582307/86b42dc2-f36b-41ac-b7fb-a9a3f7e072fe)

**Comment by v-sunnsun** [comment]
Verified this issue on the build 20230608.6. Fixed. So, we are going to close it.
