### ISSUE TITLE
Update 3rd party package managers to point at 64 bit windows setup

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#6959]
Put out PRs once we are ready to ship, but before publishing GitHub release (having a draft release is fine). Then once PRs are all live, can make publish the GitHub release.

- winget: https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Microsoft/Azure/StorageExplorer/
- Chocolatey: https://community.chocolatey.org/packages/microsoftazurestorageexplorer#files
- Scoop: https://github.com/ScoopInstaller/Extras/blob/master/bucket/azurestorageexplorer.json

**Comment by richardMSFT** [comment]
PRs for winget & scoop have been opened. I've emailed the maintainer for the Chocolately package with a description of what to expect from the new 64-bit installer.
