### ISSUE TITLE
1.4.2 breaks Azure Gov environments

### ISSUE THREAD

**Issue by okaicomputer** [Microsoft/AzureStorageExplorer#696]
**Storage Explorer Version**: 1.4.2
**Platform/OS Version**: Windows
**Architecture**: ia32 -->
**Regression From**: Yes, 1.4.1

#### Steps to Reproduce: ####
1. Connect to a Storage Account in the Azure Gov environment
2. Click to expand a Storage Account.

#### Expected Experience: ####
You should be able to browse/expand to access storage resources within a Storage Account.

#### Actual Experience: ####
Storage Accounts are visible, but when you attempt to expand them they are empty.  I removed my Gov account and re-authenticated--same behavior.

**Comment by JakeRadMSFT** [comment]
Sorry about that! We've recently changed the api-version to support a new blob type but Azure Government doesn't support that yet.  I'll add the workaround to my next comment on this thread.

**Comment by JakeRadMSFT** [comment]
To workaround the issue
1. Locate AzureStorageAccountAttributeLoader.js
2. Locate the variable assignment v2AttributesApiVersion = "2018-07-01"
3. Change to v2AttributesApiVersion = "2017-10-01";
4. Restart all Storage Explorer instances.

**Comment by JakeRadMSFT** [comment]
We double checked and the version is supposed in Azure Government ... except US Gov Iowa. Are you targeting US Gov Iowa?

**Comment by okaicomputer** [comment]
No, the target is Virginia.  I will do some more digging in and follow back up.

**Comment by okaicomputer** [comment]
Changing the v2AttributesApiVersion as suggested corrected the issue.  Thanks much for the quick response.  This is the second time I've seen a new version break Gov.

**Comment by JakeRadMSFT** [comment]
Sorry about that, we'll come up with a way to make sure we don't break it in the future. Btw it will self-correct it self soon. It turns our Azure Iowa will still impact some calls for Azure Virginia if the calls are across regions. 

I'm going to leave this issue open until the new Api-Version works for Iowa.

**Comment by okaicomputer** [comment]
Awesome. I know how much of a pain Gov is. Thanks again for the prompt workaround!

**Comment by vivianxing** [comment]
@JakeRadMSFT Hi Jake. Azure China (Mooncake) also have this issue, would the issue be fix automatically in the future?

**Comment by JakeRadMSFT** [comment]
@vivianxing, yes

**Comment by rider158** [comment]
This is still an issue with US Gov Texas.  The fix referenced above did remedy the situation, however.

**Comment by JakeRadMSFT** [comment]
@rider158, Thanks for reporting! I'll see if I can get an ETA.

**Comment by JakeRadMSFT** [comment]
We'll come up with a better workaround for our next release.

**Comment by hoshauch** [comment]
Same with Azure Germany.

**Comment by Christo4bx** [comment]
Azure Government (specifically Texas) is still broken in 1.4.3 with the same issue (i.e., unable to browse storage accounts within an Azure Government subscription). The fix as provided by JakeRadMSFT still works.

**Comment by JakeRadMSFT** [comment]
Resolved (Reverted) and it will be rolled out when available everywhere.
