### ISSUE TITLE
Azure Storage Explorer crashing when tried to expand blob container list under a storage account.

### ISSUE THREAD

**Issue by anothnk** [microsoft/AzureStorageExplorer#6960]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.29.2

### Architecture

x64

### Platform

macOS

### OS Version

macOS High Sierra

### Bug Description

Azure Storage Explorer is crashing when tried to expand the blob container tree for a given storage account entry.

Tried reset, re-install etc, but issue persists.

### Steps to Reproduce

1. Launch Storage Explorer
2. Sign in with Azure
3. Browser login is successful and subscription details are updated
4. Select the subscription -> Storage Account -> Blob Containers
5. A loader appears for a brief time, and then application crashes

### Actual Experience

1. Launch Storage Explorer
2. Sign in with Azure
3. Browser login is successful and subscription details are updated
4. Select the subscription -> Storage Account -> Blob Containers
5. A loader appears for a brief time, and then application crashes

### Expected Experience

1. Launch Storage Explorer
2. Sign in with Azure
3. Browser login is successful and subscription details are updated
4. Select the subscription -> Storage Account -> Blob Containers
5. Blob containers under the storage account is listed and user is able to select one blob container and list blobs.

**Comment by JasonYeMSFT** [comment]
We haven't been developing and testing against High Sierra for a long time since it stops receiving any update since 2020. If possible, I highly recommend you to upgrade the OS.

**Comment by anothnk** [comment]
Thanks @JasonYeMSFT for the quick response.

I understand that High Sierra is pretty old, but some business apps I have is restricting me to update. I will definitely try to update the OS and check if that works.

Meanwhile, this is the crash message I see in logs:

`
Symbol not found: _objc_opt_class
Referenced from: /private/var/folders/*/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/@storage-explorer/clipboard-files/build/Release/clipboardFiles.node (which was built for Mac OS X 10.15)
Expected in: /usr/lib/libobjc.A.dylib
`

**Comment by JasonYeMSFT** [comment]
I see. It's a native module that has been upgraded to newer system APIs. It's actually for some non-critical features. We can consider making it optional so it won't block the rest of the application.

**Comment by JasonYeMSFT** [comment]
I created two private builds that attempt to catch the dependency errors. The feature depending on the module won't work but at least the application shouldn't crash. Other than that, they are identical to what we shipped in 1.30.0. I don't have a High Sierra machine to test it. You can try it and let us know if it works. If the workaround works, we'll check in it for all our future releases.

[mac arm64](https://storageexplorerpublish.blob.core.windows.net/privatebuilds/1.30.0-high-sierra/StorageExplorer-darwin-arm64-private.zip)
[mac x64](https://storageexplorerpublish.blob.core.windows.net/privatebuilds/1.30.0-high-sierra/StorageExplorer-darwin-x64-private.zip)

**Comment by anothnk** [comment]
Thank you for your support.

I tried the x64 version of the private build, and unfortunately, the crash remains. Error log below:

```
Symbol not found: _objc_opt_class

Referenced from: /Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/@storage-explorer/clipboard-files/build/Release/clipboardFiles.node (which was built for Mac OS X 10.15)

Expected in: /usr/lib/libobjc.A.dylib
  ```

**Comment by JasonYeMSFT** [comment]
I am sorry to hear that. Let me do some investigation to see what actually went wrong.

**Comment by JasonYeMSFT** [comment]
I did more investigation and found that at some point the default compiler config has changed to target 10.15 as the minimum macOS version. I saw people saying they successfully forced targeting a lower version of macOS and things are still working. I did the same thing and get the following two builds. It would be great if you still have time to try it out and help see if it mitigates the problem.

[mac arm64](https://storageexplorerpublish.blob.core.windows.net/privatebuilds/1.30.0-high-sierra/StorageExplorer-darwin-arm64%20(downgrade%20osx%20version).zip)
[mac x64](https://storageexplorerpublish.blob.core.windows.net/privatebuilds/1.30.0-high-sierra/StorageExplorer-darwin-x64%20(downgrade%20osx%20version).zip)

**Comment by anothnk** [comment]
Thanks. I installed the x64 build for downgraded macOS version. But, this time I get a different error when I try to view the contents under a storage container. It doesn't list Blob container type, and at that time it also shows a message "ERR_IPC_CHANNEL_CLOSED - Channel closed".

**Comment by JasonYeMSFT** [comment]
The new error is a Node error. I just found this "Prebuilt binaries for macOS now require macOS 10.15 or later" in the NodeJS v18 change log. https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md

Our 1.30.0 uses Electron 24 which bundles NodeJS 18 https://www.electronjs.org/blog/electron-24-0. I am afraid there is no way we can fix this problem in our future releases since Node out of our control. Our latest release without using an Electron bundling Node 18 is 1.28.x. You may install an older version of Storage Explorer and it probably would work. We have all prior releases available here https://github.com/microsoft/AzureStorageExplorer/releases

**Comment by anothnk** [comment]
Thanks again for your inputs. I tried the 1.27.2 version (December 2022), and it works fine.

I appreciate your help on this.
