### ISSUE TITLE
The layout of 'Upload Blob' dialog is odd with 'Use AzCopy for Improved Upload and Download' checked

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#697]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture**: ia32/x64
**Build Number**: 20180926.5
**Commit**: d6717c99
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Navigate to 'Experimental' menu -> Check 'Use AzCopy for Improved Upload and Download'.
2. Open one blob container then open Upload dialog.

#### Expected Experience: ####
The layout of Upload dialog shows well.

#### Actual Experience: ####
The layout of Upload dialog is odd.
![odd](https://user-images.githubusercontent.com/34729022/46067248-edc88800-c165-11e8-87da-2d54a80df0f7.png)

**Comment by MRayermannMSFT** [comment]
This was a build issue.
