### ISSUE TITLE
The icon of the action 'Refresh' is invisible for Quick Access node under 'High Contrast - Black' theme

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6970]
**Storage Explorer Version**: 1.30.0
**Build Number**: 20230613.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4 (Apple M1 Pro)
**Architecture**: x64
**How Found**: From running test cases
**Regression From**: Previous release (1.30.0)

## Steps to Reproduce ##
1. Launch storage explorer -> Change the theme to 'High Contrast - Black'.
2. Click 'Quick Access' node -> Observe the 'Actions' panel.
3. Check whether the icon of the action 'Refresh' is visible.
  
## Expected Experience ##
The icon of the action 'Refresh' is visible.
  
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/6f2045fa-dd71-41ad-93e1-c2f60fddb578)

## Actual Experience ##
The icon of the action 'Refresh' is invisible.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/710d8a94-4384-424e-abda-f4bdbbab2f2e)

## Additional Context ##
The screenshot under 'Dark' theme.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/1da53b0d-d997-486c-bf26-c1edcafa1f4b)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230614.1. Fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/d1a1f07f-62bb-43dc-8582-e9974a980532)
