### ISSUE TITLE
The 'Delete' action is disabled when selecting one regular blob/folder

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6973]
**Storage Explorer Version:** 1.30.0
**Build Number**: 20230613.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4 (Apple M1 Pro)
**Architecture:** x64
**How Found:** From running test cases
**Regression From:** Previous release (1.30.0)

## Steps to Reproduce ##

1. Expand one non-ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload a blob.
3. Select the blob.
4. Check whether the 'Delete' action is enabled.

## Expected Experience ##
The 'Delete' action is enabled.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/cf25efdd-08c1-45e0-a7ab-cf44d152b1bc)

## Actual Experience ##
The 'Delete' action is disabled.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/42ac141a-724f-4d08-8e18-ca2954a39d17)

## Additional Context ##
This issue doesn't reproduce for ADLS Gen2 blobs/files.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230614.1. Fixed. So, we are going to close it.
