### ISSUE TITLE
No icons in 'Search for resources' box

### ISSUE THREAD

**Issue by v-sunnsun** [microsoft/AzureStorageExplorer#6975]
**Storage Explorer Version**: 1.30.0
**Build Number**: 20230613.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4 (Apple M1 Pro)
**Architecture**: x64
**How Found**: From running test cases
**Regression From**: Previous release (1.30.0)

## Steps to Reproduce 

1. Launch storage explorer -> Observe the 'Search for resources' box.
2. Check whether there are icons in 'Search for resources' box.

## Expected Experience 
There are icons in 'Search for resources' box.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/122582307/734aaf5f-9344-4825-a078-d98ea74f6cff)

## Actual Experience
There is no icon in 'Search for resources' box.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/122582307/1d2d0c0b-71fb-4720-9b37-0b51816047df)

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230706.6. Fixed. So, we are going to close it.
