### ISSUE TITLE
Fail to delete snapshots for ADLS Gen2 blobs

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6976]
**Storage Explorer Version**: 1.30.0
**Build Number**: 20230613.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4 (Apple M1 Pro)
**Architecture**: x64
**How Found**: From running test cases
**Regression From**: Previous release (1.30.0)

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Create a snapshot for the blob -> Go to snapshots view.
4. Select the snapshot -> Try to delete it.
5. Check whether succeeds to delete the snapshot.

## Expected Experience ##
Succeed to delete the snapshot.

## Actual Experience ##
Fail to delete the snapshot.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/f60411a9-7d7a-4c31-81d9-eaa85b708787)

AzCopy log:
[2068f3e2-6321-d24c-7acd-8226f1881425.log](https://github.com/microsoft/AzureStorageExplorer/files/11732033/2068f3e2-6321-d24c-7acd-8226f1881425.log)

## Additional Context ##
This issue has nothing to do with soft delete policy.

**Comment by v-xianya** [comment]
@JasonYeMSFT The 'Delete' action is disabled when sleeting more than one ADLS Gen2 blob snapshots. Could you help to take a look?
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/2e55fc1d-00d4-42b8-a0d8-5c73662ac55e)

**Comment by JasonYeMSFT** [comment]
The new behavior is expected. We have removed the legacy JS code and will only use AzCopy to delete snapshots. AzCopy only supports deleting one snapshot at a time.
