### ISSUE TITLE
There is no 'Clone' action for emulator blobs

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6977]
**Storage Explorer Version:** 1.30.0
**Build Number:** 20230613.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4 (Apple M1 Pro)
**Architecture:** x64
**Azurite Version:** 3.24.0
**How Found:** From running test cases
**Regression From:** Previous release (1.30.0)

## Steps to Reproduce ##

1. Install and run Azurite 3.24.0 -> Launch Storage Explorer.
2. Expand Emulator & Attached -> Storage Accounts-> (Emulator - Default Ports) (Key).
3. Blob Containers -> Create a blob container.
4. Check whether there is a 'Clone' action on the toolbar.
 
## Expected Experience ##
There is a 'Clone' action.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/a097faa1-4817-487d-bfb6-c0c266efebc0)

## Actual Experience ##
There is no 'Clone' action.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/daea6b12-9690-45d4-9e69-18067c664728)

## Additional Context ##
There is no 'Clone...' action for one emulator blob container.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/895fad0d-cd9e-42b9-9154-78e88cbfd68f)

**Comment by MRayermannMSFT** [comment]
@v-kellyluio please consider this a by design behavior. We have removed old code that existed only for the purpose of supporting clone for Azurite/emulator.
