### ISSUE TITLE
The loading icon doesn't display on the 'Import Entities/Open Service by Name' dialog

### ISSUE THREAD

**Issue by v-kellyluo** [Microsoft/AzureStorageExplorer#6979]
**Storage Explorer Version:** 1.30.0
**Build Number:** 20230613.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4 (Apple M1 Pro)
**Architecture:** x64
**How Found:** From running test cases
**Regression From:** Previous release (1.30.0)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Click 'Import'.
3. Select a large csv file -> Click 'Open'.
4. Check whether the loading icon displays.

## Expected Experience ##
The loading icon displays.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/ec7233e4-5167-43d5-9d56-7b4ef5e80074)

## Actual Experience ##
The loading icon doesn't display.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/bdf7edf9-2320-4afb-ad9c-0fdce55dcb69)

## Additional Context ##
There is no loading icon on the 'Open Service by Name' dialog.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/6ed4bf20-ba5c-43e2-a248-313f84d90790)

**Comment by v-xianya** [comment]
Update: Verified this issue on the build main 20230625.1.

1. Fixed for 'Open Service by Name' dialog.
2. Reproduce for 'Import Entities' dialog.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230629.1. Fixed.
