### ISSUE TITLE
There are no icons for the actions 'Open in Portal' and 'Pin to Quick Access'

### ISSUE THREAD

**Issue by v-sunnsun** [microsoft/AzureStorageExplorer#6980]
**Storage Explorer Version**: 1.30.0
**Build Number**: 20230613.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4 (Apple M1 Pro)
**Architecture**: x64
**How Found**: From running test cases
**Regression From**: Previous release (1.30.0)

## Steps to Reproduce 

1. Select one storage account -> Observe its 'Actions' panel.
2. Check whether there are icons for the actions 'Open in Portal' and 'Pin to Quick Access'.

## Expected Experience 
There are icons for the actions 'Open in Portal' and 'Pin to Quick Access'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/122582307/18c5f266-d98d-401f-8b08-9cab1ae41115)

## Actual Experience
There are no icons for the actions 'Open in Portal' and 'Pin to Quick Access'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/122582307/92565c36-cd8c-4963-ad72-2f0b8aee7f00)

## Additional Context ##

1. No icon for the 'Open' action for blob containers/file shares/queues.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/122582307/a285c572-24df-4a3d-9627-b77c8018e9b2)
2. No icon for the 'Open in new tab' action for queues.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/122582307/e2a09844-344b-4373-9dea-8a78e1f5595a)
3. No icons for actions for disks.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/122582307/551365e7-f745-4909-9d98-531cf2d6e94e)
5. No icon for the 'Connect to Azure Storage...' action.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/122582307/d8b35e6d-102d-4adf-8c78-fc55afc286cc)
6. The down arrow doesn't display next to the 'Properties' panel.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/122582307/75066895-aae8-4381-8b9e-744825a2842a)

.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230707.6, this issue only reproduces for disks.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/d1aaae5e-5184-4927-a399-09a5cdcf19e1)

**Comment by v-xianya** [comment]
@craxal 
Verified this issue on the main build 20230711.6.
For file shares/disks, there are missing icon on Actions panel. So, we are going to reopen this issue.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/dd5621d7-c29d-4783-b84a-e8389e0aea22)
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/8b82b12a-9174-413e-868f-6214b682a53d)

**Comment by craxal** [comment]
Fixes for file shares and disks have been merged.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230713.8. Fixed.
