### ISSUE TITLE
File downloaded from blob, js file downloaded to local open after garbled

### ISSUE THREAD

**Issue by madman215330** [microsoft/AzureStorageExplorer#6981]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

File downloaded from blob, js file downloaded to local open after garbled

### Desired Solution

File downloaded from blob, js file downloaded to local open after garbled

**Comment by madman215330** [comment]
version is 1.29.2

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. This issue will no longer be monitored. If you are still encountering this issue we recommend opening a support ticket from the Azure portal. Alternatively you can open a new issue here.
