### ISSUE TITLE
Only one snapshot is deleted when deleting multiple snapshots for a regular blob

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6984]
**Storage Explorer Version**: 1.31.0-dev
**Build Number**: 20230614.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4 (Apple M1 Pro)
**Architecture**: x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.30.0)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Create two snapshots for the blob -> Go to the snapshots view.
4. Select the two snapshots -> Click 'Delete'.
5. Check whether the two snapshots disappear.

## Expected Experience ##
The two snapshots disappear.

## Actual Experience ##
1. Only one snapshot disappears.
2. Show '2 completed' in the delete activity log.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/43ec5e92-d5ea-46bc-9676-c7294852b741)

**Comment by MRayermannMSFT** [comment]
@v-xianya please consider this a by design behavior. We have removed old code that existed only for the purpose of supporting multi-snapshot delete.
