### ISSUE TITLE
my storager explorer doesnt connect to my azure account or any resources in my azure account

### ISSUE THREAD

**Issue by Dezipro** [microsoft/AzureStorageExplorer#6987]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.29.2

### Architecture

i86

### Platform

All

### Bug Description

The authentication library used by Storage Explorer has failed to start properly. Please ensure you have .NET Framework 4.7.2 or greater installed. If .NET Framework 4.7.2 or greater is already installed then refer to the troubleshooting guide for help. Verbose authentication logging has been enabled.

### Steps to Reproduce

signin with azure 

### Actual Experience

Each time i want to sign in it displays that same message 

### Expected Experience

its supposed to prompt up my azure account for me to link

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. This issue will no longer be monitored. If you are still encountering this issue we recommend opening a support ticket from the Azure portal. Alternatively you can open a new issue here.
