### ISSUE TITLE
PDF preview and video open in browser fails when the file is within a trailing dot directory

### ISSUE THREAD

**Issue by richardMSFT** [microsoft/AzureStorageExplorer#6988]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.30.0

### Architecture

arm64

### Platform

All

### Bug Description

PDF preview and video play in browser fails when the file is in a trailing dot directory. This is because we have to capture/intercept the request and attach the correct headers to support trailing dot.

### Steps to Reproduce

1. Trailing dot support enabled
2. Go to a file share container
3. Go to a directory that ends in a trailing dot
4. Try to preview a pdf or open a video in browser within the trailing dot directory

### Actual Experience

<img width="922" alt="Screenshot 2023-06-14 at 11 20 02 AM" src="https://github.com/microsoft/AzureStorageExplorer/assets/111301956/f023b9db-1e6c-4d8c-bb76-089b6d1f4c3a">

**Comment by MRayermannMSFT** [comment]
This bug happens because the allow trailing dot header needs to be set when accessing files in a directory with a trailing dot. The browser (for play in browser) and PDF fetch-thing in Chromium/Electron (for PDF preview) do not send this header. Not much we can do now, probably best to just wait for the service to no longer require the header.
