### ISSUE TITLE
Clicking 'Open Folder' doesn't do anything with 'Use AzCopy for Improved Blob Upload and Download' checked

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#699]
Storage Explorer Version: 1.5.0
Platform/OS Version: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
Architecture: ia32
Build Number:20180826.5
Commit: d6717c99
Regression From: Not a regression

#### Steps to Reproduce: ####
1. Navigate to 'Experimental' menu -> Select ‘Use AzCopy for Improved Blob Upload and Download’.
2. Open one blob container which contains one blob at least -> Download a blob.
3. After downloading successfully -> Click ‘Open Folder’ in Activities panel.

#### Expected Experience: ####
Clicking ‘Open Folder’ works well.

#### Actual Experience: ####
Clicking 'Open Folder' doesn't do anything.

**Comment by MRayermannMSFT** [comment]
Fixed in 20180927.3.
