### ISSUE TITLE
It would be better to mention tag key valid characters in the error message of the 'Upload Files' dialog that includes 'Tags' section

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6993]
**Storage Explorer Version**: 1.31.0-dev
**Build Number**: 20230615.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4 (Apple M1 Pro)
**Architecture**: x64
**How Found**: ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Click 'Upload -> Upload Files...'.
3. Type an invalid tag key (Like ',') -> There is an error message.
4. Observe the error message.

## Expected Experience ##
It would be better to mention tag key valid characters in the error message. 

The screenshot for 'Edit Tags' dialog.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/6e772dca-0a5b-454a-a2a9-2b1c773053ce)

## Actual Experience ##
Not mention valid characters in the error message.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/0758e61c-360e-4ed8-abb1-fb02ccb0f3fd)

## Additional Context ##
It is better to add a notification message that telling you can add up to 10 tags if there are already 10 tags.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230801.4. Fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/a3e2f308-ba61-4772-afd8-6f5af486bc74)
