### ISSUE TITLE
Storage Explorer doesn't open on Ubuntu 22.04

### ISSUE THREAD

**Issue by toomer** [microsoft/AzureStorageExplorer#6994]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.30

### Architecture

x64

### Platform

Linux (snap)

### OS Version

Ubuntu 22.04

### Bug Description

The storage explorer don't open on the Ubuntu 22.04 with Wayland windows system
Here is the error message:

$ storage-explorer 
[2023-06-15T10:16:00.208Z] (main:33696) <NONE> Log file: /home/erobtom/snap/storage-explorer/51/.config/StorageExplorer/logs/2023-06-15_111600/2023-06-15_111600_main_33696.log
[2023-06-15T10:16:00.212Z] (main:33696) <NONE> Log level: info
[2023-06-15T10:16:00.213Z] (main:33696) <INFO> Startup app state:  {
    lastWindowState: { rect: { x: 0, y: 27, width: 1000, height: 768 }, maximized: false },
    disableGpu: false,
    dialogAutoResponse: {}
  }
[2023-06-15T10:16:00.397Z] (main:33696) <INFO> Calling handleQuitOrRelaunch from quit
[2023-06-15T10:16:00.397Z] (main:33696) <INFO> Quitting, sessionEnded: false, force: true, quitOrRelaunch: quit
[2023-06-15T10:16:00.397Z] (main:33696) <ERRO> Error occurred while trying to actually quit: {}
[2023-06-15T10:16:00.397Z] (main:33696) <INFO> Calling quit, bye!
Gtk-Message: 11:16:00.401: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

### Steps to Reproduce

1. Get Ubuntu 22.04 with Wayland windows system (default one)
2. Install Storage Explorer from snap
3. Try to open it: $ storage-explorer 

### Actual Experience

Storage Explorer don't open on Ubuntu 22.04

### Additional Context

Log file:
$ cat /home/erobtom/snap/storage-explorer/51/.config/StorageExplorer/logs/2023-06-15_111600/2023-06-15_111600_main_33696.log
[2023-06-15T10:16:00.212Z] (main:33696) <NONE> Log level: info
[2023-06-15T10:16:00.213Z] (main:33696) <INFO> Startup app state:  {
    lastWindowState: { rect: { x: 0, y: 27, width: 1000, height: 768 }, maximized: false },
    disableGpu: false,
    dialogAutoResponse: {}
  }
[2023-06-15T10:16:00.397Z] (main:33696) <INFO> Calling handleQuitOrRelaunch from quit
[2023-06-15T10:16:00.397Z] (main:33696) <INFO> Quitting, sessionEnded: false, force: true, quitOrRelaunch: quit
[2023-06-15T10:16:00.397Z] (main:33696) <ERRO> Error occurred while trying to actually quit: {}
[2023-06-15T10:16:00.397Z] (main:33696) <INFO> Calling quit, bye!

**Comment by craxal** [comment]
@toomer Can you go into more detail about your system? Do you have more precise repro steps? Are you trying to remotely log into the Ubuntu machine? Are there other snaps, such as VS Code, that also have problems running? Can you share Storage Explorer log files with us?

**Comment by John-Vance** [comment]
I am seeing identical behavior and identical log file with an identical configuration. Installed via snap from the Ubuntu Software application. VS Code installed the same way is working great. On first launch, it requests me to run `https://github.com/microsoft/AzureStorageExplorer/issues/6994`, which I do, but it fails silently on subsequent launches.

**Comment by craxal** [comment]
@John-Vance Just to clarify, when you say you're seeing identical behavior/logs/configurations,  you mean identical to what the issue author has posted? And when you say it fails silently, you mean Storage Explorer fails to launch?

Here's one thing you can try, which will tell us if the problem is with the snap. Can you try using the .tar.gz distribution of Storage Explorer? Does it consistently launch and work correctly? You may have to install other dependencies to get it to work.

**Comment by John-Vance** [comment]
Correct—same behavior, setup, and log file content as the author. Nothing happens when trying to launch it from the shortcut in the application menu, but it does generate the log file in the background. Good idea on the .tar.gz, I will try that out today and let you know the results.

________________________________

**Comment by John-Vance** [comment]
@craxal The .tar.gz version works perfectly after installing the dotnet6 package. And after installing dotnet6, the snap version is working perfectly as well!

**Comment by craxal** [comment]
Ah ha. Interesting. Well, the .NET 6 requirement should have been taken care of in the snap, so looks like we need to make sure that's working correctly. Glad you you were able to get it working!

**Comment by John-Vance** [comment]
Yeah, thanks for your help! I could be crazy, but try the current snap available in Ubuntu Software for yourself on a vanilla 22.04 system without dotnet6 installed. The .tar.gz version would launch without it, but wouldn't do the AAD/MFA auth in the browser until I installed it.

**Comment by craxal** [comment]
@John-Vance Yes, I can confirm a clean Ubuntu install won't run Storage Explorer. How did you install .NET 6? Did you install any snaps, or did you install using the instructions on the .NET website?

**Comment by John-Vance** [comment]
I didn't see any snaps for it, I just did an apt install dotnet6, I guess it's already in the default repos.
________________________________

**Comment by craxal** [comment]
@toomer @John-Vance Installing .NET 6 as mentioned did not resolve the issue for me, but I believe I've found the root of the issue. Let me know if this helps.

On a new installation of Ubuntu, the password manager may not create a default password keyring. Storage Explorer normally does this at first launch (you'd see a confirmation dialog), but for some reason it doesn't (could be due to issues in the "unintrusive" dialog notification system Ubuntu uses). To get around this:
1. Open Passwords and Keys.
2. Create a new password keyring.
3. Set the new keyring as the default.
4. Relaunch Storage Explorer.

**Comment by John-Vance** [comment]
Hi Craig, thanks for reaching out, and good timing. I haven't seen the original issue again, but I'm seeing a similar one now with new users (who are sudoers) connecting to the system. After trying to connect to an Azure account, it hangs for several seconds when it would normally be expected to open a browser window for authentication, and eventually gives this error:

[cid:ce64349a-248f-4079-b0a5-d8ffdbe9bba6]

This is even after installing the latest snap and installing/updating the dotnet6 apt package. It also occurs with the .tar.gz version. I've tried deleting/recreating the user's keyring and also re-running the snap command from the first time setup under the user's profile, but same issue. It works fine under local accounts; it seems to only be affecting our AD-authenticated users in Ubuntu.

Best regards,

 ~ John

________________________________

**Comment by craxal** [comment]
@John-Vance GitHub doesn't support sharing images from emails. Can you repost your image using the website?

**Comment by John-Vance** [comment]
Absolutely, thanks for your guidance.

**Comment by craxal** [comment]
Closing this issue due to lack or response from original author. If the mitigation steps above resolve your issue, please let us know. Otherwise, you may open a new issue.

**Comment by jose7165** [comment]
> @toomer @John-Vance Installing .NET 6 as mentioned did not resolve the issue for me, but I believe I've found the root of the issue. Let me know if this helps.
> 
> On a new installation of Ubuntu, the password manager may not create a default password keyring. Storage Explorer normally does this at first launch (you'd see a confirmation dialog), but for some reason it doesn't (could be due to issues in the "unintrusive" dialog notification system Ubuntu uses). To get around this:
> 
> 1. Open Passwords and Keys.
> 2. Create a new password keyring.
> 3. Set the new keyring as the default.
> 4. Relaunch Storage Explorer.

FYI, these steps worked for me. Ubuntu 22.04, installed Azure Storage Explorer via Snap.

**Comment by FabianTr13** [comment]
It works in ubuntu 23, if the message about key appears, Open Passwords and Keys then delete the azure explore keys and relaunch the app.

**Comment by glaubermd-leaf** [comment]
> @toomer @John-Vance Installing .NET 6 as mentioned did not resolve the issue for me, but I believe I've found the root of the issue. Let me know if this helps.
> 
> On a new installation of Ubuntu, the password manager may not create a default password keyring. Storage Explorer normally does this at first launch (you'd see a confirmation dialog), but for some reason it doesn't (could be due to issues in the "unintrusive" dialog notification system Ubuntu uses). To get around this:
> 
>     1. Open Passwords and Keys.
> 
>     2. Create a new password keyring.
> 
>     3. Set the new keyring as the default.
> 
>     4. Relaunch Storage Explorer.

This solved my issue on Ubuntu 23.10. Storage Explorer from snap store is working.

**Comment by entmike** [comment]
> @toomer @John-Vance Installing .NET 6 as mentioned did not resolve the issue for me, but I believe I've found the root of the issue. Let me know if this helps.
> 
> On a new installation of Ubuntu, the password manager may not create a default password keyring. Storage Explorer normally does this at first launch (you'd see a confirmation dialog), but for some reason it doesn't (could be due to issues in the "unintrusive" dialog notification system Ubuntu uses). To get around this:
> 
> 1. Open Passwords and Keys.
> 2. Create a new password keyring.
> 3. Set the new keyring as the default.
> 4. Relaunch Storage Explorer.

Thank you!  This solved my problem.

**Comment by pmcarballo** [comment]
I've fixed this issue in a different way.
In Passwords and Keys, I opened the default keyring. Then searched and opened every "Chromium Safe Storage" entry; one of them was created by the StorageExplorer application. I delete it and then started the Storage Explorer application without errors.

**Comment by paolo-lulli** [comment]
I have exactly the same issue: basically the *.tar.gz installer is useless, since it does not work by itself.

**Comment by jthom1** [comment]
I installed the edge version of storage explorer and it launched fine for me

**Comment by dagord** [comment]
I encountered the same problem on Ubuntu 20.04 as well.
I tried installing Dotnet6 runtime libraries running `sudo apt-get install -y dotnet-runtime-6.0` but this didn't help.
Creating a new keyring as suggested above solved the problem

**Comment by uville** [comment]
Also encountered this problem with Ubuntu 24.04 LTS.

Creating a new default keyring solved the problem.

**Comment by yshahin** [comment]
I fixed the problem by
1) installing storage account from snap
  * using this command if you want terminal install ```sudo snap install storage-explorer```
2) Before opening the app run this command
  * sudo snap connect storage-explorer:password-manager-service :password-manager-service
 3) then open storage explorer

Apparently when you get the error to enable keyring to access it goes into this load failure.
