### ISSUE TITLE
The Get Started and Release Notes panel all open if Storage Explorer is a new installation

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6997]
**Storage Explorer Version:** 1.31.0-dev
**Build Number:** 20230616.3
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4 (Apple M1 Pro)
**Architecture:** x64
**How Found:** From running test cases
**Regression From:** Previous release (1.30.0)

## Steps to Reproduce ##

1. Uninstall Storage Explorer.
2. Delete all Storage Explorer data from %AppData%.
3. Launch the install executable from the current build.
4. Check whether the Get Started opens and Release Notes doesn't open.

## Expected Experience ##

1. The Get Started opens.
2. The Release Notes doesn't open.

## Actual Experience #
1. The Get Started opens.
2. The Release Notes opens.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230627.1. Fixed.
