### ISSUE TITLE
Stop prompting to login when there are accounts added by name/key

### ISSUE THREAD

**Issue by JakeRadMSFT** [Microsoft/AzureStorageExplorer#7]
Storage Explorer Version: 0.9.6

OS Version: Windows 10 (All)

Steps to Reproduce:

1. Open Storage Explorer with only an account added by Name/Key

Expected Experience:
Not continuously prompted to login.

Actual Experience:
Continuously prompted to login.

**Comment by MRayermannMSFT** [comment]
Fixed on master.
