### ISSUE TITLE
Final page of installer indicates to click finish but button text reads next

### ISSUE THREAD

**Issue by bgklein** [Microsoft/AzureStorageExplorer#70]
**Storage Explorer Version:**
1.0.0
**OS Version:**
Win10
**Steps to Reproduce:**

1. Download Installer from  https://azure.microsoft.com/en-us/features/storage-explorer/
2. Proceed to final page of install

**Expected Experience:**
Button to say finish
**Actual Experience:**
Button indicates a next page

**Comment by MRayermannMSFT** [comment]
Fix merged into master.

![image](https://user-images.githubusercontent.com/21112697/39274596-5ef5b612-4897-11e8-92ab-d81ce8583492.png)

Thank you for the bug report @bgklein !
