### ISSUE TITLE
Clicking 'Upload' doesn't do anything in Upload dialog with 'Use AzCopy for Improved Blob Upload and Download' checked

### ISSUE THREAD

**Issue by v-haiz** [Microsoft/AzureStorageExplorer#700]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture**: ia32/x64
**Build Number**: 20180926.5
**Commit**: d6717c99
**Regression From**: Not a regression

**Steps to Reproduce**:
1. Navigate to 'Experimental' menu -> Check 'Use AzCopy for Improved Upload and Download'.
2. Open one **blob container** then open Upload dialog -> Select a blob to upload.
3. Check the result after clicking 'Upload' button in Upload dialog.   

**Expected Experience**:
Succeed to upload the selected blob after clicking 'Upload' button .

**Actual Experience**:
It doesn't do anything after clicking 'Upload' button.

**Comment by MRayermannMSFT** [comment]
I believe this was due to a build issue. Please try again with 20180927.3.
