### ISSUE TITLE
Attempting to preview parquet on 1.30

### ISSUE THREAD

**Issue by gpcottle** [microsoft/AzureStorageExplorer#7002]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.30.0

### Architecture

x64

### Platform

All

### Bug Description

Trying to view parquet files and get the following error:
{
  "name": "TypeError",
  "message": "o.buffer.readUInt32LE is not a function",
  "stack": "TypeError: o.buffer.readUInt32LE is not a function\n    at ZR (file:///C:/Program%20Files/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:736826)\n    at Object.QR (file:///C:/Program%20Files/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:736928)\n    at Tn (file:///C:/Program%20Files/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:764741)\n    at rD (file:///C:/Program%20Files/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:766114)\n    at async sb (file:///C:/Program%20Files/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:765449)\n    at async fb (file:///C:/Program%20Files/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:767625)\n    at async Mu.readRowGroup (file:///C:/Program%20Files/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:763489)\n    at async Object.next (file:///C:/Program%20Files/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:756357)\n    at async ParquetParser.getRecords (file:///C:/Program%20Files/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:5046)\n    at async getParquetData (file:///C:/Program%20Files/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:6298)"
}

### Steps to Reproduce

1 Launch Storage Explorer
2 Browse to Parquet file
3 Attempt to preview

### Actual Experience

Error message:
{
  "name": "TypeError",
  "message": "o.buffer.readUInt32LE is not a function",
  "stack": "TypeError: o.buffer.readUInt32LE is not a function\n    at ZR (file:///C:/Program%20Files/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:736826)\n    at Object.QR (file:///C:/Program%20Files/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:736928)\n    at Tn (file:///C:/Program%20Files/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:764741)\n    at rD (file:///C:/Program%20Files/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:766114)\n    at async sb (file:///C:/Program%20Files/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:765449)\n    at async fb (file:///C:/Program%20Files/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:767625)\n    at async Mu.readRowGroup (file:///C:/Program%20Files/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:763489)\n    at async Object.next (file:///C:/Program%20Files/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:756357)\n    at async ParquetParser.getRecords (file:///C:/Program%20Files/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:5046)\n    at async getParquetData (file:///C:/Program%20Files/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:6298)"
}

**Comment by cf-dtrznadel** [comment]
I experienced same issue

**Comment by ghormann** [comment]
I aloo experience same

**Comment by JasonYeMSFT** [comment]
I am going to close this issue and track in #6990 instead. This is very likely due to your data being compressed. The library we use for parsing data is not converting decompressed data back to buffer correctly which may lead to this problem. Please let us know if your data is not compressed.
