### ISSUE TITLE
Upgrade for x64: "updated" version missing Taskbar Icon.

### ISSUE THREAD

**Issue by OzBob** [microsoft/AzureStorageExplorer#7004]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.30.0

### Regression From

1.29.0

### Architecture

x64

### Storage Explorer Build Number

20230609.2

### Platform

Windows

### OS Version

Windows 11

### Bug Description

install new version and Taskbar link, removed, and new one has missing icon. 

### Steps to Reproduce

install 1.30
Open via startmenu, 

### Actual Experience

![image](https://github.com/microsoft/AzureStorageExplorer/assets/1796771/14f9476c-754c-442d-981d-996e4642f1cf)

### Expected Experience

icon from exe available for windows
the path to task bar items should be updated

### Additional Context
closed and openned after installing, still not there.

Right click on shortcut to change icon and get "can't find" error

![image](https://github.com/microsoft/AzureStorageExplorer/assets/1796771/b9bd39ab-9e8c-432b-be69-aafc18af9a40)

install location of exe moved to 'user':
C:\Users\{userid}\AppData\Local\Programs\Microsoft Azure Storage Explorer\
but the install wizard did not prompt for 'only me' installation, and certainly no different from previous upgrades.

Either the defaults in the installation wizard have changed or the default installation location has changed, but certainly not by me or actively choosing a different location in the wizard.

Did you do a test the 32-64 "upgrade"(uninstall-reinstall) process on a test Windows 11 PC?  Should that procedure be a new step in your build/release process?

**Comment by MRayermannMSFT** [comment]
Hi @OzBob

> Did you do a test the 32-64 "upgrade"(uninstall-reinstall) process on a test Windows 11 PC? Should that procedure be a new step in your build/release process?

Yes. We did this scenario many different times. Windows 10, Windows 11, x64, ARM64, all user -> all user, all user -> cur user, cur user -> all user, cur user -> cur user, every matrix we could think of.

Could you please try:
1. Uninstall Storage Explorer, either via Windows settings or by going to the install location and running the uninstall executable
2. Restart your computer
3. Download 1.30 
4. Install
5. See if the icon is working well again

**Comment by mayureshs** [comment]
Hello, I am facing the same issue. I have followed the steps suggested above and reinstalled 1.3.0 but that did not help. Icon is missing when the program is opened. I have also deleted and restored IconCache.db file. Please help!

**Comment by MRayermannMSFT** [comment]
> Hello, I am facing the same issue. 

Hi @mayureshs, to be clear, are you just having a problem of the taskbar icon being blank, or can you also not launch Storage Explorer?

**Comment by mayureshs** [comment]
But this never happened in the previous versions of the Azure Storage Explorer. Was there a switch to move from Program Files (x86) to Program Files with this version upgrade ? Anyway, that can be updated in newer release so others don't experience the same issue ?

**Comment by MRayermannMSFT** [comment]
> Was there a switch to move from Program Files (x86) to Program Files with this version upgrade ?

Yes, as part of moving to 64 bit, the default all-user install location is now "Program Files".

> But this never happened in the previous versions of the Azure Storage Explorer. 

It has for others.

> Anyway, that can be updated in newer release so others don't experience the same issue ?

Based on the number of folks updated to 1.30 so far, we're fairly certain at this point that the issue you and the OP have run into are quirky Windows issues.

**Comment by OzBob** [comment]
> 'This should only be an issue if your 64 bit install ends up in a location different from your 32 bit install'

...**only**...

**Comment by MRayermannMSFT** [comment]
We'll be adding an explicit attempt to remove the task bar shortcut. You'll still need make a new one. If folks want the option to create a taskbar shortcut as part of install, we'll evaluate that request separately.

**Comment by MRayermannMSFT** [comment]
Unfortunately while performing more testing of our "remove taskbar icon during incompatible arch uninstall" we ran into some inconsistent/bad behavior by Windows. Despite removing the taskbar shortcut (using the APIs our installer makes available to us), taskbar shortcuts created for the newly-installed version were for some reason still using the old app path. This feels like a worse experience than the old taskbar shortcut not getting removed during uninstall, having to remove it manually (which seems to always work flawlessly), and then add for the new one.

We don't have any other options at this time for removing the old taskbar shortcut programmatically, so for now we are won't fixing this. Sorry to have gotten folks' hopes up.
