### ISSUE TITLE
abc

### ISSUE THREAD

**Issue by snazzybloke** [microsoft/AzureStorageExplorer#7005]

**Comment by JasonYeMSFT** [comment]
Your attachment is using your AAD credential to authenticate. Could you go to the container in Azure Portal to see if you are given the necessary roles to read data in it (e.g. Storage Blob Data Reader, Storage Blob Data Contributor, etc.)? If none of your roles are giving you access, you could have your user identity added in the access control list of the container and the directory your are trying to list under. Try right click on the directory and select `Manage Access Control Lists...` to see if you are in it. If you get an access denied error, you may need to get someone who has the permission to manage it add you.

In general, if you are not the owner of this container and is getting permissions from the owner. I recommend you to talk to the owner and make sure you are given the right permissions to it.
