### ISSUE TITLE
It would be better to update the warning 'Please input a number between 0 and 1000' to 'Please input a number between 1 and 1000' next to the 'Show top results' for tables

### ISSUE THREAD

**Issue by v-sunnsun** [microsoft/AzureStorageExplorer#7006]
**Storage Explorer Version**: 1.31.0-dev
**Build Number**: 20230619.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4 (Apple M1 Pro)
**Architecture**:  x64
**How Found**: ad-hoc testing
**Regression From**:  Not a regression

## Steps to Reproduce 

1. Expand one storage account -> Tables.
2. Create a table -> Click 'Query' in its toolbar.
3. Expand the 'Advanced Options' -> Type an invalid value into the 'Show top results' field.
4. Observe the warning next to the 'Show top results'.

## Expected Experience 
It would be better to update the warning 'Please input a number between 0 and 1000' to 'Please input a number between 1 and 1000'.

## Actual Experience ##
The warning is 'Please input a number between 0 and 1000'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/122582307/0342f4db-2261-40b4-9b8d-36e6c99baf61)

**Comment by JasonYeMSFT** [comment]
Apparently we don't allow entering 0 now. Let's change the string.

**Comment by v-xianya** [comment]
Verifed this issue on the main build 20230731.1. Reproduce.
We are going to re-open this issue and close it once it got fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/bcd818d8-6b09-4f33-aefd-fddf00530529)

**Comment by v-xianya** [comment]
Verified this issue on the build 20230802.3. Fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/9355d4ac-847e-4b53-a5f0-588497771387)
