### ISSUE TITLE
The textbox does not turn red in the Access Policies dialog when start time is greater than expire time

### ISSUE THREAD

**Issue by v-sunnsun** [microsoft/AzureStorageExplorer#7007]
**Storage Explorer Version**: 1.31.0-dev
**Build Number**: 20230619.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4 (Apple M1 Pro)
**Architecture**:  x64
**How Found**: From running test cases
**Regression From**:  Previous release (1.30.0)

## Steps to Reproduce 

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Right click the blob container -> Click 'Manage Stored Access Policies...'.
3. Add one access policies.
4. Change the start time to make it is greater than the expire time.
5. Check whether the textbox is red and the 'Save' button is disabled.

## Expected Experience 
The textbox is red and the 'Save' button is disabled.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/122582307/6f2726c1-43b8-4ab7-8977-b2f7594bbb19)

## Actual Experience ##
The textbox does not turn red and the 'Save' button is enabled.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/122582307/751259dd-d127-4d5f-8c73-dc30a9e25ea3)

## Additional Context ##
This issue also reproduces for file shares/queues/tables.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230620.3. Fixed. So, we are going to close it.
