### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by elcuevero** [microsoft/AzureStorageExplorer#7009]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.30

### Architecture

i86

### Storage Explorer Build Number

20230609.2

### Platform

All

### OS Version

Server 2019

### Bug Description

Issue happens in customer network on all machines. Get error when expanding file share no matter what suscription I'm accessing. Issue does not happen with other resources. Ran OpenSSL to grab certificate information and create CER file as suggested here but still happens: https://github.com/CawaMS/StorageExplorerTroubleshootingGuide/blob/master/se-troubleshooting-guide.md#self-signed-certificate-in-certificate-chain

### Steps to Reproduce

1. Open ASE
2. expand suscription
3. expand storage accounts
4. select account and expand it
5. select File Share

### Actual Experience

Get the following error when opening file shares
Unable to retrieve child resources

ProducerError:{
  "name": "RestError",
  "message": "request to https://stitcdev001.file.core.windows.net/?comp=list failed, reason: getaddrinfo ENOTFOUND stitcdev001.file.core.windows.net",
  "stack": "RestError: request to https://stitcdev001.file.core.windows.net/?comp=list failed, reason: getaddrinfo ENOTFOUND stitcdev001.file.core.windows.net\n    at NodeFetchHttpClient.sendRequest (C:\\Program Files\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\file-extension\\dist\\src\\index.js:2:161214)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async CoreHttpLogHttpClient.sendRequest (C:\\Program Files\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\file-extension\\dist\\src\\index.js:2:509049)\n    at async StorageRetryPolicy.attemptSendRequest (C:\\Program Files\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\file-extension\\dist\\src\\index.js:2:387904)\n    at async StorageClientContext.sendOperationRequest (C:\\Program Files\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\file-extension\\dist\\src\\index.js:2:206790)\n    at async ShareServiceClient.listSharesSegment (C:\\Program Files\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\file-extension\\dist\\src\\index.js:2:458297)",
  "code": "REQUEST_SEND_ERROR",
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://stitcdev001.file.core.windows.net/?comp=list",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2022-11-02"
        },
        "accept": {
          "name": "Accept",
          "value": "application/xml"
        },
        "user-agent": {
          "name": "User-Agent",
          "value": "Microsoft Azure Storage Explorer/1.30.0 (win32) azsdk-js-storagefile/12.14.0 (NODE-VERSION v18.14.0; Windows_NT 10.0.17763)"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "b7fbd8d2-ace1-425f-aab1-9b12ff3b7b8f"
        },
        "x-ms-date": {
          "name": "x-ms-date",
          "value": "Mon, 19 Jun 2023 23:14:55 GMT"
        },
        "authorization": {
          "name": "authorization",
          "value": "Signed SharedKey Redacted="
        }
      }
    },
    "withCredentials": false,
    "timeout": 0,
    "keepAlive": true,
    "decompressResponse": false,
    "requestId": "b7fbd8d2-ace1-425f-aab1-9b12ff3b7b8f",
    "operationSpec": {
      "path": "/",
      "httpMethod": "GET",
      "responses": {
        "200": {
          "bodyMapper": {
            "serializedName": "ListSharesResponse",
            "xmlName": "EnumerationResults",
            "type": {
    

### Expected Experience

Expect to open file shares

**Comment by JasonYeMSFT** [comment]
Could you try enabling use system proxy in the proxy settings?

**Comment by elcuevero** [comment]
Thanks Jason,

I just did and get a different error: 
Unable to retrieve child resources

ProducerError:{
  "name": "Error",
  "message": "net::ERR_NAME_NOT_RESOLVED",
  "stack": "Error: net::ERR_NAME_NOT_RESOLVED\n    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49509)\n    at SimpleURLLoaderWrapper.emit (node:events:513:28)"
}

**Comment by JasonYeMSFT** [comment]
Both errors indicate that your file share url "stitcdev001.file.core.windows.net" cannot be resolved. Could you try manually resolving it from the command line (e.g. using [nslookup](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/nslookup))? If it doesn't give you any results, you may need to contact your local network admin or the internet service provider to help you troubleshoot.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. This issue will no longer be monitored. If you are still encountering this issue we recommend opening a support ticket from the Azure portal. Alternatively you can open a new issue here.
