### ISSUE TITLE
Deleting lots of entities has performance issues

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#7010]
Deleting lots of entities takes a while and blocks the UI (or at least provides no indication of progress) until it finishes.

Deleting entities only requires specifying the partition and row keys of the entity to delete. Passing the rest of the entity is unnecessary and causes slow down because of all the data that has to pass process boundaries. In some cases, errors due to "insufficient resources" can be thrown.

Deletion is still slow and blocks UI even after reducing the amount of data that's passed around. The operation should be refactored as a job handler in order to provide non-blocking progress updates.

**Comment by craxal** [comment]
Unfortunately, passing keys does not solve the performance issues. We should still only pass keys, but it looks like the delete task needs to be refactored into a job handler so as to avoid blocking the UI thread.

**Comment by richardMSFT** [comment]
Can I close this issue? The PR that resolves the issue described in the title has been merged, but the underlying slow down of deleting entities hasn't. But I feel like that should be it's own separate issue.

**Comment by craxal** [comment]
The original intent of this issue was to track the performance issue observed when deleting entities. The original title was an overly optimistic assumption of the underlying problem. Don't close. Instead, I've renamed the issue and updated the initial comment.

**Comment by craxal** [comment]
I have merged some changes that resolves the network resource error by throttling the number of requests that get sent out. I plan on making one more change that ensures the UI doesn't block waiting for the operation to complete.

In a future milestone, I can work on refactoring the operation into a job that reports on the progress.
