### ISSUE TITLE
Copy/Paste bug #6653 is back in 1.30.0

### ISSUE THREAD

**Issue by SergeiKamnev** [microsoft/AzureStorageExplorer#7014]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.30.0

### Regression From

1.29.2

### Architecture

x64

### Platform

Windows

### Bug Description

Bug #6653 is back

### Steps to Reproduce

1. Install AzureStorageExplorer 1.30.0
2. Make steps in #6653

### Actual Experience

Copy/Paste doesn't work

### Expected Experience

Copy/Paste works

### Additional Context

Workaround: downgrade to 1.29.2

**Comment by JasonYeMSFT** [comment]
If you are running into this problem when working with v1 storage accounts, try setting the setting `Settings > Transfers > AzCopy > Preserve Blob Tags` to "Don't preserve". Attempting to preserve tags breaks AzCopy. If you frequently work with v1 storage account it's recommended to keep not preserving blob tags.

**Comment by SergeiKamnev** [comment]
Hello Jason. Is it 1.30 setting? I don't see such in 1.29.2
However, your suggestion helps me work around Clone issue in 1.29.2. When I do F2 ("Clone") and give new name, clone fails with same error. But Clone window has some checkboxes, including "Preserver Blob Tags". When I untick it, then clone goes smooth.
BTW, in previous versions, Clone worked in context of current folder in Blob container, but now Clone works in context of Blob container root. To me it looks a little embarrassing. Was it done by intent?

**Comment by JasonYeMSFT** [comment]
Yes, it is a 1.30.0 setting. The context change for clone is intended. The purpose is to allow people to clone to any directory in the container.

**Comment by SergeiKamnev** [comment]
Got it.
To me, context change for Clone is arguable solution. You could use approach like in other applications: when clone path starts with root "/" then use the path from the root of the container. If not, then use relative path, like earlier.
From my experience: Clone within same folder is reasonable, because it allows you to change folder name. Clone to another folder is not much usable, because I prefer pressing Copy in source and pressing Past in destination. Usually in such operation name change is not necessary.
