### ISSUE TITLE
"format JSON" option, changing data unexpectedly

### ISSUE THREAD

**Issue by elisonrj** [microsoft/AzureStorageExplorer#7015]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.30.0

### Architecture

x64

### Platform

Windows

### OS Version

Windows 11

### Bug Description

I apologize for any confusion. When we attempt to preview a JSON file, all the data appears to be correct. However, when you click on the "format JSON" option, some of them change unexpectedly.

### Steps to Reproduce

1. Launch Storage Explore.
2. Choose a container with a JSON file inside.
3. Select JSON file.
4. Cick in preview option.
5. Click in format json.

### Actual Experience

![image](https://github.com/microsoft/AzureStorageExplorer/assets/34030988/0e2093ac-35e5-473f-87e5-9f4fadc0d9bd)

![image](https://github.com/microsoft/AzureStorageExplorer/assets/34030988/b90113c5-fe92-4b98-be53-edf1a70e02c5)

**Comment by MRayermannMSFT** [comment]
@elisonrj this is a very interesting bug. Any chance you're able to share the JSON file, or some other file that reproduces the bug with us? You can drag and drop here on GitHub, or we can share an email for you to send it to. No worries if the data cannot be shared.

**Comment by elisonrj** [comment]
Hi @MRayermannMSFT , thank you for your fast response.

Yes, to protect all sensitive data within the company, I removed it and kept only the necessary. So, I created a new file and tried to reproduce the same scenario. Fortunately, it's still happening. Below, I'm sending the file and a video that provides a better view of the bug in action.

[#7015 - format JSON.zip](https://github.com/microsoft/AzureStorageExplorer/files/11856542/7015.-.format.JSON.zip)

**Comment by MRayermannMSFT** [comment]
@elisonrj I see what the issue is.

You have the field `"numSerie": 101000001716225757`. The value of this field is a number. However, this number is larger than the max number size for JavaScript. This is a problem because we use this JavaScript code to obtain a formatted version of your data:

```js
JSON.stringify(JSON.parse(data), undefined, 2)
```

We will look into if there is anything we can do about this. We'll update this issue when we know more.
