### ISSUE TITLE
There is no error on 'Clone and Rehydrate' dialog when typing the source blob container name to 'Destination blob container' if typing a valid blob container name previously

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7017]
**Storage Explorer Version**: 1.31.0-dev
**Build Number**: 20230625.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4 (Apple M1 Pro)
**Architecture**: x64/arm64
**How Found**: ad-hoc testing
**Regression From**: Previous release (1.29.2)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create two blob containers named 'bc01, bc02'-> Upload one blob to blob container 'bc01'.
3. Change the access of the blob to 'Archive'.
4. Right click the blob -> Click 'Clone and Rehydrate...'.
5. Type 'bc02' to 'Destination blob container' field -> The error for 'Destination blob name' field the disappears.
6. Delete 'bc02' -> Type 'bc01' to 'Destination blob container' field.
7. Check whether the error for 'Destination blob name' field appears.

## Expected Experience ##
The error for 'Destination blob name' field appears.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/d2e393d1-fcd1-43be-801c-0a9d554976a6)

## Actual Experience ##
The error for 'Destination blob name' field doesn't appear.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/01b46249-2ec2-4b89-b6fe-7a1b6bc2f582)

## Additional Context ##

1. This issue also reproduces when copying one archived blob.
2. This issue can't be reproduced consistently.

**Comment by v-xianya** [comment]
This issue reproduces on 1.31.0 version and the main build 20230810.9. So, we are going to re-open it.

**Comment by JasonYeMSFT** [comment]
This is probably due to a very rare race condition. We are going to won't fix this for now.
