### ISSUE TITLE
The localized string 'Local' on the 'Shared Access Signature', 'Custom Timestamp Query' dialog doesn't show in one line

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7018]
**Storage Explorer Version:** 1.31.0-dev
**Build Number:** 20230625.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4 (Apple M1 Pro)
**Architecture:** x64/arm64
**Language:** Japanese/Korean/zh-CN/zh-TW
**How Found:** From running test cases
**Regression From:** Not a regression

## Bug Description ##

1. The localized string 'Local' on the 'Shared Access Signature' dialog doesn't show in one line.
2. The localized string 'Local' on the 'Custom Timestamp Query' dialog doesn't show in one line.
3. The localized strings 'Field' and 'Operator' under query builder don't show in one line.

## Steps to Reproduce ##

1. Open 'Settings' -> Application (Regional Settings) -> Select '日本語' -> Restart Storage Explorer.
2. Select and right click one storage account -> Click ‘Shared Access Signature...'.
3. Observe the 'Time zone' part.
5. Check whether the localized string 'Local' shows in one line.

## Expected Experience ##
The localized string 'Local' shows in one line.

## Actual Experience ##
The localized string 'Local' doesn't show in one line.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/b41c0c36-719d-4786-b1b6-507b44725931)

## Addition Context ##
1. The screenshot for the 'Custom Timestamp Query' dialog:
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/60bb4a3b-ccf5-44fb-81ad-e5b10d564236)
2. The screenshot under the query builder after clearing query:
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/8a181e1f-c128-4ab1-8395-cab7d08a0da0)
3. The localized strings 'And/Or' 'Field' 'Operator' and 'Type' don't show in one line under Korean/zh-CN/zh-TW.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/2733dc69-f5d0-4a6e-8b17-7d69c6ca5d59)

**Comment by v-kellyluo** [comment]
@craxal,  verified this issue on the build 20230629.1, it doesn't reproduce on the 'Custom Timestamp Query' dialog and the strings under the query builder, but it still reproduces on the 'Shared Access Signature' dialog, so we are going to reopen it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/99f1d581-add4-4d6e-b707-bdbb266b3b4b)

**Comment by craxal** [comment]
@v-kellyluo I must have missed this in the details. Merged a fix for the SAS dialog.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230702.1. Fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/9863fd30-cec8-49bc-9f68-0a98aab32d51)
