### ISSUE TITLE
Display of settings within "Set Container Public Access level" window does not represent previous setting selection

### ISSUE THREAD

**Issue by Richard-Parish** [microsoft/AzureStorageExplorer#702]
**Storage Explorer Version**: 1.4.2
**Platform/OS Version**: Windows Server 2008 R2
**Architecture**: ia32
**Regression From**:  Unsure

#### Steps to Reproduce: ####

1. Created a <user generated blob container> under "Storage-Accounts - Local-1 (Key) - Blob Containers".
2. Hover cursor over <user generated blob container>, select right-hand mouse button and select "Set Public Access Level ..."
3. Within the Set Container Public Access level window select "Public read access for container and blobs" or "Public read access for blobs only"
4. Select the Apply button.
5. Hover cursor over <user generated blob container>, select right-hand mouse button and re-select "Set Public Access Level ..."
6. Review the radio button selected in the Set Container Public Access level window.

#### Expected Experience: ####

Either "Public read access for container and blobs" or "Public read access for blobs only" radio buttons should be selected (as applicable).

#### Actual Experience: ####

"No public access" radio button selected.

**Comment by MRayermannMSFT** [comment]
I fixed this sometime around last May. Just verified the behavior is still working in 1.12. 🙃
