### ISSUE TITLE
The content of the pasted file is same as the base blob when pasting one blob snapshot to one file share

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7021]
**Storage Explorer Version:** 1.31.0-dev
**Build Number:** 20230625.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4 (Apple M1 Pro)
**Architecture:** x64/arm64
**How Found:** ad-hoc testing
**Regression From:** Not a regression
 
## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload a blob.
3. Open the blob -> Make some changes and save it.
4. Create a snapshot for the blob -> Switch to snapshots view -> Copy the snapshot.
5.  Open one file share -> Paste the snapshot to the file share -> Open the file.
6. Check whether the content of the file is same as the snapshot.

## Expected Experience ##
The content of the file is same as the snapshot.

## Actual Experience ##
The content of the file is same as the base blob.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230704.7. Fixed. So, we are going to close it.
