### ISSUE TITLE
Unable to retrieve child resources  ProducerError:{   "message": "{}" }

### ISSUE THREAD

**Issue by farisakmall** [microsoft/AzureStorageExplorer#7026]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.30.0

### Architecture

i86

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Unable to retrieve child resources

ProducerError:{
  "message": "{}"
}

### Steps to Reproduce

1. Launch Storage Explorer
2. Click 'Refresh all' on explorer

### Actual Experience

![image](https://github.com/microsoft/AzureStorageExplorer/assets/96882997/7c1514de-860b-448b-b3dd-568c2df4f8eb)

**Comment by julopera** [comment]
I am getting a similar error except the error that displays is:

```
Unable to retrieve child resources

ProducerError:{
  "name": "RestError",
  "message": "{\"odata.error\":{\"code\":\"AuthenticationFailed\",\"message\":{\"lang\":\"en-US\",\"value\":\"Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.}

...
...
...

  "details": {
    "errorCode": "AuthenticationFailed",
    "content-length": "299",
    "content-type": "application/json",
    "server": "Microsoft-HTTPAPI/2.0",
    "x-ms-request-id": "f38ae547-2002-0084-0518-aa551a000000",
    "date": "Wed, 28 Jun 2023 23:29:50 GMT",
    "odataError": {
      "code": "AuthenticationFailed",
      "message": {
        "lang": "en-US",
        "value": "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:f38ae547-2002-0084-0518-aa551a000000\nTime:2023-06-28T23:29:50.9810652Z"
```

**Comment by MRayermannMSFT** [comment]
@farisakmall assuming you can consistently reproduce this, can you please:
1. Go to Settings (gear on the left) > Application > Logging > set log level to Verbose
2. Restart Storage Explorer
3. Reproduce the error
4. Go to Help > Open Logs Directory, find the newest folder, zip it, and then drag and drop it here.

Thanks.

**Comment by farisakmall** [comment]
[2023-07-05_125156.zip](https://github.com/microsoft/AzureStorageExplorer/files/11954029/2023-07-05_125156.zip)

Hey @MRayermannMSFT, this is the file.

**Comment by MRayermannMSFT** [comment]
@farisakmall unfortunately I'm not seeing anything helpful in the logs.

- Can you go the account panel (person icon on the left), and make sure none of your tenants are requiring reauthentication?
- Can you tell me after what node being expanded you are getting this error?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue we recommend opening an Azure support ticket. Alternatively you can open a new issue here. This issue will no longer be monitored.
