### ISSUE TITLE
No icon shows for the refresh/expire notification for regular blob containers/queues

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7028]
**Storage Explorer Version**: 1.31.0-dev
**Build Number**: 20230628.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4.1 (Apple M1 Pro)
**Architecture**: x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.30.0)

## Steps to Reproduce ##
1. Open 'Settings' -> Select 'Data Explorers' -> Uncheck the setting 'Auto Refresh On Change'.
2. Expand one storage account -> Blob Containers.
3. Create a blob container -> Upload one blob.
4. There is a refresh notification.
5. Check whether the icon for the refresh notification shows well.

## Expected Experience ##
The icon for the refresh notification shows well.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/e9f218f5-5102-4c18-a84d-f38b49436e05)

## Actual Experience ##
No icon shows for the refresh notification.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/df4f10b5-781e-46de-ab71-72c39defa8d5)

## Additional Context ##
1. This issue reproduces for regular blob containers/queues.
2. This issue doesn't reproduce for ADLS Gen2 blob containers/file shares/tables.
3. Here is the screenshot for expired regular blob container/queue attachments.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/0b6858c3-1d15-4730-8905-6675fddd43d5)
4. Here is the screenshot for regular blob container/queue attachments that will be expired soon.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/a8c68db9-86cd-4e9a-af52-04374aec4f74)

**Comment by craxal** [comment]
A fix has been merged for blobs. Still working on a fix for queues.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230712.4. Fixed.
