### ISSUE TITLE
There is no error information bar when trying to open one expired table attachment whose SAS URL is generated by an access policy

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7029]
**Storage Explorer Version**: 1.31.0-dev
**Build Number**: 20230628.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4.1 (Apple M1 Pro)
**Architecture**: x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.30.0)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Right click the table.
3. Click 'Manage Stored Access Policies...' -> Add one access policy (set to expire after 2 minutes).
4. Attach the table via SAS URL generated by the access policy.
5. Open the table attachment after it expires.
6. Check whether there is an error information bar.

## Expected Experience ##
There is an error information bar.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/d0138dc2-d3ae-4567-88e4-c2a7517f8704)

## Actual Experience ##

1. There is no error information bar.
2. The table explorer displays as blank.

![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/afbe92ed-d411-4ebb-9417-df3b73a46a3d)
## Additional Context ##
This issue doesn't reproduce for other services.

**Comment by MRayermannMSFT** [comment]
My best guess is that this is related to recent networking work. I will investigate and reassign if needed.

**Comment by MRayermannMSFT** [comment]
This is not related to the recent networking changes. It seems that error handling was changed in commit a2b4a8695a6d39c69b4287adeccec9819e7b3cb0. The error handling code introduced in this commit results in an exception in the scenario described by the issue.

**Comment by craxal** [comment]
@MRayermannMSFT I'm not sure the commit ID you mentioned is the right one. That has a very small change in TopLevelNodesProvider.ts which does not appear to be related to error handling code at all.

**Comment by MRayermannMSFT** [comment]
> 846492319f1fdd6e00df35f4cac8652bf4388661

Yes. Sorry about that. Must've copied the wrong commit hash from my notes.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230709.3. Fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/7aa415cf-c03f-419e-9934-b64be9b27a08)
