### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by julopera** [microsoft/AzureStorageExplorer#7030]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.30.0

### Architecture

x64

### Storage Explorer Build Number

20230609.2

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Unable to retrieve child resources

ProducerError:{
  "name": "RestError",
  "message": "{\"odata.error\":{\"code\":\"AuthenticationFailed\",\"message\":{\"lang\":\"en-US\",\"value\":\"Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\\nRequestId:fc949abe-7002-0097-791d-aa60fb000000\\nTime:2023-06-29T00:07:12.8093835Z\"}}}",
  "stack": "RestError: {\"odata.error\":{\"code\":\"AuthenticationFailed\",\"message\":{\"lang\":\"en-US\",\"value\":\"Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\\nRequestId:fc949abe-7002-0097-791d-aa60fb000000\\nTime:2023-06-29T00:07:12.8093835Z\"}}}\n    at handleErrorResponse (C:\\Users\\jlope\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\table-extension\\dist\\src\\index.js:2:189356)\n    at deserializeResponseBody (C:\\Users\\jlope\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\table-extension\\dist\\src\\index.js:2:190070)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
  "statusCode": 403,
  "request": {
    "url": "https://thebraincloud9operations.table.core.windows.net/Tables",
    "headers": {
      "accept": "application/json;odata=minimalmetadata",
      "x-ms-version": "2019-02-02",
      "dataserviceversion": "3.0",
      "accept-encoding": "gzip,deflate",
      "user-agent": "Microsoft Azure Storage Explorer/1.30.0 (win32) azsdk-js-data-tables/13.1.2 core-rest-pipeline/1.9.0 Node/v18.14.0 OS/(x64-Windows_NT-10.0.22621)",
      "x-ms-client-request-id": "2df065b4-c96d-482d-90aa-bf49dc6fd841",
      "authorization": "Bearer JSON Web Token Redacted"
    },
    "method": "GET",
    "timeout": 0,
    "disableKeepAlive": false,
    "streamResponseStatusCodes": {},
    "withCredentials": false,
    "tracingOptions": {
      "tracingContext": {
        "_contextMap": {}
      }
    },
    "requestId": "2df065b4-c96d-482d-90aa-bf49dc6fd841",
    "allowInsecureConnection": true,
    "enableBrowserStreams": false
  },
  "response": {
    "status": 403,
    "headers": {
      "content-length": "299",
      "content-type": "application/json",
      "server": "Microsoft-HTTPAPI/2.0",
      "x-ms-request-id": "fc949abe-7002-0097-791d-aa60fb000000",
      "x-ms-error-code": "AuthenticationFailed",
      "date": "Thu, 29 Jun 2023 00:07:12 GMT"
    },
    "request": {
      "url": "https://thebraincloud9operations.table.core.windows.net/Tables",
      "headers": {
        "accept": "application/json;odata=minimalmetadata",
        "x-ms-version": "2019-02-02",
        "dataserviceversion": "3.0",
        "accept-encoding": "gzip,deflate",
        "user-agent": "Microsoft Azure Storage Explorer/1.30.0 (win32) azsdk-js-data-tables/13.1.2 core-rest-pipeline/1.9.0 Node/v18.14.0 OS/(x64-Windows_NT-10.0.22621)",
        "x-ms-client-request-id": "2df065b4-c96d-482d-90aa-bf49dc6fd841",
        "authorization": "Bearer JSON Web Token Redacted"
      },
      "method": "GET",
      "timeout": 0,
      "disableKeepAlive": false,
      "streamResponseStatusCodes": {},
      "withCredentials": false,
      "tracingOptions": {
        "tracingContext": {
          "_contextMap": {}
        }
      },
      "requestId": "2df065b4-c96d-482d-90aa-bf49dc6fd841",
      "allowInsecureConnection": true,
      "enableBrowserStreams": false
    },
    "bodyAsText": "{\"odata.error\":{\"code\":\"AuthenticationFailed\",\"message\":{\"lang\":\"en-US\",\"value\":\"Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\\nRequestId:fc949abe-7002-0097-791d-aa60fb000000\\nTime:2023-06-29T00:07:12.8093835Z\"}}}",
    "parsedBody": {
      "odataError": {
        "code": "AuthenticationFailed",
        "message": {
          "lang": "en-US",
          "value": "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:fc949abe-7002-0097-791d-aa60fb000000\nTime:2023-06-29T00:07:12.8093835Z"
        }
      }
    },
    "parsedHeaders": {
      "errorCode": "AuthenticationFailed",
      "content-length": "299",
      "content-type": "application/json",
      "server": "Microsoft-HTTPAPI/2.0",
      "x-ms-request-id": "fc949abe-7002-0097-791d-aa60fb000000",
      "date": "Thu, 29 Jun 2023 00:07:12 GMT"
    }
  },
  "details": {
    "errorCode": "AuthenticationFailed",
    "content-length": "299",
    "content-type": "application/json",
    "server": "Microsoft-HTTPAPI/2.0",
    "x-ms-request-id": "fc949abe-7002-0097-791d-aa60fb000000",
    "date": "Thu, 29 Jun 2023 00:07:12 GMT",
    "odataError": {
      "code": "AuthenticationFailed",
      "message": {
        "lang": "en-US",
        "value": "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:fc949abe-7002-0097-791d-aa60fb000000\nTime:2023-06-29T00:07:12.8093835Z"
      }
    }
  }
}

### Steps to Reproduce

1. Launch Storage Explorer
2. Expand a tables node

### Actual Experience

![image](https://github.com/microsoft/AzureStorageExplorer/assets/94776848/23068f0a-181c-421c-bbc9-47399a683ace)

**Comment by jinglouMSFT** [comment]
Are you behind a proxy?

**Comment by julopera** [comment]
I am not behind a proxy.

**Comment by MRayermannMSFT** [comment]
@julopera it looks like you are using OAuth to access your table resources. Can you please confirm what table RBAC permissions you have for storage account?

**Comment by julopera** [comment]
<img width="1916" alt="image" src="https://github.com/microsoft/AzureStorageExplorer/assets/94776848/60f14d2a-7c7e-40c2-a46f-f78378b0d217">

I am currently a Reader for this storage account.

**Comment by julopera** [comment]
Thanks, I'll try this and close this issue if everything works properly afterwards.

**Comment by julopera** [comment]
This is a Storage account (classic) resource, which does not have Storage Table Data Reader or Storage Table Data Contributor roles available.

**Comment by JasonYeMSFT** [comment]
We are told from the service team that classic storage accounts don't support accessing tables using Azure AD credentials. You will need to access it using either storage account key or SAS.
