### ISSUE TITLE
Parquet preview fails

### ISSUE THREAD

**Issue by andrePKI** [microsoft/AzureStorageExplorer#7031]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.30.0

### Architecture

x64

### Storage Explorer Build Number

20230609.2

### Platform

Windows

### OS Version

Windows Server 2016 1607

### Bug Description

Preview Parquet shows 'Unable to preview ...'.
details:
{
  "name": "TypeError",
  "message": "o.buffer.readUInt32LE is not a function",
  "stack": "TypeError: o.buffer.readUInt32LE is not a function\n    at ZR (file:///C:/Program%20Files/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:736826)\n    at Object.QR (file:///C:/Program%20Files/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:736928)\n    at Tn (file:///C:/Program%20Files/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:764741)\n    at rD (file:///C:/Program%20Files/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:766114)\n    at async sb (file:///C:/Program%20Files/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:765449)\n    at async fb (file:///C:/Program%20Files/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:767625)\n    at async Mu.readRowGroup (file:///C:/Program%20Files/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:763489)\n    at async Object.next (file:///C:/Program%20Files/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:756357)\n    at async ParquetParser.getRecords (file:///C:/Program%20Files/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:5046)\n    at async getParquetData (file:///C:/Program%20Files/Microsoft%20Azure%20Storage%20Explorer/resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:6298)"
}

### Steps to Reproduce

1. Launch Storage Explorer
2. Connect to Azure services with AAD Authn
3. Browse to Subscription with the required blob container (ADLS Gen2 with HNS enabled)
4. Select the blob (....parquet) and click  Preview button

### Actual Experience

"no data"

### Expected Experience

Data preview of the file contents

### Additional Context

parquet file is created by Synapse/Spark
parquet file can be read successfully through http://parquet-viewer-online.com/

**Comment by MRayermannMSFT** [comment]
Hi @andrePKI , the library we were using to parse Parquet files had some bugs in it. We've been contributing fixes back to the library, and once they ship a new version with our fixes, we'll be shipping that version as well. You can track our progress here: https://github.com/microsoft/AzureStorageExplorer/issues/6990
