### ISSUE TITLE
The expiration time is incorrect for the message whose 'Time to live' is set to 'None' on queue explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7033]
**Storage Explorer Version**: 1.31.0-dev
**Build Number**: 20230704.7
**Branch**: main
**Platform/OS**: Windows 10/MacOS Ventura 13.4.1 (Apple M1 Pro)
**Architecture**: x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Expand one storage account -> Queues.
2. Create a queue -> Click 'Add' -> Set 'Time to live' to 'None'.
3. Click 'OK' -> Observe the 'Expiration Time' of the message.
4. Check whether the expiration time is correct. 

## Expected Experience ##
The expiration time is correct.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/1e878a84-5da1-40b6-8eaf-ad5ad6415461)

## Actual Experience ##
The expiration time is incorrect.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/df9a50be-e525-49c8-af17-d4e02870498d)

## Additional Context ##
1. The 'Expiration time' is correct on 'View Message' dialog.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/4ee1da20-007c-4d44-9b71-c1a112792844)
2. This issue doesn't reproduce on Linux Ubuntu 20.04.
3. The screenshot on MacOS as below.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/fa4f8fbd-1b7a-42ed-a448-ffc8d2e37d43)

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230707.6. Fixed on Windows.
@MRayermannMSFT on MacOS. The expiration time is '01/01/10000'. Could you please help to take a look?
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/6a080a92-bfa4-4318-9c6e-5ff0fbe25b05)

**Comment by MRayermannMSFT** [comment]
WE'L

**Comment by MRayermannMSFT** [comment]
Ok, update! So the reason you are seeing that time is due to your machine's time zone. In the queue data grid, the times are shown in local time. This is by design. It is similar to how other date times in data grids, like blob last modified time, are shown in local time. I know that when y'all test on macOS, those are local machines you have at your desk. And since China is ahead of UTC time, it makes sense you are seeing a later time date.

**Comment by v-xianya** [comment]
Got it. thanks for your updates!
