### ISSUE TITLE
Not able to setup Storage explorer locally on my machine

### ISSUE THREAD

**Issue by naikra** [microsoft/AzureStorageExplorer#7034]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.30.0

### Architecture

x64

### Platform

Windows

### OS Version

Windows

### Bug Description

Unable to retrieve child resources

ProducerError:{
  "name": "FetchError",
  "message": "request to https://dbstorage22mbvml7pfczo.blob.core.windows.net/?comp=list&include=metadata failed, reason: self signed certificate in certificate chain",
  "stack": "FetchError: request to https://dbstorage22mbvml7pfczo.blob.core.windows.net/?comp=list&include=metadata failed, reason: self signed certificate in certificate chain\n    at ClientRequest.<anonymous> (C:\\Users\\NAIKRAK\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\blob-extension\\dist\\src\\index.js:2:2834516)\n    at ClientRequest.emit (node:events:513:28)\n    at TLSSocket.socketErrorListener (node:_http_client:502:9)\n    at TLSSocket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
  "type": "system",
  "errno": "SELF_SIGNED_CERT_IN_CHAIN",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}

### Steps to Reproduce

Launch explorer and try to setup

### Actual Experience

Unable to retrieve child resources

ProducerError:{
  "name": "FetchError",
  "message": "request to https://dbstorage22mbvml7pfczo.blob.core.windows.net/?comp=list&include=metadata failed, reason: self signed certificate in certificate chain",
  "stack": "FetchError: request to https://dbstorage22mbvml7pfczo.blob.core.windows.net/?comp=list&include=metadata failed, reason: self signed certificate in certificate chain\n    at ClientRequest.<anonymous> (C:\\Users\\NAIKRAK\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\blob-extension\\dist\\src\\index.js:2:2834516)\n    at ClientRequest.emit (node:events:513:28)\n    at TLSSocket.socketErrorListener (node:_http_client:502:9)\n    at TLSSocket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
  "type": "system",
  "errno": "SELF_SIGNED_CERT_IN_CHAIN",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}

**Comment by MRayermannMSFT** [comment]
@zachdialwynnlasvegas can you give using system proxy setting a try? You can read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. This issue will no longer be monitored. If you are still encountering this issue we recommend opening a support ticket from the Azure portal. Alternatively you can open a new issue here.
