### ISSUE TITLE
The app configuration name shows instead of full path when hovering over the opened tab

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7036]
**Storage Explorer Version**: 1.31.0-dev
**Build Number**: 20230706.6
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4.1 (Apple M1 Pro)
**Architecture**: x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand 'App Configurations' node -> Open one app configuration.
2. Hover over the opened tab.
3. Check whether a full path shows. 

## Expected Experience ##
A full path shows. 

The screenshot of a QA disk.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/781633fc-30e4-4cef-9118-623b097d579a)

## Actual Experience ##
Only show the app configuration name.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/76f25cea-136b-4229-8762-d1f332b95d9b)

**Comment by JasonYeMSFT** [comment]
Moving to 1.33.0 so if we ship a new version of app config extension, it can be included from there.

**Comment by v-kellyluo** [comment]
Verified this issue after installing app configuration extension 0.2.1. Fixed. So, we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/cbb02b8d-3398-44b4-96eb-ea39addd0bab)
