### ISSUE TITLE
Cannot create connection for Azure Account

### ISSUE THREAD

**Issue by spboyer** [microsoft/AzureStorageExplorer#704]
Version: 1.4.2

Platform: macOS
Architecture: x64
Build Number: 20180917.1
Commit: f66de7ea
Support Id: d02ab9b4-e6df-b370-42ae-f793c85261ca

Authentication Window is presented and never presents the ability, eventually goes away.

**Comment by MRayermannMSFT** [comment]
@spboyer , if you're still having auth issues, please let us know with a new issue. Thanks.
