### ISSUE TITLE
Authorization Failure via connection string

### ISSUE THREAD

**Issue by ASOS-NikhilGunda** [microsoft/AzureStorageExplorer#7041]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.30.0

### Architecture

i86

### Platform

All

### Bug Description

I tried to connect to one of the storage account I'm getting authorization Failure even after whitelisting my ip.

### Steps to Reproduce

1. Launch the storage explorer
2. Expand the blob container

### Actual Experience

I'm getting the following error: This storage account's 'Firewalls & virtual networks' settings may be blocking access to storage services. Try adding your client IP address to the firewall exceptions, or by allowing access from 'all networks' instead of 'selected networks'. 
<img width="542" alt="image" src="https://github.com/microsoft/AzureStorageExplorer/assets/101690959/d717323d-09d5-44d5-b7bb-7c89408cf9de">

### Expected Experience

need solution to connect to my storage account

**Comment by MRayermannMSFT** [comment]
@ASOS-NikhilGunda 

1. Can you share the full error with us?
2. How are you accessing your containers? Have you attached your storage account, or did you sign in and list the account underneath your subscription?

**Comment by ASOS-NikhilGunda** [comment]
Hi, 
1. I have attached error screenshots.
<img width="782" alt="blob issue" src="https://github.com/microsoft/AzureStorageExplorer/assets/101690959/3a0785bc-4608-4358-ab5e-165b1240ee31">
<img width="383" alt="blob-issue" src="https://github.com/microsoft/AzureStorageExplorer/assets/101690959/6e169648-4c5e-45f9-834b-e4d9696f3c11">
2. I have deployed containers in AKS, we saved storage account connection strings in key vault and whitelisted AKS ip address in storage account but still getting Auth issue.
3. Same steps are working for other environments.

**Comment by craxal** [comment]
@ASOS-NikhilGunda It's not entirely clear how you are attempting to connect to your storage account via Storage Explorer. Can you provide more details? Specifically, can you provide more detailed steps between 1 and 2 in the repro steps you already provided?

**Comment by ASOS-NikhilGunda** [comment]
Please close this ticket as I'm having IPAuthorization issue for storage account, not in storage explorer.
