### ISSUE TITLE
Fail to open Storage Explorer by taskbar shortcut if its previous version has been pinned to taskbar

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7045]
**Storage Explorer Version**: 1.30.1
**Build Number**: 20230707.14
**Branch**: hotfix/1.30.1
**Platform/OS**: Windows 10/Windows 11
**Architecture**: x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Install Storage Explorer 1.29.2 -> Pin it to the Taskbar.
2. Install 64 bit Storage Explorer 1.30.1.
3. After installing 64 bit 1.30.1 -> Pin it to the Taskbar -> Close Storage Explorer.
4. Open Storage Explorer by clicking Taskbar shortcut.
5. Check whether succeeds to open Storage Explorer.

## Expected Experience ##
Succeed to open Storage Explorer.

## Actual Experience ##
Fail to open Storage Explorer.

![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/0fc1c693-379e-4a0b-8d5d-aafaf1ce3321)

**Comment by MRayermannMSFT** [comment]
We have removed the code that forcefully has the uninstaller remove the taskbar icon. If Windows chooses to do it, and then gets confused, then that is a Windows bug.
