### ISSUE TITLE
Unable to use Storage Explorer on laptop

### ISSUE THREAD

**Issue by sarorausa** [microsoft/AzureStorageExplorer#7048]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

latest

### Regression From

first time download

### Architecture

x64

### Platform

Windows

### Bug Description

I get the following message when I click on any resource in the explorer to get details on the resource:

Unable to retrieve child resources

ProducerError:{
  "name": "FetchError",
  "message": "request to https://axwaysftp.file.core.windows.net/?comp=list failed, reason: self signed certificate in certificate chain",
  "stack": "FetchError: request to https://axwaysftp.file.core.windows.net/?comp=list failed, reason: self signed certificate in certificate chain\n    at ClientRequest.<anonymous> (C:\\Users\\T4263SA\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\file-extension\\dist\\src\\index.js:2:154871)\n    at ClientRequest.emit (node:events:513:28)\n    at TLSSocket.socketErrorListener (node:_http_client:502:9)\n    at TLSSocket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
  "type": "system",
  "errno": "SELF_SIGNED_CERT_IN_CHAIN",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}

### Steps to Reproduce

1.Launch storage explorer
2.Launch Blob store

### Actual Experience

I get the following message when I click on any resource in the explorer to get details on the resource:

Unable to retrieve child resources

ProducerError:{
  "name": "FetchError",
  "message": "request to https://axwaysftp.file.core.windows.net/?comp=list failed, reason: self signed certificate in certificate chain",
  "stack": "FetchError: request to https://axwaysftp.file.core.windows.net/?comp=list failed, reason: self signed certificate in certificate chain\n    at ClientRequest.<anonymous> (C:\\Users\\T4263SA\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\file-extension\\dist\\src\\index.js:2:154871)\n    at ClientRequest.emit (node:events:513:28)\n    at TLSSocket.socketErrorListener (node:_http_client:502:9)\n    at TLSSocket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
  "type": "system",
  "errno": "SELF_SIGNED_CERT_IN_CHAIN",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}

### Expected Experience

I was supposed to see what data the blob container has

### Additional Context

I need to startusing Storage explorer

**Comment by jinglouMSFT** [comment]
Have you tried to diagnose the issue following the steps in the Storage Explorer Troubleshooting Guide?  https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/storage-explorer-troubleshooting?tabs=Windows#ssl-certificate-issues

**Comment by craxal** [comment]
Are you using a proxy? You may find that changing your Proxy Configuration setting to "Use system proxy" will also help:

<img width="475" alt="image" src="https://github.com/microsoft/AzureStorageExplorer/assets/3473026/f6697dc8-4c8a-49d7-92a3-f444ba165bb5">

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue we recommend opening an Azure support ticket. Alternatively you can open a new issue here. This issue will no longer be monitored.
