### ISSUE TITLE
Azure Storage Explorer failed to connect to Microsoft Fabric Lakehouse

### ISSUE THREAD

**Issue by pranotiDE** [microsoft/AzureStorageExplorer#7049]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.30.0

### Architecture

x64

### Storage Explorer Build Number

20230609.2

### Platform

Windows

### OS Version

Windows 10 pro

### Bug Description

[AzureStorageExplorerAttemptToConnectToMicrosoftFabricLakehouse.txt](https://github.com/microsoft/AzureStorageExplorer/files/12010993/AzureStorageExplorerAttemptToConnectToMicrosoftFabricLakehouse.txt)

I have followed.instructions : https://learn.microsoft.com/en-us/fabric/onelake/onelake-azure-storage-explorer

url used to connect to gen2 storage: 
 https://onelake.blob.fabric.microsoft.com/fabricspace/firstLakehouse.Lakehouse/

![AzureStorageExplorerConnectingToFabricLakehouseError](https://github.com/microsoft/AzureStorageExplorer/assets/26461164/f0b70588-20c8-4e6b-b5f7-b037ed769791)

### Steps to Reproduce

1. Get Latest version of Azure Storage Explorer
2. Follow instructions as per https://learn.microsoft.com/en-us/fabric/onelake/onelake-azure-storage-explorer
3. Try to open the storage or try to see properties
4. Error shown, 

### Actual Experience

![AzureStorageExplorerConnectingToFabricLakehouseError](https://github.com/microsoft/AzureStorageExplorer/assets/26461164/e62b023b-121a-44c4-bda0-b99baeb6ffde)
Above attachment is showing error message

[AzureStorageExplorerAttemptToConnectToMicrosoftFabricLakehouse.txt](https://github.com/microsoft/AzureStorageExplorer/files/12011079/AzureStorageExplorerAttemptToConnectToMicrosoftFabricLakehouse.txt)
Above attachment is long json which is stored in Error Detailed message, when tried to see properties for this storage connection.

### Expected Experience

Storage explorer should be able to show Tables and Files that are on Microsoft Fabric workspace lakehouse.

**Comment by MRayermannMSFT** [comment]
@proanotiDe for now, can you please reach out to support for this issue? Information on how to get support for Microsoft Fabric can be found here: https://learn.microsoft.com/en-us/power-bi/support/service-support-options#get-started-with-support
