### ISSUE TITLE
Open from VS Code fails.

### ISSUE THREAD

**Issue by spboyer** [microsoft/AzureStorageExplorer#705]
Version: 1.4.2

Platform: macOS
Architecture: x64
Build Number: 20180917.1
Commit: f66de7ea
Support Id: d02ab9b4-e6df-b370-42ae-f793c85261ca

Right click from vscode Storage Explorer to "Open in Storage Explorer"

<img width="421" alt="screen shot 2018-09-26 at 10 36 54 pm" src="https://user-images.githubusercontent.com/7681382/46120251-dd072900-c1dc-11e8-86b0-0dbdfb9b79aa.png">

**Comment by radmint** [comment]
Related to this issue that I commented on a couple of days ago https://github.com/Microsoft/AzureStorageExplorer/issues/689

**Comment by MRayermannMSFT** [comment]
Closing as duplicate #689
