### ISSUE TITLE
No natural sorting for name column

### ISSUE THREAD

**Issue by Roterfux** [microsoft/AzureStorageExplorer#7050]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.30.0

### Architecture

x64

### Storage Explorer Build Number

20230609.2

### Platform

All

### Bug Description

![grafik](https://github.com/microsoft/AzureStorageExplorer/assets/6770980/2349b3b2-907c-41f5-88e1-16b555e386aa)
Sorting is not natural, which can lead to issues in finding e.g. the latest version (see screenshot)

### Steps to Reproduce

Launch Storage Explorer
Navigate to a blob download directory
check the names, sorted

### Actual Experience

Can lead to issues in finding e.g. the latest version

### Expected Experience

Natural sorting as e.g. in a file explorer

**Comment by craxal** [comment]
@Roterfux By "natural", assume you mean numeric parts of a name are treated as numbers when sorting? I notice Finder on macOS also sorts using numeric semantics for appropriate values, so I think this is something we can look into more.

**Comment by Roterfux** [comment]
I had to google it, since I was so sure how such a sorting is called.
But thanks for considering it @craxal

**Comment by MRayermannMSFT** [comment]
Let's see if we can do this in 1.32.
 - Thoroughly investigate in what ways Windows and macOS support natural sorting. Do they have a way to turn it off? Does it apply to folders and files?
 - If implementing, try to use existing npm library to implement the sort.

**Comment by Roterfux** [comment]
Is there a planned release (RC) window?

**Comment by richardMSFT** [comment]
1.33.0 is scheduled to release sometime late this month if all goes to plan :)

**Comment by Roterfux** [comment]
Sounds good :)
