### ISSUE TITLE
Storage Explorer crashes after loading ~80,000 during global sort in Linux

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#7057]
The machine used for testing has
- Ubuntu 18.04
- 7.5 GiB memory
- 2.4 GHz x 4 CPU
- 512 GB SSD

**Comment by MRayermannMSFT** [comment]
Double check with Jason on how much memory his test VM had. On my Windows machine with 32GB RAM, I have been able to get to 300k entities with ~4GB of RAM used by the explorer.

**Comment by craxal** [comment]
While it's possible this is due to the sheer amount of data we're trying to load into memory, it's also possible a small cleanup bug is contributing. It looks like the code isn't correctly unregistering reflow event listeners (mistakenly trying to unregister from the "focus" event).

**Comment by MRayermannMSFT** [comment]
Going to close this for now and wait for user feedback. We've seen various limits on "max items to load" depending on machine spec and the size of each item being loaded.
