### ISSUE TITLE
Update the log message from 'Transfer from...' to 'Transferred from...' after uploading blobs successfully 

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#706]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture**: ia32/x64
**Build Number**: 20180927.3
**Commit**: 42803a93
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Navigate to 'Experimental' menu -> Check 'Use AzCopy for Improved Blob Upload and Download'.
2. Open one blob container then upload a file to it.
3. Check the log message after the activity succeeds.

#### Expected Experience: ####
Show **'Transferred** from ...' in Activities.

#### Actual Experience: ####
Show **'Transfer** from ...' in Activities.
![transfer](https://user-images.githubusercontent.com/34729022/46133599-6b58ca80-c230-11e8-890f-bf9a68671943.png)

**Comment by MRayermannMSFT** [comment]
Fixed in 20180927.14. All log messages now start with "Transfer" as a noun.
