### ISSUE TITLE
There is an error info bar when executing actions in the original blob container if there is an Azure AD attached blob container without rbac roles

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7063]
**Storage Explorer Version:** 1.30.1
**Build Number:** 20230712.2
**Branch:** hotfix/1.30.1
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4.1 (Apple M1 Pro)
**Architecture:** x64/arm64
**How Found:** Ad-hoc testing
**Regression From:** Previous release (1.29.2)

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create a blob container (Don't assign rbac roles to it).
3. Azure AD attach the blob container -> There is an error info.
4. Switch to the original blob container -> Upload a blob.
5. Check whether succeeds to upload the blob and there is no error info.

## Expected Experience ##
Succeed to upload the blob and there is no error info.

## Actual Experience ##
Succeed to upload the blob, but there is an error info.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/a7ea7374-6b76-4e19-9693-bf6d73bb9448)

**Comment by JasonYeMSFT** [comment]
@v-kellyluo When you are available, can we have a call to go through what is wrong with the behavior?

**Comment by v-kellyluo** [comment]
Verified this issue on the build hotfix/1.30.1-20230713.8. Fixed. 
There is no error info if the only active explorer is the one that has full permissions, so we are going to close it.
