### ISSUE TITLE
Unable to open the Storage Explorer on destop

### ISSUE THREAD

**Issue by SaravanaKnauf** [microsoft/AzureStorageExplorer#7065]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.25.1

### Architecture

i86

### Platform

All

### OS Version

Windows 11

### Bug Description

Hi Team,
I get the below error while opening the Storage explore on my laptop.

Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://azweurtestcomexstorage01.blob.core.windows.net/?comp=list&include=metadata failed, reason: unable to get local issuer certificate",
  "stack": "FetchError: request to https://azweurtestcomexstorage01.blob.core.windows.net/?comp=list&include=metadata failed, reason: unable to get local issuer certificate\n    at ClientRequest.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1491:11)\n    at ClientRequest.emit (node:events:526:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:526:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "type": "system",
  "errno": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY",
  "code": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"
}

### Steps to Reproduce

1.started the application.
2. added the account details.
3. Opened the storage and clicked on containers. 

### Actual Experience

I am not sure whats the issue

**Comment by craxal** [comment]
@SaravanaKnauf Have you been able to sign in or connect to resources previously? Are you trying you attempting to connect through a proxy server?

Two things you can try:
1. Set the Proxy Configuration setting to "Use system proxy".
2. Follow the [troubleshooting guide](https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/storage-explorer-troubleshooting?tabs=Windows#ssl-certificate-issues) for importing SSL certificates.

**Comment by SaravanaKnauf** [comment]
Thanks Using System proxy worked.
