### ISSUE TITLE
Nothing happens after uploading/downloading blobs for attached blob containers

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#707]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture**: ia32/x64
**Build Number**: 20180927.3
**Commit**: 42803a93
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Navigate to 'Experimental' menu -> Check 'Use AzCopy for Improved Blob Upload and Download'.
2. Attach one blob container with SAS URI:
**Display name**: blobtest
**SAS URI:** https://e6pbf6rpi2zlw100.blob.core.windows.net/blobtest?st=2018-09-27T07%3A26%3A15Z&se=2018-10-30T07%3A26%3A00Z&sp=rwdl&sv=2018-03-28&sr=c&sig=dv%2FobS1ugPUiLzwNOcEkhUg41LU5TgVVNi0PC0riNpI%3D
3. Open the attached blob container -> Try to upload a blob to it.
4. Check whether the blob is uploaded successfully or not.

#### Expected Experience: ####
The blob can be uploaded successfully with log message 'Transferred from ...' in Activities.

#### Actual Experience: ####
Nothing happens.

**Comment by MRayermannMSFT** [comment]
Fixed in 20180927.14
