### ISSUE TITLE
1.30.0 deletes wrong table row on occasion.  

### ISSUE THREAD

**Issue by joepperkins** [microsoft/AzureStorageExplorer#7071]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.30.0

### Regression From

1.2x

### Architecture

x64

### Storage Explorer Build Number

0

### Platform

All

### OS Version

Window 11

### Bug Description

From Table view unfiltered delete row deletes wrong row on occasion.

### Steps to Reproduce

Open Table, right click any cell and select delete, deletes wrong row.

### Actual Experience

deletes wrong row.

### Expected Experience

deletes selected row.

**Comment by MRayermannMSFT** [comment]
@joepperkins 

1. Are you able to capture this behavior with screen recording?
2. Are you able to do a Teams call with us to show the behavior?

**Comment by MRayermannMSFT** [comment]
> If the cell selection returns and not the entire row I will re-test.

Please do. We will also do some testing today based on the initial steps you have provided.

**Comment by JasonYeMSFT** [comment]
I cannot reproduce the issue. One thing I would like point out is that right click on an unselected row will result in the row being selected. If you want to select some rows and delete them, you will need to right click on one of the selected rows.

Implementation wise, the onClick handler for the cell, which highlights the cell, is within the row element whose onClick handler alters the selection. I cannot see how the cell is highlighted without causing the row to be selected.

**Comment by MRayermannMSFT** [comment]
@joepperkins thanks again for the issue report. We continued looking for ways for this bug to happen and we believe we found a scenario that reproduces the behavior you described. We will be shipping a hotfix. Thank you again.

**Comment by v-kellyluo** [comment]
Verified this issue on the build hotfix-1.30.2/20230721.3, it doesn't reproduce if sort by one column then right click one entity. But it still reproduces in the following scenarios:

_Scenario1:_ The context menu action is applied to incorrect items if sort by one column then select more than one item.

**Repro step:**
1. Open one table which contains several entities -> Sort by one column.
2. Select and right click two entities -> Click 'Delete'.
3. The incorrect entities are deleted.

![two](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/81ecc711-b427-4399-b371-03c00c32a103)

_Scenario2: The context menu action is applied to incorrect item when right clicking one entity if execute context action for it and click another entity previously._

**Repro step:**

1. Open one table which contains several entities -> Sort by one column.
2. Select and right click one entity -> Click 'Copy Rows'.
3. Click another entity.
4. Select and right click the entity in Step2 -> Click 'Delete'.
5. The incorrect entity is deleted.

![delete](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/33849997-c779-4255-a5a9-eb188c8611e1)

**Comment by JasonYeMSFT** [comment]
I made a fix to the bug and we published a 1.30.2 for the fix. Please upgrade to 1.30.2. Thanks!
