### ISSUE TITLE
The 'Cancel' action next to the message 'Loading all items for global sort' doesn't take effect

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7072]
**Storage Explorer Version**: 1.31.0-dev
**Build Number**: 20230717.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4.1 (Apple M1 Pro)
**Architecture**: x64/arm64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Open Settings -> Data Explorers-> Enable the setting 'Global Sort'.
2. Create a new table -> Add two entities.
3. Sort the entities by one column.
4. There is a notification message 'Loading all items for global sort (x items found)'.
5. Click 'Cancel' next to the message.
6. Check whether the 'Cancel' action takes effect.

## Expected Experience ##
The 'Cancel' action takes effect.

## Actual Experience ##
The 'Cancel' action does not take effect.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/9d9bc04e-b7a7-4277-b9ba-194e7241471a)

**Comment by craxal** [comment]
@v-xianya It sounds like the reason the Cancel action doesn't work is because all the items are already loaded, so there's nothing to cancel. I think the _real_ bug here is the message doesn't disappear after loading completes.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230724.1. Fixed.
1. The message will auto disappear if all items are loaded.
2. The loading message disappears after clicking 'Cancel'.
