### ISSUE TITLE
There is no icon for the action 'Open' against one app configuration

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7074]
**Storage Explorer Version:** 1.31.0-dev
**Build Number:** 20230717.15
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4.1 (Apple M1 Pro)
**Architecture:** x64
**How Found:** From running test cases
**Regression From:** Previous release (1.30.1)

## Steps to Reproduce ##

1. Expand 'App Configurations' node -> Select one app configuration.
2. Observe its 'Actions' panel.
3. Check whether there is an icon for the action 'Open'.

## Expected Experience ##
There is an icon for the action 'Open'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/bfc3447c-507a-44e8-80d5-9b2448967046)

## Actual Experience ##
There is no icon for the action 'Open'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/f3207481-0677-4d22-affc-d1b10eb0f286)

**Comment by JasonYeMSFT** [comment]
Icon migration is done. I need to test the changes.

**Comment by JasonYeMSFT** [comment]
Moving to 1.33.0 so if we ship a new version of app config extension in 1.33.0, we can include this from there.

**Comment by v-kellyluo** [comment]
Verified this issue after installing app configuration extension 0.2.1, Fixed. So, we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/5619eb4b-aaed-4b8c-82aa-9e89f91ba2c5)
