### ISSUE TITLE
I can't delete a file if it ends with a trailing forward slash

### ISSUE THREAD

**Issue by bkleinman7** [microsoft/AzureStorageExplorer#7075]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.30.0

### Architecture

x64

### Storage Explorer Build Number

20230609.2

### Platform

All

### OS Version

macOS Ventura 13.4.1

### Bug Description

If I try to delete a file with a trailing forward slash, the file is not deleted. 

### Steps to Reproduce

1. Use API to create a file in azure blob storage with a "/" appended to the end of the filename
2. Go to file and try to delete it using the X Delete button in Azure Storage Explorer. 
3. File will not be deleted

### Actual Experience

1. Note if you upload a file using microsoft azure storage explorer with a trailing forward slash, the file is created with a colon ":" appended to the file name. 
2. The signed version I used to upload the file was 2018-03-28

**Comment by JasonYeMSFT** [comment]
@bkleinman7 Creating blobs whose name ends with forward slash is not recommended. We've found issues with our underlying library/executable which would treat the blob as directory and accidentally delete user data. As a result, we banned such risky operations entirely and always attempt to don't let people create such kind of blobs within Storage Explorer.  For now you can try deleting it in Azure Portal or write a script using the API to delete those blobs.

**Comment by bkleinman7** [comment]
> @bkleinman7 Creating blobs whose name ends with forward slash is not recommended. We've found issues with our underlying library/executable which would treat the blob as directory and accidentally delete user data. As a result, we banned such risky operations entirely and always attempt to don't let people create such kind of blobs within Storage Explorer. For now you can try deleting it in Azure Portal or write a script using the API to delete those blobs.

Thanks, I will just delete them via the API.
