### ISSUE TITLE
Fail to upload/clone/paste blobs with option 'Optimize block size (requires write permission)' unchecked in one attached blob container whose SAS URL is created by an access policy

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7077]
**Storage Explorer Version**: 1.31.0-dev
**Build Number**: 20230719.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4.1 (Apple M1 Pro)
**Architecture**: x64
**How Found**: Ad-hoc testing
**Regression From**: Previous release (1.29.2)

## Steps to Reproduce ##
1. Open Settings -> Transfers -> Set 'Buffer Size' to 4.
2. Expand one storage account -> Blob Containers.
3. Create a blob container -> Right click the blob container -> Click 'Manage Stored Access Policies...'.
4. Add one access policy with full permissions.
5. Attach the blob container via a SAS URL which is created by the access policy.
6. Go to the attached blob container -> Upload one blob.
7. There is a dialog -> Uncheck the option 'Optimize block size (requires write permission)' -> Click 'OK'.
8. Check whether succeeds to upload the blob.

## Expected Experience ##
Succeed to upload the blob.

## Actual Experience ##
Fail to upload the blob.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/0386107a-d85d-4b27-be83-07cd4abf9495)

Here is the AzCopy Log:
[f693b399-53d6-ed44-40ff-bb5a1aa53e51.log](https://github.com/microsoft/AzureStorageExplorer/files/12092328/f693b399-53d6-ed44-40ff-bb5a1aa53e51.log)

**Comment by MRayermannMSFT** [comment]
Related to this: https://github.com/Azure/azure-storage-azcopy/pull/2228

Will talk with Jason offline.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20231121.2. Fixed for upload.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20231121.9. Fixed.
