### ISSUE TITLE
The items under one folder show normal if type '/folder name/' on the address bar then press 'Enter' for one ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7079]
**Storage Explorer Version**: 1.31.0-dev
**Build Number**: 20230720.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4.1 (Apple M1 Pro)
**Architecture**: x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container named 'bc01' -> Create a folder named 'f1' -> Upload one blob to the folder.
3. Back to the root -> Put the cursor on the address bar.
4. Type '/f1/' -> Press 'Enter' -> Show strings on the address bar ![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/aa6dd626-4e12-47fb-ad8b-b0f7e1fc219c) .
5. Check whether the current behavior makes sense.

## Expected Experience ##
The current behavior makes sense.

Like:
1. For one regular blob container, no items show under the new path.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/668770b5-c329-48ac-8fe6-c1e8ae76e8fd)
2. For one file share, prompt an error information.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/3d86e9d3-249c-4b4e-af3c-217aa8926b46)

## Actual Experience ##
1. The current behavior does not make sense.
2. The blob under 'f1' folder shows.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/fb50f216-842d-4d91-b546-a5ac1790e715)

**Comment by MRayermannMSFT** [comment]
Interesting issue. We have known for a while that no-name folders are not supported for gen2. However, it seems that if you do try to include one in the prefix while listing, the server will collapse them/remove duplicate slashes, thus you get a result like seen in the bug. Since the service is doing this behavior we are going to won't fix.
