### ISSUE TITLE
Fail to complete the activity of uploading a VHD file with 0B size

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#708]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture**: ia32/x64
**Build Number**: 20180927.3
**Commit**: 42803a93
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Navigate to 'Experimental' menu -> Check 'Use AzCopy for Improved Blob Upload and Download'.
2. Open one blob container and try to upload a vhd file with 0B.
3. Check the result.

#### Expected Experience: ####
Succeed to complete the uploading activity at a short time.

#### Actual Experience: ####
Fail to complete the uploading activity(More than 30 minutes).
![fail_to_complete](https://user-images.githubusercontent.com/34729022/46131557-7ceba380-c22b-11e8-89fb-566d994bafd3.png)

#### More Info: ####
1. The empty vhd file shows well after refreshing the editor. 
2. This issue doesn't reproduce when downloading the same vhd file.

**Comment by MRayermannMSFT** [comment]
It looks like this is only happens when AzCopy is asked to output JSON. I'll need to report this to the AzCopy team.

**Comment by MRayermannMSFT** [comment]
Opened a bug against AzCopy https://github.com/Azure/azure-storage-azcopy/issues/67

**Comment by v-xuanzh** [comment]
Hi @MRayermannMSFT ,This issue still reproduces in 20181025.6.

**Comment by MRayermannMSFT** [comment]
@v-xuanzh can you try repro'ing this again? Thanks!

**Comment by MRayermannMSFT** [comment]
Per CTI email from 3/27 this is fixed.
