### ISSUE TITLE
An .opus file will be previewed in Storage Explorer instead of being downloaded if double click it and set the setting 'Open Operation' to 'Preview'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7080]
**Storage Explorer Version**: 1.31.0-dev
**Build Number**: 20230720.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4.1 (Apple M1 Pro)
**Architecture**: x64
**How Found**: Ad-hoc testing
**Regression From**: Previous release (1.30.1)

## Steps to Reproduce ##
1. Go to 'Settings -> Data Explorers'.
2. Set the setting 'Open Operation' to 'Preview'.
3. Expand one storage account -> Blob Containers.
4. Create a blob container -> Upload one .opus file -> Double click the file.
5. Check whether Storage Explorer will download the file.

## Expected Experience ##
Storage Explorer will download the file.

## Actual Experience ##
Storage Explorer will try to preview the file.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/aa580c8a-d215-4af9-a744-eb8cb21c8fce)

## Additional Context ##
This issue doesn't reproduce for files under file shares.

**Comment by MRayermannMSFT** [comment]
Hi @v-xianya , Richard went on vacation shortly after merging his feature. I assume he'll email y'all with more details once he's back. He has been working on audio preview: https://github.com/microsoft/AzureStorageExplorer/issues/6642

I believe it should be expected that this file type can now be previewed. It is an audio file yes?

**Comment by v-kellyluo** [comment]
@MRayermannMSFT , yes, it is an audio file.

**Comment by richardMSFT** [comment]
Hi @v-xianya, I am unable to reproduce this issue with the .opus file that I have. Can you share the file that is causing this on your end? Can you also tell me what you see under "Content Type" for the file? 

The reason for this is because from the screenshot attached above, the toolbar has the "Play in Browser" action which should only appear for video files. It's interesting that audio preview is triggering when the file is recognized as a video by Storage Explorer.

**Comment by v-xianya** [comment]
Hi @richardMSFT I sent the .opus file to you on teams.
The content type of the file is 'audio/ogg'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/3d151990-251e-4a77-b333-8728bbcfcf0a)

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230731.1. Fixed. So, we are going to close it.

Set the setting 'Open Operation' to 'Preview'.
For one .opus file with content type 'audio/ogg', double click it, storage explorer will try to download then open the file.

**Comment by v-xianya** [comment]
Verified this issue on the build 20230801.4. 
Reproduce for regular blobs. So, we are going to re-open it.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230803.5. Fixed.
