### ISSUE TITLE
Error previewing parquet on mac

### ISSUE THREAD

**Issue by PorterJosh** [microsoft/AzureStorageExplorer#7081]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.30.0

### Architecture

arm64

### Storage Explorer Build Number

20230609.2

### Platform

macOS

### Bug Description

Cannot view parquet file. 

Error Details
If you cannot resolve this issue on your own, you may open an issue on the Storage Explorer GitHub site. Please include the details below to help us diagnose your issue. Make sure to redact any personal information you do not wish to make public before posting.
{
  "name": "TypeError",
  "message": "o.buffer.readUInt32LE is not a function",
  "stack": "TypeError: o.buffer.readUInt32LE is not a function\n    at ZR (file:///Applications/Microsoft%20Azure%20Storage%20Explorer.app/Contents/Resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:736826)\n    at Object.QR (file:///Applications/Microsoft%20Azure%20Storage%20Explorer.app/Contents/Resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:736928)\n    at Tn (file:///Applications/Microsoft%20Azure%20Storage%20Explorer.app/Contents/Resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:764741)\n    at rD (file:///Applications/Microsoft%20Azure%20Storage%20Explorer.app/Contents/Resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:766114)\n    at async sb (file:///Applications/Microsoft%20Azure%20Storage%20Explorer.app/Contents/Resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:765449)\n    at async fb (file:///Applications/Microsoft%20Azure%20Storage%20Explorer.app/Contents/Resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:767625)\n    at async Mu.readRowGroup (file:///Applications/Microsoft%20Azure%20Storage%20Explorer.app/Contents/Resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:763489)\n    at async Object.next (file:///Applications/Microsoft%20Azure%20Storage%20Explorer.app/Contents/Resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:756357)\n    at async ParquetParser.getRecords (file:///Applications/Microsoft%20Azure%20Storage%20Explorer.app/Contents/Resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:5046)\n    at async getParquetData (file:///Applications/Microsoft%20Azure%20Storage%20Explorer.app/Contents/Resources/app/node_modules/@storage-explorer/file-preview/dist/src/Panels/ParquetPreviewPanel/index.js:2:6298)"
}

### Steps to Reproduce

1. Right click on a parquet and select preview

### Actual Experience

File does not open.  It does open in other parquet viewers.

### Expected Experience

Software works.

**Comment by JasonYeMSFT** [comment]
This is likely an issue we have already fixed. If you upgrade to our latest version, you might be able to preview your parquet file.

**Comment by JasonYeMSFT** [comment]
Closing since this is very likely a duplicated issue. If you still have this issue after upgrading to 1.30.2, please reopen it and ideally share a sample file with us.

**Comment by PorterJosh** [comment]
I subscribed to the insider builds and got the new version.  Can confirm this is fixed.
