### ISSUE TITLE
Managing storage accounts is a very clunky experience, especially with a large tenant

### ISSUE THREAD

**Issue by theficus** [microsoft/AzureStorageExplorer#7082]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I have hundreds of Azure subscriptions for my tenant, and it's a very clunky experience managing them.

### Desired Solution

Under the Account Management view, there is no search functionality which makes it very difficult to find the subscriptions I want without lots and lots of scrolling. Furthermore, if a subscription ends up in the "Explorer" view there is no ability to remove a subscription from there (for instance right click, remove). I have to go back to the Account Management view, scroll through hundreds of subscriptions, and find the one I want to uncheck. This is especially frustrating because subscriptions seem to sometimes get checked that I didn't specifically add so I have to go hunting through the list to find and remove them.

**Comment by MRayermannMSFT** [comment]
> I have to go back to the Account Management view, scroll through hundreds of subscriptions, and find the one I want to uncheck.

Hi @theficus , how many subscriptions do you find yourself frequently switching between, vs how many do you have access to? If there is a big disparity in that number, then I highly recommend you take advantage of hiding subscriptions. For example, I have access to ~100 subscriptions, but only ever work with 3. The rest are garbage to me. Therefore, I have hidden those subscriptions. To hide a subscription you can hover your mouse near/over it, look for the eye icon to pop up, and then click that. See this gif for an example of what I mean:

![image](https://github.com/microsoft/AzureStorageExplorer/assets/21112697/fbdd83ff-7bad-4c2f-990d-ddc3943676eb)

> Under the Account Management view, there is no search functionality which makes it very difficult to find the subscriptions I want without lots and lots of scrolling.

Our hope is that with subscription hiding, the average user should be able to get your list of subscriptions down to an amount that does not require searching. However, if we get feedback that subscription hiding is not enough, this is definitely an improvement we'd be open to exploring.

> Furthermore, if a subscription ends up in the "Explorer" view there is no ability to remove a subscription from there

Yes. This is annoying. I will open a specific item for this.

> subscriptions seem to sometimes get checked that I didn't specifically add

Yes. If you get access to a new subscription, it will automatically be not-hidden, checked, and show up in the tree view on startup. The thinking behind this was to make it very quick to get access to resources in a subscription you were just added to. We've heard from users both for and against this behavior. I'm not sure that we're ready to commit to changing it or adding a setting for it though.


Please feel free to continue the discussion of all of your raised concerns/points. We're more than happy to talk things through. :)

**Comment by theficus** [comment]
My tenant like yours, is microsoft.onmicrosoft.com so there's hundreds if not thousands of subscriptions visible in the Account Management view. The problem isn't the checking/unchecking which I have to do to have a manageable list, it's that there's no search functionality so finding what I want involves lots and lots of scrolling through hundreds of items -- many of which have very similar names -- to find the one thing I'm looking for so I can check/uncheck it.

Given the amount of subscriptions available in my case, and the pain in managing them, having "new things checked by default" is definitely not an ideal experience. Why not have a setting to configure this behavior?

**Comment by MRayermannMSFT** [comment]
> The problem isn't the checking/unchecking which I have to do to have a manageable list, it's that there's no search functionality so finding what I want involves lots and lots of scrolling through hundreds of items -- many of which have very similar names -- to find the one thing I'm looking for so I can check/uncheck it.

I understand what you're saying here. Can you let me know how the subscription hiding doesn't help?

> Why not have a setting to configure this behavior?

Given the feedback we've had on the behavior so far, it hasn't been a priority compared to other work.

**Comment by theficus** [comment]
The problem is that when you're in the "Account Management" view, there can be a massive amount of things there. There's no search functionality that would let you filter the list of names or subscription IDs, and many subscriptions are not named in such a way that makes it easy to skim for them by name so just finding the subscription I want requires a whole bunch of scrolling and scanning. I admit this is probably a Microsoft-centric problem since I would assume most tenants don't have the sheer count of subscriptions microsoft.onmicrosoft.com has but it's a daily frustration for me none the less. (Especially so with the decision to automatically add new subscriptions since I don't want those cluttering up my Explorer view so I have to go back into the Account Management view and scroll through hundreds of things to find those one or two new things that were added and make them go away.)

I hope this clarifies things!

**Comment by MRayermannMSFT** [comment]
> I hope this clarifies things!

Unfortunately, it doesn't. I've reached out a few times over Teams to see if we could do a screenshare so we can show it each other what we're talking about, but for some reason it seems like perhaps my messages aren't reaching you. Feel free to reach out at your convenience.

**Comment by MRayermannMSFT** [comment]
@theficus closing issue due to lack of response. I'm still interested in connecting with you over Teams though. Feel free to reach back out whenever.
