### ISSUE TITLE
Add glTF files preview

### ISSUE THREAD

**Issue by ibober** [microsoft/AzureStorageExplorer#7084]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I can't see .gltf and .glb files preview.

### Desired Solution

I'd like to see .gltf and .glb files preview.

### Alternatives and Workarounds

Right now I have to download each file and open on my PC.

### Additional Context

There is plenty of libraries to open and display glTF files, I think it worth adding BabylonJS or some other 3D view.

**Comment by MRayermannMSFT** [comment]
@ibober thanks for the feature request. This is a very interesting request. We're going to put this in our Near Future milestone for now, and wait and see what other 3D model file types other folks are interested in being able to preview. Once we have more of that information we can start looking at the best path forward.

**Comment by MRayermannMSFT** [comment]
@richardmsft for 1.34.0 please:

- Identify popular file types for 3D models
- Identify libraries that could allow us to preview such file types in storage explorer

And then once done, come back to the team and we can figure out if adding the preview fits better in 1.34 or 1.35.

**Comment by richardMSFT** [comment]
3D model previewing that supports .gltf >= 2.0, .glb, .stl, and .obj files has been included with the 1.34.0 release.
