### ISSUE TITLE
The 'Copy Rows' action is applied to an incorrect item if sort by one column in tabular preview panel

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7085]
**Storage Explorer Version:** 1.30.2
**Build Number:** 20230721.7
**Branch:** From github release page
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture:** x64/arm64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Open one blob container -> Upload a csv blob. (Make sure its content type is text/csv)
3. Right click the blob -> Click 'Preview'.
4. The tabular preview tab opens -> Sort by one column.
5. Select and right click one item -> Click 'Copy Rows' -> Paste it to one text file.
6. Check whether the correct item is pasted.

## Expected Experience ##
The correct item is pasted.

## Actual Experience ##
The incorrect item is pasted.

## Additional Context ##
1. This issue doesn't reproduce for tables.
2. In 1.29.2, the 'Copy Rows' action has not been added.
3. This issue doesn't reproduce when selecting more than one item.
4. Here is the record:
![tabular](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/bcbbd4c0-c982-4df1-b27f-11db072cb151)

**Comment by JasonYeMSFT** [comment]
I haven't touched that since the operations are read only. Will make the same fix in 1.31.0.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230801.4. Fixed.
