### ISSUE TITLE
Storage Explorer download function does not detect all available folders

### ISSUE THREAD

**Issue by linsson** [microsoft/AzureStorageExplorer#7086]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.30.2

### Architecture

x64

### Storage Explorer Build Number

20230721.7

### Platform

Linux (snap)

### OS Version

Ubuntu 20.04

### Bug Description

When I try to download a large folder (~2TB), the "Select a folder for download" panel does not allow me to access partitions from other disks. I can't even see them. I am the owner of that partition.
Ex:
$ ls -l / | egrep data00
drwxr-xr-x  10 bill bill  4096 mag 25 09:20 data00

### Steps to Reproduce

1. Launch Storage Explorer
2. Connect to a blob container
3. select a folder
4. Press Download Button
5. Some destination (folders) are missing

### Actual Experience

When trind to download a file, some destination folders are missing.
![Screenshot_Storage_explorer](https://github.com/microsoft/AzureStorageExplorer/assets/6852536/2c6b231f-0f82-4bc3-8d98-07ba9db02649)

### Expected Experience

I expected to see all folders as possible destinations (at least those for which I have rw permissions)

$ ls -l / | sort -k 9,9
total 168
lrwxrwxrwx   1 root  root      7 mar 14 17:53 bin -> usr/bin
drwxr-xr-x   4 root  root   4096 lug  7 06:28 boot
drwxr-xr-x   2 root  root   4096 mar 14 17:55 cdrom
drwxr-xr-x  10 bill bill  4096 mag 25 09:20 data00
drwxr-xr-x   4 bill bill  4096 lug 19 09:49 data01
drwxr-xr-x  20 root  root   5060 lug 24 14:25 dev
drwxr-xr-x 142 root  root  12288 lug 21 06:32 etc

### Additional Context

I can see those missing directories when using the Upload button.
I already used
snap connect storage-explorer:removable-media :removable-media
Which likely solved the same or a silmilar issue for the /media folder but my problem with other mounted partitions is still there.

**Comment by MRayermannMSFT** [comment]
@linsson did you install via snap or the .tar.gz bundle?

**Comment by linsson** [comment]
Exactly! Sounds weird to me too!

![Screenshot_Storage_explorer_upload](https://github.com/microsoft/AzureStorageExplorer/assets/6852536/5792a3be-20db-48be-9618-17a37648399d)
![Screenshot_Storage_explorer_download](https://github.com/microsoft/AzureStorageExplorer/assets/6852536/9eb43ab3-d28d-4f63-ac48-8bbe8f472c2f)

Am I missing something?

**Comment by MRayermannMSFT** [comment]
@linsson one thing we are noticing in the screenshots is that the two file manager applications in each picture are very different. It looks like that they might even be totally different applications. Do you know why this might be?

**Comment by linsson** [comment]
> @linsson one thing we are noticing in the screenshots is that the two file manager applications in each picture are very different. It looks like that they might even be totally different applications. Do you know why this might be?

I also noticed that but I have no idea about it, unfortunately. Can I change something from some option panel?

**Comment by MRayermannMSFT** [comment]
> it uses something different that I can't recognize.

To me it looks like the default Ubuntu file explorer, Nautilus, but I'm not 100% sure.
- https://wiki.gnome.org/action/show/Apps/Files?action=show&redirect=Apps%2FNautilus
- https://manpages.ubuntu.com/manpages/xenial/en/man1/nautilus.1.html
- https://linuxhint.com/ubuntu_file_managers/

I think it could be good to try:
1. See if you can launch Nautilus on its own (e.g. not from Storage Explorer), and see if it has access to your mounted drives?
2. It it doesn't, can you find a way to give it access?
3. If it does, but you don't use it normally, try uninstalling it. Perhaps that will force Storage Explorer to use Dolphin during downloads.

**Comment by linsson** [comment]
Hi,

unfortunately the nautilus command seems to be unavailable and 

"apt list --installed | egrep -i nau"

returns nothing.

**Comment by MRayermannMSFT** [comment]
@linsson well, it must be some other file explorer then. I think the solution lies in finding out which one it is and then either removing it, or figuring out how to give it access to your mounted drives. Unfortunately this now getting out of our expertise area. We can leave this issue open while you investigate down that path. Let us know if you have any Storage Explorer centric questions while doing so.

**Comment by MRayermannMSFT** [comment]
One final alternative for you is to create a linked folder in a location that the other-file-explorer has access to, which resolves to a location on the mounted drive. Then you could do the download into that linked folder.

**Comment by linsson** [comment]
> @linsson well, it must be some other file explorer then. I think the solution lies in finding out which one it is and then either removing it, or figuring out how to give it access to your mounted drives. Unfortunately this now getting out of our expertise area. We can leave this issue open while you investigate down that path. Let us know if you have any Storage Explorer centric questions while doing so.

Is there any possibility to set app explorer from Storage Explorer settings?

**Comment by MRayermannMSFT** [comment]
> Is there any possibility to set app explorer from Storage Explorer settings?

No, not that I know of. Basically we call an Electron API, which calls a Chromium API, which calls API specific to your OS.
