### ISSUE TITLE
Cannot download some files

### ISSUE THREAD

**Issue by ffisc** [microsoft/AzureStorageExplorer#7087]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.30.2

### Architecture

arm64

### Storage Explorer Build Number

20230721.7

### Platform

macOS

### OS Version

macOS Ventura

### Bug Description

I can download files from blob container A, but not from blob container B.
Both are under the same storage account, and I can download from blob container B via Azure portal.
If I try generating a SAS for blob container B and running `azcopy cp` in the terminal, I get the same issue.

### Steps to Reproduce

Tricky to reproduce as it seems specific to a blob container.

### Actual Experience

I get an error as seen below. Despite the message, I'd be very surprised if the issue was related to formatting since it's automatically generated by Storage Explorer.

### Expected Experience

I'd expect to be able to download files just as I can for other blob containers.

### Additional Context

```
{
  "message": "\"failed to perform copy command due to error: cannot start job due to error: cannot list files due to reason -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /Users/azcopydev/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/zc_storage_error.go:42\\n===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====\\nDescription=403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature., Details: (none)\\n   HEAD https://foo.blob.core.windows.net/bar/baz/qux?se=2023-08-23t12%3A46%3A32z&sig=-REDACTED&timeout=901\\n   User-Agent: [Microsoft Azure Storage Explorer, 1.30.2, darwin, azcopy-node/3.0.0-rc.4 (darwin)  AzCopy/10.19.0-Preview Azure-Storage/0.15 (go1.19.6; darwin)]\\n   X-Ms-Client-Request-Id: [REDACTED]\\n   X-Ms-Version: [2020-10-02]\\n   --------------------------------------------------------------------------------\\n   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\\n   Date: [Mon, 24 Jul 2023 12:46:33 GMT]\\n   Server: [Microsoft-HTTPAPI/2.0]\\n   X-Ms-Error-Code: [AuthenticationFailed]\\n   X-Ms-Request-Id: [REDACTED]\\n\\n\\n.\\n\""
}
```

**Comment by MRayermannMSFT** [comment]
@ffisc would you be able to share the full log file with us?

**Comment by JasonYeMSFT** [comment]
The log indicates the signature doesn't match the blob you are trying to download. In the error message, it says the SAS is generated for this blob container "att-fraud" in storage account "benchmarks" (/blob/benchmarks/att-fraud). The blob you are trying to download is in container "bar" in storage account "foo".

**Comment by ffisc** [comment]
> The log indicates the signature doesn't match the blob you are trying to download. In the error message, it says the SAS is generated for this blob container "att-fraud" in storage account "benchmarks" (/blob/benchmarks/att-fraud). The blob you are trying to download is in container "bar" in storage account "foo".

Thank you. Somehow the issue seems to have solved itself.
