### ISSUE TITLE
Make sure commands putting things on clipboard are only using `\n`

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#7088]
When copying line separated urls/paths to clipboard, we use platform dependent new line delimiters. On windows it's `\r\n` and on other platforms it's just `\n`. We've been using `\n` for table copy rows and copy cells across all platforms. We should find out if these platform dependent new line delimiters.

**Comment by MRayermannMSFT** [comment]
Relevant anytime we take multiple lines and export to a file or move to a clipboard.

**Comment by MRayermannMSFT** [comment]
Criag investigated. We are safe to not make use of `\r` on windows.
