### ISSUE TITLE
An extra 'Open Folder' shows in Activities after cancelling the activity of uploading blobs

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#709]
Storage Explorer Version: 1.5.0
Platform/OS Version: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
Architecture: ia32/x64
Build Number: 20180927.3
Commit: 42803a93
Regression From: Not a regression

#### Steps to Reproduce: ####
1. Navigate to 'Experimental' menu -> Check 'Use AzCopy for Improved Blob Upload and Download'.
2. Open one blob container then upload a blob -> Click ‘Cancel’.
3. After cancelling complete then check the Activities panel.

#### Expected Experience: ####
There is no ‘Open Folder’ in Activities.

#### Actual Experience: ####
An extra 'Open Folder' shows in Activities.
![actual](https://user-images.githubusercontent.com/41351993/46133940-4022ab00-c231-11e8-9570-1db72006c255.PNG)

**Comment by MRayermannMSFT** [comment]
Fixed in 20180927.14
