### ISSUE TITLE
It is better to set the default tag key to 'TagKey1' instead of 'TagKey' in 'View Options' panel

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7092]
**Storage Explorer Version**: 1.31.0-dev
**Build Number**: 20230726.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4.1 (Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.30.2)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Right click one blob container -> Click 'Open in React'.
3. Open 'View Options' panel -> Select 'Tag Query'.
4. Observe the default tag key.

## Expected Experience ##
It would be better to show 'TagKey1' as the default tag key.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/38bd9a89-7db7-49b8-b520-5e32ca0022ec)

## Actual Experience ##
It shows 'TagKey' as the default tag key.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/1c36cc4d-9796-4d18-80ff-7ab2586e9bbe)

## Additional Context ##
For the next added clause, the tag key better to keep the same as the previous blob explorer.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/bf7420c5-5f1c-4102-8423-ddfeebd1bc84)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230727.4. Fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/e39321ff-d3ad-4f49-b06b-887ac59ebda5)
