### ISSUE TITLE
The blob editor is refreshed after clicking 'Reset' in view options panel even though no tag query is applied

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7093]
**Storage Explorer Version**: 1.31.0-dev
**Build Number**: 20230726.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4.1 (Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.30.2)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Right click one blob container -> Click 'Open in React'.
3. Open 'View Options' panel -> Select 'Tag Query' -> Click 'Reset'.
4. Check the blob editor is not refreshed.

## Expected Experience ##
The blob editor is not refreshed.

## Actual Experience ##
The blob editor is refreshed.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230727.4. Fixed.
