### ISSUE TITLE
The 'Edit Tags...' action is enabled for one emulator blob

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7094]
**Storage Explorer Version:** 1.31.0-dev
**Build Number:** 20230726.3
**Branch:** main
**Platform/OS:** Windows 10
**Emulator Version:** Azurite 3.24.0
**Architecture:** x64
**How Found:** From running test cases
**Regression From:** Previous release (1.30.2)

## Steps to Reproduce ##

1. Install and run Azurite 3.24.0 -> Launch Storage Explorer.
2. Expand 'Local & Attached -> Storage Accounts -> (Emulator - Default Ports) (Key)' -> Blob Containers.
3. Create a blob container -> Right click the blob container -> Click 'Open in React'.
4. Upload a blob -> Right click the blob.
5. Check whether the 'Edit Tags...' action is disabled.

## Expected Experience ##
The 'Edit Tags...' action is disabled.

## Actual Experience ##
The 'Edit Tags...' action is enabled.

## Additional Context ##
The 'Tag Query' option can be selected in the 'View Options' panel.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/bda4910c-1ab6-4e91-be3f-e30a7565b09b)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230727.4, the 'Edit Tags...' action is disabled for emulator blobs, but 'Tag Query' option can be selected in the 'View Options' panel.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/07ab6d52-670a-41f8-9a7b-4332a1ef7d6c)

**Comment by JasonYeMSFT** [comment]
I merged a change to disable the tags query option for Emulator explorers.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230728.3, 'Tag Query' is disabled for Emulator explorers, so we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/3fe85092-f927-487e-bf3d-eb16f16f3a1f)
