### ISSUE TITLE
'View Options' panel doesn't disappear after switching to 'Snapshots/Versions' view

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7097]
**Storage Explorer Version**: 1.31.0-dev
**Build Number**: 20230726.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4.1 (Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.30.2)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Right click the blob container -> Click 'Open in React'.
3. Upload a blob -> Open 'View Options' panel.
4. Right click the blob -> Click 'Manage History -> Manage Versions'.
5. Check whether 'View Options' panel disappears.

## Expected Experience ##
 'View Options' panel disappears.
## Actual Experience ##
'View Options' panel doesn't disappear.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/da6bac6f-18c8-4ab0-b706-750f4bf415a0)

**Comment by v-xianya** [comment]
Hi @JasonYeMSFT Is it possible to hide the view options panel under Snapshot/Version?

**Comment by JasonYeMSFT** [comment]
It is possible but there is no need to do that.
