### ISSUE TITLE
'Download All…' is enabled for one empty blob explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7099]
**Storage Explorer Version**: 1.31.0-dev
**Build Number**: 20230726.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4.1 (Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.30.2)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Right click the blob container -> Click 'Open in React'.
3. Observe the toolbar.
4. Check whether 'Download All...' action is disabled.

## Expected Experience ##
 'Download All...' action is disabled.
 
## Actual Experience ##
 'Download All...' action is enabled.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/aa31ab4a-8ed5-41be-a161-7f1dc18cb56e)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230727.4. Fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/6e062a41-128d-4bd1-82e1-51739cddbc28)
