### ISSUE TITLE
Multiple unexpected results occur when uploading/downloading large VHD files

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#710]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture**: ia32/x64
**Build Number**: 20180927.3
**Commit**: 4280a93
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Navigate to 'Experimental' menu -> Check 'Use AzCopy for Improved Blob Upload and Download'.
2. Open one premium blob container and try to upload a large vhd file (Like 30G) to it.
3. Check the result.

#### Expected Experience: ####
The large vhd file can be uploaded successfully.

#### Actual Experience: ####
There are three unexpected results for the uploading/downloading operation.
1. Fail to upload with the error 'AzCopy quit unexpectedly'.
![error](https://user-images.githubusercontent.com/34729022/46132943-eae59a00-c22e-11e8-9ce4-680a2af0719b.png)
2. The uploading activity is cancelled automatically.
3. The uploading activity can't be completed.

**Comment by v-xuanzh** [comment]
Hi @MRayermannMSFT ,We verified this issue on the build 20181022.4. The uploaded large VHD(127G) can be uploaded successfully, but the percentage number stayed at 12% for a long time. And continue to waiting about 2 hours until the the activity is complete.
![progress](https://user-images.githubusercontent.com/34729022/47287267-3f104e00-d624-11e8-91b3-a52f5c8cf5ac.png)

**Comment by MRayermannMSFT** [comment]
@v-xuanzh , should we close this issue?

**Comment by v-xuanzh** [comment]
Hi @MRayermannMSFT ,We verified this issue on the latest build, There is one result when uploading a large file to one premium blob container.

**Result Experience**:
The uploading status has always been 7% and it cannot be completed. And I'm not sure if it is a network issue. ☹

![image](https://user-images.githubusercontent.com/34729022/55052768-4beffe00-5017-11e9-821b-27d63e448575.png)

**Comment by v-xianya** [comment]
This issue doesn't reproduce on build 20191220.9. So we close it.
