### ISSUE TITLE
The action 'Edit Tags…' is enabled for one soft deleted blob in new blob explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7100]
**Storage Explorer Version**: 1.31.0-dev
**Build Number**: 20230726.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4.1 (Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.30.2)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Right click the blob container -> Click 'Open in React'.
3. Upload a blob -> Soft delete the blob.
4. Switch to context view 'Active and soft deleted blobs'.
5. Right click the soft deleted blob.
6. Check whether the action 'Edit Tags...' is disabled.

## Expected Experience ##
The action 'Edit Tags...' is disabled.
 
## Actual Experience ##
The action 'Edit Tags...' is enabled.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230727.4. Fixed.
