### ISSUE TITLE
There is no value for the column property 'Remaining Days' against one soft deleted blob

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7101]
**Storage Explorer Version**: 1.31.0-dev
**Build Number**: 20230726.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4.1 (Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.30.2)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Right click the blob container -> Click 'Open in React'.
3. Upload a blob -> Soft delete the blob.
4. Switch to context view 'Active and soft deleted blobs'.
5. Observe the column properties for the soft deleted blob.
6. Check there is a value for the column property 'Remaining Days'.

## Expected Experience ##
There is a value for the column property 'Remaining Days'.
 
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/1823220e-c809-468b-80d8-8c3bfcc4f8c9)

## Actual Experience ##
There is no value for the column property 'Remaining Days'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/f2dbce17-c397-4be2-8695-ef850e47ce4d)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230727.4. Fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/b873bd3e-4250-4d74-8b05-10c04279b00b)
