### ISSUE TITLE
The 'Filter by prefix' box is not reset after creating a new folder in new blob explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7104]
**Storage Explorer Version**: 1.31.0-dev
**Build Number**: 20230726.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4.1 (Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.30.2)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Right click the blob container -> Click 'Open in React'.
3. Open 'View Options' panel -> Type 'a' into the 'Filter by prefix' box.
4. Create a new folder.
5. Check whether the 'Filter by prefix' box is reset.

## Expected Experience ##
The 'Filter by prefix' box is reset.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/e456d61a-70e2-4645-8c65-eaddc7e3e896)

## Actual Experience ##
The 'Filter by prefix' box is not reset.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/61a80b91-90e7-4922-9b72-edf2cf12e29d)

## More Info ##
The string on the address bar is incorrect.

**Comment by v-xianya** [comment]
Hi @JasonYeMSFT Verified this issue on the main build 20230727.4.
1. The 'Filter by prefix' box is reset and the string on the address bar is correct.
2. No placeholder shows in the Filter by prefix box. Could you help to take a look?
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/af069481-6189-49ee-a286-68a1b972ed1f)

**Comment by v-xianya** [comment]
Hi @JasonYeMSFT  Verified comments on the build 20230731.1. The issue on the comment3 is fixed.

For below scenario：
Steps:
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Right click the blob container -> Click 'Open in React'.
3. Open 'View Options' panel -> Type 'a' into the 'Filter by prefix' box.
4. Create a new folder -> The 'Filter by prefix' box is reset.

Actual: The text box is not auto focused. Is this intentional? (For the old blob explorer, the text box is auto focused.)

**Comment by JasonYeMSFT** [comment]
Yes, I think the new behavior makes more sense.
