### ISSUE TITLE
Ctrl+F doesn't open the view options panel

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7105]
**Storage Explorer Version**: 1.31.0-dev
**Build Number**: 20230726.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4.1 (Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.30.2)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Right click the blob container -> Click 'Open in React'.
3. Press Ctrl+F.
4. Check whether the view options panel is opened.

## Expected Experience ##
The view options panel is opened.

## Actual Experience ##
The view options panel is not opened.

**Comment by v-xianya** [comment]
Hi @JasonYeMSFT Verified this issue on the build 20230727.4. 
Ctrl+F opens the view options panel. 
No placeholder shows in the 'Filter by prefix(case-sensitive)' box, could please help to check it? thanks
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/0ba51980-a45f-4a97-8381-bd3c9d75a2e9)

**Comment by JasonYeMSFT** [comment]
@v-xianya What do you mean by the "placeholder" in the text box?

**Comment by v-xianya** [comment]
Hi @JasonYeMSFT Yes, the text box is not auto focused when the side panel opens.
Here is the screenshot in old blob explorer
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/5314d3f8-1794-429d-8251-3b7cc2d06e25)

**Comment by JasonYeMSFT** [comment]
I made a fix to autofocus the text box when the side panel opens.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230731.1. Fixed. So, we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/12297234-75f7-4d5e-9cb8-67b02b017cda)
