### ISSUE TITLE
An extra '/' shows next to the folder name if switch list mode from 'Flat' to 'Hierarchical'

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7107]
**Storage Explorer Version:** 1.31.0-dev
**Build Number:** 20230726.3
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4.1 (Apple M1 Pro)
**Architecture:** x64/x64/arm64
**How Found:** From running test cases
**Regression From:** Previous release (1.30.2)

## Steps to Reproduce ##
1. Open Settings -> Set 'Default List Mode' to 'Flat'.
2. Expand one storage account -> Blob Containers.
3. Select and right click one blob container -> Click 'Open in React'.
4. Upload a folder -> Open the view options panel -> Select 'Hierarchical' as the list mode.
5. Check no extra '/' shows next to the folder name.

## Expected Experience ##
No extra '/' shows next to the folder name.

## Actual Experience ##
An extra '/' shows next to the folder name.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/b14237f7-1c30-4a40-ace5-c315623c4cb3)

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230727.4. Fixed. So, we are going to close it.
