### ISSUE TITLE
The new ADLS Gen2 blob explorer displays as a regular blob explorer

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7108]
**Storage Explorer Version:** 1.31.0-dev
**Build Number:** 20230726.3
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4.1 (Apple M1 Pro)
**Architecture:** x64/x64/arm64
**How Found:** From running test cases
**Regression From:** Previous release (1.30.2)

## Steps to Reproduce ##

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Select and right click one blob container -> Click 'Open in React'.
3. Check whether new ADLS Gen2 blob explorer displays correctly.

## Expected Experience ##
The new ADLS Gen2 blob explorer displays correctly.

The screenshot of the previous ADLS Gen2 blob container:
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/e2cfa0b5-ba40-4de9-8bf1-d530e145f97a)

## Actual Experience ##
The new ADLS Gen2 blob explorer displays as a regular blob explorer.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/bb0153c9-8f63-4903-9a4f-67d5b2f2ec37)

**Comment by JasonYeMSFT** [comment]
We don't plan to use this explorer for Gen2 containers. I will remove the "Open React" action from Gen2 container nodes.

**Comment by JasonYeMSFT** [comment]
@v-kellyluo This issue should be resolved now. The Blob Explorer open code has been cleaned up.

**Comment by v-xianya** [comment]
Verified this issue on the build 20230802.3. Fixed.
