### ISSUE TITLE
Unable to access Azure Storage Explorer  - looks like account disabled

### ISSUE THREAD

**Issue by gokulbab** [microsoft/AzureStorageExplorer#7111]
{
  "message": "\"{\\n  \\\"message\\\": \\\"\\\\\\\"AADSTS500571: The guest user account is disabled.\\\\\\\\r\\\\\\\\nTrace ID: 3333c240-b7e4-4a1a-abdd-9cd827641200\\\\\\\\r\\\\\\\\nCorrelation ID: e462d9fa-7d33-48a2-9e6e-984677707987\\\\\\\\r\\\\\\\\nTimestamp: 2023-07-26 18:14:20Z\\\\\\\"\\\"\\n}\""
}

**Comment by MRayermannMSFT** [comment]
@gokulbab you will need to reach out to Azure support for help with this problem.
