### ISSUE TITLE
The action 'Edit Tags...' is disabled for one blob/blob snapshot/blob version

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7115]
**Storage Explorer Version**: 1.31.0-dev
**Build Number**: 20230727.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4.1 (Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.30.2)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Right click it -> Click 'Open in React'.
3. Upload a blob -> Right click the blob.
4. Check whether the action 'Edit Tags...' is enabled.

## Expected Experience ##
The action 'Edit Tags...' is enabled.

## Actual Experience ##
The action 'Edit Tags...' is disabled.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230728.3. Fixed.
