### ISSUE TITLE
The 'Back' button is not enabled when applying filter by prefix/tag query

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7117]
**Storage Explorer Version**: 1.31.0-dev
**Build Number**: 20230727.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4.1 (Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.30.2)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Right click it -> Click 'Open in React'.
3. Open the view options panel -> Type 'a' to the filter by prefix box.
4. Check whether the 'Back' button is enabled or not.

## Expected Experience ##
The 'Back' button is enabled.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/f1fda9cd-a8b1-4616-a573-0cbf69980b06)

## Actual Experience ##
The 'Back' button is disabled.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/8eee6175-ba9a-4bfe-b61d-3a23f90a9a37)

**Comment by JasonYeMSFT** [comment]
This is by design. We used to add one entry in the navigation history for every different prefix applied to the view, which is too overwhelming and easily overflows the navigation history since it only show up to 10 recent locations.

**Comment by v-xianya** [comment]
The 'Back' button is enabled when applying a tag query.
