### ISSUE TITLE
Configurable thread count for file uploads

### ISSUE THREAD

**Issue by seguler** [microsoft/AzureStorageExplorer#712]
A customer wants to configure the thread count used for file uploads, because they have an application that polls the uploaded files continuously and the application throws an error when the file is not written to sequentially.

Current workaround is to change the parameter DefaultParallelOperationThreadCount in the FlobManager.js to 1.

**Comment by MRayermannMSFT** [comment]
Closing. This is basically implemented with the various AzCopy settings we have now.
