### ISSUE TITLE
The 'Filter by prefix' box is reset if apply a tag query then reset it

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7121]
**Storage Explorer Version:** 1.31.0-dev
**Build Number:** 20230727.4
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4.1 (Apple M1 Pro)
**Architecture:** x64/x64/arm64
**How Found:** From running test cases
**Regression From:** Previous release (1.30.2)

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Right click one blob container -> Click 'Open in React'.
3. Open view options panel -> Type 'a' to the 'Filter by prefix' box.
4. Select 'Tag Query' -> Click 'Apply -> Reset'.
5. Check whether the filter by prefix box is not reset.

## Expected Experience ##
The filter by prefix box is not reset.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/06457b66-1486-420e-abb8-bd20ee6998a2)

## Actual Experience ##
The filter by prefix box is reset.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/7cf24d80-cce5-40bf-862a-c084a1e827dc)

**Comment by JasonYeMSFT** [comment]
The new behavior is intended. When the tags query is reset, the view is brought back to listing at the root without prefix so we clear the current prefix in the search box. 

On the other hand, we do need to clear the previous search prefix when applying the new tags query. I made a change to clear the search prefix when tags query is applied. In short, when the view changes, the search prefix should be updated to reflect the search prefix applied to the new view.
