### ISSUE TITLE
Unable to sign in and attach the account to azure storage explorer

### ISSUE THREAD

**Issue by PriyaBidkar** [microsoft/AzureStorageExplorer#7125]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.30.2

### Architecture

x64

### Storage Explorer Build Number

20230721.7

### Platform

Windows

### OS Version

Windows 10

### Bug Description

{
  "name": null,
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"self signed certificate in certificate chain\\\",\\n  \\\"stack\\\": \\\"Error: self signed certificate in certificate chain\\\\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1540:34)\\\\n    at TLSSocket.emit (node:events:513:28)\\\\n    at TLSSocket._finishInit (node:_tls_wrap:959:8)\\\\n    at ssl.onhandshakedone (node:_tls_wrap:743:12)\\\",\\n  \\\"code\\\": \\\"SELF_SIGNED_CERT_IN_CHAIN\\\"\\n}\""
}

### Steps to Reproduce

Attach my storage containers to Azure explorer

### Actual Experience

I need to add my account but it is showing error even after authenticating

### Expected Experience

I want to connect my Azure account with mail id nandkishorbidkar87@gmail.com with Azure Storage Explorer Tool

**Comment by MRayermannMSFT** [comment]
@PriyaBidkar can you give using system proxy setting a try? You can read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue we recommend opening a support ticket from the Azure portal. Alternatively you can open a new issue here. This issue will no longer be monitored.
