### ISSUE TITLE
The path on the address bar doesn't make sense if create a new folder using name '/'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7126]
**Storage Explorer Version**: 1.31.0-dev
**Build Number**: 20230728.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4.1 (Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: Ad-hoc testing
**Regression From**: Previous release (1.30.1)
## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Right click the blob container -> Click 'Open in React'.
3. Click 'New Folder' -> Type '/' into 'Name' field -> Click 'OK'.
4. Observe the path on the address bar.
5. Check whether it makes sense.

## Expected Experience ##
It makes sense.

Below is the screenshot of the old blob explorer.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/81bf01f3-8cc4-47fa-817f-36527bc9b05b)

## Actual Experience ##
It doesn't make sense.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/68e9b24b-da29-4339-92d0-7b2e1be0fcb5)

## Additional Context ##
This issue doesn't reproduce if type '/' then press 'Enter' on the address bar.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/8e8338a2-ecdc-4845-8e1d-6ce496eb9321)

**Comment by JasonYeMSFT** [comment]
Neither the new nor the old explorer is correct. There should be only one `<no name>` folder after creating a new folder with "/". I changed the new explorer code to have the correct behavior. The old explorer code will be won't fix.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230731.1. Fixed for both new blob explorer and old blob explorer.
There is one <no name> when creating a new folder with '/'. So, we are going to close this issue.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/c34fc983-26bf-4173-af48-1bea5495fdc8)
