### ISSUE TITLE
The option 'Hot' is incorrectly translated to '热访问层' instead of '热' on localized 'Change Default Access Tier' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7128]
**Storage Explorer Version**: 1.31.0-dev
**Build Number**: 20230731.1
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Language**: Chinese (zh-CN)
**Architecture**: x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select '中文(简体)' -> Restart Storage Explorer.
3. Right click one storage account -> Click the localized 'Set Default Access Tier...'. 
4. Check whether the localized option 'Hot' is correct.

## Expected Experience ##
The localized option 'Hot' is correct.

## Actual Experience ##
The localized option 'Hot' is incorrect.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/aaa1af9f-99d4-4fff-8aa6-a5b9600b296a)

## Additional Context ##
1. Here is the screenshot on English.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/b9a4dcc4-399b-4305-a3f8-bc0c102f807c)
2. The screenshot in 1.29.2.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/36e1d4e5-f47b-4100-9412-f8eae87ad6f2)

**Comment by JasonYeMSFT** [comment]
This should have been fixed now.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230831.2. Fixed. So, we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/433f2fb6-4010-465f-beb0-65452daf78b9)
