### ISSUE TITLE
The string 'messages' is incorrectly localized to '邮件' instead of '消息' on the delete confirmation dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7129]
**Storage Explorer Version**: 1.31.0-dev
**Build Number**: 20230731.1
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Language**: Chinese (zh-CN)
**Architecture**: x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##

1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select '中文(简体)' -> Restart Storage Explorer.
3. Expand one storage account -> Queues.
4. Add one message -> Select the message then click 'Delete'.
5. There is a confirmation dialog -> Observe the content in the dialog.
6. Check whether all strings are localized correctly.

## Expected Experience ##
All strings are localized correctly.

## Actual Experience ##
The string 'messages' is incorrectly localized to '邮件' instead of '消息'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/7452cafe-ffaa-4753-ad6f-9206a534bdcb)

## Additional Context ##
Here is the screenshot on English:
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/4700f87c-d26f-46c8-89b6-420cbf7a8f12)

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230829.2. Reproduce. So, we are going to reopen it.

**Comment by JasonYeMSFT** [comment]
This should have been fixed.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230831.1. Fixed. So, we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/5997786e-a7b7-4ec8-ad08-ba5e0080f960)
