### ISSUE TITLE
Upload a VHD file with 0B size to Blob accounts with a complete message

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#713]
Storage Explorer Version: 1.5.0
Platform/OS Version: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
Architecture: ia32/x64
Build Number: 20180927.14
Commit: a985fab8
Regression From: Not a regression

#### Steps to Reproduce: ####
1. Navigate to 'Experimental' menu -> Check 'Use AzCopy for Improved Blob Upload and Download'.
2. Select a Blob account -> Open one blob container and try to upload a VHD file with 0B in size.
3. Check  ‘Activities’
#### Expected Experience: ####
Prompt the page blob is not supported for blob account type.

#### Actual Experience: ####
Show a complete message in Activities.
![actual2](https://user-images.githubusercontent.com/41351993/46196638-2fd50380-c2f7-11e8-8827-368e8741e6b6.png)

**Comment by v-xianya** [comment]
This issue doesn't reproduce on 20181022.4. It would be better to show 'the page blob is not supported for blob account type' in Activities.
![image](https://user-images.githubusercontent.com/41351993/47281099-fcdb1280-d60b-11e8-96e4-1b93a702d876.png)

**Comment by v-xuanzh** [comment]
This issue has been fixed on the latest master build 20190723.4. So closed it.
