### ISSUE TITLE
The strings 'Copy' and 'Command Palette' are not localized on the preview panel

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7130]
**Storage Explorer Version:** 1.31.0-dev
**Build Number:** 20230731.1
**Branch:** main
**Platform/OS:** Windows 10/ Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Language:** All languages
**Architecture:** x64/x64/arm64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select '中文(简体)' -> Restart Storage Explorer.
3. Expand one storage account -> Blob Containers.
4. Upload a text file -> Click 'Preview'.
5. Right click the preview panel.
6. Check whether the strings 'Copy' and 'Command Palette' are localized.

## Expected Experience ##
The strings 'Copy' and 'Command Palette' are localized.

## Actual Experience ##
The strings 'Copy' and 'Command Palette' are not localized.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/226bd996-8751-49d6-b54e-9fa05aaf0e4c)

## Additional Context ##
1. This issue also reproduces for a json file.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/27f6e12e-ee3e-4609-9eab-a3a9c6d2bd8f)
2. This issue doesn't reproduce for 'Copy Rows' in the tabular preview panel.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/45651233-eade-44e4-ba6b-c16b775e9268)

**Comment by JasonYeMSFT** [comment]
These strings are provided by monaco editor, not us. We need to investigate how they could be localized.

**Comment by JasonYeMSFT** [comment]
There is no easy way to change those strings. I am going to won't fix this issue for now.
