### ISSUE TITLE
This request is not authorized to perform this operation.

### ISSUE THREAD

**Issue by aqeelawan375** [microsoft/AzureStorageExplorer#7132]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.30.2

### Architecture

i86

### Platform

Windows

### Bug Description

This request is not authorized to perform this operation.

This storage account's 'Firewalls & virtual networks' settings may be blocking access to storage services. Try adding your client IP address to the firewall exceptions, or by allowing access from 'all networks' instead of 'selected networks'. To learn more about Azure Storage firewalls and virtual networks, visit http://go.microsoft.com/fwlink/?LinkId=845443.

Error Details:
{
  "name": "RestError",
  "code": "AuthorizationFailure",
  "statusCode": 403,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://quickbite.blob.core.windows.net/?comp=list&include=metadata",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2021-10-04"
        },
        "accept": {
          "name": "Accept",
          "value": "application/xml"
        },
        "user-agent": {
          "name": "User-Agent",
          "value": "Microsoft Azure Storage Explorer/1.30.2 (win32) azsdk-js-storageblob/12.12.0 (NODE-VERSION v18.14.0; Windows_NT 10.0.22621)"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "a5571d65-7067-4711-8381-bd8bb0522fa3"
        },
        "authorization": {
          "name": "authorization",
          "value": "Bearer JSON Web Token Redacted"
        },
        "cookie": {
          "name": "Cookie",
          "value": ""
        }
      }
    },
    "withCredentials": false,
    "timeout": 0,
    "keepAlive": true,
    "decompressResponse": false,
    "requestId": "a5571d65-7067-4711-8381-bd8bb0522fa3"
  },
  "response": {
    "headers": {
      "_headersMap": {
        "content-length": {
          "name": "content-length",
          "value": "246"
        },
        "content-type": {
          "name": "content-type",
          "value": "application/xml"
        },
        "date": {
          "name": "date",
          "value": "Mon, 31 Jul 2023 15:21:48 GMT"
        },
        "server": {
          "name": "server",
          "value": "Microsoft-HTTPAPI/2.0"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "a5571d65-7067-4711-8381-bd8bb0522fa3"
        },
        "x-ms-error-code": {
          "name": "x-ms-error-code",
          "value": "AuthorizationFailure"
        },
        "x-ms-request-id": {
          "name": "x-ms-request-id",
          "value": "d0689159-901e-004c-6ac2-c32f37000000"
        }
      }
    },
    "request": {
      "streamResponseStatusCodes": {},
      "url": "https://quickbite.blob.core.windows.net/?comp=list&include=metadata",
      "method": "GET",
      "headers": {
        "_headersMap": {
          "x-ms-version": {
            "name": "x-ms-version",
            "value": "2021-10-04"
          },
          "accept": {
            "name": "Accept",
            "value": "application/xml"
          },
          "user-agent": {
            "name": "User-Agent",
            "value": "Microsoft Azure Storage Explorer/1.30.2 (win32) azsdk-js-storageblob/12.12.0 (NODE-VERSION v18.14.0; Windows_NT 10.0.22621)"
          },
          "x-ms-client-request-id": {
            "name": "x-ms-client-request-id",
            "value": "a5571d65-7067-4711-8381-bd8bb0522fa3"
          },
          "authorization": {
            "name": "authorization",
            "value": "Bearer JSON Web Token Redacted"
          },
          "cookie": {
            "name": "Cookie",
            "value": ""
          }
        }
      },
      "withCredentials": false,
      "timeout": 0,
      "keepAlive": true,
      "decompressResponse": false,
      "requestId": "a5571d65-7067-4711-8381-bd8bb0522fa3"
    },
    "status": 403,
    "bodyAsText": "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.\nRequestId:d0689159-901e-004c-6ac2-c32f37000000\nTime:2023-07-31T15:21:49.2070956Z</Message></Error>",
    "parsedBody": {
      "message": "This request is not authorized to perform this operation.\nRequestId:d0689159-901e-004c-6ac2-c32f37000000\nTime:2023-07-31T15:21:49.2070956Z",
      "code": "AuthorizationFailure"
    },
    "parsedHeaders": {
      "errorCode": "AuthorizationFailure",
      "content-length": "246",
      "content-type": "application/xml",
      "date": "Mon, 31 Jul 2023 15:21:48 GMT",
      "server": "Microsoft-HTTPAPI/2.0",
      "x-ms-client-request-id": "a5571d65-7067-4711-8381-bd8bb0522fa3",
      "x-ms-request-id": "d0689159-901e-004c-6ac2-c32f37000000"
    }
  },
  "details": {
    "errorCode": "AuthorizationFailure",
    "content-length": "246",
    "content-type": "application/xml",
    "date": "Mon, 31 Jul 2023 15:21:48 GMT",
    "server": "Microsoft-HTTPAPI/2.0",
    "x-ms-client-request-id": "a5571d65-7067-4711-8381-bd8bb0522fa3",
    "x-ms-request-id": "d0689159-901e-004c-6ac2-c32f37000000",
    "message": "This request is not authorized to perform this operation.\nRequestId:d0689159-901e-004c-6ac2-c32f37000000\nTime:2023-07-31T15:21:49.2070956Z",
    "code": "AuthorizationFailure"
  }
}

### Steps to Reproduce

1. Launch the explorer
2. Create the new blob container, then it shows the error which I reported in the Bug description

### Actual Experience

h

### Expected Experience

New blob container should be created. i-e I want to create an image blob container

**Comment by MRayermannMSFT** [comment]
@aqeelawan375 did you try what the error details suggested?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this issue we recommend opening a support ticket from the Azure portal. Alternatively you can open a new issue here. This issue will no longer be monitored.
