### ISSUE TITLE
Unable to query entities with empty PartitionKey field for emulator tables when running Azurite 3.25.0

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7134]
**Storage Explorer Version**: 1.31.0-dev
**Build Number**: 20230801.4
**Branch**: main
**Platform/OS**: Windows 10
**Architecture**: x64
**Azurite Version** 3.25.0
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch storage explorer -> Install and start Azurite 3.25.0.
2. Expand 'Emulator & Attached' -> 'Storage Accounts' -> (Emulator -Default Ports) (Key) -> Tables.
3. Create a table -> Add one entity (keep the Partitionkey field blank).
4. Click 'Query' -> Run query with the query clause `PartitionKey eq ''`.
5. Check whether it is able to query the entity.

## Expected Experience ##
It is able to query the entity.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/f0c41274-62f2-433a-b738-41d01f2a0312)

## Actual Experience ##
Unable to query the entity.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/a2921a59-f0a3-4e4e-81a0-9de109312e78)

## Additional Context ##
This issue doesn't reproduce when using Azurite 3.24.0.

**Comment by garrettbaski** [comment]
@v-xianya Azurite has a 3.25.1 hotfix version out now. This should solve the issue above. Please let me know if that is not the case.

**Comment by v-xianya** [comment]
Hi @garrettbaski This issue has been resolved after upgrading Azurite version to 3.25.1. So, we are going to close it.
