### ISSUE TITLE
Fail to download one file whose directory name ends with a dot

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7137]
**Storage Explorer Version**: 1.31.0-dev
**Build Number**: 20230802.3
**Branch**: main
**Platform/OS**: Windows 10
**Architecture**: x64
**How Found**: From running test cases
**Regression From**: Previous release (1.30.2)

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Create a folder named 'test.'.
3. Upload a file to the folder -> Try to download the file.
4. Check whether succeeds to download the file.

## Expected Experience ##
Succeed to download the file.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/9917ee2d-8245-479f-a649-fd675f25287a)

## Actual Experience ##
Fail to download the file.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/fa14e893-66cc-4d0a-b9b0-669bb1323341)

Error details:
`{
  "message": "\"failed to perform copy command due to error: cannot start job due to error: Invalid Blob or Windows Name..\\n\""
}`
## Additional Context ##
1. This issue also reproduces when using the action 'Download All...' under one folder name ends with a dot.
2. This issue doesn't reproduce on Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro).

**Comment by MRayermannMSFT** [comment]
It looks like this is expected: https://github.com/Azure/azure-storage-azcopy/releases/tag/v10.20.0#:~:text=Gracefully%20handle%20File%20Share%20trailing%20dot%20paths%20to%20Windows/Blob%20(that%20do%20not%20support%20trailing%20dot)%20by%20skipping%20such%20files
