### ISSUE TITLE
Ctrl+V works well on the blob snapshots view

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#714]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture**: ia32/x64
**Build Number**: 20180927.14
**Commit**: a985fab8
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Open one blob container then upload a blob named Dockerfile.txt to it.
2. Right click the uploaded blob and select 'Manage Snapshots'.
3. Copy another blob -> Paste it to the currently blob snapshots view using Ctrl +V.

#### Expected Experience: ####
Ctrl +V doesn't work.

#### Actual Experience: ####
1. Ctrl+V works well.
2. The copied blob shows a folder with the same as base blob 'Dockerfile.txt' after backing to the base blob level.
![ctrl_v](https://user-images.githubusercontent.com/34729022/46197098-4def3380-c2f8-11e8-9298-83a3948da267.png)

**Comment by v-xianya** [comment]
Verified this issue on build 20191220.9. This issue is similar with #411. So we close it.

**Actual Experience:**
1. Ctrl +V works well.
2. The copied blob shows in blob container editor.
![image](https://user-images.githubusercontent.com/41351993/71611578-f6afd100-2bd4-11ea-9e40-f6eeed182df9.png)
