### ISSUE TITLE
The search icon doesn't disappear after typing a letter to the filter by prefix box

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7140]
**Storage Explorer Version**: 1.31.0-dev
**Build Number**: 20230802.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.30.2)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Open one blob container -> Open the view options panel.
3. Type a letter to the filter by prefix box.
4. Check whether the search icon disappears.

## Expected Experience ##
The search icon disappears.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/b5f5098c-7cc9-4aeb-acca-31e908ec6926)

## Actual Experience ##
The search icon doesn't disappear.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/137e6bc7-8ea0-4d7d-832b-a4e0188f3250)

## Additional Context ##
This issue doesn't reproduce for file shares/ADLS Gen2 blob containers.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230803.5. Fixed. So, we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/b88c1883-3f08-47f7-831d-259568d9e1f9)
