### ISSUE TITLE
I can't access my blob container using microsoft azure storage explorer

### ISSUE THREAD

**Issue by junjibienestar** [Microsoft/AzureStorageExplorer#7141]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.18.1

### Architecture

i86

### Platform

Windows

### OS Version

windows

### Bug Description

No se pueden recuperar los recursos secundarios.

Detalles:
{
  "name": "FetchError",
  "message": "request to https://stgaccpdevops01rec.blob.core.windows.net/?include=metadata&comp=list failed, reason: self signed certificate in certificate chain",
  "__zone_symbol__error": {
    "originalStack": "Error: request to https://stgaccpdevops01rec.blob.core.windows.net/?include=metadata&comp=list failed, reason: self signed certificate in certificate chain\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError 

Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)",
  "type": "system",
  "errno": "SELF_SIGNED_CERT_IN_CHAIN",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}

### Steps to Reproduce

![blob](https://github.com/microsoft/AzureStorageExplorer/assets/88163316/61ce305d-c361-4f87-b018-bbee55348b6f)

### Actual Experience

I can't access my blob container using microsoft azure storage explorer

**Comment by MRayermannMSFT** [comment]
@junjibienestar can you give using system proxy setting a try? You can read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by JasonYeMSFT** [comment]
The system proxy support is added in 1.20.0, which is not available to you since you are using 1.18.1. Please consider upgrading the application if it is possible. We always encourage people to stay at the latest version not only for new features but also for security updates.
