### ISSUE TITLE
Timeout errors when attempting to access child resources

### ISSUE THREAD

**Issue by jaykay26** [microsoft/AzureStorageExplorer#7142]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.30.2

### Architecture

x64

### Storage Explorer Build Number

20230721.7

### Platform

Windows

### OS Version

Windows Server 2012 R2

### Bug Description

Unable to retrieve child resources

ProducerError:{
  "name": "Error",
  "message": "net::ERR_CONNECTION_TIMED_OUT",
  "stack": "Error: net::ERR_CONNECTION_TIMED_OUT\n    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49509)\n    at SimpleURLLoaderWrapper.emit (node:events:513:28)"
}

### Steps to Reproduce

1. Launch Storage Explorer
2. Connect to Azure Subscriptions using Azure account
3. Choose subscription to connect to
4. Go to subscription
5. Click on Storage account
6. Click on File Shares
7. Time out occurs when attempting to access the file share

### Actual Experience

When attempting to connect to a storage account, I can log onto Azure and connect to my subscriptions with no issues, but when I attempt to access a storage account file share, I get the following error:

Unable to retrieve child resources

ProducerError:{
  "name": "Error",
  "message": "net::ERR_CONNECTION_TIMED_OUT",
  "stack": "Error: net::ERR_CONNECTION_TIMED_OUT\n    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49509)\n    at SimpleURLLoaderWrapper.emit (node:events:513:28)"
}

I have made sure the proxy is set to system, and I've got internet access, including access to Azure, I'm a global admin, and this works fine from another VM in our tenancy on a different subscription, just not from the VM I'm having trouble with.
I've checked internet speed, that's fine, I'm continually getting timeout errors and cannot identify why.

### Expected Experience

To connect to the storage accounts file shares

**Comment by MRayermannMSFT** [comment]
First thing I want to note is that I am surprised that you are able to run Storage Explorer 1.30.2. The last version of Storage Explorer to use an Electron that supported Windows Server 2012 was 1.28. If all else fails, you may want to consider going back to 1.28. You can find that version here: https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.28.1

Ignoring that fact, for ERR_CONNECTION_TIMED_OUT, can you please try, on the same machine, using the Azure Portal to access your storage data?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of reponse. This issue will no longer be actively monitored. If you still need help, we recommend reaching out to Azure support, via openeng a ticket in the Azure portal. Alternatively you can open a new issue here.
