### ISSUE TITLE
The blob tags can be edited in one SAS attached secondary blob container with all permissions

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7144]
**Storage Explorer Version:** 1.31.0-dev
**Build Number:** 20230803.5
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture:** x64/x64/arm64
**How Found:** From running test cases
**Regression From:** Previous release (1.30.2)

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create one blob container -> Upload a blob.
3. Right click the blob container -> Click 'Open Secondary Location'.
4. Attach the secondary blob container via SAS URL (all permissions).
5. Switch to the attached secondary blob container.
6. Right click the blob -> Click 'Edit Tags...'.
7. Check whether the blob tags are read-only.

## Expected Experience ##
The blob tags are read-only.

## Actual Experience ##
The blob tags can be edited.

**Comment by MRayermannMSFT** [comment]
@JasonYeMSFT, email said this **wasn't** a regression, but it is tagged as one. Can you check if it is a regression, and then if it is really **not** a regression, please fix the issue tags and then don't worry about this until 1.32.0. Though I do feel like I remember this issue popping up before...

**Comment by v-xianya** [comment]
@MRayermannMSFT There is a typo in email. this issue is a regression. sorry for the confusion.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230804.3. Fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/b6555755-a336-4bbb-885a-31297297f89d)
