### ISSUE TITLE
Fail to delete more than one blob at the same time under the directory named '/'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7146]
**Storage Explorer Version**: 1.31.0-dev
**Build Number**: 20230803.5
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Create a new folder using the name ‘/’.
3. Upload two blobs to the folder -> Select the two blobs -> Click 'Delete'.
4. Check whether succeeds to delete the two blobs.

## Expected Experience ##
Succeed to delete the two blobs.

## Actual Experience ##
Fail to delete the two blobs.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/bccbbabe-146c-4642-af40-61ed1ae9acb3)

## Additional Context ##
This issue doesn't reproduce when deleting one blob.

**Comment by MRayermannMSFT** [comment]
@JasonYeMSFT, probably an AzCopy limitation. If so, no worries.

**Comment by JasonYeMSFT** [comment]
AzCopy collapses the consecutive slashes we give in the paths.
