### ISSUE TITLE
There are two navigation histories when applying the same tag query twice

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7147]
**Storage Explorer Version**: 1.31.0-dev
**Build Number**: 20230803.5
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: Exploratory testing
**Regression From**: Previous release (1.30.2)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Open one blob container -> Open the view options panel.
3. Select 'Tag Query' -> Click 'Apply' twice.
4. Open the recent locations.
5. Check whether there is only one navigation history for 'Filter xxx by tag query'.

## Expected Experience ##
There is only one navigation history for 'Filter xxx by tag query'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/5fc24238-9362-4ed9-86d1-e4ba7947efbe)

## Actual Experience ##
There are two navigation histories for 'Filter xxx by tag query'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/2b0aed95-0425-424b-98bb-b5e475f0a481)

**Comment by MRayermannMSFT** [comment]
@jasonyemsft, if you are making other changes to blob-extension and the fix for this is simple, then let's fix this now, otherwise, I'm ok leaving for 1.32 if you think either.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230804.3. Fixed. So, we are going to close it.
