### ISSUE TITLE
Showing the wrong message for the number of messages in a queue in Swedish

### ISSUE THREAD

**Issue by valuja** [microsoft/AzureStorageExplorer#7148]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.30.2

### Architecture

x64

### Storage Explorer Build Number

20230721.7

### Platform

Windows

### OS Version

WWindows 11

### Bug Description

The count of messages in a queue is showing the wrong numbers

![image](https://github.com/microsoft/AzureStorageExplorer/assets/51408735/8eb83037-bfc0-4e73-b07b-8389d03432d1)

This says "Showing 1 to 0 of 1 messages in queue" and this happens when there are no visible message in the queue but there are one that is being processed.

### Steps to Reproduce

1. Launch explorer
2. Open a Queue that has one message which is being processed so that it is not visible in the list

### Actual Experience

The message that is shown is wrong

### Expected Experience

Expect it to say "Visar 0 av 1 meddelande i kö"

**Comment by MRayermannMSFT** [comment]
@valuja while I investigate this, can you check what you see when running Storage Explorer in English and tell me if it is correct? I ask because the strings we have for english and Swedish have placeholders in the same order:

- `"MessagePageInfo": "Showing %1$s to %2$s of %3$s messages in queue"`
- `"MessagePageInfo": "Visar %1$s till %2$s av %3$s meddelanden i kö"`

So I think this may be an issue for all languages, not just Swedish.

**Comment by valuja** [comment]
Hi,

Thanks again for the feedback, it is not an important thing so no need to fix it until other stuff is done!

Best regards
Johan

Från: Matthew Rayermann ***@***.***>
Skickat: den 3 augusti 2023 18:41
Till: microsoft/AzureStorageExplorer ***@***.***>
Kopia: Johan Lundqvist ***@***.***>; Mention ***@***.***>
Ämne: Re: [microsoft/AzureStorageExplorer] Showing the wrong message for the number of messages in a queue in Swedish (Issue #7148)


@valuja<https://github.com/valuja> thanks for confirming this as well. This is a weird quirk that seems to happen when all messages are hidden. Basically the first number in the message is going to be off by 1. I'm not super sure when we'll get to fixing this. We're in the middle of moving to a new data grid library, so we'll likely fix it once we move queues to that new library.

**Comment by jguadagno** [comment]
You can replicate this in English if you have a message in the queue, the message gets processes, then you click the refresh toolbar button
