### ISSUE TITLE
Fail to upload/download blobs for local emulator

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#715]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture**: ia32/x64
**Build Number**: 20180927.14
**Commit**: a985fab8
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Navigate to 'Experimental' menu and check 'Use AzCopy for Improved Blob Upload and Download'. 
2. Attach to one local emulator.
3. Create a blob container then try to upload a blob to it.
4. Check the result.

#### Expected Experience: ####
Succeed to upload the blob.

#### Actual Experience: ####
Fail to upload the blob with error 'AzCopy quit unexpectedly'.
![fail](https://user-images.githubusercontent.com/34729022/46199249-17b4b280-c2fe-11e8-8f29-9803c2291a19.png)
#### More Info: ####
This issue also reproduces for Azurite.

**Comment by MRayermannMSFT** [comment]
This should be fixed in the latest build. Will let you know in email which one that is.
