### ISSUE TITLE
Fail to clone and rehydrate one blob between ADLS Gen2 and regular blob containers

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7151]
**Storage Explorer Version**: 1.31.0-dev
**Build Number**: 20230804.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.30.2)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob and set the access tier to 'Archive'.
3. Copy the archived blob -> Open one ADLS Gen2 blob container -> Click 'Paste'.
4. Click 'Apply' on the 'Copy and Rehydrate' dialog.
5. Check whether succeeds to copy and rehydrate the blob.

## Expected Experience ##
Succeed to copy and rehydrate the blob.

## Actual Experience ##
Fail to copy and rehydrate the blob.

Error details:
`  "name": "RestError",
  "message": "Specified feature is not yet supported for hierarchical namespace accounts.\nRequestId:f0a442c3-801e-0012-65a3-c65710000000\nTime:2023-08-04T07:13:05.1871550Z",`
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/8adbca01-c1b4-439b-b156-2e9d1af9e650)

## Additional Context ##
1. Show below error when pasting one archived blob from ADLS Gen2 blob container to regular blob container.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/8f4738f8-0424-4ea7-9fc3-c75a7c351eb7)

Error details:
`Cannot verify the source blob. Copying and rehydrating archive blob is only supported within the same region. Please check the region of the source and the destination storage account.`

2. The location of the source and the destination storage account used for testing is the same one.

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT
Verified this issue on the main build  202308.7.1.
1. Succeed to clone and rehydrate one blob from regular blob containers to ADLS Gen2 blob containers.
2. Fail to clone and rehydrate one blob from ADLS Gen2 blob containers to regular blob containers with error
"This request is not authorized to perform this operation using this permission". 
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/02d1c57c-c7b0-4a23-923e-f005e7afde02)

**Comment by MRayermannMSFT** [comment]
@v-xianya apologies, I did not see the note about doing a Gen2->Blob copy. This should be fixed now.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230808.1. Fixed.
