### ISSUE TITLE
Ctrl+V doesn't take effect in regular blob explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7158]
**Storage Explorer Version**: 1.31.0-dev
**Build Number**: 20230807.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.30.2)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Select the blob -> Click 'Copy'.
4. Create a new folder -> Press 'Ctrl+V'.
5. Check whether succeeds to paste the blob.

## Expected Experience ##
Succeed to paste the blob.

## Actual Experience ##
Ctrl+V doesn't take effect.

## Additional Context ##
This issue doesn't reproduce for ADLS Gen2 blob containers/File Shares.

**Comment by JasonYeMSFT** [comment]
I merged a fix for this. The shortcut for paste should now work. Besides, I made similar changes to the shortcut for "Refresh" (CtrlCmd+R) and "Open Side Panel" (CtrlCmd+F). After "New Folder", these two shortcuts should also work now.

**Comment by v-xianya** [comment]
Verified this issue on the build 20230808.1.

1. Ctrl+V works.
2. (CtrlCmd+R) and (CtrlCmd+F) also work after "New Folder", So, we are going to close this issue.
