### ISSUE TITLE
Confused error message shows when uploading a non-exists file 

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#716]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture**: ia32/x64
**Build Number**: 20180927.14
**Commit**: a985fab8
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Navigate to 'Experimental' menu and check 'Use AzCopy for Improved Blob Upload and Download'
2. Open one blob container -> Open Upload dialog with selected blob -> Keep the dialog is opened then delete the source file in local file system -> Click 'Upload'.
3. Check the error message.

#### Expected Experience: ####
The error message shows that the selected file is skipped due to it no longer exists.

#### Actual Experience: ####
Display a confused error message with 'AzCopy quit unexpectedly'.
![exist](https://user-images.githubusercontent.com/34729022/46199679-2a7bb700-c2ff-11e8-9702-474ffead9875.png)

**Comment by MRayermannMSFT** [comment]
AzCopy failed to give us an error message in the way that we expected. If they change to using the expected output format, we can present the error they give us. https://github.com/Azure/azure-storage-azcopy/issues/70

**Comment by dikokob** [comment]
I had the same issue. 
Disable use of AzCopy:
Preview -> Use AzCopy for Improved Blob Upload and Download

**Comment by jinglouMSFT** [comment]
@dikokob Would you mind elaborating a bit on your scenario so we can verify if the fix will fix the issue you ran into?  Thanks.

**Comment by MRayermannMSFT** [comment]
@v-xuanzh can you try repro'ing this again? Thanks!

**Comment by v-xuanzh** [comment]
Hi @MRayermannMSFT ,This issue has been fixed on the latest master build. Could you help to resolve it?
