### ISSUE TITLE
Focus does not go into explorer panels when clicking on tab for the panel

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#7161]
1. Have two react blob explorer open
2. For each, click in whitespace so focus is lost
3. Click on tab for whichever is not showing

Expect: focus is un-lost and set to something, ideally the toolbar (that is prior behavior)
Actual: focus is not un-lost

- [x] #7301
- [x] #7302
- [x] Table
- [x] Blob Containers
- [x] #7303

**Comment by JasonYeMSFT** [comment]
In 1.30.2, we only do this for (the old) blob explorer and queue explorer. ADLS Gen2, File Share explorers, Disks and Table explorers don't automatically focus the first enabled toolbar button.

**Comment by JasonYeMSFT** [comment]
I merged a fix for this issue in Blob Explorer (Gen2 as well since they will be using one explorer). This still need to be fixed in 
- [ ] File Share
- [ ] Queue
- [ ] Table
- [ ] Blob Containers
- [ ] App Configuration
