### ISSUE TITLE
Title the dialog window with 'Retry Transfers' label

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#717]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture**: ia32/x64
**Build Number**: 20180927.14
**Commit**: a985fab8
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Navigate to 'Experimental' menu and check 'Use AzCopy for Improved Blob Upload and Download'
2. Open one blob container then upload a blob to it.
3. Upload the same blob again -> Click 'Retry Failed and Skipped Transfers' link next to the displayed activity message.
4. Check the Retry dialog.

#### Suggestion: ####
Title the dialog window with 'Retry Transfers' label like 'Rename'/'Delete'/'Send Feedback' and so on.
![suggestion](https://user-images.githubusercontent.com/34729022/46199873-b1309400-c2ff-11e8-9570-83f23cc27009.png)

**Comment by MRayermannMSFT** [comment]
Will be fixed in tonight's build.
