### ISSUE TITLE
The pasted file will be transferred to the blob explorer if press Ctrl+V on the address bar/filter by prefix box 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7174]
**Storage Explorer Version**: 1.31.0
**Build Number**: 20230810.9
**Branch**: rel/1.31.0
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Copy the blob -> Click the address bar -> Press Ctrl+V.
4. Check there is no transfer activity log.

## Expected Experience ##
There is no transfer activity log.

## Actual Experience ##
There is a transfer activity log.

## Additional Context ##
1. This issue also reproduces when pressing Ctrl+V on 'Filter by prefix' box.
2. This issue doesn't reproduce in one ADLS Gen2 blob explorer/file share explorer.
3. Here is the record:
![0810](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/ddb3da60-be4e-44fb-a327-b33ce21c2e24)

**Comment by MRayermannMSFT** [comment]
Let's think about if there is a not-annoying solution to this. If there is let's use it. But keep the bar high.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230904.1. Fixed.
So, we are going to close it.
