### ISSUE TITLE
No icon shows for opened tabs against blob containers and queues after upgrading from 1.30.2 to 1.31.0

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7175]
**Storage Explorer Version**: 1.31.0
**Build Number**: 20230810.9
**Branch**: rel/1.31.0
**Platform/OS**: Windows 10
**Architecture**: x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Install and launch storage explorer 1.30.2 -> Make sure the setting 'Preserve Explorer Session' is enabled. 
2. Open one blob container and one queue permanently.
3. Uninstall 1.30.2 -> Install and launch 1.31.0.
4. Check the icons of the opened tabs show well.

## Expected Experience ##
The icons of the tabs show well.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/de9ee615-1c96-40dc-92d8-8bd37166b1c9)

## Actual Experience ##
No icon shows for the blob container and queue tabs.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/f09dd8d3-79e7-4cb8-8f2c-03f6e21c28cc)
## Additional Context ##
This issue doesn't reproduce for ADLS Gen2 blob containers/tables/file shares/resource groups/app configurations.

**Comment by JasonYeMSFT** [comment]
We made a breaking change to how to handle icons and it is incompatible with the old tab data. We will let users manually close/reopen the tabs to migrate to tab data using the new representation of icons.
