### ISSUE TITLE
Preview panel - JSON formatting

### ISSUE THREAD

**Issue by SeanFeldman** [microsoft/AzureStorageExplorer#7178]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

When previewing JSON blobs with the right content type, the content is not formatted, forcing to copy the contents and paste externally for formatting.

![image](https://github.com/microsoft/AzureStorageExplorer/assets/1309622/800080eb-a71c-47e4-af0c-af54c0dc2479)

### Desired Solution

Format JSON to allow large content to be presented on multiple lines

<img width="207" alt="image" src="https://github.com/microsoft/AzureStorageExplorer/assets/1309622/129db048-7483-4d22-b749-08f6bc08550d">

**Comment by MRayermannMSFT** [comment]
Hi @SeanFeldman this is already possible in-app today! First, the text preview is designed to initially show you a preview of what your file contains **exactly**. However for JSON files, you can use right click the preview, and then choose "Format JSON" to view a formatted version of your JSON file. You can also then right click and choose "Restore JSON" to view the original contents of the file.

**Comment by SeanFeldman** [comment]
Thank you, @MRayermannMSFT.
