### ISSUE TITLE
Experimental feature is disabled for the new opened instance

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#718]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra
**Architecture**: ia32/x64
**Build Number**: 20180929.2
**Commit**: a985fab8
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Launch Storage Explorer with Experimental feature enabled.
2. Open a new window(Make sure the main instance keep opened).
3. Check whether Experimental feature is enabled or not for the new opened window.

#### Expected Experience: ####
Experimental feature is enabled.

#### Actual Experience: ####
Experimental feature is disabled.

#### More Info: ####
This issue doesn't reproduce when reloading Storage Explorer.

**Comment by v-xianya** [comment]
This issue will no longer reproduce with the new search feature.
So we close it.
