### ISSUE TITLE
Global Sort & Load All & Load Batch Size Feedback

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#7180]
If you have feedback on the global sort feedback included in version 1.31.0, please share it here!

**Comment by ikki74** [comment]
Hello,
I am trying to test global sort but it is not working. It seems it is not activated and I dont know how to activate (p.e. I have tables with more that 1000 elements, but it is not loading all the elements for the global sort). Can you help me and tell me how to activate it?
Thanks,
Sergio

**Comment by HasibAhmed577** [comment]
I have enabled global sort from the settings and it is working fine. Useful feature 👍 .
<img width="688" alt="image" src="https://github.com/microsoft/AzureStorageExplorer/assets/90024856/1bc1d5a1-23d0-4748-ae44-64eba5f2dcd8">

**Comment by ikki74** [comment]
Thanks a lot! I didnt see that configuracion, now it is working perfectly!

**Comment by dspnav29** [comment]
This feature would be extremely helpful for Blob Containers!

**Comment by MRayermannMSFT** [comment]
> This feature would be extremely helpful for Blob Containers!

Hi @dspnav29 , global sort is currently on track to be added to both blob containers and file shares in 1.32. Thanks for the feedback.

**Comment by MRayermannMSFT** [comment]
For any further feedback on global sort, please open a new issue. Thanks everyone.
