### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by jaycosentino** [microsoft/AzureStorageExplorer#7183]
It looks to me that I am in, but when I go to Blob Containers, I get an authentication error.  I use a storage container for my video using Media Services.  I am the owner of the account and should have complete access to everything.  

Not sure what to do.

Jay Cosentino

This request is not authorized to perform this operation.

This storage account's 'Firewalls & virtual networks' settings may be blocking access to storage services. Try adding your client IP address to the firewall exceptions, or by allowing access from 'all networks' instead of 'selected networks'. To learn more about Azure Storage firewalls and virtual networks, visit http://go.microsoft.com/fwlink/?LinkId=845443.

Error Details:
{
  "name": "RestError",
  "code": "AuthenticationFailed",
  "statusCode": 403,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://arclearn3.blob.core.windows.net/?comp=list&include=metadata",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2021-10-04"
        },
        "accept": {
          "name": "Accept",
          "value": "application/xml"
        },
        "user-agent": {
          "name": "User-Agent",
          "value": "Microsoft Azure Storage Explorer/1.30.2 (win32) azsdk-js-storageblob/12.12.0 (NODE-VERSION v18.14.0; Windows_NT 10.0.19045)"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "4c015666-9c43-4ede-ac5d-f74f025f8941"
        },
        "x-ms-date": {
          "name": "x-ms-date",
          "value": "Sat, 12 Aug 2023 22:36:14 GMT"
        },
        "authorization": {
          "name": "Authorization",
          "value": "Signed SharedKey Redacted="
        },
        "cookie": {
          "name": "Cookie",
          "value": ""
        }
      }
    },
    "withCredentials": false,
    "timeout": 0,
    "keepAlive": true,
    "decompressResponse": false,
    "requestId": "4c015666-9c43-4ede-ac5d-f74f025f8941"
  },
  "response": {
    "headers": {
      "_headersMap": {
        "content-length": {
          "name": "content-length",
          "value": "727"
        },
        "content-type": {
          "name": "content-type",
          "value": "application/xml"
        },
        "date": {
          "name": "date",
          "value": "Sat, 12 Aug 2023 22:36:15 GMT"
        },
        "server": {
          "name": "server",
          "value": "Microsoft-HTTPAPI/2.0"
        },
        "x-ms-error-code": {
          "name": "x-ms-error-code",
          "value": "AuthenticationFailed"
        },
        "x-ms-request-id": {
          "name": "x-ms-request-id",
          "value": "47b0bbd7-e01e-0033-186d-cd5a1f000000"
        }
      }
    },
    "request": {
      "streamResponseStatusCodes": {},
      "url": "https://arclearn3.blob.core.windows.net/?comp=list&include=metadata",
      "method": "GET",
      "headers": {
        "_headersMap": {
          "x-ms-version": {
            "name": "x-ms-version",
            "value": "2021-10-04"
          },
          "accept": {
            "name": "Accept",
            "value": "application/xml"
          },
          "user-agent": {
            "name": "User-Agent",
            "value": "Microsoft Azure Storage Explorer/1.30.2 (win32) azsdk-js-storageblob/12.12.0 (NODE-VERSION v18.14.0; Windows_NT 10.0.19045)"
          },
          "x-ms-client-request-id": {
            "name": "x-ms-client-request-id",
            "value": "4c015666-9c43-4ede-ac5d-f74f025f8941"
          },
          "x-ms-date": {
            "name": "x-ms-date",
            "value": "Sat, 12 Aug 2023 22:36:14 GMT"
          },
          "authorization": {
            "name": "Authorization",
            "value": "SharedKey REDACTED"
          },
          "cookie": {
            "name": "Cookie",
            "value": ""
          }
        }
      },
      "withCredentials": false,
      "timeout": 0,
      "keepAlive": true,
      "decompressResponse": false,
      "requestId": "4c015666-9c43-4ede-ac5d-f74f025f8941"
    },
    "status": 403,
    "bodyAsText": "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:47b0bbd7-e01e-0033-186d-cd5a1f000000\nTime:2023-08-12T22:36:15.6090321Z</Message><AuthenticationErrorDetail>The MAC signature found in the HTTP request '22paDn1xNoDluh3awHz1muG3W4y2waHWYlE2tM7rF5E=' is not the same as any computed signature. Server used following string to sign: 'GET\n\n\n\n\n\n\n\n\n\n\n\nx-ms-client-request-id:4c015666-9c43-4ede-ac5d-f74f025f8941\nx-ms-date:Sat, 12 Aug 2023 22:36:14 GMT\nx-ms-version:2021-10-04\n/arclearn3/\ncomp:list\ninclude:metadata'.</AuthenticationErrorDetail></Error>",
    "parsedBody": {
      "message": "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:47b0bbd7-e01e-0033-186d-cd5a1f000000\nTime:2023-08-12T22:36:15.6090321Z",
      "code": "AuthenticationFailed",
      "AuthenticationErrorDetail": "The MAC signature found in the HTTP request '22paDn1xNoDluh3awHz1muG3W4y2waHWYlE2tM7rF5E=' is not the same as any computed signature. Server used following string to sign: 'GET\n\n\n\n\n\n\n\n\n\n\n\nx-ms-client-request-id:4c015666-9c43-4ede-ac5d-f74f025f8941\nx-ms-date:Sat, 12 Aug 2023 22:36:14 GMT\nx-ms-version:2021-10-04\n/arclearn3/\ncomp:list\ninclude:metadata'."
    },
    "parsedHeaders": {
      "errorCode": "AuthenticationFailed",
      "content-length": "727",
      "content-type": "application/xml",
      "date": "Sat, 12 Aug 2023 22:36:15 GMT",
      "server": "Microsoft-HTTPAPI/2.0",
      "x-ms-request-id": "47b0bbd7-e01e-0033-186d-cd5a1f000000"
    }
  },
  "details": {
    "errorCode": "AuthenticationFailed",
    "content-length": "727",
    "content-type": "application/xml",
    "date": "Sat, 12 Aug 2023 22:36:15 GMT",
    "server": "Microsoft-HTTPAPI/2.0",
    "x-ms-request-id": "47b0bbd7-e01e-0033-186d-cd5a1f000000",
    "message": "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:47b0bbd7-e01e-0033-186d-cd5a1f000000\nTime:2023-08-12T22:36:15.6090321Z",
    "code": "AuthenticationFailed",
    "AuthenticationErrorDetail": "The MAC signature found in the HTTP request '22paDn1xNoDluh3awHz1muG3W4y2waHWYlE2tM7rF5E=' is not the same as any computed signature. Server used following string to sign: 'GET\n\n\n\n\n\n\n\n\n\n\n\nx-ms-client-request-id:4c015666-9c43-4ede-ac5d-f74f025f8941\nx-ms-date:Sat, 12 Aug 2023 22:36:14 GMT\nx-ms-version:2021-10-04\n/arclearn3/\ncomp:list\ninclude:metadata'."
  }
}

**Comment by MRayermannMSFT** [comment]
@jaycosentino did you attach with a connection string or name&key? If so, could you please re-attach and make sure that:
- your storage account name is correct (anywhere it is present in input you give to storage explorer)
- your storage account key is correct (make sure it hasn't been rotated, if possible, grab a fresh key value from the Azure portal)
