### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by Bryton07** [microsoft/AzureStorageExplorer#7184]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.30.0

### Architecture

x64

### Platform

macOS

### Bug Description

Unable to retrieve child resources

ProducerError:{
  "message": "{\"message\":\"The resource you are attempting to access is in a tenant which is currently filtered out. Un-filter it to access this resource.\",\"operationError\":{}}"
}

### Steps to Reproduce

1.Launch Storage explorer
2. Connect to account and blob storage
3. Error with failure to connect

### Actual Experience

I am can not see any of the files that are uploaded or processed in the blob storage containers.

**Comment by MRayermannMSFT** [comment]
@Bryton07 please do the following:
1. Go to the account panel (person icon on the left) and make sure to un-filter the tenant that the resource you are trying to access is in
2. If the tenant is already un-filtered, please try removing, and re-adding your account
3. If that does not work, please try using the Help -> Reset -> Select authentication only, feature to do a reset of auth related features, then sign back in, and try again

Let us know if none of those help.

**Comment by Bryton07** [comment]
﻿Thank you for the options. I have tried all the options but the issue has not been resolved.When trying to access my containers in azure this below is the error I am getting as well.{
  "sessionId": "c0c0a28774b94dadbbb40fc8295da32f",
  "uri": "https://atm.portal.azure.com/api/Utilities/getClientIp",
  "type": "POST",
  "correlationId": null,
  "clientRequestId": "85db8761-173a-4bdc-8d72-db8114bca003"
}Thank you!SincerelyBrighton MasukaOn Aug 14, 2023, at 13:13, Matthew Rayermann ***@***.***> wrote:﻿
@Bryton07 please do the following:

Go to the account panel (person icon on the left) and make sure to un-filter the tenant that the resource you are trying to access is in
If the tenant is already un-filtered, please try removing, and re-adding your account
If that does not work, please try using the Help -> Reset -> Select authentication only, feature to do a reset of auth related features, then sign back in, and try again

Let us know if none of those help.

**Comment by MRayermannMSFT** [comment]
@Bryton07 can you elaborate on when you are seeing this error?

```
{
  "sessionId": "c0c0a28774b94dadbbb40fc8295da32f",
  "uri": "https://atm.portal.azure.com/api/Utilities/getClientIp",
  "type": "POST",
  "correlationId": null,
  "clientRequestId": "85db8761-173a-4bdc-8d72-db8114bca003"
}
```

We have never seen such an error before. It also looks like an error that would happen when using portal. Can you confirm that you saw this when using Storage Explorer?

**Comment by Bryton07** [comment]
The issue is now resolved and can access the files from the storage. That message was from the azure homepage under containers.Thank you!SincerelyBrighton MasukaOn Aug 21, 2023, at 11:22, Matthew Rayermann ***@***.***> wrote:﻿
@Bryton07 can you elaborate on when you are seeing this error?
{
  "sessionId": "c0c0a28774b94dadbbb40fc8295da32f",
  "uri": "https://atm.portal.azure.com/api/Utilities/getClientIp",
  "type": "POST",
  "correlationId": null,
  "clientRequestId": "85db8761-173a-4bdc-8d72-db8114bca003"
}

We have never seen such an error before. It also looks like an error that would happen when using portal. Can you confirm that you saw this when using Storage Explorer?
