### ISSUE TITLE
Clicking 'Open Folder' always open the parent directory of the downloaded blob 

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#719]
Storage Explorer Version: 1.5.0
Platform/OS Version: Linux Ubuntu 16.04
Architecture: x64
Build Number: 20180929.2
Commit: 8a55f0d3
Regression From: Not a regression

#### Steps to Reproduce: ####
1. Navigate to ‘Experimental’ menu -> Check ‘Use Azcopy for Improved Blob Upload and Download’.
2. Open one blob container then download a blob.
3. Click ‘Open Folder’ in Activities after successful download.
4. Check the opened directory.

#### Expected Experience: ####
Open the directory of the downloaded blob.
#### Actual Experience: ####
Open the parent directory of the downloaded blob.
![capture](https://user-images.githubusercontent.com/41351993/46242566-eef1f300-c3b9-11e8-99fe-373a6b2e6e60.PNG)

#### More Info: ####
This issue doesn't reproduce when unchecking ‘Use Azcopy for Improved Blob Upload and Download’.

**Comment by MRayermannMSFT** [comment]
Oops. I'll have a fix for this in tonight's build. Just need to append /. to the path I'm opening.

**Comment by MRayermannMSFT** [comment]
You can find a fix for this in 20181003.1
