### ISSUE TITLE
Enable 'Edit tags...' for Azurite emulated storage

### ISSUE THREAD

**Issue by Itzalive** [microsoft/AzureStorageExplorer#7195]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Cannot 'Edit tags...' for emulated storage

### Desired Solution

Azurite now supports viewing and editting tags for a blob, please enable the 'edit tags' for emulated storage.

### Alternatives and Workarounds

The alternative is to create a SAS token that allows viewing tags and view them via a browser. This is much slower as is a multi step process. It's also difficult to edit the tags using this method.

### Additional Context

![image](https://github.com/microsoft/AzureStorageExplorer/assets/1061907/3ebcc799-4969-4f20-9562-44f2152cf2d5)

Using Storage Explorer 1.31.0 (92), Azurite 3.24.0

**Comment by MRayermannMSFT** [comment]
Change merged. This will be in 1.32
