### ISSUE TITLE
Search inside Blob Containers takes forever in v1.31.0

### ISSUE THREAD

**Issue by nemanjavicovicfz** [microsoft/AzureStorageExplorer#7197]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

v1.31.0

### Regression From

v1.30.2

### Architecture

x64

### Storage Explorer Build Number

20230810.9

### Platform

All

### OS Version

Windows 11

### Bug Description

This takes forever:

![image](https://github.com/microsoft/AzureStorageExplorer/assets/92727505/4331f31e-da96-4b07-9abb-06d5f442680e)

### Steps to Reproduce

1. Launch Storage Explorer
2. Go to some storage account
3. Select Blob Containers
4. Right click on Blob Containers
5. Click on Search from here
6. Type the container name you want to find

### Actual Experience

It takes forever, and never finds anything

### Expected Experience

It finds expected container

**Comment by JasonYeMSFT** [comment]
@nemanjavicovicfz From the status message, are you still seeing it making progress or does it complete stop increasing the number of nodes scanned at some point? If it completely stopped it might be a bug we need to investigate. If you can reproduce the hang, please set the log level to "debug" in the settings, do a search, get the log files from App Menu > Help > Open Logs Directory, and share the latest log files with us. After that, you can turn the log level back to "info" to reduce the log output.

When we finish searching but cannot find any result, we will show completed message for it. In most cases, the perf bottleneck of the search is the network. If the search is still making progress, it's possible that your internet connection is not fast enough or your connection is throttled.

**Comment by nemanjavicovicfz** [comment]
I can see progress and like more than 600 000 nodes scanned (after half an hour no found), and still scanning... It never finishes. It's not about internet connection for sure, because my colleague next to me is using previous version of Storage Explorer and it finds container in 5 seconds... 

Here are log files you asked:
[2023-08-17_102917_editor_21080.log](https://github.com/microsoft/AzureStorageExplorer/files/12367681/2023-08-17_102917_editor_21080.log)
[2023-08-17_102917_main_33668.log](https://github.com/microsoft/AzureStorageExplorer/files/12367682/2023-08-17_102917_main_33668.log)
[2023-08-17_102917_blob-extension_19876.log](https://github.com/microsoft/AzureStorageExplorer/files/12367684/2023-08-17_102917_blob-extension_19876.log)

**Comment by nemanjavicovicfz** [comment]
And a proof that I'm searching the correct value:

<img width="154" alt="image" src="https://github.com/microsoft/AzureStorageExplorer/assets/92727505/a11330a7-ea11-4f11-8dbc-4c023664edba">

... this never finishes:

<img width="153" alt="image" src="https://github.com/microsoft/AzureStorageExplorer/assets/92727505/223054e3-0d30-4cd5-a4d6-889adbe687c9">

**Comment by JasonYeMSFT** [comment]
I found the container in the logs. We did get the container but for some reason the search tree fails to present it.

**Comment by nemanjavicovicfz** [comment]
Hmmm OK I think I understand. Search is working fine, but showing search results is not

**Comment by JasonYeMSFT** [comment]
@nemanjavicovicfz Could you click on the search box and see what options are selected in the dropdown menu? Like in my screenshot, Storage Accounts and Blob Containers are selected. If Blob Containers option is not selected, could you select it and re-run the search?
<img width="427" alt="image" src="https://github.com/microsoft/AzureStorageExplorer/assets/39359541/976d39b6-7fa9-4402-908d-c7a54b221cf4">

**Comment by JasonYeMSFT** [comment]
I discovered a bug that explains why it's loading forever. Basically we are infinitely listing the first batch of containers. We will try to fix this problem asap. Before that gets out, please consider downgrading to the previous version for now. Sorry about the inconvenience.

**Comment by nemanjavicovicfz** [comment]
Nice one. Thanks for information. Hope fix will be deployed soon as new version feels much nicer than previous ones
