### ISSUE TITLE
1.31.0 NODE_ENV Environment Variable

### ISSUE THREAD

**Issue by sacunningham** [microsoft/AzureStorageExplorer#7198]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.31.0

### Architecture

x64

### Storage Explorer Build Number

20230810.9

### Platform

Windows

### OS Version

Windows 11 Pro 22H2

### Bug Description

Having an environment variable of NODE_ENV = development causes the program to fail on the splash screen.  The splash screen is displayed but the main window never loads, the splash screen remains shown until it is closed.  Removing the NODE_ENV environment variable fixes the issue. 

### Steps to Reproduce

1. On Windows 11 set a system environment variable NODE_ENV = development
2. Launch Azure Storage Explorer

### Actual Experience

The application fails to load past the splash screen.

**Comment by JasonYeMSFT** [comment]
@sacunningham We have never expected our users to have this environment variable configured globally. During development mode, we import some dev dependencies to help us develop but they are not present in the release. Is there a reason you want to keep the flag on? In most cases, it would result in much more logging stuff being written and will make the application slower if you run it in the development mode.

**Comment by sacunningham** [comment]
Understood.  I use that environment variable globally on my development machine for other projects that I develop.  I wanted to bring the issue to your attention because I’ve been using Azure Storage Explorer for years with NODE_ENV set globally without issue.  It wasn’t until the most recent update that I experienced the problem of the program getting stuck at the loading/splash screen.

Regards,
Sean Cunningham | Senior Engineer | Kenexis
T +1 614-353-9051 | www.<www.Kenexis.com>Kenexis<www.Kenexis.com>.com<www.Kenexis.com>

**Comment by MRayermannMSFT** [comment]
@sacunningham thanks for the info. We'll be looking to see how we can fix this experience for you in our next version. In the meantime, you could consider launching Storage Explorer via a shortcut, which first invokes cmd.exe, and unsets NODE_ENV. You could use this as a starting guide: https://stackoverflow.com/questions/3036325/can-i-set-an-environment-variable-for-an-application-using-a-shortcut-in-windows

Alternatively you can download the previous version of Storage Explorer from here: https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.30.2

**Comment by JasonYeMSFT** [comment]
@craxal Could you take a look at the broken dependency and find a way to mitigate this problem?

**Comment by sacunningham** [comment]
Apologies, i misidentified the cause of my issue.  Yesterday removing the NODE_ENV environment variable seemed to fix the issue.  Today the issue is back and the NODE_ENV doesn't exist.  I've attached output when running the storage explorer from the terminal to assist.  Again, the behavior the app getting stuck on the loading screen.
[CMD Output.txt](https://github.com/microsoft/AzureStorageExplorer/files/12372724/CMD.Output.txt)

**Comment by MRayermannMSFT** [comment]
Issue has been mitigated for 1.31.1. In 1.32.0, let's figure out how to do this debug ext properly.

**Comment by craxal** [comment]
It does not appear that any of the underlying components in Storage Explorer recognize or use `NODE_ENV`, so I think we can remove any of our own code that looks for it. We can look for a different variable to enable debug mode.
