### ISSUE TITLE
It navigates to an incorrect page if click the link 'Learn more about access tiers' on 'Update Access Tier' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7199]
**Storage Explorer Version**: 1.32.0-dev
**Build Number**: 20230817.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.31.0)

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Open one blob container -> Upload one blob.
3. Right click the blob -> Click 'Change Access Tier...'.
4. Click the link 'Learn more about access tiers' on the dialog.
5. Check whether navigates to the correct page.

## Expected Experience ##
 It navigates to the correct page.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/26b12dce-f445-441d-91eb-335f81dd85fd)

## Actual Experience ##
It navigates to an incorrect page.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/a4a2944f-6f63-4431-bec9-f68fdd9afaa2)

## Additional Context ##
1. This issue also reproduces for page blobs under premium storage account.
2. This issue doesn't reproduce for blobs under regular blob container.
3. This issue doesn't reproduce for the link on 'Change Default Access Tier' dialog.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/90b6eb09-0d72-4d98-b782-35bffe1a0fbc)

**Comment by JasonYeMSFT** [comment]
I just checked. This issue should have been fixed.

**Comment by v-xianya** [comment]
Hi @JasonYeMSFT
Verified this issue on the main build 20230906.9.
The link opens the page below. is this the expected page?
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/0a95eb7f-934c-4778-a38d-3646f6df3225)

**Comment by JasonYeMSFT** [comment]
> Hi @JasonYeMSFT Verified this issue on the main build 20230906.9. The link opens the page below. is this the expected page? ![image](https://user-images.githubusercontent.com/41351993/266217186-0a95eb7f-934c-4778-a38d-3646f6df3225.png)

For block blobs, it should go to this page: https://learn.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview
For page blobs, it should go to this page: https://learn.microsoft.com/en-us/azure/virtual-machines/disks-types

**Comment by v-xianya** [comment]
@JasonYeMSFT Got it. thanks for the response! We are going to close this issue.
