### ISSUE TITLE
Can not handle two accounts with the same name

### ISSUE THREAD

**Issue by Confuset** [Microsoft/AzureStorageExplorer#72]
**Storage Explorer Version:**
1.0.0
**OS Version:**
Win 10
**Steps to Reproduce:**

1. Create private account a@b.c
2. Create another account bound to some Company AD a@b.c

**Expected Experience:**
Can drill down in browser to see storage accounts etc.

**Actual Experience:**
Can not drill down. ASE is not able to expand any node.
Also when you delete one of those two accounts in Account Management in ASE it will delete both…

**Comment by MRayermannMSFT** [comment]
@Confuset , are you getting the "Subscriptions for one or more tenants could not be retrieved" message in the account panel?

**Comment by Confuset** [comment]
Not that iam aware of.

in account managment my Microsoft account listed 3 subscriptions (which is correct). For the other account i was asked to reenter credentials, what i did not do, because the blob storage, i was interested in was one of the 3 listed already of my Microsoft account.

in the tree browser i could see all 3 subcriptions, but when i tried to expand one of those, it failed with no message. the + (for expand) just disappeared.

i then tried to delete the one account i was not using and for which it asked for the credentials, but when i did that both account where deleted.

i have the feeling that Storage Explorer does not cope well with to accounts having the same mail address…

**Comment by Confuset** [comment]
side not. after readding my Microsoft Account everything worked :-)

**Comment by MRayermannMSFT** [comment]
I'm glad you got it working, but it does seem like you were in a less than ideal state for quite a while though. So I'm going to leave this issue open until we can repro it and figure out what went wrong. :)

**Comment by MRayermannMSFT** [comment]
@chillryan , so let me understand this correctly,

You have your "rhill@gre..." email address, and that has both an MSA and an O365 account associated with it. Then you also have your "ryanchill..." email address which is just an MSA.

For "ryanchill...", you have no issues. But for "rhill@gre...", you have to duplicate the MSA? How are you doing that? I guess what I'm interested to know is how many times did you have to sign in to see the 3 "rhill@gre..." accounts.

**Comment by chillryan** [comment]
I depends on which rhill@gre.. I remove. When I remove one, I can't access our azure resources (see the second shot; you'll notice that there is no chevron), it will popup but not display anything. If I remove the other, Azure Storage Explorer is happy but VS says invalid token to access VSTS and prompts me to sign in again. Doing so duplicates the MSA account. My O365 account doesn't have any VSTS or Azure subscriptions tied to.

**Comment by MRayermannMSFT** [comment]
Ok, it sounds like VS and Storage Explorer are causing issues for each other. While I try to figure out how I can get my VS into the same state, can you do the following?

1. Close Storage Explorer and VS
2. Go to %temp%\servicehub\logs
3. Clear the folder, leave file explorer open
4. Launch Storage Explorer and VS, remove the account that causes VS to need reauthentication. Once you see VS asking for reauth, sign back in, and then close the programs
5. Go back to the logs, give them a quick look and remove any personal information you don't want other people to see
6. Zip up the files and add them to this issue

Also, I'm pretty sure you're not blocked (just an annoying state), but if you are, you can download the previous version here: https://go.microsoft.com/fwlink/?LinkId=809306&clcid=0x409 (though I would appreciate the logs before you downgrade :) ).

**Comment by chillryan** [comment]
Will do, and yeah it's annoying at most. I tried all kinds of scenarios. Removing accounts from Storage Explorer, adding through storage explorer and vice versa. I'll post the logs as soon as I can.

**Comment by chillryan** [comment]
@MRayermannMSFT not much going on in the logs

[StorageServiceClient-hubControllerLookup-15464-j3mcmudn-1.log](https://github.com/Microsoft/AzureStorageExplorer/files/1955109/StorageServiceClient-hubControllerLookup-15464-j3mcmudn-1.log)

**Comment by MRayermannMSFT** [comment]
For anyone watching this issue, please be aware that if you are:
- Using Windows
- Your machine is domain joined/your are signing into Windows with your ADFS work account or you have logged in with this work account before
It is possible that you will not receive 2 factor authentication or even your password. This capability comes from our new auth library.

Basically, with our new auth library, once you enter your username, a request goes to your company's ADFS server. If your Windows account/machine is linked with this account, then the server knows who are, and thus doesn't ask you for a password or to authenticate.

**Comment by MRayermannMSFT** [comment]
Closing this as no one has replied to it in a while. If you continue to have issues, please open a new one describing your situation. Thanks!
