### ISSUE TITLE
cannot expand any storage account for China but Global in new version 1.4.2

### ISSUE THREAD

**Issue by xudgenler** [Microsoft/AzureStorageExplorer#720]
**Storage Explorer Version**: 1.4.2
**Platform/OS Version**: Win10
**Architecture**: 
**Regression From**: 

#### Steps to Reproduce: ####
1. 
2.

**Comment by jinglouMSFT** [comment]
This is a dup of #696.  There is a workaround listed in #696.

**Comment by mchenx** [comment]
same issue...
