### ISSUE TITLE
Items on the root still display if typing '/' then pressing 'Enter' on the address bar for one ADLS Gen2 blob container/file share

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7201]
**Storage Explorer Version**: 1.31.0
**Build Number**: 20230820.1
**Branch**: hotfix/1.31.1
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Type '/' on the address bar -> Press 'Enter'.
4. Check no item displays on the editor.

## Expected Experience ##
No item displays on the editor.

## Actual Experience ##
The blob displays on the editor.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/4901c064-47bc-4eb2-8bd1-dcba2986028c)

## Additional Context ##
Here is the screenshot for file shares.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/e54141b2-1d8d-47ee-ac28-5607af1c17ce)

**Comment by JasonYeMSFT** [comment]
The service dropping the / characters our specified prefix so there is no way we can fix this problem. Empty name directories are invalid anway. We are going to won't fix this issue.
