### ISSUE TITLE
Unable to retrieve child resources from storage account file shares

### ISSUE THREAD

**Issue by JoseManuelSITA** [microsoft/AzureStorageExplorer#7202]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.31.0(92)

### Architecture

x64

### Storage Explorer Build Number

20230810.9

### Platform

Windows

### OS Version

Windows 10

### Bug Description

When I try to browse File Shares data:

ProducerError:{
  "name": "RestError",
  "message": "This request is not authorized to perform this operation.\nRequestId:49f84937-501a-0017-762c-d4ccca000000\nTime:2023-08-21T12:40:28.7173480Z",
  "stack": "RestError: This request is not authorized to perform this operation.\nRequestId:49f84937-501a-0017-762c-d4ccca000000\nTime:2023-08-21T12:40:28.7173480Z\n    at handleErrorResponse (C:\\Users\\Jose_Manuel.Alvavez\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\file-extension\\dist\\src\\index.js:2:167920)\n    at C:\\Users\\Jose_Manuel.Alvavez\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\file-extension\\dist\\src\\index.js:2:168604\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async StorageRetryPolicy.attemptSendRequest (C:\\Users\\Jose_Manuel.Alvavez\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\file-extension\\dist\\src\\index.js:2:390472)\n    at async StorageClientContext.sendOperationRequest (C:\\Users\\Jose_Manuel.Alvavez\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\file-extension\\dist\\src\\index.js:2:206653)\n    at async ShareServiceClient.listSharesSegment (C:\\Users\\Jose_Manuel.Alvavez\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\file-extension\\dist\\src\\index.js:2:460873)",
  "code": "AuthorizationFailure",
  "statusCode": 403,

### Steps to Reproduce

1. Launch Storage Explorer
2. Expand Subscription
3. Expand Storage Account
4. Expand File Share
5. ERROR

### Actual Experience

I'm not able to browse File Share data with user already logged in.

### Expected Experience

I expect to see File Share data in Storage Explorer right panel.

**Comment by JoseManuelSITA** [comment]
Sorry, the issue was related with network connectivity.

**Comment by rjgentile** [comment]
I am still getting this error and don't know how to resolve it. I have uninstalled the application and deleted the app folder from my local profile. After re-install, the error still exists:
Unable to retrieve child resources

ProducerError:{
  "message": "{}"
}
