### ISSUE TITLE
Warnings to other users who try to edit what I'm accessing

### ISSUE THREAD

**Issue by kylejohnstonGV** [microsoft/AzureStorageExplorer#7208]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I wish there was a warning to other users who try to manipulate a file while I'm downloading it. I was downloading a file for a few hours and someone else changed it's location which cancelled my download

### Desired Solution

Create a pop-up to warn the other user before they change the file I'm accessing. The popup should also inform the other user who it is that is accessing the file so that they can contact them

**Comment by MRayermannMSFT** [comment]
Hi @kylejohnstonGV , this type of feature is 99.9% probably out of scope of Storage Explorer. Azure storage is a lower level storage service. A feature like you are describing would likely be built into a service which itself is built ontop of Azure storage, like OneDrive for example. Does that make sense?

That said, one thing you could try to do is leasing your blobs/files before working on them, and making sure other people working in your storage resources understand that if a blob/file is leased then someone is working on it.

**Comment by kylejohnstonGV** [comment]
Ok thanks Matt

Kyle Johnston
Geospatial Specialist
GeoVerra
C : 403-875-5842

________________________________
