### ISSUE TITLE
Unable to create-blob-container with docker-azurite

### ISSUE THREAD

**Issue by snalli** [microsoft/AzureStorageExplorer#7209]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.31.0

### Architecture

arm64

### Storage Explorer Build Number

20230810.9 

### Platform

macOS

### OS Version

Ventura 13.5.1 (22G90)

### Bug Description

Unable to create blob container using azurite with the explorer. see steps to repro

### Steps to Reproduce

1. docker run --name azurite \
	--publish 127.0.0.1:10000:10000 \
	--volume /Users/snalli/projects/azurite:/home/host \
	--rm --tty \
	mcr.microsoft.com/azure-storage/azurite \
	azurite \
	--location /home/host \
	--debug /home/host/azure.log

2. Launch explorer and connect to docker
3. Try to create blob container and fails

### Actual Experience

Unable to retrieve child resources

ProducerError:{
  "name": "Node Fetch Error",
  "message": "other side closed",
  "stack": "SocketError: other side closed\n    at Socket.onSocketEnd (/private/var/folders/t9/y_8rpmdd1d3fdbmcw9vrc29r0021m4/T/AppTranslocation/C324C0A0-09E9-4947-BF68-58B21C17BFE5/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/undici/lib/client.js:995:22)\n    at Socket.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1359:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
  "cause": {
    "cause": {
      "name": "SocketError",
      "code": "UND_ERR_SOCKET",
      "socket": {
        "localAddress": "127.0.0.1",
        "localPort": 53179,
        "remoteAddress": "127.0.0.1",
        "remotePort": 10000,
        "remoteFamily": "IPv4",
        "bytesWritten": 555,
        "bytesRead": 0
      }
    }
  },
  "code": "UND_ERR_SOCKET"
}

### Expected Experience

Expected to create container

**Comment by snalli** [comment]
Docker container is running 

```
docker run --name azurite \
        --publish 127.0.0.1:10000:10000 \
        --volume /Users/snalli/projects/azurite:/home/host \
        --rm --tty \
        mcr.microsoft.com/azure-storage/azurite \
        azurite \
        --location /home/host \
        --debug /home/host/azure.log
Azurite Blob service is starting at http://127.0.0.1:10000
Azurite Blob service is successfully listening at http://127.0.0.1:10000
Azurite Queue service is starting at http://127.0.0.1:10001
Azurite Queue service is successfully listening at http://127.0.0.1:10001
Azurite Table service is starting at http://127.0.0.1:10002
Azurite Table service is successfully listening at http://127.0.0.1:10002
```

**Comment by snalli** [comment]
Azurite is also running inside the container
```
tail -f azure.log
2023-08-22T21:21:15.802Z         info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-08-22T21:21:15.802Z         info: QueueGCManager:markSweepLoop() Start new mark and sweep.
2023-08-22T21:21:15.802Z         info: QueueGCManger:markSweep() Get all extents.
2023-08-22T21:21:15.803Z         info: QueueGCManager:marksweep() Get 0 extents.
2023-08-22T21:21:15.803Z         info: QueueGCManager:markSweep() Get referred extents, then remove from allExtents.
2023-08-22T21:21:15.803Z         info: QueueGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2023-08-22T21:21:15.803Z         info: QueueGCManager:markSweepLoop() Mark and sweep finished, take 1ms.
2023-08-22T21:21:15.803Z         info: QueueGCManager:markSweepLoop() Sleep for 60000
2023-08-22T21:21:15.803Z         info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-08-22T21:21:15.804Z         info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.

```

**Comment by snalli** [comment]
Here are the port mappings of the container 
```
➜  azurite docker exec -it azurite ps
PID   USER     TIME  COMMAND
    1 root      0:00 node /usr/local/bin/azurite --location /home/host --debug
   54 root      0:00 ps
➜  azurite docker port azurite
10000/tcp -> 127.0.0.1:10000
```

**Comment by snalli** [comment]
```
Unable to retrieve child resources

ProducerError:{
  "name": "Node Fetch Error",
  "message": "other side closed",
  "stack": "SocketError: other side closed\n    at Socket.onSocketEnd (/private/var/folders/t9/y_8rpmdd1d3fdbmcw9vrc29r0021m4/T/AppTranslocation/C324C0A0-09E9-4947-BF68-58B21C17BFE5/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/undici/lib/client.js:995:22)\n    at Socket.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1359:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
  "cause": {
    "cause": {
      "name": "SocketError",
      "code": "UND_ERR_SOCKET",
      "socket": {
        "localAddress": "127.0.0.1",
        "localPort": 54133,
        "remoteAddress": "127.0.0.1",
        "remotePort": 10000,
        "remoteFamily": "IPv4",
        "bytesWritten": 555,
        "bytesRead": 0
      }
    }
  },
  "code": "UND_ERR_SOCKET"
}
```

**Comment by MRayermannMSFT** [comment]
@snalli can you try reaching azurite from a non-Docker instance terminal, ex:

For example, I can use telnet:
```
> brew install telnet
> telnet 127.0.0.1 10000
```

And then I get the output:
```
Trying 127.0.0.1...
Connected to localhost.
```
?

**Comment by snalli** [comment]
```
telnet 127.0.0.1 10000
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.
```

Azurite is running in docker. I could not install it using npm due to dependency hell. Docker is easier to install.
However, I am trying telnet outside of Docker from my mac and the output is shown above.

**Comment by snalli** [comment]
@MRayermannMSFT I am from Microsoft too. Can I talk to someone over teams and do a screen-share to move things along faster ?

**Comment by MRayermannMSFT** [comment]
Mitigated by not using docker.

**Comment by jooooel** [comment]
What options do I have if I want to use Docker? 🙁 I'm running into the same issue...

**Comment by ga-efmanuella** [comment]
> Mitigated by not using docker.

I *believe* ran into this same issue. Is there a fix aside from the mitigation?
"don't use docker" in my case translates to "don't use azure storage explorer"

**Comment by twanvanderpoel** [comment]
In my setup the binary was listening on localhost (`127.0.0.1`). You might need to start the binary and specify it to listen to all incoming ipv4 connections (rather than *localhost*). Can you try running Azurite like this?

```
azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0
```

Afterwards you should have a non-closing connection on your host towards the exposed container-port;

```
telnet localhost 10000
```

**Comment by ga-efmanuella** [comment]
Thanks, this was the issue for me. Working as expected. 👍
