### ISSUE TITLE
Azure Explore Authentication Error blob not visible after successful login

### ISSUE THREAD

**Issue by superrisusan** [microsoft/AzureStorageExplorer#7211]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.31.1

### Architecture

x64

### Storage Explorer Build Number

20230822.1

### Platform

Windows

### OS Version

Windows 10 Enterprise

### Bug Description

This request is not authorized to perform this operation.

This storage account's 'Firewalls & virtual networks' settings may be blocking access to storage services. Try adding your client IP address to the firewall exceptions, or by allowing access from 'all networks' instead of 'selected networks'. To learn more about Azure Storage firewalls and virtual networks, visit http://go.microsoft.com/fwlink/?LinkId=845443.

Error Details:
{
  "name": "RestError",
  "code": "AuthorizationFailure",
  "statusCode": 403,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://nebuscentrdatprddls001.blob.core.windows.net/?comp=list&include=metadata",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2021-10-04"
        },
        "accept": {
          "name": "Accept",
          "value": "application/xml"
        },
        "user-agent": {
          "name": "User-Agent",
          "value": "Microsoft Azure Storage Explorer/1.31.1 (win32) azsdk-js-storageblob/12.12.0 (NODE-VERSION v18.15.0; Windows_NT 10.0.19045)"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "b928d9d0-7ec1-4e27-82ad-f3a07e895706"
        },
        "authorization": {
          "name": "authorization",
          "value": "Bearer JSON Web Token Redacted"
        }
      }
    },
    "withCredentials": false,
    "timeout": 0,
    "keepAlive": true,
    "decompressResponse": false,
    "requestId": "b928d9d0-7ec1-4e27-82ad-f3a07e895706"
  },
  "response": {
    "request": {
      "streamResponseStatusCodes": {},
      "url": "https://nebuscentrdatprddls001.blob.core.windows.net/?comp=list&include=metadata",
      "method": "GET",
      "headers": {
        "_headersMap": {
          "x-ms-version": {
            "name": "x-ms-version",
            "value": "2021-10-04"
          },
          "accept": {
            "name": "Accept",
            "value": "application/xml"
          },
          "user-agent": {
            "name": "User-Agent",
            "value": "Microsoft Azure Storage Explorer/1.31.1 (win32) azsdk-js-storageblob/12.12.0 (NODE-VERSION v18.15.0; Windows_NT 10.0.19045)"
          },
          "x-ms-client-request-id": {
            "name": "x-ms-client-request-id",
            "value": "b928d9d0-7ec1-4e27-82ad-f3a07e895706"
          },
          "authorization": {
            "name": "authorization",
            "value": "Bearer JSON Web Token Redacted"
          }
        }
      },
      "withCredentials": false,
      "timeout": 0,
      "keepAlive": true,
      "decompressResponse": false,
      "requestId": "b928d9d0-7ec1-4e27-82ad-f3a07e895706"
    },
    "status": 403,
    "headers": {
      "_headersMap": {
        "content-length": {
          "name": "content-length",
          "value": "246"
        },
        "content-type": {
          "name": "content-type",
          "value": "application/xml"
        },
        "date": {
          "name": "date",
          "value": "Wed, 23 Aug 2023 06:41:24 GMT"
        },
        "server": {
          "name": "server",
          "value": "Microsoft-HTTPAPI/2.0"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "b928d9d0-7ec1-4e27-82ad-f3a07e895706"
        },
        "x-ms-error-code": {
          "name": "x-ms-error-code",
          "value": "AuthorizationFailure"
        },
        "x-ms-request-id": {
          "name": "x-ms-request-id",
          "value": "c4a44a84-f01e-0076-358c-d5059f000000"
        }
      }
    },
    "bodyAsText": "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.\nRequestId:c4a44a84-f01e-0076-358c-d5059f000000\nTime:2023-08-23T06:41:25.0220880Z</Message></Error>",
    "parsedBody": {
      "message": "This request is not authorized to perform this operation.\nRequestId:c4a44a84-f01e-0076-358c-d5059f000000\nTime:2023-08-23T06:41:25.0220880Z",
      "code": "AuthorizationFailure"
    },
    "parsedHeaders": {
      "errorCode": "AuthorizationFailure",
      "content-length": "246",
      "content-type": "application/xml",
      "date": "Wed, 23 Aug 2023 06:41:24 GMT",
      "server": "Microsoft-HTTPAPI/2.0",
      "x-ms-client-request-id": "b928d9d0-7ec1-4e27-82ad-f3a07e895706",
      "x-ms-request-id": "c4a44a84-f01e-0076-358c-d5059f000000"
    }
  },
  "details": {
    "errorCode": "AuthorizationFailure",
    "content-length": "246",
    "content-type": "application/xml",
    "date": "Wed, 23 Aug 2023 06:41:24 GMT",
    "server": "Microsoft-HTTPAPI/2.0",
    "x-ms-client-request-id": "b928d9d0-7ec1-4e27-82ad-f3a07e895706",
    "x-ms-request-id": "c4a44a84-f01e-0076-358c-d5059f000000",
    "message": "This request is not authorized to perform this operation.\nRequestId:c4a44a84-f01e-0076-358c-d5059f000000\nTime:2023-08-23T06:41:25.0220880Z",
    "code": "AuthorizationFailure"
  }
}

### Steps to Reproduce

1. Launch Azure Storage Explore
2. Login by selecting Subscrion > Azure
3. Login via Web Browser
4. Successful Login in Web Browser
5. Login detected in Azure Storage Explore
6. Goes to Blog but empty and getting this error.

### Actual Experience

1. Launch Azure Storage Explore
2. Login by selecting Subscrion > Azure
3. Login via Web Browser
4. Successful Login in Web Browser
5. Login detected in Azure Storage Explore
6. Goes to Blog but empty and getting this error.

### Expected Experience

1. Launch Azure Storage Explore
2. Login by selecting Subscrion > Azure
3. Login via Web Browser
4. Successful Login in Web Browser
5. Login detected in Azure Storage Explore
6. Goes to Blog and not empty but available two entries 
     1) copy activity logs
     2) sapcrmcasehist

**Comment by JasonYeMSFT** [comment]
@superrisusan Have you tried modifying your firewall settings as suggested by the error message?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of reponse. This issue will no longer be actively monitored. If you still need help, we recommend reaching out to Azure support, via openeng a ticket in the Azure portal. Alternatively you can open a new issue here.
