### ISSUE TITLE
Items do not disappear if typing its parent folder's name append with '//' on the search by prefix for ADLS Gen2 blob containers/file shares

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7212]
**Storage Explorer Version**: 1.32.0-dev (93)
**Build Number**: 20230823.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Create a new folder 'f1' -> Upload two blobs to the folder.
3. Soft delete one blob -> Switch to the view 'Active and soft deleted blobs'.
4. Go back to root -> Type 'f1//' on the search by prefix box.
5. Check whether the items disappear.

## Expected Experience ##
The items disappear.

## Actual Experience ##
The items do not disappear.

## Additional Context ##
1. Only the soft deleted blob disappears after typing 'f1///' on the search by prefix box.
2. Switch to 'Deleted only' view, show two '//' in the full name of the soft deleted blob when typing 'f1//' on the search by prefix box.  As below:
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/31a551e5-da50-4207-a80c-f5cc17859190)

3. Here is the record:
![0823](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/27fa1d15-9fd8-4600-8226-7b8773b83ac6)
4. For file shares, the items do not disappear if typing '//' next to the folder name. the items disappear if typing '///' next to the folder name.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/7b56f33a-4155-44ef-b835-1f8c1531032b)

**Comment by JasonYeMSFT** [comment]
Those names actually come from the blob service lol. We will let the service team know about it and won't fix this issue since such prefixes are invalid in Gen2 and file share.
