### ISSUE TITLE
Show extra '...' for actions 'Open/Delete/Break Lease' against blob containers in the view opened by clicking 'View all'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7218]
**Storage Explorer Version**: 1.32.0-dev (93)
**Build Number**: 20230825.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch storage explorer -> Open 'Settings' -> Select 'Services'.
2. Set the setting 'Storage Nodes Trailing Action' to 'View all'.
3. Refresh the tree view -> Expand one storage account -> Blob Containers.
4. Click 'View all' in the tree view -> There is a separate view.
5. Right click one blob container in the view -> Observe the context menu.
6. Check whether no extra '...' for actions 'Open/Delete/Break Lease'.

## Expected Experience ##
No extra '...' for actions 'Open/Delete/Break Lease'.

## Actual Experience ##
Show extra '...' for actions 'Open/Delete/Break Lease'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/1df3f631-c815-4cb0-9f0f-e06cf74a0bb9)

**Comment by MRayermannMSFT** [comment]
- Removed "..." from delete in blob container explorer to match blob explorer and blob container node
- Removed "..." from open in blob container explorer to match blob explorer and blob container node
- Added "..." to break lease on blob container node to match blob explorer and blob container explorer

**Comment by v-xianya** [comment]
@MRayermannMSFT 
According to action on the break lease dialog. It doesn't make sense to add '...' next to break lease action against one blob container node. Could you help to double confirm this?
Break lease for a blob container. show below dialog:
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/ac434bb2-024c-4c7e-ab8a-e73f8a65bb6b)
Break lease for a blob. show below dialog:
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/4365aec6-82d4-4200-95a1-bcb30886841e)

**Comment by MRayermannMSFT** [comment]
@v-xianya yes, we're going to be going through our menus in December to make sure we're being more consisent on our usage of ..., for now though, please just make sure individual actions are consistent across context menus.
