### ISSUE TITLE
Possibility to use wildcards for search in blob storage

### ISSUE THREAD

**Issue by olgakorichkovskaya** [microsoft/AzureStorageExplorer#722]
**Storage Explorer Version**: 1.4.2
**Platform/OS Version**: Windows 10 Enterprise
**Architecture**: ia32
**Regression From**: n/a

#### Feature request ####
Possibility to use wildcard for search in blob storage.
E.g.
Files:
abce.txt
abde.txt
aaae.txt
..
Search: sb*e.txt

#### Actual Experience: ####
No possilility to use wildcards in search.

![image](https://user-images.githubusercontent.com/3368477/46282186-23f47600-c571-11e8-9d09-436ddca3bd91.png)

**Comment by niklasinde** [comment]
Interested in this to!

**Comment by lucidltd** [comment]
would make ASE much more fun to use.

**Comment by craxal** [comment]
We are using #1667 to track this issue. Please continue the discussion there.
