### ISSUE TITLE
Can't see "View all" action when selecting it under High Contrast - Black/White theme

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7224]
**Storage Explorer Version:** 1.32.0-dev (93)
**Build Number:** 20230827.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture:** x64/x64/x64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Launch storage explorer -> Change the theme to 'High Contrast - Black'.
2. Open 'Settings' -> Select 'Services'.
3. Set the setting 'Storage Nodes Trailing Action' to "View all".
4. Refresh the tree view -> Expand one storage account -> Blob Containers.
5. Click "View all" in the tree view.
6. Check whether "View all" action is visible.

## Expected Experience ##
"View all" action is visible.

The screenshot under Dark theme:
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/8c412e8e-a3a5-4484-814d-6fa0dc51e0a8)

## Actual Experience ##
Can't see "View all" action.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/37b6ec81-85ea-434a-b07f-e8ca404b6cb7)

## Additional Context ##
This issue doesn't reproduce when hovering over "View all" action.

**Comment by v-kellyluo** [comment]
@MRayermannMSFT, verified this issue on the build 20230901.1 it still reproduces under High Contrast - White theme. So, we are going to re-open it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/08e52059-abc3-4bcc-bcda-ac610bff51b4)

**Comment by MRayermannMSFT** [comment]
Updated stylings to address things I missed. :)

![image](https://github.com/microsoft/AzureStorageExplorer/assets/21112697/7ec68a9b-9d09-4f6f-81b0-5a005fde9a0b)

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230904.1. Fixed.
