### ISSUE TITLE
The toolbar items on view all containers explorer show as regular size when setting the toolbar size to 'small'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7225]
**Storage Explorer Version**: 1.32.0-dev (93)
**Build Number**: 20230827.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch storage explorer -> Open 'Settings' -> Select 'Data Explorers' -> Set 'Toolbar Size' to 'Small'.
2. Select 'Services' -> Set the setting 'Storage Nodes Trailing Action' to 'View all'.
4. Refresh the tree view -> Expand one storage account -> Blob Containers.
5. Click 'View all' in the tree view -> There is a separate view.
6. Check whether the toolbar items show as small size.

## Expected Experience ##
The toolbar items show as small size.

## Actual Experience ##
The toolbar items show as regular size.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230901.1. Fixed.
