### ISSUE TITLE
Filter by prefix doesn't take effect on view all containers explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7226]
**Storage Explorer Version**: 1.32.0-dev (93)
**Build Number**: 20230827.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch storage explorer -> Open 'Settings' -> Select 'Services'.
2. Set the setting 'Storage Nodes Trailing Action' to 'View all'.
4. Refresh the tree view -> Expand one storage account -> Blob Containers.
5. Click 'View all' in the tree view -> There is a separate view.
6. Type a prefix to the filter by prefix box.
7. Check whether the unmatched items disappear.

## Expected Experience ##
The unmatched items disappear.

## Actual Experience ##
The unmatched items do not disappear.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/3f8ca5e7-6f38-4699-b9c1-5bfc2eb723b7)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230901.1. Fixed.
