### ISSUE TITLE
The search icon doesn't disappear after executing filter by prefix on view all containers explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7227]
**Storage Explorer Version**: 1.32.0-dev (93)
**Build Number**: 20230827.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch storage explorer -> Open 'Settings' -> Select 'Services'.
2. Set the setting 'Storage Nodes Trailing Action' to 'View all'.
3. Refresh the tree view -> Expand one storage account -> Blob Containers.
4. Click 'View all' in the tree view -> There is a separate view.
5. Type a prefix to the filter by prefix box.
6. Check whether the search icon disappears.

## Expected Experience ##
The search icon disappears.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/fb42dff3-3a84-4be4-bdfa-30ff3693572b)

## Actual Experience ##
The search icon doesn't disappear.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/397a707c-0c0c-4a89-94d7-257f3bc4c722)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230901.1. Fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/df621eec-86e4-493a-80d1-ff994ef3154f)
