### ISSUE TITLE
"Unable to retrieve child resources" even after changing proxy settings

### ISSUE THREAD

**Issue by nikhilabb** [microsoft/AzureStorageExplorer#7231]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.31.1 (93)

### Architecture

x64

### Storage Explorer Build Number

20230822.1

### Platform

Windows

### OS Version

Windows 10 Enterprise 21H2

### Bug Description

Unable to retrieve child resources

ProducerError:{
  "name": "Electron Net Error",
  "message": "net::ERR_TUNNEL_CONNECTION_FAILED",
  "stack": "Error: net::ERR_TUNNEL_CONNECTION_FAILED\n    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49935)\n    at SimpleURLLoaderWrapper.emit (node:events:513:28)",
  "cause": {}
}

### Steps to Reproduce

1. Open Storage Explorer
2. Click on the explorer icon
3. Open the 'Emulator & Attached' drop down box
4. Under the storage account, open 'File share'

### Actual Experience

When I try to access the 'File Share' option using system proxy settings, it loads for a few seconds and throws the error message as shown below:

![image](https://github.com/microsoft/AzureStorageExplorer/assets/143417410/61ce71e0-584e-42c1-9e39-40365d1769cc)

**Comment by MRayermannMSFT** [comment]
Can you please try accessing, via the Azure portal, on the same machine, the same storage resources you are attempting to access, and let us know if that works? If access by via the Azure portal does work, then please if possible share screenshots showing a side by side view of portal working and Storage Explorer not working, such that we can see you did in fact access the same resources.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response from original author. This issue will no longer be monitored. If you still require help, we recommend opening an Azure support ticket via the Azure portal.
