### ISSUE TITLE
The layout of the view's menu is not left aligned

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7233]
**Storage Explorer Version**: 1.32.0-dev (93)
**Build Number**: 20230829.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch storage explorer -> Click 'View'.
2. Observe the layout the menu.
3. Check whether it is left aligned.

## Expected Experience ##
It is left aligned.

## Actual Experience ##
It is not left aligned.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/a37e4d88-9f8b-40c4-8364-3b7c5c842030)

## Additional Context ##
Here is the screenshot of the 'Edit' menu.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/b34f731c-67c9-4101-a0cd-9064c8add51b)

**Comment by craxal** [comment]
This is not a bug. This is a visual change as a result of upgrading Electron. The alignment is still correct, but the menu padding was reduced. See electron/electron#39611.
