### ISSUE TITLE
There is an extra scrollbar in the emulator notification dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7234]
**Storage Explorer Version**: 1.32.0-dev (93)
**Build Number**: 20230829.2
**Branch**: main
**Platform/OS**: Windows 10
**Language**: Czech /Deutsch/Spanish/ French/Italian/Japanese/Dutch/Polish/Portuguese(Brazil)/Portuguese(Portugal) /Russian/Swedish/Turkish  
**Architecture**: x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select 'Español' -> Restart Storage Explorer.
3.  Make sure the Azurite is not installed or running.
4. Expand 'Emulator & Attached -> Storage Accounts' -> (Emulator - Default Ports) (Key).
5. There is a notification dialog.
6. Check there is no extra scrollbar in the dialog.

## Expected Experience ##
There is no extra scrollbar in the dialog.

## Actual Experience ##
There is an extra scrollbar in the dialog.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/7a659ee2-6e5d-4253-8d52-deba9983ab6b)

## Additional Context ##
This issue doesn't reproduce on Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro).

**Comment by craxal** [comment]
This should be fixed now that #1420 is resolved.

**Comment by v-xianya** [comment]
Hi @craxal Verified this issue on the main build 20230908.4. Reproduce. So, we are going to reopen it.

**Comment by craxal** [comment]
The necessary change might not have made it in to the build you tested. Please verify again.

**Comment by v-xianya** [comment]
Hi @craxal Verified this issue on the main build 20230914.4. Reproduce.
Will verify it on a newer build.
