### ISSUE TITLE
The string 'true' is localized in the Value field for one Boolean property

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7235]
**Storage Explorer Version:** 1.32.0-dev (93)
**Build Number:** 20230829.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Language:** Spanish/Polish/Portuguese (Brazil)/Swedish
**Architecture:** x64/x64/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.25.1)
## Steps to Reproduce ##

1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select 'Español' -> Restart Storage Explorer.
3. Expand one storage account -> Tables.
4. Create a table -> Click 'Add -> Add Property'.
5. Input a valid property name -> Select Boolean type -> Observe the Value field.
6. Check whether the string 'true' is not localized.

## Expected Experience ##
The string 'true' is not localized.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/bfe7237e-8233-457d-8dff-ea9ac94a87d9)

## Actual Experience ##
The string 'true' is localized.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/1c8c6632-ae85-4599-9a5f-dc2dc0218ac6)

**Comment by craxal** [comment]
Required localization team to correct. Work item has been created to track: https://ceapex.visualstudio.com/CEINTL/_workitems/edit/901567
