### ISSUE TITLE
cannot access blob container

### ISSUE THREAD

**Issue by maheshkharvidxc** [microsoft/AzureStorageExplorer#7236]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.0

### Regression From

1.18.0

### Architecture

i86

### Platform

Windows

### OS Version

Windows

### Bug Description

Unable to retrieve child resources

ProducerError:{
  "name": "Node Fetch Error",
  "message": "getaddrinfo ENOTFOUND https",
  "stack": "Error: getaddrinfo ENOTFOUND https\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)",
  "cause": {
    "cause": {
      "errno": -3008,
      "code": "ENOTFOUND",
      "syscall": "getaddrinfo",
      "hostname": "https"
    }
  },
  "code": "ENOTFOUND",
  "errno": -3008
}

### Steps to Reproduce

lauch explorer
click on the containers

### Actual Experience

Unable to retrieve child resources

ProducerError:{
  "name": "Node Fetch Error",
  "message": "getaddrinfo ENOTFOUND https",
  "stack": "Error: getaddrinfo ENOTFOUND https\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)",
  "cause": {
    "cause": {
      "errno": -3008,
      "code": "ENOTFOUND",
      "syscall": "getaddrinfo",
      "hostname": "https"
    }
  },
  "code": "ENOTFOUND",
  "errno": -3008
}

### Expected Experience

Unable to retrieve child resources

ProducerError:{
  "name": "Node Fetch Error",
  "message": "getaddrinfo ENOTFOUND https",
  "stack": "Error: getaddrinfo ENOTFOUND https\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)",
  "cause": {
    "cause": {
      "errno": -3008,
      "code": "ENOTFOUND",
      "syscall": "getaddrinfo",
      "hostname": "https"
    }
  },
  "code": "ENOTFOUND",
  "errno": -3008
}

### Additional Context

Unable to retrieve child resources

ProducerError:{
  "name": "Node Fetch Error",
  "message": "getaddrinfo ENOTFOUND https",
  "stack": "Error: getaddrinfo ENOTFOUND https\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)",
  "cause": {
    "cause": {
      "errno": -3008,
      "code": "ENOTFOUND",
      "syscall": "getaddrinfo",
      "hostname": "https"
    }
  },
  "code": "ENOTFOUND",
  "errno": -3008
}

**Comment by JasonYeMSFT** [comment]
@maheshkharvidxc We have stopped supporting 1.19.0 since it's out of our [support lifecycle](https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-support-policy-lifecycle#releases). I recommend you to upgrade to the latest version if that's possible. Your error indicates you are trying to resolve the ip address of hostname "https", which obviously cannot be found. Could you check if you entered an incorrect url by mistake?
