### ISSUE TITLE
An extra '/' displays next to the folder name in the delete dialog when deleting a folder

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7237]
**Storage Explorer Version:** 1.32.0-dev (93)
**Build Number:** 20230830.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture:** x64/x64/arm64
**How Found:** From running test cases
**Regression From:** Previous release (1.30.2)

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload a folder.
3. Click 'Delete' -> There is a delete dialog.
4. Check whether no extra '/' displays next to the folder name.

## Expected Experience ##
No extra '/' displays next to the folder name.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/630fad85-cf0d-4916-9edb-29f818b42845)

## Actual Experience ##
An extra '/' displays next to the folder name.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/820c596f-f62e-4ab6-8526-c79bf54f0298)

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230831.2. Fixed. So, we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/0d13c952-8abd-4afd-a31e-53bd333f793f)
