### ISSUE TITLE
error previewing parquet file: invalid schema for type: DECIMAL, can not handle precision over 18

### ISSUE THREAD

**Issue by jasonhorner** [microsoft/AzureStorageExplorer#7240]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.31.1

### Architecture

x64

### Storage Explorer Build Number

20230822.1

### Platform

All

### Bug Description

when trying to preview a parquet. I encounter this error:

{
  "name": null,
  "message": "\"invalid schema for type: DECIMAL, for Column: **MyColumn**, can not handle precision over 18\""
}

the column MyColumn data type is money in the underlying sql server database. the parquet file was generated from the ADF Copy activity the parquet file seems valid.

As a side note while there is an error shown in the activities tab. the preview u/i shows the message "No Data" this is potentially misleading and I feel like it should say something like "Error Encountered" as no data implies at least to me that the file was empty.

here is a screenshot for context:
![image](https://github.com/microsoft/AzureStorageExplorer/assets/7981510/57af5cbb-197a-4f7b-998a-9af4075bd7f4)

### Steps to Reproduce

See Above

### Actual Experience

see Above

**Comment by JasonYeMSFT** [comment]
This is currently not supported. We will semi-support it in 1.32.0 by unblocking parsing when there are decimal fields whose underlying representation cannot be easily parsed (e.g. fixed length byte array, non-fixed length byte array) whose precision may be beyond 18.

**Comment by jasonhorner** [comment]
@JasonYeMSFT not sure how I missed this issue last night... I did look. I do think the error messaging visibility in the preview window could be improved. Hope you will consider this for a future build. the preview features especially for parquet and Avro have been very useful.
