### ISSUE TITLE
Storage explorer is not listing Azure accounts and some containers within it 

### ISSUE THREAD

**Issue by Bhupendra-Aithani** [microsoft/AzureStorageExplorer#7244]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.31.0

### Architecture

x64

### Platform

All

### OS Version

Windows 10

### Bug Description

Not able to view all the storage accounts and the containers within in it.

### Steps to Reproduce

Launch stroage explorer 
login 
then not able to list the storage account, some time after re loign in again it  show storage account but soent show the containers

### Actual Experience

then not able to list the storage account, some time after re loign in again it  show storage account but soent show the containers

### Additional Context

Unable to retrieve child resources

ProducerError:{
  "name": "Node Fetch Error",
  "message": "{\"name\":\"Node Fetch Error\",\"cause\":{\"cause\":{\"errno\":-3008,\"code\":\"ENOTFOUND\",\"syscall\":\"getaddrinfo\",\"hostname\":\"management.azure.com\"}},\"code\":\"ENOTFOUND\",\"errno\":-3008}"
}

**Comment by craxal** [comment]
@Bhupendra-Aithani We recently released a patch update (v1.31.1). If you upgrade to that version, do you still encounter this issue?

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. If you still encounter this issue, please provide the additional information we requested and re-open this.
