### ISSUE TITLE
There is an extra '…' next to the tooltip of the action 'Manage ACLs' on the toolbar in the new blob explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7246]
**Storage Explorer Version**: 1.32.0-dev (93)
**Build Number**: 20230904.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running testing
**Regression From**: Previous release (1.31.1)

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Right click one blob container -> Click 'Open Gen2 as Blob Explorer (test)'.
3. Hover over the 'Mange ACLs' -> There is a tooltip.
4. Check there is no extra '...' next to the tooltip.

## Expected Experience ##
There is no extra '...' next to the tooltip. 
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/03fe7c26-9029-41fd-8468-bb17f027bf41)

## Actual Experience ##
There is an extra '...' next to the tooltip. 
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/f86762e5-a104-438a-9761-b49e34c13e74)

**Comment by JasonYeMSFT** [comment]
I will make the tooltip say "Manage Access Control Lists". The original string "Manage ACL" is not a good string since it carries no additional information other than what the label has already conveyed.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230906.5. Fixed. So, we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/24dc5046-0423-41ea-acd8-03712c3a399d)
