### ISSUE TITLE
Can't list file shares when signed-in with Azure AD v2

### ISSUE THREAD

**Issue by eskaufel** [microsoft/AzureStorageExplorer#7248]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.1

### Architecture

x64

### Storage Explorer Build Number

20230822.1

### Platform

All

### Bug Description

Error message:

Unable to retrieve child resources

ProducerError:{
  "name": "Error",
  "message": "Unable to perform operation 'FileServiceClient.listSharesSegment'. No suitable credentials provided.",
  "stack": "".....
}

### Steps to Reproduce

1. Launch storage explorer.
2. Sign in with Azure AD Account
3. Expand the subscription
4. Expand the storage account
5. Expand File Shares

### Actual Experience

Error message is shown like you can see in the bug description.

### Expected Experience

Show the files shares the user has permissions for.

### Additional Context

This is a new report for this issue #6451 that ended in "by design". Azure file share does now support authentication with OAuth over HTTP. 

https://techcommunity.microsoft.com/t5/azure-storage-blog/general-availability-introducing-azure-ad-support-for-azure/ba-p/3826733

**Comment by eliaquimbrandao** [comment]
Hello @eskaufel , 

Thank you for sharing your concern. I'm an SME in the Storage area at Azure Support Microsoft. Recently, I spoke with our Program Manager team and learned that Azure Storage Explorer (ASE) still requires the addition of OAuth over REST functionality for Azure Files. While we don't have a precise timeline yet, we anticipate this implementation to take place by the end of Calendar Year 2024.

Today through the Azure Portal, you can benefit from this for your users if you wish, but for ASE forecast only for CY24.

**Comment by MRayermannMSFT** [comment]
This work can be tracked here: https://github.com/microsoft/AzureStorageExplorer/issues/6287

**Comment by eskaufel** [comment]
> This work can be tracked here: #6287

Thank you. This is causing some issues in the application we are using forcing us to maintain dual access lists. I will follow the issue for updates
