### ISSUE TITLE
The 'Clone' dialog pops up when pressing F2 in the new ADLS Gen2 blob explorer

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7249]
**Storage Explorer Version:** 1.32.0-dev (93)
**Build Number:** 20230904.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture:** x64/x64/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.31.1)

## Steps to Reproduce ##

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Right click one blob container -> Click 'Open Gen2 as Blob Explorer (test)'.
3. Select one blob -> Press F2.
4. Check whether the 'Rename' dialog pops up.

## Expected Experience ##
The 'Rename' dialog pops up.

## Actual Experience ##
The 'Clone' dialog pops up.

## Additional Context ##
Related bug: [6591](https://github.com/microsoft/AzureStorageExplorer/issues/6591).

**Comment by v-xianya** [comment]
Verified this issue on the build 20230906.5. Fixed. So, we are going to close it.
