### ISSUE TITLE
There is no error icon when creating a blob container using an invalid name

### ISSUE THREAD

**Issue by v-xinda** [microsoft/AzureStorageExplorer#7251]
**Storage Explorer Version:** 1.32.0-dev (93)
**Build Number:** 20230904.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture:** x64/x64/x64
**How Found:** From running testing
**Regression From:** Previous release (1.31.1)

## Steps to Reproduce ##

1. Expand a storage account -> Blob Containers.
2. Create a blob container using an invalid name "T".
3. Check whether there is an error icon.

## Expected Experience ##
There is an error icon.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/57662131/5647229c-c98c-4860-95b7-a28a9d15a5ba)

## Actual Experience ##
There is no error icon.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/57662131/f6280d5c-ab24-4a26-8487-0a616939bbba)

## Additional Context ##
This issue doesn't reproduce for the file share, queue and table.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230906.5. Fixed.
