### ISSUE TITLE
Nothing happens when clicking 'Manage Versions' action in the new ADLS Gen2 blob explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7253]
**Storage Explorer Version**: 1.32.0-dev (93)
**Build Number**: 20230904.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Right click one blob container -> Click 'Open Gen2 as Blob Explorer (test)'.
3. Upload one blob -> Right click the blob.
4. Click 'Manage History' -> Click 'Manage Versions'.
5. Check whether switches to versions view.

## Expected Experience ##
Switch to versions view.

## Actual Experience ##
Nothing happens.

**Comment by JasonYeMSFT** [comment]
The Manage Versions action should be hidden in Gen2 explorer.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230906.5. 'Manage Versions' has been hidden. So, we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/8a3f67db-5f14-4b74-bee2-ee3349f32fec)
