### ISSUE TITLE
The action 'Open' is enabled for one soft deleted folder in the new ADLS Gen2 blob explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7257]
**Storage Explorer Version**: 1.32.0-dev (93)
**Build Number**: 20230904.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running testing
**Regression From**: Previous release (1.31.1)

## Bug Descriptions ##
Several actions are incorrectly enabled for one soft deleted folder in the new ADLS Gen2 blob explorer.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/2bb3acd2-442e-463c-86cc-5d324f93ef7a)

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Right click one blob container -> Click 'Open Gen2 as Blob Explorer (test)'.
3. Create a folder -> Soft delete the folder.
4. Switch to 'Active and soft deleted blobs' -> Select the soft deleted folder.
5. Check whether the action 'Open' is disabled.

## Expected Experience ##
The action 'Open' is disabled.
## Actual Experience ##
The action 'Open' is enabled.

**Comment by v-kellyluo** [comment]
@JasonYeMSFT ,verified this issue on the build 20230906.5, the 'Propagate Access Control Lists...' action is still enabled for one soft deleted folder.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/3a43351a-81eb-4d9b-93a1-da727783f1d0)

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230908.4. 
The 'Propagate Access Control Lists...' action is disabled for soft delete folder. So, we are going to close it.
