### ISSUE TITLE
'Move' action is disabled for items under one SAS attached ADLS Gen2 blob container (with full permissions)

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7258]
**Storage Explorer Version**: 1.32.0-dev (93)
**Build Number**: 20230904.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running testing
**Regression From**: Previous release (1.31.1)

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Attach the blob container via SAS URL (with full permissions).
3. Right click the attached blob container -> Click 'Open Gen2 as Blob Explorer (test)'.
4. Upload one blob -> Then select the blob.
5. Check whether the move action is enabled.

## Expected Experience ##
The move action is enabled.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/4e19dcd7-d381-4fc5-a860-5961cc84770a)

## Actual Experience ##
The move action is disabled.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/79ed7d37-a034-48f1-8a0e-37ff70393301)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230906.5. Fixed. So, we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/6338dd38-1ff5-4a65-be24-7ed28f32c3de)
