### ISSUE TITLE
The search icon on the filter by prefix box is invisible under 'High Contrast - Black' theme for the new ADLS Gen2 blob explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7259]
**Storage Explorer Version**: 1.32.0-dev (93)
**Build Number**: 20230904.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running testing
**Regression From**: Previous release (1.31.1)

## Steps to Reproduce ##
1. Launch storage explorer -> Set the theme to 'High Contrast - Black'.
2. Expand one ADLS Gen2 storage account -> Blob Containers.
3. Right click one blob container -> Click 'Open Gen2 as Blob Explorer (test)'.
4. Observe the filter by prefix box.
5. Check whether the search icon is visible.

## Expected Experience ##
The search icon is visible.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/1c857624-60b0-4b2f-8540-b5fde4b7686c)

## Actual Experience ##
The search icon is invisible.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/fc66f93d-fea3-40bc-81ca-cd87daddf230)

## Additional Context ##
It is hard to see the search icon under the 'Dark' theme.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/50b0d707-4874-4a74-be44-ad1f3d9f52dc)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230906.5. Fixed. So, we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/e743721f-1bde-48fd-94d4-1181e93d8cc4)
