### ISSUE TITLE
Cannot open connection

### ISSUE THREAD

**Issue by spboyer** [Microsoft/AzureStorageExplorer#726]
Version: 1.4.2

Platform: macOS
Architecture: x64
Build Number: 20180917.1
Commit: f66de7ea
Support Id: d02ab9b4-e6df-b370-42ae-f793c85261ca

### Recreate ###
1. Add Azure Subscription
1. Sign In / Authenticate

After subscriptions are selected and starting to load, repeated dialogs popup with the following message.

The requested action could not be completed.
Details: Cannot read property 'connectionString' of undefined

After clicking OK/Close, and attempting click `Load More` under the CosmosDB or Storage Accounts; the same message is presented.

Product not usable.

**Comment by JeffMushmo** [comment]
#788 Reference to same issue.

**Comment by tbolon** [comment]
Same here.

**Comment by tbolon** [comment]
Same here, with the message "Unable to retrieve child resources.".

Please note that I tried following the [Troubleshooting guide](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting#unable-to-retrieve-children-error-message) without success:

> If you are connected to Azure through a proxy, verify that your proxy settings are correct. If you were granted access to a resource from the owner of the subscription or account, verify that you have read or list permissions for that resource.

This information does not apply to my case.

**Comment by tbolon** [comment]
Finally found a simple way to fix the problem: delete the `%appdata%\StorageExplorer` folder, then restart the app.

**Comment by spboyer** [comment]
Delete folder per OS here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting#cannot-remove-attached-account-or-storage-resource

For Mac / Linux, you need to also remove  Microsoft.Developer.IdentityService entry from your OS' keystore. Restart App and r-authenticate. Solves issues.

Appears to be a local cache issue.

Close #788 as duplicate.
