### ISSUE TITLE
import queue messages from a file

### ISSUE THREAD

**Issue by bobmeyers5** [Microsoft/AzureStorageExplorer#7261]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I need to post a large number of messages to a storage queue for background processing. The messages have been generated and stored in a file as an array of JSON objects. They could also be formatted as CSV.

### Desired Solution

I'd like to see an import feature similar to Table Import, but for posting queue messages.

**Comment by richardMSFT** [comment]
@bobmeyers5 Can you share a bit more of what you expect the json or csv file used to store and import messages would look like? Do you have a strong preference for whether to import from a JSON or CSV file?
