### ISSUE TITLE
It is better to use 'Paste copied items' instead of 'Paste selected items' as the tooltip of 'Paste' on the toolbar

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7264]
**Storage Explorer Version**: 1.32.0-dev (93)
**Build Number**: 20230906.9
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Open one blob container.
3. Hove over the 'Paste' button on the toolbar.
4. Check whether the tooltip is accurate. 

## Expected Experience ##
The tooltip is accurate. 

## Actual Experience ##
1. The tooltip is inaccurate.
2. It is better to show 'Paste copied items' instead of 'Paste selected items'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/8c723b87-9145-46f9-badc-a691987a37b6)

## Additional Context ##
This issue does not reproduce for disks.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/c0cd1fc4-d057-4a65-9699-cc3cbada09aa)

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230908.4. Fixed on regular/ADLS Gen2 blob explorer.
Reproduce for files explorer.

**Comment by craxal** [comment]
Fixed for files.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230911.1. Fixed for files.
