### ISSUE TITLE
It is better to update the tooltip of 'Select All' to 'Select All in page' in blob explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7265]
**Storage Explorer Version**: 1.32.0-dev (93)
**Build Number**: 20230906.9
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: Exploratory testing
**Regression From**: Previous release (1.30.2)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Open one blob container.
3. Hove over the 'Select All' button on the toolbar.
4. Check whether the tooltip is 'Select All in Page'. 

## Expected Experience ##
The tooltip is 'Select All in Page'. 
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/ea715920-4060-4961-a70b-a4c3df3b20fa)

## Actual Experience ##
The tooltip is 'Select all items'. 
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/8d1aea4b-80e3-4f52-a6b3-12feb1bb67ea)

## Additional Context ##
This issue also reproduces for new ADLS Gen2 blob explorer.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230908.4. Fixed on regular/ADLS Gen2 blob explorer.
Reproduce for files explorer.

**Comment by craxal** [comment]
Fixed for files.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230911.1. Fixed for files.
