### ISSUE TITLE
Configurable columns on Blob Container grid

### ISSUE THREAD

**Issue by RolandoAvila** [microsoft/AzureStorageExplorer#7266]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I want to remove the new columns added. (access tier, access tier last modified) or any new columns I may not need.

### Desired Solution

I would like to select which columns I can see.

**Comment by JasonYeMSFT** [comment]
The work is done for 1.32.0. By right clicking on the column header, you will see a "Customize Columns..." action. You can click it and follow the instruction to configure your column preference that can persist across all blob containers.
