### ISSUE TITLE
Getting error while authenticating

### ISSUE THREAD

**Issue by arunkumar-subbiah** [microsoft/AzureStorageExplorer#7267]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.30.2

### Architecture

x64

### Storage Explorer Build Number

20230721.7

### Platform

Windows

### Bug Description

{
  "name": null,
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"read ECONNRESET\\\",\\n  \\\"stack\\\": \\\"Error: read ECONNRESET\\\\n    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)\\\\n    at __node_internal_errnoException (node:internal/errors:620:12)\\\\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)\\\",\\n  \\\"errno\\\": -4077,\\n  \\\"code\\\": \\\"ECONNRESET\\\",\\n  \\\"syscall\\\": \\\"read\\\"\\n}\""
}

### Steps to Reproduce

1. Launch storage explorer
2. Try to add an azure account

### Actual Experience

![image](https://github.com/microsoft/AzureStorageExplorer/assets/134924876/f72a888c-8083-4450-afff-c6910d0bdc49)

**Comment by MRayermannMSFT** [comment]
Hi @arunkumar-subbiah can you please:
1. Upgrade to the latest Storage Explorer
2. Try enabling system proxy: https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy ?

**Comment by arunkumar-subbiah** [comment]
Updated to the latest version resolved the issue.
