### ISSUE TITLE
Browse VHD files from inside Storage Explorer.

### ISSUE THREAD

**Issue by nezerulz** [microsoft/AzureStorageExplorer#727]
Storage Explorer Version: 1.4.2
Platform/OS Version: Windows 10 Professional
Architecture: ia32
Regression From: n/a

Feature request
Possibility to mount and browse vhd files inside Storage explorer

This will shorten download times in retrieving a particular file from a vhd instead of downloading the whole vhd

Actual Experience:
No possibility of doing this yet

**Comment by MRayermannMSFT** [comment]
This is out of the scope of Storage Explorer. Thank you for the request.
