### ISSUE TITLE
There is an extra '…' next to action 'Download' on the react file explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7270]
**Storage Explorer Version**: 1.32.0-dev (93)
**Build Number**: 20230908.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture**: x64/arm64/x64
**How Found**: From running test case
**Regression From**: Previous release (1.31.1)

## Steps to Reproduce ##
1. Expand one storage account ->File Shares.
2. Right click one file share -> Click '[New] Open'.
3. Upload one file -> Right click the file.
4. Observe the context menu.
5. Check there is no extra '...' next to the 'Download' action.

## Expected Experience ##
There is no extra '...' next to the 'Download' action.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/154f103f-4c3f-483d-8452-917da05e8335)

## Actual Experience ##
There is an extra '...' next to the 'Download' action.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/cedc5f59-c243-4fcc-bc30-6a22c088293f)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230911.1. Fixed.
