### ISSUE TITLE
There is no '…' next to 'Clone/rename/Move' actions on the react file explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7271]
**Storage Explorer Version**: 1.32.0-dev (93)
**Build Number**: 20230908.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture**: x64/arm64/x64
**How Found**: From running test case
**Regression From**: Previous release (1.31.1)

## Steps to Reproduce ##
1. Expand one storage account ->File Shares.
2. Right click one file share -> Click '[New] Open'.
3. Upload one file -> Right click the file.
4. Observe the context menu.
5. Check there is '...' next to the 'Clone/Rename/Move' actions.

## Expected Experience ##
There is '...' next to the 'Clone/Rename/Move' actions.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/7d1505fd-8762-4a08-ac80-e533e74b0f0b)

## Actual Experience ##
There is no '...' next to the 'Clone/Rename/Move' actions.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/309fd7c4-4780-468a-a073-0b8687fca73f)

**Comment by v-kellyluo** [comment]
@craxal  ,verified this issue on the build 20230911.1, there is no '...' next to 'Rename/Move' actions, so we are going to re-open it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/0c1b47e1-fe93-4075-a7c5-ede7798a77a9)

**Comment by craxal** [comment]
@v-kellyluo Sorry, I missed the "Rename" and "Move" part in the bug.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230912.1. Reproduce.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230913.4. Fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/7149b222-5ceb-4b50-9fb7-6c80e688441c)
