### ISSUE TITLE
The search icon doesn't disappear after typing a letter to the filter by prefix box

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7274]
**Storage Explorer Version:** 1.32.0-dev (93)
**Build Number:** 20230908.4
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture:** x64/x64/arm64
**How Found:** From running test cases
**Regression From:** Previous release (1.31.1)

## Bug Description ##

1. The search icon doesn't disappear after typing a letter to the filter by prefix box.
2. The location of the search icon is incorrect.

## Steps to Reproduce ##

1. Expand one storage account -> File Shares.
2. Create a file share -> Type a letter to the filter by prefix box.
3. Check whether the search icon disappears.

## Expected Experience ##
The search icon disappears.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/2894de66-67dc-443b-a2d0-a034475bc397)

## Actual Experience ##
The search icon doesn't disappear.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/2b23cb41-4836-42fd-b3b1-83df821c3fed)

**Comment by v-kellyluo** [comment]
@craxal ,verified this issue on the build 20230911.1, the search icon disappears after typing a letter to the filter by prefix box, but the location of the search icon is still incorrect, could you help to take a look?
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/8294c34f-1f23-459d-9c28-8f835167d1a0)

**Comment by craxal** [comment]
The change in the location of the icon is intentional to better match the search box in the tree view.

**Comment by v-kellyluo** [comment]
Hi @craxal, thanks for your update!

1. In new file explorer, the search icon is on the left side of the filter by prefix box.
2. But in new ADLS Gen2 explorer or view options panel, it is on the right side of the box.

Do they need to be consistent?
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/2ac925e4-5f1c-4bd4-a746-f5c8fb32135a)
