### ISSUE TITLE
Nothing happens after clicking 'Delete' for file share snapshots in the react file explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7275]
**Storage Explorer Version**: 1.32.0-dev (93)
**Build Number**: 20230908.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture**: x64/arm64/x64
**How Found**: From running test case
**Regression From**: Previous release (1.31.1)

## Steps to Reproduce ##
1. Expand one storage account ->File Shares.
2. Create a file share -> Right click the file share -> Click 'Create Snapshot'.
3. Right click the file share -> Click '[NEW] Open New Tab'.
4. Click 'View Share Snapshots'.
5. Select the snapshot -> Click 'Delete'.
6. Check whether the delete confirmation dialog pops up.

## Expected Experience ##
The delete confirmation dialog pops up.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/e85c0a13-0bc7-40ae-8b62-7daa0fd4edb1)

## Actual Experience ##
No delete confirmation dialog pops up.

## Additional Context ##
This issue also reproduces when pressing 'Delete' on the keyborad.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230911.1. Fixed.
