### ISSUE TITLE
The pasted file will be transferred to the react file explorer if press Ctrl+V on the address bar/filter by prefix box

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7276]
**Storage Explorer Version**: 1.32.0-dev (93)
**Build Number**: 20230908.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture**: x64/arm64/x64
**How Found**: Exploratory testing
**Regression From**: Previous release (1.31.1)
## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Right click one file share -> Click '[NEW] Open'.
3. Upload one file -> Select the file -> Click 'Copy'.
4. Click the address bar -> Press Ctrl+V.
5. Check there is no transfer activity log.

## Expected Experience ##
There is no transfer activity log.

## Actual Experience ##
There is a transfer activity log.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230911.1. Fixed.
