### ISSUE TITLE
It is better to support using Ctrl+F to focus the filter by prefix box

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7278]
**Storage Explorer Version**: 1.32.0-dev (93)
**Build Number**: 20230908.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture**: x64/arm64/x64
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account ->File Shares.
2. Create a file share -> Press 'Ctrl+F'.
3. Check whether the filter by prefix box is focused.

## Expected Experience ##
The filter by prefix box is focused.

## Actual Experience ##
The filter by prefix box is not focused.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230911.1. Fixed.
