### ISSUE TITLE
The split tabs are inconsistent if the original tab is not under the root/current view

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7279]
**Storage Explorer Version:** 1.32.0-dev (93)
**Build Number:** 20230908.4
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture:** x64/x64/arm64
**How Found:** From running test cases
**Regression From:** Previous release (1.31.1)

## Steps to Reproduce ##

1. Expand one storage account -> File Shares.
2. Select and right click one file share -> Click '[New] Open'.
3.  Click 'View Share Snapshots'.
4. Right click the file share tab -> Click 'Split'.
5. Check whether the split tabs are consistent.

## Expected Experience ##
The split tabs are consistent.

## Actual Experience ##
The split tabs are inconsistent.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/35baee1d-6640-41fe-8045-51d36a61f0f6)

## Additional Context ##
This issue also reproduces when the original tab is not under the root view.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/f35871e2-544a-4dd4-b965-985e54369d7a)

**Comment by craxal** [comment]
Session state for the tab is not being saved/loaded correctly. Working on a fix.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230912.1. Reproduce.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230913.4. Fixed.
