### ISSUE TITLE
Not able to connect to storage account using azure storage explore

### ISSUE THREAD

**Issue by knsujith2** [microsoft/AzureStorageExplorer#728]
**Storage Explorer Version**:   1.4.2
**Platform/OS Version**:  Windows10
**Architecture**: 
**Regression From**:  

#### Steps to Reproduce: ####
1. Try to logon to microsoft account with correct credentials using azure storage explore.
account  : knsujith@gmail.com

#### Expected Experience: ####
I should be able to connect to azure storage.

#### Actual Experience: ####

I am not able to log in. Throwing below error.

Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: f8cdef31-a31e-4b4a-93e4-5f571e91255a, Error: {"code":"ENOTFOUND","errno":"ENOTFOUND","syscall":"getaddrinfo","hostname":"management.azure.com","host":"management.azure.com","port":443}
Tenant Id: d5e3ee3d-2e45-4576-a5af-8f47d2a3632e, Error: {"code":"ENOTFOUND","errno":"ENOTFOUND","syscall":"getaddrinfo","hostname":"management.azure.com","host":"management.azure.com","port":443}

**Comment by MRayermannMSFT** [comment]
@knsujith2 are you behind a proxy? If so, then you'll need to add your proxy info to the proxy settings. See more here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&tabs=Windows%2C1904#proxy-issues

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
