### ISSUE TITLE
Error when opening azure storage explorer

### ISSUE THREAD

**Issue by joseluiseiguren** [microsoft/AzureStorageExplorer#7283]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.31.1 (93)

### Architecture

x64

### Storage Explorer Build Number

20230822.1

### Platform

Windows

### Bug Description

Unable to retrieve child resources

ProducerError:{
  "name": "Node Fetch Error",
  "message": "{\"name\":\"Node Fetch Error\",\"cause\":{\"cause\":{\"name\":\"ConnectTimeoutError\",\"code\":\"UND_ERR_CONNECT_TIMEOUT\",\"message\":\"Connect Timeout Error\"}},\"code\":\"UND_ERR_CONNECT_TIMEOUT\"}"
}

### Steps to Reproduce

1. Open the application

### Actual Experience

When I open the application, it raises a popup with the error avobe

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response from original author. This issue will no longer be monitored. If you still require help, we recommend opening an Azure support ticket via the Azure portal.
