### ISSUE TITLE
Nothing happens when pressing Delete key for one file share snapshot

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7284]
**Storage Explorer Version:** 1.32.0-dev (93)
**Build Number:** 20230911.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture:** x64/x64/arm64
**How Found:** From running test cases
**Regression From:** Previous release (1.31.1)

## Steps to Reproduce ##

1. Expand one storage account ->File Shares.
2. Create a file share -> Right click the file share -> Click 'Create Snapshot'.
3. Right click the file share -> Click '[NEW] Open New Tab'.
4. Click 'View Share Snapshots'.
5. Select the snapshot -> Press 'Delete'.
6. Check whether the delete confirmation dialog pops up.

## Expected Experience ##
The delete confirmation dialog pops up.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/561d34ec-f62e-4b72-8442-7a0127fcc31a)

## Actual Experience ##
No delete confirmation dialog pops up.

**Comment by craxal** [comment]
Duplicate of #7275.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230912.1. Reproduce.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20230913.4. Fixed.
