### ISSUE TITLE
The file still displays on the react file explorer if type a string on the address bar then press 'Enter'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7285]
**Storage Explorer Version**: 1.32.0-dev (93)
**Build Number**: 20230911.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture**: x64/arm64/x64
**How Found**: From running test case
**Regression From**: Previous release (1.31.1)

## Steps to Reproduce ##
1. Expand one storage account ->File Shares.
2. Right click one file share -> Click '[New] Open'.
3. Upload one file.
4. Type 'test' on the address bar -> Press 'Enter'.
5. Check no file displays on the file explorer.

## Expected Experience ##
No file displays on the file explorer.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/56cf2de0-21f3-44f5-b2fc-5576f27164b3)

## Actual Experience ##
The file displays on the file explorer.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/906d4aaf-f691-449e-8e3c-d81445484b9f)

**Comment by craxal** [comment]
@v-xianya The folder doesn't exist in the share. Do you get any error message when you enter the folder name?

**Comment by v-xianya** [comment]
@craxal  Yes, there is an error info bar when entering the folder name.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/6e473861-60c6-4b21-b935-695a9e88c7b1)

Verified this issue on the main build 20230912.1. Reproduce.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230913.4. Fixed. So, we are going to close it.
