### ISSUE TITLE
The string on the address bar doesn't make sense if type '/' then press enter on the address bar

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7286]
**Storage Explorer Version**: 1.32.0-dev (93)
**Build Number**: 20230911.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture**: x64/arm64/x64
**How Found**: Exploratory testing
**Regression From**: Previous release (1.31.1)

## Steps to Reproduce ##
1. Expand one storage account ->File Shares.
2. Create a new file share -> Type '/' on the address bar then press 'Enter'.
3. Observe the address bar.
4. Check whether the strings on the address bar makes sense.

## Expected Experience ##
The strings on the address bar makes sense.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/db0e3321-f8e1-408e-a5cd-ace12efc2f97)

## Actual Experience ##
The strings on the address bar does not make sense.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/62397a49-f138-4888-97bc-44cdae9a971d)

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230912.1. Reproduce.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230913.4. 
The current behavior: still show the root path after typing '/' then press 'Enter'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/bfa84547-566d-453e-b562-d8a68cf79216)

**Comment by craxal** [comment]
Yes, that's now expected. A leading slash usually indicates an absolute path (one that starts at the root), so we're now duplicating that behavior here.
