### ISSUE TITLE
Carriage Return in data messes up CSV export

### ISSUE THREAD

**Issue by MikeWilliams-UK** [microsoft/AzureStorageExplorer#729]
**Storage Explorer Version**: 1.4.2
**Platform/OS Version**: Windows 10
**Architecture**: ia32

#### Steps to Reproduce: ####
1. Create an Azure Function which writes multiple lines to the TraceWriter log.
(ie calling log.Info("This data is written to the log"); inside the Run method)
2. Open storage explorer, connect to storage account where Function's WebJob logs are stored.
3. The output is visble in the grid, as column LogOutput.

#### Expected Experience: ####
When I export the grid to csv I should be able to view it in Excel.

#### Actual Experience: ####
When I export the grid to csv the Carriage returns in the log mess up Excel's ability to read the csv file, hence putting a blocker to using Excel to perform further anaysis.

**Comment by leidegre** [comment]
Please for the love of God. Fix this.

**Comment by MRayermannMSFT** [comment]
@MikeWilliams-UK and @leidegre 

Does the actual text contents of the file appear to be right? Or in other words, are we downloading the data poorly and that is messing excel up, or, are we downloading the data correctly and this is just a bug in excel?

**Comment by MikeWilliams-UK** [comment]
Sorry, but I no longer actively use Service Bus Explorer. So I am unable to help.

**Comment by MRayermannMSFT** [comment]
Welp. Ok!
