### ISSUE TITLE
The file editor is refreshed when clicking the current location on the recent locations dropdown list

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7292]
**Storage Explorer Version**: 1.32.0-dev (93)
**Build Number**: 20230912.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture**: x64/arm64/x64
**How Found**: Exploratory testing
**Regression From**: Previous release (1.31.1)

## Steps to Reproduce ##
1. Expand one storage account ->File Shares.
2. Create a file share named 'new' -> Click 'View Share Snapshots'.
3. Expand recent locations -> Click **Snapshots for 'new'.**
4. Check the editor is not refreshed.

## Expected Experience ##
The editor is not refreshed.

## Actual Experience ##
The editor is refreshed.
![0912](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/3a7aad56-79cf-46b7-9fa7-0f724cbe5713)

## Additional Context ##
This issue doesn't reproduce for regular/ ADLS Gen2 blob containers.

**Comment by craxal** [comment]
@v-xianya Are you sure blobs doesn't also refresh? It could be the UI updates too quickly to notice. Either way, I do think this a bug.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230913.4. Reproduce.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230918.1. Fixed. So, we are going to close it.
