### ISSUE TITLE
Erroneous Transfer Complete downloading a blob open by another process

### ISSUE THREAD

**Issue by brianmatusz** [microsoft/AzureStorageExplorer#7293]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.31.1

### Architecture

x64

### Storage Explorer Build Number

93

### Platform

Windows

### Bug Description

Downloading a blob and overwriting an existing blob open by another process reports the activity succeeded. But the download is not completed because the temporary .azDownload file is unable to overwrite the file open by another process. 

### Steps to Reproduce

1. Launch storage explorer.
2. Using Storage Explorer, download a ZIP file of any size from an Azure storage account container to the local disk. Storage Explorer will report the successful transfer (used SAS, discovery completed) as expected.
3. Open the ZIP file locally using a tool like 7Zip and leave it open.
4. Using Storage Explorer, download the ZIP again to the same local disk location. Specify "Overwrite" when prompted.
5. Storage Explorer will report the transfer succeeded.

### Actual Experience

Open File Explorer to the local disk location. An .azDownload-{guid}-{filename.exe} will exist in the folder and the target file opened by another process will not be overwritten.

### Expected Experience

Microsoft Storage Explorer should report that the transfer was not successful due to the file being open by another process.

**Comment by craxal** [comment]
Possibly an issue with AzCopy. Need to look into this.

**Comment by JasonYeMSFT** [comment]
@brianmatusz Could you please open an issue describing what you observed in the [AzCopy repo](https://github.com/Azure/azure-storage-azcopy)? Storage Explorer 1.31.1 uses AzCopy 10.20.1. If possible, please consider sharing the AzCopy log file for the erroneous completed download. The log file can be found in a folder named ".azcopy" under your user directory.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem, you can either open a support ticket via the Azure portal, or open a new issue here. This issue however will no longer be monitored.
