### ISSUE TITLE
Remove the string 'currently supported by table explorers only' from descriptions of 'Global Sort'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7295]
**Storage Explorer Version**: 1.32.0-dev (93)
**Build Number**: 20230913.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture**: x64/arm64/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Open 'Settings' -> Click 'Data Explorers'.
2. Observe the descriptions of the setting 'Global Sort'.

## Expected Experience ##
Remove the string 'currently supported by table explorers only' from the descriptions of 'Global Sort'.

## Actual Experience ##
The string 'currently supported by table explorers only' shows in the descriptions of 'Global Sort'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/48e74036-c1d0-4315-b795-8f43d3a954bd)

**Comment by MRayermannMSFT** [comment]
I have updated the description for numerous data explorer settings. Please note that the descriptions of what should be supported are accurate for what we intend to ship in 1.32, not necessarily what is supported at the time of this comment.

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT Verified this issue on the main build 20230914.4. The descriptions have been updated.

I thought it would make more sense to use 'Load more' instead of 'Load All' in the descriptions.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/846fb07c-7065-4b08-a39a-c2fae4c6a3b3)
