### ISSUE TITLE
Block Blob Size in GiB are rounded

### ISSUE THREAD

**Issue by brianmatusz** [microsoft/AzureStorageExplorer#7296]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Would like to download the larger of two block blobs. I have to view the properties of each blob to determine which is larger.

### Desired Solution

Would like additional precision on block blob sizes (2.123 GiB). Or a configuration item that lets me view the raw value with commas (ex: 2,123,123,123)

### Alternatives and Workarounds

Right-click on each blob and scroll down to properties which is time consuming

### Additional Context

I have a screenshot, but two blobs side-by-side show as 2 GiB but one is slightly larger than the other. I can't tell unless I open properties

**Comment by brianmatusz** [comment]
<img width="527" alt="image" src="https://github.com/microsoft/AzureStorageExplorer/assets/25850776/268dccf9-0b7c-41e7-8dfb-e188f0790cee">
An example of what the view looks like.

**Comment by JasonYeMSFT** [comment]
We will preserve two digits after the decimal point if the size is in a unit greater or equal to KiB in 1.32.0.

**Comment by brianmatusz** [comment]
Thank you for the quick turn around on this! Much appreciated!
