### ISSUE TITLE
Add real functional tests for decimal places of numbers formatted by system format

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#7297]

**Comment by craxal** [comment]
@JasonYeMSFT @MRayermannMSFT Can we narrow down the scope of tests being asked for? This is not trivial. Open to ideas, but the trick will be being able to predict the locale and format settings of the test machine. I would think we would want to use different settings to test other formats as well.

**Comment by JasonYeMSFT** [comment]
I updated the title. We are interested in testing the number of digits after the decimal points if we explicitly specify how many digits to use.
