### ISSUE TITLE
Casing of 'Open In Portal' is wrong for database context menu

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#73]
**Storage Explorer Version:** 20180424.5(1.0.0)

**OS Version:** Win10/Mac/Linux

**Regression**: Not a regression

**Steps to Reproduce:**

1. Launch Storage Explorer and expand one Cosmos DB accounts.
2. Right click database node and check the context menu.

**Expected Experience:**
Display 'Open **in** Portal' on the context menu.

**Actual Experience:**
Display 'Open **In** Portal' on the context menu.
![in](https://user-images.githubusercontent.com/34729022/39233039-c38f2d3a-485e-11e8-9218-952f810b42c0.png)

**More info:**
This issue doesn't reproduce for Cosmos DB account context menu.

**Comment by MRayermannMSFT** [comment]
Merged into master.
