### ISSUE TITLE
Azurite emulator for local Azure Storage development : Unable to retreive child resource in Microsoft Azure Storage Explorer

### ISSUE THREAD

**Issue by Samuelchg** [microsoft/AzureStorageExplorer#7304]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.31.1

### Architecture

x64

### Platform

All

### Bug Description

Azurite emulator for local Azure Storage development : Unable to retreive child resource 

Error Message : Unable to retrieve child resources

Detail : "HTTP/1.1 404 , Not Found"
"url": "http://127.0.0.1:10000/devstoreaccount1?comp=list&include=metadata",
"method": "GET"

![image](https://github.com/microsoft/AzureStorageExplorer/assets/46440617/01772dca-7f5b-4200-9a8e-c77cf14c926a)

### Steps to Reproduce

1. docker pull mcr.microsoft.com/azure-storage/azurite
2. docker run -p 10000:10000 mcr.microsoft.com/azure-storage/azurite azurite-blob --blobHost 0.0.0.0 --blobPort 10000
3. Open Microsoft Azure Storage Explorer connect to "Blob Containers"

### Actual Experience

I try to create an azure blob storage emulator in my local machine by the following step:

1. docker pull mcr.microsoft.com/azure-storage/azurite
2. docker run -p 10000:10000 mcr.microsoft.com/azure-storage/azurite azurite-blob --blobHost 0.0.0.0 --blobPort 10000
3. Open Microsoft Azure Storage Explorer connect to "Blob Containers"

But got the below error when I connect it with the Microsoft Azure Storage Explorer.

Error Message : Unable to retrieve child resources

Detail : "HTTP/1.1 404 , Not Found"
"url": "http://127.0.0.1:10000/devstoreaccount1?comp=list&include=metadata",
"method": "GET"

![image](https://github.com/microsoft/AzureStorageExplorer/assets/46440617/01772dca-7f5b-4200-9a8e-c77cf14c926a)

**Comment by MRayermannMSFT** [comment]
Hello:

1. What version of azurite are you using?
2. Are you able to share the stdout/terminal/log output of Azurite?

**Comment by JasonYeMSFT** [comment]
@ninoissac Your issue is different from the original author's. Please open a new issue and follow the template to describe it.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response from original author. This issue will no longer be monitored. If you still require help, we recommend opening an Azure support ticket via the Azure portal.
