### ISSUE TITLE
Fail to detach one broken regular/ADLS Gen2 blob container attachment

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7305]
**Storage Explorer Version**: 1.32.0-dev (93)
**Build Number**: 20230915.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5.2 (Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.31.1)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
3. Select one blob container -> Attach the blob container via OAuth.
4. Switch to the 'ACCOUNT MANAGEMENT' panel -> Remove the azure account that associated with the OAuth attachment.
5. Switch to the 'EXPLORER' panel -> The attached blob container shows as broken.
6. Detach the broken attachment.
7. Check whether succeeds to detach broken attachment.

## Expected Experience ##
Succeed to detach the broken attachment.

## Actual Experience ##
Fail to detach the broken attachment.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/c12c6d84-6c43-44d9-a97c-e9c4747d2041)

## Additional Context ##
The broken attachments disappear after manually refreshing.

**Comment by v-xianya** [comment]
Hi @JasonYeMSFT This issue also reproduces when detaching one expired ADLS Gen2/regular blob container attachment.

**Comment by JasonYeMSFT** [comment]
I published a new package and this should be fixed in our next build.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230920.1. Fixed. So, we are going to close it.
