### ISSUE TITLE
Only 1000 entities are loaded when sorting by one column if there is a query clause under query mode

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7306]
**Storage Explorer Version:** 1.32.0-dev (93)
**Build Number:** 20230915.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5.2 (Apple M1 Pro)
**Architecture:** x64/x64/x64
**How Found:** Exploratory testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Open 'Settings' -> Enable the setting 'Global Sort'.
2. Expand one storage account -> Tables.
3. Open one table which contains more than 1000 entities.
4. Click 'Query' -> Make sure there is at least one query clause.
5. Sort entities by one column.
6. Check whether all entities are loaded.

## Expected Experience ##
All entities are loaded.

## Actual Experience ##
Only 1000 entities are loaded.

## Additional Context ##

1. This issue doesn't reproduce when there is no query clause.
2. Here is the record:
![enti](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/4631c652-93d7-418b-9140-54a0e3abdc5b)

**Comment by craxal** [comment]
@v-kellyluo Unable to reproduce using 20230923.2. If you are still able to reproduce, can you be more precise about the steps you took?

**Comment by v-kellyluo** [comment]
@craxal , this issue still reproduces on the build 20230923.2, there are some details to reproduce this issue:

1. The table contains more than 1000 entities.
2. It is under query builder mode -> There is at least one query clause.
3. Sory by one column -> Check whether all entities are loaded.

**Comment by craxal** [comment]
@v-kellyluo Yes, I've tried to reproduce with those conditions, and I'm not able to do so. Can you provide a GIF or screenshot of the bug, please?

**Comment by v-kellyluo** [comment]
Hi @craxal, verified this issue on the build 20230923.2 and the latest build 20230928.9:

1. On build 20230923.2, only 1000 entities are loaded when sorting by one column if there is query clause, but it will load all entities if there is no query clause.
![before](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/2aac6253-d876-4d6f-a942-145d8b2e129b)

2. On build 20230928.9, regardless of whether there is a query clause, it only loads 1000 entities, here is the record:
![latest](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/96c76cc0-d574-4a26-a80b-b918053a70c3)

**Comment by craxal** [comment]
@v-kellyluo OK, I'm able to reproduce. This only occurs right as the explorer is opened, and the details are complex.

Please note that we recently altered query panel behavior such the explorer now has a _working_ query and an _applied_ query. The working query is what you see and edit in the query panel, and the applied query is the one that is used when listing entities, global sort, exporting, etc. The working entity is not applied until you click the Run Query button. Likewise, changes in the query panel aren't applied until the Run Query button is clicked.

With that said, the problem has several parts:
1. When the explorer first opens, the initial load retrieves the first 1000 entities. These 1000 entities from the first load are the 1000 entities seen when reproducing this bug.
2. Along with the first load, there's some code that also sets up a default query using the first entity's partition and row keys. This should be the _working_ query, but the code is setting the _applied_ query. This means that a subsequent global sort will use the mistakenly set applied query. 
3. Global sort appends results to the existing list. When you click a column header and trigger a global sort, it uses the modified applied query. The resulting query to Azure returns 0 results and appends those results to the existing lists (it looks like it refreshes loads 1000 entities).

Should have a fix out soon.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 2023107.7. Fixed.
