### ISSUE TITLE
Create configuration auto-enable mechanism

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#7307]
Create a mechanism for auto-setting a set of configurations for a certain percentage of users.

## Requirements

Auto-set only runs in the first session after a new install or update.

A configuration that Storage Explorer can auto-set has an associated $percentage$, which can be any integer between 1 and 100. This value indicates the probability that a user will be selected for auto-set. This value may change between versions.

Storage Explorer assigns each user a random $percentile$, which can be any integer between 1 and 100. Storage Explorer does not change this value between sessions or versions.

A user will be selected for auto-set for a given configuration if the following is true:

```math
percentile \le percentage
```

Storage Explorer will set the configuration to the auto-set value if and only if:
- The configuration has not been selected for auto-set previously.
- The user has been selected for auto-set.
- The value is not set to the default value.
    
Storage Explorer tracks the configurations for which a user has been selected for auto-set, regardless of whether the configuration value was actually changed. Once tracked, a configuration is no longer considered for auto-set in future sessions.

## Telemetry

Telemetry for each configuration should be sent during _every_ startup. For each configuration, data should include:
   - Whether a user was selected for auto-set
   - If selected for auto-set, what the intended auto-set value was
   - If selected for auto-set, what the configuration value actually was

Telemetry should be able to answer the following questions:
- For a given configuration, how many users were selected for auto-set during their last session?
- For a given configuration, if the user was selected for auto-set, how many users have the configuration set to the auto-set value?
- For a given configuration set to a particular value, what is the average amount of available memory across all users?

**Comment by craxal** [comment]
# Design

## Logic Flow

```mermaid
flowchart TD
  start[Launch]
  install{New install or update?}
  get[Get auto-set local storage values]
  nothing1[Do nothing]
  nothing2[Do nothing]
  exists{Exists?}
  compare[Compare auto-set values to threshold]
  gen["Generate random number [1..100]"]
  save[Save numbers to auto-set local storage]
  update[Update settings]

  start-->install
  install--True-->get
  install--False-->nothing1
  get-->exists
  exists--True-->compare
  compare-->above
  exists--False-->gen
  gen-->save
  save-->compare
  above--True-->update
  above--False-->nothing2
```

**Comment by MRayermannMSFT** [comment]
Example telemetry datas:

Let's say we want to enable `"services.storageAccounts.trailingAction"` for 20% of users. For a user in that 20%...

The telemetry sent during their first session of 1.32 should contain information like:
```
"services.storageAccounts.trailingAction": {
	"didAutoSet": "true"
	"expectedValue": "viewAll",
	"actual": "viewAll"
},
```

If they then set trailing action back to load more during that first session of 1.32, the telemetry sent during the second would contain information like:
```
"services.storageAccounts.trailingAction": {
	"didAutoSet": "true"
	"expectedValue": "viewAll",
	"actual": "loadMore"
},
```

For someone outside of the 20%, their telemetry would always would contain information like:
```
"services.storageAccounts.trailingAction": {
	"didAutoSet": "false"
},
```

**Comment by craxal** [comment]
Code adding mechanism and telemetry has been merged. Working on queries.
