### ISSUE TITLE
The file explorer is not focused after clicking 'Yes/No' on the refresh notification

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7308]
**Storage Explorer Version**: 1.32.0-dev (93)
**Build Number**: 20230918.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5.2 (Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> File Shares. (Make sure 'Auto Refresh On Change' is disabled)
2. Create a file share -> Upload one file.
3. There is a refresh notification -> Click 'Yes'.
4. Check whether the file explorer is focused.

## Expected Experience ##
The file explorer is focused.

## Actual Experience ##
The file explorer is not focused.

**Comment by craxal** [comment]
Change has been merged. Need to update package version.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20230927.4. Fixed.
