### ISSUE TITLE
Storage explorer does not start nor show any errors

### ISSUE THREAD

**Issue by niklas-e** [microsoft/AzureStorageExplorer#731]
**Storage Explorer Version**: 1.4.2 
**Platform/OS Version**: Linux Mint 19
**Architecture**: x86_64 
**Regression From**: 

#### Steps to Reproduce: ####
1. Start the StorageExplorer 
2. See infinitely lasting splash screen with a loading indicator

#### Expected Experience: ####

The program would start or inform about errors

#### Actual Experience: ####

1. After trying to start via UI, start the StorageExplorer from terminal to get at least some output
2. Crashes because ~/.config/appState.json does not exist
```
An error ocurred while retrieving previous app state:
Error: ENOENT: no such file or directory, open '/home/niklas/.config/StorageExplorer/appState.json'
```
3. Create appState.json manually
4. Start StorageExplorer -> Invalid JSON in appState.json
```
An error ocurred while retrieving previous app state:
SyntaxError: Unexpected end of JSON input
```
5. Set appState.json contents to empty JSON object
6. Start StorageExplorer
```
UNHANDLED PROMISE REJECTION: 
TypeError: Cannot read property 'rect' of undefined
    at createMainWindow (/opt/azure-storage-explorer/resources/app/out/app/index.js:385:41)
```
7. Try to paste the default appstate to appState.json (copied from ./resources/app/out/app/AppSettingsHelper.js)
8. Start StorageExplorer
9. Nothing at all happens except infinitely lasting splash screen with a loading indicator. No errors or info in terminal.

**Comment by Mithrilhall** [comment]
Same issue here.

Storage Explorer Version: 1.4.2 
Platform/OS Version: KDE Neon (rebased on Ubuntu 18.04 LTS)
Architecture: x86_64 
.NET Version:
```
Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

Command line output (I believe this was there before as well but the application worked):
```
ThinkPad-T460:~/Software/StorageExplorer-linux-x64$ ./StorageExplorer 

(StorageExplorer:10138): Gtk-WARNING **: 15:15:40.922: Theme parsing error: gtk.css:127:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(StorageExplorer:10138): Gtk-WARNING **: 15:15:40.922: Theme parsing error: gtk.css:128:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(StorageExplorer:10138): Gtk-WARNING **: 15:15:40.922: Theme parsing error: gtk.css:132:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
```

**Comment by Mithrilhall** [comment]
I ended up getting it to work. I had an old version of 1.3.1 and I tried that and it gave an error message that mentioned **`libgnome-keyring`.** I ended up installing **`libgnome-keyring-common`** and **`libgnome-keyring0`** and 1.3.1 and 1.4.2 both started.

**Comment by sashgorokhov** [comment]
Having the same issue.

**Comment by Mithrilhall** [comment]
Here is the contents of my appState.json.

```
{"lastWindowState":{"rect":{"x":1920,"y":32,"width":1920,"height":1044},"maximized":true}}
```

On a side note, I did an upgrade recently that must have uninstalled some stuff and I was no longer able to launch StorageExplorer; it would hang at `Loading`. I received no error messages in the terminal when launching.

I ended up trying to run an old copy of 1.3.1 that I had lying around and I received an error message that mentioned libgnome-keyring. I ended up installing `libgnome-keyring-common` and `libgnome-keyring0` and everything worked.

**Comment by MRayermannMSFT** [comment]
Sounds like y'all are good to go. Sorry we didn't get to y'all. For anyone following this still having issues please:

1. Try using our snap if you are having install problems
2. If your distro does not support snaps, then refer here to what our general dependencies are for Linux: https://docs.microsoft.com/en-us/azure/vs-azure-tools-storage-manage-with-storage-explorer?tabs=linux#prerequisites
3. If you are still stuck, you can open an issue, but depending on the distro we may or may not be able to help you. 

Thanks!
