### ISSUE TITLE
Source Code for Microsoft Azure Storage Explorer

### ISSUE THREAD

**Issue by jlongo62** [microsoft/AzureStorageExplorer#7312]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Where is the source for Microsoft Azure Storage Explorer

### Desired Solution

The link to a git repo containing Microsoft Azure Storage Explorer

**Comment by jlongo62** [comment]
Is Microsoft Azure Storage Explorer open-source ? If so where is the source code ?

**Comment by MRayermannMSFT** [comment]
Hi, at this time the code is not open source. This repo currently only hosts our issue tracking. If you have any feature requests or other issues, we encourage you to open an issue for them here. We (the storage explorer developers) will directly engage with you.
