### ISSUE TITLE
Keep getting error: This request is not authorized to perform this operation.

### ISSUE THREAD

**Issue by cf-szywko** [microsoft/AzureStorageExplorer#7315]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.31.1

### Regression From

NONE

### Architecture

x64

### Storage Explorer Build Number

20230822.1

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Keep getting 403 erorr doing normal staff. 

### Steps to Reproduce

1. Lunch app.
2. Keep working.
3. Do nothing for 1- 10 minutes.
4. Perform any action. 
5. Get 403 error:  RequestId:a319abc7-601e-0092-3439-ed5a2f000000 Time:2023-09-22T09:47:10.5714608Z

### Actual Experience

The solution which works sometimes are: reset work VPN, reset application, reset computer (always works.). I am getting this error like once per 20 minutes or  more often. If once get i am not able to do anything. 

### Expected Experience

I expect not to get these errors every now and then. 

### Additional Context

I suspect it can be related with stability of internet connection. 
My internet is not stable but i do not see it at all.

**Comment by craxal** [comment]
@cf-szywko Sounds like it could be an authentication issue. Can you provide your app and ServiceHub logs? Did you try signing out then back in?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.

If you're still encountering this issue, we recommend opening an Azure support ticket via the Azure portal. Alternatively you can open a new issue here. This issue will no longer be monitored.
