### ISSUE TITLE
does not allow me to pass information and generates this error in Microsoft Azure storage Explorer {   "message": "\"UnexpectedQuit\"" }

### ISSUE THREAD

**Issue by 1030kmilopar** [microsoft/AzureStorageExplorer#7316]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.31.1 (93)

### Regression From

No

### Architecture

x64

### Storage Explorer Build Number

20230822.1

### Platform

All

### OS Version

Windows 10

### Bug Description

Al cargar copia de seguridad en Link URL genera error:
```
{
  "message": "\"UnexpectedQuit\""
}
```

me he desconectado ya he reiniciado la aplicación y el equipo y genera la misma falla
![Captura](https://github.com/microsoft/AzureStorageExplorer/assets/145792680/d1227272-51d1-4c0b-a5d2-05bdf38ff427)

### Steps to Reproduce

cargo la aplicación Microsoft azure Storage, ingreso a recurso compartido de archivos y me pide la url de conexión y el nombre que le quiero dejar a la conexión, se conecta, pero cuando voy a cargar una carpeta para subirla, genera el error enviado y ya no permite seguir  cargando información
![Captura](https://github.com/microsoft/AzureStorageExplorer/assets/145792680/c6e6cc1d-9f05-4e32-aeec-6194aa8ab0a2)

### Actual Experience

cargo la aplicación Microsoft azure Storage, ingreso a recurso compartido de archivos y me pide la url de conexión y el nombre que le quiero dejar a la conexión, se conecta, pero cuando voy a cargar una carpeta para subirla, genera el error enviado y ya no permite seguir  cargando información

### Expected Experience

Que me permita cargar la información faltante

### Additional Context

ya se informo

**Comment by craxal** [comment]
@1030kmilopar It appears that you are connecting to a file share using a shared access signature (SAS). Can you tell us more about the parameters of the SAS? What permissions does the SAS have? When does it expire?

**Comment by JasonYeMSFT** [comment]
@1030kmilopar The "UnexpectedQuite" error often indicates AzCopy crashed. Could you try running the AzCopy command in the command line and share the output in the console? Meanwhile, if you can reproduce the issue from AzCopy CLI, please open an issue with the command line reproduction in [AzCopy repo](https://github.com/Azure/azure-storage-azcopy) and their engineers can provide you better help.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.

If you're still encountering this issue, we recommend opening an Azure support ticket via the Azure portal. Alternatively you can open a new issue here. This issue will no longer be monitored.
