### ISSUE TITLE
The 'Connect File Share to VM' dialog is not localized completely

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7319]
**Storage Explorer Version:** 1.32.0-dev (93)
**Build Number:** 20230923.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5.2 (Apple M1 Pro)
**Language:** All languages
**Architecture:** x64/x64/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.31.1)

## Steps to Reproduce ##

1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select 'Deutsch' -> Restart Storage Explorer.
3. Expand one storage account -> File Shares.
4. Create a file share -> Click 'Connect VM'.
5. Check whether the 'Connect File Share to VM' dialog is localized completely.

## Expected Experience ##
The 'Connect File Share to VM' dialog is localized completely.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/8b6835cd-d2bf-42ac-9029-5db37bd3c60b)
## Actual Experience ##
The 'Connect File Share to VM' dialog is not localized completely.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/3d62783f-ba71-4208-a007-d3b0f4079e0b)

**Comment by JasonYeMSFT** [comment]
If the strings aren't ready, let's move it to the loc milestone.

**Comment by craxal** [comment]
Localization takes time. Moving to loc milestone.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20231103.1. Fixed. So, we are going to close it.
