### ISSUE TITLE
SELF_SIGNED_CERT_IN_CHAIN

### ISSUE THREAD

**Issue by adwaitu** [microsoft/AzureStorageExplorer#732]
**Storage Explorer Version**: 1.42
**Platform/OS Version**: Windows 10
**Architecture**: ia32
**Regression From**: No

#### Steps to Reproduce: ####
1. Install a self signed cert on your computer to use VPN
2. Login to Storage Explorer

#### Expected Experience: ####
Should be able to login and use the app

#### Actual Experience: ####
Unable to login, error message:

Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: 513294a0-3e20-41b2-a970-6d30bf1546fa, Error: {"code":"SELF_SIGNED_CERT_IN_CHAIN"}

**Comment by JakeRadMSFT** [comment]
Please see: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?toc=%2fazure%2fstorage%2fqueues%2ftoc.json

**Comment by MRayermannMSFT** [comment]
Closing due to lack of reply. Please open a new issue if you still have problems.
