### ISSUE TITLE
The name of the 'Create Snapshot' icon shows incompletely and end with '...' in one resource group's toolbar

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7321]
**Storage Explorer Version:** 1.32.0-dev
**Build Number:** 202030923.2
**Branch:** main
**Language:** German/Dutch/Swedish/Russian/Japanese/French
**Platform/OS:** x64/x64/x64
**Architecture:** Windows 10/ Linux Ubuntu 22.04/MacOS Ventura 13.5.2 (Apple M1 Pro)
**Regression From:** Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Deutsch' -> Restart Storage Explorer.
3. Expand 'Disks' -> Open one resource group.
4. Observe the toolbar.
5. Check whether the name of the 'Create Snapshot' icon shows completely.

## Expected Experience ##
The name of the 'Create Snapshot' icon shows completely.

## Actual Experience ##
 The name of the 'Create Snapshot' icon shows incompletely and end with '...'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/e6e55bc4-544a-44df-aea1-d3a5d87ad22e)

## Additional Context ##
The screenshot in ENU.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/c5706fce-8b66-48f9-9376-9e2d72a5319c)

**Comment by MRayermannMSFT** [comment]
This string is pretty long. Going to won't fix.
