### ISSUE TITLE
Azure Storage Explorer does not correctly use Proxy Settings

### ISSUE THREAD

**Issue by DivingJoen** [microsoft/AzureStorageExplorer#7322]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.31.1

### Regression From

1.29.0

### Architecture

x64

### Storage Explorer Build Number

20230822.1

### Platform

Windows

### OS Version

Windows Server 2016

### Bug Description

In Version 1.29.0 the system proxy was used without issues allowing to logon and work with ASX without issues.
Since the move to X64 logon is not possible anymore. Error:
"Anmeldung nicht möglich: The proxy tunnel request to proxy 'http://proxy-wsa-p.enbw.net:3128/' failed with status code '407'."

I've tried the different settings to no avail. The Environment Variables are set correct (are being used for some other applications). 

Strangely enough, when I logon under 1.29.0, then upgrade to 1.31.1 I can see the resources for which I was already setup. I can not logon however for other resources or when I logoff I can not logon to the resources again.

Version 1.31.1 no Logon possible:

Version 1.29 all working

Version 1.31.1 have access to the resources, can't logon

### Steps to Reproduce

Have a Proxy with a Proxy Technical User
Launch Storage Explorer
Try to logon

### Actual Experience

See bug description

### Expected Experience

Being able to work with ASX like in Version 1.29.0

**Comment by DivingJoen** [comment]
After further testing I noticed following error "Unable to sign in: The proxy tunnel request to proxy 'http://https:%2F%2F<username>%3A<password>@proxy-wsa-p.enbw.net:3128/' failed with status code '407'."".

Please note, that a "http://" has been added to the settings which of course will not work. Could that be the source why it will not work? Our Proxy is only reachable via https://

**Comment by MRayermannMSFT** [comment]
@DivingJoen http status 407 indicates that the proxy server wants you to authenticate.

Have you given Storage Explorer your proxy credentials? If not you can do so via Edit > Configure Proxy, and then entering your credentials and clicking "OK".

**Comment by MRayermannMSFT** [comment]
@DivingJoen ok, I'm going to assume we want to get System Proxy working since it was working for you before. So let's do the following:

1. Please downgrade to 1.29 (https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.29.2) and confirm that system proxy still works for you. If it does, let us know, if it doesn't, let us know the error you get.
2. Please upgrade back to 1.31 (https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.31.1)
3. If you are still getting the 407 error, please make sure you have set your proxy credentials via, Edit > Configure Proxy, and re-enter your proxy username & password. The status 407 indicates the server is expecting authentication information, so I am expecting you to have a proxy username & password.

If things are sitll not working, please follow these steps to gather and share Storage Explorer logs with us: https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/storage-explorer-troubleshooting?tabs=Windows#storage-explorer-logs

**Comment by DivingJoen** [comment]
Hi,

Thanks for your reply. I've gone through the steps requested:

Downgraded to 1.29 and access works with No-Proxy, App-Proxy and System Proxy. With App-Proxy I do get an error message and I need to exclude azure.com and our local domains for it to work.
![ASX_1292_NoProxy](https://github.com/microsoft/AzureStorageExplorer/assets/82597428/7b3f19fa-5dae-4252-98a7-13bc551e9c08)
![ASX_1292_AppProx](https://github.com/microsoft/AzureStorageExplorer/assets/82597428/c9adc6ea-6237-4e9b-a00b-2023e891dc7f)
![ASX_1292_SysProx](https://github.com/microsoft/AzureStorageExplorer/assets/82597428/caaf6e14-e982-479b-94c0-a7398260a707)
Strangely it does not work with Environment Variables even though they look correctly configured.
![ASX_1292_EnvironVar](https://github.com/microsoft/AzureStorageExplorer/assets/82597428/4d1c2a97-17a9-4bb0-aae8-a7b3f80ed85e)
our Environment Variables are written as http_proxy and https_proxy. Is this case sensitive?

I've upgraded to Version 1.31 and there only App-Proxy works (again with an initial error and after exluding our own domains and azure.com)
![ASX_1311_AppProx](https://github.com/microsoft/AzureStorageExplorer/assets/82597428/3c68e8d6-9fe4-4933-b76a-c5c5eb43981f)
No Proxy works initially when I've been already authenticated in 1.29.2, but as soon as I remove the account and try to reauthenticate I get the 407 error.
![ASX_1311_NoProx_AllreadyAuthenticated](https://github.com/microsoft/AzureStorageExplorer/assets/82597428/f5e978c2-723d-417d-8232-989d861ef665)
![ASX_131_NoProx_SignInFail](https://github.com/microsoft/AzureStorageExplorer/assets/82597428/2e8da0f2-b9d3-41f7-a872-e4698c29c818)
System Proxy also fails with a 407 erro.
![ASX_1311_SysProx](https://github.com/microsoft/AzureStorageExplorer/assets/82597428/74b2267c-8c73-460d-9f58-d2b84643a391)

Logs for App Proxy:
[ASX_1311AppProxy.zip](https://github.com/microsoft/AzureStorageExplorer/files/12736389/ASX_1311AppProxy.zip)

Logs for SysProxy:
[ASX_1311SysProxy.zip](https://github.com/microsoft/AzureStorageExplorer/files/12736392/ASX_1311SysProxy.zip)

Logs for NoProxy:
[ASX_1311NoProxy.zip](https://github.com/microsoft/AzureStorageExplorer/files/12736396/ASX_1311NoProxy.zip)

**Comment by MRayermannMSFT** [comment]
> our Environment Variables are written as http_proxy and https_proxy. Is this case sensitive?

For best results, I would use uppercase and follow all other specs listed here: https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-environment-variables

> No Proxy works initially when I've been already authenticated in 1.29.2, but as soon as I remove the account and try to reauthenticate I get the 407 error.

> System Proxy also fails with a 407 erro.

Ah ah ah, ok, these screenshots are a big help! I have an ideas as to the issue now. In 1.30, Storage Explorer on Windows auth library switched from using .NET Framework 4.7.2, to .NET 6. Based on your screenshots and provided logs, I believe the error is coming from the auth library.

 I need to do some research and talk to some folks on what needs to be done about this.

Some questions for you:
- Can you try setting your proxy environment variables using uppercase?
- Do you have this proxy configured at the OS level? For example, does it show up in Windows settings and are you connected to it?

**Comment by DivingJoen** [comment]
Thanks for your efforts so far. 

I've set the Proxy Environment Variables to Uppercase but it doesn't solve the issue. I do not get a 407 error and can authenticate but directly afterwards I get an error "could not access ressources for this tenant. You may need to reauthenticate." reauthenticating seems to work (able to succesfully logon) but it does nothing in the end. 
Error Details:
{
  "name": null,
  "message": "\"{\\n  \\\"name\\\": \\\"Node Fetch Error\\\",\\n  \\\"message\\\": \\\"unable to get local issuer certificate\\\",\\n  \\\"stack\\\": \\\"Error: unable to get local issuer certificate\\\\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1540:34)\\\\n    at TLSSocket.emit (node:events:513:28)\\\\n    at TLSSocket._finishInit (node:_tls_wrap:959:8)\\\\n    at ssl.onhandshakedone (node:_tls_wrap:743:12)\\\",\\n  \\\"cause\\\": {\\n    \\\"cause\\\": {\\n      \\\"code\\\": \\\"UNABLE_TO_GET_ISSUER_CERT_LOCALLY\\\"\\n    }\\n  },\\n  \\\"code\\\": \\\"UNABLE_TO_GET_ISSUER_CERT_LOCALLY\\\"\\n}\""
}
Here are the logs:
[ASX_1311_EnvVar.zip](https://github.com/microsoft/AzureStorageExplorer/files/12746578/ASX_1311_EnvVar.zip)

The Server is set to automatically recognize Proxy settings. Works for all other programs installed. 
Proxy itself is configured centrally and I do not have access to it. We've done a session with our proxy colleagues some time ago and basically it seemed on their side as if the calls with the 407 error were made without the authentication info.

**Comment by MRayermannMSFT** [comment]
Ok, thanks for the update. I think at this point you are going to be blocked. So in the meantime, please feel free to continue using 1.29.0. I will update this issue when I have more to share.

**Comment by JasonYeMSFT** [comment]
@DivingJoen We produced a private build that integrates a bug fix that might have solved your problem. Could you try installing it and see if it resolves your problem? [private build win64](https://storageexplorerpublish.blob.core.windows.net/privatebuilds/1.31.2-identity-proxy-credential/StorageExplorer-windows-x64-identity-proxy-credential.exe)

Please help do the following:
1. Install the private build
2. Set the proxy setting to "use system proxy"
3. Open Storage Explorer and check if it can pick up the proxy as well as your credentials like how it works in 1.29.0.

If that doesn't work, please try setting an environment variable VS_USE_DEFAULTPROXY and set its value to true. For example, in command prompt you can do "SET VS_USE_DEFAULTPROXY=true" to set the environment variable. After setting the environment variable, retry steps 1 to 3 and see if the proxy works.

**Comment by DivingJoen** [comment]
Hi,
Thanks for the update.

I've installed the private build and tested:

- I don not get a warning pop up that no connection is possible anymores
- When I try to sign in the browser pops up and I'm able to sign in succesfully there
- immediately when I return in ASX I get the 407 error again (Unable to sign in: The proxy tunnel request to proxy 'http://proxy-wsa-p.enbw.net:3128/' failed with status code '407'.")

Tried this using System Proxy, No Proxy 

the SET VS_USE_DEFUALTPROXY=true setting does not seem to make a difference. 

Interestingly enough, the "workaround" using App settings does not work anymore in this version.

Below the logs with verbose authentication logging.

[SystemProxy_NoVar.zip](https://github.com/microsoft/AzureStorageExplorer/files/12818899/SystemProxy_NoVar.zip)
[NoProxy_NoVar.zip](https://github.com/microsoft/AzureStorageExplorer/files/12818902/NoProxy_NoVar.zip)

[SystemProxy_VarSet.zip](https://github.com/microsoft/AzureStorageExplorer/files/12818901/SystemProxy_VarSet.zip)
[NoProxy_VarSet.zip](https://github.com/microsoft/AzureStorageExplorer/files/12818898/NoProxy_VarSet.zip)

**Comment by JasonYeMSFT** [comment]
@DivingJoen Is it possible for us to have a screenshare session with you to debug the problem on your end? At this point, we have exhausted all the potential ideas of the cause. If this is possible for you, please send us (sehelp at microsoft dot com) an email with your available time in the following week and your preferred tools (e.g. MS Teams, zoom, etc.). 

Do you use Visual Studio on that computer? If you don't, are you willing to install Visual Studio Community for the troubleshooting purpose? If Visual Studio is available, we can create a much simpler .net core application to help reproduce the problem and locate the cause.

At the meantime, could you try to collect the verbose authentication logs for the error? Authentication logs are different from the Storage Explorer logs you shared. You need to enable Settings > Application > Sign-in > Verbose Authentication Logging. After enabling it, reproduce the error and collect the logs at `C:\Users\<your username>\AppData\Local\Temp\servicehub\logs`. We have instructions in this section of the troubleshooting guide [collect authentication logs](https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/storage-explorer-troubleshooting?tabs=Windows#authentication-logs). It would be even better if you can capture a Fiddler trace while reproducing the issue. When Fiddler is on, it acts as a local proxy server that intercepts and logs all the HTTP/HTTPS requests sent from your computer. We have instructions in this section of the troubleshooting guide [capture Fiddler trace](https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/storage-explorer-troubleshooting?tabs=Windows#network-logs).

**Comment by JasonYeMSFT** [comment]
We have added a few more additional loggings in a private build that may help us locate what the root cause is. Here is a link to the [build](https://storageexplorerpublish.blob.core.windows.net/privatebuilds/1.32.1-identity-proxy-logging/StorageExplorer-windows-x64-identity-proxy-logging.exe). It would be appreciated if you can install it, reauthenticate with the proxy and collect the authentication logs.

To enable the additional logging, please make sure you enable the "Verbose Authentication Logging" in the settings and make sure when starting Storage Explorer, a "VS_USE_DEFAULTPROXY" environment variable is set to "true".

**Comment by DivingJoen** [comment]
Hi,
This special Version ist the first 64bit Version that actually works for us on our W2K16 Server. 1.32.0 and 1.32.1 do not and still have the 407 Error. Attached the requested Zips with logs: 

First 1.32.1 which does not work
[logs 1.32.1.withEnvVar.zip](https://github.com/microsoft/AzureStorageExplorer/files/13488239/logs.1.32.1.withEnvVar.zip)
[logs 1.32.1.withoutEnvVar.zip](https://github.com/microsoft/AzureStorageExplorer/files/13488241/logs.1.32.1.withoutEnvVar.zip)

Then the special build which works. 
[logs 1.32.special.withEnvVar.zip](https://github.com/microsoft/AzureStorageExplorer/files/13488242/logs.1.32.special.withEnvVar.zip)
[logs 1.32.special.withoutEnvVar.zip](https://github.com/microsoft/AzureStorageExplorer/files/13488243/logs.1.32.special.withoutEnvVar.zip)

As both are nominally 1.32.1 I'm not sure how that is possible. If actually installed back and forth between 1.32.1 and 1.32.1"special" a few times to be sure but really only the special version works.

**Comment by JasonYeMSFT** [comment]
I checked with the identity service team. They did fix a few minor bugs which might mitigated the issue. If you are happy with the private build, you may keep using it until we ship 1.33.0. The only difference between official 1.32.1 and the private build is the upgraded identity service package. Besides, the new identity service package we integrated is one of their official release so you don't need to worry about its stability. We have integrated the same version of the identity service package in 1.33.0 so it will also have the fixes.
