### ISSUE TITLE
There is no tooltip Ctrl+R for 'Refresh' action in the new queue explorer

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7323]
**Storage Explorer Version:** 1.32.0-dev (93)
**Build Number:** 20230928.9
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.5.2 (Apple M1 Pro)
**Architecture:** x64/x64/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.31.1)

## Steps to Reproduce ##

1. Expand one storage account -> Queues.
2. Create a queue -> Right click the queue -> Click '[NEW] Open in New Tab'.
3. Hover the mouse to the 'Refresh' button in the toolbar.
4. Check whether there is a tooltip Ctrl+R.

## Expected Experience ##
There is a tooltip Ctrl+R.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/53f58192-e81a-4cab-9bb5-66b78311e064)

## Actual Experience ##
1. There is no tooltip Ctrl+R.
2. Ctrl+R works well.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/9868c1cd-732a-437d-b1bc-8b7f7e0083ae)

**Comment by v-xianya** [comment]
Verified this issue on the main build 20231007.7. Fixed. So we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/5d0cbbef-9594-48ad-beb3-d94fbf35b8db)
