### ISSUE TITLE
'View/Delete/Requeue/Move Selected...' actions are enabled after deleting/clearing all messages in the queue

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7324]
**Storage Explorer Version:** 1.32.0-dev (93)
**Build Number:** 20230928.9
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.5.2 (Apple M1 Pro)
**Architecture:** x64/x64/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.31.1)

## Steps to Reproduce ##

1. Expand one storage account -> Queues.
2. Create a queue -> Right click the queue -> Click '[NEW] Open in New Tab'.
3. Add one message -> Delete the message.
4. Check whether 'View/Delete/Requeue/Move Selected...' actions are disabled.

## Expected Experience ##
'View/Delete/Requeue/Move Selected...' actions are disabled.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/b051f4dd-ae65-44af-a6c3-0d229c7415e9)

## Actual Experience ##
'View/Delete/Requeue/Move Selected...' actions are enabled.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/d23a5874-ee1d-4556-bd6c-1fde392a2477)

**Comment by richardMSFT** [comment]
I am unable to reproduce this behavior. Let me know if you are still experiencing it.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20231007.7, it doesn't reproduce, so we are going to close it.
