### ISSUE TITLE
The second message is selected automatically after moving the first message

### ISSUE THREAD

**Issue by v-xinda** [microsoft/AzureStorageExplorer#7325]
**Storage Explorer Version:** 1.32.0-dev (93)
**Build Number:** 20230928.9
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture:** x64/x64/x64
**How Found:** From running testing
**Regression From:** Previous release (1.31.1)

## Steps to Reproduce ##

1. Expand one storage account -> Queues.
2. Create two queues -> Right click one queue -> Click '[NEW] Open in New Tab'.
3. Add two messages -> Select first message -> Click 'Move -> Move Selected' -> Select another queue -> Move.
4. Check whether the second message is not selected automatically.

## Expected Experience ##
The second message is not selected automatically.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/57662131/6cd27e00-f121-4182-8533-e69af9dab9ac)

## Actual Experience ##
The second message is selected automatically.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/57662131/9bc4b5a9-d952-460b-a92a-ce38a31ad437)

**Comment by v-kellyluo** [comment]
Verified this issue on the main build 20231007.7. Fixed. So we are going to close it.
