### ISSUE TITLE
There is an extra '...' next to the 'Customize Columns' in the toolbar

### ISSUE THREAD

**Issue by v-xinda** [microsoft/AzureStorageExplorer#7329]
**Storage Explorer Version:** 1.32.0-dev (93)
**Build Number:** 20230928.9
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture:** x64/x64/x64
**How Found:** From running testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create a table.
3. Hover on the 'Customize Columns' button in the toolbar.
4. Check whether there is no extra '...' next to the 'Customize Columns' in the toolbar.

## Expected Experience ##
There is no extra '...' next to the 'Customize Columns' in the toolbar.

## Actual Experience ##
There is an extra '...' next to the 'Customize Columns' in the toolbar.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/57662131/422b5d1a-f15d-4e32-b898-bf6005675879)

**Comment by v-xianya** [comment]
Verified this issue on the main build 20231007.7. The tooltip has been updated!
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/d8ce9fb8-ed97-4187-9a97-ec2ebae6cdc4)
