### ISSUE TITLE
Disk Download Error

### ISSUE THREAD

**Issue by cooldog77** [microsoft/AzureStorageExplorer#7330]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.31.1

### Architecture

x64

### Storage Explorer Build Number

20230822.1

### Platform

Windows

### OS Version

Windows 10

### Bug Description

AzCopy failed to complete the transfer.

AzCopy error message: failed to perform copy command due to error: Login Credentials missing. No SAS token or OAuth token is present and the resource is not public

### Steps to Reproduce

Browse to the Resource Group, find the file, right-click the disk and choose download.

### Actual Experience

I get the error described above with a failure to download

### Expected Experience

Download the VHD

### Additional Context

No idea why it's missing.

**Comment by MRayermannMSFT** [comment]
@cooldog77 can you please follow these steps to gather Storage Explorer logs while reproducing the issue? Thanks.

https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/storage-explorer-troubleshooting?tabs=Windows#storage-explorer-logs

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.

If you're still encountering this issue, we recommend opening an Azure support ticket via the Azure portal. Alternatively you can open a new issue here. This issue will no longer be monitored.
