### ISSUE TITLE
Error Message _ UND_ERR_CONNECT_TIMEOUT

### ISSUE THREAD

**Issue by ShicksFS** [microsoft/AzureStorageExplorer#7336]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.31.1

### Architecture

x64

### Storage Explorer Build Number

20230822.1

### Platform

Windows

### Bug Description

Was able to access Blob Containers with no issue.  Was able to access FireShares yesterday morning, but by afternoon it was no longer accessible.  Below is the error message received when trying access FileShares. It worked yesterday morning, by the afternoon it was no longer working.

Unable to retrieve child resources

ProducerError:{
  "name": "Node Fetch Error",
  "message": "Connect Timeout Error",
  "stack": "ConnectTimeoutError: Connect Timeout Error\n    at onConnectTimeout (C:\\Users\\Shelley\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\undici\\lib\\core\\connect.js:182:24)\n    at C:\\Users\\Shelley\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\undici\\lib\\core\\connect.js:129:46\n    at Immediate._onImmediate (C:\\Users\\Shelley\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\undici\\lib\\core\\connect.js:168:33)\n    at process.processImmediate (node:internal/timers:476:21)",
  "cause": {
    "cause": {
      "name": "ConnectTimeoutError",
      "code": "UND_ERR_CONNECT_TIMEOUT",
      "message": "Connect Timeout Error"
    }
  },
  "code": "UND_ERR_CONNECT_TIMEOUT"
}

### Steps to Reproduce

uninstalled reinstalled Microsoft Azure Storage, upgraded program, checked connections, firewall, DNS, Proxy, wifi connection, etc

### Actual Experience

See Bug Description

**Comment by JasonYeMSFT** [comment]
@ShicksFS Your error is a network error which might have something to do with your local network configuration and proxy settings. Could you try enabling "use system proxy" in the settings? If that doesn't work, could you try collecting a network trace [instructions](https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/storage-explorer-troubleshooting?tabs=Windows#network-logs) and share it with us for troubleshooting?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.

If you're still encountering this issue, we recommend opening an Azure support ticket via the Azure portal. Alternatively you can open a new issue here. This issue will no longer be monitored.
