### ISSUE TITLE
Debug mode?

### ISSUE THREAD

**Issue by leomwa** [Microsoft/AzureStorageExplorer#734]
**Storage Explorer Version**: 1.4.2
**Platform/OS Version**: Windows 20180917.1
**Architecture**: ia32

#### Steps to Reproduce: ####
I seem to have this Test Menu on one machine but not another with the same version of Windows and Storage Explorer. How do I revert back to normal, and not be in this debug/test mode?

#### Expected Experience: ####
Normal UI

#### Actual Experience: ####
![image](https://user-images.githubusercontent.com/1427633/46538909-786f5c80-c8b5-11e8-8e45-61d4e6ba1178.png)

**Comment by MRayermannMSFT** [comment]
Well this is very interesting @leomwa , were you given a private build or was this straight from storageexplorer.com?

**Comment by leomwa** [comment]
On two machines, I got it from `scoop install storageexplorer` and one remains operational with default UI (no debug items or test menus). At one point the one on my one machine started exhibiting the debug mode menus behaviour.
I then uninstalled the scoop version, deleted the appdata profile and reinstalled from [official sources](https://azure.microsoft.com/en-us/features/storage-explorer/).
After installing the new version - eerily its like I didn't change a thing as even the Azure account information is reloaded from a priort install.
Any tips to completely start afresh will be appreciated :-)

**Comment by MRayermannMSFT** [comment]
What is scoop?

**Comment by MRayermannMSFT** [comment]
@leomwa , I looked into scoop and I'm not sure how it would be starting the app in debug mode. What I do know, is that debug mode is activated if you have an environment variable `NODE_ENV` and it is set to `development`.

**Comment by leomwa** [comment]
@MRayermannMSFT wow yea, NODE_ENV might well be it. I will get back to you (left my offending machine at work so I can't check the env vars at the moment). I did try it on my unaffected machine and saw the behavior after toggling development on and off - so I wonder if I left that toggled on.

Thanks a lot for looking into it.

**Comment by leomwa** [comment]
Can confirm that I found NODE_ENV set to development for my user on my work machine. That was what caused it.

Back to normal now. 
Thanks a lot @MRayermannMSFT
