### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by markwanghfc** [microsoft/AzureStorageExplorer#7340]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.0

### Regression From

1.18.0

### Architecture

i86

### Platform

Windows

### Bug Description

This request is not authorized to perform this operation.

This storage account's 'Firewalls & virtual networks' settings may be blocking access to storage services. Try adding your client IP address to the firewall exceptions, or by allowing access from 'all networks' instead of 'selected networks'. To learn more about Azure Storage firewalls and virtual networks, visit http://go.microsoft.com/fwlink/?LinkId=845443.

Error Details:
{
  "name": "RestError",
  "code": "AuthenticationFailed",
  "statusCode": 403,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://formstackpatienthi32c4ce.blob.core.windows.net/?sv=2022-11-02&ss=bfqt&srt=sco&sp=rwdlacupiyx&se=2023-09-29T02:05:17Z&st=2023-06-21T18:05:17Z&spr=https&SAS Token Redacted&comp=list&include=metadata",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2021-10-04"
        },
        "accept": {
          "name": "Accept",
          "value": "application/xml"
        },
        "user-agent": {
          "name": "User-Agent",
          "value": "Microsoft Azure Storage Explorer/1.31.1 (win32) azsdk-js-storageblob/12.12.0 (NODE-VERSION v18.15.0; Windows_NT 10.0.19045)"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "42bea6fc-80d8-4233-b26d-d01ddb248ea3"
        }
      }
    },
    "withCredentials": false,
    "timeout": 0,
    "keepAlive": true,
    "decompressResponse": false,
    "requestId": "42bea6fc-80d8-4233-b26d-d01ddb248ea3"
  },
  "response": {
    "request": {
      "streamResponseStatusCodes": {},
      "url": "https://formstackpatienthi32c4ce.blob.core.windows.net/?sv=2022-11-02&ss=bfqt&srt=sco&sp=rwdlacupiyx&se=2023-09-29T02:05:17Z&st=2023-06-21T18:05:17Z&spr=https&SAS Token Redacted&comp=list&include=metadata",
      "method": "GET",
      "headers": {
        "_headersMap": {
          "x-ms-version": {
            "name": "x-ms-version",
            "value": "2021-10-04"
          },
          "accept": {
            "name": "Accept",
            "value": "application/xml"
          },
          "user-agent": {
            "name": "User-Agent",
            "value": "Microsoft Azure Storage Explorer/1.31.1 (win32) azsdk-js-storageblob/12.12.0 (NODE-VERSION v18.15.0; Windows_NT 10.0.19045)"
          },
          "x-ms-client-request-id": {
            "name": "x-ms-client-request-id",
            "value": "42bea6fc-80d8-4233-b26d-d01ddb248ea3"
          }
        }
      },
      "withCredentials": false,
      "timeout": 0,
      "keepAlive": true,
      "decompressResponse": false,
      "requestId": "42bea6fc-80d8-4233-b26d-d01ddb248ea3"
    },
    "status": 403,
    "headers": {
      "_headersMap": {
        "access-control-allow-origin": {
          "name": "access-control-allow-origin",
          "value": "*"
        },
        "access-control-expose-headers": {
          "name": "access-control-expose-headers",
          "value": "x-ms-request-id,x-ms-error-code,Content-Length,Date,Transfer-Encoding"
        },
        "content-length": {
          "name": "content-length",
          "value": "544"
        },
        "content-type": {
          "name": "content-type",
          "value": "application/xml"
        },
        "date": {
          "name": "date",
          "value": "Fri, 29 Sep 2023 17:49:32 GMT"
        },
        "server": {
          "name": "server",
          "value": "Microsoft-HTTPAPI/2.0"
        },
        "x-ms-error-code": {
          "name": "x-ms-error-code",
          "value": "AuthenticationFailed"
        },
        "x-ms-request-id": {
          "name": "x-ms-request-id",
          "value": "7cc4e6ab-501e-0019-43fd-f24a0a000000"
        }
      }
    },
    "bodyAsText": "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:7cc4e6ab-501e-0019-43fd-f24a0a000000\nTime:2023-09-29T17:49:33.4940864Z</Message><AuthenticationErrorDetail>Signature not valid in the specified time frame: Start [Wed, 21 Jun 2023 18:05:17 GMT] - Expiry [Fri, 29 Sep 2023 02:05:17 GMT] - Current [Fri, 29 Sep 2023 17:49:33 GMT]</AuthenticationErrorDetail></Error>",
    "parsedBody": {
      "message": "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:7cc4e6ab-501e-0019-43fd-f24a0a000000\nTime:2023-09-29T17:49:33.4940864Z",
      "code": "AuthenticationFailed",
      "AuthenticationErrorDetail": "Signature not valid in the specified time frame: Start [Wed, 21 Jun 2023 18:05:17 GMT] - Expiry [Fri, 29 Sep 2023 02:05:17 GMT] - Current [Fri, 29 Sep 2023 17:49:33 GMT]"
    },
    "parsedHeaders": {
      "errorCode": "AuthenticationFailed",
      "access-control-allow-origin": "*",
      "access-control-expose-headers": "x-ms-request-id,x-ms-error-code,Content-Length,Date,Transfer-Encoding",
      "content-length": "544",
      "content-type": "application/xml",
      "date": "Fri, 29 Sep 2023 17:49:32 GMT",
      "server": "Microsoft-HTTPAPI/2.0",
      "x-ms-request-id": "7cc4e6ab-501e-0019-43fd-f24a0a000000"
    }
  },
  "details": {
    "errorCode": "AuthenticationFailed",
    "access-control-allow-origin": "*",
    "access-control-expose-headers": "x-ms-request-id,x-ms-error-code,Content-Length,Date,Transfer-Encoding",
    "content-length": "544",
    "content-type": "application/xml",
    "date": "Fri, 29 Sep 2023 17:49:32 GMT",
    "server": "Microsoft-HTTPAPI/2.0",
    "x-ms-request-id": "7cc4e6ab-501e-0019-43fd-f24a0a000000",
    "message": "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:7cc4e6ab-501e-0019-43fd-f24a0a000000\nTime:2023-09-29T17:49:33.4940864Z",
    "code": "AuthenticationFailed",
    "AuthenticationErrorDetail": "Signature not valid in the specified time frame: Start [Wed, 21 Jun 2023 18:05:17 GMT] - Expiry [Fri, 29 Sep 2023 02:05:17 GMT] - Current [Fri, 29 Sep 2023 17:49:33 GMT]"
  }
}

### Steps to Reproduce

1. Launch
2. Open blob container
3. error

### Actual Experience

can not have access datalake

**Comment by JasonYeMSFT** [comment]
@markwanghfc Have you looked at your firewall settings to see if that's the cause of the issue? The error messages suggests:

"This storage account's 'Firewalls & virtual networks' settings may be blocking access to storage services. Try adding your client IP address to the firewall exceptions, or by allowing access from 'all networks' instead of 'selected networks'. To learn more about Azure Storage firewalls and virtual networks, visit http://go.microsoft.com/fwlink/?LinkId=845443."

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.

If you're still encountering this issue, we recommend opening an Azure support ticket via the Azure portal. Alternatively you can open a new issue here. This issue will no longer be monitored.
