### ISSUE TITLE
Microsoft azure storage explorer

### ISSUE THREAD

**Issue by marcelomayor** [microsoft/AzureStorageExplorer#7348]
Cant upload files, with this error: {
  "message": "\"UnexpectedCancel\""
}
I tree all, but nothing. I dont`t what. Someone can SOS ?

**Comment by craxal** [comment]
@marcelomayor Can you provide all of the information outlined in our standard [bug template](https://github.com/microsoft/AzureStorageExplorer/issues/new?assignees=&labels=&projects=&template=bug_report.yml)?

Also, please tell us what you are connecting to (blob container, file share, etc.) and how (sign in, account name and key, SAS, etc.). Also tell us if you have special network conditions, such as working behind a proxy server.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.

If you're still encountering this issue, we recommend opening an Azure support ticket via the Azure portal. Alternatively you can open a new issue here. This issue will no longer be monitored.
