### ISSUE TITLE
Deleting a blob freezes ASE and have to force quit

### ISSUE THREAD

**Issue by dfibuch** [microsoft/AzureStorageExplorer#735]
**Storage Explorer Version**: 1.4.2 build 20180917.1
**Platform/OS Version**:  Windows 10
**Architecture**: ia32
**Regression From**: Yes but can't remember what version

#### Steps to Reproduce: ####
1. Open the storage account you want to use
2. Open the blob so that you can see the list of folders in the main screen
3. Right click on the folder -> Delete -> Delete (not Soft Delete)

#### Expected Experience: ####
I expect for the blob to be deleted and allow me to continue using the app

#### Actual Experience: ####
The blob is deleted but the app completely freezes and I have to kill it in Task Manager

**Comment by dfibuch** [comment]
UPDATE: This only seems to happen when performing a delete or rename of a folder inside the blob container of a **classic** storage account. It works fine on the new types. Confirmed the problem with my colleague on another machine.

**Comment by MRayermannMSFT** [comment]
@JakeRadMSFT , let's make sure that this works with the delete rewrite we're doing for RBAC.

**Comment by MRayermannMSFT** [comment]
I believe we fixed this problem since you opened this issue. Please open a new issue if you are still having problems.

**Comment by dfibuch** [comment]
Yup, just tested latest version and it works. Cheers all!
