### ISSUE TITLE
More entry points for View All blob containers (and others)

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#7354]
Right now, the only way to open a blob container explorer is to turn on the View All setting, expand a Blob Containers node, scroll to the bottom of the node list, and then click "View all". Having more entry points for the explorer would be beneficial.

Ideas:
* Default action when clicking the Blob Containers node.
* "View all" context menu for the Blob Containers node.

**Comment by craxal** [comment]
> Default action is expand/collapse

By "default action", I mean something for single-click. Single-clicking leaf nodes opens a temporary tab for that node, so doing that for parent nodes that support explorer views should do likewise.

Double-clicking to expand the node is fine, but we may want to reconsider for consistency reasons, since double-clicking leaf nodes opens a permanent tab.

**Comment by MRayermannMSFT** [comment]
If user feedback is given to support the change, I'm not opposed to it. Until then, I'm worried about the change disrupting expectations about what clicking (even single clicking) normally does.
