### ISSUE TITLE
Some message dialogs have odd ordering of statements or wording 

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#7359]
Message dialogs should pose the question for which they need user input upfront. Any additional details, such as the effect of the user's choice, should follow later.

For example, the Acquire and Break Lease messages awkwardly state the consequences of proceeding then ask "Continue?" at the end. They should instead say something more like:

> Are you sure you want to...?
>
> This will...

However, some messages state why user input is needed or have contextual information needed to understand the question. Trying to reword these kinds of messages so that this information appears as part of the question or after it would be awkward and therefore should _not_ be given after the question.

For example, the following message is perfectly valid, because the leading statement gives necessary context to the question:

> A file with the name 'file.txt' already exists. Do you want to overwrite it?

```[tasklist]
### Messages to Fix
- [x] Activities Running on Quit
- [x] Blob: Acquire Lease
- [x] Blob: Break Lease
- [x] Blob: Delete Container
- [x] Blob: Promote Snapshot
- [x] Blob: Promote Version
- [x] Blob: Undelete
- [x] File: Delete Fileshare
- [x] File: Restore Snapshot
- [x] Queue: Delete Queue
- [x] Queue: Clear
- [x] ~~AzCopy: Check Copy Features~~
- [x] ~~AzCopy: Check Delete Features~~
- [x] Table: Delete Table
```

**Comment by MRayermannMSFT** [comment]
@craxal for this issue please:
1. Identify all other dialogs which need work
2. Add them to the task list above
3. Share list with team, at which point we can decide if we want to create and assign issues for 1.33, 1.34, or some other milestone/s

**Comment by craxal** [comment]
The guidelines I've outlined are admittedly more of a heuristic than a hard rule. Every message is different, so feel free to discuss ideas or concerns.

**Comment by craxal** [comment]
The messages for "AzCopy: Check Copy Features" and "AzCopy: Check Delete Features" are complex enough that following the general guideline for message dialogs probably isn't applicable.
