### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by GitRameshHub** [microsoft/AzureStorageExplorer#7364]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.31.1

### Architecture

x64

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Unable to retrieve child resources

ProducerError:{
  "message": "{}"
}

### Steps to Reproduce

1. creating the storage account
2. Open Microsoft Azure Storage explorer

### Actual Experience

After creating the storage account, when opened the Microsoft Azure Storage explorer. I received the below error.
Unable to retrieve child resources

ProducerError:{
  "message": "{}"
}

**Comment by craxal** [comment]
@GitRameshHub Can you provide any more details about the step you followed in order to reproduce the issue? How are you connecting to the storage account (sign-in, connection string, SAS, etc.). Which storage resources are you trying to work with?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.

If you're still encountering this issue, we recommend opening an Azure support ticket via the Azure portal. Alternatively you can open a new issue here. This issue will no longer be monitored.
