### ISSUE TITLE
Cannot see storage account resources with subscriptions setup for @outlook.com address

### ISSUE THREAD

**Issue by larrywa** [Microsoft/AzureStorageExplorer#737]
**Storage Explorer Version**:  1.4.2
**Platform/OS Version**: Windows 10 Ent 1803
**Architecture**:  I have no idea what this means
**Regression From**: Yes, the previous version which I believe was 1.4.1

#### Steps to Reproduce: ####
1. Create a new outlook.com address
2. Use an Azure subscription from Azure Pass (one of the free ones)
3. Add that account in to the storage explorer. It will appear to connect but then you can only see the name of the account, ie, myaccount@outlook.com listed. Not storage resources.

#### Expected Experience: ####
I expect to be able to add, delete, browse blogs, tables etc.

#### Actual Experience: ####
See above

**Comment by MRayermannMSFT** [comment]
Hey @larrywa , who did you get your azure pass code from? I'd like to try this out for myself, but am having difficulty getting a code. So if the person who gave it to you works at MSFT I can message them directly. Thanks!

**Comment by MRayermannMSFT** [comment]
Also, are you able to see your subscription at portal.azure.com?

**Comment by larrywa** [comment]
Hi Matthew,

Seems the problem just corrected itself after a couple of restarts and reboots.

---------------------------------------------------------
Thanks!
larrywa

**Comment by MRayermannMSFT** [comment]
Cool. Sounds good. Closing issue.
