### ISSUE TITLE
Fail to upload items to one emulator blob container

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7382]
**Storage Explorer Version:** 1.32.0-dev (95)
**Build Number:** 20231008.1
**Branch:** main
**Platform/OS:** Windows 10
**Architecture:** x64
**Azurite Version:** 3.26.0
**How Found:** From running test cases
**Regression From:** Previous release (1.31.2)

## Steps to Reproduce ##

1. Install and run Azurite 3.26.0 -> Launch Storage Explorer.
2. Expand 'Emulator & Attached -> Storage Accounts -> (Emulator - Default Ports) (Key)' -> Blob Containers.
3. Create a blob container -> Try to upload one file.
4. Check whether succeeds to upload the file.

## Expected Experience ##
Succeed to upload the file.

## Actual Experience ##
Fail to upload the file.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/44ae7d3c-661a-4696-8fed-ae7026dfecdb)

## Additional Context ##
Here is the Azcopy log file:
[894e9487-16f1-2946-7c2f-dfc61d31cfee.log](https://github.com/microsoft/AzureStorageExplorer/files/12839921/894e9487-16f1-2946-7c2f-dfc61d31cfee.log)

**Comment by JasonYeMSFT** [comment]
We reverted to use the previous version of AzCopy. This issue should be resolved for now.

**Comment by v-xianya** [comment]
Verified this issue on the rel build 20231014.5. Fixed.

**Comment by v-kellyluo** [comment]
This issue reproduces on the build 20231020.6, so we are going to reopen it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/db9ac20b-5510-40b4-ba5e-964cef1c6a07)

**Comment by v-xianya** [comment]
Verified this issue on the rel build 20231021.1. Fixed.
