### ISSUE TITLE
无法检索子资源  ProducerError:{   "name": "Node Fetch Error",   "message": "getaddrinfo ENOTFOUND wecontactstg.blob.core.windows.net",   "stack": "Error: getaddrinfo ENOTFOUND wecontactstg.blob.core.windows.net\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26)",   "cause": {     "cause": {       "errno": -3008,       "code": "ENOTFOUND",       "syscall": "getaddrinfo",       "hostname": "wecontactstg.blob.core.windows.net"     }   },   "code": "ENOTFOUND",   "errno": -3008 }

### ISSUE THREAD

**Issue by zhwuhuang** [microsoft/AzureStorageExplorer#7383]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.31.1

### Architecture

x64

### Platform

Windows

### OS Version

win 11

### Bug Description

无法检索子资源

ProducerError:{
  "name": "Node Fetch Error",
  "message": "getaddrinfo ENOTFOUND wecontactstg.blob.core.windows.net",
  "stack": "Error: getaddrinfo ENOTFOUND wecontactstg.blob.core.windows.net\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26)",
  "cause": {
    "cause": {
      "errno": -3008,
      "code": "ENOTFOUND",
      "syscall": "getaddrinfo",
      "hostname": "wecontactstg.blob.core.windows.net"
    }
  },
  "code": "ENOTFOUND",
  "errno": -3008
}

### Steps to Reproduce

启动，打不开节点

### Actual Experience

![image](https://github.com/microsoft/AzureStorageExplorer/assets/57713119/7c0732e6-4a63-4b2f-b3cf-f9552bff0d66)
![image](https://github.com/microsoft/AzureStorageExplorer/assets/57713119/57e06b34-2cdf-47d3-abcc-301bc9463087)

**Comment by MRayermannMSFT** [comment]
@zhwuhuang 

1. Can you confirm that you the key connection string you used to connect your storage account is correct? Please double check the account name and the any endpoints in the connection string. Please also double check that the account itself still exists.
2. Are you able to access the containers in the storage account using a different a tool, on the same machine you are running storage explorer? For example, can you browse blobs in the portal, can you use AzCopy on the command line to upload or download a blob?
3. Finally, if all else fails, please try enabling System Proxy. You can do so via Settings (gear on the left hand size) -> Application -> Proxy -> select "System Proxy" in the dropdown.

**Comment by kiriokiritai** [comment]
Have the exact same issue:
1. Yes. key connection string is correct.
2. Can map the share from Windows just fine.
3. Didn't help.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.

If you're still encountering this issue, we recommend opening an Azure support ticket via the Azure portal. Alternatively you can open a new issue here. This issue will no longer be monitored.
