### ISSUE TITLE
can't used the sftp in storage explorer

### ISSUE THREAD

**Issue by kimfern18** [microsoft/AzureStorageExplorer#7388]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.28.1

### Architecture

i86

### Platform

Windows

### Bug Description

Unable to retrieve child resources.

Details:
{
  "name": "Error",
  "message": "Unable to perform operation 'FileServiceClient.listSharesSegment'. No suitable credentials provided.",
  "stack": "Error: Unable to perform operation 'FileServiceClient.listSharesSegment'. No suitable credentials provided.\n    at FileServiceClient.runOperation (C:\\Users\\kimberly.fernandez\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:493698)\n    at FileServiceClient.listSharesSegment (C:\\Users\\kimberly.fernandez\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:32999)\n    at FileShareNodeProducer.produceFileShareNodes (C:\\Users\\kimberly.fernandez\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:64388)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Azure.Storage.FileShareProducer.produceFileShareNodes (C:\\Users\\kimberly.fernandez\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:88272)\n    at async Provider.executeOperation (C:\\Users\\kimberly.fernandez\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\providers\\Provider.js:28:16)\n    at async NodeProcessHostProxy._handleExecuteRequest (C:\\Users\\kimberly.fernandez\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:229:31)\n    at async NodeProcessHostProxy._handleMessage (C:\\Users\\kimberly.fernandez\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:182:24)\n    at async C:\\Users\\kimberly.fernandez\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:65:17"
}

### Steps to Reproduce

1. Launch the storage explorer 
2. click the file Shares

### Actual Experience

Unable to retrieve child resources.

Details:
{
  "name": "Error",
  "message": "Unable to perform operation 'FileServiceClient.listSharesSegment'. No suitable credentials provided.",
  "stack": "Error: Unable to perform operation 'FileServiceClient.listSharesSegment'. No suitable credentials provided.\n    at FileServiceClient.runOperation (C:\\Users\\kimberly.fernandez\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:493698)\n    at FileServiceClient.listSharesSegment (C:\\Users\\kimberly.fernandez\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:32999)\n    at FileShareNodeProducer.produceFileShareNodes (C:\\Users\\kimberly.fernandez\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:64388)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Azure.Storage.FileShareProducer.produceFileShareNodes (C:\\Users\\kimberly.fernandez\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:88272)\n    at async Provider.executeOperation (C:\\Users\\kimberly.fernandez\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\providers\\Provider.js:28:16)\n    at async NodeProcessHostProxy._handleExecuteRequest (C:\\Users\\kimberly.fernandez\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:229:31)\n    at async NodeProcessHostProxy._handleMessage (C:\\Users\\kimberly.fernandez\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:182:24)\n    at async C:\\Users\\kimberly.fernandez\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:65:17"
}

### Expected Experience

Unable to retrieve child resources.

Details:
{
  "name": "Error",
  "message": "Unable to perform operation 'FileServiceClient.listSharesSegment'. No suitable credentials provided.",
  "stack": "Error: Unable to perform operation 'FileServiceClient.listSharesSegment'. No suitable credentials provided.\n    at FileServiceClient.runOperation (C:\\Users\\kimberly.fernandez\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:493698)\n    at FileServiceClient.listSharesSegment (C:\\Users\\kimberly.fernandez\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:32999)\n    at FileShareNodeProducer.produceFileShareNodes (C:\\Users\\kimberly.fernandez\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:64388)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Azure.Storage.FileShareProducer.produceFileShareNodes (C:\\Users\\kimberly.fernandez\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-file-extension\\dist\\src\\index.js:2:88272)\n    at async Provider.executeOperation (C:\\Users\\kimberly.fernandez\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\providers\\Provider.js:28:16)\n    at async NodeProcessHostProxy._handleExecuteRequest (C:\\Users\\kimberly.fernandez\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:229:31)\n    at async NodeProcessHostProxy._handleMessage (C:\\Users\\kimberly.fernandez\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:182:24)\n    at async C:\\Users\\kimberly.fernandez\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:65:17"
}

**Comment by JasonYeMSFT** [comment]
@kimfern18 Could you go to Azure Portal and check if your user account has the permission to list storage account keys?

**Comment by jairus1988** [comment]
Send payment

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.

If you're still encountering this issue, we recommend opening an Azure support ticket via the Azure portal. Alternatively you can open a new issue here. This issue will no longer be monitored.
