### ISSUE TITLE
There is a failed activity log telling an error 'UnexpectedCancel' when promoting one blob version

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7389]
**Storage Explorer Version**: 1.32.0-dev (93)
**Build Number**: 20231011.6
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.0(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test case
**Regression From**: Previous release (1.31.0)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers. (Make sure blob versioning is enabled)
2. Create a blob container -> Upload one blob -> Modify its properties to generate a blob version.
3. Go to the blob version mode -> Right click the blob version.
4. Click 'Promote Version'.
5. Check whether there is a successfully activity log.

## Expected Experience ##
There is a successfully activity log.

## Actual Experience ##
There is a failed activity log.

Error:
`{
  "message": "\"UnexpectedCancel\""
}`
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/71f4fd13-23de-422f-b27a-e5c70de8eb48)

Here is the AzCopy Log:
[2741b5dc-f136-1646-5195-5dddff64da33.log](https://github.com/microsoft/AzureStorageExplorer/files/12866998/2741b5dc-f136-1646-5195-5dddff64da33.log)

## Additional Context ##
The current version displays after manually refreshing.

**Comment by JasonYeMSFT** [comment]
This reveals a mysterious issue of AzCopy. In AzCopy log and command line output, the operation is successfully done but AzCopy somehow reports a "Canceled" status.

**Comment by v-xianya** [comment]
Verified this issue on the rel build 20231014.5. Fixed. So, we are going to close it.
