### ISSUE TITLE
Azure Storage Explorer is going not responding while working after update 1.4.2

### ISSUE THREAD

**Issue by MoizeNU** [Microsoft/AzureStorageExplorer#739]
**Storage Explorer Version**: 
**Platform/OS Version**: 
**Architecture**: 
**Regression From**: 

#### Steps to Reproduce: ####
1. 
2.

**Comment by ngueyo** [comment]
The same problem here:

Storage Explorer Version:  1.4.2
Platform/OS Version: Ubuntu 16.04
Architecture:  x64
Regression From: Fresh Install

Actual Experience: After enter credencial, just stock on waiting for authentication

**Comment by MRayermannMSFT** [comment]
@MoizeNU , at what point does Storage Explorer not respond?

**Comment by ngueyo** [comment]
For me, i upgraded to "Runtime .NET Core 2.0.9" and everything works fine now. i can loggin and make transactions.

**Comment by MRayermannMSFT** [comment]
Awesome, glad you got it working.
