### ISSUE TITLE
Install Now for updates is opening a web browser instead of doin the update

### ISSUE THREAD

**Issue by GaryHayMSFT** [microsoft/AzureStorageExplorer#7390]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.1

### Architecture

x64

### Platform

Windows

### OS Version

Windows 11

### Bug Description

Previous releaes of ASE prompted to Install a new update Now or when the app is closed. 
Click on the Install Now button used to download the latest release and start installing the update.
This now links to the Azure Storage Explorer homepage where the user has to mess around downloading a new version manually.

### Steps to Reproduce

Check for Updates, click on Install Now

### Actual Experience

Previous releaes of ASE prompted to Install a new update Now or when the app is closed. 
Click on the Install Now button used to download the latest release and start installing the update.
This now links to the Azure Storage Explorer homepage where the user has to mess around downloading a new version manually.

### Expected Experience

Click on Install Now should, Install Now and not take the user to a website.

**Comment by JasonYeMSFT** [comment]
@GaryHayMSFT I cannot reproduce this issue on my end. Could you check if you accidentally disabled auto download in Settings > Application >Auto Download Updates?

**Comment by GaryHayMSFT** [comment]
Yes this was the issue. However I have never unticked this, so not sure why this setting changed or didnt persist across many previous updates.

**Comment by jairus1988** [comment]
Send payment
