### ISSUE TITLE
There is no refresh notification when executing actions in one file share/table with 'Auto Refresh On Change' disabled

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7393]
**Storage Explorer Version:** 1.32.0-dev (95)
**Build Number: 2**0231012.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.0(Apple M1 Pro)
**Architecture:** x64/x64/x64
**How Found:** From running test case
**Regression From:** Previous release (1.31.2)

## Steps to Reproduce ##

1. Expand one storage account -> File Shares. (Make sure 'Auto Refresh On Change' is disabled)
2. Open one file share -> Upload one file.
3. Check whether there is a refresh notification.

## Expected Experience ##
There is a refresh notification.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/acd4c41a-c701-45df-8ba3-cc61657324f1)

## Actual Experience ##
There is no refresh notification.

## Additional Context ##

1. This issue also reproduces for tables.
2. This issue doesn't reproduce for blob containers/disks.

**Comment by v-xianya** [comment]
Verified this issue on the rel build 20231014.5. Fixed.
