### ISSUE TITLE
Both the uploaded folder 'MicrosoftAzureStorageExplorer' and its parent folder show on the current container's editor

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#740]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: MacOS High Sierra
**Architecture**: x64
**Build Number**: 20181003.1
**Commit**: a8750d65
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Make sure Experimental feature is enabled.
2. Download and extract the 'StorageExplorer-darwin-x64.zip' to Desktop, then try to upload the extracted folder to one blob container.
3. Refresh the editor then check the result.

#### Expected Experience: ####
Only the uploaded folder shows on the current editor.

#### Actual Experience: ####
Both the uploaded folder and its parent folder show on the container's editor.
![parent](https://user-images.githubusercontent.com/34729022/46601837-f910a180-cadd-11e8-8685-95241b828755.png)
#### More info: ####
1. This issue doesn't reproduce when attempting to upload other local folders.
2. The percentage number stuck at 99% the failed.

**Comment by v-xianya** [comment]
This issue has been fixed on build 20191127.2. So we close it.
