### ISSUE TITLE
There is an extra action 'Manage Versions' after clicking 'Manage History' on the toolbar against one ADLS Gen2 blob explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7403]
**Storage Explorer Version**: 1.32.0-dev (95)
**Build Number**: 20231013.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.0(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test case
**Regression From**: Previous release (1.31.2)

## Steps to Reproduce ##
1. Turn on the "Enable ADLS Gen2 Snapshots (Preview)" setting.
2. Expand one storage account -> Blob Containers.
3. Open one blob container -> Observe the toolbar.
4. Click 'Manage History'.
5. Check whether there is only one action 'Manage Snapshots'.

## Expected Experience ##
There is only one action 'Manage Snapshots'.
 
## Actual Experience ##
There is an extra action 'Manage Versions'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/8b6a66a4-9667-4796-951e-b327030da1fb)

**Comment by craxal** [comment]
@v-xianya I'm not able to reproduce with my own ADLS Gen2 container. Are you sure it's an ADLS Gen2 container? Perhaps you can provide a link to a container that does reproduce for you?

**Comment by craxal** [comment]
Scratch that. I was able to reproduce after turning on "Enable ADLS Gen2 Snapshots (Preview)".

**Comment by v-xianya** [comment]
Verified this issue on the rel build 20231014.5. Fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/4734906b-ceef-4a4a-b9d5-293bbb5a7546)
