### ISSUE TITLE
No context menu displays for the focused top column grid on the view all containers explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7404]
**Storage Explorer Version**: 1.32.0-dev (95)
**Build Number**: 20231013.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.0(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Right click 'Blob Containers' node.
2. Click 'View All' -> The view all containers explorer opens.
3. Focus on the top column grid -> Right click it or press 'Ctrl+5'.
4. Check whether a context menu displays.

## Expected Experience ##
 A context menu displays.
 
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/cda15bdc-f46b-4637-a3b1-deb58064674b)

## Actual Experience ##
No context menu displays.

**Comment by MRayermannMSFT** [comment]
Customizing columns is currently not available for this explorer.
