### ISSUE TITLE
SSLV3_ALERT_HANDSHAKE_FAILURE

### ISSUE THREAD

**Issue by StokholmENDK** [microsoft/AzureStorageExplorer#7406]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.26

### Architecture

x64

### Storage Explorer Build Number

20230609.2

### Platform

Windows

### OS Version

Windows 10 Enterprise

### Bug Description

When opening a container i get the following error message.

```
Unable to retrieve child resources

ProducerError:{
  "name": "FetchError",
  "message": "request to https://dpcontainerdev.blob.core.windows.net/?comp=list&include=metadata failed, reason: write EPROTO 8972160:error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE:..\\..\\third_party\\boringssl\\src\\ssl\\tls_record.cc:592:SSL alert number 40\n",
  "stack": "FetchError: request to https://dpcontainerdev.blob.core.windows.net/?comp=list&include=metadata failed, reason: write EPROTO 8972160:error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE:..\\..\\third_party\\boringssl\\src\\ssl\\tls_record.cc:592:SSL alert number 40\n\n    at ClientRequest.<anonymous> (C:\\Program Files\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\blob-extension\\dist\\src\\index.js:2:2834516)\n    at ClientRequest.emit (node:events:513:28)\n    at TLSSocket.socketErrorListener (node:_http_client:502:9)\n    at TLSSocket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
  "type": "system",
  "errno": "EPROTO",
  "code": "EPROTO"
}
```

### Steps to Reproduce

1. Launch Storage Explorer
2. Confirm account is logged in.
3. Open Storage Accounts
4. Open Any Storage Account
5. Open Blob Containers 
6. Error message appears.

### Actual Experience

![image](https://github.com/microsoft/AzureStorageExplorer/assets/119044770/29589fd6-767f-4712-8b7f-59d07c3bbd56)

### Expected Experience

Expected Blob Contains to open and being able to view th containers.

### Additional Context

Encountered the issue in version 1.26. It had been working for a long while, 6 month+.
After the error i tried upgrading to v.1.30.0, but the error is still there.

I am not connected through a proxy,
The subsciptions are from Azure AD account which is signed correctly, with out errors.

**Comment by MRayermannMSFT** [comment]
@StokholmENDK if this suddenly started happening without any obvious change in storage explorer, then likely this is going to be something broken in your environment. All the same, you can try enabling system proxy by going to Settings (gear on the left) > Application > Proxy > choose "System proxy" in the dropdown.

**Comment by StokholmENDK** [comment]
Think i found the issue, there were mulitiple versions installed on the machine. Had v. 1.19 + 1.26 + 1.30 installed at the same time. I uninstalled all of them and re installed 1.30. Then i worked.
