### ISSUE TITLE
Copy/Paste creates empty blobs

### ISSUE THREAD

**Issue by VladM-L** [Microsoft/AzureStorageExplorer#741]
**Storage Explorer Version**: 1.4.2
**Platform/OS Version**: Windows 10
**Architecture**: ia32
**Regression From**: definitely used to work, not sure when stopped

#### Steps to Reproduce: ####
1. Find a blob you want to copy to somewhere else, select it and click 'Copy' button
2. Find location where you want to paste it to, select it and click 'Paste' button
3. It usually fails the first time with 400 InvalidHeaderValue "Copy failed when reading the source." (0 B of 966 B copied) 
4. After I hit retry, it shows like it copied successfully, but the resulting blob is empty
That is what I get when trying to copy/paste from Azure blob location to local storage location. 
When I try to do the same in the opposite direction on step 3 I get  The specified resource does not exist. RequestId:97d06119-f01e-00e5-290e-5f030f000000 Time:2018-10-08T13:55:42.6149545Z
Downloading and uploading works fine in either case.

#### Expected Experience: ####
I expect blobs being copied, of course

#### Actual Experience: ####
see above

**Comment by VladM-L** [comment]
Also to add, copy/paste between two remote containers seems fine. The problem seems to show up only when local storage emulator is involved. I am running Windows Azure Storage Emulator 5.6.0.0.

**Comment by craxal** [comment]
Bug is getting stale, and we've updated several times since 1.4.2. If copy and paste still isn't working, you might want to enable Experimental/AzCopy features. If you continue to experience this issue, please provide additional info.
