### ISSUE TITLE
The existing entities disappear if type '1' in 'Text editor' then execute query

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7410]
**Storage Explorer Version**: 1.32.0-dev (95)
**Build Number**: 20231014.5
**Branch**: rel/1.32.0
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.0(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test case
**Regression From**: Previous release (1.31.2)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create one table -> Add one entity.
3. Click 'Query' -> Remove the existing clauses.
4. Open 'Text editor' -> Type '1' into the editor -> Execute query.
5. Check whether the entity shows well.

## Expected Experience ##
 The entity shows well.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/c34ec59f-c275-4faa-a248-cb3c220a3503)

## Actual Experience ##
The entity disappears.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/249e5ff2-fe09-4d6b-858f-7a6e6c0f11f2)

**Comment by craxal** [comment]
As per other work items, the changing the query should do _nothing_ to the list of entities until the Run Query button is clicked. Will look into a fix.
