### ISSUE TITLE
File Explorer: prefix clearing issues when navigating via address var

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#7416]
Regression from: 1.31.2

Repro steps:
1. Open file explorer
2. Go into folder
3. Filter by prefix
4. Navigate back to root via bread crumb
Expected: text box is cleared, no prefix is applied to root folder
Actual: text box is never cleared, prefix is sometimes applied to root folder

Desired outcome: emulate same behavior as either:
- File explorer in 1.31.2
- Blob explorer in 1.31.2/1.32.0 (should be same behavior in both versions, difference from file  explorer in 1.31.2 is that the file explorer adds a "filtered directory" location into the history, while the blob explorer appears to just be modifying the current location in place, aka, not adding an additional location into history)

**Comment by craxal** [comment]
Will match blob behavior.
