### ISSUE TITLE
Tag Query Filter missing blob information in results

### ISSUE THREAD

**Issue by cjstremick** [microsoft/AzureStorageExplorer#7418]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.31.2

### Architecture

x64

### Storage Explorer Build Number

20231003.6

### Platform

Windows

### OS Version

Windows 11

### Bug Description

if I navigate to a blob container and filter by a tag, The results are property filtered, but only the Name and Status columns are provided.  Size, Access Tier, Last Modified and others are all blank.

### Steps to Reproduce

1. Launch storage explorer
2. Navigate to a storage account
3. Expand Blob Containers
4. Observe many blobs listed
5. Click the Filter Icon
6. Select "Tag Query" radio button
7. Provide a tag name and value
8. Click "Apply"
9. Observe that matching blobs are displayed
10. Observe that Blob Type, Access Tier, Last Modified, Size and other columns are blank

### Actual Experience

I can filter blobs by tags but I can only see the blob name.  I would like to see Last Modified and other fields so I knew which blobs are new.

### Expected Experience

I expect to see all the columns filled in, like they are if I perform a filter by Prefix (or no filter).

**Comment by JasonYeMSFT** [comment]
@cjstremick Unfortunately this is a service limitation. The tags filter results only include the blobs' name, container name and tags. https://learn.microsoft.com/en-us/rest/api/storageservices/find-blobs-by-tags?tabs=azure-ad
