### ISSUE TITLE
Fail to create IOT blob containers

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7422]
**Storage Explorer Version:** 1.32.0-dev (95)
**Build Number:** 20231017.4
**Branch:** rel/1.32.0
**Platform/OS:** Windows 10
**Architecture:** x64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer.
2. Connect to a blob storage module on edge using the connection string.
3. Switch to the attached storage account -> Blob Containers.
4. Try to create a blob container.
5. Check whether succeeds to create a blob container.

 
## Expected Experience ##
Succeed to create a blob container.

## Actual Experience ##
Fail to create a blob container.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/07ba6dac-9294-46c1-8550-98c056509db3)

## Additional Context ##

1. We didn't meet this issue in the previous version before, but it reproduces in 1.31.1 today.
2. An error dialog pops up when expanding Blob Containers node.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/b4ea1f1d-92a4-4131-8271-20d676309e72)

**Comment by MRayermannMSFT** [comment]
@jasonyemsft please investigate this for now, and you can determine if there's something we need to do for 1.32. However, given the lack of user complaint, if you think the work would best be deferred to 1.33, feel free to make such a recommendation.

**Comment by JasonYeMSFT** [comment]
@v-kellyuo I tried my IoT instance and it works on my end. Please share areproducing VM so I can investigate.

**Comment by v-kellyluo** [comment]
@JasonYeMSFT , I shared the VM on teams.

**Comment by JasonYeMSFT** [comment]
This is caused by the a network configuration issue and the failure of the IoT module. After fixing the IP address and restarting the IoT module it works as expected again.

**Comment by v-kellyluo** [comment]
This issue has been resolved now. So, we are going to close it.
