### ISSUE TITLE
remember azure user name

### ISSUE THREAD

**Issue by datadockery** [microsoft/AzureStorageExplorer#7423]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Each time I open storage explorer, it never remembers my user name

### Desired Solution

I would like to have it remember my account, then I only need to enter my password each time

**Comment by MRayermannMSFT** [comment]
@datadockery are you saying that you use sign in, and then have to sign in again after restarting, and you don't want to? 

Do you have sign out on exit enabled? Please check Settings (gear on the left hand side) > Application > Sign-In and check if Logout On Exit is checked. If it is checked, you can un check it so you don't have to sign in every time.

**Comment by datadockery** [comment]
Ok that worked for me

Thank you
