### ISSUE TITLE
Storage explorer UI does not provide a way to specify “include snapshots”.

### ISSUE THREAD

**Issue by v-priy** [microsoft/AzureStorageExplorer#7426]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Storage explorer UI does not provide a way to specify “include snapshots”.

### Desired Solution

While deleting blob from azure portal containers getting the popups to select delete blob snapshot.   and Storage Browser :While deleting blob from storage browser we are getting the popups to select delete blob snapshot.   But while deleting blob with snapshot we are not getting snapshot popups

### Alternatives and Workarounds

After Retry option we are getting dropdown to delete snapshot in azure storage explorer tool

### Additional Context

Need help with ETA when Storage explorer UI does provide a way to specify “include snapshots”, as azure portal UI provide.Please refer case no.2310130050002294 for more details.

**Comment by v-priy** [comment]
Hello Storage Explorer Team,

Hope you are doing well. 

We have a Unified customer who came up below ask :

Need help with ETA when Storage explorer UI does provide a way to specify “include snapshots”, as azure portal UI provide.

Service Request No.- 2310130050002294
Issue : Storage explorer UI does not provide a way to specify “include snapshots”.

Analysis/Investigation

We tried with all the 3 scenarios(Storage explorer, Azure Portal, and storage browser) to delete blob snapshot.
Scenario 1: Using Azure Storage Explorer.

Checked on storage explorer version 1.31.2 and 1.31.1 and getting the same error/warning message.
 
Step1: After deleting blob for which snapshot is created.
 
![image](https://github.com/microsoft/AzureStorageExplorer/assets/139970981/8a19d22d-ae78-47f6-a908-8f0060c153f7)

Step 2: Click on Retry getting dropdown to delete blobs with snapshots.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/139970981/4540f186-ee87-429c-964c-8732111574e9)

Step 3:Tried without changing settings i.e not selecting the below check box.
 
Get the same warning message 
 
Step 4: Tried with changing setting i.e. selecting check boxes get the same warning message.
 
 
![image](https://github.com/microsoft/AzureStorageExplorer/assets/139970981/6703befc-3802-4e0b-8dce-bf7ddcbcf179)


Scenario 2:  User Azure portal

While deleting blob from azure portal containers getting the popups to select delete blob snapshot.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/139970981/a828707e-ba94-440d-862f-d73441053813)

 
Scenario 3: Storage Browser

While deleting blob from storage browser getting the popups to select delete blob snapshot.

 
![image](https://github.com/microsoft/AzureStorageExplorer/assets/139970981/af68080d-b173-4035-8216-a78c6f8981c2)



Business justification: Customer is just using storage explorer tools to delete blob.
As per customer on azure storage explorer this is indeed a workaround, this cannot be the default flow for their engineers. We won’t expect from them to always have to first delete, wait until it skips, and then delete again, especially when we are working with large number of files, which means that the wait time can be quite considerable. As a said it is a fine, very temporary solution, cx would really like to have a better flow – for example similar to what’s in the azure portal. 

Ask:  Is that something that can be done? What would be the ETA?

**Comment by MRayermannMSFT** [comment]
This will only be offered for non-Gen2 containers. Adding this capability for Gen2 containers may come in a future release: https://github.com/microsoft/AzureStorageExplorer/issues/7442
