### ISSUE TITLE
Normalize design of search boxes in data explorers, settings UI, and tree view

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#7430]
Ensure consistent location of icons, size of icons, icon direction/type, padding, placeholder texts, etc. across data explorers.

Begin addressing this issue by:
1. Identify all search box UX elements
2. Propose a design that they should all be switched to, or at least the changes that need to be made to make them appear more uniform
3. Cost the work needed for each UX element
4. Share results with the team

```[tasklist]
## Tasks
- [x] Blob explorer side bar
- [x] Blob container explorer
- [x] File explorer
- [x] Settings panel
- [ ] Tree view
```

**Comment by craxal** [comment]
## Question
Where should the magnifying lens icon go?

## Answer
The magnifying lens icon should be aligned with the _left_ or _leading_ edge.

## Reasoning
The following applications/sites align the magnifying lens icon with the _left_ or _leading_ edge of either the input or placeholder text:
- Azure Portal
- GitHub
- Azure DevOps
- VS Code
- Microsoft 365

Somewhat unhelpfully, the following applications/sites align the magnifying lens icon with the _right_ or _trailing_ edge of wither the input or placeholder text:
- VisualStudio

**Comment by craxal** [comment]
Common component has been added to `ui-components`.

**Comment by craxal** [comment]
All UI components using search inputs now use the component from `ui-components` with one exception. The tree view is still in Knockout, and its search input is a little different from other search inputs. The magnifying lens icon is actually a clickable button in this case, so slight deviations from the styling are expected.
