### ISSUE TITLE
It is better to update the tooltip of 'Select All' button to 'Select All in Page' for table explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7434]
**Storage Explorer Version**: 1.32.0-dev (95)
**Build Number**: 20231019.3
**Branch**: rel/1.32.0
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Sonoma 14.0(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Open one table -> Hover on the 'Select All' button.
3. Check whether the tooltip is accurate.

## Expected Experience ##
The tooltip is accurate and shows 'Select All in Page'.

## Actual Experience ##
The tooltip is not accurate and shows 'Select all entities'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/aaa9b8d0-53f0-4622-86f2-ab381129f22e)

**Comment by MRayermannMSFT** [comment]
Fix availalbe build 20231020.6 or later.

**Comment by v-xianya** [comment]
Verified this issue on the build 20231020.6. Reproduce. So, we are going to re-open it.

**Comment by v-xianya** [comment]
Verified this issue on the rel build 20231021.1. The tooltip has been updated.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/01d25670-6d73-41e1-911b-04e6d20ad5c0)
