### ISSUE TITLE
The tooltip of the button 'Download' is not accurate for blob/file explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7435]
**Storage Explorer Version**: 1.32.0-dev (95)
**Build Number**: 20231019.3
**Branch**: rel/1.32.0
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Sonoma 14.0(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test case
**Regression From**: Previous release (1.31.2)

## Bug Descriptions ##
1. For blob container/file share explorer, the tooltips of the 'Download'/the triangle button for 'Select All' are not accurate.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/41d0d21a-fac6-4bd4-b3f4-d5469af6f39e)

2. For queue explorer, the tooltip of the 'Move' button is not accurate.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/61b29c78-97af-4fe6-8775-c0667d4a788e)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Open one blob container -> Hover on the 'Download' button.
3. Check whether the tooltip is accurate.

## Expected Experience ##
The tooltip is accurate.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/aae7c1b4-2727-4f17-a090-893fa4c46012)

## Actual Experience ##
The tooltip is not accurate.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/d0ccd437-155b-4f1b-b209-e0ec4451da58)

**Comment by MRayermannMSFT** [comment]
Fixes for blob, queue, and file available in 20231020.5 or later

**Comment by MRayermannMSFT** [comment]
Edit, build 20231020.6 or later.

**Comment by v-xianya** [comment]
Verified this issue on the rel build 20231020.6. Fixed.
