### ISSUE TITLE
Fail to delete one regular blob snapshot if check the option 'Also delete blob snapshots' in delete dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7437]
**Storage Explorer Version**: 1.32.0-dev (95)
**Build Number**: 20231019.3
**Branch**: rel/1.32.0
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Sonoma 14.0(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Create a snapshot for the blob -> Go to the snapshots view.
4. Select the snapshot -> Click 'Delete'.
5. Check the option 'Also delete blob snapshots' -> Click 'Yes'.
6. Check whether succeeds to delete the snapshot.

## Expected Experience ##
Succeed to delete the snapshot.

## Actual Experience ##
Fail to delete the snapshot.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/26d59b1f-75e0-4d6d-acd7-273e733416c9)

Here is the AzCopy log:
[5c0e1954-3e44-9643-73e6-a80b7ed0d261.log](https://github.com/microsoft/AzureStorageExplorer/files/13039239/5c0e1954-3e44-9643-73e6-a80b7ed0d261.log)

**Comment by MRayermannMSFT** [comment]
Checkbox no longer offered when deleting snapshots.

**Comment by MRayermannMSFT** [comment]
Fix available in 20231020.5 or later

**Comment by MRayermannMSFT** [comment]
Edit, build 20231020.6 or later.

**Comment by v-xianya** [comment]
Verified this issue on the rel build 20231020.6.
The checkbox ‘Also delete blob snapshots’ has been removed from the delete dialog for snapshots.
