### ISSUE TITLE
Fail to delete one ADLS Gen2 blob/snapshot if check the option 'Also delete blob snapshots' in delete dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7438]
**Storage Explorer Version**: 1.32.0-dev (95)
**Build Number**: 20231019.3
**Branch**: rel/1.32.0
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Sonoma 14.0(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Enable the setting 'Enable ADLS Gen2 Snapshots (Preview)'.
2. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Create a snapshot for the blob.
4. Select the blob -> Click 'Delete'.
5. Check the option 'Also delete blob snapshots' -> Click 'Yes'.
6. Check whether succeeds to delete the blob.

## Expected Experience ##
Succeed to delete the blob.

## Actual Experience ##
Fail to delete the blob.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/ec3b9cf5-191f-4fb3-8409-e13e4cea645c)

Error from AzCopy log:
`This operation is not permitted because the file has snapshots`
Here is the AzCopy log:
[96555b48-59f6-114a-6a87-cb973b327d5b.log](https://github.com/microsoft/AzureStorageExplorer/files/13039300/96555b48-59f6-114a-6a87-cb973b327d5b.log)

**Comment by MRayermannMSFT** [comment]
Checkbox no longer offered for gen2

**Comment by MRayermannMSFT** [comment]
Fix available in 20231020.5 or later

**Comment by MRayermannMSFT** [comment]
Edit, build 20231020.6 or later.

**Comment by v-xianya** [comment]
Verified this issue on the rel build 20231020.6. 
The checkbox ‘Also delete blob snapshots’ has been removed from the delete dialog for ADLS Gen2 blobs/snapshots.
