### ISSUE TITLE
It is better to always disable the 'Paste' action in the view all containers explorer for emulator blob containers

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7445]
**Storage Explorer Version**: 1.32.0-dev (95)
**Build Number**: 20231020.6
**Branch**: rel/1.32.0
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Sonoma 14.0(Apple M1 Pro)
**Architecture**: x64/x64/x64
**Azurite Version** 3.26.0
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Install and run Azurite 3.26.0.
2. Expand 'Emulator & Attached -> Storage Accounts -> (Emulator - Default Ports) (Key)'.
3. Right click the 'Blob Containers' node -> Click 'View All'.
4. Copy one blob container from another storage account.
5. Go to the view all containers explorer.
6. Check whether the 'Paste' action is disabled.

## Expected Experience ##
The 'Paste' action is disabled.

## Actual Experience ##
The 'Paste' action is enabled.

## Additional Context ##
1. There is a failed activity when pasting one non-empty blob container to the view all containers explorer.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/1d5dcd2f-f59f-469f-aacc-7a03a66c13d7)
2. The action 'Paste Blob Container' is always disabled.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/55f8c424-bc9a-4faf-96c0-9e4b13b0d7d7)

**Comment by MRayermannMSFT** [comment]
Paste is simply hidden now

**Comment by v-xianya** [comment]
Verified this issue on the rel build 20231021.1. The action 'Paste' is removed from the context menu.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/fc0dd59b-fc89-4d00-8d9a-aab33c5e4ded)
