### ISSUE TITLE
It is better to disable splitting multiple tabs for the 'View all containers' explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7446]
**Storage Explorer Version**: 1.32.0-dev (95)
**Build Number**: 20231020.6
**Branch**: rel/1.32.0
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Sonoma 14.0(Apple M1 Pro)
**Architecture**: x64/x64/arm64
**Azurite Version** 3.26.0
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account.
2. Right click the 'Blob Containers' node -> Click 'View All'.
3. Split the opened tab -> Split the opened tab again.
4. Check there is no new split tab.

## Expected Experience ##
There is no new split tab.

## Actual Experience ##
There is a new split tab.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/d1fa72da-286c-457d-966b-7a4300ff2cac)

**Comment by MRayermannMSFT** [comment]
The tab is no longer duplicated after splitting the split tab

**Comment by v-xianya** [comment]
Verified this issue on the rel build 20231021.1. Fixed.
