### ISSUE TITLE
Could not access resources for this tenant

### ISSUE THREAD

**Issue by ngruson** [microsoft/AzureStorageExplorer#7447]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.2

### Architecture

x64

### Storage Explorer Build Number

20231003.6

### Platform

Windows

### OS Version

Windows 11

### Bug Description

Hi,

I'm trying to access my subscriptions in Storage Explorer (freshly installed).
Initially, these are filtered out. I'm trying to unfilter them in the Account Management pane.
I've tried 2 different Azure tenants but each time I get the error 'Could not access resources for this tenant. You may need to reauthenticate' .
I've restarted Storage Explorer several times. I'm not using a proxy, but I configured 'Use system proxy' in the settings as it was suggested in a similar GitHub issue.

I can access my subscriptions in the Azure Portal just fine. I just created a storage account that I would like to work with in Storage Explorer.
Can you help out?

Here are the error details from the Storage Explorer log files:

```
[2023-10-20T07:57:45.837Z] (main:38612) <ERRO> API call for SubscriptionListingClient.listSubscriptions failed
  GET https://management.azure.com/subscriptions?api-version=2015-01-01 - 503
  Credential used: Auth token - accountId: 00000000-0000-0000-2eb0-aac65e55cd4e.9188040d-6c67-4c5b-b112-36a304b66dad:9CC2FC93E1FBA83A5E6B08C17028B6080A53EAA1598D0E099F72AA3ADB95A25C, tenantId: 235caa24-0e40-4b1e-b555-2adb08709271
  RequestId: , Date sent: Fri, 20 Oct 2023 07:57:45 GMT, ApiVersion: 2015-01-01, ProxySettings: undefined
  ErrorCode: ServerTimeout
[2023-10-20T07:57:45.837Z] (main:38612) <ERRO> Failed to list all/some subscriptions for account 00000000-0000-0000-2eb0-aac65e55cd4e.9188040d-6c67-4c5b-b112-36a304b66dad:9CC2FC93E1FBA83A5E6B08C17028B6080A53EAA1598D0E099F72AA3ADB95A25C, tenant 235caa24-0e40-4b1e-b555-2adb08709271, error: {
    "name": "Error",
    "message": "Failed to parse response body: {\"error\":{\"code\":\"ServerTimeout\",\"message\":\"The request timed out. Diagnostic information: timestamp '20231020T075745Z', subscription id '', tracking id '028d8840-0b49-4234-971e-7a21f8c7817c', request correlation id '028d8840-0b49-4234-971e-7a21f8c7817c'.\"}}",
    "stack": "Error: Failed to parse response body: {\"error\":{\"code\":\"ServerTimeout\",\"message\":\"The request timed out. Diagnostic information: timestamp '20231020T075745Z', subscription id '', tracking id '028d8840-0b49-4234-971e-7a21f8c7817c', request correlation id '028d8840-0b49-4234-971e-7a21f8c7817c'.\"}}\n    at sendRequestAndParseResponse (C:\\Users\\ngrus\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\AzureSubscriptions\\SubscriptionLister.js:122:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async SubscriptionLister.listSubscriptions (C:\\Users\\ngrus\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\AzureSubscriptions\\SubscriptionLister.js:33:36)\n    at async SubscriptionListingClient.runOperation (C:\\Users\\ngrus\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\azure-sdk-helpers\\dist\\src\\CoreRest\\CoreRestClient.js:110:24)\n    at async SubscriptionService._getAccountSubscriptionsForTenants (C:\\Users\\ngrus\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\AzureSubscriptions\\SubscriptionService.js:42:49)\n    at async SubscriptionService.getTenantSubscriptions (C:\\Users\\ngrus\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\AzureSubscriptions\\SubscriptionService.js:24:16)\n    at async AzureSubscriptionsManager.getAccountSubscriptions (C:\\Users\\ngrus\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\AzureSubscriptions\\AzureSubscriptionsManager.js:27:22)\n    at async Provider.executeOperation (C:\\Users\\ngrus\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\providers\\Provider.js:28:16)\n    at async ElectronMainHost.executeOperation (C:\\Users\\ngrus\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\ElectronMainHost.js:25:20)\n    at async ElectronRendererProviderProxy._handleExecuteRequest (C:\\Users\\ngrus\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\ElectronRendererProviderProxy.js:145:31)\n    at async ElectronRendererProviderProxy._handleMessage (C:\\Users\\ngrus\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\ElectronRendererProviderProxy.js:107:24)\n    at async IpcMainImpl.<anonymous> (C:\\Users\\ngrus\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\ElectronRendererProviderProxy.js:28:21)"
  }
```

### Steps to Reproduce

1. Launch Storage Explorer
2. Add a filtered subscription from the Account Management pane.

### Actual Experience

I click on the cog and click the 'Un-filter' button.

![image](https://github.com/microsoft/AzureStorageExplorer/assets/3188323/a6ca6da6-4f5d-40a2-9a8c-a66bec57cbcd)

Then it's trying to load the subscriptions for the tenant which fails after a couple of seconds.

![image](https://github.com/microsoft/AzureStorageExplorer/assets/3188323/28571c36-fac2-405b-8fe4-bf59909ef183)

**Comment by MRayermannMSFT** [comment]
Hi @ngruson it looks like Storage Explorer reached the server but then got a 503. So in this case can:
1. You try again in a few hours (which should be by now)
2. Try signing out and sign back in
3. If after all that you're still getting errors, then open a support ticket from the Azure portal

**Comment by ngruson** [comment]
I logged out in the Azure portal and logged in again.
Then started Storage Explorer and now it works!

**Comment by MRayermannMSFT** [comment]
Great. Glad you got unblocked. I think there was an quick Azure incident about 8-10 hours ago, so that lines up with your issue. Thanks for the patience.
