### ISSUE TITLE
The 'Prefix' option is selected in the split tab when the 'Tag Query' is applied in the original tab

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7455]
**Storage Explorer Version:** 1.32.0 (95)
**Build Number:** 20231025.1
**Branch:** rel/1.32.0
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Sonoma 14.0(Apple M1 Pro)
**Architecture:** x64/x64/arm64
**How Found:** From running test cases
**Regression From:** Previous release (1.30.2)

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Open one blob container -> Open show view options panel.
3. Select 'Tag Query' option -> Click 'Apply'.
4. Split the tab -> Open show view options panel.
5. Check whether the 'Tag Query' option is selected.

## Expected Experience ##
The 'Tag Query' option is selected.

## Actual Experience ##
The 'Prefix' option is selected.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/ea452a69-6e1e-4544-99c4-8c4afd14a507)

**Comment by JasonYeMSFT** [comment]
@v-kellyluo The filter option and the entries in the tag query section doesn't have to match the current view since it is separately applied. We don't need to fix this in 1.32.0 but we can consider fixing it in 1.33.0.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20231103.1. Fixed. So, we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/7e80be78-7810-4b29-84dd-946274045d83)
