### ISSUE TITLE
cannot have folder statistics after upgrade ! (worked fine before  ..) 

### ISSUE THREAD

**Issue by denistarkett** [microsoft/AzureStorageExplorer#7456]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.31.2

### Regression From

1.26.1

### Architecture

i86

### Storage Explorer Build Number

94

### Platform

All

### OS Version

Windows 2019 Version 1809 OS BUIld 17763.4974

### Bug Description

After successfull connection to  a storage account ( we can browse ) 
The usage of the folder Statistics button on a Blob containers lead to an error 

Strangely it was working fine and a message made me aware that there was a new version after upgrading I get the error doinf the same thing..

Also the previous version was 32 bits on x64 architecture  .. the new one is  both  64 bits .. 

### Steps to Reproduce

1. Expand the storage account -> Blob Containers.
2. Open a blob container -> Click 'Folder Statistics' on the toolbar.
3. Check whether there is a successful activity log.

### Actual Experience

it runs for seconds withoud doing anything and finish with the following error 

Failed to inspect '', error: {
  "name": "RestError",
  "message": "Value for one of the query parameters specified in the request URI is invalid.\nRequestId:184263be-501e-003b-5c5c-077488000000\nTime:2023-10-25T15:59:06.9262458Z",
  "stack": "RestError: Value for one of the query parameters specified in the request URI is invalid.\nRequestId:184263be-501e-003b-5c5c-077488000000\nTime:2023-10-25T15:59:06.9262458Z\n    at handleErrorResponse (C:\\Program Files\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\blob-extension\\dist\\src\\index.js:2:412653)\n    at C:\\Program Files\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\blob-extension\\dist\\src\\index.js:2:413337\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async StorageRetryPolicy.attemptSendRequest (C:\\Program Files\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\blob-extension\\dist\\src\\index.js:2:1076967)\n    at async BlobApiVersionRequestPolicy.sendRequest (C:\\Program Files\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\blob-extension\\dist\\src\\index.js:2:70658)\n    at async StorageClientContext.sendOperationRequest (C:\\Program Files\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\blob-extension\\dist\\src\\index.js:2:451439)\n    at async ContainerClient.listBlobFlatSegment (C:\\Program Files\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\blob-extension\\dist\\src\\index.js:2:1223099)",
  "code": "InvalidQueryParameterValue",
  "statusCode": 400,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://stnnprdsap1opentextacrw.blob.core.windows.net/sap-a3?comp=list&maxresults=25&restype=container&include=deleted,metadata,snapshots",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2017-04-17"
        },
        "accept": {
          "name": "Accept",
          "value": "application/xml"
        },
        "user-agent": {
          "name": "User-Agent",
          "value": "Microsoft Azure Storage Explorer/1.31.2 (win32) azsdk-js-storageblob/12.12.0 (NODE-VERSION v18.15.0; Windows_NT 10.0.17763)"

### Expected Experience

successfull activty log :-)

**Comment by JasonYeMSFT** [comment]
@denistarkett Did you enable targeting Azure Stack? In the error log the API version is 2017-04-17. If so, could you please disable it? The latest Storage Explorer targets a much more recent API version and sends HTTP headers not supported in the old API version.

**Comment by dmakeyman** [comment]
ok , I just click on the submenu "Edit" , change "Target Azure Stack APIs" , it changes something ( not clearly explained) and ask to restart and then it works again .. so in a way thanks ! :-)

I'm not sure if it is the button to enable/disable .. ( not visible either way )
