### ISSUE TITLE
The data grid will not be focused if uncheck the top order column against ADLS Gen2/blob/file/queue/table explorers

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7459]
**Storage Explorer Version**: 1.32.0-dev (95)
**Build Number**: 20231025.1
**Branch**: rel/1.32.0
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Sonoma 14.0(Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: AD-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Right click the 'Name' column and select 'Customize Columns...'.
4. Uncheck 'Name' column -> Click 'OK'.
5. Reopen the blob container.
6. Check whether the data grid is focused.

## Expected Experience ##
The data grid is focused.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/e5657f36-3717-42b4-9cd3-6e18815bc741)

## Actual Experience ##
The data grid is not focused.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/fd95b49b-1a94-4511-be73-806929b3e399)

## Additional Context ##
This issue doesn't reproduce if move one of the visible columns to top.

**Comment by craxal** [comment]
@v-xianya Step 5 says to reopen the container. Did you close the container after clicking OK? If that's true, I can't reproduce. Or are you referring to the fact that focus is lost right after the dialog closes?

**Comment by v-xianya** [comment]
@craxal This issue reproduces whether the original container explorer is closed or not.
To reproduce this issue, we must uncheck the top visible column on the 'Column Options' dialog.
If select one column that is not the top visible one, this issue will not be reproduced.
Here is the record:

![0125](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/f944d124-8015-4ff5-8719-b1659217334a)

**Comment by v-xianya** [comment]
@craxal Verified this issue on the main build 20240130.3. 
Fixed for file shares/queues/tables. 
Reproduce for ADLS Gen2 /regular blob containers. So, we are going to reopen this issue.

**Comment by craxal** [comment]
Changes have now been merged for blobs.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240130.14. Fixed for blobs. So, we are going to close this issue.
