### ISSUE TITLE
Context menu that opened by pressing 'Ctrl+5' or context menu key does not position as expected

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7460]
**Storage Explorer Version**: 1.32.0-dev (95)
**Build Number**: 20231025.1
**Branch**: rel/1.32.0
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Sonoma 14.0(Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: AD-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Focus the cells respectively -> Open the context menu by pressing 'Ctrl+5' or the context menu key.
4. Check whether the context menu is positioned as expected.

## Expected Experience ##
The context menu is positioned as expected.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/096e9dbd-f279-4f59-a46c-bd1919338e98)

## Actual Experience ##
The context menu is not positioned as expected.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/e98ac4cb-5e52-4f4a-8c6e-742d281bb212)

**Comment by craxal** [comment]
Here's an explanation on what's happening:
* To determine the coordinates of the context menu, the data grid uses the focused column index to select the DOM element, then gets that element's client rectangle. The query used is:
  ```css
  table.data-grid tbody tr:nth-child(focusedItemPagedIndex + 1) td:nth-child(focusedColumnIndex + 1)
  ```
* The virtual columns feature avoids rendering unnecessary columns to improve performance. However, the cell focus information doesn't take this into account. That means, as the user scrolls to the right and the leftmost columns are dropped, the focused column index becomes increasingly inaccurate.
* As a result, the wrong cell is selected, and the context menu is rendered at the wrong coordinates.

**Comment by v-xianya** [comment]
Verified this issue on the rel build 20231028.1. Reproduce for queues. So, we are going to reopen this issue.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/d4b0c3e9-8a8c-4910-a06b-d10ae24b1ccc)

**Comment by craxal** [comment]
So the problem _this_ time is the virtual columns code includes hidden columns in its calculations, which it shouldn't.

**Comment by v-xianya** [comment]
Verified this issue on the rel build 20231030.12. Fixed. So, we are going to close it.
