### ISSUE TITLE
Nothing happens if open one blob container in the restored view all containers explorer

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7461]
**Storage Explorer Version:** 1.32.0-dev (95)
**Build Number:** 20231025.1
**Branch:** rel/1.32.0
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Sonoma 14.0(Apple M1 Pro)
**Architecture:** x64/x64/arm64
**How Found:** Ad-hoc testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Open Settings -> Make sure 'Preserve Explorer Session' is enabled.
2. Expand one storage account -> Right click 'Blob Containers' node.
3. Click 'View All' -> The view all containers explorer opens.
4. Restart Storage Explorer.
5. Select one blob container -> Click 'Open'.
6. Check whether the blob container opens.

## Expected Experience ##
The blob container opens.

## Actual Experience ##
Nothing happens.

**Comment by MRayermannMSFT** [comment]
Fixed for open, paste, and clone

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT Verified this issue on the rel build 20231028.1. 
Reproduces for open/clone. So, we are going to re-open it.

FYI, if open one new tab, then go back to the restored view all containers explorer.
open/clone works well.

**Comment by MRayermannMSFT** [comment]
I determined how you were still able to reproduce and I did not. I had blob containers in quick access which caused resources to be loaded. When they were not loaded, trying to do open, clone, or paste, would fail. Thanks for the good find.

**Comment by v-xianya** [comment]
Verified this issue on the rel build 20231030.12. Fixed.
