### ISSUE TITLE
The pasted entities don't display automatically when successfully canceling the copy activity

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7462]
**Storage Explorer Version:** 1.32.0-dev (95)
**Build Number:** 20231025.1
**Branch:** rel/1.32.0
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Sonoma 14.0(Apple M1 Pro)
**Architecture:** x64/x64/arm64
**How Found:** Ad-hoc testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create a table -> Import a large csv file.
3. Right click the table -> Click 'Copy Table'.
4. Paste the table to another storage account.
5. Click 'Cancel' next to the activity log.
6. Check whether the pasted entities display automatically.

## Expected Experience ##
The pasted entities display automatically.

## Actual Experience ##
The pasted entities don't display automatically.

## Additional Context ##
The pasted entities display after manually refreshing.

**Comment by MRayermannMSFT** [comment]
Assuming entities were copied, we should show how many were, and refresh data explorers as needed.
