### ISSUE TITLE
Unable to access to data storage.

### ISSUE THREAD

**Issue by Z4Dan** [microsoft/AzureStorageExplorer#7467]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.30.0

### Architecture

x64

### Storage Explorer Build Number

20230609.2

### Platform

Windows

### OS Version

Windows 10 Enterprise LTSC

### Bug Description

Unable to access Blob Containers in Azure Staroage Container.

Unable to retrieve child resources

ProducerError:{
  "name": "FetchError",
  "message": "request to https://renasantsftp.blob.core.windows.net/?comp=list&include=metadata failed, reason: self signed certificate in certificate chain",
  "stack": "FetchError: request to https://renasantsftp.blob.core.windows.net/?comp=list&include=metadata failed, reason: self signed certificate in certificate chain\n    at ClientRequest.<anonymous> (C:\\Program Files\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\blob-extension\\dist\\src\\index.js:2:2834516)\n    at ClientRequest.emit (node:events:513:28)\n    at TLSSocket.socketErrorListener (node:_http_client:502:9)\n    at TLSSocket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
  "type": "system",
  "errno": "SELF_SIGNED_CERT_IN_CHAIN",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}

### Steps to Reproduce

1. Launch Storage Explorer.
2. Expand Blob container node for MicroStrategy Blob Storage.
3. Receive the following instead of access data.

Unable to retrieve child resources

ProducerError:{
  "name": "FetchError",
  "message": "request to https://renasantsftp.blob.core.windows.net/?comp=list&include=metadata failed, reason: self signed certificate in certificate chain",
  "stack": "FetchError: request to https://renasantsftp.blob.core.windows.net/?comp=list&include=metadata failed, reason: self signed certificate in certificate chain\n    at ClientRequest.<anonymous> (C:\\Program Files\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\blob-extension\\dist\\src\\index.js:2:2834516)\n    at ClientRequest.emit (node:events:513:28)\n    at TLSSocket.socketErrorListener (node:_http_client:502:9)\n    at TLSSocket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
  "type": "system",
  "errno": "SELF_SIGNED_CERT_IN_CHAIN",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}

### Actual Experience

1. Launch Storage Explorer.
2. Expand Blob container node for MicroStrategy Blob Storage.
3. Receive the following instead of access data.

Unable to retrieve child resources

ProducerError:{
  "name": "FetchError",
  "message": "request to https://renasantsftp.blob.core.windows.net/?comp=list&include=metadata failed, reason: self signed certificate in certificate chain",
  "stack": "FetchError: request to https://renasantsftp.blob.core.windows.net/?comp=list&include=metadata failed, reason: self signed certificate in certificate chain\n    at ClientRequest.<anonymous> (C:\\Program Files\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\blob-extension\\dist\\src\\index.js:2:2834516)\n    at ClientRequest.emit (node:events:513:28)\n    at TLSSocket.socketErrorListener (node:_http_client:502:9)\n    at TLSSocket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
  "type": "system",
  "errno": "SELF_SIGNED_CERT_IN_CHAIN",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}

### Expected Experience

1. Launch Storage Explorer.
2. Expand Blob container node for MicroStrategy Blob Storage.
3. Access data files.

### Additional Context

N/A

**Comment by JasonYeMSFT** [comment]
@Z4Dan Are you using a proxy? If so, could you try enabling "use system proxy" in the settings?

**Comment by MRayermannMSFT** [comment]
@Z4Dan can you please still give the setting a try? Thanks.

**Comment by Z4Dan** [comment]
I uninstalled the application and then installed the latest version and everything is working fine now.Thanks,Dan FraserSent from my iPhoneOn Oct 31, 2023, at 12:04 PM, Matthew Rayermann ***@***.***> wrote:﻿
@Z4Dan can you please still give the setting a try? Thanks.
