### ISSUE TITLE
No string shows on the address bar if click on the address bar then press Tab

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7469]
**Storage Explorer Version**: 1.32.0 (95)
**Build Number**: 20231030.12
**Branch**: rel/1.32.0
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.0(Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: AD-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Click on the address bar-> Press 'Tab'.
4. Check whether the string on the address bar shows.

## Expected Experience ##
The string on the address bar shows.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/7a97c5ca-c885-4471-94e3-b1d25febd81d)

## Actual Experience ##
No string shows on the address bar.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/ffd95085-b08b-48e6-a9e9-288a43bf60f5)

## Additional Context ##
This issue can't be reproduced consistently.

**Comment by JasonYeMSFT** [comment]
I cannot reproduce this issue. Could you record the screen to better illustrate what is happening in the UI?

**Comment by v-xianya** [comment]
@JasonYeMSFT This issue can't be reproduced consistently. we will record the screen when we reproduce it.

**Comment by v-xianya** [comment]
@JasonYeMSFT Here is the record.
![try](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/3a6246bf-abe0-43fc-bc04-10cddd74abda)

**Comment by JasonYeMSFT** [comment]
I am still not able to reproduce this issue. Could you try to record the whole process from the very beginning? It's ok if the recording doesn't reproduce the issue in it. You can write down what it looks like when the problem occurs and differs from the recording.

**Comment by JasonYeMSFT** [comment]
The key to reproduce is to
1. Split the tab
2. Close all tab on the new split view
3. Click on the address bar.

I will make a fix.

**Comment by v-xianya** [comment]
Verified this issue on the build 20231121.2. Fixed. So, we are going to close it.
