### ISSUE TITLE
Premium File Storage not working

### ISSUE THREAD

**Issue by rpengms** [microsoft/AzureStorageExplorer#747]
**Storage Explorer Version**:  1.4.2
**Platform/OS Version**:  Windows
**Architecture**: ia32
**Regression From**: 

#### Steps to Reproduce: ####
1.  Expand a premium file storage account
2.  

#### Expected Experience: ####

Show File shares.

#### Actual Experience: ####

It only shows Blob Containers, with an error prompt (ENOTFOUND). We don't have blob, only file share. File shares are not showing.

**Comment by jinglouMSFT** [comment]
Are you talking about the File Storage preview under the premium account?

**Comment by rpengms** [comment]
This:
https://azure.microsoft.com/en-us/blog/premium-files-pushes-azure-files-limits-by-100x/

**Comment by jinglouMSFT** [comment]
Yeah. it's in a limited preview. We haven't on-board the support yet.

**Comment by MRayermannMSFT** [comment]
We have premium file support now. Please open a new issue if you are still encountering problems.
