### ISSUE TITLE
Unable to retrieve child resources "ProducerError: Electron Net Error"

### ISSUE THREAD

**Issue by ericthomas1** [microsoft/AzureStorageExplorer#7471]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.31.2

### Architecture

x64

### Storage Explorer Build Number

20231003.6

### Platform

Windows

### Bug Description

1. I added a self-signed certificate (.pfx and pw) to the [VS Code Azurite extension settings](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio-code#install-azurite). 
2. Closed VS Code and Storage Explorer. 
3. Reopened them both. 
4. Started the Azurite Services (Blob, Table and Queue) in VS Code. They all open as "HTTP**S**"
5. Opened Storage Explorer
6. Clicked on Emulator & Attached then expanded `(Emulator - Default Ports) (Key)` then `Blob Containers`
7. Error appeared:
    ```
    Unable to retrieve child resources
    
    ProducerError:{
      "name": "Electron Net Error",
      "message": "net::ERR_EMPTY_RESPONSE",
      "stack": "Error: net::ERR_EMPTY_RESPONSE\n    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49935)\n    at SimpleURLLoaderWrapper.emit (node:events:513:28)",
      "cause": {}
    }
    ```
    - ![image](https://github.com/microsoft/AzureStorageExplorer/assets/42788729/65e9a8be-f73a-47d6-a350-187b34431903)

If I remove the path to cert.pfx and pw for the cert from the VS Code Azurite Extension Settings, then close and reopen everything, start the services, etc., there is no error and the Emulator `Blob Containers` open as normal. Though everything is now HTTP. I need to enable HTTP**S**.

![image](https://github.com/microsoft/AzureStorageExplorer/assets/42788729/bfb01850-f485-4a2e-9891-35a3ed23ed64)

How do I properly enable HTTPS between VS Code Azurite Extension and Azure Storage Explorer?

### Steps to Reproduce

1. I added a self-signed certificate (.pfx and pw) to the [VS Code Azurite extension settings](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio-code#install-azurite). 
2. Closed VS Code and Storage Explorer. 
3. Reopened them both. 
4. Started the Azurite Services (Blob, Table and Queue) in VS Code. They all open as "HTTP**S**"
5. Opened Storage Explorer
6. Clicked on Emulator & Attached then expanded `(Emulator - Default Ports) (Key)` then `Blob Containers`
7. Error appeared:

### Actual Experience

See above

### Expected Experience

Azurite would connect to Storage Explorer using HTTPS

### Additional Context

Captured above.

**Comment by ericthomas1** [comment]
Anything you can do to unblock here would be great. I'm unable to test an Azure Function (queue-triggered that downloads a blob). 

Thank you!

**Comment by MRayermannMSFT** [comment]
@ericthomas1 thank you for opening the issue!

Can you please:
1. Since you're needing to rely on a manually imported certificate please go to Settings (gear on the left) > Application > Proxy, and first uncheck "Auto Manage Proxy Settings", then set the dropdown to "Do Not Use Proxy".
2. Can you confirm for us how you imported your self signed certificate into Storage Explorer? Specifically, did you convert it to a base 12 .cer file?

**Comment by ericthomas1** [comment]
Hello @MRayermannMSFT,

1. Completed
2. I created a self-signed .pfx cert using PowerShell.

Are the instructions for creating a `base 12 .cer file` documented?

**Comment by MRayermannMSFT** [comment]
@ericthomas1  to convert to base12 .cer file, you can:
1. Right click on the file > "Open"
2. Go to "Details" tab
3. Click "Copy to File..."
4. Go through the wizard and choose "Base-64 encoded X.509 (.CER) when prompted
5. Finish the Wizard

**Comment by ericthomas1** [comment]
I think I have it...

**Steps**:

1. `openssl req -newkey rsa:2048 -x509 -nodes -keyout key.pem -new -out cert.pem -sha256 -days 365 -addext "subjectAltName=IP:127.0.0.1" -subj "/C=CO/ST=ST/L=LO/O=OR/OU=OU/CN=CN"`
2. `certutil –addstore -enterprise –f "Root" cert.pem`
3. Add `cert.pem` and `key.pem` to the Azurite VS Code Extension `Extension Settings`
4. Start the Azurite VS Code Extensions. All show `https`
5. Import `cert.pem`  into Storage Explorer via the `Edit -> SSL Certificates -> Import Certificates` dialog
6. Restarted Storage Explorer
7. Connect to an Emulated Storage Account:
    - In Storage Explorer, click Connect (plug icon)
    - Select `Storage Account or Service`
    - Select `Connection String`
    - Name the Connection and paste in the HTTPS Connection String: `DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;`

**Comment by nlriverty** [comment]
> I think I have it...
> 
> **Steps**:
> 
> 1. Create new self-signed cert: `openssl req -newkey rsa:2048 -x509 -nodes -keyout key.pem -new -out cert.pem -sha256 -days 365 -addext "subjectAltName=IP:127.0.0.1" -subj "/C=CO/ST=ST/L=LO/O=OR/OU=OU/CN=CN"`
> 2. Add cert to store: `certutil –addstore -enterprise –f "Root" cert.pem`
> 3. Add `cert.pem` and `key.pem` to the Azurite VS Code Extension `Extension Settings`
> 4. Start the Azurite VS Code Extensions. All show `https`
> 5. Import `cert.pem`  into Storage Explorer via the `Edit -> SSL Certificates -> Import Certificates` dialog
> 6. Restarted Storage Explorer
> 7. Connect to an Emulated Storage Account:
>    
>    * In Storage Explorer, click Connect (plug icon)
>    * Select `Storage Account or Service`
>    * Select `Connection String`
>    * Name the Connection and paste in the HTTPS Connection String: `DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;`

Why did you do all that if you're connecting via http instead of https?
