### ISSUE TITLE
Fileshares: Time shown in "Creation Time", "Last Modified" and "Last Write Time" is not always the correct local time

### ISSUE THREAD

**Issue by P47K0** [microsoft/AzureStorageExplorer#7472]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.31.2 (94)

### Architecture

x64

### Storage Explorer Build Number

20231003.6

### Platform

Windows

### OS Version

Windows 11

### Bug Description

The time shown in the file explorer columns: "Creation Time", "Last Modified" and "Last Write Time" is not always correct. The files are stored on the server in UTC time. The time shown in Storage Explorer should be the local time representation. But after the day light saving time ended in the Netherlands (from UTC+2 to UTC+1), the time representation of all the files changed (also from the files which were saved before the 29th of October. The time shown in the columns is now based on the local time without daylight saving time so UTC+1. I would expect that the files from before the 29th of October would still be in UTC+2.

Here is a screen shot with some log files which were all finished at midnight (UTC), before and after the 29th:
![image](https://github.com/microsoft/AzureStorageExplorer/assets/6309117/3beff1e6-b872-498f-98dc-a51fdbbc5e0e)

### Steps to Reproduce

1. Lanch storage explorer
2. Click on Storage Accounts in the Explorer on the left
3. Open a storage account with file shares
4. Select a file share
5. Open a folder on the file share which contains files
6. Inspect the dates of the files, which are shown in the file explorer, from before and after day light saving time

### Actual Experience

The "Creation Time", "Last Modified" and "Last Write Time" of all files are shown in the current local time (UTC+1)

### Expected Experience

The files created/modified before 29th of October (during Day Light Saving Time) are shown with (UTC+2), the files after 29th of October are shown with (UTC+1)

**Comment by MRayermannMSFT** [comment]
Hi @P47K0 would you mind trying to view the timestamps in question on this version of Storage Explorer, and let me know if you still see the time you do not expect, or if the timestamp is now expected? Thank you.

https://github.com/microsoft/AzureStorageExplorer/releases/download/v1.18.1/Windows_StorageExplorer.exe

**Comment by craxal** [comment]
Related to https://github.com/microsoft/AzureStorageExplorer/issues/7466

**Comment by MRayermannMSFT** [comment]
Hi @P47K0 , nevermind on trying that old version. We've decided to fix this and we believe we have a fix. Can you double check for us that in this new version of Storage Explorer, you see timestamps as you expect? Thanks!

https://storageexplorerpublish.blob.core.windows.net/privatebuilds/1.32.0-dst-fix/StorageExplorer-windows-x64.exe?sv=2023-01-03&se=2023-10-30T04%3A27%3A00Z&sr=b&sp=r&sig=N%2BihBFqpySwnu0IF%2BGENmn7awTGo3kinYWpiNb%2F1yd0%3D

**Comment by P47K0** [comment]
Thanks for fixing it, I cannot access the new version via the link provided:
<Error>
<Code>AuthenticationFailed</Code>
<Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:3cbcdeed-101e-002d-23b2-0c027f000000 Time:2023-11-01T10:56:34.5343167Z</Message>
<AuthenticationErrorDetail>Signed expiry time [Mon, 30 Oct 2023 04:27:00 GMT] must be after signed start time [Wed, 01 Nov 2023 10:56:34 GMT]</AuthenticationErrorDetail>
</Error>

**Comment by P47K0** [comment]
Thanks, it is fixed!

<img width="1002" alt="image" src="https://github.com/microsoft/AzureStorageExplorer/assets/6309117/fb9e55cc-e8f6-44e0-9bb3-ff8f79c1c80d">
