### ISSUE TITLE
Storage Explorer not able to connect

### ISSUE THREAD

**Issue by babeitman** [microsoft/AzureStorageExplorer#7473]
Storage Explorer is not opening browser to authenticate account to allow access to Storage Accounts. 
Unable to sign in: An attempt was made to access a socket in a way forbidden by its access permissions. (login.microsoftonline.com:443)

I removed my account to start over and now the account can not be added back in.

**Comment by babeitman** [comment]
new error message details:
{
  "name": null,
  "message": "\"{\\n  \\\"name\\\": \\\"Electron Net Error\\\",\\n  \\\"message\\\": \\\"net::ERR_PROXY_CONNECTION_FAILED\\\",\\n  \\\"stack\\\": \\\"Error: net::ERR_PROXY_CONNECTION_FAILED\\\\n    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49935)\\\\n    at SimpleURLLoaderWrapper.emit (node:events:513:28)\\\",\\n  \\\"cause\\\": {}\\n}\""
}

**Comment by MRayermannMSFT** [comment]
@babeitman can you check if you're able to, on the same machine and same user login, use Microsoft Edge and/or Google Chrome, to go to the Azure Portal, and view your storage data?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you still need help with this problem, we recommend opening a support ticket via the Azure portal. Alternatively you can open a new issue here. This issue will no longer be monitored.
