### ISSUE TITLE
The view all containers explorer is not localized

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7476]
**Storage Explorer Version:** 1.33.0 (96)
**Build Number:** 20231103.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.1(Apple M1 Pro)
**Language:** All languages
**Architecture:** x64/x64/x64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select 'Français' -> Restart Storage Explorer.
3. Expand one storage account.
4. Right click Blob Containers node -> Click 'View All'.
5. Check whether the view all containers explorer is localized.

## Expected Experience ##
The view all containers explorer is localized.

## Actual Experience ##
The view all containers explorer is not localized.

**Comment by MRayermannMSFT** [comment]
Likely just waiting on loc team.

**Comment by MRayermannMSFT** [comment]
And nope, I forgot to add to LocProject.json 🤦. It is added now. Moving to 1.34. Will close later once Loc team has had a chance to loc strings and a new package is published.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20231128.1. Fixed. So, we are going to close it.
