### ISSUE TITLE
The descriptions of the setting 'Load Batch Size' are not localized

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7477]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20231103.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.1 (Apple M1 Pro)
**Reproduce Languages**: All languages
**Architecture**: x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.31.2)

## Steps to Reproduce ##
1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select 'Français' -> Restart Storage Explorer.
3. Go to 'Settings'.
4. Check whether all strings are localized.

## Expected Experience ##
All strings that should be localized have been localized.

## Actual Experience ##
The descriptions of the 'Load Batch Size' are not localized.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/67ba9602-0d00-4b10-8fd8-3f7fa591067a)

**Comment by MRayermannMSFT** [comment]
Likely just waiting on loc team.

**Comment by JasonYeMSFT** [comment]
The strings have been translated on the main branch.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20231128.1. Fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/b642cebf-8206-472b-9e5d-4e1ee7cd400e)
