### ISSUE TITLE
Workaround node-gyp incompatability with Python 3.12

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#7481]
Compliance builds (and maybe soon other pipelines) are bringing in Python 3.12. The versions of node-gyp we are currently using are incompatible with this version of Python. We need to workaround the incompatability.

Related links:
https://github.com/nodejs/node-gyp/issues/2869

**Comment by MRayermannMSFT** [comment]
![BatmanThinkingGIF](https://github.com/microsoft/AzureStorageExplorer/assets/21112697/b0068c17-1fda-4b7b-9356-3a0a20cd54fa)

**Comment by JasonYeMSFT** [comment]
We fixed the Python version in the pipeline to < 3.12. We should upgrade node-gyp to v10 and see if it's compatible with Python 3.12 in the future.

**Comment by JasonYeMSFT** [comment]
Very likely we cannot get this done in 1.34.0. Electron v29 uses Node 20.9.0 which is still on node-gyp 9.4.0.

**Comment by JasonYeMSFT** [comment]
All Python workaround tasks are remoeved.
