### ISSUE TITLE
Review Compatability With HTTPS Azurite Steps

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#7483]
1. Review our compatability with HTTP Azurite steps: https://github.com/Azure/Azurite/blob/main/README.md#https-setup
2. Can we give Azurite team easier steps for users via System Proxy? If yes, do we need to implement this: https://www.electronjs.org/docs/latest/api/app#event-certificate-error

Related to: https://github.com/microsoft/AzureStorageExplorer/issues/7471

**Comment by craxal** [comment]
Old issue. Might revisit if we get user feedback.
