### ISSUE TITLE
Table Storage Explorer - Execute Query ('Play') button disabled after first query

### ISSUE THREAD

**Issue by kweebtronic** [microsoft/AzureStorageExplorer#7484]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.0

### Regression From

1.31.x

### Architecture

x64

### Storage Explorer Build Number

20231101.3

### Platform

Windows

### OS Version

Windows 11 Pro Build 22631

### Bug Description

The 'Execute Query' button is disabled for subsequent queries using the same criteria, on a table

### Steps to Reproduce

1. open an explorer tab for a particular table
2. query by timestamp 'last hour'
3. execute the query with play button
4. results returned successfully
5. I want to run the query again a few minutes later to get current 'last hour' data, but **the Execute Query ('play') button is disabled** and I can't F5

### Actual Experience

see above ... re-querying is disabled

![image](https://github.com/microsoft/AzureStorageExplorer/assets/37149921/e6cb9a1e-b560-47e2-a7e2-9ac3aeb7ceb6)

### Expected Experience

Execute Query button should not be disabled.
I should be able to run the same query, on the same table, at a later time with one click/action

**Comment by sixeyes** [comment]
Same issue here after updating to v1.32.0. I have to refresh page before I can run the query again.

**Comment by lu2Github** [comment]
Same issue here after updating to v1.32.0.

**Comment by craxal** [comment]
This change was intentional in order to address #7061 and to minimize costs that might stack up from repetitive queries.

If you would prefer the older behavior, please let us know here, and we'll look into it.

**Comment by kweebtronic** [comment]
Most definitely, I want to have the option to re-query using the same
criteria, with one action.

This is a user-driven action, not automated ... so costs are not even a
factor ... at 0.05 cents per 10,000 transactions!

**Comment by sixeyes** [comment]
I'll be reverting to the previous build until this is fixed. New behaviour is not helpful. 

Instead of pressing Play, I have to hit refresh and then Play one after the other, so generating 2 queries in short order. In the previous versions it would have been one query. 

Given that you've added a feature to load all pages, is pressing the Play button on a filtered query really a huge hit?

Surely loading all pages just to get a sort is far larger?

**Comment by kweebtronic** [comment]
This is a regression, reducing functionality that has been around since version 1.
If it's 'by design' (your label @craxal) then it isn't considering existing use cases.

The isolated issue you have referenced is related to **exporting** - so "design" the change in the Export menu, not impacting other use cases within the explorer. Perhaps delineate between 'active' and 'applied' query dynamically within the drop-down, if they differ.

**Comment by craxal** [comment]
Thank you, everyone, for the feedback. We will work on getting the one-click behavior for Execute Query back in.

**Comment by MRayermannMSFT** [comment]
Version 1.32.1 has been released, which includes restoring the behavior of being able to rerun a query:
![7484](https://github.com/microsoft/AzureStorageExplorer/assets/21112697/f2a77dcc-3359-4b71-b865-cd2055e0019c)

Thanks again to everyone for the feedback. We are always open to change based on what y'all are looking for!
