### ISSUE TITLE
Data in table not displayed due to invalid query condition request, despite no query being taken

### ISSUE THREAD

**Issue by MaxPaceCCS** [microsoft/AzureStorageExplorer#7485]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.0

### Regression From

1.30.0

### Architecture

x64

### Storage Explorer Build Number

20231101.3

### Platform

Linux (snap)

### OS Version

Ubuntu 22.04.3 LTS

### Bug Description

By default, data in locally hosted tables are being queried with an invalid request.

### Steps to Reproduce

1. Launch Storage Explorer
2. Populate table with data
3. Open Emulator & Attached --> Storage Accounts --> (Emulator - Default Ports) (Key) --> Tables
4. Open any table listed in the Tables folder.

### Actual Experience

Table displays no data, except until a query is entered. Switching to a new table or refreshing the table resets the query.
[Screencast from 07-11-23 15:01:25.webm](https://github.com/microsoft/AzureStorageExplorer/assets/117731038/eb33be6a-27da-401f-adc7-e6d2adb376d9)

### Expected Experience

Table should show data without using a separate query by default.

### Additional Context

Error message shown when loading or refreshing a table: "The query condition specified in the request is invalid."

This behaviour is not observed when connecting to a remote storage account.

**Comment by cgleadall** [comment]
I am having the same behavior. 
```
Version: 1.32.0 (95)
AzCopy Version: 10.20.1
Platform: Windows
Architecture: x64
BuildNumber: 20231101.3
Commit: 84b96e1ed2
```
I can delete tables from the right-click popup menu, just cannot retrieve/see data in the tables until you define a query.

Here are a few lines from the CLI output when running `azurite.exe` from Terminal:
``` 
127.0.0.1 - - [07/Nov/2023:18:28:51 +0000] "GET /devstoreaccount1/Network()?$filter= HTTP/1.1" 400 -
127.0.0.1 - - [07/Nov/2023:18:29:07 +0000] "GET /devstoreaccount1/Network()?$top=50&$filter= HTTP/1.1" 400 -
127.0.0.1 - - [07/Nov/2023:18:29:18 +0000] "GET /devstoreaccount1/Network()?$top=50&$filter=PartitionKey%20ge%20%27%27 HTTP/1.1" 200 -
```

Notice the query ends with `?filter=`  by default, but when you add an explicit filter `$filter=PartitionKey ge ''`  the data does appear.

**Comment by craxal** [comment]
@MaxPaceCCS @cgleadall What version of Azurite are you running? I used 3.27.0 on Windows, and am not able to reproduce the issue.

**Comment by cgleadall** [comment]
@MaxPaceCCS  - Yes you are right, my azureite.exe is 'only' version 3.24.0
I re-installed Storage Explorer 1.32.0 to double check that it is still working with the real Azure instances - as I couldn't remember if I had tested that. I guess I am on a journey to update `Azurite.exe`.

Thanks for the troubleshooting information.

**Comment by cgleadall** [comment]
After 10 minutes of looking to update the Visual Studio installed version of Azurite, and failing... :| 
I went with the Docker version. I was able to mount the data partition to the same location that was used by Visual Studio, so there is no data loss.
When Studio starts and try to execute the Azurite.exe it will have a port conflict and just give up, but everything should still work after that.

Here is the docker run command I used:
`docker run -d --restart unless-stopped --name Azurite -p 10000:10000 -p 10001:10001 -p 10002:10002 -v C:\Users\{myAccountName}\AppData\Local\.vstools\azurite:/data mcr.microsoft.com/azure-storage/azurite`
after doing a `docker pull mcr.microsoft.com/azure-storage/azurite:latest`

**note** the `{myAccountName}` placeholder in the `-v` parameter.

**Comment by craxal** [comment]
A simple alternative to the Docker version is, if you have Node installed, you can run `npm install azurite` and run Azurite from the command line.

**Comment by craxal** [comment]
If I remember correctly, we encountered this same filter issue some time ago with older versions of Azurite. Upgrading resolved the issue.

It sounds like this has been mitigated with an Azurite upgrade, so I'll close. But let us know if you still need help or are still having issues, and we will reopen.

**Comment by craxal** [comment]
@cgleadall Out of curiosity, what version of VS were you using?

**Comment by cgleadall** [comment]
@craxal I was 1 version behind current at the time. I am sorry but I have already updated Visual Studio (dotnet Conf blinded me and I forgot to check for you).
The `./azurite.exe -v` response is: `3.26.0` after I have installed Visual Studio `17.8.0`

**Comment by WillGoldLO** [comment]
Where exactly is this latest version 3.x.x? 

![image](https://github.com/microsoft/AzureStorageExplorer/assets/61398749/eb373229-56f4-4dbf-bdf4-d5d426299905)

**Comment by cgleadall** [comment]
@WillGoldLO Those appear to be the correct / latest versions. 
As for Explorer not working with the 'azurite.exe' (3.26.0) Node application: I don't know. I switched to running Azurite in Docker, instead of letting Visual Studio start the node application.

Sorry for not giving you any solutions.

**Comment by craxal** [comment]
@WildGoldLO You don't have to use the version of Azurite that comes with VS. If you have Node installed, you can install the latest with the command `npm install -g azurite`.
