### ISSUE TITLE
[Emulator - Default Ports] Unable to retrieve child resources (Azurite listening on default ports)

### ISSUE THREAD

**Issue by darkoa-msft** [microsoft/AzureStorageExplorer#7487]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.0

### Regression From

First time trying to use the explorer with Azurite

### Architecture

x64

### Storage Explorer Build Number

20231101.3

### Platform

Windows

### OS Version

Windows 11

### Bug Description

Cannot manage local emulator's queues (or any other services).

I have two instances of Azurite running, one on default ports.
Freshly installed 64-bit explorer (removed my 32-bit I had installed previously).

Azurite Blob service is starting at https://127.0.0.1:10000
Azurite Blob service is successfully listening at https://127.0.0.1:10000
Azurite Queue service is starting at https://127.0.0.1:10001
Azurite Queue service is successfully listening at https://127.0.0.1:10001
Azurite Table service is starting at https://127.0.0.1:10002
Azurite Table service is successfully listening at https://127.0.0.1:10002

### Steps to Reproduce

1. Launch Storage Explorer
2. Try to expand Emulator & Attached -> (Emulator - Default Ports) (Key) -> Queues
3. Get the 'Unable to retrieve child resources' error

### Actual Experience

Explorer errors out.

### Expected Experience

I should see local queues created by my services in Azurite.

### Additional Context

Unable to retrieve child resources

ProducerError:{
  "name": "Node Fetch Error",
  "message": "other side closed",
  "stack": "SocketError: other side closed\n    at Socket.onSocketEnd (C:\\Program Files\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\undici\\lib\\client.js:995:22)\n    at Socket.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1359:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
  "cause": {
    "cause": {
      "name": "SocketError",
      "code": "UND_ERR_SOCKET",
      "socket": {
        "localAddress": "127.0.0.1",
        "localPort": 52763,
        "remoteAddress": "127.0.0.1",
        "remotePort": 10001,
        "remoteFamily": "IPv4",
        "bytesWritten": 573,
        "bytesRead": 0
      }
    }
  },
  "code": "UND_ERR_SOCKET"
}

**Comment by JasonYeMSFT** [comment]
@darkoa-msft You started your Azurite instance with https protocol. Our default (Emulator - Default Ports) uses the http protocol. If you want to connect to Azurite in https, you need to add a custom connection and add the trusted certs in Storage Explorer. There are more details in this thread. https://github.com/microsoft/AzureStorageExplorer/issues/2598#issuecomment-616765993

**Comment by darkoa-msft** [comment]
@JasonYeMSFT Thanks, that sounded promising but I am not sure what 'trusted' means here.
I create a self-signed dev cert, put it in LocalMachine\Root, export public key as base 64 .cer, import into explorer, restart it,, still failing.

Note that I have to use system proxy as well, otherwise cert cannot be verified.


```
Unable to retrieve child resources

ProducerError:{
  "name": "Electron Net Error",
  "message": "net::ERR_CERT_COMMON_NAME_INVALID",
  "stack": "Error: net::ERR_CERT_COMMON_NAME_INVALID\n    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:50188)\n    at SimpleURLLoaderWrapper.emit (node:events:513:28)",
  "cause": {}
}
```

**Comment by MRayermannMSFT** [comment]
We just helped someone with this: https://github.com/microsoft/AzureStorageExplorer/issues/7471

I'd recommend reading through that tread for more help.

We're also going to be sync'ing up with the Azurite team in the near future to make sure their HTTPS instructions for Storage Explorer are as simple as possible.

**Comment by darkoa-msft** [comment]
I appreciate the help. Disabled SSL check in the explorer in order to use it with Azurite. I don't think that it is on Azurite to instruct how to use Storage Explorer with the recommended emulator.
