### ISSUE TITLE
Unable to retrieve child resources - error message after updating

### ISSUE THREAD

**Issue by WozziFoat** [microsoft/AzureStorageExplorer#7488]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.0

### Architecture

x64

### Platform

All

### Bug Description

After updating to 1.32.0 the follow message pops up each time app is launched

Unable to retrieve child resources

ProducerError:{
  "name": "TypeError",
  "message": "{\"name\":\"TypeError\"}"
}

### Steps to Reproduce

1. Launch storage explorer

### Actual Experience

After updating to 1.32.0 the follow message pops up each time app is launched

Unable to retrieve child resources

ProducerError:{
  "name": "TypeError",
  "message": "{\"name\":\"TypeError\"}"
}

**Comment by schikla** [comment]
A relogin solved the problem for me.

**Comment by WozziFoat** [comment]
Thanks schikla. That resolved the issue for the users who got it
