### ISSUE TITLE
On Mac M1 Pro with Sonoma 14.0 I cannot see the window

### ISSUE THREAD

**Issue by antonio-bravo** [microsoft/AzureStorageExplorer#7498]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.0(95)

### Regression From

1.32.0

### Architecture

arm64

### Storage Explorer Build Number

20231101,3

### Platform

macOS

### OS Version

Sonoma 14,0

### Bug Description

When I open the Microsoft Azure Storage Explorer only I can see this

<img width="588" alt="image" src="https://github.com/microsoft/AzureStorageExplorer/assets/79697559/8cb113f8-cb2e-4aab-8f63-b82a38ffd063">

I have no way to see the window anywere, I was able from the toolbar to see the version open another dialogs, but not the application itself.

it was tryied to open the app using the following command without success

`
open -a "Microsoft Azure Storage Explorer" --args --disable-gpu
`

### Steps to Reproduce

Just open the application

### Actual Experience

Openning the app I am only to see the following image 
<img width="588" alt="image" src="https://github.com/microsoft/AzureStorageExplorer/assets/79697559/b9427843-7cf1-450b-b25c-718d8d8bc2a3">

I tried to open from the console using 
`
open -a "Microsoft Azure Storage Explorer" --args --disable-gpu
`
without success

**Comment by JasonYeMSFT** [comment]
@antonio-bravo There may be something you can try to resolve this issue. However, before you try that, could you go to StorageExplorer app data directory, find a file called "appState.json" and copy paste its content here? You can quickly go to our app data directory by clicking through "Edit" > "SSL Certificates" > "View Imported SSL Certificates" in the app menu (the ones in your screenshot). It will open a directory in your Finder. Navigate one directory level up and you should be able to find the "appState.json". I am very confident that the whole file is safe to share but feel free to inspect its content before sharing.

Long story short. On mac, for unknown reason, the application window can be resized to almost 0x0 and placed at the very bottom of the screen. This normally should be blocked by our UI logic. The appState.json contains data that tells our application what size the window should have and where is should appear on the screen. We've always wanted to see the values in the "appState.json" when this issue occur. The resolution is to either find that tiny window and resize it back to normal, or simply delete the appState.json and let a new fresh default value replace the problematic ones.
You can find more details in this issue https://github.com/microsoft/AzureStorageExplorer/issues/3086

**Comment by antonio-bravo** [comment]
> @antonio-bravo There may be something you can try to resolve this issue. However, before you try that, could you go to StorageExplorer app data directory, find a file called "appState.json" and copy paste its content here? You can quickly go to our app data directory by clicking through "Edit" > "SSL Certificates" > "View Imported SSL Certificates" in the app menu (the ones in your screenshot). It will open a directory in your Finder. Navigate one directory level up and you should be able to find the "appState.json". I am very confident that the whole file is safe to share but feel free to inspect its content before sharing.
> 
> Long story short. On mac, for unknown reason, the application window can be resized to almost 0x0 and placed at the very bottom of the screen. This normally should be blocked by our UI logic. The appState.json contains data that tells our application what size the window should have and where is should appear on the screen. We've always wanted to see the values in the "appState.json" when this issue occur. The resolution is to either find that tiny window and resize it back to normal, or simply delete the appState.json and let a new fresh default value replace the problematic ones. You can find more details in this issue #3086

Thank you so much for your prompt reply, this is the content of appState.json located at /Users/<MyUserName>/Library/Application Support/StorageExplorer/appState.json

{"lastWindowState":{"rect":{"x":0,"y":1663,"width":73,"height":29},"maximized":false},"disableGpu":false,"dialogAutoResponse":{}}

I have just changed the **y** value in order to fit on the screen and I can see right now.

**Comment by mbortolussi9** [comment]
Solution worked but I lost an hour with this issue.

**Comment by JasonYeMSFT** [comment]
We've been aware of this issue for a long time but unfortunately we weren't able to figure out exactly why. We had hypothesis about multi-monitor setup that somehow tweaks the size of the app window to something super tiny (I've seen it happening for some other application) but we weren't able to reproduce it ourselves. In 1.33.0 we will enforce a small but still big enough minimum size of our app window so people can find the app window and resize it.

**Comment by antonio-bravo** [comment]
> We've been aware of this issue for a long time but unfortunately we weren't able to figure out exactly why. We had hypothesis about multi-monitor setup that somehow tweaks the size of the app window to something super tiny (I've seen it happening for some other application) but we weren't able to reproduce it ourselves. In 1.33.0 we will enforce a small but still big enough minimum size of our app window so people can find the app window and resize it.

Certainly, it seems to be linked to multiple monitors. I had suspected this when the issue first arose, thinking that returning home to the multi-monitor setup would resolve it and move the window correct place but I was not able to see. That's when I decided to open this issue.
