### ISSUE TITLE
Version 1.32.0 - JavaScript error in the main process error

### ISSUE THREAD

**Issue by genzorp** [microsoft/AzureStorageExplorer#7499]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.0

### Regression From

1.31.2

### Architecture

x64

### Storage Explorer Build Number

20231003.6

### Platform

Windows

### OS Version

Windows 10 Enterprise

### Bug Description

After updating from previous version to version 1.32.0 the Explorer fails to start. 

### Steps to Reproduce

Update to Explorer version 1.32.0 on Windows 10 machine.

### Actual Experience

I downloaded the new version of explorer. Installed it which happened without any issues. When the programs was to start, a large window appears stating there was "A JavaScript error occurred in the main process" . The installation process apparently runs smoothly, however programs fails to initiate. 

After downgrade to previous version, Explorer starts normally.

**Comment by JasonYeMSFT** [comment]
@genzorp Could you go to the logs directory and share you one of the logs for the failed startup with us? The logs directory is at "C:\Users\your_username\AppData\Roaming\StorageExplorer\logs\"

**Comment by JasonYeMSFT** [comment]
@genzorp Are you seeing an error similar to this? We found a bug that can lead to that error and will fix it in 1.32.1.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/39359541/e1321caf-be5c-4c6c-8089-be8fb24e0767)

**Comment by MRayermannMSFT** [comment]
We've released 1.32.1 which includes a fix for the error @JasonYeMSFT shared. We'll move this issue out of the 1.32.1 milestone until we know that @genzorp indeed was encountering this error. If no response is ever shared, we will close the issue after a month of no response. Thanks.

**Comment by genzorp** [comment]
@JasonYeMSFT - My apologies for the late response - I am traveling at the moment - sorry I wasn't able to provide the logs. 

Yes, the error that I received was the same as the one you shared in your image. Thank you very much for looking into this and sharing an update. I will try to install the 1.32.1 version with the fix (@MRayermannMSFT - thank you!) and will update you as soon as I determine if it is working. 

Thank you very much!

Best wishes,
