### ISSUE TITLE
Make container name editable, or provide an alternative fast way of navigating to a given container

### ISSUE THREAD

**Issue by ant0nsc** [microsoft/AzureStorageExplorer#75]
| | |
|-|-|
|**Storage Explorer Version**|1.0.0|
|**OS Version**|Windows 10|

**Steps to Reproduce:**
I have a storage account that holds several hundreds of containers (each container has the results of a large simulation run in Azure Batch). I'm trying to navigate to container named `xyz`. Presently, I have to
1. Navigate to the storage account.
2. Right click on "Blob Containers" and select "Search from here". 
3. Type or copy in the container name. 
4. Press the search button. At this point, it takes 20 to 30 seconds for search to return the single container that I'm interested in.
5. Click on the container

**Expected Experience:**
It would be much faster if I could just edit the name of the container in the main window. In the same washup, it would be helpful to make the full directory path editable - but the container name is really my main beef here because navigating to a container of given name is just dead slow if the storage account has more than a dozen container.

**Comment by ant0nsc** [comment]
I can't work with frequently used containers because I always need to navigate to different ones (experiment finishes, all going into brandnew container, I need to locate that container and inspect)

**Comment by dagood** [comment]
I regularly work with an account with > 3,500,000 containers in it, and I hit this same problem except that no search I've run on it for a container has ever finished.

Specifying an exact container name and/or prefix search seems like the only reasonable way to make storage explorer usable in this scenario. The Azure Portal does prefix search, so I use it when I need to use this account. (I use Storage Explorer regularly for other accounts that don't have an obscene number of containers, so I'm always painfully aware of the neat functionality I'm missing out on when I work with the large account. :smile:)

**Comment by abarefoot** [comment]
I also have a similar issue and workflow. Our storage account has thousands of containers with "N" formatted guids for names. I regularly need to navigate to specific containers and using the search is basically unusable - it takes 15 minutes or more to locate the container.

It would be ideal if there was an "Open/Navigate to Container" feature.

**Comment by MRayermannMSFT** [comment]
@abarefoot @dagood @ant0nsc and others, have you ever tried the "Search from here" action on the "Blob Containers" node?
![image](https://user-images.githubusercontent.com/21112697/102128534-e18e7b00-3e02-11eb-8f83-63f0e5dac354.png)
If so, can you let us know how it performed for your use cases?
If not, can you try it, and then let us know how it performed for your use cases?

**Comment by dagood** [comment]
I gave it a try now. (I'm on 1.16.0, which "check for updates" says is up to date.)

1. After clicking the button, there's no obvious place to type. This box gets some text put in it, but it's cut off, and the text cursor doesn't seem to be placed in the box at all:
   ![image](https://user-images.githubusercontent.com/12819531/102149665-9a20e280-3e34-11eb-8376-cd16feaba1b9.png)

2. After manually clicking in the box, pressing End, and pasting the container name I want to go to, and pressing enter, it takes ~10 seconds for the search to complete.

This is better than waiting indefinitely, but far from ideal.

(Luckily this isn't part of my workflow anymore, personally. The things I browse often recently have used virtual folders instead of containers, so I can just do a prefix search. I went back and did the same sort of search I used to have to do in the past to help give info on this issue, though.)

**Comment by dagood** [comment]
> have you ever tried the "Search from here" action on the "Blob Containers" node?

I just noticed this says "ever". This issue has actually always been about this specific feature. 😄 I assumed the ping was because there was some improvement, so I went to try again.

Maybe I got lucky with my 10 second results this time. Hopefully someone else has been using this feature regularly, and can give better historical data than my single attempt just now.

**Comment by ant0nsc** [comment]
@MRayermannMSFT : If you read the very start of this issue, you might see that "Search from here" is precisely what I've had to use so far.
Trying that now, I can confirm that search speed has certainly improved. It takes about 12 seconds to find the container in question - a definite improvement over the 20-30 seconds it took when I filed this issue.
However, the whole time until I'm in the container in question is way more than those 12 seconds - because of a odd behaviour of the "Search from here" box:
- I first right-click on the context menu, choose "Search from here".
- Then the text box with "/Quick Access/..." gets active, and it _immediately starts searching_, using an empty prefix. This search takes 8-10 seconds on my storage account. During those 8-10 seconds, I can't do anything - only once that empty search has completed, I can type in the container name that I actually need.

So, in total, I need about half a minute until I'm at the container in question. 

@MRayermannMSFT , I'd suggest to fix that odd empty search behaviour to start with.

While we're on the subject of odd UI behaviour: The search bar on the right hand side is also unintuitive. It shows the container name, but the moment I start typing in it, the container name disappears. I'm now unsure, what happened to the container name? Am I search inside the container? Can I specify the container name now, because it is no longer showing?

![image](https://user-images.githubusercontent.com/4396121/102194218-f592b500-3eb4-11eb-92e9-2c3fab6dcb56.png)

**Comment by DuncWatts** [comment]
I don't think improving search is the answer here, adding in the ability to go straight to a named container as per the original issue would be a massive time saver when working with large numbers of containers.

**Comment by abarefoot** [comment]
I'll second what @dagood, @ant0nsc, and @DuncWatts have said. While the actual search time has improved since this issue was created, the entire flow of trying to navigate to specific storage containers is error prone and frustrating (e.g. focus leaving selected controls, etc).

**Comment by ant0nsc** [comment]
... and just to add that the folks on this thread @dagood @DuncWatts @abarefoot  are not the only ones longing for faster access to specific containers. @AlexUrbanAc mentions in #1790 that he has 100k+ containers, and search takes AGES for him, way more than for me with my 1k+ containers.

**Comment by AlexUrbanAc** [comment]
@ant0nsc That number is outdated. We're currently at ~400k containers and counting. Time to access a container through Azure Storage Explorer has gone up, didn't use a stopwatch but it should be something between 20 and 30 minutes.

**Comment by ant0nsc** [comment]
@MRayermannMSFT - I think the wait time of 20-30min that @AlexUrbanAc is reporting here should be enough of a justification to allow direct navigation to a container, without having to go through search.
