### ISSUE TITLE
Add the specified value 64 KB next to 'maximum permissible limit'

### ISSUE THREAD

**Issue by v-dantch** [microsoft/AzureStorageExplorer#750]
**Storage Explorer Version**: 1.4.3
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20181010.1
**Commit**: 39ec4ed9
**Regression From**: Not a Regression

#### Steps to Reproduce: ####
1. Open one queue -> Select 'Add Message' ->type some messages which size is greater than 64KB.
2. Click 'OK' to check the error dialog.

#### Suggestion Experience: ####
Add the specified value 64 KB next to 'maximum permissible limit'.

#### Actual Experience: ####
No specified value shows in the error dialog.
![image](https://user-images.githubusercontent.com/41351993/71611812-029c9280-2bd7-11ea-9b8f-1d9a193537bd.png)

**Comment by MRayermannMSFT** [comment]
This is a general error message that the server is returning. Not easy for them to change. So won't fix for now.
