### ISSUE TITLE
No se pueden recuperar los recursos secundarios  ProducerError:{   "message": "{}" }

### ISSUE THREAD

**Issue by estyfen** [microsoft/AzureStorageExplorer#7500]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32

### Architecture

x64

### Platform

Windows

### Bug Description

No se pueden recuperar los recursos secundarios

ProducerError:{
  "message": "{}"
}

### Steps to Reproduce

1. Launch Azure Storage Explorer

### Actual Experience

![image](https://github.com/microsoft/AzureStorageExplorer/assets/29147360/28c42960-1276-4ff4-96ee-54f024b70a9c)

**Comment by JasonYeMSFT** [comment]
@estyfen Could you let us know why you closed this issue?

**Comment by estyfen** [comment]
Because It was not really an error. Thanks!!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
