### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by rx801s** [microsoft/AzureStorageExplorer#7504]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.0

### Architecture

i86

### Platform

All

### Bug Description

Unable to retrieve child resources.

Details:
{
  "name": "RestError",
  "message": "This request is not authorized to perform this operation.\nRequestId:943e4589-c01e-0078-129b-15163c000000\nTime:2023-11-12T19:05:23.3566501Z",
  "stack": "RestError: This request is not authorized to perform this operation.\nRequestId:943e4589-c01e-0078-129b-15163c000000\nTime:2023-11-12T19:05:23.3566501Z\n    at handleErrorResponse (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/@azure/core-http/dist/index.js:3129:19)\n    at /Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/@azure/core-http/dist/index.js:3065:49\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async StorageRetryPolicy.attemptSendRequest (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/@azure/storage-blob/dist/index.js:14086:24)\n    at async StorageClientContext.sendOperationRequest (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/@azure/core-http/dist/index.js:4894:31)\n    at async BlobServiceClient.listContainersSegment (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/@azure/storage-blob/dist/index.js:23132:20)",

### Steps to Reproduce

Unable to retrieve child resources.

Details:
{
  "name": "RestError",
  "message": "This request is not authorized to perform this operation.\nRequestId:943e4589-c01e-0078-129b-15163c000000\nTime:2023-11-12T19:05:23.3566501Z",
  "stack": "RestError: This request is not authorized to perform this operation.\nRequestId:943e4589-c01e-0078-129b-15163c000000\nTime:2023-11-12T19:05:23.3566501Z\n    at handleErrorResponse (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/@azure/core-http/dist/index.js:3129:19)\n    at /Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/@azure/core-http/dist/index.js:3065:49\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async StorageRetryPolicy.attemptSendRequest (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/@azure/storage-blob/dist/index.js:14086:24)\n    at async StorageClientContext.sendOperationRequest (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/@azure/core-http/dist/index.js:4894:31)\n    at async BlobServiceClient.listContainersSegment (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/@azure/storage-blob/dist/index.js:23132:20)",

### Actual Experience

Unable to retrieve child resources.

Details:
{
  "name": "RestError",
  "message": "This request is not authorized to perform this operation.\nRequestId:943e4589-c01e-0078-129b-15163c000000\nTime:2023-11-12T19:05:23.3566501Z",
  "stack": "RestError: This request is not authorized to perform this operation.\nRequestId:943e4589-c01e-0078-129b-15163c000000\nTime:2023-11-12T19:05:23.3566501Z\n    at handleErrorResponse (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/@azure/core-http/dist/index.js:3129:19)\n    at /Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/@azure/core-http/dist/index.js:3065:49\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async StorageRetryPolicy.attemptSendRequest (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/@azure/storage-blob/dist/index.js:14086:24)\n    at async StorageClientContext.sendOperationRequest (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/@azure/core-http/dist/index.js:4894:31)\n    at async BlobServiceClient.listContainersSegment (/Applications/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/@azure/storage-blob/dist/index.js:23132:20)",

**Comment by rx801s** [comment]
sorry I used latest version 1.32.0

**Comment by MRayermannMSFT** [comment]
@rx801s how are you authenticating your access to your storage resources?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you continue encountering this problem, we recommend opening a support ticket via the Azure portal. Alternatively you can open a new issue here.
