### ISSUE TITLE
'Ctrl + S' works for 'Save query as...' not 'Save query' for tables

### ISSUE THREAD

**Issue by v-dantch** [microsoft/AzureStorageExplorer#751]
**Storage Explorer Version**: 1.4.3
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20181010.1
**Commit**: 39ec4ed9
**Regression From**: Not a Regression

#### Steps to Reproduce: ####
1. Open one table ->Select 'Query' in table editor.
2. Check the keyboard shortcuts for 'Save query as...' and 'Save query'.

#### Expected Experience: ####
'Ctrl + S' works for 'Save query' not 'Save query as...'.

#### Actual Experience: ####
'Ctrl + S' works for 'Save query as...' not 'Save query'.

**Comment by v-xianya** [comment]
This issue has been fixed on the build 20190919.2. So we close it.
