### ISSUE TITLE
In Azure explorer while trying to Manage ACLs getting the below error

### ISSUE THREAD

**Issue by RamPatel58** [microsoft/AzureStorageExplorer#7512]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.28.0

### Regression From

1.28.0

### Architecture

i86

### Storage Explorer Build Number

20230214.5

### Platform

All

### OS Version

Windows 11

### Bug Description

If you cannot resolve this issue on your own, you may open an issue on the Storage Explorer GitHub site. Please include the details below to help us diagnose your issue. Make sure to redact any personal information you do not wish to make public before posting.

**{
  "name": null,
  "message": "\"{\\n  \\\"name\\\": \\\"RestError\\\",\\n  \\\"message\\\": \\\"request to https://storageaccount.dfs.core.windows.net/container/server-schedule-predictions?upn=true&action=getAccessControl failed, reason: getaddrinfo ENOTFOUND storageaccount.dfs.core.windows.net\\\",\\n  \\\"stack\\\": \\\"RestError: request to https://storageaccount.dfs.core.windows.net/container/server-schedule-predictions?upn=true&action=getAccessControl failed, reason: getaddrinfo ENOTFOUND storageaccount.dfs.core.windows.net\\\\n    at NodeFetchHttpClient.sendRequest (C:\\\\\\\\Users\\\\\\\\useralias\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\se-adls2-extension\\\\\\\\dist\\\\\\\\src\\\\\\\\index.js:2:65566)\\\\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)\\\\n    at async CoreHttpLogHttpClient.sendRequest (C:\\\\\\\\Users\\\\\\\\useralias\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\se-adls2-extension\\\\\\\\dist\\\\\\\\src\\\\\\\\index.js:2:673724)\\\\n    at async StorageRetryPolicy_StorageRetryPolicy.attemptSendRequest **

### Steps to Reproduce

1. Lunch the explorer
2. connect to the subscription 
3. Navigate to storage account and container
4. Trying to open the Manage ACLs getting the error

### Actual Experience

getting the error while opening the manage ACLs

### Expected Experience

should open the Manage ACLs and provide the option to add the user for permissions 

### Additional Context

nothing

**Comment by MRayermannMSFT** [comment]
@RamPatel58 can you, on the same machine & on the same network try, managing ACLs via the Azure Portal for the same account?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you continue encountering this problem, we recommend opening a support ticket via the Azure portal. Alternatively you can open a new issue here.
