### ISSUE TITLE
I can't open blob containers from different country on Microsoft Azure

### ISSUE THREAD

**Issue by potatogochan** [microsoft/AzureStorageExplorer#7513]
I need to connect to azure storage from my company in Korea, meanwhile I'm in Indonesia. 
I tried connecting with connection string and account name & key, both connection were successful, 
but I still can not open the the blob containers. 
when I click, "Authentication Error" page show up and there's this below details. 

Please help :(

This request is not authorized to perform this operation.

This storage account's 'Firewalls & virtual networks' settings may be blocking access to storage services. Try adding your client IP address to the firewall exceptions, or by allowing access from 'all networks' instead of 'selected networks'. To learn more about Azure Storage firewalls and virtual networks, visit http://go.microsoft.com/fwlink/?LinkId=845443.

Error Details:
{
  "name": "RestError",
  "code": "AuthenticationFailed",
  "statusCode": 403,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://megabox12.blob.core.windows.net/?comp=list&include=metadata",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2023-01-03"
        },
        "accept": {
          "name": "Accept",
          "value": "application/xml"
        },
        "user-agent": {
          "name": "User-Agent",
          "value": "Microsoft Azure Storage Explorer/1.32.0 (win32) azsdk-js-storageblob/12.15.0 (NODE-VERSION v18.16.1; Windows_NT 10.0.22621)"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "d5a12bb5-6027-474d-bd7d-57281ba618a1"
        },
        "x-ms-date": {
          "name": "x-ms-date",
          "value": "Tue, 14 Nov 2023 08:45:49 GMT"
        },
        "authorization": {
          "name": "Authorization",
          "value": "SharedKey Redacted"
        }
      }
    },
    "withCredentials": false,
    "timeout": 0,
    "keepAlive": true,
    "decompressResponse": false,
    "requestId": "d5a12bb5-6027-474d-bd7d-57281ba618a1"
  },
  "response": {
    "request": {
      "streamResponseStatusCodes": {},
      "url": "https://megabox12.blob.core.windows.net/?comp=list&include=metadata",
      "method": "GET",
      "headers": {
        "_headersMap": {
          "x-ms-version": {
            "name": "x-ms-version",
            "value": "2023-01-03"
          },
          "accept": {
            "name": "Accept",
            "value": "application/xml"
          },
          "user-agent": {
            "name": "User-Agent",
            "value": "Microsoft Azure Storage Explorer/1.32.0 (win32) azsdk-js-storageblob/12.15.0 (NODE-VERSION v18.16.1; Windows_NT 10.0.22621)"
          },
          "x-ms-client-request-id": {
            "name": "x-ms-client-request-id",
            "value": "d5a12bb5-6027-474d-bd7d-57281ba618a1"
          },
          "x-ms-date": {
            "name": "x-ms-date",
            "value": "Tue, 14 Nov 2023 08:45:49 GMT"
          },
          "authorization": {
            "name": "Authorization",
            "value": "SharedKey megabox12:BKV6h2qwMUypy218r8hq9gWcvykWfWKS5VLx0S/Nmuk="
          }
        }
      },
      "withCredentials": false,
      "timeout": 0,
      "keepAlive": true,
      "decompressResponse": false,
      "requestId": "d5a12bb5-6027-474d-bd7d-57281ba618a1"
    },
    "status": 403,
    "headers": {
      "_headersMap": {
        "content-length": {
          "name": "content-length",
          "value": "435"
        },
        "content-type": {
          "name": "content-type",
          "value": "application/xml"
        },
        "date": {
          "name": "date",
          "value": "Tue, 14 Nov 2023 10:47:31 GMT"
        },
        "server": {
          "name": "server",
          "value": "Microsoft-HTTPAPI/2.0"
        },
        "x-ms-error-code": {
          "name": "x-ms-error-code",
          "value": "AuthenticationFailed"
        },
        "x-ms-request-id": {
          "name": "x-ms-request-id",
          "value": "37adb668-001e-001b-66e7-16a709000000"
        }
      }
    },
    "bodyAsText": "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:37adb668-001e-001b-66e7-16a709000000\nTime:2023-11-14T10:47:32.5508568Z</Message><AuthenticationErrorDetail>Request date header too old: 'Tue, 14 Nov 2023 08:45:49 GMT'</AuthenticationErrorDetail></Error>",
    "parsedBody": {
      "message": "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:37adb668-001e-001b-66e7-16a709000000\nTime:2023-11-14T10:47:32.5508568Z",
      "code": "AuthenticationFailed",
      "AuthenticationErrorDetail": "Request date header too old: 'Tue, 14 Nov 2023 08:45:49 GMT'"
    },
    "parsedHeaders": {
      "errorCode": "AuthenticationFailed",
      "content-length": "435",
      "content-type": "application/xml",
      "date": "Tue, 14 Nov 2023 10:47:31 GMT",
      "server": "Microsoft-HTTPAPI/2.0",
      "x-ms-request-id": "37adb668-001e-001b-66e7-16a709000000"
    }
  },
  "details": {
    "errorCode": "AuthenticationFailed",
    "content-length": "435",
    "content-type": "application/xml",
    "date": "Tue, 14 Nov 2023 10:47:31 GMT",
    "server": "Microsoft-HTTPAPI/2.0",
    "x-ms-request-id": "37adb668-001e-001b-66e7-16a709000000",
    "message": "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:37adb668-001e-001b-66e7-16a709000000\nTime:2023-11-14T10:47:32.5508568Z",
    "code": "AuthenticationFailed",
    "AuthenticationErrorDetail": "Request date header too old: 'Tue, 14 Nov 2023 08:45:49 GMT'"
  }
}

**Comment by JasonYeMSFT** [comment]
@potatogochan Have you looked at your firewall settings as suggested by the error message "This storage account's 'Firewalls & virtual networks' settings may be blocking access to storage services. Try adding your client IP address to the firewall exceptions, or by allowing access from 'all networks' instead of 'selected networks'. To learn more about Azure Storage firewalls and virtual networks, visit http://go.microsoft.com/fwlink/?LinkId=845443."?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you continue encountering this problem, we recommend opening a support ticket via the Azure portal. Alternatively you can open a new issue here.
