### ISSUE TITLE
Can't re-execute table query after first executing 

### ISSUE THREAD

**Issue by royalone** [microsoft/AzureStorageExplorer#7516]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32

### Regression From

Is a regression from previous version but not sure which 

### Architecture

x64

### Storage Explorer Build Number

20231101.3

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Can't re-execute queries on tables 

### Steps to Reproduce

- Open a table
- Write a query
- Execute query
- Query works fine
- Cant click the button to run it again

### Actual Experience

- Execute the query
- "Execute query" button is now disabled and cannot be clicked
- F5 also does not re-run the query
- Need to refresh the table (ctrl-R) to be able to re-run the query

### Expected Experience

After our tables are updated externally to storage explorer, I want to re-run my query to see changes. Storage explorer used to allow this, so must be a regression.

**Comment by devmonster** [comment]
Related issue here. Seems like they will be adding it back

https://github.com/microsoft/AzureStorageExplorer/issues/7484

**Comment by MRayermannMSFT** [comment]
Hi, @devmonster is correct. We're going to bring back the behavior. Thanks for opening this issue and letting us know it is important to y'all. Hopefully the hotfix will be released soon, we're just wrapping up verifying a few more things. In the meantime, you can always download 1.31.2 here: https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.31.2 , and we've also paused the upgrade notification so you shouldn't be bothered by that while waiting for 1.32.1. Closing as duplicate.

**Comment by royalone** [comment]
Ok great, thanks. Sorry for the dupe, I hadn't checked closed tickets before I reported this.

**Comment by MRayermannMSFT** [comment]
> Ok great, thanks. Sorry for the dupe, I hadn't checked closed tickets before I reported this.

No worries! Ultimately, We'd rather have you open a duplicate than open nothing at all. :)
