### ISSUE TITLE
Error connecting to container

### ISSUE THREAD

**Issue by c-ortbauer** [microsoft/AzureStorageExplorer#7517]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.0

### Architecture

i86

### Storage Explorer Build Number

20231101.3

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Since a few days ago I can no longer access a Azure Storage Container in Storage Explorer.

It was working previously (for months) with an older version. The same error happend on the older version, I only updated in the hope of fixing it.

### Steps to Reproduce

1. Launch Storage Explorer
2. Expand Blob Container

### Actual Experience

Following error message pops up:
```
Unable to retrieve child resources

ProducerError:{
  "name": "Node Fetch Error",
  "message": "16140544:error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE:..\\..\\third_party\\boringssl\\src\\ssl\\tls_record.cc:592:SSL alert number 40\n",
  "stack": "Error: 16140544:error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE:..\\..\\third_party\\boringssl\\src\\ssl\\tls_record.cc:592:SSL alert number 40\n",
  "cause": {
    "cause": {
      "library": "SSL routines",
      "function": "OPENSSL_internal",
      "reason": "SSLV3_ALERT_HANDSHAKE_FAILURE",
      "code": "ERR_SSL_SSLV3_ALERT_HANDSHAKE_FAILURE"
    }
  },
  "code": "ERR_SSL_SSLV3_ALERT_HANDSHAKE_FAILURE"
}
```

### Expected Experience

Content of Container should be shown

**Comment by MRayermannMSFT** [comment]
@c-ortbauer

Can you try a copule of things?
1. Try, on the same machine & same network, viewing your container data via the Azure Portal, ideally with a Chromium derivative browser (e.g, Edge, Chromium, or Chrome), for the same account & container. If it works, let us know what browser it worked with.
2. Try enabling system proxy in storage explorer (Settings (gear on the left) > Application > Proxy > Choose 'system proxy' in the dropdown'). Let us know if that does or does not work.

**Comment by c-ortbauer** [comment]
Sorry for the delay, I just tried your suggestions:

1. I can view the blob storage data in the portal.azure.com Storage browser using Edge on the same machine without any issue.

2. After enabling the "Use system proxy" I got the following error message on the first try:

```
Unable to retrieve child resources

ProducerError:{
  "name": "Electron Net Error",
  "message": "net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH",
  "stack": "Error: net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH\n    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:50234)\n    at SimpleURLLoaderWrapper.emit (node:events:513:28)",
  "cause": {}
}
```

Now it just shows this message
`net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH`

**Comment by c-ortbauer** [comment]
The Issue was solved by our IT staff. Apperently the blob storage url had been automatically blocked by our company firewall.
