### ISSUE TITLE
Getting an issue after uninstall and install the latest version as well. 

### ISSUE THREAD

**Issue by sreethan1234** [microsoft/AzureStorageExplorer#7519]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.31.2

### Architecture

x64

### Storage Explorer Build Number

20231003.6

### Platform

Windows

### Bug Description

Getting an error after launching Azure Storage explorer, I have uninstalled and installed a same version and also new version but for every version it displays the same issue. 

Unable to retrieve child resources

ProducerError:{
  "name": "Error",
  "message": "{\"name\":\"Error\",\"code\":-32004,\"data\":{\"ClassName\":\"System.UnauthorizedAccessException\",\"Message\":\"Access to the path 'C:\\\\Users\\\\sthanu\\\\AppData\\\\Local\\\\.IdentityService\\\\StorageExplorer-552afc90145a469c8c31943595db4a66V3AccountStore.json' is denied.\",\"Data\":null,\"InnerException\":null,\"HelpURL\":null,\"StackTraceString\":\"   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)\\r\\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)\\r\\n   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)\\r\\n   at Microsoft.Developer.IdentityService.FileStore.StringFileStore.<>c__DisplayClass31_0.<<OpenLockedFileStreamAsync>b__0>d.MoveNext() in D:\\\\a\\\\_work\\\\1\\\\s\\\\src\\\\IdentityService\\\\Microsoft.Developer.IdentityService\\\\FileStore\\\\StringFileStore.cs:line 269\\r\\n--- End of stack trace from previous location ---\\r\\n   at Microsoft.Developer.IdentityService.FileStore.StringFileStore.WriteAsync(String data, CancellationToken cancellationToken) in D:\\\\a\\\\_work\\\\1\\\\s\\\\src\\\\IdentityService\\\\Microsoft.Developer.IdentityService\\\\FileStore\\\\StringFileStore.cs:line 162\\r\\n   at Microsoft.Developer.IdentityService.FileStore.StringFileStore.<>c__DisplayClass24_0.<<MutateAsync>b__0>d.MoveNext() in D:\\\\a\\\\_work\\\\1\\\\s\\\\src\\\\IdentityService\\\\Microsoft.Developer.IdentityService\\\\FileStore\\\\StringFileStore.cs:line 149\\r\\n--- End of stack trace from previous location ---\\r\\n   at Microsoft.Developer.IdentityService.FileStore.StringFileStore.ExecuteWithinLockAsync[U](Func`1 function, Nullable`1 retryCount, Nullable`1 retryWait, CancellationToken cancellationToken) in D:\\\\a\\\\_work\\\\1\\\\s\\\\src\\\\IdentityService\\\\Microsoft.Developer.IdentityService\\\\FileStore\\\\StringFileStore.cs:line 246\\r\\n   at Microsoft.Developer.IdentityService.FileStore.JsonFileStore`1.MutateAsync(Func`2 mutation, CancellationToken cancellationToken) in D:\\\\a\\\\_work\\\\1\\\\s\\\\src\\\\IdentityService\\\\Microsoft.Developer.IdentityService\\\\FileStore\\\\JsonFileStore.cs:line 67\\r\\n   at Microsoft.Developer.IdentityService.StorageService.FileAccountStorage.MutateAsync(Func`2 mutation, CancellationToken cancellationToken) in D:\\\\a\\\\_work\\\\1\\\\s\\\\src\\\\IdentityService\\\\Microsoft.Developer.IdentityService\\\\StorageService\\\\FileAccountStorage.cs:line 105\\r\\n   at Microsoft.Developer.IdentityService.StorageService.StorageServiceImpl.MutateStoreAsync(AccountKey accountWhichCausedMutation, Func`2 mutateFunction, CancellationToken cancellationToken) in D:\\\\a\\\\_work\\\\1\\\\s\\\\src\\\\IdentityService\\\\Microsoft.Developer.IdentityService\\\\StorageService\\\\StorageServiceImpl.cs:line 935\\r\\n   at Microsoft.Developer.IdentityService.StorageService.StorageServiceImpl.UpdateStateAsync(AccountKey account, Boolean stale) in D:\\\\a\\\\_work\\\\1\\\\s\\\\src\\\\IdentityService\\\\Microsoft.Developer.IdentityService\\\\StorageService\\\\StorageServiceImpl.cs:line 467\\r\\n   at Microsoft.Developer.IdentityService.StorageService.StorageService.EnsureInitializedAndExecuteAsync[T](Boolean overwrite, String prefix, Func`2 function, String caller) in D:\\\\a\\\\_work\\\\1\\\\s\\\\src\\\\IdentityService\\\\Microsoft.Developer.IdentityService\\\\StorageService\\\\StorageService.cs:line 342\\r\\n   at Microsoft.Developer.IdentityService.StorageService.StorageService.UpdateStateAsync(AccountKey account, Boolean stale) in D:\\\\a\\\\_work\\\\1\\\\s\\\\src\\\\IdentityService\\\\Microsoft.Developer.IdentityService\\\\StorageService\\\\StorageService.cs:line 230\",\"RemoteStackTraceString\":null,\"RemoteStackIndex\":0,\"ExceptionMethod\":null,\"HResult\":-2147024891,\"Source\":\"System.Private.CoreLib\",\"AssemblyName\":\"System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e\"}}"
}

### Steps to Reproduce

1.Launch Azure Storage explorer tool 
2. You see the error dialogue box after a min 

### Actual Experience

Unable to retrieve child resources

ProducerError:{
  "name": "Error",
  "message": "{\"name\":\"Error\",\"code\":-32004,\"data\":{\"ClassName\":\"System.UnauthorizedAccessException\",\"Message\":\"Access to the path 'C:\\\\Users\\\\sthanu\\\\AppData\\\\Local\\\\.IdentityService\\\\StorageExplorer-552afc90145a469c8c31943595db4a66V3AccountStore.json' is denied.\",\"Data\":null,\"InnerException\":null,\"HelpURL\":null,\"StackTraceString\":\"   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)\\r\\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)\\r\\n   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)\\r\\n   at Microsoft.Developer.IdentityService.FileStore.StringFileStore.<>c__DisplayClass31_0.<<OpenLockedFileStreamAsync>b__0>d.MoveNext() in D:\\\\a\\\\_work\\\\1\\\\s\\\\src\\\\IdentityService\\\\Microsoft.Developer.IdentityService\\\\FileStore\\\\StringFileStore.cs:line 269\\r\\n--- End of stack trace from previous location ---\\r\\n   at Microsoft.Developer.IdentityService.FileStore.StringFileStore.WriteAsync(String data, CancellationToken cancellationToken) in D:\\\\a\\\\_work\\\\1\\\\s\\\\src\\\\IdentityService\\\\Microsoft.Developer.IdentityService\\\\FileStore\\\\StringFileStore.cs:line 162\\r\\n   at Microsoft.Developer.IdentityService.FileStore.StringFileStore.<>c__DisplayClass24_0.<<MutateAsync>b__0>d.MoveNext() in D:\\\\a\\\\_work\\\\1\\\\s\\\\src\\\\IdentityService\\\\Microsoft.Developer.IdentityService\\\\FileStore\\\\StringFileStore.cs:line 149\\r\\n--- End of stack trace from previous location ---\\r\\n   at Microsoft.Developer.IdentityService.FileStore.StringFileStore.ExecuteWithinLockAsync[U](Func`1 function, Nullable`1 retryCount, Nullable`1 retryWait, CancellationToken cancellationToken) in D:\\\\a\\\\_work\\\\1\\\\s\\\\src\\\\IdentityService\\\\Microsoft.Developer.IdentityService\\\\FileStore\\\\StringFileStore.cs:line 246\\r\\n   at Microsoft.Developer.IdentityService.FileStore.JsonFileStore`1.MutateAsync(Func`2 mutation, CancellationToken cancellationToken) in D:\\\\a\\\\_work\\\\1\\\\s\\\\src\\\\IdentityService\\\\Microsoft.Developer.IdentityService\\\\FileStore\\\\JsonFileStore.cs:line 67\\r\\n   at Microsoft.Developer.IdentityService.StorageService.FileAccountStorage.MutateAsync(Func`2 mutation, CancellationToken cancellationToken) in D:\\\\a\\\\_work\\\\1\\\\s\\\\src\\\\IdentityService\\\\Microsoft.Developer.IdentityService\\\\StorageService\\\\FileAccountStorage.cs:line 105\\r\\n   at Microsoft.Developer.IdentityService.StorageService.StorageServiceImpl.MutateStoreAsync(AccountKey accountWhichCausedMutation, Func`2 mutateFunction, CancellationToken cancellationToken) in D:\\\\a\\\\_work\\\\1\\\\s\\\\src\\\\IdentityService\\\\Microsoft.Developer.IdentityService\\\\StorageService\\\\StorageServiceImpl.cs:line 935\\r\\n   at Microsoft.Developer.IdentityService.StorageService.StorageServiceImpl.UpdateStateAsync(AccountKey account, Boolean stale) in D:\\\\a\\\\_work\\\\1\\\\s\\\\src\\\\IdentityService\\\\Microsoft.Developer.IdentityService\\\\StorageService\\\\StorageServiceImpl.cs:line 467\\r\\n   at Microsoft.Developer.IdentityService.StorageService.StorageService.EnsureInitializedAndExecuteAsync[T](Boolean overwrite, String prefix, Func`2 function, String caller) in D:\\\\a\\\\_work\\\\1\\\\s\\\\src\\\\IdentityService\\\\Microsoft.Developer.IdentityService\\\\StorageService\\\\StorageService.cs:line 342\\r\\n   at Microsoft.Developer.IdentityService.StorageService.StorageService.UpdateStateAsync(AccountKey account, Boolean stale) in D:\\\\a\\\\_work\\\\1\\\\s\\\\src\\\\IdentityService\\\\Microsoft.Developer.IdentityService\\\\StorageService\\\\StorageService.cs:line 230\",\"RemoteStackTraceString\":null,\"RemoteStackIndex\":0,\"ExceptionMethod\":null,\"HResult\":-2147024891,\"Source\":\"System.Private.CoreLib\",\"AssemblyName\":\"System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e\"}}"
}

**Comment by JasonYeMSFT** [comment]
@sreethan1234 What environment are you running Storage Explorer within? It seems like you are trying to run Storage Explorer in a virtualized environment because I see this "D:\\a\\_work\\1\\s\\"? Storage Explorer assumes that the application has access to certain directories under the user machine. I am not sure if the application can access those directories under a virtualized environment.

**Comment by sreethan1234** [comment]
Thanks for the response Jason, it’s not virtualized, I just use it my local and however i have be using it for a year it was working till couple weeks ago, I have not done any changes but it suddenly started giving error

**Comment by JasonYeMSFT** [comment]
OK. Could you check what user you are running Storage Explorer as (e.g. is it sthanu)? If so, could you try to manually access the directory specified in the error message and see if it is allowed?

**Comment by sreethan1234** [comment]
Sorry for the late reply, yes Jason its sthanu and I am able to access it manually, since the explorer is not working i have setup PWA tool, i work in either PWA or portal.azure ( i know both are same). but yeah it works fine without any issues.

**Comment by JasonYeMSFT** [comment]
@sreethan1234 I couldn't think of anything on our end that would trigger this problem. I suggest you to look at your local security settings and see if Storage Explorer isn't given enough permission to access certain file system locations. You may try elevating its privileges and see if that resolves the issue.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you still need help with this problem, we recommend opening a support ticket via the Azure Portal. Alternatively you can open a new issue. This issue will no longer be monitored.
