### ISSUE TITLE
Avro test file does not create Avro files with long type

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#7521]
We need it to so we can test Avro preview thoroughly! Please either update the script to generate files which result in Storage Explorer having to handle `long` values or check in a diverse set of test files to the `file-preview` folder. Then, test existing functionality and either fix, or open issues for, any bugs found.

**Comment by craxal** [comment]
To be more precise, what we need here is some functionality to handle Avro `long` types correctly and some tests to ensure that handling functions correctly.

JavaScript `bigint` can hold Avro `long` values, but writing/parsing values that extend beyond the safe integer boundaries of JavaScript `number` become problematic. Specifically, JSON doesn't like `bigint`.

Rather, we ought to do something similar to what we did for dates. We can represent `long` values with `BigIntLike` type that's just an object with a string value representation.
