### ISSUE TITLE
The whole path is displayed on the selected folder/files field instead of the item name when uploading an item

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7522]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20231116.2
**Branch**: main
**Platform/OS**: Windows 10
**Architecture**: x64
**How Found**: From running test cases
**Regression From**: Previous release (1.32.1)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Click 'Upload -> Upload Folder...'.
3. Choose one folder -> Click 'Select Folder'. 
4. Observe the 'Selected folder' field on the 'Upload Folder' dialog.
5. Check whether only the folder name is displayed.

## Expected Experience ##
Only the folder name is displayed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/7dbb6835-7999-494b-9c3c-4bb7281d3bbf)

## Actual Experience ##
The whole path is displayed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/e223e4a1-6736-48f5-9c4a-1411c310d461)

## Additional Context ##
This issue only reproduces on Windows platform.

**Comment by MRayermannMSFT** [comment]
Some work in this dialog is in flux. Will be wrapped up soon.

**Comment by v-xianya** [comment]
Verified this issue on the build 20231117.3. Fixed. So, we are going to close it.
