### ISSUE TITLE
Virtual directories not shown anymore

### ISSUE THREAD

**Issue by gibimani** [microsoft/AzureStorageExplorer#7524]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.1 (96)

### Regression From

1.31.2

### Architecture

x64

### Storage Explorer Build Number

20231114.10

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Opening a container doesn't show any virtual directories anymore. Although this bug doesn't always show up, some container listings works as expected.

### Steps to Reproduce

1. Open a container wich includes a couple of virtual directories and some blobs.
2. The blobs will be shown, the virtual directories not.
3. Click the "Load more" button in the lower right corner. Now the virtual directories will be shown.
4. Enter a virtual directory and leave it. Now the virtual directories are missing again.

### Actual Experience

No virtual directories are shown when opening a container. Clicking "Load more" reloads the view and lists all virtual directories. Refreshing the view with the "Refresh" button doesn't list the virtual directories neither. This bug does not occur with all containers. Actually affected is a container with a larger number of blobs, for containers with a smaller number of blobs everthing is working as expected.

**Comment by MRayermannMSFT** [comment]
Hi @gibimani , depending on what the server returns, this behavior is possible. However, the servers shouldn't return things differently to different versions of Storage Explorer, so I would be surprised if the behavior for the **same container** would be different for two versions of Storage Explorer (assuming there isn't a bug in 1.32 haha).

For this issue, I think it would be best if we could get a Fiddler trace from you.

You can download Fiddler here: https://www.telerik.com/fiddler/fiddler-classic
Instructions on how to collect the trace are here: https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/storage-explorer-troubleshooting?tabs=Windows#network-logs

Please send your trace to sehelp `at-sign` microsoft dot com (hopefully you can parse out that email address, I'm trying to avoid it getting picked up by spam bots).
