### ISSUE TITLE
Fail to restore file share snapshot with error 'Unexpected Cancel'

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7525]
**Storage Explorer Version:** 1.33.0-dev (96)
**Build Number:** 20231119.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Sonoma 14.0(Apple M1 Pro)
**Architecture:** x64/x64/arm64
**How Found:** From running test cases
**Regression From:** Previous release (1.32.1)

## Steps to Reproduce ##

1. Expand one storage account -> File Shares.
2. Open one file share -> Upload a file.
3. Right click the file share -> Click 'Create Snapshot'.
4. Switch to snapshots view -> Open the file share snapshot.
5. Select the file -> Click 'Restore Snapshot'.
6. Check whether succeeds to restore snapshot.

## Expected Experience ##
Succeed to restore snapshot.

## Actual Experience ##
Fail to restore snapshot.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/be169c5e-337c-4fc8-93a0-81a66e1305dd)

**Comment by JasonYeMSFT** [comment]
A fix has been merged.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20231121.2. Fixed. So, we are going to close it.
