### ISSUE TITLE
Fail to delete one blob under one OAuth attached regular/ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7527]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20231121.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.1 (Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.32.1)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Attach the blob container via OAuth (make sure give the correct RBAC role).
3. Upload one blob to the attached blob container.
4. Try to delete the blob.
5. Check whether succeeds to delete the blob.

## Expected Experience ##
Succeed to delete the blob.

## Actual Experience ##
Fail to delete the blob.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/a68fac22-f2a3-4ec2-8d9a-790ba3e01d5e)

Error details:
`{
  "name": null,
  "message": "\"failed to perform remove command due to error: cannot start job due to error: cannot list files due to reason get cached token failed in Token Store Mode(SE), segmented token broken, failed to read azcopy/aadtoken/4980/18, Element not found..\\n\""
}`

**Comment by v-xianya** [comment]
Verified this issue on the main build 20231121.9. Reproduce. So, we are going to close it.

**Comment by MRayermannMSFT** [comment]
@v-xianya I don't reproduce either this on 20231121.9. Can you please share (make sure Storage Explorer log level is set to debug before reproducing):
1. All Storage log files
2. The AzCopy log file

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT Here is the storage log files. there is no AzCopy log for the delete action.

[2023-11-22_172528.zip](https://github.com/microsoft/AzureStorageExplorer/files/13445464/2023-11-22_172528.zip)

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240110.12. Fixed. So, we are going to close it.
