### ISSUE TITLE
Fail to upload one file to subfolder under one regular/ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7528]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20231121.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.1 (Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.32.1)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Attach the blob container via OAuth (make sure give the correct RBAC role).
3. Go to the attached blob container -> Create a new folder.
4. Upload one file to the folder.
5. Check whether succeeds to upload the file.

## Expected Experience ##
Succeed to upload the file.

## Actual Experience ##
Fail to upload the file.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/79379752-650f-472c-88a1-8deae81add66)

## Additional Context ##
1. Here is the Azcopy log:
[995425c0-b37d-8142-544c-50e5723537e7.log](https://github.com/microsoft/AzureStorageExplorer/files/13424850/995425c0-b37d-8142-544c-50e5723537e7.log)

2. Fail to upload one folder to OAuth attached regular/ADLS Gen2 blob containers.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20231121.9. Reproduce. So, we are going to close it.

**Comment by MRayermannMSFT** [comment]
@v-xianya I don't reproduce either this on 20231121.9. Can you please share (make sure Storage Explorer log level is set to debug before reproducing):
1. All Storage log files
2. The AzCopy log file

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT 
1. All Storage log files
[2023-11-22_172528.zip](https://github.com/microsoft/AzureStorageExplorer/files/13445489/2023-11-22_172528.zip)


2. The AzCopy log file
[4680ddbc-b731-694f-42e8-3ad88bac5ff8.log](https://github.com/microsoft/AzureStorageExplorer/files/13445483/4680ddbc-b731-694f-42e8-3ad88bac5ff8.log)

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240110.12. Fixed. So, we are going to close it.
