### ISSUE TITLE
It doesn’t focus on the downloaded blob after clicking Open Folder 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#753]
Storage Explorer Version: 1.4.3
 Platform/OS Version: Linux Ubuntu 16.04
 Architecture: x64
 Build Number: 20181010.1
 Commit: 39ec4ed9
 Regression From: Not a regression

#### Steps to Reproduce: ####
1. Open a blob container which contains at least one blob then select a blob to download.
2. Click Open Folder in Activities after downloading successfully.
3. Check whether the downloaded blob is focused or not.

#### Expected Experience: ####
The downloaded blob is focused.

#### Actual Experience: ####
The downloaded blob doesn’t be focused.

**Comment by MRayermannMSFT** [comment]
v-xianya does this still repro in the latest builds?

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT 
This issue still reproduces on the latest build 20200201.2. 
The folder 'ClouldExplorer' is download to '/Home/v-xianya/Desktop'. 

'Home' is focused after clicking Open Folder in Activities panel. Like below.
![image](https://user-images.githubusercontent.com/41351993/73650276-bbfdf480-46bc-11ea-9e1e-9fe9f7967cb8.png)

**Comment by MRayermannMSFT** [comment]
Le'ts make sure that on every platform:

1. Downloading one thing, the file browser that is opened should focus that thing
2. Downloading more than one thing, focus the first item in the folder that the things were downloaded to

**Comment by v-xianya** [comment]
@MRayermannMSFT 

**On Winddows:**
1. Download one file, the downloaded file is focused.
![image](https://user-images.githubusercontent.com/41351993/73714024-81429d80-474a-11ea-83b0-6d5b01c5fabe.png)
2. Download more than one file (or one folder), the parent directory is focused.
![image](https://user-images.githubusercontent.com/41351993/73714586-3aee3e00-474c-11ea-9137-b3552812a1f6.png)

**On Linux:**
1. Download one file, the parent directory is focused.
![image](https://user-images.githubusercontent.com/41351993/73714689-a46e4c80-474c-11ea-8f3a-c995652229d4.png)
2. Download more than one file (or one folder), the Home diretory is focused.
![image](https://user-images.githubusercontent.com/41351993/73714839-0dee5b00-474d-11ea-9a02-90b5e59e8f43.png)

**Comment by MRayermannMSFT** [comment]
@v-xianya here's the behavior we decided on:
1. The action has been renamed "Show in Folder"
2. After clicking that action, if downloading 1 thing, then the thing should be focused when the file explorer appears
3. After clicking that action, if downloading many things, then the contents of the destination folder should be shown when the file explorer appears, it is possible that none of the items in the file explorer will be focused

**Comment by MRayermannMSFT** [comment]
fix merged into main

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT 
Verified this issue on build 20210205.4. Things doesn't work as expected for the **2 & 3** behaviors. So we re-open it.

On Windows, works fine.
On Linux, the behaviors as below：

1. The action has been renamed "Show in Folder"  -> Done
2. **After clicking that action, The parent folder is focused whenever downloading one things or many things.**
![linux](https://user-images.githubusercontent.com/41351993/106997881-9f5c3700-67be-11eb-9183-35b17290ea80.gif)

**Comment by MRayermannMSFT** [comment]
That looks to be an issue from Electron: https://github.com/electron/electron/issues/14462

We have another bug open which covers this: https://github.com/microsoft/AzureStorageExplorer/issues/2820

So I'm going to close this one, and 2820 can cover the Linux specific issue. Thank you @v-xianya!

**Comment by v-xianya** [comment]
@MRayermannMSFT Ok. got it.
