### ISSUE TITLE
The colors of the two action icons for the node 'App Configurations' are inconsistent

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7533]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20231123.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.1 (Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: AD-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Select 'App Configuration' node.
2. Go to Actions panel.
3. Observe the colors of the two action icons.
4. Check whether the colors are consistent.

## Expected Experience ##
The colors are consistent.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/5c017699-1a95-4421-9ca9-32481d32c17d)

## Actual Experience ##
The colors are inconsistent.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/949d1438-1ceb-4f8e-89cd-c8d854ff3152)

**Comment by JasonYeMSFT** [comment]
This issue is fixed in the 0.2.2 app config extension release.

**Comment by v-xianya** [comment]
Verified on the main build 20240321.3 with the 0.2.2 app config extension release. Fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/d74665ce-2ebd-4aac-8ac3-5ede4e9a1f25)
