### ISSUE TITLE
esbuild script not generating JavaScript files with a .js extension

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#7534]
The file extension is not required by node, however, when analyzing app size, it is helpful for the files to have their extension so we can see "how much of app size is taken up by JavaScript files".

**Comment by JasonYeMSFT** [comment]
The path of the files are inferred from the path we declared in the package.json. If we want to preserve the extension, we should make sure the path in the package.json has the .js extension.
