### ISSUE TITLE
The 'Settings -> Transfer -> AzCopy Command Shell Language' part is not localized

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7535]
**Storage Explorer Version:** 1.33.0-dev (96)
**Build Number:** 20231128.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.1 (Apple M1 Pro)
**Reproduce Languages:** All languages
**Architecture:** x64/x64/arm64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select '日本語' -> Restart Storage Explorer.
3. Go to 'Settings -> Transfer'.
4. Check whether all strings are localized.

## Expected Experience ##
All strings that should be localized have been localized.

## Actual Experience ##
The 'AzCopy Command Shell Language' part is not localized.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/e0174c82-13ca-4c48-a03e-d15fca963844)

**Comment by MRayermannMSFT** [comment]
Will track loc progress.
