### ISSUE TITLE
The localized view options panel is incomplete

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7537]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20221128.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.6 (Apple M1 Pro)
**Reproduce Languages**: Russian/German/French/Hungarian/Dutch 
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select 'русский' -> Restart Storage Explorer.
3. Expand one storage account -> Blob Containers.
4. Open one blob container -> Press Ctrl+F.
5. Check shows a complete view options panel.

## Expected Experience ##
Show a complete view options panel.

## Actual Experience ##
Show an incomplete view options panel.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/6abcc059-9693-49ea-be20-137b8654f2f6)

## Additional Context ##
This issue doesn't reproduce on Czech/Spanish/Italian/Japanese/Polish/Portuguese/Portuguese/Swedish/Turkish/Korean/Chinese (simplified)/Chinese (traditional).

**Comment by JasonYeMSFT** [comment]
The panel is not incomplete. It overflows the available space and uses a scrollbar to let users view the overflowing portions of the panel.
