### ISSUE TITLE
MASE has high processor usage when using azcopy

### ISSUE THREAD

**Issue by GitPeterJ** [microsoft/AzureStorageExplorer#7538]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.0

### Architecture

i86

### Platform

All

### OS Version

Windows 10

### Bug Description

Whenever I use MASE to copy bodies of files to a new directory the processor usage spikes to 100%, memory usage increases to more than 3 GB, network usage increases to maximum bandwidth and my machine overall unresponsive. I would expect that azcopy performs this transaction in the cloud as it's to the same blob storage account, so why does my machine get taxed like that?

### Steps to Reproduce

1. Copy large amount of files or a container to new destination
2. Check control panel to see increased usage

### Actual Experience

While cloning a blob container my machine become almost unresponsive like described above.

### Expected Experience

Minimal strain on my machine as I only need to know the progress of the transaction.

**Comment by MRayermannMSFT** [comment]
Hi @GitPeterJ,

> I would expect that azcopy performs this transaction in the cloud as it's to the same blob storage account, so why does my machine get taxed like that?

Great question! For server to server copies (which is what it sounds like you are asking about), the transferring of data does not take place in the cloud. Instead, AzCopy asks the source server for the data in your blob/s, stores that in local memory, and then sends that data to the destination server.

Why does it do this? From my understanding, there are two main reasons:

1. Sometimes the source and destination servers are unable to talk to each other. There's a variety of reasons why this might be.
2. Although there is a server-side copy API, it is not performant. The API is less of a "hey server, do this copy", and more of a "hi server, please do this copy when you have time". Or in other words, the API simply tells the server to schedule the copy, there is no guarantee about when it will happen. Sometimes it may be immediate, sometimes it could take a few days. 

So with that in mind, if AzCopy is using too much system resources when performing operations, there are settings in Storage Explorer you can use to reign it in. If you go to Settings (gear on the left) > Transfers > AzCopy, you can find a multitude of settings related to AzCopy performance. In my experience, the best one to try changing is the "Network Concurrency", and to try changing it to "Adjust dynamically". If you have further questions regarding these settings, feel free to ask.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you have further questions, please open a new issue.
