### ISSUE TITLE
The blob access tier is not updated after replacing it with the same blob whose access tier is 'Cold'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7542]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20231201.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.6 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.32.1)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob with the default access tier.
3. Upload the same blob with 'Cold' access tier.
4. There is a conflict dialog -> Apply 'Replace'.
5. Check whether the access tier of the blob is updated to 'Cold'.

## Expected Experience ##
The access tier of the blob is updated to 'Cold'.

## Actual Experience ##
The access tier of the blob is not updated.

**Comment by JasonYeMSFT** [comment]
This issue has been fixed in the latest AzCopy candidate. We need to upgrade to the latest version of AzCopy to fix this issue in Storage Explorer.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240110.12. Fixed. So, we are going to close it.
