### ISSUE TITLE
The access tier is not preserved when cloning/copying one blob whose access tier is 'Cold' with setting 'Preserve Blob Access Tier' enabled

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7543]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20231201.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.6 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.32.1)

## Bug Descriptions ##
1. The blob access tier always shows as default when uploading with 'Cold'.
2.  The access tier is not preserved when cloning/copying one blob whose access tier is 'Cold' with setting 'Preserve Blob Access Tier' enabled.

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
3. Create a blob container -> Upload one blob -> Change the blob access tier to 'Cold'.
4. Go to 'Settings'-> Enable the setting 'Preserve Blob Access Tier.'
5. Clone the blob.
6. Check whether the access tier of the cloned blob is 'Cold'.

## Expected Experience ##
The access tier of the cloned blob is 'Cold'.

## Actual Experience ##
The access tier of the cloned blob is the default access tier.

**Comment by JasonYeMSFT** [comment]
This issue has been fixed in the latest AzCopy candidate. We need to upgrade to the latest version of AzCopy to fix this issue in Storage Explorer.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240110.12. Fixed. So, we are going to close it.
