### ISSUE TITLE
Fail to copy and rehydrate an archive blob to a blob under the same storage account with cold access tier

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7544]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20231201.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.6 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob with 'Archive' access tier.
3. Select the blob -> Click 'Copy' -> Click 'Paste'.
4. Type a valid blob name -> Change the access tier to 'Cold'.
5. Check whether succeeds to execute copy and rehydrate.

## Expected Experience ##
Succeed to execute copy and rehydrate.

## Actual Experience ##
Fail to execute copy and rehydrate.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/ec5c56c1-3939-4876-9d93-8be5c43a725d)
Error details:
`  "message": "One of the request inputs is not valid.\nRequestId:5bec2279-301e-0057-7633-244cc3000000\nTime:2023-12-01T08:50:24.8762471Z",`

![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/fbde07c9-cb5c-49be-b3e4-2cee3adc4a77)

## Additional Context ##
1. This issue doesn't reproduce for ADLS Gen2 blobs.
2. This issue doesn't reproduce for clone and rehydrate.
3. This issue doesn't reproduce if paste the archive blob to different storage account (in the same region).

**Comment by JasonYeMSFT** [comment]
Maybe this is because of the empty header values?

**Comment by JasonYeMSFT** [comment]
I can reproduce this issue using clone and rehydrate. It seems to be related to the cold tier.

**Comment by MRayermannMSFT** [comment]
Let's determine if this really is a service issue, and if so, either open ICM or email owning PM.

**Comment by JasonYeMSFT** [comment]
The service team has applied a mitigation and I verified the fix.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20231221.5. Fixed.
