### ISSUE TITLE
Fail to delete one regular blob whose access tier is 'Archive (rehydrating to Cold)'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7545]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20231201.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.1.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob with 'Archive' access tier.
3. Right click the archive blob -> Change the access tier to 'Cold'.
4. Delete the blob.
5. Check whether succeeds to delete it.

## Expected Experience ##
Succeed to delete the blob.

## Actual Experience ##
Fail to delete the blob.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/e712ddc0-b4d2-4e77-ad42-1c48037c1ff4)

Error:
`RESPONSE Status: 400 One of the request inputs is not valid.`
## Additional Context ##
1. AzCopy log:
[aab3362f-8010-bb4d-74b4-a72cfba44cf9.log](https://github.com/microsoft/AzureStorageExplorer/files/13523583/aab3362f-8010-bb4d-74b4-a72cfba44cf9.log)
2. This issue doesn't reproduce for ADLS Gen2 blobs.

**Comment by JasonYeMSFT** [comment]
Maybe this is because of the empty header values?

**Comment by MRayermannMSFT** [comment]
Let's determine if this really is a service issue, and if so, either open ICM or email owning PM.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240110.12. Fixed. So, we are going to close it.
