### ISSUE TITLE
Opening table from emulator always results in 'The query condition specified in the request is invalid.'

### ISSUE THREAD

**Issue by OzBob** [Microsoft/AzureStorageExplorer#7549]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.1 (96)

### Architecture

x64

### Storage Explorer Build Number

20231114.10

### Platform

Windows

### OS Version

Windows 11

### Bug Description

On Windows 11, with Visual Studio Prof 2022 (Version 17.7.0 Preview 5.0), Azurite (v14.20.0.0 from: C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\Extensions\Microsoft\Azure Storage Emulator\azurite.exe)
Get error: "The query condition specified in the request is invalid."

### Steps to Reproduce

When run Azure Function project in debug
Then open Microsoft Azure Storage Explorer
Then open 'local storage emulator'
Open: Queue OK
Open: Blob OK
Open: Table 
Get error: "The query condition specified in the request is invalid."

### Actual Experience

No Local tables:
![image](https://github.com/microsoft/AzureStorageExplorer/assets/1796771/6f1d5134-c5c3-45d2-a296-5f7764afb6cf)

### Additional Context

I will update VS to the latest build and report back.

FYI, previoulsy, if i restart my computer and do not open visual studio, but run:
```
azurite.exe" --silent --location c:\azurite --debug c:\azurite\debug.log --loose
```

The **--loose** used to make all the difference, but not now.

Due to my version being very high, this is NOT a duplicate of these AzureStorageExplorer issues:

1. https://github.com/microsoft/AzureStorageExplorer/issues/7511
2. https://github.com/microsoft/AzureStorageExplorer/issues/7485
3. https://github.com/microsoft/AzureStorageExplorer/issues/5746 

It may be related to the Azurite issue: https://github.com/Azure/Azurite/issues/1573

What is the default query being sent from StorageExplorer to Azurite?

**Comment by craxal** [comment]
@OzBob Can you confirm the version of Azurite you are using? Version 14 isn't a valid version at this time (the latest is 3.28.0).

Also, we're working on a workaround. Here's a link to a download for a private build. Can you install this build and see if your issue is resolved?

https://cralvordtest02.blob.core.windows.net/share/1.33.0-table.1/StorageExplorer-windows-x64.exe?sv=2023-01-03&st=2023-12-05T00%3A20%3A13Z&se=2023-12-09T00%3A20%3A00Z&sr=b&sp=r&sig=0qzMeJwB9xDqbig6XpRhQXkiGTo%2BtF6wsmvVmE7xmVs%3D

**Comment by OzBob** [comment]
FYI: workaround: enter in query:
PartitionKey > "" 
this returns all rows
![image](https://github.com/microsoft/AzureStorageExplorer/assets/1796771/3b84958b-a603-46c1-b90c-b08d4530c8a4)

**Comment by OzBob** [comment]
@craxal the versioning is unexpected

https://github.com/Azure/Azurite/releases does show "2023.11 Version 3.28.0" as the latest version but, going to "C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\Extensions\Microsoft\Azure Storage Emulator" and right clicking **azurite.exe** | Properties | File Version = "v14.20.0.0"

![image](https://github.com/microsoft/AzureStorageExplorer/assets/1796771/7c755b4d-244a-44d5-a98b-2ec594596a6e)

```
c:\azurite>"c:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\Extensions\Microsoft\Azure Storage Emulator\azurite.exe" --version
```
Mine returns: **3.24.0**

I will update Visual Studio and see what version is gifted unto me... if that doesn't improve things I'll use your pirvate build link (thank you!)

**Comment by mikejwhat** [comment]
> @mikejwhat Did you try the earlier download link to the private build? Is the issue resolved for you in that build?

Yes looks like that one is working nicely thanks!

**Comment by craxal** [comment]
We've merged the change, which will be available in our next release.
