### ISSUE TITLE
Storage account queues are not being presented in storage Explorer

### ISSUE THREAD

**Issue by fabiosterchille** [microsoft/AzureStorageExplorer#755]
**Storage Explorer Version**: 1.4.2
**Platform/OS Version**: Windows 10 - 1809
**Architecture**: ia32
**Regression From**: 

#### Steps to Reproduce: ####
1. 
2. 

#### Expected Experience: ####
When you click queue, you can see the existing

#### Actual Experience: ####
Storage account queues are not being presented in storage Explorer. Through the portal, you need to click load more to be Presented.
![after load more](https://user-images.githubusercontent.com/44057921/46801094-06bd6580-cd30-11e8-9473-55fc576a96c5.png)
![before load more](https://user-images.githubusercontent.com/44057921/46801095-06bd6580-cd30-11e8-86a2-420fdb33b72c.png)
![queue](https://user-images.githubusercontent.com/44057921/46801096-06bd6580-cd30-11e8-843a-f2ec43a68e15.png)

**Comment by MRayermannMSFT** [comment]
Hmmm this is odd. @fabiosterchille , can you try clicking on your storage account, and then looking at the properties panel (below the tree), and check to see that you have a connection string?

**Comment by TiTi** [comment]
I'm also having this issue with current stable version
```
[Content]
Version: 1.10.1
AzCopy Version: 10.2.1
```

It was working on previous versions.
This is not a RBAC issue, i tried with 2 identities which have access to the queue (it works from the portal).

Blob containers, File shares & Tables work, but not Queues :-/

![image](https://user-images.githubusercontent.com/137691/66382906-50c93d80-e9bc-11e9-91f9-4ee2db603a29.png)

**Comment by MRayermannMSFT** [comment]
Can y'all test against Storage Explorer 1.12.0? If you're still not seeing your queues can you do the following:

1. Click on your Storage Account in the tree view
2. Look at the properties grid in the bottom left
3. Tell us if you see the "Primary Key" and "Secondary Key" properties:
![image](https://user-images.githubusercontent.com/21112697/73206730-50ce8400-40f8-11ea-85d3-ccc4709d72bb.png)

**Comment by TiTi** [comment]
With 1.11.2, i do not have the issue anymore
It also work fine after 1.12.0 installation 😃 

For me, this issue is resolved 😄
