### ISSUE TITLE
The error for 'Destination blob name' field doesn't change if empty 'Destination blob container' and 'Destination blob name' fields

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7550]
**Storage Explorer Version:** 1.33.0-dev (96)
**Build Number:** 20231203.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.1.1(Apple M1 Pro)
**Architecture:** x64/x64/arm64
**How Found:** Ad-hoc testing
**Regression From:** Previous release (1.28.1)

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create one blob container -> Upload one archive blob.
3. Right click the blob -> Click 'Clone and Rehydrate...'.
4. The error 'A blob with the same name already exists' displays for the 'Destination blob name' filed.
5. Empty 'Destination blob container' and 'Destination blob name' fields respectively.
6. Check whether the error for 'Destination blob name' field changes.

## Expected Experience ##
The error for 'Destination blob name' field changes.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/a3080327-f19a-4465-9831-71790d46ec21)

## Actual Experience ##
The error for 'Destination blob name' field doesn't change.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/c054eded-a2d2-4d38-b55f-46ebb25d3fe9)

## Additional Context ##
This issue also reproduces if empty 'Destination blob name' and 'Destination blob container' fields respectively then type a name for the 'Destination blob name' field.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/de693596-29f3-4f26-86b6-aa5f90e7d35b)

**Comment by JasonYeMSFT** [comment]
It doesn't make sense to validate blob name when the container name is invalid. We will show no validation error for blob name when the container name is invalid.

**Comment by v-kellyluo** [comment]
@JasonYeMSFT , verified this issue on the build 20231205.1, there is no validation error for the 'Destination blob name' field if empty the two fields. But the error doesn't disappear if empty 'Destination blob container' field then type a valid name:
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/102588d3-921c-4acb-aaa9-62880a73cc4b)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20231208.2. Fixed. So, we are going to close it.
