### ISSUE TITLE
Unable to download anonymous files via CDN endpoint

### ISSUE THREAD

**Issue by 11braemm** [microsoft/AzureStorageExplorer#7551]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.1

### Regression From

n/a

### Architecture

x64

### Storage Explorer Build Number

20231114.10

### Platform

All

### Bug Description

You are unable to download anonymous files via a CDN endpoint using microsoft azure storage explorer. Copying the URL of files into an icognito browser allows them to be downloaded without issue.

I have created an example storage account and CDN with test files to demonstrate this bug at 
anonymous-access-a9engahagrb4dudx.z01.azurefd.net 
which resolves to https://aseanonymouscdnbugdemo.blob.core.windows.net/

There are 5 demo txt files in a container called ase-bug-demo

Attepting to download the files by accessing the storage account directly works fine but when accessing via the CDN the files can be previewed but there is an error on attempting to download them

### Steps to Reproduce

1. Add a new blob container with address
https://aseanonymouscdnbugdemo.blob.core.windows.net/ase-bug-demo

This is accessing the storage account directly, files should be accessible and downloadable

2. Add a new blob container with address
https://anonymous-access-a9engahagrb4dudx.z01.azurefd.net/ase-bug-demo

This is accessing the blob container through a public cdn

Files are now previewable but not downloadable

If you copy the url's of files into browsers they also can be seen

### Actual Experience

You receive an error when trying to download files via the CDN

### Expected Experience

Files should be downloadable via the CDN

**Comment by MRayermannMSFT** [comment]
@11braemm point of clarification, are the blobs themselves publicly accessible? Or in other words, is public read access enabld on the container containing the blobs?

**Comment by 11braemm** [comment]
Yes public read is enabled on the blobs, which is why they can be previewed all fine via ASE or other means. And downloaded via the url in a browser

**Comment by MRayermannMSFT** [comment]
@11braemm what error are you getting? I just tried with the containers you linked and everything worked great. Here's my AzCopy log file as proof:

[64672c96-d0d0-e24f-71ba-1e83abe932b2.log](https://github.com/microsoft/AzureStorageExplorer/files/13573009/64672c96-d0d0-e24f-71ba-1e83abe932b2.log)

**Comment by 11braemm** [comment]
Here's my log file
[e6f6ba9d-a2c4-1149-4789-652b9f75d63b.log](https://github.com/microsoft/AzureStorageExplorer/files/13573886/e6f6ba9d-a2c4-1149-4789-652b9f75d63b.log)

It looks like the error is
`DOWNLOADFAILED: https://anonymous-access-a9engahagrb4dudx.z01.azurefd.net/ase-bug-demo/demo-file-0.txt/demo-file-0.txt : 404 : 404 The specified blob does not exist.. When Downloading response body. X-Ms-Request-Id: 32c42eec-e01e-0070-07d0-275733000000`

It seems to be trying to access 
`https://anonymous-access-a9engahagrb4dudx.z01.azurefd.net/ase-bug-demo/demo-file-0.txt/demo-file-0.txt`
instead of just
`https://anonymous-access-a9engahagrb4dudx.z01.azurefd.net/ase-bug-demo/demo-file-0.txt`

I am not sure why

**Comment by 11braemm** [comment]
Though other times I seem to get an error like this

![image](https://github.com/microsoft/AzureStorageExplorer/assets/24542587/6e697c13-70cc-48fb-b5f5-1e03fb81e3a7)

There then isn't an option to open a log file, only to `Copy AzCopy Command to Clipboard` which is the following
```

$env:AZCOPY_CONCURRENCY_VALUE = "AUTO";
./azcopy.exe copy "https://anonymous-access-a9engahagrb4dudx.z01.azurefd.net/ase-bug-demo/demo-file-0.txt" "C:\Users\emmbra\Downloads\demo-file-0.txt" --overwrite=prompt --check-md5 FailIfDifferent --from-to=BlobLocal --recursive --log-level=INFO;
$env:AZCOPY_CONCURRENCY_VALUE = "";
```

**Comment by MRayermannMSFT** [comment]
@11braemm you can update the version of AzCopy used by performing the following steps:
1. Use file explorer and go to where you have Storage Explorer installed
2. Then, navigate into `resources\app\node_modules\@azure-tools\azcopy-win64\dist\bin`
3. Drag and drop a new version of AzCopy into this folder, with the same file name

We will be updating AzCopy for our 1.33.0 release early next year.

**Comment by 11braemm** [comment]
Thanks so much that works for me.

An additional question is I am having trouble accessing the CDN via python SDK to retrieve a file. I am attempting to do it as seen in the code below, when I use `base_url` (accessing the storage account directly) this works fine though when I use `base_url_via_cdn `(accessing via the cdn) I get `ValueError: Required Content-Range response header is missing or malformed.`

I have seen [here](https://github.com/Azure/azure-sdk-for-python/issues/22297#issuecomment-1165031164) there is known issues with a microsoft classic tier cdn prodcuing this exact error however I am using the standard tier cdn, is this still a known issue here?

```
async def download_blob():
    base_url = "https://aseanonymouscdnbugdemo.blob.core.windows.net/ase-bug-demo/"
    base_url_via_cdn = "https://anonymous-access-a9engahagrb4dudx.z01.azurefd.net/ase-bug-demo/"
    blob_url = f"{base_url_via_cdn}demo-file-0.txt"

    async with BlobClient.from_blob_url(blob_url) as blob_client:
        blob_downloader: StorageStreamDownloader = await blob_client.download_blob(
            encoding="UTF-8"
        )
        contents = await blob_downloader.readall()
        print(contents)


asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
asyncio.run(download_blob())
```

**Comment by MRayermannMSFT** [comment]
@11braemm unfortunately you're now asking about something I'm not an expert in. 🙈 Based on my quick read of your link, you'll need to either open an issue with the python SDK about this, or open a support ticket with Azure via the portal.
