### ISSUE TITLE
Delete dependency of native modules that aren't needed before shipping

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#7553]
There are packages that are necessary for rebuilding native modules but aren't needed during runtime (e.g. node-addon-api). We can delete them after building the native modules but before shipping.

**Comment by craxal** [comment]
Doesn't that make them dev dependencies?

**Comment by JasonYeMSFT** [comment]
No. Native modules are rebuilt for the current platform during npm install. Packages like our system-format needs to include napi.h, which is provided by the package "nan". As a result, nan is a "dependency" of the "system-format", even though it won't be used any further after building the binary.

**Comment by MRayermannMSFT** [comment]
With this work mostly complete, I'm seeing the following stats:

| Stats (Windows only)            | 1.18.1 | 1.33.0-dev | Change |
|---------------------------------|--------|------------|--------|
| Total Files                     | 17,943 | 2,900      | -84%   |
| JavaScript Files                | 9,172  | 248        | -98%   |
| Size (MB, not incl. allocation) | 449.2  | 354.7      | -21%   |
