### ISSUE TITLE
Unable to query or delete table entity when rowkey has two single quotes '' (Azurite)

### ISSUE THREAD

**Issue by rcfearn** [microsoft/AzureStorageExplorer#7555]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.1

### Architecture

i86

### Storage Explorer Build Number

20231114.10

### Platform

All

### OS Version

Windows 11

### Bug Description

When I have an entity in an Azurite storage table with the following values:

PartitionKey: Variant
Rowkey: V_Pyewacket''sAromaticBitters50mL
Timestamp: 2023-12-03T22:09:57.3394176Z

I cannot delete the entity/row from either storage explorer or from .Net Core using TableClient.DeleteEntityAsync(PK, RK)

In .Net I get the error:
"Not Found."

In storage explorer I get the following error if I try to delete the single entity or if I select all rows and hit the Delete button:
Failed to delete entities in table 'xxxx'

 {
  "name": "RestError",
  "message": "0:The specified resource does not exist.\nRequestId:a5844b1d-0186-4e8d-af0d-421b7ea2387e\nTime:2023-12-04T22:19:11.469Z",
  "stack": "RestError: 0:The specified resource does not exist.\nRequestId:a5844b1d-0186-4e8d-af0d-421b7ea2387e\nTime:2023-12-04T22:19:11.469Z\n    at handleBodyError (C:\\Users\\rcfearn\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\table-extension\\dist\\src\\index.js:2:240883)\n    at C:\\Users\\rcfearn\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\table-extension\\dist\\src\\index.js:2:240069\n    at Array.map (<anonymous>)\n    at parseTransactionResponse (C:\\Users\\rcfearn\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\table-extension\\dist\\src\\index.js:2:239737)\n    at C:\\Users\\rcfearn\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\table-extension\\dist\\src\\index.js:2:240383\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Object.withSpan (C:\\Users\\rcfearn\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\table-extension\\dist\\src\\index.js:2:151807)\n    at async Promise.all (index 0)\n    at async #t (C:\\Users\\rcfearn\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\table-extension\\dist\\src\\index.js:2:30940)\n    at async TableClient.runOperation (C:\\Users\\rcfearn\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\table-extension\\dist\\src\\index.js:2:292143)",
  "code": "ResourceNotFound",
  "statusCode": 404,
  "request": {
    "url": "http://127.0.0.1:10002/devstoreaccount1/$batch",
    "body": "--batch_2d6480d1-65d9-452f-b831-3cab8d97ccaa\r\ncontent-type: multipart/mixed; boundary=changeset_143271b2-5ee0-4d10-883a-0e37d15015e7\r\n\r\n\r\n--changeset_143271b2-5ee0-4d10-883a-0e37d15015e7\r\ncontent-type: application/http\r\ncontent-transfer-encoding: binary\r\n\r\nDELETE http://127.0.0.1:10002/devstoreaccount1/ProductMicroserviceDeltaQueue(PartitionKey='VARIANT',RowKey='V_Chateau%20L''''Eglise%20Clinet%20Pomerol%202020') HTTP/1.1\r\nAccept: application/json;odata=minimalmetadata\r\nDataServiceVersion: 3.0\r\nIf-Match: *\r\n\r\n\r\n--changeset_143271b2-5ee0-4d10-883a-0e37d15015e7--\r\n--batch_2d6480d1-65d9-452f-b831-3cab8d97ccaa--\r\n",
    "headers": {
      "accept": "application/json",
      "x-ms-version": "2019-02-02",
      "dataserviceversion": "3.0;",
      "maxdataserviceversion": "3.0;NetFx",
      "content-type": "multipart/mixed; boundary=batch_2d6480d1-65d9-452f-b831-3cab8d97ccaa",
      "accept-charset": "UTF-8",
      "connection": "Keep-Alive",
      "accept-encoding": "gzip,deflate",
      "user-agent": "Microsoft Azure Storage Explorer/1.32.1 (win32) azsdk-js-data-tables/13.1.2 core-rest-pipeline/1.11.0 Node/v18.16.1 OS/(x64-Windows_NT-10.0.22000)",
      "x-ms-client-request-id": "4c6d0292-bc88-4061-99f0-3652428b3ccc",
      "x-ms-date": "Mon, 04 Dec 2023 22:19:11 GMT",
      "content-length": "617",
      "authorization": "SharedKey Redacted"
    },
    "method": "POST",
    "timeout": 0,
    "disableKeepAlive": false,
    "withCredentials": false,
    "tracingOptions": {
      "tracingContext": {
        "_contextMap": {}
      }
    },
    "requestId": "4c6d0292-bc88-4061-99f0-3652428b3ccc",
    "allowInsecureConnection": true,
    "enableBrowserStreams": false
  },
  "response": {
    "request": {
      "url": "http://127.0.0.1:10002/devstoreaccount1/$batch",
      "body": "--batch_2d6480d1-65d9-452f-b831-3cab8d97ccaa\r\ncontent-type: multipart/mixed; boundary=changeset_143271b2-5ee0-4d10-883a-0e37d15015e7\r\n\r\n\r\n--changeset_143271b2-5ee0-4d10-883a-0e37d15015e7\r\ncontent-type: application/http\r\ncontent-transfer-encoding: binary\r\n\r\nDELETE http://127.0.0.1:10002/devstoreaccount1/ProductMicroserviceDeltaQueue(PartitionKey='VARIANT',RowKey='V_Chateau%20L''''Eglise%20Clinet%20Pomerol%202020') HTTP/1.1\r\nAccept: application/json;odata=minimalmetadata\r\nDataServiceVersion: 3.0\r\nIf-Match: *\r\n\r\n\r\n--changeset_143271b2-5ee0-4d10-883a-0e37d15015e7--\r\n--batch_2d6480d1-65d9-452f-b831-3cab8d97ccaa--\r\n",
      "headers": {
        "accept": "application/json",
        "x-ms-version": "2019-02-02",
        "dataserviceversion": "3.0;",
        "maxdataserviceversion": "3.0;NetFx",
        "content-type": "multipart/mixed; boundary=batch_2d6480d1-65d9-452f-b831-3cab8d97ccaa",
        "accept-charset": "UTF-8",
        "connection": "Keep-Alive",
        "accept-encoding": "gzip,deflate",
        "user-agent": "Microsoft Azure Storage Explorer/1.32.1 (win32) azsdk-js-data-tables/13.1.2 core-rest-pipeline/1.11.0 Node/v18.16.1 OS/(x64-Windows_NT-10.0.22000)",
        "x-ms-client-request-id": "4c6d0292-bc88-4061-99f0-3652428b3ccc",
        "x-ms-date": "Mon, 04 Dec 2023 22:19:11 GMT",
        "content-length": "617",
        "authorization": "SharedKeyLite devstoreaccount1:dC5CPBJbFmqX4+ClUUSqgyxQ54EIjvi1+wYKyYcnySI="
      },
      "method": "POST",
      "timeout": 0,
      "disableKeepAlive": false,
      "withCredentials": false,
      "tracingOptions": {
        "tracingContext": {
          "_contextMap": {}
        }
      },
      "requestId": "4c6d0292-bc88-4061-99f0-3652428b3ccc",
      "allowInsecureConnection": true,
      "enableBrowserStreams": false
    },
    "status": 202,
    "headers": {
      "connection": "keep-alive",
      "content-type": "multipart/mixed; boundary=batchresponse_2d6480d1-65d9-452f-b831-3cab8d97ccaa",
      "date": "Mon, 04 Dec 2023 22:19:11 GMT",
      "keep-alive": "timeout=5",
      "server": "Azurite-Table/3.22.0",
      "transfer-encoding": "chunked",
      "x-ms-request-id": "a5844b1d-0186-4e8d-af0d-421b7ea2387e",
      "x-ms-version": "2021-12-02"
    },
    "bodyAsText": "--batchresponse_2d6480d1-65d9-452f-b831-3cab8d97ccaa\r\nContent-Type: multipart/mixed; boundary=changesetresponse_143271b2-5ee0-4d10-883a-0e37d15015e7\r\n\r\n--changesetresponse_143271b2-5ee0-4d10-883a-0e37d15015e7\r\nContent-Type: application/http\r\nContent-Transfer-Encoding: binary\r\n\r\nHTTP/1.1 404 Not Found\r\nContent-ID: 1\r\nDataServiceVersion: 3.0;\r\nContent-Type: application/json;odata=minimalmetadata;charset=utf-8\r\n\r\n{\"odata.error\":{\"code\":\"ResourceNotFound\",\"message\":{\"lang\":\"en-US\",\"value\":\"0:The specified resource does not exist.\\nRequestId:a5844b1d-0186-4e8d-af0d-421b7ea2387e\\nTime:2023-12-04T22:19:11.469Z\"}}}\r\n--changesetresponse_143271b2-5ee0-4d10-883a-0e37d15015e7--\r\n--batchresponse_2d6480d1-65d9-452f-b831-3cab8d97ccaa--\r\n"
  }
}

### Steps to Reproduce

Add a new entity manually in storage explorer with the following values:

PartitionKey: Variant
RowKey: test''test

Once added, attempt to delete it and receive error as above.

### Actual Experience

Unable to delete an entity in an azurite storage table by Partition/Row Key

### Expected Experience

Should be able to delete an entity in an azurite storage table by Partition/Row Key

**Comment by craxal** [comment]
@rcfearn Have you tried updating your version of Azurite? It doesn't look like you are using the latest.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you still need help with this problem, we recommend opening a support ticket via the Azure Portal. Alternatively you can open a new issue.
