### ISSUE TITLE
The dialog shows blank when clicking 'Configure CORS Settings...'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7556]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20231205.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.1.1 (Apple M1 Pro)
**Architecture**: ia32/x64/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.32.1)

## Steps to Reproduce ##
1. Expand one storage account.
2. Right click 'Blob Containers' node -> Click 'Configure CORS Settings...'.
3. Check whether the dialog shows normal.

## Expected Experience ##
The dialog shows normal.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/23c33c93-521e-489e-be3e-d4e910dab9ce)

## Actual Experience ##
The dialog shows blank.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/0d8e94fd-8806-4c83-a60e-dd0b68012db2)

## Additional Context ##
This issue also reproduces for 'File Shares/Queues/Tables' node.

**Comment by craxal** [comment]
There's a change already in PR that should resolve this.

**Comment by craxal** [comment]
No, it is not. I'll make sure it's reinserted. Please verify.

**Comment by v-xianya** [comment]
Verified this issue on main build 20231209.3. The description has been added back.
