### ISSUE TITLE
Authentication Error: Unable to retrieve child resources

### ISSUE THREAD

**Issue by abbasderawall** [microsoft/AzureStorageExplorer#7559]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.1(96)

### Architecture

x64

### Storage Explorer Build Number

20231114.10

### Platform

All

### OS Version

Windows 11

### Bug Description

"details": {
    "errorCode": "AuthenticationFailed",
    "content-length": "435",
    "content-type": "application/xml",
    "date": "Wed, 06 Dec 2023 07:03:46 GMT",
    "server": "Microsoft-HTTPAPI/2.0",

    "message": "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly 
    "code": "AuthenticationFailed",
    "AuthenticationErrorDetail": "Request date header too old: 'Tue, 05 Dec 2023 21:31:10 GMT'"
  }
}

### Steps to Reproduce

All system components are functioning as expected; however, an AuthenticationFailed error occurs when attempting to access the storage table. This issue is observed both in the Azure Explorer and the web interface. Immediate attention and investigation are required to address and resolve the authentication challenge, ensuring seamless access to the storage table.

### Actual Experience

![image](https://github.com/microsoft/AzureStorageExplorer/assets/44167027/373f3516-3b16-43a5-8010-beadda060848)

**Comment by craxal** [comment]
@abbbasderawall If you're also encountering issues in the Azure portal, it's likely a problem in Azure itself. We recommend opening a service request (https://docs.microsoft.com/en-us/azure/azure-supportability/how-to-create-azure-support-request).

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you still need help with this problem, we recommend opening a support ticket via the Azure Portal. Alternatively you can open a new issue.
