### ISSUE TITLE
View and update metadata on blob container?

### ISSUE THREAD

**Issue by Tottmar** [microsoft/AzureStorageExplorer#756]
**Storage Explorer Version**: <= 1.4.3
**Platform/OS Version**: Windows
**Architecture**: ia32
**Regression From**: N/A

#### Steps to Reproduce: ####
1. Select a blob container.
2. Select the Properties tab at the bottom left corner of Storage Explorer.

#### Expected Experience: ####
The Properties tab should include the metadata of the container.

#### Actual Experience: ####
The metadata is not visible.

#### Steps to Reproduce: ####
1. Right-click a blob container.

#### Expected Experience: ####
You should be able to update the Properties of a container the same way as you update the Properties of a blob.

#### Actual Experience: ####
It's not possible to update the Properties of a container.

**Comment by MRayermannMSFT** [comment]
Working on getting this done for 1.15...
![image](https://user-images.githubusercontent.com/21112697/85186451-eb696400-b24d-11ea-9cdd-9f428ba7adee.png)

**Comment by MRayermannMSFT** [comment]
The work for this has been merged into master. Will be available in 1.15.0
