### ISSUE TITLE
The icon for the error message shows as a blank square on the 'Upload VHD/Paste Disk/Create Snapshot' dialog

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7562]
**Storage Explorer Version:** 1.33.0-dev (96)
**Build Number:** 20231206.12
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.1.2(Apple M1 Pro)
**Architecture:** x64/x64/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.32.1)

## Steps to Reproduce ##
1. Expand the node 'Disks' -> Open one resource group.
2. Click 'Upload' -> Type an invalid name for the 'Disk name' field.
3. The error message displays.
4. Check whether the icon shows well.

## Expected Experience ##
The icon shows well.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/4043c3a1-7082-4fbd-bd34-1876e5fdf791)

## Actual Experience #
The icon shows as a blank square.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/c8b27560-1d92-4ed0-a144-e0b2a38f7ec3)

## Additional Context ##
This issue also reproduces for 'Paste Disk/Create Snapshot' dialog:
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/1444e7ef-8867-4eef-907f-0b14003e9536)

**Comment by craxal** [comment]
I'm already working in this area, so I'll fix it.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20231208.2. Fixed.
