### ISSUE TITLE
Unable to access Blob Container using Storage Explorer 

### ISSUE THREAD

**Issue by SaravanaKnauf** [microsoft/AzureStorageExplorer#7565]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.1

### Architecture

i86

### Platform

Windows

### Bug Description

I am trying to access our Blob Container using the storage explorer  but it is giving the flowing error. It is still access over web and cant find issues in web portal.

### Steps to Reproduce

1. Launched Storage explore and connected Azure subscription. 
2. When clicked on the Blob An error occurred. 

### Actual Experience

Unable to view Blob

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you still need help with this problem, we recommend opening a support ticket via the Azure Portal. Alternatively you can open a new issue.
