### ISSUE TITLE
The 'Undelete by Date' dialog shows blank

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7569]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20231209.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.1.2 (Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.32.1)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container.
3. Upload one folder -> Right click the folder.
4. Click 'Undelete -> Undelete by Date...'.
5. Check whether the dialog shows well.

## Expected Experience ##
The dialog shows well.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/cfe25977-4d84-4307-8032-ea6a7c1b2a94)

## Actual Experience ##
The dialog shows blank.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/5a94477d-be7d-465c-9f14-3ee962c5aa6f)

**Comment by craxal** [comment]
@JasonYeMSFT Looks like this was due to a typo in the Standalone index.html file. "View" was missing from "UndeleteByDataeRange".

**Comment by v-xianya** [comment]
Verified this issue on the main build 20231212.5. Fixed.
