### ISSUE TITLE
Configure Soft Delete Policy on Azure Emulator error: XML Specified is not syntactically valid.

### ISSUE THREAD

**Issue by moutono** [microsoft/AzureStorageExplorer#757]
**Storage Explorer Version**: 1.4.3
**Platform/OS Version**: Windows 10 Enterprise
**Architecture**: ia32
**Regression From**: No, soft delete is new feature.

#### Steps to Reproduce: ####
1. Start Azure Storage Emulator Version 5.7.0.0 command line tool
2. Open Azure Storage Explorer
3. Expand Local & Attached -> Storage Accounts -> LocalEmulator (Key)
4. Right Click Blob Containers -> Configure Soft Delete Policy
5 Enable Soft Delete for X number of days. Click Save.

#### Expected Experience: ####
Soft Delete Policy is enabled.

#### Actual Experience: ####
Following message displayed under Activities tab:
Failed to configure delete policy of 'devstoreaccount1': StorageError:XML specified is not syntactically valid. RequestId:b2ab72ff-33b5-4b29-82e6-2ec2a01fcc03 Time:2018-10-12T06:48:15.1822285Z

Error Details:
{
  "name": "StorageError",
  "message": "XML specified is not syntactically valid.\nRequestId:b2ab72ff-33b5-4b29-82e6-2ec2a01fcc03\nTime:2018-10-12T06:48:15.1822285Z",
  "stack": "StorageError: XML specified is not syntactically valid.\nRequestId:b2ab72ff-33b5-4b29-82e6-2ec2a01fcc03\nTime:2018-10-12T06:48:15.1822285Z\n    at Function.StorageServiceClient._normalizeError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:1198:23)\n    at Object.StorageServiceClient._processResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:744:50)\n    at Request.processResponseCallback [as _callback] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:317:37)\n    at Request.self.callback (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:185:22)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at Request.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\request\\request.js:1157:10)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at Request.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)",
  "code": "InvalidXmlDocument",
  "linenumber": "1",
  "lineposition": "66",
  "reason": "Element 'DeleteRetentionPolicy' is not recognized.",
  "statusCode": 400,
  "requestId": "b2ab72ff-33b5-4b29-82e6-2ec2a01fcc03"
}
![azureerror](https://user-images.githubusercontent.com/20123995/46852796-6e40e700-cdfc-11e8-941a-3c791704a4a0.jpg)

**Comment by MRayermannMSFT** [comment]
@moutono , this is probably due to a bug/lack of support for soft delete on the emulator, we'll investigate it when we have time. Is this blocking you?

**Comment by moutono** [comment]
Thanks for prompt replies.
No, this is not blocking me.

**Comment by JohnReeson** [comment]
See same error on 5.8.0.0 emulator.

**Comment by jinglouMSFT** [comment]
I believe 5.8 is still on 2018-03-28 of the storage services.

**Comment by JasonYeMSFT** [comment]
Storage Emulator is being deprecated and it doesn't support soft delete. As its replacement, Azurite is the future and has already supported soft delete.
