### ISSUE TITLE
The content is incomplete for dialog 'Propagate Access Control Lists/Manage Access/Update Access Tier/Upload/Connect File Share to VM/Add Message/Import Messages'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7570]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20231209.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.1.2 (Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.32.1)

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Right click one blob container -> Click 'Manage Access Control Lists...'.
3. Check whether the content of the dialog is complete.

## Expected Experience ##
The content of the dialog is complete.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/d6520fe2-7c90-4221-8782-524300697651)

## Actual Experience ##
The content of the dialog is incomplete.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/29eb3566-f868-4ce0-b6d9-c3eb852154ef)

**Comment by craxal** [comment]
I believe this is the same root cause as #7572.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20231213.5. Fixed,
