### ISSUE TITLE
An extra scrollbar shows in the connect dialog after selecting one resource

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7572]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20231209.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.1.2 (Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.32.1)

## Steps to Reproduce ##
1. Open connect dialog -> Click 'Subscription'.
2. Check there is no extra scrollbar in the dialog.

## Expected Experience ##
No extra scrollbar in the dialog.

## Actual Experience ##
An extra scrollbar in the dialog.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/a160c706-33e0-495f-8b25-7ebbe4e8af33)

## Additional Context ##
This issue also reproduces for 'Open Direct Link' dialog.

**Comment by craxal** [comment]
This appears to be a problem with how `jQuery.show()` and `jQuery.hide()` works. jQuery sets the element's `display` property to `block` when showing and `none` when hiding. This interferes with a dialog panel's default `flex` setting, which removes the more dynamic sizing of the panel.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20231212.6. Fixed. So, we are going to close it.
