### ISSUE TITLE
Cannot see the delete icon when selecting one custom environment under 'High Contrast - Black/White' theme 

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7573]
**Storage Explorer Version:** 1.33.0-dev (96)
**Build Number:** 20231212.6
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.1.2 (Apple M1 Pro)
**Architecture:** x64/x64/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.32.1)

## Steps to Reproduce ##

1. Launch storage explorer -> Set the theme to 'High Contrast - Black'.
2. Open connect dialog -> Click 'Subscription'.
3. Select 'Custom Environment' -> Click 'Manage custom environments...'.
4. Add one custom environment -> Select it.
5. Check whether we can see the delete icon.

## Expected Experience ##
We can see the delete icon.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/b744759d-06ff-4286-a4fb-7b7c7613352f)

## Actual Experience ##
Can't see the delete icon.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/ce1b30d1-df9b-42da-8225-f91f151563a2)

## Additional Context ##
It is hard to see the delete icon under 'Light' theme.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/9d8e4155-f7da-41aa-a70e-326c7185667c)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20231213.5. Fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/ad676f87-adc6-48c6-b3c3-1072adb03a20)

**Comment by craxal** [comment]
@v-kellyluo Merged a fix for the flash. Please verify.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20231214.2. Fixed.
