### ISSUE TITLE
It is better to remove the scrollbar on properties dialog for blobs/files

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7576]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20231212.6
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.1.2 (Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.32.1)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Right click the blob -> Click 'Properties'.
4. Check whether there is no extra scrollbar on the dialog.

## Expected Experience ##
It is better to remove the scrollbar on the dialog.

## Actual Experience ##
There is an extra scrollbar on the dialog.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/576a8872-6250-4a3f-92e9-639254db1c72)

**Comment by craxal** [comment]
Same root cause as #7252.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20231213.5. Fixed.
