### ISSUE TITLE
Experiencing difficulties when generating a SAS (Shared Access Signature) assigned IP for a specific container in Microsoft Azure Storage Explorer.

### ISSUE THREAD

**Issue by NicolasGomez97** [microsoft/AzureStorageExplorer#7580]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.1

### Architecture

x64

### Storage Explorer Build Number

20231114.10

### Platform

Windows

### OS Version

Windows 10

### Bug Description

I am currently experiencing difficulties generating a SAS (Shared Access Signature) for a specific container in Microsoft Azure Storage Explorer.

### Steps to reproduce the issue
1. I open Microsoft Azure Storage Explorer.
2. I generate a SAS for a specific container with the IP of my local machine.
3. I try to copy, move or rename a file or folder within that container.
4. I note that these actions are not allowed.

### Actual Experience

However, when generating the SAS with the IP of my local machine, I run into limitations. I am unable to perform the functions mentioned above (copy, move, rename, etc.).

![image](https://github.com/microsoft/AzureStorageExplorer/assets/37515105/3ba3197f-a709-4074-8141-1058320a603b)

![image](https://github.com/microsoft/AzureStorageExplorer/assets/37515105/a2f22881-2a1d-4668-b686-2307766604d2)

### Expected Experience

When I generate a SAS with the IP of my local machine, I expect to be able to perform all the functionality available in the Microsoft Azure Storage Explorer, such as copy, move, rename, etc.

### Additional Context

- This problem does not occur when I generate a SAS without including the IP of my local machine.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/37515105/c510e5cd-57fc-4c52-8016-79878b3f11e9)

![image](https://github.com/microsoft/AzureStorageExplorer/assets/37515105/3f638e36-0de7-4b4a-9013-397380fe1807)

- Have there been any recent changes made to Azure Storage Explorer configuration or SAS generation that could be related to this issue?

**Comment by craxal** [comment]
@NicolasGomez97 Has using an IP worked with previous versions of Storage Explorer? Have you verified that you're using the correct IP (for example, not using 127.0.0.1)?

**Comment by JasonYeMSFT** [comment]
@NicolasGomez97 If your device is behind NAT (not assigned a global IP), you may need to use methods like whatismyipaddress.com or a STUN server to get your Internet facing IP address.

**Comment by NicolasGomez97** [comment]
@JasonYeMSFT It is not a NAT or firewall problem, because it allows me to do some functionalities. In any case, if that would be the problem, it would not let me do anything. But the bug comes when I want to do some of the following functionalities:
* Rename
* Move or copy files and folders
* Delete files and folders
Features that it does let me do:
* Upload Files and Folder
*Download Files and folder
*Create folder.
web my ip: https://www.myip.com/
![image](https://github.com/microsoft/AzureStorageExplorer/assets/37515105/ce43fe60-5f70-4bef-a51e-0acebedee24b)
Permissions:
![image](https://github.com/microsoft/AzureStorageExplorer/assets/37515105/c43de664-2239-4ccd-a4cb-84d772d47e39)

**Comment by JasonYeMSFT** [comment]
@NicolasGomez97 For operations like copy, rename and move, the server needs to access the source. If your SAS token IP parameter restricts the server it won't be able to do so. However, delete should work. I tested in 1.32.1 and my delete worked.
