### ISSUE TITLE
Fail to preview avro files in the blob container '$blobchangefeed'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7586]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20231214.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.1.2 (Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.32.1)

## Steps to Reproduce ##
1. Open one storage account in Portal.
2. Go to 'Data protection' -> Check the option 'Enable blob change feed' -> Save it.
3. Go to Storage Explorer -> Expand the storage account -> Blob Containers.
4. Open the blob container named '$blobchangefeed'.
5. Execute some actions to make avro file shows in the explorer of the blob container '$blobchangefeed'.
6. Try to preview the avro file.
7. Check whether succeeds to preview the avro file.

## Expected Experience ##
Succeed to preview the avro file.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/063de7df-c21d-4f25-a6a0-7f2e905c1731)

## Actual Experience ##
Fail to preview the avro file.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/ddf3c732-440f-47c8-81b6-3b963c55cef3)

![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/3e07959f-8d55-42c0-b1ed-d285e4673596)

**Comment by craxal** [comment]
@v-xianya Can you be more specific about the "actions to make the Avro file show"? Can you share the file? If you download the file and upload it to another container, does the preview work as expected?

**Comment by v-xianya** [comment]
Hi @craxal

> `Can you be more specific about the "actions to make the Avro file show"?` 

 

I am not sure there are specific actions. Below are my steps to show avro files

1. I created a blob container under the same storage account.
2. Upload blobs to the blob container -> Acquire/break lease for the blob -> Run filter query -> Run 'Selection Statistics'.
3. Delete the blob.
4. Create a folder -> Upload blob to the folder -> Run 'Folder Statistics'.

> `Can you share the file?`

I shared the file on teams.

> ` If you download the file and upload it to another container, does the preview work as expected?`

The preview doesn't work in file share or other containers against the avro file.

**Comment by craxal** [comment]
@v-xianya The file you shared appears to be an invalid Avro file, because I can't preview it from a normal container either. Do you know for sure the Avro file could be previewed when it was first uploaded? Do you have a version that is valid?

**Comment by v-xianya** [comment]
Hi @craxal The avro file can be successfully previewed on 1.32.1 (Under the $blobchangefeed blob container).
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/822fd395-e7ca-47ee-b158-364a741e1bb6)

**Comment by craxal** [comment]
After some investigation, it looks like this has nothing to do with $blobchangefeed. This is due to a small bug in the code that parses long values from the Avro file. By fixing this code, the Avro files can be parsed successfully.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240130.14. Fixed.
