### ISSUE TITLE
Not able to expand storage accounts after installing version 1.4.3

### ISSUE THREAD

**Issue by khosrojerdi** [Microsoft/AzureStorageExplorer#759]
**Storage Explorer Version**: 1.4.3
**Platform/OS Version**: Windows 10
**Architecture**: 
**Regression From**: it was working on 1.4.1

#### Steps to Reproduce: ####
1. I have updated my app to version 1.4.3 after the prompt and afterwards I can not expand my storage accounts anymore even though I do sign in again. Then I checked the activities panel and there it shows me the following sign in error:
Unable to sign in: ERR_NOT_IMPLEMENTED

#### Expected Experience: ####
Expand a storage account and see the containers

#### Actual Experience: ####
App does nothing when I expand the storage account.

**Comment by MRayermannMSFT** [comment]
@JakeRadMSFT , could this be a result of the API roll back?

**Comment by jinglouMSFT** [comment]
@khosrojerdi  if you are blocked, you can revert back to v1.4.2 which is available on storageexplorer.com. Go to the bottom of that page and you can download it from the "Previous Version".  Meanwhile we will look into the cause of this issue.  Thanks for the report.

**Comment by MRayermannMSFT** [comment]
@khosrojerdi , this should be fixed in 1.4.4 (we just shipped it). Please try again and let us know how it goes.

**Comment by khosrojerdi** [comment]
@MRayermannMSFT Sorry for my late reply. As you mentioned it was fixed with new version. Thanks for your support
