### ISSUE TITLE
Reordering columns by dragging and dropping them on a new disk explorer doesn't take effect for other resource groups

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7592]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20231215.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.1.2(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand 'Disks' -> Open one resource group.
2. Reorder the columns by dragging and dropping them.
3. Split the tab.
4. Check whether the columns on the split tab are reordered.

## Expected Experience ##
The columns on the split tab are reordered.
## Actual Experience ##
The columns on the split tab keep default order.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/7bf56fa7-afc3-4463-88bb-24d8ce12dc7c)

## Additional Context ##
This issue also reproduces when opening a new resource group.

**Comment by MRayermannMSFT** [comment]
@richardMSFT I'm not actually sure if this is expected behavior? I don't think we do this for other explorers, right?

**Comment by richardMSFT** [comment]
Looks like the behavior is expected in other explorers. However, blob container explorer doesn't seem to have this behavior.

The fix for managed-disks was that I wasn't saving the column state into the storage manager.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20231221.5. Fixed. So, we are going to close it.
