### ISSUE TITLE
Sign-in Error "The SSL connection could not be established, see inner exception."

### ISSUE THREAD

**Issue by mmdegraaf** [microsoft/AzureStorageExplorer#7593]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.1

### Regression From

1.32.1

### Architecture

i86

### Storage Explorer Build Number

20231114.10

### Platform

Windows

### OS Version

Windows 11 23H2

### Bug Description

Can't sign-in anymore using Azure Storage Explorer. Been using SE for a long time already and never had this problem before. When i tried the re-authenticate option today it failed with the same error. I remove the account from SE and tried to add it using the option "Sign in with Azure"; this gives the same error. I remove SE completely, rebooted my laptop and reinstalled from scratch. Same error.

### Steps to Reproduce

Launch SE and try to sign-in.

### Actual Experience

When i start SE from the command prompt and choose Azure as a sing in option i can see the actual error:
 <ERRO> Failed to addAccount, authFlowType: systemBrowser, authResult: {"UserCancelled":false,"Errors":[{"Message":"The SSL connection could not be established, see inner exception.","ExceptionType":"System.Net.Http.HttpRequestException","HResult":-2146232800,"ExceptionString":"System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.\r\n ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..\r\n ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)\r\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)\r\n   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)\r\n   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)\r\n   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)\r\n   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)\r\n   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\r\n   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\r\n   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)\r\n   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)\r\n   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\r\n   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)\r\n   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\r\n   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)\r\n   at Microsoft.Identity.Client.Http.HttpManager.ExecuteAsync(Uri endpoint, IDictionary`2 headers, HttpContent body, HttpMethod method, ILoggerAdapter logger, CancellationToken cancellationToken)\r\n   at Microsoft.Identity.Client.Http.HttpManagerWithRetry.SendRequestAsync(Uri endpoint, IDictionary`2 headers, HttpContent body, HttpMethod method, ILoggerAdapter logger, Boolean doNotThrow, Boolean retry, CancellationToken cancellationToken)\r\n   at Microsoft.Identity.Client.Http.HttpManagerWithRetry.SendGetAsync(Uri endpoint, IDictionary`2 headers, ILoggerAdapter logger, Boolean retry, CancellationToken cancellationToken)\r\n   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ExecuteRequestAsync[T](Uri endPoint, HttpMethod method, RequestContext requestContext, Boolean expectErrorsOn200OK, Boolean addCommonHeaders, Func`2 onBeforePostRequestData)\r\n   at Microsoft.Identity.Client.OAuth2.OAuth2Client.DiscoverAadInstanceAsync(Uri endpoint, RequestContext requestContext)\r\n   at Microsoft.Identity.Client.Instance.Discovery.NetworkMetadataProvider.SendInstanceDiscoveryRequestAsync(Uri authority, RequestContext requestContext)\r\n   at Microsoft.Identity.Client.Instance.Discovery.NetworkMetadataProvider.FetchAllDiscoveryMetadataAsync(Uri authority, RequestContext requestContext)\r\n   at Microsoft.Identity.Client.Instance.Discovery.NetworkMetadataProvider.GetMetadataAsync(Uri authority, RequestContext requestContext)\r\n   at Microsoft.Identity.Client.Instance.Discovery.InstanceDiscoveryManager.FetchNetworkMetadataOrFallbackAsync(RequestContext requestContext, Uri authorityUri)\r\n   at Microsoft.Identity.Client.Instance.Discovery.InstanceDiscoveryManager.GetMetadataEntryAsync(AuthorityInfo authorityInfo, RequestContext requestContext, Boolean forceValidation)\r\n   at Microsoft.Identity.Client.Instance.AuthorityManager.RunInstanceDiscoveryAndValidationAsync()\r\n   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.ExecuteAsync(CancellationToken cancellationToken)\r\n   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)\r\n   at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenInteractiveParameters interactiveParameters, CancellationToken cancellationToken)\r\n   at Microsoft.Developer.IdentityService.AccountProvider.MsalNetworkServicesImpl.PerformSystemWebBrowserFlowAsync(MsalGetTokenInteractiveContext context, String qp, CancellationToken cancellationToken) in D:\\a\\_work\\1\\s\\src\\IdentityService\\Microsoft.Developer.IdentityService\\AccountProvider\\AADAccountProvider\\MsalNetworkServicesImpl.cs:line 803\r\n   at Microsoft.Developer.IdentityService.AccountProvider.MsalNetworkServicesImpl.ExecuteInteractiveFlowAsync(IGetTokenInteractiveContext getTokenContext, AuthenticationFlowType authenticationFlowType, CancellationToken cancellationToken) in D:\\a\\_work\\1\\s\\src\\IdentityService\\Microsoft.Developer.IdentityService\\AccountProvider\\AADAccountProvider\\MsalNetworkServicesImpl.cs:line 468\r\n   at Microsoft.Developer.IdentityService.AccountProvider.MsalNetworkServicesImpl.ExecuteInteractiveFlowAsync(IGetTokenInteractiveContext getTokenContext, AuthenticationFlowType authenticationFlowType, CancellationToken cancellationToken) in D:\\a\\_work\\1\\s\\src\\IdentityService\\Microsoft.Developer.IdentityService\\AccountProvider\\AADAccountProvider\\MsalNetworkServicesImpl.cs:line 486\r\n   at Microsoft.Developer.IdentityService.AccountProvider.AadAccountProviderNetworkServicesBase.AcquireTokenWithPromptInternalAsync(String resource, String tenant, UserIdentifier userId, String queryParameters, AuthenticationFlowType authenticationFlowType, Dictionary`2 additionalAuthProperties, CancellationToken cancellationToken) in D:\\a\\_work\\1\\s\\src\\IdentityService\\Microsoft.Developer.IdentityService\\AccountProvider\\AADAccountProvider\\AadAccountProviderNetworkServicesBase.cs:line 851\r\n   at Microsoft.Developer.IdentityService.AccountProvider.AadAccountProviderService.CreateAccountInnerAsync(String userName, String queryParameters, AuthenticationFlowType authenticationFlowType, Dictionary`2 additionalAuthProperties, Boolean homeTenantOnly, CancellationToken cancellationToken) in D:\\a\\_work\\1\\s\\src\\IdentityService\\Microsoft.Developer.IdentityService\\AccountProvider\\AADAccountProvider\\AadAccountProviderService.cs:line 902","Data":{}}]}

**Comment by MRayermannMSFT** [comment]
@mmdegraaf are you behind any sort of proxy or vpn that might be inteferring with the connection?

**Comment by mmdegraaf** [comment]
There is no proxy and no firewall. It actually was working for almost 2 years without any problems. Is there any test i could perform ?

**Comment by JasonYeMSFT** [comment]
@mmdegraaf Could you please follow the steps in this section of our troubleshooting guide to raise the authentication log level, reproduce the issue one more time and collect the authentication logs? https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/storage-explorer-troubleshooting?tabs=Windows#authentication-logs

**Comment by mmdegraaf** [comment]
[StorageExplorer.zip](https://github.com/microsoft/AzureStorageExplorer/files/13707101/StorageExplorer.zip)
@JasonYeMSFT As requested the logs attached.

**Comment by JasonYeMSFT** [comment]
Are you still experiencing this issue? I went through the logs but didn't find anything significant other than the HTTP error, which might be related to your network configuration.

**Comment by mmdegraaf** [comment]
Issue is still there. My network configuration has not changed for a long time. I have been using StorageExplorer for years, never had this issue. And it doesn't matter if i work from home, office, with or without VPN. I always end up with the very same error. The ticket i raised at MS is still open since Dec 15; no progress yet.

________________________________

**Comment by MRayermannMSFT** [comment]
@mmdegraaf we have no updates to share from our side. Unfortunately it looks like getting this solved likely rests with the support folks being able to help you out. We'll leave this issue open a while longer incase you/they have any further questions related to this problem.

**Comment by mmdegraaf** [comment]
Hi Matthew,

 I found the solution.

Importing this in the registry fixed the issue:

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Cryptography\Configuration\Local\SSL\00010003]
@="NCRYPT_SCHANNEL_SIGNATURE_INTERFACE"
"Functions"=hex(7):52,00,53,00,41,00,45,00,2d,00,50,00,53,00,53,00,2f,00,53,00,\
  48,00,41,00,32,00,35,00,36,00,00,00,52,00,53,00,41,00,45,00,2d,00,50,00,53,\
  00,53,00,2f,00,53,00,48,00,41,00,33,00,38,00,34,00,00,00,52,00,53,00,41,00,\
  45,00,2d,00,50,00,53,00,53,00,2f,00,53,00,48,00,41,00,35,00,31,00,32,00,00,\
  00,52,00,53,00,41,00,2f,00,53,00,48,00,41,00,32,00,35,00,36,00,00,00,52,00,\
  53,00,41,00,2f,00,53,00,48,00,41,00,33,00,38,00,34,00,00,00,52,00,53,00,41,\
  00,2f,00,53,00,48,00,41,00,31,00,00,00,45,00,43,00,44,00,53,00,41,00,2f,00,\
  53,00,48,00,41,00,32,00,35,00,36,00,00,00,45,00,43,00,44,00,53,00,41,00,2f,\
  00,53,00,48,00,41,00,33,00,38,00,34,00,00,00,45,00,43,00,44,00,53,00,41,00,\
  2f,00,53,00,48,00,41,00,31,00,00,00,44,00,53,00,41,00,2f,00,53,00,48,00,41,\
  00,31,00,00,00,52,00,53,00,41,00,2f,00,53,00,48,00,41,00,35,00,31,00,32,00,\
  00,00,45,00,43,00,44,00,53,00,41,00,2f,00,53,00,48,00,41,00,35,00,31,00,32,\
  00,00,00,00,00

Thanks,

Max
________________________________

**Comment by prafulbusa** [comment]
Make to have these below "Functions" values are added for registry 'Type' Reg_MULTI_SZ

RSAE-PSS/SHA256
RSAE-PSS/SHA384
RSAE-PSS/SHA512
RSA/SHA256
RSA/SHA384
RSA/SHA1
ECDSA/SHA256
ECDSA/SHA384
ECDSA/SHA1
DSA/SHA1
RSA/SHA512
ECDSA/SHA512

See picture below
![image](https://github.com/microsoft/AzureStorageExplorer/assets/35320049/6a66846a-c185-4219-806f-41666ec9fefa)

**Comment by 0anton** [comment]
> Hi Matthew, I found the solution. Importing this in the registry fixed the issue

Thanks for sharing. This method unfortunately didn't work for me. I'm still getting:
```
{
  "message": "\"The SSL connection could not be established, see inner exception.\""
}
```
