### ISSUE TITLE
CSV files are uploaded as `application/vnd.ms-excel` instead of `text/csv`

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#7596]
CSV files uploaded as `text/csv` were uploaded in a prior version of Storage Explorer. It's possible this is a regression in AzCopy.

![image](https://github.com/microsoft/AzureStorageExplorer/assets/3473026/2f292749-5715-4c50-8d65-23887f968b1b)

**Comment by JasonYeMSFT** [comment]
Could you check if the rule described here is regressed? https://github.com/Azure/azure-storage-azcopy/issues/136#issuecomment-446755335

**Comment by MRayermannMSFT** [comment]
> Could you check if the rule described here is regressed? [Azure/azure-storage-azcopy#136 (comment)](https://github.com/Azure/azure-storage-azcopy/issues/136#issuecomment-446755335)

Or in other words, @craxal, check what mime type csv is associated with in your registry. If it is vnd.ms-excel, then what you are seeing is expected.

**Comment by craxal** [comment]
Ah, so for my Windows machine, CSV is associated with the `application/vnd.ms-excel` MIME type. But on my Mac machine, it still uploads as `text/csv`.
