### ISSUE TITLE
Investigate and plug up potential memory leaks from event registration

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#7597]
Components hosted in separate processes can register for app-wide events. For example, panels can listen for configuration changes. Some of these separate processes live alongside the app's main process. Others are temporary (for example, panels). These temporary panels don't unregister listeners. Over the course of an app session, many orphaned listeners can accumulate if many panels are opened and closed.

Additional lifecycle events should be put into place so that processes know when something is about to be terminated and needs to dispose of resources properly.

**Comment by JasonYeMSFT** [comment]
Fixed a bug in WebviewTabViewModel using the memory profiler. I checked other dynamically allocated resources such as activity and tree view nodes and I don't see them leaking any memory.
