### ISSUE TITLE
Display as blank in 'Rename' dialog when renaming a blob container

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#76]
**Storage Explorer Version:** 20180424.5(1.0.0)

**OS Version:** Win10/Mac/Linux

**Regression**: Not a regression

**Steps to Reproduce:**

1. Launch Storage Explorer and expand Storage Accounts.
2. Right click one blob continer and select 'Rename...'.
3. Check the Rename dialog.

**Expected Experience:**
Display as 'Rename Blob Container' in 'Rename' dialog.

**Actual Experience:**
Display as blank in 'Rename' dialog.
![rename](https://user-images.githubusercontent.com/34729022/39233730-c9113ae4-4860-11e8-982f-1e033f1bd236.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
