### ISSUE TITLE
Leading and trailing space to the metadata value leads to error”

### ISSUE THREAD

**Issue by apsarpasha** [Microsoft/AzureStorageExplorer#760]
**Storage Explorer Version**: 
![image](https://user-images.githubusercontent.com/33099220/46876205-577dad00-ce5b-11e8-9100-46573e0db88e.png)

**Platform/OS Version**:  Windows 
**Architecture**: 
**Regression From**:  No

#### Steps to Reproduce: ####
1. 
Open Storage Account -> Go to Container ->Select Blob -> Right Click and open Properties -> Add meta data - > Add some value with the space 

![image](https://user-images.githubusercontent.com/33099220/46876393-d5da4f00-ce5b-11e8-9579-5b82c9cd3c7c.png)

2. 

One of our customer has concern saying  “When trying to add metadata that ends with a space to a blob it responds with 'Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.' in code. and in Azure Storage Explorer it gives the same response.”
 

Research:
While investigating,  I noticed that  “the Leading and trailing space to the metadata value leads to error”

![image](https://user-images.githubusercontent.com/33099220/46875858-73348380-ce5a-11e8-8421-b963a12b2308.png)

![image](https://user-images.githubusercontent.com/33099220/46875868-7b8cbe80-ce5a-11e8-863f-6274b5ebcfe0.png)
![error1](https://user-images.githubusercontent.com/33099220/46875899-8f382500-ce5a-11e8-8698-da80468ea89f.PNG)

**Comment by MRayermannMSFT** [comment]
Yep, looks like we're supposed to be trimming whitespace when setting metadata.

**Comment by MRayermannMSFT** [comment]
Fix merged into master for next major release (we'll now check for leading and trailing whitespace, and not let you save with any there).
