### ISSUE TITLE
Need Help With Storage Explorer

### ISSUE THREAD

**Issue by AmazingPete** [microsoft/AzureStorageExplorer#7612]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.1

### Regression From

1.18.0

### Architecture

i86

### Storage Explorer Build Number

20231114.10

### Platform

All

### OS Version

Windows 2019

### Bug Description

Unable to retrieve child resources

ProducerError:{
  "name": "RestError",
  "message": "This request is not authorized to perform this operation.\nRequestId:23690f13-601a-009d-7189-3205c9000000\nTime:2023-12-19T14:44:50.2091946Z",
  "stack": "RestError: This request is not authorized to perform this operation.\nRequestId:23690f13-601a-009d-7189-3205c9000000\nTime:2023-12-19T14:44:50.2091946Z\n    at handleErrorResponse (C:\\Program Files\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\file-extension\\dist\\src\\index.js:2:171145)\n    at C:\\Program Files\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\file-extension\\dist\\src\\index.js:2:171829\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async StorageRetryPolicy.attemptSendRequest (C:\\Program Files\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\file-extension\\dist\\src\\index.js:2:393697)\n    at async StorageClientContext.sendOperationRequest (C:\\Program Files\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\file-extension\\dist\\src\\index.js:2:209878)\n    at async ShareServiceClient.listSharesSegment (C:\\Program Files\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\file-extension\\dist\\src\\index.js:2:464098)",
  "code": "AuthorizationFailure",
  "statusCode": 403,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://metranet.file.core.windows.net/?comp=list",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2023-01-03"
        },
        "accept": {
          "name": "Accept",
          "value": "application/xml"
        },
        "user-agent": {
          "name": "User-Agent",
          "value": "Microsoft Azure Storage Explorer/1.32.1 (win32) azsdk-js-storagefile/12.15.0 (NODE-VERSION v18.16.1; Windows_NT 10.0.14393)"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "bc490f8c-71a5-43e5-9a57-64c31ed74348"
        },

### Steps to Reproduce

Launch storage explorer
authenticate with Azure
Navigate to the FileShare Storage
Node not populating and error pops up

### Actual Experience

Error pops up whenever I go to specific File Share storage.

### Expected Experience

File Share Storage should display

### Additional Context

none

**Comment by JasonYeMSFT** [comment]
@AmazingPete The error indicates that your user credential is missing some permissions. Does your azure account has the permission to list your storage account keys? You can check that by going to Azure Portal, navigate to your storage account, go to the Access Control blade, click "View my Access" and check what roles you have.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. This issue will no longer be monitored. If you need further help, we recommend opening a support ticket via the Azure portal. Alternatively you can open a new issue here.
