### ISSUE TITLE
Four properties are missed for ADLS Gen2/regular blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7614]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20231220.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.2(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.32.1)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Select one blob container.
3. Observer its properties on the 'Properties' panel.
4. Check whether all properties show well.

## Expected Experience ##
All properties show well.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/a138d715-33ad-4399-ad76-4878848bd4da)

## Actual Experience ##
Four properties are missed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/553db6fa-3fd2-40a1-bcbf-d149642ec477)

**Comment by v-xianya** [comment]
Hi @JasonYeMSFT Verified this on the main build 20231220.4. 
No properties 'Immutability policy retention days/Has legal hold/Allow protected append writes' show for blob containers. Is this intentional?
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/ae456f07-6789-421c-bcb9-5403423199ba)

**Comment by JasonYeMSFT** [comment]
Yes, we will be hiding these properties if the underlying value is not defined. If you install older version, these properties should be undefined.

**Comment by v-xianya** [comment]
Got it. thanks for the response! we will close this issue.
