### ISSUE TITLE
A11y_Azure Tools Storage Explorer_Disk_DiskToolbar_Usable: No Status message is Conveyed to User that refresh completed.

### ISSUE THREAD

**Issue by keerthiduvvuri** [microsoft/AzureStorageExplorer#7615]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.1(96)

### Regression From

NO

### Architecture

x64

### Storage Explorer Build Number

20231114.10

### Platform

macOS

### OS Version

MAC Version 13.6.1

### GitHub Tags:
#A11yUsable;#A11yTCS;#MAC;#DesktopApp;#A11ySev4;#BM_AzureToolsStorageExplorer_MAC_Dec2023;#Azure Tools Storage Explorer;#FTP;#Voiceover;

### Environment Details:
Application: Microsoft Azure Storage Explore
version: 1.32.1 (96)
Screen Reader: Voice Over

### Steps to Reproduce

1. Launch Storage Explorer
2. Tab Navigate to "Open Connect dialog" pane and Sign into Azure.
3. Tab Navigate to "Manage Accounts" pane and Select the subscriptions you will use. Once selected, click on "Apply" button.
4. Tab Navigate to "Disks" of the selected subscription.
5. Tab Navigate to "A11ytest" and click on it.
6. Tab Navigate to Toolbar.
7. Turn on Voice Over and Observe that No Status message is Conveyed to User that refresh completed.

### Actual Experience

No Status message is Conveyed to User that refresh completed.

### Expected Experience

Status message should be Conveyed to User that refresh completed.

### User Impact:
Screen reader users will face difficulty if No Status message is Conveyed to User that refresh completed.

### Attachment:

https://github.com/microsoft/AzureStorageExplorer/assets/98728920/56106b73-4d7b-4b8d-aadb-ba5865f399c9

**Comment by kupatkar99** [comment]
Verified the issue in below environment:
Azure Tools Storage Explorer: Version: 1.33.0-dev (96)
AzCopy Version: 10.22.2
Platform: macOS
Build Number: 20240111.7 
Issue is fixed. Hence Closing the bug Please find added attachment for reference.
<img width="1440" alt="7615_Fixed" src="https://github.com/microsoft/AzureStorageExplorer/assets/98530069/302b9ce6-74e8-4832-9589-ba4376fdff8d">

**Comment by keerthiduvvuri** [comment]
#Closed;
