### ISSUE TITLE
Azure Storage Explorer it's not showing child resource in blob container

### ISSUE THREAD

**Issue by srsagar** [microsoft/AzureStorageExplorer#762]
**Storage Explorer Version**: 
**Platform/OS Version**: 
**Architecture**: 
**Regression From**: 

#### Steps to Reproduce: ####
1. 
2.

**Comment by srsagar** [comment]
![image](https://user-images.githubusercontent.com/40386227/47138971-570c6880-d2d8-11e8-97de-3c203392c2dd.png)

**Comment by MRayermannMSFT** [comment]
@srsagar , I believe this has been fixed in a release since you opened your issue. Please test against the latest version of Storage Explorer and open a new issue if you are still seeing this error. Thanks.
