### ISSUE TITLE
The order of the pasted message text is inconsistent with the sorted messages

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7620]
**Storage Explorer Version:** 1.33.0-dev (96)
**Build Number:** 20231220.4
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.2(Apple M1 Pro)
**Architecture:** x64/x64/arm64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Queues.
2. Open one queue which contains messages.
3. Sort messages by one column.
4. Click 'Select All' -> Right click messages -> Click 'Copy Message Text'.
5. Paste the message text to notepad.
6. Check whether the order of pasted message text is consistent with the sorted messages.

## Expected Experience ##
The order of pasted message text is consistent with the sorted messages.

## Actual Experience ##
The order of pasted message text is inconsistent with the sorted messages.

## Additional Context ##
Here is the record:
![queue](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/877c7c46-a04d-4050-84a2-43084ad40f3f)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240203.7. Fixed. So, we are going to close it.

**Comment by craxal** [comment]
CTI is reproducing this issue. Here are the new data:

Storage Explorer Version: 1.35.0-dev (98)
Build Number: 20240530.2
Branch: main
Platform/OS: Windows 11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.5(Apple M1 Pro)
Architecture: arm64/x64/x64/arm64
How Found: From running test cases
Regression From: Previous release (1.34.0)

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240613.1. Fixed.
