### ISSUE TITLE
The failed activity log doesn't contain error details when deleting one leased blob container

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7627]
**Storage Explorer Version:** 1.33.0-dev (96)
**Build Number:** 20231223.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.2(Apple M1 Pro)
**Architecture:** x64/x64/arm64
**How Found:** From running test cases
**Regression From:** Previous release (1.32.1)

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Right click one blob container -> Click 'Acquire Lease'.
3. Try to delete the leased blob container -> There is a failed activity log.
4. Check whether the failed activity log contains error details.

## Expected Experience ##
The failed activity log contains error details.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/dadd0445-c0d2-48c4-a1d6-38c1a723891e)

## Actual Experience ##
The failed activity log doesn't contain error details.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/08e357d3-4afe-429c-ab3a-70f659ae229b)

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240103.2. Fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/9c9d5be4-2145-4fb6-80d1-eb2479e125d0)
