### ISSUE TITLE
The 'Key' field is missed on 'Add/Edit Key-value' dialog for one app configuration

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7629]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20231226.2
**Branch**: main
**Platform/OS**: Windows 10
**Architecture**: x64
**How Found**: From running test cases
**Regression From**: Previous release (1.32.1)

## Steps to Reproduce ##
1. Expand 'App Configurations' node -> Open one app configuration.
2. Click 'Add' -> The 'Add Key-value' dialog pops up.
3. Check whether no field is missed.

## Expected Experience ##
No field is missed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/409d1054-0a89-4ced-afe6-d2bbd6d5aa9c)

## Actual Experience ##
The 'Key' field is missed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/ccce01bb-8679-4f50-b8df-091c599c1cbc)

**Comment by JasonYeMSFT** [comment]
The bug is due to some incompatible changes we made in the base dialog view. It will be addressed in a new version of the app config extension.

**Comment by v-kellyluo** [comment]
Verified this issue after installing app configuration extension 0.2.1. Fixed. So, we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/e4aa0f69-a8b5-4289-a4d3-362070bf1074)
