### ISSUE TITLE
No progress displays when uploading vhd files for one resource group

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7630]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20231226.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.2(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.32.1)

## Bug Descriptions ##
1. No progress displays when uploading vhd files for one resource group.
2. No progress displays when importing/exporting entities.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/5795cf23-a593-43a5-a003-d5f2780a498a)

## Steps to Reproduce ##
1. Expand 'Disks' node -> Open one resource group.
2. Upload a vhd file and observe its activity log.
3. Check whether the progress displays in the activity log.

## Expected Experience ##
The progress displays in the activity log.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/66809c3b-8fc2-4a30-a654-4ecfc5fb7e7d)

## Actual Experience ##
No progress displays in the activity log.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/57516726-7ba7-4ddf-b319-32f53c3299d7)

## Additional Context ##
1. This issue also reproduces when importing/exporting entities.
2. This issue doesn't reproduce when downloading vhd files.

**Comment by MRayermannMSFT** [comment]
@v-xianya I can only repro this in the "[NEW] Activities" panel. Do you also observe this?

**Comment by v-xianya** [comment]
@MRayermannMSFT Yes, this issue is opened against "[NEW] Activities" panel. Sorry for not pointing this out.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240106.11. Fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/51b0439f-4387-4538-8316-2fdd675a772a)
