### ISSUE TITLE
Cannot get access to Blob Container

### ISSUE THREAD

**Issue by OlgaNikolaevaKofax** [microsoft/AzureStorageExplorer#7632]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.1

### Architecture

x64

### Storage Explorer Build Number

20231114.10

### Platform

Windows

### OS Version

Windows 10

### Bug Description

While trying to get access to Blob Container I always get same error:
Unable to retrieve child resources

ProducerError:{
  "name": "Node Fetch Error",
  "message": "getaddrinfo ENOTFOUND qatcstorage24char.blob.core.windows.net",
  "stack": "Error: getaddrinfo ENOTFOUND qatcstorage24char.blob.core.windows.net\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26)",
  "cause": {
    "cause": {
      "errno": -3008,
      "code": "ENOTFOUND",
      "syscall": "getaddrinfo",
      "hostname": "qatcstorage24char.blob.core.windows.net"
    }
  },
  "code": "ENOTFOUND",
  "errno": -3008
}

### Steps to Reproduce

1. Launch Storage Explorer
2. Expand Blob container node

### Actual Experience

Unable to retrieve child resources

ProducerError:{
  "name": "Node Fetch Error",
  "message": "getaddrinfo ENOTFOUND qatcstorage24char.blob.core.windows.net",
  "stack": "Error: getaddrinfo ENOTFOUND qatcstorage24char.blob.core.windows.net\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26)",
  "cause": {
    "cause": {
      "errno": -3008,
      "code": "ENOTFOUND",
      "syscall": "getaddrinfo",
      "hostname": "qatcstorage24char.blob.core.windows.net"
    }
  },
  "code": "ENOTFOUND",
  "errno": -3008
}

### Expected Experience

I get access to blob container successfully

**Comment by MRayermannMSFT** [comment]
@OlgaNikolaevaKofax is your storage account on a private virtual network? If so, is your current machine on that network? As a quick test, can you try accessing the same container from the Azure Portal, using the same machine as you are running Storage Explorer?
