### ISSUE TITLE
There is a successful activity log if undelete a folder that contains an active blob and a soft-deleted blob with the same name

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7633]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20231228.6
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.2(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.31.2)

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Create a folder.
3. Upload one blob to the folder -> Soft delete the blob.
4. Upload a same blob to the folder.
5. Right click the folder -> Click 'Undelete -> Undelete Selected'.
6. Click 'OK' on the prompt dialog.
7. Check whether there is a failed activity log.

## Expected Experience ##
There is a failed activity log.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/f237bb7a-7218-4d49-9d15-d379c4776949)

## Actual Experience ##
There is a successful activity log.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/d96801e2-93a1-4145-82ca-3cc9acb6a995)

**Comment by JasonYeMSFT** [comment]
I think my fix missed the build on 1/2/2024. Let's verify the fix on 1/3/2024.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240103.2. Fixed. So, we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/56a5d96c-e816-4111-b755-a4ca635e011e)
