### ISSUE TITLE
Miss '...' for the action 'Break Lease' against one blob

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7636]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20240103.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.2(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.32.1)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Right click the blob.
4. Check whether shows '...' for the action 'Break Lease'.

## Expected Experience ##
Show '...' for the action 'Break Lease'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/f6bb5356-8a49-48c1-bc21-5e9dd4a70b14)

## Actual Experience ##
No '...' shows for the action 'Break Lease'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/2fb459f7-115c-4664-8339-2688af9f00e6)

## Additional Context ##
Here is the break lease dialog for blobs.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/0e7a63c8-247b-4586-9976-64348838e6a9)

**Comment by MRayermannMSFT** [comment]
We have decided to remove the '...' in this case.

**Comment by v-xianya** [comment]
@MRayermannMSFT When breaking lease for blobs. There is not just a confirm dialog, it needs user to type blobs name to continue.  So, I thought it would make sense to show 'Break Lease...'.

**Comment by MRayermannMSFT** [comment]
For the purposes of deciding if there should be a "...", we're going to treat this as a basic confirmation dialog.
