### ISSUE TITLE
There is an extra dot at the end of the tooltip for 'Edit Tags' button against one app configuration

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7638]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20240104.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.2(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand 'App Configurations' -> Open one app configuration.
2. Hover over 'Edit Tags' button -> Observe the tooltip.
3. Check whether there is no extra dot at the end of the tooltip.

## Expected Experience ##
There is no extra dot at the end of the tooltip.

## Actual Experience ##
There is an extra dot at the end of the tooltip.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/a7eb660d-f1b9-4b32-b51e-3004658cead9)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240625.2. Reproduce. So we are going to re-open it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/26d7f7ee-c9f5-4763-b946-5191778d8da7)

**Comment by craxal** [comment]
Fix is merged, but the fix has not yet been integrated.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20241115.2. fixed. So, we are going to close it.
![Image](https://github.com/user-attachments/assets/4522b5ee-4eac-43d0-aeab-40e1055a7a81)
