### ISSUE TITLE
Error 403 when try access to Blob containers

### ISSUE THREAD

**Issue by csilva1971** [microsoft/AzureStorageExplorer#7642]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

When try access the blob storage of the Storage Explorer a reciebed the error 403 a not can access

### Desired Solution

The steeps for solution the problem

### Additional Context

Detalles del error: {   "name": "RestError",   "code": "AuthorizationPermissionMismatch",   "statusCode": 403,   "request": {     "streamResponseStatusCodes": {},     "url": "https://storagecheckstores.blob.core.windows.net/?comp=list&include=metadata",     "method": "GET",     "headers": {       "_headersMap": {         "x-ms-version": {           "name": "x-ms-version",           "value": "2021-10-04"         },         "accept": {           "name": "Accept",           "value": "application/xml"         },         "user-agent": {           "name": "User-Agent",           "value": "Microsoft Azure Storage Explorer/1.31.1 (win32) azsdk-js-storageblob/12.12.0 (NODE-VERSION v18.15.0; Windows_NT 10.0.22631)"         },         "x-ms-client-request-id": {           "name": "x-ms-client-request-id",           "value": "474a1056-2638-485b-bdfc-e4609031af91"         },         "authorization": {           "name": "authorization",           "value": "Bearer JSON Web Token Redacted"         }       }     },     "withCredentials": false,     "timeout": 0,     "keepAlive": true,     "decompressResponse": false,     "requestId": "474a1056-2638-485b-bdfc-e4609031af91"   },   "response": {     "request": {       "streamResponseStatusCodes": {},       "url": "https://storagecheckstores.blob.core.windows.net/?comp=list&include=metadata",       "method": "GET",       "headers": {         "_headersMap": {           "x-ms-version": {             "name": "x-ms-version",             "value": "2021-10-04"           },           "accept": {             "name": "Accept",             "value": "application/xml"           },           "user-agent": {             "name": "User-Agent",             "value": "Microsoft Azure Storage Explorer/1.31.1 (win32) azsdk-js-storageblob/12.12.0 (NODE-VERSION v18.15.0; Windows_NT 10.0.22631)"           },           "x-ms-client-request-id": {             "name": "x-ms-client-request-id",             "value": "474a1056-2638-485b-bdfc-e4609031af91"           },           "authorization": {             "name": "authorization",             "value": "Bearer JSON Web Token Redacted"           }         }       },       "withCredentials": false,       "timeout": 0,       "keepAlive": true,       "decompressResponse": false,       "requestId": "474a1056-2638-485b-bdfc-e4609031af91"     },     "status": 403,     "headers": {       "_headersMap": {         "content-length": {           "name": "content-length",           "value": "279"         },         "content-type": {           "name": "content-type",           "value": "application/xml"         },         "date": {           "name": "date",           "value": "Fri, 05 Jan 2024 14:51:51 GMT"         },         "server": {           "name": "server",           "value": "Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0"         },         "x-ms-client-request-id": {           "name": "x-ms-client-request-id",           "value": "474a1056-2638-485b-bdfc-e4609031af91"         },         "x-ms-error-code": {           "name": "x-ms-error-code",           "value": "AuthorizationPermissionMismatch"         },         "x-ms-request-id": {           "name": "x-ms-request-id",           "value": "0ff407d6-901e-002c-1ce6-3f9bcc000000"         },         "x-ms-version": {           "name": "x-ms-version",           "value": "2021-10-04"         }       }     },     "bodyAsText": "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.\nRequestId:0ff407d6-901e-002c-1ce6-3f9bcc000000\nTime:2024-01-05T14:51:52.0596847Z</Message></Error>",     "parsedBody": {       "message": "This request is not authorized to perform this operation using this permission.\nRequestId:0ff407d6-901e-002c-1ce6-3f9bcc000000\nTime:2024-01-05T14:51:52.0596847Z",       "code": "AuthorizationPermissionMismatch"     },     "parsedHeaders": {       "errorCode": "AuthorizationPermissionMismatch",       "content-length": "279",       "content-type": "application/xml",       "date": "Fri, 05 Jan 2024 14:51:51 GMT",       "server": "Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0",       "x-ms-client-request-id": "474a1056-2638-485b-bdfc-e4609031af91",       "x-ms-request-id": "0ff407d6-901e-002c-1ce6-3f9bcc000000",       "x-ms-version": "2021-10-04"     }   },   "details": {     "errorCode": "AuthorizationPermissionMismatch",     "content-length": "279",     "content-type": "application/xml",     "date": "Fri, 05 Jan 2024 14:51:51 GMT",     "server": "Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0",     "x-ms-client-request-id": "474a1056-2638-485b-bdfc-e4609031af91",     "x-ms-request-id": "0ff407d6-901e-002c-1ce6-3f9bcc000000",     "x-ms-version": "2021-10-04",     "message": "This request is not authorized to perform this operation using this permission.\nRequestId:0ff407d6-901e-002c-1ce6-3f9bcc000000\nTime:2024-01-05T14:51:52.0596847Z",     "code": "AuthorizationPermissionMismatch"   } }

**Comment by craxal** [comment]
@csilva1971 Please provide as much information as possible from our [bug template](https://github.com/microsoft/AzureStorageExplorer/issues/new?assignees=&labels=&projects=&template=bug_report.yml). Especially provide steps you took that led to the error. Please also let us know the following:
* How are you authenticating with Azure? For example, are you signing in or using a SAS?
* If you are signing in, can you confirm that you have the necessary RBAC permissions as described in our [troubleshooting guide](https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/storage-explorer-troubleshooting?tabs=Windows#azure-rbac-permissions-issues)?
* If you are using a SAS, can you confirm the SAS grants the [necessary permissions](https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/storage-explorer-troubleshooting?tabs=Windows#issues-with-a-shared-access-signature-url)?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. This issue will no longer be monitored. If you need further help, we recommend opening a support ticket via the Azure portal. Alternatively you can open a new issue here.
