### ISSUE TITLE
Feature Request: Add support for DeviceCode 

### ISSUE THREAD

**Issue by cdiskan** [microsoft/AzureStorageExplorer#7644]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Azure storage explorer requires a browser on the device in order to sign in.

### Desired Solution

Support az login --use-device-code or other similar method to authenticate Azure storage explorer by using a web browser on a separate device

### Alternatives and Workarounds

Currently utilizing connection strings and keys for individual storage accounts. However, this does not scale well as we have hundreds of storage accounts. Additionally, doing so negativley impacts logging, as actions taken under SAS are not uniquely attributable to a user for legal\auditing purposes. 

### Additional Context

In highly regulated environments, use of web browsers is significantly limited. When migrating large amounts of data, Azure storage explorer is most effectively run on well-connected high availability systems. However, these devices are also the least likely to be able to run a web browser. (Either from a technical or regulatory limitation). To address this issue, Azure storage explorer should allow sign-in via device code in the same manner that Azure CLI on powershell does. This would eliminate the dependency on having a browser that can reach the internet installed on the storage server(s) that Storage Explorer is installed on. Additionally it would allow storage explorer to login when used as a Remote App (Via Remote Desktop Services) which currently does not function because the storage explorer login process takes place in a different process\application than is being broadcast via remote desktop services.

**Comment by JasonYeMSFT** [comment]
Could you try go to Settings > Application > Sign In With and change it to "Device Code Flow"? I believe it can achieve what you want.

**Comment by MRayermannMSFT** [comment]
As @JasonYeMSFT says, this is already implemented. See here for instructions. 
https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-sign-in#changing-where-sign-in-happens
