### ISSUE TITLE
There is an extra scrollbar in the 'Shared Access Signature' dialog for one storage account if click the link 'Learn more about shared access signatures'

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7645]
**Storage Explorer Version:** 1.33.0-dev (96)
**Build Number:** 20240106.11
**Branch:** main
**Platform/OS:** Windows 10
**Architecture:** x64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Select and right click one storage account.
2. Click 'Get Shared Access Signature...'.
3. Click the link 'Learn more about shared access signatures'.
4. Check there is no extra scrollbar.

## Expected Experience ##
There is no extra scrollbar.

## Actual Experience ##
There is an extra scrollbar.
Here is the record:
![shared](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/aa36f5ae-da74-4982-92dd-9275bc73939c)

## Additional Context ##
This issue doesn't reproduce for blob containers/file shares/queues/tables.

**Comment by craxal** [comment]
The scroll bar is inserted because the content size increases from the focus border. This is easily fixed by changing the border to an outline, which does not take up any space.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240109.2. Fixed.
