### ISSUE TITLE
Getting Error in Azure Authentication

### ISSUE THREAD

**Issue by himanshusaini-fa** [microsoft/AzureStorageExplorer#7647]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.321

### Architecture

x64

### Storage Explorer Build Number

20231114.10

### Platform

Windows

### OS Version

11

### Bug Description

{
  "name": null,
  "message": "{\"source\":{\"accountId\":\"af9abd0f-5552-4441-87ef-4fa4245a2c7b.a797b4e5-32f0-48af-a044-0ba31874fa00:9CC2FC93E1FBA83A5E6B08C17028B6080A53EAA1598D0E099F72AA3ADB95A25C\",\"tenantId\":\"a797b4e5-32f0-48af-a044-0ba31874fa00\"},\"resourceId\":\"https://management.core.windows.net/\",\"code\":\"AADSTS50173\",\"message\":\"\"}"
}

Getting above Error while authenticating with Azure

### Steps to Reproduce

Sign in to Azure. Browser says authenticated but Storage Explorer shows error after 10 sec

### Actual Experience

Sign in to Azure. Browser says authenticated but Storage Explorer shows error after 10 sec

**Comment by MRayermannMSFT** [comment]
Hi @himanshusaini-fa can you try:
1. Goto to Help > Reset
2. Only select "Authentication"
3. Click "Reset"
4. Restart Storage Explorer
5. Try signing in again

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. This issue will no longer be monitored. If you need further help, we recommend opening a support ticket via the Azure portal. Alternatively you can open a new issue here.
