### ISSUE TITLE
The red border overlaps the username box border on the 'Proxy Settings' dialog when the username is missing

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7649]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20240106.11
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.2(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.32.1)

## Steps to Reproduce ##
1. Launch Storage Explorer -> Click 'Edit -> Configure Proxy'.
2. Select 'Use system proxy' as the source -> Check the option 'Use a username and password'.
3. Check if the red border doesn't overlap the username box border.

## Expected Experience ##
The red border doesn't overlap the username box border.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/abf99287-2887-421e-ab17-f44f28435730)

## Actual Experience ##
The red border overlaps the username box border.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/0e1aa33a-469a-45c1-995c-a2d8a18608e8)

**Comment by craxal** [comment]
I forgot to set the outline offset.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240109.2. Fixed.
