### ISSUE TITLE
unable to login to azure

### ISSUE THREAD

**Issue by sushmakasim** [microsoft/AzureStorageExplorer#765]
**Storage Explorer Version**: 
**Platform/OS Version**: 
**Architecture**: 
**Regression From**: 

#### Steps to Reproduce: ####
1. 
2.

**Comment by sushmakasim** [comment]
Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: bd5c6713-7399-4b31-be79-78f2d078e543, Error: {"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}

**Comment by jaypetrin** [comment]
I am seein g this as well. Not sure if it matters but I am using AAD with Multifactor Auth

**Comment by sterkhedkar** [comment]
@sushmakasim what method were you using for logging in?

In case you are using `azcopy login` on a linux terminal, try this:
`azcopy login --tenant-id "your-tenant-id"`

**Comment by MRayermannMSFT** [comment]
Hi all, are you still encountering problems? If so, please try the latest version of Storage Explorer, 1.12.0.

If in that version you are still having problems, please try enabling MSAL. MSAL is a newer auth library we are offering via preview setting. You can enable it via Settings -> Application -> Sign in. Thanks!

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
