### ISSUE TITLE
The 'Filter by prefix' box is not focused if press Ctrl+F in the view all containers explorer

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7659]
**Storage Explorer Version:** 1.33.0-dev (96)
**Build Number:** 20240109.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.2(Apple M1 Pro)
**Architecture:** x64/x64/arm64
**How Found:** From running test cases
**Regression From:** Previous release (1.32.1)

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Right click Blob Containers node -> Click 'View All'.
3. Press Ctrl+F.
4. Check whether the 'Filter by prefix' box is focused.

## Expected Experience ##
The 'Filter by prefix' box is focused.

## Actual Experience ##
The 'Filter by prefix' box is not focused.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240110.3. Fixed. So, we are going to close it.
