### ISSUE TITLE
Fail to load services for attached national accounts with Key and Name

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#766]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181015.10
**Commit**: 0a03e736
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Sign in with China/Germany account.
2. Attach one account with Key and Name.
**Display name**: alphaxuantestacc
**Primary Key:** I2pAvjgk90in2Sm9QlK+lp9R36+IR7gWhmy3JbOWzAScn94euZI1JO7vQbK1rc5x0/PjnlhH+ziReIAYWg8L5g==
3. Expand 'Local &Attached' -> Storage Account ->The attached account -> Blob Containers.

#### Expected Experience: ####
There is no error and these services can be loaded successfully.

#### Actual Experience: ####
An error occurs when attempting to load services for the attached account.
![error](https://user-images.githubusercontent.com/34729022/47006914-a08a7580-d169-11e8-932a-579c41d1ec69.png)

**Comment by MRayermannMSFT** [comment]
@v-xuanzh , did you choose the correct storage endpoints domain?

![image](https://user-images.githubusercontent.com/21112697/47120798-e1939000-d224-11e8-9cb1-b62d3c4fba6d.png)

**Comment by v-xuanzh** [comment]
Ahhhhhhhh. Sorry for reporting this issue. I forgot to choose the endpoint domain. Could you help to resolve it?
