### ISSUE TITLE
An extra scrollbar displays in the 'Quick Access Error' dialog for one QA queue/table which associated account is removed

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7661]
**Storage Explorer Version:** 1.33.0-dev (96)
**Build Number:** 20240110.3
**Branch:** main
**Platform/OS:** Windows 10
**Architecture:** x64
**How Found:** From running test cases
**Regression From:** Previous release (1.32.1)

## Steps to Reproduce ##
1. Expand one storage account -> Queues.
2. Create a queue -> Add the queue to quick access.
3. Switch to ACCOUNT MANAGEMENT panel -> Remove the associated account.
4. Go to EXPLORE panel -> The QA queue displays as broken.
5. Right click the broken queue -> Click 'View Error...'.
6. Check whether no extra scrollbar displays in the 'Quick Access Error' dialog.

## Expected Experience ##
No extra scrollbar displays in the 'Quick Access Error' dialog.

## Actual Experience ##
An extra scrollbar displays in the 'Quick Access Error' dialog.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/612d6472-7ac7-4290-9aa7-920ac9978b04)

## Additional Context ##
This issue also reproduces for broken tables.

**Comment by craxal** [comment]
In this case, the scroll box is doing its job. I don't think we need to worry about where the extra pixel or two came from.
