### ISSUE TITLE
not able to load file storage 

### ISSUE THREAD

**Issue by amchakr** [microsoft/AzureStorageExplorer#7662]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.1

### Architecture

i86

### Platform

All

### Bug Description

{
  "name": null,
  "message": "\"{\\n  \\\"name\\\": \\\"Node Fetch Error\\\",\\n  \\\"message\\\": \\\"Connect Timeout Error\\\",\\n  \\\"stack\\\": \\\"ConnectTimeoutError: Connect Timeout Error\\\\n    at onConnectTimeout (/private/var/folders/4q/w1bcxs792bnff031k_8rcjd0kzh5dl/T/AppTranslocation/8FB91ED2-B185-426B-B6FA-C0CAD53A5AA3/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/undici/lib/core/connect.js:182:24)\\\\n    at /private/var/folders/4q/w1bcxs792bnff031k_8rcjd0kzh5dl/T/AppTranslocation/8FB91ED2-B185-426B-B6FA-C0CAD53A5AA3/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/undici/lib/core/connect.js:129:46\\\\n    at Immediate._onImmediate (/private/var/folders/4q/w1bcxs792bnff031k_8rcjd0kzh5dl/T/AppTranslocation/8FB91ED2-B185-426B-B6FA-C0CAD53A5AA3/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/undici/lib/core/connect.js:170:9)\\\\n    at process.processImmediate (node:internal/timers:476:21)\\\",\\n  \\\"cause\\\": {\\n    \\\"cause\\\": {\\n      \\\"name\\\": \\\"ConnectTimeoutError\\\",\\n      \\\"code\\\": \\\"UND_ERR_CONNECT_TIMEOUT\\\",\\n      \\\"message\\\": \\\"Connect Timeout Error\\\"\\n    }\\n  },\\n  \\\"code\\\": \\\"UND_ERR_CONNECT_TIMEOUT\\\"\\n}\""
}

### Steps to Reproduce

1. Launch storage explorer 
2. login azure account 

### Actual Experience

{
  "name": null,
  "message": "\"{\\n  \\\"name\\\": \\\"Node Fetch Error\\\",\\n  \\\"message\\\": \\\"Connect Timeout Error\\\",\\n  \\\"stack\\\": \\\"ConnectTimeoutError: Connect Timeout Error\\\\n    at onConnectTimeout (/private/var/folders/4q/w1bcxs792bnff031k_8rcjd0kzh5dl/T/AppTranslocation/8FB91ED2-B185-426B-B6FA-C0CAD53A5AA3/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/undici/lib/core/connect.js:182:24)\\\\n    at /private/var/folders/4q/w1bcxs792bnff031k_8rcjd0kzh5dl/T/AppTranslocation/8FB91ED2-B185-426B-B6FA-C0CAD53A5AA3/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/undici/lib/core/connect.js:129:46\\\\n    at Immediate._onImmediate (/private/var/folders/4q/w1bcxs792bnff031k_8rcjd0kzh5dl/T/AppTranslocation/8FB91ED2-B185-426B-B6FA-C0CAD53A5AA3/d/Microsoft Azure Storage Explorer.app/Contents/Resources/app/node_modules/undici/lib/core/connect.js:170:9)\\\\n    at process.processImmediate (node:internal/timers:476:21)\\\",\\n  \\\"cause\\\": {\\n    \\\"cause\\\": {\\n      \\\"name\\\": \\\"ConnectTimeoutError\\\",\\n      \\\"code\\\": \\\"UND_ERR_CONNECT_TIMEOUT\\\",\\n      \\\"message\\\": \\\"Connect Timeout Error\\\"\\n    }\\n  },\\n  \\\"code\\\": \\\"UND_ERR_CONNECT_TIMEOUT\\\"\\n}\""
}

### Expected Experience

able to load the file explorer

**Comment by craxal** [comment]
@amchakr Are you able to successfully sign in? Please tell us more about your environment. Are you attempting to connect through a proxy server? Do you need to use custom certificates?
