### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by AhmedAbdElbary** [microsoft/AzureStorageExplorer#7663]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version
1.32.1

### Regression From
1.31.2

### Architecture

i86

### Storage Explorer Build Number

20231114.10

### Platform

Windows

### OS Version

Windows 10

### Bug Description
![image](https://github.com/microsoft/AzureStorageExplorer/assets/48794067/7b33e9ee-8453-4d28-a153-49d1e450980d)

 A full error producer json is attached below:
[Azure storage explorer error.json](https://github.com/microsoft/AzureStorageExplorer/files/13886959/Azure.storage.explorer.error.json)

### Steps to Reproduce

1. Launch Microsoft Azure Storage Explorer
2. Add Storage Account
3. Expand Storage Accounts/Account/Blob Containers
4 Attached a video below

https://github.com/microsoft/AzureStorageExplorer/assets/48794067/6fdfdd55-4752-4f52-91a6-1a1563643f72

### Actual Experience

Error and cannot expand resource child

### Expected Experience

expand resource child

**Comment by craxal** [comment]
@AhmedAbdElbary How did you connect to the storage account (sign in, SAS, etc.)? Do you have the correct permissions to list blob containers?

**Comment by AhmedAbdElbary** [comment]
I am connecting to the storage account via a connection string. BTW I am accessing an storage image within a docker container.

**Comment by craxal** [comment]
@AhmedAbdElbary

> BTW I am accessing an storage image within a docker container.

Do you mean that you are running an Azurite Docker image and are trying to access an emulator running in a Docker container? Have you configured the container ports to accept traffic from the host machine (https://hub.docker.com/_/microsoft-azure-storage-azurite)?

**Comment by AhmedAbdElbary** [comment]
Exactly, I am using this docker image "mcr.microsoft.com/azure-blob-storage" 
The connection string is like:
BlobEndpoint=http://{{hostAdress}}:11002/{{Account}};AccountName={{AcountName}};AccountKey={{AccountKey}};

**Comment by craxal** [comment]
@AhmedAbdElbary If your blob endpoint is configured to listen to port 11002, then you will likely need to run the Docker container with a command like this (if you haven't already done so):

```
docker run -p 11002:10002 mcr.microsoft.com/azure-storage/azurite
```
or
```
docker run -p 11002:11002 mcr.microsoft.com/azure-storage/azurite --blobPort 11002
```

**Comment by AhmedAbdElbary** [comment]
I've run the docker image, I can access all children/blobs with Storage Explorer Version 1.31.2 but I am not able to access the children (error mentioned above) within versions 1.32.1 or 1.32.0

Both scenarios using the same image and connection string.

**Comment by craxal** [comment]
@AhmedAbdElbary Hmm. That's unusual, because I can successfully connect, upload, etc. with 1.32.1 myself. This is command I ran to start the container:

```
 docker run -p 10000:10000 mcr.microsoft.com/azure-storage/azurite
```

Other than alternative port numbers, are you running your container with other options?

**Comment by AhmedAbdElbary** [comment]
@craxal I am using this image :"mcr.microsoft.com/azure-blob-storage"
which is run with this command: 
docker run -d --name=azure-blob-storage --env=LOCAL_STORAGE_ACCOUNT_NAME=*** --env=LOCAL_STORAGE_ACCOUNT_KEY=*** --volume=blob-data:/blobroot -p 11002:11002 --restart=unless-stopped mcr.microsoft.com/azure-blob-storage:latest

**Comment by craxal** [comment]
Apologies, I asked if you were trying to connect to an Azurite Docker image, and you replied yes. Since Azurite is an emulator, I assumed you were trying to connect to an emulator docker container.

If I understand correctly, you are actually trying to connect to an isolated Azure Blob IoT instance and not public Azure or an emulator.

Have you switched Storage Explore to Azure Stack mode? This changes the API version Storage Explorer uses to the version used by Azure Stack and IoT.

![image](https://github.com/microsoft/AzureStorageExplorer/assets/3473026/8fc6ffbc-050e-4ca6-9c35-f12f008f733c)

If that doesn't work, can you please share your connection string (without the sensitive parts, like the account key)? Have you followed the steps to set up the Docker container as an IoT device from the Azure portal (this link may be helpful: https://learn.microsoft.com/en-us/azure/iot-edge/how-to-store-data-blob?view=iotedge-1.4).

**Comment by daiy03** [comment]
Any update on this? I've tried other patch versions for v1.31, still the same error.

**Comment by AhmedAbdElbary** [comment]
> Apologies, I asked if you were trying to connect to an Azurite Docker image, and you replied yes. Since Azurite is an emulator, I assumed you were trying to connect to an emulator docker container.
> 
> If I understand correctly, you are actually trying to connect to an isolated Azure Blob IoT instance and not public Azure or an emulator.
> 
> Have you switched Storage Explore to Azure Stack mode? This changes the API version Storage Explorer uses to the version used by Azure Stack and IoT.
> 
> ![image](https://private-user-images.githubusercontent.com/3473026/300567473-8fc6ffbc-050e-4ca6-9c35-f12f008f733c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNTU3OTAsIm5iZiI6MTcwNzI1NTQ5MCwicGF0aCI6Ii8zNDczMDI2LzMwMDU2NzQ3My04ZmM2ZmZiYy0wNTBlLTRjYTYtOWMzNS1mMTJmMDA4ZjczM2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDZUMjEzODEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzkzMWI2OGRhNjRmODViNGNkZTZkOWVjNTg5MzUxNTA1ODQyOGY0M2Q1YTA3YzI5MDU4NzdhY2M3MzM3MjY2YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.waPyxxy5yxtbGBnsdE473d_IjHPQewxWBvPGqbP8Swk)
> 
> If that doesn't work, can you please share your connection string (without the sensitive parts, like the account key)? Have you followed the steps to set up the Docker container as an IoT device from the Azure portal (this link may be helpful: https://learn.microsoft.com/en-us/azure/iot-edge/how-to-store-data-blob?view=iotedge-1.4).

Yeah @craxal, it worked when I activated this option

**Comment by daiy03** [comment]
Mine's running Azurite installed via npm, but getting the above error after importing certs:

```
Unable to retrieve child resources

ProducerError:{
  "name": "Node Fetch Error",
  "message": "unable to verify the first certificate",
  "stack": "Error: unable to verify the first certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1540:34)\n    at TLSSocket.emit (node:events:513:28)\n    at TLSSocket._finishInit (node:_tls_wrap:959:8)\n    at ssl.onhandshakedone (node:_tls_wrap:743:12)",
  "cause": {
    "cause": {
      "code": "UNABLE_TO_VERIFY_LEAF_SIGNATURE"
    }
  },
  "code": "UNABLE_TO_VERIFY_LEAF_SIGNATURE"
}
```

Followed the [instructions](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&bc=%2Fazure%2Fstorage%2Fblobs%2Fbreadcrumb%2Ftoc.json&tabs=npm%2Cblob-storage#https-connection-strings), using the connections string.

@craxal toggling that Azure Stack didn't fix it though.

**Comment by craxal** [comment]
@AhmedAbdElbary Glad you got things working!

@daiy03 I was a bit confused earlier. If you're trying to connect to Azurite, that's an entirely separate issue from this one. _This_ issue is about connecting to an Azure Blob IoT instance.

I don't think you need to import any certificates to use a local emulator. Do you still have issues if you do not import certificates?

A few more troubleshooting tips:
* You said you installed Azurite via npm, you said. Did you install azurite globally (`npm install -g azurite`).
* Did you start Azurite (run `azurite` from the command line)?
* Are you using the default ports? If not, did you use the Connect dialog to create a connection with those ports?

If you're still having trouble, you can open a new bug to help keep our discussions focused.
