### ISSUE TITLE
There is no red border on the new added property box for 'Add/Edit Entity' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7665]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20240110.12
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.2(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.32.1)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Click ''Add'.
3. Click 'Add Property'.
4. Check whether there is a red border on the new added property box.

## Expected Experience ##
There is a red border on the new added property box.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/716bce91-0689-469a-a709-2175a30ff4a7)

## Actual Experience ##
There is no red border on the new added property box.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/5e99ec8e-1f0f-4ea4-91dd-798ff34e449d)

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240113.2. Reproduce. Will verify it on a newer build.

**Comment by craxal** [comment]
The change has been merged but not verified (a package update is required). You can wait till this issue is closed before trying to verify yourself.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240120.3. Fixed.
