### ISSUE TITLE
The order of the actions between the attached file shares and other three attached services is inconsistent

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7669]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20240112.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.2(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Attach the blob container via SAS URL.
3. Right click the attached blob container -> Observe its context menu.
4. Create a file share -> Attach the file share via SAS URL.
5. Right click the attached file share -> Observe its context menu.
6. Check whether the order of the actions between the two attached services is consistent.

## Expected Experience ##
The order of the actions is consistent. 

## Actual Experience ##
The order of the actions is inconsistent. 
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/d0404f9f-be89-4817-a564-2ad92e8e7b5d)

## Additional Context ##
Here is the screenshot for attached tables/queues.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/77c20ffd-8537-437d-b939-6699ec573018)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240328.5. Fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/e7f1a721-61d7-4dbb-a62c-b6d4c5be532e)
