### ISSUE TITLE
The alert icon is incorrectly displayed as an empty square when the key value is empty for one app configuration

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7674]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20240113.2
**Branch**: main
**Platform/OS**: Windows 10/MacOS Sonoma 14.2(Apple M1 Pro)
**Architecture**: x64/arm64
**App Config Version:** 0.2.1
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand App Configurations -> Open one app configuration.
2. Click 'Add' -> Type a value in the key field then empty the field.
3. There is an alert message.
4. Check the alert icon shows well.

## Expected Experience ##
The alert icon shows well.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/6f7fc697-1758-4a9a-aeb8-2a3a062a212f)

## Actual Experience ##
Show an empty square instead of an alert icon.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/6fd407d2-8ba0-46e0-a99b-57a580c1f533)

## Additional Context ##
This issue doesn't reproduce when installing App Configuration 0.2.0.

**Comment by craxal** [comment]
@v-xianya This work item is marked as Verifying, meaning it's not Done yet. We still need to update the package before it can be closed.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240305.7 with App configuration 0.2.2. Fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/de0b74f6-1016-459c-918f-730e0dc22d5e)
