### ISSUE TITLE
Login into Azure not working

### ISSUE THREAD

**Issue by Theragus** [microsoft/AzureStorageExplorer#768]
**Storage Explorer Version**: 1.4.4
**Platform/OS Version**: Windows 10 (1809)
**Architecture**: ia32
**Regression From**: Was never working

#### Steps to Reproduce: ####
Login to Azure

#### Expected Experience: ####
Login into the Azure Storage Explorer with my credentials

#### Actual Experience: ####
Login Windows just shows white with "Browser-SSO" in the title bar and never logs me in.
Were using ADFS with Windows Authentication.

**Comment by juve** [comment]
I am having a similar problem on Mac OS. I just get a pop-up saying I am being redirected to my organization's sign-in page, and then I get a blank window and nothing happens.

**Comment by jinglouMSFT** [comment]
@Theragus, can you please upgrade to 1.6.x and give this another try?  Also, if you use proxy, make sure you first config the proxy. 

@juve can you try with the steps outlined in #126?

**Comment by juve** [comment]
@jinglouMSFT thank you for the reference. Those steps did not work for me. It does ask for access to the keychain when I start storage explorer, but I still get the same blank window when I try to sign in to my account.

**Comment by Theragus** [comment]
@jinglouMSFT I now upgrade to 1.6.1 but the issue still persists. Redirecting to Orga Sign In Page and blank page
![ase](https://user-images.githubusercontent.com/38653346/50288939-af422100-0467-11e9-90c7-ea1e8cb5980f.PNG)

**Comment by Theragus** [comment]
After deactivating all other option except Formular Auth in the ADFS I was prompted for a login from the ADFS Server. The Issue seems to be related with the Windows and the Windows Passport Auth.

**Comment by jinglouMSFT** [comment]
@Theragus Thanks for the info.
@juve Your issue will require additional information and therefore I recommend you opening a support request with our support team. Here is a link for the instructions:  https://docs.microsoft.com/en-us/azure/azure-supportability/how-to-create-azure-support-request

**Comment by MRayermannMSFT** [comment]
Hello to anyone watching this issue! In 1.7.0 we're introducing the ability to optionally sign-in via device code flow, or as you may be more familiar with, copying a code from Storage Explorer into a page in your browser, and then signing in via your browser.

We're currently previewing that feature in our insiders channel. If y'all are intereseted in trying it early, simply go to Help -> Opt-in To Insider Builds.
![image](https://user-images.githubusercontent.com/21112697/52584072-04563f80-2de6-11e9-90c1-094e4bbcd0b4.png)
Then, go to Help -> Check for updates, wait for 1.7.0 to appear, and install it. Then once you install it, you can enable device code flow by going to Experimental -> Use Device Code Flow Sign In. 
![image](https://user-images.githubusercontent.com/21112697/52584173-3e274600-2de6-11e9-85af-6ed3cf5ed006.png)

And then let us know if things work out for y'all! This issue of blank sign in dialog is one we've been fighting for the longest time, and we're hoping this method of sign-in will unblock y'all. 😄

**Comment by MRayermannMSFT** [comment]
Closing this due to lack of response.

**Comment by andyghc** [comment]
I'm having the same issue in v1.16.0.  
Steps:
Select "add an Azure account"
Next a popup window titled "Sign in to your account" appears, I enter my corporate email address and click next
Briefly I see my corporate logo appear but then a blank window with "Browser SSO" appears and that's as far as it gets.  
I am using a corporate proxy which does do SSL inspection also, but there is a SSL proxy bypass rule in place for Azure storage accounts in place.  

However, when I went in to Edit -> Settings screen and ticked the "Use device code flow sign-in" option, and then followed the instructions to login via a browser, the login worked great and was able to access all storage I had access to.  So that works now.
