### ISSUE TITLE
Authentication Error - Blob Container

### ISSUE THREAD

**Issue by jroh-aa** [microsoft/AzureStorageExplorer#7689]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.1

### Regression From

1.32.1

### Architecture

x64

### Storage Explorer Build Number

20231114.10

### Platform

Windows

### OS Version

Windows 10 Enterprise

### Bug Description

Authentication Error when trying to access Blob Containers

### Steps to Reproduce

1. Launch Storage Explorer
2. Open Blob Container

### Actual Experience

This request is not authorized to perform this operation.

This storage account's 'Firewalls & virtual networks' settings may be blocking access to storage services. Try adding your client IP address to the firewall exceptions, or by allowing access from 'all networks' instead of 'selected networks'. To learn more about Azure Storage firewalls and virtual networks, visit http://go.microsoft.com/fwlink/?LinkId=845443.

Error Details:
{
  "name": "RestError",
  "code": "AuthorizationFailure",
  "statusCode": 403,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://aabaoriondlsnp.blob.core.windows.net/?comp=list&include=metadata",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2023-01-03"
        },
        "accept": {
          "name": "Accept",
          "value": "application/xml"
        },
        "user-agent": {
          "name": "User-Agent",
          "value": "Microsoft Azure Storage Explorer/1.32.1 (win32) azsdk-js-storageblob/12.15.0 (NODE-VERSION v18.16.1; Windows_NT 10.0.19045)"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "30032919-ef46-40b9-9cb1-e77560308691"
        },
        "authorization": {
          "name": "authorization",
          "value": "Bearer JSON Web Token Redacted"
        }
      }
    },
    "withCredentials": false,
    "timeout": 0,
    "keepAlive": true,
    "decompressResponse": false,
    "requestId": "30032919-ef46-40b9-9cb1-e77560308691"
  },
  "response": {
    "request": {
      "streamResponseStatusCodes": {},
      "url": "https://aabaoriondlsnp.blob.core.windows.net/?comp=list&include=metadata",
      "method": "GET",
      "headers": {
        "_headersMap": {
          "x-ms-version": {
            "name": "x-ms-version",
            "value": "2023-01-03"
          },
          "accept": {
            "name": "Accept",
            "value": "application/xml"
          },
          "user-agent": {
            "name": "User-Agent",
            "value": "Microsoft Azure Storage Explorer/1.32.1 (win32) azsdk-js-storageblob/12.15.0 (NODE-VERSION v18.16.1; Windows_NT 10.0.19045)"
          },
          "x-ms-client-request-id": {
            "name": "x-ms-client-request-id",
            "value": "30032919-ef46-40b9-9cb1-e77560308691"
          },
          "authorization": {
            "name": "authorization",
            "value": "Bearer JSON Web Token Redacted"
          }
        }
      },
      "withCredentials": false,
      "timeout": 0,
      "keepAlive": true,
      "decompressResponse": false,
      "requestId": "30032919-ef46-40b9-9cb1-e77560308691"
    },
    "status": 403,
    "headers": {
      "_headersMap": {
        "content-length": {
          "name": "content-length",
          "value": "246"
        },
        "content-type": {
          "name": "content-type",
          "value": "application/xml"
        },
        "date": {
          "name": "date",
          "value": "Fri, 19 Jan 2024 20:14:51 GMT"
        },
        "server": {
          "name": "server",
          "value": "Microsoft-HTTPAPI/2.0"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "30032919-ef46-40b9-9cb1-e77560308691"
        },
        "x-ms-error-code": {
          "name": "x-ms-error-code",
          "value": "AuthorizationFailure"
        },
        "x-ms-request-id": {
          "name": "x-ms-request-id",
          "value": "0a0637ba-701e-00d0-7614-4b5ed8000000"
        }
      }
    },
    "bodyAsText": "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.\nRequestId:0a0637ba-701e-00d0-7614-4b5ed8000000\nTime:2024-01-19T20:14:52.1515380Z</Message></Error>",
    "parsedBody": {
      "message": "This request is not authorized to perform this operation.\nRequestId:0a0637ba-701e-00d0-7614-4b5ed8000000\nTime:2024-01-19T20:14:52.1515380Z",
      "code": "AuthorizationFailure"
    },
    "parsedHeaders": {
      "errorCode": "AuthorizationFailure",
      "content-length": "246",
      "content-type": "application/xml",
      "date": "Fri, 19 Jan 2024 20:14:51 GMT",
      "server": "Microsoft-HTTPAPI/2.0",
      "x-ms-client-request-id": "30032919-ef46-40b9-9cb1-e77560308691",
      "x-ms-request-id": "0a0637ba-701e-00d0-7614-4b5ed8000000"
    }
  },
  "details": {
    "errorCode": "AuthorizationFailure",
    "content-length": "246",
    "content-type": "application/xml",
    "date": "Fri, 19 Jan 2024 20:14:51 GMT",
    "server": "Microsoft-HTTPAPI/2.0",
    "x-ms-client-request-id": "30032919-ef46-40b9-9cb1-e77560308691",
    "x-ms-request-id": "0a0637ba-701e-00d0-7614-4b5ed8000000",
    "message": "This request is not authorized to perform this operation.\nRequestId:0a0637ba-701e-00d0-7614-4b5ed8000000\nTime:2024-01-19T20:14:52.1515380Z",
    "code": "AuthorizationFailure"
  }
}

**Comment by MRayermannMSFT** [comment]
@jroh-aa it looks like you are tring to list containers in your storage account, authenticating with RBAC/OAuth/Microsoft Entra. Please make sure you have an RBAC role which gives you the ability to list blob containers. such as "Blob Data Reader".

**Comment by jroh-aa** [comment]
It seems to be working now. I'm not sure what was the issue
