### ISSUE TITLE
Storage Explorer Login Issue

### ISSUE THREAD

**Issue by cloudcomputing4ari** [microsoft/AzureStorageExplorer#7690]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.0

### Architecture

i86

### Platform

Windows

### OS Version

Windows 10

### Bug Description

{
  "name": null,
  "message": "\"{\\n  \\\"name\\\": \\\"TypeError\\\",\\n  \\\"message\\\": \\\"Cannot read properties of null (reading 'exp')\\\",\\n  \\\"stack\\\": \\\"TypeError: Cannot read properties of null (reading 'exp')\\\\n    at TokenCache.refreshCachedToken (C:\\\\\\\\Users\\\\\\\\Arindam\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\out\\\\\\\\app\\\\\\\\main\\\\\\\\UserAccountManagement\\\\\\\\TokenCache.js:36:38)\\\\n    at IdentityUserAccountsManager._getTenantToken (C:\\\\\\\\Users\\\\\\\\Arindam\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\out\\\\\\\\app\\\\\\\\main\\\\\\\\UserAccountManagement\\\\\\\\IdentityUserAccountsManager.js:907:50)\\\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\\\n    at async Provider.executeOperation (C:\\\\\\\\Users\\\\\\\\Arindam\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\out\\\\\\\\app\\\\\\\\providers\\\\\\\\Provider.js:28:16)\\\\n    at async ElectronMainHost.executeOperation (C:\\\\\\\\Users\\\\\\\\Arindam\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\out\\\\\\\\app\\\\\\\\main\\\\\\\\ElectronMainHost.js:26:20)\\\\n    at async Object.getToken (C:\\\\\\\\Users\\\\\\\\Arindam\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\@storage-explorer\\\\\\\\azure-sdk-helpers\\\\\\\\dist\\\\\\\\src\\\\\\\\CoreRest\\\\\\\\CoreRestClient.js:142:37)\\\\n    at async SubscriptionLister.listSubscriptions (C:\\\\\\\\Users\\\\\\\\Arindam\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\out\\\\\\\\app\\\\\\\\main\\\\\\\\AzureSubscriptions\\\\\\\\SubscriptionLister.js:26:23)\\\\n    at async SubscriptionListingClient.runOperation (C:\\\\\\\\Users\\\\\\\\Arindam\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\@storage-explorer\\\\\\\\azure-sdk-helpers\\\\\\\\dist\\\\\\\\src\\\\\\\\CoreRest\\\\\\\\CoreRestClient.js:110:24)\\\\n    at async SubscriptionService._getAccountSubscriptionsForTenants (C:\\\\\\\\Users\\\\\\\\Arindam\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\out\\\\\\\\app\\\\\\\\main\\\\\\\\AzureSubscriptions\\\\\\\\SubscriptionService.js:42:49)\\\\n    at async SubscriptionService.getTenantSubscriptions (C:\\\\\\\\Users\\\\\\\\Arindam\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\out\\\\\\\\app\\\\\\\\main\\\\\\\\AzureSubscriptions\\\\\\\\SubscriptionService.js:24:16)\\\"\\n}\""
}

### Steps to Reproduce

Azure Dala Lake login using storage explorer

### Actual Experience

{
  "name": null,
  "message": "\"{\\n  \\\"name\\\": \\\"TypeError\\\",\\n  \\\"message\\\": \\\"Cannot read properties of null (reading 'exp')\\\",\\n  \\\"stack\\\": \\\"TypeError: Cannot read properties of null (reading 'exp')\\\\n    at TokenCache.refreshCachedToken (C:\\\\\\\\Users\\\\\\\\Arindam\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\out\\\\\\\\app\\\\\\\\main\\\\\\\\UserAccountManagement\\\\\\\\TokenCache.js:36:38)\\\\n    at IdentityUserAccountsManager._getTenantToken (C:\\\\\\\\Users\\\\\\\\Arindam\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\out\\\\\\\\app\\\\\\\\main\\\\\\\\UserAccountManagement\\\\\\\\IdentityUserAccountsManager.js:907:50)\\\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\\\n    at async Provider.executeOperation (C:\\\\\\\\Users\\\\\\\\Arindam\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\out\\\\\\\\app\\\\\\\\providers\\\\\\\\Provider.js:28:16)\\\\n    at async ElectronMainHost.executeOperation (C:\\\\\\\\Users\\\\\\\\Arindam\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\out\\\\\\\\app\\\\\\\\main\\\\\\\\ElectronMainHost.js:26:20)\\\\n    at async Object.getToken (C:\\\\\\\\Users\\\\\\\\Arindam\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\@storage-explorer\\\\\\\\azure-sdk-helpers\\\\\\\\dist\\\\\\\\src\\\\\\\\CoreRest\\\\\\\\CoreRestClient.js:142:37)\\\\n    at async SubscriptionLister.listSubscriptions (C:\\\\\\\\Users\\\\\\\\Arindam\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\out\\\\\\\\app\\\\\\\\main\\\\\\\\AzureSubscriptions\\\\\\\\SubscriptionLister.js:26:23)\\\\n    at async SubscriptionListingClient.runOperation (C:\\\\\\\\Users\\\\\\\\Arindam\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\@storage-explorer\\\\\\\\azure-sdk-helpers\\\\\\\\dist\\\\\\\\src\\\\\\\\CoreRest\\\\\\\\CoreRestClient.js:110:24)\\\\n    at async SubscriptionService._getAccountSubscriptionsForTenants (C:\\\\\\\\Users\\\\\\\\Arindam\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\out\\\\\\\\app\\\\\\\\main\\\\\\\\AzureSubscriptions\\\\\\\\SubscriptionService.js:42:49)\\\\n    at async SubscriptionService.getTenantSubscriptions (C:\\\\\\\\Users\\\\\\\\Arindam\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\out\\\\\\\\app\\\\\\\\main\\\\\\\\AzureSubscriptions\\\\\\\\SubscriptionService.js:24:16)\\\"\\n}\""
}

### Additional Context

{
  "name": null,
  "message": "\"{\\n  \\\"name\\\": \\\"TypeError\\\",\\n  \\\"message\\\": \\\"Cannot read properties of null (reading 'exp')\\\",\\n  \\\"stack\\\": \\\"TypeError: Cannot read properties of null (reading 'exp')\\\\n    at TokenCache.refreshCachedToken (C:\\\\\\\\Users\\\\\\\\Arindam\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\out\\\\\\\\app\\\\\\\\main\\\\\\\\UserAccountManagement\\\\\\\\TokenCache.js:36:38)\\\\n    at IdentityUserAccountsManager._getTenantToken (C:\\\\\\\\Users\\\\\\\\Arindam\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\out\\\\\\\\app\\\\\\\\main\\\\\\\\UserAccountManagement\\\\\\\\IdentityUserAccountsManager.js:907:50)\\\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\\\n    at async Provider.executeOperation (C:\\\\\\\\Users\\\\\\\\Arindam\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\out\\\\\\\\app\\\\\\\\providers\\\\\\\\Provider.js:28:16)\\\\n    at async ElectronMainHost.executeOperation (C:\\\\\\\\Users\\\\\\\\Arindam\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\out\\\\\\\\app\\\\\\\\main\\\\\\\\ElectronMainHost.js:26:20)\\\\n    at async Object.getToken (C:\\\\\\\\Users\\\\\\\\Arindam\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\@storage-explorer\\\\\\\\azure-sdk-helpers\\\\\\\\dist\\\\\\\\src\\\\\\\\CoreRest\\\\\\\\CoreRestClient.js:142:37)\\\\n    at async SubscriptionLister.listSubscriptions (C:\\\\\\\\Users\\\\\\\\Arindam\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\out\\\\\\\\app\\\\\\\\main\\\\\\\\AzureSubscriptions\\\\\\\\SubscriptionLister.js:26:23)\\\\n    at async SubscriptionListingClient.runOperation (C:\\\\\\\\Users\\\\\\\\Arindam\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\node_modules\\\\\\\\@storage-explorer\\\\\\\\azure-sdk-helpers\\\\\\\\dist\\\\\\\\src\\\\\\\\CoreRest\\\\\\\\CoreRestClient.js:110:24)\\\\n    at async SubscriptionService._getAccountSubscriptionsForTenants (C:\\\\\\\\Users\\\\\\\\Arindam\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\out\\\\\\\\app\\\\\\\\main\\\\\\\\AzureSubscriptions\\\\\\\\SubscriptionService.js:42:49)\\\\n    at async SubscriptionService.getTenantSubscriptions (C:\\\\\\\\Users\\\\\\\\Arindam\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\out\\\\\\\\app\\\\\\\\main\\\\\\\\AzureSubscriptions\\\\\\\\SubscriptionService.js:24:16)\\\"\\n}\""
}

**Comment by MRayermannMSFT** [comment]
@cloudcomputing4ari please upgrade to the latest Storage Explorer, sign out, and try again.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. This issue will no longer be monitored. If you need further help, we recommend opening a support ticket via the Azure portal. Alternatively you can open a new issue here.
