### ISSUE TITLE
Storage Explorer Access Issue

### ISSUE THREAD

**Issue by micoach** [microsoft/AzureStorageExplorer#7691]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

Versión: 1.32.1 (96)

### Architecture

x64

### Storage Explorer Build Number

20231114.10

### Platform

macOS

### OS Version

Sonoma

### Bug Description

I can't create folders or upload files into my account. I've tried to delete the content, to create a new one, to create one with different configuration and nothing is working. 

### Steps to Reproduce

Error 1
Failed to update storage account 'conferencias'. Error:
The resource '788d4384-dbbf-40ae-a1e3-2a38f26ffOab'
does not exist.

Error 2
No se pudo crear el contenedor de blobs "trainingcursos": Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:2862d8aa-a01e-0058-541f-4ca21d000000
Time:2024-01-21T04:05:45.4989610Z

Error 3
Failed to add directory 'conferencias'. Error:
OperationTimedOut: Operation could not be completed
within the specified time.
Requestld:5dae18cb-401f-002b-5a26-4c64ae000000
Time:2024-01-21T04:58:57.0121205Z

Operation could not be completed within the specified time.

Error 4
Esta solicitud no está autorizada para realizar esta operación.

Es posible que la configuración "Firewalls y redes virtuales" de esta cuenta de almacenamiento esté bloqueando el acceso a los servicios de almacenamiento. Intente agregar la dirección IP del cliente a las excepciones del firewall o permita el acceso desde "todas las redes" en lugar de "redes seleccionadas". Para obtener más información sobre firewalls y redes virtuales de Azure Storage, visite http://go.microsoft.com/fwlink/?LinkId=845443.

Detalles del error:
{
  "name": "RestError",
  "code": "AuthenticationFailed",
  "statusCode": 403,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://trainingconferences.blob.core.windows.net/?comp=list&include=metadata",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2023-01-03"
        },
        "accept": {
          "name": "Accept",
          "value": "application/xml"
        },
        "user-agent": {
          "name": "User-Agent",
          "value": "Microsoft Azure Storage Explorer/1.32.1 (darwin) azsdk-js-storageblob/12.15.0 (NODE-VERSION v18.16.1; Darwin 23.2.0)"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "e666fc59-0286-471d-a358-b5815bd5371b"
        },
        "x-ms-date": {
          "name": "x-ms-date",
          "value": "Sun, 21 Jan 2024 04:46:42 GMT"
        },
        "authorization": {
          "name": "Authorization",
          "value": "SharedKey Redacted"
        }
      }
    },
    "withCredentials": false,
    "timeout": 0,
    "keepAlive": true,
    "decompressResponse": false,
    "requestId": "e666fc59-0286-471d-a358-b5815bd5371b"
  },
  "response": {
    "request": {
      "streamResponseStatusCodes": {},
      "url": "https://trainingconferences.blob.core.windows.net/?comp=list&include=metadata",
      "method": "GET",
      "headers": {
        "_headersMap": {
          "x-ms-version": {
            "name": "x-ms-version",
            "value": "2023-01-03"
          },
          "accept": {
            "name": "Accept",
            "value": "application/xml"
          },
          "user-agent": {
            "name": "User-Agent",
            "value": "Microsoft Azure Storage Explorer/1.32.1 (darwin) azsdk-js-storageblob/12.15.0 (NODE-VERSION v18.16.1; Darwin 23.2.0)"
          },
          "x-ms-client-request-id": {
            "name": "x-ms-client-request-id",
            "value": "e666fc59-0286-471d-a358-b5815bd5371b"
          },
          "x-ms-date": {
            "name": "x-ms-date",
            "value": "Sun, 21 Jan 2024 04:46:42 GMT"
          },
          "authorization": {
            "name": "Authorization",
            "value": "SharedKey trainingconferences:cccRCkxBh+/6VJGTk1Qez3Uov+TCMu1YQPgxXWhkWps="
          }
        }
      },
      "withCredentials": false,
      "timeout": 0,
      "keepAlive": true,
      "decompressResponse": false,
      "requestId": "e666fc59-0286-471d-a358-b5815bd5371b"
    },
    "status": 403,
    "headers": {
      "_headersMap": {
        "content-length": {
          "name": "content-length",
          "value": "737"
        },
        "content-type": {
          "name": "content-type",
          "value": "application/xml"
        },
        "date": {
          "name": "date",
          "value": "Sun, 21 Jan 2024 04:46:43 GMT"
        },
        "server": {
          "name": "server",
          "value": "Microsoft-HTTPAPI/2.0"
        },
        "x-ms-error-code": {
          "name": "x-ms-error-code",
          "value": "AuthenticationFailed"
        },
        "x-ms-request-id": {
          "name": "x-ms-request-id",
          "value": "16bd4132-d01e-0020-7e24-4c01e5000000"
        }
      }
    },
    "bodyAsText": "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:16bd4132-d01e-0020-7e24-4c01e5000000\nTime:2024-01-21T04:46:43.3762791Z</Message><AuthenticationErrorDetail>The MAC signature found in the HTTP request 'cccRCkxBh+/6VJGTk1Qez3Uov+TCMu1YQPgxXWhkWps=' is not the same as any computed signature. Server used following string to sign: 'GET\n\n\n\n\n\n\n\n\n\n\n\nx-ms-client-request-id:e666fc59-0286-471d-a358-b5815bd5371b\nx-ms-date:Sun, 21 Jan 2024 04:46:42 GMT\nx-ms-version:2023-01-03\n/trainingconferences/\ncomp:list\ninclude:metadata'.</AuthenticationErrorDetail></Error>",
    "parsedBody": {
      "message": "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:16bd4132-d01e-0020-7e24-4c01e5000000\nTime:2024-01-21T04:46:43.3762791Z",
      "code": "AuthenticationFailed",
      "AuthenticationErrorDetail": "The MAC signature found in the HTTP request 'cccRCkxBh+/6VJGTk1Qez3Uov+TCMu1YQPgxXWhkWps=' is not the same as any computed signature. Server used following string to sign: 'GET\n\n\n\n\n\n\n\n\n\n\n\nx-ms-client-request-id:e666fc59-0286-471d-a358-b5815bd5371b\nx-ms-date:Sun, 21 Jan 2024 04:46:42 GMT\nx-ms-version:2023-01-03\n/trainingconferences/\ncomp:list\ninclude:metadata'."
    },
    "parsedHeaders": {
      "errorCode": "AuthenticationFailed",
      "content-length": "737",
      "content-type": "application/xml",
      "date": "Sun, 21 Jan 2024 04:46:43 GMT",
      "server": "Microsoft-HTTPAPI/2.0",
      "x-ms-request-id": "16bd4132-d01e-0020-7e24-4c01e5000000"
    }
  },
  "details": {
    "errorCode": "AuthenticationFailed",
    "content-length": "737",
    "content-type": "application/xml",
    "date": "Sun, 21 Jan 2024 04:46:43 GMT",
    "server": "Microsoft-HTTPAPI/2.0",
    "x-ms-request-id": "16bd4132-d01e-0020-7e24-4c01e5000000",
    "message": "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:16bd4132-d01e-0020-7e24-4c01e5000000\nTime:2024-01-21T04:46:43.3762791Z",
    "code": "AuthenticationFailed",
    "AuthenticationErrorDetail": "The MAC signature found in the HTTP request 'cccRCkxBh+/6VJGTk1Qez3Uov+TCMu1YQPgxXWhkWps=' is not the same as any computed signature. Server used following string to sign: 'GET\n\n\n\n\n\n\n\n\n\n\n\nx-ms-client-request-id:e666fc59-0286-471d-a358-b5815bd5371b\nx-ms-date:Sun, 21 Jan 2024 04:46:42 GMT\nx-ms-version:2023-01-03\n/trainingconferences/\ncomp:list\ninclude:metadata'."
  }
}

### Actual Experience

I've tried online, i've tried with the app. And nothing happens, 3 days trying to access and it's says that I have no permission when I access with my admin email 

### Expected Experience

I want to fix it

**Comment by micoach** [comment]
![Uploading Screenshot 2024-01-20 at 11.04.33 p.m..png…]()

**Comment by micoach** [comment]
<img width="1428" alt="Screenshot 2024-01-20 at 11 07 18 p m" src="https://github.com/microsoft/AzureStorageExplorer/assets/157266366/f16084b5-a678-45db-af08-614fd83a76aa">

**Comment by MRayermannMSFT** [comment]
@micoach the most likely reason I could imagine for this is that you only have an RBAC role with gives you the ability to read data and not write data. I would recommend you open an Azure support ticket for this issue. You can do so in the portal b clicking on the (?) icon to the right of the search bar at the top of the portal.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. This issue will no longer be monitored. If you need further help, we recommend opening a support ticket via the Azure portal. Alternatively you can open a new issue here.
