### ISSUE TITLE
The file is opened when dragging and dropping it to versions/snapshots view for one file share/ADLS Gen2 blob /regular blob explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7693]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20240120.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.2(Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.32.1)

## Bug Descriptions ##
1. The file will be opened if drag and drop it to one Public attached blob container explorer.
2. The file will be opened if drag and drop it to Snapshots/Versions view.

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
3. Create a blob container -> Upload one blob.
4. Right click the blob -> Click 'Manage History -> Manage Versions'.
5. Drag and drop one file to the versions view.
6. Check there is an activity log, and no file is not opened.

## Expected Experience ##
1. There is an activity log.
2. No file is opened.

## Actual Experience ##
1. There is an activity log.
2. The file is opened.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/b6332f41-c9c3-4af8-89a9-c51e87ed180a)

**Comment by JasonYeMSFT** [comment]
I merged a change to prevent opening the file in a new window.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240123.1. Fixed. So, we are going to close it.
