### ISSUE TITLE
No '...' shows for the sub action 'Customize Columns' on the toolbar of one table

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7695]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20240123.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.2(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Click the dropdown button next to 'Customize Columns'.
3. Observe the actions.
4. Check whether shows '...' for the action 'Customize Columns'.
 
## Expected Experience ##
Show '...' for the action 'Customize Columns'.
## Actual Experience ##
No '...' shows for the action 'Customize Columns'.

![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/2a9e543d-b1b4-45e8-a76a-eb67e910c749)

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240128.2. Fixed. So, we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/92e9323d-da99-45ad-9772-06baddfcc948)

**Comment by craxal** [comment]
@v-xianya Actually, I'm going to revert the ellipsis addition. The strings are the same, and there's no way to divide them at the moment, and finding a way to do that is not a priority.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240130.3. Fixed. So, we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/20880744-585e-4e6b-adb9-fa3916e9e403)
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/c344d04c-b58a-4480-a37d-08262bffe927)
