### ISSUE TITLE
Cursor keys don't work as expected in tree view when creating queue

### ISSUE THREAD

**Issue by marcelvb** [microsoft/AzureStorageExplorer#7703]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.1

### Architecture

x64

### Storage Explorer Build Number

20231114.10

### Platform

All

### OS Version

Windows 11

### Bug Description

When creating a queue by right clicking Queues node in the Explorer, the cursor keys don't work as expected. When typing a name for a queue, and I made a typo, I press cursor left. This will not move the cursor, but will move the node in the tree, resetting my action.

### Steps to Reproduce

1. Right click Queues node in Explorer view
2. Click "Create Queue"
3. Start typing a few letters
4. Press cursor left

### Actual Experience

The selected node changes, undoing creation of the queue.

### Expected Experience

I expect the cursor to move left to edit the typed name.

**Comment by MRayermannMSFT** [comment]
A fix for this will be included in our 1.33 release.
