### ISSUE TITLE
It is better to remove the background color for the comparison operators box on the view options panel

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7704]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20240126.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.2(Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: Exploratory testing
**Regression From**: Previous release (1.32.1)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Open one blob container -> Open the view options panel.
3. Select 'Tag Query' -> Observe the comparison operators box.
4. Check whether the box has no background color.
 
## Expected Experience ##
The box has no background color.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/888a02ad-3cf6-4409-9cbd-b9ed88f8e1ba)

## Actual Experience ##
The box has a background color.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/9aa2a480-4a7c-4278-a136-b3be4530f582)

## Additional Context ##
This issue only reproduces on Light theme.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240130.3. Reproduce. So, we are going to reopen it.

**Comment by craxal** [comment]
I somehow forgot to publish and integrate the changes.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240130.14. Fixed. So, we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/24eea531-6ed6-40a7-bc77-ae6a1de30c3d)
