### ISSUE TITLE
The tree node always keeps loading on MacOS

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7707]
**Storage Explorer Version:** 1.33.0-dev (96)
**Build Number**: 20240128.2
**Branch:** main
**Platform/OS:** MacOS Sonoma 14.3(Apple M1 Pro)
**Architecture:** x64
**How Found:** From running test cases
**Regression From:** Previous release (1.32.1)

## Steps to Reproduce ##

1. Download the Mac build StorgeExplorer-darwin-arm64.zip -> Expand the .zip file.
2. Double click the file 'Microsoft Azure Storage Explorer' to open Storage Explorer.
3. Check whether the tree node is loaded successfully.

## Expected Experience ##
The tree node is loaded successfully.

## Actual Experience ##
The tree node always keeps loading.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/4dd31374-13d0-4a5d-bdd2-0676bc073069)

## Additional Context ##
This issue doesn't reproduce on Windows & Linux.

**Comment by MRayermannMSFT** [comment]
Related to https://github.com/electron/electron/pull/41028. Will be able to fix once a new MSFT electron is available.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240130.14. Fixed.

**Comment by MRayermannMSFT** [comment]
For the record @v-kellyluo , I didn't do anything to fix this, and as far as I know it should still repro haha. So feel free to reopen if you want!

**Comment by v-kellyluo** [comment]
Hi @MRayermannMSFT , this issue doesn't reproduce on the latest build 20240201.4. We will re-open it once it reproduces again.

**Comment by v-kellyluo** [comment]
This issue reproduces on the main build 20240203.7. So, we are going to re-open it.

**Comment by MRayermannMSFT** [comment]
This should be fixed now.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240207.6. Fixed.
