### ISSUE TITLE
Unable to retrieve child resources. Still.

### ISSUE THREAD

**Issue by bretthackermsft** [Microsoft/AzureStorageExplorer#771]
**Storage Explorer Version**: 1.4.4
**Architecture**: ia32
**Regression From**: version before last

#### Steps to Reproduce: ####
1. Expand ANY node (Local & Attached, or any Azure AD-authenticated subscription)
2. Throws the dialog, unable to continue

#### Expected Experience: ####
Seeing the actual resource nodes under the subscription

#### Actual Experience: ####
This dialog throws:
![dlg1](https://user-images.githubusercontent.com/24515695/47199802-04af6400-d339-11e8-8321-4a66345b52b3.png)

On clicking "OK", that dialog goes away and is replaced by this one:
![dlg2](https://user-images.githubusercontent.com/24515695/47199804-08db8180-d339-11e8-8889-a57dabf9c399.png)

App is completely unusable. Has been this way for 2 versions (at least) now. I have removed and re-added my accounts. This occurs expanding the Cosmos DB Accounts node or the Storage Accounts node.

**Comment by bretthackermsft** [comment]
Follow-up: the workaround someone posted on this issue in the last version (or the one before, not sure), still works. You can click File > New Window...and in the new instance, everything works exactly as expected. This is easily repro'd.

**Comment by khowling** [comment]
Thanks for the workaround! works a treat

**Comment by MRayermannMSFT** [comment]
I suggest using this workaround, it will unblock you without needing to open a new window: https://github.com/Microsoft/AzureStorageExplorer/issues/969#issuecomment-445064981
