### ISSUE TITLE
The scrollbar displays against the 'Manage Custom Environments' dialog rather than ‘custom environments’ part

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7710]
**Storage Explorer Version:** 1.33.0-dev (96)
**Build Number:** 20240130.3
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04
**Architecture**: x64/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.32.1)

## Steps to Reproduce ##

1. Open connect dialog -> Click 'Subscription'.
2. Select 'Custom Environment' -> Click 'Manage custom environments...'.
3. Add several custom environments to make the scrollbar to display.
4. Check whether the scrollbar displays against the 'custom environments' part.

## Expected Experience ##
The scrollbar displays against the 'custom environments' part.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/1074dffc-c07d-4b46-94b8-d7f3a595baf4)

## Actual Experience ##
The scrollbar displays against the 'Manage Custom Environments' dialog.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/14a50044-c43b-4ba5-a112-789ac995c8c4)

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240201.4. Fixed. 
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/ad2a21e1-7f0f-4779-b9c3-1da169b55f30)
