### ISSUE TITLE
The focused color of CORS rules is incorrect

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7711]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20240130.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04
**Architecture**: x64/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.32.1)

## Steps to Reproduce ##
1. Expand one storage account -> Right click 'Blob Containers' node.
2. Click 'Configure CORS Settings...' -> Add one CORS rule -> Save it.
3. Select the new added CORS rule.
4. Check whether the focused color is correct. 

## Expected Experience ##
The focused color is correct. 
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/9a524feb-6445-43b3-a89a-1bc77e68f777)

## Actual Experience ##
The focused color is incorrect. 
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/fc2464d6-dbd2-40c0-8d3f-850678b2da4c)

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240201.4.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/9e8dfae7-d93d-4410-ba26-5f4130578f54)

**Comment by craxal** [comment]
@v-xianya Notice the selection color fades to a gray when the list loses focus. This better matches how other controls appear (such as the data grid).
