### ISSUE TITLE
Look Into Shrinking .git Folder

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#7714]
As of this issue:
- Repo folder size: 2.87 GB
- Repo's .git folder size: 2.64 GB

The .git folder is 92% of the repo. Can we do anything to make it smaller/more compressed (without losing history ofc)?

For comparison:

VS Code
- Repo folder size: 1.04 GB
- Repo's .git folder size: 953.5 MB (92%)

React Native
- Repo folder size: 977.7 MB
- Repo's .git folder size: 933.7 MB (95%)

Based on those comparisions, the ratio we have (92%) doesn't seem out of the ordinary. Ultimately though, the size in growth of our .git folder has definitely contributed to some longer build times. If we can do something that could be helpful.

**Comment by craxal** [comment]
* Remove binary files from source. If binaries change frequently, this can contribute to a lot of repo bloat.
* Try `git repack` to combine old objects into more efficient packs and drop unreachable objects.
