### ISSUE TITLE
Nothing happens if press Enter when typing a name in the input text to create service

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7716]
**Storage Explorer Version:** 1.33.0-dev (96)
**Build Number:** 20240130.14
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.3(Apple M1 Pro)
**Architecture:** x64/x64/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.32.1)

## Steps to Reproduce ##

1. Expand one storage account.
2. Right click the 'Blob Containers' node -> Click 'Create Blob Container'.
3. Input a valid name in the text input -> Press Enter.
4. Check whether succeeds to create the blob container.

## Expected Experience ##
Succeed to create the blob container.

## Actual Experience ##
Nothing happens.

## Additional Context ##
This issue also reproduces for other services.

**Comment by MRayermannMSFT** [comment]
🤦@ myself

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240201.4. Fixed.
