### ISSUE TITLE
It would be better to keep one default visible column after clicking 'Hide All' on 'Column Options'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7718]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20240130.14
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.3(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Click 'Customize Columns'.
3. Click 'Hide All' on the 'Column Options' dialog.
4. Check the result.

## Expected Experience ##
It would be better to keep one default visible column.

## Actual Experience ##
All columns are hidden and there is an error message.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/2674dfef-e594-4b85-be9a-f34bda27e319)

## Additional Context ##
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/38fbdd42-488c-4f0b-9506-6d780f536b07)

**Comment by MRayermannMSFT** [comment]
I think this can wait till 1.34, but @craxal feel free to do it sooner if you want.

**Comment by craxal** [comment]
This is not trivial to do, because this dialog is used with other explorers, which may have other rules.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main 20240423.1. Fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/cd3e8618-bffe-4090-9bfd-0f176bea951d)
