### ISSUE TITLE
It is better to add a cancel action next to moving messages activity log

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7719]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20240201.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.3(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Queues.
2. Open one queue which contains more than 100 messages.
3. Select all the messages -> Click 'Move'.
4. Select one queue on the 'Move Messages' dialog -> Click 'Move' button.
5. Observe the move messages activity log.
6. Check whether there is a cancel action next to the activity log.

## Expected Experience ##
It is better to add a cancel action next to the activity log.

## Actual Experience ##
There is no cancel action next to the activity log.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/ac7a1108-10d0-4810-a1db-3a30cd952875)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240328.5. Fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/49722ceb-7357-4aaa-8d81-bc11bf123328)
