### ISSUE TITLE
Nothing happens after clicking the 'More troubleshooting help' link on 'Reset' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#772]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181018.2
**Commit**: b246d18d
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Navigate to Help menu -> Select 'Reset'.
2. Try to click the 'More troubleshooting help' link -> Check the result.

#### Expected Experience: ####
The web page of the troubleshooting will be opened successfully.

#### Actual Experience: ####
Nothing happens.

**Comment by v-xuanzh** [comment]
This issue also reproduces on the latest master build 20190702.3.

**Comment by v-xianya** [comment]
This issue also reproduces on build 20191220.9.

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
