### ISSUE TITLE
Fail to upload one blob with 'Cold' access tier under Azure China account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7720]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20240201.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.3(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Bug Descriptions ##
1. Fail to change blob access tier to 'Cold' with error 'The value for one of the HTTP headers is not in the correct format.'
2. Fail to upload one blob with 'Cold' access tier.

## Steps to Reproduce ##
1. Launch storage explorer with Azure China account.
2. Expand one storage account -> Blob Containers.
3. Create a blob container -> Click 'Upload -> Upload Files...'.
4. Select one file -> Select 'Cold' as the target access tier -> Click 'Upload'.
5. Check whether succeeds to upload the blob.

## Expected Experience ##
Succeed to upload the blob.

## Actual Experience ##
Fail to upload the blob.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/3e5ea159-b154-44d8-af25-3212f90c48a2)

## Additional Context ##
Here is the AzCopy Log:
[edb06eb5-f149-1747-740a-ca921f740e0a.log](https://github.com/microsoft/AzureStorageExplorer/files/14121914/edb06eb5-f149-1747-740a-ca921f740e0a.log)

**Comment by JasonYeMSFT** [comment]
The log indicates that "Cold" is not supported in this storage account.

**Comment by v-xianya** [comment]
Hi @JasonYeMSFT Because 'Cold' access tier is not supported in Azure China account. Is it possible to remove 'Cold' access tier in Azure China account.

In portal, there is no 'Cold' access in Azure China account.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/9ac2fc75-bc79-44ae-a9bb-611630486876)

**Comment by MRayermannMSFT** [comment]
Let's discuss what we want to do with this in our next triage.

**Comment by MRayermannMSFT** [comment]
We will double check that the root issue is that "Cold" is not supported for Azure China. If that is the root issue, we will close as "Won't fix". If it isn't, we will rediscuss where to go from there.

**Comment by JasonYeMSFT** [comment]
Quote from the service PM: "It's not supported yet in Azure China. The launch process is ongoing as we speak. It's likely to complete in next few weeks."

Let's keep the option in the product for 1.33.0.
