### ISSUE TITLE
Remove workaround for node-gyp issues

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#7722]
It looks like we can finally remove our workarounds for node-gyp https://github.com/nodejs/node-gyp/issues/2584.

The fix shipped in node-gyp 9.4.0: https://github.com/nodejs/node-gyp/releases/tag/v9.4.0

Electron 28 comes with node 18.18.2, which comes with npm 9.8.1, and that has node-gyp 9.4.0!
See: https://github.com/npm/cli/blob/facda25daab7cdd5f6aaad2260379aedeef33caa/package.json#L95

Electron 29 comes with node 20.9.0, which comes with npm 10.1.0, and that has node-gyp 9.4.0!
See: https://github.com/npm/cli/blob/39e2b87f283a80af8c79eb76096c017127b2d63f/package.json#L96

So I think we should be good to go. Perhaps as a smoke test, create a branch which installs like 4 copies each of our native modules (via the use of npm aliases), and run a couple of local and CI WIndows builds, making sure `npm install`/`npm run init` never fails.

This should probably be done after updating to Electron 29, after we have handled any breaking changes associated with moving to node 20.

**Comment by JasonYeMSFT** [comment]
This has been done for Electron 28. I'll close this issue and maybe re-open it if Electron 29 regresses and a new workaround needs to be implemented.
