### ISSUE TITLE
The access tier is not updated if overwrite a blob using a same blob with default access tier

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7726]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20240201.15
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.3(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob with the default access tier.
3. Change the access tier to 'Cold'.
4. Upload a same blob with the default access tier -> Apply the conflict.
5. Check whether the access tier is updated.

## Expected Experience ##
The access tier is updated.

## Actual Experience ##
The access tier is not updated.

**Comment by JasonYeMSFT** [comment]
This is the by design behavior. Setting "default" means letting the service decide the access tier of the blob. In the overwrite case, the service will preserve its previous access tier.

**Comment by v-xianya** [comment]
@JasonYeMSFT The default access tier is inferred from the access tier set on Account level.
If user want to overwrite a blob and use the default access tier inferred from account.
I wonder if it is possible to update the blob access tier with the default access tier inferred from account.
