### ISSUE TITLE
The column strings overlaps if narrow them horizontally

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7727]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20240201.15
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.3(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: exploratory testing
**Regression From**: Previous release (1.32.1)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Select 'Name' column -> Narrow the name column horizontally.
4. Check whether the sort icon does not overlap the 'Name' string.

## Expected Experience ##
The sort icon does not overlap the 'Name' string.

![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/0b8ed156-3443-48c2-9524-55b5f8caa090)

## Actual Experience ##
The sort icon overlaps the 'Name' string.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/a6336d0e-6c5d-4e0f-8a58-96a2059fd763)

## Additional Context ##
If narrow columns from the last one, the column strings will overlap.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240208.4. Reproduce. So, we are going to reopen it.

**Comment by craxal** [comment]
There seems to have been a mishap when updating the necessary packages, because the UI package containing the fix wasn't updated. I'm making new packages, so please try again with a later build.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240209.3. Fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/99e2ab34-3ad0-49ab-a039-9e5b123732fb)
