### ISSUE TITLE
No way to reset part of Storage Explorer

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#773]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181018.2
**Commit**: b246d18d
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Navigate to Help menu -> Select 'Reset'.
2. Select 'Authentication' to reset.

#### Expected Experience: ####
Only the 'Authentication' item is selected.

#### Actual Experience: ####
Both of them are selected.
![both_selected](https://user-images.githubusercontent.com/34729022/47206537-77612380-d3bb-11e8-9004-78e2803780b3.png)

**Comment by v-xianya** [comment]
Verified this issue on the latest build 20190618.3. It has been fixed. So we close it.
![image](https://user-images.githubusercontent.com/41351993/59650820-fe200780-91b9-11e9-96c7-5551267b99db.png)
