### ISSUE TITLE
Upload of 100 GB VHD Fails with 407 Proxy Authentication Required after 1/3 to 1/2 

### ISSUE THREAD

**Issue by Davidmack** [microsoft/AzureStorageExplorer#7731]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.31.2 (94)

### Architecture

x64

### Storage Explorer Build Number

20231004.10

### Platform

Windows

### OS Version

Windows 10

### Bug Description

5 gb vhd upload without issue - 70 gb fails about halfway through with 407
Proxy is set to System and valid auth credentials supplied

### Steps to Reproduce

1. Launch Storage Explorer
2. Navigate to Disks
3. Select VM
4. dlick upload
5. select local vhd
6. selecting V1 or V2 does not affect outcome
7. 

### Actual Experience

after some time failsRESPONSE Status: 407 Proxy Authentication Required
   Content-Length: [2309]
   Content-Type: [text/html]
   Date: [Sun, 04 Feb 2024 10:39:44 CST]
   Mime-Version: [1.0]
   Proxy-Authenticate: [NTLM]

### Expected Experience

successful upload of vhd which I can then attach

**Comment by MRayermannMSFT** [comment]
@Davidmack can you go to your `<user directory/.azcopy/` folder, find the log file associated with this disk upload, and then share that log file here? Thanks!
