### ISSUE TITLE
The location of the dialog title and the buttons 'Save' and 'Cancel' are incorrect if drag the bottom scrollbar to right

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7733]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20240204.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.3(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test case
**Regression From**: Previous release (1.32.1)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Right click one blob container -> Click 'Manage Stored Access Policies...'.
3. Click 'Add' on the 'Access Policies' dialog.
4. Drag the scrollbar to the right.
5. Check whether the location of the dialog title and the buttons 'Save' and 'Cancel' are correct.

## Expected Experience ##
The location of the dialog title and the buttons 'Save' and 'Cancel' are correct.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/806a3d46-d58c-48a4-bd21-41c28bd33462)

## Actual Experience ##
The location of the dialog title and the buttons 'Save' and 'Cancel' are incorrect.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/9e7f23d1-1788-4c34-a400-0bc86e26b5ed)

**Comment by craxal** [comment]
This does not reproduce if there is already at least one stored access policy for the container. The root of the issue in in the dialog window auto-sizing mechanism. It only runs once when the window is opened. In this case, an empty access policy list takes less space, so the dialog does grow as much when there are policies. But when a user adds a policy to the list, the dialog suddenly needs more space.

I think the answer here is not to remove all the labels when the list is empty. That way, the dialog is more correctly sized when it opens.

**Comment by v-xianya** [comment]
Hi @craxal Verified this issue on the main build 20240207.6. This issue doesn't reproduce on the new dialog.
There is an extra scrollbar on the new dialog if add five access policies for blob containers. 
Could you please help to take a look?
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/23b87538-7fbb-4813-93f9-c8c56ae3d15b)

**Comment by craxal** [comment]
@v-vianya Spacing should now be fixed.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240208.4. Fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/513d2946-627a-4237-88a1-ad0309b16d27)
