### ISSUE TITLE
Document Download via Cognitive Search not working when files moved to ADLS via Storage Explorer

### ISSUE THREAD

**Issue by Rahul-Mukherjee** [microsoft/AzureStorageExplorer#7736]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.31.0

### Architecture

i86

### Platform

All

### Bug Description

We are working in a migration project, where we need to move some blobs (pdf files) from ADLS of one tenant to another. I achieved this migration using Storage Explorer(copy/paste). 
Generally these files are send to ADLS through some Azure data factory pipeline. 
Now we have a cognitive search, where when we search any keyword contained in the ADLS files, it returns a link to download the relevant file from ADLS.
So this issue is the files which were moved through Storage Explorer are not getting downloaded and giving an error 
"""Error while fetching data from MICROSOFT API: Error: HttpClient.getResponse: Can't get the response from the server: Internal Error occurred: 'Error while parsing HTTP response"""
whereas the files getting populated from the ADF pipeline are downloaded.

### Steps to Reproduce

We are working in a migration project, where we need to move some blobs (pdf files) from ADLS of one tenant to another. I achieved this migration using Storage Explorer(copy/paste). 
Generally these files are send to ADLS through some Azure data factory pipeline. 
Now we have a cognitive search, where when we search any keyword contained in the ADLS files, it returns a link to download the relevant file from ADLS.
So this issue is the files which were moved through Storage Explorer are not getting downloaded and giving an error 
"""Error while fetching data from MICROSOFT API: Error: HttpClient.getResponse: Can't get the response from the server: Internal Error occurred: 'Error while parsing HTTP response"""
whereas the files getting populated from the ADF pipeline are downloaded.

### Actual Experience

We are working in a migration project, where we need to move some blobs (pdf files) from ADLS of one tenant to another. I achieved this migration using Storage Explorer(copy/paste). 
Generally these files are send to ADLS through some Azure data factory pipeline. 
Now we have a cognitive search, where when we search any keyword contained in the ADLS files, it returns a link to download the relevant file from ADLS.
So this issue is the files which were moved through Storage Explorer are not getting downloaded and giving an error 
"""Error while fetching data from MICROSOFT API: Error: HttpClient.getResponse: Can't get the response from the server: Internal Error occurred: 'Error while parsing HTTP response"""
whereas the files getting populated from the ADF pipeline are downloaded.

**Comment by MRayermannMSFT** [comment]
@Rahul-Mukherjee 
1. Can you download the files manually via Storage Explorer to confirm they were copy and pasted correctly?
2. Does the error from cognitive search give any more information? Perhaps what API it is try to call which is failing?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. This issue will no longer be monitored. If you need further help, we recommend opening a support ticket via the Azure portal. Alternatively you can open a new issue here.
