### ISSUE TITLE
All columns disappear in the service explorer if empty the value for one column on the 'Column Options' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7739]
**Storage Explorer Version**: 1.33.0-dev (96)
**Build Number**: 20240207.6
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.3(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Click 'Customize Columns'.
3. Empty the value for 'PartitionKey' -> Click 'OK'.
4. Check whether the 'RowKey' column shows well.

## Expected Experience ##
The 'RowKey' column shows well.

## Actual Experience ##
All columns disappear.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/55fa1a2d-4afa-4918-97ff-130ca8027c63)

**Comment by craxal** [comment]
@v-xianya When you say "empty value", I assume you mean you delete the text in the size input?

**Comment by v-xianya** [comment]
Yes, "empty value" means delete the text in the size input
Verified this issue on the main build 20240208.4. Reproduce. So, we are going to reopen it.

**Comment by craxal** [comment]
@v-xianya I've added additional validation logic and an error message.

**Comment by v-xianya** [comment]
Hi @craxal Thank you for the update. Verified this issue on the main build 20240209.3. 
The columns size has a validation. while an error message appears, the 'OK' button is still enabled. Could you help to check it?
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/fe6c3086-f6cf-4917-9b24-a02daa6da543)

**Comment by craxal** [comment]
I'll make sure the OK button is disabled.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240217.4. 'OK' button is disabled when there is an error message.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/fd9781ff-6741-479c-8709-1db4c1fee3e0)
