### ISSUE TITLE
Show an inconsistent icon between the base cosmos DB account and attached

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#774]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181018.2
**Commit**: b246d18d
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Right click one Cosmos DB account -> Select 'Copy Primary Connection String'.
2. Open 'Connect to Cosmos DB' dialog -> Paste the copied connection string -> Connect.
3. Check the displayed icon between the base account and attached.

#### Expected Experience: ####
Show a consistent icon.

#### Actual Experience: ####
Show an inconsistent icon.
![inconsistent](https://user-images.githubusercontent.com/34729022/47206833-37e70700-d3bc-11e8-8248-d06a6bbd96a5.png)

**Comment by v-xianya** [comment]
Verified on build 20190108.2. This issue doesn't reproduce. Could you help to resolve it?

**Comment by v-xianya** [comment]
Verified this issue on the latest build 20190618.3. It has been fixed.
![image](https://user-images.githubusercontent.com/41351993/59650991-b64db000-91ba-11e9-8378-5973704a06df.png)
