### ISSUE TITLE
Connection to local Azurite emulator over https Unable to retrieve child resources

### ISSUE THREAD

**Issue by daiy03** [microsoft/AzureStorageExplorer#7742]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.1

### Architecture

x64

### Storage Explorer Build Number

20231114.10

### Platform

Windows

### Bug Description

I have azurite running locally, installed with npm, and connecting with https as specified in the [documentation](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&bc=%2Fazure%2Fstorage%2Fblobs%2Fbreadcrumb%2Ftoc.json&tabs=visual-studio%2Cblob-storage#oauth-configuration)

I tried to attach the Storage Explorer to the emulator, following the [instructions](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&bc=%2Fazure%2Fstorage%2Fblobs%2Fbreadcrumb%2Ftoc.json&tabs=visual-studio%2Cblob-storage#connect-to-azurite-using-https) by importing the self-signed certificates used by the Azurite instance. However, the explorer throws the error when attempting to expand the storage nodes.

```
Unable to retrieve child resources

ProducerError:{
  "name": "Node Fetch Error",
  "message": "unable to verify the first certificate",
  "stack": "Error: unable to verify the first certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1543:34)\n    at TLSSocket.emit (node:events:513:28)\n    at TLSSocket._finishInit (node:_tls_wrap:962:8)\n    at TLSWrap.onhandshakedone (node:_tls_wrap:746:12)",
  "cause": {
    "cause": {
      "code": "UNABLE_TO_VERIFY_LEAF_SIGNATURE"
    }
  },
  "code": "UNABLE_TO_VERIFY_LEAF_SIGNATURE"
}
```

### Steps to Reproduce

1. Install Azurite via npm, generate self-signed certificates, and start Azurite `azurite --oauth basic --cert cert.pem --key key.pem`
2. Start the Storage Explorer, Connect to the emulator storage account using the https connection string
3. Attempt to explore the Tables, Queues or Blob Containers

### Actual Experience

An dialog opens with error:

```
Unable to retrieve child resources

ProducerError:{
  "name": "Node Fetch Error",
  "message": "unable to verify the first certificate",
  "stack": "Error: unable to verify the first certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1543:34)\n    at TLSSocket.emit (node:events:513:28)\n    at TLSSocket._finishInit (node:_tls_wrap:962:8)\n    at TLSWrap.onhandshakedone (node:_tls_wrap:746:12)",
  "cause": {
    "cause": {
      "code": "UNABLE_TO_VERIFY_LEAF_SIGNATURE"
    }
  },
  "code": "UNABLE_TO_VERIFY_LEAF_SIGNATURE"
}
```

### Expected Experience

I can explore data stored in the emulator

**Comment by MRayermannMSFT** [comment]
@daiy03 thanks for opening the issue.

Can you please refeer to these instructions? They go into a bit more detail than the one you have already found:

https://github.com/Azure/Azurite/blob/main/README.md#storage-explorer-with-azurite-https

One important thing to note in the doc I linked is:

> Storage Explorer doesn't currently work with certs produced by dotnet dev-certs. 

Additionally, you can also try enabling System Proxy :
1. Open Settings, via the gear icon in the vertical toolbar.
2. Enter "system proxy" in the search box at the top of the settings page.
3. Look for the the "Proxy Configuration" setting to appear, and then click the dropdown and choose "Use system proxy".

**Comment by daiy03** [comment]
Ah, splendid. Uploading the root cert worked, thanks @MRayermannMSFT

**Comment by fardarter** [comment]
@MRayermannMSFT I'm getting this same issue using `mkcert` and importing `rootCA.pem` from the same root as `mkcert -CAROOT`. Have tried both with and without system proxy enabled.
