### ISSUE TITLE
Show current version id of a blob

### ISSUE THREAD

**Issue by DJ4ddi** [microsoft/AzureStorageExplorer#7746]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I am unable to view the version id of the current blob version.
- None of the 4 view modes (e.g. "All blobs and blobs without current version") display the current version id in either flat or hierarchical view.
- "Manage history -> Manage versions" does not show the version id of the current blob (only for every previous version).
- The timestamp in "Properties" -> "CreatedOn" rounds away decimal digits, so this also can't be used.

### Desired Solution

The "Manage versions" view should display the version id of the current version. The property window should not round the timestamp.

**Comment by JasonYeMSFT** [comment]
In 1.34.0, I added a new column to show the version id of blob versions, including the version id of the current version. I also added the version id to the properties dialog so you can copy the value to the clipboard more easily.
