### ISSUE TITLE
Add validation model for blob containers

### ISSUE THREAD

**Issue by v-dantch** [microsoft/AzureStorageExplorer#775]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181018.2
**Commit**: b246d18d
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Right click one blob container ->Select 'Acquire Lease' -> Select 'Yes' to acquire.
2. Right click the same blob container -> Select 'Break Lease '.
3. Check the result.

#### Actual Experience: ####
Succeed to break lease by clicking 'Yes'.

#### Suggestion Experience: ####
Add validation model for blob containers.
![image](https://user-images.githubusercontent.com/34729092/47210817-8c8f7f80-d3c6-11e8-95e9-0e7ba3fe3b1c.png)

**Comment by MRayermannMSFT** [comment]
Won't fix.
