### ISSUE TITLE
The activity log is always in progress when pasting a blob container from a StorageV2 Premium account to a storage account that does not support page blobs

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7754]
**Storage Explorer Version**: 1.33.0 (97)
**Build Number**: 20240217.4
**Branch**: rel/1.33.0
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.3(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.32.1)

## Steps to Reproduce ##
1. Expand a StorageV2 Premium account (premium account with account type page blob) -> Blob Containers.
2. Create a blob container -> Upload one page blob.
3. Copy the blob container -> Paste it to one ADLS Gen2 storage account.
4. Check whether there is a failed activity log.

## Expected Experience ##
There is a failed activity log.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/c80f6cc2-10cd-4339-878a-df963ae9cae0)

## Actual Experience ##
The activity log is always in progress.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/6e5f6ebd-a68a-41f9-ad0b-80eb688d1ee5)

## Additional Context ##
This issue also reproduces when pasting the blob container to one Premium BlockBlobStorage account.

**Comment by JasonYeMSFT** [comment]
@v-xianya The next time you test on main branch, could you verify this bug one more time? We have integrated AzCopy 10.24.0 in main which should have a fix for this issue.

**Comment by v-xianya** [comment]
Got it. we will verify this issue on main branch after we finished hotfix testing.

**Comment by v-xianya** [comment]
We found the current main build is using AzCopy 10.23.0. will verify this issue once AzCopy 10.24.0 is integrated.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240416.1. Fixed. So, we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/71bc921f-0a81-4af0-befc-19c28835013a)
