### ISSUE TITLE
The authentication library used by Storage Explorer has failed to start properly.

### ISSUE THREAD

**Issue by MattHolton** [microsoft/AzureStorageExplorer#7757]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.1

### Regression From

1.32.0

### Architecture

x64

### Platform

Windows

### Bug Description

When I open MASE
![image](https://github.com/microsoft/AzureStorageExplorer/assets/160529024/b2cd49ae-8717-47c1-a662-e2a65e27fd04)

### Steps to Reproduce

Launch Storage application

### Actual Experience

When I open it, I get this error and then it closes.  Started doing it about a month ago and I have uninstalled and reinstalled everything and I have tried multiple computers. 

![image](https://github.com/microsoft/AzureStorageExplorer/assets/160529024/7f21aedf-ab59-4cba-b9ae-899ed908ce80)

**Comment by MRayermannMSFT** [comment]
@MattHolton please gather authentication logs and share those here. Please follow all instructions at this link to do so: https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/storage-explorer-troubleshooting?tabs=Windows#authentication-logs

**Comment by MattHolton** [comment]
[logs.zip](https://github.com/microsoft/AzureStorageExplorer/files/14496680/logs.zip)
Attached are the logs. I tried again today with the same error.

**Comment by MRayermannMSFT** [comment]
@MattHolten can you try running Storage Explorer as admin?

**Comment by MattHolton** [comment]
Yes and it works fine that way.  I can work with it that way.   THANK YOU!
