### ISSUE TITLE
The value of 'Retention Days' switches from the invalid to 365 directly after clicking the reduce button

### ISSUE THREAD

**Issue by v-dantch** [microsoft/AzureStorageExplorer#776]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181018.2
**Commit**: b246d18d
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Select one blob service node -> Select 'Configure Soft Delete Policy' ->Enable soft delete -> Type an invalid value like 1000.
2. Click the reduce button -> Check the result.

#### Expected Experience: ####
The invalid value minus one.

#### Actual Experience: ####
The value of 'Retention Days' switches from the invalid to 365 directly.
![image](https://user-images.githubusercontent.com/34729092/47207176-22bea800-d3bd-11e8-9036-865a5c5e59bc.png)

**Comment by v-xianya** [comment]
The current mechanism is good. So we close it.
