### ISSUE TITLE
The scrollbar doesn't move if press the arrow down key consistently in the 'Column Options' dialog

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7768]
**Storage Explorer Version:** 1.33.0 (97)
**Build Number:** 20240221.3
**Branch:** rel/1.33.0
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.3(Apple M1 Pro)
**Architecture:** x64/x64/arm64
**How Found:** From running test cases
**Regression From:** Previous release (1.32.1)

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Open a table which contains lot of custom properties.
3. Click 'Customize Columns' -> There is a scrollbar.
4. Click one column -> Press the arrow down key consistently.
5. Check whether the scrollbar moves.

## Expected Experience
The scrollbar moves.
![expect](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/106b2688-08a8-4d2e-b35c-a9e199f77ccd)

## Actual Experience ##
The scroll bar doesn't move.
![aztual](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/601e8b98-d422-42b0-826b-40c4ce32ef25)

**Comment by MRayermannMSFT** [comment]
Fix should be available in 20240224.3

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240225.5. Fixed.
![fixed](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/cfeebc45-0b4d-4e92-a64e-f56f8fad22ab)
