### ISSUE TITLE
unable to expand azure storage in explorer

### ISSUE THREAD

**Issue by handasunny** [microsoft/AzureStorageExplorer#7770]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

10.20.1

### Architecture

i86

### Platform

All

### OS Version

Windows server 2019

### Bug Description

Unable to retrieve child resources

ProducerError:{
  "name": "Node Fetch Error",
  "message": "getaddrinfo ENOTFOUND stcazurefiles01.file.core.windows.net",
  "stack": "Error: getaddrinfo ENOTFOUND stcazurefiles01.file.core.windows.net\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26)",
  "cause": {
    "cause": {
      "errno": -3008,
      "code": "ENOTFOUND",
      "syscall": "getaddrinfo",
      "hostname": "stcazurefiles01.file.core.windows.net"
    }
  },
  "code": "ENOTFOUND",
  "errno": -3008
}

### Steps to Reproduce

![error](https://github.com/microsoft/AzureStorageExplorer/assets/116026611/c3161055-e062-43e3-bf9c-2d15a0f08f41)

### Actual Experience

![error](https://github.com/microsoft/AzureStorageExplorer/assets/116026611/daf79e27-e4a7-4e50-b022-4ad7a75cb805)

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. This issue will no longer be monitored. If you need further help, we recommend opening a support ticket via the Azure portal. Alternatively you can open a new issue here.
