### ISSUE TITLE
The position of the horizontal scrollbar is incorrect on 'Properties' and 'Edit Tags' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7771]
**Storage Explorer Version**: 1.33.0 (97)
**Build Number**: 20240225.5
**Branch**: rel/1.33.0
**Platform/OS**: Linux Ubuntu 22.04
**Architecture**: x64
**How Found**: From running test cases
**Regression From**: Previous release (1.32.1)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Right click the blob container -> Click 'Properties'.
3. Add one metadata -> There is a horizontal scrollbar.
4. Check whether the scrollbar is in the Metadate section.

## Expected Experience ##
The scrollbar is in the Metadate section.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/6a918fd9-53c6-407a-b7f3-6eacf5b4ed42)

## Actual Experience ##
The scrollbar is not in the Metadate section.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/836fb662-55ec-475c-9c3e-f5ccf546fbd6)

## Additional Context ##
This issue also reproduces for 'Edit Tags' dialog.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/eaefd3b4-2b5a-4863-9773-e604508434d1)

**Comment by craxal** [comment]
I am not able to reproduce this issue on my Ubuntu 22.04 machine with the specified build or the current rel branch.

**Comment by v-xianya** [comment]
@craxal this issue reproduces on my side with the rel build 20240225.5.
Did you add a metadata on the properties dialog?

To reproduce this issue. Open the Properties dialog -> Add one metadata.

Also, to reproduce this issue on Edit Tags dialog, we need to add at least one tag in the dialog.

**Comment by v-xianya** [comment]
@craxal Here is the record:
![0228](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/4b6b3c48-f123-4d08-906f-ad0b94547383)

**Comment by craxal** [comment]
I'm afraid I still can't get this to repro. We don't consider this a serious issue, as the content is still accessible if you scroll. If you can provide any more information that would help us diagnose, that would be appreciated.
