### ISSUE TITLE
I don't have access to my Blob Containers

### ISSUE THREAD

**Issue by jenPG09** [microsoft/AzureStorageExplorer#7772]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.1

### Architecture

x64

### Storage Explorer Build Number

20231114.10

### Platform

Windows

### OS Version

Windows 11

### Bug Description

This request is not authorized to perform this operation.

This storage account's 'Firewalls & virtual networks' settings may be blocking access to storage services. Try adding your client IP address to the firewall exceptions, or by allowing access from 'all networks' instead of 'selected networks'. To learn more about Azure Storage firewalls and virtual networks, visit http://go.microsoft.com/fwlink/?LinkId=845443.

Error Details:
{
  "name": "RestError",
  "code": "AuthorizationFailure",
  "statusCode": 403,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://tpmsknimestorageprod01.blob.core.windows.net/?comp=list&include=metadata",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2023-01-03"
        },
        "accept": {
          "name": "Accept",
          "value": "application/xml"
        },
        "user-agent": {
          "name": "User-Agent",
          "value": "Microsoft Azure Storage Explorer/1.32.1 (win32) azsdk-js-storageblob/12.15.0 (NODE-VERSION v18.16.1; Windows_NT 10.0.22631)"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "3a3b220d-1646-42e0-ad15-bbc8fcd66e97"
        },
        "authorization": {
          "name": "authorization",
          "value": "Bearer JSON Web Token Redacted"
        }
      }
    },
    "withCredentials": false,
    "timeout": 0,
    "keepAlive": true,
    "decompressResponse": false,
    "requestId": "3a3b220d-1646-42e0-ad15-bbc8fcd66e97"
  },
  "response": {
    "request": {
      "streamResponseStatusCodes": {},
      "url": "https://tpmsknimestorageprod01.blob.core.windows.net/?comp=list&include=metadata",
      "method": "GET",
      "headers": {
        "_headersMap": {
          "x-ms-version": {
            "name": "x-ms-version",
            "value": "2023-01-03"
          },
          "accept": {
            "name": "Accept",
            "value": "application/xml"
          },
          "user-agent": {
            "name": "User-Agent",
            "value": "Microsoft Azure Storage Explorer/1.32.1 (win32) azsdk-js-storageblob/12.15.0 (NODE-VERSION v18.16.1; Windows_NT 10.0.22631)"
          },
          "x-ms-client-request-id": {
            "name": "x-ms-client-request-id",
            "value": "3a3b220d-1646-42e0-ad15-bbc8fcd66e97"
          },
          "authorization": {
            "name": "authorization",
            "value": "Bearer JSON Web Token Redacted"
          }
        }
      },
      "withCredentials": false,
      "timeout": 0,
      "keepAlive": true,
      "decompressResponse": false,
      "requestId": "3a3b220d-1646-42e0-ad15-bbc8fcd66e97"
    },
    "status": 403,
    "headers": {
      "_headersMap": {
        "content-length": {
          "name": "content-length",
          "value": "246"
        },
        "content-type": {
          "name": "content-type",
          "value": "application/xml"
        },
        "date": {
          "name": "date",
          "value": "Mon, 26 Feb 2024 16:30:10 GMT"
        },
        "server": {
          "name": "server",
          "value": "Microsoft-HTTPAPI/2.0"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "3a3b220d-1646-42e0-ad15-bbc8fcd66e97"
        },
        "x-ms-error-code": {
          "name": "x-ms-error-code",
          "value": "AuthorizationFailure"
        },
        "x-ms-request-id": {
          "name": "x-ms-request-id",
          "value": "6a5363a8-701e-0060-6dd1-683bce000000"
        }
      }
    },
    "bodyAsText": "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.\nRequestId:6a5363a8-701e-0060-6dd1-683bce000000\nTime:2024-02-26T16:30:11.8980973Z</Message></Error>",
    "parsedBody": {
      "message": "This request is not authorized to perform this operation.\nRequestId:6a5363a8-701e-0060-6dd1-683bce000000\nTime:2024-02-26T16:30:11.8980973Z",
      "code": "AuthorizationFailure"
    },
    "parsedHeaders": {
      "errorCode": "AuthorizationFailure",
      "content-length": "246",
      "content-type": "application/xml",
      "date": "Mon, 26 Feb 2024 16:30:10 GMT",
      "server": "Microsoft-HTTPAPI/2.0",
      "x-ms-client-request-id": "3a3b220d-1646-42e0-ad15-bbc8fcd66e97",
      "x-ms-request-id": "6a5363a8-701e-0060-6dd1-683bce000000"
    }
  },
  "details": {
    "errorCode": "AuthorizationFailure",
    "content-length": "246",
    "content-type": "application/xml",
    "date": "Mon, 26 Feb 2024 16:30:10 GMT",
    "server": "Microsoft-HTTPAPI/2.0",
    "x-ms-client-request-id": "3a3b220d-1646-42e0-ad15-bbc8fcd66e97",
    "x-ms-request-id": "6a5363a8-701e-0060-6dd1-683bce000000",
    "message": "This request is not authorized to perform this operation.\nRequestId:6a5363a8-701e-0060-6dd1-683bce000000\nTime:2024-02-26T16:30:11.8980973Z",
    "code": "AuthorizationFailure"
  }
}

### Steps to Reproduce

1. Launch Blob Storage Explorer
2. Open the Blob Containers of tpmsknimestorageprod01
![Prod Storage Explorer issue](https://github.com/microsoft/AzureStorageExplorer/assets/143435671/8535f84a-eb46-4ab6-bbfd-06d999f9dbec)

### Actual Experience

I have access from Web version, but I can't in the Storage Explorer when I'm from the office. It works when I'm working from home.

**Comment by MRayermannMSFT** [comment]
@jenPG09

So to confirm, this is the case?

|       | Home   | Office |
| ---------------- | ----- | ------ |
| Storage Explorer                 | Works      | Fails        |
| Azure Portal                     | Works      | Works        |

Can you confirm that:
- When you work from home/office, you are on the same computer?
- When you use Azure Portal/Storage Explorer, you are on the same computer?

I think there's a good chance the message "This storage account's 'Firewalls & virtual networks' settings may be blocking access to storage services" is correct. I can help you narrow down what is likely the culprit type of setting, but ultimately it will be up to you/the owner of your storage account/its firewall & vnet settings to go and fix this.

**Comment by jenPG09** [comment]
Hi @MRayermannMSFT 
Thank you so much for your response. Please find below my answers:

When you work from home/office, you are on the same computer? Yes, I'm using the same computer.
When you use Azure Portal/Storage Explorer, you are on the same computer? Yes, I'm using the same computer.

I'm the owner :) but I'm new in Azure :)

**Comment by MRayermannMSFT** [comment]
> When you work from home/office, you are on the same computer? Yes, I'm using the same computer.
> When you use Azure Portal/Storage Explorer, you are on the same computer? Yes, I'm using the same computer.

I was hoping that this would not be the answer. 🙈 Unfortunately I have no idea why Storage Explorer would work well on one network but not on another. I think the best bet for you now is to open an Azure support ticket where you can get help from folks who know more than I do: https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
