### ISSUE TITLE
Enable File Share OAuth

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#7775]

**Comment by yangchengs** [comment]
@JasonYeMSFT can you please confirm that we can target this to 1.36.0 and do you know what is the release date?

**Comment by cveld** [comment]
@JasonYeMSFT @yangchengs can you at least update the docs to state that oauth is not yet supported in the desktop app?

https://learn.microsoft.com/en-us/azure/storage/files/authorize-oauth-rest?tabs=portal#application-development-and-service-integration:
> DevOps tools such as the Azure portal, PowerShell, and CLI, AzCopy, and Storage Explorer can manage data using the user's identity, eliminating the need to manage or distribute storage access keys.
This is not true as the desktop app still requires key access. 

Oauth support in the desktop app is a highly demanded feature. Would be very cool to see it land!

**Comment by MRayermannMSFT** [comment]
> Would be very cool to see it land!

Just waiting for the files service to support it at the data plane API level. I believe we are very close. So far I have not seen anything which indicates 1.36 will not contain the capability. 🤞

**Comment by MRayermannMSFT** [comment]
Merged for inclusion in 1.36.0.
