### ISSUE TITLE
Storage Explorer connect error "ERR_SSL_KEY_USAGE_INCOMPATIBLE"

### ISSUE THREAD

**Issue by MarioHelbingDB** [microsoft/AzureStorageExplorer#7778]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.1

### Architecture

x64

### Platform

Windows

### Bug Description

I can't connect to my storage account with the following error:
ERR_SSL_KEY_USAGE_INCOMPATIBLE
I don't change my storage account and from one to a other day I can't connect.

### Steps to Reproduce

1. We checked the ASE certificates were not expired, we (re)installed the same on the Windows VM (including the ASE Blob certificate), and we confirmed that all entries were correct in the Windows hosts file (including each specific ASE blob storage).
2. Then, in Storage Explorer (version 1.32.1), we selected Edit -> Target Azure Stack APIs -> Restart the Storage Explorer.
3. We tried without explicitly importing the certificates in Storage Explorer, but also tried after importing the same there (in Edit -> SSL Certificates -> Import).
4. We Attached a resource -> Storage Account -> Account name and key -> We filled-in some display name, set the correct Account name (already created in ASE and having a container), and set the account key. The Storage Domain was set to ..
5. If we set the checkmark "use http" while connecting to the storage account we can establish the connection but if we use https then the error occurs.

### Actual Experience

I can't connect to my storage account.
We use Azure Stack Edge and I want connect to the storage account of the Azure Stack Edge.
we take steps 1-5 with https and we get this error:
ProducerError:{
"name": "Electron Net Error",
"message": "net::ERR_SSL_KEY_USAGE_INCOMPATIBLE",
"stack": "Error: net::ERR_SSL_KEY_USAGE_INCOMPATIBLE\n at SimpleURLLoaderWrapper. (node:electron/js2c/browser_init:2:50234)\n at SimpleURLLoaderWrapper.emit (node:events:513:28)",
"cause": {}
}

**Comment by craxal** [comment]
@MarioHelbingDB If you can connect to the storage account with HTTP, that seems to suggest there's something wrong with your certificates. They might not be expired, but it's possible something else has changed that could invalidate them. Where did you get your certificates from and how long ago?  Can you get new updated certificates and try those?

**Comment by MarioHelbingDB** [comment]
The certificates are still valid for over a year, but we still created a new one on the ASE, but the problem still exists even with the new certificate.

**Comment by craxal** [comment]
@MarioHelbingDB Which version of Windows are you on? If on Windows 11, do you know if this works on Windows 10?

Just so we can rule some things out, was this working at some point before? That is, was there a previous version of Storage Explorer that were able to connect to your storage account successfully?

Is there any more information about the certificate you can share? For example, do you know which TLS/SSL protocol version the certificate uses? Do you know anything about which cipher suite is used?

This article might help: https://learn.microsoft.com/en-us/windows/win32/secauthn/tls-cipher-suites-in-windows-11

**Comment by MarioHelbingDB** [comment]
We have installed Storage Explorer on a Windows 2019 server in our management network and have already tested several versions.
The certificate is created and renewed on the ASE via the interface. It is a certificate with an RSA 4096 key. I cannot say which TLS/SSL version and which cipher suite the Storage Explorer uses when establishing the connection.

**Comment by craxal** [comment]
@MarioHelbingDB 
> We have installed Storage Explorer on a Windows 2019 server in our management network and have already tested several versions.

I assume all the versions you tested have the same problem, then?

> The certificate is created and renewed on the ASE via the interface.

Do you mean you import certificates using Storage Explorer's **Edit > SSL Certificates > Import Certificates** menu? I'm still unclear about how you are getting or creating certificates. Storage Explorer does not create certificates. You can only import existing certificates.

> It is a certificate with an RSA 4096 key. I cannot say which TLS/SSL version and which cipher suite the Storage Explorer uses when establishing the connection.

Assuming the problem persists regardless of Storage Explorer version, it's possible the issue is related to the TLS version in use. Versions prior to 1.2 are deprecated, I believe, and Azure itself switched to 1.2 by default a year or two ago. You may need to look into whether your certificates can be updated to TLS 1.2 or higher or see if your system is configured to block certain versions.

**Comment by MarioHelbingDB** [comment]
we have started a Microsoft call TrackingID#2402140050001906
The result is summarized here, so we could solve our problem.

**Comment by MarioHelbingDB** [comment]
Thanks for having our remote session today.

As we’ve seen, changing between Storage Explorer’s system proxy setting to no proxy has not helped, so it was necessary to create a certificate in your Windows machine, to upload it to Stack Edge.
The procedure to generate a new certificate for ASE Blob as we did, can be found below:
1.	Open PowerShell as admin and generate a new certificate in local machine: [https://learn.microsoft.com/en-us/azure/databox-online/azure-stack-edge-gpu-create-certificates-powershell#create-signing-chain-certificate](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fdatabox-online%2Fazure-stack-edge-gpu-create-certificates-powershell%23create-signing-chain-certificate&data=05%7C02%7Cecs%40deutschebahn.com%7C66deabe1cf9a47e2878808dc3f827d6a%7Ca1a72d9c49e64f6d9af65aafa1183bfd%7C0%7C0%7C638455078103219153%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=1FXkqD4dQmwyP47la%2FmxLimxfUJtUs3bmi5UUfdVeCs%3D&reserved=0)
•	Note: For the purpose of accessing ASE Blob Storage, it's enough to create signing chain certificate and then only the Blob endpoint certificate.
•	Commands:
•	$AppName = "<ASE_Name>"
•	$domain = "<Domain>"
•	$cert = New-SelfSignedCertificate -Type Custom -KeySpec Signature -Subject "CN=RootCert" -HashAlgorithm sha256 -KeyLength 2048 -CertStoreLocation "Cert:\LocalMachine\My" -KeyUsageProperty Sign -KeyUsage CertSign
•	$gencert = New-SelfSignedCertificate -Type Custom -DnsName "*.blob.$AppName.$domain" -Subject "CN=*.blob.$AppName.$domain" -KeyExportPolicy Exportable  -HashAlgorithm sha256 -KeyLength 2048 -CertStoreLocation "Cert:\LocalMachine\My" -Signer $cert -KeySpec KeyExchange -TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.1")
2.	Export the certificates: [https://learn.microsoft.com/en-us/azure/databox-online/azure-stack-edge-gpu-prepare-certificates-device-upload#export-certificates-as-der-format](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fdatabox-online%2Fazure-stack-edge-gpu-prepare-certificates-device-upload%23export-certificates-as-der-format&data=05%7C02%7Cecs%40deutschebahn.com%7C66deabe1cf9a47e2878808dc3f827d6a%7Ca1a72d9c49e64f6d9af65aafa1183bfd%7C0%7C0%7C638455078103232198%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=punsYcAL0Mo0G%2BOAjZGL9nLIK4qtV9O8PROlTZu%2FrkU%3D&reserved=0)
•	Open/run "certlm" in PowerShell as admin and go to Personal -> Certificates -> Right click "RootCert" -> All Tasks -> Export -> Base-64 encoded X.509 (.CER).
•	Still in certlm go to Personal -> Certificates -> Right click "*.blob.<ASE>.<Domain>" -> All Tasks -> Export -> Yes, export the private key.
•	Tick " Include all certificates in certification path" + "Export all extended properties" + "Enable certificate privacy" -> Enter a password -> Export as pfx.
3.	Import the certificate to ASE: [https://learn.microsoft.com/en-us/azure/databox-online/azure-stack-edge-gpu-deploy-configure-certificates?pivots=single-node#bring-your-own-certificates](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fdatabox-online%2Fazure-stack-edge-gpu-deploy-configure-certificates%3Fpivots%3Dsingle-node%23bring-your-own-certificates&data=05%7C02%7Cecs%40deutschebahn.com%7C66deabe1cf9a47e2878808dc3f827d6a%7Ca1a72d9c49e64f6d9af65aafa1183bfd%7C0%7C0%7C638455078103241068%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=KCCXiLfvcU%2BJ9X5tdf3LfvTNaizGGQrQ5RPkDIb73Ms%3D&reserved=0)
•	Open ASE WebUI -> Certificates -> Add certificate -> Certificate type = Endpoints -> Blob Storage -> Select the generated pfx and enter the password utilized in 2.2) -> Validate & add.
4.	Install the signing chain certificate .cer (2.1) to your machine.
•	Double click on it (it was exported in step 2) -> Install certificate -> Local Machine -> Place in "Trusted Root Certification Authorities".
•	If needed, import the certificate in Storage Explorer as well, under Edit -> SSL Certificates -> Import Certificates.
5.	Open Storage Explorer and add the ASE Storage Account details as usual.
•	If it does not work when using "No proxy" setting, change it to "System proxy".

During our remote session, I’ve also mentioned that, in case you have problems connecting to the WebUI (also due to ERR_SSL_KEY_USAGE_INCOMPATIBLE), then you could either create a certificate for the WebUI (similarly as we did for the ASE Blob), or you could implement the following WA:
1)	For Edge and WebView2, set this key and entry in your Windows machine/VM (if some key does not exist, please create it):
-	Under: HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge
•	Create new DWORD entry named: RSAKeyUsageForLocalAnchorsEnabled ; Set the value to: 0x00000000 (0)
-	Under: HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\WebView2
•	Create a new DWORD entry named: RSAKeyUsageForLocalAnchorsEnabled ; Set the value to: 0x00000000 (0)
2)	For Chrome:
-	Under: HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome
•	Create new DWORD entry named: RSAKeyUsageForLocalAnchorsEnabled ; Set the value to: 0x00000000 (0)

As you have now been unblocked to use Storage Explorer to access ASE Blob Storage (via https), please let me know if I may proceed closing this case.
