### ISSUE TITLE
The strings on the search box overlap if resize the preview editor

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7779]
**Storage Explorer Version**: 1.33.0 (97)
**Build Number**: 20240225.5
**Branch**: rel/1.33.0
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.3(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test case
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one .txt file as block blob.
3. Preview the blob -> Focus on the preview editor.
4. Press 'Ctrl+F' -> Resize the preview panel.
5. Check the strings on the search box do not overlap.

## Expected Experience ##
The strings on the search box do not overlap.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/518f3c55-4808-4bc6-820d-8e3d7c85da93)

## Actual Experience ##
The strings on the search box overlap.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/ac153173-8f2c-43c4-8955-426ea7b3c8c0)

**Comment by craxal** [comment]
This is Monaco's search box and not ours, so is there anything really actionable on our side?

**Comment by MRayermannMSFT** [comment]
Ya, nothing we can do. We'll won't fix for today.
