### ISSUE TITLE
Storage Explorer is failing to authenticate and immediately crashes.

### ISSUE THREAD

**Issue by jjhornx** [microsoft/AzureStorageExplorer#7780]
Storage Explorer is failing to authenticate and immediately crashes.

"The authentication library used by Storage Explorer has failed to start properly. Please ensure you have .NET 6 or greater installed. If it is already installed then refer to the troubleshooting guide for help. Verbose authentication logging has been enabled.

Error:Hub Controller process exited prematurely with exit code 2147516563."

OS Name	Microsoft Windows 11 Enterprise Version 10.0.22631 Build 22631
version of Storage Explorer you're trying to use: v1.32.1

Whether you checked the prerequisites: Yes. .Net 8.0.2 

[logs.zip](https://github.com/microsoft/AzureStorageExplorer/files/14443591/logs.zip)

**Comment by jjhornx** [comment]
No, I tried downgrading the data explorer to 1.30 which included the .net installation. it didn't seem to work. I can try that too.

**Comment by jjhornx** [comment]
It didn't work. :(

**Comment by MRayermannMSFT** [comment]
Ah @jjhornx sorry about the confusion. The error message is definitely misleading if read a certain way. When it says ".NET 6 or greater" that means ".NET 6.0 or any version of .NET 6 greater than that". You cannot just have .NET 8 installed. Here's a link to the latest .NET 6 runtime installer for Windows x64:https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-6.0.27-windows-x64-installer

**Comment by jjhornx** [comment]
I did that

> Ah @jjhornx sorry about the confusion. The error message is definitely misleading if read a certain way. When it says ".NET 6 or greater" that means ".NET 6.0 or any version of .NET 6 greater than that". You cannot just have .NET 8 installed. Here's a link to the latest .NET 6 runtime installer for Windows x64:https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-6.0.27-windows-x64-installer

I did this already. Did not work.

**Comment by jjhornx** [comment]
> I did that
> 
> > Ah @jjhornx sorry about the confusion. The error message is definitely misleading if read a certain way. When it says ".NET 6 or greater" that means ".NET 6.0 or any version of .NET 6 greater than that". You cannot just have .NET 8 installed. Here's a link to the latest .NET 6 runtime installer for Windows x64:https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-6.0.27-windows-x64-installer
> 
> I did this already. Did not work.

![image](https://github.com/microsoft/AzureStorageExplorer/assets/78782123/bde45800-1309-4688-9bff-04faae387235)
