### ISSUE TITLE
The action 'Undelete Selected' is disabled when selecting more than one soft deleted blob snapshot

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7781]
**Storage Explorer Version**: 1.33.0 (97)
**Build Number**: 20240229.8
**Branch**: rel/1.33.0
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.3(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.31.2)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Create two snapshots for the blob -> Switch to the snapshots view.
4. Soft delete the two blob snapshots -> Switch to 'Active and soft deleted blobs' context view.
5. Select the two soft deleted blob snapshots -> Right click the selection.
6. Click 'Undelete'.
7. Check whether the action 'Undelete Selected' is enabled.

## Expected Experience ##
The action 'Undelete Selected' is enabled.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/f9bc86ba-2620-403b-b89b-ccfd79631d71)

## Actual Experience ##
The action 'Undelete Selected' is disabled.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/9362afba-f340-4ccc-ae53-073d448aa19e)

**Comment by JasonYeMSFT** [comment]
This is by design for non-HNS blobs. There is no way to undelete individual snapshot. Undeleting any deleted snapshot will undelete all the snapshots.
