### ISSUE TITLE
BLOBコンテナーの追加ができない

### ISSUE THREAD

**Issue by uto-yurina** [microsoft/AzureStorageExplorer#7782]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.1

### Architecture

i86

### Platform

Windows

### Bug Description

子リソースを取得できません。

ProducerError:{
  "name": "Node Fetch Error",
  "message": "connect ECONNREFUSED 127.0.0.1:11002",
  "stack": "Error: connect ECONNREFUSED 127.0.0.1:11002\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)",
  "cause": {
    "cause": {
      "errno": -4078,
      "code": "ECONNREFUSED",
      "syscall": "connect",
      "address": "127.0.0.1",
      "port": 11002
    }
  },
  "code": "ECONNREFUSED",
  "errno": -4078
}

### Steps to Reproduce

ストレージアカウント
→AzureStorageへ接続
→接続文字列を入力し、追加

・BLOBコンテナーの作成→以上の書いた通りのエラーが出る

### Actual Experience

![無題](https://github.com/microsoft/AzureStorageExplorer/assets/157099041/fc5e8f61-8787-4a11-ac9e-63db9aa1ebe9)

**Comment by JasonYeMSFT** [comment]
You are trying to connect to a local storage emulator. Have you started your local emulator? This is a common error code when the local storage emulator is not started.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. This issue will no longer be monitored. If you need further help, we recommend opening a support ticket via the Azure portal. Alternatively you can open a new issue here.
