### ISSUE TITLE
Storage Explorer gets deleted or uninstalled , if  the application is closed

### ISSUE THREAD

**Issue by sramesh-nlg** [microsoft/AzureStorageExplorer#7784]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.1

### Architecture

x64

### Storage Explorer Build Number

20231114.10

### Platform

Windows

### Bug Description

Storage explorer gets uninstalled every time it is closed or the system is rebooted

### Steps to Reproduce

1. Download the Azure Stroage explorer .exe of latest version
2. Run .exe file and install
3. Authenticate to Azure
4. Close the Application
5. when searching again , unable to find it.. even in the control panel, not listed in the list of apps as well

### Actual Experience

Everytime i want to use it, i am being to install it. but the application which was installed is not there.
not just reboot , even if the application is closed, unable to open it again

### Expected Experience

I want the installation to be persisted unless i uninstall the Application

**Comment by MRayermannMSFT** [comment]
@sramesh-nlg let's try the following steps:

1. Go to Windows settings > Apps/Installed Apps > search for Storage Explorer
2. If you find Storage Explorer in that list, click it/the "..." menu for it, choose "Uninstall", and follow all of the steps to uninstall
3. Launch the Registry Editor (search for "Registry Editor" in the start menu)
4. Navigate to `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{746B270C-5E45-41AA-BB5E-E81793FBD404}_is1`
5. If it exists, click it, and then on the right, look for a row called "UninstallString", and if found, double click it, copy the value data in the dialog that pops up, and paste it somewhere you can refer to later.
6. Repeat steps 4 & 5 for the location `Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{746B270C-5E45-41AA-BB5E-E81793FBD404}_is1`
7. Close Registry Editor
8. If you copied any uninstall string values, navigate to the location of the .exe the value refers to, and then double click to run the the uninstall .exe
9. After running either uninstaller, restart your computer
10. Re-download the Storage Explorer installer from https://www.storageexplorer.com
11. Run the installer, note if you install for all or current user, and note where you choose to install Storage Explorer
12. Launch Storage Explorer
13. Go to Windows settings > Apps/Installed Apps > search for Storage Explorer, and confirm that it shows up
14. Naviage to where you chose to install Storage Explorer and confirm there are files there
15. Close Storage Explorer
16. Try to launch by searching the start menu
17. If it doesn't show up, repeat steps 14 and 15, and additionally, if the files are still there, try to launch by double clicking on `StorageExplorer.exe`

Ultimately, please let us know the results of:
- Step 2 (was Storage Explorer in Windows settings and could you uinstall it?)
- Step 5 (was there a registry entry at `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{746B270C-5E45-41AA-BB5E-E81793FBD404}_is1`?)
- Step 6 (was there a registry entry at `Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{746B270C-5E45-41AA-BB5E-E81793FBD404}_is1`?)
- Step 13 (did you install for all users or current user, and where did you choose to install?)
- Step 14 (was Storage Explorer in Windows settings?)
- Step 14 (were there files there?)
- Step 16(could you find it in the start menu, and launch it?)
- Step 17(were the files still there, and did Storage Explorer launch after clicking on `StorageExplorer.exe`?)

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you still need help, we recommend opening a support ticket via the Azure Portal. This issue will no longer be monitored.
