### ISSUE TITLE
An error dialog pops up if expand 'File Shares' node when setting 'Disable Usage Of Keys' is checked

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7785]
**Storage Explorer Version**: 1.34.0-dev (98)
**Build Number**: 20240304.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.3(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Open 'Settings' -> Check the setting 'Disable Usage Of Keys'.
2. Restart Storage Explorer -> Expand one storage account -> File Shares.
3. Check whether no error dialog pops up.

## Expected Experience ##
No error dialog pops up.

## Actual Experience ##
An error dialog pops up.

Error message:
`  "message": "Unable to perform operation 'FileServiceClient.listSharesSegment'. No suitable credentials provided."`
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/07d38e64-d85b-4035-96d0-1d2c58cd9027)

## Additional Context ##
This issue does not reproduce when both settings 'Enable Files OAuth Support' and 'Disable Usage Of Keys' are checked.

**Comment by MRayermannMSFT** [comment]
@v-xianya this is by design. When the 'Enable Files OAuth Support' is disabled, if you only have SAS and/or Account Key credentials, then you will get an error like this. :)

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT thank you for the update.

If we check the setting 'Disable Usage Of Keys', we can expand Blob containers/Queues/Tables node. it only prompts an error info bar when trying to open one blob container/queue/table. while for file shares, it fails to list file shares. Could you help to tell why the different behaviors between file shares and other three services?

In addition, do we need to add 'File Share' into the description of setting 'Disable Usage Of Keys'?
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/0288ae13-3074-44cb-a1c0-d4ab151143e1)

**Comment by MRayermannMSFT** [comment]
> If we check the setting 'Disable Usage Of Keys', we can expand Blob containers/Queues/Tables node. it only prompts an error info bar when trying to open one blob container/queue/table. while for file shares, it fails to list file shares. Could you help to tell why the different behaviors between file shares and other three services?

Since File Share support for OAuth is currently not GA, we don't expose the existance of OAuth credentials to File Share related features. So if you disable the usage of keys, then File Share features will....oh...I see...now I understand your point!

> In addition, do we need to add 'File Share' into the description of setting 'Disable Usage Of Keys'? ![image](https://private-user-images.githubusercontent.com/41351993/309966263-0288ae13-3074-44cb-a1c0-d4ab151143e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NjYzNDAsIm5iZiI6MTcwOTY2NjA0MCwicGF0aCI6Ii80MTM1MTk5My8zMDk5NjYyNjMtMDI4OGFlMTMtMzA3NC00NGNiLWExYzAtZDRhYjE1MTE0M2UxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDE5MTQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MDVhNjg2NWQwMDY0MjRlN2NlY2VlZTJhMDU5ODNhYzM1MzMyZDY5NWUzNmFmMGU4OWU5NTY3ODM2ZTIwNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PZjbapYn2HCN6xzczq1wym7r4zkXA-RvOiLSO1RwJ7A)

Ok, yes, this is a very good point. :) Thank you. I will fix all of this so it all makes sense. :)

**Comment by MRayermannMSFT** [comment]
Ok, here's what I've done:

- Updated logic in file share service producer to only worry about respecting "disable usage of keys setting" if file share OAuth support is enabled.
- Updated description of the file share OAuth setting to mention that if enabled, then the "disable usage of keys setting" will be respected for file shares.

**Comment by v-xianya** [comment]
Thank you for the update! Verified this issue on the main build 20240305.7.
1. Now the setting 'Disable Usage Of Keys' will not affects file share if file share OAuth support is enabled.
2. The description of setting 'Enable Files OAuth Support' has been updated!
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/e479d0ff-29b2-4947-a60c-dcf6487166c6)
