### ISSUE TITLE
Fail to paste file shares between storage accounts which have assigned 'Storage File Data Privileged Contributor' role with 'Disable Usage Of Keys' checked

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7786]
**Storage Explorer Version:** 1.34.0 (98)
**Build Number:** 20240304.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.3(Apple M1 Pro)
**Architecture:** x64/x64/arm64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Open 'Settings' -> Check the setting 'Disable Usage Of Keys' -> Restart Storage Explorer.
2. Expand one storage account (Assign 'Storage File Data Privileged Contributor' role to it).
3. File Shares -> Right click one file share -> Click 'Copy File Share'.
4. Expand another storage account (Assign 'Storage File Data Privileged Contributor' role to it).
5. Right click File Shares node -> Click 'Paste File Share'.
6. Check whether succeeds to paste the file share.

## Expected Experience ##
Succeed to paste the file share.

## Actual Experience ##
Fail to paste the file share.

Error message:
`  "message": "Unable to perform operation 'FileShareClient.getProperties'. No suitable credentials provided."`
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/ceeaa8f4-52cf-4529-adef-4023a189af1e)

## Additional Context #
Nothing happens when clicking 'Retry' next to the failed activity log.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/b72352f0-9678-499e-a5fc-92d795e077a3)

**Comment by MRayermannMSFT** [comment]
Fixed. You can now copy & paste file shares even if you only have auth credentials.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240305.3. Fixed.
