### ISSUE TITLE
The action 'Copy' is disabled when the selection contains more than one item

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7787]
**Storage Explorer Version**: 1.34.0-dev (98)
**Build Number**: 20240304.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.3(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.33.0)

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Upload two files.
3. Select the two files.
4. Check whether the 'Copy' action is enabled.

## Expected Experience ##
The 'Copy' action is enabled.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/50b23b83-1252-493f-871d-1f25f75775ad)

## Actual Experience ##
The 'Copy' action is disabled.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/75ca20d6-bf6f-4c43-9781-a489a1102faa)

**Comment by MRayermannMSFT** [comment]
Fixed. Copy is back to being enabled even if multiple items are selected.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240305.3. Fixed.
