### ISSUE TITLE
The action 'Connect VM' is disabled for one file share when settings 'Enable Files OAuth Support' and 'Disable Usage Of Keys' are checked

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7788]
**Storage Explorer Version**: 1.34.0-dev (98)
**Build Number**: 20240304.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.3(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Check the settings 'Enable Files OAuth Support' and 'Disable Usage Of Keys'.
2. Restart Storage Explorer.
3. Create a storage account (Select eastus2 EUAP as its region) -> Then assign a role 'Storage File Data Privileged Contributor' to the storage account.
4. Expand the storage account -> File Shares.
5. Create a file share -> Observe its toolbar.
6. Check whether the action 'Connect VM' is enabled.

## Expected Experience ##
The action 'Connect VM' is enabled.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/fc23d9fa-78e7-4aeb-9d60-cb0b44db9025)

## Actual Experience ##
The action 'Connect VM' is disabled.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/d771a70a-e4f2-4f6d-9534-60f47491d8ae)

**Comment by MRayermannMSFT** [comment]
@v-xianya this is by design. To connect a VM to a file share you must have access to the account key, and 'Disable Usage Of Keys' is checked. :)

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT 



> @v-xianya this is by design. To connect a VM to a file share you must have access to the account key, and 'Disable Usage Of Keys' is checked. :)

In this scenario, to connect VM, why do we need to check the setting "Disable use of keys" if we have access to the account keys?
