### ISSUE TITLE
The log message shows an extra '.blob.' when attempting to copy blobs 

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#779]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181018.2
**Commit**: b246d18d
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Open one blob container which contains one blob at least.
2. Copy one blob to another blob container.
3. Check the log message after coping successfully.

#### Expected Experience: ####
There shows 'Copied 1 blob from [account_name]/[blob container_name] to ....'

#### Actual Experience: ####
There shows 'Copied 1 blob from [account_name]**.blob.**/[blob container_name] to ....'
![log](https://user-images.githubusercontent.com/34729022/47212655-66b8a980-d3cb-11e8-8be0-cdb5f4ee6188.png)

#### More info: ####
This issue also reproduces when coping files/directories.

**Comment by v-xianya** [comment]
Verified on build 20190603.4. This issue also reproduces when renaming one blob container.
![image](https://user-images.githubusercontent.com/41351993/58857512-0c5d2680-86d8-11e9-9eca-4f9174cda693.png)

**Comment by v-xianya** [comment]
This issue doesn't reproduce on the build master/20190916.5. So we close it.
