### ISSUE TITLE
Miss the action 'View Share Snapshots' on the toolbar of one file share when settings 'Enable Files OAuth Support' and 'Disable Usage Of Keys' are checked

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7790]
**Storage Explorer Version**: 1.34.0-dev (98)
**Build Number**: 20240304.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.3(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Check the settings 'settings 'Enable Files OAuth Support' and 'Disable Usage Of Keys'.
2. Restart Storage Explorer.
3. Create a storage account (Select eastus2 EUAP as its region) -> Then assign a role 'Storage File Data Privileged Contributor' to the storage account.
4. Expand the storage account -> File Shares.
5. Create a file share -> Observe its toolbar.
6. Check whether there is an action 'View Share Snapshots'.

## Expected Experience ##
There is an action 'View Share Snapshots'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/8776fe80-657a-460a-9d6f-a63523e7777d)

## Actual Experience ##
There is no action 'View Share Snapshots'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/fb5c3f00-2803-48e3-a66d-4ed3e93080f3)

## Additional Context ##
This issue also reproduces when switching to 'read-only snapshots' context view.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/8b3307f2-bbcb-4b4d-bc61-21f8fb8ec363)

**Comment by MRayermannMSFT** [comment]
Fixed. The button now shows up if only auth credentials exist.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240305.3. Fixed.
