### ISSUE TITLE
French localization of visual themes is incorrect

### ISSUE THREAD

**Issue by bastienmosnier-bib** [microsoft/AzureStorageExplorer#7791]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.1

### Architecture

x64

### Storage Explorer Build Number

20231114.10

### Platform

Windows

### OS Version

Windows 11

### Bug Description

In french localization, in the menu View --> Theme, the setting "System Default" has been translated to "Défaillance du système", which means "System failure"

### Steps to Reproduce

Go to Settings --> Regional Settings --> Language (Preview)
Set to "Français"
Go to Afichage --> Thème

### Actual Experience

The label for the System default theme says "Défaillance du système" which means "Systeme failure". 

### Expected Experience

It should say something like "Paramètres système"

**Comment by JasonYeMSFT** [comment]
I made a request to our localization team to fix the translation.

**Comment by JasonYeMSFT** [comment]
The string has been fixed in main.
