### ISSUE TITLE
There is no 'Preview' action on the toolbar of one file share under read-only snapshot context view

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7794]
**Storage Explorer Version**: 1.34.0-dev (98)
**Build Number**: 20240305.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.3(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: Ad-hoc testing
**Regression From**: Previous release (1.33.0)

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Upload one file.
3. Create a snapshot for the file share -> Switch to read-only snapshot context view.
4. Check whether there is a 'Preview' action on the toolbar.

## Expected Experience ##
There is a 'Preview' action on the toolbar.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/f9711fa8-eb86-48ee-869e-6b29b2602671)

## Actual Experience ##
There is no 'Preview' action on the toolbar.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/d3934117-9a96-4b69-9fe0-90899587a28d)

**Comment by MRayermannMSFT** [comment]
Fixed.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240305.7. Fixed.
