### ISSUE TITLE
Succeed to delete file share snapshots if the storage account has 'Storage File Data Privileged Reader' role with 'Disable Usage Of Keys' checked

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7795]
**Storage Explorer Version:** 1.34.0-dev (98)
**Build Number:** 20240305.3
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.3(Apple M1 Pro)
**Architecture:** x64/x64/x64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Launch Storage Explorer -> Check the settings 'Enable Files OAuth Support' and 'Disable Usage Of Keys'.
2. Restart Storage Explorer.
3. Expand one storage account which has assigned a role 'Storage File Data Privileged Reader' -> File Shares.
4. Right click one file share -> Click 'Create Snapshot'.
5. Click 'View Share Snapshots' -> Try to delete the snapshot.
6. Check whether fails to delete the snapshot.

## Expected Experience ##
Fail to delete the snapshot.

## Actual Experience ##
Succeed to delete the snapshot.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/1e2eb5c3-085b-4352-85be-1f8e98bc4654)

**Comment by MRayermannMSFT** [comment]
@v-kellyluo can y'all double check your access on the storage account you repro this with? When I try to repro I get this error, which I expect:

<img width="715" alt="image" src="https://github.com/microsoft/AzureStorageExplorer/assets/21112697/8e201476-5b8b-4006-b582-0dd9414cad11">

For refrerence, these are the roles I have on the account I tested with:

<img width="1073" alt="image" src="https://github.com/microsoft/AzureStorageExplorer/assets/21112697/ebdb8d4e-ca2e-41d7-9706-4ca75f76b11d">

**Comment by v-kellyluo** [comment]
Hi @MRayermannMSFT,

After checking 'Enable Files OAuth Support' and 'Disable Usage Of Keys' settings, I only signed in one account, then assigned the 'Storage File Data Privileged Reader' role to the signed in account, it succeeds to delete the snapshots, could you help to take a look?

**Comment by MRayermannMSFT** [comment]
@v-kellyluo , the owner role will be problematic. It gives you permissions to do literally anything.

**Comment by v-kellyluo** [comment]
Hi @MRayermannMSFT , 

1. We only can delete snapshots successfully, we cannot execute 'Upload/Delete/Rename/Move' actions, please see the screenshot:

![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/45b9f738-9ba9-4459-9ab7-dfbbc150cea2)

2. And for blob containers, if we only signed in one account, and assigned 'Storage Blob Data Reader' role to the signed in account, it fails to execute other actions except 'Read', Should it be consistent?

**Comment by MRayermannMSFT** [comment]
@v-kellyluo this is by design. The owner role gives you permissions to create & delete both file share and their snapshots.
