### ISSUE TITLE
The action 'Move' is disabled when the selection contains more than one item for one file share

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7797]
**Storage Explorer Version**: 1.34.0-dev (98)
**Build Number**: 20240305.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.3(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: Ad-hoc testing
**Regression From**: Previous release (1.33.0)

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Upload two files.
3. Select the two files -> Right click the selection.
4. Check whether the action 'Move...' is enabled.

## Expected Experience ##
The action 'Move...' is enabled.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/4d75e030-ca53-4e15-8bad-dbb420d4c20a)

## Actual Experience ##
The action 'Move...' is disabled.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/fc2cc6d6-15f1-430a-8afd-d2e85064fe48)

**Comment by MRayermannMSFT** [comment]
Fixed.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240305.7. Fixed.
