### ISSUE TITLE
The storage account name shows instead of full path when hovering over one view all containers tab

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7799]
**Storage Explorer Version:** 1.34.0-dev (98)
**Build Number:** 20240305.7
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.3(Apple M1 Pro)
**Architecture:** x64/x64/arm64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account.
2. Right click 'Blob Containers' node -> Click 'View All'.
3. Hover over the opened tab.
4. Check whether a full path shows.

## Expected Experience ##
A full path shows.

## Actual Experience ##
Only show the storage account name.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/50321c5a-be8d-4d91-a2e4-a7dbc146a246)

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240320.3. Fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/dd1c2942-2fee-4d73-9326-9299199a7010)
