### ISSUE TITLE
Focus is not visible for 'Edit/Delete' buttons using Tab in 'Edit Entity' dialog under HC-modes

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#78]
**Storage Explorer Version:** 20180424.5(1.0.0)

**OS Version:** Win10/Mac/Linux

**Regression**: Previous release 1.0.0

**Steps to Reproduce:**

1. Launch Storage Explorer and expand Storage Accounts.
2. Change the current theme to HC-Dark/Light.
3. Open one table and edit any of entity.
4. Focus on the 'Edit' or 'Delete' button using Tab and check whether it is visible or not.

**Expected Experience:**
It is visible.

**Actual Experience:**
It is not visible.
![visible](https://user-images.githubusercontent.com/34729022/39234286-53f7df54-4862-11e8-810f-23b8f8e023c7.png)

**More info:**
This issue also reproduces when tabbing the property Type.

**Comment by MRayermannMSFT** [comment]
Merged into master.
