### ISSUE TITLE
Subscription connection issue

### ISSUE THREAD

**Issue by sohail-ali** [microsoft/AzureStorageExplorer#780]
Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: 19e76119-5881-4f06-ab72-67c63f0df2ed, Error: {"code":"SELF_SIGNED_CERT_IN_CHAIN"}

**Comment by MRayermannMSFT** [comment]
@sohail-ali please see our troubleshooting guide for self signed certs: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C1804#error-self-signed-certificate-in-certificate-chain-and-similar-errors

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
