### ISSUE TITLE
The cursor disappears if click the size input in the 'Column Options' dialog

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7803]
**Storage Explorer Version:** 1.34.0-dev (98)
**Build Number:** 20240306.5
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.3(Apple M1 Pro)
**Architecture:** x64/x64/x64
**How Found:** Ad-hoc testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create a table -> Click 'Customize Columns'.
3. Click the size input.
4. Check where the cursor appears.

## Expected Experience ##
The cursor appears.

## Actual Experience ##
The cursor disappears.

## Additional Context ##
This issue can be resolved if select all text in the size input.
Here is the record:
![disa](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/c46958e0-be98-4e70-b23a-c48667f051b1)

**Comment by brunis** [comment]
How do I upvote this.. it's super annoying :(

**Comment by craxal** [comment]
@brunis Click the happy face under the comment then select an appropriate response. :smile:

<img width="471" alt="image" src="https://github.com/microsoft/AzureStorageExplorer/assets/3473026/7134deff-d224-4d2d-a2e2-14d833624ccf">

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240416.1. Fixed. So, we are going to close it.
