### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by hstoyanova** [microsoft/AzureStorageExplorer#7804]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.30.0

### Architecture

x64

### Storage Explorer Build Number

20230609.2

### Platform

Windows

### OS Version

Windows 11

### Bug Description

Unable to retrieve child resources

ProducerError:{
  "name": "FetchError",
  "message": "request to https://saragrseuntcccnsremeat03.blob.core.windows.net/?comp=list&include=metadata failed, reason: self signed certificate in certificate chain",
  "stack": "FetchError: request to https://saragrseuntcccnsremeat03.blob.core.windows.net/?comp=list&include=metadata failed, reason: self signed certificate in certificate chain\n    at ClientRequest.<anonymous> (C:\\Users\\O48121\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\blob-extension\\dist\\src\\index.js:2:2834516)\n    at ClientRequest.emit (node:events:513:28)\n    at TLSSocket.socketErrorListener (node:_http_client:502:9)\n    at TLSSocket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
  "type": "system",
  "errno": "SELF_SIGNED_CERT_IN_CHAIN",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}

### Steps to Reproduce

1. Launch Storage explorer
2. Expand 'Blob containers' for given storage
3. The error message described in previous step is received.

### Actual Experience

Additionally I am not able to authenticate. I see following error messages:
Could not access resources for this tenant. You may need to reauthenticate. See the error details for more information:
{
  "name": null,
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"self signed certificate in certificate chain\\\",\\n  \\\"stack\\\": \\\"Error: self signed certificate in certificate chain\\\\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1540:34)\\\\n    at TLSSocket.emit (node:events:513:28)\\\\n    at TLSSocket._finishInit (node:_tls_wrap:959:8)\\\\n    at ssl.onhandshakedone (node:_tls_wrap:743:12)\\\",\\n  \\\"code\\\": \\\"SELF_SIGNED_CERT_IN_CHAIN\\\"\\n}\""
}

**Comment by MRayermannMSFT** [comment]
@hstoyanova can you give using system proxy setting a try? You can read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. If you still have this issue, please open a new one with the additional information we requested.
