### ISSUE TITLE
storage explorer not able to create or view the blob container

### ISSUE THREAD

**Issue by cavulamanda** [microsoft/AzureStorageExplorer#7808]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.33.0

### Regression From

na

### Architecture

i86

### Storage Explorer Build Number

20240301.4

### Platform

Windows

### OS Version

windows 10

### Bug Description

Hi, 
I am not able to access blob container from the storage explorer or browser. I have added my IP to the firewall as below:
![image](https://github.com/microsoft/AzureStorageExplorer/assets/43422737/68d83c2d-2870-4dfb-a34b-f96984809413)

Please can someone advise how can I enable my local access to storage account.

Thanks
Kumar

### Steps to Reproduce

na

### Actual Experience

NA

### Expected Experience

should be able to access and create blob container from storage explorer with selected virtual networks and IP addresses setting enabled

### Additional Context

na

**Comment by MRayermannMSFT** [comment]
@cavulamanda if you're still seeing a 403 error in Storage Explorer and you are confident your vNet/firewall settings are correct, we recommend opening an Azure support ticket to get more help: https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. If you still have issue, please create a new one with the additional information we requested.
