### ISSUE TITLE
Cannot delete files from Azure storage explorer

### ISSUE THREAD

**Issue by bokbob** [microsoft/AzureStorageExplorer#7809]
Hi, we have some ADLS blob container and folders within it and I need to clear the blobs occasionally when the job fails to pick them up or clear them. 

When I try to delete a blob from Azure storage explorer it is not letting me do that. If I do that from Azure portal it does let me delete it but there are 4000 files to delete and its not feasible from UI. Please let me know how to achieve this.

**Comment by bokbob** [comment]
HI, By selecting the file and hitting on delete button wont delete a file.

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. If you still have issue, please open a new one with the additional information requested.
