### ISSUE TITLE
Slow download speed compared to AzCopy

### ISSUE THREAD

**Issue by sebastinovich** [microsoft/AzureStorageExplorer#781]
**Storage Explorer Version**: 1.4.4
**Platform/OS Version**: Windows
**Architecture**: ia32
**Regression From**: 

#### Steps to Reproduce: ####
1. Download a 1GB file from a blob storage.

#### Expected Experience: ####
I would like the download speed to be the same as AzCopy. Is there any reason why it is far slower than AzCopy?

#### Actual Experience: ####
Actually, it takes around 40 seconds to download a 1GB file, so roughly 25MB/sec, while with AzCopy, we are slightly exceeding 60MB/sec.

**Comment by MRayermannMSFT** [comment]
Hi @sebastinovich , in the latest version of Storage Explorer, we are now using AzCopy to do uploads and downloads, so I think your issue is fixed/I'm going to go ahead and close it. If you're still having issues with transfer speeds, please open a new issue. Thanks!
