### ISSUE TITLE
Untergeordnete Ressourcen können nicht abgerufen werden

### ISSUE THREAD

**Issue by BeiseF** [microsoft/AzureStorageExplorer#7810]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.33.0(97)

### Architecture

i86

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Untergeordnete Ressourcen können nicht abgerufen werden

ProducerError:{
  "name": "Node Fetch Error",
  "message": "{\"name\":\"Node Fetch Error\",\"cause\":{\"cause\":{\"name\":\"ConnectTimeoutError\",\"code\":\"UND_ERR_CONNECT_TIMEOUT\",\"message\":\"Connect Timeout Error\"}},\"code\":\"UND_ERR_CONNECT_TIMEOUT\"}"
}

### Steps to Reproduce

Launch Storage app

### Actual Experience

can't open files with app, in explorer mode it works

**Comment by MRayermannMSFT** [comment]
@BeiseF can you give using system proxy setting a try? You can read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. If you still have issue, please open a new one with the additional information requested.
