### ISSUE TITLE
The 'Import Messages' dialog is not localized completely

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7813]
**Storage Explorer Version:** 1.34.0-dev (98)
**Build Number:** 20240308.12
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.4 (M1 Pro)
**Reproduce Languages:** All languages
**Architecture:** x64/x64/arm64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select 'Français' -> Restart Storage Explorer.
3. Expand one storage account -> Queues.
4. Create a queue -> Click 'Import'.
5. Check whether the 'Import Messages' dialog is localized completely.

## Expected Experience ##
The 'Import Messages' dialog is localized completely.

## Actual Experience ##
The 'Import Messages' dialog is not localized completely.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/f9a29b3e-d67d-4718-b390-e5bf0dbc5a7a)

## Additional Context ##
The error message is also not localized if empty the 'Delimiter' field.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/055c5b5c-c6ce-4362-bcdc-694185be1896)

**Comment by craxal** [comment]
@v-kellyluo Translations have not yet been provided.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240506.3, it still reproduces, so we are going to re-open it.
1. On Czech/French/Hungarian/Italian/Japanese/Korean/Polish/Portuguese (Brazil)/Portuguese (Portugal)/Swedish, only the string 'Import files' is not localized.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/5b50abed-58d8-49ba-8bd0-4de77afd4dd8)
2. On German/Spanish/Dutch/Russian/Turkish/zh-CN/zh-TW, the dialog is not localized completely.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/f43d510d-01fe-446e-9fa5-6f5f5e376bf2)

**Comment by craxal** [comment]
I guess translators aren't done yet. Moving this to Localization milestone.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20241021.1. Fixed. So, we are going to close it.
![Image](https://github.com/user-attachments/assets/54d6487c-7deb-4f4d-b2db-d94465f899ed)
