### ISSUE TITLE
Run CTI test pass for Windows ARM64 Build

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#7816]
- Run a full test pass after completion of this issue: https://github.com/microsoft/AzureStorageExplorer/issues/7815 . Make sure expectations about installer behavior are well communicated to CTI.
- As issues come in, either assign to @MRayermannMSFT to fix, or other devs to fix, either on local dev machine (if possible) or on Windows ARM64 VMs (https://learn.microsoft.com/en-us/windows/arm/create-arm-vm)

Related to: https://github.com/microsoft/AzureStorageExplorer/issues/6072

**Comment by craxal** [comment]
Test pass verifies installers work as intended.
