### ISSUE TITLE
Need to be able to select rows WITH HEADERS  on preview view of parquets, deltas etc. 

### ISSUE THREAD

**Issue by Alonlon79** [microsoft/AzureStorageExplorer#7818]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

unable to select-and-copy rows with headers in preview (just rows are avaliable)

### Desired Solution

add "copy rows with headers" option when right clicking on a selection in previewed table

### Alternatives and Workarounds

alternatively, add ability to filter columns (not just sort) in preview and add export options to csv/xlsx etc.

**Comment by MRayermannMSFT** [comment]
We'll attempt to address this in 1.35.0. When we do let's make sure we also look at this capability not only in the tabular preview panel, but also in the table explorer panel. Maybe we need to make enhancements into the data we copy onto clipboard (more structured format or something?).

**Comment by craxal** [comment]
Currently, we put two separate formats onto the clipboard when copying table data: tab-delimited text and HTML.

I'm hesitant to clutter up the context menu with yet another copy command. On further examination, I see no reason to just include the header information when copying rows. If the headers are not wanted, they can easily be removed in editor scenarios (delete the first line of text in text editors or remove the first row in word processors).

@Alonlon79 Would this be sufficient for your needs?

**Comment by Alonlon79** [comment]
Hey, yes thank you. I rarely have a scenario where I need the rows without headers so replacing current option with the “with headers” option would be better for me.

Best regards,
Alon Levy
________________________________
