### ISSUE TITLE
Premium Blob Storage regression

### ISSUE THREAD

**Issue by clausjor** [microsoft/AzureStorageExplorer#782]
**Storage Explorer Version**: 1.4.4 
**Platform/OS Version**: Windows 10 1803
**Architecture**: ia32
**Regression From**: 1.4.3

#### Steps to Reproduce: ####
1. Click to expand an Azure Premium Blob Storage account does not reveal 'Blob Containers'
2. Right-click an Azure Premium Blob Storage account, select get 'SAS Signature', click create. This fails with 'Error when calling Azure Storage: {}' 

#### Expected Experience: ####
1. Expanding a premium blob storage account should reveal the default 'Blob containers' leaf.
2. Creating a SAS token should succeed.  

#### Actual Experience: ####
Described above.

**Comment by MRayermannMSFT** [comment]
@clausjor are you still encountering this issue in the latest version of Storage Explorer (1.12.0)?

**Comment by clausjor** [comment]
This issue has been resolved. Thank you.
