### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by smendigoria** [microsoft/AzureStorageExplorer#7822]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.33

### Architecture

x64

### Platform

Windows

### OS Version

Windows 21H@

### Bug Description

I'm getting this error when connecting to the storage account:

Unable to retrieve child resources

ProducerError:{
  "name": "Node Fetch Error",
  "message": "{\"name\":\"Node Fetch Error\",\"cause\":{\"cause\":{\"code\":\"ECONNRESET\",\"host\":\"test123.blob.core.windows.net\",\"port\":443,\"localAddress\":null}},\"code\":\"ECONNRESET\"}"
}

The storage account is using private endpoint and tested that there is a connectivity between my machine and the storage explorer, DNS resolves also.

This is the debug info of the Storage explorer:

[2024-03-18T06:19:16.538Z] (blob-extension:14748) <ERRO> HttpClient threw while making API call for BlobServiceClient.getProperties
  GET https://test123.blob.core.windows.net/?restype=service&comp=properties
  Credential used: Account name and key - account name: test123, account key: ******, keyName: key1
  RequestId: 816756a3-1b09-40b2-ba61-fe3f5f925f15, Date sent: Mon, 18 Mar 2024 06:19:16 GMT, ApiVersion: 2023-01-03, ProxySettings: undefined
  Error: {"name":"Node Fetch Error","cause":{"cause":{"code":"ECONNRESET","host":"test123.blob.core.windows.net","port":443,"localAddress":null}},"code":"ECONNRESET","message":"Client network socket disconnected before secure TLS connection was established"}

### Steps to Reproduce

1. Connect using Azure storage explorer

### Actual Experience

Cannot connect to the storage account.

The DNS resolves and tested that there is connectivity between the VM and the storage private endpoint IP.

**Comment by MRayermannMSFT** [comment]
@smendigoria can you give using system proxy setting a try? You can read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by MelGrubb** [comment]
I see this consistently on every start-up of the application these days. What does "give using system proxy setting a try" even mean. Mine is set to "Auto". Is that somehow wrong? If so, then isn't that a bug? If I turn off auto-mode, then what would I even set things to? Is this like a web proxy? You're going to need a better explanation than "have you tried messing with these 7 settings?" with no further details.

**Comment by JasonYeMSFT** [comment]
@MelGrubb Setting the proxy setting in Storage Explorer tells Storage Explorer where to grab the proxy information to use. If Storage Explorer is configured to "use system proxy", it will use the system's proxy setting no matter what it is. If you set the system's proxy to "Auto", then it will use the auto detected proxy server by the system. If you manually configured a proxy server in the system, then it will use that proxy server.

If Storage Explorer is set to use the system proxy and you still see these network errors, there is a chance that the proxy server is not configured correctly at the system level.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response from original issue author. For more help, we recommend opening an Azure support ticket via the portal.

**Comment by MelGrubb** [comment]
I'll just follow up here anyway. I have no proxy server. Not at the office, and not at home.
