### ISSUE TITLE
It is hard to see the black part of one .glb file content when previewing it under 'Dark/High Contrast - Black' theme

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7824]
**Storage Explorer Version**: 1.34.0-dev (98)
**Build Number**: 20240316.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.4(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch storage explorer -> Make sure it is under 'Light' theme.
2. Expand one storage account -> File Shares.
3. Open one file share -> Upload one .glb file that contains black part when it's being previewed.
4. Select the file -> Click 'Preview' -> Change the theme to dark.
5. Check whether it is clear to see the content.

## Expected Experience ##
It is clear to see the content.

The screenshot under 'Light' theme.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/fcb38338-fc8b-4d23-94a5-e62a1d87b53d)

## Actual Experience ##
It is hard to see the content.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/f667923d-5481-4336-96b4-0d6b8f6cfc87)

**Comment by richardMSFT** [comment]
After review, our conclusion is that if when previewing a 3D model it is hard to see in a certain theme the user can decide to switch to a theme where the background makes it easier to view.

**Comment by v-xianya** [comment]
We are going to close this issue because it is marked won't fix.
