### ISSUE TITLE
Blob metadata not showing up with correct casing in blob properties

### ISSUE THREAD

**Issue by KSib** [microsoft/AzureStorageExplorer#7825]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.33.0

### Architecture

x64

### Storage Explorer Build Number

20240301.4

### Platform

All

### OS Version

Windows 11

### Bug Description

The storage explorer should show the casing that's actually stored or associated with the blob. I ran into a weird issue where I was attempting to double-store metadata (with different casing) and then ran into some forbidden API error.

![image](https://github.com/microsoft/AzureStorageExplorer/assets/1589238/7e4fa252-469d-4493-9708-a370293a292c)
![image](https://github.com/microsoft/AzureStorageExplorer/assets/1589238/58de02ad-6e8a-4329-a50a-ad3074387009)

### Steps to Reproduce

- Using the latest C# Azure.Storage.Blobs NuGet package, upload a new blob with metadata with a capital letter in it
- Using Azure Storage Explorer, nagivate to the blob and notice that the capital letter isn't there
- Using Azure.Storage.Blobs, fetch the metadata for the blob and see that it's actually stored there, but not showing up that way in Azure Storage Explorer

### Actual Experience

The storage explorer should show the casing that's actually stored or associated with the blob. I ran into a weird issue where I was attempting to double-store metadata (with different casing) and then ran into some forbidden API error.

![image](https://github.com/microsoft/AzureStorageExplorer/assets/1589238/7e4fa252-469d-4493-9708-a370293a292c)
![image](https://github.com/microsoft/AzureStorageExplorer/assets/1589238/58de02ad-6e8a-4329-a50a-ad3074387009)

### Expected Experience

Azure storage explorer should show metadata as its stored.

**Comment by MRayermannMSFT** [comment]
@KSib I can look into this, as ideally the casing is respected, however, please please please do not write code with assumes blob metadata casing is preserved. There is no such guarantee. Since blob metadata are implemented as HTTP headers, they should be treated case insensitively.

**Comment by MRayermannMSFT** [comment]
Ya it looks like something in the Azure SDKs regressed quite a while back. Though I can't even seem to find what exactly changed. Thankfully it looks like we can do a little something to work around that. Hopefully that doesn't break in the future though! ✊🪵
