### ISSUE TITLE
Azure Storage Explorer not showing any storage accounts and stuck in "loading"

### ISSUE THREAD

**Issue by Ragzz1995** [microsoft/AzureStorageExplorer#7826]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.33.0

### Regression From

NA

### Architecture

x64

### Storage Explorer Build Number

20240301.4

### Platform

All

### OS Version

Windows 10

### Bug Description

Hi,

My Azure storage explorer is stuck on "Loading" after logging into my subscription. I've tried resetting and reinstalling but it doesn't seem to work. Attached image for reference. I know for sure I have the required RBAC accesses as I can verify the same through Azure portal

![image](https://github.com/microsoft/AzureStorageExplorer/assets/16513966/119f9fa3-ad54-4635-adc0-538fc499677c)

### Steps to Reproduce

1. Launch Storage Explorer
2. Login to subscription
3. Try opening a "Subscription" tree

### Actual Experience

My Azure storage explorer is stuck on "Loading" after logging into my subscription. I've tried resetting and reinstalling but it doesn't seem to work. Attached image for reference.

### Expected Experience

To view my storage accounts

**Comment by craxal** [comment]
@Ragzz1995 Are you attempting to connect through a proxy? If so, have you configured Storage Explorer to use the system proxy (or use custom proxy settings)? Have you imported any certificates that your network requires?

Are you able to connect to a local emulator? Determining this can help narrow down where issues may be occurring.

Also, if you can, please share your app logs. They can be located by selecting **Help > Open Logs Directory** from the menu.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. This issue will no longer be monitoried. If you still require help, we recommend opening an Azure support ticket via the portal, or you can open a new issue here.
