### ISSUE TITLE
The new filtering functionality is confusing

### ISSUE THREAD

**Issue by jeffpapp** [microsoft/AzureStorageExplorer#7829]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.33.0

### Architecture

x64

### Storage Explorer Build Number

20240301.4

### Platform

Windows

### OS Version

Windows 11

### Bug Description

The new way to filter by a prefix is confusing.  Before you could just type your filter into the giant text box at the top of the window and you could search.

Now you have to click the filter button, then type your search term into a text box there and then it shows up as a chip in the main text box with a description on what your filtering.

I kept trying to type in the big search box and all that seemed to do was try to add a directory layer to my view.

### Steps to Reproduce

1. Launch storage explorer
2. Open a blob container view
3. Type something in what looks like a giant search box

### Actual Experience

When I type in the giant search box it seems like it's just adding whatever I typed as a directory and then shows no results.  This made me think that what I was searching for didn't exist.  

### Expected Experience

Either make it clear that the giant search box is just a directory selector now, or add another way to be able to filter for a file quickly without having to pop open the filter panel

**Comment by MRayermannMSFT** [comment]
@jeffpapp as far as I'm aware, filter by prefix has always been in a separate search box, even before the introduction of the view options panel. For example, here's 1.14.2 where there is a search box:
![image](https://github.com/microsoft/AzureStorageExplorer/assets/21112697/d6d8ced8-93b8-46b8-8f65-7e85732ccf5d)

The big text box, which we refer to as the address bar, has never supported prex filtering. It only supports inserting a known folder path. 

That all said, if you do find yourself using filter by prefix a lot, and you'd like to not have to remember to pop our the view options panel, there's a setting you can use to make it appear by default. That can be found at Settings (gear on the left) > Data Explorers > Blob Explorer > Show View Options By Default.

**Comment by jeffpapp** [comment]
@MRayermannMSFT, you're probably right on the prefix filter being it's own box.

I think what I'm remembering is being able to put an exact filename in the address bar and getting a result.  That not does not seem to work now, whatever I put in the address bar gets translated to a folder path.  Now it seems like the only way to find an exact file is through the prefix filter.

**Comment by MRayermannMSFT** [comment]
> put an exact filename in the address bar and getting a result

@jeffpapp hmmmm I've tried a couple of older versions to see if that was ever the case , but so far I can't find one. I've tried:
- 1.14.2 - address bar is not editable
- 1.15.1 - first version with editable address bar, no results after entering name of file in address bar
- 1.16.0 - no results after entering name of file in address bar
- 1.20.1 - no results after entering name of file in address bar

I'm pretty sure if that was ever a behavior, that would have been a bug, at least according to us.

In general, we intend for the UI/UX of the data explorers to be as follows. The address bar controls what "location" you are currently look at. For things like blob containers and file shares, that means what folder/directory. For trying to find a file, that should be something handled by a search box. Does that help resolve the confusion indicated in your original post? And does the setting I talked about earlier (Settings (gear on the left) > Data Explorers > Blob Explorer > Show View Options By Default) help give you a faster way to get to the search box for blobs?

**Comment by jeffpapp** [comment]
Maybe I'm going crazy, but I feel like I've gone in hundreds of time and pasted a file name in there and hit enter and had it find the file I was looking for.  Maybe I was using the second prefix search box in your screen shot above.

The `Show View Options By Default` works ok, but it still takes up extra screen real estate to be popped open all the time.  I'd much rather have the extra search box next to the address bar.

If the address bar is only for showing folder/directory locations I'd wish it was a little more clear on that.  Even looking at Windows you get This PC > Disk Name > Folder > Folder, then when you click on the address bar to edit you get the full path as you're typing.  It seems confusing when you click into the address bar that the container name goes away and you are typing in an empty box.  Also, if you do type in a folder that doesn't exist, maybe it would be helpful if it didn't just give you an empty grid, even in Windows you get an error that says folder doesn't exist.  Having a different message between a folder that doesn't exist and a search that didn't find any results might have cleared things up for me as well.

I would say it's also a bit confusing that when you do a prefix filter, it shows your search in the address bar (filtering 'xxx' by prefix 'yyyy') but then you can click on that and type anything it's only editing the folder you are searching in.  It just seems strange the filter is displayed there but not editable.

**Comment by MRayermannMSFT** [comment]
> The Show View Options By Default works ok, but it still takes up extra screen real estate to be popped open all the time. I'd much rather have the extra search box next to the address bar.

This is fair feedback. For now, I think we're still convinced that, for non-gen2 blobs, having the search box co-located with other filtering-esque controls makes sense, but we get that ultimately prefix filter is way more popular of a control than the others in the panel.

> If the address bar is only for showing folder/directory locations I'd wish it was a little more clear on that. Even looking at Windows you get This PC > Disk Name > Folder > Folder, then when you click on the address bar to edit you get the full path as you're typing. 

I did some testing on my PC this morning, and I think I can see a key difference in how Storage Explorer is behaving versus Windows/file explorer. In file explorer, I can't seem to find ANY location which results in a clicked address bar transforming to an empty input. However for Storage Explorer, if you are at the root directory, a clicked address bar does transform to an empty input. For non-root folders, it works just like file explorer. See example here:

![addressbar](https://github.com/microsoft/AzureStorageExplorer/assets/21112697/22d1ab6f-3a5a-46d8-aa12-22aa14e332e9)

This is something I think we can easily address, at least with a placeholder string in the empty case to make it more clear what the empty input is for.

> I would say it's also a bit confusing that when you do a prefix filter, it shows your search in the address bar (filtering 'xxx' by prefix 'yyyy') 

So displaying in the address bar that you are viewing search results is a pattern we have borrowed from file explorer.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/21112697/717618bc-e3bb-445a-a8c5-375308c6bcc5)

![image](https://github.com/microsoft/AzureStorageExplorer/assets/21112697/702d8478-4393-4563-b949-119ffa392792)

> but then you can click on that and type anything it's only editing the folder you are searching in. It just seems strange the filter is displayed there but not editable.

This is a good point. For file explorer, if you click on the address bar in the example I had above, the address bar transforms to an input with this value: 

`search-ms:displayname=Search%20Results%20in%20jsons&crumb=System.Generic.String%3Ajso&crumb=location:C%3A%5CUsers%5Cmyusername%5CDownloads%5Cjsons`

I guess technically speaking that is a value I could edit? However, I gave it a try, for example, editing the display name or the location, but neither worked in the way I would expect. Part of me thinks that's more intended as something I can save and use later to quickly return to those search results. An interesting idea.

I think for now, the immediate thing we can do is improve that empty address bar situation I describe above. For the future, we should keep an eye on how other folks feel about:
- for non-gen2 blobs, the search box being in the view options panel
- being able to get a more useful value when clicking on the address bar when viewing search/filter results

**Comment by MRayermannMSFT** [comment]
@jeffpapp it seems the discussion in this issue has run its course. If you have any commentary on the issue I opened, please feel free to comment on it there. Or if you have any specific ideas releated to this conversation, please feel free to open an issue for that specific idea. Thanks!
