### ISSUE TITLE
It is better to make the behaviors consistent when typing non-exist folder to 'filter by prefix' box between ADLS Gen2 blob containers and file shares

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7832]
**Storage Explorer Version**: 1.34.0-dev (98)
**Build Number**: 20240321.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.4(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> File Shares.
2. Create a file share -> Type 'f1/' into the 'filter by prefix' box.
3. Observe the result.
4. Expand 'Blob Containers' node -> Create a blob container.
5. Type 'f1/' into the 'filter by prefix' box -> Observe the result.
6. Check whether the behaviors are consistent.
## Expected Experience ##
The behaviors are consistent.
## Actual Experience ##
The behaviors are inconsistent.
1. For ADLS Gen2 blob containers, there is no error info.
2. For file shares, there is an error info bar.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/59d80c5f-19e1-49bf-b077-0543a3c8e308)

**Comment by v-xianya** [comment]
Hi @richardMSFT Verified this issue on the main build 20240529.1.
The current behavior is 'No error pops up for both ADLS Gen2 blob containers and file shares when typing non-exist folder to filter box'. Is this the expected behavior?

**Comment by richardMSFT** [comment]
Yes that is the behavior we decided on :).

**Comment by v-xianya** [comment]
Thanks for your confirmation. Now the behavior is expected, so, we are going to close this issue.
