### ISSUE TITLE
Fail to paste a file share when the setting 'Enable file OAuth support' is in effect

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7834]
**Storage Explorer Version**: 1.34.0-dev (98)
**Build Number**: 20240323.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.4(Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Open 'Settings' -> Check the setting 'Enable Files OAuth Support'.
2. Restart Storage Explorer.
3. Expand one storage account -> File Shares -> Create a file share.
4. Copy the file share then paste it to another storage account.
5. Check whether succeeds to paste the file share.

## Expected Experience ##
Succeed to paste the file share.

## Actual Experience ##
Fail to paste the file share.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/0f1da01b-111d-46ba-9979-bb5c82d20b93)
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/8b017637-792c-4713-8d85-e610b7dc5def)

Error details:
`message": "Authentication information is not given in the correct format. Check the value of Authorization header.\n`

**Comment by MRayermannMSFT** [comment]
@v-xianya when you do the paste, is it to another storage account in either eastus2euap or centraluseuap?

**Comment by v-xianya** [comment]
@MRayermannMSFT `is it to another storage account in either eastus2euap or centraluseuap?` yes, I think so. But just to be sure, we'd better retest this feature after implementation.

**Comment by MRayermannMSFT** [comment]
@v-xianya I still cannot repro this. Can you:

1. Re-test on latest main
2. If it fails, then make sure:
   1. You can create shares in the destination storage account (e.g. do a right click ->  "Create File Share"
   2. The location is `eastus2euap ` or `centraluseuap`
3. If it fails, then share here:
   1. The log file for file-extension
   2. The subscription & name of the source and destination storage accounts so I can try myself

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT I tested this issue on the main build 20240725.1. Reproduce.
1. The log files:
[2024-07-25_014703.zip](https://github.com/user-attachments/files/16369208/2024-07-25_014703.zip)
2. **Subscription:** Azure Tools Manual Testing 2 
**Storage accounts:** ay0725 & ay10725

**Comment by MRayermannMSFT** [comment]
Ok @v-xianya I think I understand the issue. It looks like on the accounts you are using, you only have the "Owner" role. Can you try this scenario a few more times, where:

1. On the first retry, also give yourself "Storage File Data Privileged Reader" ONLY on the destination storage account
2. On the second retry, also give yourself "Storage File Data Privileged Reader" ONLY on the source storage account
3. On the third retry,  also give yourself "Storage File Data Privileged Reader" on BOTH the source and destination storage account

I think I expect 2. and 3. to work, but not 1., let me know how it goes for real though!

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT 
I tried the three scenarios. All fails with the same error.

Here is the log for Scenarios 3:
 
[2024-07-26_012847.zip](https://github.com/user-attachments/files/16386101/2024-07-26_012847.zip)

**Comment by MRayermannMSFT** [comment]
Fix merged.

**Comment by v-xianya** [comment]
Verified this issue on the rel build 20240730.7. Fixed.
