### ISSUE TITLE
The azcopy activity log is always in progress when the setting 'Disable AzCopy Proxy Usage' is checked

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7835]
**Storage Explorer Version:** 1.34.0-dev (98)
**Build Number:** 20240325.7
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.4(Apple M1 Pro)
**Architecture:** x64/x64/arm64
**How Found:** From running test cases
**Regression From:** Previous release (1.32.1)

## Steps to Reproduce ##

1. Launch Storage Explorer -> Open 'Settings' -> Check the setting 'Disable AzCopy Proxy Usage'.
2. Expand one storage account -> Blob Containers -> Create a blob container.
3. Click 'Upload -> Upload Files...' -> Select a file -> Click 'Upload'.
4. Check whether there is a successful activity log.

## Expected Experience ##
There is a successful activity log.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/e5fcb44f-ca3f-4a90-bc25-0a201eae26d5)

## Actual Experience ##
The activity log is always in progress.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/0e7ddf59-8f92-456b-a530-8216773cdfde)

## Additional Context ##
'0 completed' displays in the activity log when deleting blobs/files.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/99792ee5-b998-4ad5-a0d2-5441ea62cc37)

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240401.1. Fixed. So, we are going to close it.

**Comment by v-xianya** [comment]
This issue reproduces on the hotfix/1.33.1 build 20240409.2. So, we are going to reopen it.

**Comment by v-xianya** [comment]
Verified this issue on the hotfix build 20240410.2. Fixed. So, we are going to close it.
