### ISSUE TITLE
MOV file upload failures

### ISSUE THREAD

**Issue by v-maddiemaze** [microsoft/AzureStorageExplorer#7836]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.33.0

### Regression From

1.32.1

### Architecture

x64

### Storage Explorer Build Number

20240301.4

### Platform

Windows

### OS Version

Windows 11

### Bug Description

When attempting to upload MOV files over 50 GB in size to our Azure blob storage containers, we encounter a recurring issue where the upload process halts indefinitely at a specific percentage, such as 57% or 99%. This is indicated by a persistent spinning circle, yet no error messages are displayed. This issue has been occurring approximately with 50% of MOV uploads since the latest update was implemented. The only way to resolve is to manually cancel the upload and try to upload again. 

### Steps to Reproduce

Confirming the most recent update. Closing and restarting Azure blob storage. Re-attempting to upload MOV files a second time.

### Actual Experience

When attempting to upload MOV files over 50 GB in size to our Azure blob storage containers, we encounter a recurring issue where the upload process halts indefinitely at a specific percentage, such as 57% or 99%. This is indicated by a persistent spinning circle, yet no error messages are displayed. This issue has been occurring approximately with 50% of MOV uploads since the latest update was implemented. The only way to resolve is to manually cancel the upload and try to upload again. 

### Expected Experience

The MOV file should upload into a container with no freezing. 

### Additional Context

We use Azure blob storage to store video files for the Microsoft Archives and have never encountered this issue before.

**Comment by MRayermannMSFT** [comment]
Reached out internally.

**Comment by MRayermannMSFT** [comment]
This is being internally via email support.
