### ISSUE TITLE
It displays ' ' instead of the file share's name when the move activity is in progress

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7838]
**Storage Explorer Version**: 1.34.0-dev (98)
**Build Number**: 20240327.12
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.4(Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Upload one file.
3. Create a folder on the file share.
4. Select the file -> Click 'Move' -> Type the folder name in to the 'Destination directory' field on the move dialog -> Click 'Move'.
5. Observe the activity log.
6. Check whether it always displays the file share's name.

## Expected Experience ##
It always displays the file share's name.

Here is the screenshot of the completed activity log.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/d417a4a5-0996-4650-8791-5d01093b54fd)

## Actual Experience ##
It displays ' ' instead of the file share's name when the activity is in progress.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/55c54fcb-b371-4c14-9239-f8c9514aabb9)

## Additional Context ##
1. This issue doesn't reproduce when the moved file is not in root directory.
2. This issue doesn't reproduce for ADLS Gen2 blobs.

**Comment by MRayermannMSFT** [comment]
Pretty sure this is fixed? I'm having a hard time getting a move operation to last long enough that I can even see the in progress message.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240411.1. Fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/5bd81a63-d0c6-4a58-8523-dd7a1f7184a0)
