### ISSUE TITLE
There is no 'X' button on the opened tab

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#784]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10
**Architecture**: ia32
**Build Number**: 20181022.4
**Commit**: 492b519a
**Regression From**: Previous release 1.4.4

#### Steps to Reproduce: ####
1. Open one blob container -> Focus on the opened tab.
2. Press Tab -> Verify the 'X' button is focused or not on the opened tab .

#### Expected Experience: ####
The 'X' button is focused with highlight.

#### Actual Experience: ####
There is no 'X' button on the opened tab when trying focused to it.
![x](https://user-images.githubusercontent.com/34729022/47284880-86461100-d61b-11e8-815b-11357586e35f.png)

**Comment by MRayermannMSFT** [comment]
Fixed.
