### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by fmunizsimas** [microsoft/AzureStorageExplorer#7843]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.33.0 (97)

### Architecture

arm64

### Storage Explorer Build Number

20240301.4 

### Platform

macOS

### OS Version

Sonoma 14.4.1 (23E224)

### Bug Description

Unable to retrieve child resources

ProducerError:{
  "name": "Electron Net Error",
  "message": "net::ERR_CONNECTION_REFUSED",
  "stack": "Error: net::ERR_CONNECTION_REFUSED\n    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:108315)\n    at SimpleURLLoaderWrapper.emit (node:events:517:28)",
  "cause": {}
}

### Steps to Reproduce

1. open storage explorer
2. opena file shares (none displayed)

### Actual Experience

![Screenshot 2024-03-31 at 9 48 28 PM](https://github.com/microsoft/AzureStorageExplorer/assets/44655418/0e09de39-6afc-4a67-a646-a3198c2e2f13)

### Expected Experience

Browse directories

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. This issue will no longer be monitored. If you need further help, we recommend opening a support ticket via the Azure portal. Alternatively you can open a new issue here.
