### ISSUE TITLE
No entities appear when importing 'table200x200.csv' file in one emulator table

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7844]
**Storage Explorer Version:** 1.34.0-dev (98)
**Build Number:** 20240401.1
**Branch:** main
**Platform/OS:** Windows 10
**Emulator Version:** Azurite 3.29.0
**Architecture:** x64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Install and run Azurite 3.29.0 -> Launch Storage Explorer.
2. Expand 'Local & Attached -> Storage Accounts -> (Emulator - Default Ports) (Key)'.
3. Tables -> Create a table -> Import the below csv file.
[table200x200.csv](https://github.com/microsoft/AzureStorageExplorer/files/14821894/table200x200.csv)
4. Check whether the entities appear in the explorer.

## Expected Experience ##
The entities appear in the explorer.

## Actual Experience ##
1. No entities appear in the explorer.
2. An empty error info prompts.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/0bf0b6b1-b3a0-40b0-995b-3b307a493ebe)

## Additional Context ##
1. This issue doesn't reproduce for regular tables.
2. We can't reproduce this issue for other csv files.
3. In 1.30.2, an error info prompts.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/2c16ef3f-4f4d-4e4e-bece-46a9aeb4b448)

**Comment by JasonYeMSFT** [comment]
Since this kind of csv cannot be imported since 1.30.2, let's just focus on investigating the cause of it in 1.34.0.

**Comment by craxal** [comment]
@v-kellyluo Can you provide any console output from the Azurite process for a better idea of what the error might be?

**Comment by v-kellyluo** [comment]
Hi @craxal, here is the console output from the Azurite process:
[azurite.txt](https://github.com/microsoft/AzureStorageExplorer/files/14830290/azurite.txt)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240415.1. Fixed.
