### ISSUE TITLE
The QA item's name is inconsistent with its original blob container attachment's name

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7845]
**Storage Explorer Version:** 1.34.0-dev (98)
**Build Number:** 20240401.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.4(Apple M1 Pro)
**Architecture:** x64/x64/arm64
**How Found:** From running test cases
**Regression From:** Previous release (1.30.2)

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Attach the blob container.
3. Pin the attached blob container to Quick Access node.
4. Check whether the QA blob container name is consistent with attached blob container name.

## Expected Experience ##
The QA blob container name is consistent with attached blob container name.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/0f4f9758-d955-415d-81d5-df908dcae05e)

## Actual Experience ##
The QA blob container name is inconsistent with attached blob container name.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/0b2a6ff2-de3c-4c7e-b33c-ad2c45b68ba6)

## Additional Context ##
This issue doesn't reproduce for other services.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240416.1. Fixed. So, we are going to close it.
