### ISSUE TITLE
The error is unclear when the preview of parquet files fails

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7849]
**Storage Explorer Version**: 1.33.0 (97)
**Build Number**: 20240404.6
**Branch**: dev/cralvord/hotfix-build
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.4(Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.32.1)

## Steps to Reproduce ## 
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload the parquet file 'brotli.parquet'.
3. Preview the parquet file -> There is a failed activity log.
4. Check whether the error is clear.

## Expected Experience ##
The error is clear.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/0253625c-f98f-4a05-bdef-8194f8465a22)

## Actual Experience ##
The error is unclear.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/cc02f6f3-415f-4e60-917f-1da8e1ef16ea)

## Additional Context ##
Below are two files that can reproduce this issue.
[brotli.zip](https://github.com/microsoft/AzureStorageExplorer/files/14896303/brotli.zip)

**Comment by craxal** [comment]
A fix has been merged. Messages are now less vague. Please keep in mind that the specific BROTLI error message is different, but a specific message is still displayed.

**Comment by v-xianya** [comment]
Verified this issue on the hotfix build 20240409.2. Reproduce. So, we are going to reopen it.

**Comment by craxal** [comment]
The build I sent you did not contain the fix. Please verify on a new build.

**Comment by v-xianya** [comment]
Verified this issue on the hotfix build 20240410.2. The error is clear.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/a7db9edb-aab0-4268-b65b-4b15c684065e)
