### ISSUE TITLE
No 'Toggle Explorer & Manage Accounts & Add account' buttons present 

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#785]
Storage Explorer Version: 1.5.0
Platform/OS Version: Windows 10
Architecture: ia32
Build Number: 20181022.4
Commit: 492b519a
Regression From: Previous release 1.4.4

#### Steps to Reproduce: ####
1. Launch the Storage Explorer -> Check the top left of the Storage Explorer.

#### Expected Experience: ####
'Toggle Explorer & Manage Accounts & Add account' buttons present at the top of left in storage explorer.

#### Actual Experience: ####
 No 'Toggle Explorer & Manage Accounts & Add account' buttons present at the top left of storage explorer.
![image](https://user-images.githubusercontent.com/41351993/47286251-78df5580-d620-11e8-95e9-f3e30c9edea7.png)

#### More Info: ####
This issue doesn't reproduce on Mac/Linux.

**Comment by MRayermannMSFT** [comment]
Fixed.
