### ISSUE TITLE
Can't list file shares when signed-in with Entra ID credentials

### ISSUE THREAD

**Issue by jackvdbuk** [microsoft/AzureStorageExplorer#7851]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.33.0

### Architecture

x64

### Storage Explorer Build Number

20240301.4

### Platform

Windows

### Bug Description

Based on this article, i should be able to access Storage account files shares using storage explorer and Entra credentials 
[https://techcommunity.microsoft.com/t5/azure-storage-blog/general-availability-introducing-azure-ad-support-for-azure/ba-p/3826733](url)
[https://github.com/microsoft/AzureStorageExplorer/issues/6287](url)

### Steps to Reproduce

Launch storage explorer.
Sign in with Azure AD Account
Expand the subscription
Expand the storage account
Expand File Shares (displays error). 

### Actual Experience

The error displayed on expanding file shares is:

Unable to retrieve child resources

ProducerError:{
  "name": "Error",
  "message": "Unable to perform operation 'FileServiceClient.listSharesSegment'. No suitable credentials provided.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/55866307/582c9915-e10b-445a-8d19-6794bf22f6fe)

### Expected Experience

File share should expand.

### Additional Context

The  Entra ID account has the following IAM roles on the storage account:

- Reader (to be able to list storage accounts 
-  Storage File Data Privileged Contributor
- Storage File Data SMB Share Contributor

I can see from a fiddler trace, the list keys API call is failing: 
POST /subscriptions/%sub%/resourceGroups/%rg%/providers/Microsoft.Storage/storageAccounts/%storageaccountname%/listKeys?api-version=2023-01-01&$expand=kerb HTTP/1.1

**Comment by MRayermannMSFT** [comment]
@jackvdbuk unfortunately the file share service does not yet support using OAuth (Entra ID) credentials on all of the APIs that storage explorer uses. The backend team is working to roll out full support, but unfortunately until that work is done, this is not possible. Regarding any sort of ETA for this support, the best I can tell you right now is "later in the year". You can follow this issue for updates: https://github.com/microsoft/AzureStorageExplorer/issues/7775
