### ISSUE TITLE
It displays unclear error when the avro file preview fails

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7852]
**Storage Explorer Version**: 1.33.1 (98)
**Build Number**: 20240409.2
**Branch**: hotfix/1.33.1
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.4(Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.32.1)

## Steps to Reproduce ## 
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload the avro file 'avro/weather-snappy.avro'.
3. Preview the file -> There is a failed activity log.
4. Check whether the error is clear.

## Expected Experience ##
The error is clear.
**Error details:**  "message": "unknown codec: snappy"

![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/e8f0e0b8-f336-4fe2-8584-68945e31bc19)

## Actual Experience ##
The error is unclear.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/aa01b841-ded3-41a2-9079-ae4118c1cc19)

## Additional Context ##
Below is the file that can reproduce this issue.
[weather-snappy.zip](https://github.com/microsoft/AzureStorageExplorer/files/14914099/weather-snappy.zip)

**Comment by craxal** [comment]
It seems that the last package update didn't get all the changes somehow. Just need to update the package again.

**Comment by v-xianya** [comment]
Verified this issue on the hotfix build 20240410.2. Fixed. So, we are going to close it.
