### ISSUE TITLE
The error message does not make sense when saving '汉字‘ as the metadata key for blob containers/blobs/queues

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7853]
**Storage Explorer Version**: 1.33.1 (98)
**Build Number**: 20240409.2
**Branch**: hotfix/1.33.1
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.4(Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: Ad-hoc testing 
**Regression From**: Not a regression
## Steps to Reproduce ## 
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Right click the blob container.
3. Click 'Properties...' -> Click 'Add Metadata' -> Type '汉字' in the metadata key field -> Save it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/c778321d-8335-4972-a7b5-9ad00e3d1ffb)
4. There is a failed activity log -> Click 'Details...'.
5. Check whether the error message makes sense.

## Expected Experience ##
The error message makes sense. Like 'The metadata specified is invalid.'

## Actual Experience ##
The error message doesn't make sense.
**Error details:**   "message": "Cannot convert argument to a ByteString because the character at index 10 has a value of 27721 which is greater than 255."
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/09cfd7ca-886d-42b1-b1ee-94d5a878dfc2)

## Additional Context ##
Here is the screenshot for files under file shares when saving metadata whose metadata key is '汉字'.
**Error details:**  "stack": "RestError: The metadata specified is invalid. It has characters that are not permitted.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/eb3d4c1b-9982-4085-868e-8e5bcea53a25)

**Comment by MRayermannMSFT** [comment]
We should have validation that catches this case (assuming it is actually invalid).

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240604.2. Fixed. So, we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/0a21ba45-9a56-4851-a5f8-4041e912f5f7)
