### ISSUE TITLE
It is better to adjust the size of the clone blob container dialog to ensure no scrollbar appears

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7854]
**Storage Explorer Version**: 1.33.1 (98)
**Build Number**: 20240409.2
**Branch**: hotfix/1.33.1
**Platform/OS**: Windows 10
**Architecture**: x64
**How Found**: Ad-hoc testing 
**Regression From**: Previous release (1.31.2)

## Steps to Reproduce ## 
1. Expand one storage account -> Blob Containers.
2. Right click one blob container -> Click 'Clone...'.
3. Type 'aa-' into the 'New name' field.
4. Check whether there is no scrollbar.

## Expected Experience ##
It is better to adjust the size of the dialog to ensure no scrollbar appears.

## Actual Experience ##
There is a scrollbar.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/44ed21ab-c385-44f1-9dfd-3f24cd83a9be)

## Additional Context ##
Here is the screenshot in previous release 1.31.2 version.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/8bdd16a2-5be4-40fc-b5df-99a02af50b4c)

**Comment by craxal** [comment]
@richardMSFT I'm not able to reproduce this. Can you verify on Mac and Windows? If it reproduces, there could be a problem in the auto-sizing code, but let's just adjust the size of the dialog for now.

**Comment by v-xianya** [comment]
This issue only reproduces on Windows platform.

**Comment by craxal** [comment]
I'm keeping Richard assigned just so we retain that he originally worked on this.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240423.1. Fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/ec45b828-bd43-4a53-b916-56973009cf36)
