### ISSUE TITLE
1.4.4 tosses error when expanding Blob node of Classic accounts

### ISSUE THREAD

**Issue by justSteve** [microsoft/AzureStorageExplorer#786]
**Storage Explorer Version**: 1.4.4
**Platform/OS Version**: win10
**Architecture**: ia32
**Regression From**: was working. unsure of exact version number

#### Steps to Reproduce: ####
1. Navigate to an account designated with (classic)
2. Expand 'Blobs'.

#### Expected Experience: ####
See list of blobs

#### Actual Experience: ####
App tosses 2 successive error dialogs: 
![image](https://user-images.githubusercontent.com/103760/47287529-2a966c00-d5b8-11e8-9fb9-0d96e3ecb5bb.png)

**Comment by MRayermannMSFT** [comment]
I want to say that this was due to Storage Explorer not supporting RBAC in Oct 2018. But now that it is supported, you should be able to access your data. @justSteve are you still having issues with the latest version, 1.12.0?

**Comment by justSteve** [comment]
All is well - thx
