### ISSUE TITLE
The blob container name and storage account name are confused in translation for the delete blob container dialog on Japanese

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7860]
**Storage Explorer Version:** 1.34.0-dev (98)
**Build Number:** 20240411.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.4(Apple M1 Pro)
**Language:** Japanese
**Architecture:** x64/x64/arm64
**How Found:** Ad-hoc testing
**Regression From:** Previous release(1.32.1)

## Steps to Reproduce ##

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select '日本語' -> Restart Storage Explorer.
3. Expand one storage account -> Blob Containers.
4. Create a blob container -> Right click the blob container -> Click 'Delete'.
5. Observe the translated descriptions in the delete dialog.
6. Check whether the descriptions are localized correctly.

## Expected Experience ##
The descriptions are localized correctly.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/1069be38-3a20-4408-9d4d-179a957ccf6f)

## Actual Experience ##
The blob container name and storage account name are confused.
It is translated to 'Do you want to permanently delete blob container **'0407try**' and its contents in storage account '**a-test**'?'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/c39ee945-78c1-418b-aa42-53f2ef10734d)

**Comment by craxal** [comment]
I have created a work item for the translation team to verify and fix: https://ceapex.visualstudio.com/CEINTL/_workitems/edit/963099

**Comment by v-kellyluo** [comment]
Verified this issue on the build main 20240423.1. Fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/b0ebf6cb-4a47-470d-9d55-1f0f7ec8862f)
