### ISSUE TITLE
Add File Type to "Customize Columns..." - Column Options window

### ISSUE THREAD

**Issue by bgoosen** [microsoft/AzureStorageExplorer#7861]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I would like to be able to quickly sort between file types

### Desired Solution

Add File Extension as an option for column sort to the Column Options menu

### Alternatives and Workarounds

I can also access the File Share using our users' credentials in an FTP client that allows File Type sorting, but would prefer to work in Storage Explorer under my own account credentials.

### Additional Context

I routinely need to find if a client has uploaded any other files (typically XLS) in a File Share loaded with 1000s of JPGs

**Comment by craxal** [comment]
@bgoosen When you say "file type", are you referring to the file's `ContentType` property (it's MIME type), or do you want the extension from the file name?

**Comment by bgoosen** [comment]
I believe either would be sufficient for my situation.
