### ISSUE TITLE
Fix WASM bundling

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#7870]
- Upgrade parquetjs lib to 1.6.2 (add ^ to package.json)
- ~~Figure out how to esbuild the new brotli lib.~~
- ~~Ideally add some sort of test in file preview extension which detects if the parquet Brotli lib dependency changes again.~~

**Comment by craxal** [comment]
This really a multi-layered problem.

First, our ESBuild plugin currently is not correctly bundling _any_ WASM modules, leading to "not a function" errors when trying to open Brotli-compressed Parquet files. On closer inspection, although the binary data is present in the bundle, it appears that the WASM module isn't actually loaded. Only the "stub" created by ESBuild is loaded in a `default` property.

Second, our plugin assumes that WASM modules are being imported like any other module, such as:

```typescript
import something from "./some.wasm";
```
However, the Brotli packages aren't importing the WASM modules at all. They are reading them directly from the file system. ESBuild does not consider these imports, and so they are never processed by the plugin. 

From this, it seems that trying to bundle WASM files won't work as expected. We may have to include them as external files along with the bundles.
