### ISSUE TITLE
The 'Status' column is still visible in the editor even if the column is hidden

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7878]
**Storage Explorer Version**: 1.34.0-dev (98)
**Build Number**: 20240416.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.4(Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.32.1)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Right click the column header -> Click 'Customize Columns...'.
4. Hide the 'Status' column -> Click 'OK'.
5. Check whether the 'Status' column is not visible in the editor.

## Expected Experience ##
The 'Status' column is not visible in the editor.

## Actual Experience ##
The 'Status' column is visible in the editor.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240419.1. Fixed.
