### ISSUE TITLE
Cannot read property 'connectionString' of undefined

### ISSUE THREAD

**Issue by JeffMushmo** [microsoft/AzureStorageExplorer#788]
Version: 1.4.4 Build: 20181012.3
Windows
ia32
Has worked on all previous versions I've used.

#### Steps to Reproduce: ####
1. Authenticate using Azure AD.
2. Expand any Azure subscription.
3. Expand any storage account.

#### Expected Experience: ####
A list of all of your blob containers that exist within each Azure subscription.

#### Actual Experience: ####
Error Dialog saying:
Unable to retrieve child resources.
Details: Cannot read property 'connectionString' of undefined

**Comment by JeffMushmo** [comment]
I've tried uninstalling and reinstalling with no fix.

**Comment by JeffMushmo** [comment]
Bueller?

**Comment by spboyer** [comment]
See -> https://github.com/Microsoft/AzureStorageExplorer/issues/726#issuecomment-443310882 for solution.

**Comment by MRayermannMSFT** [comment]
@JeffMushmo are you still having problems?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
