### ISSUE TITLE
Azure Storage Explore cannot clone or copy blobs after first container backup to an Azure Backup vault

### ISSUE THREAD

**Issue by rssllptrs** [microsoft/AzureStorageExplorer#7882]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.33.1 (98)

### Architecture

x64

### Storage Explorer Build Number

20240410.2

### Platform

Windows

### OS Version

Windows 11

### Bug Description

After configuring a Storage Account (non ADLS) for backup to an Azure Backup Vault, and after the first backup, all clones and copy/paste operations of blobs  from containers that were configured for backup yield an error "RESPONSE Status: 400 The metadata specified is invalid. It has characters that are not permitted." Note that copy and clone from the Azure Portal "Storage Browser" work find and as expected. Also copy/paste and clone operations from containers that are not backed up to an Azure Backup vault work as expected.
[81c9c2d8-290e-784b-6cee-65db5696e2c9.log](https://github.com/microsoft/AzureStorageExplorer/files/15015281/81c9c2d8-290e-784b-6cee-65db5696e2c9.log)

### Steps to Reproduce

For an existing storage account and an existing backup vault:
1. Verify that clones and copies work as expected using storage explorer.
2. configure the storage account for backup to the vault using the procedure in this document:
https://learn.microsoft.com/en-us/azure/backup/blob-backup-configure-manage?tabs=operational-backup
3. Issue a manual backup (or wait for the scheduled backup to occur.
4. Attempt to clone or copy same blobs as in step 1 to show they no longer work. You can still download and upload fine and you can clone/copy from Azure portal fine.

### Actual Experience

Paste and Clone simply do not work. They start, but fail at the very end (appears to be related to metadata issues).

### Expected Experience

Expectation is for clone/copy to work like for containers that don't have Backup configured.

### Additional Context

NA

**Comment by JasonYeMSFT** [comment]
@rssllptrs From the log, the copy/clone job is trying to set the metadata pair with name "E2bc6aa5-07df-4039-A05f-69a29f48c7e5_8179f480-Fb83-419b-90a7-B20c5a7233fd" and value "complete". I am pretty sure this is not a valid metadata name. It violates not only Storage Explorer's validation rule but also Azure Portal's.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/39359541/5adcbdc0-edf0-45c3-8894-a61766762fa0)

Could you view the properties of the source blob and see what Storage Explorer display as the metadata name? If Azure Backup Vault somehow manages to set the metadata with an invalid name, it's a serious bug that they need to look at as soon as possible. Could you reach out to Azure Backup Vault team to find out?

**Comment by rssllptrs** [comment]
Hi Jason,

Using Storage explorer, when viewing the blob properties there is no custom
metadata on the blob in question. However, within the "Storage Browser" in
the Azure Portal, when viewing the properties, I do see a new set of fields
under the heading "Object replication" (which only exists for blobs that
are protected by an Azure Backup Vault policy). The fields are Policy ID,
Rule ID, and Status. Incidentally, the Policy ID matches the invalid
metadata key in the log file and the Status = "Completed" matches the
corresponding invalid metadata value. Perhaps this isn't user modifiable
metadata, but some internal (new) data that Storage Explorer is yet to
support and is treating as metadata. I have opened a case in Azure
describing the issue -- case: 2404190040009165.

- Russ
***@***.***

**Comment by JasonYeMSFT** [comment]
AzCopy is incorrectly treating this object replication header as metadata. I have notified their dev on this bug.

**Comment by MRayermannMSFT** [comment]
Currently slotted for 10.26.0 (July 24). Maybe we'll shift our release a bit to catch 10.26.0. We'll see. @JasonYeMSFT please track this for 1.35. :)

**Comment by JasonYeMSFT** [comment]
https://github.com/Azure/azure-storage-azcopy/issues/2655#issuecomment-2220270779

**Comment by JasonYeMSFT** [comment]
This is fixed in 1.35 rel branch.
