### ISSUE TITLE
The 'Cancel' action next to propagate ACLs activity log does not take effect

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7883]
**Storage Explorer Version**: 1.34.0-dev (98)
**Build Number**: 20240418.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.4(Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload more than 100 files to the blob container.
3. Right click the blob container -> Click 'Propagate Access Control Lists...'.
4. Check the option 'I understand that propagating ACLs cannot easily be reversed.' -> Click 'OK'.
5. Click 'Cancel' next to the InProgress activity log.
6. Check whether the activity cancellation was successful.

## Expected Experience ##
The activity cancellation was successful.

## Actual Experience ##
'Cancel' action does not take effect.

**Comment by craxal** [comment]
I think the request sequence is being canceled correctly. The problem is the cancelation event isn't propagating. I think it's deep down in our internal net implementations.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240421.1. Fixed. 
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/523f79c7-2e5f-4d6e-976c-8e8da925ec44)
