### ISSUE TITLE
Fail to preview one 3D file with an error "Error creating WebGL context."

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7884]
**Storage Explorer Version**: 1.34.0-dev (98)
**Build Number**: 20240419.1
**Branch**: main
**Platform/OS**: Windows 11
**Architecture**: arm64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload a .stl file whose size is less than 10 MiB.
3. Preview the file.
4. Check whether the file is previewed successfully.
## Expected Experience ##
The file is previewed successfully.

## Actual Experience ##
Fail to preview the file with an error `"message": "Error creating WebGL context"`.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/40071c19-206a-4bb4-a4f1-40d91602c5a4)

## Additional Context ##
1. This issue doesn't reproduce for Windows x64 (Windows 10).
2. Display the same error `"message": "Error creating WebGL context"` when previewing .glb/.gltf/.obj/.stl files.

**Comment by MRayermannMSFT** [comment]
@v-xianya can you share a file used to repro this? I am not able to reproduce. In my case I used: 
[Menger_sponge_sample.zip](https://github.com/microsoft/AzureStorageExplorer/files/15043336/Menger_sponge_sample.zip)

**Comment by craxal** [comment]
I can reproduce on a Windows VM. This shouldn't be entirely surprising, because VMs don't come with hardware-accelerated graphics. This is easily proven by attempting to view [THREE.js sample models](https://threejs.org/examples).

@MRayermannMSFT @richardMSFT The error is being thrown when attempting to create the `THREE.WebGLRenderer`. Considering how often users install Storage Explorer on VMs, it may be prudent to add a try/catch block

**Comment by MRayermannMSFT** [comment]
@v-xianya nevermind on needing a sample file. We'll instead focus on handling the error in a more graceful way.

**Comment by MRayermannMSFT** [comment]
Ok @v-xianya, first, it should be considered expected that 3d file preview doesn't work on the Auzre VM. However, I have updated the file preview exxperience to be more tolderant of this situation. In this situation, there should be an activity saying Storage Explorer was unable to preview, and no error dialogs should pop up unless you click on something to explicitly bring one up (ex: a "Details..." action).

**Comment by v-xianya** [comment]
Hi,  @MRayermannMSFT thank you for the updates!
On the new build 20240421.1, the current behaviors keep the same with the build 20240419.1. Are these the expected behaviors?
1. Display an activity log saying Storage Explorer was unable to preview.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/25f533bd-eed8-4664-9729-0d7efe3a2170)
2. Popping up the error details after clicking 'Details...'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/00ec5eef-be98-4881-934b-d8023e5956fd)
