### ISSUE TITLE
The 'No' button is focused instead of 'Yes' button in the delete entity dialog 

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7885]
**Storage Explorer Version:** 1.34.0-dev (98)
**Build Number:** 20240419.1
**Branch:** main
**Platform/OS:** Windows 11/Linux Ubuntu 22.04/MacOS Sonoma 14.4(Apple M1 Pro)
**Architecture:** arm64/x64/arm64
**How Found:** From running test cases
**Regression From:** Previous release (1.33.1)

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create a table -> Add an entity.
3. Select the entity -> Click 'Delete'.
4. Check whether the 'Yes' button is focused in the delete entity dialog.

## Expected Experience ##
The 'Yes' button is focused.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/bc7e109e-7bae-400b-b595-f06191b64700)

## Actual Experience ##
The 'No' button is focused.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/ad5c1b34-d39d-4f44-b2fe-88192507eb96)

**Comment by craxal** [comment]
This was intentional, as we normally want to avoid defaulting an affirmative choice for a destructive operation. But for some reason, that decision was not widely implemented, so I'll switch this back for consistency reasons.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240421.1. Fixed.
