### ISSUE TITLE
Does RBAC  not work on Storage Explorer?  

### ISSUE THREAD

**Issue by picwopics** [microsoft/AzureStorageExplorer#789]
**Storage Explorer Version**: 1.4.4
**Platform/OS Version**: Windows 10 Pro 1803
**Architecture**: ia32
**Regression From**: 

#### Steps to Reproduce: ####
1. Add an Azure Account to SE.
2. Open a Storage Accounts on Explorer.
3.All Containers and BLOBs are shown, otherwise it's not allowed on RBAC in Azure Portal(IAM).

#### Expected Experience: ####
Only allowed Containers and BLOBs  are shown on SE, as same as in Azure Portal.

#### Actual Experience: ####
I would like to configure Azure Storage as  only allowed user can access the container.
I configured like that on Azure Portal by using RBAC(IAM), and it works on Azure Portal.
However on SA, it seems like  not to work.
I think it caused by permission of getting access key whose I gave users, 
but if it is not given, SE cannot read Containers and BLOBs. 
Is there a solution?

**Comment by MRayermannMSFT** [comment]
RBAC for blobs is now supported in Storage Explorer! I can't recall if it was supported when you first opened this issue though. Please try the latest version, 1.12.0, and let us know if you are still having issues.
