### ISSUE TITLE
Getting "Unable to retrieve child resources" error when I am trying to expand blob container in azurite storage emulator.

### ISSUE THREAD

**Issue by padmasekhar** [microsoft/AzureStorageExplorer#7891]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.33.1

### Architecture

x64

### Storage Explorer Build Number

20240410.2

### Platform

Windows

### OS Version

Windows 11

### Bug Description

Getting "Unable to retrieve child resources" error when I am trying to expand blob container in azurite storage emulator. I have attached error json here.

[Unable to retrieve child resources.txt](https://github.com/microsoft/AzureStorageExplorer/files/15057273/Unable.to.retrieve.child.resources.txt)

### Steps to Reproduce

1. Launch Storage explorer 
2. Expand storage accounts 
3. Expand storage 
4. Expand Blob Container

### Actual Experience

Getting "Unable to retrieve child resources" error when I am trying to expand blob container in azurite storage emulator. I have attached error json here.

**Comment by padmasekhar** [comment]
Hi @MRayermannMSFT 

1. Is your emulator running? - Yes - I ran "azurite" command in the command prompt and I got success response. I have attached the screen shot.
2. Is it running on the same machine you are running Storage Explorer? - Yes
3. Is it exposing blob service on port 10000? - Yes

**Comment by padmasekhar** [comment]
![azure](https://github.com/microsoft/AzureStorageExplorer/assets/139613546/cd8fec89-8de6-4a29-bcb2-8722b3117d4f)

**Comment by padmasekhar** [comment]
![azure2](https://github.com/microsoft/AzureStorageExplorer/assets/139613546/9958a77a-8854-44ab-b578-c4e02f2bb716)

**Comment by MRayermannMSFT** [comment]
@padmasekhar ok, one thing I now notice is that you trying to use Azurite with a custom storage account name. Normally the name of the Azurite storage account is `devstoreaccount1`. Are you intentionally trying to use a custom account name?

If you are ok with using the normal account, `devstoreaccount1`, then please try:
1. Start Azurite
2. Start Storage Explorer
3. Expand: Emulator & Attached > Storage Accounts > (Emulator - Default ports)

If you are wanting to use a custom account name, can you make sure you have followed the steps here to do so?
https://github.com/Azure/Azurite?tab=readme-ov-file#customized-storage-accounts--keys

**Comment by padmasekhar** [comment]
Well, No I am not intentionally trying to user custom account but, I little confused and created a new one. However, I just followed your suggestion and it is working as expected. Thank you very much for quick response @MRayermannMSFT
