### ISSUE TITLE
无法检索子资源

### ISSUE THREAD

**Issue by caoxiangou** [microsoft/AzureStorageExplorer#7892]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.331

### Regression From

1.331

### Architecture

x64

### Platform

All

### Bug Description

无法检索子资源

ProducerError:{
  "name": "Node Fetch Error",
  "message": "{\"name\":\"Node Fetch Error\",\"cause\":{\"cause\":{\"errno\":-3008,\"code\":\"ENOTFOUND\",\"syscall\":\"getaddrinfo\",\"hostname\":\"noitomshop.blob.core.windows.net\"}},\"code\":\"ENOTFOUND\",\"errno\":-3008}"
}

### Steps to Reproduce

1.启动
2. 展开blob列表

### Actual Experience

无法检索子资源

ProducerError:{
  "name": "Node Fetch Error",
  "message": "{\"name\":\"Node Fetch Error\",\"cause\":{\"cause\":{\"errno\":-3008,\"code\":\"ENOTFOUND\",\"syscall\":\"getaddrinfo\",\"hostname\":\"noitomshop.blob.core.windows.net\"}},\"code\":\"ENOTFOUND\",\"errno\":-3008}"
}

**Comment by MRayermannMSFT** [comment]
@caoxiangou can you give using system proxy setting a try? You can read more about it here: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-network#use-system-proxy-preview

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. This issue will no longer be monitored. If you need further help, we recommend opening a support ticket via the Azure portal. Alternatively you can open a new issue here.
