### ISSUE TITLE
file deletion.

### ISSUE THREAD

**Issue by Ahmed-Aljalal** [microsoft/AzureStorageExplorer#7893]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.33.1

### Regression From

N/A

### Architecture

x64

### Storage Explorer Build Number

1.33.1

### Platform

Windows

### Bug Description

{
  "name": null,
  "message": "\"Authentication Failed. The SAS is not correct or expired or does not have the correct permission DELETE https://icrcregionname.blob.core.windows.net/sannonconfidential/HOE/2024/202404/Voucher with Attachment/Stop Flying Paper Initiative Global Rollout - Kickoff Meeting and Technical Training Session.pptx\\n--------------------------------------------------------------------------------\\nRESPONSE 403: 403 This request is not authorized to perform this operation using this permission.\\nERROR CODE: AuthorizationPermissionMismatch\\n--------------------------------------------------------------------------------\\n﻿<?xml version=\\\"1.0\\\" encoding=\\\"utf-8\\\"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.\\nRequestId:5f9534c0-801e-001b-707f-94dd51000000\\nTime:2024-04-22T06:35:15.5253988Z</Message></Error>\\n--------------------------------------------------------------------------------\\n\""
}

### Steps to Reproduce

1-Right click on the file to be deleted, 2- choose delete in the drop list.

### Actual Experience

I uploaded a ppt file as a test and tried to delete it, but the deletion failed.

### Expected Experience

be advised on how to do a successful deletion.

### Additional Context

{
  "name": null,
  "message": "\"Authentication Failed. The SAS is not correct or expired or does not have the correct permission DELETE https://icrcregionname.blob.core.windows.net/sannonconfidential/HOE/2024/202404/Voucher with Attachment/Stop Flying Paper Initiative Global Rollout - Kickoff Meeting and Technical Training Session.pptx\\n--------------------------------------------------------------------------------\\nRESPONSE 403: 403 This request is not authorized to perform this operation using this permission.\\nERROR CODE: AuthorizationPermissionMismatch\\n--------------------------------------------------------------------------------\\n﻿<?xml version=\\\"1.0\\\" encoding=\\\"utf-8\\\"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.\\nRequestId:5f9534c0-801e-001b-707f-94dd51000000\\nTime:2024-04-22T06:35:15.5253988Z</Message></Error>\\n--------------------------------------------------------------------------------\\n\""
}

**Comment by MRayermannMSFT** [comment]
@Ahmed-Aljalal how have you connected to your storage resource? Did you:
- Sign in, and access the storage accont/blob container underneath a subscription?
- Attach a storage account, using name & key, or a key or SAS connection string?
- Attach your container directly, using a SAS URL, or via OAuth authentication?

**Comment by Ahmed-Aljalal** [comment]
> @Ahmed-Aljalal how have you connected to your storage resource? Did you:
> 
> * Sign in, and access the storage accont/blob container underneath a subscription?
> * Attach a storage account, using name & key, or a key or SAS connection string?
> * Attach your container directly, using a SAS URL, or via OAuth authentication?


Thanks for replying.
we have solved this and, FYI, it is part of the system setup to not allow deleting uploaded documents.
