### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by burningchrome7** [microsoft/AzureStorageExplorer#7894]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.33.1

### Architecture

x64

### Storage Explorer Build Number

20240410.2

### Platform

Windows

### OS Version

Windows 11 Business

### Bug Description

Cannot view the contents of Blob Containers. $web

### Steps to Reproduce

1. Launch Storage Explorer
2. Open Pay-As-You-Go
3. Open Storage Accounts
4. Open storage account (premium) (BlockBlobStorage)
5. Select Blob Containers

### Actual Experience

After step 5 above I get:
Unable to retrieve child resources

ProducerError:{
  "name": "Electron Net Error",
  "message": "{\"name\":\"Electron Net Error\",\"cause\":{}}"
}

### Expected Experience

I would expect to see $logs and $web but I get the error message instead.

### Additional Context

It was working this morning when I copied blobs from a production directory to a development dir. The third time I did a copy Storage Explorer quit responding. Now every time I try I get the Electron Net Error. Also if I try to access the storage account from Azure Portal  Storage Account/ Containers I do see the $web and $log containers but I cannot access them with the following error:
Unable to Load Data Do you want to run some check to detect common connectivity issues? Running Perform-Self-Diagnostics shows all is okay:
{
	"browserInfo": {
		"success": true,
		"details": {
			"browserName": "Google Chrome",
			"OSName": "Windows",
			"userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
		}
	},
	"fetchManifest": {
		"success": true,
		"status": 200,
		"statusText": "",
		"details": "Manifest was successfully retrieved with a status of 200. Cosmos DB is available."
	},
	"clientSideDependencyEndpoints": {
		"success": true,
		"details": [
			{
				"name": "Hosting Service: https://hosting.portal.azure.net/",
				"uri": "https://hosting.portal.azure.net/api/ping",
				"status": 200,
				"statusText": ""
			},
			{
				"name": "Hosting Service: https://hosting.portal.azure.net/",
				"uri": "https://hosting.portal.azure.net/api/ping",
				"status": 200,
				"statusText": ""
			},
			{
				"name": "Third Party Hosting Service",
				"uri": "https://hosting.partners.azure.net/api/ping",
				"status": 200,
				"statusText": ""
			},
			{
				"name": "Azure Resource Manager",
				"uri": "https://management.azure.com/healthcheck?api-version=2014-04-01",
				"status": 200,
				"statusText": ""
			},
			{
				"name": "Hosting Service: https://ms.hosting.portal.azure.net/",
				"uri": "https://ms.hosting.portal.azure.net/api/ping",
				"status": 200,
				"statusText": ""
			},
			{
				"name": "React View",
				"uri": "https://reactblade.portal.azure.net/api/ping",
				"status": 204,
				"statusText": ""
			},
			{
				"name": "Hosting Service: https://hosting-ms.portal.azure.net/",
				"uri": "https://hosting-ms.portal.azure.net/api/ping",
				"status": 200,
				"statusText": ""
			},
			{
				"name": "Hosting Service: https://hosting-ms.portal.azure.net/",
				"uri": "https://hosting-ms.portal.azure.net/api/ping",
				"status": 200,
				"statusText": ""
			}
		]
	},
	"serviceHealthEndpoints": {
		"success": true,
		"details": [
			{
				"name": "Azure Resource Manager",
				"uri": "https://management.azure.com/healthcheck?api-version=2014-04-01",
				"status": 200,
				"statusText": "OK"
			},
			{
				"name": "Microsoft Graph",
				"uri": "https://graph.microsoft.com/v1.0/$metadata",
				"status": 200,
				"statusText": "OK"
			},
			{
				"name": "Insights",
				"uri": "https://insights1.exp.azure.com/",
				"status": 200,
				"statusText": "OK"
			},
			{
				"name": "Graph",
				"uri": "https://graph.windows.net/v1.0/$metadata",
				"status": 200,
				"statusText": "OK"
			},
			{
				"name": "Azure Active Directory",
				"uri": "https://login.microsoftonline.com/",
				"status": 200,
				"statusText": "OK"
			},
			{
				"name": "Azure Email Orchestration",
				"uri": "https://emails-stable.azure.net/",
				"status": 200,
				"statusText": "OK"
			}
		]
	},
	"loadIFrame": {
		"success": true,
		"details": "Loading an iframe was successful."
	},
	"localStorage": {
		"success": true,
		"details": "Read/write to storage was successful."
	},
	"sessionStorage": {
		"success": true,
		"details": "Read/write to storage was successful."
	},
	"webWorkers": {
		"success": true,
		"details": "All web workers responded successfully."
	},
	"requestBodyPersistence": {
		"success": true,
		"details": "Request body was not stripped while making a POST request to the server."
	},
	"cookiePersistence": {
		"success": true,
		"details": "Cookies were received by server and not stripped during request."
	}
}

**Comment by JasonYeMSFT** [comment]
@burningchrome7 Could you please open a support ticket on Azure Portal? Since you have connection issue in both Storage Explorer and Portal, there is a chance the root cause is a backend service issue.

**Comment by burningchrome7** [comment]
Hi Jason,

I opened a ticket this morning.

Thanks,

Brian
