### ISSUE TITLE
Search and Filter needs work

### ISSUE THREAD

**Issue by RolandoAvila** [Microsoft/AzureStorageExplorer#7895]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Every grid and list doesn't default to most recent and most can't search

### Desired Solution

Every list no matter in menu or grid should be defaulted to most recent. I should also be able to do a quick search in that list to filter what I want. Multi select file share would be ideal.

### Alternatives and Workarounds

None only one at a time.

### Additional Context

Apply to any list or grid as a rule of thumb.

**Comment by JasonYeMSFT** [comment]
@RolandoAvila Could you please elaborate on which part of Storage Explorer do you refer to as "grid" and "list"? Could you please also describe the desirable behavior of a few scenarios as examples for us?

**Comment by RolandoAvila** [comment]
One example is navigating through the FileShares from the explorer. Unfortunately this is the only way to navigate through files. If I have a long list of files I have a hard time with this feature. The list by default display from oldest to newest. This feature should allow me to sort by something or at least display the list of files in the tab (on the right) so I can work with them like I can with Container or Queue items.

**Comment by RolandoAvila** [comment]
Sorry about the confusion Jason. Yes I was referring to the tree view for file shares. Thanks for letting me know about the View All feature. I will see how I can upvote it.
