### ISSUE TITLE
Unable to delete or detach unwanted local storage

### ISSUE THREAD

**Issue by khandelwalvikas** [microsoft/AzureStorageExplorer#7896]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.22.0

### Regression From

NA

### Architecture

arm64

### Storage Explorer Build Number

20211211.10

### Platform

macOS

### OS Version

macOS

### Bug Description

I have a local storage account that needs to be removed but I do not see any option to remove it. I tried Detach but that throw the error. See the screencast for more details.

https://somup.com/cZf0nFCSaB

### Steps to Reproduce

See video: https://somup.com/cZf0nFCSaB

### Actual Experience

It is not blocking me but I just want to remove whatever does not exist anymoreremove

### Expected Experience

I should be able to detach to remove the unwanted local storage

### Additional Context

https://somup.com/cZf0nFCSaB

**Comment by JasonYeMSFT** [comment]
@khandelwalvikas 1.22.0 is old and we have stopped supporting that version. You should consider upgrading to the latest version if possible. 

But before that, you can mitigate your local storage issue by manually deleting the reference of those attachments. StorageExplorer's local attachments are stored in this way. There is an array storing the records of the local attachments in the app's local storage. For each record, there is an entry in your OS credential manager (Credential Manager on Windows, KeyChain Access on Mac, libsecret on Linux). You can manually delete them as you wish. You just need to make sure that after your manual manipulation, the record array in local storage matches the data stored in the OS credential manager. You can refer to this [doc](https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/blobs/alerts/storage-explorer-troubleshooting?tabs=Windows#error-occurred-while-adding-new-connection-typeerror-cannot-read-property-version-of-undefined) on how to manage those data.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. This issue will no longer be monitored. If you need further help, we recommend opening a support ticket via the Azure portal. Alternatively you can open a new issue here.
