### ISSUE TITLE
It is better to mention skipped files in the activity log if the upload contains files that have been deleted

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7900]
**Storage Explorer Version**: 1.34.0-dev (98)
**Build Number**: 20240425.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.4.1(Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Click 'Upload -> Upload Files...'.
3. Select two files -> Then delete one file from the destination.
4. Click 'Upload' on the 'Upload Files' dialog -> Observe the activity log.
5. Check whether it is mentioned that 1 file has been skipped.

## Expected Experience ##
It would be better to mention that 1 file has been skipped.

## Actual Experience ##
No skipped file is mentioned in the activity log.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/31cc1d94-f40a-4dc3-befc-193654389197)

**Comment by craxal** [comment]
AzCopy does not report the deleted file as skipped. It only seems to acknowledge the remaining file. Therefore, unless AzCopy actually reports these as skipped, Storage can't report it in the activity log.

I feel like this is a very fringe edge case; I don't expect users to run into the situation where they're trying to upload a file that's been deleted very often, even if they are uploading many files.
