### ISSUE TITLE
The column order of the original tab changes when dragging and dropping one column header from a split tab to the original tab

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7907]
**Storage Explorer Version**: 1.34.0-dev (98)
**Build Number**: 20240426.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.4.1(Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob -> Split the blob container tab.
3. Go to the split tab -> Drag one column header and drop it to the original tab.
4. Check the column order of the original tab doesn't change.

## Expected Experience ##
The column order of the original tab doesn't change.

## Actual Experience ##
The column order of the original tab changes.

## Additional Context ##
1. This issue also reproduces for different services between the split view and the original view
2. Here is the record:
![0425](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/0802bb4a-4af8-4509-a9f0-a61a893e984e)

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240428.1. Reproduce.

**Comment by craxal** [comment]
@v-xianya We now disallow dropping columns outside of the explorer they're from. The merged changes were in a separate package, hence we moved this to "Verifying" and did not yet close the issue. The changes have now been integrated.

**Comment by v-xianya** [comment]
Verified this issue on the rel build 20240506.3. Fixed.
