### ISSUE TITLE
I cannot access to the azure blob storage through azure storage explorer at the company network 

### ISSUE THREAD

**Issue by lwzhang6** [microsoft/AzureStorageExplorer#7908]
My Azure resource was hosted in europe. I am physically located in USA. I am trying to access to the azure datalake/Blob storage, I have issue in accessing to it. it shows the error: 

Unable to retrieve child resources

ProducerError:{
  "name": "Electron Net Error",
  "message": "{\"name\":\"Electron Net Error\",\"cause\":{}}"
}

Can you give suggestion on how to fix the issue as soon as possible ?

**Comment by craxal** [comment]
@lwzhang6 What platform are you running on? What version of Storage Explorer are you using? Please refer to our [issue template](https://github.com/microsoft/AzureStorageExplorer/issues/new?assignees=&labels=&projects=&template=bug_report.yml) for information we usually need to help diagnose problems.

Here are some additional questions:

1. When you say "Azure Datalake/Blob Storage", are you referring to ADLS Gen1 or Gen2? If Gen1, you should know that those services have been retired, and Gen1 functionality has been removed from Storage Explorer.

2. Assuming Gen2, how are you setting up your connection to the blob container? Are you:
   - Signing in?
   - Connecting to an account using name and key or connection string?
   - Connecting directly to the container by signing in?
   - Connecting directly to the container using a SAS URL?

3. If you are signing in, do you have the necessary RBAC permissions to list or read the necessary objects (see out [troubleshooting guide](https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/blobs/alerts/storage-explorer-troubleshooting?tabs=Windows#azure-rbac-permissions-issues)). 

4. Are you expected to connect through a proxy server? Have you configured Storage Explorer to use that proxy (ideally by setting **Proxy > Proxy Configuration** to "Use system proxy")?

5. Can you please provide any [app logs](https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/blobs/alerts/storage-explorer-troubleshooting?tabs=Windows#gather-logs) to help us further diagnose the issue?

**Comment by lwzhang6** [comment]
My azure cloud administration colleague asigned me as the following in the azure:
Resource - reader
storage blob data - contributor

Would it be correct configuration?

**Comment by lwzhang6** [comment]
to answer question 3
My azure cloud administration colleague asigned me as the following in the azure:
Resource - reader
resource group -reader

storage blob data - contributor

Would it be correct configuration?

**Comment by craxal** [comment]
I think those permissions should be sufficient, though it depends on what level they are available. You can check these permissions yourself, as well, from the Azure portal and clicking on "Access Control (IAM)" on the blade for the storage account you're attempting to access. Typically, you need the Reader role set at the subscription level to list storage accounts and Storage Blob Data Contributor set at the account level.

If you follow the link I provided above, you'll find clear instructions on how to gather app logs. Just select **Help > Open Logs Directory** from the menu, create a zip file from the appropriate session folder, and attach it here.

And please do let us know what platform you're on, what version of Storage Explorer you're using, etc.

**Comment by lwzhang6** [comment]
it is windows 10 enterprise computer
MS azure storage explorer - version 1.33.1; azcopy version 10.23.0
![image](https://github.com/microsoft/AzureStorageExplorer/assets/44276489/60939679-5f3f-4799-b54d-2b645905bff9)

**Comment by lwzhang6** [comment]
[logs.zip](https://github.com/microsoft/AzureStorageExplorer/files/15134736/logs.zip)
I uploaded the zip. Can you please help?

**Comment by craxal** [comment]
You shared the authentication logs. Can you also share the app logs, please?

Also, are you able to view the resources you need from the Azure portal? That is, can you see a list of the contents of the blob container you are trying to access using the **Data Storage > Containers** item in the storage account blade? Doing this should help us narrow down whether this is a Storage Explorer or an Azure issue.

**Comment by lwzhang6** [comment]
how to get app logs?
In the azure Data Storage > Containers, I can see a list of the folders of the blob containers. But, clicking any of the folders does not work. I am able to see the folders, but can not get into it.

**Comment by lwzhang6** [comment]
[2024-04-26_094749.zip](https://github.com/microsoft/AzureStorageExplorer/files/15135244/2024-04-26_094749.zip)

**Comment by lwzhang6** [comment]
i uploaded the app logs. may you please have a look? thanks

**Comment by craxal** [comment]
I'm seeing two errors, which might be related. The first is a connection timeout error, and the second is a "no suitable credentials" error related to listing file shares. I suspect Azure may be having a hard time authenticating your connection. Or it could be requests aren't making it to Azure (possibly blocked by the proxy?).

Can you share any details about the storage account you're trying to connect to? For example, is a blob-only storage account (for example, premium)?

When did you sign in? Have you tried removing your account and signing back in?

One way to work around this while we're trying to find a solution: Could someone provide a SAS URL for you to use temporarily? If that works, then it's definitely a sign-in related issue.

**Comment by lwzhang6** [comment]
Could you please give your offical microsoft account for me to connect you directly by email for this issue related to Azure? OR directly drop me an issue?

Regarding the proxy issue, can you suggest how I fix it? I have the company proxy info and do not know how to figure it. also which IP address or web link I should request unblock? THANK YOU very much for your help

**Comment by MRayermannMSFT** [comment]
@lwzhang6 it sounds like you have quite a bit unique network constraints going on here. At this point I would recommend you open an Azure support ticket via the portal.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/21112697/d30079dd-475e-4211-a74a-805c42ef78ca)
