### ISSUE TITLE
The behavior is inconsistent if press Ctrl+A in different service explorers

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7911]
**Storage Explorer Version:** 1.34.0-dev (98)
**Build Number:** 20240428.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.4.1(Apple M1 Pro)
**Architecture:** x64/x64/arm64
**How Found:** Ad-hoc testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Open one blob container which contains more than 100 blobs.
3. Press Ctrl+A -> Observe the selected blobs.
4. Open one table which contains more than 100 entities.
5. Press Ctrl+A -> Observe the selected entities.
6. Check whether the behavior is consistent.

## Expected Experience ##
The behavior is consistent.

## Actual Experience ##
The behavior is inconsistent.

1. For blobs, only the blobs in this page are selected.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/d1702854-fcd9-45a5-9c0a-20a5d8abcf7a)
2. For entities, all entities can be cached are selected.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/e9415f02-3ed7-4fa3-9370-e786c015a725)

## Additional Context ##
For files, all files can be cached are selected.

**Comment by craxal** [comment]
The managed disks explorer also only selects the items in the page.

Considering that selecting all in the page is the default command for the toolbar, the keyboard shortcut should do likewise.

I think it also makes sense for there to be a keyboard shortcut for selecting all cached items as well. Ctrl/Cmd+Shift+A seems reasonable.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240506.3. Fixed. 
For all services, only items in this page are selected if press Ctrl+A.
