### ISSUE TITLE
The columns order is inconsistent between the original and split tab if the columns order in the original is not default for view containers tab

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7912]
**Storage Explorer Version**: 1.34.0-dev (98)
**Build Number**: 20240428.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.4.1(Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Click 'View all' -> Drag the 'Last Modified' column and drop it as the first column.
3. Split the view all containers tab.
4. Check whether the columns order is consistent between the two tabs.

## Expected Experience ##
The columns order is consistent between the two tabs.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/597d0add-eaf6-48bb-ba84-e8c4b1957fbb)

## Actual Experience ##
The columns order is inconsistent between the two tabs.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/589dfa28-c91d-47fb-9686-e1b9c09ed1a2)

**Comment by MRayermannMSFT** [comment]
Unsure if this is by design. Seems like it shouldn't be since custom column order is persisted. @craxal can you find a happy conclusion to this either way?

**Comment by craxal** [comment]
Blob container explorer columns aren't persisted at all.

**Comment by v-xianya** [comment]
Verified this issue on the rel build 20240506.3. Fixed.
