### ISSUE TITLE
Not able to view data from CosmosDB Azure portal.

### ISSUE THREAD

**Issue by sureshmallurik** [microsoft/AzureStorageExplorer#7915]
Azure portal Cosmos DB(Table API) data explorer does not show any data. We Inserted data via Databricks and able to retrieve the same via databricks.
But when try to take a look at the data, we dont see any data in Azure portal.

Tried to insert data manually from the portal and it is visible.

**Comment by MRayermannMSFT** [comment]
Hi @sureshmallurik , for issues with the Azure Portal please open an Azure support ticket.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/21112697/ab1dda9e-ba81-4cff-a13a-5f9e9267d149)
