### ISSUE TITLE
It would be better to update 'Copy Rows' to 'Copy Rows with Heads' for tabular data

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7919]
**Storage Explorer Version**: 1.34.0-dev (98)
**Build Number**: 20240506.3
**Branch**: rel/1.34.0
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.4.1(Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Add one entity.
3. Right click the entity -> Click 'Copy Rows'.
4. Paste the rows to a text -> Observe the pasted content.
5. Include the headers in the pasted content.

## Expected Experience ##
It would be better to update 'Copy Rows' to 'Copy Rows with Headers'.

## Actual Experience ##
It displays 'Copy Rows'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/eb4612df-fabd-4d0f-8a10-167a33f64800)

**Comment by craxal** [comment]
It is a normal expectation for headers to come with tabular data. We don't need to make this explicitly known.
