### ISSUE TITLE
Sign-in Error "The SSL connection could not be established, see inner exception"

### ISSUE THREAD

**Issue by 0anton** [microsoft/AzureStorageExplorer#7920]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.33.1 (98)

### Regression From

1.32.1 

### Architecture

i86

### Storage Explorer Build Number

20240410.2

### Platform

Windows

### OS Version

Windows 11

### Bug Description

Suddenly, SE fails to log me in in to Azure account throwing the error:

```
{
  "message": "\"The SSL connection could not be established, see inner exception.\""
}
```

### Steps to Reproduce

1. Launch SE
2. Click "Sign in with Azure"
3. In "Select Azure Environment" to "Azure"
4. Click "Next" to start the browser authentication flow.
5. Error "Unable to sign in: The SSL connection could not be established, see inner exception." appears.

### Actual Experience

![image](https://github.com/microsoft/AzureStorageExplorer/assets/17309924/aa60e5c4-d2fd-45ac-bd34-529b15654d46)

### Expected Experience

After the browser authentication flow has completed, the SE lists the available Azure subscribtions.

### Additional Context

Nothing unusual. It just stopped working.
I still can access the same Blob Storage from CLI (`az storage blob ..`) using the same user and the same machine.

It is related to https://github.com/microsoft/AzureStorageExplorer/issues/7593, but the latter does not provide the solution or provides an obscure recommendation by the author.

**Comment by MRayermannMSFT** [comment]
> It is related to https://github.com/microsoft/AzureStorageExplorer/issues/7593, but the latter does not provide the solution or provides an obscure recommendation by the author.

Did you try the solution suggested in the final comment?

**Comment by MRayermannMSFT** [comment]
@0anton given that what the user user did worked, I would recommend that you try it as well.

**Comment by prafulbusa** [comment]
I have exact same issue and as a MS internal I am not able to use many tools that requires to have SSL Secure tunnel connection to remote host. CaseBuddy, OofSponder, SA, Kusto, and some more have exact same issue. 
Not even able to RDP to Azure machine, not sure if this is related to that.

**Comment by 0anton** [comment]
@prafulbusa method (extending the list of allowed protocols didn't work for me.

Still getting:
```
{
  "message": "\"The SSL connection could not be established, see inner exception.\""
}
```

I've just restarted the app. Did you reboot the PC to apply new SSL configs?

**Comment by 0anton** [comment]
@MRayermannMSFT is it possible you extend the error message to include the _inner exception_, so I have hints why the SSL connection originating from Azure Storage Explorer got dropped?

**Comment by MRayermannMSFT** [comment]
@0anton can you try following these steps to get a hold of your authentication logs?

https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/blobs/alerts/storage-explorer-troubleshooting?tabs=Windows#authentication-logs

Those logs may have the inner exception, if they don't then please share the logs here so I can share with the team responsible for surfacing the inner exception. Also, please follow the recommended step of clearing out the existing logs before gathering the fresh set. Thanks.

**Comment by victor-miranda-komatsu** [comment]
I faced the same issue today.

BTW, I'm behind the company VPN. It worked after disconnecting the VPN.

My logfiles are attached anyway.

[ServiceHub.zip](https://github.com/microsoft/AzureStorageExplorer/files/15489621/ServiceHub.zip)

**Comment by craxal** [comment]
@MRayermannMSFT Take a look at the logs and see what can be done.

**Comment by 0anton** [comment]
Trying to open Azure Support request as direct on the home page. Still not working, tried disabling FW, enabling additional ssl ciphers... No avail

**Comment by craxal** [comment]
@0anton It has been suggested that you try Wireshark instead of Fiddler, as it is better at diagnosing SSL issues.

Here are some links that may also be helpful:
- https://dev.azure.com/VS-Languages-Training-Path/Training/_wiki/wikis/Test.wiki/104/SSL-issues
- https://dev.azure.com/VS-Languages-Training-Path/Training/_wiki/wikis/Test.wiki/14/TLS-1.2-TLS-1.3-detection-script-for-VS-Sign-in(by-Chris-Mann)

**Comment by 0anton** [comment]
Thanks @craxal, @MRayermannMSFT for hints!

Somehow it started working.

I believe allowing again ciphers
```
RSAE-PSS/SHA256
RSAE-PSS/SHA384
RSAE-PSS/SHA512
```
by adding them at the top of the `Functions` in the registry key `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Cryptography\Configuration\Local\SSL\00010003\ ` and **rebooting** the host did the trick.

That's the same what @prafulbusa suggested and also https://github.com/microsoft/AzureStorageExplorer/issues/7593

Will observer and closing for now.
