### ISSUE TITLE
Update the month in release note from 'March' to 'May'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7921]
**Storage Explorer Version**: 1.34.0-dev (98)
**Build Number**: 20240507.1
**Branch**: rel/1.34.0
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.4.1(Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Open Storage Explorer -> Click 'Help -> Release Notes'.
2. Observe the month in the release notes.
3. Check whether it displays a correct month.

## Expected Experience ##
It displays 'May'.

## Actual Experience ##
It displays 'March'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/133a3ff8-dbee-473a-b125-77134f68d822)

**Comment by MRayermannMSFT** [comment]
😅

**Comment by v-xianya** [comment]
Verified this issue on the build 20240508.1. Fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/a112d4ea-b826-4d16-824e-19f650833e9f)
