### ISSUE TITLE
It navigates to an incorrect page after clicking 'here' on 'Release Note -> Windows ARM64 Preview' part

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7922]
**Storage Explorer Version:** 1.34.0-dev (98)
**Build Number:** 20240507.1
**Branch:** rel/1.34.0
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.4.1(Apple M1 Pro)
**Architecture:** x64/x64/arm64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Open 'Release Notes' -> Go to 'Windows ARM64 Preview' part.
2. Click the hyperlink 'here'.
3. Check whether navigates to the correct page.

## Expected Experience ##
Navigate to the correct page.

## Actual Experience ##
Navigate to below page.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/07527b0d-e86e-49ff-95bc-0ba2af27d41c)

**Comment by MRayermannMSFT** [comment]
This link will not be setup to work properly until right as we are releasing.

**Comment by MRayermannMSFT** [comment]
I've pre set the fwd link to go to `https://github.com/microsoft/AzureStorageExplorer/releases/download/v1.34.0/StorageExplorer-windows-arm64.exe`. It 404's right now, but will later not. Closing this.
