### ISSUE TITLE
The status message is selected instead of all rows if select one row then press Ctrl+A on the previewed tab of tabular data

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7924]
**Storage Explorer Version**: 1.34.0-dev (98)
**Build Number**: 20240508.1
**Branch**: rel/1.34.0
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.4.1(Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Upload one .parquet file -> Preview it.
3. Select one row -> Press Ctrl+A.
4. Check whether all rows are selected. 

## Expected Experience ##
All rows are selected. 

## Actual Experience ##
The status message is selected.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/400f2365-7c6a-4db5-a429-80e8830ce76a)

**Comment by craxal** [comment]
Correct, we have not added keyboard shortcuts to select all rows in preview.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240526.2. Fixed. So, we are going to close it.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/bdd81819-47b5-40b6-8df5-c21901583bdc)
