### ISSUE TITLE
"View all" under Container tree view opens new tab.

### ISSUE THREAD

**Issue by joelcochran-causeway** [microsoft/AzureStorageExplorer#7926]
This used to be "Load more" or "Show more" (I don't recall) and expanded the list in the Tree view. Now it opens a new tab, and if you select a container in the new tab it opens a parallel tab alongside the container tab.

I spend a lot of time in Storage Explorer working in systems with large numbers of containers and I absolutely HATE this change. It forces me to do more manual tab management and robs me of horizontal space. I can drag the newly opened tab back to the primary tab group on the left, but it opens as a copy so I still have to close the tab on the right.

I'm sure there was a reason for making this change but the prior way was vastly superior. At least please consider making this option configurable.

**Comment by craxal** [comment]
@joelcochran-causeway You're absolutely right, and fortunately, it _is_ an option. Open Settings and change **Services > Storage Nodes Trailing Action** to "Load more" to restore the original behavior. Let us know if that works for you.

For reference. This functionality was added in response to other users who work with a lot of different containers and listing the first so-many items was tedious for them. Storage Explorer automatically set this setting to enable "View all" to increase visibility and get earlier feedback. Apologies if this interrupted your normal workflow.

**Comment by joelcochran-causeway** [comment]
That worked great - Thank you!!!

--
Joel Cochran
VP of Technology
Causeway Solutions
***@***.******@***.***>
540.255.8340
