### ISSUE TITLE
Unable to retrieve child resources.  Details: getaddrinfo ENOTFOUND azcaccmsprd02cos01.documents.azure.com

### ISSUE THREAD

**Issue by Aswindel** [microsoft/AzureStorageExplorer#7927]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.17.0

### Architecture

x64

### Platform

Windows

### Bug Description

Unable to retrieve child resources.

Details:
getaddrinfo ENOTFOUND azcaccmsprd02cos01.documents.azure.com

### Steps to Reproduce

![image](https://github.com/microsoft/AzureStorageExplorer/assets/169488124/4798159e-bfcb-4a19-bf09-a8aafa17145b)
![error](https://github.com/microsoft/AzureStorageExplorer/assets/169488124/798c09ff-353f-49f2-b7b7-8620a141e96e)

### Actual Experience

![error](https://github.com/microsoft/AzureStorageExplorer/assets/169488124/30cd8f7a-c3df-4e35-97d6-0a23a2c88928)

Couldnt access the Cosmo db throws error as attached in screenshot

**Comment by craxal** [comment]
@Aswindel CosmosDB is no longer supported in Storage Explorer (see https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.22.0).

[Azure CosmosDB Explorer](https://cosmos.azure.com/) is a separate tool that you can use (see also https://learn.microsoft.com/en-us/azure/cosmos-db/data-explorer).
