### ISSUE TITLE
File Size Discrepancy

### ISSUE THREAD

**Issue by AquickCCBCC** [microsoft/AzureStorageExplorer#793]
**Storage Explorer Version**:  Version 1.4.2
**Platform/OS Version**:  Windows 7 ent
**Architecture**:  ia32
**Regression From**:  

#### Steps to Reproduce: ####
1.  Check file size in main window and crosscheck with file size in file properties.

2. 
The file size shown on in the main window does not match the file size shown in the properties window.

**Comment by AquickCCBCC** [comment]
I realized where the discrepancy comes from. 
This is the age old 1,000 vs 1,024 debate.

**Comment by MRayermannMSFT** [comment]
Sounds like you solved the issue on your own. Closing. Please open a new issue if you're still having problems.
