### ISSUE TITLE
Write release notes & update version numbers for 1.35.0

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#7933]
- Write release notes
- Include at least one or two screenshots or gifs to enhance presentation of new features (if warranted)
- Make sure all version numbers are correct (package.json (both version and intVersion), package-lock.json, snap.yaml)
- Refer to old release notes to help maintain consistentcy in style/organization/content

Helpful queries:
- [Feature Request Issues](https://github.com/microsoft/AzureStorageExplorer/issues?q=is%3Aissue+milestone%3A1.35.0+-label%3A%22%3Atest_tube%3A+engineering%22+label%3A%22%3Abulb%3A+feature+request%22+-label%3A%22%F0%9F%93%8B+feedback+wanted%22+-label%3A%22%F0%9F%A7%AA+testing%22+-label%3A%22%3Abeetle%3A+bug%22+-label%3A%22%3Awhite_check_mark%3A+won%27t+fix%22+-label%3A%22%3Abeetle%3A+regression%22+-label%3A%22%3Aclipboard%3A+feedback+wanted%22+)
- [Engineering Issues](https://github.com/microsoft/AzureStorageExplorer/issues?q=is%3Aissue+milestone%3A1.34.0+label%3A%22%3Atest_tube%3A+engineering%22+-label%3A%22%3Abulb%3A+feature+request%22+-label%3A%22%F0%9F%93%8B+feedback+wanted%22+-label%3A%22%F0%9F%A7%AA+testing%22+-label%3A%22%3Abeetle%3A+bug%22+-label%3A%22%3Awhite_check_mark%3A+won%27t+fix%22+-label%3A%22%3Abeetle%3A+regression%22+-label%3A%22%3Aclipboard%3A+feedback+wanted%22+) (look for engineering issues that are notable to users, ex: Electron updates, new major .NET versions, etc.)

**Comment by craxal** [comment]
Make sure Electron Update notes refer to v30.
