### ISSUE TITLE
Failure trying to delete managed disk (already deleting)

### ISSUE THREAD

**Issue by DavidBerg-MSFT** [microsoft/AzureStorageExplorer#7937]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.31.1

### Architecture

x64

### Storage Explorer Build Number

20230822.1

### Platform

Windows

### OS Version

Windows 11

### Bug Description

I'm getting a failure trying to delete a managed disk.  I know this disk's state is already "deleting" but it's been in that state for days...  I'm trying to find the underlying issue and resolve it. It might be lease related, but there's nothing I can find to let me view or break the lease on a managed disk in deleting state...

Here's the error I'm getting (which isn't very informative, same error on latest version, 1.33.1): 

> Storage Explorer encountered an error when attempting to delete disk 'armp230902215256s201c3i44_OsDisk_1_8355d72a7ade40c19009fc845c23d7bf' in resource group 'rg-gartner-perf-eastus-linux_u1000_arm_private_ip10xDsv5U22.04230902215249'

```json
{
  "name": "Error",
  "message": "The long-running operation has failed",
  "stack": "Error: The long-running operation has failed\n    at processOperationStatus (C:\\Users\\davberg\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\managed-disks-extension\\dist\\src\\index.js:2:828733)\n    at pollOperation (C:\\Users\\davberg\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\managed-disks-extension\\dist\\src\\index.js:2:830660)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async GenericPollOperation.update (C:\\Users\\davberg\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\managed-disks-extension\\dist\\src\\index.js:2:301433)\n    at async LroEngine.pollOnce (C:\\Users\\davberg\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\managed-disks-extension\\dist\\src\\index.js:2:302681)"
}
```

### Steps to Reproduce

1. Try to delete a managed disk that's already stuck in the deleting state.
2. Try to check the lease status or break the lease for a managed disk (stuck in the deleting state) - I couldn't find an option for this.

### Actual Experience

See error message in bug description.

### Expected Experience

Either:
1) No failure, disk deletes.
2) Better error message on why disk won't delete.
3) Ability to check managed disk lease status and break it so I can retry delete.

**Comment by MRayermannMSFT** [comment]
Reaching out internally...
