### ISSUE TITLE
It displays 'Folder is Empty' instead of selecting the azcopy log file when clicking 'Go to AzCopy Log File' for storage explorer installed by snap

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7939]
**Storage Explorer Version**: 1.34.0 (99)
**Build Number**: 20240515.2
**Branch**: rel/1.34.0
**Platform/OS**: Linux Ubuntu 22.04
**Architecture**: x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch storage explorer that is installed by snap.
2. Expand one storage account -> Blob Containers.
3. Create a blob container -> Upload one blob.
4. Select the blob -> Click 'Copy' -> Click 'Paste'.
5. There is a failed activity log -> Click 'Go to AzCopy Log File' next to the failed activity log.
6. Check whether the AzCopy log file is selected.

## Expected Experience ##
The AzCopy log file is selected.

The screenshot of .tar storage explorer.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/9dd7a957-4b10-4516-9f48-bfa52f8de449)

## Actual Experience ##
It displays 'Folder is Empty'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/eb076467-13df-43e7-b122-7961407ca57c)

**Comment by richardMSFT** [comment]
Hi @v-xianya, I tried reproducing this bug following the exact same steps but I am getting the expected experience. I double checked and am running the same build on the same platform. 

When I click on 'Go to AzCopy Log File', the file explorer opens up to the `Home/snap/storage-explorer/x1/.azcopy` directory with the log file selected.

**Comment by v-xianya** [comment]
Hi @richardMSFT Thank you for the confirmation. This issue still reproduce on my side. here is the record. I will share the repro vm on teams.
![0517](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/fd4a592a-ebe9-4d1d-b93c-db938f00a296)

**Comment by richardMSFT** [comment]
After investigation, this seems to be an electron bug with `showItemInFolder`. I've opened up an issue with electron here: https://github.com/electron/electron/issues/42251

**Comment by craxal** [comment]
Same root cause as #5363. File dialogs won't open to any subdirectories within the user's home directory for some reason when run as a snap. Let's use the existing issue to track.
