### ISSUE TITLE
Latest azurestorage explorer doesnot open when icon is clicked after install in win7 

### ISSUE THREAD

**Issue by razaaalirizvi** [microsoft/AzureStorageExplorer#794]
**Storage Explorer Version**: 
**Platform/OS Version**: 
**Architecture**: 
**Regression From**: 

#### Steps to Reproduce: ####
1. 
2.

**Comment by MRayermannMSFT** [comment]
@razaaalirizvi are you still having issues with the latest issue of Storage Explore (1.12.0)?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
