### ISSUE TITLE
From CSS: Make it harder to trigger a priority archive rehydration/retrieval

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#7940]
CSS gave feedback that it is very easy for customers to do a priority archive rehydration/retrieval acceidentally. This is not good, because doing so is higher cost. Perhaps there should be a bit of confirmation-friction when that choice is selected?

**Comment by JasonYeMSFT** [comment]
Here is the proposed way to mitigate this issue.

When the higher priority is selected, show a checkbox element below it asking if the user really meant to use the higher priority. Don't allow the user to submit from the dialog if the higher priority is selected and the checkbox isn't checked.

**Comment by JasonYeMSFT** [comment]
I cannot reproduce this issue. Even if I have focus on the dropdown menu, I cannot change the selected option by scrolling with my mouse.

**Comment by JasonYeMSFT** [comment]
Talked to the CSS team offline. They cannot reproduce the wheel button. This is just about "making it harder to rehydrate stuff using high priority.".
