### ISSUE TITLE
Downloading blob file takes huge time and downloaded file is appended multiple times

### ISSUE THREAD

**Issue by ameyvaidya** [microsoft/AzureStorageExplorer#795]
**Storage Explorer Version**:1.4.4 

**Platform/OS Version**:  Windows 10 latest update as of this post
**Architecture**: 64bit
**Regression From**: 0.9.6

#### Steps to Reproduce: ####
1. Open blob
2. Download file

We use blob to store our application logs. So each request we receive on our API, our code create file for that day 2018-10-24_Info.txt.
Once that done we append incoming request data like ip address, requested URL, headers etc with date and time entry.
So for every new request we keep appending log at the end of txt file.

What I observed:
1. Even 10 MB files takes a lot of time and when downloaded it goes around 40,50 or even as high as 80 MB.
2. After examining content of file we saw that some entries were appearing again and again with same timestamp. Each entry in log file has unique timestamp.
3. When download file from blob it somehow keep appending file again and again.

#### Expected Experience: ####
1. Downloading file should not take long time. For 10MB file with 50 MBPS internet speed it is taking ridiculous amount of time. Plus full bandwidth is not being utilized.
2. File size should be the same as shown in blob container

#### Actual Experience: ####
1. Downloading file taking long time. For 10MB file with 50 MBPS internet speed it is taking ridiculous amount of time.
2. File size is utterly high.

**Comment by ameyvaidya** [comment]
File size in Blob storage: 16 MB
![image](https://user-images.githubusercontent.com/5148671/47426618-53328780-d7ab-11e8-84e1-302d713544e0.png)

Still downloading: 
Download started from: 4:33 PM IST
Partial size is way more than original

![image](https://user-images.githubusercontent.com/5148671/47426676-7b21eb00-d7ab-11e8-89f8-9e86b5a9237a.png)

Entries are getting appended: Searching firs entry in notepad++
![image](https://user-images.githubusercontent.com/5148671/47426777-d0f69300-d7ab-11e8-875c-a6622ff652e6.png)

Final file size after downloading:
![image](https://user-images.githubusercontent.com/5148671/47426868-2cc11c00-d7ac-11e8-9088-815fa67d6434.png)

**Comment by MRayermannMSFT** [comment]
@ameyvaidya are you still having issues when using latest storage explorer?

**Comment by ameyvaidya** [comment]
Hi Matthew, It's working perfectly in latest version. Thank you. I'll close the issue.
