### ISSUE TITLE
"Unable to Retrieve Child Resources"

### ISSUE THREAD

**Issue by kinneymic** [microsoft/AzureStorageExplorer#7953]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.33.1

### Regression From

no

### Architecture

x64

### Storage Explorer Build Number

20240410.2

### Platform

Windows

### Bug Description

Our IT recently gave me permissions to an Azure subscription, and further read access to a certain storage account.  When I click on the "File Shares" drop down an error appears.

### Steps to Reproduce

1. Launch Storage Explorer
2. Under desired subscription click on Storage accounts
3. Under desired storage account click on the File Shares drop down
*Error shows up immediately

Unable to retrieve child resources

ProducerError:{
  "name": "Error",
  "message": "Unable to perform operation 'FileServiceClient.listSharesSegment'. No suitable credentials provided.",
  "stack": "Error: Unable to perform operation 'FileServiceClient.listSharesSegment'. No suitable credentials provided.\n    at sl.runOperation (C:\\Users\\z003du2z\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\file-extension\\dist\\src\\index.js:38:5637)\n    at sl.listSharesSegment (C:\\Users\\z003du2z\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\file-extension\\dist\\src\\index.js:56:6448)\n    at FileShareNodeProducer.produceFileShareNodes (C:\\Users\\z003du2z\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\file-extension\\dist\\src\\index.js:56:53842)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Azure.Storage.FileShareProducer.produceFileShareNodes (C:\\Users\\z003du2z\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\file-extension\\dist\\src\\index.js:59:13147)\n    at async Ze.executeOperation (C:\\Users\\z003du2z\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:3:2742)\n    at async Bt._handleExecuteRequest (C:\\Users\\z003du2z\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:7:915)\n    at async Bt._handleMessage (C:\\Users\\z003du2z\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:6:30146)\n    at async C:\\Users\\z003du2z\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:6:27657"
}

### Actual Experience

![image](https://github.com/microsoft/AzureStorageExplorer/assets/170521165/e5bbb3dc-2ed0-4e24-a142-9b1d6b19505a)

### Expected Experience

I expected to see and navigate through the File Share named "airflow-dags" (as illustrated through my SAS connection):

![image](https://github.com/microsoft/AzureStorageExplorer/assets/170521165/99c8af55-2c07-4dd7-b484-ca5d3c75fda7)

**Comment by kinneymic** [comment]
Looks like this was solved internally.  IT figured out the right role for me.

**Comment by dinhe878** [comment]
I encountered the same error while executing different steps:

1. Launch Storage Explorer.
2. Under desired subscription click on a Storage account.
3. Navigate to a blob container.
4. Navigate to a folder in that blob container.
5. Right click while selecting the folder, select "Copy Direct Link".
6. Open a browser and paste the link and enter.
7.  Select "Open Microsoft Azure Storage Explorer".
8. Now redirect to the Microsoft Azure Storage Explorer, with "Open Direct Link" dialog select "Navigate to Container".
9. Quit the Microsoft Azure Storage Explorer app.
10. Re-execute the link in step 6.
11. The identical same error message appears.

**Comment by dinhe878** [comment]
> Looks like this was solved internally. IT figured out the right role for me.

Hi @kinneymic, can you tell me more how did IT fixed your issue?

**Comment by kinneymic** [comment]
> > Looks like this was solved internally. IT figured out the right role for me.
> 
> Hi @kinneymic, can you tell me more how did IT fixed your issue?

They used the "Contributor" role.  But since I am not the owner, they are now creating a custom role for me.  (which is more complicated than I understand)
