### ISSUE TITLE
TableStorage Timestamp shows UTC instead of user's localtime

### ISSUE THREAD

**Issue by Terrence77** [microsoft/AzureStorageExplorer#7954]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.33.1

### Architecture

x64

### Storage Explorer Build Number

20240410.2

### Platform

Windows

### OS Version

win 23h2

### Bug Description

All timestamps are shown in UTC, not converted to local time as I have read in many posts.  
There is no mention of settting timezone or setting how to display times in the help..

### Steps to Reproduce

show a query from tablestorage

### Actual Experience

shows utc time

### Expected Experience

show local time based on user's computer's time Zone, or let me select the time Zone.

### Additional Context

none.

**Comment by craxal** [comment]
@Terrence77 We have implemented this feature, which will be present in 1.37.0!

We added a new setting: **Data Explorers > Table Explorer > DateTime Format** with three options: None, Local, and UTC. When set to Local or UTC, Storage Explorer will format DateTime values using your system format settings in the respective time zone.

Thank you for your feedback! We hope this will meet your needs.

**Comment by Terrence77** [comment]
Great news, thank you for adding this feature.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
