### ISSUE TITLE
Not all tabs are closed if delete one queue with split tabs

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7955]
**Storage Explorer Version**: 1.34.0 (99)
**Build Number**: 20240523.2
**Branch**: rel/1.34.0
**Platform/OS**: Windows 10/Windows 11/Linux Ubuntu 22.04/MacOS Sonoma 14.4.1(Apple M1 Pro)
**Architecture**: x64/arm64/x64/arm64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Queues.
2. Open one queue -> Split the queue tab.
3. Go to the tree view -> Delete the queue.
4. Check whether the two tabs are closed.

## Expected Experience ##
The two tabs are closed.

## Actual Experience ##
Only one tab is closed.

## Additional Context ##
This issue does not reproduce for other three services.

**Comment by craxal** [comment]
This has a different root cause than #8173.

**Comment by craxal** [comment]
The queue explorer manager was not looking at all the arguments it was given, so it was not properly associating one of the split tabs with the node being deleted. This has been fixed.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240920.3. Fixed.
