### ISSUE TITLE
The position of the horizontal scrollbar is incorrect in the 'Column Options' dialog

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7963]
**Storage Explorer Version:** 1.35-dev (98)
**Build Number:** 20240526.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.5(Apple M1 Pro)
**Architecture:** x64/x64/x64
**How Found:** Ad-hoc testing
**Regression From:** Previous release (1.33.1)

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create a table -> Add an entity which has one property name with 255 characters.
3. Open 'Column Options' dialog -> There is a horizontal scrollbar.
4. Check whether the scrollbar is in the 'Available Columns' section.

## Expected Experience ##
The scrollbar is in the 'Available Columns' section.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/41a10965-f41f-47e0-9406-08c8b8e7e9c3)

## Actual Experience ##
The scrollbar is not in the 'Available Columns' section.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/8a4b8631-2aca-447b-8de1-c5371b1fe932)

**Comment by v-xianya** [comment]
@craxal we tried to verify this issue on the main build 20240611.1.
The spacing for the spacing between available columns is too wide. we have opened a new bug [7998](https://github.com/microsoft/AzureStorageExplorer/issues/7998).
we are going to reopen this bug, and verify it once the bug 7998 get fixed.

**Comment by craxal** [comment]
That would a separate issue. The horizontal scroll bar is still has not come back, so I'm closing again.

**Comment by v-kellyluo** [comment]
@craxal , verified this issue on the build 20240612.1, there is no horizontal scrollbar in the 'Available Columns' section, is this by expected?
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/d19ae5ba-2fab-446b-a6a1-68a85471f924)

**Comment by craxal** [comment]
@v-kellyluo Yes, this is expected. It is expected that users with column names that big are very rare. If they do, a tooltip appears when hovering over the column name that shows the full name.
