### ISSUE TITLE
There is an extra 'Target Access Tier' field in the 'Upload Folder/Files' dialog for file shares

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7966]
**Storage Explorer Version:** 1.35.0-dev (98)
**Build Number:** 20240529.1
**Branch:** main
**Platform/OS:** Windows 11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.5(Apple M1 Pro)
**Architecture:** arm64/x64/x64/arm64
**How Found:** From running test cases
**Regression From:** Previous release (1.34.0)

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Click 'Upload -> Upload Folder.../Files...'.
3. Check whether there is no 'Target Access Tier' field.

## Expected Experience ##
There is no 'Target Access Tier' field.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/3f7ab94f-e941-4740-9b04-44e1ffbf5700)

## Actual Experience ##
There is an extra 'Target Access Tier' field.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/52e96ded-b35f-4080-874c-c4e8744a431d)

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240716.5. Fixed. So, we are going to close it.
![image](https://github.com/user-attachments/assets/74e1019f-864b-40e0-9784-8214fbfd99af)

**Comment by v-xianya** [comment]
HI @craxal Yes, a fix has been merged for this bug.
![image](https://github.com/user-attachments/assets/703c7ec5-5421-427b-a2f2-c9be4456b36a)
