### ISSUE TITLE
cannot connect to azure stack using self signed cert

### ISSUE THREAD

**Issue by lucidqdreams** [microsoft/AzureStorageExplorer#797]
**Storage Explorer Version**: 
**Platform/OS Version**: 
**Architecture**: 
**Regression From**: 

#### Steps to Reproduce: ####
1. import self signed azure stack AAD cert
2. select target azure stack
3. restart program
4. you try and connect to the endpoint.  It doesn't even try.

if you try to you a connection string, it gives a cert err, and if you try and connect to a azure stack instance with a trusted certificate from global CAs you get a login prompt. 

this app does not work with azure stack self signed or I suspect an enterprise signed certificates. (which it should)

#### Expected Experience: ####
to be consistent, If I choose to use a self signed cert that is my choice and the program should work

#### Actual Experience: ####
with the connection, there is no useful error at all, using a connection string it at least popups 

![image](https://user-images.githubusercontent.com/6086602/47458915-aeef1780-d78f-11e8-8f4f-655bc88e55fe.png)

![image](https://user-images.githubusercontent.com/6086602/47458986-d3e38a80-d78f-11e8-8c57-b45bfe8ed388.png)

**Comment by MRayermannMSFT** [comment]
@ucidqdreams are you still having issues with the latest version of Storage Explorer (1.12.0)?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you're still having problems. Thanks.
