### ISSUE TITLE
Fail to upload/download/delete/clone/paste items in one OAuth attached blob container

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7975]
**Storage Explorer Version:** 1.35.0-dev (98)
**Build Number:** 20240531.1
**Branch:** main
**Platform/OS:** Windows 11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.5(Apple M1 Pro)
**Architecture:** arm64/x64/x64/arm64
**How Found:** From running test cases
**Regression From:** Previous release (1.34.0)

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Select one blob container -> Attach the blob container via OAuth.
3. Open the attached blob container -> Try to upload one blob.
4. Check whether succeeds to upload the blob.

## Expected Experience ##
Succeed to upload the blob.

## Actual Experience ##
Fail to upload the blob with an error.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/a5269f4e-44c2-4766-a0cb-771fbbe3c91d)
`"\"failed to perform copy command due to error: get token from environment variable failed to unmarshal token, json: cannot unmarshal string into Go struct field OAuthTokenInfo._token_refresh_source of type common.AutoLoginType\""`

## Additional Context ##
1. This issue also reproduces if download/paste/clone blobs.
2. The below error displays if delete blobs:
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/55f0d276-460b-4b78-a6b9-0a1097b1fddb)

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240614.1. Fixed.
