### ISSUE TITLE
The blob container on the tree view doesn't automatically show as leased if acquire lease for blob container on view all containers explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7977]
**Storage Explorer Version**: 1.35.0-dev (98)
**Build Number**: 20240604.2
**Branch**: main
**Platform/OS**: Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.5(Apple M1 Pro)
**Architecture**: arm64/x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.34.0)

## Steps to Reproduce ##
1. Open 'Settings -> Services' -> Select 'View all' for the setting 'Storage Nodes Trailing Action'.
2. Refresh the tree view -> Expand one storage account -> Blob Containers -> Create a blob container.
3. Click 'View all' -> Go to the view all containers explorer.
4. Select the blob container -> Acquire lease for it.
5. Check whether the blob container on the tree view shows as leased automatically.

## Expected Experience ##
The blob container on the tree view shows as leased automatically.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/524995ee-7e1a-42c1-9dc8-b0f57700a5a7)

## Actual Experience ##
The blob container on the tree view doesn't show as leased automatically.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/1c084cd4-a396-4fda-8d94-09b1180cc602)

**Comment by craxal** [comment]
That's weird, because I _did_ see the tree node update automatically when testing.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240705.1. Fixed. So, we are going to close it.
