### ISSUE TITLE
Use 'blob container' instead of 'blob containers' in descriptions when confirming the deletion of a single blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7979]
**Storage Explorer Version**: 1.35.0-dev (98)
**Build Number**: 20240604.2
**Branch**: main
**Platform/OS**: Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.5(Apple M1 Pro)
**Architecture**: arm64/x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Open 'Settings -> Services' -> Select 'View all' for the setting 'Storage Nodes Trailing Action'.
2. Refresh the tree view -> Expand one storage account -> Blob Containers -> Click 'View all'.
3. Go to the view all containers explorer -> Select one blob container -> Click 'Delete'.
4. Observe the description on the confirmation dialog.
5. Check whether it shows '1 blob container' in the descriptions.

## Expected Experience ##
It shows '1 blob container' in the descriptions.

## Actual Experience ##
It shows '1 blob containers' in the descriptions.

![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/5439848c-8673-4d0e-96b8-edb2032fcbc7)

## Additional Context ##
Below is the screenshot in previous release:
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/daa15fa2-d57c-4d13-903a-7d48ac59b883)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240717.2. Reproduce. So, we are going to reopen it.
![image](https://github.com/user-attachments/assets/b7c3be23-93a3-4044-8897-a22c3adb391e)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240718.1. Reproduce. Will verify it on a newer build.

**Comment by craxal** [comment]
Merged an additional change. Should be fixed now.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240719.6. Fixed.
![image](https://github.com/user-attachments/assets/2a3bb5cb-94a6-4bda-9855-9e7b7c6569e3)
