### ISSUE TITLE
Graph values CHANGED to "null" when they are null and not modified.

### ISSUE THREAD

**Issue by GetTheBalanceRight** [microsoft/AzureStorageExplorer#798]
**Storage Explorer Version**: 1.4.4
**Platform/OS Version**: macOS Mojave 10.14
**Architecture**: x64

#### Steps to Reproduce: ####
1. Create a graph object with multiple null values for some properties using an application, or with a script
2. Query for the object in the graph
3. Click on the result that object that was retrieved. The null values show as blank when viewing
4. Click the edit pencil
5. Delete any property with the trash icon
6. Save the object
7. The properties that were null now have the string value "null"

#### Expected Experience: ####
I would expect that values that were not modified would remain at their previous value of null.

#### Actual Experience: ####
The unmodified null values have the string value "null"

**Comment by ziyel** [comment]
Thanks @ctearpak for the feedback. We are investigating the issue.

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
