### ISSUE TITLE
An error dialog pops up when trying to delete one blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7983]
**Storage Explorer Version**: 1.35.0-dev (98)
**Build Number**: 20240605.2
**Branch**: main
**Platform/OS**: Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.5(Apple M1 Pro)
**Architecture**: arm64/x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.34.0)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Select one blob container and right click it -> Click 'Delete'.
3. Check whether a confirmation dialog pops up.

## Expected Experience ##
A confirmation dialog pops up.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/ad01e481-6eb9-4aa9-b285-003ad1dd8f88)

## Actual Experience ##
An error dialog pops up.
**Error message:**
`TypeError:Cannot read properties of undefined (reading 'serviceEndpoint')`
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/76742de1-9412-4e54-9537-67a7df71c8c4)

**Comment by craxal** [comment]
@v-xianya Do you know how the connection is being authenticated? Are you signed in? Are account keys enabled? Are you using a SAS?

**Comment by v-xianya** [comment]
Hi @craxal 
I logged in with my Azure account -> Blob container is under my subscription.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240717.2. Fixed. So, we are going to close it.
