### ISSUE TITLE
It would be better to use uncapitalized prepositions such as in "Organize by Resource Group"

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7991]
**Storage Explorer Version**: 1.35.0-dev (98)
**Build Number**: 20240607.1
**Branch**: main
**Platform/OS**: Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.5(Apple M1 Pro)
**Architecture**: arm64/x64/x64/arm64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Open ‘Settings -> Services'.
2. Observe the setting 'Organize by Resource Group'.
3. Check whether it shows 'By' in the description.

## Expected Experience ##
It would be better to update 'by' to 'By'.

## Actual Experience ##
It shows 'by' in the description.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/629c99b8-9115-4e20-9ca4-b1c73b31c563)

**Comment by v-xianya** [comment]
Hi @craxal In the settings, other prepositions are capitalized; should we maintain consistency
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/a18d13f4-4eba-4e4a-a391-584d327ed533)

**Comment by v-xianya** [comment]
Hi @craxal I think it would be better to maintain consistency for prepositions, so, we are going to re-open this issue.

**Comment by craxal** [comment]
Agreed. We will fix these strings.

**Comment by v-kellyluo** [comment]
Hi @craxal ,verified this issue on the build 20240716.5, the [comments ](https://github.com/microsoft/AzureStorageExplorer/issues/7991#issuecomment-2159860077)mentioned are fixed.
But there are still some prepositions are capitalized, could you help to take a look?
![image](https://github.com/user-attachments/assets/d93b1cae-445c-46dd-8869-fb353c150688)

**Comment by craxal** [comment]
Changes have been merged. Prepositions should have proper capitalization now. Please note, though that "Sign In With:" is now "Sign In with:". The word "in" is considered part of the "Sign In" feature and not quite a preposition, so it remains capitalized. However, "with" is a properly uncapitalized preopsition.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240723.1. The current behaviors match the comments.
