### ISSUE TITLE
Rate limit prevents download

### ISSUE THREAD

**Issue by ScottOfford** [microsoft/AzureStorageExplorer#7994]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.34.0

### Architecture

x64

### Storage Explorer Build Number

20240523.2

### Platform

Windows

### OS Version

Windows 10

### Bug Description

When enabling a download speed cap, the download fails to start

### Steps to Reproduce

1. Launch Storage Explorer
2. Navigate to Edit > Settings
3. Click on Transfers and scroll down to Maximum Transfer Rate
4. Set this to any value (in my case, 25Mbps)
5. Connect to a file share storage account
6. Trigger a download

### Actual Experience

Transfer immediately fails
![image](https://github.com/microsoft/AzureStorageExplorer/assets/67613661/60805977-42c3-458a-ad8e-de25a5c75db3)

"_request size greater than pacer target. When Enqueueing chunk._" is listed in the AzCopy Log File

### Expected Experience

File is downloaded, adhering to the transfer limit defined in the settings.

### Additional Context

I have seen this mentioned in the issue: https://github.com/Azure/azure-storage-azcopy/issues/2380

**Comment by craxal** [comment]
@ScottOfford Yeah, this is a known issue in AzCopy, and they plan on fixing this in a future version. In the meantime, can you bump up the rate limit to a value that works?
