### ISSUE TITLE
The spacing between available columns is too wide on 'Column Options' dialog for tables

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7998]
**Storage Explorer Version**: 1.35.0-dev (98)
**Build Number**: 20240611.1
**Branch**: main
**Platform/OS**: Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.5(Apple M1 Pro)
**Architecture**: arm64/x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.34.0)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Click 'Customize Columns'.
3. Check whether the spacing between available columns is fine.

## Expected Experience ##
The spacing between available columns is fine.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/89630c13-3878-45ed-ba78-3a8e4ca1bb03)

## Actual Experience ##
The spacing between available columns is too wide.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/0ff81a66-1035-4fed-8d1a-c6aeb04edc30)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240612.1. Fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/af26fd64-22d5-4117-8cb2-54ad6ea2f591)
