### ISSUE TITLE
Account Name/Label

### ISSUE THREAD

**Issue by ishutyak** [Microsoft/AzureStorageExplorer#80]
Hi All,
We faced with the following issue:

**Storage Explorer Version:** 1.0.0

**OS Version:** Windows 10 

**Steps to Reproduce:**

1.	Press “Add Account” button 
2.	Choose “Use a connection string or a shared access signature URI” press Next
3.	Enter valid connection string DefaultEndpointsProtocol=https;AccountName=[ACC-NAME];AccountKey=[KEY]
4.	Change Account label like ACC-NAME-1
5.	Press Next
6.	Press Connect
7.	New storage showing on left panel
8.	Try expand Blob Containers 
9.	In our side we see following error:
[Window Title]
Storage Explorer has encountered an unexpected error:
[Content]
Unable to retrieve child resources.
Details: getaddrinfo ENOTFOUND ACC-NAME-1......windows.net ACC-NAME-1......windows.net:443

**Expected Experience:** account name should be used
**Actual Experience:** account label (alias) is used

Thanks,
Ihor

**Comment by craxal** [comment]
Hm, yes, this falls under a class of issues we hope to address in the near future.

The "Use a connection string or shared access signature URI" was only really meant for SAS connections. It looks like you have the account name and key. So, in the meantime, I suggest choosing the "Use a storage account name and key" option for now. Is that a suitable workaround?
