### ISSUE TITLE
It is better to enlarge the 'Update Access Tier' dialog to ensure there is no scrollbar

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8001]
**Storage Explorer Version**: 1.35.0-dev (98)
**Build Number**: 20240612.1
**Branch**: main
**Platform/OS**: Windows11/Windows 10
**Architecture**: arm64/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one blob with archive access tier.
3. Right click the archive blob -> Click 'Change Access Tier...'.
4. Click 'Apply' on the update access tier dialog.
5. Then right click the blob -> Click 'Change Access Tier...'.
6. Set the rehydration priority to 'High'.
7. Check there is no scrollbar on the dialog.

## Expected Experience ##
It is better to enlarge the dialog to ensure there is no scrollbar.

## Actual Experience ##
There is a scrollbar on the dialog.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/235d6702-b491-4a7c-af7a-48cf1da151f6)

## Additional Context ##
This issue doesn't reproducer on Linux Ubuntu 22.04 & MacOS Sonoma 14.5(Apple M1 Pro).

**Comment by craxal** [comment]
@JasonYeMSFT "Invisible" elements aren't always accounted for when dialog auto-sizing code runs (for example, when `display: none` is used). Either expand the dialog's default size or make sure even invisible elements' layouts are accounted for.

**Comment by JasonYeMSFT** [comment]
I have increased the height of the dialog to prevent the scroll bar from showing up with default zoom level and English locale.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240716.5. Fixed. So, we are going to close it.

![image](https://github.com/user-attachments/assets/53e17181-668d-45d5-b5b8-8550b48410ce)
