### ISSUE TITLE
It shows the property 'Configure Soft Delete Policy...' instead of 'Soft Delete' on the Properties panel of 'Blob Containers' node

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8004]
**Storage Explorer Version**: 1.35.0-dev (98)
**Build Number**: 20240613.1
**Branch**: main
**Platform/OS**: Windows11/Windows 10/Linux Ubuntu 22.04 & MacOS Sonoma 14.5(Apple M1 Pro)
**Architecture**: arm64/x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.34.0)

## Steps to Reproduce ##
1. Expand one storage account -> Select the 'Blob Containers' node.
2. Observe its properties on the Properties panel.
3. Check whether there is a property 'Soft Delete'.

## Expected Experience ##
There is a property 'Soft Delete'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/de5b796e-9c7b-43e7-bd6b-77a521eaf188)

## Actual Experience ##
1. There is no property 'Soft Delete'.
2. There is a property 'Configure Soft Delete Policy...'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/06b5fbf3-5de4-46be-943d-99d50b2c20e8)

**Comment by MRayermannMSFT** [comment]
I'm going to guess this is my fault.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240703.1. Fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/0a52cbe0-4cea-49ee-89f3-6e113fd03c6b)
