### ISSUE TITLE
Determine/Find a source that documents why `--analyze` does not work on macOS ARM64

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#8009]
Update the comment in `src\components\build-common\gulp\binding-build.gyp` once the reason is discovered.

**Comment by JasonYeMSFT** [comment]
I can't find any docs on this. I don't see recent SDL tasks mentioning this anymore so maybe this is no longer important.

**Comment by craxal** [comment]
We started getting build issues for macOS x64. Apparently, the `--analyze` flag is just flat out broken. It causes linking issues with the object files. No wonder, as looking at the object files reveals what looks like plist formatted data rather than binary.
