### ISSUE TITLE
The focused colors are inconsistent between the refresh notification and others under HC-Black theme

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#801]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181025.6
**Commit**: a287009c
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Change the current theme to HC-Black.
2. Enable AzCopy feature -> Open one blob container then try to upload a blob to it.
3. Focus on any one button of the refresh notification after uploading successfully.
4. Check the focused color.

#### Expected Experience: ####
The focused color is consistent with others like 'Delete' button.
![actual](https://user-images.githubusercontent.com/34729022/47488533-29469700-d877-11e8-8c57-a3f22f5da9cb.png)

#### Actual Experience: ####
The color is inconsistent with others.
![expect](https://user-images.githubusercontent.com/34729022/47488540-2cda1e00-d877-11e8-8910-a48a225f4c5f.png)

**Comment by craxal** [comment]
This is not inconsistent with the info bar, which also uses the same blue color. However, we may want to consider modifying the high contrast colors for buttons to all be the same. @jinglouMSFT, what do you think?

**Comment by jinglouMSFT** [comment]
We had a similar accessibility bug on the blue color during our accessibility push.  The deep blue is not an acceptable color. Could you please fix both, the info bar and the refresh notification bar?  Need this fixed for the 1.5.0 release.  Thanks.
