### ISSUE TITLE
It is better to adjust the size of the 'Available Columns' section to remove the scrollbar against the 'Select Columns' dialog

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#8010]
**Storage Explorer Version:** 1.35.0-dev (98)
**Build Number:** 20240618.3
**Branch:** main
**Platform/OS:** Windows11/Windows 10/Linux Ubuntu 22.04 & MacOS Sonoma 14.5(Apple M1 Pro)
**Architecture:** arm64/x64/x64/arm64
**How Found:** Ad-hoc testing
**Regression From:** Previous release (1.33.1)

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create a table -> Add an entity which has one property name with 255 characters.
3. Click 'Query' -> Expand 'Advanced Options' -> Click 'Select Columns...'.
4. Check whether there is no scrollbar against the 'Select Columns' dialog.

## Expected Experience ##
It is better to adjust the size of the 'Available Columns' section to remove the scrollbar against the 'Select Columns' dialog.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/2ff2037b-ef91-46fe-a00a-a5ea56b28763)

## Actual Experience ##
There is a scrollbar against the 'Select Columns' dialog.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/60a4be16-6eb1-4bae-ac4c-eb8fb5d529eb)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240716.5. Reproduce. So, we are going to re-open it.
![image](https://github.com/user-attachments/assets/c48e03e0-a03b-4bf4-8aeb-603b4898a3d2)

**Comment by craxal** [comment]
Oops, I forgot to integrate a new table extension.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240717.2. Fixed.
![image](https://github.com/user-attachments/assets/f587caee-2454-4baa-9433-653a6343df26)
