### ISSUE TITLE
It shows 'Rename...' instead of 'Rename Connection...' on the context menu of attached blob containers

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8013]
**Storage Explorer Version**: 1.35.0-dev (98)
**Build Number**: 20240620.3
**Branch**: main
**Platform/OS**: Windows11/Windows 10/Linux Ubuntu 22.04 & MacOS Sonoma 14.5(Apple M1 Pro)
**Architecture**: arm64/x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.34.0)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Attach the blob container.
3. Right click the attached blob container -> Observe its context menu.
4. Check whether it shows 'Rename Connection...' on the context menu.

## Expected Experience ##
It shows 'Rename Connection...' on the context menu.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/f4de7bfe-37a5-4f2c-b03f-6b59aa46a941)

## Actual Experience ##
It shows 'Rename...' on the context menu.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/4b621b08-4e0b-4fc5-b085-177f36cb16c3)

## Additional Context ##
It shows 'Rename Connection...' against attached file shares/queues/tables.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240703.1. Fixed.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/ce8ef94b-c71f-4f52-b2e5-d95b26bae2f8)
