### ISSUE TITLE
Customize columns regression

### ISSUE THREAD

**Issue by sixeyes** [microsoft/AzureStorageExplorer#8015]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.34.0

### Regression From

1.33.1

### Architecture

i86

### Storage Explorer Build Number

20240523.2

### Platform

All

### OS Version

Windows 10

### Bug Description

When viewing a storage table, on the customize columns dialog, the Hide All button used to hide all the columns (v1.33.1), but in v1.34.0, the top column is no longer hidden.

The button no longer does what it says and it is confusing.

In addition, since I don't want to look at PartitionKey (the top column when first opening a table), this is unhelpful and slows me down. In v1.33.1 ALL I had to do was enable the columns I wanted to view. Now in v1.34.0 I have to hide PartitionKey before selecting to columns I actually want to view.

### Steps to Reproduce

1. Launch Storage Explorer
2. Open a Storage Table
3. Right click on the column headers
4. Choose Customize Columns
5. Click Hide All button in dialog

### Actual Experience

All columns EXCEPT the top column are hidden

### Expected Experience

All columns should be hidden

**Comment by craxal** [comment]
@sixeyes This is by design. At least one column _must_ be visible. So, in previous versions, if you try to hide all columns, you would get an error message, and the OK button would be disabled. We believed it would be less cumbersome to simply enforce the at-least-one-column rule instead (see #7718).

But it sounds like you prefer the older behavior, and I agree it makes one's column selections easier to control.

**Comment by sixeyes** [comment]
I rarely include PartitionKey in my list of columns, as it's usually part of the filter.

If you do keep the design as it is, could we have the option to load the list of columns from a file, much like loading a filter definition, that way I wouldn't need to worry about hide all behaviour.

**Comment by craxal** [comment]
We plan on reverting to the original behavior.
