### ISSUE TITLE
Files shares missing

### ISSUE THREAD

**Issue by JorgePortu** [microsoft/AzureStorageExplorer#8016]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.34.0 (99)

### Architecture

x64

### Storage Explorer Build Number

20240523.2

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Files shares option missing. Also i need to map as a network disk.

### Steps to Reproduce

I don´t see the option of files shares to upload my files. 

### Actual Experience

Can´t work.

### Expected Experience

![No title](https://github.com/microsoft/AzureStorageExplorer/assets/173363798/27d388ae-6c4c-4856-af8a-7870b3a665e8)

**Comment by craxal** [comment]
@JorgePortu Your storage account appears to be a premium _blob_ storage account, which does not support file shares. You need either a general-purpose or premium file shares storage account (see https://learn.microsoft.com/en-us/azure/storage/common/storage-account-overview#types-of-storage-accounts).

**Comment by JorgePortu** [comment]
Craig,
Thanks very much.
Now i had another problem. I mount the drive with the script in power shell but i can´t see it in the explorer neither access to it with CMD.

**Comment by JorgePortu** [comment]
I am starting. very sorry to distur you but you have been the only one that helped me.

**Comment by JorgePortu** [comment]
PS D:\> D:\ScriptAzureCARMIN.ps1

CMDKEY: credencial agregada correctamente.

Name           Used (GB)     Free (GB) Provider      Root                                                                                                                      CurrentLocation
----           ---------     --------- --------      ----                                                                                                                      ---------------
U                   0,00     102400,00 FileSystem    \\eolico.file.core.windows.net\p...

**Comment by JorgePortu** [comment]
![ResultScript](https://github.com/microsoft/AzureStorageExplorer/assets/173363798/94e3fb6c-4565-4305-9c4a-c656fc3a5d3b)

**Comment by JorgePortu** [comment]
Solved. It was the annoying antivirus.
Thanks anyway.
Best regards
