### ISSUE TITLE
Authentication failing

### ISSUE THREAD

**Issue by Ian-256** [microsoft/AzureStorageExplorer#8017]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.34.0

### Regression From

1.33.0

### Architecture

x64

### Storage Explorer Build Number

Unable to get just gives (Empty)

### Platform

Windows

### OS Version

windows 11 22H2 22621.3593

### Bug Description

open Storage Explorer, all menus (File, Edit etc) say (Empty) 
![image](https://github.com/microsoft/AzureStorageExplorer/assets/173378745/7e20e3ff-809a-40df-bcf3-0d9d9551e4b3)
Click the user icon "Sign in with Azure" Azure next. just stops on "Your browser should now open and redirect you to a login page. Waiting for authentication..." nothing else. 
Also if you click the plug for a new connection select "Subscription" > Azure this does the same. 
I've uninstalled deleted all contents from AppData for it etc. still the same. 

### Steps to Reproduce

Click the user icon "Sign in with Azure" Azure next. just stops on "Your browser should now open and redirect you to a login page. 
OR 
Also if you click the plug for a new connection select "Subscription" > Azure

### Actual Experience

open Storage Explorer, all menus (File, Edit etc) say (Empty) 
![image](https://github.com/microsoft/AzureStorageExplorer/assets/173378745/7e20e3ff-809a-40df-bcf3-0d9d9551e4b3)
Click the user icon "Sign in with Azure" Azure next. just stops on "Your browser should now open and redirect you to a login page. Waiting for authentication..." nothing else. 
Also if you click the plug for a new connection select "Subscription" > Azure this does the same. 
I've uninstalled deleted all contents from AppData for it etc. still the same. 
![image](https://github.com/microsoft/AzureStorageExplorer/assets/173378745/b6569825-0400-4645-96bc-f22e96079ff3)

### Expected Experience

Should open browser and allow MFA / Sign in.

**Comment by craxal** [comment]
@Ian-256 Sometimes it takes a few seconds for everything in Storage Explorer to initialize, including the menus. Can you try waiting a few seconds for the menus to populate and then try signing in? If that doesn't work, can you please share the app and the authentication logs?

**Comment by santoshgshet** [comment]
Hello all, I am facing the same issue and not able to login after upgrading the storage explorer version. It is stuck on waiting for authentication or the default browser option doesn't open the browser at all.

**Comment by Ian-256** [comment]
HI, Ive left this opening for about 15mins come back to it and it has timed out and does ask if you want to retry. Click retry and it waits another 15mins or so.

**Comment by Ian-256** [comment]
After a lot of diffing, I've managed to resolve the issue. 
when logging I noticed sometimes I get a .net 8 error. Event ID1023...
Description: A .NET application failed.
Application: Microsoft.ServiceHub.Controller.exe
I've basically removed .net 8 and reinstalled it (redownloaded it) rebooted tested storage explorer and its all working.
