### ISSUE TITLE
Remove the action 'Auto-Resolve behavior…' during the download with no conflicts

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#802]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181025.6
**Commit**: a287009c
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Open one file share which contains one file/directory at least.
2. Create a new folder on local file system -> Try to download the file/directory to the new folder.
3. Check the log message during the download.

#### Expected Experience: ####
'Auto-Resolve behavior…' doesn't show next to the log message since there are no conflicts.

#### Actual Experience: ####
'Auto-Resolve behavior…' shows next to the log message.
![conflict](https://user-images.githubusercontent.com/34729022/47489045-3ca63200-d878-11e8-8643-5761fb94063e.png)

**Comment by v-xianya** [comment]
Verified on the latest build 20190618.3. This issue still reproduces.

**Comment by MRayermannMSFT** [comment]
Closing as we're moving File Shares to AzCopy which doens't have this behavior.
