### ISSUE TITLE
The downloaded item is not highlighted in the file explorer if only one transfer is selected on the 'Retry Azcopy' dialog

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#8020]
**Storage Explorer Version:** 1.35.0-dev (98)
**Build Number:** 20240625.2
**Branch:** main
**Platform/OS:** Windows11/Windows 10/Linux Ubuntu 22.04 & MacOS Sonoma 14.5(Apple M1 Pro)
**Architecture:** arm64/x64/x64/arm64
**How Found:** Ad-hoc testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create one blob container -> Upload two blobs -> Download the two blobs.
3. Download the two blobs to the same destination again -> Select 'Do not download -> Apply to All Conflicts'.
4. Click 'Retry...' next to the failed activity log -> Uncheck one transfer -> Select 'Enable overwrite' option -> Click 'Retry Selected'.
5. Click 'Show in Folder' next to the successful activity log.
6. Check whether the file is highlighted in the file explorer.

## Expected Experience ##
The file is highlighted in the file explorer.

## Actual Experience ##
The file is not highlighted in the file explorer.

## Additional Context ##
This issue also reproduces for file shares.

**Comment by craxal** [comment]
@v-kellyluo I am unable to produce, because I get no "Show in Folder" action when the activity completes.

**Comment by v-kellyluo** [comment]
@craxal, here is the GIF, we must only select one transfer when there are several transfers on the 'Retry Azcopy' dialog.
![high](https://github.com/user-attachments/assets/7db25838-366c-497b-9bc0-45850a3861a2)

**Comment by craxal** [comment]
Oh, my bad. This is _download_, not upload.

**Comment by craxal** [comment]
OK, I see now. This happens because the _original download_ was more than two files. Therefore, the location for the "Show In Folder" action is a folder, not an individual item. This is behaving as intended, and I don't think we need to worry about refining this unless users are bothered.
