### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by VaughanHFlood** [microsoft/AzureStorageExplorer#8021]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

To upload a file/folder takes far too many clicks

### Desired Solution

1. Instead of clicking upload and then selecting files or folders have two buttons so I can just click upload files (or upload folders).
2. Instead of showing a dialog with No files selected populate the dialog with the last file selected.  More than half the time this will be the right file.
3. Add keyboard shortcuts to the dialog buttons - this was the norm even back in the 90s.

### Alternatives and Workarounds

Some form of Macro. Voice control

**Comment by craxal** [comment]
@VaughanHFlood Have you tried and of these other alternatives?
* Drag and drop local files and folders into Storage Explorer.
* Copy local files and folders and paste them in Storage Explorer (Ctrl+C/V keyboard shortcuts should also work).

**Comment by craxal** [comment]
@VaughanHFlood Have you tried the alternatives I mentioned above? We need your input in consideration of this feature request.

**Comment by VaughanHFlood** [comment]
Hi Craig

Thanks for getting back to me. Drag and drop certainly helps – hadn’t appreciated this was possible.

But I’m still left with the issue of having to click on one of the buttons on this screen:

***@***.***

In my workflow I’m doing this literally dozens of times a day. It would be good to have the options of:

  *   Either being able to turn this off (yes I appreciate the risks)
  *   Or having keyboard shortcuts available as an alternative to have to click one of the (small) buttons

Thanks

Vaughan

Vaughan Flood

+44 (0) 7801 099041  •  +44 (0) 20 3890 8100
www.flood.partners<http://www.flood.partners/>  •  Twitter<https://twitter.com/FloodPartners>  •  LinkedIn<https://www.linkedin.com/company/floodpartners/>  •  ***@***.***>
 ***@***.***
 ***@***.***
This email is confidential, may be legally privileged, and is for the intended recipient only. Access, disclosure, copying, distribution or reliance on any of it by anyone else is prohibited and may be a criminal offence. Please delete if obtained in error. Any views expressed in this message are those of the individual sender, except where the sender specifically states them to be the views of Flood + Partners Ltd.

**Comment by craxal** [comment]
@VaughanHFlood Did you try to share a screenshot? Please post it using the website directly. You can't share screenshots via email.

> 1. Instead of clicking upload and then selecting files or folders have two buttons so I can just click upload files (or upload folders).

This is easily implemented. We can look into which shortcuts would be best for this. Any suggestions?

> 2. Instead of showing a dialog with No files selected populate the dialog with the last file selected. More than half the time this will be the right file.

I'm not sure I agree on this point. This doesn't sound very useful in most situations, unless you wanted to quickly upload the same file multiple times...? Perhaps I'm not understanding your meaning.

> 3. Add keyboard shortcuts to the dialog buttons - this was the norm even back in the 90s.

What specific shortcuts would you expect for the dialog buttons?

**Comment by VaughanHFlood** [comment]
Hi Craig

Thanks for getting back to me. I’m not sure how to communicate directly via the website so I’ll stick to email.


  1.  Your hint about dragging/dropping files/folders has been a significant gamechanger and reduces the need/benefits of separate ‘upload files’ and ‘upload folder’ buttons – though it could still be useful in some circumstances.

  2.  Again, dragging/dropping effectively addresses your second point so I would drop this (as you can have the relevant folder permanently open and drag across changes instantly. This just leaves…

  3.  The dialog box titled ‘Conflict’ that appears when you drag across a file that will potentially overwrite a pre-existing file currently has no keyboard shortcuts available on it. This means you have to manually click on any of the buttons. Ideally the  ’Apply to all conflicts’ button would be set as the default and pressing enter would make your selection. And the tab key would enable you to switch from button to button.

You’ve helped improve my workflow a lot. Implementing the change outlined at three would streamline things for me and I imagine many thousands of other people too.

Kind regards

Vaughan


Vaughan Flood

+44 (0) 7801 099041  •  +44 (0) 20 3890 8100
www.flood.partners<http://www.flood.partners/>  •  Twitter<https://twitter.com/FloodPartners>  •  LinkedIn<https://www.linkedin.com/company/floodpartners/>  •  ***@***.***>
 ***@***.***
 ***@***.***
This email is confidential, may be legally privileged, and is for the intended recipient only. Access, disclosure, copying, distribution or reliance on any of it by anyone else is prohibited and may be a criminal offence. Please delete if obtained in error. Any views expressed in this message are those of the individual sender, except where the sender specifically states them to be the views of Flood + Partners Ltd.

**Comment by craxal** [comment]
@VaughanHFlood

> 3. The dialog box titled ‘Conflict’ that appears when you drag across a file that will potentially overwrite a pre-existing file currently has no keyboard shortcuts available on it. This means you have to manually click on any of the buttons. Ideally the ’Apply to all conflicts’ button would be set as the default and pressing enter would make your selection. And the tab key would enable you to switch from button to button.

Are you saying you _cannot_ currently tab to the controls in this dialog? Because you should be able to do this already. I just tested it myself, and it works fine. We have not set any default buttons, so that's one thing we can do.

> I’m not sure how to communicate directly via the website so I’ll stick to email.

I would recommend using github.com from a desktop or laptop computer. You can very easily get to this issue and follow this conversation by opening this link in your browser: https://github.com/microsoft/AzureStorageExplorer/issues/8021.

**Comment by VaughanHFlood** [comment]
Hi Craig

Yes you can use tab but when you do it goes straight to the statement ‘how will soft delete affect overwrite’ which I submit is something people very rarely want to review and certainly not on every visit. To get to one of the apply buttons (again I envisage this is the usual action) currently takes at least 3 keyboard strokes. If one of the apply buttons was set as the default it would take one. That’s a lot of keyboard strokes saved. Here’s hoping you can add a default.

Thanks

Vaughan

Vaughan Flood

+44 (0) 7801 099041  •  +44 (0) 20 3890 8100
www.flood.partners<http://www.flood.partners/>  •  Twitter<https://twitter.com/FloodPartners>  •  LinkedIn<https://www.linkedin.com/company/floodpartners/>  •  ***@***.***>
 ***@***.***
 ***@***.***
This email is confidential, may be legally privileged, and is for the intended recipient only. Access, disclosure, copying, distribution or reliance on any of it by anyone else is prohibited and may be a criminal offence. Please delete if obtained in error. Any views expressed in this message are those of the individual sender, except where the sender specifically states them to be the views of Flood + Partners Ltd.

**Comment by craxal** [comment]
I have opened #8101 to track that work.
