### ISSUE TITLE
Unable to sign in via Default Web Browser and Integrated Sign-in

### ISSUE THREAD

**Issue by inaaa-iio** [microsoft/AzureStorageExplorer#8024]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.34.0

### Architecture

x64

### Platform

Windows

### OS Version

Windows 11

### Bug Description

Unable to sign in to Storage Explorer via Default Web Browser and Integrated Sign-in
1- The Storage Explorer does not open a webpage for me to sign in when the Default Web Browser option is enabled. I also followed the troubleshooting guide of opening my web browser beforehand, but nothing happened.

2- I also tried the Integrated Sign-in option but nothing's happening expect that it's stuck with "Waiting for authentication"

3- I also tried to attach a Storage account using connection string but it's stuck with "Adding new connection..."

I haven't been able to install .NET 8 because I do not have admin rights. Does this affect the authentication?

### Steps to Reproduce

1. Launch Storage explorer
2. Select Subscription and Sign in with Azure

### Actual Experience

Nothing happens when I try to sign in via the following:
1- Default Web Browser - browser does not open
![image](https://github.com/microsoft/AzureStorageExplorer/assets/173975834/e35c685f-8db0-49e1-a9a7-1c3befd10f30)

2- Integrate sign-in
![image](https://github.com/microsoft/AzureStorageExplorer/assets/173975834/ec28f6da-7aa0-471f-9a18-98aafb1c993d)

3- Attach storage account
![image](https://github.com/microsoft/AzureStorageExplorer/assets/173975834/54b9c191-7aee-4747-bb9c-0d42243bf057)

### Additional Context

I haven't been able to install .NET 8 because I do not have admin rights. Does this affect the authentication?

**Comment by martinitus** [comment]
Similar behavior here since the upgrade. Can't even tell you which version I'm on now, cause the UI is pretty broken and only shows empty stuff. Non of the 3 sign in options do anything. Logs were also not helpful. Completely blocked at work because of this now.

![image](https://github.com/microsoft/AzureStorageExplorer/assets/7611856/5dc012a2-57e9-4b47-8d7d-a5cd1bac39c3)

**Comment by inaaa-iio** [comment]
Hi @martinitus ,
Issue is now resolved on my end after installing .NET 8.

[I was informed](https://learn.microsoft.com/en-us/answers/questions/1770376/unable-to-sign-in-to-storage-explorer-via-default?page=1&orderby=Helpful&comment=answer-1568975#newest-answer-comment) that Storage Explorer should still work without .NET 8 but it was the answer to my problem.

**Comment by craxal** [comment]
@inaaa-iio I believe that information may be out-of-date. If you look at our [1.34.0 release notes](https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.34.0), you'll see that .NET 8 is now required.

**Comment by martinitus** [comment]
Well, if dotnet 8 is required that explains it. i updated storage manager via the UI, but i don't have admin rights on the machine, so the dotnet8 update didn't go through. Quite pointless to allow updating the app into a broken state then :-/
