### ISSUE TITLE
signing in with azure has the wrong application name

### ISSUE THREAD

**Issue by mrgum** [microsoft/AzureStorageExplorer#8026]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

Version: 1.34.0 (99)

### Architecture

x64

### Storage Explorer Build Number

20240523.2 

### Platform

macOS

### OS Version

macOS Sonoma

### Bug Description

After signing in to azure using firefox I get the message

`Authenticated. You can return to Visual Studio. You might need to authenticate again if you close this browser tab.`

Surely it should be 

`Authenticated. You can return to Microsoft Azure Storage Explorer. You might need to authenticate again if you close this browser tab.`

### Steps to Reproduce

1. Launch Storage Explorer
2. Sign in to Azure
3. Sign in

### Actual Experience

Authenticated. You can return to Visual Studio. You might need to authenticate again if you close this browser tab.

### Expected Experience

Authenticated. You can return to Microsoft Azure Storage Explorer You might need to authenticate again if you close this browser tab.

**Comment by craxal** [comment]
This is just a display string issue. It will be fixed in the future. There's nothing you need to do!

See #8005.
