### ISSUE TITLE
There is no 'Deleted Time' column in blob container explorers

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#8028]
**Storage Explorer Version:** 1.35.0-dev (98)
**Build Number:** 20240628.1
**Branch:** main
**Platform/OS:** Windows11/Windows 10/Linux Ubuntu 22.04 & MacOS Sonoma 14.5(Apple M1 Pro)
**Architecture:** arm64/x64/x64/arm64
**How Found:** From running test cases
**Regression From:** Previous release (1.33.1)

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Open a blob container -> Observe the columns in the explorer.
3. Check whether there is a 'Deleted Time' column.

## Expected Experience ##
There is a 'Deleted Time' column.

## Actual Experience ##
There is no 'Deleted Time' column.

## Additional Context ##
1. This issue also reproduces for ADLS Gen2 blob containers. 
2. For regular blob containers, it is a regression from 1.33.1. For ADLS Gen2 blob containers, it is a regression from 1.32.1.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240717.2. Reproduce. So, we are going to reopen it.

**Comment by craxal** [comment]
Oops, I didn't quite integrate changes correctly. Published a new package.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240719.6. Fixed.
