### ISSUE TITLE
Azure explorer does not sign in and times out

### ISSUE THREAD

**Issue by CovaB** [microsoft/AzureStorageExplorer#8030]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.0

### Architecture

i86

### Platform

Windows

### OS Version

Windows 10

### Bug Description

I recently updated Azure storage (28.06.2024) and since then my accounts have disappeared from the app and when I try to log in it does not open the explorer. I have tried signing in in app as per the troubleshooting guide but it just says "waiting for authentication..." and then times out.

### Steps to Reproduce

1. launch explorer
2. open account management tab
3. sign in with azure
4. nothing happens.

### Actual Experience

Sign in times out without requesting credentials. troubleshooting guide does not solve the issue.

### Expected Experience

-

### Additional Context

-

**Comment by craxal** [comment]
@CovaB Can you share the app and authentication logs (you may also need to turn on verbose authentication logging in the Settings).

**Comment by CovaB** [comment]
managed to resolve it manually installing .Net 8 and reinstalling azure storage.
