### ISSUE TITLE
The strings are not localized completely on the context menu of one blob container/Blob Containers node

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#8034]
**Storage Explorer Version:** 1.35.0-dev (98)
**Build Number:** 20240701.1
**Branch:** main
**Platform/OS:** Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.5(Apple M1 Pro)
**Architecture:** arm64/x64/x64/arm64
**Reproduce Languages:** All
**How Found:** From running test cases
**Regression From:** Previous release (1.34.0)

## Bug Description ##

1. The strings are not localized completely on the context menu of one blob container/Blob Containers node.
2. The strings are not localized completely on Actions & Properties panel.

## Steps to Reproduce ##

1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select 'español' -> Restart Storage Explorer.
3. Expand one storage account. 
4. Right click Blob Containers node -> Observe the context menu.
5. Check whether all strings are localized.

## Expected Experience ##
All strings are localized. 
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/80d722d9-8f57-4d41-9d64-eb28afe2f02b)

## Actual Experience ##
The strings are not localized completely.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/e857a495-fa00-4e05-8794-41b563069d1a)

## Additional Context ##
1. This issue also reproduces on the context menu of one blob container.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/2f59d9c4-7264-4923-932c-c599fab2bc2b)
2. This issue also reproduces on Action & Properties panel.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/6b091e2f-ddee-4342-b4a2-81ecc090f25b)

**Comment by MRayermannMSFT** [comment]
@v-xianya it's been a few week since this was opened, and I think most strings should be translated by now. I'm going to close this for now that if there's any strings left, they'll continue to be translated as time goes on.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240725.1. Fixed.
