### ISSUE TITLE
Unable to Login with Debug Account

### ISSUE THREAD

**Issue by JackieJiaqiYin** [microsoft/AzureStorageExplorer#8039]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.34.0

### Architecture

i86

### Platform

All

### Bug Description

[Microsoft internal] Two weeks ago, I was able to log in with my debug account without any issues. However, since last week, this is no longer possible. Recently, the company implemented a policy that restricts Azure Data Lake access to managed identities only. I suspect this change might be the reason why logging in with my debug account suddenly stopped working.
Could the team please investigate this issue and provide a solution? Thank you for your assistance.
Here is my error description: 
> Error details: error invalid_request error_description: AADSTS1001010: The client or resource application: e0001ebd-xxx is missing service principal in the tenant: cdc5aeea-xxxx. See instructions here: https://go.microsoft.com/fwlink/?linkid=2167121. Trace ID: 671195c5-1ef9-4a2a-91b4-17ad08c81b00 Correlation ID: ef6ae11d-2444-44f9-b8c4-6fbc88a9229b Timestamp: 2024-07-02 18:05:24Z
(I have hidden the app ID and tenant ID for security reasons. If you need these details, please let me know, and I can provide them internally.)

### Steps to Reproduce

1. Launch storage explorer
2. login in Azure with debug account
3. leading to the error page 

### Actual Experience

Display the error message and cannot access storage

**Comment by craxal** [comment]
Can you send us your authentication logs?

**Comment by sterlind** [comment]
[Microsoft Internal]
Also having the same issue:

```
{
  "message": "\"AADSTS1001010: The client or resource application: e0001ebd-xxx is missing service principal in the tenant: 33e01921-xxx. See instructions here: https://go.microsoft.com/fwlink/?linkid=2167121. Trace ID: 4dd1ca9f-c932-4baa-8dd3-8dd58ce01500 Correlation ID: 4553dcd4-97c0-439f-8b09-94656dcf0c82 Timestamp: 2024-07-12 02:11:46Z\""
}
```

@craxal messaged you on Teams with an excerpt from the authentication logs.

**Comment by craxal** [comment]
We're currently in the process of adding our relatively new app ID to several tenants. Hopefully this should be resolved soon.
