### ISSUE TITLE
Hard to see the dialog prompting to refresh the blob editor in HC modes

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/AzureStorageExplorer#804]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181025.6
**Commit**: a287009c
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Switch theme to HC modes.
2. Check 'Use AzCopy for Improved Blob Upload and Download'.
3. Upload one blob  -> After succeeding, check the dialog prompting to refresh the blob editor.

#### Expected Experience: ####
Easy to see the dialog in HC modes.

#### Actual Experience: ####
Hard to see the dialog in HC modes.
![image](https://user-images.githubusercontent.com/34729092/47490312-0e762180-d87b-11e8-8efd-d436e4eea464.png)

**Comment by craxal** [comment]
This is pretty suggestive. Our color usage is very limited in HC themes. We're using the same colors as the "infobar" anyway. Won't fix.
