### ISSUE TITLE
The selected items are not highlighted if click 'Select All' on the view all containers toolbar

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8044]
**Storage Explorer Version**: 1.35.0-dev (98)
**Build Number**: 20240705.1
**Branch**: main
**Platform/OS**: Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.5(Apple M1 Pro)
**Architecture**: arm64/x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Right click the 'Blob Containers' node.
3. Click 'View All' -> Click 'Select All' on the view all containers toolbar.
4. Check whether the selected items are highlighted.

## Expected Experience ##
The selected items are highlighted.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/6f6c2b35-fd54-4296-8d6a-0634c9c1b133)

## Actual Experience ##
The selected items are not highlighted.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/9c87ef8f-96ee-4d85-aac6-7a87c3b4abb0)

**Comment by craxal** [comment]
@v-xianya The selected items _are_ highlighted (see the gray background). The data grid just doesn't have focus (the "Select All" button does).

**Comment by v-xianya** [comment]
Hi @craxal For other explorer, the items will be highlighted as below after clicking 'Select All'. 
Also, there is a similar bug [7735](https://github.com/microsoft/AzureStorageExplorer/issues/7735).
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/1c1e6a33-7cbc-447e-9afe-5fac05b6a05e)

**Comment by craxal** [comment]
The real issue here appears to be whether the grid receives _focus_ after clicking the Select All button, not whether the items are selected/highlighted.

**Comment by v-xianya** [comment]
Hi @craxal thank you for the response, I get your meaning.
But I thought it would be much better to keep all explorers a same behavior when clicking 'Select All'. So, we are going to reopen this issue.

**Comment by craxal** [comment]
After discussion, we agreed that keyboard focus should _not_ move when clicking the button.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240717.2
The 'Select All' action is focused after clicking the button for all explorers.
![image](https://github.com/user-attachments/assets/42cdf058-df05-4f25-85f7-fa9e8c0f4567)
