### ISSUE TITLE
Allow drilling down through folder structure when filtering for files

### ISSUE THREAD

**Issue by Alonnixx** [microsoft/AzureStorageExplorer#8046]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

when filtering files, the only option is to filter current view/folder 

### Desired Solution

add a checkbox to allow user to choose between search/filter current view or search down the folder structure 

### Additional Context

i have a master folder with sub-folders containing same type files. i would like to be able to download all the files underneath the master folder by filter

**Comment by craxal** [comment]
@Alonnixx Here are some follow-up questions for you:
* What kind of storage service are you referring to? Blobs, ADLS Gen2 Blobs, or File Shares?
* When you say you want to "search down the folder structure", are you saying you want a flat list of search results similar to File Explorer in Windows?

Please note that we are limited by what APIs the Azure platform provides. For example, there is no API for file shares that supports listing multiple levels of folders, so we would not be able to support searching multiple levels at once.

**Comment by Alonnixx** [comment]
Hi carxal, sorry for my late reply. My use case is mainly with ADLS2 storage, and yes, I was looking to get an advanced, windows-like search option that scans sub-folders for objects. I gathered from your reply that the API may not support such actions 😒, so I reluctantly concede...
