### ISSUE TITLE
The first invisible action doesn't appear on the context menu if press arrow down key to select it

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#8047]
**Storage Explorer Version:** 1.35.0-dev (98)
**Build Number:** 20240708.1
**Branch:** main
**Platform/OS:** Windows11/Windows 10/Linux Ubuntu 22.04
**Architecture:** arm64/x64/x64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Right click the blob container. 
3. The context menu appears. (Make sure 'Pin to Quick Access' action is invisible)
4. Press arrow down key to select the action.
5. Check whether 'Pin to Quick Access' action appears.

## Expected Experience ##
 'Pin to Quick Access' action appears.

## Actual Experience ##
 'Pin to Quick Access' action doesn't appear.
![invisible](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/032d8dc0-6913-401e-b924-94506cc4d259)

**Comment by craxal** [comment]
This looks like a Windows menu glitch of some kind, not something we have any control over.
