### ISSUE TITLE
 Unable to authenticate version 1.34

### ISSUE THREAD

**Issue by TakataMichiyoshi** [microsoft/AzureStorageExplorer#8049]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.34

### Regression From

1.31

### Architecture

i86

### Platform

All

### OS Version

windows11

### Bug Description

I am experiencing an authentication issue with Storage Explorer version 1.34. In version 1.31, authentication via browser and other methods works without any problems. However, in version 1.34, the browser does not open, and I am unable to authenticate. Reverting back to version 1.31 resolves the issue. I believe this is a bug and would appreciate a fix for it.

### Steps to Reproduce

1. Update to Storage Explorer version 1.34.
2. Attempt to authenticate using the browser or any other method.

### Actual Experience

The browser does not open, and authentication fails.

unable to authenticate all methods

### Expected Experience

The browser should open, allowing for successful authentication.

### Additional Context

Reverting back to Storage Explorer version 1.31 resolves the issue, and authentication works as expected.

Thank you for your attention to this matter.

**Comment by craxal** [comment]
@TakataMichiyoshi What about versions in between 1.31.0 and 1.34.0? Do any of those versions authenticate successfully?

**Comment by TakataMichiyoshi** [comment]
Version 1.30, 1.31, 1.33.1 works fine today, but version 1.34.0 does not progress beyond the initial state. Thank you for your reply.

**Comment by TakataMichiyoshi** [comment]
1.34.0
![image](https://github.com/user-attachments/assets/18484cd6-1188-430a-8c22-92ceaa9660d6)

**Comment by TakataMichiyoshi** [comment]
1.33.1
![image](https://github.com/user-attachments/assets/7001e6a7-195f-4a9e-bdb0-480733fe6367)

**Comment by TakataMichiyoshi** [comment]
Version 1.34 is stuck on loading and won't progress. The Help, View, Edit, and File menus are all unresponsive.

**Comment by MRayermannMSFT** [comment]
@TakataMichiyoshi do you know if you have .NET 8 installed? If you don't know, you can share the output you see of running `dotnet --info` in PowerShell, like:

```
PS C:\Users\username> dotnet --info
.NET SDK:
 Version:           8.0.400-preview.0.24324.5
 Commit:            736a2616db
 Workload version:  8.0.400-manifests.fbc8f109
 MSBuild version:   17.11.0+1192b22fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.26120
 OS Platform: Windows
 RID:         win-arm64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.400-preview.0.24324.5\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [aspire]
   Installation Source: VS 17.12.35101.237
   Manifest Version:    8.0.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.0.0\WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      8.0.5
  Architecture: arm64
  Commit:       087e15321b

.NET SDKs installed:
  8.0.400-preview.0.24324.5 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x64   [C:\Program Files\dotnet\x64]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation]
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by TakataMichiyoshi** [comment]
.NET SDK:
 Version:   8.0.100-preview.5.23303.2
 Commit:    3fe444af72

ランタイム環境:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.5.23303.2\

.NET workloads installed:
表示するインストール済みワークロードはありません。

Host:
  Version:      8.0.0-preview.5.23280.8
  Architecture: x64
  Commit:       bc78804f5d

.NET SDKs installed:
  8.0.100-preview.5.23303.2 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0-preview.5.23302.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.5.23280.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.5.23302.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by TakataMichiyoshi** [comment]
The Japanese '表示するインストール済みワークロードはありません', and it's means 'no installed workload'.
Thank you for your cooperation.

**Comment by TakataMichiyoshi** [comment]
After updating .NET and the SDK to the latest versions, everything started working properly with version 1.34.0. Thank you for your assistance.

**Comment by TakataMichiyoshi** [comment]
.NET SDK:
 Version:           8.0.303
 Commit:            29ab8e3268
 Workload version:  8.0.300-manifests.c915c39d
 MSBuild version:   17.10.4+10fbfbf2e

ランタイム環境:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.303\

インストール済みの .NET ワークロード:
表示するインストール済みワークロードはありません。

Host:
  Version:      8.0.7
  Architecture: x64
  Commit:       2aade6beb0

.NET SDKs installed:
  8.0.100-preview.5.23303.2 [C:\Program Files\dotnet\sdk]
  8.0.303 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0-preview.5.23302.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.5.23280.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.5.23302.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by TakataMichiyoshi** [comment]
![image](https://github.com/user-attachments/assets/8c9ea79d-4d18-4907-8188-be8a4cebb3a1)
