### ISSUE TITLE
Not able to access resources

### ISSUE THREAD

**Issue by athusa** [microsoft/AzureStorageExplorer#8054]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.34.0(99)

### Architecture

x64

### Storage Explorer Build Number

20240523.2

### Platform

Windows

### Bug Description

{
  "name": null,
  "message": "\"{\\n  \\\"name\\\": \\\"Node Fetch Error\\\",\\n  \\\"message\\\": \\\"Connect Timeout Error\\\",\\n  \\\"stack\\\": \\\"ConnectTimeoutError: Connect Timeout Error\\\\n    at onConnectTimeout (C:\\\\\\\\Program Files\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\out\\\\\\\\app\\\\\\\\index.js:62:36240)\\\\n    at C:\\\\\\\\Program Files\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\out\\\\\\\\app\\\\\\\\index.js:62:35582\\\\n    at Immediate._onImmediate (C:\\\\\\\\Program Files\\\\\\\\Microsoft Azure Storage Explorer\\\\\\\\resources\\\\\\\\app\\\\\\\\out\\\\\\\\app\\\\\\\\index.js:62:35945)\\\\n    at process.processImmediate (node:internal/timers:478:21)\\\",\\n  \\\"cause\\\": {\\n    \\\"cause\\\": {\\n      \\\"name\\\": \\\"ConnectTimeoutError\\\",\\n      \\\"code\\\": \\\"UND_ERR_CONNECT_TIMEOUT\\\"\\n    }\\n  },\\n  \\\"code\\\": \\\"UND_ERR_CONNECT_TIMEOUT\\\"\\n}\""
}

### Steps to Reproduce

Launch explorer
and authenticated 

### Actual Experience

it should show resources in the 
![image](https://github.com/microsoft/AzureStorageExplorer/assets/95520040/92e8492f-cf33-412f-a69b-ff2223882303)
explorer

**Comment by craxal** [comment]
@athusa Are you trying to connect through a proxy server? Have you configured Storage Explorer proxy settings accordingly?
