### ISSUE TITLE
It displays as expired when attaching one queue via SAS URL generated by an access policy

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8055]
**Storage Explorer Version**: 1.35.0-dev (98)
**Build Number**: 20240711.2
**Branch**: main
**Platform/OS**: Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.5(Apple M1 Pro)
**Architecture**: arm64/x64/x64/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.33.1)

## Steps to Reproduce ##
1. Expand one storage account -> Queues.
2. Create a queue then right click it -> Click 'Manage Stored Access Policies...'.
3. Add one access policy (keep the default start and expire time).
4. Attach the queue via SAS URL generated by the access policy.
5. Go to the attached queue.
6. Check whether it doesn't display as expired.

## Expected Experience ##
It doesn't display as expired.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/f9009766-f9b2-4cbb-9630-1e968011847a)

## Actual Experience ##
It displays as expired.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/5714a8f7-8f43-4186-9496-f607cf03b382)

## Additional Context ##
No expire notification shows if open the attached queue.

**Comment by craxal** [comment]
Small coding error. `isExpired()` is returning "unknown", and we should be testing for `isExpired() === true`.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240717.2. Reproduce. So, we are going to reopen it.
![image](https://github.com/user-attachments/assets/8458e9d5-04fa-4c18-bb14-9287d89110cb)

**Comment by craxal** [comment]
Oops, didn't quite integrate the changes correctly. Published a new package.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240719.6. Fixed.
![image](https://github.com/user-attachments/assets/1775f92c-3438-4535-81e1-f0c5e7282dc4)
