### ISSUE TITLE
Cannot list file share with Reader and Storage File Data SMB Share Reader 

### ISSUE THREAD

**Issue by yangchengs** [microsoft/AzureStorageExplorer#8057]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.34.0

### Architecture

x64

### Storage Explorer Build Number

20240523.2

### Platform

Windows

### Bug Description

I have a user which has roles over a storage account
Reader
Storage File Data SMB Share Reader 

The user can view file share and files from Azure Portal 

In azure portal, it calls the REST API to list file shares and it succeeded.

https://management.azure.com/subscriptions/1ccb1bf8-f93f-42dc-886b-acdbc6f972eb/resourceGroups/testrg1/providers/Microsoft.Storage/storageAccounts/yangchengtest1/fileServices/default/shares?%24skipToken=&%24maxpagesize=20&%24filter=&%24expand=&api-version=2019-06-01

From storage explorer version 1.34.0, it cannot list file shares.

Unable to retrieve child resources

ProducerError:{
  "name": "Error",
  "message": "Unable to perform operation 'FileServiceClient.listSharesSegment'. No suitable credentials provided.",
  "stack": "Error: Unable to perform operation 'FileServiceClient.listSharesSegment'. No suitable credentials provided.\n    at sl.runOperation (C:\\Users\\yangshen\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\file-extension\\dist\\src\\index.js:38:5815)\n    at sl.listSharesSegment (C:\\Users\\yangshen\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\file-extension\\dist\\src\\index.js:77:17070)\n    at FileShareNodeProducer.produceFileShareNodes (C:\\Users\\yangshen\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\file-extension\\dist\\src\\index.js:77:64687)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Azure.Storage.FileShareProducer.produceFileShareNodes (C:\\Users\\yangshen\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\file-extension\\dist\\src\\index.js:80:13570)\n    at async Ye.executeOperation (C:\\Users\\yangshen\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:3:2742)\n    at async Vt._handleExecuteRequest (C:\\Users\\yangshen\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:7:915)\n    at async Vt._handleMessage (C:\\Users\\yangshen\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:6:30805)\n    at async C:\\Users\\yangshen\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:6:28316"
}

### Steps to Reproduce

1. Launch storage explorer.
2. Login with Microsoft Entra Id, the user has Reader and Storage File Data SMB Share Reader.
3. Go to file share to list file shares.

### Actual Experience

Unable to retrieve child resources

ProducerError:{
  "name": "Error",
  "message": "Unable to perform operation 'FileServiceClient.listSharesSegment'. No suitable credentials provided.",
  "stack": "Error: Unable to perform operation 'FileServiceClient.listSharesSegment'. No suitable credentials provided.\n    at sl.runOperation (C:\\Users\\yangshen\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\file-extension\\dist\\src\\index.js:38:5815)\n    at sl.listSharesSegment (C:\\Users\\yangshen\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\file-extension\\dist\\src\\index.js:77:17070)\n    at FileShareNodeProducer.produceFileShareNodes (C:\\Users\\yangshen\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\file-extension\\dist\\src\\index.js:77:64687)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Azure.Storage.FileShareProducer.produceFileShareNodes (C:\\Users\\yangshen\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\file-extension\\dist\\src\\index.js:80:13570)\n    at async Ye.executeOperation (C:\\Users\\yangshen\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:3:2742)\n    at async Vt._handleExecuteRequest (C:\\Users\\yangshen\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:7:915)\n    at async Vt._handleMessage (C:\\Users\\yangshen\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:6:30805)\n    at async C:\\Users\\yangshen\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js:6:28316"
}

### Expected Experience

I can view file shares as I can view and list from azure portal

**Comment by JasonYeMSFT** [comment]
@yangchengs Storage Explorer hasn't implemented the OAuth support for file share yet. As of today you will need storage account keys to access file share resources in Storage Explorer.
