### ISSUE TITLE
It would be better to remove 'display' from the descriptions in 'Rename Quick Access Item' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8058]
**Storage Explorer Version**: 1.35.0-dev (98)
**Build Number**: 20240712.1
**Branch**: main
**Platform/OS**: Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.5(Apple M1 Pro)
**Architecture**: arm64/x64/x64/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Select one ADLS Gen2 storage account -> Pin it to the 'Quick Access' node.
2. Right click the QA item -> Click 'Rename'.
3. Observe the description in the rename dialog.

## Expected Experience ##
It would be better to remove 'display' from the description.
It would be better to use an appropriate name instead of 'Display name'.

## Actual Experience ##
It indicates to change the display name.
![image](https://github.com/user-attachments/assets/660c15c5-d7eb-4990-a029-c9571c447e2c)

## Additional Context ##
If using display name in the rename dialog, it doesn't match the display name in the properties.

**Comment by MRayermannMSFT** [comment]
Changed property name to "Node Display Name". That property is specifically for the node's name as a whole, which includes the status of the thing (aka the part in parens) and the display name of the thing (thing in this case being the quick access item).

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240717.2. the property name has been updated to 'Node Display Name'.
![image](https://github.com/user-attachments/assets/13454b7d-9baf-4222-a47e-0f2cb4b174f7)
