### ISSUE TITLE
No dialog pops up after clicking ‘Telemetry Settings’ under 'Help' menu

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8063]
**Storage Explorer Version**: 1.35.0-dev (98)
**Build Number**: 20240718.1
**Branch**: main
**Platform/OS**: Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.5(Apple M1 Pro)
**Architecture**: arm64/x64/x64/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.34.0)

## Steps to Reproduce ##
1. Open Storage Explorer -> Click 'Help -> Telemetry Settings'.
2. Check whether the 'Telemetry Settings' dialog pops up.

## Expected Experience ##
The 'Telemetry Settings' dialog pops up.
![image](https://github.com/user-attachments/assets/f524c037-fc85-4e27-a5ff-a34f18b798f2)
## Actual Experience ##
No dialog pops up.

**Comment by craxal** [comment]
Same root cause as #7997. Currently investigating.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240719.6. Fixed.
![image](https://github.com/user-attachments/assets/dce217b8-7142-421d-b199-b995265bbad0)
