### ISSUE TITLE
A confirmation dialog pops up when pasting one blob container which is copied from a QA directory 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8064]
**Storage Explorer Version**: 1.35.0-dev (98)
**Build Number**: 20240718.1
**Branch**: main
**Platform/OS**: Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.5(Apple M1 Pro)
**Architecture**: arm64/x64/x64/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one folder.
3. Right click the folder -> Click 'Pin to Quick Access'.
4. Right click the QA directory -> Click 'Copy Blob Container'.
5. Select one storage account -> Paste the blob container.
6. Check whether no dialog pops up.

## Expected Experience ##
No confirmation dialog pops up.

## Actual Experience ##
A confirmation dialog pops up.
![image](https://github.com/user-attachments/assets/ef77ec6d-cdfe-40aa-b57f-99d502aae4f0)

**Comment by craxal** [comment]
@JasonYeMSFT @MRayermannMSFT @RichardMSFT Is this expected behavior? Seems like it should be, but I suppose that depends on the type of connection.

**Comment by JasonYeMSFT** [comment]
This is a bug. The "getProperty" call is trying to make to a path including the directory's path. However, I think we should just disable the copy action on attached directories since it's unclear what the paste action should do.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240821.1. The 'Copy Blob Container' action has been disabled for one QA directory.
![image](https://github.com/user-attachments/assets/9061c1ff-9349-4eba-b116-3e206e1756a6)
