### ISSUE TITLE
It would better to add a blank line between the two sentences on the prompt dialog when breaking lease for one blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8067]
**Storage Explorer Version**: 1.35.0-dev (99)
**Build Number**: 20240719.6
**Branch**: main
**Platform/OS**: Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.5(Apple M1 Pro)
**Architecture**: arm64/x64/x64/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Acquire lease for the blob container.
3. Right click the leased blob container -> Click 'Break Lease'.
4. Observe the contents on the prompt dialog.
5. Check whether there is a blank line between the two sentences.

## Expected Experience ##
It would be better to add a blank line between the two sentences.

## Actual Experience ##
There is no blank line between the two sentences.
![image](https://github.com/user-attachments/assets/bda6b2ae-23c0-45cc-92dd-19763088cefe)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240724.1. Fixed.
![image](https://github.com/user-attachments/assets/42b722c4-dac9-4cb1-bef5-b2372c0913de)
