### ISSUE TITLE
The value of the 'Tag Query' field is inconsistent between original and split blob containers when applying tag query in the original blob container

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#8068]
**Storage Explorer Version:** 1.35.0-dev (99)
**Build Number:** 20240719.6
**Branch:** main
**Platform/OS:** Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.5(Apple M1 Pro)
**Architecture:** arm64/x64/x64/x64
**How Found:** Exploratory testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Open one blob container -> Upload a blob -> Add a tag for the blob (Don't use the default tag).
3. Open view options panel -> Apply the tag query.
4. Split the blob container.
5. Go to the split blob container -> Open view options panel.
6. Check whether the value of the 'Tag Query' field is consistent between original and split blob containers.

## Expected Experience ##
The value of the 'Tag Query' field is consistent.
## Actual Experience ##

The value of the 'Tag Query' field is inconsistent.
![image](https://github.com/user-attachments/assets/5763930b-faf7-4e15-982c-b708382986bc)

**Comment by craxal** [comment]
I consider this as By Design. The point of splitting tabs is so you can look at or run separate queries on the same container side by side. I don't see any reason why tab queries should mirror each other across split tabs.

**Comment by v-kellyluo** [comment]
@craxal ,Thanks for your updates!, but this issue doesn't reproduce for 'Filter by prefix' field.
![image](https://github.com/user-attachments/assets/aced81c3-1bf7-459d-8e45-58b1543f7a30)
And in the split tab, the address bar and the 'Tag Query' field is inconsistent. Could you help to take a look?
![image](https://github.com/user-attachments/assets/924b04a6-11bc-4a53-b2a5-70f5f40d77fc)
