### ISSUE TITLE
Differentiate the error contents when there is a file naming conflict

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#807]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181025.6
**Commit**: a287009c
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Open one file share -> Upload two files named 'test1.txt' 'test2.txt'.
2. Try to rename the 'test2.txt' to 'test1.txt'.
3. Check the error contents.

#### Expected Experience: ####
The error content shows '**A file** with that name already exists' like blob naming conflicts.
![blob](https://user-images.githubusercontent.com/34729022/47492225-1a63e280-d87f-11e8-9523-df9293faa7ff.png)

#### Actual Experience: ####
The error content shows '**A file or directory** with that name already exists'.
![file](https://user-images.githubusercontent.com/34729022/47492215-1637c500-d87f-11e8-9155-d38d3b6043e7.png)

**Comment by craxal** [comment]
If customers complain, we'll fix. Otherwise, we won't worry about it.
