### ISSUE TITLE
Connect to Azurite Docker Containers

### ISSUE THREAD

**Issue by philliphoff** [microsoft/AzureStorageExplorer#8073]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I would like to quickly attach to Azurite Docker containers running on non-standard ports (such as those started via .NET Aspire).

### Desired Solution

I would like Storage Explorer to auto-detect running Azurite Docker containers and offer to connect to one of them.  The explorer can look for running Azurite containers and their mapped ports (and other properties), and either automatically connect to them or prompt the user to add them.

### Alternatives and Workarounds

The alternative is to delete and then recreate the connection on each application run (hand entering the ports for each endpoint).  Another option is to use a common Azurite instance, which works but means an external dependency to running an application.  Another option is to explicitly use the "default" ports, which also works but means only a single application can run at a time (else risk collisions with other Azurite instances).

### Additional Context

.NET Aspire, in particular, creates Azurite containers and, by default, maps the endpoints to random ports on each and every run.  This constant port shifting makes using the Storage Explorer difficult as the process of removing/creating local connections is manual and tedious.

**Comment by MRayermannMSFT** [comment]
@philliphoff how exactly would Storage Explorer know that an Azurite container with mapped ports is hosting Azurite and not some other service?

**Comment by philliphoff** [comment]
@MRayermannMSFT Storage Explorer could attempt to list running docker containers that are running the standard Azurite image (e.g. `docker ps -a --format "{{.ID}}|{{.Image}}"` that returns entries like `77b5186cbafc|mcr.microsoft.com/azure-storage/azurite:3.30.0`).  It then can filter by the `mcr.microsoft.com/azure-storage/azurite` image name, grab the mapped ports from each (e.g. `docker container inspect 77b5186cbafc --format "{{.NetworkSettings.Ports}}"` that returns entries like `map[10000/tcp:[{127.0.0.1 53601}] 10001/tcp:[{127.0.0.1 53602}] 10002/tcp:[{127.0.0.1 53603}]]`).  From that, Storage Explorer should be able to create a connection (in the same way it does when Azurite is using the default port mapping).

**Comment by craxal** [comment]
@philliphoff Do you need detection for other options such as alternate host IPs or custom account names and keys? Or are the defaults with port mapping detection sufficient for now?

**Comment by philliphoff** [comment]
> Do you need detection for other options such as alternate host IPs or custom account names and keys? Or are the defaults with port mapping detection sufficient for now?

@craxal I *think* just port mapping detection will be sufficient.  (I don't *think* custom keys are involved at all.)  I'm only using Azurite with .NET Aspire  in the most basic way (see snippet below).  If Storage Explorer can connect to that out-of-the-box (or with minimal prompting), then I'll be happy.

```csharp
var builder = DistributedApplication.CreateBuilder(args);

var storage =
    builder
        .AddAzureStorage("storage")
        .RunAsEmulator(
            c =>
            {
                // NOTE: Explicit use of 3.30.0 is to avoid an Aspire issue where blobs client uses schema newer than supported by default version of emulator.
                c.WithImageTag("3.30.0");
                
                // NOTE: A random volume is used to avoid conflicts with other services running on the same machine.
                c.WithVolume("D9F6DAFF-3FD2-43A5-BA18-9D877C1960E0", "/data");
            });

builder.Build().Run();

```

**Comment by philliphoff** [comment]
@craxal Perhaps, for Mac/Linux, the Explorer can assume the default Docker path for the platform and, if that becomes a problem, then offer a app-level setting where the user can point to their particular Docker install path.  (This would also allow for those users that prefer Docker alternatives like Podman.)

**Comment by craxal** [comment]
I think we'll worry about alternate paths once user feedback starts coming in.

For macOS, the `PATH` issue is solved by providing a custom value in the Info.plist.

Linux, unfortunately, is more complicated than I anticipated. In theory, we should be able to create a symlink to the Docker binary within the snap's directory structure, but I'm having trouble getting that to build. I will continue to work on this, but with the amount of Linux usage we are currently seeing, I think we can postpone Linux support for this feature for 1.36.0.
