### ISSUE TITLE
Display Content encoding when previewing and browsing text files

### ISSUE THREAD

**Issue by jasonhorner** [microsoft/AzureStorageExplorer#8074]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

often I need to see the underlying encoding of a file type at a glance when troubleshooting. however I currently have to download the file and open in another editior. this process is cumbersome and time consuming

### Desired Solution

I'd like to be able to see the encoding of text files at a glance from both the preview panes and the browsing experience

**Comment by jasonhorner** [comment]
see this thread where I believe a working prototype of file encodings was built for the preview feature:
https://github.com/microsoft/AzureStorageExplorer/issues/7546

**Comment by jasonhorner** [comment]
here is a sample image of the possible encodings. note this would only be for text files (txt ,csv etc)
![image](https://github.com/user-attachments/assets/7d370f22-bb95-4892-abde-bfa02ea8ba53)

I would expect it to show up next to the content type field in the browser with the label Encoding:
![image](https://github.com/user-attachments/assets/393bd2be-826c-422b-b91a-d0b1dd09e95a)
it would be blank for folders and perhaps say binary for binary files files

**Comment by MRayermannMSFT** [comment]
@jasonhorner for showing encoding when viewing the list of blobs in a container, I don't think that will be possible, as that information is not surfaced by the service. We'll investigate the text preview aspect of this request.

**Comment by craxal** [comment]
Let's investigate to see whether this is feasible. At the very least, we may be able to add an encoding selector for text preview. We can add auto-detection afterwards.

**Comment by craxal** [comment]
Auto-detection turned out to be easy, very similar to how we do it for CSV/tabular data. We'll have this as well as an encoding selector for text preview.
