### ISSUE TITLE
It's better to resize the command field on the 'Connect File Share to VM' dialog to ensure there is no scrollbar

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8079]
**Storage Explorer Version**: 1.35.0-dev (99)
**Build Number**: 20240724.1
**Branch**: main
**Platform/OS**: Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.5(Apple M1 Pro)
**Architecture**: arm64/x64/x64/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share named 'file12345file12345file12345file12345file12345file12345file12345'.
3. Go to the file share explorer -> Click 'Connect VM'.
4. Check whether there is no scrollbar for the command field.

## Expected Experience ##
It's better to resize the command field to ensure there is no scrollbar.

## Actual Experience ##
There is a scrollbar for the command field.
![image](https://github.com/user-attachments/assets/8905b345-e80f-4ad6-abe0-0f31895472a7)

**Comment by craxal** [comment]
Won't fix. Users very rarely are going to have file share names that long. And a scrollbar on the text area is fine instead of the dialog.
