### ISSUE TITLE
Not able to open images (as preview) from Azure Explorer

### ISSUE THREAD

**Issue by LWiegman** [Microsoft/AzureStorageExplorer#808]
**Storage Explorer Version**: 1.4.4
**Platform/OS Version**: Windows 10
**Architecture**: 
**Regression From**: no previous versions used

#### Steps to Reproduce: ####
In blob storage, click on an image in the blob and select "Open" in Storage Explorer
Not sure what/how to install to enable this. 

#### Expected Experience: ####
That the image opens, i.e. you see a preview within Storage Explorer

#### Actual Experience: ####
Unable to open image. Error: This file does not have a program associated with it for performing this action. Please install a program or, if already installed, create an association in the Default Programs control panel.

**Comment by MRayermannMSFT** [comment]
Hi @LWiegman , can you tell me if this error is coming from Storage Explorer, or Windows? I would assume it is coming from windows, as we do not have that error message anywhere in our code base. Also, have you:
- Tried doing what the message says? 
- Downloading the file, and then double clicking on it?

**Comment by LWiegman** [comment]
Hi Matthew,
Problem solved! It was indeed Windows and it was very stupid: no standard viewer was selected to open jpeg/png files. So no need to download any extension (as I thought). Downloading the file worked from the start, but I wanted to avoid downloading all files before being able to view them. Thanks for the response!
Linda

**Comment by MRayermannMSFT** [comment]
Cool. Glad you were able to get unblocked. 😄
