### ISSUE TITLE
It is better to resize the 'Shared Access Signature' dialog for one storage account so that no scrollbar appears

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8080]
**Storage Explorer Version**: 1.35.0-dev (99)
**Build Number**: 20240724.1
**Branch**: main
**Platform/OS**: Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.5(Apple M1 Pro)
**Architecture**: arm64/x64/x64/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Right click one storage account -> Click 'Get Shared Access Signature...'.
2. Change the start time to make it is greater than expiry time.
3. There is an error message.
4. Check whether there is no scrollbar.

## Expected Experience ##
It is better to resize the dialog to ensure that no scrollbar appear.

## Actual Experience ##
There is a scrollbar.
![image](https://github.com/user-attachments/assets/340d1321-a995-4008-b2c3-bf2598f35096)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240726.3. Fixed.
![image](https://github.com/user-attachments/assets/c52f8504-c12e-4ee6-a540-c35b08fcf71c)
