### ISSUE TITLE
Can't download blob: 000 : File Creation Error destination file has no known flags that could cause issue (current set: 0) and azcopy was unable to clear the flag(s), so access will be denied: The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by andrePKI** [microsoft/AzureStorageExplorer#8082]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.34.0

### Architecture

x64

### Storage Explorer Build Number

20240523.2

### Platform

Windows

### OS Version

Windows Server 2016 Datacenter

### Bug Description

Can't download blob. Apparently something with the local file name. I can create a file in that location with that name using Notepad.
This is the log file of azcopy
2024/07/24 09:37:00 AzcopyVersion  10.23.0
2024/07/24 09:37:00 OS-Environment  windows
2024/07/24 09:37:00 OS-Architecture  amd64
2024/07/24 09:37:00 Log times are in UTC. Local time is 24 Jul 2024 11:37:00
2024/07/24 09:37:01 ISO 8601 START TIME: to copy files that changed before or after this job started, use the parameter --include-before=2024-07-24T09:36:55Z or --include-after=2024-07-24T09:36:55Z
2024/07/24 09:37:01 Any empty folders will not be processed, because source and/or destination doesn't have full folder support
2024/07/24 09:37:01 Job-Command copy https://gsia001itweup01ltssts01.blob.core.windows.net/aaaingestfailure/4f31b30eb5c4435189a85858cdab61eb-httpsvk8kd001jm9eq5xecp9but4r.blob.core.windows.net20240723-dc-dc-azurediagnosticssiemAzureDiagnosticsRaweh-am-azurediagnostics-partition-0-seq-285606464-285606509-count-46-y0m.multijson.gz?se=2024-08-23t09%3A36%3A59z&sig=-REDACTED-&sp=rl&sr=c&sv=2023-01-03 C:\Users\ad062685\AppData\Local\Temp\2\17218138199254\4f31b30eb5c4435189a85858cdab61eb-httpsvk8kd001jm9eq5xecp9but4r.blob.core.windows.net20240723-dc-dc-azurediagnosticssiemAzureDiagnosticsRaweh-am-azurediagnostics-partition-0-seq-285606464-285606509-count-46-y0m.multijson.gz --output-type=json --cancel-from-stdin --overwrite=prompt --check-md5 FailIfDifferent --from-to=BlobLocal --blob-type BlockBlob --recursive --log-level=INFO 
2024/07/24 09:37:01 Number of CPUs: 4
2024/07/24 09:37:01 Max file buffer RAM 2.000 GB
2024/07/24 09:37:01 Max concurrent network operations:  will be dynamically tuned up to 3000 (Based on auto-tuning limit. Set AZCOPY_CONCURRENCY_VALUE environment variable to override)
2024/07/24 09:37:01 Check CPU usage when dynamically tuning concurrency: true (Based on hard-coded default. Set AZCOPY_TUNE_TO_CPU environment variable to true or false override)
2024/07/24 09:37:01 Max concurrent transfer initiation routines: 64 (Based on hard-coded default. Set AZCOPY_CONCURRENT_FILES environment variable to override)
2024/07/24 09:37:01 Max enumeration routines: 16 (Based on hard-coded default. Set AZCOPY_CONCURRENT_SCAN environment variable to override)
2024/07/24 09:37:01 Parallelize getting file properties (file.Stat): false (Based on AZCOPY_PARALLEL_STAT_FILES environment variable)
2024/07/24 09:37:01 Max open files when downloading: 2147479959 (auto-computed)
2024/07/24 09:37:01 Final job part has been created
2024/07/24 09:37:01 Final job part has been scheduled
2024/07/24 09:37:01 Trying 4 concurrent connections (initial starting point)
2024/07/24 09:37:01 ERR: [P#0-T#0] DOWNLOADFAILED: https://gsia001itweup01ltssts01.blob.core.windows.net/aaaingestfailure/4f31b30eb5c4435189a85858cdab61eb-httpsvk8kd001jm9eq5xecp9but4r.blob.core.windows.net20240723-dc-dc-azurediagnosticssiemAzureDiagnosticsRaweh-am-azurediagnostics-partition-0-seq-285606464-285606509-count-46-y0m.multijson.gz : 000 : File Creation Error destination file has no known flags that could cause issue (current set: 0) and azcopy was unable to clear the flag(s), so access will be denied: The filename, directory name, or volume label syntax is incorrect.
   Dst: \\?\C:\Users\ad062685\AppData\Local\Temp\2\17218138199254\4f31b30eb5c4435189a85858cdab61eb-httpsvk8kd001jm9eq5xecp9but4r.blob.core.windows.net20240723-dc-dc-azurediagnosticssiemAzureDiagnosticsRaweh-am-azurediagnostics-partition-0-seq-285606464-285606509-count-46-y0m.multijson.gz
2024/07/24 09:37:01 INFO: [P#0-T#0] https://gsia001itweup01ltssts01.blob.core.windows.net/aaaingestfailure/4f31b30eb5c4435189a85858cdab61eb-httpsvk8kd001jm9eq5xecp9but4r.blob.core.windows.net20240723-dc-dc-azurediagnosticssiemAzureDiagnosticsRaweh-am-azurediagnostics-partition-0-seq-285606464-285606509-count-46-y0m.multijson.gz Deleting incomplete destination file Dst: \\?\C:\Users\ad062685\AppData\Local\Temp\2\17218138199254\4f31b30eb5c4435189a85858cdab61eb-httpsvk8kd001jm9eq5xecp9but4r.blob.core.windows.net20240723-dc-dc-azurediagnosticssiemAzureDiagnosticsRaweh-am-azurediagnostics-partition-0-seq-285606464-285606509-count-46-y0m.multijson.gz
2024/07/24 09:37:01 ERR: [P#0-T#0] \\?\C:\Users\ad062685\AppData\Local\Temp\2\17218138199254\4f31b30eb5c4435189a85858cdab61eb-httpsvk8kd001jm9eq5xecp9but4r.blob.core.windows.net20240723-dc-dc-azurediagnosticssiemAzureDiagnosticsRaweh-am-azurediagnostics-partition-0-seq-285606464-285606509-count-46-y0m.multijson.gz: 0: Delete File Error -remove \\?\C:\Users\ad062685\AppData\Local\Temp\2\17218138199254\.azDownload-b1dd3689-27f4-8844-7fca-1d942de0118c-4f31b30eb5c4435189a85858cdab61eb-httpsvk8kd001jm9eq5xecp9but4r.blob.core.windows.net20240723-dc-dc-azurediagnosticssiemAzureDiagnosticsRaweh-am-azurediagnostics-partition-0-seq-285606464-285606509-count-46-y0m.multijson.gz: The filename, directory name, or volume label syntax is incorrect.. X-Ms-Request-Id:

2024/07/24 09:37:01 JobID=b1dd3689-27f4-8844-7fca-1d942de0118c, Part#=0, TransfersDone=1 of 1
2024/07/24 09:37:01 all parts of entire Job b1dd3689-27f4-8844-7fca-1d942de0118c successfully completed, cancelled or paused
2024/07/24 09:37:01 is part of Job which 1 total number of parts done 
2024/07/24 09:37:03 PERF: primary performance constraint is Unknown. States: C:  0, R:  0, W:  0, F:  0, H:  0, B:  0, S:  0, P:  0, Q:  0, D:  0, E:  0, T:  0, GRs:  4
2024/07/24 09:37:03 0.0 %, 0 Done, 1 Failed, 0 Pending, 0 Skipped, 1 Total, 
2024/07/24 09:37:03 Closing Log

### Steps to Reproduce

Open Storage Explorer, 
browse to Blob container, 
select blob, 
double click or select Download

I can download other blobs fine
![image](https://github.com/user-attachments/assets/afd7a47b-f8db-4e5f-9a9f-43115a7e2977)

### Actual Experience

Error message

### Expected Experience

Download successful

**Comment by craxal** [comment]
@andrePKI That blob name is pretty long all on its own (more than 220 characters). Unless the path of the parent directory is very short, it seems like you could be hitting the Windows path character limit. What happens if you shorten the blob name? Or enable long paths?

**Comment by andrePKI** [comment]
Well, I  can create a file with the same name from Notepad in the same
location as stated.
So I'm afraid it is something else.
Otherwise, maybe it is the full path - can I control where (what folder)
the blob is downloaded to?
KR,
André

Op do 25 jul 2024 19:49 schreef Craig Alvord ***@***.***>:

**Comment by craxal** [comment]
You most certainly can control the download location. When selecting Download, a system dialog opens and allows you to select the destination folder.

@JasonYeMSFT I think the key issue is highlighted by the message: "The filename, directory name, or volume label syntax is incorrect." The destination begins with "\?". Shouldn't this be "\\?"?

**Comment by andrePKI** [comment]
Hi, I still have the issue woth Storage Explorere 1.35.0 (100). But I think the issue is with azcopy (10.26.0)
I have enabled long file name support `(HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\ControlFileSystem\LongPathsEnabled=1` and rebooted)
and I can create files with those long names
```
   Directory: C:\temp\piep\aabbingestfailure


Mode                LastWriteTime         Length Name                                                                                                                                                                            
----                -------------         ------ ----                                                                                                                                                                            
-a----        8/28/2024  12:17 PM              0 8d6d4cf709304396bdd9a11d7b5c6d64-https4yrkd000th7bt9pnd37khz5p.blob.core.windows.net20240827-dc-dc-azurediagnosticssiemAzureDiagnosticsRaweh-am-azurediagnostics-partition-2-seq
                                                 -345346010-345346151-count-142-aqp.multijson.gz                                                                                                                                 
[...]
[...]
PS C:\temp\piep\aabbingestfailure> $f=dir *.gz

PS C:\temp\piep\aabbingestfailure> $f.FullName.Length
254
```

But still I get errors from azcopy
```
$env:AZCOPY_CRED_TYPE = "Anonymous";
$env:AZCOPY_CONCURRENCY_VALUE = "AUTO";
#& 'C:\Program Files\azcopy\azcopy.exe' copy "https://gsia001itweup01ltssts01.blob.core.windows.net/aabbingestfailure/*?sv=2023-01-03&se=2024-09-27T09%3A37%3A43Z&sr=c&sp=rl&sig=apCP8KCpqX%2BBTf2tDMV6YIHRsKfL207yQEHstmgtboY%3D" "C:\Temp\piep" --overwrite=prompt --check-md5 FailIfDifferent --from-to=BlobLocal --list-of-files "C:\Users\ad062685\AppData\Local\Temp\5\stg-exp-azcopy-eb03c51c-a391-4d1b-b314-76d41608c562.txt" --recursive --log-level=INFO;
& 'C:\Program Files\azcopy\azcopy.exe' copy "https://gsia001itweup01ltssts01.blob.core.windows.net/aabbingestfailure/?sv=<REDACTED>" "C:\Temp\piep" --overwrite=prompt --check-md5 FailIfDifferent --from-to=BlobLocal --recursive=true
$env:AZCOPY_CRED_TYPE = "";
$env:AZCOPY_CONCURRENCY_VALUE = "";
```
with errors
```
2024/08/28 10:15:20 ERR: [P#0-T#17] DOWNLOADFAILED: https://gsia001itweup01ltssts01.blob.core.windows.net/aabbingestfailure/8d6d4cf709304396bdd9a11d7b5c6d64-https4yrkd000th7bt9pnd37khz5p.blob.core.windows.net20240827-dc-dc-azurediagnosticssiemAzureDiagnosticsRaweh-am-azurediagnostics-partition-2-seq-345346010-345346151-count-142-aqp.multijson.gz : 000 : File Creation Error destination file has no known flags that could cause issue (current set: 0) and azcopy was unable to clear the flag(s), so access will be denied: The filename, directory name, or volume label syntax is incorrect.
   Dst: \\?\C:\Temp\piep\aabbingestfailure\8d6d4cf709304396bdd9a11d7b5c6d64-https4yrkd000th7bt9pnd37khz5p.blob.core.windows.net20240827-dc-dc-azurediagnosticssiemAzureDiagnosticsRaweh-am-azurediagnostics-partition-2-seq-345346010-345346151-count-142-aqp.multijson.gz
[...]
2024/08/28 10:15:20 INFO: [P#0-T#17] https://gsia001itweup01ltssts01.blob.core.windows.net/aabbingestfailure/8d6d4cf709304396bdd9a11d7b5c6d64-https4yrkd000th7bt9pnd37khz5p.blob.core.windows.net20240827-dc-dc-azurediagnosticssiemAzureDiagnosticsRaweh-am-azurediagnostics-partition-2-seq-345346010-345346151-count-142-aqp.multijson.gz Deleting incomplete destination file Dst: \\?\C:\Temp\piep\aabbingestfailure\8d6d4cf709304396bdd9a11d7b5c6d64-https4yrkd000th7bt9pnd37khz5p.blob.core.windows.net20240827-dc-dc-azurediagnosticssiemAzureDiagnosticsRaweh-am-azurediagnostics-partition-2-seq-345346010-345346151-count-142-aqp.multijson.gz
```

I can ofcourse copy 1 by 1 and specify the (shorter) target file name. But that defeats the purpose of automation.
Meanwhile I have fixed it by first do azcopy list, then copy blobs one by one, replacing the file name with a shorter one.

**Comment by craxal** [comment]
@JasonYeMSFT Can you provide any insight? The user here is getting the error "The filename, directory name, or volume label syntax is incorrect."

**Comment by JasonYeMSFT** [comment]
@andrePKI File systems have length limits for each segment in the file path, which is different from the length limit of the total path. Enabling long file path support in Windows doesn't make it possible to create files whose segments exceed the length limit. It's hard for us to know what that limit is because it's file system dependent.

Your best action is to try to stop giving such long names to your blobs. By default, when AzCopy downloads a file, it writes to a temporary file with a `.azDownload-<36 char jobid>-<your_real_file_name>` which makes it easier to exceed the segment length limit. If that's the case, you may be able to work around the issue by adding an environment variable `AZCOPY_DOWNLOAD_TO_TEMP_PATH:false` in the process that executes AzCopy command but that won't work if you blob name itself exceeds the segment length limit.

**Comment by andrePKI** [comment]
@JasonYeMSFT Fair enough. I was able to create files with such long names in the location, so the download to temp path could still break things. 
Problem is that I don't control the blob name, it is a result of a troubleshooting step when ingestion into Azure Data Explorer fails. I could ask the ADX team, but I would not think they will change it.
Anyway, my workaround is in place, I now first list the blobs, and download 1 by 1, substituting the long name with a shorter one for the target.
Thanks for your time and effort.
