### ISSUE TITLE
It is better to resize the dialog to ensure there is no scrollbar in the 'Error Details' dialog when creating an existing folder in one ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#8085]
**Storage Explorer Version:** 1.35.0-dev (99)
**Build Number:** 20240726.3
**Branch:** main
**Platform/OS**: Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.5(Apple M1 Pro)
**Architecture:** arm64/x64/x64/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.33.1)

## Steps to Reproduce ##

1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Create a folder.
3. Try to create a new folder using the existing name.
4. There is a failed activity log -> Click 'Details...' next to the failed activity log.
5. Check whether there is no extra scrollbar in the 'Error Details' dialog.

## Expected Experience ##
It is better to resize the dialog to ensure there is no scrollbar.
![image](https://github.com/user-attachments/assets/2a2cde93-c76b-4558-b4ce-fc19540d62ff)

## Actual Experience ##
There is an extra scrollbar.
![image](https://github.com/user-attachments/assets/6f285741-7c0f-455b-967b-361449f427a7)

**Comment by craxal** [comment]
Eh, I don't think we're going to worry about this. The scrollbar is appropriately within the text area, and no scrolling actually needs to happen to see the whole content.
