### ISSUE TITLE
The localized string is localized as 'Display Name' instead of 'Node Display Name' on the Properties panel

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8086]
**Storage Explorer Version**: 1.35.0-dev (99)
**Build Number**: 20240728.1
**Branch**: main
**Platform/OS**: Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.5(Apple M1 Pro)
**Architecture**: arm64/x64/x64/arm64
**Reproduce Languages**: All
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select '中文(简体)' -> Restart Storage Explorer.
3. Select one storage account -> Observe its Properties panel.
4. Check whether the string 'Node Display Name' is correctly localized.

## Expected Experience ##
The string 'Node Display Name' is correctly localized as '节点显示名称'.

The screenshot on ENU:
![image](https://github.com/user-attachments/assets/d1737217-3342-42c4-83a3-bb5cb6116aa9)

## Actual Experience ##
The string 'Node Display Name' is localized as '显示名称'.
![image](https://github.com/user-attachments/assets/dfc6ecd9-6331-4b82-aba3-1fc90b873a69)

**Comment by MRayermannMSFT** [comment]
This retranslation will take time. Tracking for 1.36.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240829.6. Fixed.
![image](https://github.com/user-attachments/assets/9f991d8c-2f3d-478c-9e8c-78045760dc69)
