### ISSUE TITLE
The prompt dialog is not localized completely when breaking lease one blob container

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#8087]
**Storage Explorer Version:** 1.35.0-dev (98)
**Build Number:** 20240728.1
**Branch:** main
**Platform/OS:** Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.5(Apple M1 Pro)
**Architecture:** arm64/x64/x64/arm64
**Reproduce Languages:** All
**How Found:** From running test cases
**Regression From:** Previous release (1.34.0)
## Steps to Reproduce ##

1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select 'Deutsch' -> Restart Storage Explorer.
3. Expand one storage account -> Blob Containers.
4. Create a blob container -> Right click the blob container -> Click 'Acquire Lease'.
5.  Right click the leased blob container -> Click 'Break Lease'.
6. Check whether the prompt dialog is localized completely.

## Expected Experience ##
The prompt dialog is localized completely.
![image](https://github.com/user-attachments/assets/82826e0b-25c4-45de-9a6c-03db408f44e4)

## Actual Experience ##
The prompt dialog is not localized completely.
![image](https://github.com/user-attachments/assets/f74f4368-6311-48e1-a6ed-e5d20d47db10)

**Comment by MRayermannMSFT** [comment]
This retranslation will take time. Tracking for 1.36.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240626.1. Fixed. So, we are going to close it.
![image](https://github.com/user-attachments/assets/0fe52019-0cb9-449f-9e1f-1c83459c0af1)
