### ISSUE TITLE
It would be better to adjust the size to make sure there is no scroll bar when error occurs on the 'Proxy Settings' dialog

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#8095]
**Storage Explorer Version:** 1.35.0-dev (100)
**Build Number:** 20240803.2
**Branch:** rel/1.35.0
**Platform/OS:** Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.5(Apple M1 Pro)
**Architecture:** arm64/x64/x64/arm64
**How Found:** From running test cases
**Regression From:** Previous release (1.34.0)

## Steps to Reproduce ##

1. Open Storage Explorer -> Click 'Edit -> Configure Proxy'.
2. Set Source to 'Use app proxy settings'.
3. Check 'Use a username and password' -> There is an error message.
4. Check whether there is no scroll bar.

## Expected Experience ##
There is no scroll bar.
![image](https://github.com/user-attachments/assets/6f6d8895-ccbd-44c2-975c-9f34d8c1e7b0)

## Actual Experience ##
There is a scroll bar.
![image](https://github.com/user-attachments/assets/02f32046-e446-4d30-a871-874f7ff43105)

**Comment by craxal** [comment]
@RichardMSFT Make sure to test your changes in a language whose strings tend to be longer, such as German or Russian, to make sure enough space is given to the dialog.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240807.2. Fixed.
![image](https://github.com/user-attachments/assets/14362b23-3092-4c67-bd1d-357bb9771d05)
