### ISSUE TITLE
The refresh notification flashes when opening blob containers

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#810]
Storage Explorer Version: 1.5.0
Platform/OS Version: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
Architecture: ia32/x64
Build Number: 20181026.1
Commit: 431d9b67
Regression From: Not a regression

#### Steps to Reproduce: ####
1. Expand Blob Containers which at least contain a blob container.
2. Check the toolbar during opening a blob container.

#### Expected Experience: ####
The blob container opened without refresh notification flashing.

#### Actual Experience: ####
The refresh notification flashes when opening the blob container.

**Comment by JakeRadMSFT** [comment]
@v-xianya does it go away when the window is resized?

**Comment by v-xianya** [comment]
It still exists when the window is resized.

**Comment by MRayermannMSFT** [comment]
@v-xianya, are you still seeing this repro? Thanks!

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT 
This issue still reproduces on the latest build.😶
![image](https://user-images.githubusercontent.com/41351993/71862856-13e52200-3136-11ea-82b6-baa8e8b23351.png)

**Comment by MRayermannMSFT** [comment]
@v-xianya, are you still seeing this repro? Thanks!
