### ISSUE TITLE
Fail to update access tier as Archive for blobs of GPV2 accounts

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#811]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181025.6
**Commit**: a287009c
**Regression From**: Previous release 1.4.4

#### Steps to Reproduce: ####
1. Choose one GPV2 account -> Open one blob container which contains one blob at least.
2. Try to update the current access tier as 'Archive'.
3. Check the result.

#### Expected Experience: ####
The current access tier can be updated to Archive successfully.

#### Actual Experience: ####
Fail to update the access tier as Archive with the below error.
![error](https://user-images.githubusercontent.com/34729022/47557913-7e9caa00-d944-11e8-8004-bbedcbdbe952.png)

**Comment by MRayermannMSFT** [comment]
Hmmmm...I'm not able to repro this...

**Comment by v-xuanzh** [comment]
I tried this issue on latest rel/1.5.0_20181026.3 and it didn't reproduce. Could you help to resolve it?

**Comment by MRayermannMSFT** [comment]
Sure.
