### ISSUE TITLE
Succeed to select and upload one folder when using the action 'Upload Files...' on Linux

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8119]
**Storage Explorer Version**: 1.35.0-dev (100)
**Build Number**: 20240810.1
**Branch**: rel/1.35.0
**Platform/OS**: Linux Ubuntu 22.04
**Architecture**: x64
**How Found**: From running test cases
**Regression From**: Previous release (1.34.0)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Click 'Upload -> Upload Files...'.
3. Click the 'Selected files' field -> Select one folder.
4. Click 'Open'.
5. Check whether the folder is opened in local file explorer.

## Expected Experience ##
The folder is opened in local file explorer.

## Actual Experience ##
The folder is selected on the upload dialog.

## Additional Context ##
1. This issue doesn't reproduce on Windows11/Windows 10/MacOS Sonoma 14.6(Apple M1 Pro).
2. Here is the record:
![Animation](https://github.com/user-attachments/assets/a7a02ec8-61a6-46fa-a9c3-414ff11a3859)

**Comment by craxal** [comment]
I am attempting to reproduce on my Linux machine. It's been some time since I've been able to seriously develop on Linux, so I'm ironing out some system/build issues first.

**Comment by craxal** [comment]
I'm experiencing a slight difference. When I click Open after selecting a folder, the system dialog closes, but nothing is actually selected in the "Selected files" field. Furthermore, if I double-click the folder, the dialog navigates into the folder as expected.

I'm going to chalk this up to OS weirdness. We are passing the correct values to the native OS dialog, so it's up to the system to handle it from there. We don't have any control over it.
