### ISSUE TITLE
SFI work - Disable anonymous access to blob storage

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#8121]
We need to disable anonymous access to the blob storage.  Due 12/31
[SFI-TI 2.3.3](https://eng.ms/docs/cloud-ai-platform/azure-edge-platform-aep/aep-engineering-systems/aep-documentation/disable-anonymous-blobs)

**Comment by craxal** [comment]
The linked information is in reference to a requirement that resources _used by Storage Explorer_ must disable anonymous blob access, _not_ that we remove the ability for users to change anonymous blob access settings. That work is already in progress.
