### ISSUE TITLE
Download data from containers whose key authentication is disabled

### ISSUE THREAD

**Issue by wangkenpu** [microsoft/AzureStorageExplorer#8126]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.34.0

### Architecture

x64

### Storage Explorer Build Number

20240523.2

### Platform

All

### OS Version

Windows 11

### Bug Description

Because of the Security Wave in MSFT, we have to disable key authentication for all Azure Storage accounts. Thus, we can not download the files from Azure Storage Explorer.

### Steps to Reproduce

1. Launch Storage Explorer
2. Expand a blob container node whose key authentication is disabled
3. Navigate to a folder and select a file
4. Right click the file and select download

### Actual Experience

![image](https://github.com/user-attachments/assets/218d2cdb-4297-4bdc-96c5-57da0019155f)
![image](https://github.com/user-attachments/assets/3cc881fe-eabf-4f8b-8f6e-5d5e16b71856)

### Expected Experience

Download the file to the local disk even the key is disabled, since we have login the Storage Explorer with our MSFT account.

### Additional Context

{
  "name": null,
  "message": "\"failed to perform copy command due to error: cannot start job due to error: cannot list files due to reason HEAD https://stdstoragetts01scus.blob.core.windows.net/philly-ipgsp/SpeechAssessData/Data/Xiaoying/21Century_2019/Script/449260.txt\\n--------------------------------------------------------------------------------\\nRESPONSE 403: 403 Key based authentication is not permitted on this storage account.\\nERROR CODE: KeyBasedAuthenticationNotPermitted\\n--------------------------------------------------------------------------------\\nResponse contained no body\\n--------------------------------------------------------------------------------\\n.\\n\""
}

**Comment by craxal** [comment]
@wangkenpu This is an open item (see #7775). OAuth support for file shares requires platform support, which is currently in development but not generally available yet (see https://learn.microsoft.com/azure/storage/files/authorize-oauth-rest). As a workaround, you may need to get your admin to permit local auth via key or SAS.
