### ISSUE TITLE
Show a confused description for AzCopy uploading scenarios on Release Notes

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#813]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181025.6
**Commit**: a287009c
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Open Release Notes -> Check the description for the AzCopy uploading scenarios under 'New'

#### Expected Experience: ####
It shows 'Upload of folders and files to ..., via the toolbar or dag and drop'.
#### Actual Experience: ####
It shows 'Upload of folders and files to ..., via the toolbar, **context menu** or dag and drop'. 

Actually, we have no way to upload blobs using context menu.
![releasenotes](https://user-images.githubusercontent.com/34729022/47559685-bad20980-d948-11e8-92de-f07c3195ba7b.png)

**Comment by MRayermannMSFT** [comment]
Ah, yep, good point. Uploading is not available via the context menu! Will fix.

**Comment by MRayermannMSFT** [comment]
Fixed.
