### ISSUE TITLE
There is an extra scrollbar if a warning message occurs in the upload dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8135]
**Storage Explorer Version**: 1.35.0-dev (100)
**Build Number**: 20240821.1
**Branch**: main
**Platform/OS**: Windows11/Windows 10
**Architecture**: arm64/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Click 'Upload -> Upload Folder...'.
3. Type 'test' into the field -> Press 'Enter'.
4. There is a warning message.
5. Check whether there is no extra scrollbar.

## Expected Experience ##
There is no extra scrollbar.

## Actual Experience ##
There is an extra scrollbar.
![image](https://github.com/user-attachments/assets/b066b795-596e-4e79-8183-2235b7363e96)

## Additional Context ##
This issue doesn't reproduce on Linux Ubuntu 22.04/MacOS Sonoma 14.6.1(Apple M1 Pro)

**Comment by craxal** [comment]
Related to #8178

**Comment by craxal** [comment]
@v-xianya I'm no longer reproducing this after fixing #8178. Can you double-check?

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240920.3. Fixed. So, we are going to close it.
![image](https://github.com/user-attachments/assets/35f64709-e9ff-4225-90f8-464738c7b232)
