### ISSUE TITLE
It is better to resize the 'Shared Access Signature' dialog for one blob container so that no scrollbar appears

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#8136]
**Storage Explorer Version:** 1.35.0-dev (100)
**Build Number:** 20240821.1
**Branch:** main
**Platform/OS:** Windows11/Windows 10
**Architecture:** arm64/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.35.0)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Right click the blob container -> Click 'Get Shared Access Signature...'.
3. Change the start time to make it is greater than expiry time.
4. There is an error message.
5. Check whether there is no scrollbar.

## Expected Experience ##
It is better to resize the dialog to ensure that no scrollbar appears.
![image](https://github.com/user-attachments/assets/d0b3f1db-44b2-4ae4-b547-6a3dcbd2240d)

## Actual Experience ##
There is a scrollbar.
![image](https://github.com/user-attachments/assets/10f0a121-d59f-43c9-b406-27d9e6fb1141)

**Comment by v-kellyluo** [comment]
@craxal , verified this issue on the build 20240904.1. It only fixed for regular blob containers, but it still reproduces for ADLS gen2 blob containers. So, we are going to re-open it.
![image](https://github.com/user-attachments/assets/e801bd80-a443-45b8-8b91-38c53dee3e5f)

**Comment by craxal** [comment]
Should be fixed now for ADLS Gen2.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240912.2. Fixed.
