### ISSUE TITLE
It's better to keep the behaviors consistent if the expiry time is the same as the start time when using different signing key in the shared access signature dialog for one blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8137]
**Storage Explorer Version**: 1.35.0-dev (100)
**Build Number**: 20240821.1
**Branch**: main
**Platform/OS**: Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.6(Apple M1 Pro)
**Architecture**: arm64/x64/x64/arm64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Right click one blob container -> Click 'Get Shared Access Signature...'.
3. Make the expiry time the same as the start time. 
4. There is no warning message -> Then switch the signing key to 'User delegation key'.
5. There is a waning message 'Expiry time must be after the current time.'.

## Expected Experience ##
It's better to keep the behaviors consistent.

## Actual Experience ##
The behaviors are inconsistent.
![image](https://github.com/user-attachments/assets/091d235f-c57c-4750-bf09-143168780ae0)

**Comment by craxal** [comment]
User-delegated SAS have different requirements than key-based SAS, so this is by design.

@JasonYeMSFT Can you confirm?

**Comment by JasonYeMSFT** [comment]
> User-delegated SAS have different requirements than key-based SAS, so this is by design.
> 
> [@JasonYeMSFT](https://github.com/JasonYeMSFT) Can you confirm?

This is true. Besides, it's pointless to create a SAS whose expiration time is about to be behind the current time.
