### ISSUE TITLE
Standardize "OS" to "system"

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#8138]
Some strings, particularly those for settings, use the term "OS", and some use "system". We should use the same term in all cases. "System" is preferred.

**Comment by MRayermannMSFT** [comment]
I have time to drop the usage of OS from strings related to the authentication broker. I don't have time to work on other strings (proxy settings, AzCopy proxy settings, OS theme settings, locale settings, etc.)
