### ISSUE TITLE
ERR_NOT_IMPLEMENTED in Azure Storage Explorer

### ISSUE THREAD

**Issue by shyamrangaraju9** [Microsoft/AzureStorageExplorer#814]
**Storage Explorer Version**: 
**Platform/OS Version**: 
**Architecture**: 
**Regression From**: 

#### Steps to Reproduce: ####
1. 
2. 

#### Actual Experience: ####

ERR_NOT_IMPLEMENTED

**Comment by jinglouMSFT** [comment]
I am going to close this issue as it's not actionable with the information provided.  Please feel free to reactivate but with the information we needed to further investigate. Thanks.
