### ISSUE TITLE
Move Refresh button to the left side of the menu

### ISSUE THREAD

**Issue by P47K0** [microsoft/AzureStorageExplorer#8146]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

The refresh button is now shown as last button and therefore the first button to be hidden when there isn't enough space

### Desired Solution

I would like to have this button shown as the first button

<img width="880" alt="image" src="https://github.com/user-attachments/assets/e68ccfab-dd8e-4ef3-a1e4-234c3572494c">

**Comment by craxal** [comment]
@P47K0 This has been the location of the Refresh button for a very long time. Explorers should have Ctrl+R keyboard shortcut for refreshing. Is this sufficient for your needs?

**Comment by P47K0** [comment]
CTRL + R is working. I'll use that, thanks
