### ISSUE TITLE
Deleting folder crashes

### ISSUE THREAD

**Issue by HunterCZE** [Microsoft/AzureStorageExplorer#815]
**Storage Explorer Version**: 1.4.4 (noticed on previous version)
**Platform/OS Version**: Windows 10
**Architecture**: x86
**Regression From**: no, worked on version 2 months ago

#### Steps to Reproduce: ####
1. in blob storage delete whole folder
2. folder must contain subitems (including subfolders)

#### Expected Experience: ####
deletes folder without crash

#### Actual Experience: ####
folder in BLOB is deleted, but StorageExplorer freezes and has to be killed via task manager.

**Comment by netsnake182** [comment]
![image](https://user-images.githubusercontent.com/1838469/47624018-829e1700-db52-11e8-9247-d00d4e18ac2e.png)

Yep. And always get stuck on 99%

**Comment by craxal** [comment]
Bug getting stale, and we've updated several times. Consider trying the Experimental/AzCopy features if you still can't delete folders. If that doesn't work, you may provide additional info to help us investigate.
