### ISSUE TITLE
No descriptions for 'Settings -> Sign In with' part on Mac/Linux platforms

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8158]
**Storage Explorer Version**: 1.36.0-dev (100)
**Build Number**: 20240830.6
**Branch**: main
**Platform/OS**: Linux Ubuntu 22.04/MacOS Sonoma 14.6.1(Apple M1 Pro)
**Architecture**: x64/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.35.0)

## Steps to Reproduce ##
1. Launch Storage Explorer -> Open 'Settings'.
2. Type 'Sign' into the search box -> Observe the 'Sign In with' part.
3. Check whether there are descriptions for this part.

## Expected Experience ##
There are descriptions for this part.
![image](https://github.com/user-attachments/assets/e3765637-dfd8-43ae-a33d-db2aab59d8ca)

## Actual Experience ##
No descriptions for this part.
![image](https://github.com/user-attachments/assets/5246f612-5ee2-4b6a-a971-5201033ce32c)

## Additional Context ##
This issue doesn't reproduce on Windows.

**Comment by v-kellyluo** [comment]
Verified this issue on the main build 20240902.1. Fixed.
![image](https://github.com/user-attachments/assets/740ef805-9e9e-48d5-8b6a-7085f5127221)
