### ISSUE TITLE
Not able to navigate to blobs in subdirectories below parent directory with empty name.

### ISSUE THREAD

**Issue by sgryt** [microsoft/AzureStorageExplorer#816]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows
**Architecture**: ia32
**Regression From**: Not entirely sure, but I'm confident that it worked in a previos version where I had no problems navigating our blob directory structure (I have used versions from both 1.2, 1.3 and 1.4 ranges previously where this was not a problem).

#### Steps to Reproduce: ####
1. In an existing blob container (I'll call it `events` here)
2. - with a top-level directory having an empty name (this can be created via the .NET API)
3. - and a subdirectory below the empty-named top-level directory (called `Users` here)
4. - and with blobs in the subdirectory
5. - try navigating to the subdirectory in the UI to see and manipulate the blob contents

#### Expected Experience: ####
I expect to be able to see and manipulate the blobs in the `Users` subdirectory

#### Actual Experience: ####
I cannot see the blobs in the `Users` subdirectory. When I double-click the empty top-level directory, I am presented with another empty-named directory (even if the navigation bar now shows `events >`). When I double-click this (unexpected) empty-named directory, the navigation bar changes to `events > >`, but shows me the `Users` subdirectory.
When I then double-click the `Users` subdirectory,  the UI says I have no blobs in the subdirectory, and the navigation bar says `events > > Users`.

**Comment by sgryt** [comment]
This is still a problem in version 1.9.0 - can you say anything about a timeframe on this ?

**Comment by sgryt** [comment]
Ping, this is still a problem in version 1.11.2.

**Comment by JasonYeMSFT** [comment]
We already have an open item for this #1512. We will address this once we figure out a solution for it.
