### ISSUE TITLE
It is better to add a property 'Name' for blob containers and file shares

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8163]
**Storage Explorer Version**: 1.36.0-dev (100)
**Build Number**: 20240902.1
**Branch**: main
**Platform/OS**: Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.6.1(Apple M1 Pro)
**Architecture**: arm64/x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Select the blob container.
3. Observe the properties on the Properties panel.
4. Check whether there is a property 'Name'.

## Expected Experience ##
It is better to add a property 'Name'.

Here is the screenshot for queues and tables.
![image](https://github.com/user-attachments/assets/7a9c8b1d-f47b-436c-863b-a00e10f3749d)

## Actual Experience ##
There is no property 'Name'.

Here is the screenshot for blob containers and file shares.
![image](https://github.com/user-attachments/assets/6746fe3f-3b7b-49df-8c07-043dac8431d9)

## Additional Context ##
For attached services, only table attachment has property 'Name'. It is better to keep consistent between four services.

**Comment by craxal** [comment]
Fix for attached file share property has been merged.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240924.3. The property name of attached file has been updated.
![image](https://github.com/user-attachments/assets/002fa5df-bb34-4a2b-9c71-e8f946d50911)
