### ISSUE TITLE
It is better to use 'storage account' instead of 'Storage account' in the description in the 'Move Message' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8166]
**Storage Explorer Version**: 1.36.0-dev (100)
**Build Number**: 20240904.1
**Branch**: main
**Platform/OS**: Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.6.1(Apple M1 Pro)
**Architecture**: arm64/x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Queues.
2. Create a queue -> Add one message.
3. Click 'Move -> Move All...' -> The 'Move Messages' dialog pops up.
4. Observe the description in the dialog.
5. Check whether it shows 'storage account' in the description.

## Expected Experience ##
It shows 'storage account' in the description.

## Actual Experience ##
It shows 'Storage account' in the description.
![image](https://github.com/user-attachments/assets/820b1d81-3014-49a0-9777-ab138e7c53a7)

**Comment by craxal** [comment]
@v-xianya I have merged a fix and confirmed that it works. However, it requires a queue extension package update to fully integrate, and I don't think a small string change such as this warrants a full build. I'll keep this in Verifying for now then close it when a package update happens.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240920.3. Fixed.
![image](https://github.com/user-attachments/assets/c77905b7-4a1a-464d-b807-ca8cac7b40ee)
