### ISSUE TITLE
The Azure account is expired when switching from 'Authentication Broker' to other three options

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8167]
**Storage Explorer Version**: 1.36.0-dev (100)
**Build Number**: 20240904.1
**Branch**: main
**Platform/OS**: Windows 10
**Architecture**: x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Open storage explorer.
2. Open settings -> Make sure it is using the 'Authentication Broker'.
3. Go to ACCOUNT MANAGEMENT panel -> Click 'Sign in with Azure...'.
4. Select one Azure account to sign in -> After successfully signing in.
5. Switch 'Sign In with' to 'Default Web Browser' -> Click 'Open Explorer'.
6. Switch to ACCOUNT MANAGEMENT panel.
7. Check whether the Azure account is not expired.

## Expected Experience ##
The Azure account is not expired.

## Actual Experience ##
The Azure account is expired.

## Additional Context ##   
1. This issue reproduces when switching from 'Authentication Broker' to other three options or from other three options to 'Authentication Broker'.

2. Here is the record:

![test](https://github.com/user-attachments/assets/5467001c-7287-4c37-8366-f87cf70b83dd)

**Comment by MRayermannMSFT** [comment]
This is by design. For....reasons...chanigng "sign in with" affects how we acquire Entra tokens, and we use Entra tokens when doing things like listing subscriptions. So when you change the setting, we fail to get the token.
