### ISSUE TITLE
Sign-in doesn't open browser

### ISSUE THREAD

**Issue by njb-ms** [microsoft/AzureStorageExplorer#8169]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.0

### Regression From

1.18.0

### Architecture

i86

### Platform

All

### Bug Description

When I try to sign-in the browser doesn't open

<img width="703" alt="sigin" src="https://github.com/user-attachments/assets/38047896-9615-4a95-a088-c63eef34240a">

### Steps to Reproduce

1. launch program
2. try to sign in

### Actual Experience

When I try to sign-in the browser doesn't open

**Comment by craxal** [comment]
@njb-ms You are using a very old version of Storage Explorer. Please update to the [latest version](https://github.com/microsoft/AzureStorageExplorer/releases/latest). Are you still encountering issues after updating?

**Comment by njb-ms** [comment]
I've auto-updated to the latest version and still face the issue.

**Comment by craxal** [comment]
Can you share your app logs?

**Comment by njb-ms** [comment]
I reinstalled the software and it now works. Not sure what the root cause is.
