### ISSUE TITLE
Adding blob hangs

### ISSUE THREAD

**Issue by njb-ms** [microsoft/AzureStorageExplorer#8170]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.0

### Regression From

1.18.0

### Architecture

i86

### Platform

All

### Bug Description

When adding a blob via a connection string, the opening seems to hang. See attached screenshot

<img width="1092" alt="loading" src="https://github.com/user-attachments/assets/73909e25-98e3-4ce8-99be-b37df54e9572">

### Steps to Reproduce

1. launch program
2. try to add a blob

### Actual Experience

When adding a blob via a connection string, the opening seems to hang. See attached screenshot

**Comment by craxal** [comment]
You are using a very old version of Storage Explorer. Please update to the [latest version](https://github.com/microsoft/AzureStorageExplorer/releases/latest). Are you still encountering issues after updating?

**Comment by njb-ms** [comment]
I've auto-upgraded and still see the issue.

**Comment by craxal** [comment]
@njb-ms Can you provide more detailed steps on what you are trying to accomplish and how? Where exactly are you seeing the hand?

**Comment by njb-ms** [comment]
I'm using the program on my company laptop and am trying to add a blob via the connection string. After inputting the connection string and clicking connect the program just keeps on saying "Adding new connection..." without ever finishing. It doesn't freeze, just never completes the operation.

**Comment by craxal** [comment]
@njb-ms I assume by "add a blob", you mean you are attempting to connect to a blob container.
- Just to be sure, can you verify the version up upgraded to?
- Can you describe your connection string? Which properties does it define?
- Can you share your app logs?

**Comment by njb-ms** [comment]
I reinstalled the software and it now works. Not sure what the root cause is.
