### ISSUE TITLE
Both accounts attached to storage explorer giving an AccountDisabled Error

### ISSUE THREAD

**Issue by dinotom** [microsoft/AzureStorageExplorer#8175]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.35

### Regression From

1.33

### Architecture

x64

### Storage Explorer Build Number

20240810.1

### Platform

Windows

### Bug Description

None on my blobs or tables show in either of my storage accounts. When I click on blob containers, on either one. I get this error message. " The specified account is disabled. RequestId:b6ba6e86-901e-009a-1752-00362e000000 Time:2024-09-06T11:47:13.1729205Z"

### Steps to Reproduce

1. Launch
2. Open Blob

### Actual Experience

I see what the problem is now, but don't know how to rectify it. I deleted my Visual Studio Professional subscription via azure, since I've been using my Enterprise monthly subscription for two years now and I was paying for professional for no reason. These two storage accounts were under the "Visual Studio Professional with MSDN' subscription. I tried moving the storage accounts to another billing subscription, but the portal is not letting me. Here is THAT error message "The subscription '124c83eb-5ad9-4417-a40c-c9eb1fc7841d' is disabled and therefore marked as read only. You cannot perform any write actions on this subscription until it is re-enabled. (Code: ReadOnlyDisabledSubscription) (Code: ReadOnlyDisabledSubscription)" Pleaase advise on how I can solve this. Two sites use these storage accounts, a lot, and are both are down now due to this

**Comment by craxal** [comment]
@dinotom I would suggest you open an [Azure support request](https://docs.microsoft.com/en-us/azure/azure-supportability/how-to-create-azure-support-request) since the trouble you're having is with Azure and not Storage Explorer.

**Comment by dinotom** [comment]
Craig,
Thank you for replying. I have tried that, but it gives me canned suggestions to restore blobs , tables et al, which is NOT the issue. Isn't there a support method to talk to an actual person?

[https://cdn.gifo.wisestamp.com/im/sh/aHR0cHM6Ly9zMy5hbWF6b25hd3MuY29tL3Vjd2ViYXBwLndpc2VzdGFtcC5jb20vNGQwODFkZGMtZjE5My00YzU5LTllMWYtNDgxNGNjMzdhZGU2L3ZpZXdsb2dvLmZvcm1hdF9wbmcucmVzaXplXzEyMHgucG5n/rounded.png]
Thomas Donino
Managing Partner
BATL Group
Tel: (914) 967-0436
Mobile: (914) 826-0061
Email: ***@***.***
Website: www.batl-group.com<http://www.batl-group.com/>
Florida tel: (914) 509-5124

[https://tracy.srv.wisestamp.com/px/wsid/g0y8YAP6.png]
________________________________

**Comment by craxal** [comment]
Once you get to the list os prescribed suggestions, you should see a button at the top of the blade to create a support request:

<img width="483" alt="image" src="https://github.com/user-attachments/assets/4f2f671e-155c-43ad-a773-ad325506b282">
