### ISSUE TITLE
This tenant is currently filtered out. Use the tenant configuration menu to un-filter the tenant and load subscriptions.

### ISSUE THREAD

**Issue by rajinira6** [microsoft/AzureStorageExplorer#8176]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.35.0

### Regression From

NA

### Architecture

i86

### Storage Explorer Build Number

20240810.1

### Platform

Windows

### OS Version

Windows 10

### Bug Description

When I connect to my asure account, I can see a tenant id which is different from the one which has my subscription (thought the login id for that subcription is the same and it is the service admin). I am unable to find any subscription and an error displayed "This tenant is currently filtered out. Use the tenant configuration menu to un-filter the tenant and load subscriptions."
<img width="887" alt="Untitled" src="https://github.com/user-attachments/assets/c0900e2c-fa2b-4ec2-ab0b-b98769fa3cb1">

### Steps to Reproduce

1. Launch explores
2. 2. Login to azure
3. No subscription listed though I have a subscription

### Actual Experience

When I connect to my azure account, I can see a tenant id which is different from the one which has my subscription (thought the login id for that subscription is the same and it is the service admin). I am unable to find any subscription and an error displayed "This tenant is currently filtered out. Use the tenant configuration menu to un-filter the tenant and load subscriptions."

<img width="887" alt="Untitled" src="https://github.com/user-attachments/assets/55a81a5f-edbf-45ac-b380-1ccb52090804">

### Expected Experience

I should me able to see my subscription under the azure environment I created and login into

**Comment by craxal** [comment]
@rajinira6 If you click on the little gear icon next to the tenant and select "Un-filter", does that resolve your issue?

**Comment by SeraphStray** [comment]
@craxal that worked for me! Not at all what I was thinking would work. 

I was looking at documentation (https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/blobs/alerts/storage-explorer-troubleshooting?tabs=Windows) and it's talking about keys and whatnot, so I went hunting for a key in the portal for this particular resource and couldn't find any, which lead me here.

**Comment by craxal** [comment]
Glad you got things working.

Tenants and subscriptions are collectively referred to as "sign-in" in Storage Explorer. Keys only enter the picture at the storage account level and are only necessary if that's what you use to authenticate. You actually need specific permissions to list keys, and its possible for key-based authentication to be disabled for a storage account.
