### ISSUE TITLE
The broken file share attachment doesn't disappear when clicking 'Detach' for it

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#8177]
**Storage Explorer Version:** 1.36.0-dev (100)
**Build Number:** 20240910.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.6.1(Apple M1 Pro)
**Architecture:** x64/x64/x64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##
1. Expand the storage account -> File Shares.
2. Select one file share ->  OAuth attach the file share.
3. Go to ACCOUNT MANAGEMENT -> Remove the azure account.
4. Go back to EXPLORER panel -> The file share attachment displays as broken.
5. Right click the broken file share attachment -> Click 'Detach' -> Click 'Yes'.
6. Check whether the broken file share attachment disappears.

## Expected Experience ##
The broken file share attachment disappears.

## Actual Experience ##
The broken file share attachment doesn't disappear.

**Comment by MRayermannMSFT** [comment]
Fix merged to main.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240912.2. Reproduce. So, we are going to re-open it.

**Comment by MRayermannMSFT** [comment]
Ok, fix actually merged (I hope, haha).

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240913.3. Fixed.

**Comment by v-kellyluo** [comment]
Hi @MRayermannMSFT , this issue reproduces on the build 20241101.5. So, we are going to re-open it.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20241127.4. Fixed.
