### ISSUE TITLE
It would be better to resize the upload dialog so that no scrollbar appears

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8178]
**Storage Explorer Version**: 1.36.0-dev (100)
**Build Number**: 20240911.2
**Branch**: main
**Platform/OS**: Windows11/Windows 10
**Architecture**: arm64/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Click 'Upload -> Upload Folder...'.
3. Add two tags with the same tag key -> An error message occurs.
4. Check whether there is no scrollbar on the dialog.

## Expected Experience ##
It would be better to resize the upload dialog so that no scrollbar appears.

## Actual Experience ##
There is a scrollbar on the dialog.
![image](https://github.com/user-attachments/assets/1593924e-ef02-4fba-a2d6-edf505621252)

**Comment by craxal** [comment]
Fix merged.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240920.3. Fixed.
![image](https://github.com/user-attachments/assets/553207c8-2ebd-4d3e-861d-ea1de993146a)
