### ISSUE TITLE
The opened tab is not closed after deleting the corresponding blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8179]
**Storage Explorer Version**: 1.36.0-dev (100)
**Build Number**: 20240911.2
**Branch**: main
**Platform/OS**: Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.6.1(Apple M1 Pro)
**Architecture**: arm64/x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.35.0)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Then delete it.
3. Check whether the opened tab is closed.

## Expected Experience ##
The opened tab is closed.

## Actual Experience ##
The opened tab is not closed.

**Comment by craxal** [comment]
Well, silly me. By making `closeTab()` async and awaiting the result, that put us right back into the dead lock I was originally trying to solve.

Here's what I think we can do:
* Make the top level close functions synchronous again. They will return as soon as the message to close has been sent to the panel or panels that need to close.
* Handle tab closures as a group. Wait for all panels that are closing to finalize, and then make the necessary changes to the observable arrays.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240914.2. Fixed.
