### ISSUE TITLE
Fail to open the attached blob containers with an error

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#818]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181023.6
**Commit**: 1b1810d7
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Add the 'Storage Account Contributor' role under Subscription or Storage Account level.
2. Sign in with the added account in Storage Explorer.
3. Choose one blob container -> Attach the selected blob container with SAS.
**Display name**: newtest
**SAS URI:** https://1015test.blob.core.windows.net/newtest?st=2018-10-30T01%3A23%3A50Z&se=2018-12-01T01%3A23%3A00Z&sp=rwdl&sv=2018-03-28&sr=c&sig=IcNdD1lMQFn5ro%2BT5Sy1ASaJhAgZfqRdl6xrAWdG3BI%3D
4. Try to expand '**Local & Attached**' -> '**Storage Accounts**' -> '**Blob Containers'** -> The attached blob container.

#### Expected Experience: ####
Succeed to open the attached blob container.
#### Actual Experience: ####
Fail to open the attached blob container with the below error.
![error_attached_blobcontainer](https://user-images.githubusercontent.com/34729022/47689784-5f449c00-dc26-11e8-9410-8319446f0a49.png)

**Comment by craxal** [comment]
I'm having trouble reproducing. I can't seem to get an account that I have the "Storage Account Contributor" role for to list. It's not a Storage Explorer issue, either, because it doesn't appear in the portal.

Have you verified whether the keys are successfully retrieved? Check the Properties tab to be sure.

**Comment by v-xuanzh** [comment]
This issue doesn't reproduce on the latest master build 20190723.4. So closed it.
