### ISSUE TITLE
Partition keys not sorted in alphabetic order

### ISSUE THREAD

**Issue by sixeyes** [microsoft/AzureStorageExplorer#8180]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.35.0

### Architecture

i86

### Storage Explorer Build Number

20240810.1

### Platform

All

### OS Version

Windows 10

### Bug Description

When sorting partition keys, they are not appearing in the expected sort order (i.e. alphabetic)

### Steps to Reproduce

1. Load records from attached file into new storage table.
2. View table in Azure Storage Explorer.
3. Sort by partition key increasing.
[Sort Issue.csv](https://github.com/user-attachments/files/16963931/Sort.Issue.csv)

### Actual Experience

![image](https://github.com/user-attachments/assets/ed0ec639-2229-4037-8756-e997287da953)

### Expected Experience

I would expect partition key 251540a0dd7541ccadac81d50807a7b0 to appear BEFORE partition key 43ea54abb79849539b3e6880982b1dce.

**Comment by craxal** [comment]
@sixeyes Odd... Out of curiosity, is this the result of default sorting (when the table is first opened)? Does manually sorting the column resolve the issue?

Can you provide sample data? Our existing tests still seem to sort correctly.

**Comment by craxal** [comment]
@sixeyes As a workaround, you can simply turn off the Natural Sort Order setting.

Natural sort order is implemented like this:

```js
"43ea54abb79849539b3e6880982b1dce".localeCompare("251540a0dd7541ccadac81d50807a7b0", undefined, { numeric: true })
// Returns -1
```

Default sort order is implemented like this:

```js
"43ea54abb79849539b3e6880982b1dce".localeCompare("251540a0dd7541ccadac81d50807a7b0", undefined, { numeric: false })
// Returns 1
```

The unexpected result from numeric comparisons comes from the comparison function trying to parse out the largest continuation of digits and treat them as one number. This is easy to see if you insert rows with the keys `9aaa`, `88aa`, `777a`, and `6666`. Clearly, `9aaa` should be last, but with natural sort order turned on, it actually comes first.

Natural sort order was added primarily for blob users who wanted blobs to be sorted not purely by ASCII or Unicode characters:

Unexpected char-based order | Expected numeric order
----------------------------|-----------------------
`blob19`                    | `blob2`
`blob2`                     | `blob19`
`blob321`                   | `blob321`

A universal setting for natural sort order is not suitable for all columns. We can consider a more granular approach.

**Comment by sixeyes** [comment]
> @sixeyes Odd... Out of curiosity, is this the result of default sorting (when the table is first opened)? Does manually sorting the column resolve the issue?

This is the order, regardless of when it's done. Reverse sorting Partition Key has the same sort order (but in reverse)
