### ISSUE TITLE
Open Storage Containers In Tabs instead of Splitting the window

### ISSUE THREAD

**Issue by cquick-srs** [microsoft/AzureStorageExplorer#8181]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

When browsing all storage containers and then clicking on a storage container, the window is suddenly split. 

### Desired Solution

It would be nice to have an option on the way to open a storage container. For the majority of my workflows, I only need to open the storage container within a new tab. The split view is causing extra steps and makes it frustrating to use storage explorer. 

### Alternatives and Workarounds

Even if this were an advanced option by right clicking on the container and choosing open as new tab in this pane.

**Comment by craxal** [comment]
VS Code has an "Open to the Side" option. We could consider gradually adding that in all other places we have Open commands.

**Comment by cquick-srs** [comment]
That would be fine. It's just the default behavior of opening to the side at all times quickly fills up the interface with split panes, which can be challenging if working in multiple storage containers. The tabs are easier to navigate in that scenario.

**Comment by richardMSFT** [comment]
The default open behavior has been changed to open in a new tab, and "open to the side" option has been added to the context menu. This will ship with the 1.37.0 release.
