### ISSUE TITLE
Right-click, SHA256 option

### ISSUE THREAD

**Issue by sopsmattw** [microsoft/AzureStorageExplorer#8184]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

For really large files, it would be nice to have an option to check file integrity without downloading it. 

### Desired Solution

right-click, Get SHA256 or something like that. 

### Additional Context

Occasionally, I need to verify a file was uploaded without corruption. Some of these files can be multiple Terabytes. Downloading locally to get the SHA256 is less efficient just to get the hash.

**Comment by craxal** [comment]
@sopsmattw By default, when uploading AzCopy checks file integrity via MD5 hashes for you. If you want to check a blob's MD5 hash in Storage Explorer, you can view its Properties. No download should be necessary.

**Comment by MRayermannMSFT** [comment]
To get a SHA256 hash, we'd have to re-download the file. By default, the Azure storage does not compute any sort of integrity hash for blobs. However, most tools (Storage Explorer & AzCopy included)  will compute an MD5 hash upon uplooad and add it to the blob's properties. If you'd like a right-click option for that, please open a new issue.
