### ISSUE TITLE
Pin File Share Subdirectories

### ISSUE THREAD

**Issue by bgoosen** [microsoft/AzureStorageExplorer#8186]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

The new Pin Blob Subdirectories is nice. It would be cool if we could pin File Share Subdirectories too.

### Desired Solution

Add option to pin File Share Subdirectories

**Comment by richardMSFT** [comment]
Merged and will be included in 1.37.0 release.
