### ISSUE TITLE
An error information bar occurs after launching storage explorer on Windows

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8187]
**Storage Explorer Version**: 1.36.0-dev (100)
**Build Number**: 20240914.2
**Branch**: main
**Platform/OS**: Windows11/Windows 10
**Architecture**: x64/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.35.0)

## Steps to Reproduce ##
1. Launch Storage Explorer.
2. Check no error information bar occurs.

## Expected Experience ##
No error information bar occurs.

## Actual Experience ##
An error information bar occurs.

Error message:
`Unable to establish connection using current proxy settings. Please verify current settings by accessing the proxy dialog in the toolbar.`
![image](https://github.com/user-attachments/assets/c7fd2ec1-a991-425b-9645-e668f217be71)

## Additional Context ##
1. If you can't reproduce this issue, try to reload storage explorer.
2. We did not set any proxy setting.
![image](https://github.com/user-attachments/assets/a98ff3b4-5567-4674-b0c3-0613d3eada50)
3. Here is the log:
[2024-09-14_015200.zip](https://github.com/user-attachments/files/17001390/2024-09-14_015200.zip)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240918.1. Fixed.
