### ISSUE TITLE
Unable to authenticate because the browser doesn't open

### ISSUE THREAD

**Issue by Blackbaud-ColleenGutierrez** [microsoft/AzureStorageExplorer#8188]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

Latest - downloaded 9/13/2024

### Regression From

Not sure, but I thought it was the latest

### Architecture

i86

### Platform

Windows

### Bug Description

The browser never opens for me to authenticate. I have uninstalled and reinstalled twice. I have tried switching the sign on to use the in-app authentication (instead of browser), but it doesn't do anything when I try to sign in. 
How do I get the browser to open so that I can authenticate and log in?

### Steps to Reproduce

1. Open ASE tool.
2. Select Sign in
3. Select Azure.
4. Wait for browser to open for authentication, but it never does.

### Actual Experience

1. Open ASE tool.
2. Select Sign in
3. Select Azure.
4. Wait for browser to open for authentication, but it never does. 
![image](https://github.com/user-attachments/assets/69f22d49-2176-4064-bb0d-0e3552f18c5c)

### Expected Experience

I am usually already logged in to ASE when I open it, because I set it up months ago. Even though I try to re-set it up, it never allows me to get past the first screen.

### Additional Context

I am trying to access our Azure repo so I can publish new help documentation. This is blocking me from my work.

**Comment by joarsolvang** [comment]
Hi, 

I had the same problem but was able to get around it by changing where the sign in happens:

https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-sign-in#changing-where-sign-in-happens

**Comment by Blackbaud-ColleenGutierrez** [comment]
Thanks. Sadly, changing the sign in away from a browser did not work for me. I'm glad that it worked for you, though!

**Comment by Inzagio** [comment]
I also have a similar issue, tried all the different sign-in other places options to no avail.

**Comment by N3rdage** [comment]
Had the same issue after updating to 1.35.0. 
Downgrading back to 1.31.2 solved my issue, so seems to be something in the new version.

**Comment by Blackbaud-ColleenGutierrez** [comment]
Wow, thank you, @N3rdage!  That solved it for me! Yay!  (I even tried setting different browsers as default, but none worked)

In case anyone comes here due to this issue and wants to try the resolution of going back a version, you can download 1.31.2 here: https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.32.1

**Comment by craxal** [comment]
Do you have .NET 8 installed?

**Comment by Blackbaud-ColleenGutierrez** [comment]
No, @craxal, I do not have .NET 8.

**Comment by N3rdage** [comment]
D'oh @craxal, just updated and it worked, thanks. 😊 
Had been doing !C# development for a while and hadn't been keeping up with my .NET runtimes.

**Comment by craxal** [comment]
@Blackbaud-ColleenGutierrez .NET 8 became a requirement as of 1.34.0 (we mentioned it in our [release notes](https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.34.0)). Funny, you should have gotten a prompt to install it when installing the Storage Explorer update. Try updating to see of that fixes your issue.

@N3rdage Very glad updating .NET unblocked you.

**Comment by Blackbaud-ColleenGutierrez** [comment]
Woooo, I'm back in after updating to .NET 8. Thank you, @craxal !  

(I did not, in fact, get prompted to update .NET)

**Comment by Blackbaud-ColleenGutierrez** [comment]
Resolved with the update to .NET 8.
