### ISSUE TITLE
Azure Storage Explorer (ARM64), dropdown menus say empty, won't sign in.

### ISSUE THREAD

**Issue by tballowe** [microsoft/AzureStorageExplorer#8189]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.35.0

### Architecture

arm64

### Platform

Windows

### OS Version

Windows 11

### Bug Description

I cannot sign in, dropdown menus say "Empty."

### Steps to Reproduce

1. Launch the explorer
2. Try to sign in
3. Try to view a dropdown menu

### Actual Experience

Hi,

I have the Azure Storage Explorer installed on my ARM64 Surface Laptop 7, and it was working fine. About a week ago, it stopped working. It won't let me sign in, and the dropdown menus all say "Empty."I have:

1. uninstalled and reinstalled.
3. uninstalled and deleted all temporary and AppData files, then reinstalled.
5. uninstalled and tried the Intel version.
7. tried a newly installed browser and set it as default.
9. tried the integrated sign on

Nothing makes any difference. I keep having the same issues. The dropdown menus say "Empty," and it will not sign in.
.
![image](https://github.com/user-attachments/assets/1d500b37-4571-46ff-86ab-0973baaca9a1)

**Comment by tballowe** [comment]
Turns out my .NET SDK was not working correctly. I reinstalled that and now all is well.

**Comment by nielsvdc** [comment]
Confirmed. Installing .NET 8.0 fixed the issue for us.
