### ISSUE TITLE
Pop up an error after expanding Blob Containers node for one attached account with Key and Name

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#819]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181023.6
**Commit**: 1b1810d7
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Add the '**Storage Account Contributor'** or '**Classic Storage Account Contributor**' role under **Subscription** level.
2. Sign in with the account in Storage Explorer.
3. Right click one account -> Select 'Copy Primary Key' -> Attach the selected account with Key and name.
**Display name**: zag230
**Key**: [REDACTED]
4. Try to expand **'Local & Attached'** ->'**Storage Accounts'** -> **The attached account** node -> '**Blob Containers**'.
#### Expected Experience: ####
The Blob Containers node can be expanded successfully.

#### Actual Experience: ####
Pop up an error when expanding the Blob Containers node.
The containers list well after closing the error dialog directly.
![error_keyandname](https://user-images.githubusercontent.com/34729022/47690901-eb58c280-dc2a-11e8-96a7-07dc2ed2457d.png)

**Comment by MRayermannMSFT** [comment]
@v-xuanzh , does this still reproduce for you? I'm not seeing it happen anymore? If it is, can you confirm that the key which is copied onto the clipboard is correct? I'd suggest checking against the value of the key in the portal.

**Comment by MRayermannMSFT** [comment]
Closing.
