### ISSUE TITLE
The space between the option and the buttons appears insufficient in delete confirmation dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8195]
**Storage Explorer Version**: 1.36.0-dev (100)
**Build Number**: 20240918.2
**Branch**: main
**Platform/OS**: Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.6.1(Apple M1 Pro)
**Architecture**: arm64/x64/x64/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers. (Make sure the soft delete is disabled)
2. Open one blob container -> Upload one blob.
3. Select the blob -> Click 'Delete' -> Observe the prompt dialog.
4. Check whether the space between option and buttons is sufficient.

## Expected Experience ##
It is better to add a space line between the option and buttons.

## Actual Experience ##
The space between the option and the buttons appears insufficient.
![image](https://github.com/user-attachments/assets/1d1b1b10-1d7d-49bb-8c76-3b662c151621)

**Comment by craxal** [comment]
This is by design. It's meant to be grouped with the dialog buttons, similar to system dialogs that have check box options on the same line as the buttons.
