### ISSUE TITLE
The string 'Quick Access/Subscription Name' does not include a '.../' prefix for tabs that display relevant parts of the node path

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8198]
**Storage Explorer Version**: 1.36.0-dev (100)
**Build Number**: 20240923.1
**Branch**: main
**Platform/OS**: Windows11/Windows 10/Linux Ubuntu 22.04
**Architecture**: arm64/x64/x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Add the blob container to Quick Access.
3. Open the QA blob container -> Observe the QA blob container tab.
4. Check whether the 'Quick Access' string include a '.../' prefix.

## Expected Experience ##
The 'Quick Access' string include a '.../' prefix.

## Actual Experience ##
The 'Quick Access' string does not include a '.../' prefix.
![image](https://github.com/user-attachments/assets/87386428-973d-49f2-bda4-9bc63bef6482)

## Additional Context ##
This issue also reproduces for below situation.
![image](https://github.com/user-attachments/assets/e3fd1ffa-918b-4eb8-993b-8a11306b2096)

**Comment by craxal** [comment]
This is by design. Subscription nodes and "Quick Access" are at the root of the path, so it doesn't make sense for the tags to have a ".../" prefix.

**Comment by craxal** [comment]
Is it OK? Sure. But that would require updating several packages, and I don't think the change is worth the effort.
