### ISSUE TITLE
Blob containers can’t be retrieved 

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#820]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20181023.6
**Commit**: 1b1810d7
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Add permission with the role ‘**Classic Storage Account Contributor**’ under Subscription level -> Select a member and save.
2. Use the selected member’s account to sign in.
3. Expand one storage account -> Check whether blob containers can be retrieved or not.

#### Expected Experience: ####
Blob containers can be retrieved.

#### Actual Experience: ####
Blob containers can’t be retrieved with the error.
![image](https://user-images.githubusercontent.com/41351993/47691278-6d95b680-dc2c-11e8-80e5-d890239fa421.png)

**Comment by craxal** [comment]
We've been running into these issue before, not just RBAC related. @MRayermannMSFT, do you know anything?

**Comment by craxal** [comment]
Also, @v-xianya, you're using the "Classic Storage Account Contributor". Is the account you expanded a classic account or general purpose V2 account?

**Comment by craxal** [comment]
Think I found the bug. Due to some important error information getting gobbled up which we need to determine whether it's just an RBAC authentication error for our fallback mechanism.

**Comment by v-xianya** [comment]
Verified on build 20181109.1. This issue reproduces for  all Classic Accounts and it  has nothing to do with RBAC feature.

**Comment by v-xianya** [comment]
Verified on build 20181113.1. This issue doesn't reproduce. Can you help to resolve it?
