### ISSUE TITLE
No update notification appears when running './StorageExplorer --add-update-group=CTI' to open Storage Explorer on Linux

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8202]
**Storage Explorer Version**: 1.36.0 (101)
**Build Number**: 20240925.3
**Branch**: rel/1.36.0
**Platform/OS**: Linux Ubuntu 22.04
**Architecture**: x64
**How Found**: From running test cases
**Regression From**: Previous release (1.35.0)

## Steps to Reproduce ##
1. Download StorageExplorer-linux.tar.gz on Linux -> Extract it.
2. Open terminal, navigate to the folder's location, run "./StorageExplorer --add-update-group=CTI".
3. Storage Explorer opens.
6. Check whether the update notification appears.

## Expected Experience ##
The update notification appears.
![image](https://github.com/user-attachments/assets/ee96071c-d5ca-4460-88c4-de1bd9894c12)

## Actual Experience ##
No update notification appears.

## Additional Context ##
1. This issue doesn't reproduce for Windows.
2. No mac arm64 signed build. so we haven't test this case on MacOS.

**Comment by craxal** [comment]
@v-xianya Thank you for finding this! I updated the forward link. Please try again.

**Comment by v-xianya** [comment]
Hi @craxal Verified this issue on the rel build 20240926.1. Fixed on Linux.
We also tested it on Mac and Windows platforms.
This issue **reproduces** on MacOS arm64 and Windows Arm64.

**Comment by craxal** [comment]
@v-xianya So, the download URL in the versions file was pointing directly to our publish container, for which I've disabled anonymous blob access, so I can easily see why Windows ARM isn't working. I just need to update the versions file.

macOS ARM, though...that's a bit concerning. I've updated the version file, so can you verify whether this continues to reproduce for macOS ARM?

**Comment by v-xianya** [comment]
Hi @craxal Verified this issue on the rel build 20240926.1. Fixed on MacOS ARM.
Still no notification prompts on Windows arm64.

**Comment by craxal** [comment]
@v-xianya Oh, I think that's because I had caching enabled on the CDN. I updated the version2.json file, but no matter how many times I was refreshing in the browser, it wasn't updating. After disabling caching, I started getting the updated versino2.json. Try it one more time.

**Comment by v-xianya** [comment]
Hi @craxal 
Verified on the new build 20240929.1, there is no update notification when opening Storage Explorer with the command --add-update-group=CTI on Windows x64&arm64, MacOS ARM, and Linux.

However, below update notification prompts appear on **MacOS ARM and Linux** when launching Storage Explorer normally (Without the command --add-update-group=CTI ). Could you help to take a look?
![image](https://github.com/user-attachments/assets/74ac3329-f662-47cf-9686-079172b6b98f)

**Comment by craxal** [comment]
I was not able to reproduce when running macOS ARM with the command `--add-update-group=CTI`:

<img width="1069" alt="image" src="https://github.com/user-attachments/assets/e6140d72-de62-495a-9aeb-f9e862e0d5dd">

I've made a few observations:

* The "CTI" update group persists in subsequent sessions. I continue to get update messages even if the `--add-update-group=CTI` option is not provided every time after.
* The message appears when manually checking for updates (I don't have to wait 60 minutes for the message to appear automatically).
* The "Install on Close" button should only appear on Windows.

In light of these observations, I have a few follow-up questions: 
* How long did you wait for an update message to automatically appear?
* Did you try manually checking for updates? Does doing so make the update message appear?
* In all situations (whether you use the `--add-update-group=CTI` option, whether you see the update message or not), check whether the CTI group is applied:
  1. Open dev tools (F12)
  2. Under the Application tab, select Local storage > file://.
  3. Select the `Standalone_RolloutPercentile_v1`. Is there a `CTI: {name: "CTI", percentage: 100}` value?

**Comment by craxal** [comment]
@MRayermannMSFT found that the issue was related to a change in platform behavior such that certain platform detection functions were returning incorrect responses. Logic was restructured slightly to account for this, so Windows ARM should now be getting updates.

**Comment by v-xianya** [comment]
@craxal Verified this issue on the rel build 20241011.2. 
On Windows ARM64, run command: **.\StorageExplorer.exe --add-update-group=CTI** below update prompts.
![Image](https://github.com/user-attachments/assets/03f0488c-2ed6-4d40-a95e-ebf6631b2677)
On Windows x64, below update prompts after installing and opening storage explorer.
![Image](https://github.com/user-attachments/assets/088b934c-fa1a-4dc6-bf97-5ffdeaaa7ae6)
On MacOS ARM, below update prompts regardless of the option '--add-update-group=CTI' is provided.
![Image](https://github.com/user-attachments/assets/1e4a06e9-c9ff-4398-8c9f-c23082b4ece9)
On Linux, below update prompts when running **./StorageExplorer --add-update-group=CTI** to open storage explorer.
![Image](https://github.com/user-attachments/assets/1e4a06e9-c9ff-4398-8c9f-c23082b4ece9)

**Comment by craxal** [comment]
@v-xianya What you are now observing appears to be expected behavior, but we're not 100% sure about your latest findings, whether they're expected behaviors and what steps were followed.

We all followed the test case instructions and were able to verify update notifications appeared as expected for all platforms. As mentioned before, the `--add-update-group` option persists between sessions, whether it's included or not. You need to use `--remove-update-group`, otherwise you will continue to get update notifications.

In the future, can you be sure to be explicit about new or alternate steps taken and expected/observed results? We need to make sure we minimize ambiguities in ongoing discussions such as this.

**Comment by v-xianya** [comment]
`In the future, can you be sure to be explicit about new or alternate steps taken and expected/observed results? `
Ok, got it, we will do.
