### ISSUE TITLE
Adding blob containers to Quick Access display as broken

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#821]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181023.6
**Commit**: 1b1810d7
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Add '**Reader**' role under **Storage Account** level
2. Sign in with the selected account in Storage Explorer.
3. Choose one storage account -> Try to add one blob container to Quick Access.
4. Check whether the added service displays well under Quick Access or not.
#### Expected Experience: ####
The added blob container displays well under Quick Access.
#### Actual Experience: ####
The added blob container displays as broken under Quick Access.

**Comment by craxal** [comment]
Unable to reproduce, but it may have been the same root cause as #819.
