### ISSUE TITLE
The file share attachment doesn't disappear after detaching it

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8211]
**Storage Explorer Version**: 1.36.0-dev (101)
**Build Number**: 20240926.1
**Branch**: main
**Platform/OS**: Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.6.1(Apple M1 Pro)
**Architecture**: arm64/x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.35.0)

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Attach the file share.
3. Go to the file share attachment -> Right click the file share attachment.
4. Click 'Detach' -> Click 'Yes' on the confirmation dialog.
5. Check whether the file share attachment disappears.

## Expected Experience ##
The file share attachment disappears.

## Actual Experience ##
The file share attachment doesn't disappear.

## Additional Context ##
The file share attachment doesn't disappear after manually refreshing.

**Comment by craxal** [comment]
The wrong arguments were getting passed around; the wrong value for the connection ID was being used.

**Comment by v-xianya** [comment]
Verified this issue on the build 20240929.1. Fixed. So, we are going to close it.
