### ISSUE TITLE
The relevant part of the node path is displayed next to the tab's name when only one tab is open for a blob container or table

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8213]
**Storage Explorer Version**: 1.36.0-dev (101)
**Build Number**: 20240926.1
**Branch**: main
**Platform/OS**: Windows11
**Architecture**: arm64
**How Found**: From running test cases
**Regression From**: Not a regression
## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Open one blob container.
3. Check whether no relevant part of the node path is displayed next to the tab's name.

## Expected Experience ##
No relevant part of the node path is displayed next to the tab's name.
![image](https://github.com/user-attachments/assets/f1edbbae-2687-4d54-b000-1da9cd30e2e9)

## Actual Experience ##
The relevant part of the node path is displayed next to the tab's name.
![image](https://github.com/user-attachments/assets/7465ac55-7806-4526-8d00-75b90e40d93f)

## Additional Context ##
1. For now, we only occurred this issue against blob containers and tables on Windows ARM64 and it is unstable.
2. This issue can't be reproduced consistently.
3. Here is the record:
![Animation](https://github.com/user-attachments/assets/83c269e6-1a99-4fb0-9f73-fd3c1e58a1a3)
4. Here is the log:
[2024-09-27_055658 (2).zip](https://github.com/user-attachments/files/17160202/2024-09-27_055658.2.zip)
[2024-09-27_055658.zip](https://github.com/user-attachments/files/17160205/2024-09-27_055658.zip)

**Comment by craxal** [comment]
@v-xianya Can you verify whether this _only_ reproduces on Windows ARM64? Or does this also reproduce in Windows x64 or other platforms?

**Comment by craxal** [comment]
Unfortunately, the logs you attached don't contain much useful information. I'm going to add some extra verbose logging to help us narrow down the problem. If you can repro, please share any relevant verbose output from the renderer process (or just share the renderer process logs).

**Comment by v-xianya** [comment]
Got it, will share the logs once we reproduce this issue.

**Comment by v-xianya** [comment]
We reproduced this issue on Linux(.tar) using build 20241008.1. Unfortunately, we didn't set the log to verbose when this issue occurred😓
![image](https://github.com/user-attachments/assets/122b8bfd-a6c4-4458-b9c7-16d738c0c504)

**Comment by v-xianya** [comment]
Hi @craxal @richardMSFT  Today we met this issue on 3 platforms MacOS ARM, Windows ARM, Linux.

These are the most likely steps to reproduce this issue. I hope this helps.
Steps:
1. Ensure there are two blob containers with the same name but from different storage accounts.
2. Expand one storage account and temporarily open the blob container.
3. Expand the other storage account and temporarily open the blob container with the same name.

Here is the render log on Windows ARM.
[2024-10-09_074651_renderer_6888.log](https://github.com/user-attachments/files/17304430/2024-10-09_074651_renderer_6888.log)

Below is the record:
![Image](https://github.com/user-attachments/assets/9b7e7f12-ba54-4a41-95bd-831f87bf8bfd)

**Comment by v-xianya** [comment]
@richardMSFT Verified this issue on the rel build 20241011.2. It doesn't reproduce. However, I noticed that the relevant part of the node path briefly flashes after opening a secondary temporary tab. I'm not sure if this requires further attention. Here is the record.
![Image](https://github.com/user-attachments/assets/f42662c9-e4ab-467b-b5d3-c94d0da9b5bf)

**Comment by craxal** [comment]
The flash comes from the time between adding the new temporary tab to the collection of tabs (which causes path differentiations to be recalculated) and removing the old temporary tab. We can address this in 1.37.0.

**Comment by craxal** [comment]
Initial problem is resolved, but we won't worry about the "flash".
