### ISSUE TITLE
Only one file is uploaded successfully when selecting and uploading multiple files from different locations

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8215]
**Storage Explorer Version**: 1.36.0-dev (101)
**Build Number**: 20240929.1
**Branch**: rel/1.36.0
**Platform/OS**: Windows11/Linux Ubuntu 22.04/MacOS Sequoia 15.0(Apple M1 Pro)
**Architecture**: arm64/x64/arm64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Click 'Upload -> Upload Files...'.
3. Select two files that come from different locations.
4. Check whether succeeds to upload the two files.

## Expected Experience ##
Succeed to upload the two files.

## Actual Experience ##
1. Succeed to select the two files.
2. Only one file is uploaded successfully.
![image](https://github.com/user-attachments/assets/0396d92e-284a-40ad-b50c-0c1e940a7819)

## Additional Context ##
Here is the record:

![Animation](https://github.com/user-attachments/assets/a369f936-eb97-4eb2-97e3-17363556a8d5)

**Comment by MRayermannMSFT** [comment]
The upload files dialog will now display an error message if you try to upload files from different directories at the same time.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20241206.2. Fixed. 
The upload files dialog displays an error message when trying to upload files from different directories at the same time
![Image](https://github.com/user-attachments/assets/ffc5400d-cc09-4b42-888d-a5149a145697)
