### ISSUE TITLE
Unable to add account in Azure Storage Explorer

### ISSUE THREAD

**Issue by RupaNag19** [microsoft/AzureStorageExplorer#8216]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.25.1

### Architecture

i86

### Storage Explorer Build Number

20220809.7

### Platform

All

### OS Version

Windows 10

### Bug Description

I am trying to add my account via Azure Storage Explorer --> Account Management-->Subscription. My account is getting authenticated (message received on browser :Authenticated. You can return to Storage Explorer. You might need to authenticate again if you close this browser tab.). But when i am back to Azure Storage Explorer--> Account Management, I am getting error:

{
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"getaddrinfo ENOTFOUND management.azure.com\\\",\\n  \\\"stack\\\": \\\"Error: getaddrinfo ENOTFOUND management.azure.com\\\\n    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)\\\\n    at __node_internal_ (node:internal/errors:686:10)\\\\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)\\\",\\n  \\\"errno\\\": -3008,\\n  \\\"code\\\": \\\"ENOTFOUND\\\",\\n  \\\"syscall\\\": \\\"getaddrinfo\\\",\\n  \\\"hostname\\\": \\\"management.azure.com\\\"\\n}\""
}

Note: Architecture(from about) is ia32 but there is no such option in the above list. Hence mentioning here.
![about](https://github.com/user-attachments/assets/4a8268a7-2ae4-4b64-b514-fa71a4ebbe9e)
![error](https://github.com/user-attachments/assets/78a9edfe-ab13-4457-863a-47a233237a66)
 

### Steps to Reproduce

Launch Azure Storage Explorer --> Go to Account Management--> Go to Subscription-->Authenticate account(message received on browser :Authenticated. You can return to Storage Explorer. You might need to authenticate again if you close this browser tab.).
-->Back to Azure Storage Explorer --> Go to Account Management--> Error

### Actual Experience

I am trying to add my account via Azure Storage Explorer --> Account Management-->Subscription. My account is getting authenticated (message received on browser :Authenticated. You can return to Storage Explorer. You might need to authenticate again if you close this browser tab.). But when i am back to Azure Storage Explorer--> Account Management, I am getting error:

{
  "message": "\"{\\n  \\\"name\\\": \\\"Error\\\",\\n  \\\"message\\\": \\\"getaddrinfo ENOTFOUND management.azure.com\\\",\\n  \\\"stack\\\": \\\"Error: getaddrinfo ENOTFOUND management.azure.com\\\\n    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)\\\\n    at __node_internal_ (node:internal/errors:686:10)\\\\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)\\\",\\n  \\\"errno\\\": -3008,\\n  \\\"code\\\": \\\"ENOTFOUND\\\",\\n  \\\"syscall\\\": \\\"getaddrinfo\\\",\\n  \\\"hostname\\\": \\\"management.azure.com\\\"\\n}\""
}

### Expected Experience

After adding and authenticating my account, I should have been able to see my subscriptions .

**Comment by craxal** [comment]
@RupaNag19 You are on a very old version of Storage Explorer. Please update to the [latest](https://github.com/microsoft/AzureStorageExplorer/releases/latest) and try again. Please note also that we no longer release 32-bit versions of Storage Explorer (see [1.29.0 release notes](https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.29.0)).

**Comment by RupaNag19** [comment]
> @RupaNag19 You are on a very old version of Storage Explorer. Please update to the [latest](https://github.com/microsoft/AzureStorageExplorer/releases/latest) and try again. Please note also that we no longer release 32-bit versions of Storage Explorer (see [1.29.0 release notes](https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.29.0)). If you are running 64-bit Windows, I recommend you uninstall Storage Explorer and download and uninstall the latest 64-bit version for Windows.

Thank you for the suggestion. I have raised it with our service desk team who are responsible to install the latest version.

**Comment by RupaNag19** [comment]
I could not update to latest version due to some infrastructure limitation. My team helped me with a work around. So this issue is no more causing any problem to me.
