### ISSUE TITLE
Large data transfer freezes/times out

### ISSUE THREAD

**Issue by brettsheehan** [microsoft/AzureStorageExplorer#8222]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.35

### Regression From

1.32.1

### Architecture

i86

### Platform

Windows

### OS Version

11

### Bug Description

When uploading large data (650GB) we notice a freeze on upload after a certain time. We suspect it's a timeout as when we limit the bandwidth the percentage complete before it freezes reduces. I think it's around the 4-5hr mark but can be sure when it freezes. 

### Steps to Reproduce

1. Launch Explorer
2. Upload large folder with many files (500GB)
3. Blue spinning wheel appears, and upload speed disappears (after about 4-5hrs?)

### Actual Experience

See Steps to reproduce

### Expected Experience

Upload doesn't freeze and completes

### Additional Context

Doesnt look like we are along https://www.reddit.com/r/AZURE/comments/1cbz7ow/wondering_if_someone_could_assist_me_with_azure/?rdt=43401

**Comment by craxal** [comment]
Is your issue similar to #8200? Can you copy the AzCopy command from the activity and attempt to run the command directly? Does the output of that command say anything about an expired token?
