### ISSUE TITLE
Error trying to view a fileshare

### ISSUE THREAD

**Issue by CMCD-git** [microsoft/AzureStorageExplorer#8223]
I have an existing fileshare which I can view in Storage Explorer on my machine. I tried to set up Storage Explorer on another machine which is closer to the source so I can upload files.
I get the following error What's up?
Unable to retrieve child resources

ProducerError:{
  "name": "Node Fetch Error",
  "message": "Connect Timeout Error",
  "stack": "ConnectTimeoutError: Connect Timeout Error\n    at onConnectTimeout (C:\\Users\\ME\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\index.js:62:37810)\n    at C:\\Users\\ME\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\index.js:62:37152\n    at Immediate._onImmediate (C:\\Users\\ME\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\index.js:62:37515)\n    at process.processImmediate (node:internal/timers:478:21)",
  "cause": {},
  "code": "UND_ERR_CONNECT_TIMEOUT"
}

Cheers,
Colin

**Comment by craxal** [comment]
@CMCD-git Can you provide all information as per our [bug template](https://github.com/microsoft/AzureStorageExplorer/issues/new?assignees=&labels=&projects=&template=bug_report.yml)? Can you also describe the differences between your machine and the machine you are having problems with (OS, user restrictions, network configurations, etc.).

**Comment by CMCD-git** [comment]
I was going through the steps to document as per the bug template and it started working
