### ISSUE TITLE
Azure File Shares not working

### ISSUE THREAD

**Issue by adtmlf** [microsoft/AzureStorageExplorer#8227]
Unable to retrieve child resources

ProducerError:{
  "name": "Node Fetch Error",
  "message": "Connect Timeout Error",
  "stack": "ConnectTimeoutError: Connect Timeout Error\n    at onConnectTimeout (C:\\Users\\MLFPA\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\index.js:62:37810)\n    at C:\\Users\\MLFPA\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\index.js:62:37152\n    at Immediate._onImmediate (C:\\Users\\MLFPA\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\index.js:62:37515)\n    at process.processImmediate (node:internal/timers:478:21)",
  "cause": {},
  "code": "UND_ERR_CONNECT_TIMEOUT"
}

This is the error message i receive when I try to open my file shares in Azure. Even on the off chance I can access what's in here, it doesn't load properly onto my computer.

**Comment by craxal** [comment]
@adtmlf Can you provide the information we ask for in our [bug template](https://github.com/microsoft/AzureStorageExplorer/issues/new?template=bug_report.yml), including app version, platform, architecture, repro steps, etc.?

Are you using a proxy server at all? Are you using a VM or shared machine?
