### ISSUE TITLE
A refresh notification appears after an 'undelete by Date' activity is skipped with setting 'Auto Refresh on Change' unchecked

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8228]
**Storage Explorer Version**: 1.36.0 (101)
**Build Number**: 20241009.1
**Branch**: rel/1.36.0
**Platform/OS**: Windows 11/Windows 10/Linux Ubuntu 22.04/MacOS Sequoia 15.0(Apple M1 Pro)
**Architecture**: arm64/x64/x64/arm64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch storage explorer -> Open Settings -> Uncheck the setting 'Auto Refresh on Change'.
2. Expand one storage account -> Blob Containers.
3. Create a blob container -> Upload one blob -> Soft delete the blob.
4. Go to 'Active and soft deleted blobs' -> Right click the soft deleted blob -> Click 'Undelete -> Undelete by Date...'.
5. Click 'OK' on the prompt dialog -> There is an activity log indicating that the undelete action was skipped.
![Image](https://github.com/user-attachments/assets/eaf7957a-bcc1-4259-9efa-e26b4571ab13)

6. Check whether no refresh notification appears.

## Expected Experience ##
No refresh notification appears.

## Actual Experience ##
A refresh notification appears.

![Image](https://github.com/user-attachments/assets/c38b0cd4-6276-45ca-895f-e6bc193a6af1)

## Additonal Context ##
1. Fail to undelete the soft deleted blob, so it should not prompt a refresh notification.
2. There is no refresh notification if try to delete a blob with snapshots ( The option 'Also delete blob snapshots' is not checked.)

**Comment by craxal** [comment]
I'm going to consider this a Won't Fix, for the following reasons:

- While it is true that skipped or failed items probably don't result in any changes to the server, the message is not necessarily wrong. The view _may_ be out of date. This is especially true if the container is being modified by some other client. It's generally safer to assume a change may be possible even if nothing appears to have happened.
- In most cases, I would expect there to be multiple operations and at least one of them to be successful. In this case, a change does happen.
- The user can still opt out of the refresh if they want; it is unobtrusive.
- Determining whether a notification should be shown or not increases complexity when very little is to be gained from it.
