### ISSUE TITLE
Suggestions - CosmosDB

### ISSUE THREAD

**Issue by PMoransais** [microsoft/AzureStorageExplorer#823]
I have 3 suggestions for the CosmosDB explorer

1) In main list it would be nice to be able to save filters and select them for a new query

2) In the record list it would be nice to be able to select a field other then id to display

3) if would be VERY nice to have a multiple selection for deletes

thanks

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
