### ISSUE TITLE
Error donload file with AzureStorageExplorer

### ISSUE THREAD

**Issue by TonyPuga** [microsoft/AzureStorageExplorer#824]
I have this error while I'm trying to download a file

{
  "name": "Error",
  "message": "getaddrinfo ENOTFOUND saeusceprod01.blob.core.windows.net saeusceprod01.blob.core.windows.net:443",
  "stack": "Error: getaddrinfo ENOTFOUND saeusceprod01.blob.core.windows.net saeusceprod01.blob.core.windows.net:443\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
  "code": "ENOTFOUND",
  "errno": "ENOTFOUND",
  "syscall": "getaddrinfo",
  "hostname": "saeusceprod01.blob.core.windows.net",
  "host": "saeusceprod01.blob.core.windows.net",
  "port": "443",
  "innerError": {
    "code": "ECONNRESET",
    "errno": "ECONNRESET",
    "syscall": "read"
  }
}

**Comment by MRayermannMSFT** [comment]
Hi @TonyPuga , are you working behind a proxy?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
