### ISSUE TITLE
The contents are previewed as garbled text when previewing a .txt file saved with UTF-16LE

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8245]
**Storage Explorer Version**: 1.36.0-dev (101)
**Build Number**: 20241017.1
**Branch**: main
**Platform/OS**: Windows11/Linux Ubuntu 22.04/MacOS Sequoia 15.0(Apple M1 Pro)
**Architecture**: arm64/x64/arm64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Open Notepad -> Typing some contents into the Notepad window.
2. Go to 'File > Save As' -> In the Save as type dropdown, select All files.
3. In the Encoding dropdown, select UTF-16 LE-> Specific a file name with a .txt extension and click Save.
4. Open storage explorer -> Expand one storage account -> File Shares.
5. Open one file share -> Upload the .txt file 
6. After the upload is successful, right-click the file -> Click 'Preview'.
7. Check whether the contents can be previewed correctly.

## Expected Experience ##
The contents can be previewed correctly.

## Actual Experience ##
The contents are previewed as garbled text.
![Image](https://github.com/user-attachments/assets/d4fa11b1-c399-4576-8183-fb263b48c800)

## Additional Context ##
This issue also reproduces when the file is saved with encoding 'UTF-16 BE'.

**Comment by craxal** [comment]
Similar to how CSV/tabular data works, we've added encoding auto detection and an encoding selector for text preview. This should resolve the issue.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20241019.5. Reproduce. Will verify it on a newer build.

**Comment by craxal** [comment]
Apologies. I need to build a new package. I'll close again when it's done.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20241031.1. Fixed. The encoding selector for text preview has been added.
So, we are going to close it.
![Image](https://github.com/user-attachments/assets/d79cb62c-efac-4a1d-86f3-dd250ebb2fd9)
