### ISSUE TITLE
Following upgrade to latest verions, no longer have access to table data.

### ISSUE THREAD

**Issue by johnJoeScally** [microsoft/AzureStorageExplorer#8249]
### Preflight Checklist

- [x] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [x] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [x] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.36.0

### Regression From

I didn't record what version was installed

### Architecture

x64

### Platform

All

### Bug Description

Unable to retrieve child resources

ProducerError:{
  "name": "Electron Net Error",
  "message": "net::ERR_NAME_NOT_RESOLVED",
  "stack": "Error: net::ERR_NAME_NOT_RESOLVED\n    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:115482)\n    at SimpleURLLoaderWrapper.emit (node:events:519:28)",
  "cause": {}
}

### Steps to Reproduce

Re-start Microsoft Azure Storage Exporter

### Actual Experience

When I start MASE I can't access tables view.

Unable to retrieve child resources

ProducerError:{
  "name": "Electron Net Error",
  "message": "net::ERR_NAME_NOT_RESOLVED",
  "stack": "Error: net::ERR_NAME_NOT_RESOLVED\n    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:115482)\n    at SimpleURLLoaderWrapper.emit (node:events:519:28)",
  "cause": {}
}

**Comment by sergiosolorzano-2** [comment]
I am getting the same problem, why is this closed, how was this resolved?
Thank you
