### ISSUE TITLE
Unable to sign into Azure File Storage Explorer using credentials

### ISSUE THREAD

**Issue by kbhosarekar** [microsoft/AzureStorageExplorer#8251]
### Preflight Checklist

- [x] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [x] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [x] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.36.0

### Architecture

x64

### Storage Explorer Build Number

20241012.1

### Platform

Windows

### OS Version

Windows 11

### Bug Description

{
  "message": "\"WAM Error  \\n Error Code: 0 \\n Error Message: ApiContractViolation \\n WAM Error Message: Disallowed additional query parameter was used: 'domain_hint' \\n Internal Error Code: 590899090 \\n Possible causes: \\n- Invalid redirect uri - ensure you have configured the following url in the application registration in Azure Portal: ms-appx-web://microsoft.aad.brokerplugin/e0001ebd-e920-49b8-a27e-92e573ec0af6 \\n\""
}

### Steps to Reproduce

1. Launch Storage Explorer
2. Sign in using Azure credentials.
3. Select microsoft account, click next.
4. Automatically signed in without being asked for a password.
5. select unfilter after clicking on the gear icon in front of Default Directory

### Actual Experience

I am unable to connect to Azure file storage through storage explorer. I've installed this on a new laptop and am trying to sign in. I clicked on sign in using Azure credentials, and selected my account; however, I wasn't asked for my password, and I automatically see that I am logged in. I am stuck in a constant loop of "reauthenticate now". Despite following troubleshooting options here: https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/blobs/alerts/storage-explorer-troubleshooting?tabs=Windows

![Image](https://github.com/user-attachments/assets/4cd322d6-2d5c-4ae9-a61d-adee51e16523)

### Expected Experience

I am hoping that I would be asked for my password and show up the storage accounts.

### Additional Context

This is a new laptop that I am working on, and I've installed storage explorer for the first time.

**Comment by illbegood73** [comment]
Exactely the same behaviour here, pls fix. Thank you.

**Comment by Liandrel** [comment]
Same here, trying to use Storage explorer first time and Im stuck in Authentication loop

**Comment by kbhosarekar** [comment]
Issue was automatically resolved after shutting down and turning on PC. No action needed.

**Comment by ashwin-kambli** [comment]
I am getting the same error. Restarting the PC did not resolve the problem for me.

**Comment by jiahe620** [comment]
the solution below work for me, as my account login will need multi-factor authentication.

Under **Settings** (gear icon on the left) > Application, look for the **Sign in with** setting.
Change option to "Integrated Sign-in"
Then reauthenticate.

**Comment by JasonYeMSFT** [comment]
If you are still able to reproduce the issue, could you please do us a favor to turn on the verbose logging, collect the authentication logs and share the logs with us? The logs may help us locate the cause of the issue and make a fix.

There are detailed instructions in this section of our troubleshooting guide
https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/blobs/alerts/storage-explorer-troubleshooting?tabs=Windows#authentication-logs

**Comment by craxal** [comment]
Due to how widespread this issue is, we will be releasing 1.36.2 very soon to revert the default authentication method for Windows users.

For anyone having this issue, we invite you to do the following:

## Help us diagnose

1. Install Storage Explorer 1.36.x.
2. Ensure you are signed out and that the "Sign in with:" setting is set to "Authentication Broker".
3. Follow the [troubleshooting docs](https://learn.microsoft.com/troubleshoot/azure/azure-storage/blobs/alerts/storage-explorer-troubleshooting?tabs=Windows#authentication-logs) to gather authentication logs.
4. Please clear out any existing logs from the logs folder if you can.
5. Share your logs by posting a comment in #8237!

## Unblock yourself

1. Install Storage Explorer 1.36.x.
2. Change the value for the "Sign In with:" setting to be "Default Web Browser".
3. Try signing in.

Thank you everyone for your patience and your help in diagnosing this issue!

**Comment by vronp** [comment]
Any chance this was also affecting hotmail.com users?  I am on 1.37.0

Thank you.

**Comment by craxal** [comment]
@vronp Try fiddling with your "Sign in With" setting. 1.37.0 should have fixed some issues with authentication broker, and many users report that problems go away after switching.
