### ISSUE TITLE
Storage Explorer unexpectedly closes after closing a formatted JSON tab

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8253]
**Storage Explorer Version**: 1.36.0-dev (101)
**Build Number**: 20241012.1
**Branch**: main
**Platform/OS**: Windows11/Windows11/Linux Ubuntu 22.04/MacOS Sequoia 15.0(Apple M1 Pro)
**Architecture**: arm64/x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.35.0)

## Steps to Reproduce ##
1. Expand one Storage Account -> Blob Containers.
2. Create a blob container -> Upload a .json file.
3. Right click the .json file -> Click 'Preview'.
4. In the preview panel, right-click and choose 'Format JSON'.
5. Close the preview tab.
6. Check whether Storage Explorer is still open.

## Expected Experience ##
Storage Explorer remains open.

## Actual Experience ##
Storage Explorer closes unexpectedly.

**Comment by craxal** [comment]
A user has already reported on this (#8235).

**Comment by craxal** [comment]
@v-xianya Does this also repro on macOS Sonoma (14)? Sequoia is a pretty new version, which we aren't yet ready to test on.

**Comment by v-xianya** [comment]
@craxal We verified this issue on the macOS Sonoma (14.6.1), it reproduces.
