### ISSUE TITLE
UND_ERR_SOCKET","message":"other side closed" - but it's open. It really is

### ISSUE THREAD

**Issue by owebeewan** [microsoft/AzureStorageExplorer#8256]
### Preflight Checklist

- [x] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [x] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [x] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.35.0 (100)

### Architecture

x64

### Storage Explorer Build Number

20240810.1

### Platform

Windows

### OS Version

Windows 11

### Bug Description

Unable to retrieve child resources
```
ProducerError:{
  "name": "Node Fetch Error",
  "message": "{\"name\":\"Node Fetch Error\",\"cause\":{},\"code\":\"UND_ERR_SOCKET\"}"
}
```

after launching with "--ignore-certificate-errors"
```
 C:\Program Files\Microsoft Azure Storage Explorer> .\StorageExplorer.exe --ignore-certificate-errors
```

### Steps to Reproduce

1. Launch Storage Explorer from command line:  C:\Program Files\Microsoft Azure Storage Explorer> .\StorageExplorer.exe --ignore-certificate-errors
2. Connect Dialog
3. No proxy, https, 10251,10252,10253

![Image](https://github.com/user-attachments/assets/96448556-9139-499d-ac4d-70d3a2709c0d)

4. Click on Blob Containers

### Actual Experience

![Image](https://github.com/user-attachments/assets/5c129ca7-d4fe-4cbb-9e37-e87ce2d921d7)

Error with UND_ERR_SOCKET

### Expected Experience

Would connect to  Microsoft.Azure.Cosmos.Emulator.exe seamlessly and I can browse blob storage

### Additional Context

The Emulator is running: ![Image](https://github.com/user-attachments/assets/26eae118-04f6-4d0b-b1b9-ad418e29b787)
I started it from the command line as simply: **C:\Program Files\Azure Cosmos DB Emulator>Microsoft.Azure.Cosmos.Emulator.exe**

I pasted the emulator Account Key into Storage Explorer Connect

I started Explorer as follows:[StorageExplorerLogs_activity-log_28284.log](https://github.com/user-attachments/files/17497270/StorageExplorerLogs_activity-log_28284.log)

![Image](https://github.com/user-attachments/assets/23ce1f45-9061-47ed-b79c-55a3dbfaa943)

The log files contain a lot of: 
```
[2024-10-23T18:04:15.946Z] (blob-extension:56144) <ERRO> HttpClient threw while making API call for BlobService.getAccountInfo
  GET https://127.0.0.1:10251/devstoreaccount1?comp=properties&restype=account
  Credential used: Account name and key - account name: devstoreaccount1, account key: ******, keyName: undefined
  RequestId: 45c22744-5b73-4503-baaa-37e9144318de, Date sent: Wed, 23 Oct 2024 18:04:15 GMT, ApiVersion: 2019-07-07, ProxySettings: undefined
  Error: {"name":"Node Fetch Error","cause":{},"code":"UND_ERR_SOCKET","message":"other side closed"}

```

**Comment by craxal** [comment]
@owebeewan You're trying to connect to an CosmosDB emulator, correct? Storage Explorer does not support connecting to CosmosDB resources and only supports connecting to an Azure Storage resources or emulators. If you'd like something for accessing CosmosDB resources, you might want to try their [dedicated application](https://learn.microsoft.com/en-us/azure/cosmos-db/data-explorer)
