### ISSUE TITLE
Fail to play video file in browser if it doesn't have current version

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#8259]
**Storage Explorer Version:** 1.37.0-dev (101)
**Build Number:** 20241024.1
**Branch:** main
**Platform/OS:** Windows11/Linux Ubuntu 22.04/MacOS Sequoia 15.0(Apple M1 Pro)
**Architecture:** arm64/x64/arm64
**How Found:** Exploratory testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers. (Make sure blob versioning is enabled)
2. Create a blob container -> Upload a .MP4 file.
3. Right click the blob -> Click 'Manage History-> Manage Versions'.
4. Delete the blob -> Select the blob version -> Click 'Play in Browser'.
5. Check whether succeeds to play the file in browser.

## Expected Experience ##
Succeed to play the file in browser.

## Actual Experience ##
Fail to play the file in browser.
![Image](https://github.com/user-attachments/assets/865c11e1-4545-41fe-920e-c9e3a16c99b1)

## Additional Context ##
1. This issue reproduces for all video files.
2. This issue doesn't reproduce for csv/avro/parquet files.

**Comment by JasonYeMSFT** [comment]
We probably are missing the version id in the generated url.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20241119.13. Fixed. So, we are going to close it.
