### ISSUE TITLE
macOS - Last modified not applying daylight savings adjustment

### ISSUE THREAD

**Issue by RobBarat** [microsoft/AzureStorageExplorer#826]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: macOS
**Architecture**: x64
**Regression From**: Just noticed this on Macbook OS. Not happening for Windows

#### Steps to Reproduce: ####
1. Open container and view blobs.

#### Expected Experience: ####
Expecting to see local time.

#### Actual Experience: ####
Expecting time to be UTC +11 (Sydney) but only seeing a +10 adjustment on macOS.

![screen shot 2018-11-01 at 8 43 45 am](https://user-images.githubusercontent.com/25378721/47820745-84661580-ddb2-11e8-963d-185f6443806c.png)

**Comment by craxal** [comment]
Did you by chance leave Storage Explorer running during the DST transition? DST transitions are essentially just moving to a different timezone, which I don't think we can handle dynamically. Does restarting Storage Explorer may solve this issue?

**Comment by RobBarat** [comment]
Not that I'm aware of.
I just dropped in version 1.6 and the behaviour is the same. 
Just trying to work out if there is a way to clear the cache in MacOS.

**Comment by craxal** [comment]
Stupid question, but is your Mac's time zone correct? Is the time correct on Windows?

**Comment by RobBarat** [comment]
Time zone in MacOs is Australia/Sydney
In Parallels / Windows 10 - It's set to UTC +10:00 Canberra, Melbourne, Sydney.
Time is correct both Windows and MacOS.

**Comment by craxal** [comment]
One way to verify this is to manually change your system's time zone (preferably between standard and daylight time of your current time zone). Do the dates and times display correctly after relaunching Storage Explorer?

**Comment by RobBarat** [comment]
When I set to time zone to Brisbane, the adjustment in Storage explorer is +10, and the time is 1 hour behind Sydney, so the blobs show the correct time.
Interestingly, when I set it back to Sydney, and hit refresh (without reopening storage explorer) the attached messages appears. Reopening Storage explorer, the message doesn't show and the incorrect +10 adjustment is still applied.
<img width="285" alt="screen shot 2019-01-19 at 12 42 14 pm" src="https://user-images.githubusercontent.com/25378721/51420699-81780580-1be8-11e9-9f47-b130511fc441.png">

**Comment by craxal** [comment]
I don't think changing the timezone while the application is running will work as expected. We use the native `Date.getTimezoneOffset` function. And I don't think the Electron/Node environment picks up system changes unless you restart.

If you're willing to do a little debugging, can you give this a try:
1. Hit F12 to open the dev tools window.
2. Select Sources tab, then press Cmd+P and enter TimestampUtilities.js.
3. In the open file, drop a breakpoint at line 33:
   ```js
    if (timezone === Timezone_1.default.utc) {
   ```
4. Follow the same procedure you mentioned above.

Let me know what happens (I won't be surprised if the breakpoint never gets hit).

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
