### ISSUE TITLE
Failure to Connect

### ISSUE THREAD

**Issue by johnh1974** [microsoft/AzureStorageExplorer#8260]
### Preflight Checklist

- [x] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [x] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [x] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.35.0

### Regression From

1.35.0

### Architecture

i86

### Storage Explorer Build Number

20240810.1

### Platform

All

### OS Version

Edition	Windows 11 Pro Version	23H2 Installed on	‎2/‎24/‎2023 OS build	22631.4317 Experience	Windows Feature Experience Pack 1000.22700.1041.0

### Bug Description

Unable to retrieve child resources

ProducerError:{
  "name": "Electron Net Error",
  "message": "net::ERR_CONNECTION_REFUSED",
  "stack": "Error: net::ERR_CONNECTION_REFUSED\n    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:114352)\n    at SimpleURLLoaderWrapper.emit (node:events:519:28)",
  "cause": {}
}

### Steps to Reproduce

Attempt to attach to existing Azure Storage Account

### Actual Experience

Unable to access Storage Account with Azure Storage Explorer

**Comment by craxal** [comment]
@johnh1974 Can you provide more details about your steps?
- How are you trying to attach to the account (sign in, key, SAS)? If sign in or SAS, can you verify you have the needed permissions to connect?
- Are you working behind a proxy at all? What are your proxy settings set to? Do you require any custom certificates?
- Are there other storage accounts you are able to connect to?
- Version 1.35.0 does not support i86 machines (see [1.29.0 release notes](https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.29.0)). Can you verify that your machine is indeed i86 or x64? Is this what appear in the About dialog? If so, I would suggest you install the latest version of Storage Explorer for Windows x64/ARM64 (depending on your architecture) and try again.
