### ISSUE TITLE
unable to connect to storage explorer

### ISSUE THREAD

**Issue by Padmaja511** [microsoft/AzureStorageExplorer#8262]
### Preflight Checklist

- [x] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [x] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [x] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

unable to locate version

### Architecture

i86

### Platform

All

### Bug Description

storage explorer not working

### Steps to Reproduce

storage explorer not working tried to authenticate but not working.

### Actual Experience

storage explorer not working tried to authenticate but not working.

**Comment by craxal** [comment]
@Padmaja511 Can you explain your problem in more detail by providing the exact steps you followed? Does the app launch at all?

The version of Storage Explorer and most other information we ask for can be found by selecting **Help > About** from the menu (in Windows or Linux) or **Storage Explorer > About** (in Mac). The version is also visible in the splash window that appears when you launch the app.
 
Please note that 32-bit systems (i86) are no longer supported. If your machine has an x64 or ARM64 architecture, we encourage you to install the matching flavor of Storage Explorer.
