### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by lazybadcode** [microsoft/AzureStorageExplorer#8266]
### Preflight Checklist

- [x] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [x] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [x] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.34.0

### Architecture

i86

### Platform

All

### Bug Description

Unable to retrieve child resources

ProducerError:{
  "name": "Node Fetch Error",
  "message": "{\"name\":\"Node Fetch Error\",\"cause\":{\"cause\":{\"errno\":-3008,\"code\":\"ENOTFOUND\",\"syscall\":\"getaddrinfo\",\"hostname\":\"strgsahlhu001.blob.core.windows.net\"}},\"code\":\"ENOTFOUND\",\"errno\":-3008}"
}

### Steps to Reproduce

1. test to connect storage account and expand to list a container then will show an error

Unable to retrieve child resources

ProducerError:{
  "name": "Node Fetch Error",
  "message": "{\"name\":\"Node Fetch Error\",\"cause\":{\"cause\":{\"errno\":-3008,\"code\":\"ENOTFOUND\",\"syscall\":\"getaddrinfo\",\"hostname\":\"strgsahlhu001.blob.core.windows.net\"}},\"code\":\"ENOTFOUND\",\"errno\":-3008}"
}

### Actual Experience

1. test to connect storage account and expand to list a container then will show an error

Unable to retrieve child resources

ProducerError:{
  "name": "Node Fetch Error",
  "message": "{\"name\":\"Node Fetch Error\",\"cause\":{\"cause\":{\"errno\":-3008,\"code\":\"ENOTFOUND\",\"syscall\":\"getaddrinfo\",\"hostname\":\"strgsahlhu001.blob.core.windows.net\"}},\"code\":\"ENOTFOUND\",\"errno\":-3008}"
}

**Comment by craxal** [comment]
@lazybadcode We no longer support 32-bit (i86) Storage Explorer. Is it possible for you to install the latest 64-bit version and try again?
