### ISSUE TITLE
It would be better to remove the term 'Visual Studio' from the content in the remove account confirmation dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8268]
**Storage Explorer Version**: 1.37.0-dev (102)
**Build Number**: 20241028.13
**Branch**: hotfix/1.36.2
**Platform/OS**: Windows11/Linux Ubuntu 22.04/MacOS Sequoia 15.0(Apple M1 Pro)
**Architecture**: arm64/x64/arm64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch storage explorer -> Sign in with one Azure account.
2. Go to the 'ACCOUNT MANAGEMENT' -> Click 'Remove'.
3. A confirmation dialog pops up -> Observe the content in the dialog.

## Expected Experience ##
It would be better to remove the term 'Visual Studio' from the content.

## Actual Experience ##
The dialog currently displays 'Visual Studio' in its content.
![Image](https://github.com/user-attachments/assets/505e8aef-0fb5-45d1-8637-4d301e58a51a)

**Comment by craxal** [comment]
I think this is by design. The identity service we use for authentication is the same service used by Visual Studio. If a user has Visual Studio installed, and the user signs out from Storage Explorer, that will sign them out of Visual Studio, too. So, we include this to let them know that.

**Comment by v-xianya** [comment]
Hi @craxal The comments make sense to me. However, there are some confusing aspects:

We tried having both Storage Explorer and Visual Studio installed. When we sign out from Storage Explorer, the account in Visual Studio remains signed in.

Similarly, if I sign out from Visual Studio, the account in Storage Explorer still stays signed in.
here is the confirmation dialog when removing account from Visual Studio.
![Image](https://github.com/user-attachments/assets/ac75106a-293c-48f4-9d53-dc5507f2a27c)

**Comment by craxal** [comment]
It seems you're right. Apparently, the association was severed some time ago. Storage Explorer and Visual Studio now have separate sign in collections. So, I think we can update the string.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20241101.5. The term 'Visual Studio' has been removed. So, we are going to close it.
![Image](https://github.com/user-attachments/assets/093d709e-ead1-460b-8158-d159dc65a947)
