### ISSUE TITLE
It will focus on the already opened blob container instead of opening it in a separate panel when clicking 'Open to the Side'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8269]
**Storage Explorer Version**: 1.37.0-dev (102)
**Build Number**: 20241028.11
**Branch**: main
**Platform/OS**: Windows11/Linux Ubuntu 22.04/MacOS Sequoia 15.0(Apple M1 Pro)
**Architecture**: arm64/x64/arm64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Click 'View all' -> Create a blob container.
3. Go to the view all containers explorer -> Right click the newly created blob container.
4. Click 'Open to the Side'.
5. Check whether the blob container opens in a separate panel.

## Expected Experience ##
The blob container opens in a separate panel.

## Actual Experience ##
The currently opened blob container is focused.

**Comment by v-xianya** [comment]
Hi @richardMSFT Verified this issue on the rel build 20241214.2. 
Clicking "Open on the Side" will now always open a new tab in a split panel. Is this expected?
![Image](https://github.com/user-attachments/assets/867298a1-bfd5-499f-a54c-c9a13a4ea9e8)

**Comment by craxal** [comment]
@v-xianya Yes, this is expected. That is exactly what "Open on the Side" is designed to do.

**Comment by v-xianya** [comment]
Hi @craxal Got it. Thanks for your response! As the current behavior is expected. We will close this issue.
