### ISSUE TITLE
Unable to upload large files from stream (upper than 100MB)

### ISSUE THREAD

**Issue by nemrism** [Microsoft/AzureStorageExplorer#827]
**Storage Explorer Version**: latest (5.8)
**Platform/OS Version**: Windows/10 x64
**Architecture**: ia32
**Regression From**: 5.6

#### Steps to Reproduce: ####
1. Upload stream async (larger than 100Mb)
2. Wait for the unhandled exception to raise (NullReference inner exception)

#### Expected Experience: ####
Successful async upload
It is actually working on a real Azure storage

#### Actual Experience: ####
Failure See logs attached

[Error_debug01-Nov-18-15-11.log](https://github.com/Microsoft/AzureStorageExplorer/files/2539026/Error_debug01-Nov-18-15-11.log)
[Error01-Nov-18-15-11.log](https://github.com/Microsoft/AzureStorageExplorer/files/2539027/Error01-Nov-18-15-11.log)
[Info_debug01-Nov-18-15-11.log](https://github.com/Microsoft/AzureStorageExplorer/files/2539028/Info_debug01-Nov-18-15-11.log)
[Info01-Nov-18-15-11.log](https://github.com/Microsoft/AzureStorageExplorer/files/2539029/Info01-Nov-18-15-11.log)
[LinqToSQL01-Nov-18-15-11.log](https://github.com/Microsoft/AzureStorageExplorer/files/2539030/LinqToSQL01-Nov-18-15-11.log)
[Perf01-Nov-18-15-11.log](https://github.com/Microsoft/AzureStorageExplorer/files/2539031/Perf01-Nov-18-15-11.log)
[UnhandledException01-Nov-18-15-11.log](https://github.com/Microsoft/AzureStorageExplorer/files/2539032/UnhandledException01-Nov-18-15-11.log)
[Verbose_debug01-Nov-18-15-11.log](https://github.com/Microsoft/AzureStorageExplorer/files/2539033/Verbose_debug01-Nov-18-15-11.log)
[Verbose01-Nov-18-15-11.log](https://github.com/Microsoft/AzureStorageExplorer/files/2539034/Verbose01-Nov-18-15-11.log)

**Comment by MRayermannMSFT** [comment]
@nemrism, I don't think this is the repo you are looking for. We don't have a version 5.8, and we don't have any sort of "upload from stream" feature. I'm going to close this issue for now. Let me know if you think I'm wrong though...

**Comment by nemrism** [comment]
Indeed, the correct repo is this one: 
https://github.com/Azure/azure-storage-net

Is there a way for you to transfer the issue to it?

**Comment by nemrism** [comment]
Forget about it... they have another issue template. I'll copy paste the informations!
