### ISSUE TITLE
File share issue

### ISSUE THREAD

**Issue by Gautam-916** [microsoft/AzureStorageExplorer#8272]
### Preflight Checklist

- [x] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [x] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [x] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

October 2024 (Version 1.36.2)

### Architecture

i86

### Platform

All

### Bug Description

{
  "name": "Node Fetch Error",
  "message": "getaddrinfo ENOTFOUND storageassignment3.file.core.usgovcloudapi.net",
  "stack": "Error: getaddrinfo ENOTFOUND storageassignment3.file.core.usgovcloudapi.net\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)",
  "cause": {},
  "code": "ENOTFOUND",
  "errno": -3008
}

### Steps to Reproduce

October 2024 (Version 1.36.2)

### Actual Experience

{
  "name": "Node Fetch Error",
  "message": "getaddrinfo ENOTFOUND storageassignment3.file.core.usgovcloudapi.net",
  "stack": "Error: getaddrinfo ENOTFOUND storageassignment3.file.core.usgovcloudapi.net\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)",
  "cause": {},
  "code": "ENOTFOUND",
  "errno": -3008
}

### Expected Experience

{
  "name": "Node Fetch Error",
  "message": "getaddrinfo ENOTFOUND storageassignment3.file.core.usgovcloudapi.net",
  "stack": "Error: getaddrinfo ENOTFOUND storageassignment3.file.core.usgovcloudapi.net\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)",
  "cause": {},
  "code": "ENOTFOUND",
  "errno": -3008
}

### Additional Context

{
  "name": "Node Fetch Error",
  "message": "getaddrinfo ENOTFOUND storageassignment3.file.core.usgovcloudapi.net",
  "stack": "Error: getaddrinfo ENOTFOUND storageassignment3.file.core.usgovcloudapi.net\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)",
  "cause": {},
  "code": "ENOTFOUND",
  "errno": -3008
}

**Comment by craxal** [comment]
@Gautam-916 Can you verify the correct architecture? We no longer support 32-bit Storage Explorer, and we stopped shipping 32-bit flavors starting with 1.30. All of the relevant information can be seen from **Help > About**.

Can you also please verify your repro steps? The only think listed is the app version. Specifically, can you tell us how you signed in? Did you select "Azure US Government" as your environment?
