### ISSUE TITLE
The scrollbar on the 'Properties' panel is not aligned to the left after switching from the 'Actions' panel

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8275]
**Storage Explorer Version**: 1.37.0-dev (102)
**Build Number**: 20241106.1
**Branch**: main
**Platform/OS**: Windows 11/Windows 11/Linux Ubuntu 22.04/MacOS Sequoia 15.0(Apple M1 Pro)
**Architecture**: arm64/x64/x64/arm64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Open Storage Explorer and select a storage account.
2. Observe the scrollbar on the Properties panel (If there isn't a scrollbar, resize the panel until one appears).
4. Navigate to the 'Actions' panel and click on 'Properties'.
5. Check whether the scrollbar is aligned to the left.

## Expected Experience ##
The scrollbar is aligned to the left.
![Image](https://github.com/user-attachments/assets/2f63058c-4b54-42f7-9c87-aad065221529)

## Actual Experience ##
The scrollbar is not aligned to the left.
![Image](https://github.com/user-attachments/assets/dfa21199-83b7-44eb-ab55-acc2e42789cb)

## Additional Context ##
![Image](https://github.com/user-attachments/assets/13cf578e-913b-4d07-ad95-0237ea96832c)

**Comment by craxal** [comment]
Not a blocking issue, so we're not going to worry about fixing this unless users are having trouble with it.
