### ISSUE TITLE
Can't access blobs any longer

### ISSUE THREAD

**Issue by piskovvx** [microsoft/AzureStorageExplorer#8277]
### Preflight Checklist

- [x] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [x] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [x] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.36.2

### Regression From

No

### Architecture

x64

### Platform

Windows

### Bug Description

```
Unable to retrieve child resources

ProducerError:{
  "name": "Electron Net Error",
  "message": "{\"name\":\"Electron Net Error\",\"cause\":{}}"
}
```

### Steps to Reproduce

1. Launch Storage Explorer
2. Expand Blob Containers

### Actual Experience

It throws the error message 

```
Unable to retrieve child resources

ProducerError:{
  "name": "Electron Net Error",
  "message": "{\"name\":\"Electron Net Error\",\"cause\":{}}"
}
```

### Expected Experience

Shows blobs containers

**Comment by craxal** [comment]
For anyone experiencing this issue, to help us diagnose the problem, please try the following:
- Check your sign in method (**Application > Sign-In > Sign In with:**). If it is set to "Authentication Broker", switch to something else, such as "Default Web Browser". If you're still having issues, try a different sign in method.
- Try signing out and signing back in.
- Try uninstalling and reinstalling.
- Try rolling back the version to an earlier one and see of the problem persists. Please share the version here if there's a version it does not reproduce.
- If you're working through a proxy server, check your proxy settings. Try working where a proxy is not needed. Adjust settings as needed.
- Check your application and authentication logs and share anything that looks odd to you. If in doubt, you can share the logs here.

**Comment by craxal** [comment]
Is it possible to try connecting from a different network?

Also related to #7992.
