### ISSUE TITLE
The generated SAS URI for blob does not open the blob

### ISSUE THREAD

**Issue by nemrism** [Microsoft/AzureStorageExplorer#828]
**Storage Explorer Version**: latest (5.8)
**Platform/OS Version**: Windows/10 x64
**Architecture**: ia32
**Regression From**: don't know

#### Steps to Reproduce: ####
1. Right click in UI on a blob
2. Generate SAS URI
3. Try to download it

#### Expected Experience: ####
Download happens

#### Actual Experience: ####
Following Internal Server Error (XML downloaded instead of the blob):
Server encountered an internal error. Please try again after some time. RequestId:f0aaf1e6-007b-45cf-a2ed-fde902d2e2b7 Time:2018-11-01T15:24:14.6509496Z

In ASE logs, you got the following lines:

**Info log:**
[Info_debug] [ActivityId=a4a28182-860d-421a-ace3-e980b5fef038] Setting status description as "Server encountered an internal error. Please try again after some time."

**Error log:**
[Error_debug] [ActivityId=a4a28182-860d-421a-ace3-e980b5fef038] Exception raised during processing of request. Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.FatalServerCrashingException: The fatal unexpected exception 'Object reference not set to an instance of an object.' encountered during processing of request. ---> AsyncHelper.NullReferenceRethrowableException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Cis.Services.Nephos.Storage.Service.Protocols.Rest.HttpRestProcessor.<CommitBlobImplV2>d__101.MoveNext()
   at AsyncHelper.AsyncIteratorContextBase.ExecuteIterator(Boolean inBegin)
   --- End of inner exception stack trace ---
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.EndPerformOperation(IAsyncResult ar)
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.<ProcessImpl>d__103.MoveNext()
   --- End of inner exception stack trace ---

**Unhandled log**
[UnhandledException] [ActivityId=a4a28182-860d-421a-ace3-e980b5fef038] EXCEPTION thrown: Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.FatalServerCrashingException: The fatal unexpected exception 'Object reference not set to an instance of an object.' encountered during processing of request. ---> AsyncHelper.NullReferenceRethrowableException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Cis.Services.Nephos.Storage.Service.Protocols.Rest.HttpRestProcessor.<CommitBlobImplV2>d__101.MoveNext()
   at AsyncHelper.AsyncIteratorContextBase.ExecuteIterator(Boolean inBegin)
   --- End of inner exception stack trace ---
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.EndPerformOperation(IAsyncResult ar)
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.<ProcessImpl>d__103.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessor.EndProcess(IAsyncResult result)
   at Microsoft.WindowsAzure.DevelopmentStorage.Store.BlobServiceEntry.ProcessAsyncCallback(IAsyncResult ar)

**Verbose log**
[Verbose_debug] [ActivityId=a4a28182-860d-421a-ace3-e980b5fef038] Accepting request
[Verbose_debug] [ActivityId=a4a28182-860d-421a-ace3-e980b5fef038] Got request PUT http://127.0.0.1:10000/devstoreaccount1/maincontainer/670d8d88-c68a-4949-8e6a-956c5e1c9673.MP4?comp=blocklist 2015-12-11
[Verbose_debug] [ActivityId=a4a28182-860d-421a-ace3-e980b5fef038] Host-style URI resolution failed. Allowing path-style for uri http://127.0.0.1:10000/devstoreaccount1/maincontainer/670d8d88-c68a-4949-8e6a-956c5e1c9673.MP4?comp=blocklist
[Verbose_debug] [ActivityId=a4a28182-860d-421a-ace3-e980b5fef038] StorageAccount.GetPropertiesImpl(PropertyNames=0x0020, ServiceMetadataPropertyNames=0x000000007807C000,,00:00:30)
[Verbose_debug] [ActivityId=a4a28182-860d-421a-ace3-e980b5fef038] Returning from AcceptRequest method.
[Verbose_debug] [ActivityId=a4a28182-860d-421a-ace3-e980b5fef038] Setting status code to 500
[Verbose_debug] [ActivityId=a4a28182-860d-421a-ace3-e980b5fef038] In the process end callback
[Verbose_debug] [ActivityId=a4a28182-860d-421a-ace3-e980b5fef038] Entering BasicHttpRestProcessor.EndProcess

**Comment by jinglouMSFT** [comment]
I don't believe this is the right repo you were looking for.  Storage Explorer never had versions 5.8.  The error messages don't look familiar either.

**Comment by nemrism** [comment]
Indeed, my mistake, correct repo is this one: https://github.com/Azure/azure-storage-net
Could you transfer the issue to it?

**Comment by nemrism** [comment]
Forget about this, they have a different issue template. I'll copy paste the information in new ones.

**Comment by jinglouMSFT** [comment]
great.  Github also has a beta feature to transfer issues from one repo to another.

**Comment by nemrism** [comment]
Yup, heard about it, that's why I was asking ;)
However their issue template is really different so I recreated it
