### ISSUE TITLE
Crash in clipboardFiles.node when copying from certain other apps

### ISSUE THREAD

**Issue by MichaelBuckley** [microsoft/AzureStorageExplorer#8280]
### Preflight Checklist

- [x] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [x] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [x] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.36.2

### Architecture

arm64

### Storage Explorer Build Number

20241029.2

### Platform

macOS

### OS Version

macOS 14 and 15, possibly earlier versions too

### Bug Description

Storage Explorer will crash as soon as data another app with a specific structure is placed in the system-wide pasteboard.

### Steps to Reproduce

1. Launch Storage Explorer
2. Launch Transmit 5.10.5 ( https://panic.com/transmit/ ) (There is a free trial period which can be use to test this bug.)
3. Connect to a server in Transmit.
4. Select a file on the server in Transmit
5. Edit > Copy or command-c

### Actual Experience

Storage Explorer crashes. Here is a sample crash log. [Microsoft Azure Storage Explorer-2024-11-05-125837.txt](https://github.com/user-attachments/files/17654216/Microsoft.Azure.Storage.Explorer-2024-11-05-125837.txt)

### Expected Experience

Storage Explorer does not crash.

### Additional Context

The crash appears to occur when Storage Explorer attempts to parse the data placed on the macOS pasteboard. Some other apps can't process the data, but Storage Explorer is the only app we found that crashes. We here at Panic have found a solution and will release an update to Transmit that won't trigger the crash, other apps could cause Storage Explorer to crash if they use the pasteboard the same way.

We suspect there may be a bug in macOS causing a problem with the data to be written to the pasteboard. We're still gathering information and will follow up with Apple if so.

The issue itself is very strange. Transmit creates an `NSFilePromiseProvider` for the file and places it on the pasteboard. Transmit also also attaches a `userInfo` dictionary to this `NSFilePromiseProvider`. As long as the userInfo dictionary remains flat, Storage Explorer will not crash. However, if another dictionary is added as a value to this userInfo dictionary, Storage Explorer will crash.

The userInfo dictionary ought to only be available to Transmit. The fact that this affects the pasteboard for other apps is surprising to us.

**Comment by MichaelBuckley** [comment]
Here's a more readable crash report. Sorry about the last one. [Microsoft.Azure.Storage.Explorer-2024-11-05-125837-translated.txt](https://github.com/user-attachments/files/17654309/Microsoft.Azure.Storage.Explorer-2024-11-05-125837-translated.txt)

**Comment by craxal** [comment]
@JasonYeMSFT Can you look into this? If you don't have time feel free to reassign.

**Comment by MichaelBuckley** [comment]
@JasonYeMSFT I will try to put together a minimally-reproducible sample today, but just from looking at that code and the stack trace in the crash, I'm almost entirely certain that the problem is calling std::string::substr(7) without checking that the string is at least 7 characters long. When the position parameter for substr is greater than the string length, it throws std::out_of_bounds, which is what we see in the stack trace.

Exactly what < 7 length URL you're getting there when we put an NSDictionary in an NSDictionary, I'm not sure, but I'll find out shortly.

**Comment by MichaelBuckley** [comment]
That is indeed the problem. The URL is an empty string in this case, and the crash occurs in the std::string::substr call.

This appears to be a bug in macOS itself. Calling `[pb types]` in the code above returns slightly different types. When copying from the version of Transmit that causes the crash, the types list includes `public.file-url`, but the actual URL is an https:// URL. We're not copying a local file, so it would make sense that's an empty URL.  However, when copying from the fixed version of Transmit, the types list instead contains `public.url`.

I'll still see if I can get a minimally-reproducible case—the code in Transmit is not trivial—and I'll follow up with Apple, but you might want to add a check before you call substr.

**Comment by MichaelBuckley** [comment]
Update for anyone who finds this in a Google search years down the road:

There was no bug in macOS. Transmit had a piece of code that was looking for data in the outer userInfo dictionary when it should have been looking in the inner userInfo dictionary. There's noting inherently wrong with nesting dictionaries. But as a result of the bug in Transmit, it was placing an empty string as a URL on the pasteboard. I'm attaching a sample project which you can build in Xcode and click a button to recreate how Transmit was putting the empty URL on the pasteboard.

[PasteTest.zip](https://github.com/user-attachments/files/17721612/PasteTest.zip)

**Comment by JasonYeMSFT** [comment]
I merged a change to check for the url string to prevent the out of range error.

**Comment by MRayermannMSFT** [comment]
@MichaelBuckley if you'd like to help us make sure our fix for this issue is sufficient, we have a preview release of 1.37.0 that you can find here: https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.37.0-preview.1

If you have time, please download & install this preview release, and try to reproduce this issue. You can then let us know here whether or not you were still able to reproduce. If you were able to reproduce, please share any information (error messages, screenshots, etc.) that may help us understand why our fix was not successful.

After you are done with this, we recommend you return back to Storage Explorer 1.36, which you can find here: https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.36.2 .

Thank you in advance for finding the time for this!

**Comment by MRayermannMSFT** [comment]
The preview release has been un-published. You can now use 1.37.0: https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.37.0

Please open a new issue if this continues to reproduce in 1.37.0.
