### ISSUE TITLE
It would be better to include all options in the description of the upload dialog for blob containers and file shares

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8282]
**Storage Explorer Version**: 1.37.0-dev (102)
**Build Number**: 20241106.1
**Branch**: main
**Platform/OS**: Windows 11/Windows 11/Linux Ubuntu 22.04/MacOS Sequoia 15.1(Apple M1 Pro)
**Architecture**: arm64/x64/x64/arm64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Open one blob container -> Click 'Upload -> Upload Folder...'.
3. Observe the descriptions in the 'Upload Folder' dialog.

## Expected Experience ##
It would be better to include all options in the descriptions.

## Actual Experience ##
Not all options are included in the descriptions.
![Image](https://github.com/user-attachments/assets/25be92f3-0e24-4a80-996b-ef1d0709b016)

## Additional Context ##
1. This issue also reproduces for 'Upload Files' dialog.
2. This issue also reproduces for file shares.

**Comment by craxal** [comment]
Won't fix. The purpose of the description is not to enumerate all possible options but to give a general idea of what the inputs should be. Unless users think the description is vague or inaccurate, I think we'll leave it as is.
