### ISSUE TITLE
The json file is not formatted after clicking 'Format JSON'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8283]
**Storage Explorer Version**: 1.37.0-dev (102)
**Build Number**: 20241106.1
**Branch**: main
**Platform/OS**: Windows 11/Windows 11/Linux Ubuntu 22.04/MacOS Sequoia 15.1(Apple M1 Pro)
**Architecture**: arm64/x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.36.2)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one .json file.
3. Right click the .json file -> Click 'Preview'.
4. In the preview panel, right-click and choose 'Format JSON'.
5. Check whether the file is formatted.

## Expected Experience ##
The file is formatted.
![Image](https://github.com/user-attachments/assets/0d8f0f7e-c7e9-41ba-a9ea-e358a298ceff)

## Actual Experience ##
The file is not formatted.
![Image](https://github.com/user-attachments/assets/3c7782e4-dfd0-40d1-9062-e605d46f1fb1)

**Comment by craxal** [comment]
I see the problem. The format action setup for the editor captures the initial `props.value` ("Loading..."). Although the editor displays the expected data, the action always uses the initial value. So, we need to figure out how to get the editor actions to use the updated `props.value`.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20241107.5. Fixed.
