### ISSUE TITLE
All entities are calculated when executing 'Table Statistics' for the queried entities

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#8285]
**Storage Explorer Version:** 1.37.0-dev (102)
**Build Number:** 20241107.5
**Branch:** main
**Platform/OS:** Windows 11/Windows 11/Linux Ubuntu 22.04/MacOS Sequoia 15.1(Apple M1 Pro)
**Architecture:** arm64/x64/x64/arm64
**How Found:** From running test cases
**Regression From:** Previous release (1.36.2)

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create a table -> Add several entities.
3. Click 'Query' -> Add one clause -> Execute query.
4. Click 'Table Statistics' -> Observe the activity log.
5. Check whether only the queried entities are calculated.

## Expected Experience ##
Only the queried entities are calculated.
![Image](https://github.com/user-attachments/assets/3a2ad6d9-02e4-49fc-b25b-82052e6c012d)

## Actual Experience ##
All entities are calculated.
![Image](https://github.com/user-attachments/assets/0f73bac4-3e2e-4148-bfa8-8803c0aee751)

**Comment by craxal** [comment]
Probably an oversight when refactoring tables to use the common components. Will look into it.

**Comment by craxal** [comment]
@v-kellyluo Can you please include the query you used?

**Comment by v-kellyluo** [comment]
@craxal , The query is `PartitionKey eq '1'`.
![Image](https://github.com/user-attachments/assets/ed8219bb-0971-4620-bc1e-0aaef45ee825)

**Comment by craxal** [comment]
I found the problem. We weren't actually applying the working query when running the query. Should be fixed soon.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20241115.2. Fixed. So we're going to close it.
![Image](https://github.com/user-attachments/assets/18e363be-e71c-47b8-be6b-5781683638a0)
