### ISSUE TITLE
I cancelled a share copy operation and now I cant see any shares..

### ISSUE THREAD

**Issue by K9isK9** [microsoft/AzureStorageExplorer#8292]
### Preflight Checklist

- [x] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [x] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [x] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.23.2

### Architecture

i86

### Platform

Windows

### Bug Description

Unable to retrieve child resources

ProducerError:{
  "name": "Node Fetch Error",
  "message": "getaddrinfo ENOTFOUND devescap001.file.core.windows.net",
  "stack": "Error: getaddrinfo ENOTFOUND devescap001.file.core.windows.net\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)",
  "cause": {},
  "code": "ENOTFOUND",
  "errno": -3008
}

### Steps to Reproduce

I cancelled a share copy operation and now I cant see any shares..

### Actual Experience

I cancelled a share copy operation and now I cant see any shares..

**Comment by craxal** [comment]
@K9isK9 You're using a very old version of Storage Explorer. Please update to the latest x64 version of Storage Explorer ([1.36.2](https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.36.2) as of today). Let us know if you continue to have issues.

**Comment by K9isK9** [comment]
Hi, I tried almost all the versions starting from 36.2 to go down to 32.1
but unfortunately the same erros perceived.  Seems like some cache files
causing the issue. How can I clear all the cache and start afresh. Please
help. Thanks.

**Comment by craxal** [comment]
@K9isK9 Can you still see your file shares in the Azure Portal? What happens if you sign out and sign back in to Storage Explorer? You can also reset portions of Storage Explorer from **Help > Reset**.

**Comment by K9isK9** [comment]
Hi Craig, The resetting  worked! Thanks so much. I appreciate your kind
support.  Thanks once again. Good bye!

**Comment by craxal** [comment]
@K9isK9 Glad that helped resolve your issue. Let us know if you have any additional issues.
