### ISSUE TITLE
Unable to browse Azure File Shares in ADLS Gen2 account

### ISSUE THREAD

**Issue by engrmaqs** [microsoft/AzureStorageExplorer#8293]
### Preflight Checklist

- [x] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [x] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [x] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.36.2

### Architecture

x64

### Storage Explorer Build Number

20241029.2

### Platform

Windows

### OS Version

Windows Datacentre 2022 Datacenter Azure Edition

### Bug Description

I am unable to browse Azure File Shares on ADLS Gen2 Storage account.
Unable to retrieve child resources

ProducerError:{
  "name": "Node Fetch Error",
  "message": "getaddrinfo ENOTFOUND storageeversholtprod.file.core.windows.net",
  "stack": "Error: getaddrinfo ENOTFOUND storageeversholtprod.file.core.windows.net\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)",
  "cause": {},
  "code": "ENOTFOUND",
  "errno": -3008
}

### Steps to Reproduce

1. Launch Storage Explorer
2. Click on File Shares and I get the error
3. Unable to retrieve child resources

ProducerError:{
  "name": "Node Fetch Error",
  "message": "getaddrinfo ENOTFOUND storageeversholtprod.file.core.windows.net",
  "stack": "Error: getaddrinfo ENOTFOUND storageeversholtprod.file.core.windows.net\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)",
  "cause": {},
  "code": "ENOTFOUND",
  "errno": -3008
}

### Actual Experience

1. Launch Storage Explorer
2. Click on File Shares and I get the error
3. Unable to retrieve child resources

ProducerError:{
  "name": "Node Fetch Error",
  "message": "getaddrinfo ENOTFOUND storageeversholtprod.file.core.windows.net",
  "stack": "Error: getaddrinfo ENOTFOUND storageeversholtprod.file.core.windows.net\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)",
  "cause": {},
  "code": "ENOTFOUND",
  "errno": -3008
}

**Comment by craxal** [comment]
* How are you connecting to the storage account? Sign in? Account name and key? SAS?
* Are you working with any special networking conditions, such as a proxy?
* Can you confirm the file share service is enabled on the account?
* If using sign in or SAS, do you have sufficient permissions to access the file share service and list file shares? If using key, does the storage account allow access using keys.
* If using sign in, have you tried signing out and signing back in?

**Comment by engrmaqs** [comment]
Thanks for contacting.
Our Networks team has managed to resolve the issue.
it was related to a DNS entry missing from the Private DNS Zones within Azure
Adding Storage Account DNS Entry to the Private Link resolved the issue.
