### ISSUE TITLE
The tags for a key-value disappear after opening the edit key-value dialog and saving it without making any changes

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8296]
**Storage Explorer Version**: 1.37.0-dev (103)
**Build Number**: 20241115.2
**Branch**: main
**Platform/OS**: Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.6(Apple M1 Pro)
**Architecture**: arm64/x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand 'App Configurations' node -> Open one app configuration.
2. Add one key-value, then right click it -> Click 'Edit Tags...'.
3. Add one tag to the key-value.
4. Select the key-value -> Click 'Edit'.
5. Without making any changes -> Click 'Save'.
6. Check whether the tag for the key-value shows well.

## Expected Experience ##
The tag for the key-value shows well.
![Image](https://github.com/user-attachments/assets/ac3055a8-dec1-4257-9f63-8bf0cd28e82a)

## Actual Experience ##
The tag for the key-value disappears.
![Image](https://github.com/user-attachments/assets/1acdc970-dba7-4345-83d5-f9fded0a1a72)

**Comment by JasonYeMSFT** [comment]
We should make the edit settings operation preserve the most up to date tags value that the client has received.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20241117.1. Fixed. So, we are going to close it.
