### ISSUE TITLE
'Upload files' should display as 'Upload Files' in 'Upload' dialog

### ISSUE THREAD

**Issue by v-flyuan** [Microsoft/AzureStorageExplorer#83]
**Storage Explorer Version:** 20180425.3(1.0.0)

**OS Version:** Win10/Mac/Linux

**Regression:** Not a regression

**Steps to Reproduce:**

1. Launch Storage Explorer and expand Storage Accounts.
2. Open a file share editor and click 'Upload' ->'Upload Files...' in the toolbar.
3. On the 'Upload files' dialog, verify whether the title is properly or not.

**Expected Experience:**
The title displays as 'Upload **Files**'.

**Actual Experience:**
The title displays as 'Upload **files**'. You can see the screenshot.
![file](https://user-images.githubusercontent.com/12556995/39298537-52c4b316-48fb-11e8-838b-147e55dc0c69.png)

**More Info:**
1. This issue also reproduces for 'Upload Folder' dialog.
![folder](https://user-images.githubusercontent.com/12556995/39298563-623225c2-48fb-11e8-993e-cbff7198979b.png)

**Comment by v-xuanzh** [comment]
Hi @craxal , This issue has been fixed on '**Upload Files to Blob Containers**' dialog.
But it still reproduces on '**Upload Files on File Shares**' dialog. Could you help to take a look?
![upload_files](https://user-images.githubusercontent.com/34729022/49711448-4b0aaa80-fc7a-11e8-9df7-b8868f9fdc55.png)
![upload_folder](https://user-images.githubusercontent.com/34729022/49711449-4b0aaa80-fc7a-11e8-8642-73053e04e9aa.png)

**Comment by v-xuanzh** [comment]
This issue has been fixed on build 20181213.1. Could you help to resolve it?

**Comment by MRayermannMSFT** [comment]
Oh, guess it was then. :)
