### ISSUE TITLE
'Rename' always is disabled for blobs context menu

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#830]
Version: 1.5.0
Platform/OS Version: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
Architecture: ia32/x64
Build Number: 20181101.2
Commit: 022557d3
Regression From: Previous release 1.5.0 (20181026.1)

#### Steps to Reproduce: ####
1. Launch Storage Explorer and expand one storage account.
2. Open one blob container -> Select one blob then check the context menu.

#### Expected Experience: ####
'Rename' is enabled.

#### Actual Experience: ####
'Rename' always is disabled.
![image](https://user-images.githubusercontent.com/41351993/47899940-1b67c600-deb6-11e8-8b83-08e90ff8290f.png)

**Comment by MRayermannMSFT** [comment]
Fix for this has been merged into master.

**Comment by v-xianya** [comment]
Verified on 20181107.1. This issue reproduces, so reopen it.

**Comment by v-xianya** [comment]
Verified on build 20181127.2. This issue doesn't reproduce. Could you help to resolve it?
