### ISSUE TITLE
Cannot delete Files in Blob Storage that's has SFTP enable using Storage explore

### ISSUE THREAD

**Issue by Weasleman** [microsoft/AzureStorageExplorer#8300]
### Preflight Checklist

- [x] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [x] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [x] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.36.2

### Architecture

x64

### Storage Explorer Build Number

202411029.2

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Strange one have Blob SFTP enabled with a Private Endpoint. Can connect to the SFTP services using Azure Storage Explorer and Navigate around upload etc. But cannot delete or create folders. 

The Public IP has the firewall enabled "selected Networks". External SFTP access is enabled and working.
Logging into storage explore using my azure credentials with the assigned the roles of "Storage Blob Data Contributor" and "Reader and Data Access". 

PE is working as I can navigate to the blob storage and navigate internally. I can upload to the SFTP blob. Just cannot delete any files.

Deletion of 'test.txt' from 'files/' failed: 0 completed, 1 failed (used name and key)

Stranger still if I enable All networks on the Public network access. I can delete files. May not be a bug but for the life of me I cannot understand this behaviour.

 Was working but has stopped working. 

### Steps to Reproduce

1. Open storage Explore
2. Navigate to the container
3. go to blob container
4. Navigate to files 
5. Upload a file 
6. try to delete 

### Actual Experience

2024/11/15 17:31:23 AzcopyVersion  10.26.0
2024/11/15 17:31:23 OS-Environment  windows
2024/11/15 17:31:23 OS-Architecture  amd64
2024/11/15 17:31:23 Log times are in UTC. Local time is 15 Nov 2024 17:31:23
2024/11/15 17:31:25 ISO 8601 START TIME: to copy files that changed before or after this job started, use the parameter --include-before=2024-11-15T17:31:18Z or --include-after=2024-11-15T17:31:18Z
2024/11/15 17:31:25 Authenticating to destination using SharedKey
2024/11/15 17:31:25 Authenticating to source using SharedKey
2024/11/15 17:31:25 Job-Command remove https://xxxxxxxxx.dfs.core.windows.net/files/scotttest.txt --output-type=json --cancel-from-stdin --from-to=BlobFSTrash --recursive --log-level=INFO 
2024/11/15 17:31:25 Number of CPUs: 4
2024/11/15 17:31:25 Max file buffer RAM 2.000 GB
2024/11/15 17:31:25 Max concurrent network operations:  will be dynamically tuned up to 3000 (Based on auto-tuning limit. Set AZCOPY_CONCURRENCY_VALUE environment variable to override)
2024/11/15 17:31:25 Check CPU usage when dynamically tuning concurrency: true (Based on hard-coded default. Set AZCOPY_TUNE_TO_CPU environment variable to true or false override)
2024/11/15 17:31:25 Max concurrent transfer initiation routines: 64 (Based on hard-coded default. Set AZCOPY_CONCURRENT_FILES environment variable to override)
2024/11/15 17:31:25 Max enumeration routines: 16 (Based on hard-coded default. Set AZCOPY_CONCURRENT_SCAN environment variable to override)
2024/11/15 17:31:25 Parallelize getting file properties (file.Stat): false (Based on AZCOPY_PARALLEL_STAT_FILES environment variable)
2024/11/15 17:31:25 Max open files when downloading: 2147479959 (auto-computed)
2024/11/15 17:31:25 Trying 4 concurrent connections (initial starting point)
2024/11/15 17:31:25 Final job part has been created
2024/11/15 17:31:25 Final job part has been scheduled
2024/11/15 17:31:25 WARN: [P#0-T#0] Displayed file count will be either 1 or based upon list-of-files entries, and thus inaccurate, as deletes are performed recursively service-side.
2024/11/15 17:31:25 ==> REQUEST/RESPONSE (Try=1/27.8396ms, OpTime=253.4649ms) -- RESPONSE SUCCESSFULLY RECEIVED
   HEAD https://xxxxxxxxxxxxx.blob.core.windows.net/files/scotttest.txt
   X-Ms-Request-Id: [1c710355-f01e-0036-5684-37566d000000]

2024/11/15 17:31:26 ==> REQUEST/RESPONSE (Try=1/95.2093ms, OpTime=195.2235ms) -- RESPONSE STATUS CODE ERROR
   DELETE https://xxxxxxx.dfs.core.windows.net/files/scotttest.txt?recursive=false
   Accept: application/json
   Authorization: REDACTED
   User-Agent: Microsoft/Azure/Storage/ azsdk-go-azdatalake/v1.2.0 (go1.22.5; Windows_NT)
   X-Ms-Client-Request-Id: ed1d2b8e-4a60-4df4-5688-7879ac2dd8ab
   X-Ms-Date: Fri, 15 Nov 2024 17:31:25 GMT
   x-ms-version: 2023-08-03
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation.
   Content-Length: 194
   Content-Type: application/json;charset=utf-8
   Date: Fri, 15 Nov 2024 17:31:32 GMT
   Server: Windows-Azure-HDFS/1.0 Microsoft-HTTPAPI/2.0
   X-Ms-Client-Request-Id: ed1d2b8e-4a60-4df4-5688-7879ac2dd8ab
   X-Ms-Error-Code: AuthorizationFailure
   X-Ms-Request-Id: 6ea5241c-801f-0061-0d84-37f85e000000
   X-Ms-Version: 2023-08-03
Response Details: {"error":{"code":"AuthorizationFailure","message":"This request is not authorized to perform this operation.\nRequestId:6ea5241c-801f-0061-0d84-37f85e000000\nTime:2024-11-15T17:31:32.7577840Z"}}

2024/11/15 17:31:26 ERR: [P#0-T#0] Authentication Failed. The SAS is not correct or expired or does not have the correct permission DELETE https://xxxxxxxxxxxxx.dfs.core.windows.net/files/scotttest.txt
--------------------------------------------------------------------------------
RESPONSE 403: 403 This request is not authorized to perform this operation.
ERROR CODE: AuthorizationFailure
--------------------------------------------------------------------------------
{
  "error": {
    "code": "AuthorizationFailure",
    "message": "This request is not authorized to perform this operation.\nRequestId:6ea5241c-801f-0061-0d84-37f85e000000\nTime:2024-11-15T17:31:32.7577840Z"
  }
}

### Expected Experience

Able to delete files and create folders.

**Comment by JasonYeMSFT** [comment]
> It seems that when you delete a file it goes to dfs.core.windows.net not to blob.core.windows.net

This is correct. For ADLS Gen2 storage resources, we use dfs endpoint for delete because otherwise it would be hard to deal with directories since there is no native support for real directories in the non-dfs blob realm.
