### ISSUE TITLE
Fail to add a message for one queue

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8308]
**Storage Explorer Version**: 1.37.0-dev (103)
**Build Number**: 20241119.13
**Branch**: main
**Platform/OS**: Windows11/Windows11/Linux Ubuntu 22.04/MacOS Sequoia 15.1(Apple M1 Pro)
**Architecture**: x64/arm64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.36.2)

## Steps to Reproduce ##
1. Expand one storage account -> Queues.
2. Create a queue -> Click 'Add' -> Click 'OK'.
3. Check whether succeeds to add the message.

## Expected Experience ##
Succeed to add the message.
![Image](https://github.com/user-attachments/assets/26c8fb47-10d5-45ec-99f8-b76814b381ea)

## Actual Experience ##
Fail to add the message.
![Image](https://github.com/user-attachments/assets/a0f480e7-2891-4734-af4f-9f7668848385)

`Error details:`
{
  "name": "RestError",
  "message": "Value for one of the query parameters specified in the request URI is invalid.\nRequestId:98db051b-8003-0019-7c17-3b9270000000\nTime:2024-11-20T06:41:11.9426923Z",

**Comment by craxal** [comment]
Oops. The `timeToLive` and `visibilityTimeout` values weren't being returned by the dialog.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20241122.6. Fixed.
![Image](https://github.com/user-attachments/assets/7c6acbfc-8fd2-4eac-95dc-61150c43f4af)
