### ISSUE TITLE
Fail to dequeue the first message in one queue

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8309]
**Storage Explorer Version**: 1.37.0-dev (103)
**Build Number**: 20241119.13
**Branch**: main
**Platform/OS**: Windows11/Windows11/Linux Ubuntu 22.04/MacOS Sequoia 15.1(Apple M1 Pro)
**Architecture**: x64/arm64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.36.2)

## Steps to Reproduce ##
1. Expand one storage account -> Queues.
2. Open a queue that contains at least one message.
3. Click 'Dequeue' -> Click 'Yes' on the confirmation dialog.
4. Check whether succeeds to dequeue the first message.

## Expected Experience ##
Succeed to dequeue the first message.
![Image](https://github.com/user-attachments/assets/f7ab3fe5-a0a5-49c1-8896-bb7d72161900)

## Actual Experience ##
Fail to dequeue the first message.
![Image](https://github.com/user-attachments/assets/63ea8704-3e87-4f13-94bc-652cb00d052d)

**Comment by craxal** [comment]
Oops. The problem was the `topMessageId` wasn't being set properly by the async data source.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20241122.6. Fixed.
![Image](https://github.com/user-attachments/assets/04260109-3de9-4c0d-85af-e8b53392bcc7)
