### ISSUE TITLE
The activity log is incorrect when exporting messages for one queue

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#8310]
**Storage Explorer Version:** 1.37.0-dev (103)
**Build Number:** 20241119.13
**Branch:** main
**Platform/OS:** Windows10/Windows11/Linux Ubuntu 22.04/MacOS Sequoia 15.1(Apple M1 Pro)
**Architecture:** x64/arm64/x64/arm64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Queues.
2. Create a queue -> Import several messages.
3. Click 'Export' -> Observe the activity log.
4. Check whether the activity log is correct.

## Expected Experience ##
The activity log is correct.

## Actual Experience ##
1. The number of the exported messages is incorrect, it always displays '32'.
2. The exported file name is 'Undefined'.
3. There is no action 'Show in Folder' next to the activity log.
![Image](https://github.com/user-attachments/assets/1ed33da2-1f68-4212-9d42-c117bc113ca4)

**Comment by craxal** [comment]
The number is hardcoded, because we always export _up to_ 32 messages, but maybe we can reword it for clarity.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20241122.6. Fixed.
![Image](https://github.com/user-attachments/assets/2613096d-0822-4152-8946-cbb2184aaf32)

**Comment by craxal** [comment]
@v-xianya That would be a separate feature request, but I can consider that here.
