### ISSUE TITLE
The column header is focused instead of the 'Select All' button after clicking 'Select All' for tables and queues

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8311]
**Storage Explorer Version**: 1.37.0-dev (103)
**Build Number**: 20241119.13
**Branch**: main
**Platform/OS**: Windows11/Windows11/Linux Ubuntu 22.04/MacOS Sequoia 15.1(Apple M1 Pro)
**Architecture**: x64/arm64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.36.2)

## Steps to Reproduce ##
1. Expand one storage account -> Queues.
2. Create a queue -> Click 'Select All'.
3. Check whether the 'Select All' button is focused.

## Expected Experience ##
The 'Select All' button is focused.
![Image](https://github.com/user-attachments/assets/193a0383-c3f7-4349-b2aa-bad7ce5ddc15)

## Actual Experience ##
The column header is focused.
![Image](https://github.com/user-attachments/assets/9a698145-171a-43e8-b64b-d27cd0a3ac8c)

## Additional Context ##
1. This issue also reproduces for tables.
2. This issue doesn't reproduce for blob containers/ADLS Gen2 blob containers/file shares.

**Comment by craxal** [comment]
I think this is intentional. There's an explicit line of code in the shared component that moves focus to the data grid, and both tables and queues are using the shared component. The other explorers will eventually have this same behavior once refactored to use the shared components.

**Comment by v-xianya** [comment]
@craxal Thank you for the updates! We opened this bug refer to [8044](https://github.com/microsoft/AzureStorageExplorer/issues/8044).

**Comment by craxal** [comment]
Ah, yes. I had a feeling we discussed that earlier. I will take a look. I agree with the earlier decision.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20241206.2. Fixed.
![Image](https://github.com/user-attachments/assets/c238bf67-6ff1-4c54-9d89-d9a0f604a193)
