### ISSUE TITLE
The position of the scrollbar is not in 'Message Text' section for the 'Import Messages' dialog

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#8314]
**Storage Explorer Version:** 1.37.0-dev (103)
**Build Number:** 20241119.13
**Branch:** main
**Platform/OS:** Windows10/Windows11/Linux Ubuntu 22.04/MacOS Sequoia 15.1(Apple M1 Pro)
**Architecture:** x64/arm64/x64/arm64
**How Found:** From running test cases
**Regression From:** Previous release (1.36.2)

## Steps to Reproduce ##

1. Expand one storage account -> Queues.
2. Create a queue -> Click 'Import'.
3. Click 'Import file' field -> Select a csv file which has more than 10 rows -> Click 'Open'.
4. There is a scrollbar in the 'Import Messages' dialog.
5. Check whether the position of the scrollbar is in 'Message Text' section.

## Expected Experience ##
The position of the scrollbar is in 'Message Text' section.
![Image](https://github.com/user-attachments/assets/95f69dc9-3f37-4d6d-b4bb-2e8b7f6b3a62)

## Actual Experience ##
1. The position of the scrollbar is not in 'Message Text' section.
2. The 'Store as' option can't show completely.
![Image](https://github.com/user-attachments/assets/98b94608-a997-4b0f-af51-a79797d75823)

**Comment by v-xianya** [comment]
Verified this issue on the main build 20241122.6. Fixed.
![Image](https://github.com/user-attachments/assets/061b6eb2-d6b6-4a57-af89-b45a7f01134d)
