### ISSUE TITLE
The 'Close' button is selected by default in the 'View Message' dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8315]
**Storage Explorer Version**: 1.37.0-dev (103)
**Build Number**: 20241119.13
**Branch**: main
**Platform/OS**: Windows11/Windows11/Linux Ubuntu 22.04/MacOS Sequoia 15.1(Apple M1 Pro)
**Architecture**: x64/arm64/x64/arm64
**How Found**: Exploratory testing
**Regression From**: Previous release (1.36.2)

## Steps to Reproduce ##
1. Expand one storage account -> Queues.
2. Open one queue that contains at least one message.
3. Select one message then click 'View'.
4. Check whether the 'Close' button in the dialog is not selected.

## Expected Experience ##
The 'Close' button on the dialog is not selected.
![Image](https://github.com/user-attachments/assets/f2c4a376-9875-4494-af21-aa58d6ef3483)

## Actual Experience ##
The 'Close' button on the dialog is selected.
![Image](https://github.com/user-attachments/assets/2f0cd95f-e0bd-46d4-84e5-b60ef253c896)

**Comment by craxal** [comment]
Subtle difference, doesn't interfere with anything, so won't fix.
