### ISSUE TITLE
Add possibility to Filter resources by Resource Group

### ISSUE THREAD

**Issue by e-antoni** [microsoft/AzureStorageExplorer#8316]
### Preflight Checklist

- [x] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [x] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [x] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Unable to filter Subscription resouces by Resource Group

### Desired Solution

I'd like to see a sub menu item on the subscription to select Resource Group/s to limit the amount of resources i see.  Working in large organization with hundreds of storage accounts make it difficult to see the ones i work with.

### Alternatives and Workarounds

Alternatively i've used Quick Access to set the storage accounts i am working with.

**Comment by MRayermannMSFT** [comment]
Please be aware that there is a setting to group resources by resource group in the tree view:

![Image](https://github.com/user-attachments/assets/91da9830-057b-481c-8040-7b909fe173fd)

Let us know if this is sufficient for your needs.

**Comment by e-antoni** [comment]
Hi @MRayermannMSFT, thanks for pointing out this feature, but unfortunately i just then replace this issue with a high number of resource groups that the organization has. 

Good thing about your suggestion is that I can then pin the Resource Group or more in the Quick Access.
