### ISSUE TITLE
Installer for Azure Storage Explorer 1.36.2 requires .NET 8, even with .NET 9 SDK installed

### ISSUE THREAD

**Issue by tiagofilipesilva** [microsoft/AzureStorageExplorer#8317]
**Bug Description:**

When attempting to install Azure Storage Explorer version 1.36.2, the installer complains that .NET 8 is required.
However, I have the .NET 9 SDK installed, and I believe the installer should recognize and use .NET 9 instead of requiring .NET 8.

**Steps to Reproduce:**
1. Download Azure Storage Explorer version 1.36.2 from the official website.
2. Launch the installer for the application.
3. The installer prompts that .NET 8 is required, even though .NET 9 SDK is already installed.

**Expected Behavior:**

The installer should recognize the installed .NET 9 SDK and proceed with the installation without requiring to install .NET 8.

![Image](https://github.com/user-attachments/assets/35035fcc-92f3-4f79-930a-acd9cc2c691d)

**Comment by craxal** [comment]
@tiagofilipesilva .NET 9 is not a long-term support release, and there may be subtle dependencies Storage Explorer components have on .NET 8. Does installing .NET 8 resolve your issue?

**Comment by tiagofilipesilva** [comment]
@craxal  Thank you for your reply.

Yes, installing .NET 8 should resolve the immediate issue, but that isn't the core concern here.

Unless Azure Storage Explorer is using APIs that are incompatible with .NET 9, as outlined in [the official .NET 9 compatibility documentation](https://learn.microsoft.com/en-us/dotnet/core/compatibility/9.0), the installer should recognize the availability of the .NET 9 SDK and proceed without requesting the installation of the .NET 8 runtime.

The source code for Azure Storage Explorer remains unavailable, despite [a request for it back in 2018](https://github.com/microsoft/AzureStorageExplorer/issues/138). The absence of a detailed software supply chain or a clear software/API bill of materials makes it difficult to understand what dependencies are included or required. As a result, we are forced to rely on (1) installation prompts and (2) [past release notes](https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.34.0) to determine these dependencies.

Therefore, the issue isn't simply about installing the .NET 8 runtime. It's about ensuring that the installer correctly handles compatible .NET versions without unnecessarily requiring additional installs. It also highlights the need for greater transparency regarding the Azure Storage Explorer's dependencies/code.

**Comment by craxal** [comment]
On examination, it looks we are explicitly checking for major versions of .NET 8. We can relax that to include any major versions greater than 8.

**Comment by MRayermannMSFT** [comment]
Changes have been made to the installer for allowing install ontop of .NET 9. In the future, we'll be more proactive on testing new .NET versions. Changes will ship in 1.37.

**Comment by MRayermannMSFT** [comment]
@tiagofilipesilva if you'd like to help us make sure our fix for this issue is sufficient, we have a preview release of 1.37.0 that you can find here: https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.37.0-preview.1

If you have time, please download & install this preview release, and try to reproduce this issue. You can then let us know here whether or not you were still able to reproduce. If you were able to reproduce, please share any information (error messages, screenshots, etc.) that may help us understand why our fix was not successful.

After you are done with this, we recommend you return back to Storage Explorer 1.36, which you can find here: https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.36.2 .

Thank you in advance for finding the time for this!

**Comment by MRayermannMSFT** [comment]
The preview release has been un-published. You can now use 1.37.0: https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.37.0

Please open a new issue if this continues to reproduce in 1.37.0.
