### ISSUE TITLE
AuthorizationFailure by Colin

### ISSUE THREAD

**Issue by xjcyp** [microsoft/AzureStorageExplorer#8319]
This request is not authorized to perform this operation.

This storage account's 'Firewalls & virtual networks' settings may be blocking access to storage services. Try adding your client IP address to the firewall exceptions, or by allowing access from 'all networks' instead of 'selected networks'. To learn more about Azure Storage firewalls and virtual networks, visit http://go.microsoft.com/fwlink/?LinkId=845443.

Error Details:
{
  "name": "RestError",
  "code": "AuthorizationFailure",
  "statusCode": 403,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://sa01cnprd33185.blob.core.chinacloudapi.cn/?comp=list&include=metadata",
    "method": "GET",
    "headers": {
      "_headersMap": {
        "x-ms-version": {
          "name": "x-ms-version",
          "value": "2023-01-03"
        },
        "accept": {
          "name": "Accept",
          "value": "application/xml"
        },
        "user-agent": {
          "name": "User-Agent",
          "value": "Microsoft Azure Storage Explorer/1.36.2 (win32) azsdk-js-storageblob/12.15.0 (NODE-VERSION v20.16.0; Windows_NT 10.0.19045)"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "1a6268cf-3999-4d70-b1fa-d7d3a11403c4"
        },
        "x-ms-date": {
          "name": "x-ms-date",
          "value": "Thu, 21 Nov 2024 00:43:27 GMT"
        },
        "authorization": {
          "name": "Authorization",
          "value": "SharedKey Redacted"
        }
      }
    },
    "withCredentials": false,
    "timeout": 0,
    "keepAlive": true,
    "decompressResponse": false,
    "requestId": "1a6268cf-3999-4d70-b1fa-d7d3a11403c4"
  },
  "response": {
    "request": {
      "streamResponseStatusCodes": {},
      "url": "https://sa01cnprd33185.blob.core.chinacloudapi.cn/?comp=list&include=metadata",
      "method": "GET",
      "headers": {
        "_headersMap": {
          "x-ms-version": {
            "name": "x-ms-version",
            "value": "2023-01-03"
          },
          "accept": {
            "name": "Accept",
            "value": "application/xml"
          },
          "user-agent": {
            "name": "User-Agent",
            "value": "Microsoft Azure Storage Explorer/1.36.2 (win32) azsdk-js-storageblob/12.15.0 (NODE-VERSION v20.16.0; Windows_NT 10.0.19045)"
          },
          "x-ms-client-request-id": {
            "name": "x-ms-client-request-id",
            "value": "1a6268cf-3999-4d70-b1fa-d7d3a11403c4"
          },
          "x-ms-date": {
            "name": "x-ms-date",
            "value": "Thu, 21 Nov 2024 00:43:27 GMT"
          },
          "authorization": {
            "name": "Authorization",
            "value": "SharedKey sa01cnprd33185:KBi3r8pMxwUs27e0FQks4IcDhdg/be0mlJDMIInw7Bg="
          }
        }
      },
      "withCredentials": false,
      "timeout": 0,
      "keepAlive": true,
      "decompressResponse": false,
      "requestId": "1a6268cf-3999-4d70-b1fa-d7d3a11403c4"
    },
    "status": 403,
    "headers": {
      "_headersMap": {
        "connection": {
          "name": "connection",
          "value": "keep-alive"
        },
        "content-length": {
          "name": "content-length",
          "value": "246"
        },
        "content-type": {
          "name": "content-type",
          "value": "application/xml"
        },
        "date": {
          "name": "date",
          "value": "Thu, 21 Nov 2024 00:43:27 GMT"
        },
        "server": {
          "name": "server",
          "value": "Microsoft-HTTPAPI/2.0"
        },
        "via": {
          "name": "via",
          "value": "HTTP/1.1 m_proxy_hkg"
        },
        "x-ms-client-request-id": {
          "name": "x-ms-client-request-id",
          "value": "1a6268cf-3999-4d70-b1fa-d7d3a11403c4"
        },
        "x-ms-error-code": {
          "name": "x-ms-error-code",
          "value": "AuthorizationFailure"
        },
        "x-ms-request-id": {
          "name": "x-ms-request-id",
          "value": "453333b8-801e-0010-39ae-3b8bae000000"
        }
      }
    },
    "bodyAsText": "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.\nRequestId:453333b8-801e-0010-39ae-3b8bae000000\nTime:2024-11-21T00:43:27.7531018Z</Message></Error>",
    "parsedBody": {
      "message": "This request is not authorized to perform this operation.\nRequestId:453333b8-801e-0010-39ae-3b8bae000000\nTime:2024-11-21T00:43:27.7531018Z",
      "code": "AuthorizationFailure"
    },
    "parsedHeaders": {
      "errorCode": "AuthorizationFailure",
      "connection": "keep-alive",
      "content-length": "246",
      "content-type": "application/xml",
      "date": "Thu, 21 Nov 2024 00:43:27 GMT",
      "server": "Microsoft-HTTPAPI/2.0",
      "via": "HTTP/1.1 m_proxy_hkg",
      "x-ms-client-request-id": "1a6268cf-3999-4d70-b1fa-d7d3a11403c4",
      "x-ms-request-id": "453333b8-801e-0010-39ae-3b8bae000000"
    }
  },
  "details": {
    "errorCode": "AuthorizationFailure",
    "connection": "keep-alive",
    "content-length": "246",
    "content-type": "application/xml",
    "date": "Thu, 21 Nov 2024 00:43:27 GMT",
    "server": "Microsoft-HTTPAPI/2.0",
    "via": "HTTP/1.1 m_proxy_hkg",
    "x-ms-client-request-id": "1a6268cf-3999-4d70-b1fa-d7d3a11403c4",
    "x-ms-request-id": "453333b8-801e-0010-39ae-3b8bae000000",
    "message": "This request is not authorized to perform this operation.\nRequestId:453333b8-801e-0010-39ae-3b8bae000000\nTime:2024-11-21T00:43:27.7531018Z",
    "code": "AuthorizationFailure"
  }
}

**Comment by suryasreepada** [comment]
I have the same issue. It was working until 11/20.

**Comment by MRayermannMSFT** [comment]
These are likely due to a change in your local or storage account's network configuration. 

Please refer to documentation here for more help: https://learn.microsoft.com/en-us/azure/storage/common/storage-network-security

If you continue to have problems, we recommend reaching out to Azure support for this type of issue.
