### ISSUE TITLE
First char of file name is deleted with upload.

### ISSUE THREAD

**Issue by irensaltali** [Microsoft/AzureStorageExplorer#832]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Win 10 1703
**Architecture**: ia32
**Regression From**: Yes, I dont know version.

#### Steps to Reproduce: ####
1. Upload block blob to blob container

#### Expected Experience: ####
I'm expecting to upload file with same name in my pc. If there is another with same name I expected to ask what to do.

#### Actual Experience: ####
First char of file will be deleted after upload.

**Comment by MRayermannMSFT** [comment]
What is the name of your file @irensaltali ? Does this repro for every file you upload?

**Comment by irensaltali** [comment]
I can give an example but it happens for every file I upload.

In my pc: 1930552440020521721391500950281680680570450092542.jpg
After upload: 930552440020521721391500950281680680570450092542.jpg

**Comment by MRayermannMSFT** [comment]
Hmmmm so far I'm unable to repro, even with that file name. Can you look in the activity log and see if the two filenames match, e.g.:

![image](https://user-images.githubusercontent.com/21112697/48019359-243fde00-e0e8-11e8-9995-7f129a3b3028.png)

**Comment by irensaltali** [comment]
In activiy log I see the same but when I search by name I can't find file. I find file as first char missing.

**Comment by MRayermannMSFT** [comment]
How long is the full file's path? Can you try uploading with AzCopy (click on Experimental -> Use AzCopy for Blob upload and download")

**Comment by irensaltali** [comment]
I switch back to version 1.4.1 so I can't try it on 1.5.0. Path was C:\Users\isaltali\Desktop\1930552440020521721391500950281680680570450092542.jpg

**Comment by MRayermannMSFT** [comment]
Well my username is the same length as yours, which means if I upload from the desktop I have the same path length as you, but when I do that I still can't repro. I'll go ahead an leave this issue open for a while though incase anyone else is seeing it/can help us narrow down why we aren't.

**Comment by MRayermannMSFT** [comment]
@irensaltali , we just shipped 1.6.0. Can you try with that version? Can you also try with AzCopy enabled. Go to Experimental Features to enable Azcopy.

**Comment by irensaltali** [comment]
I just tried without enabling AzCopy and it worked properly in this version (1.6.0). Thank you.
