### ISSUE TITLE
The message text occasionally appears garbled

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8321]
**Storage Explorer Version**: 1.37.0-dev (103)
**Build Number**: 20241122.6
**Branch**: main
**Platform/OS**: Windows11/Windows11/Linux Ubuntu 22.04/MacOS Sequoia 15.0(Apple M1 Pro)
**Architecture**: x64/arm64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release

## Steps to Reproduce ##
1. Expand one storage account -> Queues.
2. Create a queue -> Click 'Add' -> The 'Add Message' dialog pops up.
3. Type 'test' into message text field and ensure the message is stored as Base64 encoded -> Click 'OK'.
4. Check whether the message text is displayed correctly.

## Expected Experience ##
The message text is displayed correctly
![Image](https://github.com/user-attachments/assets/ec0fac32-09fa-44f3-9e08-4357ca390654)

## Actual Experience ##
The message text is displayed as garbled characters.
![Image](https://github.com/user-attachments/assets/ca8baec7-6066-4e39-b6ff-93b0c7d4f797)

## Additional Context ##
 If a message is stored as 'Base64 encoded', it might be incorrectly decoded as 'plain UTF-8' and vice versa.
Here is the record:
![Image](https://github.com/user-attachments/assets/86d04f3f-fe34-4589-879e-689d276892a3)

**Comment by craxal** [comment]
Encoding wasn't being used to actually encode the text.

**Comment by craxal** [comment]
The correct query was in use for the refresh, but the applied query was not updated on refresh.

**Comment by craxal** [comment]
@v-xianya This issue should be fixed now. Can you please confirm?

**Comment by v-xianya** [comment]
@craxal We encountered an issue while verifying build 20241203.1. When typing a string like 'test' and storing it as UTF-8, the message text appears garbled. Could you please help check this?
![Image](https://github.com/user-attachments/assets/1bc4a930-2c2d-46f7-bd72-a414b8dc894b)

**Comment by craxal** [comment]
@v-xianya This is expected. Some UTF-8 strings are also perfectly valid Base64 strings. Which means there's no way for Storage Explorer to know for certain how such messages were encoded. The encoding is purely a heuristic; they are not a property of the message itself.

**Comment by v-xianya** [comment]
Got it. thank you for the clarification.
