### ISSUE TITLE
There is no action 'Show in Folder' next to the export messages activity log

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#8324]
**Storage Explorer Version:** 1.37.0-dev (103)
**Build Number:** 20241123.6
**Branch:** main
**Platform/OS:** Windows10/Windows11/Linux Ubuntu 22.04/MacOS Sequoia 15.1(Apple M1 Pro)
**Architecture:** x64/arm64/x64/arm64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Queues.
2. Create a queue -> Add a message.
3. Export the message -> Observe the activity log.
4. Check whether there is an action 'Show in Folder' next to the activity log.

## Expected Experience ##
There is an action 'Show in Folder' next to the activity log.
 
## Actual Experience ##
There is no action 'Show in Folder' next to the activity log.
![Image](https://github.com/user-attachments/assets/f1262219-a3f5-4d42-82ae-dffec7fa2f6f)

**Comment by craxal** [comment]
@v-kellyluo Relabeling as a feature request, since export is a new feature.
