### ISSUE TITLE
There is a failed activity log when executing 'Add/Deque/Delete/Requeue' message actions and 'Clear Queue' action for a queue with the 'Auto Refresh on Change' setting unchecked

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8325]
**Storage Explorer Version**: 1.37.0-dev (103)
**Build Number**: 20241123.6
**Branch**: main
**Platform/OS**: Windows11/Windows11/Linux Ubuntu 22.04/MacOS Sequoia 15.0(Apple M1 Pro)
**Architecture**: x64/arm64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.36.2)

## Steps to Reproduce ##
1. Launch storage explorer -> Open settings -> Uncheck the setting 'Auto Refresh on Change'.
2. Expand one storage account -> Queues.
3. Create a queue -> Add one message.
4. Check whether there is a successful activity log.

## Expected Experience ##
There is a successful activity log.
![Image](https://github.com/user-attachments/assets/a2a3dc7a-7bf5-43f4-9e1e-f42433ef5bca)

## Actual Experience ##
There is a failed activity log.
![Image](https://github.com/user-attachments/assets/56afc133-0268-4bcc-aa0e-1468723024b5)

_Error details:_
`{
  "name": "TypeError",
  "message": "Cannot read properties of undefined (reading 'notify')",
  "stack": "TypeError: Cannot read properties of undefined (reading 'notify')\n    at Object.autoRefresh `

## Additional Context ##
1. The newly added message appears after manually refreshing.
2. Display the same error details when executing 'Add', 'Deque', 'Delete', 'Requeue' message actions, and 'Clear Queue' actions.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20241206.2. Fixed.
