### ISSUE TITLE
There is no refresh notification when executing 'Import/Move' message actions for a queue with the 'Auto Refresh on Change' setting unchecked

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8326]
**Storage Explorer Version**: 1.37.0-dev (103)
**Build Number**: 20241123.6
**Branch**: main
**Platform/OS**: Windows11/Windows11/Linux Ubuntu 22.04/MacOS Sequoia 15.0(Apple M1 Pro)
**Architecture**: x64/arm64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.36.2)

## Steps to Reproduce ##
1. Launch storage explorer -> Open settings -> Uncheck the setting 'Auto Refresh on Change'.
2. Expand one storage account -> Queues.
3. Create a queue -> Click 'Import'.
4. Select a csv file then click 'Import'.
5. Check whether there is a refresh notification.

## Expected Experience ##
There is a refresh notification.
![Image](https://github.com/user-attachments/assets/2e435550-7e15-45be-a4dd-145132510392)

## Actual Experience ##
There is no refresh notification.

## Additional Context ##
The imported messages appear after manually refreshing.

**Comment by craxal** [comment]
Oof, that was definitely my bad. I didn't actually update the code that raises the notification.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20241206.2. Fixed.
![Image](https://github.com/user-attachments/assets/96ae8686-10d7-4952-abd9-5e684b80d230)
