### ISSUE TITLE
CosmosDB docs with / in _id do not display

### ISSUE THREAD

**Issue by jeffmcaffer** [microsoft/AzureStorageExplorer#833]
**Storage Explorer Version**: 1.5
**Platform/OS Version**: Windows 10
**Architecture**: ia32
**Regression From**: 

#### Steps to Reproduce: ####
1.  Create a CosmosDB database and collection using Mongo protocol
2. Add a document to the database such that its `_id` property has '/' chars in it (legal AFAICT)
3. use storage explore to find the doc in the collection
4. Select the doc whose `_id` has the '/'s

#### Expected Experience: ####
I expect the content of the selected doc to show up in the text pane of storage explorer

#### Actual Experience: ####
the doc content pane of storage explorer is empty. Note that it appears that the content pane actually just does not update. that is, if you first select a doc where the content shows (e.g., without /s) then select one that has /s, the old content is shown. in the attach image I first selected _id = 589 and the content showed. Then I selected the doc with _id `nuget/nuget/-/jmespath.net` and the doc content did not update. 

I suspect there is a url encoding problem and the explorer is simply crapping out before it can get and update the content.

![image](https://user-images.githubusercontent.com/10070956/47965471-abb02300-dffc-11e8-94da-cfc6433b6416.png)

**Comment by jeffmcaffer** [comment]
Also just discovered that the Delete X operation is not enabled for entries that have /s in the `_id`

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
