### ISSUE TITLE
Cannot sign-in to Azure: default browser doesn't open

### ISSUE THREAD

**Issue by HeiWack** [microsoft/AzureStorageExplorer#8334]
### Preflight Checklist

- [x] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [x] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [x] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.36.2

### Architecture

x64

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Hi,

I recently needed to define a new password for Windows/Azure. A day later when I opened Storage Explorer there was an infinite progress circle. I tried to login to Azure via default browser, but the browser didn't open or no page has been opened. I tried to use the internal login, but nothing happened.

Do you have any hints?

Best regards,

Heiko

### Steps to Reproduce

Launch Storage Explorer after defining a new Windows/Azure password.

### Actual Experience

![Image](https://github.com/user-attachments/assets/2d01b280-1b82-4850-8929-9686a18a5ba1)

**Comment by ezherman** [comment]
I am having the same issue with 1.36.2 on Linux Ubuntu 22.02.

**Comment by MRayermannMSFT** [comment]
@ezherman  and @HeiWack can y'all try:

1. Go to Settings -> Application -> Sign-In -> Sign In with, and choose:
    - If on Windows, and signed into Windows with the same acount you use to access your Azure resources: "Authentication Broker"
    - Otherwise, "Default Web Browser"
1. Go to Help -> Reset, and then choose only Authentication, and click Reset/Ok
1. Restart Storage Explorer
1. Try to sign-in

If sign-in fails, please share any error messages you see, or that are behind any sort of "error details" link.

**Comment by HeiWack** [comment]
Well, I changed the settings to Authentication Broker. I couldn't select the help menu item Reset, because there wasn't any.
![Image](https://github.com/user-attachments/assets/7f29bca8-2261-4ee9-92c2-80a9999ec086)
So I restarted the application. I then needed to choose "Sign-in to Azure". A dialog appeared with the text "Sign-in will be started..." and nothing happened.
![Image](https://github.com/user-attachments/assets/ddd7ab89-e833-4604-a70a-d469d418dec0)
I changed the setting back to "Default Web Browser" and needed to restart the application. After choosing "Sign-in to Azure" a dialog appeared with the information that the browser should be opened and a sign-in page should be redirected to. But nothing happened.
![Image](https://github.com/user-attachments/assets/a0db5677-45b3-4cfd-a726-fa40a0c462ff)

**Comment by MRayermannMSFT** [comment]
Thanks @HeiWack. It seems like something is going wrong with our authentication library on your machine. To figure out what it is, we're going to need to collect some logs from your machine. Please follow the steps here (and please try to do step 3 of deleting the existing logs): https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/blobs/alerts/storage-explorer-troubleshooting?tabs=Windows#authentication-logs

**Comment by craxal** [comment]
@HeiWack Sometimes it can take a few seconds for the menus to initialize. Can you check to see again if the Help > Reset menu is there?

**Comment by HeiWack** [comment]
Thanks that helped. It was an old dotnet version installed on my system, although I've installed a newer one without setting some environment variables. It helped to set these environment variables:

`set DOTNET_ROOT=%USERPROFILE%\dotnet
set PATH=%USERPROFILE%\dotnet;%PATH%
set DOTNET_MULTILEVEL_LOOKUP=0`
