### ISSUE TITLE
The actions 'Copy File Share/Create Snapshot' are enabled for one QA file share directory

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#8337]
**Storage Explorer Version:** 1.37.0-dev (103)
**Build Number:** 20241128.2
**Branch:** main
**Platform/OS:** Windows11/Windows11/Linux Ubuntu 22.04/MacOS Sequoia 15.1(Apple M1 Pro)
**Architecture:** x64/arm64/x64/arm64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> File shares.
2. Create a file share -> Upload a folder.
3. Right click the folder -> Click 'Pin to Quick Access'.
4. Right click the QA folder.
5. Check whether the actions 'Copy File Share/Create Snapshot' are disabled.

## Expected Experience ##
The actions 'Copy File Share/Create Snapshot' are disabled.

## Actual Experience ##
The actions 'Copy File Share/Create Snapshot' are enabled.
![Image](https://github.com/user-attachments/assets/f5e632fc-a304-4f80-a94c-63115ec0e4d4)

## Additional Context ##
There is a failed activity log when clicking 'Copy File Share/Create Snapshot' actions.
![Image](https://github.com/user-attachments/assets/453ac213-7d47-41b4-b4d6-a67f3f087aca)

**Comment by v-xianya** [comment]
Verified this issue on the main build 20241206.2. Fixed. So we are going to close it.
![Image](https://github.com/user-attachments/assets/497b7149-375a-4a4c-91c5-bb2088017fac)
