### ISSUE TITLE
An error dialog pops up when clicking 'Get Shared Access Signature…' action for one QA file share directory

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#8338]
**Storage Explorer Version:** 1.37.0-dev (103)
**Build Number:** 20241128.2
**Branch:** main
**Platform/OS:** Windows11/Windows11/Linux Ubuntu 22.04/MacOS Sequoia 15.1(Apple M1 Pro)
**Architecture:** x64/arm64/x64/arm64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> File shares.
2. Create a file share -> Upload a folder.
3. Right click the folder -> Click 'Pin to Quick Access'.
4. Right click the QA folder -> Click 'Get Shared Access Signature...'.
5. Check whether no error dialog pops up.

## Expected Experience ##
No error dialog pops up.

## Actual Experience ##
An error dialog pops up.
![Image](https://github.com/user-attachments/assets/4ec58fbe-c6cc-4c90-881f-f41e55786f46)

**Comment by v-xianya** [comment]
Verified this issue on the main build 20241206.2. Fixed. So we are going to close it.
![Image](https://github.com/user-attachments/assets/adc9ad0a-c28b-42d6-bf3b-ccf497ab27a5)
