### ISSUE TITLE
There is a failed activity log when clicking 'Manage Stored Access Signature…' action for one QA file share directory

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#8339]
**Storage Explorer Version:** 1.37.0-dev (103)
**Build Number:** 20241128.2
**Branch:** main
**Platform/OS:** Windows11/Windows11/Linux Ubuntu 22.04/MacOS Sequoia 15.1(Apple M1 Pro)
**Architecture:** x64/arm64/x64/arm64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> File shares.
2. Create a file share -> Upload a folder.
3. Right click the folder -> Click 'Pin to Quick Access'.
4. Right click the QA folder -> Click 'Manage Stored Access Signature…'.
5. Check whether 'Access Policies' dialog pops up.

## Expected Experience ##
'Access Policies' dialog pops up.

## Actual Experience ##
There is a failed activity log.
![Image](https://github.com/user-attachments/assets/7f47ec78-303a-4a5c-b089-bae849505c0a)
Error details:
`  "name": "RestError",
  "message": "The requested URI does not represent any resource on the server.\nRequestId:149e5c78-501a-0025-7a64-41bbb7000000\nTime:2024-11-28T07:13:13.3406524Z",`

**Comment by v-xianya** [comment]
Verified this issue on the main build 20241206.2. Fixed. So we are going to close it.
![Image](https://github.com/user-attachments/assets/180f060a-89ce-469c-9506-733b1a707248)
