### ISSUE TITLE
The order of the pasted rows is inconsistent with the sorted rows when pressing 'Ctrl+A' and then sorting rows in the tabular preview tab

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#8340]
**Storage Explorer Version:** 1.37.0-dev (103)
**Build Number:** 20241128.3
**Branch:** main
**Platform/OS:** Windows11/Windows11/Linux Ubuntu 22.04/MacOS Sequoia 15.1(Apple M1 Pro)
**Architecture:** x64/arm64/x64/arm64
**How Found:** Ad-hoc testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload a csv file.
3. Select the file -> Click 'Preview'.
4. Press 'Ctrl+A' in the tabular preview tab.
5. Sort rows by one column -> Right click the rows -> Click 'Copy Rows'.
6. Paste the rows to notepad.
7. Check whether the order of the pasted rows is consistent with the sorted rows.

## Expected Experience ##
The order of the pasted rows is consistent with the sorted rows.

## Actual Experience ##
The order of the pasted rows is inconsistent with the sorted rows.

## Additional Context ##
1. This issue doesn't reproduce if sort rows first and then press 'Ctrl+A'.
2. Here is the record:
![Image](https://github.com/user-attachments/assets/600a850f-1074-4eb5-87b2-8ef97d0f38a9)

**Comment by craxal** [comment]
Very likely related to #8332, since they use the same component.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20241206.2. Fixed.
