### ISSUE TITLE
Failed to access resources for this tenant. You may need to reauthenticate. For more information, refer to the error details.

### ISSUE THREAD

**Issue by Zdeny82** [microsoft/AzureStorageExplorer#8379]
### Preflight Checklist

- [x] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [x] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [x] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.36.2

### Architecture

i86

### Storage Explorer Build Number

October 2024 (Version 1.36.2)

### Platform

All

### Bug Description

{
  "name": null,
  "message": "{\"source\":{\"accountId\":\"00000000-0000-0000-1732-70289d290bbf.9188040d-6c67-4c5b-b112-36a304b66dad:666446FFA39D8AF9E3F8ADB1ACD75DE573935F2F62E51D8AFD6362BDDCA142C3\",\"tenantId\":\"f8cdef31-a31e-4b4a-93e4-5f571e91255a\"},\"resourceId\":\"https://storage.azure.com/\",\"code\":\"AADSTS50020\",\"message\":\"User account '{EUII Hidden}' from identity provider 'live.com' does not exist in tenant 'Microsoft Services' and cannot access the application 'e0001ebd-e920-49b8-a27e-92e573ec0af6'(Storage Explorer) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account. Trace ID: fda6c040-0558-467c-ad49-cb540d6fdf00 Correlation ID: 6f7b3270-e7d8-412c-94bd-c59e88b69553 Timestamp: 2024-12-07 05:00:48Z\"}"
}

### Steps to Reproduce

Launch storage
expand blob container

### Actual Experience

After login, error mesasage appears: "Failed to access resources for this tenant. You may need to reauthenticate. For more information, refer to the error details."

**Comment by craxal** [comment]
@Zdeny82 Your tenant probably doesn't have Storage Explorer registered. We will need to handle that on our end. Can you message me through Teams?

**Comment by craxal** [comment]
@Zdeny82 Other than inform my team, I didn't do a thing. Glad that's resolved. :-)
