### ISSUE TITLE
An error dialog pops up when clicking 'Show in Folder' next to 'Download All' in a non-root directory activity log against file shares

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8385]
**Storage Explorer Version**: 1.37.0-dev (103)
**Build Number**: 20241212.7
**Branch**: main
**Platform/OS**: Windows11/Windows11
**Architecture**: x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.36.2)

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Create a folder -> Upload one file to the folder.
3. Select the file -> Click 'Download -> Download All...'.
4. Select one folder for download.
5. Click 'Show in Folder' next to the download activity log.
6. Check whether the file explorer opens.

## Expected Experience ##
The file explorer opens.

## Actual Experience ##
An error dialog pops up.
![Image](https://github.com/user-attachments/assets/26794a4d-f8ea-42aa-b9eb-6c089a5d876d)

## Additional Context ##
Nothing happens when clicking 'Show in Folder' on Linux Ubuntu 22.04/MacOS Sequoia 15.1(Apple M1 Pro).

**Comment by JasonYeMSFT** [comment]
I merged a fix for this bug.

**Comment by v-xianya** [comment]
Verified this issue on the rel build 20241214.2. Fixed. No error dialog pops up and the directory is highlighted.
So, we are going to close it.
