### ISSUE TITLE
The downloaded item is highlighted after clicking 'Show in Folder' next to the opening single .gzip file activity log

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8386]
**Storage Explorer Version**: 1.37.0-dev (103)
**Build Number**: 20241212.7
**Branch**: main
**Platform/OS**: Windows 11/Windows11/Linux Ubuntu 22.04/MacOS Sequoia 15.1(Apple M1 Pro)
**Architecture**: x64/arm64/x64/arm64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Open Settings -> Enable setting 'Decompress Files'.
2. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one .gzip file (Make sure its ContentEncoding is 'gzip').
3. Download the file -> Click 'Show in Folder' next to the transfer activity log.
5. Check whether the downloaded item is not highlighted.

## Expected Experience ##
The downloaded item is not highlighted.

## Actual Experience ##
The downloaded item is highlighted.

## Additional Context ##
This issue doesn't reproduce for file shares.

**Comment by craxal** [comment]
@JasonYeMSFT Since this is not a regression, if the fix is not trivial, feel free to move to 1.38.0.

**Comment by JasonYeMSFT** [comment]
@v-xianya I cannot reproduce this issue. What are the blob name/size and the downloaded file's name/size? In https://github.com/microsoft/AzureStorageExplorer/issues/8387, I noticed that you might be downloading the non-compressed version of the file. If that's the case, the behavior of this issue is expected.

**Comment by v-xianya** [comment]
Hi @JasonYeMSFT 
`The blob name: `compressed.txt.gzip `size:` 43B
`The download's file's name:`  compressed.txt.gzip `size:`1KB
Here is the record on the build 20241214.2.
![Image](https://github.com/user-attachments/assets/3e086421-dace-4834-b598-8515924dbea6)

**Comment by JasonYeMSFT** [comment]
@v-xianya I understand the behavior better now. This is expected behavior. For "Open" action, we preserve the blob name as is and don't let AzCopy rename it. Since the blob name is preserved, the show in folder action will be able to locate the file and highlight it.
