### ISSUE TITLE
The file is not decompressed in the file explorer after clicking 'Show in Folder' next to the opening .gzip file activity log

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#8387]
**Storage Explorer Version:** 1.37.0-dev (103)
**Build Number:** 20241212.7
**Branch:** main
**Platform/OS:** Linux Ubuntu 22.04/MacOS Sequoia 15.1(Apple M1 Pro)
**Architecture:** x64/arm64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##
1. Open Settings -> Enable setting 'Decompress Files'.
2. Expand one storage account -> Blob Containers.
3. Create a blob container -> Upload a .gzip file.
4. Select the file -> Click 'Open'.
5. Click 'Show in Folder' next to the activity log -> The file explorer opens.
6. Check whether the file is decompressed.
 
## Expected Experience ##
The file is decompressed.
![Image](https://github.com/user-attachments/assets/a7a2a066-4cad-449f-a2b1-6a28663f1812)

## Actual Experience ##
1. There are two files.
2. The file is not decompressed.
![Image](https://github.com/user-attachments/assets/69ffa1f3-7b4a-4098-8ec8-c17e8475d478)

## Additional Context ##
1. This issue doesn't reproduce on Windows.
2. This issue doesn't reproduce for file shares.
3. This issue also reproduces on Linux, and there is only one file.
![Image](https://github.com/user-attachments/assets/360f0a55-dcec-48a9-9a5c-dd2937e0e95a)

**Comment by craxal** [comment]
@JasonYeMSFT Since this is not a regression, if the fix is not trivial, feel free to move to 1.38.0.

**Comment by JasonYeMSFT** [comment]
@v-kellyluo The file I shared with you has 5 bytes in plain text and 43 bytes in gzip compressed form. I have a feeling that you were downloading the uncompressed version of the file. In that case, although the file name has .gzip extension, AzCopy won't decompress it and won't rename it.

**Comment by v-kellyluo** [comment]
Hi @JasonYeMSFT, 

1. On Mac, Open one compressed.txt.gzip blob, there are two files in the file explorer after clicking 'Show in Folder'.
2. The blob name: compressed.txt.gzip size: 43B
3. The downloaded temporary file's name: compressed.txt.gzip. Size: 5KB
4. Here is the screenshot on the build 20241214.2.
![Image](https://github.com/user-attachments/assets/931146c3-f587-4f58-8e43-c31388ab0aaa)

**Comment by JasonYeMSFT** [comment]
@v-kellyluo I understand the behavior now. This is expected behavior. For "Open" action, we preserve the blob name as is and don't let AzCopy rename it. Since the file contains .gzip file extension, mac incorrectly believes this is a compressed bundle and does some weird stuff to it, which is unfortunate but there isn't much we can do at this point. As shown in https://github.com/microsoft/AzureStorageExplorer/issues/8386, on windows, the user may open the file with the correct program if the OS supports it.

**Comment by v-kellyluo** [comment]
@JasonYeMSFT  Thanks for the explanation. 
But this issue doesn't reproduce when opening one compressed.txt.gzip file in one file share, the file is compressed and renamed to compressed.txt, do we need to worry about this?

The screenshot on Windows:
![Image](https://github.com/user-attachments/assets/3d78c8c2-13e9-4e98-9916-f409e2cef6ec)
