### ISSUE TITLE
AzureStorage RestError with status code 400

### ISSUE THREAD

**Issue by graceleeis** [Microsoft/AzureStorageExplorer#8388]
### Preflight Checklist

- [x] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [x] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [x] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.36.2

### Architecture

x64

### Storage Explorer Build Number

20241029.2

### Platform

Windows

### OS Version

Windows 11

### Bug Description

[bug_log.txt](https://github.com/user-attachments/files/18125002/bug_log.txt)

### Steps to Reproduce

1. Launch Azure Storage Explorer
2. Create durable task

### Actual Experience

durable task cannot create due to azureStorage error

**Comment by craxal** [comment]
@graceleeis Can you elaborate on what you're trying to accomplish and the steps you followed? What do you mean by "durable task"? Based on the text file you shared, you are trying to do something with a storage emulator.
