### ISSUE TITLE
Undeleting files in Gen 2 HNS container

### ISSUE THREAD

**Issue by hieuhoang** [microsoft/AzureStorageExplorer#8390]
### Preflight Checklist

- [x] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [x] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [x] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.36.2

### Architecture

i86

### Storage Explorer Build Number

20241029..2

### Platform

Windows

### OS Version

Windows 11

### Bug Description

Undeleting a file within a directory that has been deleted produces the error:
    The destination parent directory was not found
I'm trying to undeleting 1000s of files in hundreds of directories. So I need to create directories manually before deleting each file.

Ideally, the undelete functionality should create the directory required

### Steps to Reproduce

1. Create file in a directory, eg a/b.txt
2. Delete directory a from the command line, rm -r a
3. Undelete b.txt

### Actual Experience

Error:
   The destination parent directory was not found

### Expected Experience

Undelete suceeds

**Comment by craxal** [comment]
@hieuhoang The Azure platform doesn't really let you do that, for essentially two reasons. First, when you soft delete a directory, the items inside it are not technically soft deleted, so you can't undelete them (they don't get delete IDs until they are individually deleted). Second, because the directory has been deleted, if you tried to undelete an item, the parent directory no longer exists, which is why you get the "parent directory was not found" error. You must first undelete the parent directory before you can undelete any items it contains.

**Comment by hieuhoang** [comment]
hmm. So if I wanted to restore a directory with several hundred subdirs I've accidently deleted I would have to pick through it to identify the hierachy and undelete the directories first?! A shame such a useful backend feature is let down by nonsensical app

**Comment by craxal** [comment]
@hieuhoang No, you can restore the directory, and all of its items will become active again. You just can't undelete an item in a deleted parent directory without first undeleting the parent directory.

It sounds like the only thing you need to do is restore to restore the parent directory in order to restore all the other items.

**Comment by craxal** [comment]
@hieuhoang The easiest solution is to undelete `d1`. It is best to delete only the items or directories you don't need.

I'm actually a bit confused by your use of the command line. Are you working with an Azure file share?

**Comment by hieuhoang** [comment]
Undeleting d1 just creates an empty directory, it doesn't undelete anything else.

I think I understand our difference.  
  1. I mount the blob on Linux with blobfuse2 driver. When I delete d1 on Linux, it recursively delete files and subdirs before deleting d1. That's why undeleting d1 just creates an empty d1 and I would have to search and manually undelete each subdir before undeleting the files.
  2. You delete from the Storage Explorer app which executes 1 command to delete d1. Undeleting d1 recurvicely restores all its child files and subdirs as the hierarchical was preserved.
  
So you're correct in what you've said. However, since blobfuse  and HNS and is designed to allow blobs to be used as a filesystem, it would be good to have a way to restore files when they have been deleted on the mounted FS.

**Comment by hieuhoang** [comment]
Ok. I understand your priorities. 

Doubt if the blobfuse team would do anything about this. Directory deletes are always recursive in all is:
   rm -r
  Del /s
Blobfuse won't even know it's deleting the dir until all its children have been deleted. 

Looks like it's some I'm gonna have to write myself

**Comment by hieuhoang** [comment]
Not sure what can be done and who should do it. Hoping to start a discussion about it Being able to undelete a directory and it's subdirectory (like the Recycle Bin on Windows) would be a very useful feature
Roping in @vibhansa-msft from Blobfuse team for advise
(ps. I'm MSFT too)

**Comment by hieuhoang** [comment]
For those who have the same issue (ie. error when recursively restoring a deleted directory in a HNS blob store), I have a script that can do it. Ping me for details
