### ISSUE TITLE
Attached storage accounts will not be expanded automatically if no storage account attachments have been expanded previously

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8391]
**Storage Explorer Version**: 1.37.0-dev (103)
**Build Number**: 20241214.2
**Branch**: rel/1.37.0
**Platform/OS**: Windows 11/Windows11/Linux Ubuntu 22.04/MacOS Sequoia 15.1(Apple M1 Pro)
**Architecture**: x64/arm64/x64/arm64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Select one storage account.
2. Attach the storage account.
3. Check whether the attached storage account is expanded.

## Expected Experience ##
The attached storage account is expanded.

## Actual Experience ##
The attached storage account is not expanded.

## Additional Context ##
1. If you are unable to reproduce this issue, please reload Storage Explorer and try again.
2. Here is the record:
![Image](https://github.com/user-attachments/assets/eb629020-e52c-40d5-be1a-8a08add402d8)

**Comment by craxal** [comment]
@v-xianya I think this is expected behavior. The same is true for subscription nodes. If the number of children for a particular node grows beyond a certain threshold, we don't automatically expand the children.

**Comment by v-xianya** [comment]
Hi @craxal In this case I have only one storage account attached.

If I attach one storage account and expand it manually. Then attach another storage account. The second attached storage account will be expanded automatically.
