### ISSUE TITLE
The split tab is inconsistent with the original one against one QA file directory

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8396]
**Storage Explorer Version**: 1.37.0-dev (103)
**Build Number**: 20241216.3
**Branch**: rel/1.37.0
**Platform/OS**: Windows 11/Windows11/Linux Ubuntu 22.04/MacOS Sequoia 15.2(Apple M1 Pro)
**Architecture**: x64/x64/x64/arm64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Create a folder 'f1' -> Create a subfolder 'f2'.
3. Right click the folder 'f1' -> Click 'Pin to Quick Access'.
4. Open the QA file directory -> Open the folder 'f2'.
5. Split the QA file directory tab.
6. Check whether the split tab keeps consistent with the original one.

## Expected Experience ##
The split tab keeps consistent with the original one.
![Image](https://github.com/user-attachments/assets/547bc678-6840-4078-8980-fe7871c9e342)

## Actual Experience ##
The split tab is inconsistent with the original one.
![Image](https://github.com/user-attachments/assets/936eb30f-ca00-4ad5-bd73-40b643bc5c07)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20241221.4. Fixed. So, we are going to close it.
![Image](https://github.com/user-attachments/assets/c803adf0-df1a-4f5b-9cb4-87bef37b6377)
