### ISSUE TITLE
There is a share snapshot for one QA file directory

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8397]
**Storage Explorer Version**: 1.37.0-dev (103)
**Build Number**: 20241216.3
**Branch**: rel/1.37.0
**Platform/OS**: Windows 11/Windows11/Linux Ubuntu 22.04/MacOS Sequoia 15.2(Apple M1 Pro)
**Architecture**: x64/x64/x64/arm64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share (Do not create snapshots for it) -> Create a folder.
3. Pin the folder to Quick Access -> Open the QA item.
4. Click 'View Share Snapshots'.
5. Check whether there is no share snapshot.

## Expected Experience ##
There is no share snapshot.
![Image](https://github.com/user-attachments/assets/cdadd158-d9ea-45a7-b27f-e2c9cd5e06e6)

## Actual Experience ##
There is a share snapshot.
![Image](https://github.com/user-attachments/assets/d37eef3d-9c8e-452e-9b50-59ca9192773a)

## Additional Context ##
Below error occurs if trying to open the share snapshot.
![Image](https://github.com/user-attachments/assets/2b8ea783-7f08-44ef-bda4-15d4929026e1)

`Error details:`
The specified share does not exist. RequestId:83470656-401a-0004-7ff6-51a715000000 Time:2024-12-19T09:13:45.0628658Z

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20241221.4. Fixed. So, we are going to close it.
![Image](https://github.com/user-attachments/assets/a3c619cc-04a6-448a-ace9-ee1b3679a9fd)
