### ISSUE TITLE
The context menu 'Get Shared Access Signature' should be disabled for one directory

### ISSUE THREAD

**Issue by v-flyuan** [microsoft/AzureStorageExplorer#84]
**Storage Explorer Version:** 20180425.3(1.0.0)

**OS Version:** Win10/Mac/Linux

**Regression:** Not a regression

**Steps to Reproduce:**

1. Launch Storage Explorer and expand Storage Accounts.
2. Open a file share editor which has at least a directory.
3. Right click a directory, verify whether the context menu 'Get Shared Access Signature' is disabled or not.

**Expected Experience:**
The context menu 'Get Shared Access Signature' is disabled.

**Actual Experience:**
The context menu 'Get Shared Access Signature' is enabled
![enabled](https://user-images.githubusercontent.com/12556995/39297822-5c8d72b8-48f9-11e8-8579-3e73f375435d.PNG)
.

**Comment by v-xianya** [comment]
Verified this issue on latest build 20190614.7. This issue still reproduces.

**Comment by JasonYeMSFT** [comment]
Hi, this is supposed to be enabled since there is usage of Shared Access Signature for fileshare directories. See the issue [Invalid SAS for fileshare directory](https://github.com/microsoft/AzureStorageExplorer/issues/1375).
