### ISSUE TITLE
The display name of a Quick Access ADLS Gen2 folder does not include 'ADLS Gen2'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8401]
**Storage Explorer Version**: 1.37.0-dev (103)
**Build Number**: 20241216.3
**Branch**: rel/1.37.0
**Platform/OS**: Windows 11/Windows11/Linux Ubuntu 22.04/MacOS Sequoia 15.2(Apple M1 Pro)
**Architecture**: x64/x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Open one ADLS Gen2 storage account -> Blob Containers.
2. Create a new blob container -> Create a folder.
3. Right click the folder -> Click 'Pin to Quick Access'.
4. Observe the QA item.
5. Check whether the display name includes 'ADLS Gen2'.

## Expected Experience ##
The display name includes 'ADLS Gen2'.

## Actual Experience ##
The display name does not include 'ADLS Gen2'.
![Image](https://github.com/user-attachments/assets/de8a33b3-8f5a-4175-bcd6-c51a61e80dd7)

## Additional Context ##
This issue doesn't reproduce for folders under attached ADLS Gen2 blob container.
 ![Image](https://github.com/user-attachments/assets/97419c17-ba21-470e-abb4-c250de1728af)

**Comment by craxal** [comment]
@richardMSFT I think we should make sure the HNS is included in Quick Access, since we do so that for other statuses:

![Image](https://github.com/user-attachments/assets/b13a8d54-6d18-4978-830c-71865d310c7d)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20241221.4. Fixed. So, we are going to close it.
![Image](https://github.com/user-attachments/assets/2356be0a-8ea7-4673-ba32-bdd9dbd42440)
