### ISSUE TITLE
Update the name of the Release Notes tab to 'Release Notes: 1.37.0'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8403]
**Storage Explorer Version**: 1.37.0-dev (103)
**Build Number**: 20241216.3
**Branch**: rel/1.37.0
**Platform/OS**: Windows 11/Windows11/Linux Ubuntu 22.04/MacOS Sequoia 15.2(Apple M1 Pro)
**Architecture**: x64/x64/x64/arm64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Click 'Help -> Release Notes'.
2. Observe the name of the Release Notes tab.
3. Check whether it shows 'Release Notes:1.37.0'.

## Expected Experience ##
It shows 'Release Notes:1.37.0'.

## Actual Experience ##
It shows 'Release Notes:1.37.0-dev'.

![Image](https://github.com/user-attachments/assets/4879b763-c50b-493d-82c8-e08207384807)

## Additional Context ##
Also need to update the version in 'About' panel
.![Image](https://github.com/user-attachments/assets/32303812-95b8-44d9-91bc-35711d2994bd)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20241221.4. Fixed. So, we are going to close it.
![Image](https://github.com/user-attachments/assets/ee103cb2-7d48-4353-b4fe-f85ffb68380f)
