### ISSUE TITLE
ADLS Gen2: Acquire/Break Lease

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#848]

**Comment by STATCowboy** [comment]
Yes! This is very much needed. Also, need to fix azure cli to allow for break lease with ADLS Gen2 Hierarchal Namespaces!

**Comment by SimRinguet** [comment]
Is there anything new on this? I've got a couple files that I can't manage to un-lease?

**Comment by craxal** [comment]
@SimRinguet How did you establish leases on your blobs? Do you have a workaround?
