### ISSUE TITLE
Feature request: windows explorer like UI experience and batch operations

### ISSUE THREAD

**Issue by EvanCui** [Microsoft/AzureStorageExplorer#850]
Select any node on the left side tree view, please show the sub items in the right side pane. The behavior is quite like the windows explorer.
For example, when I select storage accounts node, it should show all storage accounts as Icons at the right side, and I can batch select them and do something.
When I select Queues node of a storage account, it should show all queues at the right side, and I can batch select the queues to delete or do some other operations.

**Comment by jinglouMSFT** [comment]
Interesting... what kind of batch operations you would like to do if the accounts are displayed on the right hand side?
