### ISSUE TITLE
Query Latest Record on Large Table Return Nothing

### ISSUE THREAD

**Issue by chugene88** [microsoft/AzureStorageExplorer#851]
**Storage Explorer Version**: 1.5
**Platform/OS Version**: Windows 10
**Architecture**: N/A
**Regression From**: Don't Know

#### Issue ####

Not sure if this issue has been reported or now.  I am connect to a classic storage account to query event logs that are written to the WADWindowsEventLogsTable.  I don't know how big the table size is but pretty sure is huge (millions of records).  I tried to query for the most recent records (past 24 hours for example) but it tells me nothing was found... after 10-15 minutes.  I tried the same using a 3rd party tool called Azure Management Studio and that returned data.  

Any recommendations?

Thanks

**Comment by craxal** [comment]
Please provide concise repro steps. Are you using the query builder?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of reponse.
