### ISSUE TITLE
Not able to access azure subscriptions

### ISSUE THREAD

**Issue by sindhek** [Microsoft/AzureStorageExplorer#854]
Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: 535b2d87-664f-415a-b7fa-fd3f1086d450, Error: {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"**.**.***.242","port":443}

**Comment by jinglouMSFT** [comment]
Can you please provide some additional information?  Are you using Storage Explorer?  Which version? How did you try to connect?  Do you have access permission?  Can you access through the Azure Portal? Do you go through a proxy?  The error indicated to me that you may not have access permission.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please comment/reopen if you would still like help!
