### ISSUE TITLE
Upper panel with tabs not visible

### ISSUE THREAD

**Issue by SychevIgor** [microsoft/AzureStorageExplorer#855]
**Storage Explorer Version**: 1.5.0 (build 20181026.3)
**Platform/OS Version**: Linux
**Regression From**: First time installation on this machine

#### Steps to Reproduce: ####
1- Ubuntu 18.10
2- Download storage explorer from here for linux https://azure.microsoft.com/en-us/features/storage-explorer/
3-Extract content from archive and run install.sh 
4- install missing packages as it was recommended here https://superuser.com/questions/1233459/error-running-gitkraken-even-though-dependencies-installed/1255172#1255172
sudo apt install libgnome-keyring-common libgnome-keyring-dev 
to fix the issue
![1](https://user-images.githubusercontent.com/578954/48368507-fa2c8400-e6c4-11e8-80de-0f845a1c732f.png)
5- open a storage explorer 
![screenshot from 2018-11-12 21-39-32](https://user-images.githubusercontent.com/578954/48368564-221be780-e6c5-11e8-871e-85ec33a5ce76.png)

#### Expected Experience: ####
Upper panel should be visible

#### Actual Experience: ####
Upper panel  hidden

**Comment by SychevIgor** [comment]
ignore GIMP opened on a background. first attached image was cut in it.

**Comment by jinglouMSFT** [comment]
Do you have .net core 2.0 on the machine?  Here is a link to the release note that includes a link to install .net core.  https://docs.microsoft.com/en-us/azure/vs-azure-tools-storage-explorer-relnotes
Please let us know if that solves the problem.  Thanks.

**Comment by SychevIgor** [comment]
@jinglouMSFT dotnet --version
2.1.403

**Comment by SychevIgor** [comment]
@jinglouMSFT can I help you troubleshot this issue or fix a documentation?

**Comment by jinglouMSFT** [comment]
yes please do, if you have additional information.

**Comment by craxal** [comment]
@SychevIgor, has this issue been resolved for you?

**Comment by SychevIgor** [comment]
no

**Comment by craxal** [comment]
It looks like the menu bar is colored funny, not the tabs.

**Comment by MRayermannMSFT** [comment]
For anyone tracking this issue, please try upgrading to 1.9.0. We believe this issue has been fixed...if you still see problems please open a new issue.
