### ISSUE TITLE
Export feature, option to not include the @type columns

### ISSUE THREAD

**Issue by mark6543** [Microsoft/AzureStorageExplorer#857]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10
**Architecture**: ia32
**Regression From**: No

#### Steps to Reproduce: ####
1. This is a feature request (and this tool is awesome thank you), it would be great when exporting data that there was an option or setting to not include the @type columns. The reason is when you have large entities in the table and just want to use the data these columns are redundant and difficult to delete in the export file.

**Comment by MRayermannMSFT** [comment]
Hi @mark6543 this feature actually already exists!

![image](https://user-images.githubusercontent.com/21112697/49618292-de876700-f96c-11e8-9704-b335a02a04f2.png)

When you export, you can change the file type to csv, which doesn't type annotations.
