### ISSUE TITLE
The renamed blob container doesn't display

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#859]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181109.1
**Commit**: e721f1fb
**Regression From**: Previous release 1.5.0

#### Steps to Reproduce: ####
1. Expand one storage account.
2. Choose one blob container then rename it.
3. Check the whether the renamed blob container displays or not.

#### Expected Experience: ####
The renamed blob container displays well and the original blob container is disappears.

#### Actual Experience: ####
The renamed blob container doesn't display and the the original blob container is disappears.

**Comment by v-xianya** [comment]
Verified with build 20181204.3. This issue still reproduces.

**Comment by craxal** [comment]
Not able to reproduce with current source code. When I rename a blob container, the tree refreshes, and I have to expand all the nodes again. Not desirable, but when I get back to the blob containers, the new container is there and the old container is gone as expected.

Going to close as not reproducible. If you need to reopen, please provide more info, such as any error messages in the debug (F12) console that show up.

**Comment by v-xuanzh** [comment]
Hi @craxal , one question need to confirm with you.

Have you added the account to Quick Access? Because we don't need to re-expand all the nodes after renaming one blob container.

**Comment by craxal** [comment]
No, I did not add the account to Quick Access. I seem to have inconsistent behavior when in debug mode.
