### ISSUE TITLE
‘Execute Query' button isn't themed in Query document editor under Dark theme

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#86]
**Storage Explorer Version:** 20180425.3(1.0.0)

**OS Version:** Win10/Linux/Mac

**Regression**: Not a regression

**Steps to Reproduce:**

1. Launch Storage Explorer and expand Cosmos DB Accounts.
2. Change the current theme to Dark.
3. Right click one document and select 'Open Query Tab'.
4. Check the ‘Execute Query' button.

**Expected Experience:**
‘Execute Query' button is themed. 

**Actual Experience:**
‘Execute Query' button isn't themed.
![thmee](https://user-images.githubusercontent.com/34729022/39299077-6bdb0710-4937-11e8-8d51-5cb32df4559c.png)

**More info:**
This issue also reproduces on HC-Black theme.

**Comment by MRayermannMSFT** [comment]
Hey @djlan , please triage this bug! Thanks. 😄

**Comment by v-xianya** [comment]
Verified with build 20181220.1. Documents under Cosmos DB Accounts don't support the operation 'Open Query Tab'.

**Comment by v-xuanzh** [comment]
This issue still reproduces on latest master build 20190410.5. So re-opened it.
![image](https://user-images.githubusercontent.com/34729022/55943008-8c946d80-5bfa-11e9-8f8e-7dbd53925cca.png)

**Comment by v-xuanzh** [comment]
**More info:**

The Editor Panel isn't themed under Dark theme.
![image](https://user-images.githubusercontent.com/34729022/57437208-24837800-71f6-11e9-827f-51338477d352.png)


Keep the Query Editor opening, change the current theme to HC-modes directly, this issue doesn't reproduce.
