### ISSUE TITLE
The checked item always is 'Disable Soft Delete' on 'Configure Soft Delete Policy' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#860]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181109.1
**Commit**: e721f1fb
**Regression From**: Previous release 1.5.0

#### Steps to Reproduce: ####
1. Expand one storage account -> Open the 'Configure Soft Delete Policy' dialog(**_The default checked item is 'Disable Soft Delete'_**).
2. Try to change the default soft delete policy to **'Enable Soft Delete'** -> Reopen the 'Configure Soft Delete Policy' dialog then check the result.

#### Expected Experience: ####
The checked item is '**Enabled Soft Delete**' on 'Configure Soft Delete Policy' dialog.

#### Actual Experience: ####
The checked item always is '**Disable Soft Delete'** on 'Configure Soft Delete Policy' dialog.

**Comment by jinglouMSFT** [comment]
also, after the policy is enabled and you go back to the dialog, the dialog still says it's disabled.
![image](https://user-images.githubusercontent.com/10081483/49258270-ae2e4e80-f3e9-11e8-876c-b1c28a972d16.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into hotfix branch
