### ISSUE TITLE
Pop up an error dialog after clicking ‘Save’ button on blob Properties dialog

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#861]
Storage Explorer Version: 1.5.0
Platform/OS Version: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
Architecture: ia32/x64
Build Number: 20181109.1
Commit: e721f1fb
Regression From: Previous 1.5.0 release

#### Steps to Reproduce: ####
1. Expand a non-premium storage account -> Open one blob container which contains one blob at least.
2. Right click a blob and select 'Properties…' -> Open Properties dialog -> Click Save button.

#### Expected Experience: ####
No error pops up.

#### Actual Experience: ####
Pop up an error dialog.
![image](https://user-images.githubusercontent.com/41351993/48405048-82b22f80-e76c-11e8-816f-b5ab66cce620.png)

#### More Info: ####
1. This issue doesn’t reproduce for Premium accounts.
2. Since for Classic accounts can’t retrieve blob containers so this issue doesn't verified for Classic accounts.

**Comment by MRayermannMSFT** [comment]
@v-xianya does this still repro?

**Comment by v-xianya** [comment]
Verified with build 20181206.1. This issue doesn't reproduce. Could you help to resolve it?
