### ISSUE TITLE
Fail to create/delete blob containers

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#862]
Storage Explorer Version: 1.5.0
Platform/OS Version: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
Architecture: ia32/x64
Build Number: 20181109.1
Commit: e721f1fb
Regression From: Not a regression

#### Steps to Reproduce: ####
1. Add permission with the role ‘Storage Blob Data Contributor(preview) + Reader’ under Storage Account level -> Select a member and save.
2. Use the selected member’s account to sign in.
3. Expand one storage account and try to create/delete a blob container.
4. Check whether the blob container can be created/deleted or not.

#### Expected Experience: ####
Succeed to create/delete blob containers.

#### Actual Experience: ####
Fail to create/delete blob containers.

#### More Info: ####
Closing the popped error dialog directly the created blob container shows after refreshing the Blob Containers node.
![image](https://user-images.githubusercontent.com/41351993/48406718-205b2e00-e770-11e8-8c63-97943999c2c5.png)

**Comment by craxal** [comment]
Unable to repro. Possibly fixed recently. Please verify.

**Comment by jinglouMSFT** [comment]
I was able to repro with 20181128.5 yesterday. If you can't repro it with a newer build, let me know where to get that build.  Thx

**Comment by v-xianya** [comment]
Verified on build 20181129.17. This issue doesn't reproduce. Could you help to resolve it ?
