### ISSUE TITLE
Usability: missing features

### ISSUE THREAD

**Issue by andig** [microsoft/AzureStorageExplorer#863]
**Storage Explorer Version**: 1.1.4
**Platform/OS Version**: OSX Mojave
**Architecture**: amd64

I would appreciate the following features that would significantly enhance usability:

- in storage table list view selected keep sort order when running "Refresh"
- in storage table list view add "copy cell" to context menu
- in storage table list view when using "Import" allow blank row keys to be automatically created during import instead of erroring due to missing RowKey

If or interest or helpful I'd be happy to split these into individual issues.

**Comment by craxal** [comment]
* "Copy cell" feature request is tracked by #634.
* "Allow blank keys" feature request is tracked by #6461.
* "Keep sort order after refresh" should be available in our upcoming 1.29.0 release.
