### ISSUE TITLE
Show retrieval headers for CosmosDB records

### ISSUE THREAD

**Issue by RobinHSanner** [microsoft/AzureStorageExplorer#869]
**Storage Explorer Version**: 1.5
**Platform/OS Version**: Windows 10
**Architecture**: ia32

#### Steps to Reproduce: ####
1. View CosmosDB collection records

#### Expected Experience: ####
It would be nice to be able to see the CosmosDB document retrieval headers, for instance the one showing document size, etc.

**Comment by jinglouMSFT** [comment]
CosmosDB has been removed from Storage Explorer.
