### ISSUE TITLE
Clicking 'Restart Now'(Edit -> Target Azure Stack) doesn't restart Storage Explorer after launching it with command

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#87]
**Storage Explorer Version:** 20180425.3(1.0.0)

**OS Version:** Linux

**Regression**: Not a regression

**Steps to Reproduce:**

1. Launch Storage Explorer using command.(Open terminal and go to the path of the Storage Explorer -> Type './StorageExplorer')
2. Navigate to 'Edit' menu -> Select 'Target Azure Stack'.
3. Click 'Restart Now' in the popped notification.

**Expected Experience:**
Storage Explorer is restarted successfully.

**Actual Experience:**
Storage Explorer isn't restarted successfully.

**Comment by MRayermannMSFT** [comment]
I don't think Linux is even supported for connecting to azure stack (we don't even have instructions for how to do it). So won't fix unless a customer complains.
