### ISSUE TITLE
No conflict dialog appears when try to upload an existing blob

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#876]
Storage Explorer Version: 1.5.0
Platform/OS Version: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
Architecture: ia32
Build Number: 20181117.12
Commit: 78a0d1ab
Regression From: Previous release 1.5.0

#### Steps to Reproduce: ####
1. Open one blob container then upload a blob file to it.
2. Upload the same blob file again -> Check whether there shows a conflict dialog or not.

#### Expected Experience: ####
A conflict dialog appears because the blob already exists.

#### Actual Experience: ####
1. No conflict dialog pops up and the blob can be re-uploaded successfully.
2. The existing blob file is overridden directly.

**Comment by jinglouMSFT** [comment]
@v-xuanzh is this for ADLS gen2 or normal blobs?  If ADLS gen2, there is a known bug in AzCopy that the overwrite flag (to false) doesn't work.

**Comment by v-xuanzh** [comment]
It reproduces for normal blobs.

**Comment by v-xianya** [comment]
This issue doesn't reproduce when AzCopy is enabled.

**Comment by jinglouMSFT** [comment]
@v-xianya This is fixed in build 20181129.17 for the normal blobs, although we auto update the editor after the upload finishes, which we have a different bug to track that.
