### ISSUE TITLE
Nothing happens when dragging files to one blob container for ADLS Gen2 accounts

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#878]
Storage Explorer Version: 1.5.0
Platform/OS Version: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
Architecture: ia32
Build Number: 20181117.12
Commit: 78a0d1ab
Regression From: Not a regression

#### Steps to Reproduce: ####
1. Create one account with Azure Data Lake Storage Gen2 enabled.
2. Expand the created account -> Create one blob container.
3. Try to drag files to the current blob container then check the result.

#### Expected Experience: ####
The dragged files can be uploaded successfully.

#### Actual Experience: ####
Nothing happens after dragging files to the blob container.

**Comment by jinglouMSFT** [comment]
This is not supported for this release.  Only upload/download/Rename/Delete will be supported.

**Comment by v-xianya** [comment]
Verified on build 20190515.1. This issue doesn't reproduce. Could you help to resolve it?
