### ISSUE TITLE
Clicking "cancel" on the break lease confirmation dialog releases the leases

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#879]
Storage Explorer Version: 1.5.0
Platform/OS Version: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
Architecture: ia32
Build Number: 20181117.12
Commit: 78a0d1ab
Regression From: Previous release 1.5.0

#### Steps to Reproduce: ####
1. Open one blob container which contains multiple blobs.
2. Acquire lease for all the blobs.
3. Right click all the leased blobs then check the context menu.

#### Expected Experience: ####
'Break Lease' is disabled.

#### Actual Experience: ####
'Break Lease' is enabled.
![break](https://user-images.githubusercontent.com/34729022/48696239-4d01c080-ec1c-11e8-8524-6534e89d2453.png)

**Comment by jinglouMSFT** [comment]
@v-xuanzh Does it actually work if you click to Break Lease?

**Comment by v-xuanzh** [comment]
Actually, It only works well for the first blob when trying to release the lease for multiple blobs.

**Comment by jinglouMSFT** [comment]
@kfasick Actually in our test build for 1.6.0 (20181129.17) multi-select to release lease does work for all selected blobs. However, we only ask for confirmation on the first blob.  Users need to be careful so leases are not unintentionally released.

**Comment by jinglouMSFT** [comment]
@v-xuanzh In build 20181129.17, multi-select to release leases does work for all selected blobs. However, we only ask for confirmation on the first blob.

**Comment by v-xuanzh** [comment]
Hi @jinglouMSFT In fact, clicking 'Cancel' directly on the confirmation dialog will release leases of all the leased items when selecting multiple items

**Comment by MRayermannMSFT** [comment]
@kfasick , I can confirm the next version of stg exp will return multi select lease breakage. Sorry for the nerf! 😄
