### ISSUE TITLE
It doesn’t convert to the right page after clicking the link 'Learn more about default ACLs' on 'Manage Permission' dialog

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#881]
Storage Explorer Version: 1.5.0
Platform/OS Version: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
Architecture: ia32
Build Number: 20181117.12
Commit: 78a0d1ab
Regression From: Not a regression

#### Steps to Reproduce: ####
1. Expand an ADLS Gen2 account -> Create a blob container -> Create a folder.
2. Click 'Manage Permissions' for the folder -> Click the link 'Learn more about default ACLs' on 'Manage Permission' dialog.

#### Expected Experience: ####
It converts to the right page after clicking the link 'Learn more about default ACLs' on 'Manage Permission' dialog.

#### Actual Experience: ####
It doesn’t convert to the right page after clicking the link 'Learn more about default ACLs' on 'Manage Permission' dialog.

**Comment by jinglouMSFT** [comment]
Sercan needs to provide a fwlink to the document.

**Comment by jinglouMSFT** [comment]
Emailed Sercan and Roy.

**Comment by MRayermannMSFT** [comment]
This was fixed!

**Comment by v-xuanzh** [comment]
Hi @MRayermannMSFT, The link 'Learn more about default ACLs' still convert to the unmatched web site using the newer build Hotfix/1.6.1_20181210.2. Could you help to take a look?
![website](https://user-images.githubusercontent.com/34729022/49723629-39d59400-fca2-11e8-900c-b58d91b3857c.png)

**Comment by MRayermannMSFT** [comment]
Yes, I've been trying to get the link owner to change the target URL for a while now.... =/

**Comment by MRayermannMSFT** [comment]
I've messaged Dinsesh
