### ISSUE TITLE
Cannot read property 'connectionString' of undefined Error.

### ISSUE THREAD

**Issue by qwpham** [Microsoft/AzureStorageExplorer#883]
**Storage Explorer Version**: 
**Platform/OS Version**: <MAC version 1.5>
**Architecture**: 
**Regression From**: 

#### Steps to Reproduce: ####
1. Trying to connect to a storage account I get the error message. 
2. "Unable to retrieve child resources. Details: Cannot read property 'connectionString' of undefined"

#### Actual Experience: ####
Nothing shows and the error message appears.

**Comment by jchen86** [comment]
I'm having the same issue as well. I just upgraded to 1.5.0 and I'm unable to connect to any storage account and have been getting the same error.

**Comment by jinglouMSFT** [comment]
@qwpham can you try to clean up your keychain and give it a try?  Here are the steps:
![image](https://user-images.githubusercontent.com/10081483/49263382-2d7a4d00-f3ff-11e8-8214-4c5660b51562.png)

**Comment by tbolon** [comment]
Try also to delete the local data, see [this help](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting#cannot-remove-attached-account-or-storage-resource). It helped me resolve the exact same problem on windows.

**Comment by MRayermannMSFT** [comment]
@tbolon is correct. Those instructions are a way to workaround this issue. There's also a possibility this is due to RBAC preventing us from accessing your resources. That is fixed in 1.6.0, so I'd suggest trying 1.6.0 first, and then clearing the local data.

**Comment by craxal** [comment]
Bug is getting stale, and hasn't been any further discussion, so I will close this issue. Please provide additional information if problem persists.
