### ISSUE TITLE
Provide a visual cue when uploading/downloading files for ADLS Gen2 accounts

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#885]
Storage Explorer Version: 1.5.0
Platform/OS Version: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
Architecture: ia32
Build Number: 20181117.12
Commit: 78a0d1ab
Regression From: Not a regression

#### Steps to Reproduce: ####
1. Expand an ADLS Gen2 accounts -> Create a blob container.
2. Upload files to the blob container.

#### Expected Experience: ####
Provide a visual cue to remind the user that we are using AzCopy when uploading/downloading blobs for ADLS Gen2 accounts.

#### Actual Experience: ####
It doesn’t provide any visual cues when uploading/downloading blobs for ADLS Gen2 accounts.

**Comment by jinglouMSFT** [comment]
We need to design with the PM to determine what we should do here.  In this case, we use AzCopy but the AzCopy check under the Experimental menu is not checked.

**Comment by v-xianya** [comment]
Verified on build 20181129.2. This issue has been fixed. Could you help to resolve it?
