### ISSUE TITLE
Nothing happens when trying to download blobs with AzCopy enabled

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#886]
Storage Explorer Version: 1.5.0
Platform/OS Version: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
Architecture: ia32
Build Number: 20181119.1
Commit: b4d317fd
Regression From: Not a regression

#### Steps to Reproduce: ####
1. Add '**Reader**' and '**Storage Blob Data Reader(Preview)**' roles on storage account scope.
2. Expand this account -> Open one blob container which contains one blob at least -> Make sure the AzCopy feature is enabled.
3. Try to download blobs from the blob container -> Check the result.

#### Expected Experience: ####
The selected blob can be downloaded successfully.

#### Actual Experience: ####
Nothing happens when trying to downloading the blob.
#### More info: ####
This issue still reproduces when uploading blobs to one blob container which has write permission.

**Comment by jinglouMSFT** [comment]
Although AzCopy command line supports RBAC, we haven't built in RBAC support in Storage Explorer using AzCopy yet.  It is a work item in our backlog however.

**Comment by v-xianya** [comment]
Verified this issue on build 20201119.2. Fixed.
