### ISSUE TITLE
Fail to complete the undelete activity when undeleting blobs by date

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#887]
Storage Explorer Version: 1.5.0
Platform/OS Version: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
Architecture: ia32
Build Number: 20181117.12
Commit: 78a0d1ab
Regression From: Previous release 1.5.0

#### Steps to Reproduce: ####
1. Choose one storage account then make sure the soft delete policy is enabled.
2. Open one blob container which contains one blob at least.
3. Try to delete one blob -> Switch to 'Active and deleted blobs' ->Right click the deleted blob then select 'Undelete by Date'.
4. Check the result.

#### Expected Experience: ####
The deleted blob can be undeleted successfully.

#### Actual Experience: ####
Fail to complete the undelete activity.

**Comment by jinglouMSFT** [comment]
Just to clarify, AzCopy is disabled for this test.  Undelete gets stuck at being queued, but never completes and one can't cancel the action either.  The selected date range was within the "deleted time". The task is left orphaned.

**Comment by MRayermannMSFT** [comment]
Fix merged into feature branch
