### ISSUE TITLE
The lock icon doesn't auto present after acquiring lease for one blob

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#889]
Storage Explorer Version: 1.5.0
Platform/OS Version: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
Architecture: ia32
Build Number: 20181119.1
Commit: b4d317fd
Regression From: Not a regression

#### Steps to Reproduce: ####
1. Add '**Reader**' and '**Storage Blob Data Contributor(Preview)**' roles on storage account scope.
2. Expand this account -> Open one blob container which contains one blob at least.
3. Right click one blob then select 'Acquire Lease'.
4. Check whether the lock icon auto shows or not.

#### Expected Experience: ####
The lock icon auto shows after acquiring lease for blobs successfully.

#### Actual Experience: ####
The lock icon doesn't auto present after acquiring lease for blobs.
#### More info: ####
Pop up an error dialog when trying to breaking lease for the leased blob.
![leased](https://user-images.githubusercontent.com/34729022/48757512-f8238000-ecd7-11e8-8eb7-ea96608cd06f.png)

**Comment by jinglouMSFT** [comment]
The rest of the Acquire Lease does do auto refresh. This one should too.
