### ISSUE TITLE
Creating a file share snapshot displays an error after clicking 'Restart Now' in the popped notification(Edit->Target Azure Stack)

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#89]
**Storage Explorer Version:** 20180425.3(1.0.0)

**OS Version:** Win10/Linux/Mac

**Regression**: Not a regression

**Steps to Reproduce:**

1. Launch Storage Explorer.
2. Navigate to 'Edit' menu -> Select 'Target Azure Stack'.
3. Click 'Restart Now' in the popped notification.
4. Create a snapshot for one file share after restarting successfully.

**Expected Experience:**
The snapshot can be created successfully.

**Actual Experience:**
An error occurs and the combo box is cleared.
![error](https://user-images.githubusercontent.com/34729022/39297477-242e5ce0-4933-11e8-88cd-65fae7080eaf.png)

**Comment by MRayermannMSFT** [comment]
File shares are not supported when targeting Azure Stack. Closing as won't fix.
