### ISSUE TITLE
Show an incomplete activity log after copying/renaming blobs 

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#892]
Storage Explorer Version: 1.5.0
Platform/OS Version: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
Architecture: ia32
Build Number: 20181117.12
Commit: 78a0d1ab
Regression From: Previous release 1.5.0

#### Steps to Reproduce: ####
1. Launch storage explorer -> Copy blobs to another blob container.
2. Check the activity log after copying completed.

#### Expected Experience: ####
Show a complete activity log after copying/renaming blobs completed.
![image](https://user-images.githubusercontent.com/41351993/48764420-8c96de00-ecea-11e8-87ad-388d497da760.png)

#### Actual Experience: ####
Show an incomplete activity log after copying/renaming blobs completed.
![image](https://user-images.githubusercontent.com/41351993/48764430-96204600-ecea-11e8-9339-f1a86f8e8135.png)

**Comment by MRayermannMSFT** [comment]
Won't fixing. We prefer the simpler log message for single copy. Good catch though.

**Comment by MRayermannMSFT** [comment]
Won't fixing. We prefer the simpler log message for single copy. Good catch though.
