### ISSUE TITLE
Undelete still on auto fresh and do not prompt for refresh

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#895]
**Storage Explorer Version**: 1.5.0.20181117.12
**Platform/OS Version**: All platforms
**Architecture**: 
**Regression From**: These have not been updated to prompt for refresh

#### Steps to Reproduce: ####
1. Enable soft delete at the blob container level
2. Open the blob container and delete a blob from the RHS
3. Switch to view you can see soft deleted blogs

#### Expected Experience: ####
The expected new behavior: Once the blob is deleted, we should prompt for refresh. Once refreshed, the editor should be updated; the context menu Undelete should be enabled; while Delete should be disabled.

#### Actual Experience: ####
We auto refresh, but the context menu items are not refreshed.  So after Delete, even though the editor is auto refreshed, the context menu still has Delete enabled and Undelete disabled. 

You can observe the same behavior for Undelete.

**Comment by JasonYeMSFT** [comment]
@v-xianya Could you please verify in 1.10 that if undelete works as expected when auto refresh is on/off?

**Comment by v-xianya** [comment]
Hi @JasonYeMSFT 
This issue also reproduces on 1.10.0.

Verified on the release build 20190912.8. Show the **same behaviors** when the auto refresh is on or off:
1. The undeleted blob is auto refreshed.
2. The action Undelete on its context menu is not auto refreshed (the context menu still has Delete enabled and Undelete disabled).

**Comment by JasonYeMSFT** [comment]
The current design is that we remove the dimming and the cross line for the deleted items. We are not going to make auto refresh apply on this command.
