### ISSUE TITLE
Can't add blob metadata through the Blob Properties dialog

### ISSUE THREAD

**Issue by jinglouMSFT** [Microsoft/AzureStorageExplorer#896]
**Storage Explorer Version**: 1.5.0.20181117.12
**Platform/OS Version**: all 
**Architecture**: 
**Regression From**: Regression from 1.5.0 released bits

#### Steps to Reproduce: ####
1. Disable AzCopy experiment. Sign in into Azure storage
2. Open a blob container and select a blog on the RHS. Use the blob context menu to open the blob properties dialog
3. In the Blob Properties dialog, click Add Metedata trying to add a property. 
4. Click Save

Technically you don't even need step 3 to reproduce this bug.

#### Expected Experience: ####
Able to open and close the dialog without any problem. 
Able to open the dialog and add properties then save without any problem.

#### Actual Experience: ####
Error: 
![image](https://user-images.githubusercontent.com/10081483/48808679-80a12100-ecd6-11e8-8445-d67074533651.png)

**Comment by jinglouMSFT** [comment]
This is not using RBAC.

**Comment by v-xuanzh** [comment]
If use RBAC, There shows two results as below. 
1. We can't save the added properties for the selected blob which is uploaded from **Storage Explorer**. This case is same as you mentioned.
2. We can save the added properties for the blob which is uploaded from **Azure Portal**.

You can try to reproduce this issue using the account '**sacontributoracc**' which is assigned "**Storage Account Contributor**" permission.
