### ISSUE TITLE
"Load More" Subscriptions broken

### ISSUE THREAD

**Issue by JakeRadMSFT** [Microsoft/AzureStorageExplorer#9]
Storage Explorer Version: 0.9.6

OS Version: Windows 10 (All)

Steps to Reproduce:

1. Have 20+ Subscriptions
2. Open Storage Explorer

Expected Experience:
Show a group of subscription and allow user to load more.

Actual Experience:
No Load More and not showing all the subscriptions.

**Comment by MRayermannMSFT** [comment]
Fixed on master.
