### ISSUE TITLE
Any other azure explorer program out there?

### ISSUE THREAD

**Issue by RobertK73** [Microsoft/AzureStorageExplorer#903]
This does not allow me to connect to azure. Works fine in web browser connecting to Azure but not this. Tried proxy, but then i get "unable to get local issuer certificate" when trying to copy folder or files. 
Trying to get SSL is not easy and the so called git shit hub claiming to have that program, does not as far as I can see. What's the problem with one file to download and install??

**Comment by jinglouMSFT** [comment]
@RobertK73 It would be more useful if you tell us a bit more information on which version of the storage explorer you were trying to use, on what OS platform and in what network environment?  Were you trying to connect to the global Azure, or any Azure government or Azure Stack?  From the information you've provided above, it looks like you do have a self signed certificate in the certificate chain, which might be cause of the issue you've seen. We have a troubleshooting doc that covers the basic steps to help diagnose self-signed certificate problems that might be helpful to you.  You can find the troubleshooting guide here:  https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?toc=%2fazure%2fstorage%2fqueues%2ftoc.json.  Hope this is helpful.  If you still have issues using Storage Explorer, please reactive the issue and provide us with a little bit more information so we can help diagnose. Thanks.

**Comment by RobertK73** [comment]
Version is 1.5 on Windows 10. Trying to connect to Azure global i guess. 
Works fine when I connect to azure via VS 2015 for example. 
What I cant fathom is why there is not a link directly to the Open SSL program in your linke. Which by the way I have allready visited before my OP.
