### ISSUE TITLE
Fail to rename the blob which name contains spaces

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#904]
Storage Explorer Version: 1.5.0
Platform/OS Version: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
Architecture: ia32
Build Number: 20181127.2
Commit: 71a17300
Regression From: Not a regression

#### Steps to Reproduce: ####
1. Expand one **ADLS Gen2 account** -> **Blob Containers**.
2. Open one blob container -> Upload a blob which name contains spaces.
3. Rename the uploaded blob after uploading successfully.

#### Expected Experience: ####
Succeed to rename the blob.

#### Actual Experience: ####
Unable to rename the blob with the below error.
![rename](https://user-images.githubusercontent.com/34729022/49068434-b2c7fb00-f261-11e8-8138-e78c1d3aed8f.png)
![details](https://user-images.githubusercontent.com/34729022/49069345-03d8ee80-f264-11e8-96d9-79b953543caf.PNG)

#### More info: ####
This issue doesn't reproduce for blobs on RHS.

**Comment by jinglouMSFT** [comment]
Renaming always fails whether the name contains space or no space.

**Comment by jinglouMSFT** [comment]
When HNS is off, renaming works fine.

**Comment by craxal** [comment]
Bug verified. This only occurs when the original name contains spaces. A request header isn't getting encoded when it needs to be by the library, so we can add a small fix in out code.
