### ISSUE TITLE
Fail to upload an empty blob folder for ADLS Gen2 accounts

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#905]
Storage Explorer Version: 1.5.0
Platform/OS Version: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
Architecture: ia32
Build Number: 20181127.2
Commit: 71a17300
Regression From: Not a regression

#### Steps to Reproduce: ####
1. Expand one ADLS Gen2 account -> Blob Containers.
2. Open one blob container -> Upload an empty blob folder to it.
3. Check the result.

#### Expected Experience: ####
The empty folder can be uploaded successfully.

#### Actual Experience: ####
Fail to upload an empty blob folder with the error.
![upload](https://user-images.githubusercontent.com/34729022/49068726-6e892a80-f262-11e8-8e4a-e5a095fc351f.png)

**Comment by jinglouMSFT** [comment]
AzCopy can't seem to upload empty folders even from the command line. This is only for empty folder. 
![image](https://user-images.githubusercontent.com/10081483/49109924-e2b2d680-f240-11e8-9660-98e015369927.png)

**Comment by MRayermannMSFT** [comment]
@v-xuanzh , can you try to repro this on the 20181213.1 build  I just sent y'all? It includes some new azcopy bits, so they may have fixed this bug. Thanks!

**Comment by v-xuanzh** [comment]
This issue still reproduces on the new build 20181213.1 with the same error.

**Comment by MRayermannMSFT** [comment]
@v-xuanzh can you try repro'ing this again? Thanks!

**Comment by v-xuanzh** [comment]
Hi @MRayermannMSFT ,I verified this issue on the latest master build 20190326.6. We cannot upload an empty folder to ADLS Gen2 blob containers with the different error.
![image](https://user-images.githubusercontent.com/34729022/55047494-39b79500-5002-11e9-9ff2-146f6eb64969.png)

**Comment by MRayermannMSFT** [comment]
Yep. That's the error I'd expect y'all to see/that's the one we get from AzCopy. I'll run it by Jing to get his opinion on it, but I consider this fixed. Thanks Xuan.
