### ISSUE TITLE
Unable to expand services nodes for attached accounts with name and key using HTTP

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#906]
Storage Explorer Version: 1.5.0
Platform/OS Version: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
Architecture: ia32
Build Number: 20181127.2
Commit: 71a17300
Regression From: Not a regression

#### Steps to Reproduce: ####
1. Choose one GPV2 account -> Attach it with key and name.
**Key**: raUzzv+OExzxlz0G6h7m4PvpETc3DZhVZicmZF2Zs9RfYHnp7Ggcs3H42PyK2L/qvupsX1K813iI8lyVSWY6Aw==
**Account Name**: lclyan
2. Check "Use HTTP" on 'Connect with Name and Key' dialog when adding the account info -> 'Connect'.
3. Expand 'Local & Attached' -> Storage Accounts -> The attached account -> Blob Containers node.

#### Expected Experience: ####
Blob Containers node expanded well.

#### Actual Experience: ####
Unable to expand the Blob Containers node and pop up an error dialog.
![image](https://user-images.githubusercontent.com/41351993/49068760-82cd2780-f262-11e8-8e7f-02b884b85c7e.png)

**More Info:**
1. This issue reproduces for File Shares/ Queues/Tables node under the same account.
2. This issue reproduces for StorageV1 & Premium & Blob storage account.
3. This issue doesn't reproduce for Classic account.

**Comment by jinglouMSFT** [comment]
The error message is pretty actionable. I don't believe the ARM services support http connections.
