### ISSUE TITLE
Azure Explorer unable to Authenticate 

### ISSUE THREAD

**Issue by vency-pcci** [Microsoft/AzureStorageExplorer#909]
**Storage Explorer Version**: 
**Platform/OS Version**: 
**Architecture**: 
**Regression From**: 

#### Steps to Reproduce: ####
1. 
2. 
Unable to login to  storage account
#### Expected Experience: ####

Subscriptions for the follwowing tenants could not be retrieved:
{"code":"SELF_SIGNED_CERT_IN_CHAIN"}

**Comment by jinglouMSFT** [comment]
This means you have a or multiple self signed certificates.  We normally try to auto-detect them but there are times we can't find them.  you may want to contact your network admin to find the specific self signed certificate(s) and manually add them.

**Comment by MRayermannMSFT** [comment]
Closing as there is nothing we can do for you right now. Let us know if you have additional questions.
