### ISSUE TITLE
Error when downloading VHD from Azure

### ISSUE THREAD

**Issue by nash-dev** [Microsoft/AzureStorageExplorer#911]
{
  "name": "Error",
  "message": "getaddrinfo ENOTFOUND 5700.blob.core.windows.net 5700.blob.core.windows.net:443",
  "stack": "Error: getaddrinfo ENOTFOUND 5700.blob.core.windows.net 5700.blob.core.windows.net:443\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)",
  "code": "ENOTFOUND",
  "errno": "ENOTFOUND",
  "syscall": "getaddrinfo",
  "hostname": "5700.blob.core.windows.net",
  "host": "5700.blob.core.windows.net",
  "port": "443",
  "innerError": {
    "code": "ECONNRESET",
    "errno": "ECONNRESET",
    "syscall": "read"
  }
}

**Comment by jinglouMSFT** [comment]
The error message indicated that we can't find the VHD at the address.  Have you tried to access the VHD from the portal? Also, how did you connect to Azure?  Do you have the appropriate permission to access the file?  Please also provide info on which version of Storage Explorer you are using, on what platform.  Thanks.

**Comment by nash-dev** [comment]
Hi jinglouMSFT, I managed to come right here. Just restarted the download again. Maybe the internet connection dropped. Unsure the reasoning why it didn't work the first time though. Thank you.

**Comment by jinglouMSFT** [comment]
Assuming you are all good now.  Please feel free to contact our support team if you need additional help.  Here is how to get to our support team: https://docs.microsoft.com/en-us/azure/azure-supportability/how-to-create-azure-support-request
Thanks.
