### ISSUE TITLE
Show a confusing log in Activity when trying to open a blob for ADLS Gen2 accounts

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#913]
Storage Explorer Version: 1.5.0
Platform/OS Version: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
Architecture: ia32
Build Number: 20181128.5
Commit: 21f66e3b
Regression From: Not a regression

#### Steps to Reproduce: ####
1. Launch Storage Explorer -> Expand an ADLS Gen2 account which contains at least one blob container.
2. Open the blob container -> Upload a file to it.
3. Try to open the uploaded file -> Check the log in Activity.

#### Expected Experience: ####
Show an exact log in Activity.

#### Actual Experience: ####
Show a confusing log in Activity.
![image](https://user-images.githubusercontent.com/41351993/49142048-e45cc700-f332-11e8-9054-79b2282d60c9.png)

**Comment by jinglouMSFT** [comment]
In December release, we will only support CRUD operations.  Open will not be supported.  We will remove the Open toolbar button as well as the context menu.
