### ISSUE TITLE
There shows a duplicate blob container on the tree view after creating a new HNS container

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#915]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181128.5
**Commit**: 21f66e3b
**Regression From:** Previous build 20181127.2

#### Steps to Reproduce: ####
1. Choose one ADLS Gen2 account.
2. Try to create a new blob container -> Check the tree view.

#### Expected Experience: ####
There only shows one blob container on the tree view.

#### Actual Experience: ####
There shows a duplicate blob container on the tree view.
![duplicate](https://user-images.githubusercontent.com/34729022/49142877-bed0bd00-f334-11e8-9a2e-289828cf33cb.png)

**More info:**
1. It will disappear after refreshing the tree view.
2. This issue doesn't reproduce when 'HNS Enabled = false'.

**Comment by jinglouMSFT** [comment]
This is a regression from the previous build.

**Comment by MRayermannMSFT** [comment]
Fix merged into master
