### ISSUE TITLE
Upload auto refresh but not prompt for refreshing 

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#916]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181128.5
**Commit**: 21f66e3b
**Regression From:** Not a regression

#### Steps to Reproduce: ####
1. Expand one storage account with 'HNS Enabled = false'.
2. Make sure AzCopy is disabled.
3. Open one blob container -> Upload a blob to it -> Check the result.

#### Expected Experience: ####
Prompt for refreshing after uploading successfully.

#### Actual Experience: ####
The uploaded blob auto refreshed.

**Comment by craxal** [comment]
Should be fixed now now that we have a setting. Please verify.
