### ISSUE TITLE
Can't expand Blob container node on LHS when attached using name/key on ADLS Gen 2 account

### ISSUE THREAD

**Issue by jinglouMSFT** [Microsoft/AzureStorageExplorer#918]
**Storage Explorer Version**: 1.5.0.20181128.5
**Architecture**: Windows x32
**Regression From**: No

Repro:
- Go to an ADLS Gen2 account. Copy the primary key (I did this in Storage Explorer)
- Use Name and Key to attach the account.  My account name = jinglouadlsgen2
- Once attached, try to expand the blob container node on LHS

Actual Result:
Unable to retrieve child resources
Details: Container name format is incorrect

Expected:
Should be able to expand the Container node and list the available containers

![image](https://user-images.githubusercontent.com/10081483/49191628-1cacd700-f32c-11e8-9870-7bfe7a5d0eba.png)

**Comment by MRayermannMSFT** [comment]
fix merged into master
