### ISSUE TITLE
Remove Manage Permissions... in context menu when/if ADLS Gen2 account is attached using Name/Key on LHS

### ISSUE THREAD

**Issue by jinglouMSFT** [Microsoft/AzureStorageExplorer#919]
**Storage Explorer Version**: 1.5.0.20181128.5
**Platform/OS**: Windows 10
**Architecture**: x86
**Regression From**: No

Please remove context menu "Manage Permissions..." when/if ADLS Gen2 account was attached using Name/key on LHS.

**Comment by MRayermannMSFT** [comment]
fix merged into master
