### ISSUE TITLE
Blob with path name empty, problem view

### ISSUE THREAD

**Issue by mourabruno** [Microsoft/AzureStorageExplorer#92]
**Storage Explorer Version:**

**OS Version:**

**Steps to Reproduce:**

1. Create a path in blob empty
2. Add files on path
3. Explore the path the files not showed 

**Expected Experience:**

**Actual Experience:**
![image](https://user-images.githubusercontent.com/8479649/39309071-823b9208-493d-11e8-97af-0471b4ad72cf.png)

**Comment by craxal** [comment]
I'm a little unclear on how to reproduce this issue, since Storage Explorer doesn't let you create virtual folders with empty names.

Out of curiosity, does clicking Refresh in the toolbar make the items appear?

**Comment by craxal** [comment]
According to the [Azure documentation](https://github.com/Microsoft/AzureStorageExplorer/issues/92), using consecutive / characters is discouraged.

**Comment by HZass** [comment]
These folders/files are being uploaded under computer backup software which reads files from our central server.  Yes, there are empty directories due to the way that the files are stored and read by the file directory iterator,

**Comment by craxal** [comment]
Closing this bug as stale. If this continues to be an issue, please let us know, and we can reopen.

**Comment by mourabruno** [comment]
Do it


      _storageAccount = CloudStorageAccount.Parse(StorageTableConnection);
      _tableClient = _storageAccount.CreateCloudTableClient();


      _blobClient = _storageAccount.CreateCloudBlobClient();


      var cont = _blobClient.GetContainerReference("testiles");

      if (!cont.Exists())
        throw new ArgumentException($"Container  não existe");


      var blob = cont.GetBlockBlobReference($"/subpath/file.txt");


      await blob.UploadFromFileAsync(@"d:\blacklist.txt");


thanks


Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: Craig <notifications@github.com>
Enviado: Monday, June 25, 2018 3:23:58 PM
Para: Microsoft/AzureStorageExplorer
Cc: mourabruno; Mention
Assunto: Re: [Microsoft/AzureStorageExplorer] Blob with path name empty, problem view (#92)


Closing this bug as stale. If this continues to be an issue, please let us know, and we can reopen.

**Comment by craxal** [comment]
@mourabruno What is your code snippet for?
