### ISSUE TITLE
Prompt for refreshing when pasting an existing blob

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#920]
Storage Explorer Version: 1.5.0
Platform/OS Version: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
Architecture: ia32
Build Number: 20181128.5
Commit: 21f66e3b
Regression From: Not a regression

#### Steps to Reproduce: ####
1. Open anyone blob container then upload a blob to it.
2. Copy the uploaded blob then click 'Paste' on the same blob container editor.

#### Expected Experience: ####
Fail to paste the existing blob and there is no prompting for refreshing.

#### Actual Experience: ####
Fail to paste the existing blob and there prompt for refreshing.
Actually, the prompting pops up again after retrying the failed activities.

**Comment by JakeRadMSFT** [comment]
Out for PR
