### ISSUE TITLE
Can't view folders contents for ADLS Gen2 accounts

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#921]
Storage Explorer Version: 1.5.0
Platform/OS Version: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
Architecture: ia32
Build Number: 20181129.6
Commit: 86486916
Regression From: Not a regression

#### Steps to Reproduce: ####
1. Expand an ADLS Gen2 account -> Create a blob container -> Upload a folder with files.
2. Try to view files in the uploaded folder.

#### Expected Experience: ####
Succeed to view files.

#### Actual Experience: ####
Can't view files.

**Comment by jinglouMSFT** [comment]
This is probably because nothing was uploaded.  I know i have files in the folder to upload.
![image](https://user-images.githubusercontent.com/10081483/49257496-4d057b80-f3e7-11e8-9d60-5f36fc241d96.png)

**Comment by craxal** [comment]
Not reproducible as of build 20181129.17.
