### ISSUE TITLE
Show a confused error message when inputting an empty property name for HNS blobs

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#923]
Storage Explorer Version: 1.5.0
Platform/OS Version: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
Architecture: ia32
Build Number: 20181129.6
Commit: 86486916
Regression From: Not a regression

#### Steps to Reproduce: ####
1. Choose one ADLS Gen2 account -> Open one blob container.
2. Right click one blob then select 'Properties...' -> Add a property then delete the default property name 'Property1'.
3. Check the error message.

#### Expected Experience: ####
There shows 'The property keys doesn't conform the naming conventions...'.

#### Actual Experience: ####
There shows 'Property keys cannot contain whitespace'.
![compare](https://user-images.githubusercontent.com/34729022/49208720-7a582680-f3f3-11e8-9e5d-6af11c17ac79.png)

**Comment by MRayermannMSFT** [comment]
Won't fixing this.
