### ISSUE TITLE
Replacing the conflicted blob doesn't prompt for refreshing when uploading an existing blob

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#924]
Storage Explorer Version: 1.5.0
Platform/OS Version: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
Architecture: ia32
Build Number: 20181129.6
Commit: 86486916
Regression From: Not a regression

#### Steps to Reproduce: ####
1. Expand one storage account with 'HNS Enabled = false'.
2. Open one blob container then upload one blob to it.
3. Upload the same blob again -> Select 'Replace' on the popped conflict dialog.
4. Check whether prompt for refreshing after replacing successfully or not.

#### Expected Experience: ####
Prompt for refreshing after replacing the blob successfully.

#### Actual Experience: ####
Auto refresh after replacing the blob successfully.

**Comment by v-limu** [comment]
This issue will no longer reproduces with the new search feature on build [20191128.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3280503&view=results). So we close it.
