### ISSUE TITLE
Capitalize for the displayed error message of metadata on Properties dialog

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#925]
Storage Explorer Version: 1.5.0
Platform/OS Version: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
Architecture: ia32
Build Number: 20181129.6
Commit: 86486916
Regression From: Not a regression

#### Steps to Reproduce: ####
1. Open one blob container with 'HNS Enabled = false'.
2. Right click one blob then select 'Properties...' -> Add a metadata with an invalid name.
3. Check the displayed error message on the dialog.

#### Expected Experience: ####
There shows 'Metadata: **Metadata** keys ......'.

#### Actual Experience: ####
There shows 'Metadata: **metadata** keys......'.
![capitalize](https://user-images.githubusercontent.com/34729022/49209848-97dabf80-f3f6-11e8-8b17-ac770a52e3a5.png)

**Comment by v-limu** [comment]
This issue has been fixed on build [20191106.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3218228&view=logs). So we close it.
