### ISSUE TITLE
New user gets wrong permissions when added in Manage Permissions dialog

### ISSUE THREAD

**Issue by craxal** [Microsoft/AzureStorageExplorer#927]
**Storage Explorer Version**: 1.6.0
**Platform/OS Version**: Windows 10
**Architecture**: ia32
**Build**: 20181129.17
**Regression From**: N/A

#### Steps to Reproduce: ####
1. Open the Manage Permissions dialog on an ADLS Gen 2 blob.
2. Add a valid user.
3. Enable Access and turn on Read permission.
4. Save and close the dialog.
5. Reopen Manage Permissions dialog. Select the added user.

#### Expected Experience: ####
User has Read permission.

#### Actual Experience: ####
User has Write permission.

**Comment by MRayermannMSFT** [comment]
This was fixed!
