### ISSUE TITLE
The Delete confirmation dialog for FileShare is not themed

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#929]
**Storage Explorer Version**: 1.5.0
**Platform/OS**: All
**Architecture**: All
**Regression From**: NYI

**Bug description**
The Delete confirmation dialog for FileShares is not themed

**Steps to Reproduce**
List the minimal steps clearly and concisely to reproduce the behavior:
1. Running Storage Explorer in the dark theme
2. Select a file share and try to delete one of the files

**Expected Experience**
The confirmation dialog should be themed to dark theme

**Actual Experience**
Not themed
![image](https://user-images.githubusercontent.com/10081483/49262186-3caacc00-f3fa-11e8-800f-6709601c8aa8.png)

**Comment by craxal** [comment]
This is a system dialog, and so the theming comes from the system, not the app.

**Comment by jinglouMSFT** [comment]
This is the only system dialog as far as i know in SE. why?

**Comment by MRayermannMSFT** [comment]
Fix merged into master
