### ISSUE TITLE
Double clicking fails to open .txt files

### ISSUE THREAD

**Issue by leftler** [Microsoft/AzureStorageExplorer#93]
**Storage Explorer Version:** 1.0.0
**OS Version:** Windows
**Architecture:** ia32
**Build Number:** 20180415.2
**Commit:** 5d603052

**Steps to Reproduce:**

1. Navigate to a file with the .txt extension
2. Double click to download.

**Expected Experience:**
The file is downloaded to the temp folder and is opened with my default viewer for .txt files (Notepad++)

**Actual Experience:**
I get the following message in my Activities log
> Failed to open 'INT-LabResultsApi/2018/04/06/15/afb338852ec7227ac269b1f8211ef69976b7dd324bb39cca9bae976603ac7f6c_applicationLog.txt': unknown

Clicking Details provides only the following in the text box.
> {}

This appears to only happen to .txt files, I tried with a .log file which is also associated with Notepad++ and that opened fine. Downloading the .txt file then manually double clicking on it in the folder works fine.

Attached is a copy of the dev tools console when the error happens with my access key redacted, line 65 contains the exception that was thrown.

[-1524755114343.log](https://github.com/Microsoft/AzureStorageExplorer/files/1951807/-1524755114343.log)

**Comment by MRayermannMSFT** [comment]
Hi @leftler , can you try to manually open the file that was downloaded as part of the open process? The path to it appears to be: "C:\Users\SCHAMB~1\AppData\Local\Temp\212…7dd324bb39cca9bae976603ac7f6c_applicationLog.txt".

**Comment by leftler** [comment]
Trying to open it from a command prompt I get
```
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

U:\>C:\Users\SCHAMB~1\AppData\Local\Temp\2129B3~1\1A9D2D~1\INT-LA~1\2018\04\06\17\AFB338~1.TXT
Access is denied.

U:\>C:\Users\schamberlain\AppData\Local\Temp\2129b340d9871c60427f119d150b1c669de1f9e7d961164d33f65c95c9d3ca23\1a9d2d18a9f75448e4eac03508f7e3d21f78049baffd5a7ca55bad2078f62ccf\INT-LabResultsApi\2018\04\06\17\afb338852ec7227ac269b1f8211ef69976b7dd324bb39cca9bae976603ac7f6c_applicationLog.txt
Access is denied.
```
 Looking at the permissions on the file show I should have the permissions to open it
![image](https://user-images.githubusercontent.com/1425499/39326380-69a8ae5c-495a-11e8-8161-3f47b9417324.png)

Copying the file to another location like the desktop allows me to open the file normally. My suspicion is this might be windows disagreeing with the length of the file path. Does `%Temp%\2129b340d9871c60427f119d150b1c669de1f9e7d961164d33f65c95c9d3ca23\1a9d2d18a9f75448e4eac03508f7e3d21f78049baffd5a7ca55bad2078f62ccf` really need to be that long for a temp folder?

**Comment by MRayermannMSFT** [comment]
Can you try opening a text file with a much shorter name? I want to verify that we're looking at a path length issue here before looking at changing that path generation.

**Comment by craxal** [comment]
Closing this bug as stale. If this continues to be an issue, please let us know, and we can reopen.

**Comment by craxal** [comment]
Does Excel open the file if you shorten the file name?

I agree. That's probably an excessively long path for a temp location. @MRayermannMSFT, where do we generate the temp location and how? Is there a way to shorten this?

[This page](https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file#maximum-path-length-limitation) contains some interesting information on path lengths. I notice particularly that character limits should be lifted in Windows 10 (though you have to opt into it somehow).

**Comment by MRayermannMSFT** [comment]
Yes, I know where the path is generated. The implementer of the function was trying to make sure the downloaded file would not overwrite one of the same name, but I think they were a bit over zealous...

Anyway, it sounds like @redwyre has confirmed this is a path issue. Let's reopen the bug and try to get it fixed.

**Comment by redwyre** [comment]
It does work if I shorten the path. Excel is the party at fault here, but unfortunately that's what I work with

**Comment by MRayermannMSFT** [comment]
Fix merged into hotfix branch.
