### ISSUE TITLE
upload using AzCopy doesn't include file name in Activity log

### ISSUE THREAD

**Issue by jinglouMSFT** [Microsoft/AzureStorageExplorer#930]
**Storage Explorer Version**: 1.5.0.20181129.17
**Platform/OS**: All
**Regression From**: Not clear

**Bug description**
When uploading individual file using AzCopy, the activity log message doesn't include the file name in the log. 

**Steps to Reproduce**
1. Turn on AzCopy in the Experimental menu 
2. Under a regular storage account and blob container, try to upload an individual blob
3. When upload completes, take a look at the activity log 

**Expected Experience**
I would expect to see the file name to be included in the activity log

**Actual Experience**
Only included directory information.
![image](https://user-images.githubusercontent.com/10081483/49262927-65809080-f3fd-11e8-821d-93a1139de9d4.png)

If AzCopy is turned off, we include the file name.
![image](https://user-images.githubusercontent.com/10081483/49262978-8943d680-f3fd-11e8-9edf-18c99ef3b184.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
