### ISSUE TITLE
Unable to expand Blob Containers node for attached ADLS Gen2 accounts with SAS

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#931]
**Storage Explorer Version:** 1.6.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number:** 20181130.7
**Commit**: 98b890fc
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Choose one ADLS Gen2 account ->Attach the account with SAS Connection string.
**Display name**: firstadlsacc
**SAS**: SharedAccessSignature=sv=2018-03-28&ss=bfqt&srt=sco&sp=rwdlacup&st=2018-11-30T08%3A56%3A28Z&se=2018-1205T08%3A56%3A00Z&sig=an35BnXuwzW%2B4xJVPVmRxIBiOS%2FWlA4PnL3UG%2FEvKME%3D;BlobEndpoint=https://firstadlsacc.blob.core.windows.net/;FileEndpoint=https://firstadlsacc.file.core.windows.net/;QueueEndpoint=https://firstadlsacc.queue.core.windows.net/;TableEndpoint=https://firstadlsacc.table.core.windows.net/;
2. Expand '**Local & Attached'** -> **Storage Accounts** -> '**firstadlsacc**' ->**Blob Containers**.
3. Check whether the Blob Containers node can be expanded successfully or not.

#### Expected Experience: ####
Succeed to expand Blob Containers node.

#### Actual Experience: ####
Unable to expand the Blob Containers node with the below error.
![incorrect](https://user-images.githubusercontent.com/34729022/49279921-ba86da00-f4c3-11e8-8cfe-504eee12b990.png)

**Comment by craxal** [comment]
We are not supporting SAS features for ADLS Gen 2 for 1.6.0.
