### ISSUE TITLE
The 'Upload Conflict' dialog pops up again after closing it directly

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#932]
**Storage Explorer Version:** 1.6.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181130.7
**Commit**: 98b890fc
**Regression From**: Previous release 1.5.0

#### Steps to Reproduce: ####
1. Expand one normal storage account with 'HNS Enabled = false'.
2. Open one blob container -> Upload one blob to it.
3. Upload the same blob to the blob container -> Close the popped 'Upload Conflict' dialog directly.

#### Expected Experience: ####
The 'Upload Conflict' dialog no longer pops up.

#### Actual Experience: ####
The 'Upload Conflict' dialog pops up again.

**Comment by jinglouMSFT** [comment]
Won't fix.  We do need to know what the user would want us to do before proceeding.
