### ISSUE TITLE
Remove the properties of soft delete from the attached ALDS Gen2 accounts 	

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#933]
**Storage Explorer Version:** 1.6.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181130.7
**Commit**: 98b890fc
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Choose one ADLS Gen2 account ->Attach the account with SAS Connection string.
**Display name**: firstadlsacc
**SAS**: SharedAccessSignature=sv=2018-03-28&ss=bfqt&srt=sco&sp=rwdlacup&st=2018-11-30T08%3A56%3A28Z&se=2018-1205T08%3A56%3A00Z&sig=an35BnXuwzW%2B4xJVPVmRxIBiOS%2FWlA4PnL3UG%2FEvKME%3D;BlobEndpoint=https://firstadlsacc.blob.core.windows.net/;FileEndpoint=https://firstadlsacc.file.core.windows.net/;QueueEndpoint=https://firstadlsacc.queue.core.windows.net/;TableEndpoint=https://firstadlsacc.table.core.windows.net/;
2. Expand '**Local & Attached'** -> **Storage Accounts** -> '**firstadlsacc**'.
3. Select Blob Containers node then check the Properties panel.

#### Expected Experience: ####
There is no properties on Blob Containers node.

#### Actual Experience: ####
There shows the properties of soft delete on Blob Containers.
![soft delete](https://user-images.githubusercontent.com/34729022/49280477-4b11ea00-f4c5-11e8-85dc-c710f1e41916.png)

**Comment by jinglouMSFT** [comment]
SAS attach for ADLS Gen2 is not supported in 1.6.0.  Only Name/Key attach will be supported.
