### ISSUE TITLE
The order of the blob properties are inconsistent between the non-leased and leased blob

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#934]
**Storage Explorer Version:** 1.6.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181130.7
**Commit**: 98b890fc
**Regression From**: Previous release 1.5.0

#### Steps to Reproduce: ####
1. Expand one normal storage account with 'HNS Enabled = false'.
2. Open one blob container which contains one blob at least.
3. Make sure the blob isn't leased then check the order of the blob properties.
4. Acquire lease for the same blob then check the order of the blob properties.
5. Compare these two results.

#### Expected Experience: ####
There shows a consistent order of the properties.

#### Actual Experience: ####
There shows an inconsistent order of the properties.
![order](https://user-images.githubusercontent.com/34729022/49280910-3eda5c80-f4c6-11e8-94ea-7c04d4947e71.png)

**Comment by MRayermannMSFT** [comment]
Agree there is a regression, but at the moment, won't fix it.
