### ISSUE TITLE
Can't remove all user properties for HNS blobs at the same time

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#935]
Storage Explorer Version: 1.6.0
Platform/OS Version: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
Architecture: ia32
Build Number: 20181130.7
Commit: 98b890fc
Regression From: Not a regression

#### Steps to Reproduce: ####
1. Expand one ADLS Gen2 account -> Open one blob container.
2. Right click one blob then select 'Properties...' -> Add some user properties then click 'Save'.
3. Reopen the Properties dialog -> Try to remove all added properties then click 'Save'.
4. Reopen the Properties dialog then check whether all user properties are removed or not.

#### Expected Experience: ####
 All user properties are removed.

#### Actual Experience: ####
All user properties still exist.

#### More info: ####
The removed user properties disappeared when trying to remove part of user properties.

**Comment by jinglouMSFT** [comment]
Removing one by one doesn't work as smoothly either.

**Comment by v-xianya** [comment]
Verified with build 20181204.3. This issue doesn't reproduce. Could you help to resolve it?

**Comment by MRayermannMSFT** [comment]
Doesn't repro anymore.
