### ISSUE TITLE
Can’t remove the value of system properties for HNS blobs

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#936]
Storage Explorer Version: 1.6.0
Platform/OS Version: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
Architecture: ia32
Build Number: 20181130.7
Commit: 98b890fc
Regression From: Not a regression

#### Steps to Reproduce: ####
1. Expand one ADLS Gen2 account -> Open one blob container.
2. Right click one blob then select 'Properties...' -> Input a value for one system property then save it.
3. Reopen the Properties dialog -> Try to remove the added value in step2 then click Save.
4. Reopen the Properties dialog -> Check whether the value is removed or not. 

#### Expected Experience: ####
The value has been removed successfully.

#### Actual Experience: ####
1. The value still exists.
2. There shows '_Successfully saved properties for path [blob_name]'_ in Activities.

**Comment by v-xianya** [comment]
Verified with build 20181204.3. This issue doesn't reproduce. Could you help to resolve it?

**Comment by craxal** [comment]
Related to #935. Waiting for more info.

**Comment by MRayermannMSFT** [comment]
Doesn't repro anymore.
