### ISSUE TITLE
Unable to connect to MAG account

### ISSUE THREAD

**Issue by sean-mullin** [Microsoft/AzureStorageExplorer#94]
**Storage Explorer Version:**
1.00
**OS Version:**
Win 10 1709
**Steps to Reproduce:**

1. Add Account
2. Select Azure US Government
3. Enter Credentials

**Expected Experience:**
Connect to subscription
**Actual Experience:**
being told credentials are wrong

**Comment by MRayermannMSFT** [comment]
Hi @sean-mullin , this is a known issue with 1.0.0, as a workaround you can do the following:

## Create a US Govt custom environment
1. Open connect dialog (plug icon)
2. Choose "Create Custom Environment" in the "Azure environment:" dropdown
3. Input "US Govt" as the "Environment name:" and `https://management.usgovcloudapi.net/` as the "ARM endpoint:"
4. Click "Sign in..."

Anytime you want to add another govt account, choose "Use Custom Environment" in the "Azure environment" dropdown, and use the "US Govt" environment. We've checked in a fix for this issue, so once 1.1.0 is released, you can go back to using the normal Azure US Government option in the first dropdown.

**Comment by MRayermannMSFT** [comment]
Closing as duplicate of #61
