### ISSUE TITLE
There shows a confused log message after deleting blob snapshots successfully

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#941]
**Storage Explorer Version**: 1.6.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181204.3
**Commit**: 6ae5640a
**Regression From:** Previous release 1.5.0

#### Steps to Reproduce: ####
1. Expand Blob Contains node under one normal storage account.
2. Open one blob container then upload a blob to it.
3. Create snapshots for the uploaded blob -> Go to Manage Snapshots of the blob.
4. Delete the created snapshots -> Check the log message after deleting successfully. 

#### Expected Experience: ####
There shows '**Deleted snapshots from** ...'

#### Actual Experience: ####
There shows '**Deleted blobs from** ...'.
![snapshots](https://user-images.githubusercontent.com/34729022/49431082-9a1e8e80-f7e7-11e8-9f3b-d2bfbfda5f9c.png)

**Comment by MRayermannMSFT** [comment]
Won't fix for now. We're ok with the more limited output.
