### ISSUE TITLE
Display 'File Properties' on a folder properties dialog

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/AzureStorageExplorer#942]
**Storage Explorer Version**: 1.6.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture:** ia32
**Build Number**: 20181204.3
**Commit**: 6ae5640a
**Regression From**:  Not a Regression

#### Steps to Reproduce: ####
1. Drill down from one storage account -> 'File Share' node  -> Open one file share -> Upload one folder into it.
2. Right click this folder -> Select 'Properties...'.

#### Expected Experience: ####
Display 'Folder Properties'.

#### Actual Experience: ####
Display 'File Properties'.
![image](https://user-images.githubusercontent.com/34729092/49431723-1a91bf00-f7e9-11e8-9c87-5125ed014704.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into hotfix branch
