### ISSUE TITLE
'Cancel' doesn't work when downloading/uploading blobs using AzCopy

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#943]
**Storage Explorer Version**: 1.6.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181204.3
**Commit**: 6ae5640a
**Regression From:** Previous release 1.5.0

#### Steps to Reproduce: ####
1. Make sure AzCopy is enabled under Experimental.
2. Choose one normal storage account -> Open one blob contains.
3. Try to upload a large file to the blob container.
4. Click 'Cancel' next to the log message when the activity is in progress.

#### Expected Experience: ####
The operation is canceled.

#### Actual Experience: ####
'Cancel' doesn't work.

**Comment by craxal** [comment]
Since this is AzCopy, and we have never supported cancelling with AzCopy, this is not a regression.

**Comment by MRayermannMSFT** [comment]
Fix merged into hotfix branch
