### ISSUE TITLE
'Connect' dialog doesn't auto appear when launching Storage Explorer without accounts added

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#944]
**Storage Explorer Version**: 1.7.2/20190312.3
**Platform/OS Version**: Windows 10
**Architecture**: ia32
**Regression From:** Not a regression

#### Steps to Reproduce: ####
1. Launch Storage Explorer -> Make sure there is no accounts added and no resources attached.
2. Re-launch Storage Explorer -> Check whether the 'Connect' dialog auto appears or not.

#### Expected Experience: ####
The Connect dialog auto appears.

#### Actual Experience: ####
The Connect dialog doesn't auto appear.

#### More info: ####
1. This issue doesn't reproduce on Mac.
2. We didn't verify this issue on Linux, because there is a block issue [1142](https://github.com/Microsoft/AzureStorageExplorer/issues/1142)

**Comment by MRayermannMSFT** [comment]
Nevermind, I figured it out.

**Comment by MRayermannMSFT** [comment]
Fix merged into hotfix branch

**Comment by v-xuanzh** [comment]
This issue reproduces on the latest build 20190312.3. So reopened and updated the configurations above.

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
