### ISSUE TITLE
Add quotes for the container's name on the log message after saving properties successfully

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#945]
**Storage Explorer Version**: 1.6.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181204.3
**Commit**: 6ae5640a
**Regression From:** Not a regression

#### Steps to Reproduce: ####
1. Choose one ADLS Gen2 account ->Right click one blob container '_xuanzhangtestblob1_'->Select 'Properties...'. 
2. Add properties for the blob container then save it -> Check the log message on Activities.

#### Expected Experience: ####
There shows 'Successfully saved properties for blob container **'xuanzhangtestblob1'**'

#### Actual Experience: ####
There shows 'Successfully saved properties for blob container **xuanzhangtestblob1**(_Lack of quotes for the name of the blob container_)
![quotes](https://user-images.githubusercontent.com/34729022/49433030-fedbe800-f7eb-11e8-8028-9838b1fe8203.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into hotfix branch.
