### ISSUE TITLE
Capitalize for Ok on 'Break Lease' dialog

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#946]
**Storage Explorer Version**: 1.6.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181204.3
**Commit**: 6ae5640a
**Regression From:** Not a regression

#### Steps to Reproduce: ####
1. Open one normal blob container -> Acquire lease for one blob.
2. Right click the leased blob then check the 'Break Lease' dialog.

#### Expected Experience: ####
Display '**OK**' on the dialog.

#### Actual Experience: ####
Display '**Ok**' on the dialog.
![ok](https://user-images.githubusercontent.com/34729022/49433531-42832180-f7ed-11e8-9f43-7a231804ea06.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into hotfix branch
