### ISSUE TITLE
There is slight delay when creating blob containers from ADLS Gens accounts

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#948]
**Storage Explorer Version**: 1.6.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181204.3
**Commit**: 6ae5640a
**Regression From:** Not a regression

#### Steps to Reproduce: ####
1. Choose one ADLS Gen2 account -> Try to create a blob container.

#### Expected Experience: ####
The created blob container shows on the tree view immediately.

#### Actual Experience: ####
Creating the blob container takes about 2 seconds.

**Comment by MRayermannMSFT** [comment]
Won't fixing this for now.
