### ISSUE TITLE
The 'Manage Access' dialog appears in the front of the opened web page after clicking 'Learn more about ACLs' action

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#949]
**Storage Explorer Version**: 1.6.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181204.3
**Commit**: 6ae5640a
**Regression From:** Not a regression

#### Steps to Reproduce: ####
1. Make sure the default browser is Edge and there is no web page opened.
2. Choose one ADLS Gen2 account -> Right click one blob container then select 'Manage Access...'.
3. Click the link '[Learn more about ACLs](https://docs.microsoft.com/en-us/azure/role-based-access-control/rbac-and-directory-admin-roles)' on the dialog.

#### Expected Experience: ####
The 'Manage Access' dialog appears at the back of the the opened web page.

#### Actual Experience: ####
The 'Manage Access' dialog appears in the front of the opened web page.
![front](https://user-images.githubusercontent.com/34729022/49434666-a73f7b80-f7ef-11e8-8ef9-7a32f24d893b.png)
#### More info: ####
1. There issue doesn't reproduce when there are web page opened on Edge. 
2. This issue doesn't reproduce on IE and Chrome.
3. The opened web page is unmatched.

**Comment by MRayermannMSFT** [comment]
@v-xuanzh , is the webpage stuck behind the dialog, or if you click on it, does it come forward?

**Comment by v-xuanzh** [comment]
Hi @MRayermannMSFT We still can do some actions on the dialog like change permissions, add user or group... But the web page still stuck behind the dialog.
