### ISSUE TITLE
Cannot locate the azure data lake file when tried to open the adl url in browser

### ISSUE THREAD

**Issue by jian1981** [Microsoft/AzureStorageExplorer#950]
**Storage Explorer Version**: In which Storage Explorer version was the bug encountered?
**Platform/OS**: Linux? macOS? Windows?
**Architecture**:
**Regression From**: Was this working in a previous version? If so, which one?

**Bug description**

When I tried to open a azure data lake resource link (e.g. adl://myaccount.azuredatalakestore.net/abc/def/2018/12/4/89dfe0d4c9464239accd5bf40056b343.zip) in browser, the explorer cannot locate the related folder. It was working previously.

**Steps to Reproduce**
List the minimal steps clearly and concisely to reproduce the behavior:
1. Open a azure data lake resource url in any browser, e.g. adl://myaccount.azuredatalakestore.net/abc/def/2018/12/4/89dfe0d4c9464239accd5bf40056b343.zip
2. The explorer can be opened automatically.
3. But it cannot locate the related folder.

**Expected Experience**
A clear and concise description of what you expected to happen. If applicable, add screenshots to help explain what you expected.

**Actual Experience**
A clear and concise description of what actually happens. If applicable, add screenshots to help explain what actually happened.

**Additional Context**

**Comment by ziyel** [comment]
@jian1981 , Thanks for your feedback.
Could you let me know which version of Azure Storage Explorer are you using?

And located to the related folder required:
1. You have login in the Azure Storage Explorer before;
2. The subscription contains the account need to be chosen in account setting. In your example link(`adl://myaccount.azuredatalakestore.net/abc/def/2018/12/4/89dfe0d4c9464239accd5bf40056b343.zip`), you need to choose the subscription contain the ADLS account `myaccount`.

**Comment by jian1981** [comment]
Thanks for reply.

The version I am using is 1.6.0.

Repro:
a) Open the adl url in the browser.
b) The explorer is opened automiatically.
c) The explorer displays a message: The subscription for this resource is currently filtered out. You need to select the subscription in the account settings panel to see the resource.

I can confirm all subscriptions are selected before I try to locale that file.

By the way, the folder we are trying to access contains large number of subfolders (40000), is it the possible reason?

Thanks again

**Comment by jian1981** [comment]
In addition, the search in the explorer also doesn't work. It seems it only can search the cached files/folders. Because in my case there are large number of folders, I cannot get the folder/file I need when I tried to use the search.

**Comment by ziyel** [comment]
@jian1981 Thanks for the information.
I have reproduced the issue.
Just want to make sure if this is the same case with yours.

Is your account belong to a subscription which contains many ADLS accounts?
In the first time you open Azure Storage Explorer, you have to click `Load more` to see the account?
![image](https://user-images.githubusercontent.com/1286176/49715527-adb87200-fc8b-11e8-9d1f-08c0247ac68d.png)

**Comment by jian1981** [comment]
Yes, it is. We have two dl account under the same subscription. 

By the way, the search feature in the Explorer for the data lake seems only search the cached files. Please do the fix as well for this. 

Thanks a lot.

**Comment by ziyel** [comment]
Thanks @jian1981.
Do you need to click `Load more` to load your account which you try to open with link in browser?

For the search feature, I will create a new issue to track it.

**Comment by jian1981** [comment]
Yes, we need to click "load more" to load the second account we need. Thanks.

**Comment by ziyel** [comment]
Thanks @jian1981 . Then it will be the same root cause with my reproduced steps. I'm working on the fix.

**Comment by ziyel** [comment]
Have create https://github.com/Microsoft/AzureStorageExplorer/issues/988 to track the search not work bug.
