### ISSUE TITLE
Verify that adding a group to a ADLS Gen2 ACL Works

### ISSUE THREAD

**Issue by MRayermannMSFT** [Microsoft/AzureStorageExplorer#954]
During the ADLS Gen2 bug bash, Jeff K. had issues adding an AAD security group. We should revalidate that adding groups works.

**Comment by tolandmike** [comment]
It's not working for me. Using v1.6.0

**Comment by MRayermannMSFT** [comment]
Fix merged into hotfix branch for 1.6.1. @tolandmike , 1.6.1 will be released next week. I'll share a private build with you if we have one earlier though.
