### ISSUE TITLE
Cannot upload file from a local OneDrive folder

### ISSUE THREAD

**Issue by dsghi** [Microsoft/AzureStorageExplorer#96]
**Storage Explorer Version:**
1.0.0

**OS Version:**
Windows 10 (1709 Build 16299.402)

**Steps to Reproduce:**
1. Select a file in a local synced OneDrive folder (From SharePoint Online Document Library)

**Expected Experience:**
Upload file

**Actual Experience:**
Upload fail

**Workaround**
Moved file to a local path (downloads) and upload worked normally.

**Comment by MRayermannMSFT** [comment]
Hi @dsghi , the cause of this issue is a bug in NodeJS. They [recently fixed the bug](https://github.com/nodejs/node/issues/12737), and we're now waiting on Chromium/Electron to use a version of NodeJS which has the fix, at which point we'll upgrade to that version of Electron. Until then, you'll need to move the file out of your OneDrive folder before uploading.

**Comment by steveesp** [comment]
+1 
How is this issue related to Chromium/Electron?

**Comment by craxal** [comment]
@steveesp Storage Explorer is built using Electron, and Electron integrates with a specific version of Node. We use that version of Node's APIs to access local files and upload to Azure. Electron has to publish an update in which they integrate with a newer version of Node wherein these issues are fixed. Then we have to update the version of Electron we use to get the fix.

**Comment by BrianMinister** [comment]
A few of workarounds are:

1. Copy files out of the OneDrive folder, and into a file that you have fill control over. IE: D:\FileTransfer
2. Download Red-Gate's Azure Explorer, which doesn't have this limitation, but doesn't have all of the features that we are used to for the storage explorer.
3. Get the paid version of Filezilla, which includes filestorage, and use it for uploads.

Not perfect options, but an ok collection triage solutions.

**Comment by dsghi** [comment]
I am using version 1.4.1 and this is now working for me.

**Comment by steveesp** [comment]
Ack, correct behavior confirmed. Thanks!
