### ISSUE TITLE
Missing selection statistics for gen2

### ISSUE THREAD

**Issue by thelazydogsback** [microsoft/AzureStorageExplorer#964]
**Storage Explorer Version**: 1.6.0
**Platform/OS Version**: win10 x64

It would be great to have the following when gen2 stats are supported:

-	Total number of files
-	Total number of directories
-	Max directory depth
-	Total size in bytes
-	Min/Avg/Max # of files per directory
-	Min/Avg/Max bytes per file

**Comment by samuda2019** [comment]
This is a basic feature missing in ADLS Gen2. It is very important to have this enabled. Please let us know the ETA on when it would be enabled.

**Comment by thelazydogsback** [comment]
To underscore why this is needed so badly especially here: When using Spark/Databricks it's pretty easy to get your partitioning wrong, leading to horrible performance.  For example, one can easily find oneself with a 100,000 directories in 4 levels, and only one or two files in each directory, rather than let's say 1000 directories at two levels with a few hundred files per directory. If the number of directories is within an order of magnitude of the # of files, it's can be a red flag.

Even better than just a static view, would be to emit events that contained these status over time.

**Comment by samuda2019** [comment]
@thelazydogsback I couldn't agree more.

**Comment by Robert-Kostecki** [comment]
Hi, this "feature request" (or bug depending how you read it) has been opened for nearly 21 months now, is there any plan for these to be added anytime soon please? 

Alternatively are you planning to fix "Azure Storage Explorer Folder Statistics missing in ADLS Gen2"[https://github.com/microsoft/AzureStorageExplorer/issues/1349](url) which was closed as a duplicate?

Can we please have updates on the timelines please?

**Comment by dazzag24** [comment]
This is a key missing feature.

**Comment by MikeWedderburn-Clarke** [comment]
+1

**Comment by mortenf** [comment]
+1

**Comment by MRayermannMSFT** [comment]
Selection and folder statistics for Gen2 are going to be included in 1.17. The feature has parity with the existing normal blob experience. That is: counts of number of and total bytes of active blobs.
