### ISSUE TITLE
Cannot update account credentials

### ISSUE THREAD

**Issue by vladbilyk** [Microsoft/AzureStorageExplorer#97]
**Storage Explorer Version:**
1.0.0
**OS Version:**
Platform: macOS
Architecture: x64
Build Number: 20180415.2
Commit: 5d603052
Support Id: ca79a3ff-0016-7bd0-8f06-ea5fa1529f0b

**Steps to Reproduce:**

1. I have 2 Azure accounts connected to the Storage Explorer (SE),
2. Once, SE has started to asks to reenter credentials for both accounts.
3. First account credentials was updated fine.
4. For the second account SE constantly shows the error: Unable to sign-in: Duplicate query parameter 'prompt' in extraQueryParameters
![screen shot 2018-04-27 at 10 27 31](https://user-images.githubusercontent.com/2409419/39350045-b3a77212-4a05-11e8-8c50-2ed62a77567b.png)

**Expected Experience:**
The second account credentials must be updated.

**Actual Experience:**
The second account credentials are outdated...

**Comment by craxal** [comment]
1.0.0 introduced a new component for managing sign-in credentials. In our release notes, we advise that you first sign out of your accounts then sign back in. Have you tried that yet?

**Comment by vladbilyk** [comment]
@craxal removing account and adding it back works fine... but I believe that second account was added on 1.0.0 version, anyway if the issue comes again I will inform you...

@MRayermannMSFT yep, I'm using VS for Mac

**Comment by craxal** [comment]
Awesome. If you encounter it again, we can reopen and investigate.

**Comment by MRayermannMSFT** [comment]
@vladbilyk , let me know if you run into the issue again. I know the cause and I know how to get you out of it. Thanks!

**Comment by mcetkovsky** [comment]
I have just run into the issue with an Azure AD account.
Unable to sign-in: Duplicate query parameter 'prompt' in extraQueryParameters

Version: 1.0.0

Platform: macOS
Architecture: x64
Build Number: 20180415.2
Commit: 5d603052
Support Id: cc1e9539-7af3-8377-627c-36d500960dc9

**Comment by MRayermannMSFT** [comment]
Hi @mcetkovsky , do you have a ~/.IdentityService/aadconfiguration directory (my casing of the directories may be wrong)?

**Comment by mcetkovsky** [comment]
Yes, I do. I have just a single file Inside the directory, called AadConfiguration.lock.

**Comment by mcetkovsky** [comment]
I've removed names, e-mails, some ids and logos.
[IdentityService 2-1.zip](https://github.com/Microsoft/AzureStorageExplorer/files/1975722/IdentityService.2-1.zip)

**Comment by MRayermannMSFT** [comment]
Yep, ok, looks like at one point you did have an Aad Configuration that you used to add that account to VS for Mac. Simply remove the account using either Stg Exp or VS for Mac, and then re-add it using Storage Explorer. You should be able to use the account that is then added in both Stg Exp and VS for Mac.

**Comment by mcetkovsky** [comment]
That worked. However, the solution is not very self-discoverable :)

**Comment by MRayermannMSFT** [comment]
Definitely not discoverable. I've added it to our known issues for the next set of release notes, so hopefully people see that. Our auth team is also working on a fix so this situation doesn't happen in the future. 😃
