### ISSUE TITLE
Upload of PST files v1.6.0 - Forbidden

### ISSUE THREAD

**Issue by joachimloe** [Microsoft/AzureStorageExplorer#970]
# 🛑 STOP! 🛑
Are you encountering issues? Do these things first before submitting a bug report:
- Check the [troubleshooting guide](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting) for common problems and solutions.
- Check the [release notes](https://docs.microsoft.com/en-us/azure/vs-azure-tools-storage-explorer-relnote) for known issues.
- If you need assistance, submit an [Azure support request](https://docs.microsoft.com/en-us/azure/azure-supportability/how-to-create-azure-support-request).

---

**Storage Explorer Version**: 1.6.0
**Platform/OS**: Windows / Windows Server 2008 R2
**Architecture**: ia32
**Regression From**: It worked with 1.5.0 and still does

**Bug description**
Uploading PST Files to the Azure Storage Blob provided by the Office 365 Import Service 

**Steps to Reproduce**
List the minimal steps clearly and concisely to reproduce the behavior:
1. Connect to the blob using "Shared Access Signature URI"
2. Open the "ingestiondata" blob.
3. select "Upload Files"
4. Upload starts and runs to 100%, then ends up with error code 403 forbidden.

**Expected Experience**
100% Successful upload

**Actual Experience**
100%, the failed with error code 403 Forbidden.
File is present in blob.

**Additional Context**
Uninstalled 1.6.0
Installed 1.5.0
Executed the same steps.
Upload of same file
Successfull Upload.

**Comment by MRayermannMSFT** [comment]
Fix merged into hotfix branch.

**Comment by Taomyn** [comment]
HI, sorry to bring this old issue up but I'm on v1.10.1 and have exactly the same problem and cannot upload any files to the container. Did the fix actually go into a release or am I missing something else and should be connecting in a different way? All I do is enter the SAS URI that the Office 365 gives me, and I know if I use AZCopy manually I can upload files, it's just not as convenient as using Storage Explorer.

```
2019/10/09 06:59:34 ERR: [P#0-T#0] UPLOADFAILED: c:///Temp/Annotation%202019-10-03%20101833.png : 000 : Could not check file existence. -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthorizationPermissionMismatch) =====
Description=403 This request is not authorized to perform this operation using this permission., Details: (none)
```

**Comment by jinglouMSFT** [comment]
@Taomyn do you have AzCopy enabled or not enabled when you tried to do the upload?

**Comment by Taomyn** [comment]
Yes it's enabled

![Annotation 2019-10-10 074625](https://user-images.githubusercontent.com/4365929/66542184-27cab900-eb32-11e9-983f-3918bc22b0aa.png)
