### ISSUE TITLE
Azure Storage Explorer upload error

### ISSUE THREAD

**Issue by BasilSAM1610** [Microsoft/AzureStorageExplorer#973]
**Storage Explorer Version**: 1.6.0
**Platform/OS Version**: Windows
**Architecture**: ia32
**Regression From**: No

#### Steps to Reproduce: ####
1. Attempt to upload a PST to blob container for upload into Office 365 online archive.

#### Expected Experience: ####
Upload Successful

#### Actual Experience: ####
Error.
[Error.txt](https://github.com/Microsoft/AzureStorageExplorer/files/2654945/Error.txt)

**Comment by craxal** [comment]
Duplicate of #970.
