### ISSUE TITLE
Not able to explore CosmosDB after updating

### ISSUE THREAD

**Issue by RecipeSavants** [Microsoft/AzureStorageExplorer#974]
**Storage Explorer Version**: 1.60
**Platform/OS Version**: Windows10
**Architecture**:  x64
**Regression From**:  in previous vesion i was able to view collecitons and details - in the new version i am unable to do so

![image](https://user-images.githubusercontent.com/32582201/49615147-3aa0ba00-f972-11e8-8704-31a8f5be691f.png)

#### Steps to Reproduce: ####
1. 
2.

**Comment by ziyel** [comment]
Duplicated with https://github.com/Microsoft/AzureStorageExplorer/issues/971

**Comment by MRayermannMSFT** [comment]
For anyone facing this issue, we're shipping a hotfix to fix this regression. Until then, if you'd like to preview the hotfix simply go to the "Help" menu on Windows and Linux/app menu on macOS ->" Opt in to Insider Builds" We'll still doing some final testing and a few other fixes, but we wanted to at least let people who needed the fixes we have done so far, have them. Thanks!
