### ISSUE TITLE
CosmosDb document viewer throws exception and shows a blank screen

### ISSUE THREAD

**Issue by Zettersten** [Microsoft/AzureStorageExplorer#977]
**Storage Explorer Version**: 1.6.0
**Platform/OS Version**: Window 10
**Architecture**: ia32
**Regression From**: This was working prior to the 1.6.0 update. Not certain on the previous version installed.

#### Steps to Reproduce: ####
1. Navigate to CosmosDb
2. Select a Database
3. Select a Collection
4. Click on Documents

#### Expected Experience: ####
Should have seen documents

#### Actual Experience: ####
Seeing a blank screen

![image](https://user-images.githubusercontent.com/183147/49688509-71e1a900-fae1-11e8-9ad2-52664c69eda5.png)

![image](https://user-images.githubusercontent.com/183147/49688511-77d78a00-fae1-11e8-9077-42c2d01c265a.png)

**Comment by Zettersten** [comment]
Duplicate of 971

**Comment by Zettersten** [comment]
Temporary hack got this working again for me:

Open > "C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\DataExplorer\built\Platform\Daytona\DaytonaContext.js"

Change this line:

`//this.subscription = JSON.parse(this.parameters.metadata.subscription);
this.subscription = this.parameters.metadata.subscription;`

**Comment by MRayermannMSFT** [comment]
For anyone facing this issue, we're shipping a hotfix to fix this regression. Until then you can either do the hack as Zettersten suggests, or if you'd like to preview the hotfix simply go to the "Help" menu on Windows and Linux/app menu on macOS ->" Opt in to Insider Builds" We'll still doing some final testing and a few other fixes, but we wanted to at least let people who needed the fixes we have done so far, have them. Thanks!
