### ISSUE TITLE
The message 'Showing properties for...' always shows after saving invalid properties for one ADLS Gen2 blob container

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#979]
**Storage Explorer Version**: 1.6.1
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181210.2
**Commit**: 4fed5a79
**Regression From**: Previous release 1.6.0

#### Steps to Reproduce: ####
1. Expand one ADLS Gen2 account -> Blob Containers node.
2. Right click one blob container then select 'Properties...' -> Add one property with an invalid value like '사용하면' -> 'Save'.
3. Check the log message on the Activities Window.

#### Expected Experience: ####
There is no message '_Showing properties for..._'on the Activities Window.

#### Actual Experience: ####
The message '_Showing properties for...'_ always shows.
![showsing](https://user-images.githubusercontent.com/34729022/49719942-9aac9e80-fc99-11e8-983a-bc4390e28bd1.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into hotfix branch.
