### ISSUE TITLE
Change the title 'Path Properties' to 'Blob Properties' on Properties dialog for ADLS Gen2 accounts

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#982]
**Storage Explorer Version**: 1.6.1
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181210.2
**Commit**: 4fed5a79
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Expand one ADLS Gen2 account -> Blob Containers node.
2. Open one blob container which contains one blob at least.
3. Right click one blob then select 'Properties...' -> Check the displayed title.

#### Expected Experience: ####
There shows '**Blob Properties**' on the Properties dialog.

#### Actual Experience: ####
There shows '**Blob Properties**' on the Properties dialog.

**Comment by MRayermannMSFT** [comment]
Let's just call it "Properties", ignore the issue of do we use the blob term or the adls gen2 term.

**Comment by MRayermannMSFT** [comment]
This still hasn't been merged. Reopening.

**Comment by MRayermannMSFT** [comment]
Ok, looks like this was merged, but the adls2 extension just needs updating.

**Comment by MRayermannMSFT** [comment]
Ok, it's all there now!
