### ISSUE TITLE
Cannot view the full display name with long characters on Detach confirmation dialog

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#983]
**Storage Explorer Version**: 1.6.1
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181210.2
**Commit**: 4fed5a79
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Attach one account with long display name(SAS or Key/Name) like below.
**Display name:** blobreadaccessblobreadaccessblobreadaccessblobreadaccessblobreadaccessblobreadaccessblobreadaccessblobreadaccessblobreadaccessblobreadaccessblobreadaccessblobreadaccessblobreadaccess
**SAS:** SharedAccessSignature=sv=2018-03-28&ss=bfqt&srt=sco&sp=rl&st=2018-12-10T09%3A04%3A54Z&se=2018-12-16T09%3A04%3A00Z&sig=QtxVp73EouIyRxMKNz9Q7oB5QjpcYzvJTIj1HwGdxkA%3D;BlobEndpoint=https://blobreadaccess.blob.core.windows.net/;FileEndpoint=https://blobreadaccess.file.core.windows.net/;QueueEndpoint=https://blobreadaccess.queue.core.windows.net/;TableEndpoint=https://blobreadaccess.table.core.windows.net/;
2. Right click the attached account then select 'Detach'.
3. Check whether the full display name shows on the Detach confirmation dialog or not.

#### Expected Experience: ####
The full display name shows on the Detach confirmation dialog.

#### Actual Experience: ####
We cannot view the full display name on the Detach confirmation dialog.
![detach](https://user-images.githubusercontent.com/34729022/49722149-fb8aa580-fc9e-11e8-8efb-ea88dac33281.png)

**Comment by MRayermannMSFT** [comment]
Won't fixing. Will reopen if customers provide feedback.
