### ISSUE TITLE
If a Custom Connection is Corrupted, Notify User, Don't Just Fail

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#985]
If a custom connection is corrupted, Storage Explorer fails to load anything in the tree. We should try to:

1. Fix the azure resource producer to not fail if loading custom connections fails
2. Catch corrupted connections earlier
3. Give better error messages for corrupted connections

**Comment by placidseven** [comment]
I have clients using 1.9.0 and the issue is still present. Has this bug fix not been committed yet?

**Comment by MRayermannMSFT** [comment]
We've checked in better handling for Storage Accounts as this is what we see people running into most. If people see it at the container level we can add the add'l error handling there as well.
