### ISSUE TITLE
Missing path name in activity message after deleting blobs from an ADLS Gen 2 subfolder

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#993]
**Storage Explorer Version**: 1.6.1
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181211.1
**Commit**: 2455da61
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Choose one ADLS Gen2 account -> Open one blob container.
2. Upload a folder which contains sub-folders to it-> Go to one sub-folder then upload a blob **_'test.txt'_** to it.
3. Delete _**'text.txt**_' from the sub-folder -> Check the log message after deleting successfully.

#### Expected Experience: ####
There shows a complete activities for the blobs deletion. 
![expect](https://user-images.githubusercontent.com/34729022/49791774-19720c00-fd6c-11e8-8854-aa66a47239d4.png)

#### Actual Experience: ####
There shows an incomplete activities for the blobs deletion.
![actual](https://user-images.githubusercontent.com/34729022/49791779-1d059300-fd6c-11e8-9cd3-03c264368938.png)

#### More info: ####
This issue doesn't reproduce for normal blobs.

**Comment by v-xuanzh** [comment]
This issue still reproduces on build 20190123.3. So reopened.

**Comment by craxal** [comment]
Please try again with a newer build. That build does not contain the changes.
