### ISSUE TITLE
Azure Blob - More granular control of upload throughput / number of threads / retry policies 

### ISSUE THREAD

**Issue by jiripik** [microsoft/AzureStorageExplorer#994]
**Storage Explorer Version**: Latest
**Platform/OS**: Windows?
**Architecture**: 64 bit
**Regression From**: Never worked properly.

**Bug description**
The Storage Explorer has no throughput control so if you are on a fiberoptics and try to upload tens of files, the app tries to upload as many in parallel as possible even well beyond the throughput of Azure Blobs. 

When that happens, the uploads start to fail, they are retried up to 5x and then the upload restarts from scratch.

The app should never try to upload more than is supported and should offer a choice of the number of parallel thread uploads and better retry policies.

**Comment by MRayermannMSFT** [comment]
@jiripik , are you using the experimental AzCopy feature or the standard upload/download?

**Comment by jiripik** [comment]
The experimental AzCopy features virtually always fail with an unknown error. 

I can use the Storage Explorer to upload only one file at the time, since each time I try to upload more, the throughput limit of the blob is exceeded and then all the hell breaks out.

**Comment by MRayermannMSFT** [comment]
Ok. I can definitely understand that frustration. As you already know, we don't currently let you customize upload speed or how many uploads we do in parallel. Though we are aware that being able to customize those is a very much sought after feature! What I can do for you today is tell you how to manually configure the number of uploads. Here's what you need to do:

1. Open your favorite text editor (as Admin if on Windows)
2. Open <install location>\resources\app\out\app\renderer\providers\WorkerManagerProvider.js, if you're not on Windows, the path will be slightly different, let me know if you need help finding it.
3. Look for the line:
```js
"upload": createPool(5, 1),
```
4. Change the `5` to however many parallel uploads you want
5. Save the file
6. Start the app

**Comment by jiripik** [comment]
THANK YOU. 

Please let me know once this feature is implemented and I will be most happy to test it out!

**Comment by JasonYeMSFT** [comment]
This is a part of the work of #1147.
