### ISSUE TITLE
Unable to get permissions for ADLS Gen2 blob containers

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#997]
**Storage Explorer Version**: 1.6.1
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181211.1
**Commit**: 2455da61
**Regression From**: Previous release 1.6.0

#### Steps to Reproduce: ####
1. Expand one ADLS Gen2 blob container -> Blob Containers node.
2. Right click one blob container then select 'Manage Access...'.

#### Expected Experience: ####
The 'Manage Access' dialog pops up.

#### Actual Experience: ####
Unable to get the permissions for the blob container.
![get_permission](https://user-images.githubusercontent.com/34729022/49855613-bdb98880-fe28-11e8-99d7-a768d618f20b.png)

#### More info: ####
This issue doesn't reproduce on blob files/blob folders from one ADLS Gen2 account.

**Comment by craxal** [comment]
Is there a Details... action associated with the failed activity? What permissions do you have on the blob container in question? Do you have the right roles to read and edit ACLs?

**Comment by v-xuanzh** [comment]
This issue doesn't reproduce on build 20181213.1. Could you help to resolve it?

**Comment by MRayermannMSFT** [comment]
Sure.
